### ISSUE TITLE
Tap on Return adds new line to input instead of sending a message [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1000]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: on iOS user sends a message by tapping on Return. As a result, message is not sent but new line is added into input field. For example: 
line1: where is 
line2: my text
If user taps on send icon then only first line is sent ("where is"), second line is not sent. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When user taps on Return in keyboard then message is sent
#### Actual behavior
[comment]: # (Describe what actually happened.)
When user taps on Return then message is not sent but new line is added. If tap on send icon then onli first line is sent
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video; https://drive.google.com/open?id=0Bz3t9zSg1wb7aDZpZDRVby1fclk
- Open Status and login
- in 1-1 chat type "line1: where is my text"
- On device keyboard tap on Return
- Type "lien2: is it sent"
- Tap on send icon

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: .0.9.6d38
* Operating System: iOS

**Comment by alwx** [comment]
Fixed in #1009
