### ISSUE TITLE
Ens name of other users overwritten when they recover

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#10004]
# Bug Report

## Problem

Ens name is still overwritten by no ens name: if A set up ens name X and is known as name X by B, when A recovers the account but not the his username X, and starts sending messages that are visible by B, B will start seeing A as its random name again, losing the knowledge of A username 
An overview of the background required to understand the problem.

#### Expected behavior

B still sees A as X

#### Actual behavior

B sees A as his random usernaname

**Comment by yenda** [comment]
@cammellos could you look into that?

**Comment by flexsurfer** [comment]
i think this can't be reproduced, to reproduce you should start new chat by ens name
