### ISSUE TITLE
Do not allow to register ens name from reserved names list

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10000]
# Feature Issue

It's possible to register reserved ens name,  and then later anyone can slash this name and get your deposit

### User Story

As a user i want to be aware of what names are reserved and can be slashed

Reserved names: https://github.com/status-im/ens-usernames/blob/master/config/ens-usernames/reservedNames.js

**Comment by hesterbruikman** [comment]
Added state in case a username is entered that is on the list:  

"ens-username-reserved": "Username not available :( [Check ](https://github.com/status-im/ens-usernames/blob/master/config/ens-usernames/reservedNames.js)if the name is reserved to protect against scams",

cc @andremedeiros 

@errorists please check if you're ok with this update to ENS name validation in this magical issue #10000

The link is a barebones view on Github. I think it's fine for V1 and can be updated later. Don't expect this validation to come up often.

**Comment by errorists** [comment]
🤧🤧10000🤭😯😦😧😮😲🤯

**Comment by rachelhamlin** [comment]
Was chatting with Jarrad about [this](https://discuss.status.im/t/how-to-deal-with-reserved-ens-usernames/1530/3) and he also thinks it's unwise for Status to be policing anything. Let's do away with the reserved names list in the next migration? 

@3esmit @yenda I will create an issue.
