### ISSUE TITLE
Can't login to account `sql: no rows in result set`

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10002]
# Bug Report

## Problem

No clear reproduction so far but I keep here some notes for now:

I've got this state while testing RC11. And at the same time on both iOS and Android, can't reproduce now on Android (kept logcat and kept the build with such 'sick' account on iOS)
Last actions before issue occured:

- I had ~4 accounts already existing in apps (both Android and iOS)

1) Android created new account (UserA). Back up seed phrase (it was  this one `cloud mesh pyramid kidney rubber winner lounge system reject weird picnic ride`). Android switch to Ropsten and received ETHro and XLS from different account
2) iOS creates one more new account (UserB). Back up seed phrase (it was `system remain polar salad couch dwarf churn tourist depend answer intact minute`). iOS switched to Ropsten and received XLS from different account
3) iOS recovers UserA
4) Android recovers UserB
5) iOS recovers UserB and Android recovers UserA (their first accounts they back up)

Now when I login to account which was recovered in 3rd and 4th steps on respective device, - I get `sql: no rows in result set` error.
If I try to login to any other account - I get the same error, until I restart the app. In that case I can login to "healthy" accounts.

#### Expected behavior

Can login to account

#### Actual behavior

Can't login to account `sql: no rows in result set` 

<img width="298" alt="Screenshot 2020-02-07 at 22 26 54" src="https://user-images.githubusercontent.com/8749671/74063375-f76c2c00-49f8-11ea-8731-1c2c3786bde7.png">

### Additional Information

- Status version: RC11
- Operating System: Android and iOS

#### Logs

[logcatNoRowsInResultSet.log](https://github.com/status-im/status-react/files/4172851/logcatNoRowsInResultSet.log)

 of device when I try to login to sick account

``` 
02-07 20:14:17.518 27678 27718 D StatusModule: clearCookies
02-07 20:14:17.519 27678 27718 D StatusModule: clearStorageAPIs
02-07 20:14:17.520 27678 27718 D StatusModule: login
02-07 20:14:17.521 27678 27729 D StatusModule: Signal event: {"type":"node.login","event":{"error":"sql: no rows in result set"}}
02-07 20:14:17.522 27678 27718 D StatusModule: Login result: {"error":""}

```

**Comment by Serhy** [comment]
I'd blame the recovering same account twice, but that's not the case

**Comment by rachelhamlin** [comment]
Does restarting the app also allow you to log in to the accounts in question @Serhy?

**Comment by Serhy** [comment]
No. For the particular account I created (or re-recovered) I can't login even after restart. But all the rest multiaccounts are fine. 
It seem may be connected to recover, because before I could re-login when receiving funds, and if so - user won't loose funds (because recovery phrase stored).

I'm trying to reproduce it now

**Comment by rasom** [comment]
I can't reproduce the issue

**Comment by Serhy** [comment]
I can't reproduce it as well now, tried steps from description, various re-logins/changing network and recovering already existed account, - no 'no rows in result set' error (error apparently says that account failed to be stored in db, maybe that happened when I recovered account and node was not running or something like that)

**Comment by Serhy** [comment]
Finally, I reproduced it. 
That's indeed connected to recover of the same account.

**Comment by Serhy** [comment]
Really edge case. 
When we recover same account (which is different issue I'll create) node fails to start. But I still can log out of that account. If I log out and create or recover another accounts in the same app session - they, if I'm correct, fail to be stored in DB and thus no way to log in later. 
Root cause here is to recover the same  account already existing, then log out (not via app restart) - and then create or recover different account. 

Reproduction:
1) Open fresh Status build and recover `cloud mesh pyramid kidney rubber winner lounge system reject weird picnic ride`
2) Restart app (or log out)
3) Recover the same account ( `cloud mesh pyramid kidney rubber winner lounge system reject weird picnic ride`) 
4) Once you on Chats home view -> `Profile` -> `Log out` 
5) Create or recover different account (`system remain polar salad couch dwarf churn tourist depend answer intact minute`)
6) Restart the app and try to login to account created in 5th step
**Actual result:** Can't login to account sql: no rows in result set

**Comment by rasom** [comment]
@Serhy would be great if we write aoutotest for recovering existing acc

**Comment by Serhy** [comment]
Autotest has been created. Will merge along with other fixes in separate PR
