### ISSUE TITLE
Chat view is broken its not possible to scroll messages

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10003]
# Bug Report

## Problem

Chat view is broken its not possible to scroll messages

#### Expected behavior

Chat view works smooth, its possible to scroll

#### Actual behavior

Have an opened public chat with messages, and open it next day and receive lots of new messages, start scrolling, first it started to jiggle while scrolling, when it was white with no messages, and then only today titles like 100 scrolled

Important thing app and chat should be opened when you open app from background

Steps
1) Open chat #status
2) Receive a bunch of messages
3) Put the app in background (without closing the app)
4) Wait for a day
5) Open the app, receive new messages
6) Scroll up?

VIDEO: https://drive.google.com/file/d/1HuJDWLvMzVZDp2g6zRhz78-0bJz0AnYW/view?usp=sharing

**Comment by flexsurfer** [comment]
probably fixed with offloading messages

**Comment by cammellos** [comment]
@flexsurfer is this still an issue or can be closed?

**Comment by flexsurfer** [comment]
haven't seen it , can be closed probably
