### ISSUE TITLE
NFC status (enable/disabled) is checked only before a keycard flow

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#10011]
Problem: 
Currently  NFC check is done only before navigation to screens which need NFC. If the user enables it using quick access sheet, while screen with "Turn on NFC" the app does not react to that. User should close/move to bg and open app again to see NFC changes.

Solution:
 It should be a listener as other checks like internet conenction

**Comment by rasom** [comment]
@guylouis can you please provide steps to reproduce the issue?

**Comment by rasom** [comment]
> - another case I have where NFC listening is not working properly (corner case ok): nfc is on, I go to login screen>...>generate a new key>generate keys>choose a name>keycard>begin setup>"Hold card to the bazck of your phone to start"-> If here I turn NFC off, then I don't have any more a warning that NFC is off and needs to be turned on while I try to tap my card

**Comment by rasom** [comment]
https://cdn.discordapp.com/attachments/626364653890437140/674950507617583119/20200206_151145.mp4
