### ISSUE TITLE
Pressing chat tab when in a chat should go back to chat list

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#10014]
A few users already requested a QoL improvement regarding behavior of the chat tab. When a user is in a chat, the desired behavior for the chat tab button is not to do nothing but to redirect to the chat list.

**Comment by flexsurfer** [comment]
i would say all tabs should lead to main screen, same for browser and profile

**Comment by rachelhamlin** [comment]
What chat tab button do you mean? The name of the chat at the top?
