### ISSUE TITLE
Numeric keyboard is not shown for /send, /confirmation-code [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1002]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Usual text keyboard instead of numeric keyboard is shown for commands /send and /confirmation-code
![confirm code](https://cloud.githubusercontent.com/assets/6584810/25041700/17c893d4-2112-11e7-82c1-3e8252dfda42.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Numeric keyboard is shown when user selects commands /send, /confirmation-code (as it done in 0.9.4)
#### Actual behavior
[comment]: # (Describe what actually happened.)
Text keyboard is shown when user selects commands /send, /confirmation-code
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- Provide phone number is console
- Tap on message "Thanks we've sent you a text message with a confirmation code..". As a result, command  /confirmation-code is shown with keyboard (issue: keyboard is not numeric)
- In 1-1 chat tap on /send command. As a result, command  /send is shown with keyboard (issue: keyboard is not numeric)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.5-38-gdd2c3aa+
* Operating System: iOS 10.3.1 (iPhone 7 plus) and Android 7.0, real device Samsung Galaxy S7

**Comment by alwx** [comment]
Fixed in #1008
