### ISSUE TITLE
Link invite Friends to join.status.im/user/...

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10028]
# Problem
Provide user's invited to Status a more direct way to download and install Status as well as find friends.

We've revamped the 'web2' user profile page https://join.status.im/user/0x04f1ab965a3db6433923ceba0488ff605f230aca4c4c93bb6563c10b700cfdbbed2a364c980b9cf9679f352584d4da44cc01fc1e7257f1d2b80ffff5af64aa129f

This page is already being linked to from: `Profile`  >`Share button`

## Implementation
- Url from `Chat` > `Invite friends` button must include full url (i.e. including join.status.im)
- Url from `+ - button` > `Invite friends` must include full url (i.e. including join.status.im)
- QR code of profile share must include full url (i.e. including join.status.im)

## Notes
- Invite friends links to https://join.status.im/user/
- In case of ENS https://join.status.im/user/<ens name>
- In case of random name https://join.status.im/user/<chat key>

## Future Steps
- Fix QR code reading ENS https://github.com/status-im/status-react/issues/10017
- Tweak page styling https://github.com/status-im/universal-links-handler/issues/23
- Investigate compressing Chat key to reduce QR code size

**Comment by hesterbruikman** [comment]
fyi @flexsurfer @jakubgs updated this issue to include using the full join.status.im url in QR code

Do you know if it's intended/why we use https://join.status.im/user/hester.stateofus.eth instead of https://join.status.im/user/hester instead of ENS name? Is it that we need it the domain in case the user does not use a stateofus.eth domain? If so, we'd want to update our hint text in `+ - button` > `New chat`

**Comment by jakubgs** [comment]
The actual URL should be `https://join.status.im/u/${USER}`.

**Comment by hesterbruikman** [comment]
fixed
