### ISSUE TITLE
Implement Intent Filter for Android to open links

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#10029]
# Feature Description

Opening a https://join.status.im/user/jakubgs should open the user profile view in the Android app.
Same should go for https://join.status.im/chat/public/status.

Right now it only provides a QR code we can scan and a download link.

# Details

As the web browser has no way of detecting if the app is installed or not the only way to automatically handle the URL is via Android Intent Filters.

Intent filters allow Android to figure out what an App should do with a specific URL:
https://developer.android.com/guide/components/intents-filters
You can see an example of that in this StackOverflow answer:
https://stackoverflow.com/a/12901352

**Comment by Ferossgp** [comment]
Hey! @jakubgs we already have it in code https://github.com/status-im/status-react/blob/develop/android/app/src/main/AndroidManifest.xml#L56-L62 
Open in app in browser:
![photo_2020-02-19 17 52 02](https://user-images.githubusercontent.com/5794620/74845809-93bef880-5340-11ea-8377-d020d83a631b.jpeg)
Open link:
![photo_2020-02-19 17 52 05](https://user-images.githubusercontent.com/5794620/74845816-9588bc00-5340-11ea-9312-4d1d75bddc28.jpeg)

And it opens the user profile. One possible problem is that it Clojure we handle only links which starts: `https://join.status.im`

Unfortunately, now we show only download the app and we do not have open in the app button on the website, I think it was before.

**Comment by jakubgs** [comment]
Oh, that's good to know. But I guess we can improve it. As far as I know there is no way to detect if app is installed from a browser, so to display a link that goes to the app we'd need to change the intent filter.

Maybe we could change the intent filter to react only to `https://join.status.im/click/*` or something like that? So when you go to https://join.status.im/chat/public/status, the button under the QR code leads to https://join.status.im/click/chat/public/status so tapping it takes you to the app.

**Comment by jakubgs** [comment]
Oh I see, we have an intent filter for `status-im://` defined here:
https://github.com/status-im/status-react/blob/c995174a22e2fd8d45208ae2ba4ce359ba8f31f4/android/app/src/main/AndroidManifest.xml#L67
But how does it work tho? Maybe we could modify the `join.status.im` site to make the button under the QR code to link using the `status-im://` scheme if it detects Android based on `User-Agent` header.

But what is the format of `status-im://`? I'd expect it to work the same as https://join.status.im/, so:

https://join.status.im/chat/public/status should work the same as `status-im://chat/public/status`.

**Comment by jakubgs** [comment]
Okay, I created https://github.com/status-im/universal-links-handler/pull/27. I tested it locally with my Android phone and it seems to work. Though I'm not sure how it will be have when it's hosted under `joint.status.im` domain.

**Comment by Ferossgp** [comment]
@jakubgs yes `status-im://` and join.status.im are handled the same way because of regexp which handles it: https://github.com/status-im/status-react/blob/develop/src/status_im/utils/universal_links/core.cljs#L24

**Comment by jakubgs** [comment]
@Ferossgp wouldn't this mean that the format of QR codes should also be that of `status-im://`?

**Comment by Ferossgp** [comment]
@jakubgs for that I'm not sure what's the best practice. This for sure will be helpful to open the app by reading QR with an external QR code reader. But if we do that we should also allow in-app QR code to handle it. I think there is a task in backlog assigned to me, I can do it soon.

**Comment by cammellos** [comment]
Looks like the description is outdated, as my understanding is that those cases are handled (I tested it on my phone on 1.7 and works as expected), closing this, feel free to re-open with an updated description if necessary.
