### ISSUE TITLE
Outgoing transaction message is not replaced correctly after being signed

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#10030]
# Bug Report

## Problem

I sent 3 tx requests from acc1 to acc2 and then signed all three requests on acc2. In result there are 4 transaction messages on acc2. After re-login only 3 tx messages are left on acc2.

acc1:
<img width=320 src=https://user-images.githubusercontent.com/2364994/74242369-722d9380-4ce6-11ea-952f-279430910bd0.jpg />

acc2(before re-login):
<img width=320 src=https://user-images.githubusercontent.com/2364994/74242407-840f3680-4ce6-11ea-8659-c9d54293dd6b.jpeg />

acc2(after re-login):
<img width=320 src=https://user-images.githubusercontent.com/2364994/74242460-a0ab6e80-4ce6-11ea-8bec-cac537b7ed52.PNG />

 
 

#### Expected behavior

 signed tx message is properly confirmed without duplication

#### Actual behavior

tx message can be duplicated after signing

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

prise steps to be defined, but that's how I got it:

- send 3-4 tx requests from acc1
- sign them on acc2

**Comment by churik** [comment]
Issue is not reproducible on release 1.13
