### ISSUE TITLE
ENS search is case sensitive, or so it seems.

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#10039]
# Bug Report

It seems as though the ENS search is case sensitive. When the starting letter is capital names are not found and I cannot start a chat.

ENS however defines that names should be lowercased automatically.

#### Expected behavior

Lowercase automatically when searching for names.

This seems to only happen on the iPhone 10

**Comment by 3esmit** [comment]
Just for context... ENS names are always registered lowercase, this is also enforced by slashing conditions, but it don't make any sense to register an upper case username because no one will able to access it (as software auto lowercase before checking).

**Comment by rachelhamlin** [comment]
Whoops, yeah, looks to be the case for me too. Thanks @decanus @3esmit

**Comment by StatusSceptre** [comment]
Neither yenda nor I can reproduce, and haven't heard reports. So I will close for now.

**Comment by rachelhamlin** [comment]
After a chat with @yenda, we'll actually make a small improvement and simply lowercase any caps the user enters.
