### ISSUE TITLE
EIP-747 wallet_watchAsset Interface support for Dapps

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10036]
# Feature Issue

If you navigate through a token page in etherscan.io, there will be a link there for "Add Token for Web3 Wallet", which works fine in MetaMask, but not in Status.

### User Story

As a user I want to easily watch a token from a DApp.

As a dapp developer I want to ask users to watch a token in their wallet.

### Description

Token Lists are not good enough. They provide a nice method for scanning user wallet for value.
However, they have to be updated everytime, and fast, by the developer team, because new tokens are being created everyday, and some DApps, like CirclesUBI have a different token for each user (so list are not effective here)
It's common to new users in Status willing to buy the next hot food token, which just released. And than they need to wait for Status for go through pasting some crazy address in a settings menu - not the best UX. 

While Status provides a option to add custom tokens, this might be too complicated or misused in some way, being a more advanced feature to use in Status.
EIP 747 helps with this problems by allowing a DApp to request the add of a new token. 

Status can't solve this problems alone, but it can provide the necessary features to developers requesting add of token in their token page. 

### Security Considerations

- EIP 747 popup should only be triggered by direct user action!
- Users must be warned that the data being included in the token list is arbitrary. therefore might be false. 
- EIP 747 can never overwrite existing values in the list, if a token address have some decimal/symbol, this can only be changed through settings. 
- EIP 747 can never reuse existing symbols in the list, if another token address have the same symbol, the user is requested to name it with something else, or the request is denied. 
- EIP 747 should never register a URL. The image must be either a contenthash (decentralized storage) or while being added by user, downloaded from a provided URL and saved on local storage. 

### Acceptance Criteria

DApp (Browser) can request add token to list.

### Links

https://eips.ethereum.org/EIPS/eip-747

**Comment by 3esmit** [comment]
In etherscan.io
![image](https://user-images.githubusercontent.com/224810/74423083-6e0c8d80-4e2e-11ea-8d8e-b7e22ae3ddc7.png)

In metamask this appears when 'Add Token for Web3 Wallet' is pressed:

![image](https://user-images.githubusercontent.com/224810/74423036-5cc38100-4e2e-11ea-8dae-13699e80c88d.png)

**Comment by 3esmit** [comment]
@hesterbruikman community is requesting it https://twitter.com/FrancescoRenziA/status/1317066525514358786

**Comment by hesterbruikman** [comment]
Crosslinking #11124 . There's a dependency to the token list we use and how it's maintained

**Comment by Ferossgp** [comment]
`EIP-747` specifications allow the caller to set assets as an image link. This could be a Privacy problem in case the server which distributes the image will use that image as a "Web Beacon" tracking. I think this could be handled by us differently from specification, or we can propose changes to spec to ensure privacy.

**Comment by 3esmit** [comment]
Implementation discussion: https://ethereum-magicians.org/t/eip-747-wallet-watchasset/1048

**Comment by danfinlay** [comment]
I totally agree that a CID is better, so if you want to go that path, my request would be that Status implements a version that can be compatible with the current http-based method that MetaMask is using.

For example, maybe just a type prefix for the `image:string` parameter:
```javascript
ethereum.request({
    method: 'wallet_watchAsset',
    params: {
      type: 'ERC20', // Initially only supports ERC20, but eventually more!
      options: {
        address: tokenAddress, // The address that the token is at.
        symbol: tokenSymbol, // A ticker symbol or shorthand, up to 5 chars.
        decimals: tokenDecimals, // The number of decimals in the token
        image: `cid:${CID}`, // By adding a type prefix, we can differentiate this type of image from a URL, and support both while migrating and suggesting the more secure approach.
      },
    },
  });
```

This would allow you to only support `cid:` if you want, and MetaMask can then introduce compatible support with yours and recommend that approach instead.

**Comment by danfinlay** [comment]
Oh, one more proposed improvement to EIP-747 to facilitate cross-format support (and graceful migration):

I propose the type of the `image` param is `string | string[]`:
- If the param is a `string` it will use the segment before the `:` to identify the content type.
- If the param is a `string[]`, the user's wallet MAY prefer the earliest listed item it is able to retrieve. (Or prefer another format per user preference)

Loosely based on email MIME-types, which allow graceful fallbacks between locally supported view methods.

I'll get this added to the EIP and MetaMask if you agree. Should be a very simple change.

**Comment by df257** [comment]
I want add two token together，how to do it?
![image](https://user-images.githubusercontent.com/7835444/143228349-712f25b5-f9b0-46f4-ab4c-27c45dae8806.png)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
