### ISSUE TITLE
in onboarding, when user defines the keycard PIN passcode, he's proposed a 'cancel button'

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#10032]
in onboarding, when user defines the keycard PIN passcode, he's proposed a 'cancel button'

![Screenshot_20200212-121325](https://user-images.githubusercontent.com/11461437/74330191-87133100-4d91-11ea-96d1-bc8719f35422.jpg)

when he types 'cancel' he gets a dangerous operation warning. It's not necessary and should be replaced by a back button

see logic here https://miro.com/app/board/o9J_kvIXxoU=/

**Comment by guylouis** [comment]
01/12/2020 this issue is still relevant 
see the dangerous operation screen that is shown here : 
![image](https://user-images.githubusercontent.com/11461437/100765818-37712500-33f8-11eb-9c99-451800754326.png)

**Comment by bitgamma** [comment]
@guylouis is the dangerous operation warning needed anymore at any step of the setup? Even if we cancel after pairing, the pairing is stored and not wasted. Also since we have factory reset it is not really dangerous, you can always reset. My proposal is to completely remove this warning, wdyt?

**Comment by bitgamma** [comment]
as discussed in the call, the warning will be removed altogether
