### ISSUE TITLE
Register ETHDenver Bufficorn

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#10042]
# Problem

Let's add the Bufficorn as a sticker pack for ETHDenver 2020, kicking off today!

## Implementation

Register sticker pack using these images:

https://www.dropbox.com/sh/p00gc1qpvxgk5hf/AAAmcrv50r5Nuv-dKt6iuWxZa/ETHDenver?dl=0&subfolder_nav_tracking=1

(Banner, icon, and stickers are in one folder)

## Acceptance Criteria

Pack title: ETHDenver Bufficorn
Artist: ETHDenver
Price: Free
Wallet: ------

cc @j-zerah - any idea who made these stickers? I shot ETHDenver a FB message, hoping to hear more.

**Comment by flexsurfer** [comment]
done
