### ISSUE TITLE
App crash after upgrade nightly (with Keycard acc) on to Release (no keycard support)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10045]
# Bug Report

## Problem

In nightlies we support keycard accounts. If user upgrades successfully from such build with keycard on to Release build (with no keycard) app fails right on start with `Can not read property 'params' of undefined` error, so no way to proceed use the app. 
Re-upgrading on to nightly (with higher version than release) again fixes the problem.
For now it's edge case, because its need to be:
1) Nightly version before 1.0.1 release 
2) Upgrade to Release 1.0.1
In other cases (using nightly version > 1.0.1 release) it's downgrade which wan't work. 

That's what happened to @Ferossgp when his nightly build with keycard autoupdated to 1.0.1

#### Expected behavior

Not sure actually what is expected...:) Upgrade made on build having no core feature (I mean no keycard support). @rachelhamlin @errorists ? It's not so far from theory that users who would like to use keycard will install nightly and in the next days Release version without keycard come up with described problem 
#### Actual behavior

After upgrade open app and...
<img width="442" alt="Screenshot 2020-02-14 at 14 22 45" src="https://user-images.githubusercontent.com/8749671/74531524-89ae8b80-4f35-11ea-82cc-5bfec8f04afc.png">

### Reproduction

- Install nightly version < 1.0.1 Release version (e.g. https://status-im.ams3.digitaloceanspaces.com/StatusIm-200205-025959-76f970-nightly-universal.apk)
- Open Status and create new account with Keycard
- Upgrade Status to `Release 1.0.1` (from Play Store)

### Additional Information
- Status version: Any build without keycard support
- Operating System: Android (keycard only on Android for now)

#### Logs
[Status.log](https://github.com/status-im/status-react/files/4204424/Status.log)

**Comment by Serhy** [comment]
After all if one see this error it's possible to upgrade to nightly version > Release version and proceed with account, so it's not a dead lock.

**Comment by churik** [comment]
suppose it can be closed
