### ISSUE TITLE
Status mobile application privacy policy

### ISSUE THREAD

**Issue by serejandmyself** [status-im/status-react#10047]
I am unsure if I'm opening the issue in the correct repo, please feel free to move it to the right repo if necessary. 

I have wrote a [reddit post](https://www.reddit.com/r/ethereum/comments/f3pqm6/status_privacy_policy_a_public_inquiry_about_the/) with my concerns to the Status mobile app privacy policy. IMO, it's only fair that I link the post to this issue, as it is my intention to clarify my question, rather than anything else. 

Thanks!

**Comment by churik** [comment]
@oskarth please, reopen if still relevant in this repo.
Thank you.

**Comment by oskarth** [comment]
@churik I don't know if it is still relevant, but it seems like @serejandmyself questions are still unanswered? cc @cammellos

**Comment by cammellos** [comment]
That's probably something that our legal team can answer, I will direct them to the reddit post.

**Comment by guylouis** [comment]
Carly's working on an updated privacy policy. 
I'll forward the reddit post link from @serejandmyself to her. 
I'll reopen this issue, and I will close it once:
- new privacy policy is written and approved 
- and integrated in status mobile app (related to https://github.com/status-im/status-react/issues/12081)

**Comment by churik** [comment]
thanks @guylouis

**Comment by serejandmyself** [comment]
Thanks for keeping this alive guys and working this through!

**Comment by guylouis** [comment]
@serejandmyself Here is our new privacy policy 
https://status.im/privacy-policy/

**Comment by guylouis** [comment]
closing this - please reopen if needed
