### ISSUE TITLE
gas is not being estimated

### ISSUE THREAD

**Issue by renaynay** [status-im/status-react#10040]
# Bug Report

## Problem

When trying to perform a contract interaction for ens domain setting, gas is not being estimated properly and an `invalid number` error pops up, but it is unclear with which field it is associated.

#### Expected behavior

Gas is already estimated

#### Actual behavior

Gas is not estimated and user has to manually input the network fee. Also an `invalid number` error pops up but it is unclear to which field it is associated.

![2020-02-13 21 44 04](https://user-images.githubusercontent.com/41963722/74476631-0431c980-4eaa-11ea-9745-f713d0cc4b22.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- click profile
- choose ENS usernames
- `Get started`
- `I own a name on another domain`
- enter <name>.eth and tap the arrow

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.0.1
[comment]: # 
- Operating System: iOS

**Comment by flexsurfer** [comment]
thank you for reporting @renaynay this issues will be addressed here https://github.com/status-im/status-react/issues/9037
