### ISSUE TITLE
App crash if tap on received link in 1-1 chat [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1005]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User receives link in 1-1 chat and taps on it -> app crashes

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Popup with options to /browse or to open in browser is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
in iOS app crashes
Note: in Android there is other issue: Empty popup is shown if tap on received link [ui-refresh] #1006
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7dThxcU5rWTBUeVk
- Open Status and login
- As another contact send to this contact link google.com
- As this contact tap on received link google.com

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: .0.9.6d38
* Operating System: iOS.

**Comment by rasom** [comment]
fixed in this commit too https://github.com/status-im/status-react/commit/b6f220d4252df8232b0e44af3daf55bf6413a2c0
