### ISSUE TITLE
Can't get messages and invitation to group chat (Mainnet)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10054]
# Bug Report

## Problem
Can get neither invites or messages in group chats (reproducibility 100% manually)
However, users in e2e are able to receive invites (see [test session ](https://app.saucelabs.com/tests/83c75fb3b67d4ff69414cbc8ac45e867?auth=7f6eb4e62a8cd2650330274019cc4161#58))

#### Expected behavior
Device 1: can see the sent message
Device 2: can see the invite

#### Actual behavior
Device 1: no sent message
![screencast 2020-02-18 17-58-20](https://user-images.githubusercontent.com/4557972/74758976-60b13200-5278-11ea-9cb0-ca7c1f9485c8.gif)

Device 2: no invite is received

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Device 1: create a new user
- Device 2: create a new user
- Device 1: add Device 2 to Contacts, start a group chat, send message to group chat

### Additional Information

- Status version: nightly 18/2/20
- Operating System: Android, iOS

#### Logs

Receiver (17:35-17:38): [Status-debug-logs.zip](https://github.com/status-im/status-react/files/4220508/Status-debug-logs.zip)
Sender  (17:41-17:45): [Status-debug-logs-2.zip](https://github.com/status-im/status-react/files/4220512/Status-debug-logs-2.zip)

**Comment by cammellos** [comment]
@churik I was not able to replicate with fresh accounts.
Which accounts were you using? Also when this happen, can you send 1-to-1 messages from user 1 to user 2?

**Comment by churik** [comment]
@cammellos 
I'll try today at home as well because as it turned out provider in  my coworking space is cutting traffic somehow (for example I can't launch e2e without VPN now)

> Which accounts were you using? 

Fresh one

> Also when this happen, can you send 1-to-1 messages from user 1 to user 2?

Yes

**Comment by churik** [comment]
@cammellos 
It is reproducible for me in 100% cases (tried on Android8, Android9, IOS 13 on different WI-FI networks).
I didn't see invites and sent messages to group chats.

Full logcat for receiver: [receiver.log](https://github.com/status-im/status-react/files/4229978/receiver.log)

Full logcat for sender: [sender.log](https://github.com/status-im/status-react/files/4229980/sender.log)

Users can exchange messages in 1-1 and public chats normally.
Mailserver for both: mail-01.do-ams3.eth.prod
Connection: stable WI-FI
Build: [nightly 20/02/2020](https://status-im.ams3.digitaloceanspaces.com/StatusIm-200220-025900-40c122-nightly-universal.apk)

**Comment by churik** [comment]
@cammellos I found very important detail.
Issue is reproducible when both are on Mainnet and not reproducible on Ropsten network.

**Comment by churik** [comment]
сс @rachelhamlin

**Comment by Serhy** [comment]
With latest nightly I can reproduce with new accounts, but only when group chat created by Android user. But all fine when iOS user creates group chat - in that case Android user receives invite and can accept it and both proceed messaging in the group chat 

My steps:
1) Install nightly build 24th of Feb on iOS and Android
2) Create new users on both devices
3) iOS_user and Android_user post message in public chat and add each other in contacts from public chat
4) iOS_user and Android_user create Group chats (so two group chats from each user)
**Actual result:** Android_user receives invite to group chat from iOS_user BUT there is no GroupChat on iOS_user side created by Android_user
Both can exchange messages in 1-1 chat
