### ISSUE TITLE
Use Android specific icons

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#10069]
# Problem

At the moment our UI is homogenised to a follow a single design, skewed towards iOS, without taking platform specific patterns into account. While in past this allowed us to design more rapidly and keep the codebase simpler, this doesn't always take into account what's good for our users. 
By implementing these Android specific assets, we will make the experience more familiar to our users and in line with best platform practices and expectations.

### 1. Implement platform specific `Share` icon

<img width="760" alt="Screenshot 2020-02-24 at 10 02 38" src="https://user-images.githubusercontent.com/4932774/75140228-c2e1bb00-56ee-11ea-895a-e77763ea08a9.png">

### 2. For the back button, on iOS we should use the `<` chevron or `x` when it's a modal dialogue (like we do now). On Android `<` should be replaced with a `←`.

<img width="1140" alt="Screenshot 2020-02-24 at 10 18 16" src="https://user-images.githubusercontent.com/4932774/75140340-fc1a2b00-56ee-11ea-8cc0-0a570583a8b9.png">

### 3. Do not use disclosure indicators on Android. ( `>` chevrons in list items )
This is an iOS only pattern, simple as that :)

<img width="1150" alt="Screenshot 2020-02-24 at 10 22 18" src="https://user-images.githubusercontent.com/4932774/75141045-6ed7d600-56f0-11ea-80be-639156849b7f.png">

## Acceptance Criteria

All items on the list were implemented and tested, if necessary, appropriate steps were taken so that it's handled on component level. 

## Notes

Thanks! 🙏

**Comment by miguelsm** [comment]
As an Android user I appreciate this effort. What about the action overflow icon? It's always struck me that Status uses a horizonal dots icon. It seems that's also iOS specific according to the Material Design guidelines: https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

**Comment by errorists** [comment]
Thanks! I think the overflow icon is easily understood and can be seen as a stylistic choice, regardless if it's horizontal or vertical. I wouldn't change that since as a stylistic choice I highly prefer the horizontal alignment that reinforces the visual metaphor that's something is left out or didn't fit, you know like in text…
