### ISSUE TITLE
Message cut off when selecting account

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#10062]
The message is cut off when creating an account, as in the picture.

![issue2](https://user-images.githubusercontent.com/1017008/74922154-1b534880-53cf-11ea-970a-92ea0f57210f.jpeg)

**Comment by churik** [comment]
@cammellos 
is it still relevant?
what device do you use to reproduce it?

**Comment by cammellos** [comment]
@churik it was reported by the community, I have asked for the device but did not get an asnwer back
