### ISSUE TITLE
Wrong ERC20 decimal rounding in "Set max"

### ISSUE THREAD

**Issue by tbenr** [status-im/status-react#10060]
# Problem

My intention was to send entire amount of an ERC20 token to another address.

Context: ERC20 with 18 decimals
Entire Amount in my wallet: all decimal was non-0:  the exact entire amount was using all 18 decimals

ISSUE 1: the displayed amount on Status was ceiled. So the displayed amount was grater then my actual amount (checked later with etherscan)
So when i manually set the amount it was accepted by the UI but then the transaction failed

ISSUE2: missing of "MAX" button which set the exact amount without having ti type it in my my self

replicated in ropsten:

![image](https://user-images.githubusercontent.com/15999009/74870719-7ac34100-535a-11ea-9f3d-2a128698a4f0.png)

it seems that it is ceiled up to 14 decimals

**Comment by tbenr** [comment]
it seems the root cause is in status go

![image](https://user-images.githubusercontent.com/15999009/74909393-80e80a80-53b8-11ea-9702-a361b1b7d765.png)


![image](https://user-images.githubusercontent.com/15999009/74909372-70379480-53b8-11ea-9c77-4083c0a12d22.png)

**Comment by 3esmit** [comment]
@hesterbruikman @andremedeiros This is very bad bug that needs to be fixed ASAP.

This causes transfers to fail, gas to be wasted, and is very hard to figure out why.

In case of SNT, this is what appears on etherscan: https://etherscan.io/tx/0xa6d220794018f90bbb6bb44ef4bbb74f541652ecb8b7482f17fdd67d51f606ba
https://etherscan.io/tx/0xc4799419adf1619dd2c287e551bc79846d3ad1fea24aa4df380aecb155e9b415

After manually setting the total value in the transfer value field, it goes correctly, see https://etherscan.io/tx/0x7aa74cab89bd600f46aaa4e22415d6e8f5b359489879c51f8c3cab77b875418b 

For this transaction, the total balance was `1267.855876884165207048`, but when I press "set max" it filled `1267.8558768841653`

For me to be able to make it work I needed to manually load the balance in the smart contract, place the decimal in the correct place and paste it on the value field.

**Comment by 3esmit** [comment]
Just to update on this bug report.

ISSUE 1: Currently is possible to set the exact value of the balance without being ceiled. 
ISSUE 2: Currently there is a MAX button, but it brings a ceil rounded value.

**Comment by hesterbruikman** [comment]
@3esmit Do I understand correctly that with Set MAX, the transaction fails because the amount set is higher than the actual value in your account, due to rounding?

**Comment by 3esmit** [comment]
Yes, exactly
