### ISSUE TITLE
Popup error reappears if tap on "Cancel" in "Error connecting to mailserver" popup

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10065]
# Bug Report

## Problem
Before if you dismiss "Error connecting to mailserver" popup (by tapping "Cancel") - you can see popup again on tapping banner in the header ("Tap to reconnect")
Currently, popup appears again in several seconds, so can't dismiss it

#### Expected behavior
button "Cancel" closes popup (con see it again if tap on "Tap to reconnect" in case of unsuccessful connection)

#### Actual behavior
poup reappears

### Reproduction

- Open Status
- Go to Profile > Sync settings > Mailserver
- Turn off automatic selection
- Add mailserver, that matches required format, but in fact invalid (i.e. enode://ee2b53b0ace9692167a510515bca3025695dbf0e1a68e1dff9716da620efb195f05a5b9e873fb9b75ac85de801106c565b8e2b6c5f0d93b8759d1578bfcaf03e:password@105.197.238.155:553 )
- Connect to it
- In "Error connecting to mailserver" tap "Cancel"

### Additional Information

- Status version: nightly 21/02/2020
- Operating System: Android, iOS

**Comment by churik** [comment]
Blocks part of `test_can_not_connect_to_mailserver` - should be uncommented and checked after fix

**Comment by flexsurfer** [comment]
@errorists do we have a proper flow for connecting to custom mailservers? the current implementation is a complete mess

**Comment by errorists** [comment]
@flexsurfer hard to say, previously it was Andrei who worked on those, [here are the 'latest' designs I could find ](https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=576%3A6676)

**Comment by iurimatias** [comment]
unassigning this due to https://github.com/status-im/status-react/pull/10342#issuecomment-614406994 cc: @andremedeiros
