### ISSUE TITLE
incorrect prices

### ISSUE THREAD

**Issue by GregTheGreek** [status-im/status-react#10064]
# Bug Report

## Problem

Using the address watch only feature, the app is displaying a drastically incorrect value ~30% higher.

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

![Screenshot_20200220_120858_im status ethereum~2](https://user-images.githubusercontent.com/16929357/74960521-7b032100-53da-11ea-9f7a-975c1a9729a6.jpg)

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- add watch only address
- check SaI balance

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: latest non-beta
[comment]: # (Android or iOS.)
- Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
...
```

**Comment by GregTheGreek** [comment]
@decanus

**Comment by andremedeiros** [comment]
@GregTheGreek we get FIAT prices from a 3rd party source, although we've made some updates to that system. Can you confirm you still see this issue?

**Comment by churik** [comment]
The prices are the same if add multi-account via seed phrase or add it as watch-only account for wallet.
@GregTheGreek reopen please if it is still happening to you.
