### ISSUE TITLE
Implement new shorter universal links

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#10083]
# Feature Issue

The current form of links is too verbose and long. After discussing this with @jarradh and some others we've decided to use shorter forms, like so:

* https://join.status.im/markets in favour of https://join.status.im/chat/public/markets
* https://join.status.im/u/0x04abcXYZ123... in favour of https://join.status.im/user/0x04abcXYZ123...
* https://join.status.im/u/jakubgs in favour of https://join.status.im/user/jakubgs
* https://join.status.im/u/jakubgs.eth in favour of https://join.status.im/user/jakubgs.eth
* https://join.status.im/b/ens.domains in favour of https://join.status.im/browse/ens.domains

These were implemented in https://github.com/status-im/universal-links-handler/pull/29 and are already deployed.

### User Story

As a user, I want to shorter universal links so that it's easier to remember them and make them yourself. They also produce more readable QR codes. 

### Description

We will have to support both the old and the new way for at least one release to not break the old links. After that we can see in server logs how many people still use them and we can retire them eventually in a later release to avoid maintaining dead code.

### Acceptance Criteria

New forms of universal links are supported on Android and iOS, in addition to old forms.

**Comment by jakubgs** [comment]
@hesterbruikman can we include this for `1.2`? As `1.1` appears to be already taking shape.

**Comment by hesterbruikman** [comment]
I think that's fine, as long as we have it by the end of this month. As I understand it, this isn't hugely complex or would risk any delays. Added v1.2 release label.

Does this issue require any updates in https://github.com/status-im/universal-links-handler/?

**Comment by jakubgs** [comment]
The necessary changes have already been made in https://github.com/status-im/universal-links-handler/pull/29 and deployed.

**Comment by hesterbruikman** [comment]
Then I'm confused 🙂 Are you saying it's not in the release cut for V1.1?

**Comment by jakubgs** [comment]
It's very simple. There are two parts to this:

* [universal-links-handler](https://github.com/status-im/universal-links-handler) - service that runs at https://join.status.im/
* [status-react](https://github.com/status-im/status-react) - The app that makes use of the links from https://join.status.im/

In order to change the structure of links under https://join.status.im/ two changes have to be made:

* Implement the displaying of new links - Done in https://github.com/status-im/universal-links-handler/pull/29
* Implement handling of the new links - To be done based on #10083, this issue.

On a specific example. If you go to https://join.status.im/@jakubgs.eth - which is the new form of https://join.status.im/user/jakubgs.eth - it will display a page, but it will not work with the App, regardless of from where you open it. For that to work changes have to be made to `status-react`.

**Comment by jakubgs** [comment]
But there is still the issue of #10029 and #10017 which touch partially on the same thing.

I think QR codes should always use full URLs and never use shorter forms like `status-im://jakubgs` or `@jakubgs` because this way they will work for anyone, not just for people who have the app installed.

**Comment by hesterbruikman** [comment]
Thanks for explaining!

> I think QR codes should always use full URLs and never use shorter forms like `status-im://jakubgs` or `@jakubgs` because this way they will work for anyone, not just for people who have the app installed.

Agree! I hate it when the short form doesn't work and I also get zero information about what it's trying to do

**Comment by hesterbruikman** [comment]
Btw @jakubgs do you know why exactly we don't allow upper case, spaces, etc? I see a lot of value in being able to create a channel anywhere, just by editing a url. The format restrictions limit that feature.

Nothing concrete yet, but thinking of how we can offer a 'create and share channel' feature on status.im

**Comment by jakubgs** [comment]
I don't know exactly why, but it makes sense to me. Look at Twitter, hashtags can't have spaces or special characters either. I think it's sensible. And you still can "create" a channel by just writing down a URL like https://join.status.im/my-new-channel just that if you for example use uppercase it will not work: https://join.status.im/My-New-Channel

What we could possibly do is simply redirect the upper case URL to the lower case URL.

**Comment by hesterbruikman** [comment]
> What we could possibly do is simply redirect the upper case URL to the lower case URL.

That would solve it. What I noticed before was the issue of having #friendschat when using Join Chat in Status (validation permits uppercase) and #Friendschat when using the url https://join.status.im/Friendschat. They'd open 2 different channels.

**Comment by jakubgs** [comment]
There you go: https://github.com/status-im/universal-links-handler/pull/32

**Comment by jakubgs** [comment]
#5302 is old but still relevant. We should fix the deep linking of upper case channel names.

**Comment by jakubgs** [comment]
Due to issues found in #10222 I had to replace `/@` format with `/u/` because iOS eats the `@`.
Related change: https://github.com/status-im/universal-links-handler/pull/35

Fuck Apple.
