### ISSUE TITLE
IOS build is keeping logged out after several minutes of inactivity

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10095]
# Bug Report

## Problem
After several minutes when app is in background and phone switched to sleep mode - user is logged out.
I didn't experience with this issue before v1.0.1, and also can't see that behavior in other chat applications (WhatsUp, Discord, Telegram)

#### Expected behavior
session is active

#### Actual behavior
user is logged out

### Reproduction

- Open Status
- Log in
- Put app to background
- Wait ~5 mins

### Additional Information
- Status version: nightly 27/02/2020
- Operating System: iOS 13.2.3.

#### Logs 

[status_logs.zip](https://github.com/status-im/status-react/files/4262395/status_logs.zip)

**Comment by hesterbruikman** [comment]
@churik do you know if in this case you have biometrics enabled?

**Comment by churik** [comment]
no, it is without "Save password" enabled. we actually can skip it for now, because @andremedeiros as far as I remember said that it is not possible to avoid with current implementations - app is killed on OS level

**Comment by cammellos** [comment]
Ok, closing this as it seems we can't do much about it, feel free to re-open if more action is required.
