### ISSUE TITLE
Status Starter Pack

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#10097]
# Feature Issue

In order to onboard users more quickly to the network, we're experimenting with an in-wallet starter pack.

![image](https://user-images.githubusercontent.com/15470435/75522103-b5ed0080-5a3b-11ea-99ae-d3a262c282ab.png)

Users can buy a bundle of tokens, including SNT, along with a set of stickers, for a set fee via Apple/Google Pay or credit card. This has the benefit of distributing more SNT to more people, and helping new crypto users to onboard quickly.

We're unsure whether this will be accepted by the stores, but we're going to give it a go.

[Figma designs](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=4550%3A0)

[Starter pack service created by Jarrad](https://github.com/status-im/starterpack-service/)

### User Story

As a user, I want to purchase tokens with my credit card so that I can pay for in-app features. 

### Acceptance Criteria

**Phase 1**
- RFC for the technical integration 

**Phase 2**
- SNT, ETH, sticker pack

**Phase 3**
- Other tokens bundled into pack

### Notes

- This will ultimately be replaced by a Teller Network or exchange link. 
- It should be dynamic or easy to change [the tokens that are included], the ideal situation would be to prefetch it from the distributor smart contract, but not necessary for first iteration.
- Certain countries like South Korea and Venezuela don't accept Apple/Google pay, so if we are to support those countries, it will need to be via credit card. 
- Pricing has yet to be worked out. Stores will take a 30% cut of whatever we earn. Other developers who want to bundle their token in the pack will do so at-cost, for distribution and exposure. 
- The user is getting a deal; essentially `Buy XYZ sticker pack for only $5, and you'll receive $10 in crypto directly into your wallet as a welcome gift.`
- Sticker pack to include is TBD—working with Jonny to see if we can use one of the other community packs that was submitted in our sticker contest in 2019. Would be nice to include something other than Tozemoon.

**Comment by hesterbruikman** [comment]
In app purchase Starter Pack no longer relevant
