### ISSUE TITLE
Add fiat entry in Send transaction

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10103]
# Feature Issue
### User Story
As a user I want to enter my transfer amount in fiat, because I don't know what the current token value is. Also, I determine how much I want to transfer in fiat, as it's most familiar due to day to day use.

### Description
Designs on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=5849%3A42299)

* [ ] Designs change the asset selection to become a list item below the divider
* [ ] The default selected asset remains ETH (no change)
* [ ] Designs introduce a new button style `Enter in USD`
* [ ] Currency displayed on the button depends on the set default fiat currency
* [ ] When button `Enter in USD` is tapped:
* [ ]  Button copy changes to `Enter in SNT` (depending on selected asset, ETH as default)
* [ ]  Asset/currency label by Amount field is updated
* [ ]  Asset icon is updated
* [ ] When amount is entered:
* [ ] Converted value changes from 0 to entered value

![Frame 2](https://user-images.githubusercontent.com/35233054/75549624-635a1700-5a30-11ea-831b-abe24e4b1f2a.png)

### Acceptance Criteria
Implementation follows design

### Notes
See also issue to add `Send all` next to `Enter in USD` https://github.com/status-im/status-react/issues/10105

**Comment by hesterbruikman** [comment]
cc @errorists @rachelhamlin issue based on Andrei's design to address entering amounts in fiat when sending a transaction

**Comment by rachelhamlin** [comment]
Lovely - thanks @hesterbruikman
