### ISSUE TITLE
Add set max to Send transaction

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10105]
# Feature Issue
### User Story
As a user I want to be able to quickly move all my funds, because, for example I lost my seed phrase

### Description
Designs on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=5849%3A42299)

* [ ] Adds available amount in wallet for selected asset
* [ ] In case ETH is selected, the user will need to manually edit the total to reserve some funds for gas. This design does not resolve this issue yet
* [ ] When user taps on `Send all`
* [ ] Amount is updated to available assets in account

![1!UNITO-UNDERSCORE!1 Chat](https://user-images.githubusercontent.com/35233054/75551004-79b5a200-5a33-11ea-8720-43033c935cb3.png)

### Acceptance Criteria
Implementation follows design

### Notes
Best implemented after or paired with https://github.com/status-im/status-react/issues/10103

**Comment by hesterbruikman** [comment]
cc @errorists @rachelhamlin less frequent than entering a fiat amount, this has also come up multiple times. It's not a full safety switch to move all assets, but at least per asset type. Also doesn't account for remaining ETH dust yet. Still think it's a worthwhile improvement

**Comment by flexsurfer** [comment]
"send all" doesn't sound good, because you don't send , you set value in a field, so probably "set max" or smth would be better

**Comment by hesterbruikman** [comment]
Agreed! Updated in Figma and above. Thanks @flexsurfer
