### ISSUE TITLE
Wallet universal qrcode scanner does not fails gracefully (an invalid UI state is displayed)

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10109]
# Bug Report

## Problem

When an invalid QR Code is scanned, for example:
![image](https://user-images.githubusercontent.com/224810/75564041-2723b800-5a2a-11ea-9d09-be5b24a38cfe.png)

This bug only occurs when the invalid qr code scanner is scanned through the universal scanner, a button with this icon: 
![image](https://user-images.githubusercontent.com/224810/75564150-5d613780-5a2a-11ea-9293-21471a244c44.png)
Placed at top corner of all wallets view:
![image](https://user-images.githubusercontent.com/224810/75564126-51757580-5a2a-11ea-8f1d-681d62c20a2b.png)

The transaction form is displayed without an account selected:
![image](https://user-images.githubusercontent.com/224810/75564308-a87b4a80-5a2a-11ea-864f-ac3739c4f1af.png)

which renders an invalid state causing other bugs, such as, the wallet balance not being updated and an error message saying that "Insufficient funds", even though I have funds:
![image](https://user-images.githubusercontent.com/224810/75564448-ef694000-5a2a-11ea-95c9-162f9224d589.png)

#### Expected behavior

If an invalid value is scanned, it should not open the transaction screen, or open it with default account selected.

#### Actual behavior

No account is selected opening a can of worms.

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Wallet
- Press on square icon representing qrcode
- Scan an invalid value

### Additional Information

- Status version: 1.0.2 (22020022507)
- Operating System:  Android

**Comment by jrainville** [comment]
I just tested and checked the code and I can no longer reproduce.
I think this was fixed in https://github.com/status-im/status-react/commit/b1170179cd3833bd8894689a8d75451b93147ea8 by @flexsurfer
