### ISSUE TITLE
Import an account and store it on Keycard (within a regular multiaccount)

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10128]
# Feature Issue
Allow storing an imported seed, through seed phrase, private key or keyfile storage, on Keycard.

### User Story
As a user I want to add an existing seed to my Status multiaccount and store it on Keycard, because I want to make all transactions from a single wallet, while keeping some of my funds in cold storage. 

### Description
- Add storage selection to:
`Add account` >`Enter a seed phrase`
`Add account` > `Enter private key`
- Issue needs design input. Proposal below and on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=7266%3A902) has not been reviewed
- Feature should be available for both regular multiaccount and Keycard multiaccount (in case of Keycard multiaccount this will require another Keycard)
- Selection of the added Keycard account for tx requires using the passcode and card to sign. This issue includes making sure that tx sign checks for the account's sign method

![Frame 3](https://user-images.githubusercontent.com/35233054/75914323-d7dbee00-5e54-11ea-85f8-9d3aa20cc350.png)

### Acceptance Criteria

- Implementation according to final designs
- tx overview calls Keycard sign method

### Notes
This feature should not be available for `Add account` > `Generate an account` as the keys for this account will be derived from a regular multiaccount and from a security perspective there is no point in storing only derived keys on Keycard.

This feature offers a better position for up sell of Keycard as users can continue to use their existing chat key and simply have the Keycard account 'under one roof', with benefits such as moving funds from and to Keycard.

Related issues:
https://github.com/status-im/status-react/issues/7134
https://github.com/status-im/status-react/pull/10100
https://github.com/status-im/status-react/issues/10101

**Comment by hesterbruikman** [comment]
@rasom @guylouis please check if this issue is accurate. Added after discussing with @rasom on Discord

**Comment by guylouis** [comment]
see 10/03 discussion summary here 
https://github.com/status-im/status-react/issues/10101#issuecomment-596999543

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
