### ISSUE TITLE
Log level is not applied

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10127]
# Bug Report

## Problem

By default we set log level in DISABLED state in profile setting. However changing it to DEBUG/TRACE does not make any effect. In logcat (Status.log for iOS) there are no DEBUG/TRACE records anyway. 

It's fine with develop (nightly/PR) builds.

#### Expected behavior

Log level setting applies and reflected in logs for release builds

#### Actual behavior

Log level setting change from Profile is not reflected in logs for release builds

### Reproduction

- Instal release build
- Create new account
- Navigate to `Profile` ->  `Advanced` -> `Log level`
- Set TRACE value
- Re-login to account, navigate between different screens and check logcat has DEBUG/TRACE/INFO records (also sending bug report from `Profile` -> `Need help?` -> `Submit bug`  to your email should has Status.log in package with the similar results: DEBUG/TRACE logs should be there) 

### Additional Information
- Status version: Release 1.1 (and Release 1.0.2)
- Operating System: Android and iOS

#### Logs

Logcat with TRACE log level setting in 1.1.x release build:

[logcatTRACErelease.log](https://github.com/status-im/status-react/files/4288656/logcatTRACErelease.log)

**Comment by churik** [comment]
The same in nightly builds - it should be `INFO` by default, in fact it is `DEBUG`.
Log example:
```
05-27 11:18:45.638 17119 17202 D ReactNativeJS: DEBUG [status-im.mailserver.core:317] - Adjusting mailserver request from: 1590571012 adjusted-from: 1590570992
05-27 11:18:45.640 17119 17202 I ReactNativeJS: INFO [status-im.mailserver.core:358] - mailserver: request-messages for:   topics  #{"0x87526257" "0x8a709717" "0xcaca5536"}  from  1590570992  force-to?  false  to  1590571125  range  113  cursor  nil  limit  1000
05-27 11:18:45.644 17119 17202 I ReactNativeJS: INFO [status-im.mailserver.core:378] - mailserver: messages request success for topic  #{"0x87526257" "0x8a709717" "0xcaca5536"} from 1590571012 to 1590571125
05-27 11:18:45.645 17119 17202 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver.callback/request-success
05-27 11:18:45.697 17119 17214 D StatusModule: Signal event: {"type":"mailserver.request.completed","event":{"requestID":"0x0db800f7ea14529cb55aae3ef68e6d3065450c65d46aaf7bd27450a378ef81a9","lastEnvelopeHash":"0x3061d113af75755507394bd15b5f9602e6f71573a30eb1732370c87cecbcb9bc","cursor":"","errorMessage":""}}
```
Nothing changes in log etries when I set `TRACE` level (no `TRACE` entries in logcat) or `ERROR` level (still see `DEBUG`)

So for me only works only disabling logs and only after full manual restart of the application (after logout still Debug level is set in fact)
