### ISSUE TITLE
Enter Seed Phrase Input Not Rendering Properly 

### ISSUE THREAD

**Issue by zach-is-my-name** [status-im/status-react#10121]
> # Bug Report

Enter Seed Phrase Input Not Rendering Properly 

> ## Problem

![image](https://user-images.githubusercontent.com/16063092/75697137-a9a2b680-5c7a-11ea-9b4a-83ad5cfa5d64.png)

> #### Expected behavior

See the phrase input 

> #### Actual behavior

Not seeing it 

> #### Notes

iOS 13.3.1
Model: iPhone SE

**Comment by hesterbruikman** [comment]
Might be possible to take along this issue, words are being hyphenated unnecessarily
![Screenshot_20200302_180925_im status ethereum](https://user-images.githubusercontent.com/35233054/75771961-4fbdf180-5d4b-11ea-8f85-49c1d0b0e342.jpg)

**Comment by zach-is-my-name** [comment]
Not sure what that means but, the issue is most certainly related to style and assumptions about screen size. The iPhone SE has a really small screen (relative to the others).
