### ISSUE TITLE
Messages are not marked as read after changing transaction state in 1-1 chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10136]
# Bug Report

## Problem
Currently if transaction in 1-1 chat changed state (i.e. Pending->confirmed, Shared address->Declined), message is marked as unread and the only way mark it as read - use "Mark all read" option

#### Expected behavior
no unread messages

#### Actual behavior
![photo_2020-03-05 14 58 26](https://user-images.githubusercontent.com/4557972/75988473-ed532580-5ef1-11ea-8399-d8f1e8f3c624.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- User A: create 1-1 chat with User B
- User A: Send request 0.1 ETH in chat
- User A: go back to home screen
- User B: decline request
- User A: see unread message; open chat with User B
-  User A: go back

### Additional Information

- Status version: v1.1 [RC 4](https://ci.status.im/job/status-react/job/release/job/release%252F1.1.x/4/)
- Operating System: Android, iOS

**Comment by churik** [comment]
@flexsurfer not sure it is blocker, WDYT?
can it be easy to fix?

**Comment by flexsurfer** [comment]
doesn't look like a blocker, i believe we have it in v1 as well and its only for the first message

**Comment by churik** [comment]
1) no, we don't have
2) no, it is for others as well
