### ISSUE TITLE
No send icon is shown if paste several lines into input field [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1013]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User pasted 3 lines into input field -> send icon is not shown, so it's impossible to send text. 
![3 lines](https://cloud.githubusercontent.com/assets/6584810/25062761/4f570ddc-21d3-11e7-8fcc-7f9f34022877.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Send icon is shown if user pasted any text into input, including text with several lines
#### Actual behavior
[comment]: # (Describe what actually happened.)
Send icon is not shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- copy text 
line1
line2
line3
- Open Status and login
- in 1-1 chat paste the text into input field

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6d43
* Operating System: Android and iOS

**Comment by alwx** [comment]
Probably related to #999 and #1011
