### ISSUE TITLE
Add possibility to select wallet for ENS names

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10142]
# Feature Issue

Currently, you can use ENS that is owned only by default (`Status`) account.
It would be nice to have possibility to choose a wallet in ENS, like it is done for DApps.
In continuation of https://github.com/status-im/status-react/issues/9749

### User Story

As a user, I want to have ability to use ENS names for imported wallets.

### Acceptance Criteria
Can use ENS for any account in my multiaccount.

**Comment by errorists** [comment]
should be easy looking at the UI, just change the text label where it shows your wallet address inside the summary view to a list item button and follow it with the same bottom sheet we already use elsewhere (browser / referral flow) to choose one of your accounts.

<img width="452" alt="Screenshot 2020-10-02 at 08 49 23" src="https://user-images.githubusercontent.com/4932774/94895676-2d7c8580-048c-11eb-8bb7-3bb63de8ea19.png">

[Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=1822%3A945)

**Comment by D4nte** [comment]
Wouldn't it make more sense if this flow was a separate dApp?

If the user wants to link their chat key to their ENS then the mobile app should provide a link to the dApp to set it.

Then it's up to the user to open the link in Status mobile dApp browser or any other dApp browser to use their wallet.

Finally, this would allow the same solution to be deployed for mobile, desktop and web.
