### ISSUE TITLE
Visible lag when loading list of chats after sign in

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10147]
# Bug Report

## Problem

After sign in there is a white screen for ~1-2s, and then list partially appears and then after ~1-2s full list of chats appears 

#### Expected behavior

The list is fully shown right after sign in

https://github.com/status-im/status-go/issues/2215

**Comment by flexsurfer** [comment]
still the issue, in latest releases even more visible

**Comment by churik** [comment]
@flexsurfer still the issue?

**Comment by flexsurfer** [comment]
still the issue

**Comment by flexsurfer** [comment]
fixed
