### ISSUE TITLE
Update account label in dapp permission dialog

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10148]
# Problem
When a dapp requests permission to connect to an account (address) a permission dialog is shown. The selected account looks tappable, giving the impression that the account can be changed here (e.g. a account selector bottom sheet will come up).

This is currently not possible. 

## Implementation
Change the color of the account name to black to make it appear less tappable. 
Color: Black
Font: Inter medium
Font-size: 13
See [Figma](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=3000%3A5095)

![Frame 3](https://user-images.githubusercontent.com/35233054/76215541-43d0a480-620f-11ea-8396-669c153a8906.png)

## Acceptance Criteria
Color of account name in permission dialog is black

## Notes
Investigate if/how account can be changed after dapp has send request to client and before address has been shared.

## Future Steps

- Allow 'connect' as after dapp request to connect
- In long-term pipeline: allow burner account for dapps

**Comment by hesterbruikman** [comment]
cc @jakubgs @errorists

**Comment by jakubgs** [comment]
Removing the border might be good too, but I'd defer to @errorists on that.
