### ISSUE TITLE
Unable to login to multiaccount if it is already restored as account in another multiaccount (IOS)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10141]
# Bug Report

## Problem
Currently at attempt to login to account, restored from seed phrase, got an error:
![photo_2020-03-06 15 05 12](https://user-images.githubusercontent.com/4557972/76090454-e4c72180-5fbb-11ea-8ff2-a85ce39c18f7.jpeg)

#### Expected behavior
app does not allow to restore this account from seed phrase

#### Actual behavior
IOS: error at login
Android: invalid password

#### Notes
Got several crashes when login / logout to these accounts (IOS only)
[Status.log](https://github.com/status-im/status-react/files/4298730/Status.log)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new multiaccount with password A
- Go to wallet -> Add new account (restore from seed phrase)
- Log out
- Use same seed phrase to restore multiaccount with password B
- Try to login / logout from both multiaccounts (IOS)
- Android only: login with password B
- Android only: try to generate new account in wallet with password B

### Additional Information

- Status version: v1.1 [RC 4](https://ci.status.im/job/status-react/job/release/job/release%252F1.1.x/4/)
- Operating System: Android, iOS

#### Logs
IOS: [geth.log](https://github.com/status-im/status-react/files/4298721/geth.log)
Android: [geth.log](https://github.com/status-im/status-react/files/4298738/geth.log)

**Comment by churik** [comment]
cc @flexsurfer @andremedeiros

**Comment by flexsurfer** [comment]
blocked : https://github.com/status-im/status-go/issues/1896
