### ISSUE TITLE
Last letter is cut for commands /faucet, /location and /browse in input field [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1014]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Last letter is cut for commands /location and /browse in input field. Also for /faucet in console. Can reproduce only on iOS. Same build in Android shows commands OK.
![browse cut](https://cloud.githubusercontent.com/assets/6584810/25063877/198003f0-21ef-11e7-9052-6855d8297e73.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Command text is fully visible
#### Actual behavior
[comment]: # (Describe what actually happened.)
 Last letter is cut 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- In 1-1 chat tap on command /location or on /browse
- in Console tap on command /faucet
### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6d43
* Operating System: iOS 10.2.3 iphone 6s.

**Comment by rasom** [comment]
@annadanchenko, can you check this on ios 10.3.1? It looks fine on 6s 10.3.1:

![img_1590](https://cloud.githubusercontent.com/assets/2364994/25064163/3d397b2e-21fd-11e7-87a8-8875757dce09.PNG)

**Comment by annadanchenko** [comment]
@rasom same issue on iphone 7 plus with 10.3.1 with build epic/ui-refresh (iOS) https://i.diawi.com/Eqijc3
![ios1031](https://cloud.githubusercontent.com/assets/6584810/25064181/5068be2e-21f5-11e7-96e4-5a978d16910f.jpg)
