### ISSUE TITLE
Improve alerts and flow to back up seed phrase

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10163]
# Feature Issue
We can do better making people aware that they need to back up their seed phrase. The current implementation includes badges on `Profile`, `Settings > Privacy and security`, `Settings > Privacy and Security > Back up seed phrase`. In addition we show a notification banner once the user has value in their wallet.

After V1 release we received feedback that:
- People hadn't backed up their seed phrase (we don't know what implementation they were using)
- Didn't notice the back up seed phrase notification nor badges in a limited time frame after receiving funds through chat commands

Aside from this we know that from a usability perspective the back up seed phrase alerts' styling and patterns are not as alarming as that should be given the risk.

### User Story
As a user I want to be made aware of having to back up my seed phrase as I'm not familiar with having to do anything like it, because I want my accounts and funds connected to it to be safe and available when I've lost my phone.

### Description
Designs introduce a countdown to make back up seed phrase alerts increasingly more visible and finally unavoidable.
##### Phase 1
- `Notification dot` (on Profile) > (currently a nr badge)
- `Number badge` on `Settings > Privacy and security` and `Settings > Privacy and security > Back up seed phrase` (exists)
##### Phase 2
- 3-day countdown triggered by `Assets in wallet` or `Having sent a message (exposing identity)`
- Back up your seed phrase popover appears on or after every 3rd new day that the app is opened
- Back up seed phrase `notification banner` is shown in wallet (exists)
##### Phase 3
- Back up seed phrase flow not completed by day 21 (7 days till countdown reaches 0)
- Color of dot, badges and notification banner turns red
##### Phase 4
- Seed phrase not backed up by day 30 (countdown reaches 0)
- Back up seed phrase flow appears when app is opened, cannot be dismissed, user has to complete flow to use the app

![Frame 60](https://user-images.githubusercontent.com/35233054/76630663-b1970c00-6540-11ea-96c1-bbb762154c1e.png)

Designs on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=8314%3A36337)

### Acceptance Criteria
Implementation follows Figma

### Notes

**Comment by hesterbruikman** [comment]
@andremedeiros @rachelhamlin I'd love to see this on the roadmap. With the current subtle nudges to back up seed phrase I'm afraid we'll onboard a lot of users that don't back up their seed phrase.

**Comment by rachelhamlin** [comment]
Nice solution. Tracked as unplanned on Trello right now. It is important, I agree.

**Comment by cammellos** [comment]
This one needs to be further broken down into features as it's too large and difficult to action.
I would suggest:

Notification on top of wallet view:

```
As a user
I want to see a notification when I access wallet to backup my seed phrase
So I don't forget to back it up
```
Pop up
```
As a user
I want to be reminded to backup my seed phrase periodically 
So I don't forget to back it up
```

Enforce backup

```
As a user
I want to be forced to backup my seed phrase after 30 days
So that I am sure that I can recover my funds
```

I am happy to do that if you'd like me to, let me know what you think @hesterbruikman

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
