### ISSUE TITLE
Set default currency based on Play Store/App store country/region

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10161]
# Problem
Anyone who wants to use a currency other than USD, currently has to locate and change the currency setting manually. Setting the currency based on App store/Play store region can make first time use more hassle free for a larger group of users

## Implementation
Set default currency to App store/Play store country or region

## Acceptance Criteria
Changing country/region changes default currency set in Status

## Notes
Sense check if any permissions are required and if feature is still in line with our Privacy principle

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
