### ISSUE TITLE
Create invite link for group chat

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10179]
# Feature Issue
Create an invite link for group chats that can be used as a referral link

### User Story

- As a user I want to invite friends in my current group chat to join me on Status in a private group chat, because I want to continue our existing shared conversation there
- As Status we want to onboard existing groups as they are more likely to stay compared to individuals being connected to one other user / not interested in public group chats
- As a user who sent out a link I want to be part of the referral scheme using that link so that I can earn SNTs

Deep linking throughout install only works on Android. on iOS recipients of an invite link will always need to reopen the link after installing the app.

##### User requirements
- Admins can create a group chat link
- Anyone can share the link once it's created by an admin
- The admin who created the link gets notified to Approve/Reject
_*Only admins as the link needs to include their pk in order for them to Approve joining_

##### Flow
- User B wants to invite someone, they tell user A
- User A creates the invite link url (note that it will be long, includes a group chat ID, chat name, admin pk)
- User B invites someone
- User A sees a notification to approve

### Notes
Effort estimate 3 weeks upon availability of designs

**Comment by hesterbruikman** [comment]
cc @errorists @cammellos

**Comment by cammellos** [comment]
One potential implementation for this is, given the requirements described above:

An admin of the group will generate an invite link.
This link will include at least:

1) The admin public key
2) The group chat ID (not sure we need this, as it can be revealed at later stages)
3) The group chat name at the time of invitation (might change after that)
4) A unique identifier for the invitation

If the user has already status installed, it will be handled as a universal link (this would work both on IOS and Android).
If the user has not status installed, and installs it through this link, it will be handled on creating a new account. This option is only available on Android. IOS user won't be able to continue the flow.

This link will be shared in any way the admin wants, it can be posted in a group chat, one-to-one, or send through other means (whatsapp etc).

Once the receiving user has either installed the app (Android only), or clicked on it (if status was already installed, both Android IOS), it can be shown with an invitation to join the group chat (or can happen automatically, that's a question for UX and UI).

If confirmed, the user will send a protocol message to the admin. We have quite a lot of freedom on the format. The simplest would be a new protocol message, for example:

``` protobuf
    message GroupChatInvitation {
     string chatId = 1; (not sure we need this)
     string invitationID = 2;
     string introductionMessage = 3;
   }
```
Multiple options are possible, the concept is just that the sending user needs to communicate that it has responded to the invitation.

The signature of the sender can be used to identify the sending user, so does not have to be transmitted.

Once the admin receives this message, it will show some UI to allow the user to confirm or decline the whether the user can join the chat. 

Mind that at this point no identity is verified, anyone who had access to the link could be the sender, therefore the admin should be invited to verify the identity through some means (i.e chatting with the user through status, or some other media).

If accepted, the admin would actually add the PK to the group chat, in the same way `add-members` currently work. 
The invited user will receive the invitation, and automatically join the chat (or it could still be asked to join the chat, that's a UX decision), by responding with a `join-event` message type (this is just the normal flow).

This is a non-breaking change, so users invited will be seen as normal participants once the flow is completed.

Disclaimer, this is just one of the potential implementations, and until the feature is fully fleshed out with UX/UI, implementation might have to be modified to reflect the changes.

**Comment by errorists** [comment]
if it helps the designs I did some time ago for this feature can be found [here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8927%3A39804)

**Comment by cammellos** [comment]
@errorists thanks, very helpful.

Looking at the designs, all the above still stands, a couple of things:

1) Does anyone see the `Group membership request`? or only the creator of the link/admin? (others might see it "read-only"). For simplicity it'd be better if only the admin sees it, but both options can be worked on.

2) In the group membership request, I think we should invite the user to verify the identity, as we don't know exactly who it might be (the only information we might have is their 3 random words name). Say something like `Chat with x` `Accept` `Decline`, or a warning or something.

**Comment by errorists** [comment]
@cammellos 
re: 1. I think the expectation is only the admin, so it helps that it's also the simpler one
re: 2. So could the person compose a short message that would be shown to the admin? You'd still be able to tap on their username to go their profile and `Send a message` to begin a new private chat if desired. It increases the complexity but we did a similar idea with Tribute to Talk to verify your identity and do an intro you'd attach a message.

<img width="427" alt="Screenshot 2020-05-28 at 15 01 01" src="https://user-images.githubusercontent.com/4932774/83144881-434ff780-a0f4-11ea-8d40-43bf37dec16e.png">

<img width="427" alt="Screenshot 2020-05-28 at 15 01 17" src="https://user-images.githubusercontent.com/4932774/83144898-48ad4200-a0f4-11ea-8e89-80dcdd68e487.png">

**Comment by cammellos** [comment]
@errorists sure, that's totally fine

**Comment by errorists** [comment]
my biggest concern here is spam and a link once published can't be made void right? so things might get out of hand fast for the poor admin. I honestly think that for groups the mechanism we have in place now of adding members manually from a contacts list is absolutely sufficient. but hey, happy to help finalise the UI if we're going with that.

**Comment by errorists** [comment]
also I guess it should return some kind of error if you visit a link to a group that's full

**Comment by cammellos** [comment]
> my biggest concern here is spam and a link once published can't be made void right?

We can give the admin an option to void the link, meaning that it will not receive anymore requests from it. It will just ignore those requests and won't see them in the UI. You can even just specify how many users can be used for before-hand potentially.

> also I guess it should return some kind of error if you visit a link to a group that's full

This is tricky, if you mean that the receiver should show an error if the group chat is full as soon as it clicks, that won't be possible, as you can't tell membership from the link itself (or it might have changed in the meantime).

**Comment by errorists** [comment]
> We can give the admin an option to void the link, meaning that it will not receive anymore requests from it. It will just ignore those requests and won't see them in the UI. You can even just specify how many users can be used for before-hand potentially.

it will considerably increase the complexity but I feel it's worth it to give that kind of granular control to keep admins happy.

So an alternative: if a person joins an invite to a full chat, admin will have the button to accept him greyed out until he makes room? What I guess I'm saying, groups are capped at 12 members so this doesn't seem like an edge case.

**Comment by cammellos** [comment]
> if a person joins an invite to a full chat, admin will have the button to accept him greyed out until he makes room? What I guess I'm saying, groups are capped at 12 members so this doesn't seem like an edge case.


Yes, that's fine, we should also spike on increasing the participants, it might be that's fine to increase now to a higher number.

**Comment by hesterbruikman** [comment]
Thanks for following up here! All makes sense to me. @cammellos do you see more details required for anyone to start work on this issue, in addition to the designs on Figma?

I imagine this also creates a new link type for status.im to handle, to be shown in a QR code and for status app QR code reader to handle. @errorists can you add these steps (between screen 4 and 5) of opening the link on Desktop and Mobile? 

Spam is a valid concern. I think there are options for future mitigations next to giving granular control now, e.g. staking to an associated smart contract account in order to send a membership request. Multiple chat keys would be an option here as well so you would stop listening with a chat key if you are completely overwhelmed.

**Comment by errorists** [comment]
I've changed the design a bit… well actually I started fresh following the discussion. For admins it now resides in a single view tucked inside group profiles so that chat history is clear of all those requests, it's also more prominent and they have options to control if a link is active or not. If desired I can add generating new links. All in all, I think it's more spam resistant, granular and obvious. 
One thing I'm not sure, if an admin declined your request should you be able to retry, wdyt?

**Comment by hesterbruikman** [comment]
🤔 depends if multiple invite links can be created. If yes, I'd say they can, but only in response to a new invite link. However we haven't discussed multiple invite links here, so I don't know if that's an option. If it's not, I'd suggest yes, until the admin Blocks the requesting user

**Comment by cammellos** [comment]
> Thanks for following up here! All makes sense to me. @cammellos do you see more details required for anyone to start work on this issue, in addition to the designs on Figma?

I would add in the issue that this is only possible with android if the app is not already installed, so that expectations are clear (so As an Android user ...). I would also remove `System requirement` section (I would leave technical requirements always out of the issues), just the functional ones, unless there are some hard technical requirement (i.e the one about the URL, although you can translate it to a functional i.e As a user who sent out a link I want to be part of the referral scheme using that link so that I can earn SNTs or something).
Otherwise looks ok

**Comment by hesterbruikman** [comment]
Updated based on @cammellos last comments. @andremedeiros can you look into if anyone/who is available to work on this in the coming weeks?

**Comment by hesterbruikman** [comment]
As discussed on Discord regarding the url format:

- groups join.status.im/g/ 

Other existing urls

- public chat join.status.im/ 
- chat key or ens name join.status.im/u/ 
- dapps join.status.im/b/
