### ISSUE TITLE
Send transaction popup doesn't respect back gesture

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#10187]
# Bug Report

## Problem

The "back gesture" on Android doesn't close the `Send transaction` popup, but it does have effect on the app, so it can cause the app to go into background if done 2-3 times while the popup is out. After the app goes into the background and you focus it again the popup is gone and can't be opened again.

#### Expected behavior

* The back button exits the `Send transaction` popup
* The popup can be opened again after app goes into background

### Reproduction

* Go into wallet view
* Open the `Send transaction` popup using the blue button at the bottom
* Try exiting it by clicking on the darkened area beyond it
* Try exiting it by using the Android back gesture
* Repeat the gesture few times until app goes into background
* Re-focus the Status app
* Try opening the `Send transaction` popup
* See that the button does nothing now

I assume the popup is still open but not visible.

### Video

![ezgif-2-96c3783e0caa](https://user-images.githubusercontent.com/2212681/77070411-77b78100-69ea-11ea-8adc-62a2dd227de6.gif)

**Comment by qoqobolo** [comment]
The issue is not reproducible on Nightly 2/12

**Comment by jakubgs** [comment]
Yep, I don't see it either, since it's not using an overlay anymore.
