### ISSUE TITLE
Make Status support new and old deep link format 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10192]
# Bug Report

## Problem

In the https://github.com/status-im/universal-links-handler/pull/29 we've implemented new shorter URLs for deep links
The app needs to be modified to support both for at least one release and then we can retire the old ones and use HTTP redirects to new ones

This issue should also cover opening of the deep link while Status is closed (it doesn't work now)
And also deep links should work on emulators.

#### Expected behavior

Opening both and new deep link while Status is closed and tap upon `Open in Status` button should open Status and after login inn to account it should redirect to appropriate view deep link suppose to do. See steps to reproduce per each URL what it should make:

#### Actual behavior

See steps to reproduce

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

e2e tests pass

### Precondition
Status installed and closed. 

### Reproduction

Here is the list of deep links and their behavior: https://docs.google.com/spreadsheets/d/1JiTBNVdmoYt0BN15EKo3RRO4rlIZAggK32Ye7pRCr6o/edit?usp=sharing

When user opens OLD/NEW deep link from the list then after login in user ends up on what described in BEHAVIOR section

Deep link | OLD DEEP LINK | NEW DEEP LINK |              BEHAVIOR              
-- | -- | -- | --
User Profile Public Key | https://join.status.im/user/0x04286c5fc..... |  https://join.status.im/0x04286c5fc...... (updated https://join.status.im/u/0x04286c5fc.....)| Opens user profile view
Your own Profile Public Key | https://join.status.im/user/[your_own_public_key] | https://join.status.im/[your_own_public_key] (update https://join.status.im/u/[your_own_public_key]) | Opens your own profile view (the Profile tab)
Your own ENS name | https://join.status.im/user/[your_own_ens] | https://join.status.im/[your_own_ens] (updated: https://join.status.im/u/[your_own_ens]) | Opens your own profile view (the Profile tab)
User Profile ENS name (stateofus.eth) | https://join.status.im/user/statuse2e | https://join.status.im/@statuse2e (updated: https://join.status.im/u/statuse2e) | Opens user profile view
User Profile external ENS (.eth) | https://join.status.im/user/statuse2e.eth | https://join.status.im/@statuse2e.eth (updated to: https://join.status.im/u/statuse2e.eth)  | Opens user profile view
Public chat | https://join.status.im/chat/public/markets | https://join.status.im/markets | Opens respective public chat
Dapp URL | https://join.status.im/browse/ens.domains | https://join.status.im/b/ens.domains | Opens pop-up with two options: Open in Status and Open in [Android/iOS]

### Additional Information

- Status version: develop / release 1.1
- Operating System: Android and iOS

**Comment by churik** [comment]
review `TestDeepLinks` after fix

**Comment by jakubgs** [comment]
This already has an issue: https://github.com/status-im/status-react/issues/10083

**Comment by Serhy** [comment]
> This already has an issue: #10083

Yes, they are related but current issue describes behavior per links and what should it do because currently we have bugs with how universal links are working in general (like if I open public chat universal link while app is closed - then after login I see public chat joined but on Chats main view instead of me automatically navigated to public chat view after login)

**Comment by jakubgs** [comment]
So is there something the #10222 does not cover here?

**Comment by jakubgs** [comment]
Because of issues found in #10222 I had to drop the `/@` format for user links and replace it with `/u/`.

Change: https://github.com/status-im/universal-links-handler/pull/35

**Comment by Serhy** [comment]
Thank you @jakubgs 
Everything (including /u/ links for user unniversal links) works fine for me now in iOS and Android in https://github.com/status-im/status-react/pull/10222

All items and scenarios mentioned in description of this issue works as expected.
