### ISSUE TITLE
Positive token balances display '0' after re-login in Wallet views

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10197]
# Bug Report

## Problem

It started often to appear that after re-login (maybe 1 of 3 re-login) token balances display 0, even there are funds (balance > 0). Below are logcat when after login all token balances show 0. 

#### Expected behavior

Appropriate token balance displayed on Wallet  
#### Actual behavior

<img width="344" alt="Screenshot 2020-03-23 at 16 07 09" src="https://user-images.githubusercontent.com/8749671/77325253-a3a37100-6d20-11ea-99ad-f1653a5003f5.png">

### Reproduction

- Open Status and recover an account with any token where balance > 0 
- Relogin to account multiple times each login checking balance on main wallet view (switch network from Ropsten to Mainnet) 

### Additional Information

- Status version: develop nightly 23rd of March
- Operating System: Android and iOS

#### Logs

Logcat when tokens are 0 after login:
[tokens3.log](https://github.com/status-im/status-react/files/4369819/tokens3.log)

**Comment by churik** [comment]
сс @rasom

**Comment by churik** [comment]
@flexsurfer  - can you please take a loook, can it be related to https://github.com/status-im/status-react/commit/2272fafc05c82514d829dc7c1d33a3dcf0f8dd60?

**Comment by flexsurfer** [comment]
no its not related

**Comment by rasom** [comment]
that's what can be found in the attached logs
```
03-23 16:02:43.881 16708 16749 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :status-im.wallet.core/update-token-balance-fail
03-23 16:02:43.888 16708 16749 D ReactNativeJS: DEBUG [status-im.wallet.core:82] - Unable to get tokens balances:  {:code -32000, :message "header not found"}
```

**Comment by rasom** [comment]
Almost likely it is thrown here https://github.com/status-im/status-go/blob/develop/vendor/github.com/ethereum/go-ethereum/eth/api_backend.go#L108

**Comment by Serhy** [comment]
With the latest nightly it reproduced probably 1 of 7 relogins. 
I set up autologin and re-open Status multiple times to catch the bug. 
Yesterday it was easy to see the bug  on network change, but now 5 of 5 network changes (with relogin)  succeeded in relation to 0 token balances)

**Comment by rasom** [comment]
@Serhy @churik 
The reason of this bug is that `wallet_getTokensBalances` quite often fails after account unlocking. Eventually balance will be loaded, but probably we need to show something different form 0 while numbers are not available.
