### ISSUE TITLE
Double /phone command

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1020]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description
![image](https://cloud.githubusercontent.com/assets/11790366/25083348/3e8cb352-235f-11e7-9ac4-6150b867fb8d.png)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

And also in suggestions, there are /phone request and /phone command

**Comment by alwx** [comment]
https://github.com/status-im/status-react/pull/1027
