### ISSUE TITLE
Endless spinner when sending two TX in a batch in Dapp

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10203]
# Bug Report

## Problem

There is an endless signing transaction process when trying to send two transactions in a batch. 
You can check it in simpledapp.eth -> Transaction tab: the `Send two Txs in batch.` button.

It seems nothing to deal with failing transaction itself but bottom sheet, because once `Send transaction` bottom sheet is opened there is no way to close it (nothing happens when tapping `Cancel` button). Unlike to other bottom sheets in Dapp where all is OK.

It's all fine when sending single transaction or when sending two transactions one after another

#### Expected behavior

Two Transactions sent fine from `simpledapp.eth` -> `Transactions` -> `Send two txs in batch`

#### Actual behavior

Endless spinner when trying to send two transaction in a batch from DApp

<img width="290" alt="Screenshot 2020-03-24 at 14 21 59" src="https://user-images.githubusercontent.com/8749671/77425071-d873fe80-6dda-11ea-88f9-3d0c0b55f13a.png">

### Reproduction

- Open Status and recover an account with funds
- In Browser open `simpledapp.eth`
- Open Transactions tab
- Tap `Send two txs in batch, 0.00001 and 0.00002 ETH` button
- Tap `Cancel` button (**Actual result**: nothing closed)
- Sign transaction with valid password

### Additional Information

- Status version: develop nightly 23rd of March
- Operating System: Android and iOS

**Comment by churik** [comment]
Blocks test 5743 `test_send_two_transactions_in_batch_in_dapp`
