### ISSUE TITLE
Reduce ambiguity between digits and letters

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10201]
# Problem
In several places in the app it's important to distinguish digits and letters, e.g. O vs 0.
- Wallet address
- Chat key
- Pairing code Keycard

## Implementation
Apply Inter Status, part of Quo, to relevant components
Inter has a specific styling to reduce ambiguity between characters:  https://rsms.me/inter/#features/ss02 
To enable it requires to insert font-feature-settings: "ss02" string in the text declaration  

## Acceptance Criteria
- All places where a combination of letters and digits is shown in a string (address, chat key, or pairing code) are shown uses `ss02`
- Inter ss02 is used on Android and iOS

## Future Steps

**Comment by hesterbruikman** [comment]
@errorists can you please check if the issue is accurate?
cc @rachelhamlin

**Comment by errorists** [comment]
It's a bit more than that. For addresses the full range of what needs to be included:

• Disambiguation (slashed zero and curved tails) 
font feature: `ss02`
_or if that's unavailable somehow, Slashed Zero `zero`_
• Disable Contextual Alternates (default is enabled, if letter `x` is joined by digits on both sides it's automatically turned to multiply `×`)
font feature: `Disable calt`
• I would also enable stylistic set 01, this makes numbers more open and easier to read
font feature: `ss01`

**Comment by errorists** [comment]
I doubt this will be easy to accomplish without the use of native code. Alternative here is to fork and create a specific version of Inter that has those features enabled by default

**Comment by errorists** [comment]
Ok we figured this one out to fork Inter and replace default characters with ones from the disambiguation set and disable the feature to replace `x` with `×` when joined by digits.

It's called Inter Status and ready to be used in the app

<img width="855" alt="Screenshot 2020-04-27 at 21 29 23" src="https://user-images.githubusercontent.com/4932774/80413798-4d51c100-88d0-11ea-910e-eb43cf7e3a2b.png">
