### ISSUE TITLE
To-be-sent amount and currency is reset after QR code scanning if currency is a token

### ISSUE THREAD

**Issue by leafcutterant** [status-im/status-react#10215]
# Bug Report

## Problem

See title.

#### Expected behavior

Chosen amount and currency should be preserved in the send flow after scanning the recipient's QR code, so that user can proceed with the transaction.

#### Actual behavior

It resets to 0.0 ETH.

#### Acceptance Criteria

Amount and currency is retained after scanning the QR code.

### Reproduction

- initiate send flow
- specify an amount and select a token (e.g. 30 DAI)
- choose recipient by scanning QR code

### Additional Information
- Status version: **1.1.0 (!)**
- Operating System: Android

**Comment by churik** [comment]
Thanks for reporting @leafcutterant !

**Comment by churik** [comment]
Actually it is duplicate of #9580
