### ISSUE TITLE
ens sometimes not visible to some people

### ISSUE THREAD

**Issue by Onebotband** [status-im/status-react#10219]
# Bug Report
Not everyone can see my ens name Lilsiri.eth 

## Problem

I’m not sure why it’s happening. But it appears to be solved after people search my ens name by adding me as a new contact. 

#### Expected behavior

[comment]: # (Describe what you expected to happen. Please include designs if possible.)

People are expected to see my ens name when I add them and in public chats. 

#### Actual behavior

[comment]: # (Describe what actually happened. Please include screenshots if possible.)

People only see my three word name. 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: ...
[comment]: # (Android or iOS.)
- Operating System: <Android|iOS>

I’m on iOS and the latest status update. 

I will post a message on status channel. 
#status-issue-10219
Let me know if you can see my ens or not

**Comment by 0x-r4bbit** [comment]
@Onebotband Did you send a message in #status-issue-10129? Just took a look and loaded messages from 25 days ago, but none is showing up in the channel.

Also, apparently ENS names resolve every 30 seconds, so I think there's a possibility that that's what other users were experiencing. In fact I ran into the same thing myself just now (see: https://github.com/status-im/status-react/issues/10218#issuecomment-613359624)

**Comment by Onebotband** [comment]
Hey, I reinstalled the app and it seems to be working fine now. Thanks.

Lilsiri.eth Ξ

**Comment by 0x-r4bbit** [comment]
Thanks @Onebotband !

Closing this as resolved.
