### ISSUE TITLE
1.2.0 Release

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10210]
Issue to manage 1.1.0 Release

### Release scope

* Changes: https://github.com/status-im/status-react/search?o=desc&q=committer-date%3A%3E2020-03-05&s=committer-date&type=Commits (in Release branch)
* Release notes: 
* Feature freeze date: March, 25, 2019
* Release branch: https://github.com/status-im/status-react/tree/release/1.2.x
* Expected release date: 
31/03/2019
### Testing info
* build 1 test plan: https://ethstatus.testrail.net/index.php?/runs/view/5103

### Builds in TestFlight and PlayStore to push as a release
RC 8

* https://status-im.ams3.digitaloceanspaces.com/StatusIm-200330-135232-2a755e-release-universal.apk
* https://status-im.ams3.digitaloceanspaces.com/StatusIm-200330-135232-2a755e-release.ipa

### Links for stable page update
Steps:

* [x] Submit iOS build to Apple review
* [ ] Create release notes
* [x] Waku deployed to prod fleet
* [x] Regression testing for release candidate build
* [x]  (optional) Fix known blocker(s) found during regression testing
* [x]  (optional) Cherry pick fix(es) to the release branch
* [x] (optional) Verify fix(es) on new release candidate build
* [x] (optional) Retest
* [x] ~Battery consumption testing~
* [ ] Update description for final release build on PlayStore and AppStore
* [x] Get links to release artefacts to update stable page
* [ ] Update status.im with Play Store, App Store and .apk links
* [x] Get exact versions of the tested final release build from test team and push them as release

#### Fixes to cherrypick:

* [x]  #10206 - [#10197] More retriers when requesting balances
* [x] #10191 - Fix android tabbar animation
* [x] Enable waku node default
#### Issues
* [x] https://github.com/status-im/status-react/issues/10211 - Android animation
* [x] Endless spinner after upgrade until relogin
* [x] Enable Waku by default 

Post release steps:

* [ ] Update PlayStore Screenshots if significant feature is added or existing Screenshots are no longer same as in previous version

**Comment by churik** [comment]
@rachelhamlin 
is it required to include https://github.com/status-im/status-react/pull/10207?

**Comment by jakubgs** [comment]
[2nd build](https://ci.status.im/job/status-react/job/release/job/release%2F1.2.x/2/) failed on Android upload to Play Store with:
```
Google Api Error: Server error - Internal error encountered.
```
As far as I can tell this is transient:
https://cloud.google.com/storage/docs/json_api/v1/status-codes#500_Internal_Server_Error
Because the upload did start, it just failed part way.

**Comment by jakubgs** [comment]
It looks like the Play Store upload error persists. I've reverted my change in 3337d9f77a3336ea09a351a0815874baf65cc94c.

I have to wait for Jarrad to show up to possible re-generate the API access keys for publishing.

For future reference: https://docs.fastlane.tools/actions/upload_to_play_store/#setup

**Comment by jakubgs** [comment]
Shouldn't this be closed? @hesterbruikman ?
