### ISSUE TITLE
Can't find web3 in browser (on simpledapp.eth) when refreshing the page

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10221]
# Bug Report

## Problem

When refreshing browser page with simpledapp.eth then it's often "..fails to find web3 library"
While I could not reproduce it with usual opening Dapp in browser, it's reproduced 2 of 3 times when refreshing the page

#### Expected behavior

Refreshing the page and finds web3 fine
#### Actual behavior

<img width="303" alt="Screenshot 2020-03-26 at 12 34 46" src="https://user-images.githubusercontent.com/8749671/77637368-3bda6980-6f5e-11ea-8105-272544503246.png">

### Reproduction

- Open Status and create new account
- Open `simpledapp.eth` in browser
- Tap `Refresh` button (top-right) 

### Additional Information

- Status version: develop nightly 26th of March
- Operating System: Android

#### Logs

```

03-26 12:28:37.445  1543  1543 D ViewRootImpl@e3f57af[MainActivity]: ViewPostIme pointer 0
03-26 12:28:37.542  1543  1543 D ViewRootImpl@e3f57af[MainActivity]: ViewPostIme pointer 1
03-26 12:28:37.719  1543  1583 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set-in
03-26 12:28:37.937  1543  1583 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :browser/loading-started
03-26 12:28:37.939  1543  1583 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set-in
03-26 12:28:38.456  1543  1583 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :browser/navigation-state-changed
03-26 12:28:42.128  1543  1583 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :mailserver/check-connection-timeout

```

**Comment by Serhy** [comment]
@siphiuel could you take a look please?  (started to appear after browser update)

**Comment by vitvly** [comment]
@Serhy yes, checking

**Comment by vitvly** [comment]
Some weird racing condition here. Android WebKit's own onPageStarted event (that injects web3 script) is firing consistently, looking at JS side now. When running simple-dapp code on localhost i cannot reproduce the issue at all, only on `simpledapp.eth` remote host. Investigating.
