### ISSUE TITLE
Update the Keycard request screen to Reedem transactions

### ISSUE THREAD

**Issue by bitgamma** [status-im/status-react#10223]
# Feature Issue

The request screen already implemented in Status is enough to make the preloaded card scenario work. From an UX perspective however it would appropriate to show a specialized screen. The fields to detect in the typed data are:

1. receiver (address)
1. code (bytes32)

The screen should show something like “You are redeeming the preloaded assets to the address 0x…” so that the user can confirm that they are really redeeming to the correct address. Showing the code is probably not needed especially if it is not an alphanumeric value.

### Acceptance Criteria

Given a Redeem transaction, the specialized request screen UI is shown instead of the generic one.

### Notes
The request screen is implemented in the `feature/9275-keycard-signTypedData` branch.

**Comment by guylouis** [comment]
here's the figma design 
https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=5849%3A42261

@hesterbruikman may you change the link if I did not use the right one ? 

Also @siphiuel @bitgamma @gravityblast : 
as for the account field, we did not fully precise how this should work. Here's a tentative 
- if receiver = one of the status account address then write its name 
- if receiver <> of any status address then write the address it self 0x.....

ok ?

**Comment by hesterbruikman** [comment]
Thanks @guylouis This link leads more directly to the flow: https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=9051%3A46835

**Comment by bitgamma** [comment]
@guylouis yeah the way you describe is fine. I don't see however the input for the account anywhere in the flow, how does the user select that?

**Comment by guylouis** [comment]
@bitgamma yes, it's a work in progress, discussed it this morning with @hesterbruikman

**Comment by guylouis** [comment]
For clarification 
"if receiver = one of the status account address then write its name"

the name of this account is not the 3 word name of the multiaccount, but the name of the account itself like "Status 1" etc.
