### ISSUE TITLE
Enable Waku by default 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10227]
### Description
Since `eth.prod` fleet was updated to support Waku and it works now we may default app to have  `Waku enabled` in the `Profile` -> `Advanced` settings to be ON.
It should be enabled in Release1.2 as well.

### Acceptance Criteria

- `Waku enabled` setting is turned on

**Comment by churik** [comment]
closed in RC8.
More details: https://github.com/status-im/status-react/issues/10210#issue-587560245
