### ISSUE TITLE
Merge create and confirm password into a single screen

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10220]
# Problem
In ad hoc testing the design team has identified people getting stuck at the `Confirm password` screen in onboarding. This is a critical step in onboarding and we'd like to remove any identified hurdles that negatively impact acquisition.

- People perceive the second screen to confirm their password as an indication that their password is wrong; As they have to enter it again
- The password input fields give no validation/confirmation that an entered password is correct, i.e. meets requirements
- There are currently no password requirements beyond 6 characters (can be addressed separately, but needs to be taken into account for design)
- The current design causes accessibility issues as the tappable area becomes 'invisible' without a placeholder

## Implementation
Changes include but not limited to:
- A single screen that shows both Create and Confirm (more familiar pattern, makes it easier to understand the second is a confirmation and to compare nr of characters)
- This screen is to be included in both the Onboarding flow and the Access keys flow
- Clear validation that shows entry meets requirements (6 characters)
- Clearly showing focus on either entry field
- Show/Hide icon to compare entries (maybe)

## Acceptance Criteria
Implementation follows [Figma design](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=6339%3A36595)

![Frame 12](https://user-images.githubusercontent.com/35233054/78247152-a9504200-74ea-11ea-8fd9-5ab8967d8659.png)

## Notes
When the issue is nearly complete, please experiment with increasing the fontsize for the glyphs (i.e `••••••`) from 15px to 18px, keeping the displayed password characters at 15px. This would be to increase spacing between the dots for clarity, but might create weird behavior while typing which is why we're not sure.

![Frame 13](https://user-images.githubusercontent.com/35233054/78247982-1912fc80-74ec-11ea-919c-5f42fb574401.png)

**Comment by hesterbruikman** [comment]
cc @rachelhamlin

**Comment by njokuScript** [comment]
@hesterbruikman how do i start working on this?

**Comment by rachelhamlin** [comment]
@Khay-EMMA have a look at our quickstart guide - https://status.im/technical/build_status/status_react_quickstart.html :)

**Comment by hesterbruikman** [comment]
@Khay-EMMA added the designs to the issue 👆 And, welcome! Thanks for you're interest in this issue!
