### ISSUE TITLE
Not clear in what account you are logged in if using touch id and have several accounts on your phone

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10235]
# Bug Report

## Problem
Currently when opening the app with enabled touch-id - the default screen is list of multi-accounts.
So it is not clear in what multiaccount you will be logged in after passing biometric authentication
![photo_2020-03-27 16 14 57](https://user-images.githubusercontent.com/4557972/77771212-b7afe100-7046-11ea-9efe-3198a575bd78.jpeg)
 
Would love to have your opinion on this @hesterbruikman

**Comment by hesterbruikman** [comment]
Yeah, that doesn't look right :) Thanks @churik 

We introduced `Sign out` to go to `Your keys`. So you can select a multiaccount to unlock. If this multiaccount has biometric enabled, it should prompt after selecting this multiaccount.

**Comment by churik** [comment]
Currently, login screen is shown, not a list of accounts, so it is fixed in 1.4
