### ISSUE TITLE
Web-page splits in 2 frames when contains errors

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10233]
# Bug Report

## Problem

![photo_2020-03-27 14 43 45](https://user-images.githubusercontent.com/4557972/77762166-61887100-7039-11ea-87e1-1e6e997b6e6e.jpeg)
![photo_2020-03-27 14 43 43](https://user-images.githubusercontent.com/4557972/77762171-63523480-7039-11ea-83ea-c34832cc24ec.jpeg)

#### Expected behavior
Nicely-handled error

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
-  Go to Webview
-  Type non-existing URL -> Enter

### Additional Information

- Status version: nightly 27/03/2020
- Operating System: Android, iOS

**Comment by churik** [comment]
@errorists your input is appreciated!
cc @siphiuel

**Comment by errorists** [comment]
I absolutely forgot about this issue, apologies for that!

here's the mockup, this should be placed centred in the webview

![error](https://user-images.githubusercontent.com/4932774/79983487-264a5800-84a8-11ea-9f08-3672ca377ac4.png)

👉 👉 👉 [Figma link](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=4783%3A15088) 👈 👈 👈

**Comment by errorists** [comment]
for the image I guess it would be cool if we could fetch the same ipfs hash we use normally for the sticker rather than embedding it?
