### ISSUE TITLE
Cursor is white on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10231]
# Bug Report

## Problem
<img width="242" alt="Monosnap 2020-03-27 13-31-09" src="https://user-images.githubusercontent.com/4557972/77756340-4284e180-702f-11ea-9c20-acea2e9496db.png">
Was introduced by  #10171

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 27/03/2020
- Operating System: Android

**Comment by Serhy** [comment]
I have it as green. 
Green cursor on Android 8.1 and Android 9

**Comment by churik** [comment]
Status of message is not visible as well (Android 9, LG V20)
<img width="247" alt="Monosnap 2020-03-27 14-05-40" src="https://user-images.githubusercontent.com/4557972/77758899-16b82a80-7034-11ea-86f8-666231a347bf.png">
