### ISSUE TITLE
Endless spinner after upgrade until relogin

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10240]
# Bug Report

## Problem
As we enabled WAKU mode by default in 7 RC v1.2 - after upgrade you will see endless spinner and can't use app until manual restarting.

#### Expected behavior
app is logged out, should login again

#### Actual behavior
endless "Connecting"

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Install v1.1
- Enable "Save password"
- Install RC 7
- Open app
### Additional Information

- Status version:[RC 7 ](https://ci.status.im/job/status-react/job/release/job/release%252F1.2.x/7/artifact/StatusIm-200330-090900-975b74-release-universal.apk)
- Operating System: Android, iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
[Status.log](https://github.com/status-im/status-react/files/4402140/Status.log)

**Comment by Serhy** [comment]
When I force reloging when changing LogLevel (after upgrade) then everything is ok (with Waku enabled by default) 
But if I simply relogin/restart app - then as described there is endless `Connecting...` and this is in logs:

```

03-30 13:31:01.362 22908 22949 D StatusModule: addPeer
03-30 13:31:01.362 22908 22948 I ReactNativeJS: HERE true [enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443]
03-30 13:31:01.376 22908 22948 E ReactNativeJS: ERROR [status-im.mailserver.core:96] - mailserver: update-mailservers error {:code -32601, :message "the method wakuext_updateMailservers does not exist/is not available"}
03-30 13:31:01.393 22908 22949 E unknown:ReactNative: console.error: "ERROR [status-im.mailserver.core:96] - mailserver: update-mailservers error {:code -32601, :message "the method wakuext_updateMailservers does not exist/is not available"}", js engine: hermes, stack:
03-30 13:31:01.393 22908 22949 E unknown:ReactNative: apply@-1
03-30 13:31:01.393 22908 22949 E unknown:ReactNative: c (address at@1:3807029
03-30 13:31:01.393 22908 22949 E unknown:ReactNative: f (address at@1:3806642
03-30 13:31:01.393 22908 22949 E unknown:ReactNative: call@-1
03-30 13:31:01.393 22908 22949 E unknown:ReactNative: apply@-1


```

**Comment by churik** [comment]
closed in RC 8
Details: https://github.com/status-im/status-react/issues/10210#issue-587560245
