### ISSUE TITLE
Gap ("Fetch messages" button) is always located in the beginning of the history

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10249]
# Bug Report

## Problem

"Fetch messages" should appear in gaps history. Currently, it is always shown in the beginning of the chat history.

#### Expected behavior
"Fetch messages" in the middle of history.

#### Actual behavior
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/4557972/78008443-f6dc7b80-733f-11ea-944d-dd91e11780b7.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join #status 
- Log out for > 24h
- Log in

### Additional Information

- Status version: nightly 31/03/2020
- Operating System: Android, iOS

#### Logs

[Status-debug-logs-gaps.zip](https://github.com/status-im/status-react/files/4407898/Status-debug-logs-gaps.zip)

**Comment by churik** [comment]
@rasom please take a look when you have a time. 
Thanks!

**Comment by flexsurfer** [comment]
ping @cammellos :)
