### ISSUE TITLE
Support ENS in browser

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10247]
# Feature Issue

ENS can be used as replacement for DNS. ENS domains can be configured to resolve websites, 

### User Story

As a user I want to navigate through websites configured with an ENS domain.

### Description

This was already done in past but we dropped at v1 https://github.com/status-im/status-react/issues/4772

### Acceptance Criteria

ENS can be used in broser.

**Comment by flexsurfer** [comment]
it's  already supported, status implements https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1577.md

**Comment by flexsurfer** [comment]
fixed https://github.com/status-im/status-react/pull/10258
