### ISSUE TITLE
Bottom system panel is white on dark mode on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10253]
# Bug Report

## Problem

![photo_2020-03-31 13 17 10](https://user-images.githubusercontent.com/4557972/78020538-f0ef9600-7351-11ea-91ca-c678ff8a8183.jpeg)

#### Expected behavior
![photo_2020-03-31 13 18 18](https://user-images.githubusercontent.com/4557972/78020651-1f6d7100-7352-11ea-803f-f7f6997f5408.jpeg)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 31/03/2020
- Operating System: Android (Xiaomi Mi Note9), dark mode is selected in phone settings

**Comment by StatusSceptre** [comment]
@Ferossgp I suspect this issue is resolved by `Change status-bar color on theme change` https://github.com/status-im/status-react/pull/10778 can you confirm?

**Comment by Ferossgp** [comment]
@StatusSceptre no, #10778 fixed the color for the top system bar only
