### ISSUE TITLE
Browser with Wallet url instead of Wallet screen is opened if quickly open Wallet->go back->open Wallet

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1025]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Browser with wallet url is opened instead of Wallet screen. 
![wallet in browser](https://cloud.githubusercontent.com/assets/6584810/25086602/2118a33a-2369-11e7-8c37-3db7a5e7b548.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Wallet screen is shown 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Browser with url https://status.im/dapps/wallet is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Nmg3UWptT1ZEeTA
- Open Status and login
- On Chats screen tap on Wallet. Wait till Main Wallet is shown
- Hit back device button
- As soon as Chats screen is shown, tap on Wallet. You need to be quick and tap on Wallet as soon as you see it. Do not make delays. If can't reproduce try same steps 3-4 times: open Wallet, hit back button, open Wallet again.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.5-53
* Operating System: Android

**Comment by rasom** [comment]
I can't reproduce this in `develop`

![wb](https://cloud.githubusercontent.com/assets/2364994/25117060/eff7e422-2418-11e7-8553-16841f583144.gif)

**Comment by annadanchenko** [comment]
I can reproduce it in new develop build. If it does not happen first time - try to "switch" between Main Wallet and Chats several times (5-6) and tap on Wallet in Chats as soon as you see it.

**Comment by annadanchenko** [comment]
Might be related issue and I can reproduce it on 0.9.6 on real Android device: "Sometimes when opening Maker Market, it opens the DApp on my default browser not in Status, doesn't happen every time but is replicable. The page has re-directing which might cause this, but there's a bug even if the url is fixed."
https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/396

**Comment by flexsurfer** [comment]
@annadanchenko looks like I can't reproduce it in develop anymore.
I couldn't find a reason of this, and it's possible only to make "blind fix" but because it happens rare and difficult to reproduce it's not worth it, fix can only bring new bugs

**Comment by yenda** [comment]
outdated with new wallet
