### ISSUE TITLE
Cannot input ChainID for Network Settings

### ISSUE THREAD

**Issue by collincusce** [status-im/status-react#10257]
# Feature Issue

### User Story

As a user, I want to add AVA's C-chain **so that** I can have AVA's C-chain. 

### Description

Can't add ChainID when creating network settings for new networks. This blocks ETC, AVA's C-chain, and probably other ones.

NetworkID can be the same if the ChainID is different. 

### Acceptance Criteria

Can add chains like ETC and AVA-based EVM chains.

### Notes

@corpetty knows what's up.

![Screenshot_20200330-185657](https://user-images.githubusercontent.com/6778681/78058688-ac1a2e00-7356-11ea-8f8b-2b31ec3254f3.png)

**Comment by corpetty** [comment]
I've also noticed when trying to add custom endpoints, the URL forces lowercase letters.  This seems unnecessary as URLs are case sensitive.

**Comment by hesterbruikman** [comment]
@corpetty is this issue still relevant? I'm checking what UI design is needed for the Network setting screens

**Comment by churik** [comment]
Closed as stale, reopen if still relevant @corpetty
