### ISSUE TITLE
Improve keycard login time

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#10259]
This is a place holder to follow-up this issue from the keycard project board. 

loging in a multi account with keycard takes about 2.84 seconds (test doen with nightly from 30/03/2020) and a JCOP4 card. Eventhough that's acceptable, it could be made better by improving the interaction with the card: the code contains some unneccessary code to write to the card. 

Issue here: https://github.com/status-im/react-native-status-keycard/pull/23

Discussion here : https://discordapp.com/channels/624205794384281629/626364653890437140/694545012804812850

Video of logging time with nightly from 30.03.2020 and a JCOP4 (phone is a oneplus 6T): https://drive.google.com/open?id=1sq9dd5wJWwQCiNgVxo4xOxpIj5znvSwv

**Comment by andremedeiros** [comment]
@guylouis looks like that PR has been merged.

Is this still an issue?

**Comment by guylouis** [comment]
@andremedeiros 
mmmh which PR do you mean? 
I don't think this has been worked on yet, it needs investigation on the react side with help from @bitgamma and we considered this is low priority and will do that later on, after launch

**Comment by bitgamma** [comment]
this has been partly addressed by merging https://github.com/status-im/react-native-status-keycard/pull/23 (we merged it to close some other issues which it incidentally fixed). However there are still several areas that could be seriously improved performance-wise, so let's leave this open for now.
