### ISSUE TITLE
App version is () on Android and 0.14.0 on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10265]
# Bug Report

## Problem
![photo_2020-04-02 12 02 42](https://user-images.githubusercontent.com/4557972/78236117-dfd19100-74d9-11ea-8b30-b318ee36f44c.jpeg)

#### Expected behavior
App version is shown correctly

#### Actual behavior
()

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to profile > About
- Check app version

### Additional Information

- Status version: nightly 02/04/2020
- Operating System: Android, IOS (on IOS app version is 0.14.0)

**Comment by churik** [comment]
Blocks `test_version_format`

**Comment by jakubgs** [comment]
Are we sure this applies to iOS too?

**Comment by jakubgs** [comment]
As far as I can tell the building of `jsbundle` requires the `VERSION` file because it `stat`s it:
```
stat("VERSION", 0x7ffff4bb8180)   = -1 ENOENT (No such file or directory)
```
So the issue is in this `mkFilter` defined for `jsbundle` derivation:
https://github.com/status-im/status-react/blob/19fdced2bc3dd5df68d5038a36439607ce6d5669/nix/mobile/android/jsbundle/default.nix#L19-L40

**Comment by jakubgs** [comment]
And as @rasom said we load it at compile time here:
https://github.com/status-im/status-react/blob/19fdced2bc3dd5df68d5038a36439607ce6d5669/src/status_im/utils/build.clj#L35-L42
But I guess we check it's availability during `jsbundle` creation.

**Comment by jakubgs** [comment]
I tested if it's Gradle's fault with 47a74efc173437c1e131600135b4e22d1e316995 but it didn't fix it so that can't be it.
