### ISSUE TITLE
"Nonce is too low" error at attempt to send transaction from non-main wallet account in keycard

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10277]
# Bug Report

## Problem
At attempt to send a transaction from non-default (generated in wallet) account got an error.

#### Expected behavior
no error

#### Actual behavior
![photo_2020-04-06 12 29 05](https://user-images.githubusercontent.com/4557972/78549156-37d20580-7802-11ea-843a-39b693aa5354.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Access key > Enter valid seed phrase > select keycard storage > finish setup
- Go to wallet > + > Generate new account > Enter right PIN
- from created account try to send transaction

### Additional Information

- Status version: highly 06/04/2020
- Operating System: Android

#### Logs
[Status-debug-logs-3.zip](https://github.com/status-im/status-react/files/4437732/Status-debug-logs-3.zip)

**Comment by churik** [comment]
cc @guylouis

**Comment by andremedeiros** [comment]
@churik can this be reproduced with a non-keycard account too?

**Comment by churik** [comment]
@andremedeiros no
