### ISSUE TITLE
Wrong public key is shown on keycard login screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10272]
# Bug Report

## Problem

Value of public key on login screen is not corresponding real public key of keycard user.

#### Expected behavior
no public key is shown or right value of public key

#### Actual behavior
<img width="321" alt="Genymotion for personal use - Google Pixel9 (1080x1920, 420dpi) - 192 168 57 103 2020-04-03 15-58-05" src="https://user-images.githubusercontent.com/4557972/78368646-3adfb280-75c4-11ea-8c25-17b26f922943.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard
- Log out
- Navigate to login screen

### Additional Information

- Status version: nightly 03/04/2020
- Operating System: Android

**Comment by churik** [comment]
cc @guylouis

**Comment by rasom** [comment]
@churik @guylouis that's actually `key-did`, not `public-key`. Should I change it?

**Comment by rasom** [comment]
We do not show it for a regular multiacc at all.

**Comment by guylouis** [comment]
I would make it consistent between regular multiaccount and keycard multiaccount, and not show it at all
@hesterbruikman agreed ?

**Comment by churik** [comment]
No objections from my side

**Comment by hesterbruikman** [comment]
Agree to removing it. 

Following designs the key should actually be shown for regular multiaccount as well. I'll update Figma to reflect that we do **not** show a key on the sign in screen. We've had issues there around what key actually should be shown, which will become more confusing when we add multiple chat keys.
