### ISSUE TITLE
Expand token icon set with icons for added custom tokens

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10283]
# Problem
The current token icon set is hard-coded and limited. We do not use an external library for 1) privacy when calling a service 2) limit dependencies. We've received feedback in #support that the default image we use for tokens not in our set makes tokens seem untrustworthy.

With the growing and evolving set of popular tokens, it becomes more pressing to find a way to support more tokens visually by expanding the token icon set.

## Implementation
Embark team has forked a library with a more extensive set of tokens. @simonricoo can work on styling these if needed. Core can use this set. 
- Upload and pin all images of the repo on IPFS
- Add JSON file in repo that lists them
- Support finding relevant token when a new token is added
- Include assets for all currently hard coded icons (requires design input cc @errorists) 

## Acceptance Criteria
Performance to load assets should not decrease

## Notes
Figure out the best way to store the image after the first download, so we don't keep asking for it to the ipfs gateway every time the wallet is opened
Complexity of asset list composition will increase a bit until everything is unified, we would have the clj code, the database and that json file as sources

**Comment by yenda** [comment]
This would be the source repo for icons: https://github.com/embarklabs/cryptocurrency-icons

> Support finding relevant token when a new token is added
when a user adds a custom token, the json file is checked to see if that token is already "known" based on address 

@hesterbruikman could you elaborate on this one:
> Include assets for all currently hard coded icons
do we have hardcorded tokens that currently don't have an icon?

**Comment by hesterbruikman** [comment]
![Screenshot_20200407-135630_Status](https://user-images.githubusercontent.com/35233054/78666795-2b1fe100-78d8-11ea-8c45-999d35e6bafc.jpg)

@yenda I meant the cases where we uses the 'default' icon for assets that are in the `Manage assets` list. I'm counting 10.

**Comment by churik** [comment]
closed in favour of https://github.com/status-im/status-react/issues/12104
