### ISSUE TITLE
support image type of message using base64 encode/decode

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#10296]
# Feature Issue

support sending limited size of image using base64 encode/decode technology, like browser parse "data:image/png;base64"

### User Story

when user send an image, status app convert it to a base64 encoded string, the other client decode the string to image and display it

### Description

it would be great to implement this, it's simple to implement from technology view, status already support normal text message, also this should have a high priority, because lots of ppl like sending image while chatting, it's a basic requirement.

**Comment by hesterbruikman** [comment]
@qfrank please check if this PR is in line with your request: https://github.com/status-im/specs/pull/107

**Comment by qfrank** [comment]
> @qfrank please check if this PR is in line with your request: [status-im/specs#107](https://github.com/status-im/specs/pull/107)

yes

**Comment by hesterbruikman** [comment]
Cool, thank, in that case I'm closing this issue 👍
