### ISSUE TITLE
Blinking messages with message replies when joining such chat for the first time 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10297]
# Bug Report

## Problem

When joining chat with messages for the first time (confirmed in public chat and 1-1 chat) the message replies starting to blinking each 5 seconds and whole list of messages redrawing too  
When re-navigating to that chat, then only username blinks only once in reply snipped. 

**NOTE:**  In a case of above scenario when the message which was replied to is visible (like the reply is the very next message) then no issues

#### Expected behavior

No message blinking when the joinning the chat for the first time

#### Actual behavior

Each 5 seconds after joining the chat with reply this what happens:

![112121212](https://user-images.githubusercontent.com/8749671/78782143-34797e00-79aa-11ea-8485-c6d3b6c60843.gif)

### Reproduction
- Open Status and create new account
- Join public chat where offline inboxed history exists

### Additional Information

- Status version: develop and release 1.2.0
- Operating System: Android and iOS

#### Logs

These are logcat logs for what happens when blinking happens:

```
04-08 15:09:39.940  3150  3227 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :chat.ui/message-visibility-changed
04-08 15:09:40.173  3150  3227 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :chat.ui/load-more-messages
04-08 15:09:40.216  3150  3227 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :status-im.chat.models.loading/messages-loaded


```

**Comment by cammellos** [comment]
This is also tracked here https://github.com/status-im/status-react/issues/10274
