### ISSUE TITLE
Make browser secure again

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10309]
With the new webview component we need to make sure we:

1) persist cookies and localstorage between login sessions
2) switch cookies and localstorage between accounts (or clear if not possible to switch)
3) have an option in settings to clear all data

**Comment by andremedeiros** [comment]
> have an option in settings to clear all data

Think it would make sense to have one option to clear everything or should we allow it to be more granular?

For instance, it looks like on iOS you can get a list of cookies per domain, so we could either say "it's all or nothing" or "here's a list of domains I have cookies for, delete only the ones you want"

**Comment by cyanlemons** [comment]
>have an option in settings to clear all data

In the same line of thought, I believe it would be nice to provide an "Incognito" mode where all cookies, local storage and cache always ends up getting cleared automatically.

If possible, it would be nice if the "Incognito" was an option that would persist even after the Status app has been fully closed – which is not the case for most browsers, but is a very desirable feature nonetheless.

**Comment by churik** [comment]
@flexsurfer suppose it is still relevant; however, feel free to close it if smth fresher on the topic exists

**Comment by flexsurfer** [comment]
still relevant

**Comment by churik** [comment]
https://github.com/status-im/status-mobile/issues/1751 is a part of it
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
