### ISSUE TITLE
Horizontal scroll between Assets, Collectibles and History

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10305]
# Problem
Enhancement to make switching between tabs `assets`, `collectibles`, `history` more intuitive

## Implementation
There is [another issue](https://github.com/status-im/status-react/issues/10303) on horizontal scroll between account views. Because of that, this issue requires distinguishing whether the user intends to swipe between accounts.

Needs design input to further specify behavior

![Frame 11](https://user-images.githubusercontent.com/35233054/78807463-64ce1600-79c4-11ea-8132-cfbe5985de70.png)

**Comment by simonricoo** [comment]
Expected behaviour:
![Screen_Recording_2020-05-13_at_18 43 57](https://user-images.githubusercontent.com/52249767/81903576-3bf00080-95c2-11ea-8c88-08e41f1f632c.gif)
