### ISSUE TITLE
Allow horizontal scroll between accounts in wallet

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10303]
# Problem
Enhancement to make switching between account view more intuitive

## Implementation
There is [another issue](https://github.com/status-im/status-react/issues/10305) on horizontal scroll between `Assets`, `Collectibles` and `History`. Because of that, this issue requires distinguishing whether the user intends to swipe between accounts.
Designs on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=2054%3A926)
Needs design input for transition when threshold to switch account view has been reached.

![Frame 4](https://user-images.githubusercontent.com/35233054/78806568-22580980-79c3-11ea-8d91-ff8d369ea9b7.png)
 

## Notes
Related to Pinterest style transitions for account explorer: https://github.com/status-im/status-react/issues/8896

## Future Steps

**Comment by errorists** [comment]
I'm not sure about this one, the way this UI is designed, switching between subviews inside a subview, I don't find it elegant and somewhat counter to how these building blocks were meant to function. Not my circus not my monkeys, just thought to mention this

**Comment by hesterbruikman** [comment]
Your circus @errorists 😄🐒  Please close this issue and #10305 if you disagree with the design. It's a legacy idea.

**Comment by errorists** [comment]
closing this one only, #10305 is still relevant
