### ISSUE TITLE
Request compressed keys

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10325]
**This issue is paired with and should follow implementation of https://github.com/status-im/status-go/issues/1937**

## Problem
Chat key is currently shown (as used) as the public key in full. This is unnecessarily daunting. Compressing the public key used for chat can make it less daunting, more space efficient in the UI as well as reducing file size and visual complexity of the QR code.

## Implementation
Status-go will include two new functions:
- decompress public key - anywhere the full public key is required
- request compressed key - places where the key is shown or shared in the UI

02 and 03 will be used for compressed keys, 04 will be maintained for decompressed keys

status-react should always receive the decompressed key (no changes to current implementation) unless the compressed key is requested. Instances where the compressed key should be requested include:

- `Onboarding` > `Choose a chat name`
- `Profile` > `Header`
- `Profile` > `Share icon` > `QR code popover`
- `Invite friends` url from `Invite friends` button and `+ -button` > `Invite friends`
- Other user `Profile details` 
- `Profile details` > `Share icon` > `QR code popover`

## Future Steps
- Add Status logo/styling to QR code (design tbd)
- Add save to gallery action for QR code

**Comment by hesterbruikman** [comment]
cc @andremedeiros @gravityblast

**Comment by Samyoul** [comment]
The `status-go` functionality for this is merged https://github.com/status-im/status-go/pull/1990.

Awaiting on specs to be cleared for merge

**Comment by hesterbruikman** [comment]
Thanks for making this happen!

**Comment by churik** [comment]
@hesterbruikman is this still relevant?

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
