### ISSUE TITLE
Add sticker submissions to market place

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#10336]
# Problem

We have two sticker market submissions via Google. Would like to push these to the sticker market with associated metadata.

## Implementation

- Add sticker packs to sticker market interface 

## Acceptance Criteria

Pack 1
**Artist name:** Mugen Feng
**Sticker pack name:** Dogeth
**Pack price in SNT:** 20 
**ETH address:** 0x595645110FDE0691A94DE393e080558539237126
[Sticker images](https://www.dropbox.com/sh/z1za6jywm2cneh1/AAAPJ-8UAVlN-9Xs6iqsZ8XTa?dl=0)
[Banner image](https://www.dropbox.com/s/8g4mdux21b4ew7n/1280%20x%20800%20pixel.jpg?dl=0)
[Thumbnail image](https://www.dropbox.com/s/mykhkwob7vh2a8n/thumbnail%20128x128%20pixel.png?dl=0)

Pack 2
**Artist name:** DesignBlock
**Sticker pack name:** Stanny
**Pack price in SNT:** 70
**Ethereum address:** 0x8bb4afc9b4aAcb73ecC0993df4a15DE25ba2a7CE
[Sticker images](https://drive.google.com/open?id=1tEs-8cpx4v8FbNVibTzM-43o_Uf9jpoF)
[Banner image](https://drive.google.com/open?id=15XytsKmFReck57I-bUARaVyVryDKgu4L)
[Thumbnail image](https://drive.google.com/open?id=1KTSsoO8-_qXJQgb6McmSgQIuQ3zVWuRJ)

Pack 3
**Artist name:** Brooklyn Design Factory
**Sticker pack name:** Ghostatus
**Pack price in SNT:** 0
**Ethereum address:** 0xA71C4Ef0c5BC4b1a172A19DcB5882683808E6b82
[Sticker images](https://www.dropbox.com/sh/mmf0ivfdtxhpmn1/AACqokrb5wg5iTy4v8t7Q8wza?dl=0)
[Banner image](https://www.dropbox.com/sh/eq0upjdg8sxcclo/AABbnzBL03PM0iJ2enCWKxi_a?dl=0)
[Thumbnail image](https://www.dropbox.com/sh/582he14qfj4vkn1/AACB22MfSveNEq_TBJuPpahta?dl=0)

**Comment by 3esmit** [comment]
Some problems with the information below.

Pack 1 was named "Dogeth" by the artist. Why is it being called "Shiba Pack"? Is this right? 
Pack 1 suggested name is suffixed with the word "Pack", which is redundant and does not happen for other packs in the market. Is this right?

Pack 2 is missing the pack name.

**Comment by rachelhamlin** [comment]
Thanks for checking me, @3esmit! I added the missing name for pack 2, but there's a conflict.
 
I pulled these from the [Sticker Market form submissions](https://docs.google.com/spreadsheets/d/1Gkaebx7zgbTXqiWNDd5fseAR2B-NiuuzPdjmdW8lr6w/edit?usp=sharing). 

It looks like Shiba Pack was renamed and submitted to the latest contest. I missed the results from that and see we have 9 other packs to add as well.

But the second pack appears to be replicated as well. I can't tell if the robot image was created by the same artist, or if two separate artists took the same graphic off the internet and modified it for stickers.

@j-zerah where can we find the image files for [these winners](https://our.status.im/stick2web3-sticker-design-competition-we-have-a-winner/)? I would like to compare the two submissions.

We'll also need ETH addresses, artist names, and SNT prices for those that are legit. Banner images & thumbnails would be great, too. 🤞

**Comment by j-zerah** [comment]
@rachelhamlin looks like you have all the info you need for Shiba pack and Stanny.

We have reached out to all other artists but have not heard back. As long as they have the google form, it is up to them to upload the correct information right?

**Comment by rachelhamlin** [comment]
In this case, we are good to publish the data in the issue. I am going to rename Shiba Pack to `Dogeth` as that's what the artist submitted to the competition, and that happened after his Shiba Pack submission. cc @3esmit

**Comment by rachelhamlin** [comment]
@3esmit one more pack added. Are you able to handle this one?

**Comment by 3esmit** [comment]
All packs listed here are added.
