### ISSUE TITLE
Feature Request: Addition of Unstoppable Domains resolution into the application

### ISSUE THREAD

**Issue by corpetty** [status-im/status-react#10353]
# Feature Issue

### User Story

As a user, I would like to do the following:
- resolve <domain>.crypto in the web3 browser
- resolve owned .crypto NFTs in the wallet
- resolve username records in chat search (will require record standardization agreement with UD)

### Acceptance Criteria

I can do all of the previously mentioned things in user stories

### Notes
This could probably be broken up into three issues, one for each part of the app.

**Comment by bigcook12345** [comment]
This would help me out a lot actually. I'm just trying to understand this whole thing. It's pretty confusing. Dove in head first with minimal experience.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
