### ISSUE TITLE
Add help text to Account settings > Type

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10359]
# Problem
Account information is an advanced feature that provides the user with information about where their keys are stored (`Storage`) and what type they are (`Type`), meaning whether they are derived from the same seed, a different seed, or a watch only account. The latter should inform users about what seed phrase would be required to recover the account.

Tge `Type` label is not clear and difficult to define while terminology is still evolving. A help text should further explain what the account info means.

## Implementation
Adjust list items to double button bar to include help text.
![Account type imported-1](https://user-images.githubusercontent.com/35233054/79572663-a003cf80-80bd-11ea-818c-04fc06a73b06.png)
![Account type imported](https://user-images.githubusercontent.com/35233054/79572666-a09c6600-80bd-11ea-85cc-ebc0dae14af1.png)
![Account type Watch-only](https://user-images.githubusercontent.com/35233054/79572664-a09c6600-80bd-11ea-913f-e567d1e62ef1.png)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
