### ISSUE TITLE
DARK MODE for status-im on iOS and andriod

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#10352]
# Feature Issue
 status-Im should integrate dark mode to the app as a minority of apps like this have dark mode compatibility and it would be nice to have an option to have dark mode

**Comment by ghost** [comment]
here is some guidelines for dark mode for ios and Andriod for their platform  

https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by flexsurfer** [comment]
thanks @epicodertime dark mode has been implemented and currently in testing, will be available in the next release 1.3
