### ISSUE TITLE
App freezes on transaction signing after entering wrong password

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10369]
# Bug Report

## Problem
After entering wrong password on Signing transaction screen app is freezing with endless spinner.
Reproducible in 1-1, wallet flows

#### Expected behavior
Can enter valid password and sign transaction

#### Actual behavior
![photo_2020-04-20 16 05 24](https://user-images.githubusercontent.com/4557972/79760711-c1b0c100-8320-11ea-972e-8922ebbd937f.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to wallet
- Try to send transaction to any address
- Enter invalid password, click "Sign"

### Additional Information

- Status version: RC 1.3 #5 
- Operating System: Android, iOS

#### Logs

[Status-debug-logs-trn.zip](https://github.com/status-im/status-react/files/4503984/Status-debug-logs-trn.zip)

**Comment by flexsurfer** [comment]
@churik was introduced here 
https://github.com/status-im/status-react/pull/9390

https://github.com/status-im/status-react/commit/e11385e35093f6f312bf0a037dc63fe829f3fc2b#diff-598cee30285d1d51df0def4398019d98R337
