### ISSUE TITLE
Message that contains only emoji are shown as replies to "Unknown" in all chats

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10371]
# Bug Report

## Problem

![photo_2020-04-20 16 44 59](https://user-images.githubusercontent.com/4557972/79764933-49e59500-8326-11ea-8ed6-03ea5616eb04.jpeg)

#### Expected behavior
ordinary message, not reply

#### Actual behavior
message is shown as reply from unknown

### Reproduction

- Open Status
- Join any chat
- Send emoji

### Additional Information

- Status version: RC 1.3 #5 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
probably related to https://github.com/status-im/status-react/pull/10304 ? @cammellos

**Comment by cammellos** [comment]
possibly, I can have a look at it tomorrow

**Comment by StatusSceptre** [comment]
Would be great guys @cammellos @flexsurfer I don't want to release 1.3 with this.

**Comment by StatusSceptre** [comment]
it can't be "fixed" on our side, we have next options:
1. we could force those guys to add logs to that contract call (but that won't fix transfers from other contracts)
2. or create our own "archival nodes" with some custom API for those cases
3. or implement "wallet contract" as Ricardo mentioned in core
but that's not a simple fix unfortunately
