### ISSUE TITLE
Can't install Status on real android device using make command

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-react#10375]
# Bug Report

## Problem

This repository comes with a couple of `make` commands to run Status in different environments, including virtual devices and real devices. 

I tried installing and running Status on my Android device (Pixel 1) and followed the following steps:

1. Put my phone in develop mode and enabled USB debugging
2. Pulled changes from latest `develop`
3. Ran `make shell TARGET=android`
4. Ran `make startdev-android-real`
5. Ran `make react-native-android`
6. Ran `make run-android`

This installed Status from latest `develop` on my phone, however, **starting the app resulted in it being stuck in the splash screen**. I know @gravityblast is experiencing the same.

It tried it once again, at which point I got an error on my device, saying it couldn't connect to the metro server (even though it was running). I then decided to do all the steps above again, so I've uninstalled Status from the device and repeated everything from step 3.

Things got worse from that point on, as `make run-android` fails with 

```
> Task :app:installDebug
Skipping device 'emulator-5562' (emulator-5562): Device is OFFLINE.
10:21:15 V/ddms: execute: running am get-config
10:21:15 V/ddms: execute 'am get-config' on 'FA69X0310593' : EOF hit. Read: -1
10:21:15 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Pixel - 10' for app:debug
10:21:15 D/app-debug.apk: Uploading app-debug.apk onto device 'FA69X0310593'
10:21:15 D/Device: Uploading file onto device 'FA69X0310593'
10:21:15 D/ddms: Reading file permision of /Users/pascalprecht/projects/status-im/status-react/android/app/build/outputs/apk/debug/app-debug.apk as: rw-r--r--
10:21:16 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
10:21:27 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'FA69X0310593' : EOF hit. Read: -1
10:21:27 V/ddms: execute: returning
10:21:27 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
10:21:27 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'FA69X0310593' : EOF hit. Read: -1
10:21:27 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 21s
505 actionable tasks: 505 executed
info Connecting to the development server...
8081
info Starting the app on "FA69X0310593"...
Starting: Intent { cmp=im.status.ethereum.debug/im.status.ethereum.MainActivity }
Error type 3
Error: Activity class {im.status.ethereum.debug/im.status.ethereum.MainActivity} does not exist.
```

Notice that the output says that the installation was successful, however there's no Status app on my phone.

@flexsurfer suggested I should try cleaning my Gradle files using

```
./android/gradlew cleanBuildCache`
```

Unfortunately, that fails due to `gradle` not being available in the shell. I assumed that `make shell TARGET=android` would take care of installing `gradle` as well.

#### Expected behavior

I guess it should be possible to run Status on a real device to test developments.

#### Actual behavior

As described above, `make run-android` fails and I don't know how to get past that error.

#### Notes

I **assume** first of all, to verify whether `gradle cleanBuildCache` fixes it, the `make shell` command needs to be updated/fixed to include `gradle` as well? 

### Additional Information

- Status version: latest `develop` (https://github.com/status-im/status-react/commit/387b9cb37a3a5a10484e75bc3a639affc4335ffe)
- Operating System: Android v10

**Comment by gravityblast** [comment]
yes I had the same problem with a pixel 2

**Comment by emizzle** [comment]
Happens to me also on an HTC U11

**Comment by jakubgs** [comment]
I don't see how it doesn't work.
```
 $ make shell TARGET=android
Configuring default Nix shell for target 'android'...
Checking for modifications in node_modules...
No modifications detected.

[nix-shell:~/work/status-react]$ cd android

[nix-shell:~/work/status-react/android]$ ./gradlew cleanBuildCache
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
...
BUILD SUCCESSFUL in 12s
26 actionable tasks: 26 executed
```
Though it is true that the `make android-clean` target is fucked due to lack of `TARGET`.
Here's a fix: https://github.com/status-im/status-react/pull/10376

I'll take a look at the rest.

**Comment by jakubgs** [comment]
Oh! Interesting, I just noticed we are using a pretty old Gradle plugin version:
https://github.com/status-im/status-react/blob/387b9cb37a3a5a10484e75bc3a639affc4335ffe/android/gradle.properties#L30
We've upgrade to Gradle `5.6.4` in #10340 but I missed this.
According to the docs the plugin version appropriate for Gradle `5.6.4` is `3.6.0+`:
https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
I will attempt to do this change and see what happens.

**Comment by 0x-r4bbit** [comment]
So there are two issues here, one being that we can't get past the splash screen, the other one, which only I am experiencing, is that `make run-android` fails with said error. I really hope this can be fixed with gradle clean. Otherwise I'm not sure what to do. Notice that this happened after I've uninstalled Status from the device (not sure if that's related)

**Comment by jakubgs** [comment]
Here's a Gradle plugin upgrade PR that fixes errors from `make run-android`: #10387

But now I'm seeing the same issue, the screen is black after installation of `Status Debug` build.

**Comment by jakubgs** [comment]
The Gradle plugin upgrade in #10387 was reverted in #10402 due to issues so I went one version lower in #10410, and I'll do the upgrade to `3.6.0` separate.

**Comment by cammellos** [comment]
I assume this has been resolved, please reopen if necessary
