### ISSUE TITLE
Sometimes messages-replies don't change state to "Sent" (endless spinner)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10389]
# Bug Report

## Problem

The issue is mostly visible from restored accounts (however sometimes can be reproduced and from freshly created account).
If send first message as reply - it may freeze with endless spinner (reproducibility ~90% with restored accounts) - and ~30-40% of the next messages-replies don't change state.
 
#### Expected behavior
messages are sent

#### Actual behavior
<img width="181" alt="photo_2020-04-21 16 18 41 jpeg 2020-04-21 16-19-02" src="https://user-images.githubusercontent.com/4557972/79876860-dad27400-83eb-11ea-907a-14ccff9362f2.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

The easiest way to reproduce for me:
- Open Status
- Restore account from seed phrase
- Join any public channel
- Select any message > Reply > Send reply

But it can be also reproduced from any account at attempt to send several reply-messages.

### Additional Information

- Status version: release v1.2 and v1.3
- Operating System: Android, iOS

#### Logs

[status_logs-1.zip](https://github.com/status-im/status-react/files/4510011/status_logs-1.zip)

**Comment by churik** [comment]
It is pretty visible in 1.3 (like 50% of replies are with endless spinner), so decided it is blocker for v1.3

**Comment by churik** [comment]
cc @cammellos

**Comment by Serhy** [comment]
Confirmed with Android 8 and 9 and iOS 13.3
 
Here is the video and respective logcat logs for that video: https://drive.google.com/file/d/1qBGtv4ocpCwnIgTtbzf1abfoB2Su3L6e/view?usp=sharing

[replies_logcat.log](https://github.com/status-im/status-react/files/4510750/replies.log)

**Comment by cammellos** [comment]
This is actually 2 issues, one is specific to replies and only present in 1.3 , the other one is both in 1.2 and 1.3 and it's for any kind of message, it might be the cause of those reports "I am connected to mailserver but sending messages show always spinning", I will address both.
