### ISSUE TITLE
Protocol specs

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#10384]
# Problem
To create a developer-friendly spec for other teams that may wish to build Status clients, we're dedicating time to documentation during the last half of April. 

## Implementation
We'll complete the following sections: 

* [x] How we use IPFS gateway for stickers—Gheorghe @Ferossgp 
* [x] How notifications work since changes last few months—Eric @yenda 
* [x] How we interface with the Ethereum blockchain—Andrea P @cammellos 
* [x] How Status clients use Keycard—Roman @rasom & Andrea F (?)
* [x] 3rd party APIs used for core functionality that impacts things like availability/censorship and privacy—Volodymyr @vkjr 
* [x] Dapp browser API usage—Vitaliy @siphiuel and Andrey @flexsurfer 
* [x] Things on the horizon—Image sending, mentions TK
* [ ] Starterpack & Referrals—André @andremedeiros 

We suggest using these vacp2p specs as references:
https://specs.vac.dev/specs/mvds.html
https://specs.vac.dev/specs/mvds-metadata.html

Although we can identify a couple of requirements (below), it's difficult to offer explicit guidelines on structure, as that will depend on the content covered. We encourage authors to create an outline first.

Once a draft is written, we'll peer review the content internally for missing items. 

## Acceptance Criteria

* Include an abstract
* Include definition of any terms upfront

## Timing
First drafts by Wednesday, 29/4/20.

Peer review through EOW. 

Polishing and editing w/o 4/5/20.

**Comment by vkjr** [comment]
[3rd party APIs used for core functionality that impacts things like availability/censorship and privacy (DRAFT)](https://notes.status.im/zMADIsmGRe69US4hMl1EWw?view)

**Comment by Ferossgp** [comment]
[How we use IPFS gateway for stickers](https://notes.status.im/s/_WLWrkr_I#)

**Comment by vitvly** [comment]
Dapp browser API usage: https://notes.status.im/s/FnEGcXIq8

**Comment by rachelhamlin** [comment]
Bravo team. 

Specs in progress from @cammellos as linked in Discord (to-do: ENS): 
https://github.com/status-im/specs/blob/db9612dd983463d2e8358b5c1e916ce476737857/docs/stable/9-blockchain-usage.md#ENS

Push notifications/mentions by @yenda 
https://github.com/status-im/specs/pull/104
https://github.com/status-im/specs/pull/105

**Comment by flexsurfer** [comment]
Dapp browser API usage: https://notes.status.im/s/FnEGcXIq8

**Comment by rachelhamlin** [comment]
Next step is to move into peer review. I suggest the following people review...

@flexsurfer - IPFS gateway usage: https://notes.status.im/s/_WLWrkr_I#
@yenda  - How we interface with Ethereum blockchain: https://github.com/status-im/specs/blob/db9612dd983463d2e8358b5c1e916ce476737857/docs/stable/9-blockchain-usage.md#ENS (once finished)
@cammellos (once finished writing) - Push notifications, mentions: https://github.com/status-im/specs/pull/104, https://github.com/status-im/specs/pull/105
@vkjr  - Dapp Browser API usage - https://notes.status.im/s/FnEGcXIq8
@siphiuel  - How Status clients use Keycard - (once finished)
@rasom  - 3rd party apis for core functionality - https://notes.status.im/zMADIsmGRe69US4hMl1EWw?view

You do not need to be an expert in the assigned area, just approach it as a third party dev would. But if you think you are better suited to another section, please don't hesitate to coordinate with the person assigned. :) It would be wonderful if this could be completed before the weekend. 

I suggest leaving comments in a separate copy of the file, or within the PR.
