### ISSUE TITLE
New invite to group chat will be not sent if user left chat and then will be readded

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10390]
# Bug Report

## Problem
Currently, we have odd behavior after user left and was readded by admin - chat is not recreated and user doesn't receive the invite.
As a user, I want to be warned that if I left chat - it is forever and I can't be added to the same group again if this behavior is expected.

#### Expected behavior
User is warned about consequences

#### Actual behavior
User can be added but doesn't receive the invite

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- As user A: create group chat with User B
- As User B: join to group chat 
- As User B: left group chat
- As User A: add User B to the same group chat again

### Additional Information

- Status version: release v.1.3
- Operating System: Android, iOS

**Comment by churik** [comment]
@hesterbruikman would like to have your opinion on this, thank you!

**Comment by hesterbruikman** [comment]
Agree, that's unexpected behavior. Seems more like user B's action is `abandon` instead of `leave`. So either we can think of copy changes to better reflect what happens or allow re-adding. @cammellos can you please explain why a user cannot be re-added after leaving a group chat?

**Comment by cammellos** [comment]
User can be re-added to a chat from a technical perspective,I think it's just a choice we have to make, no technical reason to be one way or the other.

**Comment by errorists** [comment]
it shouldn't be a one-way street: one of admins removes a user, anyone who's a group admin can choose to add him back, the same flow is repeated again when the user was added for the first time. there's no limit in place on how many times a user can be removed and invited back, the same goes for leaving the chat by the user

**Comment by cammellos** [comment]
cool, we can change the behavior

**Comment by errorists** [comment]
@cammellos thank you!
