### ISSUE TITLE
User is navigated to "Your keys have been successfully recovered" screen instead of accounts list if tap on "Back" after unlock existing account

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10398]
# Bug Report

## Problem
"Back" button brings user to wrong screen instead of multiaccounts  list if it is clicked from login screen after tapping "Unlock" existing multiaccount
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/4557972/79963527-d361a800-8489-11ea-9c7a-e118901c80d3.gif)

#### Expected behavior
list of multiaccounts

#### Actual behavior
<img width="90" alt="Monosnap 2020-04-22 11-08-43" src="https://user-images.githubusercontent.com/4557972/79963502-cc3a9a00-8489-11ea-821e-58f93a4574b8.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Restore multiaccount from seed phrase
- Log out
- Tap on "Access existing keys" -> enter same seed phrase
- In popup tap "Unlock"
- On login screen tap "Back"

### Additional Information
- Status version: release 1.3
- Operating System: Android, iOS

**Comment by qoqobolo** [comment]
The issue is not reproducible on Nightly 2/12
