### ISSUE TITLE
Quoted text (using markdown) in dark mode  is hardly visible

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10396]
# Bug Report

## Problem
<img width="182" alt="Monosnap 2020-04-22 10-32-55" src="https://user-images.githubusercontent.com/4557972/79959643-a9f24d80-8484-11ea-9e17-c6344dad1653.png">

#### Expected behavior
Text is more visible

#### Actual behavior

see screenshot

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- User A: join to public chat, send message with quoted text( i.e. `> aaaaaaa`)
- User B: join same public chat

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release v1.3
- Operating System: Android, iOS

**Comment by errorists** [comment]
you guys are awesome, good catch! I've filled in all the markdown values for dark theme [here](https://www.figma.com/file/9hkPcxsqDTWa9b9c49OX3X/Dark-Mode?node-id=130%3A4675)

**Comment by errorists** [comment]
@flexsurfer while we're at it, would it be possible please to correct the chat avatar initial, it should be the same for both dark theme and light, currently as you can see on the screenshot attached in the issue the text is dark?
<img width="1671" alt="Screenshot 2020-04-22 at 14 38 16" src="https://user-images.githubusercontent.com/4932774/79982638-e9319600-84a6-11ea-9d05-4cd841f08973.png">

**Comment by flexsurfer** [comment]
@errorists done
![image](https://user-images.githubusercontent.com/11790366/79983659-627db880-84a8-11ea-8830-c78c12b1dc7b.png)

**Comment by errorists** [comment]
@flexsurfer legend, as always 🙏

**Comment by flexsurfer** [comment]
@errorists @churik super local change, do you want this to be cherry picked in 1.3 ? i think chat avatar initial would be nice to have in 1.3 wdyt ?

**Comment by errorists** [comment]
It would be cool if we could introduce the dark mode in as good shape as possible, yes
