### ISSUE TITLE
Bugs in group-chat-commands [Android]

### ISSUE THREAD

**Issue by coyotespike** [status-im/status-react#1039]
Bugs remaining after rebase.

- [ ] `/console/faucet` response shows up in command sender's chat, but not in other person's chat. `/mailman/location` shows in both though.
- [ ] "Requests" in suggestions popup shows only group name, doesn't populate requests/responses
- [x] Response to `/phone` shows up in Console, not in group chat. 
- [x] Only `/c` filters to /Console commands, all suggestions vanish with capitalized`/C`. Same for other commands.

- [x] If wallet is not in convo, `location`, `send`, `request` are prefaced with wrong person.
- [x] Commands show in preview without command owners: in preview, `/console/faucet` shows as `/faucet`.

~- [ ] After visiting group chat where Wallet is a member, Wallet commands show as `/Wallet/send`~

**Comment by yenda** [comment]
@alwx can this be closed now with the rework ?
