### ISSUE TITLE
Landscape/Tablet/Desktop view

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#104]
How should Status look like when in landscape mode?

**Comment by sla-shi** [comment]
Per Design call notes 17/08/17 - let's start with at least 1 screen @denis-sharypin @andmironov

**Comment by sla-shi** [comment]
Removing from the milestone backlog - unlikely that we can start working on this near term.

**Comment by chadyj** [comment]
Closing. We have Status working in tablet view in portrait and landscape.
