### ISSUE TITLE
Message marked as sent but it's not (when bad network connection)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10404]
# Bug Report

## Problem

It was noticed and reproduced cases when message is sent and visible on sender side and sent but in fact it's not reached mailserver.
That easy to reproduce on iOS when WiFi enabled (and no mobile network) -> you disable WiFi and there is 5-7 seconds till device (or Status) recognise WiFi is OFF. And sending messages in this range - they are marked and 'Sent' (no message status spinner). After enabling WiFi back - nothing is re-sent thus message sender thinks messages are sent while it's not. 

Not all messages are marked as 'Sent'. There are messages with "status spinner". 
But with that issue, i.e. messaging while in poor network connection (and often switch between WiFi and MobileNetwork) may end up in "lost messages issues" but reason was that message even 

With Android it's reproducible as well. See Reproduction valid for both platforms.
#### Expected behavior

Message sent in 5-7 seconds after WiFi disabled gets status spinner on sender side

#### Actual behavior

Message sent in 5-7 seconds after WiFi disabled marked as sent on message sender side
Video: https://drive.google.com/file/d/1_U6_ZUpqcwaHPW1mfMj47MBq2aj1KI9O/view?usp=sharing

<img width="364" alt="Screenshot 2020-04-22 at 15 21 09" src="https://user-images.githubusercontent.com/8749671/79981298-200aaa80-84ad-11ea-87a1-b17391dc11df.png">

### Reproduction

- Open Status and create new account
- Join public chat
- Plug out WiFi router (if you are with iPhone then just simply turn off WiFi on device)
- Send messages right after you plugged out WiFi (in the next 5-7 seconds you have 'Send' button available)
- Keep attention on whether messages are sent, but check with different Device in the same public chat if they sent indeed.

### Additional Information
- Status version: develop/release1.3
- Operating System: Android and iOS

#### Logs

```
TBD...

```

**Comment by churik** [comment]
@Serhy not relevant I believe?

**Comment by Serhy** [comment]
Correct. We don't have 'Sent' indication now. Closing the issue
