### ISSUE TITLE
Blank Chats view if quickly tap twice "<" back button from any chat view  

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10425]
# Bug Report

## Problem

Tapping quickly `<` back button while in any chat view leads to blank Chats view. It's "refreshed" and back to normal after navigate back-and-forth between tabs though.  
It may not be reproduced from the first time, but not hard enough to reproduce. 

#### Expected behavior

Chats view shown if quickly tap twice "<" back button from any chat view  
#### Actual behavior

![TwiceTapBAck](https://user-images.githubusercontent.com/8749671/80197158-eeb5ea00-8626-11ea-91d0-992998195062.gif)

Video: https://drive.google.com/file/d/1uizl3dcF1GShuVgWlANUvhiiAVfz0wDJ/view?usp=sharing

### Reproduction

- Open Status and create new account
- Join any chat (public chat for example)
- Tap `<` back button quickly twice in a row 

### Additional Information
- Status version: Release1.3/develop
- Operating System: Android and iOS

**Comment by fasih** [comment]
Same thing is happening if you tap any channel hashtag from another conversation in android devices.

**Comment by churik** [comment]
not reproducible on nightly 10/06/2020
