### ISSUE TITLE
Margin issue in public chat input field

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10429]
# Bug Report

## Problem

Few issues related to margin values of input fields:
1) `(+)` -> `Join public chat`
2) `Profile` -> `Advanced` -> `Bootnodes` ->  `(+)` -> both fields
3)  `Profile` -> `Sync settings` -> `Devices` -> input field

#### Expected behavior

Margin of placeholder and cursor in input is pleasing to the eye
#### Actual behavior

<img width="603" alt="Screenshot 2020-04-24 at 14 08 30" src="https://user-images.githubusercontent.com/8749671/80206510-1e6bee80-8635-11ea-9eef-6a8cc3c9d1d7.png">

### Reproduction
- Open Status and create new account
- Navigate to `(+)` -> `Join public chat` -> input field
- Novigate to `Profile` -> `Advanced` -> `Bootnodes` ->  `(+)` -> both fields
- Navigate to `Profile` -> `Sync settings` -> `Devices` -> input field

### Additional Information
- Status version: release 1.3, 
- Operating System: Android and iOS (public  chat creation input), the rest Android only

**Comment by Serhy** [comment]
cc @Ferossgp

**Comment by churik** [comment]
From initial issue only public chat name is left, the rest is fixed

**Comment by StatusSceptre** [comment]
@Ferossgp Can you verify whether this issue will be resolved by Thursday's Quo test-inputs merge https://github.com/status-im/status-react/pull/10797#event-3433712104?

**Comment by Ferossgp** [comment]
Yes, this is fixed in #10797
