### ISSUE TITLE
First carrousel image onboarding is cut off

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10427]
# Problem
In dark mode it becomes visible that the walkie-talkie is cut off at the bottom.

![Screenshot_20200424-112146_Status PR](https://user-images.githubusercontent.com/35233054/80201281-2f603400-8624-11ea-9251-fa57fca2a105.jpg)

## Implementation
Requires investigation as to why the image is cut off.
Specification of image size, position and padding in [Figma](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A11631)

## Acceptance Criteria
Full image is shown

## Notes
cc @errorists for review

**Comment by emizzle** [comment]
@hesterbruikman, which device is this? I've tested on a Pixel 2 and cannot replicate. ![Imgur](https://i.imgur.com/tcnx1zS.png)

**Comment by hesterbruikman** [comment]
Ah interesting. This is on Galaxy S10e. Let me check iPhone 👀

**Comment by emizzle** [comment]
@hesterbruikman -- seemed to happen on narrow devices (where the title was pushed to two lines). See the comments in https://github.com/status-im/status-react/pull/10442 as there is some UI guidance needed.

**Comment by hesterbruikman** [comment]
Good catch, looks like that's it. Just checked iPhone 8 which is fine too. @errorists any advice on how to handle text on small screens in onboarding carousel?

**Comment by errorists** [comment]
@hesterbruikman I already commented in the issue

**Comment by hesterbruikman** [comment]
Fixed in #10442
