### ISSUE TITLE
"cannot locate account for address: [wallet address]" error when sending TX

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10423]
# Bug Report

## Problem

It was appeared while sending TX (from Wallet and 1-1 chat). No steps to reproduce so far for 

#### Expected behavior

No errors when sending TXs
#### Actual behavior

"cannot locate account for address: [wallet address]" error when sending TX

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

### Reproduction
- Open Status with funds
- Send transaction

### Additional Information
- Status version: release 1.2/develop
- Operating System: Android and iOS

#### Logs

TBD...

**Comment by churik** [comment]
@ceripower 
do you still have this issue?
if yes, would you mind to send us logs via shaking your phone?

**Comment by ceripower** [comment]
Hey @churik! Thanks for checking in. 

I needed to make the transaction urgently so I deleted the app, reinstalled it and tried again and it worked then. Apologies I can't retrieve a log for you relating to the original issue (or is it still helpful if I send something from the now-functioning app?)

**Comment by churik** [comment]
No, thanks! please send us logs if you have this issue in the future.

**Comment by flexsurfer** [comment]
this error is happening here in status-go https://github.com/status-im/status-go/blob/8b61d92d5834215fb06532c527b0bead7b4625d9/account/accounts.go#L159 it can't find KeyFile

**Comment by flexsurfer** [comment]
as an assumption problem might be in the checksummed address @gravityblast wdyt ? how do we   store and finding keyfiles?

**Comment by flexsurfer** [comment]
for example, if we're trying to sign tx with checksummed and not address in the from the field will be any difference do you lowercase address?

**Comment by gravityblast** [comment]
@flexsurfer I don't think it can be related because the address received is somehow sanitized with:
`addressObj := types.BytesToAddress(types.FromHex(address))`
And then the comparison is: `types.HexToAddress("0x"+accountKey.Address).Hex() == addressObj.Hex()`

so they  are always converted to an `Address` object and then serialized back to hex in the same way.

It's also strange that it happens only now, it would be easy if we can reproduce it.
