### ISSUE TITLE
"Offline, waiting for WiFi" chat status when Mobile network connected is misleading

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10424]
# Bug Report

## Problem

In `Profile` -> `Sync settings` -> `Mobile data` there is a setting **Use mobile data** 
When this setting is disabled and Status is used in mobile network in chats there is an info status in chats: "Offline, waiting for WiFi. Change"
Which is confusing because in fact user is still possible to receive and send messages. What is disabled if offline inbox history (receiving history messages from mailservers)

#### Expected behavior

(1) Updated translation of label in chat reflecting more accurate meaning to what **Use mobile data**  setting does and (2) maybe also concretise descriptions in Profile -> Sync settings -> Mobile data

#### Actual behavior

<img width="352" alt="Screenshot 2020-04-24 at 11 17 30" src="https://user-images.githubusercontent.com/8749671/80191193-09379580-861e-11ea-8da6-85db1f998cd3.png">

### Reproduction

- Enable on your device both `WiFi` and `Mobile network`
- Open Status and login to account 
- Navigate to `Profile` -> `Sync settings` -> `Mobile data` and disable **Use mobile data** if it's enabled  
- Disable WiFi on your device
- Open Chats main view (or any chat view)

### Additional Information
- Status version: release1.3/develop
- Operating System: Android and iOS

**Comment by Serhy** [comment]
cc @hesterbruikman @errorists. Your wisdom required. Maybe it's simple translation change

**Comment by hesterbruikman** [comment]
How about `Can't sync chat history. Check settings`

Where settings is a link to `sync settings`

Related Todo's are:
- Update the sync dialog
- Update Settings

**Comment by errorists** [comment]
after some follow up with @hesterbruikman we decided to change this to

`No Wi-fi, message syncing disabled. Settings` where Settings gets the underline and link

just making sure it isn't communicated as an error,
thanks!
