### ISSUE TITLE
Shadow-cljs part 2

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#10456]
The first step of the transition to shadow-cljs is considered done as iOS and Android are building, and dev commands are working. Some corners were cut in order to "limit" the chunk of work, so the following tasks are still pending:

* [x] move tests alongside their cljs counterpart instead of separate test dir
* [ ] move translations and js-files back into modules
* [x] restore hot-reloading
* [x] integrate re-frisk
* [ ] cleanup js imports
* [ ] fix warnings to enable clj-kondo

**Comment by flexsurfer** [comment]
i can take these two

-  restore hot-reloading
-  integrate re-frisk
