### ISSUE TITLE
PUK code field is not shown in "Generate account" flow in wallet  if user exceed 3 retries of passcode

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10452]
# Bug Report

## Problem

6-digit passcode instead of 12-digit PUK when 3 retries of the passcode are exceeded during "Generate account" flow in the wallet
![photo_2020-04-28 11 06 28](https://user-images.githubusercontent.com/4557972/80469109-65f9bf80-8940-11ea-82e3-076d14fe8e1e.jpeg)

#### Expected behavior
Can enter PUK-code, change passcode and proceed

#### Actual behavior
user can't generate account, flow is blocked

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard
- Go to wallet > Generate account > Enter wrong passcode 3 times

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 28/04/2020
- Operating System: Android

**Comment by churik** [comment]
cc @guylouis

**Comment by hesterbruikman** [comment]
fyi Also occurs when exceeding 3 attempts on sign in screen

**Comment by hesterbruikman** [comment]
Original issues

Countdown to freezing keys: https://github.com/status-im/status-react/issues/9285
When keys are frozen (not implemented): https://github.com/status-im/status-react/issues/9348 cc @churik @guylouis
