### ISSUE TITLE
Add sounds 🎶

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#10468]
### User Story

As a user, I want my actions to be accompanied with sound feedback so I know when an action I took was successful. I want these sounds to be unique so I can easily recognise them among others. 

### Description

The scope of this issue is to figure out where and how we can best accompany the visual user interface with an additional layer of feedback in the form of sounds. It might be an ongoing effort to include these as more actions become available. It might require an additional React Native library to enable sound playback  

**Here's the list of sounds and where they should be used**

---
Incoming push notification, outside of Status
https://www.dropbox.com/s/dh55jqy6028m1pe/Notification%20Out%20of%20App.wav?dl=0

---
Incoming in-app notification, inside Status
https://www.dropbox.com/s/d0c2etoh8q0pd3k/Notification%20In%20App.wav?dl=0

---
Sending a message in chat
https://www.dropbox.com/s/mu2jtqu1q7kji4o/Sending%20a%20message.wav?dl=0

---
Successfully signing and sending a transaction
https://www.dropbox.com/s/43vo12tuos8rk5k/Send%20Transaction.wav?dl=0

---
Pull to refresh / manually reloading wallet / manually fetching chat history
https://www.dropbox.com/s/tbmshr7arshh2hu/Syncronization.wav?dl=0

---
Error: incorrect password, incorrect seed phrase, other input returning an error
https://www.dropbox.com/s/kdgx23maivzbpzo/Error.mp3?dl=0

---
A setting is added to disable sounds

<img width="395" alt="Frame 22" src="https://user-images.githubusercontent.com/4932774/80620339-27e6c380-8a46-11ea-9b61-2fe786456e7b.png">

### Acceptance Criteria

Where possible sounds are added and can be heard correctly, until the list is complete the feature request can be left as pending. 

### Notes

All sounds were commissioned by us, designed by[ Sono Sanctus](http://www.sonosanctus.com), are licensed and paid for.
Thank you, if you have other ideas where can we include sound feedback be sure to leave your comments 🙏

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
