### ISSUE TITLE
Can't finish card setup if "Access key" flow is canceled on PUK / Pairing code screen if it is second account created with keycard

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10461]
# Bug Report

## Problem
Found during retesting flows in https://github.com/status-im/status-react/pull/10458
Endless spinner on "Confirm the passcode" state if "Access your key" flow was interrupted on 2 step (PUK / Pairing code screen)

#### Expected behavior
can finish setup

#### Actual behavior
Endless spinner after confirming passcode

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard and log out
- Access key> Enter Seed  Phrase > Keycard > Begin Setip
- Enter and confirm passcode
- Tap on "Cancel" on PUK / Pairing code screen 
### Additional Information

- Status version: PR build from https://github.com/status-im/status-react/pull/10458 
- Operating System: Android

#### Logs

[Status-debug-logs-3.zip](https://github.com/status-im/status-react/files/4550795/Status-debug-logs-3.zip)

**Comment by churik** [comment]
cc @guylouis @rasom

**Comment by rasom** [comment]
I can't reproduce it in `develop`

**Comment by churik** [comment]
@guylouis 
updated issue because it is reproducible only if it is 2 account on device, created with keycard.
Do we expect that users will use several keycards accounts in one device?
Anyway don't think that this is blocking issue because with happy path everything is OK with second account as well, so from my POV case is pretty rare.

**Comment by guylouis** [comment]
I agree this is a corner case ! i moved it to LOW priorities

**Comment by churik** [comment]
Cleared milestone as it is not blocker

**Comment by bitgamma** [comment]
@churik this should be fixed now

**Comment by churik** [comment]
Not reproducible on nightly 10/09/21
