### ISSUE TITLE
Research & spec centralized PNs

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#10462]
# Problem

Let's explore centralized push notifications as an *option* for all users, in order to improve retention rates.

## Implementation

We could bring back the old implementation of PNs, relying on Firebase.

Implementation strategy is up to technical team.

The requirements for this issue are to conduct research and write a spec for how centralized PNs could work.

## Acceptance Criteria

1. Spec filed in https://github.com/status-im/specs. Spec should include:
- Proposed solution
- Pros/cons considered—for other solutions considered, as well
- External components and/or dependencies
- Privacy/security/risk evaluation

One requirement for the feature: these should be optional and toggled off by default.

## Notes

[Design explorations in progress](https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=1241%3A69)

**Comment by hesterbruikman** [comment]
Cross posting proposed options and discussion by @flexsurfer: https://discuss.status.im/t/decentralized-push-notifications-for-ios/1718
