### ISSUE TITLE
Timestamp format in chat

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1048]
### Description
![image](https://cloud.githubusercontent.com/assets/11790366/25181945/caa48ac8-251b-11e7-92f1-e5c634127150.png)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Timestamp should be understandable to the user

#### Actual behavior
[comment]: # (Describe what actually happened.)
Timestamp is shown in period time format, but without AM/PM

**Comment by flexsurfer** [comment]
we need to use something like this https://github.com/fnando/i18n-js#date-formatting

**Comment by Alonski** [comment]
Should this be configurable or always use AM/PM or always use 24h time?
Willing this give this a shot when I have time

**Comment by flexsurfer** [comment]
hi @Alonski I think it should depend on user locale

**Comment by Alonski** [comment]
Can you point me in the direction of getting user locale?

**Comment by p14n** [comment]
`(def i18n (js/require "react-native-i18n"))
(def locale (.currentLocale I18n))`

**Comment by annadanchenko** [comment]
Expected after the fix: timestamp (if it's not Today or Yesterday) should depend on the user locale and show time in the format with (am/pm) or in 24-hour format.

Steps to reproduce:
- Open Status 
- Open Contacts
- Tap on Jarrad
- Send to Jarrad some text message
- Wait 2 days (or change date?) and check the timestamp of the sent message

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x1661f7146872ef013f544001b0c53b200cd7da1f](https://etherscan.io/address/0x1661f7146872ef013f544001b0c53b200cd7da1f)
Network: Mainnet
Paid to: dottedmag
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dottedmag** [comment]
I'll take this one.

**Comment by raghav-garg** [comment]
I can help you on this!

**Comment by dottedmag** [comment]
@flexsurfer Got this one working too. Please have a look.
