### ISSUE TITLE
Own profile is not opened from deep link

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10495]
# Bug Report

## Problem

Blocker for e2e 5780.
On tapping on `https://join.status.im/u/my_chat_key` user is redirected to home screen instead of own profile.

#### Expected behavior
Profile is shown

#### Actual behavior
User is redirected to home screen

#### Notes
Appeared on nightly 30/04/2020
The issue is not critical, but it is regression so good to fix in next release.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account, copy own chat key
- Close app
- Open browser and paste URL `https://join.status.im/u/my_chat_key` > Open in Status

### Additional Information

- Status version: nightly 30/04/2020
- Operating System: Android, iOS

**Comment by andremedeiros** [comment]
This one should wait until we spec out and define deeplinking/URI structure as per status-im/specs#112

**Comment by churik** [comment]
skipped in #10605

**Comment by churik** [comment]
Closed with universal QR code scanner
