### ISSUE TITLE
Markdown rendering doesn't respect spacing between paragraphs

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10499]
# Bug Report

## Problem
When entering text with multiple paragraphs, space between paragraphs is not rendered.

#### Expected behavior
When entering text with a space between paragraphs, text is displayed _with_ space between paragraphs

#### Actual behavior
When entering text with a space between paragraphs, text is displayed _without_ space between paragraphs

#### Notes
- Occurs on iOS and Android
- Occurs when message is written in Discord and written in Status
- Occurs in public chat and 1:1 chat

#### Acceptance Criteria
Space is shown when markdown includes space between paragraphs

### Reproduction
- Open Status
- Send message with multiple lines using return to add space in between lines
- View message rendered in chat

### Additional Information
- Status version: 0.14.0 (20200428025931)
- Operating System: Android & iOS

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
