### ISSUE TITLE
Newly added member of the group chat is not shown in chat settings (on 1st run only)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1049]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: On first run (when user just added a password and didn't close app): if create new group chat and modify it by adding new member then new member is not shown in members list. If close and open app again then new member is shown in the members list.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New member is shown in list of members right after it was added
#### Actual behavior
[comment]: # (Describe what actually happened.)
If it's first run of the app then new group chat member is not shown in list of members right after it was added. Old list of members is shown instead. Only if close and open app again then new member is shown in the members list.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install and run Status
- Create a password
- Create new group chat with 1 member: Console
- Open group chat settings and add 1 more member: First blood. Tap on Save
- Check that First Blood is shown in the members list

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6d61
* Operating System: Android and iOS

**Comment by coyotespike** [comment]
Not present on 0.9.4-11 (epic/chat-api), fwiw.
