### ISSUE TITLE
App does not respond to any tap if try to send requested sum with 15 digits after comma 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1050]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Other account is requesting 0.111122223333444. Account from iOS device taps on request and taps on /send command. After this nothing happens. Pending transaction screen is not shown. Tap on any element has no effect, only scrolling works. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When user taps on /send then Pending transactions screen is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
Pending transactions screen is not shown. Tap on any button has no effect
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Mm82T1VraU1keTA
- From another device: request 0.111122223333444 from iOS device
- As iOS device: tap on request 
- Tap on send button

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  0.9.6d64, 0.9.7 and 0.9.8
* Operating System: only iOS. Can reproduce on iPhone 7 plus with iOS 10.3.2. Can't reproduce on iPhone 6s with iOS 10.2.1

Console Log from iPhone 7 plus: 
[consolelog2.txt](https://github.com/status-im/status-react/files/1049542/consolelog2.txt)

**Comment by annadanchenko** [comment]
Note that on iPhone 7 plus there are several issues that I can reproduce only on this device. They might be connected: #1255 and #989

**Comment by annadanchenko** [comment]
Issue can be reproduced on simulator in Xcode simulator for iPhone 7 plus, iOS 10.3:

Send to Jarrad 0.1234567890123456 ether-> app freezes

**Comment by occamin** [comment]
Hey @annadanchenko, I'll pick this one up. Would you mind putting it in progress?

**Comment by flexsurfer** [comment]
hey @occamin any progress on this?

**Comment by occamin** [comment]
Hey @flexsurfer, 

Not much, I haven't had much time the last few weeks so you are welcome to pick it up. One insight is that I don't get a bug if I create 2 accounts on an iPhone 7 simulator and switch between them. The Eth request goes through as expected.

**Comment by annadanchenko** [comment]
can be reproduced with new `send/request` commands

**Comment by oskarth** [comment]
I've isolated the issue to the  `unsigned transaction view (views.list-item/view). The minimal failing case I have found is the following:

```
cljs.user=> (.fromWei js/Web3.prototype 111122223333440000 "ether")
"0.11112222333344"
cljs.user=> (.fromWei js/Web3.prototype 111122223333444000 "ether")
nil
```

Running the above in a stock JS REPL (web3.version api 0.18.1), this works:
```
> web3.fromWei(111122223333440000, 'ether')
"0.11112222333344"
> web3.fromWei(111122223333444000, 'ether')
"0.111122223333444"
```

Which seems curious. Our package.json has `"web3": "github:farazdagi/web3.js#geth/1.6.1-unstable"`. Comparing https://github.com/ethereum/web3.js/blob/f8aa391351166316c81d7a70dcc95d695c8005db/lib/utils/utils.js#L316-L320 and https://github.com/farazdagi/web3.js/blob/geth/1.6.1-unstable/lib/utils/utils.js#L316-L320 they seem identical to me.

Assuming the above indeed is the problem, it seems as if something is happening between CLJS and JS and BigNumber.

**Comment by rasom** [comment]
I thing that we have to treat such input as string, not as a number. `web3` will deal with such strings fine as it uses bignumber.js under the hood.

**Comment by oskarth** [comment]
To clarify, treating the number as a string also fails. Or did you mean something else?

```
cljs.user=> (.fromWei js/Web3.prototype "111122223333440000" "ether")
"0.11112222333344"
cljs.user=> (.fromWei js/Web3.prototype "111122223333444000" "ether")
Eval timed out!
No stacktrace available.
```

**Comment by asemiankevich** [comment]
I can reproduce the issue , iOs 10.3.3 build 0.9.9d110

**Comment by asemiankevich** [comment]
I tested it and can't reproduce anymore.
**Version/build:** 0.9.9d113 / 1429.113 iOS, 0.9.8-113-gce472c95+ Android
**Tested:**
- Other account is requesting 0,111122223333444. Account from iOS device taps on request and taps on /send command
- Go to 1x1 chat and Click send/request 0,111122223333444
- Create group chat and /send / request 0,111122223333444
- /send /request with dot
- /send /request 16, 17, 18 digits after comma/dot
