### ISSUE TITLE
New message from A is shown in the beginning of a group chat for all other users after user A cleared chat history

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1051]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Users A and B are in group chat. User A tap on "Clear history" and send new message to group chat. For user B new message from A is shown not at the end of conversation but in the beginning:
![message after clear history](https://cloud.githubusercontent.com/assets/6584810/25189113/88e45c64-2528-11e7-8c18-49882302f35b.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New message is shown at the end of the conversation
#### Actual behavior
[comment]: # (Describe what actually happened.)
New message is shown in the begining of the conversation
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
- As user A: create new group chat with B
- Exchange several massages in group chat with A and B
As userB:
- open group chat settings 
- Tap on Clear history
- As a result, there are no old messages shown for user B in chat
- Write new message to chat: "new message"
- As user A: check where is "new message" from userB is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  0.9.6d64
* Operating System: Android and iOS

**Comment by flexsurfer** [comment]
related to https://github.com/status-im/status-react/issues/1015
