### ISSUE TITLE
Allow Sticker Pack to be uninstalled

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10554]
# Feature Issue

Currently is only possible for users to Install a new Sticker Pack, to uninstall a sticker pack is not possible and would require wiping all the app data.  

### User Story

As a user I don't want to use a specific sticker pack anymore, or for whatever reason I want to uninstall it.

### Description

Pressing on the "Green Check Icon" would uninstall the sticker pack.

### Acceptance Criteria

User needs a way to uninstall sticker packs.

### Notes

This was noted during an update of a sticker pack with missing items, which were added later and current users that installed it would not be able to use these new packs until a reinstall of the pack.

**Comment by hesterbruikman** [comment]
@3esmit sounds like there is a need for something like `update` stickerpack. Is that right?

**Comment by 3esmit** [comment]
@hesterbruikman This issue is for the "uninstall" feature, which is something normal to have. We expect users not wanting some packs and wanting to remove from that list. 

Updates of sticker packs are also another feature, I didn't opened an issue about update because its less common that uninstalling a sticker pack. 
Currently Updates of Sticker packs are only possible by Status, but in future a proposal could be voted to update them. There are 4 users that have the sticker pack Stanny incomplete because the first pack had missing files which were added later through an update of the contenthash uri.

**Comment by errorists** [comment]
[Here are the designs](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=9564%3A492), once installed, the detailed view of a pack has a clearly labeled Uninstall button. Also, enabling updates is a great idea!

![Sticker Market -_ Stickers Bought](https://user-images.githubusercontent.com/4932774/81167844-3aa54f00-8f96-11ea-8c7e-3c1218eff580.jpg)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
