### ISSUE TITLE
dragonereum.io doesn't work on Android

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10560]
# Bug Report

## Problem

https://dapp.dragonereum.io dapp doesn't recognize status as wallet on Android

#### Expected behavior

Dapp asks for permissions

#### Actual behavior

Suggests to download wallet

#### Notes

Probably related to latest webview update and js injection on Android

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

Open dapp.dragonereum.io Dapp in status on Android 10

**Comment by flexsurfer** [comment]
ping @andremedeiros

**Comment by Serhy** [comment]
It works for me with nightly 5th of May on Android 9 and iOS13: - dapp.dragonnereum.io asks for Wallet permissions and sees my account after I allowed permissions.
However bug confirmed on Android 8.1 (when Dragonereum is loads view blinks and there is a blank webpage  displayed (with their discord button)

<img width="182" alt="Screenshot 2020-05-05 at 14 54 05" src="https://user-images.githubusercontent.com/8749671/81063351-4b938900-8ee0-11ea-9060-97c8f655ec61.png">

**Comment by flexsurfer** [comment]
it doesn't work on modern phones like samsung s10 with android 10
