### ISSUE TITLE
Dapp crashes!

### ISSUE THREAD

**Issue by Bild96** [status-im/status-react#10565]
**Errors and crashes, apparently related to infura and requests to it for Status Dapp stickers.**

incident details /* Pictures are included at the end of the report */ :

App version: 1.3.1 (20200502104447)
OS: ios
Node version: StatusIM/v0.52.2/darwin-arm64/go1.13.4
Mailserver: mail-01.do-ams3.eth.prod
----------------------------------------
Node Info
id: 712ff2e7c4de92242d5cde6f49136e74780026df84951f2b8a22656a49348a508a89f6cc0f304626927d67a24a44a950659431cf3fb1c3983282d79068041c9e
ip: 127.0.0.1
port: 0
----------------------------------------
Peers
id: 66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7
ip: 178.128.141.87
port: 30305?discport=0

id: ce559a37a9c344d7109bd4907802dd690008381d51f658c43056ec36ac043338bd92f1ac6043e645b64953b06f27202d679756a9c7cf62fdefa01b2e6ac5098e
ip: 134.209.136.123
port: 30305?discport=0

id: fbeddac99d396b91d59f2c63a3cb5fc7e0f8a9f7ce6fe5f2eed5e787a0154161b7173a6a73124a4275ef338b8966dc70a611e9ae2192f0f2340395661fad81c0
ip: 34.67.230.193
port: 30305?discport=0

id: cf5f7a7e64e3b306d1bc16073fba45be3344cb6695b0b616ccc2da66ea35b9f35b3b231c6cf335fdfaba523519659a440752fc2e061d1e5bc4ef33864aac2f19
ip: 47.75.221.196
port: 30305?discport=0

id: 0624b4a90063923c5cc27d12624b6a49a86dfb3623fcb106801217fdbab95f7617b83fa2468b9ae3de593ff6c1cf556ccf9bc705bfae9cb4625999765127b423
ip: 35.222.158.246
port: 30305?discport=0

id: 887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875
ip: 178.128.141.0
port: 30305?discport=0

id: c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49
ip: 178.128.142.54
port: 443

id: b77bffc29e2592f30180311dd81204ab845e5f78953b5ba0587c6631be9c0862963dea5eb64c90617cf0efd75308e22a42e30bc4eb3cd1bbddbd1da38ff6483e
ip: 47.75.10.177
port: 30305?discport=0

id: ac3948b2c0786ada7d17b80cf869cf59b1909ea3accd45944aae35bf864cc069126da8b82dfef4ddf23f1d6d6b44b1565c4cf81c8b98022253c6aea1a89d3ce2
ip: 47.75.88.12
port: 30305?discport=0

id: 385579fc5b14e04d5b04af7eee835d426d3d40ccf11f99dbd95340405f37cf3bbbf830b3eb8f70924be0c2909790120682c9c3e791646e2d5413e7801545d353
ip: 47.244.221.249
port: 443

id: ee2b53b0ace9692167a410514bca3024695dbf0e1a68e1dff9716da620efb195f04a4b9e873fb9b74ac84de801106c465b8e2b6c4f0d93b8749d1578bfcaf03e
ip: 104.197.238.144
port: 443

id: 0d9d65fcd5592df33ed4507ce862b9c748b6dbd1ea3a1deb94e3750052760b4850aa527265bbaf357021d64d5cc53c02b410458e732fafc5b53f257944247760
ip: 178.128.141.42
port: 30305?discport=0

id: e87f1d8093d304c3a9d6f1165b85d6b374f1c0cc907d39c0879eb67f0a39d779be7a85cbd52920b6f53a94da43099c58837034afa6a7be4b099bfcd79ad13999
ip: 35.238.106.101
port: 30305?discport=0

id: 44160e22e8b42bd32a06c1532165fa9e096eebedd7fa6d6e5f8bbef0440bc4a4591fe3651be68193a7ec029021cdb496cfe1d7f9f1dc69eb99226e6f39a7a5d4
ip: 35.225.221.245
port: 443

id: 8bebe73ddf7cf09e77602c7d04c93a73f455b51f24ae0d572917a4792f1dec0bb4c562759b8830cc3615a658d38c1a4a38597a1d7ae3ba35111479fc42d65dec
ip: 47.75.85.212
port: 30305?discport=0

id: 282e009967f9f132a5c2dd366a76319f0d22d60d0c51f7e99795a1e40f213c2705a2c10e4cc6f3890319f59da1a535b8835ed9b9c4b57c3aad342bf312fd7379
ip: 35.223.240.17
port: 30305?discport=0

----------------------------------------
May 4, 2020, 20:56:15

![image1](https://user-images.githubusercontent.com/52472445/80995983-66fa8780-8e3f-11ea-975b-9bb2364c7b90.png)
![image0](https://user-images.githubusercontent.com/52472445/80995994-69f57800-8e3f-11ea-9ea3-6954d52f3737.png)

**Comment by flexsurfer** [comment]
Duplicate  https://github.com/status-im/status-react/issues/10557
