### ISSUE TITLE
Change button "Sign with keycard" in dark mode

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10576]
# Bug Report

## Problem

In https://github.com/status-im/status-react/pull/10558:
![photo_2020-05-05 10 14 50](https://user-images.githubusercontent.com/4557972/81046708-453de680-8eb9-11ea-909a-81fbd2d42034.jpeg)

@errorists can you please assist to improve it?

**Comment by churik** [comment]
cc @guylouis

**Comment by errorists** [comment]
<img width="369" alt="Screenshot 2020-05-05 at 10 24 48" src="https://user-images.githubusercontent.com/4932774/81047440-a87c4880-8eba-11ea-926e-37a139ff6f40.png">

sure, use the turquoise colour found on the 'keycard' logo for the button background, white on everything else

**Comment by churik** [comment]
сс @flexsurfer
