### ISSUE TITLE
Open search engine when no url is detected in browser address bar input

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10575]
# Problem
When no url in the browser address bar is detected, desired, conventional, browser behavior is to open a search engine.

## Implementation
When no url in the browser address bar is detected open Duckduckgo with input as search query.

## Notes
Can be paired with #10473

**Comment by hesterbruikman** [comment]
cc @andremedeiros @errorists

**Comment by 3esmit** [comment]
Can we make this system even smarter? 

E.g. If we paste a transaction hash, or address, it could open etherscan.io. 

Not sure how useful it would be, just some food for thought.

**Comment by hesterbruikman** [comment]
Great idea! Thanks for documenting it here. I'm not sure about the privacy impact and any favoritism. Food for thought though. Maybe there's a site search that can be done one Duckduckgo instead.

Also, we could see if a submitting a [bang](https://duckduckgo.com/bang?c=Research&sc=Reference) makes sense

**Comment by andremedeiros** [comment]
If we're not using APIs we can make etherscan an option. Ethplorer wanted to partner up not that long ago and I'm sure we could re-ignite that conversation.

**Comment by hesterbruikman** [comment]
That could work. As long as we're smart about offering options so we don't get a (new) settings junk drawer. Maybe a shortcut after first time address lookup

**Comment by errorists** [comment]
The intended design for address bar includes recommendations for typing so I imagine we could reuse the same UI here: to match the string with browsing history, suggest a search engine search or if the entered string is a hash/address suggest ethplorer

<img width="1239" alt="Screenshot 2020-05-07 at 19 02 23" src="https://user-images.githubusercontent.com/4932774/81323389-97d3fa00-9095-11ea-82b1-d399b66863a7.png">

**Comment by hesterbruikman** [comment]
❤ great! That resolves favoritism and privacy concerns in one go as it's an explicit user action and choice

**Comment by du82** [comment]
Allowing users to type a URL on the Chat tab's search bar at the top and have an option to jump to the Browser tab with the site open would be great. This is just like how the QR code feature works currently, and is super convenient.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
