### ISSUE TITLE
Hide opened keyboard when user taps on chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1057]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In chat screen: to see more messages user taps on chat screen but keyboard is not hidden. We need to hide opened keyboard when user taps on chat.
![chat](https://cloud.githubusercontent.com/assets/6584810/25224369/7e499ddc-25be-11e7-98d4-2a4fa04ec671.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- User taps on chat empty space -> keyboard is hidden. 
- User taps on input field -> keyboard is shown
- User taps on commands -> relevant keyboard (text or numeric) is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
- User taps on chat -> keyboard is not hidden and takes half of the screen
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7ZjFMeTF6SjhwM1E
- Open Status 
- Open 1-1 chat
- Tap on input field -> keyboard is shown
- Tap on chat (I expect that keyboard will be hidden, so there is more space to read)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d67
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
I've re-checked behavior in other msg apps and the fix needs changes:
1. On iOS: it should hide keyboard when user taps on chat, as initially described  
2. On Android: nothing should happen when user taps on chat - this is the change. In the initial description both Android and iOS should hide keyboard.

Note: currently, initial fix is not in the develop build

**Comment by alwx** [comment]
@annadanchenko https://github.com/status-im/status-react/pull/1137
