### ISSUE TITLE
"Cannot call a class as a function" error when scrolling on account view (transaction history or assets)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10591]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "Cannot call a class as a function" error when scrolling on account view with several assets or in transaction history

#### Expected behavior
no error

#### Actual behavior
![photo_2020-05-06 16 01 34](https://user-images.githubusercontent.com/4557972/81186315-f1172d00-8fb2-11ea-8c00-e6ce5a731502.jpeg)

### Reproduction

Steps:
- create new multiaccount
- open wallet > manage assets > add several different assets (>5)
- open Status account
- scroll

### Additional Information

* Status version: nightly 06/05/2020
* Operating System: Android, iOS

#### Logs

[Status-debug-logs-5.zip](https://github.com/status-im/status-react/files/4587213/Status-debug-logs-5.zip)

**Comment by flexsurfer** [comment]
same for transactions history
