### ISSUE TITLE
Browser panel jumps

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1059]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

https://status-im.slack.com/files/andrey/F51RRA0AF/2017-04-20_13-57-50_com.zeptolab.cats.google.mp4

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

Sometimes it jumps once, but sometimes it jumps in cycle

**Comment by rasom** [comment]
duplicates https://github.com/status-im/status-react/issues/656

**Comment by flexsurfer** [comment]
I think it's different issues, in #656 webview jumps on android because keyboard appears and webviwe resizes, in this issue panel animation In a non-consistent state

**Comment by annadanchenko** [comment]
Instabug 0.9.6 reports:
* Android, Suggestions in console for /faucet jumps: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/367
