### ISSUE TITLE
Do not default the receiving Ethereum address to the ENS address

### ISSUE THREAD

**Issue by cyanlemons** [status-im/status-react#10594]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### Description

As a user, I believe that Status should not default the receiving Ethereum address to the same address that was used to register one's ENS username. Instead, it should always ask the receiving party which Status account they would like to use to accept the money.

If one wishes to send a crypo asset to a Status user, one normally has to request a receiving Ethereum address before such a transfer is possible. The user on the receiving end can **choose** the appropriate Status account for this transaction.

For example, one could have two separate Status accounts: one for the ENS username and one for personal transactions. It would be desirable that one could receive money from a family member without said transaction being publicly tied to one's chat identity.

However, the current behavior of the Status application is as follows: if you wish to send someone a crypto asset, the receiving address will default to the Ethereum address that was used to register their ENS username (if they have one) rather than force the sending party to request a receiving Ethereum address.

This is not an issue if one does not have an ENS username, as in this case Status will always request which Ethereum address to use. If one so desires, they can compartmentalize their financial transactions into various different Status accounts to achieve a greater degree of privacy.

### Notes

Of course, I am not suggesting to hide the Ethereum address associated with the ENS username as doing so would be impossible. However, I wish to provide Status users with the ability to only receive money on accounts that are not associated with their chat username/identity.

I believe that as a privacy-focused application, it should go without saying that your financial transactions should always be **separate** from your chat identity.

**Comment by flexsurfer** [comment]
ping @hesterbruikman

**Comment by hesterbruikman** [comment]
That makes total sense @cyanlemons

- You should be able to select the account you wish to use to register your ENS name
- Accept and share address should allow you to select the address that you would like to share

This is not trivial from a design perspective as we do not want to paralyze people with options. That said I'll add it to an epic on ENS improvements (registration and resolution)

cc @errorists @andremedeiros

**Comment by hesterbruikman** [comment]
> That makes total sense @cyanlemons
> 
> * You should be able to select the account you wish to use to register your ENS name
> * Accept and share address should allow you to select the address that you would like to share
> 
> This is not trivial from a design perspective as we do not want to paralyze people with options. That said I'll add it to an epic on ENS improvements (registration and resolution)
> 
> cc @errorists @andremedeiros

First bullet captured in #11872

**Comment by churik** [comment]
> First bullet captured in #11872

https://github.com/status-im/status-react/issues/10142

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
