### ISSUE TITLE
Endless spinner on adding new account in wallet (keycard only)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10622]
# Bug Report
## Problem
Can't add new account in wallet - endless spinner.

#### Expected behavior
New account is added 

#### Actual behavior
![photo!UNITO-UNDERSCORE!2020-05-11 12.20.08.jpeg](https://images.zenhubusercontent.com/5a12b3598a75884b908817f8/e35ded6f-5604-4631-8759-7cc16e6b8f98)

### Reproduction

* Open Status
* Restore multiaccount from seed phrase (select storage - Keycard)
* Go to wallet
* Add account -> generate account
* Enter your passcode

### Additional Information

* Status version: nightly 11/05/2020
* Operating System: Android

#### Logs
https://app.zenhub.com/files/52308441/156896c3-2fe7-4c6c-9ee5-ce67521cef9a/download

**Comment by rasom** [comment]
This is almost likely caused by @yenda's refactoring because `:hardwallet.callback/on-export-key-success` handles is not registered now.
