### ISSUE TITLE
Allow saving or sharing QR code as image file

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10628]
**Following https://github.com/status-im/status-react/issues/10627**

# Problem
Chat (key) QR is undergoing style changes to make it more suitable to share outside of the app and join.status.im (e.g. social media, website, slide deck). Once implemented, the user will also need to be able to save the QR code as an image to share it in other places.

Screenshots are not suitable as they are blocked by default and require manual actions to cut out the QR code.

## Implementation
Long press prompts action to download or share, depending on platform standard
cc @errorists to specify behavior

## Future Steps

**Comment by hesterbruikman** [comment]
Update after early investigation by @Ferossgp 

We draw QR codes as blocks in UI elements and they are not actually images, making it impossible to save them as image. 
In order to save the QR code, it's likely this needs to be implemented in status-go, serving status-react with images.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
