### ISSUE TITLE
Sticker pack is loading forever

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10638]
# Bug Report

## Problem

henrystats@discord
 it seems the issue with ens names (transaction failing) also affects sticker packs
i tried getting dogeth sticker packs few weeks ago- the transaction failed
if i try to get it now - i cant, it shows as if it is loading 

#### Expected behavior

it should be possible to purchase sticker again if transaction has failed

**Comment by churik** [comment]
It is still reproducible on v1.4.
In case if the transaction is dropped from network, I've got endless spinner on stickerpack

**Comment by hesterbruikman** [comment]
closing in favor of #11238
