### ISSUE TITLE
Requiring chainId for EIP712 signing

### ISSUE THREAD

**Issue by nicholasmueller** [status-im/status-react#10644]
# Bug Report

## Problem

Status dapp browser requires the chainId to be defined when signing transactions using eip712 domain typeddata, even though this field is defined as optional in the [eip712 spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md#definition-of-domainseparator).

```
Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.
```

#### Expected behavior

To be able to sign a transaction on networks that don't include the chainId in their signing hash.

#### Actual behavior

Signing transactions fail because chainId is missing in the typedData. 

#### Notes

Signing transactions without the chainId works in all other dapp browsers except Status.

![81656652-65454b00-9461-11ea-8a53-62ef88c791b8](https://user-images.githubusercontent.com/29919550/81917245-21884800-95ff-11ea-8bbe-aea9be6c48cc.png)

**Comment by cammellos** [comment]
@nicholasmueller could you please add some repro steps to the issue and re-open if still an issue?
Thank you!
