### ISSUE TITLE
Update framework for keycard to support pairing and commands in 1-1 chats

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10659]
# Problem

Currently there is no option to add automation tests for:
- pairing card flows (Recover from keycard)
- sending assets in one-to-one chat 
At attempt to send ETH in 1-1 chat (Ropsten) - "Sign and send" label on message is not changed

## Acceptance Criteria
- can recover predefined card using "Recovery card" flow
- can send ETH in 1-1 chat to ENS and using "Sign and send" label on message

**Comment by churik** [comment]
cc @rasom @guylouis

**Comment by guylouis** [comment]
do we agree that this is not blocking for release, right?

**Comment by churik** [comment]
yes
