### ISSUE TITLE
Upgrade eth-phishing-detect library

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10667]
# Bug Report

## Problem

 eth-phishing-detect library is outdated , we need to find a way to use a recent version for every release

**Comment by flexsurfer** [comment]
npm library was updated last time 2 months ago, we have to use the latest master instead

**Comment by flexsurfer** [comment]
cc @hesterbruikman

**Comment by hesterbruikman** [comment]
cc @0kok0 

Release cut for 1.4.1 is planned for today. Is it reasonable to include npm library for 1.5 (release mid-Jul)?

@flexsurfer or @0kok0 can you elaborate on the function of the library and in what use cases the user is exposed to phishing that an up-to-date library would prevent?
