### ISSUE TITLE
Redscreen crash on selecting "console" or "web3" suggestions

### ISSUE THREAD

**Issue by coyotespike** [status-im/status-react#1068]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...
On typing `//` in Console chat, user is presented with two suggestions: `console` and `web3`. After selecting either suggestion, the app crashes. These suggestions do not show in any other chat.

![screen shot 2017-04-20 at 12 33 48 pm](https://cloud.githubusercontent.com/assets/3118964/25244310/c09390c4-25c5-11e7-8025-8046adc4d652.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I expect nothing to show when I type `//`, or something else to happen after choosing a suggestion.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The app crashes with red screen: `re-matches must match against a string`

![screen shot 2017-04-20 at 12 34 03 pm](https://cloud.githubusercontent.com/assets/3118964/25244319/cda56ad0-25c5-11e7-82eb-f1274128c7f4.png)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Console. 
- Type `//`.
- Choose from suggestions, `console` or `web3`
- App crashes

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 
Make it not crash, or remove the suggestions?

### Additional Information

* Status version: `epic/chat-api` branch, 0.9.4-11

* Operating System: tested on Android only so far

**Comment by annadanchenko** [comment]
does not happen in 0.9.5 and later (real Android device Galaxy S6, Adroid 6.0.1)
