### ISSUE TITLE
Balance of custom tokens is not updated until app restart

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10699]
# Bug Report
## Problem
If you have some custom tokens in your account their balance is not shown just after adding, only after app restart.

#### Expected behavior
Can see balance after adding

#### Actual behavior

The actual of custom tokens amount is shown only after app restart

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Deposit some custom tokens to Status account(i.e. https://github.com/bokkypoobah/WeenusTokenFaucet )
* Go to Manage Assets -> Add custom token
* Pay attention to balance

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 21/052020
* Operating System: Android, iOS

#### Logs
[status_logs-2.zip](https://github.com/status-im/status-react/files/4663604/status_logs-2.zip)

**Comment by bitznbrewz** [comment]
I can confirm this on the latest version of the app from the app store.  I added aDai tokens to my account.  

I also noticed that really tracking any new token requires an app relaunch to update the numbers.  For example, today I added USDC and they didn't show up until I did an app restart.

**Comment by churik** [comment]
Thank you @bitznbrewz !
I thin you encounter https://github.com/status-im/status-react/issues/10786, will update issue
