### ISSUE TITLE
Check if cryptocompare returns USD value

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10695]
# Problem
User report: The case where Cryptocompare call is successful, but cannot deliver USD value is not handled. Currently, only an error state exists for the scenario that Status cannot connect to Cryptocompare or is not getting USD values altogether. There is not distinction for individual tokens.

e.g. https://www.cryptocompare.com/coins/ret/overview/ETH

### Current
When account holds tokens that have no USD conversion on Cryptocompare, USD value is not shown and token value is not included in accumulated value

### Expected
When account holds tokens that have no USD conversion on Cryptocompare, user is informed that USD value is not available

## Implementation
Check if Cryptocompare returns call. Check if return includes USD value. If call does not include USD value show <design tbd>

**Comment by hesterbruikman** [comment]
Discussed with @Ferossgp that it's probably better to:

- [ ] Add a check to `Manage assets`  > `Add custom token`
- If Cryptocompare or Coingecko (not sure which is used or both) returns selected currency value on check do nothing (i.e. add custom token)
- If Cryptocompare or Coingecko does not return selected currency value on check show dialog 'Status will not be able to show fiat values if you add this token' (copy to be confirmed when work starts)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
