### ISSUE TITLE
Commands are not shown in group chat to non-admin members after admin added new member

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1070]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Commands line is not shown to group members after admin user adds new member to the group. This happens with any chat screen if it's opened at the moment when admin added new member (not only to 1 particular group chat)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Commands line is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
Empty line is shown with no commands in it (like /browse /location...)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7cUlzTEdvWVJ2ZEk (on the left side there is non-admin member who opens another 1-1 chat)

You need to have group chat with 1 member. App should be run not 1st time
- As group non-admin user
-- Open Status
-- Open group chat. Check you see commands
- As group admin:
--  Open Status
--  Open group chat
--  Add new member to the group and tap Save
- As non-admin user
--  Check that new message is shown in group chat about new member added
-- Check that there are commands in commands line (currently they disappear) 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6d76
* Operating System: Android and iOS

**Comment by alwx** [comment]
Fixed in #1090
