### ISSUE TITLE
Status crashes with 'java.lang.AssertionError: No System TLS' error upon lauch

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10714]
# Bug Report

## Problem

Can't start Status (on Android 9). App crashes with 
```
05-26 17:57:18.676 21553 21635 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: Failed to create NativeModule "UIManager"
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: java.lang.AssertionError: No System TLS
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: 	at okhttp3.internal.Util.assertionError(Util.java:504)
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: 	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:258)
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1040)
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: 	at com.reactnativecommunity.webview.RNCWebViewManager.<init>(RNCWebViewManager.java:182)
05-26 17:57:18.684 21553 21635 E unknown:NativeModuleInitError: 	at com.reactnativecommunity.webview.RNCWebViewPackage.createViewManagers(RNCWebViewPackage.kt:13)
05-26 17:57:
...
```

It's all fine on Android 8.1 but on Android 9 I get crashes all the time on both Nightly Develop and PR builds

E2E tests which are running on Android 10, sometimes may may crash the session with the same error (but it's 1 of 20 times)
#### Expected behavior

Status app starts
#### Actual behavior

App crash when launch

![323](https://user-images.githubusercontent.com/8749671/82917159-b5510100-9f7b-11ea-988b-3b568fb70673.gif)

### Reproduction

- Install Status build https://status-im.ams3.digitaloceanspaces.com/StatusIm-200526-025900-2f65ce-nightly-universal.apk on Android 9
- Open Status

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: https://status-im.ams3.digitaloceanspaces.com/StatusIm-200526-025900-2f65ce-nightly-universal.apk
- Operating System: Android 9, Android 10

#### Logs

Full system logcat:  
[appcrash.txt](https://github.com/status-im/status-react/files/4683080/appcrash.txt)

**Comment by churik** [comment]
cc @hesterbruikman - for me looks like release-blocker

**Comment by hesterbruikman** [comment]
Is this on emulator or real device?

**Comment by flexsurfer** [comment]
both

**Comment by hesterbruikman** [comment]
Yes, that's definitely a blocker. Any thoughts on the cause yet? @flexsurfer are you available to investigate further?

**Comment by churik** [comment]
e2e caught it for 1 time on nightly 04/05/2020.
As we didn't see this on real devices, this issue was considered as emulator-specific and we tried to resolve it by updating caps for sauce-lab.

**Comment by Serhy** [comment]
I found that app starts fine if I restart device. 

If I Force Stop + Clear data of Status build - app keeps crashing on start. And even if I deinstall and install it again - all the time app crashes upon start. 

However any build (Nightly/PR) starts fine the first time after device restart.

**Comment by hesterbruikman** [comment]
[Status-debug-logs.zip](https://github.com/status-im/status-react/files/4700710/Status-debug-logs.zip)
