### ISSUE TITLE
Change keycard website link in keycard onboarding

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#10722]
In onboarding when user selects to store his keys on Keycard the first screen popped up is 
![image](https://user-images.githubusercontent.com/11461437/83122735-5521a280-a0d4-11ea-9fcf-b3fbd5207fa1.png)
The link used in "Learn more about Keycard" is https://keycard.tech

This link should be changed to https://status.im/keycard-integration

This new site is user oriented site with CTA to buy keycard

cc @hesterbruikman for info
cc @rasom

**Comment by hesterbruikman** [comment]
Also needs to be updated in Recover with Keycard flow

![Screenshot_20200528-114709_Status PR](https://user-images.githubusercontent.com/35233054/83126484-26f29180-a0d9-11ea-95c7-dc18d20031e7.jpg)

**Comment by rasom** [comment]
@guylouis @hesterbruikman I see "page not found" at https://status.im/keycard-integration

**Comment by rasom** [comment]
@guylouis do you mean that new link is https://keycard.tech? It is a bit unclear in the issue description.

**Comment by hesterbruikman** [comment]
@rasom as far as I know this is work in progress, but with high confidence content for https://status.im/keycard-integration will be ready and live by release. Let me verify in #marketing to be sure

**Comment by hesterbruikman** [comment]
Confirmed. https://status.im/keycard-integration  is the correct url and will be live when Keycard integration is released

> yes - this site will be live before the release. It is just about done and then Ill just need to coordinate with @jakubgs to deploy to production ahead of the release

**Comment by rasom** [comment]
thanks @hesterbruikman
