### ISSUE TITLE
Images 1.1  📷

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#10727]
# Problem
During the development of the [images PR](https://github.com/status-im/status-react/pull/10609) (great job everyone!) we agreed to cut some things from the scope of the PR and work on those separately. This issue tracks them.

## Implementation

* [ ] Allow copying and posting an image to and from clipboard and sending those images in chat [Design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=6990%3A226)
* [x] Allow queuing and sending multiple images in a batch. [Design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4188%3A600)
* [ ] Add a scale to full screen animation on opening and reverse on closing of the image preview view. 
* [ ] Allow dismissing the image preview by dragging and flicking the image outward [Design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4190%3A25540)
* [ ] Allow pinching to zoom and pan the image in preview
* [x] Add a 1px 10% black transparent inner border over the images in chat so that there's a subtle outline separation from background
* [ ] Add a placeholder for permission denied and iOs "selected photos"
## Acceptance Criteria
All of the above were addressed in a single PR or separately

## Notes
These interactions are quite common in apps but if you need help on any of them, let me know. thanks! :pray:

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
