### ISSUE TITLE
Tap near options button should work as tap on the button

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1072]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

![image](https://cloud.githubusercontent.com/assets/11790366/25273989/de6458d2-2696-11e7-90b1-385ff3145e89.png)

**Comment by annadanchenko** [comment]
Instabug feedback: "the three dot edit button to delete chats is small and difficult to press accurately. often it enters the chat instead"
https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/363
