### ISSUE TITLE
 Keycard reset is not possible during card pairing (and it leads to impossibility to pair card at all)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10739]
# Bug Report

## Problem

Leftover from  #10655 (issue 14)
If during pairing keycard enter 3 times wrong passcode or already trying to use frozen card - resetting account is not possible, so basically it is wasted card (you can only update it using kecard-cli and card reader)

#### Expected behavior
can set new PIN

#### Actual behavior
can't proceed after 2 step
<img width="181" alt="Monosnap 2020-05-28 16-02-29" src="https://user-images.githubusercontent.com/4557972/83151326-b6f60280-a0fc-11ea-8714-c211d2fe01e1.png">
[comment]: # (Describe what actually happened. Please include screenshots if possible.)

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

- open frow Recover with keycard
- enter valid pair code
- enter invalid PIN 3 times

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 1.4
- Operating System: Android

**Comment by churik** [comment]
cc @guylouis

**Comment by qoqobolo** [comment]
The issue is no longer relevant due to the ability to reset the Keycard implemented in #12055, so the described flow does not have a dead-end.
