### ISSUE TITLE
Disable images in Release 1.4 and enabled Group chats back

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10745]
# Bug Report

## Problem

We need to disable images in Release 1.4 (currently in StatusIm-200602-180557-03d29a-release-universal.apk it's enabled) 
Also we lost Group chats (but they are present in .e2e.env) - need to enable them back.

#### Expected behavior

No images icon in chats
Group chats are present on `Chats` -> `(+)`
#### Actual behavior

Images icon in chats
No Group chats are present on `Chats` -> `(+)`

### Reproduction

- Open Status and create new account
- Join 1-1 chat and check image
- Try to create Group  chat

### Additional Information

- Status version: 
StatusIm-200602-180557-03d29a-release-universal.apk
- Operating System: Android and iOS

**Comment by cammellos** [comment]
This has now been done, would you mind checking and closing the issue if it's all ok?

**Comment by Serhy** [comment]
Everything is fixed now! 
Thanks @cammellos !
