### ISSUE TITLE
Strip EXIF data from image

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10769]
# Problem
As a user I want to make sure no image can be traced back to me through exif data.

## Implementation
TBD

## Acceptance Criteria
All exif data is stripped before an image is send

## Notes
**Discussion**: Is it worthwhile to maintain date (without time)? This could help users receiving an image determine validity, i.e. was this an image of current events or past events?

**Comment by hesterbruikman** [comment]
@jarradh added stripping exif data to 1.5. What are your thoughts on the discussion note above? Wondering if leaving date makes sense or if that still poses privacy issues. Also depends if stripping exif is an all or nothing action and whether it's even possible to be selective

**Comment by hesterbruikman** [comment]
@0kok0 Any advice on the security side of the discussion note? (I.e. leaving date of image taken while removing all other image exif)

**Comment by 0kok0** [comment]
Def +1 for removing exif. 
When in doubt, I'd also remove the date, as we would then not need to parse the header on the receivers end; 
- exif headers were used to [hide payloads](https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/hiding-php-code-in-image-files-revisited/), so if we can skip it, we remove that vector
- we should make sure we also remove exif in case an image is send as an attachment, this is something that whatsapp for example does not.

**Comment by flexsurfer** [comment]
all meta is already stripped by react-native-image-resizer, @churik @Serhy could you confirm please and close the issue

**Comment by Serhy** [comment]
@flexsurfer yes, I can confirm exif (and ICC profile) data stripped for the image sent in chat. 
Tested with iOS13 and Android 8.
(1) Sending image (which has exif Data) from device storage or by (2) making a photo (which has exif data as well) - has no any data after I downloaded the image and checked again.
@hesterbruikman I guess we may close the issue then 👍
