### ISSUE TITLE
Dictated messages on IOS are shown with `obj` on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10772]
# Bug Report

## Problem
Messages, which are created with "Dictate" option on IOS, are shown with `obj` in the end of message on Android.

#### Expected behavior
No `obj` in the end of message

#### Actual behavior
<img width="186" alt="Monosnap 2020-06-08 12-55-08" src="https://user-images.githubusercontent.com/4557972/84022871-53cf6000-a987-11ea-8818-e346c905a982.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- IOS: Open Status
- IOS: Join public chat
- IOS: enable dictation
- IOS: dictate some message and send it to public chat
- Android: join same public chat

### Additional Information

- Status version: release 1.4
- Operating System: Android

**Comment by qoqobolo** [comment]
The issue is not reproducible on Nightly 2/12
