### ISSUE TITLE
No message in 1-1 chat when sending small amount of tokens to ENS name

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10777]
# Bug Report

## Problem
If sending small amount of tokens (0.00000001 BLT, 0.0000001 DGD, 0.0000000001 SNT) to user with ENS name - messages are not shown, but transactions are sent

#### Expected behavior
message in 1-1 chat

#### Actual behavior
transaction is sent, no message
![ezgif com-video-to-gif (20)](https://user-images.githubusercontent.com/4557972/84044766-45de0700-a9a8-11ea-82bd-b2bb0937bc28.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Start chat with ENS name
- Send 0.0000000001 SNT

### Additional Information

- Status version: release 1.4
- Operating System: Android, iOS

**Comment by bgits** [comment]
Seems like an issue I'm having. Someone sent me 1 ETH and it confirmed in wallet but no in chat notification. I was on iOS they sent from Android. Both have ENS usernames.

**Comment by churik** [comment]
cc @cammellos 
still very visible issue in commands
