### ISSUE TITLE
"Join Group" and "Decline invitation" are still displayed after removing user from group chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10776]
# Bug Report

## Problem

Buttons "Join Group" and "Decline invitation" are shown even user was removed from group chat.

#### Expected behavior

[comment]: # (Describe what you expected to happen. Please include designs if possible.
User can't join or decline invite to group chat if he was removed 

#### Actual behavior
![photo_2020-06-08 15 06 02](https://user-images.githubusercontent.com/4557972/84033911-e37e0a00-a999-11ea-9655-e8164b63bbf8.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Invite User A to it
- Remove User A from Group chat
- As User A: check group chat

### Additional Information

- Status version: release 1.4
- Operating System: Android, iOS

**Comment by errorists** [comment]
also, the second button `Decline…` is not updating its blue colour for dark mode :)

**Comment by hesterbruikman** [comment]
Small comment on expected behavior to be more specific:

Expected: 'Join Group' and 'Decline invitation' are only shown if user was invited and user has not been removed

As it should be possible to show Join Group and Decline invitation if the user is invited again after being removed.
