### ISSUE TITLE
Standard settings for Push notifications are turned off by default in status app (Android 10)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10773]
As a user 
I would like to have "Show on lock screen", "Display popup windows while running on background",  "Notification badges" enabled by default
So that I have a better out-of-the-box experience when receiving notifications

#### Acceptance criteria
 "Show on lock screen",  "Display popup windows while running on background", "Notification badges" settings are enabled by default.

### Additional Information

- Status version: release 1.4
- Operating System: Android 10
- Device: Xiaomi Mi 9T Pro

**Comment by hesterbruikman** [comment]
@errorists can please add designs to enable notifications during onboarding to this issue?

**Comment by errorists** [comment]
@hesterbruikman they're [here](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A13229), however the copy there likely needs adjusting as afaik we don't send PNs on transaction updates?

**Comment by hesterbruikman** [comment]
Thanks. And yes, the copy needs an update:

Android
- Status will notify you about new 1:1 and group chat messages. You can edit your notification preferences later in settings.

iOS
- TBD

WDYT about the above for Android? @errorists @yenda

**Comment by flexsurfer** [comment]
@hesterbruikman so this issue about specific notification options are not enabled by default on the specific phone, can we create a separate issue for onboarding ?

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/issues/10899

**Comment by hesterbruikman** [comment]
@churik I think we can save this to bundle with Notifications on iOS, in spite of it being an Android issue. Wdyt? 

Btw, I can't find these settings on Samsung Galaxy S10e. Can they be hardware specific?  🤔

**Comment by churik** [comment]
Yes, we can. BTW, yesterday I've got an update for Android, so I'll recheck if it is still the case.


> Btw, I can't find these settings on Samsung Galaxy S10e. Can they be hardware specific? 

They can be hidden in general settings (Lock screen notifications, Notifications, Notification Badges)
In my specific case I can manage them from both general or app settings.

**Comment by churik** [comment]
Still the case:
![photo_2020-07-16 12 31 13 jpeg 2020-07-16 12-31-43](https://user-images.githubusercontent.com/4557972/87661088-554b2f80-c760-11ea-8ae5-1cdfb39ab00c.png)


>  I think we can save this to bundle with Notifications on iOS, in spite of it being an Android issue. Wdyt?

Agreed 👍

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
