### ISSUE TITLE
Implement rate limiting by size

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#10775]
### User Story

As a user
I want to be protected against an attacker sending multiple large files
So that I won't be consuming too much bandwith

### Description

Currently we only rate limit data based on the number of packets, but an attacker could potentially send a lower amount of packets so that it does not breach the limit, each one of a large size, which would result in an excessive data consumption.

### Technical details

This will only be a bland mitigation, as currently how to prevent spam is an open question.
We already have limits in place for the number of messages, this can be easily extended to check for packet size.

**Comment by cammellos** [comment]
Specs PR: https://github.com/vacp2p/specs/pull/141
Implementation PR: https://github.com/status-im/status-go/pull/1989

**Comment by hesterbruikman** [comment]
@cammellos as #1989 was merged, can this issue be closed or is it open to include more rate limiting functionality?
