### ISSUE TITLE
"Next" button is overlapped by keyboard on "Enter your seed phrase" and on "Create a password" screens

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10789]
# Bug Report

## Problem
![image](https://user-images.githubusercontent.com/4557972/84144241-3918ec00-aa58-11ea-9a93-1ce1fc30b83a.png)

![image](https://user-images.githubusercontent.com/4557972/84155621-d419c200-aa68-11ea-8bf0-c325f267e080.png)

Not reproducible on release 1.4

#### Expected behavior
Next button is visible

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Proceed to Access Key > Enter seed phrase

### Additional Information

- Status version: nightly 09/06/20
- Operating System: Android only

**Comment by Serhy** [comment]
Has been fixed by https://github.com/status-im/status-react/pull/10778 
Closing this issue
