### ISSUE TITLE
"Make admin" icon is not shown on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10785]
# Bug Report

## Problem

![photo_2020-06-09 11 25 39](https://user-images.githubusercontent.com/4557972/84130750-f5b48280-aa43-11ea-913f-3428482fa7ce.jpeg)

#### Expected behavior
icon is shown

#### Actual behavior
no icon

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create group chat
- Go to group info 
- Open user options

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 1.4
- Operating System: iOS

**Comment by Ferossgp** [comment]
fixed in https://github.com/status-im/status-react/pull/10686
