### ISSUE TITLE
If 2 keycard multiaccounts are opened on one device it is not possible to log in to second multiaccount until you manually log out from the first multiaccount

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10784]
# Bug Report

## Problem
When 2 keycard multiaccounts are opened on device and you close app when logged in to 1 multiaccount, at attempt to login to 2 multiaccount you'll get an endless processing spinner.

#### Expected behavior
Can login

#### Actual behavior
can't login to 2 multiaccount; 
can't create or restore new multiaccount with keycard.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create keycard multiaccount A and B
- Close app when logged in to account B
- Try to login to account A

### Additional Information

- Status version: release 1.4
- Operating System: Android

#### Logs

[Status-debug-logs-9.zip](https://github.com/status-im/status-react/files/4752709/Status-debug-logs-9.zip)

**Comment by churik** [comment]
сс @guylouis

**Comment by rasom** [comment]
I can't reproduce this issue in `develop`.

**Comment by rasom** [comment]
@churik 
It is likely that you tapped a wrong card when tried to reproduce that bug and we do not handle a wrong card properly there, this causes endless spinner.

**Comment by churik** [comment]
@rasom 
indeed, behavior 'can't log in to 2 multiaccount;' but still reproducible second part of the issue.

so steps for it:
- Open Status
- Create keycard multiaccount A 
- close app
- try to create multiaccount B with new keycard

On "Begin Setup" stage endless "Processing" state is shown.
To fix this behavior you need manually log out from multiaccount A
