### ISSUE TITLE
Translation JSON files with '_' don't work

### ISSUE THREAD

**Issue by jinhojang6** [status-im/status-react#10803]
Used the latest apk file (StatusIm-200611-025900-db202f-nightly-universal.apk)

**Test cases:**
Changed the device language into
- Korean
- German
- Turkish
- French
- Indonesian
- Spanish (Colombia)
- Simplified Chinese -> zh.JSON
- Traditional Chinese -> zh_TW.JSON
- Brazilian Portuguese -> pt_BR.JSON

**Bugs:**
Language JSON files with `_` showed wrong translations

- Brazilian Portuguese -> showed English
- Traditional Chinese -> showed simplified Chinese

---
I think the app cannot handle any language JSON files with underscores at the moment. All the languages worked well before.

(I guess they worked well until we refreshed [i18n_resources.cljs](https://github.com/status-im/status-react/blob/develop/src/status_im/i18n_resources.cljs)).

**Comment by 3esmit** [comment]
The file for pt_BR is actually named `pt_br.json` instead of `pt_BR.json` https://github.com/status-im/status-react/blob/develop/translations/pt_br.json

maybe its a case sensitive issue? Not sure, because zh_TW is `zh_TW.json` and it's reported as not working as well?

**Comment by churik** [comment]
сс @hesterbruikman  - should include it in 1.4?
(IMO would be better to 1.4.1)

**Comment by hesterbruikman** [comment]
Agree. It's a shame, but after go ahead to Marketing I don't consider additions to release an option unless it's a blocker. Will add to 1.4.1 list on Zenhub

**Comment by flexsurfer** [comment]
@jinhojang6 fixed Brazilian by renaming json `pt_br.json -> pt_BR.json` not sure about Traditional Chinese, because for me iphone uses   `:zh-Hant-US` which falls to `:zh`

**Comment by jinhojang6** [comment]
Thanks @flexsurfer! This is weird because traditional Chinese worked well before.
