### ISSUE TITLE
No contract events reaching the frontend

### ISSUE THREAD

**Issue by benjaminaaron** [status-im/status-react#10809]
# Bug Report

## Problem
I can't find a way to make contract events reach my frontend in the Status browser. I reduced our [Fin4-dApp](https://github.com/FuturICT2) to the absolute minimum and made a few test cases.
👉  Code at [benjaminaaron/dev-dApp](https://github.com/benjaminaaron/dev-dApp), live at [dev.finfour.net](https://dev.finfour.net):

<kbd>
  <img src="https://user-images.githubusercontent.com/5141792/84565647-c5822200-ad6a-11ea-98d9-01a8fb49e878.png">
</kbd>

#### Expected behavior

[comment]: # (Describe what you expected to happen. Please include designs if possible.)
Contract events to reach the frontend.

#### Actual behavior

[comment]: # (Describe what actually happened. Please include screenshots if possible.)
I made screenrecordings with the _dev-dApp_ open on desktop browser and in the latest Status nightly build (visible via Chrome remote devices DevTools). One after the other I am clicking the four different ways I implemented to trigger the event on the smart contract. As you can see, while the desktop browser receives the events, they don't get through on the Status browser. Whereas the transaction confirmations do land in the console. I tried the exact same thing with MetaMask mobile: also no contract events (that might very well mean it is totally my fault??).  Here is the [link to a Google Drive folder with both mp4 files in it](https://drive.google.com/drive/folders/19zQISRX17D0VxDd900X4fI2a2HxiDkw9?usp=sharing) (video quality better when downloaded).

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
1. Go to `https://dev.finfour.net` on Status and on desktop
2. Click on `Add contract` and `Subscribe to TestEvent using web3`
3. Now you should be subscribed via drizzle _and_ via web3 to `TestEvent` from the `DevContract`
4. Use the four ways to trigger the contract event and watch the contract events coming through on desktop but not on mobile

### Additional Information

[comment]: # (Please do your best to fill this out.)
 - Device: Xiaomi Mi 9
 - Operating System: MIUI Global 11.0.9 / Android 10
 - Status version: 1.4.0 (20200612025936)

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
...
```

**Comment by benjaminaaron** [comment]
**Update**: I included `ethers` and that works! 🥳 
drizzle, web3 and @truffle/contract don't.

**Comment by 3esmit** [comment]
@hesterbruikman I am experiencing this bug. I am developing a DApp, currently only running on testnet, and the events are not appearing. 

To test it, go to ropsten and load `teste123.eth`. The footer have a blocknumber, which does not update. In metamask it updates, try changing metamask to Ropsten and load https://dweb.link/ipfs/bafybeig57dtxm6huqm55zwzmkgnsdgewj4adj4nnhd4h67ma4tcesvbjli/

This was previously reported at https://github.com/status-im/status-react/issues/8577

**Comment by churik** [comment]
Closing in favor of https://github.com/status-im/status-mobile/issues/8577, added this issue as a reference.
