### ISSUE TITLE
Can't recover keys from keycard

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10808]
# Bug Report

## Problem
No next button on "Enter pairing code" stage
![Sauce Labs | Test Details: 2020-06-12 16-41-29](https://user-images.githubusercontent.com/4557972/84514615-99639400-accb-11ea-8696-8ce082b68641.png)

#### Expected behavior
Can pair device with keycard

#### Actual behavior
No next button on "Enter your pairing code" screen

### Reproduction
**Prerequisites:** have initialized keycard

- Open Status
- Go to "Recover with keycard"
- Begin recovery
- Enter pairing code

### Additional Information

- Status version: nighty 12/06/2020
- Operating System: Android

**Comment by churik** [comment]
cc @guylouis

**Comment by guylouis** [comment]
@churik 
which means that recover from keycard is broken then isn't it ?

**Comment by churik** [comment]
yes, it is broken in current nightly
