### ISSUE TITLE
Message description should always be located below the image in chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10801]
# Bug Report

## Problem
Leftover from https://github.com/status-im/status-react/pull/10609.
Expected that is you attach some text to image, it is always will appear after image in chat. Currently it sometimes appears below, sometimes under image.

#### Expected behavior
description is below

#### Actual behavior
<img width="183" alt="Monosnap 2020-05-27 16-26-21" src="https://user-images.githubusercontent.com/4557972/83033035-e2aeb500-a036-11ea-9a61-f87f158df70a.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Start 1-1 chat
- Send several images with description

### Additional Information

- Status version: nightly 11/06/2020
- Operating System: Android, iOS

**Comment by Ferossgp** [comment]
Actually image and text are sent as 2 different messages, so in that case the messages are not part of the image. The text which is attached to the image is `Update to latest version to see a nice image here!` and it is hidden in the UI

**Comment by hesterbruikman** [comment]
@Ferossgp does this mean that it's a time stamp issue? The client doesn't know the message is related to the image and order depends on how quickly image and text message travel through the network?

**Comment by Ferossgp** [comment]
Yes this is the problem of order, but the problem root I described https://discordapp.com/channels/624205794384281629/626738033701683200/740880403245826120
