### ISSUE TITLE
Commands are not shown for new 1-1 chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1082]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Contact Mulder added Scully to his Contacts and sends first message. Scully opens 1-1 chat and it does not contain commands. If Scully sends any reply to Mulder then commands are shown.

 ![no commands for new chat](https://cloud.githubusercontent.com/assets/6584810/25379927/c4fbd936-29ae-11e7-9312-456e7f19c088.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Commands are shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
No commands are shown, only empty line
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- As Mulder:
1. Open Status 
2. Add Scully to the contacts
3. Send her any message
- As Scully:
1. Open Status
2. Open Chats
3. Open new chat with Mulder (who is not yet in the Contacts)
4. Check if commands are shown (/browse, /location, etc)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6
* Operating System: Android and iOS

**Comment by alwx** [comment]
Fixed in #1090
