### ISSUE TITLE
Nix can't handle annotated tags

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#10825]
# Description
Some developers have encountered the following error when building with Nix:

```
error: cannot update ref 'refs/heads/v2.0.3-status': trying to write non-commit object 53e823d1bd0dffd7bf799ccfb8fccd3e4023d00f to branch 'refs/heads/v2.0.3-status'
```

This happens because Nix's `builtins.fetchgit` cannot handle annotated tags: https://github.com/NixOS/nix/issues/2385
This has been noted in the docs but has been since removed from them: https://github.com/NixOS/nix/commit/ae244af242ca3621e5a3b9196f27d9fcbf297266

# Reproducing
Here's a simple Nix derivation for fetching a `v2.0.3-status` tag of `react-native-audio-toolkit.`:

```nix
(import <nixpkgs> {}).stdenv.mkDerivation {
name = "test";
src = builtins.fetchGit {
url = "https://github.com/tbenr/react-native-audio-toolkit.git";
ref = "v2.0.3-status";
};
}
```

And it fails the exact same way:

```
> nix-build --show-trace
error: cannot update ref 'refs/heads/v2.0.3-status': trying to write non-commit object 53e823d1bd0dffd7bf799ccfb8fccd3e4023d00f to branch 'refs/heads/v2.0.3-status'
error: while evaluating the attribute 'src' of the derivation 'test' at /home/sochan/soft/nix-fetchgit-test/default.nix:2:3:
program 'git' failed with exit code 1
```

But it fetches it without issues if I change the `ref` to be `v2.0.3`:

```
> nix-build --show-trace
these derivations will be built:
/nix/store/gm72l91mw8bd5wy9s84bzca4xi557xyd-test.drv
building '/nix/store/gm72l91mw8bd5wy9s84bzca4xi557xyd-test.drv'...
unpacking sources
unpacking source archive /nix/store/vg34709b4dgkz4hndq3gzhhk2f66ngyr-source
source root is source
...
```

And when I checkout the repo the issue is clearly that `v2.0.3-status` is an annotated tag:

```
> git for-each-ref | grep v2.0.3
96197e3d6643d47b86267bcc6cb29cb26536e226 commit refs/tags/v2.0.3
53e823d1bd0dffd7bf799ccfb8fccd3e4023d00f tag refs/tags/v2.0.3-status
```

# Solutions
Currently there is no known solution other than not using annotated tags.
Which should be pretty simple considering you have to explicitly provide a `-a`/`--annotate` flag to `git tag` in order to make your tag an annotated one.

**Comment by jakubgs** [comment]
This is not resolved and still a known issue.

**Comment by churik** [comment]
@jakubgs still relevant?

**Comment by jakubgs** [comment]
These are still open:

* https://github.com/NixOS/nix/issues/3701
* https://github.com/NixOS/nix/pull/6766

So yes.

**Comment by cammellos** [comment]
@jakubgs I'll close this as it's non actionable from our side (we need to do some spring cleaning :) ), feel free to re-open if any work can be done to overcome the issue, thank you
