### ISSUE TITLE
'ERC20' instead token name in History tab for the custom token just added 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10838]
# Bug Report

## Problem

After adding custom token in the list of tokens and you have transactions in the history then custom token name will default to ERC20 instead normal token name.
After re-login the name picked up and displays fine.

#### Expected behavior

Token name displays fine without re-login in Transaction History after adding token name.

#### Actual behavior

ERC20 displays Transaction History after adding token name.
<img width="338" alt="Screenshot 2020-06-17 at 18 28 07" src="https://user-images.githubusercontent.com/8749671/84917725-5db03c00-b0c8-11ea-90f5-a80f010ae8ec.png">

### Reproduction
1)Open Status (switch to Ropsten)
2)Deposit some custom tokens to Status account(i.e. https://github.com/bokkypoobah/WeenusTokenFaucet )
3) Go to Manage Assets -> Add custom token
4) Send any transaction with this token
5) Open History tab (and Transaction details) and check token name with this token

### Additional Information
- Status version: develop, release 1.4
- Operating System: Android and iOS

**Comment by churik** [comment]
disabled check in TC 6208  - uncomment after fix

**Comment by churik** [comment]
relevant on 1.15

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
