### ISSUE TITLE
App crash on 1st run if tap on message to set password

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1084]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Installed app, tap on  message to set password -> app crashes

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Password can be typed
#### Actual behavior
[comment]: # (Describe what actually happened.)
app crashes
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Y0NWTjJfdG9EdnM
- Install Status
- Tap on message to set password

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6-10
[comment]: # (Android or iOS.)
* Operating System: Android and iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
[20172504152643-logcat.txt](https://github.com/status-im/status-react/files/955185/20172504152643-logcat.txt)

**Comment by alwx** [comment]
Please, re-check it in the newest version. It has been fixed by this commit: https://github.com/status-im/status-react/commit/9d975c497f7ffadc5656c3e428d0b57e6dbd3adc

**Comment by annadanchenko** [comment]
@alwx yes it's ok now. I'm closing the issue.
