### ISSUE TITLE
It's not possible to remove the notification of background service

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10840]
# Bug Report

## Problem

The current notification system leaves an annoying notification that does nothing, and is displayed whenever Status have notifications enabled.

#### Expected behavior

I expected that I could cleanup that notification. I expected that this notification would appear only once.

#### Actual behavior

The notification is locked there, I can't hide it without disabling the notification system.

#### Additional information

Build StatusIm-200616-155619-798c46-pr-universal.apk

**Comment by yenda** [comment]
You can't remove it it's Android guidelines, a background service must display a notification as long as it runs. To make it more useful though I added a stop button on a pending PR and made it touchable so that tapping open the app.
