### ISSUE TITLE
Status is giving notifications when there is nothing new

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10841]
# Bug Report
## Problem
I created a new account to review a translation, using Status PR, which only had that account on it. 
I enabled notifications, looked around the texts, and turned off the screen. Randomly I get a notification, when I unlock the device to see the notifications, the only thing that's changed is the age of the background service notification.

#### Expected behavior
Be notified only on new messages (of my contacts).

#### Actual behavior
Notification happens even if I am not in any room, or have any contacts. Seems like the background service is restarted and it notifies again. 

#### Notes
Might be related to #10840

Tested with this build https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200608-161609-c10166-universal.apk

#### Acceptance Criteria

* [ ] Background service don't make a notification.
* [ ] Notification only happens on new messages.

#### Additional information
Build StatusIm-200616-155619-798c46-pr-universal.apk

**Comment by churik** [comment]
@3esmit can you please specify Android version and device?
after what time approximately notifications are starting to appear?
Thank you for reporting, we are investigating it.

**Comment by 3esmit** [comment]
Android 8.1.0

Takes about 1 hour to happen. Open Status and turn off screen. Sometime later it will happen. Is randomly happening, seems like that the background service is killed and restarted, causing the problem.

**Comment by yenda** [comment]
What is the device

**Comment by churik** [comment]
Didn't happen to me on Android 10 / Xiaomi Mi Note 9

**Comment by 3esmit** [comment]
> What is the device

One Plus 5T

**Comment by yenda** [comment]
@3esmit yeah that is what I suspected, I have a OnePlus too, afaik it's the only Android flavor that doesn't respect the guideline. They have a very aggressive battery saving algorithm that ends up killing anything that isn't on their whitelist, which is just a bunch of Fitness apps such as Google Fit. The solution that seems to work is:


> - In the app switcher (bottom right square button of your phone screen) press the 3 dots on the top right corner above status app
> - tap on Lock
> - press the 3 dots again and go to App Info, tap advanced at the bottom then Battery optimization
> - select Don't optimize and you are set

**Comment by hesterbruikman** [comment]
@3esmit did the solution suggested by Yenda work for you? If it did I suggest closing the issue as there's not much more we can do other than work on an alternative (less privacy focused) implementation that friendlier on battery life

**Comment by 3esmit** [comment]
Yes, it helped, however Android keeps killing the background service after some time.
