### ISSUE TITLE
Devices Pairing "Learn more" link is broken

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10843]
# Bug Report

## Problem

When I try to "Learn more" about Pairing, the link takes me to `https://status.im/tutorials/pairing.html` which is a dead link. I couldn't find the new "pairing tutorial" link. 

#### Expected behavior

No broken links.

#### Additional information

Build StatusIm-200616-155619-798c46-pr-universal.apk

**Comment by churik** [comment]
@hesterbruikman IMO better to fix it ASAP

**Comment by jakubgs** [comment]
The pairing page was removed in this massive documentation "update" by B9Lab:
https://github.com/status-im/status.im/commit/0c502810
This isn't the only thing they removed without care.
Would we want to re-add it?

**Comment by hesterbruikman** [comment]
@guylouis @rajeevgopalakrishna do you know if we have content for a pairing tutorial? Alternatively, maybe we can direct to the Keycard FAQ section?

**Comment by jakubgs** [comment]
We still have the content in history:
https://github.com/status-im/status.im/blob/babef192/source/tutorials/pairing.md
Unless that's outdated.

**Comment by churik** [comment]
It is a bit outdated. I can change it.

**Comment by rajeevgopalakrishna** [comment]
I don't have the context here but this looks like it's talking about pairing/syncing Status apps on multiple devices.

Are we talking about that or pairing Keycard with Status app?

**Comment by churik** [comment]
no, we are talking about device syncing.

**Comment by hesterbruikman** [comment]
Apologies for the ping @rajeevgopalakrishna ! I read this as Keycard pairing

**Comment by churik** [comment]
@jakubgs  where ca I post updated content? I can post it here and you push it wherever it is needed
Sorry for delay

**Comment by jakubgs** [comment]
Why not make it a docs page on the main site?
https://github.com/status-im/status.im/tree/develop/source/technical

**Comment by churik** [comment]
made a PR, take a look https://github.com/status-im/status.im/pull/531
