### ISSUE TITLE
Mailserver "Automatic selection" get stuck on timeouting mailserver 

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10855]
# Bug Report

## Problem

When a mailserver is timeouting, as this:
```
 > ./build/bin/node-canary -log=WARN -mailserver='enode://ee2b53b0ace9692167a410514bca3024695dbf0e1a68e1dff9716da620efb195f04a4b9e873fb9b74ac84de801106c465b8e2b6c4f0d93b8749d1578bfcaf03e@104.197.238.144:443' 
ERROR[06-22|09:10:28.751] Error waiting for mailserver response    package=status-go/cmd/node-canary error="timed out waiting for mailserver response"
```

The messages keep loading forever, and I need to manually disable automatic selection, and try another.

## Current Behavior

By default, messages don't load and no error is given.

## Expected Behavior 

It should detect that a node is not answering and move on to next.

## Additional info

This was happening on:

```
mail-01.gc-us-central1-a.eth.prod: "never answers" (infinite loading)
mail-02.gc-us-central1-a.eth.prod: "never answers" (infinite loading)
mail-03.gc-us-central1-a.eth.prod: "never answers" (infinite loading)
```

And was caused, according to @jakubgs: "the 3 hosts ran out of space, but for some reason I didn't get a prometheus metric alert"

App version : 1.3.0
Device: OnePlus 5T
Android Version: 8.1.0

**Comment by jakubgs** [comment]
Correct, the issue was caused by no free disk space left. But I think there's two issues here:

1. Connecting to a history node with disk space issues:
  - `timed out waiting for mailserver response`
  - This error doesn't make much sense and `status-go` could probably be improved in that regard
2. The app itself doesn't attempt to pick another mailserver despite the so called "timeout".

**Comment by jakubgs** [comment]
Looks like disk space run out because of new db backups I added, but the retention is too high, so it ate up all disk space. Will fix that today.

**Comment by jakubgs** [comment]
Okay, I see what was the issue. We had retention set right to `3`:
```yml
mailsrv_pg_bb_backup_retention: 3
```
https://github.com/status-im/infra-eth-cluster/blob/d8dca70/ansible/roles/statusd-mailsrv/defaults/main.yml#L144
But the purging part of the script has a bug:
```sh
      # Purge old dumps
      OLD_DUMPS=$(ls -Art ${BKP_DIR} | head -n -${MAX_KEPT})
      rm -vf ${OLD_DUMPS}
```
https://github.com/status-im/infra-eth-cluster/blob/d8dca70/ansible/roles/statusd-mailsrv/tasks/backup.yml#L34-L36
When calling `rm` on `${OLD_DUMPS}` it's not using an absolute path, but a relative one.

**Comment by jakubgs** [comment]
Modified the `systemd-timer` to support setting work dir: https://github.com/status-im/infra-role-systemd-timer/commit/3ba6995b
And modified the history node role to set it correctly: https://github.com/status-im/infra-eth-cluster/commit/f9cc9fd7
Looks much better:
```
systemd[1]: Starting Dumping mailserver PostgreSQL database...
dump-statusd-mail-db[9579]: Created: /var/tmp/backups/mailsrv/statusd_mail_db_dump_20200622095042.sql
dump-statusd-mail-db[9579]: removed 'statusd_mail_db_dump_20200331130625.sql'
dump-statusd-mail-db[9579]: removed 'statusd_mail_db_dump_20200401000003.sql'
dump-statusd-mail-db[9579]: removed 'statusd_mail_db_dump_20200402000004.sql'
...
dump-statusd-mail-db[9579]: removed 'statusd_mail_db_dump_20200621000005.sql'
dump-statusd-mail-db[9579]: removed 'statusd_mail_db_dump_20200622000005.sql'
dump-statusd-mail-db[9579]: removed 'statusd_mail_db_dump_20200622093738.sql'
systemd[1]: Started Dumping mailserver PostgreSQL database.
```
```
admin@mail-01.do-ams3.eth.prod:~ % ls -l /var/tmp/backups/mailsrv 
total 1884088
-rw-r--r-- 1 root root 643025572 Jun 22 09:39 statusd_mail_db_dump_20200622093918.sql
-rw-r--r-- 1 root root 643115453 Jun 22 09:48 statusd_mail_db_dump_20200622094816.sql
-rw-r--r-- 1 root root 643146256 Jun 22 09:51 statusd_mail_db_dump_20200622095042.sql
```
