### ISSUE TITLE
Invalid phone number error is shown for valid phone number

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1087]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "Invalid phone number" error if provide 
* valid Isle of Man mobile number +447624###### (tried this number in previous version 0.9.4 and it's accepted)
* Argentina number +541123######

For exact number see 
* chat https://dashboard.instabug.com/applications/status/beta/chats/42
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/374

I checked the numbers with https://www.twilio.com/lookup and they look like valid one
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Phone number is accepted and app responds "Thanks! We've sent you a text message...
#### Actual behavior
[comment]: # (Describe what actually happened.)
 "Invalid phone number" error
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Console
- Tap on /phone and provide phone number+447624######  as in https://dashboard.instabug.com/applications/status/beta/chats/42 or in https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/374

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6
* Operating System: Android and iOS

**Comment by alwx** [comment]
Fixed in #1152.

By the way, `+541123######` is not a valid mobile phone number — phone numbers in Argentina look this way: `+54 9 ### #######` (source: https://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina)
