### ISSUE TITLE
"Update to latest version to see..." when receiving push notification with sticker, audio or image or as previe in chat input in case of responding to image

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10876]
# Bug Report

## Problem
On preview of push notifications with images or with stickers misleading message is shown:
![IMAGE 2020-06-25 15:02:13](https://user-images.githubusercontent.com/4557972/85724802-da5c9f00-b6f4-11ea-8f26-bcf96fc2b3a7.jpg)
![IMAGE 2020-06-25 15:02:17](https://user-images.githubusercontent.com/4557972/85724813-dcbef900-b6f4-11ea-8e38-b5815fc68b90.jpg)

#### Expected behavior
If it is impossible to have preview of image or sticker - message "Image" or "Sticker"

#### Actual behavior
see screenshots above

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Device 1: login and enable notifications
- Device 2: send sticker to 1-1 chat to Device 1
- Device 2: send image to 1-1 chat to Device 1

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 25/06/2020
- Operating System: Android

**Comment by churik** [comment]
On latest nightly also reproducible in as a preview in chat input when reply on image:
![IMAGE 2020-07-27 16:56:32](https://user-images.githubusercontent.com/4557972/88557132-1f446000-d02a-11ea-814e-0647e0f12bbb.jpg)


@hesterbruikman for me it looks pretty visible.
Can we prioritize it?

**Comment by hesterbruikman** [comment]
I think so, it is very visible indeed. I would timebox it and move to 1.7 if Emojis is ready in the meantime

**Comment by churik** [comment]
I would say that it will cause a lot of questions in 1.5, at least with replying to images. 
Maybe it is not so difficult to fix it and it is doable earlier? 

People for sure will try out new features and sending push notifications with it and from my side it looks like not really the best experience.

**Comment by hesterbruikman** [comment]
I think the quickest solution here to avoid confusion is to simply say `Image` or `Sticker` as you suggested. Instead of the full copy used now

Notification: Sticker if sticker, Image if image
Reply: Sticker if sticker, Image if image
(same as message preview in chat list)

wdyt @churik

**Comment by churik** [comment]
Agree! Thank you

**Comment by flexsurfer** [comment]
its not possible to reply to sticker, so i fixed image reply here https://github.com/status-im/status-react/pull/11002

**Comment by hesterbruikman** [comment]
Fixed for `Reply`. Issue still open to to provide fix for `Notification banner`

**Comment by churik** [comment]
still relevant in 1.11

**Comment by briansztamfater** [comment]
I was able to reproduce this one and #10875 on 1.12 production build, but if testing on a local debug build both issues work as expected 🤔 
Any insights for better debugging these Push Notification-related issues?

**Comment by cammellos** [comment]
@churik I think this one might be fixed in develop / 1.13, could you please confirm? 
It should just show "Image" I believe (or "Audio message" etc)

**Comment by churik** [comment]
yes, it is fixed, thank you!!!
