### ISSUE TITLE
PN for reply message is shown as two messages

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10874]
# Bug Report

## Problem
When user receives Push Notification for a reply message, - PN shows is as like two separate messages were received: first is the actual message and second on is the message of reply-to quote 

#### Expected behavior

Only actual message is shown when reply is received

#### Actual behavior

Reply + actual message shown in push notification

![2324234234](https://user-images.githubusercontent.com/8749671/85719374-0a597180-b6f8-11ea-81e9-fabaf58e6b83.gif)

### Reproduction

- Create two new users (UserA and UserB)
- UserA creates 1-1 chat with UserB
- UserB sends a text message to UserA
- UserA enables Push Notifications
- UserA puts Status on background
- UserB replies to previously sent message with another message

### Additional Information

- Status version: release 1.4 
- Operating System: Android and iOS

**Comment by churik** [comment]
Not relevant in 1.11
