### ISSUE TITLE
Changed LOG LEVEL once in release builds makes impossible to disable logs again until reopening app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10888]
# Bug Report

## Problem
By default LOG LEVEL is disabled in release builds - it means that Status.log and geth.log are empty.
But if you change it once to another log level and then change back to disable it - you'll see new entries in logs, which means that `DISABLED` log level is not applied.
Moreover, it is written for new multiaccounts on this build as well. 
**But log level is set correctly again after manual reopening app.**

#### Expected behavior
No new entries in geth.log

#### Actual behavior
New entries in geth.log when user is logged out and 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new account
- Change log level to `INFO` (14:15 in logs)
- Login again and DISABLE log level
- Login (14:25 in logs)

### Additional Information

- Status version: release 1.4.1
- Operating System: Android, iOS

#### Logs

with DISABLED in log level (before change): [status_logs_empty.zip](https://github.com/status-im/status-react/files/4846169/status_logs_empty.zip)
with DISABLED in log level (after change): [status_logs 12.zip](https://github.com/status-im/status-react/files/4846198/status_logs.12.zip)

**Comment by churik** [comment]
as a temporary workaround IMO we can change the copy in this popup (to add that manual restarting app is required). WDYT @hesterbruikman ?
![IMAGE 2020-06-29 16:47:18](https://user-images.githubusercontent.com/4557972/86020436-317daf00-ba28-11ea-8505-f20670094242.jpg)

**Comment by hesterbruikman** [comment]
>  But log level is set correctly again after manual reopening app.
@Ferossgp how much more effort would it cost to offer a `restart` button on the above dialog? I don't know if something like this is possible on Android/iOS
