### ISSUE TITLE
Expanded view with public chat categories

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10880]
# Problem
When joining Status is difficult for people to understand what to do next; especially if they were not invited by a friend and are therefor not deeplinked into a chat.

There is a list of hardcoded channels, this list can be expanded on a new screen to show a categorized and more extensive list of public chats.

Follow up from #8845 

## Implementation

- Designs to be added (imagine something similar to [earlier design](https://github.com/status-im/status-react/issues/8845#issuecomment-543589234))
- _Content (i.e. public chats) to populate lists needs to be updated_

## Acceptance Criteria

- Implementation follows design 
- There is a suggested flow for contributors to update the list

## Notes
It's not possible to get a list of 'most popular' channels by traffic. In the future this hardcoded list could be dynamic based on user curation (e.g. staking to promote channels)

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by errorists** [comment]
👉  [Design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15093%3A2)
Needs to be completed with all public chats, but already anyone can get the gist of it

**Comment by hesterbruikman** [comment]
@flexsurfer design is updated to a [categorized view](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15093%3A2) 

You can find the list in this sheet to copy: https://docs.google.com/spreadsheets/d/1YBCQON1sxy-eSCx-E6e4KeIk3yYkqWG1h2XjwCHjxKk/edit?usp=sharing

While you're at it, could you please update the `featured chats` on the Chat tab tooltip as well?

Finally, if you see anyway of publishing and pulling the list from decentralized storage, that would be fantastic. (that way we can update between releases) If not, let's go with the quickest solution for now ✴️

![Frame 47](https://user-images.githubusercontent.com/35233054/86911327-72a64b00-c11b-11ea-89be-08cbfc30af7f.png)
