### ISSUE TITLE
Signing messages in DApp using transaction signing method for keycard accounts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10882]
# Bug Report

## Problem

Signed messages for KK accounts and ordinary accounts are different because of using wrong method for keycard accounts (as @rasom told it is using transaction signing method)
This may lead to non-working Keycard accounts with applications that using this method.

#### Expected behavior
signed message is the same

#### Actual behavior
<img width="453" alt="photo_2020-06-26 17 41 12 jpeg 2020-06-26 17-41-41" src="https://user-images.githubusercontent.com/4557972/85875491-90e38100-b7d4-11ea-90ac-0a0dadaabf5d.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

1) Device A: open Status, open simpledapp.eth, allow permissions
2) Device A: open Transaction, Sign message
2) Device B: restore the same account with keycard
3) Device B: repeat steps 1-2

### Additional Information

- Status version: 1.4.1

- Operating System: Android

**Comment by churik** [comment]
cc @guylouis @hesterbruikman 
I believe we need to fix it in 1.4.1

**Comment by hesterbruikman** [comment]
Tell if this is correct please:

- User opens dapp
- User connects
- Dapp sends sign message request (e.g. contract interaction)
- Status asks to sign tx instead of message?

What is the effect? Failed message signing?

**Comment by churik** [comment]
For apps, that are using signing text method for authorization (i.e. CryptoKitties), after generating and signing transaction you'll see error:
![IMAGE 2020-06-26 18:05:45](https://user-images.githubusercontent.com/4557972/85877581-a8703900-b7d7-11ea-94a8-0fc9cbdce2d9.jpg)
So it is failed transactions in Dapp.
All fine with regular accounts.

**Comment by churik** [comment]
@rasom update:
today I'm able to sign transaction from Cryptokitties, but after signing was redirected to:
![IMAGE 2020-06-29 10:44:24](https://user-images.githubusercontent.com/4557972/85992685-805e2100-b9f5-11ea-8ca4-f195f6f37595.jpg)


It is not reproducible from ordinary multiaccount.

**Comment by churik** [comment]
UPDATE: got [this error](https://github.com/status-im/status-react/issues/10882#issuecomment-651025602) on ordinary multiaccounts as well
so not sure exactly what can be affected by this issue.
cc @hesterbruikman

**Comment by churik** [comment]
UPDATE: one issue that is caused by this issue is that transaction messages are not confirmed on recipient side.
