### ISSUE TITLE
Push notification is generated on paired account when you send message to 1-1

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10895]
# Bug Report

## Problem
For each message sent from paired device push notification arrives

#### Expected behavior
no push notification

#### Actual behavior
push notification is arriving on Device B (my own message from Device A)

### Reproduction

- Device A: create account and start chat with User C
- Device B: restore the same account as on device A
- Device A: got to Profile > Sync > Device syncing and pair Device A and Device B
- Device A: send some messages to User C

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 1.4.1
- Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/4851810/Status-debug-logs.zip)

**Comment by churik** [comment]
still relevant on 1.11

**Comment by cammellos** [comment]
I believe this should be fixed in latest develop, could you please test it @churik if you have some time?
feel free to close if fixed, thanks!

**Comment by churik** [comment]
right. it is fixed, thank you!
