### ISSUE TITLE
No message in 1-1 chat if sending assets to ENS name

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10893]
# Bug Report

## Problem
currently if sending funds directly to ENS name (tried on mainnet) there is no message received.

#### Expected behavior
the message is received by User B

#### Actual behavior
no message has arrived

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
**Prerequisites:** User A has some ETH; User B has ENS name

- User A: Open Status
- User B: install Status and set ENS name
- User A: start chat with User B (with ENS name), send some messages
- User A: send ETH to User B in 1-1 chat

### Additional Information

- Status version: release 1.4.1
- Operating System: Android, iOS

#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/4851249/Status-debug-logs.zip)

**Comment by flexsurfer** [comment]
@churik are you sending from keycard or regular account ?

**Comment by churik** [comment]
reproducible for both @flexsurfer

**Comment by hesterbruikman** [comment]
@churik is the tx send and not shown in the 1:1 chat or not send at all?

**Comment by churik** [comment]
the tx is sent but is not shown in 1-1 chat

**Comment by hesterbruikman** [comment]
If it helps working on the issue: Sending a transaction request is received by the recipient.

**Comment by flexsurfer** [comment]
what about sending to users without ens name?

**Comment by hesterbruikman** [comment]
@flexsurfer just tried sending from account that has ENS name to account without ENS name. That works fine.

Correction; last tx I tried from non-ENS account to non-ENS account is also not showing up. Address request came up, but tx is not confirming in chat even though it's visible in Wallet

**Comment by flexsurfer** [comment]
request or transaction?

**Comment by hesterbruikman** [comment]
Transaction. So seems like the issue can occur:
- when receiving tx in chat on a chat key with and without ENS name
- sending from Keycard or regular account
- address request does appear for the recipient (user B)

Here's what happened in the last case I found. Neither User A nor User B has ENS name:
- User A sends address request to user B
- User B sees request and accepts
- User A sees request is accepted and signs and sends transaction
- User B continues to see `Shared Status account` (2h later) even though on tx History the transaction shows as received.

End state for user A and B below
![Frame 166](https://user-images.githubusercontent.com/35233054/86162301-db376b80-bb0e-11ea-817a-6c8a32ed4f72.png)

Logs:
[Status-debug-logs_Recipient.zip](https://github.com/status-im/status-react/files/4857314/Status-debug-logs_Recipient.zip)
[Status-debug-logs_Sender (1).zip](https://github.com/status-im/status-react/files/4857315/Status-debug-logs_Sender.1.zip)
