### ISSUE TITLE
Entering confirmation code does not switch to confirmation code request mode

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1089]
## Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In previous version (0.9.5): when user types 4 digits of confirmation code then app switches to confirmation code request mode automatically. So, user does not need to tap on "Thanks ... Please provide code..." message. Now it does not happen and user must tap on the message or on /confirmation-code command to enter code.
Video:
* before https://drive.google.com/open?id=0Bz3t9zSg1wb7RnRSUUNDc0t2cDg
* now https://drive.google.com/open?id=0Bz3t9zSg1wb7RzVQNUlXVENWZDQ

Before (works as expected):
![before conf code](https://cloud.githubusercontent.com/assets/6584810/25431677/ddb57f58-2a81-11e7-8cfc-09687a224c88.png)

Now (issue):
![now conf code](https://cloud.githubusercontent.com/assets/6584810/25431680/e1dd6c3a-2a81-11e7-8d1e-26f2c144e68f.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After text msg with confirmation code is sent: when user types 4 digits of confirmation code then app switches to confirmation code request mode automatically.
#### Actual behavior
[comment]: # (Describe what actually happened.)
when user types 4 digits of confirmation code then nothing happens. User can send to console this numbers but they are not considered as confirmation code. So, user must tap on the message or on /confirmation-code command to enter code.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and create new account
- Provide phone number
- After message "Thanks we've sent you a text message..." type 1234
- Expected: app should switch to  confirmation code request mode

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6
* Operating System: Android and iOS

### Instabug
* https://dashboard.instabug.com/applications/status/beta/bugs/192
* https://dashboard.instabug.com/applications/status/beta/bugs/218
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/382

**Comment by tiabc** [comment]
Faced it as well. Pretty annoying and misleading, especially for a newcomer to the application.

**Comment by annadanchenko** [comment]
Phone feature is removed, so no confirmation code command anymore
