### ISSUE TITLE
Add 'Add new contact' and 'Invite friends' button to Contact screen

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10891]
Issue within epic #7234 

# Problem
We've received more than one report of people struggling to add contacts. An explicit `Invite friends` button on the Contact screen can support users that are accustomed to inviting friends before starting a chat

## Implementation

- Add an invite friends button to the Contacts screen
- Invite friends button generates referral url

Designs on [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A4233) 
<img width="375" alt="Profile -_ Contacts" src="https://user-images.githubusercontent.com/35233054/86114727-3cd5e680-bacb-11ea-96d7-43cf36c11981.png">

## Acceptance Criteria
Follow design on Figma

## Notes
Adding contacts is not center stage in the UI as starting a chat does not require 'friending' or 'being contacts'. `Contacts` rather serves as a phonebook. Adding an explicit `Invite friends` button to the `Contacts` view, makes starting a chat easier for those under the impression that it is required.

## Future Steps
Add remaining features to contact management as found in the design and epic #7234

**Comment by errorists** [comment]
Very cool, should I close[ this issue](https://github.com/status-im/status-react/issues/9472)? It's only about the Invite Friends part

**Comment by hesterbruikman** [comment]
Yes please, sorry about that, couldn't find a related issue and added this one to the epic
