### ISSUE TITLE
Can't block a user

### ISSUE THREAD

**Issue by KyleNie** [status-im/status-react#10917]
# Bug Report

## Update

I left beta, reinstalled and the issue is gone.

## Problem

Cannot block a user from a group chat.

#### Expected behavior

The user is blocked, I don't see their messages anymore.

#### Actual behavior

The user is not added to the "blocked" list, I can still see their existing and new messages, and the interface becomes buggy (I can't see any messages in groups).

### Reproduction

In a group, select a user, open their profile and block.

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.4.0 Beta
[comment]: # (Android or iOS.)
- Operating System: Android 10 (EMUI 10)
- Device: Huawei Mate 20 Pro

**Comment by flexsurfer** [comment]
thanks @KyleNie fixed here https://github.com/status-im/status-react/issues/10312 , will be available in the next release
