### ISSUE TITLE
Two tokens (Flexacoin and FUTURAX) is checked and unchecked at the same time in "Wallet" -> "Manage assets"

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10922]
# Bug Report

## Problem

When trying to check or uncheck one of two tokens (Flexacoin or FUTURAX) in "Wallet" -> "Manage assets"  they both are checked and unchecked at the same time by one tap.

#### Expected behavior

When user checks/unchecks one of the tokens, only one token is checked/unchecked.

#### Actual behavior

When user checks/unchecks one of tokens (Flexacoin or FUTURAX), two tokens - both Flexacoin and FUTURAX - are checked/unchecked.

![ezgif-4-8e83a4ed3d5c](https://user-images.githubusercontent.com/67952253/86769749-f135b680-c04f-11ea-9259-059e22cad4bb.gif)

### Reproduction

- Open Wallet
- Tap 3 dots at the top right
- Select "Manage assets"
- Find in list Flexacoin and FUTURAX
- Check Flexacoin
- Uncheck Flexacoin or FUTURAX
- Check FUTURAX
- Uncheck Flexacoin or FUTURAX

### Additional Information

- Status version: release 1.4.1
- Operating System: Android and iOS

**Comment by flexsurfer** [comment]
hm wondering if we have validation for token symbol, because for FUTURAX symbol is `FTXT` , https://etherscan.io/address/0x41875c2332b0877cdfaa699b641402b7d4642c32#readContract

**Comment by Serhy** [comment]
@flexsurfer I thought we have. 
Another Futurax token is https://etherscan.io/address/0xc92d6e3e64302c59d734f3292e2a13a13d7e1817#readContract

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/86789973-30700180-c068-11ea-904a-2afd08826a30.png)
![image](https://user-images.githubusercontent.com/11790366/86790002-35cd4c00-c068-11ea-8190-a9e9774c8814.png)
![image](https://user-images.githubusercontent.com/11790366/86790018-39f96980-c068-11ea-9f8d-975f72f74da4.png)
![image](https://user-images.githubusercontent.com/11790366/86790032-3f56b400-c068-11ea-8eab-f866b0e3f56e.png)
![image](https://user-images.githubusercontent.com/11790366/86790068-47165880-c068-11ea-9c14-da102716a0d4.png)

**Comment by flexsurfer** [comment]
ok it seems like these two tokens have the same symbol but we use the symbol as unique id, this might lead to unexpected behavior

**Comment by hesterbruikman** [comment]
For future reference

[Flexacoin](
    0x4a57E687b9126435a9B19E4A802113e266AdeBde): 0x4a57E687b9126435a9B19E4A802113e266AdeBde
Current icon

Futurax I think we can drop support. Associated accounts of the project seem to no longer exist
