### ISSUE TITLE
Chat headers are messed up after opening app from background on IOS and navigating to 1-1 chat and back

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10943]
# Bug Report

## Problem
When app is on background  and several 1-1 chats are opened, after getting back from background and navigating back-forth to 1-1 chats and back, after second attempt `User A` chat header is shown for `User B`.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/4557972/87298025-bfb66280-c509-11ea-8ec0-6afc9816a42b.gif)
Issue is not reproducible on 1.4, so I guess it is another regression from QUO (though not sure) 

#### Expected behavior
`User A` chat header

#### Actual behavior
`User B` chat header, but in fact chat view with `User A`

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

1) Open Status, create multiaccount
2) Start chat with `User A` and `User B` (with ENS or using chat key, both cases are working), go back to home view
3) Put app to background,
4) Put app back from background
5) Navigate to chat with `User B` and back (can use swipe gesture or button)
6) Navigate to chat with `User A` 

### Additional Information

- Status version: nightly 13/07/20
- Operating System: iOS

**Comment by churik** [comment]
cc @hesterbruikman

**Comment by Ferossgp** [comment]
The placeholder of empty chat is also wrong, it happens because chat is wrapped in an element that does not update when receiving properties https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/connectivity/view.cljs by unwrapping it, chat works as expected.

**Comment by Ferossgp** [comment]
Same here #10914
