### ISSUE TITLE
Replace account cards in wallet with account list layout

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10969]
# Problem
In case of accounts with high value (e.g. a watch-only account kept on cold storage), the value exceeds the card width and pushes the share icon out of view

![Screenshot!UNITO-UNDERSCORE!20200716-225553!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!01](https://user-images.githubusercontent.com/35233054/87762447-73be3300-c813-11ea-94c7-1b9dc6bd451b.jpg)

A list layout is better suited to accommodate accounts of different values.

![](https://user-images.githubusercontent.com/35233054/87762303-35287880-c813-11ea-9133-c4bc4cc72b32.png)

Design on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=9777%3A37903)

* [ ] Address is displayed in Inter Status
* [ ] `...` calls bottom sheet with option to `Send` > `Request` > `Share`
* [ ] `Request` calls tx request flow. This is currently not the case
* [ ] adapt design for Keycard accounts; design TBD

## Future Steps

**Comment by tbenr** [comment]
@hesterbruikman I can work on this

**Comment by flexsurfer** [comment]
i don't know who is the designer, so i i ask @hesterbruikman and @errorists   :) could we also add an icon for imported accounts, similar to watch only?  also many users complain that after creating an account it's not obvious that you need to scroll to reach "add new account", so they think its possible to create only one account,  so probably we could add "add account" item in meu as well ?  thanks

**Comment by flexsurfer** [comment]
also im not a designer but as a user would say this white circle takes too much attention
![image](https://user-images.githubusercontent.com/11790366/92684170-2652d380-f335-11ea-9fa4-cb91a76bed5e.png)

**Comment by hesterbruikman** [comment]
> i don't know who is the designer, so i i ask @hesterbruikman and @errorists :) could we also add an icon for imported accounts, similar to watch only? 

Good question @flexsurfer ! It sparked quite the conversation within the design team on how and where to best distinguish different types of accounts and whether they are imported and on a different 'recovery tree'; Also differentiating Keycard for StatusPay. 

@johnlea-quiup has the best overview by now I believe, but it'll take some time to translate to the UI.

> also many users complain that after creating an account it's not obvious that you need to scroll to reach "add new account", so they think its possible to create only one account, so probably we could add "add account" item in meu as well ? thanks

This is a recurring issue; people get a shock of accounts not visible upon recovery. I strongly feel the solution here is in path scanning on import. Fall out of scope last year, designs [here](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=7353%3A36859). The user shouldn't have to manually add accounts that were derived from the seed

**Comment by John-44** [comment]
@flexsurfer hi, I'm working on the wallet atm, currently trying to see how we can avoid the current 'popups over popups over popups' complexity when performing actions like sending a transaction, and also how to integrate multisig functionality.  The designs shown above will probably evolve, I'll post updated mocks once I've got a concept ready to share.
