### ISSUE TITLE
Add path scanning to 'Access existing keys' and upon request

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10973]
# Problem
There are multiple occasions where the wallet does not accurately shows active accounts in the HD wallet or the tokens they hold.

* User imports/recovers an existing account using their seed phrase. They have derived and used one or more accounts beyond the first leaf. These accounts are not shown upon recovery, nor is the user informed that they need to manually generate the accounts again in order for them to be visible in the wallet
* User receives tokens on an account that are not included in their asset list yet. The tokens received will not be visible, nor is the user informed that they need to manually add the token through `manage assets` in order for them to be visible in the wallet
_A related issue is that the user is required to restart the app to ensure tokens are visible after manually adding them. See issue #10786 _

## User story

1. As a user I want to see 'active' accounts (i.e. accounts that I've used for transactions) that I have derived from my master keypair, when I recover my keys in **onboarding** (i.e. multiaccount) so that I feel reassured everything is still there
1. As a user I want to see 'active' accounts (i.e. accounts that I've used for transactions) that I have derived from my master keypair, when I recover my keys in **wallet** (i.e. multiaccount) so that I feel reassured everything is still there
1. As a user I want to enable checking for assets that are not yet visible in my wallet, either upon opening the app, wallet or by manually refreshing the wallet, so that I don't have to manually add the asset

* [ ] Original designs for path scanning as part of `Wallet` > `Add account` > `Enter a seed phrase` (or `Enter a private key`) on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=7361%3A5316)
* [ ] Adapt designs for use in `Your keys` > `Access existing keys` > `Enter seed phrase`
* [ ] Adapt designs for use in `Your keys` > `Access existing keys` > `Recover with Keycard`
* [ ] Original designs for 'Pull to refresh' that can include scanning for new tokens captured in https://github.com/status-im/status-react/issues/10242

## Notes
I believe method to scan paths already exists in status-go @gravityblast @Samyoul can you confirm?

cc @johnlea-quiup @churik 

## Future Steps

**Comment by gravityblast** [comment]
@hesterbruikman I don't think the scan is already implemented but we could do it easily during the creation of the first account

**Comment by cammellos** [comment]
Looking at the designs, what happens if the user is offline on account creation (we need to be online to fetch funds/transactions)? Will he be given another chance to go through the process?

**Comment by gravityblast** [comment]
good point @cammellos, if the user is offline we can't understand if other accounts have balance or txs. 
but we store the BIP44 parent account, so in theory we could derive child accounts in memory and check them later when the user is online.

**Comment by hesterbruikman** [comment]
Does that mean that in theory we could do this in the background when the user comes online and prompt a notification like?:

'More accounts found'
Ignore / View

**Comment by cammellos** [comment]
Yes, that sounds feasible

**Comment by guylouis** [comment]
> Yes, that sounds feasible

it means we keep m/44'/60'/0' or m/44'/60'/0'/0 public key in the app memory for keycard multi-accounts right ?

**Comment by gravityblast** [comment]
@guylouis for keycard we can't extract that key if you already have a card initialized though. 
Instead if the current Status installation is importing a key into the card, yes we could keep in memory an extended public key that allows us to derive child public keys and addresses.

**Comment by gravityblast** [comment]
because a normal public key wouldn't be enough, we need an extended public key to derive child public keys.

**Comment by guylouis** [comment]
@cammellos 
I guess one point to clarify to do this scanning of m/44'/60'/0'/0/i accounts in the background is wether we have 
- for regular accounts 
- for keycard accounts 
what's needed (I guess it's at least m/44'/60'/0'/0 extended public key) to derive the public addresses and scan **without asking the user a password (regular m.account) or a keycard tap (keycard m.account)**

**Comment by cammellos** [comment]
I think this issue needs a bit more clarity, 
currently there seem to be 3 different features included in this:

```
As a user I want to see 'active' accounts (i.e. accounts that I've used for transactions) that I have derived from my master keypair, when I recover my keys in onboarding (i.e. multiaccount) so that I feel reassured everything is still there
As a user I want to see 'active' accounts (i.e. accounts that I've used for transactions) that I have derived from my master keypair, when I recover my keys in wallet (i.e. multiaccount) so that I feel reassured everything is still there
As a user I want to enable checking for assets that are not yet visible in my wallet, either upon opening the app, wallet or by manually refreshing the wallet, so that I don't have to manually add the asset
```

I would recommend splitting them if still necessary and cut the scope, as not sure as it is this is currently actionable.

I would focus on:

```
As a user I want to see 'active' accounts (i.e. accounts that I've used for transactions) that I have derived from my master keypair, when I recover my keys in onboarding (i.e. multiaccount) so that I feel reassured everything is still there
```
create a new issue and exclude the custom derivation path and cover the error scenario in https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=4207%3A0 
in case the user is offline.

Happy to do that but I don't have all the context.

cc @hesterbruikman

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
