### ISSUE TITLE
Research of log behavior in Nightly and Release

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10977]
# Problem
The selected value in Log level settings doesn't match the actual value in log files.

- - -
#### 1. **The default setting of Log level is "INFO” (in application Profile -> Advanced -> Log level). But in fact *_status.log_* may contain entries from “DEBUG” level.**
_Steps:_

* Install Status app: nightly build
* Join to any chat, write smth, open Wallet
* Report a bug
* Check **status.log** file

#### 2. **When changing Log level to “TRACE” in fact *_status.log_* contains DEBUG entries only. The question is: are TRACE entries possible at all in this case?**
_Steps:_

* Log in
* Profile -> Advanced -> Log level -> TRACE
* Write smth to any chat, open Wallet
* Report a bug
* Check **status.log** file

#### 3. **When going back to default setting (INFO) in fact *_status.log_* still contains DEBUG entries.**
_Steps:_

* Log in
* Profile -> Advanced -> Log level -> INFO
* Write smth to any chat, open Wallet
* Report a bug
* Check **status.log** file

#### 4. The default setting of Log level is “DISABLED”. But in fact *_status.log_* may contain entries from “DEBUG” level. *_Geth.log_* file doesn't created as expected.
_Steps:_

* Install Status app: release build
* Join to any chat, write smth, open Wallet
* Report a bug
* Check **status.log** file

#### 5. **When changing Log level to “TRACE” in fact *_status.log_* contains DEBUG entries only. The question is: are TRACE entries possible at all in this case?**
_Steps:_

* Log in
* Profile -> Advanced -> Log level -> TRACE
* Write smth to any chat, open Wallet
* Report a bug
* Check **status.log** file

#### 6. **When going back to default setting (DISABLED) in fact there are two cases:**
6.1. **Without restart** the app after change **until login** new entries in **geth.log** appeared, although in user settings DISABLED is set.

6.2. **With restart** after change **until user is logged out** TRACE level is set (therefore from last user), **after login** DISABLED is set, new entries don’t appear in **geth.log.**

- - -
All mismatches are shown in the tables below.

**_NIGHTLY_**

|geth.log (log level ) | geth.log (in fact) | status.log (og level) | status.log (in fact)|
|----|----|----|----|
|INFO | INFO | INFO | DEBUG|
|TRACE | TRACE | TRACE | DEBUG|
|back to INFO | INFO | back to INFO | DEBUG|

**_RELEASE_**

|geth.log (log level) | geth.log (in fact) | status.log (log level) | status.log (in fact)|
|----|----|----|----|
|x | x | DISABLED | DEBUG|
|TRACE | TRACE | TRACE | DEBUG|
|back to DISABLED | TRACE (until login without restart); TRACE (until login with restart); DISABLED (after login with restart) | back to DISABLED | DEBUG (in all cases)|

# Summary

* [ ] 1. Is it expected that Log level setting impacts _status.log_ or not?
Currently _Status.log_ seems to be completely independent from LogLevel which is not obvious from user POV.
IMO should be changed in more user-friendly way.
* [ ] 2. Need to have ability to set Log level per-app not per user 
It may be helpful or necessary to investigate some issues, sometimes it is the only way to get some info from users when they can't login or restore their multiaccounts (so before actual login)

#### 3. Release: Disabled -> TRACE -> Disabled (unpredictable behavior on release builds when changing from default LogLevel and back)

* [ ] **3.1. With restart app** until the user logged out TRACE level is set (hence from last user), after login DISABLED is set.
Not sure it is an issue, but anyway it is not obvious from user POV
* [ ] **3.2. without restart app** after change Disabled -> TRACE -> Disabled after login new entries in geth.log appeared, so TRACE level is preserved. In user settings DISABLED is set - so it is an issue that should be solved.

**Comment by churik** [comment]
@hesterbruikman 

take a look when you have time. That sounds for me as an epic for proper handling log level settings in app.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
