### ISSUE TITLE
No margin between "Re-encrypt your keys" button and bottom panel during recovery from seed phrase flow

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10979]
# Bug Report

## Problem

No margin between "Re-encrypt your keys" button and bottom panel during recovery on the screen after input seed phrase.
Regression issue of QUO component system.

> Note: If try to lock and unlock the phone while on this screen and without moving the app to the background, then the margin appears.

![photo_2020-07-21_11-07-04](https://user-images.githubusercontent.com/67952253/88060081-00dfef80-cb66-11ea-8e69-771145a71205.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Log out from a multi-account (or install Status app)
- Tap "Access existing keys" (or "Get started" -> "Access existing keys")
- Tap "Enter seed prase"
- Input seed phrase
- Tap "Next"

### Additional Information

- Status version: Nightly build 1.4.1

- Operating System: 
Android 8, 10
IPhone 7 IOS 13

> cc @Ferossgp

**Comment by churik** [comment]
Visible regression issue in one of the main user flows, so should be fixed ASAP IMO
cc @hesterbruikman
