### ISSUE TITLE
ENS resolving for IPNS names.

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#10974]
# Bug Report

Recently I asked @hesterbruikman why ENS resolving does not work in browser. I was actually wrong on whether or not it works. If you use for example `pactxt.eth` in the browser it resolves. However `uniswap.eth` does not.

## Problem

This is because there was an issue in the contenthash library that did not resolve names correctly when they were IPNS hashes. You can see a more detailed discussion here: https://github.com/ensdomains/ens-app/issues/849. This was recently fixed in ENS which can be viewed here: https://github.com/ensdomains/ui/pull/77.

#### Expected behavior

Names using IPNS names resolve properly in the browser.

#### Actual behavior

They currently do not.

### Reproduction

- Open Status
- Open browser
- Type `uniswap.eth` and hit enter
- Name does not resolve.

**Comment by hesterbruikman** [comment]
Thanks for adding this @decanus 

Checking with @churik and @Serhy also noticed that some urls redirect to infura.status.im. Need to invest more time to understand how this works as I'm not sure why e.g. ethereum.eth directs to https://ciqg44hq64xcxtik22n3fmk65hqpj6egsp3lf5ef4sdjtz6w7dn5mkq.infura.status.im

Are we using a content hash library by Infura?

**Comment by decanus** [comment]
@hesterbruikman all names redirect, thats a correct resolution.
