### ISSUE TITLE
"Select account" bottom sheet view is changed (after "Accept and share" action in  commands in 1-1 chat)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10986]
# Bug Report

## Problem

Changed view of the bottom sheet after tap “Accept and share address” during the request of the Incoming transaction in 1-1 chat.

### Expected behavior

Design in Figma: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=6715%3A2599

#### Nightly:
![photo_2020-07-22_16-01-18](https://user-images.githubusercontent.com/67952253/88185772-a06bb380-cc34-11ea-9bee-7a71bd954594.jpg)
***
#### Release:
![photo_2020-07-22_16-12-33](https://user-images.githubusercontent.com/67952253/88188190-c9417800-cc37-11ea-83a0-7d449fb500f0.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

Device 1 (Sender):

1. Open Status
2. Home screen -> Open 1-1 chat
3. Open "Send/request transaction" menu ("+" at the bottom left)
4. Enter valid ETH amount
5. Tap "Send"
 
Device 2 (Receiver):

6. Check chat list
7. Open chat with Sender
8. Tap "Accept and Share address, select account"

### Additional Information

- Status version: Nightly 1.4.1
- Operating System: Android 8, 10

**Comment by churik** [comment]
@errorists 
should it be like in design now I guess? 
Anyway IMO current view doesn't look good, so asking how we can do it acceptable for now.

**Comment by errorists** [comment]
ewww oh god, I wish I didn't see this! 🙈  guys what happened there? 
@Ferossgp how can we fix this? list item component for selection, regular dismissible bottom sheet?

**Comment by hesterbruikman** [comment]
@errorists is this what it's supposed to be?

![1_1 Chat Commands](https://user-images.githubusercontent.com/35233054/89319570-98723180-d680-11ea-86cb-977046c7fd53.png)

**Comment by errorists** [comment]
@hesterbruikman yes, thank you :)

**Comment by qoqobolo** [comment]
Isn't reproduced in Nightly 11/08.
