### ISSUE TITLE
The message "2 attempts left" after entering wrong 6-digit passcode on the "changing PIN" flow (Profile -> Keycard settings) isn't shown every time

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10985]
# Bug Report
## Problem
During changing PIN in Keycard-account (Profile -> Keycard settings) if the first time to enter an invalid PIN, the message "Wrong passcode" will be shown and then must be shown the message "2 attempts left". But the message "2 attempts left" **isn't shown every time.The message was shown just 4 times out of 7 attempts.**

#### Expected behavior
The message "2 attempts left" after entering wrong 6-digit passcode is shown every time.

![photo!UNITO-UNDERSCORE!2020-07-22!UNITO-UNDERSCORE!15-21-21](https://user-images.githubusercontent.com/67952253/88181372-06edd300-cc2f-11ea-9df2-89559c8dda94.jpg)

#### Actual behavior
The message "2 attempts left" after entering wrong 6-digit passcode is shown from time to time.

![2 attempts1](https://user-images.githubusercontent.com/67952253/88175966-e4f05280-cc26-11ea-91a5-3b8eb14d4474.gif)

### Reproduction

* Login to keycard-account
* Profile -> Keycard settings -> Change 6-digit passcode
* Enter invalid PIN
* Put the keycard to the back of the phone

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: Nightly 1.4.1
* Operating System: Android 8

**Comment by churik** [comment]
cc @guylouis

**Comment by bitgamma** [comment]
most likely fixed when merging #11540, can be closed?
