### ISSUE TITLE
Design of several screens in frozen card flow when user is logged in doesn't correspond to the original design

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10991]
# Bug Report

#### Expected behavior

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=6918%3A23090

#### Actual behavior

![Снимок экрана 2020-07-23 в 3 51 01 PM](https://user-images.githubusercontent.com/67952253/88297031-babe9380-ccff-11ea-82a2-97117e102b76.png)

### Reproduction

- Log in to Keycard account
- Profile -> Keycard -> + Change 6-digit passcode
- Enter invalid passcode 3 times

(Or any flow which leads to a freeze keycard when user is logged in)

### 2. If restart the app after the keycard was frozen elements on the Log in screen will be shifted. There are also redundant elements.

![Снимок экрана 2020-07-23 в 3 46 06 PM](https://user-images.githubusercontent.com/67952253/88298177-1f2e2280-cd01-11ea-98e6-e28cab089e36.png)

### Reproduction

- After successfully resetting the passcode -> Log out
- Restart Status app

### Additional Information

- Status version: Nightly 23/07
- Operating System: Android 8, 10

cc @errorists

**Comment by churik** [comment]
@Ferossgp easy or not really to fix?

**Comment by Ferossgp** [comment]
@churik it is not hard, but as I understood it's not a priority for near releases

**Comment by bitgamma** [comment]
Except for the "Dimissis" button look (regular button instead of "link" style) I couldn't see the rest of the problems on develop. The button can be easily fixed (do we want to?) but please clarify if there is anything else still to fix.

**Comment by guylouis** [comment]
@bitgamma If you can't see the problems on develop, I'd change the button style to a link and close it.

**Comment by churik** [comment]
@qoqobolo can you please recheck if this is still relevant?

**Comment by qoqobolo** [comment]
@churik @bitgamma it remains only to fix the `Dismiss` button style, the rest of the issues are no longer relevant. Thank you

**Comment by qoqobolo** [comment]
@guylouis  @bitgamma sorry for misleading you!
This small redundant element is also still on the new password creation screen (when Keycard is frozen, but only in the logged-in state and if you choose to reset with PUK) and blocked Keycard screen.

Could you include this in the fix as well, please?

<img width="263" alt="Screenshot 2021-05-27 at 11 11 48" src="https://user-images.githubusercontent.com/67952253/119799426-56023580-bedc-11eb-9453-c9fd3206e7f7.png">
<img width="265" alt="Screenshot 2021-05-27 at 11 12 01" src="https://user-images.githubusercontent.com/67952253/119799448-5dc1da00-bedc-11eb-802b-e45382e4ae18.png">

**Comment by bitgamma** [comment]
@qoqobolo thanks for pointing it out, will fix that too
