### ISSUE TITLE
Creating "myself" 1-1 chat in Activity center on a synchronized device after sending address request in 1-1 chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10994]
# Bug Report

## Problem

If send ETH to any other user from Device 1, then on paired Device 2 will be created a 1-1 chat with “myself” (with the same account from which the Address request was sent). 

#### Expected behavior

"Myself" 1-1 chat on a synchronized device isn't created.

#### Actual behavior

![ezgif com-resize (2)](https://user-images.githubusercontent.com/67952253/88382567-ff523980-cda8-11ea-8ca7-7c0531cb6bd7.gif)

### Reproduction

Device 1:
- Sync with Device 2
- Open 1-1 chat with any other user -> Send transaction
- Enter valid ETH amount and send Address request
- Check chats on Device 2

### Additional information

- Status version: Nightly 24/07
- Operating System: Android 8, 10

**Comment by churik** [comment]
cc @guylouis

**Comment by churik** [comment]
Don't agree, it is not common case but definitely very strange behaviour that can cause more issues

**Comment by churik** [comment]
valid on nightly 10/05/21

**Comment by bitgamma** [comment]
I can reproduce it also when both account are stored on phone and also when you request eth instead of sending it (easier to reproduce because you don't need eth on the account). @qoqobolo can you confirm that it happens only using Keycard but not with regular accounts on your device?

**Comment by bitgamma** [comment]
also, if you don't already have a 1-to-1 chat to yourself, it goes through the activity center

**Comment by qoqobolo** [comment]
@bitgamma you are right, the case is relevant for a regular account as well. Updated the issue.
Thanks for pointing this out.
