### ISSUE TITLE
Add option to show default chat on onboarding

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10990]
# Problem
We've learned it's not clear to users how to start a chat or generally what Status app can be used for upon onboarding.

A chat bot can activate new users by offering on-demand guidance. We would like this chat bot to be available upon onboarding by displaying it as a default chat.

Design on [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15161%3A42662)

![Frame 62](https://user-images.githubusercontent.com/35233054/102386280-2b2bc100-3fcf-11eb-84db-9a5b6d4e84e7.png)

## Acceptance Criteria

* [ ] 1:1 chat with bot is visible as first chat list item upon onboarding (after Welcome screen)
* [ ] When tapping on chat in list item, 1:1 chat with bot is shown
* [ ] 1:1 chat with bot shows 'mock' chat content as in design; including a button to opt in to a conversation with the bot
* [ ] Tap on the button Tell me more (copy might change) shares chat key with chat bot, along with device language
  * Chat bot will have a chat key. A random message needs to be send to this chat key
* [ ] User receives messages from bot like any other user (contact status does not change)
* [ ] The chat has all the same options as a regular 1:1 chat in the chat list

## Future Steps

* [ ] (Optional) The chat has a option to initiate conversation with the bot at any time
* [ ] (Optional) The chat represents options (content type) used by the chat bot as buttons

**Comment by hesterbruikman** [comment]
cc @Ferossgp @AK87ST @errorists

**Comment by errorists** [comment]
> We've learned it's not clear to users how to start a chat 

sorry but I just couldn't leave this alone, I think it's not true, it's more about finding relevant chats :)

**Comment by hesterbruikman** [comment]
> sorry but I just couldn't leave this alone, I think it's not true, it's more about finding relevant chats :)

Have heard both. Not knowing how to chat with friends most recently

**Comment by cammellos** [comment]
It's not clear exactly what the requirements are, given that we don't currently have a chatbot, we should probably make those clearer and act on a separate issue, as first we should create a chatbot, deploy it, make sure it works fine for a period of time, and later eventually use it as a default onboarding chat for users.
@hesterbruikman or @AK87ST could you please create a separate feature for what the chat bot should be doing and how the app should interact with it?
We can then make this feature dependent on that one and split off the work

**Comment by AK47Status** [comment]
> @hesterbruikman or @AK87ST could you please create
> a separate feature for what the chat bot should be doing
> and how the app should interact with it?

Sure! @hesterbruikman let me take care of this. 

What I'm about to do is: 
- (by Monday) create chatbot flow based on the contents Jonny created
- ... and deploy it with that flow (so we could start testing it)
- (on Monday) sync up with you @cammellos regarding technical aspects
- (on Tuesday) sync up with you @hesterbruikman on the progress

Cool?

**Comment by StatusSceptre** [comment]
Sounds good, thanks @AK87ST

**Comment by hesterbruikman** [comment]
@cammellos @AK87ST updated this issue; can you please check if the acceptance criteria are clear? I wrote these to describe what's expected from the client/in status-react

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
