### ISSUE TITLE
Balance is not updated 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1099]
### Help to reproduce is needed
If you can reproduce it, please, make a comment with 
* Steps to reproduce (if available). 
* Any special conditions/data/settings (e.g. slow connection, first run, run app after it was not used for several days, any other special info)
* Have you tried same steps or check data later? Have you waited for any updates from the app and for how long (e.g. balance is not updating, checked 30 minutes later and it's same)?
* Any extra comments you have
* Status version
* Device model and OS version 
* Logs (crash log or logcat)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
* ETH was sent to the Wallet but balance is not updated. 
* Or /faucet request sent but Wallet balance is not updated.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Balance is updated with sum sent. 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Balance is 0
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Need help to reproduce

#### Instabug:
iOS:
* 0.9.6 https://dashboard.instabug.com/applications/status/beta/bugs/203
* 0.9.5 balance not updated even after loaded 100% https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/355
* 0.9.4 Not showing balance received from faucet https://dashboard.instabug.com/applications/status/beta/bugs/178
* 0.9.4 https://dashboard.instabug.com/applications/status/beta/bugs/167

Android
* 0.9.6 https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/416
* 0.9.4 https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/325

**Comment by jarradh** [comment]
Faucet can fail, at the moment the Faucet command doesn't actually say if they money was sent, just the request worked.. which is weird.

They may not have sync'd

They may have tried to send mainnet eth instead of testnet eth

**Comment by yenda** [comment]
I think this can be closed as it was for old wallet and probably not related to wallet itself

**Comment by asemiankevich** [comment]
Assume it is not relevant anymore - we have new wallet (anyway it is not wallet issue) as well as `/faucet` works fine unless it is down or out of money.
