### ISSUE TITLE
Redundant step in changing PIN flow after entering invalid passcode 3 times (user is logged in)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#10993]
# Bug Report

## Problem

During changing PIN flow (Profile -> Keycard -> Change 6-digit passcode) if user enters invalid 6-digit passcode 3 times, pop-up "Keycard is frozen" is shown. After tap "Dismiss" return to "Keycard settings" screen is expected. But instead, the screen "Enter PUK code" is shown.

#### Expected behavior

Return to "Keycard settings" screen after tap "Dismiss"

#### Actual behavior

"Enter PUK code" screen is shown

![ezgif com-resize (1)](https://user-images.githubusercontent.com/67952253/88373672-8cd95d80-cd98-11ea-9710-e5e88cbd8a64.gif)

### Reproduction

- Log in to Keycard account
- Profile -> Keycard -> + Change 6-digit passcode
- Enter invalid passcode 3 times
- Tap "Dismiss"

### Additional Information

- Status version: Nightly 24/07
- Operating System: Android 8, 10

**Comment by churik** [comment]
сс @guylouis

**Comment by hesterbruikman** [comment]
Thanks for catching this @qoqobolo 

Indeed, following [design](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=7687%3A0), user can continue to use application when tapping `Dismiss`. If user came from Settings, they should return to Settings. In addition, a banner should be shown on wallet overview screen.


![Frame 189](https://user-images.githubusercontent.com/35233054/89395638-e3865600-d70d-11ea-9f7b-935ad9448f33.png)

**Comment by churik** [comment]
valid on nightly 10/05/21

**Comment by churik** [comment]
still valid on 1.15

**Comment by churik** [comment]
Closing, as it is part of https://github.com/status-im/status-react/issues/12328
