### ISSUE TITLE
Push notification doesn’t disappear after opening a chat via application shortcut (not via the notification itself)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11001]
# Bug Report

## Problem

If the user receives a notification of a new message while the application is in the background, and open the application to read this message not via push notification but via application shortcut, push notification stays in notification panel after an opening chat and reading message.

#### Expected behavior

New push notification disappears after opening the app and chat with the sender via both the push notification and the app icon.

#### Actual behavior

![ezgif com-resize (3)](https://user-images.githubusercontent.com/67952253/88639601-3d0ed500-d0bd-11ea-9f44-f98f537378de.gif)

### Reproduction

Device 1 (Sender):
1. Open 1-1 chat with Receiver
2. Send message

Device 2 (Receiver):
0. Send App to the background
1. After receiving the push notification tap to Status icon on the desktop 
2. Open 1-1 chat with Sender

### Additional Information

- Status version: Nightly 28/07
- Operating System: Android 8, 10

**Comment by churik** [comment]
relevant on release 1.11
