### ISSUE TITLE
3-random name is displayed instead of ENS name in mention push notification

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11003]
# Bug Report

## Problem

ENS names are displayed as 3-random names in PNs for mentions in chats (any type).

#### Expected behavior

ENS is shown in PNs with the mention

#### Actual behavior

https://user-images.githubusercontent.com/97245802/155154318-c7cd00dc-9a88-4db0-b489-4cd1bb4b1062.mp4

### Reproduction

Device 1:
1. Enable PNs on Android device
2. Add ENS username in Profile
3. Join a public chat
4. Send the app to the background

Device 2:
1. Join the same public chat
2. Mention the ENS user

Device 1:
1. Check the PN

### Additional Information

- Status version: Nightly 13/05
- Operating System: Android

**Comment by churik** [comment]
not relevant on 1.11 - can see ENS name in PN

**Comment by pavloburykh** [comment]
### UPDATE
Still reproducing in develop and release 1.18.2 (Android)
ENS name is not resolving in PN in 1-1 / group / public chat mentions. 3 random name displays instead of ENS. Video and logs attached. 

[geth.log](https://github.com/status-im/status-react/files/8117470/geth.log)

https://user-images.githubusercontent.com/97245802/155154318-c7cd00dc-9a88-4db0-b489-4cd1bb4b1062.mp4

**Comment by Parveshdhull** [comment]
**UPD:** Push notifications with 3-random names are only shown for older notifications that were delivered before ENS name is resolved, once ENS name is resolved new notifications are delivered with the ENS name:
![shot2](https://user-images.githubusercontent.com/17097240/167954307-e638b0a9-66d1-4613-940a-263c36d84440.png)

**Comment by Parveshdhull** [comment]
**UPD2:** ENS names for mentions are also getting resolved 
![shot3](https://user-images.githubusercontent.com/17097240/168132905-1971045d-d8ee-4039-8aab-5442f08e33fd.png)

**Comment by qoqobolo** [comment]
Hey @Parveshdhull thanks for the updates!

The issue itself is not reproducible for me either.

> UPD2: ENS names for mentions are also getting resolved

But this one I still can see on my device, ENS in PNs with mentions are still displayed as 3-random names
<img width="393" alt="Screenshot 2022-05-13 at 18 23 53" src="https://user-images.githubusercontent.com/67952253/168326324-b52c3dab-22b6-4620-97fa-2c9b2144b120.png">

I'll update the issue according to the actual state.

**Comment by qoqobolo** [comment]
Closing it for now. ENS in notifications seem to need more time to be resolved.
