### ISSUE TITLE
App crash on opening a DApp

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1100]
### Help to reproduce is needed
If you can reproduce it, please, make a comment with 
* Steps to reproduce (if available). 
* Any special conditions/data/settings (e.g. slow connection, first run, run app after it was not used for several days, any other special info)
* Have you tried same steps or check data later? Have you waited for any updates from app and for how long?
* Any extra comments you have
* Status version
* Device model and OS version 
* Logs (crash log or logcat)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Tap on DApp to open it (Etherplay, Melonport, bchat) and app crashes

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
DApp is opened
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashed
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Need help to reproduce

### Instabug reports:
Android:
* OS Level 21, 0.9.5, Etherplay: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/351
* OS Level 19, 0.9.5, Melonport: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/380

iOS
* iOS 10.2, 0.9.3, bchat: https://dashboard.instabug.com/applications/status/beta/bugs/119

**Comment by Monali109-zz** [comment]
Sign in to Status.
Tap to DApp(Melonport).
![dapp](https://user-images.githubusercontent.com/20433356/33730513-32ca7234-dba6-11e7-8c19-ee387c998e10.png)
Please see the attached screenshot.
@annadanchenko  Here it's displaying Web page not available.

**Comment by annadanchenko** [comment]
not reproducible on last nightlies
