### ISSUE TITLE
IP address is not shown for /debug on [only Android 7.1.1?]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1101]
### Help to reproduce is needed
If you can reproduce it, please, make a comment with 
* Steps to reproduce (if available). 
* Any special conditions/data/settings (e.g. slow connection, first run, run app after it was not used for several days, any other special info)
* Have you tried same steps or check data later? Have you waited for any updates from app and for how long?
* Any extra comments you have
* Status version
* Device model and OS version 
* Logs (crash log or logcat)

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: IP address is not shown, {{ip}} is shown instead. 
Instabug: https://dashboard.instabug.com/applications/status/beta/bugs/400
![ip](https://cloud.githubusercontent.com/assets/6584810/25500760/8a573c1a-2b90-11e7-8b68-d343fb2818ab.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
IP address is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
 {{ip}} is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6
* Operating System: Android; OS Level 25

**Comment by annadanchenko** [comment]
matteopey [11:16] 
@anna for me it works while I'm connected to WiFi. It gives the ip error when I'm connected to mobile network.

**Comment by alwx** [comment]
Fixing it :)
