### ISSUE TITLE
[keycard] Enter pairing code screen doesn't hint the paring code format to the user

### ISSUE THREAD

**Issue by John-44** [status-im/status-react#11025]
The current paring code entry screen doesn't hint the expected format of the paring code to the User.  This could lead to the User accidentally entering say their numeric pin code instead of their pairing code, as some users non-technical may not be aware of the difference between these code.

-- Desired resolution --

See attached screenshot [Pairing code entry field should hint at type of code required.png](https://user-images.githubusercontent.com/22846356/89037232-6ee29e80-d33e-11ea-801e-494745a5cd87.png).  The grey hint text in the pairing code entry field that currently says "Pair code..." should be replaced with a string that is representative of an actual pairing code would look like e.g. "bha1lbl9kv" 

![Pairing code entry field should hint at type of code required.png](https://user-images.githubusercontent.com/22846356/89037232-6ee29e80-d33e-11ea-801e-494745a5cd87.png)

**Comment by guylouis** [comment]
not relevant anymore since a pairing code is not shown to the user anymore in onboarding and the user sets himself his pairing code if he wants to (and with the format he choses)
