### ISSUE TITLE
Listen to a sent confirmation for all message types

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11020]
# Problem
When adding a `reaction` in an offline state, it is instantly visible for user A. However, the reaction is not send when offline, nor when User A comes back online. User B never sees the reaction, while it remains visible for user A

### Expected
Three options (ideally a combination of 1&2):
1. User A can add a reaction when offline, when the client comes back online, the reaction is send
2. User A can add a reaction when offline, user is informed the reaction was not send and can `Tap to try again`, upon which this message will disappear as soon as the reaction is send successfully
3. User A cannot send a reaction when offline

### Current
User A can add a reaction when offline. User A is not informed the reaction is not send. Reaction is not send when user A comes online

## Acceptance Criteria
Reaction is successfully sent or user is informed if message is not successfully sent
or
User cannot add reaction when offline

## Future Steps

**Comment by errorists** [comment]
Let's try to make the first option work since imo it's superior to other alternatives

> User A can add a reaction when offline, when the client comes back online, the reaction is send

**Comment by hesterbruikman** [comment]
From conversation with @Ferossgp this is actually related to how we get and show a send confirmation for all message types. 

Hiding (disallowing) reactions in offline state is not sufficient. Also with low or interrupted connections, we cannot confirm the message was send; however the client might still show as online and allow reactions.

A better solution would be to listen to a send confirmation
