### ISSUE TITLE
Error appears if start to type from the dot any name during "Start new chat" flow 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11022]
# Bug Report

## Problem

If start to type any name with dot at the beginning of this name in search field during "Start new 1-1 chat" flow, alert with error will appear. 

#### Actual behavior

![ezgif com-resize (9)](https://user-images.githubusercontent.com/67952253/89014771-51014380-d316-11ea-807b-29b4f0f19de8.gif)

### Reproduction

1. Home screen -> + -> Start new chat
2. Start type from the dot any word (e.g. ".e")

### Additional Information

- Status version: Nightly 31/07
- Operating System: Android 8, 10, iOS 13

**Comment by hesterbruikman** [comment]
Can't reproduce in 1.5, can you please check if this issue is still relevant @qoqobolo?

**Comment by qoqobolo** [comment]
@hesterbruikman yes, just checked 1.5 on Android 10 (Google Pixel 2) and iOS 13 (iPhone SE) and the error still appears
