### ISSUE TITLE
No conversion for WETH is assests in wallet

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11037]
# Bug Report

## Problem

Сonversion for WETH in wallet no displayed. Adress for checking conversion for this asset on [Etherscan](https://etherscan.io/): 0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E

#### Actual behavior

![Снимок экрана 2020-08-05 в 4 17 39 PM](https://user-images.githubusercontent.com/67952253/89423917-653ea980-d737-11ea-9bb4-1eca4b760578.png)

- Status version: Release 1.5

**Comment by flexsurfer** [comment]
cryptocompare api doesn't support WETH https://min-api.cryptocompare.com/data/price?fsym=WETH&tsyms=USD,JPY,EUR

**Comment by hesterbruikman** [comment]
See also https://github.com/status-im/status-react/issues/10695#issuecomment-677450692 for a  check with Cryptocompare on Manage assets to inform the user of fiat values not available

**Comment by churik** [comment]
@hesterbruikman 
WETH (which is the really common case on exchanges) or  any asset that already presented (not added) in our assets list probably at least show nothing or use another source (not cryptocompare)?

It seems weird to me to have tokens / currencies that are not supported in case if they are already hardcoded in our assets list.

**Comment by hesterbruikman** [comment]
Agreed, I think WETH is one of the exceptions where it is commonly used so we want to offer not having to add it manually. At the same time it's supported, but not _fully_ supported. We should probably still check if the token fiat value is supported given the fiat value you have selected.

**Comment by flexsurfer** [comment]
i didn't find a list of supported tokens by Cryptocompare, so probably not only weth from our list is not supported, but i figured out that WETH is not traded on any centralized exchange , thats why there is no price, it is traded on decentralized uniswap, so if we want its price we should get it somehow from uniswap contract i guess

**Comment by flexsurfer** [comment]
related issue https://github.com/status-im/status-react/issues/9140

**Comment by cammellos** [comment]
Seems like this can be closed, @flexsurfer feel free to re-open if other actions are required
