### ISSUE TITLE
Transaction status for commands in 1-1 chats isn't updated on synced devices

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11042]
# Bug Report

## Problem

If User1 has synced devices and declines request for outgoing transaction from User2, or User2 shares address for incoming transaction from User1 in 1-1 chat, the status of this commands is updated only on one of the synced devices (User1). On the second synced device status doesn't update. (**Case 1**)

Also if User1 requests transaction from one of the synced devices, this request doesn't appear on the second device. (**Case 2**)

#### Expected behavior

Transaction status is updated on both synchronized devices; the transaction messages themselves are shown. 

#### Actual behavior

![Снимок экрана 2020-08-05 в 5 15 54 PM](https://user-images.githubusercontent.com/67952253/89430771-6542a780-d73f-11ea-932c-3b734bd423b1.png)

#### Case 1

User2:
- Open 1-1 chat with User1
- Open transaction dialog and request transaction

User1:
- Sync two devices
- Decline request from User2 on Device1
- Open 1-1 chat with User2 on Device2

#### Case 2

- User1 sync two devices
- Open 1-1 chat with User2 on Device1
- Open transaction dialog and request transaction
- Open 1-1 chat with User2 on Device2

### Additional Information

- Status version: Release 1.5
- Operating System: Android 10; iOS13

**Comment by churik** [comment]
still relevant on nightly 27/07/22

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
