### ISSUE TITLE
Add local contact names

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11046]
## Add local contact names
Source: Roadmap planning workshop item #37 and [Discuss](https://discuss.status.im/t/add-local-contact-names/1789)

### User stories
- As a user, I want to add a nickname to my contacts so that I don’t get confused about who I’m chatting to or struggle to find the person I want to chat with in my contact list.

#### Use cases
- Add local name in `Contacts`
- View local name in chat
- View local name in chat list
- View local name in notifications
- View local name in user profile
- View local name in contact list

Preliminary [designs](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4067%3A2905)

**Comment by Samyoul** [comment]
## My responses to concerns from team

[See feedback](https://docs.google.com/spreadsheets/d/1w6ohP7RQY6am4Vpac-43YUuBIIENIe_h09GfESCPy1k/edit#gid=0)


### Security concerns

> On the other hand, isn't there any risk of my contacts deanonymization if my phone gets hacked?

Yes, depending on the nickname you give. But if your phone is hacked all of your chat is also compromised, along with your wallet keys and identity key. A concern, but a tiny one compared to the other consequences of a hacked phone.

Also there is nothing stopping someone from creating a list of all their contacts and saving them in a pastebin. If you are communicating with someone you are always giving up some level of anonymity.

---

>crucial. Are there any privacy/security concerns with this?

To me the main concerns are a phone being compromised. Syncing is not an issue as the data is encrypted with the same process as all Waku messages are.

---

### Syncing

> We need to have a good grasp on what syncing looks like.

Currently device contact sync protobuf looks like:

```protobuf
message SyncInstallationContact {
  uint64 clock = 1;
  string id = 2;
  string profile_image = 3;
  string ens_name = 4;
  uint64 last_updated = 5;
  repeated string system_tags = 6;
}
```

I'd imagine that a logical next step would be to add a `nickname` field to the protobuf and change the logic to handle this additional field.

---

>This should be quick, it NEEDs to be synced across synced devices.

Syncing can be handled.

---

> Mobile <-> Desktop local names sync. What are the requirements?

---

### Misc

> Feels highly important, but is it easily doable? Wondering if there's a technical blocker as to why we don't have it already

Looking through the code there is no technical limitation.

---

>Not ambitious enough, could try and improve random name as well?

This would be a separate feature. Both can exist simultaneously, and be developed independently.

---

>Size of data? Like comments or just names?

Comments if a priority should be a separate feature. Equally easy to implement as nicknames but not dependant on local nicknames.

---

> i'm not convinced this will help with the username challenges we experience, but rather dump the responsibility on the user to make sense of it

This feature is not designed to resolve username challenges. This feature is designed to address confusing contact lists. Granted a self determined user name would solve this concern, ENS gives a pre-existing solution.

---

> I think it's helpful; it might also be nice if you could set a local profile photo for a contact. But for both the name an photo there should be some subtle but constant visual indicator that it's a local name/photo.

--- 

> In the UI we need to be really clear with how someone could be imporsonating someone else just by changing their usernameWe are reducing value to the ENS usernames. Why would I spend gas and snt to get a username if i can use a free local name instead?

This is only for the local user's address book. This isn't for setting a public name.

---

> IMO can be merged with 'profile image' swarm (at least in the past it was managed as of contact list) and really dependant from go side

Probably could be merged with profile image, but it is not dependant in my estimation.

**Comment by Samyoul** [comment]
We need to identify any syncing weirdness, and edge cases where syncing is not working.

See https://github.com/status-im/status-react/issues?q=is%3Aopen+is%3Aissue+label%3Apairing
