### ISSUE TITLE
Addition of a Custom RPC for TomoChain on Status

### ISSUE THREAD

**Issue by drexit** [status-im/status-react#11056]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user of both Status and Tomochain, I would love to see these two great projects combined in a way that will allow others in both communities to interact on a single platform which is Status.

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ... Already, I have gone in and I see that it is possible to incorporate the native Tomochain Token onto status. Everything works perfectly it is just the fact that a custom Tomochain(TOMO) RPC is needed and also some minor UI revisions relating to the TOMO ticker and price feed. 

### Notes

TomoChain information:

RPC URL: https://rpc.tomochain.com
Chain/ Network ID: 88
Network Name: TomoChain
Ticker/Symbol: TOMO
Explorer Information: https://scan.tomochain.com

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by cammellos** [comment]
I believe we only support ERC20 tokens for now, unfortunately currently there's no plan to support other currencies, thanks for the suggestion, if anything changes we'll reopen.
thank you
