### ISSUE TITLE
add new dapp 

### ISSUE THREAD

**Issue by noxonsu** [status-im/status-react#1105]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: <Beginner|Feature>

I try to follow this documentation https://wiki.status.im/contributing/development/adding-dapps/ 

But cannot submit commit because "it seems you do not have permission to push your changes to this repository"

Here is my commit: https://github.com/DaoCasino/MainSite/raw/master/status-react.zip

**Comment by jarradh** [comment]
Could you please submit as a Pull Request, you cannot push directly to the repository.

To do you this you can goto https://github.com/status-im/status-react/pulls and hit the big green button that says "New Pull Request"

**Comment by noxonsu** [comment]
wow my first Pull Request to another repository :1st_place_medal:  ))
