### ISSUE TITLE
Add 'data saver' mode to settings

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11061]
# Problem
With https://github.com/status-im/status-react/pull/11007 wallet updates now depend on mobile data settings; Along with message fetching from history node. When `use mobile data` is disabled, no wallet updates are fetched over mobile data. 

#10242 adds an action to trigger wallet updates manually, outside of a set frequency of wallet updates. This manual action makes it possible to offer a `Data saver` mode to mobile data settings. When enabled, the user can fetch messages over mobile data (uses relatively less bandwidth) and get wallet updates only when triggered manually (uses significantly more bandwidth).

#### User story
As a user who hardly uses the wallet I want to receive messages over mobile data, but I don't want wallet updates to exhaust my data plan. Therefore I want to sync messages over mobile data, but only check for wallet updates when I say so

#### Options

* Enable - auto-sync messages and tx when on mobile network, pull to refresh available in addition
* Disable - does not sync messages and tx prompt settings bottom sheet when:_
  * switching to mobile network
  * attempting pull to refresh
* Data saver - syncs messages, syncs tx on pull to refresh only

Design TBD (cc @errorists)

## Acceptance Criteria

* [ ] User can select data saver
* [ ] When data saver is selected, user receives messages from history node
* [ ] When data saver is selected, user receives wallet updates on `pull to refresh` only

## Notes
Depends on https://github.com/status-im/status-react/issues/10242

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
