### ISSUE TITLE
Error "java.lang.RuntimeException: getParameters failed (empty parameters)" while opening QR scanner during "Start 1-1 chat" flow

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11069]
# Bug Report

## Problem

Error "java.lang.RuntimeException: getParameters failed (empty parameters)" appears after opening QR scanner to start 1-1 chat. 

![Снимок экрана 2020-08-11 в 3 14 18 PM](https://user-images.githubusercontent.com/67952253/89901447-619e9d00-dbe5-11ea-8dce-11feff2835ac.png)

### Reproduction

Case is reproduced during various scenarios. Steps couldn't be determined.

### Additional Information

- Status version: Nightly 11/08
- Operating System: Android 10

#### Logs

```
08-11 14:26:29.677 20908 20908 E AndroidRuntime: java.lang.RuntimeException: getParameters failed (empty parameters)

```
[java.lang.RuntimeException.log](https://github.com/status-im/status-react/files/5057228/java.lang.RuntimeException.log)

**Comment by churik** [comment]
Issue appeared after merging https://github.com/status-im/status-react/pull/11016

**Comment by churik** [comment]
have you seen it again @qoqobolo?

**Comment by qoqobolo** [comment]
@churik nope, never again. The issue can be closed for now
