### ISSUE TITLE
Invalid 'grant permission' errors are shown when access to camera was denied 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11071]
# Bug Report

## Problem

For Android: if permission to Camera was denied and if you tap to camera icon in 1-1/group chat, pop-up with text "_To grant the required camera permission, please go to your system settings and make sure that Status > **Photos is selected**_" will be shown.

#### Expected behavior

Text of error: To grant the required camera permission, please go to your system settings and make sure that Status > **Camera is selected**.

#### Actual behavior

Text of error: To grant the required camera... > **Photos is selected.** 

![ezgif com-resize (16)](https://user-images.githubusercontent.com/67952253/89910048-09b96380-dbf0-11ea-9d34-bda33a030e84.gif)

### Reproduction

- Install Status and log in
- Open 1-1 or group chat
- Tap Image gallery icon
- Tap Camera icon
- Deny permission
- Tap Camera icon one more time

### Additional Information

- Status version: Nightly 11/08
- Operating System: Android 10

## Problem

For iOS: if permission to Camera was denied and if you tap to camera icon in 1-1/group chat, pop-up with information (error) about permissions will not appear. 

#### Expected behavior

Error "To grant the required camera permission, please go to your system settings and make sure that Status > Camera is selected" is expected, as for permission to Image gallery.

#### Actual behavior

Nothing happens after tapping Camera icon, no error/information message.

### Reproduction

- Install Status and log in
- Open 1-1 or group chat
- Tap Image gallery icon to open Image panel
- Tap Camera icon
- Deny permission
- Tap Camera icon one more time

### Additional Information

- Status version: Nightly 11/08
- Operating System: iOS 13

**Comment by churik** [comment]
Moved to #11271
