### ISSUE TITLE
Help text for Confirm password takes 2 lines instead of one

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1107]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There are 2 differences with develop build:
1. Confirm text is different: in develop it's "Confirm". In this build: "Please, re-enter password to confirm"
2. On Android text "Please, re-enter password to confirm" is shown in 2 lines instead of 1 long line. Second line is cut. 
![confirm text](https://cloud.githubusercontent.com/assets/6584810/25520601/bf29ce96-2bfc-11e7-8b7e-841d1074a2a0.png)

On iOS text is shown in 1 line
![confirm text in ios](https://cloud.githubusercontent.com/assets/6584810/25520774/7e2e8aac-2bfd-11e7-9e92-c1c7707b45a4.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Not sure why we have different hint text. It's fine to get new text but it should be shown in the same way on iOS and on Android. Most likely in 1 line.
#### Actual behavior
[comment]: # (Describe what actually happened.)
On Android hint text is shown in 2 lines and 2nd line is cut
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and create new account
- Create password
- Check how help text is shown for confirm password

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d22
* Operating System: Android 

### Instabug
https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/641

**Comment by rasom** [comment]
I reverted "Please, re-enter password to confirm" to "Confirm" and now it looks fine... But in general this issue is not related to `chat-api-rebase`: this problem still appears for languages where placeholder is long.

**Comment by annadanchenko** [comment]
not relevant anymore because of new onboarding
