### ISSUE TITLE
Issues in height calculation of image/sticker panel view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11075]
# Bug Report

## Problem

If open chat (any type), open keyboard, send the app to the background and open it again, the input field will be shifted upwards.

#### Actual behavior

![ezgif com-resize (12)](https://user-images.githubusercontent.com/67952253/89545427-a00e1380-d803-11ea-9bb9-2e88576c3aa6.gif)

### Reproduction

- Open chat view
- Open keyboard
- Send the app to background
- Open the app

### Additional Information

- Status version: Nightly 12/08
- Operating System: Android 8, 10

## Problem

If switch keyboard to sticker panel while scrolling long message, sticker/image/command panel height changes, sometimes it's overlapped with main tabs.
This case is rarely reproduced. The gif below is a case that was reproduced before cleaning up the storage of the device.

#### Actual behavior

![BAACAgQAAxkBAAEqDo1fLTNJXumiwIfk3n7bq6QhNzCrggACdAcAAo6vaVFMR8xOpLe0xhoE_1596797912 01](https://user-images.githubusercontent.com/67952253/90002169-974d8f80-dc92-11ea-93fb-83d616c1620e.gif)

### Reproduction

- Open chat view
- Send long message
- Scroll chat history with opened keyboard
- During scrolling long message switch to sticker/image panel

### Additional Information

- Status version: Nightly 12/08
- Operating System: Android 8, 10

## Problem

If open chat that contains a long message, open keyboard, send the app to the background, reopen it, and switch to sticker pad, then text input and sticker pad will be shifted upwards and overlaid on the chat history.
Сan reproduce on Xiaomi mi Note 9 (Android 10) only.

#### Actual behavior

![ezgif com-resize (13)](https://user-images.githubusercontent.com/67952253/90003560-8aca3680-dc94-11ea-85f5-3937002a9871.gif)

### Reproduction

- Open chat view
- Send long message
- Open keyboard
- Send the app to the background
- Open the app
- Switch to sticker panel

### Additional Information

- Status version: Nightly 12/08
- Operating System: Android 10
- Device: Xiaomi mi Note 9

**Comment by churik** [comment]
Moved to #11271
