### ISSUE TITLE
Custom bootnode settings cleared after app restart

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11076]
# Bug Report

## Problem

After custom bootnode created if to open it you see it's name and enode address and `Delete` button which works fine. 
However after relogin there is nothing from that when opening custom bootnode. Thus there is no option to delete custom bootnode after app restart. 

#### Expected behavior

Custom bootnode settings are present
#### Actual behavior

![dddwd38388d3d](https://user-images.githubusercontent.com/8749671/90005083-5f991480-dc9f-11ea-8aef-dede4b1482e3.gif)

Custom bootnode settings are absent after app restart

### Reproduction

- Open Status and create new account 
- Open `Profile` -> `Advanced` -> `Bootnodes` -> `+` (add new bootnode)
- Specify valid name and bootnode address (e.g. `enode://a8a97f126f5e3a340cb4db28a1187c325290ec08b2c9a6b1f19845ac86c46f9fac2ba13328822590fd3de3acb09cc38b5a05272e583a2365ad1fa67f66c55b34@167.99.210.203:30404`)
- Hit `Save`
- Open custom bootnode created
**Actual=Expected result:** Name, address and Delete button are present.
- Restart the app and login to account
- Open custom bootnode created again

### Additional Information
- Status version: release1.5/develop
- Operating System: Android and iOS

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
