### ISSUE TITLE
Crash after opening collectibles in specific multiaccount

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11077]
# Bug Report

## Problem

Status crashes if open collectibles, tap one, tap back and tap the same collectible again.
Reproducible in only one multiaccount. Seed phrase will be provided upon request.

#### Actual behavior

![ezgif com-resize (18)](https://user-images.githubusercontent.com/67952253/90008522-c406a480-dc9c-11ea-8a5b-688b77c52102.gif)

### Reproduction

- Log in
- Open Wallet view
- Tap account with collectibles
- Tap Collectibles tab
- Tap collectible (e.g. CryptoKitties)
- Tap back
- Tap collectible again

### Additional Information

- Status version: Nightly 12/08
- Operating System: Android

**Comment by churik** [comment]
Closing as it is in OpenSea now
