### ISSUE TITLE
Message disappears from the chat history if scroll it during long tapping

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11072]
# Bug Report

## Problem

If long tap to a message to call reaction menu and scroll it without lifting your finger from the screen, the message disappears from the chat history. If after that open any other tab (e.g. browser), send the app to background and open the app again, all disappeared messages will appear with the reaction menu and will be overlaid to the last screen.

#### Actual behavior

![ezgif com-resize (17)](https://user-images.githubusercontent.com/67952253/89920459-b863a100-dbfc-11ea-9618-0d1dec6121a8.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open chat (any type)
- Send several messages (all types)
- Long tap to any message and scroll without lifting your finger from the screen
- Open Browser view
- Send the app to background
- Open Status

### Additional Information

- Status version: Nightly 11/08
- Operating System: Android 8,10

**Comment by churik** [comment]
still valid on nightly 10/05/21

**Comment by qoqobolo** [comment]
Messages don't disappear anymore, only the issue after returning from the background is still reproducible.
Consider it as `Won't fix` and close this one.
