### ISSUE TITLE
Timestamp duplicates in long text message in chat view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11084]
# Bug Report

## Problem

If send a message 2 or more lines long and shortly tap it, a duplicate of timestamp will appear. On Android 8 (LG V20) long message (~2000 characters) from another user always contains a duplicate of timestamp.

#### Actual behavior

![Снимок экрана 2020-08-13 в 5 31 44 PM](https://user-images.githubusercontent.com/67952253/90154860-ebd43600-dd8a-11ea-8245-bc2d0a77b6f8.png)

### Reproduction

Case 1:
- Open chat (any type)
- Send a text message 2 or more lines long
- Tap it

Case 2:
- User 1 sends a long message to User 2
- User 2 opens chat with User 1

### Additional Information

- Status version: Nightly 13/08
- Operating System: Android 8, 10

**Comment by Ferossgp** [comment]
@qoqobolo how did you get the white background on message in second case? Asking cause usually it should be light blue

**Comment by qoqobolo** [comment]
@Ferossgp I can reproduce it each time on **LG V20** (Android 8) when I send a message 6000+ characters long from another device. But sometimes (can't determine a particular amount of characters) background of the message becomes white with ~5500 characters, i.e. one time message has a white background with 5500 and another time it's light blue. 

Moreover, if send the same message (6000+) from LG to another device, on both devices it looks like an empty bubble (on LG it's white) without message but with timestamp. If I'm not mistaken, this issue has already been created before.
![Снимок экрана 2020-08-14 в 4 43 44 PM](https://user-images.githubusercontent.com/67952253/90261668-94e36500-de4d-11ea-9678-7bd3ecfea11c.png)
