### ISSUE TITLE
0 USD value of asset in Transaction request in 1-1 chat if this asset hasn't been enabled previously

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11098]
# Bug Report

## Problem

If the asset has not been enabled previously, when a transaction request in 1-1 chat is received, the value of this asset is zero (0 USD). 

#### Note

If enable this asset after receiving the request and **re-login** to Status, the value of the asset in 1-1 chat will be updated.

#### Expected behavior

Relevant value of an asset is shown when a transaction request is received.

#### Actual behavior

![ezgif com-resize (20)](https://user-images.githubusercontent.com/67952253/90624475-4c92c100-e218-11ea-9cb3-1c3c0635e8c1.gif)

### Reproduction

User 1:
1.  Open Wallet view
2. Three dots on the top right -> Manage assets
3. Сheck the box for AMB
4. Start 1-1 chat with User 2
5. Request transaction -> Choose AMB in the assets list -> Enter any amount (e.g. 50)
6. Tap Request

User 2:
1. Open 1-1 chat with User 1

### Additional Information

- Status version: Nightly 19/08

**Comment by churik** [comment]
better just don't display fiat value for such cases, to display 0 is not user-friendly from my POV and should be fixed

**Comment by qoqobolo** [comment]
Is not reproducible on Nightly 30/11/21
