### ISSUE TITLE
Unread message counter is not updated for the first message after changing status of command message in 1-1 chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11105]
# Bug Report

## Problem

If User 2 declines transaction request from User 1, navigates to Home screen, and receives one more text message from User 1, counter for this new unread message won't be shown. If User 2 receives one more text message while on Home screen, the unread message counter will show "1" instead of "2". 
However, after relogin "2" unread messages will be shown on Home screen. 

#### Expected behavior

The unread message counter counts the first message after a declined transaction request.

#### Actual behavior

![ezgif com-resize](https://user-images.githubusercontent.com/67952253/90778383-d87e1900-e2fc-11ea-8d90-97e71cf28c6b.gif)

### Reproduction

User 1: 
- Open 1-1 chat with User 2
- Send Transaction request 

User 2:
- Open 1-1 chat with User 1
- Decline Transaction request 
- Open Home view

User 1:
- Send a message to User 2

User 2:
- Check the counter of unread messages (without opening the chat)
- Relogin
- Check the counter

### Additional Information

- Status version: Nightly 20/08
- Operating System: Android 10, iOS 13

**Comment by churik** [comment]
Also reproducible when user 1 shares address for example (for transaction message in 1-1 chat) and then sends message.
@cammellos take a look when you've got a chance, thank you!
