### ISSUE TITLE
Issues in error handling when scanning QRs generated from universal links containing particular characters or upper case

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11116]
# Bug Report

## Problem

When scanning QR-code that was generated from a link containing "%", the error "Malformed decodeURI input" ("URI error on iOS)" occurs.
If try to scan the correct QR-code after closing the error, nothing happens (no error/pop-up). It's necessary to reopen the scanner to scan the correct QR.

#### Expected behavior

1. More user-oriented error text;
2. Auto closing scanner after error or the ability to scan the correct code without reopening QR scanner

#### Actual behavior

![ezgif com-resize (3)](https://user-images.githubusercontent.com/67952253/91422228-2b088980-e857-11ea-8ba0-359d064b4dcf.gif)

### Reproduction

- Home view -> + -> open QR-scanner
- Scan QR generated from link: https://join.status.im/u/dikhasi%.stateofus.eth
![Screenshot 2020-08-27 at 13 00 33](https://user-images.githubusercontent.com/67952253/91434636-63af5f80-e865-11ea-8230-fdfa6287d414.png)
- Tap "Cancel" in pop-up
- Delete "%" from the link 
- Scan QR generated from the valid link: https://join.status.im/u/dikhasi.stateofus.eth
![Screenshot 2020-08-27 at 13 04 32](https://user-images.githubusercontent.com/67952253/91434971-e46e5b80-e865-11ea-8df1-aab66441b607.png)
- Close QR-scanner
- Open QR-scanner
- Scan the valid QR 

## Problem

When scanning  QR-code that was generated from a link for public chat but containing upper case there is no reaction from the QR scanner (no error/pop-up). Also, if try to scan the correct QR-code after that, it's necessary to reopen the scanner.

#### Expected behavior

1. Error about invalid public chat characters is shown (e.g. “Only lowercase letters (a to z), numbers & dashes (-) can be used to join public chat”
2. Auto closing scanner after error or the ability to scan the correct code without reopening QR scanner

### Reproduction

- Home view -> + -> open QR-scanner
- Scan QR generated from link: https://join.status.im/somepublicchaT
![Screenshot 2020-08-27 at 13 02 08](https://user-images.githubusercontent.com/67952253/91434730-8ccff000-e865-11ea-90f8-13a55d039a96.png)
- Replace the last "T" to "t"
- Try to scan the valid QR (https://join.status.im/somepublicchat)
![Screenshot 2020-08-27 at 13 06 36](https://user-images.githubusercontent.com/67952253/91435166-38794000-e866-11ea-839d-2e75cab45919.png)
- Close QR-scanner
- Open QR-scanner
- Scan the valid QR 

## Problem

When scanning  QR-code that was generated from a link for 1-1 chat (with chat-key or ENS) containing upper case, the error "Cannot resolve ENS name" occurs.

#### Expected behavior

Relevant error text.

#### Actual behavior

![Screenshot 2020-08-27 at 12 22 49](https://user-images.githubusercontent.com/67952253/91431132-3ad89b80-e860-11ea-896f-bd604491cf8d.png)

### Reproduction

- Home view -> + -> open QR-scanner
- Scan QR generated from link (the last letter is in upper case): https://join.status.im/u/0x044e1f542d98c71a3789e2c12bd6e2b67696d98d957282d579c902d42eae2d8d54b1d61fe1acdcd748b37e6ff24e82ebfa5338f082c6a56b99ca1a58b52a919abB
![Screenshot 2020-08-27 at 12 55 54](https://user-images.githubusercontent.com/67952253/91434844-affa9f80-e865-11ea-8ba1-13e91230c3a7.png)

### Additional Information

- Status version: Nightly 27/08
- Operating System: Android, iOS

**Comment by churik** [comment]
marking as won't fix
