### ISSUE TITLE
Move notifications on Android to status-go

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11117]
### Description
Notifications in java, as they are disconnected from the rest of the app, we should move them to status-go, using Java only to display them.

This issue should be resolved before addressing other issues in the epic #10737

### User Story
As a developer, I want to maintain logic of local notifications on Android in status-go so that I don't have to duplicate any code/data.

### Description

Currently android notifications are in the Java layer, they parse `messages.new` and notify on the content.
The issue with this approach is that they don't have access to a lot of information, ENS names, duplicated messages etc.

The building of notifications should be in status-go, so that the Java layer simply displays what is instructed by status-go, instead of having to replicate the logic in Java.

Local push notifications (in-app notifications) are dependent on this issue

**Comment by hesterbruikman** [comment]
cc @cammellos @Ferossgp

**Comment by guylouis** [comment]
@cammelos 
given https://github.com/status-im/status-go/pull/2026 , can this one be closed ?

**Comment by cammellos** [comment]
@guylouis no, this one is about chat notifications, the other was only taking care of transactions notfications
