### ISSUE TITLE
Can't send image without description in 1-1 and group chats 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11113]
# Bug Report

## Problem

An error "Cannot read property 'indexOf of null" occurs when sending an image message without description in 1-1 or group chats. 

#### Actual behavior

![ezgif com-resize (1)](https://user-images.githubusercontent.com/67952253/91176512-a98fea80-e6e2-11ea-809b-1c5d30ba9a7e.gif)

### Reproduction

- Start 1-1 or group chat
- Try to send image only (without text message below)

### Additional Information

- Status version: Nightly 25/08
- Operating System: Android and iOS

**Comment by churik** [comment]
Part of test_pair_devices_group_chat_different_messages - check should be enabled after fix
