### ISSUE TITLE
Timestamp in text, emoji messages, and replies is duplicated or shifted out the bubble

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11127]
# Bug Report

## Problem

The timestamp is duplicated in text messages and replies in all types of chats. If send a long emoji message the timestamp will be shifted out the bubble.

#### Actual behavior

![Screenshot 2020-09-01 at 12 13 13](https://user-images.githubusercontent.com/67952253/91839402-4a385a00-ec4f-11ea-9520-dc93f54eba10.png)
![Screenshot 2020-09-01 at 12 30 04](https://user-images.githubusercontent.com/67952253/91839407-4b698700-ec4f-11ea-82f2-3acb74bb3163.png)

### Reproduction

- Start any chat
- Send and receive some text and emoji messages, reply to any message

### Additional Information

- Status version: Nightly 1/09
- Operating System: Android 10

**Comment by churik** [comment]
closed in https://github.com/status-im/status-react/pull/11157
