### ISSUE TITLE
Investigate use of a community token list

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11124]
# Problem
Maintaining a token list is difficult as new tokens are introduced all the time and popularity varies over time

## Implementation
options:
- https://uniswap.org/blog/token-lists/
- https://github.com/ethereum-lists/tokens
- ... other

## Acceptance Criteria
- Consistent asset design, ideally using our current design
- Library can be integrated without calling 3rd party services
- Supported default tokens must be supported by Cryptocompare or Coingecko

**Comment by hesterbruikman** [comment]
Consider adding our own list to https://tokenlists.org/

**Comment by guylouis** [comment]
consider myetherwallet list 
https://github.com/MyEtherWallet/ethereum-lists/tree/master/src/tokens/eth

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
