### ISSUE TITLE
Blank space appears below the large emoji message on chat view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11120]
# Bug Report

## Problem

If send a large emoji message (~200+ emoji) from the Android device in any type of chat, then the sender will have an blank space under it. The more emoji, the longer the blank space.
If the emoji message contains at least one letter, number, or another symbol, this space does not appear.
If send a reaction to this message, the reaction icon will be placed under the blank space.

#### Actual behavior

![ezgif com-resize (4)](https://user-images.githubusercontent.com/67952253/91463571-d7fcf980-e88b-11ea-89b1-c1f1d6838934.gif)

![Screenshot 2020-08-27 at 17 33 55](https://user-images.githubusercontent.com/67952253/91463425-a84df180-e88b-11ea-8526-2f195142f407.png)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open any chat (1-1, group or public)
- Send 200 / 500 / 1000 emoji
- Send reaction to this message

### Additional Information

- Status version: Nightly 27/08
- Operating System: Android 8, 10

**Comment by churik** [comment]
Agree that's edge case, nice-to-have fixed but can definitely live with it.
@qoqobolo reopen if think that it is important to fix
