### ISSUE TITLE
Warning to users sending ERC20 directly to smart contract

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11136]
# Feature Issue

Add a warning when users are trying to use the Wallet Send function directly to a smart contract. 

This would important for preventing newbie users to make the common mistakes of sending tokens to a contract that does not accept it.

Related history:  https://twitter.com/NomiChef/status/1299960487153549312

### User Story

As a user without technical knowledge, I want to be warned when I am about to make a common mistake, such ash sending tokens directly to whatever I think is the right place.

### Description

Whenever a user tries to send any ERC20 token to an address where `eth.getCode(destinationAddress).lenght > 0` a warning is displayed like this (or equivalent message):
```
# Attention!
You are trying to send tokens to a smart contract, which can cause a problem because smart contracts cannot identify this interaction.
Smart contracts consume tokens using a "approve and call" scheme, so it can identify your deposit and interact over it.
If you are trying to interact with a DApp, such as a DeFi project or crypto-game, then you are probably making a mistake, and you should use the "Cancel" button and inform yourself on how to properly interact with this DApp (it's probably using the Status Browser and navigating to the web3 enabled dapp page).
If you are trying to send tokens to another user, and therefore the destination address refers to a "user controlled wallet" (such as a Multisig, Gnosis Safe or similar) then you can check "I know what I'm doing" and dismiss this warning.

[ ] Destination address is a user controlled address and I know what I'm doing. [ ] Don't ask me again for this address. [ ] Never warn me again.
 
[Cancel this operation] [Continue to Send] 
```

### Acceptance Criteria

Users are warned when sending ERC20 to a smart contract using the wallet send feature.

### Notes

This does not apply to ETH, as for ETH smart contract can reject value sent.

**Comment by 3esmit** [comment]
Happened again https://twitter.com/kevingaspar/status/1306688623958466565, more than 300k of losses due mistakes like this https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984?a=0x1f9840a85d5af5bf1d1762f925bdaddc4201f984

**Comment by 3esmit** [comment]
Aaand again... https://twitter.com/TokenOops/status/1307512952594071552?s=19

**Comment by John-44** [comment]
@3esmit Great idea, I've added a screen to cover this scenario in the wallet refresh designs I'm working on atm.  How about whitelisting smart contract wallets (e.g. Gnosis Safe, Argent, etc...) and then not posting this warning for the whitelisted smart contract addresses?  Then we can make the copy much more concise.     
![sending_funds_to_smart_contract_warning_old](https://user-images.githubusercontent.com/22846356/93916378-5de05900-fd01-11ea-867a-be9e72492987.png)

**Comment by flexsurfer** [comment]
@johnlea-quiup could you please add copy here?

**Comment by John-44** [comment]
@flexsurfer copy as per screenshot above:

Title: Warning!

Description: The address you entered is a smart contract, sending funds to this address may result in loss of funds.  To interact with a DApp, open the DApp in the Status DApp Browser. 

Actions: [Cancel] <-- primary  [Continue] <-- secondary

**Comment by 3esmit** [comment]
We can have global and local lists, but this can be left to another interaction. For now add a "Learn more" to some docs or other screen in app explaining why and when this is an exception.

In this other interaction we can discuss also other rules, like users sending to users (under stateofus.eth) in chat may not need to display this warning, as if one user set his address in ens it's probably his wallet.

**Comment by churik** [comment]
Fix in https://github.com/status-im/status-react/pull/11204 is only on Recepient screen when pasting contract address in field, so it is still reproducible when scanning QR with contract code or EIP link with contract code as recepient

**Comment by John-44** [comment]
@flexsurfer minor update to copy and design.  @3esmit with the new alert style I've posted it would be possible to link from the alert to a 'learn more' URL when such a URL exists.

I do think we should at least whitelist the most popular wallet contracts in the same release as this lands, as otherwise we will get complaints from users who become annoyed from seeing this warning every time they send funds to Gnosis and Argent wallets.

**Comment by hesterbruikman** [comment]
@johnlea-quiup could you please create an issue for the updates 🙏 I think this just crossed the PR merging. Gives a little bit more time to think about a Learn more link and whitelisting while a safeguard is in place. Both are straightforward in terms of design and implementation, but we currently don't have a good workflow to maintain this content (especially across Mobile and Desktop)

**Comment by 3esmit** [comment]
@johnlea-quiup I think for #11204 only the link is interesting, but as #11204 is already merged, and adding a url link to browser, is simple another PR could include the link once it exists.

For the safe list, Is a slight more complex change, and it still wont be the ideal solution, but it's an improvement instead of warning to everything. 

I can provide a list of hashes with the "contract code" data that are commonly used to receive ERC20 directly, so the app would have this hardcoded list (or it can be loaded from a smart contract).

**Comment by 3esmit** [comment]
@hesterbruikman I think we can keep the discussion on this issue, but later create smaller issues for baby-stepping to the final solution.

**Comment by 3esmit** [comment]
BTW, if we could have #11204 in 1.7 would be great, because better safe than sorry, and a only a small number of users (trying to deposit on GnosisSafe or MultiSigWallet) would be "affected by this annoyance".

**Comment by 3esmit** [comment]
As @churik mentioned, the PR #11204 is only for "pasting in the field of receipient". 
I think is important to detect in any situation, for example, using qr code scanner to make this mistake is a possible scenario: 
1. a user coming from bitcoin (thinks that only transfer exists); 
2. reads about some protocol in his news feed; search more in the internet and ends up in the token smart contract of that project (usually the most visible smart contract);
3. user scans the contract address qr-code in a block-explorer, to use it as destination to send tokens, in an attempt to participate in the protocol;
4. rekt.

**Comment by John-44** [comment]
@3esmit @hesterbruikman  split into two new issues, apologies for not seeing the 'Merged' status above my comment and making design changes in this issue after this had already been merged.

Anyhow, new issues are #11210 and #11209

**Comment by John-44** [comment]
@3esmit @hesterbruikman comment updates reverted as well, so the merge can be correctly accepted.

**Comment by 3esmit** [comment]
https://github.com/status-im/status-react/issues/11264

**Comment by churik** [comment]
Closed as part of https://github.com/status-im/status-react/issues/11209
