### ISSUE TITLE
Implement privatekey importing, in the next Google Play release

### ISSUE THREAD

**Issue by danimesq** [status-im/status-react#11133]
https://github.com/status-im/status-react/issues/9749 still isn't available in a app store update.

It limits its usage by people who already have a MetaMask/Ethereum key.

**Comment by hesterbruikman** [comment]
Thanks for adding this issue @DaniellMesquita 

fyi There is currently an option inside Status Wallet to add an Ethereum account by private key:
`Wallet` > `Add account` > `Enter a private key`

This is admittedly different from importing the full tree by private key (`Sign out` > `Access existing keys`); I.e. When adding with private key inside the wallet you wouldn't be able to derive, or view multiple keys derived from, your MetaMask/Ethereum key inside the app or use the `0x.04` leaf of your MetaMask/Ethereum keypair as a chat key. 

Perhaps this could fit your use case in the short term

cc @0kok0 @johnlea-quiup

**Comment by churik** [comment]
Closing as the stale issue, please reopen if still important.
