### ISSUE TITLE
Sometimes user can get group chat history prior joining

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11130]
# Bug Report

## Problem
In some cases messages sent after user was invited but before he joined are visible to invited user.
From core discussion:
> The behavior is that you should not see any message sent before you were invited (that should always be the case, otherwise is a bug)
You should see messages after you joined, if you don't is a bug
While you are invited and not joined, the behavior is not well defined. For compatibility issues, those messages are sent, but we don't necessarily retrieve them from the mailserver. We can drop compatibility (it was a pre v1 thing anyway, so it should not matter), so that the behavior is that you should see messages since you joined.

#### Expected behavior
Messages are not visible until user joined group chat

#### Actual behavior
sometimes messages are fetched

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Invite user A
- Send messages to group chat
- as user A: wait for messages (not join)

### Additional Information

- Status version: nightly 01/09/20
- Operating System: Android, iOS

**Comment by churik** [comment]
cc @cammellos @hesterbruikman

**Comment by cammellos** [comment]
This should be fixed, closing for now, feel free to re-open
