### ISSUE TITLE
No validation messages in Console if enter non-commands (e.g. some text, symbols)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1114]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In console enter "some text" or "!". Expected: validation messages like "Unexpected identifier", "Unexpected end of input", etc. Currently, there is no feedback from Console.
![console feedback](https://cloud.githubusercontent.com/assets/6584810/25531533/5bdc2914-2c2a-11e7-8c08-a8328f2bf061.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If send "some text" then message shown "Unexpected identifier"
#### Actual behavior
[comment]: # (Describe what actually happened.)
If send "some text" then no message from console is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Console
- Send "some text" to console

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d22
* Operating System: Android and iOS

**Comment by rasom** [comment]
fixed with #1124
