### ISSUE TITLE
Self mention isn't resolved in group chat and 1-1

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11152]
# Bug Report

### Case 1
If create a group chat or join one as a member, type **_@_**, select own name in the suggestions list, and send this message, the mention will not be resolved.

#### Expected behavior

Self mention is resolved. Tapping on the mention opens the user's own profile tab.

#### Actual behavior

![ezgif com-resize (13)](https://user-images.githubusercontent.com/67952253/92913695-495faf00-f42b-11ea-81eb-6c7b689376b5.gif)

#### Reproduction

- Create or join group chat
- Type @ in text input
- Select your name in the suggestions list
- Send message
- Tap the mention

### Case 2

Own name appears in the suggestions list after getting history from public chat and sending messages to 1-1 (probably not an issue).
**Also, it isn't resolved after sending the message.**

#### Expected behavior

Self mention is resolved. Tapping on the mention opens the user's own profile tab.

#### Actual behavior

![Screenshot 2020-09-11 at 16 19 12](https://user-images.githubusercontent.com/67952253/92936580-8a1af080-f44a-11ea-9599-7150aa303c41.png)

#### Reproduction

- Start 1-1 chat
- Join public chat 1 (in my case chu)
- Scroll to the beginning of history (wait until history will be loaded)
- Open 1-1 chat
- Send message
- Reopen 1-1 chat
- Start @
- Select your name in the suggestions list
- Send message
- Tap the mention

### Additional Information

- Status version: develop with [16fecc2](https://github.com/status-im/status-react/commit/16fecc2ac68439f2bae9d1adf73416669a9acca0) 
- Operating System: Android 10, iOS 13

**Comment by churik** [comment]
Should be closed in #11182
