### ISSUE TITLE
Timestamp is overlapped with mention, and the distance between ENS and @ appears if ENS mention follows the arabic text

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11154]
# Bug Report

## Problem

If enter an Arabic text, type @, select ENS name from the suggestions list, and send this message, the order in the message will be broken: timestamp will be overlapped with mention, and the distance between ENS and **_@_** will appear.

#### Actual behavior

![Screenshot 2020-09-11 at 14 54 55](https://user-images.githubusercontent.com/67952253/92927980-c34d6380-f43e-11ea-956f-9b69715e4703.png)

### Reproduction

- Open any chat
- Type some arabic text
- Type @ and select ENS from the suggestions list
- Send message 

### Additional Information

- Status version: develop with [16fecc2](https://github.com/status-im/status-react/commit/16fecc2ac68439f2bae9d1adf73416669a9acca0) 
- Operating System: Android 10, iOS 13

**Comment by churik** [comment]
Leftover from https://github.com/status-im/status-react/pull/11157
![image](https://user-images.githubusercontent.com/4557972/93091088-f3467200-f69d-11ea-9a69-953feccb8b0e.png)
