### ISSUE TITLE
Mention suggestion list contains blocked users

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11160]
# Bug Report

## Problem

If start 1-1 chat after blocking several users, the suggestion list still will contain blocked users. 
It might be useful in the current situation to hide them when some users have a lot of blocked spammers.

#### Expected behavior

Suggestion list doesn't contain blocked users.

#### Actual behavior

![Screenshot 2020-09-14 at 13 22 55](https://user-images.githubusercontent.com/67952253/93080088-73b0a700-f68d-11ea-8dd0-dbb911a9eeba.png)

### Reproduction

- Join some public chat
- Block several users 
- Type `@` to check suggestions list
- Start 1-1 chat and check suggestions list

### Additional Information

- Status version: Nightly 14/09
- Operating System: Android 10, iOS 13

сс @hesterbruikman

**Comment by churik** [comment]
Just to add: in case of a large amount of blocked users (it is important now, as users sometimes have > 100 blocked users) suggestions list will be messy due to a lot of "trash" blocked users.
That's why INO it should be fixed with mentions feature.

**Comment by hesterbruikman** [comment]
@qoqobolo looks like this was fixed in https://github.com/status-im/status-react/pull/11181 Not sure why it didn't autoclose. Please reopen if the issue persists

**Comment by qoqobolo** [comment]
@hesterbruikman just checked, looks good for me, so approve closing.
