### ISSUE TITLE
Hashtag symbol is cut from messages when replying or copying (only plain text is shown)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11161]
# Bug Report

## Problem
The hashtag symbol is cut from messages when replying or copying messages from chat.

#### Expected behavior
The hashtag symbol is visible

#### Actual behavior
<img width="465" alt="Screenshot 2021-12-06 at 17 00 26" src="https://user-images.githubusercontent.com/67952253/144879307-25945b4f-853b-489f-9def-87f030c6caa5.png">

### Reproduction

- Open Status
- Send a message with a hastag
- Reply to it
- Try to copy and paste it

### Additional Information

- Status version: nightly 14/09/20
- Operating System: Android, iOS

**Comment by Serhy** [comment]
I guess it makes sense to include here similar bug that when copying message with hashtag (e.g. `#statuschat`) then sharp sign in stripped so only letters copied.

**Comment by churik** [comment]
Behavior  with hashtag (https://github.com/status-im/status-react/issues/11161#issuecomment-693426432) is still reproducible
UPD: reproducible on 1.17

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.

**Comment by churik** [comment]
again relevant on nightly 21/03/23
