### ISSUE TITLE
Text keyboard instead of numeric is shown in Wallet for Send and Recieve

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1116]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Only iOS. In Wallet tap in Send or Receive - text keyboard is shown instead of numeric
![wallet keyboard](https://cloud.githubusercontent.com/assets/6584810/25537548/2d9e8eba-2c3f-11e7-8e7f-98c60207a196.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Numeric keyboard is shown to enter sum
#### Actual behavior
[comment]: # (Describe what actually happened.)
Text keyboard is shown to enter sum
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Wallet
- Tap in Send

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6 and 0.9.6d22
* Operating System: iOS only

**Comment by alwx** [comment]
It may sound strange, but iOS doesn't completely support 'number' input type: http://stackoverflow.com/questions/19684855/force-ios-numeric-keyboard-with-custom-currency-pattern

The best solution is to use hacky javascript to force iOS to display the right keyboard, but I am not sure that it's worth it. What do you think, @jarradh, @rasom ?

**Comment by annadanchenko** [comment]
new wallet is implemented in 0.9.12 and older wallet DApp functionality is no longer used. Not a bug anymore as of 0.9.12
