### ISSUE TITLE
No margin between "Block this user" button and main tabs panel on user profile view on iOS

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11163]
# Bug Report

## Problem

![ezgif com-resize (15)](https://user-images.githubusercontent.com/67952253/93101896-217e7e80-f6ab-11ea-898c-2c4da6f0ca75.gif)

### Reproduction

- Open any public chat
- Open some user profile
- Scroll to the bottom

### Additional Information

- Status version: Nightly 14/09
- Operating System: iOS 13

**Comment by churik** [comment]
very easy to fix, and can be hard to block users for some devices - so adding as 1.7
