### ISSUE TITLE
No reaction pop-up appears when long-tap upon link in the chat message

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11168]
# Bug Report

## Problem

When user long taps upon link (or tag) in the chat message there is no Reactions-Reply-Copy pop-up menu appears. INstead there is 'Open in Status' pop-up (for link) pop-up.

However, long-tapping on the any other place of message where text is present does the job. But it may be not obvious for users (especially if message consists only weblink or only tag when in that case the only way to copy content is to tap somewhere on the place of message timestamp).

#### Expected behavior

Single tap event produces respective action to link/tag (already the case)
Long-tap upon weblink/tag in the message then reactions pop-up menu appears

#### Actual behavior

'Open in Status' appears when long-tap upon weblink/tag in the message

![2020_09_15_19_55_18_trim](https://user-images.githubusercontent.com/8749671/93241119-99bd7080-f78d-11ea-9434-78dd626a1bea.gif)

### Reproduction

- Open Status and join any chat 
- Send text message with weblink (or tag) (e.g. `Link https://status.im`)
- Do a long tap on the link in the message 

### Additional Information
- Status version: any
- Operating System: Android and iOS

**Comment by cammellos** [comment]
Probably a won't fix, feel free to re-open @Serhy if you think otherwise!

**Comment by Serhy** [comment]
@cammellos the time has come to reopen this issue :)
Now we have also "Edit" and "Pin" options for messages, which increase importance of having such message options for links or tags (e.g. if wrong URL - it's good to have ability to Edit it,  or to 'Pin' the link in chats)

Issue description kept the same.

**Comment by churik** [comment]
Agree, would be nice to fix that

**Comment by churik** [comment]
Can see menu now quite easily.
Fixed on nightly 27/07/2022
