### ISSUE TITLE
No redirect to own user profile if tap self mention in chat view after re-login 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11173]
# Bug Report

## Problem

If tap self mention in received or sent message in any type of chat, then there is no redirect to own User profile.
If open own User profile via the main tabs, and then return to chat view and tap the mention again, the user will be redirected to the profile.

#### Expected behavior

Redirect to own User profile when tap self mention.

#### Actual behavior

![ezgif com-resize (16)](https://user-images.githubusercontent.com/67952253/93331896-4432a380-f821-11ea-9532-1f789181f812.gif)

### Reproduction

- Log in
- Open chat
- Send self mention
- Tap self mention in sent message
- Open User Profile via main tabs panel
- Navigate to the chat
- Tap self mention

### Additional Information

- Status version: Nightly 16/09
- Operating System: Android 10, iOS 14

**Comment by churik** [comment]
Don't think it is crucial for 1.7
