### ISSUE TITLE
Redirect to chat view when tap to push notification on iOS

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11176]
As a user
I want to be redirected to the chat were the message was sent when tapping on a notification
So I can easily view the new message

### Description

If tap push notification when the app is in the background the last opened screen will be shown. If tap push notification after the app was closed after login Home screen will be opened. 

### Acceptance criteria

When tapping on notification coming from chat X, chat X is opened. If logged out, chat X should be opened upon login.

An hashed chatID is passed in the notification. https://github.com/status-im/status-go/blob/a759d9dd676e680bafd3f25c693a61605b39b7a2/protocol/pushnotificationserver/gorush.go#L70
This can be used to open the right chat.

Mind that it is possible to receive notifications from logged out accounts, in some cases, so chatID might not be present. In such cases the home screen should be shown.

**Comment by cammellos** [comment]
Will be changing this to a feature as this was out of scope

**Comment by churik** [comment]
still relevant on release 1.11

**Comment by churik** [comment]
closing as part of https://github.com/status-im/status-react/issues/11715
