### ISSUE TITLE
Add DApp permissions placeholder when empty

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#11171]
As a user 
I want to see a placeholder on the dapp permission page
So I can immediately understand what it is about.

### Description

DApp permissions page has no explanation why it is empty.
To reach, navigate to profile/privacy and security/Set dapp access permissions.

![Screenshot 2020-09-16 at 13 08 17](https://user-images.githubusercontent.com/5786310/93323910-dfc21500-f81d-11ea-8bca-1265fc0de875.png)

### Acceptance criteria

The page should read: "DApp permissions will appear here", centered font 15 / 400 / Grey

**Comment by cammellos** [comment]
@errorists what do you think the text should be? do you think this is an issue worth fixing?

**Comment by errorists** [comment]
@cammellos the template I use for empty states goes like this `<Feature name> will appear here`, so in this case `DApp permissions will appear here`, centred font 15 / 400 / Grey

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
