### ISSUE TITLE
Audio message record button is changed if start to record audio, open keyboard and reopen audio message panel

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11178]
# Bug Report

## Problem

If start recording an audio message and switch to the keyboard while recording, and then open the audio message panel again, the button of the recording will not have an outer circle.
The issue isn't reproducible every time.

#### Actual behavior

![ezgif com-resize (19)](https://user-images.githubusercontent.com/67952253/93358199-7bb14800-f841-11ea-94b2-01970236bfaf.gif)

### Reproduction

- Open chat
- Tap the audio message icon on the input field 
- Start to record audio
- Switch to the keyboard without tapping stop (tap text input or keyboard icon)
- Tap audio message icon again

### Additional Information

- Status version: Nightly 16/09
- Operating System: Android 10, iOS 14

**Comment by cammellos** [comment]
I would close this as a "Won't fix", as it seems a minor cosmetic issue and little impact on the user, would you be ok with this @qoqobolo ? cc @churik @Serhy

**Comment by Serhy** [comment]
Have not objection to won't fix it.
