### ISSUE TITLE
No notifications for mentions (but works on iOS it to re-enable 'Show @ mentions' option)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11172]
# Bug Report

## Problem

When user receives message with his username mentioned, - there is no push notification appears on iOS (and Android). 
NOTE: By default when we enable notification on iOS the `Show @ mentions' option enabled as well. In case of turn OFF and back ON the `Show @ mentions` solves the problem. Maybe this setting not applied by default when enabling mentions on iOS.
On Android at the moment there is no such setting so mentions not trigger notification in any case (even if to re-enable Notification setting)

#### Expected behavior

PN appears for message with mention in public chat

#### Actual behavior

No PN appears for message with mention in public chat

### Reproduction

- Open Status on iOS (UserA) and open Status on Android (UserB)
- Create new accounts on both devices and while onboarding process enable Notifications
- UserA and UserB joins same public chat
- UserA puts app on background
- UserB sends the text message with mention on UserA
**Actual result:**  No PN appears on iOS (UserA)
**Expected result:**  PN 'Someone mentioned you' appears on iOS (UserA) device
- Viceversa, UserB(Android) puts app on background and UserA sends mention in public chat
 **Actual result:**  No PN appears on Android (UserB)
- _(Optional to show when it works):_ UserA (iOS) re-enables `Profile` -> `Notifications` -> `Show @ mentions` settings and puts app on background
- UserB sends mention message to UserA
**Actual result = Expected result:** PN 'Someone mentioned you' appears on iOS (UserA) device. But since there is no such setting on Android - such "trick" can't be applied. 

### Additional Information

- Status version: Develop 1.7
- Operating System: Android and iOS

**Comment by cammellos** [comment]
@Serhy this should be fixed in develop, would you mind checking when you have some time and close the issue if that's the case? 
Thanks!

**Comment by Serhy** [comment]
Yes, it's indeed fixed, confirmed with nightly build 18th of Sept. 
Closing this issue. Thanks, @cammellos
