### ISSUE TITLE
Select and view nickname as mention

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11179]
# Problem
When users have assigned a nickname, they likely expect to mention people by their nickname and only ever see the nickname as a way to recognize the given user. However, if users enter a nickname this might lead to collisions; People in the chat might have a ENS name that is the same as the nickname. This problem is addressed by letting people select the mention from a suggestion list.

Discussed flow:
- hierarchy Nickname, ENS name, 3-word name is followed in mentions
- when user enters @ mention suggestion list appears
- when user enters @x mention suggestion list appears with relevant users. This can be nickname starting with x or ens name starting with x (collision case) - both will including random name to differentiate
- when user taps on user in mention suggestion list, ENS/3w-name is shown in chat input box, highlighted as mention
- when user hits send, mention is shown in message as nickname

## Acceptance Criteria
User can select nickname as mention and view nickname in chat message

**Comment by hesterbruikman** [comment]
@rasom @errorists here's an issue to capture what we agreed yesterday on how to handle selecting a nickname as mention
cc @cammellos @qoqobolo @churik

**Comment by rasom** [comment]
<img width="802" alt="foo" src="https://user-images.githubusercontent.com/2364994/93855438-3026f000-fcc0-11ea-95ac-09ff80bdb9e6.png">

**Comment by rasom** [comment]
> hierarchy Nickname, ENS name, 3-word name is followed in mentions

it already works this way in messages
