### ISSUE TITLE
Add backwards compatibility for ENS Usernames

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11189]
# Feature Issue

Currently status-react registers ENS Usernames by calling a hardcoded smart contract address `0xDB5ac1a559b02E12F29fC0eC0e37Be8E046DEF49`

However this will break compatibility once the ENS Usernames get migrated to a new version as the UI don't knows the new address.

### User Story

As a developer I want that migrations on ENS Usernames happen seamlessly, even if they happen in a future version of Status App. 

### Description

UI reads owner of `stateofus.eth` and use it as the ENS Usernames registrar contract. 

Instead of the hardcoded address, UI (https://github.com/status-im/status-react/blob/develop/src/status_im/ethereum/stateofus.cljs) calls `ensRegistry.owner(namehash("stateofus.eth"))` to find out the ENS Username registrar payment address.

In future version of UsernameRegistrar, a ERC721 NFT would be created to each username, resolvable by `ensRegistry.resolver(namehash("stateofus.eth")).addr(namehash("stateofus.eth"))`. 

### Notes

For security purposes, it's important to keep using `approveAndCall`. The price should also be read from the smart contract and displayed on the UI.

**Comment by cammellos** [comment]
As part of this we need to decide whether we want to fetch it every-time, how often, whether to store it in the database, what happens if the network request fails etc.

**Comment by 3esmit** [comment]
It can be fetched right before attempting to register a name, i.e. on demand, as this won't happen frequently, and to register a name another requests are done anyway

**Comment by 3esmit** [comment]
Notice, I changed the way the ENS Registry is read to figure out the address of payment contract. This was done to support https://github.com/status-im/ens-usernames/issues/108. 
With this, the Address Resolver of `stateofus.eth` is set to the Payment Contract, and the owner of `stateofus.eth` is the Username NFT address (that would be handling the ENS functions).

For this to work, we need to configure `stateofus.eth` Resolver to the Payment Contract before this PR is merged.

Another option is to give the owner of `stateofus.eth` to the payment address, and the NFT can be authorized to handle `stateofus.eth` operations, however architecturally I think that's not ideal because it's mixing the concerns.

**Comment by rasom** [comment]
@3esmit 
`ensRegistry.resolver(namehash("stateofus.eth"))` returns `0x0000000000000000000000000000000000000000`, am I missing something here?

**Comment by rasom** [comment]
> For this to work, we need to configure stateofus.eth Resolver to the Payment Contract before this PR is merged.

ok, probably I just have to learn how to read

**Comment by 3esmit** [comment]
@rasom I'll request the change of this parameter in mainnet.

**Comment by 3esmit** [comment]
@rasom It's not possible to change the resolver due ENS bug Migration. Therefore I am changing this issue to use `ensRegistry.owner(namehash("stateofus.eth")) `, which was the original idea. 

Sorry for the inconvenience. I added a code-suggestion to your PR that will use owner instead of resolver.addr.
