### ISSUE TITLE
Add UNI, COMP, AAVE, BAL, AKRO tokens

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11185]
# Problem
Add UNI to token list as it's likely anyone who's used Uniswap with a Status wallet will want to view the token
https://uniswap.org/blog/uni/

Contract address: 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984

@simonricoo @flexsurfer 

## Acceptance Criteria
UNI can be selected from `Manage assets`

**Comment by simonricoo** [comment]
New icon design in SVG: https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=341%3A45

**Comment by churik** [comment]
nice-to-have in 1.7, wdyt @hesterbruikman ?

**Comment by hesterbruikman** [comment]
Absolutely! Would not block release because of it though, looks like there's some time (depending on mention progress). But the sooner we can get notifications on iOS out the better

**Comment by flexsurfer** [comment]
most users have added UNI as a custom token, we need to check this case: what will happen if we add it in our list and a user updates the app which already has this token as custom

**Comment by hesterbruikman** [comment]
@flexsurfer not sure.... Would it be a case of conflicting acronym? Can test on a nightly. I assume that testing a PR won't work as the token needs to be manually added prior to installing the update

Related, there are a few other tokens to be added: COMP, AAVE, BAL, AKRO Is it easier to add these in one go or as a separate issue?

**Comment by flexsurfer** [comment]
> Related, there are a few other tokens to be added: COMP, AAVE, BAL, AKRO Is it easier to add these in one go or as a separate issue?

one go better we could test them all together in one go , but we need icons then @simonricoo @hesterbruikman

**Comment by flexsurfer** [comment]
UNI, 
address 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
name Uniswap
symbol UNI
decimals 18

COMP, 
address 0xc00e94cb662c3520282e6f5717214004a7f26888
name Compound
symbol COMP
decimals 18

AAVE, 
address
name
symbol
decimals 18

BAL, 
address 0xba100000625a3754423978a60c9317c58a424e3d
name Balancer
symbol BAL
decimals 18


AKRO
address 0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7
name Akropolis
symbol AKRO
decimals 18

**Comment by flexsurfer** [comment]
@hesterbruikman could you review the list please, also i didn't find AAVE token

**Comment by simonricoo** [comment]
@flexsurfer had problem with finding $AAVE too as for others here are the icons:
UNI (NEW - updated since last week)- https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=341%3A45
COMP - https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=348%3A36
BAL - https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=348%3A63
AKRO - https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=348%3A41

**Comment by hesterbruikman** [comment]
@j-zerah Is checking with Aave; it seems like their governance token is about to launch, but not available yet. Let's give it till noon tomorrow

**Comment by j-zerah** [comment]
@hesterbruikman  since AAVE tokens are not available yet (and they have a policy not to distribute the token), the Aave team will be issuing aUSDC instead https://www.coingecko.com/en/coins/aave-usdc

So sorry for the late reply but is it possible to add this token to the list as well.

**Comment by hesterbruikman** [comment]
When is the AMA planned for? As release cut has been made wondering if this is worth saving for a more low key fixes release soon after or if that'll be too late. I'm cognizant of the size of the community that a AMA in Status can draw

fyi @cammellos

**Comment by j-zerah** [comment]
AMA is next Thursday (Sept 30)
