### ISSUE TITLE
App crash when send phone number or capture a picture [iOS only]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1118]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Send /phone with valid number or tap on Capture in profile -> app crashes

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Wmc0M1dpUnpzUlE
- Open Status
- In Console tap on /phone. Type valid phone number and send it -> crash
- Edit Profile. Tap on Capture -> crash

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d26
* Operating System: iOS only. On Android is OK.
iOS 10.2.1

#### Logs

[StatusIm-2017-04-29-125909.crash.txt](https://github.com/status-im/status-react/files/966091/StatusIm-2017-04-29-125909.crash.txt)
[StatusIm-2017-04-29-125934.crash.txt](https://github.com/status-im/status-react/files/966090/StatusIm-2017-04-29-125934.crash.txt)

**Comment by rasom** [comment]
![screen shot 2017-05-01 at 09 21 04](https://cloud.githubusercontent.com/assets/2364994/25575018/03fe5ad0-2e5c-11e7-9c4a-a6a7ca2e7011.png)
