### ISSUE TITLE
Unable to login to github with status-browser on android

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11190]
# Bug Report

## Problem

I am not able to login to github on status-browser.

1) Open status-browser
2) Go to `github.com`
3) Login

#### Expected behavior

Login is successful

#### Actual behavior

"What? Your browser did something unexpected. Please contact us if the problem persist" is shown.

#### Notes

Some investigation was made and:
-  it seems like github returns 422.
- we believe this to be cookie related.
- works fine on IOS.
- a previous similar issue existed. https://github.com/status-im/status-react/pull/5726 https://github.com/status-im/react-native-webview-bridge/commit/6195e9c13565060823d3d565b6b442d6e88cd8a9
- it was suggested that the regression might have been introduced as we moved to the community webview.

This is necessary to login in gitcoin grants.

**Comment by cammellos** [comment]
@siphiuel could you please give us your insights on this? Thanks

**Comment by flexsurfer** [comment]
related issue https://github.com/status-im/status-react/issues/7402

**Comment by vitvly** [comment]
@cammellos @flexsurfer will look into it

**Comment by vitvly** [comment]
So the CookieSyncManager was missing, added it back and created a new react-native-webview tag https://github.com/status-im/react-native-webview/tree/v10.2.3_8/. Testing it.

**Comment by vitvly** [comment]
Doesn't work. Also tried using a non-deprecated `CookieManager.flush()` method (https://developer.android.com/reference/android/webkit/CookieSyncManager deprecation notice), but:
-  github.com login silently redicts to the login page again after clicking `Sign In`
- gitcoin.com shows `SSL error: Hostname mismatch` page

Continuing debug.

**Comment by vitvly** [comment]
Now i recall why the cookie sync section was removed in our community Webview fork. Docs for `CookieSyncManager` say that explicit sync is not necessary anymore as Webview automatically syncs cookies.

**Comment by vitvly** [comment]
I got a couple of emails with this content:
```
Are you trying to sign in? Based on your typical account activity, we did not recognize the location of the sign in.
As of this email, two-factor authentication has prevented the sign in attempt from being successful.
Your password was entered correctly, but an authentication code was not entered correctly.
You may view details about this sign in attempt by visiting https://github.com/settings/sessions/incomplete/836686124
```

So maybe the auth code form is prevented from appearing somehow.

**Comment by vitvly** [comment]
In adb logs there is this:
```
 [WARNING:cookie_manager.cc(366)] Strict Secure Cookie policy does not allow setting a secure cookie for http://github.com/
```
Why `http://github.com` I wonder, and not `https://`. **UPDATE**: fixed it via using `request.getUrl().getScheme()`, but still no luck.

Also saw this error:
```
09-21 18:43:04.808 28535 28535 I StatusNativeLogs: ###js Refused to execute inline script because it violates the following Content Security Policy directive: "script-src github.githubassets.com". Either the 'unsafe-inline' keyword, a hash ('sha256-Pfq569oo62l1RGN0HMpoQGiml1Zj5+jwyRdaDNQ3jeg='), or a nonce ('nonce-...') is required to enable inline execution.
09-21 18:43:04.808 28535 28535 I StatusNativeLogs:  -- From line 7 of https://github.com/login?return_to=%2Fsessions%2Ftwo-factor
```
But this is probably related to github.com returning `unsafe-inline` in its response headers, and means that we didn't inject the web3 provider, but this should not affect the login itself.

**Comment by flexsurfer** [comment]
@siphiuel any updates ?

**Comment by vitvly** [comment]
@flexsurfer still in debug, investigating why Github's 2-factor auth is not showing up on mobile.

**Comment by flexsurfer** [comment]
@siphiuel have you tried to comment `:on-message` and  `:on-navigation-state-change` the reason might be because we refresh the browser with new url

**Comment by vitvly** [comment]
@flexsurfer good idea, let me try that on top of cookie fixes

**Comment by vitvly** [comment]
Had no effect, trying out some other options.

**Comment by cammellos** [comment]
@churik I believe this has been fixed, is that correct?

**Comment by churik** [comment]
Not sure, let me recheck
