### ISSUE TITLE
Collapse sent message user A and make collapse message accessible

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11193]
# Problem

- As a user I want to see a message I sent as it appears to others, because that helps me judge how to best format messages 
- As a user that increases font size to make it more legible, I want messages to still contain sufficient content to read coherent sentences

A follow up to #11164 to also show messages sent by user A as collapsed in chat view of user A and make collapsed messages accessible:

- [ ] Apply collapse message to message coming from chat input
- [ ] Investigate and introduce alternative to fixed physical dimensions to determine collapse

## Acceptance Criteria
- When sending long message as user A, message appears as collapsed
- When increasing font size in OS, collapsed message still includes full sentence

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
