### ISSUE TITLE
Mentions are not resolved in messages with markdown

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11192]
# Bug Report
## Problem
Mentions in messages with markdown looks as `@chat-key`

#### Expected behavior
mentions in message

#### Actual behavior
![@roman 2020-09-21 11-07-46](https://user-images.githubusercontent.com/4557972/93749741-b842c200-fbfa-11ea-8fc6-7d74df91fd19.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Join any chat
* Send message with markdown and mention inside formatted text (i.e. `>hey @mention` )

### Additional Information

* Status version: nightly 21.09.20
* Operating System: Android, iOS

**Comment by rasom** [comment]
This is not a markdown issue, more likely we son't want to resolve `@name` as `@0xpk` in case if it is placed inside some formatted text.

**Comment by rasom** [comment]
Ok so, there are two ways to solve this issue:
1. do not replace mention with pubkey in case if that mention is inside some formatted text (telegram, discord)
2. parse `0xpk` as mentions even inside markdown (whatsap)

@hesterbruikman @errorists what do you think would be the best way to go?

**Comment by errorists** [comment]
I'm very much for option 1

**Comment by rasom** [comment]
@errorists then the next question: should we detect this during typing and do not suggest options and do not highlight mentions in input? That might be a bit trickier because mention might be inside some formatting tag and that tag might not be closed and... it adds a lot of complexity actually

**Comment by errorists** [comment]
I think ideally the moment you close a tag it strips of mentions from the input inside the tag, wdyt?

**Comment by rasom** [comment]
It is doable, might be complicated though

**Comment by churik** [comment]
Looks good to me. Tested on Android 10 and IOS 13 in 1-1, public chats with different markdown.
Aldo found that markdown with * and ~ is not applied to messages with mentions but I believe it is small issue which will be marked an `won't fix`, so I'll add it to https://github.com/status-im/status-react/issues/11271

**Comment by cammellos** [comment]
Closing this one then, thank you!
