### ISSUE TITLE
Message not sent tapping Send button while typing the message

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11205]
# Bug Report

## Problem

Often when you type a message and have quick enough fingers, - the message 'Send' button could be tapped really fast. Especially on low-level devices it's easy to tap Send button while the text you type is still in process of being rendered in the message input. In that case no message is sent which feels as not the best UX.
Could not reproduce on iOS, but might because iPhoneX too fast enough

It's visible that Send button is pressed but no message is sent. 

#### Expected behavior

Any time the 'Send' message button is active, - once it tapped it - message is sent.
#### Actual behavior
![1wd1wd1wd1wd](https://user-images.githubusercontent.com/8749671/93888794-21a4fc80-fcf1-11ea-9d88-232e5905cba0.gif)

### Reproduction

- Open Status and create new account
- Join any chat
- Start typing  a message and tap 'Send' message with a delay of 0.2-0.3sec between last char and 'Send' message being tapped 

### Additional Information
- Status version: develop 1.7, release 1.6.1
- Operating System: Android

**Comment by churik** [comment]
Have seen reports from developers about this - so worth to get look at

**Comment by churik** [comment]
@Serhy can you please recheck it? 
unable to reproduce it on  IPhone 12

**Comment by Serhy** [comment]
Can't reproduce with low-level Android devices with 1.13.0 release, - closing this issue.
