### ISSUE TITLE
Crash at attempt to scan QR code via Universal scanner after scanning via scanner in "Choose Recipient" view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11200]
# Bug Report

## Problem

If first scan the QR code using the QR scanner in the "Choose Recipient" view, and then navigate to the Home view, tap "+" button, open Universal scanner and scan the same QR-code again, the pop-up with the error appears, and after this, the app crashes. 

Reproduced time to time and on Android devices only (checked on Pixel 2 and Xiaomi mi note 9).

#### Actual behavior

![Screenshot 2020-09-21 at 17 55 26](https://user-images.githubusercontent.com/67952253/93790707-a29dbe80-fc33-11ea-8d4e-1b6f5ac714aa.png)

### Reproduction

- Open Choose Recipient screen
- Open QR scanner
- Scan some address, e.g. 0x835a70ee39a88aFFCf153642992326066afA7C8e
![Screenshot 2020-09-21 at 17 02 22](https://user-images.githubusercontent.com/67952253/93790817-bfd28d00-fc33-11ea-8e08-73117a9b652e.png)
- Navigate to Home view -> + -> Tap Universal scanner icon
- Scan the same QR

### Additional Information

- Status version:  ["Wallet favourites" PR](https://github.com/status-im/status-react/pull/11151) build [#11](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-11151/11/)
- Operating System: Android 10 (Google Pixel 2 and Xiaomi mi note 9)

#### Logs

[qr.log](https://github.com/status-im/status-react/files/5256612/qr.log)

**Comment by cammellos** [comment]
This looks like a bit of an edge case, or there's a legitimate flow when this might happen? Otherwise I would think this is a wontfix for now, but I leave the decision up to you.

**Comment by qoqobolo** [comment]
@cammellos agree with you.
@flexsurfer do you mind if I close this issue?

**Comment by flexsurfer** [comment]
i don't mind :)
