### ISSUE TITLE
Update design of 'Warning to users sending ERC20 directly to smart contract'

### ISSUE THREAD

**Issue by John-44** [status-im/status-react#11209]
# Feature Issue

Update the design of the warning users see when they try to use the Wallet Send function to send tokens directly to a smart contract.

### User Story

As a user without technical knowledge, I want to be warned when I am about to make a common mistake, such ash sending tokens directly to whatever I think is the right place.

### Description

![sending_funds_to_smart_contract_warning](https://user-images.githubusercontent.com/22846356/93913718-5f0f8700-fcfd-11ea-9015-a98efbe57666.png)

Title: Warning!

Description: This address is a smart contract, funds sent to this address may be lost. Use Status DApp Browser to interact with Dapps.

Actions: [Cancel] <-- primary       [Send funds to this address] <-- secondary

### Acceptance Criteria

Visual design of this warning is updated to match the attached mock

### Notes

This is a follow on to issue #11136

This should be tackled at the same time as issue #11210

**Comment by cammellos** [comment]
closing as new wallet designs will handle this
