### ISSUE TITLE
Whitelist directly sending tokens to smart contract wallets

### ISSUE THREAD

**Issue by John-44** [status-im/status-react#11210]
# Feature Issue

Issue #11136 introduced a warning for users to prevent funds being lost via the funds accidentally being sent to a smart contract, and issue #11209 updates the design of this warning.  However there are some smart contracts that a user can directly send funds to, the most common of these being smart contract wallets.  This issue introduces a whitelist of known smart contract wallets, so that users sending tokens to these addresses do not see the 'don't send funds to a smart contract' warning.

### User Story

As a user, I want to send funds directly from by Status wallet to a GnosisSafe, MultiSigWallet or other smart contract based walled, without seeing a warning every time. 

### Description

See user story above.  Known smart contracts that are safe for the user to directly send funds to should be whitelisted so user's sending funds to these wallets don't see the 'don't send funds to a smart contract' warning ( issue #11136 ).

### Acceptance Criteria

Users sending funds directly from their wallet to whitelisted smart contract wallets shouldn't see the 'don't send funds to a smart contract' warning.

Users sending funds to any smart contract address that is not on the whitelist should continue to see the 'don't send funds to a smart contract' warning.

### Notes

This is a follow on to issue #11136

This should be tackled at the same time as issue #11209

**Comment by 3esmit** [comment]
I defined an informational standard to this functionality, so other wallets can also implement this, if they wish so. https://github.com/ethereum/EIPs/pull/3023

I am also creating a powerful script that can connect to a full node and find all user wallets based on a combination of function signatures on the contract code, to then register on this standard in https://github.com/status-im/walletcontract-list

**Comment by cammellos** [comment]
Closing this as will be addressed by the new wallet designs
