### ISSUE TITLE
url localhost:8185/resources is opened in Console after upgrade from 0.9.6 version

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1121]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After upgrade from 0.9.6, if open Console then its input field contains "@browse http://localhost:8185/resources" and it opens "Web page not available" view
![console2](https://cloud.githubusercontent.com/assets/6584810/25555750/dc5aad94-2cee-11e7-8760-52cc89d929e3.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Cosnole chat is opened, Input field contains no text
#### Actual behavior
[comment]: # (Describe what actually happened.)
After upgrade from 0.9.6 on next run: Console input field contains "@browse http://localhost:8185/resources" and it opens "Web page not available" view
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video (run app after it was upgraded): https://drive.google.com/open?id=0Bz3t9zSg1wb7MnhESHBWMFQybG8
- Install 0.9.6.
- Upgrade (do not remove any data manually)
- Run Status and Open Console

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d26
* Operating System: Android 7.0 and iOS 10.2.1
### Logs
Run app after it was upgraded Logcat:
[20172904150605-logcat.txt](https://github.com/status-im/status-react/files/966144/20172904150605-logcat.txt)

**Comment by rasom** [comment]
fixed in https://github.com/status-im/status-react/commit/0c53936d61df77e87adeca828ace02ddccc3f631
