### ISSUE TITLE
Cursor moved in the middle of ENS name when typing message with mentioned user

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11216]
# Bug Report

## Problem

Mentions can be located by ENS/nickname/three-words name. 
In case user has ENS name set, - in the input field it's mention displays ENS name (disregard it was searched by nickname or three-words name or ENS). But when I continue typing message after selecting user from mention list, - cursor automatically moves in the middle of mention (to the point when I entered several chars before selecting user for mention).
Please see gif below for better understanding. 

Could not reproduced with nicknames/three-word names
Could not reproduce on iOS, but on Android 9 and Android 8 

#### Expected behavior

User continue typing from the place after ENS name in mention used

#### Actual behavior

Note here cursor shifted by itself to the point I stopped typing ENS name

![2020_09_23_15_24_03_trim](https://user-images.githubusercontent.com/8749671/94020307-73b25480-fdbb-11ea-9fbf-c266036f649c.gif)

### Reproduction

- Open Status and create new account
- Add new user by ENS name (e.g. 'statuse2e')
- Put cursor in the input field
- Type `@stat`
- Tap upon 'statuse2e' user from suggested mentions list
- Continue typing text

### Additional Information

- Status version: develop 1.7
- Operating System: Android9, Android8

**Comment by rasom** [comment]
@Serhy you were able to reliable reproduce this on different devices, right? I'm trying two android devices and on both it works as expected.

**Comment by Serhy** [comment]
@rasom Yes, it's reproducible 100% on Samsung S8 (Android 9). And on Galaxy J7 (Android 8.1)
I found the reason. It is because of `Predictive text` enabled setting for keyboard. 

For example on Galaxy S8 I have `Samsung Keyboard` set to use as on-screen keyboard and when I turn off `Smart typing` -> `Predictive text` setting then have no any issues like that.
Same for another Android device.

**Comment by rasom** [comment]
@Serhy well then it is rather Samsung keyboard's bug then ours. Not sure what can be done here.

**Comment by rasom** [comment]
might also be RN thing... checking

**Comment by rasom** [comment]
https://github.com/facebook/react-native/pull/12462 this one
