### ISSUE TITLE
Mention suggestions based on letter occuring in ENS, random, or nickname

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11212]
Follow up to #11206

# Problem
As a user I want to see suggestions if I start typing @ followed any letter that occurs in the random name, nickname or ENS name, because I might not recall the full name to trigger the mention suggestions list

## Future Steps
Enter @ followed by any letter that occurs in ENS, random or nickname you want to mention. Suggestion list should include all names that contain this character set

**Comment by rasom** [comment]
As far as I understood @errorists we actually wanted to check user tries to type some word from three-words-name. That doesn't mean an occurrence of substring but only when part of name starts with it.

**Comment by errorists** [comment]
I'll follow up with my understanding:

A username in Status can consist of more than one word, separated by spaces

currently only the first word in the username will be matched with your input query
instead, all of the words in the username should be matched

So a Ninja Mutant Turtle
would be matched with `@n` `@m` and `@t` and not only `@n`

**Comment by hesterbruikman** [comment]
Works for me. The behavior of checking for substring I described seems to be what happens on Discord. If it's more straightforward to check the first letter of each word in the random name that's fine IMO, as long as we're aligned that's the direction
