### ISSUE TITLE
web pages are not rendered on Android, html text is shown instead

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#11224]
# Bug Report

## Problem

when opening web pages in status browser they are not rendered 

![image](https://user-images.githubusercontent.com/11790366/94141751-81281700-fe6d-11ea-8371-a239906468ac.png)

#### Expected behavior

page is rendered 

/// Samsung Galaxy Note 10 (Android 10)

**Comment by hesterbruikman** [comment]
I could reproduce, but not with this specific example. Do you recall another url that wouldn't render?

EDIT Twitter works for me in 1.7 as well

**Comment by churik** [comment]
Tried on:
- Android 10 (Xiaomi  mi note 9)
- Android 10(Google Pixel 2)
- Android 9 (Samsung Galaxy S8)

Issue is not reproducible on these devices

**Comment by hesterbruikman** [comment]
Issue occurred for me. With Twitter. Samsung galaxy S10e, release build 1.7. _(Same build as Thursday when I could not reproduce)_

Could also reproduce on several 1.6 PR builds on 2nd attempt 

To reproduce:
- Enter Twitter in address bar
- Close view to tap on dap.ps
- Empty address bar with keyboard and enter Twitter.com again

OR

- enter Twitter.com in address bar and load 3x
(Will fail on 3rd)

Couldn't reproduce for dragonereum.io

![Screenshot_20200926-094942_Status](https://user-images.githubusercontent.com/35233054/94335786-324dbf00-ffde-11ea-93f0-0fa5266a8bbe.jpg)

**Comment by flexsurfer** [comment]
couldn't replicate on the PR build, but on nightly it's still can be replicated :(

**Comment by flexsurfer** [comment]
its kinda random, now it works on nightly

**Comment by churik** [comment]
Can't reproduce it on nightly 10/05/21, please reopen if still valid
