### ISSUE TITLE
Add support for #status-standups

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11220]
https://github.com/status-im/status/issues/3

As a user
I want to have a read-only channel #status-standups
So I can check what devs are working on

### Description

A new channel should be added to the list of channels, #status-announcements
This channel will be read-only for most but core-developers.

### Notes

This should form the basis of organisation channels https://github.com/status-im/specs/pull/151 and part of #11045 
So underneath the channel should be managed by the Status organisation and marked as invitation only.

### Designs

https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15316%3A0

**Comment by jakubgs** [comment]
What happened to the idea that I believe Andrey proposed to make channels like that using ENS names?

Something like `status.eth#standups`?

**Comment by cammellos** [comment]
We can use ENS names (currently the cost is just not feasible), but we are not limited to it, this is part of the communities/org channel effort  https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15316%3A0 as underneath it will use that mechanism.

We can still attach an ENS name to a particular community and list of channels, to make discovery easier. (i.e we are going to be working with IP addresses for now, until we add DNS on top :) )

**Comment by jakubgs** [comment]
I understand why ENS would be not feasible for just normal chatting. But why not for a broadcast channel?

If you are a company or someone with wider reach that wants a read-only announcements channel a few bucks isn't much.

**Comment by cammellos** [comment]
This will be de-scoped to 1.10 as discussed cc @Simona-Pop @j-zerah @hesterbruikman
