### ISSUE TITLE
Opening Stickers Menu and navigating on it is slow when there are many sticker packs installed

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11238]
# Bug Report

## Problem

As I test all sticker packs that are installed, I have them all installed in my account. When there is only a few installed this is not a problem. 

![image](https://user-images.githubusercontent.com/224810/94327844-10bfe980-ff84-11ea-97fb-f2c2a405b0bc.png)

#### Expected behavior

Sticker menu opening should not slow down the whole app.

#### Actual behavior

When there are many sticker packs installed, opening the sticker menu freezes the app for a few seconds.

#### Notes

It's slower when the menu opens with an animated sticker pack.

#### Acceptance Criteria

The app must not freeze.

### Reproduction

Install all sticker packs that you can and try choosing a sticker to send.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
