### ISSUE TITLE
status-react doesn't run with xcode 12

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#11239]
# Bug Report

## Problem

After Xcode update to 12 `status-react` doesn't build

#### Expected behavior

`status-react` builds

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- update to Xcode 12
- build status

**Comment by cammellos** [comment]
We had a discussion about this on the retro, my understanding is that there are quite a few libraries that we use that are not building on Xcode 12, so we have agreed that the best we can do for now is to wait until those get fixed upstream and then we can fix the issues on our side.
Please correct me if I am wrong cc @flexsurfer @Ferossgp

**Comment by vkjr** [comment]
Here is a [link](https://github.com/status-im/status-react/tree/upgrade_rn_0.63.2) to wip branch of migrating to RN 0.63.2.

**Comment by Ferossgp** [comment]
@vkjr Here some details why some libs aren't working https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
This affects also libs that we use like https://github.com/react-native-webview/react-native-webview/pull/1643

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/pull/11612
