### ISSUE TITLE
Show informative loading state UI depending on system state

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11251]
# Problem
Related to https://github.com/status-im/status-react/issues/11249#issuecomment-701951296

When migration is interrupted it can fail. Migration can take long when a lot of messages are stored. The UI does not inform the user that a migration is ongoing and shows a blank screen with spinner when `Save password` is enabled. Given the relative duration and lack of system state visibility, the user is left guessing and likely to kill the app (failing migration).

![Frame 1](https://user-images.githubusercontent.com/35233054/94783979-c8625a80-03cd-11eb-8c64-ca0ed19b3a86.png)

## User story
As a user I want to see what the app is doing and how long it will take so I can judge my actions (wait, switch to another app, kill app)

### Requirements
- Save version
- Compare to check for new version when starting app
- Inform user that the app is `updating` and/or `loading`, with a time approximation (reported that updating can take 'minutes')

## Notes
Other actions discussed in https://github.com/status-im/status-react/issues/11249#issuecomment-701952067

**Comment by errorists** [comment]
a text label under the spinner saying `Database migration in progress, this might take a while. Don't close the app`. I've seen such things previously in other apps like Sonos, I don't think it's a big deal to ask.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
