### ISSUE TITLE
ENS mention is shown with stateofus.eth domain for the mentioned user in chat view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11259]
# Bug Report

## Problem

If someone mentions a user with ENS name, the mention will be shown for the mentioned user with `stateofus.eth` domain (i.e. `dikhasi.stateofus.eth` instead of `@dikhasi`).

#### Expected behavior

ENS name is shown without `stateofus.eth` domain in mention. 

#### Actual behavior

![Screenshot 2020-10-02 at 11 41 09](https://user-images.githubusercontent.com/67952253/94909916-2b262580-04a4-11eb-9dba-43e43d122cd3.png)

### Reproduction

User 1:
- Set ENS name in User Profile settings
- Join public chat 

User 2:
- Join the same public chat
- Mention User 1

User 1:
- Check the received mention

### Additional Information

- Status version: Nightly 2/10
- Operating System: Android, iOS

cc @flexsurfer

**Comment by flexsurfer** [comment]
thanks :)

**Comment by churik** [comment]
still valid on nightly 10/05/21

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
.
