### ISSUE TITLE
Redundant ‘Notifications settings’  screen with toggle-buttons appears during Keycard onboarding on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11254]
# Bug Report

## Problem

During registration new keycard multiaccount or recovering existing one there is an unexpected Notifications settings with toggle-buttons screen appears between the PUK code/Seed phrase screen and the Private notifications (with buttons) screen. 

#### Actual behavior

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/67952253/94801939-146dc900-03e7-11eb-8ff8-c5965279b146.gif)

![Screenshot 2020-10-01 at 12 44 08](https://user-images.githubusercontent.com/67952253/94801805-dec8e000-03e6-11eb-881c-01cf0800e047.png)

### Reproduction

- Install Status
- Generate new key 
- Choose chat name 
- Chose keycard as key storage 
- Follow onboarding flow until the iOS notification settings screen appears

### Additional Information

- Status version: release 1.12, develop
- Operating System: Android

**Comment by guylouis** [comment]
@qoqobolo you mean android all along right ?

**Comment by Serhy** [comment]
Also adding another video to show blinking notification toggle-button screen. Sometimes e2e test with Keycard is stuck on this screen (there is no automated redirect to Notifications with buttons screen).

https://user-images.githubusercontent.com/8749671/113405169-10306180-93b2-11eb-8c9c-45690dfe931c.mp4
