### ISSUE TITLE
Wallet "Done" and "Add to favorites" only appears when the input box is focused

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11262]
# Bug Report

## Problem

When entering a value in the Recipient address, the buttons "Done" and "add to favorites" display.
![image](https://user-images.githubusercontent.com/224810/94927807-290a9980-0499-11eb-8413-655e299d6762.png)

But when  the input element losses the focus, the buttons disappear. 

![image](https://user-images.githubusercontent.com/224810/94927778-1e500480-0499-11eb-9b69-138ba6635bfe.png)

#### Expected behavior

"Done" and "Add to favorites" should be visible whenever a valid wallet is entered in the Recipient address

#### Actual behavior

"Done and "Add to favorites" are hidden but there is a valid address in the input of Recipient.

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Additional Information

- Status version: 1.7.0
- Operating System: Android

**Comment by flexsurfer** [comment]
as designed @errorists

**Comment by flexsurfer** [comment]
actually i reopen it, because i agree hiding done button makes things more dificult in code and in the UI

**Comment by 3esmit** [comment]
I got totally lost by the missing "Done" button...

**Comment by errorists** [comment]
❤️  thanks for the feedback, I agree, let's keep the toolbar on when the input is not empty
