### ISSUE TITLE
Recent Recipients show addresses of DApps

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11265]
# Bug Report

## Problem

I used Gitcoin and now at my recent Recipients addresses the Gitcoin address appears.

#### Expected behavior

Only show recent receipients that have codesize = 0 (not a contract address), because contracts usually need data to be sent. 

#### Actual behavior

[comment]: # (Describe what actually happened. Please include screenshots if possible.)

#### Notes

This is related to https://github.com/status-im/status-react/issues/11136

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
