### ISSUE TITLE
Using QRCode to scan a contract address does not rise a warning

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11264]
# Bug Report

## Problem

As @churik mentioned, the PR #11204 is only for "pasting in the field of receipient". 
I think is important to detect in any situation, for example, using qr code scanner to make this mistake is a possible scenario: 
1. a user coming from bitcoin (thinks that only transfer exists); 
2. reads about some protocol in his news feed; search more in the internet and ends up in the token smart contract of that project (usually the most visible smart contract);
3. user scans the contract address qr-code in a block-explorer, to use it as destination to send tokens, in an attempt to participate in the protocol;
4. rekt. 

#### Expected behavior

QR Code scanner warns of potential loss of funds if trying to interact with a contract address

#### Actual behavior

No warning

**Comment by churik** [comment]
Still relevant on nightly 27/07/2022

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
