### ISSUE TITLE
Forbidden users to send an ERC20 to the ERC20 token contract address itself

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11268]
# Feature Issue

Prevent one of the most common mistakes in ERC20 newbies, sending (burning) their tokens while trying to paste the ERC20 token in the wallet configuration.

### User Story

As a user, I don't want to burn my tokens, and I expect the wallet software to forbid me to do such a mistake.

### Description

This issue is part of the #11136 effort. 

While the warning should prevent most errors, there is no reason for accepting a user to send their tokens to the token contract address itself. 

Different from the general warning, this would be an error message which would not allow the user to proceed. 

### Acceptance Criteria

Impossible to send an ERC20 to the token contract itself.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
