### ISSUE TITLE
Add ability to remove account

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1126]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to remove existing account from the app so that all data of the account is deleted.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, it's possible to add new accounts but not possible to remove accounts. It would be nice to have such feature.

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/408
* https://dashboard.instabug.com/applications/status/beta/bugs/339

**Comment by Swader** [comment]
Still nothing.

**Comment by mandrigin** [comment]
@hesterbruikman @rachelhamlin it would be nice to get some visuals for that and then open it as a bounty.

**Comment by hesterbruikman** [comment]
@andmironov I recall you have [Delete my account] in the new Settings menu under [Privacy and Security]. 

Do you have any proposals that can work in the current UI? If not @mandrigin I suggest we hold off on this issue until the new Settings screen is implemented.

**Comment by guylouis** [comment]
will the user need to input his password to delete his account ?

**Comment by hesterbruikman** [comment]
Closing this issue, same as #10195
