### ISSUE TITLE
Wallet destination lookup accepts breakline

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11261]
# Bug Report

## Problem

The keyboard of "Escolher destinatário" accepts breakline. 
![image](https://user-images.githubusercontent.com/224810/94926727-96b5c600-0497-11eb-8352-d36ee9bba388.png)

#### Expected behavior

Breakline is not accepted as character, instead, if a valid wallet is entered, it executes the action of "Done"

#### Actual behavior

Breakline is accepted and messes up stateofus.eth lookup. 

#### Acceptance Criteria

Breakline is not accepted.

### Additional Information
- Status version: 1.7
- Operating System: Android

**Comment by 3esmit** [comment]
Was this fixed? @flexsurfer

**Comment by flexsurfer** [comment]
i think not yet

**Comment by shivekkhurana** [comment]
@3esmit The current app doesn't allow you to proceed if there is a space in the address (the next button is disabled, [video demo](https://imgur.com/a/bXM7rPt)).

Let me know if it needs more work, or close this issue if it's acceptable.

---
Edit 0: Closing the issue. Feel free to comment or re-open if I missed something.
Edit 1: Sorry, I interpreted it wrong. The issue still persists.
