### ISSUE TITLE
Inject infura token for release in CI

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#11270]
# Bug Report

## Problem

Currently develop token is used for release builds, and because its open anyone could use it in their project and exceed rate limits 

#### Expected behavior

Infura token isn't open

**Comment by jakubgs** [comment]
Here's the logic for picking which Infura token to use in Jenkins:
https://github.com/status-im/status-react-jenkins/blob/ef72482c99799206230c9665129a8cd585ce0624/vars/utils.groovy#L206-L216
And based on release build logs we pick the right one:
```
[Pipeline] echo
14:41:44  Using infura token: release
[Pipeline] withCredentials
14:41:44  Masking supported pattern matches of $INFURA_TOKEN or $KEYSTORE_PATH or $KEYSTORE_PASSWORD or $KEYSTORE_ALIAS or $KEYSTORE_KEY_PASSWORD
```
https://ci.status.im/job/status-react/job/combined/job/mobile-android/13128/consoleFull

And we have verified that `infura-release-token` is indeed the correct release token, so the issue should be in Clojure.

**Comment by cammellos** [comment]
We verified this is working
