### ISSUE TITLE
Include an image and copy in the iOS app switcher preview

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#11278]
### Description

Scope of this issue is to include an image and a text label, which tells why we obfuscate the preview and make it appear nicer than an empty rectangle of nothing, when viewed next to other app previews.

![Group 45](https://user-images.githubusercontent.com/4932774/95215085-e3c7ce00-07f0-11eb-999c-35d8269a35d4.jpg)

👉 [Design in Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15849%3A0)

### Acceptance Criteria

Image (we already use it for the Welcome Screen), and copy, are added to the app switcher preview.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
