### ISSUE TITLE
Tabs are not updated when switching between screens

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1127]
### Help to reproduce is needed
If you can reproduce it, please, make a comment with 
* Steps to reproduce (if available). 
* Any special conditions/data/settings (e.g. slow connection, first run, run app after it was not used for several days, any other special info)
* Have you tried same steps or check data later? Have you waited for any feedback from the app and for how long?
* Any extra comments you have
* Status version
* Device model and OS version 
* Logs (crash log or logcat)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When switching between Chats, Discover and Contacts then tabs in the bottom of the screen are not updated. For example, Chats can be active but tab highlights Discover tab.
![tab vs screen](https://cloud.githubusercontent.com/assets/6584810/25566628/1a555aba-2ddd-11e7-9d83-3ac5931ebb3e.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Active page and active tab in the bottom show the same item. E.g if Discover screen is shown then Discover tab is highlighted.
#### Actual behavior
[comment]: # (Describe what actually happened.)
Sometimes tab in the bottom is not updated and wrong element is highlighted. For example, when  Discover screen is shown then Chats tab is highlighted.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video (issue but not steps): https://drive.google.com/open?id=0Bz3t9zSg1wb7UC1nSGhmNEpmVFE
Need help to find exact steps to reproduce the issue

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6
* Operating System: Android OS Level 23, Device OnePlus A0001

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/372

**Comment by asemiankevich** [comment]
attaching TF: https://app.testfairy.com/projects/4803622-status/builds/6655902/sessions/16/?accessToken=CobZgJaTO9KSc8TD9yjgO7-5KGw (from 1.50)

STR: use `0.9.11` release candidate build https://i.diawi.com/Zuhm98 and switch fast between tabs right after login. The same can be reproduced when resuming the app from background

**Comment by annadanchenko** [comment]
outdated issue
