### ISSUE TITLE
Allow user to set profile picture from camera

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11281]
https://github.com/status-im/status/issues/4

As a user
I want to be able to take a picture from camera
So that it can be seen by other status users when chatting with them

Description
The user should be able to take a picture from camera (which format do we want to support), which will be selected as their profile picture.
This picture should be shown in chat/profile/all the relevant places.

https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A3116

Notes
There used to be some code already for this, and you might be able to reuse it

This can be worked together with #11280 #11282

**Comment by Samyoul** [comment]
Add 5 to the estimate to handle https://app.zenhub.com/workspaces/status-mobile-5729dbcd8c3f63656a8f6eaa/issues/status-im/status-react/11282
