### ISSUE TITLE
Allow user to crop profile picture

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11282]
As a user
I want to be able to crop a profile picture
So that it can be nicely shown to other users

Description
The user should be able to crop an image as per designs, which will be selected as their profile picture.
This picture should be shown in chat/profile/all the relevant places.

https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A3116

**Comment by Samyoul** [comment]
Ideally we want to only select the cropping coords (x, y and dimensions) and pass filename and coords to `status-go`, this ensures that the cropping will be handled consistently across all clients.

See [Discord#profile-pics chat](https://discordapp.com/channels/624205794384281629/748581152843104326/763354618523680778) we estimate that selecting the coords only is technically possible in mobile.
