### ISSUE TITLE
Endless loading on transaction history and ... balance on assets on nightly and PRs builds

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11299]
# Bug Report

## Problem
Currently, balance and transaction history is not fetched in nightly and PRs builds on mainnet.
However, on e2e builds on Ropsten network balance and transaction history are fetched.

#### Expected behavior
assets are fetched

#### Actual behavior
![IMAGE 2020-10-14 16:57:06](https://user-images.githubusercontent.com/4557972/96006933-4ac33380-0e3e-11eb-8e50-6a5de24a943a.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Restore account with funds 
- Check assets and transaction history

### Additional Information

- Status version: nightly 14/10/20
- Operating System: Android, iOS

#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/5379055/Status-debug-logs.zip)

**Comment by cammellos** [comment]
We are using the infura dev token for these builds, that's likely the issue, as they get rate limited. Maybe worth to restore the old tokens, but we'd be taking away quota from production effectively.

**Comment by cammellos** [comment]
This should now be fixed, we reverted the change back to the old token, PRs need to be rebuilt
