### ISSUE TITLE
Empty message bubbles on iOS in 1-1 chat after sending the app to the background from User Profile, and after blocking user in public chat.

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11309]
# Bug Report

## Problem

If start 1-1 chat, open User Profile, send the app to the background, reopen the app, and tap "back" to return to the chat view, some message bubbles in chat history will be empty. Text appears after scrolling.
Also the issue is reproduced for public chat after blocking some user.

#### Expected behavior

Text doesn't disappear from the bubbles after sending the app to the background and after blocking user.

#### Actual behavior

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/67952253/96462043-686d1000-1225-11eb-85cd-3d1c37854545.gif)

![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/67952253/96461839-293ebf00-1225-11eb-8c0b-217ec586a776.gif)

### Reproduction

_Steps:_

**For 1-1 chat**
User 1:

- Open 1-1 chat with User 2
- Send several messages

User 2:

- Open 1-1 chat
- Open User's 1 Profile
- Send the app to the background
- Reopen Status
- Tap back
- Scroll

**For public chat**

- Join public chat
- Tap some user name in chat history to open User Profile
- Block user
- Scroll

### Additional Information

- Status version: Nightly 19/10
- Operating System: iOS

**Comment by qoqobolo** [comment]
One more case.
It is reproduced ~10% of cases in Nightly and 100%  in [#11260](https://github.com/status-im/status-react/pull/11260).

_Steps:_

Device 1:
- Start **1-1 or group chat** with iOS Device
- Send several messages

Device 2 (iOS):
- Open chat with Device 1
- Tap `Back`
- Open chat with Device 1

As #11260 is almost ready for the merge, probably it would be important to fix this issue for 1.9. @cammellos Wdyt?

![ezgif com-gif-maker (16)](https://user-images.githubusercontent.com/67952253/97280934-2e12fc80-183d-11eb-97d5-e317dcf9bd24.gif)

**Comment by cammellos** [comment]
> As #11260 is almost ready for the merge, probably it would be important to fix this issue for 1.9. @cammellos Wdyt?

We should probably fix or at least make sure is not worse in #11260 before merging, we can add it to 1.9 scope, thank you

**Comment by flexsurfer** [comment]
fixed in https://github.com/status-im/status-react/pull/11260

**Comment by vkjr** [comment]
@qoqobolo, can be closed I believe.
