### ISSUE TITLE
Password request is not shown in Console for slow connection

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1130]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sometimes password request is not shown in Console. 
Can finally reproduce it on Android studio emulator by setting very slow connection: in Cellular section set Network type to GSM and Signal to Poor, install app and password request is not shown.

![password request](https://cloud.githubusercontent.com/assets/6584810/25577392/f153e9ea-2e65-11e7-8bab-b5c93862e5c1.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
password request is shown in Console
#### Actual behavior
[comment]: # (Describe what actually happened.)
password request is not shown in Console
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- in Android emulator in Cellular section set Network type to GSM and Signal to Poor
- install app 
- run it and check that password request is shown in Console

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6 (and lower)
[comment]: # (Android or iOS.)
* Operating System: Android for sure. iOS not know

**Comment by asemiankevich** [comment]
[18072017-logcat.txt](https://github.com/status-im/status-react/files/1155462/18072017-logcat.txt)

**Comment by annadanchenko** [comment]
TestFairy session: https://status-im.testfairy.com/projects/4803622-status/builds/6125337/sessions/3 and its log 
[status-09885gcad5e0c51514-3.logcat.txt](https://github.com/status-im/status-react/files/1155482/status-09885gcad5e0c51514-3.logcat.txt)

**Comment by annadanchenko** [comment]
Issue can't be reproduced with the described steps (to set Poor connection in emulator) but it exists in auto test runs, e.g in http://185.90.37.243:8080/job/end-to-end-test-automation/sauce-ondemand-report/jobReport?jobId=5024a26691cf4f9383eb2bd41fefdcdc

**Comment by x-goose-x** [comment]
```
10-03 23:38:48.895  3536  3659 D StatusModule: Starting Geth node in folder: /data/user/0/im.status.ethereum/ethereum/testnet
10-03 23:38:48.902  3536  3659 D StatusModule: UpstreamConfig is not null
10-03 23:38:48.902  3536  3659 D StatusModule: Attach to geth.log to instabug /data/user/0/im.status.ethereum/ethereum/testnet/geth.log
10-03 23:38:48.903  3536  3659 D StatusModule: Node config {"DevMode":false,"NetworkId":3,"DataDir":"\/data\/user\/0\/im.status.ethereum\/ethereum\/testnet_rpc","KeyStoreDir":"\/data\/user\/0\/im.status.ethereum\/keystore","NodeKeyFile":"","Name":"StatusIM","Version":"0.9.9-unstable","APIModules":"db,eth,net,web3,shh,personal,admin","HTTPHost":"localhost","RPCEnabled":false,"HTTPPort":8545,"WSHost":"localhost","WSPort":8546,"WSEnabled":false,"IPCFile":"geth.ipc","IPCEnabled":false,"TLSEnabled":false,"MaxPeers":25,"MaxPendingPeers":0,"LogFile":"geth.log","LogLevel":"DEBUG","LogToStderr":true,"UpstreamConfig":{"Enabled":true,"URL":"https:\/\/ropsten.infura.io\/z6GCTmjdP3FETEJmMBI4"},"BootClusterConfig":{"Enabled":true,"RootNumber":395,"RootHash":"673363514b866bbbaf1b94462203650e3b1a2d4fb498df33361458b465b61ca3","BootNodes":["enode:\/\/7ab298cedc4185a894d21d8a4615262ec6bdce66c9b6783878258e0d5b31013d30c9038932432f70e5b2b6a5cd323bf820554fcb22fbc7b45367889522e9c449@51.15.63.93:30303","enode:\/\/f59e8701f18c79c5cbc7618dc7bb928d44dc2f5405c7d693dad97da2d8585975942ec6fd36d3fe608bfdc7270a34a4dd00f38cfe96b2baa24f7cd0ac28d382a1@51.15.79.88:30303","enode:\/\/e2a3587b7b41acfc49eddea9229281905d252efba0baf565cf6276df17faf04801b7879eead757da8b5be13b05f25e775ab6d857ff264bc53a89c027a657dd10@51.15.45.114:30303","enode:\/\/fe991752c4ceab8b90608fbf16d89a5f7d6d1825647d4981569ebcece1b243b2000420a5db721e214231c7a6da3543fa821185c706cbd9b9be651494ec97f56a@51.15.67.119:30303","enode:\/\/482484b9198530ee2e00db89791823244ca41dcd372242e2e1297dd06f6d8dd357603960c5ad9cc8dc15fcdf0e4edd06b7ad7db590e67a0b54f798c26581ebd7@51.15.75.138:30303","enode:\/\/9e99e183b5c71d51deb16e6b42ac9c26c75cfc95fff9dfae828b871b348354cbecf196dff4dd43567b26c8241b2b979cb4ea9f8dae2d9aacf86649dafe19a39a@51.15.79.176:30303","enode:\/\/12d52c3796700fb5acff2c7d96df7bbb6d7109b67f3442ee3d99ac1c197016cddb4c3568bbeba05d39145c59c990cd64f76bc9b00d4b13f10095c49507dd4cf9@51.15.63.110:30303","enode:\/\/0f7c65277f916ff4379fe520b875082a56e587eb3ce1c1567d9ff94206bdb05ba167c52272f20f634cd1ebdec5d9dfeb393018bfde1595d8e64a717c8b46692f@51.15.54.150:30303","enode:\/\/e006f0b2dc98e757468b67173295519e9b6d5ff4842772acb18fd055c620727ab23766c95b8ee1008dea9e8ef61e83b1515ddb3fb56dbfb9dbf1f463552a7c9f@212.47.237.127:30303","enode:\/\/d40871fc3e11b2649700978e06acd68a24af54e603d4333faecb70926ca7df93baa0b7bf4e927fcad9a7c1c07f9b325b22f6d1730e728314d0e4e6523e5cebc2@51.15.132.235:30303","enode:\/\/ea37c9724762be7f668e15d3dc955562529ab4f01bd7951f0b3c1960b75ecba45e8c3bb3c8ebe6a7504d9a40dd99a562b13629cc8e5e12153451765f9a12a61d@163.172.189.205:30303","enode:\/\/88c2b24429a6f7683fbfd06874ae3f1e7c8b4a5ffb846e77c705ba02e2543789d66fc032b6606a8d8888eb6239a2abe5897ce83f78dcdcfcb027d6ea69aa6fe9@163.172.157.61:30303","enode:\/\/ce6854c2c77a8800fcc12600206c344b8053bb90ee3ba280e6c4f18f3141cdc5ee80bcc3bdb24cbc0e96dffd4b38d7b57546ed528c00af6cd604ab65c4d528f6@163.172.153.124:30303","enode:\/\/00ae60771d9815daba35766d463a82a7b360b3a80e35ab2e0daa25bdc6ca6213ff4c8348025e7e1a908a8f58411a364fe02a0fb3c2aa32008304f063d8aaf1a2@163.172.132.85:30303","enode:\/\/86ebc843aa51669e08e27400e435f957918e39dc540b021a2f3291ab776c88bbda3d97631639219b6e77e375ab7944222c47713bdeb3251b25779ce743a39d70@212.47.254.155:30303"]},"LightEthConfig":{"Enabled":true,"Genesis":"{\"config\":{\"chainId\":3,\"homesteadBlock\":0,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d\",\"eip155Block\":10,\"eip158Block\":10,\"metropolisBlock\":9223372036854775807,\"ethash\":{}},\"nonce\":\"0x42\",\"timestamp\":\"0x0\",\"extraData\":\"0x3535353535353535353535353535353535353535353535353535353535353535\",\"gasLimit\":\"0x1000000\",\"difficulty\":\"0x100000\",\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"coinbase\":\"0x0000000000000000000000000000000000000000\",\"alloc\":{\"0000000000000000000000000000000000000000\":{\"balance\":\"0x1\"},\"0000000000000000000000000000000000000001\":{\"balance\":\"0x1\"},\"0000000000000000000000000000000000000002\":{\"balance\":\"0x1\"},\"00000000
10-03 23:38:48.935  3536  3659 D StatusModule: StartNode result: {"error":""}
10-03 23:38:48.935  3536  3659 D StatusModule: Geth node started
10-03 23:38:49.070  3536  3586 D StatusService: Signal event: {"type":"node.started","event":{}}
```

- Here's an example of the geth node in status module starting with an error.
It fails silently and won't process any more requests, resulting in :received-message-when-commands-loaded
polling forever.

http://185.90.37.243:8080/job/end-to-end-test-automation/sauce-ondemand-report/jobReport?jobId=547f25f876c84d02bf74f5b6be2c5e09

- In this case the only logged re-frame messages are `:status-im.chat.events.commands/jail-command-data-response`
and `:received-message-when-commands-loaded`

It looks like there are a number of StrictModeWriteViolations indicating writes to disk that exceed 30 seconds.

I'm not entirely sure what's failing on write, but it seems to prevent some of the app threads from starting.

It looks like the one thing the violations have in common is an attempt to delete an SQLite database

```
10-03 23:46:56.957  1988  1988 D Error   : 	at android.database.sqlite.SQLiteDatabase.deleteDatabase(SQLiteDatabase.java:736)
```

**Comment by rasom** [comment]
> StartNode result: {"error":""}

this actually means that node was started without error
