### ISSUE TITLE
Endless progress bar when connecting when coming back from offline mode

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11305]
# Bug Report

## Problem
Endless progress bar and messages are not fetched when application is back from offline mode.
Issue is gone after relogin.

#### Expected behavior
"Connected" and no progress bar after coming back from offline, messages are fetched 

#### Actual behavior
"Connected" and endless progress bar (waited for ~4 mins)
![IMAGE 2020-10-19 14:09:15](https://user-images.githubusercontent.com/4557972/96449117-ac0b4e00-1214-11eb-8ad1-de816bea7d77.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Device 1: Open Status
- Device 1: Join any public chat 
- Device 1: Turn on airplane mode
- Device 2: Send to public chat several messages
- Device 1: Turn off airplane mode and wait

### Additional Information

- Status version: 1.8 RC 1
- Operating System: Android, iOS

#### Logs

[Status.log](https://github.com/status-im/status-react/files/5401651/Status.log)
[geth.log](https://github.com/status-im/status-react/files/5401654/geth.log)

**Comment by cammellos** [comment]
The issue seems to be that after going online we don't actually make a request

**Comment by cammellos** [comment]
The issue is that a request is not cleaned up when we come back from online/offline, and therefore it gets stuck
