### ISSUE TITLE
Sound is played on receiving Instabug message in Status even if sound is muted and phone in Do not disturb mode

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1131]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Phone is muted and in Do not disturb mode, however when message from Instabug is received in Status app then sound is played 
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7ODVoNHpvX1hoV3M
settings: 
![do not disturb mode](https://cloud.githubusercontent.com/assets/6584810/25578991/fdbcaace-2e73-11e7-805d-8153b737df96.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Sound is not played
#### Actual behavior
[comment]: # (Describe what actually happened.)
when message from Instabug is received in Status app then sound is played 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Shake phone and submit Instabug report
- Mute phone, set Do not disturb mode
- Keep Status app opened
- In Instabug send reply to the submitted report
- Check if message from Instabug is received and if sound is played 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6
* Operating System: Android 6.0.1, Samsung Galaxy S6. Didn't check on iOS yet

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/388

**Comment by jarradh** [comment]
seems more like an instabug thing rather anything we can do

**Comment by annadanchenko** [comment]
ok to close, no more Instabug
