### ISSUE TITLE
Open chat where user is mentioned on PNs

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11319]
# Feature Issue
Open chat where user is mentioned when opening chat from mention notification

### User Story
As a user I want to open the relevant chat where someone mentioned me when I tap on the mention notification, because I want to easily find and see the message and context in which someone mentioned me

### Description
When tapping on mention notification, app is opened, after log in, chat is opened where user was mentioned

iOS only, issue for local notifications on Android listed in #11213

Out of scope: opening the chat on the position of the mention

### Acceptance Criteria
Tap on mention notification to open app shows chat in which mention was created when multiaccount is unlocked

### Notes

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
