### ISSUE TITLE
Всякие баги

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#11332]
For those who are wondering: that's an issue where I'm trying to collect some complaints from one person from #status-russian pubchat. They don't have GH account nor are able to file issues in English. 

pubchat history issue https://github.com/status-im/status-react/issues/10362

**Comment by rasom** [comment]
> в браузере лидирующий пробел = ошибка

> пробел от переключения раскладки на моб клаве и его не очень видно

https://github.com/status-im/status-react/pull/11353

**Comment by rasom** [comment]
> гугл-маркет

> бывает ограничение по региону и по номеру версии андроида

> у меня вылезает не помню что, но по-разному для статуса и для вот этих
https://snatchapp.me/
> Это только пример - у меня были и с другими НЕ крупными такие же проблемы

> Вероятно это связано с тем, что я использую лоченный на америку смарт алкател через вай-фай
У него ГУЙ андроида только англ и испанский, а я захожу в гугл-маркет с московского IP - мож тут и перекашивает?

> Статус после ручной установки НЕ попадает в список установок моего гугл-маркета,
а эти - попадают, но при попытке установить апдейт - снова отказ

> У них ваще поддержка совсем "невосприимчивая", и мессенджер для них делали на аутсорсе, похоже

> Если что-то еще интересно - спрашивайте

**Comment by rasom** [comment]
> в списке участников у всех видны мои заметки для ников, если эти заметки я написал,
но нет самой фичи "заметка про меня самого"
М.б. это было не нужно ни для чего - но для групповухи это очень полезно, чтобы не вспоминать какой у меня собственный ник, если я кого-то еще не "озаметил" но он есть в групповухе

> Было еще что-то, но подтвердите, что это Ваша область, а не как с перестановкой #hello
тогда я вспомню и добавлю

**Comment by rasom** [comment]
> перенос контактов

> переносится только имя из 3 слов,
> а платный ник появляется только после моего появления в чате, где этот ник есть

> НЕ переносятся заметки - это ужасТно

> НЕ переносятся "все контакты" разом, а не "по одному" при переносе акка (или создании нового акка)
> Бэкап контактов - как и бэкап чатика - это же так полезно и удобно!

**Comment by rasom** [comment]
> постоянно и не только у меня одного виснет стикер-маркет

> в настройках есть ручной выбор мэйл-сервера - не влияет

> "надо что-то делать!.."
> Хотя я понимаю, что если сделать выбор (своего) сервера для стикеров, то это подорвет их продажу

**Comment by rasom** [comment]
> загаживание юзер-дата - НЕ проверено

> после посещения любого паблика, даже если его стереть внутри, или стереть из моего общего списка -
> размер юзер-дата в андроиде не меняется,
> но в процессе чтения пабликов явно увеличивается

> Почистить "память на диске" можно либо переносом акка, либо созданием нового

> Все это мне "показалось" не раз, но я не проверил все это "наверняка"

https://www.sqlite.org/lang_vacuum.html

**Comment by rasom** [comment]
> пометка "прочитано" и смежные темы

> после чтения или "пометить прочитано" невозможно вернуть "не прочитано", а это также удобно как и любая закладка

> смежная тема "удобства":
> я использую стирание внутри паблика, чтобы одним взглядом на общий список "нет сообщений" видеть, что я все прочитал внимательно, а не "мельком и оставил на потом", а пометка "не прочитано" уже снялась
>НО
> если стереть внутри, или стереть из моего общего списка,
> то архив предыд. дня и ранее становится недоступен,
> хотя юзер-дата НЕ уменьшается

> я решаю это одновременным использованием нескольких акков, но это явное извращение для таких как я

> Очевидно(?), что надо сделать как-то более по-человечески -
> расписать еще подробнее или это не Ваша область?

**Comment by rasom** [comment]
> fetch last 24 hours

> в меню чатов есть такая фича, но я не понимаю смысла и не вижу ее действия:
> при первом заходе всегда молча показывает эти самые 24 часа,
> при не первом заходе - тоже вроде бы так

> либо это "отрыжка" как двойной chitchat
> либо объясните  смысл, пжлста

> Сюда же и про "удобство":
> после первого захода кликать 30 раз, чтобы загрузить весь доступный архив - это издевательство и\или идиотия
> Очевидно(?), что нужна кнопка "загрузить все" или даже несколько кнопок - 5 дней, 10, 20 и 30, например
> Или возможность ввести кол-во дней загрузки, хотя на мобильной клаве это опять не очень удобно

**Comment by rasom** [comment]
> браузер + ошибка загрузки приложения с сайта

> не было такого у меня никогда на версии 1.6 и 1.5, а мож и раньше - не помню уже
> Появилось на 1.7 после выхода 1.8 и теперь проверил снова на уже установленной 1.8

> исходные условия

> у меня есть 4 тестовых смарта
> 2 шт андроид-8 одинаковых буквально
> 2 шт андроид-7 одинаковых буквально

> не установлено никаких глобальных софтовых навесок вроде ВПН и\или перехвата клавы
> установлен примерно одинаковый набор "некоторых обычных" приложений из маркета
> рута нет

> сегодня на всех 4 установлена версия Статуса 1.8
> при попытке загрузки
> 1 шт андроид-7 = загрузка через встроенный браузер запускается норм как и раньше
> 3 шт остальных = ошибка, затем завис или даже крэш Статуса

> говенное фото ошибки - не скриншот - в личке Статуса
> Само сообщение - его начало - руками перепишу и отправлю почтой дополнительно попозже

> При использовании стороннего (примитивного) браузера загрузка во всех 3 случаях = ок

> Я не могу сообразить, кто м.б. виноват: браузер Статуса или что-то на сайте Статуса

> Если что-то еще вспомню сам, или Вы уточните и переспросите - напишу доп.

![IMG_9537](https://user-images.githubusercontent.com/2364994/97081626-45b76e80-160c-11eb-94e9-c7105de805b8.JPG)

**Comment by rasom** [comment]
> QR-code + camera

> моя фотка в личке Статуса сделана на андроид-7 - камера и там говно
> НО
> QR-code норм фокусируется и картинка квадратная = контакты передаются норм
> НО
> андроид-8 примерно такой же дешевый залоченный алкател, но явно отличающийся по железу - он собран на MTK и дизайн явно другой, чем а у андр-7, который сделан на Qualcomm и дизайн тут заметно богаче, даже качество экрана явно лучше, но цена обоих была одинакова для залочки - каждый по $25 в Walmart
QR-code
НЕ фокусируется == а потому и НЕ работает
картинка вытянута == явно НЕ квадратная
ХОТЯ
при использовании камеры == вызове ее НЕ из Статуса
картинка НЕ вытянута,
а фокусировку сравнивать тяжело, потому что камера все-таки говно

> имхо НЕсварщика:
QR-code + camera "для андроид-8" и именно в Статусе = что-то "явно не так" или "нехорошо"

> Есть еще и другие мелкие различия в Статусе в версии "для андроид-8" и "для андроид-7"
но они на уровне совсем мелких придирок и артефактов отрисовки -
имхо это не ст0ит разговора, но могу и про это рассказать

> Все это наблюдается с самого начала - с версии 1.5 или даже 1.4 - не помню уже с чего я "начинал" \ когда подключился к изучению Статуса

**Comment by rasom** [comment]
> некоторые пункты меню надо назвать длиннее
> некоторые описания под пунктами меню в самом приложении надо уточнить \ расширить

> я веду речь про пункты меню

> а) пабликов

> 1) Mark all read
> 2) Clear history
> 3) Fetch last 24 hours
> 4) Delete chat

> в) в настройках

> 1) Mobile data
> 2) Use history nodes

**Comment by rasom** [comment]
> при обмене сообщениями перенос строк реализован так, чтобы не резать слова на части,
но сегодня стабильно режется смайлик - символы ":("

**Comment by rasom** [comment]
> глюки цитирования

> после стирания (или уничтожения паблика и повторного захода в него)
все новые сообщения с цитатами на предыд. "стертые" сообщения показываются без даже намека на отвалившееся цитирование
НО
нередко и сами некоторые сообщения не прогружаются - пропускаются
Т.е. цитаты есть, а самих сообщений - нет
Конкретно сейчас в #status-russian
есть несколько таких случаев,
но это было около 15 октября, поэтому через 20 дней уже не увидеть повторяемость эффекта,
которую я только что проверил на разных акках и в разные дни(!) загрузки этого паблика.

> Поэтому, если кому-то из команды Статуса интересно наблюдать такое - надо поторопиться

**Comment by churik** [comment]
Closed as stale issue, reopen if still relevant
