### ISSUE TITLE
Rename mailserver to history node

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11337]
# Problem
Release 1.7 introduced the name `history node` in a new feature to disable connecting to a history node (a.k.a. mailserver). The name needs to be updated in several places:

* [ ] Settings > Sync settings
* [ ] Glossary
* [ ] FAQ (https://status.im/faq/)
* [ ] Security content (https://status.im/security/)
* [x] Set up node docs

## Implementation
Update Mailserver to History node

## Acceptance Criteria
Mailserver referred to as History node in all user facing documentation

**Comment by hesterbruikman** [comment]
@shivekkhurana noticed a bunch more places that I didn't list above. You may have found these already when starting this issue, in which case you can ignore:) These are the keys for content that still refers to `mailserver`

- mailserver-error-content
- mailserver-error-title 
- mailserver-pick-another 
- mailserver-request-error-content
- mailserver-request-error-title
- add-mailserver 
- delete-mailserver 
- mailserver-address
- delete-mailserver-title
- mailserver-reconnect
- delete-mailserver-are-you-sure
- mailserver-details
- mailserver-connection-error
- offline-messaging

@jinhojang6 these changes are an incoming translation request. One word, but quite a few keys using it. Next to the above I noticed two keys that currently use `History nodes` in english, but their translations still seem to use `mailserver`

- offline-messaging-settings
- mailserver-title

**Comment by jinhojang6** [comment]
I initialized or fixed the translation for the 2 keys @hesterbruikman . Will follow this up

**Comment by shivekkhurana** [comment]
@hesterbruikman Thanks for creating that list. It'll make my job way easy 💨💨💨

**Comment by shivekkhurana** [comment]
https://github.com/status-im/status-react/pull/11423 changes the app aspect of things (settings to sync settings and mailserver label to history nodes). The error messages can probably be handled in the Lokalise app. 

Update: en.json needs to be handled in this PR and other languages can be handled in Localise app.

**Comment by shivekkhurana** [comment]
Unassigned myself because the remaining changes are at the website level.

**Comment by cammellos** [comment]
Closing this as it's probably best to track in a separate repo if all the changes are on the website, cc @hesterbruikman
