### ISSUE TITLE
[Spike] Use Pokt network as an infura replacement

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11335]
As a developer
I want to use Pokt instead of Infura 
As I want to use decentralized technologies

### Description

Assess the viability of using https://www.pokt.network/ as an infura replacement

We should start from using their gateway, and making sure that the app works as expected, later, we can move to https://github.com/status-im/status-react/issues/13591

**Comment by cammellos** [comment]
I have created an application on https://dashboard.pokt.network/ 
Selected the ethereum mainnet and mainnet archival, testing their gateway as it should be just a swapping of the URLs.
I have plugged in the archival URL in the application, and basic functionalities seems to be working, but I am currently not able to retrieve transaction history.

It fails with:

```
t=2020-10-27T06:32:26+0000 lvl=eror msg="failed to get next batch" error="Post \"https://eth-archival.gateway.pokt.network/v1/[redacted]\": context deadline exceeded"
```

Investigating

**Comment by guylouis** [comment]
closing this because it's not the short term plan anymore

**Comment by rasom** [comment]
Tested, there is no support for archival requests on goerli network yet.
