### ISSUE TITLE
Add hint that wallet balance is not updated when app is on cellular network

### ISSUE THREAD

**Issue by tom4399** [status-im/status-react#11344]
# Bug Report

## Problem
 My balance isn’t showing https://blockscout.com/poa/xdai/address/0x2A52Fc9657E495856FbF04dA704dE8f40F6De929/transactions 
![20E528B3-1B9E-45AD-8F20-FB9BE7ACCD98](https://user-images.githubusercontent.com/73671467/97636357-e9e84d80-1a30-11eb-9500-8a0daf63233e.png)

- Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
...
```

**Comment by danimesq** [comment]
@Ferossgp @churik 

I'm also using xDAI and its me who bought they to switch to it and also its me who sent the token (DANIMESQ).

For me, the balances shows correctly and I can also tap "Scan tokens" to quickly update it.

If there is some workaround for Tom at sorting it out, this issue shouldn't be closed but investigated to fix what is causing the tokens to show "..." instead of loading.

**Comment by danimesq** [comment]
Additionally CC'ing @0kok0 @johnlea-quiup and @hesterbruikman, which were already supporting a issue I've opened before.

**Comment by danimesq** [comment]
Also worth noting that, while OP reports to be using iOS, I'm using Android.
![Screenshot_20201029-191513](https://user-images.githubusercontent.com/6765277/97638410-3e80ce00-1a1b-11eb-9680-d15114783931.png)

**Comment by churik** [comment]
@tom4399 thank you for reporting!
I see, that you are using 4G connection.
In that case it is expected - option to sync token balance is disabled by default to reduce traffic usage on cellular network.
You can always turn it on in Profile > Sync settings > Mobile Data.

**Comment by churik** [comment]
@hesterbruikman @cammellos it is not the first report about balance, so I suppose it is not obvious from user POV. may be we need smth in the wallet to show users that to see his balance when on the mobile network he needs to change the setting?

**Comment by tom4399** [comment]
I got it to work :) Ty

**Comment by churik** [comment]
@errorists WDYT about it?

**Comment by danimesq** [comment]
@tom4399

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
