### ISSUE TITLE
Support for POAP NFT

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11357]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story
As an event attendee
I want to claim my POAP NFT through https://app.poap.xyz/claim/{my-event} (or Keycard redeem)
so that I can thereafter keep it in my Status wallet

As an event attendee
I want to view and show a POAP NFT in Status wallet
so that I can use it show my ticket at a venue

As an event attendee
I want to view and show the POAP NFT while I'm offline
So I can view the NFT I claimed ahead of entering the venue without requiring a local mobile data subscription or wifi access at the event

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: As community communication tool we aim to position ourselves as communication and engagement layer for events, enabling things like proofs of attendance to happen in Status vs other wallets thus providing a unified experience becomes a necessity. 

POAP NFT's are planned to be used to provide attendees with Proof of Attendance during Devcon. 
- Users must be able to view and show this NFT when entering the venue and during potential other irl activities.
- Users must be able to claim the POAP NFT using https://app.poap.xyz/claim/{my-event} in Status browser
     - seems to cost ETH, needs to be confirmed
- Users should be able to view and show the NFT while they are offline (should not require opening OpenSea)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- Open wallet
- Open Collectibles
- Select POAP NFT
- View associated content (could be a QR code)

### Additional Information
* Operating System: Android|iOS
_Desktop - nice to have_

**Comment by Simona-Pop** [comment]
Re cost - POAP has typically transferred the NFTs directly. In the scenario where the POAP is the ticket for the event, again the NFT would be sent to the address the payment was made through (if made in crypto) or a section with wallet address in the event sign up form should enable the sharing of the POAP badges.

**Comment by hesterbruikman** [comment]
If you're in touch with the team @Simona-Pop, I think one thing that would help is if they have a test event and badge on a testnet. With that we can check any current support of the dapp and NFT

**Comment by Simona-Pop** [comment]
I’ll get in touch with Patricio and see! Will link back in here

**Comment by Simona-Pop** [comment]
Ok: There are POAP implementations on Sokol (xdai testnet) and ropsten.

Ropsten: 0xd237716b056d5bf44181c471a7c633583b552d78

Xdai, Sokol, mainnet: 0x22C1f6050E56d2876009903609a2cC3fEf83B415 (They use the same address in all 3)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
