### ISSUE TITLE
App crashes when tapping 'download report' in Snapshot dapp

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11366]
# Bug Report

## Problem

When using Snapshot dapp. Viewing a [proposal](https://snapshot.page/#/status/proposal/QmUyxGsc6BwzHzGDyKWXhdX29t6F9obv4AM1RwvMhqrVxS), tapping `Download report` gives an error and causes Status Mobile app to crash

#### Expected behavior

[comment]: # (Describe what you expected to happen. Please include designs if possible.)
File is downloaded to default folder on device
File is a csv file named: snapshot-report-QmUyxGsc6BwzHzGDyKWXhdX29t6F9obv4AM1RwvMhqrVxS

#### Actual behavior

[comment]: # (Describe what actually happened. Please include screenshots if possible.)
##### Android
Error, followed by app crash when tapping `Exit`
[Logs](https://drive.google.com/file/d/1IVKU1_s5Ug0ofelzeWCQ1fOufX-2U4TK/view?usp=sharing)
![Screenshot_20201104-093804_Status](https://user-images.githubusercontent.com/35233054/98088837-41981600-1e82-11eb-8589-4799bf20470a.jpg)

##### iOS
No response to Download report

#### Notes
These might be separate issues:
- Resolve error and crash when request is unknown
- Allow downloading (csv) files (not sure if other filetypes are currently supported)

#### Acceptance Criteria

- App does not crash
- If needed issue is created for a feature to download files through Browser

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open browser
- Open [proposal on Snapshot](https://snapshot.page/#/status/proposal/QmUyxGsc6BwzHzGDyKWXhdX29t6F9obv4AM1RwvMhqrVxS)
- Tap `Download report`

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.8.0 (0201103025931 (Android) 1.8 release (iOS)

**Comment by churik** [comment]
Now I see error "SSL certificate is not valid"

![image](https://user-images.githubusercontent.com/4557972/181244185-58d0e82e-f0e5-4ac4-9524-4027d4d4c80c.png)
Closing as stale, reopen if still relevant
