### ISSUE TITLE
Status field in profile of another contact can't be scrolled 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1136]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If view profile of another contact then Status field with more than 3 lines can't be scrolled down. Only on Android.
![status profile](https://cloud.githubusercontent.com/assets/6584810/25593989/3b0f7744-2ebf-11e7-8cf3-0e71aff1b0e4.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Status field in profile can be scrolled
#### Actual behavior
[comment]: # (Describe what actually happened.)
Status field in profile can't be scrolled
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7UG1DUXQ2VnB2VlU
You need to have 1-1 chat with a contact who has very long status (max length allowed)
- Open Status
- Open 1-1 chat 
- Tap on profile picture in top right corner
- Tap on Status field to scroll it
- Try to scroll to the last line

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6 and later (0.9.7d34)
* Operating System: Android only

**Comment by flexsurfer** [comment]
this is looks like UX problem, because we have status scroll inside screen scroll and it's difficult to scroll inside scroll

**Comment by annadanchenko** [comment]
there is no status field in profile anymore
