### ISSUE TITLE
Handle unpaired cards

### ISSUE THREAD

**Issue by bitgamma** [status-im/status-react#11387]
# Bug Report

## Problem

You have a Keycard multiaccount. Using another tool, you remove the pairing between the card and Status. When trying to perform any operation with the card you are not prompted to pair the card again and the operation fails. The only workaround is to reinstall the app.

#### Expected behavior

If the pairing has been broken for whatever reason, prompt the user to restore the pairing

#### Actual behavior

The pairing remains broken with no way to recover

### Reproduction

- Open Status
- Create an account with Keycard
- Log out in Status
- Pair the card with Keycard Connect
- Tap Unpair Others in Keycard Connect
- Try to login in Status

**Comment by guylouis** [comment]
To be tested again when testing for keycard resumes. I thought this was managed. 
Doesn't it depend on which operation the user engages with the unpaired card (which action is not mentioned above) ?
