### ISSUE TITLE
Migrate multiaccount: keycard to regular

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11390]
As a user,  I want to migrate my Keycard account to a regular account  so that I can use my account without requiring my Keycard. 

**Notes:**
- I still hold my keycard and knows my PIN
- My keycard will be cleared of any of my keys (remove the seed from the card) because I want to be sure that the device does not hold anymore any information that could lead to control of my keys. 
- Keys will be moved to my phone, and my data base will be kept on the phone. 

**Design** 
It is **flow number 4** here https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A11552
 
**Other related issues:**
- if I want to clear my keycard & remove the corresponding multi account from the phone that's issue #9229 (flow 6 in figma)
- if I have lost my keycard and want to get back control over my assets with status, (issue #11391  and flow 5 in figma)

cc @hesterbruikman

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
Added `recheck` label for easy finding that one in case of need.
