### ISSUE TITLE
Enable "show transaction data" button on the generic request screen 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11392]
Related to request screen  implementation (see https://github.com/status-im/status-react/issues/9275 )

For the generic request screen (the signed data does not include the fields that trigger either the payment screen or the redeem screen, see ) we had designed that a button with 'show transaction data' would be present, and would pop up the transaction data as here: 
![image](https://user-images.githubusercontent.com/11461437/98397790-2b47b100-2060-11eb-86ed-603c82a7995d.png)
![image](https://user-images.githubusercontent.com/11461437/98397806-33075580-2060-11eb-8d2a-f6cc3e59ce71.png)

This button is not present in current release. 

We should renable this button and screen with signed datas. 

cc @gravityblast @siphiuel @bitgamma

**Comment by gravityblast** [comment]
closed with #11447
