### ISSUE TITLE
Error at attempt to sign typed message in simpledapp.eth

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11398]
# Bug Report

## Problem
Errorat attempt to sign typed message in simpledapp.eth ( "Cannot read property 'replace' of null"  in case of keycard and "invalid character x" in case of ordinary multiaccount)
Likely consequence of https://github.com/status-im/status-react/pull/11369

#### Expected behavior
can sign typed message 

#### Actual behavior
If signed with password:
![Sauce Labs | Test Details: 2020-11-09 10-09-27](https://user-images.githubusercontent.com/4557972/98521688-0d529a00-2274-11eb-9fd6-3644d0153aca.png)
If signed with keycard:
![image](https://user-images.githubusercontent.com/4557972/98520486-66213300-2272-11eb-833c-c126ad61467d.png)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create multiaccount with keycard and switch to Ropsten
- Open simpledapp.eth -> Transactions
- Click on "Sign typed message" and try to sign transaction

### Additional Information

- Status version: nightly 09-11-2020
- Operating System: Android

#### Logs

Logs and video: https://app.saucelabs.com/tests/249c2127057a40b5bd4fb9071ce7357e?auth=c4b9cf8c38a9a7c3b13f0eec51420251#102

**Comment by churik** [comment]
cc @flexsurfer

**Comment by flexsurfer** [comment]
i would say this one https://github.com/status-im/status-react/pull/11376 @bitgamma
