### ISSUE TITLE
Inapp Keycard upsell MVP

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11395]
We want to promote inside status app, the possibility to upgrade the account security by using a keycard. This includes:

* explain to the user benefits 
* call to action to get a keycard

This encounters three things:
**i/** a banner inside the app that promotes to the user to increase his security with a keycard 
**ii/** a landing page explaining with more details what his keycard and how it helps the user with his security and calls to action to purchase one 
**iii/** user is then on a shopping site and we must be able to track conversions 

**For an MVP we want to do the following:**
**i/** have a banner _on the login screen_. Proposed design here: 
banners : 
![image](https://user-images.githubusercontent.com/11461437/100632265-ecd6a680-332c-11eb-8864-df1ce84ee1b2.png)

in the logins screen here: 
![image](https://user-images.githubusercontent.com/11461437/100632213-dd575d80-332c-11eb-9035-971a183ae124.png)

**ii/** landing page can be a duplicate of https://status.im/keycard-integration
**iii/** shopify site remains as is, and tracking of conversions is done from shopify 

**To do**

* [x] [X ] create the landing page (guylouis + aleks) and provide URL
update (09/12): the URL is https://get-keycard.status.im/
* [x]  implement the banner in the app

**Comment by guylouis** [comment]
The URL where the banner should lead to is 
https://get-keycard.status.im/

cc @AK87ST

**Comment by guylouis** [comment]
@cammellos 
we've got the website ready 
anything else needed top move this to the next column ?

**Comment by cammellos** [comment]
No, looks good to me, I can move it to Next

**Comment by guylouis** [comment]
note: 
it would make sense to have this banner only when the login screen is the login screen of a non-keycard account :)

**Comment by flexsurfer** [comment]
@guylouis is there a figma link ?

**Comment by guylouis** [comment]
**Problem**
after some discussions, it was considered that the banner defined above is too intrusive and pushy for our users 
- it's a bit pro-eminent 
- it's shown each time a user signs in his non-keycard account 

**Solution:** 
- change the banner to this one which is smaller and can be clicked out 
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8469%3A28991
- the banner should be shown only on non-keycard accounts 
- if the user clicks it out once, then it will never be shown again 
- change text (less sell-sy, and more in line with our ethos) from "Get a Keycard. Your portable and easy to use hardware wallet" to "Get a Keycard. Enhanced security and convenience"
