### ISSUE TITLE
Resolve sticker market address from ENS name

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11419]
# Problem
The Sticker market contract will be updated. This currently requires an update in status-react to call a new contract address. Resolving the address from a static ENS name, makes it easier to adapt the contract when needed.

## Implementation
- Replace [current contract address](https://github.com/status-im/status-react/blob/fe5b5ab4bc1cf4baf554406b2885c61424becdaf/src/status_im/ethereum/contracts.cljs#L13) with ENS name, similar to `:status/acquisition`
- ENS name tbd (likely stickers.status.eth). Please verify ENS name with @3esmit before making changes.

## Acceptance Criteria
Includes a reasonable fallback if we can't get an address for any reason
@flexsurfer do you know what happens when we can't get the address for Sticker market? Can we also not get the content from IPFS or is it the purchasing that will not work? Trying the understand what fall back is required

**Comment by flexsurfer** [comment]
purchasing won't work, also it will be impossible to check for recovered accounts which stickers have been purchased earlier

**Comment by hesterbruikman** [comment]
> purchasing won't work, also it will be impossible to check for recovered accounts which stickers have been purchased earlier

Do you know if stickermarket already has a state of purchase and install buttons being inactive?

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
