### ISSUE TITLE
App is crashed on account creation after navigating to access key and back

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11411]
# Bug Report

## Problem
App is crashing if creating account after navigating to access key after.
Reproducible on 1.8.

#### Expected behavior
no crash

#### Actual behavior
crash

![IMAGE 2020-11-09 11:05:20](https://user-images.githubusercontent.com/4557972/98527544-7558ae80-227b-11eb-8393-039be81d42cc.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
*Scenario 1:*
- Open Status
- Get Started > Access existing keys > Enter seed phrase -> Back
- Tap on Generate keys (button is not responding after 1 tap, so tap 2 times)
- Next > Create password > Next

*Scenario 2 (reproducible only for Android):*
- open app > Generate keys > Cancel
- Generate keys > Cancel
- Access existing key > Back > Generate keys > try to create new account with password

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 1.8
- Operating System: iOS, Android
#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/5509661/Status-debug-logs.zip)

**Comment by shivekkhurana** [comment]
@churik I'm unable to reproduce on iOs (tried both scenarios).
[Scenario 2 Video](https://www.dropbox.com/s/hzf2zmsoiknzchc/RPReplay_Final1605088304.MP4?dl=0)

**Comment by churik** [comment]
@shivekkhurana 
it is reproducible when you don't have accounts, so after fresh installation.
Scenario 2 is reproducible only for Android though, you are right, thank you for trying.
