### ISSUE TITLE
IPNS names are not resolved

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11429]
# Bug Report

## Problem

`simpledapp.eth` and `uniswap.eth` are not resolving (on 1.8 and on current release - blank screen).

It causes failure of 12% of e2e on current nightly. 
1 time resolving of  `simpledapp.eth` is failed 14/11/2020.

#### Expected behavior
"ALLOW" button is shown

#### Actual behavior
blank screen

### Reproduction

- Open Status
- Open `uniswap.eth`

### Additional Information

- Status version: 1.8, nightly 14/11/2020
- Operating System: Android, iOS

### Logs 
```
 :json-rpc/error eth_call :error {:code -32000, :message "execution reverted"} :params [{:to "0x42d63ae25990889e35f215bc95884039ba354115", :data "0x2dff69414c60899c02837bf7df89811740bc54bc6bc953e3ad7e3fb8a990f94e039fca11"} "latest"]
```

**Comment by churik** [comment]
from discord:

> `content(bytes32) [0x4c60899c02837bf7df89811740bc54bc6bc953e3ad7e3fb8a990f94e039fca11]`
params which cause error

**Comment by churik** [comment]
cc @3esmit @cammellos @flexsurfer

**Comment by flexsurfer** [comment]
at some point infura started to return execution reverted error instead of "0x" result, our code expects "0x" result
