### ISSUE TITLE
Migrate account to a regular keycard from logged out "Manage keys and storage"

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11431]
Part of: https://github.com/status-im/status-react/issues/11237

As a user 
I want to migrate my regular account to keycard when I am logged out
As I might have forgotten my password and can't access it

### Description

We want to provide users a way to migrate an existing account to a keycard 

The flow starts here: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8374%3A86 
only `Manage keys and storage` is in scope.

When clicked the user will be asked their seed phrase:  https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8218%3A7269

and go through the flow: 

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8218%3A7230

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8218%3A10957

Error state: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8218%3A10131

Success: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=5452%3A766

### Notes

For simplicity the database can be completely removed and re-initialized, eventually we will support migrating data, but out of scope for now.

**Comment by shivekkhurana** [comment]
The first iteration will happen only on Android devices, because Keycard for iOs doesn't exist yet.
