### ISSUE TITLE
Show button to Accept Starter Pack on deep link to Public chat

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11433]
Follow up to #11432 

# Problem
Deep link to public chat is intended for use with advertisers and influencers. Prior to introducing deep link to public chat, referral campaigns have been stopped following feedback that attributions were much lower than traffic (referral url use) provided by influencers and advertisers.

Allowing users to receive a Starter Pack in exchange for their attribution should increase attributions, as well as user retention.
_Previously StarterPack release for advertiser and influencer campaigns was too expensive. Gas prices are more favorable now and promo packs will be used to control number of Starter Packs being released_

### User stories
As a user
I want to receive a StarterPack when I join Status
so that I can try features and get crypto for trying out the app

As a user
I want to be pointed directly to a chat after creating an account
so that I can find out what to do in the app

As I user
I want to explicitly join the chat
so that if there is spam in the chat, the app doesn't crash without me being able to do anything about it

[Design](https://www.figma.com/file/brK5wYEsm82xbMz7V2orM3/Referral-program-UI-s?node-id=169%3A153)

![Frame 55](https://user-images.githubusercontent.com/35233054/100136537-76006000-2e8b-11eb-92ca-d256386b1ba0.png)

## Acceptance Criteria
- User is shown button to Accept StarterPack and join public chat
- Accept Starter Pack behaves the same as referral deep link to 1:1 chat
- Messages for public chat are only fetched after user taps Accept and Join
- Dialog incl Accept and join button remains visible in pending or confirmed state
- User can join chat without accepting Starter Pack and attributing referrer by removing the chat from the chat list and adding it again manually

**Comment by Ferossgp** [comment]
I don't see how we can implement these:
* Dialog incl Accept and join button remains visible in pending or confirmed state

How then we access the public chat after press on "Accept and Join chat"? If we redirect to the chat after acceptance, how then the user will access this screen again to see the pending screen?

* User can join chat without accepting Starter Pack and attributing referrer by removing the chat from the chat list and adding it again manually

Does this mean that we also need to show this chat in the list of user chats?

**Comment by hesterbruikman** [comment]
> I don't see how we can implement these:
> 
>     * Dialog incl Accept and join button remains visible in pending or confirmed state
> 
> 
> How then we access the public chat after press on "Accept and Join chat"? If we redirect to the chat after acceptance, how then the user will access this screen again to see the pending screen?

I see, I actually thought the content could be shown on the same screen; simply remaining at the top and populating messages below. If there's no way to do that, it'll need a different design



>     * User can join chat without accepting Starter Pack and attributing referrer by removing the chat from the chat list and adding it again manually
> 
> 
> Does this mean that we also need to show this chat in the list of user chats?

Yes, I think similarly I expected this to be the same public chat and was simply pointing out that the user is not 'forced' to accept in order to join the chat. There is a workaround, which means removing the chat

Let's sync on chat. As this might need a different approach
