### ISSUE TITLE
Meta-transaction data shown in the request screen doesn't scroll properly 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11457]
Related to status-im/status-react#11392

When using the request screen (all flavors: generic, payment and redeem), if the user clicks on "show transaction data", the app shows the meta transaction data. 

Problem: there is a UI issue and this data is not always scrollable

**Comment by churik** [comment]
@guylouis any clue how can I get this screen? :)
Is it relevant?

**Comment by guylouis** [comment]
this screen can only be triggered by a dapp that calls a specific web3.js function described here https://keycard.tech/docs/web3.html
this was created to enable point of sales use cases with status and keycard 
it's not the priority anymore, we will come back to this but not in the short term 

Since the request screen works, and this i anyway just a low severity bug to improve it. I would not tackle this now. 

@bitgamma fyi

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
