### ISSUE TITLE
'Set max' option is not working if "Send transaction" screen was opened using universal scanner

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11460]
# Bug Report

## Problem
When scanning QR code with wallet address using universal QR code scanner or QR code scanner in wallet, "Set max" option does nothing.
![BAACAgQAAxkBAAEtg2Nft74ea1UWPnrqdV9KPzcsFfC8QQACyggAApKSwVE6GTjljgizgh4E_1605877392 96](https://user-images.githubusercontent.com/4557972/99803237-63a7be80-2b39-11eb-8d44-a49aa9e1458e.gif)

#### Expected behavior
can set max

#### Actual behavior
nothing happens

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Using "Universal QR scanner" scan valid wallet address
- Try to "Set max"

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 20/11/20 
- Operating System: Android, iOS

**Comment by churik** [comment]
relevant on 1.15

**Comment by churik** [comment]
still valid on nightly 27/07/22

**Comment by yqrashawn** [comment]
Hi, I'd like to work on this one.
