### ISSUE TITLE
Status: images bellow text as default, but also configurable position

### ISSUE THREAD

**Issue by danimesq** [status-im/status-react#11475]
Images are on top of text, unlike the conventional - which is ok - but also different from its edit/preview.

Images should be bellow text, or configurable.
https://twitter.com/MesquitaDaniell/status/1331362400948412419

**Comment by bluebibi** [comment]
unsubscribe


2020년 11월 25일 (수) 오전 7:24, Daniell Mesquita <notifications@github.com>님이 작성:

**Comment by cammellos** [comment]
Tracked here https://github.com/status-im/status-react/issues/10801
