### ISSUE TITLE
Update copy and styling advertiser referral link (excl StarterPack)

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11473]
# Problem
- Title of current popup doesn't meet design
- Copy has been updated to be more explicit

Popup appears when user onboards with referral link of type 'AdvertiserRegistration'

### User story
As a user
I want to be explicitly requested to attribute a referrer
so that I can follow a commercial link to install Status while maintaining control over the data I share with them in return

[Design](https://www.figma.com/file/brK5wYEsm82xbMz7V2orM3/Referral-program-UI-s?node-id=3%3A469)

![Advertiser registration - no deeplink, no Starter Pack](https://user-images.githubusercontent.com/35233054/100142668-92ed6100-2e94-11eb-864d-7f91243ed141.png)

## Future Steps
see #11246

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
