### ISSUE TITLE
Statuses issues

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#11470]
# Bug Report

1) Outgoing reaction alignment is wrong
![image](https://user-images.githubusercontent.com/11790366/100117181-d3d57d80-2e74-11eb-9c08-dd4624b52d63.png)

2) statuses page is flickering when there are images 

3) swap profile and statuses tabs

**Comment by errorists** [comment]
another one, in the unfurled link container, can we have all corner radius to be the same 16 for status updates? similar to images, we shouldn't be using the chat's teardrop shape here

**Comment by errorists** [comment]
![image](https://user-images.githubusercontent.com/4932774/100202947-42145180-2f02-11eb-987f-7cfc158ae0bf.png)

everyone is mentioning this, can we change the translation to just `Fetch more` without the `messages`

**Comment by errorists** [comment]
would be super cool to figure this out, place image and text in a single update exactly how they appear when you compose them in the My Status modal https://github.com/status-im/status-react/issues/11475
