### ISSUE TITLE
Sent TXs never reach the pool if to change network for account multiple times

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11472]
# Bug Report

## Problem

At some point it may happen that when user sends transaction it is displayed as Pending and has hash in transaction history, however, it never appears in Pending state in the actual network (can't find in Etherscan), even if Gas Price was twice more than current recommended.
It reproducible when for the same account changing network back and forth (not app restart but re-login).
But could not reproduce when re-login being in the same network.   

#### Expected behavior

Transaction sent and mined as expected disregard how many times network changed for account 

#### Actual behavior

TX never found in the Etherscan and never mined if I change the the network for the same account multiple times
![2020_11_24_19_32_40_trim (1)](https://user-images.githubusercontent.com/8749671/100131808-3175c400-2e8d-11eb-9111-5da0d1b995b8.gif)

### Reproduction

1) Open Status and recover an account with funds in Mainnet and Rinkeby
2) Switch network to Rinkeby
3) Send transaction (ETHri) in Rinkeby network to any address. No need to wait till it is mined.
4) Switch network back to Mainnet
5) Send ETH transaction
6) Check the transaction from 5th step if it's ever appear in Etherscan as Pending/Success
**Actual result:** No transaction appears in Etherscan however, it's `Pending...` in Status.

Note: if it's OK in 6th step, - repeat 2-5th steps once more

### Additional Information

- Status version: release 1.8
- Operating System: Android and iOS

#### Logs

[geth.log](https://github.com/status-im/status-react/files/5591494/geth.log)
[Status.log](https://github.com/status-im/status-react/files/5591496/Status.log)

**Comment by Serhy** [comment]
cc @hesterbruikman @cammellos This happens in Mainnet, but I'm not sure about it's priority because it happens at least when changing the network twice including sending TX in the 'test' network and funds were not lost, - TX simply fails at some point to be broadcasted (if it's correct word to use for reason of this bug, - we still see in Status tx hash)

This also could be possible answer to 'I'm sure I sent transaction but never found in etherscan' question

**Comment by churik** [comment]
Couldn't reproduce the issue on nightly 27/07/22
