### ISSUE TITLE
'No protocol method DateTimeProtocol.plus- defined for type null:' error when block contact

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11489]
# Bug Report

## Problem

There is an error appears after contact is blocked from public chat:  '`No protocol method DateTimeProtocol.plus- defined for type null`
Originally reported by user, I was able able to reproduce sporadically after 30+ contacts was blocked from public chat. Then all further contact blocks worked fine after app restart. 
Logcat attached with log error. 

#### Expected behavior

No error when blocking contact from public chat 
#### Actual behavior
When contact is blocked from public chat 
<img width="362" alt="Screenshot 2020-11-30 at 12 48 28" src="https://user-images.githubusercontent.com/8749671/100600876-8d679f00-330a-11eb-970f-8516e0a52325.png">

### Reproduction

- Open Status and create new account
- Join public chat with messages
- Long tap upon one contact
- Tap `Block contact` -> `Block`

### Additional Information

- Status version: release 1.9.0
- Operating System: Android (confirmed with Android 9) and iOS

#### Logs
[Status.log](https://github.com/status-im/status-react/files/5615543/Status.log)

**Comment by churik** [comment]
Have you seen this error again @Serhy?

**Comment by Serhy** [comment]
I did not see this error since this issue posted, retested with blocking users again in 1.13.0 and could not reproduce (plus we removed a long-tap upon contact from chat, - so blocking a user is done via his profile view which opens by tap upon username/user-icon). Closing this issue.
