### ISSUE TITLE
Jump to the original message by clicking on the reply box

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11482]
# Feature Issue

Add navigation to the message that was replied to.

### User Story

As a user, I would like to navigate up to the original message by clicking on the reply box.

<img width="396" alt="Screenshot 2020-11-30 at 10 29 21" src="https://user-images.githubusercontent.com/67952253/100592063-ea595a00-32f6-11eb-9f10-7fbec157e1ed.png">

### Notes

Feature request was posted here:
https://discord.com/channels/624205794384281629/626744384565674034/764101405833166848

**Comment by churik** [comment]
Will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
