### ISSUE TITLE
"Audio recording permission denied" if try to record audio in Instabug report [Android only]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1149]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, it's impossible to record audio in Instabug report: it shows "Audio recording permission denied" message. App does not ask for permission to record audio. In App permissions setting there is no Microphone permission listed. 
![permission android audio](https://cloud.githubusercontent.com/assets/6584810/25658802/04ac202a-3005-11e7-84ed-7d7cf4dea246.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When user tries to record audio for 1st time there is popup with "Allow/Deny access to microphone"
#### Actual behavior
[comment]: # (Describe what actually happened.)
 "Audio recording permission denied" message. App does not ask for permission to record audio.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Shake phone
- In popup tap on Report a problem
- Proceed to the next step from "Report a problem" screen
- Tap on mic icon in the bottom and tap on Record a Voice note 
- Press and Hold mic icon -> currently, "Audio recording permission denied" message is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d38
* Operating System: Android only

**Comment by yugensoft** [comment]
What version of android OS is it?

**Comment by annadanchenko** [comment]
@yugensoft Android 6.0.1 on Samsung Galaxy S6

**Comment by rasom** [comment]
@annadanchenko can this be reproduced?

**Comment by annadanchenko** [comment]
@rasom can reproduce with same steps on today's develop with Android 6.0.1 on Samsung Galaxy S6

**Comment by rasom** [comment]
ok, thanks

**Comment by annadanchenko** [comment]
no more Instabug so ok to close
