### ISSUE TITLE
Sometimes pull-ro-refresh in individual account view leads to endless spinner 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11502]
# Bug Report

## Problem
Following to https://github.com/status-im/status-react/pull/11478#issuecomment-736486097

Sometimes on switching to WI-Fi from cellular network or when WI-FI signal is weak.
Also faced with this issue after getting 429 error (too many requests) in e2e (@rasom please tell me if it should be reported separately)
![image](https://user-images.githubusercontent.com/4557972/100769874-e9aaeb80-33fc-11eb-84b7-214426f95719.png)

#### Expected behavior
Info that transaction cannot be fetched or transaction history

#### Actual behavior
endless spinner;
even if you switched to WI-FI, transaction history still can't be downloaded until relogin

### Reproduction

1) restore multiaccount from seed phrase when on cellular network
2) open individual account view
3) pull-to-refresh

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 02/12/20
- Operating System: Android, iOS

#### Logs
- From e2e:
Session of e2e: https://app.saucelabs.com/tests/48645b9793b34e5f8ca37fdcd05f54f9?auth=54f95a473cd8a89c7b83a1d367e1440f#114
Logcat: [logcat.log](https://github.com/status-im/status-react/files/5624053/logcat.log)

- IOS (cellular network): 
https://github.com/status-im/status-react/files/5622297/status_logs.zip

**Comment by rasom** [comment]
@churik the issue you see on that screen is unrelated to tx history, this happened on sending transaction
