### ISSUE TITLE
Transactions are failed with 429 Too Many requests too often (Ropsten)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11507]
# Bug Report

## Problem
Around 50% of transaction e2e currently failed with error  429 Too Many requests on Ropsten network in e2e builds.
![image](https://user-images.githubusercontent.com/4557972/100869798-d865eb80-349d-11eb-8b84-3c0d8cd10946.png)

As @rasom said, it can be fixed by using more tokens for Infura.

#### Logs

Session: https://app.saucelabs.com/tests/0a6cb6cd0fc64ae388ea4c5db0e2b591?auth=e095fb692e88e7f3a10f7673832e56d8#120

Logcat: 
[logcat (1).log](https://github.com/status-im/status-react/files/5629060/logcat.1.log)

**Comment by cammellos** [comment]
@rasom seemsl like the best way to address this is to back-off the amount of seconds and retry, (we could create multiple tokens as well, but this seems to be the first step to try), would you agree?

**Comment by churik** [comment]
seems that issue somehow related to #11478  PR
Couldn't find this failure in e2e tests before this PR.

**Comment by rasom** [comment]
closed by 7055c46
