### ISSUE TITLE
A way to add custom ERC-721 assets

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11505]
# Bug Report

## Problem
Currently added ERC-721 assets are treated as ERC-20 assets.
That can cause issues at attempt to send them to another wallet.
Originally reported by user:
> I added the KODA (Known Origin) token contract address expecting to see my qty of KODA to show in my wallet along with my KODA collectibles (Digital Artwork). The KODA qty is displayed but the collectibles are not shown when clicking in the collectibles section. This shows fine in my MetaMask wallet. 

#### Expected behavior
new asset in Collectibles, can see them in Opensea

#### Actual behavior
![IMAGE 2020-12-02 11:37:28](https://user-images.githubusercontent.com/4557972/100861926-c29ef900-3492-11eb-8770-c6df62c0edbb.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add custom ERC-721 asset

### Additional Information

- Status version: 1.9
- Operating System: Android, iOS

**Comment by cammellos** [comment]
This is tracked here https://github.com/status-im/status-react/issues/10373 , closing for now, feel free to re-open if necessary
