### ISSUE TITLE
`DEBUG` log level by default in PRs builds and e2e builds

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11525]
# Problem
Better to have more logs in PR builds, as in most of the cases developers need `DEBUG` level instead of default `INFO`.
Will reduce time for replicationg issues to get debug logs.

## Acceptance Criteria
- `DEBUG` is set as default in PR builds and in all e2e builds
- 5368 e2e is fixed to check default log level

**Comment by Batatos** [comment]
Hi @churik ,

I want to be assigned on this.
