### ISSUE TITLE
Browser bookmarks 2.0

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#11538]
1.0 is here https://github.com/status-im/status-react/pull/11533

Finish browser design and features

* [ ] search recently opened and bookmarks
* [ ] tabs design , animation and screenshots
* [ ] persist tabs
* [ ] the no.1 way to improve the UX is to bring favicons into the list (Maciej)
* [ ] why can't I open multiple instances of empty tabs? It's a bit weird coming from other browsers, to find empty tab being permanently opened and only a single instance of it. It would be better if we could have multiple instances of empty tabs, and if you have only one left on the list it could be closed. (Maciej)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
