### ISSUE TITLE
Add extra tokens to default asset list

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11542]
@Simona-Pop commented on [Mon Nov 30 2020](https://github.com/status-im/status/issues/17)

**As a user**

I want to be able to easily select tokens from the default asset list so that I can better interact with projects featured in dapps - this will make my experience better by accessing tokens easily

Tokens to add:

 - aDAI and other aTokens - https://docs.aave.com/developers/deployed-contracts/deployed-contract-instances
 - aTokens images - https://aave.com/branding/
 - renBTC - https://etherscan.io/token/0xeb4c2781e4eba804ce9a9803c67d0893436bb27d

---

@jdreyespaez commented on [Mon Dec 14 2020](https://github.com/status-im/status/issues/17#issuecomment-744187545)

Another token to add:
- Pooltogether token [here](https://github.com/pooltogether/pooltogether--brand-assets/tree/master/token) assets and this is the token to be included [PcDAI](https://etherscan.io/token/0x334cbb5858417aee161b53ee0d5349ccf54514cf?a=0x8b308c0870dd6da8aba82119a924b9a621ed27bb).

---

@simonricoo commented on [Mon Dec 14 2020](https://github.com/status-im/status/issues/17#issuecomment-744307247)

- AAVE Tokens: https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=366%3A246
- Ren Tokens: https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=514%3A33
- Pool Together tokens: https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=514%3A79
plDAI (https://etherscan.io/token/0x49d716dfe60b37379010a75329ae09428f17118d)
plUSDC (https://etherscan.io/token/0xbd87447f48ad729c5c4b8bcb503e1395f62e8b98)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
