### ISSUE TITLE
Tab with the last viewed website appears after navigating to the Tabs view from the Browser screen on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11545]
# Bug Report

## Problem

"About:blank" tab appears if open browser tabs screen after installing the app, without navigating to any websites before.
If close it and re-login it will appear again.
If open a website in the Status browser, i.e. google.com, then navigate to the Tabs view, tap "Close all" or close the last viewed website, navigate to the Browser tab and return to the Tabs view, the tab with the last viewed website will appear in the list again.

#### Expected behavior

No tabs if the tab list was cleared before

#### Actual behavior

![ezgif com-gif-maker (18)](https://user-images.githubusercontent.com/67952253/102100250-8328c300-3e29-11eb-89c3-17de5b1f7e06.gif)

### Reproduction

- Open google.com in the Status browser
- Tap the Tabs icon 
- Tap Close all
- Navigate to Browser screen
- Tap the Tabs icon 

### Additional Information

- Status version: Nightly 14/12
- Operating System: Android

**Comment by churik** [comment]
blocker for e2e 5390
