### ISSUE TITLE
🏃‍♀️ Improving app startup time at UX level

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#11556]
# Problem
The time is takes for Status app to be interactive is too much compared to industry standard like WhatsApp or Telegram. In a convoluted experiment on an iPhone SE, with biometrics enabled and many channels joined, it took about 6 seconds for the app to become usable.

A part of the delay is due to the encrypted database - we can't really do anything about this. But a significant chunk is because how we structure screens and components:
[Pre Login]
- After the splash screen goes away, a list of multi accounts show up for a split second
- The user is then redirected to the last used multiaccount (aka login page)
- If the bio-metrics are turned on, the user is then redirected to a biometrics screen automatically

[Post Login]:
- On successful login, we present the user with a loading spinner ⭕️ 
- Then the active chats populate
- Followed by a few seconds delay (which makes me feel that the app has hanged), and finally the new chat messages (ignoring the scroll context)

## Implementation
The implementation is two phased:
1. Change the routing structure to show the login or biometric page directly after splash screen (user can cancel and choose other accounts)
2. Add skeleton screens on chat list page (and maybe inside chats too) instead of a full screen loading indicator, so that the app becomes responsive and user can at least use tabs. 

## Acceptance Criteria
- The bio-metric screen shows up immediately after the splash screen
- The chat screen loading indicator is localised (ie. instead of blocking the entire view, skeletons should be rendered and other parts of the app, like bottom tab bar should be usable).

## Notes
- Instead of skeleton screens on chat list page, we can also show gibberish text like "ejkj787932Fwws" in places where the channel names and messages show up. The loading indicator will say "decrypting" instead of "loading" which make the extra load time justified. 
- The loading skeletons might cascade to other screens to, because if the user can navigate to other tabs before the database is decrypted, many functionalities will break.

**Comment by hesterbruikman** [comment]
@shivekkhurana Great catch! Sounds like a good improvement. For some planning hygiene, I suggest bundling this with an effort to make other improvements to onboarding. To be compiled and captured in issues, but there are enough for a small epic

Regarding item 2 skeleton screens. I see a dependency here with #11251 where the latter is an edge case in which delay is not the result from messages being loaded, but from db migration happening in the background and perhaps other unforeseen activities. I'm not sure how we can best communicate such case, so for now just flagging so you're aware of this issue

**Comment by shivekkhurana** [comment]
@errorists Updated the login screen to be the entry point:

<details>
<summary>Screenshot 🖼</summary>

![Screenshot_2020-12-17_at_13 50 16](https://user-images.githubusercontent.com/1925158/102505534-1f5ffd80-40a8-11eb-9dc9-7d6de3db339f.png)

</details>
