### ISSUE TITLE
Emoji reactions doesn't resend when sent immediately after network disconnect

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#11553]
# Bug Report

## Problem

If you turn off network connection and send emoji reaction right after - it won't be delivered when connection turned on. This is because in `status-go` we do not wait for acknowledgements from non-mailserver peers and automatically treat them as delivered. Same thing happens with chat messages - they treated as delivered while in reality they aren't

#### Expected behavior

Reaction resends when devices goes back online

#### Actual behavior

Reaction not resends when devices goes back online

#### Notes

Related to #11020

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- turn off network connection and quickly add emoji reaction to any message
- at this moment reaction can't be seen on other device
- turn on network connection
- make sure reaction seen on other device after short period of time

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.8
- Operating System: Android,iOS

**Comment by churik** [comment]
couldn't reproduce on 1.15
