### ISSUE TITLE
Push notification of the outgoing message on the synced Android device in background

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11550]
# Bug Report

## Problem

If sync two devices, one of which is Android, and send a message to 1-1 chat from another device then the push notification about the sent message will be received on the Android device while it is in the background.

#### Expected behavior

No push notification on the synced device

#### Actual behavior

Push notification about the outgoing message in the background

### Reproduction

- Recover the same multiaccount on Device 1 (any OS) and Android device
- Sync Device 1 with Android device
- Enable push notifications on Android device
- Send the Android device to the background
- Start 1-1 chat with another user on Device 1
- Send a message from Device 1
- Check push notification on the Android device

### Additional Information

- Status version: Nightly 15/12
- Operating System: Android

#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/5697317/Status-debug-logs.5.zip)

**Comment by churik** [comment]
relevant on 1.13
