### ISSUE TITLE
Buttons are looking as disabled (on background) when changing profile photo 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11559]
# Bug Report

## Problem
Leftover from #11347
Editing profile picture interface is greyed out on Android, which makes it confusing.

#### Expected behavior
active buttons, depending on dark or light mode

#### Actual behavior
<img width="381" alt="Monosnap 2020-12-11 12-14-26" src="https://user-images.githubusercontent.com/4557972/101897374-bad60780-3baa-11eb-8f2e-ec80622b556d.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to profile and change profile picture

### Additional Information

- Status version: develop with https://github.com/status-im/status-react/pull/11347
- Operating System: Android

**Comment by churik** [comment]
still relevant on 1.15

**Comment by qoqobolo** [comment]
Is not reproducible on 1.18
Android 11, light and dark mode

<img width="260" alt="Screenshot 2022-03-11 at 16 19 26" src="https://user-images.githubusercontent.com/67952253/157895721-faf38dde-992d-4bb4-b85e-974e576b6805.png">
