### ISSUE TITLE
List of Transactions is empty in the Wallet while transactions were done

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1156]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: No transactions are in the Wallet. App is in sync. Could sent/receive ether but no transactions listed. Waited for 20 minutes - still empty list 
![no transactions](https://cloud.githubusercontent.com/assets/6584810/25679382/6d74abde-304d-11e7-93ba-d9a7edc7ea02.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Wallet has list of transaction that is not empty
#### Actual behavior
[comment]: # (Describe what actually happened.)
list of transaction is empty
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- use /faucet in console to request eth
- send some eth to other contact
- receive some eth from another contact
- open Wallet and check content of Transactions list

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d47
* Operating System: Android and iOS

**Comment by GustavoNunes** [comment]
Hi @annadanchenko, I couldn't reproduce this one. In both Android and iOS, I created an account, used the faucet and sent some eth. The transactions appeared in the Wallet dapp.

**Comment by annadanchenko** [comment]
Re-checked it this morning - now transactions are listed (at least on android). Closing it for now.
