### ISSUE TITLE
Own profile picture isn't displayed in the member list on the Group info screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11569]
# Bug Report

## Problem

If set a profile picture, create or join a group chat, and navigate to Group info, the own profile picture will not be displayed in the member list.

#### Expected behavior

Own profile picture is displayed in Group info.

#### Actual behavior

No own profile picture.

<img width="236" alt="Screenshot 2020-12-22 at 14 40 23" src="https://user-images.githubusercontent.com/67952253/102894648-be4b7780-4463-11eb-8577-b7d4cc5d783c.png">

### Reproduction

- Open User Profile settings and set a profile picture
- Create a group chat
- Open Group info

### Additional Information

- Status version: Nightly 22/12
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
fixed in develop
