### ISSUE TITLE
Blank page after navigating to browser tabs view from browser screen and using back gesture

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11561]
# Bug Report

## Problem

If open browser tabs right after the browser screen and tap the Android back button or swipe to go back on iOS, an empty page will be opened.

#### Expected behavior

Navigation to browser screen when using the back gesture from the tab screen

#### Actual behavior

Blank page

![ezgif com-gif-maker (20)](https://user-images.githubusercontent.com/67952253/102596207-22df9d00-4119-11eb-9bfe-1ce63e10823d.gif)

### Reproduction

- Open Status
- Navigate to Browser screen
- Tap Tabs icon
- Tap Android back button or swipe right on iOS

### Additional Information

- Status version: 18/12
- Operating System: Android, iOS

**Comment by churik** [comment]
not relevant on 1.15
