### ISSUE TITLE
"Increase Gas" and "Cancel" do not replace transactions on keycard accounts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11585]
# Bug Report

## Problem
In case of using "Increase gas" or "Cancel" on keycard multiaccount instead of replacing initial transaction new transaction is created.
So basically feature is not working on keycard.
Leftover from https://github.com/status-im/status-react/pull/11456

#### Expected behavior
Transaction is dropped and replaced 

#### Actual behavior
New transaction with increased nonce is created 
![Monosnap 2020-12-24 16-44-37](https://user-images.githubusercontent.com/4557972/103097466-a0b71300-4607-11eb-8cf0-feb9f2e7bbaa.png)

### Reproduction

- Open Status, restore multiaccount with seed phrase (with assets on it)
- Try to send transaction with low gas price
- Try to increase Gas price 
- Try to cancel transaction

### Additional Information

- Status version: 1.10
- Operating System: Android

Initial transaction: https://etherscan.io/tx/0x87a097f866e514cb5596d2876ebddf7e3b6984393ce32b010ff14839584280d7
Attempt to increase gas: https://etherscan.io/tx/0xa27a2c1a5f56d8e48d0a0148ba18b06c0cf841fd06510b9b0714ca5d4deae8c9
Attempt to cancel transaction: 
https://etherscan.io/tx/0x1c76d061bd3adf55a59170e0b0128c036910b9ca3b39178f6c7122ec456d6033

**Comment by cammellos** [comment]
This is sort of fixed, I will close it for now, and open a feature request for increase gas/cancel transaction on keycard.
