### ISSUE TITLE
Add Giphy & Tenor gif support

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11580]
As a user
I want to be able to preview Giphy & Tenor
So that I can send and receives gifs in chat

### Description

Giphy & Tenor have been whitelisted in status-go, status-react can now leverage that support.
There seem to be some questions about how we fetch those, so that needs to be looked at.

For example

> btw, Giphy does support oembed https://giphy.com/services/oembed?url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fcant-hardly-wait-kW8mnYSNkUYKc we could use it to get the gif url

**Comment by cammellos** [comment]
This has been fixed by disabling gifs previews.
I will convert it to a feature request.
