### ISSUE TITLE
Add send video, send files, video call, phone call & send location features in private and group chat

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11591]
# Feature Issue
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story
![Capture+_2020-12-29-01-17-11](https://user-images.githubusercontent.com/40263018/103247400-d47f9900-4977-11eb-9a72-b3f0297c4d91.png)

As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description
[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
_Summary_: ...

### Acceptance Criteria
[comment]: # (Rules for the future PR to be accepted.)

### Notes
[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by cammellos** [comment]
Thanks for the feature request, we use https://discuss.status.im/ for those, please open a post there.
thank you!
