### ISSUE TITLE
Improvements to Cancel and Speed up transaction

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11613]
# Feature Issue
Cancel and Speed up transaction was planned for release 1.10, but pulled from release as some unforeseen cases occurred that made the feature feel unreliable.

#### Root causes

* Nonce or tx object is not stored locally; after a signed transaction has been dispatched, transaction information (including the required nonce) is only available through an http request to Infura
  * Tx may be in Infura pool, but not in Etherscan, as a result the user may get confused 
  * Sometimes there is no tx in infura. Might not be in the pool yet, so a hash is not returned
  * If the user closes the app or signs out, the pending transaction cannot be cancelled or speed up because the tx object was not stored and the hash was not yet received from Infura (as described in #11597)
* Speed up transaction is unreliable and can easily result in two pending transactions as no gas estimation service is used to ensure that the replacing transaction is effective. This can result in the user spending more gas without result
  * The same is true for Cancelling a transaction, but this transaction is cheaper in gas as it's a 0 ETH tx to the user's own address

### User Stories

* As a user I want to cancel a transaction at any time, also after closing and reopening the application
* As a user I want to spend more gas to speed up a transaction only if there's a reasonable chance that the new transaction will go through, because I don't want to end up with two pending transactions and having spend more ETH
* As a user I want to trust that if the application tells me that I can speed up a transaction I can effectively do this without 'wasting' gas, because I don't know how much gas to make my 2nd transaction go through in an active market
* As a user who knows current gas prices well, I want to be able to speed up (replace) my transaction even when the app can't give me an accurate gas estimate, because I can do this myself and want control over my transactions (advanced use case)
* As a user I want to see that I Canceled or Speed up (i.e. Replaced) a transaction, because it gives me feedback/confirms that my action was effective (even if both transactions are still pending) and is consistent with finding 2 pending transactions on Etherscan
* As a user I want to see that I Canceled or Speed up (i.e. Replaced) a transaction with a new transaction, and that one was mined successfully, while the other was not, because this reassures me that only one transaction occurred and is consistent with finding 2 transactions, of which one failed, on Etherscan

### Description

* [ ] Store nonce or tx obj as a whole after transaction is successfully dispatched to blockchain (i.e. Infura) > #11597 
* [ ] Review services to get gas estimation for use within principles (Desktop + Referral service)
* [ ] Propose design changes, if sensible, to move speed up tx to an 'Advanced' view
* [ ] Propose design changes, if sensible, to show the state of two pending transactions with the same nonce 
* [ ] Propose design changes, if sensible, to show the state of two transactions with the same nonce and eventually one 'failing', or 'replaced' (tbd what exact state this is as there's no way of knowing which tx wins

### Notes
Separate issues already exist to enable Speed up and Cancel transaction for Keycard, #11595 #11594

**Comment by hesterbruikman** [comment]
@flexsurfer, for the gas estimation when replacing a tx, wondering if this Infura update makes a difference: https://blog.infura.io/announcing-our-acquisition-of-any-sender-and-the-alpha-release-of-infura-transactions/ 

(Even though we would probably want a more self-reliant solution eventually as goes for use of Infura in general)

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
