### ISSUE TITLE
Resending messages is to eager

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11617]
We noticed in group chats that performance degrade quickly as the number of users increase.

One of the reason is that we re-send messages too eagerly, I can see in log a ton of `message.sent` event.
This is probably fine when you have a one to one, but with a group chat of 15 users it means that you will be sending (for a single message):

15 messages on the first round
15 messages after 30 seconds
15 messages after 60 seconds
15 messages after 120 seconds 
..... 

clearly that's too much, so we should relax the re-sending time for private group chats, or have different kind of optimizations so we don't send a message for each user, but that's more complex, for now relaxing the resending interval is probably the easiest.

**Comment by churik** [comment]
Still relevant @cammellos ?


Added `recheck` label for easy finding that one in case of need.
