### ISSUE TITLE
Add GRT erc20 token in our default list of supported tokens in the wallet

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11627]
**summary** 
add GRT erc20 token to our default list of erc20 token supported by the wallet 

**user story** 
a user holding GRT token in his wallet account should see in his list of assets the number of GRT tokens he holds

**details**
the token details (name, contract address, decimals) are here (provided by the Graph team directly)
https://docs.google.com/document/d/1zFXNliXfeie5ufukQjXLxWI8rqavZIZVx1-cb3qKqy8/edit
and logo here 
[logo](https://drive.google.com/drive/folders/17yaoidIUTd2OQqRKeLW52Vfw7J5QXGT_)

**Comment by flexsurfer** [comment]
@guylouis logo is 404

**Comment by guylouis** [comment]
thanks for the headsup @flexsurfer 
link corrected
