### ISSUE TITLE
Crash on enabling chat link previews on Android 10 or later

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11631]
# Bug Report

## Problem
Issue is not reproducible on release 1.10.
When enable youtube link previews on Android 10, got java exception and app crash.

#### Expected behavior
no crash, previews are enabled

#### Actual behavior
![IMAGE 2021-01-12 16:13:06](https://user-images.githubusercontent.com/4557972/104333008-0e60ab80-54f1-11eb-9a1e-28bf6bbbe901.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join any chat with youtube links 
- Enable preview

### Additional Information

- Status version: nightly 12/01/2021
- Operating System: Android 10+

#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/5803000/Status-debug-logs.zip)

**Comment by flexsurfer** [comment]
duplicate https://github.com/status-im/status-react/issues/11610

**Comment by flexsurfer** [comment]
should be fixed in tomorrow nightly

**Comment by churik** [comment]
right. thank you!
