### ISSUE TITLE
Status' replies

### ISSUE THREAD

**Issue by danimesq** [status-im/status-react#11647]
As both messages and statuses have support to react with emojis, and messages have support to replies, I think status should have this feature as well.

**Comment by danimesq** [comment]
Also, for both messages and statuses, these replies could support nested replies, and these replies could work as statuses themselves so also supporting reactions.

**Comment by danimesq** [comment]
Just looked at it now, and thankfully this issue isn't a duplicate of another issue, so probably this is the first issue suggesting this so needed feature.

Also related, an bugfix: https://github.com/status-im/status-react/issues/10874

**Comment by cammellos** [comment]
This is a bit tricky, as the way they work you only see messages in your timeline from people you follow, so if you reply to a message from someone you don't follow you would not see it, but we could change the mechanics to allow replies to shows from anyone.

In any case please open a feature request on https://discuss.status.im/ 
We use issues (or try to :) ) mostly for things that we already agreed to implement or bugs. 
Thanks for the suggestion
