### ISSUE TITLE
Display profile picture only of users I have added to contacts

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11643]
As a user
I want to see only the profile pictures of users I have added to my contacts
So that I won't be subject to inappropriate pictures in public chats

### Description

Because of the demand for moderation in app stores to some apps, we decided to limit our exposure and protect users from inappropriate content.
Users should only be seeing profile pictures of other users if they added them as contacts.

### Designs

https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4717%3A2107

### Implementation

This will require a change in status-go to be feature-complete.
If we want to cut the scope to a minimum we can implement the design but grey out the other two options (`Everyone`, `None`), leaving `Contacts` as the only option, which does not require any status-go changes.
Up to you, if de-scoped, please create a separate issue with the remaining work.

**Comment by errorists** [comment]
[Preference setting design](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4717%3A2107)

**Comment by cammellos** [comment]
Status go part is here https://github.com/status-im/status-go/pull/2117

**Comment by churik** [comment]
can we rename it or add more explicit explanation that it is not setting for exposing my profile picture, but for me to see other's profile pictures?
It is extremely unclear and IMO it will be confusing for users.
@cammellos @errorists

**Comment by errorists** [comment]
we can 'Show profile picture **of**'. it should be clear from the label alone, I'm very much open to other suggestions how to phrase it

**Comment by churik** [comment]
Let's add 'of' or 'from' if no objections.
Just asked Diana and Sergey and got the same answer - that at first glance it loos like setting for exposing my profile picture.
And maybe some small label on the screen itself with an explanation sort of "who's profile pictures I choose to see" wouldn't hurt.

@errorists would you mind to update design in figma?
