### ISSUE TITLE
Package to UWP

### ISSUE THREAD

**Issue by danimesq** [status-im/status-react#11649]
Porting into the Universal Windows Platform would allow the Status .exe app to be packaged inside an .appx package, listed in the Microsoft Store while using UWP's notifications, live tile and other of its features. Maybe it would be the first Ethereum/Web3 wallet to enter Microsoft Store and take advantage of the UWP's APIs.

**Comment by cammellos** [comment]
This seems to be an issue for status-desktop,
https://github.com/status-im/nim-status-client , this repo only contains the mobile code.
Thanks

**Comment by danimesq** [comment]
Moved to: https://github.com/status-im/nim-status-client/issues/1684
