### ISSUE TITLE
[Question] How this ReactNative project is ported to Desktop?

### ISSUE THREAD

**Issue by danimesq** [status-im/status-react#11645]
How can an ReactNative project such as Status, be also compiled to desktop while keeping the same codebase?

**Comment by cammellos** [comment]
We used to have our fork of `react-native-desktop` and run the same codebase, but after some discussion we moved to nim/qt implementation, which is a separate codebase other than status-go (backend) which is a shared component. https://github.com/status-im/nim-status-client 
By the way the best place for questions and feature requests is https://discuss.status.im/ .
Thanks!
