### ISSUE TITLE
Add list of website where you can buy crypto

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11644]
As a user
I want to discover places where I can buy crypto
So that I can get rich and buy a lambo 

### Description

There should be a banner in wallet that opens a list of links that if clicked takes you to the right website.

### Scope

The designs shows a webview where the website opens. This can be de-scoped if necessary and the link can be opened in the system browser (if opened in the status browser we need to make sure it works correctly).

### Designs
https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=10744%3A0

### Implementation

The list should be some JSON hosted somewhere (github?) and it should be refreshed periodically, as content might change.

**Comment by guylouis** [comment]
For our ability to change the list without a new release, I'd propose as a scope:
- remove/add entries of the list
- edit content of an entry (picture, title, description, fees and countries)
- (later) possibility to change the copy of  the string "Choose a service you'd like ..."
- (later) possibility to change the copy and url of the "learn more" link

**Comment by Samyoul** [comment]
First step to implementing this feature, the json list of on ramps https://github.com/status-im/crypto-on-ramps

**Comment by guylouis** [comment]
list of URLs for the initial list 

- wyre -> https://pay.sendwyre.com/purchase
- moonpay -> https://buy.moonpay.com/
- transak -> https://global.transak.com/
- ramp -> https://ramp.network/buy/
- localcryptos -> https://localcryptos.com/

**Comment by Samyoul** [comment]
@guylouis in case you missed it yesterday these links are implemented in the [on ramps json document](https://github.com/status-im/crypto-on-ramps). Any changes to the links can be addressed in this repo.

**Comment by Samyoul** [comment]
The PR for the go code https://github.com/status-im/status-go/pull/2131, currently in draft but as it stands this PR will get the on ramp data from the https://github.com/status-im/crypto-on-ramps repo. I'll add some caching so we are not hammering github or whatever other service we may choose to use in the future.

**Comment by guylouis** [comment]
decided on 27/11 with the team, that for a first iteration we'll keep the list of services static (the JSON file), embedded in the code. This is to avoid having to share the user IP adress to the server hosting the JSON file (e.g github).

**Comment by cammellos** [comment]
Closing this, it has been merged
