### ISSUE TITLE
Can I define networkid myself

### ISSUE THREAD

**Issue by xx007** [status-im/status-react#11652]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to define networkid myself
### Description

app start, show the toast ethereum node started incorrectly

it will prompt that the networkid is different from the actual networkid. Clicking the ok button will exit the app and can no longer be used.

I have a main chain with a networkid of 200. Now I want to change networkid 1 to 200.

Which configuration file can modify networkid?

or can I continue using it after clicking the ok button? Ignore this error

thanks.

<img width="475" alt="1" src="https://user-images.githubusercontent.com/3196125/104867497-f5864900-597b-11eb-8d0a-4a51f3923680.png">
<img width="221" alt="2" src="https://user-images.githubusercontent.com/3196125/104867506-fc14c080-597b-11eb-9140-be9966fe4b67.png">

**Comment by flexsurfer** [comment]
hi, you can connect to your custom network
1)open Advanced in Profile
2)open Network
![image](https://user-images.githubusercontent.com/11790366/104890378-c8339e00-596f-11eb-8d93-9cc55e4a8efe.png)
3)press "+"
4) select custom 
![image](https://user-images.githubusercontent.com/11790366/104890437-d7b2e700-596f-11eb-86cc-9ce8313bfd70.png)

**Comment by xx007** [comment]
Do it according to your method, it is ok, network ok

I want to modified Mainnet with upstream RPC

So I modified the file src/status_im/utils/config.cljs 
Also changed to custom_rpc

Because I am not a user, I coded as a developer. I want to write networkid directly in the code,


But after the change, the chat shows Offline after launching, and the wallet cannot be obtained

How should I change the code file? Thank you
<img width="441" alt="1" src="https://user-images.githubusercontent.com/3196125/105018850-7169b980-5a80-11eb-8c4e-c8c22589db4a.png">
<img width="250" alt="2" src="https://user-images.githubusercontent.com/3196125/105018869-7595d700-5a80-11eb-900d-2b050788c465.png">
<img width="257" alt="3" src="https://user-images.githubusercontent.com/3196125/105018883-77f83100-5a80-11eb-8aee-9d22f0a4c905.png">
<img width="258" alt="4" src="https://user-images.githubusercontent.com/3196125/105018897-7af32180-5a80-11eb-978d-7d90d173315a.png">
