### ISSUE TITLE
Public chat with #{chat_key} name appears on the secondary device after pairing

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11654]
# Bug Report
## Problem
If open Profile of some User on Device A and then pair Device A and Device B, the public chat with #{user_chat_key} name will appear on Device B. If the User has posts in the Status tab, they will be displayed in this chat.

#### Expected behavior
No public chat on paired device

#### Actual behavior
Public chat on **_Device B:_**

![](https://user-images.githubusercontent.com/67952253/104902708-582d1400-597f-11eb-819f-2180d25a410d.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Recover the same multiaccount on Device A and Device B
2. Open some User Profile on Device A, for instance from public chat. It doesn't matter if there are posts in his Status tab
3. Sync Device A and Device B
4. Check chat list on Device B

### Additional Information

* Status version: develop
* Operating System: Android, iOS

### Logs
From Device B
[geth.log](https://github.com/status-im/status-react/files/5829640/geth.log)
[Status.log](https://github.com/status-im/status-react/files/5829641/Status.log)

**Comment by cammellos** [comment]
I believe this can be closed now, open if necessary, thanks!

**Comment by qoqobolo** [comment]
@cammellos  Checked on develop, the issue is still reproducible, but steps are now in a different order:

1. Recover the same multiaccount on Device A and Device B
2. Open some User Profile on Device A, for instance from public chat. It doesn't matter if there are posts in his Status tab
3. Sync Device A and Device B
4. Check chat list on Device B

So I'll reopen this issue, but edit the title and description.

**Comment by cammellos** [comment]
thanks, pushed a fix here https://github.com/status-im/status-react/pull/11813

**Comment by cammellos** [comment]
Merged in develop, closing again :)
