### ISSUE TITLE
No spinner when pressing "Fetch more messages" in public chat + white toggles in Sync settings on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11651]
# Bug Report

## Problem 1

If press `Fetch more messages` in chat view downloading spinner doesn't appear.

#### Expected behavior

Spinner appears when pressing `Fetch more messages`

#### Actual behavior

No spinner

https://user-images.githubusercontent.com/67952253/104734670-e798b400-5740-11eb-8d65-b21797554f4f.mp4

### Reproduction

- Join public chat
- Tap `Fetch more messages`

## Problem 2

'Toggle' element is not fully rendered in the disabled state in Sync settings section. 

#### Actual behavior

<img width="324" alt="Screenshot 2021-01-15 at 19 13 32" src="https://user-images.githubusercontent.com/67952253/104743988-a1495200-574c-11eb-81f3-a0149d90b29d.png">

### Reproduction

- Navigate to Settings
- Sync settings 
- History nodes
- Disable `Use history nodes` toggle

### Additional Information

- Status version: develop 15/01
- Operating System: Android

**Comment by flexsurfer** [comment]
React native PR : https://github.com/facebook/react-native/pull/30057 here you can find issues
