### ISSUE TITLE
Hit Enter adds new line to the input field and hides keyboard

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1165]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: Hit Enter now adds new line to the input field but after this keyboard is hidden
Most likely caused by merging #1119 to develop.
This fix was working before: #1111

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
new line is added in input field. Keyboard is visible, so user can proceed typing
#### Actual behavior
[comment]: # (Describe what actually happened.)
keyboard is hidden. New line is added to input field
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7WkdhRFpzbmo4Q2M
- Open Status
- Open 1-1 chat
- Type "A" and hit Enter on device keyboard

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6-52
* Operating System: Android only

**Comment by alwx** [comment]
The fix has been merged yesterday.
