### ISSUE TITLE
Keycard migration flow is missing the popup that informs user about migration success

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#11659]
# Bug Report

## Problem
https://github.com/status-im/status-react/pull/11526#issuecomment-762736743

#### Expected behavior
Designs in comment linked above.

**Comment by shivekkhurana** [comment]
@hesterbruikman On successful migration to Keycard, the "get started" screen pops up instead of the chat pane. But the [UI suggests showing a popup message](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8192%3A466) on the chat screen instead. Do you want to get rid of the "get started" screen on migration?

**Comment by hesterbruikman** [comment]
Apologies for the late reply @shivekkhurana 

> Do you want to get rid of the "get started" screen on migration?

I think a popup on top of the chat screen is better in this case such that you can see the impact of migration on your chats. I suspect it's reassuring to immediately see your chats have remained unaffected if your db was not reset and informative to see your chat list is empty if your db was deleted. In both cases with a modal on top, but in context of the chat view.

Let me know if you have other ideas about this!

**Comment by shivekkhurana** [comment]
I didn't suggest getting rid of the popup. The success popup is a good thing. 
The question was about the ["getting started" screen](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A13440).

**Comment by hesterbruikman** [comment]
So ideally, the pop up is shown on top of chat screen. The getting started screen would not be part of this flow.
