### ISSUE TITLE
Can't connect wallet to zapper.fi (DeFi) in Status browser

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11667]
# Bug Report

## Problem

There is no permission access buttons (Accept/Decline) appears when I try to connect wallet in zapper.fi selecting 'Status' as wallet option to connect

#### Expected behavior

Can connect wallet to zapper.fi

#### Actual behavior

Engless spinner in Status browser when trying to connect to zapper.fi

<img width="314" alt="Screenshot 2021-01-20 at 15 26 03" src="https://user-images.githubusercontent.com/8749671/105180914-d3372b80-5b33-11eb-99eb-b1b2798028ea.png">

### Reproduction

- Open Status and login to account
- Open Browser -> enter `zapper.fi` in URL input and submit
- In dapp tap `Connect Wallet` button
- Select `Status` from the list of wallets

### Additional Information
- Status version: release 1.10/develop
- Operating System: Android and iOS

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/105182042-dbd83380-5b2c-11eb-88c1-8fb8e05ed3c2.png)

**Comment by flexsurfer** [comment]
its not a Status issues i guess, at least we have manual option and it works 

![image](https://user-images.githubusercontent.com/11790366/105182226-1772fd80-5b2d-11eb-8bfc-96f2997f4833.png)

**Comment by cammellos** [comment]
Tested and it's fixed in develop/1.11, feel free to re-open if it's still an issue
