### ISSUE TITLE
Add Group invite with QR Code

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11662]
# Feature Issue
![Capture+_2021-01-19-16-38-46.png](https://user-images.githubusercontent.com/40263018/105042071-dc14f800-5a74-11eb-9e98-a2b314e241f9.png)
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story
As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description
[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
_Summary_: ...

### Acceptance Criteria
[comment]: # (Rules for the future PR to be accepted.)

### Notes
[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by churik** [comment]
Moved to https://github.com/status-im/status-react/discussions/12614 discussion
