### ISSUE TITLE
Error "Failed to create database.." while attempting to log in after log out

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11664]
# Bug Report

## Problem

If log out using the bottom "Sign out" in User Profile, then while attempting to log in an error appears and login is not possible until re-open the application.

#### Expected behavior

No error, can log in

#### Actual behavior

<img width="337" alt="Screenshot 2021-01-19 at 20 22 44" src="https://user-images.githubusercontent.com/67952253/105062496-f2be4d80-5a7a-11eb-9593-6ce27e049452.png">

### Reproduction

- Install Status
- Log in
- Navigate to User Profile
- Sign out
- Try to log in

### Additional Information

- Status version: develop
- Operating System: Android

#### Logs

[geth.log](https://github.com/status-im/status-react/files/5837218/geth.log)
[Status.log](https://github.com/status-im/status-react/files/5837219/Status.log)

**Comment by cammellos** [comment]
```
01-19 20:08:20.205 20910 20993 E StatusModule: Logout failed: {"error":"server: \u003cnil\u003e, services: map[*wakuext.Service:sql: database is closed]"}
```
Seems like a status-go error, will take a look

**Comment by cammellos** [comment]
I don't think we have an issue here, basically that error is coming from a PR that I made
I created a manual build (but not published) with nightly parameters
I take tests have been running against it for some reason, is that possible?
(currently nightly and develop are fine, only my PR was giving that error)

**Comment by qoqobolo** [comment]
> I don't think we have an issue here, basically that error is coming from a PR that I made
> I created a manual build (but not published) with nightly parameters
> I take tests have been running against it for some reason, is that possible?
> (currently nightly and develop are fine, only my PR was giving that error)

Yes, it seems the manual build was taken by mistake. Everything is fine then. Sorry for bothering you.
