### ISSUE TITLE
Add a dedicated Token Details view

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#11678]
# Feature Issue

Scope of this feature is to add a dedicated view to track token value across time, up-down % trends and perform all interactions for that token. This view would be accessed by tapping on a token in your wallet. 
_Outside of scope: it would also be presented when you 'mention' token in chat by prefixing it with `$` character (type `$snt` creates a link to this details view in a message)_

### User Story

As a user I want to track the price of my tokens, or tokens I'm interested in. I want to know how their value changed across different time spans, how well they're performing and take all available actions from one place. I want this data to be shown on a graph I can interact and zoom on with.

### Description

**Design in Figma [here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=18652%3A552)**
_work in progress, will be updated with all available interactions_

<img width="379" alt="Token Details View" src="https://user-images.githubusercontent.com/4932774/105730110-44108600-5f2e-11eb-9f0d-e5f087a90d84.png">

#### Scope:

- Implement the design for this view
- Include the graph visualisation, allow for scrubbing it horizontally to show the value for that particular position as long as it's pressed.
- include a % change of value for chosen time period
- allow to change the time period between: 1 hour, 1 day, 1 week, 1 month, 1 year
- show current balance in your wallet
- place available interactions : send, buy (prerequisite: crypto onramp), swap (prerequisite native token swap integration), request
- tapping on a token in your wallet list should open this view

Out of scope:
- at mentions of tokens in chat

### Acceptance Criteria

This view was implemented with all of the functionality, fetching is optimised and relatively fast, graph animates between state changes and can be scrubbed to show data for a given time on the X axis. 

### Notes

Designs are missing states for loading - scrubbing, I'm working on them and will edit this issue once finished.

Thanks! 🙌

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
