### ISSUE TITLE
Can't fetch message history after rejoining a public chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11683]
# Bug Report

## Problem

If join a public chat, delete it and join it again, there will be no history for the day that was already fetched before deletion

#### Expected behavior

Can get history after rejoining

#### Actual behavior

https://user-images.githubusercontent.com/67952253/105839394-b4bcae80-5fd1-11eb-912a-17cd690532c6.mp4

### Reproduction

- Join public chat
- Navigate to home screen
- Long tap on the chat and delete it from the list
- Join the same chat
- Tap `Fetch more messages`

### Additional Information

- Status version: Nightly 26/01
- Operating System: Android, iOS

**Comment by cammellos** [comment]
This is due to the added message caching, we should be clearing the cache when this happen.
I will take a look  at it

**Comment by jakubgs** [comment]
Not sure if this is the same issue, but if you use `Clear history` and then `Fetch messages` the same thing happens: nothing.

**Comment by cammellos** [comment]
same issue, yes

**Comment by cammellos** [comment]
This should be fixed now
