### ISSUE TITLE
[Android] Register 2nd password Autofill does not work & no paste option available

### ISSUE THREAD

**Issue by linceaerian** [status-im/status-react#11708]
# Bug Report

First of all, Hello Maintainer & Devs :)

## Problem

Second password prompt during register attempt does not accept "paste" (not shown in interface)
and does not trigger "Autofill" correctly.

#### Expected behavior

Either having autofill working or at least being able to paste the password.

#### Actual behavior

![Screenshot_2021-02-03-08-59-33-265_im status ethereum](https://user-images.githubusercontent.com/1318470/106716881-409c8f00-65ff-11eb-9e4e-c0c46bd1f380.jpg)

Autofill does not trigger anything, no paste option: have to manually input passphrase from Password Vault.

#### Notes

No related issue found.

#### Acceptance Criteria

Having either paste accepted in this field or autofill.

### Reproduction

- Open Status on a new device
- Click "Get stated"
- Click "Generate keys"
- Choose a chat name among the one provided
- Click "Next"
- Click "Next" (use default field "This device")
- Try to input password from "Autofill" in first password field (long press), it works and unlock second field
- Try to input password from "Autofill" in second password field (long press), "but nothing happens"
- Observe that no "paste" option is available in the 2 fields.

### Additional Information

- Status version: PlayStore latest (1.10)
- Operating System: MIUI 12.0.2 = Android 9
- Password Vault: Enpass

#### Logs

No logs available (No crash log detected, it seems no Error linked to application was visible either for the Autofill).

Lastly, Thanks for reading ! ;)

**Comment by churik** [comment]
@linceaerian thank you for logging the issue!
It is not relevant anymore on 1.15, but please feel free to reopen the issue if you still experience it
