### ISSUE TITLE
signing typed data with wrong chain ID fails without proper error message

### ISSUE THREAD

**Issue by bitgamma** [status-im/status-react#11706]
# Bug Report

## Problem

When signing a typed message, the chain ID is part of the message being signed. If this differs from the currently selected network, hashing the message fails (correctly). However this failure is not caught/shown anywhere and the user is still prompted to tap their card. At this point the process stalls, with the NFC prompt showing "Processing" forever. The user can only cancel, but likely will have no idea why this happens.

If the chain id matches the current network everything works normally.

### Additional Information

Test on release 1.10.1, develop branch from 02.02.2021 and PR11540. PR11540 tested on iOS as well.

**Comment by churik** [comment]
@bitgamma I believe that is the reason why signing in to CryptoKitties is not working with keycard?
![IMAGE 2021-02-05 10:26:32](https://user-images.githubusercontent.com/4557972/107015011-9f4b3f80-679c-11eb-81c1-50ae2fd005cd.jpg)
After signing I see that user was signed out immediately, so dapp not usable with keycard on nightly 05/02/21

**Comment by bitgamma** [comment]
@churik yes this is probably related. I will investigate those issues together

**Comment by churik** [comment]
actually I deleted comment because after 3d attempt I could login normally, so not sure what happened. also will investigate from my side

**Comment by bitgamma** [comment]
turned out to be more of an UX problem, I updated the description accordingly. I also separated the other issue which I was investigating together with this since they turned out not to be related.
