### ISSUE TITLE
App crashes if delete Demo bot from Contacts

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1170]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: App crashes if delete Demo bot from Contacts, 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Demo bot is deleted from Contacts. Contacts screen is shownin edit mode
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashes
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Contacts
- Edit Contacts
- Delete Demo bot

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6-60
* Operating System: Android and iOS

#### Logs

[20170505125328-logcat.txt](https://github.com/status-im/status-react/files/978796/20170505125328-logcat.txt)

**Comment by GustavoNunes** [comment]
Debugging through the REPL, I traced the error to the `:commands` and `:responses` keys inside the Demo Bot contact map, and also the `:params` keys inside `:commands` and `:responses`. It appears that these keys' values must be vectors of maps, like this:
```
:commands [ {:name "location" ...} {:name "request" :params [{:name "amount" ...}]} ]
```
Only when the contact map had this structure that the type errors from Realm disappeared.
However I couldn't translate this to an actual fix. I tried to fix it [here](https://github.com/status-im/status-react/blob/develop/src/status_im/data_store/contacts.cljs#L9) but kept running into issues, so I decided to leave it for now.

**Comment by GustavoNunes** [comment]
Also: to reproduce this bug with a new account, I had to log out after creation then log in again. I noticed that after logging in again, the structure of the Demo Bot contact map changed (from 16 keys to 19, some of them changed).
When I tried to delete the Demo Bot just after creating the account, it was deleted successfully without error.
