### ISSUE TITLE
Let waku broadcast mode as option for send message

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11712]
# Feature Issue
I know waku protocol is main feature of this project more secure, decentralized and p2p. But the waku broadcast eating too much battery and data usage. Maybe, let whisper waku broadcast as option mode in setting (Users can enable or disable the feature) for messaging, it can be increase the usability.
And add additional layer in waku protocol, direct p2p(not broadcast) the message to receiver.

Thanks;
I don't have too much knowledge about developing. If I thinks wrong, ignore it.
🏋
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by oskarth** [comment]
We agree that bandwidth usage is a problem for Waku v1! Current development is happening under Waku v2. See:

https://vac.dev/waku-v2-plan and https://github.com/status-im/nim-waku/

**Comment by cammellos** [comment]
Closing this for now, thanks @oskarth for answering and thanks @johndejohn for the question
