### ISSUE TITLE
Mentions are not counted when shortening long messages

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11710]
# Bug Report

## Problem

If paste to the input field a message with a length of 4096 chars, it will be impossible to continue typing. But if delete one char, type `@`, and select any mention from the suggestions list, it will be inserted into the message, although its length will be >4096 chars.

Also, if send a message containing >30 mentions it will be sent, but **will never be received by the recipient**, as well as the '4096 chars+mention' message.

<img width="236" alt="Screenshot 2021-02-03 at 16 39 03" src="https://user-images.githubusercontent.com/67952253/106770505-59786500-663e-11eb-8744-def1d70683a8.png">

#### Expected behavior

- Cannot send any message longer than 4096 chars
- Messages with a lot of mentions are shortened, as well as plain-text ones

#### Actual behavior

https://user-images.githubusercontent.com/67952253/106770935-bf64ec80-663e-11eb-95a7-38a3f446a8a2.mp4

### Reproduction

Case 1:
- Open chat
- Paste message 4096 chars long
- Delete last char
- Type `@`
- Select any mention from the list
- Send the message and check it on another device

Case 2:
- Enter more than 30 mentions to the input field
- Send the message
- Check the recipient's device

### Additional Information

- Status version: Nightly 03/02
- Operating System: Android, iOS

**Comment by churik** [comment]
still relevant on 27/07/2022

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
