### ISSUE TITLE
We shouldn't allow to delete Wallet and Browse contacts. Currently if delete then app crashes

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1171]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, app crashes if try to delete Wallet or Browse from Contacts. It should not be possible to delete these contacts

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
We should not allow to delete Wallet and Browse from Contacts. It can be done in different ways (e.g. do not show Delete option)
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashes if try to delete Wallet or Browse from Contacts
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Contacts
- Edit Contacts
- Delete Wallet or Browse

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6-60
* Operating System: Android and iOS

**Comment by flexsurfer** [comment]
@annadanchenko and also console shouldn't be deleted

**Comment by flexsurfer** [comment]
still possible to delete these contacts from their profiles

**Comment by flexsurfer** [comment]
Reproduction

Open Status
Open Console Profile
Edit Profile
Delete Contact
