### ISSUE TITLE
Mention in push notification is displayed as chat key on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11711]
# Bug Report

## Problem

Mention in PN is displayed as chat key, instead of a 3-random user name or ENS.

#### Expected behavior

A 3-random user name or ENS is shown in PN

#### Actual behavior

<img width="356" alt="Screenshot 2021-02-03 at 17 37 57" src="https://user-images.githubusercontent.com/67952253/106778721-8f214c00-6646-11eb-95fd-4ce3bdc2bb90.png">

### Reproduction

Device A (Android):
- Enable PNs

Device B:
- Start 1-1 chat with Device A
- Send a mention

Device A:
- Pull the PN down to check

### Additional Information

- Status version: Nightly 03/02
- Operating System: Android

**Comment by churik** [comment]
not reproducible on nightly 12/02 in 1-1, group and public chats
