### ISSUE TITLE
Improvements for remote push notifications on Android and iOS: add sound, redirect to the chat, show a content in PN

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11715]
### User Story

As a user, I want:

- Сan tap PN and be redirected to the chat
- Can see the content of the message in PN
- Can receive push notifications with sound

### Description

When tapping on notification, app is opened, after log in, chat is opened in which the user received a message.
When a notification is received, it displays the message content.
User can set sound for PNs in settings.

### Notes

The original feature request was received in the user report.

**Comment by tinyluck** [comment]
It is more convienent if we have push notification sound on iOS. (On Android, the sound could be configured by system settings)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
