### ISSUE TITLE
[Spike] Investigate using a replacement for RN FlatList

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11724]
# Problem

As part of https://github.com/status-im/status-react/issues/6375
we started hitting some FlatList limitations.
The one that we most struggled with is inserting messages on both ends so we can implement pagination on both sides.
In this spike we should try out different react native list implementations to see if there's a suitable replacement out-of-the-box.

## Acceptance criteria

- LIst should be performant
- We should be able to paginate both sides
- We should be able to maintain scroll position

Please timebox it to a suitable time.

**Comment by flexsurfer** [comment]
we could look at this component : https://github.com/Flipkart/recyclerlistview

**Comment by flexsurfer** [comment]
How Discord achieves native iOS performance with React Native: https://blog.discord.com/how-discord-achieves-native-ios-performance-with-react-native-390c84dcd502

Current implementation: https://notes.status.im/-iLVTV7ESK68JCFc0AzvmQ?both

**Comment by cammellos** [comment]
closing this as completed
