### ISSUE TITLE
No connection with Keycard when sending transaction on Galaxy S20

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11729]
# Bug Report

## Problem

On Galaxy S20 (Android 11) when I try to sign transaction, - on the step to hold the card -  the Keycard is not recognised. It keeps the message 'Still looking for card...'. Neither haptic feedback occurs.   
However, if I turn OFF and back ON the NFC reader from setting and again hold the card - keycard recognised fine.
It's not happening when login in to account or changing PIN from setting but when sending transaction it reproduced all the time.

Also there is no such issue on: Galaxy S8(Android 9), Galaxy J7 (Android8), GooglePixel2 (Android 11)
It seems it device specific (i.e. Galaxy S20 so far, maybe some other devices) 

#### Expected behavior

Keycard connected fine when signing transaction on Galaxy S20

#### Actual behavior

When holding keycard to sign transaction on Galaxy S20, card is not visible to Status (only NFC restart helps).

<img width="236" alt="Screenshot 2021-02-09 at 15 02 46" src="https://user-images.githubusercontent.com/8749671/107367379-e52f3d00-6ae7-11eb-9201-95cb2ce15971.png">

Video: https://drive.google.com/file/d/1qYS9VHXL9UOxdRxrjEQkWS4yO_I0wpCb/view?usp=sharing

### Preconditions:
Empty Keycard is ready for use

### Reproduction
- Install Status on Galaxy S20
- Recover account with assets and choose Keycard as storage
- Navigate to Wallet -> Send transaction
- Enter valid values in amount, address and proceed by tapping Next
- Tap `Sign with Keycard` button and enter valid PIN
- Hold the card to the phone

### Additional Information

- Status version: Release 1.10, 1.11
- Operating System: Galaxy S20 specific (Android 11) 

#### Logs

Full device logcat when holding keycard here: 
[Keycard_on_Galaxy_S20.txt](https://github.com/status-im/status-react/files/5951564/Keycard_not_seen_Galsxy_S20.txt)

**Comment by flexsurfer** [comment]
ping @bitgamma

**Comment by bitgamma** [comment]
@Serhy could you try also the build at https://github.com/status-im/status-react/pull/11540 ? since there have been some changes to connection handling on the Android side as well, it would be interesting to see if it has any effect

**Comment by Serhy** [comment]
@bitgamma yes, it's indeed all good with latest build (https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210209-143341-9ee9f5-pr-universal.apk) from #11540 
Great, thanks for update! 
I keep this issue open though, until #11540 is merged.

**Comment by bitgamma** [comment]
@Serhy #11540 just merged

**Comment by Serhy** [comment]
Thanks @bitgamma ! Can't reproduce anymore this bug with develop build on Galaxy S20.
Closing this issue.
