### ISSUE TITLE
Different account restored after "Move keystore file" to keycard on Galaxy S20

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11735]
# Bug Report

## Problem

When moving multiaccount keystore file to keycard with respective feature, - there is a different account restored from the same seed phrase which were used for multiaccount recovered on device keystorage.
However on login screen I see "correct" account (public key), - after login in to it there is a different address and public key. For note: this "different" account is always the same on reproduction of Galaxy S20. It's like using another derivation path (it's not because I see it's same m/44'/60'/0'/0/0 in all cases for account setting

No issue on Android 11 (Google pixel 2), Android 8. So far it's Galaxy S20 and Galaxy S8.

NOTE: it happens with only my own account. Reproduced on Galaxy S20 and Galaxy S8. But Galaxy J7 looks good with it (it's on Android 8)
I checked another account on Galaxy S20 and they were ok. Also I tested this account on another device with the same build and it's all OK too (i.e. the same account recovered after moving keycard keystore storage)
  
#### Expected behavior

There is the same account when same seed phrase moved to keycard keystore file

#### Actual behavior

Different accounts when same seed phrase moved to keycard keystore file

### Precondition 
Empty keycard ready for use exists

### Reproduction

- Open Status and recover multiaccount
- Log out of this account 
- Open login screen of this account
- Tap three dots menu at the top-right
- Select `Manage keys and storage` -> Move keystore file -> `Enter seed phrase`
- Enter the same seed phrase (so use above)
- Select `Keycard` -> `Confirm` -> `Move and reset`
- Begin setup
- Finish all keycard onboarding processes
- Check address and public key whether it's different

**Actual result:** (pay attention to username which is different)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/8749671/107533994-2b5bcd80-6bc8-11eb-9b8b-5da3c0bb44fc.gif)

### Additional Information
- Status version: release 1.11
- Operating System: Android 11 (Galaxy S20), Android 9 (Galaxy S8) with specific account

#### Logs

Full device logcat starting from 'Move keystore file' keycard storage flow 
[Keycard_diff_accc.txt](https://github.com/status-im/status-react/files/5959203/Keycard_diff_accc.txt)

**Comment by Serhy** [comment]
@bitgamma if you may suggest where I can look more here let me know please. 
Also, I retested that scenario with my account seed phrase in (https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210209-143341-9ee9f5-pr-universal.apk) from #11540 and it reproduced there.

**Comment by Serhy** [comment]
It turns out the reason of above issue is in pasting of seed phrase from clipboard. 
If I type seed phrase then all behaves fine.
'Enter seed phrase' UI behaves correctly if user has entered whitespace at the beginning/end, or different seed phrase - the error pop-up 'Seed phrase is not match' appears. But in my case seed phrase correct and no any UI errors. Additionally the same approach with another accounts works well.

**Comment by shivekkhurana** [comment]
@Serhy What happens if you logout of this restored (Complete Disguised Jackal) ? Do you see this on the multiaccount list or the original account (Lightsalmon Wry Javalina) ? 

If you see "Lightsalmon Wry Javalina", and you login again, what do you see on the profile page?

**Comment by Serhy** [comment]
@shivekkhurana Yes, when login out or Force Stop of Status and opening Status - there is always on login screen `Lightsalmon Wry Javalina` (original correct account) and `Complete Disguised Jackal` on Profile screen after login in.

Another note: after all above steps when we migrated to Keycard, -if I recover my original account with seed phrase - it recovers fine. Mean that inside DB there is a different private key stored for account after migration to keycard.
This how it looks on Login screen then:

<img width="254" alt="Screenshot 2021-02-12 at 16 13 29" src="https://user-images.githubusercontent.com/8749671/107792142-78bd7380-6d5d-11eb-8242-e88d7686f418.png">

Where Keycard version of `Lightsalmon Wry Javalina` is just like UI glitch because next observation below:

Then, I used this Keycard with migrated account to recover account on another devices (including device where there were no issues) - and in that case it recovers everywhere that wrong `Complete Disguised Jackal` account. 

If we have ability to export Private key in Status - I'd at least export private key of `Complete Disguised Jackal` and then reveal seed phrase of it to see how it different from my original account...

**Comment by shivekkhurana** [comment]
This is really weird and abrupt. As of now, the Keycard migration process is just the "Restore using seed phrase" flow without the initial steps. 

The image that you posted with the same account stored on Keycard and the device is an illegal state and should never occur. 

1. Were you able to reproduce this step with other seed phrases?
2. Can you send me the seed phrase of `Lightsalmon Wry Javalina` on Discord ? I want to try and reproduce it on my device.

**Comment by Serhy** [comment]
Hey @shivekkhurana as discussed on Discord I'm not really comfortable to share my account seed phrase for now :) 
I also tried several more different seed phrases and they behaved fine.
Also, I noticed one thing: 
On the main Seed Phrase recovery view (`Open Status` -> `Access Existing keys` -> `Recover with seed phrase`) we trim seed phrase value when entered. So if there are whitespaces at the beginning or end or empty lines - we ignore and use only seed phrase value. 
However, when moving account to Keycard storage (`Account login` -> `...` -> `Manage keys and storage` -> `Enter seed phrase`) - there is no seed phrase trim function (in a case I recover seed phrase with whitespaces - it responds 'Seed doesn't match'.

This means to me we are using different module/view/function in last scenario than first. And maybe that can fix the original issue I have.
Could you check the difference between above two seed phase recover views and try to alight seed phrase parsing (so that we have `Manage keys and storage`'s sedd phrase view behave the same to main account recovery flow seed phrase view).
In any case i'd say that's also and issue that we don't have seed phrase trimming when moving account to Keycard.

**Comment by shivekkhurana** [comment]
@Serhy I have fixed the other issue that you pointed, but have not been able to reproduce the "different account being restored" issue. 

Can we mark this as stale and look into it if there are further reports? Or do you want to keep this open and try to reproduce with other seed phrases?

**Comment by Serhy** [comment]
Closing this issue for now, @shivekkhurana, thanks for fix #11939 
It didn't fix the issue so I mark it as stale, will open once reproduce with one more seed phrase.

**Comment by churik** [comment]
Closing as stale
