### ISSUE TITLE
Remove image metadata before sending

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11737]
As a user
I want the app to remove any image metadata before sending
So I don't have to disclose it when sending images

### Description
All the metadata should be removed before sending an image

### Technical implementation 

https://github.com/scottleedavis/go-exif-remove is an example, we don't have to use the library necessarily but might help

**Comment by flexsurfer** [comment]
its already removed when we resize and compress image https://github.com/status-im/status-react/issues/10769

**Comment by cammellos** [comment]
Oh thanks, a user mentioned that it wasn't so I assumed it wasn't :) 
I'll get back to them!
