### ISSUE TITLE
Public chat hastag # name input other languages

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11731]
# Feature Issue
![Capture+_2021-02-10-04-57-13.png](https://user-images.githubusercontent.com/40263018/107453683-7e983680-6b5c-11eb-8fba-d8670548ff5d.png)

### User Story
As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description
[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
_Summary_: ...

### Acceptance Criteria
[comment]: # (Rules for the future PR to be accepted.)

### Notes
[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by cammellos** [comment]
Thanks, we don't allow characters for security reasons as it would make easier to spoof chat names
