### ISSUE TITLE
Error when redeeming TORN token from tornado.cash

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11742]
# Bug Report

## Problem

Originally reported by user that he is not able to redeem TORN tokens using the status wallet. transaction failing with the following error: 

`cannot unmarshal non-string into Go struct field SendTxArgs.value of type *hexutil.Big`

Can't reproduce because I don't have TORN tokens to redeem :(

#### Expected behavior

Can redeem vTORN tokens from https://app.tornado.cash/airdrop/

#### Actual behavior

`cannot unmarshal non-string into Go struct field SendTxArgs.value of type *hexutil.Big` error when redeem tokens from https://app.tornado.cash/airdrop/

### Preconditions
Address with vTORN tokens available to redeem exists

### Reproduction

- Open Status and recover an account with vTORN tokens available to redeem
- In Browser -> open `https://app.tornado.cash/airdrop/` dapp
- Click top-right `...` -> 'Connect' -> `Web3 wallet` -> `Allow`
- Click `Redeem`
- Sign and send transaction

### Additional Information
- Status version: release 1.10
- Operating System: Android and iOS

**Comment by Serhy** [comment]
Attached [geth.log](https://github.com/status-im/status-react/files/5980790/geth.log) and [Status.log](https://github.com/status-im/status-react/files/5980791/Status.log) from user report

**Comment by churik** [comment]
linked here another issue with same dapp #11565

**Comment by churik** [comment]
Closing, as page doesn't exist anymore
