### ISSUE TITLE
Add support for the WalletConnect protocol

### ISSUE THREAD

**Issue by adamsoffer** [status-im/status-react#11746]
# Feature Issue

### User Story
As a user, I want my Status wallet to support the WalletConnect protocol so that I can use my wallet inside defi desktop and mobile dapps such as Zerion.

**Comment by cammellos** [comment]
Thanks for the feature request, currently wallet connect 1.0 relies on a centralized server, so we are opting and working together with the creators of wallet connect 2.0 for a protocol built on waku.
cc @oskarth 

Closing for now as will be tracked somewhere else.

**Comment by caffeinum** [comment]
Is it possible to allow user to connect to selected server of his choice to use this? What's the update for the wallet connect 2.0?

@cammellos 

Edit:

Found my answers here
https://github.com/status-im/status-react/pull/13032
https://github.com/status-im/status-react/pull/12701
