### ISSUE TITLE
Chat id route

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11745]
# Feature Issue
./src/status_im/router/core.cljs

The public and group chat Id routing in or from  join.status.im ? and it can be route to decentralise ?

![Screen Shot 2021-02-14 at 04.33.28.png](https://user-images.githubusercontent.com/40263018/107866599-ac92b900-6e83-11eb-972b-4751a824f01d.png)

### User Story

As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by cammellos** [comment]
> The public and group chat Id routing in or from join.status.im ? and it can be route to decentralise ?

Unfortunately that's not possible, as universal links don't allow it. Though if you have the app already installed it won't be hitting the https endpoints.

Thank you
