### ISSUE TITLE
Let user change language in Settings

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11751]
# Problem
It is often difficult for translation contributors to see the context in which copy appears, as a result translations don't always fit context or UI. Allowing translation contributors to easily switch language in the app helps them review and adapt copy in context

## User story
As a translation contributor I want to view the app in my native language, without having to change the language settings of my phone, because it makes it easier for me to review copy

![Screenshot_20210214-220736_Status](https://user-images.githubusercontent.com/35233054/107972075-984dd980-6fb3-11eb-8894-3d77a76ed1ad.jpg)

## Acceptance Criteria

- User can set preferred language in Settings
- Default language is set to device language
- Preferred language setting persist when closing and reopening the app

## Notes
Changing language setting helps find and correct translations where needed. More convenient would be to view screenshots for all new copy in Lokalise when translating. Unfortunately, this requires a lot of manual work. Any way to automate could also be a good solution

cc @jinhojang6

**Comment by churik** [comment]
closing due to re-design
