### ISSUE TITLE
Bottom bar not showing well in dark/light appearance

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11755]
# Problem
![Capture+_2021-02-16-18-04-29.png](https://user-images.githubusercontent.com/40263018/108081451-09f45900-7082-11eb-91ce-ff35c54fd7b4.png)
![Capture+_2021-02-16-18-05-00.png](https://user-images.githubusercontent.com/40263018/108081482-1082d080-7082-11eb-8ee6-432512c0664c.png)

## Implementation
Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria
Rules for the future PR to be accepted.

## Notes
Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps
Steps which should be taken after this issue has been resolved.

**Comment by flexsurfer** [comment]
thanks @johndejohn could you tell phone model and android version

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/pull/10846/files

**Comment by johndejohn** [comment]
> thanks @johndejohn could you tell phone model and android version

I tested LG G6 and Samsung S10+
Android 9 and One UI

**Comment by flexsurfer** [comment]
thanks, @churik @Serhy  did we break it at some point?

**Comment by churik** [comment]
Works for me as expected on Android 10 (Xiaomi Mi Note 9 pro)
@Serhy @qoqobolo please check on your devices also, thanks.

**Comment by johndejohn** [comment]
Now looks working well some unknown reason in dark mode

I just restart the phone.

![Capture+_2021-02-18-01-59-36.png](https://user-images.githubusercontent.com/40263018/108279029-01d51000-718d-11eb-9256-8f7b350140ee.png)

**Comment by qoqobolo** [comment]
It looks fine on Google Pixel 2 (Android 11) as well.

**Comment by errorists** [comment]
@flexsurfer hey any ideas what's up with the `+` icon next to `Add to contacts`, why it's so big?

**Comment by flexsurfer** [comment]
@errorists OMG, have no idea
