### ISSUE TITLE
"Manage keys and storage" screens show top padding (or margin) 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11765]
# Bug Report

## Problem
Leftover from https://github.com/status-im/status-react/pull/11540#issuecomment-780611335

## ISSUE 16: all screens in "Manage keys and storage" should be aligned with design.
![photo_2021-02-17 15 54 13](https://user-images.githubusercontent.com/4557972/108221737-6914a500-7138-11eb-8a1f-302780260517.jpeg)
<img width="579" alt="photo_2021-02-17 15 50 06 jpeg 2021-02-17 15-52-58" src="https://user-images.githubusercontent.com/4557972/108221838-82b5ec80-7138-11eb-8700-dc748bb6d549.png">

**Comment by shivekkhurana** [comment]
<img width="388" alt="Screenshot 2021-02-23 at 5 47 21 PM" src="https://user-images.githubusercontent.com/1925158/108842382-328ace80-75ff-11eb-8374-76a59b35ad50.png">

https://discord.com/channels/624205794384281629/626738033701683200/813745275083948092
