### ISSUE TITLE
Adding iCloud Photo Library photo as profile picture hangs app on iOS 

### ISSUE THREAD

**Issue by benmorrow** [status-im/status-react#1176]
### User Story

As a user, I want to change my profile picture so that I am identifiable.

### Description

*Type*: Bug

*Summary*: Tried to set my profile photo by selecting a photo from the iOS gallery. A modal, blocking activity indicator is stuck on "Processing assets..."

![img_0209-2](https://cloud.githubusercontent.com/assets/5604/25883827/98a283c6-3502-11e7-8df8-15feba26c2ab.png)

#### Expected behavior

Profile photo gets set immediately.

#### Actual behavior

Modal, blocking activity indicator is stuck on "Processing assets..."

### Reproduction

1. Open Status for iOS
2. Navigate to your user profile
3. Tap on the "..." button in the upper right
4. Tap "Edit"
5. Tap the profile photo with "Edit" overlay
6. Tap "Select from gallery"
7. Select the any album
8. Select one photo that you haven't looked at in a long time. Photo should be stored on iCloud rather than locally on the device.
9. [App is now stuck and you cannot cancel the modal]

### Solution
Two options:
1. Have a timeout and error message
2. Figure out how to fetch an iCloud Photo Libray photo in a timely manner

### Additional Information
* Status version: 0.9.7d64
* Operating System: iOS 10.3.1

**Comment by rasom** [comment]
I can't reproduce this on iphone 6s. @annadanchenko could you please test this?

**Comment by asemiankevich** [comment]
I can't reproduce it, iOS 10.3

**Comment by lukaszfryc** [comment]
@rasom @asemiankevich I'm able to reproduce it on latest nightly (March 1). When I try to use an iCloud Photo the screen freezes and you need to kill the app.

Should we reopen it to investigate more?
