### ISSUE TITLE
Allow copying and pasting of images in chat's input

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#11760]
# Problem

Scope of this issue is to allow pressing in the chat input to evoke the native actions tooltip, select paste from it (if an image is present in clipboard) and following that, this image would be loaded into the input as if it was selected from other sources (gallery, camera).

## Implementation

[Design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=6990%3A226)

Multiple images should be allowed to be pasted and placed in queue. Should be available for any supported image

## Acceptance Criteria

Scope of the issue was correctly implemented and works with any supported images

![screen-2 (2)](https://user-images.githubusercontent.com/1017008/128211896-03572953-4396-4aac-b1ef-1ad178ed5a4f.png)
![screen-1](https://user-images.githubusercontent.com/1017008/128211159-f029daec-c562-43de-a638-57d781e67146.png)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
