### ISSUE TITLE
Implement swipe-to-delete gesture in chat view

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11767]
As a user
I want to be able to swipe on a chat in the home view and delete a chat
So that I can delete a chat quickly

### Description

A user should be able to delete a chat by swiping on it on the home view.

We want any of the `quo/list-item` to be able to have this functionality, so the component should be generic. 

It's fine for the scope of this task to just remove the chat from the re-frame db without calling `status-go` (it will be populated again eventually), but otherwise is fine to call `wakuext_deleteChat`.

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
