### ISSUE TITLE
NFC connection errors at attempt to use keycard on IPhone 7

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11772]
Leftover from #11540 
In general connection is unstable, and to create multiaccount I could from 4th attempt (NFC reader on device is working, can use it in other applications)
After creating account couldn't login.

Tried > 5 times - no successful login after you log out from app.
Once got crash.

**Steps:**
1) restore multiaccount from seed phrase (store on keycard)
2) log out
3) try to login

**Expected result:** can login

**Actual result:** connection error or "Connected. Don't move your keycard" and app freeze after background. Once got crash.

Video:  https://user-images.githubusercontent.com/4557972/107061591-ab54f280-67d8-11eb-8e79-8e249520d5bb.mp4
Logs: [status_logs.zip](https://github.com/status-im/status-react/files/5933934/status_logs.zip)

**OS:** IOS 13.5.1, IPhone 7

**Comment by guylouis** [comment]
closing this because we can't solve it technically, it's now a matter of communicating well to users
