### ISSUE TITLE
App crash on attempt to delete a contact (happens not for all accounts)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1177]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: App crashes it try to delete Auction House from Contacts. It's reproducible only on 1 account atm.
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7dHRkZUZXMGJjdEU

I could get to 2 more accounts with same issue  but unfortunately, do not have clear steps. So far, all of them have these steps in common:
1. Phone number added and contacts imported from phone
2. New contact added by scan QR that appears on top of the Contacts list 
3. I've added one new group of contacts, then modified it by adding/removing members. I've also re-ordered  this group with default ones. At the end this new custom group was deleted. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Contact is deleted
#### Actual behavior
[comment]: # (Describe what actually happened.)
app crashes
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Contacts
- Tap "..." in top right corner
- Tap Edit
- Tap "..." net to  Auction house and tap Delete contact -> app crashes
It also happens if try to delete other contacts, e.g. "bchat"

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d64
* Operating System: iOS 10.3.1

#### Logs

[20170505215713-consolelog.txt](https://github.com/status-im/status-react/files/980219/20170505215713-consolelog.txt)
crash log: 
[StatusIm-2017-05-05-215732.crash.txt](https://github.com/status-im/status-react/files/980223/StatusIm-2017-05-05-215732.crash.txt)

**Comment by vmutius** [comment]
Works fine for me. No crash. Just deleted the contact

**Comment by flexsurfer** [comment]
fixed by https://github.com/status-im/status-react/pull/1197
