### ISSUE TITLE
Enable keeping database when migrating account to keycard

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11777]
relates to #11431 "Migrate account to a regular keycard from logged out "Manage keys and storage"

When solving #11431 we intentionally left out the case where the user wants to keep its data base when migrating. So the user is forced to reset its database and the check box is checked and greyed out in flow like this https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8218%3A7450

This issue is about enabling the user to keep its database
- having "reset database" unchecked by default 
- letting the user checks it or not 

Figma design 
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8218%3A8089

**Comment by shivekkhurana** [comment]
This feature requires a "password reset" feature as a foundation. ~I wasn't able to find an issue for that~ Issue link: https://github.com/status-im/status/issues/48
