### ISSUE TITLE
Wallet pop-up Ui in dark mode

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11789]
Looks there need to the pop-up corner framing will better in dark mode.

# Problem
![Capture+_2021-02-24-00-29-21.png](https://user-images.githubusercontent.com/40263018/108911033-bf517e80-7637-11eb-97bc-6dc092294dba.png)

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by hesterbruikman** [comment]
@errorists is this issue already included in #10721?

I found bottom sheet styling there, but no popup styling, not sure if the same can be applied

**Comment by churik** [comment]
closing as included in #10721
