### ISSUE TITLE
Communities issues

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11797]
Umbrella issue for leftovers from https://github.com/status-im/status-react/pull/11566

### 1. Reply option is shown on read-only chats on long tap on messages

 **Steps:**
 - as user A: create community (require approval), create chat and send some message
- as user B: import community, join
- as user B: long tap on message in chat
**Expected result:**
Reply is not available
 **Actual result:**
![IMAGE 2021-02-22 15:55:56](https://user-images.githubusercontent.com/4557972/108725230-7362e480-7526-11eb-8515-c3c2a933d732.jpg)

 ### 2. Can't set image from gallery as community icon (IOS only)
https://user-images.githubusercontent.com/4557972/108726643-f173bb00-7527-11eb-84d9-1546d816a9e7.mp4

 ### 3. Navigation: back from chat brings you to the chat list instead of chats inside community
 **Steps:**
 - as user A: create community, create a chat inside it, send several messages
- as user A: tap back
**Expected result:**
community with chats
 **Actual result:**
general chat list

 ### 4. Navigation: leave community from "Members" page doesn't redirect you to chat list
 **Steps:**
 - as user A: create community 
- as user A: open ... > tap on community name
- as user A: tap on leave community
**Expected result:**
redirected to home view
 **Actual result:**
need to go back manually

### 5. Placeholder for empty community says about + button 
Should be replaced 
![IMAGE 2021-02-22 16:01:59](https://user-images.githubusercontent.com/4557972/108726058-4bc04c00-7527-11eb-8b95-27354fd88446.jpg)

### 6. For community without picture icon colors are different 
 **Steps:**
 - as user A: create community 
- as user A: open ... 
![Monosnap 2021-02-22 16-02-41](https://user-images.githubusercontent.com/4557972/108726374-a3f74e00-7527-11eb-8efd-d0a202ea44b8.png)

### 7. Invitations in 1-1 chat: preview - upgrade to latest version to see community preview, custom icons are not shown, the description doesn't fit message bubble

 **Steps:**
 - as user A: create community 
- as user A: open ... > Share > send it to User B (should be added as your contact)
- as user B: check out the invite

![Monosnap 2021-02-22 16-12-40](https://user-images.githubusercontent.com/4557972/108727463-e79e8780-7528-11eb-9205-410b6282e1f6.png)
Custom image / description:
![Monosnap 2021-02-22 16-12-40](https://user-images.githubusercontent.com/4557972/108727613-0e5cbe00-7529-11eb-88c8-1e73173fb95c.png)
Preview
![Monosnap 2021-02-22 16-13-55](https://user-images.githubusercontent.com/4557972/108727563-03099280-7529-11eb-8498-df89eebfe683.png)

### 8: no outgoing invite message is shown in 1-1 chat if sharing it to  user via public key
**Steps:**
1)  create community (no membership requirement)
2) options -> share
3) paste valid public key
4) tap invite

**Expected result:**
outgoing invite in 1-1 chat 
**Actual result:**
outgoing invite in 1-1 chat is not shown in chat view, but it is shown in preview

### 9. "No membership" by default when creating community 
https://github.com/status-im/status-react/pull/11566#issuecomment-785270618

## Acceptance criteria

Fixed following issues

- [ ] 1. Reply option is shown on read-only chats on long tap on messages
- [ ] 2. Can't set image from gallery as community icon (IOS only)
- [ ] 3. Navigation: back from chat brings you to the chat list instead of chats inside community
- [ ] 4. Navigation: leave community from "Members" page doesn't redirect you to chat list
- [ ] 5. Placeholder for empty community says about + button
- [ ] 6. For community without picture icon colors are different
- [ ] 7. Invitations in 1-1 chat: preview - upgrade to latest version to see community preview, custom icons are not shown, the description doesn't fit message bubble
- [ ] 8. no outgoing invite message is shown in 1-1 chat if inviting user via public key
- [ ] 9. "No membership" by default when creating community

**Comment by flexsurfer** [comment]
Fixed following issues

- [x]  1. Reply option is shown on read-only chats on long tap on messages
- [x]  2. Can't set image from gallery as community icon (IOS only)
- [x]  3. Navigation: back from chat brings you to the chat list instead of chats inside community
- [x]  4. Navigation: leave community from "Members" page doesn't redirect you to chat list
- [x]  5. Placeholder for empty community says about + button
- [x]  6. For community without picture icon colors are different
- [x]  7. Invitations in 1-1 chat: preview - upgrade to latest version to see community preview, custom icons are not shown, the description doesn't fit message bubble
- [x]  8. no outgoing invite message is shown in 1-1 chat if inviting user via public key
- [x]  9. "No membership" by default when creating community
