### ISSUE TITLE
Keycard icon overlaps long 3 random name on "Your keys" screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11795]
# Bug Report

## Problem

Keycard icon overlaps long 3 random name on "Your keys" screen

#### Expected behavior

Line break or dots at the end of a long name

#### Actual behavior

Device: iPhone SE

<img width="356" alt="Screenshot 2021-02-25 at 11 13 49" src="https://user-images.githubusercontent.com/67952253/109138324-8a8a1800-775a-11eb-8308-77ef90c1021d.png">

### Reproduction

- Create keycard multiaccount
- Log out

### Additional Information

- Status version: Nightly 25/02
- Operating System: Android, iOS

**Comment by churik** [comment]
@bitgamma @gravityblast  please, take a look if you have a chance, thank you!

**Comment by bitgamma** [comment]
is this really iOS only or can it be reproduced on Android devices with low-res screens?

**Comment by flexsurfer** [comment]
its not an ios issue, we had it before for long names , so i guess its fine, it should be fixed in list component

**Comment by bitgamma** [comment]
Fixed by #12471
