### ISSUE TITLE
Notification settings for mentions on Android

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11808]
Relates to #11213 

This issue is about allowing users to setup in notifications preferences in android, how they want their @mentions notifications

- [ ] User can disable Show @mentions in Notification preferences on Android

- [ ] When `Show @mentions is disabled, local notifications are no longer received

- [ ] User can Hide message content and sender in Notification preferences on Android

- [ ] When hide content and sender is disabled, notification shows Someone mentioned you

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
