### ISSUE TITLE
Remove or upgrade react-native-device-info to 7.4.0

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#11809]
# Description

The dependency on `react-native-device-info` is causing our APK to include Google dependencies that we do not use or want.

Because of this we were force to make a separate branch called [`fdroid-release/1.11.x`](https://github.com/status-im/status-react/tree/fdroid-release/1.11.x) as a [dirty fix](https://github.com/status-im/status-react/commit/f010a0cd8897077bfc9b8864cdb019ae8655bdf0) to the Google dependencies blocking inclusion of our app in the [F-Droid](https://f-droid.org/) application directory as part of [fdroidata#7179](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7179).

# Requirements

As [suggested](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7179#note_511312796) by `@Licaon_Kter` there was a fix implemented for the package in https://github.com/react-native-device-info/react-native-device-info/pull/1153 which was included in [`v7.4.0`](https://github.com/react-native-device-info/react-native-device-info/releases/tag/v7.4.0). We can either upgrade our version to `v7.4.0` or newer, or remove the dependency entirely.

But the removal of the dependency is dependent on the future of Referral program and our need for including `installreferrer`.

**Comment by cammellos** [comment]
we can't remove referrer code as it's actively used

**Comment by jakubgs** [comment]
This project upgraded to `v8.0.0` to fix this issue: https://github.com/MBach/LeMondeRssReader/pull/36

**Comment by jakubgs** [comment]
You can verify if the build includes GoogleAPI stuff by disassembling to built APK using:
```
apktool d app-release.apk
```
And then search the resulting unpacked APK for instances of `googleapi` with `grep`/`ack`/`ag`.

**Comment by jakubgs** [comment]
I'm also adding a `make release-fdroid` target in https://github.com/status-im/status-react/pull/11791 but I'm not sure if it's ready yet.

**Comment by jakubgs** [comment]
As far as I understand this stuff:
https://github.com/status-im/status-react/blob/f71faee5c2a869485e9dfafe3de5e704838a6ca2/src/status_im/utils/config.cljs#L47
https://github.com/status-im/status-react/blob/f71faee5c2a869485e9dfafe3de5e704838a6ca2/src/status_im/acquisition/core.cljs#L111-L123
Might not be necessary after you've upgraded this dependency. But not sure.

**Comment by flexsurfer** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-device-info:debugUnitTestRuntimeClasspath'.
   > Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
     Required by:
         project :react-native-device-info
      > Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
         > Could not parse POM /nix/store/rxyqm9laxsjajl7v28v52rkvm1ad6p28-status-react-maven-deps/org/junit/jupiter/junit-jupiter-api/5.7.0/junit-jupiter-api-5.7.0.pom
            > Could not resolve org.junit:junit-bom:5.7.0.
               > No cached version of org.junit:junit-bom:5.7.0 available for offline mode.
      > Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
         > Could not parse POM /nix/store/rxyqm9laxsjajl7v28v52rkvm1ad6p28-status-react-maven-deps/org/junit/jupiter/junit-jupiter-api/5.7.0/junit-jupiter-api-5.7.0.pom
            > Could not resolve org.junit:junit-bom:5.7.0.
               > No cached version of org.junit:junit-bom:5.7.0 available for offline mode.
      > Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
         > Could not parse POM /nix/store/rxyqm9laxsjajl7v28v52rkvm1ad6p28-status-react-maven-deps/org/junit/jupiter/junit-jupiter-api/5.7.0/junit-jupiter-api-5.7.0.pom
            > Could not resolve org.junit:junit-bom:5.7.0.
               > No cached version of org.junit:junit-bom:5.7.0 available for offline mode.
      > No cached version of org.junit.jupiter:junit-jupiter-api:5.7.0 available for offline mode.
      > Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
         > Could not parse POM /nix/store/rxyqm9laxsjajl7v28v52rkvm1ad6p28-status-react-maven-deps/org/junit/jupiter/junit-jupiter-api/5.7.0/junit-jupiter-api-5.7.0.pom
            > Could not resolve org.junit:junit-bom:5.7.0.
               > No cached version of org.junit:junit-bom:5.7.0 available for offline mode.
      > Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
         > Could not parse POM /nix/store/rxyqm9laxsjajl7v28v52rkvm1ad6p28-status-react-maven-deps/org/junit/jupiter/junit-jupiter-api/5.7.0/junit-jupiter-api-5.7.0.pom
            > Could not resolve org.junit:junit-bom:5.7.0.
               > No cached version of org.junit:junit-bom:5.7.0 available for offline mode.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by flexsurfer** [comment]
@jakubgs i can build dev build just fine but have error above when building realease

**Comment by jakubgs** [comment]
Have you done `make nix-update-gradle`? Seems like it changes some dependencies.

**Comment by flexsurfer** [comment]
yes

**Comment by jakubgs** [comment]
The missing library is:
```
> Could not resolve org.junit.jupiter:junit-jupiter-api:5.7.0.
```
But we clearly have that included in our dependencies:
```
 > grep junit nix/deps/gradle/deps.list 
junit:junit:4.12
org.junit.jupiter:junit-jupiter-api:5.7.0
org.junit.platform:junit-platform-commons:1.7.0
```

**Comment by jakubgs** [comment]
OH WAIT, i think i get it

**Comment by jakubgs** [comment]
The issue isn't `junit-jupiter-api`, it's `junit-bom`:
```
            > Could not resolve org.junit:junit-bom:5.7.0.
               > No cached version of org.junit:junit-bom:5.7.0 available for offline mode.
```
Which is related to newer version of Gradle, as I mentioned in https://github.com/status-im/go-maven-resolver/pull/5.

In that case I had trouble with:
```
> Could not find com.google.protobuf:protobuf-bom:3.10.0.
```
But this appears to be an issue specifically related to Gradle 6, and we are still on Gradle 5.
https://github.com/status-im/status-react/blob/293fd5fae1d35551e8d801de81bffabf8ca4083d/nix/overlay.nix#L36

**Comment by jakubgs** [comment]
Although if we look at the `build.gradle` of `react-native-device-info` it shows to default to `4.4.1`:
```gradle
def buildGradleVersion = ext.has('buildGradlePluginVersion') ? ext.get('buildGradlePluginVersion') : '4.1.1'
```
https://github.com/react-native-device-info/react-native-device-info/blob/v7.4.0/android/build.gradle#L10

**Comment by jakubgs** [comment]
Ah yes, Gradle Build tools `4.1.0` are indeed the issue:

![image](https://user-images.githubusercontent.com/2212681/109533962-1a152b00-7abb-11eb-86d0-974767c14f57.png)

https://developer.android.com/studio/releases/gradle-plugin

**Comment by jakubgs** [comment]
So either we have to apply the https://github.com/react-native-device-info/react-native-device-info/pull/1153 fix before https://github.com/react-native-device-info/react-native-device-info/commit/b79d6ca8232c4a7a8306b00933f31af0dc8fb2e9 was added and changed the default Gradle Build plugin version from `3.6.3` to `4.1.1`, or we have to upgrade to Gradle 6.

**Comment by jakubgs** [comment]
They did leave a possibility of overriding the `4.1.1` default with `buildGradlePluginVersion`:
```gradle
def buildGradleVersion = ext.has('buildGradlePluginVersion') ? ext.get('buildGradlePluginVersion') : '4.1.1'
```
So in theory we could try reverting it back to `3.6.3` by setting that.

https://docs.gradle.org/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html

**Comment by jakubgs** [comment]
I added the following line to `android/build.gradle` in the `ext` block:
```gradle
    buildGradlePluginVersion = project.gradlePluginVersion
```
But it fails the same way. I guess I'm missing something, or this just won't work.

**Comment by flexsurfer** [comment]
i guess its because of `if (project == rootProject) {`

**Comment by flexsurfer** [comment]
btw we also have `classpath "com.android.tools.build:gradle:${project.ext.gradlePluginVersion}"` where do we set it ?

**Comment by flexsurfer** [comment]
prepared a fork with reverted gradle https://github.com/status-im/react-native-device-info/commits/v7.4.0-gradle but it didn't help, same error

**Comment by flexsurfer** [comment]
@jakubgs

**Comment by jakubgs** [comment]
So I think my change in https://github.com/status-im/go-maven-resolver/pull/5 might actually be the fix.
I used the commit from the PR and ran `make nix-update-gradle` and it worked:
```
BUILD SUCCESSFUL in 7m 1s
1018 actionable tasks: 1018 executed
running tests
 11124078  00-00-1980 00:00   assets/index.android.bundle
installing

Extracting result: /nix/store/2g55c1g1i26rl80xpkypw5qg352726wa-status-react-build-nightly-android
'/nix/store/2g55c1g1i26rl80xpkypw5qg352726wa-status-react-build-nightly-android/app-release.apk' -> './result/app-release.apk'

SUCCESS
removed '/tmp/tmp-status-react-5b7389f5a/tmp.22bhLgb8Op'
```
Maybe it might even work without the fork?

**Comment by jakubgs** [comment]
I'm gonna try reverting your last commit and see if that works too.

**Comment by jakubgs** [comment]
It worked without the fork added in 5b7389f5a. I'll try pushing without it.
