### ISSUE TITLE
Audio recording noisy ? Quality low ?

### ISSUE THREAD

**Issue by johndejohn** [status-im/status-react#11817]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by cammellos** [comment]
Thanks for the question, unfortunately that'd due to the low bandwidth requirements of the waku protocol.

**Comment by johndejohn** [comment]
> Thanks for the question, unfortunately that'd due to the low bandwidth requirements of the waku protocol.

The parasite noises could be remove..
