### ISSUE TITLE
Sometimes new transaction is not shown after coming back from background even after pull-to-refresh

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11811]
# Bug Report

## Problem
In ~30 % e2e  `test_send_eth_in_1_1_chat_transaction_push` failed on receiver side because confirmed transaction doesn't come (even after pull-to-refresh gesture on account view)

#### Expected behavior
transaction is received, balance is updated.

#### Actual behavior
 Balance 0 ETH is not changed during 400 seconds

#### Acceptance Criteria
6253 e2e is passed

### Reproduction
 

- Sender: send transaction in 1-1 chat
- Receiver: put app to background
- Sender: wait until transaction will be confirmed
- Receiver: put app to foreground, open `Ethereum account`, pull-to-refresh

### Additional Information
- Status version: nightly 02/03/21
- Operating System: Android (not sure about IOS)

#### Logs

Receiver: https://app.saucelabs.com/tests/651a42ed5c34415aa9dae0456ad258fc?auth=2500128cbbf1272b8b4d709f54057349 
10:34 - from background 
12:05 - pull-to-refresh
Logcat: 
[logcat (2).log](https://github.com/status-im/status-react/files/6068059/logcat.2.log)

**Comment by churik** [comment]
Also can be the reason of failed e2e with error:
`Balance ETH 0 is not changed during 400 seconds!`
Examples of failed e2e:
- 6253: [test_send_eth_in_1_1_chat_transaction_push](https://ethstatus.testrail.net/index.php?/tests/view/2177353)
- 6225:  [test_send_funds_between_accounts_in_multiaccount_instance](https://ethstatus.testrail.net/index.php?/tests/view/2177340)
- 6292: [test_keycard_send_funds_between_accounts_in_multiaccount_instance](https://ethstatus.testrail.net/index.php?/tests/view/2177371)

**Comment by churik** [comment]
It is a blocker now for 5% of cases.
Transaction will not appear even after relogin.

https://user-images.githubusercontent.com/4557972/114711986-dfe0af80-9d2f-11eb-8bd8-d610f812c44b.mp4

```
t=2021-04-14T11:30:55+0000 lvl=info msg="load erc20 transfers in range" from=10037870 to=10037884
t=2021-04-14T11:30:56+0000 lvl=info msg="wallet historical downloader for erc20 transfers finished" in=300.970469ms
t=2021-04-14T11:30:56+0000 lvl=info msg="fast indexer Erc20 finished" in=301.579427ms
t=2021-04-14T11:30:56+0000 lvl=info msg="loadTransfers finished" in=523.866406ms
t=2021-04-14T11:30:56+0000 lvl=info msg="end control command"
t=2021-04-14T11:31:00+0000 lvl=info msg="publishing records" records=[]
t=2021-04-14T11:31:00+0000 lvl=info msg="received records" records=[]
t=2021-04-14T11:31:30+0000 lvl=info msg="publishing records" records=[]
t=2021-04-14T11:31:30+0000 lvl=info msg="received records" records=[]
t=2021-04-14T11:32:00+0000 lvl=info msg="publishing records" records=[]
t=2021-04-14T11:32:00+0000 lvl=info msg="received records" records=[]
t=2021-04-14T11:32:16+0000 lvl=info msg="merge old ranges" account=0xf75CE48258b0352DAfe63D69EA284a6dde3346d1 network=3 ranges=1
t=2021-04-14T11:32:16+0000 lvl=info msg="start control command"
t=2021-04-14T11:32:16+0000 lvl=info msg="current head is" block number=10037887
t=2021-04-14T11:32:16+0000 lvl=info msg="eth historical downloader finished successfully" address=0xf75CE48258b0352DAfe63D69EA284a6dde3346d1 from=10037884 to=10037887 total blocks=0 time=285.601927ms
t=2021-04-14T11:32:16+0000 lvl=info msg="fast indexer finished" in=286.745312ms
t=2021-04-14T11:32:16+0000 lvl=info msg="iterative downloader" address=0xf75CE48258b0352DAfe63D69EA284a6dde3346d1 from=10037884 to=10037887 size=100000
```
Comment from Roman:
> transaction  was in 10037879 block
> so it wasn't detected at all

**Comment by rasom** [comment]
well, transaction was detected
```
t=2021-04-14T11:30:55+0000 lvl=info msg="current head is" block number=10037884
t=2021-04-14T11:30:55+0000 lvl=info msg="eth historical downloader finished successfully" address=0xf75CE48258b0352DAfe63D69EA284a6dde3346d1 from=10037870 to=10037884 total blocks=1 time=941.424063ms
```
