### ISSUE TITLE
"Next" button hidden behind keyboard when moving multiaccount to keystore [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11812]
# Bug Report

## Problem

Folllow up fix from https://github.com/status-im/status-react/pull/11784 
It occurs on iOS only and in a case the seed phrase view visited the second time in a same app session.
Partially it's present on seed phrase view when recover non-keycard account but on seed phrase when Move to Keycard storage view it looks worse.
With this issue we need to fix both

#### Expected behavior

1) Seed phrase adapts to keyboard and 'Next' button always visible on screen
2) Tapping inside Seed phrase input twice - makes 'Enter 12, 15, 21 or 24 words' text + Seed phrase input jump down

#### Actual behavior

See below in reproduction steps

### Reproduction

- Recover non-keycard account on iOS (any seed phrase e.g. feel cradle thunder next dignity arrest assist guess need vault still small)
- Log out (NOTE: do not close Status app but log out)
- `Login` screen -> `...` menu -> `Manage keys and storage` -> Check `Move keystore file` checkmark
- Tap Enter seed phrase
**Actual result:**

https://user-images.githubusercontent.com/8749671/109640540-4a130b80-7b59-11eb-815e-25b2e4939f7f.mov

### Reproduction 2:

- Open Status
- Access existing keys -> Recover with seed phrase
- Tap two times in the 'Seed phrase...' input

**Actual result:**

https://user-images.githubusercontent.com/8749671/109640608-60b96280-7b59-11eb-91b2-c1991f7f8655.mov

### Additional Information

- Status version: develop 1.12
- Operating System: Android (for second issue above) and iOS (both issue above)

**Comment by churik** [comment]
not relevant on 1.15
