### ISSUE TITLE
Improve translation process

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11818]
# Problem

The translation process is a bit rocky at this, as it's not well connected to the development process, which means that we always scramble last moment to add translations. 

## Implementation

1) When sending a PR, we should check that `en.json` has new keys. If that's the case, merging the PR should be blocked unless screenshots are attached. We should provide a way for devs to override this behavior. @jinhojang6 should be tagged in the PR automatically.
2) Once the PR is merged, screenshots and new translations should be uploaded to github.

As a bonus, we could have a mode in the app where translation keys are shown aside the actual translation, but that's not necessarily in scope for this.

**Comment by guylouis** [comment]
for 2. you mean localize right ?

**Comment by cammellos** [comment]
Closing this as that's something that we will want to discuss again after 2.0 launch
