### ISSUE TITLE
After migrating multiaccount to keycard can't fetch transaction history and balance isn't fetched automatically

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11823]
# Bug Report

## Problem
If migrating recovered from seed phrase multiaccount to keycard, after login:
1) assets are not loaded automatically
2) can't load transaction history using pull-to-refresh

#### Expected behavior
- all assets are visible
- can load transaction history

#### Actual behavior
https://user-images.githubusercontent.com/4557972/109828916-5f616600-7c3d-11eb-9473-6499cefd74f6.mp4

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Restore multiaccount from seed phrase
- Migrate multiaccount to keycard
- Check balance after login and try to load transaction history

### Additional Information
- Status version: RC 1 v1.12
- Operating System: Android, iOS

**Comment by churik** [comment]
@rasom it is likely the regression from https://github.com/status-im/status-react/pull/11723

**Comment by rasom** [comment]
@churik that happens only when account is recovered, but doesn't happen with a newly created account?

**Comment by rasom** [comment]
@churik 
how exactly do I "Migrate multiaccount to keycard"?

**Comment by rasom** [comment]
ok, steps to reproduce could be reduced to 
- restore multiacc to keycard
