### ISSUE TITLE
Use disabled checkbox on Key management

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11839]
# Problem
The current implementation to the keystore file from a regular account to Keycard will always reset the database (until a future iteration is implemented). To manage this temporary dependency the design includes a 'disabled checkbox'. 

### Current
Visual styling of the 2nd checkbox makes it look like it can be unchecked, while in fact this is not possible, as the 2nd check box is dependent on the first. In the current implementation, the data base will always be reset when the keystore file is moved
![Screenshot_20210304-171510_Status](https://user-images.githubusercontent.com/35233054/109994954-1c22f800-7d0e-11eb-85c9-1692dcfcfcdb.jpg)

### Expected
2nd checkbox is shown as 'disabled' (style available in Quo)
![Group 217](https://user-images.githubusercontent.com/35233054/109995151-5391a480-7d0e-11eb-84f1-4c0fa7763db7.png)

 

## Implementation
afaik disabled state is available in Quo

**Comment by guylouis** [comment]
This looks like a bug remaining form PR "Migrate on-device accounts to keycard" #11526

@shivekkhurana if you can take a look at it whenever you have a chance, many thanks !
