### ISSUE TITLE
Aragon works in Metamask but not Status

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#1184]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to  browse dapps, because that's what Status is for

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When I goto https://alpha.aragon.one/#!/home it should work

**Comment by rasom** [comment]
Logs:

<img width="888" alt="screen shot 2017-05-09 at 10 58 28" src="https://cloud.githubusercontent.com/assets/2364994/25840924/882b2aea-34a6-11e7-8152-49a3e4c2f888.png">


```
StatusHttpProvider
VM32:121 https:
a3b148c….min.js:3 Secp256k1 bindings are not compiled. Pure JS implementation will be used.
a3b148c….min.js:77 [Aragon] Injecting metamask for: https://alpha.aragon.one false false
VM46:121 https:
a3b148c….min.js:76 EthereumNode: Trying connection in 1000
VM49:121 https:
a3b148c….min.js:48 GET https://alpha.aragon.one/sockjs/info?cb=10_uaad2xl 404 ()
y._start @ a3b148c….min.js:48
(anonymous) @ a3b148c….min.js:48
setTimeout (async)
n.delay @ a3b148c….min.js:47
n.XHRLocalObject @ a3b148c….min.js:48
N.doXhr @ a3b148c….min.js:48
(anonymous) @ a3b148c….min.js:48
setTimeout (async)
n.delay @ a3b148c….min.js:47
N @ a3b148c….min.js:48
V @ a3b148c….min.js:48
w @ a3b148c….min.js:48
_launchConnection @ a3b148c….min.js:48
t.ClientStream @ a3b148c….min.js:48
o @ a3b148c….min.js:48
e.connect @ a3b148c….min.js:49
(anonymous) @ a3b148c….min.js:49
(anonymous) @ a3b148c….min.js:49
(anonymous) @ a3b148c….min.js:49
3VM51:121 https:
a3b148c….min.js:76 EthereumNode: Trying connection in 3000
VM56:121 https:
favicon.ico:1 GET https://alpha.aragon.one/favicon.ico 404 ()
a3b148c….min.js:76 EthereumNode: Trying connection in 7000
a3b148c….min.js:76 EthereumNode: Trying connection in 15000
a3b148c….min.js:76 EthereumNode: Trying connection in 31000
a3b148c….min.js:76 EthereumNode: Trying connection in 63000
a3b148c….min.js:76 EthereumNode: Trying connection in 127000
```

I didn't find aragon.one sources, so I can't say for sure, but it seems that app ignores `web3` that is provided in the webview. I don't know what can be done on our side.

**Comment by jarradh** [comment]
okay thank-you, paging @izqui @luisivan

**Comment by izqui** [comment]
Weird as it is working with other injected web3 (Metamask, parity and mist) without problem. Will look into it :)

**Comment by onbjerg** [comment]
I've opened a PR that fixes this 🎉

**Comment by izqui** [comment]
Merged in aragon! Whenever we redeply it will be fixed.
