### ISSUE TITLE
Upsell keycard with notification for users with assets that are worth more than x

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11847]
relates to this MVP #11395

**issue with this MVP above**
it targets any user that doesn't have a keycard, without taking into account if the user has some value to protect or not
in particular the banner is thus shown to every single one of new status users that use a standard (non keycard account).
We want the upsell to be more tageted 

**solution** 
- when a user has on his device, on one of the multiacounts, more than x (treshold to define) $ of value in eth or erc20 tokens (NFTs not considered since valuation is hard to get), on all his account that he controls from the seed of his multiaccount (read only accounts not considered, imported accounts with a sigle private key not taken into account)
- then this user is being pushed a notification to let him aware that he can upgrade his security with a keycard
- this notification is being sent not exactly when the treshold is passed but when it is passed and a given action is perfomed by the user. This action needs to be defined

**Comment by hesterbruikman** [comment]
@guylouis Is the intention here to send a push notification or an in-app notification https://github.com/status-im/status/issues/35?

I'd prefer an in-app notification as a) it is less aggressive and b) can be timely as the user is likely interacting with the app when conditions are met. Potentially there is argument c) can also work on F-droid as it doesn't require push notifications dependencies (not sure about this one)

However, this might take more development effort; In-app notification pattern does exist and was used here: https://github.com/status-im/status-react/pull/11522

**Comment by guylouis** [comment]
@hesterbruikman indeed these are good arguments to do this with in-app notifications

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
