### ISSUE TITLE
Share setting extension

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#11840]
# Feature Issue

It should be possible to send setting in the chat as a message, so other user could use your settings

### User Story

As a community manager or participant i want to share community mailserver in the chat

As a user i want to share bootnode or maiserver in the chat

**Comment by churik** [comment]
@flexsurfer still relevant?
I believe not a prio for now,  closing due to re-design, label `recheck` added for future re-consideration.
Please reopen it if still makes sense for you to keep it, thanks!
