### ISSUE TITLE
Move pull to refresh to the main account to make it more easily discoverable

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11849]
# Problem
See also #11821 

Currently, following #11723 the account balance is not automatically updated for newly generated accounts and imported accounts with zero value. The user can pull to refresh to start fetching balance. However, pull to refresh is currently only available on individual account screens, not on the account overview screen. 

Especially for users with only one account, this can be difficult to discover, resulting in the user not seeing updates or knowing how to update their balance after sending funds to their empty account.

## Implementation
tbd

## Acceptance Criteria
Pull to refresh is available on account overview screen

## Future Steps
#11821

**Comment by shivekkhurana** [comment]
@rasom I'm not able to tackle this. Moved the account refresh logic to accounts index page, but refreshing leads to multiple spinners sometimes. Ping me when you are back from holidays.
