### ISSUE TITLE
Do not scroll conversation view down during initial sync after being away for a long time

### ISSUE THREAD

**Issue by trosel** [status-im/status-react#11859]
# Bug Report

## Problem

When I tap on a channel in iOS that has had a lot of activity since I was last there, the new messages pop-in continuously until I have received the latest message on my device. Sometimes this can take a long time if there was a lot of messages. While this is happening, my view is being dragged downward with the latest messages.

If I want to "catch up" with the conversation, I need to scroll back up and try to find where the point was where I last read. 

#### Expected behavior

I expect the new messages to not push my view continually down. I want to stay in the same spot that I was in before and then have the new messages fill in underneath my view. I can then scroll down as I read.

#### Actual behavior

As new messages come in, in rapid succession, my view is continually pushed down. I need to drag up and up quickly in order to stay in the same spot that I was in before. Otherwise I "drown" in new messages.

#### Notes

This may be related to a request for a "jump to latest" button. I can imagine a scenario in which someone does not care to be caught up to a long conversation but rather just wants to jump to the latest message after all the new messages load.

#### Acceptance Criteria

?

### Reproduction

- Open Status after not checking it for 12-24 hours
- Tap on the main Status channel quickly
- See new messages flow in and push your view down
- Try to figure out where your last read point was in the conversation by scrolling up

### Additional Information

- Status version: 1.11
- Operating System: iOS

**Comment by flexsurfer** [comment]
thanks for the issue @trosel we have already similar one here https://github.com/status-im/status-react/issues/6375, so i'll close this one
