### ISSUE TITLE
After relogin on mobile network transaction history is reset (need to load it again) and "Load more" button doesn't do anything when open history for 1 time

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11860]
# Bug Report

## Problem
2 issues with transaction history on mobile network: 

#### 2) No caching of transaction history in view, so after relogin on mоbile network (with "Use mobile data" = OFF) it is empty again
Also there is no indication that it should be pull-to-refresh to download transaction history (cc @errorists how to do it in better way)

#### Expected behavior
1) if "Load more" button is useless - let's hide it
2) if transaction history was loaded before, assume it should be loaded after relogin.

#### Actual behavior
1) https://user-images.githubusercontent.com/4557972/110498872-00499880-80f8-11eb-8603-8503fae1f554.mp4
2) https://user-images.githubusercontent.com/4557972/110498884-02abf280-80f8-11eb-8279-cbe86b724817.mp4

### Reproduction

- Open Status (on cellular network)
- Restore multiaccount with transaction history
- Tap on "Load more" (ISSUE 1)
- Pull-to-refresh
- Relogin and open transaction history (ISSUE 2)

### Additional Information

- Status version: release 1.12
- Operating System: Android, iOS

**Comment by rasom** [comment]
It can be reproduced in 1.11.1 as well.
