### ISSUE TITLE
App crashes if start migrating to Keycard until the Seed phrase screen is opened, press back and try to log in

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11861]
# Bug Report

## Problem

App crashes when trying to migrate from a regular account to Keycard if go through the "Key managment" screen, navigate to "Enter seed phrase" screen, return to the login screen and try to log in.
If try this flow on iOS device, User will be able to log in, but his multiaccount will be empty.

#### Expected behavior

Can be able to log to the regular multiaccount if the migration process was interrupted at this stage

#### Actual behavior

**Android:**

https://user-images.githubusercontent.com/67952253/110625474-c16f1d80-819f-11eb-9f72-b8d9313cbb6f.mp4

**iOS:**

https://user-images.githubusercontent.com/67952253/110626305-d9936c80-81a0-11eb-8a0a-f8c612265a59.mp4

### Reproduction

- Recover multiaccount with seed phrase or create a new one with key storage on device
- Log out
- Tap  `...` at the top right of the password screen
- `Manage keys and storage`
- Tick "Move keystore file" checkbox
- Tap `Enter seed phrase`
- Tap back twice
- Enter password to log in

### Additional Information

- Status version: Nightly 10/03
- Operating System: Android, iOS

#### Logs

[crashAndroid.log](https://github.com/status-im/status-react/files/6115637/crashAndroid.log)

**Comment by imrane** [comment]
Is this iOS released in production on the AppStore? I can't see the key management option in mine.

**Comment by bitgamma** [comment]
@qoqobolo should this be closed?
