### ISSUE TITLE
Cursor jumps if trying to set it to specific place in long message in input field (iOS only)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11865]
# Bug Report

## Problem

If type or paste scrollable text message into the input field of any chat and try to place the cursor to some specific place in the text, it will jump to another random place.
Cursor placement works fine with long press.

#### Expected behavior

Can set the cursor to any place in long text with a quick tap.

#### Actual behavior

https://user-images.githubusercontent.com/67952253/110649856-4a934e00-81ba-11eb-85ac-e0647c859941.mp4

### Reproduction

- Open chat
- Paste a long message into the input field
- Scroll the message a little
- Tap on some place in the text to set the cursor

### Additional Information

- Status version: Nightly
- Operating System: iOS

**Comment by churik** [comment]
reproducible on 1.15

**Comment by qoqobolo** [comment]
Not reproducible on 1.17
