### ISSUE TITLE
Blinking top bar of chat view when type first char in the input or after sending message [iOS] 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11879]
# Bug Report

## Problem

When user type the very first char in message input the top bar of chat view always blinks. The same when sending message.
Apparently it may be connected to appear-disappearing of the command-image icons located to the left of chat input when the first character appears(disappears) in the input.

Doesn't happen on Android. 

#### Expected behavior

Chat view is static (no blinking behavior when char appears in input)
#### Actual behavior

Pay attention to the top bar of the chat view:
![ezgif-2-f19d52d6913b](https://user-images.githubusercontent.com/8749671/111287656-1c938b00-864c-11eb-8905-225a6af5e0a4.gif)

### Reproduction
- Open Status and create new account
- Join any public chat
- Put cursor in message input
- Type any char and pay attention to top chat view bar

### Additional Information
- Status version: Develop 1.12 (no issue in release 1.11.1)
- Operating System:  iOS only

**Comment by Serhy** [comment]
Also there is might be related minor issue to it (it's also only iOS when typing the first char)

If user user sent a mention in chat as the very first item in the message, - the next time this user starts to type a char in message input it's visible that this char has a colour of mention (but quickly backs to regular colour)

(Slowed down twice. Pay attention to the char in input when it changes colour)
![50Percent_slow_blue_char_first](https://user-images.githubusercontent.com/8749671/111289790-2cac6a00-864e-11eb-8590-c30d6ba5ed29.gif)

**Comment by churik** [comment]
Couldn't reproduce the issue on 1.13, @Serhy please close it if it is not reproducible for you as well

**Comment by Serhy** [comment]
No bug anymore in 1.13. Closing the issue.
