### ISSUE TITLE
Show hint, that you can buy username only from predefined wallet

### ISSUE THREAD

**Issue by mxmzb** [status-im/status-react#11871]
_this should be a UI/UX improvement_

# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be informed that I need to transfer tokens only to the predefined main wallet to buy a username with it.

Back story: I played around with the app and created a second wallet. Then I transferred SNT to it to buy a username, just to realize you can pay for it only from the main wallet at the moment. With fees close to $30 and a username cost of about $1 it's annoying to run into this.

### Solution

I think this can be easily achieved even with a simple alert or note where you copy the address or similar.

**Comment by hesterbruikman** [comment]
Thanks for raising this @mxmzb! I will close this issue as I 100% agree this should actually be resolved by allowing to select an account when registering an ENS name (as you decsribe in #11872)

cc @guylouis
