### ISSUE TITLE
Browser Enhancement - Settings spoof language + Adware / Malware blocker

### ISSUE THREAD

**Issue by ckorder** [status-im/status-react#11870]
# Built-in browser lacks privacy and potentially security

I would love to see the feature enhancements for the built-in browser:

### Setting for spoofing language

On android the system language or the keyboard **language settings get automatically transmitted to websites**. It would be nice if this could be optional spoofed if the user enabled this within the settings area as well as the timezone he is currently using. 

**Potential way to achieve this**

Usage of en-us and UTC would be my proposal, 
something very similar like Firefox is using on private tabs on the desktop application.

### Filter for Ad-/Malware

Maybe as opt in as well or as opt out, your choice :)

Protects users from many well known shady scripts, click hijacking, totally annoying adware.
Goal would be a very nice usable browser without lacking functionality like broken websites etc. 
Brave like browsing experience, would mean blocking really dangerous sites and enhanced tracking protection.

**Potential ways to achieve this**

https://github.com/gorhill/uBlock
Using the default filters 

Simply blocking well known trash spreader 
https://github.com/StevenBlack/hosts
Unified hosts = (adware + malware) 

Alternatives for hosts filters:
https://adaway.org/hosts.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

I don't like the idea of being to restrictive and block more than really necessary to protect the users of the application.

### Acceptance Criteria

Good PR since the project provides a solid and strong built-in browser feature and protects users privacy needs.
Faster loading sites without annoying ad-/malware.

**Summary** 

You guys are awesome! I love the creation of multiple ETH accounts and the reproducible build on [F-Droid](https://f-droid.org/en/packages/im.status.ethereum/). Great job so far!

**Comment by churik** [comment]
closing due to re-design and inactivity, label `recheck` added for future re-consideration
