### ISSUE TITLE
Make username purchasable through secondary wallets

### ISSUE THREAD

**Issue by mxmzb** [status-im/status-react#11872]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, you should be able to purchase a username from a secondary wallet.

### Description

This is a more sophisticated feature request for https://github.com/status-im/status-react/issues/11871

**Comment by hesterbruikman** [comment]
Actually, closing this issue @mxmzb . Will be addressed by https://github.com/status-im/status-react/issues/10142
