### ISSUE TITLE
Add ETH2x-FLI erc20 token in our default list of supported tokens in the wallet

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11885]
summary
add ETH2x-FLI erc20 token to our default list of erc20 token supported by the wallet

user story
a user holding ETH2x-FLI token in his wallet account should see in his list of assets the number of ETH2x-FLI tokens he holds

details
the token details are here 
https://docs.google.com/document/d/1or50qQ6QNq-cugSpN0V4cMU9NyrMvXTsvAxqXVUdWCM/edit

**Comment by guylouis** [comment]
@j-zerah I have a doubt is the name of the token FLI or ETH2x-FLI ?

**Comment by hesterbruikman** [comment]
@simonricoo in the Google doc is a logo for the token. Can you please check if that one needs any changes/design to fit the token list?

**Comment by guylouis** [comment]
> @j-zerah I have a doubt is the name of the token FLI or ETH2x-FLI ?

after discussion, we confirmed it is ETH2x-FLI

**Comment by flexsurfer** [comment]
@simonricoo could you please add logo to figma ?

**Comment by hesterbruikman** [comment]
@flexsurfer Simon is OOO. @guylouis what's the timeline for this? Can it wait two weeks and be included in 1.13 or 1.14?

**Comment by guylouis** [comment]
@j-zerah call actually

**Comment by flexsurfer** [comment]
@errorists could you please assist with this ? we just need to import svg to figma where we have all tokens assets

**Comment by hesterbruikman** [comment]
fyi Maciej is out today

If it's urgent I can add the SVG to Figma. If it's not I'd rather wait, as I don't know if there's any styling to the icons I'm not aware of

**Comment by guylouis** [comment]
discussed with Jonny, this can definitely wait for simon to be back

**Comment by flexsurfer** [comment]
ping @errorists , @simonricoo for the icon

**Comment by simonricoo** [comment]
Hey the icon is already in Figma https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=822%3A49
