### ISSUE TITLE
No last message when opening chat but it was visible on chat-preview

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11895]
# Bug Report

## Problem

Sometimes it happens that message is received and it's visible on chat preview with unread indicator. But when opening this chat - message(s) are not visible for, relatively, quite a while (sometimes for 4-5 sec of top-level device, sometimes up to 10 seconds). Below are log for when delay of message appearance happened.

#### Expected behavior

Message is visible when opening chat 

#### Actual behavior

Message is not visible for some time (up to 10 sec) after opening chat

https://user-images.githubusercontent.com/8749671/111467864-9c455680-872d-11eb-9f2a-fc4d131b03c4.mov

### Reproduction (not 100% but what happened)

- Create two new account (UserA and UserB)
- UserA creates 1-1 chat with UserB, created GroupChats
- UserB open main Chats view.
- UserA sends text message in each chat
- UserB opens each chat and pays attention whether message appears without delay

### Additional Information

- Status version: release 1.12.1 
- Operating System: Android and iOS

#### Logs

Logs from two devices after issue noticed:
[iPhone_geth_and_logact](https://github.com/status-im/status-react/files/6155395/status_logs.25.zip)
[Android11_geth_and_logcat](https://github.com/status-im/status-react/files/6155396/Status-debug-logs.38.zip)

**Comment by Serhy** [comment]
Will add more details once I have it. 
Not reproduced in develop1.13 builds yet

**Comment by Serhy** [comment]
Reproduced in nightly build. 

However, it's not exactly the one I saw in release (plus below scenario is not reproduced in Release1.12), - current one is the something connected to navigation between screens.

**Reproduction**:
1) UserA and UserB joins same public chat (or group)
2) UserB sends text message in public chat
3) UserA taps UserB user icon to navigate to it’s profile -> and tap Chat from there to open 1-1
4) UserB now sends again in public chat message(s)
5) UserA navigates back to Chats
6) UserA opens public chat where unread message + unread indicator displayed
**Actual result**: Message is not visible
7) UserA returns back to Chats view
**Actual result:** Unread message indicator still displayed

**Comment by churik** [comment]
Also as part of this issue noticed that an unread indicator is not shown, if new messages arrived to chat which was opened once and then user went back to home view.
Reproducible with public, 1-1 chats

**Steps:**
- user A: join public chat `zzz`
- user B: join public chat `zzz`
- user A: tap back
- user B: send several messages to `zzz`
- user A: pay attention to  `zzz` chat.

**Expected result:**
unread indicator is shown on `zzz` chat.
**Actual result:**
no unread indicator even if you switched to another tab.
**OS:** IOS, Android

**Comment by flexsurfer** [comment]
@Serhy when did you see this last time ? probably fixed ?

**Comment by Serhy** [comment]
Didn't see it since then. Closing for now. As for unread message described in https://github.com/status-im/status-react/issues/11895#issuecomment-804977796 the only reproduction for now is https://github.com/status-im/status-react/issues/12251 (last one caused by recent updates but the bug is the same)

**Comment by flexsurfer** [comment]
users report that its still can be replicated

**Comment by flexsurfer** [comment]
@cammellos @Samyoul might it be related to `remove messenger lock` ? or may be you have any thoughts on this ?

**Comment by flexsurfer** [comment]
seems like `remove messenger lock` not related, because it was done later

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-go/issues/2314
