### ISSUE TITLE
No wallet support for https://marketplace.windingtree.com/

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#11897]
# Bug Report

## Problem

Can’t create an account

#### Expected behavior

Selected status wallet used for creating an account

#### Actual behavior

Metamask used instead.

#### Notes

iOS

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- ...
- Step 3, etc.

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.11.1 (20210215172307)

- Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
...
```

**Comment by flexsurfer** [comment]
thanks., but its better to file issue on windingtree.com
