### ISSUE TITLE
Activity indicator on Sign In

### ISSUE THREAD

**Issue by benmorrow** [status-im/status-react#1191]
### User Story

As a user, I want to sign in.

### Description

*Type*: Feature, User Experience

*Summary*: On the Sign In screen, I type my password and press the Sign in button... and nothing happens for three seconds. This is confusing because I wonder if I pressed the button correctly.  

#### Expected behavior
When I tap the Sign In button, the app should show an activity indicator.

#### Actual behavior
When I tap the Sign In button, the keyboard dismisses but nothing else happens for three seconds until the screen changes.

### Reproduction
Force Quit the app. Open the app. Tap your username. Type your password. Tap the Sign In button.

### Solution
I think the easy way to fix this would be to replace the words, "Sign In", inside the button, with an activity indicator spinner while the app is authenticating the user.

![img_0204-2](https://cloud.githubusercontent.com/assets/5604/25883434/8a4cf912-34ff-11e7-8a2b-bfa4e0aec92c.png)

### Additional Information
* Status version: 0.9.7d64
* Operating System: iOS, iPhone 6 Plus

**Comment by annadanchenko** [comment]
same as #641

**Comment by flexsurfer** [comment]
in this issue, standard loading component has been implemented, design version will be implemented in https://github.com/status-im/status-react/issues/641
