### ISSUE TITLE
Add action icons under opened pic

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#11912]
# Feature Issue

Right now when picture is opened, there is an ugly drop down menu with actions to do. This design is “slow” compared to usual set of actions icons under the picture.

### User Story

As a user I want to have more usual way of saving, sharing, etc. of pictures

![PNG image](https://user-images.githubusercontent.com/41779817/111902611-57802f00-8a4f-11eb-9d56-42fe8ba29c85.png)

**Comment by churik** [comment]
@rapidddenis  thank you for reporting!
Can you please elaborate where the selected picture is opened (profile > set picture, or it is an image from chat, or it is browser)?

**Comment by rapidddenis** [comment]
This is image from status feed, the same goes for 1-1 chats images

**Comment by churik** [comment]
cc @hesterbruikman @errorists

**Comment by hesterbruikman** [comment]
Thanks for the ping @churik

@rapidddenis to confirm: There is are options to Share and Save when you long press on an image inside a chat window (see image below). Do I understand correctly that you'd like something similar for the full image view?

Also, are you using Android or iOS?

![IMG_0437](https://user-images.githubusercontent.com/35233054/130095727-a064b3bf-8b7e-45e5-9aa4-55df562f59be.PNG)

**Comment by rapidddenis** [comment]
Exactly, fast action icons

**Comment by churik** [comment]
@hesterbruikman 
The requested feature as I understand is "Share".
Currently we have 2 options on images:
- save 
- reply

> Do I understand correctly that you'd like something similar for the full image view?
These options are available in full image view.

And there is no chance to "Share" image, like in other messengers.
It has a higher prio than redesigning full image view from my POV

Also @jarradh  mentioned "Share" option on images as desirable. 
So I suggest to add share first (create another issue with more details?) and maybe redesign full image view
Currently it looks like this:
<img width="186" alt="Monosnap 2021-08-20 15-12-17" src="https://user-images.githubusercontent.com/4557972/130238522-8b51e52a-3028-44bd-9ea6-d42cd77aa91e.png">

**Comment by hesterbruikman** [comment]
@churik the view looks slightly different on my end (Android, image below). It seems only a `Save` action is included on Android; No context menu including all 3 actions `save`, `reply`, `view profile`, as is the case on iOS.

I don't see a reason for this difference. In sum, looks like we have 3 issues:

1. Add `share` (to all platforms)
2. Add `reply` and `view profile` of image sender to Android
3. Review design to increase discoverability and make actions more instantly available

I'll create separate issues in this repo for the first 2 items. For the 3rd item I'll Ieave a note for errorists to check when he's back and available. 

![Screenshot_20210823-105005_Status](https://user-images.githubusercontent.com/35233054/130419054-52b2afd1-3adb-4620-b67c-8275888a8e08.jpg)

**Comment by churik** [comment]
Agree, thank you @hesterbruikman 
Please ping me in case I may help.

**Comment by errorists** [comment]
Ok I'll revisit the design and follow up with instructions here once done

**Comment by errorists** [comment]
… and done, design revisited. [Here's the Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4190%3A24449). Be sure to also update the accompanying long press sheet [found here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4190%3A25193).

The button layout did change in the image preview, there's actions to share and download. 
⚠️ I don't know where the 'View profile' came from but it shouldn't be there at all.⚠️

<img width="375" alt="Photos -_ Image preview" src="https://user-images.githubusercontent.com/4932774/130581928-a0bef58c-595e-4430-b868-f32ea16bafba.png">

<img width="375" alt="Image" src="https://user-images.githubusercontent.com/4932774/130583348-66152ef8-1017-4225-8208-5bacf2b758df.png">

**Comment by rapidddenis** [comment]
Shall there be the same options for view and preview?

**Comment by churik** [comment]
So it was splitted in 2 separate issues:
- https://github.com/status-im/status-react/issues/12472
- https://github.com/status-im/status-react/issues/12480
