### ISSUE TITLE
Communities improvements

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11914]
### 1.1 [Design] No community colour (M)
![image](https://user-images.githubusercontent.com/4557972/111962943-438e0900-8af3-11eb-9190-d7e721dbe181.png)
### 1.2 [ISSUE] after setting profile image option "Remove" is shown, it is not working (S)
![IMAGE 2021-03-22 09:50:37](https://user-images.githubusercontent.com/4557972/111963667-0f671800-8af4-11eb-8fa3-fa720807ff03.jpg)
### 2.1 [Design] Exporting / importing communities (M)
Process in Figma: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=18581%3A61837
Process in current develop: 
<img width="892" alt="import" src="https://user-images.githubusercontent.com/4557972/111965262-d5971100-8af5-11eb-859f-2550e457d29a.png">
Also imo would be nice to add QR code for simplifying process.

### 2.2 [Design] Sharing / inviting members (M)
Figma design is [here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=16053%3A50)
#### 2.2.2 [Design] Invitation in chat (M)
[Design in Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15316%3A0)
In fact invite for sender and receiver are the same
<img width="825" alt="photo_2021-03-22 11 05 08 jpeg 2021-03-22 11-05-35" src="https://user-images.githubusercontent.com/4557972/111973300-a3d67800-8afe-11eb-8dd9-2e5fc1eba0da.png">
#### 2.2.3 [ISSUE]Open membership -> Admin opens options -> Invite people (S)
Option should be Share instead of  Invite people
![IMAGE 2021-03-22 11:30:04](https://user-images.githubusercontent.com/4557972/111976471-f4030980-8b01-11eb-898d-8f1b4a0855d6.jpg)
#### 2.2.4 [ISSUE] Required approval membership -> Invited user opens .. > View Profile  -> Invite people (S)
Share screen is shown
#### 2.2.5 [Design] Align with [figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=17672%3A54578) membership request sending (M)
https://user-images.githubusercontent.com/4557972/111980692-f451d380-8b06-11eb-8988-138853697458.mp4
#### 2.2.6 [ISSUE] Prior to joining if tap on invite - all chats inside have purple icons (they changed colour after joining)
![IMAGE 2021-03-22 14:30:58](https://user-images.githubusercontent.com/4557972/111997315-38e76a00-8b1b-11eb-85b9-1e891b1c7eb5.jpg) (S)

### 2.4 [ISSUE] Missing [options](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15316%3A0) when opening options from community view (S)
Expected that options match possible actions from Community Profile page (Leave, Share, in some cases Members, Invite)
#### 2.4.1 [ISSUE] Open membership -> Admin opens options
![IMAGE 2021-03-22 11:21:23](https://user-images.githubusercontent.com/4557972/111975305-bce02880-8b00-11eb-8265-8865d092288c.jpg)
#### 2.4.2 [ISSUE] Open membership -> non-admin opens options
![IMAGE 2021-03-22 11:23:51](https://user-images.githubusercontent.com/4557972/111975603-15afc100-8b01-11eb-83ac-4da9c0c6c6a3.jpg)

### 3.1 [ISSUE] Not possible to see user profile from Membership requests page (S)
![IMAGE 2021-03-22 12:09:08](https://user-images.githubusercontent.com/4557972/111981035-688c7700-8b07-11eb-8b10-3322650fd827.jpg)

### 3.2 [ISSUE] Nicknames are not shown on  Membership requests page, overlapping with username (S)
![IMAGE 2021-03-22 12:25:48](https://user-images.githubusercontent.com/4557972/111982833-bc985b00-8b09-11eb-899e-8fe020ee67bd.jpg)

### 3.3 [ISSUE] Error when declining membership requests (S)
![IMAGE 2021-03-22 12:27:23](https://user-images.githubusercontent.com/4557972/111983029-f5383480-8b09-11eb-85f9-9aede4d957ba.jpg)

### 3.4 [Design] No any sign on home screen that you have several membership requests (should be notification, but IMO would be better to show some indicator or on home screen or on community screen)
Currently, you can see membership requests only if you go to Options > View Profile

### 4.2 [ISSUE] No validation for chat names inside communities (so can use cyrillic, spaces, etc) https://github.com/status-im/status-react/issues/12010 (M)
![IMAGE 2021-03-22 14:48:13](https://user-images.githubusercontent.com/4557972/111999827-a2687800-8b1d-11eb-9063-adee9b3a5c46.jpg)
### 5.1 [Question] Roles management is not implemented
Without roles managements not clear:
- who is admin
- that for "Require approval" communities invited by admin users can share chat, but all members should also be approved by admin 
- that option "Follow" is available only for the "Require invite from another member" and by "Share" option from the admin; difference between share and invite still not clear.
### 5.2 [Question] Type of community is shown only in case if it is open community 
Not sure it is expected
### 5.8 [Design] Banned user stays with "Pending membership" request
After banning user if he taps on Invite to community, "Membership request is pending" is shown, not sure it is expected way to handling this case

**Comment by churik** [comment]
To summarize:
## 1. Creating community process (general, about all types of communities)

- [ ] **Low:** 1.1 [Design] No community colour 
- [ ] **Medium:** 1.2 [ISSUE] after setting profile image option "Remove" is shown, it is not working
- [ ] **Low:** 1.3 [Design]  No [banner](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15316%3A0) after creating community
- [ ] **Low:** 1.4 [Design]  No back up community key [feature](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=19202%3A2)

## 2. Community options

- [ ] **High:** 2.1 [Design, general] Exporting / importing communities
Basically, it is not clear that if smbd is importing the community, he will be ADMIN of the community.
In that case, he is not shown as a community admin but has the same options.
- [ ] **High:** 2.2 [Design, general] Sharing / inviting members [figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=16053%3A50)
- [ ] **Medium:**  2.2.1 [Design, general] No community link, so not possible to share community with non-contacts
- [ ] **Medium:** 2.2.2 [Design, general] Invitation in chat
In fact, it is not clear is it an outgoing or incoming invitation
- [ ]  **Medium:** 2.2.3 [ISSUE, "Open membership"] Open membership -> Admin opens options -> Invite people
The option should be Share instead of  Invite people~~
- [ ] **High:** 2.2.4 [ISSUE, "Required approval"] Required approval membership -> Invited user opens .. > View Profile  -> Invite people
Share screen is shown. There should be a clear explanation of what options are available if you are invited by the Admin or invited by the invited user.
- [ ] **Low:** 2.2.5 [Design, general] Align with [figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=17672%3A54578) membership request sending
- [ ]  **Medium:** 2.2.6 [ISSUE, general] Before joining if tap on the invite - all chats inside have purple icons (they changed color after joining)
- [ ] **Low:** 2.3 [Design, general] No [options](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=17023%3A50817) on long tap on community
- [ ]  **High:** 2.4 [ISSUE, general] Missing [options](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15316%3A0) when opening options from community view
- [ ] **High:**  2.4.1 [ISSUE, "Open membership"] Open membership -> Admin opens options
- [ ] **High:** 2.4.2 [ISSUE, "Open membership"] Open membership -> non-admin opens options
- [ ] **Low:** 2.5 [Design, general] No option to edit community (at least name, description, photo)

## 3. Membership management 

- [ ] **Low:** 3.1 [ISSUE, "Require approval"] Not possible to see user profile from Membership requests page
- [ ] **Medium:** 3.2 [ISSUE, "Require approval"] Nicknames are not shown on the Membership requests page, overlapping with username
- [ ] **High:** 3.3 [ISSUE, "Require approval"] Error when declining membership requests
- [ ]  **High:** 3.4 [Design, "Require approval"] No sign on the home screen that you have several membership requests (should be notified, but IMO would be better to show some indicator or on the home screen or community screen)


## 4. Chats inside communities

- [ ] **Low:** 4.1 [Design, general] Can't delete chat from community ([design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=16068%3A3633))
- [ ] **High:** 4.2 [ISSUE, general] No validation for chat names inside communities (so can use cyrillic, spaces, etc)~~ https://github.com/status-im/status-react/issues/12010


## 5. General

- [ ] **High:** 5.1 [Question] Roles management is not implemented
- [ ] **Medium:** 5.2 [Question] Type of community is shown only in case if it is an open community 
- [ ] **High:** 5.3 [ISSUE, general] User is not shown as admin when he imports the community
- [ ] **High:** 5.4 [ISSUE, "Require approval"] When importing community "Require approval" type, can create channels, but can't post
- [ ] **Medium:** 5.5 [ISSUE, general] No validation for key on "Import a community" screen (expected to see an error message or disabled button)
- [ ] **High:** 5.6 [Question, general] Not sure that allowing audio, images for chats inside communities don't affect performance.
- [ ] **Low:** 5.7 [Question, general] Features chat categories in communities, accepting new people by ENS name clearly not implemented and don't think they are required for now
- [ ] **Medium:** 5.8 [Design, "Require approval", "Require invite"] Banned user stays with "Pending membership" request

**Comment by guylouis** [comment]
2.4 detailed in this issue: https://github.com/status-im/status-react/issues/11938

**Comment by churik** [comment]
A brief explanation about types of communities: https://notes.status.im/testing-communities
Video from community sync with presentation how they are implemented is [here](https://drive.google.com/file/d/11cJgMbI-xQBqXLjJUnd4drY-v2hUPKVl/view?usp=sharing)

**Comment by guylouis** [comment]
closing this since the issues we will address (see list here https://notes.status.im/JYSsgv14RjKPyX-bxJpYPQ?view )
have been opened in new issues:

- https://github.com/status-im/status-desktop/issues/12128 Limit types of communities to 'require Approval'
- https://github.com/status-im/status-desktop/issues/12129 Allow user to pick community color
- https://github.com/status-im/status-desktop/issues/12130 After setting profile community picture image option 'remove' is shown but it is not working
- https://github.com/status-im/status-desktop/issues/12131 Show community link
- https://github.com/status-im/status-desktop/issues/12132 community links should be unfurled in chat
- https://github.com/status-im/status-desktop/issues/12133 Communities deeplinks
