### ISSUE TITLE
Unexpected return to settings

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#11918]
# Problem

https://user-images.githubusercontent.com/41779817/112272797-8a573c80-8c74-11eb-8a6b-04ac28a0b97f.MOV

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by churik** [comment]
@rapidddenis thank you for reporting!
as 'Sync settings' is a sub-menu of Profile, navigation works as expected in this case.
