### ISSUE TITLE
Back gesture on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11913]
### User Story

As a user, I want to use a swipe-to-back gesture in Status on Android devices. 

### Description

Currently, users have to press the arrow to go back, even on Android devices that have the back gesture.

### Acceptance Criteria

Users can use the back gesture in the Status app on all Android devices that support this type of navigation.

### Notes

The feature request was originally received from the user to error-reports@status.im

**Comment by briansztamfater** [comment]
As per talked in #11970 with @errorists, system's back gesture is already working if gestures are enabled from the Android device settings. Maybe it's worth testing with some Android devices that support gestures to verify, but I tested on an emulator and it worked. Example below 👇 

![android-back-default](https://user-images.githubusercontent.com/18485527/114283435-195ba700-9a20-11eb-99f9-a3c259904fe1.gif)
