### ISSUE TITLE
White screen if browse any url right after app is launched

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1193]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If browse any url right after launching an app then white screen is shown instead of loading page
![white browse](https://cloud.githubusercontent.com/assets/6584810/25885679/16ef2fe8-355a-11e7-9c12-553d51198a17.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Page is loaded
#### Actual behavior
[comment]: # (Describe what actually happened.)
White screen is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7ZS1tYTdRenpNeWs
- Open Status
- Open console
- @browse google.com -> white screen is shown. If browse same url again then page is loaded. Issue happens only on 1st attempt to browse page.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6-66
* Operating System: Android 7.0; Samsung Galaxy S7 and iOS 10.2.1 iphone6s
#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
[20171005 logcat 6.txt](https://github.com/status-im/status-react/files/988868/20171005.logcat.6.txt)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by annadanchenko** [comment]
If use @browse command first time then no hint text "URL" is shown. If use it second time then it's shown. It might be connected to this issue
![no hint](https://cloud.githubusercontent.com/assets/6584810/26057861/a6b76224-397b-11e7-851c-c07d33dfdda2.png)

**Comment by annadanchenko** [comment]
cant reproduce on 0.9.12
