### ISSUE TITLE
IOS failed to build

### ISSUE THREAD

**Issue by pinkfrog9** [status-im/status-react#11959]
Running `make run-ios` gives the following error output:
```
The error is: clang: error: no such file or directory: '/Users/john/Library/Developer/Xcode/DerivedData/StatusIm-dprrsbwjuoblntfqhwuqdhsmcaps/Build/Products/Debug-iphonesimulator/libRCTStatus.a'
Command Ld failed with a nonzero exit code
```
On macOs11.2.3 with the toolchain updated to the latest.

**Comment by churik** [comment]
@introom is it still relevant?

**Comment by pinkfrog9** [comment]
Not sure. You can close it for now (at least on my side, I haven't played with it thereafter).

**Comment by churik** [comment]
Thank you for quick response!
Be free to reopen it in case you need it
