### ISSUE TITLE
Add activity center

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#11958]
As a user
I want to have a activity center 
So incoming invitation/messages from new contacts can be grouped and don't pollute the chat area

### Description

Chats from non-contacts and new group chat invitation from non contacts should open in the activity center first, with an option  to accept, in which case they will be moved to the main chat view.

### Acceptance criteria

- A chat from a non-contact should open first in the activity center, and should not be shown in the main chat view.
- A group chat invitation from a non-contact should open in the activity center, and should not be shown in the main chat view.
- The user should be able to navigate on the activity center, and `Accept and add` or `Reject and delete` a 1-to-1 chat or a group chat from the activity center. If deleted it should not show anymore and if accepted it should show in the main chat area.

### Designs

https://www.figma.com/file/r59kCQxl6tlC0dHkcAJOpP/Action-center-MVP---Mobile?node-id=2%3A8012

**Comment by hesterbruikman** [comment]
One note of caution on the title. I prefer referring to this as Activity Centre to not set expectations that everything you get a 'notification' for will be displayed here. As especially for the time being it's only incoming chats from non-contacts. Potato, potato, but sometimes issues titles go into commits, go into blog posts, etc

**Comment by cammellos** [comment]
good point, thank you, updated

**Comment by errorists** [comment]
Catching up, this wasn't quite the idea I had for this, I believe we discussed with Andrey to have a list item placed on the chat list to group all new chats, especially once T2T kicks in, activity centre was supposed to be a springboard for incoming notifications and only that
Either way the linked UI isn't quite production level, @cammellos I would ask kindly to please let me know once any further, post-MVP work on this task is planned so I have time to redesign it beforehand.

**Comment by cammellos** [comment]
@errorists of course, we rushed it out to address the spam issue, but we'll appreciate your input so it's closer to your idea.
thanks
