### ISSUE TITLE
There is no way to backup seed phrase for additional wallets!

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#11953]
# Feature Issue

Have installed and created status  account a while ago, backed up seed phrase. Than created an additional wallet account. Yesterday have found “my acc totally broken”, on chat screen there are a lot of invites, non of chats I’m using opens. Reinstalled app and restored my acc with backup to find that MY ADDITIONAL WALLET IS MISSING AND THERE IS NO WAY RESTORE IT BECAUSE THERE IS NOW WAY TOO BACK UP IT’S SEED PHRASE AND EVEN IF THERE WAS SUCH A FEATURE I WAS NEVER ACKNOWLEDGED ABOUT IT. AS A USUALL DUMB APE I THOUGHT ALL MY PRECIOUS KEYS WERE SAFE NO MATTER WHAT!

### User Story

As a user i want:
1. to be able to back up all wallet/chat keys, no matter how and when there were created with clean understanding which of them i’m backing up;
2. to be notified that I MUST BACK UP wallet/chat keys and all other sensitive data;
3. an easy way to use the same wallet key with different chat keys and vise versa. Why do I create both with the same seed on start up but only wallet key when adding additional wallet? I want to switch chat identities and wallets separately of each other;

**Comment by nahuhh** [comment]
If you added an account from the wallet screen and selected "generate an account", the seed phrase for that account is the same as your original. 

Click generate an account again and it will come back. 

If you added an account by logging out and creating a new one, you should have the seed phrase...
Hope this helps 

- nah.uhh
