### ISSUE TITLE
iOS build failing with 'main.jsbundle does not exist'

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#11961]
The iOS nightly builds have been broken for several days because of:
```
▸ Processing Info.plist
▸ Generating 'StatusIm.app.dSYM'
▸ Running script 'Bundle React Native code and images'

❌  error: File /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle does not exist. This must be a bug with

    The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'boost-for-react-native' from project 'Pods')
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/IntermediateBuildFilesPath/StatusIm.build/Release-iphoneos/StatusIm.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)
[09:40:34]: Exit status: 65
```
Specifically `main.jsbundle does not exist`.

This started happening on the 3rd of April: https://ci.status.im/job/status-react/job/nightly/1903/

**Comment by jakubgs** [comment]
What's interesting is that there are no new commits recorded between build [1902](https://ci.status.im/job/status-react/job/nightly/1902/) and [1903](https://ci.status.im/job/status-react/job/nightly/1903/), and yet the former succeeded while the latter failed.

**Comment by jakubgs** [comment]
I tried purging the Jenkins workspaces with:
```
 > ansible ci-slave-macos -a 'rm -fr /Users/jenkins/workspace/status-react/combined/mobile-ios'
```
But it didn't help: https://ci.status.im/job/status-react/job/nightly/1909/

**Comment by jakubgs** [comment]
This error was mentioned in one comment in the PR that implemented use of `shadow-cljs`: https://github.com/status-im/status-react/pull/10217#issuecomment-617737277

**Comment by jakubgs** [comment]
According to the logs this is the script that failed:
```
/Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/IntermediateBuildFilesPath/StatusIm.build/Release-iphoneos/StatusIm.build/Script-00DD1BFF1BD5951E006B06BC.sh
```
And when I check it's contents I see this:
```
administrator@macos-03.ms-eu-dublin.ci.misc:~ % cat /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/IntermediateBuildFilesPath/StatusIm.build/Release-iphoneos/StatusIm.build/Script-00DD1BFF1BD5951E006B06BC.sh
```
```sh
#!/bin/sh
set -o errexit
export NODE_BINARY="node"
export NODE_ARGS=" --max-old-space-size=16384 "

bash -x ../node_modules/react-native/scripts/react-native-xcode.sh 2>&1 > ./react-native-xcode.log
```
Which is simply this:
https://github.com/status-im/status-react/blob/be0ad943eaf9807c79fae405c15a2a573d7ffc29/ios/StatusIm.xcodeproj/project.pbxproj#L526
And when i check the `ios/react-native-xcode.log` there's nothing useful in it:
```
administrator@macos-03.ms-eu-dublin.ci.misc:/Users/jenkins/workspace/status-react/combined/mobile-ios/ios % cat react-native-xcode.log 
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


React Native, please report it here: https://github.com/facebook/react-native/issues
```

**Comment by jakubgs** [comment]
I tried building locally with `make release-ios BUILD_TYPE=nightly` but it fails with some unrelated error:
```
ld: warning: directory not found for option '-L-L/Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-byxfyjmbslalemdeptottzdfriyp/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/BVLinearGradient'
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
	Ld /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-byxfyjmbslalemdeptottzdfriyp/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/InstallationBuildProductsLocation/Applications/StatusIm.app/StatusIm normal arm64
(1 failure)
make: *** [release-ios] Error 65
```

**Comment by jakubgs** [comment]
I fixed piping of logs into `ios/react-native-xcode.log` with:
```patch
diff --git a/ios/StatusIm.xcodeproj/project.pbxproj b/ios/StatusIm.xcodeproj/project.pbxproj
index f61fb41de..39ac5c0eb 100644
--- a/ios/StatusIm.xcodeproj/project.pbxproj
+++ b/ios/StatusIm.xcodeproj/project.pbxproj
@@ -523,7 +523,7 @@
                        );
                        runOnlyForDeploymentPostprocessing = 0;
                        shellPath = /bin/sh;
-                       shellScript = "set -o errexit\nexport NODE_BINARY=\"node\"\nexport NODE_ARGS=\" --max-old-space-size=16384 \"\n\nbash -x ../node_modules/react-native/scripts/react-native-xcode.sh 2>&1 > ./react-native-xcode.log\n";
+                       shellScript = "set -o errexit\nexport NODE_BINARY=\"node\"\nexport NODE_ARGS=\" --max-old-space-size=16384 \"\n\nbash -x ../node_modules/react-native/scripts/react-native-xcode.sh > ./react-native-xcode.log 2>&1";
                };
                1997449D1D0A7BEAADD6CEC8 /* [CP] Embed Pods Frameworks */ = {
                        isa = PBXShellScriptBuildPhase;
```
And I got back this:
```
+ BUNDLE_FILE=/Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle
+ node --max-old-space-size=16384 /Users/jenkins/workspace/status-react/combined/mobile-ios/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle --assets-dest /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


+ [[ false != true ]]
+ [[ ! -f /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle ]]
+ echo 'error: File /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```
https://ci.status.im/job/status-react/job/combined/job/mobile-ios/8856

**Comment by jakubgs** [comment]
This is the script that is being called: `node_modules/react-native/scripts/react-native-xcode.sh`

**Comment by jakubgs** [comment]
This issue seems to be exactly the same thing, and `react-native` version also matches: https://github.com/facebook/react-native/issues/31094

This comment - https://github.com/facebook/react-native/issues/31094#issuecomment-796743154 - indicates that the issue might be related to `PATH` and how `metro-bundler` identifies `watchman`.

**Comment by flexsurfer** [comment]
https://github.com/facebook/react-native/issues/31138#issuecomment-799415325

**Comment by jakubgs** [comment]
As per usual, it makes no fucking sense. But I'm gonna try some other things first.

**Comment by jakubgs** [comment]
Lol, I fixed it by doing:
```
 > ansible ci-slave-macos -a 'rm -fr /Users/jenkins/Library/Developer/Xcode/DerivedData'       
macos-01.ms-eu-dublin.ci.misc | CHANGED | rc=0 >>
macos-03.ms-eu-dublin.ci.misc | CHANGED | rc=0 >>
macos-02.ms-eu-dublin.ci.misc | CHANGED | rc=0 >>
```
https://ci.status.im/job/status-react/job/manual/128/

**Comment by jakubgs** [comment]
But the normal nightly failed...
https://ci.status.im/job/status-react/job/combined/job/mobile-ios/8858

![1440445292514](https://user-images.githubusercontent.com/2212681/113915520-2b9ad280-97df-11eb-8e61-0a21cd68c91b.jpg)

**Comment by jakubgs** [comment]
I don't know why either, but it seems like upgrading Fastlane - and some other gems - worked: https://github.com/status-im/status-react/pull/11967

But only for a manual nightly build: https://ci.status.im/job/status-react/job/combined/job/mobile-ios/8863
It failed for the PR build: https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-11967/2/

Makes no sense to me.

**Comment by jakubgs** [comment]
A second manual nightly build on the same commit failed: https://ci.status.im/job/status-react/job/manual/132/

So I think the first one worked only because it accidentally ran on a host on which had `~/Library/Developer/Xcode/DerivedData` removed.

**Comment by jakubgs** [comment]
As far as I can tell this is something specific to `nightly` builds, because PR builds seems to work fine:

![image](https://user-images.githubusercontent.com/2212681/114012154-43696980-9866-11eb-8ac9-c683ca2f2edd.png)

While `nightly` builds are failing:

![image](https://user-images.githubusercontent.com/2212681/114012191-4ebc9500-9866-11eb-8430-a7c913131fe7.png)

**Comment by jakubgs** [comment]
I tried running the `node ./node_modules/react-native/cli.js bundle` command with `--verbose` added but I see no addition log messages explaining why no output bundle is created. I might have to go back to the roots and add some `console.log()`s.

**Comment by jakubgs** [comment]
By doing dirty `console.log()` debugging I can see this function call never exists:
https://github.com/react-native-community/cli/blob/v4.10.0/packages/cli/src/commands/bundle/buildBundle.ts#L88
Which appears to be starting a Metro server:
```js
import Server from 'metro/src/Server';
```

**Comment by jakubgs** [comment]
And this appears to be the constructor of the server:
https://github.com/facebook/metro/blob/v0.64.0/packages/metro/src/Server.js#L124-L150

**Comment by jakubgs** [comment]
This line:
```js
    const metroBundle = await output.build(metroServer, requestOptions);
```
https://github.com/facebook/metro/blob/v0.64.0/packages/metro/src/index.js#L316
Calls `buildBundle`:
https://github.com/facebook/metro/blob/v0.64.0/packages/metro/src/shared/output/bundle.js#L21

**Comment by jakubgs** [comment]
As far as I can tell there's multiple async functions run by that Node process, and one of them exits with code 0, and kills the Metro bundle process before it finishes. I base that on different number of `console.log()` prints I get at different times without changing anything at all.

**Comment by jakubgs** [comment]
Now it seems to be hanging on this call:
https://github.com/facebook/metro/blob/v0.64.0/packages/metro/src/DeltaBundler/DeltaCalculator.js#L119

**Comment by jakubgs** [comment]
Now the behavior has changed on `macos-03`. I'm running this:
```
node --max-old-space-size=16384 \
    /Users/jenkins/workspace/status-react/combined/mobile-ios/node_modules/react-native/cli.js \
    bundle --entry-file index.js --platform ios --dev false --reset-cache \
    --bundle-output /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app/main.jsbundle \
    --assets-dest /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-gzbepwnrlqbukxbmmpfskimspfch/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/Release-iphoneos/StatusIm.app
```
And now it's getting stuck for no good reason, instead of exiting with `0` without creating the `main.jsbundle`.
Very, very confusing and annoying.

**Comment by jakubgs** [comment]
And now the nightly build worked even though I didn't change anything in the repo:
https://ci.status.im/job/status-react/job/nightly/1912/
All I did was clean up workspaces and `DerivedData`.

I swear. I hate iOS so much. So much.

**Comment by jakubgs** [comment]
And now I'm unable to reproduce the issue, either for the PR or the nightly build. This is so dumb.

**Comment by jakubgs** [comment]
And now it's fucked again: https://ci.status.im/job/status-react/job/nightly/1913/

**Comment by jakubgs** [comment]
Oh wait, but the error is different:
```
❌  /Users/jenkins/workspace/status-react/combined/mobile-ios/modules/react-native-status/ios/RCTStatus/RCTStatus.h:4:9: 'Statusgo.h' file not found
#import "Statusgo.h"
                                                      ^
▸ Compiling react-native-status-dummy.m
▸ Compiling RCTStatus.m

❌  /Users/jenkins/workspace/status-react/combined/mobile-ios/modules/react-native-status/ios/RCTStatus/RCTStatus.h:4:9: 'Statusgo.h' file not found

#import "Statusgo.h"
        ^~~~~~~~~~~~
```
Looks like #11951 now...

**Comment by jakubgs** [comment]
I'm not actually sure I fixed this permanently, but at least after merging #11967 the nightly build worked:
https://ci.status.im/job/status-react/job/nightly/1914/

**Comment by jakubgs** [comment]
The nightly has been green for a few days now:

![image](https://user-images.githubusercontent.com/2212681/114523093-47213580-9c44-11eb-9718-ad0af9ab551a.png)

So I'm going to close this for now, but knowing Apple this might be re-opened in the future.
