### ISSUE TITLE
"TypeError: Network request failed" when switching to Goerli network

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11964]
# Bug Report

## Problem

Originally the issue was reported by user:
> Can't connect to goerli testnet. Since rinkeby and ropsten work, I think the problem is that goerli has a blockscout url Set instead of infura RPC.
I also can't even set it up manually, as the "chain-id already defined"

#### Expected behavior

Can switch to Goerli network

#### Actual behavior

<img width="246" alt="Screenshot 2021-04-07 at 14 10 06" src="https://user-images.githubusercontent.com/67952253/113864250-f6748d00-97aa-11eb-84ad-74546e848ae4.png">

### Reproduction

- Open Status
- Navigate to `Profile` -> `Advanced` -> `Network` -> `Goerli`
- Tap `Connect`

### Additional Information

- Status version: Release 1.12.2, develop
- Operating System: Android, iOS

### Note
There is a similar issue but with a different error: https://github.com/status-im/status-react/issues/9688

**Comment by tennox** [comment]
It should at least be possible to add a custom goerli network.
But I also think it's just to fix the URL, as the blockscout URL is not an RPC one, afaik.

**Comment by qoqobolo** [comment]
@cammellos @jakubgs need your opinion here when you have time 🙏

Originally, the Goerli network was added in 2019 with the aim of switching from the Ropsten network to the Goerli (https://github.com/status-im/status-react/pull/7734 and discussion [here](https://discuss.status.im/t/replacing-ropsten-with-gorli-network-for-faucet-and-les-needs/1235)).
But it never happened, and we currently have no way to switch to Goerli and check if it works at all.

So the question is, do we still need this network in the Status app?
Should we fix it or maybe just remove it from the networks list? And also, probably we could add the possibility to add a custom Goerli network instead, as @tennox  suggests.

cc @flexsurfer @churik

**Comment by flexsurfer** [comment]
actually, we just need to use infura rpc, I think it shouldn't hurt a lot our infura usage, but might be useful for dapps developers

**Comment by jakubgs** [comment]
Goerli is still a much better network than Ropsten, and would be great for tests, but it lacks contracts we need for the app.

We do have our own goerli endpoints in CI infra tho: https://ci-goerli.status.im/secret-token-here

But Infura works too.
