### ISSUE TITLE
Wyre asks for required field that is not in the screen

### ISSUE THREAD

**Issue by eerlo** [status-im/status-react#11976]
# Problem

Wyre buy crypto webview asks for a required "reservationId" field. 

## Implementation

Open Wyre buy crypto option and try to complete the steps to buy crypto (Using BRL currency)
you will notice that you can't proceed with the purchase because it asks for a required field that is not in the screen.

![image](https://user-images.githubusercontent.com/1106118/114197324-99064a80-9928-11eb-952c-cabf33222734.png)

## Acceptance Criteria

The PR should fix this issue.

## Notes

Please test it with multiple currencies on IOS +Android.

## Future Steps

Asks for someone else to test it and make sure it works.

**Comment by eerlo** [comment]
Samsung Galaxy A51.
Android Version 10.
Android Webview version 89.0.4389.105.

**Comment by guylouis** [comment]
I have the exact same issue on any browser: brave on my mac, brave on my iphone, or status webview. John had the same issue this weekend too. 

Not sure anyone managed to make https://pay.sendwyre.com/ work

I looked at the wyre public doc but did not find any relevant info

Let's try to reach wyre team

**Comment by churik** [comment]
can be closed, as wyre removed from ramp options
