### ISSUE TITLE
webview can't access camera

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11972]
**Problem**: 
on android and iOS our users browsing buy crypto third party services from our banner, and thus in the webview, cannot access their device camera from the webview. Accessing the camera is important because it used at KYC level by these third party service

**Reproduction**:
- android: go to ramp, enter amount and an email, select wire transfer (for  instance), you're redirected to their KYC by passbase, the screen gets stuck on 
![image](https://user-images.githubusercontent.com/11461437/114154620-e2529c00-9920-11eb-8cb7-fbbb382f51e5.png)

- ios: enter amount and an email, select wire transfer (for  instance), you're redirected to their KYC by passbase, the kyc app asks for mic access, a camera recording is ongoing but with no picture taken

_Note_: 
- It seems that on some android devices there is a system setting accessible by the user Privacy and Security > Webview camera permission request, but if the user enbales it it does not solve the problem 
https://discord.com/channels/624205794384281629/626738033701683200/828628005944819752

- an other note about how we allow access to camera in status web browser (not webview) https://discord.com/channels/624205794384281629/780361414275366923/828907672295833600

**Comment by eerlo** [comment]
@guylouis the same problem happens for LATAMEX and MoonPay

![image](https://user-images.githubusercontent.com/1106118/114195805-2ba5ea00-9927-11eb-9a2d-060ecadc3388.png)
