### ISSUE TITLE
Webview in buy crypto can't access Latamex (cookie error) - iOS

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11974]
**Problem**: when browsing Latamex third party service with our webview, in buy crypto service, users can't access latamex service and get a message saying cookies should be enabled. 

**Reproduction:**
- on a ~~android~~ IOS device 
- click on buy crypto banner + latamex 
- enter an amount + your email, click 'comprar'
- you'll get such an error message 
![image](https://user-images.githubusercontent.com/11461437/114158382-e84a7c00-9924-11eb-8cfe-c09090ca4897.png)

_Note_
The problem does not happen on ~~iOS~~ android

**Comment by cammellos** [comment]
@guylouis I followed your instruction but I am not receiving the error, I reach a step where it asks me to validate my email. 
Did you reach the same step or the error occurred earlier?

**Comment by briansztamfater** [comment]
@cammellos @guylouis I think it is actually working on Android but not working on iOS and the description is mistaken

**Comment by guylouis** [comment]
Gosh @cammellos @briansztamfater you're right, I switched android and iOS in the description. 

This **works** in android 
This **does not work** on iOS 

Sorry for the confusion created

**Comment by guylouis** [comment]
Same issue on Safari in macosx ! Works fine with brave on macosx 
I will ping Latamex for guidance

**Comment by guylouis** [comment]
Closing this since the issue is not on status side
