### ISSUE TITLE
Buy crypto account selection screen modification for phase 1.5 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11999]
Phase 1 of Buy Crypto consisted of providing a list of third party services where our users could buy crypto with Fiat. 

Phase 1.5 brings:

- [ ] ux improvement: users can chose the wallet address they want to use with the chosen service 
- [ ] user can manually copy address for cases where selected address cannot be passed to 3rd party service
- [ ] an extra legal notice 
- [ ] requires updating the padding on the list item header

Designs are here: 
https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=10744%3A0

**Comment by guylouis** [comment]
out of our three service partner, for now only **Ramp** can allow to pass the wallet address as a parameter of the url called 

use UserAdress parameter detailed here https://docs.ramp.network/configuration#useraddress

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
