### ISSUE TITLE
No background for link preview in chat view when opening reactions panel

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11995]
# Bug Report

## Problem

When calling the reactions panel in chat view on Light mode, the link preview description doesn't have any background, so reading is slightly difficult.

#### Expected behavior

Light background or a different font color for better description readability

#### Actual behavior

<img width="289" alt="Screenshot 2021-04-14 at 17 29 37" src="https://user-images.githubusercontent.com/67952253/114737118-fe05da00-9d46-11eb-8fa4-3f77276e6ee9.png">

### Reproduction

- Open chat
- Send Youtube or Github link
- Enable link preview
- Long tap on the link message to open reactions panel

### Additional Information

- Status version: Nightly 14/04
- Operating System: Android, iOS

**Comment by churik** [comment]
relevant on 1.15
