### ISSUE TITLE
No custom user icon in Activity Center

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12007]
# Bug Report

## Problem

When user has `Appearance` -> `Show profile pictures of` -> `Everyone` and `Accept new chats from` -> `Anyone` chat requests which appears in `Activity Center` does not have custom user image if it was set. But it appears right away when open chat view. 

#### Expected behavior

Custom user icon is visible on the Activity Center view
#### Actual behavior

https://user-images.githubusercontent.com/8749671/115217372-1b9fbe80-a10e-11eb-8e0a-b99eacac4204.mov

### Reproduction

- Create two new users: UserA and UserB
- UserA enables `Profile` -> `Appearance` -> `Show profile pictures of `-> `Everyone` setting
- UserB sets custom profile image
- UserB sends text message to UserA
- UserA opes Activity Center where UserB's request is visible

### Additional Information

- Status version: develop 1.12
- Operating System: Android and iOS

**Comment by churik** [comment]
relevant on 1.15

**Comment by pavloburykh** [comment]
fixed. Tested on nightly 04/02/22.
