### ISSUE TITLE
Extend syncing period 

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12016]
As a user
I want to retrieve more than 24 hours of data
So that if I am offline for the weekend I will still be able to read old messages

### Description

We want to allow the user to retrieve more days of history without having to manually hit the gaps buttons.
The issue is that syncing is already fairly slow on 24 hours, so we need to strike a balance between fetching too much data and have slow syncing times, or fetch too little and miss messages.
Therefore we need to find a solution, and we need to see how much we can afford, ideally 7 days would be best, but that might not be possible.

A few ideas is to for example don't sync public chats for 24 days, but sync only one-to-one topics, which are the most relevant.
Or sync only up to X messages, but that might be tricky as we don't know how many messages are shown to the user until received.

Solutions might include some UX to reduce the impact on syncing cc @errorists

**Comment by cammellos** [comment]
This has been merged and implemented, users can select the sync period in`sync settings` to a day (default), three days, a week and a month.
Closing for now, eventually we might want to change the default once we better understand the bw requirements.

**Comment by n-boc** [comment]
Is it possible to emphasize in the UI that this can be changed in the settings? 

Also, is there a way to prevent pointless refreshing when all the messages have already been loaded? Maybe a channel could store the time of the first sent message -- or just the date of the first sent message. Any adversary that has access to the channel can get this information, so it doesn't seem to be compromising security
