### ISSUE TITLE
Naming validation for communities

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-react#12010]
As a user
I want to limit the number of characters available when creating community names/channel names/channel categories
So that the UI is not cluttered

### Description

Community names should allow anything and just limit to 30 characters

Channel names should allow anything besides:
 - spaces, they should be replaced as the user types with dashes `-`
 - Uppercase letter, they should be replaced by the lowercase counterpart as the user types
 - limit to 30 characters

If categories are also implemented, they should have the same limitations as channel names, if they are not implemented, this is out of scope for this taks.

**Comment by du82** [comment]
Lets not become Discord. Lets let the community be creative with custom fonts, spacing, and anything else they want. Communities aren't meant to be a clone of Discord servers, they're supposed to be innovative and unique, so lets be unique and not limit our users :)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
