### ISSUE TITLE
Group Chat names containing # break deep links

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12025]
## Problem

When a Group Chat is created with `#` in the name it breaks the deep link. For example:

https://join.status.im/g/args?a=0x0461f576da67dc0bca9888cdb4cb28c80285b756b324109da94a081585ed6f007cf00afede6b3ee5638593674fee100b590318fc7bdb0054b8dd9445acea216ad2&a1=#broken-group-name&a2=c3ba1620-eb44-4758-afc5-8853f8abdc73-0x0461f576da67dc0bca9888cdb4cb28c80285b756b324109da94a081585ed6f007cf00afede6b3ee5638593674fee100b590318fc7bdb0054b8dd9445acea216ad2

The reason for this is that URL arguments after `#` are not passed to the server, which then thinks it's missing arguments.
https://en.wikipedia.org/wiki/URI_fragment
https://www.w3.org/2001/tag/doc/hash-in-url-20080211.html

#### Expected behavior

Some options:

* Do not allow `#` character in group chat names
* Find some way of encoding the `#` character so it doesn't break the deep link.

#### Actual behavior

![image](https://user-images.githubusercontent.com/2212681/115553872-2f822680-a2ae-11eb-9f89-92679866f96e.png)

**Comment by churik** [comment]
No more links to group chat, closing issue
