### ISSUE TITLE
False error for 1:1 messages "not confirmed - tap for options"

### ISSUE THREAD

**Issue by nahuhh** [status-im/status-react#12028]
# Bug Report

#### Expected behavior
Messages that are confirmed with 2 checkmarks shouldnt change to show they are unconfirmed. 

#### Actual behavior

Confirmed messages show an error

![Screenshot_20210421_164439.jpg](https://user-images.githubusercontent.com/50635951/115619597-0ec3cc00-a2c2-11eb-8aba-0713c5ff2298.jpg)
### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

On 2 devices
-  set to sync to Wi-Fi only
- status nodes off
- device Wi-Fi disabled (using on mobile data) 
- enable notifications 
- send a few messages back and forth 
- remove the app from recent apps on one device 
- wait a while (10 minutes should be fine) 
- reopen status

### Additional Information

- Status version: 1.12.1 (20210324160131)

- Operating System: android 10

```
...
```

**Comment by churik** [comment]
@nahuhh thank you for reporting!
I believe it can be a consequence of https://github.com/status-im/status-react/issues/12192 - but anyway I'm unable to reproduce it on 1.15

Please, reopen if still relevant for you.
