### ISSUE TITLE
App crashes if continue to Reddit app while browsing reddit.com  

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1202]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: App crashes if browse reddit.com and Continue to download reddit app
![reddit](https://cloud.githubusercontent.com/assets/6584810/26007314/414d4ad0-3740-11e7-86cd-ae891d05a4a4.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Play Store is opened with reddit app
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashes
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7bmRWR2ZYMFJBTFE
- Open Status
- Open console
- @browse reddit.com
- after page is loaded popup is shown "View Reddit in the app..." 
- tap on button Continue on the popup

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android only

#### Logs

[20171205181427-logcat.txt](https://github.com/status-im/status-react/files/997357/20171205181427-logcat.txt)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x647e25066b9954bacd60c68162c36f7d540ef166](https://etherscan.io/address/0x647e25066b9954bacd60c68162c36f7d540ef166)
Network: Mainnet
Paid to: vizanto

**Comment by floAr** [comment]
Just checked on my Android Honor 8 with Andorid 7.0 and EMUI 5.0.1 everything works as expected.

**Comment by puilp0502** [comment]
Can confirm, Status crashes with ActivityNotFoundException. Using LG X300 with Android 7.0

**Comment by vizanto** [comment]
I have a fix. The problem lies in the webview fork https://github.com/status-im/react-native-webview-bridge - working on a PR now :)

**Comment by vizanto** [comment]
`package.json` refers to branch `react-native-webview-bridge.git#remove-status-go-2`, so that repository has to merge the fix.

**Comment by vizanto** [comment]
Trying to get bounty bot to work here:
Fixes #1202

**Comment by andytudhope** [comment]
@vizanto please will you log in to openbounty.status.im, go to the dropdown menu, select 'Payment Details' and make sure to update and save your Ethereum address so that we can confirm the payout to you for solving this issue? Thank you so much and here's to seeing you around these repos more often 😉

**Comment by vizanto** [comment]
Woohoo! Review took a while, but yes, you will see me more often :)

**Comment by andytudhope** [comment]
Haha, our bad - translations are a little more difficult to review. Submit some code and it should happen far quicker 😉
