### ISSUE TITLE
Create 1.13 release on github

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12035]
Once released in the play stores, we should create 1.13 release on github.

**Comment by guylouis** [comment]
seems done and can be closed right ? @cammellos

**Comment by cammellos** [comment]
Not yet, we need fdroid as well

**Comment by churik** [comment]
and now? :)

**Comment by cammellos** [comment]
still working on F-Droid release https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8879

**Comment by cammellos** [comment]
thanks @licaon-kter !
