### ISSUE TITLE
1-1 chat is displayed in Activity centre after opening if it was opened from public chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12043]
# Bug Report

## Problem

If User receives a message in 1-1 chat that is displayed in the Activity Center, but opens it from the public chat, then that chat will be displayed in both the Activity Center and the Home screen after opening.

#### Expected behavior

Once opened, chat isn't displayed in the Activity Center, no matter what screen it was opened from.

#### Actual behavior

https://user-images.githubusercontent.com/67952253/116097567-8cb11a00-a6aa-11eb-9700-3bb7f427a3c3.mp4

### Reproduction

User A:
- Join public chat
- Send a message
- Start 1-1 chat with User B
- Send a message
User B:
- Check that 1-1 chat with User A appeared in the Activity Center (don't open it)
- Join the same public chat
- Tap User's A username to open his profile
- Tap `Chat` to start 1-1
- Send a message
- Navigate to the Activity Center to check that the 1-1 is still displayed in the Activity Center

### Additional Information

- Status version: Nightly 26/04
- Operating System: Android, iOS

**Comment by cammellos** [comment]
@errorists what's the expected behavior?

**Comment by errorists** [comment]
whoa, I needed to watch the video like 5 times to wrap my head around it. 

> Once opened, chat isn't displayed in the Activity Center, no matter what screen it was opened from.

I think that's the expected behaviour. You initiate a private conversation with a contact, meaning you accepted to engage with that person, it's moved to regular chat list from out of Activity Centre. or am I missing something?

**Comment by churik** [comment]
The issue is that it is not moving - it is presented in Activity Centre + it is presented in chat list on home view.

Still the case on 1.15, but it is matter of clicking on it in Activity centre, so definitely low-priority
