### ISSUE TITLE
replace react/text by quo/text

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#12048]
component | status-im.ui | usage | descr | quo | usage | descr |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
text | status-im.ui.components.react/text | 75% |   | text | 25% |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

remove `status-im.ui.components.react/text` namespace

**Comment by churik** [comment]
@flexsurfer still makes sense in terms of new component library?
