### ISSUE TITLE
Buy Crypto: Webview doesn't allow access to web3 wallet (LocalCryptos)

### ISSUE THREAD

**Issue by eerlo** [status-im/status-react#12041]
### User Story

As a user, I want to buy cryptos using LocalCryptos on the Buy Crypto webview.

### Description

*Type*: Bug

*Summary*: The webview from the Buy Crypto feature doesn't give us web3 access to the wallet, and LocalCryptos need it.
If we go on LocalCryptos.com using the web3 browser, everything works pretty nice. They even have a good integration with Status, showing our logo.

#### Expected behavior
It should allow me to connect with my Status Wallet form the webview.

#### Actual behavior
It doesn't allow me to connect with my Status Wallet form the webview.

### Reproduction
- Open Status
- Go to the wallet tab
- Click on " Buy Crypto"
- Choose LocalCryptos
- Try to connect your wallet

### Solution
*Summary*: Make sure the Buy Crypto webview let me connect to my wallet when I need to.

### Additional Information
* Status version: v1.12
* Operating System: Android and IOS

**Comment by flexsurfer** [comment]
in that case, we could just open LocalCryptos in the Status browser instead of Buy Crypto webview ?

**Comment by guylouis** [comment]
closed - because we decided to remove localcryptos from the buy crypto list. It will of course still be available from dap.ps and in this case opens the browser which obviously works well with web3
