### ISSUE TITLE
Badger dao dapp not working on status

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12054]
# Bug Report

## Problem

I am not able to stake Badger on the badger dao app https://app.badger.finance/

#### Expected behavior

I am able to complete the staking flow.

#### Actual behavior

Issue 1: It takes some time for the dapp to show my badger balance.
I am able to deposit badger, but I am not able to stake, the balance gives me 2100 (I only have 4.9 badger in my wallet) and I am unable to stake.

### Reproduction

-  Have some badger in your wallet 
- Go to the badger dao website
- Connect your wallet with status
- Click on Badger coin
- Click on deposit
- Wait for the confirmation
- Click on Stake

**Comment by shivekkhurana** [comment]
When I try to connect to Badger via Status, it says "Connecting to an unsupported network"

<details>
  <summary>📷  View Screenshot</summary>
  
![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 17 20 13](https://user-images.githubusercontent.com/1925158/124467458-81b6ec00-ddb5-11eb-9967-0abc8c2dbe2a.png)
</details>

If I ignore the Badger UI and use Status browsers menu to connect, the browser says that Ethereum is connected but Badger apps says it isn't.

<details>
  <summary>📷  View Screenshot</summary>
  
![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 17 23 03](https://user-images.githubusercontent.com/1925158/124467730-deb2a200-ddb5-11eb-97c5-c8d050a42c42.png)

</details>

edit: False alarm, I was on xDai not on mainnet.

**Comment by flexsurfer** [comment]
@churik do you know if we have test account with badger ?

**Comment by churik** [comment]
No, we don't have any. Will look if I can buy some

**Comment by rasom** [comment]
<img width="344" alt="Screenshot 2022-02-23 at 14 45 23" src="https://user-images.githubusercontent.com/2364994/155401369-38367d4a-5f15-4b19-a239-18cbe13f28fa.png">

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
