### ISSUE TITLE
move toolbar to quo

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#12051]
component | status-im.ui | usage | descr | quo | usage | descr |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
toolbar | status-im.ui.components.toolbar | 40 occurr. |   | - |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

remove `status-im.ui.components.toolbar` namespace

**Comment by churik** [comment]
@flexsurfer does it make sense in terms of new component library?
