### ISSUE TITLE
Add gesture for iOS to navigate back and forward (swipe from left edge to right and in opposite direction)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1205]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Add gesture for iOS to navigate back by swiping from the very left edge of the screen to right. Also, when you swipe in opposite direction (from right edge to the left) then it should go to the next page (like tap on forward button)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When webview is opened with DApp/webpage then 
- swipe from the very left edge of the screen to right shows previous page (same as tap on back button)
- swipe from the very right edge of the screen to left shows next page (same as tap on forward button)
#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing happens if swipe from left/right
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Console 
- browse google.com and search for "search". Open any found link
- swipe from the very left edge of the screen to right -> currently, nothing happens
- tap on back button
- swipe from the very right edge of the screen to left -> currently, nothing happens
- Open Auction House DApp and navigate to several pages there. 
- swipe from the very left edge of the screen to right -> currently, nothing happens

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android

**Comment by denis-sharypin** [comment]
Closed, will be partly fixed in #3804
