### ISSUE TITLE
Alignment issue for strings in different languages

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12068]
Status is developed with english as a default language for design/copy. When strings are being translated in different languages, it happens that they get too long and wrongly aligned 

This issue can be used as a placeholder to list them 

1. Keycard first onboarding screen in portuguese

![image](https://user-images.githubusercontent.com/11461437/116670472-0e9d8d80-a9a0-11eb-9368-3b3a72a769ac.png)

**Comment by churik** [comment]
Suppose it makes sense to review it again after new re-design, closing for now
