### ISSUE TITLE
Allow user to edit messages

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12067]
As a user
I want to be able to edit messages
So that I can correct any mistake I have made

### Description

We want to allow users to edit their own messages, the trigger is through a long press on the message, which will show an `Edit` entry. 
Backend work is also required. Please mind that a user receiving and edit might not have the original message, or might retrieve them out-of-order, so care must be taken that messages are not duplicated.

### Designs

https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4968%3A641

**Comment by nahuhh** [comment]
Perhaps "delete and replace" could be the underlying function of the "edit" button.
Which would

Messages 1-9, need to edit message 8. 
1. Delete the message, making note of the preceding and following messages(7 and 9) + timestamp
2. Create a new message placing between message 7 and message 9 and displaying a additional timestamp for the time it was edited (displaying with timestamps)
3. A "delete" button would automate the process, replacing the message with "message deleted" text. 

I do believe the delete feature to be one and the same as this and should be included. 
Inadvertent messages are the worst. (Sending to the wrong person).

**Comment by cammellos** [comment]
This has been merged and will be in 1.15
