### ISSUE TITLE
If User joins a group chat and leaves it after, he won't receive a new invitation to the same group chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12079]
# Bug Report

## Problem

If User1 receives an invitation to a group chat created by User2, joins and leaves it, then he won't receive re-invitation from User2 to the same group chat. It will not appear in either the Action Center or the Home screen.

#### Expected behavior

User can receive re-invitation after leaving group chat

#### Actual behavior

User cannot receive re-invitation

### Reproduction

User1:
- Add User2 to contacts
- Create a group chat with User2

User2:
- Navigate to the Activity center
- Join the group
- `Three dots` at the top right
- `Leave chat`

User1:
- `Three dots` at the top right
- `Group info`
- `Add members`
- Add User2

User2:
- Check Activity center and Home screen

### Additional Information

- Status version: Nightly 04/05
- Operating System: Android, iOS

**Comment by churik** [comment]
relevant on 1.15
