### ISSUE TITLE
Typing , ( or ) shows suggestions for web3 and console 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1207]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If type "," or ")" "(" then suggestions for web3 and console are shown 
![suggestions](https://cloud.githubusercontent.com/assets/6584810/26055096/a9d63a22-396f-11e7-8405-09f0cf755e72.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No suggestions are shown if type "," "(" or ")"
#### Actual behavior
[comment]: # (Describe what actually happened.)
If type "," or ")" "(" then suggestions for web3 and console are shown 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7VEhaOGU1XzhOZFU
- Open Status
- Open Console
- Type , 
- Delete all and type  ( 
- Delete all and type  )

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
Issue can be reproduced on develop build with integrated fix:
1. Type ")" -> suggestions with console and web are shown
2. Type "a(" or "a," -> suggestions with console and web are shown

**Comment by oskarth** [comment]
@annadanchenko My bad. Will have another go at it.

Re 2: do you know what valid suggestions there are that incorporate '(', ')', or ','? Want to make sure I don't introduce any regressions for more complex suggestions.

**Comment by rasom** [comment]
Regarding
> Type "a(" or "a," -> suggestions with console and web are shown
it doesn't look like a problem, i suppose that the problem is that when i continue typing `a,something` both console and web3 are still shown (but they shouldn't be)
