### ISSUE TITLE
Assets are displayed as "..." in the individual account view if that account does not contain them

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12078]
# Bug Report

## Problem

If User has some tokens in the primary account (Ethereum account in the video below) but doesn't have them in the additional account (Account 1), then when opening Account 1 these tokens will be displayed as `... SNT`/`... USD`.
Thus, there is a similar design for the loading state and for assets that are not present in a particular individual account. 

#### Expected behavior

- Display this state in a different way than loading status
- Probably only show assets that are in the current individual account

#### Actual behavior

https://user-images.githubusercontent.com/67952253/116887209-57687700-ac2a-11eb-81a0-246daf0bdab8.mp4

### Reproduction

- Open Status
- Recover multiaccount with several assets
- Open Wallet
- Add a new account

### Additional Information

- Status version: Nightly 03/05
- Operating System: Android, iOS

cc @errorists your opinion is needed. Take a look when you have time, please.

**Comment by errorists** [comment]
those `…`look weird and not cool at all, I'll ping our wallet champion @carlfairclough to provide direction

**Comment by carlfairclough** [comment]
If the user doesn't hold the assets inside that account, then they shouldn't be displayed at all.

While in a loading state (when there are assets), I don't think there is much to be done and we should address it in a wider design update for Status (e.g. with content placeholders in loading states: https://codepen.io/nurulishlah/pen/beEGVE)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
