### ISSUE TITLE
Deleted 1-1 chat is opened when tapping on push notification of this chat after deleting (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12070]
# Bug Report

## Problem

If User receives a push notification for a 1-1 chat, deletes this chat without tapping the push notification (it remains in notification service), and taps the push notification, then deleted chat will be opened. 

#### Expected behavior

Redirect to Home screen

#### Actual behavior

https://user-images.githubusercontent.com/67952253/116688326-da819700-a9b6-11eb-8546-5a19d8a3b9b4.mp4

### Reproduction

User1:
- Enable push notifications
- Start 1-1 chat with User2
- Send a message
- Open the Home screen

User2:
- Send a message to 1-1 chat with User1

User1:
- Long tap on the chat to delete it from the chat list
- Pull down and tap the push notification

### Additional Information

- Status version: Nightly 30/04
- Operating System: Android

**Comment by churik** [comment]
That seems fine to me and will be resolved after fix for https://github.com/status-im/status-react/issues/11001
