### ISSUE TITLE
Old versions in Google Play and F-Droid

### ISSUE THREAD

**Issue by nahuhh** [status-im/status-react#12074]
Google play and F-droid are distributing old versions. Staying up to date is a manual process or not possible if running the f droid version (different signature from apk release)

Latest available from f droid is 1.12.1.2021031517

Google play is showing June 23, 2020 as the latest update, supplying version 1.4.0.

![Screenshot_20210430_142534.jpg](https://user-images.githubusercontent.com/50635951/116738358-5502e480-a9c0-11eb-8f65-5957d4d012d4.jpg)
![Screenshot_20210430_142519.jpg](https://user-images.githubusercontent.com/50635951/116738376-5c29f280-a9c0-11eb-88a6-e74a6e5935b8.jpg)

**Comment by cammellos** [comment]
Hi @nahuhh 
f-droid will always be a bit slower to update as we only push it to f-droid once it has been released on the stores.
On play store it's only a naming issue, we promoted from beta and play store assigned the wrong version to it, as it automatically bumped it for us, we need to use a different scheme, but the apk is the most up to date.
thanks for spotting this.

**Comment by nahuhh** [comment]
@cammellos 
Apologies if I'm misinformed 🙏 but I do believe f-droid has the ability to periodically scan the status github and automatically pull releases, then build, sign and push them to f-droid (automatically). 
Iirc, there is a bit of a delay but is(?) relatively hands free after set up

Take care

**Comment by chaserene** [comment]
the current [F-droid release](https://f-droid.org/en/packages/im.status.ethereum/) (1.20.3) is almost 1.5 years old.

considering that you don’t PGP sign your releases either, your complete release supply chain is vulnerable to interference via three corporations we all know and love.

please re-open.

**Comment by cammellos** [comment]
@chaserene thanks for the message, I'll make sure that F droid version is up to date (1.20.6) and start the process. Thank you and I'll keep you posted

**Comment by chaserene** [comment]
thanks a lot, @cammellos.

judging by the release page, 1.20.6 is alpha and the latest release (2.29.0) is beta. if that’s correct, why not go for the newer and more stable 2.x.x branch?

**Comment by cammellos** [comment]
@chaserene I think that's 1.26.0 (alpha), while we would be releasing 1.20.6, which is just a minor bugfix. 

We are planning to get 2.30.0 out in the stores, which will be the first major release in a year or so around early/mid august, and that will be available on fdroid, but first we'll try to get 1.20.6 out on fdroid since as you pointed out we haven't released there in a while

**Comment by nahuhh** [comment]
Why not release the v2 version to fdroid as betas?

**Comment by chaserene** [comment]
@cammellos I’m sorry, you’re right, that’s 1.26.0 I was looking at.

1.20.6 hasn’t been released or even tagged on Github. may I ask why?
