### ISSUE TITLE
Blank screen when app.uniswap.org loads in browser

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12086]
# Bug Report

## Problem

Uniswap app doesn't work in Status. Apparently they changed something in app UI, because it has blank screen in 1.11 and 1.12 release version as well (where it was working in the past)

#### Expected behavior

Uniswap loads fine in Status browser
#### Actual behavior

Blank screen when app.uniswap.org loads in browser

https://user-images.githubusercontent.com/8749671/117279010-f29b5f80-ae69-11eb-81d8-a78848f75081.mov

### Reproduction

- Open Status and create new account
- Open in browser app.uniswap.org

### Additional Information
- Status version: any (1.11/1.12/1.13
- Operating System: Android and iOS

**Comment by cammellos** [comment]
This seems to be due to an error on ethers.js
https://github.com/ethers-io/ethers.js/issues/1484

The version used by uniswap is 5.1.0, and it's fixed in 5.1.3, not sure we can do much about it for now, other than contacting the developers.

**Comment by cammellos** [comment]
Other people have the same issue:

https://github.com/Uniswap/uniswap-interface/issues/1447

replied there.

**Comment by Serhy** [comment]
Fixed on Uniswap side
