### ISSUE TITLE
After leaving of user community list of members is not updated 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12087]
# Bug Report

## Problem
After leaving community user remains and is shown as a member of community.

#### Expected behavior
1 member

#### Actual behavior
2 members

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- As user A: create "Require approval" community, invite user B
- user B: Join community, leave community
- user A: check amount of members in community

### Additional Information
- Status version: nightly 06/05/2021
- Operating System: Android, iOS

**Comment by cammellos** [comment]
Currently that's the expected behavior, leaving a community will not change membership requirements so the user is free to re-join at any time without admin intervention. 
This will likely change in phase 3, so closing for now, feel free to re-open if necessary.
