### ISSUE TITLE
Pop-up "Backup successful" appears in the restore/create new Keycard multiaccount flow and makes login impossible (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12088]
# Bug Report

## Problem

There are two possible scenarios for reproducing this problem, but in both cases it **_reproduces sporadically_**:

1. If User deletes Keycard-multiaccount without deleting keys from Keycard via `Privacy and security` settings, then he won't be able to recover this multiaccount with Keycard. After entering PIN the pop-up `Backup successful` will be shown and login will be impossible. 
2. If User creates new Keycard-multiaccount using `Return card to factory settings`, then after seed phrase confirmation (entering two words) the pop-up `Backup successful` will be shown and completion of the multiaccount creation process will be impossible.

#### Expected behavior

Eliminate redundant pop-up not related to these scenarios

#### Actual behavior

Video for scenario 2:

https://user-images.githubusercontent.com/67952253/117284469-21fc9d00-ae67-11eb-8776-27f158ac6453.mp4

### Reproduction

Scenario 1:
- Recover Keycard-multiaccount
- `Privacy and security` > `Delete my profile` > uncheck `Delete keys from Keycard` > Delete profile
- Recover the same multiaccount with Keycard
- Enter pairing code and 6-digit passcode
- _Sometimes_ on this step the pop-up "Backup successful" appears
- Check the multiaccount

Scenario 2:
- Create a new Keycard multiaccount using `Return card to factory settings` option
- Create and confirm 6-digit passcode
- Save PUK, pairing codes, and seed phrase
- Confirm two words of seed phrase
- _Sometimes_ on this step the pop-up "Backup successful" appears
- Try to complete the multiaccount creation process

### Additional Information

- Status version: develop, probably 1.13
- Operating System: Android

#### Logs

Logs for Scenario 1:
[geth.log](https://github.com/status-im/status-react/files/6433917/geth.log)
[Status.log](https://github.com/status-im/status-react/files/6433918/Status.log)

cc @bitgamma

**Comment by bitgamma** [comment]
@qoqobolo I can reproduce this 100% if I go to a keycard account, press "create backup keycard" and then go back without proceeding and perform one of the scenarios you mentioned. Should be an easy fix, working on it now

**Comment by bitgamma** [comment]
@qoqobolo should this be closed?

**Comment by qoqobolo** [comment]
@bitgamma sure! I'll close it.
