### ISSUE TITLE
Share community link (desktop) contains extra C in the Url , which is not clickable on mobile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-react#12084]
Encountered and described in https://github.com/status-im/status-desktop/issues/2501

We need to align the pattern of the link for sharing community link so it looks the same on mobile and desktop 

![image](https://user-images.githubusercontent.com/82375995/117255455-574ac000-ae52-11eb-9d21-4789f8e3db61.png)

**Comment by cammellos** [comment]
I think this is not relevant, sorry for the confusion https://github.com/status-im/status-desktop/issues/2501#issuecomment-833297617 feel free to re-open if I missed something
