### ISSUE TITLE
No complains from Console if enter text that starts with "web3." or "console." e.g. web3.aaa

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1209]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Console returns no error message if enter non-existing method call. For example: web3.waaa or console.Ctext. Expected: error message returned
![no error](https://cloud.githubusercontent.com/assets/6584810/26056211/9dfccd74-3974-11e7-94c5-f9ca7b4a3efd.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Console returns some error message if enter non-existing method call like web3.a
#### Actual behavior
[comment]: # (Describe what actually happened.)
Console returns nothing
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Console
- Send "web3.a" 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS

**Comment by oskarth** [comment]
Accidentally merged/closed, to be tested in develop.

**Comment by churik** [comment]
suppose that this issue can be related to #2622

**Comment by churik** [comment]
At the moment just for invalid input started with web3. it returns "undefined" message
![img_0040](https://user-images.githubusercontent.com/4557972/34049721-20b09026-e1c1-11e7-8c4f-a3d84719d2cd.jpg)
Checked with IOS and Android build 0.9.11d443 (15.12.2017)
