### ISSUE TITLE
Remove chose storage screen from onboarding

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12101]
Onboarding include a screen where the user choses where he stores his seed (on the phone or on the keycard). In order to reduce the number of screens in the onboarding we want to remove this screen, and add in an entry point in an existing screen to the keycard flow for users that want to create or import a seed in a keycard. 

See discussion and rationale here: https://discord.com/channels/624205794384281629/706881441744552107/841222721853194270

A design is needed. It needs to show the entry point mentioned above (on which screen it's located, what's the copy)

**Comment by churik** [comment]
closing due to re-design
