### ISSUE TITLE
Prevent creating channels with the same name within community

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#12107]
# Feature Issue

Channels with the same name currently can be created within community

### User Story

As a community admin, I want to be prevented from creating a channel with already existing name **so that** I don't introduce ambiguities. 

### Acceptance Criteria

It is impossible to create channels with the same name within community

### Current Behavior

![Screenshot 2021-05-11 at 13 17 09](https://user-images.githubusercontent.com/5786310/117799823-34a61600-b25b-11eb-9622-d0ef964db258.png)

**Comment by churik** [comment]
should be the part https://github.com/status-im/status-react/issues/12010
