### ISSUE TITLE
Support more ERC20 in default list 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12104]
Status app currently supports a default list of ERC-20 tokens. See [here](https://github.com/status-im/status-react/blob/3fd36c6904ec8c75391e8386bb6c000b193598f8/src/status_im/ethereum/tokens.cljs) the list.
- there are about 150 tokens (approx) and this list 
- it was initially setup 3 years ago
- there was ponctual maintenance (add some important tokens, change some tokens metadata) since then. 

**Problem** we are to provide our users an updated, quite exhaustive list of ERC-20 tokens. 

Other elements:
- a format has emerged https://tokenlists.org/ to create list of ERC-20 tokens. 
- This format is used by a couple of projects like kleros (about 700 tokens), coingecko (about 4000 tokens), 1inch (1000 tokens), uniswap, coinmarketcap to keep an updated list of common erc20 tokens 
- uniswap in particular allows their users to chose which of these tokenlists they want to list
- among those lists only kleros use logos stored on ipfs

**Roadmap** 
we aim to: 
1/ update this list (up to date, more complete)
2/ design a system where the user can chose its own lists. Btw Status might build its own list, decentralized and curated by Status users. 

**First Goal**
Fix 1/

Questions:
- are there performance consequences of using a 1k-4k list of tokens ? 
- can we build a tool that converts one token list (e.g. coingecko list) into our own format (and it would grab pictures and have them downloaded into our own assets) ? if we do, will we run this at each new build ? 

cc @cammellos @flexsurfer

**Comment by flexsurfer** [comment]
> are there performance consequences of using a 1k-4k list of tokens ?

defenetly , but we should check code for details

> can we build a tool that converts one token list (e.g. coingecko list) into our own format (and it would grab pictures and have 
them downloaded into our own assets) ? if we do, will we run this at each new build ?

yes we can do it for each new build

there is also infura calls, we'll have to scan all tokens for balances , so it will be 4k calls per user

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
