### ISSUE TITLE
No hint text for @browse and /location commands

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1210]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If app is run not first time then there is no hint text for @browse (expected URL as hint) and /location (expected Address as hint)
![browse no hint](https://cloud.githubusercontent.com/assets/6584810/26059294/8b6cbd6a-3981-11e7-8a0a-70da0a53924c.jpg)
![location no hint](https://cloud.githubusercontent.com/assets/6584810/26059293/8b5b712c-3981-11e7-8d5c-85c429ab2fb5.jpg)

Note: if send @browse command first time then blank screen is shown (#1193). If use @browse command second time then URL as hint text is shown. However, for location command hint text is not shown even after it was used

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Hint "URL" is shown for @browse
Hint "Address" is shown for /location
#### Actual behavior
[comment]: # (Describe what actually happened.)
if type /location then there is empty line after it, no hint is shown, same for @browse
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status not 1st time
- Open console
- type @browse or select it from commands. check if URL is shown after it
- delete browse command
- type /location or select it from commands. check if URL is shown after it Address

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS

**Comment by occamin** [comment]
Working on this in #1239. Will keep the PR updated as I make progress
