### ISSUE TITLE
ENS is lost after relogin when starting 1-1 chat with an ENS user from the search bar on the Home screen without adding him to contacts

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12125]
# Bug Report

## Problem 

If starting a new 1-1 chat with an ENS user from the search bar on the Home screen, but don't add this user to contacts, then ENS will be lost in the chat list and 1-1 chat view after relogin.

#### Note
Sometimes ENS turns into a 3-words name immediately after the chat is opened

#### Expected behavior

ENS is shown after relogin

#### Actual behavior

https://user-images.githubusercontent.com/67952253/118798331-cf2ad880-b89d-11eb-8283-6c68a4715848.mp4

### Reproduction

1. Open Status
2. Enter ENS to the search bar on the Home screen
3. Tap the suggested user to start 1-1 chat
4. Re-open Status

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

Leftover from #12100 
cc @briansztamfater

**Comment by churik** [comment]
not reproducible anymore on nightly 27/07/22
