### ISSUE TITLE
Limit types of communities to 'Require Approval'

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12128]
Currently an admin I can create a community, and chose among three types (see screens below): require approval, require invite from an other member, no requirement

![IMG_0C4F47438FD8-1.jpeg](https://images.zenhubusercontent.com/5eb28af232777f28c9e414e2/2d4492e0-6086-43e7-b1d3-442963ce1c48)
![IMG_8CB12FCCA8F0-1.jpeg](https://images.zenhubusercontent.com/5eb28af232777f28c9e414e2/23083a0d-7a9a-4322-9f84-973758a107ff)

Problem:
-  it has created some confusion on what the admin can expect from each of those community types. Neither admins or users understand in an easy manner what are the rules to invites and share the community with new users
- these 3 types will be revamped in phase 3

Solution 
- we have decided to use only the 'require approval' type of community 
- to avoid any more any confusion before we get to phase 3, the only choice for the user should be 'require approval'. 

Possible implementation
- in the first screen above, have 'require approval by default'
- in the first screen above do not allow to click and go to the second screen

**Comment by cammellos** [comment]
This has been fixed in develop
