### ISSUE TITLE
Can't send @browse command if space is typed before url

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1212]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If type a space before url in @browse command then 
1. Hint text "URL" is shown over typed url
2. Tap on send icon does nothing. Expected: space is ignored and command with url can be sent

![browse space](https://cloud.githubusercontent.com/assets/6584810/26063576/af5058ce-398e-11e7-8d48-f17059656fb7.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
space in the beginning of url is ignored and command with url can be sent
#### Actual behavior
[comment]: # (Describe what actually happened.)
1. Hint text "URL" is shown over typed url (on Android). Hint hides first 3 letters of url (on iOS)
2. Tap on send icon does nothing. 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open console
- tap on @browse command ( if url hint is not shown then send @browse google.com once because of #1193 )
- type " " (space)
- type some valid url
- tap on send

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS

**Comment by occamin** [comment]
Hey @GustavoNunes, mind if I grab this one?

**Comment by jeluard** [comment]
Hi @occamin ! I already started working on it! Sorry..

**Comment by occamin** [comment]
Hey @jeluard, sure thing. Enjoy!
