### ISSUE TITLE
Community links should be unfurled in chat

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12132]
**Issue:** when a user receives a community link in chat, the link is not unfurled

![image.png](https://images.zenhubusercontent.com/5eb28af232777f28c9e414e2/be2e7ed2-b5ff-4aa2-b5c5-f2d59e9b9821)

**Comment by vkjr** [comment]
@guylouis, this link has a mistake. There should be only one `c` character. `join.status.im/c/XXXX`

Excerpt from related code in `status-react`:
```
(def links {:public-chat        "%s/%s"
            :private-chat       "%s/p/%s"
            :community-requests "%s/cr/%s"
            :community          "%s/c/%s"
            :group-chat         "%s/g/%s"
            :user               "%s/u/%s"
            :browse             "%s/b/%s"})
```

**Comment by guylouis** [comment]
ok interesting, the link was copy pasted from desktop 
It probably means the links generated on desktop doesn't have the good format ? and 'cc' should be replaced by 'c' ? 
@jrainville 
@anastasiyaig

**Comment by guylouis** [comment]
oh wait it's been fixed three days ago: https://github.com/status-im/status-desktop/issues/2580
I'll close this issue then

**Comment by anastasiyaig** [comment]
@guylouis it is known issue and already fixed in https://github.com/status-im/status-desktop/pull/2576 , please check latest master: https://join.status.im/c/0x03087a139185be1ecb5546120d4cb443edc7d14e171f8776a949d90ab4937faf53
