### ISSUE TITLE
Can't change PIN code in the Keycard account if biometric login is enabled / password is saved

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12137]
# Bug Report

## Problem 

`You're unauthorized to perform this operation` pop-up is shown while attempting to change PIN if biometric login was applied to this Keycard multiaccount or password was saved.

#### Notes

To reproduce this issue, re-login is required after first enabling the biometric login/saving the passcode. 

#### Expected behavior

Can change PIN

#### Actual behavior

<img width="262" alt="Screenshot 2021-05-21 at 14 18 41" src="https://user-images.githubusercontent.com/67952253/119136038-72ffba00-ba3f-11eb-87b3-0bc38c9bfe1d.png">

### Reproduction

1. Recover Keycard multiaccount
2. Log out
3. Enable biometric login / Save password (`Don't ask for card to sign in` checkbox)
4. Log out and re-login
5. Open Settings > Keycard > Change 6-digit passcode

### Additional Information

- Status version: nightly 21/05
- Operating System: Android, iOS

**Comment by qoqobolo** [comment]
cc @bitgamma

**Comment by bitgamma** [comment]
as a note, it can also be reproduced without biometric login, by logging in with saved password and restarting the app

**Comment by qoqobolo** [comment]
@bitgamma thanks for the clarification. The description is updated.
