### ISSUE TITLE
Lock 'Require approval' type of community and show it on Edit community screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12147]
# Problem
Currently from mobile it is possible to create 3 types of community, while from desktop only 1 is allowed('Require approval' type, which is approved for phase 2)
Discussion is [here](https://github.com/status-im/status-desktop/pull/2565#issuecomment-846833735)

## Acceptance Criteria
- make possible to create only 'Require approval' community type (lock field in UI, desktop screen as an example)
![unknown](https://user-images.githubusercontent.com/4557972/119493350-65f50a80-bd60-11eb-9674-797a41b41313.png)

- show community type on edit community screen

**Comment by churik** [comment]
cc @vkjr

**Comment by cammellos** [comment]
@churik after a discussion with @errorists, we think it's best to hide the option completely, as being the only one, it might confuse the user or give them a sense that there will be further types in the future.
