### ISSUE TITLE
Android "Share" intents

### ISSUE THREAD

**Issue by nahuhh** [status-im/status-react#12148]
# Feature Issue

### User Story

Current unable to share, say, a picture, to a contact or to create a new status

1. Opening gallery
2. Share

Expected
3. Select "status - chat" and "status - new status"

Duplicate of: #4605 (4yrs old)

**Comment by nahuhh** [comment]
@briansztamfater 

Any way to prioritize this?
(Trying to use status as a daily driver isnt ~~possible~~ painless without)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration

**Comment by nahuhh** [comment]
@churik should i bump this in a few months?

**Comment by churik** [comment]
sure, be free! But as we're working on a complete redesign of the app right now, likely we'll get back to it afterward
