### ISSUE TITLE
Last used command is shared between accounts on same device

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1214]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Last used command is shared between accounts on same device. Command {A: "first"} is sent by user A in Console. After this user A closes app and user B opens app on same device. If user B types "{" in Console then Last used command shows  {A: "first"}. Expected: user B can't see last used command of user A

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
 user B can't see last used command of user A
#### Actual behavior
[comment]: # (Describe what actually happened.)
 If user B types "{" in Console then Last used command shows  {A: "first"}
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7N1hrSTdFV0ZNS0E
- As user A
   - Open Status
   - In console send command {A: "first"} or any other like web3.net.version
   - switch users
- As user B
   - Open Status
   - In console type first symbol from command used by user A. E.g if it was  {A: "first"} then type {. check if last used command from user A is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS

**Comment by occamin** [comment]
I'll pick this one up. @annadanchenko would you mind labelling this as in progress?

**Comment by occamin** [comment]
Hey @annadanchenko, I've had a look at this. The solution is going to be affected a bit by the changes being added during the hackathon so I'm going to pause on this for a bit and pick up something else.

**Comment by annadanchenko** [comment]
can't reproduce on nightly build March 19 (Android and iOS)
