### ISSUE TITLE
Allow user to onboard to a website after install

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12162]
As a user
I want to be redirected to a website after I install the app
So I can have a better onboarding experience

### Description

After installing, if installed through a particular link, we should be able to redirect a user to a specific website opening the status-browser.
We had similar mechanism with chats, and this will involve changing the referral service and create a new type of links likely.

**Comment by hesterbruikman** [comment]
Update following conversation on [Discord](https://discord.com/channels/624205794384281629/704741763729850529/847673247016812595)

- Ability to redirect to a website has been implemented
- Two issues remain:
     - UI currently includes StarterPack reference 
     - Bug; likely the referral contract is called

For the UI, some design work is needed if either partner branding and/or informing the user of pinging the referral service is required. If neither of these are requirements, the existing 'Open in Status // Open in Android' dialog can be used.

### Current

![Screenshot_20210528-105910](https://user-images.githubusercontent.com/35233054/119962159-0ccae800-bfa7-11eb-84f7-166164f34866.png)
![Screenshot_20210528-105845](https://user-images.githubusercontent.com/35233054/119962163-0d637e80-bfa7-11eb-92bf-2c8a54369217.png)

**Comment by guylouis** [comment]
@cammellos as a note and as discussed on discord, we need to confirm if the URL we redirect to can include a parameter or not

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
