### ISSUE TITLE
Missing delete wallet option

### ISSUE THREAD

**Issue by jovancosta-zz** [status-im/status-react#12161]
# Problem
It's not possible to remove a wallet from the app.

Given the user wants to delete a wallet
When user tries to do it
Then there is no option to do it

In case the user imports other wallets, user will keep this wallet as junk on his main page.
The user should be free to add and remove wallets at any time.

### Where should it be implemented?
Desktop and Mobile

## Implementation

Include a removal button or option at the menu
A strong remind warning must also be presented to the user

## Acceptance Criteria

Considering status will create a default wallet option:
- User must be able to remove any wallet, that is not the default one, except this wallet is the last and only left.
- User must confirm, that user knows the wallet will disappear from the app

## Notes

Check other wallets as benchmark.

Given the user wants to delete a wallet
When he clicks at removal button or option
Then the app will present a modal with a warning
When the user clicks at Yes
Then the wallet is removed from the app
And the user return to the main page

Given the user wants to delete a wallet
When he clicks at removal button or option
Then the app will present a modal with a warning
When the user clicks at No
Then the wallet is not removed from the app
And the user returns to the main page

## Future Steps

On-Going operations must be considered
Test Cases must be created
Issue must be validated

**Comment by churik** [comment]
feature-request is a follow-up after https://github.com/status-im/status-react/issues/11468 - not sure that we need to keep it open. 
cc @flexsurfer

**Comment by flexsurfer** [comment]
hey @jovancosta , thanks for the issue, is it important for you to remove the keys, or hiding wallet will be enough, so you can show it later if you want?

**Comment by jovancosta-zz** [comment]
Most wallets have the delete key option. 
I don't remember seeing one that offers to hide.
The main idea is to remove.

I don't know if you have a place where you could start a pool and consider the opinion of other users.
But this could be a good approach to evaluate what is the most preferable for Status users.
