### ISSUE TITLE
Onboarding UX: When importing an existing account, users are afraid to loose their seed phrase

### ISSUE THREAD

**Issue by eerlo** [status-im/status-react#12167]
# Feature Issue

### User Story

As a user, I want to feel secure putting my 12-word to import an existing account.

### Description

![image](https://user-images.githubusercontent.com/1106118/120034211-1bc78f80-bfd3-11eb-826a-1c52a0fabf3a.png)

Right after putting the 12 words to import an existing account, users are asked to "re-encrypt" the keys. Users are not proceeding at this step because they think it will change their 12-words seed phrase somehow, when in fact it will just encrypt them to store securely on the phone, using the password to be able to decrypt when needed.

### Acceptance Criteria

We should just make it clear, changing the copy of this screen. We have plenty of available space to make it as clear as possible.

**Comment by churik** [comment]
closing due to re-design
