### ISSUE TITLE
Webview is opened in half-screen instead of default "almost-fullscreen" size

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1217]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sometimes, webview for different DApps is opened on half screen. It's not yet clear how to reproduce it, however each testing day it happens ~4-5 times. If open same DApp again then it will be shown as expected (almost full-screen).
 
![half screen](https://cloud.githubusercontent.com/assets/6584810/26097086/a95cbb34-3a23-11e7-8843-7188fa0fac3c.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
DApp is opened almost in fullscreen (see picture for Expected)
#### Actual behavior
[comment]: # (Describe what actually happened.)
DApp is opened in half-screen 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7RmI3ZDdKWkFEekE
- Open Status
- Open Maker Market or Wallet 
- Sometimes, DApp is opened in half-screen

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android. Didn't see it on iOS (yet)

#### Logs

[20171605101136-logcat.txt](https://github.com/status-im/status-react/files/1003702/20171605101136-logcat.txt)

**Comment by rohithpr** [comment]
Steps to reproduce:

1. Go to contacts tab
2. Select any contact (augur in this case)
3. Dapp in just half a page
4. Closing and opening it again by entering the command works fine.

**Comment by flexsurfer** [comment]
In progress
