### ISSUE TITLE
Don't show 'Fetch more messages' in group chat at the beginning of chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12172]
# Bug Report

## Problem 
When group chat just created right after `You create the group [gr_name]` there is a `Fetch more messages` option which does nothing upon tap. 
In a case of upgrading from previous release there is an endless `Loading...` instead "Fetch more messages"  in Group chats 
#### Expected behavior
No 'Fetch more messages' in group chat at the beginning of chat

#### Actual behavior
'Fetch more messages' in group chat at the beginning of chat
<img width="230" alt="Screenshot 2021-05-31 at 15 27 59" src="https://user-images.githubusercontent.com/8749671/120193399-0d70b200-c225-11eb-9cc6-76f1ce68cfe7.png">

### Reproduction

1) Open Status and create new account
2) Create any group chat (no need even to add any user)

### Additional Information

- Status version: nightly 1.13.0 (20210426081529)
- Operating System: Android and iOS

**Comment by cammellos** [comment]
@Serhy this one should also be fixed, could you please check?

**Comment by Serhy** [comment]
This is fixed (in https://github.com/status-im/status-react/pull/12169), and looks good in Develop now.
