### ISSUE TITLE
support mutual contact requests 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12175]
design is here: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=19780%3A321

rationale (design brief): https://docs.google.com/document/d/1d5zdPR2_Jn2EZmKNQVNsc7sUoLk4DXPN7Gch3CnYkaE/edit

**Comment by guylouis** [comment]
_note_: this one is needed to allow initiation of mobile-desktop chats 
https://docs.google.com/spreadsheets/d/1Jq1Rdnfn5oy17vzZ0onbhcfv2GOqouqxZHCPfeUcr6w/edit?ts=60c0db56#gid=0

**Comment by cammellos** [comment]
This is ready to be picked up again, backend specs are now ready (ish) if anyone wants to implement it https://github.com/status-im/specs/pull/154
