### ISSUE TITLE
Endless 'Loading...' for members in communities public chats instead 'Fetch more messages'

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12177]
# Bug Report

## Problem 
When community member invites user to community with chat, and user accepts invite - once new member opens the chat view from community - there is an endless `Loading...` at the top of the chat.
It's all OK for community admin though.

#### Expected behavior
Fetch more messages in the community chat for members

#### Actual behavior
Endless `Loading...` for members in communities public chats instead 'Fetch more messages'

https://user-images.githubusercontent.com/8749671/120216033-2c7c3d80-c23f-11eb-97ca-bd627b7df342.mov

### Reproduction

1) Create two users: UserA and UserB
2) UserA adds UserB in contacts
3) UserA creates community 
4) UserA invites UserB into community (open community  ->`...` button at top right -> `View profile` -> top-right 'Share' -> select user -> `Share`)
5) UserB opens 1-1 chat with UserA and taps `View` -> `Request access`
6) UserA open community -> `...` button at top right -> `View profile` -> `Members` -> Membership requests -> tap `Accept` 
7) UserA in community taps `(+)` -> `Create a channel` -> enter valid name -> `Create`
8) UserB opens newly created channel 
 
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
@Serhy this might be fixed in development, would you mind having a look when you have time please?
Thanks!

**Comment by Serhy** [comment]
Correct, it's fixed in latest develop `1.14.0 (20210602065931)`, thanks @cammellos, closing this issue

**Comment by Serhy** [comment]
Correct, it's fixed in latest develop `1.14.0 (20210602065931)`, thanks @cammellos, closing this issue
