### ISSUE TITLE
Comunities autoenables once user re-logins to account

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12176]
# Bug Report

## Problem 
`Profile` -> `Advanced` -> `Comunities enabled` option is disabled by default. And it's true for newly created user. However, once user re-login to account, this option auto-toggles in `ON` state. Even if to toggle it back into `OFF` -> relogin and `ON` again. 

#### Expected behavior
`Profile` -> `Advanced` -> `Comunities enabled` -> `OFF` by default
`Profile` -> `Advanced` -> `Comunities enabled` -> kept in `OFF` state after relogin UNTIL it's enabled into `ON` state

#### Actual behavior
`Profile` -> `Advanced` -> `Comunities enabled`  turns into ON state each time user relogins to account

https://user-images.githubusercontent.com/8749671/120209600-8b3db900-c237-11eb-97ae-e6a8d147efed.mov

### Reproduction

1) Open Status
2) Create new account
**Actual result = Expected result:** `Profile` -> `Advanced` -> `Comunities enabled` = `OFF`
3) Re-login to account
**Actual result:** `Profile` -> `Advanced` -> `Comunities enabled` = `ON`
**Expected result:** `Profile` -> `Advanced` -> `Comunities enabled` = `OFF`
4) Switch off communities by `Profile` -> `Advanced` -> `Comunities enabled` -> turn `OFF` toggle butoon
5) Re-login to account
**Actual result:** `Profile` -> `Advanced` -> `Comunities enabled` = `ON`
**Expected result:** `Profile` -> `Advanced` -> `Comunities enabled` = `OFF`

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
@Serhy the issue is slightly different, 
communities should be ON by default on PRs, so the bug is that is OFF when you create an account.
On release, it should be always OFF until enabled, I will check that as well.
