### ISSUE TITLE
Redirect to browser from wallet QR scanner

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12195]
As a user, when I am using the wallet scanner on the main wallet screen (see below) and I am scanning an URL, Status should open status browser. 

notes: 
- current behaviour: it shows an error invalid address
- when the QR code scanner is used to fill up the to field of a transaction in send/choose recipient , and a URL is scanned, it should not redirect to the browser. 

![IMG_A0D233717BC5-1](https://user-images.githubusercontent.com/11461437/120665247-e4058f80-c48b-11eb-8a46-33651c6f00b1.jpeg)

**Comment by hesterbruikman** [comment]
fyi @Ferossgp implemented a universal QR code scanner. It's under the plus-button

**Comment by guylouis** [comment]
note: I could not open a URL with the chat universal QR code scanner which under the plus button in chat (tested with v1.14)

**Comment by hesterbruikman** [comment]
We might be talking about different requirements:
- scan QR of join.status.im, for example https://join.status.im/b/dap.ps
- scan QR of dapp url

**Comment by guylouis** [comment]
indeed
-  https://join.status.im/b/dap.ps opens
- https://dap.ps does not open
 
I created an issue to support this second case 
#12222
