### ISSUE TITLE
Mute can't be enabled and leads to disappering of 1-1 chat  until relogin

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12191]
# Bug Report

## Problem 

Mute button doesn't work visually, and after muting 1-1 chat disappears from home screen until relogin.
Not reproducible on 1.13

#### Expected behavior
Can mute user

#### Actual behavior
When tapping on mute: 

https://user-images.githubusercontent.com/4557972/120653058-a2bbb280-c480-11eb-9693-4f7e1f7cd124.mp4

### Reproduction

1) User А: create chat with User B
2) User A: open options > View profile > Mute

### Additional Information

- Status version: RC 1.14 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
Fixed, it should be ready to be tested
