### ISSUE TITLE
No response if use 'Select from gallery' after access to photos was denied

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1220]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is no response from the app when user taps on Select from gallery to choose profile picture after access to photos was denied. Expected: same as for camera, there is popup wth explanation where to turn on access to photos. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After user denied access to photos on 1st attempt to select pictures from Gallery and repeats this attempt, app should show popup with explanation how to turn on access to photos
#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing happens when user taps on Select from Gallery
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7c2x1WHRGTTloZUE
- Open Status first time
- Open Profile
- Edit Profile
- Edit profile picture
- tap on Select from Gallery. As a result, popup is shown "Deny/Allow" access to photos
- Deny access to photos
- Tap on Select from Gallery again. 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: iOS only
OS: iOS 10.3.1
Device: iPhone 7 plus

**Comment by lukaszfryc** [comment]
@annadanchenko @rasom I'm now able to reproduce it on iOS on latest nightly (March 1). I've not checked Android. Should we reopen this issue?
