### ISSUE TITLE
New user with new install - require user ToS opt in

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12206]
When a user downloads Status for the first time, he needs to approve terms of services before being able to proceed with using the app. 

**Design** 
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=9665%3A33134

**Notes** 
- the checkbox is unchecked by default, the user must check it before being able to continue 
- Terms of Services link is https://status.im/terms-of-service/ and should be displayed in a webview 
- Privacy policy link is https://status.im/privacy-policy/ and should be displayed in a webview

**Comment by shivekkhurana** [comment]
This explicit checkbox will only be visible on the first multi-account, not for keys that are generated later or alternate on-boarding routes.
