### ISSUE TITLE
No contact request in Activity Center after 1-1 chat deleted of non-contact user

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12218]
# Bug Report

## Problem 
If to delete 1-1 chat of the non-contact request the next time this contact sends a message it does not appear in Activity Center.

#### Expected behavior
1-1 chat re-appears in Activity Center upon the next message sent disregard when the 1-1 chat being deleted

#### Actual behavior
No 1-1 chat in Activity Center upon the next message sent if this 1-1 chat of non-contact deleted from chat list

### Reproduction

1) Create UserA and UserB
2) UserA adds UserB in contacts
3) UserA sends text message to UserB
4) UserB opens Activity Center and taps on 1-1 contact request
5) UserB taps `...` chat menu at top-right -> `Delete Chat`
6) UserA sends text message to UserB again
7) UserB verifies whether UserA's chat request appears in Activity Center

### Additional Information

- Status version: nightly/release 0.14 
- Operating System: Android and iOS

Logs: when received contact reuqest -> open 1-1 chat -> delete and UserA sends message again:
[geth.log](https://github.com/status-im/status-react/files/6630785/geth.log)
[Status.log](https://github.com/status-im/status-react/files/6630786/Status.log)

**Comment by churik** [comment]
Fixed in #12231
