### ISSUE TITLE
Group and Community -  "double names" when content has a "nickname"

### ISSUE THREAD

**Issue by nahuhh** [status-im/status-react#12213]
# Problem

Contacts who you have given a nickname are showing both nickname and status name. 

## Implementation

For a contact with a nickname, in all circumstances, only the nickname should be shown. 
![Screenshot_20210609_130117.jpg](https://user-images.githubusercontent.com/50635951/121398431-56aabb00-c923-11eb-8dda-4d4db6aaa662.jpg)

**Comment by churik** [comment]
closed, as it is by design
![image](https://user-images.githubusercontent.com/4557972/127157919-f715893e-b1e4-45cf-92b4-6898796ce8db.png)

**Comment by nahuhh** [comment]
I think it is ok when the user has a custom name (@Carmen in your screenshot, for example) but when I rename my dad, I don't need to see "hotpink arrow crab" ...
