### ISSUE TITLE
Add password validation for Restore Access flow 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1224]
### User Story

As a user I should not be able to login with a password that doesn't match security criteria (ex. password length <6 symbols)

### Description

*Type*: Bug

#### Expected behavior
[comment]: As a user I should not be able to proceed with a password that doesn't match security criteria (ex. password length <6 symbols)

#### Actual behavior
[2017_05_18_16_50_28 - logcat.txt](https://github.com/status-im/status-react/files/1011101/2017_05_18_16_50_28.-.logcat.txt)
[comment]: I am able to login with insecure password , for ex. "1" after I restore an access to account

### Reproduction
[comment]: https://drive.google.com/open?id=0B7h1U1joPifRazlFaEgxeU9lc2M

- Open Status
- Set up a password 
- Copy the secure phrase
- Tap Switch Account
- Tap Restore Access
- Enter the secure phrase and enter insecure password (like "1")
- Tap Restore Access
- Select newly created account and proceed with the newly created password

### Solution
Add the password validation for Restore Access flow exactly the same as for the setting up new password flow

### Additional Information
* Operating System: Android
* Status version: 0.9.7+
* [2017_05_18_16_50_28 - logcat.txt](https://github.com/status-im/status-react/files/1011117/2017_05_18_16_50_28.-.logcat.txt)

**Comment by poiga** [comment]
I am working on this.

**Comment by poiga** [comment]
What if someone set short password already. Will they be able to login?
