### ISSUE TITLE
Unexpected notification in Activity Center when mention of my account received in Group Chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12250]
# Bug Report

## Problem 
When user receives mention of own account into already joined Group Chat - there is notification displayed on Activity Center. Nothing in Activity Center view when opening it. 
All fine in 1-1 / Public chats.
All fine if to send any other (text/image/sticker) message

#### Expected behavior
No notifications in Activity Center when mention of my account received in any Group Chat
#### Actual behavior
Notification on Activity Center icon when mention of my account received in any Group Chat

https://user-images.githubusercontent.com/8749671/123292964-37637e80-d51c-11eb-971a-8637efc68a1b.mov

### Reproduction

1) Create two new accounts: UserA and UserB
2) UserA adds UserB in contacts
3) UserA creates Group Chat with UserB
4) UserB joins into GroupChat
5) UserA sends mentioned UserB in message
6) UserB verifies Activity Center notification icon on Chats view

### Additional Information

- Status version: develop 1.14.0 (20210624055928) 
- Operating System: Both Android and iOS

**Comment by Serhy** [comment]
Turns out https://github.com/status-im/status-react/pull/12227 fixes this issue. Let's close this issue after 12227 is merged.

**Comment by cammellos** [comment]
The root cause of this might be the same as issue 2 on https://github.com/status-im/status-react/pull/12231 
There's a bug in status-go, I will fix in that PR.
