### ISSUE TITLE
Browser deeplinks don't open in Android when Status is installed but killed

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12252]
**Intended behaviour**
- status is installed 
- status app is killed 
- user scans a QR code with the system browser
e.g https://join.status.im/b/www.google.com/search?q=status
![image](https://user-images.githubusercontent.com/11461437/123405081-c66aa800-d5a9-11eb-9df9-45ee2f301823.png)
- status opens and shows in browser

**Current behaviour**
- after scanning QR code, status is opened, but status opens on chat screen
- if user switches to the browser no link is opened 

**Reproduction**
- uses today's nightly (25/06/2021)
- use google lens for scanning

**Notes**
- on iOS (tested with iOS nightly, and iOS native camera as a scanner)  we have the intended behaviour
- when testing please use URLs with parameters like www.google.com/search?q=status, because we need to make sure that parameters are taken into account when our deeplinks are opened

**Comment by churik** [comment]
@guylouis 
it works for me on both Android 10 and IOS on 1.15.
After scanning QR I'm redirected to chat view > open in Status > can see  google search with 'Status', which is expected behavior.

Please, reopen if it still reproducible for you.
Thanks!
