### ISSUE TITLE
No unread message counter if to open chat view and quickly close it

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12251]
# Bug Report

## Problem 

In a case you open chat view but quickly close it (like realising you opened wrong chat) leads to next received message in this have having no unread counter. Any chat 1-1/public/group affected.
All fine after re-login.
Can't reproduce on iOS, apparently because any actions with buttons while chat view opens are not responsive (can't do a "quick open-close" on iOS)

#### Expected behavior
Unread messages are present counter if to open chat view and quickly close it

#### Actual behavior

https://user-images.githubusercontent.com/8749671/123393539-da60da80-d5a6-11eb-9d05-07b2be95e3b3.mov

### Reproduction

1) Create two new accounts UserA and UserB
2) UserA creates 1-1 chat with UserB
3) UserB adds UserA so 1-1 chat it's present on Chats main view
4) UserB staying on Chats view quickly opens and closes 1-1 chat
5) UserA sends messages to UserB

### Additional Information

- Status version: nightly 
- Operating System: Android only

**Comment by flexsurfer** [comment]
@Serhy is it still relevant?
