### ISSUE TITLE
No 'Request access' view opens when tap on community invitation posted inside another community (Android only)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12254]
# Bug Report

## Problem 
If someone posts invitation link to join some community in community chat, - users who tap upon 'View' button doesn't have redirect to 'Request access' view. 
Everything is fine if to post the same link in public or any chat. 

All fine with release 1.14 build

#### Expected behavior
'Request access' view opens when tap on community invitation posted inside another community

#### Actual behavior
<img width="256" alt="Screenshot 2021-06-25 at 15 00 56" src="https://user-images.githubusercontent.com/8749671/123423059-bbbf0b80-d5c7-11eb-9e35-b06f4cffd657.png">

### Reproduction

1) Create new UserA and UserB
2) UserA creates TWO new communities (CommunityA and CommunityB)
3) Create a channel in the CommunityA  (`CommunityA_channel`)
4) Invite UserB into CommunityA
5) UserB accepts invitation and so both UserA and UserB in CommunityA now can see and post the posts in `CommunityA_channel`)
6) UserA copies invitation link to **CommunityB** (Open community -> `...` -> `Community Info` -> tap on join.status.im community link to copy it)
7) UserA posts invitation link to CommunityB in the `CommunityA_channel`
8) UserB opens CommunityA_channel and taps on `View` button

### Additional Information

- Status version: nightly 
- Operating System: Android and iOS

**Comment by qoqobolo** [comment]
@flexsurfer 
Another issue looking related to the described one.

If follow the invitation link to the community that you have already joined before or that you have created, open the channel, then tap `back` twice, `Unknown - Not a contact` screen will be opened.

**_Steps:_**
- Join a community with a channel via invitation link (e.g. from a public chat)
- Reopen chat with the invitation link
- Tap `View`
- Open the channel
- Tap `back` twice

https://user-images.githubusercontent.com/67952253/123615715-db437780-d805-11eb-92e8-cf1c994b7c26.mp4

**Comment by qoqobolo** [comment]
The issue with `View` button is reproducible again on Android in nightly build 01/09.

cc @flexsurfer

**Comment by churik** [comment]
Initial issue and https://github.com/status-im/status-mobile/issues/12254#issuecomment-869544380 are not reproducible on nightly 27/072022
