### ISSUE TITLE
Keycard UI issues after RNN

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12260]
# Bug Report

#### ISSUE 1: 'Change PIN / PUK / Pairing Code' screen reappears after changing it. Android only 
When changing PIN or PUK after making the changes "Enter PIN" screen opens again, when changing the pairing code - the same screen remains open without the ability to press the back button.

https://user-images.githubusercontent.com/67952253/123821219-808c4780-d8fb-11eb-9866-71004c908b05.mp4

---

#### ISSUE 2: `Change pairing code` button is overlaid with text. iOS

<img width="262" alt="Screenshot 2021-06-29 at 17 13 49" src="https://user-images.githubusercontent.com/67952253/123823327-605d8800-d8fd-11eb-85f2-4700b1dcec5f.png">

---

#### ISSUE 3: `Confirm the passcode` screen reopens after a successful backup on Android

_Steps:_
- Settings > Keycard > Create a backup Keycard
- Complete the flow

https://user-images.githubusercontent.com/67952253/123825244-0cec3980-d8ff-11eb-924d-2c4eaa611a6e.mp4

---

#### ISSUE 4: Notifications screen appears twice during onboarding after recovering multiaccount with Keycard. More visible on Android
If recover a multiaccount with Keycard and quickly tap `Maybe later`, the notifications screen will be opened again. If just stay a little on the notification screen, it blinks.

https://user-images.githubusercontent.com/67952253/123826162-ce0ab380-d8ff-11eb-9c6f-75f3e42c0b9b.mp4

cc @flexsurfer

**Comment by flexsurfer** [comment]
**Issue 5** When tapping Back button from `Reset passcode` view  - error `function (a0) { [bytecode] is not ISecuble}`
**Reproduction:**
1) Create new Keycard account
2) From `Profile` -> `Status Keycard` -> `Change 6-digit passcode` -> enter wrong PIN three times in a raw so Keycard is frozen
3a) From `Profile` -> `Status Keycard` open any of PIN / PUK codes.
OR (same view could be opened from)
3b) From Wallet -> `Your Keycard is frozen Reset card access` at the top of wallet view.
<img width="236" alt="Screenshot 2021-06-30 at 14 03 46" src="https://user-images.githubusercontent.com/8749671/123959625-0f11cf00-d9b7-11eb-89ec-7d5ff07b057a.png">

**Comment by churik** [comment]
One more issue (not related to keycard, but decided to add it here):
**ISSUE 6** if you enter invalid recovery phrase  (i.e. Acess  existing keys > Recovery phrase) after dismissing popup all phrase is erased and you need to enter it 2nd time
