### ISSUE TITLE
"Not found" when open community invitation which just received in the chat (takes long time to resolve it in chat)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12271]
# Bug Report

## Problem 
When the invitation link to community received in chat, - when I tap the link it opens Community `Not found` view. 
It takes some time so the `Request access` view be shown. 
In the chat as "indication" of the `Request access` will be shown is the `View` button appeared in chat upon join community link. 
It depends how much time community invitation will work, but 10 seconds minimum it takes minimum.
 

#### Expected behavior
'View' button is shown right away when Join community link received in chat
Opening community link just received in chat opens 'Request access' view 

#### Actual behavior

Trimmed only last minute in below video but it took 5+ minutes:

https://user-images.githubusercontent.com/8749671/124296118-47a1dc00-db62-11eb-90da-5401acf61a96.mp4

### Reproduction

1) Create two new accounts: UserA and UserB
2) Both users join the same public chat or meet each other in 1-1 chats
3) UserA creates community
4) Copy invitation link (in created community -> `...` -> `Community info` -> `tap upon join.status.im... link` to copy it)
5) UserA sends this link chat
6) UserB opens this chat and taps upon this link right away. Also, wait till `View` option appears on chat

### Additional Information

- Status version: nightly 
- Operating System: Android and iOS

**Comment by flexsurfer** [comment]
@Serhy  can't replicate

**Comment by churik** [comment]
Not reproducible on nightly 24/11/2021
