### ISSUE TITLE
After editing message sticker and audio buttons are not shown in chat input until reopening chat view

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12277]
# Bug Report

## Problem 
When sending edited message, buttons "Audio" and "Stikers" are not shown in chat input.
To make them display you need to type smth and then clean chat input or reopen chat view.

#### Expected behavior
can see chat input with  "Audio" and "Stikers" after message sending

#### Actual behavior
https://user-images.githubusercontent.com/4557972/124473907-29292400-dda0-11eb-8c11-6dbaa6aa476a.mp4

### Reproduction

1) Open Status
2) Open 1-1 chat
3) Send message
4) Edit message and pay attention to chat input after editing

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by bitgamma** [comment]
@churik would it be OK if the bug is fixed, but the keyboard is closed after sending the edited message like it happens when you cancel editing?

**Comment by churik** [comment]
IMO yes, it will be better
