### ISSUE TITLE
Add validation for Seed Phrase in the Restore Access flow

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1228]
### User Story

As a user I want an ability to restore my account using my previously generated secure phrase

### Description

*Type*: Bug

*Summary*:  Secure Pharse field is only checked for NOT NULL value. No other validation present

#### Expected behavior
[comment]: Add the following validation: 
- exact count of words entered in Secure Phrase field should be 12
- no dot, comma, numbers, special characters entered

#### Actual behavior
[comment]: the Secure Pharse field is only checked for NOT NULL value. Once any information is entered user is able to proceed

### Reproduction

https://drive.google.com/open?id=0B7h1U1joPifRQ242OGZ1cXZyWHM

Open Status
Set up a password
Remember the secure phrase
Tap Switch Account
Tap Restore Access
Enter anything in the Secure Phrase field and enter password
Tap Restore Access

### Additional Information
Operating System: Android
Status version: 0.9.7+ (http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-e16b93.apk)
[2017_05_20_23_50_32 - logcat.txt](https://github.com/status-im/status-react/files/1016506/2017_05_20_23_50_32.-.logcat.txt)

**Comment by annadanchenko** [comment]
@asemiankevich for expected result: maybe add validation that 
1. 12 words are entered? not less not more...
2. no other symbols are enetred (dot, comma, number..)
 Not sure what extra things we can do

**Comment by asemiankevich** [comment]
i did see several Instabug reports for this as well so we may want to fix this unless it is redesiged with onboarding, then lets close it @annadanchenko

**Comment by asemiankevich** [comment]
@denis-sharypin is there any redesign for restore access? asking if the issue is worth fixing

**Comment by annadanchenko** [comment]
Also need to provide explanation text for the user (here should be only 12 words)

**Comment by gravityblast** [comment]
@annadanchenko @asemiankevich another thing we can do is following [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic) and allow users to put 12, 15, 18, 21, or 24 words based on the entropy they had when created. 
In Status we actually always create 12 words, but users could be able to create the wallet outside of it.

Another interesting thing is that the words are part of a known set of 2048 words, so we could also validate the words in case the user misspells some.

**Comment by denis-sharypin** [comment]
Conditionals: 
— check special characters (dot, comma, numbers, etc)
— check the misspelling of words

If one (or both) of this conditionals are true, we show:
`Please double check`

cc @jeluard 

<img width="502" alt="screenshot 2018-05-25 17 10 24" src="https://user-images.githubusercontent.com/6559881/40551916-8a9ffc1e-603e-11e8-9780-9ee765e233bc.png">

**Comment by jeluard** [comment]
There is no finite set of words that we can use across all wallet implementations as any is free to choose a different so we should rule this out.

The main issue we were having is people not providing the correct number of words.
When do we want to show this message then? All the time we don't have enough words?
Also how about enabling/disabling the `Next` button?

**Comment by jeluard** [comment]
After discussing with @denis-sharypin , we will do the following:

* enable / disable the next button based on passphrase words count
* sanitize all extra spaces
* incorrect characters prevent users to hit `next` 

So the error message won't be used (at least with current design).
