### ISSUE TITLE
📦 Mobile release - 1.15.0

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#12289]
Issue to manage mobile release 1.15.0

### Scope
[comment]: # (Add milestone from github)
https://github.com/status-im/status-react/milestone/54

- release notes: https://notes.status.im/s/3KPug1hkK
- release branch: https://github.com/status-im/status-react/tree/release/1.15.x

### Testing info 
[comment]: # (TestRail info, added by QA)
Main test suite: https://ethstatus.testrail.net/index.php?/runs/view/7596&group_by=cases:section_id&group_order=asc&group_id=890
Upgrade (e2e): none; upgrade will be tested manually this time, as navigation changed

### Builds in TestFlight and PlayStore to push as a release
[comment]: # (Will be added by QA after testing approving of build)
APK: https://status-im-releases.ams3.digitaloceanspaces.com/StatusIm-Mobile-v1.15.0-81a206-universal.apk
IOS: 1.15.0(20210712120616)

#### 1) Kick-off
- [x] 1. Translation PRs is merged before cutting branch (Jinho)
- [x] 2. Prepare scope of visible changes based on commits history, started from previous release branch cut ([example]( https://notes.status.im/1.14-release-notes?view))
- [x] 3. Update [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) with release notes (make PR based on previous step)
- [x] 4. Create 1.14.0 release branch and get successful builds (doc is [here](https://github.com/status-im/status-react/blob/develop/doc/RELEASE_GUIDE.md) so, testing can be started)
- [x] 5. Based on release scope, ask for comms (Jonny) 
- [x] 6. Make sure that assets (screenshots, video) in stores are up to date. If should be updated, ask @cammellos  for help

#### 2) Testing
[comment]: # (Section will be maintained by QA)
- [x] Dogfooding [(notes)](https://notes.status.im/DoYCPsVbRmurpmznmNVbCQ?edit) 
- [x] Regression testing for release candidate build
- [x] Upgrade tests
- [x] Fix known blocker(s) found during regression testing

##### Blockers
[comment]: # (Section for blocker issues; should be fixed and merged by release-manager. Remove if no blockers found)
- [x] 1 blocker: https://github.com/status-im/status-react/issues/12294
- [x] 2 blocker: https://github.com/status-im/status-react/issues/12297
- [x] 3 blocker: https://github.com/status-im/status-react/issues/12296
- [x] 4 blocker: https://github.com/status-im/status-react/issues/12302

=============================================================================================

- [x] Cherry-pick fix(es) to the release branch
- [x] Verify fix(es) on new release candidate build
- [x] Retest
- [x] Keep release build forever (button in Jenkins)

#### 3) Submission

- [x] 1. Release notes written and added (500 character limit for updates (Android) and PR for [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) is ready to be merged (from 1.3 step)
- [x] 2. Submit beta version for Android (Open Testing in Play Store)
- [x] 3. Submit iOS build to Apple review ([instruction](https://drive.google.com/file/d/10Cl7PBB7TFPkZiVbfzdFGpfMRP9bxXuq/view?usp=sharing), be careful - low quality of audio)
- [x] 4. Play store content reviewed and updated
- [x] 5. Privacy policy reviewed and updated (ask in channel)
- [x] 6. Countries to be excluded (ask in channel) 
- [x] 7. Changes to our FAQ made (should be checked and if any changes needed, ask Jakub to made them)
- [x] 8. Prepare PR for F-droid build ([instruction]( https://github.com/status-im/status-react/blob/develop/doc/FDROID.md))

#### 4) Before publishing
- [x] 1. Translations for comms available (marketing, ask in the channel)
- [x] 2. Promotional content ready (marketing, ask in channel)
- [x] 3. Upload builds for DO store,  https://dev.status.im/ (Jakub)

#### 5) At time of publishing
- [x] 1. Notify marketing to push comms and blog post (Jonny)
- [x] 2. Publish release to app store and playstore
- [x] 3. Final push to update prod site https://status.im/,  [instructions](https://github.com/status-im/infra-docs/blob/master/articles/status_release_upload.md) (Jakub - requires credentials to upload) 
- [x] 4. Add the link to the post about the release and publish the release: https://github.com/status-im/status-react/releases (Jakub)
- [x] 5. Merge PR for updating [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) (from 1.3 step)

**Comment by shivekkhurana** [comment]
## F-Droid Release

Release commit: https://gitlab.com/shivekkhurana/fdroiddata/-/commit/894d168ffa5756d50770f78e46dcf06ee463edc1
(Need to update if new commits are cherry-picked on top of release1.15.x)

### Process
- [x] Test using Docker
- [x] Raise upstream PR

**Comment by jakubgs** [comment]
@shivekkhurana You don't need the `chown -R vagrant /tmp` line, it's already being handled by `make fdroid-build-env`:
https://github.com/status-im/status-react/blob/a19f98e8b3118079122921354a482d4adc45cccc/Makefile#L168-L172

**Comment by licaon-kter** [comment]
Why remove Fastlane?

https://f-droid.org/en/packages/im.status.ethereum/ no more description :(

Ref.  https://github.com/status-im/status-react/commit/3469aca1d873a21491510dc4cd001eaf4910492a#diff-5ae073a3a8e68455a57b03664d4ce77198e9ad62c7fd89a522b7b06c968dca2c

**Comment by jakubgs** [comment]
@licaon-kter hahahaha, yeah, I saw that, pretty darn stupid. I have no idea whatsoever why the fastlane metadata folder was removed. I did point it out when I noticed it, but I thought that maybe F-Droid will just use the old description.

I'll make sure it'll be re-added.

**Comment by jakubgs** [comment]
There you go: https://github.com/status-im/status-react/pull/12428
