### ISSUE TITLE
Pinned messages are sorted by time of initial posting, not by time of pinning

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12290]
# Bug Report

## Problem 
The difference in implementation between Desktop and mobile version - on desktop pinned messages are sorted by time of pinning (newest in the top), on mobile - by the time of posting messages.
Therefore we have different order of pinned messages in the same channel for mobile and for desktop:
![IMAGE 2021-07-08 10:51:52](https://user-images.githubusercontent.com/4557972/124892829-814b6a80-dfda-11eb-9624-d89023b91a33.jpg)
After discussion in #design channel  was decided, that we should implement it the same way as Discord, so **sort messages by time of pinning**
cc @cammellos @errorists 

#### Expected behavior
same sort in mobile and desktop

#### Actual behavior
on desktop pinned messages are sorted by time of pinning (newest in the top), on mobile - by the time of posting messages.

### Reproduction

1) User A: start chat with User B, send 3 messages 
2) User A:  pin messages (3 > 2 > 1)
3) User B (desktop): open pinned messages with User A
4) User A: open pinned messages with User B

### Additional Information

- Status version: nightly 08.07.20201
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by briansztamfater** [comment]
To keep consistency between Desktop & Mobile, should we keep the timeframe header in pinned messages list ("Today", "Yesterday", etc) or we can remove it? cc @churik @errorists @cammellos
