### ISSUE TITLE
Adjust clear history/remove behavior in private group chats and communities

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12323]
As a user
When I leave a private group chat
I want all messages to be deleted

As a user
When I leave a community
I want all messages to be deleted

## Description

Leaving a community or leaving a private group chat should remove all the messages.
In the case of a private group chat, we should warn the users before, as messages will not be recoverable.

Clear history option should be removed from both.

**Comment by errorists** [comment]
[**Figma**](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=21429%3A99840)

<img width="754" alt="Screenshot 2021-07-27 at 11 19 59" src="https://user-images.githubusercontent.com/4932774/127130270-751a5a67-b695-4cb7-ac6a-d08d460479c3.png">
