### ISSUE TITLE
Improve UX to migrate normal account to keycard account

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12336]
**Problem:**
when a normal (his keys are stored on the phone) user wants to migrate his account to a keycard then, he is been taken through this flow
https://www.figma.com/file/Z2T0QW0TgIrJEeTjgBidAG/Untitled?node-id=0%3A1

![image](https://user-images.githubusercontent.com/11461437/126616167-853474d8-6882-4bc4-824c-426454074614.png)

Primarily, this flow has been considered
- hard to locate for users that want to migrate 
- complex (naming and copy are not obvious)
Also
- the choose storage screen is not providing any choice to the user so it could be removed or simplified to an information screen

**How to improve this?**
This flow needs design eyes to simplify the user experience 
An idea would be to add in the '...' screen an entry which would be 'move account to keycard' and which by default would keep the database, it would thus be much simpler for the user to understand and proceed. MOre advanced users could still go through 'manage keys and storage'

cc fyi @bitgamma @churik

**Comment by churik** [comment]
I believe that can be closed after https://github.com/status-im/status-react/pull/12395
 @guylouis please reopne if still relevant

**Comment by bitgamma** [comment]
I think it would be nice to reopen this because this was about simplyfing the flow (both from logged in and logged out state) and making it easier to find

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
