### ISSUE TITLE
No redirect to chat when receive PN with mention from community (Android) and no PN at all on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12332]
# Bug Report

## Problem 
When receive mention in community channel:
- on Android: PN is received, when tapping - redirect to "Browse" popup instead of channel
- on IOS: no PN at all

#### Expected behavior
- on Android: redirect to community channel after tap
- on IOS: PN

#### Actual behavior
![IMAGE 2021-07-21 15:39:42](https://user-images.githubusercontent.com/4557972/126498204-54fe7744-6efa-4e8b-8198-4531d51c2ee9.jpg)

### Reproduction

1) User A: create a community, invite User B, create a channel
2) User B: join community
3) User A: send in channel message with User B mention

### Additional Information

- Status version: nightly 21/07/21
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
It is fixed on Android side, still has to be fixed on iOS.

**Comment by rasom** [comment]
btw, when there is no redirection to chat on iOS atm, so Pls for 1-1 and pub chats just open the app
