### ISSUE TITLE
QR code is not displayed in deep link when opened in an external browser on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12344]
# Bug Report

## Problem 

Broken QR-code is displayed when opening a deep link in an external browser on Android.

<img width="261" alt="Screenshot 2021-07-23 at 10 42 23" src="https://user-images.githubusercontent.com/67952253/126757878-d2886143-f18e-41cd-a5d4-172bf1cf13ae.png">

### Reproduction

- Open a deep link (e.g. https://join.status.im/u/ditest.stateofus.eth) in an external browser (e.g. Chrome)

### Additional Information

- Status version: nightly 23/07
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
@jakubgs do you know in what repo we should file an issue ?

**Comment by jakubgs** [comment]
The repo is [status-im/universal-links-handler](https://github.com/status-im/universal-links-handler), and interestingly enough works fine on Linux, but fails to load in Brave on Android.

**Comment by qoqobolo** [comment]
@flexsurfer @jakubgs okay, thanks! I'll close this one then.

**Comment by jakubgs** [comment]
Haha, looks like this was reported before, but nobody pinged me about it: https://github.com/status-im/universal-links-handler/issues/59

**Comment by jakubgs** [comment]
Fixed in: https://github.com/status-im/universal-links-handler/commit/cadf83ef
