### ISSUE TITLE
In-app sticker pack creation

### ISSUE THREAD

**Issue by hardBSDk** [status-im/status-react#12356]
Implement a way to create sticker packs inside of app.

**Comment by hesterbruikman** [comment]
For future reference: @tbenr worked on a [sticker pack publisher](https://github.com/tbenr/sticker-packs-publisher). This is a dapp that can be used in Status, but is ideally used on Desktop.

Remaining actions are listed in [this comment](https://github.com/status-im/design/issues/44#issuecomment-779307275).

**Comment by hardBSDk** [comment]
> For future reference: @tbenr worked on a [sticker pack publisher](https://github.com/tbenr/sticker-packs-publisher). This is a dapp that can be used in Status, but is ideally used on Desktop.
> 
> Remaining actions are listed in [this comment](https://github.com/status-im/design/issues/44#issuecomment-779307275).

Thanks!

**Comment by churik** [comment]
added to https://github.com/status-im/status-react/discussions/12617
