### ISSUE TITLE
Session breaks, user is logged out

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1235]
*Type*: Bug

*Summary*: User is logged out when leaving Status running at the background and sharing a picture via Gmail at the same time

#### Expected behavior
As a user I want to get back to the Status app running in the background

#### Actual behavior
Session breaks, need to re-login

### Reproduction

*PRECONDITION: open any screenshot in the gallery and leave it running in the background. Then:

- Open Status
- Enter password and login
- Using the device button switch to the screenshot in the gallery
- Click Share icon and select gmail app
- Wait untill the attachment is added
- Using the device button switch to the Status app

https://drive.google.com/open?id=0B7h1U1joPifRc1RwS3RUQ1JySm8

*Summary*: Session should not break when operating with other applications while Status is in the background

### Additional Information

* Status version: 0.9.7+
* Operating System: Android
* Gmail version 7.1.29.147605088
* [2017_05_23_16_30_22 - logcat.txt](https://github.com/status-im/status-react/files/1022339/2017_05_23_16_30_22.-.logcat.txt)

**Comment by annadanchenko** [comment]
@asemiankevich can't reproduce yet. used Samsung Galaxy S6 with Android 6.0.1. What device and OS version do you have?

**Comment by asemiankevich** [comment]
Its Samsung Galaxy A7, android 6.0.1

**Comment by asemiankevich** [comment]
I can reproduce the issue again

https://app.testfairy.com/projects/4803622-status/builds/6456500/sessions/4/?accessToken=1EHJv-tgqxS6XAYjU3A5SoBGl6I (from 2.20 )
