### ISSUE TITLE
Spin of death on adding custom NFT token contract

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#12365]
# Bug Report

## Problem 

The app seems to be loading forever when trying to add a custom NFT token.

Go to Wallet > 

### Reproduction

1) Open Status
2) Open wallet
3) Manage tokens
4) Add custom token
5) Enter NFT contract address is Contract address field such as `0x31385d3520bCED94f77AaE104b406994D8F2168C`
6)  Spin wheel "just a moment" spins forever

### Additional Information

- Status version: 1.15.0
- Operating System: Android

**Comment by flexsurfer** [comment]
we don't support custom nft tokens atm, probably we should detect if it's an nft token and show the alert ?

**Comment by flexsurfer** [comment]
cc @carlfairclough
