### ISSUE TITLE
Android App Crashing with java.lang.nullpointerexception

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#12367]
# Bug Report

## Problem 
On fresh install (or after clearing data), there are two ways to proceed either generate keys or access existing keys. If the option is chosen to access existing keys and then without accessing existing keys, the user decides to generate new keys, App Crashes on account creation as shown in Video.

### Reproduction

https://user-images.githubusercontent.com/17097240/126963531-a072bb01-e96b-4bbe-b0cd-c62df145b058.mp4

### Additional Information

- Status version: 1.14.0 (Downloaded From Play Store) 
- Operating System: Android

**Comment by flexsurfer** [comment]
thanks @Parveshdhull , @churik i believe this should be fixed in 15 ?

**Comment by churik** [comment]
@Parveshdhull 
thank you for reporting!

@flexsurfer 
Android 10 (Xiaomi Mi Note 9)
1) I was able to reproduce it only once (from 4 attempts) on 1.14, and if you restart app one more time, you can finish flow, so it is not a dead-end
2) couldn't reproduce it on 1.15 (tried ~5 times)

@Parveshdhull would you mind recheck it one more time after upgrading? 1.15 will be available soon in stores (matter of hours /day)

**Comment by Parveshdhull** [comment]
@churik Sure, I will recheck once the update will be available on the play store

**Comment by Parveshdhull** [comment]
The problem is fixed in the latest available version on Play Store(1.15)
