### ISSUE TITLE
Let me only share my profile picture with my contacts

### ISSUE THREAD

**Issue by trosel** [status-im/status-react#12386]
# Feature Issue

### User Story

As a user, I want to share my profile picture only with my contacts **so that** I can maintain my privacy and choose to selectively reveal myself to others over time. 

### Description

Currently, the only setting around profile pictures is deciding which pictures you want to *see*. I think this is backwards. The user should determine who to *share* their picture with, not which pictures they want to *see*.

**Comment by churik** [comment]
part of https://github.com/status-im/status-react/pull/11768
