### ISSUE TITLE
Importing my account via private key

### ISSUE THREAD

**Issue by mehdiag** [status-im/status-react#12404]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

I have been trying to import my account and use my ENS but there is a problem, i have not generated new wallet and imported my wallet by using my seed phrase, but under my account there are two accounts which have two different path and one of them have the ENS domain, unfortunelty when use my seed phrase it uses my other account and when i import my Private key it keep saying its the second account. so can we have a feature to import directly with private key at the start of the app ? 

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)

Add feature to import wallets through private key also.

[comment]: # (Rules for the future PR to be accepted.)

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by vitorgomesgomes** [comment]
nice

**Comment by vitorgomesgomes** [comment]
nice

**Comment by vitorgomesgomes** [comment]
nice
