### ISSUE TITLE
Categories and channels, added after resolving community link are not shown when tapping View on invite

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12419]
# Bug Report

## Problem 
There are couple of issues with displaying categories on community invite (view when  user requesting access):
- categories are not shown at all (so all chats are uncatogorized) 
- channels, which were added to community after resolving invite, will not be shown in the invite at all

#### Expected behavior
can see categorized chats which are added in community (category A + chat A, uncatogorized B)

#### Actual behavior

User B: https://user-images.githubusercontent.com/4557972/128171213-7d473957-1a31-4c61-827b-edc50bde9316.mp4

### Reproduction

1) User A: open community, post link in public chat
2) User B: wait until invite to community will be resolved
3) User A: create category A + add public channel A to that category
4) User A: add channel B to community 

### Additional Information

- Status version: nightly 04/08/21
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@churik 

> channels, which were added to community after resolving invite, will not be shown in the invite at all
I think this is kind of expected, to some extent. 


Basically we don't want a user to "subscribe" to updates of a community automatically, otherwise it can be spammed.
What we could do though is to refresh the community info if the user lands on the preview page.

> categories are not shown at all (so all chats are uncatogorized)

This should not be the case, I would think it's a UI issue, but I can take a look

**Comment by churik** [comment]
> Basically we don't want a user to "subscribe" to updates of a community automatically, otherwise it can be spammed.
What we could do though is to refresh the community info if the user lands on the preview page.

That's sound reasonable, actually IMO it is just nice to see relevant info on preview page (where user can request access) - all categories and channels

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
