### ISSUE TITLE
ERC20 txns are pending in tx history and balance is updated only after re-login 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12436]
# Bug Report

## Problem 
After EIP-1559 fork ERC20 token transactions can be sent from 1.15, but they are stuck in "Pending" in transaction history and balance is updated only after re-login.
Incoming token txs are not shown in tx history

#### Expected behavior
txs are up-to-date

#### Actual behavior

https://user-images.githubusercontent.com/4557972/128692483-58701d9f-0389-4775-886a-22f9e0de6302.mp4

### Reproduction

1) Open Status
2) Restore multiaccount with assets
3) Send some ERC20 to another account

### Additional Information

- Status version: 1.15 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
[Status-debug-logs.zip](https://github.com/status-im/status-react/files/6953152/Status-debug-logs.zip)

**Comment by rasom** [comment]
Interesting that it happens with legacy txs, it is not clear how exactly eip1559 is related to this issue

**Comment by churik** [comment]
yes, that happens to all multiaccounts for now regardless of presence of EIP1559 txs on them

**Comment by rasom** [comment]
I can't reproduce it in `develop`, so probably it is already fixed

**Comment by churik** [comment]
You are right, this is release issue only.
On nightly can't reproduce.

**Comment by churik** [comment]
will be fixed in 1.16, will recheck during release testing
