### ISSUE TITLE
When using a BT keyboard enter should send, not add new line

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12441]
# Bug Report

## Problem 
When I connect a Bluetooth keyboard to an Android phone and try to type in chat pressing `Enter` does not send a message, but instead creates a new line. This isn't what you would expect compared to any other chat application.

#### Expected behavior
* `Enter` sends the messages
* `Shift+Enter` adds new line

#### Actual behavior
* `Enter` adds new line
* `Shift+Enter` adds new line

### Additional Information

- Status version: Release `1.15.0` 
- Operating System: Android

**Comment by rasom** [comment]
I tried to introduce some quick fix for this issue, but no luck.

We can detect that virtual keyboard is not used by subscribing to `keyboardWillShow`/`keyboardWillHide` and then change input's `blurOnSubmit=true` and set handler for `onSubmitEditing`. 
It would even look like a fix until you will actually try to add a newline by pressing something like shift+enter. There is no way to say that shift was pressed using RN's api, so it would just submit the input. Also input will be blurred.

To fix it we would need to use some lib for `shift` pressing detection and also find a workaround to focus input after submitting it.

**Comment by jakubgs** [comment]
Damn, that sounds like much more of a pain in the ass than I thought. Considering it's an edge case I don't know if it makes sense to add new libraries just to fix this. Thanks for looking into it @rasom.

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration

**Comment by cammellos** [comment]
Closing, as this is not something we will be looking into anytime soon, we will reopen when we will have time to look into it
