### ISSUE TITLE
Sometimes first tap on buttons (e.g. send button or < button) has no effect [iOS only]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1244]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sometimes, app does nothing if tap on a button (e.g. send button in chat or < back button). Only second tap on the same button results in expected action. It's not clear yet how to reproduce this

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App responds to the first tap on the button
#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing happens, only second tap on the same button leads to expected action
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Not clear what are the steps to get such issue, but as soon as it's there:
- open 1-1 chat
- type "text" and tap on send button. Expected that text will be sent, however nothing happens
- Tap second time on the send button -> text is sent

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: iOS only. 10.3.2 and 10.2.1

**Comment by asemiankevich** [comment]
I can reproduce it in Wallet (app verison 0.9.9d89): 

1. Go to Wallet -> Open
2. Enter any sum in SEND field and click Send

The same for REQUEST

**Comment by annadanchenko** [comment]
Session with video and log (see from 08:02), user types /16 tries to send - onlt second tap on the send button sends the message, first one has no effect.
https://app.testfairy.com/projects/4803590-status/builds/7178534/sessions/2/?accessToken=xJejZdXk5Iy-Y0exoTu-n/Jqm0M

**Comment by chadyj** [comment]
This happened to me with version 0.911d446 build 2002.1.
It could be fixed by restarting the app. However, I couldn't reproduce it again, and tried the above steps.

**Comment by annadanchenko** [comment]
haven't seen it for last couple of months, so closing
