### ISSUE TITLE
Screens with overlapping long usernames

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12446]
# Bug Report

## Problem 
There are several screens found where long 3 random names overlap with other elements on the screen.

- [x] **1. Membership request in community (Android, iOS)**

_Steps_:
- UserA: create a community, post invite in some chat
- UserB: send a request
- UserA: open membership requests screen
<img width="263" alt="Screenshot 2021-08-13 at 14 03 23" src="https://user-images.githubusercontent.com/67952253/129340858-afbf4bf6-f56e-4bdb-8f79-3c0ef00fdf79.png">

- [x] **2. List of Keycard multiaccounts (Android, iOS)** 

_Steps_:
- Create a Keycard multiaccount
- Log out
- Open list of your keys
<img width="263" alt="Screenshot 2021-08-13 at 14 03 42" src="https://user-images.githubusercontent.com/67952253/129340977-0abd4db1-a74d-4845-b918-0fb6d2168e23.png">

- [x] **3. List of group members (Android, iOS)**

_Steps_:
- Create a group chat
- Open Group info

<img width="264" alt="Screenshot 2021-08-13 at 14 04 36" src="https://user-images.githubusercontent.com/67952253/129341151-b0de7b0d-2847-4cdd-b0bc-f5443fc0a84d.png">

- [x] **4. List of community members (Android, iOS)**

_Steps_:
- Create a community
- Open Community info
- Open Members

<img width="264" alt="Screenshot 2021-08-13 at 14 06 07" src="https://user-images.githubusercontent.com/67952253/129341244-8028b22f-c13e-4c37-94d1-f436b8af3357.png">

- [x] **5. Header of 1-1 chat (iOS only)**

<img width="269" alt="Screenshot 2021-08-13 at 14 06 29" src="https://user-images.githubusercontent.com/67952253/129341280-b3b1ea4d-386f-49bd-8dff-31745d4d42cd.png">

- [ ] **6. Timestamp is shifted in Timeline (could reproduce on Android only)**

<img width="270" alt="Screenshot 2021-08-16 at 13 45 39" src="https://user-images.githubusercontent.com/67952253/129544837-53f03ed9-446b-4370-aeb0-c1d74ac20d2a.png">

### Additional Information

- Status version: nightly 13/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
сс @briansztamfater @flexsurfer
