### ISSUE TITLE
App crashes if save status with hashtag (#) and backslash (\)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1245]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Save status `#\` -> app crashes

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Status is saved
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashes
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open profile
- Edit profile
- in Status type #\ and tap Save -> crash

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
[StatusIm-2017-05-26-110446.crash.txt](https://github.com/status-im/status-react/files/1031262/StatusIm-2017-05-26-110446.crash.txt)

**Comment by occamin** [comment]
Hi guys, I'll pick this one up. Could someone assign it to me?

**Comment by flexsurfer** [comment]
hi @occamin, issues can be assigned only to team members. I've added 'in progress' label, so you can work on it, thanks

**Comment by occamin** [comment]
Cool, thanks @flexsurfer
