### ISSUE TITLE
Redundant "!" button in the "Message actions" context menu in Timeline

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12451]
# Bug Report

## Problem 

<img width="271" alt="128864340-ef845617-18be-4dad-ab29-563ff5b10f80" src="https://user-images.githubusercontent.com/67952253/129563324-67b47728-2b6e-4063-bb1b-27f5c05be679.png">

### Reproduction

1. Post something in Timeline
2. Long tap on the message

### Additional Information

- Status version: nightly 16/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
@qoqobolo should it have copy icon instead? Like here:
<img width="325" alt="Screenshot 2021-08-17 at 16 06 57" src="https://user-images.githubusercontent.com/2364994/129731022-06c90f01-5ecd-48d7-ac9a-eaeced25d94e.png">

**Comment by qoqobolo** [comment]
@rasom yeah, it would be okay.
Or like in the previous develop without any icons, just `Copy` in the middle. 
But with the new design, your option is better. 
Thanks.

<img width="265" alt="Screenshot 2021-08-17 at 17 12 03" src="https://user-images.githubusercontent.com/67952253/129731724-c6a46843-e104-4225-91ba-b70be8aae0f7.png">
