### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by mfekadu** [status-im/status-react#1246]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a student developer, I want to simply build & run #StatusIM for ios so that I can understand how it works.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Bug*: 'RCTBridgeModule.h' file not found

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I tried replacing `#import "RCTBridgeModule.h" `with `#import <React/RCTBridgeModule.h>` after reading here: https://github.com/weflex/react-native-wechat/issues/33 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
StatusIM should run on the ios simulator.

#### Actual behavior
[comment]: # (Describe what actually happened.)
It did not :(

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status via Xcode
- Click the play button
- Notice error ::: `'RCTBridgeModule.h' file not found`

### Solution
[comment]: # (Please summarize the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ... not yet, will update when found

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 1.0? cloned repository today (5/26/17)
* Operating System: iOS
* Xcode Version 8.3.2 (8E2002)
* I'm possibly missing files because I've never done anything with React before? :\

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
RCTStatus Group
Lexical or Preprocessor Issue Group
(~my-status-react-directory~)/modules/react-native-status/ios/RCTStatus/RCTStatus.h:2:9: 'React/RCTBridgeModule.h' file not found
(~my-status-react-directory~)/modules/react-native-status/ios/RCTStatus/RCTStatus.m:1:9: In file included from (~my-status-react-directory~)/modules/react-native-status/ios/RCTStatus/RCTStatus.m:1:
```

#### Various Warnings... possibly related?

```
StatusImTests Group
Target Integrity Group
(~my-status-react-directory~)/ios/StatusIm.xcodeproj The file “Pods-StatusImTests.debug.xcconfig” couldn’t be opened because there is no such file. ((~my-status-react-directory~)/ios/Pods/Target Support Files/Pods-StatusImTests/Pods-StatusImTests.debug.xcconfig)
(~my-status-react-directory~)/ios/StatusIm.xcodeproj The file “Pods-StatusImTests.release.xcconfig” couldn’t be opened because there is no such file. ((~my-status-react-directory~)/ios/Pods/Target Support Files/Pods-StatusImTests/Pods-StatusImTests.release.xcconfig)
Dependency Analysis Warning Group
The file “Pods-StatusImTests.debug.xcconfig” couldn’t be opened because there is no such file. ((~my-status-react-directory~)/ios/Pods/Target Support Files/Pods-StatusImTests/Pods-StatusImTests.debug.xcconfig)
StatusIm Group
Target Integrity Group
(~my-status-react-directory~)/ios/StatusIm.xcodeproj The file “Pods-StatusIm.debug.xcconfig” couldn’t be opened because there is no such file. ((~my-status-react-directory~)/ios/Pods/Target Support Files/Pods-StatusIm/Pods-StatusIm.debug.xcconfig)
(~my-status-react-directory~)/ios/StatusIm.xcodeproj The file “Pods-StatusIm.release.xcconfig” couldn’t be opened because there is no such file. ((~my-status-react-directory~)/ios/Pods/Target Support Files/Pods-StatusIm/Pods-StatusIm.release.xcconfig)
Dependency Analysis Warning Group
The file “Pods-StatusIm.release.xcconfig” couldn’t be opened because there is no such file. ((~my-status-react-directory~)/ios/Pods/Target Support Files/Pods-StatusIm/Pods-StatusIm.release.xcconfig)
StatusIm project Group
Validate Project Settings Group
(~my-status-react-directory~)/ios/StatusIm.xcodeproj Update to recommended settings
```

I hope that was nice and detailed :)
Thanks in advance for your help!
-michael

**Comment by morelazers** [comment]
I had this issue and solved it by doing:
`rm -r node_modules/`
`rm -r ios/Pods`
`npm install`
`cd ios && pod install`
Open XCode, hit `CMD + Shift + K` to clean and build`

Basically just clean the whole thing and go again from 0, also worth noting that this worked for me on XCode 8.2.1 but I don't think the version is necessarily the problem.

**Comment by rasom** [comment]
Thanks for help @morelazers

**Comment by mfekadu** [comment]
Thanks @morelazers! Worked perfectly!
