### ISSUE TITLE
Redundant "!" button in the "Message actions" in context menu for images

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12467]
# Bug Report

## Problem 
![IMAGE 2021-08-20 15:15:38](https://user-images.githubusercontent.com/4557972/130238859-1bb78245-5ae9-47f1-8963-bd5ec4d9f427.jpg)

### Reproduction

1) Open Status
2) Start 1-1 chat
3) send image
4) Long tap on image message

### Additional Information

- Status version: nightly 20/08/21
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
@churik which icons should be shown there? none?

**Comment by churik** [comment]
@rasom 
didn't have any
![IMAGE 2021-08-23 10:11:41](https://user-images.githubusercontent.com/4557972/130413385-84335d02-eba0-4ef8-b016-255f8bdf1fcd.jpg)

**Comment by rasom** [comment]
@churik so I checked and the layout of this component was changed in delete message pr ([here](https://github.com/status-im/status-react/commit/8ec46a0d78b7a6e28286e42ff9af60799162b3c0)).

As far as I see, we have it used for next types of messages:
1. regular text message 1-1 chat/private group: edit/reply/copy/pin/delete for incoming, reply/copy/pin for outgoing
2. regular text message in pub chat/communities: edit/reply/copy/delete fro incoming, reply/copy for outgoing
3. image in 1-1 chat/private group/communities: reply/save for both cases
4. sticker 1-1 chat: View Details for incoming (currently also has that `!` mark)
5. status text message: copy for both

So the question is: in which cases we want to align them vertically and have an icon, in which cases we want to align them horizontally. Just to fix it for all cases.

**Comment by churik** [comment]
@rasom 
I believe for all cases they are aligned OK, just replace for places where "!" is shown to empty place
1) regular text message 1-1 chat/private group: edit/reply/copy/pin/delete for incoming, reply/copy/pin for outgoing
2) regular text message in pub chat/communities: edit/reply/copy/delete fro incoming, reply/copy for outgoing
3) image in 1-1 chat/private group/communities: reply/save for both cases 

- [ ]  Reply -with icon 
- [ ]  Save - if no icon, no "!"
4) sticker 1-1 chat: View Details for incoming (currently also has that ! mark)
- [ ]   Remove  "!" if no icon
5) status text message: copy for both
