### ISSUE TITLE
Sometimes token txs are stuck in "Pending" state in tx history

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12477]
# Bug Report

## Problem 
Leftover from https://github.com/status-im/status-react/pull/12369
Tx confirmed by network, but will stay in our tx history with "Pending" state forever (relogin doesn't help)
Can't reproduce consistently when trying with the same prerequisites

#### Expected behavior
tx will be confirmed in history

#### Actual behavior
![IMAGE 2021-08-17 12:45:02](https://user-images.githubusercontent.com/4557972/129712631-51feebc9-23d7-40bf-bd7e-a6087a4c210c.jpg)
TX 0.01 SALT is stuck in history in "Pending", relogin doesn't help.

Balance was refreshed only after relogin

### Reproduction

1) Open Status, restore some multiaccount with assets
2) Send tokens to some valid address

### Additional Information

- Status version: nightly 23/08/21
- Operating System: Android, iOS

Logs: 
[Status-debug-logs.zip](https://github.com/status-im/status-react/files/6999274/Status-debug-logs.zip)

**Comment by rasom** [comment]
@flexsurfer noticed
> WARN [status-im.ethereum.json-rpc:251] - :json-rpc/error wallet_getPendingTransactions :error {:code -32000, :message "no such column: hash"} :params []
