### ISSUE TITLE
Add ability to Share image from Status

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#12472]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to Share an image **so that** I can send images to apps and contacts outside of Status. 
As a user I want to Save an image **so that** I can keep it for later use.

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: As per feature request #11912 

Share image comes with a [design update](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4190%3A24449) that should apply to Android and iOS. Currently the implementation differs between Android and iOS (see #12474) 

### Acceptance Criteria

- Share option is available when viewing image in full screen
- UI is update to reflect design update

[comment]: # (Rules for the future PR to be accepted.)

### Notes

- Note that this request is somewhat orthogonal to e.g. blocking screenshots and might need community debate to understand if easily sharing images outside of Status is desirable from a privacy point of view. That said, the ability to share is already available albeit with a workaround by either saving and sharing the image or enabling screenshots and sharing an image 
- Note that this issue is distinct from #12148, which describes ability to Share an image to Status

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by churik** [comment]
is it not the same https://github.com/status-im/status-react/issues/11912 @hesterbruikman ?

**Comment by nahuhh** [comment]
> - Note that this issue is distinct from #12148, which describes ability to Share an image to Status
> 

Is there any work being done in regards to #12148?

**Comment by churik** [comment]
@nahuhh 
no, the issue is still open.

**Comment by nahuhh** [comment]
> @nahuhh 
> no, the issue is still open.

Thank you for the response. (I originally opened the issue some time ago).

I'm not sure how much work it is to implement, but that (to me) is the #1 thing that makes status  hard to use.

More often then not, I send links, screenshots etc through the share menu. Navigation through status, or copy and paste, while it works, is more trouble than it's worth and usually leads me to just use other messengers. Those that I recommend status to, thats usually their biggest pain as well.

Otherwise, this is one of the best there is.
