### ISSUE TITLE
Initial syncing of messages takes > 5 mins  when switching to eth.test from IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12487]
# Bug Report

## Problem 
Found during testing go-version update on `eth.test` fleet. 
Initial syncing of messages in `#status` channel took > 5mins (IOS only)
During this time at attempt to send a message they are not confirmed, so from user's perspective looks like messaging is not working.
After initial syncing app is working normally.

#### Expected behavior
can see messages in seconds (like on Android)

#### Actual behavior
spinner for > 5 mins

### Reproduction

1) Open Status
2) Switch to `eth.test`
3) Join #status 

### Additional Information

- Status version: nightly 24/08/2021
- Operating System:  iOS

Logs: [status_logs.zip](https://github.com/status-im/status-react/files/7040357/status_logs.zip)

**Comment by churik** [comment]
cc @jakubgs

**Comment by jakubgs** [comment]
@cammellos suggested that this issue might be account-specific. Not sure how that could be possible, but have you tested this with more than just one account on iOS?

**Comment by churik** [comment]
no, it is reproducible with fresh accounts

**Comment by churik** [comment]
but I'll ask to reproduce it other QA, just in case

**Comment by churik** [comment]
Well, it is reproducible:
1) from my device (IOS) - Spain
2) from Sergey device (IOS) - Ukraine
And not reproducible from Diana's device (IOS) - Russia

It becomes more and more weird

**Comment by jakubgs** [comment]
I think we'll need some help from people more well versed in the protocol to debug this.

@Samyoul do you have any ideas what this might be? Android E2E tests pass with 100% but iOS has major issues.

**Comment by jakubgs** [comment]
All `eth.test` nodes are running `v0.84.0`:
```
 > a mail,whisper -o -a '/docker/statusd-*/rpc.sh admin_nodeInfo | jq .result.name' 
node-01.do-ams3.eth.test | CHANGED | rc=0 | (stdout) "Statusd/v0.84.0/linux-amd64/go1.13.15"
mail-01.do-ams3.eth.test | CHANGED | rc=0 | (stdout) "Statusd/v0.84.0/linux-amd64/go1.13.15"
node-01.gc-us-central1-a.eth.test | CHANGED | rc=0 | (stdout) "Statusd/v0.84.0/linux-amd64/go1.13.15"
node-01.ac-cn-hongkong-c.eth.test | CHANGED | rc=0 | (stdout) "Statusd/v0.84.0/linux-amd64/go1.13.15"
mail-01.ac-cn-hongkong-c.eth.test | CHANGED | rc=0 | (stdout) "Statusd/v0.84.0/linux-amd64/go1.13.15"
mail-01.gc-us-central1-a.eth.test | CHANGED | rc=0 | (stdout) "Statusd/v0.84.0/linux-amd64/go1.13.15"
```
While both `eth.staging` and `eth.prod` are still on `v0.79.0`.

**Comment by jakubgs** [comment]
@churik have you tested only mobile or also desktop?

**Comment by churik** [comment]
mobile only.

**Comment by jakubgs** [comment]
Thanks to debugging by @cammellos I identified that this issue is caused by `go-ethereum` upgrade in `status-go` that resulted in my fix for rate limiting connections being removed:

* https://github.com/status-im/status-go/pull/2146
* https://github.com/status-im/go-ethereum/pull/91

**Comment by cammellos** [comment]
@churik could you please test again? we put a fix on test and might help with this.
Thanks

**Comment by churik** [comment]
sure, on it

**Comment by churik** [comment]
It is fixed, let me know if I should retest smth on `eth.test` fleet, thank you!

**Comment by cammellos** [comment]
Thanks @churik !
@jakubgs did you hear that? Time to pop the champagne!
