### ISSUE TITLE
Amount field formatting error during wallet->send

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12483]
# Bug Report

https://user-images.githubusercontent.com/41779817/130598141-123e95b5-ed38-4040-9a54-728c01714f9b.MP4

#### Expected behavior

Small values are fully visible on the screen

### Additional Information

- Status version: 1.15
- Operating System: iOS

**Comment by flexsurfer** [comment]
cc @carlfairclough

**Comment by rasom** [comment]
@hesterbruikman @carlfairclough would something like work?


https://user-images.githubusercontent.com/2364994/150351940-8c8a9919-e10a-4110-a1d8-ff7470a79503.mov

**Comment by flexsurfer** [comment]
@rasom  that's nice, that is actually what design team suggested in the past

**Comment by carlfairclough** [comment]
@rasom that's great. My only concern is that token picker feels like it's jumping around even more than it did already. Would it be possible to pin that to the right hand side? That is how it is in proposed updates.

**Comment by rasom** [comment]
@carlfairclough, like this?

https://user-images.githubusercontent.com/2364994/150509377-653ed296-62f5-4d73-814a-a34a085ce157.mov

Another option would be to put it before amount

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
