### ISSUE TITLE
Unread indicator is not cleared for community mentions when message is deleted

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12494]
# Bug Report

## Problem 
If UserA mentions UserB and deletes the message, UserB still sees an unread indicator on the community.

#### Expected behavior

Unread counter `1` is not shown on the community

#### Actual behavior

<img width="386" alt="Screenshot 2021-08-25 at 15 23 10" src="https://user-images.githubusercontent.com/67952253/130782103-79a95247-a60e-4a76-b2e1-dd6f2511da26.png">

### Reproduction

1. User A, B: join a community
2. User B: navigate to the home screen
3. User A: mention User B in the community 
4. User A: delete the message
5. User B: check the home screen

### Additional Information

- Status version: nightly 25/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
@qoqobolo as far as I can say it was also reproducible in public chats, so it is not specific to community chats.

**Comment by qoqobolo** [comment]
@rasom this is one of the leftovers of #12475. Unread indicator for mentions in public chats was fixed there, but for communities the issue is still reproducible

**Comment by rasom** [comment]
@qoqobolo I doubt it was fixed for pub chats, but well it doesn't matter :)

**Comment by qoqobolo** [comment]
@rasom hmm okay. I was just asked to log leftovers without retesting. Anyway, sorry for the confusing information. Will double-check next time :)
