### ISSUE TITLE
Unable to edit existing channels in Android

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-react#12509]
# Bug Report

issue reported by a user originally [here](https://github.com/status-im/status-desktop/issues/3275)

## Problem 

"4. Unable to edit existing channels at all in Android - can only create new channel."

### Additional Information
- Operating System: Android

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-desktop/issues/3275#issuecomment-907572229
