### ISSUE TITLE
New member of group chat does not see new chat and does not get messages from the chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1250]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Admin creates new group chat with 1 member "B". Each of them send 1 message in the group chat. Admin adds another member "C" to the members of the group chat. "C" does not see new group chat in Chats. If Admin or "B" send message to the group chat then "C" gets nothing

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When new member is added to existing group chat then for this user
- new group chat is visible in Chats 
- if new messages are sent to the chat by other "old" members then they are received by new member 
#### Actual behavior
[comment]: # (Describe what actually happened.)
When new member is added to existing group chat then for this user
- There is no new group chat in Chats 
- if new messages are sent to the chat by other "old" members then they are not received by new member 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
As Admin:
- Open Status
- Create new group chat with member "B"
- send a message as Admin and as "B". Make sure, that both users see these messages
- add another member "C" to the group chat. Send new message
- As "C" member: check that new group chat is visible in Chats and new message is received

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7
* Operating System: Android and iOS (iPhone 7 plus,  iOS 10.3.2; iPhone 6s, iOS 10.2.1, Samsung Galaxy S7, Android 7.0)

**Comment by rasom** [comment]
In progress

**Comment by rasom** [comment]
fixed in https://github.com/rasom/status-react/tree/bug/%231250

**Comment by annadanchenko** [comment]
Works fine on 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3
develop build 0.9.8-130-g6a56b600 | 0.9.9d130
