### ISSUE TITLE
Backup of contacts

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12518]
As a user
I want to backup my contacts
So that I can retrieve my contacts on a new device

### Description

We should give the user an option to backup and restore their contacts, so that in the case they lose access to their device, they can restore them on a different one.
A file should be generated and should be password protected, an option to download should be available.
A similar option should be given to restore from a backup file your contacts.

The format should accommodate for other types of data to be backed up in the feature (chats/messages/etc)

**Comment by errorists** [comment]
Designs

- [Entry point, no contacts](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A4233)
- [Entry point, some contacts](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4066%3A8731)
- [Backup UI and dialogues](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=7240%3A26099)

**Comment by cammellos** [comment]
Closing for now in favor of https://github.com/status-im/status-react/issues/12550
