### ISSUE TITLE
Unread indicator state on home tab is reset when open user profile from chat view

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12511]
# Bug Report

## Problem 
Currently the amount of unread messages on home tab is reset if open profile from chat view.
Reproducible with mentions in public chats.

#### Expected behavior
no unread indicator

#### Actual behavior
unread messages on tab = 1

https://user-images.githubusercontent.com/4557972/131094716-1e197b12-1dc4-4006-8862-c1a2ec69c998.mp4

### Reproduction

1) UserA: add user B to contacts 
2) UserB: send a message to userA
3) UserA: open 1-1 chat with userB
4) UserA: open user Profile via options > view User Profile
5) UserA: go back to home view

### Additional Information

- Status version: release 1.16 RC1 
- Operating System: Android

**Comment by rasom** [comment]
Apparently it is related to some bug in `react-native-navigation` lib. When a modal is opened, bottomTab's state is reset to the state before `{:dotIndicator {:visible false}}` was set. If I dispatch `:change-tab-count` from that modal screen, for instance:
```clojure
(re-frame/dispatch [:change-tab-count :chat {:public 15 :other 20}])
```
The state is successfully updated, but if I dispatch `{:public 15 :other 20}` it states with previous value. So it seems that `{:visible false}` is ignored in some cases.
