### ISSUE TITLE
personal_sign

### ISSUE THREAD

**Issue by wighawag** [status-im/status-react#1251]
### User Story

As a developer I want to be able to request the user to sign a piece of information without hitting the blockchain. This can be used for various purpose such as login the user in

### Description

*Type*: Feature

*Summary*: 
Metamask implements it and here is a blog post describing its utility : https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527

**Comment by flexsurfer** [comment]
related issue https://github.com/status-im/status-react/issues/2704
