### ISSUE TITLE
Endless 'Loading...' in the newly created community channel under Mobile network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#12527]
# Bug Report

## Problem 
When creating community and joining to a new channel while device under Mobile network (LTE) then there is in an endless spinner with 'Loading...' displayed. No issues with WiFi.

#### Expected behavior
Can send message right after joined to newly created community channel under Mobile network

#### Actual behavior
Endless 'Loading...' in the newly created community channel under Mobile network

https://user-images.githubusercontent.com/8749671/131534033-fb656638-475f-46b6-905e-944e1b95953c.mov

### Reproduction
0) Switch to Mobile network
1) Open Status and create new account
2) Create new community 
3) Create new channel and open it's view
 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
Not relevant anymore
