### ISSUE TITLE
Connecting autofarm.network dapps with status wallet freezes browser

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12526]
## Context
On ethereum mainnet, autofarm.network dApps works well with meta mask. 

## Issue
On ethereum mainnet, a user can't properly connect his wallet to autofarm.network dapps.

## Reproduction
- Status on mainnet 
- with browser go to https://autofarm.network 
- the user gets the bottom pop-up telling him autofarm wants to connect to his wallet 
- if user approves the connection, then status browser gets freezed

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/131640977-bfd607ff-6935-459a-ab5f-78295004a35a.png)
