### ISSUE TITLE
Human Readable data display when signing using `eth_signTypedData_v3`

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#12535]
For the Status Community Curation dApp, poll responses and votes are signed using [EIP-712](https://eips.ethereum.org/EIPS/eip-712): Ethereum typed structured data hashing and signing.

Currently, the data is displayed in one line JSON format.

Instead, we should display the data in a more human readable format.

The [EIP-712](https://eips.ethereum.org/EIPS/eip-712) provides examples such as:

![image](https://user-images.githubusercontent.com/300805/131761569-345fb1ae-7e49-4bf2-bfe9-11d3820f2f86.png)

https://status-im.github.io/js-waku/eth-pm/ can be used to play around (broadcast encryption public key step).

**Comment by D4nte** [comment]
In which version is this released? I tried 1.18.2 and it's still a one liner.

**Comment by D4nte** [comment]
![Screenshot_20220221-163755.jpg](https://user-images.githubusercontent.com/300805/154895713-d0069be0-a52c-4f5b-b076-0f86815ad93b.jpg)

Cc @qfrank @flexsurfer

**Comment by flexsurfer** [comment]
@D4nte is this keycard ?

**Comment by D4nte** [comment]
> @D4nte is this keycard ?

Yes

**Comment by churik** [comment]
@D4nte 
still not into release, should be in 1.19
