### ISSUE TITLE
Allow users to be banned in a community

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12549]
As an admin
I want to be able to ban users from a community
So that they won't be able to access it ever again

### Description

Currently we only allow kicking members of a community. 
We should allow banning as well, in open-membership communities, so that they won't be able to access it again.

**Comment by ducheng0** [comment]
Muting users would also be nice, so they can still read the conversation, but cannot send new messages. Read-only chats for things like announcements, rules, etc.. would also be nice.

**Comment by du82** [comment]
You can ban members as of the 1.16 update I believe... The option is there for me and I'm running the latest version from Google Play.

![Screenshot_20210908-070647_Status](https://user-images.githubusercontent.com/65834069/132506443-1f21eb0f-bf74-476f-a96b-b3353eb53796.png)

**Comment by cammellos** [comment]
Thanks @ducheng0 I'll check if that's working as expected and close this issue if so.

**Comment by shivekkhurana** [comment]
@cammellos Is this relevant ?

**Comment by cammellos** [comment]
@shivekkhurana let me check

**Comment by cammellos** [comment]
Already implemented, yes
