### ISSUE TITLE
Wallet connect 2.0 integration

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12546]
As a user
I want to be able to use wallet connect 2.0
So I can use dapps on desktop etc

### Description

We should support the wallet connect 2.0 protocol.
The protocol uses waku 2.0, so a connection needs to be made, likely in parallel to a waku v1 connection (currently not supported). 

### Designs

https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=6030%3A15485

**Comment by flexsurfer** [comment]
figma design looks strange because wallet connect is needed to connect status app with dapps outside status, so there should be a possibility to scan qr and connect dapp, and then sign transactions , and we need a convenient UI for that
