### ISSUE TITLE
Transaction screen is not shown and app freezes if send sum "X,Y" where X>0 (1,1 or 2,123 etc) [iPhone 7 plus only?]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1255]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Can reproduce only on iPhone 7 plus: send any sum greater than 1 with some decimal point in it: 1,1 ETH or 2,123 ETH -> no Confirm Transaction screen is shown and app does not respond to any tap. Note: on same device it's fine sending sums "0,1", "0,12345" and "1" 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Confirm Transaction screen is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
1-1 chat is shown, no Confirm Transaction screen is shown and app does not respond to any tap.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7REh1NDRjZTU2b3c
you need to have more than 1,2 ETH.
- Open Status
- Open 1-1 chat
- send 1,1 ETH

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7 and dev build 0.9.8d28
* Operating System: iOS 10.3.2, iPhone 7 plus

### Logs
[consolelog.txt](https://github.com/status-im/status-react/files/1039422/consolelog.txt)

**Comment by rasom** [comment]
@annadanchenko can this bug be reproduced now?

**Comment by annadanchenko** [comment]
@rasom yes it can be reproduced on today's develop build on real iPhone 7 plus, see https://app.testfairy.com/projects/4803590-status/builds/6214474/sessions/32/?accessToken=qKbEMLgxeKLsGyApXNySbu6JOBE

**Comment by rasom** [comment]
ok, thanks

**Comment by annadanchenko** [comment]
can't reproduce on 0.9.12
