### ISSUE TITLE
Can't setup the sign in with fingerprint, using keycard

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#12553]
# Bug Report

## Problem 

I am trying to enable fingerprint login on my Status app.
My account is setup with a keycard.
I find the flow confusing and I am not able to reach a stage where my app is locked and I am able to unlock it with a fingerprint.

### Reproduction

1. In Privacy & Security I have "Lock app with fingerprint" on
2. The only way to lock the app seems to do profile > sign out
3. This gives a "log out" confirmation (Maybe better to keen same terminology across the screens? log out < sign out).
4. tap log out
5. To sign in, I have to enter my pin, "don't ask for card to sign in" is unchecked.
6. I check "don't ask for card to sign in" > pop ups to secure with fingerprint shows up
7. Tap enable fingerprint
8. touch sensor
9. "don't ask for card to sign in" is now ticked
10. enter pin
11. It ask for keycard, scan keycard
12. Logged in
13. Again, only way to lock the card I can see is "Sign out"
14. "Are you sure you want to log out?"
15. log out
16. back to log in screen where the "don't ask for card to sign in" is unchecked
17. Enter pin
18. Asks for keycard

I'd expect to be able to just scan with my fingerprint at steps 5 and 16.

### Additional Information

- Status version: 1.16.0
- Operating System: Android

**Comment by churik** [comment]
@D4nte 
Thank you for logging this!
It is already an open issue https://github.com/status-im/status-react/issues/9763 (it makes confusion around this feature) - basically, now it works this way:
1) if you enable logging with fingerprint - it will log you automatically in case you were logged out automatically (by a timeout or just closing the app)
2) if you logged out from profile and confirmed it - it is considered as manual log out and the app will always ask for keycard in this case
cc @hesterbruikman - maybe we can add new issue / transform existing https://github.com/status-im/status-react/issues/9763 to feature request?

This one I believe can be closed, @D4nte reopen if you have more questions.

**Comment by hesterbruikman** [comment]
Thanks @churik. Yes, makes sense to update the existing issue. Both sign out and log out are wrong terminology for what actually happens.

**Comment by D4nte** [comment]
Could https://github.com/status-im/status-react/issues/9763's description be updated to make it clearer what is the new/expected behaviour in relation to fingerprint usage + not requiring keycard?
At this stage, while I understand it is related I cannot assert that #9763 would resolve the problem I was facing.
