### ISSUE TITLE
Incorrect amount populated with QR code scan of EIP-681

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#12587]
# Bug Report

## Problem 
When scanning a QR code to make a payment, wallet populated the amount with zeros. Maybe amount in Gwei? QR code was reportedly following [eip-681](https://eips.ethereum.org/EIPS/eip-681)

#### Expected behavior
When using QR code scanner tx input fields are populated correct and readible with data from url

#### Actual behavior
- Currency > populated correctly (DAI)
- Amount > not populated correctly. Lots of 0's looks like denomination is off/not parsed. Amount in USD looks derived from incorrectly populated token amount and now shows 275,000,000,000,000,000,000.00 USD
- Address > unsure, cut off screenshot 😕

![Screenshot_20210915-182451_Status](https://user-images.githubusercontent.com/35233054/133474431-db464e7c-d7c8-4ca6-b6d4-31eb2e7dd1f5.jpg)

### Reproduction

1) Open Status
2) Open Wallet
3) Tap QR code scanner
4) Scan QR code that follows eip-681 with $275 in DAI (not sure if issue occurs with other tokens)

### Additional Information

- Status version: 1.16.0 (20210827115911) afaik this is a public release
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
Can send Trace logs if needed, please ping if that helps. Didn't notice anything in particular; seems like a UI bug

**Comment by flexsurfer** [comment]
how can we make sure QR code is correct ?

**Comment by hesterbruikman** [comment]
I believe this using was used: https://github.com/esPass/pretix-eth-payment-plugin

I haven't checked, but I suspect it includes QR code generation

**Comment by churik** [comment]
@hesterbruikman afaik we didn't use the amount converted in USD in QRs, I didn't check it because we don't have such option in wallet.
I've tested always with https://brunobar79.github.io/eip681-link-generator/# and I didn't see any option to add converted value to amount.
I may be wrong though, but we need QR for investigating this

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
