### ISSUE TITLE
ERC-20 assets are not shown after restoring multiaccount

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12586]
# Bug Report

## Problem 
Wrong assets (that multiaccount doesn't own) are shown after recovering it from seed phrase.
On the main user for e2e (Ropsten network) only MDS are shown, however he owns ADI and STT
Likely regression caused by some of the commits made on 15.09 (on nightly 15.09 no issue, so it is recent regression in `develop`)

#### Expected behavior
assets are the same as on etherscan  (ADI + STT)

#### Actual behavior
can see MDS

### Reproduction

1) Open Status
2) Restore multiaccount `tree weekend ceiling awkward universe pyramid glimpse raven pair lounge grant grief`
3) Check out balance and compare it with Etherscan

### Additional Information

- Status version: develop (nightly 16/09) 
- Operating System: Android, iOS
Logs: [status_logs.zip](https://github.com/status-im/status-react/files/7171551/status_logs.zip)

**Comment by alaibe** [comment]
@churik since this one has been merged: https://github.com/status-im/status-go/commit/5d1fe07544b7970d86ccdef574470dd6deca15f3 this one should now be resolved. Let me know if you still have issue
