### ISSUE TITLE
Can't connect to zk.money dapp 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12592]
https://zk.money/signin

When trying to connect web3 with the dApp by clicking on 'Metamask', we get an error message 'Unable to connect to Metamask'

**Comment by flexsurfer** [comment]
nothing we can do on our side, probably it's trying to detect MM somehow

**Comment by guylouis** [comment]
ok, thanks
Btw ... do we have recommendations for dApps developers on how to make their dApp compatible with Status?

**Comment by flexsurfer** [comment]
yes, we even have tutorials https://status.im/developer_tools/
