### ISSUE TITLE
Remove the limit on community member count

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12593]
As the moderator of a large community, I'd like all of my members to be able to exist on the Status community.

I don't want to use Discord, and so moving everyone over to Status is the most logical option, but I can't because it has a limit of 20 members per community.

**Comment by guylouis** [comment]
Hey, private group chats are indeed limited to 20 users in status. We're preparing a new type of groups called communities, where you can read and write only if you're a member, and where there is no limitation of members. It's under development and not ready to launch but you can test it already both on mobile and desktop status app. For this you need to enable 'communities' in the 'advanced' section.

**Comment by du82** [comment]
I understand. What about public communities that anyone can become a member without requiring an admin to accept you? That would be very useful, and great to compete with Discord.
