### ISSUE TITLE
Clicking on 3 word user name does nothing

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12599]
#### Expected behavior

User profile is opened

#### Actual behavior

Nothing happens

### Reproduction

https://user-images.githubusercontent.com/41779817/133832245-8702a4de-3337-4a69-a586-2784497184cd.MP4

### Additional Information

- Status version: 1.16 
- Operating System: iOS

**Comment by flexsurfer** [comment]
hey @rapidddenis thanks, could you please add steps on how we could replicate it? it's not obvious from the video

**Comment by rapidddenis** [comment]
1. Start 1-1 chat
2. Tap on the 3-word name or ENS name on the top of the screen
3. nothing happens

**Comment by rapidddenis** [comment]
Try the same with 3-word name next to message in chat and it opens user profile

**Comment by Parveshdhull** [comment]
> 1. Start 1-1 chat
> 2. Tap on the 3-word name or ENS name on the top of the screen
> 3. nothing happens

The topbar also opens the profile.
But looks like only the thumbnail circle is touchable not the chat title label.

**Comment by rapidddenis** [comment]
Exactly
