### ISSUE TITLE
No error feedback for creating channels with same name

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#12595]
# Problem

If a user uses the same name for two channels, then there is no error feedback is shown. The button feels like not working.

## Implementation
https://user-images.githubusercontent.com/17097240/133718656-ba283bb1-a906-4f6f-89e0-8a4d2b5733f6.mp4

## Acceptance Criteria

It will be great if an error message is shown.

**Comment by churik** [comment]
IMO should be addressed along with https://github.com/status-im/status-react/pull/12189

**Comment by churik** [comment]
part of https://github.com/status-im/status-react/issues/12010
