### ISSUE TITLE
Category names don't show up in communities

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12601]
# Bug Report

## Problem 
The names of categories rarely show up in Communities on Android and to a lesser extent iOS

#### Expected behavior
Category names should show up every time a community is opened

#### Actual behavior
Category names do not show up next to the dropdown icon, and look like they're left blank

### Reproduction

1) Open Status
2) Open a community that uses categories
3) Check for missing category names

### Additional Information

- Status version: 1.16 installed from Google Play
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
hey @ducheng0 , thanks, is that happening in dark mode ? https://github.com/status-im/status-react/issues/12556

**Comment by du82** [comment]
> hey @ducheng0 , thanks, is that happening in dark mode ? #12556

Yes it is

**Comment by flexsurfer** [comment]
duplicate  #12556
