### ISSUE TITLE
web3.eth.getBalance(context.from) from my App not linked to testrpc accounts

### ISSUE THREAD

**Issue by JoaquinFT** [status-im/status-react#1263]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

as a developer i wanted to make a transaction using the API to test my chatbot

### Description

bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: i ran testrpc, the status wallet recognizes the adresses on testrpc. but when in my javascript file i try to see the balance of my account it tries to get the balance of an adress which is not in the testrpc. it is like it is playing with another set of adresses.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

it was expected for me that the adress detected by the contract was my main adress on testrpc

#### Actual behavior
[comment]: # (Describe what actually happened.)

but in practice is using another adress
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

create a bot, and in your js code do a web3.eth.getBalance(context.from) ... it will say that the wallet is empty even though on testrpc all the wallets have 100ETH

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nighltly build
[comment]: # (Android or iOS.)
* Operating System: Galaxy J5 Android and Ubutnu linux on my desktop

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by yenda** [comment]
Fixed
