### ISSUE TITLE
App crashes on some devices with Android 5.0 (while syncing or opening bchat)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1264]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After installation, during 1st sync, app crashes if leave it for a while or if open bchat.

Devices where it can be reproduced:
* LG G3 D855. Android	5.0.	Quad-core 2.5 GHz Krait 400 / ARMv7 / 2048 MB / QHD (2560 x 1440). Log: 
[manual-testing-3234815 (1).log.txt](https://github.com/status-im/status-react/files/1049840/manual-testing-3234815.1.log.txt)

* LG Google Nexus 5 D820 5.0.  Android 5.0. Quad-core 2.3 GHz Krait 400 / ARMv7 / 2048 MB /Full HD (1920 x 1080). Log: 
[manual-testing-3234817.log.txt](https://github.com/status-im/status-react/files/1049841/manual-testing-3234817.log.txt)

* Samsung Galaxy Note 3 SC-01F. Android 5.0. Quad-core 2.3 GHz Krait 400 / ARMv7 / 3072 MB / Full HD (1920 x 1080). Log: 
[manual-testing-3236903.log.txt](https://github.com/status-im/status-react/files/1052288/manual-testing-3236903.log.txt)

* OnePlus One A0001 OxygenOS. Android 5.0.2. Quad-core 2.5 GHz Krait 400 / ARMv7 /3072 MB
Full HD (1920 x 1080). Log: 
[manual-testing-3239809.log.txt](https://github.com/status-im/status-react/files/1058073/manual-testing-3239809.log.txt)
* Samsung Galaxy Note 3 (SM-N9005)

* Instabug reporter with Samsung Galaxy S4 (Samsung GT-I9505). Android 5.0: "The application close right after I enter my password" 

In all logs for crashing I see lots of "ThermalEngine" entries.

In the same time, app does not crash on these devices:
* LG G Flex 2 H955. Android 5.0.1. Quad-core 1.5 GHz Cortex-A53 & Quad-core 2 GHz Cortex-A57 / ARMv8-A / 2048 MB / Full HD (1920 x 1080)
* Motorola Moto G3. Android 6.0.1 / ARMv7 / 1024 MB / HD 720 (1280 x 720)
* Huawei Honor 7 PLK-L01. Android 5.0. Quad-core 2.2 GHz / ARMv8-A / 3072 MB / Full HD (1920 x 1080)
* Sony Xperia M4 Aqua E2303. Android 5.0. Quad-core 1.5 GHz Cortex-A53 & quad-core 1.0 GHz Cortex-A53 / ARMv8 / 2048 MB / HD 720 (1280 x 720)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App can finish synching, bchat load boards
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashes 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Q09XTFRoSmhsY00
- Install Status
- Create password
- Wait for sync to start
- Wait till sync is done or open bchat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.8, 0.9.10-31-g0df8dcad+ (1588)
* Operating System: Android 5.0
* TF: https://app.testfairy.com/projects/4803622-status/builds/6429877/sessions/20/?accessToken=VNk2/INTd-vzoHij4qwoflPv7fU

**Comment by louisgv** [comment]
The app also crashes after about 20-30 seconds idle as well. I am on Android 5.x and thanks god I managed to setup the password, but just leave the app 10-20 seconds idle and it will crash and close.

**Comment by annadanchenko** [comment]
Will not fix after setting minimal OS as Android 6: #4651
