### ISSUE TITLE
Can't send funds to multisig - Out of gas

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#12642]
# Bug Report

## Problem 
When sending funds to a Gnosis multisig, the tx failed 4 times. Sending funds to 2 different addresses, both Gnosis multisig contract addresses. Error on Etherscan for transactions send using Status Wallet says `Warning! Error encountered during contract execution [Out of gas]`

I was able to:
- Send funds from the same account as used in Status using https://www.myetherwallet.com/wallet/send-tx in combination with Frame to sign.
- Send funds from a different account through MetaMask 
- Sign contract interaction to exchange on Uniswap using Status wallet

Etherscan shows succesful transaction signed with Frame to use a bit more gas, but not much:
- Frame: 0.001414693564
- Status: 0.001054394619 (highest amount of gas out of 3 failed transactions)

#### Expected behavior
Wallet accurately estimates fees required to send funds to contract

#### Actual behavior
Wallet does not accurately estimate fees required to send funds to contract in case of contract being a Gnosis multisig
(Don't have an address to verify if the issue occurs only for Gnosis multisigs or also for other multisign contract addresses)

### Reproduction

1) Open Status
2) Open Wallet
3) Send
4) Enter multisig address as recipient (ping @hesterbruikman for address if needed)
5) Receive warning about interacting with contract > Tap OK
6) Sign and send tx > View progress on Etherscan

### Additional Information

- Status version: Release 1.16
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
![Frame 1](https://user-images.githubusercontent.com/35233054/134492500-41093eef-5a64-4642-8419-d5c15ea333d7.png)

**Comment by carlfairclough** [comment]
I wonder why this is using so much gas? 21000 should be sufficient for sends.

**Comment by flexsurfer** [comment]
> I wonder why this is using so much gas? 21000 should be sufficient for sends.

yes, its an answer to why tx is failing, because 21000 is for sending ETH to non-contract addresses, so we have a condition in status-react, if tx has only ETH and no data (for a contract) we don't estimate gas, and set it to 21000, but in some cases, ETH may be sent without data to contract, and in that case, contract could do additional calculations and use more gas

related issue https://github.com/status-im/status-react/issues/12583

**Comment by flexsurfer** [comment]
i don't remember why we did this, at some point ETH estimation was wrong, and we hardcoded 21000, but its pretty easy to fix
