### ISSUE TITLE
Mention preview is displayed as @0x... instead of user name/ENS on the home screen and in the Activity center

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12649]
# Bug Report

## Problem 
If send a mention to any chat, it will be displayed as `@[chat_key]` on the home screen.

#### Expected behavior
3-random name/ENS is shown in preview
<img width="218" alt="Screenshot 2021-09-24 at 12 32 19" src="https://user-images.githubusercontent.com/67952253/134660764-93fa0e54-5871-4e0f-bfc5-a0326e5aff76.png">

#### Actual behavior

Mention is displayed as `@0x...`
<img width="259" alt="Screenshot 2021-09-24 at 12 32 05" src="https://user-images.githubusercontent.com/67952253/134660727-dc83a74b-3e85-4015-9db7-7b51521c24b5.png">

### Reproduction

1. Open Status
2. Start any chat
3. Send mention 
4. Navigate to the home screen

### Additional Information

- Status version: nightly 24/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
that's because of chat list optimization, i don't have any good solutions for this

**Comment by churik** [comment]
hmm, let's ask @hesterbruikman what is her opinion on this. Maybe instead of raw public key better to show some label?

**Comment by flexsurfer** [comment]
i mean, for optimization we just show 200 chars of text, we don't parse it, so we don't know what in this text

**Comment by hesterbruikman** [comment]
@flexsurfer what do you think the impact of not parsing text messages is on optimization? 

Would parsing affect populating the list on opening the tab, or also scrolling the list?

**Comment by churik** [comment]
Blocks e2e 695845
![IMAGE 2021-09-28 12:45:43](https://user-images.githubusercontent.com/4557972/135072950-31723813-d3d4-4b71-9542-09858c5104d4.jpg)

**Comment by flexsurfer** [comment]
@churik could you elaborate please, how it blocks e2e ?

**Comment by churik** [comment]
sure; 
on 695845 e2e we are checking that:
- notifications by text are presented in the activity center;
- tapping on them and make more checks.

I'm not sure that I need to replace text `User is mentioned` by `@0x..... is mentioned` - obviously it is not what users expect to see in mention messages, so we need to define how the feature will look like and afterward I can edit texts of mention messages as well.

**Comment by flexsurfer** [comment]
thanks , i'll take a look then
