### ISSUE TITLE
The chat list is missing the last message, in the case of community Invite

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#12650]
# Problem

Previously app used to show the last message with the invited community name, currently, it is showing blank.

## Implementation
<div align="center">
<img src="https://user-images.githubusercontent.com/17097240/134723072-f83b0047-a9a8-4e14-b9c7-56baf5e80a23.png" alt="Screenshot" height="400"/>
<img src="https://user-images.githubusercontent.com/17097240/134723106-385ce077-1e09-4ed5-9afe-eca2cba65aa3.png" alt="Screenshot" height="400"/>
</div>

**Comment by Parveshdhull** [comment]
Maybe this was intentional to improve chat list performance 🤔
In that case, feel free to close the issue 👍

**Comment by flexsurfer** [comment]
its not intentional
