### ISSUE TITLE
Can't join group by request membership link if you are already a member

### ISSUE THREAD

**Issue by dankrad** [status-im/status-react#12657]
# Bug Report

 I was invited to a channel (as admin) while I was offline. I did not receive any notification about this. Later I joined the channel via link and requested to join.

The channel admin now cannot se my request, and neither can they add me as an admin again. My app is permanently stuck in "Request pending..."

## Problem 

I cannot join the channel

#### Expected behavior

1. It should have added me to the channel as soon as I came online, even though I was offline when I was originally added.
2. When I tried to join the channel via invite link, I should have been added automatically, without sending a request.
3. The channel admin should still be able to add me or respond to my request.

#### Actual behavior

"Request pending..."

### Reproduction

1) Open Status
2) 

### Additional Information

- Status version: 1.16.0 (20210827115911(
- Operating System: Android

**Comment by churik** [comment]
@dankrad 
Thank you for reporting!
Can you please elaborate, was it an invitation to a group chat or to the community (which is in alfa stage)?

**Comment by dankrad** [comment]
As far as I know it's a group chat. Can give you more details via email?

**Comment by churik** [comment]
sure, you can email us via error-reports@status.im

**Comment by dankrad** [comment]
Sent.

**Comment by churik** [comment]
So I believe what happened is an edge case, as far as I understood from the info:
- user A has `device A`  and have bought  `device B`
- user C created group chat and send invite link to user A
- user A has requested access via group chat invite link
- user A was offline on `device B` for a while (probably more > 24h). During this time he was added as an admin of group chat 
- user A tried to access group chat via link on `Device B` - `Request pending` is shown
- group chat has never appeared on `Device B` or on `Device A`

So User C has no option to remove user from group chat (he was added as admin), User A has no option to access group, as accessing via link shows `Request pending`

**Suggested solution:**
If user was already added to group chat and access it via group link, show Group chat itself instead `Request pending`.
What do you think @cammellos is it possible?

**Comment by dankrad** [comment]
> user A tried to access group chat via link on Device A - Request pending is shown

Correction, this was on `device B`.

**Comment by churik** [comment]
closing due to re-design
