### ISSUE TITLE
Old chats don't fully sync; old contacts not displayed with ENS name until chatted to

### ISSUE THREAD

**Issue by dankrad** [status-im/status-react#12659]
# Bug Report

## Problem 
After changing to a new mobile, chat history was not fully synced (despite setting it to 1 month, not all chats from this time were synced). More annoyingly, all old contacts are, until I chat to them, only displayed with cryptic names, not their ENS names.

#### Expected behavior

1. Sync should be complete, there should also be an option for all time.
2. All contacts should be displayed with ENS names, not only after you chat to them.

**Comment by churik** [comment]
@dankrad thank you for reporting!
What do you mean by `after changing on new mobile`?
Did you buy new device and restore your multi-account from seed phrase on it, right?

**Comment by dankrad** [comment]
Not sure what multi account means. I have a new phone, restored using seed phrase and enabled sync on both old and new devices.

**Comment by churik** [comment]
Ah, yes I see.
So issues that you mentioned are resolved and will be available on 1.17:
- https://github.com/status-im/status-react/pull/12541 - here with contacts
- and partially with chat https://github.com/status-im/status-react/pull/12644
