### ISSUE TITLE
Unable to rejoin public chat after deletion until relogin

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12669]
# Bug Report

## Problem 
If join a public chat, delete it, and try to rejoin, it won't appear on the home screen, If relogin and try to join again it will work - the public will appear on the home screen.

#### Expected behavior
Can rejoin public chat after deletion without relogin

#### Actual behavior

https://user-images.githubusercontent.com/67952253/135307402-dc5bcbb1-6128-4025-a38b-be57aa7f7d6c.mp4

### Reproduction

1. Join some public chat
2. Open the home screen > Long tap > Delete
3. Join the same public chat
4. Open the home screen
5. Relogin
6. Join the same public chat one more time and check the home screen

### Additional Information

- Status version: nightly 29/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
issue is on status-react side

**Comment by rasom** [comment]
fixed here https://github.com/status-im/status-react/pull/12662
