### ISSUE TITLE
Please add localStorage or some sort of local storage to bot API

### ISSUE THREAD

**Issue by makoto** [status-im/status-react#1266]
### User Story

As a developer, I want Bot to be able to save some value locally so that user does not have to keep providing the same value again and again.

### Description

*Type*: Feature

Local sorage is mentioned [here](https://github.com/status-im/status-react/search?utf8=%E2%9C%93&q=localStorage&type=) but does not seem working. Also `localSorage.set` in one of bot code seems wrong.

#### Expected behavior

`localStorage.setItem('foo','bar')`

https://developer.mozilla.org/en/docs/Web/API/Window/localStorage

**Comment by jarradh** [comment]
there is currently `web3.db` which is not ideal, can be used for hackathon ?

**Comment by morelazers** [comment]
@jarradh can you or others advise on the best way to use this?
![image](https://cloud.githubusercontent.com/assets/2966123/26767119/1997b1f8-49e0-11e7-9d52-c407775c9464.png)

**Comment by makoto** [comment]
It's obsolete https://github.com/ethereum/go-ethereum/issues/311 I got the same error message when I tried on my local node on my machine (without pointing to status's own node).

**Comment by jarradh** [comment]
well shit, my mistake, sorry. The guys are looking at alternatives now

**Comment by rasom** [comment]
`localStorage` is available in `develop` branch
