### ISSUE TITLE
`No potocol method` error when tapping + in Bootnodes

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12667]
# Bug Report

## Problem 

![IMAGE 2021-09-29 15:07:47](https://user-images.githubusercontent.com/4557972/135274406-0e6a846b-471f-4a47-b7e4-83ea3b17ab24.jpg)
Firstly reproduced on nightly 29/09/21 (no issue on nightly 28/09/21)
Blocker for e2e 5432.

#### Expected behavior
Can add custom bootnode

#### Actual behavior
error when tapping on + 

### Reproduction

1) Open Status
2) Go to Profile > Advanced > Bootnodes > +

### Additional Information

- Status version: nightly 29/09/21
- Operating System: Android, iOS

**Comment by rasom** [comment]
this commit https://github.com/status-im/status-react/commit/a0acdeca33d34439c45e44afc541d345a92824c5
