### ISSUE TITLE
Drawer is not hidden if tap outside it [iOS only]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1267]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When drawer is opened then it's possible to hide it only by swipe left. It should be possible to hide it by tap outside (as it happens in Android version)
![img_1558](https://cloud.githubusercontent.com/assets/6584810/26760364/b846d422-491e-11e7-8515-b639a7c0a947.jpeg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Drawer is hidden when tap outside of it
#### Actual behavior
[comment]: # (Describe what actually happened.)
Drawer stays opened if tap outside of it. The only way to hide it now is to swipe left
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open drawer
- Tap on black area outside of the drawer

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.8
* Operating System: iOS 10.2.1, iphone 6s

**Comment by cnolimit** [comment]
I ran a build just now on my local machine, didn't get that bug, when i clicked on the black area it seemed to close the drawer fine.

**Comment by annadanchenko** [comment]
Can reproduce on 0.9.12 released version with real iphone 6s (iOS 10.3.3). If user taps outside the drawer then nothing happens (expected: drawer is closed). If user swipes drawer then it's closed (this works fine). So issue is in only if tap outside.

**Comment by status-open-bounty** [comment]
Balance: 0x0 ETH
Tokens: SNT: 2000.00
Contract address: [0x61da1b575633c7fbc59f3fe94ccdc646621584d6](https://etherscan.io/address/0x61da1b575633c7fbc59f3fe94ccdc646621584d6)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: andytudhope
Visit [http://194.44.239.202:3003](http://194.44.239.202:3003) to learn more.

**Comment by annadanchenko** [comment]
Can reproduce on today's (Nov 15) develop build  0.9.11d365 with real iPhone 7 Plus. Video and log:
https://app.testfairy.com/projects/4803590-status/builds/7091484/sessions/2/?accessToken=aUNWuoPiH/C7hSjrbCXjpn9sPmg

**Comment by SHA-2048** [comment]
tested this with develop branch and an iPhone 6 simulator. It is working as expected. So maybe you can re-check it @annadanchenko and close the issue if not needed anymore.

**Comment by pablanopete** [comment]
What's the state of this? @annadanchenko? Can we revoke since this drawer will be removed?

**Comment by oskarth** [comment]
@pablanopete Correct, no longer part of UI. Don't know what happens if we close with outstanding bounty - do you want to close it?

**Comment by pablanopete** [comment]
@oskarth I'll need to ping @tpatja about revoking.

**Comment by annadanchenko** [comment]
drawer is removed, not it's tab
