### ISSUE TITLE
Make keycard pairing password a default one

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12685]
To simplify user experience the idea of using a fixed, default pairing password when setting up Keycard with Status has come up. The idea is that this way we can do pairing without any user interaction, unless the user intentionally changed the pairing password (the option to do so will remain).

Full description here: https://hackmd.io/8g0MuXW2TSixVpJDEs5jdg

To be done: 
[ ] make generated pairing code a default one 
[ ] any place in the flows where the pairing code is asked to the user, replace this by automatic fullfilment of the pairing code

**Comment by bitgamma** [comment]
let's decide what the default password should be!

**Comment by bitgamma** [comment]
I'll make the pass KeycardDefaultPairing
