### ISSUE TITLE
Can't hide Profile picture from another user if it was once seen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12680]
# Bug Report

## Problem 
If first UserA sets `Show your profile picture to: Contacts` and UserB is a contact of UserA, but after that UserA changes this setting to `Show your profile picture to: None`, then UserB will still see the profile picture of UserB.
But if UserA first changes the settings to `Show your profile picture to: None`, and then started a chat with UserB, then UserB will not see UserA's profile photo.

#### Expected behavior

- UserB can't see UserA's profile picture after changing the setting or deleting UserB from contacts
- **As a temporary solution, there may be a warning to users that they will not be able to hide their profile picture for users who have already seen their profile picture (add some explanation to the `Show my picture to` screen** (suggested [here](https://github.com/status-im/status-react/pull/11768#issuecomment-931240752)))

#### Actual behavior

Once seen by another user, the profile picture cannot be hidden

### Reproduction

1. Add profile photo
2. Add UserB to contacts and start 1-1 chat
3. UserB adds UserA to contacts
4. UserA: Settings > Privacy and security > `Show your PP to: None` (or delete UserB from contacts)
5. UserB: check profile photo of UserA

### Additional Information

- Status version: nightly 4/10
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
One more example: user also won't see a photo of contacts if ha had restricted and changed settings after until contact will reset profile photo or send message to public chat

**Steps**
1) User1: has `Show profile photos to` - None, `Show profile photos of` - None
2) User2: has `Show profile photos to` - Contacts, `Show profile photos of` - Contacts, set profile photo
3) User1 adds User2 to contacts, User2 adds User1 to contacts. No photo is shown for User2 as expected.
4) User1: changed settings to `Show profile photos to` - Everyone, `Show profile photos of` - Everyone
In that  case he will not see updates from User2 until (1) he posts smth in the public chat to which both are joined OR (2) he will change profile photos


### To summarize how the feature works now:

1.  No way to `hide` your profile photo for users, that have already seen it
(but if you set it to `None` and then changed profile photo, no updates will be shown for your contacts)
2. When changing setting `Show profile photos to`, `Show profile photos of` they will work for new users (which you have never interacted with), but for existing users (your contacts, for users that have seen your photo in pub chats / group chats, communities) there are 3 ways to update: 
       - (1) post smth to public chat, 
       - (2) updating this profile photo, 
       - (3) adding user to your contact (if you changed some of settings to `Contact`)
**Until one of these actions no updates will be shown for existing contacts / in 1-1, group chats**


@hesterbruikman it looks a bit complicated and I'm not sure how we can explain current limitations to users now and are we OK to release it like this in 1.17.
Need your opinion here.
Thank you!

**Comment by cammellos** [comment]
I believe point 2 can be addressed, I can take a look at it. 
Point 1 is harder, there's always going to be some edge cases where the picture is visible unfortunately (that's due to the p2p nature of the application), so warning the user might make sense.

**Comment by hesterbruikman** [comment]
From a chat with @churik For point 1, we probably want to add a subtext to the setting:

`Show profile photos to` 
People who have already seen your profile picture will continue to do so

Same list item as Webview camera permisison

Sidenote: the list item should only be active if a custom profile picture has been added. Else it should apppear as Back up seed phrase after seed phrase has been backed up

**Comment by cammellos** [comment]
@hesterbruikman 
I can't fit "People who have already seen your profile picture will continue to do so" (at least on my device), could we shorten it if possible?

Another way would be to use instead of "Show your profile pictures to" "Share your profile pictures to", which to me sounds better represent the behavior, though not sure it would be for the average user
