### ISSUE TITLE
Stickers button is missing on latest PR build

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12682]
It's not possible to send stickers on the latest beta builds.

To test this, download the latest merged PR build, open a public, group, community, or private chat and try to send a sticker. the button isn't there.

**Comment by flexsurfer** [comment]
cc @churik

**Comment by flexsurfer** [comment]
@ducheng0 i can't replicate, are you sure you're on mainnet? stickers work only on mainnet

**Comment by du82** [comment]
Thanks, that fixed the problem.
