### ISSUE TITLE
Messages disappear from Timeline if join public chat and open Timeline tab while public chat history is loading

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12684]
# Bug Report

## Problem 

If post a message to Timeline, join a public chat, and quickly navigate to the Timeline tab while public chat history is loading, then timeline messages disappear when public chat history is loaded.
If send another message to Timeline or re-open the Timeline tab, the messages will be restored.

#### Actual behavior

https://user-images.githubusercontent.com/67952253/135993184-3f78e0c7-266b-41b0-ac55-b9c3ea9988ac.mp4

### Reproduction

1. Post smth to Timeline
2. Open the home screen and join a public chat, e.g. #status
3. Quickly navigate to the Timeline tab

### Additional Information

- Status version: nightly 5/10
- Operating System: Android, iOS

[geth.log](https://github.com/status-im/status-react/files/7284408/geth.log)
[Status.log](https://github.com/status-im/status-react/files/7284410/Status.log)

**Comment by churik** [comment]
blocker for 6342: `test_different_status_in_timeline`
