### ISSUE TITLE
Mobile release 1.17

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12711]
Issue to manage mobile release 1.17

### Scope

https://github.com/status-im/status-react/milestone/56

- release notes: 
- release branch: https://github.com/status-im/status-react/tree/release/1.17.x 

### Testing info 
[comment]: # (TestRail info, added by QA)
Main test suite: https://ethstatus.testrail.net/index.php?/runs/view/8041&group_by=cases:section_id&group_order=asc&group_id=891
Upgrade (e2e): https://ethstatus.testrail.net/index.php?/runs/view/8042&group_by=cases:section_id&group_order=asc

### Builds in TestFlight and PlayStore to push as a release
[comment]: # (Will be added by QA after testing approving of build)
APK: https://status-im-releases.ams3.digitaloceanspaces.com/StatusIm-Mobile-v1.17.0-c34b91-universal.apk
IOS: 1.17.0(2021102133339)

#### 1) Kick-off
- [x] 1. Translation PRs is merged before cutting branch (Jinho)
- [x] 2. Prepare scope of visible changes based on commits history, started from previous release branch cut ([example]( https://notes.status.im/1.14-release-notes?view))
- [x] 3. Update [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) with release notes (make PR based on previous step)
- [x] 4. Create release branch using this [guide](https://github.com/status-im/status-react/blob/develop/doc/RELEASE_GUIDE.md), bump VERSION (merge created PR ([example](https://github.com/status-im/status-react/pull/12504) ) to develop) and get successful release builds (so, testing can be started)
- [x] 5. Based on release scope, ask for comms (Jonny) 
- [x] 6. Make sure that assets (screenshots, video) in stores are up to date. If should be updated, ask @cammellos  for help

#### 2) Testing
[comment]: # (Section will be maintained by QA)
- [x] Dogfooding (add notes, if it was held) 
- [x] Regression testing for release candidate build
- [x] Upgrade tests
- [x] Fix known blocker(s) found during regression testing

##### Blockers
[comment]: # (Section for blocker issues; should be fixed and merged by release-manager. Remove if no blockers found)
- [x] 1 blocker: https://github.com/status-im/status-react/issues/12720
- [x] 2 blocker: https://github.com/status-im/status-react/issues/12718
- [x] 3 blocker: https://github.com/status-im/status-react/issues/12717
- [x] 4 blocker: https://github.com/status-im/status-react/issues/12727
- [x] 5 blocker: https://github.com/status-im/status-react/issues/12715
- [x] 6 blocker: https://github.com/status-im/status-react/issues/12719
- [x] 7 blocker: https://github.com/status-im/status-react/issues/12731

=========================================================================================
- [x] Cherry-pick fix(es) to the release branch
- [x] Verify fix(es) on new release candidate build
- [x] Retest
- [x] Keep release build forever (button in Jenkins)

#### 3) Submission

- [x] 1. Release notes written and added (500 character limit for updates (Android) and PR for [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) is ready to be merged (from 1.3 step)
- [x] 2. Submit beta version for Android (Open Testing in Play Store)
- [x] 3. Submit iOS build to Apple review ([instruction](https://drive.google.com/file/d/10Cl7PBB7TFPkZiVbfzdFGpfMRP9bxXuq/view?usp=sharing), be careful - low quality of audio)
- [ ] 4. Play store content reviewed and updated
- [ ] 5. Privacy policy reviewed and updated (ask in channel)
- [ ] 6. Countries to be excluded (ask in channel) 
- [ ] 7. Changes to our FAQ made (should be checked and if any changes needed, ask Jakub to made them)
- [x] 8. Prepare PR for F-droid build ([instruction]( https://github.com/status-im/status-react/blob/develop/doc/FDROID.md))

#### 4) Before publishing
- [ ] 1. Translations for comms available (marketing, ask in the channel)
- [x] 2. Promotional content ready (marketing, ask in channel)
- [ ] 3. Upload builds for DO store,  https://dev.status.im/ (Jakub)

#### 5) At time of publishing
- [ ] 1. Notify marketing to push comms and blog post (Jonny)
- [ ] 2. Publish release to app store and playstore
- [ ] 3. Final push to update prod site https://status.im/,  [instructions](https://github.com/status-im/infra-docs/blob/master/articles/status_release_upload.md) (Jakub - requires credentials to upload) 
- [ ] 4. Add the link to the post about the release and publish the release: https://github.com/status-im/status-react/releases (Jakub)
- [ ] 5. Merge PR for updating [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) (from 1.3 step)

**Comment by Samyoul** [comment]
Completed scope of changes https://notes.status.im/CUq4tVKgS_C03pgsk5D02Q?both

**Comment by Samyoul** [comment]
Release notes PR https://github.com/status-im/status-react/pull/12714

**Comment by Samyoul** [comment]
## Release notes

**Blog post:**

preview at https://our.status.im/p/f2aa0d3c-769d-498d-9623-2977fda4107b/
[done, just needs some links fixed]

**Playstore:**

1.17.0

Status v1.17 introduces several messenger and wallet updates, including better image sharing, privacy settings for profile pictures, and customizable thumbnails for community channels. Multi-device syncing has been added for deleted chats and modified contacts, and multisig wallet gas estimation has been fixed. And things are faster.

**Status public server:**

Status v1.17 released
Contains the following features
- "Share" feature for images
- privacy settings for profile pictures
- profile pictures in push notifications
- custom emoji thumbnails for community channels
- multi-device sync on deleted chats and altered contacts
- added RARE token
- nonce can be overridden when sending transactions
- multisig gas estimation compatibility fixes
- legacy tx UI for networks without EIP-1559
- doubled timeline post character limit

**Blockfolio signal:
Twitter:
Facebook:**

 Status v1.17 is out! 

 Profile pictures are private by default
 Emoji thumbnails for community channels
 Multi-device sync improvements
 Deleted messages

[link to blog (link to releases also for blockfolio signal)]

**Reddit:**

[post blog on release

---

Source : https://discordapp.com/channels/624205794384281629/739764149516501053/901126605190070282

**Comment by Samyoul** [comment]
PR for fdroid https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9979

**Comment by Samyoul** [comment]
fdroid build https://f-droid.org/wiki/page/im.status.ethereum/lastbuild_2021102112

**Comment by cammellos** [comment]
Closing this, feel free to re-open if there's any outstanding work to be done
