### ISSUE TITLE
No preview for transaction messages in 1-1 chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12717]
# Bug Report

## Problem 
<img width="412" alt="photo_2021-10-18 12 17 10 jpeg 2021-10-18 12-17-36" src="https://user-images.githubusercontent.com/4557972/137712787-5de74d2b-c482-4fdd-b079-01008ff31b17.png">

#### Expected behavior
can see preview for message

#### Actual behavior
no preview

### Reproduction

1) Open Status
2) Start 1-1 chat
3) Request some assets
4) Get back to home view

### Additional Information

- Status version: RC 2 1.17
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
@flexsurfer Also, no preview for emoji messages in all types of chats. 
Could you fix it in the same PR, please?
