### ISSUE TITLE
Please help ASAP! Status glitched and my stuff is gone!!

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12715]
# Problem

My Status locked me out just now and I can't get back in, the app gives me this error, and everyone I talk to is saved as contacts, and chat history is there too. Please help me get back into my account if it's possible...
All of my family and important contacts are there, and I don't have their chat keys or message history saved anywhere, but I do have my mnemonic phrase if that helps.

![Screenshot_20211016-211042_Status](https://user-images.githubusercontent.com/65834069/137607901-1427796e-1e3c-4f79-9976-ae650c4ec105.png)

**Comment by cammellos** [comment]
@ducheng0 which version of the app were you/are you running?
looks like you might have been running PR/nightlies, is that the case?

**Comment by du82** [comment]
@cammellos I was running the version 1.16 from Google Play. No idea what happened but it would be great to have my contacts and messages back

**Comment by cammellos** [comment]
@ducheng0 are you sure you did not install any nightly, or PR builds? that would help debugging the issue, and generally the error you showed above is a migration error, which happens when upgrading builds, and we need to know which one you upgraded to & from. 
Could you also send the version of the app? (in the settings you should find those infos)

Thanks

**Comment by du82** [comment]
@cammellos I do regularly test and give feedback on other's PR builds, but this was the official version 1.16.0 from the Google Play store, it wasn't a PR, nightly, or debug build. I didn't update the app recently, and I have auto-updates off on Google Play. I can't access the settings because I can't log in, but on my phone it comes up as "**Version 1.16.0 - App downloaded from Google Play Store**"

**Comment by flexsurfer** [comment]
hey @ducheng0 nightly has the same application id, so if you installed nightly (or any other apk with the same application id) it was installed on top of play store app, and next time it was updated from app store it could have conflicts

**Comment by cammellos** [comment]
@ducheng0 if you ping me on discord when you have some time we can try a few things to at least recover the data

**Comment by cammellos** [comment]
@ducheng0 we managed to replicate, we'll fix it for 1.17, we can also send you a link to a fixed build once that's resolved, sorry for the inconvenience

**Comment by du82** [comment]
@cammellos What's your Discord tag?

**Comment by du82** [comment]
> @ducheng0 we managed to replicate, we'll fix it for 1.17, we can also send you a link to a fixed build once that's resolved, sorry for the inconvenience

Please send me that build when you can, thanks :)

**Comment by cammellos** [comment]
@ducheng0 the app has been released on the beta play store, or @churik can send you a link if you need it.
Sorry for the inconvenience

**Comment by churik** [comment]
@ducheng0 should be resolved in 1.17.
Feel free to reopen or open another issue in case you have questions.
