### ISSUE TITLE
ReactNativeWebView.onMessage is not a function

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#12726]
# Bug Report
When browsing dapp `swap.eros.fund` with android 10+, everything works fine, but with android 8.1, you encounter the problem shown in the title

### Reproduction

1) using Android Studio -> AVD Manager to create a virtual device, when creating, select "Phone" from Category, select "Pixel XL" from name list, click "next", select "Oreo" which api level is 27, ABI is x86, and most important the target should use Android 8.1(Google APIs)
2) install status app(version 1.16) into the newly created device above
3) open status login and navigate to browser tab, type `swap.eros.fund` in the address bar and go
4) you will see a screenshot like this one 
![1](https://user-images.githubusercontent.com/12406719/138064195-0e0683bc-a0d0-4740-a747-6921fc7435b1.png)
5) open chrome, type `chrome://inspect`, u will see like this
![2](https://user-images.githubusercontent.com/12406719/138064747-3dd40db6-b80b-4557-85b0-022467ce7edf.png)
6) click inspect and navigate to `Console`
7) click the button in the red box as shown in the picture `... `
![3](https://user-images.githubusercontent.com/12406719/138065383-74f9d1ff-ddb5-4450-91eb-52fdf0ced9c8.png)
8) Connect wallet ![4](https://user-images.githubusercontent.com/12406719/138065696-f6ef779b-d918-4766-80b4-35caea5fb5ab.png)
9) choose Allow  
![5](https://user-images.githubusercontent.com/12406719/138066049-4b7cfc61-0b59-406b-b05a-18aa183f0217.png)
10) back to DevTools
![6](https://user-images.githubusercontent.com/12406719/138066204-0a609305-f983-4a76-a741-ad20dc952b3b.png)

### Additional Information
a work solution is: edit package.json, and change dependency "react-native-webview" to "git+https://github.com/status-im/react-native-webview.git#js_injection_before_load", then won't have this issue on android 8.1 , i have checked `https://github.com/status-im/react-native-webview` , looks like the latest tag or branch master didn't merge branch `js_injection_before_load`, why?

- Status version: 1.16 
- Operating System: Android

**Comment by churik** [comment]
Could noramally connect wallet on Pixel 2, Android8 (real remote device)

https://user-images.githubusercontent.com/4557972/138267559-630a3d00-be80-4fe5-bcf5-203f635023c4.mp4

**Comment by qfrank** [comment]
Hi @churik , have u tried this type of simulator: Pixel XL, Oreo, api level 27, x86 Android 8.1(Google APIs)?

**Comment by flexsurfer** [comment]
>  looks like the latest tag or branch master didn't merge branch js_injection_before_load, why?

cc @bitgamma

**Comment by bitgamma** [comment]
when I updated the dependency, I based off https://github.com/status-im/react-native-webview/tree/v10.9.2 (the version we were using before) which also didn't include the commits from `js_injection_before_load`. I'll see if those commits can be applied as-is to the new version

**Comment by bitgamma** [comment]
the commits cannot be applied as is and also it looks like at least part of that code is already part of upstream so further analysis of the underlying error is needed to apply a fix

**Comment by flexsurfer** [comment]
thanks @bitgamma
