### ISSUE TITLE
Issue using app.ens in browser

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#12744]
# Bug Report

## Problem 

When trying to buy an ENS name from the ENS, the "connect wallet" button doesn't work if the app was previously authorized.

#### Expected behavior

1. Open app.ens.domains in status browser
2. Click "connect wallet " in ens app
3. Authorize dapp to connect to wallet
4. Close tab, close status app
4. Reopen ens app 
1. Click "connect wallet" in ens app
2. Wallet is connected 

#### Actual behavior

At last step, nothing happens.

#### work around

Remove authorisation in status wallet for ens app, go through authorisation flow again. 

### Additional Information

- Status version: 1.1.16
- Operating System: Android

**Comment by flexsurfer** [comment]
thanks for reporting, fixed

**Comment by D4nte** [comment]
The issue still occurs with 1.17.0

**Comment by D4nte** [comment]
Actually it's worst now because before I could remove authorisation and add again and it'll be fine.
Whereas now, if I remove the authorization, click "connect" in ENS app and authorize again, ENS still does not see the wallet as connected (nothing happen when clicking "connect" again after authorization flow).

**Comment by churik** [comment]
right, as issue will be fixed in 1.18
https://github.com/status-im/status-react/commit/77e593572fdb16dfb557cfa31a2ac290eff3cf22 is included in 1.18, not in 1.17
Please, reopen if it will be relevant in 1.18, thanks!
