### ISSUE TITLE
Please add JSON parsing for bot responses

### ISSUE THREAD

**Issue by spdz** [status-im/status-react#1274]
### User Story

As a developer, I want to parse a json string returned from an api so that present that information to the user of the bot.

### Description

Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Like the /location call, but instead of returning a static image created by the google API, the api's that will be returning will return a json string.  We need a way to parse and format that information in a meaningful way. 

#### Expected behavior
User taps and sends a request:
/weather london,uk
or
/anrgyclouds london,uk

The bot.js goes to openweathermap.org to request the weather info and returns a json string with the following for example:
`{"coord":{"lon":-0.13,"lat":51.51},"weather":[{"id":300,"main":"Drizzle","description":"light intensity drizzle","icon":"09d"}],"base":"stations","main":{"temp":280.32,"pressure":1012,"humidity":81,"temp_min":279.15,"temp_max":281.15},"visibility":10000,"wind":{"speed":4.1,"deg":80},"clouds":{"all":90},"dt":1485789600,"sys":{"type":1,"id":5091,"message":0.0103,"country":"GB","sunrise":1485762037,"sunset":1485794875},"id":2643743,"name":"London","cod":200}`

We would need to parse weather.main, and main.temp to present the current temp and weather to the user. [note: this response is in K]

#### Actual behavior
I don't really know how to parse it currently as it is not implemented. Possibly use JSON.parse()

**Comment by rasom** [comment]
@spdz `JSON.parse()` works as expected in otto vm, so you can use it for parsing. When I first read your message in slack i was under impression that you are asking for some UI component that will do JSON pretty print in app.
