### ISSUE TITLE
Annoying popup

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12763]
https://user-images.githubusercontent.com/41779817/139394682-4bdce992-bbb7-4582-a9a9-6657b3ea1f5f.mp4

In addition the popup message is confusing "...Status > Face ID...". Where shall I enable it, shall I enable "Lock app with face ID" option too if this is the first log in?
 
Expected: appears only once or can be disabled 

"Lock app with face ID" is disabled 

- Status version: 1.17
- Operating System: iOS 15.1

**Comment by rapidddenis** [comment]
**@churik** 

> Yes, you need to enable Face ID for the log in into application or use a password, and you can't disable it for security reasons.

It is disabled and never used but the popup coninues

**Comment by churik** [comment]
> In addition the popup message is confusing "...Status > Face ID...". Where shall I enable it, shall I enable "Lock app with face ID" option too if this is the first log in?

To enable authentication without a password you need to click on 'Cancel' in the popup and then log in with the password.
Then after relaunching the app, it will not require a password anymore for login.

> It is disabled and never used but the popup continues

If you log out from profile, even if you checked "Save password" , you need to login again.
I'm not sure what are your expectations from "Save password" functionality if you enable it

**Comment by rapidddenis** [comment]
It’s not a big deal, but in some rare cases when you log out quite often this popup becomes annoying

**Comment by churik** [comment]
it is disabled by design when you log out manually.
So you can login with a saved password until manual logout.
Hopefully, it is clearer now why it is working this way.
Full discussion around feature is here: https://github.com/status-im/status-react/pull/8127

Feel free to reopen or open new request if you have further questions
