### ISSUE TITLE
Privacy settings for online indicator

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12767]
As a user I want at least to configure who can see my online indicator: everyone or contacts

**Comment by flexsurfer** [comment]
cc @Parveshdhull

**Comment by Parveshdhull** [comment]
The requested feature is not possible with the current implementation. 
Either you can enable broadcasting your status updates by selecting `Automatic/Always online`, or you can disable broadcasting by selecting `Inactive`
If enabled, it will broadcast status updates to its contact topic, and anyone can subscribe to that topic. (contact or not)

**Comment by rapidddenis** [comment]
Can you encrypt status, so the pining is done but exact values are known only to contacts?
You can broadcast on different topic known only to contacts and manage it accordingly when contacts are addeded/deleted/blocked?

**Comment by Parveshdhull** [comment]
cc @richard-ramos

**Comment by rapidddenis** [comment]
When you run the app it relays and sends messages, node itself can be tracked and considered active but your online indicator, activities & info are disclosed only to contacts the same way group chat messages can be found and decrypted only by participants, group chat for all contacts by default

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
