### ISSUE TITLE
Text elements position mismatch

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12766]
![photo_2021-10-29_13-08-20](https://user-images.githubusercontent.com/41779817/139417352-558f1b64-38c4-4ccc-8dfb-e99dcea8b20a.jpg)
![photo_2021-10-29_13-09-20](https://user-images.githubusercontent.com/41779817/139417355-bf3524eb-e98f-4b5e-9f89-899fcfa3297b.jpg)
![photo_2021-10-29_13-09-27](https://user-images.githubusercontent.com/41779817/139417356-271d18f2-c739-4254-bf1d-b5a4e1e97242.jpg)

### Additional Information

- Status version: 1.17 
- Operating System: iOS 15.1

**Comment by Parveshdhull** [comment]
fixed in https://github.com/status-im/status-react/pull/12594
