### ISSUE TITLE
App freezes after keycard connection timeout on IOS 15

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12762]
https://user-images.githubusercontent.com/41779817/139391326-a81b3223-afc0-4b64-8b74-0182302e8ae6.mp4

- Status version: 1.17 
- Operating System: iOS 15.1

**Comment by churik** [comment]
Couldn't reproduce. After timeout bottom sheet is closed and I can tap 'Begin setup' again.
@qoqobolo would you mind to try when you have a time?

**Comment by rapidddenis** [comment]
retried, 3 of 3 times app freezes

**Comment by churik** [comment]
It is IOS-15 specific issue, reproduced.
Thank you for reporting @rapidddenis !

**Comment by rapidddenis** [comment]
iPadOS 15.1
https://user-images.githubusercontent.com/41779817/139460275-93312dd5-ba84-4cc3-ae85-e73d075173fa.mov
