### ISSUE TITLE
Transaction history can't be loaded for xDai and POA networks 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12777]
# Bug Report

## Problem 
No way to see tx history on xDai or POA networks.

#### Expected behavior
Can see a tx history or user-friendly error and link to respective block explorer to check it externally.

#### Actual behavior
Endless spinner
![IMAGE 2021-11-01 17:18:24](https://user-images.githubusercontent.com/4557972/139704663-015cd3a4-9921-45c2-8f08-632c49ab607b.jpg)

### Reproduction

1) Open Status
2) Restore multiaccount
3) Change network to xDai or POA

### Additional Information

- Status version: nightly 01/11/21
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
Fixed in https://github.com/status-im/status-react/pull/12809
