### ISSUE TITLE
Stickers in the Sticker Market and chat views are not loaded sometimes

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12770]
# Bug Report

## Problem 
Sometimes stickers are partially downloaded and displayed in the Sticker Market, and sometimes cannot open the Sticker Market itself at all (an endless spinner is shown).

#### Actual behavior

https://user-images.githubusercontent.com/67952253/139454405-dd042c44-b7c6-4853-95a6-5a5039f2b672.mp4

https://user-images.githubusercontent.com/67952253/139454412-cad13294-3d09-4abf-8ef8-6a8edf71c25a.mp4

### Reproduction

1. Open Status
2. Join a public chat
3. Tap the Stickers icon to open the Sticker Market
4. Open several sticker packs

### Additional Information

- Status version: nightly 29/10
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
that's because of cf-ipfs.com has a rate limit 

```
Error 1015 Ray ID: 6a1935fdecfd58de • 2021-10-21 08:45:38 UTC
You are being rate limited
What happened?
The owner of this website (bafybeidcdfco5d6abyag5nclj2rophqfmz4gpxivxnzgm76c3ixxy3oujy.ipfs.cf-ipfs.com) has banned you temporarily from accessing this website.
```

**Comment by anastasiyaig** [comment]
i was able to reproduce it with latest develop commit eeb8db00f79e8cbdabe3d5db2cc575f27d3ae75d commit date `5 January 2022 at 21:27:51 GMT+3`

<img width="1396" alt="Screenshot 2022-01-10 at 14 18 42" src="https://user-images.githubusercontent.com/82375995/148758211-34bfebd8-28f4-4cd4-a924-b4d0c0072083.png">
<img width="1396" alt="Screenshot 2022-01-10 at 14 17 33" src="https://user-images.githubusercontent.com/82375995/148758241-1bf02d78-6e40-4504-8adf-ef15e12c1cd4.png">
