### ISSUE TITLE
Cocoapods fail to install on Darwin aarch64

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12799]
Currently when attempting to run an Nix shell for iOS it fails during `pod install` with:
```
Installing SQLCipher (3.4.2)
[!] /nix/store/399xcc4m12747gbi18xzmj3ac32py2s9-bash-interactive-5.1-p8/bin/bash -c 
set -e
./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"; make sqlite3.c

checking build system type... 
Invalid configuration `arm64-apple-darwin20.6.0': machine `arm64-apple' not recognized
configure: error: /nix/store/lcvafvjg1a9v5cbf9ghx1ync5xc20l1h-bash-4.4-p23/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed
```
[Full Log](https://gist.github.com/Jonathansoufer/d154ef228ffc060e08185685d5acfe9a)

This appears to be a known issue:

* https://github.com/sqlcipher/sqlcipher/issues/390
* https://github.com/sqlcipher/sqlcipher/issues/399

**Comment by jakubgs** [comment]
According to https://github.com/sqlcipher/sqlcipher/issues/390:

>Your output mentions Darwin 20.3.0 -- that refers to Big Sur version 11.2, can you check your macOS version? It might also help to make sure you are using the latest Xcode as well.

So we might have to look at upgrading the OS and XCode as a way to fix this.

**Comment by jakubgs** [comment]
This issue:

* https://github.com/CocoaPods/CocoaPods/issues/10349

Recommends using `arch -x86_64` command to prefix `gem` and `pod` calls:
```
arch -x86_64 pod install
```

**Comment by jakubgs** [comment]
Except this doesn't seem to work on our host:
```
admin@macm1-01.ms-eu-dublin.slave.ci:~ % arch -arch arm64 machine
arm64e

admin@macm1-01.ms-eu-dublin.slave.ci:~ % arch -arch x86_64 machine
arch: posix_spawnp: machine: Bad CPU type in executable
```

**Comment by jakubgs** [comment]
Apparently:

>Rosetta 2 enables a Mac with Apple silicon to use apps built for a Mac with an Intel processor.
https://support.apple.com/en-gb/HT211861

And it apparently needs to be installed manually:
```
softwareupdate --install-rosetta
```
https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executableh

**Comment by jakubgs** [comment]
That does help:
```
admin@macm1-01.ms-eu-dublin.slave.ci:~ % arch -arch x86_64 machine
arch: posix_spawnp: machine: Bad CPU type in executable

admin@macm1-01.ms-eu-dublin.slave.ci:~ % softwareupdate --install-rosetta 
I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
Type A and press return to agree: A
2021-11-29 15:55:41.895 softwareupdate[59123:1251710] Package Authoring Error: 071-97390: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
Install of Rosetta 2 finished successfully

admin@macm1-01.ms-eu-dublin.slave.ci:~ % arch -arch x86_64 machine       
i486
```

**Comment by jakubgs** [comment]
But running `pod install` under `arch -arch x86_64` fails:
```
[nix-shell:~/workspace/status-react_prs_ios_PR-12849]$ arch -arch x86_64 pod --version
arch: posix_spawnp: pod: Bad CPU type in executable
```
Which is because both `pod` and `gem` are script ran by Ruby provided by Nix was build for `arm64`:
```
[nix-shell:~/workspace/status-react_prs_ios_PR-12849]$ which ruby
/nix/store/30prvf10b1px4dbck5s5dinqa2g5wkzr-ruby-2.7.4/bin/ruby

[nix-shell:~/workspace/status-react_prs_ios_PR-12849]$ ruby --version
ruby 2.7.4p191 (2021-07-07) [arm64-darwin20]
```

**Comment by jakubgs** [comment]
If I clone https://github.com/sqlcipher/sqlcipher and checkout `v3.4.2` which we use I can configure and build it just fine:
```
jenkins@macm1-01.ms-eu-dublin.slave.ci:~/repos/sqlcipher % ./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999" | grep 'build system'
checking build system type... arm-apple-darwin20.6.0
configure: WARNING: Can't find Tcl configuration definitions
configure: WARNING: *** Without Tcl the regression tests cannot be executed ***
configure: WARNING: *** Consider using --with-tcl=... to define location of Tcl ***

jenkins@macm1-01.ms-eu-dublin.slave.ci:~/repos/sqlcipher % echo $?
0

jenkins@macm1-01.ms-eu-dublin.slave.ci:~/repos/sqlcipher % make sqlite3.c
tclsh8.5 /Users/jenkins/repos/sqlcipher/tool/mksqlite3c.tcl
cp tsrc/shell.c tsrc/sqlite3ext.h .
cp /Users/jenkins/repos/sqlcipher/ext/session/sqlite3session.h .
```
Which means the issue might be related to Nix shell.

**Comment by jakubgs** [comment]
And indeed, in a Nix shell it fails:
```
[nix-shell:~/repos/sqlcipher]$ ./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"
checking build system type... Invalid configuration `arm64-apple-darwin20.6.0': machine `arm64-apple' not recognized
configure: error: /nix/store/ppzr8yab3s3883skd0da5i4ylzpksk9l-bash-5.1-p8/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed
```

**Comment by jakubgs** [comment]
If I specify the build system in the command line it works fine:
```
[nix-shell:~/repos/sqlcipher]$ ./configure arm-apple-darwin20.6.0
configure: WARNING: you should use --build, --host, --target
checking build system type... arm-apple-darwin20.6.0
checking host system type... arm-apple-darwin20.6.0
checking how to print strings... printf
checking for arm-apple-darwin20.6.0-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
...
```

**Comment by jakubgs** [comment]
By adding `set -x` I can see the error comes from the `config.sub` script:
```
+ printf '%s\n' 'configure: error: /nix/store/ppzr8yab3s3883skd0da5i4ylzpksk9l-bash-5.1-p8/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed'
configure: error: /nix/store/ppzr8yab3s3883skd0da5i4ylzpksk9l-bash-5.1-p8/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed
+ as_fn_exit 1
```
https://github.com/sqlcipher/sqlcipher/blob/v3.4.2/config.sub

**Comment by jakubgs** [comment]
I can see that the `case` that checks architectures does not allow `arm64`:
```sh
	| arm-*  | armbe-* | armle-* | armeb-* | armv*-* \
```
https://github.com/sqlcipher/sqlcipher/blob/v3.4.2/config.sub#L320
```sh
			| arm  | arm[lb]e | arme[lb] | armv* \
```
https://github.com/sqlcipher/sqlcipher/blob/v4.5.0/config.sub#L1170

**Comment by jakubgs** [comment]
I see what's the difference now. In normal shell it detects `arm`:
```
jenkins@macm1-01.ms-eu-dublin.slave.ci:~/repos/sqlcipher % ./configure | grep 'build system'
checking build system type... arm-apple-darwin20.6.0
```
But within Nix it detects `arm64`:
```
[nix-shell:~/repos/sqlcipher]$ ./configure | grep 'build system'
Invalid configuration `arm64-apple-darwin20.6.0': machine `arm64-apple' not recognized
configure: error: /nix/store/ppzr8yab3s3883skd0da5i4ylzpksk9l-bash-5.1-p8/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed
checking build system type... 
```
Which explains the difference.

**Comment by jakubgs** [comment]
I've opened an issue: https://github.com/sqlcipher/sqlcipher/issues/413

**Comment by jakubgs** [comment]
I see, it calls [config.guess](https://github.com/sqlcipher/sqlcipher/blob/v3.4.2/config.guess) to figure out architecture:
```
[nix-shell:~/repos/sqlcipher]$ bash ./config.guess
arm64-apple-darwin20.6.0
```

**Comment by jakubgs** [comment]
And that comes from `uname -p`:
```sh
	UNAME_PROCESSOR=`uname -p` || UNAME_PROCESSOR=unknown
	case $UNAME_PROCESSOR in
	    unknown) UNAME_PROCESSOR=powerpc ;;
	esac
	echo ${UNAME_PROCESSOR}-apple-darwin${UNAME_RELEASE}
	exit ;;
```
https://github.com/sqlcipher/sqlcipher/blob/v3.4.2/config.guess#L1253-L1258

**Comment by jakubgs** [comment]
What I do not get is why the system shell appears as `arm`:
```
admin@macm1-01.ms-eu-dublin.slave.ci:~ % uname -p
arm
admin@macm1-01.ms-eu-dublin.slave.ci:~ % uname -m
arm64
admin@macm1-01.ms-eu-dublin.slave.ci:~ % lipo -info /bin/bash            
Architectures in the fat file: /bin/bash are: x86_64 arm64e 
admin@macm1-01.ms-eu-dublin.slave.ci:~ % lipo -info /bin/zsh 
Architectures in the fat file: /bin/zsh are: x86_64 arm64e 
```
And the Nix one appears as `arm64`:
```
[nix-shell:~/repos/sqlcipher]$ uname -p
arm64
[nix-shell:~/repos/sqlcipher]$ uname -m
arm64
[nix-shell:~/repos/sqlcipher]$ lipo -info $(which bash)
Non-fat file: /nix/store/gpf2hyxynkkijvqk2ijlw25jnb8q8fk4-bash-interactive-5.1-p8/bin/bash is architecture: arm64
```

**Comment by jakubgs** [comment]
According to this issue this is normal:

>I can reproduce what you are seeing on our Macs on `11.2.3` and `11.3.1` - we get `arm64` / `arm` / `arm64` reliably back despite different shells and homebrew (or lack thereof) setups on each.

https://apple.stackexchange.com/questions/420452/running-uname-m-gives-x86-64-on-m1-mac-mini

**Comment by jakubgs** [comment]
According to `autoconf` documentation the `config.sub` and `config.guess` files can be fetched from their repo:
```sh
wget -O config.guess 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
wget -O config.sub 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'
```
https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html

**Comment by jakubgs** [comment]
If I test their current `config.guess` script I get this:
```
[nix-shell:~/repos/sqlcipher]$ bash ./config.guess
aarch64-apple-darwin20.6.0
```
And the same outside of Nix shell:
```
jenkins@macm1-01.ms-eu-dublin.slave.ci:~/repos/sqlcipher % bash ./config.guess
aarch64-apple-darwin20.6.0
```
So updating `config.guess` in SQLCipher definitely seems like an option.

**Comment by jakubgs** [comment]
And it appears that most recent version of `config.guess` uses `uname -m` instead of `uname -p`:
```sh
    arm64:Darwin:*:*)
        GUESS=aarch64-apple-darwin$UNAME_RELEASE
        ;;
```
https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob;f=config.guess;h=e94095c5fbe89c77bfb99903f66223e4ef856e86;hb=2593751ef276497e312d7c4ce7fd049614c7bf80#l1346

This was fixed in: https://git.savannah.gnu.org/gitweb/?p=config.git;a=commit;h=2593751ef276497e312d7c4ce7fd049614c7bf80

**Comment by jakubgs** [comment]
Thanks to suggestion in [the Nixpkgs issue](https://github.com/NixOS/nixpkgs/issues/147914#issuecomment-986297967) this issue might be specific to [GNU Coreutils]() and not Nix shell:
```
 > uname -m
arm64
 > uname -p 
arm
 > /opt/homebrew//Cellar/coreutils/9.0/bin/guname -m
arm64
 > /opt/homebrew//Cellar/coreutils/9.0/bin/guname -p
arm64
```
Since GNU Coreutils from homebrew provides `uname` that acts the same as the on from Nix.

**Comment by jakubgs** [comment]
As a first step I've opened a new thread on SQLite forum to report this issue and ask about updating the `config.*` scripts:
https://www.sqlite.org/forum/forumpost/f0875bea54

**Comment by jakubgs** [comment]
I also wrote an email to the `bug-coreutils@gnu.org` mailing lists:
https://lists.gnu.org/archive/html/bug-coreutils/2021-12/msg00008.html

**Comment by jakubgs** [comment]
Looks like I managed to get some help from Paul Eggert and get a fix into GNU Coreutils:
https://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=e3d1ff04370b3e090e4cfeb8f6cc4a63590a516f

Now, when this is released and arrives in `nixpkgs` is anybodys guess. Nixpkgs is on `9.0` which came out two months ago, so it's not unlikely we might see it there in January.

**Comment by jakubgs** [comment]
Looks like a new 9.1 release of GNU Coreutils is out: https://git.savannah.gnu.org/cgit/coreutils.git/tag/?h=v9.1

There's already a PR to update it in `nixpkgs`:

* https://github.com/NixOS/nixpkgs/pull/169046

**Comment by cammellos** [comment]
I believe this has been fixed? Closing for now @jakubgs let me know if there's more work to be done
