### ISSUE TITLE
Bot command param suggestions are only shown for the first param

### ISSUE THREAD

**Issue by morelazers** [status-im/status-react#1279]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to show users suggestions for each parameter in a series so that they can make more informed decisions.

### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When adding multiple sequential params for a command, only the first param's `suggestions` prop is ever shown.

#### Expected behavior
All params show their own suggestions markup.

#### Actual behavior
Suggestion markup is only shown while the user is selecting the first parameter.

### Reproduction
Add a bot command with at least two sequential params, and specify suggestions markup for both.

### Additional Information
* Status version: 0.9.8-4-g024cf6d6+
* Operating System: Android

#### Logs

No relevant logs AFAICT

**Comment by rasom** [comment]
@morelazers could you please provide some code sample?

**Comment by morelazers** [comment]
@rasom 
```
function suggestionsFunction(number) {
  return {markup: status.components.view({}, [status.components.text({}, 'Suggestion ' + number)])}
}

var testCommand = {
  name: 'test',
  title: 'Test',
  sequentialParams: true,
  params: [{
    name: 'one',
    type: status.types.TEXT,
    suggestions: suggestionsFunction(1)
  }, {
    name: 'two',
    type: status.types.NUMBER,
    suggestions: suggestionsFunction(2)
  }]
}

status.command(testCommand)
status.response(testCommand)
```

**Comment by flexsurfer** [comment]
@morelazers `sequentialParams: true`, means only one param with spaces, if you want use several params do not use `sequentialParams: true`

**Comment by morelazers** [comment]
Hmm - I get opposite results @flexsurfer, for me `sequentialParams: true` means that we get two separate inputs, if I omit the prop or turn it to false, then we must enter all the params on the same line

**Comment by morelazers** [comment]
That's also what it says in the docs here: http://docs.status.im/?js#status-command

**Comment by flexsurfer** [comment]
yes, that's right, i'll look on this, thank you

**Comment by yenda** [comment]
Command have been rewritten
