### ISSUE TITLE
iOS builds on MacOS with M1 CPU

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12798]
Meta-issue for the general effort of getting iOS builds to work correctly on M1 machines(@Jonathansoufer has one).

* https://github.com/status-im/status-react/issues/12794
* https://github.com/status-im/status-react/issues/12799

There's also been a request by @stefantalpalaru for an M1 CI host for Nimbus builds.

**Comment by cammellos** [comment]
Closing as both issues seems to have been addressed
