### ISSUE TITLE
Sometimes sendMessage calls from a command's `handler` are shown before the command's `preview`

### ISSUE THREAD

**Issue by morelazers** [status-im/status-react#1280]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to show the user that they issued the command before the result so that the action-consequence sequence is clearer.

### Description

*Type*: Bug

*Summary*: When issuing a `status.sendMessage` from a `handler` function, sometimes the message appears in the chat history _before_ the command's preview is shown. To the user, it looks like they issued the command after the result. Adding a busy-wait in the `handler` function doesn't solve the problem.

#### Expected behavior
The command's `preview` is shown first, then any messages from the `handler`.

#### Actual behavior
Sometimes it shows in the desired order, sometimes it doesn't. Seemingly at random.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Create a command with both a `preview` and `handler` function
- Call `status.sendMessage` from the `handler`
- Observe the results of multiple command issuances
- See that sometimes the message appears before the command's preview

### Additional Information
* Status version: 0.9.8-4-g024cf6d6+
* Operating System: Android

**Comment by rasom** [comment]
`status.sendMessage` immediately sends signal to React Native app form Otto vm, but command appears in chat only when command's handler returns results. That's way message that is sent via `status.sendMessage` it can appear before command.

I have created a branch which allows to to send the message by returning object with `text-message` prop (like here https://github.com/status-im/status-react/blob/develop/bots/demo_bot/bot.js#L88) https://github.com/rasom/status-react/commit/08b7fafbe977bc4c8844aed160cb74fe24f0f620 .

@morelazers as we have locked `develop` branch for time being, the only way to get use of this during the hackathon is to build app locally.
