### ISSUE TITLE
Network balance is not updated after sending transaction when network symbol is not ETH

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12818]
# Bug Report

## Problem 
Reproduced on BSC mainnet, can be tested on BSC testnetwork after merging https://github.com/status-im/status-react/pull/12810

**Expected result:**
will be updated when tx gets confirmed

**Actual result:**
no update until relogin or custom scan tokens

### Reproduction

1) create new multiaccount
2) add BSC testnet (https://data-seed-prebsc-1-s1.binance.org:8545/ , 97 from [here](https://docs.binance.org/smart-chain/developer/rpc.html)
3) get Testnet Fund: https://testnet.binance.org/faucet-smart
4) try to send it to any address and pay attention to balance update

### Additional Information

- Status version: nightly 15/11/2021
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
balance is not updated at all, even with pull to refresh, user has to relogin
it happens for faucet transactions as well

**Comment by rasom** [comment]
History fetching is broken for those networks and that cause the problem with balances.

The issue on BSC testnet is that we can't fetch `eth_getLogs` for a range bigger than 5000 blocks, and that was a reason for an endless failing loop on status-go side. Although it is pretty simple to fix, later I figured later it wouldn't work on a main BSC network as it doesn't provide a historical data even for last 128 blocks (as it usually works on a regular ethereum node). That means we can't use our tx history scanning algorithm, also we will not be able to check recent history using it. 

The only option we are left with is to show transactions which are sent from Status (or to use some third party api but no ethereum RPC) and provide a link to https://bscscan.com.
