### ISSUE TITLE
Network fee is not calculated on POA network and POA network is merged with xDai

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12813]
# Bug Report

## Problem 
1) Network fee is not calculated 
![IMAGE 2021-11-12 13:41:35](https://user-images.githubusercontent.com/4557972/141468857-4ed9c821-e70a-4b62-85f2-b911292c6f1f.jpg)
2) Basically, Poa is merged with xDai(https://www.poa.network/how-to-swap) so don't think we need to support it anymore

Not sure how better to make transition from our side
Need your opinions @cammellos @flexsurfer

**Comment by flexsurfer** [comment]
i think its related to https://github.com/status-im/status-react/issues/12819

**Comment by rasom** [comment]
@churik can you please check whether it is already fixed by https://github.com/status-im/status-react/pull/12845 ?

**Comment by churik** [comment]
@rasom yes, network fee is calculated. can close the issue, however maybe we need to remove it, as it is merging with xDai now (https://www.poa.network/)?

**Comment by rasom** [comment]
@churik 
> The network will continue to operate in a staging capacity for the xDai chain without emissions or rewards.

well we can either remove it or move to testnets section

**Comment by guylouis** [comment]
@rasom I discussed it with @John-44 : PoA can be removed form the list of supported networks
