### ISSUE TITLE
Validation error in case of not enough balance for network fee is not clear

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12816]
# Bug Report

## Problem 
When a user doesn't have enough ETH to cover the default network fee, instead of `Not enough ETH for transaction` gas limit is not set  (when open form no default value is set) and when tapping tosee more info, `Gas required exceeds allowance` error is shown.
So it is not lear how much ETH user will need to cover tx fee for particular transaction.

#### Expected behavior
1) Default gas limit is set
2) Error is more user-friendly (cc @hesterbruikman )

#### Actual behavior

![IMAGE 2021-11-15 10:21:51](https://user-images.githubusercontent.com/4557972/141755576-477bbbc6-09b0-4b38-baeb-7293b9133702.jpg)
![IMAGE 2021-11-15 10:21:59](https://user-images.githubusercontent.com/4557972/141755603-fb663c06-2c53-4e5c-a4a5-df829b83ce7e.jpg)

### Reproduction

1) Restore multiaccount with small amount of ETH (not enough for default fee)
2) Try to send transaction 
Fore testing account ping me in dm.

### Additional Information

- Status version: nightly 15/11/21
- Operating System: Android, iOS

**Comment by carlfairclough** [comment]
The first screenshot is related to the tx signing/review view which is currently being worked on, I will make sure to take this into account.

The second screenshot shouldn't be happening, but does point to another issue:
We don't have an error state to indicate that the max overall gas fee exceeds the available network balance:
https://www.figma.com/file/XK7vrp3pZdQ5gqQVJ7Pqgz/EIP-1559-Presentation?node-id=110%3A674
I will update this after the tx signing/review view is ready.

**Comment by flexsurfer** [comment]
this is what we get from infura
```
:code-32000
:message"gas required exceeds allowance (1429)"
```

we can't set default gas limit, because there is no default one, and we can't calculate it, so we have to show an error, also we can't show different messages , because -32000 code is general for many errors, we could parse string with message, but I'm not sure it's a right way

**Comment by rasom** [comment]
I'm not sure there is any kind of a bug here. A user will not be able to send a transaction, we can just disable an option to open that custom fee sheet as it won't make any difference.

**Comment by flexsurfer** [comment]
if we still want to change error message in this task, we can parse error message from infura and replace by our

**Comment by churik** [comment]
the issue is that validation error, in this case, is not really clear here

>  we can just disable an option to open that custom fee sheet as it won't make any difference.

And this will be a solution to prevent users from setting a custom gas limit, which can't be enough to cover tx fee and tx likely fail.
My vote is for disabling  custom fee sheet  for this case

Would be awesome to have your opinion @hesterbruikman
