### ISSUE TITLE
Network fee is not calculated on xDai

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12819]
# Bug Report

## Problem 
![IMAGE 2021-11-16 11:06:08](https://user-images.githubusercontent.com/4557972/141965104-0e8e5443-e666-4de3-8180-d5c3b4c511fe.jpg)
It was working 12/11/2021 (had transaction that I made from status app), but currently can't send any transaction due to endless spinner in Network fee

#### Expected behavior
network fee is calculated 

### Reproduction

1) Open Status, restore multiaccount with funds on xDai
2) Try to send some xDai

### Additional Information

- Status version: release 1.17 (after 12.11.2021) 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
[status_logs.zip](https://github.com/status-im/status-react/files/7545392/status_logs.zip)

**Comment by flexsurfer** [comment]
`WARN [status-im.ethereum.json-rpc:261] - :json-rpc/error eth_feeHistory :error {:code -32602, :message "Parameter count mismatch."} :params [101 "latest" nil]`
