### ISSUE TITLE
Unread indicator is not reset for mentions

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12821]
# Bug Report

## Problem 
All received mentions are counted as new by the unread message counter, even if they were read.
In other words, if the user receives a mention, opens the chat to read it, returns to the home screen, and receives another mention, the count `2` will be shown, although only one mention was received. 
Also, all mention messages are displayed as new after relogin.

#### Expected behavior
Refresh the unread message counter when reading a mention message; display `1` when one new mention is received. 

#### Actual behavior

https://user-images.githubusercontent.com/67952253/141995204-499be66a-0c63-4251-9408-d3fb0101df01.MP4

### Reproduction

1. UserA and UserB join the same public chat (works for any type of chat)
2. UserA sends a message and returns to the home screen
3. UserB sends a message mentioning UserA
4. UserA opens the public chat and returns to the home screen
5. UserB sends another mention of UserA
6. UserA checks the unread counter on the public chat

### Additional Information

- Status version: nightly 16/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
seems like the reason in status-go in this change https://github.com/status-im/status-go/pull/2405/files#diff-9c10d1fdc9bdc5ba03f06708c5860c31fdde851efed63c172d6900c887a8481aR1257
