### ISSUE TITLE
Nix 2.4 issues with git tags

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12832]
It appears that newest `2.4` release of Nix has some weird issues with Git tags:
```
 > make run-clojure 
yarn shadow-cljs watch mobile
Configuring Nix shell for target 'clojure'...
fatal: couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
fatal: couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128

       … while fetching the input 'git+https://github.com/tbenr/react-native-audio-toolkit.git?ref=v2.0.3-status-v6&rev=7ae9055cf6169b30f5089bda7bfcfc1c40a715e5'

       … while evaluating the attribute 'buildCommand' of the derivation 'react-native-audio-toolkit.git'
```

**Comment by jakubgs** [comment]
This appears to be a known issue:

* https://github.com/NixOS/nix/issues/5291
* https://github.com/NixOS/nix/issues/5128
* https://github.com/NixOS/nix/issues/4711
* https://github.com/NixOS/nix/issues/4456
* https://github.com/NixOS/nixpkgs/pull/141005

**Comment by jakubgs** [comment]
I checked `2.5.1` but the same issue appears:
```
checking for references to /build/ in /nix/store/nsmg4iyqkndfg0llfzgz24gcbfir7jzq-yarn2nix-1.0.0...
distPhase
yarn pack v1.22.17
building '/nix/store/h3d6dg58b41lcpk85v7kr8py5akd454b-yarn.nix.drv'...
fatal: couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
removed '/tmp/tmp-status-react-59d3e3e46/tmp.Td1Psq2Dz2'
make: *** [Makefile:196: release-android] Error 1
```

**Comment by jakubgs** [comment]
Actually, there might be a way to get around this by prefixing tags with `refs/tags/` as in this fix:
https://github.com/hercules-ci/docs.hercules-ci.com/commit/b8a3e391fb1ee5f2896fd692f2c2ed28e85c0f7d

**Comment by jakubgs** [comment]
It builds, but will require fixes in `packages-check-bot`:
https://github.com/status-im/packages-check-bot/blob/dffdedb9/src/dependency-check-json.ts#L77-L79

**Comment by ZainAliSyed24** [comment]
@jakubgs  

I am also facing exactly same issue with version 2.6.0 , 

Can you please have get any solution for this , Is this solution merge ?

**Comment by cammellos** [comment]
@ZainAliSyed24 you need to uninstall `2.6.0` and use the version that is installed through the script, ping me on our discord if you need some help (@cammellos )

**Comment by cammellos** [comment]
To install, follow this guide if you are on catalina https://github.com/status-im/status-react/blob/develop/nix/KNOWN_ISSUES.md#macos-1015-catalina

**Comment by ZainAliSyed24** [comment]
@cammellos  Thanks let me uninstall and can you please send me message at discord if possible Syed Zain Ali#1534

**Comment by Guolanlan** [comment]
macOS  Monterey,But this ....... 
Andy:status-react guolanlan$ make run-clojure
yarn shadow-cljs watch mobile
Configuring Nix shell for target 'clojure'...
fatal: Couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
fatal: Couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128

       … while fetching the input 'git+https://github.com/tbenr/react-native-audio-toolkit.git?ref=v2.0.3-status-v6&rev=7ae9055cf6169b30f5089bda7bfcfc1c40a715e5'

       … while evaluating the attribute 'buildCommand' of the derivation 'react-native-audio-toolkit.git'

       at /nix/store/4aynlbs95bakwhwqsw5sjs7g5d0jxy5x-nixpkgs-source/pkgs/stdenv/generic/make-derivation.nix:205:7:

          204|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          205|       name =
             |       ^
          206|         let

       … while evaluating 'escapeShellArg'

       at /nix/store/4aynlbs95bakwhwqsw5sjs7g5d0jxy5x-nixpkgs-source/lib/strings.nix:318:20:

          317|   */
          318|   escapeShellArg = arg: "'${replaceStrings ["'"] ["'\\''"] (toString arg)}'";
             |                    ^
          319|

       … from call site

**Comment by Guolanlan** [comment]
Nix  Uninstalled and reinstalled，Version 2.6.1. but still not,why ???

**Comment by jakubgs** [comment]
Are you asking why the git tag issue hasn't been fixed in any of the Nix versions after 2.4?

Not really a question for us. More for the Nix developers.

**Comment by Guolanlan** [comment]
Then I  “make run clojure”. It didn't compile successfully. Isn't it your problem? Is it Nix's problem?? How can I compile IOS status without this?

**Comment by cammellos** [comment]
@Guolanlan you need to completely uninstall nix and run `make run-clojure`, it will install the right version of nix for you, nix should not be installed manually.
Here's a guide to uninstall nix completely (if you are on one of those macs https://gist.github.com/chriselsner/3ebe962a4c4bd1f14d39897fc5619732 )
