### ISSUE TITLE
Extra characters are inserted while typing in Ethlance DApp (on google and samsung keyboards)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1284]
### Description

*Type*: Bug

*Summary*: Previously typed characters are automatically inserted while user is typing in most of input fields of Ethlance DApp. It happens both with Google and Samsung keyboard.
![screenshot_20170607-175715](https://user-images.githubusercontent.com/6584810/26885414-3e63e340-4bab-11e7-949f-1e68b1b737fc.png)

#### Expected behavior
Field shows what was typed by the user. No extra words/characters are inserted. When user deletes part of the text then the remaining text is not modified.
#### Actual behavior
While user types some text there are extra letters auto-inserted. When user deletes text then first characters of the remaining text are duplicated.

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/8149726/sessions/34/?accessToken=IbTkbmIOJYZqSywCL3rWEsL43V8
- Open Status
- Open DApp Ethlance if on testnet or use https://ethlance.com/ is on mainnet
- Tap on "become freelancer"
- in "Your Name" field start typing Alexander. Then delete characters one by one.

### Additional Information
* Status version: 0.9.8
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

**Comment by rasom** [comment]
Most likely that's Ethlance's bug.

**Comment by annadanchenko** [comment]
TestFairy session with logcat and video: https://app.testfairy.com/projects/4803622-status/builds/7912666/sessions/68/?accessToken=8m//5iGnEjZThGDbcCnxk7TVh7w

**Comment by annadanchenko** [comment]
TF session on nightly build for Apr 22 (Android 8.1.0, real Pixel XL) https://app.testfairy.com/projects/4803622-status/builds/8149726/sessions/34/?accessToken=IbTkbmIOJYZqSywCL3rWEsL43V8

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8149726/sessions/34/?accessToken=IbTkbmIOJYZqSywCL3rWEsL43V8">TestFairy: Status 0.9.16-30-gf60025b8+ (2457) @34</a></strong></div></blockquote>

**Comment by jeluard** [comment]
@annadanchenko Just tried on both android and iOS and can't reproduce. Do you mind re testing?

**Comment by annadanchenko** [comment]
@jeluard yes it's possible to reproduce on nightly build May 18: when typing name try to delete and type it again, here is fresh TF session (from 00:36) https://app.testfairy.com/projects/4803622-status/builds/8311330/sessions/85/?accessToken=tOpoh5-0yISGNe7LPjetkTuQwEE

tried on real Pixel XL, Android 8.1.0

**Comment by annadanchenko** [comment]
I also tried once more time after app was closed and run again, in this case extra characters were added right when I've started typing, so no delete was necessary to get the bug: https://app.testfairy.com/projects/4803622-status/builds/8311330/sessions/87/?accessToken=hgKb2LG6Kr6CfgUqvWjQzuGLwRA

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8311330/sessions/87/?accessToken=hgKb2LG6Kr6CfgUqvWjQzuGLwRA">TestFairy: Status build-6002+ (6002) @87</a></strong></div></blockquote>
