### ISSUE TITLE
can't connect 1nch dapp on optimism  (chain ID doesn't match)

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12859]
**Reproduction:** 
- switch RPC to 
RPC URL: https://mainnet.optimism.io
Chain ID: 10
as specified here: https://community.optimism.io/docs/infra/networks.html
- go to app.1nch.io
- try to connect wallet 
- you get the following error: "App network (optimism) doesn't match to network selected in wallet (network with id:16)"

The same sequence works with metamask

**Comment by flexsurfer** [comment]
fixed in the latest nightly, will be available in the next release
