### ISSUE TITLE
Load images from an https server

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12855]
For performance reasons, we should load images from an https server run locally, instead of passing them through the bridge.

The issue is to automate the creation on certificates and making sure that they are trusted.

On IOS we can follow: 

https://developer.apple.com/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication

while on Android we could use https://stackoverflow.com/a/57046889/13685841 , but it might require changing fast-image library.

The status-go PR is here https://github.com/status-im/status-go/pull/2418 , I can update it to use SSL, @flexsurfer has done already some work here https://github.com/status-im/status-react/pull/12780/files (changing in the frontend are minimal, other than accepting the certificate).

**Comment by bitgamma** [comment]
on Android, there is also this method https://developer.android.com/training/articles/security-config#TrustingAdditionalCas
