### ISSUE TITLE
[ANDROID] Changing screen orientation results in breaking images / layout 

### ISSUE THREAD

**Issue by pburykh** [status-im/status-react#12858]
**STR:** 

1. Download latest build from PlayMarket
2. Start the app
3. On onboarding slides change screen orientation from portrait to landscape mode and then back to portait
4. Pay attention at the image's size of onboarding slides

**Actual result:** images remained small after changing screen mode from landscape to portrait 

https://user-images.githubusercontent.com/73826761/143905945-706f8003-f369-46ef-a59f-ac8c2bdf1916.mp4

**Expected result:** 

2 options: 
1. Disable possibility to change screen orientation while using the app
OR
2. Support layout transformation in case of changing the layout.   

- Status version: 1.17.0
- Operating System: Android 11
- Device: Samsung Galaxy A22 

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
thanks @pburykh  , @churik look like regression?

**Comment by flexsurfer** [comment]
related https://github.com/wix/react-native-navigation/issues/7050

**Comment by churik** [comment]
@flexsurfer yes, it is regression.
Confirmed on Android 10 (Xiaomi Mi Note9)
