### ISSUE TITLE
Text on the "Privacy policy" screen is not displayed properly

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12860]
# Bug Report

## Problem 

Rendering of the text on the "Privacy Policy" screen is broken in some places.

https://user-images.githubusercontent.com/67952253/144029119-2226df85-cc7a-4deb-a14c-ce3b80237629.MP4

### Reproduction

1. Open Status
2. Profile > About > Privacy policy
3. Scroll down

### Additional Information

- Status version: nightly 30/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
cc @jakubgs not sure if this is the correct repo to report this. Please move it if you know the better place.
Thanks!

**Comment by jakubgs** [comment]
Looks fine for me in both the app and Brave browser on Android.

|||
|-|-|
|![image](https://user-images.githubusercontent.com/2212681/144043580-e169e670-b3ec-45ef-a36b-8323cc496f76.png)|![image](https://user-images.githubusercontent.com/2212681/144043690-94181532-0e8e-4f42-bcb1-3d2999f9750d.png)|

**Comment by jakubgs** [comment]
The site repo is: https://github.com/status-im/status.im

**Comment by qoqobolo** [comment]
@jakubgs hmm looks fine for now too. Close this one.
Anyway, thanks for the link, and sorry for bothering you!
