### ISSUE TITLE
Can't finish multiaccount creation if keycard onboarding was interrupted on back up recovery phrase

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12876]
# Bug Report

## Problem 
Blocker for e2e  5742 `test_keycard_interruption_creating_onboarding_flow`
Appeared on nightly 16/11/2021
App stuck on `Confirm the passcode` stage, connect card screen doesn't  appear anymore.

#### Expected behavior
can finish multiaccount creation 

#### Actual behavior
1. Can't connect a keycard if stays on the same flow (NFC reader can't connect a keycard)
2. If tap on background and back - can connect, but app stuck
![IMAGE 2021-12-02 17:45:08](https://user-images.githubusercontent.com/4557972/144465553-928081ec-d55b-46ae-8864-0cbdb9db6c25.jpg)

### Reproduction

1) Open Status
2) Start creating multiaccount > choose keycard > begin setup > confirm passcode 2 times
3) On "Back up seed prase" tap Confirm > YES 
4) on screen "Confirm seed phrase" tap Cancel, On "Back up seed prase" tap Cancel and try to finish the process

### Additional Information

- Status version: nightly from 16/11/2021
- Operating System: Android, iOS

Logs (e2e): [test_keycard_interruption_creating_onboarding_flow_geth.log](https://github.com/status-im/status-react/files/7643734/test_keycard_interruption_creating_onboarding_flow_geth.log)
Session + logcat: https://saucelabs.com/jobs/3a10da218e634d17a83164ce1aec872d?auth=3e14d33853f585ca172f926ef19b7041

**Comment by flexsurfer** [comment]
ping @bitgamma
