### ISSUE TITLE
Sychronize sticker packs across devices

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12889]
As a user
I want to have my sticker packs synchronized across devices
So I don't have to install them on each device.

### Description

When a user installs a sticker pack, it should also appear on any paired device that they own.
Similarly, if a sticker pack is removed, the same should happen on the paired device.

This settings should also be backed up, similarly as we do for contacts.

**Comment by Samyoul** [comment]
Possibly covered by https://github.com/status-im/status-go/pull/2478 . @bitgamma when you are available perhaps we can discuss this issue, just to see what work you've already done and if there is anything we need to team up on.

**Comment by bitgamma** [comment]
@Samyoul I am back on Monday so we can discuss this. In any case, I haven't started work on this yet, I have been doing other stuff.

**Comment by Samyoul** [comment]
Also see https://github.com/status-im/status-react/issues/13193
