### ISSUE TITLE
Allow pairing without entering your seed phrase on both devices

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12882]
As a user
I want to be able to pair a new device without entering my seed phrase
So that having multiple devices is smoother

### Description

A new pairing interface is in the works.
We will allow users to pair devices without having to input the seed phrase on both devices.

**New Designs:**
https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?node-id=758%3A134336

Both sync from mobile & desktop UI should be implemented, though we can focus on mobile->mobile at first until desktop also implements their part.
@Samyoul is working on the backend and can help out with that.

---
**Old Designs**
https://www.figma.com/file/Ystsc2tMRJOTFLYsSqhp3E/Pairing-%26-Syncing?node-id=1016%3A14980

**Comment by Samyoul** [comment]
### `status-go` Update

- https://github.com/status-im/status-go/pull/2506 (API and events awaiting merge of below tasks)
- https://github.com/status-im/status-go/pull/2601
- https://github.com/status-im/status-go/pull/2626
- https://github.com/status-im/status-go/pull/2653
- https://github.com/status-im/status-go/pull/2656
- https://github.com/status-im/status-go/pull/2729
- https://github.com/status-im/status-go/pull/2790
- https://github.com/status-im/status-go/pull/2806

**Comment by cammellos** [comment]
This is going to be fixed with waku-2, we tested in bad network conditions and large messages are sent as expected, closing for now.

**Comment by cammellos** [comment]
Don't mind me, commented on the wrong issue :)

**Comment by Samyoul** [comment]
With the merging of https://github.com/status-im/status-go/pull/2506 there should be at least the MVP in `status-go/develop` to perform key/account transfer between 2 devices. This does not do anything about automatically setting up mutual sync / pairing setup which is another step. 🥲 .

And so it continues.

**Comment by cammellos** [comment]
this has been completed
