### ISSUE TITLE
Endless "Loading" in public chats / communities (mail-02.do-ams3.eth.prod)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12884]
# Bug Report

## Problem 
In  most of cases app is stuck on fetching history for public channel (`eth.prod` / `mail-02.do-ams3`)
![IMAGE 2021-12-06 11:17:58](https://user-images.githubusercontent.com/4557972/144828817-e82dbc8c-fd53-47aa-9a64-2e41c946d637.jpg)

#### Expected behavior
history is fetched

#### Actual behavior
history is not fetched

### Reproduction

1) Open Status
2) Join public chat (sometimes need to relogin couple of times and join any public chat)

### Additional Information

- Status version: nightly 06/12/21
- Operating System: Android, iOS
Logs: [geth.log](https://github.com/status-im/status-react/files/7659892/geth.log)

**Comment by cammellos** [comment]
Closing this as server issue
