### ISSUE TITLE
Sometimes add button overlaps with tabs if move app from background 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1288]
### Description

*Type*: Bug

*Summary*: When app is moved from background to foreground then sometimes Add button overlaps tabs. Can't find steps to reproduce it always but it happens like 1 time per couple of days.
![screenshot_20170607-204609](https://user-images.githubusercontent.com/6584810/26901715-797a2582-4bdf-11e7-8a26-de0fbcaae3e8.png)

#### Expected behavior
add button overlaps with tabs
#### Actual behavior
Add button is shown as usual (above tabs)

### Reproduction
Not always reproducible
- Open Status
- Open Console
- Move app to background and use other apps for ~10 minutes
- in Applications tap on Status icon to move to the app. Check if Add button overlaps tabs on Chats screen

### Additional Information
* Status version: 0.9.8, 0.9.7
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/500
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/528
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/757

**Comment by chadyj** [comment]
No longer an issue. Closing.
