### ISSUE TITLE
Erase mentions in community or group chat from activity center from blocked user

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12885]
# Bug Report

## Problem 
[comment]: # (A problem description)
Leftover from #12878

#### Expected behavior
No community or group chats mentions in activity center after blocking user

#### Actual behavior
mentions are still in AC
![144620910-f0aca753-6cca-4e6a-911d-deaf46debd3a](https://user-images.githubusercontent.com/4557972/144846332-e0000931-6c78-4f0c-a4ea-e88999f34667.jpeg)

### Reproduction

1) User A: don't add user B as contact
2) User B: add User A to community and group chat
3) User A: join community and group chat
4) User B: mention User A in community and group chat
5) User A: block User B

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Hi @churik,
I tried blocking the user in [#b941766](https://github.com/status-im/status-react/pull/12878#issuecomment-984965248), and the group mentions and community mentions both are getting removed. Can you please verify it once more, and perhaps a video with steps, in case it still shows. Thank you

**Comment by churik** [comment]
Em, you are right, rechecked on 07/12/21 nightly and it is not reproducible, but when I was checking on https://github.com/status-im/status-react/commit/494efcabc0f303e891b5f537337c2b3deb11e1f7

So again we have the same as 2 days ago, on commit that created (after rebase I suppose?) in time of merge PR (https://github.com/status-im/status-react/commit/b9417664f6b51e671c1ea1c7cb3a5bbf846669dc) - there is  no issue, on commit that was base for build for testing (https://github.com/status-im/status-react/commit/494efcabc0f303e891b5f537337c2b3deb11e1f7) there is issue.

Closing issue for now and ask ppl in chat can we do smth about it
