### ISSUE TITLE
Add read indicator in 1-to-1 chats

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12886]
As a user
I want to be able to enable read receipts for my messages
So that I can see whether my message has been read by my recipients

### Description

When reading a message, we should notify the other end that the message has been read.
This feature should be disabled by default, and a user should be able to enable it under "Settings"->"Privacy and security".

If the feature is disabled, it should not be sending nor processing read receipts.

This applies for one to one chats only for the time being.

The design is just a change of color in the double tick.

**Comment by jo-mut** [comment]
I have implemented the change of color in the double tick to blue

**Comment by jo-mut** [comment]
However the background color of the outgoing text-message is the theme blue color. It overshadows the tick's blue color upon being delivered but its only for the textual chat message which renders it invisible

**Comment by jo-mut** [comment]
Am working on this one

**Comment by churik** [comment]
don't think it makes sense anymore
