### ISSUE TITLE
Some data added before syncing is not synced on the secondary device

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12897]
# Bug Report

## Problem 
Not all public chats, that were added before pairing, appear on the secondary device after pairing. Also, new 1-1 chats in the activity center are not synced.
In some cases, blocked users and ENS-contacts with `.eth` domain (added before pairing) are not synced. This issue was reproduced in one case out of three.

#### Expected behavior
Public chats, 1-1 chats in the activity center, all contacts, and blocked users that were added before pairing on the primary device appear on the secondary device after pairing

#### Actual behavior

- 3 out of 5 public chats are synced
- 1-1 chat in the activity center, some of contacts and blocked users are not synced

### Reproduction

1. Create a new account on device1
2. Recover this account on device2
3. Join several public chats, add to contacts an ENS-user with `.eth` domain, block some user, receive a new 1-1 cah in the activity center (do not open it) on device1
4. Sync device2 with device1 and then device1 with device2 (probably, it matters in what order the devices are synchronized)

### Additional Information

- Status version: 1.18 RC
- Operating System: Android, iOS

Logs:
device1: [geth.log](https://github.com/status-im/status-react/files/7686956/geth.log)
device2: [geth.log](https://github.com/status-im/status-react/files/7686959/geth.log)

**Comment by qoqobolo** [comment]
device1: [geth.log](https://github.com/status-im/status-react/files/7691821/geth.log)
device2: [geth.log](https://github.com/status-im/status-react/files/7691825/geth.log)

**Comment by qoqobolo** [comment]
[device1 geth.log](https://github.com/status-im/status-react/files/7692320/device1.geth.log)
[device2 geth.log](https://github.com/status-im/status-react/files/7692322/device2.geth.log)

After relogin and re-sync on device2 [geth.log](https://github.com/status-im/status-react/files/7692326/geth.log)

**Comment by churik** [comment]
closed in https://github.com/status-im/status-react/pull/12900
