### ISSUE TITLE
Synchronize ENS name across devices

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12891]
As a user
I want my ENS name to be synchronized across paired devices
So that I don't have to set it up on each one of them

### Description

When setting up an ENS name on one device, the change should also be reflected on each paired device you have.

Ideally this is also backed up similarly as we do with contacts, but this can be implemented separately.

It can be tested on Ropsten so you don't have to spend real ETH, you can ask the QA team for assistance with the faucet. 

Most of the changes (all of them probably), are in status-go.

**Comment by cammellos** [comment]
I believe this should be fixed, @qfrank correct me if am wrong and we can reopen

**Comment by qfrank** [comment]
reopen since synchronize ens name across devices only implemented in status-go before
