### ISSUE TITLE
Chat on Android

### ISSUE THREAD

**Issue by madorian** [status-im/status-react#1290]
Is this chat function supposed to work on Android? 

I've tried like 15 different "friends" the last 5 days and nothing has worked; I've never gotten a reply. I mentioned this in the slack channel and I was adviced to use a new APK, which I've done, but it also does not work. 

I've also created a new account and it also doesn't work; I never see a reply to any of my chats. 

Is it supposed to work? Is there some status page on status somewhere?

**Comment by flexsurfer** [comment]
hi @madorian we have an issue with messages in 0.9.8, will be fixed in 0.9.9, thanks

**Comment by annadanchenko** [comment]
hey @madorian Previous versions of the app are not compatible with new ones, so if 15 friends you have tried do not use the latest apk (with messaging fix) they will not see your messages. Please, add my public key I've shared with you in Slack to the app installed from the latest apk. Here is my request: https://status-im.slack.com/archives/C3NRE0L3U/p1496863973212855?thread_ts=1496863360.986654&cid=C3NRE0L3U

**Comment by annadanchenko** [comment]
fixed in 0.9.9
