### ISSUE TITLE
Deleted chat is shown again after app is relaucnhed

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1291]
### Description

*Type*: Bug

*Summary*: Chat is deleted in Chats but after app relaunch it's shown again in Chats

#### Expected behavior
Deleted chat is not shown in chats
#### Actual behavior
after app is relaunched  deleted chat is shown again in Chats

### Reproduction
Video (on emulator): https://drive.google.com/open?id=0Bz3t9zSg1wb7ckNwRVZqNHZScG8
- Open Status
- Open Chats
- Delete some chat (e.g with Auction House)
- Close app
- Open app
- Check if Auction House is shown in Chats

### Additional Information
* Status version: 0.9.8-5-ga53e1afd+, 0.9.8 release
* Operating System: Android. Can reproduce both on real device Galaxy S6, Android 6.0.1 and on Android Emulator (Nexus 6P API 25)

#### Logs

**Comment by janherich** [comment]
_In progress_
