### ISSUE TITLE
Emoji as last char erases value in input field if char + emoji > acceptable limit

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12919]
# Bug Report

## Problem 
1 emoji = 2 chars, so in case when text + emoji > limit for field (i.e. 4096 for chat input, 600 for status), value is erased
Reproducible on different text inputs on IOS (message input, group chat invite field, status input etc)

#### Expected behavior
can't type emoji, as it 2 chars

#### Actual behavior
when typing emoji, value is erased

https://user-images.githubusercontent.com/4557972/146220608-32869769-7fa8-4cf0-8b6a-97ef8d4bf12b.mp4

### Reproduction

1) Open Status
2) Open status tab > +
3) Paste text with 599 chars
4) Type emoji

### Additional Information

- Status version: 1.18 
- Operating System:  iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
https://github.com/facebook/react-native/issues/28774

There is no way to properly fix this bug at the moment. We can implement a kind of fix mentioned in the issue above, but it will rather cause flickering UI.  

Another option is to allow user to type more than 600 chars and then disable `send` button and somehow emphasise that limit has been exceeded. That might cause worse UX, but at least it will be more predictable. :) Also this is only needed for iOS version.

**Comment by rasom** [comment]
@churik it is fixed for status input 

Tested it on message input and got a bit different behaviour. Emoji is cute and `send` button is disabled, which is probably enough?

<img width=320 src=https://user-images.githubusercontent.com/2364994/149905573-2f375856-a247-43c8-8a15-6dd5a5783093.jpeg />

**Comment by churik** [comment]
Yes, it is enough, thanks @rasom
