### ISSUE TITLE
Move translations received from onehourtranslate to the app

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1292]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There are some not-translated strings shown in English for any language (because of new UI). We need to move translations from onehourtranslate so this is fixed.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Translations are updated with strings received from onehourtranslate 
#### Actual behavior
[comment]: # (Describe what actually happened.)
English strings are shown for new UI elements in non-English version
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status while phone language is set to Russian
- Check Sign in screen. It should not contain English strings

**Comment by flexsurfer** [comment]
fixed in https://github.com/status-im/status-react/pull/1374
