### ISSUE TITLE
Unable to perform swap on 1inch.exchange if initial swap was cancelled by closing bottom sheet

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12920]
# Bug Report

## Problem 
After cancelling swap on 1inch.exchange unable to complete it again ("Unknown error" on tapping on `Swap`)
Is not reproducible on MM / Chrome.

#### Expected behavior
can see the bottom sheet again

https://user-images.githubusercontent.com/4557972/146224108-b71ce670-5279-4aba-b801-0a0e0a629552.mp4

#### Actual behavior
Unknown error;
On Android can again start the process after re-login, on IOS couldn't find the way to proceed

### Reproduction

1) Restore multiaccount with funds
2) Open 1inch.exchange, connect wallet
3) Tap on "Swap"
4) Tap on Cancel
5) Tap on "Swap" again

### Additional Information

- Status version: 1.18 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
seems like that happens because `personal_ecRecover` returns `undefined`

**Comment by flexsurfer** [comment]
`CALL RPC personal_ecRecover   nil  :  #js {:jsonrpc 2.0, :id 10, :error #js {:code -32700, :message method is unsupported by RPC interface}}`
