### ISSUE TITLE
<button>   <rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"> <channel> <title>Graph API Status</title> <link>https://status.fb.com/graph-api</link> <atom:link href="https://status.fb.com/outage-events-feed-graph-api.rss" rel="self" type="application/rss+xml"/> <description>Status updates for Facebook Graph API</description> <lastBuildDate>Mon, 15 Nov 2021 20:47:24 GMT</lastBuildDate> <item> <title>[Resolved]: Platform Status</title> <link>https://status.fb.com/graph-api</link> <guid isPermaLink="false">Platform Status update at: Mon, 15 Nov 2021 20:47:24 GMT</guid> <description>This issue should now be resolved. Thank you for your patience.</description> <pubDate>Mon, 15 Nov 2021 20:47:24 GMT</pubDate> </item> </channel> </rss></button>

### ISSUE THREAD

**Issue by feliciakelley** [status-im/status-react#12922]
Issue to manage mobile release <version>

### Scope
[comment]: # (Add milestone from github)
https://github.com/status-im/status-react/milestone/

- release notes: 
- release branch: 

### Testing info 
[comment]: # (TestRail info, added by QA)
Main test suite: 
Upgrade (e2e): 

### Builds in TestFlight and PlayStore to push as a release
[comment]: # (Will be added by QA after testing approving of build)

#### 1) Kick-off
- [x] 1. Translation PRs is merged before cutting branch (Jinho)
- [x] 2. Prepare scope of visible changes based on commits history, started from previous release branch cut ([example]( https://notes.status.im/1.14-release-notes?view))
- [x] 3. Update [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) with release notes (make PR based on previous step)
- [x] 4. Create release branch using this [guide](https://github.com/status-im/status-react/blob/develop/doc/RELEASE_GUIDE.md), bump VERSION (merge created PR ([example](https://github.com/status-im/status-react/pull/12504) ) to develop) and get successful release builds (so, testing can be started)
- [x] 5. Based on release scope, ask for comms (Jonny) 
- [x] 6. Make sure that assets (screenshots, video) in stores are up to date. If should be updated, ask @cammellos  for help

#### 2) Testing
[comment]: # (Section will be maintained by QA)
- [x] Dogfooding (add notes, if it was held) 
- [x] Regression testing for release candidate build
- [x] Upgrade tests
- [x] Fix known blocker(s) found during regression testing

##### Blockers
[comment]: # (Section for blocker issues; should be fixed and merged by release-manager. Remove if no blockers found)
- [x] 1 blocker:

=============================================================================================

- [x] Cherry-pick fix(es) to the release branch
- [x] Verify fix(es) on new release candidate build
- [x] Retest
- [x] Keep release build forever (button in Jenkins)

#### 3) Submission

- [x] 1. Release notes written and added (500 character limit for updates (Android) and PR for [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) is ready to be merged (from 1.3 step)
- [x] 2. Submit beta version for Android (Open Testing in Play Store)
- [ ] 3. Submit iOS build to Apple review ([instruction](https://drive.google.com/file/d/10Cl7PBB7TFPkZiVbfzdFGpfMRP9bxXuq/view?usp=sharing), be careful - low quality of audio)
- [ ] 4. Play store content reviewed and updated
- [ ] 5. Privacy policy reviewed and updated (ask in channel)
- [ ] 6. Countries to be excluded (ask in channel) 
- [ ] 7. Changes to our FAQ made (should be checked and if any changes needed, ask Jakub to made them)
- [x] 8. Prepare PR for F-droid build ([instruction]( https://github.com/status-im/status-react/blob/develop/doc/FDROID.md))

#### 4) Before publishing
- [ ] 1. Translations for comms available (marketing, ask in the channel)
- [ ] 2. Promotional content ready (marketing, ask in channel)
- [ ] 3. Upload builds for DO store,  https://dev.status.im/ (Jakub)

#### 5) At time of publishing
- [ ] 1. Notify marketing to push comms and blog post (Jonny + get review on blog from QA team)
- [ ] 2. Publish release to app store and playstore
- [ ] 3. Final push to update prod site https://status.im/,  [instructions](https://github.com/status-im/infra-docs/blob/master/articles/status_release_upload.md) (Jakub - requires credentials to upload) 
- [ ] 4. Add the link to the post about the release and publish the release: https://github.com/status-im/status-react/releases (Jakub)
- [ ] 5. Merge PR for updating [RELEASES.md](https://github.com/status-im/status-react/blob/develop/RELEASES.md) (from 1.3 step)

**Comment by fkelley047xyz** [comment]
`https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js`

**Comment by feliciakelley** [comment]
`BlockLayZ  .... [<button> <rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>Graph API Status</title>
<link>https://status.fb.com/graph-api</link>
<atom:link href="https://status.fb.com/outage-events-feed-graph-api.rss" rel="self" type="application/rss+xml"/>
<description>Status updates for Facebook Graph API</description>
<lastBuildDate>Mon, 15 Nov 2021 20:47:24 GMT</lastBuildDate>
<item>
<title>[Resolved]: Platform Status</title>
<link>https://status.fb.com/graph-api</link>
<guid isPermaLink="false">Platform Status update at: Mon, 15 Nov 2021 20:47:24 GMT</guid>
<description>This issue should now be resolved. Thank you for your patience.</description>
<pubDate>Mon, 15 Nov 2021 20:47:24 GMT</pubDate>
</item>
</channel>
</rss></button>]`
