### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [status-im/status-react#12932]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 165  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on status-react (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve status-react's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by flexsurfer** [comment]
cc @corpetty

**Comment by serhanwbahar** [comment]
Hi @misterAnderson90,

Thank you for contacting the Status team. We are running a bug bounty program on HackerOne. You can send your findings via HackerOne: https://hackerone.com/status_im.

Best,
Serhan
