### ISSUE TITLE
Add message statuses to all types of messages

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12944]
# Feature Issue

### User Story

As a user, I want to see that all types of messages (stickers, commands, pictures, audio) are sent.
cc @hesterbruikman 
### Description
Currently only for text messages can see statuses (sent / delivered / pending)
![IMAGE 2021-12-21 13:17:18](https://user-images.githubusercontent.com/4557972/146928618-e0e50ba1-1e7b-40b2-a51b-c9e9ad82a995.jpg)

### Acceptance Criteria
Can see statuses for all types of messages.

**Comment by jo-mut** [comment]
I am working on this one.

**Comment by flexsurfer** [comment]
@churik are we sure we need status for stickers ?

**Comment by churik** [comment]
@flexsurfer 
Why not? IMO user should know if they are sent and delivered to the receiver. 
Perhaps it should be different from the perspective of design, but for now, I don't think that we need to exclude some messages and don't show status for them

**Comment by churik** [comment]
Closed due to https://github.com/status-im/status-react/pull/12962#issuecomment-1021009328 (see discussion)
