### ISSUE TITLE
Add segmented controls to community edit chats screen

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#12954]
# Feature Issue

### User Story

As a community admin, I want to separate editing/reordering of chats and categories into different screens using segments

### Designs
https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=22167%3A100053

<div align="center">
<img src="https://user-images.githubusercontent.com/17097240/148132982-f03d9266-459b-4eca-8504-af4b6515556f.png" alt="Screenshot" height="400"/>
<img src="https://user-images.githubusercontent.com/17097240/148132976-2b2f8022-6e67-4fb5-b47a-052d276cf2c5.png" alt="Screenshot" height="400"/>
</div>

**Comment by flexsurfer** [comment]
reopen, because PR hasn't been tested, cc @churik

**Comment by jo-mut** [comment]
cool. working on it so that its tested. my apologies @flexsurfer and the QA team

**Comment by Parveshdhull** [comment]
Tested - OK ([details](https://github.com/status-im/status-react/pull/13183))
