### ISSUE TITLE
is the chatkey the uncompressed public key?

### ISSUE THREAD

**Issue by readygo67** [status-im/status-react#12959]
a chat key(0x0425f536410a006f4da05388c6dcb3b11276a9eb73d3e69dabfc7c3fe20f3da46181a874b92535ed661646a802401e11fed3fd3785645bac19ec6acf2c109dfb32) looks like an uncompressed public key,  but  I can derive the address (0x1ee399b35337505dafce451a3311ed23ee023885) from the chat key.  what am I missing?

**Comment by flexsurfer** [comment]
yes chatkey = public key

**Comment by flexsurfer** [comment]
for chatkey  a different path is used, so the address derived from the chat key is not used by the user https://specs.status.im/spec/2#initial-key-generation
