### ISSUE TITLE
Mirroréd|ReusedMyDesignbyWithholding my own data .. i never authorized to allow use of my work.. TLD. ssl is net::error as well as dns configured within preventing me any rights to my TLD..

### ISSUE THREAD

**Issue by feliciakelley** [status-im/status-react#12964]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a <user|developer|...>, I want to <task> so that <goal>.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: <Bug|Feature>

[comment]: #12286 scribe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

#### Expected behavior
comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Status
- ...
- Step 3, etc.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ]  oembed data...
- [ ] ...legacy

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...yes 
```

**Comment by ducheng0** [comment]
can we just ban them from making issues/PRs?
