### ISSUE TITLE
Nothing or only 1 letter is shown in the topic of a public chat if first typed letter is in uppercase

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1297]
### Description
*Type*: Bug

*Summary*: 

In Join public chat screen user types "A" in topic. After this 
* all other typed characters are not shown at all (on iOS) 
* next typed character "deletes" the first one so field is empty (on Android)

#### Expected behavior
If there is any restriction then user should get a feedback from the app about it or typed uppercase character should be transformed to lowercase. If user types some allowed characters then they should be shown in the topic field.
#### Actual behavior
User types "A" and it's shown in the topic field. Than type "m":
1. on iOS it's not shown, so field contains "A"
2. on Android field becomes empty

### Reproduction
video (Android): https://drive.google.com/open?id=0Bz3t9zSg1wb7QkFCRUNabElMc2M
- Open Status
- Open Chats
- tap on +
- tap Join public chat
- set keyboard to uppercase and type "A"
- type "m". check that topic field contains "Am" or "am". 

### Additional Information
* Status version: 0.9.8 and 0.9.9 and 0.9.7
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by jeluard** [comment]
_In progress_

**Comment by jeluard** [comment]
Note that only lowercase characters are allowed. Other characters will be removed.
