### ISSUE TITLE
Add link with redirection to device settings for quick change of app's photo access preferences

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#12990]
# Feature Issue

Currently if user has chosen type of app's photo access as "Selected Photos" it is not obvious how to change access to "All photos" (Video of current flow attached). In order to improve this issue we can implement some kind of "Change Settings"  button in Status app that will redirect user to Status app preferences in device settings in order user can change photo access type. This kind of implementation can be observed in different apps, for example in WhatsApp (video attached). 

### User Story

As a user, I want to have possibility to be quickly redirected to Status app preferences so that I could change photo access settings from "Selected Photos" to "All photos". 

https://user-images.githubusercontent.com/97245802/148841423-24eb4978-a5af-436c-b669-bb6de0203a4b.mp4

https://user-images.githubusercontent.com/97245802/148841438-90b5008e-0cfd-498c-a6ac-ff183b58e383.mp4

**Comment by churik** [comment]
Closing due to re-design of the app.
The label `recheck` is added in order to keep an eye on it while testing the new design.
