### ISSUE TITLE
white line between status bar and splash screen on Android in dark mode

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#13002]
white line between status bar and splash screen on Android in dark mode

**Comment by Parveshdhull** [comment]
Hi @flexsurfer, Can you please attach a video or screenshot? Is your splash screen color also changing with theme? Mine remains complete screen white, even in dark mode 🤔

**Comment by Parveshdhull** [comment]
Ok, I am able to replicate dark background. But it looks like splash screen and alert dialogs, both are following system theme, not app theme. That's why even when I had dark mode in app only, it was white.

**Comment by flexsurfer** [comment]
i tried to make a video, but for some reason on video it looks different and its hard to notice, yes I have a dark splash screen

**Comment by flexsurfer** [comment]
https://user-images.githubusercontent.com/11790366/149514162-a168648a-d7c7-4bbb-a1ec-15f745d26297.mp4

@Parveshdhull in real life its more visible

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/149514237-bee2bcf1-2e94-4afe-9d8b-a2a8af0935ba.png)

**Comment by flexsurfer** [comment]
fixed by latest splash screen library
