### ISSUE TITLE
Sync wallets across accounts

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13003]
As a user
I want to have my wallet synced across accounts
So that I don't have to create the same twice

### Description

If a user creates/imports a wallet on an account, it should appear on any synced devices.
Similarly if any information is edited/changed/deleted, it should reflect on the synced devices.

### Technical implementation

We should start from generated wallet, and on the other device they should appear as watch only addresses, no private key should be passed on the wire.

This is the first step, as there's some complications with generating the wallet on the other side, as it requires the user password.

The next step will be to mark those wallets as "generate on the fly", so that when the user inputs their password (either at login or when transacting), they should be generated, becoming the same as all generated wallets.

**Comment by cammellos** [comment]
@Jonathansoufer I have updated the descriptions with the discussion we had today, let me know if you have any question.

**Comment by Jonathansoufer** [comment]
@cammellos Thank you for this update. @Samyoul and I discussed exactly about it yesterday.
