### ISSUE TITLE
"No collectibles available" at attempt to get any existing collectibles

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13016]
# Bug Report

## Problem 
![IMAGE 2022-01-17 18:16:59](https://user-images.githubusercontent.com/4557972/149813156-df9eea88-fc5f-4dcc-8ec7-042c2e61a82f.jpg)

#### Expected behavior
can see collectibles 

#### Actual behavior
No collectibles available

### Reproduction

1) Open Status
2) Restore multiaccount with collectibles
3) Enable "Display collectibles"
4) Try to uncollapse collectible category

### Additional Information

- Status version: all 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-go/pull/2491#pullrequestreview-855294034

**Comment by churik** [comment]
Again reproducible on 1.18 and nightly 31/01/22
We now need an API key  from https://docs.opensea.io/reference/getting-assets

**Comment by jakubgs** [comment]
I've requested the key using one of our org email addresses. So far no response.

**Comment by cammellos** [comment]
We received a key, it needs to be injected in status-go at build time, an example would be something like https://blog.alexellis.io/inject-build-time-vars-golang/ (feel free to find a different solution).
You can contact me or jakubgs for details about the key.

**Comment by jakubgs** [comment]
Here's the change that adds the env variable to CI builds: https://github.com/status-im/status-jenkins-lib/pull/38
