### ISSUE TITLE
Fetching chat history button stops responding after couple of fetches in public chat with lot of messages (#status) 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13012]
# Bug Report

## Problem 
After couple of fetching requests followed one after another in public chats with a lot of messages, fetch button stops responding on tapping (Video and logs attached)

https://user-images.githubusercontent.com/97245802/149550609-2b3ccb94-ae19-4be9-b80c-fa6860bee9ee.mp4

[Status-debug-logs-fetch-not-responding.zip](https://github.com/status-im/status-react/files/7871793/Status-debug-logs-fetch-not-responding.zip)

#### Expected behavior

Tapping fetch button should result in uploading chat history 

#### Actual behavior

Fetch button does not respond on tapping. App reloading fixes issue until another couple fetch requests are performed one after another.

### Reproduction

1) Open Status
2) Go to chats tab
3) Open public chat with a long history. Best reproducible on #status public chat
4) Scroll through chat history
5) Fetch couple of pages one after another until fetch button stops responding
### Additional Information

- Status version: 1.17, 1.18
- Operating System: Android 11, Device Samsung A52.

**Comment by rasom** [comment]
@pavloburykh did you try to reproduce it on iOS devices?

**Comment by pavloburykh** [comment]
> @pavloburykh did you try to reproduce it on iOS devices?

@rasom yes, it is reproducible for IOS. Below I attach video of reproduction on prod build 1.17. 

Also, for reproduction of this bug it is better to enter public chat from default list (like I did on the video). Entering public chat from search results in failing of reproduction for me.


https://user-images.githubusercontent.com/97245802/150116301-4bd3efcf-db4c-4269-be4b-6f07ebb075a7.mp4

**Comment by rasom** [comment]
I only managed to get an endless spinner on `develop` (iOS)
<img width=320 src=https://user-images.githubusercontent.com/2364994/150118306-ab9bd0cd-1624-4b2b-86c1-40a7b834e6b5.PNG />

**Comment by pavloburykh** [comment]
@rasom yeah, endless spinner is another issue that should be fixed in release build 1.18

**Comment by pavloburykh** [comment]
anyway, on current prod build 1.17 I managed to reproduce the bug today on IOS without facing endless spinner issue. So try prod build 1.17 or release build 1.18.

**Comment by rasom** [comment]
> should be fixed fixed in release build 1.18

@pavloburykh do you mean that it is already fixed in 1.18? As I reproduced it in `develop` it is very unlikely :)

**Comment by rasom** [comment]
> on current prod build 1.17 I managed to reproduce

but what is the point of doing this if it already can't be reproduced on `develop`? :) I will check on Android real device later today, but if it is not reproducible on `develop` it doesn't sound like an issue.

**Comment by churik** [comment]
@rasom @pavloburykh thanks for the investigation!
Reproduced on 1.18 and on 1.17 on `status` channel as described in the issue.
Somehow with the same steps, it is not reproducible on nightly 19/01/21.
So not relevant at the moment, maybe we'll see it later on other chats.
In that case, issue will be reopened.
Can be closed for now

**Comment by pavloburykh** [comment]
@rasom you're right, I've messed up little bit with branches. I also failed to reproduce in develop builds, so I'm closing the ticket. Thanks @churik for help!

**Comment by rasom** [comment]
@pavloburykh @churik thanks
