### ISSUE TITLE
Ethlance returns 404 error - change url or remove DApp

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1302]
### Description

*Type*: Bug

*Summary*: 
404 error if open Ethlance
![ethlance](https://user-images.githubusercontent.com/6584810/26971720-141bb3ca-4d17-11e7-8201-02b192613eb8.jpg)

#### Expected behavior
Ethlance is opened or it's not available in the Contacts
#### Actual behavior
404 error page

### Reproduction

- Open Status
- Open Contact
- Tap on Ethlance

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment]
fixed in https://github.com/status-im/status-react/pull/1345
