### ISSUE TITLE
Missing translation for Advanced->Notification switcher in IOS app

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13026]
# Bug Report

## Problem 
Advanced Notification switcher in IOS app is missing translation (see screenshot attached)
![photo_2022-01-20 17 04 26](https://user-images.githubusercontent.com/97245802/150366419-970e2240-cf97-4d83-bc8e-8094925912c2.jpeg)

#### Expected behavior
Notification switcher in IOS app has translation

#### Actual behaviour
[missing "en-us send-push-n...] instead of translated switcher name. 

### Reproduction

1) Open Status
2) Go to Settings -> Advanced -> Notifications
3) Pay attention at the name of notification switcher

### Additional Information

- Status version: nightly 
- Operating System: iOS

**Comment by Parveshdhull** [comment]
Also missing for Push notifications servers
<img src="https://user-images.githubusercontent.com/17097240/150407498-c503c26d-8959-4e07-8c28-5d3ae9c2055f.jpg" height="400"/>

**Comment by pavloburykh** [comment]
fixed
