### ISSUE TITLE
Community adds invited accounts as members even though they haven't accepted yet

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-react#13035]
# Bug Report

## Problem 
[comment]: # (A problem description)
I've noticed, when I send a community invite to another account, that account will see the invite with a member count that includes that same account, even though that account hasn't accepted the invite yet.

#### Expected behavior

Invited accounts should not be automatically added to the members of the community if they haven't accepted the community invite yet.

#### Actual behavior

They show up in the members list (and count) before they accepted the invite

### Reproduction

See description above.

### Additional Information

- Status version: 1.17.0
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app.

The label `recheck` is added in order to keep an eye on it while testing this part of the new design.

**Comment by 0x-r4bbit** [comment]
@churik I think this can be considered fixed by now anyways. The reason this was showing as explained is because we used to optimistically add everyone we invited to the community.

This is no longer the case. Users always have to request access to a community and only after they've been accepted they the owner, they'll be added to the members list.
