### ISSUE TITLE
Adding a user as a contact sends a mutual contact request

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-react#13033]
# Bug Report

## Problem 
[comment]: # (A problem description)
I used the scan QR code feature to find a Status user (another test account I own). The profile opened which allows me to do a bunch of things. One of those things being the ability to set the local nickname.

I've set the local nickname but didn't actually send a contact request.
The moment I set the nickname, I saw the contact request in that other account.

#### Expected behavior

Setting the local nickname of some account should not result in a contact request.

#### Actual behavior

Setting the local nickname of some account results in a contact request.

### Reproduction

See description above.

### Additional Information

- Status version: 1.17.0 (20211021123338)
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
@PascalPrecht, Thanks for the bug report.

### Steps to reproduce:
1. Scan QR of `desktop client` in `mobile app` (as mutual contacts yet not supported by mobile)
2. Add user as a contact
3. Contact request will be sent to `desktop` user

will be fixed in https://github.com/status-im/status-react/issues/12175

**Comment by cammellos** [comment]
This does not happen anymore, it should be fixed, https://github.com/status-im/status-react/issues/13033#issuecomment-1020098538 this is the expected behavior I believe. @churik @pavloburykh would you mind checking if you can replicate? otherwise is ok to close.

Thanks!
