### ISSUE TITLE
No value in 'Gas amount limit' field in NFT dapps by default

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13046]
# Bug Report

## Problem 

The 'Gas amount limit' field is empty in collectible dapps (the issue confirmed for Superrare, Cryptographics, Clovers, The Hash Avatars, and Cryptokitties).
Gas estimation is performed correctly in dapps such as Uniswap or Penguinswap, and also in Metamask. 

![IMG_6246](https://user-images.githubusercontent.com/67952253/150959987-870ead65-367c-4079-9751-fcd69810f9a6.png)

#### Expected behavior
'Gas amount limit' is estimated by default

#### Actual behavior
'Gas amount limit' is not estimated 

### Reproduction

1. Open Browser
2. Go to superrare.com
3. Initiate tx signing 
4. Tap Network fee

### Additional Information

- Status version: nightly 25/01
- Operating System: Android, iOS

[geth.log](https://github.com/status-im/status-react/files/7932813/geth.log)

**Comment by flexsurfer** [comment]
seems like this line causes the issue https://github.com/status-im/status-react/blob/develop/src/status_im/signing/gas.cljs#L393

**Comment by pavloburykh** [comment]
### UPDATE

Reopening as still reproducing the bug. Managed to replicate on opensea.io , cryptokitties.co

**Steps:** 

1. Open Browser
2. Go to  opensea.io / cryptokitties.co
3. Try to purchase some collectible
4. When signing modal will appear - open network fee and see if Gas limit amount has been calculated

**Actual result:** Error 'execution reverted'. Gas limit amount field is empty. Bug does not reproduces every time and on every account. Ping me if you will need assistance with reproduction. 

**Expected result:** Gas limit amount field has calculated gas value

![photo_2022-08-10 15 06 19](https://user-images.githubusercontent.com/97245802/183896889-1d2f5f68-42a5-4168-a40f-50648f496824.jpeg)

https://user-images.githubusercontent.com/97245802/183240911-b7494828-55c6-477a-8d9c-3691ee9a79f6.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9274659/geth.log)

**Comment by pavloburykh** [comment]
Causing fail of e2e ID 702167 https://ethstatus.testrail.net/index.php?/tests/view/2955502

**Comment by flexsurfer** [comment]
`execution reverted` means there is an unexpected error in the contract, and it's not related to this issue

**Comment by pavloburykh** [comment]
Thanx @flexsurfer for clarifying this case.
