### ISSUE TITLE
Polish animation when replying to message

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13055]
When replying to messages, the animation when the input is populated and when is cleared is a bit rough, we should improve it to make it a bit smoother.

**Comment by marinhoarthur** [comment]
@cammellos I'll be taking this one for myself. Couldn't find this issue on Gitcoin though.

Just to be accurate: I understand that the animation being referred to is the one regarding the height of the input box as the replied-to-msg enters/exits (see video).


https://user-images.githubusercontent.com/3693700/178674588-57df2e01-9f6e-4b35-8f18-37fe66b11ef2.mov

**Comment by cammellos** [comment]
> @cammellos I'll be taking this one for myself. Couldn't find this issue on Gitcoin though.
> 
> Just to be accurate: I understand that the animation being referred to is the one regarding the height of the input box as the replied-to-msg enters/exits (see video).
> 
>  status.mov

@marinhoarthur Thanks, we create the bounty on gitcoin after someone expresses interest, as we don't want too many people to apply for it, I'll create a bounty today.

Yes, that's the animation I was referring to
Thank you

**Comment by marinhoarthur** [comment]
Got the app up and running locally. Will dive into the actual issue.
