### ISSUE TITLE
Message status changes from 'Delivered' to 'Sent' in 1-1 chat history if send messages from offline, return online, and receive another message 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13057]
# Bug Report

## Problem 

Double ticks in the message status in 1-1 chat change to single ticks after going offline, sending a message from offline, returning online, and receiving another message (presumably, from the third user, but once could reproduce it with receiving a message from the same user - your contact, with whom you are chatting). 
The issue is reproducible in ~90% of cases on Android and is not reproducible on iOS so far.

#### Expected behavior

Once received status "Delivered" does not change to "Sent" after relogin

#### Actual behavior
Status changes

https://user-images.githubusercontent.com/67952253/151545214-5b42ce7d-70f2-46e1-b9e3-dd875270e8f5.mp4

### Reproduction

1. Create new accounts on device1, device2, and device3
2. On device1 add to contacts device2 and device3, start 1-1 chats to see them on the home screen
3. Device2 is online. On device1 send several messages to device2
4. On device1 turn on airplane mode, send several messages more, return online, wait for messages to get status 'Delivered' (double ticks)
5. Right after that, send a couple of messages from device3 to device1
6. On device1 wait for double ticks turn into single ticks (~60 sec)

### Additional Information

- Status version: 1.18
- Operating System: Android (iOS not defined)

### Logs

[Device1 geth.log](https://github.com/status-im/status-react/files/7958513/geth.log)

**Comment by flexsurfer** [comment]
probably related https://github.com/status-im/status-react/pull/12812
cc @rasom

**Comment by cammellos** [comment]
Should be fixed in #13065 , feel free to re-open if necessary
