### ISSUE TITLE
Add error/validation feedback to users when adding duplicated watch-only accounts 

### ISSUE THREAD

**Issue by Jonathansoufer** [status-im/status-react#13062]
### Description
As a user
I want to know if there's something wrong when I type the information needed to add a watch-only account 
**so that** I can fix and add the account. 

### Description

When a user attempt to add a watch-only account already registered, no feedback is given. 
This impacts watch-only accounts.

*Summary*:

![Screenshot 2022-01-28 at 17 50 24](https://user-images.githubusercontent.com/44679989/151602801-c35ce355-1da0-4d14-8ceb-c728c846ec96.png)

### Acceptance Criteria

When user attempts to add an already registered watch-only account, he/she should see an alert saying something like this: "Duplicated account: This account was already registered previously."

**Comment by adamschmideg** [comment]
I'm not sure if there's a "standard" way of handling such an error. Here's how I'd proceed. When you enter an address or account name already added, do this:
- Disable the "Add an account" button
- Show a little error message similar to the one displayed when you want to transfer an incorrect amount

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app.

The label `recheck` is added in order to keep an eye on it while testing this part of the new design.
