### ISSUE TITLE
Crash on creating  community 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13082]
# Bug Report

## Problem 
Status crashes on tapping `Create`  while opening community.
Regression appeared on nightly 03/02/22, so likely caused by go-update in https://github.com/status-im/status-react/commit/9fb81c3894d646bf29a4583240f936aa836ad937
Blocker for 695856,695842,695842

#### Expected behavior
No crash

#### Actual behavior
Crash

### Reproduction

1) Open Status
2) Try to create community

Video:  https://app.saucelabs.com/tests/77c92de4a13d49c8b9b89c2ed2919f6c?auth=6a787d2024cf2d40e6cdfc32f86307e8#94

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
Logcat: [logcat (2).log](https://github.com/status-im/status-react/files/8015144/logcat.2.log)

**Comment by rasom** [comment]
should be fixed in `develop`
