### ISSUE TITLE
Disable messaging with a blocked contact

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#13115]
# User can send messages to blocked contact

## Problem 
Users are able to send messages to contacts they have blocked. We want when a contact has been blocked by the user, they should not be able to send the blocked contact a message. If the user unblocks the contact, they should be able to send messages to the contact again.

#### Expected behavior
Sending message to a blocked contact is disabled

#### Actual behavior
Sending message to a blocked contact is allowed

### Reproduction

1) Open Status
2) Block a contact from your contacts lists
3) Try send a message to the blocked contact
4) Confirm that you were able to send a message to the blocked contact

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
hey @jo-mut i don't think its a valid case, I think that's fine that you can write to blocked user

**Comment by flexsurfer** [comment]
its not a bug for sure, we could create a feature but I'm not sure its a valid case, I would want to write to spammers

**Comment by jo-mut** [comment]
> its not a bug for sure, we could create a feature but I'm not sure its a valid case, I would want to write to spammers 

Its just didn't seem right that you can just chat with a blocked user but see why you say ita not a valid case like you pointed out. I guess its okay
