### ISSUE TITLE
Stop sending acknowledgments to blocked users

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#13114]
# Message status changes from sent to delivered when messaging with a blocked contact

## Problem 
When a contact sends a message to a blocked contact while the blocked contact is active, the status of the message changes from sent to delivered which should not happen. We want when messaging with a blocked contact the message status to remain as sent

#### Expected behaviour
Message status remains sent when sending a message to a blocked contact

#### Actual behaviour
Message status changed to delivered when sending a message to a blocked
contact when the contact is active or comes online

### Reproduction

1) Open Status
2) Block a contact from your contacts lists
3) Confirm the blocked contact is active
4) Send a message to the blocked contact
4) Confirm that message status changes from sent to delivered

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app.

The label `recheck` is added in order to keep an eye on it while testing this part of the new design.
