### ISSUE TITLE
ENS disappears from Profile in case of logout and re-login before ENS purchase transaction is confirmed

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13124]
When user logouts the account before ENS purchase transaction is confirmed, the connected ENS disappears from Profile and needs to be re-added manually. 

STR: 
1. Sign ENS purchase transaction
2. Logout and the re-login the account before transaction is confirmed
3. Open Profile and pay attention if ENS name is displayed

#### Expected behavior
ENS name is displayed

#### Actual behavior
ENS name disappeared from Profile and needs to re-added manually. 

https://user-images.githubusercontent.com/97245802/155134628-a91ee652-42f9-481e-b3a6-303e67b5bac6.mp4

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app.

The label `recheck` is added in order to keep an eye on it while testing this part of the new design.
