### ISSUE TITLE
Add android mute notification on public chat mentions

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#13126]
As an android user I want to stop receiving  public chat mention notifications of muted contacts

### Description
If a contact is muted, we should not show notifications of mentions for muted contacts on public chats.

### Technical details
Most of the changes are in status-go, there's already an endpoint that we use to mute chats/contacts, we just need to enable the UI in status-react and make sure that we don't show notifications for muted contacts, that's done in status-go.

**Comment by qoqobolo** [comment]
Also, this is relevant for messages in group chats from muted users with local notifications enabled.

**Comment by jo-mut** [comment]
> Also, this is relevant for messages in group chats from muted users with local notifications enabled.

Thats mean we stop showing notifications for public chats and group chat mentions for muted chats we did for one to one chats. I am working on this

**Comment by jo-mut** [comment]
this is not relevant in the redesigned app am closing it
