### ISSUE TITLE
Can't connect to Wallet Connect through the Status mobile browser

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13141]
# Bug Report

## Problem 
Leftover from https://github.com/status-im/status-react/pull/13032#
Nothing happens when trying to connect to Wallet Connect in a DApp in the mobile Status browser.

#### Expected behavior
Can use Wallet Connect in the mobile Status browser

#### Actual behavior
https://user-images.githubusercontent.com/67952253/155364194-92180332-f03e-424f-b016-c2f7fbfc5fde.mp4

### Reproduction

1. Open some dapp in the Status app browser, e.g. app.1inch.io
2. Tap Connect wallet
3. Choose network
4. Choose WalletConnect
5. Tap Connect

### Additional Information

- Status version: nightly
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
cc @briansztamfater

**Comment by flexsurfer** [comment]
hey @qoqobolo @briansztamfater @audriu  i don't think its a valid case, why would you want to connect with wallet connect if you can use status wallet directly

**Comment by audriu** [comment]
So is this whole story not valid or does it mean the ticket has to be redefined?
