### ISSUE TITLE
Timeline images stretch off screen

### ISSUE THREAD

**Issue by du82** [status-im/status-react#13149]
Images in the timeline stretch off the screen.
This bug started on version 1.18 and still exists on horizontal images.

![Screenshot_20220305-102717_Status](https://user-images.githubusercontent.com/65834069/156891925-ac45d5b2-c9a3-4c69-9e66-2a543c84088b.png)

**Comment by siddarthkay** [comment]
@cammellos : Please assign this to me

**Comment by siddarthkay** [comment]
@ducheng0 : This seemed okay on my iphone 11 (screenshot attached below ), I will test on Android next, Could you please share device specifications you have captured this screenshot from? 

![IMG_C3F3E90357CD-1](https://user-images.githubusercontent.com/64726664/159864938-8c503450-cb13-42bf-a0e9-e9404ebc56d2.jpeg)

**Comment by siddarthkay** [comment]
was able to reproduce this on my android device, the `image-set-size` method resizes the image width which then overflows on android, working on a fix...

**Comment by du82** [comment]
> @ducheng0 : Could you please share device specifications you have captured this screenshot from?

Android 11
Samsung Galaxy A505U (Rooted, Google purged)
Latest nightly build installed

Problem persists independent of root or google purge status, and it persists on multiple Google Pixel VMs that I tested too running Android 11 and 12

**Comment by siddarthkay** [comment]
Thanks @ducheng0 ! 
Once https://github.com/status-im/status-react/pull/13211 passes QA and is merged it will fix this issue for all devices :)
