### ISSUE TITLE
Add permissions management for Wallet Connect

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13140]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to revoke access for Wallet Connect to my Status account from `Privacy and security` settings **so that** I don't need to do it in a desktop DApp. 

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: Currently, we can't revoke Wallet Connect's access to the Status account through the app's settings as we can with DApp accesses (`Profile` > `Privacy and security` > `Set DApp access permissions`). To do this we need to open a desktop version of DApp and disconnect the wallet there.

### Acceptance Criteria

Permissions management for Wallet Connect is added to Status settings

### Notes

Improvement for [Wallet Connect 1.0](https://github.com/status-im/status-react/pull/13032)

**Comment by qoqobolo** [comment]
cc @briansztamfater

**Comment by siddarthkay** [comment]
This issue is fixed in : https://github.com/status-im/status-mobile/pull/13799
