### ISSUE TITLE
Chat view redesigns

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13156]
We need to apply the new chat designs https://www.figma.com/file/lWq5Jk6FfQbyBK9I8AJlUi/Mobile-UI-Look-%26-Feel?node-id=839%3A21490

Mind that the designs are not ready ready, please coordinate with the design team for more info.

**Comment by du82** [comment]
Not a fan of the discord-style chat without message bubbles... Could that be an option to switch between them for those who like bubbles?

**Comment by flexsurfer** [comment]
John_ — Today at 3:58 PM


_There certainly could be in the future, but I would say it's should probably be out of scope until we've got the mobile reskin done and the communities MVP launched.  We are aiming for our product to be primarily focused on the group chat space (as opposed to the 1on1 and ad-hoc group chat messaging space), and if we look at the Slack mobile app, the MS Teams mobile app, the Discord mobile app, or even the mobile apps smaller group chat competitors like Twist or Chanty, none of them use message bubbles._

_Of course we are still fully supporting 1on1 and ad-hoc messaging, that's not changing at all, but our primary focus for user growth will be the Communities group chat functionality.  So if it's ok, let's loop back to this question once we've got the mobile redesign done and the communities mvp out of the door._
