### ISSUE TITLE
Move tx users to JSON

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13159]
# Problem
Follow up on https://github.com/status-im/status-react/pull/13152
As the solution here https://github.com/status-im/status-react/pull/13152 is not optimal, better to add users to JSON file (or similar) that is loaded using explicit logic that we can control, so we can for example skip some tests affected by it missing

## Acceptance Criteria
users.py is in the repo and only tx users are added from secret JSON

**Comment by cammellos** [comment]
I believe this might not be anymore relevant for now, @churik feel free to re-open if necessary
