### ISSUE TITLE
"Update to latest version ..." in case of replying to image message

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13171]
# Bug Report

## Problem 
Recent regression (no issue on 1.18.2)
"Update to latest version" is shown nstead of image thumbnail when replying yo image.

#### Expected behavior
![IMAGE 2022-03-14 12:32:39](https://user-images.githubusercontent.com/4557972/158163682-d5a83abc-246a-4fd6-9878-e997ff4ab12a.jpg)

#### Actual behavior
![IMAGE 2022-03-14 12:33:15](https://user-images.githubusercontent.com/4557972/158163763-366e4160-9bdf-4b1e-bed0-131bbdc0bdca.jpg)

### Reproduction

1) Open Status
2) Send image (any chat type that allows sending images)
3) Image > Reply 

### Additional Information

- Status version: nightly  14/03/21
- Operating System: Android, iOS

**Comment by msuess** [comment]
This might be caused by #13019. I'll look into this.

**Comment by flexsurfer** [comment]
most likely its related to http server for images, there is no image property in the quoted-message

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-go/pull/2418/files#diff-9c10d1fdc9bdc5ba03f06708c5860c31fdde851efed63c172d6900c887a8481aL209

**Comment by flexsurfer** [comment]
something like this, but for some reason code doesn't work https://github.com/status-im/status-go/pull/2591/files , @cammellos could you take a look ?

**Comment by cammellos** [comment]
@flexsurfer the only thing I can see is that it could have crashed for nil checks, but otherwise it looks like it should work, provided that we fetch the image, what happens in the frontend?
