### ISSUE TITLE
Long username is overlaid on timestamp in Activity center (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13178]
# Bug Report

## Problem 
[comment]: # (A problem description)

![photo_2022-03-17_12-09-46](https://user-images.githubusercontent.com/67952253/158796650-8cdf5166-4e56-438d-af2d-9ebb032445c6.jpg)

### Reproduction

1. UserA with a long username creates a new 1-1 chat with UserB
2. UserB (Android) opens Home screen > navigates to the Activity center (the bell at the top right)

### Additional Information

- Status version: nightly 17/03
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
cc @siddarthkay

**Comment by siddarthkay** [comment]
@cammellos : can you please assign this to me? I already have some research on this issue which could come in handy!

**Comment by siddarthkay** [comment]
Resumed working on this..

Can someone tell me use-cases when notifications actually appear in the activity center other than when a new contact chat has begun?
I am looking for some easily reproducible cases that I can repeat 10-20 times.

**Comment by siddarthkay** [comment]
For now I am just adding and removing the same contact again and again

**Comment by qoqobolo** [comment]
> Can someone tell me use-cases when notifications actually appear in the activity center other than when a new contact chat has begun?

1. You can also delete the chat with **non-contact** user from the home screen and receive a message from them again;
2. Notifications on replies and mentions in group chats and communities also appear in the Activity center.
- UserA with a long name adds UserB to contacts and creates a group chat
- UserB joins the group
- UserA mentions UserB or replies to their message in the group
- UserB checks the activity center

<img width="219" alt="Screenshot 2022-03-21 at 10 57 39" src="https://user-images.githubusercontent.com/67952253/159238984-f65b69b8-2f60-4b12-b7a0-9a86f8c7fe83.png">
