### ISSUE TITLE
Cannot delete images or audio messages

### ISSUE THREAD

**Issue by du82** [status-im/status-react#13181]
Users cannot delete images or audio messages. Occasionally a delete button will appear, but I believe this is a bug and not intentional.

Tested on:
~ Android 11
~ Samsung Galaxy A505U
~ Version 1.18.1 - Latest nightly

**Comment by flexsurfer** [comment]
@churik could QA confirm this?

**Comment by churik** [comment]
Yeah, it has never been done.
No delete button on my side on both IOS and Android platforms
