### ISSUE TITLE
Silent crash to homescreen on start (iOS only)

### ISSUE THREAD

**Issue by CapitanRedBeard** [status-im/status-react#1319]
### Description
Starting up the iOS simulator after running the [start instructions here](http://wiki.status.im/contributing/development/building-status/) the app will crash silently shortly after start and go to the home screen. No error is reported. My android simulator works like a champ

*Type*: Bug

#### Expected behavior
Expected behavior is to run without crashing silently to the home screen

#### Actual behavior
The simulator crashes to the home screen

### Reproduction
After installing 
run 
```
$ git clone git@github.com:status-im/status-react.git -b master && cd status-react
# or
$ git clone git@github.com:status-im/status-react.git -b develop && cd status-react

$ lein deps && npm install && ./re-natal deps && lein generate-externs && ./re-natal use-figwheel && lein re-frisk use-re-natal && ./re-natal enable-source-maps
$ mvn -f modules/react-native-status/ios/RCTStatus dependency:unpack
$ cd ios && pod install && cd ..
$ lein prod-build
$ ./re-natal use-ios-device simulator
$ ./re-natal use-figwheel
# new tab, run figwheel REPL
$ BUILD_IDS="ios,android" lein repl
# new tab, run react native packager
$ react-native start
$ react-native run-ios
```
This will start my Xcode 8.3, iOS 6 OS 10.3 simulator and will crash in about 3 seconds.

### Additional Information
Here is a gif of the behavior:
![statusiosbug](https://user-images.githubusercontent.com/5445860/27015270-01d08958-4ebf-11e7-9586-061c804b630c.gif)

#### Logs
No logs reported anywhere, RN packager looks fine

**Comment by jeluard** [comment]
Lots has changed here. Please reopen if it still applies.
