### ISSUE TITLE
Synchronise gif setting fields

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-react#13191]
Implement functionality that handles the syncing of the `gifs/favorite-gifs` and `gifs/recent-gifs` settings.

### Background

In `status-go` syncing of settings has been implemented, and additional setting sync *should be* a relatively straightforward process. The initial work for syncing of the `gifs/favorite-gifs` and `gifs/recent-gifs` settings has been implemented on the `status-go` side.

See https://github.com/status-im/status-go/pull/2478 and https://github.com/status-im/status-react/pull/13053

However additional work needs to be done on these two setting fields to get robust behaviour:

- [ ] Liaise with Desktop to get sample for testing
- [ ] Establish a consensus on what should happen if there are differences between the gif data payloads
  - Example: `gifs/favorite-gifs` may contain 3 gifs on device A and 4 gifs on device B, and both sets have 2 gifs in common and the other gifs are unique. What should happen when syncing this data?
    - Overwrite the data with first being the winner
    - Combine the data into a merged set

### `status-go` Implementation

Currently the `gifs/favorite-gifs` and `gifs/recent-gifs` setting have thier sync functionality disabled:

```go
GifFavourites = SettingField{
	reactFieldName: "gifs/favorite-gifs",
	dBColumnName:   "gif_favorites",
	valueHandler:   JSONBlobHandler,
	// TODO resolve issue 8 https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963
	//  The reported issue is not directly related, but I suspect that gifs suffer the same issue
	syncProtobufFactory: &SyncProtobufFactory{
		inactive:          true, // Remove after issue is resolved
		fromInterface:     gifFavouritesProtobufFactory,
		fromStruct:        gifFavouritesProtobufFactoryStruct,
		valueFromProtobuf: BytesFromSyncProtobuf,
		protobufType:      protobuf.SyncSetting_GIF_FAVOURITES,
	},
}
GifRecents = SettingField{
	reactFieldName: "gifs/recent-gifs",
	dBColumnName:   "gif_recents",
	valueHandler:   JSONBlobHandler,
	// TODO resolve issue 8 https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963
	//  The reported issue is not directly related, but I suspect that gifs suffer the same issue
	syncProtobufFactory: &SyncProtobufFactory{
		inactive:          true, // Remove after issue is resolved
		fromInterface:     gifRecentsProtobufFactory,
		fromStruct:        gifRecentsProtobufFactoryStruct,
		valueFromProtobuf: BytesFromSyncProtobuf,
		protobufType:      protobuf.SyncSetting_GIF_RECENTS,
	},
}
```

To reactivate the `gifs/favorite-gifs` and `gifs/recent-gifs` functionality in `status-go` simply remove the `inactive` field from the `SyncProtobufFactory`

**NOTE:** the TODO comment referring to [Issue 8](https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963) has been resolved, but the rest of the functionality to make gif syncing work has not been fully implemented. That's your job now 😎

**Comment by cammellos** [comment]
Closing for now, as that's something we wont be working as of now until designs are clearer on gifs usage
