### ISSUE TITLE
Synchronise `preview-privacy?` setting

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-react#13192]
Implement functionality that handles the syncing of the `preview-privacy?` setting.

### Background

In `status-go` syncing of settings has been implemented, and additional setting sync *should be* a relatively straightforward process. The syncing of the `preview-privacy?` setting has been implemented from the `status-go` side.

See https://github.com/status-im/status-go/pull/2478 and https://github.com/status-im/status-react/pull/13053

However there is additional functionality that needs to be implemented on the `status-react` side to make `preview-privacy` work correctly.

See the QA report here [ISSUE 7: The preview-privacy setting is not applied on the synced Android device](https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963)

### `status-go` Implementation

Currently the `preview-privacy` setting has its sync functionality disabled:

```go
PreviewPrivacy = SettingField{
	reactFieldName: "preview-privacy?",
	dBColumnName:   "preview_privacy",
	valueHandler:   BoolHandler,
	// TODO resolved issue 7 https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963
	syncProtobufFactory: &SyncProtobufFactory{
		inactive:          true, // Remove after issue is resolved
		fromInterface:     previewPrivacyProtobufFactory,
		fromStruct:        previewPrivacyProtobufFactoryStruct,
		valueFromProtobuf: BoolFromSyncProtobuf,
		protobufType:      protobuf.SyncSetting_PREVIEW_PRIVACY,
	},
}
```

To reactivate the `preview-privacy` functionality in `status-go` simply remove the `inactive` field from the `SyncProtobufFactory`

**Comment by cammellos** [comment]
I think this field does not need to be synchronized, since it's kind of particular to a specific device, feel free to re-open if disagree
