### ISSUE TITLE
"No protocol method" on login when connected to custom history node

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13208]
# Bug Report

## Problem 
Appeared on nightly 23/03/22, no issue on 22/03/22
Can't log in after connected to custom mailserver

#### Expected behavior
Can login

#### Actual behavior
![IMAGE 2022-03-24 10:09:23](https://user-images.githubusercontent.com/4557972/159881780-d424a854-86d5-4867-a06b-9f4df22d9fe3.jpg)

### Reproduction

1) Open Status
2) Add custom valid mailserver, i.e. (`ee2b53b0ace9692167a410514bca3024695dbf0e1a68e1dff9716da620efb195f04a4b9e873fb9b74ac84de801106c465b8e2b6c4f0d93b8749d1578bfcaf03e:pass@104.197.238.144:443`)
3) Connect
4) Save
5) Login

### Additional Information

- Status version: nightly 23/03/22
- Operating System: Android, iOS
[test_can_not_connect_to_mailserver_geth1 (1).log](https://github.com/status-im/status-react/files/8340075/test_can_not_connect_to_mailserver_geth1.1.log)

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
when the investigation is done, can you please notify what PR in status react cause this one?
Thank you!

**Comment by cammellos** [comment]
@churik It's fixed in https://github.com/status-im/status-react/pull/13206 
I believe the issue was introduced in the sync settings PR, it was a rebase issue and one the fields was serialized correctly when saved on the database.
