### ISSUE TITLE
ENS name list `usernames` should sync with `preferred-name` setting

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-react#13204]
Include `usernames` in the setting fields that are synced. Once implemented, reactivate `preferred-name` in the same PR.

- [ ] Get sample of raw `usernames` data
- [ ] Build out some TDD tests with the data

Be careful to check a repeat of [Issue 8](https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963)

See for more details: https://github.com/status-im/status-react/pull/13053#issuecomment-1075336559

**Comment by Samyoul** [comment]
@flexsurfer do you have any sample data for ENS username lists? The data that is passed into the `status-go` to save

**Comment by cammellos** [comment]
Closing for now, @qfrank feel free to reopne if actionable

**Comment by qfrank** [comment]
reopened since preferred-name not reactivate, the corresponding PR for status-go coming soon
