### ISSUE TITLE
Empty spaces between stickers in stickers' lists

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13223]
### Reproduction

1) Open Status
2) Make sure app is using Mainnet
3) Initiate 1-1 or group chat with any user
4) Install couple of different stickerpacks (Open chat => tap stickers icon => Get Stickers) 
5) Send some Stickers in chat
6) Go through stickers in added sticker packs tabs and recently sent tab
7) Pay attention if there are any empty spaces between some stickers

#### Expected behavior
No empty spaces between stickers

#### Actual behavior
Empty spaces between some stickers

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

https://user-images.githubusercontent.com/97245802/160409434-0bf9f534-ebd7-4389-a856-0572c8c00cae.mp4

![photo_2022-03-28 16 36 55](https://user-images.githubusercontent.com/97245802/160409865-71f8a624-cdc1-43ba-b489-98695097a526.jpeg)
![photo_2022-03-28 16 37 00](https://user-images.githubusercontent.com/97245802/160409875-0d331d5a-5bd2-4053-ae60-27245cbe68fe.jpeg)
![photo_2022-03-28 16 37 04](https://user-images.githubusercontent.com/97245802/160409887-474740d8-362f-4641-bab9-9e125e38264c.jpeg)

**Comment by Parveshdhull** [comment]
hi @pavloburykh, is this issues same as: https://github.com/status-im/status-react/issues/12770

**Comment by flexsurfer** [comment]
@Parveshdhull i don't think so, it's more like https://github.com/status-im/status-react/issues/9482, old one

**Comment by pavloburykh** [comment]
@Parveshdhull Hi! Yes, @flexsurfer is right. I didn't see an old issue https://github.com/status-im/status-react/issues/9482. I guess, I need to delete this one as duplicate. Thanx

**Comment by pavloburykh** [comment]
closing as duplicate of https://github.com/status-im/status-react/issues/9482
