### ISSUE TITLE
Incorrect resolve token rates

### ISSUE THREAD

**Issue by boozook** [status-im/status-react#13231]
Problem:
Rates resolving happens for token by its id/name. For example if we have two various tokens named XFI, we have a problem. 

Steps to reproduce:
- open app
- add token by address 0xe4e822c0d5b329e8bb637972467d2e313824efa0 (XFI, __Dfinance__)
- see rates

Curren result:
Rates wrong, resolves __by name__ (XFI) for [XFI xfinance](https://www.coinbase.com/price/xfinance) 
instead of needed 0xe4e822c0d5b329e8bb637972467d2e313824efa0 by [Dfinance](https://www.coinbase.com/price/dfinance).

Expected result:
Rates should be resolved for 0xe4e822c0d5b329e8bb637972467d2e313824efa0 token.

![F87B67C3-C38A-4D82-A843-4D0E36B7C76D](https://user-images.githubusercontent.com/888526/160650916-137c86b4-f7b3-4e0d-9713-4ebeede9130c.png)
![A0F6F5F1-DF66-481B-8214-3A3F93745217](https://user-images.githubusercontent.com/888526/160650921-577f6e72-8ec7-4fe5-aa80-4c681b0848c2.jpeg)
![074C44F6-45D4-401C-973F-DA04F9B29438](https://user-images.githubusercontent.com/888526/160650925-2afe38e5-2939-4464-8b2b-10e130d14893.png)

**Comment by flexsurfer** [comment]
we're limited by https://min-api.cryptocompare.com/documentation

**Comment by boozook** [comment]
> @churik closed this as [completed](https://github.com/status-im/status-mobile/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [yesterday](https://github.com/status-im/status-mobile/issues/13231#event-7964736763)

In this case will be better to close this with "Close as not planned", because it isn't done. Just FYI.
<img width="347" alt="Screenshot 2022-12-07 at 17 59 44" src="https://user-images.githubusercontent.com/888526/206198589-262e2c4a-f7ec-4b9f-a878-88b1b10eafa6.png">

**Comment by churik** [comment]
cool, good to know, thank you @boozook
