### ISSUE TITLE
"It's been quiet here for 19079 days" after clear history in public chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13233]
# Bug Report

## Problem 
After clearing history in public chat "It's been quiet here for 19079 days"

#### Expected behavior
![IMAGE 2022-03-30 12:17:46](https://user-images.githubusercontent.com/4557972/160809164-174dedc1-8b44-4886-88b8-e97c56dbfd83.jpg)

#### Actual behavior
It's been quite here (IMO better with no time reference)

### Reproduction

1) Open Status
2) Join any public chat
3) Clear history

### Additional Information

- Status version: release 1.19 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
frightening quietness
