### ISSUE TITLE
App crashes on Android O 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1324]
### Description

*Type*: Bug

*Summary*: App crashes on Android O 

#### Expected behavior
App can be installed, launched and user can set a password
#### Actual behavior
App crashes on first launch

### Reproduction

- Install Status
- tap on the Status app icon to open ->  I get a white screen and then a "Status has stopped" message.

### Additional Information
* Status version: 0.9.9
* Operating System: Android O

### Logs
[crashAndroidO.txt](https://github.com/status-im/status-react/files/1071226/crashAndroidO.txt)

**Comment by flexsurfer** [comment]
In progress

**Comment by Ornolfr** [comment]
having the same on my Android 21 Lenovo K920

**Comment by Ornolfr** [comment]
@flexsurfer dudes you should have never tried to do such a serious project on react native...

**Comment by asemiankevich** [comment]
[Android8Crash.txt](https://github.com/status-im/status-react/files/1187534/Android8Crash.txt)

**Comment by goranjovic** [comment]
Ran into this one on my first run, too.

**Comment by goranjovic** [comment]
Can't reproduce this any more. The log still contains some of the warnings like above, but the app does not crash. Instead, user can sign up fine, but the app then gets stuck on 65% syncing (starts at that percentage and doesn't move after)

**Comment by annadanchenko** [comment]
Installed and synced successfully on Android 8.0 on real device Google Pixel XL, using develop build 0.9.10-71-g5d2a0e83+
No crashes.
