### ISSUE TITLE
PNs are not auto cleared after messages are read. (IOS and Android with turned on local notifications)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13245]
# Bug Report

PNs are not automatically cleared after opening chat (1-1/group/ public) and reading unread messages. Bug is reproducible for IOS and Android with remote notifications on. For local notifications on Android everything works correct. 

### Reproduction 

1. Open Status on Device 1 (message receiver) and Device 2 (message sender)
2. Enable notifications on Device 1
3. In case if Device 1 is Android: turn on Remote notifications (Profile => Notifications => Remote notifications toggle ON) 
4. Device 1 starts chat with Device 2
5. Close Device 1 
6. Send message form Device 1 to Device 2 in order to generate PN on Device 1
7. Open chat containing new message on Device 1
8. Pay attention if PN disappeared after reading message on Device 1
 

#### Actual behavior
PN remains uncleared

#### Expected behavior
PN is cleared 

### Additional Information

- Status version: nightly 
- Operating System: Android(with remote notifs ON), iOS

[comment]: # (Please, add logs/notes if necessary)

https://user-images.githubusercontent.com/97245802/161277859-a257e2f4-a828-4e95-9aa6-7b8eec9b06a9.mp4

[geth.log](https://github.com/status-im/status-react/files/8398304/geth.log)

**Comment by Parveshdhull** [comment]
hi @pavloburykh, as remote push notifications don't have information about the sender, we don't know which notifications belong to opened chat.
one thing we can do is clear all notifications on opening any chat. Will that work?

**Comment by Parveshdhull** [comment]
Also fixing some other issues related to notifications. Adding all here for reference:
(Should I also create a separate issue?)
### Updated Scope:
- [x] Clear all remote notifications on opening any chat
- [x] Clear user local notifications(for one-to-one chat) when a user is blocked
- [x] Clear user local notifications(for one-to-one chat) when a user's chat is deleted
- [x] Clear community chat notifications when leaving the community or Mark read 
- [x] Remove notifications from the activity center when leaving the community or Mark read 
- [x] Clear group chat notifications when leaving the group or Mark read 
- [x] Remove notifications from the activity center when leaving the group or Mark read

**Comment by pavloburykh** [comment]
> hi @pavloburykh, as remote push notifications don't have information about the sender, we don't know which notifications belong to opened chat. one thing we can do is clear all notifications on opening any chat. Will that work?

Hi @Parveshdhull For now, clearing all notifications on opening any chat might be fine solution. Although, if to look in perspective, there is a feature request https://github.com/status-im/status-react/issues/11715 about showing a content of remote PNs. 
So, my question is:
1. Is it theoretically possible in future to implement a feature request about showing a content of remote PNs (described here https://github.com/status-im/status-react/issues/11715)?
2. If it is possible, then current clearing all notifications on opening any chat might not be best solution after implementation of feature about showing a content of remote PNs. Please, share your opinion on that @Parveshdhull ? 
3. So, will we be able in future to somehow solve issue of clearing PNs after reading the exact messages those PNs belong to? Or it's totally impossible even in case of refactoring or re-implementation of remote notifications?

**Comment by pavloburykh** [comment]
> Also fixing some other issues related to notifications. Adding all here for reference: (Should I also create a separate issue?)
> 
> ### Updated Scope:
> * [x]  Clear all remote notifications on opening any chat
> * [x]  Clear user local notifications when a user is blocked
> * [x]  Clear user local notifications when a user's chat is deleted
> * [x]  Clear community chat notifications when Mark all read pressed in community
> * [x]  Remove notifications from the activity center when Mark all read pressed in community
> * [x]  Clear community chat notifications when a user leaves the community
> * [x]  Remove notifications from the activity center when a user leaves the community

@Parveshdhull thank you for your great work! Regarding separate issues, I think it's totally up to you.

**Comment by Parveshdhull** [comment]
> Is it theoretically possible in future to implement a feature request about showing a content of remote PNs

I think it is possible, but it will be tricky. We need to make sure that the app handles remote notifications delivery instead of the system, so we can decrypt those notifications(somehow) and deliver with content.

> If it is possible, then current clearing all notifications on opening any chat might not be best solution after implementation of feature about showing a content of remote PNs.

As we don't have any timeline on feature implementation, I think we can keep this clearing of all remote notifications on opening any chat for now so that the user's notification center doesn't get cluttered.

> So, will we be able in future to somehow solve issue of clearing PNs after reading the exact messages those PNs belong to? Or it's totally impossible even in case of refactoring or re-implementation of remote notifications?

Once we find the solution of delivering encrypted notifications, I think clearing will not be an issue
