### ISSUE TITLE
Chat commands button is missing when using ropsten

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-react#13259]
# Bug Report

## Problem 

When the network is ropsten, the button for the chat commands is missing, though the functionality itself still seems to work

#### Expected behavior

![IMG_5793](https://user-images.githubusercontent.com/176720/162620833-ae3cda43-fe96-4457-81f4-b07bb240ea64.PNG)

#### Actual behavior

![IMG_5792](https://user-images.githubusercontent.com/176720/162620837-9321b6fb-e89e-4656-95b1-74dcd9053460.PNG)

### Reproduction

1) Open Status
2) go to profile -> advanced -> network and choose ropsten
3) login again and open a 1 on 1 chat

### Additional Information

- Status version: 1.19.0 
- Operating System: iOS

**Comment by churik** [comment]
no, it is not missing. it is not working on Ropsten as intended on nightly or release builds, because it depends on VERIFY_TRANSACTION_CHAIN_ID param
Ropsten is enabled bu default on PR and e2e builds.
