### ISSUE TITLE
Unknown contact is automatically added to Contacts if re-launch app 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1325]
### Description

*Type*: Bug

*Summary*: After someone adds you to Contacts and sends a message there is new chat created with "Add to Contacts" link on the top. If you re-launch the app then this "unknown" contact is automatically added to your Contacts list. I expect that after app is re-launched there is same situation: unknown contact is not in my Contact list and there is "Add to contacts" link in the 1-1 chat 

#### Expected behavior
after app is re-launched there is same situation: unknown contact is not in my Contact list and there is "Add to contacts" link in the 1-1 chat 

#### Actual behavior
 If you re-launch the app then this "unknown" contact is automatically added to your Contacts list.

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7QTlnbzVkUlNxZE0
As contact A
- Open Status
- Add contact B to the Contacts and send "Hi" to B
As contact B:
- check there is new chat with contact A with "Add to contacts" link
- close app
- launch app
- check that contact A is not in Contacts (this is issue)
- check that 1-1 chat has no link "Add to contacts"

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment]
In progress
