### ISSUE TITLE
Yarn install not working due to rn-emoji-keyboard

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13269]
# Bug Report

**Original Report**: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10879#note_908604479

Our current fork of rn-emoji-keyboard is using `react-native-svg`: `^9.8.4`, and that is causing issues with `yarn install`, we should upgrade `react-native-svg` to  `^12.1.1`

## Problem 
[comment]: # (A problem description)

#### Expected behavior
`yarn install` should work

#### Actual behavior
`yarn install` not working

### Additional Information

- Status version: develop 
- Operating System: Linux

**Comment by jakubgs** [comment]
It would be good to include some of the errors we got in the issue for future reference:
```
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
src/EmojiPicker.tsx:52:12 - error TS2322: Type '{ children: Element; style: { height: AnimatedSubtraction; }[]; }' is not assignable to type 'IntrinsicAttributes & { hitSlop?: WithAnimatedValue<Insets | undefined> | undefined; onLayout?: WithAnimatedValue<((event: LayoutChangeEvent) => void) | undefined> | undefined; ... 53 more ...; key?: WithAnimatedValue<...> | undefined; } & { ...; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { hitSlop?: WithAnimatedValue<Insets | undefined> | undefined; onLayout?: WithAnimatedValue<((event: LayoutChangeEvent) => void) | undefined> | undefined; ... 53 more ...; key?: WithAnimatedValue<...> | undefined; } & { ...; }'.

52           <Animated.View
              ~~~~~~~~~~~~~

src/assets/Ban.tsx:5:4 - error TS2786: 'Svg' cannot be used as a JSX component.
  Its instance type 'Component<SvgProps, any, any>' is not a valid JSX element.

5   <Svg width="22" height="22" viewBox="0 0 22 22" fill="none">
     ~~~

src/assets/Ban.tsx:6:6 - error TS2786: 'Path' cannot be used as a JSX component.
  Its instance type 'Component<PathProps, any, any>' is not a valid JSX element.

6     <Path
       ~~~~
```
Full log: https://gist.github.com/jakubgs/7ffa6c414a0f65e98ef84c15c9f4d8c6

**Comment by Parveshdhull** [comment]
There is still a little confusion about why it happened, and why only in some instances. The issue looks like a new one, reported only 4 days ago.

**Issue 1:** https://github.com/react-native-svg/react-native-svg/issues/1741
**Issue 2:** https://github.com/facebook/react/issues/24304

Also, upgrading `react-native-svg` is fixing the issue. But if I use it as a local package like `yarn add file://home/User/rn-emoji-keyboard`, then these errors popup again.

**Comment by Parveshdhull** [comment]
Oh, they also mentioned why it might have happened in our case

> If you have issues but you did NOT upgrade to 18, or if you upgraded but get confusing errors from dependencies, the problem is likely that some library (incorrectly) specifies @types/react as a dependency with version * rather than an optional peer dependency. Find which library it is and file an issue for it. See https://github.com/facebook/react/issues/24304#issuecomment-1094565891 for diagnostics and common workarounds.

**Comment by Parveshdhull** [comment]
Ok, main question was why we are suddenly getting versions for dependencies, which are not compatible with the typescript and breaking build ([reference](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10879#note_906067192)) . I was trying to see what is different happening when I am trying local repo and got same `No lockfile found` log as fdroid. Not sure if this is issue with yarn or something

![image](https://user-images.githubusercontent.com/17097240/163028580-4a886576-0f8a-4b2a-ae0a-93817f5c98c4.png)
