### ISSUE TITLE
Failed to connect to go.googlesource.com port 443 after 75015 ms: Operation timed out

### ISSUE THREAD

**Issue by windswrold** [status-im/status-react#13279]
Hello
when i use 'sudo make run-ios'
report an error
npx react-native run-ios
Configuring Nix shell for target 'ios'...
these derivations will be built:
  /nix/store/6jz67s4izgvddhv96prfi15vyzamqmvl-gomobile.drv
  /nix/store/a4pmnbbj47vsw90yl1g67iyjkyxmjkf2-sdk-tools-darwin-4333796.zip.drv
  /nix/store/whwvkgi6y3aw9p5mv13xccrbrax7mx7v-platform-30_r03.zip.drv
  /nix/store/nqbdl014z1q58q4rcl86bp0khla31ckj-platforms-30.drv
  /nix/store/84j225ww3a1x9cvq8hn5228d7jq0644h-androidsdk.drv
  /nix/store/l973j2kd3yr90vdqvxxkl43hwiyz52vw-gomobile-unstable-2021-06-14-go-modules.drv
  /nix/store/5bynvjhiswk9c7iyfh1q98xfbf690y2n-gomobile-unstable-2021-06-14.drv
  /nix/store/1armknhnchn4gx2kzn7miwd0xxnm7lnm-status-go-0.92.4+hotfix.2-3df0ea5-ios.drv
building '/nix/store/6jz67s4izgvddhv96prfi15vyzamqmvl-gomobile.drv'...
exporting https://go.googlesource.com/mobile (rev 7c8f154d100840bc5828285bb390bbae1cb5a98c) into /nix/store/r7zip33r5jnc2vykz1rapnljc865z2lb-gomobile
已初始化空的 Git 仓库于 /nix/store/r7zip33r5jnc2vykz1rapnljc865z2lb-gomobile/.git/
fatal: 无法访问 'https://go.googlesource.com/mobile/'：Failed to connect to go.googlesource.com port 443 after 75015 ms: Operation timed out
fatal: 无法访问 'https://go.googlesource.com/mobile/'：Failed to connect to go.googlesource.com port 443 after 75002 ms: Operation timed out
fatal: 无法访问 'https://go.googlesource.com/mobile/'：Failed to connect to go.googlesource.com port 443 after 75003 ms: Operation timed out
Unable to checkout 7c8f154d100840bc5828285bb390bbae1cb5a98c from https://go.googlesource.com/mobile.
builder for '/nix/store/6jz67s4izgvddhv96prfi15vyzamqmvl-gomobile.drv' failed with exit code 1
cannot build derivation '/nix/store/5bynvjhiswk9c7iyfh1q98xfbf690y2n-gomobile-unstable-2021-06-14.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1armknhnchn4gx2kzn7miwd0xxnm7lnm-status-go-0.92.4+hotfix.2-3df0ea5-ios.drv': 1 dependencies couldn't be built
error: build of '/nix/store/1armknhnchn4gx2kzn7miwd0xxnm7lnm-status-go-0.92.4+hotfix.2-3df0ea5-ios.drv' failed
make: *** [run-ios] Error 1

**Comment by siddarthkay** [comment]
Hi @windswrold : For recreating this issue could you please specify the following : 
-> What version of nix is installed ?  ( you can find that out by `nix-env --version` )
-> What is your OS? ( linux,windows,mac ) and further which version of OS you received this error on ?
-> Do you get any errors when you run `make shell TARGET=ios` ?
-> Do you get any errors when you run `make run-clojure` ?
-> I hope you are running above 2 commands before you run `make run-ios`  ?
-> Do you get the same errors without `sudo` ? I believe you do not need to `sudo` before any make commands

**Comment by siddarthkay** [comment]
@windswrold : Looking at your error logs, It's probably the case that the url :  https://go.googlesource.com/mobile is being blocked by your ISP.
Could you confirm if this url https://go.googlesource.com/mobile opens up in the web browser of the machine you are trying to make the IOS build from ?

**Comment by jakubgs** [comment]
Yeah, looks like just connectivity issues that are unrelated to Nix. Have you tried opening https://go.googlesource.com/mobile in a browser or fetching it with `curl` to see if that works?

Also, please use [fenced code blocks with triple backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) when pasting logs/errors/code.

**Comment by siddarthkay** [comment]
Closing it for now, @windswrold : feel free to open this issue when you have more information on what I asked.
