### ISSUE TITLE
Implement Emoji Keyboard

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13271]
# Feature Issue

We need an emoji keyboard for creating thumbnails for the community channel. And for that, we are using the [fork](https://github.com/status-im/rn-emoji-keyboard) of [rn-emoji-keyboard](https://github.com/status-im/rn-emoji-keyboard), and modified it as per our design requirements. It will be great if we can implement this in the Clojure script instead of using this dependency.

Implementation should be mostly straightforward. We need to populate the flat list with emojis and filter them when searched, etc.

**Original Designs:** https://github.com/status-im/status-react/issues/12375

### Acceptance Criteria

Emoji keyboard should be implemented as a standalone component in the Clojure script, which we can embed in other screens if needed.

**Comment by cammellos** [comment]
Closing this for now as out of scope of MVP
