### ISSUE TITLE
Accept new chats from/See profile pictures from/Show profile pictures to settings are not synced on paired device if its values where not default before sync

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13284]
### Reproduction

1) Create or restore an account on Device 1
2) Restore the same account on Device 2 
3) On Device 2 change default values of Accept new chats from/See profile pictures from/Show profile pictures to settings
4) On Device 1 leave default settings
3) Pair Device 1 and Device 2 
4) Sync Device's 1 settings on Device 2 
5) Check if Devices 2 settings were changed to default values set on Device 1

#### Expected behavior
Device's 1 settings are synced on Device 2. 

#### Actual behavior
Device's 1 settings are synced on Device 2. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

https://user-images.githubusercontent.com/97245802/164041683-47ca18c3-0aef-4288-b028-a65e1ff7a92c.mp4

[geth_device2_ios.log](https://github.com/status-im/status-react/files/8514414/geth_device2_ios.log)
[geth_device1_android.log](https://github.com/status-im/status-react/files/8514416/geth_device1_android.log)

**Comment by rasom** [comment]
@pavloburykh technically settings on Device 2 were changed later than on Device 1, this means that everything works as expected. We don't force changes from device 1 if changes on device 2 had been made later.

**Comment by pavloburykh** [comment]
@rasom got it, thanx for the explanation. Closing issue.
