### ISSUE TITLE
Syncing of removal/adding to contacts of a blocked user doesn't work for paired devices

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13283]
# Bug Report
Removal and adding to contacts of blocked user is synced only for the first removal/add to contact actions on paired devices. Following attempts of removal and adding to contacts of blocked user are not synced. 

### Reproduction

1) Create or restore an account on Device 1
2) Restore the same account on Device 2 
3) Pair Device 1 and Device 2 
4) On Device 1 add any user to Blocked list (actual result: blocked user appears on Device 2)
5) Open profile of Blocked user on both Devices
6) Add blocked user to contacts on Device 1 (actual result: blocked user is added to contacts on Device 2)
7) Remove blocked user from contacts on Device 1 (actual result: blocked user is added to contacts on Device 1)
8) Once again add blocked user to contacts on Device 1

#### Actual behavior: 
Blocked user is NOT added to contacts on Device 2

#### Expected behavior
Blocked user is added to contacts on Device 2

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

https://user-images.githubusercontent.com/97245802/164024292-1675181b-9fc5-4fc6-8bd7-1c243d85dbf9.mp4

[geth_device_1.log](https://github.com/status-im/status-react/files/8513756/geth_device_1.log)

[geth_device_2.log](https://github.com/status-im/status-react/files/8513782/geth_device_2.log)

**Comment by rasom** [comment]
@pavloburykh @churik @cammellos 
Why do we allow to add the user to contacts without unblocking that user?

**Comment by churik** [comment]
It was this way from the start. I believe we can just disable that button if user is blocked
