### ISSUE TITLE
Network fee calculation stucks

### ISSUE THREAD

**Issue by ErrorEater** [status-im/status-react#13281]
When submitting transactions to a custom network the "Network fee" can not be calculated and waits forever.
![image](https://user-images.githubusercontent.com/8914034/163737539-03ed6d82-7df4-4467-9318-0e85790b16a2.jpeg)

**Comment by rasom** [comment]
[aliveli186](https://github.com/aliveli186) which custom network do you use, can you share the details?

**Comment by ErrorEater** [comment]
> [aliveli186](https://github.com/aliveli186) which custom network do you use, can you share the details?

Its my local Hardhat node with Ethereum mainnet fork. Chain Id: 31337. The node is accessible from internet.
This was working before, maybe after an update it started to stuck here.

If it is related with "eth_feeHistory" I think Hardhat has a problem with that request.

**Comment by churik** [comment]
Closing because of redesign / new wallet
