### ISSUE TITLE
Remove android remote push notifications

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13293]
We should remove android remote notifications and any google dependency so that play store & fdroid are the same build (minus signing). 
We need to try to see if referrals still works on that build.

**Comment by du82** [comment]
We just added this feature, why remove it on Android and keep it on iOS? I support keeping it 100% open source and removing the Google spookiness though

**Comment by cammellos** [comment]
@du64 thanks for the question, on Android we have another option (using a background service that does not depend on google dependencies, at the cost of keeping the app running all the times), while on IOS that's not possible, so we'd rather offer users an option instead of having none.

**Comment by jakubgs** [comment]
I think with this PR being merged also closes:

* https://github.com/status-im/status-react/issues/13266
