### ISSUE TITLE
JCenter Bintray Maven Repository Shutdown

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#13320]
Looks like [JCenter Bintray Maven Repository has shut down on 1st of May 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/):
```
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve status-im:status-go:4c05868.
     Required by:
         project :app > project :react-native-status
      > Could not resolve status-im:status-go:4c05868.
         > Could not get resource 'https://jcenter.bintray.com/status-im/status-go/4c05868/status-go-4c05868.pom'.
            > Could not GET 'https://jcenter.bintray.com/status-im/status-go/4c05868/status-go-4c05868.pom'.
               > Read timed out
```
Which was the way we fetched the Java-`status-go` glue package:
https://github.com/status-im/status-react/blob/1e8d85983e5b87b7645ad7064a4df2871159a04f/modules/react-native-status/android/build.gradle#L34

But we still refer to it in Gradle configuration:
https://github.com/status-im/status-react/blob/1e8d85983e5b87b7645ad7064a4df2871159a04f/android/build.gradle#L20
https://github.com/status-im/status-react/blob/1e8d85983e5b87b7645ad7064a4df2871159a04f/android/build.gradle#L65

**Comment by jakubgs** [comment]
In theory the Android part of the `react-native-status` node package should be built by Gradle automatically based on this line:
https://github.com/status-im/status-react/blob/1e8d85983e5b87b7645ad7064a4df2871159a04f/modules/react-native-status/android/build.gradle#L34
But for some reason some devs saw timeouts trying to fetch it from JCenter. No idea why, other than some weird caching.

**Comment by jakubgs** [comment]
There's a lot of references to `jcenter` in NodeJS modules we use:
```
 > ag -a 'jcenter()' | wc -l
63

 > ag -a 'jcenter()' | head -n 4
node_modules/@react-native-community/slider/android/build.gradle:4:    jcenter()
node_modules/@react-native-community/slider/android/build.gradle:34:  jcenter()
node_modules/@react-native-community/masked-view/android/build.gradle:9:      jcenter()
node_modules/@react-native-community/masked-view/android/build.gradle:47:  jcenter()
```

**Comment by audriu** [comment]
Maybe it is worth doing some host file aliasing for these?

**Comment by jakubgs** [comment]
Nah, this should not be necessary. Gradle should find in other repositories what's not available via JCenter.
