### ISSUE TITLE
Add `jq` to Nix configuration

### ISSUE THREAD

**Issue by audriu** [status-im/status-react#13322]
# Problem

rebasing status-go changes run some git hooks that depend on `jq` package but it is not present in the current Nix configuration and therefore requires manual installation.

**Comment by yqrashawn** [comment]
@jakubgs  Is this still relevant. I saw there's `jq` in default shell https://github.com/status-im/status-mobile/blob/6fa1729384407a477c9f8d6e92c561d25a820b2e/nix/shell.nix#L16

**Comment by jakubgs** [comment]
Yes, `jq` is already part of Nix shell. Not sure what this issue is about.
```
 > make shell
Configuring Nix shell for target 'default'...

[nix-shell:~/work/status-mobile]$ which jq
/nix/store/q4rjxagxikpsbvir0clyxk24rn2wckgg-jq-1.6-bin/bin/jq
```

**Comment by audriu** [comment]
I just tested and the nix shell has JQ indeed but when committing something with 'status-go-version.json' changes a git hook requires JQ. Is there a way to use the nix env inside the hook's script? Or would it be too long to wait until it starts? Maybe it is good enough as it is and contributors has to bring their own JQ. As it is installed only once...

**Comment by jakubgs** [comment]
Hmmmm, one possibility is using `nix-shell` in a shebang:
https://nixos.wiki/wiki/Nix-shell_shebang

But it is possible that it might make the hook startup a bit slower. I'd have to check and compare.

**Comment by jakubgs** [comment]
Another option is to use something common like `grep` instead of `jq`, making it a bit less predictable, but portable.
