### ISSUE TITLE
App crashes on enabling history nodes which were previously disabled and user made relogin (e2e blocker)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13333]
Currently this this bug was caught only by e2e test and we failed reproduce it manually on physical device. 

### Steps performed by e2e test

1) Create new multiaccount
2) Open Profile tab - Sync settings - Status nodes
3) Switch off (disable) "Use history node" toggle
4) Open Chats tab
5) Join public chat (e.g. #status)
6) Send some message in public chat
7) Perform manual logout and relogin
8) Open Profile tab - Sync settings - Status nodes
9) Switch on (enable) "Use history node" toggle

#### Actual behavior
App crashes

#### Expected behavior
History nodes are enabled

### Additional Information

- Status version: nightly 
- Operating System: Android
- build for e2e https://status-im-nightlies.ams3.digitaloceanspaces.com/StatusIm-Mobile-220506-055900-5e9738-nightly-x86.apk

geth log is attached 

[Link to video of reproduction during e2e](https://app.saucelabs.com/tests/84766d1cf2ca491e9edc69be75396b86?auth=e1721bc28a0bcf9d7646b5cb18754b3d#155)

[link to Testrail with failed test run](https://ethstatus.testrail.net/index.php?/tests/view/2712532)
[test_profile_disable_use_history_node_geth1.log](https://github.com/status-im/status-react/files/8641764/test_profile_disable_use_history_node_geth1.log)

**Comment by churik** [comment]
Failed test: 702287


https://user-images.githubusercontent.com/4557972/174104140-96ee3211-a458-4774-bef0-a6b5434d3755.mp4

**Comment by churik** [comment]
Closing because of redesign / new wallet
