### ISSUE TITLE
Long time (5-15 sec) for loading chat messages

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13355]
# Bug Report

## Problem 
Originally reported by user (discussion is [here](https://discord.com/channels/624205794384281629/704741763729850529/967599448559611975))
According to the discussion, the 1-1 chat takes significant time (5-15 sec) to render the messages if the chat was re-entered by navigating back from the home screen (the app was upgraded from 1.18).
Couldn't reproduce it.

#### Expected behavior
chat loads instantly

#### Actual behavior
5-15 sec

### Reproduction
**I didn't manage to reproduce it in 1-1 chat (20+ heavy audio, 50+ images)**
Video attached.

https://user-images.githubusercontent.com/4557972/168080620-a141eca7-9305-4b57-b2cd-510d5c9129c0.mp4

1) Open Status
2) Open 1-1 chat
3) Reopen app
4) Go back and select chat from home screen

### Additional Information

- Status version: release 1.19 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
it can be replicated on the application with lots of messages (~90k messages)

times on a slow android device

```
wakuext_chatMessages 141.55900000035763ms
wakuext_emojiReactionsByChatID 1293.7240000069141ms (~1.2sec)
wakuext_chatPinnedMessages 1286.5460000038147ms (~1.2sec)
wakuext_markAllRead 1133.9249999970198ms (~1.2sec)
```

EDITED: it seems like sometimes methods "waiting" to be sent in batch, so most likely here `emojiReactionsByChatID` and. `chatPinnedMessages` "waiting" for  `markAllRead`, because `markAllRead` always shows this time, but other two sometimes shows ~50-80ms

**Comment by flexsurfer** [comment]
wakuext_markAllRead 1133.9249999970198ms (~1.2sec)

```go
Exec(`UPDATE user_messages SET seen = 1 WHERE local_chat_id = ? AND not(seen) AND clock_value <= ? AND not(mentioned)`, chatID, clock)

Exec(`UPDATE user_messages SET seen = 1 WHERE local_chat_id = ? AND not(seen) AND clock_value <= ? AND mentioned`, chatID, clock)

Exec(`UPDATE chats
	SET unviewed_message_count =
	(SELECT COUNT(1)
	FROM user_messages
	WHERE local_chat_id = ? AND seen = 0),
	unviewed_mentions_count =
	(SELECT COUNT(1)
	FROM user_messages
	WHERE local_chat_id = ? AND seen = 0 AND mentioned),
               highlight = 0
WHERE id = ?`, chatID, chatID, chatID)
```

**Comment by flexsurfer** [comment]
wakuext_emojiReactionsByChatID 1293.7240000069141ms (~1.2sec)

```go
query := fmt.Sprintf(`
	SELECT
	    e.clock_value,
	    e.source,
	    e.emoji_id,
	    e.message_id,
	    e.chat_id,
	    e.local_chat_id,
	    e.retracted
	FROM
		emoji_reactions e
	WHERE NOT(e.retracted)
	AND
	e.local_chat_id = ?
	AND
	e.message_id IN
	(SELECT id FROM user_messages m WHERE NOT(m.hide) AND m.local_chat_id = ? %s
	ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m.clock_value, -64, 64) || m.id DESC LIMIT ?)
	LIMIT 1000
`, cursorWhere)
		```

**Comment by flexsurfer** [comment]
wakuext_chatPinnedMessages 1286.5460000038147ms (~1.2sec)

```go
db.db.Query(
		fmt.Sprintf(`
			SELECT
				%s,
				pm.clock_value as pinnedAt,
				pm.pinned_by as pinnedBy,
				substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id as cursor
			FROM
				pin_messages pm
			JOIN
				user_messages m1
			ON
				pm.message_id = m1.id
			LEFT JOIN
				user_messages m2
			ON
				m1.response_to = m2.id
			LEFT JOIN
				contacts c
			ON
				m1.source = c.id
			WHERE
				pm.pinned = 1
				AND NOT(m1.hide) AND m1.local_chat_id IN %s %s
			ORDER BY cursor DESC
			%s
		`, allFields, "(?"+strings.Repeat(",?", len(chatIDs)-1)+")", cursorWhere, limitStr),
		args..., // take one more to figure our whether a cursor should be returned
	)
	```

**Comment by flexsurfer** [comment]
it seems like sometimes methods "waiting" to be sent in batch, so most likely here `emojiReactionsByChatID` and. `chatPinnedMessages` "waiting" for  `markAllRead`, because `markAllRead` always shows this time, but other two sometimes shows ~50-80ms

**Comment by flexsurfer** [comment]
so at first we need to improve `markAllRead`

**Comment by flexsurfer** [comment]
```go
func (db sqlitePersistence) MarkAllRead(chatID string, clock uint64) error {
	tx, err := db.db.BeginTx(context.Background(), &sql.TxOptions{})
	if err != nil {
		return err
	}
	defer func() {
		if err == nil {
			err = tx.Commit()
			return
		}
		// don't shadow original error
		_ = tx.Rollback()
	}()

	start := time.Now()

	seenResult, err := tx.Exec(`UPDATE user_messages SET seen = 1 WHERE local_chat_id = ? AND not(seen)`, chatID)
	if err != nil {
		return err
	}

	seen, err := seenResult.RowsAffected()
	if err != nil {
		return err
	}

	elapsed := time.Since(start)
	log.Printf("UPDATE user_messages %s took %s - %d", chatID, elapsed, seen)

	return nil
}
```

**Comment by flexsurfer** [comment]
in code above we have only one query `UPDATE user_messages SET seen = 1 WHERE local_chat_id = ? AND not(seen)`

it updates 0 rows, so nothing to update, but it still takes 600ms, although `EXPLAIN QUERY PLAN UPDATE user_messages SET seen = 1 WHERE local_chat_id = ? AND not(seen) ` shows that index is used 
`SEARCH TABLE user_messages USING INDEX seen_local_chat_id_idx (local_chat_id=?)`

**Comment by churik** [comment]
Able to reproduce this issue with [this DB](https://drive.google.com/file/d/1kaaBYkZH3018vh_H801vdFGNnuY-EIAf/view?usp=sharing):
Data:
- 5 public chats with 20k messages each
- one 1-1 chat with 20k messages
- 200 contacts

Seed phrase:
`midnight skirt eight display earn moment remain lava arrange visual topple clip`
Instruction on how to import DB is [here](https://notes.status.im/yJMuhPAGT5inXa9Zb4vMZw)

https://user-images.githubusercontent.com/4557972/171413509-ebda0c26-c75e-4a14-a71a-3ab666d57ec3.mp4
