### ISSUE TITLE
iOS builds failing due to missing or invalid auth credentials

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#13352]
@flexsurfer identified an issue with PR builds which manifests in the Build stage of iOS app:
```
[10:38:20]: Authentication credentials are missing or invalid.
  - Provide a properly configured and signed bearer token, and make sure that it has not expired.
    Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```
https://ci.status.im/job/status-react/job/prs/job/ios/view/change-requests/job/PR-13351/3/console

It appears this issue can be reproduces consistently.

**Comment by jakubgs** [comment]
And it appears other PRs are affected as well:
https://ci.status.im/job/status-react/job/prs/job/ios/view/change-requests/job/PR-13349/2/console

**Comment by jakubgs** [comment]
My first through was that this might be an expired iOS certificate, but this already happened in December last year:

* https://github.com/status-im/status-react/issues/12967

And the new expiry dates are in January of 2023:
```
16:09:22  +-------------------+------------------------------------------------------------+
16:09:22  |                             Installed Certificate                              |
16:09:22  +-------------------+------------------------------------------------------------+
16:09:22  | User ID           | DTX7Z4U3YA                                                 |
16:09:22  | Common Name       | Apple Distribution: STATUS HOLDINGS PTE. LTD. (DTX7Z4U3YA) |
16:09:22  | Organisation Unit | DTX7Z4U3YA                                                 |
16:09:22  | Organisation      | STATUS HOLDINGS PTE. LTD.                                  |
16:09:22  | Country           | US                                                         |
16:09:22  | Start Datetime    | 2022-01-03 14:53:46 UTC                                    |
16:09:22  | End Datetime      | 2023-01-03 14:53:45 UTC                                    |
16:09:22  +-------------------+------------------------------------------------------------+
```
And the errors do not match either.

**Comment by jakubgs** [comment]
This issue appears to be related:

* https://github.com/fastlane/fastlane/issues/19072

But the comments talk about increasing duration. Which I assume refers to the argument for `app_store_connect_api_key`:

>Key | Description | Default
>-- | -- | --
>duration | The token session duration | 500

https://docs.fastlane.tools/actions/app_store_connect_api_key/#parameters

**Comment by jakubgs** [comment]
Though there is something to that, since the error happens shortly after this line:
```
11:44:14  [10:44:13]: Creating authorization token for App Store Connect API
```

**Comment by jakubgs** [comment]
Our `duration` is already extended to 1200 seconds:
https://github.com/status-im/status-react/blob/b83fe64b0f1bbfc5c453ef3eb8c7d04ad42d0bed/fastlane/Fastfile#L98-L109

**Comment by jakubgs** [comment]
There is also a discussion related to this issue:

* https://github.com/fastlane/fastlane/discussions/18100

And aside from also mentioning changing `duration` they mention this PR:

* https://github.com/fastlane/fastlane/pull/19502

Which apparently fixed issues with `UnauthorizedAccessError` errors due to expired session token that needs to be refresh and session creation retried. It was included in `2.205.2`, which we are already using:
https://github.com/status-im/status-react/blob/b83fe64b0f1bbfc5c453ef3eb8c7d04ad42d0bed/fastlane/Gemfile.lock#L69

**Comment by jakubgs** [comment]
I attempted to lower the session duration just to see what happens:

* https://github.com/status-im/status-react/pull/13353

But no, that fails the exact same way.

**Comment by jakubgs** [comment]
The original issue and PR in which we switched to using Apple Store Connect API were:

* https://github.com/status-im/status-react/issues/11713
* https://github.com/status-im/status-react/pull/11714
* https://github.com/fastlane/fastlane/issues/18098

It might be that the key might have to be re-generated.

**Comment by jakubgs** [comment]
When I logged into https://appstoreconnect.apple.com/ with our auto account I got:

![image](https://user-images.githubusercontent.com/2212681/168055180-402eecc6-8787-4f0f-b7cb-98f7e5aa036b.png)

Which MIGHT be the reason for this issue.

**Comment by jakubgs** [comment]
And indeed, if I log in as the holder I can see there's a new "Paid Applications agreement":

![image](https://user-images.githubusercontent.com/2212681/168056378-dee07e1a-29ab-4f3b-86e0-261f4d5513f1.png)

**Comment by rborn** [comment]
I still have this with the last version

- updated fastlane to 2.205.2
- cleaned Gemfile.lock and installed again
- tried to set duration to 500
- checked for any agreement that needs to be signed, all clear for me

❤️

**Comment by jakubgs** [comment]
I accepted the agreement:

![image](https://user-images.githubusercontent.com/2212681/168069677-b3358428-e3be-4711-8ede-f6a4df94a640.png)

Though it still complains about "banking information". No idea what that's about, since out app is free.

**Comment by jakubgs** [comment]
Looks like it didn't help, fails the same way:

https://ci.status.im/job/status-react/job/prs/job/ios/view/change-requests/job/PR-13351/5/

**Comment by ghost** [comment]
We are experiencing the same issue. Also on the latest `2.205.2`.

**Comment by jakubgs** [comment]
I've opened an issue with fastlane, as it appears to be affecting other users of Fastlane and this way it will get more attention:

* https://github.com/fastlane/fastlane/issues/20270

**Comment by jencircj-developer** [comment]
It seems App Store connect API is down now. You can see the status of Appstore connect API here https://developer.apple.com/system-status/

I am getting the same above error repeatedly in my iOS pipeline as well in my local machine. Probably the issue will be fixed when Appstore connect API comes back online. Guess the API was down from yesterday. Also i am experiencing same problem when i try to login to Appstore connect account and view the App's page in the website.

**Comment by jakubgs** [comment]
Good point, I checked that site earlier on but it didn't have that update yet:

![image](https://user-images.githubusercontent.com/2212681/168076852-ec7e6132-f534-4315-aec3-7b867905150a.png)

**Comment by odanu** [comment]
Have had my first green build. Looks like this time again, it was the issue on Apple side.

**Comment by jakubgs** [comment]
Looks like it's recovering, this is the first build that passed:

https://ci.status.im/job/status-react/job/prs/job/ios/view/change-requests/job/PR-13351/6/

**Comment by jencircj-developer** [comment]
AppStore connect issue issue still exists, Apple has now updated the right issue and it's status as in attached screenshot
<img width="540" alt="Screenshot 2022-05-12 at 5 00 29 PM" src="https://user-images.githubusercontent.com/38936017/168093332-b9e517b6-88ca-4d10-89b8-3a3f53d293b4.png">

**Comment by jakubgs** [comment]
Yeah, took them a while.

**Comment by jencircj-developer** [comment]
Getting the same error today also although Apple mentioned the status as resolved. I am getting error's with in pipeline builds and even with official Appstore connect website. Anybody else facing the same problem today?

**Comment by Spejbl** [comment]
> Getting the same error today also although Apple mentioned the status as resolved. I am getting error's with in pipeline builds and even with official Appstore connect website. Anybody else facing the same problem today?

Yeah, we are experiencing the same. App Store Connect seems to have another ongoing issue today.

![image](https://user-images.githubusercontent.com/17637244/168257715-ca0a0065-e421-4a34-b019-3ecd3f435a5a.png)

**Comment by jakubgs** [comment]
@JencirJamal our nightly build worked fine, and ran another one manually and that worked fine too.

From our perspective it's mostly recovered. And at least we know the cause is Apple, and not our setup.
