### ISSUE TITLE
No transaction history is fetched on mainnet (release 1.19) 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13361]
# Bug Report

## Problem 
Can't see token balances and tx history on release 1.19 (mainnet)
From 3 attempts two times balance wasn't fetched, and transaction history was not fetched at all.

#### Expected behavior
can see balance

#### Actual behavior
![IMAGE 2022-05-16 16:07:16](https://user-images.githubusercontent.com/4557972/168611470-e6853232-5c31-4c4c-b1df-bae386aeaef4.jpg)

### Reproduction

1) Open Status
2) Restore multiaccount with funds

### Additional Information

- Status version: release 1.19 
- Operating System: Android, iOS
[geth.log](https://github.com/status-im/status-react/files/8700727/geth.log)
[Status.log](https://github.com/status-im/status-react/files/8700728/Status.log)

[comment]: # (Please, add logs/notes if necessary)
[geth.log](https://github.com/status-im/status-react/files/8700797/geth.log)
[Status.log](https://github.com/status-im/status-react/files/8700798/Status.log)

**Comment by churik** [comment]
сс @cammellos

**Comment by flexsurfer** [comment]
```
t=2022-05-16T14:22:06+0000 lvl=eror msg="controlCommand error" error="403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":36,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to archive state\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}}" counter=1
```

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/168621277-3221b197-7f65-47ae-944a-66b51c3601b8.png)

**Comment by flexsurfer** [comment]
fixed by adding archive node addon
