### ISSUE TITLE
Implement toggle to show the new UI

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13370]
As a developer/designer
I want to have a toggle in advanced that shows the new UI
So it's easier to showcase and receive feedback

### Description

We should have a toggle in advanced that shows the new UI.
One method proposed by @Parveshdhull is to change the root to show the new UI https://github.com/status-im/status-react/blob/7991bbe95807d166a11955870dc5a2abbfd68a75/src/status_im/navigation/core.cljs#L175 

The value does not have to be remembered, enabled in session only (i.e until logout), is fine.

cc @flexsurfer what do you think?

**Comment by flexsurfer** [comment]
not sure about root, we need to change `:component` in `status-im.ui.screens.screens`
