### ISSUE TITLE
App freezes until relogin if open and close the 'Share image' bottom sheet twice (iOS only)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13381]
# Bug Report

## Problem 
The Status app freezes until relogin when opening and closing the `Share` bottom sheet (in the long-press menu in chat view) twice or after the second sharing an image to some app.
Sometimes the issue is reproducible on the first try. 

#### Expected behavior
The app doesn't freeze

#### Actual behavior

https://user-images.githubusercontent.com/67952253/169512832-1d925ee0-d6a5-454f-a115-ea18846654bb.MP4

### Reproduction

1. Open a 1-1 chat
2. Send an image
3. Long press on the image > tap `Share`
4. Tap somewhere on the screen to close the bottom sheet
5. Long press on the image > tap `Share` > close the bottom sheet again
6. Try to interact with the app

### Additional Information

- Status version: nightly 20/05
- Operating System: iOS

cc @jo-mut

**Comment by jo-mut** [comment]
I have not been able to reproduce this. Maybe it is because I am using an emulator instead of a real device. Did you test  it on a real device? Seems to work just fine

**Comment by qoqobolo** [comment]
> Did you test it on a real device?

@jo-mut  Yes, that's on real devices. Tested on iPhone SE and 12 mini
