### ISSUE TITLE
Request is not accepted when using Select - Accept and add button from Activity center 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13397]
follow up #13054 

**Important:** The same with "Reject and delete" button in the activity center: it does not result in declining contact request.  

**Steps:**
1) User A sends contact request to User B
2) User B open the Activity center
3) User B tap `Select`
4) User B select new chat
5) User B tap Reject and delete
6) User B - add User A to contacts and open 1-1 chat 

**Actual result:** User B can send messages to User A. For User A `Pending` contact request is still shown,  they are unable to send messages (the message input field is missing) 

https://user-images.githubusercontent.com/4557972/169350378-d158bd1f-fc47-46d8-8a2a-86d21506187e.mp4

**Comment by churik** [comment]
Closing because of redesign
