### ISSUE TITLE
Hide invitation link to group chats

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13399]
It was decided to deprecate the invitation link for group chats.

For now, we should just hide the link in group chats so that 1.20 users will not be using it, but we maintain all the functionalities so it's backward compatible.

To reproduce:
add some contacts,
create a group chat with them,
go to the group chat,
click on the dots on the top,
group info,
Group invite,
and you should see the group invite link,
we want to remove the group invite link, but not the rest (so that the admin will still be able to accept pending requests)

**Comment by du82** [comment]
Why was this deprecated? It's a very useful feature, especially with the client mods that allow for groups with hundreds of users.

Groups are a great tool if you just want a simple chat with a few other people, without the complexity of channels and categories.
