### ISSUE TITLE
Value from contact request is duplicating in chat input after accepting it

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13400]
follow up #13054 

**Prerequisites:** mutual CR (contact request) is enabled for  User1 and User2 

**Steps:**
- User1: send CR
- User2: accept it from AC 

**Expected result:** chat input field is empty for User1

**Actual result:** CR text is in chat input field

![IMAGE 2022-05-25 15:22:55](https://user-images.githubusercontent.com/4557972/170272315-52ddb46b-5991-4f1e-8a61-e044493cced6.jpg)

**Comment by churik** [comment]
Closing because of redesign / new wallet
