### ISSUE TITLE
"Accepted" CR are not erased from AC when opening 1-1 chat with accepted CR

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13407]
follow up #13054 

"Accepted" CR are not erased from AC when opening 1-1 chat with accepted CR. So they need to be manually accepted/rejected from AC.

**Prerequisites:** mutual CR (contact request) is enabled for  User1 and User2 

**Steps:**
- User1: send CR
- User2: accept it from AC 
- User1: open chat with User1 from chat list

**Expected result:** no more messages in AC

**Actual result:** "Accepted" CR still in AC until a manual tap on it or accept/reject. This issue is reproducible for both users regardless if it is sender or receiver. If chat is opened NOT through activity center - "Accepted" CR will remain in AC until it is deleted manually. 

Video from perspective of User 1

https://user-images.githubusercontent.com/97245802/170478396-f0de17fa-ab18-44e4-86ae-61f1d77bfbd8.mp4

**Comment by churik** [comment]
Can't be done in new flow, not relevant anymore
