### ISSUE TITLE
Can use mentions in contact request field but markdown/links are not resolved

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13401]
follow up #13054 

**Prerequisites:** mutual CR (contact request) is enabled for  User1 and User2 

**Steps:**
- User1: send CR with links, markdown, and mention

**Expected result:** no mentions, markdown/links are resolved as in ordinary message (**assumption**)

https://user-images.githubusercontent.com/97245802/170452105-6321d323-ae2e-4e9e-bea3-0f2f83cb0f96.mp4

**Comment by churik** [comment]
Closing because of redesign
