### ISSUE TITLE
Can not tap on pending CR to see the full text

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13403]
follow up #13054 

**Steps**
1) D1 sends CR to D2
2) D2 opens activity center 
3) D2 taps on pending CR trying to open it and see the full text

**Actual result:** can not tap on pending CR to see the full text

**Expected result:** can tap on pending CR to see the full text

https://user-images.githubusercontent.com/97245802/170455801-4985ef38-4e8b-4923-8c64-cfbc3b466915.mp4

![Monosnap 2022-05-25 15-30-18](https://user-images.githubusercontent.com/4557972/170274240-1cd3be65-43b0-47e2-9be2-b82e663d7550.png)

**Comment by churik** [comment]
Closing because of redesign
