### ISSUE TITLE
Accepting CR from User2 generates a message in AC about accepted CR from User1 on User1 device

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13404]
follow up #13054 

**Prerequisites:** mutual CR (contact request) is enabled for  User1 and User2 

**Steps:**
- User1: send CR
- User2: accept it from AC 

**Expected result:** "Accepted" in both AC; for the sender it is evident that it is his CR (outgoing) was accepted;

**Actual result:** for sender CR it is not apparent is it incoming or outgoing CR which is accepted

https://user-images.githubusercontent.com/97245802/170459569-2bfa65ba-37e9-4026-8bd6-b99d84446632.mp4

**Comment by churik** [comment]
Closing because of redesign
