### ISSUE TITLE
Can't see the previous history if was removed from contacts

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13408]
follow up #13054 

**Prerequisites:** mutual CR (contact request) is enabled for  User1 and User2 

**Steps:**
- User1: send CR
- User2: accept it from AC; exchange several messages
- User2: remove User1 from contact
- User1: check chat with User2
**Expected result:** can see the previous history  with User 2 + welcome message to resend CR
**Actual result:** no way to see the previous history 

**IMPORTANT** [here is](https://user-images.githubusercontent.com/4557972/170281156-a73b73c6-64e8-4954-b75c-6d3018f0fdf0.mp4) one way to unblock chat input if you still have "Accepted" CR in AC. It is an issue that shouldn't be available after fixing ISSUE #13407

**Comment by churik** [comment]
Closing because of redesign
