### ISSUE TITLE
ETH balance is not retrieved from the connected chain thus transaction fee can not be paid

### ISSUE THREAD

**Issue by ErrorEater** [status-im/status-react#13411]
```
iPhone;
App version: 1.19.0 (20220328123004)
App comit: d6a6c41dd3ff06b057d2226644583ef57e7347da
Node version: StatusIM/v0.97.3/ios-arm64/go1.16.9
```

When a DApp is connected to a custom chain the native coin balance (ETH balance) is not retrieved from that chain and shows as zero even if there is a balance.
In wallet page it also shows zero. Maybe it checks the balance from the main Ethereum chain.
Anyway, due to that zero balance issue transactions can not be signed (no fee to pay).

Related with: https://github.com/status-im/status-react/issues/13281

![WhatsApp Image 2022-05-26 at 4 06 11 PM](https://user-images.githubusercontent.com/8914034/170495518-f44f7f17-d584-4d04-8436-c8874c8359bd.jpeg)
![WhatsApp Image 2022-05-26 at 4 06 15 PM](https://user-images.githubusercontent.com/8914034/170495533-5c938fdd-b7d8-435f-8c74-bd442c3ec98c.jpeg)

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
