### ISSUE TITLE
Add possibility to accept/decline incoming CR from existing chat 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13410]
### User Story

As a user, I want to be able to accept/decline CR directly from existing 1-1 chat so that I don't have to do it by opening AC or sending a counter CR from exiting chat (in case if I have enabled CR in Settings). 

# Feature Issue
**Case 1:**  both Users enabled CR. Users are not contacts. There is an existing 1-1 chat between users in chat list. 

**Steps:** 
1) User 1 send CR to User 2
2) User 2 opens existing 1-1 chat
3) User 2 wants to accept or to decline CR without opening AC. 

**Actual results:** User 2 is shown "Send Contact Request" button.  He can accept CR by sending a counter CR. But sending CR to user who has already sent you his CR (and by that in fact already added you to contacts) does not make a big sense. And still, there is no way to decline CR from chat. 

**Expected result:**
Pending CR is shown instead of "Send Contact Request" button. Accept/Decline buttons are located under Pending request. 

**Case 2:**  User 1 (sender) has enabled CR, User 2 (receiver) disabled CR. Users are not contacts. There is an existing 1-1 chat between users in chat list. 

**Steps:** 
1) User 1 send CR to User 2
2) User 2 opens existing 1-1 chat
3) User 2 wants to accept or to decline CR without opening AC. 

**Actual results:** User 2 is shown Pending request. There is no possibility neither to decline nor to accept it from chat.  

**Expected result:**
Accept/Decline buttons are located under Pending request in 1-1 chat.

**Comment by cammellos** [comment]
Closing as this will be done as part of new designs
