### ISSUE TITLE
Migrate Wallet Connect to Rc-2

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13429]
WalletConnect Beta phase is over.
Latest Release Candidate guide is present here : https://docs.walletconnect.com/2.0/javascript/guides/react-native

**Comment by qfrank** [comment]
i'll look into this :) @flexsurfer

**Comment by qfrank** [comment]
Hi @flexsurfer , when i update `"@walletconnect/client": "^2.0.0-beta.23"` to `"@walletconnect/sign-client": "^2.0.0-beta.100"` , i couldn't make status startup normally, error log:
```
[Fri Aug 12 2022 18:27:54.915]  ERROR    ReferenceError: Property 'TextEncoder' doesn't exist, js engine: hermes
[Fri Aug 12 2022 18:27:54.915]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
```
i'm not good at this, so i think i should leave this opportunity to other talents :)

**Comment by flexsurfer** [comment]
@briansztamfater any thoughts?

**Comment by siddarthkay** [comment]
I'll try this out @flexsurfer

**Comment by siddarthkay** [comment]
> [Fri Aug 12 2022 18:27:54.915]  ERROR    ReferenceError: Property 'TextEncoder' doesn't exist, js engine: hermes
> [Fri Aug 12 2022 18:27:54.915]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes

I was able to recreate this error.

The migration docs here : https://gist.github.com/pedrouid/1a36c6a8776e49453838578ec84715e6 mention that we have to explicitly also install the following dependency : `@react-native-async-storage/async-storage` 
we however have a different version of Async Storage in our `package.json`  : `@react-native-community/async-storage`

It is clear that these 2 dependencies can not co-exist in our codebase, I'll do more research on this to find the best way forward.

**Comment by siddarthkay** [comment]
it seems like `@react-native-community/async-storage` is deprecated and we should get rid of its usage/bindings in our code and replace with `@react-native-async-storage/async-storage` instead.


![Screenshot 2022-08-19 at 2 34 30 PM](https://user-images.githubusercontent.com/64726664/185585318-4d44907f-ef0c-4054-b366-401e08af9fa4.png)

**Comment by siddarthkay** [comment]
> it seems like `@react-native-community/async-storage` is deprecated and we should get rid of its usage/bindings in our code and replace with `@react-native-async-storage/async-storage` instead.

Addressing that here https://github.com/status-im/status-mobile/pull/13846

**Comment by cammellos** [comment]
Closing for now, we will re-open as we'll be ready to work on it
