### ISSUE TITLE
Invalid phone number error is shown for valid Mexican phone number

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1342]
### Description

*Type*: Bug
Entering valid Mexican phone number returns Invalid phone number error
Phone format: +526641xxxxxx and +526611xxxxxx
I've checked the number in Twillo and it looks like a valid (country code MX is returned and no errors)
![lookup2](https://user-images.githubusercontent.com/6584810/27224246-bf543624-529c-11e7-87d3-7034bf72c6e9.png)

Team members can use Instabug report to see full number: 
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/chats/398
* https://dashboard.instabug.com/applications/status/beta/bugs/273

*Summary*: 

#### Expected behavior
Phone number can be entered 
#### Actual behavior

Invalid phone number error is shown if enter valid Mexican number
### Reproduction

- Open Status
- Open Console
- send /phone command with Mexican phone number

### Additional Information
* Status version: 0.9.9
* Operating System:  
Android  OS Level 23 
Device: samsung SM-A720F

**Comment by janherich** [comment]
@annadanchenko I debugged the functionality and found the cause of the bug. 
When the function `status-im.utils.phone-number/valid-phone-number?` is called with `"+526641xxxxxx"` string (replace x with decimal digits), it's correctly identified as an valid Mexican phone number, but of the `:fixed-line` type, and the functions treats only phone numbers of type `:mobile`, `:fixed-line-or-mobile` and `:pager` as valid. 

That actually makes sense, as only those devices can display the confirmation code sent from the app, but the message is still very confusing (the number is certainly not invalid per se) and it would be nice to actually provide some more descriptive error message to the user, something like `"the number you entered is fixed-line, only mobile and pager phone numbers are supported"`.

I can implement it, if we agree on it. 

The second thing which is quite strange is that twillo API identified the number as `:mobile`, while the library used by the project (`awesome-phonenumber`, which is just wrapping google's `libphonenumber`) identified the number as `:fixed-line`, I need to dig deeper to find out why that's the case.

**Comment by annadanchenko** [comment]
Phone feature is removed
