### ISSUE TITLE
Sometimes e2e results are not posted in PR

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13430]
# Bug Report

## Problem 
Sometimes we face a situation when the test run is completed, but the results fail to publish in the PR.
Example: https://github.com/status-im/status-react/pull/13420
Testrun: https://ethstatus.testrail.net/index.php?/runs/view/9300&group_by=cases:section_id&group_order=asc (tests are marked as `untested`)
Job: https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/1613/
Error: 
```
Got TestRail error when adding results: 
{'error': 'Field :results cannot be empty (one result is required)'}
```

#### Expected behavior
E2e results are posted in PR

#### Actual behavior
No results; tests are stuck in pending state in GH
 
<img width="580" alt="Screenshot 2022-05-30 at 17 44 23" src="https://user-images.githubusercontent.com/67952253/171025906-c1c11104-d188-417b-b3d4-44c59f4864ae.png">

### Note
Workaround: rebuild the e2e (x86) build and rerun tests

**Comment by qoqobolo** [comment]
Another case: in this PR https://github.com/status-im/status-react/pull/13427 tests failed at the start with the same error when I tried to rerun them 
```
Got TestRail error when adding results: 
{'error': 'Field :results cannot be empty (one result is required)'}
```

https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/1630/

https://ethstatus.testrail.net/index.php?/runs/view/9327&group_by=cases:section_id&group_order=asc

But rerun helped.

<img width="920" alt="Screenshot 2022-06-01 at 11 02 59" src="https://user-images.githubusercontent.com/67952253/171368345-b18a5f78-39b7-48bb-8723-07b2fc646378.png">

**Comment by churik** [comment]
More examples: https://ci.status.im/job/status-react/job/e2e/job/status-app-prs/2589/console

**Comment by churik** [comment]
![2 (2)](https://user-images.githubusercontent.com/4557972/178725598-08fce11d-c14f-4888-a91e-1f7e8f461f98.png)
![1 (2)](https://user-images.githubusercontent.com/4557972/178725605-1706de64-0cc2-4fcf-8e38-d32238a7eed1.png)

**Comment by churik** [comment]
not relevant for now, will reopen if still the case
