### ISSUE TITLE
App crashes if tap forward/back buttons [Android 4.4.2]

### ISSUE THREAD

**Issue by svetak0tleta** [status-im/status-react#1344]
[comment]: # (Please replace ... with your information. Remove < and >)
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Synchronization was completed.  Cant repeat the bug after reinstall.
When trying to open link by using browser command, browser has white screen. 
If you tap "forward" or "back" button, app will crash (Video 1)
If you tap "close" button, browser will be closed. Reusing browser command after that will open the link. (Video 2)
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Link opens correctly the first time
#### Actual behavior
[comment]: # (Describe what actually happened.)
When using browser command link first time, browser has white screen.
 app crashes if tap forward/back buttons

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
[Crash](https://drive.google.com/open?id=0B8KdjOyX8mFbWlFFaHBCUXNuWnMxNG5mRnFlOHY1QUhPN1Bv)

[Work after tapping "close" button](https://drive.google.com/open?id=0B8KdjOyX8mFbcG5RVGNzUW10YWxtREVoQkg1ZjRvYU4zUkVZ)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9
* Operating System: Android 4.4.2

#### Logs
[comment]: # (if on Android please replicate bug whilst running adb logcat)

[log.txt](https://github.com/status-im/status-react/files/1092343/log.txt)

**Comment by annadanchenko** [comment]
will not fix after setting limit of OS to lowes Android 6.9 in #4651
