### ISSUE TITLE
Missing documentation regarding the use of status-im in rooted devices.

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [status-im/status-react#13445]
There is a popup saying "Your phone appears to be ROOTED, by pressing CONTINUE you understand and accept the risks in using this software.", however I can't find any documentation on the risks of using status-im on a rooted device. Would it be possible to document this somewhere? Preferably by putting a link on said popup.

**Comment by flexsurfer** [comment]
thank you for the question, but it's not about the status app, if you ROOT your phone you should be already aware of the risks related to this

**Comment by M-i-k-o-t-o** [comment]
It was not a question but rather an observation regarding missing pieces of documentation as multiple people in a chat that I am in mentioned that they got spooked by this popup and were avoiding status-im because they were unsure as to what it meant. I would expect the documentation to address at least the following:
- Whether there are any risks regarding the use of status-im specifically on a rooted device
- The risks involved with rooted phones
- Why this popup exists if having a rooted phone has nothing to do with Status
