### ISSUE TITLE
Close all switcher tabs

### ISSUE THREAD

**Issue by du82** [status-im/status-react#13447]
We should have the option to close all tabs in the switcher, similar to WeChat and Mixin Messenger.
Closing two dozen tabs is much easier with one tap than repeatedly spamming the close button.

![Screenshot_20220602-172507_Mixin](https://user-images.githubusercontent.com/65834069/171748514-7e95fbc3-cc53-4723-a16c-07788ebb28f9.png)

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app.

The label `recheck` is added in order to keep an eye on it while testing this part of the new design.
