### ISSUE TITLE
Audio message gets stuck in pending state until reopening chat view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13454]
# Bug Report

## Problem 
The delivery status of audio messages is stuck in a pending state (`...`) until reopening the chat (relevant for 1-1 chats, community channels, and group with members). After reopening, it's marked as `sent` or `delivered`, as expected. 
In the case of a group chat, the issue is only reproducible for groups with joined members, i.e. if you create a group chat with no members and send an audio message, it'll be marked as `sent`. 

#### Expected behavior
The delivery status is updated without reopening the chat

#### Actual behavior

https://user-images.githubusercontent.com/67952253/172349367-6db427f6-8ca9-47a5-b315-0c495d620c63.MP4

### Reproduction

1. Start a 1-1 chat
2. Send an audio message
3. Reopen the chat

### Additional Information

- Status version: nightly 7/06
- Operating System: Android, iOS

[geth.log](https://github.com/status-im/status-react/files/8852118/geth.log)
[Status.log](https://github.com/status-im/status-react/files/8852119/Status.log)

**Comment by Parveshdhull** [comment]
> The delivery status of audio messages is stuck in a pending state (...)

same behavior is also happening for emoji messages
