### ISSUE TITLE
Implement React Native Reanimated V2

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13452]
_Research issue for the implementation of react-native-reanimated v2_

# Summary:
Currently we are only using reanimated v1 API's and only version is bumped in `package.json`. We should Implement and use React Native Reanimated v2, at-least for newer animations for redesign.

## Project Setup:
Configure project as per v2 [installation guidelines](https://docs.swmansion.com/react-native-reanimated/docs/2.1.x/installation#android) and import API's.

### Issue 1:
[useAnimatedStyle](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle) hook is one of the main element of reanimated v2. But when we use this hook like:
```
(reanimated/use-animated-style (fn [] #js {:width 100}))
```
It throws [error](https://github.com/software-mansion/react-native-reanimated/issues/1090):
```
Cannot convert undefined value to object
```
Screenshot:
<img src="https://user-images.githubusercontent.com/17097240/172066924-7198b297-4aa6-489d-86ad-f1e8a466000d.png" alt="Screenshot" height="400"/>

this error is only shown in the older version, like `2.1.0`, `2.2.0`, etc. newer versions don't show errors due to [this](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/src/reanimated2/hook/useAnimatedStyle.ts#L412) check, but the app just crashes with these logs

```
06-05 01:21:19.812 12779 12779 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Tried to synchronously call function {G__75911} from a different thread.
06-05 01:21:19.812 12779 12779 F DEBUG   : 
06-05 01:21:19.812 12779 12779 F DEBUG   : Occurred in worklet location: /home/parvesh_monu/Desktop/ArchFiles/React/status-react/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (492:18)
06-05 01:21:19.812 12779 12779 F DEBUG   : 
06-05 01:21:19.812 12779 12779 F DEBUG   : Possible solutions are:
06-05 01:21:19.812 12779 12779 F DEBUG   : a) If you want to synchronously execute this method, mark it as a Worklet
06-05 01:21:19.812 12779 12779 F DEBUG   : b) If you want to execute this method on the JS thread, wrap it using runOnJS
06-05 01:21:19.812 12779 12779 F DEBUG   :   at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)
```

### Cause
This error occurs because `useAnimatedStyle` expects [worklet](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets) as an argument ([ref](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle#updater-function)), while we are just passing a simple function.

While setting project we are also adding [react-native-reanimated/plugin](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin), which is supposed to convert the passed argument to `worklet` automatically ([ref](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/plugin.js#L7)), which is not happening for us.

### Issue 2
There is also another way to create [worklet](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets) for reanimated v2. Using directives

```
function someWorklet(greeting) {
  'worklet';
  console.log("Hey I'm running on the UI thread");
}
```
This will also not work for clojure script, because even if I add "worklet" string, something like
```
(defn someWorklet [greeting]
    "worklet"
    (js/console.log "Hey I'm running on the UI thread"))
```
compiler will strip it out. It seems [react-native-reanimated/plugin](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin) is more tailored toward javascript syntax and not working in cljs.

There is also a babel [plugin](https://www.npmjs.com/package/babel-plugin-assign-directive) available for using directive in cljs, but unfortunately it don't work in shadow-cljs.

### Possible Solutions
1. One workaround can be to not rely on directive and the library can just provide a function to manually create worklets. Function is already there just not yet completely implemented ([ref](https://github.com/software-mansion/react-native-reanimated/issues/3131)). One drawback of this is we have to maintain fork branch for the implementation for now, because even if change gets merged in parent, we can't use that because after version `2.4.0`, latest versions of library needs gradlePluginVersion=4.2.2 and gradle 6.
2. Create or fix plugin so that directive also work for shadow-cljs. (?)

### Related Refs:
- [Original Issue](https://github.com/software-mansion/react-native-reanimated/issues/1090)
- [Stackoverflow Question](https://stackoverflow.com/questions/72500152/interop-how-to-use-javascript-directive-in-clojurescript)
- [Issue Comment](https://github.com/software-mansion/react-native-reanimated/issues/1090#issuecomment-1146681621)

**Comment by flexsurfer** [comment]
there is reanimated 3 is coming, so worth waiting and use it

**Comment by Parveshdhull** [comment]
Yes, [Reanimated 3](https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7) looks great. But I think we have to skip using this for now.
> Reanimated 3 will no longer include support for legacy Reanimated 1 API

And also it will most probably will require higher versions of gradle and gradle plugin.
(We should look into upgrading them, they are becoming blocker for several upgrades now)

**Comment by Parveshdhull** [comment]
Another solution:  https://stackoverflow.com/a/72513996/7475429

**Comment by Parveshdhull** [comment]
> Another solution: https://stackoverflow.com/a/72513996/7475429

So, I tried creating a separate Javascript file as mentioned in [stackoverflow](https://stackoverflow.com/a/72513996/7475429) answer for the "worklets" and the app still crashed with the same error. I tried both with or without "directive" keyword and both time crashed.

 For testing purposes, I created a simple react-native project, and with "directive" it worked but without it crashed with the exact error as above.

So, I think in shadow-cljs project adding directives not working even in the js file. Maybe the working of babel plugin not only affected by file type but also by project type.

**Comment by Parveshdhull** [comment]
The real magic behind the conversion of a regular function to a `worklet` is being handled by [makeWorklet](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/plugin.js#L337) function of the reanimated plugin. Maybe we can directly implement this function in cljs?

**Comment by flexsurfer** [comment]
https://stackoverflow.com/questions/72500152/how-to-use-reanimated-worklet-directive-in-clojurescript

**Comment by flexsurfer** [comment]
i feel like all that reanimated stuff doesn't feet well clojurescript, a lot of interop, hooks hacks etc, so probably we should find a way how we could do it in plain js ?

**Comment by flexsurfer** [comment]
i believe @chrispader had all these issues here https://github.com/status-im/status-react/pull/13386 , would be great to hear his opinion

**Comment by flexsurfer** [comment]
probably we could do all animation code in js and just pass cljs components (views ) as a parameter (child)

**Comment by flexsurfer** [comment]
actually, i feel like we need to move quo2 in the separate library in plain js, so we'll have syles, components, and all animations in the separate js library, so other js devs could work on it and use it in their projects, wdyt ?

**Comment by Parveshdhull** [comment]
> actually, i feel like we need to move quo2 in the separate library in plain js, so we'll have syles, components, and all animations in the separate js library, so other js devs could work on it and use it in their projects, wdyt ?

We are just using `react-native` components and polishing with styles as per our use case, I am not sure how much it will be useful for other projects. 

I guess it will be somewhat easy for new contributors to contribute, but still not sure if it is worth it.

**Comment by Parveshdhull** [comment]
> Another solution: https://stackoverflow.com/a/72513996/7475429

Using Javascript file for storing `worklet directives` worked.
Problem was for importing `js` file, I was using `:require` and file was being processed by `shadow-cljs` and directive didn't worked. But after using `js/require` file first went through metro and `directive` worked.

**Comment by Parveshdhull** [comment]
> > Another solution: https://stackoverflow.com/a/72513996/7475429
> 
> So, I tried creating a separate Javascript file as mentioned in [stackoverflow](https://stackoverflow.com/a/72513996/7475429) answer for the "worklets" and the app still crashed with the same error. I tried both with or without "directive" keyword and both time crashed.
> 
> For testing purposes, I created a simple react-native project, and with "directive" it worked but without it crashed with the exact error as above.
> 
> So, I think in shadow-cljs project adding directives not working even in the js file. Maybe the working of babel plugin not only affected by file type but also by project type.

Using Javascript file for storing `worklet directives` worked.
Problem was for importing `js` file, I was using `:require` and file was being processed by `shadow-cljs` and directive didn't worked. But after using `js/require` file first went through metro and `directive` worked.

**Comment by chrispader** [comment]
Extracting animations completely to a separate JS lib could be tricky i guess...

@Parveshdhull how did you manage to create worklets within CLJS now?

I was generally also struggling with using hooks within ClojureScript. Is there some elegant way of doing this?

**Comment by chrispader** [comment]
Especially reanimated-v2 hooks.

**Comment by Parveshdhull** [comment]
> Extracting animations completely to a separate JS lib could be tricky i guess...

I don't think we need to extract whole animations. We are only facing problems with `worklets` (because of directives),  so I think we should only create them in the `js`. 

> how did you manage to create worklets within CLJS now?

[[WIP]: Use reanimated v2 for switcher animations](https://github.com/status-im/status-react/pull/13470)

> I was generally also struggling with using hooks within ClojureScript. Is there some elegant way of doing this?

By default, the reagent will convert hiccup vectors into class components, while Hooks only work with functional components. You can find more details on how to create a Functional component in CLJS in this reagent Doc. https://github.com/reagent-project/reagent/blob/master/doc/ReactFeatures.md#function-components

**Comment by Parveshdhull** [comment]
After implementing `worklet` in javascript file animating components styles is working without any issues.

But for [Layout Animations](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/layout_animations) the app is crashing with the error ["Trying to resolve view with tag ## which doesn't exist"](https://github.com/software-mansion/react-native-reanimated/issues/3011) which is known issue and fixed in [PR:2982](https://github.com/software-mansion/react-native-reanimated/pull/2982) and fix released in [2.5.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.5.0
)

This error only occurs in version 2.4.0, because of PR ([Changed default ViewState](https://github.com/software-mansion/react-native-reanimated/pull/2802)).

Currently for making Layout Animations work without upgrading to 2.5.0, I downgraded library to 2.3.0 and enabled layout animations manually, by calling 
```
enableLayoutAnimations(true);
```
We need to enable this manually to properly render layouts because of PR [Disable by default layout animation](https://github.com/software-mansion/react-native-reanimated/pull/2651)

(This is temporary workaround, we should upgrade library to 2.5.0 or higher)

**Comment by Parveshdhull** [comment]
### Upgrade to react-native-reanimated 2.5.0

After upgrading to react-native-ranimatied to 2.5.0, it is giving error
```
* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Could not resolve all artifacts for configuration ':react-native-reanimated:classpath'.
   > Could not find com.android.tools.build:gradle:4.2.2.
```
Thanks to script `add_package.sh` created by @jakubgs in https://github.com/status-im/status-react/pull/13455, this error gets fixed but another error pops up  while calling `make run-android` (originally reported by @flexsurfer)

```
* What went wrong:
Could not determine the dependencies of task ':react-native-reanimated:mergeDebugNativeLibs'.
> com.android.builder.sdk.InstallFailedException: Failed to install the following SDK components:
      cmake;3.6.4111459 CMake 3.6.4111459
  The SDK directory is not writable (/nix/store/3vckfk09zy450m1kz5k1cdggh0555ik4-androidsdk-mod-sdk)
```
> Above logs copied from @flexsurfer's message on discord, because I am unable to reproduce this error second time due to another error, given below

I also tried calling `sudo chown -R $(whoami) $ANDROID_HOME` but that didn't helped.

Also, while calling `add_package.sh` second time, this error shows, (not sure if it is due to my chown command or something else)

```
[nix-shell:~/Desktop/ArchFiles/React/status-react]$ nix/deps/gradle/add_package.sh com.android.tools.build:gradle:4.2.2
Regenerating Nix files...
./gradlew: line 25: exec: gradle: not found
```

> Reproduction Steps:
> - yarn add react-native-reanimated@2.5.0
> - nix/deps/gradle/add_package.sh com.android.tools.build:gradle:4.2.2
> - make run-android

**Comment by jakubgs** [comment]
1. The `The SDK directory is not writable` is just a warning, it's irrelevant.
2. The `chown` on `ANDROID_HOME` has no meaning since `/nix/store` permissions are unchangeable.
3. The actual error is about `cmake;3.6.4111459`. The cmake version we use, have nave used for a long time is:
    https://github.com/status-im/status-react/blob/62a3ed6138e1f86b55863e16a694a2a629e39f7f/nix/pkgs/android-sdk/compose.nix#L15
4. Lack of gradle can just mean you were in the wrong kind of shell, like `default` shell instead of `android` or `gradle` shells.

**Comment by Parveshdhull** [comment]
Hi @jakubgs, yes using `make shell TARGET=android` fixed the 4th issue, but even after changing cmakeVersion to `3.6.4111459` in `status-react/nix/pkgs/android-sdk/compose.nix`, it still giving same error

**Comment by jakubgs** [comment]
You shouldn't be changing the cmake version. Also, why would a newer version of `react-native-reanimated` require much older version of cmake? Makes no sense to me. That error looks like you fucked up `nix/deps/gradle` in some way and that cause the Nix shell to become incomplete in some way.

I ran `make nix-update-gradle` myself on your `fix/use-reanimated-v2-for-switcher-animations` branch and it worked fine, and I also built an Android APK using `make release-android` without issues.

**Comment by flexsurfer** [comment]
i should admit, that this happens only when you use new script `add_package.sh`, if add gradle version manually it works fine

**Comment by Parveshdhull** [comment]
> I ran `make nix-update-gradle` myself on your `fix/use-reanimated-v2-for-switcher-animations` branch and it worked fine, and I also built an Android APK using `make release-android` without issues.

`fix/use-reanimated-v2-for-switcher-animations` is currently using reanimated version `2.3.3`, that's why no errors.

### Error Reproduction step:
- yarn add react-native-reanimated@2.5.0
- make shell TARGET=android
- nix/deps/gradle/add_package.sh com.android.tools.build:gradle:4.2.2
- make run-android

**Comment by jakubgs** [comment]
Heh, that can't work my dude, look at this table:

Plugin version | Required Gradle version
-- | --
3.4.0 - 3.4.3 | 5.1.1+
3.5.0 - 3.5.4 | 5.4.1+
3.6.0 - 3.6.4 | 5.6.4+
4.0.0+ | 6.1.1+
4.1.0+ | 6.5+
__4.2.0+__ | __6.7.1+__
7.0 | 7.0+
7.1 | 7.2+
7.2 | 7.3.3+

https://developer.android.com/studio/releases/gradle-plugin

You can't use Gradle plugin `4.2.2` with Gradle version 5:
https://github.com/status-im/status-react/blob/78033eedc983e3e2d425e2182d4e94943f21f1e3/nix/overlay.nix#L36
I'd expect @flexsurfer to know this already :D.
