### ISSUE TITLE
Switcher button covers text

### ISSUE THREAD

**Issue by du82** [status-im/status-react#13451]
I know this was in the design concepts, but having the switcher icon right in the middle wastes space and makes it hard to see whatever is under it, such as text.

It would be neat to see the button in the top bar, or triggered by a long press of the back arrow.

![Screenshot_20220604-195803_Status PR](https://user-images.githubusercontent.com/65834069/172030578-2989fc7e-cd89-4f2e-b37d-22eb2f7fa3ff.png)

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app and the switcher is not a part of it anymore.
