### ISSUE TITLE
Audio is not recorded in audiomessages sent from IOS devices with connected bluetooth headphones

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13467]
Reproduced on iPhone X, IOS 14.1 with connected Airpods Pro/Galaxy Buds headphones. Reproducible on release 1.19/nightly 
Audio messages are sent with no sound. 

**Steps:**
1. Connect bluetooth headphones to iOS device
2. Login multiaccount
3. Start 1-1 chat 
4. Record and send an audiomessage while headphones are connected to iPhone
5. Play the audio
6. Pay attention if sound has been recorded

**Actual result:** 
Sound has not been recorded, silent audio messaage is sent

**Expected result:**
Audio has been recorded. 

### Additional Information

- Status version: release 1.19/nightly 
- Operating System: iOS 14.1, 15.5
- Device: iPhone X, iPhone 12 mini
- Headphones device: Airpods Pro/Airpods/GalaxyBuds

Logs from release build is attached. 
[geth.log](https://github.com/status-im/status-react/files/8868418/geth.log)

**Comment by churik** [comment]
Also reproducible on IPhone12 Mini with Airpods.

**Comment by flexsurfer** [comment]
we use `@react-native-community/audio-toolkit` but it seems it's not maintained anymore https://github.com/react-native-audio-toolkit/react-native-audio-toolkit

**Comment by churik** [comment]
descoped for now
