### ISSUE TITLE
Unused translations

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13469]
Translations that are not used in 'src/status_im', 'components/src', 'src':
{
    "community-image-delete",
    "looking-for-cards",
    "give-permissions-camera",
    "allow-and-send",
    "approve-token-contract-desc",
    "wallet-connect-go-back",
    "dapp-starter-pack-description",
    "contacts-descr",
    "transaction-signed",
    "try-keeping-the-card-still",
    "invite-warning",
    "wallet-manage-app-connections",
    "membership-invite-description",
    "invite-receive-account",
    "follow-your-interests",
    "invite-reward-friend-name",
    "enter-watch-account-address",
    "describe-channel",
    "ok-save-pass",
    "community-info-not-found",
    "about-sharing-data",
    "advertiser-title",
    "welcome-blank-community-message",
    "invite-public-chat-intro",
    "invite-chat-name",
    "invite-reward-friend",
    "view-rules",
    "invite-reward-you",
    "how-it-works",
    "invite-chat-accept-join",
    "optimal",
    "view-public-dashboard",
    "membership-ens",
    "invite-reward-friend-description",
    "invite-chat-rule",
    "invite-chat-intro",
    "data-collected-subtitle",
    "expand-all",
    "invite-instruction-fourth",
    "invite-chat-accept",
    "invite-reward-you-name",
    "invite-chat-starter-pack",
    "invite-instruction-third",
    "wallet-connect-proposal-description",
    "data-collected",
    "remove-from-contacts-text",
    "dapp-starter-pack-title",
    "advertiser-description",
    "enter-recipient-address-or-username",
    "ens-dismiss-message",
    "lost-connection",
    "invite-reward",
    "fetch-timeline",
    "buy-crypto-description",
    "starter-pack-received-description",
    "redeem-success",
    "starter-pack-coming-description",
    "advertiser-starter-pack-description",
    "safe-estimate",
    "membership-ens-description",
    "advertiser-starter-pack-accept",
    "remote-notifications",
    "redeem-now",
    "contact-request-header",
    "rpc-usage-get-stats",
    "group-invite-link",
    "invite-public-chat-home",
    "http-gateway-error",
    "community-roles",
    "thank-you",
    "what-is-shared",
    "community-invite-title",
    "buy-crypto-title",
    "redeem-amount",
    "no-thanks",
    "wallet-connect-app-connected",
    "invite-privacy-policy-public",
    "ens-username-owned-continue",
    "attribution-received",
    "remote-notifications-subtitle",
    "starter-pack-received",
    "reduced-tip",
    "help-improve-status",
    "invite-chat-pending",
    "community-color-placeholder",
    "tap-card-again",
    "invite-reward-you-description",
    "rearrange-categories",
    "invite-select-account",
    "notifications-switch",
    "advertiser-starter-pack-title",
    "add-to-contacts-text",
    "load-more-timeline",
    "invite-instruction-second",
    "invite-instruction-first",
    "membership-invite",
    "invite-instruction-fifth",
    "dapp-starter-pack-accept",
    "starter-pack-coming",
    "join-a-community",
    "advertiser-starter-pack-decline",
}
Translations to recheck usage:
[
    "invite-privacy-policy2",
    "sharing-data-desc-5",
    "wallet-connect-2.0",
    "sharing-data-desc-1",
    "sharing-data-desc-6",
    "invite-privacy-policy1",
    "sharing-data-desc-4",
    "sharing-data-desc-3",
    "sharing-data-desc-2",
]

**Comment by churik** [comment]
cc @flexsurfer @jinhojang6

**Comment by cammellos** [comment]
Closing for now, until ready to work on
