### ISSUE TITLE
User is automatically deleted from contacts if they were deleted by their contact

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13465]
# Bug Report

## Problem 
If DeviceA and DeviceB are contacts, and DeviceA deletes DeviceB from contacts, then DeviceA will be automatically deleted from contacts on DeviceB as well.

_Mutual contact requests are disabled._

#### Expected behavior
DeviceA is not deleted from contacts on DeviceB

#### Actual behavior
DeviceA is deleted from contacts on DeviceB

### Reproduction

1. Create UserA and UserB
2. UserA adds UserB to contacts and starts 1-1 chat
3. UserB opens the chat in the activity center and adds UserA to contacts
4. UserB removes UserA from contacts
5. Check UserA

### Additional Information

- Status version: nightly 8/06
- Operating System: Android, iOS

cc @cammellos it looks like a `Mutual contact request` regression. Could you please confirm that this is **not** expected behavior for the time being?

**Comment by cammellos** [comment]
@qoqobolo yes, definitely a regression, it should only happen if you have contact requests enabled. I'll take a look.
