### ISSUE TITLE
White screen instead of camera if  try to scan address in Wallet and no permissions to camera were given before

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1347]
### Description

*Type*: Bug

*Summary*: White screen without camera is shown when try to scan address from the Wallet If app has no access to camera.
![screenshot_20170618-145038](https://user-images.githubusercontent.com/6584810/27260517-bb3302b4-5436-11e7-8384-d46400690a5d.png)

#### Expected behavior
Ask user to provide access to camera. If access is provided then camera is shown and it's possible to scan QR code. If access not provided (same as on scan QR for contact) -> ask again to provide access.
#### Actual behavior
White screen with no camera

### Reproduction
Prerequisites: 
1. no permissions were given to the app to access camera (or re-install app if permissions were given)
2. you need to have some ETH in the Wallet

Steps:
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7YnJrN3VjY1Q3d2c
- Open Status 
- Open Wallet
- Under "Send ETH" type 0.1 and tap on SEND
- In Contacts screen, tap on Scan QR. Check that camera can be used to scan QR code

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/693 Same issue but other error in the log:  
[log19.log.txt](https://github.com/status-im/status-react/files/1083078/log19.log.txt)

* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/751 Same issue but different error in the log: 
[log18.log.txt](https://github.com/status-im/status-react/files/1083081/log18.log.txt)

* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/781

* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/788 Similar issue (no camera but different issue in the log). According to answer from Instabug user the steps to enable camera access by using "scan QR for contact" do not help. It might be other issue to log separately.

* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/649

### Logs
[log20.log.txt](https://github.com/status-im/status-react/files/1083056/log20.log.txt)

```
06-18 14:50:27.271  3072 21754 W ServiceManager: Permission failure: android.permission.CAMERA from uid=10200 pid=10571
06-18 14:50:27.271  3072 21754 E CameraService: Permission Denial: can't use the camera pid=10571, uid=10200
06-18 14:50:27.271 10571 10571 W CameraBase: An error occurred while connecting to camera: 0
06-18 14:50:27.271 10571 10571 E RCTCamera: acquireCameraInstance failed
06-18 14:50:27.271 10571 10571 E RCTCamera: java.lang.RuntimeException: Fail to connect to camera service
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.hardware.Camera.<init>(Camera.java:568)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.hardware.Camera.open(Camera.java:405)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.lwansbrough.RCTCamera.RCTCamera.acquireCameraInstance(RCTCamera.java:41)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.lwansbrough.RCTCamera.RCTCamera.<init>(RCTCamera.java:440)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.lwansbrough.RCTCamera.RCTCamera.createInstance(RCTCamera.java:34)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.lwansbrough.RCTCamera.RCTCameraView.<init>(RCTCameraView.java:30)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.lwansbrough.RCTCamera.RCTCameraViewManager.createViewInstance(RCTCameraViewManager.java:22)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.lwansbrough.RCTCamera.RCTCameraViewManager.createViewInstance(RCTCameraViewManager.java:12)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:912)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:884)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.view.Choreographer.doFrame(Choreographer.java:628)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.os.Handler.handleCallback(Handler.java:739)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.os.Looper.loop(Looper.java:158)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-18 14:50:27.271 10571 10571 E RCTCamera: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by yenda** [comment]
Cannot reproduce on Android device One Plus 3 is this issue still relevant ?

**Comment by asemiankevich** [comment]
I can't reproduce it in latest develop
