### ISSUE TITLE
IOS app receives push notifications for outgoing messages sent from same account by another paired devices

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13479]
# Bug Report
IOS app receives push notifications when messages are sent from same account by another paired device

Preconditions: Device 1 (IOS), Device 2 (IOS or Android)
**Steps:**

1. Restore same account on Device 1 and Device 2 
2. Pair Device 1 and Device 2 
3. Start 1-1 or group chat on any device
4. Sent some messages from Device 2 
5. Open notification bar on Device 1
6. Pay attention at notifications on Device 1 

**Actual result:** push notifications appear on Device 1 after sending messages from paired Device 2 

**Expected result:** notifications should not be received for outgoing messages. 

### Additional Information

- Status version: nightly 
- Operating System: iOS

Sorry for no logs attached, as this functionality is broken on IOS #13342 

On below video Device 1 (IOS) from the right side, Device 2 (Android) from the left 

https://user-images.githubusercontent.com/97245802/173533876-a7b8de8e-147c-45da-ac69-9dc5eb720715.mp4

**Comment by cammellos** [comment]
@pavloburykh I believe this has been fixed, closing now, @pavloburykh would you mind re-opening if that's not the case? 
Thank you

**Comment by pavloburykh** [comment]
> @pavloburykh I believe this has been fixed, closing now, @pavloburykh would you mind re-opening if that's not the case? Thank you

@cammellos hi! Reproducing the bug in latest nightly. I believe PR with fix has not been merged, as it is in Draft state https://github.com/status-im/status-react/pull/13485 Would you mind rebasing it and sending for re-test to E2E column? Thank you!
