### ISSUE TITLE
Sticker packs only synchronizes in real time

### ISSUE THREAD

**Issue by audriu** [status-im/status-react#13484]
# Bug Report

## Problem 
[comment]: # Sticker packs only synchronizes in real-time but not straight after the synchronization is enabled nor after device re-login.

#### Expected behavior
Devices synchronize stickers when sync is enabled in any direction. Sticker packs preserve even if synced one way or re-logged-in.

#### Actual behavior
Sometimes sticker pack gets overridden.

### Reproduction
https://github.com/status-im/status-react/pull/13358#issuecomment-1156164942

**Comment by churik** [comment]
Closing because of redesign
