### ISSUE TITLE
Emoji line that is not fully shown

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1349]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When i key in long text in input area, it's ok, haven't focus problems. but when i key in more than 3 lines of emojis , it can't display correctly. Emoji line that is not fully shown. i think got the focus | position's problem. It's not a good experience.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Emoji line that is fully shown.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Emoji line that is not fully shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click Chats Tab
- Chat with someone
- Textarea, if you input more than 3 lines with emoji , the four line emoji can't show fully.
![wechatimg148](https://user-images.githubusercontent.com/5856990/27434658-0cc4143a-578c-11e7-83e8-74f5da3b183b.png)
![wechatimg149](https://user-images.githubusercontent.com/5856990/27434659-0d0517b4-578c-11e7-9367-517e76910852.png)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9(1434)
* Operating System: IOS 10.3.2

**Comment by lukaszfryc** [comment]
I can't reproduce it in 0.9.20
