### ISSUE TITLE
Can not switch to xDai chain

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13493]
# Bug Report

## Problem 
The xDai now is[ Gnosis network ](https://www.anyblockanalytics.com/networks/xdai/) and an attempt to switch to the xDai chain got an error  'Network failed'
Blocker for part of e2e: 695890

#### Expected behavior
can switch to Gnosis network

#### Actual behavior
![IMAGE 2022-06-16 12:31:38](https://user-images.githubusercontent.com/4557972/174051641-c06ea2f4-8049-4357-9646-d3398800bdfa.jpg)

### Reproduction

1) Open Status
2) Go to Advanced > Network 
3) switch to xDai

### Additional Information

- Status version: nightly 16/06/2021
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
https://dai.poa.network/

`This site can’t be reached`

**Comment by flexsurfer** [comment]
```
POA Network is now part of the much larger Gnosis ecosystem with the completion of the token swap and merge from POA to STAKE (and STAKE to GNO, which will be finalized on 31 May 2022).
```

https://www.poa.network/poa-+-gnosis

**Comment by flexsurfer** [comment]
oh i see , its all in the description :)

**Comment by flexsurfer** [comment]
https://metamask.zendesk.com/hc/en-us/articles/360052711572-How-to-connect-to-the-Gnosis-Chain-network-formerly-xDai-

**Comment by flexsurfer** [comment]
https://rpc.xdaichain.com/  redirects to gnosis website, so its not valid rpc
