### ISSUE TITLE
Show profile picture of member of communities

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13505]
As a user
I want to see the profile pictures of other members of the community
So that I can recognize them more easily

### Description
If I join a community, I should see pictures of other members and share mine.

This needs to be implemented in status-go:

https://github.com/status-im/status-go/issues/2707

PR is out, we just need to make sure we integrate and it works as expected on mobile.

**Comment by qfrank** [comment]
I’d like to have a try :)

**Comment by du82** [comment]
I think there should be a way to hide your existence in a community. 
Discord scrapers commonly profile users and build relationship maps through the "Mutual Servers" feature which is impossible to opt-out of.

**Comment by rasom** [comment]
it is working in `develop` already
