### ISSUE TITLE
UI Component - Photo Row

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13514]
This issue is to track the creation of the component: **Photo Row**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3591%3A77287.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by yqrashawn** [comment]
new design link https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=5626-158270&t=dIRwzW7HfMjszZfY-4
