### ISSUE TITLE
Clearing the chat history when line is still shown in Chats 

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1351]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  When i cleared the someone chat history, but it is still shown content in Chats.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
it is shown empty content in Chats

#### Actual behavior
[comment]: # (Describe what actually happened.)
it is shown some contents in Chats
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click Chats Tab
- Chat with someone
- Clean the current chat history
- Back to Chats Tab

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9(1434)
* Operating System: IOS 10.3.2

**Comment by annadanchenko** [comment]
Issue happens in the Group and Public chats. Last received message is shown in Chats list after Clear History was used for the chat. Expected: "No messages" is shown in Chats list for the chat where history was deleted. If re-launch the app then expected "No messages" is shown.
1. Initial group chat content: 
![initial chat content](https://user-images.githubusercontent.com/6584810/27427934-44031de4-5749-11e7-9ac8-bf3d89c63d15.jpg)

2. Clear history is used for the chat:
![history deleted](https://user-images.githubusercontent.com/6584810/27427944-47e3c2ec-5749-11e7-8fb6-ff3469f9b31b.jpg)

3. Last received message is still shown in the Chats (issue):
![img_0408](https://user-images.githubusercontent.com/6584810/27427959-53278a8a-5749-11e7-8b63-1df7e98e3acf.jpg)

4. Expected:
![img_0413](https://user-images.githubusercontent.com/6584810/27428125-c8373244-5749-11e7-8af2-f5aeea4130b0.jpg)

**Comment by jeluard** [comment]
Fixed by #1353
