### ISSUE TITLE
UI Component - Message Drawer

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13521]
This issue is to track the creation of the component: **Message Drawer**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3289%3A67074.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by flexsurfer** [comment]
implemented here https://github.com/status-im/status-mobile/pull/13620
