### ISSUE TITLE
Number of group members shows incorrect number when reorder groups

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1352]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  When i  want to reorder  groups,  i found some number of group members shows incorrect number.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
shows correct number
#### Actual behavior
[comment]: # (Describe what actually happened.)
shows incorrect number
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click Contracts Tab
- Click "…"  and Edit
- Click 'Delete contact'
- Click "…" and Reorder groups

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9(1434)
* Operating System: IOS 10.3.2

**Comment by annadanchenko** [comment]
Issue happens after group member is deleted: 
1. On Contacts screen correct amount of members is shown after 1 member is deleted in DApps group,  Amount: 8 members:
![img_0401](https://user-images.githubusercontent.com/6584810/27426713-3953bede-5745-11e7-9907-2753185ad985.jpg)

2. On Reorder groups screen wrong amount of members is shown (amount before 1 member was deleted), Amount: 9 members:
![img_0400](https://user-images.githubusercontent.com/6584810/27426728-437f1462-5745-11e7-881e-10eef9eb9c89.jpg)

**Comment by annadanchenko** [comment]
Groups feature and Contacts tab are removed
