### ISSUE TITLE
UI Component - React

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13524]
This issue is to track the creation of the component: **React**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3161%3A67981.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by ibrkhalil** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33176106/177392960-f3fedf8a-71b9-4693-98ec-1daa94faed63.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33176106/177394892-b8e527e8-b4ea-437a-ae06-d765d77b689c.png">

Please check if it match the required design
