### ISSUE TITLE
UI Component - Emoji Drawer

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13525]
This issue is to track the creation of the component: **Emoji Drawer**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3112%3A54053.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by siddarthkay** [comment]
I'll be using this issue to import all emoji's into the status app from : https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Mobile-Foundations?node-id=620%3A42 and make them available via helper utilities, the same way we currently do `get-image` and icons
