### ISSUE TITLE
UI Component - Image

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13535]
This issue is to track the creation of the component: **Image**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=611%3A29891.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by briansztamfater** [comment]
There are lots of edge cases of this component so I'm sizing it as a 8
