### ISSUE TITLE
UI Component - GIF

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13534]
This issue is to track the creation of the component: **GIF**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3187%3A49869.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by briansztamfater** [comment]
@cammellos was there any discussion or requirements definition on how we will implement this component besides the UI?

Where we will pull the GIFs from, how (de)centralized will the approach be, message structure for GIFs on status-go, etc
