### ISSUE TITLE
UI Component - Message Reply

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13539]
This issue is to track the creation of the component: **Message Reply**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3289%3A70623.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by briansztamfater** [comment]
Not duplicated but super-duper related with #13538, I'll work on both

**Comment by flexsurfer** [comment]
implemented
