### ISSUE TITLE
UI Component - Account Selector

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13549]
This issue is to track the creation of the component: **Account Selector**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=1627%3A30638.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by siddarthkay** [comment]
need this component for https://github.com/status-im/status-mobile/issues/13439 
I have done most of the work in the screen
