### ISSUE TITLE
Long parameter text overlaps input field and send button on iphone 5s

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1354]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: If i want to change/edit my phone number , i need to input correct confirmation Codes. When i input long confirmation codes, it should be shown correctly in textarea.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The confirmation codes should be shown correctly in textarea, 

#### Actual behavior
[comment]: # (Describe what actually happened.)
The confirmation codes bounds.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Edit my profile
- Click Edit phone number
- Input phone number
- Input long confirmation codes

![1](https://user-images.githubusercontent.com/5856990/27489026-a1518166-586b-11e7-8e21-1cd090de0bd0.png)
 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9d5
* Operating System: IOS 10.3.2

**Comment by NataliaGrigoreva** [comment]
I can reproduce this issue for location command  (IPhone 5S iOS 10.2.1)
