### ISSUE TITLE
UI Component - Buttons

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13552]
This issue is to track the creation of the component: **Buttons**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=57%3A15962.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by ibrkhalil** [comment]
This is done successfully by @flexsurfer

**Comment by ibrkhalil** [comment]
This is done successfully by @flexsurfer
