### ISSUE TITLE
UI Component - Switcher Tab

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13550]
This issue is to track the creation of the component: **Switcher Tab**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=1338%3A34522.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by Parveshdhull** [comment]
Not relevant anymore due to shell migration
