### ISSUE TITLE
UI Component - Top Nav

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13568]
This issue is to track the creation of the component: **Top Nav**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=145%3A6203.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by jo-mut** [comment]
I am removing myself from this assignment just so I can first finish with pending tasks. If no one will have picked this up I will reassign it to myself
