### ISSUE TITLE
UI Component - Bottom Nav Tab

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13566]
This issue is to track the creation of the component: **Bottom Nav Tab**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=265%3A17957.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by Parveshdhull** [comment]
implemented in https://github.com/status-im/status-mobile/pull/14077
