### ISSUE TITLE
UI Component - Alert

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13576]
This issue is to track the creation of the component: **Alert**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=2980%3A43739.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by J-Son89** [comment]
@ibrkhalil looked into this component and it appears to be the native iOS/Android Alert component. As such there is nothing needed to be done here.
