### ISSUE TITLE
UI Component - Home Indication

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13573]
This issue is to track the creation of the component: **Home Indication**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=844%3A26374.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by ibrkhalil** [comment]
I think this is a system-based component too.

**Comment by du82** [comment]
> I think this is a system-based component too.

Yes, this is managed by the OS, to match the multiple navigation styles on both iOS and Android

**Comment by Parveshdhull** [comment]
Yes, we currently can't change the color of the home indicator in ios
Refs:
- https://stackoverflow.com/questions/46194557/how-to-change-home-indicator-background-color-on-iphone-x
- https://developer.apple.com/forums/thread/86906
