### ISSUE TITLE
UI Component - Status Bar

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13572]
This issue is to track the creation of the component: **Status Bar**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=843%3A26355.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by ibrkhalil** [comment]
Hey @cammellos 
Isn't the status bar OS specific ?
Do you think there's work to be done here?

**Comment by cammellos** [comment]
@ibrkhalil good point :) I have created these with a script, but looks like that it's not a valid issue, if @pedro-et confirms, this can be closed.
Thanks!

**Comment by Parveshdhull** [comment]
> Isn't the status bar OS specific ?
> Do you think there's work to be done here?

Yes, the icons of the status bar will be controlled by OS, but we still need to change icons and background color as per the theme.
(So not a component, but still needs to be addressed)
