### ISSUE TITLE
UI Component - Keyboard

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13570]
This issue is to track the creation of the component: **Keyboard**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=843%3A26311.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

**Comment by ibrkhalil** [comment]
I think this is a system based component, which won't need work
What do you think @cammellos
