### ISSUE TITLE
Request installation permissions

### ISSUE THREAD

**Issue by katebashurova** [status-im/status-react#1358]
Description

Type: Bug

Summary: Request installation permissions

Expected behavior: It should not ask for any permissions for Android installation

Actual behavior: It should ask for any permissions for Android installation

Reproduction:
1. Go to Playmarket 
2. Install the application

Additional Information

Status version: 0.9.9+
Device/OS: Samsung Galaxy S4 (SHV-E300K) Android 5.0.1

**Comment by katebashurova** [comment]
![screenshot_2017-06-13-23-39-10](https://user-images.githubusercontent.com/29694033/27519717-df774874-59f9-11e7-9511-68d2020aa153.png)
![screenshot_2017-06-13-23-53-02](https://user-images.githubusercontent.com/29694033/27519718-df903c8a-59f9-11e7-8239-504e774ba5ce.png)

**Comment by rasom** [comment]
It's not possible to request permissions at runtime on devices which are running Android 5.1 or lower https://developer.android.com/training/permissions/requesting.html , so this issue can't be fixed
