### ISSUE TITLE
No sign in UI of fetching messages for user (can take more than an hour in case of a large amount of messages)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13592]
# Bug Report

## Problem 
Found during performance testing. Eventually a vast of messages were fetched, (only 150 from 9k were not fetched, which is expected due to a possible block on backend level), but they were fetching approximately 1h and during this time:

- the preview was updated immedialtely regardless of chat view (the last sent message was shown) 
- inside chat view, no fetched messages were shown and there was no sign that something is happening

#### Expected behavior
1) can see that messages are fetching 
2) preview is updated only when a message can be shown in the chat view

#### Actual behavior
1) messages (2-9000) for User A are fetching in ~1h , meanwhile can see only message `1` in chat view
2) preview during this time is `9000`, so it was updated faster, but I couldn't see this message in chat view

### Reproduction

1) User A: send message `1` to user
2) User B: receive message, open chat with user A
3) User B: get offline for 4h
4) User A: send 9k messages (2 - 9000) while User B is offline
5) User B: get back online and wait for new messages

### Additional Information

- Status version: nightly 06/09/22
- Operating System: tested only on Android

**Log:** [geth_09_06.txt](https://github.com/status-im/status-react/files/9009577/geth_09_06.txt)

**DB that used for test:** https://drive.google.com/drive/folders/1987CcUWMw5pnV6kHptmkQNn3Wb-FpddD?usp=sharing

**Comment by ibrkhalil** [comment]
Hey @churik 
Can you tell me how can I send ~9k messages and I am happy to take a look ?
Cheers!

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app and migrating to Wakuv2. 

The label `recheck` is added in order to keep an eye on it while testing this part.
