### ISSUE TITLE
Goerli transition: status test dapp

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13606]
# Problem
Due to the transition from Ropsten to Goerli, we need Status Test Dapp working on Goerli.

## Acceptance Criteria
Can open `simpledapp.eth` and use:
- all Transaction methods (Tab `Transactions`)
- `Status API` (`Request contact code`)
- Assets (request any ERC-20 available )

**Comment by churik** [comment]
1) `Transactions` -> `Sign typed message`:
![IMAGE 2022-07-04 16:43:17](https://user-images.githubusercontent.com/4557972/177177118-ed828f46-9a07-4d5c-b3cb-28e8a1d1236a.jpg)

2)  Assets > request ETH, XEENUS, YEENUS, ZEENUS, STT
**Goerli Faucets:**
ETH: ping in DM
XEENUS: https://goerli.etherscan.io/address/0x022E292b44B5a146F2e8ee36Ff44D3dd863C915c
YEENUS: https://goerli.etherscan.io/address/0xc6fDe3FD2Cc2b173aEC24cc3f267cb3Cd78a26B7
ZEENUS: https://goerli.etherscan.io/address/0x1f9061B953bBa0E36BF50F21876132DcF276fC6e
STT: https://goerli.etherscan.io/address/0x7C9928829641Dd2Fa76AF3408f295A0A116983e3

~~3) Point `https://bafybeidzlqpkbtvpjtxnzgew6ffxhozq5f4ojbk64iq3tjl7lkjue2biby.ipfs.infura-ipfs.io/` to simpledapp.eth on Goerli~~

URL: https://simpledapp.eth.link/  is working 

all other methods are working on Goerli

**Comment by flexsurfer** [comment]
1. you have to change chainId manually in the input field

**Comment by flexsurfer** [comment]
1. changed default value to 5
2. deployed to  https://simpledapp.eth.link/
