### ISSUE TITLE
Locked out app after selecting Waku2 prod (no UI feedback when app needs time tologin)

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#13613]
# Bug Report

## Problem 

After selecting waku prod nodes for connection, I was redirected to the login screen.
I selected "Don't ask card to sign in", went through fingerprint flow, then entered my pin, tapped the keycard. Then redirected to the login screen with no error message.

#### Expected behavior

Getting logged in after tapping keycard

#### Actual behavior

See problem section 

### Reproduction

See problem section

### Additional Information

- Status version: 1.19.0 from google play store
- Operating System: Android

I am now locked out! No way to change the setting without login in...

**Comment by D4nte** [comment]
Wait... I went back to the app and I was finally logged in 😮

I tried to log in 6 times before that.

**Comment by D4nte** [comment]
Maybe better feedback to the user on the in progress login?

**Comment by du82** [comment]
Can confirm this is still a big issue. Both a friend and I got locked out after experimenting, thinking it would be easy to reverse the changes.

**Comment by churik** [comment]
@D4nte thank you for the issue!
It is expected that after changing fleet you need to re-login.

By "locked out" do you mean that the login screen got frozen, or something else?
I tried the flow that you described (with keycard on Android) and could login normally.

**Comment by D4nte** [comment]
@churik so after I tap the keycard it just remained at the login screen. So I entered my pin again and tap my card again and then, again remained at login screen.

I think the issue is that after tapping the card it takes several second to load the app but there's no feedback to the user that it's loading.

Do note I enabled Waku v2.

**Comment by D4nte** [comment]
Once the card is tap it remains at this screen.![Screenshot_20220705-102211.jpg](https://user-images.githubusercontent.com/300805/177227904-95fec92e-2d2c-4ba7-9d4c-c8e3f0e32eda.jpg)

**Comment by guylouis** [comment]
@churik is it keycard specific ? if yes, let's ping @bitgamma

**Comment by churik** [comment]
Well, it is visible more on the keycard as there is no animation when the login process is long. Not sure that in terms of new UI it has high priority to fix it though.

**Comment by churik** [comment]
Closing because of redesign
