### ISSUE TITLE
Messages stop being delivered in group chat from one of the devices after accepting membership request sent from another device with the same multiaccount

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13622]
# Bug Report

### Context

_The issue was discovered during a dogfooding session where participants used different versions of the Status app: 1.19 and a current Nightly.
Reproducing the problem is only possible when using 1.19 or 1.19 **and** the latest develop, since invitation links in group chats were removed in develop.
Also, to reproduce this, the user needs to have a restored account on two unsynchronized devices.
However, despite the fact that this is an edge case, it was decided to have the issue logged as the fix may help prevent other possible message delivery issues in the future._

## Problem 
[comment]: # (A problem description)

### Steps to reproduce:

1. Install 1.19 on Device1 and create a multiaccount - UserA
2. Install Nightly (or 1.19) on Device2 and Device3 
3. Recover another multiaccount on Device2 and Device3 (the same on both devices) - UserB
4. UserA adds UserB to contacts
5. UserA creates a group chat with UserB
6. UserA: `Group info` > `Group invite` > Copy link > Send the link to a public chat
7. UserB on Device2: join the same public chat > follow the link > Send a membership request
8. UserB on Device3: open the group in the activity center (so now the user is a member of the group) > Send a message just to check it's delivered 
9. UserA on Device1: open the group > `Group membership requests` > Accept a pending request from UserB
10. UserB on Device3: try to send another message

Thus, the problem is that messages from Device3 stop being delivered to Device1 and become invisible on Device2 (the same multiaccount) after the membership request sent from Device2 has been accepted by Device1.

#### Expected behavior
Messages sent from Device3 are still visible for all group members after accepting the membership request sent from Device2

#### Actual behavior
- Device1 can only see messages sent from Device2
- Messages from Device3 are also invisible for Device2

### Additional Information

- Status version: nightly 4/07, 1.19
- Operating System: Android, iOS

### Logs

[Device1 (group admin) geth.log](https://github.com/status-im/status-react/files/9039354/geth.log)
[Device2 geth.log](https://github.com/status-im/status-react/files/9039359/geth.log)
[Device3 geth.log](https://github.com/status-im/status-react/files/9039361/geth.log)

**Comment by churik** [comment]
I'm closing this one as the team is working on a full re-design of the app and migrating to Wakuv2.

The label recheck is added in order to keep an eye on it while testing this part.
