### ISSUE TITLE
RoadMap or ToDo list or Schedule or Improvement Proposal or something else wanted!

### ISSUE THREAD

**Issue by ngxiaoyi** [status-im/status-react#1362]
Hi there.

Firstly, congratulations on your held a successfully contribution. 

Seems you guys had a happy weekend. But no more updates I could found between your social communities.  Just a kindly reminder to you guys that your vision is just beginning, you should be responsible for your investors as I believe so much ETHs is enough for you to run your project smoothly and quickly. Maybe an open roadmap or develop schedule is necessary for your investors.

Just give a continuous output on your project  :)

**Comment by jarradh** [comment]
Have you had a chance to view our wiki?
We have a roadmap here http://wiki.status.im/#the-roadmap there are some proposals there but admittedly not as complete as they should be. 

As for a todo list, we have 214 issues open at the moment on status-react and and some more on https://github.com/status-im/status-go

**Comment by ngxiaoyi** [comment]
Interesting that  you missed your roadmap here and glade to see you have a completely roadmap. 

But the key of this issue I raised here is that you guys should keep close contract with your community rather than lose your voice after ICO like this: https://www.reddit.com/r/statusim/comments/6jjx5t/why_there_is_no_any_update_from_official/  .And if you guys choose agile development, then I believe the investors are your Product Owner and sure you should delivery something to PO every Sprint.

**Comment by jarradh** [comment]
Sure, well we've been in development for over a year and have been transparent every step of the way. We only have contributors, and they should have already been be familiar with our merge and regression cycles.

**Comment by clar** [comment]
no blog , no reddit, closed slack channel . Is this the team that raised 300 000 ethers from their supporters??  I'm very disappointed to what status team has done so far.

**Comment by jarradh** [comment]
Development has been unfrozen today and take a look at our commits already. 
https://github.com/status-im/status-react/commits/develop

Slack has been closed to guard against scammers as per Tokensale best practices which you can read about here: https://github.com/Scanate/Tokensale it will open up soon. 

Here's a draft of the blog post but **THIS IS STILL A DRAFT DO NOT SHARE THIS**
https://medium.com/@status.im/36e64d35d3e4

You are free to be disappointed in us, but unfortunately this attitude cannot make us work any faster. Please realise that running a contribution period is a huge undertaking, we are currently a small team, we're working as hard as we can, it is Monday.
