### ISSUE TITLE
Currently blocked users are not syncing

### ISSUE THREAD

**Issue by audriu** [status-im/status-react#13635]
@audriu 
e2e found an issue: currently blocked users are not syncing
**Steps:**
- Device1: create multiaccount, block any user from public chat
- Device2: restore same multiaccount on device 2
- Device2: pair Device1  and Device2
- Device1: tap on Sync All

**Expected result:**
can see blocked user on synced device
**Actual result:**
blocked user is not synced

Log: [geth.log](https://github.com/status-im/status-react/files/9021452/geth.log)

_Originally posted by @churik in https://github.com/status-im/status-react/issues/13509#issuecomment-1171394525_

**Comment by pavloburykh** [comment]
****UPDATE:**** 

### **Also blocked contacts are not backed up**

**Steps:**
1. Create multiaccount on Device 1
2. Add blocked user
3. Perform back up
4. Recover same multiaccount on Device 2
5. Pay attention if blocked contact is displayed on Device 2

**Actual result:** blocked contact is not displayed on Device 2

**Expected result:** blocked contact is displayed on Device 2
