### ISSUE TITLE
The user picture doesn't change if tapping on the "Camera" button twice

### ISSUE THREAD

**Issue by NataliaGrigoreva** [status-im/status-react#1363]
### Description

*Type*: Bug

The user picture doesn't change if tapping on the "Camera" button for two times
*Summary*: The user picture doesn't change if tapping on the "Camera" button for two times

#### Expected behavior
The user picture should change.

#### Actual behavior
The user picture doesn't change.

### Reproduction
1. Launch app "Status" 
2. Login with valid credentials
3. Go to Profile 
4. Click on the button with three points and tap on the "Edit" button
5. Tap on the user picture
6. Select "Capture" 
7. Tap on the "Camera" button twice or more

### Additional Information
* Status version: 0.9.9

* Operating System: Samsung Galaxy S IV | Android 4.3

#### Logs

[log_Camera.txt](https://github.com/status-im/status-react/files/1102430/log_Camera.txt)

#### Video
https://drive.google.com/file/d/0B0pYIvdvIoAHdHM5UmhxTThZNEk/view

**Comment by annadanchenko** [comment]
Can reproduce: tap twice on capture and nothing happens (except the sound of making a picture). Same "Profile image" screen is shown where user can see camera. 
Expected: picture is saved and screen "Edit profile" is shown with new avatar.
issue is from 0:31 https://app.testfairy.com/projects/4803622-status/builds/6456500/sessions/45/?accessToken=KezFZFj5MMcrmToqtZzEhrC/DnY

Android 6.0.1, real device Galaxy S6
 0.9.10-36-g9a06417b

**Comment by jeluard** [comment]
I don't see any image at all in your case. Is that it?
Can you take a picture with a single tap?
