### ISSUE TITLE
Back button closes app when using dapp browser

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#13633]
# Bug Report

Maybe not a bug but very annoying UX.

## Problem

When using dapp browser, back button close the app.
To resume browsing, one must:
1. Re-Open the Status App (I usually use the android "running apps" button)
2. Tap on dapp browser tab (it always open on chat tab)
3. Tap on the active pages button
4. Select the tab (I also find this part confusing because I never know if the most recent tab is at the top or bottom)

### Expected behavior

When dapp browser is open, android back button does a "back" browser navigation action. 

Also, when reopening the app, go back to last used tab (ie dapp browser, not chat)

Also, when opening dapp browser, automatically open the last active page

### Additional Information

- Status version: 1.19.0
- Operating System: Android

Note: android back button on firefox does a back navigation action, which is why it's a reflex for me.

**Comment by du82** [comment]
Finally someone mentioned the annoying feature where the app opens on the previous chat... It should reopen on the homepage, like every other superapp.

**Comment by D4nte** [comment]
For some reason, when switching Status app it does open to the previous app. But in the case of the back button being used, when switching back it goes to chat app.

**Comment by flexsurfer** [comment]
most likely this will be fixed only in the design

**Comment by churik** [comment]
Closing because of redesign
