### ISSUE TITLE
Android can not export an unencrypted database

### ISSUE THREAD

**Issue by audriu** [status-im/status-react#13648]
# Bug Report

## Problem 
[comment]: # Android can not export an unencrypted database.  Logs such message. 
'2022-07-11 17:13:30.676 10426-10591/im.status.ethereum.debug E/StatusModule: Login failed: {"error":"file is not a database"}'

#### Expected behavior
Log in screen click "Export unencrypted" and see it exported to a file

#### Actual behavior
logs error instead

### Additional Information

- Status version: develop
- Operating System: Android

**Comment by cammellos** [comment]
@churik @pavloburykh can you confirm please?

**Comment by churik** [comment]
Can't reproduce on nightly 11/07/22

export.db was created just fine.
[geth_11_07.log](https://github.com/status-im/status-react/files/9085884/geth_11_07.log)
Do you have any specific data on your account? And when exactly do you try to perform export? 
Doc for exporting is here, ping me in case of having questions.
https://notes.status.im/yJMuhPAGT5inXa9Zb4vMZw

**Comment by audriu** [comment]
I try to export whole db to check how blocked users are saved and why blocked contacts synchronise but blocked non-contact users don't.
DB export worked in IOS but failed on Android. I will investigate why.

**Comment by churik** [comment]
Interesting that it works on my side. However, DB was almost empty so not sure what exact data can cause the issue. 
> DB export worked in IOS but failed on Android. I will investigate why.

Thank you!

**Comment by pavloburykh** [comment]
> I try to export whole db to check how blocked users are saved and why blocked contacts synchronise but blocked non-contact users don't. DB export worked in IOS but failed on Android. I will investigate why.

Hey @audriu Could you please specify what do you mean by "blocked contacts" here? Currently all blocked users are being removed from contacts and there is no way to add blocked user to contacts until unblock. Maybe by successful synchronising of "blocked contacts" you meant synchronising of "contacts"?

**Comment by audriu** [comment]
I am working on this https://github.com/status-im/status-react/issues/13635
So there are 2 cases:

1. blocked users from a public chat
2. blocked users from your personal contacts

So only blocked users from case 2 are synchronized and backed up. Users from case 1 are not restored to a new device with the same account.
My reasoning was to get the DB and to see how is it different, and why it won't restore both types of blocked users.
