### ISSUE TITLE
Some of synced data is not being updated on paired device after initial sync until relogin

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13647]
In current set of synced data among the data that is not being updated right after initial sync are:
- account currency
- "Accept chats from" setting value
- "See profile pictures from" setting value
- "Show profile pictures to" setting value

**Steps:**

1. Create multiaccount on Device 1 
2. On Device 1 generate the following data that will be synced: 
- Create community
- Create a new channel in community
- Send some message in newly created community channel
- Add profile picture
- Set Accept chats from setting value to Contacts
- Set See profile pictures from setting to Everyone
- Set Show profile pictures to to None
- Add watch only account
- Change account currency (for example set value to AFN)
- Start 1-1 chat with any user, add this user to contacts
- Start a group chat with newly added contact

**Below video demonstrates the process of generating the above listed data:** 

https://user-images.githubusercontent.com/97245802/178249431-1d71c6ff-0573-4787-b557-f2456ff06c62.mp4

3. Restore account on Device 2
4. Pair Device 1 and Device 2
5. Tap Sync button on Device 1
6. Check if all synced data has appeared on Device 2 

**Actual result:** 
following values have not been updated on Device 2 after sync:
- "Accept chats from" setting value
- "See profile pictures from" setting value
- "Show profile pictures to" setting value
- account currency

Values are being updated only after performing re-login on Device 2

https://user-images.githubusercontent.com/97245802/178250562-4cdbae35-7c9f-4575-afa3-5f2bcfdfeec3.mp4

**Expected result:** all data has been updated on paired Device 2 right after performing sync.

[IOS_geth.log](https://github.com/status-im/status-react/files/9083371/IOS_geth.log)
[Android_geth.log](https://github.com/status-im/status-react/files/9083373/Android_geth.log)

### Additional Information

**- Bug appeared since nightly from July 8.** 
- Operating System: Android, iOS

**Note for QA team:** current issue causes the need to relogin after syncing in group of tests TestPairingSyncMediumMultipleDevicesMerged. Relogin should be removed after fix of this issue.

**Comment by churik** [comment]
Has been introduced in new version status-go in https://github.com/status-im/status-react/commit/33f6daff33425b17d9d6069d99553cd3ef81327e

**Comment by pavloburykh** [comment]
@churik @audriu **UPDATE:** I've checked current issue in 2 PRs with reverted commits https://github.com/status-im/status-react/pull/13650 and https://github.com/status-im/status-react/pull/13654

Still reproducing the issue in both reverted PRs.

**Comment by audriu** [comment]
So it implies that the bug was before https://github.com/status-im/status-react/commit/33f6daff33425b17d9d6069d99553cd3ef81327e . I am fixing this next.

**Comment by audriu** [comment]
So @pavloburykh tested a PR that I made for 1 commit before the https://github.com/status-im/status-react/commit/33f6daff33425b17d9d6069d99553cd3ef81327e and the regression was still there. So effectively "v0.102.6" is tested to have the regression.

**Comment by rasom** [comment]
The first attempt (not first actually, but I mean the first I got reproduced multiple times):
1. I did all steps from 2) except for "Add watch only account"
2. In result it has all four settings from the original issue synchronised. 
3. 1-1 chat and a private group were not synchronised though (I don't remember whether that's a problem)

**Comment by audriu** [comment]
The currency also doesn't synchronize if all steps are reproduced.

**Comment by rasom** [comment]
@audriu that is correct

So if I don't add watch only acc those setting are synchronised successfully.

In both cases 1-1 chat and private group are not synchronised (still wondering whether this is ok @pavloburykh )

**Comment by pavloburykh** [comment]
> 1-1 chat and private group are not sync

@rasom Yes, that is ok. We do not initially synchronise group/private chats in current implementation.
