### ISSUE TITLE
E2E: connect ECONNREFUSED 127.0.0.1:8200 error in nightly testruns 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13653]
Recently some e2e tests in nightly run started failing with an error "An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8200"

Example of test run containing such errors https://ethstatus.testrail.net/index.php?/runs/view/9632&group_by=cases:section_id&group_order=asc

The issue needs to be investigated and fixed if it is possible to do on our side.

**Comment by churik** [comment]
Another issue: sometimes connection is just lost without reason, and no commands are sent
Example: https://ethstatus.testrail.net/index.php?/tests/view/2938090

**Comment by churik** [comment]
Please re-open if still the case
