### ISSUE TITLE
Watches, battery etc on the status bar are not shown

### ISSUE THREAD

**Issue by katebashurova** [status-im/status-react#1366]
### Description
_Type:_  Bug

_Summary:_  User cannot see any notification, WiFi network, data or even battery level on all the screens with white background. 

**Expected behavior**:  Watches, battery etc on the status bar are shown

![image](https://user-images.githubusercontent.com/28752642/29767354-c8e9dda6-8bea-11e7-8dca-52ef4147b93a.png)

**Actual behavior:**  Watches, battery etc on the status bar are not shown

![image](https://user-images.githubusercontent.com/28752642/29767365-d148b7ce-8bea-11e7-8d1d-09e3ac0e907c.png)

**Reproduction**
1. Launch the app 
2. Open chat -> Console

**Additional information**
Device/OS: Samsung Galaxy S4 (SHV-E300K) Android 5.0.1
App version 0.9.9+

**Comment by katebashurova** [comment]
Pic

**Comment by katebashurova** [comment]
![screenshot_2017-06-20-22-59-17](https://user-images.githubusercontent.com/29694033/27563148-6638eba2-5ad0-11e7-9a7a-2a22a709a8cc.png)
![screenshot_2017-06-20-22-58-27](https://user-images.githubusercontent.com/29694033/27563166-6e62570a-5ad0-11e7-88b1-5c5b6c60e809.png)
![screenshot_2017-06-19-22-57-07](https://user-images.githubusercontent.com/29694033/27563173-74cc8656-5ad0-11e7-95f9-e3ccd5152f5d.png)

**Comment by katebashurova** [comment]
![20170627_225431](https://user-images.githubusercontent.com/29694033/27609609-ab1c95be-5b8b-11e7-92a5-80a07257ee1a.png)
![20170627_225404](https://user-images.githubusercontent.com/29694033/27609616-b2f9a272-5b8b-11e7-958c-0dd203df9ac9.png)
![20170627_225244](https://user-images.githubusercontent.com/29694033/27609625-ba4c5452-5b8b-11e7-8813-1bb6994d5acc.png)

**Comment by annadanchenko** [comment]
Instabug reports: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/846

**Comment by karan42** [comment]
This looks like an SDK version issue, I'm unable to reproduce this on my Nokia 3 running Android 7.1.1 app version: 0.9.10.429-gf227962a+. 

More details here https://stackoverflow.com/questions/20653305/full-screen-theme-for-appcompat the Answer by KrHashisM
