### ISSUE TITLE
ENS names are not resolved in mentions list in community channel

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13669]
**Steps:**
1. Create new community channel
2. Join community with User 1 
3. Join community with User 2 who has ENS name connected
4. Start typing @ by User 1 in community channel to see mensions list
5. Pay attention if Users 2 ENS is displayed in mentions list

**Actual result:** ENS name is not displayed in mentions list. It is impossible to mention User 2 be his ENS

https://user-images.githubusercontent.com/97245802/179187885-5a294e75-d7e5-45a0-9b8b-19cc078fc74a.mp4

**Expected result:** User's 2 ENS name should be resolved in mentions list. User 1 is able to mention User 2 by his ENS name. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
**UPD**: Issue only affecting Open communities.
