### ISSUE TITLE
New status bar is wrong color

### ISSUE THREAD

**Issue by du82** [status-im/status-react#13666]
The new status bar isn't the right color, it's slightly off from what it should be. I think @Parveshdhull did the original implementation, maybe it needs a slight fix

![Screenshot_20220713-171127_Status PR](https://user-images.githubusercontent.com/65834069/178867609-463743d2-6053-49eb-934c-34cbd00bf212.jpg)

**Comment by Parveshdhull** [comment]
Hi, @du64, Thank you very much for reporting this issue. Please can you specify which build you are using?

**Comment by Parveshdhull** [comment]
<img src="https://user-images.githubusercontent.com/17097240/178868993-81ce62ba-b87e-419a-b302-527d17fc77a3.png" alt="Screenshot" height="200"/>

@briansztamfater, Please can you check if you are using `colors/neutral-5` for messages view, it looks different then wallet and status-bar

**Comment by du82** [comment]
Using the version with commit hash:

df1189bb7af5bba9c57c313f510fc3857d985366

**Comment by Parveshdhull** [comment]
Issue fixed in https://github.com/status-im/status-react/pull/13640, Next nightly build will have same color for messages screen and status-bar. Thank you
