### ISSUE TITLE
Bookmarks added after pairing are not synced 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13679]
# Bug Report

## Problem 
Browser bookmarks (favourites) added on the main device after pairing don't appear on the secondary device. 
There is another issue on 1.19: bookmarks added after pairing only appear on the secondary device after relogin. 
However, on the develop relogin doesn't work. 

#### Expected behavior
- New bookmarks are synced immediately after being added on the main device
- Relogin not needed

#### Actual behavior
- On develop: new bookmarks are not synced if added after pairing
- On 1.19: new bookmarks added after pairing are only synced after relogin on the secondary device

### Reproduction

1. Recover the same account on Device1 (main) and Device2 (secondary)
2. Sync Device1 with Device2
3. Device1: open the Browser tab > open a website > Tap `...` at the bottom right > `Add favourite`
4. Device2: open the Browser tab

### Additional Information

- Status version: nightly 15/07, 1.19
- Operating System: Android, iOS

### Logs

[Device1 geth.log](https://github.com/status-im/status-react/files/9122824/geth.log)
[Device2 geth.log](https://github.com/status-im/status-react/files/9122826/geth.log)

**Comment by qoqobolo** [comment]
Hey @PascalPrecht! Pinging you here as @Samyoul mentioned that you might have more details on this issue. If so, could you please share? 
Probably you could fix it on the status-go side?

**Comment by Samyoul** [comment]
Ah I know the problem, we need to add some signal handling on the mobile side.

**Comment by 0x-r4bbit** [comment]
Hi @qoqobolo 
as mentioned in https://github.com/status-im/status-go/pull/2709#issuecomment-1150982565, for bookmarks to be synced in realtime, mobile has to use messenger APIs.

Right now they use service APIs which bypass the implicit sync done by the messenger.
