### ISSUE TITLE
Clicking on a sticker in chat view opens wrong sticker pack if its contract is also registered on another network

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13683]
# Bug Report

## Problem 
If a contract of a sticker pack is registered in the main network and in a test network (e.g. the `Status Cat` sticker pack is registered in both Mainnet and Ropsten), then if UserA (on Mainnet) receives a sticker from the `Status Cat` sticker pack from UserB (that is on Ropsten) and taps it in the chat view, the wrong sticker pack will be opened. 

#### Expected behavior
Corresponding sticker pack opens in the sticker market when press a sticker in chat view

#### Actual behavior

https://user-images.githubusercontent.com/67952253/179522296-ef0dfa2b-9786-464e-9007-e13d8574baa3.mp4

### Reproduction

1. UserA on Mainnet and UserB on Ropsten (PR or `x86` (e2e) build)
2. UserA and UserB join a public chat
3. UserA sends a sticker from the `Status Cat` sticker pack being on Mainnet
4. UserB taps the sticker in the chat view being on Ropsten
   **Actual result:** the Tozemoon sticker pack is shown in the sticker market

### Additional Information

- Status version: 1.19
- Operating System: Android, iOS

**Comment by churik** [comment]
Blocks part of 702157, re-enable check after fix

**Comment by flexsurfer** [comment]
this should be fixed in contract or in e2e tests

**Comment by churik** [comment]
closing because of redesign

**Comment by flexsurfer** [comment]
redesign won't help much

**Comment by cammellos** [comment]
Closing for now, until it's planned
