### ISSUE TITLE
Chinese translations don't work

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1369]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

For example, a user uses Traditional Chinese characters and lives in Taiwan, his language and locale should be zh-Hant-TW, and the priority of the i18n strategy should be:

zh-Hant-TW: Traditional Chinese characters used in Taiwan
zh-Hant: general Traditional Chinese characters
zh: general Chinese characters
The current fallback strategy of react-native-i18n has a bug. If it don't find zh-Hant-TW, it will only look for zh, not zh-Hant first.

https://github.com/AlexanderZaytsev/react-native-i18n/issues/96#event-1128148909

https://github.com/fnando/i18n-js/issues/460

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

**Comment by flexsurfer** [comment]
temporary fixed in https://github.com/status-im/status-react/issues/1374

**Comment by rasom** [comment]
@flexsurfer @annadanchenko Can we close this issue?

**Comment by flexsurfer** [comment]
@rasom it's better to wait this fix https://github.com/fnando/i18n-js/pull/465, remove my temporary fix and use fixed library

**Comment by rasom** [comment]
ok, thanks

**Comment by PikachuEXE** [comment]
new version for `i18n-js` is released

**Comment by flexsurfer** [comment]
thanks @PikachuEXE !

**Comment by chadyj** [comment]
From @flexsurfer:

> i think it should work we don't need to do something special for Chinese

Closing!
