### ISSUE TITLE
Implement Scan tab in switcher

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13699]
As a user
I want to have a Scan tab in the switcher.

[Switcher](https://github.com/status-im/status-mobile/issues/13155) and [Switcher tabs](https://github.com/status-im/status-mobile/pull/13386) are being implemented separately.
Scope of the issue is to implement QR scanner screen and animations. 

### Designs
https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18994

### Animations
https://user-images.githubusercontent.com/17097240/180041582-52f805b0-af41-44e9-aa9e-518484a1f276.mp4

Principle file https://www.notion.so/Animation-guidelines-49cbc3e7a52b4120850936ca35d959ee

**Comment by flexsurfer** [comment]
replaced by https://github.com/status-im/status-mobile/issues/14011
