### ISSUE TITLE
make run-clojure is not working when there is space in repo path

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13715]
# Bug Report

## Problem 
[comment]: # (A problem description)

If a user clones the status-mobile repo to a path that contains a space in the folder name, then `make run-clojure` is not working

```
[kadian@fedora status-react]$ make run-clojure
yarn shadow-cljs watch mobile
/home/kadian/Develpment/GitHub Projects/status-react/nix/scripts/source.sh: line 28: /home/kadian/Develpment/GitHub: No such file or directory
make: *** [Makefile:258: run-clojure] Error 127
```
> Error logs taken from contributor's message from the [discord](https://discord.com/channels/641364059387854899/758090615950016602/1000268644200226827) 

### Reproduction Steps
1) Create a folder `test folder`
2) Clone `status-mobile` inside the `test folder`
3) Run `make run-clojure`

### Additional Information

- Reproduced in fedora and arch linux

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
cc: @jakubgs

**Comment by jakubgs** [comment]
>consists a space in the folder name

It's "contains a space", not "consists a space".

And clearly the issue is in the exact line indicated by the error, line 28:
https://github.com/status-im/status-mobile/blob/694986682a69b18b249085cdabe659cb85eb4407/nix/scripts/source.sh#L27-L29
It just needs to be double quoted.

Btw, your repo clone name is still `status-react`, not `status-mobile`.

**Comment by Parveshdhull** [comment]
> It just needs to be double quoted.

Actually, I tried double quoting `${GIT_ROOT}/nix/scripts/setup.sh` at line 28, and also few other places where use of `${GIT_ROOT}` is not double quoted
but then similar error is reported from nix file, don't remember exact name, but something like
`nix/......./setup`

**Comment by Parveshdhull** [comment]
```
[status-mobile]-> make run-clojure
yarn shadow-cljs watch mobile
Configuring Nix shell for target 'clojure'...
/nix/store/mmaml7sb1isvixsywh46kfdh94f18ib3-stdenv-linux/setup: line 89: /home/parvesh_monu/Desktop/test: No such file or directory
yarn run v1.22.19
error Command "shadow-cljs" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:258: run-clojure] Error 1
```

**Comment by jakubgs** [comment]
I cannot reproduce your `run-clojure` issue.

**Comment by Parveshdhull** [comment]
> I cannot reproduce your `run-clojure` issue.

hmmm, that's weird
