### ISSUE TITLE
The sign under Public key`s QR code doesnt match the key

### ISSUE THREAD

**Issue by svetak0tleta** [status-im/status-react#1373]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When viewing the QR code of a public key, the signature below it shows the value of the main wallet (see Screenshot1), while the link  works correctly and gives the correct value of the public key (see Screenshot 2)
![screenshot_1](https://user-images.githubusercontent.com/29459366/27622830-f633199e-5bf2-11e7-9a79-c65fe0c1cf82.png)
![screenshot_2](https://user-images.githubusercontent.com/29459366/27622937-85d2c3e2-5bf3-11e7-841f-43c8f30dc96d.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Public key`s QR code has a sign from the Account public key

#### Actual behavior
[comment]: # (Describe what actually happened.)
Public key`s QR code has a sign from the main wallet

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open profile
2. Tap Public key options -> Show QR

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9
* Operating System: Android 4.4.2

**Comment by yenda** [comment]
Fixed in current version
