### ISSUE TITLE
Extend clojure integration test to cover sending a message

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-react#13746]
We should increase the coverage of the newly created clojure integration tests.

One of the most common use cases is to send a message in a 1:1 or public chat.

The test steps that should be covered in the tests should be:
1. Create a new account (already covered by steps) & login (we can start from these steps https://github.com/status-im/status-react/blob/9f9b896eb7fcfac60d55b33a3744480b13d2ba8d/src/status_im/integration_test.cljs#L46 )
1. Simulate inputting a public key or joining a public chat
1. Create / enter a chat
1. Simulate entering message text
1. Simulate sending the message

We want to achieve the closest coverage to what the UI is actually doing.

To simulate in the UI:
1. Create a new account
1. Click on the + button on the home screen
1. Click on either:
    - Start new chat (Extend https://github.com/status-im/status-react/issues/13579)
    - Join public chat (Extend https://github.com/status-im/status-mobile/issues/13752)
1. Click on the Message input
1. Input message text
1. Click on the send button
1. See new message

If you have any question feel free to ask me on discord.

**Comment by alexandre-k** [comment]
I would like to do this one, can you assign it to me?

**Comment by spac3c4det** [comment]
@alexandre-k how are you doing on this one?
Been working on this one: https://github.com/status-im/status-mobile/issues/13579
which is closely related, so don't hesitate to hit me up if you need some help

**Comment by alexandre-k** [comment]
> @alexandre-k how are you doing on this one? Been working on this one: #13579 which is closely related, so don't hesitate to hit me up if you need some help

Go for it. I shared what I did on Discord but didn't have any reply and didn't have time to troubleshoot how to run my test anyway.

**Comment by spac3c4det** [comment]
@Samyoul can you sign me up for this one?
