### ISSUE TITLE
Extend clojure integration test to cover joining a public chat

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-react#13752]
We should increase the coverage of the newly created clojure integration tests.

One of the most common use cases is to join a public chat.

The test steps that should be covered in the tests should be:
1. Create a new account (already covered by steps) & login (we can start from these steps https://github.com/status-im/status-react/blob/9f9b896eb7fcfac60d55b33a3744480b13d2ba8d/src/status_im/integration_test.cljs#L46 )
1. Simulate inputting a public chat name. eg `status`, `crypto` or `layer2`
1. Create public chat

We want to achieve the closest coverage to what the UI is actually doing.

To simulate in the UI:
1. Create a new account
1. Click on the + button on the home screen
1. Click on Join public chat
1. Input a chat-name
1. Load public chat with messages

If you have any question feel free to ask me on discord.

**Comment by spac3c4det** [comment]
@Samyoul could you sign me up for this one? ;-)
