### ISSUE TITLE
Profile pictures blink (with loading spinner) when making some actions

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13768]
# Bug Report

## Problem 

The loading spinner appears for a moment on profile pictures when performing actions such as:
- adding/removing a contact
- mute/unmute
- adding a nickname
- changing the online status visibility in own profile
- etc

#### Expected behavior
Profile picture doesn't blink

#### Actual behavior

https://user-images.githubusercontent.com/67952253/183041160-ec8fc179-1d0d-436a-8576-c6c75dd198ac.mp4

### Reproduction

1. Open Status
2. Open profile of some user
3. Add to contacts, mute
4. Navigate to own profile > change the online status

### Additional Information

- Status version: nightly 5/08
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
thats because of how header is created 
```
:header                    [:<>
                                     [(profile-header/extended-header
```

its not simple fix, so better to wait new designs
