### ISSUE TITLE
app license is ambiguous, is Status free software or not?

### ISSUE THREAD

**Issue by sneak** [status-im/status-react#13777]
According to the `LICENSE.md` in the repository, the app is licensed under Mozilla Public License 2.0.

However, on launching the app, I am presented with a consent screen demanding that I agree to the "Terms of Use", which says, among other things:

> You agree to use the Status app in a way that doesn't harm or violate the rights of Status, Status app users, or others in any way.

I do not agree to this!  In fact, I reserve all rights granted to me under the MPL, including the right to use the software in ways that the copyright owner does not agree with.

If this is indeed a condition of the software license agreement, then Status is not free software / open source, as such usage restrictions make software nonfree.

The Terms of Use should be removed from the mobile app, as the app is software and the only terms of use for the software are the software license agreement.

However, if the Terms of Use govern the use of APIs or services provided by Status Research & Development GmbH in Switzerland, this should be made much more clear, as the messaging around the brand suggests that I am using only public/decentralized/***permissionless*** APIs (such as the Ethereum blockchain) and that it has no reason to phone home.

If it does indeed use **permissioned services** provided by Status Research & Development GmbH, I don't want to be a user.  I want local free software, not an account on some centralized service provider that tells me how I can and can't use the service.  That's a ***permissioned** system, as evidenced by the restrictive demands made of me in the "Terms of Use".

If it does not, then it's only the **software** license that applies to the app, and that's the MPL2, and the whole "Terms of Use" thing is a confusing red herring.

**Comment by du82** [comment]
Status is free, open-source, peer to peer (decentralized) software.

Do whatever you want with the app, (hack it, fork it, have fun) just don't use the Status brand if you release your own version. The brand and app are seperate.

**Comment by sneak** [comment]
If it's free software, why am I asked to agree to a nonfree Terms of Use on first launch?
