### ISSUE TITLE
On massive phones the switcher doesnt fit

### ISSUE THREAD

**Issue by du82** [status-im/status-react#13785]
On large phones, the switcher overlay is too small to fit.
Maybe the app should detect screen size, and make the switcher 110% of screen size?

Tested on:
- Samsung A50
- OnePlus Nord N20 5G
- iPhone 13 Pro

![Screenshot_2022-08-09-20-43-55-80_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/183792473-d2d1f32b-386c-40a3-ad5e-218278d14c4e.jpg)

**Comment by Parveshdhull** [comment]
closing issue as it not relevant anymore, because switcher is replaced by shell in https://github.com/status-im/status-mobile/pull/14099
