### ISSUE TITLE
Implement triggering nightly e2e run regardless of ios/android build results (in case if android e2e build is successful)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13786]
Currently nightly e2e testrun is not triggered in case if ios/android build has fallen even if android e2e build is successful. 

Lately, we have had several cases when ios nightly build has [failed](https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fnightly/detail/nightly/2426/pipeline) and because of that nightly e2e testrun was not triggered. 

So, it would be nice if nightly e2e testrun was triggered every time in case if android e2e build is successful and regardless of ios/android builds results.

**Comment by cammellos** [comment]
@churik I will be closing this, feel free if still actively working on it
