### ISSUE TITLE
Double emoji are shown in the input field

### ISSUE THREAD

**Issue by Ferraiya** [status-im/status-react#1378]
Description

*Type*: Bug

*Summary*: Double emoji are in the input field, but after sending they look correctly

#### Expected behavior
 # Single emoji are shown in the input field after entering it in every chat

#### Actual behavior
# Double emoji are shown in the input field in every chat

### Reproduction
# 
- Open Status
- Open a chat with anybody 
- Tap on emoji near the right edge of the text line
- Tap on one or more some emoji

### Additional Information
* Status version: 0.9.9d5 Build 1329.105
* Operating System: iPhone 5, iOS 9.3.5

Video: https://drive.google.com/file/d/0B5WergArvaY1RWZyMHZPZ2VNVkk/view?usp=sharing
#### Logs
[iosdevicelog 29.06.17 1.05.txt](https://github.com/status-im/status-react/files/1110365/iosdevicelog.29.06.17.1.05.txt)

**Comment by chadyj** [comment]
Shouldn't be an issue anymore. Closing.
