### ISSUE TITLE
Implement Message Context Drawer Component (New UI)

### ISSUE THREAD

**Issue by chrispader** [status-im/status-react#13789]
Implement the Msg Context Drawer component as in the design

[Figma Design](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=6122%3A256554)

**Comment by briansztamfater** [comment]
I think it's duplicate from #13527

**Comment by chrispader** [comment]
Are you sure? I think `Reactions drawer` should be renamed then. Are you already working on this? You are the assignee :) @briansztamfater

**Comment by briansztamfater** [comment]
@chrispader Yes, I think Figma components were renamed, already working on it! Let me know if you have made any progress also and we can figure it out.
