### ISSUE TITLE
Improve quo2 text component

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13793]
### 1. letter-spacing
Letter spacing currently used by the component doesn't match with letter spacing for Figma [design](https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Mobile-Foundations?node-id=617%3A208).
And looks like small changes in letter spacing are not affecting the text component.
Formula used by Figma for letter spacing: [formula](https://rsms.me/inter/dynmetrics/) ([ref](https://github.com/status-im/status-mobile/pull/13753#discussion_r941192544))
`Heading-1/Regular`
<img src="https://user-images.githubusercontent.com/17097240/184025017-e8e663ca-6032-49b1-8080-486a5dd2578d.png" alt="Screenshot" height="300"/>

### 2. Line Height:
The line height currently used by the component doesn't match with line height from the Figma design
`Paragraph-2/Regular`
<img src="https://user-images.githubusercontent.com/17097240/184026205-c64ef274-85a9-4e49-baf6-f6bb83a560b7.png" alt="Screenshot" height="300"/>

[Original image]
<img src="https://user-images.githubusercontent.com/17097240/184026699-c641aabc-19d2-4129-8beb-292343f4141d.png" alt="Screenshot" height="200"/>

**Comment by yqrashawn** [comment]
> 2. Line Height:

H @Parveshdhull I compared `Paragraph-2/Regular` and can't find line height difference.

![CleanShot 2022-09-09 at 14 35 23@2x](https://user-images.githubusercontent.com/15090582/189289396-706706b9-45e2-4c37-a767-06519de3331a.png)

**Comment by Parveshdhull** [comment]
hi @yqrashawn,
Thank you very much for looking into this.
Please can you try with 5-10 lines? Small line heights difference might not be visible, but they add up to a big difference with multiple lines.

**Comment by yqrashawn** [comment]
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/15090582/189304171-6fcff891-dfe9-432a-bbd6-2ccb75b1c514.png">

There's indeed mismatch. I'll check.

Line 1
<img width="711" alt="image" src="https://user-images.githubusercontent.com/15090582/189305268-3bab99fa-a0f2-4375-9dbf-4ad92b87c389.png">


Line 10
<img width="711" alt="image" src="https://user-images.githubusercontent.com/15090582/189305130-e9b6fefd-2e99-455d-b1a1-c860a5637449.png">

**Comment by cammellos** [comment]
Closing for now due to inactivity

**Comment by Parveshdhull** [comment]
reopening issue (https://github.com/status-im/status-mobile/pull/16981#pullrequestreview-1587186278)

**Comment by Parveshdhull** [comment]
related PR https://github.com/status-im/status-mobile/pull/13960, and related discussion https://github.com/status-im/status-mobile/pull/13960#discussion_r966749759

**Comment by yqrashawn** [comment]
add more info here
we use inter font, and it has this thing called Dynamic Metrics http://rsms.me/inter/dynmetrics/
it's a formula that calculates letter spacing based on font size

merged PR https://github.com/status-im/status-mobile/pull/13960 fixed the formula in our code

yet, quo2 text component is different from figma design

A is figma design
B is screen shot from http://rsms.me/inter/dynmetrics/
C is quo2 text component screenshot on ios, not tested on android

you can see B and C are identical, which means quo2 text implementation is the same as the Inter font recommended dynamic metrics implementation 
the calculated letter spacing value always looks like `0.31585560420509633%` and figma round it to `0.32%`, which might be the reason A is not the same as B/C

![CleanShot 2023-08-22 at 10 00 03](https://github.com/status-im/status-mobile/assets/15090582/9b75c584-4d09-4af4-9c17-300932abca86)

**Comment by yqrashawn** [comment]
this might help https://www.figma.com/community/plugin/795733302011238428/Inter-Letter-Spacing
Inter Letter Spacing figma plugin
