### ISSUE TITLE
Show anonymous usernames instead of Unknown contact in public chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1379]
### Description

*Type*: Bug

*Summary*: All participants in public chat have "unknown contact" title. It would be easier to distinguish several users if anonymous usernames are shown instead of same Unknown contact title.
![img_1906](https://user-images.githubusercontent.com/6584810/27680379-29d6b3ce-5cc4-11e7-9d33-906841d18764.jpg)

#### Expected behavior
Anonymous username is shown as a user name in public chat to other participants
#### Actual behavior
Unknown contact  is shown as a user name in public chat to other participants

### Reproduction

- Open Status
- Join public chat as contact A
- Join public chat as contact B
-  as contact A: write a message to public chat
-  as contact B: check the user name shown above the message from A in public chat

### Additional Information
* Status version: 0.9.9
* Operating System: iOS and Android

**Comment by annadanchenko** [comment]
@mlahia Unfortunately, instead of anonymous username there is Revolving Pikeperch name shown. Steps:
- User with anonymous name `Oldlace Proud Queenslandheeler` is not in my contacts. This anonymous username was generated during account creation and user did not set other name.
- We joined public chat 'testhere'. 
- I've sent message "A"
- User sent message "B"
Expected: I see that message B is sent by user `Oldlace Proud Queenslandheeler`
Currently: I see that message "B" is sent by "Revolving Wide Pikeperch"
Log and video from my side (see from 00:22, Google Pixel XL, Androi 8.0.0 real device): https://app.testfairy.com/projects/4803622-status/builds/7127704/sessions/3/?accessToken=P/0w7X7bGCXJZS6n0HDlvjSidUs
Log and video from user's side (see from 00:15, iPhone 6s, iOS 10.3.3, real device): https://app.testfairy.com/projects/4803590-status/builds/7127482/sessions/7/?accessToken=Ic3FlDekGbHL-MQIqiC-YKnMppQ
Issue:
![screenshot_20171121-163042](https://user-images.githubusercontent.com/6584810/33080959-92416c38-ced9-11e7-89e6-276113996144.png)

**Comment by SHA-2048** [comment]
OK very sorry for that. I'm having some troubles installing the app on my old macbook. I'll submit a fix as soon as I manage to test properly. Thanks !

**Comment by SHA-2048** [comment]
@annadanchenko with the help of @lahian I've been able to test it on the iPhone simulator. I've update the PR with a working version. Please take a look when you have time :) . Thanks !

**Comment by churik** [comment]
Issue is not fixed

**Comment by SHA-2048** [comment]
@churik can please put some details?
I've tested the fix on an iphone 6 simulator and the anounymous user name was displaying correctly instead of "Unkown contact"

**Comment by churik** [comment]
@mlahia I checked wrong PR (#2452), sorry for mistake, will check on #2815

**Comment by churik** [comment]
Install:
Public chat:
* check that default usernames are shown instead of Unknown contact (when users are not added as contacts of each other) when users did not change them before
* check that default usernames are shown instead of Unknown contact (when users are not added as contacts of each other) when users set another profile name
*check that one user add another as contact and profile names in Chat will be updated accordingly
Upgrade:
* upgrade with existed history in Public chat (messages from unknown contact) - defoult names are displayed after upgrade.
* sent new messages in public chat after upgrade
