### ISSUE TITLE
Make error message more human-readable when switching network while offline

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13805]
# Bug Report

#### Actual behavior
<img width="327" alt="Screenshot 2022-08-16 at 12 10 56" src="https://user-images.githubusercontent.com/67952253/184854769-b195fa11-0923-4361-8abe-93336858c276.png">

### Reproduction

1. Open Status
2. Go offline (e.g. enable airplane mode) 
3. Profile > Advanced > Network
4. Select a network > Tap `Connect`

### Additional Information

- Status version: nightly 16/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
that's expected, but we need to fix error message

**Comment by qoqobolo** [comment]
> that's expected, but we need to fix error message

Got it, thanks. The issue is updated

**Comment by churik** [comment]
Closing because of redesign
