### ISSUE TITLE
Support changing network without loggin in and out

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13803]
As a user
I want to be able to change network without logging in and out
So that I can more easily use WC/Dapps etc

### Description

Currently changing network triggers a login/logout
Status-go & desktop has been already updated to support this (check with @alaibe for details), and we should do similar for mobile.

**Comment by qoqobolo** [comment]
@flexsurfer bringing your attention to this scenario which could probably be checked and covered in your future PR: https://github.com/status-im/status-mobile/issues/13805

**Comment by flexsurfer** [comment]
thanks @qoqobolo mhm that's interesting, i don't have any good idea how to handle it, we need to check if network id returning by rpc is correct , but still there is no sense to switch network in offline mode, so we could just improve error message

**Comment by flexsurfer** [comment]
how changing network works now:

1) change current network value
```clojure
:db (assoc db :networks/current-network network)
::json-rpc/call [{:method "settings_saveSetting"
                  :params [:networks/current-network network]
``` 
2) prepareDirAndUpdateConfig

change keys path in node config json

```java
 final String multiaccountKeystoreDir = pathCombine("/keystore", keyUID);
 final String updatedJsonConfigString = this.updateConfig(jsonConfigString, absRootDirPath, multiaccountKeystoreDir);
```

3) save new node config

```clojure
::json-rpc/call [{:method "settings_saveSetting"
                  :params [:node-config config]
```

4) logout and login 

to restart node we need user password

**Comment by flexsurfer** [comment]
actually, we don't need `prepareDirAndUpdateConfig` because we don't change an account, so the only thing we need is to change network in node-config, and restart the node

**Comment by flexsurfer** [comment]
but also there are parts of the application that are networks dependent:
stickers, ens names, wallet, browser, so we need to "restart" the application because there might be a screen opened that is not available in different network

there is already the implementation for status-go which supports chain-id in some service's methods, but it doesn't look like it will work with "global" network switcher, it's more for using different networks in the same time in parallel, so we need to understand how to implement it , and how it will work in the UI

**Comment by flexsurfer** [comment]
`and we should do similar for mobile.` we can't do similar for mobile because we need designs first

**Comment by flexsurfer** [comment]
so probably network in Advanced should be moved under Dev flag, and it should be not possible to change network for stickers and ens in the prod

**Comment by flexsurfer** [comment]
in that case stickers and ens always will be using ethereum mainnet, and in wallet we could change network or use a few networks in parallel

**Comment by flexsurfer** [comment]
but still to implemented it in mobile we need designs for browser, WC and wallet for different networks usage

**Comment by churik** [comment]
not sure it makes sense in the scope of redesign, closing for now, re-open if it is still relevant
