### ISSUE TITLE
Blank screen on the 'Invite people' screen in community if user has no contacts

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13807]
# Bug Report

## Problem 
There is a missing informational message on the screen for inviting contacts to the community if the user has no contacts.
In this case, a blank screen can be confusing.

#### Expected behavior
If a user has no contacts, a message like `Contacts that you can invite to the community will be displayed here` should be displayed.
Summon @hesterbruikman for more precise wording.

#### Actual behavior

https://user-images.githubusercontent.com/67952253/184867754-bea7a611-201e-447f-8545-e5b480017f24.MP4

### Reproduction

1. Create a community 
2. Tap the `Plus` button > `Invite people`

### Additional Information

- Status version: nightly 16/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by hesterbruikman** [comment]
I would suggest: `Add contacts to invite them to this community`

This should be a temporary issue that'll be resolved by share links for open membership communities. Correct @xAlisher @pedro-et ?

**Comment by ibrkhalil** [comment]
Something like this ?
![screenshot](https://user-images.githubusercontent.com/33176106/186192503-017c2763-0143-4816-9cd7-805894fa2e03.png)

**Comment by ibrkhalil** [comment]
Maybe centered ?
![image](https://user-images.githubusercontent.com/33176106/186194311-d5c164f8-1e9d-4211-baa0-13ce30f1540b.png)

**Comment by ibrkhalil** [comment]
@qoqobolo 
@hesterbruikman

**Comment by qoqobolo** [comment]
@ibrkhalil we have a similar informational message in group chats. I think it would be more neat to stick to the same style
<img width="326" alt="Screenshot 2022-08-24 at 10 28 44" src="https://user-images.githubusercontent.com/67952253/186369812-db28a396-40bb-4e64-a863-0dfda068221f.png">

**Comment by hesterbruikman** [comment]
@ibrkhalil also checking with the design team on new patterns/components that might be used. I can get back to you in a few hours on that. (Cc @qoqobolo)

**Comment by ibrkhalil** [comment]
Waiting for response

**Comment by hesterbruikman** [comment]
@ibrkhalil the team proposes to use a new 'Empty state' component. The benefit of this approach is that it can remain in V2 of the app. 

You can find the component here on [Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=7877%3A229756).

![Empty state](https://user-images.githubusercontent.com/35233054/186459310-a6a9a29c-2d0e-4d7c-b67d-c168e2adf4e4.png)

Thanks for poining out the same for group chat @qoqobolo ! Same design with different copy makes sense there as well. What are the steps to get to the screen you shared? I recognize the copy, but only get it in combination with the group chat share link, like this:

![Screenshot_20220824-173130_Status](https://user-images.githubusercontent.com/35233054/186460184-4c8d2720-83ed-49cb-a331-75694d870586.jpg)

**Comment by qoqobolo** [comment]
@hesterbruikman group invite links were deleted from this screen: https://github.com/status-im/status-mobile/pull/13435. 
So my screenshot is just taken from Nightly :)

**Comment by xAlisher** [comment]
Yesterday design team made a component for an empty states for a new component library, maybe it can be used in a legacy design to solve an issue.  Rectangle is a placeholder for an icon that will be a part of illustration system.

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=7877%3A229756

CC @hesterbruikman

**Comment by hesterbruikman** [comment]
Aaah, I see, thanks. I'm afraid I'm not fully up to speed on the change. If there is no group chat invite link, there would also be no membership requests, correct? As anyone joining the group would be added by an admin.

**Comment by qoqobolo** [comment]
> If there is no group chat invite link, there would also be no membership requests, correct? As anyone joining the group would be added by an admin.

Yes, correct. But the scenario was also covered when users follow the old invitation links, sent from previous Status versions. Therefore, the item `Membership requests` was retained to keep compatibility.

**Comment by hesterbruikman** [comment]
Great! Thanks for clarifying! So for this case I'd suggest this variation of the same component (variant excludes the button).

In copy leaving out any reference to invite link. It might leave the question "Why would people join that I haven't already invited?", but that'll be temporary.

Shame about the public invite links! Really liked the use case of that deeplink when inviting people from existing chat groups on Whatsapp, Telegram, Signal, etc.

![Frame 3](https://user-images.githubusercontent.com/35233054/186685862-17985b8e-a9b1-4b2d-8d53-1f13a7b7d196.png)

**Comment by ibrkhalil** [comment]
> Great! Thanks for clarifying! So for this case I'd suggest this variation of the same component (variant excludes the button).
> 
> In copy leaving out any reference to invite link. It might leave the question "Why would people join that I haven't already invited?", but that'll be temporary.
> 
> Shame about the public invite links! Really liked the use case of that deeplink when inviting people from existing chat groups on Whatsapp, Telegram, Signal, etc.
> 
> ![Frame 3](https://user-images.githubusercontent.com/35233054/186685862-17985b8e-a9b1-4b2d-8d53-1f13a7b7d196.png)

So is this the final desired look ?

**Comment by hesterbruikman** [comment]
So there are two flows, two designs, one component [see here on Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=7877%3A229756).

These are designs using the component for the two flows:
- blank screen on invite people to community when user has no contacts
![186459310-a6a9a29c-2d0e-4d7c-b67d-c168e2adf4e4](https://user-images.githubusercontent.com/35233054/187861538-ad872548-c1e2-441f-bd62-125549f1492b.png)

- screen on going to membership requests when no one has used (deprecated) group chat invite link
![Frame 3](https://user-images.githubusercontent.com/35233054/187862313-1cdfcf0f-4856-4c58-907f-14c0ad2c7800.png)

**Comment by ibrkhalil** [comment]
> So there are two flows, two designs, one component [see here on Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=7877%3A229756).
> 
> These are designs using the component for the two flows:
> 
> * blank screen on invite people to community when user has no contacts
>   ![186459310-a6a9a29c-2d0e-4d7c-b67d-c168e2adf4e4](https://user-images.githubusercontent.com/35233054/187861538-ad872548-c1e2-441f-bd62-125549f1492b.png)
> * screen on going to membership requests when no one has used (deprecated) group chat invite link
>   ![Frame 3](https://user-images.githubusercontent.com/35233054/187862313-1cdfcf0f-4856-4c58-907f-14c0ad2c7800.png)

So one for groups and one for communities .. I am going to do the community one for this issue

**Comment by ibrkhalil** [comment]
@hesterbruikman 
@qoqobolo

**Comment by hesterbruikman** [comment]
I'm not sure what the best approach is. This is a new component so perhaps it should be implemented first as a separate issue and applied here. Is there any UI call this week for you to agree on this with the team?

**Comment by ibrkhalil** [comment]
@hesterbruikman  I think it was today, But we have design channels, will save us a whole week of waiting 😉

**Comment by churik** [comment]
don't think it is still relevant in terms of new ui. Please, reopen if still makes sense.
