### ISSUE TITLE
Implement request to join communities flow in the new UI

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13817]
As a user
I want to be able to request to join a community
So that I can participate and read messages

### Description

We should implement the screens in the new UI for joining a community.
For now, ignore token gated communities.

The initial screen is:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1355%3A111104 (that should be already implemented by @jo-mut )

Then follow the manual approval step:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1356%3A115613

Ignore captcha & rules screens and you can land directly on:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1401%3A108004

Of this screen only `Leave community` and  `Share community` are implemented

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1401%3A108067

All of these are also implementable:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1401%3A115668
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1387%3A104203
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1386%3A110589

Some of the data might not be available for a community yet (Tags, number of users for example), in that case it's fine to mock the data.

**Comment by jo-mut** [comment]
@cammellos @J-Son89 I will get it merged

**Comment by flexsurfer** [comment]
@J-Son89 @jo-mut can we close this ?

**Comment by J-Son89** [comment]
not just yet, I was waiting for page nav component which has just been merged so putting that into the design. 
There is also some advanced styling features which I need to discuss with @cammellos whether I put in another feature or put it as part of this work.
