### ISSUE TITLE
Empty white boxes instead of send messages are shown in 1-1 chat after upgrade [send]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1382]
### Description

*Type*: Bug

*Summary*: Empty white boxes instead of send messages are shown in 1-1 chat after upgrade [send]

After upgrade:

![screenshot_20170629-125547](https://user-images.githubusercontent.com/6584810/27684603-64b9d57a-5cd3-11e7-971f-589ad97cef60.png)
Before upgrade:
![screenshot_20170629-125150](https://user-images.githubusercontent.com/6584810/27684596-5c154ca6-5cd3-11e7-9ab3-bf2d4f81552f.png)

#### Expected behavior
Same send messages are shown in 1-1 chat after upgrade as they were before upgrade
#### Actual behavior

Empty white boxes are shown after upgrade
### Reproduction

- Open Status installed from PlayStore (v 0.9.9)
- Send some eth in 1-1 chat and receive some eth
- upgrade from 0.9.9 to `send` PR
- open same 1-1 chat

### Additional Information
* Status version: 0.9.9
* Operating System: Android and iOS

**Comment by alwx** [comment]
Fixed in latest commit

**Comment by annadanchenko** [comment]
all send/request messages are now removed in 1-1 chat after upgrade (expected)
