### ISSUE TITLE
The features i really miss in Status

### ISSUE THREAD

**Issue by cizz0r** [status-im/status-react#13826]
Hello, i am regularly using Status as a way to chat with someone from China because it doesn’t need VPN, but there are some things we really really need.

In priority: 

1 - Sending files
2 - Sending videos
3 - Do video/audio calls

4 - we just want to chat, being able to disable that crypto stuff
5 - Being able to view sent media 
6 - Search through chat history
7 - (She says notifications don’t work, she uses android without play services)

This is the reason we still normally use the unsecure wechat, and only switch to status when talking stuff like politics and that…

**Comment by du64** [comment]
I would LOVE to be able to disable individual features. I just want chat and web browsing, I already have a dedicated wallet app

**Comment by du82** [comment]
That's cool, I use Status to do business in China, it works well because it's P2P, no servers or WeChat necessary :)

I'll relay your feedback to the rest of the team. I also want to be able to disable features I don't use...
