### ISSUE TITLE
UI Component : Toast 

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#13831]
This issue is created to track progress on Toast Component

Design : https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3928%3A77614

**Comment by siddarthkay** [comment]
need this component for https://github.com/status-im/status-mobile/issues/13439
I have to discuss animations with Pedro

**Comment by yqrashawn** [comment]
Also need this for delete for me ui https://github.com/status-im/status-mobile/issues/13873
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4277%3A511682

**Comment by siddarthkay** [comment]
@yqrashawn : I'll keep you posted on its progress :)

**Comment by yqrashawn** [comment]
Looked into this a bit, better take https://github.com/status-im/status-mobile/issues/14296 in-app notification together. 
They should share the same container handling 
1. base style
2. interaction
3. anmation
4. state management
