### ISSUE TITLE
After upgrade: 'command=send' instead of 'Send transaction: x ETH' is shown in Chats [send]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1383]
### Description

*Type*: Bug

*Summary*: After upgrade: if send transaction was done before upgrade then it's shown as 'command=send' in chats
![screenshot_20170629-125602](https://user-images.githubusercontent.com/6584810/27685687-f8763aac-5cd7-11e7-9dc0-838e38226a5e.png)

#### Expected behavior
'Send transaction: x ETH' is shown in Chats 
#### Actual behavior

'command=send' in chats
### Reproduction

- Open Status installed from PlayStore v 0.9.9.
- Send some eth in 1-1 chat, so the last messages in Chats is "Send ETH: x ETH"
- upgrade from 0.9.9 to `send` PR build
- open Chats

### Additional Information
* Status version: 0.9.9
* Operating System: iOS and Android

**Comment by alwx** [comment]
Fixed in latest commit

**Comment by annadanchenko** [comment]
all send/request messages are now removed in 1-1 chat after upgrade (expected)
