### ISSUE TITLE
Redundant `Confirm seed phrase` screen is displayed for a moment when creating a new multiaccount using Keycard (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13836]
# Bug Report

## Problem 
An extra `Confirm seed phrase` screen is displayed for a moment when completing the creation of a new multi-account process using Keycard. See the video below on 0:04. 
Sometimes (on some devices) the flow gets stuck on this screen which makes it impossible to complete the process.

Device on which the issue with the stuck screen was reproduced: Samsung S21

#### Expected behavior
Redirect to the `Private notifications` screen immediately after confirmation of the second word and tapping Keycard

#### Actual behavior

https://user-images.githubusercontent.com/67952253/185942091-21babe9c-69e2-47c4-8655-76367a55efc3.mp4

### Reproduction

1. Install Status
2. Tap `Get started` > `Generate keys` > Choose a chat name > Choose Keyacard as key storage > `Begin setup` > Create and confirm the passcode > Back up and confirm seed phrase
3. Tap Keycard
4. Keep an eye on the screen

### Additional Information

- Status version: nightly 22/08
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
> Sometimes (on some devices) the flow gets stuck on this screen which makes it impossible to complete the process.

Hi @qoqobolo, I am unable to reproduce this issue. (tested on Samsung S21 FE)
Still, Please let me know if linked PR fixes this issue, otherwise we can create a separate issue for it?
As this doesn't look related to the redundant screen, might be caused by some other bug.
