### ISSUE TITLE
Sync contact requests accepted/declined before pairing 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13855]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user with two devices
When I accept a contact request on one device _before pairing_ I want it to be accepted on the other device _after pairing_
So that I don't have to accept/decline the request on the other device after pairing

### Description

Leftover from https://github.com/status-im/status-mobile/pull/13776

**Steps to reproduce:**
1. UserA has device1 and device2
2. UserB sends a contact request to UserA
3. UserA accepts the request
4. UserA syncs device1 and device2

**Expected result:** the request is accepted on device2 after pairing

**Comment by rasom** [comment]
introduced in 2c1bfcd0922204c7a07d5dd11d0e8b675e82329d

**Comment by rasom** [comment]
likely caused by https://github.com/status-im/status-go/commit/31671ea040852e24dbcae0e7e87f7989da701dff
