### ISSUE TITLE
Implement "Forward" option for messages

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13869]
# Feature Issue

### User Story

As a user, I want to forward a message **so that** I can share it within other Status users. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A631636

<img width="275" src="https://user-images.githubusercontent.com/18485527/187117579-9c0bebe4-3633-4cf5-a8ea-938e92bca472.png">

**Comment by cammellos** [comment]
closing as not in mvp
