### ISSUE TITLE
Transactions do not appear in Wallet if change Fee to the cheapest one [send]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1386]
### Description

*Type*: Bug

*Summary*: None of transactions sent with cheapest Fee appear in the Wallet and on ropsten. All subsequent transactions (even if use default Fee or set to the highest) also do not appear in the Wallet. If relaunch app and send ether with default of highest fee then it's shown in the Wallet.

#### Expected behavior
Transactions appear in the Wallet, ether is moved to another account 
#### Actual behavior
1. 1-1 chat shows send message for both sender and recipient
2. Wallet does not contain new transaction, also if check on https://ropsten.etherscan.io/

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7SFQ0WFRGcFB6SU0
- as contact A: send to contact B 0.2 ETH using the lowest Fee
- as contact B: in 1-1 chat with A check that message about sending 0.2 ETH is shown
- open https://ropsten.etherscan.io/ and search by address of the contact A to view transaction. Currently transaction of 0.2 is not shown (even if wait for 10 minutes)
- as contact A: send to contact B 0.3 ETH with highest fee
- on https://ropsten.etherscan.io/  check if new transaction is shown for contact A

### Additional Information
* Status version: 0.9.8-54-g363bd0d+
* Operating System: both iOS and Android
contact A: Real device Samsung Galaxy S6, Android 6.0.1
contact B: Real device iPhone 6s, iOS 10.2.1

**Comment by annadanchenko** [comment]
@alwx issue can be reproduced on develop build 0.9.9d63 (iOS)

**Comment by annadanchenko** [comment]
can't reproduce anymore

**Comment by annadanchenko** [comment]
Can be reproduced with same steps on develop build#235

**Comment by goranjovic** [comment]
Reproduced this even with second to lowest fee setting. The transaction never completes and is not visible on etherscan and the same happens with all subsequent transactions from that account. 

The only way to unblock the account is to delete the app and recover the account, which hints that the cause of the issue is in data persisted on the device.

**Comment by goranjovic** [comment]
This behavior is by design, the issue happens when tx fee is too low and the fix is to restart the app.
The proposed fix is to increase the minimum suggested fee in the UI.

tiabc:

>So it's a queue.
When you send a transaction, it gets assigned a nonce (just an incrementing number).
If you send a transaction with a low fee which is never mined, all subsequent transactions won't be mined as well.
Just because they have a higher nonce and miners won't even process them.
All that, as I know, is happening on the local memory queue. If you restart the application, that memory pool is gone and you can start sending transactions again.
As I can see, we just need to increase the minimum possible fee to the amount miners accept.

**Comment by goranjovic** [comment]
@annadanchenko Something just occurred to me, you probably tested this with very small amounts of eth, same as I did, in order to ration the ether in test accounts. Is that right?

**Comment by goranjovic** [comment]
Payments from Ethereum Wallet
Amount: 0.0001 eth

Fees (highest to lowest):

-  1 - 0.000966 Ether - [link](https://ropsten.etherscan.io/tx/0x5f2d6a3238fe4b48e34dd44706f33b8f7f04fb93408bf23aa86b54a358dc0ea4) ✓
-  0 - 0.000483 Ether - [link](https://ropsten.etherscan.io/tx/0xe2a6463318ca78a94d62a9017131a7c813e2d0ff70a3e46d02333e9390146b45) ✓
- -1 - 0.000252 Ether - [link](https://ropsten.etherscan.io/tx/0x96bc237479e1a2e1caf2c6c7a0aeeae6462ced502b00e9489bfb678deeaf2930) ✓
- -2 - 0.000126 Ether - [link](https://ropsten.etherscan.io/tx/0x90ddcb608410f5fd8f88d11b7922e1dd89b894662c57af6c84b9372b5daa1be5) ✓
- -3 - 0.000063 Ether - [link](https://ropsten.etherscan.io/tx/0x9240a4071050a24f47b517888e395b93e5e944a5ba5bddaebdcfd2bcec13fdfe) ✓
- -4 - 0.000021 Ether - [link](https://ropsten.etherscan.io/tx/0x4599509aa45c141e77bbcfe1eacddfb9bc487e3ae182fda8ce78719f7f407372) ✓


Payments from Status
Amount: 0.0001 eth

Fees (highest to lowest):

-  2 - 0.0009467 Ether - [link](https://ropsten.etherscan.io/tx/0x1b6be6d88b332a61291ddfe3164ca72a3ec64be6134771d2775d736b79600989) ✓
-  1 - ~0.0006762~ 0.0004830 Ether - [link](https://ropsten.etherscan.io/tx/0x6b8b12eb2a6fd2483bcba6955581185c686d7f47df152b36ff691ac0cc63f0e5) ✓
-  0 - 0.0004830 Ether - [link](https://ropsten.etherscan.io/tx/0x8d32ae15c752a4b5588bde55733820f1c09e81fd56cfa8c91b6f3ace34b5c61a) ✓
- -1 - 0.0003449 Ether ✘
- -2 - 0.0002142 Ether  ✘

In a separate run:
- -2 - 0.0010710 Ether [link](https://ropsten.etherscan.io/tx/0xe3e1a65c1ec2779e5a16a91db0b95aa0f2ddb43035d4cf22651bf7f06b11ab1f) ✓ 

In two different cases the lowest case did and did not go through. Worth noting that it did go through when all the prices (not just the lowest) were a lot higher.

Either way, Ethereum Wallet transactions went fine with significantly lower fees around the same time, so something definitely is not right.

**Comment by yenda** [comment]
On my device I can move the cursor for gas as much as I want it doesn't change the Fee so cannot reproduce anymore as we seem to be using a default fee that can't be changed now

**Comment by yenda** [comment]
Outdated

**Comment by annadanchenko** [comment]
@yenda there is an issue that Fee does not change, so this was a reason for you not getting this issue. In fact there is still scenario that works for changing Fee. See #2220

**Comment by annadanchenko** [comment]
Verified ok in last develop with min and max fee - can see transactions on etherscan sent with mean fee from 1-1 chat
