### ISSUE TITLE
Implement "Mention @{sender}" option for messages

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13871]
# Feature Issue

### User Story

As a user, I want to see an option to mention the sender of a message **so that** I can tag him/her get his/her attention. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A631636

<img width="275" src="https://user-images.githubusercontent.com/18485527/187117579-9c0bebe4-3633-4cf5-a8ea-938e92bca472.png">

**Comment by cammellos** [comment]
Closing as post mvp
