### ISSUE TITLE
Implement “Copy text” option for photo(s) messages with text

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13875]
# Feature Issue

### User Story

As a user, I want to copy text of a message with photos + text **so that** I can paste it on other places. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A634056

<img width="297" src="https://user-images.githubusercontent.com/18485527/187119848-c069c874-6599-4527-9508-c6870118c173.png">

**Comment by cammellos** [comment]
closing as post mvp
