### ISSUE TITLE
Implement “Save all images to library” option for messages with multiple photos

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13874]
# Feature Issue

_Blocked until we have support for multi-photos messages_

### User Story

As a user, I want to save all images to library **so that** I don't need to save them one by one. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A632233

<img width="195" src="https://user-images.githubusercontent.com/18485527/187119564-8f260b8b-7577-4d1b-b3bd-bd2611cfce8b.png">

**Comment by cammellos** [comment]
closing as post mvp
