### ISSUE TITLE
Implement "Add to favorites" option for GIF messages

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13878]
# Feature Issue

_This is blocked until we have support for GIF messages_

### User Story

As a user, I want to add a GIF from a GIF message to favorites **so that** I can find it easily the next time 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A633149

<img width="293" src="https://user-images.githubusercontent.com/18485527/187120437-bbf14c73-38b0-458d-ad0d-96cd50535561.png">

**Comment by cammellos** [comment]
closing as post mvp
