### ISSUE TITLE
Implement “Open in Dapp browser” and “Open in default browser” option for messages with a link

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13877]
# Feature Issue

### User Story

As a user, I want to open a link **so that** I can interact with the content on the Status or the default browser. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A633454

<img width="253" src="https://user-images.githubusercontent.com/18485527/187120305-639cb16c-ce38-4a30-9b7c-d63751c1a3d1.png">

**Comment by cammellos** [comment]
closing as psot mvp
