### ISSUE TITLE
Add kick and ban options for messages inside communities channels

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13872]
# Feature Issue

### User Story

As an admin, I want to kick and ban senders of a message **so that** I can better moderate group chats and communities. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A636170

<img width="199" src="https://user-images.githubusercontent.com/18485527/187118961-a4054e1f-b7b8-4dd0-90de-935556f046b4.png">

**Comment by hardiktheprogrammer** [comment]
Hey i can build for  you , can you approved my gitcoin bountie approval 
Id -@hardiktheprogrammer
Discord id -hardik#5890

**Comment by Sixto5** [comment]
Hey @briansztamfater 

Thank you for sharing this project!

I'm reaching out to share our invitation to support your issue via OpenQ marketplace. We are permissionless and free, see more here: [https://www.openq.dev/](https://www.openq.dev/)

Zero hassle from your side 🙂 We will mirror your bounty, adding the same budget.Devs from our community might solve your issue. So then we can support you meanwhile our marketplace grows.

If you give me your thumbs up we will do it and share the link again here to you for full transparency!

**Comment by cammellos** [comment]
Closing as post mvp

**Comment by hardiktheprogrammer** [comment]
@cammellos  No problem
