### ISSUE TITLE
Empty Console after installation, can't proceed using the app [HUAWEI only?] 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1388]
### Description

*Type*: Bug

*Summary*: 2 Instabug reports (both HUAWEI devices with OS Level 24): Nothing is shown in Console (not only password request but welcome text too), so no way to proceed using the app. On re-install same thing happens (tried 5 times)

Instabug:

![bug_2](https://user-images.githubusercontent.com/6584810/27729301-06200910-5d8e-11e7-9035-bfebc55952de.jpg)
![bug_1](https://user-images.githubusercontent.com/6584810/27729306-0bceca36-5d8e-11e7-83d9-a015c9573793.jpg)

#### Expected behavior
Console with welcome text and password request
#### Actual behavior
Empty Console window with no text, no commands

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/813
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/763

### Additional Information
* Status version: 0.9.9
* Operating System: Android, OS level 24. HUAWEI VTR-L09 and HUAWEI HUAWEI VNS-L21

**Comment by AlessandroSpallina** [comment]
What means help to reproduce? I have Huawei devices

**Comment by annadanchenko** [comment]
@AlessandroSpallina It means that we need help to reproduce the issue: video, logcat and extra info on you device/OS, any special settings that exist on the device. If you can reproduce it: Is it always reproducible? What happens if re-launch app for several times (3-4)? If re-install and try again?

**Comment by AlessandroSpallina** [comment]
Ok, my device is Huawei p10, stock rom, no root, no developer option enabled, so, vanilla OS. 
This issue is ever reproducible, I tried to uninstall and reinstall app several times, same if I kill the app and relaunch it! So, with my phone I never see any output from any chat! 
I am here, ask me what you need and I can give you

**Comment by annadanchenko** [comment]
@AlessandroSpallina shake the phone after getting that empty screen and use option Report a problem to send to us logs from the app, please!

**Comment by AlessandroSpallina** [comment]
Done

**Comment by AlessandroSpallina** [comment]
Any news?

**Comment by AlessandroSpallina** [comment]
Hey, you can close this issue, now works!
