### ISSUE TITLE
App should not allow to request invalid sum (NaN ETH Request) [send]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1389]
Type: Bug

**Summary**: /request command accepts invalid requests, for ex:

 /request "Acc1" 0,**q** ;  **0;3** results into NaN ETH
/request "Acc1" **+,1** ; **-,1** results into 0,1 ETH

**Expected behavior**

It should not send such requests, error “not valid amount” is expected

**Actual behavior**

NaN ETH request 

![screenshot_2017-06-30-14-01-21](https://user-images.githubusercontent.com/28752642/27733155-4436a8b2-5d9d-11e7-951e-88d9d06dddcd.png)

**Additional Information**

Status build: http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-d74369.apk
Operating System: Android 6.0.1

**Comment by annadanchenko** [comment]
verified ok on develop (Android) http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-06bff3.apk
