### ISSUE TITLE
Add Read/Unread accordions section for activity center in the new UI

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13895]
We should start to implement behavior in the activity center.

We can start from the Read/Unread accordion.

As part of this task we should:
- Implement the read/unread accordions
- Show unread notifications under unread
- Show read notifications under read

The styling of the actual notifications is not important for now, just the read/unread accordions.

We will provide two new endpoints from status-go:

`GetUnreadActivityCenterNotifications`
and
`GetReadActivityCenterNotifications`
and provide pagination.

### Designs

https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=2220%3A73630

### Animation

Animation and behavior for reference, but does not need implementing

https://user-images.githubusercontent.com/1017008/187483327-46b3f175-42fc-41e8-8007-f598c121521b.mp4

**Comment by ilmotta** [comment]
FYI: The Design team is working on a new way to display read/unread notifications, such that it doesn't confuse the user with two infinite scroll sections.
