### ISSUE TITLE
App crashes if delete part of recipient name and select it from suggestions again [send]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1390]
### Description

*Type*: Bug

*Summary*: In send or request commands: delete part of the recipient name, suggestions will show, select same recipient -> app crashes

#### Expected behavior
Recipient name is updated in input field
#### Actual behavior
app crashes

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Y1gwNFN1eDlPUEk
- Open Status
- Open 1-1 chat
- tap on send or request command
- select recipient name
- tap on delete key on the keyboard to delete part of the name (enough to delete 1 character)
- suggestions are shown with recipient name again
- in suggestions, tap on the name -> crash

### Log
[logcrash45.log.txt](https://github.com/status-im/status-react/files/1114962/logcrash45.log.txt)

### Additional Information
* Status version: 0.9.8-56-gd743691+
* Operating System:  Real device Samsung Galaxy S6, Android 6.0.1

**Comment by oskarth** [comment]
Unable to reproduce crash on iOS simulator (but mouse cursor moves in a weird way). Able to reproduce on Android Simulator with:

```Error while updating propery 'selection' of a view managed by AndroidTextInput```. Looking into it.
