### ISSUE TITLE
Long/heavy audio messages are not sent

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13914]
# Bug Report

## Problem 
Audio messages longer than 1:25 (mostly with silence (no content)) get stuck in a pending state and never reach the recipient, relogin doesn't help. 
Probably the content of the message also affects the maximum length of a message that can be sent.

#### Expected behavior
Can send audio messages of any length (within 2 minutes) 

#### Actual behavior
<img width="394" alt="Screenshot 2022-09-01 at 15 45 11" src="https://user-images.githubusercontent.com/67952253/187929688-5e184fd8-f57e-4551-b1e8-3ac85cbff1f5.png">

### Reproduction

1. Start 1-1 chat
2. Record an audio message longer than 1:25
3. Send

### Additional Information

- Status version: RC 1.20
- Operating System: Android, iOS

### Logs 
[geth.log](https://github.com/status-im/status-mobile/files/9470364/geth.log)

**Comment by cammellos** [comment]
Relevant logs:
```
t=2022-09-01T13:42:07+0000 lvl=eror msg="failed to send a datasync message" error="huge messages are not allowed [0x49b5794d2dbefd50bf66f1cea6e0530e03b530e0b30400ed9203c9cbd6b76638][1353605][1048576]"
t=2022-09-01T13:42:07+0000 lvl=eror msg="failed to send message" error="huge messages are not allowed [0x49b5794d2dbefd50bf66f1cea6e0530e03b530e0b30400ed9203c9cbd6b76638][1353605][1048576]"
```

The message size it's 1.3MB, so this one should get compressed before being able to send it.

**Comment by Samyoul** [comment]
@qoqobolo Could you share an example of a file that isn't working? Thank you :)

**Comment by qoqobolo** [comment]
@Samyoul unfortunately, there is no way to share an audio file as we can do this with images, it has to be recorded inside the application.
You can reproduce it on a real device: just record silence for 1:30 - 2:00 and try to send it in 1-1 chat

**Comment by Samyoul** [comment]
The current library used for audio recording and playback is : https://www.npmjs.com/package/@react-native-community/audio-toolkit

But it appears to not be supported any more https://github.com/react-native-audio-toolkit/react-native-audio-toolkit/issues/272 and does not support `wav` output.

There is an alternative lib that is more supported but it doesn't support `wav` output either : https://github.com/hyochan/react-native-audio-recorder-player/issues?q=is%3Aissue+wav

There is another alternative lib that is not supported it seems BUT does support `wav` : https://github.com/goodatlas/react-native-audio-record

It would be helpful to have a lib that can record to `wav` rather than `aac`, as `wav` is easier to perform postprocessing on in Go. We can then re-encode the data into `aac` before transport.

**Comment by Samyoul** [comment]
This go lib https://github.com/gen2brain/aac-go can be used to perform post-processing and seems to be 100% pure Go, BUT it can only do AAC encoding and not the required decoding, therefore the input audio needs to be `wav`, or I need to figure out how to pass a byte-stream reader into the `aac` encoder.

This lib can perform AAC decode and encode, BUT it requires a none standard setup to import C libs https://github.com/izern/go-fdkaac

**Comment by audriu** [comment]
I will create a branch with this lib https://github.com/goodatlas/react-native-audio-record.

**Comment by Samyoul** [comment]
A little note about the work I did on this issue.

Unfortunately there is a bug that I don't really have want to spend more time resolving, it is really taking too much time to resolve. Basically the process hangs for some encodings params, I don't know why, but it hangs indefinitely and that is a big problem and if I try to interrupt the process I get a segmentation violation crash. And recover isn't seeming to work. Also it would be better if we can decode AAC and then re-encode to AAC, so this whole PR is a massive wash.

I'm closing the PR, but I'll not delete it to make the work available in case we revisit this issue at some point in the future. I'm regrettably resigning from this issue. 

https://github.com/status-im/status-go/pull/2853

**Comment by Samyoul** [comment]
Consider https://github.com/edgeware/mp4ff as a point for research when/if this issue becomes more important.

Ooooor, we could just implement global file chunking for any file that is less than ~10mb (or whatever) and then you don't need to worry about Waku transport limitations (so much).
