### ISSUE TITLE
New component preview area isn't using the full width available

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#13913]
# Problem

As pointed out by @xAlisher in recent internal discussions, the new UI components are previewed in a smaller _viewport width_ than what's in Figma. This creates friction for designers to review components because they have to scale images, and thus have a hard time seeing if they perfectly match with what's in Figma.

Below is a screenshot of one of @xAlisher's analysis:

<img width="600" alt="Screenshot_2022-09-01_at_15 14 30" src="https://user-images.githubusercontent.com/46027/187914417-062a8e1b-faa0-4676-833e-2cf09b379157.png">

## Acceptance Criteria

Make the preview area of the component occupy the full width available.

**Comment by xAlisher** [comment]
Backlink https://discord.com/channels/624205794384281629/1009838421797245099/1014870308026597456

**Comment by ibrkhalil** [comment]
I think this isn't an issue because what's happening is `padding` is being added by the developer so that'll make the view smaller
ref: [padding:16](https://github.com/status-im/status-mobile/pull/13882/files#diff-ee8e2f9fcc01956e83d0059c92693e71c7483772257e029198ec1f0e3eb5ce48R151)

**Comment by Parveshdhull** [comment]
will be fixed in https://github.com/status-im/status-mobile/pull/14055
