### ISSUE TITLE
Keycard confirm seed phrase screen back button is not working correctly

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13925]
# Bug Report

## IOS
On the IOS Back button keeps opening new screens over each other

https://user-images.githubusercontent.com/17097240/188314973-f8ec1c0f-55a2-42ee-974c-3a268b5d4f1a.MP4

## Android
On the first word screen, it doesn't do anything, but on the second-word screen it reopens the same screen

https://user-images.githubusercontent.com/17097240/188315057-07e0c1e0-e0db-49f6-9918-125b3412eab9.mp4

Due to this weird behavior of back button, I also came to a state where it created an account only by confirming one seed phrase

https://user-images.githubusercontent.com/17097240/188315130-1e6293a3-d71c-4961-9135-e7eacc32c095.mp4

### Reproduction
1. Install Status
2. Tap `Get started` > `Generate keys` > Choose a chat name > Choose Keyacard as key storage > `Begin setup` > Create and confirm the passcode > Back up and confirm seed phrase
3. Tap Keycard
4. Press Back button on Confirm seed phrase screen

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### Solutions:
1. The back button should close all screens and return to the Backup seed phrase screen, same as the cancel button. But as the cancel button already does that, it might look a little weird
2. The back button should open the first-word screen if pressed on the second-word screen. But it looks unnecessary to me. As the user already confirmed the first word, I can't think of any reason why he/she might want to go back to that screen. Also, It is a little hard to do this with current navigation where we are replacing the seed phrase screen instead of opening new. So we have to fix this navigation and have to make sure both screens subscribe to the correct word. But probably we are going to redesign keycard flow, so rewriting this navigation looks a little counterproductive
3. Remove the Back button (It is not doing anything important)

wdyt?

cc: @churik @qoqobolo

**Comment by churik** [comment]
I'm totally OK with 3d option in terms of this flow
And thank you for looking at it!
