### ISSUE TITLE
First line in the input field is cut if recipient name is 2 lines long

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1393]
### Description

*Type*: Bug

*Summary*: First line is cut and not fully visible (only bottom half can be seen) If recipient name is long enough and takes 2 lines. Same happens if in total name and sum take 2 lines:
1. Name is long (takes 2 lines)
![screenshot_20170630-190928](https://user-images.githubusercontent.com/6584810/27746540-4ea7c212-5dd0-11e7-9d4a-0b984f79e6a5.png)

2. Sum and name are long (in total take 2 lines):
![screenshot_20170630-190439](https://user-images.githubusercontent.com/6584810/27746752-0d477104-5dd1-11e7-8a18-383ba031eee7.png)

#### Expected behavior
All lines (first 4 lines) in the input field are fully visible
#### Actual behavior
First line is cut

### Reproduction

- Open Status
- Open group chat with a member who has long username, e.g. "Anna Username with several words inside"
- tap on send command and select user name. Check the content of the input field after username is inserted

### Additional Information
* Status version:  0.9.8-56-gd743691+
* Operating System: 
Real device Samsung Galaxy S7, Android 7.0

**Comment by flexsurfer** [comment]
can't reproduce on ios simulator

**Comment by annadanchenko** [comment]
Can reproduce on real Android device (Galaxy S6, Android 6.0.1) on 0.9.12 release build

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0xf1ec1e7bacce8215f0b46e5e593562e30b65bedb](https://etherscan.io/address/0xf1ec1e7bacce8215f0b46e5e593562e30b65bedb)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by annadanchenko** [comment]
Issue can be reproduced on real Google Pixel XL/Android 8.0.0 with today's nightly build (Nov 15) version 0.9.10-365-g777c9d04+ (1922). See video and log in https://app.testfairy.com/projects/4803622-status/builds/7085013/sessions/5/?accessToken=bCXzG0ncrjtoKj-PF4kzURWmS0E

**Comment by poiga** [comment]
I am working on this.

**Comment by ghost** [comment]
This fixed for all devices I could test on :)

**Comment by pablanopete** [comment]
Thanks @poiga ! Getting our QA team to look into it ASAP 👍
