### ISSUE TITLE
Crash during onboarding / migration from regular account to Keycard after password confirmation and returning back

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13943]
# Bug Report

## Problem 

There are several ways to reproduce the issue. Also, the app behaves differently on iOS and Android. 

### 1. New account creation on Android

**STR:**
1. Install Status
2. `Generate a new key` > Choose device as key storage > Create a password > Tap `Next` and quickly tap `Back`while processing is in progress
3. Choose device as key storage and create a password again
4. Tap `Next`

**Actual result:** app crashes with `java.lang.NullPointerException`

https://user-images.githubusercontent.com/67952253/188643626-526b50ab-0287-47bb-a74d-bc32cc132b20.mp4

### 2. Migration from a regular account to Keycard on Android

**STR:**
1. Install Status
2. Recover/create a regular account
3. `Profile` > `Privacy and security` > `Manage keys and storage` > `Log out`
4. Put a tick `Move keystore file` > `Enter seed phrase` > `Choose a storage` > `Keycard` > `Confirm`
5. Enter password to move your data > `Confirm`
6. Tap `Back` on the `Store your keys on Keycard` screen
7. Select `Keycard` and enter the password again > `Confirm` > Complete the onboarding flow

**Actual result:** app crashes with `java.lang.NullPointerException` after Keycard passcode confirmation

### 3. Migration from a regular account to Keycard on iOS
Most problematic one

There are the same steps to reproduce as in the previous scenario but the resulting behavior is different.
You can finish the migration process, but if you log out of the app once and try to log in again, you will get `Looks like you've tapped a wrong keycard` message.
The `lost or frozen card?` flow doesn't help either - when you try to log in after recovery, the multi-account "loses" the username and changes the user's picture (see video below). Thus, login is not possible until the application is reinstalled.

https://user-images.githubusercontent.com/67952253/188650692-bae1873a-2036-47ec-a597-af27af01c9c8.MP4

### Additional Information

- Status version: nightly 1.19
- Operating System: Android, iOS

**Comment by audriu** [comment]
I can not reproduce these at all - the app just does not go back when keys are processing.

**Comment by qoqobolo** [comment]
> the app just does not go back when keys are processing.

@audriu thanks for assigning this!
You mean scenario 1, right? Yes, I believe that a pretty slow Android device is needed to reproduce it.

Did you try scenarios 2 and 3?
There is no need to tap the `Back` button quickly there, it happens on another flow - when migrating from a regular account to Keycard.

**Comment by qoqobolo** [comment]
@audriu sorry, I forgot to attach logs. Here they are for scenario 2:
[crashlog_migration.log](https://github.com/status-im/status-mobile/files/9504544/crashlog_migration.log)

Btw today I am not able to reproduce scenario 1 on my slow device either.

**Comment by audriu** [comment]
Do you think that this https://github.com/status-im/status-mobile/pull/13922 merge may affect scenarios 2 and 3?

**Comment by qoqobolo** [comment]
Hm no, I don't think so. Just re-checked and scenario 2 is reproducible in 13922 builds.

**Comment by audriu** [comment]
In scenario 2 I have
`2022-09-08 10:56:56.043 31514-11275/im.status.ethereum.debug E/AndroidRuntime: FATAL EXCEPTION: Thread-32
    Process: im.status.ethereum.debug, PID: 31514
    java.lang.RuntimeException: Is Bouncycastle correctly initialized?
        at im.status.keycard.applet.Mnemonic.toBinarySeed(Mnemonic.java:131)
        at im.status.ethereum.keycard.SmartCard.generateAndLoadKey(SmartCard.java:391)
        at im.status.ethereum.keycard.RNStatusKeycardModule$4.run(RNStatusKeycardModule.java:141)
        at java.lang.Thread.run(Thread.java:1012)`
Interesting...
