### ISSUE TITLE
The second request becomes inactive if tap on the third one when receiving 3 requests in a row  [Send]

### ISSUE THREAD

**Issue by NataliaGrigoreva** [status-im/status-react#1394]
### Description

*Type*: Bug

*Summary*: If the user sends several request one-by-one in 1-1 chat. The reciever answers on them in the order: the first one, the third one. The second one gets unavalable. The third one can be answered twice.

#### Expected behavior
All requests can be accepted and answered once.

#### Actual behavior
If the user answers the requests in the next order: the first one, the third one (1. 0.0041; 3. 0.043). The second request gets inactive (2. 0.042). The third one is active twice (3. 0.043).  
This bug was reproduced on Android emulator (Android  6.0).  The request was sent from the device  with Android 5.0.
The bug is reproducible if the user answers the request not more than in a few minutes after requesting.  

### Reproduction
1. Launch Status app on the Android device (Sender of the requests)
2. Login with valid credentials
3. Go to 1-1- chat
4. Request 3 amounts in the following order: 1. 0.0041; 2. 0.042;  3. 0.043
5. Launch Status app on the Android emulator (Reciever of the request). 
6. Login with valid credentials
7. Go to 1-1- chat
8. Answer the requests in order 1. 0.0041; 3. 0.043

Video: https://drive.google.com/file/d/0B0pYIvdvIoAHemhPLTZyQUI3bVU/view

### Additional Information

* Status version: 0.9.8-56-gd743691+
* Operating System: Android 6.0

**Comment by annadanchenko** [comment]
can reproduce on real Galaxy S6, Android 6.0.1

**Comment by flexsurfer** [comment]
can't reproduce because 
![image](https://user-images.githubusercontent.com/11790366/28118981-ea0acaca-671b-11e7-84cc-693fac9ce32e.png)
