### ISSUE TITLE
Tenor gif preview is not shown on status mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13955]
# Bug Report

## Problem 
Whitelisted in https://github.com/status-im/status-go/pull/2832 but doesn't work on mobile client side

#### Expected behavior
Can see gif

#### Actual behavior
![IMAGE 2022-09-08 12:42:23](https://user-images.githubusercontent.com/4557972/189102595-dc703018-44d4-482a-ae0f-0b9f5e527644.jpg)

### Reproduction

1) Open Status
2) Join any public channel
3) send any tenor GIF (i.e. https://tenor.com/bWdkz.gif )

### Additional Information

- Status version: RC 1.20 6 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
status-go returns `:thumbnailUrl"https://tenor.com/bWdkz.gif"` which is redirect if you open it in the browser , thats why it won't work in the app cc @stefandunca

**Comment by flexsurfer** [comment]
```
:height 0
:width 0
```

**Comment by flexsurfer** [comment]
cc @stefandunca

**Comment by flexsurfer** [comment]
https://tenor.com/bWdkz.gif doesn't work because its a redirect

**Comment by flexsurfer** [comment]
so two issues

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-go/pull/2439

**Comment by stefandunca** [comment]
> https://tenor.com/bWdkz.gif doesn't work because its a redirect

This is a problem on desktop as well:
![image](https://user-images.githubusercontent.com/47554641/189138302-cf664333-46a7-488b-b5f6-c599a4f8d652.png)

I plan to remove `tenor.com` from the whitelist and keep only `media.tenor.com` that is returned by the API we are using. @flexsurfer will this work for mobile?

**Comment by flexsurfer** [comment]
thanks @stefandunca this will work. but we still need to fix size, width and height are 0 now

**Comment by stefandunca** [comment]
> thanks @stefandunca this will work. but we still need to fix size, width and height are 0 now

This will require fetching of an image in the best case which is quite inefficient. Hardcoding a default one will also generate scaled images.

Because this is a workaround to preview gifs from our own API the simplest way will be to use the fetched image size when width and height are `0` as we do on the desktop. Will this work for mobile?

A more appropriate solution will be to track our gifs by forwarding the preview URL we receive from tenor when requesting gifs or finding an appropriate preview system/API like oembed that works for tenor. I didn't find one by the way.

**Comment by flexsurfer** [comment]
@stefandunca how does size work for other image providers?

**Comment by stefandunca** [comment]
> @stefandunca how does size work for other image providers?

They are fetched from the "oembed" request. However, oembed request doesn't work for tenor hence the "0 size means use the fetched image size" workaround.

**Comment by flexsurfer** [comment]
it was fixed partially, only for https://tenor.com/bWdkz.gif links, but other tenor links will not work because of zero size we need to address this

**Comment by cammellos** [comment]
closing as descoped, not planned for now
