### ISSUE TITLE
Group chat history unavailable for newly added member until some action is taken (some messages can be lost)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13957]
# Bug Report

## Problem 

Sometimes (in ~90% of cases), if a user was added to a new group chat while offline, and some messages were sent in that group from other members (from admin in this particular case), then when the user comes back online, the group chat history won't be available until some action triggers it to load (lock - unlock the screen, relogin and switch to another app worked while replication). 

The waiting time for the message history to load without any actions was up to 10 minutes.

Sometimes, chat history was loaded partially (the last sent messages were more likely to be delivered).

Sometimes, some messages never load for the user. 
In order to reproduce this, you need to create several chat groups and send several messages there (while the new member is offline). The issue with the message history never loaded was reproduced with 5 groups with 10 messages in each.
In that case, ~70% of messages were eventually delivered, but nothing helped to receive the rest of the messages.

#### Expected behavior
Group chat history is loaded right after the user logged in

#### Actual behavior
Some trigger needed in most cases

### Reproduction (this is reproducible in most cases)

1. UserA and UserB are contacts
2. UserA closes Status
3. UserB creates group chat with UserA
4. UserB sends several messages
5. UserA logs in and checks the group chat
6. Wait for a while
7. If history doesn't load, try locking and unlocking the screen. The bug report also triggered the loading of the history (shake the phone and go to email, and then back to the group chat).

**Steps for `never loaded messages`:**
1. UserA and UserB are contacts
2. UserA closes the app
3. UserB creates 5 group chats with UserA and send 10 messages in each group
4. UserA logs in and checks the group chat
5. Wait for a while, try to relogin

### Additional Information

- Status version: RC 1.20
- Operating System: Android, iOS

### Logs 

UserA before any actions (in ~5 min of waiting for messages with open chat) [geth.log](https://github.com/status-im/status-mobile/files/9528374/geth.log)
UserA after screen lock - unlock  [geth.log](https://github.com/status-im/status-mobile/files/9528386/geth.log)
UserB (sender) [geth.log](https://github.com/status-im/status-mobile/files/9528392/geth.log)

**Comment by qoqobolo** [comment]
### Case with the lost messages

**Receiver:**

After ~10 mins of waiting, before relogin [geth.log](https://github.com/status-im/status-mobile/files/9534267/geth.log)
After relogin [geth.log](https://github.com/status-im/status-mobile/files/9534276/geth.log)

Messages received right after the first login
<img width="485" alt="Screenshot 2022-09-09 at 11 40 43" src="https://user-images.githubusercontent.com/67952253/189321243-d93bb501-188b-45aa-9af6-261c11f8c408.png">

Messages received after waiting ~10 mins and sending the logs (call "Report a bug" pop-up, go to email and back). 10 messages in each group were sent by Sender:
<img width="393" alt="Screenshot 2022-09-09 at 11 43 37" src="https://user-images.githubusercontent.com/67952253/189321890-062287e4-8626-42bf-8077-9db021b45c42.png">


**Sender:**

[geth.log](https://github.com/status-im/status-mobile/files/9534313/geth.log)

https://user-images.githubusercontent.com/67952253/189322168-c0388807-e542-49d4-a3f0-712058942c68.MP4

**Comment by cammellos** [comment]
So far what I am getting:
- Peer was alwasy connected to the same mailserver throughout `mail-03.do-ams3.eth.prod`
- Connection looked stable
- Requests were successful
The timestamps also checks out, I'll be looking at exactly when the peer has sent messages to cross check in the other logs

**Comment by qoqobolo** [comment]
New logs [geth.log](https://github.com/status-im/status-mobile/files/9546970/geth.log)

pk 0x043fcbe384316f331b26ec92f8eaacd55625786d7974b8ec9dc43c5c3057547187d7b4b69e419611c38ad1679b834f215b785562a6c80ec5e605b54b8bd73cdbb3 (Positive Soupy Veery)

**Comment by qoqobolo** [comment]
New users:
**Sender** `Minty Giddy Mussel` 0x04e707de8db3d21ad1efee98ed77b55f046111fd4f8d6d1271a0a80568056978f2a92f0b57da3bac9030d0831ba2236909650cb24d7e69d805c2d3a624e5be1b67
[geth.log](https://github.com/status-im/status-mobile/files/9547111/geth.log)


**Receiver**  `Nautical Green Armyworm` 0x040f4e6f3b75eaf88847b53a3c9562c21bba3ec49cfcb9cba278f6da11b58d2d3aaa8ad39ba7d261b6093a3add3d39ad96f6293e8203c5b0e0c860dc4fe74d2503

Messages received right after login (before sending logs)
<img width="542" alt="Screenshot 2022-09-12 at 12 26 38" src="https://user-images.githubusercontent.com/67952253/189631663-dc95a78c-1a1c-401e-accf-a84036300e1c.png">

Receiver's state after ~5 mins of waiting and sending logs (without relogin)
Logs: 
[geth.log](https://github.com/status-im/status-mobile/files/9547129/geth.log)

<img width="608" alt="Screenshot 2022-09-12 at 12 30 39" src="https://user-images.githubusercontent.com/67952253/189632346-44c03f6d-2e19-48ac-b350-b8db66dc3afd.png">

Logs after relogin: 
[geth.log](https://github.com/status-im/status-mobile/files/9547138/geth.log)

**Comment by cammellos** [comment]
I think I might have found the issue:
```
"can't create a new group chat without us being a member"
```
it's in the logs, likely due to the recent changes in group chat protocol.
Investigating

**Comment by churik** [comment]
Closing because of redesign / new protocol
