### ISSUE TITLE
Add Status Waku v2 nodes to fleet configuration

### ISSUE THREAD

**Issue by felicio** [status-im/status-react#13952]
# Problem

Add Status Waku v2 nodes to fleet configuration, thus allowing

- connecting to fleets that don't have v1 to v2 bridge (i.e. `status.prod`)
- cross-platform dogfooding on Status nodes

## Implementation

- Possibly extend https://github.com/status-im/status-mobile/blob/b05787b0b2883a6ebc87e276bb49965cb055a1a6/resources/config/fleets.json for https://github.com/status-im/status-desktop/blob/c2c2532986de1391bcc0cc6430da5f7d7d6d50ff/fleets.json
- And update any other files relevant to loading the configuration
  - Maybe those referencing `wakuv2-config` like `src/status_im/node/core.cljs`, `src/status_im/multiaccounts/login/core.cljs` and `src/status_im/waku/core.cljs`

## Acceptance Criteria

- When connected to a Status peer, a sent message is received by Desktop and Web clients

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/issues/14210
