### ISSUE TITLE
Opposite from actual status of contact request in activity center on paired device after sync

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13956]
Accepted contact request on Device 1 is displayed as Declined on Device 2 after sync (and vice verse - Declined appears as Accepted) 

**Steps:** 
1. Restore the same multiaccounton Device 1 and Device 2
2. Send contact request from Device 3 to Devices' 1 and 2 account
3. Accept contact request on Device 1 
4. Pair Device 1 and Device 2 
5. Sync data from Device 1 to Device 2 (tap sync all in sync settings) 
6. Open Activity center on Device 2 and check status of contact request

**Actual result:** contact request is in status Declined on Device 2. At the same time, Device 3 successfully added as a contact on both devices. 

https://user-images.githubusercontent.com/97245802/189114633-7ccceb17-c6e2-4113-a386-af571f1462fd.mp4

[Android_geth.log](https://github.com/status-im/status-mobile/files/9526489/Android_geth.log)
[IOS_geth.log](https://github.com/status-im/status-mobile/files/9526492/IOS_geth.log)

**Expected result:** contact request status should be the same (Accepted) on both Device 1 and Device 2

**Devices:** IOS/Android
**Build version:** release 1.20, nightly

**Comment by churik** [comment]
fixed in https://github.com/status-im/status-mobile/pull/13958
