### ISSUE TITLE
Two send messages instead of one are shown for one send transaction in group chat [send]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1397]
### Description

*Type*: Bug

*Summary*: All members except sender see 2 messages for 1 send transaction sent in group chat:
![screenshot_20170630-233503](https://user-images.githubusercontent.com/6584810/27753320-da21283e-5ded-11e7-8417-69906ccbe03c.png)

only sender sees 1 expected message:
![img_1915](https://user-images.githubusercontent.com/6584810/27753370-03667514-5dee-11e7-880e-3be95ed2a4d7.PNG)

#### Expected behavior
for 1 send transaction all group members see 1 send message 
#### Actual behavior
for 1 send transaction all group members except sender see 2 send messages

### Reproduction

- Open Status
- open group chat wth 2 members
- as member1 send ether to member2
- as member2 check how many send messages are shown in group chat

### Additional Information
* Status version: 0.9.8-56-gd743691+
* Operating System: Android and iOS

**Comment by goranjovic** [comment]
The extra message was intended for Wallet contact. The other side effect of the same bug was that no transaction received in group chat appeared in Wallet messages.

**Comment by annadanchenko** [comment]
tested on 3 devices (iphone 6s, galaxy 6 and iphone 7 plus): 
- all 3 members of the group chat see only 1 send message now
- Wallet contains send message (for recipient) in the same format as group chat: `/send 0.01 ETH from iphone6`
- Wallet contains send message (for sender) in the different format as group chat, instead of the recipient name there is group name in the chat:
group chat: `/send 0.01 ETH to iphone6`
Wallet: `/send 0.01 ETH to GroupName`
Ignoring this as Wallet will be re-done and issue is not introduced in this PR
