### ISSUE TITLE
Deep links with ENS names contaning non-latin chars cause endless redirect in Status browser

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13983]
# Bug Report

## Problem 
Valid ENS names can contain emoji and basically any char according to https://docs.ens.domains/frequently-asked-questions 
So `숨겨진보물.eth` is correct ENS, which is resolved in wallet / chat key field to corresponding user
However, if I open it as a deep link, I've got endless redirect.

#### Expected behavior
Can see user profile after navigating to the app

#### Actual behavior

https://user-images.githubusercontent.com/4557972/189691435-270987d3-64fa-4f55-8889-0c40c97e89bb.MP4

### Reproduction

1) Open Status, create multiaccout
2) Past in mobile browser: https://join.status.im/u/숨겨진보물.eth > Redirect me > Open in status

### Additional Information

- Status version: nightly 12/09/2022
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
### Adding for context:

https://github.com/status-im/status-mobile/blob/a489e07bd1f4450bdeb0a4b04183945a097d659b/src/status_im/router/core.cljs#L64

`(bidi/match-route routes uri)` is not returning route

related issue  https://github.com/juxt/bidi/issues/206

(didn't tested in deep, needs more research)

**Comment by cammellos** [comment]
Closing for now until we work on browser
