### ISSUE TITLE
"Generate new key" in "There's nothing to recover here" doesn't do anything in case it is not first account on device

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13981]
# Bug Report

## Problem 
Flow "Access existing keys" > "Recover with keycard" > "There's nothing to recover here" > "Generate new key" is not working on the last step - the button doesn't do anything on tap.
Issue is reproducible when it is not first multiaccount on device

#### Expected behavior
Can generate a new account

#### Actual behavior

https://user-images.githubusercontent.com/4557972/189673010-4b059464-a29b-4ba6-823d-4433e93fdbf5.mp4

### Reproduction

1) Open Status, generate new multiaccount, log out 
2) Go to access existing keys > Recover with keycard > tap empty card to get "There's nothing to recover here" (most straightforward way to get a blank card is to "Generate new multiaccount" > Keycard > tick Return card to factory settings and close app on entering PIN step)
3) Try to tap "Generate multiaccount"

### Additional Information

- Status version: nightly 12/09/22
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
interesting, it was recently fixed https://github.com/status-im/status-mobile/issues/13835

**Comment by churik** [comment]
It was fixed for the case when it is the first account on device.

**Comment by Parveshdhull** [comment]
fixed in https://github.com/status-im/status-mobile/pull/13989
