### ISSUE TITLE
The input filed text doesn't clear after double click send button(up arrow)

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1399]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  After i sent the message,  the input filed should be cleared .

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The message input filed should be cleared.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The content which i just sent still exists in input filed.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Chat with someone
- Input message in the  chat box (i just input 'HELLO')
- Double click send button quickly,  **_at the same time_** , input other message (i just input 'D')
- The input area should be cleared and should be displayed 'D' only.

![11](https://user-images.githubusercontent.com/5856990/27763088-b18df59c-5eaf-11e7-8ebe-bc591613ea6e.png)
![22](https://user-images.githubusercontent.com/5856990/27763089-b1c9858a-5eaf-11e7-90d9-507c2a301a39.png)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9d5
* Operating System: IOS 10.3.2

**Comment by jeluard** [comment]
Double click is not necessary, single click is sufficient.

**Comment by rasom** [comment]
duplicate https://github.com/status-im/status-react/issues/379
