### ISSUE TITLE
Group chat adjustments due to changes in status go

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13990]
Due to changes in Status go https://github.com/status-im/status-go/pull/2828 we need to implement corresponding changes on status mobile side according to this spec https://github.com/status-im/feature-specs/blob/3bcd4909d730bea213ad94412ed8e0077a32e7ba/content/raw/chat/group_chat.md:

1. In case if User tries to create group chat with non mutual contacts or add non mutual contacts to existing group he should be shown notification "You can only send direct messages to your Contacts". Currently in this case we do not show anything, nothing happens when User taps "Add" a new member or "Create group". 
At the same time system notification "You can only send direct messages to your Contacts" which is proposed to be used in  [spec](https://github.com/status-im/feature-specs/blob/3bcd4909d730bea213ad94412ed8e0077a32e7ba/content/raw/chat/group_chat.md) seems to me confusing. Maybe we can think about some alternative text of notification. 

3. Non admin members of group chat should have possibility to edit group's name and to add mutual contacts as group members. Currently mobile app does not show non admin member options to edit group name or adding a new member although feature is implemented on status go side.

**Comment by churik** [comment]
closing due to re-design
