### ISSUE TITLE
Implement GIF Search on Reactions Drawer

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13999]
# Feature Issue

### User Story

As a user, I want to search and send GIFs. 

#### Visual reference

<img width="637" src="https://user-images.githubusercontent.com/18485527/190169271-ddde1995-e11f-4f7f-a3e1-8b0fe9503f71.png">

Link to Figma: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3444%3A62646

**Comment by flexsurfer** [comment]
@briansztamfater i think just a regular bottom sheet should be used? probably i'll be working on stickers in parallel, because message drawer doesn't support this yet

**Comment by briansztamfater** [comment]
@flexsurfer Yes, I think we should use the regular bottom sheet. I understand that emojis will be added later to this sheet, similar to how Status Desktop works, but I am not sure. BTW - I will implement this issue UI once we have #14000 done, backend part is already implemented in `status-go`, so I will just start with some GIF fetching logic.

**Comment by cammellos** [comment]
closing as not in mvp
