### ISSUE TITLE
Seed phrase / private key disappear from the field when sending app to background during account creation in wallet (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13997]
# Bug Report

## Problem 
If put the app in the background in process of adding an account in Wallet, the filled seed phrase / private key field will look empty after returning in the foreground, but in fact, it will remain filled: if you enter the password again, the account will be added.

#### Expected behavior
- the field remains filled after returning to the foreground
or
- the field is truly cleared after returning to the foreground (like the password field) 

#### Actual behavior

https://user-images.githubusercontent.com/67952253/189956747-e20e77fd-f922-4226-b837-256b05fb568b.mp4

### Reproduction

1. Open Wallet
2. Add an account
3. Enter a seed phrase
4. Fill in all the fields
5. Put the app in the background/switch to the app preview mode
6. Re-open the app
7. Enter the password
8. Add an account

### Additional Information

- Status version: nightly 13/09
- Operating System: Android

**Comment by churik** [comment]
closing because of redesign
