### ISSUE TITLE
Transaction messages don't respect network 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13995]
# Bug Report

## Problem 
If 2 users are using different networks (i.e. `BSC` and `Mainnet`), user on Mainnet can request ETH in 1-1 chat, but user on BSC network will get request for `BNB`.
That can cause confusion for both parts.

#### Expected behavior
Something like "Transaction messages should be only available on `Mainnet`", actions are not available

#### Actual behavior

![photo_2022-09-13 15 59 54 jpeg 2022-09-13 16-01-09](https://user-images.githubusercontent.com/4557972/189921714-6fa04fb9-2b98-40b5-9701-370008b9b650.png)
So user can sign and send funds on another network.

### Reproduction

1) UserA: request some funds on Mainnet from UserB
2) UserB: switch to any other network and check chat with UserA

### Additional Information

- Status version: nightly 13/09/22
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@hesterbruikman may be we have it covered somewhere, can I get your opinion on this?

**Comment by hesterbruikman** [comment]
> @hesterbruikman may be we have it covered somewhere, can I get your opinion on this?

Great catch! I'll check if this is covered by the new designs. As well as if and how this might be addressed in the current. 

There are two scenarios for which the issues would occur:
- Multichain (L1>L2, L2>L1, L2>L2)
- Crosschain (e.g. BNB > ETH)

Leaving that as a note as we'll likely address these differently

**Comment by hesterbruikman** [comment]
@churik just discussed this issue with @John-44 and closing this issue. Can be reopened if we have new insights.

There is no loss of funds (although it will be a hassle to switch networks) and the issue will no longer occur with the new multichain design and implementation.
