### ISSUE TITLE
Mention is not centered in suggestions list if it contains only one suggestion in 1-1 and group chats (iOS)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14008]
# Bug Report

## Problem 

<img width="324" alt="Screenshot 2022-09-15 at 10 35 36" src="https://user-images.githubusercontent.com/67952253/190356737-d9ca2579-de1b-4395-822c-64b00da5df40.png">

#### Expected behavior
The line is centered vertically

### Reproduction

1. Open 1-1 chat or group chat with one invited member
2. Type `@`

### Additional Information

- Status version: nightly 15/09
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
closing because of redesign
