### ISSUE TITLE
StatusKeycard module not compatible with Xcode 14.0 / iOS 16.0

### ISSUE THREAD

**Issue by chrispader** [status-im/status-react#14002]
# Bug Report

## Problem
StatusKeycard module not compatible with Xcode 14.0 / iOS 16.0

#### Expected behavior
`make run-ios` should build without failure.

#### Actual behavior
`make run-ios` results with the following error:

```bash
** BUILD FAILED **


The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ react_native_status_keycard (in target 'react-native-status-keycard' from project 'Pods')
(1 failure)
```

The error is in the `react-native-status-keycard` package [here](https://github.com/status-im/react-native-status-keycard/blob/af61b0213adbf4b5a6bae97c85496d95007d5acb/ios/StatusKeycard.swift#L12)

and looks like so:

```swift
Stored properties cannot be marked potentially unavailable with '@available'
```

### Reproduction

1) Run `make run-ios` on a MacBook with Xcode 14.0 installed

### Additional Information

- Status version: nightly 
- Operating System: iOS
- Development machine OS: macOS

**Comment by flexsurfer** [comment]
cc @bitgamma

**Comment by siddarthkay** [comment]
since I too burned my hands with this 

![Screenshot 2022-09-15 at 5 47 53 PM](https://user-images.githubusercontent.com/64726664/190404737-8c3e3e8b-cb09-4726-bff6-a6353049af38.png)




here are links that I found useful  : 
https://stackoverflow.com/questions/41904724/using-available-with-stored-properties/43503888#43503888
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1216

**Comment by chrispader** [comment]
> since I too burned my hands with this
> 
> ![Screenshot 2022-09-15 at 5 47 53 PM](https://user-images.githubusercontent.com/64726664/190404737-8c3e3e8b-cb09-4726-bff6-a6353049af38.png)
> 
> here are links that I found useful : https://stackoverflow.com/questions/41904724/using-available-with-stored-properties/43503888#43503888 [pichillilorenzo/flutter_inappwebview#1216](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1216)

Thanks @siddarthkay ! I have seen these threads too, but also wanted to make sure, that this gets fixed in the repo as well.

**Comment by siddarthkay** [comment]
@chrispader : yes for sure, getting this fixed in the repo is the right way to go :)

**Comment by flexsurfer** [comment]
@bitgamma any updates? i feel like its a blocker for ios dev?

**Comment by bitgamma** [comment]
@flexsurfer working on it today, sorry I didn't think it was a blocker yet
