### ISSUE TITLE
Alert "failed to send message {message: not implemented} when sending first message in community channel

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14009]
Reproducing on latest nightly and release 1.20

**Steps:** 

1. Create community
2. Create channel inside community
3. Open newly created channel
4. Send very first message in channel
5. Observe an error

**Actual result:** Alert "failed to send message {code -32000, message: "not implemented"}". The following messages are sent without alerts. 

**Expected result**:  no alert on sending message

![photo_2022-09-15 13 33 54](https://user-images.githubusercontent.com/97245802/190382409-14d2411c-78fd-457c-be0c-3143a14e2402.jpeg)

[geth.log](https://github.com/status-im/status-mobile/files/9574393/geth.log)

https://user-images.githubusercontent.com/97245802/190383359-3f608881-0842-4854-b519-408e59df77c9.mp4

**Comment by cammellos** [comment]
looking at this, present in latest status-go
