### ISSUE TITLE
Cannot re-join community requiring approve via invitation link 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14003]
# Bug Report

## Problem 

If a User leaves a community that has a type `Require approval` once, they won't be able to re-join it using the same invitation link in chat. 

#### Expected behavior
New join request is sent; the admin of the community should approve it again

#### Actual behavior
No request (nothing happens in fact)

### Reproduction

1. UserA creates a `Require approval` community and post an invitation link in a public chat
2. UserB requests membership
3. UserA approves the request
4. UserB leaves the community
5. UserB taps the same invitation link in the chat to re-join the community

### Additional Information

- Status version: nightly 14/09
- Operating System: Android, iOS

### Note
Introduced in https://github.com/status-im/status-go/pull/2813 (status-mobile PR with description: https://github.com/status-im/status-mobile/pull/13847). [It was agreed](https://github.com/status-im/status-mobile/pull/13847#issuecomment-1226918717) that the issue should be fixed on the mobile side.

**Comment by churik** [comment]
It is a common issue that community links are not updated in chat, and you need to re-send it in order to have updated community view, it is caught https://github.com/status-im/status-mobile/issues/16098
