### ISSUE TITLE
Implement Sticker search on Reactions Drawer

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#14000]
# Feature Issue

### User Story

As a user, I want to search and send stickers from Reactions Drawer.

#### Visual reference

<img width="543" src="https://user-images.githubusercontent.com/18485527/190170509-23d3f7c5-effa-4314-86f2-829dad9abac7.png">

Link to Figma: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=3442%3A60225

**Comment by flexsurfer** [comment]
@briansztamfater i'll take this one

**Comment by cammellos** [comment]
closing as not in mvp
