### ISSUE TITLE
Cannot import DB  in any build except e2e

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14019]
# Bug Report

## Problem 
Currently exporting DBs working for all builds, where it is enabled while importing is only working for apk-e2e builds

#### Expected behavior
can login after importing DB

#### Actual behavior
<img width="210" alt="MyApplication 2022-09-16 13-04-32" src="https://user-images.githubusercontent.com/4557972/190625639-9e0a47e5-0588-4d6c-8a63-792d36501b15.png">

### Reproduction

1) Open Status
2) Try to import db according to [doc](https://notes.status.im/yJMuhPAGT5inXa9Zb4vMZw) with user `west dwarf festival fabric pelican gallery jewel bind snack fiction awkward second` and [db](https://drive.google.com/file/d/1PmQInw7EAVzBwsHIoNJza5a_HM6h9zPM/view?usp=sharing) on real device or emulator with arm-64 arcitecture 

### Additional Information

- Status version: nightly 16/09/22
- Operating System: Android, iOS
- Log:  [geth.log](https://github.com/status-im/status-mobile/files/9583488/geth.log)

**Comment by churik** [comment]
cc @qfrank

**Comment by qfrank** [comment]
sorry, missed the notification, i'll look into it @churik , thank you

**Comment by rasom** [comment]
I tested it locally on various devices, and from what I see it looks like permissions/file owner issue. In case if device is not rooted the only change which is needed to make it work is to run 

```
adb shell <<< "chmod 777 /storage/emulated/0/Android/data/im.status.ethereum.pr/files/Download/export.db"
```

after pushing file to the device. **Please make sure you use a correct path in that command, as I tested it on pr build it contains `im.status.ethereum.pr` in my case, but if that's nightly it should be `im.status.ethereum`.**

**Comment by churik** [comment]
updating doc, thank you for finding the reason Roman.
