### ISSUE TITLE
Can't receive message after i sign out  app

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1401]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  when app crashed or i sign out forwardly,  i should receive message which sent by my friends.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When i sign in app, i should receive message which are from my contacts.
#### Actual behavior
[comment]: # (Describe what actually happened.)
When i sign in app,  i can't see any message which sent by my contacts   
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Sign out app
- Ask contact to send message to me 
- Sign in
- Check chat group
- can't see latest message from my contact.

![66](https://user-images.githubusercontent.com/5856990/27764145-ed1b985c-5ec4-11e7-8937-9f1ad18a6143.png)
![55](https://user-images.githubusercontent.com/5856990/27764149-02f5fa82-5ec5-11e7-822b-218f56df7005.png)

Chat content screen should be same,  but my friend's is different from mine.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9d5
* Operating System: IOS 10.3.2

**Comment by yenda** [comment]
This part of the app was completely refactored and the issue doesn't exist anymore
