### ISSUE TITLE
Show pinned messages - New UI

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14023]
As a user
I want to be able to see pinned messages
So that I know the important information about a community/channel

This needs to be implemented for 1-to-1, private group chats & communities.

### Designs

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=3425%3A413546

This includes showing the banner on top with the latest pinned message,  the number of pinned messages, and showing the pinned messages https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=3505%3A368386

Depends on: #14022 

Component dependency:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=863%3A26323 Banner component

**Comment by OmarBasem** [comment]
Implementation of this issue is complete. Waiting for [dependency PR](https://github.com/status-im/status-mobile/pull/14147) to be merged first.
