### ISSUE TITLE
bchat can't be used: error resolving go-bchat.eth: no contract code at given address

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1402]
### Description

*Type*: Bug

*Summary*: If open bchat from Contacts then page with text "error resolving go-bchat.eth: no contract code at given address" is shown. Need to update bchat url or remove it from Contacts
![screenshot_20170702-140141](https://user-images.githubusercontent.com/6584810/27769306-c7c16bf2-5f2f-11e7-808a-37c5c035d86d.png)

#### Expected behavior
bchat is opened or bchat is not available in Contacts (if there is no working url for bchat)
#### Actual behavior
page with text "error resolving go-bchat.eth: no contract code at given address" 

### Reproduction

- Open Status
- Open Contacts
- Tap on bcjat

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment]
@annadanchenko looks like it works now
