### ISSUE TITLE
"Muted" property of contacts is not backed up

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14038]
# Feature Issue
Currently the "muted" property is not preserved, therefore I need to mute users one more time when restore it from multiaccount

### User Story

As a user, I want to restore muted users when recovering multi-account from seed phrase

### Acceptance Criteria

Muted contacts / users are restored from backup

**Comment by cammellos** [comment]
Closing for now, I believe this should be fixed, @qfrank feel free to reopen if necessary
