### ISSUE TITLE
No old messages (>1 year) are shown in chat view when importing DB 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14037]
# Bug Report

## Problem 
It is a blocker for re-using imported DBs.

#### Expected behavior
Can see old messages

#### Actual behavior
Messages are shown in preview, but no messages are shown when opening chat view

https://user-images.githubusercontent.com/4557972/191020765-170ecbbf-1294-4e4b-ad79-449aed6f24da.mp4

### Reproduction

1) Open Status, restore user `identify level pink lift choose winner hour onion style festival rather salmon`, log out
2) Import DB for upgrade from [here](https://github.com/status-im/status-mobile/blob/develop/test/appium/views/dbs/chats/export.db) 

### Additional Information

- Status version: release 1.19, 1.20
- Operating System: Android
- Logcat: [log_db.log](https://github.com/status-im/status-mobile/files/9599013/log_db.log)

**Comment by churik** [comment]
cc @qfrank

**Comment by rasom** [comment]
Apparently the database's integrity was compromised in this commit https://github.com/status-im/status-mobile/commit/1f7fd17ff1903dca3db24c949a1a5403301984a9 by @jakubgs 

The database from older commits works as expected.

@churik if that's it lets close the issue.

**Comment by churik** [comment]
Yes, I'll restore the previous dbs before commit. 
HUGE thank you from QA for resolving this!
