### ISSUE TITLE
Removed transaction is shown in 1-1 chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1404]
### Description

*Type*: Bug

*Summary*: There are 2 transactions in Unsigned transaction screen. If remove first one then it's shown as "sent" in 1-1 chat for both sender and recipient. Expected: transaction is removed and 1-1 chat has no new messages about this transaction. Only signed transactions should be shown in 1-1 chat. Note: Issue does not happens if unsigned transactions contain 1 transaction that is removed.

#### Expected behavior
transaction is removed and 1-1 chat has no new messages about this transaction.
#### Actual behavior
If remove first one then it's shown as "sent" in 1-1 chat for both sender and recipient.
![screenshot_20170703-151916](https://user-images.githubusercontent.com/6584810/27792739-d5765260-6003-11e7-8715-664236e09695.png)

### Reproduction
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7ZGE4UENLQWMyWHM
- Open Status
- Open 1-1 chat
- send 1 transaction of 0.1 ETH (do not sign it, close Unsigned transaction screen - tap on cross in the top left corner)
- send second transaction of 0.2 ETH
- on Unsigned transaction screen remove first transaction of 0.1 ETH (tap on cross next to it). As a result
1. Transaction is removed from Unsigned transaction screen (Expected)
2. New send message 0.1 ETH is shown for both your contact and recipient in 1-1 chat (Issue)

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by jeluard** [comment]
This issue is related to https://github.com/status-im/status-go/issues/192.

We currenlty rely on [returned](https://github.com/status-im/status-react/blob/024cf6d6b8d17e6b46cd1d10bae24a2ff2a511e4/src/status_im/commands/handlers/jail.cljs#L23) value to detect call failure.

**Comment by jeluard** [comment]
When transactions are discarded last to first there is no unexpected message created.
In this case message received at StatusModule level is:

```
{"result": {"context":{"1501551205462-d624c11e-0eeb-54e1-8cb5-b9502b189f2b":"message_id"},"messages":[],"returned":{"error":"Invalid JSON RPC response: {\"error\":{\"code\":-32603,\"transaction has been discarded\":\"transaction has been discarded\"},\"id\":132,\"jsonrpc\":\"2.0\"}"}}}
```

When transactions are discarded first to last there issue is reproduced.
In this case message received at StatusModule level is:

```
#first discard
{"result": {"context":{"1501550762668-f1563e57-ae8c-5620-bc4e-9bfb9f744440":"message_id"},"messages":[]}}
#second discard
{"result": {"context":{"1501550752327-33db6774-f9d4-55a4-bc2a-abea060eb98a":"message_id"},"messages":[],"returned":{"error":"Invalid JSON RPC response: undefined"}}}
```

It has to be noted that in the former case `message_id` from corresponding `signal-event` and context do not match (they do in the other case).

**Comment by goranjovic** [comment]
Can't reproduce this regardless of the order in which I discard transactions.

**Comment by goranjovic** [comment]
Getting this `returned` for all combinations: `{:error "Invalid JSON RPC response: {\"error\":{\"code\":-32603,\"transaction has been discarded\":\"transaction has been discarded\"},\"id\":2,\"jsonrpc\":\"2.0\"}"}}}`

**Comment by annadanchenko** [comment]
can't reproduce on develop 0.9.10-47-gb1bf5a4f
