### ISSUE TITLE
Error '1.20.0 (20220922040832) is not a function' when opening About screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14056]
**Steps:**

1. Install latest nightly build
2. Create/recover multiaccount
3. Go to Profile tab
4. Open About screen
5. Observe an error

**Actual result:** error '1.20.0 (20220922040832) is not a function' appears. After closing error modal the About screen remains empty. 

**Expected result:** no error. Data is displayed on About screen. 

![photo_2022-09-22 10 46 55](https://user-images.githubusercontent.com/97245802/191688484-a9731f8a-57fa-4652-a044-69d7df84896f.jpeg)

https://user-images.githubusercontent.com/97245802/191688085-b4fd8d87-fc6a-4eba-8f2c-cb20ba1db814.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9623522/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/9623523/Status.log)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
@rasom mistake during subs refactoring,filed a PR
