### ISSUE TITLE
ENS name turns into public key after editing message containing mention with this ENS

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14051]
**Steps:**

1. Open any chat with member having ENS name
2. Send some message containing ENS name
3. Edit the sent message
4. Pay attention at ENS name in edited message

**Actual result:** private key and part of 3 random name is displayed instead of ENS name. 

**Expected result:** ENS name should be preserved in edited message

https://user-images.githubusercontent.com/97245802/191309513-1f5b8587-51b5-405f-9a2b-bf5fffd4161a.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9609444/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/9609445/Status.log)
me

- Status version: nightly 
- Operating System: Android, iOS

**Comment by audriu** [comment]
Ok. Failed on this one. I have created [a fix](https://github.com/status-im/status-mobile/pull/14106). that works for me but not for QAs. I tried hard to reproduce but still works ok for me. Maybe someone with a fresh look can see wtf. Ping me if you need any help...
