### ISSUE TITLE
Some reactions to messages sent from offline are not delivered to receiver after sender (IOS) comes back online 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14052]
Currently I have managed to reproduce the bug only in case when sender is IOS and receiver is Android

**Steps:**

1. Start chat between User A (IOS) and User B (Android)
2. Send some message by User A or User B
3. Go offline by User A (turn on airplane mode)
4. Set all 6 possible reactions to the sent message be User A while being offline. One of the reactions should be set then unset and at last set again (as shown on the video below)
5. Go back online by User A
6. Observe how many reactions are delivered on User's B side

**Actual result**: commonly 3 - 4 out of 6 reactions are delivered

**Expected result:** all 6 reactions are delivered

https://user-images.githubusercontent.com/97245802/191316844-eab1cdeb-aaca-4fcc-a3c9-72aa3222b2cd.mp4

[sender_IOS_geth.log](https://github.com/status-im/status-mobile/files/9609712/sender_IOS_geth.log)
[sender_IOS_Status.log](https://github.com/status-im/status-mobile/files/9609713/sender_IOS_Status.log)

[receiver_android_geth.log](https://github.com/status-im/status-mobile/files/9609715/receiver_android_geth.log)
[receiver_android_Status.log](https://github.com/status-im/status-mobile/files/9609717/receiver_android_Status.log)

- Status version: nightly 
- Operating System: IOS

**Comment by churik** [comment]
closing it as we're using waku2 now and this can work differently, does not make sense for now
