### ISSUE TITLE
Autocomplete mentions in the input box

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14065]
> As a user
> 

> I want to have my mentions to be autocompleted
> 

> So that I don’t have to type the full name
> 

### Description

When inputting `@` in the input box, I should see a list mentionable users, filtered by the text following `@` 

- If I have set a nickname it should have priority over everything and should be shown here https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=2740%3A258262
- If the user has a ENS name but not a user set nickname it should be shown similarly to above
- If the user has only a display name it should be shown similarly to above
- In a one to one chat only 1 user will be in the mention box
- In a private group chat all the members will be in the mention box
- In a community all members will be in the mention box

### To be defined

- If the input box is full screen, where do we display the mention box

### Designs

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=2706%3A263716

**Comment by OmarBasem** [comment]
Done with the implementation of this issue but waiting for PR [#14098](https://github.com/status-im/status-mobile/pull/14098) to be merged first.
