### ISSUE TITLE
"pod install" failed in windows system

### ISSUE THREAD

**Issue by mutouji** [status-im/status-react#1406]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to build status-react on windows 8 os.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug?

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below) 
*Summary*: exec `pod install` in cmd window on windows8 os,，it complained 
`C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:439:
in 'help!': [!] You cannot run CocoaPods as root. (CLAide::Help)
`
### Reproduction
[comment]: build it in windows8 step by step， untill run `cd ios && pod install && cd ..`，the it occurs

- Open Status
- ...
- Step 3, etc.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by mutouji** [comment]
it seems like missing a Podfile.lock file

**Comment by HofmannZ** [comment]
Run as non root?
