### ISSUE TITLE
Create make script to generate visual tests for default renders of all quo2 components

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14069]
Depends on #14068 

Feature Issue
Reference this branch https://github.com/status-im/status-mobile/tree/jcaprani/visual-test

User Story
As a developer I want to be able to automatically create visual tests for new components so that I have less development overheads.

Description
Taking the work from this branch:
https://github.com/status-im/status-mobile/tree/jcaprani/visual-test

Decide on the best tooling to use for static parsing of the codebase. 
2 options (if not more). use cljs condo for parsing (limited data)
move quo2 screens into .edn file and parse this with javascript/node. 

Both of these approaches are in the reference branch. 

Acceptance Criteria
make script to generate visual tests
add default renders for all screens to codebase

**Comment by cammellos** [comment]
Closing for now
