### ISSUE TITLE
Integrate visual tests into CI/CD pipeline

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14070]
Depends on https://github.com/status-im/status-mobile/issues/14069

User Story
As a developer I want to be able to make changes to quo2 components and have confidence that the CI/CD pipeline will run visual tests to ensure some quality control on my latest work.

Description
Take the tests created in issue #14069 and get them to run in the CI/CD pipeline

If it is not too much additional setup, consider making this test suite only run if there is changes made to the quo2 component library.
Alternatively this could be run on a specific branch naming pattern to avoid wasting resources.

Acceptance Criteria
Add visual tests to ci cd pipeline

**Comment by cammellos** [comment]
This has been completed
