### ISSUE TITLE
Login screen is set to system appearance (light/dark mode) even if "System" is not selected in app appearance settings

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14076]
**Steps:** 
1. Open Status app
2. Go to Profile tab - Appearance - Select "Light" mode
3. Log out and close the app
4. On your device go to system settings and set Appearance to "Dark" mode
5. Re-open the app
6. Pay attention at color mode of login screen

**Actual result:** login screen has dark mode (system appearance) although light mode is selected in app settings. After login app screens are displayed in light mode.  

**Expected result:** Login screen should have appearance that is selected in app settings. 

https://user-images.githubusercontent.com/97245802/192351000-53666aab-a5e2-4cce-bcaa-be190671c727.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, user preferences are stored in the database and can only be accessed after login. Before login, we can't know the user's selection and that's why we use the system theme as the app theme. So currently it is intentional.

But maybe we can store theme selection in async storage instead of the database. @cammellos wdyt?

**Comment by pavloburykh** [comment]
> Hi @pavloburykh, user preferences are stored in the database and can only be accessed after login. Before login, we can't know the user's selection and that's why we use the system theme as the app theme. So currently it is intentional.
> 
> But maybe we can store theme selection in async storage instead of the database. @cammellos wdyt?

@Parveshdhull thanx for the explanation! Feel free to close this issue if option with async storage will not work in our case. Thank you!

**Comment by Parveshdhull** [comment]
Let's keep this open for now. We can fix this issue while implementing new ui and can test if is fixed, once the redesign is complete.

**Comment by churik** [comment]
I guess we may close it as we have a bunch of issues opened for now related to changing mode in new design
