### ISSUE TITLE
Launching app and encounter issue on iOS 10.3 simulator

### ISSUE THREAD

**Issue by andyden9** [status-im/status-react#1407]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

I am a developer, I want to launch the status app and test. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When launching freshly built app, I met this issue on iOS 10.3 simulator:

JSON Parse error: Unrecognized token '<'

__invokeCallback
    MessageQueue.js:290:19
<unknown>
    MessageQueue.js:127:28
guard
    MessageQueue.js:46:4
invokeCallbackAndReturnFlushedQueue
    MessageQueue.js:126:10

![simulator screen shot 2017 7 4 6 35 41](https://user-images.githubusercontent.com/14224413/27826939-9adb187c-60e7-11e7-95f7-41c7a66cb423.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Launching app correctly.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Can skip this issue, but the console will not respond correctly to any commend therefore can't log in.
![simulator screen shot 2017 7 4 6 36 42](https://user-images.githubusercontent.com/14224413/27826974-bea83f3c-60e7-11e7-8809-393c4d6485dd.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

I followed guide exactly to build app for development, but this issue occurs every time.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Sorry, I'm not able to provide a solution. I don't use your stack.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Latest develop branch on 4th July.

[comment]: # (Android or iOS.)
* Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by yenda** [comment]
console doesn't exist anymore
