### ISSUE TITLE
Design for channel avatar needs adjustment.

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14081]
The current implementation of the Channel avatar component is missing two pieces in the design spec.

1- The icon size might change, as such it is better to have a bounding box of 20px around the emoji so that the spacing etc is consistent but allows for emojis of different sizes to be used. 

2 - The lock/unlock icon should have an option to use a mask so that it shows the color below the channel avatar component.

reach out to design team if there is some confusion in what's needed.

Acceptance criteria. 
- Implement 1 & 2.
- get the green light from the design team.
- Adjust channel list component to use the mask feature for the lock/unlock icon.

**Comment by churik** [comment]
I believe these caught in recent design reviews, re-open if still makes sense
