### ISSUE TITLE
Autobot may start several `status-app-prs` jobs for no reason

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14089]
# Problem
Sometimes e2e jobs `status-app-prs` are triggered for no reason (no move to E2E column was performed)
It happens from time to time and may block our e2e for several hours
Example: https://github.com/status-im/status-mobile/pull/14080#issuecomment-1262125980
Jobs: 
1) https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs/2819/console
2) https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs/2816/console
![image](https://user-images.githubusercontent.com/4557972/193242128-f1bf09a7-ed71-4e2c-b13a-124337739b3c.png)

## Acceptance Criteria

`status-app-prs` are triggered ONLY on moving PR to  E2E column

**Comment by churik** [comment]
@jakubgs please take a look when you get a minute

**Comment by jakubgs** [comment]
That's just me restarting the bot trying to fix:

* https://github.com/status-im/status-github-bot/pull/55
