### ISSUE TITLE
Sometimes balance is not updated automatically after multiaccount restore (Goerli network)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14111]
# Bug Report

## Problem 
Caught by e2e, can't reproduce on real devices with same multi-accounts. Sometimes the balance is not fetched after restoring multi-account (in 30% of cases, sometimes all tx tests can be failed in PR build)
It started approx 28.09
![1-1 chat: send ETH directly to ENS - TestRail 2022-10-05 17-16-43](https://user-images.githubusercontent.com/4557972/194097345-898e5af7-5c2e-42f8-aa73-cd1497a3bebc.png)

#### Expected behavior
ETH are fetched right after multi-account restore

#### Actual behavior
no ETH in 180 sec, which makes the test fail

### Reproduction

1) Open Status
2) On PR (or e2e) build: restore multiaccount with assets on Goerli (i.e. `desert void flight crystal tilt seminar exchange detect rather keep chair sense`)
3) Open wallet and pay attention to the balance

### Additional Information

- Status version: mostly PRs builds after 28/09/22 and subsequent; can be reproduced on nightly
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
Test example: https://ethstatus.testrail.net/index.php?/tests/view/3014434, [Device session](https://saucelabs.com/jobs/d62d53a3c83d414dba2628db1347c1c0?auth=6d8823b81654370b924727b98f277506#94)

Log: [test_ens_command_send_tx_eth_1_1_chat_geth2.log](https://github.com/status-im/status-mobile/files/9716934/test_ens_command_send_tx_eth_1_1_chat_geth2.log)

**Comment by rasom** [comment]
@churik do we have Status.log for this case?

**Comment by churik** [comment]
@rasom  we have logcat, which should contain required log entries
[logcat.log](https://github.com/status-im/status-mobile/files/9808531/logcat.log)

**Comment by rasom** [comment]
ok so that's the reason 
> t=2022-10-04T19:40:36+0000 lvl=eror msg="controlCommand error" error="failed to dowload transfers using concurrent downloader: 429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"id\":334,\"error\":{\"code\":-32005,\"message\":\"archive request rate exceeded\",\"data\":{\"rate\":{\"allowed_rps\":1,\"backoff_seconds\":30,\"current_rps\":10.633333333333333},\"see\":\"https://infura.io/docs/ethereum#section/Rate-Limits\"}}}" counter=2

It can not download history and then getting balances also fails.

**Comment by rasom** [comment]
As an option we can still try to update balances even when the history can not be retrieved.

**Comment by churik** [comment]
@rasom seems reasonable to me

**Comment by rasom** [comment]
let's get back to this when UI will be ready

**Comment by cammellos** [comment]
closing for now
