### ISSUE TITLE
UI Component - Internal Link Card

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14123]
This issue is to track the creation of the component: **Internal Link Card**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=11182%3A147560&t=9WYD2Z0h926wFs72-1

Please have a chat with the design team before starting with the component

**Comment by naftalimurgor** [comment]
Hey @cammellos 
I'd like to work on this. You may assign it to me over gitcoin so I can get this done
Best,
Naftali

**Comment by hieple7985** [comment]
Where could I reach to the design team?

**Comment by enehizy** [comment]
Hi, here are the community components on the Figma link I can't find a community link component or is this a ui design bounty rather than a frontend one..
![community link](https://user-images.githubusercontent.com/39803122/212738334-1fa57f3f-e3f8-4604-bb73-3cf5dbaa7cac.PNG)
