### ISSUE TITLE
Always use dark mode theme

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14134]
## Problem

Given the UX team requirement to only support dark mode in the new Activity Center, we need to adapt the code to not dynamically use light mode colors.

As it is today (2022-10-10), when the user switches to the system light mode, the AC is completely unreadable due to white text on top of white background.

**Comment by smohamedjavid** [comment]
Closing this issue as the fix is merged with PR https://github.com/status-im/status-mobile/pull/14244
