### ISSUE TITLE
Show incremental changes of saved addresses between paired devices

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-react#14139]
# Feature Issue

Follow up on the [sync of saved addresses PR]( https://github.com/status-im/status-go/pull/2865) to add incremental sync of saved address functionality.

### User Story

As a user, I want to sync saved addresses between paired devices.

### Description

Notes

- Full sync for saved addresses is done behind the scene on a manual sync
- Incremental sync requires the following API calls changes
  - Call `wakuext_upsertSavedAddress` instead of `wallet_addSavedAddress`
  - Call `wakuext_deleteSavedAddress` instead of `wallet_deleteSavedAddress`
- Dynamic reloading of changes after sync requires processing `MessengerResponse` and checking for `savedAddresses` json array entries to be reloaded for all the wallet changes.
- Remove wallet saved addresses API endpoints that were replaced with messenger calls

### Acceptance Criteria

Devices A and B are paired
- [ ] Adding or making changes to a new address on device A will reflect in device B when online
- [ ] On the device B, when receiving a change from device A should be reflected in the saved address list (Favourites view)

**Comment by cammellos** [comment]
closing as will be re-evaluated in the scope of new wallet
