### ISSUE TITLE
Allow styling text in composer when selecting it with native actions

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14137]
# Allow styling text in composer when selecting it

| As user

| I want to be able to style some text when selecting it

| So I don’t have to learn markdown

### Description

When selecting some text, I want to be able to style it.

For reference, this is similar to how whatsapp does when selecting text.

### Designs

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2630%3A207636

**Comment by VolodLytvynenko** [comment]
Just for notes, I will leave some known issues that are not implemented yet and would be good to fix within the future PRs related to the current feature
**SSUE 1. The text is not shown as styled if a user is typing it within styling frames**

**Steps to reproduce:**

1. Open 1-1 chat with any existing contact
2. Start typing the following: **test

**Actual result:**
Text is not shown in the style
![image](https://user-images.githubusercontent.com/52490791/203418198-31e58c39-f131-4913-a039-656c5b474016.png)

**Expected result:**
The text is shown in style during the user typing it in the style frames
![image](https://user-images.githubusercontent.com/52490791/203418259-04413fcf-29b2-4104-8fac-94d24ab98df8.png)

**ISSUE 2. Text is not shown in style if the current text is wrapped into all together styles**

**Steps to reproduce:**

1. Open 1-1 chat with any existing contact
2. Type any text
3. Select current text and wrap it into a Bold style
4. Select current text one more time and wrap it in Italic style
5. Select current text one more time and wrap it in Strikethrough style

**Actual result:**
Text is not shown as styled for all selected styles
https://user-images.githubusercontent.com/52490791/203312437-3dfc2b6c-e856-40a0-b91d-8de7e614aab2.mp4

**Expected result**
Text is shown as styled for all selected styles

How it is implemented within WhatsApp
https://user-images.githubusercontent.com/52490791/203313185-7266f927-0b46-4445-a8c1-4f5dbb3d7c94.mp4
