### ISSUE TITLE
Blur the Activity Center screen background

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14133]
# Feature Issue

Blur the Activity Center screen background.

<img src="https://user-images.githubusercontent.com/46027/194847108-ad73b2af-eb4b-457c-91e5-23e020ceaf70.png" height="500" />

### Notes

Take a look at the `status-im.switcher.switcher/switcher-screen` component for an animated example of a blurred screen background. The implementation will probably be similar.

### Resources

- https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681

**Comment by ibrkhalil** [comment]
@smohamedjavid You already did this right ?

**Comment by smohamedjavid** [comment]
Yes, @ibrkhalil. Please check this PR: https://github.com/status-im/status-mobile/pull/14165

**Comment by smohamedjavid** [comment]
Closing this issue as the fix is merged with PR https://github.com/status-im/status-mobile/pull/14165

**Comment by ilmotta** [comment]
I haven't investigated why, but `develop` is displaying a solid screen background instead of a blurred one.

**Comment by ilmotta** [comment]
Fixed by https://github.com/status-im/status-mobile/pull/14398
