### ISSUE TITLE
Message drawer covers messages

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14148]
The drawer covers messages after you reopen a chat. When tapping the message box, you actually hit the message below, which causes the message actions sheet to appear

![Screenshot_2022-10-11-10-37-40-15_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/195136737-cd051e3f-0c0c-4369-853b-050b3a731709.jpg)

**Comment by ibrkhalil** [comment]
Was able to reproduce this issue on Android only .. Will fix for Android

**Comment by du82** [comment]
> Was able to reproduce this issue on Android only .. Will fix for Android

It doesnt seem to be a problem on iOS, only Android
