### ISSUE TITLE
Selected tab not highlighting

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#14153]
# Bug Report

## Problem 
When user navigates from Tab A to Tab B, the selected Tab B fails to highlight. This way is difficult for the user to know which tab is currently active

#### Expected behavior
Tab B background color should change to show that is the current active tab

#### Actual behavior
Tab B background color  does not highlight to show that its active

### Reproduction

1) Open Status
2) Quo2 Preview
3) Tabs
4) Select another tab 

https://user-images.githubusercontent.com/28704507/195412279-559dbf2a-e285-4f7c-987f-bdae0f614b62.mov

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by du82** [comment]
Can confirm, happens to me too
