### ISSUE TITLE
Sometimes error on command handling is shown if use send after app launch [send] 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1416]
### Description

*Type*: Bug

*Summary*: Sometimes, error on command handling is shown instead of unsigned transaction screen if use /send command after app is launched. If scroll to the end of the error then "Error: no suitable peers available" can be found in the text
![screenshot_20170707-135440](https://user-images.githubusercontent.com/6584810/27973504-e69c39b2-6362-11e7-984f-91e7e07ae4a5.png)
 
Last screen:
![screenshot_20170713-093229](https://user-images.githubusercontent.com/6584810/28155813-ed68b37e-67b8-11e7-87b8-470881de343d.png)

#### Expected behavior
unsigned transaction screen is shown 
#### Actual behavior
error on command handling is shown 

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7T0t2My1HdjFyZVk
- Open Status
- Open 1-1 chat
- tap on send command, type amount, e.g 0.202 and tap on send icon

### Additional Information
* Status version: 0.9.8-74-gf0847bba+
* Operating System: 
Real device Samsung Galaxy S6 , Android 6.0.1. Real device Galaxy S7, Android 7.0

**Comment by flexsurfer** [comment]
@annadanchenko i can't reproduce it, if you can, please add logs and full error text from this alert, thanks

**Comment by adambabik** [comment]
This error is sometimes visible when we run status-go tests when the blockchain is not fully synced.

**Comment by annadanchenko** [comment]
can't reproduce
