### ISSUE TITLE
Messages Contact Requests

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14164]
### User Story

As a user
I want to be able to view contacts requests from the contacts tabs on Messages home
so that I can see and respond to my sent and received contact requests

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1806%3A378603
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2010%3A507764

**Comment by du82** [comment]
@cammellos Could I get access to the Messages-for-Mobile Figma designs? I want to contribute to some of the UI dev

**Comment by cammellos** [comment]
Sure, you have to ask @pedro-et , he will be able to grant access, thank you!

**Comment by du82** [comment]
@pedro-et can I get access to the figma designs so I can contribute?
