### ISSUE TITLE
Allow user to search contacts when opening a new chat

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14174]
```
As a user
When creating a new chat with a contact
I want to be able to search for contacts
```
Search should be searching through:
1) ENS name
2) Nickname
3) Display name
4) 3 random words name (pending discussion with design team)

### Notes
- Search should clear if clicking on `x` or if a contact is selected

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=516%3A122739

**Comment by churik** [comment]
Duplicate? https://github.com/status-im/status-mobile/issues/14477

**Comment by cammellos** [comment]
@churik no, different feature, this one is when you click on Start chat, and allows you to search from the contacts you have, but it's post MPV, labelled, thank you
