### ISSUE TITLE
App is hidden after entering on iPhone 5, iOS 9.3.5

### ISSUE THREAD

**Issue by Ferraiya** [status-im/status-react#1417]
### Description

*Type*: Bug

*Summary*: App is hidden just after entering 

#### Expected behavior
app is open, the screen is active

#### Actual behavior
App is hidden just after entering 

### Reproduction
1. Launch Status

VIDEO: https://drive.google.com/file/d/0B5WergArvaY1NU9tRVNCVVlaQlE/view?usp=sharing 
https://drive.google.com/file/d/0B5WergArvaY1QUptV3lfcjZYTzg/view?usp=sharing

### Additional Information
Device/OS: iPhone 5, iOS 9.3.5
Status version: 0.9.9d5 Build 1329.105

Logs: https://drive.google.com/file/d/0B5WergArvaY1Y3FZd2VVYlJXYk0/view?usp=sharing
https://drive.google.com/file/d/0B5WergArvaY1aGswN1g0NXJLZGc/view?usp=sharing
https://drive.google.com/file/d/0B5WergArvaY1aGswN1g0NXJLZGc/view?usp=sharing
https://drive.google.com/file/d/0B5WergArvaY1eXE5MS05M0N4Zjg/view?usp=sharing

**Comment by annadanchenko** [comment]
will not fix after setting min OS to iOS 11 in #4651
