### ISSUE TITLE
Display identity requests

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14171]
# Feature Issue

Display identity requests that can be declined or accepted in the Activity Center.

![img](https://user-images.githubusercontent.com/46027/196445683-829a4bca-7003-42ae-aa05-3232e1d2a9b3.png)

### Acceptance criteria

>Given that Alice already accepted a contact request from Carol
>When Alice sends an identity verification to Carol
>Then Carol receives a new notification in her Activity Center
>And the notification message displays the challenge

>Given that Carol received an identity request from Alice
>Then Carol can either Accept or Decline the challenge

>Given that Carol received an identity request from Alice
>When Carol declines the challenge
>Then she sees the same notification change its status to "Declined"

### Out of scope

- There's no need to implement the actual acceptance flow, as this is more complex and can be done using a separate issue. A dummy event handler might suffice.

### Notes

At the moment (2022-10-18), it's necessary to use the unmerged status-go branch https://github.com/status-im/status-go/tree/feature/activity-center-read-unread.

### Figma

Identity request flows are described in https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=639%3A21926.

**Comment by churik** [comment]
I probably missed smth, but frankly can't understand the purpose of identity requests in case both users are already contacts. 
Is there any doc/explanation or someone can elaborate on it?

**Comment by ilmotta** [comment]
> I probably missed smth, but frankly can't understand the purpose of identity requests in case both users are already contacts. Is there any doc/explanation or someone can elaborate on it?

@churik, I think I'm not the best person to answer your question, but I believe the idea is that some users need to verify certain contacts are who they really think they are, for various reasons.

Imagine, for example (and this is a real case scenario), my smartphone was stolen and the thief starts to communicate with my mom before I get the chance to warn her. My mom would then be able to send an identity challenge to the thief if she thinks something is fishy, and, at least in theory, she would be able to avoid sharing unwanted secrets with the thief.

I know the above scenario is super edge case for some people, but not here in Brazil. I think there are many other scenarios to justify this feature, **but having said all this, I think the vast majority of users won't care or even know what identity verification even is**.

**Comment by churik** [comment]
> My mom would then be able to send an identity challenge to the thief if she thinks something is fishy, and, at least in theory, she would be able to avoid sharing unwanted secrets with the thief.

Thank you for the explanation.  Just wondering, why you just cannot ask it as a question instead of an identity challenge in this case and what is the benefit of this additional functionality
@xAlisher may know the answer

**Comment by ilmotta** [comment]
@churik, I'm not sure either. The user will be able to mark other users as untrustworthy in the identity verification flow, which is kind of a categorization that the Status app can take advantage of in the future. For example, the app could prevent users from transacting with untrustworthy users, etc. If this is useful or worth of our effort is beyond my understanding at this point.
