### ISSUE TITLE
Incorrect pagination of notifications

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14173]
# Bug Report

## Problem 

Read/unread notifications are not properly paginated due to a mismatch in how the frontend decodes the cursor _"string"_ sent by the backend.

#### Expected behavior

When scrolling over notifications, the user should be able to see all existing notifications stored in the local DB.

### Reproduction

There are many ways to reproduce this issue, because it happens with various combinations of notifications size and number of notifications per page.

1. Open Status.
2. Log in with a user with 3 notifications.
3. Enable the new AC flag.
4. Enable the new UI.
5. Modify the code `status-im.activity-center.core/defaults` `:notifications-per-page` to 1.
6. Open the new AC.
7. Notice only two notifications are ever displayed.

### Notes

We have pinpointed the issue to be related to how the mobile app decodes RPC responses, probably the Java code (for production env). Currently, status-go sends a `cursor` that's a DB concatenation of the zero-padded notification timestamp with its ID, but when the frontend decodes the cursor as UTF-8, it changes the precise sequence of bytes when it sends it back to fetch the next result set.

It's likely the case that only status-go will need the fix, because the mobile app doesn't manipulate the cursor, apart from storing in the app DB and sending it back to fetch subsequent pages.

### Possible solution

There seems to be more than one way to solve this problem. It's recommended to bring it up to status-go folks to get more opinions, but one solution that fixed the problem was to store the notification IDs as strings instead of `types.HexBytes`. This solution would cause a _local_ breaking change in status-go.

For reference, here's how an ID is built:

```go
// MessageID calculates the messageID from author's compressed public key
// and not encrypted but encoded payload.
func MessageID(author *ecdsa.PublicKey, data []byte) types.HexBytes {
    keyBytes := crypto.FromECDSAPub(author)
    return types.HexBytes(crypto.Keccak256(append(keyBytes, data...)))
}
````

We should probably also consider changing the pagination implementation to use `<` instead of `<=` to catch out-of-order messages. See `protocol/activity_center_persistence.go#buildActivityCenterQuery`.

**Comment by rasom** [comment]
I see two separate issues here.
1) when `:notifications-per-page=1` `:on-end-reached` is not triggered after the first fetch likely because the second notification completely fits on screen and `flat-list` "sees no reason" to request more of them (to trigger `:on-end-reached`). When we have  `:notifications-per-page=8` or something this issue becomes irrelevant. 
2) in some particular cases, and that happens only with specific cursors, not with all of them, although in SQL query we have condition like `cursor <= parameters.cursor`, the record for which `cursor == parameters.cursor` is not selected and it doesn't make it to the result set (although it should). This second one might be related to encoding/decoding. Not sure though that 
     > probably the Java code
 
     part is relevant because I reproduce this on iOS simulator.

**Comment by ilmotta** [comment]
>when :notifications-per-page=1 :on-end-reached is not triggered after the first fetch likely because the second notification completely fits on screen and flat-list "sees no reason" to request more of them (to trigger :on-end-reached). When we have :notifications-per-page=8 or something this issue becomes irrelevant.

@rasom, I tried to eliminate the mobile code from the equation, and back then I thought I eliminated the possibility that the mobile client was not requesting the next page correctly due to `on-end-reached`. Of course, you should double-check this, but in my experiments the problem was always that mobile was sending the cursor it received (without modification of course), but it was getting back missing notifications due to the encoding differences in the cursor.

>This second one might be related to encoding/decoding. Not sure though that

It's very likely that it's related to encoding. There are many ways to see this. One is to copy the cursor generated by status-go and use it in mobile as a hardcoded string, and you'll see that mobile receives all notifications correctly. The point being that mobile doesn't touch the cursor, it only stores in the db and reuse it, so something much lower-level is going on.

It's been so long that I don't remember the details, but I believe the proposed solution worked well, but it might not be the best solution. @cammellos has context of this issue, as he helped me a lot in the investigation.
