### ISSUE TITLE
"Wrong password" message is shown after entering right password when there is a slow internet connection

### ISSUE THREAD

**Issue by Ferraiya** [status-im/status-react#1418]
### Description

*Type*: Bug

*Summary*: 
 "Wrong password" message is shown after entering right password when there is a slow internet connection (3G mobile)

#### Expected behavior
Entering the account is successful

#### Actual behavior
"Wrong password" message is shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status
2. Tap on the account
3. Enter the right password of this account

### Additional Information
Device/OS: iPhone 5, iOS 9.3.5
App version 0.9.9d5

Speed: https://drive.google.com/file/d/0B5WergArvaY1VmRzdV9hVUFPZk0/view?usp=sharing

#### Logs

https://drive.google.com/file/d/0B5WergArvaY1VDFOQWxsR0RUT2s/view?usp=sharing

**Comment by jeluard** [comment]
Duplicates #1295
