### ISSUE TITLE
There is no response from the system on recover screen after entering a password phrase and password and tapping on "Recover access" button

### ISSUE THREAD

**Issue by Ferraiya** [status-im/status-react#1419]
### Description

*Type*: Bug

*Summary*: 
 There is no response from the system on recover screen after entering a password phrase and password and tapping on "Recover access" button

#### Expected behavior
User loggs in to the account

#### Actual behavior
There is no response from the system when user enters a password phrase and password and taps on "Recover access" button.

### Reproduction

Launch the app
Tap on the button “Recover access”.
Input password phrase and password.
Tap on "Recover access"

### Additional Information
* Status version: 0.9.9d5, 0.9.9d55
* Operating System: iPhone 5, iOS 9.3.5

VIDEO: https://drive.google.com/file/d/0B5WergArvaY1dkdsQlhfR05rSTQ/view?usp=sharing

#### Logs
https://drive.google.com/file/d/0B5WergArvaY1eHBidXhVRXduZDQ/view?usp=sharing

### Instabug:
https://dashboard.instabug.com/applications/status/beta/bugs/361

**Comment by annadanchenko** [comment]
can't reproduce
