### ISSUE TITLE
 There's no grey status message Offline on pages Contacts, Discover, DApps

### ISSUE THREAD

**Issue by katebashurova** [status-im/status-react#1420]
Description
Type: Bug

Summary: There's no grey status message Offline on pages Contacts, Discover, DApps

Expected behavior: Grey status message Offline on pages Contacts, Discover, DApps is shown
Actual behavior: Grey status message Offline on pages Contacts, Discover, DApps is   not shown

Reproduction
1. Log in to the app
2. Go from online into offline

Additional Information 
Device/OS: Samsung Galaxy S4 (SHV-E300K),Android 5.0.1 and Samsung Galaxy A5,Android 6.0.1
App version 0.9.8-74gf0847bba+
![20170707_012300](https://user-images.githubusercontent.com/29694033/27989499-94eaa424-6442-11e7-9d57-34691e66a837.png)
![20170707_012240](https://user-images.githubusercontent.com/29694033/27989503-9fc833c0-6442-11e7-9195-7a41ea3ac7fe.png)
![20170707_012217](https://user-images.githubusercontent.com/29694033/27989505-a8a1bae8-6442-11e7-95c0-ab697c552f60.png)

**Comment by annadanchenko** [comment]
Contacts and Discover tabs are removed
