### ISSUE TITLE
1-1 and public chats are missing title (new UI)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14213]
**Steps:**

1. Open 1-1/public chat
2. Pay attention if there is a title

**Actual result:** no title is displayed

**Expected result:** title is displayed

![photo_2022-10-21 22 45 19](https://user-images.githubusercontent.com/97245802/197277109-58d663bd-746e-4037-be1b-31d55664b7ae.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
im not sure it makes sense to create issues, because chat screens is not implemented yet in the new design, all these expected, i removed title so we know we need to implement new design

**Comment by pavloburykh** [comment]
> im not sure it makes sense to create issues, because chat screens is not implemented yet in the new design, all these expected, i removed title so we know we need to implement new design

Agree. Closing the issue.
