### ISSUE TITLE
No icons are displayed for set reactions under the message (New UI)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14212]
Reaction icons used to display correctly in previous builds with new UI, so it is a newly introduced issue. 

**Steps:**

1. Start any kind of chat
2. Send a message
3. Set any reaction to the massage
4. Observe the appearance of set reaction under the message

**Actual result:** icons are not displayed for set reactions and for new reaction button. 

![photo_2022-10-21 18 14 15](https://user-images.githubusercontent.com/97245802/197229835-3b745afb-d7a5-4e2e-937a-a7b0fc37e1b8.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by du82** [comment]
The name of the channel also doesnt show up

**Comment by Parveshdhull** [comment]
icons issue is fixed in https://github.com/status-im/status-mobile/pull/14211

**Comment by pavloburykh** [comment]
> icons issue is fixed in #14211

oh great, thanx @Parveshdhull I just missed this fix and the last nightly build does not include this yet. Will check it in next nightly build and close this issue.

**Comment by Parveshdhull** [comment]
we still need to fix second [issue](https://github.com/status-im/status-mobile/issues/14212#issuecomment-1287275036)

**Comment by pavloburykh** [comment]
> 

ok. 
I just wanted to notice that currently there are lots of UI bugs as large part of functionality/features of new UI are still in process of implementation.  For now, we are logging only bugs related to those parts/flows that have been already implemented and have been moved into testing. The whole chat functionality has not been claimed to be fully implemented, and that's why for now QAs are ignoring lots of bugs.

**Comment by Parveshdhull** [comment]
> > icons issue is fixed in #14211
> 
> oh great, thanx @Parveshdhull I just missed this fix and the last nightly build does not include this yet. Will check it in next nightly build and close this issue.

cool thank you, I guess we can close this issue after confirmation and can log the missing title issue separately.

**Comment by pavloburykh** [comment]
> > > icons issue is fixed in #14211
> > 
> > 
> > oh great, thanx @Parveshdhull I just missed this fix and the last nightly build does not include this yet. Will check it in next nightly build and close this issue.
> 
> cool thank you, I guess we can close this issue after confirmation and can log the missing title issue separately.

I've logged a separate issue for missing title https://github.com/status-im/status-mobile/issues/14213

**Comment by flexsurfer** [comment]
im not sure it makes sense to create issues, because chat screens is not implemented yet in the new design, all these expected, i removed title so we know we need to implement new design

**Comment by flexsurfer** [comment]
the new design is not ready for testing yet

**Comment by Parveshdhull** [comment]
> > icons issue is fixed in #14211
> 
> oh great, thanx @Parveshdhull I just missed this fix and the last nightly build does not include this yet. Will check it in next nightly build and close this issue.

Is this fixed? cc: @pavloburykh

**Comment by pavloburykh** [comment]
> > > icons issue is fixed in #14211
> > 
> > 
> > oh great, thanx @Parveshdhull I just missed this fix and the last nightly build does not include this yet. Will check it in next nightly build and close this issue.
> 
> Is this fixed? cc: @pavloburykh

yeah, its fixed. sorry @Parveshdhull I've forgotten to close the issue. Closing it now.
