### ISSUE TITLE
Deleting a pinned message causes issues

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14224]
When you pin a message, then use "delete for me" its impossible to unpin the message, so it exists in a half deleted state.

![Screenshot_2022-10-25-00-22-53-02_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/197689483-326337cc-77fb-45f5-bdb3-f2ff88e8b8ab.jpg)

**Comment by OmarBasem** [comment]
Thanks for pointing this out. This issue has already been fixed in [the PR](https://github.com/status-im/status-mobile/pull/14204).

**Comment by pavloburykh** [comment]
Closing this issue as a duplicate.
