### ISSUE TITLE
Implement Selectors components with blur style

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14220]
Implement Selectors components with blur style:

Figma: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=398%3A18229

The selectors without blur style have already been implemented, so take these components and implement with blur style
- see: https://github.com/status-im/status-mobile/issues/14015

**Comment by ibrkhalil** [comment]
Hey Jaime
I think the blurring that happens here is only for the background of the component and not the component itself
WDYT ?

**Comment by J-Son89** [comment]
@ibrkhalil, it looks like there is some differences in the design. Actually it looks rather straightforward in that it's mostly just different colors.
E.g
Non blur
<img width="800" alt="Screenshot 2022-10-26 at 10 11 26" src="https://user-images.githubusercontent.com/22799766/197985652-ab901eb2-d37d-49b0-92ed-bc06443e87dc.png">

Blur
<img width="800" alt="Screenshot 2022-10-26 at 10 11 50" src="https://user-images.githubusercontent.com/22799766/197985761-550d7866-e078-4199-af59-fdb87410ded1.png">
