### ISSUE TITLE
Allow user to change nickname of a user you have a chat with

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14222]
As a user
I want to be able to change the nickname of a user
So I can easily recognize them

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447%3A349773

**Comment by ibrkhalil** [comment]
Fixed in
https://github.com/status-im/status-mobile/pull/15557
