### ISSUE TITLE
Activity Center is not closing upon tapping close button

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#14231]
## Problem 

Activity Center is utilising the `popover` view/component to display. The `:hide-popover` event is dispatched upon the user tapping the close button. However, the Activity Center is NOT closing.

### Reproduction

1) Open Status
2) Navigate to Activity Center
3) Try to close Activity Center

### Additional Information

- Operating System: Android, iOS

**Comment by ilmotta** [comment]
I'm reopening this issue because, for reasons I don't know yet, the `develop` branch close button stopped working again.
