### ISSUE TITLE
Messages are not delivered or automatically set as read in chats (NEW UI)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14230]
This issue represents 2 problems that might have the same rootcause. 

### ISSUE 1 Messages are not delivered in chats that are not last opened

**Steps:** 

1. Start 1-1 chat between User A and User B (also reproducible for other types of chats)
2. Start one more chat by User A, for example public chat
3. Enter 1-1 Chat by both User A and User B
5. Close the 1-1 Chat by User A and open Public chat
6. Close public chat by User A and open a chat screen with a list of chats
7. Send a message by User B to User A in 1-1 Chat
8. Pay attention at the chat unread indicator for User A 
9. Open 1-1 Chat by User A
10. Check if there a message send by User B is displayed for User B

**Actual result:** unread indicator appears for a new message to User A but after opening a chat it turns out that message is not displayed 

**Expected result:** message is delivered to User A

[geth.log](https://github.com/status-im/status-mobile/files/9861544/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/9861545/Status.log)

https://user-images.githubusercontent.com/97245802/197993896-0adf2a2f-f9ec-4a6b-ac80-95b9e5fa030c.mp4

### ISSUE 2 Messages are automatically set as read for the last opened chat

**Steps:** 

1. Start 1-1 chat between User A and User B (also reproducible for other types of chats)
2. Enter the chat by both User A and User B
3. Close the chat by User A and open a chat screen
4. Send a message by User B
5. Pay attention at the chat unread indicator for User A

**Actual result:** unread indicator appears for a moment and then disappears 

**Expected result:** unread indicator remains until the messages in the chat are read

[geth.log](https://github.com/status-im/status-mobile/files/9861452/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/9861454/Status.log)

https://user-images.githubusercontent.com/97245802/197809665-843d184f-ead3-487a-bc50-9f6acdb29b42.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
Moreover: 
In case of issue 1 all messages that are delivered while user was on another chat view (let's say public chat) are lost and  are not shown after opening the initial chat view until relogin
**Prerequisites:**
User A has chat with User B and public chat
**Steps:**
- User A:  navigate to public chat
- User B: send messages 1,2 to chat with User A
- User A: navigate to chat with User B
- User B: send messages 3,4 to chat with User A

User A will see only messages 3,4 until the reopening the application

**Comment by pavloburykh** [comment]
@rasom UPDATE

ISSUE 1 is reproducible in case when receiver of messages is Android and sender is IOS
