### ISSUE TITLE
Confirm Server Port Race Condition is resolved

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-react#14234]
`status-go` PR https://github.com/status-im/status-go/pull/2904 introduces some functionality to more tightly manage server ports. My initial implementation introduced a few regressions, https://github.com/status-im/status-mobile/pull/14167 .

I've introduced into the go PR some go tests that check unusual behaviour that used to break, but fix I've introduced resolves this.

However as confident as I am, I have not been able to confirm that I have completely resolved the issue via the mobile app because currently image handling is not supported in the new UI. Therefore this issue is a reminder that this work needs to be checked.

**Comment by churik** [comment]
@Samyoul is this still relevant?

**Comment by Samyoul** [comment]
Hey @churik i think this is resolved now
