### ISSUE TITLE
ENS search takes more than 1 minute 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14235]
Can be reproducible during ENS search when adding new ENS contact, start new chat with ENS user, adding existing ENS to user's Profile. 

**Prerequisites:** couple of ens names for reproduction on mainnet - pavlotest, ensmessenger
**Steps (example with adding new ENS contact):**

1. Open Profile tab
2. Open contacts screen
3. Tap add new contact button 
4. Search for existing ENS user
5. Observe the result

**Actual result:** ens search takes > 1 minute. Sometimes it takes regular time, sometimes user will get an error that ENS not found

**Expected result:** ENS search takes up round 5 seconds as it used to take before 

[geth.log](https://github.com/status-im/status-mobile/files/9868969/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/9868971/Status.log)

https://user-images.githubusercontent.com/97245802/198014817-64cdea97-dd77-46e3-b75b-96f4b8863528.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
🪄  Issue is resolved by itself 🪄  on nightly 03/01/23
