### ISSUE TITLE
faucet request does not send 1 ETH

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1423]
### Description

*Type*: Bug

*Summary*: If use /faucet to request test ether then nothing is received, because 
http://46.101.129.137:3001/faucet-info faucet’s balance is too small

#### Expected behavior
1 test ETH is sent
#### Actual behavior
no ETH sent

### Reproduction

- Open Status
- Open Console
- tap on /faucet command, from suggestions select url http://46.101.129.137:3001 and send
- Console shows "Faucet request has beed received"

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by sla-shi** [comment]
@farazdagi @tiabc requires faucet to be mining

**Comment by annadanchenko** [comment]
Works on today's develop #222

**Comment by annadanchenko** [comment]
Open again because https://github.com/status-im/status-go/issues/234 is not done yet

**Comment by tiabc** [comment]
Our faucet now constantly mines ether, this issue may be closed. Proof: https://ropsten.etherscan.io/address/0xadaf150b905cf5e6a778e553e15a139b6618bbb7#mine

**Comment by annadanchenko** [comment]
1. Nothing is received from faucet if use /faucet command in Status app. Expected: 1 ETH is received as it was in previous versions
2. http://46.101.129.137:3001/faucet-info returns ```{"account":"0xadaf150b905cf5e6a778e553e15a139b6618bbb7","balance":"0 Wei"}```

**Comment by annadanchenko** [comment]
Works as expected:
1. 1 ETH received after using faucet command 
2. http://46.101.129.137:3001/faucet-info returns 
 `{"account":"0xadaf150b905cf5e6a778e553e15a139b6618bbb7","balance":"450 Ether"}`
