### ISSUE TITLE
Incorrect read/unread filter behavior

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14245]
## Problem 

The read/unread toggle button is currently behaving as a toggle that **only** displays either read or unread notifications.

<img src="https://user-images.githubusercontent.com/46027/198122312-1303f3fb-3c2f-4059-a187-687ad7122dc9.png" width="500" />

#### Expected behavior

The toggle button should display either unread notifications or notifications in any state (both read and unread).

#### Resources

- https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681

**Comment by rasom** [comment]
@ilmotta 
I'm a bit lost, where do I find this toggle in the app currently?

**Comment by ilmotta** [comment]
> @ilmotta I'm a bit lost, where do I find this toggle in the app currently?

@rasom, This bug is only applicable for the new Activity Center, and in order to see it, you need to enable the flag `status-im.utils.config/new-activity-center-enabled?` (disabled by default).

On a side note, I still think we should keep the flag disabled by default until we implement a couple more fixes/features in the new AC, so that we don't disrupt other people's workflows using the old AC. Hopefully next month we get there ;)

**Comment by rasom** [comment]
@ilmotta understood, thanks
