### ISSUE TITLE
Allow user to mute a chat

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14259]
```
As a user
I want to be able to mute a chat
So that ....
```

### Description

As a user I want to be able to mute a chat.

When we mute a one-to-one chat, what's the desired behavior? @pedro-et 
When we mute a private group chat, what's the desired behavior? @pedro-et 

### Notes
- Design already implemented in develop, so there should be nothing to do there.

- Current implementation will avoid sending push notifications to a user who has a chat muted, but we still show the counter etc, is that the desired behavior? @pedro-et 
- Blocked until questions are answered

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447%3A349773

**Comment by flexsurfer** [comment]
hey @ibrkhalil did you have a conversation with the design team? all clear what needs to be done?

**Comment by ibrkhalil** [comment]
> hey @ibrkhalil did you have a conversation with the design team? all clear what needs to be done?

Yes, Thank you
Me and Pavlo had a chat with Mario and Ben on that matter and currently in the process of fixing a final bug related to it.
