### ISSUE TITLE
Show count of mentions when available in home screen

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14268]
As a user
I want to see the count of mentions for a private group chat in the home screen
So that I know if someone wanted to get my attention

### Description

If there are any unread mention for a private group chat, we should show the count instead of the unread indicator only.

### Notes

- Backend should be already implemented

### Designs
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447%3A349398

**Comment by ibrkhalil** [comment]
I tried it but I already see a count 
![image](https://user-images.githubusercontent.com/33176106/198849938-f5f0429e-3699-4f7d-88c7-9a72825fc197.png)

**Comment by OmarBasem** [comment]
It got implemented in this [PR](https://github.com/status-im/status-mobile/pull/14256). I think this issue can be closed.
