### ISSUE TITLE
Allow user to share a profile when long-pressing on a chat on home screen

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14266]
As a user
I want to be able to share a profile for a one-to-one-chat (what about private group chats?)
So that....

### Description

When long-pressing on a one-to-one chat on the home screen, if I click on share profile, what should happen? cc @pedro-et 

should this option be available private group chats?

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447%3A349773

**Comment by flexsurfer** [comment]
@cammellos still blocked?
