### ISSUE TITLE
@browse command doesn't work in public chat 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1426]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open public chat
- Press @browse

![image](https://user-images.githubusercontent.com/11790366/28055921-b8efca60-6623-11e7-8e7e-d0ab3a2d453f.png)

**Comment by annadanchenko** [comment]
fixed and tested in 0.9.12
