### ISSUE TITLE
Show last message for a chat in the home screen

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14267]
As a user
I want to see the last message of a chat in the home screen
So that I don't have to open the chat to see was last written

### Description

The last message should be displayed in the home screen for each chat, similarly as we did in the old UI
backend is already implemented, chats have a `LastMessage` property that can be used.

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447%3A349398

**Comment by OmarBasem** [comment]
Also got implemented in this [PR](https://github.com/status-im/status-mobile/pull/14256).

**Comment by OmarBasem** [comment]
Showing latest message of other types of messages like audio and images is not yet handled as it is not yet implemented inside the chat to be tested. So I think we can keep this one open as a reminder to get back to it.

**Comment by ibrkhalil** [comment]
Then close this issue @OmarBasem @cammellos ?
