### ISSUE TITLE
0 members in group chat and chat input is not shown in group chat after re-login 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14271]
# Bug Report

## Problem 
After the successful creation of a group chat and exchanging messages, there are no members and no message input in the chat view after re-login

https://user-images.githubusercontent.com/4557972/198600333-21cb9bbb-d0c9-4313-9160-b4080c5ca862.mp4

#### Expected behavior
- 2 members
- when opening group chat, can see chat input

#### Actual behavior
- 0 members (IOS, Android)
- no chat input (Android)

### Reproduction
**Prerequisites:** User A and User B are mutual contacts

1) User A: open group chat with User B, send couple of messages
2) User A: relogin

### Additional Information

- Status version: nightly 28/10/22 (appeared earlier)
- Operating System: Android, iOS (partially)

**Comment by du82** [comment]
affects me as well

**Comment by ibrkhalil** [comment]
> affects me as well

Can you please check?

**Comment by ibrkhalil** [comment]
> affects me as well

Can you please check?
