### ISSUE TITLE
Icons with a background color do not look as they should be

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14289]
How the icon should look:

<img width="84" alt="Screenshot 2022-11-07 at 12 20 18" src="https://user-images.githubusercontent.com/29354102/200260518-486fffb8-e6b7-4e6b-8ed7-60d2283fbede.png">

How it appears:

<img width="23" alt="Screenshot 2022-11-07 at 12 20 24" src="https://user-images.githubusercontent.com/29354102/200260559-a263f2f5-2209-405c-9a68-3a60924dc0c4.png">

As seen in the above pictures, the icon details cannot be seen, only the background color (ignore the picture sizes)

**Comment by OmarBasem** [comment]
cc @flexsurfer

**Comment by flexsurfer** [comment]
you need to set `:no-color` to `true`

**Comment by flexsurfer** [comment]
or if you need dynamic background color, you need to ask design team to remove the background from the icon, and create background as a view in react , example : https://github.com/status-im/status-mobile/pull/14280/files

**Comment by OmarBasem** [comment]
> you need to set `:no-color` to `true`

Thank you!
