### ISSUE TITLE
Allow owner/admin to delete messages of a community

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14290]
As an admin/owner of a community
I should be able to delete a message of a community
so that I can make sure the content is relevant to users

### Description

An admin (or owner) should be given the option to delete messages from a community. 
This should be reflected on any member of the community.

If the role is `ROLE_ALL` or `ROLE_MODERATE_CONTENT` (this needs to be added), it should also be allowed to delete messages.

**Comment by qfrank** [comment]
if the role is CommunityMember_ROLE_MANAGE_USERS, should it also be allowed to delete messages? @cammellos

**Comment by cammellos** [comment]
> if the role is CommunityMember_ROLE_MANAGE_USERS, should it also be allowed to delete messages? @cammellos

I'd say no

**Comment by du82** [comment]
Why not let communities structure their own roles system just like Discord does.
Every community is different, there's no one size fits all
