### ISSUE TITLE
Bad availability for JCenter Bintray Maven repo archive

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#14303]
Today while trying to reproduce [a different issue]() I encountered this:
```
trying https://plugins.gradle.org/m2/com/eightbitlab/blurview/1.6.6/blurview-1.6.6.aar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   554    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download blurview-1.6.6.aar from any mirror
```
https://github.com/status-im/status-mobile/blob/add00a5609ffc01f147e862fdf0e5912ec9a38ea/nix/deps/gradle/deps.urls#L291
But for now it works since we have local copies in Nix store:
```
admin@linux-01.he-eu-hel1.ci.devel:~ % find /nix/store -maxdepth 1 -iname '*blurview*'
/nix/store/yg3k0d05mfvjycw11cs2hncdmv5w83jv-blurview-1.6.6.pom.drv
/nix/store/d3zvymcj2rsybqsbi9ixq52l56iqmw1q-blurview-1.6.6.aar.drv
/nix/store/12pphxyfi6a4p3nlyrrf8id8hdpyzs43-blurview-1.6.6.aar
/nix/store/x9rllnj12pbyzn398a22x3swcdplvxw7-blurview-1.6.6.pom
```

**Comment by jakubgs** [comment]
Actually, it appears that `plugins.gradle.org` now returns a `303 See Other` redirect for this URL:
```
 > c -v https://plugins.gradle.org/m2/com/eightbitlab/blurview/1.6.6/blurview-1.6.6.aar >/dev/null 2>&1 | grep -e Location        
< Location: https://jcenter.bintray.com/com/eightbitlab/blurview/1.6.6/blurview-1.6.6.aar
```
Which suggests that this might have been some kind of internal change in the `plusing.gradle.org` backend.

But that redirect is weird considering JCenter Bitray has been shut down:

* https://github.com/status-im/status-mobile/issues/13320

This might be a sign of some more weird stuff happening in the future with that repo.

**Comment by jakubgs** [comment]
This actually appears to be a known issue:

* https://discuss.gradle.org/t/plugin-portal-dependency-resolution-failing-due-to-jcenter-usage/44131/15

Which says that:

>Just the usual regular JCenter outage which caused me to never like JCenter.

and

>Given that JCenter is sunset and in read-only mode, I can’t imagine that there are many resources being devoted to maintaining it or ensuring high availability.

And that is indeed true:

>__UPDATE 4/27/2021:__ We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cammellos** [comment]
closing for now as non actionable, feel free to reopen
