### ISSUE TITLE
Contact requests missing implementations

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14306]
There are some missing implementation in contact requests:

1. Give feedback to users in toasts when they accept or reject a contact request. Depends on #13831
2. Show sent-out contact requests. Depends on [#2952](https://github.com/status-im/status-go/issues/2952) in status-go
3. Empty state

[Designs](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2795%3A541615)

**Comment by cammellos** [comment]
closing for now as part of it is post mpv
