### ISSUE TITLE
Toast Component

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14305]
Many actions in the app require a toast to be presented to the user as a feedback. This issue is to track the creation of Toast component like in this design: [https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2795%3A541802](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2795%3A541802)

**Comment by flexsurfer** [comment]
duplicate https://github.com/status-im/status-mobile/issues/13831 ?

**Comment by OmarBasem** [comment]
Oooh :/  I tried to search if there is an open issue but did not appear
