### ISSUE TITLE
Chat Screen Top Bar UI

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14312]
An issue to track the creation of Chat screen top bar UI
[Designs.](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=332%3A78250)

**Comment by OmarBasem** [comment]
I was going to work on that issue, but I see a comment in the codebase in `status-im.ui2.screens.chat.view` line 59: 
`;;TODO It is better to not use topbar component because of performance`. 

Not sure what to use instead, and how/why is this affecting the performance.

cc @flexsurfer

**Comment by flexsurfer** [comment]
i think you can ignore my comment
