### ISSUE TITLE
All chats except Console disappear after app re-launch [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1432]
### Description

*Type*: Bug

*Summary*: Only Console is shown in the Chats after app re-launch even when there were more 1-1 chats before closing the app.

![screenshot_20170711-212137](https://user-images.githubusercontent.com/6584810/28086591-2f982be4-6688-11e7-8936-b2013a64f03b.png)

#### Expected behavior
Same chats are shown in Chats after app re-launch as were before app was closed
#### Actual behavior

Only Console is shown in the Chats 
### Reproduction

- Open Status
- Open some DApp, so its chat is shown in the Chats 
- Open some people contact and write a message in 1-1 chat, so it's shown in the Chats
- Close app
- Launch app again and Sign in
- Check the content on the Chats tab

### Additional Information
* Status version: develop 0.9.8-63-g06bff32f+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment]
interesting. if you reloggin without relaunching app. all chats will be available

**Comment by lishiqiadmin** [comment]
**Does status have a language switching function?**
For example, Chinese, Chinese users more。

SNT is tumbling... Lower than all the chips, the heart is bleeding. What time does it go up?
SNT在 爆跌，低于众筹的价格，粉丝心在滴血啊，什么时候上涨？

**Comment by lishiqiadmin** [comment]
Is app on line yet?

**Comment by flexsurfer** [comment]
hi @lishiqiadmin why are you asking in this issue? you can ask in our slack. We have translations https://github.com/status-im/status-react/tree/develop/src/status_im/translations and use phone's language
