### ISSUE TITLE
Messages not shown when mutual contact requests are enabled

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14337]
Originally reported here: https://github.com/status-im/status-go/pull/2927#issuecomment-1307105201 

1) User A and B are mutual contacts and exchange some messages
2) A blocks B
3) A unblocks B
4) A sends a message to B

Here in 4, we should not allow the user to send a message without adding the user back to contacts, messages are not displayed and we should show the user a prompt to add the user to contacts/send a contact request.

This might require some design work. cc @pedro-et @pavloburykh

**Comment by ibrkhalil** [comment]
Should we have a bool that turns on when user;s blocked and on readding the user as a contact again it goes to false ?
