### ISSUE TITLE
CJK languages overflow on chat screen

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14336]
Languages that don't use spaces overflow when no space is used in a string.  I think this is because the algorithm that chooses where to put the elipses expects spaces where there are none.

![Screenshot_2022-11-11-07-48-26-53_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/201353658-08ae611d-2c3b-49e6-8a58-e0cba2f21cc4.jpg)

**Comment by du82** [comment]
The spaces you see earlier in the string aren't actually spaces, they are double width characters that only utilize the front 1/3 or 1/2 of the available space, and leave the rest blank.

**Comment by churik** [comment]
![IMAGE 2023-06-01 12:23:07](https://github.com/status-im/status-mobile/assets/4557972/ec542c74-c5da-4e8d-93ec-56d1f3cb4855)
Nightly 01/06/23
