### ISSUE TITLE
Missing community icon in community list

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14339]
The community icon is missing in the home list view (there's a comment that mention this in the code, so i take we are aware of it, but leaving this open to keep track of it)

**Comment by du82** [comment]
Can confirm, affects me sometimes

![Screenshot_2022-11-11-11-27-16-88_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/201395816-f42ae7e9-48e1-456f-a912-faca8c91d7c8.jpg)

**Comment by cammellos** [comment]
fixed in develop
