### ISSUE TITLE
Community conditions not showing

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#14344]
# Bug Report

## Problem 
Community conditions not rendering

#### Expected behavior
Community conditions should show and at least cater for the case they don't exist ..

#### Actual behavior
Community conditions are not showing

### Reproduction

1) Open Status
2) Go to communities
3) Try to join the Status community

![image](https://user-images.githubusercontent.com/33176106/201491219-c09037d9-8ee4-40aa-b9bc-353c2c54ab8c.png)

**Comment by jo-mut** [comment]
@churik  this issues seems to have been fixed in an earlier PR. The pop up shows up when you click to join a community. Seems to work fine on develop

**Comment by J-Son89** [comment]
This issue is fixed now. So closing
