### ISSUE TITLE
Should we upgrade React Native to v0.70.x?

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#14340]
## Summary

As our mobile app is on React Native v0.63.5, we need to (in near future) upgrade the app to a newer React Native version (v0.70.x). We are looking for solid reasons to upgrade and the challenges of it. 

This issue helps us to capture those items and track them.

### Reasons to upgrade
1. Better performance with new React Native architecture includes Gradle update for faster build time
2. Replacing `FlatList` with `WishList` for more robust control
3.

### Reasons NOT to upgrade
1.

### Challenges in upgrading
1. Third Party Libraries / Dependencies
2. 

### Notes

Contributors, please add your input below.

**Comment by ibrkhalil** [comment]
We talked on the offsite about how valuable wish list is going to be for status-react and that we'll do our best to update to it

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/issues/14386

**Comment by smohamedjavid** [comment]
Closing this issue as this is a duplicate of https://github.com/status-im/status-mobile/issues/14386
