### ISSUE TITLE
Only display declined notifications for the contact verification challengee

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14354]
# Problem

Nowdays status-go is generating notifications for both the contact verification _challenger_ and _challengee_. According to [flows in Figma](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681), only the challengee should see declined notifications

This is also a bug, because notifications need to filtered out on the client, which doesn't work well with server-side pagination in status-go.

## Implementation

The bulk of the work is in status-go, but in status-mobile we should also remove the workaround in https://github.com/status-im/status-mobile/blob/9473d3f40cc1b8f182f5a4c63d29e652c71732d4/src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs#L163

## Scope

Identity verification is a feature that may not be enabled in the MVP after all, so before working on this issue, double-check with @cammellos.

**Comment by cammellos** [comment]
closing as post mvp
