### ISSUE TITLE
Use new multiline input field to reply to contact verification requests

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14364]
# Problem

The current implementation to reply to a contact verification request is using the old component `quo.core/text-input`, but the redesign requires a new multiline component. At the time of implementation of the identity verification flow, the new component wasn't available.

<img src="https://user-images.githubusercontent.com/46027/201723774-8610931c-4db3-446b-b859-04ad2aba34aa.png" height="500" />

### Expected

Once the new text input component is available, we should use it. See the specs here https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=57%3A5646

<img height="500" alt="Reply" src="https://user-images.githubusercontent.com/46027/201732743-30e7e398-1284-4dda-bab1-752c13e563ac.png">

**Comment by pavloburykh** [comment]
Also as have been [agreed](https://github.com/status-im/status-mobile/pull/15284#issuecomment-1466203855) with @ilmotta the following issue will be addressed within current ticket:

### Keyboard overlaps Identity verification bottom sheet

**Steps:** 

1. Generate identity verification request for User B
2. By User B: open AC => tap identity verification notification => make answer input field active to open keyboard
3. See if keyboard overlaps Identity verification bottom sheet

**Actual result:** Keyboard overlaps Identity verification bottom sheet


https://user-images.githubusercontent.com/97245802/224648435-72ea9ea5-c36c-49c4-8b32-17e78304682e.mp4

**Comment by ilmotta** [comment]
Closing because contact verification flows are descoped and the code should actually be removed from the mobile client.
