### ISSUE TITLE
Long address text overlaps chat area on Chats tab [iOS only]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1436]
### Description

*Type*: Bug

*Summary*: only on iOS: Long address overlaps chat area in the Chats tab if chat is the last one in the list. It's expected that only first x words will be shown to use 2 lines instead of showing the complete address. 
Ok scenario (first 2 lines are shown in chats for address is in green box on the picture below)
Issue (more than 2 lines are shown for an address is in red box on the picture below)
![img_2467](https://user-images.githubusercontent.com/6584810/32115952-fd91ca54-bb48-11e7-9fa9-5c363ad6f5e5.jpg)

#### Expected behavior
Only 2 lines of the address are shown in Chats screen, so it fits the area for the chat 
#### Actual behavior
Long address (e.g. 5 lines) is fully shown and overlaps chat area in the Chats tab

### Reproduction

- Open Status
- Open Chats
- Create a new group chat "Test", add Jarrad as a member. 
- in created group chat tap on command /location
- in the input field next to location command type "Museum of medical instruments". As a result, suggestions list will be shown with this name
- Tap on "Museum of medical instruments of the Hos..."  item in the suggestions list. As a result, location message with an address and a map is shown in the chat
- now return back to Chats list (tap on icon "<" in top left corner)
- if new chat with location command is not shown at the bottom of Chats list then open each chat below our "Test" chat and send something to the chat, e.g. word "text" - as a result, the chat will go up in the list of chats. You need to repeat it until the "Test" chat is at the very bottom in the Chats
- Check how location text is shown (currently, it takes 5 lines instead of expected 2 lines)

### Additional Information
* Status version:  0.9.8-63-g06bff32f+ and up to 0.9.12
* Operating System: 
Real device iPhone 6s, iOS 10.2.1

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0xe9eb037a80da70c5465e185ca6f5588d1dc73a23](https://etherscan.io/address/0xe9eb037a80da70c5465e185ca6f5588d1dc73a23)
Network: Mainnet
Paid to: acmcc
