### ISSUE TITLE
Message input: image selection

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14363]
As a user, I want to be able to send image in any chat

Designs: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2827%3A269831&t=1NrhQoSGitjVl9dD-4 

Suggest starting by choosing one photo, if the feature itself is too big to handle it in one piece.

**Comment by cammellos** [comment]
@churik is this still relevant? seems like we can send now images in the input, but maybe i misunderstand the feature

**Comment by qoqobolo** [comment]
Closing the issue since the feature itself is implemented. 
There are some related bugs, but they are tracked in separate tickets.
