### ISSUE TITLE
Regression issues regarding new project structure

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14370]
# Bug Report

## Problem 
Some regression/unexpected behaviour after https://github.com/status-im/status-mobile/commit/c7d5e90882d709f15df32ec38e699f725ae546ae 

1) Black line (Android)
<img width="520" alt="photo_2022-11-15 11 03 10 jpeg 2022-11-15 11-03-48" src="https://user-images.githubusercontent.com/4557972/201891245-a3fc9103-2b24-4928-a376-9b9747e6210c.png">

2) White lines / wrong background color for header/footer/ 'Jump to' shifted (Android)
<img width="522" alt="photo_2022-11-15 11 16 27 jpeg 2022-11-15 11-17-00" src="https://user-images.githubusercontent.com/4557972/201894127-19895463-abe9-4ef1-a462-bf8bff4f5347.png">

<img width="523" alt="photo_2022-11-15 11 18 10 jpeg 2022-11-15 11-18-42" src="https://user-images.githubusercontent.com/4557972/201894514-d3a54378-a38f-42ba-b337-a1a8233af34b.png">

**Comment by churik** [comment]
### ISSUE 3: endless spinner on log out

**Steps:**
1) create miltiaccount
2) Profile > Log out

**Expected result:**
Login screen

**Actual result:**
![IMAGE 2022-11-15 11:52:02](https://user-images.githubusercontent.com/4557972/201902005-b80ea6a9-0db5-4898-a394-7b736eec1123.jpg)


**OS:** IOS, Android

**Comment by VolodLytvynenko** [comment]
**ISSUE 4: An additional black section is shown within each opened menu on the profile page**
**Steps:**

1. create miltiaccount
2. Be sure the light mode is enabled
3. Profile 
4. Tap each button within the profile:


https://user-images.githubusercontent.com/52490791/201921991-31780a8b-84bd-4a6c-91d2-df7543c0b640.mp4

  - Contact 
   - Privacy and security
   - Appearance
   - Notification
   - Sync settings
   - Advanced
   - Need help
   - About

**Actual result:**
The black section contains each  page
   - Contact 
   - Privacy and security
   - Appearance
   - Notification
   - Sync settings
   - Advanced
   - Need help
   - About
![image](https://user-images.githubusercontent.com/52490791/201920976-93b57b0b-1590-4ec3-9e92-b21f58799a0d.png)
![image](https://user-images.githubusercontent.com/52490791/201921082-b5076de5-34b8-43b8-9d70-850be8524749.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/52490791/201921246-e139d86e-5d06-4918-913f-01d6843ab67d.png)
![image](https://user-images.githubusercontent.com/52490791/201921279-3905fc8a-9e57-4d86-bb10-e2c63a77b1a4.png)

**OS:** IOS, Android

**Comment by cammellos** [comment]
I am looking at the logout issue.

**Comment by flexsurfer** [comment]
duplicate https://github.com/status-im/status-mobile/issues/14399
