### ISSUE TITLE
Jump to message being replied to on tap reference message

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14375]
As a user, I want to be able to tap a message (the one with the red arrow) that someone replied to, and jump to the original message, so I can read the context surrounding it.

![Screenshot_2022-11-15-20-27-00-66_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/202068698-95d33447-07c8-4c67-8a6f-c35ebef211e7.jpg)

**Comment by cammellos** [comment]
This is currently blocked by the flat list implementation unfortunately, since it would involve scrolling on both sides.
