### ISSUE TITLE
[quo2 new design tech debt] status-im.ui.screens.communities.community

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#14387]
reimplement status-im.ui.screens.communities.community for new designs with quo2 usage

**Comment by J-Son89** [comment]
@flexsurfer would you consider that these issues are the same?

i.e status-im.ui.screens.communities.community when moved will just be a place that stores all of the community context drawer options

**Comment by flexsurfer** [comment]
im not sure i understand, this issue for status-im.ui.screens.communities.community namespace refactoring, currently its implemented in old design and guidlines

**Comment by J-Son89** [comment]
apologies, I meant to link this issue: https://github.com/status-im/status-mobile/issues/14464

as it seems that status-im.ui.screens.communities.community  mostly contains context drawer options for various states.
which that issue I linked is also doing

**Comment by flexsurfer** [comment]
yeah its up to you , youre more familiar with that code, this issue just for refactoring, to keep track that new design implemented

**Comment by J-Son89** [comment]
I believe this issue is covered in https://github.com/status-im/status-mobile/issues/14464, closing this as it's already done
