### ISSUE TITLE
Chat view freezes if open/close chat multiple times (iOS)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14385]
# Bug Report

## Problem 

Sometimes, a chat view stops scrolling and the back button stops responding on iOS if you navigate to a chat and back several times (community channel, 1-1, etc.).
Such actions as focusing on the input field or swiping to the right (to go back) fix the issue.

#### Expected behavior
UI doesn't freeze

#### Actual behavior
UI partially freezes

### Reproduction

1. Open a community on an iOS device
2. Open and close a channel several times

### Additional Information

- Status version: nightly 16/11
- Operating System: iOS

**Comment by rasom** [comment]
There is no need to scroll, in order to reproduce the issue on iOS simulator I only needed to open/close chat multiple times.
