### ISSUE TITLE
[quo2 new design tech debt] quo2.components.navigation.top-nav

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#14408]
quo2.components.navigation.top-nav

pass buttons as parameters to the component

**Comment by Parveshdhull** [comment]
hi @flexsurfer, sorry I didn't understand what do you mean.

**Comment by flexsurfer** [comment]
i mean top-nav should be dynamic, currently implementation of fixed number of buttons hardcoded inside, but it should get buttons vector of dynamic buttons like 

```
[top-nav {:buttons [{:i/search open-search :open-search-button button-common-props}]}
```

**Comment by Parveshdhull** [comment]
Actually, Figma also has a fixed number of buttons in component [design](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=145%3A6203&t=zPMlwQGalUHN2H1k-0).
And for a dynamic number of buttons, we have a separate component [Page Nav](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=159%3A6045&t=zPMlwQGalUHN2H1k-0).

**Comment by flexsurfer** [comment]
when this component should be outside quo, because it's not general
