### ISSUE TITLE
Send and location Messages are shown as plain text for several seconds after app launch [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1441]
### Description

*Type*: Bug

*Summary*: Send and location messages are shown as long text messages for several seconds after app is launched and chat is opened for the first time. After several seconds they are transformed into expected form. Sometimes it takes more than 5 seconds on my Galaxy S7 real device.
Send (Android):
![screenshot_20170712-181502](https://user-images.githubusercontent.com/6584810/28128095-489c9602-6737-11e7-813f-0b2a4a5b0d6d.png)

Location (iOS):
![img_2109](https://user-images.githubusercontent.com/6584810/28130442-50c47978-673f-11e7-8c09-01a99e52c886.jpg)

#### Expected behavior
After chat is opened all messages are shown in a familiar form/design/content for the user 
#### Actual behavior
Send message is shown as a long text message for several seconds and than transforms into usual send message

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7cVlSNzBFY3VIXzQ
- Open Status
- Open group chat with send message or 1-1 chat with send message

### Additional Information
* Status version:  0.9.8-67-g8e896fcd+
* Operating System: 
Real device Samsung Galaxy S7, Android 7.0
Real device iPhone 6s, iOS 10.2.1

**Comment by annadanchenko** [comment]
@retro On build#1 for PR `Branch bug/send-and-location-msgs-plain-text-#1441`
issue still occurs and it's most visible on real device iPhone 6s/iOS 10.3.3 (plain text is shown for ~ 8 seconds). On android there is very little delay about ~2 seconds when plain text is shown for same steps on real device Samsung Galaxy S6, Android 6.0.1

Steps: 
1. Create new group chat and add 2 members to it.
2. In the created group chat 
- send some eth
- request some eth
- send location
3. close app
4. launch app
5. open the group chat created above
6. check the messages 

iOS session #1 Create group chat and send commands: https://app.testfairy.com/projects/4803590-status/builds/6414784/sessions/37/?accessToken=m1bS0Qe0pB2VwoiyHFfrZzqBj/M 
iOS session#2  see from 00:09 Launch app and open created group chat (plain text issue):
https://app.testfairy.com/projects/4803590-status/builds/6414784/sessions/38/?accessToken=pg6kUh8hXzPpn/3h6NROwUEEQ5w

Android session see from 00:18 (plain text) https://app.testfairy.com/projects/4803622-status/builds/6448327/sessions/18/?accessToken=N0vv5MHKtwTPycSDTTqawF/0o-8

**Comment by retro** [comment]
I'll wait with this issue until branch for #1709 is merged since it might fix it.

**Comment by oskarth** [comment]
No longer blocked with status-go merge I believe.

**Comment by janherich** [comment]
This is already solved in the #1710 branch

**Comment by annadanchenko** [comment]
tested ok in develop. will be in 0.9.12 release
