### ISSUE TITLE
Add CI/CD job for component tests

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14417]
# Add CI/CD job for component tests

Following on from https://github.com/status-im/status-mobile/issues/14330

There is a need for component tests to be run in the CI/CD job on developer builds

Description:
- Add this job to develop p.rs
- Add this job to master branch (??)
- Add documentation on how this is setup/working.

**Comment by yqrashawn** [comment]
@J-Son89 @siddarthkay I'll work on this once resolve those delete message related bugs

**Comment by siddarthkay** [comment]
@yqrashawn : awesome! please go ahead and take this up 👍🏻

**Comment by yqrashawn** [comment]
try run `make component-test`
got can't find module `@react-native-community/blur` error 
resolved by delete `node_modules/@react-native-community/blur/` and run `yarn install`

next up:
check infra repo
