### ISSUE TITLE
"Objects are not valid as a React child..." error when trying to mention chat member

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14429]
**Steps:**
1. Start any chat
2. Try to mention another chat member (start typing @). In case of Android, after typing @ you should close chat and then try to open it again to reproduce a bug. In case of IOS - error will appear just after typing @ in chat input field
3. Observe the error

**Actual result:** Objects are not valid as a React child error appears

**Expected result:** no error

![photo_2022-11-23 13 51 09](https://user-images.githubusercontent.com/97245802/203540011-4d72b633-0b5d-4bfd-9fa3-4cc251d5bd48.jpeg)

https://user-images.githubusercontent.com/97245802/203540920-6b2e0e00-000f-4a52-a9fa-731ba631499c.mp4

https://user-images.githubusercontent.com/97245802/203540944-d2b49c11-f9d4-4d22-becf-c7aabb965e1a.mp4

[Android logs.zip](https://github.com/status-im/status-mobile/files/10075189/Android.logs.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
This happened to me once and can't reproduce it again, Retrying
Update: Tested for iOS, And fixed the issue
