### ISSUE TITLE
Shows a menu option with styling for android

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#14423]
related [issue](https://github.com/status-im/status-mobile/issues/14137) 
related [pr](https://github.com/status-im/status-mobile/pull/14249)

It would be great if we could shows a menu option with styling as the figma shows:
![figma](https://user-images.githubusercontent.com/12406719/203461663-57336c7a-2230-49cb-98ec-a36d62baf15b.png), #14249 haven't implemented this styling yet

### Acceptance Criteria
the menu option with styling looks the same as [figma](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2634%3A211035&t=EjvH60rAtlNmQFwV-0) shows

**Comment by cammellos** [comment]
closing as post mvp
