### ISSUE TITLE
Photo Selector (1)

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14425]
An issue to track the creation of photo selector.

Issue number (1).

Designs: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2827%3A269831&t=1NrhQoSGitjVl9dD-4

**Comment by cammellos** [comment]
@OmarBasem this one is most likely post-mvp, design is going through the files and removing anything that is not in it, sorry for the confusion

**Comment by OmarBasem** [comment]
As discussed, will complete the remaining part in the photo selector, then we decide if we can use it in mvp.
