### ISSUE TITLE
Unable to launch the app. Receiving "...facebook.react.common.JavascriptException.."

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14433]
**Steps:** 

1. Install Status
2. Launch the app
3. Observe the result

**Actual result:**  "...facebook.react.common.JavascriptException.."

**Expected result:** no errors

![photo_2022-11-23 18 16 55](https://user-images.githubusercontent.com/97245802/203596252-633aa3ab-d74b-4f73-a646-925e3e7482b1.jpeg)
[logcat (4).log](https://github.com/status-im/status-mobile/files/10081951/logcat.4.log)

**Comment by churik** [comment]
cc @flexsurfer

**Comment by Parveshdhull** [comment]
related https://discord.com/channels/624205794384281629/626045898878877696/1045149383852826664

**Comment by jakubgs** [comment]
No no, that's just because the e2e x86 build doesn't have a separate name because of https://github.com/status-im/status-mobile/pull/14430.

You tried to install an x86 build on an arm device, so obviously it would fail. The error is just dumb.

Simple fix.

**Comment by Parveshdhull** [comment]
actually I tried both, x86 didn't even installed and universal gave this error

**Comment by Parveshdhull** [comment]
maybe it is different bug

**Comment by jakubgs** [comment]
Actually, you're right, the `universal` build does fail. So there's another issue too.

**Comment by Parveshdhull** [comment]
probable cause: https://github.com/status-im/status-mobile/pull/14331
cc @J-Son89

**Comment by Parveshdhull** [comment]
oh we deleted .babelrc file in this commit. this is cause then

**Comment by J-Son89** [comment]
hmm, all the CI jobs passed before merging. I'll start investigating anyway. :)

**Comment by Parveshdhull** [comment]
> hmm, all the CI jobs passed before merging. I'll start investigating anyway. :)

its runtime error
