### ISSUE TITLE
Photo picker bugs

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14438]
This is an issue to catalog bugs in the photo picker.

Issue 1: Photo picker bottom nav buttons are out of frame. I can drag the ___ at the top of the BottomSheet upwards to show them, but they go away quickly on release.

![Screenshot_2022-11-24-08-10-49-52_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/203804996-887ca0b1-39cc-4fbc-88ce-2bceed3aecd1.jpg)

Issue 2: The background color of the picker is wrong.

![Screenshot_2022-11-24-08-14-32-45_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/203805542-c9b8d096-db5f-4922-8309-075a295f089d.jpg)

Issue 3: the X icon at the bottom is cut off at the top.

![Screenshot_2022-11-24-08-15-38-44_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/203805790-40a69bed-c447-4f49-a6e0-91f30475db66.jpg)

I think it would be good if the transparency layer behind the selected images was lighter, it's difficult to see borders of the images if they're light on light, or dark on dark.

**Comment by du82** [comment]
@OmarBasem please take a look, thanks

**Comment by OmarBasem** [comment]
Hi @du64, thank you for highlighting these issues. The new photo picker is not complete yet. It is still under development.
