### ISSUE TITLE
NFC Card

### ISSUE THREAD

**Issue by cryptoplatz-vault** [status-im/status-react#14449]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to integrate Status with NFC Card **so that** private keys and seed phrase will be stored outside the smartphone, offline and encrypted on NFC Card. 

### Description

[comment]: Sync new card, authorize send cryptocurrency, authorize login, backup card
[comment]: Login, withdrawal

### Acceptance Criteria

[comment]: # The card will be optional, use the NFC Card who wants more privacy and security.

### Notes

[comment]: # It is very easy, I already have the code on dart and node.js.

**Comment by flexsurfer** [comment]
hey @cryptoplatz-vault have you seen https://keycard.tech/ ?

**Comment by cryptoplatz-vault** [comment]
Yes, very similar to what we need to do with Status.

**Comment by flexsurfer** [comment]
ok but then why the issue in this repo? NFC Card support is already implemented

**Comment by cryptoplatz-vault** [comment]
> ok but then why the issue in this repo? NFC Card support is already implemented

Really? Can I use NFC Card on Status app?

**Comment by cryptoplatz-vault** [comment]
Sorry, now I found it https://status.im/keycard-integration/

Can I use any NFC Card or just keycard?

**Comment by flexsurfer** [comment]
cc @bitgamma

**Comment by bitgamma** [comment]
NFC card is a very broad term which encompasses simple memory cards (not secure) to smartcards (secure). However there isn't a standard way to store keys and sign transactions etc, meaning there is no way to have a generic solution working on all cards. 

Status supports Keycard which is an opensource applet and can run on any smartcard (NFC or not) that meets the requirements listed at https://keycard.tech/docs/applet_installation.html. We also distribute cards with Keycard preinstalled, based on NXP JCOP4 smartcards.

**Comment by cryptoplatz-vault** [comment]
Great! I will order a Keycard and use with Status, tnks!
