### ISSUE TITLE
can send messages as another user

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14446]
I can send messages as another user that I have no relation to (not mutual contacts, never initiated DM). This is not simply a graphical glitch, as it shows up as the other user sent it on all versions of mobile and desktop clients.

To reproduce: tap send button while shaking phone to attempt a bug report. If you time it right, the bug report action is never shown, and the message is sent by whoever sent the previous one. Must be on mobile data.

https://user-images.githubusercontent.com/65834069/204108573-ac6163d9-236f-4356-a887-da53e1f18e30.mp4

**Comment by du82** [comment]
This seems to correct itself mostly by resending the messages when the app is completely restarted

**Comment by cammellos** [comment]
@du64 is it possible to see the chat where this has happened? And can you replicate consistently?

**Comment by churik** [comment]
I'm able to replicate it  (tried it on IOS) with public chat
Incredible finding @du64 , thank you.


**UPD:** was able to reproduce only once, and after re-login issue is gone, on other devices it was shown as sent from right user. So eventually I'm not able to reproduce it even the second time. 
Can I ask you to give more details? (device, OS, build which you are using, logs if you have some)

**Comment by du82** [comment]
> @du64 is it possible to see the chat where this has happened? And can you replicate consistently?

the video should've been linked above, I can see it

**Comment by du82** [comment]
> I'm able to replicate it (tried it on IOS) with public chat Incredible finding @du64 , thank you.
> 
> **UPD:** was able to reproduce only once, and after re-login issue is gone, on other devices it was shown as sent from right user. So eventually I'm not able to reproduce it even the second time. Can I ask you to give more details? (device, OS, build which you are using, logs if you have some)

OnePlus Nord N20 5G (Chinese edition) phone running stock Android 11. It is reproducible on my Samsung as well, although I can't get it to work on an emulator because I can't shake those. For me it's working on the official 1.20 release, as well as all releases since then. I don't have logs sadly, as I delete and reinstall the app many many times throughout the day to do testing.

For me, it successfully sent messages as the other user about 1/3 of the time, and then corrected itself after a complete sign-out and sign back in, or clearing app cache.

**Comment by du82** [comment]
I'm not sure if this is related, but I can unpin, delete, edit, and send messages as other users, even in communities or DMs with no privelage to moderate.


https://user-images.githubusercontent.com/65834069/204912525-f5f67563-fce4-40be-ba34-749c7d3c462a.mp4

**Comment by du82** [comment]
I've only been able to edit another users message once, it's a very tricky thing to achieve, but it can be done by messing with the swipe down panel on Android

**Comment by churik** [comment]
closing as a stale issue, as new composer was implemented and there is no way to reproduce it for other users and it is gone after re-login
