### ISSUE TITLE
Can't create an account if PR and nightly builds are running on the same device simultaneously (Android, "Failed to create a go-waku node..." error on login)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14467]
Reproducible on Android

**Steps:**

1. Install the latest nightly build 
2. Install any PR build 
3. Create an account on the PR build and keep it logged in and running in the background
4. Open the nightly build and try to create a new account/recover an existing one from a seed phrase

**Actual result:** The onboarding flow gets stuck at the password creation step if a PR build with a logged in account is running at the same time.  
If you go back and try to create a password again, it will crash the app. 
If you open the app after the crash and try to log in, the "Failed to create a go-waku node..." error will appear. 
User is able to login when another running build is removed from the background (closed). 

**Expected result:** able to create/recover an account in the app on both running builds

![photo_2022-12-01 16 40 17](https://user-images.githubusercontent.com/97245802/205081192-d06c955c-2dfd-4f8c-b4b7-3943a6d3e569.jpeg)

https://user-images.githubusercontent.com/67952253/208465231-bdaf85b0-a631-46cc-9f96-c093b37edce1.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
reproducible in case when you have Status PR build running on the same fleet, don't think it worth looking on it

**Comment by pavloburykh** [comment]
> reproducible in case when you have Status PR build running on the same fleet, don't think it worth looking on it

Let's fix that in order to be able to run both builds at one time.
