### ISSUE TITLE
Move mock data to central location and out of views.

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14462]
As discussed with @ilmotta -https://github.com/status-im/status-mobile/pull/14444#discussion_r1033704197

It would be nice to move mock data to a higher centralised location in the application.
This means that views etc do not need to handle such data mocking and eventually when we go to remove the mock data then it is done in one place 
and the respective views do not need adjustment.

Discuss with the team on an appropriate solution.
Document this discussion and decision

Go through the codebase and find any mock data.
Apply the solution that the team has agreed upon.

Some examples:
"src/status_im2/contexts/communities/discover/view.cljs"
"src/status_im2/contexts/communities/overview/view.cljs"

discuss with Desktop team if they have any knowledge of this api should look so that we can match what will eventually be implemented.

**Comment by vkjr** [comment]
Closed as unnecessary per discussion [here](https://github.com/status-im/status-mobile/pull/15102#issuecomment-1433245808)
