### ISSUE TITLE
Messages, that are sent while both devices are online may be received in >10 mins (status.prod)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14466]
# Bug Report

## Problem 
Currently, messages that are sent online, are not received immediately. Some of them may be received in seconds, and some do not appear even in 10-15 mins.
Login fixes the issue, all messages are fetched successfully after relaunch.
Reproducible for any type of chat.
**The issue is reproducible only on the mobile client, on the desktop can see messages right after sending.**
**Not reproducible on eth.prod fleet**

#### Expected behavior
Can see messages in the right order after sending 

#### Actual behavior

https://user-images.githubusercontent.com/4557972/204811084-1e9fa561-8167-46b8-8b99-70c2b9b29941.mp4

### Reproduction

1) User A: send some bunch of messages to UserB
2) UserB: check chat with UserA

### Additional Information

- Status version: nightly  30/11/22
- Operating System: Android, iOS
- Fleet: status.prod
- Wakuv: v0.13.0-32-gbcab36
- Log(receiver): [geth.log](https://github.com/status-im/status-mobile/files/10123783/geth.log)

**Comment by churik** [comment]
Note:  light client protocols are disabled on `status.prod`,  `status.test` can be used for this.

**Comment by cammellos** [comment]
@churik this one should be fixed on new accounts on develop, would you mind checking please?

**Comment by churik** [comment]
That's fixed, works perfectly.
Thank you for addressing it!
\

**Comment by churik** [comment]
The issue is fixed, there are some other issues with the unread indicator (which may be related or not) that will be logged separately.
Tested with 1-1, group chats and communities.
Thank you for addressing this one!
