### ISSUE TITLE
Validate key when adding a contact

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14478]
As a user
I want to check whether the key I have inputted is valid
So that I can correct any mistake

### Description
The error should be shown as soon as the key in the input box is not valid (i.e if the user types zQ it should already show an error), and disappear as soon as a valid key is in the input box.

### Designs
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1694%3A380190&t=D6cAP4sUcnKzVSgH-0

Depends on https://github.com/status-im/status-mobile/issues/14477

**Comment by erikseppanen** [comment]
How should form validation work for these various inputs? @cammellos 

The following is my interpretation of current requirements:

Valid inputs:
1. A compressed key (validated with regex `^zQ3[0-9A-HJ-NP-Za-km-z]{46}`). status-go will attempt to convert to uncompressed key, and if successful, it is is considered valid.
#14845
2. `.eth` ENS: if input ends with `.eth`, status-go will attempt to resolve it. If resolved, input is considered valid. However, currently what should be valid ".eth" names (like "vitalik.eth") are returning "0x04000...".
#14480
3. `.stateofus.eth` ENS. If input does not end in ".eth", it appends `.stateofus.eth` and status-go attempts to resolve it. If resolved, input is considered valid.
#14480
4. A join.status.im link `https://join.status.im/u/{key/ens-name}`
#14814

Invalid inputs:
1. A valid uncompressed key (validated with regex `0x04[0-9a-f]{128}`). If it passes regex, it is considered invalid and returns error "This is not a chatkey".
#14477
2. User's own ENS or chatkey (as @VladimrLitvinenko states below).

This issue says that an error should be shown as as soon as the key is not valid (eg, if the user types zQ it should already show an error). However, ETH names can start with "0x", "zQ3", and "https" (but must be at least 3 characters).

**Comment by VolodLytvynenko** [comment]
@cammellos which validation should be shown if the user enters his own ENS or his own chat key? Is it the same as shown in the old implementation 'That's you, to start a chat choose someone else' or user should be able to find his profile?
Thanx!

Old implementation:
![image](https://user-images.githubusercontent.com/52490791/215546163-f6a88ea7-a398-4e4a-9bc5-9a8bcb5d8773.png)

**Comment by VolodLytvynenko** [comment]
> 2. User's own ENS or chatkey (as @VladimrLitvinenko states below).
> 
> This issue says that an error should be shown as as soon as the key is not valid (eg, if the user types zQ it should already show an error). However, ETH names can start with "0x", "zQ3", and "https" (but must be at least 3 characters).

@erikseppanen Thank you!
