### ISSUE TITLE
Lookup contact/add a contact from home screen

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14477]
As a user
I would like to add a contact by typing their chat key
I would like to add a contact by typing their ENS

### Description

We should only support compressed keys, and https://join.status.im/u/{key/ens-name} links.
If the key is valid, or the ENS name resolves, we should enable the View Profile button, which if clicked, will take you to the user's profile.

Out of scope:
- Retrieve user info
- User's profile page

### Designs

The structure of the bottom sheet is already in place as it has been implemented in the community screens, please re-use that component if possible.

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=628%3A174935&t=D6cAP4sUcnKzVSgH-0

**Comment by du82** [comment]
Shouldn't we use status.app links per designs?

**Comment by cammellos** [comment]
This has been merged in develop
