### ISSUE TITLE
Edge case when delete pinned messages in community

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#14488]
This is a follow-up issue for https://github.com/status-im/status-mobile/pull/14232

Need input from designer. Q: what to do when 
1. user A sent a message
2. admin pinned the message
3. user A try to delete the message while don't have the permission to unpin the message

Potential solutions
1. user A can delete the message, the pinned message turns to "message deleted by user xxx" ✅
2. ~user A can't delete the message, hide the delete message for everyone option in the context menu for such kind of messages~

**Comment by VolodLytvynenko** [comment]
Hi @yqrashawn  some questions related to the spec of this task. Could you help here, please?
1.  Should the same logic work for the group chat?
2. Should the pin banner be shown with text '' in such a case? 
![image](https://user-images.githubusercontent.com/52490791/219436835-96644840-50b8-417a-a713-4fd6a93a802e.png)

**Comment by yqrashawn** [comment]
1. yes
2. asked in mobile-ui
