### ISSUE TITLE
No "from Name" is shown in requesting message if it was received when group chat is not opened [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1448]
### Description

*Type*: Bug

*Summary*: Request message has no "from X" part in group chat in case receiver has other app screen (not this group chat) opened
![screenshot_20170714-121657](https://user-images.githubusercontent.com/6584810/28206486-bd99a794-688e-11e7-85e4-a33fa5e4463d.png)

#### Expected behavior
Request message contains part "from X", where X is username who needs to send ether
#### Actual behavior

Request message does not contain part "from X"
### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7S21jZjRpUmN1RE0
- As contact B: open Chats screen (do not open group chat with A)
- As contact A: in group chat with contact B request ether from B
- As contact B open group chat with A

### Additional Information
* Status version: 0.9.8-72-ga0de31eb+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by annadanchenko** [comment]
#1741 
still testing

**Comment by annadanchenko** [comment]
tested on build #3 with  #1741 fixed - looks ok to merge

**Comment by jeluard** [comment]
Fixed in develop
