### ISSUE TITLE
Persist switcher tabs between devices / installs

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14486]
As a user, I want my switcher tabs to sync between devices and remain even if I delete and reinstall the app, the same way contacts do currently.

**Comment by Parveshdhull** [comment]
Hi @du64, thank you for your suggestion.

Switcher tabs represent the app's state on a particular device and another device will have its separate state. For example, the order of the community card will depend on when and if that community is opened on that device.
So syncing is not beneficial for switcher cards.
But cards will be persisted across sessions so the app's state can be restored after restart (currently WIP).
