### ISSUE TITLE
Allow user to paste ENS/chat key when adding contact 

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14481]
As a user
I would like to add a contact by pasting the ENS/chat key

### Description
We should allow user to paste an ENS/chat Key

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=628%3A174935&t=D6cAP4sUcnKzVSgH-0

Depends on: https://github.com/status-im/status-mobile/issues/14477

**Comment by VolodLytvynenko** [comment]
**NOTES for QA:**
Check ability to use [x] button to clean the textbox is scope of current task
