### ISSUE TITLE
Header background image remains partially blurred after fast scrolling to the up of the Community page (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14507]
Reproducible on Android

**Steps:**

1. Open any community in the list of Discovery page
2. Scroll down the page (observe header image becoming blurred)
3. Scroll up the page by fast swipe 
4. See if header image is unblurred

**Actual result:** header image remains partially blurred. 

**Expected result:** header image is not blurred

![photo_2022-12-06 20 41 16](https://user-images.githubusercontent.com/97245802/205994937-5dbc3191-4511-43ea-be39-e21a0615c5fd.jpeg)

https://user-images.githubusercontent.com/97245802/205994941-772d80f5-c8c3-4bb5-9756-689c689bfa28.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
can't replicate anymore, feel free to reopen if still an issue
