### ISSUE TITLE
[quo2 new design tech debt] refactor pinned-banner to banner component in quo2 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#14528]
status-im.ui2.screens.chat.pinned-banner.view should be refactor to quo2 banner component

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=863%3A26323&t=JeFB0V7ClQQKQsuA-3

**Comment by J-Son89** [comment]
I will work on creating this component now in:
https://github.com/status-im/status-mobile/issues/14605

and follow up with this task to implement in chat screens 👍

**Comment by flexsurfer** [comment]
@J-Son89 it's already implemented here `status-im.ui2.screens.chat.pinned-banner.view`

**Comment by flexsurfer** [comment]
but we need to move it as component to quo2 and make sure its implemented according latest design with quo2 components

**Comment by J-Son89** [comment]
cool, I'll copy that over so! thanks :D
