### ISSUE TITLE
"scrollTolndex should be used in conjuction with getItemLayout..." error after switching filters and reopening AC (IOS only)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14532]
Reproducible only in IOS. Device iPhone X, IOS v.14.1

Bug might be related to recent changes in https://github.com/status-im/status-mobile/pull/14492 @ilmotta Could you please take a look when you got a chance? Thanx! 

**Steps:**
1. Open AC
2. Switch between different filters
3. Close and reopen AC after every filter switch
4. See if any errors appear

**Actual result:** after couple of filter switchings and reopening AC - the error will appear "scrollTolndex should be used in conjuction with getItemLayout..."

**Expected result:** no errors

![photo_2022-12-13 16 25 34](https://user-images.githubusercontent.com/97245802/207359331-496f7186-24df-494a-a299-1c9051ffe240.jpeg)

https://user-images.githubusercontent.com/97245802/207359394-5d34ef73-0970-41b5-b955-266201c514fa.mp4

[geth.log](https://github.com/status-im/status-mobile/files/10218817/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/10218818/Status.log)

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Thanks for reporting the issue @pavloburykh. I could not yet reproduce it, but I'll dig into this problem when I finish the work on https://github.com/status-im/status-mobile/issues/14495.

**Comment by pavloburykh** [comment]
> Thanks for reporting the issue @pavloburykh. I could not yet reproduce it, but I'll dig into this problem when I finish the work on #14495.

Thank you @ilmotta ! Let me know if you need any help or more details on reproduction.

**Comment by ilmotta** [comment]
@pavloburykh, I have a pretty good idea on how to solve this problem, but without an iOS development environment I would only be able to fix by trial and error, which could end up wasting a lot of our time (yours and mine). I'll try to find someone that's actually able to reproduce the issue next week.

Edit:

For future reference, these might be useful to devs:

- https://stackoverflow.com/questions/57471165/efficient-way-to-scroll-to-certain-index-in-flatlist-with-variable-item-size
- https://reactnative.dev/docs/virtualizedlist#onscrolltoindexfailed
- https://stackoverflow.com/questions/53059609/flat-list-scrolltoindex-should-be-used-in-conjunction-with-getitemlayout-or-on

**Comment by pavloburykh** [comment]
@ilmotta thanx for your investigation on this bug. IMO the issue is not urgent or critical as most of AC types of notifications are still in progress of development. So take your time, no worries about it. I have logged this bug in order we keep in mind that such kind of issue exists. Thank you!

**Comment by ilmotta** [comment]
> @ilmotta thanx for your investigation on this bug. IMO the issue is not urgent or critical as most of AC types of notifications are still in progress of development. So take your time, no worries about it. I have logged this bug in order we keep in mind that such kind of issue exists. Thank you!

Good to hear about the priorities, thanks @pavloburykh

**Comment by ilmotta** [comment]
@smohamedjavid, copying you here because you develop in macOS. Whenever you finish your top priorities (no hurry), could you help us by investigating this issue, given it only happens in iOS?

**Comment by smohamedjavid** [comment]
@pavloburykh - Kindly check PR #14641 and let us know if you encounter the bug.

**Comment by pavloburykh** [comment]
> @pavloburykh - Kindly check PR #14641 and let us know if you encounter the bug.
Hi @smohamedjavid Thanx for the fix! Will take it into testing as soon as it passes the review.
