### ISSUE TITLE
Set waku-2 fleet by default on existing users

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14545]
For existing users, we should override the waku-2 settings with the new values (the same as we have in nodes), ideally whatever the clients passes, overrides whatever is in the status-go db.

**Comment by rasom** [comment]
@cammellos so with `:WakuV2Config` it is straightforward, we just need to add those configs as a parameter to `loginWithConfig`.

Regarding fleet: so we want existing accounts to be updated to `status.prod`, correct? Do we want this this only once after upgrade, or we just disable the option to change this setting manually?

**Comment by cammellos** [comment]
> @cammellos so with `:WakuV2Config` it is straightforward, we just need to add those configs as a parameter to `loginWithConfig`.
> 
> Regarding fleet: so we want existing accounts to be updated to `status.prod`, correct? Do we want this this only once after upgrade, or we just disable the option to change this setting manually?

I think we don't have to update existing accounts to use `status.prod`, just if they do use `status.prod`, we should use the new values, I think that's good enough for now.

**Comment by rasom** [comment]
@cammellos ok, understood
