### ISSUE TITLE
Cannot use "Chat" button on another user profile until accepting contact request

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14541]
# Bug Report

## Problem 
As currently the design for other user profiles (stranger) in [WIP state](https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?node-id=3443%3A204489&t=zpwXE74sIuKBMEBe-4) current user profile will be used instead. 
After https://github.com/status-im/status-mobile/pull/14492 is merged, there is no way to chat user who did not accept your contact request.

#### Expected behavior
Cannot send message to the user until sending CR
**Suggested for now:** disable "Chat" button until sending and approving CR

**Also in the scope of the same issue "Mutual contact request" (Profile > Settings > Advanced) should be enabled by default**

#### Actual behavior
Can send a message and it won't be delivered
<img width="220" alt="Monosnap 2022-12-14 17-39-42" src="https://user-images.githubusercontent.com/4557972/207654998-8e15534b-c927-45b8-8069-f19098ad4c0b.png">

### Reproduction

1) Open Status
2) Join any community or pub channel
3) Tap on another user profile (not contact)
4) Tap on "Chat"

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
@cammellos Should we disable accessing a 1-on-1 with the user until they're mutually have accepted a CR ?

**Comment by cammellos** [comment]
@ibrkhalil yes

**Comment by ibrkhalil** [comment]
Okay, Will create a PR to do it
