### ISSUE TITLE
The ENS is not resolved into the chats after @ is entered

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14540]
**Steps to reproduce:**
1. UserA and UserB are contacts
2. Set ens for UserB
3. Go to 1-1 chat as UserA
4. Type @

**Actual result:**
The '3 random name' of userB are shown after @ is typed

**Expected result:**
ENS of UserB is shown and able to be mentioned by his ENS

**Additional info:**
User with ENS for usage:
- Seed phrase: spike spoil hidden sad juice force trap bind situate consider suit demand
- ENS: volodymyr.eth

**Comment by ibrkhalil** [comment]
I can't reproduce this, I added your account `volodymyr.eth` and I was able to successfully mention you in 1-on-1

**Comment by VolodLytvynenko** [comment]
@ibrkhalil correct. This issue is invalid. Sorry for that. Thanx
