### ISSUE TITLE
The input textbox is not tappable if message is typed into buffer of the chat, then current chat is reopened

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14542]
**Steps to reproduce:**
1. Create a new 1-1 chat
2. Start typing text within a chat
3. Tap 'back' button
4. Open current chat again
5. Try to edit the message saved into textbox
6. Send the message

**Actual result:**
- The textbox does not react on the taps after step 5 and as result, the text can't be edited
- The sent message is not visible fully after step 6 even after scrolling to the bottom

https://user-images.githubusercontent.com/52490791/207652663-0470b84f-6d83-4a0e-b05a-ef9f91c25d40.mp4

**Expected result:**
- Message is able to be edited after the user reopens the chat
- The last sent message is visible and a user can't see it fully

**ENV:** Huawei p20 light. v9

**ADDITIONAL INFO:**
This issue is reproducible only for my real device. I tried to reproduce it on the other androids with the same OS v9, but was unsuccessful

**Comment by churik** [comment]
Couldn't reproduce on Xiaomi Mi Note 9 Pro (Android 10)
