### ISSUE TITLE
Allow user to mute a community channel

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14556]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to mute a community channel.

### Description

Figma designs: 

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=6504%3A438974&t=HHyeFzRQAjawE88J-4

And here you can find how a muted channel should look like in the channels list:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1506%3A107834&t=HHyeFzRQAjawE88J-0

<img width="250" alt="Screenshot 2022-12-15 at 17 43 46" src="https://user-images.githubusercontent.com/67952253/207919565-cb40f777-2c16-47c2-b60c-5d83ed8baad8.png">

### Acceptance Criteria

- all activities are muted: no unread indicator for new messages, mentions, and replies
- no unread indicator on the community icon if a new message is received only in a muted channel

**Comment by ibrkhalil** [comment]
The work for this issue is split into two tickets
The attached one and [this](https://github.com/status-im/status-mobile/pull/15253/)
Pending review from QA CC: @status-im/mobile-qa

**Comment by pavloburykh** [comment]
> The work for this issue is split into two tickets The attached one and [this](https://github.com/status-im/status-mobile/pull/15253/) Pending review from QA CC: @status-im/mobile-qa

thanx @ibrkhalil We will be able to review https://github.com/status-im/status-mobile/pull/15253/ once we finish with Release testing. BTW, I see that all of the builds [here](https://github.com/status-im/status-mobile/pull/15253/) are failed.

**Comment by ibrkhalil** [comment]
> > The work for this issue is split into two tickets The attached one and [this](https://github.com/status-im/status-mobile/pull/15253/) Pending review from QA CC: @status-im/mobile-qa
> 
> thanx @ibrkhalil We will be able to review #15253 once we finish with Release testing. BTW, I see that all of the builds [here](https://github.com/status-im/status-mobile/pull/15253/) are failed.

Oh sorry about that .. Branch is getting old and needs rebasing .. Will do
