### ISSUE TITLE
Always handle :signal-event

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#1455]
### User Story

As a user, I don't want unexpected exceptions.

### Description

A red screen apears during startup sporadically. Underlying issue is a `:signal-event` event not properly handled.
As the associated handler actually exists it suggests a race condition during startup leading to this event being fired before the handler has been properly registered.

*Type*: Bug

### Reproduction

It happens randomly (once every 3 starts?) on my Samsung A5 (adnroid).

### Solution

Make sure all handlers are registered before we receive events. [re-frame-async-flow-fx](https://github.com/Day8/re-frame-async-flow-fx) might be useful here.

**Comment by yenda** [comment]
@jeluard do you still have this error after the init refactoring ? There shouldn't be any race conditions during init now

**Comment by jeluard** [comment]
This one is really old ..
