### ISSUE TITLE
"Scroll to the last message" button does nothing on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14557]
# Bug Report

## Problem 
Scrolling to the end of the chat history doesn't work on IOS.

#### Expected behavior
scroll to the end of the chat history

#### Actual behavior

https://user-images.githubusercontent.com/4557972/207922271-eaf7c55b-ec5d-4330-817e-886da2c59f77.MP4
(I'm tapping here on the button constantly)

### Reproduction

1) Open Status
2) Send several big messages in order to see button
3) Scroll to the start of the history
4) Try to tap on the button "scroll to the last message" 

### Additional Information

- Status version: nightly 15/12/22
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
@cammellos Could you please assign this to me?
