### ISSUE TITLE
Refactor chained animations of Record Button using withSequence method from Reanimated2

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#14561]
# Problem

For achieving the desired effect on infinite rings animation we need to chain some animations. Currently we use a `setTimeout` with a timeout value equal to the previous animation duration, but ideally we would want to use `withSequence` method from Reanimated2 (or Reanimated3 if we eventually upgrade React Native and therefore the Reanimated library). This issue is to research how to implement it and refactor that part of the code to use withSequence.

PR where the code was introduced is #14170 

## Implementation

On `record_audio.cljs` quo2 component, replace setTimeout with a sequence of animations using withSequence

## Acceptance Criteria

Refactor correctly using `withSequence` and don't break the animation :)

**Comment by ajayesivan** [comment]
@cammellos Please assign this to me.

**Comment by cammellos** [comment]
closing for now as out of mvp
