### ISSUE TITLE
Community join screens - implement bottom sheet with correct scrolling and designs

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14564]
See the designs:
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=7643%3A608085&t=bc5QBHpQ3uZT8W6b-0

On the join screens the bottom sheet has some advanced styling. 

This is also dependent on the new bottom sheet being finished as that should be used here so best to wait for this work to be merged: https://github.com/status-im/status-mobile/pull/14209

**Comment by alwx** [comment]
Linked to https://github.com/status-im/status-mobile/issues/14955

**Comment by churik** [comment]
@alwx are you still working on this?

**Comment by alwx** [comment]
@churik just removed the assignment since I probably have too many issues assigned to me
