### ISSUE TITLE
Add message delivery states

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14588]
As a user
I want to know if my message has been sent/delivered
So that I understand if the other recipient has read my message

### Description
We should add delivery states for dogfooding, to facilitate debugging and understanding where things might go wrong.
We have no designs currently, since those are still pending some discussion, so for now, best to have something that's the least disruptive. (a small icon next to the timestamp for example, a la whatsapp?)

There's a distinction between types of chats:

A message will start in `Sending...` state. That's for all chats.
A message will become `Sent` when it leaves your device. That's for all chats.

The above is all we have for community chats/public chats.

A message will be marked as delivered when acknowledge by the other recipient in a one-to-one.
A message will be marked as delivered when acknowledge by at least one other recipient in a private group chat.

All signals are already available since this feature was already present in the old UI.

**Comment by siddarthkay** [comment]
fixed with https://github.com/status-im/status-mobile/pull/14573
