### ISSUE TITLE
Issues where '3 random name' and text on preview chat are out of the screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14599]
## ISSUE 1: The 3 random names or nicknames is out of the screen in the preview of the 1-1 chat
**Steps to reproduce:**
1. Create USER_A with long '3 random name' or with long nickname
2. Make USER_A and USER_B as mutual contacts
3. Open a 'list of chats' page to check the preview as USER_B
4. Send some messages into 1-1 chat

**Actual result:**
The long name is out of the screen and as result, the unread badge and time of the sent message is overlapped
![image](https://user-images.githubusercontent.com/52490791/208896122-0091c018-6c1c-46f0-9235-1b549566b911.png)

**Expected result:**
- The unread badge and time of the sent message are shown separately
![image](https://user-images.githubusercontent.com/52490791/208899305-3769e80b-54b4-44e4-b727-8f156fae00ca.png)

- 3 dots cut the long '3 random name' or nickname... 

**ENV:** Huawei p20 light. Screen resolution for current device 2280x1080

## ISSUE 2: The text is out of the screen if long text is pasted or long invite to the community is sent
**Steps to reproduce:**
1. Open to 1-1 chat
2. Paste some long text into input textbox
3. Open a 'list of chats' page to check the preview

**Actual result:**
- The text is out of the screen if long text is pasted
![image](https://user-images.githubusercontent.com/52490791/208898219-f7a088a9-b423-40a2-ac30-fa426a5811f4.png)
- The text is out of the screen if a long invite to the community is sent 
https://user-images.githubusercontent.com/52490791/208899515-47525bb4-b542-47e9-9788-eb668484b5cf.mp4

**Expected result:**
Long text should be cut in the preview by 3 dots
![image](https://user-images.githubusercontent.com/52490791/208899915-a8befecf-97af-426e-97db-dec6193e664f.png)

## ISSUE 3: The long 3 random names and nicknames should be cut on the group details page

**Steps to reproduce:**
1. Create USER_A with long '3 random name' or with long nickname
2. Make USER_A and USER_B as mutual contacts
3. Create group chat as USER_B-> invite USER_A during chat creation
4. Long tap on the created group chat -> tap 'goup detail' option

**Actual result:**
3 dots are under the '3 random name'
![image](https://user-images.githubusercontent.com/52490791/208901291-73b3be6c-09a6-4dd2-be4a-15b27810ec8a.png)

**Expected result:**
- 3 dots are shown separately
- Long '3 random name' is cut by 3 dots
![image](https://user-images.githubusercontent.com/52490791/208901614-0beaf651-e9ff-490c-ace9-f3d724d8c165.png)

## ISSUE 4: The long 3 random names and nicknames should be cut on the member page**

**Steps to reproduce:**
1. Create USER_A with long '3 random name' or with long nickname
2. Make USER_A and USER_B as mutual contacts
3. Create group chat as USER_B-> invite USER_A during chat creation
4. Long tap on the created group chat -> tap 'group detail' option
5. Tap 'manage members' section

**Actual result:**
![image](https://user-images.githubusercontent.com/52490791/208902110-249bebb2-5ecd-4883-8019-edc390b12e7c.png)

**Expected result:**
Long 3 random names should be cut and should not overlap by checkmarks

**ENV:** Huawei p20 light. Screen resolution for current device 2280x1080

## ISSUE 5 The message with long text is not shown fully on the opened chat**
**Steps to reproduce:**
1. Send the message with the long text
2. Check it in the chat

**Actual result:**
![image](https://user-images.githubusercontent.com/52490791/210819993-4f54f599-b284-4184-a0f0-ff89b703d6e6.png)

**Expected result:**
Figma

## ISSUE 6 The long time mark is not shown fully if a user with long '3 random name' sends the message**
**Steps to reproduce:**
1. Select user with long 3 random name during account creation
2. Go to 1-1 chat
3. Send the message

**Actual result:**
The time mark is shifted out of screen
![image](https://user-images.githubusercontent.com/52490791/210822305-cbd3e144-f7e3-444e-9742-d36742dc0fe8.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/52490791/210829223-55251fa5-ecba-4aa5-b5f4-f81b4b95e6b0.png)

## ISSUE 7 The letters are not shown as per design for preview chat ring**

**Steps to reproduce:**
1. Create 1-1 chat with the user without profile image
2. Go to the preview page of chats

**Actual result:**
The letters are shifted into the ring of the preview
![image](https://user-images.githubusercontent.com/52490791/210825878-3831bb7f-768f-4dfc-aef9-90c8ecb60f5f.png)

**Expected result:**
The letters are shown as per design
![image](https://user-images.githubusercontent.com/52490791/210827074-7f38c885-c563-4701-b4ef-2d0af155da80.png)

**Comment by VolodLytvynenko** [comment]
## ISSUE 8 The notif about the deleted message is out of the screen if 3 random name or nickname is too long
**Steps to reproduce:**
1. Create multi-account -> select long 3 random name during account creation
2. User_A and User_B are mutual
3. Go to 1-1 chat as User_A
4. Send message
5. Long tap the message
6. Select 'delete for everyone' option
7. Check the message as User_B

**Actual result:**
The notif about the removed message is shown out of screen
![image](https://user-images.githubusercontent.com/52490791/220173134-35a5e3c8-ea6d-4b72-9f42-ed40225006dd.png)


**Expected result:**
The 3 random or long names are fully shown
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2272%3A149712&t=ZcB5q6O7snnRttYK-0
![image](https://user-images.githubusercontent.com/52490791/220172614-21c5460a-a5bf-4c69-b93b-365d1e48093d.png)

**Comment by churik** [comment]
I guess we might close it, as there are no 3 random names available anymore

**Comment by alwx** [comment]
@churik technically there might still be long names

**Comment by VolodLytvynenko** [comment]
> @churik technically there might still be long names

hi. long names issue fixed here https://github.com/status-im/status-mobile/pull/17414
