### ISSUE TITLE
Drawer overlaps an image in chat view (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14606]
# Bug Report

## Problem 

**Steps to reproduce:**
1. Open a community channel on an Android device
2. Tap an `Image` icon, grant permission, select an image from the gallery
3. Tap `Confirm selection`

https://user-images.githubusercontent.com/67952253/208933431-a7b34b85-6064-4827-9944-060b0de3d917.mp4

#### Expected behavior
Can see the selected image in the drawer

#### Actual behavior
The image is behind the drawer

### Additional Information

- Status version: nightly 21/12
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
cc @ibrkhalil @OmarBasem

**Comment by ibrkhalil** [comment]
Gonna work on it in a couple of minutes, Wrapping something up

**Comment by ibrkhalil** [comment]
> cc @ibrkhalil @OmarBasem

Fix here https://github.com/status-im/status-mobile/pull/14609
![image](https://user-images.githubusercontent.com/33176106/208987671-6e64af94-568a-4fc0-adeb-2276f2bdafc0.png)

**Comment by du82** [comment]
There's a problem with the rendering on Android

![Screenshot_2022-12-21-13-31-19-16_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/208987948-7a293554-78d1-4403-8a34-8113707e8b31.jpg)

**Comment by ibrkhalil** [comment]
> There's a problem with the rendering on Android
> 
> ![Screenshot_2022-12-21-13-31-19-16_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/208987948-7a293554-78d1-4403-8a34-8113707e8b31.jpg)

Kindly create an issue for it, I'll fix after finishing something with new chat flow

**Comment by qoqobolo** [comment]
> Fix here #14609

@ibrkhalil thank you for such a  quick fix!

**Comment by ibrkhalil** [comment]
> > Fix here #14609
> 
> @ibrkhalil thank you for such a quick fix!

My pleasure
