### ISSUE TITLE
Add accessibility id for the scroll button

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14617]
**Steps to reproduce:**
1. Create '1-1' or 'group' or 'community' chat
2. Send several long messages
3. Scroll up to the top message
4. Check the scroll button

**Actual result:**
The scroll button is without an 'accessibility id'
![image](https://user-images.githubusercontent.com/52490791/209108305-03486e16-baab-4f9d-9baf-e5ba4f895df9.png)

**Expected result:**
The  scroll button is with 'accessibility id'

**Comment by Parveshdhull** [comment]
Hi @VladimrLitvinenko, As I can see there is already a accessibilty-id (:bottom) assigned, [there](https://github.com/status-im/status-mobile/blob/e9252f50259785ab13015401ce647f022e65fb00/src/quo2/components/buttons/dynamic_button.cljs#L72). 
I am not sure why it is not accessible :thinking:

**Comment by Parveshdhull** [comment]
I am not familiar with testing & accessibility-id's, but looks accessibility-id is accessible.
![image](https://user-images.githubusercontent.com/17097240/209124945-34c857f6-729d-4976-84da-b0004e62c8aa.png)

Is it not unique or something?

**Comment by Parveshdhull** [comment]
![image](https://user-images.githubusercontent.com/17097240/209125314-cac55680-a421-4dcc-9daf-e338759f57a4.png)

Only parent is clickable/button (with content-desc "bottom"), child is just a simple view. Should I assign accessibility-id to that too.

**Comment by VolodLytvynenko** [comment]
> ![image](https://user-images.githubusercontent.com/17097240/209125314-cac55680-a421-4dcc-9daf-e338759f57a4.png)
> 
> Only parent is clickable/button (with content-desc "bottom"), child is just a simple view. Should I assign accessibility-id to that too.

@Parveshdhull Oh. I see. Can't believe that I didn't notice it. This issue is invalid. Sorry for that

**Comment by Parveshdhull** [comment]
np :)
just `bottom` looks confusing, I will change it to `scroll-to-bottom` or something in the next PR. Thank you for bringing it to my attention.
