### ISSUE TITLE
The device is not able to be switched to the numerical mode during message input [for Huawei devices only]

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14619]
**Steps to reproduce:**
1. Go to the 1-1 chat
2. Tap on the textbox
3. Tap on the 'numerical mode' button within the opened keyboard

**Actual result:**
The keyboard is auto-switched back to the literal mode
https://user-images.githubusercontent.com/52490791/209110251-69d61b4f-337c-40bd-8f16-fb12defb26b5.mp4

**Expected result:**
The keyboard is switched to numerical mode

**ENV:** Huawei p20 light OS: V9; Huawei p40 light OS: EMUI 12

**Additional info:** This issue is reproducible only on the Huawei devices

**Comment by cammellos** [comment]
I thnik this will be a won't fix, closing for now, feel free to reopen
