### ISSUE TITLE
Graphical glitch on image picker

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14611]
The image has graphical glitches at the bottom on Android. Haven't tested iOS, I don't own Apple stuff

![Screenshot_2022-12-21-13-31-19-16_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/208990828-3f03803d-b49f-4e1e-9b2f-616dc6e57ee7.jpg)

**Comment by du82** [comment]
@ibrkhalil here's the updated issue, thanks for letting me know where it goes

**Comment by ibrkhalil** [comment]
![image](https://user-images.githubusercontent.com/33176106/208994655-f1e97ebb-9244-4620-bc44-6b7b2fbc21c4.png)
After the fix

**Comment by du82** [comment]
It does this for me

![Screenshot_2022-12-21-15-16-05-80_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/209009718-fbdecf2e-03f5-427d-b09e-b07a7dabeef6.jpg)

**Comment by ibrkhalil** [comment]
@du64 What device/emulator is that please ?
