### ISSUE TITLE
Two jump to buttons in chat

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14627]
There are two "Jump to" buttons in chat. This was likely caused by a change in PR #14494 

![Screenshot_2022-12-22-21-45-45-70_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/209267079-1380d04a-963e-4aca-a8c6-bbd4bafcbfb6.jpg)

**Comment by flexsurfer** [comment]
thank @du64 , reverted this PR, could you check ?

**Comment by du82** [comment]
> thank @du64 , reverted this PR, could you check ?

Yes that fixed it
