### ISSUE TITLE
Editing message issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14621]
**ISSUE 1. [Send] button is not visible during message editing**
**Steps to reproduce:**
1. Go to 1-1 chat
2. Send the message
3. Long tap on it
4. Add some additional text into the editing textbox
5. Try to tap 'send' button

**Actual result:**

[Send] button is not visible

https://user-images.githubusercontent.com/52490791/209150399-d16e00cd-5ffa-4c01-ac58-6527bd1216a9.mp4

**Expected result:**
[Send] button is visible

**ENV:** Android devices

**ISSUE 2. [Only for IOS devices] The initial message is not shown into the input textbox if 'edit message' option is selected**

**Steps to reproduce:**
1. Create 1-1 chat
2. Send a message
3. Long tap on the message
4. Tap 'edit message'

**Actual result:**
https://user-images.githubusercontent.com/52490791/209154631-c8e00d73-aa94-4e8d-b8b1-dcf4aac73f7a.MP4

The initial message that intended to be edited is disappeared
**Expected result:**
The initial text is shown after 'edit message' option is tapped

**ISSUE 3: Mark that the message is edited should be shown**

**Steps to reproduce:**
1. Go to 1-1 chat
2. Send the message
3. Long tap the message -> tap 'edit  message' option
4. Make some changes -> tap 'send' button

**Actual result:**
The changed message is not  marked as 'changed'

**Expected result:**
![image](https://user-images.githubusercontent.com/52490791/209155661-bb66c875-8840-4530-a614-20cb9e5d49b5.png)

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil Take a look please one more issue

**ISSUE 4: Edited message is not updated within banner and the list of pinned messages**
**Steps to reproduce:**
1. Go to 1-1 chat
2. Send the message
3. Pin the current message
4. Long tap on the message inside the chat
5. Tap 'edit message' option -> make some edits for the message

**Actual result:**
The message is not edited within 'pin banner' and list of pinned messages
![image](https://user-images.githubusercontent.com/52490791/209549347-5d1a7144-e33f-40dd-a17b-cb8011ef36d2.png)

**Expected result:**
The message is edited within 'pin banner' and list of pinned messages
![image](https://user-images.githubusercontent.com/52490791/209549423-083309c7-b1b4-4e30-a6bd-ae878b0820e7.png)

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil Take a look please one more issue
> 
> **ISSUE 4: Edited message is not updated within banner and the list of pinned messages** **Steps to reproduce:**
> 
> 1. Go to 1-1 chat
> 2. Send the message
> 3. Pin the current message
> 4. Long tap on the message inside the chat
> 5. Tap 'edit message' option -> make some edits for the message
> 
> **Actual result:** The message is not edited within 'pin banner' and list of pinned messages ![image](https://user-images.githubusercontent.com/52490791/209549347-5d1a7144-e33f-40dd-a17b-cb8011ef36d2.png)
> 
> **Expected result:** The message is edited within 'pin banner' and list of pinned messages ![image](https://user-images.githubusercontent.com/52490791/209549423-083309c7-b1b4-4e30-a6bd-ae878b0820e7.png)

I fixed this and issue 1
Can't reproduce 2 and 3 .. Can you please retest ?

**Comment by VolodLytvynenko** [comment]
Hi, @ibrkhalil thanx for your work and sorry so the late reply. I can't reproduce 2 and 3 issues. They are not valid anymore

**Comment by ibrkhalil** [comment]
> Hi, @ibrkhalil thanx for your work and sorry so the late reply. I can't reproduce 2 and 3 issues. They are not valid anymore

Thanks Vlad! I added the request-manual-qa label for the other ones
