### ISSUE TITLE
Image URL not returned in last-message content of chat object

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#14625]
For content-type image, the `last-message` property of chat only has information about the content type but don't have the image and any of its metadata. We should return the URL of the image to preview the last message.

![shot](https://user-images.githubusercontent.com/17097240/209225490-875abd2e-bef4-4b18-bdfc-f37737324f87.png)

Not in the scope of the issue, but we also need to support returning URLs of all images sent in last-message for previewing all of them in switcher cards

![shot2](https://user-images.githubusercontent.com/17097240/209225530-79e415d9-93b5-495b-bbba-6995a7beea48.png)

**Comment by Parveshdhull** [comment]
Same is for stickers, url is nil
![image](https://user-images.githubusercontent.com/17097240/209227939-3460ab29-caa9-4767-938e-79779d2e763e.png)

**Comment by Parveshdhull** [comment]
In [HandleChatMessage](https://github.com/status-im/status-go/blob/ec7c0e9c7d34f73d89d8fb4be0e116aa29c3a29d/protocol/messenger_handler.go#L1496), [receivedMessage](https://github.com/status-im/status-go/blob/ec7c0e9c7d34f73d89d8fb4be0e116aa29c3a29d/protocol/messenger_handler.go#L1502) and [chat.LastMessage](https://github.com/status-im/status-go/blob/ec7c0e9c7d34f73d89d8fb4be0e116aa29c3a29d/protocol/messenger_handler.go#L1639) both had image url, but after [adding chat](https://github.com/status-im/status-go/blob/ec7c0e9c7d34f73d89d8fb4be0e116aa29c3a29d/protocol/messenger_handler.go#L1656) to response, image url disappears from chat's last message in client side.
Apart from `image` field, some other fields like `gapParameters` also was missing from chat.LastMessage in received response

**Comment by Parveshdhull** [comment]
@cammellos Please can you take a look. Thank you

**Comment by cammellos** [comment]
@Parveshdhull is this still relevant?

**Comment by Parveshdhull** [comment]
@cammellos yes last-message image is still nil, and we just show placeholder on shell cards.

**Comment by ilmotta** [comment]
@Parveshdhull, do you think we can close this issue for now given that the _Jump To_ feature has been disabled?
