### ISSUE TITLE
The cross button is cut off for images in the input field (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14620]
# Bug Report

## Problem 

<img width="646" alt="Screenshot 2022-12-22 at 13 29 28" src="https://user-images.githubusercontent.com/67952253/209134740-02660266-1fff-4d99-be2e-b5408929fb33.png">

### Reproduction

1. Open a chat
2. Select an image from the gallery
3. Confirm selection

### Additional Information

- Status version: nightly 22/12
- Operating System: Android

cc @ibrkhalil could you take a look at this issue as well when you have time, please? 
As far as I understood, you are the boss of the new input field :)

**Comment by ibrkhalil** [comment]
😂😂😂😂❤️
Okay, I am OOO now, Will take a look later today
