### ISSUE TITLE
'Group details' option is shown for removed user and become as disabled only in 3-5 minuts

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14624]
**Steps to reproduce:**
1. Create a 'group chat' -> invite any mutual contact
2. Remove current contact from the group
3. Long tap on created group chat as removed user

**Actual result:**
the group details are still visible for the removed user

https://user-images.githubusercontent.com/52490791/209199810-fd3fff62-eac8-4e52-a816-e32aefd65245.mp4

**Expected result:**
The 'group details' option is not shown for removed user

**Comment by churik** [comment]
@vkjr don't think it is worth to fix now, better is to take issues related to chat view / design notes for the next several weeks. We will prioritize them today, but group chat/audio are definitely out of scope for now.

**Comment by vkjr** [comment]
@churik, it is already implemented but sure, will take the next one from the prioritized list. Probably the milestones issues list should be updated accordingly.
