### ISSUE TITLE
Cellular data usage cannot be controlled

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14630]
# Bug Report

## Problem 
It is known and my assumption is that this is on the protocol level, but we should keep an eye on it as it is crucial for any mobile app.

On waku1 (1.20, eth.prod fleet) users can restrict mobile data usage via Profile > Sync settings > Mobile data.
On waku2 (nightly 23/12/22,  `status.prod` fleet) there is no option to reduce traffic usage, it is high nevertheless.

#### Actual behavior

**Case1:**
in 10 messages in the encrypted community app was consuming ~8 MB

https://user-images.githubusercontent.com/4557972/209341580-1009261b-66aa-4865-b764-348967b762c9.MP4

**Case2:**
280 MB of mobile data on empty account

#### Case1
**Prerequisites:** have 1 community, several contacts, several 1-1 chats

1) Open Status, switch to cellular data
2) Try to send 10 messages in the community and keep track of mobile data usage
#### Case2
**Prerequisites:** open brand new multiaccount (no chats)

1) Open Status, switch to cellular data
2) Keep it running for 30 mins

### Additional Information

- Status Version: nightly 23/12/22
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
closing for now, hopefully with waku-2 filter app usage will make it obsolete
