### ISSUE TITLE
Sometimes AC (activity center) filter bar is not scrolled to the last selected filter tab after AC reopening (IOS only)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14642]
**Steps:**

1. Open AC
2. Scroll through the filter tabs and select on of the last, for example "System" notifications
3. Reopen AC (several reopenings might be required for reproduction)
4. See if filter bar is scrolled to the selected "System" filter tab

**Actual result:** sometimes filter bar is not scrolled to the last selected filter tab after AC reopening. 

**Expected result:** filter bar is not scrolled to the last selected filter tab after AC reopening. 

https://user-images.githubusercontent.com/97245802/209559738-967f49ed-645c-45bc-a106-43778d843e70.mp4

### Additional Information

- Status version: nightly 
- Operating System: iOS

**Comment by ilmotta** [comment]
@pavloburykh, have you experienced this bug recently? Is it happening often enough that we should prioritize this for the next RC?

**Comment by cammellos** [comment]
closing until better triaged
