### ISSUE TITLE
fix: communities join screen - join button on overview page not hidden after making a join request

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14659]
# Bug Report

## Problem 
Navigate to community overview page (for both open and closed) communities. Open the bottom sheet to join that community

#### Expected behavior
clicking the join button will close the bottom sheet and return to the community overview page with the request button that opens the bottom sheet hidden

#### Actual behavior
clicking the join button will close the bottom sheet and return to the community overview page with the request button that opens the bottom sheet still showing

**Comment by J-Son89** [comment]
@pavloburykh - tagging you as you discovered this :)

**Comment by VolodLytvynenko** [comment]
**Note for the QA team:**
- Verify the toast is shown after user is joined to the community from the discover page https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=650%3A30484&t=6AGs9cuaa6Z1H4fi-0
![image](https://user-images.githubusercontent.com/52490791/211604253-79db5316-5faf-48ee-aced-bf60158357c5.png)

**Comment by VladimrLitvinenko** [comment]
hi @J-Son89. The Issue is fixed. Thank you for your work. No issues from my side. Could you merge this PR?
