### ISSUE TITLE
Pictures stop displaying in chat view after returning from the background until relogin (iOS)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14657]
# Bug Report

### Reproduction

1. UserA (iOS) and UserB have a chat open (1-1/community channel)
2. UserA: put the app in the background
3. UserB: wait ~3 minutes, and send a picture in the chat
4. UserA: open the app
5. UserA: send a picture

#### Expected behavior
UserA can see received and sent pictures

#### Actual behavior

<img width="394" alt="Screenshot 2022-12-28 at 16 29 00" src="https://user-images.githubusercontent.com/67952253/209835190-f837039f-3dae-44fc-8862-819981df8f45.png">

### Additional Information

- Status version: nightly 28/12
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qfrank** [comment]
Hi @qoqobolo , i didn't reproduce it after tried many times, is it a random case? i've used a physical device(iphone xs max) and an ios simulator (iphone 14 pro max) , i tried put both devices in the background for ~4 minutes at the same time but no luck to reproduce

**Comment by qoqobolo** [comment]
Hi @qfrank, thanks for checking this!
It was not a random case, it was reproducible constantly on several devices.
But now it indeed works fine. So closing the issue for now.
