### ISSUE TITLE
New message components

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14662]
An issue to track the creation of new message components (text, emoji, sticker, image)

**Comment by OmarBasem** [comment]
Does anyone know where is the designs for the new message components? I think we will be displaying the status of the message (sending, sent) but I can't find the designs for these 

cc @flexsurfer

**Comment by flexsurfer** [comment]
do you mean this one https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=611%3A22756&t=v03jGbwnImTWwdFJ-1 ?

**Comment by flexsurfer** [comment]
> I think we will be displaying the status of the message (sending, sent) but I can't find the designs for these

we have designs, but design team reworking them, so statuses not ready yet, we can't start implementing them yet

**Comment by OmarBasem** [comment]
New message components are being implemented in different issues. Closing this issue.
