### ISSUE TITLE
Active keyboard does not fold down after opening chat bottom sheets and overlapps them

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14664]
**Steps:**

1. Open any chat
2. Send a message
3. Make input field active in order to open keyboard
4. Longtap on message to open bottom sheet with message options (reproducible with other chat bottom sheets too, e.g. "pinned messages", images list pop up)
5. Observe the result

**Actual result:** 

Keyboard remains opened and overlaps message options bottom sheet

**Expected result:**

Keyboard folds down after opening message options bottom sheet

https://user-images.githubusercontent.com/97245802/209945284-63a6d31e-f326-4f19-84f5-e9b3796061c4.mp4

https://user-images.githubusercontent.com/97245802/209945301-eeb31475-391b-4aec-80fe-62c258669c6c.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
Fixed in https://github.com/status-im/status-mobile/pull/14911
