### ISSUE TITLE
Chat page is loaded correctly if opened from Contacts tab

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14666]
**Steps:**

Preconditions: User A and User B are mutual contacts. 1-1 chat between users has not been started yet. 

1. Open chat tab by User A
2. Tap on Contacts tab 
3. Find User B in the list 
4. Tap on User B element
5. Observe the result

**Actual result:** chat screen is opened but UI is not loaded (skeleton is displayed). Sending messages results in closing chat screen.

**Expected result:** chat screen is opened and loaded correctly. User has the ability to send/receive messages, observe chat history. 

https://user-images.githubusercontent.com/97245802/209957711-78d28a1d-3ea0-480c-9cb6-c93e95902717.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
duplicate of #14632?

**Comment by ibrkhalil** [comment]
Weirdly enough, They use different functions to start a new chat!

**Comment by pavloburykh** [comment]
oh. sorry for duplicate. I've forgotten that @churik already logged it. Closing this one.
