### ISSUE TITLE
Switcher buttons missing in chat view

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14668]
The switcher buttons are missing now

![Screenshot_2022-12-29-09-54-39-13_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/209977861-505d48cd-7d32-4454-85d7-eebe1b9057c5.jpg)

**Comment by qoqobolo** [comment]
Designs:
1-1 chat: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=332%3A78250&t=bdJR9zuV7v2na9hC-4
Community channel: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1558%3A118695&t=BJfJ2aZ5rDjYcfH8-4

@du64 thanks for reporting this!
