### ISSUE TITLE
The removing pop up is too much expanded during chats removing and clearing

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14677]
**Steps to reproduce:**
1. Create 1-1 chat or group chat
2. Long tap on the current chat
3. Select 'clear history' or 'delete chat' option

**Actual result:**
The pop up is too much expanded
![image](https://user-images.githubusercontent.com/52490791/210071080-d4120760-f692-41db-a604-af19b0ffc26a.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/52490791/210070909-df841f13-4e3d-4f2b-bf59-1fe3e62ffb9c.png)

**ENV:** nightly v.1.20.2 (20221230030828)

**Comment by ibrkhalil** [comment]
Kindly test if this is reproducible on this PR
https://github.com/status-im/status-mobile/pull/14680
