### ISSUE TITLE
Keyboard is not opened on reply or editing message in chats (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14673]
Reproducible on Android. 

**Steps:** 

1. Open any chat
2. Send a message
3. Longtap on message
4. Select Reply or Edit message
5. Observe the behaviour

**Actual result:** Keyboard stucks and not opened. In case with reply - input field is not visible

**Expected result:** Keyboard is opened. Input field is visible. 

https://user-images.githubusercontent.com/97245802/210067013-f4233e37-e15a-42bb-bc44-1e3a1b54ce2c.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
I think this is fixed here
https://github.com/status-im/status-mobile/pull/14680
