### ISSUE TITLE
List of contacts in New Chat modal is cut and not scrollable. It is not possible to create new chat

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14671]
Follow up of https://github.com/status-im/status-mobile/pull/14607

**Preconditions:** user has at least 1 contact

Steps:

1. Go to Chats tab
2. Tap on + button
3. Tap New chat
4. Try to select contacts from the list to create a chat

**Actual result:** 

List of contacts in New Chat modal is cut and not scrollable. Contacts checkbox stucks, it is hard to select/unselect contact in the list (need to tap several times). It is not possible to start 1-1/group chat as button for creating a chat is not visible.

**Expected result:** 

List of contacts in New Chat modal is visible and scrollable. It is possible to selects contacts and start 1-1/group chat. Link to [Figma](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=3720%3A548733&t=QidmDlQEBtSj0bFS-0)

https://user-images.githubusercontent.com/97245802/210061783-164a7ba8-1ada-40cd-8373-a6413880a525.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
This is caused due to the recently integrated bottom sheet .. will fix asap
