### ISSUE TITLE
Show selected community item in community home context actions

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#14675]
### User Story
When launching communities context action form communities home screen, the selected community item is shown as an extension of the bottom sheet above it as illustrated on the figma designs here https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=5933%3A282683&t=az9p0GbmNMZPQphP-1

**Comment by VolodLytvynenko** [comment]
hi @jo-mut @pedro-et  should be shown some empty placeholder statement if an image is not added within current sections of the community?
![image](https://user-images.githubusercontent.com/52490791/210810263-2a60fdd8-10b6-40b3-8060-24c8ed8b70ba.png)

**Comment by jo-mut** [comment]
@VladimrLitvinenko I agree. In cases where a community has been created and the user did not add an image there is an empty space. I think it would be nice to show a placeholder icon where the community thumbnail is missing

**Comment by VladimrLitvinenko** [comment]
Hi @jo-mut Thank you for fixes. It looks awesome. PR is tested and ready to be merged
