### ISSUE TITLE
App crashes if start deleting url while browsing [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1468]
### Description

*Type*: Bug

*Summary*: App crashes if browse some url and then start deleting it while browsed page is opened. Can reproduce only on iOS

#### Expected behavior
url can be edited, e.g. new url is enetered
#### Actual behavior
app crashes

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7TkczeDdjYXpWdnM
- Open Status
- Open Console
- tap on @browse command
- type some url, e.g. "bol.com" and send command
- wait till page is shown
- tap in the input field and delete part of url -> crash

### Logs
```
Application Specific Information:
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'c.contentSize.height')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'c.contentSi..., stack:
<unknown>@237:3952
_onChange@566:5969
l@358:59
a@357:389
c@357:584
v@355:503
i@360:95
processEventQueue@355:1412
s@369:88
handleTopLevel@369:143
<unknown>@368:576
perform@389:596
u@371:150
_receiveRootNodeIDEvent@368:548
receiveEvent@368:658
value@281:2722
<unknown>@281:838
<unknown>@281:106
value@281:810
'
```

[log6crash.log.txt](https://github.com/status-im/status-react/files/1155391/log6crash.log.txt)
[StatusIm-2017-07-18-113057.crash.txt](https://github.com/status-im/status-react/files/1155392/StatusIm-2017-07-18-113057.crash.txt)

### Additional Information
* Status version: develop  0.9.9d85
* Operating System: 
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/28311331-ff9a1030-6bb7-11e7-992f-565f9ca280fb.png)
