### ISSUE TITLE
Android app crashes on live reload

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14691]
Whenever changing anycode while debugging on Android, then the app tries to live reload I get the following error:
`java.lang.illegalStateException: java.lang.NullPonterException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMehodsHolder.isLayoutAnimationEnabled()' on a null object reference`

**Comment by OmarBasem** [comment]
Anybody knows why does this happen?

**Comment by Parveshdhull** [comment]
Hi, @OmarBasem, Is fast refresh disabled?
![image](https://user-images.githubusercontent.com/17097240/210306675-0109a455-7c52-4dcc-b545-26931cae1a7c.png)

**Comment by OmarBasem** [comment]
Hi @Parveshdhull, should I have it disabled or enabled?

**Comment by Parveshdhull** [comment]
disabled

**Comment by OmarBasem** [comment]
@Parveshdhull thanks!

**Comment by OmarBasem** [comment]
@Parveshdhull idk why, but the app still crashes, but without the error appearing

**Comment by Parveshdhull** [comment]
Is it crashing after every change/hot reload?

**Comment by Parveshdhull** [comment]
[Android Debug App crashes after reloading it few times](https://github.com/status-im/status-mobile/issues/14031)

[Allow disabling Hermes engine by passing flag while building app](https://github.com/status-im/status-mobile/pull/14041)

**Comment by Parveshdhull** [comment]
`make run-android DISABLE_HERMES=true`

**Comment by OmarBasem** [comment]
> `make run-android DISABLE_HERMES=true`

It crashes on emulator. On physical device seems to be working better. Will try that command.
