### ISSUE TITLE
Red icons in Activity Centre

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14706]
# Bug Report

## Problem 
The avatars are red in the activity center.
Was introduced on nightly 04/01/23

![IMAGE 2023-01-04 11:32:19](https://user-images.githubusercontent.com/4557972/210536178-f1fa8193-be0b-4d56-b94d-3bc4bfed9ffe.jpg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
If not relevant, can be closed :) thanks!

**Comment by Parveshdhull** [comment]
red color fixed in https://github.com/status-im/status-mobile/pull/14856, and original issue superseded by https://github.com/status-im/status-mobile/issues/14857
