### ISSUE TITLE
TextInput with children warning

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#14703]
```
[Wed Jan 04 2023 09:58:18.141]  ERROR    Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in RCTMultilineTextInputView (at TextInput.js:1077)
    in TouchableWithoutFeedback (at TextInput.js:1134)
    in InternalTextInput (at TextInput.js:1159)
    in ForwardRef(TextInput) (created by status_im.ui2.screens.chat.composer.input.text_input)
    in status_im.ui2.screens.chat.composer.input.text_input (created by f)
```

in `status-im.ui2.screens.chat.composer.input` 

`[rn/text-input props children]`

where `children` is a function, which is wrong? it should be text component, but if we implement it properly , mentions works wrong, so we need to fix this

**Comment by flexsurfer** [comment]
cc @ibrkhalil

**Comment by flexsurfer** [comment]
introduced in this PR https://github.com/status-im/status-mobile/pull/14442

**Comment by ibrkhalil** [comment]
I'll work on this when I have no more tickets left to work on for next release

**Comment by ulisesmac** [comment]
> I'll work on this when I have no more tickets left to work on for next release

Hey @flexsurfer  @ibrkhalil I wanted to take a look at this since it's a common issue.

It was easy to solve the main problem, but I had some other issues around to make the feature work (I'm only testing it on Android since it's also present). I'm going to create a PR with some comments so you can give your POV.

**Comment by OmarBasem** [comment]
I am currently working on a reimplementation of the composer and text input, so please avoid doing changes to the compoer for now: https://github.com/status-im/status-mobile/issues/15432

**Comment by cammellos** [comment]
closing as stale
