### ISSUE TITLE
Profile photo is not updated on receiver side

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14718]
# Bug Report

## Problem 
The profile photo is shown as an empty picture or placeholder to mutual contacts.

#### Expected behavior
The profile photo is updated

#### Actual behavior
<img width="775" alt="photo_2023-01-05 16 57 24 jpeg 2023-01-05 16-58-46" src="https://user-images.githubusercontent.com/4557972/210824622-df6baa4f-cc2f-4f78-b843-b0512f8273a4.png">

### Reproduction

1) User A and User B are added mutual contact 
2) User A: start chat with User B
3) User A: set profile photo
4) User B: check that profile photo is updated

### Additional Information

- Status version: nightly 05/01/23
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Apart from this issue, we also should improve the user avatar so it shouldn't use hard-coded identity ring

**Comment by J-Son89** [comment]
> Apart from this issue, we also should improve the user avatar so it shouldn't use hard-coded identity ring

@Parveshdhull could you make a separate issue for this with the issue described?

**Comment by Parveshdhull** [comment]
> > Apart from this issue, we also should improve the user avatar so it shouldn't use hard-coded identity ring
> 
> @Parveshdhull could you make a separate issue for this with the issue described?

@J-Son89 done https://github.com/status-im/status-mobile/issues/14861
