### ISSUE TITLE
Make (version 4.4-1) command is not creating a temp directory

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#14732]
# Problem

If I checkout a new branch and run `make run-clojure` then this error is thrown:

```
[status-mobile]-> make run-clojure                                                            
yarn shadow-cljs watch mobile                                                                 
Configuring Nix shell for target 'clojure'...                                                 
error: getting status of '/tmp/tmp-status-mobile-1cdcd298b': No such file or directory        
make: *** [Makefile:260: run-clojure] Error 1
```

Apparently `_tmpdir-mk` target is not being called. We have to call it manually `make _tmpdir-mk`

(Creating issue for context, if anyone else gets this error)

**Comment by Parveshdhull** [comment]
Oh, not only with new branch, but even with after any new commit. (because BUILD_TAG changes to new commit hash)

**Comment by Parveshdhull** [comment]
Make version: 4.4-1

**Comment by Parveshdhull** [comment]
@jakubgs Please can you take a look. Thank you

**Comment by Parveshdhull** [comment]
`-include` is not calling target automatically anymore

**Comment by jakubgs** [comment]
>`-include` is not calling target automatically anymore

Seems to work fine with `4.4`:
```
 > cat Makefile 
-include _default

test:
	@echo "TEST"

_default:
	@echo "DEFAULT"

 > $MAKE_4_3/bin/make test                                                              
DEFAULT
TEST

 > $MAKE_4_4/bin/make test
DEFAULT
TEST
```

**Comment by jakubgs** [comment]
What platform is this on? What if you add `-d` flag and grep for `_tmpdir-mk`, like so:
```
 > $MAKE_4_4/bin/make test -d | grep _default 
                              
Reading makefile '_default' (search path) (don't care) (no ~ expansion)...
 Considering target file '_default'.
  File '_default' does not exist.
  Finished prerequisites of target file '_default'.
 Must remake target '_default'.
Makefile:7: update target '_default' due to: target does not exist
Putting child 0x1474460 (_default) PID 75656 on the chain.
Live child 0x1474460 (_default) PID 75656 
 Successfully remade target file '_default'.
```

**Comment by Parveshdhull** [comment]
weird, make test worked. Only problem with status-mobile repo.

> What platform is this on? 

Arch linux (6.1.4-arch1-1)

**Comment by Parveshdhull** [comment]
> What if you add -d flag and grep for _tmpdir-mk, like so:

```
[status-mobile]-> make run-clojure -d | grep _tmpdir-mk
Reading makefile '_tmpdir-mk' (search path) (don't care) (no ~ expansion)...
Makefile '_tmpdir-mk' might loop; not remaking it.
Configuring Nix shell for target 'clojure'...
error: getting status of '/tmp/tmp-status-mobile-1cdcd298b': No such file or directory
make: *** [Makefile:260: run-clojure] Error 1
```

**Comment by jakubgs** [comment]
Interesting, I'm not getting this:
```
Makefile '_tmpdir-mk' might loop; not remaking it.
```
I get:
```
 > make xyz -d | grep _tmpdir-mk
Reading makefile '_tmpdir-mk' (search path) (don't care) (no ~ expansion)...
 Considering target file '_tmpdir-mk'.
  File '_tmpdir-mk' does not exist.
  Finished prerequisites of target file '_tmpdir-mk'.
 Must remake target '_tmpdir-mk'.
Putting child 0x1ae88f0 (_tmpdir-mk) PID 94162 on the chain.
Live child 0x1ae88f0 (_tmpdir-mk) PID 94162 
 Successfully remade target file '_tmpdir-mk'.
```

**Comment by jakubgs** [comment]
```c
                  if (f->deps == 0 && f->cmds != 0)
                    {
                      /* This makefile is a :: target with commands, but
                         no dependencies.  So, it will always be remade.
                         This might well cause an infinite loop, so don't
                         try to remake it.  (This will only happen if
                         your makefiles are written exceptionally
                         stupidly; but if you work for Athena, that's how
                         you write your makefiles.)  */

                      DB (DB_VERBOSE,
                          (_("Makefile '%s' might loop; not remaking it.\n"),
                           f->name));
```
https://github.com/LibreOffice/gnu-make-lo/blob/dc922e3f4c442255ba8deb84c9300aa7e3a6108c/main.c#L2077-L2089

**Comment by jakubgs** [comment]
I can't seem to be able to reproduce it. Seems like some kind of weird edge case.
Maybe we can have a call tomorrow to try to debug it.

**Comment by Parveshdhull** [comment]
yes sounds good. Thank you for looking into this.

**Comment by Parveshdhull** [comment]
Things are still little unclear, but these are findings:

### 1. Way to reproduce bug:
In target [_tmpdir-rm](https://github.com/status-im/status-mobile/blob/6f10ff4d3e03798f16181e852f37dcb13a1bd32f/Makefile#L127), replace shell using
```
_tmpdir-mk: SHELL := ./nix/scripts/shell.sh
_tmpdir-mk: ##@prepare Create a TMPDIR for temporary files
	@mkdir -p "$(TMPDIR)" && echo "$(BASH)"
```
and call `make _tmpdir-mk` to reproduce same output

### 2. Weird Fix
So in line [65](https://github.com/status-im/status-mobile/blob/6f10ff4d3e03798f16181e852f37dcb13a1bd32f/Makefile#L65), we are assigning default shell to `./nix/scripts/shell.sh`.

And as `run-clojure` target don't have any shell assigned to it, it uses above shell.
And somehow use of that also affecting `_tmpdir-mk` target and it also keeps using nix shell.
(even though we are assigning `/bin/bash` for that target).

(keeps using sounds weird, as `_tmpdir-mk` is supposed to run-first, but I tried to add debug log in nix shell script, and they always called even before `_tmpdir-mk` crashed)

If I assign `/bin/bash` also for `run-clojure` target using `run-clojure: SHELL := /bin/sh`, it fixes the issue or just removing line 65, also fixes the issue :)

### 3. Better fix
Looks like `-include` and `.PHONY` don't play nice together. Removing those targets from `.PHONY` fixes the issue.

**Comment by Parveshdhull** [comment]
`_install-hooks` target also included using `-include`. But for me commit message also not including status-go changes, even after adding this target to `.PHONY`

**Comment by Parveshdhull** [comment]
`prepare-commit-msg` is being called without any issue, so probably some other bug. (maybe you can check if commit message is including status-go changes for you)

**Comment by Parveshdhull** [comment]
> Looks like -include and .PHONY don't play nice together. Removing those targets from .PHONY fixes the issue.

- **Include** - The include directive tells make to suspend reading the current makefile and read one or more other makefiles before continuing. ([ref](https://www.gnu.org/software/make/manual/html_node/Include.html))

- **-include** - If you want make to simply ignore a makefile which does not exist or cannot be remade, with no error message, use the -include directive instead of include. ([ref](https://www.gnu.org/software/make/manual/html_node/Include.html))

 - **Phony** - A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request ([ref](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html))

 #### Thinking out loud
I don't know exactly why they are not playing well together, but include is saying read a file, and phony is telling it's not a file, which sounds contradictory :)

**Comment by jakubgs** [comment]
I think they way we use `-include` is hacky, but it's not uncommon. I don't see an issue with removing it from `.phony` but there might be a more kosher way to improve this. For example we could just use a real target with an alias:
```Makefile
$(TMPDIR): SHELL := /bin/sh
$(TMPDIR): ##@prepare Create a TMPDIR for temporary files
	@mkdir -p "$(TMPDIR)"
# Make sure TMPDIR exists every time make is called
_tmpdir-mk: $(TMPDIR)
-include _tmpdir-mk
```
This way we allow `make` to check if `TMPDIR` exists, and not run the command if it does.

**Comment by jakubgs** [comment]
Does that work for you?

**Comment by Parveshdhull** [comment]
yup tested, working perfectly.

**Comment by Parveshdhull** [comment]
(Removed, -include `_tmpdir-mk` for testing)

```
[status-mobile]-> make _tmpdir-mk
[status-mobile]-> make _tmpdir-mk
make: Nothing to be done for '_tmpdir-mk'.
```

**Comment by Parveshdhull** [comment]
earlier it was calling target each time

**Comment by Parveshdhull** [comment]
> Does that work for you?

oh did you meant with .PHONY. No, we still need to remove from .PHONY

**Comment by jakubgs** [comment]
That's really weird. This is what you get for using Arch I guess.

**Comment by jakubgs** [comment]
Interesting:
```
 > d run --rm -it -v $PWD:/test -w /test archlinux:base   
[root@677a5b859bca test]# pacman -Sy
[root@677a5b859bca test]# pacman -S core/make
[root@677a5b859bca test]# make test
TEST
```
```
 > d run --rm -it -v $PWD:/test -w /test alpine:latest 
/test # apk add make
/test # make --version
GNU Make 4.3
/test # make test
mkdir -p "/tmp/tmp-status-mobile-XYZ"
TEST
```
```
 > d run --rm -it -v $PWD:/test -w /test alpine:edge  
/test # apk add make
/test # make --version
GNU Make 4.4
/test # make test
TEST
```

**Comment by jakubgs** [comment]
Approved your PR, since this fix is mostly fine, but we are playing with weird hacks here: https://github.com/status-im/status-mobile/pull/14738#pullrequestreview-1242133464
