### ISSUE TITLE
Review and resolve weak NPM credentials.

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#1473]
> sophiii
> Hi @jarradhope , you should check https://github.com/ChALkeR/notes/blob/master/Gathering-weak-npm-credentials.md they managed to gain write access to numerous NPM packages. In `status-react` you include `react-native` and `react-dom` which uses the latest  version. Which means that a malicious attacker could potentially add malicious code that would be included in your dapp at deploy time

**Comment by jeluard** [comment]
Some more food for thoughts: https://iamakulov.com/notes/npm-malicious-packages/
