### ISSUE TITLE
Implement permission context

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14746]
This task is to track the implementation of the component **permission context**

### Designs

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?t=rrOoDnYGEnJIzEY8-0

**Comment by pavloburykh** [comment]
**small UPDATE:** 

I guess this is the correct Figma link for Permissions context component https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=2465%3A44216&t=H758tgluZDVjwGuf-0
