### ISSUE TITLE
Show number of unread replies in a community on the home screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14745]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user
I want to see the count of replies in a community on the home screen
So that I know if I got a reply to my message

#### Description

If there are any unread replies received in a community, we should show the count instead of the unread indicator only as we already do for mentions.

### Designs

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=4996%3A216944&t=ezih2GJzaMiMQqtK-4

**Comment by alwx** [comment]
Was just about to fix it by introducing the number of replies but found out that it was already fixed in this PR: https://github.com/status-im/status-go/pull/3035

Could you please verify and confirm? cc @qoqobolo

**Comment by qoqobolo** [comment]
Yes, it indeed already works on mobile.
@alwx thanks for pointing this out!

Closing the issue.
