### ISSUE TITLE
App crashes if change profile picture to photo and than request eth in group chat [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1475]
### Description

*Type*: Bug

*Summary*: App crashes if change profile picture to photo and than request eth in group chat. It should be a photo made by phone camera not a screenshot. After this app is useless because on the attempt to sign in it crashes again after entering a password and tap on sign in. Can reproduce on iOS only

#### Expected behavior
request is sent to group chat
#### Actual behavior
app crashes

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7S3NJU3NrWHU5QTQ
- Open Status
- Open profile and change profile picture to a photo made by this phone
- Add new contact
- create a group chat with this contact
- send in group chat eth request of 0.001 to this contact -> crash

### Logs
[log6crash.log.txt](https://github.com/status-im/status-react/files/1159360/log6crash.log.txt)
[StatusIm-2017-07-19-160712.crash.txt](https://github.com/status-im/status-react/files/1159362/StatusIm-2017-07-19-160712.crash.txt)
TestFairy: https://status-im.testfairy.com/projects/4803590-status/builds/6125315/sessions/74

```
Application Specific Information:
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: JSON Parse error: Unexpected identifier "content"', reason: 'Unhandled JS Exception: JSON Parse error: Unexpected identifier "content", stack:
<unknown>@196:2260
value@281:2963
<unknown>@281:1187
<unknown>@281:106
value@281:1157
'
```

### Additional Information
* Status version: develop 0.9.8-85-gcad5e0c5+
* Operating System: 
Real device iPhone 6s, iOS 10.2.1

**Comment by oskarth** [comment]
Unable to reproduce on Simulator due to https://github.com/status-im/status-react/issues/1502

**Comment by jeluard** [comment]
Cannot reproduce with latest develop.

**Comment by annadanchenko** [comment]
@oskarth can't reproduce on today's develop build. Will recheck on other device today and if it's not there - close it.

**Comment by annadanchenko** [comment]
can't reproduce on development build 231 (on iOS)
