### ISSUE TITLE
Communities issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14757]
introduced by https://github.com/status-im/status-mobile/pull/14735

**ISSUE 1: Communities are not able to be opened after user navigates to 'pending/opened' tabs**

**Steps to reproduce:**
1. Create a community
2. Go to the list of communities
3. Navigate to the 'opened' tap
4. Navigated back to the 'joined' tab
5. Tap on the newly created community

**Actual result:**
The community is not able to be opened
https://user-images.githubusercontent.com/52490791/211803719-aca31352-3b8d-40f9-a0fe-4f1a654303ee.mp4

**Expected result:** 
The community is able to be opened after tapping

**Build:** nightly: 11 Jan 2023 [2588]

**ISSUE 2. The community joining toast is not shown as per design**

**Actual result:**
The green mark on the left part of the toast is not shown as per the design
![image](https://user-images.githubusercontent.com/52490791/211801601-71a52d8b-0d36-4359-934f-5f74ae36daf7.png)

**Expected result:**
The green mark on the left part of the toast is shown as per the design
![image](https://user-images.githubusercontent.com/52490791/211802571-0acc50fb-a349-409e-840d-a051e306c689.png)

**Build:** nightly: 11 Jan 2023 [2588]

**Comment by VolodLytvynenko** [comment]
сс:  @alwx

**Comment by jo-mut** [comment]
@VladimrLitvinenko i am unable to reproduce this. I have tried on both develop and my other branches. Is it possible to add a screenshot video

**Comment by pavloburykh** [comment]
> @VladimrLitvinenko i am unable to reproduce this. I have tried on both develop and my other branches. Is it possible to add a screenshot video

Hey @jo-mut There is a link to video in Actual result section of issue 1 https://github.com/status-im/status-mobile/issues/14757#issue-1528891228

**Comment by pavloburykh** [comment]
@jo-mut update: issue 1 is not reproducible for me any more in latest nightly (Jan 12, 2023). @VladimrLitvinenko please confirm.

**Comment by jo-mut** [comment]
> > @VladimrLitvinenko i am unable to reproduce this. I have tried on both develop and my other branches. Is it possible to add a screenshot video
> 
> Hey @jo-mut There is a link to video in Actual result section of issue 1 [#14757 (comment)](https://github.com/status-im/status-mobile/issues/14757#issue-1528891228)

i missed that

**Comment by VolodLytvynenko** [comment]
Hi @jo-mut @pavloburykh current issue is not reproducible anymore. I think it was fixed after some last merges. Thanx!
