### ISSUE TITLE
Debugging is buggy 🐞

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14764]
Sometimes (a lot of times) when trying to run and debug on an ~Android~ (both iOS and Android) device I get the following error in metro which prevents live reloading of the app (fast refresh is disabled): `shadow-cljs - remote-error {"isTrusted": false, "message": "failed to connect to /192.168.2.1 (port 3449) from /192.168.0.103 (port 59866) after 10000ms"}`

Even after rerunning `make run-clojure` and `make run-metro` it still gives the same error. This makes testing and debugging the app very difficult.

This happens on both emulator and physical device.

**Comment by flexsurfer** [comment]
i noticed this as well when VPN is enabled

**Comment by flexsurfer** [comment]
Parvesh Monu — 07/29/2022 2:56 AM
ERROR    shadow-cljs - remote-error {"isTrusted": false, "message": "failed to connect to /192.168.100.2 (port 3449) from /192.168.0.10 (port 57996) after 10000ms"}

Looks like shadow-cljs and emulator are not able to communicate with each other, I faced somewhat similar issue in two cases
1. First I was using external device, and blocking connection using firewall
2. Some virtual NIC was interfering with connection.
In your case both IP addresses looks from different subnet, so most probably 2nd case. You can disable your virtual NIC, and that should fix this issue.
More Information: 
Adding for future reference,
if someone gets different ips in the metro while connecting, like above.
It means another NIC (Network interface card) is interfering.
Use ifconfig to see which NIC correspond to that ip, and use
ifconfig [NIC_NAME] down

**Comment by flexsurfer** [comment]
cc @Parveshdhull

**Comment by OmarBasem** [comment]
I tried this but still same issue :/

**Comment by OmarBasem** [comment]
probable fix: https://stackoverflow.com/questions/59416137/often-seeing-repl-command-timed-out-in-cider-with-shadow-cljs-and-react-native
