### ISSUE TITLE
Images Album (3)

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14773]
A third issue to track the creation of images functionalities.

Designs: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2827%3A270189&t=OA2AUu8KLlZZqDfw-0

Remainging tasks:

- Complete lightbox screen
- Lightbox screen action buttons

Dependency PR: https://github.com/status-im/status-mobile/pull/14755

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem fix it please in the scope of the current issue. This is from https://github.com/status-im/status-mobile/pull/14755
Thank you!

**ISSUE 1: The images are not shown after the app came back from the background and sleeping mode of the device**
1. Open 1-1 chat
2. Send images
3. Send the app into background mode
4. Send device into sleeping mode
5. WAIT AT LEAST 3-4 MINUTES
6. Go back to the app -> open the chat
7. Send images

**Actual result:**
Old and newly sent Images are not shown

https://user-images.githubusercontent.com/52490791/213688616-3c4d035e-df3b-4359-8d97-ab955fe2ed78.mp4


**Expected result:**
Images are still shown

**ENV:** iPhone 11 Pro max, v15
**Logs:** 
[Status.log](https://github.com/status-im/status-mobile/files/10465950/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/10465952/geth.log)

**Comment by pavloburykh** [comment]
@OmarBasem hey! Got one question: will longtap menu actions implemented is scope of this PR?

Cause currently, there are some issues with those actions. For example:

1. It is impossible to delete image - it remains undeleted after tapping Delete for me.
2. For some reason there is no option "Delete for everyone" for images, only "Delete for me". 
3. Pinning an image results in error. 
4. "Unknown" title is displayed in reply for images
5. "Copy text" option is displayed in long tap menu for images


https://user-images.githubusercontent.com/97245802/215774709-5476e13f-b7bc-4903-82ab-e9ae5b69033a.mp4

**Comment by OmarBasem** [comment]
Hi @pavloburykh. I have noted these issues. If not within the scope of this PR, then it will be in a following PR. Thank you!

**Comment by OmarBasem** [comment]
Completed in different issues, except for (Lightbox screen action buttons). I'll open a new issue for that. Closing this one.
