### ISSUE TITLE
Implement algorithm for tiling images for collectibles

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14775]
We need to implement the component below.

The scope of this task is to implement the behavior when displaying tiles (image only in the design).
You can use the test images taken from Figma from this, ultimately they will be passed to the component as a URL.

Tiles have all the same size.

Depending on how many images the component is passed, it should display them according to the design, for example:

1 Image: The image will occupy the whole tile
2 Images: The two images should share the space within the tile: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=2010%3A35736&t=QtTqoPpY029TXvwX-4

and so on

If there are 8 or more images, the design is https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=2010%3A31247&t=QtTqoPpY029TXvwX-4 . `+x` indicates how many images are not displayed within the collection.

Out of scope:
Text component (Doodle #...)
and interactions/animations

### Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=15671%3A187484&t=5oN55S16EhsyENzY-0

**Comment by ulisesmac** [comment]
I'll be working on it!

@cammellos All of these links are the same, is this correct? It'd be nice they point to the specific figma component they are referring to.

> You can use the test images taken from Figma from this, ultimately they will be passed to the component as a URL.

AFAIK, It's required to create a component preview screen, so I'll use those mentioned test images  while developing, but since the component will receive images as URLs, which URLs should I use to pass to the component for the preview screen? 

Thanks!

**Comment by cammellos** [comment]
Hey @ulisesmac! Thanks for picking up the issue.

I have updated the links, they should point to the right tile/component now, apologies :)

> so I'll use those mentioned test images while developing, but since the component will receive images as URLs,

We probably don't have to worry too much about this, the URL will be passed by the backend, we can use any test image really, as they are just square images, I'd say any NFT from https://opensea.io/ could do, what do you think? (otherwise we can upload the assets from Figma somewhere, if you'd prefer)

**Comment by ulisesmac** [comment]
> I have updated the links

Cool! Thanks!

> we can use any test image really, as they are just square images, I'd say any NFT from https://opensea.io/ could do, what do you think? 

@cammellos OK! now it's clear! I don't need you to upload any asset, I'll test it using squared images (probably from Opensea). Thanks again!

**Comment by gautomdas** [comment]
I just have two questions:
1. Should the solution be in clojure js?
2. Is the algorithm a function that takes in multiple URLs of images then produces the desired Figma designs?
