### ISSUE TITLE
React Native 0.71

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#14776]
```
info React Native v0.71.0 is now available (your project is running on v0.63.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.63.5.
info To upgrade, run "react-native upgrade".
```

![image](https://user-images.githubusercontent.com/11790366/212654827-b0719cbf-6c1f-478e-ab09-791077c2d972.png)

Plan

- [x] create and run a template project with 0.71
       Ruby version 2.7.6 https://github.com/facebook/react-native/blob/main/template/_ruby-version
- [x] run the same project with latest reagent and shadow-cljs
       "shadow-cljs": "^2.20.19"
        **issues with shadow-cljs and hermes engine, right after running the app it crashes with error `"Property Long doesn't exist"` , the temporary "fix" is `:output-feature-set :es5`** https://github.com/thheller/shadow-cljs/issues/1080
        "reagent" latest master
        **code reload doesn't work with reagent 1.1.1**
- [ ] add most important native libraries one by one
- - [x] "react-native-navigation": "^7.30.6" ios 
- - [x] "react-native-navigation": "^7.31.0" android
- [ ] replace ios and android projects in status-im repo

**Comment by Parveshdhull** [comment]
nice plan 👏

**Comment by flexsurfer** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/11790366/212326166-20b049bb-dc97-457c-84d9-c4dbe753d5ae.png">

**Comment by flexsurfer** [comment]
ios
<img height="400" alt="image" src="https://user-images.githubusercontent.com/11790366/212326581-df642364-c969-4fef-a8bf-bdd6baf69b9e.png">

**Comment by flexsurfer** [comment]
android
<img height="400" alt="image" src="https://user-images.githubusercontent.com/11790366/212328575-7aaf90dc-03a3-43e1-96bd-a38c805b0ba1.png">

**Comment by flexsurfer** [comment]
ok after spending 1h on the stupid error i can run the project with latest versions of shadow-cljs and reagent

<img height="400" alt="image" src="https://user-images.githubusercontent.com/11790366/212343568-a884f763-b149-49d5-8420-56f2b2e405da.png">

issues with shadow-cljs and hermes engine, right after running the app it crashes with error `"Property Long doesn't exist"` , the temporary "fix" is `:output-feature-set :es5`

reagent version which supports react 18.2 is not released yet, so i used old 1.1.1 and it works just fine, probably in React Native we don't need these changes and can continue using 1.1.1

**Comment by flexsurfer** [comment]
ok  code reload doesn't work with reagent 1.1.1, i tried latest master and it works fine

**Comment by flexsurfer** [comment]
react-native-navigation works fine on ios
<img height="400" alt="image" src="https://user-images.githubusercontent.com/11790366/212364096-de75b6d4-1ccf-4eba-b2f6-d50f373621aa.png">

**Comment by flexsurfer** [comment]
https://github.com/thheller/shadow-cljs/issues/1080

**Comment by flexsurfer** [comment]
```
> Task :react-native-navigation:compileReactNative68DebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
```

**Comment by flexsurfer** [comment]
https://github.com/wix/react-native-navigation/issues/7630

**Comment by flexsurfer** [comment]
just merged https://github.com/wix/react-native-navigation/pull/7669, so waiting next version

**Comment by flexsurfer** [comment]
7.31.0 available, works great

<img height="400" alt="image" src="https://user-images.githubusercontent.com/11790366/212670046-064cef6d-1338-4ecf-8e60-e21e1d8cd8c5.png">

**Comment by OmarBasem** [comment]
Good job! Btw there is a major bug in Android debug mode in v0.71.0, so I think we should be targeting 0.71.1+. See this issue: https://github.com/facebook/react-native/issues/35828

**Comment by flexsurfer** [comment]
https://github.com/facebook/react-native/releases/tag/v0.71.2 relesed

**Comment by flexsurfer** [comment]
http://clojars.org/reagent 1.2.0 is available
