### ISSUE TITLE
Can't scroll photo gallery on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14781]
# Bug Report

## Problem 

You can only scroll through the gallery with two fingers on the screen. 

https://user-images.githubusercontent.com/67952253/212388773-cf92191a-c7d4-496a-92dc-9affe3db8af1.mp4

### Reproduction

1. Open a chat on Android
2. Open a photo gallery
3. Try to scroll it

### Additional Information

- Status version: nightly 13/01
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by VolodLytvynenko** [comment]
Notes for QA:
- Recheck the ability to scroll when some images are selected and 'confirm' button should be always visible in this case
