### ISSUE TITLE
The user is not navigated back to opened chat after 'back'  device's button is tapped

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14788]
**ISSUE 1: The user is not navigated back to opened chat after 'back' device's button is tapped**

**Steps to reproduce:**
1. Go to the 1-1 chat
2. Open the image selector
3. Tap 'back' button on the device

**Actual result:**
https://user-images.githubusercontent.com/52490791/212550534-8ffa2422-48ca-4c74-8acc-de6877746406.mp4
The selector is not closed if the 'back' button is tapped

**Expected result:**
The selector is closed and the user is navigated to the opened chat

**Device:** Huawei p20 light, v9; iPhone 11 Pro, v12
**ENV:** 15 Jan 2023, [2595]

**ISSUE 2: [ANDROIDS ONLY] The shadow below the 'confirm selection' button should be shifted to the bottom part of the screen**
**Steps to reproduce:**
1. Open the image selector
2. Select any image

**Actual result:**
The uncovered part is shown below the screen
![image](https://user-images.githubusercontent.com/52490791/212552855-6ecf90c6-d545-423b-b99d-64225867b2e1.png)

**Expected result:**
The 'confirm selection' button and its shadow fully shown at the bottom
![image](https://user-images.githubusercontent.com/52490791/212551795-c5d25d84-0139-4fdb-926c-cf2a55f7319f.png)

**Device:** Huawei p20 light v9; Android studio, configured resolution 1080x2400 v12.
**ENV:** 15 Jan 2023, [2595]

**Comment by ibrkhalil** [comment]
Issue 2 is solved [here](https://github.com/status-im/status-mobile/pull/14791/files)
