### ISSUE TITLE
QR Code Reader Crash

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#148]
QR code reader sometimes crashes on back button

it is also possible to get to a blank state by pressing back and scan repeatedly.

**Comment by rasom** [comment]
@annadanchenko can this be reproduced?

**Comment by flexsurfer** [comment]
can reproduce this, you need to tap back button before camera will be active

**Comment by retro** [comment]
@jarradh Can you add me to the github team, so I can be assigned to this issue?

**Comment by retro** [comment]
@jarradh @flexsurfer On what devices were you able to reproduce this? I've tested this on:

- Huawei P9 Lite
- Lenovo Vibe P1m
- iPhone 6

and wasn't able to reproduce it. I've also tried to break it by switching to the Camera app while the QR reader was open (tried to reproduce https://github.com/lwansbrough/react-native-camera/issues/808) and it was working ok.

**Comment by flexsurfer** [comment]
@retro on android device, i think we can make a "blind" fix, activate back button only after camera will be initialized

**Comment by jeluard** [comment]
Fixed in develop
