### ISSUE TITLE
Sometimes contact requests are not delivered or delivered with delay to the receiver

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14807]
We supposed that bug has been fixed by https://github.com/status-im/status-mobile/pull/14779 but after additional testing it turned out that the problem still exists.
 **cc @cammellos** 

Bug is not reproducible every time. 

**Preconditions:** User A - CR receiver. Other Users B, C, D ... are CR senders

**Steps:**
1. Send CR to User A by Users B, C, D etc one by one. Keep sending CRs by different users until they stop being delivered to User A.
2. See if CRs are delivered to User A

**Actual result:** at some moment CRs stop being delivered to User A. 

**Expected result:** all CRs are delivered

https://user-images.githubusercontent.com/97245802/212893973-d5fdee66-64e6-42cd-850d-f8e3bdf72243.mp4

[cr_receiver.zip](https://github.com/status-im/status-mobile/files/10434812/cr_receiver.zip)
[cr_sender.zip](https://github.com/status-im/status-mobile/files/10434813/cr_sender.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
don't think that it makes sense to keep it open, closing, and new one should be opened if it will be the case again
