### ISSUE TITLE
The scrollable area of the community list is limited on iOS

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14829]
## Problem
The scrollable area of the community list is limited on iOS (see the video below).

**Steps to reproduce:**
1. Create a community
2. Try to scroll it 

**Actual result:**
The scrollable area of the community list is limited to a certain area

https://user-images.githubusercontent.com/67952253/213473006-a07b1c62-4ad4-4822-881c-61b4dab7fb29.MP4

**Expected result:**
Communities are hidden at the bottom of the screen

**ENV:**  IOS only, iPhone 11 pro max, v.15

**Comment by jo-mut** [comment]
closing this as it had been resolved in #14929
