### ISSUE TITLE
Communities - use real stats/data on Discover Screen and Overview screen 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#14836]
currently the cards on the communities cards on the discover page and the overview page are using mock data.

The live data should be pulled from the backend and used instead.

This should also be done for the Communities tags.

Design file
[in the](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=650%3A30484&t=ddqHzSJbh07auEsQ-0)

**Comment by ilmotta** [comment]
@J-Son89 @cammellos, do you know if Communities tags data are available to be consumed by clients or are we still blocked? What about the discover page data, do you know the progress on the backend or the person(s) working on it so that I could get an overview?

**Comment by J-Son89** [comment]
I believe that data is there and has actually been for sometime. It's just that the community has to be created on desktop (the only way now anyway)

I believe community overview page is using real tags ( should double check this) and discover I am not sure of but if overview page is working then it will be a quick patch on discover page.

**Comment by ilmotta** [comment]
Thanks @J-Son89. The tags are not displayed on the overview page using real data, so I'll create the issue(s). Probably the discover screen also is not showing real tags.

And what about the discover communities, do you know if we can fetch the data from status-go?

**Comment by cammellos** [comment]
@ilmotta @erikseppanen is working on this https://github.com/status-im/status-mobile/issues/16015 and https://github.com/status-im/status-mobile/pull/16232

**Comment by ilmotta** [comment]
@erikseppanen, once you get back, could you help us understand if this issue can be closed or what's left to do about it? Thanks!

**Comment by erikseppanen** [comment]
The tags are using real data from the `wakuext_curatedCommunities` endpoint, to my knowledge.

I think there are two places left to be updated with real data: 
- The stats, which should be available  from the `activeMembersCount` and `members` fields in the usual `wakuext_curatedCommunities` endpoint.
- The lock/token data, which is currently mocked here: https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/communities/discover/view.cljs#L16
  I think this data would be available from the `tokenPermissions` and `communityTokensMetadata` fields in the same `wakuext_curatedCommunities` endpoint.

**Comment by Parveshdhull** [comment]
@J-Son89 issue still relevant?

**Comment by ilmotta** [comment]
Looks like we can really close the issue @Parveshdhull

**Comment by Parveshdhull** [comment]
> Looks like we can really close the issue @Parveshdhull

Thank @ilmotta for confirming.
