### ISSUE TITLE
The overlays which are shown after chats long tap  are not matched to design

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14841]
**Steps to reproduce:**
1. Create: 
 - group chat;
 - community;
 - 1-1 chat.
2. Long tap on each created chat -> (check results)
3. Long tap on the group chat -> tap the 'group details' option -> tap '3 dots' in the right upper corner

**Actual result:**
1-1 chat 
![image](https://user-images.githubusercontent.com/52490791/213743476-4bf197dd-8083-4098-9827-1b521f70f4f3.png)

Group chat
![image](https://user-images.githubusercontent.com/52490791/213743523-8120c73e-1297-4017-a6ee-696b08083024.png)

Community chat
![image](https://user-images.githubusercontent.com/52490791/213744269-0e25c7af-7216-4e0b-b0b9-da6367b127b3.png)

Overlay which is shown after 3 dots are tapped in the right corner of detailed page of group
![image](https://user-images.githubusercontent.com/52490791/213745067-f3921211-0e3d-4dc8-a9c4-51c9b97ea114.png)

**Expected result:**
1-1 chat 
![image](https://user-images.githubusercontent.com/52490791/213745551-748fab2a-0b13-4782-9d42-d7327914f825.png)

Group chat
![image](https://user-images.githubusercontent.com/52490791/213745718-a6c4b9b8-22d6-4da2-90d6-9664c99f3d7d.png)

Community chat
![image](https://user-images.githubusercontent.com/52490791/213745459-269083fe-95d9-4192-9164-a5ac8e3d363a.png)

ENV: nightly [20 Jan 2023] (https://ci.infra.status.im/job/status-mobile/job/nightly/2600/)

**Comment by churik** [comment]
Regression from 20/01/2023 (there is no issue on nightly 19/01/2023), issue from one of [ these commits](https://ci.infra.status.im/job/status-mobile/job/nightly/2600/changes) along with #14843

**Comment by ibrkhalil** [comment]
Sorry I didn't notice this ticket before creating [14847](https://github.com/status-im/status-mobile/issues/14847)
I fixed it [here](https://github.com/status-im/status-mobile/pull/14848)
