### ISSUE TITLE
Sometimes on Android group images of 3 is not done properly

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14840]
See this comment: https://github.com/status-im/status-mobile/pull/14755#issuecomment-1398273290

**Comment by churik** [comment]
For reference:

https://user-images.githubusercontent.com/52490791/213688047-56bfdaa0-b1ba-42ff-bf3e-6f8c963e2a9c.mp4


@VolodLytvynenko please, recheck it when you got a minute, it is getting stale, not sure if we want to keep it open

**Comment by VolodLytvynenko** [comment]
@churik can't reproduce anymore
