### ISSUE TITLE
Improve re-frame.cljs merge function

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#14858]
### Summary

Currently, if [re-frame.cljs](https://github.com/status-im/status-mobile/blob/develop/src/utils/re_frame.cljs), [merge function](https://github.com/status-im/status-mobile/blob/d3667ad68319170ad9b39228091a0383e919d7c3/src/utils/re_frame.cljs#L58) merges two effects which both have `:dispatch` keys, then it will through an error `:merging-fx-with-common-keys`.

We should improve the function so that it converts multiple dispatch into `dispatch-n`.

cc: @ilmotta,  @erikseppanen wdyt?

**Comment by flexsurfer** [comment]
in general we shouldn't use dispatch or dispatch-n, but sometimes it happens, and super rare cases when we have two dispatches in merge, but, it definitely might be useful for such cases

**Comment by ilmotta** [comment]
Makes sense to me @Parveshdhull, though I'd share a couple things:

 `dispatch-n` is officially deprecated.

>From v1.1.0 onwards, this effect is deprecated in favour of using :fx with multiple :dispatch tuples.
>
>-- https://day8.github.io/re-frame/api-builtin-effects/#dispatch-n

Unfortunately, as far as I tested, `:fx` doesn't play well with the `rf/defn` + `rf/merge` pattern. The docs go a bit deeper here:

>In fact, with v1.1.0 best practice changed to event handlers should only return two effects :db and :fx, in which case :db was always done first and then :fx, and within :fx the ordering is sequential.
>
>-- https://github.com/day8/re-frame/blob/master/docs/Effects.md#order-of-effects

From my perspective, the whole pattern of treating events as functions is just complecting the code with no real benefit. `rf/defn` and `rf/merge` could be completely removed with no downside. There's a strong case to be made about removing this pattern, but I won't go into details here. But I digress, this is what we have and it's okayish ;)

**Comment by J-Son89** [comment]
@Parveshdhull as a result of - https://github.com/status-im/status-mobile/pull/17451
perhaps we should close this issue?
