### ISSUE TITLE
App crashes when chatting with newly added chat right after the Console chat was removed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1486]
### Description

*Type*: Bug

*Summary*: On the Chats screen when I have more than 10 (?) chats avaliable (including Console chat) I can remove the Console chat -> receive newly added chat with random name. When I send a message to this newly created chat the app crashes. Pay attention the Console chat is still in place after re-laucnhing the app.

#### Expected behavior
No new chats should be added when I remove the Console chat

#### Actual behavior
App crashes When I send a message to newly created chat after I remove Console chat

### Reproduction

Precondition: more than 10 chats avaliable

- Open Status
- Go to Chats
- Remove Console chat
- Pay attention new chat is added at the bottom of the chat list
- Send a message to this chat

### Additional Information

* Status version: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-cad5e0.apk
https://i.diawi.com/Ai3Wum

* Operating System: Android, iOS

#### Logs

TestFairy session: https://app.testfairy.com/projects/4803590-status/builds/6125315/sessions/117
```

Application Specific Information:
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (near '...t$kw$chat_DASH_id,e)[cljs.core.name(c)]=...')', reason: 'Unhandled JS Exception: undefined is not an object (near '...t$kw$chat_DASH..., stack:
<unknown>@205:356
write@194:21653
save_property@205:108
save_property@205:2930
reset_message_overhead@205:4053
<unknown>@217:26695
<unknown>@172:6336
<unknown>@131:7212
invoke_interceptor_fn@129:6781
invoke_interceptors@129:7089
execute@129:8831
handle@129:19888
re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@130:15416
re_frame$router$IEventQueue$_run_queue$arity$1@129:30549
<unknown>@130:1736
re_frame$router$IEventQueue$_fsm_trigger$arity$3@130:6107
<unknown>@129:31850
callTimer@283:601
callImmediatesPass@283:1725
callImmediates@283:1841
<unknown>@281:106
value@281:2287
<unknown>@281:864
<unknown>@281:106
value@281:810
'

```

**Comment by annadanchenko** [comment]
Can reproduce also on real Android device: 
* Status version: develop 0.9.8-85-gcad5e0c5+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7UnlmVm50YmlEdWs
Log: 
[log84.log.txt](https://github.com/status-im/status-react/files/1165465/log84.log.txt)

**Comment by rasom** [comment]
Console chat shouldn't be removable

**Comment by annadanchenko** [comment]
checked on iOS and Android that

1. Console chat is not removable (no option to delete chat is shown)
2. Other chats can be removed
3. no removed chats are shown after app re-launch

builds
Android: http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-8372c9.apk
iOS: https://i.diawi.com/NhjjHr
