### ISSUE TITLE
Not able to open contact profile from contacts

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#14864]
# Bug Report

https://user-images.githubusercontent.com/17097240/214129112-e943d984-70d1-44c9-98b5-44ba69543503.mp4

@flexsurfer Please can you take a look (related to https://github.com/status-im/status-mobile/pull/14835)

**Comment by cammellos** [comment]
@flexsurfer this is known and already fixed in a different PR https://github.com/status-im/status-mobile/pull/14845 , the fix is simple (we stopped dispatching the open-modal event), but I had to change a bit the code to support compressed keys.
