### ISSUE TITLE
Add "Media types" albums and "Favorite" album to Albums screen

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14870]
That PR https://github.com/status-im/status-mobile/pull/14867 implements albums screen, but some album types (https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=6376%3A372320&t=lbjLScLVrGhRdyLZ-0) like favorite album is not implemented yet as the camera-roll library we are using does not support fetching smart albums. This requires native code implementation.

**Comment by VolodLytvynenko** [comment]
@OmarBasem  fix it please in the scope of the current task
**ISSUE 1: Albums are without access id on the album selection screen**
![image](https://user-images.githubusercontent.com/52490791/216688396-0754a25f-e3a7-4657-b221-e8d4d58316a2.png)
