### ISSUE TITLE
App crashes on chat reopening after deleting of a pinned or quoted message

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14871]
Reproducible in any chat or community channel

**Steps:**

Pinned message:
1. Start any chat
2. Send a message
3. Pin message
4. Delete the message `for everyone`
5. Re-open the chat
6. Observe the result

Reply:
1. Send a message
2. Reply to this message
3. Delete the first message `for everyone`
5. Tap back and re-open the chat

**Actual result:** app crashes

**Expected result:** no crash

[crash_after_pinned_deleted.zip](https://github.com/status-im/status-mobile/files/10490317/crash_after_pinned_deleted.zip)

Pinned message:

https://user-images.githubusercontent.com/97245802/214304577-54d90efa-1863-401f-a472-c8f3d201dc2c.mp4

Reply:

https://user-images.githubusercontent.com/67952253/214552213-e460546e-ed44-415a-b030-72d14d69078e.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
@qoqobolo can we close it ?

**Comment by qoqobolo** [comment]
Yeap
