### ISSUE TITLE
'Jump to' button is not fully shown if image is added into textbook

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14876]
**Steps to reproduce:**
1. Go to 1-1 chat
2. Open the image selector
3. Select at least 1 image -> tap the [confirm] button 

**Actual result:**
The 'jump to' is not shown fully
![image](https://user-images.githubusercontent.com/52490791/214370101-f8ea6bef-1189-49f9-827d-86e56671ba66.png)

**Expected result:**
The 'jump to' is fully shown

**Device:** iPhone 11 Pro max, version 15.5; Huawei p20 light, version 9

**ENV:** Nightly 24 Jan 2023 [2604]

**Comment by flexsurfer** [comment]
i believe its by design, but the problem is that there is no text field, in that case it will be fully hidden

**Comment by flexsurfer** [comment]
cc @Parveshdhull
