### ISSUE TITLE
Input field is hidden in composer when editing/replying messages

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14881]
# Bug Report

### Reproduction

1. Send a message
2. Long tap > `Edit` or `reply`

#### Expected behavior
The textbox is visible

#### Actual behavior
The textbox is hidden

https://user-images.githubusercontent.com/97245802/214374070-8d708fff-b8e6-4843-a2c4-87e49cf42086.mp4

### Additional Information

- Status version: since nightly 24/01
- Operating System: Android (Huawei P40 Lite, Pixel 2, Samsung Galaxy A52), iOS (iPhone SE)

**Comment by qoqobolo** [comment]
cc @flexsurfer

**Comment by OmarBasem** [comment]
I noticed that it also becomes hidden after adding an image. Could be from this commit: https://github.com/status-im/status-mobile/commit/685c95591cbc8356942f3e0459c9b2d7065cb53e

**Comment by qoqobolo** [comment]
@OmarBasem yes, we have an issue for this https://github.com/status-im/status-mobile/issues/14877
