### ISSUE TITLE
Pressing a contact does nothing

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14886]
Pressing a contact from the contacts list on messages home does nothing.
Also pressing "Chat" on a user's profile page does nothing.

**Comment by qoqobolo** [comment]
Hey @OmarBasem , isn't it a duplicate of https://github.com/status-im/status-mobile/issues/14843 ?
Looks related.

**Comment by OmarBasem** [comment]
Could be related, but I think it is different. Pressing a contact or "Chat" button should open the chat. Pressing "view profile" should open the profile.

**Comment by erikseppanen** [comment]
They are similar in that they both currently rely on the `:chat.ui/show-profile` event: [source](https://github.com/status-im/status-mobile/blob/develop/src/status_im2/common/contact_list_item/view.cljs#L16)

#14845 will probably fix both.

**Comment by cammellos** [comment]
@churik this one should be fixed in develop, could you please confirm?
Thank you

**Comment by churik** [comment]
closed in favor of #14939
