### ISSUE TITLE
Can tap several times on Save button that causes multiple group chats been created with same name 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1488]
### Description

*Type*: Bug

*Summary*: When I create a group chat, it's possible to tap several times on Save button,  as a result several group chats with same name are listed in Chats.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Chats
- Create new group chat
- Tap several times on Save button

### Additional Information

* Status version: released 0.9.9 and develop 0.9.9d89
* Operating System: iOS. Can't reproduce on Android

![2](https://user-images.githubusercontent.com/28752642/28465862-f5c6bcfc-6e32-11e7-8bf3-789ccb3436d8.jpg)

![3](https://user-images.githubusercontent.com/28752642/28465882-0a799188-6e33-11e7-8593-44f0a35bea9a.jpg)

**Comment by annadanchenko** [comment]
@asemiankevich it looks like the cause of the issue is possibility to tap several times on Save button that results in multiple identical group chats being created. I've changed steps and bug title to reflect it

**Comment by asemiankevich** [comment]
I can reproduce it in 0.9.9d98 build

**Comment by annadanchenko** [comment]
same here, can reproduce in  0.9.9d98 develop build

**Comment by asemiankevich** [comment]
i can't reproduce it, 0.9.9d108
