### ISSUE TITLE
No unread indicator on community channels 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14906]
# Bug Report

## Problem 
Regression from https://github.com/status-im/status-mobile/pull/14799
No unread indicator is shown on channels inside community

#### Expected behavior
unread indicator is shown

#### Actual behavior

https://user-images.githubusercontent.com/4557972/214795870-527c24ea-a214-4d7f-9f8f-8a3f41af38f1.mp4

### Reproduction
**Prerequisites:** `User A` and `User B` are members of the same community 
1) User A: sends a message to the community channel while User B is on the messages home screen
2) User B: check unread indicator in community page

### Additional Information

- Status version: nightly 26/01/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cc @vkjr

**Comment by vkjr** [comment]
@churik, well, I believe this is not technically a regression, but absence of a feature) 

Before #14799 we were using old-ui community page, it had an unread indicator working. And new ui community page was accessible only from "Discover" section and it didn't contain real channels, only mocks.

After #14799 mock channels were removed from the new community ui and real channels added. And that new ui page now opens from community home. But it actually never contained unread indicator. In the same time if you'll go to the old community ui, you'll probably will find that unread indicator.

**Comment by churik** [comment]
yes, agree that it may never exist on this screen before, but the screen was not used. Currently, it is essential to have this indicator on the community page
