### ISSUE TITLE
All photos are cropped to a square on the receiver's side

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14919]
# Bug Report

### Reproduction

1. UserA: send a photo in portrait orientation to the chat with UserB
2. UserB: check preview, open the photo 

#### Expected behavior
The photo is not cropped

#### Actual behavior
The photo is cropped both in the preview and when opened

Sender:

https://user-images.githubusercontent.com/67952253/214889023-d7602e0e-8865-4881-bbbc-9df38498eb69.mp4

Receiver:

https://user-images.githubusercontent.com/67952253/214889104-10f891f7-092a-49a1-862a-b7cde58b8577.MP4

### Additional Information

- Status version: nightly 26/01
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
That's from status-go. There is a PR that will be merged soon.

**Comment by alwx** [comment]
What's this PR? Is there still something to do here?

**Comment by qoqobolo** [comment]
Fixed in https://github.com/status-im/status-go/pull/3121
