### ISSUE TITLE
Discover communities screen is not scrollable

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14921]
In the discover communities screen, there is a list of communities under the featured section. That list scrolls in its place, but the screen doesn't scroll. I think the screen should be scrollable.

**Comment by OmarBasem** [comment]
CC @jo-mut, I think you are working on this?

**Comment by jo-mut** [comment]
@OmarBasem  there is a similar issue #14104 and is being address in #14825. The scroll page component has been updated so am working on the updates

**Comment by jo-mut** [comment]
closing this as its resolved in this PR #14825
