### ISSUE TITLE
Building app in release mode fails

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14926]
After installing release mode app on simulator, it just crashes when trying to start the app.

Trying to build release mode app on physical device in Xcode fails with error: "Command PhaseScriptExecution failed with a nonzero exit code"

I am currently facing a bug that is happening only in release mode (PR build) which I am trying to debug.

**Comment by siddarthkay** [comment]
@OmarBasem : I am assuming the bug you are facing only happens in IOS?
Can you also paste the full stack trace here that you see in Xcode?

**Comment by OmarBasem** [comment]
@siddarthkay yes the bug is in ios. Did not try in Android. I will try to get the stack trace and post it.

**Comment by cammellos** [comment]
closing until more activity
