### ISSUE TITLE
Cannot send messages to contact

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14922]
I'm already contacts with Sebastian, but I cannot message anymore on nightlies.

![Screenshot_2023-01-27-10-58-57-87_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/215148041-aae45434-51ce-4885-a5ff-890c1309c59f.jpg)

**Comment by du82** [comment]
@Parveshdhull

**Comment by Parveshdhull** [comment]
Hi @du64, Please can you confirm if Sebastian accepted your contact request?

**Comment by du82** [comment]
> Hi @du64, Please can you confirm if Sebastian accepted your contact request?

He did not see it, nothing happens when I click the button

**Comment by cammellos** [comment]
> > Hi @du64, Please can you confirm if Sebastian accepted your contact request?
> 
> He did not see it, nothing happens when I click the button

Thanks @du64 for reporting the issue.

this is due to the fact that you can't open profile, it's tracked elsewhere (a contact request is not being sent by clicking there, it would take you to profile, where you can add the user to contacts)
