### ISSUE TITLE
Tapping on "Chat" from user profile does not open chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14939]
# Bug Report

## Problem 
When User A and User B are mutual contacts, the button "New chat" on the other user's profile does nothing.

![IMAGE 2023-01-31 10:53:38](https://user-images.githubusercontent.com/4557972/215727200-5018735c-8979-48fe-af02-da811c886f6d.jpg)

#### Expected behavior
Chat is opened 

#### Actual behavior
nothing happens

### Reproduction

1) User A: send CR
2) User B: accept CR
3) User A: open profile of User B
4) User A: open profile of User B, tap on "Chat"

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@churik @alwx I believe I have fixed it here https://github.com/status-im/status-mobile/pull/14878

**Comment by churik** [comment]
thank you Andrea, will check!

**Comment by cammellos** [comment]
@churik @pavloburykh this should be fixed in develop, could you please check?

**Comment by pavloburykh** [comment]
> @churik @pavloburykh this should be fixed in develop, could you please check?

this one is fixed by https://github.com/status-im/status-mobile/pull/14878. Forgot to close this issue. Closing now) Thanx @cammellos!
