### ISSUE TITLE
Implement Emoji Hash using new emojis

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#14940]
### This is how desktop does it :

- They pass the accounts public key to status-go and status go returns a hash : https://github.com/status-im/status-go/blob/2c38b9e673dac2a795d9885b709ec424504120dd/mobile/status.go#L729
- They then map the unicode character to the icon StatusQUtils.Emoji.iconId(modelData) (modelData is one unicode character) to render emojis consistently across platforms 
ref : https://github.com/status-im/status-desktop/blob/dfcba80df2d0e17bd069d994aeceffdd70c4e639/ui/imports/shared/controls/EmojiHash.qml#L33
- they then render SVG of emoji using their DTO ID : ref 1 : https://github.com/status-im/status-desktop/blob/5df7416fd98dceed9a006939e811aa7d30914b87/ui/StatusQ/src/StatusQ/Components/StatusEmoji.qml

the current implementation will have system emojis, We would also like to be able to show the emoji hash using new emojis

tweemoji library assets(png) url :  https://github.com/twitter/twemoji/tree/master/assets/72x72

**Comment by cammellos** [comment]
post mvp
