### ISSUE TITLE
Unneeded CR notification appears for User A, after User B (who initially declined User's A CR) sends CR to User A

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14946]
**Steps:**

1. User B send CR to User A
2. User A declines User's B CR
3. User A sends CR to User B

**Actual result:** Users A and B become mutual contacts, but unwanted CR notification appears for User A. In case if User B declines User's A CR: User A will be removed from User's B contact list, but User B will remain as a contact for User A. 

**Expected result:** we don't need to show CR notification for User A, as in this case Users already become mutual contacts and there is not need to accept it by User A. 

https://user-images.githubusercontent.com/97245802/215875031-3f6bc600-b183-421d-b95f-cb5bcb30abba.mp4

[USER_A.zip](https://github.com/status-im/status-mobile/files/10549440/USER_A.zip)
[USER_B.zip](https://github.com/status-im/status-mobile/files/10549441/USER_B.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Might also be different in this PR https://github.com/status-im/status-mobile/pull/14853 but I will check (and fix) it all tomorrow.

**Comment by cammellos** [comment]
@alwx I am fixing a related issue, I can fix it as part of it as I already have the fix

**Comment by alwx** [comment]
Please, do if you can. I am checking another bug in the meantime.
