### ISSUE TITLE
Photo Selector animated blurry buttons

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14950]
The top buttons in the photo selector should animate to blurry buttons as the user scrolls down.

Designs: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=6376%3A372350&t=yzVElE13JXJEcStX-0

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem fix it please in scope of the current task

**ISSUE 1: The [x] button has a different style than the clear and recent buttons on the image selector screen**

**Steps to reproduce:**
1. Go to the profile page -> Appearance -> Switch on the dark mode
2. Go to chat
3. Open image selector

**Actual result:**
The [x] button is not with the same style as 'clear' and 'recent' buttons
![image](https://user-images.githubusercontent.com/52490791/216686328-fdb92175-04a4-4142-b6ec-2905a07ba3de.png)

**Expected result:**
The [x] button is with the same style as 'clear' and 'recent' buttons

**ISSUE 2: Add access id to the [x] button**
![image](https://user-images.githubusercontent.com/52490791/216687743-2abf747f-b311-4d8a-8dac-a751e88b01a2.png)

**Comment by OmarBasem** [comment]
Duplicate
