### ISSUE TITLE
The [Cancel] and [Join] buttons are hidden  within 'Join Community' overlay

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14955]
# Bug Report

## Problem 
The [Cancel] and [Join] buttons are out of the screen for some devices on the 'Join Community' overlay

**Preconditions:**
User didn't join to the status community yet

**Steps to reproduce:**
1. Go to the communities page
2. Tap 'Opened' tab
3. Tap Status
4. Tap [Join Community] button
5. Check opened 'Join Community' overlay

#### Actual behavior
[Cancel] and [Join] buttons  are hidden
![image](https://user-images.githubusercontent.com/52490791/216070723-ee95f721-0ac5-4a56-b69a-571ef623d636.png)

#### Expected behavior
[Cancel] and [Join] buttons  are shown
![image](https://user-images.githubusercontent.com/52490791/216071027-4c1334cf-0850-4119-b08e-f236db959763.png)

### Additional Information
- Status version: nightly 1 Feb 2023 [2612]
- Operating System: Android version 9, Huawei P20 light

**Comment by alwx** [comment]
Working on it.

**Comment by J-Son89** [comment]
The real issue here is that the component is using the old bottom sheet and needs to be updated to the new bottom sheet. If we fix this in the current implementation we will have to fix it twice 🙃

**Comment by flexsurfer** [comment]
it seems like we shouldn't fix this "bug" but we should properly implement the screen instead https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=1381%3A109764&t=gi6NEOkI8k40nH9d-1
in designs it looks different and it has different states of scrolling

**Comment by flexsurfer** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/11790366/217195854-f23ac5dc-0ca3-415b-9105-290e829f3fe8.png">

**Comment by flexsurfer** [comment]
i think we shouldn't use bottom sheet for such screens, some special screen should be implemented cc @alwx @J-Son89 @Parveshdhull

**Comment by J-Son89** [comment]
Yes I agree @flexsurfer. I raised this concern as well. If this screen is not a bottom sheet we should check with the design team as I believe there are some similar screens across the application and perhaps this screen/pop up container should be a component that's reusable too.

**Comment by Parveshdhull** [comment]
> i think we shouldn't use bottom sheet for such screens, some special screen should be implemented cc @alwx @J-Son89 @Parveshdhull

yes, sounds good. We can create something like (thinking out loud)

```
<Parent View with full screen width and height and dark overlay background>
    <Transparent Scroll view (full screen) nesting white background content view with top margin>
    <Buttons container with absolute positioning with bottom 0>
```

We can show this as an overlay or just a quo2 component (accepting actions, and content) and load/unload with help of reagent/atom with animations

**Comment by J-Son89** [comment]
In this case can we create a separate issue for this, and can we also sync up with the design team before creating/implementing this component so that we get it right because I am pretty confident I have seen similar designs across the app.

@flexsurfer, what features/properties make you think this will not work as a bottom sheet btw? 🤔

**Comment by J-Son89** [comment]
also, I just found this component in the figma designs. Seems like it's needed here:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2638%3A35963

<img width="300" alt="Screenshot 2023-02-07 at 10 29 06" src="https://user-images.githubusercontent.com/22799766/217220027-8a3ab57b-cf7e-41ad-9000-55f70c4691e0.png">
&t=29WaMjPTYMtHqa1n-0

I'll make an issue to track this as it's mostly implemented on this screen but just needs to be moved to quo2 and abstracted out 👍

**Comment by Parveshdhull** [comment]
> what features/properties make you think this will not work as a bottom sheet btw?

- Action buttons are not scrolling with content
- Content smooth scroll with drag, instead of expand and collapse like bottom sheet

**Comment by J-Son89** [comment]
ah okay, I understand. Thanks for clearing it up @Parveshdhull !

**Comment by J-Son89** [comment]
btw there was already this issue here to implement this screen properly:
https://github.com/status-im/status-mobile/issues/14564

Let's either re-use it or we can close it if we have a duplicate 👍

**Comment by J-Son89** [comment]
> also, I just found this component in the figma designs. Seems like it's needed here: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2638%3A35963
> 
> <img alt="Screenshot 2023-02-07 at 10 29 06" width="300" src="https://user-images.githubusercontent.com/22799766/217220027-8a3ab57b-cf7e-41ad-9000-55f70c4691e0.png">
> 
> &t=29WaMjPTYMtHqa1n-0
> I'll make an issue to track this as it's mostly implemented on this screen but just needs to be moved to quo2 and abstracted out 👍

https://github.com/status-im/status-mobile/issues/15006

**Comment by alwx** [comment]
What should I do with this issue in that case if there should be a separate component implemented?

**Comment by alwx** [comment]
I can take it and implement it btw, just asking what I should do with this particular one and the PR for it.

**Comment by flexsurfer** [comment]
we could keep this issue and close with new implementation, cc @J-Son89
