### ISSUE TITLE
Mobile users are not displayed as members of open community after join

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14956]
## Problem 

Only mobile admin and desktop users are displayed as members of open type community. 

Preconditions: User A and User B are mobile users, User C - desktop user
### Reproduction

1. User C (desktop): creates a community with the `No requirement` type, invites UserA and UserB
2. User A and B: join the community
3. User A or User B: tap Communities tab => longtap on community => View members
4. See if User B/A is displayed as member of community

#### Expected behavior

User B/A is displayed as member of community 

#### Actual behavior

Only admin User C is displayed as member of open community

https://user-images.githubusercontent.com/97245802/223413714-ee5c0732-c3fc-46f8-a6e8-f2dbf5c11262.mp4

### Additional Information

- Status version: nightly 1/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
hmm, do we have some design confirmation that we actually want this behaviour? @pedro-et @John-44

**Comment by qoqobolo** [comment]
Related minor issue:

1. UserA: create a community with the `No requirement type`, invite UserB
2. UserB: join the community
3. UserB: mention UserA (it is possible to mention the admin in this case) > send the mention > edit the message


https://user-images.githubusercontent.com/67952253/217246298-01126482-67e4-4d1f-9ebc-fbef1fac0fe9.MP4

**Comment by alwx** [comment]
@qoqobolo Seems like now mentions are broken in general. Is it a known issue?

https://user-images.githubusercontent.com/911127/221516626-06c307a3-0178-4ad3-a98d-cfcd387f8167.mov

**Comment by qoqobolo** [comment]
>  Seems like now mentions are broken in general. Is it a known issue?

Hey @alwx, sorry for the late response. 
Yeah, you're right, now you can't mention a member after they've sent a message. Updated issue the description, thank you.

**Comment by pavloburykh** [comment]
@alwx @qoqobolo hi! Please note that issue title and description has been updated.

**Comment by cammellos** [comment]
Community should be created on desktop, just to make sure, as creating communties on mobile is not supported

**Comment by churik** [comment]
Taking into account that this is the most important flow for communites for 1.25, added prio label

**Comment by John-44** [comment]
I recommend speaking with @jrainville from Desktop messaging team to get an updated understanding of how the joining community flows works from a backend prospective before starting work on this issue (as there have been many recent changes here).

**Comment by jrainville** [comment]
It seems like this issue is pretty old, so it's probably not related to the recent changes.

I can shed light on those anyway if needed. They were mostly about adding new roles (admin for example).

If I had to guess what is going on here is that the mobile frontend is not updating the member list when a new community description comes in. The list of member keys is part of that description.
