### ISSUE TITLE
Bad performance when selecting images in the photo selector

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14963]
# Problem

Selecting or deselecting thumbnails in the photo selector screen is noticeably slow, even on a production release running on fast hardware (Galaxy A71). Tested using `develop` branch on 2023-02-01 8626cd3e6.

### Steps to reproduce:

1. Open a chat.
2. Press the image icon to upload 1 or more images (add around 20 or more images to your photo gallery before this step).
3. Don't bother scrolling, it's not necessary to see the slowness.
4. Tap on each image you want to select. Try selecting and deselecting and monitor how many renders are being performed by React on the `image` component.

- Even without scrolling and only looking at the initial photo selection screen with ~16 thumbnails, I can see hundreds of calls to render `image` while tapping to select/deselect.
- The visual delay is very noticeable, to the point that I don't know if my tap was registered and I tap again. Sometimes a subsequent tap is not even registered because the UI is blocked "processing".

### Notes

- Scrolling is fast and I see no needless re-renders.
- Subsequent pages of thumbnails are fetched and rendered efficiently. I only see one call to the `image` component per thumbnail.

This gives me a strong impression that it's only the selection/deselection implementation that's problematic, because the rest performs well.

**Comment by ilmotta** [comment]
@OmarBasem: cc'ing you to let you know of this problem.

**Comment by OmarBasem** [comment]
Thanks @ilmotta, I will look into it

**Comment by ilmotta** [comment]
I think this issue has been solved already, correct @OmarBasem? Can we close it?

**Comment by OmarBasem** [comment]
Yes @ilmotta we can close it
