### ISSUE TITLE
Album selector issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14981]
This issues is related to https://github.com/status-im/status-mobile/pull/14867#issuecomment-1411950542 

**ISSUE 1. Images can't be selected in the different albums at the same time**
**Preconditions:**
At least 2 albums should be created in device
Example: "Test album 1" and "Test album 2"

**Steps to reproduce:**
1. Open image selector
2. Tap 'recent' button
3. Select "Test album 1" album
4. Select at least one image in the current album (now the count of selected images shown as 1)
5. Select "Test album 2" album
6. Select at least one image 

**Actual result:**
The count of selected images that are done in second album are not calculated together with the previous album

https://user-images.githubusercontent.com/52490791/216027058-ef1259c2-cc28-4a23-9486-7f1f1471a242.mp4

**Expected result:**
The count of images are able to be selected from different albums

**ISSUE 2. The name of the album should be cut if current name is too long**

**Steps to reproduce:**
1. Create album with long name "album test test test  test test test  test test test  test test test  test test test"
2. Go to the chat
3. Open image selector
4. Select current album

**Actual result:**
The name of album overlaps the images If the name is too long

![image](https://user-images.githubusercontent.com/52490791/216029072-a9d3b8a2-77e5-4b82-8a28-980c4b85646a.png)

https://user-images.githubusercontent.com/52490791/216028837-c55d0de3-7065-457e-ae36-169ca4808673.mp4

**Expected result:**
If the name of album is too long it should be cut
Example how it is implemented in Telegram 
![image](https://user-images.githubusercontent.com/52490791/216029472-3878e170-c1ca-4546-91fc-0160bbbe3881.png)
Hi @pedro-et is it suitable?

**Comment by OmarBasem** [comment]
Hi @VladimrLitvinenko, I have fixed these 2 issues in another small unrelated PR. Please check on latest develop, it should be fixed. And if there is still anything with these issues, let me know.

**Comment by VolodLytvynenko** [comment]
> Hi @VladimrLitvinenko, I have fixed these 2 issues in another small unrelated PR. Please check on latest develop, it should be fixed. And if there is still anything with these issues, let me know.

yep. it works. Thank you :)
