### ISSUE TITLE
Contact requests, messages are delivered with delay

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14984]
Since 02 Feb or 03 Feb we started facing an issue with delivery of CR and messages in chats. 

Reproducible on latest nightly

**Steps:**
1. User A sends CR to User B - pay attention how much time it takes for CR to be delivered to receiver
2. User B accepts CR - pay attention how much time it takes for User B to appear in contact list of User A after CR acception
3. User A sends several messages in a row - pay attention at messages delivery time and order of delivered messages

**Actual result:** delivery delay is observed within CRs, CR decisions, messages. Messages in chat are delivered in random order. 

**Expected result:** no delivery delay. 

https://user-images.githubusercontent.com/97245802/216657118-fb6bf709-510e-4136-86e4-4cf72ba2ca81.mp4

[User_B_receiver.zip](https://github.com/status-im/status-mobile/files/10580817/User_B_receiver.zip)
[User_A_sender.zip](https://github.com/status-im/status-mobile/files/10580816/User_A_sender.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
This looks like a waku issue @richard-ramos any recent change that could have triggered it?

In the logs I see a bunch of:

```
t=2023-02-03T13:56:22+0000 lvl=warn msg="keep alive hasnt been executed recently. Killing all connections to peers"

```
```
t=2023-02-03T16:15:25+0000 lvl=eror msg="could not send message" envelopeHash=0x9ccbaa8c9b25675a6de4baa8b3daa244288466462e02cde2779fcefabb5a947c error="not enough peers to publish"
```

```
t=2023-02-03T13:20:25+0000 lvl=info msg="connecting to peer" peerID=16Uiu2HAm56MbHycb9SQDuL78EEu67jtK9yVV1oUAzx4JzLK1HAiN error="failed to dial 16Uiu2HAm56MbHycb9SQDuL78EEu67jtK9yVV1oUAzx4JzLK1HAiN:\n  * [/ip4/89.130.215.58/tcp/60000] failed to negotiate security protocol: peer id mismatch: expected 16Uiu2HAm56MbHycb9SQDuL78EEu67jtK9yVV1oUAzx4JzLK1HAiN, but remote key matches 16Uiu2HAm4E6Yf6qHsRL3PE9LTpKKtU1bUMsTM1tJArTEasC5EnmW\n  * [/ip4/34.121.100.108/tcp/8000/tls/sni/node-01.gc-us-central1-a.wakuv2.prod.statusim.net/ws] failed to negotiate security protocol: peer id mismatch: expected 16Uiu2HAm56MbHycb9SQDuL78EEu67jtK9yVV1oUAzx4JzLK1HAiN, but remote key matches 16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA"
```

looks like we have only one peer at times

**Comment by richard-ramos** [comment]
I added this code: https://github.com/waku-org/go-waku/blob/master/waku/v2/node/keepalive.go#L46-L47
which checks if it's been > ~90s since the last time the keepAlive code was executed, and if so, i disconnect all the peers. Is I use this in desktop to detect if the machine had gone to sleep and it's waking up, to attempt to reconnect to peers.

Do mobile phones suspend execution when they're not active? if so, this is probably what's causing the issue, and perhaps we should increase that time to ... 5-10m instead?

**Comment by cammellos** [comment]
This should be fixed by moving to light push, feel free to reopen if necessary
