### ISSUE TITLE
Incorrect display of landscape images in chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14980]
# Bug Report

## Problem 
Landscape images go beyond the screen in chat view. 

#### Actual behavior
![Screenshot 2023-02-03 at 11 59 32](https://user-images.githubusercontent.com/67952253/216586955-d171ae3d-6045-4877-b5c0-d6e9c4e41d93.png)

### Reproduction

1. Open chat
2. Send a picture in landscape orientation 

### Additional Information

- Status version: nightly 3/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
cc @OmarBasem another images related issue

**Comment by ulisesmac** [comment]
@qoqobolo 
I'm thinking about taking this issue. Do we have a design that specifies how this UI should look?

**Comment by OmarBasem** [comment]
@ulisesmac this issue may have already been fixed by another PR, so I wouldn't recommend working on it now.

@qoqobolo please let me know if this issue is fixed in https://github.com/status-im/status-mobile/pull/14996#issuecomment-1421054369

**Comment by qoqobolo** [comment]
Yes, confirming that this issue is fixed in https://github.com/status-im/status-mobile/pull/14996#issuecomment-1421054369 and is not reproducible in the 1.21.0-rc.1 version.
@OmarBasem @ulisesmac thank you and sorry for the late response!
Closing this one.
