### ISSUE TITLE
Drawer for pinned deleted message (to unpin the message)

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#14998]
Follow-up issue for https://github.com/status-im/status-mobile/pull/14977

PR above makes it able to show deleted messages in pinned message list. There's no way to unpin them since there's no drawer after long press on deleted message.
Edge case that will leave pinned deleted message https://github.com/status-im/status-mobile/issues/14488

**Comment by VolodLytvynenko** [comment]
@yqrashawn Oh. I  missed that this task should be fixed in https://github.com/status-im/status-mobile/issues/14488 which is related to https://github.com/status-im/status-mobile/pull/14977

Created a follow up https://github.com/status-im/status-mobile/issues/15115 with those issues
