### ISSUE TITLE
Action Drawer and Reactions for Albums

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14995]
Images that are sent together get grouped into an album after re-entering the chat like in this design https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=6591%3A382376&t=OjuHXouaFbikUnae-0

But there are some questions regarding the actions and reactions behaviour of an album message:

1. On long-pressing an album message, what actions should be shown?
2. Before images get grouped into an album, a user may have reacted to some images individually, so how should the reactions look like after grouping them into an album? 
3. How can the user view the different reactions for every image in an album?
4. How can a user react to a single image after it has been grouped into an album?
5. Should the user be able to react to the whole album?

cc @pedro-et

**Comment by pedro-et** [comment]
1. Contextual options to that message. Check https://www.figma.com/file/apCsJHT8J58JXbJD2igtbd/Context-Drawers-for-Mobile?t=Pe3Y0aWbTyKBRnvI-6

2. Reactions are to the whole message. That includes many photos and sometimes text. There shouldn't be an option to react to each photo individually:
3. Same answer as 2
4. Can't
5. Same answer as 2

**Comment by OmarBasem** [comment]
Thanks @pedro-et !
