### ISSUE TITLE
Quo 2 - Update Drawers / Bottom Actions component to adapt the new design

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15006]
Update this component in the quo2 component library as per the design spec:

Designs - Drawers / Bottom Actions
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2638%3A35963&t=29WaMjPTYMtHqa1n-0

** There is an implementation of this more or less done in https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/communities/menus/request_to_join/view.cljs#L112-L132

Acceptance Criteria
- dark and light mode
- component tests (jest)
- quo2 preview
- export from quo2/core.cljs
- adjust usage in communities join screen to use this component

**Comment by ajayesivan** [comment]
This component already exists but the design was updated, some changes where added in [this version](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&version-id=4394578802&node-id=2500-41324&mode=design&viewport=1457%2C378%2C0.25&t=9KnEoC5ldVZUxmV6-0). The updated version is required for the [new join community flow](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-293080&mode=design&t=q65GjFvLNstgsaWr-4).
