### ISSUE TITLE
Implement Quo2  component  Drawers/ Documentation drawers

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15016]
Designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=13833%3A272409&t=29WaMjPTYMtHqa1n-0

Component tests
Preview Screens

**Comment by ajayesivan** [comment]
@J-Son89 May I take on this task?

cc: @cammellos

**Comment by J-Son89** [comment]
yep, I will assign it to you now! :)
