### ISSUE TITLE
Implement Quo2 Component - Slideshow/ Automatic progress bar

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15012]
Implement as per designs:

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=14776%3A187263&t=cUfSBLAqiRWScu6W-0

Include component tests
Include preview screen

**Comment by ajayesivan** [comment]
@J-Son89 May I take on this task?

cc: @cammellos

**Comment by J-Son89** [comment]
I will get back to you on this one 👍

**Comment by briansztamfater** [comment]
Some things to take into consideration based on conversation with @J-Son89:
- I think that is better to start from the Automatic progress bar as is a dependency for on Automatic slideshow (thanks @J-Son89 for already adapting this issue)
- We should ask the design team how many seconds each slide should be shown cc @mariocnovoa 
- Also we should make the component flexible enough so it can adapt to removing / adding slides, and not stick to just four

**Comment by briansztamfater** [comment]
Also, for the Automatic slideshow component, I would suggest to integrate and use https://github.com/callstack/react-native-pager-view under the hoods as it uses the corresponding and correct native component for each platform to create these kind of swiping pages (`ViewPager` for Android and `UIPageViewController` for iOS)

**Comment by ajayesivan** [comment]
How should we animate the content, slide/opacity?

Edit: Now this issue is only about the automatic progress bar(I didn't notice the change before asking), this question is not directly related to this issue.
