### ISSUE TITLE
OnBoarding - Implement new splash screen

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15011]
Implement new splash screen as per new designs for onboarding:

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2231%3A253380&t=fD9St3RpvL2wULMb-0

Are more animations needed for this? Check with design team before starting as the designs/illustrations might not be 100% ready

**Comment by briansztamfater** [comment]
As talked with @pedro-et, we can implement the static splash as currently is in Figma, then we can add animations as they are still unsure what the animation will be.
