### ISSUE TITLE
Implement Quo2 component - Onboarding/ small option card

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15019]
Designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=16507%3A187682&t=29WaMjPTYMtHqa1n-0

Component tests

Preview screens

**Comment by ulisesmac** [comment]
@J-Son89  @pedro-et 
 Hi!
 I've just noted both `Default,  Secondary` & `Press, Secondary` variants of the [component](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=16559%3A187624&t=CaJr8iHo4Ft6GmxV-4) are the same.

Probably, the alpha in the backgroud is wrong, the non-pressed should be `0.05` and the pressed one `0.1` (as in the other variants).
