### ISSUE TITLE
Onboarding / Terms of use bottom sheet screen

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15015]
Implement designs for terms of use screen.

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4339%3A537912&t=fD9St3RpvL2wULMb-0

Terms of use copy needs to be updated first. Check with PM if not up to date.

The whole flow should not be broken, in the case new screens are not implemented it should point back to the next step of the old flow.

**Comment by J-Son89** [comment]
@jorge-campo do we have the copy ready for new Terms of Use designs?

**Comment by J-Son89** [comment]
this is already done

**Comment by jorge-campo** [comment]
@J-Son89 , I have just seen this for the first time. My apologies, I wasn't aware of your initial question here.

**Comment by J-Son89** [comment]
turns out it's not already done :)

**Comment by jorge-campo** [comment]
> turns out it's not already done :)

So, it's there anything I can help you with here? "Terms of Use" are not written by us (Docs); Legal is responsible for that. I guess they are similar to [the ones on the Status Website](https://status.app/legal/terms-of-use), but I recommend you double-check with them in the #ask-legal channel.

**Comment by flexsurfer** [comment]
duplicate https://github.com/status-im/status-mobile/issues/20241
