### ISSUE TITLE
Onboarding/  Implement Initial info box

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15017]
Implement as per designs:

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=3068%3A332818&t=fD9St3RpvL2wULMb-0

Depends on: https://github.com/status-im/status-mobile/issues/15016

Depends on: https://github.com/status-im/status-mobile/issues/15018

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by J-Son89** [comment]
Hi @Sudhanva-Nadiger, as you can see in the description this issue depends on two other issues. It would be better to take one of them first. 

@cammellos can @Sudhanva-Nadiger begin working on #15016 #15018 or has someone already began working on them?

**Comment by Sudhanva-Nadiger** [comment]
Yeah , I can start working on the i am new to status page !

**Comment by Sudhanva-Nadiger** [comment]
Since the project is done by clojurescript i thought I would try some easier one first ! 👀

**Comment by J-Son89** [comment]
Hi @Sudhanva-Nadiger, we use Clojurescript in this project. 

If you are going to take a task it would be better to take this one first - https://github.com/status-im/status-mobile/issues/15016

However, I would recommend taking a look at the codebase first to ensure you want to take on this work and have the right technical knowledge to do so. 
Happy to help if you have any questions etc

**Comment by J-Son89** [comment]
> Since the project is done by clojurescript i thought I would try some easier one first ! 👀

yes, the best option imo is #15016 as it is a rather simple component and will get you familiar with the codebase.

I think a good first step is getting set up locally. Please take a look at our docs:

https://github.com/status-im/status-mobile/blob/develop/doc/starting-guide.md

Additionally, we can set up a bounty as reward for completing this task if you complete it. We will contact you about that 👍

**Comment by Sudhanva-Nadiger** [comment]
Yes I will set the app first !
