### ISSUE TITLE
Onboarding/ Fresh Install - implement "Im new to Status page"

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15018]
Designs:
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2539%3A281125&t=fD9St3RpvL2wULMb-0

Needs quo2 components: https://github.com/status-im/status-mobile/issues/15019

**Comment by ulisesmac** [comment]
Hey @J-Son89!

I'm about to implement this UI, but I'm having some questions:
1. What is namespace to put this screen?
2. Besides implementing this UI, is there something else required for this issue? (tests, a preview screen, etc)

**Comment by J-Son89** [comment]
Hey @ulisesmac, I would recommend putting this code in status_im2.contexts.onboarding

As it's another section of the application.

As for requirements this screen will be used in the application so we will swap out the current version of this page for the old one but for now it will still point to old ui for the actions.

There's no tests for this as far as I can see. Maybe eventually we should start building out component tests for page components but for the moment it is not necessary.

There might be some current e2e tests that use this flow so it's worth syncing up with @churik once implemented to ensure no tests are broken from your changes
