### ISSUE TITLE
Adding a user by public key results in a different user being added (iOS simulator)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1502]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to create multiple profiles and add them as contacts so I can reproduce and fix group chat issues.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Adding a new contact by public key should add that specific user with the the same name.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Adding a user named X by their public key results in a contact with the name X being added.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Adding a user named X by their public key results in a contact with the name Y being added.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create a profile
- Copy public key of that profile
- Sign out
- Create a new profile
- Add contact and copy paste public key
- Notice that the user added has a different name

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Adding a user by public key should add that specific user with the right name

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: latest develop branch
[comment]: # (Android or iOS.)
* Operating System: iOS (simulator)

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

https://drive.google.com/file/d/0B9qqS9eU_SdpT3pWUHVBNzB1bHM/view?usp=sharing

**Comment by annadanchenko** [comment]
@oskarth it's expected. The correct user is added (you can check it by comparing public key), you just don't see user name/picture until that user will not add you to the Contacts.

**Comment by oskarth** [comment]
@annadanchenko Ah I see, makes sense from a privacy point of view. Since this is different from how (some) IMs work, do you think it would make sense to make this fact extra clear for end users?

**Comment by oskarth** [comment]
@annadanchenko I tried again by creating two users, changing profile name for both and having them each add each other. As you pointed out, they both have a contact with each other's public key added, but their real names still don't appear.

I also tried sending a message from A to B and B to A, and none of the messages came through. What am I missing?

**Comment by annadanchenko** [comment]
@oskarth it looks like open #1391
