### ISSUE TITLE
Onboarding/ Fresh Install - create profile password

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15024]
Designs:

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2241%3A251839&t=fD9St3RpvL2wULMb-0

Inlcude basic validation of character set and length etc. Consider breaking this up further if the workset is too large

Extensive validation is to be considered separately - https://github.com/status-im/status-mobile/issues/15028

Once password is acceptable - implement disclaimer on screen.

Depends on:
https://github.com/status-im/status-mobile/issues/15025
https://github.com/status-im/status-mobile/issues/15026
https://github.com/status-im/status-mobile/issues/15027

**Comment by ulisesmac** [comment]
Solved in #15405
