### ISSUE TITLE
Implement quo2 component - Colors/ Color Picker

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15021]
Designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2972%3A43112&t=29WaMjPTYMtHqa1n-0

Ensure list of colors matches set in designs:

Component tests 
-> include color set in tests to keep these colors valid.
Preview screens

**Comment by ajayesivan** [comment]
@cammellos May I take on this item?

**Comment by Parveshdhull** [comment]
Probably this code is reusable for the component:
https://github.com/status-im/status-mobile/blob/develop/src/status_im/ui/components/emoji_thumbnail/color_picker.cljs

**Comment by ajayesivan** [comment]
> Probably this code is reusable for the component:
> https://github.com/status-im/status-mobile/blob/develop/src/status_im/ui/components/emoji_thumbnail/color_picker.cljs

I was using that component as a reference.

**Comment by ajayesivan** [comment]
@Parveshdhull I have created a pr and would appreciate it if you could take a look and share your thoughts.
