### ISSUE TITLE
Implement Quo2 component - Dividers/Strength Divider

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15026]
Designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=14826%3A196114&t=29WaMjPTYMtHqa1n-0

Component tests

Preview screens

**Comment by ajayesivan** [comment]
@J-Son89 Please assign this to me

**Comment by ajayesivan** [comment]
@pedro-et The strength divider circle & alert icon designs don't seem right. Could you please take look?
