### ISSUE TITLE
Onboarding - Fresh Install - Enable biometrics flow

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15029]
Designs:
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2884%3A327682&t=fD9St3RpvL2wULMb-0

Illustration is generic for android an ios.

Use the native biometric features of the device.

**Comment by briansztamfater** [comment]
Closing as #15409 is merged (though marked as Closed don't know why)
