### ISSUE TITLE
Landscape mode in Lightbox

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15039]
Implement support for landscape mode in lightbox screen

**Comment by flexsurfer** [comment]
hey @OmarBasem could you please elaborate on why we need this?

**Comment by OmarBasem** [comment]
Hey @flexsurfer, it is a design requirement

**Comment by flexsurfer** [comment]
thanks, is it documented somewhere?

**Comment by OmarBasem** [comment]
@flexsurfer I asked Pedro about this and he told me it should support landscape mode. The designs of the surrounding content (top-view, bottom-view) are going to be post-mvp. That PR implements handling orientation changes of the image itself from portrait mode to landscape mode.
