### ISSUE TITLE
Quo2 component - Profile/ Select Profile

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15031]
Designs:https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=16934%3A192536&t=29WaMjPTYMtHqa1n-0

Component tests
 Preview screens

**Comment by ajayesivan** [comment]
@J-Son89 Can I work on this task? Since this component is mostly similar to the profile-card component, I think it will be quick to implement.

**Comment by J-Son89** [comment]
Hey @ajayesivan,yes that would be great! Feel free to ask any questions if you have any

**Comment by ajayesivan** [comment]
@J-Son89 Could you please assign this to me :)

**Comment by ajayesivan** [comment]
@J-Son89 Should the entire component be clickable, or just the radio button located in the top right corner?

**Comment by ajayesivan** [comment]
@J-Son89 In light theme, the background & text contrast doesn't look right for some customization colors. Is there a light theme variation for this component?

For eg: yellow
<img src="https://user-images.githubusercontent.com/19279756/219967490-7789c633-73b4-48e8-9b23-2791325b5bec.png" width="400"/>

This also happens in the existing `profile-card` component:
<img src="https://user-images.githubusercontent.com/19279756/219967500-1ca6711c-d9f3-473c-8bb5-5d3f3b41d82f.png" width="400"/>

Looks fine in dark theme:
<img src="https://user-images.githubusercontent.com/19279756/219967502-0d18d29c-4a15-4b26-bcd3-b530be755dcb.png" width="400"/>

**Comment by Parveshdhull** [comment]
> Should the entire component be clickable, or just the radio button located in the top right corner?

This component looks very similar to Privacy options component. There we have the whole card clickable,  So I think we should do the same here. ([ref](https://github.com/status-im/status-mobile/pull/14500#pullrequestreview-1208208867))

> Is there a light theme variation for this component?

These components are only going to be used in dark theme.
