### ISSUE TITLE
[For IOS only] The sent messages are shown with the 'sent' status when actually they are 'sending'

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15035]
**Steps to reproduce:**
1. Go to the 1-1 chat
2. Send the message
3. Switch off the internet connection
4. Send one more message
5. Tap on the current message

**Actual result:**
The message is shown with 'sent' status even after the internet connection is switched off

https://user-images.githubusercontent.com/52490791/217339624-2104907b-bd28-4faf-9243-0ca59ada29ee.mp4

**Expected result:**
The message should be with 'sending' status message if it is not sent yet

### Additional Information
- Status version: nightly 
- Operating System: iOS 16, iPhone 11 Pro Max

**Comment by cammellos** [comment]
this should be fixed by the new lightpush implmeentation
