### ISSUE TITLE
Ring comming from the back-end for user-profile is thinner that expected

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#15037]
# Bug Report

## Problem 
[comment]: # (A problem description)

The profile images come with the ring drawn over them, the problem is that the ring drawn is thinner than specified in [designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=1145%3A41518&t=PcoSkIcuyli2g6v4-4):

![image](https://user-images.githubusercontent.com/90291778/217378317-2693da65-5c6c-44ed-a851-c0d76ef1279a.png)

The identicon using a size of 32x32 looks as follows when requested from the back-end:
![image](https://user-images.githubusercontent.com/90291778/217379224-007fae0c-34cc-4f68-96cf-8bbf01baa0e7.png)

Image profile:
![image](https://user-images.githubusercontent.com/90291778/217379519-695f6f90-95e3-4e32-9bb9-82f5348c53e6.png)

But when we put the initals-letters profile image using a size of 28x28 on top of them, looks as follows:
![image](https://user-images.githubusercontent.com/90291778/217379665-48263eef-124b-484e-90d1-7dd1e2c3640e.png)

That white ring exposes the actual width of the color ring being thinner than expected.

#### Expected behavior

The ring being wider over the profile image, to look as the designs.

#### Actual behavior

The ring is thinner.

### Reproduction

1) Open Status
2) Go to chats screen
3) List a user with a profile picture set.

### Additional Information

[comment]: # (Please, add logs/notes if necessary)

It was identified while solving: #14861 
that issue uses what the back-end returns, so when this issue is solved, the rings int the app will look as expected.

**Comment by cammellos** [comment]
This could be fixed by @yqrashawn contribution, please close if that's the case, otherwise feel free to unassign yourself

**Comment by yqrashawn** [comment]
the style of the ring is not changed in https://github.com/status-im/status-mobile/pull/16193
this issue will still be valid after the PR
