### ISSUE TITLE
Contact request compatibility between mobile and desktop

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15049]
# Bug Report

### Case1:
If a desktop user sends a contact request to a mobile user, and a mobile user accepts it, then the mobile user is not displayed in the desktop user's contacts, the contact request continues to be displayed in `pending` requests on desktop, the desktop user cannot be the first to send a message to the mobile user.
The mobile user is able to send a message to the desktop user, they can continue to chat in 1-1 after that.

**Steps:**
1. Desktop User (DU) sends a contact request to Mobile User (MU)
2. MU accepts the contact request

**Expected result:** MU is displayed in contacts for DU; DU can send a message to MU
**Actual result:** MU is not displayed in contacts for DU; DU cannot send a message to MU

### Case2:
The same case but DU has also their account recovered on a mobile device.

**Steps:**
1. Desktop User (DU1) recovers the account with a seed phrase on a mobile device (MU1) (without syncing)
2. Create a new account on an additional mobile device (MU2)
3. DU1 sends a contact request to MU2
4. MU2 accepts the contact request
The expected and actual results here are the same as for Case 1.
5. MU2 sends a message to MU1

**Actual result:**  this message is displayed for MU1 as a new notification in the Activity center (`sent contact request`) with a text message that was sent in 1-1 chat; no action can be taken with this notification.
For DU1 this message is displayed in 1-1 chat normally.

<img width="325" alt="Screenshot 2023-02-09 at 12 25 10" src="https://user-images.githubusercontent.com/67952253/217800109-2c711035-9f3c-4f20-84f7-72ac6b04b6d7.png">

### Additional Information

- Status version: RC1
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
I think I know the reason, I can add a message for backward compatibility with 0.9 desktop, I'll try that first.
