### ISSUE TITLE
Documentation on how status-mobile works with status-go

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#15052]
Write documentation on how status-mobile works with status-go

**Comment by flexsurfer** [comment]
this might be useful https://notes.status.im/s/I_FYxFoy9

**Comment by ibrkhalil** [comment]
[Added a video tutorial here](https://drive.google.com/file/d/150cDvTF1Ivy2Oq3C-ddzroUnyEAqD2uy/view?usp=sharing)
