### ISSUE TITLE
Additional contact request on mobile when initial contact request is accepted 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15057]
Follow up on https://github.com/status-im/status-mobile/pull/15054
User A and User B are using mobile apps (PR builds)

**Steps:**
1) A: send CR
2) B: accept CR

**Expected result:**
A: user B is added to contacts, no pending CR anymore 

**Actual result:**
A: user B is added to contacts, and pending CR is shown 
![IMAGE 2023-02-09 18:17:07](https://user-images.githubusercontent.com/4557972/217888849-5fc7933e-3e4d-432c-bb18-14c2b1733735.jpg)

**OS:** IOS, Android (status-go with `feature/add-backward-compatibility-with-0.90`)

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
This should be fixed, re-open please if it's not the case, thank you
