### ISSUE TITLE
'ethereum accounts.Manager is nil' on login

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15055]
# Bug Report

## Problem 

<img width="391" alt="Screenshot 2023-02-09 at 17 33 55" src="https://user-images.githubusercontent.com/67952253/217877636-1d9e65a5-42e4-4e9f-a5a2-e5e799e48310.png">

### Reproduction

1. Create an account
2. Log in > log out several times

### Additional Information

- Status version: nightly 8/02
- Operating System: Android

**Comment by cammellos** [comment]
The fix has been tested, waiting review on status-go and cherry picking after that
