### ISSUE TITLE
Can't see display/ens/name when mentioning in community

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#15056]
When mentioning someone, I can only see 3 words names, we should display (and search on), the contact names.

**Comment by flexsurfer** [comment]
@cammellos could you elaborate please, because nickname and ens name work fine both in search and in mention itself

**Comment by cammellos** [comment]
@flexsurfer on the autocomplete list, I only see 3 random words names, @churik also I believe had the same issue

**Comment by flexsurfer** [comment]
im trying in group chat, works fine, probably its only community related ?

**Comment by cammellos** [comment]
> im trying in group chat, works fine, probably its only community related ?

I have only tried in communities, you are right, group chats I haven't tried

**Comment by churik** [comment]
![image_2023-02-09_18-55-58](https://user-images.githubusercontent.com/4557972/218707644-7666a15c-e22a-4ee1-9627-8cd8ebb7f935.png)
it is only community-related issue, you're right

**Comment by flexsurfer** [comment]
@churik works fine for me in communities as well
<img width="388" alt="image" src="https://user-images.githubusercontent.com/11790366/218708108-aaf872cf-44d8-45af-bb2b-26cd71d4dfbf.png">

**Comment by cammellos** [comment]
@flexsurfer another info, I thought wasn't relevant, is that I have synced my contacts from desktop, so might be that we store things differently?

**Comment by churik** [comment]
@cammellos @flexsurfer 

https://user-images.githubusercontent.com/4557972/218710636-c6f991eb-79ca-4654-98ca-9c4173eabcec.mp4


Steps to reproduce:
1) Desktop: create encrypted community
2) Desktop: invite user (mobile)
3) Mobile: join the community and try to mention there user from desktop
