### ISSUE TITLE
Random crashes all over the app (IOS/Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15053]
Unfortunately there are no clear steps yet how to reproduce crash

Here is [logcat](https://drive.google.com/file/d/1sPoQXsDjETmBtiQF8JZJgPWxKZfK9BGh/view?usp=share_link) from Android device. It should contain logs of 1 crash. 

### Additional Information

- Status version: release 1.22 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
@cammellos some more [logs](https://drive.google.com/file/d/1rJ1t88kcxIXPu-LnEyb0rlCTV3zrpOJ6/view?usp=share_link) and video. This time crash occurred on all devices - IOS, Android, Desktop. 
Crash keeps happening after every relogin. User is unable to use the app. 

https://user-images.githubusercontent.com/97245802/217856351-ba2a48a6-ce37-4b90-8965-ec8cd231c291.mp4

**Comment by churik** [comment]
On RC build [301](https://ci.status.im/job/status-mobile/job/manual/301) issue is still there unfortunately

**Comment by cammellos** [comment]
@churik do you have the logcats?

**Comment by cammellos** [comment]
> @churik do you have the logcats?

Also, for the logcat they need to be the ones taken "manually" (`adb logcat > /tmp/output.txt`), not from the app, as they don't contain crash logs

**Comment by churik** [comment]
Will attach them once we have new ones, thank you for the instruction!

**Comment by pavloburykh** [comment]
@cammellos hi! Here is [logcat](https://drive.google.com/file/d/1DxcCyqQRqGFNW5w6CypZhye27wXuoxKf/view?usp=share_link)


https://user-images.githubusercontent.com/97245802/218468713-c18a1c07-87ef-422c-a27e-d912f08cd961.mp4

**Comment by cammellos** [comment]
@richard-ramos there's some reports that his is still not fixed, qa team will test today in order to catch it and collect logs, but in the meantime, do you know where else we could get these crashes?

**Comment by richard-ramos** [comment]
![image](https://user-images.githubusercontent.com/1106587/218733728-826e6ecb-b0e6-44f9-900e-15449065174d.png)

**Comment by richard-ramos** [comment]
I looked at the prev shared logcat and saw two types of panic:
```
02-13 15:14:59.914  3140  3239 E GoLog   : panic: runtime error: slice bounds out of range [:2] with capacity 0
```
```
panic: enode: can't sign record: record bigger than 300 bytes
```

The first one SHOULD be fixed by the PR I created yesterday for status-go, but the second one, I'm not sure how to fix it.
The problem goes like this: The function `writeMultiaddressField` is called when there's an update in the multiaddresses for the node, and one of the multiaddresses contain a circuit-relay addr.

It attempts to write as many multiaddresses as possible in the multiaddr field, but since  go-ethereum will not complain until the moment `.Node()` is executed, and if it exceeds 300 bytes, it will panic. I try to intentionally cause the panic here:
https://github.com/status-im/status-go/blob/8acc46f758729b44d771b5713553c2c42109b548/vendor/github.com/waku-org/go-waku/waku/v2/node/localnode.go#L51 and capture it here: https://github.com/status-im/status-go/blob/8acc46f758729b44d771b5713553c2c42109b548/vendor/github.com/waku-org/go-waku/waku/v2/node/localnode.go#L30-L34 so instead of panicing and crashing, it returns an error instead. But as we can see, this is not effective....

I'm thinking of just removing storing circuit relay addresses in the ENR. What do you think? I dont see anything obvious that could be causing the error in the code, and it seems to happen rarely

**Comment by churik** [comment]
Crashes are getting back for both apps: desktop, android, and IOS.
So far got logs for Android (from e2e):
[logcat (5).log](https://github.com/status-im/status-mobile/files/10813454/logcat.5.log)
Moment of the crash: https://app.eu-central-1.saucelabs.com/tests/df98f00a4abf45c0aafbae29c5b209ea?auth=4e0c17d70332d6524c32297e5f01ec60#36

**Comment by cammellos** [comment]
Thank you @churik here's the stacktrace:

```
02-23 03:26:13.243  5701     0 E Go      : panic: enode: can't sign record: record bigger than 300 bytes
02-23 03:26:13.243  5701     0 E Go      : 
02-23 03:26:13.243  5701     0 E Go      : goroutine 14494 [running]:
02-23 03:26:13.244  5701     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).sign(0x8fd38160)
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:310 +0x69d
02-23 03:26:13.244  5701     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).Node(0x8fd38160)
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:122 +0x14b
02-23 03:26:13.244  5701     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).Self(...)
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:178
02-23 03:26:13.244  5701     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).lookupWorker(0x8eb13950, 0x905c39d0, {0xff, 0x18, 0xda, 0xc1, 0xac, 0xcb, 0xae, 0xac, ...})
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:313 +0x1f7
02-23 03:26:13.244  5701     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).newLookup.func1(0x905c39d0)
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:296 +0x35
02-23 03:26:13.244  5701     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*lookup).query(0x938d51a0, 0x905c39d0, 0x91b5fa40)
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:144 +0xde
02-23 03:26:13.244  5701     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*lookup).startQueries
02-23 03:26:13.244  5701     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:126 +0x2b8
```

**Comment by richard-ramos** [comment]
@cammellos in this PR i added some extra logging and Printlns to check what's being stored in the ENRs. Can we add that commit to mobile to see that information?
https://github.com/status-im/status-go/pull/3219

**Comment by richard-ramos** [comment]
@pavloburykh @cammellos @churik 
This PR: https://github.com/status-im/status-go/pull/3230 fixes the issue! sorry for the inconvenience! it was a tricky bug to catch.
