### ISSUE TITLE
Text is not shown on desktop when message with image and text is sent from mobile

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15065]
# Bug Report

## Problem 

If you send an image with a description from mobile to desktop, only the image will be delivered for the desktop user.

### Reproduction

1. UserA (mobile) and UserB (desktop) have a chat (1-1/community..)
2. UserA: pick an image from the gallery and enter text in the input field > send the message
3. UserB: check the message

<img width="327" alt="Screenshot 2023-02-10 at 15 43 59" src="https://user-images.githubusercontent.com/67952253/218119891-d4ced3a4-745f-4629-a5f7-9cde80a27243.png">

#### Expected behavior
Can see both the image and the text

#### Actual behavior
Only image received

### Additional Information

- Status version: RC1
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
@qoqobolo what is the desktop version you use?

**Comment by qoqobolo** [comment]
@rasom 0.9.0

**Comment by rasom** [comment]
@qoqobolo @cammellos @iurimatias
So on mobile we send a single message which contains both text and image, when on desktop two separate messages are sent. Thus fix might be as well done on desktop side, it depends on which version we want to support.

Currently `text` field is hardcoded on desktop on sending and ignored on showing the image 
https://github.com/status-im/status-desktop/blob/4a93fa14bc26254215e168d7e7d591633a2653b0/src/backend/chat.nim#L86

**Comment by cammellos** [comment]
@rasom ok, for the time being, we could leave this out until a decision is made, eventually, I guess it makes sense to have it going together, so this might need changing in desktop, but open to anything @jrainville what do you think?

**Comment by rasom** [comment]
@cammellos as a temporary fix we can just send two separate message on mobile side as well, just to have compatibility with desktop's 0.9.0

**Comment by cammellos** [comment]
> @cammellos as a temporary fix we can just send two separate message on mobile side as well, just to have compatibility with desktop's 0.9.0

the issue is that we would see duplicate messages on mobile and desktop (once they upgrade)

**Comment by rasom** [comment]
ok then, I don't mind just to wait till they upgrade :)

**Comment by anastasiyaig** [comment]
@John-44 could u please elaborate on this - this is new requirement to send text+image in 1 message, and it is not yet implemented in desktop client. Question - how do we want to have it aligned for both apps (mobile and desktop) and what is expected result? 
@jrainville adding u as well as it is related to messaging functionality

**Comment by qoqobolo** [comment]
A small remark here: this issue is added in rc1, although we don't consider it a strict release blocker.

It was added because the mobile team is going to use rc1 for community (1-1/group) messaging and we're trying to get the basic functionality of the messenger working properly. With this issue, users may face a situation when the recipient will not receive the text, and the sender will not know that the text was not received.
However, we can postpone it for later if there is no easy way to fix it, but warn people that this feature won't work.

**Comment by cammellos** [comment]
@qoqobolo @anastasiyaig I'd say, if we can add this on desktop, it's probably the best, but if we can't, we can restore the old behavior, what does everyone think?

**Comment by anastasiyaig** [comment]
@cammellos i am trying to get an estimate to implement this , we need developers to look into this, ideally someone from messenger team. I will leave it with @iurimatias and @John-44 to decide and plan, lets wait a bit :)

**Comment by John-44** [comment]
@cammellos @anastasiyaig @qoqobolo @rasom Re. this issue, all Status clients (Mobile, Desktop, Web) need to be compatible with the Status protocol (including the Status Communities protocol) and support the Status protocol in the same way.

@cammellos is the ultimate owner of the Status protocol and the Status Communities protocol, so if @cammellos acks a change to the Status protocol then all Status clients (Mobile, Desktop, Web) will need to implement the change that @cammellos has ack'ed.  @felicio and @prichodko also need to be looped into any discussions around any changes to the Status protocol so they can ensure that status.js is updated in line with any changes.

The particular change to the Status protocol under discussion here has been previously discussed and agreed (and it's a needed change), so we *should not* revert to the previous behaviour that is currently implemented in Status Desktop.  tldr; Status Desktop and Status Web need to implement this change.  

In the future there are more questions about how any part of any Status protocol should behave or be supported in the Desktop, Mobile, and Web clients, these questions should be directed to @cammellos as he is the ultimate authority regarding the Status protocol.

I hope this answers the question!

**Comment by anastasiyaig** [comment]
I added a follow up task for desktop project to have this implemented, i put 0.11.0 as a target for this
