### ISSUE TITLE
Some contact data is not synced between desktop and mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15066]
# Bug Report

## Problem 
Checked in the scope of rc-1.
When using the existing sync flow (Profile > Sync > Devices) some contacts data which was set on desktop may not sync. 
Unfortunately, there are no reliable steps to reproduce.
The user with 38 contacts has 8 contacts synced with that issue (so the usernames that were set on desktop are shown as 3-random names on desktop.

#### Expected behavior
All data is synced

#### Actual behavior
8/38 contacts synced like these.
<img width="161" alt="photo_2023-02-10 18 45 49 jpeg 2023-02-10 18-46-14" src="https://user-images.githubusercontent.com/4557972/218160702-d856a680-8f3d-459a-8500-be830ff3b60c.png">

### Reproduction
**Prerequisites**: have multiaccount on desktop with 30+ contacts
1) mobile: restore the same multiaccount 
2) desktop: sync desktop > mobile (Desktop > Device settings)
3) mobile: check contact list

### Additional Information

- Status version: rc-1 #300  
- Operating System: Android, iOS

**Comment by cammellos** [comment]
This has been merged
