### ISSUE TITLE
AC/read indicators are not synced in direction mobile > desktop

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15103]
# Bug Report

## Problem 
Currently, if a user reads a message in a channel or in the activity center on mobile (rc-1, #301) and has synced desktop (0.10.0),  it won't be synced on the desktop side until re-login.
All fine in the other direction.

#### Expected behavior
notification is erased from activity center on desktop

#### Actual behavior
notification is erased  only after re-login

### Reproduction
**Prerequisites:** multi-account  for User A  is paired (both sides, mobile <-> desktop)
1)  User B: send mention to User A
2) User A (mobile): reads notification in Activity center
2) User A (desktop): pay attention to Activity center

### Additional Information

- Status version: 0.10.0 (https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.10.x/11/) 
- Operating System: Desktop (Mac OSx) , IOS, Android

User A (mobile): [geth.log](https://github.com/status-im/status-mobile/files/10757049/geth.log)

User A (desktop): [geth_pairing.log](https://github.com/status-im/status-mobile/files/10757006/geth_pairing.log)

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
@churik 
As far as it works on `develop` on mobile in any direction it is likely due some changes in `status-go` which were not included in `0.10.0`

@anastasiyaig do you some kind of nightly builds to check whether the issue exists in current dev version of desktop app?

**Comment by anastasiyaig** [comment]
@rasom hi, we do have master build being triggered after each commit merged to master. You can find it there (latest) https://ci.infra.status.im/job/status-desktop/job/master/1507/

**Comment by rasom** [comment]
@anastasiyaig thank you, I will check whether it is reproducible in `master`

**Comment by rasom** [comment]
@churik @anastasiyaig 
I can confirm that the issue is not reproducible with desktop's `master`, nothing to do here `¯\_(ツ)_/¯`

**Comment by churik** [comment]
cool then! closing it
