### ISSUE TITLE
Edge cases with delete messages

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15115]
Follow up for https://github.com/status-im/status-mobile/issues/14489 , https://github.com/status-im/status-mobile/issues/14488

## ISSUE 1: The '<User_B> deleted this message' instead of '<User_A> deleted this message' notif is shown if User_A removes the message of User_B by delete for me option
**Steps to reproduce:**
1. User_A and User_B go to any chat
2. Send the message as User_B
3. Remove the message as User_A by 'delete for me' the option

**Actual result:**
The '<User_B> deleted this message' is shown for User_A

https://user-images.githubusercontent.com/52490791/219643834-073ec9cc-e49e-4ccb-af6b-699a00bfc57a.mp4

**Expected result:**
The '<User_A> deleted this message' is shown for User_A

## ISSUE 2: The messages removed by 'delete for me' option are shown in the list of pinned
**Preconditions:**
- If this is a Community or Group chat, then User_A is admin and User_B is invited

**Steps to reproduce**
1. Go to any chat
2. Send the message as User_B 
3. Remove the message by 'Delete for me' option
4. Pin the message as User_A
5. Open a list of Pinned messages as User_B
6. Long tap on the message

**Actual result:**
Message removed by 'delete for me' option is shown in the list of pinned

https://user-images.githubusercontent.com/52490791/219643139-ce59bf53-bd43-4548-b26a-dca7a12fa70f.mp4

**Expected result:**
The message is not appeared in the list of pinned if it is deleted by 'delete for me' option

**ADDITIONAL INFO:**
The same steps are for 1-1 chat

## ISSUE 3: The messages are not able to be unpinned by non-admin users if the current message is removed by 'remove for everyone' option in Group chat

**Preconditions:**
-  User_A is admin and User_B is invited

**Steps to reproduce**
1. Go to any chat
2. Send the message as User_B 
3. Remove the message by 'Delete for everyone' option
4. Pin the message as User_A
5. Open a list of Pinned messages as User_B
6. Long tap on the message

**Actual result:**
Unpin option is not shown for User_B

https://user-images.githubusercontent.com/52490791/219645477-08244fc7-3096-462b-b9ac-efe8eec633ee.mp4

**Expected result:**
Unpin option is shown for User_B

CC: @yqrashawn

**Comment by yqrashawn** [comment]
@VladimrLitvinenko question about issue2 and issue3, is this related to https://github.com/status-im/status-mobile/issues/15112, which there are features for groups and communities that allow none admin user to unpin message

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko question about issue2 and issue3, is this related to #15112, which there are features for groups and communities that allow none admin user to unpin message

@yqrashawn Oh, yes, you are right. And this is the problem with group chats. It may be better to discuss this with the design team. 
**Because can be a case:**
1. UserB (Non-admin) sends the message in group chat
2. UserA (Admin) pins the message
3. UserA removes this message by 'delete for everyone' option
4. UserA clear history in the group chat

**Actua result:**
UserB sees pinned deleted message forever without the ability to unpin and the Admin user is also not able to unpin it because this message no exist for him anymore after history clearing

**Expected result**
I would suggest removing this message from a list of pinned in the group chat. But let me ask someone from design team
