### ISSUE TITLE
1-1 chat is always started with the first user in contact list regardless which user has been selected on New chat screen (RC-1 blocker?)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15123]
Might be also assumed as RC-1 blocker @cammellos 

**Steps:** 

1. Create/recover user who has at least 2 contacts 
2. Tap Chats tab
3. Tap + (plus) button => New chat
4. Select any user from the contact list except first one
5. See which user is in fact selected (observe text in appeared "Chat with ...." button
6. Tap "Chat with ...."
7. See with which user the chat has been started

**Expected result:** chat should start with exact user that has been selected from contact list. 

**Actual result:** 1-1 chat is always started with first user from contact list. 

https://user-images.githubusercontent.com/97245802/219703645-307e1c34-fde4-489c-8334-8d4427b1e20a.mp4

[Status-debug-logs (3).zip](https://github.com/status-im/status-mobile/files/10768588/Status-debug-logs.3.zip)

### Additional Information

- Status version: nightly, [release/1.21.x](https://ci.status.im/job/status-mobile/job/manual/306/)
- Operating System: Android, iOS

**Comment by cammellos** [comment]
@pavloburykh yes, thank you for reporting this, I'd say it's a release blocker unfortunately, nice find!
