### ISSUE TITLE
3 random name is lost after relogin (release blocker)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15120]
Probably related to https://github.com/status-im/status-mobile/pull/15083 cc @siphiuel @cammellos 

**Steps:**

1. Create/restore multiaccount
2. Open Profile tab, make sure that user's 3 random name is shown
3. Perform relogin (manually tap Sign out and then login again)
6. See if 3 random name is still displayed on profile screen 

**Expected result:** 3 random name is not lost. It is possible to mention user by 3 random name both from mobile and desktop.

**Actual result:** 3 random name is lost. After that it is impossible to mention such user from desktop.

https://user-images.githubusercontent.com/97245802/219677446-6a7d3797-ca40-4b05-9a98-12afb9f72707.mp4

 
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/10767601/Status-debug-logs.2.zip)

### Additional Information

- Status version: release 1. 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vitvly** [comment]
Initially i thought it might be due to https://github.com/status-im/status-go/commit/2f41034b47d67eacc9002043b451962a45dd93ba not getting included, but it's there in the `v0.131.7+hotfix.1` tag. Debugging.

**Comment by cammellos** [comment]
```
t=2023-02-17T13:58:56+0000 lvl=dbug msg="Handling Backup" site=RetrieveAll hash=0x3b0dd7ecf53c3e744db25fa43489646d4865ad4ca66c71145ee56836f7b263d6 message-id=0xbf944352f7e5a5e688783dccfc0b791d643777c6dbd00627191356ac942e94e3 message="{Clock:1676042107182 Id: Contacts:[] Communities:[] ContactsDetails:total_number:1  CommunitiesDetails:total_number:4  Profile:<nil> ProfileDetails:total_number:1  Setting:type:DISPLAY_NAME clock:1675959864104 value_string:\"\"  SettingsDetails:data_number:2 total_number:5  XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}"
```
@siphiuel , looks like it might be backup issue https://github.com/status-im/status-go/blob/1d1a95091df0197199ea502aae24c823faf9b989/protocol/messenger_backup_handler.go#L77 we don't check for empty values

**Comment by cammellos** [comment]
If that's the issue, this is also a fix that desktop will want to include

**Comment by vitvly** [comment]
I'm trying to reproduce with the change
```
	if dbDisplayNameClock < message.DisplayNameClock &&
		message.DisplayName != "" {
		err = m.SetDisplayName(message.DisplayName, false)
```

**Comment by vitvly** [comment]
This did not help, there's still empty string in display-name. Dumb fix like https://github.com/status-im/status-mobile/pull/15122 works. It also affects desktop however, right?

**Comment by cammellos** [comment]
@siphiuel dumb fix for RC sounds fine for now, I am not 100% sure it affects desktop, it could be that display name is nil and we show it while we should not, I think for now it's fine like so until an issue is reported on desktop
