### ISSUE TITLE
new chat bottom sheet doesn't have animation on close when "new chat" is pressed

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#15134]
new chat bottom sheet doesn't have animation on close when "new chat" is pressed, it just instantly disappear

**Comment by flexsurfer** [comment]
cc @ibrkhalil

**Comment by ibrkhalil** [comment]
Dismissing a bottom sheet in any way other than the backdrop will require using a setTimeout function on the new event dispatching .. To make it wait for other view .. You think I should do it again ?

**Comment by flexsurfer** [comment]
i thought thats how it was implemented, in any case there should be closing animation

**Comment by ibrkhalil** [comment]
> i thought thats how it was implemented, in any case there should be closing animation

Okay, Will fix it asap

**Comment by flexsurfer** [comment]
no rush
