### ISSUE TITLE
No "Add to contacts" button & other commands after my account was added to someone's Contacts [contacts-refactor]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1514]
### Description

*Type*: Bug

*Summary*: 
issue is only for iOS <-> Android; iOS <-> iOS; 
Works fine on Android <-> Android
Contact "Watson" adds contact "Hudson" to his Contacts. For added Hudson:
1. there is no empty chat shown in Chats untill Watson will not send a message
2. As soon as 1st message is sent by Watson then Hudson can see new chat with that message
3. In a new 1-1 chat for Hudson there is no "Add to Contacts" button, so she can't add this contact to the Contacts
4. No commands except @browse are shown to Hudson in 1-1 chat (even after relaunch)
5. Send message received by Hudson is shown as plain text
6. Request message received by Hudson is shown as empty box

Expected: 
2. Empty 1-1 chat is shown to Hudson after Watson added her to his contacts
3. 1-1 chat for Hudson contains "Add to Contacts" button
4. commands like "send", "request", "location" are shown in 1-1 chat for Hudson

![img_0514](https://user-images.githubusercontent.com/6584810/28712304-097815b8-738b-11e7-884c-809a68764fdf.jpg)

### Reproduction

- as Watson: scan QR code for Hudson and add her to the contacts
- as Hudson: check Chats for new 1-1 chat with new contact. Wait for 1-2 minutes
- as Watson: send her new text message
- as Hudson: check new 1-1 chat with a contact and find "Add to Contacts" button and other commands, e.g. "send" - not shown currently
### Additional Information
* Status version: develop 0.9.9d103
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment]
fixed
