### ISSUE TITLE
Allow user to sync devices

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#15142]
As a user
I want to be able to pair/sync my devices
So that I can use status on multiple devices

### Description

The flow starts here: 
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675%3A177908&t=7tNq8e69gJwkCGMo-4

You can use the old profile and plug the new flow there in a new entry ("Syncing"), under Sync settings

Remove any mock data in current version in place of real data, device names etc

### Out of scope
- how to scan
- New profile design
- different error conditions (we can have a single error for now)

@qfrank @Samyoul @siddarthkay will have all the relevant information for the backend, which is being implemented right now

**Comment by J-Son89** [comment]
I have merged the first page of this into develop (after release branch was cut) - https://github.com/status-im/status-mobile/issues/15448

and will have a pr for the second page very soon - https://github.com/status-im/status-mobile/issues/15548

Also there is the "How to scan screen" on page 2 - https://github.com/status-im/status-mobile/issues/15482

Then lastly it is removing any mock data and add in the new designs for authentication process which are still in design. - cc @pedro-et

**Comment by J-Son89** [comment]
merged pr https://github.com/status-im/status-mobile/pull/15623

all that's left of this is to remove the mock data. 

Will create a pr for this and then afterwards we should be able to close this issue.
