### ISSUE TITLE
'Add a contact' page issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15146]
Follow up for https://github.com/status-im/status-mobile/issues/14481

## ISSUE 1: The 'ENS or chat key' textbox is restoring the old inputted data after its removing
**Steps to reproduce:**
1. Go to 'Add a contact' page
2. Type any data into textbox (example: testdata)
3. Remove current data

**Actual result:**
The text 'testdata' is restored and shown in the textbox again

(on the record, I didn't paste the removed 'Jjnn'  text. It appeared itself)

https://user-images.githubusercontent.com/52490791/220330339-d40cc795-7a29-4749-a4a7-436626fc43b3.mp4

**Expected result:**
The removed data is not restored in the textbox field

## ISSUE 2: The tapped [paste] button is shown as white if it is pressed
**Steps to reproduce:**
1. Open 'add a contact' page
2. Long press on the 'paste' button

**Actual result:**
The paste button is white when it is tapped

https://user-images.githubusercontent.com/52490791/220334800-b3f6c45b-7501-46f6-9581-0d254990d4fc.mp4

**Expected result:**
The button is shown as per the design

**Comment by vkjr** [comment]
@erikseppanen, do I understand correctly that this issue will be fixed within your PR #15192, since you incorporated changes from #15173? If so, can I reassign this to you?
Thanks

**Comment by erikseppanen** [comment]
> @erikseppanen, do I understand correctly that this issue will be fixed within your PR #15192, since you incorporated changes from #15173?
yes
> If so, can I reassign this to you? Thanks
yes

Thanks @vkjr
