### ISSUE TITLE
Edge case when CR which has been sent from mobile and accepted on desktop side remains as pending on mobile side

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15145]
cc @cammellos 

**Preconditions:** User M - mobile user, User D - desktop user. 

**Steps:**
1. User D sends CR to User M
2. User M accepts CR
3. User M removes User D from contact list
4. User M sends CR to User D
5. User D accepts CR
6. See if User D has been added to contacts for User M

**Expected result:** users become mutual contacts and are able to send/receive messages. 

**Actual result:** User D has not been added to contacts for User M. User's M CR remains in pending status despite it has been accepted by User D. User D observes User M in his contact list and is able to send messages. User M receives messages from User D but is not able to send messages, as input field is disabled because of pending CR. 

https://user-images.githubusercontent.com/97245802/220300995-2e33a54c-d51a-4b34-b731-9ef24f211495.mp4

[mobile_user-logs.zip](https://github.com/status-im/status-mobile/files/10791785/mobile_user-logs.zip)

### Additional Information

- Status version: nightly, release/1.21.x 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@pavloburykh can you replicate consistently? 
From the logs, I see that Mobile device didn't receive the AcceptContactRequest from desktop, so looks like it might be a network issue

**Comment by pavloburykh** [comment]
> @pavloburykh can you replicate consistently? From the logs, I see that Mobile device didn't receive the AcceptContactRequest from desktop, so looks like it might be a network issue

hi @cammellos Yes, I do replicate consistently between mobile version release/1.21.x and Desktop version 0.10.0  https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.10.x/10/

**Comment by cammellos** [comment]
@pavloburykh what about mobile->mobile? or inverted roles?

**Comment by pavloburykh** [comment]
> @pavloburykh what about mobile->mobile? or inverted roles?

mobile - mobile works correctly.  Inverted roles, when desktop sends CR and mobile accepts also works correctly. Currently I am facing only issue with mobile - desktop and only following the described  above [steps](https://github.com/status-im/status-mobile/issues/15145#issue-1593114973) steps

**Comment by cammellos** [comment]
@pavloburykh this might be an issue with desktop, from our side, we don't see the accept notification message, is it possible that it's not sending it? cc @MishkaRogachev @jrainville

**Comment by jrainville** [comment]
I don't know. Interesting case. @MishkaRogachev did you check it?

**Comment by cammellos** [comment]
@jrainville https://github.com/status-im/status-go/pull/3216 probably not related, but maybe it is, @pavloburykh are you using a new account on desktop or an existing one? 
If you are using an already existing one, worth trying with a new one

**Comment by pavloburykh** [comment]
> @pavloburykh are you using a new account on desktop or an existing one? 

@cammellos I was using a relatively new account. It has been recently created, has not been restored on other devices etc. 

A have just tried on newly created desktop and mobile accounts and still reproducing the bug. @cammellos do I understand correctly that it is not reproducible for you following those specific [steps](https://github.com/status-im/status-mobile/issues/15145#issue-1593114973)?

**Comment by cammellos** [comment]
> > @pavloburykh are you using a new account on desktop or an existing one?
> 
> @cammellos I was using a relatively new account. It has been recently created, has not been restored on other devices etc.
> 
> A have just tried on newly created desktop and mobile accounts and still reproducing the bug. @cammellos do I understand correctly that it is not reproducible for you following those specific [steps](https://github.com/status-im/status-mobile/issues/15145#issue-1593114973)?

No no, I haven't tried, I trust you :) I just thought it might be due to some issues with migrations, but if you tried with new accounts, that's not the case, thanks for confirming

**Comment by MishkaRogachev** [comment]
Latest desktop master: 
https://user-images.githubusercontent.com/2522130/220582713-5ab013eb-82b8-41e8-98f8-92750f3f9c14.mov

For sending CR we use `sendContactRequest`. For the receiver side we are still using `acceptLatestContactRequestForContact` and `dismissLatestContactRequestForContact` endpoints

@pavloburykh maybe you can share status mobile version for ios and i can debug on the desktop side

**Comment by pavloburykh** [comment]
> @pavloburykh maybe you can share status mobile version for ios and i can debug on the desktop side

sure @MishkaRogachev Here are mobile builds with latest develop:

**Android** https://status-im-builds.ams3.digitaloceanspaces.com/StatusIm-Mobile-230222-110829-d6c09d-manual-universal.apk
**IOS** https://i.diawi.com/6fXXb3

Though, I am no sure if you'll be able to install IOS builds. In order to be able to install IOS builds your UDID/apple ID should be added to the list by Jakub (ping him up if it will be needed). 
At the same time - you should be able to install android apk build. 

Feel free to ping me up if you'll need any help on reproduction.

**Comment by MishkaRogachev** [comment]
> > @pavloburykh maybe you can share status mobile version for ios and i can debug on the desktop side
> 
> sure @MishkaRogachev Here are mobile builds with latest develop:
> 
> **Android** https://status-im-builds.ams3.digitaloceanspaces.com/StatusIm-Mobile-230222-110829-d6c09d-manual-universal.apk **IOS** https://i.diawi.com/6fXXb3
> 
> Though, I am no sure if you'll be able to install IOS builds. In order to be able to install IOS builds your UDID/apple ID should be added to the list by Jakub (ping him up if it will be needed). At the same time - you should be able to install android apk build.
> 
> Feel free to ping me up if you'll need any help on reproduction.

Thanks! Unfortunately i have only ios device, will ping Jakub
