### ISSUE TITLE
Mobile is receiving messages in 1-1 chat from desktop user despite users are not mutual contacts any more

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15149]
cc @cammellos I am not sure on which side (Desktop or Mobile) this issue should be addressed. Tell please what do you think based on the description below. 

**Preconditions:** User M - mobile user, User D - desktop user

**Steps**

1. Users M and D are mutual contacts
2. Initiate 1-1 chat between User M and User D
3. By User M remove User D from contacts (or vice verse) in order users stop to be mutual contacts
4. User D opens existing 1-1 chat with User M
5. User D sends messages in 1-1 chat
6. See if messages are delivered and received by User M

**Actual result:** messages are delivered and received by User M. Overall, we currently have different UI behaviour between Mobile and Desktop in terms of input field  in 1-1 chat between non contacts: on mobile we disable chat input field in case if users are not mutual contacts so there is no possibility to send messages. On desktop, chat input field is enabled in 1-1 chat with non contact user and it is possible to send messages. But in case with chat between 2 desktop users who are not mutual - those messages are not delivered and received on recipient side. 

https://user-images.githubusercontent.com/97245802/220360860-d9b6b8a6-c609-4a4a-88b6-0e5f0da580d8.mp4

[User_M.zip](https://github.com/status-im/status-mobile/files/10793987/User_M.zip)

**Expected result:** messages should not be delivered to User M as he is not mutual contact to User D **OR** from Desktop perspective it would be correct to disable input field in 1-1 chat with non contact. Fix on Desktop side looks like easier fix and in its turn will provide compliance between desktop and mobile UI for such case. 

### Additional Information

- Status mobile version: release/1.21.x
- Operating System: Android, iOS

- Status Desktop version 0.10.0 https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.10.x/10/

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
> I'd hold on for this one, until things have settled, seems like for now we want to err on the side of allowing users to communicate instead of preventing communications

https://github.com/status-im/status-go/pull/3311#issuecomment-1474116568
