### ISSUE TITLE
image issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15154]
## ISSUE 1: The opened Image is not able to be closed when [x] is tapped if current image is double tapped
**Steps to reproduce:**
1. Go to any chat
2. Send the image
3. Open the image and immediately tap it several times
4. Tap the [x] to close

**Actual result:**
The image is not able to be closed

https://user-images.githubusercontent.com/52490791/220408253-bf61362b-739e-4541-b236-fd14f075dfe2.mp4

**Expected result:**
Image is able to be closed when [x] button is tapped

**Additional info:**
Repeat steps several times if it is not reproduced firstly as it is shown on the record

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: No ability to reply with an image 
**Steps to reproduce:**
1. Go to any chat
2. Sent the message
3. Long tap the message -> tap 'reply' option -> attach the image
4. Tap 'send' button

**Actual result:**
The image is shown as a separate message

https://user-images.githubusercontent.com/52490791/220424838-07785378-ae50-4487-afd2-c79a45313ab8.mp4



**Expected result:**
The image is shown as reply

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: The non-compressed chatkey is shown instead  "3 random name" of mentioned user if the message is sent with a mention and with an image
**Steps to reproduce:**
1. Go to any chat
2. Attach the image to the textbox (don't sent the message yet)
3. Mention some user in the textbox
4. Send the message

**Actual result:**
The non-compressed chat key is shown instead of the mention

https://user-images.githubusercontent.com/52490791/220427149-5750cc52-5896-41a9-8f61-bdfdb11f312e.mp4

**Expected result:**
The image and mentioned "3 random name" is shown in the message

**Comment by VolodLytvynenko** [comment]
**ENV:** Nightly [21 Feb 2023]

**Comment by OmarBasem** [comment]
Issue 1 is not an issue as that PR https://github.com/status-im/status-mobile/pull/15078 implements gestures for images. Tapping quickly like this would zoom in and out.

**Comment by VolodLytvynenko** [comment]
Please see the comment from @ibrkhalil  before fixing this one https://github.com/status-im/status-mobile/pull/15190#issuecomment-1454684319

> Apparently, When the user edits an image with a photo .. The photo gets lost .. So the team have added a constaint to prevent editing a photo with text on status-go [here](https://github.com/status-im/status-go/blob/999d8c0ee0f2274c58b5a2de3beddab7feaabd16/protocol/messenger_messages.go#L19) .. Happy to investigate in a subsequent issue

## ISSUE 4: The text of the message is not updated after editing if the current message is with an image

#### Steps to reproduce:
1. Go to any chat
2. Send a message that contains some text and an image
3. Long press the message -> Tap 'edit'
4. Update text

#### Actual result:
The text is not updated

https://user-images.githubusercontent.com/52490791/222458375-d7d1ce76-6605-4688-9ccf-5de81c4d2d99.mp4


#### Expected result:
Text is updated

#### Env: 
nightly 2 Mar 2023

**Comment by VolodLytvynenko** [comment]
## ISSUE 5: Single tap opens the image if to tap on the space around the current image

#### Problem: 
sometimes user needs to tap somewhere out to close the opened keyboard, but instead of the keyboard closing the image is opened if to tap on the space surrounding the image (see on the attached record)

#### Steps to reproduce:
1. Send the message with an image
2. Tap on the out-of-the-image space (example: l)

#### Actual behavior:
Single tap works both on the message area (space around the picture - not expected) and on the picture itself (expected)

https://user-images.githubusercontent.com/52490791/222470069-1b8e3f1f-dc72-4884-ac06-22b743c54f04.mp4



#### Expected behavior:
Single tap (to open picture) works on:
- only picture itself

#### Env:
nightly 2 Mar 2023

**Comment by VolodLytvynenko** [comment]
ISSUE 2: created as a follow-up https://github.com/status-im/status-mobile/issues/15318
ISSUE 3: created as a follow-up https://github.com/status-im/status-mobile/issues/15319
ISSUE 5: created as a follow-up https://github.com/status-im/status-mobile/issues/15320
