### ISSUE TITLE
ENS is resolved for a new contact only after receiving a message

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15152]
# Bug Report

## Problem 

A 3-random-name is displayed in the profile of the user who actually has an ENS name even after the users have already become mutual contacts.
The ENS name will be displayed only after receiving a message from the ENS user in any chat (accordingly, if both of you were members of the same community, and the ENS user sent at least one message to a channel, you are able to see the ENS).

**Steps:**
1. UserA: add ENS name in the profile
2. UserB: `Add a contact` > type ENS or paste a profile link like https://join.status.im/u/ditest.stateofus.eth > `View profile` > `Add to contacts`
3. UserA: accept the contact request
4. UserB: check the profile of UserA

#### Expected behavior
- ENS name is resolved after the request is accepted
or
- Is it possible to display the ENS immediately when opening a profile, since the search is performed on an already known ENS?
(Currently, if you search by ENS name/link with ENS, the profile still shows a 3-random-name)

https://user-images.githubusercontent.com/67952253/220414156-97ba48a4-9347-4172-a19d-879fb34c78d9.mp4

#### Actual behavior
Need to receive at least one message from the ENS user to see their ENS

In the video, you can see that the ENS starts displaying after receiving a message in 1-1 chat.

https://user-images.githubusercontent.com/67952253/220414051-4618ab67-f61a-45b4-846d-767afcf217ed.mp4

### Additional Information

- Status version: nightly 21/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
Reproducible again in 1.23

**Comment by churik** [comment]
not reproducible in 2.29
