### ISSUE TITLE
'Unhandled content-type' when sending another message after a photo album

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15151]
# Bug Report

## Problem 
The `Unhandled content-type` error is shown in place of the sent message if you send it immediately after sending a photo album.
The message is displayed fine after reopening the chat.

#### Expected behavior
No error

#### Actual behavior

https://user-images.githubusercontent.com/67952253/220392840-f8f4cbd4-8663-49a4-9910-da0060295277.mp4

### Reproduction

1. Open chat
2. Select several photos in the gallery > Send
3. Send another message without reopening the chat

### Additional Information

- Status version: rc1 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
Hi @briansztamfater,
I am currently working on that issue https://github.com/status-im/status-mobile/issues/14995, and I have noticed that this issue of 'unhandled content type' is not there anymore. So probably nothing needs to be done for this issue.

**Comment by briansztamfater** [comment]
Thanks @OmarBasem, assigned this issue to you and closed my PR.

**Comment by OmarBasem** [comment]
Fixed in: https://github.com/status-im/status-mobile/pull/15208
