### ISSUE TITLE
Toasts are broken

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15165]
Most likely introduced by these changes https://github.com/status-im/status-mobile/pull/15144 which were merged into develop without testing @yqrashawn 

Please, do not hesitate asking @status-im/mobile-qa team for manual testing. Also, all PRs (even those which do not require manual qa) should at least pass e2e tests. 

**Steps:** 
1. Generate any toast within the app (for example undo delete toast)
2. See if toast UI looks correct

**Actual result:** toasts are broken

https://user-images.githubusercontent.com/97245802/220628569-156bea3a-fc71-4f36-b440-24fccb309fc1.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
> Please, do not hesitate asking https://github.com/orgs/status-im/teams/mobile-qa team for manual testing. Also, all PRs (even those which do not require manual qa) should at least pass e2e tests.

ah, sorry for that, will do
