### ISSUE TITLE
User A is not mutually removed from User's B contact list when he (User A) removes User B from contact list

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15179]
@alwx could it be the case that something went wrong during merging into develop of this PR https://github.com/status-im/status-mobile/pull/14853 ? Cause same issue has been fixed by you in that particular PR and fix worked in PR builds. 

**Preconditions:** Users A and B are mutual contacts

**Steps:** 
1. User A removes User B from contacts
2. See if User A has been removed from contacts for User B

**Actual result:** User A remains in contact list for User B

**Expected result:** User A has been mutually removed from User's B contact list

[User_A.zip](https://github.com/status-im/status-mobile/files/10822497/User_A.zip)

[ User_B.zip](https://github.com/status-im/status-mobile/files/10822495/User_B.zip)

https://user-images.githubusercontent.com/97245802/221139978-ee85d71d-3400-43c5-a581-4ab4c531fefd.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
@pavloburykh I don't see how it may be related yet but will check it today (and hopefully submit a fix)

**Comment by pavloburykh** [comment]
@alwx this one as well as https://github.com/status-im/status-mobile/issues/15181 are already fixed in latest nightly. I guess as a result of updating go version.

**Comment by alwx** [comment]
Ok, let's close them then.
