### ISSUE TITLE
Header sizing problem in chat

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15174]
# Bug Report
![Screenshot_2023-02-23-23-45-55-81_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/221101926-e7b4d506-2c11-4fe5-9c15-b32e5b0a1119.jpg)

## Problem 
[comment]: # (A problem description)

### Reproduction

1) Open Status
2) 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
Hey @jo-mut, in file `quo2.components.navigation.page-nav` line 219 `:margin-top 44` shouldn't be there. If you need to add margin for a specific screen, please do it for that specific screen, not globally.

**Comment by jo-mut** [comment]
@OmarBasem yeah. I have made corrections to this. I will create the PR in a short while
