### ISSUE TITLE
The message non-admin user's message is not removed in group chat if 'delete for everyone' option is used

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15182]
#### Steps to reproduce:
1. Create a group chat as User_A (admin)
2. Invite User_B
3. Send the message as User_B
4. Remove the message as User_A using 'delete for everyone' option
5. Check the message as User_B
6. Reopen chat as User_A

#### Actual behavior
The message is shown

https://user-images.githubusercontent.com/52490791/221178636-7636a6a7-afff-413c-a583-e00fa7ad0919.mp4

#### Expected behavior
The message is removed for both users

### Additional Information

- Status version: nightly 24 Feb 2023
- Operating System: Android, iOS

**Comment by yqrashawn** [comment]
@VladimrLitvinenko seems this one is already fixed in dev

**Comment by yqrashawn** [comment]
ah it's group chat, can reproduce, working on it
