### ISSUE TITLE
Add accessibilty-id for options in community

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15187]
# Bug Report

## Problem 
no accessibility-id for community options
**Blocks 702845 e2e**

![image](https://user-images.githubusercontent.com/4557972/221247189-f236e3e5-8881-43c1-855c-af3fb9c9f1fb.png)

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Hey @churik 
I found accessiblity ids for this menu
Is this is the one intended in this PR ?
![image](https://user-images.githubusercontent.com/33176106/221363947-c3b72fb5-5248-4405-8223-7bf581bf2e57.png)

**Comment by flexsurfer** [comment]
сс @churik

**Comment by churik** [comment]
@ibrkhalil 
I'm sorry, somehow I missed the notification!
I need accessibility-id for this ... button.
Thank you, apologies for delay
<img width="188" alt="221247189-f236e3e5-8881-43c1-855c-af3fb9c9f1fb png (1397×823) 2023-03-21 14-34-40" src="https://user-images.githubusercontent.com/4557972/226622204-f604841a-c08f-4ccb-b0a4-d8070394c285.png">
