### ISSUE TITLE
Outgoing contact request does not appear in AC for CR sender

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15181]
Outgoing contact requests feature appeared to be not working in develop after merging https://github.com/status-im/status-mobile/pull/14853 
Feature worked correctly in PR builds. 
Looks like something went wrong during merging **cc** @alwx 

**Steps:** 

1. User A sends CR to User B
2. User A opens AC
3. See if there is an outgoing contact request in AC

**Expected result:** outgoing contact request appeared in AC

**Actual result:** no outgoing contact request in AC

[Status-debug-logs (9).zip](https://github.com/status-im/status-mobile/files/10823570/Status-debug-logs.9.zip)

https://user-images.githubusercontent.com/97245802/221168208-b9407701-b79f-4469-85cb-0ccd63fe99a2.mp4

@alwx  another related problem which appeared after merging outgoing CRs feature into develop is https://github.com/status-im/status-mobile/issues/15179

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Updated status-go should fix the issue.

**Comment by pavloburykh** [comment]
@alwx this one as well as https://github.com/status-im/status-mobile/issues/15179 are already fixed in latest nightly. I guess as a result of updating go version.
