### ISSUE TITLE
The frame is shown on the toasts for android devices

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15198]
Not fully fixed in https://github.com/status-im/status-mobile/issues/14702

**Steps to reproduce:**
1. Make some action that triggers the toast showing (example: send a contact request or join a community group)

**Actual result:**
The toasts are shown with frames inside
![image](https://user-images.githubusercontent.com/52490791/221546774-d5beff83-b5a3-4474-be05-75524aaeedfd.png)

![image](https://user-images.githubusercontent.com/52490791/221543971-fba9d2cc-54d1-47d1-9ea5-5df8cd9cd223.png)

**Expected result:**
The toasts are shown without frame inside
![image](https://user-images.githubusercontent.com/52490791/221547449-dd884837-7f2a-473c-a340-0f85f32d26f3.png)

**Env:**
1. Android studio: pixel 6, version 10
2. Real device: Huawei p20 light

CC: @yqrashawn

**Comment by flexsurfer** [comment]
cc @yqrashawn

**Comment by yqrashawn** [comment]
Currently, I can only test android build on a physical device, it's a OnePlus 5, android 8.1.0. And can't reproduce on that device.
@VladimrLitvinenko could you please check if this ui bug happens in quo2 preview as well.

![Screenshot_20230301-152145](https://user-images.githubusercontent.com/15090582/222072002-04ab1780-3f87-450f-9ebb-7ee3ecc2e2df.jpg)
![Screenshot_20230227-131649](https://user-images.githubusercontent.com/15090582/222072016-1dd3c459-0242-4d21-b6b6-e0d2e67d15ef.jpg)

**Comment by VolodLytvynenko** [comment]
@yqrashawn yes. It is shown on quo2 preview as well for my real device. You can try the emulator android studio: pixel 6, version 10. it is also reproducible there

https://user-images.githubusercontent.com/52490791/222140405-8bdab074-db99-487c-9dad-f2d169175af8.mp4

**Comment by yqrashawn** [comment]
@VladimrLitvinenko is it possible to reproduce this on pixel 6, version 11? version 10 keeps crash on my machine. And I can't reproduce this with version 11.
![Image 2023-4-19 at 19 53](https://user-images.githubusercontent.com/15090582/233066863-64a59b33-47d0-456d-bc2a-934ba2db77af.jpg)

**Comment by VolodLytvynenko** [comment]
hi @yqrashawn curious. This issue is not reproducible anymore. It can be closed
