### ISSUE TITLE
Sometimes App crashes when installed on Andriod emulator (Genymotion)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1520]
### Description

*Type*: Bug

*Summary*: Build  0.9.8-108-g7a3e9a1f+  crashes when installing it on AVD (Genymotion)

#### Expected behavior
I want to be able to install the build on emulator

#### Actual behavior
Application crashed upon start

### Reproduction

- Open any android emulated device (i used Nexus 6P android 6.0 and Galaxy S7 android 7.1)
- Install the 0.9.9d108 build and run it

### Additional Information

* Status version:  0.9.8-108-g7a3e9a1f+ 

* Operating System: Android

**Comment by annadanchenko** [comment]
TestFairy log: https://app.testfairy.com/projects/4803622-status/builds/6214473/sessions/14/?accessToken=WMR2TBZaxZnmPTCstdaapKf4NVg

**Comment by annadanchenko** [comment]
@asemiankevich as discussed: build was installed on top of another develop build that is not a valid case. Need to check update from release 0.9.9 to develop build. If this case does not crash - please, close the issue

**Comment by asemiankevich** [comment]
Closing as invalid
