### ISSUE TITLE
Mentioning by display names issues

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15202]
Followup of https://github.com/status-im/status-mobile/pull/15085

### ISSUE 1 Regular text instead of mention is sent when trying to mention user by display name (reproducible only for some display names)

It is reproducible only with some display names and there are no clear steps or preconditions on how to reproduce that.  Needs to more investigation.

Reproducible for me in communities/1-1 chats/group chats

**Preconditions:** use this user for reproduction. seed phrase: outdoor portion desk extend lend ugly canvas inquiry ski buffalo custom loud

**Steps:** 

1. Recover given above user
2. Tap Community tab
3. Wait until communities are restored
4. Enter "testing release /1.22" community
5. Open any channel in given community
6. Try to mention desktop user Pavlo or Pavlo-test2
7. Observe the result

**Expected result:** it is possible to mention user. 

**Actual result:** Regular text instead of mention is sent. Same happens in 1-1/group chats. 

[Status-debug-logs (7).zip](https://github.com/status-im/status-mobile/files/10813655/Status-debug-logs.7.zip)

https://user-images.githubusercontent.com/97245802/220912277-74881d1d-a1f9-46cb-91cb-57117d8e1056.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
Below ISSUES 2 and 3 are easily observed in Status community after recovering desktop user on mobile 

### ISSUE 2 Most of users in the initial mention list (when you start typing @) are still displayed with 3 random names in Status community

At the same time on desktop all users in mention list are displayed with their names. [video](https://drive.google.com/file/d/1gKeWi8VFswKtQwGlONPqWio7DHZqa3OI/view?usp=share_link)

**Comment by pavloburykh** [comment]
### ISSUE 3 Not all users in Status community are available for mentioning on mobile and at the same time available on desktop

For example, on desktop I see 2 users with name andrey On mobile I see only one. There are a lot of other examples if to go through the whole list of names which is displayed on desktop. 

**Screenshot from mobile**
<img width="397" alt="1_mobile" src="https://user-images.githubusercontent.com/97245802/218833197-1584dd11-5629-44c9-9c83-3a5a34510564.png">


**Screenshot from desktop**
<img width="739" alt="2_desktop" src="https://user-images.githubusercontent.com/97245802/218833226-a4b351aa-a8d7-463f-8937-73fb2cdd2edc.png">

**Comment by flexsurfer** [comment]
blocked by https://github.com/status-im/status-mobile/issues/15220 
cc @qfrank

**Comment by qfrank** [comment]
> blocked by #15220 cc @qfrank

Hi @flexsurfer , i'm still working on the PR for #15220, i think it will be out next Tuesday(more or less).  🙂

**Comment by qfrank** [comment]
> > blocked by #15220 cc @qfrank
> 
> Hi @flexsurfer , i'm still working on the PR for #15220, i think it will be out next Tuesday(more or less). 🙂

update: I'm sorry that the PR get delayed, it would more accurate that say it will get out next week ... draft PR: https://github.com/status-im/status-go/pull/3309

**Comment by qfrank** [comment]
Hi @pavloburykh  , i can't reproduce issue 2-3. for issue 1, maybe because it's been a little long, after "Recover given above user" i can't see the communities.
Can you confirm if issue 1-3 are still reproduceble based on this [PR](https://github.com/status-im/status-mobile/pull/15622)? thank you ❤️

**Comment by pavloburykh** [comment]
> Hi @pavloburykh , i can't reproduce issue 2-3. for issue 1, maybe because it's been a little long, after "Recover given above user" i can't see the communities. Can you confirm if issue 1-3 are still reproduceble based on this [PR](https://github.com/status-im/status-mobile/pull/15622)? thank you ❤️

Hi @qfrank! 

Issues 2 and 3 are still reproducible. Try to restore on mobile your account which is a member of Status community and compare what you see in mention list on mobile and desktop (for example in Status mobile chan). This is the easiest way to reproduce issues 2 and 3. 

Regarding Issue 1 - it was not an easy one for reproduction. This bug appeared randomly on some accounts for some users. I will check it later and provide you with an update. Thanx!

**Comment by qfrank** [comment]
> Issues 2 and 3 are still reproducible.

Hi @pavloburykh , can you provide the exact input?

**Comment by pavloburykh** [comment]
> video

[ISSUE 2](https://github.com/status-im/status-mobile/issues/15202#issuecomment-1446656284)

**Steps:** 

1. Open Status #mobile channel in mobile app
2. Open Status #mobile channel on desktop app
3. Start typing @ to open mention list in mobile and on desktop
4. See if there any 3 random names in mention list in mobile app and on desktop app

**Actual result:** lot of 3 random names in mention list in mobile app which are not displayed/cannot be found in mention list of desktop app

**Expected result:** only display names should be displayed in mention list on mobile app


[ISSUE 3](https://github.com/status-im/status-mobile/issues/15202#issuecomment-1446658434)

**Steps:** 

1. Open Status #mobile channel in mobile app
2. Open Status #mobile channel on desktop app
3. Try to to find ```@carlb``` user in mention list on mobile and desktop

**Actual result:** ```@carlb``` user cannot be found on mobile but can be found on desktop. This is only one example of such display name which exists on desktop and does not exist on mobile. You can go through display names in desktop  mention list and try to find them on mobile. As a result you will see, that a lot of those users cannot be found on mobile.

**Comment by qfrank** [comment]
Have you tried this for status desktop(i assume you are using mac)? I just found something interesting.. 
- rename directory `~/Library/Application\ Support/Status` to `~/Library/Application\ Support/StatusBackup` for status desktop
- recover your account using 12 seedphrase
- try to @ carlb to see if it's in the mention list, my result is i can't see it in my mention list 
@pavloburykh

**Comment by qfrank** [comment]
before above, i found my status desktop can @ James , but i can't find it in mobile, so i checked db in status mobile, and James does not exist in table contact .. then i tried rename status desktop data dir to backup and recovered account using seedphrase,  after login status desktop, James disappeared from mention list.. 😅

**Comment by flexsurfer** [comment]
so it seems like both issues happen because there are no display names in the contacts, they are not fetched, I'm not sure how we sync contacts from communities. so I would say the issue is not related to mentions if you can't see these names in the list of communities as well

**Comment by qfrank** [comment]
yeah, it's not relate to mention, i'm trying to check if the corresponding 3 words names for James exist in community members from recovered account

**Comment by qfrank** [comment]
oh, yeah, it exist. James -> Mediumforestgreen Darkmagenta Armadillo

**Comment by pavloburykh** [comment]
@flexsurfer @qfrank thank you guys. I think it makes sense to close current ticket. The above issues should be adressed as part of addressing the synchronization issues. Regarding ISSUE 1 - as it has appeared randomly and only for some specific display names/accounts I believe we can ignore it for now. I am not able to confirm if this bug still exists because my reproduction user's backed up data has already expired. Will log it separately if we face it in future.
