### ISSUE TITLE
Albums are lost after deleting a message

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15217]
Album images are sorted into separate images after deleting a message. They should stay as albums. See "issue 3" in this comment: https://github.com/status-im/status-mobile/pull/15208#issuecomment-1448467064

@yqrashawn I know you have been working on deleting messages, so I am wondering if you can take care of this issue.

The `albumize-messages` method in `status-im2.subs.chat.messages` would need to be called after deleting a message. But I am not sure where is the best place to call it.

I see that the list of messages is rebuilt after deleting a message (which causes the albums to be lost), but maybe there is a better way of doing it. I see a comment in `status-im2.contexts.chat.messages.list.events` "this is too expensive, probably we could mark message somehow and just hide it in the UI"

Dependency: https://github.com/status-im/status-mobile/pull/15208

**Comment by yqrashawn** [comment]
I'll look into this.

**Comment by OmarBasem** [comment]
Pasting my response here better:

@yqrashawn it is in the `albumize-messages` method in `status-im2.subs.chat.messages`

Also, the image messages needs to be marked with `albumize?` as `true`. This happens in `mark-album` method in `status-im.chat.models.loading`. Not sure if rebuilding the messages list after deleting a message removes this mark.
