### ISSUE TITLE
An accepted contact request notification  is not shown as per design

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15210]
#### Steps to reproduce:
1. USER_A: Send a contact request to USER_B
2. USER_B: Accept contact request
3. USER_A: Check a toast
#### Actual result:
The toast with the [x] mark is shown 
![image](https://user-images.githubusercontent.com/52490791/221820083-d3063e4d-78e2-4705-a3aa-038336792b15.png)

#### Expected result:
A notifification should be shown as per visual
![image](https://user-images.githubusercontent.com/52490791/221837795-b7e52219-786c-4d50-bc3f-925413ba501f.png)

https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=4537%3A515620&t=LG0i2EpRjBM1NP7Z-0

**Devices:**
- Operating System: Android, iOS

**ENV:**
- Nightly 28 Feb 2023

**Comment by rasom** [comment]
@VladimrLitvinenko that looks a bit ugly but I'm wondering whether polishing of `user-avatar` is in scope of this PR

<img width="296" alt="Screenshot 2023-02-28 at 14 09 10" src="https://user-images.githubusercontent.com/2364994/221863589-72be7f04-9a7b-4d23-a73f-0ff1d25b6d59.png">

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko that looks a bit ugly but I'm wondering whether polishing of `user-avatar` is in scope of this PR
> 
> <img alt="Screenshot 2023-02-28 at 14 09 10" width="296" src="https://user-images.githubusercontent.com/2364994/221863589-72be7f04-9a7b-4d23-a73f-0ff1d25b6d59.png">

@rasom Agree with you, this is not in the scope of this PR.  Better to be without avatar for now than with an ugly avatar :)

**Comment by rasom** [comment]
@VladimrLitvinenko no I rather mean whether that avatar should be fixed right here. I think it is better to have it even ugly there, it will be fixed eventually.
