### ISSUE TITLE
Need to tap twice on the name in suggestion mentions list in order to select it (IOS only)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15235]
Reproducible for IOS only. 

**Steps:** 

1. Open any chat
2. Start typing @ in order to open mention list
3. Tap once on any name in the list
4. See if it has been selected i.e.mention has appeared in message input field

**Expected result:** selected mention has appeared in message input field

**Actual result:** need to tap twice on name in order to select it. 

https://user-images.githubusercontent.com/97245802/222472633-f5b61a0e-f52c-4f54-a8b3-5240dc51b705.mp4

### Additional Information

- Status version: nightly 
- Operating System: iOS 14.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Currently, I am working on onboarding, so removing the assignment if anyone wants to pick it up.
If no one will I will give it a try once the onboarding work is complete.
