### ISSUE TITLE
Android header does not animate to the right position, causing a flicker

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15238]
On Android, when navigating to any screen, there is a weird flicker in the header, where it animates beyond its position, then goes back.

Device: Samsung Galaxy Note 10 Lite
Android version: 11

https://user-images.githubusercontent.com/29354102/222668111-316a4d17-cf3c-44ff-b9e5-2547862ee213.mp4

**Comment by cammellos** [comment]
this probably need to be re-evaluated in the scope of the new chat header
