### ISSUE TITLE
Bottom sheet sometimes gets stuck when opening in chat view (Android)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15265]
# Bug Report

## Problem 

The bottom sheet on Android devices sometimes gets stuck just starting to open in this state:

<img width="315" alt="Screenshot 2023-03-06 at 09 19 36" src="https://user-images.githubusercontent.com/67952253/223055069-0c00d263-90f0-4bec-8934-861c67b3c255.png">

Here is logfile for the screenshot above. Event should be somewhere at the very beginning of log history. 
[Status-debug-logs (17).zip](https://github.com/status-im/status-mobile/files/10896096/Status-debug-logs.17.zip)

In the slow-mo video, you can see, that the animation is a bit laggy at this moment, and for some reason, the bottom sheet remains at the point of slowing down. 

https://user-images.githubusercontent.com/67952253/223055560-99717998-54aa-4fca-bedd-178565b56aae.mp4

### Reproduction

The exact steps to reproduce, unfortunately, have not yet been found. 

### Additional Information

- Status version: nightly 6/03
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
To add to this issue, on my device it happens 100% of the time:

Device: Samsung Galaxy Note 10 Lite
Android version: 11

https://user-images.githubusercontent.com/29354102/223073972-786072cb-c3d8-488b-9689-208e8b842ed3.mp4

**Comment by OmarBasem** [comment]
To add to this issue, on my device, it does not happen sometimes, but 100% of the time.

Device: Samsung Galaxy Note 10 Lite
Android version: 11


https://user-images.githubusercontent.com/29354102/223074574-a065d3ba-cc34-486c-a2d4-ea9c066170fc.mp4

**Comment by flexsurfer** [comment]
also status bar style is wrong

**Comment by flexsurfer** [comment]
> To add to this issue, on my device, it does not happen sometimes, but 100% of the time.
> 
> Device: Samsung Galaxy Note 10 Lite Android version: 11

@OmarBasem could you pls elaborate what happens, its not clear from you video, what exactly is wrong, thanks

**Comment by flexsurfer** [comment]
your issues that it doesn't animate to the end ?

**Comment by OmarBasem** [comment]
@flexsurfer The same issue posted by Diana, but I am saying that it happens for me always, not just sometimes.

The bottom sheet does not start the animation from the very bottom, but a little above that, and it ends the animations a little above that also. Isn't that the issue being reported @qoqobolo ?

**Comment by flexsurfer** [comment]
thanks
