### ISSUE TITLE
Updating status bar using merge options not working on iOS

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15260]
When trying to update the status bar `style` from the `shell-stack` using `mergeOptions` on iOS, nothing happens. 

Probably that's why the status bar on iOS is black when the home screens are minimized. 

Updating the status bar the same way from a nested screen works as expected. Also, updating other options using `mergeOptions` from the `shell-stack` works as expected.

**Comment by Parveshdhull** [comment]
Hi, @OmarBasem Thank you for creating issue.

### Adding for context

Related comment: https://github.com/status-im/status-mobile/pull/14811#issuecomment-1400949792
Related Issue: https://github.com/wix/react-native-navigation/issues/5446

**Comment by Parveshdhull** [comment]
related issue: https://github.com/status-im/status-mobile/issues/17636

**Comment by ilmotta** [comment]
Closing because the issue description is not actionable (unclear what to do) and improvements/fixes to the status bar were applied since the issue creation.
