### ISSUE TITLE
Implement Blur versions of Status Tags in Quo2 component library

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15267]
Currently the Status Tags component in quo2 do not support the dark blur variants as in the designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2219%3A32360&t=pBwgLVK8a4A5mjDi-0

Implement the dark blur variant as seen in the Figma files and update the uses of this component where necessary in the application.
Some of these are in the Activity Centre.
Provide a demo in the preview screens

**Comment by J-Son89** [comment]
cc @alwx @ilmotta @smohamedjavid

**Comment by ilmotta** [comment]
Thanks @J-Son89. I added the Activity Center label to help us not forget to update the tags there.
