### ISSUE TITLE
The avatar ring displaying issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15271]
Follow-up related to https://github.com/status-im/status-mobile/pull/15036

#### Steps to reproduce:
1. Don't set ENS for users
2. Don't set images for the profiles of the users
3. Send a message in any chat

#### Actual result:
The ring is not shown for the user avatar on the opened chat if the profile image is not added
![image](https://user-images.githubusercontent.com/52490791/223117543-50beca8e-8cfe-4848-8fb8-ed52dc269f81.png)

#### Expected result:
The ring is shown inside the chat if the user didn't set the image for the profile
![image](https://user-images.githubusercontent.com/52490791/223123841-6579065d-3d0b-4fd4-9dca-0d2f059c4546.png)

#### Additional info:
1. Current logic should work for such places where the user's avatar is shown:
  - Profile page 
![image](https://user-images.githubusercontent.com/52490791/223126973-630c8c51-5d60-49a6-823d-dc67e8f21b32.png)
  - Contacts adding page
![image](https://user-images.githubusercontent.com/52490791/223127563-5244f9d7-2c09-4102-b5df-603bec9cb8da.png)

2. Current ring should be shown if the user has:
  - Nickname (able to be set in the mobile app)
  - Name (able to be set on desktop)
  - 3 random name

#### Preconditions:
1. User_A with ENS name

#### Steps to reproduce:
1. log in as a user with a set ENS name (you can use the following user with ENS <volodymyr.eth>. Can be recovered with this seed phrase: spike spoil hidden sad juice force trap bind situate consider suit demand)
2. Set the image into the profile
3. Send a message into 1-1 chat
4. Check the following pages:
- Profile page
- Avatar inside the opened chat

5. As User_B: Check chat avatar (shown for user receiver of the message)

#### Actual result:
The ring is shown surrounding the user's avatar if the current user is with ens and with the set profile image on the following places:
- Profile page
![image](https://user-images.githubusercontent.com/52490791/223160119-cee96f56-fad8-4c28-9d16-36010a3cb1de.png)

- Chat avatar
![image](https://user-images.githubusercontent.com/52490791/223164568-0d26baf9-74d9-46a2-bcf5-a3c9c5b088cf.png)

- Avatar inside the chat:
![image](https://user-images.githubusercontent.com/52490791/223165253-73938881-95d0-4adc-9d77-4a74d2c733fc.png)

#### Expected result:
The ring is not shown surrounding the user's avatar if the current user is with ens (no matter if an image is set or not for current user profile)

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac. The current follow-up I've created is based on the design team's reply
![image](https://user-images.githubusercontent.com/52490791/223166861-24a0d88a-f2b9-4f99-8ab8-af6543de62ca.png)

**Comment by ulisesmac** [comment]
> hi @ulisesmac. The current follow-up I've created is based on the design team's reply
> ![image](https://user-images.githubusercontent.com/52490791/223166861-24a0d88a-f2b9-4f99-8ab8-af6543de62ca.png)
> 

Thank you very much for creating this issue @VladimrLitvinenko 

I think we have a problem, when we request the profile picture, the ring is *already* drawn over the image returned, so we need to isolate the ring.

@cammellos What do you think? Do we need to create some extra issues before taking this one?

**Comment by cammellos** [comment]
@ulisesmac if the issue is only that we should not display the ring on top of the image if there's an ENS name, that can be done in status-go easily, we can just check there if there's an ENS name, and don't apply the ring, is that the only concern?

**Comment by ulisesmac** [comment]
> @ulisesmac if the issue is only that we should not display the ring on top of the image if there's an ENS name, that can be done in status-go easily, we can just check there if there's an ENS name, and don't apply the ring, is that the only concern?

@cammellos  ok! yes, only that's the problem to solve in status-go (it's the issue 2 mentioned by @VladimrLitvinenko )

I can solve the other ring issue (issue 1) related to the mobile app.

**Comment by J-Son89** [comment]
@ulisesmac - maybe you should align with @yqrashawn on this. Perhaps you have not seen -> https://github.com/status-im/status-mobile/issues/15751

**Comment by ulisesmac** [comment]
> @ulisesmac - maybe you should align with @yqrashawn on this. Perhaps you have not seen -> https://github.com/status-im/status-mobile/issues/15751

@J-Son89 
@yqrashawn is fixing it (and alao this issue) in this PR: https://github.com/status-im/status-mobile/pull/16193

Thanks 👍
