### ISSUE TITLE
Mentions turn into @Unknown during editing of messages containing mentions in communities

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15276]
**Steps:**

1. Open community channel
2. Send a message containing mention
3. Longtap on message => Edit message
4. Pay attention at mention in message

**Actual result:** mention turns into \@Unknown\ during editing of message

[Status-debug-logs (18).zip](https://github.com/status-im/status-mobile/files/10908207/Status-debug-logs.18.zip)

https://user-images.githubusercontent.com/97245802/223390594-e3c80a34-ba4f-4731-9508-d2e52981c5c6.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, Thank you for finding this issue. I am also facing two more issue related to mentions, please let me know if they are known.
1. Community admin not able to mention members (community created on mobile)
2. Members list is showing only 1 member even after joining

**Comment by pavloburykh** [comment]
@Parveshdhull thank you! 

This one 
> 1. Community admin not able to mention members (community created on mobile)

is logged here https://github.com/status-im/status-mobile/issues/14956

This one will check and log it. Thank you for finding. 
> 2. Members list is showing only 1 member even after joining

**Comment by pavloburykh** [comment]
> @Parveshdhull thank you!
> 
> This one
> 
> > 1. Community admin not able to mention members (community created on mobile)
> 
> is logged here #14956
> 
> This one will check and log it. Thank you for finding.
> 
> > 2. Members list is showing only 1 member even after joining

Oh, those are related bugs. Second is rootcause of the first. Will edit https://github.com/status-im/status-mobile/issues/14956

**Comment by pavloburykh** [comment]
@Parveshdhull JFYI those bugs are reproducible only for open type communities.

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, I found another issue that in 1-1 chat when editing message with display name, it turns into 3 words name. (Is this known?)
Also fixed in https://github.com/status-im/status-mobile/pull/15285

**Comment by pavloburykh** [comment]
> Hi @pavloburykh, I found another issue that in 1-1 chat when editing message with display name, it turns into 3 words name. (Is this known?) Also fixed in #15285

@Parveshdhull thanx a lot. Not sure that it was known and logged. Thanx for finding and fixing.
