### ISSUE TITLE
New intro screen graphical glitch

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15270]
There is a slight graphical issue with the color behind the artwork. Isnt that supposed to be black to fit in with the starry sky?

![Screenshot_2023-03-06-09-35-08-80_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/223160290-dd6f525b-9a3c-4645-9507-be3902d611b1.jpg)

**Comment by flexsurfer** [comment]
cc @J-Son89

**Comment by Parveshdhull** [comment]
will be fixed in https://github.com/status-im/status-mobile/issues/15274

**Comment by J-Son89** [comment]
Thanks @du64!
