### ISSUE TITLE
Users are not removed from each other's contact list after blocking

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15279]
#### Preconditions:
1. User_A and User_B are contacts

#### Steps to reproduce:
1. go to the contacts list as User_A
2. open the profile of User_B
3. Tap 'block' button -> Block the contact
4. Go to the list of contacts as User_A
5. Go to the list of contacts as User_B

#### Actual result:
User_B and User_A are still shown in the contact list for each other

https://user-images.githubusercontent.com/52490791/223477299-088c3336-89b7-4d56-8c35-36eb6a3318fc.mp4

#### Expected result:
User_B and User_A are not shown in the contact list for each other after blocking

#### Additional info:
The contact is not shown in the list of contacts only after  relogin

#### ENV:
 Nightly: 7 Mar 2023

**Comment by pavloburykh** [comment]
**UPDATE:** same behaviour in case of removing user from contacts. cc @jo-mut @VladimrLitvinenko
