### ISSUE TITLE
Uncompressed chat key is displayed instead of mention  in message preview within Shell tab

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15277]
**Steps:**

1. Open any chat
2. Send message containing mention
3. Tap "Jump to" button to open Shell screen
4. Pay attention at  message preview within closed chat tab

**Expected result:** mention is displayed in message preview

**Actual result:** Uncompressed chat key is displayed in message preview

![photo_2023-03-07 12 23 22](https://user-images.githubusercontent.com/97245802/223394654-7141ac24-7808-4287-b41a-2bc6bb4779e9.jpeg)

https://user-images.githubusercontent.com/97245802/223394661-e6fb10a4-0dc9-4c05-874c-1c9c14a5aeea.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
blocked by https://github.com/status-im/status-mobile/issues/15220
