### ISSUE TITLE
Wallet design - Token data screens

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1528]

**Comment by sla-shi** [comment]
@sla-shi follow up with Denis to provide Zeplin links for each Wallet UI issue.

**Comment by denis-sharypin** [comment]
@GustavoNunes All UI screens are here zpl://screen?pid=5863cdcee68455850f1929f2&sid=5991fb08dd2ec4ce5e3978c5

**Comment by asemiankevich** [comment]
@goranjovic Do we need this issue?

**Comment by goranjovic** [comment]
@asemiankevich No, it's replaced by the new more specific issues now. Closing
