### ISSUE TITLE
Add icons to all swipe buttons

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15287]
# Feature Issue

Swipe buttons should always have an icon, and optionally text. The text should only be displayed if there's enough room.

But not all icons have been defined in [Figma Shell](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=6105-546987&t=EIM0OQhjnArzVOmz-0), so double-check with designers.

This issue is currently blocked by the unmerged PR https://github.com/status-im/status-mobile/pull/15284.

List of swipe buttons implemented:

- Admin: accept and decline.
- Contact request: accept, decline, and cancel.
- Identity verification: decline, write reply, mark as untrustworthy, and mark as trusted.
- Membership: accept or decline private group chat invitation

### Example where the text doesn't fit the available width

In the image below, only the icon for _untrustworthy_ should be displayed, not the text because it's too long to fit.

![image](https://user-images.githubusercontent.com/46027/223685901-f59610a6-e83f-4d02-8fcd-e1f650b164b9.png)

**Comment by cammellos** [comment]
This has been done I believe, feel free to reopen if necessary
