### ISSUE TITLE
`reagent.core/with-let` is not being aligned as `clojure.core/let`

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#15283]
# Problem
`reagent/with-let` is not being aligned as `clojure.core/let` when we execute `make lint-fix`

## Acceptance Criteria

`reagent/with-let` is correctly aligned

**Comment by ilmotta** [comment]
@ulisesmac, this diff seems to solve the problem for me. Could you double-check on your editor if it's well formatted too?

```diff
modified   .zprintrc
@@ -1,32 +1,33 @@
   "h/test"          :arg1-body
   "global.describe" :arg1-body
   "global.test"     :arg1-body
+  "with-let"        "let"
   "list-comp"       :binding
   "defview"         :arg1-body
```

**Comment by ulisesmac** [comment]
> @ulisesmac, this diff seems to solve the problem for me. Could you double-check on your editor if it's well formatted too?
> 
> ```diff
> modified   .zprintrc
> @@ -1,32 +1,33 @@
>    "h/test"          :arg1-body
>    "global.describe" :arg1-body
>    "global.test"     :arg1-body
> +  "with-let"        "let"
>    "list-comp"       :binding
>    "defview"         :arg1-body
> ```


@ilmotta  Yes! it solves the problem! :) Will you create a PR with this small change? I could create it too if you want.

**Comment by ilmotta** [comment]
> @ilmotta Yes! it solves the problem! :) Will you create a PR with this small change? I could create it too if you want.

Great @ulisesmac! Please feel free to create one or update the config in your next PR (to avoid a separate PR), totally up to you! And btw, if you found any weirdly formatted Clojure, please share with us or open more issues like this one since zprint was just recently introduced and there may be some rough edges.
