### ISSUE TITLE
Messages preview issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15281]
## ISSUE 1: The specific messages content is not shown as per the design on the chat preview if a user himself sends some content and checks it in the preview
**Steps to reproduce:**
1. Go to 1-1 or group chat
2. Send a message that contains the following content and recheck the preview page after each listed content sending:
 -  Text
  - Image 
  - image with text
  - Reply
  - Mention
  - Pinned message

**Actual result:**
For all cases the 'you' is not shown at the beginning of the preview if user sends messages himself and checks them

1. Text: a message text is shown on the preview
![image](https://user-images.githubusercontent.com/52490791/223500314-e03d629a-edec-4f3f-964e-3e39c2346fa0.png)
2. Image: 'placeholder' message is shown on preview if the image is sent
![image](https://user-images.githubusercontent.com/52490791/223498409-426c18d4-6fdf-4d8c-88f5-44f34aa940dd.png)
3. Reply: just a text is shown 
![image](https://user-images.githubusercontent.com/52490791/223498885-e15af9b8-e684-49a8-a19e-e31941f51d5e.png)
4. Mention: the mentioned user is shown without '@' in the begging
![image](https://user-images.githubusercontent.com/52490791/223498546-5681f53e-edb4-4d54-bad3-23e57d557f45.png)
5. Pin a message: A content of a pinned message is not shown
![image](https://user-images.githubusercontent.com/52490791/223498299-65e518aa-94b0-4e1a-bcbb-836990cdf0d5.png)

**Expected result:**
The preview should be shown in format "You <content>" if a user sends the message yourself
1. Text 
![image](https://user-images.githubusercontent.com/52490791/223492481-735f9f82-8b41-4dab-aa2d-891a1e4c0e22.png)
2. Image: The count of images is shown
![image](https://user-images.githubusercontent.com/52490791/223492616-2ad35a1c-4a86-422a-8d77-bcdfed35dc09.png)
3. Image with the text: The count of images and text is shown
![image](https://user-images.githubusercontent.com/52490791/223501919-b9a7add1-eb2c-4669-b0d9-47e9d2c1f082.png)

4. Reply: 'You replied: <text content>' is shown
![image](https://user-images.githubusercontent.com/52490791/223492905-b47952d9-4f4e-412f-9758-9ba17fbda20e.png)
5. Pinned: You pinned: <text content> is shown if the current last message is pinned by the current user
![image](https://user-images.githubusercontent.com/52490791/223492792-c37a35c2-f229-44e5-98c1-5ebb7d65f001.png)
6. Mention: the '@' is shown if a particular user is mentioned
![image](https://user-images.githubusercontent.com/52490791/223493787-d5888d31-e282-4828-9d92-4e52e9052f9a.png)

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: The specific messages content is not shown as per the design on the chat preview if a user receives some content from a sender and checks it in the preview
#### Preconditions:
User_A and User_B are mutual contacts

#### Steps to reproduce:
1. Go to 1-1 or group chat
2. Send a message as User_B (sender) that contains the following content and recheck the preview page as User_A (receiver) after each listed content sending:
- Text
- Image
- image with text
- Reply
- Mention
- Pinned message

####  Actual result:
The following content is not shown as per the design on the chat preview page for the following sent content:
- Text
- Image
- image with text
- Reply
- Mention
- Pinned message

#### Expected result:
The content on the chat preview page is shown as per the design.
The the following content should be implemented:
- Text
- Image
- image with text
- Reply
- Mention
- Pinned message
![image](https://user-images.githubusercontent.com/52490791/223506241-eedb2442-fb15-4cd9-bf96-7f00ec20d392.png)
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=0%3A1&t=sQ1AQY8Jm9QeY8Z7-0

**Comment by vkjr** [comment]
The issue with a preview of pinned messages was extracted to #15683 due to complexities with implementation.
