### ISSUE TITLE
Remove images in edit message

### ISSUE THREAD

**Issue by mariocnovoa** [status-im/status-react#15298]
# Feature Issue

Remove images in edit message

### User Story

As a user, I want to delete an image when I'm editing a message. 

### Description

When the user edits a message that has photos attached to it, the user can add or remove images from the message.

<img width="1508" alt="Screenshot 2023-03-09 at 12 02 34" src="https://user-images.githubusercontent.com/47601204/224004864-d38ad17c-55ca-483c-ae5e-dad9fa4dcae2.png">

### Notes
Link to Figma:
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=7683%3A497438&t=pdx4DyKlnb3w7d6B-1

**Comment by yqrashawn** [comment]
related https://github.com/status-im/status-mobile/issues/15444

Note: 
Currently, we don't allow edit image content type message (guard at status-go at https://github.com/status-im/status-go/blob/48eb7052848a17ab7f972112a3653f0b4cc8537a/protocol/messenger_messages.go#L36)
To implement this. We need to handle both text and image changes in `Messenger.EditMessage`

The `:content-type` in `send-edited-message` in status-mobile should also be changed.

**Comment by cammellos** [comment]
this would be post mvp, closing for now
