### ISSUE TITLE
Wallet design - Portfolio Value Overview (a screen with a graph)

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1529]

**Comment by denis-sharypin** [comment]
It is here zpl://screen?pid=5863cdcee68455850f1929f2&sid=5991fb488fea42dc85f90b5e
Third screen from the bottom.

**Comment by asemiankevich** [comment]
@jeluard @denis-sharypin I assume we can close it?

**Comment by jeluard** [comment]
No we don't. Closing.
