### ISSUE TITLE
Messages fail to send around midnight

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15299]
Around midnight, messages always fail to send.
This problem seems to occur only around midnight, it works during the day usually.

https://user-images.githubusercontent.com/65834069/224237182-92e9598a-8218-41c4-ac76-e7cc2404ecc7.mp4

**Comment by flexsurfer** [comment]
thats interesting cc @churik @cammellos

**Comment by churik** [comment]
@du64 😯 
sorry, this is bizarre :)
Can I ask you to specify the phone model, OS, and time zone?

Also would be really helpful if you can post logs (to have them you need to shake your device and send them to email or Profile > Need help > Submit a bug) and the build that you've installed.
Thank you!

**Comment by flexsurfer** [comment]
hey @du64 whats the red `2kbps` on the top ? internet connection? why is so bad , might be a reason

**Comment by du82** [comment]
@churik My phone is OnePlus Nord N20 5G Chinese version. Logs are broken on the nightly build...

@flexsurfer It's always like that, it sends during the day with 1 kbps just fine

**Comment by cammellos** [comment]
Closing until we add replication steps that are actionable
