### ISSUE TITLE
Nightly builds not up to date

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15293]
The nightly builds aren't up to date anymore. might be worth checking

**Comment by Parveshdhull** [comment]
cc: @jakubgs

**Comment by Parveshdhull** [comment]
Current available [nightly build](https://status.im/nightly/) is updated on `2023/03/02` and has commit hash [7d9709](https://github.com/status-im/status-mobile/commit/7d9709ee678de416151286be93a88f3afb1f4ed0)

**Comment by flexsurfer** [comment]
that's intentional, develop under active development and we don't want to publish such version, if someone wants to try it on own risk it can be done from the CI

**Comment by flexsurfer** [comment]
actually i didn't know we publish it, so worth checking, cc @churik

**Comment by jakubgs** [comment]
Fixed. `status.im` site repo permissions changed and CI could not push to `gh-pages` branch.

**Comment by Parveshdhull** [comment]
Hi @jakubgs, Looks like nightly builds are again not updating. Please can you check.
(Last update - 2023/03/21)

**Comment by churik** [comment]
yes, as IOS could not built for already a week

**Comment by Parveshdhull** [comment]
closing as duplicate https://github.com/status-im/status-mobile/issues/15531
