### ISSUE TITLE
[IOS] White flickers are displayed in the right part of screen when creating a community, navigating to a community or channels on the dark mode

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15308]
#### Steps to reproduce:
1. Go to the communities list page -> tap [+] -> Communities
2. Open any created community from the communities list page
3. Open any channel created inside the community

#### Actual result:
White flickers are shown in the right part after each step from "Steps to reproduce" section

https://user-images.githubusercontent.com/52490791/224326629-a2048b43-4363-4d2e-b048-a92a12dede5c.mp4

https://user-images.githubusercontent.com/52490791/224326653-ee51fab0-7c47-4517-b0ba-2b60a5b3ebc7.mp4

#### Expected result:
White flickers are not  shown

#### Device:
- iPhone 11 Pro max, v16

#### ENV:
- Nightly: 10 Mar 2023

**Comment by churik** [comment]
Replaced by skeleton, obsolete issues, reopen is still makes sense from your POV
