### ISSUE TITLE
The non-compressed chatkey is shown instead  "3 random name" of mentioned user if the message is sent with a mention and with an image

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15319]
#### Steps to reproduce:
1. Go to any chat
2. Attach the image to the textbox (don't send the message yet)
3. Mention some user in the textbox
4. Send the message

#### Actual result:
The non-compressed chat key is shown instead of the mention

https://user-images.githubusercontent.com/52490791/220427149-5750cc52-5896-41a9-8f61-bdfdb11f312e.mp4

#### Expected result:
The image and mentioned "3 random name" is shown in the message

#### Env:
nightly 2 Mar 2023

**Comment by churik** [comment]
the same as https://github.com/status-im/status-mobile/issues/15902, closing
