### ISSUE TITLE
Image is shown as a separate message if current image is sent as a reply

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15318]
#### Steps to reproduce:
1. Go to any chat
2. Sent the message
3. Long tap the message -> tap 'reply' option -> attach the image
4. Tap 'send' button

#### Actual result:
The image is shown as a separate message

https://user-images.githubusercontent.com/52490791/220424838-07785378-ae50-4487-afd2-c79a45313ab8.mp4

#### Expected result:
The image is shown as a reply

#### Env: 
Nightly: 13 Mar 2023

**Comment by yqrashawn** [comment]
`(and (seq response-to) quoted-message)` is `nil` at https://github.com/status-im/status-mobile/blob/972347963498fc4a2bb8f85541e79ed0541698da/src/status_im2/contexts/chat/messages/content/view.cljs#L116

---

design at https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2839-282772&t=ZVQziJH7LMzqDIKH-4

---

empty from status-go as well, check
- [ ] reply action in status-mobile
- [ ] reply action in status-go
