### ISSUE TITLE
UI freezes when changing theme in profile, clicking on tabs opens wrong screens

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15310]
UPD: more details in the comments below

---

Currently there are no clear steps how to reproduce the bug. Having an assumption that it is somehow related to user with enabled PNs. Bug has been reproduced on Android after opening app that has been backgrounded for a while, right after receiving PN. Needs further investigation. 

For now, I attached video and logs. 

Below video demonstrates 2 issues:

1. Wallet bottom sheet opens on tapping on AC icon
2. Buttons/elements on community screen are not responding

[Status-debug-logs (22).zip](https://github.com/status-im/status-mobile/files/10945929/Status-debug-logs.22.zip)

https://user-images.githubusercontent.com/97245802/224423679-dfc23719-21f8-4abd-adb5-bf6ce00cbcb2.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
@pavloburykh is it still reproducible on you side? Again I can't reproduce it

**Comment by pavloburykh** [comment]
> @pavloburykh is it still reproducible on you side? Again I can't reproduce it

@rasom it is not easy to reproduce, we (QA team) still need to investigate steps. I hoped that meanwhile something will be clear out of attached logs. If not - then it is better to hold on until we find steps of reproduction.

**Comment by Parveshdhull** [comment]
**For reference:** This bug might be related to our current implementation of bottom tabs. As can be seen in [code](https://github.com/status-im/status-mobile/blob/46351543f10f588ed877ad7233074531303b7faf/src/status_im2/contexts/shell/home_stack.cljs#L26), we control selected tab by changing opacity and pointer-events.

Not sure, but from video it looks when we press bottom tabs fast enough only opacity is changed and pointer events not get updated or updated wrong.

**Comment by Parveshdhull** [comment]
> Bug has been reproduced on Android after opening app that has been backgrounded for a while, right after receiving PN.

Or restarting of app reinitialized those opacity and pointer events wrong

**Comment by qoqobolo** [comment]
**Steps to reproduce:**

1. Open profile
2. Change the device theme
3. Close profile

More details on the behavior:

At first, UI is completely frozen except for the bottom tabs, but if you click on the wallet tab and then go back to the home screen and tap on the profile many times, the keyboard will open.
Also, after that, you can click on any button on the community or chat screen (i.e. `Discover` or tabs `Joined`, `Pending`, etc.), after which the BROWSER will open, and after that UI starts working normally again.

https://user-images.githubusercontent.com/67952253/234538331-914e79f6-b822-4357-9f0d-a06e01016529.mp4
