### ISSUE TITLE
Swipe notification buttons stop responding at some moment in AC

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15311]
Unfortunately there are no clear steps how to reproduce the bug. Issue will be updated as soon as we find out the steps and other details.

Below video and logs are taken from https://github.com/status-im/status-mobile/pull/15216 were this issue has been reproduced for the first time.

[Status-debug-logs (15).zip](https://github.com/status-im/status-mobile/files/10872373/Status-debug-logs.15.zip)

https://user-images.githubusercontent.com/97245802/222459234-b7d8fce8-5e57-4928-88f0-21a03366a7fc.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
@pavloburykh - Is this bug still reproducible?
