### ISSUE TITLE
App gets stuck on splash screen and crashes (IOS)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15312]
Might be introduced by https://github.com/status-im/status-mobile/pull/15127 **cc @J-Son89** 

Several app re openings might be needed to reproduce the bug

**Steps:** 

1. Install app
2. Open app
3. Close and reopen app
4. Keep closing/reopening until app gets stuck on splash screen.  
5. After app gets stuck on splash screen wait for a while to observe a crash

https://user-images.githubusercontent.com/97245802/225270451-48b39fe9-d8da-4961-b727-d0e607bbd887.mp4

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@pavloburykh
would you mind to re-check the issue when you get a chance?
Thank you!

**Comment by pavloburykh** [comment]
@churik @Parveshdhull I am not able to reproduce the issue any more. If this issue still exists and you consider it to be related to https://github.com/status-im/status-mobile/issues/15826 feel free to re-open it with new description and reproduction steps. For now I believe current issue can be closed.
