### ISSUE TITLE
Implement onboarding switch profile flow - New design

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#15316]
### Summary

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4357%3A629599&t=HiVnD7azwfXkSsP3-0

The issue is to track the implementation of the switch profile flow for the new onboarding design.
The switch profile and App unlock flow are very similar, so we should use the same implementations from the App locked screen.

**Comment by Parveshdhull** [comment]
App unlock flow: https://github.com/status-im/status-mobile/issues/15137

**Comment by churik** [comment]
closing in favor https://github.com/status-im/status-mobile/issues/21476
