### ISSUE TITLE
'Recipient address must be specified' error when manually composing 'send' or 'request' message

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1531]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to transfer ETH by using the 'send' command.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: <Bug>

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When composing a '/send' command manually it gives you the right suggestions and looks the same as if you autocomplete '/send', but instead you get a 'recipient address must be specified' error.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Transfer to happen or "insufficient funds..." error.

#### Actual behavior
[comment]: # (Describe what actually happened.)
 'recipient address must be specified' error.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Chat with Jarrad
- Type "/send", click Jarrad, write 1, press enter
- Observe error

Compare:
- Type "/se", autocomplete by clicking suggestions, click Jarrad, write 1, press enter
- Transaction goes through or "insufficient funds" error.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Same behavior for send regardless if you type "/send" manually or not
- [ ] Don't show transaction amount suggestion if address hasn't been parsed

### Additional Information
* Status version: latest develop
* Operating System: <Android> (simulator)

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb 

Video: https://drive.google.com/file/d/0B9qqS9eU_SdpWi0wTkR0ZmhUeWs/view?usp=sharing
https://gist.github.com/oskarth/50d20ff10e52043d129487974699d058

**Comment by oskarth** [comment]
Preliminary investigation shows two different code paths being hit.

1) Good case: `/sen` and press `/send` suggestion to autocomplete
2) Bad case: `/sen` and press `d` then `space`

In the good case, we hit select-chat-input-command which clears the bot db.

## Event logs

```
GOOD CASE:
Handling re-frame event:  :select-chat-input-command
CHAT-INPUT-CMD, WILL CLEAR BOT DB
Handling re-frame event:  :set-chat-input-text
Handling re-frame event:  :clear-bot-db
Handling re-frame event:  :set-chat-input-metadata
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :load-chat-parameter-box
Handling re-frame event:  :chat-input-focus
Handling re-frame event:  :update-suggestions
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :set-expandable-height
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :update-text-selection
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :load-chat-parameter-box
:call-jail :jail-id 0x0428c9d6c1aaaa8369a7c63819684f30e34396dc0907d49afeac85a0a774ccb919b3482097d992e66bcc538e7a0c6acf874c77748f396f53c0a102e10d1a37765b
:call-jail :path [:commands "send" :params 0 :suggestions]
:call-jail :params {:parameters {:args (), :bot-db nil, :seq-arg nil}, :context {:data nil, :from "50b1bf979b9d5b13efeee623e0a0102b45abf200", :to "323a7fd769a0f106d6b41232b10c44064bb4be88"}}
{:result {:context {}, :messages [], :returned {:markup ["choose-contact" {:bot-db-key "recipient", :index 0, :title "Choose recipient"}], :title "Send transaction"}}}
Handling re-frame event:  :received-bot-response
****SUGG HANDLER DB [recv-bot-resp]
nil
Handling re-frame event:  :suggestions-handler
Handling re-frame event:  :choose-predefined-expandable-height
Handling re-frame event:  :set-in
Handling re-frame event:  :set-expandable-height
Handling re-frame event:  :set

BAD CASE:
Handling re-frame event:  :check-sync
Handling re-frame event:  :update-sync-state
Handling re-frame event:  :set
Handling re-frame event:  :set-chat-input-text
Handling re-frame event:  :update-input-data
Handling re-frame event:  :update-suggestions
Handling re-frame event:  :update-text-selection
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :load-chat-parameter-box
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :set-expandable-height
Handling re-frame event:  :set-chat-ui-props

[press space]

Handling re-frame event:  :load-chat-parameter-box
Handling re-frame event:  :update-input-data
Handling re-frame event:  :update-suggestions
Handling re-frame event:  :update-text-selection
Handling re-frame event:  :set-chat-ui-props
Handling re-frame event:  :load-chat-parameter-box
:call-jail :jail-id 0x0428c9d6c1aaaa8369a7c63819684f30e34396dc0907d49afeac85a0a774ccb919b3482097d992e66bcc538e7a0c6acf874c77748f396f53c0a102e10d1a37765b
:call-jail :path [:commands "send" :params 0 :suggestions]
:call-jail :params {:parameters {:args (), :bot-db nil, :seq-arg nil}, :context {:data nil, :from "50b1bf979b9d5b13efeee623e0a0102b45abf200", :to "323a7fd769a0f106d6b41232b10c44064bb4be88"}}
Handling re-frame event:  :set
Handling re-frame event:  :set-chat-ui-props
{:result {:context {}, :messages [], :returned {:markup ["choose-contact" {:bot-db-key "recipient", :index 0, :title "Choose recipient"}], :title "Send transaction"}}}
Handling re-frame event:  :received-bot-response
****SUGG HANDLER DB [recv-bot-resp]
nil
Handling re-frame event:  :suggestions-handler
Handling re-frame event:  :choose-predefined-expandable-height
Handling re-frame event:  :set-in
Handling re-frame event:  :set-expandable-height
Handling re-frame event:  :set
Handling re-frame event:  :check-sync
Handling re-frame event:  :update-sync-state
```

**Comment by annadanchenko** [comment]
Same happens for /request command typed manually 
Bad case: /reques and press t then space
