### ISSUE TITLE
Lowercase word "status" within the button name "I'm new to Status" on the intro screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15327]
**Steps:**

1. Install and open Status app
2. Pay attention at the word "Status" within  "I'm new to Status" button name

**Expected result:** uppercase word "Status"
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=3876%3A365058&t=RyCpDQhARtcSYAYC-0

<img width="320" alt="Onboarding for Mobile – Figma 2023-03-13 13-56-42" src="https://user-images.githubusercontent.com/97245802/224695385-308d112e-85a3-4eee-82c7-b2e43e589111.png">

**Actual result:** lowercase word "status"

![photo_2023-03-13 13 59 39](https://user-images.githubusercontent.com/97245802/224695804-a502d2ee-616d-4f8e-9a40-8c9a959901f3.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
It's a very very small bug, I will fix it in combination with https://github.com/status-im/status-mobile/issues/15340
