### ISSUE TITLE
new-group module refactoring

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1532]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

Improve new-group module guided by these rules https://github.com/status-im/status-react/issues/1495

**Comment by annadanchenko** [comment]
Tested on iOS and Android, looks ok to merge

can add/remove contacts; 
create new group of contacts, add remove members to group, rename group and delete it
