### ISSUE TITLE
Community Join Request changes

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#15322]
## Feature Issue

- [ ] If the request to join a community is ignored or unattended by the Admin/Community Manager for more than seven (7) days, the request should be marked as `expired`, and the community  "Join request" notification from Admin/Community Manager's Activity Center should be `deleted`.

![1 line](https://user-images.githubusercontent.com/19339952/224416735-04cf3ec3-ed56-4e7f-a85e-aeec63e5aa35.png)

- [ ] The Sender/Requester should be able to request again after seven (7) days
- [ ] The Sender/Requester's Activity Center notification should be updated accordingly. (Tracked here: #15082)

### Developer Notes

This feature requires an update on `status-go` for
- marking the request as expired after seven (7) days if the request is ignored
- removing the Join request notification on Admin/Community Manager's Activity Center
- allowing the user (sender/requester) to request again after seven (7) days

**Comment by pavloburykh** [comment]
@smohamedjavid hi! Could you please also include in the description the case when admin declines community request? As has been described in this [comment](https://github.com/status-im/status-mobile/pull/15084#issuecomment-1448389032):

>if the request to join a community is declined by the community manager/admin, we should NOT show the declined state to the sender/requester. Instead, it will be shown as the request is pending for seven (7) days, and after that, the text will change to "Request hasn't been accepted". The user can request again after seven (7) days.

Just want to clarify if decline flow will be implemented as described above.

**Comment by smohamedjavid** [comment]
Hi @pavloburykh! - It's captured as part of this issue (#15082) as it will take care of (or related to) the Community Request Activity Centre Notification. This breakdown (depending on Community Admin and Requester/Sender) helps us for a better understanding of the changes. Let me know if anything missing or need an addition.

**Comment by pavloburykh** [comment]
> Hi @pavloburykh! - It's captured as part of this issue (#15082) as it will take care of (or related to) the Community Request Activity Centre Notification. This breakdown (depending on Community Admin and Requester/Sender) helps us for a better understanding of the changes. Let me know if anything missing or need an addition.

Thank you for your explanation @smohamedjavid

**Comment by smohamedjavid** [comment]
Hi @John-44 / @xAlisher 

Quick question: For the Admin/Community Manager, do we have to remove the `join request` after seven (7) days (just like a **pending** request) if it's **declined**?

Because we will not show the declined result to the Sender/Requester and can request again after seven (7) days from the original join request time.
