### ISSUE TITLE
Mentions new design

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15331]
Implement mentions [new design](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2706%3A263349&t=vavORuvHSmCjRGNE-0).

Dependency: https://github.com/status-im/status-mobile/issues/15432

**Comment by churik** [comment]
Also should be considered cases:
- when editing a message with a mention
- when adding mention during editing
- when replying to messages with a mention


https://user-images.githubusercontent.com/4557972/231768757-a860b6da-4e9b-4402-b4b2-9e81ef29768c.mp4

**Comment by OmarBasem** [comment]
> Also should be considered cases:

This issue is for implementing the UI. I will open a separate issue for these cases. https://github.com/status-im/status-mobile/issues/15800
