### ISSUE TITLE
Home rendering regressions

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15336]
referenced:         @flexsurfer I think this needs to be looked at again, it doesn't render properly for me

![Screenshot_2023-03-13-14-40-00-73_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/224814580-a0f6f9d1-e37a-4de1-a2e0-108b0f5203ab.jpg)

_Originally posted by @du64 in https://github.com/status-im/status-mobile/issues/15247#issuecomment-1466848799_

**Comment by du82** [comment]
also referencing this: https://github.com/status-im/status-mobile/pull/15247#issuecomment-1466852257

**Comment by du82** [comment]
Tested on OnePlus Nord N20 5G and Samsung A50

**Comment by du82** [comment]
![Screenshot_2023-03-13-15-19-11-89_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/224823153-fce14a6a-fa92-471b-915a-96f88826ad2c.jpg)

**Comment by flexsurfer** [comment]
hey @du64 thanks for reporting, by `doesn't render properly` you mean it shouldn't have such a sharp color difference on the edge?

**Comment by du82** [comment]
> hey @du64 thanks for reporting, by `doesn't render properly` you mean it shouldn't have such a sharp color difference on the edge?

I mean the "invite your friends" button should hide when I scroll up, but instead only the groups go underneath the view

**Comment by flexsurfer** [comment]
oh that's intentional,there is no solution for Android for such behaviour see https://github.com/status-im/status-mobile/issues/15305

but i see also latest screenshot is kinda different issue?

**Comment by flexsurfer** [comment]
i see like 2 issues on the latest screenshot, statusbar color is wrong, header blur planel has wrong color

**Comment by cammellos** [comment]
This should have been addressed in the design review
