### ISSUE TITLE
Refactor and improve imported images

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#15339]
In ui & ui2 folder we have images as @2x.png and @3x.png.
They are high-quality png images and some of them like [onboarding](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=5508%3A323380&t=PPuvxyHUMLozgW4F-0) images are quite big in size
(@2x.png 4.8MB, @3x.png 9.1 MB)

These big image sizes keep adding up and affect metro bundler loading time and app size.

We should refactor imported images and improve size and performance.
We can look into a few questions like

1. Do we need to add multiple formats or can we just add a single one? (and which one?)
2. Should we use a jpeg instead?

**Comment by churik** [comment]
@Parveshdhull 
do you think it is still relevant?

**Comment by Parveshdhull** [comment]
Thank you @churik for pinging me. Not relevant anymore, as we added a compression script in https://github.com/status-im/status-mobile/pull/21300/files
