### ISSUE TITLE
Error on opening images

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15338]
When tapping the image, there's a chance that it will give this error. It also occurs if you swipe to go back while tapping the image.

![Screenshot_2023-03-14-01-56-17-74_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/224920182-9d557bd0-71c2-4356-a6be-c0ae76b61bdf.jpg)

**Comment by OmarBasem** [comment]
Hi @du64, does this happen sometimes or always?

**Comment by OmarBasem** [comment]
> It also occurs if you swipe to go back while tapping the image.

Go back from which screen?

**Comment by du82** [comment]
> Hi @du64, does this happen sometimes or always?

About 1/3 of the time

**Comment by du82** [comment]
> > It also occurs if you swipe to go back while tapping the image.
> 
> Go back from which screen?

Tap an image, then before it can animate, hit the back button.

This also happens randomly, although I found it while intentionally testing edge cases

**Comment by OmarBasem** [comment]
> Tap an image, then before it can animate, hit the back button.

@du64 Does it give the same error above or a different error?

**Comment by qoqobolo** [comment]
I was also able to reproduce this issue twice on my iOS device and so far it looks random to me too (no particular steps to reproduce).
Can only add that in both cases the error occurred on closing an image received from another user (not sent by myself).

Adding this to the 1.23 milestone.
@OmarBasem thanks for looking at this, and @du64 for reporting.

**Comment by OmarBasem** [comment]
Similar to https://github.com/status-im/status-mobile/issues/15395#issuecomment-1488310604

Dependant on reanimated upgrade which is dependant on RN upgrade

**Comment by qoqobolo** [comment]
Not reproducible in 1.23. 
Feel free to reopen it if you face it again or if you think it needs to be tracked (cc @OmarBasem )
