### ISSUE TITLE
Hashtag links to the channels which contain text with underscores around are not resolved as links

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15335]
Followup of https://github.com/status-im/status-mobile/pull/15135 cc @ibrkhalil 

**Steps:** 

1. In community create a channel that has text with underscores around it. For example: \_test-channel\_
2. In another channel of current community post a hashtag link to the newly created channel #\_test-channel\_ 
**Note:** do not forget to use `\`symbol  before underscore `_` characters in order to ignore Markdown formatting, otherwise you will see italic text in hashtag link. 
4. See if hashtag link is resolved. 

**Expected result:** hashtag link is resolved. User is redirected to #\_test-channel\_ channel on clicking the link 

**Actual result:** hashtag link is not resolved. Regular text is sent. 

https://user-images.githubusercontent.com/97245802/221606006-4b37f2a7-716c-42b9-93c2-04366730c12a.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Fixed, Creating a PR
![image](https://user-images.githubusercontent.com/33176106/225046664-d9c91343-d67a-4412-bb03-1780b34b5175.png)

**Comment by ibrkhalil** [comment]
This is now fixed .. Kindly test it so that we can close this issue
@pavloburykh

**Comment by pavloburykh** [comment]
> Allow underscores as a valid character for status-tags #15344

@ibrkhalil could you please specify in what PR can we test the fix? I see that PR mentioned above is closed  https://github.com/status-im/status-mobile/pull/15344

**Comment by ibrkhalil** [comment]
> > Allow underscores as a valid character for status-tags #15344
> 
> @ibrkhalil could you please specify in what PR can we test the fix? I see that PR mentioned above is closed #15344

Hey Pavlo .. It's merged on status-go .. It should be working in latest develop

**Comment by pavloburykh** [comment]
@ibrkhalil thanx! Fixed and tested. Closing current issue.
