### ISSUE TITLE
Cannot mention non-ascii community channel

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15337]
This doesn't work for me, it just removes the hashtag:

https://user-images.githubusercontent.com/65834069/224881612-81a55774-1679-4d77-a5a9-3440d11a5201.mp4

_Originally posted by @du64 in https://github.com/status-im/status-mobile/issues/15135#issuecomment-1467276643_

**Comment by flexsurfer** [comment]
cc @ibrkhalil

**Comment by ibrkhalil** [comment]
Please test it on latest develop, the fix was merged yesterday https://github.com/status-im/status-mobile/pull/15135

**Comment by du82** [comment]
I was on wrong PR, It works, closing issue.

**Comment by du82** [comment]
just tested non-ascii characters, they dont seem to work with a channel of the same name

![Screenshot_2023-03-14-01-36-28-85_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/224916237-a4d7238a-fba9-4212-8df4-cb2b354c2da3.jpg)

**Comment by du64** [comment]
It would be cook if instead of a blue underline, they had a rounded box like the user @ but it was another color and had # infront. HTML style links look weird in messaging apps like this

**Comment by pavloburykh** [comment]
> just tested non-ascii characters, they dont seem to work with a channel of the same name

Hi @du64!

Currently we have different validation rules for channel names on desktop and mobile.

On mobile all symbols are allowed, i.e. emoji, special characters (e.g. " , / ! ^ . etc.)

On desktop only latin letters, numbers, underscores, hyphens are allowed. Whitespaces are automatically replaces by hyphens in channel names on desktop.

At the same time, hashtag links support only those validation rules which are applied on desktop. It means that if user creates channel on mobile  with name "#test!@_channel name" it will be not resolved as hashtag link.

If you want to test hashtag links, please use channel names according to validation rules that are currently implemented on desktop. 

@ibrkhalil please confirm.

**Comment by ibrkhalil** [comment]
> > just tested non-ascii characters, they dont seem to work with a channel of the same name
> 
> Hi @du64!
> 
> Currently we have different validation rules for channel names on desktop and mobile.
> 
> On mobile all symbols are allowed, i.e. emoji, special characters (e.g. " , / ! ^ . etc.)
> 
> On desktop only latin letters, numbers, underscores, hyphens are allowed. Whitespaces are automatically replaces by hyphens in channel names on desktop.
> 
> At the same time, hashtag links support only those validation rules which are applied on desktop. It means that if user creates channel on mobile with name "#test!@_channel name" it will be not resolved as hashtag link.
> 
> If you want to test hashtag links, please use channel names according to validation rules that are currently implemented on desktop.
> 
> @ibrkhalil please confirm.

Yup, I confirm
And also I had a chat with Pedro .. Creating community channels will only happen on desktop in the future and it won't happen on mobile ..
CC: @cammellos @pedro-et

**Comment by pavloburykh** [comment]
@du64 please, feel free to close this issue if you are okay with the above answers.

**Comment by pedro-et** [comment]
@ibrkhalil channel creation is only on desktop for mvp. It will be added to mobile later

**Comment by du82** [comment]
> Yup, I confirm And also I had a chat with Pedro .. Creating community channels will only happen on desktop in the future and it won't happen on mobile .. CC: @cammellos @pedro-et

This seems like a really bad idea considering the majority of the world has a phone, but less have computers...

As someone who runs a community for Chinese Status users,  many non-english speaking people will leave if they're forced to use ASCII text. I don't see the need for an artificial limitation like this when clearly its already possible to achieve non-ascii.

**Comment by pavloburykh** [comment]
> This seems like a really bad idea considering the majority of the world has a phone, but less have computers...
> 
> As someone who runs a community for Chinese Status users, many non-english speaking people will leave if they're forced to use ASCII text. I don't see the need for an artificial limitation like this when clearly its already possible to achieve non-ascii.

@du64 from my perspective your comment above might really have a point. But still, this is a separate issue which is related to validation rules for channels/community names and not related to hashtag links directly or to mobile app. 

So I propose you to create a separate issue describing details which you have posted above or raise this question within the Status community.

**Comment by du82** [comment]
> > This seems like a really bad idea considering the majority of the world has a phone, but less have computers...
> > As someone who runs a community for Chinese Status users, many non-english speaking people will leave if they're forced to use ASCII text. I don't see the need for an artificial limitation like this when clearly its already possible to achieve non-ascii.
> 
> @du64 from my perspective your comment above might really have a point. But still, this is a separate issue which is related to validation rules for channels/community names and not related to hashtag links directly or to mobile app.
> 
> So I propose you to create a separate issue describing details which you have posted above or raise this question within the Status community.

Will do. Thanks for clearing up the confusion, I'll create a new mega-issue specific to usability with non-latin glyphs.
