### ISSUE TITLE
Bottom-sheet-like screen

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15332]
Many designs use a screen that looks like an [expanded bottom-sheet](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=6376%3A372306&t=vavORuvHSmCjRGNE-0). 

Currently, a modal screen is being used for some of these designs, while for others a bottom-sheet component is used.
The modal screen looks different from what is in the designs (especially on Android) while using a bottom-sheet component is not the best solution.

This issue is an attempt to implement a screen that looks like an expanded bottom-sheet.

**Comment by flexsurfer** [comment]
RNN modal screen should be used for this kind of screens

**Comment by flexsurfer** [comment]
@pedro-et promised that design team prepare for us table with all kinds of screens and sheets

**Comment by OmarBasem** [comment]
@flexsurfer you mean the designs will be updated to use full screen modals?

**Comment by OmarBasem** [comment]
> RNN modal screen should be used for this kind of screens

There is something in my mind that I can try (using RNN modal screen) that may give us the same look as in the current designs

**Comment by flexsurfer** [comment]
> @flexsurfer you mean the designs will be updated to use full screen modals?

no i mean, we need to clarification from design team which screens, sheet we have and what the difference, their states and transitions etc , currently its unknown

**Comment by flexsurfer** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/11790366/225000165-a37c7f0c-568d-4547-ae1e-9752b84e95f3.png">
it seems like such screens should have a stack

**Comment by flexsurfer** [comment]
and it seems like you can pull in any time to close the stack, or press the back button to navigate back, and again it seems like ios only, on Android there is no such guidelines and tools for implementing

**Comment by flexsurfer** [comment]
also wondering what kind of transition should be here
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/11790366/225038187-188e612f-4286-437d-874e-de93022ceb35.png">

**Comment by flexsurfer** [comment]
or here 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/11790366/225040229-6332c3d8-ebca-4360-8e28-ebf3c1a64157.png">

**Comment by OmarBasem** [comment]
@flexsurfer I think when we go from a bottom-sheet to another, we should first dismiss the one that is already open, like this:

https://user-images.githubusercontent.com/29354102/225054902-92ee80a9-8529-434a-95a3-456dd8c39fba.mov
