### ISSUE TITLE
White screen on navigate to a named screen

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#15333]
# Bug Report

## Problem 

While solving #15018 on [this PR](https://github.com/status-im/status-mobile/pull/15110), @pavloburykh helped reporting the following problem:

White screen appears for moment during redirection from Intro screen to I'm new to Status screen (IOS only)

#### Expected behavior

Not to show a white screen while navigating

#### Actual behavior

White screen appears for moment during redirection from Intro screen to I'm new to Status screen (IOS only)

<img alt="Monosnap 2023-03-13 13-41-23" width="364" src="https://user-images.githubusercontent.com/97245802/224693275-66219999-bf64-4c70-9ab9-75a4504f756d.png">

https://user-images.githubusercontent.com/97245802/224693336-b9160323-9d8e-4a01-ae27-d84af1b69170.mp4

### Reproduction

Steps:

  1. Install app
  2. Open Intro screen
  3. Tap Sign in/I'm new to Status button
  4. Pay attention if white screen appears for moment during animation between screens

### Additional Information

- Operating System: Reproducing on iPhone X, IOS 14.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
there are two problems
1) screen is heavy to render
2) os has a light theme

so the screen is starting opening when there is no content, and because os theme is light, white background is shown

so we need to do the next steps
1) optimize screen, like load the simple version first and then load images or something like that
2) set a custom screen content background for that screen

**Comment by ulisesmac** [comment]
> there are two problems
> 
>     1. screen is heavy to render
> 
>     2. os has a light theme
> 
> 
> so the screen is starting opening when there is no content, and because os theme is light, white background is shown
> 
> so we need to do the next steps
> 
>     1. optimize screen, like load the simple version first and then load images or something like that
> 
>     2. set a custom screen content background for that screen

@flexsurfer Thanks for helping clear this up!

**Comment by churik** [comment]
I think that it is already better in develop and also onboarding is about to be simplified. 
closing this for now, reopen if it still makes sense
