### ISSUE TITLE
Incorrect height of the composer on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15346]
# Bug Report

## Problem 

The bottom padding is too small in the composer and bottom sheets on Android.

<img width="486" alt="Screenshot 2023-03-14 at 17 12 31" src="https://user-images.githubusercontent.com/67952253/225068756-62bf8fe5-f369-41e0-993c-4f3322e62f52.png">

---

<img width="395" alt="Screenshot 2023-03-14 at 17 10 08" src="https://user-images.githubusercontent.com/67952253/225067800-cb3a5528-cd4b-4f89-bc11-ca4f6ec7b451.png">

---

Designs:

<img width="450" alt="Screenshot 2023-03-14 at 17 10 22" src="https://user-images.githubusercontent.com/67952253/225067847-0ec94c9d-07db-4cd8-b177-951182453cc1.png">

<img width="458" alt="Screenshot 2023-03-14 at 17 16 47" src="https://user-images.githubusercontent.com/67952253/225069581-14d2c52d-2ece-4030-91b9-96c0f7b36614.png">

### Reproduction

1. Open any chat / Tap the `Plus` button on the chat screen

### Additional Information

- Status version: nightly 14/03
- Operating System: Android
- Devices: Huawei P40 Lite, Pixel 2

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
Regarding the composer, I am working on a related issue: https://github.com/status-im/status-mobile/issues/15331

**Comment by flexsurfer** [comment]
@qoqobolo i guess the problem here is that all designs for ios, and ios has bottom padding, which is big, on Android we don't have it, so we need to ask designers for designs for Android

**Comment by flexsurfer** [comment]
cc @pedro-et

**Comment by du82** [comment]
The bottom sheets (not composer) have correct padding for me. The composer is still against the bottom of the screen

![Screenshot_2023-03-14-22-19-59-11_435383e61849826ed84c38f611283930](https://user-images.githubusercontent.com/65834069/225197159-fffaf44b-590b-4cb1-a89f-af03ed8b35a3.jpg)

**Comment by flexsurfer** [comment]
yes because your device has similar bottom padding to ios

**Comment by OmarBasem** [comment]
@qoqobolo I think it looks fine

![Screenshot_20230512_164948_Status PR](https://github.com/status-im/status-mobile/assets/29354102/9fadd899-1dae-4155-9d4b-515f1af1e0b4)

**Comment by qoqobolo** [comment]
@OmarBasem try to disable the system navigation buttons on your device.
For me it looks like this 

<img width="741" alt="Screenshot 2023-05-12 at 14 52 12" src="https://github.com/status-im/status-mobile/assets/67952253/4a4c283a-cdfd-4844-97e7-bbfd066cf135">

**Comment by qoqobolo** [comment]
And this is with the buttons enabled + dark mode (just because with the light mode it is all white and it is not that easy to notice the padding) 

<img width="1185" alt="Screenshot 2023-05-12 at 14 55 40" src="https://github.com/status-im/status-mobile/assets/67952253/aa602378-6ab0-42b0-a2b4-573c7cf15a87">

**Comment by OmarBasem** [comment]
> try to disable the system navigation buttons on your device.

Yeah I see..

I noticed this issue too, after closing the bottom sheet, the part behind the handle stays white

![Screenshot_20230512_170000_Status PR](https://github.com/status-im/status-mobile/assets/29354102/521ff9f3-3af3-4461-b715-94a53e120755)

**Comment by OmarBasem** [comment]
@qoqobolo I have opened a separate issue for the composer padding: https://github.com/status-im/status-mobile/issues/15885, and another issue for the handle bg color: https://github.com/status-im/status-mobile/issues/15886. You can close this one.

**Comment by qoqobolo** [comment]
@OmarBasem thank you very much!
I'll close this one again then, will track those issues separately.
