### ISSUE TITLE
More RNN Status Bar Problems

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15343]
1. ~On Android, trying to update the status bar visiblity using `mergeOptions` causes the screen to flicker:~

https://user-images.githubusercontent.com/29354102/225046572-7b63afef-f800-4206-94d0-01d288d93ce6.mp4

<br>

2. ~Doing the same, with `translucent` and `drawBehind` set to `true` will cause the content to be pushed down:~

https://user-images.githubusercontent.com/29354102/225049358-fe7199fc-5974-40fd-8ab4-eaef4d9f7c89.mp4

<br>
3. On iOS, setting animate to `true` has no effect (both using mergeOptions, and when setting options when defining the screen). 

<br>
<br>
Related issue: https://github.com/status-im/status-mobile/issues/15260

**Comment by OmarBasem** [comment]
Issues 1 and 2 seem to be not reproducible anymore

**Comment by cammellos** [comment]
closing as tracked elsewhere
