### ISSUE TITLE
Trying to lock audio recording goes to send

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15350]
After holding the record button, and then trying to drag it to the lock icon, it goes to the send icon instead. This happens on my android device most of the time. On iOS device works better.

Device: Samsung Galaxy Note 10 Lite
Android version: 11

cc @briansztamfater 

https://user-images.githubusercontent.com/29354102/225267109-12bf3bb9-8653-4258-a918-5d0e8e37defd.mp4

**Comment by OmarBasem** [comment]
Also I noticed that the audio button does not move with my finger. It only moves when it crosses a certain threshold. I don't know if this is intentional, but I think it would feel smoother if the audio button follows the gesture.

**Comment by briansztamfater** [comment]
> Also I noticed that the audio button does not move with my finger. It only moves when it crosses a certain threshold. I don't know if this is intentional, but I think it would feel smoother if the audio button follows the gesture.

Hi @OmarBasem this is intentional, and validated with design team. Will check the lock issue on Android when I have some time.

**Comment by briansztamfater** [comment]
Here's the original spec:
https://user-images.githubusercontent.com/18485527/225403939-cf3f1c7d-1814-41ad-b0f9-84231e4e5fed.mov
