### ISSUE TITLE
Wrong background opacity level on "I'm new to Status" screen (IOS)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15359]
Followup of https://github.com/status-im/status-mobile/pull/15110 **cc @ulisesmac** 

Reproducible on iPhone X, IOS 14.1

**Steps:**
1. Install Status app on IOS device
2. Proceed to "I'm new to Status" onboarding screen
3. Pay attention at background opacity level and compare it to Figma design 

**Expected result:** 

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2539%3A281125&t=To5xTQxUFGwvXeG1-0

<img width="327" alt="Onboarding for Mobile – Figma 2023-03-15 15-18-06" src="https://user-images.githubusercontent.com/97245802/225320341-f9845e36-c659-4887-b873-cc07563cbf16.png">

**Actual result:** opacity level does not correspond to design. 

Screen from iPhone X, IOS 14.1

![photo_2023-03-15 15 19 04](https://user-images.githubusercontent.com/97245802/225320590-1c4c5671-8b41-47fd-b749-0270c0d6b640.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: iOS

**Comment by ulisesmac** [comment]
@Hey @pavloburykh 

This problem will be addressed when the background is changed on https://github.com/status-im/status-mobile/issues/15274

**Comment by J-Son89** [comment]
@pavloburykh has this issue been addressed already? The background component is now the same that's used across all onboarding screens. Also this did not come up as a note in @mariocnovoa 's design review -https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=1902-145290&t=83VQuV325uSetx7o-0

**Comment by churik** [comment]
I believe can be closed in favor of design feedback,thank you!
