### ISSUE TITLE
Utilise CallRPC method from status-go

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#1536]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: By making this change we will stop using Http RPC calls for communication with local geth node. This will simplify resuming application after background mode as well as improve performance and security.

**Comment by annadanchenko** [comment]
#1558 on Android. Still testing

**Comment by annadanchenko** [comment]
#1576 on iOS, still testing

**Comment by rasom** [comment]
@annadanchenko please check #1576 
Android: http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-fc2946.apk
iOS: https://i.diawi.com/R7ZfdH

**Comment by annadanchenko** [comment]
@rasom #1576 can't be reproduced on new build (See below) will keep testing it today
Android: http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-fc2946.apk
iOS: https://i.diawi.com/R7ZfdH
