### ISSUE TITLE
The duration of recorded audio is shown as more than 2 minutes after audio message sending

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15365]
Follow up for https://github.com/status-im/status-mobile/issues/13530

#### Steps to reproduce:
1. Go to any chat
2. Long Tap "record" icon and hold unless the recording will be finished
3. Tap 'send' button

#### Actual result:
The max duration of the sent audio record = 2:03 or more

https://user-images.githubusercontent.com/52490791/225405807-718c9fd4-ec35-4ba9-8960-1815e403f143.mp4

#### Expected result:
The max duration of the sent audio record = 2:00

#### Devices:
- IOS, Android

**Comment by briansztamfater** [comment]
Hi @VladimrLitvinenko the video file was not uploaded. Could you upload it again, please?

**Comment by briansztamfater** [comment]
I am unassigning this issue from myself until I actually work on it, please tag me instead in a comment or issue description so I can be aware of it!

**Comment by VolodLytvynenko** [comment]
> Hi @VladimrLitvinenko the video file was not uploaded. Could you upload it again, please?

Sorry, didn't notice it! Uploaded. Thank you!
