### ISSUE TITLE
Status' bar colour differs from the colour of onboarding screens

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15362]
followup:  @pavloburykh  This should be translucent like the area below, just like the notification center

![Screenshot_2023-03-15-10-28-11-34_65ad86f86fd2321a85272a99323da10f](https://user-images.githubusercontent.com/65834069/225359085-4f839184-9cd9-4914-964c-4911254bd683.jpg)

_Originally posted by @du64 in https://github.com/status-im/status-mobile/issues/15353#issuecomment-1470249137_

**Comment by pavloburykh** [comment]
@du64 thanx for logging the issue!

Could you please specify what exactly is wrong on the attached screen, cause I am not sure I correctly understand the issue. 

Could you point out the problem in comparison to the design https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2231%3A253380&t=To5xTQxUFGwvXeG1-0 ?

**Comment by pavloburykh** [comment]
@du64 this is a screen from the design. 

<img width="568" alt="Onboarding for Mobile – Figma 2023-03-15 17-56-15" src="https://user-images.githubusercontent.com/97245802/225367306-7a73a6a5-c961-4dc7-b999-b5af84c58e74.png">

Sorry, it just can be me who doesn't see the difference. 

Anyway, let's wait until someone of devs will pick up the issue and addresses it. 

Thanx for reporting!

**Comment by pavloburykh** [comment]
**NOTE** for devs: see comments https://github.com/status-im/status-mobile/pull/15353#issuecomment-1470351212 and https://github.com/status-im/status-mobile/pull/15353#issuecomment-1470403453

**Comment by flexsurfer** [comment]
statusbar should be the same color as screen, not its darker and black

**Comment by J-Son89** [comment]
@pavloburykh this issue is fixed now right? Thanks to @flexsurfer's recent pr 🤔

**Comment by pavloburykh** [comment]
> @pavloburykh this issue is fixed now right? Thanks to @flexsurfer's recent pr 🤔

@J-Son89 correct. I'm closing this issue. @du64 thanx for reporting. You can observe the fix in the latest nightly build. JFYI:  onboarding screens header overlapping status bar (screenshot below) is a known bug and will be addressed later. 

![photo_2023-04-04 17 43 00](https://user-images.githubusercontent.com/97245802/229829140-06737510-2672-43b6-9ab9-badc85f41ff8.jpeg)
