### ISSUE TITLE
User chatkey display format needs to be updated

### ISSUE THREAD

**Issue by pedro-et** [status-im/status-react#15377]
![screenshot](https://user-images.githubusercontent.com/97039678/225565669-1b77fe9c-7e6b-4623-b79b-5637954f11cf.png)

In the image above you can see that the format is zQ3sqh...Hcd. Considering the first 5 characters will always be the same we should display them as zQ3...abc12. Image below for reference.

<img width="1415" alt="Screenshot 2023-03-16 at 09 00 53" src="https://user-images.githubusercontent.com/97039678/225566521-bcb0bc91-d08f-49c0-a2a4-27ccf3e0719b.png">

**Comment by cammellos** [comment]
closing as tracked elsewhere
