### ISSUE TITLE
The white space can be set as a nickname

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15378]
#### Preconditions:
User_A and User_B are mutual contacts

#### Steps to reproduce:
1. User_A: Go to contacts -> open profile of User_B -> tap 'Nickname'
2. Enter only space into the nickname textbox
#### Actual result:
The white space is set as a nickname

https://user-images.githubusercontent.com/52490791/225572434-99e6f474-be97-4423-b441-835cc7c25f0a.mp4

#### Expected result:
Potential solutions:
- The white spaces are ignored in the beginning and in the end
- The 'done' button is inactive if only white space is entered

#### ENV: 
Nightly: 16 Mar 2023

**Comment by ibrkhalil** [comment]
Solved in https://github.com/status-im/status-mobile/pull/15557
