### ISSUE TITLE
Identity request notification remains in the AC after sender cancels his request

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15372]
Initially logged [here](https://github.com/status-im/status-mobile/pull/15284#issuecomment-1467978084), agreed with @ilmotta to log as separate issue. 

**Steps:** 

1. User A sends identity request to User B
2. User A cancels identity request
3. See if identity request notification remains in AC for User B

**Expected result:** from my point the expected result should be removing identity request for receiver's AC

**Actual result:** notification remains in the AC with the following data: title, timestamp, sender's name. Action buttons/identity question are not displayed. It is impossible to perform any actions upon notif as swipe buttons do not appear. 

On the video below you can see a behaviour on mobile at the moment when desktop sender cancels his request:

https://user-images.githubusercontent.com/97245802/224989510-267f1acc-130c-48bb-b3f8-16997bf3a057.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
closing as post mvp identity verification
