### ISSUE TITLE
Identity notification animation is twitchy and slow 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15371]
Initially logged [here](https://github.com/status-im/status-mobile/pull/15284#issuecomment-1467978557), agreed with @ilmotta to log as separate issue. 

Device: Samsung Galaxy A52, Android 12

This can be some global performance problem of the AC and its elements. But with identity notifications this issue is the most noticeable. Especially if request has a long multiline text. 

**Steps:**

1. Generate identity verification notification for mobile user  (by sending identity verification request from desktop)
2. Interact with notification: swipe, open reply bottom sheet etc. 
3. Pay attention if animation is smooth

**Actual result:** Here is a video below from my device. Not sure if it is visible enough but in real I am experiencing rather slow and twitchy animation while interacting with notification.

https://user-images.githubusercontent.com/97245802/224993639-616244ff-6658-4648-aaf3-072850d58977.mp4

- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
closing as post mvp
