### ISSUE TITLE
Double pressing a button to open a modal screen, opens twice

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15373]
On Android, trying to press any button twice that would open a modal screen (like activity-center bell), would open the screen twice.

**Comment by flexsurfer** [comment]
i would say its a global issues ,not only Android or Modal screens, each time when js thread is slow you will be able to press button twice or more times

**Comment by churik** [comment]
I cannot reproduce it now if app is working fine, I suppose it is reproducible only when app is becoming slow (under some circumstances), so adding it to `Performance`

Not sure though that it can be fixed globally, feel free to close it if it doesn't make sense

**Comment by flexsurfer** [comment]
it's already fixed https://github.com/status-im/status-mobile/pull/18478
