### ISSUE TITLE
The message with long text is not scrollable in the list of pinned messages

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15380]
#### Steps to reproduce:
1. Send a few messages with a long text in any chat
2. Pin messages
3. Open a list of pinned messages
4. Scroll it

#### Actual result:
The pinned list is not scrollable on the androids

For IOS:

https://user-images.githubusercontent.com/52490791/225582290-2c2b3d7e-c6cc-48f8-9c5f-d4c460b0cbac.mp4

For Android:

https://user-images.githubusercontent.com/52490791/225582176-0654398d-9574-41d2-950a-c93e54206649.mp4

#### Expected result:
Long data is scrollable on the pinned messages list

**Comment by VolodLytvynenko** [comment]
NOTE for QA:
- Check the ability to scroll pinned images. (hope the image pinning will be fixed by now)

**Comment by alwx** [comment]
Linked to https://github.com/status-im/status-mobile/issues/14564
