### ISSUE TITLE
Header colour differs from the rest part of the blurred page when opening bottom sheet on Communities/Messages home screens (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15386]
Might be regression related to https://github.com/status-im/status-mobile/pull/15247 cc @flexsurfer 

Reproducible on Android (on IOS looks correct)

**Steps:**

1. Open Communities/Messages tabs
2. Tap + button to open bottom sheet
3. Pay attention at header color of the blurred  part of the screen

**Expected result:** blurred header should have the same color as the rest part of blurred screen
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1694-379588&t=usmdEcqVKy2zVK7R-0

![photo_2023-03-16 14 11 11](https://user-images.githubusercontent.com/97245802/225613441-d4880e9e-8dda-4fb0-a925-a1e728e25af9.jpeg)

**Actual result:** blurred header colour differs from the rest part of the blurred screen

![photo_2023-03-16 14 13 14](https://user-images.githubusercontent.com/97245802/225613909-bf9bbb52-1317-4c31-9b41-4ded01e69768.jpeg)

https://user-images.githubusercontent.com/97245802/225614343-d74a8ac3-bc23-400b-b700-5bf4b66bc2d2.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
yes , this will happen with any blur in the app when opening overlay screen

**Comment by flexsurfer** [comment]
im afraid there is no fix for that, we shouldn't implement blur for now

**Comment by pavloburykh** [comment]
@flexsurfer does it make sense to leave this issue opened until there will a way to fix? Or better close it for now?

**Comment by flexsurfer** [comment]
no we should keep it

**Comment by cammellos** [comment]
closing for now as it's not actionable
