### ISSUE TITLE
User is not navigated to the community after user taps shared link of community and taps 'fetch' button

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15387]
#### Steps to reproduce:
1. User_A: Create community -> tap on the created community -> tap '...' in the right corner -> Tap on the community name
2. User_A: Copy the link of the community and provide it to User_B
3. User_B: Tap on the community link -> Tap 'fetch' button

#### Actual result:
Nothing happens when the 'fetch' button is tapped

https://user-images.githubusercontent.com/52490791/225614576-69b27d5e-9700-483c-8bb9-a4781f5a4c61.mp4

#### Expected result:
The user navigates to the page where he is able to join/send requests to the community
![image](https://user-images.githubusercontent.com/52490791/225614402-43212f67-b667-4a5c-a160-07d7859eec66.png)

#### Additional info:
Reproducible in 30% of cases

#### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/10990546/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/10990547/geth.log)

#### ENV:
- 16 Mar 2023

**Comment by alwx** [comment]
Hey @VladimrLitvinenko! I was checking this one today but found out that the UI for it has already changed and it's impossible to reproduce it using the steps from above.
Should we close this? Or is it still reproduceable but something else actually needs to be done in order to reproduce it?

**Comment by VolodLytvynenko** [comment]
@alwx agree. For now no steps for this issue after UI changes. Can be closed
