### ISSUE TITLE
Some messages get stuck in "sending" status for sender despite they have been sent/delivered to receiver

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15385]
I faced the issue in all kind of chats but seems like it is easier to reproduce in community channels. 

**Preconditions:** User A - sender, User B - receiver

**Steps:**

1. Try sending several messages by User A to User B until some of the messages gets stuck in "sending" status
2. See if such message has been received by User B

**Actual result:** Some messages get stuck in "sending" status for sender despite they have been sent/delivered to receiver

[User_A_sender_logs.zip](https://github.com/status-im/status-mobile/files/10990054/User_A_sender_logs.zip)
[User_B_receiver_logs.zip](https://github.com/status-im/status-mobile/files/10990055/User_B_receiver_logs.zip)

https://user-images.githubusercontent.com/97245802/225603454-6d3fcab9-bd92-4620-8aa4-348220137540.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
Hi @cammellos ! If it is possible, could we prioritise this issue? It became a blocker for our e2e as in many tests we are relying on correct status of the message. And in fact this status remains in sending in many cases regardless message has been already delivered to receiver.

**Comment by cammellos** [comment]
@pavloburykh I'll be looking at this today, thank you

**Comment by cammellos** [comment]
I think I know the root cause,
it's most likely due to the fact that waku-1 was asynchronous when sending messages, while waku-2 is more synchronous, so the message is sent before it can be tracked. 
I'll be looking at a solution today.
