### ISSUE TITLE
[x] shown instead of images after the device comes back from background

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15396]
#### Steps to reproduce:
1. Send the messages with images (in my case at least 5-8 messages were sent)
2. Go to background mode (at least 1 minute)
3.  come back from background mode

#### Actual result:
[x]'s are shown instead of images

https://user-images.githubusercontent.com/52490791/225687763-a862aa08-0d2f-4a8f-b277-1274de36ab1b.mp4

#### Expected result:
Images are shown

#### Additional info:
The defect is reproducible in 20% of cases. I was able to reproduce both on IOS and Androids, on real and on emulators

#### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/10993333/Status.log)

[geth.log](https://github.com/status-im/status-mobile/files/10993336/geth.log)

[logcatlogs.txt](https://github.com/status-im/status-mobile/files/10993339/logcatlogs.txt)

#### ENV:
nightly: 16 Mar 2023

**Comment by rasom** [comment]
@VladimrLitvinenko just to clarify: [x]'s  are shown on sender's or receivers's side?

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko just to clarify: [x]'s are shown on sender's or receivers's side?

Hi @rasom . On the sender side

**Comment by rasom** [comment]
@VladimrLitvinenko Trying to repro this for hours now, no luck yet. I wonder if I'm doing something wrong

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko Trying to repro this for hours now, no luck yet. I wonder if I'm doing something wrong

@rasom Just a moment. I will try to reproduce it one more time

**Comment by VolodLytvynenko** [comment]
@rasom That's weird. Can't reproduce it anymore. Early it was easy to reproduce. I think issue can be closed

**Comment by rasom** [comment]
@VladimrLitvinenko ok, thank you
