### ISSUE TITLE
The preview links are not resolved in chat for the mobile version of twitter and youtube

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15402]
#### Problem:
in Status App there is shown a list of links located in "Privacy and security -> Chat link previews"  that should be resolved after their sending: 
![image](https://user-images.githubusercontent.com/52490791/225904834-e5ee4f57-e0ff-4494-9f59-e25342cba8ee.png)
For now, the following websites mobile versions links  are not resolved:
- m.youtube
- mobile.twitter

#### Steps to reproduce:
1. Go to Privacy and security -> Chat link previews
2. Tap 'Enable all'
3. Open any chat
4. Send a link to youtube or Twitter which navigates to mobile version (example: https://mobile.twitter.com/Xenoartist_/status/1636356156095361032 or https://m.youtube.com/watch?v=BhqiJDw4PIY)

#### Actual result:
Links for mobile versions of websites listed  in "Chat link previews" are not resolved

https://user-images.githubusercontent.com/52490791/225932694-fda518eb-d4c5-493c-b2eb-e95167e7baee.mp4

#### Expected result:
Links for mobile versions of youtube and Twitter are resolved
How it works in telegram
![image](https://user-images.githubusercontent.com/52490791/225933908-bdb7a0a2-51d2-4691-aee5-ea77f78391ee.png)

How it works in discord
![image](https://user-images.githubusercontent.com/52490791/225934068-ea9edc0c-9121-45c3-81a1-2ed2527b2492.png)

#### Additional info:
The current ticket is based on a reply from the design team
![image](https://user-images.githubusercontent.com/52490791/225934726-cd057e05-8c2e-47fe-8554-aa2b1eefe45d.png)

**Comment by du82** [comment]
We should probably get Baidu and Douyin links working too considering the flood of Chinese users joining the app, and Baidu is no worse for privacy than Twitter

**Comment by VolodLytvynenko** [comment]
> We should probably get Baidu and Douyin links working too considering the flood of Chinese users joining the app, and Baidu is no worse for privacy than Twitter

As I see there is a design that maybe will be implemented in the future. It looks like any website can be configured to see its links resolving
![image](https://user-images.githubusercontent.com/52490791/225947602-90477210-3d10-48a6-a2d9-97fb770bf4e8.png)

**Comment by du82** [comment]
> > We should probably get Baidu and Douyin links working too considering the flood of Chinese users joining the app, and Baidu is no worse for privacy than Twitter
> 
> As I see there is a design that maybe will be implemented in the future. It looks like any website can be configured to see its links resolving ![image](https://user-images.githubusercontent.com/52490791/225947602-90477210-3d10-48a6-a2d9-97fb770bf4e8.png)

could you link the figma file?

**Comment by VolodLytvynenko** [comment]
> could you link the figma file?

@du64 Sure https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=3474-360562&t=kIZrQrxaqAKqfH82-0
