### ISSUE TITLE
Refactor Deprecated functions of react-native-reanimated v1 to use v2 instead

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#15418]
This issue is a blocker for getting us to the latest version of React Native.

<img width="377" alt="Screenshot 2023-03-21 at 8 18 02 AM" src="https://user-images.githubusercontent.com/64726664/226507038-c4bf2324-837e-4968-8a77-f05718473fd2.png">

The react-native version we are currently trying to upgrade to is 0.71.4 and it requires us to use v3 of react-native-reanimated library.

The v3 version of the library is backwards compatible with v2 but it does not support most v1 code.
I found a few instances of v1 usage in our code.

We need to refactor parts of our app that use v1 to move to v2 instead.

migration guide : https://docs.swmansion.com/react-native-reanimated/docs/guide/migration-from-1.x

List of deprecated methods I can find are below : ( I will update as and when i find more ) 
- [x] usage of `clockRunning`, `startClock` & `endClock` at `src/quo/animated.cljs` 
- [x] usage of  `(.-ScrollView animated)` at `src/quo/animated.cljs` & `src/react_native/reanimated.cljs`
- [x] usage of `(.-Text animated)` at `src/quo/animated.cljs`
- [ ] usage of `useCode` Hook at `src/quo/animated.cljs`

**Comment by siddarthkay** [comment]
A second look at the stack trace and it seems like the issue could be related to using `react-native-reanimated` `3.x` with `react-native-redash/lib/module/v1` library.

**Comment by cammellos** [comment]
closing to inactivity
