### ISSUE TITLE
"times() not a number: null" error and crash when opening wallet tab 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15425]
Bug is not reproducible on all accounts. Please use account given below and follow the exact provided steps.

**Preconditions:** use this user for reproduction. seed phrase: section involve corn song gold verb topic nurse morning dream snack very

**Steps:**

1. Recover given above user
2. Open profile screen after recovering
3. Perform manual logout
4. Perform login
5. While being on Jump to screen tap Wallets tab
6. Observe the error and crash

**Expected result:** no error, wallet tab is opened

**Actual result:** "times() not a number: null" error appears. Error will keep displaying after every app relogin. 

[status_logs (2).zip](https://github.com/status-im/status-mobile/files/11026814/status_logs.2.zip)

https://user-images.githubusercontent.com/97245802/226568455-0fcea9b8-cbc4-493d-b68e-a445cff74fbb.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@yqrashawn any progress on this issue? we would like to cut the release branch by wednesday, so it would be good to have a fix in as soon as possible
thanks!

**Comment by yqrashawn** [comment]
@cammellos pr at https://github.com/status-im/status-mobile/pull/15502
