### ISSUE TITLE
Bottom sheet component expands too much on Android

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15438]
cc @Parveshdhull 

Tested on Android 12, Samsung Galaxy A52

Below example demonstrates "Remove profile" bottom sheet behaviour. 

**Expected result:** 

<img width="336" alt="Onboarding for Mobile – Figma 2023-03-20 16-46-30" src="https://user-images.githubusercontent.com/97245802/226376705-31894cd9-6ff8-4c13-9b09-ab338de6dccd.png">

**Actual result:** 

![photo_2023-03-20 16 49 06](https://user-images.githubusercontent.com/97245802/226376843-c8bf431e-6e62-4a56-848d-c30932d28488.jpeg)
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
@ibrkhalil  Please can you take a look? If I remember correctly bottom sheets are your expertise :)

**Comment by ibrkhalil** [comment]
> @ibrkhalil Please can you take a look? If I remember correctly bottom sheets are your expertise :)

Thank you so much Parvesh :D :)
I'll take a look once I finish the tasks currently in progress

**Comment by flexsurfer** [comment]
hey @ibrkhalil im working on this

**Comment by ibrkhalil** [comment]
> hey @ibrkhalil im working on this

Okay, Thanks for letting me know 🙇🏻
