### ISSUE TITLE
Password value is not centered within the password input filed on IOS (both hidden and unhidden states)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15433]
Reproduced on iPhone X, IOS 14.1

**Steps:** 

1. Open login page on IOS device
2. Start typing password in the password input field
3. See if password value is centered

**Actual result:** password value is sticked to the bottom of input field

![photo_2023-03-22 09 23 50](https://user-images.githubusercontent.com/97245802/226830045-b74f4b82-7067-45cc-ad07-ab38325a6f9e.jpeg)

**Expected result:** password value is centered 

<img width="416" alt="Onboarding for Mobile – Figma 2023-03-22 09-24-14" src="https://user-images.githubusercontent.com/97245802/226830166-18f0621f-9d60-42c2-a666-572f60512247.png">

### Additional Information

- Status version: nightly 
- Operating System:  iOS

**Comment by Parveshdhull** [comment]
cc: @ulisesmac
