### ISSUE TITLE
Ens/display name are not resolved on login/profile list screens.

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15435]
cc @Parveshdhull mentioning you, as we discussed this issue before. Please take a look when you have a chance. 

**Steps:** 

1.  Create/restore multiaccount which has set ENS/display name
2. Logout
3. See if Ens/display name is resolved on login page
4. Go to Profiles list screen
5. See if Ens/display name is resolved on Profiles list screen within profile card

**Actual result:** 

https://user-images.githubusercontent.com/97245802/226841077-a6896a1e-ce3d-4465-a1d3-2e0032d265fc.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
Currently having trouble getting ens name right, investigating

<img width="736" alt="image" src="https://user-images.githubusercontent.com/15090582/227459017-1be39072-86fb-4fb9-8b21-09cee7e530a0.png">

**Comment by yqrashawn** [comment]
code at status-go https://github.com/status-im/status-go/blob/8304f8bf88c081f2489d6e5564d8bcd15c6d9d10/api/geth_backend.go#L191
