### ISSUE TITLE
Onboarding - Update illustrations

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#15445]
This issue is to track updating illustrations in the Onboarding flow.
Currently, we have placeholders in the place where there should be images, but we should replace them with the real illustrations.

Attaching some examples from Figma designs:

![](https://user-images.githubusercontent.com/18485527/226945209-06eb731b-9623-4a14-8795-66c5085f3ff4.png)

cc @mariocnovoa @pedro-et

**Comment by cammellos** [comment]
I believe this is tracked elsewher
