### ISSUE TITLE
Follow up issues on profile onboarding screens

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15441]
The issues, required to fix for onboarding flow (follow up on https://github.com/status-im/status-mobile/pull/15401)

### ISSUE 1 Difference between design and actual implementation 
<img width="432" alt="photo_2023-03-22 12 48 42 jpeg 2023-03-22 12-49-18" src="https://user-images.githubusercontent.com/4557972/226896606-fc380b99-470e-4bf8-91da-6aab32479f2b.png">

- 6.1 The placeholder font color is not aligned
- 6.2 The cursor color is not aligned
- 6.3 No opacity either on IOS or on Android
- 6.4 'Continue' button is overlapped by the keyboard and the view is not scrollable 

### ISSUE 2 Button continue is still available when validation is not passed
Therefore, can create multi-account with invalid names.

**Steps:**
- set name with emoji 
- finish the flow

**Comment by pavloburykh** [comment]
### ISSUE 3 "Continue" button overlaps other elements when keyboard is active

Reproduced on Samsung Galaxy A52, Android 12


https://user-images.githubusercontent.com/97245802/227525400-fc0f96a4-cfbf-4de7-890d-d4f28dec2848.mp4

![photo_2023-03-24 14 50 00](https://user-images.githubusercontent.com/97245802/227525754-26fc2192-5659-47ea-95b4-77313adcb61d.jpeg)

**One more example from emulated device with small screen:**

![image_2023-03-24_14-48-13 (1)](https://user-images.githubusercontent.com/97245802/227525966-b1b1f909-34e5-4d54-b4fe-f701ded96cc6.png)

**Comment by J-Son89** [comment]
Will adjust for android!
