### ISSUE TITLE
Shell animation on Android not smooth

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15453]
The shell (jump to) animation seems to be not so smooth on Android. I am able to notice individual frames. On iOS, it looks a lot smoother, even on old iOS devices. For comparison, below are 3 videos, 120hz iOS, 60hz iOS, and 60hz Android.

- iPhone 13 Pro (120 hz)

https://user-images.githubusercontent.com/29354102/226984637-cbf7c0f8-66fa-45a1-9159-4abe103b82e6.MP4

- iPhone 6s (60 hz)

https://user-images.githubusercontent.com/29354102/226984701-e50fb996-b6d8-439f-b0c5-7d86253b4a36.MP4

- Samsung Galaxy Note 10 Lite (60 hz)

https://user-images.githubusercontent.com/29354102/226984779-01f0456c-624a-4379-bbc1-bd9922ec62af.mp4

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, Thank you for reporting this issue.
Please can you use same state in ios while comparing?
(android has few chats and shell cards)

**Comment by Parveshdhull** [comment]
But still it needs further optimization

**Comment by OmarBasem** [comment]
Hi @Parveshdhull, just tried deleting all state from Android, but still looks the same.

**Comment by Parveshdhull** [comment]
thank you for confirming

**Comment by cammellos** [comment]
closing as that has probably changed by recent changes, feel free to repoen if still an issue
