### ISSUE TITLE
Hiding bottom sheet (component) does not animate

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15458]
Calling `:bottom-sheet/hide` does not animate hiding the bottom sheet

Also, when calling `bottom-sheet/hide` to navigate to another screen, the bottom-sheet probably should animate a little faster (compared to the opening animation).

**Comment by Parveshdhull** [comment]
possible duplicate of https://github.com/status-im/status-mobile/issues/15134
cc: @flexsurfer

**Comment by flexsurfer** [comment]
yes im on it, thanks

**Comment by OmarBasem** [comment]
> possible duplicate of #15134 cc: @flexsurfer

I think it is not just new-chat bottom sheet. It is a global issue.

Anyways feel free to close either of them (if duplicated).
