### ISSUE TITLE
Commands: Improve performance and decrease number of calls to jail

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#1547]
"So imagine i’m filling some command, like `/send`, when i type `/send J` the call is sent to jail, but i continue typing `/send Ja`,  then `/send Jan` and only the last result of these three calls will be rendered as preview. So what we could do here is to make some windowing for such calls and sent no more than 1 call per second for some particular command."

**Comment by rasom** [comment]
Already implemented in `develop`
