### ISSUE TITLE
User gets stuck on "Generating keys" screen after trying to restore account (2 cases)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15475]
Followup of https://github.com/status-im/status-mobile/pull/15452 cc @cammellos 

User gets stuck on "Generating keys" screen in 2 cases

**Case 1** 

**User tries to restore account that has already been restored**

**Steps:** 
1. Create/restore an account
2. Logout
3. Proceed to the new Account restore flow
4. Try to restore account from that already exists
5. Observe user gets stuck on "Generating keys" screen

**Case 2** **User tries to restore account that has been restored before on current device **BUT** has been subsequently removed from Profile list** 

**Steps:** 
1. Create/restore an account
2. Logout
3. Open Profile list screen
4. Remove existing profile
5. Proceed to the new Account restore screen
6. Try to restore account that has been removed on step 4
7. Observe user gets stuck on "Generating keys" screen

https://user-images.githubusercontent.com/97245802/227537367-7baffb4f-2034-4076-81d3-54be042df9d2.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
fix for case 1 is merged already, fix for case 2 is here https://github.com/status-im/status-mobile/pull/15519
