### ISSUE TITLE
[JS API] Add a new contact to the user's contacts

### ISSUE THREAD

**Issue by iSasFTW** [status-im/status-react#1548]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to add a new public key to the user's contacts programmatically.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I would like to use the Status API to add a new contact to the user's "address book", either from the browser or once a command is run. This should either add the new contact outright, or open up the "new contact" window, with the public key field populated with whatever public key i gave as the function's parameter.

**Comment by jarradh** [comment]
@alwx @flexsurfer  what are your thoughts on this?

**Comment by flexsurfer** [comment]
i think for Dapp it could be implemented same way as contacts selection works for wallet, and also we can implement this for bots as well, for example, we could implement
```status.addNewContact(public-key) 
 status.addListener("on-contact-added")```

**Comment by jarradh** [comment]
I think it's the inverse also, as in he wants to do something like, `status.addContact`
