### ISSUE TITLE
Clunky chat opening animation on Android

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15481]
# Bug Report

## Problem 

The issue also may be relevant for other screens, but the most noticeable is how the screen "jumps" when opening a chat.

https://user-images.githubusercontent.com/67952253/227595404-f7eb5fbb-b9db-4695-acb9-5f33604a331b.mp4

### Reproduction

1. Open some chat or community channel

### Additional Information

- Status version: nightly 24/03
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
Possible duplicate: https://github.com/status-im/status-mobile/issues/15238

**Comment by qoqobolo** [comment]
> Possible duplicate: https://github.com/status-im/status-mobile/issues/15238

Ah you're right! Closing this one then. 
Thanks @OmarBasem
