### ISSUE TITLE
Disable back button for onboarding notifications screens 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15490]
followup of https://github.com/status-im/status-mobile/pull/15370 cc @jo-mut 

According to @cammellos [comment](https://github.com/status-im/status-mobile/pull/15370#issuecomment-1482521660)

"back button should be disabled on notification screen for now, since you can't go back to pre-login (it shows in the design because there's an in-between screen that is not implemented yet)."

Currently, back button is not disabled which can cause issues as described [here](https://github.com/status-im/status-mobile/pull/15370#issuecomment-1482508056)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Already fixed according to the code and current behaviour.

**Comment by alwx** [comment]
cc @pavloburykh

**Comment by pavloburykh** [comment]
> Already fixed according to the code and current behaviour.

Thanx @alwx. You are aright, already disabled in nightly. Closing the issue.
