### ISSUE TITLE
Carousel progress bar overlays device status bar on the intro screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15493]
# Bug Report

## Problem 

Tested on Huawei P40 Lite and Xiaomi Mi Note 9, Android 10
Cannot check on iOS since builds are not available at the moment.

https://user-images.githubusercontent.com/67952253/227902456-a9f783d1-62bf-45b7-87b7-7d6e396271eb.mp4

#### Expected behavior
<img width="389" alt="Screenshot 2023-03-27 at 11 34 27" src="https://user-images.githubusercontent.com/67952253/227902920-c62a5f21-350d-4cc2-a8a1-24102223798c.png">

### Additional Information

- Status version: nightly 27/03
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
cc @J-Son89 @Parveshdhull

**Comment by Parveshdhull** [comment]
hi @qoqobolo, Thank you for reporting this issue.
Will be fixed in https://github.com/status-im/status-mobile/pull/15489
