### ISSUE TITLE
Inconsistent ens verification logic between multiaccount and contact

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#15505]
same ens name

says it's me in adding contact
says it's not belong to me in register ens name

<img width="519" alt="CleanShot 2023-03-28 at 14 54 28@2x" src="https://user-images.githubusercontent.com/15090582/228153298-491b00e3-bc01-4ce7-933c-ad995c9b6314.png">
<img width="563" alt="CleanShot 2023-03-28 at 14 54 04@2x" src="https://user-images.githubusercontent.com/15090582/228153315-73fa3004-11eb-4780-9e1e-405521699a72.png">

**Comment by yqrashawn** [comment]
Add contact using `PublicResolver.pubkey` https://docs.ens.domains/contract-api-reference/publicresolver#get-public-key
Register using `Registry.owner` https://docs.ens.domains/contract-api-reference/ens#get-owner

**Comment by yqrashawn** [comment]
Ok, pub key is generated using whisper path `m/43'/60'/1581'/0'/0` and set in ens resolver with `setPubKey` https://etherscan.io/address/0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41#writeContract

owner is just the owner of the ens name

**Comment by yqrashawn** [comment]
place adds unverified ens record https://github.com/status-im/status-go/blob/8c85a62e108d9c54f6124117cf7a196fb3731732/protocol/messenger_handler.go#L1898
place set ens verified `true`
https://github.com/status-im/status-go/blob/8c85a62e108d9c54f6124117cf7a196fb3731732/protocol/ens/verifier.go#L170
https://github.com/status-im/status-go/blob/8c85a62e108d9c54f6124117cf7a196fb3731732/protocol/ens/verifier.go#L51

**Comment by yqrashawn** [comment]
Not a bug. Can just import the private key of the name owner and bind it with current pubkey

**Comment by yqrashawn** [comment]
Although we might want to check owner and pub key at the same time, since there's no need to bind again if already bound to the current pub key

**Comment by churik** [comment]
I think can be closed for now, as ENS purchasing/binding to the pub key from the user profile is currently not on the roadmap. Feel free to reopen @yqrashawn
