### ISSUE TITLE
ReferenceError: 'l18n' is not defined pop-up is shown after launching the app

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1550]
### Description

*Type*: Bug

*Summary*: Sometimes I can see an error pop-up when installing Status app. When this error appears, I can't set up my password and proceed with the app. I need to re-launch the application to proceed.

#### Actual behavior
Error
commands.js loading failed

console
error-in-jail
ReferenceError: 'l18n' is not defined

### Reproduction
- run Status first time after installation

### Additional Information

![screenshot_20170803-103546](https://user-images.githubusercontent.com/28752642/28912521-45d38fa4-783d-11e7-8532-fea22f876073.png)

* Status version: 0.9.8-111-gabafa330+

* Operating System: Android

#### Logs

https://app.testfairy.com/projects/4803622-status/builds/6243037/sessions/3/?accessToken=z9JDoPhWXfpA9i1Eu-tS9IX89LM

**Comment by sla-shi** [comment]
@asemiankevich any new statistics on this?

**Comment by asemiankevich** [comment]
@sla-shi no

**Comment by asemiankevich** [comment]
havent seen this anymore, closing
