### ISSUE TITLE
Keyboard overlays tips while typing a password on iOS

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15508]
# Bug Report
Followup of https://github.com/status-im/status-mobile/pull/15405

## Problem 

If you focus on the `Type password` field the tips (`Lower case`, `Upper-case`, etc) hide behind the keyboard on iOS devices, so you need to press `Return` to see again what characters are missing.

#### Expected behavior
`Tips` move up with the keyboard and remain above it when it's expanded 

#### Actual behavior
https://user-images.githubusercontent.com/67952253/227577278-74912850-422f-4658-955c-5a8b74112509.MP4

### Reproduction

1. Start creating a new account
2. On the `Create profile password` screen tap the `Type password` field

### Additional Information

- Status version: nightly 28/03
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
fixed at 1.23
