### ISSUE TITLE
Always show the "I understand my password can't be recovered" disclaimer on password creation screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15518]
# Bug Report

Followup of https://github.com/status-im/status-mobile/pull/15405

## Problem 

Currently, according to [design](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2241-251839&t=rSX39O9F5DHXFiNF-4), we only show the disclaimer `I understand my password can't be recovered` when the user sets the cursor to the second input field (`Repeat password`) .

But if the user after that presses on the first input field (`Type password`) again for some reason, for example, if they add more characters to the password in the second field first and then back to the first and close the keyboard, then the disclaimer, that is needed to complete this step, won't be shown on the screen, which may be a bit confusing. 

https://user-images.githubusercontent.com/67952253/228238711-138aedca-ddc2-44bd-b44e-309d24b9caf2.mp4

#### Expected behavior

We should consider the option to show the disclaimer on the screen always from the beginning / always when both password fields are filled

#### Actual behavior

The disclaimer is only shown after focusing on the second field

### Reproduction

1. Start creating a new account
2. Enter a password
3. Repeat it
4. Then focus back on the `Type password` field and try to complete the password creation flow

### Additional Information

- Status version: nightly 28/03
- Operating System: Android, iOS

**Comment by SilentCruzer** [comment]
if this issue issue is still open, I would like to work on this issue

**Comment by qoqobolo** [comment]
> if this issue issue is still open, I would like to work on this issue

@cammellos pinging you to confirm the assignment

**Comment by cammellos** [comment]
Sure, I'll assign it to you @SilentCruzer !
