### ISSUE TITLE
new design on old android devices

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#15529]
<img width="287" alt="image" src="https://user-images.githubusercontent.com/11790366/228572086-00daafbe-94ce-4ce1-93c4-fb53123dcede.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/11790366/228572162-1e1ae3ca-9d7c-448f-ba4a-476a359d64d9.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/11790366/228572267-57bd9cb0-d31e-4c44-a932-486ee6b53050.png">
<img width="306" alt="image" src="https://user-images.githubusercontent.com/11790366/228572334-2955736c-ac1a-4a26-89cd-aedeae3cbfed.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/11790366/228572384-65e07616-1680-4e40-b2b3-120e9a4131ca.png">

**Comment by du82** [comment]
With all of the blur and things going on, I don't think a phone of that age will be able to run Status anyways lol

**Comment by churik** [comment]
closing as we are focusing on Google Pixel for now
