### ISSUE TITLE
Non-Latin nicknames are not resolved in mentions

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15524]
# Bug Report

## Problem 

Non-Latin nicknames in mentions are sent as plain text, so you can't navigate to the user's profile by clicking on it, and the recipient isn't notified that they've been mentioned.

#### Expected behavior
Nicknames of any alphabets resolve in mentions

#### Actual behavior

https://user-images.githubusercontent.com/67952253/228322496-2570fd47-9c1e-48fc-a88d-caa351d87eda.mp4

### Reproduction

1. Open chat
2. Add a non-Latin nickname to some user
3. Try to mention them

### Additional Information

- Status version: nightly 28/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
The issue is also applicable to `-`  and to spaces at end/beginnig of the nickname

**Comment by flexsurfer** [comment]
hey @qfrank could you pls comment on this? your thought, thanks

**Comment by qfrank** [comment]
I'll look into this

**Comment by qfrank** [comment]
> spaces at end/beginnig of the nickname

Regarding above, I think nickname should not contains spaces at end/beginning, WDYT? @cammellos @churik @flexsurfer @ibrkhalil

**Comment by cammellos** [comment]
> > spaces at end/beginnig of the nickname
> 
> Regarding above, I think nickname should not contains spaces at end/beginning, WDYT? @cammellos @churik @flexsurfer @ibrkhalil

This looks like a good idea, unless there's a product reason to do so cc @John-44 @pedro-et

**Comment by churik** [comment]
>  Regarding above, I think nickname should not contains spaces at end/beginning, WDYT? 

agree!

**Comment by John-44** [comment]
> > Regarding above, I think nickname should not contains spaces at end/beginning, WDYT?
> 
> agree!

Also agree!
