### ISSUE TITLE
Logout and slow performance when sending /location on iPhone 5S

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1552]
### Description

*Type*: Bug

*Summary*: Application logs out when sending /location for the first time on iOS 10.3.3 (iPhone 5S) while syncing. Also the map is being displayed very slow. I would say this happens due to huge resources consumption for syncing and rendering the map

### Reproduction

- Open Status on iOS
- Add new contact through the QR code scanner while the app is still syncing
- Go to 1x1 chat and send /location

### Additional Information

* Status version: 0.9.9d112

* Operating System: iOS 10.3.3 real device iphone 5s

#### Logs

https://app.testfairy.com/projects/4803590-status/builds/6251318/sessions/3/?accessToken=e/du56vG9pdC10y0q2WRcTfgd94

**Comment by flexsurfer** [comment]
it can be the same reason as in https://github.com/status-im/status-react/issues/1435, resources consumption

**Comment by oskarth** [comment]
Part of 55/Fast-status. @asemiankevich comment on it being a compact bad case:

> Slow map rendering even on new device https://app.testfairy.com/projects/4803622-status/builds/7170527/sessions/30/?accessToken=L0lrqOkdM4F9zXRTQ0pA9nR008Y (1552)

Iphone 7 is rendering map faster , this current lag was noticed on Android device

**Comment by annadanchenko** [comment]
Location command is removed
