### ISSUE TITLE
[Androids only] The animation is paused on onboarding page if the Status app is closed by device's "back" button

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15522]
Follow up for https://github.com/status-im/status-mobile/pull/15489

#### Steps to reproduce:
1. Open the onboarding page
2. tap 'back' button on the device
3. Reopen the app

#### Actual result:
The animation is paused

https://user-images.githubusercontent.com/52490791/228270831-00365bad-2e9c-4039-8312-0e988fa314cc.mp4

#### Expected result:
The animation still sliding after the app is reopened

#### ENV:
- Real device: Huawei P20 light, version 9
- Android Emulator: Pixel 3 XL, version 11

**Comment by Parveshdhull** [comment]
Adding for context: Same behavior also will happen if app hot-reloaded in debug version
