### ISSUE TITLE
<Java.lang.NullPointerException> crash on creating/restoring multiaccount

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15527]
There are no exact steps to reproduce this issue. It happens very rarely. In the description, there are steps after which I reproduced it once. Hope the attached logs can help

#### Steps to reproduce:
1. Tap I'm new to Status
2. Tap 'Use recovery phrase'
3. Input some valid recovery phrase (For my case I used this one: cheap pave laptop ocean sadness need resemble actor employ lucky indoor before)

#### Actual result:
<Java.lang.NullPointerException> error is shown
![image](https://user-images.githubusercontent.com/52490791/228522508-cf57adfb-7344-4c02-973a-2d9e8d86a4ec.png)

#### Expected result:
The account is restored

#### Logs:
logcat logs
[logs123.txt](https://github.com/status-im/status-mobile/files/11100386/logs123.txt)

#### Env:
Nightly 29 Mar 2023

**Comment by pavloburykh** [comment]
> There are no exact steps to reproduce this issue. It happens very rarely. In the description, there are steps after which I reproduced it once. Hope the attached logs can help
> 
> #### Steps to reproduce:
> 1. Tap I'm new to Status
> 2. Tap 'Use recovery phrase'

Bug is reproducible both on restoring and creating multiaccount. Still no exact steps, crash appears randomly. For now, I have faced this crash on Android only. Not sure if it is reproducible on IOS.

**Comment by alwx** [comment]
Checking it. Was unable to reproduce yet but working on it :)

**Comment by alwx** [comment]
Tried to reproduce it multiple times but failed — everything was fine with creating account on Android all the time. Need more specific steps.

**Comment by VolodLytvynenko** [comment]
not reproducible anymore
