### ISSUE TITLE
There is no warning in sync flow that devices should be in the same wi-fi network 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15530]
# Problem
Currently due to technical limitations sync devices flow is working only when both devices are in the same network and VPN also may affect the ability to finish the flow successfully.
So it has to be explicit for the user that they must use the same WI-FI network with a stable connection.

In the current mobile [design](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4121-312366&t=cu0LmMROIe8dnyuF-4) it is not anticipated.

## Acceptance Criteria
The user is warned that both devices have to be in the same network and not use VPN services 

cc @John-44 @pedro-et

**Comment by siddarthkay** [comment]
@churik : can we close this? seems to be fixed in this PR : https://github.com/status-im/status-mobile/pull/16150
