### ISSUE TITLE
Nightlies are out of date

### ISSUE THREAD

**Issue by du82** [status-im/status-react#15531]
@jakubgs 

Nightlies are over a week out of date.

**Comment by jakubgs** [comment]
It appears the MacM1 host is down:

![image](https://user-images.githubusercontent.com/2212681/229429733-94800def-32b4-437e-b899-b14eeccd2b77.png)

```
 > ping -c4 macm1-01.he-eu-fsn1.ci.devel.statusim.net
PING macm1-01.he-eu-fsn1.ci.devel.statusim.net (167.235.38.106) 56(84) bytes of data.

--- macm1-01.he-eu-fsn1.ci.devel.statusim.net ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3071ms
```
And release CI has only one host of each type, so iOS builds just time out:

![image](https://user-images.githubusercontent.com/2212681/229429961-b9ed491e-16fd-4bd4-93fc-071b214f6fc4.png)

**Comment by jakubgs** [comment]
I've requested a manual power cycle on both of Hetzner Mac M1 hosts:

![image](https://user-images.githubusercontent.com/2212681/229430341-30dd8428-cc63-4b85-8595-b8edaeb5a02f.png)

**Comment by jakubgs** [comment]
Also, it appears hosts have been down for 3 days, but there also is an iOS build issue:

```
/Users/jenkins/workspace/status-mobile/platforms/ios/ios/StatusIm.xcodeproj: error: No profiles for 'im.status.ethereum' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'im.status.ethereum'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'StatusIm' from project 'StatusIm')
```
https://ci.infra.status.im/job/status-mobile/job/platforms/job/ios/1017/artifact/ios/logs/StatusIm-StatusIm.log
https://ci.infra.status.im/job/status-mobile/job/platforms/job/ios/1017/console

Has someone disabled automatic signing?

**Comment by jakubgs** [comment]
Looks like this was changed in on the 21st: https://github.com/status-im/status-mobile/commit/3f3cbe98

Which is when the last successful build took place:

![image](https://user-images.githubusercontent.com/2212681/229431822-c0e63a3e-1020-4879-8bf9-1b8e95981c0b.png)

**Comment by jakubgs** [comment]
Still waiting for Macs to get back up.

**Comment by jakubgs** [comment]
And here's a successful build:

![image](https://user-images.githubusercontent.com/2212681/229442150-f35cf75f-3488-4165-8bf8-e33de7d66d1d.png)

https://ci.infra.status.im/job/status-mobile/job/nightly/2678/
