### ISSUE TITLE
replace `:padding-top (if platform/ios? 44 0)` by using safe-area values

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#15535]
we have `:padding-top (if platform/ios? 44 0)` all over the code, we must use safe-area insets instead

**Comment by J-Son89** [comment]
@flexsurfer can we close this issue now? 🤔  I think it has been adjusted since

**Comment by flexsurfer** [comment]
we still have it in `status-im2.common.scroll-page.view`

**Comment by J-Son89** [comment]
I think this is addressed now, @flexsurfer ? 🤔

**Comment by flexsurfer** [comment]
yeah thanks :)
