### ISSUE TITLE
Sometimes backed up data is not restored/restored partially after restoring multiaccaount

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15533]
**сс @cammellos** 

There are no specific steps how to reproduce the issue. 

Sometimes data is not restored at all, sometimes is restored partially. 

Below I attach logs of a case when only 2 of 40 backed up contacts have been restored. This is my main desktop account. I am restoring it on different devices quite often. Most of the time data is being restored successfully. 

[Status-debug-logs (27).zip](https://github.com/status-im/status-mobile/files/11103781/Status-debug-logs.27.zip)

Issue is to be updated when new details will be investigated. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
@pavloburykh do you have geth.logs please? https://github.com/status-im/status-mobile/pull/15519#issuecomment-1488525703 if you need builds with geth.log enabled, as in the new flow currently there's a bug where geth.log is not created (but if you create it with the old flow everything should be there)

**Comment by pavloburykh** [comment]
> @pavloburykh do you have geth.logs please? [#15519 (comment)](https://github.com/status-im/status-mobile/pull/15519#issuecomment-1488525703) if you need builds with geth.log enabled, as in the new flow currently there's a bug where geth.log is not created (but if you create it with the old flow everything should be there)

oh, sorry. I totally forgot about this bug, was sure that attached archive contains geth log. I will attach new logs once I will reproduce the bug after https://github.com/status-im/status-mobile/pull/15519 will be merged

**Comment by pavloburykh** [comment]
As this bug is being reproduced randomly, It will take some time until we face it again and will able to get the logs.

**Comment by qoqobolo** [comment]
Didn't face this during 1.23 testing, closing for now
