### ISSUE TITLE
proper usage of :f> 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#15552]
:f> shortcut can be used to create function components from Reagent components (functions), where both RAtoms and Hooks work.

it seems like in some cases this works inefficient, investigate how to use it properly

it seems like when using reagent atoms from outside, functional component will be intialized again

like

```clojure
(fn []
  (let [atom (rf/sub [:sub]]
     (fn []
         [:f>
             (fn []
                [rn/text atom]
```

**SOLUTION:**

don't use anonymous inline functions

```clojure
(defn functional-comp []
[rn/text atom])


(fn []
  (let [atom (rf/sub [:sub]]
     (fn []
         [:f>  functional-comp])))           
```

**Comment by ulisesmac** [comment]
That's because in this example the functional component is an inline function, so each time the component is re-rendered its body is re-executed, then Clojure redefines the functions in its body:

```clojure
(fn []
  (let [atom (rf/sub [:sub]]
     (fn []
     ;; the body starts here
         [:f>
             (fn [] ;; <- this is the inline functional component redefined each time a render or re-render happens
                [rn/text atom]
```

This means instead of re-rendering the inline component we are mounting a whole new component, so hooks are reset.

To properly use hooks with ratoms we can follow this pattern:
```clojure
(defn my-f-component [props]
  (let [my-ratom (reagent/atom nil)] ;; If we're going to use ratoms, then we create a form-2 component
    (fn [props]
      (let [my-hook (useSomething ,,,)] ;; Hooks you need
        ;; view code where both hooks and ratoms work
        ))))

(defn exposed-component [props] ; It seems unnecessary to create this "wrapper",
                                ; but it helps not to worry if this component
                                ; must be called using `:f>` or not, we just use 
                                ; `exposed-component` as any other component
  [:f> my-f-component props])
```

Also we can configure the reagent compiler to always create functional components, if so, we could avoid the `:f>`, but it has a slightly slower performance.

**Comment by flexsurfer** [comment]
yes @ulisesmac you're right, it's not about functional components or hooks, it's about an anonymous inline function

```clojure
(defn parent-comp []
    [(fn [] [test-comp])])
```
in this example, `test-comp` will be initialized each time when parent component is rendered


also, i found that safe-area usage will lead to reinitialization, hope we'll replace its usage with constants soon and we won't have this problem
