### ISSUE TITLE
Profile icon disappears after setting up profile picture (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15553]
**Case 1:** 

**Steps:** 

1. Install app
2. Proceed to Create profile onboarding step
3. Set profile picture
4. See if profile icon is displayed 

**Actual result:** profile icon disappeared. It appears again after re-opening Create profile screen. 

5. Finish onboarding and enter multiaccount
6. Perform logout
7. See if profile icon is displayed on login page 

**Actual result:** profile icon disappeared. It appears again after re-opening the app. It will dissapear after every logout.   

https://user-images.githubusercontent.com/97245802/229128706-151d4688-a294-4cd3-bb10-d2436e72cafb.mp4

**Case 2:**

**Steps:** 

1. Create/restore multiaccount. Do not set profile picture during onboarding
2. Set profile picture after entering multiaccount
3. Perform logout
4. See if profile icon is displayed on login page

**Actual result:** profile icon disappeared. It appears again after re-opening the app. It will dissapear after every logout.   

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @pavloburykh,
Thank you very much for reporting this issue. I am not able to reproduce the issue with logout.
Please can you recheck in the latest develop?

The issue with creating a profile is probable regression from https://github.com/status-im/status-mobile/pull/15470 and the same fix for https://github.com/status-im/status-mobile/issues/15544 will also fix this issue.

Thank you very much @J-Son89 for looking into https://github.com/status-im/status-mobile/issues/15544.
Please also tag this issue in the corresponding PR for https://github.com/status-im/status-mobile/issues/15544 for testing.

**Comment by pavloburykh** [comment]
> Thank you very much for reporting this issue. I am not able to reproduce the issue with logout.
Please can you recheck in the latest develop?

Hi @Parveshdhull ! Thank you for investigation the issue. I've checked on latest develop and managed to reproduce **Case 2** with logout (see video below). 

https://user-images.githubusercontent.com/97245802/229432122-36d74306-f229-40ac-91c5-203fb025daca.mp4

Also, I see that 3 dots icon disappears form menu button on Switch profile screen

<img width="238" alt="Monosnap 2023-04-03 09-50-27" src="https://user-images.githubusercontent.com/97245802/229432699-91ea2bfc-075e-4859-8e7e-56e7ff4b4098.png">

**Comment by pavloburykh** [comment]
**UPDATE:** cc @Parveshdhull @J-Son89 

**Case 2** is reproducible only for me on my Samsung Galaxy, Android 12. Non of the QAs were able to reproduce on their Android 9, 10, 11. So we can consider Case 2 to be device/OS specific.

**Comment by pavloburykh** [comment]
@Parveshdhull hello! Re-opening the bug as it turned out it is reproducible only for Android 12. @churik is also reproducing on her BlackView BV5200 Pro (Android 12)

![photo_2023-05-02 13 45 00](https://user-images.githubusercontent.com/97245802/235648775-aef5adaf-d267-4314-bbc6-9ab65bef5f29.jpeg)

<img width="361" alt="photo_2023-05-02 13 55 21 jpeg 2023-05-02 13-55-53" src="https://user-images.githubusercontent.com/97245802/235648825-da4e5309-fc68-4b08-aa48-7c803b5205d7.png">

![photo_2023-05-02 14 00 18](https://user-images.githubusercontent.com/97245802/235648966-91e9e1df-23b1-4993-a8d5-3a367263c8c2.jpeg)
