### ISSUE TITLE
The deleted pinned message can't be unpinned in 1-1 chat

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15550]
### Problem:
1-1 chat does not have restrictions to pin/unpin messages for both users. But the message is not able to be unpinned when a current message is shown as deleted

#### Steps to reproduce:
1. USER_A: Send the message
2. USER_A: Delete the message by the 'delete for me' option
3. USER_B: Pin the message
4. USER_A: Go to the pinned list and try to unpin deleted message

#### Actual result:
USER_A can't unpin deleted message

https://user-images.githubusercontent.com/52490791/229103487-8214ba0f-b749-42ef-ba05-d04a808d25cf.mp4

#### Expected result:
USER_A can unpin deleted message

#### ENV:
Nightly [31 Mar 2023]

**Comment by ibrkhalil** [comment]
What is the expected bahvior for this CC: @pedro-et ?

**Comment by pedro-et** [comment]
If it's deleted it should automatically unpin @ibrkhalil

**Comment by VolodLytvynenko** [comment]
> If it's deleted it should automatically unpin @ibrkhalil

Hi, @pedro-et Should it be unpinned for both users in 1-1 chat If it was deleted by the 'delete for me' option?

**Comment by pedro-et** [comment]
No: delete for me is only a visual consequence for that user. It will show up as deleted on the user who deleted it side but will keep showing to the other user
