### ISSUE TITLE
Double tapping on the Messaging icon in the bottom nav should take the user to the Messaging screen with the 'Recent' tab selected

### ISSUE THREAD

**Issue by John-44** [status-im/status-react#15569]
Double tapping on the Messaging icon in the bottom nav should take the user to the Messaging screen with the 'Recent' tab selected.

This is different from single taping on the Messaging icon in the bottom nav which takes the user to the Messaging screen with whatever tab was last selected remaining selected.

This is a common feature in WeChat, that users who are used to using WeChat will expect.

**Comment by pavloburykh** [comment]
Hi @John-44 ! Should we follow the described pattern for community Community tab: should double tapping on the Community tab take user to the Community screen with Joined tab opened? Thank you! 

![photo_2023-05-10 12 51 00](https://github.com/status-im/status-mobile/assets/97245802/598b80ca-4282-4448-9309-3916cd9a6f86)

**Comment by John-44** [comment]
> Hi @John-44 ! Should we follow the described pattern for community Community tab: should double tapping on the Community tab take user to the Community screen with Joined tab opened? Thank you!
> 
> ![photo_2023-05-10 12 51 00](https://user-images.githubusercontent.com/97245802/237351559-598b80ca-4282-4448-9309-3916cd9a6f86.jpeg)

@pavloburykh yes good idea, that would make sense for consistency.

**Comment by pavloburykh** [comment]
> @pavloburykh yes good idea, that would make sense for consistency.

thanx for the answer!
