### ISSUE TITLE
Can't open image sent from desktop 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15560]
# Bug Report

#### Expected behavior
can open image on mobile

#### Actual behavior
![IMAGE 2023-04-03 11:29:55](https://user-images.githubusercontent.com/4557972/229469992-0299c978-a3c3-4f4d-8820-96fe43d99186.jpg)

### Reproduction

1) Desktop: send image or album
2) Mobile: open image

### Additional Information

- Status version: nightly 
- Operating System: Android (crash), iOS (cannot be opened)
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/11136812/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
So it is crashing because the desktop app is not sending image's dimensions (width and height). So if image dimensions are not available, a default value will be used.
