### ISSUE TITLE
Fix magic values for confirmation dialogue bottom-sheet

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#15564]
Investigate why the value `{:flex 0.48}` is used in bottom-sheet buttons to center elements and get rid of it

**Comment by OmarBasem** [comment]
This means each button would cover 48% of the available space. So buttons would cover 96% of the space and the rest would be margin in between.

**Comment by ibrkhalil** [comment]
Thank you so much for the explanation Omar
CC: @J-Son89

**Comment by J-Son89** [comment]
Yes but you don't need these values and can be done with margin and padding as in the commit I have shown before. The join community bottom sheet is an example of this.
