### ISSUE TITLE
Layout is broken if using markdown with code

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15575]
# Bug Report

## Problem 
On Android text is overlaying with the background:
![IMAGE 2023-04-04 19:14:20](https://user-images.githubusercontent.com/4557972/229867882-71dd760d-2b8f-4576-8ce2-c09e0d644e30.jpg)
On IOS all rows after 1 are not visible:
![IMAGE 2023-04-04 19:15:53](https://user-images.githubusercontent.com/4557972/229868189-4a728680-e9c3-42ca-a77e-6650f2c99fcf.jpg)

Also the same issue is reproducible with mentions (they are shifted up and not centered)

### Reproduction

1) Open Status
2) Send in any community text with markdown  (in  `` backticks) in several lines

### Additional Information

- Status version: release 1.22 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
Okay on initial investigation i was able to reproduce this issue and  break the UI when I introduce a code block using backticks `` mixed with normal text

so for example something like this is fine

`       
 SplashScreen splashScreen = SplashScreen.installSplashScreen(this);
setTheme(R.style.DarkTheme);
// Make sure we get an Alert for every uncaught exceptions
registerUncaughtExceptionHandler(MainActivity.this);
`

But something like this will break 

Here is my splash screen code `       
 SplashScreen splashScreen = SplashScreen.installSplashScreen(this);
setTheme(R.style.DarkTheme);
// Make sure we get an Alert for every uncaught exceptions
registerUncaughtExceptionHandler(MainActivity.this);
`


![Simulator Screen Shot - iPhone 14 Pro - 2023-04-05 at 17 53 15](https://user-images.githubusercontent.com/64726664/230079291-cc279699-f93f-47eb-80a8-8ac7ad19a207.png)
