### ISSUE TITLE
The keyboard is closed in the community chats after the app comes back from the background

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15597]
#### Steps to reproduce:
1. Go to the community chat
2. Open the keyboard
3. Type some data into the textbox
4. Go to the background
5. Come back from the background

#### Actual result:
The keyboard is closed

https://user-images.githubusercontent.com/52490791/230128212-300f0fda-faf6-43e8-90af-d2cd2234e73b.mp4

#### Expected result:
The keyboard is still shown

#### Device:
- Real device: iPhone 11 Pro Max, IOS 16
- Real device: Huawei p20 light, android 9

#### ENV: 
Nightly: [6 Apr 2023]

**Comment by ilmotta** [comment]
@VolodLytvynenko, could you verify again the bug is present? With recent changes made to the composer, this bug might not exist anymore.

**Comment by VolodLytvynenko** [comment]
@ilmotta not reproducible anymore. Can be closed
