### ISSUE TITLE
Check if we can compile status-go only for one platform (simulator/real device) in development

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#15593]
to reduce build time on development, we could compile status-go for a single platform, both on IOS/Android, maybe that might help speed up development.

**Comment by jakubgs** [comment]
Didn't notice this, so I opened my own:

* https://github.com/status-im/status-mobile/issues/15595

I also compared building `status-go` only for `iossimulator` and the difference was just 10-15 seconds in a ~2 minute build. 
So not sure if worth it.
