### ISSUE TITLE
Metro watchman error

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15600]
Sometimes when running `make run-metro` I get the following error:

```
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: query failed: synchronization failed: Operation timed out. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
```

**Comment by ilmotta** [comment]
Generally speaking, it was never reliable to to me to switch branches in `status-mobile` and just stop and restart processes like metro and shadow-cljs. I would easily get zombie processes such as watchman with the error you reported in this issue, or a zombie shadow-cljs compiling nothing, or another dangling gradle process consuming lots of GBs.

I do think we can fix this, but at the same time, I got a bad habit of just calling a shell alias to kill everything that could have been started related to status-mobile whenever I switch branches :shrug:

**Comment by OmarBasem** [comment]
Yeah, switching branches messes up everything..
