### ISSUE TITLE
Pinned messages UI issues

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15605]
# Bug Report

## Problem 
There are several issues related to how pinned messages are shown on Android devices.

#### ISSUE 1: white font on the pale gray background makes it hardly visible
<img width="502" alt="photo_2023-04-10 12 21 25 jpeg 2023-04-10 12-22-51" src="https://user-images.githubusercontent.com/4557972/230883833-67679905-e0cb-4f6d-aa14-04860a977003.png">

#### ISSUE 2: an audio message is hardly visible and cannot be played from pinned messages screen
![IMAGE 2023-04-10 12:17:03](https://user-images.githubusercontent.com/4557972/230882845-62b978c4-2fc0-47d8-8e28-f23e5d1a4254.jpg)

#### ISSUE 3: white on white in the system messages (light mode only
<img width="197" alt="Monosnap 2023-04-10 12-38-02" src="https://user-images.githubusercontent.com/4557972/230886305-062aea73-236f-440d-9c5e-8c33f36ebc47.png">

### Reproduction

1) Open Status, pin several messages in a community
2) Open pinned messages from an Android device and also pay attention to the system message 

### Additional Information

- Status version: nightly 10/04/23
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Issue 2 is already logged [here](https://github.com/status-im/status-mobile/issues/15536)
