### ISSUE TITLE
Android performance issues

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15609]
Android app navigation becomes laggy and twitchy after opening a lot of different community pages. 

For reproduction you may use this user, who already has a long list of communities: rule dirt shuffle vintage trash cricket gesture door more robust fine tooth

**Steps:** 

1. Recover given above user
2. Wait until backed up communities will appear in community list
3. Open Discover community screen
4. Start opening communities from the list one by one
5. Pay attention at navigation behaviour changes while opening more community screens

**Actual result:** the more community screens are opened the more laggy navigation becomes. Navigation becomes normal again after reopening the app. 

It is slightly visible on recorded video below, better to reproduce on real device via given user:

https://user-images.githubusercontent.com/97245802/230903054-12dc5646-8ba9-4ee9-83a7-f9cd800e8f86.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
@rasom another way to generate performance issues is to add during one session some number of new contacts (5 and more) and open different chats (1-1, group) with those contacts. Video below demonstrates laggy animation of the bottom sheet caused by the described actions. 


https://user-images.githubusercontent.com/97245802/230919121-27676f5e-8167-4dad-9d50-c201b91cc26f.mp4

**Comment by rasom** [comment]
So it looks like not dispatching `:shell/add-switcher-card` fixes the issue on Android.

**Comment by Parveshdhull** [comment]
Is dispatching this event while navigating is the problem, or rendered card in the background slowing the app?

**Comment by Parveshdhull** [comment]
> or rendered card in the background slowing the app

We probably can memoize shell cards, so they only update when the user is on the shell screen. But then we probably will have difficulty timing the shell cards update while pressing jump-to and collapsing the screen on the latest card (top one)
