### ISSUE TITLE
Screen orientation change is enabled on Android (list of cases)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15611]
@ibrkhalil I have updated the issue and added couple more cases when screen orientation change gets enabled on Android. 

Android only. Tested on Samsung Galaxy A52, Android 12

**Case 1:** Orientation change is enabled on Sign in by syncing onboarding 

**Steps:** 

1. Open Sign in by syncing onboarding screen
2. Try to scan invalid QR code 
3. Try to change screen mode to landscape at the moment when error "Oops! This is not a sync QR code" appears 
4. See if it is possible to switch to landscape mode

**Actual result:** can switch to landscape mode. 

https://user-images.githubusercontent.com/97245802/230921887-91bc2881-e195-4617-adb8-6aed7dfe3d25.mp4

**Case 2:** Orientation change is enabled when Request to join community/New chat bottom sheets are opened

https://user-images.githubusercontent.com/97245802/235913260-3fb26ade-9661-4f8e-842d-b4812b81d198.mp4

https://user-images.githubusercontent.com/97245802/235913267-9016cd83-4317-44c3-8b9f-eb3334bcf1cf.mp4

**Case 3:** Orientation change is enabled when notification toast appears

https://user-images.githubusercontent.com/97245802/235913497-6fddd5d2-f2a8-4fb3-800a-a5645963d8a2.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Most QR scanning screens I've used only allow portrait mode and disable the ability to switch to landscape.
Do you think we should do it this way? @pavloburykh

**Comment by pavloburykh** [comment]
> Most QR scanning screens I've used only allow portrait mode and disable the ability to switch to landscape. Do you think we should do it this way? @pavloburykh

Correct @ibrkhalil! Landscape mode is disabled all over the app, so it should be disabled on Scan QR screen as well.

**Comment by churik** [comment]
@ibrkhalil 
The bug is still there:

https://user-images.githubusercontent.com/4557972/232742727-8aed1fc9-2c66-440f-a2bd-dfee9a688750.mp4

**Comment by ibrkhalil** [comment]
> @ibrkhalil The bug is still there:
> 
>  FILE.2023-04-18.11.58.53.mp4

It's still WIP, Did you test on this [branch](https://github.com/status-im/status-mobile/pull/15619) ?

**Comment by qoqobolo** [comment]
Another place: `Add a contact` screen

https://user-images.githubusercontent.com/67952253/236797827-6261c3e5-fa7a-4ae1-a70d-595c30de728d.mp4

**Comment by ibrkhalil** [comment]
Going go continute working on this once I get an Android device to test it properly.
