### ISSUE TITLE
Navigation bar changes mode from dark to light after opening bottom sheet (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15629]
Followup of https://github.com/status-im/status-mobile/pull/15467 cc @flexsurfer 

RNN issue: https://github.com/wix/react-native-navigation/issues/7719

**Steps:** 

1. Open any tab, for example Messages tab
2. Open bottom sheet (tap + button)
3. Pay attention at navigation bar color

**Actual result:** Navigation bar changes mode from dark to light

![photo_2023-03-29 18 00 37](https://user-images.githubusercontent.com/97245802/228581283-a15fe90a-d32f-4a46-a44d-f160d53b15a0.jpeg)

https://user-images.githubusercontent.com/97245802/228581291-4e85a38a-25bf-4d02-a144-f6a2bc853c2b.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
Related issue: https://github.com/status-im/status-mobile/issues/15260

**Comment by flexsurfer** [comment]
@pavloburykh can't replicate this

**Comment by pavloburykh** [comment]
> @pavloburykh can't replicate this

Reproducing on latest nightly. 

Samsung Galaxy A52, Android 12


https://github.com/status-im/status-mobile/assets/97245802/ae712097-0038-4aa6-ae2c-1a2b5a1ea51d

**Comment by qoqobolo** [comment]
Reproducible with opening the activity center after merged https://github.com/status-im/status-mobile/pull/15993

https://github.com/status-im/status-mobile/assets/67952253/99bca7dd-a5d0-43f6-912e-2933587e5a9b

**Comment by pavloburykh** [comment]
Hi @cammellos! This one is still reproducible.

**Comment by pavloburykh** [comment]
Oh, ok, this is RN issue. Closing it.
