### ISSUE TITLE
IOS debug build fails non deterministically on local environment

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#15631]
Right after upgrading react-native to 0.67.5 we have an IOS build failure with the following error message : 

```log
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/siddarthkumar/Library/Developer/Xcode/DerivedData/
	StatusIm-fxiitjbbybrcsqcxqartjfyvqxdo/Build/Intermediates.noindex/Pods.build/
	Debug-iphonesimulator/FBReactNativeSpec.build/Objects-normal/x86_64/
	FBReactNativeSpec-generated-fd168fa4da568d55fc39af3f2cac5990.o 
	/Users/siddarthkumar/code/experiments/status-mobile/node_modules/
	react-native/React/FBReactNativeSpec/FBReactNativeSpec/out/FBReactNativeSpec-generated.mm 
	normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler 
	(in target 'FBReactNativeSpec' from project 'Pods')
	
	CompileC /Users/siddarthkumar/Library/Developer/Xcode/DerivedData/
	StatusIm-fxiitjbbybrcsqcxqartjfyvqxdo/Build/Intermediates.noindex/Pods.build/
	Debug-iphonesimulator/FBReactNativeSpec.build/Objects-normal/arm64/
	FBReactNativeSpec-generated-fd168fa4da568d55fc39af3f2cac5990.o 
	/Users/siddarthkumar/code/experiments/status-mobile/node_modules/
	react-native/React/FBReactNativeSpec/FBReactNativeSpec/out/FBReactNativeSpec-generated.mm 
	normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler 
	(in target 'FBReactNativeSpec' from project 'Pods')
	
(2 failures)
```

Have logged this issue to track any more such build failures and to investigate and find their fixes.
However we do not see such build failures on CI.

**Comment by OmarBasem** [comment]
Documenting the errors I am facing:

When building using `make run-ios` I always get the following: 
`
make run-ios fails with error: error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening StatusIm.xcworkspace.
`

When building on physical device from Xcode I always get the following error: 
` Command PhaseScriptExecution failed with a nonzero exit code`

I was able to get it working only when building on Simulator from Xcode.

**Comment by OmarBasem** [comment]
@siddarthkay few points that you can check to try to pinpoint the error:

- [x] App building using `make run-ios`
- [ ] App building from Xcode in debug mode on Simulator
- [ ] App building from Xcode in debug mode on physical device
- [ ] App building from Xcode in release mode on Simulator
- [ ] App building from Xcode in release mode on physical device
- [ ] App building PR build on CI

**Comment by siddarthkay** [comment]
Seems related : https://reactnative.dev/docs/0.68/new-architecture-troubleshooting#xcode-build-issues

**Comment by siddarthkay** [comment]
looking inside : `/Users/siddarthkumar/Library/Developer/Xcode/DerivedData/StatusIm-fxiitjbbybrcsqcxqartjfyvqxdo/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBReactNativeSpec.build/DerivedSources/codegen-FBReactNativeSpec.log`
I find this fantastic error : `error: Could not find node. Make sure it is in bash PATH or set the NODE_BINARY environment variable.` :)

**Comment by siddarthkay** [comment]
turns out I had somehow nuked nodejs from my system.
After `brew install node` 
I get a success on `make run-ios`

![Screenshot_2023-04-12_at_11 12 37_PM](https://user-images.githubusercontent.com/64726664/231540520-54856161-577c-44c6-af71-5ba61e9d352f.png)

**Comment by jakubgs** [comment]
But we should be using `NODE_BINARY` provided by Nix:
https://github.com/status-im/status-mobile/blob/d11ce135a66ff8bd465db033971a6b07ad375bb9/ios/StatusIm.xcodeproj/project.pbxproj#L547
https://github.com/status-im/status-mobile/blob/d11ce135a66ff8bd465db033971a6b07ad375bb9/nix/mobile/ios/shells/nodejs.nix#L9-L10
If we are not there's something still missing that's causing use to use system Node.js.

**Comment by jakubgs** [comment]
If you are running Xcode without Nix context then yes, it would naturally use system Node.js, which can result in:
```
node: bad option: --openssl-legacy-provider
```
Because that flag is only supported by specific Node.js version. We need it to fix `ERR_OSSL_EVP_UNSUPPORTED` errors that happen without it, but those should go away once we upgrade Node.js further.

**Comment by jakubgs** [comment]
Here's a potential fix. I'd appreciate if someone that had the `bad option: --openssl-legacy-provider` error could try it:

* https://github.com/status-im/status-mobile/pull/15633

**Comment by OmarBasem** [comment]
@siddarthkay I am still facing the same issue when using `make run-ios`. Building from Xcode on physical device works now tho (and on Simulator).

**Comment by jakubgs** [comment]
What's the actual error in `ios/logs` tho?

**Comment by OmarBasem** [comment]
@jakubgs I get the following error in terminal: `error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening StatusIm.xcworkspace.`

And the logs file is below:

[react-native-xcode.log](https://github.com/status-im/status-mobile/files/11226408/react-native-xcode.log)

**Comment by jakubgs** [comment]
That log shows no issues with jsbundle usage. Is there no other log file in the `ios/logs` folder? One from Gym?

The error above is useless, it tells us nothing essentially. Which is the usual when dealing with xcode.

**Comment by siddarthkay** [comment]
looking at `react-native-xcode.log` provided by @OmarBasem.  
Although we see no errors inside but this section below seems problematic : 

```log
++ NVM_NPM_PROJECT_NPMRC=/Users/omar/status-dev/status-mobile/.npmrc
++ nvm_npmrc_bad_news_bears /Users/omar/status-dev/status-mobile/.npmrc
++ local NVM_NPMRC
++ NVM_NPMRC=/Users/omar/status-dev/status-mobile/.npmrc
++ '[' -n /Users/omar/status-dev/status-mobile/.npmrc ']'
++ '[' -f /Users/omar/status-dev/status-mobile/.npmrc ']'
++ return 1
++ '[' -n 'Now using node v16.16.0 (npm v8.11.0)' ']'
++ '[' 0 -ne 1 ']'
++ nvm_echo 'Now using node v16.16.0 (npm v8.11.0)'
++ command printf '%s\n' 'Now using node v16.16.0 (npm v8.11.0)'
Now using node v16.16.0 (npm v8.11.0)
```
seems to somehow indicate that the node version v16.16.0 was used. which would not happen if we ran `xcodebuild` within nix context and only would happen when we would open Xcode.app and try a manual build.

Perhaps this could be mitigated by providing a script to open Xcode.app from within a nix shell, maybe that would solve the problem.

I'll also try to reproduce it by installing nvm in my other machine and see if there are any differences in building ios.

**Comment by siddarthkay** [comment]
> to open Xcode.app from within a nix shell

This can be done by 
- `make shell` then
- `open ios/StatusIm.xcworkspace`

**Comment by siddarthkay** [comment]
@OmarBasem : `sudo rm-rf /Users/omar/.nvm/` should work for you.

warning : this will remove `nvm` for you and may impact other projects in your system that rely on it.

**Comment by OmarBasem** [comment]
> That log shows no issues with jsbundle usage. Is there no other log file in the ios/logs folder? One from Gym?

Nope, there is no other log files

> The error above is useless, it tells us nothing essentially. Which is the usual when dealing with xcode.

Yeah I know really :/

**Comment by OmarBasem** [comment]
> warning : this will remove nvm for you and may impact other projects in your system that rely on it.

Oh I don't want to do that

**Comment by OmarBasem** [comment]
> seems to somehow indicate that the node version v16.16.0 was used. 

Can we tell Nix which Node version to use?

**Comment by jakubgs** [comment]
@OmarBasem you fundamentally misunderstand what Nix does. Pinning versions is the whole point of using Nix.
https://github.com/status-im/status-mobile/blob/f6d74df80b9c02dd928a565047ed77839ac27f40/nix/overlay.nix#L49-L50

**Comment by OmarBasem** [comment]
Oh got it! Thanks @jakubgs.

So why is it not using node v18 then

**Comment by jakubgs** [comment]
Because Xcode is fucking stupid and nobody in their right mind should be using it.
I already made at least one attempt to prevent Xcode from using system Node:

* https://github.com/status-im/status-mobile/pull/15226

But apparently that was not enough. There must be some place in which Xcode runs things outside of Nix shell context where `PATH` does not include Nix store paths, or possibly changes the order so system paths come before Nix ones.

**Comment by OmarBasem** [comment]
Speaking of Xcode, is there a way to automate to process of running on physical device. So currently, I have to open Xcode, update signing manually, select device, then build the app (and usually I have to run `pod install` before building). And if I wanted later to run `make run-ios` on Simulator I have to revert `project.pbxproj` and `podfile.lock`. Can this process be automated?

**Comment by siddarthkay** [comment]
@OmarBasem : some experiments on that were done here : https://github.com/status-im/status-mobile/pull/15637#issuecomment-1506405919 but currently on low priority
