### ISSUE TITLE
Viewpoint orientation issue in landscape mode

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#1563]
### User Story
As a user I want to view the DApp in "landscape" mode to complete a task in a DApp, or view more efficiently. This does not happen when I turn my device. 

### Description
_Type_: Bug

### when opening a DApp I want to be able to rotate my screen into landscape mode when turned on its side so for better mobile viewing
_Summary_: Back reference - https://stackoverflow.com/questions/4917664/detect-viewport-orientation-if-orientation-is-portrait-display-alert-message-ad

### Reproduction
 # 

* Open DApp
* Browser window opened , turn device to side 

### Additional Information
[comment]: # na

* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: Both
#### Logs

[comment]: # 

```
...
```

**Comment by pablanopete** [comment]
this one is still a problem from a DApp UX perspective.

**Comment by StatusSceptre** [comment]
Still relevant

**Comment by pablanopete** [comment]
@jeluard I  know you said you were looking into this the other day; any luck finding anything?

**Comment by jeluard** [comment]
Started looking into it but doesn't look straightforward.
I am wondering if it makes sense to lock the viewport at all.

**Comment by cammellos** [comment]
Currently this is not be implemented and likely won't be implemented for a while, please open a feature request as it's currently by design if still interested. Thanks!
