### ISSUE TITLE
Status bar elements are not visible on bottom tab screens when light theme is enabled

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15630]
Followup of https://github.com/status-im/status-mobile/pull/15467 cc @flexsurfer 

**Preconditions:** Light theme is enabled

**Steps:**

1. Login the app
2. Go through different bottom tabs
3. See if status bar elements are visible

**Actual result:** status bar elements are not visible on bottom tab screens when light theme is enabled as they have white color

**IOS:**

![photo_2023-04-12 16 42 35](https://user-images.githubusercontent.com/97245802/231476582-e9331dc4-36a0-4db1-a835-4b518a1241bc.jpeg)

**Android:**

![photo_2023-04-12 16 42 37](https://user-images.githubusercontent.com/97245802/231476591-6161f714-ff9e-40ea-9d63-eb67a9e24c22.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
Related issue: https://github.com/status-im/status-mobile/issues/15260

**Comment by flexsurfer** [comment]
@pavloburykh can't replicate this

**Comment by OmarBasem** [comment]
Just mentioning that there is another open status bar issue: https://github.com/status-im/status-mobile/issues/15343

**Comment by pavloburykh** [comment]
> #15343

Can't replicate this anymore too. Closing the issue.
