### ISSUE TITLE
Double-sized status bar on Galaxy S8

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#1564]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: On Galaxy S8 the height of status bar is much bigger than it should be.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Status bar's height should be smaller.

![2017-08-07 08 50 58](https://user-images.githubusercontent.com/911127/29015238-90d56a3c-7b4d-11e7-9f5f-1cee0ea3bd2f.jpg)

**Comment by lukaszfryc** [comment]
It looks normal on my Galaxy S8 (Android 7.0): 
<img src="https://user-images.githubusercontent.com/7532782/37660769-76212a16-2c53-11e8-94b3-020c9b46cad8.png" width="300">

cc @alwx

**Comment by yenda** [comment]
@alwx is it still relevant ?
