### ISSUE TITLE
'Enable biometric' screen is not included to 'Sign in with QR' flow

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15643]
# Bug Report

## Problem 
There is no 'Enable biometric' screen included in o 'Sign in with QR' flow, which is the part of [design](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4102-310471&t=doHAhTFkZCRW21B8-4)

#### Expected behavior
can see 'Eanble biometric' before syncing data

#### Actual behavior
no screen

### Reproduction

1) Open Status
2) Finish flow Sign in > scan QR

### Additional Information

- Status version: nightly 13/04/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
[Sync from device flow](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4121-311762&t=Sts678zYZz5rzWaw-4) in the Figma design doesn't seem to have Enable biometric screen. Where should I add it in the flow?

@pedro-et @churik

**Comment by ajayesivan** [comment]
Updated Design: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=6953-332528&t=VAS9IiO75lFGpqKV-4

**Comment by ajayesivan** [comment]
I'm unassigning this issue as I am currently not working on it. Please feel free to pick it up. If no one takes it, I will reassign it to myself when I am able to actively work on it again.

**Comment by cammellos** [comment]
@jo-mut could you give us an update please?

**Comment by jo-mut** [comment]
@cammellos this is ready. Am testing it to make sure no further issues
