### ISSUE TITLE
After sending an album chat view needs reload on both receiver and sender sides (after background)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15657]
# Bug Report

## Problem 
Currently to see album message in the way it is intended to be chat view requires re-load. On receiver side there are empty gaps instead of images in the described case.

#### Expected behavior
Can see album messages right after sending-receiving

#### Actual behavior
Sender:

https://user-images.githubusercontent.com/4557972/232059592-22b6d585-ff16-41f1-842d-09345ba4f470.mp4

Receiver: 

https://user-images.githubusercontent.com/4557972/232059566-b5de66eb-1595-43b6-9a5f-d2b3b3870d67.mp4

### Reproduction

1) UserA, UserB: open chat view
2) UserB: send app to the background
3) UserA: send several pictures
4) UserB: take app back and check the chat view

### Additional Information

- Status version: nightly 14/04/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Thanks for reporting this one. This bug tripped me up yesterday while testing some other stuff.

**Comment by cammellos** [comment]
@churik the behavior should be similar to whatsapp:

1) On sender side we should group them immediately 


2) On receiver side, the behavior is correct (not grouped until you reload chat), apart from the fact that they are not loading correctly of course

**Comment by yqrashawn** [comment]
PR at https://github.com/status-im/status-mobile/pull/15735
Although I can't reproduce, the image failed to load issue on develop.
