### ISSUE TITLE
Audio message is not shown in activity center

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15652]
# Bug Report

## Problem 
Empty space instead of the audio message in the activity center in case of replying.

#### Expected behavior
can see a reply in the Activity center

#### Actual behavior

![IMAGE 2023-04-14 12:05:43](https://user-images.githubusercontent.com/4557972/232015446-d7f4db6a-52ff-4ad1-a066-704cb89b5161.jpg)

### Reproduction
**Prerequisites:** joined same community

1) UserA: send a message to the community
2) UserB: reply to UserA with audio message

### Additional Information

- Status version: nightly 14/04;23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
Thanks for spotting this @churik. 

Currently, We don't have a design for this type of notification where the reply message is an audio message. We need input from the design team.

CC: @pedro-et @xAlisher
