### ISSUE TITLE
No preview for twitter links with images

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15656]
# Bug Report

## Problem 
There is no images are shown for tweets that contain them, not sure though it is the issue on our side or with API we're using for unfurling messages in chat
<img width="670" alt="dddd jpg 2023-04-14 13-13-07" src="https://user-images.githubusercontent.com/4557972/232029552-10a072f1-6431-4482-9b44-119c0c9159fb.png">

#### Expected behavior
Can see images as it is on the right side of the attached screenshot

### Reproduction

1) Open Status
2) Send any tweet with image or gif in chat (example: https://twitter.com/AMAZlNGNATURE/status/1646791596170682369?s=20) 

### Additional Information

- Status version: nightly 14/04/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
Apparently Twitter Developer account is required for this. So if we are not willing to get one than it is better to leave it as is.
