### ISSUE TITLE
'Wrong password' error and crash on login

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15653]
# Bug Report

## Problem 

Sometimes, in about 1 case out of 7, an error appears on the login that the wrong password was entered (although the password is 100% correct). When trying again after receiving an error, the login is sometimes successful, but sometimes the app crashes.

<img width="326" alt="Screenshot 2023-04-14 at 12 06 02" src="https://user-images.githubusercontent.com/67952253/232015539-2284d0a2-7c9a-409a-82f6-ff06442d7101.png">

Also sometimes this error occurs with the same conditions:

<img width="325" alt="Screenshot 2023-04-14 at 12 06 36" src="https://user-images.githubusercontent.com/67952253/232015692-19688f97-89ad-4b78-b0b3-ee5e13ae7cfe.png">

It is important to note that the problem is only reproducible on a _specific Wi-Fi_ (the same one that has issues with receiving messages). The case was also tested in two other locations with a connection to other Wi-Fi, as well as in the same location, but on the mobile network.

Logs with the error and crash:

[wrongpassword1.log](https://github.com/status-im/status-mobile/files/11231602/wrongpassword1.log)

For me, the issue is currently reproducible only on Android devices.

#### Expected behavior
Can log in even with an interrupted connection

#### Actual behavior
Error and crash

### Reproduction

1. Create an account 
2. Log out > Log in several times till you get the `Oops, wrong password` error

### Additional Information

- Status version: nightly 14/04
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
```
04-13 17:29:56.855 32305     0 E Go      : panic: close of closed channel
04-13 17:29:56.856 32305     0 E Go      : 
04-13 17:29:56.856 32305     0 E Go      : goroutine 2809 [running, locked to thread]:
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2.(*broadcaster).Close(0x6fdf76b5af?)
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/broadcast.go:167 +0x20
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).Stop(0x4005a40d00)
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:421 +0x70
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/wakuv2.(*Waku).Stop(0x4004652000)
04-13 17:29:56.856 32305  3060 E GoLog   : panic: close of closed channel
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1210 +0x3c
04-13 17:29:56.856 32305  3060 E GoLog   : 
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node.(*Node).stopServices(0x400240d0a0, {0x4005da0000, 0x16, 0x30?})
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node/node.go:298 +0xb8
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node.(*Node).Close(0x400240d0a0)
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node/node.go:218 +0x1e4
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/node.(*StatusNode).stop(0x4004430000)
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/node/get_status_node.go:421 +0x140
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/node.(*StatusNode).Stop(0x4004430000)
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/node/get_status_node.go:407 +0x84
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/api.(*GethStatusBackend).Logout(0x400033bcc0)
04-13 17:29:56.856 32305     0 E Go      : 	github.com/status-im/status-go/api/geth_backend.go:1544 +0x168
04-13 17:29:56.856 32305     0 E Go      : github.com/status-im/status-go/mobile.Logout()

```

This is an issue cleaning up waku-2 cc @siphiuel @richard-ramos

**Comment by richard-ramos** [comment]
@qoqobolo please try with this status-go PR: https://github.com/status-im/status-go/pull/3396

**Comment by cammellos** [comment]
this should be fixed, feel free to reopen if necessary
