### ISSUE TITLE
The 'I understand that my password cannot be recovered' consent checkbox clickable area is too small

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#15662]
# Bug Report
When a user tries to click on the accept consent button, The clickable area is too small.
Causing the user to click multiple times till he get it right

#### Expected behavior
The clickable should be increased or the it should be set as clicked if the user clicks on the whole rectangle

#### Actual behavior
Clickable area is too small

### Reproduction

1) Open Status
2) Generate new keys
3) Type and confirm a password
4) Try to accept consent
![image](https://user-images.githubusercontent.com/33176106/232137997-977e4d27-31ea-40d3-a748-34eba7a82358.jpeg)

**Comment by churik** [comment]
Agree, sometimes I need to tap on the area several times.
Also, it should be visible always, currently, it is shown only when focused on the second field (Confirm your password), would be nice to fix it too

UPD: actually it is fixed [here](https://github.com/status-im/status-mobile/pull/15650)

**Comment by SilentCruzer** [comment]
Can i work on this issue?, I will try making the whole container clickable.

**Comment by ibrkhalil** [comment]
> Can i work on this issue?, I will try making the whole container clickable. 

That's be great, Thank you!

**Comment by ibrkhalil** [comment]
> Can i work on this issue?, I will try making the whole container clickable. 

That'd be great, Thank you!

**Comment by J-Son89** [comment]
@ibrkhalil , @SilentCruzer there is already an open pr for this issue. https://github.com/status-im/status-mobile/pull/15757

Perhaps it was a duplicate 🤔

**Comment by siddarthkay** [comment]
hey @SilentCruzer : Unfortunately I pushed https://github.com/status-im/status-mobile/pull/15757 out without being aware of this issue. 

We'll try to get you something else to work on.
