### ISSUE TITLE
Unable to build app on iOS in anyway

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15671]
I am not able to build the app on iOS. 

`make run-ios` fails with error: `error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening StatusIm.xcworkspace.`

Building from Xcode on Physical device fails with error: `PhaseScriptExecution failed with non-zero exit code`

Building from Xcode on Simulator builds, but the app never goes past the splash screen.

Below is logs file:

[react-native-xcode.log](https://github.com/status-im/status-mobile/files/11254752/react-native-xcode.log)

**Comment by OmarBasem** [comment]
`PhaseScriptExecution failed with non-zero exit code` seems to happen at `Bundle react native code and images` script

**Comment by siddarthkay** [comment]
> Building from Xcode on Simulator builds, but the app never goes past the splash screen.

This a known and different issue logged here : https://github.com/status-im/status-mobile/issues/15477
We may have to tweak the simulator config in Xcode to get this working.

**Comment by siddarthkay** [comment]
`'Now using node v16.16.0 (npm v8.11.0)' `

Looking at your `react-native-xcode.log` file it is clear that while building the iOS App `xcodebuild` is referring to `node` version 16 which is clearly not what we pin in `nix`.

in nix we pin `node` 18, We need to figure out a proper fix on making sure that we don't have discrepancies with system environment `node` version.

I have `node` 19 on my system and I do not face this issue on my system.
I also do not have `nvm` installed and that was also one of the factors that contributed to this issue.

**Comment by siddarthkay** [comment]
> figure out a proper fix on making sure that we don't have discrepancies with system environment `node` version.

This is one possible solution : https://github.com/status-im/status-mobile/pull/15645/commits/5d0acab37b01cc53dae9ea9d57a02ba9b2e5be58
which was available from `react-native` version `0.69` onwards.

I'll experiment with this in a separate PR and see if it fixes our `node` issue

**Comment by siddarthkay** [comment]
@OmarBasem  and @qfrank : can you try this PR  https://github.com/status-im/status-mobile/pull/15673 ? 

make sure to set your `node` path from nix inside `ios/.xcode.env.local` before testing it out.
you can find your `node` path by doing the following :
- `make shell`
- `which node`

**Comment by siddarthkay** [comment]
https://github.com/status-im/status-mobile/pull/15681 fixes the `nvm` issue.
