### ISSUE TITLE
commands-loading refactoring

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#1567]
[comment]: # (Please replace ... with your information. Remove < and >)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Improve commands loading code guided by rules listed in #1495

**Comment by annadanchenko** [comment]
#1622 
still testing

**Comment by annadanchenko** [comment]
new issue #1625 
verified ok #1622

**Comment by annadanchenko** [comment]
tested, looks ok to merge. 
verified #1622 and #1625 
on iOS and Android created 1-1, group and public chats. used all commands available.
on console used all command available and web3 properties. typed, deleted, edited commands. for browse - modified url and sent new in input field. there are some issues with send/receive but they are the same as in develop build (not introduced by this PR)

**Comment by jeluard** [comment]
Fixed in develop
