### ISSUE TITLE
Pinned message preview lacks text of the message

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#15683]
## Problem 
By design message previews for pinned messages should contain the text of the pinned message. Currently they don't

#### Expected behavior
![223492792-c37a35c2-f229-44e5-98c1-5ebb7d65f001](https://user-images.githubusercontent.com/5786310/232849900-fe311654-3cb6-4264-957d-5f54a7bf4def.png)

#### Actual behavior
![223498299-65e518aa-94b0-4e1a-bcbb-836990cdf0d5](https://user-images.githubusercontent.com/5786310/232849935-f9832bcc-7f78-4fa2-997a-4610345d2ab0.png)

### Reproduction

1) Open Status
2) Go to 1-1 or group chat
3) Send a message and pin it
4) Open Status on recipient side
5) Check the last message preview

**Comment by cammellos** [comment]
This is a bit of larger change, I'd say out of scope for mvp, closing for now
