### ISSUE TITLE
[MacOS] Detect`ios-deploy` and install on systems that run `make run-ios-device` if not present.

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#15695]
- [x] when running `make run-ios-device` check if the underlying system is Darwin or not. ( this probably won't run this on a windows or a linux)
- [x] Then check if `ios-deploy` is available or not.
- [x] If not available, Then install the `ios-deploy` dependency via `nix`.

**Comment by jakubgs** [comment]
We can install it via Nix:
https://github.com/NixOS/nixpkgs/blob/d0c06fa3d3982a91aa01bd63ed84020cbde3d3ab/pkgs/os-specific/darwin/ios-deploy/default.nix

**Comment by siddarthkay** [comment]
awesome! Thanks @jakubgs for sharing!
