### ISSUE TITLE
Warning on using TestFairy in development builds

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1569]
### Description

*Type*: Feature

*Summary*: Need to warn users who installed development builds (from apk file on Android or diawi link on iOS) that we are using TestFairy service to record sessions. It means that the session log and video will be recorded and might be viewed by team members to investigate issues for any user on wifi connection with development build installed. Passwords are not stored and not visible in the log/video. For releases available on PlayStore and TestFlight such session recording is not used, so sessions are not recorded.

Example of the session: https://app.testfairy.com/projects/4803622-status/builds/6262390/sessions/34/?accessToken=rwxyGu7bXoF5HXiOJoRI6jHgaG0

It can be done by showing popup on first app launch before user creates and account. Sample text:
"You are using app installed from a nightly build. For testing purposes this build includes session recording if wifi connection is used, so all your interaction with app is saved (as video and log) and might be used by development team to investigate possible issues. Saved video/log do not include your passwords. Recording is done only if app is installed from a nightly build. Nothing is recorded if app is installed from PlayStore or TestFlight"

#### Expected behavior
If app is installed from nightly build (via apk of diawi link) then show warning popup on first app launch before user creates and account.

If it's a release build then 
1. warning should not be shown
2. TestFlight recording should be turned off

### Reproduction

- Install nightly build
- Open Status first time
- Check that warning is shown

**Comment by rasom** [comment]
> It can be done by showing popup on first app launch before user creates and account.
What if user already has account? I suppose that we have to show warning anyway.

**Comment by annadanchenko** [comment]
Yes, you are right. Warning should be shown also for the users who already have an account.

**Comment by annadanchenko** [comment]
Ok to merge. 
iOS and Android apps are tested - warning popup is shown 
- before password is created
- if account already exists then on each new launch before sign in
