### ISSUE TITLE
"Request to join" notification should be marked as read initially instead of 'unread'.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15694]
Follow up for https://github.com/status-im/status-mobile/pull/15627

#### Preconditions:
- User_A is a private community admin

#### Steps to reproduce:
1. User_B sends a request to join the community
2. User_B opens AC

####  Actual result:
The request to join is shown as unread
![image](https://user-images.githubusercontent.com/52490791/233289476-3c810d14-c7e3-420e-a64a-767b001e802f.png)

#### Expected result:
The request to join is shown as read

CC: @smohamedjavid

**Comment by smohamedjavid** [comment]
Thanks, @VladimrLitvinenko.

I have included the fix in this PR (#15627) as it requires changes in `status-go`.

**Comment by smohamedjavid** [comment]
Fixed in https://github.com/status-im/status-mobile/pull/15627
