### ISSUE TITLE
The 'copied' toast is dark on the "generate QR code" page  when a light theme is applied

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15700]
Follow up for https://github.com/status-im/status-mobile/pull/15584

#### Steps to reproduce:
1. Set up light theme
2. Go to -> Syncing -> Reveal sync code
3. Tap the 'Copy code' button

#### Actual result:
The toast is dark
![image](https://user-images.githubusercontent.com/52490791/233349302-e766d8d4-5db2-497c-8567-b733d78efb58.png)

#### Expected result:
The toast is light
![image](https://user-images.githubusercontent.com/52490791/233348701-c0317dd0-ef78-49fc-9682-e89759d3cc66.png)

**Comment by J-Son89** [comment]
Good spot @VladimrLitvinenko, this will be fixed properly once the new profile is started to be worked on as a new stack.

Currently we use the old profile stack in navigation and then navigate from there to syncing, but in the future we will navigate to new profile stack which all be in theme dark and be set correctly, so this will ignore the user's selected theme. 
We can put in a temporary fix but a long term sustainable solution will be added eventually anyway :D

**Comment by VolodLytvynenko** [comment]
> Good spot @VladimrLitvinenko, this will be fixed properly once the new profile is started to be worked on as a new stack.
> 
> Currently we use the old profile stack in navigation and then navigate from there to syncing, but in the future we will navigate to new profile stack which all be in theme dark and be set correctly, so this will ignore the user's selected theme. We can put in a temporary fix but a long term sustainable solution will be added eventually anyway :D

Hey @J-Son89 sorry for the late reply. Just got back from vacation. No need to fix it
