### ISSUE TITLE
The sync code is not compressed on the 'generate sync code' page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15701]
#### Stepd to reproduce:
1. Go to: Settings -> Syncing -> Add Device -> Reveal sync code
2. Check shown sync code

#### Actual result:
The sync code is not compressed
![image](https://user-images.githubusercontent.com/52490791/233350462-ae924fa8-7431-4668-83f5-968ea0be7463.png)

#### Expected result:
![image](https://user-images.githubusercontent.com/52490791/233350316-df76fe2e-51b7-42c0-a0ee-c91883b85e02.png)
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675-178207&t=eOUuyf3sAj7R8GWH-0

#### ENV:
- nightly [21 Apr 2023]

**Comment by cammellos** [comment]
closing for now, this looks like it should be post mvp work

**Comment by Samyoul** [comment]
This can not be post MVP work, the connection string is as compressed as it can be. The designs should be updated if not already, this is definitely a case where development must inform the direction of design.

**Comment by VolodLytvynenko** [comment]
> This can not be post MVP work, the connection string is as compressed as it can be. The designs should be updated if not already, this is definitely a case where development must inform the direction of design.

Thank you for the clarification. I will ask the design team to update the design
