### ISSUE TITLE
[Android] The scrolling  in AC is laggy if a lot of data is added into AC and tried to be scrolled

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15706]
#### Problem:
The scrolling is laggy in AC if a lot of data is added into AC and tried to be scrolled and swiped. Unfortunately, this cannot be reproduced on Android Emulator devices, and also not for some real devices.

#### Steps to reproduce:
1. Add at least 8 notifications into AC (replies, mentions, CRs)
2. Open AC
3. Swipe left-right for some notifs 
4. Try quickly scrolling to the bottom  and top

#### Actual result:
- The notifications are swiped right-left instead of scrolling down and up action
- The swiping and scrolling are laggy

https://user-images.githubusercontent.com/52490791/233411478-b3488362-db86-4679-9461-37041f1ad911.mp4

#### Expected result:
The swiping and scrolling are smooth in AC

#### Devices:
- Huawei p20 light, Android 9

#### ENV:
Nightly: 20 Apr 2023

**Comment by ilmotta** [comment]
Hey @VolodLytvynenko, this PR https://github.com/status-im/status-mobile/pull/20690 was recently merged, where some optimizations were applied in the AC.

When time allows, could you check if this scrolling issue still exists? Thanks

**Comment by VolodLytvynenko** [comment]
> When time allows, could you check if this scrolling issue still exists? Thanks

hi. @ilmotta issue is fixed. Thank you!
