### ISSUE TITLE
Messaging in imported community is not working

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15715]
# Bug Report

## Problem 
As the mobile interface of creating a community is limited and obsolated, there is a requirement to be able to import communities for testing.
At the moment after importing the community the user who has done import couldn't send/receive any messages in it.

#### Expected behavior
- user is an admin (btw it should be taken into consideration that we end up with a community that will have hundreds of admins)
- user can send-receive messages from other users

NOTE:  user can chat with invited users just normally, the issue is reproduced only with the user who imported community

#### Actual behavior

https://user-images.githubusercontent.com/4557972/233649079-1af18622-6554-4857-8a14-e58203e3f390.mp4

### Reproduction

1) On Desktop: create a community A, and copy its private key via the "Backup community key")
2) On Mobile: Communities > + > Import community > Paste key > Tap import
3) Try to send messages from both desktop and mobile

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/11296160/Status-debug-logs.zip)

**Comment by cammellos** [comment]
closing for now as we will be adding a different way to create communities for e2e tests, feel free to reopen if necessary
