### ISSUE TITLE
Refactor profile

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1571]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to refactor the profiles according to #1495 to improve developer experience.

### Description

Currently the structure of the profile directory looks like the following:
```
├── db.cljs
├── edit
│   └── views.cljs
├── events.cljs
├── photo_capture
│   ├── styles.cljs
│   └── views.cljs
├── qr_code
│   ├── styles.cljs
│   └── views.cljs
├── styles.cljs
├── validations.cljs
└── views.cljs
```
According to #1495 it should be:
```
├── edit
│   └── screen.cljs
├── handlers.cljs
├── photo_capture
│   ├── screen.cljs
│   └── styles.cljs
├── qr_code
│   ├── screen.cljs
│   └── styles.cljs
├── screen.cljs
├── specs.cljs
├── styles.cljs
└── validations.cljs
```
1. add letsubs macro in views
2. apply code convention for views (#1495)
3. move nav/preload-data! to navigation.cljs
4. rewrite events using fx and cofx
5. apply code convention for events (#1495)
6. rewrite subs using re-frame best practice (db can be used only in extraction subscriptions)
7. use ns keys in app-db
8. write specs
9. write tests

**Comment by jeluard** [comment]
Fixed in develop
