### ISSUE TITLE
Unable to run or build app on iOS physical device

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15722]
When building from Xcode on physical device I get this error: `PhaseScript execution failed with non-zero exit code`

When building using the new make command to build on physical device `make run-ios-device DEVICE_NAME="device_name"` I get the following error: `Could not find a device named: "...."`

Doing a slight change to the device name, although it is correct (removed `(2)` at the end of its name) gives another error: `error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening StatusIm.xcworkspace.`

**Comment by OmarBasem** [comment]
Hey @siddarthkay, would you please be able to look into this soon?

**Comment by siddarthkay** [comment]
Hmm I thought we had fixed all these issues, but i'll try to recreate these.

From your logs the 1st issue `Could not find a device named: "...."` seems to be related to passing an incorrect name.
Which is not really an issue.

The second issue however seems to be more cryptic. Can you share some more logs here ? 

probably the full output of `make run-ios-device DEVICE_NAME="device_name"` and the logs file located at `ios/logs` will help me debug further.

**Comment by siddarthkay** [comment]
Xcode version mismatch could also be the case, can you let me know the version of Xcode that is installed in the machine producing this error? @OmarBasem

**Comment by OmarBasem** [comment]
@siddarthkay I have Xcode `14.2`.

These are the same errors I was having as in our last chat. Unfortunately, the logs for this one are not useful as I showed you before:
```
+ set -x
+ DEST=/Users/omar/Library/Developer/Xcode/DerivedData/StatusIm-aeklsqlyrtttwtbgdmbyijabihbg/Build/Products/Debug-iphonesimulator/StatusIm.app
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0
```

**Comment by siddarthkay** [comment]
We've upgraded to `Xcode` `14.3` in `CI`, perhaps better if we do that locally as well.
Can you try upgrading your `Xcode` to `14.3` and see if this fixes your issue or produces a different output?

**Comment by OmarBasem** [comment]
Alright I will try and let you know

**Comment by siddarthkay** [comment]
similar reports by other users: 

1. https://support.magic-pod.com/hc/en-us/articles/10320009619609-Original-error-Unable-to-launch-WebDriverAgent-because-of-xcodebuild-failure-xcodebuild-failed-with-code-70
2. https://discuss.appium.io/t/xcodebuild-exited-with-code-70-and-signal-null-ios-13-5-1/31316
3. https://developer.apple.com/forums/thread/703417

What does error code 70 mean?
According to : https://stackoverflow.com/a/60544869

> xcodebuild error 70 means that the target for the build was not found. It could be due to a mismatch of iOS versions, parameters, or (if using a real device) the UDID being wrong, or the device was not connected, switched off or locked.

**Comment by OmarBasem** [comment]
@siddarthkay I have updated Xcode to v `14.3` and still getting the same error from inside xcode.
Building using the `make` command also still does not work. It gives me the following error:
```
error Could not find a device named: "Omar’s iPhone (2)". Available devices:
  - Omar’s MacBook Pro (602E09B1-5A05-51D0-A434-38F7EA2A3413)
  - Omar’s iPhone (2)
 ```
It says couldn't find a device named "X", and then tells me that "X" is available...

**Comment by OmarBasem** [comment]
@siddarthkay so renaming my physical device to `iPhone-13-Pro` made it work. It seems having one or some of (spaces, apostrophes, brackets) in the device name can be problematic.

**Comment by OmarBasem** [comment]
Building from Xcode is still not working tho, but I guess not a priority now

**Comment by OmarBasem** [comment]
So building on Physical device is again not working today :/

**Comment by cammellos** [comment]
@OmarBasem would you mind trying again if that's currently supported? feel free to reopen the issue if still not working, thank you
