### ISSUE TITLE
Generated usernames should be deterministic

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1573]
i.e. same account should always have the same username generated for it, e.g. based on address

### User Story

As a user I want all of my accounts to have the same username generated in any context in the application. I also want other users with whom I communicate to see me in any chat UIs under the same generated username as I see myself in the app.

### Description
)
*Type*: Feature

#### Actual behavior

Currently, usernames are generated in a non-deterministic way and the same account may appear under different display names depending on the context and circumstances.

**Comment by goranjovic** [comment]
@jarradh What do you think about using public-key, not specifically address for this. This would be consistent with how identicons are generated.

**Comment by rasom** [comment]
@goranjovic it should be fine to use public keys

**Comment by jeluard** [comment]
Fixed in develop
