### ISSUE TITLE
Wrong password after hot reloading in development

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#15746]
# Bug Report
got wrong password error after hot reloading in dev

#### Expected behavior
can log in with the correct password

#### Actual behavior
got wrong password error

### Reproduction

1) Open Status
2) login
3) change file to trigger hot reloading
4) login with the same password

### Additional Information

this only happens when hot reloading in login state

https://user-images.githubusercontent.com/15090582/234496914-b638e9e0-28ee-431a-b278-7502975c45fa.mp4

- Status version: develop branch 
- Operating System: iOS

**Comment by yqrashawn** [comment]
error 
```
 INFO  INFO [status-im2.contexts.onboarding.profiles.view:164] - error => node is already running
 INFO  INFO [status-im2.contexts.onboarding.profiles.view:164] - error => sql: database is closed
```

**Comment by flexsurfer** [comment]
you need to disable fast refresh, i guess that now after RN upgrade it's enabled by default

open simulator -> cmnd +D -> disable fast refresh
