### ISSUE TITLE
Incorrect mentions alignment (Android) 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15745]
Followup of https://github.com/status-im/status-mobile/pull/15723
Originally reported to @John-44 [here](https://github.com/status-im/status-mobile/pull/15723#issuecomment-1522059516)

Reproducible on Android. 

**Steps:** 

1. Send text + mention in any chat
2. Check if mention text bottom is aligned to regular text bottom

**Actual result:**  mention text bottom is not aligned to the regular text bottom

![photo_2023-04-25 22 54 45](https://user-images.githubusercontent.com/97245802/234388335-a301961e-91bf-4e29-8926-3a2af9774f16.jpeg)

**Expected result:** mention text bottom is aligned to the regular text bottom. Below is the screenshot of correct alignment on IOS

![photo_2023-04-25 22 54 50](https://user-images.githubusercontent.com/97245802/234388379-419ff728-619e-458a-a13e-596f2e49f851.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Is this fixed?

**Comment by pavloburykh** [comment]
> Fixed styling issues for mention in the chat text #15723

This one is partially fixed. There is a separate open issue related mentions alingment https://github.com/status-im/status-mobile/issues/15745 I will close current issue.
