### ISSUE TITLE
`Unfortunately, Status has stopped` popup after closing app when Auction house was opened [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1575]
### Description

*Type*: Bug

*Summary*: `Unfortunately, Status has stopped` popup is shown for ~0.3 sec after Status app was closed in case Auction house Dapp was opened in Status.

``` 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference at com.github.alinz.reactnativewebviewbridge.StatusBridge$1.run(StatusBridge.java:28)
```
#### Expected behavior
no popup is shown
#### Actual behavior
`Unfortunately, Status has stopped` popup

### Reproduction
session: https://app.testfairy.com/projects/4803622-status/builds/6262520/sessions/28/?accessToken=PWatFV5oKl0wNgYh0dn6uuKySV8

- Open Status
- Open Contacts and tap on Auction house
- Tap on Create auction
- after screen is loaded, close Status and watch for a popup (shown for a short period of time and than closed)

### Additional Information
* Status version: develop build 0.9.8-114-gf91c480a+ and CallRPC branch  0.9.8-113-g25c893a5+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
and Android emulator

**Comment by retro** [comment]
I wasn't able to reproduce this bug. I've tested it both on the emulator and on the real device (Lenovo Vibe P1m). Is it possible that some unrelated commit fixed this bug?

**Comment by annadanchenko** [comment]
ok, will recheck today in latest develop

**Comment by annadanchenko** [comment]
@retro On latest develop build  0.9.10-47-gb1bf5a4f+ (Android 6.0.1 real device Samsung Galaxy S6) with same steps:
1. There is no popup Status has stopped
2. There is still crash reported in TestFairy and logcat. I suggest to investigate why it happens and handle this error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at com.github.alinz.reactnativewebviewbridge.StatusBridge$1.run(StatusBridge.java:28)`

TestFairy: https://app.testfairy.com/projects/4803622-status/builds/6469416/sessions/22/?accessToken=5YQM-dMpJZ6kuIZWLI-KHe2/yYk
Logcat:  [crash3.log.txt](https://github.com/status-im/status-react/files/1269894/crash3.log.txt)

**Comment by Monali109-zz** [comment]
@annadanchenko  Unfortunately, Status has stopped.
Status Version -
artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk

Same on Device - Lenovo A6000
OS - Android 4.4.4

**Comment by annadanchenko** [comment]
cant reproduce
