### ISSUE TITLE
Adjust Identifiers page to do highlighting as shown in designs

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15752]
Currently there is an implementation of the identifiers page as per:
https://github.com/status-im/status-mobile/pull/15684

However this page does not add the highlighting of each identifier as is shown in the designs
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2926-331925&t=grduQVZyYrhURE0D-0

Adjust this component so on each index of the carousel the correct identifier is being highlighted.

**Comment by websky112** [comment]
Hi Jamie. This is Watson

**Comment by J-Son89** [comment]
I can take over this branch 👍 
https://github.com/status-im/status-mobile/pull/15925
