### ISSUE TITLE
Auction house does not respond or app crashes with SIGSEGV [callRPC]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1576]
### Description

*Type*: Bug

*Summary*: 
during first sync: iPhone 7 plus and iphone 6s : app crashes with SIGSEGV if open Auction house, tap on Create auction and wait for 1 minute on new screen with auction details. App installed from today's develop build does not crash in the same scenario 

after sync is done, next runs: on iPhone 6s: app does nothing if open Auction house and tap on Create auction. Expected: screen with auction details is shown.

#### Expected behavior
Auction details screen is shown
#### Actual behavior
app crashes or does not respond on tap 
### Reproduction
on iphone 7 plus:
- Open Status for the first time, create new account
- Open Auction house DApp
- Tap on button "Create an auction"
- if screen with auction details is opened then wait for 1-2 minutes and do nothing
session: https://app.testfairy.com/projects/4803590-status/builds/6262519/sessions/43/?accessToken=wLBbQSQPXT-YZn4gcMejM0IZnZI

on iphone 6s:
- after initial sync is completed, re-launch app
- Open Auction house DApp
- Tap on button "Create an auction"

### Additional Information
* Status version: callRPC branch 0.9.9d113
* Operating System: 
Real device iPhone 7 plus, 10.3.2 - crash
Real device iPhone 6s, iOS 10.3.3 - does not respond

**Comment by rasom** [comment]
I can't reproduce this on both real device and simulator

**Comment by annadanchenko** [comment]
works ok on new build
Android: http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-fc2946.apk
iOS: https://i.diawi.com/R7ZfdH
