### ISSUE TITLE
System message about pinning a message in chat/channel is not shown

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15763]
**Steps:** 

1. Open any chat/channel
2. Send a message
3. Pin a message
4. See if system message about pinning a message appeared 

**Actual result:** System message about pinning message in chat does not appear

![photo_2023-04-27 10 22 52](https://user-images.githubusercontent.com/97245802/234789440-a9688384-068b-4d81-ac29-d55b373c6520.jpeg)

**Expected result:** System message about pinning message in chat appears

![photo_2023-04-27 10 20 52](https://user-images.githubusercontent.com/97245802/234788915-999e0c89-9377-4797-a4f6-8616320036df.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by rasom** [comment]
<img width="345" alt="Screenshot 2023-04-27 at 11 14 00" src="https://user-images.githubusercontent.com/2364994/234817247-7067cf9a-9744-41aa-b744-f403ef9d95f8.png">


@pavloburykh I tried it in `develop` and can not reproduce

**Comment by pavloburykh** [comment]
@rasom thanx for checking. The bug is not reproducible for me any more either. closing this issue. Will re-open in case if we face the bug again.
