### ISSUE TITLE
Upgrade Reanimated to V3

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15764]
Now that we have upgraded to RN v 0.67.5, we can upgrade to reanimated v3

**Comment by OmarBasem** [comment]
Upgrading reanimated to v3 is currently dependent on RN upgrade to v 0.71+ due to other problem with nix.

**Comment by Parveshdhull** [comment]
- [ ] Once upgraded to reanimated to v3, we should remove redundant call for enabling layout animations. (https://github.com/status-im/status-mobile/pull/16832)
