### ISSUE TITLE
Password input should be disabled after clicking login

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#15779]
#### Expected behavior
User can type in the password field after clicking login

#### Actual behavior
Password input should be disabled after clicking login

**Comment by Parveshdhull** [comment]
Please also check: https://github.com/status-im/status-mobile/pull/15845#issuecomment-1542200631
Issue 1: https://github.com/status-im/status-mobile/pull/15845#issuecomment-1541878431
Issue 2: https://github.com/status-im/status-mobile/pull/15845#issuecomment-1541878598

Thank you @VladimrLitvinenko for finding these

**Comment by ibrkhalil** [comment]
Noice
