### ISSUE TITLE
Design notes: slideshow issues

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15776]
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1902-133425&t=h8BhUXUBEHnWas6r-4)

### Slideshow > Slideshow
- [x] Fix/update illustration, should not be cropped on top
- [x] #15992
- [x] "You're already use Status" - change font size - should be in regular, not medium
- [x] "By continuing"
     - "By continuing..." text should be in regular, not in medium.
     - Terms of Use is the only part that should be in medium
     - Also force to two lines like in design
- [x] Change  color, opacity and blur of the drawers - doesn't match design
- [x]  Change button size, should be 32x32 version

### Slideshow > Sign In-Transition
- [x] The background illustration should be the slideshow illustration, not an additional one (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1902:133425#427905184))

### Slideshow > Transition
- [ ] Change transition to the bttom > top (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1902:133425#427916978))

**Comment by J-Son89** [comment]
@churik , @rahulpsingh I think Slideshow > Sign In-Transition should be handled in a separate issue as it's a common problem -> https://github.com/status-im/status-mobile/issues/15877

**Comment by rahulpsingh** [comment]
I'll fix the swiping action part in the next PR associated to this ticket: #15992
