### ISSUE TITLE
Unintended element activation on taps in composer (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15777]
Reproducible on Android:

**Case 1:** Context menu appears while tapping below input fields area or on gallery/stickers buttons

**Steps:** 
1. Activate input field
2. Tap on area below input field or on gallery/stickers buttons

**Actual result:** context menu appears
**Expected result:** context menu appears on tap inside active input field 

Actual result: 

**Case 2:**  microphone permissions modal appears on tapping aside from audio message button area

**Preconditions:** microphone permission is not granted yet

**Steps:** 
1. Tap on area aside from audio message button
2. Observe the result

**Actual result:** microphone permissions modal appears
**Expected result:** context menu appears on tap inside active input field 

See video below for both case 1 and 2 

https://user-images.githubusercontent.com/97245802/235183288-91be4be3-332a-440d-bdba-26898f90a607.mp4

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
Adding `blocked` label since the composer is being re-implemented by @OmarBasem.

**Comment by OmarBasem** [comment]
@pavloburykh still relevant?

**Comment by pavloburykh** [comment]
> @pavloburykh still relevant?

fixed here https://github.com/status-im/status-mobile/pull/15818 Closing the issue. Thanx @OmarBasem
