### ISSUE TITLE
Check avatar font size

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#15793]
The font size is off in the avatar:

https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588832

Ideally this is implemented in status-go https://github.com/status-im/status-go/issues/3429 , but it's fine to go for a quicker fix on status-mobile, if that doesn't take long.

**Comment by ajayesivan** [comment]
Closed via https://github.com/status-im/status-mobile/pull/15801
