### ISSUE TITLE
Profile image set from gallery is not fetched on identifiers screen and inside account until re-login

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15794]
I consistently experience this issue on my Samsung Galaxy A52, Android 12, while @qoqobolo encounters it occasionally on her Huawei P40 Lite, Android 10.

Also, reproduced on iPhone 10, IOS 14.1

**Steps:** 

1. Proceed with creating/restoring multiaccount
2. Set up profile picture from gallery (not from camera) on Create profile step. Select picture which has not been uploaded before on current build. 
3. Continue onboarding
4. Pay attention if selected profile picture is fetched on Identifiers screens and inside the account

**Actual result:** profile picture is not fetched on identifiers screen. Inside account profile picture appears only after re-login. 

https://user-images.githubusercontent.com/97245802/235621151-6de2ccdd-a438-4dd9-a465-31473d76b3ba.mp4

**Expected result:** profile picture is fetched on all screens after set up. 

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Hey! I was just working on reproducing it on both Pixel 7a and Android emulator, and had no luck — everything gets fetched. Any chance it got figed in the meantime?

**Comment by pavloburykh** [comment]
> Hey! I was just working on reproducing it on both Pixel 7a and Android emulator, and had no luck — everything gets fetched. Any chance it got figed in the meantime?

Hey @alwx! Issue still partially exists. But it is reproducible randomly. We will investigate and update current issue or log a new one. Thank you.

**Comment by churik** [comment]
It is reproducible every time if follow these steps:
- Create a new profile > Generate keys
- On Create profile screen:
1) set name
2) set non-default accent colour (not sure it is required, but with nin-default it is reproducible every time for me)
3) set photo from the gallery > proceed

Buil: nightly 26/07/2023

https://github.com/status-im/status-mobile/assets/4557972/bb842699-5476-424d-875f-85a3e40e2693

**Comment by churik** [comment]
сс @Parveshdhull @alwx

**Comment by Parveshdhull** [comment]
Hi @churik, Thank you very much for detailed steps. Looks like using non default color is required for reproduction of issue.

Hi @alwx, Are you working on the issue? Otherwise I can take a look

**Comment by alwx** [comment]
@Parveshdhull I'm busy with other stuff right now, feel free to take this one!

**Comment by Parveshdhull** [comment]
We are passing image path while creating account using `onboarding-2/create-account-and-login`. And In `login.core` in `::get-chats-callback` event we are fetching identity images using `multiaccounts_getIdentityImages` but this call is returning nil.

Looks like problem is in status-go. Please can you take a look @cammellos @qfrank ? 

Logs: [geth.log](https://github.com/status-im/status-mobile/files/11891768/geth.log)

**Comment by Parveshdhull** [comment]
Happens randomly, and only on device. Not able to reproduce on emulator. Maybe some kind of race condition?

**Comment by alwx** [comment]
I'm pretty sure it's some race condition and that it's status-go related. I was unable to reproduce it using the steps above provided by @churik

**Comment by pavloburykh** [comment]
> I'm pretty sure it's some race condition and that it's status-go related. I was unable to reproduce it using the steps above provided by @churik

@alwx have you tried to reproduce on IOS?

**Comment by pavloburykh** [comment]
@alwx but I agree. It is not reproducible every time in my case. But I have faced this issue on IOS more often.

**Comment by alwx** [comment]
@pavloburykh yes, on iOS but not on real device.

**Comment by churik** [comment]
it is reproducible almost every time if proceed from 3 screen very fast as far as I saw

**Comment by pavloburykh** [comment]
> it is reproducible almost every time if proceed from 3 screen very fast as far as I saw

You are right @churik.

**Comment by qfrank** [comment]
thank you FYI, I'll look into it

**Comment by qfrank** [comment]
> It is reproducible every time if follow these steps:
> 
> * Create a new profile > Generate keys
> * On Create profile screen:
> 
> 1. set name
> 2. set non-default accent colour (not sure it is required, but with nin-default it is reproducible every time for me)
> 3. set photo from the gallery > proceed
> 
> Buil: nightly 26/07/2023
> 
>  FILE.2023-06-26.10.50.25.mp4

it's hard to reproduce even follow `if proceed from 3 screen very fast` 
it would be great if you can provide the log 🙂 @churik

**Comment by churik** [comment]
@pavloburykh when you have a chance, please, re-check it on your device.

With https://github.com/status-im/status-mobile/issues/15794#issuecomment-1607006756 it is not reproducible anyomre on nightly 04/07/23

**Comment by pavloburykh** [comment]
@churik closing the issue as it has been fixed by https://github.com/status-im/status-mobile/pull/16434 on status go side.
