### ISSUE TITLE
App gets stuck on 'Generating Keys' page during onboarding

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15805]
#### Preconditions:
- User_A generates sync code and makes it invalid (sync code becomes invalid if it has been used once)

#### Steps to reproduce:
1. User_B scans the invalid sync code
2. User_B goes to 'Im new to Status' and creates an account manually

#### Actual result:
The app is frozen on The 'generating keys' page

https://user-images.githubusercontent.com/52490791/235983825-7be80a72-9260-434d-8814-22f83eef11f1.mp4

#### Expected result:
The account is created

#### Logs: 
[android_logcat.txt](https://github.com/status-im/status-mobile/files/11385009/android_logcat.txt)

**Comment by siddarthkay** [comment]
I have randomly seen the app get stuck on "Generating Keys" on IOS as well, unfortunately I do not have any logs.
But it does get stuck for quite a while.

**Comment by siddarthkay** [comment]
Today this happened to @jo-mut as well on iOS Simulator.

**Comment by churik** [comment]
@VolodLytvynenko please, close if it is not reproducible anymore, thank you!

**Comment by VolodLytvynenko** [comment]
@churik Not valid any more. Thanx!
