### ISSUE TITLE
Tapping Request to Join community disclaimer does not result disclaimer checkbox update

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15803]
Might be regression of https://github.com/status-im/status-mobile/pull/15757 cc @siddarthkay 

**Steps:** 

1. Open some unjoined community page
2. Tap Request to Join Community button
3. Tap on "I agree with the community rules" disclaimer
4. See if check mark appeared in checkbox

**Actual result:** checkmark does not appear in checkbox though Request to join button becomes active. Checkbox can be affected only by tapping directly within checkbox area. 

https://user-images.githubusercontent.com/97245802/235909309-d78d8290-7e67-4d57-967d-4e4ff79adc0b.mp4

**Expected result:** tapping disclaimer should update checkbox. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
Seems so @pavloburykh , should be a quick fix, I'll take it up
