### ISSUE TITLE
Sometimes message in 1x1 chat is shown as "Pending"

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1580]
# Description

Type: _Bug_

Summary: Sometimes when syncing is in progress I add new contact within scanning QR code and the contact is added to contact list, however new chat is not shown for the recipient. When I send a message as originator the recipient also doesn't see the incoming message, moreover the outgoing message is shown as "Sending" (not "Sent"). I am not 100% sure of the root cause of this issue but looks like it happens when syncing is in progress so the app consumes a lot of resources , especially on slow devices. This issue was encountered using iPhone 5s iOS 10.3.3 as recipient and Galaxy s6 Android 6.0.1 as originator

### As Alice:

- Open Status and login
- Add Bob to your contacts by scanning QR code
- Write to Bob "First message" (notice the message status is stuck on "sending")

### As Bob:

- Open Status and login
- Open Chats
- Notice that no new chat is created because message is stuck on Sending

### As Alice:

- Get back to Alice and delete chat with Bob
- Send new message "Second message" to Bob

### As Bob:

- Tap on new chat with unknown contact (Alice)
- Reply to Allice "Hi alice [add time]"

### As Alice

- Wait for message from Bob
- Write to Bob "will delete this chat [add time]"
- Go back to Chats screen (tap on <)
- In Chats screen tap "..." in top right corner
- In menu select Edit chats
- Next to the chat with Bob tap on "..."
- Tap on Delete chat
- Open Contacts
- Tap on Bob
- In chat write to Bob new message "NEW after delete on [add time]

### As Bob

- check where is the message from Alice "New after delete" placed
- Pay attention that the very first message "First message" is now at the end of the chat

# Additional Information

Status version: 0.9.8-114-g243cb7de+ branch
Operating System: Android and iOS
TF: https://app.testfairy.com/projects/4803622-status/builds/6285165/sessions/8/?accessToken=KCfHyfM5ggARF/JqlxuvPex6H5k

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/1195#issuecomment-321187878 for additional context

**Comment by oskarth** [comment]
Review not needed on our side. Presumably testing is, though. This issue is just along for the ride of `status-go` issue progress.

**Comment by oskarth** [comment]
https://github.com/status-im/status-go/pull/279 has been merged in https://github.com/status-im/status-go/commit/9463d3843aa237d5ddc79f3cc2187a422d4065b3 - this issue blocked for testing until we are running that version (see https://github.com/status-im/status-react/pull/1584)

**Comment by oskarth** [comment]
Not sure what the proper state of this is, but I'm guessing it still needs testing.

**Comment by asemiankevich** [comment]
Can't reproduce it in recent develop ` 0.9.10-159-g4b6f920e+ (1716)` , closing
