### ISSUE TITLE
Some mentions bugs

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15800]
- [ ] when editing a message with a mention
- [ ] when adding mention during editing
- [ ] when replying to messages with a mention

Video: https://github.com/status-im/status-mobile/issues/15331#issuecomment-1506940312

**Comment by ilmotta** [comment]
@churik This is a rather old issue, in which case my question is, are the issues described in the video you recorded still reproducible? If they aren't we can close this issue.

**Comment by ilmotta** [comment]
Bumping again the issue @churik :) When possible, it would be good to know the situation about the chat experience from the QA perspective given the changes to the composer. The chat in the app has to work extremely well to retain users and for that, we should probably prioritize some things for 2.32, and the problems from this issue, if still relevant could be considered.

**Comment by mariia-skrypnyk** [comment]
> Bumping again the issue [@churik](https://github.com/churik) :) When possible, it would be good to know the situation about the chat experience from the QA perspective given the changes to the composer. The chat in the app has to work extremely well to retain users and for that, we should probably prioritize some things for 2.32, and the problems from this issue, if still relevant could be considered.

Hey @ilmotta !

Thanks for raising this up.

Me and @Horupa-Olena 🤝 checked how `mentiones` look like on both `iOS` and `Android` platforms considering the new simplified look of the 1-1 and group chats.
We tried various combinations of scenarios mentioned [here](https://github.com/status-im/status-mobile/issues/15331#issuecomment-1506940312): 

- when editing a message with a mention
- when adding mention during editing
- when replying to messages with a mention

**iOS** : looks great!

![Image](https://github.com/user-attachments/assets/90de2683-848d-4bea-b798-056a3772c631)

👆 The only moment should be discussed is it ok for us that when you do a reply on mention it is not marked in any special style.
(marked as yellow on my screenshot)

**Android** : `mentiones` have some misalignment compared to the other text

![Image](https://github.com/user-attachments/assets/3d6ad0ba-2271-4b2a-860d-a0232c2591d7)

Let me know if you consider smth from this should be reported separately or you need smth extra.

**Comment by churik** [comment]
Checked in TG, it works the same way, the discord shows picture and I can tap on mention from reply. 
I believe this issue can be closed then and the other small `ui-polish` opened to align mention from [here](https://github.com/status-im/status-mobile/issues/15800#issuecomment-2396874597)

@Horupa-Olena would you mind to create one?
Thanks!
