### ISSUE TITLE
Album is shown as compressed for sender user in chats after sending images

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15817]
### Steps to reproduce:
1. Go to any chat
2. Open images gallery -> selected at least 2 images
3. Send selected images

### Actual result:
The album is shown as compressed
![image](https://user-images.githubusercontent.com/52490791/236242042-def37e25-5b2c-40d4-bcb2-5d1421257059.png)

### Expected result:
The album is shown as expanded after initial images sending and should become as compressed only after the chat is reopened

https://user-images.githubusercontent.com/52490791/236243573-7379fb09-3ef6-4e89-b19e-1198b0e453f9.mp4

### ENV:
- Nightly: 4 May 2023

**Comment by cammellos** [comment]
@VladimrLitvinenko I believe that's the correct behavior, @OmarBasem could you confirm please?

thanks

**Comment by OmarBasem** [comment]
Yes @cammellos I believe that's what you told me in a recent issue https://github.com/status-im/status-mobile/pull/15735#discussion_r1176258915 when I had the same question. We used to send album images separately, but now we show them grouped into an album immediately.

**Comment by VolodLytvynenko** [comment]
Hi @cammellos @OmarBasem, I understand now. I wasn't familiar with the description in https://github.com/status-im/status-mobile/pull/15735#discussion_r1176258915, so I tracked it as an issue. Thanks for letting me know!
