### ISSUE TITLE
[Android] Play button in audio messages freezes after background

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15819]
# Bug Report

## Problem 
Follow up from https://github.com/status-im/status-mobile/pull/15594
The issue is still reproducible, but not in 100% of cases. 

Steps to reproduce:
1. Record and send an audio message
2. Start playing audio, pause it
3. Send the app to the background
4. Open the app
5. Tap play

Here is an example of when it reproduces:

https://user-images.githubusercontent.com/67952253/236413553-43d87383-604c-41c0-9da8-a0542f27334e.mp4

And here is when it works fine:

https://user-images.githubusercontent.com/67952253/236413603-cb755520-c928-435c-a741-bf92e6bb0b74.mp4

### Additional Information

- Status version: nightly 5/05
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
@VladimrLitvinenko there is a similar issue
