### ISSUE TITLE
A list of developer experience problems

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15827]
The following is a list of current developer experience issues when running the app in debug mode, related to `shadow-cljs`, `metro`, emulators, physical devices, and building and running the app. Feel free to add any other issues you are facing.

### iOS
- [x] https://github.com/status-im/status-mobile/issues/15826
- [x] https://github.com/status-im/status-mobile/issues/15722
- [x] https://github.com/status-im/status-mobile/issues/14595

### Android
- [x] https://github.com/status-im/status-mobile/issues/15872
- [x] https://github.com/status-im/status-mobile/issues/15808

### Shadow-cljs
- [ ] https://github.com/status-im/status-mobile/issues/14846, https://github.com/status-im/status-mobile/issues/14764

### Metro
- [x] https://github.com/status-im/status-mobile/issues/15862
- [x] https://github.com/status-im/status-mobile/issues/15869
- [x] https://github.com/status-im/status-mobile/issues/15600

### Other
- [x] https://github.com/status-im/status-mobile/issues/15792

**Comment by ilmotta** [comment]
Related to shadow-cljs, we might fix a lot of issues once we upgrade it because if we look at shadow-cljs's changelog there has been tons of bug fixes. Not long ago I opened a PR to upgrade shadow-cljs https://github.com/status-im/status-mobile/pull/15417, along with the necessary code changes to upgrade ClojureScript. I want to resurrect that PR once RN upgrades are sort of finished, because that was the blocker.

So I'd say there's hope in that front.

**Comment by OmarBasem** [comment]
@ilmotta Is the recent RN upgrade to 0.67.5 not sufficient?

**Comment by ilmotta** [comment]
> @ilmotta Is the recent RN upgrade to 0.67.5 not sufficient?

It's probably not enough @OmarBasem. I can try again at some point this week, but I wouldn't hold my hopes high. Quoting myself here:

> I'm hopeful that once we upgrade to RN 0.70+, the new Hermes version might behave differently and give us another shot at upgrading shadow-cljs and ClojureScript. If after the RN upgrade we still can't upgrade shadow-cljs, then I'll try to report a detailed issue to the shadow-cljs maintainer.
>
> -- https://github.com/status-im/status-mobile/pull/15417#issuecomment-1478598755

**Comment by OmarBasem** [comment]
Some info about my machine

#### Device Info:
  Model Name:	                 MacBook Pro
  Chip:	                                 Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	                         16 GB

#### Firewall Settings:
  Mode:	Allow all incoming connections
  Firewall Logging:	Yes
  Stealth Mode:	No

#### Software Info:
  System Version:	macOS 13.1 (22C65)
  Kernel Version:	Darwin 22.2.0
