### ISSUE TITLE
iOS Physical device fails to connect to metro

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15826]
A lot of times, after starting `shadow-cljs` and `metro bundler`, then trying to start the app on iOS physical device, it stalls for a few seconds on the splash screen before crashing. I have to try starting the app 5-7 times before it finally connects to metro. Re-building and re-installing the app does not solve the issue. Sometimes, it just never connects to metro.

**Comment by Parveshdhull** [comment]
Adding for reference: might be related to https://github.com/status-im/status-mobile/issues/15312
