### ISSUE TITLE
Simplify & fix the way names for contacts are being extracted and used

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#15820]
There are multiple subs and way of using them to get the name of a contact.
1. `:contacts/contact-two-names-by-identity`
2. `:contacts/contact-name-by-identity` (which basically duplicates the first one with no reason)
3. `{:keys [primary-name]} @(re-frame/subscribe [:contacts/contact-by-identity chat-id])`
4. `{:keys [preferred-name]} @(re-frame/subscribe [:contacts/contact-by-identity chat-id])`
5. `(or preferred-name display-name name)`
6. `[primary-name secondary-name] (rf/sub [:contacts/contact-two-names-by-identity from])`
7. (probably more)

The usage of all those functions is very inconsistent and also very confusing & might probably lead to display names being different in different parts of apps.

The way of fixing it and making it all much more consistent is by updaing `:contacts/contact-by-identity` and making it return `:display-name` as a part of the contact. This `:display-name` should be used anywhere where the name of a contact should be displayed.

**Comment by flexsurfer** [comment]
it was refactored recently so we should use only primary-name and secondary-name for contacts, the confusion is only we have in old code, and for user profiles, sometimes we show user profile mixed with contacts, but it doesn't have primary-name or secondary-name
