### ISSUE TITLE
Multiple duplicate notifications in AC when receiving images with a mention

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15834]
# Bug Report

## Problem 
The mentioned user receives as many notifications in the activity center as many images are added to the message.

#### Expected behavior
One mention = one notification

#### Actual behavior

https://user-images.githubusercontent.com/67952253/236830094-112991cd-ca9b-4592-bd9e-17d779fd52bc.MP4

### Reproduction

1. UserA and UserB join the same community or group chat
2. UserA opens the home screen
3. UserB selects several images from the gallery and adds one mention of UserA as a description of the message, sends the message
4. UserA checks AC

### Additional Information

- Status version: nightly 8/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Is there some settings that should be enabled first to see mentions in AC?
I only see a grey dot on community channel on mention.

**Comment by qoqobolo** [comment]
> Is there some settings that should be enabled first to see mentions in AC?

No, it should work by default.

> I only see a grey dot on community channel on mention.

This is weird, I've just checked this on the latest nightly and it works just fine for me. 
Steps:
1. UserA adds UserB to contacts, creates a community, invites UserB, and opens the home screen
2. UserB joins the community and mentions UserA

Can you clarify wich steps are you trying?

**Comment by ibrkhalil** [comment]
> > Is there some settings that should be enabled first to see mentions in AC?
> 
> No, it should work by default.
> 
> > I only see a grey dot on community channel on mention.
> 
> This is weird, I've just checked this on the latest nightly and it works just fine for me. Steps:
> 
> 1. UserA adds UserB to contacts, creates a community, invites UserB, and opens the home screen
> 2. UserB joins the community and mentions UserA
> 
> Can you clarify wich steps are you trying?

Apologies for the misleading comment, My build was ancient 🧓🏻
