### ISSUE TITLE
Implement Onboarding recovery phrase screen as designs

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#15832]
# Problem

The onboarding screen to set the seed phrase is not looking and behaving as expected according to [designs](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2647-285839&t=htPybAlrTsdLIdJs-4)

We need to implement it

## Acceptance Criteria

The screen looks and behaves as designs.

**Comment by ajayesivan** [comment]
@ulisesmac Duplicate Issue https://github.com/status-im/status-mobile/issues/15476?

**Comment by ulisesmac** [comment]
> @ulisesmac Duplicate Issue #15476?

Yes! duplicate, I'm going to close this one, thanks! @ajayesivan  :)
