### ISSUE TITLE
Images not displayed in chat when received by user with app running in the background

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15836]
### Preconditions:
User_A and User_B are on the opened chat

### Steps to reproduce:
1. Device of User_A goes to the background
2. User_B sends a few messages with images
3. User_A goes back from the background

### Actual result:
Images are not shown in the chat for user_A until the chat is reopened

https://user-images.githubusercontent.com/52490791/236846176-2b128f12-454e-4568-adba-a9797a9a3d3a.mp4

### Expected result:
Images are shown in the chat for User_A

### Devices:
- iPhone 11 Pro max, ios 16
- Huawei p20 light, android 9

### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/11421801/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/11421802/geth.log)

### Env:
Nightly 8 May 2023

**Comment by flexsurfer** [comment]
after app is back from the background the port is changed , but in the new messages there are still old, so we need to reload messages after background

**Comment by flexsurfer** [comment]
or probably better to do not include server with port in the url

**Comment by flexsurfer** [comment]
@cammellos wdyt ?

**Comment by cammellos** [comment]
@flexsurfer images should subscribe to the port, it's a bit annoying, in theory only if the failed they should refresh, not sure how to accommodate that to be honest

**Comment by flexsurfer** [comment]
it's a more general issue, its not only about images in chat, any signal with url in the background will have outdated port, same for audio messages, albums etc
