### ISSUE TITLE
The display name/nickname/ens which includes dash is not resolved in the chat when mentioned

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15839]
#### Precondition:
- User_A  includes 'dash' within the display name (example: 'dash-user')

#### Steps to reproduce:
1. User_B: opens chat with User_A
2. User_B: mention the User_A
3. Check the result in the chat

#### Actual  result:
The user with dash is not resolved
![image](https://user-images.githubusercontent.com/52490791/236868519-f2e08233-3952-4562-8c53-fef5913d0b25.png)

#### Expected  result:
Mentioned user is resolved

#### Additional info:
The same behavior if ens or nickname include at least one dash

#### ENV:
Nightly [8 May 2023]

**Comment by ibrkhalil** [comment]
Can you please check if the notification gets sent to the mentioned user?

**Comment by VolodLytvynenko** [comment]
> Can you please check if the notification gets sent to the mentioned user?

Hi @ibrkhalil . Just checked. Mentioned user with dashes does not see push notifications

**Comment by flexsurfer** [comment]
cc @qfrank

**Comment by qfrank** [comment]
let me check
