### ISSUE TITLE
Onboarding flow - generate 3 words to secure signing transactions

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1585]
In order to reduce phishing threat for Status.im users we want to have them recognize 3 predefined words when they sign transactions or make other sensitive operations.  

Onboarding flow needs to generate the 3 words for the user and store it in the profile. 

### User Story

As a user, I want to accept 3 generated words when creating my account so that I can recognize these words when signing transactions and thus make it hard to create a phishing page and protect myself from phishing attack.

### Description

*Type*: Feature

TBD

![image.png](https://images.zenhubusercontent.com/5975f08f61b4ca3b0a757622/f45e86f2-caa8-4d01-a729-d562bbc7b9bf)

**Comment by sla-shi** [comment]
@andmironov this issue needs design updates.

**Comment by sla-shi** [comment]
Nevermind @andmironov at the moment we just need to implement capture these 3 words after the password creation during onboarding.

**Comment by rasom** [comment]
https://gist.github.com/jarradh/08013a322f1b7b51368c786c68b269c1

**Comment by rasom** [comment]
https://gist.github.com/jarradh/41f2cea7a4d409b5239a8e816c94d21c Russian version, needs some filtering (weird words, 3 letters words with accented letters)

**Comment by annadanchenko** [comment]
how user can check (remind) the signing phrase after onboarding

**Comment by goranjovic** [comment]
If we show the 3 words to the user during the onboarding, then what do we do about the existing user accounts who don't get to see the initial sign up screen any more? 

And if we generate it in a migration, re Anna's question, how do they get it?

**Comment by goranjovic** [comment]
Are we going to have word lists for other languages as well? I'm assuming this should work the same way label i18n does - use device language if available, otherwise English. Is that correct?

**Comment by goranjovic** [comment]
Right now onboarding gives two different passphrases - one for recovery and this one. Does it seem too much to shove all that info to the user the moment they create their account?

**Comment by goranjovic** [comment]
Not directly related to this issue, what should a user do if his signing phrase gets compromised? Should he be able to change it (generate again), or is his only recourse to create a different account and move all the eth there?

**Comment by sla-shi** [comment]
We can decide it later - can we create this piece of functionality and extend it in the coming iterations?

**Comment by goranjovic** [comment]
@sla-shi  Absolutely, I submitted a PR with the core item - the onboarding phrase creation, since that's the part that's on the critical path. I posted the questions to bring them to everyone's attention sooner rather than later.

https://github.com/status-im/status-react/pull/1669

**Comment by annadanchenko** [comment]
Tested on iOS and Android. As expected: after account creation there is extra message shown "Here is your signing phrase. You will use it to verify your transactions" than message with 3 English words is shown.

**Comment by jeluard** [comment]
Fixed in develop
