### ISSUE TITLE
No redirect on tapping on PN until the first re-login

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15859]
# Bug Report

## Problem 
After merging https://github.com/status-im/status-mobile/pull/15818 redirect to chat on tapping PN is broken until re-login.
It affects several e2e.

#### Expected behavior
Will be redirected to 1-1 chat

#### Actual behavior
user is redirected to 1-1 chat 

### Reproduction
**Prerequisites:** users are contacts, UserA has PNs enabled during onboarding and they didn't log out after account creation
1) UserA: open any tab except messages, put the app in the background
2) UserB: send text message to UserA
3) UserA: open notification center, tap on PN

### Additional Information

- Status version: nightly 10/05/23
- Operating System: Android

https://github.com/status-im/status-mobile/assets/4557972/592079f2-0510-44ad-8369-bed6805e10c0

Video: https://app.eu-central-1.saucelabs.com/tests/db0001b72d194fc386c1624791cc74f8?auth=7ae696a96fcc1dafa9526da0237c6ca2#209

Logs:  [logcat (11).log](https://github.com/status-im/status-mobile/files/11440590/logcat.11.log)

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
Okay reproduction is successful on my actual android device, the use case being that I have not logged out of Device A ( the device receiving Push notification).
Investigating further.

**Comment by siddarthkay** [comment]
So the deep link/ universal link redirect only works after I logged out the user and logged back in.

Below are the relevant logs: 

```log
INFO  INFO [status-im.router.core:213] - [router] uri  status-im://p/0x0458387caabbdc56979ce2faf6f71e5249ae
300f845aadfe1e14330a59b9f57b93e0cf64ca2f27bfe9db6d71c19f4df5ba88d7faba377a8a464886a055
d42289d1  matched  :private-chat  with  
{:chat-id "0x0458387caabbdc56979ce2faf6f71e5249ae300f845aadfe1e14330a59b9f57b93e0cf64ca2f27bfe
9db6d71c19f4df5ba88d7faba377a8a464886a055d42289d1"}
 INFO  INFO [status-im.utils.universal-links.core:66] - universal-links: handling private chat
 0x0458387caabbdc56979ce2faf6f71e5249ae300f845aadfe1e14330a59b9f57b93e0cf64ca2f27bfe9db6
 d71c19f4df5ba88d7faba377a8a464886a055d42289d1
```

**Comment by siddarthkay** [comment]
So this code here seems to be the culprit : 

```clojure
(rf/defn handle-url
  "Store url in the database if the user is not logged in, to be processed
  on login, otherwise just handle it"
  {:events [:universal-links/handle-url]}
  [{:keys [db] :as cofx} url]
  (if (and (multiaccounts.model/logged-in? db) (= (:app-state db) "active"))
    (route-url cofx url)
    (store-url-for-later cofx url)))
```

On first login, either of the conditions are not true and they're fixed after a logout followed by a login.
working on a fix...

**Comment by siddarthkay** [comment]
I logged the value of app-state and its in `background` which is clearly the issue and the reason why the universal link was not triggered on tapping of the push notification.

```clojure
(:app-state db)
```

```log
the value of appstate in db => background
```
