### ISSUE TITLE
[Android] White borders of the 'How to scan' bottom sheet on the light device theme

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15866]
# Bug Report
Follow-up of https://github.com/status-im/status-mobile/pull/15710

## Problem 

**Steps:**

1. Turn on the light mode on your Android device
2. Open Profile > Syncing > Press `+` > Press `How to scan`

**Expected result:**
- no white borders 
- correct color of the line in the center 

**Actual result:**

![photo_2023-05-10_15-21-56](https://github.com/status-im/status-mobile/assets/67952253/c822573f-9af4-40b8-a1ac-22c4eeeab145)

### Additional Information

- Status version: version with merged https://github.com/status-im/status-mobile/pull/15710
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
@qoqobolo - Kindly confirm if this bug is still reproducible.

I guess it's fixed on this PR https://github.com/status-im/status-mobile/pull/16033#issuecomment-1564584638

**Comment by qoqobolo** [comment]
@smohamedjavid confirm that the issue is fixed, thank you!
