### ISSUE TITLE
Sync code does not expire after 2 minutes and can be successfully used for syncing

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15861]
**Steps:** 

1. Generate Sync code on Device 1
2. Make screenshot of QR code because it will be unavailable after timer is up. 
3. Wait until 2 minutes for expiration of timer 
4. Scan Sync QR by Device 2
5. See if error about sync code expiration will appear for Device 2

**Actual result:** error does not appear. Sync code does not expire and can be used after expiration period is up. 

**Expected result:** sync code should expire in 2 minutes after being generated. Using expired code should result in error "This sync code has expired". [Figma](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179730&t=vHafgfaYP1zPGpUV-0)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
@pavloburykh Are you facing this issue in this PR: https://github.com/status-im/status-mobile/pull/15852?

**Comment by pavloburykh** [comment]
> @pavloburykh Are you facing this issue in this PR: #15852?

@ajayesivan yes! I have faced this issue while testing this PR. Now I see that this is most likely a PR issue, as I haven't reproduced it in nightly. Will log it in [PR](https://github.com/status-im/status-mobile/pull/15852).
