### ISSUE TITLE
Android debug mode becomes slow after running for some time

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15872]
I have noticed that after running debug mode on Android for some time, the app starts becoming slower, animations slower, some navigation animations not executing, app takes longer to refresh. When I restart the app it is back to normal, but then after a while it becomes slower again.

**Comment by ilmotta** [comment]
Thanks for reporting this. I've had this problem since day 1 that I started to play with `status-mobile`. This looks like a classical issue of resource leaking, although I have not investigated where and what is leaking.

**Comment by OmarBasem** [comment]
One thing I noticed is that keyboard listeners from `hooks/use-keyboard` are not cleared. Our hooks library is outdated. That could be one of the things slowing it down after a while when many listeners are running the background.
