### ISSUE TITLE
Create transition component for onboarding designs

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15877]
As per design feedback in Onboarding flow, `This transition shouldn't be between whole screens, only should move the content`

<img width="750" src="https://github.com/status-im/status-mobile/assets/18485527/0b922293-f625-4743-b38b-53a24b84568e">

For I'm new to status flow, background should be static, and only content should be moved. Also background should be blurred / unblurred while transitioning to the I'm new to status flow.

**Comment by J-Son89** [comment]
There is also Syncing transition, but perhaps this needs to be handled separately -> https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1938:148917#429271502

**Comment by J-Son89** [comment]
It seems like https://wix.github.io/react-native-navigation/docs/style-animations might suit our use case ->
If not we may have to build a custom component or consider moving to another navigation library ( a lot of effort involved) to make this work. I will initially investigate using our current navigation package.

**Comment by J-Son89** [comment]
@briansztamfater discovered a nice and workable solution that works well with our current navigation package 🚀

**Comment by briansztamfater** [comment]
Not sure about the scope of this issue, maybe we could close this as #16167 #16419 are already merged, what do you think @J-Son89 @ulisesmac?

**Comment by J-Son89** [comment]
Do we have the transitions for onboarding in place? I haven't seen it yet? 🤔

**Comment by J-Son89** [comment]
Like create profile -> create password transition

**Comment by briansztamfater** [comment]
I am currently working on transitions for new to status flow in onboarding here #16554, I'll reference this issue in that PR. My doubt was mostly about the scope as this issue seemed a bit generic, but I think I'll adapt the description if you agree with that so it covers design review about transitions in the onboarding flow (`This transition shouldn't be between whole screens, only should move the content`)

**Comment by J-Son89** [comment]
Yep that's perfect, you can do whatever is best for you :) all good with me either way. Nice one for sorting it! 💪🏼

**Comment by ulisesmac** [comment]
> Not sure about the scope of this issue, maybe we could close this as #16167 #16419 are already merged, what do you think @J-Son89 @ulisesmac?

Sounds good :+1:  @briansztamfater !
