### ISSUE TITLE
Incorrect opacity level of buttons in composer (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15884]
Followup of https://github.com/status-im/status-mobile/pull/15818 **cc** @OmarBasem 

Reproduced on Samsung Galaxy A52, Android 12

**Steps:** 

1. Enter any chat
2. Start sending messages one by one quickly
3. Longpress record audio button
4. See if buttons have correct opacity level

**Actual result:** opacity level is incorrect

![photo_2023-05-12 14 42 06](https://github.com/status-im/status-mobile/assets/97245802/db376a9a-be3e-4818-98c3-052c3c9db54b)
![photo_2023-05-12 14 42 08](https://github.com/status-im/status-mobile/assets/97245802/8d0758ee-2506-4d0d-bf94-5eb8b83ab96f)

https://github.com/status-im/status-mobile/assets/97245802/7e01dcec-6e8b-4051-8d11-a7e9e8a2a72e

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by VladimrLitvinenko** [comment]
@OmarBasem thank you for PR. No issues from my side. Ready to be merged
