### ISSUE TITLE
Account entity is replaced instead of creating new one when restoring account within secure phrase [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1588]
### Description

*Type*: Bug

*Summary*: 

#### Expected behavior
When restoring account using secure phrase I expect: new account record is created in Status. Public key remains the same. No passphrase generated in console

#### Actual behavior
New account record is not created. Passphrase exists in Console for restored account 

### Reproduction

- Open Status
- Sync app
- Copy pass phrase
- Click switch accounts
- Click restore account
- Paste the pass phrase
- Enter password

Notice that no new record for restored account is created. Previous account record is replaced instead.

### Additional Information

* Status version:  0.9.8-123-g0ada614d (1552)

* Operating System: Android 6.0.1

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/6302844/sessions/6/?accessToken=Y1EI-yDQUPaEfqQ3jkaqSiG0/R0

**Comment by annadanchenko** [comment]
It's expected: If account already exists on the device then you'll get the same one (with all info) after using Recover access with account's passphrase/password.
