### ISSUE TITLE
Android bottom sheet navigation bar bg color

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15886]
On Android, after closing the bottom sheet the part behind the bottom handle stays white.

![Screenshot_20230512_170000_Status PR](https://github.com/status-im/status-mobile/assets/29354102/d1a152b4-c8a7-41d3-95a8-ca5737328b59)

**Comment by OmarBasem** [comment]
Update: this also happens with navigation bar

**Comment by J-Son89** [comment]
closing as it's a duplicate
