### ISSUE TITLE
Limit the maximum number of unfurleable URLs

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15908]
# Problem

Depends on https://github.com/status-im/status-mobile/pull/15891

Unfurled URLs need to be sent to clients from status-go, and they usually contain thumbnail and favicon data URIs. Although most users don't share huge lists of links, if a user pastes (or painfully) types a long list of URLs, this can cause the app to behave in unexpected ways.

How long is too long? We don't know yet, maybe 5, 10 link previews, 20?

At the protocol level we can theoretically indefinitely split messages in chunks, each with one or a handful of previews, therefore, the artificial limitation we want to impose on users is at the UX level, catering for a worst case scenario.

## Open question

How should we let users know they've reached the artificial limit?

**Comment by ibrkhalil** [comment]
Can we unfurl a specific amount and have an endpoint on status-go that'll unfurl anything extra on demand (Click to show preview), Or instead of breaking the message into chunks, Can we break up the previews into chunks?

**Comment by ilmotta** [comment]
> Can we unfurl a specific amount and have an endpoint on status-go that'll unfurl anything extra on demand (Click to show preview), Or instead of breaking the message into chunks, Can we break up the previews into chunks?

@ibrkhalil, I'm not sure I fully understood the idea. Thanks for sharing!

There's a fundamental requirement for us to take in consideration: only the sender will unfurl due to privacy concerns. So the UX has to be very *synchronous*, i.e. there can't be another moment where the user can request more URLs to unfurl, it's either when composing or never (or when editing). status-go has to unfurl all the bytes from all URLs and immediately provide them to the client, so the client can display them to the user, because the user has to be given a chance to decide to send with or without previews. After sending a message, status-go must respect that choice and store all the data in a `ChatMessage` protobuf (or in multiple in the future).

So allowing the user to unfurl on demand seems to me to violate this *synchronous* requirement.

I see this issue as composed of two parts:

1. How many URLs should we unfurl that won't impact the UX? Each preview will require, in general, 3 HTTP requests, many can fail or timeout (as far as I tested). Images will need to be compressed and resized. The data will be returned to clients as data URIs base64 encoded, so all of this can put too much pressure on the client and make the experience slow. That's why a hard limit should be imposed. We could say this issue is worried about an edge case.
2. There's the status-go part, the more complex one, and the one I'm not planning on solving to be honest. Depending on the total size of all previews, the message might be too big for the network. I've heard ~125 KiB is a healthy limit, so that's when splitting into multiple messages could be the ideal solution. I'm not going to work on this because John told me someone might be working on creating a general solution to deal with larger messages.

**Comment by ilmotta** [comment]
The limit is 5 in status-go, so I'm closing this issue as completed.
