### ISSUE TITLE
Can't type seed phrase on Android, autocompleted value is pasted automatically

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15916]
# Bug Report

## Problem
While typing 'hello' at seed phrase input getting "hhhellohello..." (automatically filled up with autocompletion or predictive text feature)

Not adding as a blocker, as it has to be fixed with new input field

#### Expected behavior
can see `hello`

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/94e5293b-a3eb-4264-b6fb-ce2db4386648

### Reproduction

1) Open Status
2) I'm new to status > Enter Seed phrase

### Additional Information

- Status version: nightly 
- Operating System: Android 10 (Xiaomi Mi Note9),11 (Huawei p40 lite), 12 (BV5200 Pro)

**Not reproducible on Samsung Galaxy A52, Android 12**

[comment]: # (Please, add logs/notes if necessary)

**Comment by ulisesmac** [comment]
This will be fixed in this PR: https://github.com/status-im/status-mobile/pull/15946

**Comment by ulisesmac** [comment]
Hi @qoqobolo 
is this issue solved?

**Comment by qoqobolo** [comment]
Yep, we can close it. Thanks @ulisesmac
