### ISSUE TITLE
Display favicons in link previews

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15910]
# Problem

Depends on https://github.com/status-im/status-mobile/pull/15891

We want users to be able to identify websites when looking at link previews as quickly as possible, and for that, we believe favicons can greatly help.

<img src="https://github.com/status-im/status-mobile/assets/46027/96ea00e9-b5ac-4cf5-bd77-56da7990e051" height="400" />

## Implementation

Right now `status-go` does not attempt to extract favicons when unfurling URLs, and the vast majority of the implementation related to this issue should be there.

Take in consideration that favicons can also greatly vary in size, and that some websites offer higher pixel density favicons. But we should be careful not to use larger favicons without compression. See issue https://github.com/status-im/status-mobile/issues/15909.

**Comment by igor-sirotin** [comment]
@benjthayer has plans to update the designs, according to what sizes favicons usually are. 
So probably would be nice to ping him when this is implemented and we have some favicon references 🙂

**Comment by ilmotta** [comment]
The feature has been implemented per screenshot, so I'm closing as completed.


<img src="https://github.com/user-attachments/assets/b6655947-5d84-4255-9aa6-0248cb1fd18c" width="350" />
