### ISSUE TITLE
UX Issue with copy button on share tab

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#15926]
# Bug Report 

Originally discovered by @pavloburykh in https://github.com/status-im/status-mobile/pull/15782

## Problem 
On share tab you have the ability to spam the copy button right next to emoji hash.
 
<img width="904" alt="Screenshot 2023-05-17 at 7 41 15 AM" src="https://github.com/status-im/status-mobile/assets/64726664/862c6227-9d69-44b1-af79-ccb818f4a720">

This produces an array of toast notifications which is probably not the best UX. 
There should either be a cool down period after the button is pressed or a some other way to prevent this multiple toasts appearing but also keeping in mind that the user is not prevented from copying the emoji hash whenever they want.

Maybe one way to prevent this is to check if the same value exists in clipboard we do not allow the user to press the button 🤔

cc @John-44 @pedro-et 

#### Actual behaviour

https://github.com/status-im/status-mobile/assets/97245802/0ce03844-bacd-4bac-ae75-3e10f226f609

- Operating System: Android, iOS

**Comment by siddarthkay** [comment]
So it seems we use `https://www.npmjs.com/package/@react-native-community/clipboard` for access to device's clipboard and we do have the capabilities to check what's in the clipboard.

I think i find it better to check first what exists in clipboard matches and if it matches what we're trying to copy we basically then don't allow the user to press the button ( since the value is already copied ).

I believe this will create a better UX.

**Comment by siddarthkay** [comment]
Hmm, this feels much better..

https://github.com/status-im/status-mobile/assets/64726664/a1bb7264-ca3a-4b61-8186-e434b80601e1

**Comment by siddarthkay** [comment]
> I think i find it better to check first what exists in clipboard matches and if it matches what we're trying to copy we basically then don't allow the user to press the button ( since the value is already copied ).

So a fundamental edge case with this approach is that the clipboard is also used by other apps and if we use the global clipboard as our source of truth then we can produce false positives which is not nice.

If we use the re-frame clipboard (i.e a clipboard we manage inside the app ) there is an edge case which also results in a false positive as pointed out by @ilmotta here : https://github.com/status-im/status-mobile/pull/15938#discussion_r1197714167

Another approach as discussed with design team is to replace existing toast with a new notification, I think that is a cleaner solution. I'll try taking a stab at that.

**Comment by siddarthkay** [comment]
Okay this is definitely much better, Thanks for the suggestion @pedro-et 


https://github.com/status-im/status-mobile/assets/64726664/cdb9390f-1e5e-4878-9073-cfb1be88e1fc

**Comment by ilmotta** [comment]
Thanks for writing down all the findings @siddarthkay.

It seems we can implement the desired behavior with `:toasts/upsert`. The toast expects an `:id`, and if a toast with the same ID exists, then it gets replaced. So for these copy buttons, which are highly susceptible to multiple presses in a row, we could generate their toasts with the same ID.
