### ISSUE TITLE
[RFC] Navigation library

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1592]
This documents aims at discussing the opportunity of using an existing solution 
such as https://reactnavigation.org/ for react navigation logic.

status: RFC

Current state:
- we are currently using our own navigation logic
- we don't have transitions
- we don't have documentation describing how things currently work
- all 3 tab views always "active" so all subscriptions (~240!) are recalculated each time app-db is changed
- no deep-linking

Wishlist:
- better animation on navigation, offers transitions out of the box
- animations should be fast/smooth
- may need some lazy/deferred loading of components to make navigation faster
- deep linking for notifications

Things to determine for each candidate:
- what are the advantages over the existing solution ?
- which changes are required to use it in status-react ?
- does the router hide its state internally ?
- does it uses native transitions or relies on implementation in JS ?
- opinion of the design team on the candidate

Potential candidates so far:
- https://reactnavigation.org/ (with re-frame example implementation here https://github.com/vikeri/re-navigate)
- https://wix.github.io/react-native-navigation/
- http://airbnb.io/native-navigation/

**Comment by chadyj** [comment]
In progress with https://github.com/status-im/status-react/issues/4866 and https://github.com/status-im/status-react/pull/5606
