### ISSUE TITLE
Turn on Instabug on iOS build

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1593]
### Description

*Type*: Bug

*Summary*: Instabug is not turned on for iOS app. If shake the phone then nothing happens, should be "How we can help you?" popup

### Additional Information
* Status version: develop 0.9.9d127
* Operating System: 
Real device iPhone 6s, iOS 10.3.3

**Comment by sla-shi** [comment]
I tested with v0.9.9d130 and the instabug is there. This issue can be closed.
