### ISSUE TITLE
 "localhost" as the name of the android device instead of the devices name

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#15944]
## Problem 
When paring an android device with another device ios real-device / ios-simulator, while then name of the ios device is rightly returned during the process, the name of the android device is returned as `localhost` instead of the real name of the device.  

![238624016-88ef847d-ac93-4131-a02f-11a2df868697](https://github.com/status-im/status-mobile/assets/28704507/e8138f40-506c-4b1c-b4b6-614a1ce4d303)

**Comment by pavloburykh** [comment]
Same issues are relevant for List of synced devices screen in account settings. So when fixing this bug please address them for both onboarding and sync settings screens. 

Reported here: 

https://github.com/status-im/status-mobile/pull/16132#issuecomment-1581122090

https://github.com/status-im/status-mobile/pull/16132#issuecomment-1581122182

**Comment by jo-mut** [comment]
@pavloburykh  thats okay

**Comment by rasom** [comment]
So this line returns "localhost" https://github.com/status-im/status-go/blob/develop/server/device.go#L29

and we are not alone https://github.com/tailscale/tailscale/issues/482#issuecomment-646808004
