### ISSUE TITLE
Composer grows beyond max height

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15949]
# Problem

Composer grows beyond the correct maximum height when the text is long and there are images or link previews at the bottom. Originally reported by @pavloburykh in this comment https://github.com/status-im/status-mobile/pull/15891#issuecomment-1552900157

[bug.webm](https://github.com/status-im/status-mobile/assets/46027/6be113d1-e753-438b-ba20-8798571bc2c4)

### Cause

It looks as if the initial max height is not being updated in *some* place, because as we can see from the video, minimizing and maximizing the composer still reuses the same, incorrect max height.

**Comment by OmarBasem** [comment]
@ilmotta I noticed that when the composer is maximized, adding or removing a preview link causes the composer to move up and down. This does not happen when adding and removing images, whose UI is very similar to link preview -- a horizontal list below the input.

**Comment by ilmotta** [comment]
@pavloburykh, FYI I'm changing the issue's title and description because I could reproduce the problem with just text and images, so it's not related to link previews only.

**Comment by pavloburykh** [comment]
> @pavloburykh, FYI I'm changing the issue's title and description because I could reproduce the problem with just text and images, so it's not related to link previews only.

Got it. Thank you @ilmotta for the update and investigation. Sorry for underexploration of the issue from my side.

**Comment by ilmotta** [comment]
> > @pavloburykh, FYI I'm changing the issue's title and description because I could reproduce the problem with just text and images, so it's not related to link previews only.
> 
> Got it. Thank you @ilmotta for the update and investigation. Sorry for underexploration of the issue from my side.

It was a great finding @pavloburykh. I'll try to fix nonetheless :)
