### ISSUE TITLE
The error is not shown when user scans the sync QR code when the devices are connected to the different networks

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15957]
### Preconditions:
User_A and User_B connected to different networks

### Steps to reproduce:
1. User_A generates a sync QR code
2. User_B Scans the sync QR code

### Actual result:
Nothing happens during QR code scanning. The user is not informed of what are goings on wrongly

### Expected result:
The appropriate error is shown 

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=8204-331719&mode=design&t=pnYSHrtV5Ki0q1FS-0

**Comment by Samyoul** [comment]
Ah, I haven't noticed this issue until now.

Just a bit of background, in mobile contexts you can only get the network data if the user allows the Location permission. Which could be problematic.

I have a partial solution to this problem but at the moment we can't rely on knowing what the network name / SSID is.

See https://github.com/status-im/status-mobile/issues/16548#issuecomment-1632708369 for some more details.

See [Local Pairing - Network Address / Peer Discovery#3884](https://github.com/status-im/status-go/issues/3884) - details of partial solution

**Comment by VolodLytvynenko** [comment]
> Ah, I haven't noticed this issue until now.
> 
> Just a bit of background, in mobile contexts you can only get the network data if the user allows the Location permission. Which could be problematic.
> 
> I have a partial solution to this problem but at the moment we can't rely on knowing what the network name / SSID is.
> 
> See [#16548 (comment)](https://github.com/status-im/status-mobile/issues/16548#issuecomment-1632708369) for some more details.
> 
> See [Local Pairing - Network Address / Peer Discovery#3884](https://github.com/status-im/status-go/issues/3884) - details of partial solution

Hi @Samyoul Thank you for working on these issues. I close this ticket
