### ISSUE TITLE
The Fastlane plugin for Diawi has disappeared

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#15951]
It appears the `fastlane-plugin-diawi` we use to upload artifacts to Diawi has ceased to exist:

>This gem previously existed, but has been removed by its owner. The RubyGems.org team has reserved this gem name for 94 more days. After that time is up, anyone will be able to claim this gem name using gem push.
>If you are the previous owner of this gem, you can change ownership of this gem using the gem owner command. You can also create new versions of this gem using gem push.

https://rubygems.org/gems/fastlane-plugin-diawi

And the original GitHub repository simply returns 404: https://github.com/pacification/fastlane-plugin-diawi

I have uncovered this while testing builds on our new Mac M2 host:
```
trying https://rubygems.org/gems/fastlane-plugin-diawi-2.1.0.gem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
exporting https://go.googlesource.com/mobile (rev 8578da9835fd365e78a6e63048c103b27a53a82c) into /nix/store/hpf6yd3bcbkzmnqss0w20d2145273xcq-gomobile
Initialized empty Git repository in /nix/store/hpf6yd3bcbkzmnqss0w20d2145273xcq-gomobile/.git/
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
error: cannot download fastlane-plugin-diawi-2.1.0.gem from any mirror
error: builder for '/nix/store/hm9kqp0dyisyw46m55ccz5xmcb6jrgv3-fastlane-plugin-diawi-2.1.0.gem.drv' failed with exit code 1;
```
Currently the builds work simply because we have a cached version of the Gem in our Nix cache. But that will cease to work at the ext upgrade of a package like Ruby, or other relevant input into the package.

**Comment by jakubgs** [comment]
One possibility is hosting a mirror of it ourselves, since we do have copies in our cache:
```
admin@cache-01.do-ams3.nix.ci:~ % find /nix/store -maxdepth 1 -iname '*fastlane-plugin-diawi*' | head -n5                
/nix/store/61xb0vqab2yx48rf655xpsi7l70bmxyk-ruby2.7.6-fastlane-plugin-diawi-2.1.0
/nix/store/4myhqmnh080487gw3ifjvwz9g1nk300y-ruby2.7.6-fastlane-plugin-diawi-2.1.0
/nix/store/2mplaxfp77d6z2x5ig0m6hiwrd5ywylw-ruby2.7.5-fastlane-plugin-diawi-2.1.0
/nix/store/6pg3y5q3d0kw5ggdxs313y0pm36vg3cg-ruby2.7.4-fastlane-plugin-diawi-2.1.0
/nix/store/qvhgdsq9i0krxl4ihhrscgrnp8iw3f76-ruby2.7.4-fastlane-plugin-diawi-2.1.0
```
It should be in theory doable by specifying a custom source for the gem:

* https://guides.rubygems.org/using-s3-source/
* https://guides.rubygems.org/command-reference/#gem-sources
* https://bundler.io/guides/gemfile.html

**Comment by jakubgs** [comment]
Also, I see some forks still exist:

* https://github.com/saimirgx/fastlane-plugin-diawi
* https://github.com/mhtranbn/fastlane-plugin-diawi

So this should be salvageable.

**Comment by jakubgs** [comment]
I've made an issue in the only remaining repo of @Pacification - owner of `fastlane-plugin-diawi` when it existed - to ask why:

* https://github.com/Pacification/PraktikaPM04/issues/1

Since I see no other way of contacting the guy.

**Comment by jakubgs** [comment]
It might be simpler to use another tool, or write something ourselves, rather than trying to revive this Gem.

Some possible alternatives:

* https://github.com/devindi/diawi-upload - Gradle plugin, which is awkward because we only upload iOS to Diawi.
* https://plugins.jenkins.io/diawi-upload/ - Apparently has [unresolved security issue](https://www.jenkins.io/security/advisory/2019-04-03/#SECURITY-947) of storing secrets in plaintext.
* https://www.npmjs.com/package/diawi-nodejs-uploader - Node.js module, which might be a good fit.

I'm leaning towards the Node.js one.

**Comment by jakubgs** [comment]
I tried finding the credentials for Diawi, but nobody knows where they are, or who might know. I've checked with Andrea, Mobile QA team, Finance team, and Jarrad. Nobody knows. And yet the API token in CI works, so the account must exist and most probably someone must be paying for it.

**Comment by jakubgs** [comment]
The free plan keeps apps only for 3 days:

![image](https://github.com/status-im/status-mobile/assets/2212681/ad9297ba-7bbf-4697-ae33-72516d96ce07)

I checked some PRs, and found an example from 3 days ago that already expired:

* https://github.com/status-im/status-mobile/pull/15852
* https://webapp.diawi.com/install/x2ccjb

![image](https://github.com/status-im/status-mobile/assets/2212681/f5e83fdb-8992-4eb2-8e7b-190677c388ad)

![image](https://github.com/status-im/status-mobile/assets/2212681/c7387560-171e-4f55-97b7-2ec3ec66c5c9)

This means the mysterious account is free, and there's no value in recovering it. I might as well make a new one.

**Comment by jakubgs** [comment]
I have created a new account and selected the lowest paid plan for 2,99 EUR. Credentials are in BitWarden.

**Comment by jakubgs** [comment]
I created a new Diawi account with a Starter paid plan but I'm still getting this:
```
18:41:45  Uploading: StatusIm-Mobile-230519-163442-213e3a-pr15959.ipa
18:41:47  { error: 4000000, message: 'Too many requests' }
```
https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-15959/

But on the dashboard I can see the IPA was uploaded correctly: https://webapp.diawi.com/install/fAZJb4

![image](https://github.com/status-im/status-mobile/assets/2212681/87262965-34d4-4fe2-b9ac-6029cad1eaa1)

So I'm thinking the issue is somewhere else.

**Comment by jakubgs** [comment]
I tried submitting a ticket about this issue:

>I'm trying to us this Node.js module to upload the app:
>https://www.npmjs.com/package/diawi-nodejs-uploader
>
>But when I use it in CI the upload fails with:
>```js
>{ error: 4000000, message: 'Too many requests' }
>```
>But when I check the dashboard I can see it's uploaded correctly.
>My best guess is that this error comes from upload status checks, and not from the upload itself, probably due to too frequent checks. Is that correct? They appear to be hardcoded at every 300 miliseconds:
>https://github.com/Natteke/diawi-nodejs-uploader/blob/b07d97c55f09e5a68a0ace88849587597d1f5dcc/src/core/upload/index.ts#L46
>
>If not can you explain to me why this happens?
>And maybe you have some suggestions for tools to use for uploading in CI?

But it fails with a `500` error:

![image](https://github.com/status-im/status-mobile/assets/2212681/2fe68968-9a91-49fa-bbbc-fc4a1c0d505d)

**Comment by giantslogik** [comment]
It is relatively simple to use a fork.
gem install specific_install
gem specific_install https://github.com/giantslogik/fastlane-plugin-diawi.git

**Comment by jakubgs** [comment]
Sure, but why would we want to depend on an unmaintained package?

**Comment by jakubgs** [comment]
Managed to get a response from `support@diawi.com` about the 500s from ticket creation:

![image](https://github.com/status-im/status-mobile/assets/2212681/828eb270-de07-4d4e-ac00-97a7c809374c)

I'll try submitting a ticket.

**Comment by jakubgs** [comment]
Here's the ticket: https://dashboard.diawi.com/support/XHZDN3D6S4KK/view

**Comment by jakubgs** [comment]
Indeed it looks like my guess was correct and the [`diawi-nodejs-uploader`](https://www.npmjs.com/package/diawi-nodejs-uploader) Node.js module checks the status too often:

>Hi,
>
>Thanks for contacting us!
>Your guess is correct, there is a limit on the number of requests for the status check of an upload (2 requests every second)... >and it seems that the library your are using is making requests to fast. Could you try using 600ms instead of 300ms?
>
>Best regards,
>Arthur

https://dashboard.diawi.com/support/XHZDN3D6S4KK/view

Which essentially means we either have to patch it, or make a PR and hope it gets accepted soon enough. Annoying.

**Comment by jakubgs** [comment]
I've created a fork with a fix that addresses the short sleep issue:

- https://github.com/Natteke/diawi-nodejs-uploader/commit/325aa9ba - parametrize sleep time and bump it to 600 milliseconds

We'll use the fork for now, but hopefully my PR gets merged and a new release is cut:

* https://github.com/Natteke/diawi-nodejs-uploader/pull/1

**Comment by jakubgs** [comment]
But there is a problem, because the module has no `preinstall` or `install` targets in `package.json` so it doesn't get built:
```
[nix-shell:~/work/status-mobile]$ grep diawi package.json 
    "diawi-nodejs-uploader": "git+https://github.com/status-im/diawi-nodejs-uploader.git#refs/heads/bump-status-check-sleep",

[nix-shell:~/work/status-mobile]$ ls -l node_modules/diawi-nodejs-uploader/
total 917
-rw-r--r-- 1 jakubgs jakubgs   2788 May 23 10:35 CHANGELOG.md
-rw-r--r-- 1 jakubgs jakubgs     67 May 23 10:35 commitlint.config.js
drwxr-xr-x 4 jakubgs jakubgs      4 May 23 11:12 node_modules
-rw-r--r-- 1 jakubgs jakubgs   2103 May 23 10:35 package.json
-rw-r--r-- 1 jakubgs jakubgs 433733 May 23 10:35 package-lock.json
-rw-r--r-- 1 jakubgs jakubgs   1325 May 23 10:35 readme.md
drwxr-xr-x 6 jakubgs jakubgs      7 May 23 11:12 src
-rw-r--r-- 1 jakubgs jakubgs    505 May 23 10:35 tsconfig.json
-rw-r--r-- 1 jakubgs jakubgs   1063 May 23 10:35 webpack.config.js
-rw-r--r-- 1 jakubgs jakubgs 327390 May 23 10:35 yarn.lock

[nix-shell:~/work/status-mobile]$ grep main node_modules/diawi-nodejs-uploader/package.json 
  "main": "dist/index.js",
```
And there's no `dist` folder where `package.json` expects the `index.js`. That's annoying.

**Comment by jakubgs** [comment]
Instead this library might be a better fit: https://github.com/deanWombourne/node-diawi

Especially since it already has a default polling time of 2 seconds:
```js
const POLL_INTERVAL = 2;
const DEBUG = false;

const sleep = (seconds) => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, (seconds * 1000));
  });
};
```
https://github.com/deanWombourne/node-diawi/blob/c3dbf613066cf7dde4406092da24d56e6f9c1475/diawi.js#LL10C1-L17C3

**Comment by jakubgs** [comment]
The issue with this one is that it takes the token as a positional argument:
```js
        ['upload <token> <file>', '$0'],
        'Uploads an ipa, apk or zip to Diawi',
        (yargs) => {
          yargs
              .positional('token', {
                describe: 'your API access token',
                type: 'string',
              })
```
https://github.com/deanWombourne/node-diawi/blob/c3dbf613066cf7dde4406092da24d56e6f9c1475/bin/main.js#L11-L18

Now that's dumb.

**Comment by jakubgs** [comment]
I tried using the [`diawi`](https://www.npmjs.com/package/diawi) module like this:
https://github.com/status-im/status-mobile/blob/89c3629b13a4e9ab9dcb4ee16fd2ebb9380cc8cc/scripts/diawi-upload.mjs#L21-L27
And it works:
https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-15959/33/
But the number of Node dependencies it pulls in is stupid:
```
 > g show --oneline --stat yarn.lock 
89c3629b13 (HEAD -> ci/nodejs-diawi-upload, origin/ci/nodejs-diawi-upload) ios: replace Diawi Fastlane plugin that disappered
 yarn.lock | 2713 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----
 1 file changed, 2643 insertions(+), 70 deletions(-)
```
So I'd rather not use it.

**Comment by jakubgs** [comment]
I'm tempted to just write something simple myself, because all those libraries are not that great.

Here are the API docs: https://dashboard.diawi.com/docs/apis/upload

**Comment by jakubgs** [comment]
I wrote a script from scratch becuase including hundreds of dependencies to do a few http requests is moronic:
https://github.com/status-im/status-mobile/blob/ci/nodejs-diawi-upload/scripts/diawi-upload.mjs

The only dependency it makes use of is `form-data`, which is already present in our `yarn.lock`, pulled in by `jsdom`:
https://github.com/status-im/status-mobile/blob/6e928677a9750f0f08b051ab36764164bda014b1/yarn.lock#L4929-L4932
