### ISSUE TITLE
Upgrade re-frame

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15963]
# Problem

The last commit of the re-frame library we use is from Mar 7, 2020, version `0.12`, more than 3 years ago. It's working _decently_, so why upgrade?

re-frame is very stable, but it introduced improvements in 2020 that we're dearly missing. Whatever is in double-quotes below is verbatim text extracted from re-frame's changelog.

- There are some fixes of course, and very few breaking changes!
- "Supports `:fx`, which allows for effects to be ordered." Mike Thompson explains in more detail the goals and importance of introducing `:fx` https://github.com/day8/re-frame/issues/639#issuecomment-680500053
  - "You can include the same kind of effect multiple times (eg `:dispatch`) which means there is no longer any need for special effects like `:dispatch-n`. Indeed, all *-n style effects are now redundant. This feature is a stepping stone towards making it easier to create an event handler which is a composition of other functions". See any similarities with our custom `utils.re-frame/defn` macro and `utils.re-frame/merge` function?
- "re-frame now guarantees that a :db effect, if present, will be actioned before any other sibling effects."
- Support global interceptors. Among other things, useful for logging, global error handlers and inspecting events with a REPL.
- "Add a new interceptor called unwrap. It decreases the amount of destructuring necessary in an event handler where the event is structured as a 2-vector of [event-id payload-map]." Great to be added as a global interceptor.
- Syntactic sugar for trivial reg-sub declarations (see https://github.com/day8/re-frame/pull/634)

## And then?

Once re-frame is upgraded, I would like to tackle the re-implementation of `rf/defn` and `rf/merge` to take advantage of `:fx`, and do it in a way that's as compatible as possible with our existing guidelines.

Notably, I think it would be possible to come up with a solution that's fully lintable by clj-kondo. Right now we need to code without almost any linter help in event handlers, and this is a cost we should not be paying since every little piece of the puzzle is in our hands. Last time I checked, changing clj-kondo to lint `rf/defn` as `defn` correctly found more than 200 warnings. Not to count the cost of refactoring tools that don't work with our current solution.

## Limitations?

Do we have any library blocking us from upgrading? cc @flexsurfer, @cammellos, @ulisesmac

**Comment by ulisesmac** [comment]
Thank you so much for this issue. I'll do some research to find any potential problem and will comment on this issue!

**Comment by ilmotta** [comment]
> Thank you so much for this issue. I'll do some research to find any potential problem and will comment on this issue!

Excellent @ulisesmac, thanks for that! I just tried to upgrade directly to `1.3.0` and by the magic of backwards compatibility the app works. I haven't tested any other dependency, like `re-frisk`.
