### ISSUE TITLE
App crashes after login with "Ethereum node started incorrectly" popup

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#15977]
## Bug Report

After login into the application, the `"Ethereum node started incorrectly"` popup is displayed. The App crashed/closed upon pressing the `OK` button

<img src="https://github.com/status-im/status-mobile/assets/19339952/9e67f95a-b767-43c4-a4ba-b6670bf9e85c" width="300" />

### Logs

[logs.zip](https://github.com/status-im/status-mobile/files/11523128/logs.zip)

### Expected behaviour

The app should not crash.

### Reproduction

1) Open Status
2) Try to log in with your existing account

### Additional Information

- Status Version: nightly [20/05]
- Operating System: iOS
- Network Type: WiFi
- Bug discovered time: 20 May 2023 - 19:41 UTC

**Comment by flexsurfer** [comment]
hey @smohamedjavid could you provide more details? is it happen for all profiles? or for a new one or for an existing one? did you change the network?

**Comment by ajayesivan** [comment]
I am getting this error on existing accounts, but creating a new account worked fine.

**Comment by souravbaranwal** [comment]
I am also getting the same error (with a new account as well).

**Comment by flexsurfer** [comment]
just wondering if fast refresh is disabled?

**Comment by Parveshdhull** [comment]
I was also getting same error. Only reproducible on old install, fresh install fixed it. (weird all 4 reporters are from India).

**Comment by Parveshdhull** [comment]
Now, tried changing network to Goreli (on new account), and while changing back to Mainnet, getting error
![image](https://github.com/status-im/status-mobile/assets/17097240/19b62646-421c-467d-86cd-b79f99b4d3b4)
![image](https://github.com/status-im/status-mobile/assets/17097240/edf7b0bc-e593-4d42-84d1-600bbd36e31b)

**Comment by Parveshdhull** [comment]
> just wondering if fast refresh is disabled?

Also happening on release builds

**Comment by smohamedjavid** [comment]
Hi @flexsurfer

> could you provide more details? is it happen for all profiles? or for a new one or for an existing one?

Yes, Is happened for all profiles.

> did you change the network?

No, I did not change any network. I just automatically showed up.

> just wondering if fast refresh is disabled?

It's a nightly build


<hr/>


Guys, The issue is not reproducible on the new nightly build [22/05].

**Comment by smohamedjavid** [comment]
> I was also getting same error. Only reproducible on old install, fresh install fixed it. (weird all 4 reporters are from India).

Strange. 🤔

**Comment by Parveshdhull** [comment]
> Specified network id doesn't correspond to network id by RPC url

RPC Network ID: 4689
Expected Network ID: 1

**Comment by Parveshdhull** [comment]
Is it possible, it is related to https://github.com/status-im/status-go/commit/6acb34bab7679ab47f17fb56d00ae9d4ea122399
`mainnetChainID        uint64 = 1`
cc: @cammellos

**Comment by flexsurfer** [comment]
```
  {:json-rpc/call
   [{:method "net_version"
     :on-success
     (fn [fetched-network-id]
       (when (not= network-id (str (int fetched-network-id)))
 ```
 
 ```
 network-id (str (get-in networks [current-network :config :NetworkId]))
```

**Comment by flexsurfer** [comment]
About IoTeX Network Mainnet(iotex.io)
Network Name: IoTeX Network Mainnet
WebSite:  https://iotex.io/
ChainID:   4689
NetworkID:   4689

whats that ?

**Comment by flexsurfer** [comment]
so for some reason `:json-rpc/call [{:method "net_version"` returns 4689 instead of 1

**Comment by jo-mut** [comment]
> I was also getting same error. Only reproducible on old install, fresh install fixed it. (weird all 4 reporters are from India).

@Parveshdhull for me fresh install does not seem to fix the issue. I still get the error

**Comment by jo-mut** [comment]
> I am getting this error on existing accounts, but creating a new account worked fine.

reproducible on all accounts

**Comment by flexsurfer** [comment]
@smohamedjavid @ajayesivan @souravbaranwal please run `make run-ios` or `make run-android`

**Comment by smohamedjavid** [comment]
@flexsurfer - I use `make run-ios` or `make run-android` commands everyday to run debug builds.

The issue was first discovered or faced on the nightly build [20/05] on a physical phone. Later then, I tried running the debug build locally in a simulator and faced the same issue. 

Somehow today [22/05] on nightly [22/05], I faced this error only once on both the physical device and the simulator. The issue is not reproducible all time. I will post if I face this issue again.

**Comment by ajayesivan** [comment]
In my case, I only faced this issue today with old accounts. 
- Creating a new account fixed the issue. 
- Uninstalling the build from the simulator & running `make run-ios` got rid of the issue completely and old accounts started working.
