### ISSUE TITLE
Composer jumpy while maximized

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15981]
# Bug

The user can see the composer max height jumping up and down when removing an image while maximized. The same effect is visible with link previews, therefore the problem is not specific about one type of *extra* content on the composer.

[composer-bug-height.webm](https://github.com/status-im/status-mobile/assets/46027/915095c6-8bb7-49cd-a0ff-960f4ee4d8a2)

[composer-bug-height2.webm](https://github.com/status-im/status-mobile/assets/46027/7a1a2916-0570-4b94-8474-3013bba87097)

### Solution

As far as I investigated, the problem is that the composer max height is **immediately/instantly** calculated based on the existence of collections (such as images) in the app db (see `calc-max-height`). Whereas the composer is gradually animated.

The correct solution should probably be to only update the composer max height **after animations** have finished for all extra content.

@OmarBasem, I'm copying you in this thread just for awareness. I can try to fix this issue this week, but it's not gonna be a priority for me, so if you want/can, feel free to pick this up.

**Comment by OmarBasem** [comment]
@ilmotta I think if we wait for animations to finish the composer height would go down while the images/links height is animating down, then it will go up again when max-height is updated. I think we need to be animating the composer's height up, and the other content's height down simultaneously (if removing content, and vice versa when adding content)
