### ISSUE TITLE
"Cannot set property 'G_1' of null" error is shown after tapping 'new chat' button

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15982]
### Steps:
1. Tap 'new chat' button

### Actual behavior
"Cannot set property 'G_1' of null" error is shown after tapping 'new chat' button

https://github.com/status-im/status-mobile/assets/52490791/b215d85f-ab7e-4d11-880e-622e12f6e6b4

### Expected behavior
Chats can be created

### Env:
IOS, Android

### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/11532966/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/11532967/geth.log)

**Comment by churik** [comment]
cc @flexsurfer - was introduced by https://github.com/status-im/status-mobile/pull/15980

**Comment by flexsurfer** [comment]
oh sorry, i wanted to move to QA but then decided that i didn't touch ane new code, i'll fix asap , sorry
