### ISSUE TITLE
[IOS] User is not redirected to profile screen when following a profile link until first re-login 

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15991]
**Steps:** 

1. Create/restore multiaccount 
2. Do not log out
3. Try to open profile link of another user
4. See if you'll be redirected to user's profile screen

**Actual result:** 
user is not redirected to profile screen. Redirection starts working after first logout. 

https://github.com/status-im/status-mobile/assets/97245802/4d59ed33-7663-44f7-bc83-446ce2335091

**Expected result:**
user is navigated to profile screen

**Device**:
- iPhone 11 Pro max, IOS 16

**ENV**
- Nightly: [23 May 2023]

**Comment by siddarthkay** [comment]
@VladimrLitvinenko : I'll take this one up, fix should be easy peasy ;)

**Comment by siddarthkay** [comment]
@flexsurfer : I've assigned this back to myself, I have some WIP in my local branch related to this issue.
Will file a PR and get it merged this week.
