### ISSUE TITLE
App is not bringing to foreground when tapping on PN

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15998]
# Bug Report

## Problem 
Reproduced with new **Google Pixel 7A** devices.

Nothing happens when tapping on PNs which should bring the app to the foreground, however the redirect to corresponding chat inside app is happening

#### Expected behavior
the app opens with a corresponding 1-1 chat

#### Actual behavior
https://github.com/status-im/status-mobile/assets/4557972/c1d57305-9f1a-4252-8f25-4b9510b819bf

### Reproduction

**Prerequisites:** user A and user B are contacts, user B has enabled PN

- User B: minimize the app
- User A: send a message to User B
- User B: try to tap on a message from notification center

### Additional Information

- Status version: nightly 23/05/2023
- Operating System: Android13, Google Pixel 7A

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment]
I enabled PNs on B but don't see them. is it a known problem?
