### ISSUE TITLE
Photo selector and bottom sheet screen issues

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16002]
cc @flexsurfer 

There are some issues with photo selector and bottom-sheet-screen since that PR: https://github.com/status-im/status-mobile/pull/15993

1. Photo selector scrolled state does not match the designs: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372393&t=2auDEJpU1f8tQVGS-0
2. Since the last updates to the bottom sheet screen, the opening animation is not as smooth as before, on iOS (videos below).
3. Opening photo selector on iOS throws an error (screen shot below). Reproducible steps: open photo-selector, close it, open it again.
4. Album selector does not close when pressing the top bar title, and throws a red screen error `undefined is not an object` (happens on iOS and Android)

Animation video before (the animation looks smooth and natural)
https://github.com/status-im/status-mobile/assets/29354102/0046efe5-16dc-4d4c-bfb6-e97be61bf8f7

Animation video after (the animation is not slow, but the way the screen moves and then suddenly stops looks odd)
https://github.com/status-im/status-mobile/assets/29354102/5e9714f1-04ac-47ad-af2c-8776268f9846

Error screen (point number 3)
![unnamed (2)](https://github.com/status-im/status-mobile/assets/29354102/9a899237-9851-49a6-85ee-2fc7004ccaea)

**Comment by flexsurfer** [comment]
interesting but for me videos look the opposite, the first one is laggy and the second one is smooth, its only a matter of animation settings, and for the current implementation we can tune the animation but we need params from design team

**Comment by flexsurfer** [comment]
> 1. Photo selector scrolled state does not match the designs:

oh i see, that's why padding in container doesnt' work, mhm ok, i'll think what we can do, but definitely we don't want to add it manually in each sheet screen

**Comment by flexsurfer** [comment]
> 3\. Opening photo selector on iOS throws an error (screen shot below). Reproducible steps: open photo-selector, close it, open it again.

unable to replicate

**Comment by flexsurfer** [comment]
> 4\. Album selector does not close when pressing the top bar title, and throws a red screen error `undefined is not an object` (happens on iOS and Android)

<img width="105" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/7cd0f752-9079-42a7-9513-5ff91411cc7d">
is this album selector? what should happen when we press it ?

**Comment by flexsurfer** [comment]
something is definitely wrong because of the wrong double usage of `:f>` we need to refactor that and fix it, but I need to understand how the album selector should work

**Comment by flexsurfer** [comment]
ok anyway I'm on it, will fix all issues

**Comment by OmarBasem** [comment]
> interesting but for me videos look the opposite

@flexsurfer You can try on iOS simulator to see the difference. Last commit before the change b1aec54e4ccb94e2c3272e9d8a63fa996c770540.

> unable to replicate

Happens in debug mode. For me it opens first time no problem, then second time this error happens. It doesn't happen everytime. Try a few times maybe.


> is this album selector? what should happen when we press it ?

When you press it on it should open album selector. When you press on it again while on album selector, it should go back to photo selector.
