### ISSUE TITLE
Fork web3 and BigNumber and use those across the board [cross-repo concern]

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1601]
Context:
- web3 relies on a forked version of bignumber that doesn't use regex lookahead, and from my understanding regex lookahead isn't support when evaluating JS in Otto
- There was a problem with the latest web3 "release" that required an additional build step for dist (adamb can elaborate on this)
- status-react currently adds a new version of bignumber to solve a regression bug in certain JS environments that causes basic numeric operations to hang completely
- This forked version that web3 relies on doesn't solve the abovementioned numeric bug AFAICT

Future steps and concerns:
1. We ideally want to use the same version of `web3.js` and `bignumber.js` across the board for simplicity
2. If the significant number bug can occur for smart contracts inside jail, we need to figure out how to deal with that - using another dependency like another version of bignumber is confusing for people who expect `fromWei` to just work
3. We need to decide on if and how we should fork web3 and/or bignumber in order to incorporate these fixes (no lookahead and numeric bug), as well as how involved we should be with upstream (roma started working on nolookahead in some capacity I think?)

**Conclusion from Slack chat with roman: we fork `web3` and `bignumber` that includes both relevant fixes.**

- `bignumber.js` up to date repo under org with numeric fix
- `web3` up to date repo under org with our `bignumber.js` dependency
- update dependencies across board (x2-x3)
- check envs: RN/webview/otto for regressions
- basic process doc for keeping up to date with upstream (previously we had web3 fork that became outdated)
- submit PR upstream

**Comment by oskarth** [comment]
Relevant:
https://github.com/status-im/status-react/pull/1555
https://github.com/MikeMcl/bignumber.js/issues/120
https://github.com/ethereum/web3.js/issues/877
https://github.com/ethereum/web3.js/blob/develop/package.json#L11
https://github.com/rasom/bignumber.js/commit/49f840c27d50a2f32c1085476b79f7429c94d20d

**Comment by adambabik** [comment]
Thanks @oskarth for collecting this! The conclusion section looks great. Just let's make sure that our fork of `web3.js` has up-to-date `dist` directory as `status-go` will use it directly. Also, let's make a branch or even better a tag so that it's easier to track whether both `status-go` and `status-react` use the same version.

**Comment by oskarth** [comment]
I believe this issue can be closed when https://github.com/status-im/status-react/pull/1584 is merged, but @rasom can confirm.
