### ISSUE TITLE
Plug in data from the community service

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#16015]
The designs should be mostly implemented, @jo-mut and @J-Son89 should know what is the current state:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7545-487474&t=KabYctcxuyfxfyKK-0

There's already an endpoint that returns the suggested communities in status-go, and can be already used I believe:
https://github.com/status-im/status-go/blob/ddfd0c5b140e3e5bc9dfa76fc445fa0e2bf0aa35/services/ext/api.go#L393

@osmaczko will know more details.

**Comment by J-Son89** [comment]
Yes on both pages there is/was mock versions of this data here so it really should be just connecting the data 👍

**Comment by VolodLytvynenko** [comment]
Hi, @cammellos. I have a question regarding the behavior of the 'featured' sections in the app.
 By default, I've observed that the 'Status' community always appears after creating a new account. This makes it impossible to test how the 'featured' sections should look when there are no communities at all.

I understand that in the release build, a new account will not have any communities. Therefore, I would like to inquire if it is possible to test the PR without any communities being returned, in order to test the behavior of the empty 'featured' section. Thank you

**Comment by cammellos** [comment]
@VladimrLitvinenko sure, I can push a version of status-go without it.

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko sure, I can push a version of status-go without it.

@cammellos Thank you. One more question:

Q2: While testing the PR, I noticed that only one community is consistently displayed in the 'featured' section. I'm trying to understand if this is the intended behavior. I have created at least 8 communities, yet only one of them is appearing in the 'featured' section. Could you please clarify what determines whether a community gets included in this section?

Q3: From my understanding, the 'featured' section is meant to display communities recommended for users to join. However, even after joining a community, it continues to be shown in the 'featured' section. Should all types of communities be displayed in this section, or only "those which with pending" and "opened" statuses?
CC: @osmaczko

**Comment by cammellos** [comment]
> Q2: While testing the PR, I noticed that only one community is consistently displayed in the 'featured' section. I'm trying to understand if this is the intended behavior. I have created at least 8 communities, yet only one of them is appearing in the 'featured' section. Could you please clarify what determines whether a community gets included in this section?

They should all be coming from the contract, @osmaczko should know which one should be included, with regards of communities that the user has already joined and whether they should be removed, @John-44 will know the answer

> I understand that in the release build, a new account will not have any communities. Therefore, I would like to inquire if it is possible to test the PR without any communities being returned, in order to test the behavior of the empty 'featured' section. Thank you

Actually, this is easier if implemented on the frontend, @erikseppanen could you please have a look?

**Comment by osmaczko** [comment]
Hi @VladimrLitvinenko, let me answer specific questions first, then elaborate more on the concept of communities portal.

> Q2: While testing the PR, I noticed that only one community is consistently displayed in the 'featured' section. I'm trying to understand if this is the intended behavior. I have created at least 8 communities, yet only one of them is appearing in the 'featured' section. Could you please clarify what determines whether a community gets included in this section?

As @cammellos said, the communities in the portal are taken from the contract. The contract we get the information from is there: https://goerli-optimism.etherscan.io/address/0x22EE86A14b49890957fE71990073C6C68E05F9C5. It is still a mocked contract as we haven't deployed the Community Directory Curation DApp yet but it doesn't matter from the mobile app perspective.

> Q3: From my understanding, the 'featured' section is meant to display communities recommended for users to join. However, even after joining a community, it continues to be shown in the 'featured' section. Should all types of communities be displayed in this section, or only "those which with pending" and "opened" statuses? CC: @osmaczko

The communities portal operates independently of the app/account state. The contents of the featured section are not influenced by whether a community has been joined or not.

For context: There exists a distinct DApp, called 'Community Directory Curation' which is responsible for managing the communities to be listed on the App's Community Portal. This DApp is self-contained and does not interact with Status clients. Essentially, users utilize their voting power, via SNT tokens, to vote for or against the inclusion of a particular community in the directory and the featured section. All pertinent data is housed within the contract, and this contract serves as the sole input to the app. To simplify, data sourced from the contract is structured as follows:

communities: A,B,C,D
featuredCommunities: A

Given that the contract has not undergone any recent changes, the list displayed on the communities portal should remain unchanged each time the app is accessed.

**Comment by erikseppanen** [comment]
> > Q2: While testing the PR, I noticed that only one community is consistently displayed in the 'featured' section. I'm trying to understand if this is the intended behavior. I have created at least 8 communities, yet only one of them is appearing in the 'featured' section. Could you please clarify what determines whether a community gets included in this section?
> 
> They should all be coming from the contract, @osmaczko should know which one should be included, with regards of communities that the user has already joined and whether they should be removed, @John-44 will know the answer
> 
> > I understand that in the release build, a new account will not have any communities. Therefore, I would like to inquire if it is possible to test the PR without any communities being returned, in order to test the behavior of the empty 'featured' section. Thank you
> 
> Actually, this is easier if implemented on the frontend, @erikseppanen could you please have a look?

For testing, I commented out the insertion of fetched communities into the app-db, so there won't be any fetched community data in the mobile app.

**Comment by VolodLytvynenko** [comment]
@osmaczko @cammellos thanks a lot for the detailed explanations!
