### ISSUE TITLE
Implement quo2 - Wallet - account card component

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#16028]
Implement the wallet accounts slider as per designs:

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-UI-for-Mobile?type=design&node-id=37-142126&t=VMPvPP4JUgrCdzAe-0

Please place the implementation in the quo2 preview.
Have a word/chat with our designers before starting to implement to clarify the interactions.

You should be able to swipe the list horizontally.

Please componentize the various parts into atomic components.

**Comment by flexsurfer** [comment]
Account card component https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=19513%3A197699&t=nqNiSZNGwoqQUsLz-1

**Comment by FFFra** [comment]
I am taking care of this =)
