### ISSUE TITLE
☂️ RN Upgrade related issues

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#16021]
note : This is an umbrella issue.
Here I'd like to keep a track of Issues and their resolutions which occurred as a side effect of Upgrading React Native.

### React Native Upgrade from 0.69.10 to 0.72.5
- [x] https://github.com/status-im/status-mobile/issues/18181
- [x] https://github.com/status-im/status-mobile/issues/18166
- [ ] https://github.com/status-im/status-mobile/issues/18245 - This might not be entirely related to the upgrade, but I'm keeping it in this context as the issue surfaced after the upgrade.

### React Native Upgrade from 0.67 to 0.69

- [x] `error: builder for '/nix/store/1psjkjxd5c6icyqh4mwzfr081239z8n5-aapt2-7.3.0-8691043.drv' failed with exit code 2` reported by @ajayesivan on Intel Mac
fixed by : https://github.com/status-im/status-mobile/pull/16016/files#diff-eca6de5392107f47946e33be9281eabad479400298c93d666c7990fb8ea553a4R54
- [x] All of the component tests fail  
fixed by : https://github.com/status-im/status-mobile/pull/16016/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R97
- [x] `error: Error: Unable to resolve module base-64 from /Users/siddarthkumar/code/status-mobile/node_modules/node-libs-react-native/globals.js: base-64 could not be found within the project or in these directories:
  node_modules/node-libs-react-native/node_modules` while running on Android Emulator and on Physical Device
  fixed by : https://github.com/status-im/status-mobile/pull/16016/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R28
- [x] [Android] release PR app insta crashes after upgrading react native from 0.67.5 to 0.69.10
tracked here : https://github.com/status-im/status-mobile/issues/16139
fixed by : https://github.com/status-im/status-mobile/issues/16139#issuecomment-1574638062
- [x] Android 10 Devices crash with `java.lang.RuntimeException: Could not invoke WebSocketModule.connect`
tracked here : https://github.com/status-im/status-mobile/issues/16182
- [x] Could not read property toGestureArray of null 
tracked here : https://github.com/status-im/status-mobile/issues/16250

**Comment by churik** [comment]
@siddarthkay 

is it still relevant?

**Comment by siddarthkay** [comment]
@churik : This was just made to keep track of all issues we face after various RN upgrade.
Safe to close.
