### ISSUE TITLE
Navigation returns wrong status bar height

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#16029]
### Summary

For safe-area [insets](https://github.com/status-im/status-mobile/blob/e14ed7a637059d40ae8c066c581a6a44f493d1ba/src/react_native/safe_area.cljs#LL27C1-L27C1), we use status-bar-height returned by navigation [constants](https://github.com/status-im/status-mobile/blob/e14ed7a637059d40ae8c066c581a6a44f493d1ba/src/react_native/navigation.cljs#L79).

But for emulator `Pixel_5_API_30` height returned by navigation is larger than the actual height (as shown in below images).
Height returned by navigation constants is `62.18`, while height returned by react-native status-bar is `49.09`.

<div align="center">
<img src="https://github.com/status-im/status-mobile/assets/17097240/5ac0e4da-faea-47b5-a4ed-e0de70273d0b" alt="Screenshot" height="150"/>
<img src="https://github.com/status-im/status-mobile/assets/17097240/b7279801-4f3c-4962-9f0f-5e644421e0f2" alt="Screenshot" height="150"/>
</div>

Actually there is another issue, which is causing top bar to overflow blur overlay. Height of blur overlay is not dynamic, it is currently hardcoded to 100, will fix that.

It might possible that this wrong status bar height returned by navigation is device specific (Pixel_5_API_30 emulator), in that case we probably can ignore it for now.
Just wanted to confirm if anyone seen this behavior in any other device. @status-im/mobile-qa ?

cc: @flexsurfer

**Comment by pavloburykh** [comment]
@Parveshdhull probably my case is not related to yours but sometimes I am facing app screens having wrong hight and overlaying status bar. It is fixed by app reopening. I haven't logged it cause it happens rarely and randomly on different screens. No clear steps at this moment. 

Device Samsung Galaxy A52, Android 12. 


https://github.com/status-im/status-mobile/assets/97245802/317f3932-ac63-4d38-b299-fcf1ef2f258e

**Comment by pavloburykh** [comment]
Regarding your case, I have not faced it yet.

**Comment by Parveshdhull** [comment]
> Regarding your case, I have not faced it yet.

Thank you for confirming

**Comment by flexsurfer** [comment]
@Parveshdhull @Parveshdhull ios or android or both ?

**Comment by Parveshdhull** [comment]
> @Parveshdhull @Parveshdhull ios or android or both ?

only android, and currently only able to reproduce in `Pixel_5_API_30` emulator, So might be localized issue
