### ISSUE TITLE
Passphrase filed should ignore spaces and empty lines in front/end of the phrase 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1602]
### Description

*Type*: Bug

*Summary*: Passphrase with a space in front or at the end is treated as not identical to the same passphrase without spaces in front or at the end. User might copy/paste phrase with a space and then another account will be created instead of the expected one. It would be better to truncate spaces and new lines before and after passphrase to avoid confusion.

#### Expected behavior
Spaces or empty line(s) in front or at the end of passphrase are removed 
#### Actual behavior
Spaces or empty line(s) in front or at the end of passphrase are not removed that leads to other account being created instead of recovering the expected ones

### Reproduction

- Open Status and sign in 
- Copy passphrase from the Console
- Sign out
- On Sign in screen tap on Recover access
- Type a space or tap on keyboard enter to add a new line
- paste passphrase
- type the correct password 
- Tap on button Recover access -> new account is created
- Repeat recover access for the same passpharse/password but type a space at the end -> another account is created. In fact, passphrase is the same only spaces/new lines make it different. 

### Additional Information
* Status version: develop 0.9.9d130 / 0.9.8-130-g6a56b600
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by Alonski** [comment]
Can I try tackling this guys?

**Comment by jeluard** [comment]
Fixed in develop
