### ISSUE TITLE
[IOS] Albums are not fetched after 'recent' button is tapped in the photo gallery; `undefined is not object` Error is shown after repeated tapping on 'recent'

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16031]
### Steps to reproduce:
1. Set a few albums on device 
2. Open any chat in the Status app
3. Open the gallery
4. Tap the 'recent' button (Now the albums should be shown on the bottom sheet)
5. Tap 'recent' button one more time

### Actual result:
- The albums are not fetched after `Step 4`, the bottom sheet is shown as empty
- Error is shown after `Step 5`

https://github.com/status-im/status-mobile/assets/52490791/6d0806b4-464d-4fc2-8aa1-12013781360a

### Expected result:
- List of albums is fetched 
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372320&t=SeygwipQlMQDyahm-0
- error is not shown

### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/11574064/Status.log)
https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

**Comment by flexsurfer** [comment]
@VladimrLitvinenko @qoqobolo should be fixed in latest develop

**Comment by qoqobolo** [comment]
Thanks @flexsurfer
