### ISSUE TITLE
[iOS] Messages are marked as read in 1-1 and group chats on the chat screen after first opening the chat and before relogin

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16034]
# Bug Report

## Problem 

The unread indicator instantly appears and disappears for new messages in 1-1 and group chats on iOS, while the user opens the chat once with a new message, and then gets back to the chat screen.
It works fine after relogin until opening the chat. 

https://github.com/status-im/status-mobile/assets/67952253/8902cae7-440b-443a-978a-5f8ba1c6ceec

### Reproduction

1. UserA: open the chat home screen
2. UserB: send a message to 1-1 chat with UserA
3. UserA: open the chat, tap the `back` button
4. UserB: send another message in the chat
5. UserA: keep an eye on the unread indicator 

### Logs
[geth.log](https://github.com/status-im/status-mobile/files/11574742/geth.log)

### Additional Information

- Status version: RC 1.23 `#5`
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Findings: 
Currently only able to reproduce when navigating back using swipe. While navigating back using swipe, `navigate-back-handler` never called and chat never closed.
