### ISSUE TITLE
"Failed to set 'journal_mode' pragma" when generating forgot password error on login screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16038]
**Steps:** 

1. Open login screen
2. Try to login using wrong password
3. Observe the error

**Actual result:** 

"Failed to set 'journal_mode' pragma"  error

![photo_2023-05-26 18 36 15](https://github.com/status-im/status-mobile/assets/97245802/5c2257bf-894a-4abd-b6d7-9bc0e78d522b)

**Expected result:** "Wrong password" error is displayed

![photo_2023-05-26 18 39 03](https://github.com/status-im/status-mobile/assets/97245802/0f1f3dc8-74f9-43b9-90b1-313ac946095c)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by briansztamfater** [comment]
@pavloburykh I couldn't reproduce it, maybe I am missing some pre-conditions? Tested on iOS simulator.

<img width="300" src="https://github.com/status-im/status-mobile/assets/18485527/5ab4af50-5d09-4220-a012-202af5503314">

**Comment by pavloburykh** [comment]
Hello @briansztamfater ! Weird. I am reproducing on latest develop. Testing on real devices Android 12/IOS 14.1. There no special preconditions. Just entering wron password during login.

**Comment by briansztamfater** [comment]
> Hello @briansztamfater ! Weird. I am reproducing on latest develop. Testing on real devices Android 12/IOS 14.1. There no special preconditions. Just entering wron password during login.

@pavloburykh Although I couldn't reproduce it, I pushed a PR with a potential fix. Lmk if it that works!

**Comment by flexsurfer** [comment]
seems like database is corrupted @pavloburykh is this a  fresh install, or update? probably conflict in the versions

**Comment by pavloburykh** [comment]
> seems like database is corrupted @pavloburykh is this a fresh install, or update? probably conflict in the versions

Fresh install, new account. Entering valid password does not result in any issues. Error happens only on entering wrong password.

**Comment by flexsurfer** [comment]
could you provide logs pls

**Comment by pavloburykh** [comment]
> could you provide logs pls

sure!
[Status-debug-logs (34).zip](https://github.com/status-im/status-mobile/files/11651451/Status-debug-logs.34.zip)

**Comment by flexsurfer** [comment]
this is the source of the error https://github.com/status-im/status-go/blob/c6192bd26c37dc290ff32cd4030f93ca3470adb5/sqlite/sqlite.go#L128

**Comment by flexsurfer** [comment]
there were changes 2w ago https://github.com/status-im/status-go/commit/5777bb429a196672f21db97e5f3251ed674c6280 cc @osmaczko

**Comment by flexsurfer** [comment]
PR https://github.com/status-im/status-go/pull/3507/files

**Comment by osmaczko** [comment]
How do you recognize if user provided wrong password? The error string has changed, we had the same issue on Desktop side, see:
- https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564316434
- https://github.com/status-im/status-desktop/issues/10830

**Comment by briansztamfater** [comment]
Thanks @osmaczko for providing context. @flexsurfer do you think we should implement the same solution as desktop? https://github.com/status-im/status-desktop/pull/10840/files

I think ideally we should implement a better approach for errors on status-go, but we can have this as a patch.
