### ISSUE TITLE
Images sent from desktop are cropped

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16048]
# Bug Report

## Problem 
Any images, sent from desktop are cropped and resized.

#### Expected behavior

can see the whole picture

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/81245728-a157-4ef2-a38c-d57c20e047a6

### Reproduction

1) Sent any imge from desktop and try to open it on mobile device

### Additional Information

- Status version: RC 10, 1.23
- Desktop version: 0.12.0 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
After spending some time investigating, I think the issue is on the `status-desktop` side, It doesn't send image width/height when sending a message, So this needs to be looked at by the `status-desktop` team so can you please create an issue on their side for further investigation?
