### ISSUE TITLE
Commands send, request, location are sent several times if quickly tap on send button

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1604]
### Description

*Type*: Bug

*Summary*: Same message for commands (send, request, location) is sent several times if quickly tap on the send button in 1-1 or group chats. This does not happen for text or emoji. Expected: consistent behaviour for everything that is sent - anything in the input field is sent once even if user taps on send button several times.

#### Expected behavior
message for commands send, request, location is sent once if quickly tap on the send button.
#### Actual behavior
message for commands send, request, location is sent several times if quickly tap on the send button.

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7MGZhbGNJWkNoMGc
- Open Status
- Open 1-1 chat
- Construct a request to the contact in the input field, e.g. /request 0.1 
- quickly tap on send button several times
- check that messages area for new request messages (expected only 1)
- Construct send command in the input field, e.g. /send 0.3333
- quickly tap on send button several times
- Tap on /location command
- On the suggestions shown, quickly tap several times on the address

### Additional Information
* Status version: develop 0.9.9d130 / 0.9.8-130-g6a56b600 and 0.9.12
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by annadanchenko** [comment]
@janherich seems like it's not completely fixed. Can send several request commands in chat if tap on send button several times.

version: 0.9.12 release
iOS and Android

**Comment by oskarth** [comment]
Cherry-picked to release too. Two commits from  https://github.com/status-im/status-react/pull/2663 and https://github.com/status-im/status-react/pull/2988
