### ISSUE TITLE
Adjust compressed ellipsis public key display

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#16047]
The ellipsis of compressed keys are not according to designs.

**Comment by siddarthkay** [comment]
Lets begin by listing down places where we see incorrect ellipsis of compressed keys.
- [ ] Chat Screen
- [ ] Profile Screen

**Comment by cammellos** [comment]
@siddarthkay there's only one function that I know that is shorteneing the key `get-shortned-key` in `utils.address`, that works fine for ethereum addresses, `0x...` but not for compressed keys, there's a different rule for shortening them, you can check with @John-44 

If you check all the places where it's used, you can check whether we pass a wallet address or a compressed key, and change the usage if a compressed key is used.

**Comment by siddarthkay** [comment]
I shortened compressed keys in share view to match designs like this : https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/share/view.cljs#L33-L44 perhaps I could move this to `utils.address`

**Comment by cammellos** [comment]
@siddarthkay sure, sounds like a better place
