### ISSUE TITLE
Popup `No protocol method IAssociative. - assoc defined for type cljs.core`

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1605]
### Description

*Type*: Bug

*Summary*: 
Issue happens sporadically and it seems that popup appears in the same second on different devices running the app, the actions performed in that moment do not matter. At least, it happened for 3 different devices in the same second. On some of the devices app was used and on another it was just running on foreground.
 
App is running on foreground for 10-15 minutes, no actions are done - Popup `No protocol method IAssociative. - assoc defined for type cljs.core/ Symbol`
![img_2218](https://user-images.githubusercontent.com/6584810/29265042-c7af099a-80df-11e7-99e6-ff00b4d6794d.jpg)

#### Expected behavior
No popups, app is running and can be used
#### Actual behavior
 Popup `No protocol method IAssociative. - assoc defined for type cljs.core/ Symbol`

### Reproduction

- Open Status
- Open Chats (with group, public, 1-1 chat and all types of messages inside)
- Leave app to run on foreground with screen turned on for 10-15 minutes

### Additional Information
* Status version: develop 0.9.9d130 / 0.9.8-130-g6a56b600
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by asemiankevich** [comment]
TF: https://app.testfairy.com/projects/4803590-status/builds/6348397/sessions/1/?accessToken=D17C9XpuCrtlDWnlNFEJO1tqPpU timestamp 1:06:26

**Comment by sla-shi** [comment]
@tiabc @rasom any thoughts how we can diagnose the issue?

**Comment by adambabik** [comment]
For me it happened in Console chat, but it wasn't preceded with any action.

**Comment by goranjovic** [comment]
Can confirm seeing this a few times. For me this happened when I left it alone for a couple of minutes.
