### ISSUE TITLE
Onboarding Intro Screen - Design review

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16061]
![Movie_Recording_2023-05-30_11-33-05](https://github.com/status-im/status-mobile/assets/22799766/52ad5e59-8530-46d4-96b7-5757083ee114)

Illustration is cut off at the top - the carousel text background should be transparent and the image should be visible.

border at the bottom needs to be fixed - should not have any border radius at bottom

carousel animation transitions needs review

**Comment by J-Son89** [comment]
There was other comments on this page but most of these have already been detected and addressed in open prs:

force break text on bottom card text

Sign in in Transition

**Comment by ulisesmac** [comment]
@J-Son89 @churik @qoqobolo  I tried to reproduce the issue of the cropped image but I couldn't.

I tried on iPhone 11 and iPhone 11 Pro, could you please share more details to reproduce it?
Probably this is already solved, so we can close it.

**Comment by qoqobolo** [comment]
The issue is not reproducible anymore, thanks @ulisesmac
