### ISSUE TITLE
Onboarding - Create Profile - design review notes

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16067]
- [ ] remove black and white color option for now
- [ ] name input pressed by default - only mandatory field on page
- [ ] ~~continue box border transparent unless overflowing content~~
- [ ] "Your Name" -> "Your name"
- [ ] Blue color outer highlight needs to adjusted, could be correct but double check outer colors.

![acacsa](https://github.com/status-im/status-mobile/assets/22799766/56f2329f-4e91-460e-a567-3c5433536819)

- [ ] Also minimum 5 characters should not be in red validation message but in sub text component as shown below in designs: will be green when a valid length

Designs:
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2241-250700&t=oWh4xT05N2oS44kh-4

- [ ] align colors by width (Android only, Google Pixel 7a)
![IMAGE 2023-06-20 09:26:48](https://github.com/status-im/status-mobile/assets/4557972/47dff4af-ec54-4bb9-86b9-10ef15b080b2)

**Comment by J-Son89** [comment]
removing "continue box border transparent unless overflowing content" as it should be a separate issue as it is large in scope 👍  and is tracked here: https://github.com/status-im/status-mobile/issues/16181

**Comment by J-Son89** [comment]
@churik in this pr I also properly aligned the set of colors as discussed in the last QA call

**Comment by churik** [comment]
thank you! 
true, confirmed on Pixel 7A
