### ISSUE TITLE
Bottom sheets - should adjust correctly to content

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16066]
In a few places in the application there are some issues with the bottom sheet.

In general the bottom sheet height should fit to its content. If there is more content than a whole screen the bottom sheet should be able to scroll.

In this example the bottom sheet should also be slightly higher, i.e we increase the max size of the bottom sheet.
![Movie_Recording_2023-05-30_11-50-48](https://github.com/status-im/status-mobile/assets/22799766/9d681efd-a7d8-4919-a063-8e01fbf36ba4)

Also check background color in dark mode. It might need blur

**Comment by alwx** [comment]
Very related to this: https://github.com/status-im/status-mobile/issues/14564
