### ISSUE TITLE
Onboarding - Sign In page - Implement Sync Code tab according to designs

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16062]
Implement as per designs

<img width="216" alt="Screenshot 2023-05-30 at 20 23 21" src="https://github.com/status-im/status-mobile/assets/22799766/e2265b07-9fa2-415c-8f75-2df476bdb1d1">

Designs: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=4121-312080&t=1jjwZg91dEYb7P1e-4

**Comment by siddarthkay** [comment]
@J-Son89 : I know this is `descoped` but this blocks @igor-sirotin from finishing Syncing on the desktop side. 
The UI is easy enough to implement hence I'm assigning this to myself.

**Comment by J-Son89** [comment]
@siddarthkay makes sense 👍 
Looking at the UI I think we have all of it in quo2 components, except for the variant of the input with the button (in this use case "paste-button". Can you check if we have that variant and if not can you please add that in a separate p.r first 🙏 ?

**Comment by siddarthkay** [comment]
> check if we have that variant and if not can you please add that in a separate p.r first

Sure! Thanks @J-Son89

**Comment by siddarthkay** [comment]
> variant of the input with the button

We have this in quo2 preview.

**Comment by churik** [comment]
@siddarthkay any news on this one? it blocks the big chunk of automation, therefore potential bugs

**Comment by siddarthkay** [comment]
Will raise PR tomorrow @churik
