### ISSUE TITLE
Communities Home Page - Implement Dark Mode

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16079]
The communities home page needs to implemented correctly for Dark mode.

See the designs and implement correctly.
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=5040-188662&t=dyTuecNWxkV9KhMs-4

**Comment by ilmotta** [comment]
Blocked because @J-Son89 is working on a general solution for fixing theme colors that can help solve this issue.

**Comment by J-Son89** [comment]
That pr is merged now 👍
