### ISSUE TITLE
Onboarding - Welcome to Web3 - Implement Page

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16076]
The page welcome to web3 needs to be implemented:

Current designs do not show this but this page has some advanced designs which allows the user to select the theme.

Consider breaking this story into two issues - 
- implement the basic structure with a simplified version of designs 
- implement the advanced theme selector component

Designs
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2379-293038&t=YWqXodGUAGD3g8B5-4

Please align with designs for the animations/illustrations etc

**Comment by J-Son89** [comment]
waiting for illustrations etc @pedro-et

**Comment by FFFra** [comment]
This task is closed as it has been refactored by the design team.
