### ISSUE TITLE
Messaging - Audio Message - disable for now

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16084]
Current implementation of the Audio message has some issues and we would rather ship this feature fully ready 

Disable for now with a prompt, e.g "Feature coming soon"

**Comment by qoqobolo** [comment]
@alwx when disabling audio, please also fix issues 2,3,4 from this ticket https://github.com/status-im/status-mobile/issues/16091 (they are all about the same) to prevent accidental pressing the audio button instead of the send button
