### ISSUE TITLE
Profile - Share Tab - Design Review

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16080]
Following discussion with design team the current implementation of Profile Share tab requires some adjustments.

@mariocnovoa will do this review in Figma. Align with him and adjust as required.

**Comment by mariocnovoa** [comment]
Feedback here
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=2839%3A190555&t=76wDo6mHqKJWbuRN-1

**Comment by J-Son89** [comment]
@siddarthkay

**Comment by siddarthkay** [comment]
related : https://github.com/status-im/status-go/pull/3510

**Comment by siddarthkay** [comment]
![Screenshot 2023-06-01 at 5 55 53 PM](https://github.com/status-im/status-mobile/assets/64726664/11491efc-c900-4220-a0fc-cbf24eadd535)

The figma has a few comments based on comparisons with light mode enabled in settings, here is how things look in dark mode.

@mariocnovoa

**Comment by J-Son89** [comment]
@siddarthkay I see you are developing with "iPhone 14 Pro" - can you also verify this with "iPhone 11 Pro" as this is the best for checking side by side with Figma. Should help avoid simple padding/margin mistakes using this 👍

**Comment by siddarthkay** [comment]
Thanks @J-Son89 will do.

@mariocnovoa also confirmed on figma that background overlay colour is independent of light/dark modes, I'm currently looking into it.
