### ISSUE TITLE
Messaging - In Chat - + reactions button is not correct

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16087]
This icon needs to be adjusted.
![Movie_Recording_2023-05-30_13-42-25](https://github.com/status-im/status-mobile/assets/22799766/0487d909-a0c6-44f4-83db-4860ff1b943c)

See designs:

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3395-362183&t=GEOti7l3Z5VTvbDA-4

**Comment by ibrkhalil** [comment]
Couldn't reproduce it on latest develop.

**Comment by VolodLytvynenko** [comment]
Hi. I think this was fixed here https://github.com/status-im/status-mobile/pull/15677
@J-Son89 still reproduced for you?

**Comment by J-Son89** [comment]
I will take a look, thanks @VladimrLitvinenko

**Comment by qoqobolo** [comment]
Confirming that the icon is correct now

**Comment by J-Son89** [comment]
thanks @ibrkhalil, @qoqobolo and @VladimrLitvinenko ! :)
