### ISSUE TITLE
Activity Center - Notifications - Design Review

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16081]
Accept + Decline swipe -> add icons (currently using placeholder)
also there should be no margin on left or right of swipe actions (edge to edge)
accept + decline swipe action colors should match button colors

![Movie_Recording_2023-05-30_13-11-02](https://github.com/status-im/status-mobile/assets/22799766/805875f6-e896-4b3c-bae1-b4ab1591f182)

`Figma > Shell for Mobile > Notification Center` https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=6105-546987&t=ZCmbCodo8GhbKuCu-0

**Comment by J-Son89** [comment]
Hi @codemaster115, please ignore the task "accept + decline swipe action colors should match button colors" as I have addressed this in another pr 👍

**Comment by codemaster115** [comment]
@J-Son89 Where should be no margin(edge to edge)? I can see margins in the design. Could you please confirm it? Thanks.

**Comment by J-Son89** [comment]
Apologies @codemaster115, the issue was not explained correctly. It is in the transition we should be able to see all of the card, yet it is cut. It's correct there should be a gap when it's fully visible

![image](https://github.com/status-im/status-mobile/assets/22799766/9f0dbeb1-267f-46f8-b836-b6687037d753)

**Comment by J-Son89** [comment]
this photo should make it clearer. Ping me on discord if you have any further doubts.
