### ISSUE TITLE
Mention is not resolved if username or nickname of one is a substring of another

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16099]
# Bug Report

## Problem 
In case you have `John` and `John Lenon` in the community, the mention of `John` will not be resolved

#### Expected behavior
can mention both users

#### Actual behavior

![IMAGE 2023-05-31 15:02:50](https://github.com/status-im/status-mobile/assets/4557972/98e567e7-ffb5-4b56-9132-6c55ff7fd5ff)

### Reproduction
**Prerequisites:** you're community member
1) Set nickname for user1: `John`
2) Set nickname for user1: `John M`
3) Try to mention John

### Additional Information

- Status version: nightly 31/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
@qfrank Any ideas?

**Comment by qfrank** [comment]
> @qfrank Any ideas?

I'll take a look
