### ISSUE TITLE
Message - Composer - Mentions not resolving in editor

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16097]
Currently the mentions show no clear UI to the user that the mention has been correctly resolved.

![Composer_for_Mobile_Figma_2023-05-30_16-41-12](https://github.com/status-im/status-mobile/assets/22799766/babf2a64-6127-4208-b465-4ac615bf7a36)

See the designs for how this should look:
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=5530-358489&t=1xpxUi8twtiGgxdm-0

**Comment by flexsurfer** [comment]
cc @qfrank

**Comment by qfrank** [comment]
Hello @vkjr ! are you going to modify the corresponding part on `status-go` also or just fix the part of UI ?

**Comment by vkjr** [comment]
@qfrank, not sure yet, currently figuring out the best way to implement this. Do you have something in mind regarding `status-go`?

**Comment by qfrank** [comment]
The status-go mention-related API will return an input-segments array, which should include which parts are text and which are mentions. For example, for the text message: ‘hello @john1 , how are you’, the input-segments should contain [[:text 'hello ‘] [:mention ‘@john1’] [:text ’ ,how are you’]]. So the front-end only needs to traverse the input-segments to render the interface. But I need to verify whether the relevant status-go code works as I expected. @vkjr

**Comment by vkjr** [comment]
@qfrank, yes, you talk more about messages that we already store in `status-go`, and when I touched that part of the code, splitting the text into sections worked well. This issue is about writing the new message and displaying it correctly while user still types and before message was sent, so most probably `status-go` won't be involved

**Comment by qfrank** [comment]
> splitting the text into sections worked well

okay, glad to know this! so you may reuse it as it will calculate suggestion( input-segments will get updated) while typing, there is also something like `AtIdxs` in `state` you could use, it's up to you

**Comment by qfrank** [comment]
Oh, i proberbly missunderstand you, are you familiar with [on-change-text](https://github.com/status-im/status-react/blob/2c053d993747fe660f50a372394ba6ea12aeed53/src/status_im/chat/models/mentions.cljs#L101) ? it involved with `status-go` , relate [PR](https://github.com/status-im/status-mobile/pull/15428)

**Comment by vkjr** [comment]
Oh, I misunderstood you too) I thought you are talking about already existing messages! No, wasn't aware of this `status-go` call, thank you for pointing to it, will dig deeper! :)

**Comment by qfrank** [comment]
I can help check if `InputSegments` works as expected so that you may reuse it , the implementation for mention is complex :) , i rewrote it , I will check it tomorrow

**Comment by vkjr** [comment]
Thank you!

**Comment by qfrank** [comment]
Hi @vkjr , I've made a simple test, in general, `input-segments` should work just like this example:
> For example, for the text message: ‘hello @John1 , how are you’, the input-segments should contain [[:text 'hello ‘] [:mention ‘@John1’] [:text ’ ,how are you’]]

**Comment by vkjr** [comment]
> Hi @vkjr , I've made a simple test, in general, `input-segments` should work just like this example:
> 

Thank you!

**Comment by churik** [comment]
Should be reimplemented taking into account https://github.com/status-im/status-mobile/pull/16330#issuecomment-1691405548

cc @vkjr

**Comment by ilmotta** [comment]
I'm closing this issue since I believe it's already resolved. Feel free to reopen if needed.

**Comment by churik** [comment]
no, it is not, but we descoped it, so ok to close it
