### ISSUE TITLE
Messaging - In Chat -  Implement Options Menu for 1-1 and communties

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16094]
Current version of the In Chat Messaging does not include any functionality for the options button.

Implement this as these options are available on other screens.

see red square box in image:
<img width="250px" src="https://github.com/status-im/status-mobile/assets/22799766/8829dfed-25f7-4d73-b846-8e6b32868b98" />

This should be implemented for the different variations, e,g 1-1, Group and Communities.
The individual actions can be implemented in follow up if this is too large or consider breaking this story into 3 separate tasks for each variation

Designs are here:

1-1: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=7365-512935&t=a5CFBvO6ImJoqxLC-4

Communities: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=6301-422452&t=sHzSqc7SUJQNVVgm-4 

For communities a lot of these options already exist in: 
https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/communities/actions/community_options/view.cljs

A similar approach could be taken or this functionality could be reused/extended

**Comment by J-Son89** [comment]
sorry @flexsurfer - I thought I accidentally assigned you, but I realise now that you did it 👍

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the PR. Please take a look at the following issues

### ISSUE 1 No matching clause exception on opening options menu in community channel

**Steps:**

1. Open community channel
2. Tap on Options button
3. Observe the result

**Actual result:** app crashes with "No matching clause" exception. UI freezes, app needs to be restarted. 


https://github.com/status-im/status-mobile/assets/97245802/2cad8da2-cbda-418d-b5a8-2b8f2986d955

[Status-debug-logs (32).zip](https://github.com/status-im/status-mobile/files/11626812/Status-debug-logs.32.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 Keyboard is not closed when Options bottom sheet is opened in chat

**Steps:** 

1. Open chat
2. Make input field active to open keyboard
3. Tap options button
4. See if keyborad is getting closed when options bottom sheet appears 

**Actual result:** keyboard is not closed. On Android bottom sheet appears above the keyboard, on IOS behind it. 

**Android:** 

https://github.com/status-im/status-mobile/assets/97245802/511d4971-7bcc-4b9f-a9de-3dc6e442768a

**IOS:**

https://github.com/status-im/status-mobile/assets/97245802/1f97f429-ab75-4897-8c88-7bdae7a61598

**Comment by pavloburykh** [comment]
### ISSUE 3 Deleting chat via Option menu does not result in closing currently opend chat

**Steps:** 

1. Open 1-1 chat
2. Open Options menu
3. Select Delete chat option
4. Observe the result after deletion

**Expected result:** user is redirected to Messages screen. Chat is deleted. 

**Actual result:** user remains on broken chat screen with "Add unknown to send message" info message. 


https://github.com/status-im/status-mobile/assets/97245802/7e2ee173-b7ac-4221-8842-2336e0bc8ae2

**Comment by pavloburykh** [comment]
@flexsurfer I am not sure that we need "Mark as read" option inside 1-1 chat, cause entering chat automatically makes messages read as I suppose? But this is a minor. We can merge as it is and fix separately in future. 

![photo_2023-06-02 18 01 15](https://github.com/status-im/status-mobile/assets/97245802/293b3b96-9561-4445-a075-fa02ed95ef2d)

**Comment by flexsurfer** [comment]
issue for communities channel https://github.com/status-im/status-mobile/issues/16178
