### ISSUE TITLE
Messaging - Edit Message - Composer not correct height

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16093]
When editing a message in the message composer, if there is a lot of content in the message to be edited than the composer should open to the correct height to adjust for the content of the message.

![IMG_389013B140DB-1](https://github.com/status-im/status-mobile/assets/22799766/e91f886d-5e8c-4bca-88f1-0b79dd736a98)

**Comment by ibrkhalil** [comment]
Couldn't reproduce it on Google pixel 7A, On latest develop

**Comment by vkjr** [comment]
Can't reproduce it on the iOS Simulator, the latest develop
