### ISSUE TITLE
Unread indicator from 3 digits is shown as 2 digits

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16102]
# Bug Report

## Problem 

<img width="221" alt="Monosnap 2023-05-31 15-48-17" src="https://github.com/status-im/status-mobile/assets/4557972/72feb7c5-f14e-46f8-ae73-bb6929eff133">

#### Expected behavior
100 as per [design](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2500-42373&t=f4wYb4t1GE3g28V1-4)

#### Actual behavior
10

### Reproduction

1) Receive 100+ messages at 1-1 chat to see the unread indicator

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
I'm closing this issue because in latest `develop`, commit 419e84db0848e5a9a800ceee0a153536604b9266 this issue is fixed as we can see from the screenshot:

<img src="https://github.com/status-im/status-mobile/assets/46027/1f9ff443-9de6-40d5-b62f-7c61b8dc839e" width="380" />
