### ISSUE TITLE
Messaging - In Chat - When editing a message, adding a mention causes a huge padding gap

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16109]
When editing a message and adding a mention to the new version of the message there is a big gap of padding created, this should not exist.

![Movie_Recording_2023-05-30_16-44-55](https://github.com/status-im/status-mobile/assets/22799766/8042917e-e3e2-472f-97cc-70fb8aee36b6)

**Comment by OmarBasem** [comment]
@J-Son89 I think this is how it looks in the designs: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=5273-576104&t=WVv0qtvTsqEX3bMw-0

**Comment by OmarBasem** [comment]
@J-Son89 I think can be closed?

**Comment by J-Son89** [comment]
@OmarBasem perhaps you can give a version for @qoqobolo to test and verify with or ping @pedro-et &/or @mariocnovoa and get their input. We created these issues together and I was just taking notes so I am not 💯  Although the screenshot shared also has some huge gap which I do not see in the designs 🤔

**Comment by qoqobolo** [comment]
@mariocnovoa has confirmed that the issue can be closed
