### ISSUE TITLE
Messaging - In Chat - View photo features

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16106]
~background color not correct~. - Edit (Omar): done

text is not correct, verify size/designs - Edit (Omar): @J-Son89 implementing the text drawer seems to be the only remaining part in the lightbox screen. Should I implement it now?

top buttons not working/implemented yet (perhaps a follow-up issue) - Edit (Omar): https://github.com/status-im/status-mobile/pull/16268, https://github.com/status-im/status-mobile/pull/16224, and https://github.com/status-im/status-mobile/issues/16403

There should be padding/margin on the side of photos - Edit (Omar): currently having padding on the side causes problems with Shared element transition animation on iOS. I will wait for it until we upgrade RNN and reanimated versions (dependent on RN 0.71+)

![Composer_for_Mobile_Figma_2023-05-30_17-17-01](https://github.com/status-im/status-mobile/assets/22799766/0b3bc8ff-6a3b-4e2a-acdf-ef0fb4746ffc)

Designs
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372677&t=uEhz2B0QJkxAitDo-4

**Comment by J-Son89** [comment]
use an alert for top buttons not implemented

**Comment by qoqobolo** [comment]
> text is not correct, verify size/designs

Please, ignore this issue for now, the description will be disabled in https://github.com/status-im/status-mobile/pull/16169

**Comment by OmarBasem** [comment]
Hey @ulisesmac I am already working on this issue :)

**Comment by ulisesmac** [comment]
> Hey @ulisesmac I am already working on this issue :)

Hey @OmarBasem, I have a partial a solution for some aspects, but the code is a little complex, I've seen you created most of these components, so I think it's going to be faster if you continue :+1: 

Please add me as reviewer when it's done :+1:
