### ISSUE TITLE
Messaging - In Chat - "Jump To" button should disappear when input is focused or in scrolled position

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16104]
"Jump To" button should disappear when typing.

This is how it should look as in the designs - 
![IMG_32DD96785060-1](https://github.com/status-im/status-mobile/assets/22799766/89bd6084-2267-4a6e-87c3-9002d4074dc5)

Designs:
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=3101-347945&t=Yspiy1M9ZTNBqu6s-4

**Comment by OmarBasem** [comment]
It seems it should also disappear when scrolling

**Comment by J-Son89** [comment]
Thanks @OmarBasem, feel free to adjust the description as you see best 👌
