### ISSUE TITLE
Community Overview - UI bugs - 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16119]
Tags are clipping on the sides, should overflow to the left of the page.

"Request to join" button needs margin on top

![Movie_Recording_2023-05-30_16-09-35](https://github.com/status-im/status-mobile/assets/22799766/25cb9822-7d49-48d4-b643-428e68254cd0)

Community Color should be coming from community object - as such it can be any color value as Desktop uses a color wheel (not just a small set of options)

nav bar buttons are not correct at the moment - Review these.

**Comment by J-Son89** [comment]
I guess you can add this to scroll view here? 🤔 
https://reactnative.dev/docs/scrollview#alwaysbouncevertical-ios

**Comment by ilmotta** [comment]
I'm closing this issue because I already created a handful of others extracted from this issue. More on the way.
