### ISSUE TITLE
Jump To - Banner images/colors for cards are not correct

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16112]
banner images for jump to cards should be adjusted - 
channel color, other persons color or community image

**Comment by codemaster115** [comment]
The 1-1 message card should have the other user's color.
For community card, it is the community banner image (these are mandatory for community admins to use)
For group chat, still needs to determine with designers.

**Comment by codemaster115** [comment]
For now, the mobile app doesn't have a feature to change group chat color.

**Comment by J-Son89** [comment]
Hmm, if chats are coloured by desktop do we have access to that color in mobile?

**Comment by codemaster115** [comment]
Yes, it's fixed in my branch. Gonna create the PR soon.

**Comment by J-Son89** [comment]
That's perfect so. Nice one @codemaster115!
