### ISSUE TITLE
Add blur effect on scroll for buttons inside gallery view

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16127]
Implement blur effect on scroll for buttons inside gallery view as per design below

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372379&t=LgBrTeQVDEFhr9J9-0

<img width="750" alt="Composer for Mobile – Figma 2023-06-01 11-51-31" src="https://github.com/status-im/status-mobile/assets/97245802/4cc516b6-ea78-479d-bcd9-99969717ea6b">

**Comment by alwx** [comment]
Unassigning it from myself because it's less important than the rest and because I do have a bunch of other tasks to do.

**Comment by briansztamfater** [comment]
@alwx I'll work on it, no problema 👍
