### ISSUE TITLE
Community 0verview - Scrolling animation and adjustments

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16122]
Review / revisit the animations for Community Overview page -

designs
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1506-101672&t=Tj6dedxK42Xfuh36-0

cc @xAlisher can we get a preview of the animations too 🙏

**Comment by OmarBasem** [comment]
@J-Son89 I think this animation is already implemented in quo2. We have a reusable component `animated-header-list` component which can be used for the communities screen (and profile screen when we get there).

Here is the video that Alisher previously shared with us:

https://github.com/status-im/status-mobile/assets/29354102/58d3671e-d7de-49dd-be6c-a3de58ae6d5d

**Comment by J-Son89** [comment]
Awesome, thanks @OmarBasem was not aware of that!

**Comment by ilmotta** [comment]
@codemaster115, I'm reviewing issues in the [Communities project](https://github.com/orgs/status-im/projects/81). Are you still working on this one?

**Comment by churik** [comment]
I think it can be closed in favor of a new roadmap for now, but there's no need to keep it open. 

Please reopen it if it is still relevant, for now the issue seems stale.
