### ISSUE TITLE
unable to generate wallet account

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#16125]
# Bug Report
Can't see the generated wallet account after re-login

#### Expected behavior
we can see the wallet account added by "Add an account"

#### Actual behavior
we can't see the wallet account added by "Add an account"

### Reproduction

1. create new status account
2. generate a wallet account via "Add an account" 
3. logout and login
4. switch tab to wallet

### Additional Information

- Status version: latest version on branch `develop`
- Operating System: iOS simulator

[relate changes might be](https://github.com/status-im/status-go/issues/3531)

cc @churik @rasom 

https://github.com/status-im/status-mobile/assets/12406719/993d7e86-766e-42f4-97c6-55395824f17d

**Comment by rasom** [comment]
Thanks, I'll take a look on Monday

**Comment by rasom** [comment]
@qfrank just tried it in `develop` and it works just fine on my side (iOS simulator)

**Comment by rasom** [comment]
@qfrank 

https://github.com/status-im/status-mobile/assets/2364994/82dfa187-a4cf-480c-b35c-9e342988e55a

**Comment by qfrank** [comment]
what if continue adding another wallet account via generating , so we should get 3 wallet account(1 default + 2 generated) ? @rasom

**Comment by rasom** [comment]
@qfrank this works fine for me as well

**Comment by rasom** [comment]
https://github.com/status-im/status-mobile/assets/2364994/d9c943cf-5b90-4791-a477-e01b853c888d

**Comment by qfrank** [comment]
okay, sorry, i may missed one important information, i may tried branch `release/1.22.x` first, then tried `develop` @rasom

**Comment by qfrank** [comment]
it appeared when i try to reproduce issue #16043

**Comment by rasom** [comment]
@qfrank maybe some inconsistent database state caused it or something. But if can't repro it in develop now then let's close it

**Comment by qfrank** [comment]
sure, feel free to close it, thank you!
