### ISSUE TITLE
Wrong $ value for $FLX token on status wallet

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#16129]
A user has reported on discord 

- he's using release 1.20.3
- he owns 3000 tokens of FLX, contract 0x3ea8ea4237344c9931214796d9417af1a1180770.
- status wallet shows a value of 47k$ when in reality it's worth around 100$
- contract was double checked, it's the right one. Correct price is showing on CMC, CG and Deban

**Comment by flexsurfer** [comment]
cryptocompare.com provider is used for prices, and the token symbol is used (not contract) for fetching prices, so probably it's a different token https://www.cryptocompare.com/coins/flx/overview

**Comment by flexsurfer** [comment]
https://etherscan.io/token/0x6243d8cea23066d098a15582d81a598b4e8391f4

yes contract address is different

**Comment by siddarthkay** [comment]
> * he owns 3000 tokens of FLX,

To clarify a bit further, 
Currently 3000 FLX is worth approx. 49K 
and as mentioned by @flexsurfer the contract address is different.

<img width="725" alt="Screenshot 2023-06-01 at 7 23 23 PM" src="https://github.com/status-im/status-mobile/assets/64726664/21877305-1e19-42e6-a2b4-2dc6653699c0">

**Comment by siddarthkay** [comment]
This means that status wallet indeed shows the correct value for $FLX token.

However the user that has reported this probably does not have the tokens they're claiming :)

**Comment by guylouis** [comment]
but https://etherscan.io/address/0x3ea8ea4237344c9931214796d9417af1a1180770 as the same ticker $FLX and this is the one contract the user has imported in status

doesn't this come down to: 
- when the user imports a new erc-20 token in status, are we checking (if even possible) that the ticker and smartcontract address actually match. This could avoid some user mistakes. 
- can we use the contract adress and not the ticker in the cryptocompare api?

**Comment by flexsurfer** [comment]
> * when the user imports a new erc-20 token in status, are we checking (if even possible) that the ticker and smartcontract address actually match. This could avoid some user mistakes.

yes, we're checking

> * can we use the contract adress and not the ticker in the cryptocompare api?

i guess no, only symbol supported by api

**Comment by flexsurfer** [comment]
> However the user that has reported this probably does not have the tokens they're claiming :)

he has, but different token, there are 4 FLX tokens

<img width="388" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/436bc2bf-a5c5-4018-b40a-1d13a31a2c1a">

cryptocompare supports only first one

**Comment by cammellos** [comment]
closing as this will be addressed in the new wallet
