### ISSUE TITLE
Login/Profile select page - Delete account tab color issue

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16121]
this drawer should have a color like a drawer here: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=3804-821538&t=9KwZsqJCzzZZEYAZ-4

![photo_2023-05-30_10-58-59](https://github.com/status-im/status-mobile/assets/22799766/6d902889-e310-4474-a745-6f8c863cc0f8)

Perhaps this is an overall issue with the drawer in dark mode, if so this could be a duplicate issue 🤔

**Comment by ulisesmac** [comment]
~The problem is the action drawer doesn't have implemented its `shell` variant:~

~https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1931-31188&t=vq53UTCAH2FFzwDe-4~

~I'll solve it~

**Comment by ulisesmac** [comment]
> ~The problem is the action drawer doesn't have implemented its `shell` variant:~
> 
> ~https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1931-31188&t=vq53UTCAH2FFzwDe-4~
> 
> ~I'll solve it~

I investigated about it and the problem is on Android we are not using the correct background color for shell drawers because they require the use of a blurred view, which is not working yet.

This issue is blocked until the blur on Android is fixed
