### ISSUE TITLE
Community Overview - Implement Version for users who have joined and have visited the page before

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16123]
Once a user has visited the community there is a similar but different UI for the community Overview page:
It can be seen here:
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-409196&t=U0omRlpGeYcmIF2M-4

Implement this page and add the functionality to only show this to users once they have joined a community and are visiting the page for the 2nd or more time.

**Comment by ilmotta** [comment]
@cammellos, this feature seems very optional to me and the kind of thing that can be delayed in the MVP, but most definitely in the `UI Fit & Finish` project. Wdyt?

Now on the technical side, do you know if status-go already has the implementation for the *number of times the user has visited a given community*?

**Comment by ilmotta** [comment]
I talked offline with @cammellos and @J-Son89 about the *visited* state and if we should store it in status-go. @cammellos gave the idea of using the community's `joined` state and making sure the banner doesn't collapse (shorter version) when the user presses the *join community* button. As they pointed out, we should use the joined state AND have a secondary local state.
