### ISSUE TITLE
The cursor is hidden beneath the input field when the line breaks (IOS) 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16133]
сс @OmarBasem 

Reproducible on IOS only

**Steps:** 

1. Open chat
2. Start breaking the line in the input field
3. Observe the result

**Actual result:** the cursor is hidden beneath the input field when the line breaks. It becomes fully visible after composer starts expanding. 

https://github.com/status-im/status-mobile/assets/97245802/1dfe66ce-b195-4839-b13d-5bfd6dc5643c

### Additional Information

- Status version: nightly 
- Operating System: iOS 14.1
- Device: iPhone X

**Comment by OmarBasem** [comment]
Hi @pavloburykh,
Can you please give more details? I did not see this issue before. Is there a particular flow that you went through to face this issue? Is it reproducible always?

**Comment by pavloburykh** [comment]
> Hi @pavloburykh, Can you please give more details? I did not see this issue before. Is there a particular flow that you went through to face this issue?

Hi @OmarBasem ! Actually there are no special preconditions or details except those I have provided in the description. Have you tried the steps above on iPhone device?

**Comment by OmarBasem** [comment]
Yes, I tried it on iPhone 13 Pro device. I will try on iPhone X simulator.

**Comment by OmarBasem** [comment]
Alright, so it is reproducible on iOS devices with a smaller screen

**Comment by OmarBasem** [comment]
For some reason, I can't reproduce it again 😕 

I was able to reproduce it one time on iPhone SE, then it is working fine..

**Comment by pavloburykh** [comment]
> For some reason, I can't reproduce it again 😕
> 
> I was able to reproduce it one time on iPhone SE, then it is working fine..

Thanx for the update. On my iPhone X I am reproducing easly and every time. @churik is also rerpoducing on her iPhone mini.

**Comment by OmarBasem** [comment]
@churik are you still able to reproduce that issue. I am not able to reproduce it on iPhone mini or any other simulator. Video below is iPhone mini

https://github.com/status-im/status-mobile/assets/29354102/ad2db6cf-e60a-4ab8-9ad7-94271ee7a0ec

**Comment by pavloburykh** [comment]
@OmarBasem hi! 
I am still reproducing the issue on latest nightly build (iPhone X, IOS 14.1)


https://github.com/status-im/status-mobile/assets/97245802/41911eb8-8021-47f6-b7cb-66108dc85e08

**Comment by OmarBasem** [comment]
@pavloburykh can you please check this build: https://i.diawi.com/CtyTxS

**Comment by OmarBasem** [comment]
> @pavloburykh can you please check this build: https://i.diawi.com/CtyTxS

Hey @pavloburykh, have you checked the above build please?

**Comment by pavloburykh** [comment]
> > @pavloburykh can you please check this build: https://i.diawi.com/CtyTxS
> 
> Hey @pavloburykh, have you checked the above build please?

Sorry @OmarBasem. I have missed message here. I have checked and issue is still reproducible


https://github.com/status-im/status-mobile/assets/97245802/7cfd02cf-9081-4e78-a0be-38e8ff6fd98c

**Comment by OmarBasem** [comment]
@pavloburykh can you try these 2 builds and let me know if any them works

build 1: https://i.diawi.com/z4FuMV

build 2: https://i.diawi.com/2TmkiC

**Comment by pavloburykh** [comment]
> @pavloburykh can you try these 2 builds and let me know if any them works
> 
> build 1: https://i.diawi.com/z4FuMV
> 
> build 2: https://i.diawi.com/2TmkiC

@OmarBasem still reproducing the issue on both if the builds. Let me ask someone with iOS 16 check these fixes. Maybe the problem is my IOS 14.1

**Comment by pavloburykh** [comment]
@OmarBasem looks like issue is reproducible only on my IOS 14.1 
@churik @VladimrLitvinenko are not reproducing on IOS 16.5

That's why it makes sense to close the issue as it is high likely related to my old IOS version. 

Sorry for wasting your time. I will upgrade my IOS to avoid such cases in future.

**Comment by OmarBasem** [comment]
Thanks @pavloburykh, no problem!

**Comment by pavloburykh** [comment]
@OmarBasem hi! After updating IOS to 16.5.1 the bug is still reproducible for me. So I suppose the problem can be in device model (iPhone X). 

I will re-open issue in order we continue investigation.

**Comment by churik** [comment]
Confirm that it is reprocucible for me too on IOS 16.5.1, Iphone 14 Pro

**Comment by OmarBasem** [comment]
Hi @pavloburykh, can you check this build please and let me know if it fixes the issue: https://webapp.diawi.com/install/JZccSn

**Comment by pavloburykh** [comment]
> Hi @pavloburykh, can you check this build please and let me know if it fixes the issue: https://webapp.diawi.com/install/JZccSn

Hi @OmarBasem ! Thank you. Issue is fixed for me in the above build.

**Comment by OmarBasem** [comment]
Thanks @pavloburykh ! Could you please confirm if any of the below 2 builds have the bug:

1. https://webapp.diawi.com/install/okntDy
2. https://webapp.diawi.com/install/fpjyqe

**Comment by pavloburykh** [comment]
> Thanks @pavloburykh ! Could you please confirm if any of the below 2 builds have the bug:
> 
> 1. https://webapp.diawi.com/install/okntDy
> 2. https://webapp.diawi.com/install/fpjyqe

@OmarBasem I confirm that both builds still have the bug.

**Comment by OmarBasem** [comment]
Thanks @pavloburykh

**Comment by OmarBasem** [comment]
@pavloburykh made a PR: https://github.com/status-im/status-mobile/pull/17099

**Comment by pavloburykh** [comment]
> #17099

thank you @OmarBasem ! Will be able to take it into work tomorrow as I am off today. If any of QAs will have capacity - they will pick it up today.
