### ISSUE TITLE
The banner for a pinned message is with wrong opacity

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16142]
Introduced by https://github.com/status-im/status-mobile/pull/15204
сс: @alwx

### Actual result:
![image](https://github.com/status-im/status-mobile/assets/52490791/3116659d-55d5-484f-ae39-c34e8d90f221)

### Expected result:
The opacity is not applied for pinned banner
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=7771-637931&t=bO10p9W9PtOYFZdy-0

**Comment by alwx** [comment]
There are maybe three or four issues already created for the top bar, they are all the same. Closing it in favor of this one (which is bigger): https://github.com/status-im/status-mobile/issues/16089
