### ISSUE TITLE
[Android] 'Back' button and chat screen top bar overlaps elements on the device Status Bar when the chat is opened

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16144]
Introduced by https://github.com/status-im/status-mobile/pull/15204
cc: @alwx

### Steps:
1. Open chat

### Actual result:
![image](https://github.com/status-im/status-mobile/assets/52490791/ecfcba15-22df-4ecb-8b57-0b8be549b66c)

### Expected result:
'Back' and chat screen top bar is shown below the device Status bar

### Device:
- Real device: pixel 7a, Android 13

**Comment by pavloburykh** [comment]
duplicate of https://github.com/status-im/status-mobile/issues/16141
