### ISSUE TITLE
Expanded composer is covered by the top bar

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16143]
Introduced by https://github.com/status-im/status-mobile/pull/15204 cc @alwx

**Steps:** 

1. Open any chat 
2. Fully expand the composer
3. Observe the result

**Actual result:** expanded composer is covered by the top bar

https://github.com/status-im/status-mobile/assets/97245802/9405c390-11b3-45f1-9851-f6371effba2c

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Was fixed in https://github.com/status-im/status-mobile/pull/16179 but reverted because it introduced some other issues with some views. Leaving it to @OmarBasem to decide what to do with the positioning of the composer.
