### ISSUE TITLE
Pinned list button is absent when user is located at the top of the chat history

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16157]
Introduced by https://github.com/status-im/status-mobile/pull/15204 cc @alwx 

Causing pinned messages e2e tests to fail. 

**Steps:** 

1. Open any chat
2. Send some messages
3. Pin a message to generate pinned list
4. Scroll to the top of chat history 
5. See if pinned list button is availabe

**Actual result:** pinned list button is not shown. Unable to open pinned list as pinned list bar disappears when user located at the top of chat history. 

**Expected result:** pinned list button is displed as per design

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=7950-519665&t=XaUGsCIHDWIbcWct-0

<img width="313" alt="Messages for Mobile – Figma 2023-06-02 11-59-38" src="https://github.com/status-im/status-mobile/assets/97245802/019d8632-8db9-41de-bc1a-d500905fe78b">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by alwx** [comment]
Was it really ever there? I don't remember seeing this button in any chat before.

**Comment by pavloburykh** [comment]
> Was it really ever there? I don't remember seeing this button in any chat before.

@alwx It hasn't. However, prior to the introduction of the new top bar, there was no issue with the pin bar being invisible/unavailable when the user was at the top of the chat. So in order to overcome this problem we need to implement pinned button according to the designs. So this ticket also can be considered as feature request.

**Comment by flexsurfer** [comment]
related to: https://github.com/status-im/status-mobile/issues/16333
