### ISSUE TITLE
[Android] Auto-scrolling to the bottom after tapping the composer

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16153]
introduced by https://github.com/status-im/status-mobile/pull/15204
cc: @alwx

### Steps to reproduce:
1. Open a chat with a significant number of messages.
2. Scroll to any position within the chat view.
3. Tap on the composer to begin typing a message.

### Actual result:
After tapping on the composer, the chat view automatically scrolls to the bottom, bringing the latest messages into view

https://github.com/status-im/status-mobile/assets/52490791/3ec48d1f-c3a2-499c-ba62-6b089890cb8f

### Expected result:
Tapping on the composer should not trigger an automatic scroll to the bottom of the chat view.

### Device: 
- Real device: Pixel 7a, Android 13
- Android Emulator: Pixel XL API 29

**Comment by ibrkhalil** [comment]
Unassigned myself from this as @alwx will take a look later, [Ref](https://github.com/status-im/status-mobile/pull/16172#pullrequestreview-1462104728)
