### ISSUE TITLE
Top bar flashes on iOS after quickly scrolling to the top in the chat

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16156]
Introduced by https://github.com/status-im/status-mobile/pull/15204
cc: @alwx 

### Steps to reproduce:
1. Open a chat with a significant amount of messages.
2. Perform a quick scroll to the top by swiping upwards rapidly.

### Actual result:
The top bar of the screen flashes briefly during the quick scroll action

https://github.com/status-im/status-mobile/assets/52490791/268fcce1-90d2-4e5a-be8a-c6a4f13a16e9

### Expected result:
The top bar remains stable and does not flash during the quick scroll action

### Devices:
- iPhone 11 Pro max, IOS 16

**Comment by rasom** [comment]
Just a note: that happens only on the first scrolling (so if if scroll to the top, scroll down and then repeat scrolling to the top - there is no flickering) at the moment when older messages are loaded to the list.
