### ISSUE TITLE
The reaction are not matched to the designs into the 'who sent' bottom sheet

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16166]
Suspect that this issue may have arisen due to a conflict during the merge of https://github.com/status-im/status-mobile/pull/15677 and https://github.com/status-im/status-mobile/pull/16114
CC: @ibrkhalil @ilmotta could you check it, please

### Steps to reproduce:
1. Send a message in a chat.
2. Leave a reaction to the message.
3. a long tap on the reaction.

### Actual result:
The UI  of reactions displayed in "who sent" bottom sheet does not match the design. 
![image](https://github.com/status-im/status-mobile/assets/52490791/3be44ed5-c47c-462c-94bc-5f061e0d5dba)

### Expected result:
The reaction should match the design
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2102-171276

### Additional info:
Take a look, please. "Ugly cry" is still shown instead of the "Normal cry" reaction  on the "who sent" bottom sheet
![image](https://github.com/status-im/status-mobile/assets/52490791/fe2f481e-7b04-49a8-889e-e2778351b8fc)

**Comment by ibrkhalil** [comment]
> Suspect that this issue may have arisen due to a conflict during the merge of https://github.com/status-im/status-mobile/pull/15677 and https://github.com/status-im/status-mobile/pull/16114
> 
> CC: @ibrkhalil @ilmotta could you check it, please
> 
> 
> 
> ### Steps to reproduce:
> 
> 1. Send a message in a chat.
> 
> 2. Leave a reaction to the message.
> 
> 3. a long tap on the reaction.
> 
> 
> 
> ### Actual result:
> 
> The UI  of reactions displayed in "who sent" bottom sheet does not match the design. 
> 
> ![image](https://github.com/status-im/status-mobile/assets/52490791/3be44ed5-c47c-462c-94bc-5f061e0d5dba)
> 
> 
> 
> 
> 
> ### Expected result:
> 
> The reaction should match the design
> 
> https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2102-171276
> 
> 
> 
> ### Additional info:
> 
> Take a look, please. "Ugly cry" is still shown instead of the "Normal cry" reaction  on the "who sent" bottom sheet
> 
> ![image](https://github.com/status-im/status-mobile/assets/52490791/fe2f481e-7b04-49a8-889e-e2778351b8fc)
> 
> 

No worries, I'll be back tomorrow and take a look

**Comment by ilmotta** [comment]
Most definitely related to a rebase, thanks @VladimrLitvinenko.
