### ISSUE TITLE
Create single subscription for customization-color

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#16175]
#### Problem
We are using three subscriptions for accessing a single `customization-color` property, in chat, communities & shell screens.
We should use a single subscription, it will be best if we move this subscription to the child(where it is used), so the whole view doesn't rerender when the value changes.

Like in the below case, move subscription to the shell function and also create a separate function for `[quo/floating-shell-button` and use it there.

![image](https://github.com/status-im/status-mobile/assets/17097240/46a66d4c-5771-4f4f-b339-0cd4fc3c5be3)

related to changes in https://github.com/status-im/status-mobile/pull/15860 cc @jo-mut

**Comment by jo-mut** [comment]
thanks @Parveshdhull

**Comment by ulisesmac** [comment]
@J-Son89 This issue has already been reported

**Comment by flexsurfer** [comment]
> , so the whole view doesn't rerender when the value changes.

this sub won't be changing

**Comment by Parveshdhull** [comment]
> this sub won't be changing

Yes, it shouldn't change. But still having subscription in root of tree looks little unsafe.
Not sure, but we probably will allow user to change customization-color from setting.
But feel free to skip it for now, we can address this later.
