### ISSUE TITLE
Implement Options for communtie's channel

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#16178]
Design: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=6301-422452&t=sHzSqc7SUJQNVVgm-4

Some options might be correlated with community's options:
https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/communities/actions/community_options/view.cljs

- [ ] View channel members and details
- [ ] View token requirements
- [ ] Mark as read
- [ ] Mute channel
- [ ] Notication settings
- [ ] Fetch messages
- [ ] Invite people from contacts list
- [ ] Show QR code
- [ ] Share channel

**Comment by ilmotta** [comment]
@flexsurfer, I recently merged a PR to display all options according to Figma, but I postponed the implementation of what the options themselves do, since that would be too much for a single PR.

I would like to create individual issues for implementing each option. This will be helpful for other collaborators to parallelize work, hence, can we close this issue?

**Comment by flexsurfer** [comment]
@ilmotta we could have all issues linked here, to monitor the progress, and use this issue like an epic (parent issue)

**Comment by flexsurfer** [comment]
but actually, its up to you :)

**Comment by ilmotta** [comment]
Cool @flexsurfer. I'll do the following: use the existing Communities project https://github.com/orgs/status-im/projects/81/views/1 to track the progress and maybe create a separate *area* in the project. btw I also like this approach of using an issue as an epic tracker :) Thanks

**Comment by flexsurfer** [comment]
cool @ilmotta feel free to close this issue whenever you need

**Comment by ilmotta** [comment]
FYI: The implementation of each option mentioned in this issue will be tracked in the Communities project in the area `Context Actions` https://github.com/orgs/status-im/projects/81/views/1
