### ISSUE TITLE
Error and crash on pressing 'Edit community'

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16183]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/67952253/bb8b5bad-2a2a-407d-aef9-5264505ba3e1

### Reproduction

1. Create a community
2. Long press on the community on the community screen
3. Hit `Edit community`

### Logs
[geth.log](https://github.com/status-im/status-mobile/files/11652461/geth.log)

### Additional Information

- Status version: nightly 5/06
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vkjr** [comment]
@qoqobolo, old community editing screen was removed from the project in #15994, this is why the attempt to open it fails.
I can remove this menu option or make it non-functional, which is preferable? I would vote for removing)

**Comment by qoqobolo** [comment]
> I can remove this menu option or make it non-functional, which is preferable? I would vote for removing)

I think we should keep it and make it non-functional. We already have such items in this menu, so let's leave it as it is in order to preserve the appearance :)
The info toast should appear on pressing it.

**Comment by flexsurfer** [comment]
we keep communities management only temporary for e2e because import doesn't work, so we can remove this item cc @qoqobolo @vkjr

**Comment by qoqobolo** [comment]
@flexsurfer ah you're right, so if removing is easier it totally makes sense, thank you!

**Comment by vkjr** [comment]
Closed by #16186
