### ISSUE TITLE
Wrong background around "Continue" button on Create Profile screen (design review)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16181]
Change the background according to design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428189441))
Figma Notes:
This background is wrong:
Only has to appear when button covers top content (colours)
It's too dark, check design here: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=6345%3A327366&t=azdmhomknDfXwYtl-1

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@jo-mut -  the colors etc is handled in my pr here: https://github.com/status-im/status-mobile/pull/16291
I believe all that's left is the mechanism to hide/show the background container around the "continue" button when there is content behind it or not. 

Feel free to ping me as I have already looked into this a bit so I have figured out some parts of the solution 👌
