### ISSUE TITLE
Messaging - Maximized composer is covered by top header

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16197]
# Bug

When the user maximizes the composer, the cursor and input field are partially covered by the top header.

<img src="https://github.com/status-im/status-mobile/assets/46027/39b9b4f6-8487-4e59-a204-70ae5b843030" height="700" />

This bug might be related to how the height is calculated, so maybe fixing https://github.com/status-im/status-mobile/issues/16093 will fix this one.

**Comment by alwx** [comment]
Closing in favor of this one: https://github.com/status-im/status-mobile/issues/16143
