### ISSUE TITLE
Integrate with upcoming changes in the "Request to join" community flow

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16196]
# Problem

The desktop team is working on the flow to `Request to Join` communities. Basically we realized token-gated or not, users will need to share their public addresses. This requires changes in status-go that the desktop team is already on top of.

For the mobile project `UI Fit & Finish` **we should add a WIP screen after the button `Request to join` is pressed*. Details need to be sorted out still. Reach out to @John-44 and/or @0x-r4bbit for more details before proceeding with the implementation. 

`Mobile App` > `Communities for Mobile`: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733-125561&t=UgJ3cSEVP1QlntXF-0

<img src="https://github.com/status-im/status-mobile/assets/46027/6b04189b-dcd2-4fb2-b749-41bc80655d17" height="700" />

**Comment by 0x-r4bbit** [comment]
A lot of the details on how this currently works can be found here: https://github.com/status-im/status-desktop/issues/10853#issuecomment-1578128097

**Comment by ilmotta** [comment]
Closing because it's already done.
