### ISSUE TITLE
Image in reply disappears for user who deleted the quoted message until chat is reopened after the quoted message is removed

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16203]
### Steps to Reproduce:
1. User A and User B are in a chat conversation.
2. User A sends a message with an image.
3. User B replies to the message, including the image in the reply.
4. User B removes the quoted message (original message with the image).
5. User B observes the reply section.

### Actual Result:
The image in the reply section disappears for User_B after the quoted message is removed, leaving an empty reply section.

https://github.com/status-im/status-mobile/assets/52490791/22b51ac7-3424-412c-84bf-dfc01fd96584

### Expected Result:
The image in the reply section should remain visible even after the quoted message is removed.

### ENV: 
- nightly [6 Jun 2023]

### Device:
[Status.log](https://github.com/status-im/status-mobile/files/11666092/Status.log)
https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

**Comment by rasom** [comment]
@VladimrLitvinenko was this behaviour previously discussed/documented somewhere? IMO it makes sense to show that reply was written for a removed message instead of keeping the image there. I suppose it might be deleted for a reason :)

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko was this behaviour previously discussed/documented somewhere? IMO it makes sense to show that reply was written for a removed message instead of keeping the image there. I suppose it might be deleted for a reason :)

@rasom I haven't seen a discussion about this. Looks like this is an edge case that probably was missed during image testing

**Comment by rasom** [comment]
so then, I suppose, it has to be discussed before making changes, as I'm not sure that this is actually the expectation:
> The image in the reply section should remain visible even after the quoted message is removed.

**Comment by cammellos** [comment]
@VladimrLitvinenko this should be fixed in develop, would you mind checking please? 
Thank you

**Comment by VolodLytvynenko** [comment]
Hi @cammellos the issue is fixed in cases when 'delete for everyone' option is used. 
One issue is still reproducible:
## ISSUE 1: [Android] Image/album in reply disappears for user who deleted the quoted message by 'delete for me' option
1. User sends a message with an image or album.
2. User replies to the message, including the image in the reply.
3. User  removes the quoted message  (original message with the image) by "delete for me" option.
4. User observes the reply section.

### Actual result:
The image in the reply section disappears after the quoted message is removed, leaving an empty reply section.

https://github.com/status-im/status-mobile/assets/52490791/79bab1d1-ab49-475c-81f0-c561c1b2f29c


### Expected result:
The image in the reply section should remain visible even after the quoted message is removed.

### Additional info:
in 50% of cases the same issue reproduces for IOS devices

### logs:
[logs.zip](https://github.com/status-im/status-mobile/files/11871473/logs.zip)
[[Status.log](https://github.com/status-im/status-mobile/files/11871474/Status.log)](https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0)
