### ISSUE TITLE
Bottom sheet screen background too dark

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16214]
On Android, when opening the photo selector, the background looks too dark, the status bar is barely visible. It does not look as dark in other screens (for example, the new chat screen). This could have been introduced by recent changes to the chat screen.

![Screenshot_20230607_095557_Status Debug](https://github.com/status-im/status-mobile/assets/29354102/a62b6582-7c3e-42b8-864a-891b186606e3)

![Screenshot_20230607_095605_Status Debug](https://github.com/status-im/status-mobile/assets/29354102/3e986855-c6db-4b5e-a8dc-b87131ef96ad)

**Comment by flexsurfer** [comment]
yes it's a known issue of blur on Android

**Comment by flexsurfer** [comment]
<img width="663" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/40331e9f-514a-42ff-a4d2-61c15014d3cc">

**Comment by ilmotta** [comment]
> yes it's a known issue of blur on Android
> -- https://github.com/status-im/status-mobile/issues/16214#issuecomment-1580620686

@briansztamfater, cc'ing you because the new blur solution you've been experimenting may allow us to fix this issue.

**Comment by churik** [comment]
It works Ok as far as I can see on nightly 20/06/24. Reopen if still relevant.
![IMAGE 2024-06-20 17:05:20](https://github.com/status-im/status-mobile/assets/4557972/d6aba120-c5ae-4e7e-9e0c-e547ef83ce5b)
