### ISSUE TITLE
Send transaction action from contact profile should prefill user in send command

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1621]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I don't want to type or select the name of my contact again after selecting the action `send transaction` from his profile

### Description

*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Currently when selecting the `send transaction` action from a contact profile I still have to type or select his name before being able to select an amount and send it

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to contacts
- Select Jarrad
- Click on the profile icon on the top right corner and select profile
- Select Send transaction

The `/send` command is selected but you still have to input the user before being able to select an amount

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Wait for issue #1617 to be resolved

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by janherich** [comment]
PRs #1671 and #1709 both solve this issue.

**Comment by asemiankevich** [comment]
despite name being prefilled, the focus is not on input field after the action so user still needs to tap into the field to get the transaction screen. Agreed with @janherich to fix it

**Comment by sla-shi** [comment]
Removing from the current milestone as a minor issue. The original bug does not reproduce in 0.9.11.

**Comment by janherich** [comment]
With the new `/send` command, I think the issue is not relevant anymore.

**Comment by yenda** [comment]
Indeed
