### ISSUE TITLE
Monospace Font

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/status-react#1623]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I should be typing and viewing with a monospaced font, that makes clear distinctions between all characters, i.e between l and I, 0 and O 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

On all platforms we should do our best to remove any doubts, avoid confusion or misleading the user. currently the fonts are at risk to this.

**Comment by oskarth** [comment]
Effectively not high priority considering how long it has been dormant.

**Comment by oskarth** [comment]
Still, ping @andmironov and @denis-sharypin re progress on this
