### ISSUE TITLE
Implement network connections in quo2 preview

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#16238]
We would like to implement the network connection screen in the quo preview:

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-UI-for-Mobile?type=design&node-id=318-164884&t=SXMGOCOrB0pCzC66-4

The scope is only the one displayed in the image, use figma as a reference for the real designs rather than the image attached, as it might get out of date.

![conv5_000](https://github.com/status-im/status-mobile/assets/1017008/9e627697-78fb-49e5-850b-1ab6c005c20e)

You want to allow in the quo preview to create connection from the `From` side to the `To` side, so we can see different configurations (up to you which configurations you would like to display and how the user of the preview will select them, but the system should be flexible enough to allow a fair amount of configurations).

Have a word/chat with our designers before starting to implement to clarify the interactions. 
You should be re-using existing components where available and create components when not.

**Comment by J-Son89** [comment]
this is a duplicate as we broke the issue down into smaller parts
