### ISSUE TITLE
add camera flash mode option during syncing

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#16243]
The current camera implementation does not really support flash mode as is in the figma designs. Consult with the following design to add camera flash mode

https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429186829

**Comment by silenteyesoncode** [comment]
@jo-mut 

Is it a tech(development) issue ? 
I want to contribute.

**Comment by jo-mut** [comment]
@silenteyesoncode yeah but you might want to wait until https://github.com/status-im/status-mobile/pull/16248 is merged as the issue with cameraKit is addressed here already.

**Comment by silenteyesoncode** [comment]
Please assign me once the merge for #16248 is completed. Thank you!
@jo-mut

**Comment by smohamedjavid** [comment]
@silenteyesoncode - The PR (#16248) is merged. 

We highly appreciate your interest in contributing to Status.

You can start working on this issue, and I will assign this issue to you. 
Refer to our [docs](https://github.com/status-im/status-mobile/tree/develop/doc) for a quick start if required.

We appreciate your giving timely updates.

Thanks!

**Comment by silenteyesoncode** [comment]
thank @smohamedjavid 
I'm on it

**Comment by silenteyesoncode** [comment]
@smohamedjavid  do i need figma for this ?
if **yes** how can i get access , as the above link doesn't  work in description

**Comment by smohamedjavid** [comment]
@silenteyesoncode - I believe you don't need Figma. But, I will check if I can get you access and update you.


Meanwhile, the existing code has the flash button:

https://github.com/status-im/status-mobile/blob/d91e67cae7fd85765389ab64b3ada202c815b771/src/status_im2/contexts/syncing/scan_sync_code/view.cljs#L178-L185

Feel free to run the app and check.
If the flash is on, you need to use the icon `:i/flashlight-on`.

**Comment by silenteyesoncode** [comment]
hi @smohamedjavid 

- I need help setting up the IDE with vsCode
- Also What branch should i use for my parent repo to make the changes

### [No file found in Status development](https://github.com/status-im/status-mobile/blob/develop/doc/ide-setup.md#start-and-connect-the-repl)

<img src="https://github.com/status-im/status-mobile/assets/46851135/0f95d101-0893-45db-b507-c92c555ce1a2"  width="500" >

**Comment by smohamedjavid** [comment]
Hey @silenteyesoncode,

> I need help setting up the IDE with vsCode

Apologies for the `No file found` error. We will get the docs updated.

I'm adding the correct [Status development](https://github.com/status-im/status-mobile/blob/develop/doc/starting-guide.md#development) link here to unblock your progress.

Having Calva installed in VS Code should be fine (Step 0) for development. Connecting to project [REPL](https://github.com/status-im/status-mobile/blob/develop/doc/ide-setup.md#start-and-connect-the-repl) is needed if you want to perform any actions inside it.


> Also What branch should i use for my parent repo to make the changes

Please fork the repo and start with the `develop` branch.

**Comment by smohamedjavid** [comment]
@silenteyesoncode - Can you help me share your email address for the design access?

**Comment by silenteyesoncode** [comment]
Sure, here you go @smohamedjavid 
7silenteyes07@gmail.com

**Comment by silenteyesoncode** [comment]
![Screenshot 2023-06-26 172413](https://github.com/status-im/status-mobile/assets/46851135/e2b8a0c5-b2bd-43a3-919f-d1e9e14db49f)

@smohamedjavid  i did install the make and setup the environment variable, still wasn't able to install the node lib.
can you help

**Comment by siddarthkay** [comment]
@silenteyesoncode : you'll have to run the make commands in linux subsystem for windows OR (WSL)
also commands like `yarn` should not be run unless you're inside a `nix` shell, from the screenshot I can tell you're in a normal terminal.
Once you have WSL setup you would need to run 
`make run-clojure` then 
`make run-metro` then 
`make run-android` 
in this order in 3 different terminals for initial setup.

**Comment by silenteyesoncode** [comment]
<img src="https://github.com/status-im/status-mobile/assets/46851135/1a058c31-3924-4f09-98d5-fcc4376587b3"  width="500" >

![Screenshot 2023-06-26 180208](https://github.com/status-im/status-mobile/assets/46851135/d55eea10-5e13-4480-a6af-f77c80006cf1)

hi @siddarthkay ,
i did install make and add the environment variable, but cannot run make , even the version.
Can you please help me what i'm missing here

**Comment by siddarthkay** [comment]
> what i'm missing here

WSL

**Comment by silenteyesoncode** [comment]
isn't any other way to start the App and make changes ?
 like you mention nix?
@siddarthkay

**Comment by siddarthkay** [comment]
@silenteyesoncode : you can run the app on either macOS or linux. 

If setting up WSL is proving difficult then you could install ubuntu or some other linux distro on dual boot and use that as another option.

`nix` runs only on linux OR MacOS OR windows via WSL(which is basically linux).

**Comment by silenteyesoncode** [comment]
@siddarthkay 
okayy,
I giving my next 100% shot again

**Comment by smohamedjavid** [comment]
Hey, @silenteyesoncode - Kindly keep us posted.

**Comment by silenteyesoncode** [comment]
@smohamedjavid sure 
Just give me 2 days
i just setup wsl

**Comment by silenteyesoncode** [comment]
@smohamedjavid i couldn't make the necessary changes 
may be someone else can contribute here

**Comment by smohamedjavid** [comment]
@silenteyesoncode - Thank you for your efforts. 
No worries. Feel free to contribute to Status anytime.

P.S. Installing a Linux distro as a dual boot would help you a lot in development.
