### ISSUE TITLE
[Pixel 7a, Android 13] 'Mail client should be configured' pop-up appears after attempting to submit the logs by gmail client

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16251]
### Note:
The issue is likely device-specific, as it has only been reproduced on the Pixel 7a running Android 13 (It has also been reproduced by @qoqobolo, who uses the same device. ). The issue occurs specifically when using Gmail as the mail client, but works with Outlook mail client. Other similar applications successfully open the Gmail client in their 'contact us' sections.

### Preconditions:
 Ensure that no mail client is currently configured on the system.

### Steps to Reproduce:
1. Launch the application.
2. Generate logs by shaking the app
3. Click on the "Submit by email with Logs" button.
4. Ensure that no mail client is currently configured on the system.

### Actual Result:
A pop-up message with the text 'mail client should be configured' appears, preventing the logs from being submitted via gmail.

On the 16th sec I've just show that the similar functionality works well for 'Podcast Discover' application

https://github.com/status-im/status-mobile/assets/52490791/85d48707-09b2-4af3-bf1e-0ecb9680520d

### Expected Result:
The mail client is opened

### Device:
- real device: Pixel 7a, Android 13

### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/11723845/android_logcat.txt)

**Comment by rasom** [comment]
https://github.com/chirag04/react-native-mail/issues/196

**Comment by rasom** [comment]
to fix this issue the android sdk has to be upgraded to version 33 and this causes a cascade of failures in other RN modules we have

**Comment by churik** [comment]
It is not reproducible manymore
