### ISSUE TITLE
Error null is not an object (evaluating 'cljs.core.deref(status_im.components.drawer.view.drawer_atom).openDrawerr') [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1626]
### Description

*Type*: Bug

*Summary*:  I was browsing quickly in the app interacting with group chats screen and list of contacts and I have selected Auction house dapp and then tapped "back" and received the error

#### Actual behavior
Error null is not an object (evaluating 'cljs.core.deref(status_im.components.drawer.view.drawer_atom).openDrawerr')

### Reproduction
Can't provide the STR right now, however here is TF session: https://app.testfairy.com/projects/4803622-status/builds/6366923/sessions/4/?accessToken=myFxG9tpe-9RECT6LBy1I7h33tU

![screenshot_2017-08-16-15-01-59-593_im status ethereum](https://user-images.githubusercontent.com/28752642/29363203-bf71ba16-8297-11e7-8294-bf1b3e98ec04.png)

### Additional Information
* Status version: Status / 0.9.8-137-g9bacc65c+ (1566)
* Operating System: Xiaomi Redmi Note4 Pro, Android 6.0.1

**Comment by jeluard** [comment]
@asemiankevich Is this still relevant?

**Comment by asemiankevich** [comment]
@jeluard havent seen this in recent develop, let's close
