### ISSUE TITLE
Refactor counter component

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#16261]
# Problem

The API to call the counter (`quo2.components.counter.counter`) component receives a property `:override-bg-color ` instead of `customization-color` as the other components we are creating.

We should fix the API and uses across the app

Also we should split the code in a `view` and `style` file

**Comment by ulisesmac** [comment]
@J-Son89 this issue is blocked unitl we manage to handle customization colors and community colors in the same way.

This `override-bg-color` property is receiving a string that could be a customization color or not. So I think it's better to refactor this component once we have merged a common way to handle the colors.

**Comment by J-Son89** [comment]
I believe this is a duplicate @ulisesmac and it's already done https://github.com/status-im/status-mobile/pull/16799
