### ISSUE TITLE
Partially implement browser transaction sheet

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#16264]
This issue is to track the implementation of the browser transaction sheet:

https://www.figma.com/file/VsV8jYZc7jYUHkPkOUrkyR/Browser-for-Mobile?type=design&node-id=816-17181&t=QRhLsaP5uVuyZWts-4

Please re-use existing components when available and place implementation in the preview screens.

Only what is in this screenshot is in scope, please use figma as a reference though.

Select account should be scrollable horizontally and should show the other accounts.

You can use mock data for the preview.

Have a word with our designers before staring to clarify interactions.

![selector](https://github.com/status-im/status-mobile/assets/1017008/194eeab8-5c8e-425c-94e7-446ba5f4c9fe)

**Comment by tumanov-alex** [comment]
I'm working on this

**Comment by J-Son89** [comment]
Completed in pr
