### ISSUE TITLE
Refactor Shell code to use quo2 components for switcher cards

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16276]
Using the quo2 components created in:
https://github.com/status-im/status-mobile/issues/16273
https://github.com/status-im/status-mobile/issues/16274
https://github.com/status-im/status-mobile/issues/16275

Refactor the use of the switcher cards in the shell namespace within status_im2. Create wrapped components (Similar to: src/status_im2/contexts/chat/messages/pin/banner/view.cljs ) where subs are needed to pass data to these components. 

Remove old switcher preview screens which was used for all of the cards. i.e:
status-im2.contexts.quo-preview.switcher.switcher-cards

**Comment by Parveshdhull** [comment]
they were initially implemented in quo2 namespace itself https://github.com/status-im/status-mobile/pull/14308#discussion_r1018096433, we moved them later

**Comment by J-Son89** [comment]
Hmm, for what reason?

**Comment by Parveshdhull** [comment]
cc @flexsurfer

**Comment by J-Son89** [comment]
Thank @Parveshdhull, seems that was because of i18n which we now use in quo2. I guess we were figuring out what would be best at the time.
Anyway it's a cleaner separation of concerns with the UI aspect for components in quo2. Also these should be created as multiple individual components as seen in the designs and not one large component for all cases. I guess the basic styling structure can be shared across them 👍

**Comment by Parveshdhull** [comment]
> I guess the basic styling structure can be shared across them

Apart from style, they also share same view hierarchy (except avatar). Please can you elaborate what will be benefit of separating them?

**Comment by Parveshdhull** [comment]
There are both pros and cons, code might look little simpler (although, most of the code is shared), but we need to fix every component if there is any bug

**Comment by J-Son89** [comment]
We are following the approach to match the designs, some of these components have different use cases than others.
Long term if the designs change for an individual card component we can easily isolate to adjust for just that use case 👍 
They could have a `base-card` component similar to how we are handling tags: src/quo2/components/tags/status_tags.cljs

**Comment by Parveshdhull** [comment]
base-card approach sounds ok, so in short we will isolate screen-card function into, `base-screen-card` file and instead of using function
```
    (shell.constants/one-to-one-chat-card ;; Screens Card
     shell.constants/private-group-chat-card
     shell.constants/community-card
     shell.constants/community-channel-card)
    [screens-card data]
```
we will create separate component files for them?

**Comment by Parveshdhull** [comment]
> They could have a base-card component similar to how we are handling tags: src/quo2/components/tags/status_tags.cljs

Thanks for clarification, sounds good. Please hold implementation until https://github.com/status-im/status-mobile/pull/15893 is merged, otherwise there will be conflicts.

**Comment by J-Son89** [comment]
Let's get the quo2 components in place and then figure out the best approach for this. But I think it will be along the lines of that. That's fine to wait with this until 15893 is merged 👍

**Comment by J-Son89** [comment]
@codemaster115 - there is some feedback from 1.24 release, it will be good to ensure all of these details are satisfied too 👍 
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3662-32691&mode=design&t=bIZIqzvYkSPhlGKx-4

**Comment by ilmotta** [comment]
Closing because Jump To feature is disabled and descoped.
