### ISSUE TITLE
implement quo2 switcher / 1-1 Message Card

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16274]
Implement the quo2 component

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=911-27084&t=J3iynkJ5hh44GvbG-0

These components already exist in: src/status_im2/contexts/shell/cards/view.cljs

Create the component in isolation to the status mobile best practices.
Add component spec test
Add it's own preview screen (currently shared among others)

**Comment by ilmotta** [comment]
Closing because Jump To feature is disabled and descoped.
