### ISSUE TITLE
Add Testnet warning, so no real ether or SNT is sent to the app

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1628]
### Description

*Type*: Feature

*Summary*: Need a warning that app works only in Ropstent Testnet, so users do not to send real ether or SNT to it. 

To send ether to the app user will need to get the address. So, we can add a warning on profile screen next to the address field - `Ropsten Testnet only, do not send real ETH or SNT to the address`

**Comment by andmironov** [comment]
![ios_profile copy](https://user-images.githubusercontent.com/3115606/30162050-d6906f80-93db-11e7-91c1-441c3c17fb98.png)
![android_profile copy 6](https://user-images.githubusercontent.com/3115606/30162049-d68ed634-93db-11e7-8b2d-5a09ab7533fc.png)

added warnings to profile, updated zeplin

https://zpl.io/aw6mKjV
https://zpl.io/2GxJB3V
