### ISSUE TITLE
Token registry to automatically get balance for address in wallet

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1629]
## User story
As a token holder I want to see the tokens I own automatically. At least the common ones.

## Acceptance criteria

Undefined so far.

## Suggestions

- 3esmit: Use Parity in chain smart contracts that contains the token list 
- 3esmit: Have our own in chain tokenreg list controlled by SNT holders
- 3esmit: User configuration for his own custom tokens
- Jarrad: token registry smart contract or use anothers, detect which network we are on and switch contract address for either, that way interface is the same

- 3esmit: start with config file or token list from parity, if token list get too big we make other list with defaults selected, and a local userlist. I think that instead of using token list from parity, having our own token list controlled by us and later we change controller to SNT quorum (voting by holders).

## Open questions
- Non ERC20 contracts?
- Which registry to use?
- What if contract isn't in registry?
- How deal with testing for non mainnet?

## See also
https://github.com/ethereum/EIPs/issues/22

**Comment by jeluard** [comment]
@oskarth Is that still relevant?

**Comment by oskarth** [comment]
@jeluard Not sure, you worked on this piece of the code most recently (ERC20). WDYT? Could go either way.

**Comment by jeluard** [comment]
We now have a dedicated [idea](https://github.com/status-im/ideas/issues/18) to track this so I think we can close this issue for now.
