### ISSUE TITLE
Add/Remove Contact Test

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#163]
Test user path flows for adding and removing contacts

Need to discuss and flesh out

**Comment by p14n** [comment]
Are these tests to be written in Appium or cljs?

**Comment by p14n** [comment]
Are these tests to be written in Appium or cljs?

**Comment by jeluard** [comment]
We are targeting Appium tests written in cljs (based on the nodejs API). There is not infrastructure for this yet.
Feel free to give it a try!

**Comment by p14n** [comment]
Cool, so the maven/java appium tests are old and should be ignored?  Or are they a partial implementation somehow?

**Comment by jeluard** [comment]
Yes that's an older attempt that will eventually be removed.
