### ISSUE TITLE
App crash due memory violation

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#1630]
### Description

*Type*:  Bug

*Summary*: App crashes without giving any error at screen, just vanishes.

### Additional Information
* Status version: 0.9.10

* Operating System: Android 6.0.1

#### Logs
See https://pastebin.com/Zr8mzjbA

**Comment by sla-shi** [comment]
Might be already fixed, need to verify with the test team.

**Comment by 3esmit** [comment]
I guess no, I think might be a device specific issue as I'm the only one having this issue, I'm up to doing any debug requested.

**Comment by yenda** [comment]
@3esmit is it still relevant ?

**Comment by 3esmit** [comment]
never happened again
