### ISSUE TITLE
Communities - Display members & active members count

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16312]
# Feature

Display real communities tags in the community's overview screen and in the discover communities screen.

<img src="https://github.com/status-im/status-mobile/assets/46027/efb22b5e-67f9-4740-be58-7f30c201825f" height="400" />

<img src="https://github.com/status-im/status-mobile/assets/46027/e63ed902-95fa-4dd0-a8d2-de0c431e6522" height="800" />

### Notes

Community stats should only be displayed in the Discover Communities screen. Stats in the communities list home screen is for post-MVP.

**Comment by ibrkhalil** [comment]
Can I start working on this?

**Comment by ilmotta** [comment]
Sure @ibrkhalil! I don't see any blocker. I believe everything is implemented in status-go, you will just need to create communities and add tags using another client.

**Comment by ibrkhalil** [comment]
Unassigning now to focus on MVP

**Comment by ilmotta** [comment]
I'm marking this issue as blocked until https://github.com/status-im/status-mobile/issues/17852 is resolved because it will make development & testing much easier.

**Comment by ilmotta** [comment]
This issue needs to be revisited. For the time being, I'm closing it since we haven't worked on it for a long time.

cc @churik
