### ISSUE TITLE
Let user see Community token requirements

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16316]
# Feature

Replace the dummy implementation in https://github.com/status-im/status-mobile/blob/204c8996a3ef5ffa72c5f6b1ccff9da8030165e1/src/status_im2/contexts/communities/actions/chat/view.cljs#L13 with a real one to show the token requirements.

Figma specs: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10459-412961&t=pXNSd5fOxJ4kLEOP-0

<img src="https://github.com/status-im/status-mobile/assets/46027/72142dd3-5513-4d34-bd8c-cd0e15788629" height="600" />

## Notes

The option should appear in the following conditions:

- User opened a Community Channel and pressed the header section hamburger button.
- User is in the Community overview screen and pressed the hamburger button.

Also note that **the current implementation is incorrect and should only display the option if the community is token gated**.

**Comment by cammellos** [comment]
closing as completed
