### ISSUE TITLE
Implement Community Channel option: Fetch messages

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16317]
# Feature

When a community channel (chat) is opened and the hamburger button is pressed, the dummy option "Fetch messages" should be replaced by an implementation that actually works (back & front). See in [Figma > Mobile App > Communities for Mobile > Context Actions](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=5483-218804&t=Z7a04wl2Gho9l74P-0)

<img src="https://github.com/status-im/status-mobile/assets/46027/bc73be1c-b1c1-4816-8988-d7935de45e82" height="500" />
<img src="https://github.com/status-im/status-mobile/assets/46027/840b2bcd-0234-4b87-bbe3-0d880e2737a4" height="500" />

**Comment by cammellos** [comment]
closing this as it's not scheduled for development
