### ISSUE TITLE
Implement Community Channel option: Share channel

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16318]
# Feature

Implement the "Share channel" option for any given community channel. See [Figma > Communities for Mobile > Channels](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=12658-458976&t=aX6zgxCZpQkj548k-0)

<img src="https://github.com/status-im/status-mobile/assets/46027/83965b7b-9a21-42b0-b9c4-216cdbe14f0e" height="600" />

<img src="https://github.com/status-im/status-mobile/assets/46027/b797ba66-84f6-4383-bfe9-af0ab3c61233" height="500" />

**Comment by yqrashawn** [comment]
Note: please consider using new format when generating the share link, detail in this comment https://github.com/status-im/status-mobile/pull/17480#issue-1923524297
related status-go PR: https://github.com/status-im/status-go/commit/511d6bfc540fde0e92f61f7e45b77ece73debdd5#diff-a594611e93b4c54ab50482007b066651b63e421f41b0e375e2949c8afa5e9d30R1340
design/flow: https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=2344-285187&mode=design&t=vWMeZ1JgyGnkmWKx-4

**Comment by J-Son89** [comment]
I think this is now done, https://github.com/status-im/status-mobile/pull/18271
@yqrashawn - can you check it's using the correct link format? otherwise we can close this issue agaik

**Comment by yqrashawn** [comment]
Checked the code at https://github.com/status-im/status-mobile/pull/18516/files#diff-63b184880cbf5c0450f717326801b4e79c54135e30c0bdffc1528b4c8fd89b65R226
It's using the correct RPC method

**Comment by ilmotta** [comment]
Closing the issue since @yqrashawn confirmed it's working as expected.
