### ISSUE TITLE
`make run-ios-device DEVICE_NAME="YOUR DEVICE NAME"` fails while building with error code 65

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#16310]
# Bug Report

## Problem 
As reported first by @Parveshdhull and then by @igor-sirotin 
- make show-ios-devices : gives the name of attached iPhone properly
- when using the name of the connected iPhone like this : `make run-ios-device DEVICE_NAME="YOUR DEVICE NAME"` causes iOS build to fail with error code 65.

### Screenshots 

<img width="1674" alt="igor-ios-error" src="https://github.com/status-im/status-mobile/assets/64726664/90506f46-1c2d-4820-9843-437f113aed3f">

**Comment by ibrkhalil** [comment]
Can you retry with node v16.16.0?

**Comment by siddarthkay** [comment]
@ibrkhalil : we use these commands within nix context and we set nodejs version here 
https://github.com/status-im/status-mobile/blob/develop/nix/overlay.nix#L61
which is set to v18.

This issue is not node specific since it works on both my old and my new macbook.
Its probably something else.

**Comment by ibrkhalil** [comment]
> @ibrkhalil : we use these commands within nix context and we set nodejs version here https://github.com/status-im/status-mobile/blob/develop/nix/overlay.nix#L61 which is set to v18.
> 
> This issue is not node specific since it works on both my old and my new macbook. Its probably something else.

Hmmm, I had the same exact issue two days ago when building on a physical device.
What I did was use `nvm` to use node 16 and made sure that the `development team` settings on XCode are done correctly.
And when selecting a project file make sure to use the one with the `.xcodeproj` extension inside `status-mobile/ios`

**Comment by siddarthkay** [comment]
Thanks @ibrkhalil : I'll try recreating this locally, and if `nvm` is indeed being preferred over `nix` then that is a bigger problem to solve. 
Thanks for sharing!

**Comment by siddarthkay** [comment]
@ibrkhalil : just to follow up on what you did, were you able to finally deploy on your physical iOS device using Xcode.app or using `make run-ios-device` command?

**Comment by ibrkhalil** [comment]
> @ibrkhalil : just to follow up on what you did, were you able to finally deploy on your physical iOS device using Xcode.app or using `make run-ios-device` command?

`make run-ios-device`

**Comment by siddarthkay** [comment]
update : This issue was automatically fixed for @Parveshdhull right after he updated his macbook to latest update :)
I have not yet tried to recreate this but will try to do so next week.
