### ISSUE TITLE
Implement all variants for QR code

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16329]
# Feature

Implement the "Show QR code" option for any given community channel. See [Figma > Sharing for Mobile > Share from Status](https://www.figma.com/file/Nt3KJ8AXm0VPpIRLxaHnw0/Sharing-for-Mobile?type=design&node-id=2345-300688&t=6ebQeYEMqiGEVxn5-0)

<img src="https://github.com/status-im/status-mobile/assets/46027/d279c431-e6e1-410f-85f1-edc1fbbe1351" height="600" />

## Update:

Implement all variants for the QR code component:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=17928-209739&mode=design&t=mOWDt2exmZ2Al72p-4
![image](https://github.com/status-im/status-mobile/assets/90291778/a7431a24-f35d-42df-90eb-2c282f7942ec)

**Comment by ulisesmac** [comment]
@ilmotta for the wallet we need to implement all variants, so I'm taking this issue and edited the description to cover all of them :+1:

**Comment by ilmotta** [comment]
> @ilmotta for the wallet we need to implement all variants, so I'm taking this issue and edited the description to cover all of them 👍

Just saw your conversation in Discord @ulisesmac. Thanks for updating the issue too.

**Comment by ulisesmac** [comment]
I'm removing my assignment in this issue since it's going to be addressed in status-go. 

@siddarthkay Maybe after having these avatars implemented in status-go you could take this issue and add the proper URLs to fetch them. wdyt?

**Comment by siddarthkay** [comment]
Hi @ulisesmac Thank you! 
yes I'll use this issue to track and log my progress.

**Comment by J-Son89** [comment]
@ulisesmac, @siddarthkay is this issue needed still?

**Comment by siddarthkay** [comment]
Hi @J-Son89 : yep lets keep this one open till work gets merged into develop

**Comment by ulisesmac** [comment]
Yes! I'll take it again. I'm working on it :+1:
