### ISSUE TITLE
Composer: keyboard should be closed automatically when start scrolling

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16328]
# Bug Report
Follow-up on design call from 19/06/23.

## Problem 
Currently, if the user starts scrolling with opened keyboard, it remains open.

#### Expected behavior
The keyboard is collapsed when the user starts scrolling

https://github.com/status-im/status-mobile/assets/4557972/bd63b403-9b27-4038-bbc9-7115ff8954d9

#### Actual behavior
- keyboard is not closed; 
- causes an additional issue on IOS:

https://github.com/status-im/status-mobile/assets/4557972/5726f434-79e3-47fe-8e4b-e5e5a338e167

### Reproduction

1) Open Status
2) Set cursor to chat input
3) Start scrolling

### Additional Information

- Status version: nightly 20/06/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vkjr** [comment]
@churik 
>Expected behavior
>The keyboard is collapsed when the user starts typing

Did you mean "starts scrolling"?

**Comment by churik** [comment]
@vkjr yes! thank you.
