### ISSUE TITLE
Notification Centre - add Empty Content screen

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16334]
Implement the Notification Centre empty screen designs as shown here:

https://www.figma.com/file/NAdciBFYSBXmr9wpT47jY1/Illustrations?type=design&node-id=0-1&t=78KNpMmafQHyj9DF-0

This is similar to these issues/prs and should use the same solution:
https://github.com/status-im/status-mobile/issues/16078

https://github.com/status-im/status-mobile/issues/16077

**Comment by mmilad75** [comment]
Please assign it to me

**Comment by J-Son89** [comment]
Great stuff @mmilad75, I talked with the Copy team and the text will be slightly different on each tab:
Here is the full list.
```
"All" tab: "No unread notifications."
"Admin" tab: "No unread admin notifications."
"Mentions" tab: "No unread mention notifications."
"Replies" tab: "No unread reply notifications to your messages."
"Contact requests" tab: "No contact requests notifications"
"Identity verification" tab: "No identity verification requests"
"Transactions" tab: "No transaction notifications"
"Membership" tab: "No membership notifications"
"System" tab: "No system notifications
```
The image will stay the same.
