### ISSUE TITLE
Discussion: UX in profile

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1633]
### User Story

As a user I would like the profile editing behavior to be more consistent

#### Expected behavior

There should not be such a big difference in terms of actions between editing from the drawer and editing from the `edit-my-profile` view.

#### Actual behavior

- touching `status` in `my-profile` view opens `edit-my-profile` view while touching `icon` and `name` does not
- pressing `enter` in the drawer while editing `status` saves it and stops editing while pressing `enter` in the `edit-my-profile` view adds a newline that is deleted when adding another char or selecting the name field or image.
- going through the `edit-my-profile` screen requires at least 3 taps from the drawer to start editing + confirmation by pressing the save button while editing from the drawer directly requires one tap and saves immediately when losing focus
- saving in the `edit-my-profile` view just saves and doesn't go back to `my-profile` view

**Comment by yenda** [comment]
Also not sure if it is about UX but when:

- you are in `my-profile` view 
- edit the profile (`edit-my-profile` view)
- save it and go back to `my-profile` view
- repeat the two previous step n times

you end up having to press back 2*n times to go back to the menu

**Comment by asemiankevich** [comment]
Also, when I have new profile created:
1. Go to edit profile - change picture - change name to Wallet - tab back
Actual: changed picture is not saved while the name is reverted to default (which is expected)

2. When i set username as "wallet" or "console" those usernames are not in red

**Comment by sla-shi** [comment]
We can revisit this when we start Profile redesign.

**Comment by chadyj** [comment]
UX in profile has been redone. Closing.
