### ISSUE TITLE
fresh install of nix fails with user `Permission denied` error

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#16344]
# Bug Report

This is the error i see locally when running `make run-clojure` on latest `develop`

```log
rewriting symlink /nix/store/j47rlpa4cwbl8pksya91c9cwybm6gddr-yarn2nix-1.0.0/bin/.yarn2nix-wrapped to be relative to /nix/store/j47rlpa4cwbl8pksya91c9cwybm6gddr-yarn2nix-1.0.0
distPhase
yarn pack v1.22.19
success Wrote tarball to "/nix/store/j47rlpa4cwbl8pksya91c9cwybm6gddr-yarn2nix-1.0.0/tarballs/yarn2nix-1.0.0.tgz".
✨  Done in 0.10s.
building '/nix/store/psmqz8kw0kpx9wk09sn5fzc955jvd0fh-yarn.nix.drv'...
error: creating directory '/nix/var/nix/gcroots/per-user/siddarthkumar': Permission denied
make: *** [run-clojure] Error 1
❯ mkdir /nix/var/nix/gcroots/per-user/siddarthkumar
mkdir: /nix/var/nix/gcroots/per-user/siddarthkumar: Permission denied
```

**Comment by jakubgs** [comment]
If this error happens to you the simplest way to fix it is use this:
```sh
sudo mkdir "/nix/var/nix/profiles/per-user/${USER}" "/nix/var/nix/gcroots/per-user/${USER}"
sudo chown "${USER}" "/nix/var/nix/profiles/per-user/${USER}" "/nix/var/nix/gcroots/per-user/${USER}"
```
But that's just a temporary hack-fix.

**Comment by smohamedjavid** [comment]
I used the temporary hack-fix. Every time I run any `make ...` commands I get this error but the actual process (building clojurescript, running Metro server,...etc) working after error.
```
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

**Comment by jakubgs** [comment]
I could not find any issues or discussions about this so I've opened one myself:
https://discourse.nixos.org/t/upgraded-to-nix-2-14-1-and-profiles-are-not-being-created/29455

**Comment by jakubgs** [comment]
@smohamedjavid that's an issue that has already been solved:

* https://github.com/status-im/status-mobile/issues/16342
* https://github.com/status-im/status-mobile/pull/16343

**Comment by jakubgs** [comment]
I was wondering if this is solved in version newer than `2.14.1` so i tested `2.15.1` but the same thing happens:
```
jakubgs@ubuntuvm:~/status-mobile$ make shell
Configuring Nix shell for target 'default'...
warning: ignoring untrusted substituter 'https://nix-cache.status.im/', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
error: creating directory '/nix/var/nix/gcroots/per-user/jakubgs': Permission denied
```
I have also tested `2.16.1`, and it has the same issue.

**Comment by jakubgs** [comment]
But I cannot find that issue in `2.14.3`:
```
jakubgs@ubuntuvm:~/status-mobile$ nix-shell
these 302 paths will be fetched (986.03 MiB download, 2458.25 MiB unpacked):
  /nix/store/01im8ar99bn67b3n2pp8gys2q33h2l2b-libassuan-2.5.5
  /nix/store/01s8q14nr73n2hz3ha5cdjswqfpyb3rw-perl5.36.0-HTTP-Message-6.26
  /nix/store/0am1assv4ykpg22dmf587jbvlyx7c4na-perl5.36.0-libnet-3.12
  /nix/store/0c2j8gnalpjplhjn60aczgg33pyv2g87-perl5.36.0-HTTP-Negotiate-6.01
...
```
We could downgrade, but I'd rather just fix this in the setup script.

**Comment by jakubgs** [comment]
I've created an issue to get to the bottom of this:

* https://github.com/NixOS/nix/issues/8564

But I have already implemented a fix.

**Comment by jakubgs** [comment]
But I have also identified that this error:
```
error:
       \u2026 while calling the 'import' builtin

         at \u00abstring\u00bb:1:2:

            1| (import <nixpkgs> {}).bashInteractive
             |  ^

       \u2026 while calling the 'findFile' builtin

         at \u00abstring\u00bb:1:9:

            1| (import <nixpkgs> {}).bashInteractive
             |         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at \u00abnone\u00bb:0: (source not available)
```
Does not happen on `2.15.1`, but it does on `2.14.1`. So I will make an upgrade PR to `2.15.1`

**Comment by jakubgs** [comment]
Based on a comment from my Discourse thread it appears `2.16` is supposed to have this fixed:
https://discourse.nixos.org/t/upgraded-to-nix-2-14-1-and-profiles-are-not-being-created/29455/3?u=jakubgs

So I have installed `2.16.1` and tested this:
```
jakubgs@ubuntuvm:~/status-mobile % nix-instantiate --attr shells.default --add-root /nix/var/nix/gcroots/per-user/${USER}/status-mobile/shells.default default.nix
error: creating directory '/nix/var/nix/gcroots/per-user/jakubgs': Permission denied

jakubgs@ubuntuvm:~/status-mobile % nix-instantiate --version
nix-instantiate (Nix) 2.16.1
```
And it doesn't appear to fix the `Permission denied` error.

**Comment by jakubgs** [comment]
I've decided to change my PR to just downgrade from `2.14.1` to `2.13.4` which has no such issue.
Possibly there will be a fix for this in future releases based on my issue:

* https://github.com/NixOS/nix/issues/8564
