### ISSUE TITLE
Emoji keyboard is not hidden when tapping inside the chat [iOS only]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1634]
### Description

*Type*: Bug

*Summary*: on iOS, when I type something in chat and open emoji keyboard it is not hidden automatically like normal keyboard does.

#### Expected behavior
Emoji keyboard is hidden when user taps inside the chat to see the messages

#### Actual behavior
Emoji keyboard is not hidden

### Reproduction

- Open Status
- Go to 1x1 chat
- Open emoji keyboard (tap on emoji icon on the right side of the input field)
- Tap inside the chat

### Additional Information

* Status version: 0.9.9d138 (1234.333)

* Operating System: iOS 10.3.3
* TF from 4.50 https://app.testfairy.com/projects/4803590-status/builds/6979667/sessions/1/?accessToken=xf5vpC2uJrTFmzygeJVY40r0Vfc

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x57b440e5e243353341636dd3f29e571f1fefa1c5](https://etherscan.io/address/0x57b440e5e243353341636dd3f29e571f1fefa1c5)
Network: Mainnet
Paid to: acmcc
