### ISSUE TITLE
Deal with longer names in messages

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#16345]
# Bug Report

It's illustrated on the screenshot below — in this particular case the name should be truncated to fit one line of text but the problem with that is there is some extra text, and that text shouldn't be truncated, only the name itself.
So it should be something like `alwx ww... pinned a message`, and that text should fit the entire width available.

<img width="564" alt="Screenshot 2023-06-21 at 16 30 27" src="https://github.com/status-im/status-mobile/assets/911127/98e33890-cd9d-4079-a821-d82cb00ba627">

The previous solution (before this PR: https://github.com/status-im/status-mobile/pull/16188) was to always truncate manually (`(utils/truncate-str pinned-by 18)`) but that solution is terrible because the screens are different, and localizations are different as well.
It seems like there is no good solution to this problem out-of-box: you can add `flex: 1` to the author name but in this case it won't really work good with short names, and there will always be some spacing. What I'm thinking of is some function to measure the space available but I'm not sure that it's worth it because it will take quite some time to write something like that.

Please note that the solution should work not only for pinned messages but also for deleted messages (and all other types in `quo2.components.messages.system-message`)

### Reproduction

1) Open Status
2) Create/restore an account with long name
3) Observe the truncation of the name in messages

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
If I'm not mistaken we can acheive this using flexbox properties. I have updated the pinned message variation here: #17078.

Variation| Before | After
-|-|-
Short name | ![Simulator Screenshot - iPhone 11 Pro - 2023-08-22 at 12 34 26](https://github.com/status-im/status-mobile/assets/19279756/237bae21-bdff-42bd-a055-e5a718d22019) | ![Simulator Screenshot - iPhone 11 Pro - 2023-08-22 at 12 36 00](https://github.com/status-im/status-mobile/assets/19279756/8090a6d6-b555-401b-b374-4def56dfdbcb)
Long name | ![Simulator Screenshot - iPhone 11 Pro - 2023-08-22 at 12 35 03](https://github.com/status-im/status-mobile/assets/19279756/16dd45fc-7df9-4ada-8955-bd3e90a6e8fe) | ![Simulator Screenshot - iPhone 11 Pro - 2023-08-22 at 12 36 41](https://github.com/status-im/status-mobile/assets/19279756/0c55257c-2715-4ef3-bad3-81ab6b6e65eb)

@alwx I couldn't find a system messages component variant in Figma that accommodates long names within a single line, where we'd need to truncate the name. It might be a good idea to consult the design team before proceeding further with this issue. Have you already checked with the design team about this?

cc: @flexsurfer

**Comment by ajayesivan** [comment]
The name should be truncated. Confirmed with Pedro(https://discord.com/channels/624634427930312714/928625369542713396/1146390410118311971)
