### ISSUE TITLE
Communities are not fetched in Discover community screen until app re-opening

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16346]
originally reported in https://github.com/status-im/status-mobile/pull/16232

**Steps:** 

1. Create a new user
2. Open Discover community screen
3. See if communities are displayed in Featured and All sections

**Actual result:** Featured and All sections are empty. Communities are fetched only after app re-opening

https://github.com/status-im/status-mobile/assets/97245802/442ad3d6-cbb5-41e5-a876-6d8a7554811b

**Expected result:** 

Data should be fetched without need of app re-opening

Skeleton should be displayed until communities are loaded (see design below). 

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=12510-427273&t=TyfKww2h28KiCitk-0 

 <img alt="Communities for Mobile – Figma 2023-06-21 10-57-55" width="279" src="https://user-images.githubusercontent.com/97245802/247475514-9d5748dc-727d-4259-a6dd-99a76e844950.png">

Also see comment from @John-44 originally posted [here](url)

> @erikseppanen @pavloburykh Note that the app should start trying to fetch the featured community as soon as the app has launched, not when the user visits this screen. And this information should then be cached. And if the latest fetch of this data hasn't been completed, the previously cached data should be displayed instead.

> So with this scheme, other than literally the first time the user logs into the app, the user should never see the skeleton loading screen (because there will always be data stored locally to be displayed)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
I think the best way to do this is to implement the refresh in status-go, that will periodically pull the refreshed data, and it will signal the client with the new communities.
