### ISSUE TITLE
make test error on macos

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#16356]
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory '/Users/andrey/Dev/status-react/build'
  CXX(target) Release/obj.target/status_nodejs_addon/modules/react-native-status/nodejs/status.o
../modules/react-native-status/nodejs/status.cpp:1169:11: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
          func->Call(isolate->GetCurrentContext(), v8::Null(isolate), argc, argv);
          ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  SOLINK_MODULE(target) Release/status_nodejs_addon.node
ld: framework not found IOKit
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [status_nodejs_addon.target.mk:175: Release/status_nodejs_addon.node] Error 1
make[1]: Leaving directory '/Users/andrey/Dev/status-react/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nix/store/4d4sar5gv82d7wn96lq1ddxq3vxfh7h1-nodejs-18.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.5.0
gyp ERR! command "/nix/store/4d4sar5gv82d7wn96lq1ddxq3vxfh7h1-nodejs-18.16.0/bin/node" "/nix/store/4d4sar5gv82d7wn96lq1ddxq3vxfh7h1-nodejs-18.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrey/Dev/status-react
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
error Command failed with exit code 1.
```

**Comment by yakimant** [comment]
Confirm the issue on macOS and it's relation to #14944.

Probably we need to add `darwin.apple_sdk.frameworks` to `clojure` shell.
Don't know, how it ran before, as `gyp` requires the following:
https://github.com/status-im/status-mobile/blob/d300e880627c1333c1258c6ab27c1d259143f727/binding.gyp#L18-L25

`make test` also runs Software Install every time.

**Comment by yakimant** [comment]
Adding `darwin.apple_sdk.frameworks` helps, will make a PR.

**Comment by yakimant** [comment]
"The “gcc” command requires the command line developer tools. Would you like to install the tools now?”" still show up on every run.

**Comment by yakimant** [comment]
`gcc` issue comes from `yarn install`, `gyp` `dtrace-provider`:
```
gcc -O2 -Wall -arch i386   -c -o usdt.o usdt.c
gcc: error: Failed to determine realpath of '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk' (errno=No such file or directory)
gcc: error: sh -c '/Applications/Xcode-14.3.1.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -find gcc 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
xcode-select: Failed to locate 'gcc', requesting installation of command line developer tools.
```

It looks for `MacOSX10.15.sdk`, but I have `MacOSX13.3.sdk` and `MacOSX13.sdk` linking to `MacOSX.sdk`

This problem doesn't fail the `dtrace-provider` build though:
```
make[1]: Entering directory '/Users/status/work/status-mobile/node_modules/dtrace-provider/build'
  ACTION binding_gyp_ndtp_target_build_ndtp .
-----------------------------------------------------------------
Building dtrace-provider failed with exit code 2, falling back
on stub implementation.

Re-run install with V set in your environment to see the build
output, or NODE_DTRACE_PROVIDER_REQUIRE=hard to force an
installation failure.
```
Is it a problem for us?

**Comment by jakubgs** [comment]
I wonder if this `dtrace-provicer` which is pulled in by `detox` which is used by the `run-visual-test-ios` target:
https://github.com/status-im/status-mobile/blob/7260c23e8eed3683823683975d832d844fd9ba21/Makefile#L347-L352

I wonder if this is still being used for anything, or if it's part of the old app.

**Comment by jakubgs** [comment]
Not sure if related but I found this: https://developer.apple.com/forums/thread/716814

Which suggests this might be related to env variables. But your find of the patch for NodeJS in `nixpkgs` might be the reason.

**Comment by yakimant** [comment]
Maybe we should enforce `dtrace-provider` in the future if needed:
https://github.com/chrisa/node-dtrace-provider#troubleshooting-build-issues

**Comment by yakimant** [comment]
Checked before the upgrade - `dtrace-provider` was failing too, but with different error:
```
  CXX(target) Release/obj.target/clojure/dtrace_provider.o
../dtrace_provider.cc:35:13: error: no matching member function for call to 'Set'
    target->Set(Nan::New<String>(\"DTraceProvider\").ToLocalChecked(), Nan::GetFunction(t).ToLocalChecked());
    ~~~~~~~~^~~
/Users/status/Library/Caches/node-gyp/18.9.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/status/Library/Caches/node-gyp/18.9.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../dtrace_provider.cc:94:10: error: no matching member function for call to 'Set'
    obj->Set(Nan::To<v8::String>(info[0]).ToLocalChecked(), pd);
    ~~~~~^~~
/Users/status/Library/Caches/node-gyp/18.9.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/status/Library/Caches/node-gyp/18.9.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
```
Maybe related: https://github.com/chrisa/node-dtrace-provider/issues/132

**Comment by yakimant** [comment]
@erikseppanen, @J-Son89, can we remove dependency to `detox` temporary?
Looks like visual tests added in https://github.com/status-im/status-mobile/pull/14329 are not running and `dtrace-provider`, `detox` dependency has build issues.

**Comment by J-Son89** [comment]
@yakimant - no problem. that work to add visual tests has been delayed due to some CI complications. Let me know if you need any help removing this. 👍

**Comment by yakimant** [comment]
Removing patch
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/nodejs/bypass-darwin-xcrun-node16.patch
from `nodejs` helped with `Failed to locate 'gcc'` issue.

This `nixpkgs` PR introduced the issue: https://github.com/NixOS/nixpkgs/pull/193759

**Comment by yakimant** [comment]
Removing `detox` for now: https://github.com/status-im/status-mobile/pull/16372

Please take into account `NODE_DTRACE_PROVIDER_REQUIRE` option, when returning it back.

**Comment by yakimant** [comment]
Created an issue for `nixpkgs` to fix the patch causing `node-gyp` issues on macOS: https://github.com/NixOS/nixpkgs/issues/239371

**Comment by yakimant** [comment]
#16359 is merged. @flexsurfer, please close if this issue is fixed.
