### ISSUE TITLE
Replace QR reader with input field for e2e builds

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16393]
# Bug Report

## Problem 
When access to camera was granted, the previously input field was shown (**only on e2e builds**)
Currently QR reader is shown, which is not convenient for automation corresponding feature.

#### Expected behavior
Input field for QR code value + OK/Cancel (can be as ugly as you want :), the only requirement is tappable)
**Only on e2e builds**

(video with 1.20.3 build)

https://github.com/status-im/status-mobile/assets/4557972/ae79155d-5d05-48b0-88cf-f6fe8e57f55a

#### Actual behavior
![image](https://github.com/status-im/status-mobile/assets/4557972/6701e312-617f-4544-b9dc-1cc61767cf3c)

### Reproduction

1) Open Status
2) Go sigin in by syncing > enable camera

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
@churik : I'll take a look at this today and try to unblock E2E asap.

**Comment by churik** [comment]
Thank you @siddarthkay !
It is blocker for new e2e (the whole set of flows)
