### ISSUE TITLE
Send / Receive in Chat Test

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#164]
Must ensure we can send and receive chat messages over Whisper

##### test_one_to_one_chat

Steps:
1. Set passwords for 2 users from scratch (user_1, user_2)
2. Go to profile and get public key as user_1
3. As user_2 add user_1 using public key
4. Send message to user_1 as user_2
* **verify:** user_1 received message from user_2 on Chats view
6. Open one-to-one chat with user_2 as user_1
7. Send second message to user_1 as user_2
* **verify:** user_1 received second messages from user_2 on one-to-one chat view

**Comment by antdanchenko** [comment]
test_one_to_one_chat added
