### ISSUE TITLE
issues with nix purge script

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#16404]
# Bug Report

## Problem 

The purge script `make nix-purge` often fails with 

```log
Are you sure you want to purge Nix?
[y/n]: y
Detected multi-user Nix installation.
/Library/LaunchDaemons/org.nixos.darwin-store.plist: Could not find specified service
Unload failed: 113: Could not find specified service
make: *** [nix-purge] Error 3
```

and other times it fails with 

```log
Detected multi-user Nix installation.
Started APFS operation
Deleting APFS Volume from its APFS Container
Unmounting disk3s7
The volume "Nix Store" on disk3s7 couldn't be unmounted because it is in use by process 0 (kernel)
Error: -69888: Couldn't unmount disk
```

as reported by @flexsurfer on macOS rosetta terminal. 

It would be better if the make command for nix purge can handle these errors and allow us to re-run the purge command without doing `/nix/scripts/purge.sh --force`...

**Comment by flexsurfer** [comment]
i want to point out that i tried to run `make nix-purge` in non rosetta terminal, dunno if its related
