### ISSUE TITLE
"Changing onViewableItemsChanged error on the fly is not supported" error shown when tapping on a mention within an opened image

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16401]
Follow up for https://github.com/status-im/status-mobile/pull/16176
### Steps:
1. Send image with the mention
2. Open the image
3. Tap the mention

### Actual result:
When tapping on a mention within the opened image, an error message is displayed: "Changing onViewableItemsChanged error on the fly is not supported".

https://github.com/status-im/status-mobile/assets/52490791/6aaff7f4-2a5f-42f4-a979-34b6fc47c376

### Expected result:
The mention navigates the user to the appropriate profile

### logs:
[Status.log](https://github.com/status-im/status-mobile/files/11867610/Status.log)
https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

**Comment by churik** [comment]
The description should be deleted from messages with images for now https://github.com/status-im/status-mobile/issues/16137

I'm not sure why it got back again

**Comment by ibrkhalil** [comment]
Disabling the updated one now.
