### ISSUE TITLE
two accounts created in one go

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#16435]
# Bug Report
You should click fast to reproduce this bug. Pls checks the details from video and logs.

#### Expected behavior
Only create 1 account.

#### Actual behavior
2 accounts created.

### Reproduction

1) Open Status 
2) Make sure there is none of account exist yet
3) Create new profile as fast as you can, keep clicking buttons if it's available
4) Logout and check the number of account created

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

https://github.com/status-im/status-mobile/assets/12406719/23c5a995-0674-422d-b96f-cb63a6e252a7

[logs.zip](https://github.com/status-im/status-mobile/files/11901844/logs.zip)

**Comment by flexsurfer** [comment]
i think its more like a general issue, probably we should chill by default any touchable

**Comment by cammellos** [comment]
@flexsurfer are you still looking into this?

**Comment by flexsurfer** [comment]
no switched to another tasks

**Comment by churik** [comment]
Closed as stale,  reopen if still relevant.
