### ISSUE TITLE
Selected accent color is not applied inside newly created account until re-login

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16444]
**Steps:** 

1. Proceed with creating a new user
2. Select some non-default accent color on Profile creation screen
3. Pay attention if selected accent color has been applied inside account

**Actual result:** selected accent color is not applied until re-login

https://github.com/status-im/status-mobile/assets/97245802/b3910156-b931-49e7-87e1-c95b3ddc5b1a

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ulisesmac** [comment]
@flexsurfer 
Just in case you didn't notice, this was the reason why we had two subscriptions for customization color: while onboarding we had the data in a different location in the database than when logging in, so we used:
 `customization-color  (or onboarding-data login-data)`
 
 I noticed you closed the issue related: https://github.com/status-im/status-mobile/issues/16175.
 
 Should we reopen?

**Comment by flexsurfer** [comment]
thanks @ulisesmac i'll take a look
