### ISSUE TITLE
Empty username, avatar and status for default values on Edit Profile screen [Accounts refactoring]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1644]
### Description

*Type*: Bug

*Summary*: Default values for username, avatar and status are not shown on Edit Profile screen. Instead there are hints "Name", "Status" and violet picture. Expected: same values for username, avatar and status as were set be default when account was generated. 

Note: after user sets own avatar, name and status they are shown fine on Edit Profile screen.
![img_2232](https://user-images.githubusercontent.com/6584810/29458037-670218a8-841d-11e7-8d9e-f6f1f0398995.jpg)

#### Expected behavior
for default values: same values for username, avatar and status as were set be default when account was generated. 
#### Actual behavior
hints "Name", "Status" and violet picture.

### Reproduction
https://app.testfairy.com/projects/4803590-status/builds/6381741/sessions/3/?accessToken=MYBZfZ3BR943qpw5g9inoUkizmU
- Open Status
- Create new account
- Open Profile of the account and remember values for username, avatar and status 
- Tap on default avatar to open profile screen
- Tap on 3 dots in top right corner and select Edit
- On screen Edit Profile check values shown for username, avatar and status. Expected to see the same as on Profile 

### Additional Information
* Status version: PR `accounts refactoring` 0.9.11d21 (1557.21) / 0.9.10-21-g09661eb2+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by flexsurfer** [comment]
fixed
