### ISSUE TITLE
Messages containing Giphy/Tenor links are not delivered to receiver

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16457]
Originally reported here https://github.com/status-im/status-mobile/pull/15891#issuecomment-1552899794

Example of giphy link: https://giphy.com/gifs/this-is-fine-QMHoU66sBXqqLqYvGO
Example of tenor link: https://tenor.com/view/wolf-of-wall-street-media-leonardo-di-caprio-tapping-table-happy-gif-17819377

**Steps:** 

1. User A sends given link in chat
2. See if User B received this link

**Actual result:** link is not delivered to User B. Any message containing such link will not be delivered to receiver. 

https://github.com/status-im/status-mobile/assets/97245802/f23bd88d-7cfb-43b4-9628-f261b52972c4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ibrkhalil** [comment]
We need to look into what compression looks like for gifs, Because sending them over the wire is expensive (In MBs), This not high priority at the moment.

**Comment by cammellos** [comment]
Please don't pick this up until, we need to do a spike on gifs compression before (if you want to do this fine, but timebox it please)

**Comment by churik** [comment]
Links are delivered with preview on 2.29, closing the issue
