### ISSUE TITLE
Quo2: implement Dropdown component to it's own spec

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16456]
Currently the dropdown component is using the button under the hood. However the designs are not 1-1.

Implement the dropdown component as it's own component as per the Figma designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=56-5001&mode=design&t=Uvy1ZgKhWn6un1St-4

[Design to best practices: https://github.com/status-im/status-mobile/pull/16454
](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)

Include component spec tests

Create a follow up isse to use this across the codebase and remove the unnecessary api extensions to the button component ->
 blur-active?
 override-before-margins 
override-after-margins icon-size 
icon-container-size
icon-container-rounded?

**Comment by ulisesmac** [comment]
Please take in consideration that the current implementation need some fixes:
-  #16590
