### ISSUE TITLE
Communities - Close button with incorrect background

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16455]
# Bug

The close button **with the light theme** doesn't have the correct background.

### Actual

<img src="https://github.com/status-im/status-mobile/assets/46027/1dad956a-eb27-4c9f-87ee-2ce89c5c30c5" height="300" />

### Expected

<img src="https://github.com/status-im/status-mobile/assets/46027/2167df0c-16ac-4d0c-975d-39203211731b" height="400" />

**Comment by churik** [comment]
I believe can be closed in favour of https://github.com/status-im/status-mobile/issues/17557
