### ISSUE TITLE
"Unknown" instead of username in Remove profile bottom sheet 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16469]
**Steps:** 

1. Create multiaccount
2. Open Profile list screen
3. Open Remove profile bottom sheet
4. See if username is fetched

**Actual result:** username is lost. "Unknown" instead of username is displayed. 

![photo_2023-07-03 13 45 31](https://github.com/status-im/status-mobile/assets/97245802/aa2192dc-0462-4259-abe4-7377e5da511e)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
probable regression from https://github.com/status-im/status-mobile/pull/16176
cc @ibrkhalil

**Comment by ibrkhalil** [comment]
> probable regression from https://github.com/status-im/status-mobile/pull/16176
> 
> cc @ibrkhalil 

Will investigate
