### ISSUE TITLE
Message duplication in composer after using Jump to

### ISSUE THREAD

**Issue by Garrett96** [status-im/status-react#16464]
![Screenshot_20230702_215039](https://github.com/status-im/status-mobile/assets/46694517/a51f8752-c8f9-4ac5-9954-6a013a586cc3)

Occasionally `Jump To` will duplicate the last message sent into the chat bar.

Edit: Can also happen occasionally when switching out of the app entirely and then switching back into it.

- Send a text string message
- Jump To another community or tab
- Jump To back into initial message

**Comment by flexsurfer** [comment]
unfortunately i couldn't replicate it, probably was already fixed

**Comment by flexsurfer** [comment]
is it ios or android or both?

**Comment by Garrett96** [comment]
> is it ios or android or both?

Android w/ nightly build 1.23 from late July

**Comment by flexsurfer** [comment]
is it still in latest nightly for you ?

**Comment by churik** [comment]
Can not reproduce it on [PR](https://github.com/status-im/status-mobile/pull/17113):

https://github.com/status-im/status-mobile/assets/4557972/c6d4ce1f-37e1-47db-a3d8-1369545e52fe

We'll keep eye on it when testing 1.25, so far cannot reproduce with Android13 (google Pixel 7A)
