### ISSUE TITLE
Accent color is not applied to "Jump to" inside chat view and "View profile" buttons when adding a contact

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16477]
# Bug Report

## Problem 
There are more buttons and elements that have no accent color applied yet (to be logged), but these two buttons seem to be pretty visible, so it would be nice to fix them in 1.24.

<img width="315" alt="Screenshot 2023-07-04 at 10 21 03" src="https://github.com/status-im/status-mobile/assets/67952253/cbc84c89-9b64-4f3e-90fb-b228b66d9f41">

https://github.com/status-im/status-mobile/assets/67952253/d8aaa655-552a-470f-a4e4-38ad802028c5

#### Expected behavior
Accent color is applied to the buttons

### Additional Information

- Status version: nightly 4/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
Hey, @cammellos - Have you started working on this?  
I have the fix ready for this Issue.

**Comment by cammellos** [comment]
> Hey, @cammellos - Have you started working on this? I have the fix ready for this Issue.

@smohamedjavid  I was just starting the emulator :) 
If you have the fix I'll assign it to yourself then, thank you
