### ISSUE TITLE
Toasts not displaying for the user if they received 1-2 Contact Requests while not logged in

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16478]
### Steps to reproduce:
1. `User A` logs out.
2. `User B` and `User C` send Contact Requests to `User A`.
3. `User A` logs back in.

### Actual result:
`User A` does not see any toasts anywhere, including when deleting a message, receiving a new Contact Request, joining a community, etc.

### Expected result:
Toasts should be displayed for `User A`

### Dev:
- Nightly [4 Jul 2023]

**Comment by churik** [comment]
@VolodLytvynenko is this issue still relevant?

**Comment by VolodLytvynenko** [comment]
@churik issue is not valid anymore
