### ISSUE TITLE
Chatkey is displayed as "zQ3sht...<3 last chars>" instead of "zQ3...<6 last chars>" in the chats after a message is sent

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16479]
### Steps to reproduce:
1. Send a message in any chat.
2. Check the chatkey displayed in the chat.

### Actual result:
The chatkey is shown as "zQ3sht...<3 last chatkey chars>" instead of "zQ3...<6 last chars>" in the chats.
![image](https://github.com/status-im/status-mobile/assets/52490791/58d514b4-f160-4f5d-9907-297e61cffc32)

### Expected result:
The chatkey should be displayed as "zQ3...<6 last chatkey chars>" in the chats after a message is sent

### Nightly [4 Jul 2023]

**Comment by cammellos** [comment]
@siddarthkay is working on the same issue https://github.com/status-im/status-mobile/issues/16047

**Comment by VolodLytvynenko** [comment]
> @siddarthkay is working on the same issue #16047

Got it. Thanx
Closed as duplicate of https://github.com/status-im/status-mobile/issues/16047
