### ISSUE TITLE
Incorrect display of sections in top navigation when scrolling chats

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16499]
### Steps to reproduce:
1. Create such amount of community chats or 1-1 chats to have the ability to scroll them.

### Actual result:
- When chats are scrolled on the community home page and hidden under the top navigation, the "Discover" section is shown on the current top navigation.
- When chats are scrolled on the chats page and hidden under the top navigation, the "Invite friends to Status" section is shown on the current top navigation.

![image](https://github.com/status-im/status-mobile/assets/52490791/d292dd2c-9a3e-4261-a5e8-290226e9f066)

https://github.com/status-im/status-mobile/assets/52490791/f81d4abb-696b-4918-8a17-4d69c489e5f8

### Expected result:
- When chats are scrolled and hidden under the 'top nav', then 'discover' section should not be shown on the 'top nav'
- When chats are scrolled on chats page and hidden under the 'top nav', then the 'invite friends to status' section should not be shown on the current 'top nav'

![image](https://github.com/status-im/status-mobile/assets/52490791/ee6a1664-7b6e-4c7b-a7e1-24325dcccd7e)

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=4996-221009&mode=design&t=fMfIfJ3qH6JFZetO-0

### ENV: 
Nightly [5 Jul 2023]

**Comment by ulisesmac** [comment]
Duplicate of https://github.com/status-im/status-mobile/issues/16446

**Comment by VolodLytvynenko** [comment]
Close it as dublicate
