### ISSUE TITLE
Group Chat Test

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#165]
We need to test user paths for adding a user to a group chat, removing, testing broadcasts on both (ie not sending message to person removed from contact) from different view points.

##### test_group_chat_send_receive_messages_and_remove_user

Steps:
1. Set passwords for 2 users from scratch (user_1, user_2)
2. Go to profile and get public key as user_1
3. As user_2 add user_1 using public key
4. Go back to chats view as user_2 and create group chat with user_1
5. Send first message to user_1 as user_2
**verify:** user_1 received first messages from user_2 on Chats view
6. Open group chat with user_2 as user_1
7. Send second message to user_1 as user_2
**verify:** user_1 received second messages from user_2 on group chat view
8. As user_2 remove user_1 from group chat
9. As user_2 send third message to group chat
**verify:** user_1 received message 'user_2 removed you from group chat' Chats view
**verify:** user_1  didn't receive third message from user_2 on Chats view

**Comment by antdanchenko** [comment]
test_group_chat - added
test_group_chat_remove_user - in progress

**Comment by antdanchenko** [comment]
'test_group_chat' and 'test_group_chat_remove_user' squashed into single 'test_group_chat_send_receive_messages_and_remove_user' in order to save execution time
