### ISSUE TITLE
Implement transaction progress component

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#16525]
# Feature Issue

Add the transaction progress component to Quo2.0 Preview area.
The Quo2.0 Preview area can be found by visiting Profile, ref screenshot : 

<img width="377" alt="Screenshot 2023-07-08 at 11 31 57 AM" src="https://github.com/status-im/status-mobile/assets/64726664/cdc2c9a7-dcef-4422-8e85-36f8bed6c1e9">

The designs for this component are here : https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22699-214190&mode=design&t=lo60mCKqnVfMaM1g-0 

Should be implemented according to best practices
https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Include component spec tests
https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md

Communicate with design team before starting to make sure there is no unknown requirements and to understand the interactions.

You can use mock data for the preview.

The component should be added in the `wallet` group in the Quo2.0 preview screen (scroll to the very bottom to find it)

**Comment by teoarjun** [comment]
checking this
