### ISSUE TITLE
Validation error is missing on login using invalid password. User gets stucked on login screen. 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16546]
**Steps:** 

1. Try to login using invalid password 
2. Observe the result

**Actual result:** no validation error. User gets stucked on login screen.

https://github.com/status-im/status-mobile/assets/97245802/dd3cc395-d613-4fdc-84bf-4dc43bd25e9d

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Probable regression from: https://github.com/status-im/status-mobile/pull/16507
https://github.com/status-im/status-go/pull/3722
@cammellos Please can you take a look

**Comment by Parveshdhull** [comment]
`node.login` signal is not received in case of wrong password
