### ISSUE TITLE
"Mute channel" doesn't work in the channel context menu

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16543]
# Bug Report

## Problem 

You can only mute a channel from the long-press menu on the community screen (channel list), but if you open the channel, open the context menu, and try to mute it from there, it won't work.

https://github.com/status-im/status-mobile/assets/67952253/c90d9c1a-5dd8-4b41-adf5-180dfb82a810

#### Expected behavior
Can mute the channel from both the long-press menu and the menu inside the channel

#### Actual behavior
`Mute channel` inside the channel doesn't work

### Reproduction

1. Open community
2. Open channel
3. Tap `...` at the top right 
4. Mute the channel
5. Check if it worked 

### Additional Information

- Status version: nightly 10/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
cc @ibrkhalil

**Comment by ibrkhalil** [comment]
Will pick it up today, Thanks @qoqobolo!
