### ISSUE TITLE
"Object is not a function" error in longtap on image send from Desktop client

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16547]
**Preconditions:** Desktop user and Mobile user are in the same chat/community. Before reproduction make sure you are using latest available Desktop [master](https://ci.infra.status.im/job/status-desktop/job/master/) build 

**Steps:** 

1. Desktop user sends image in chat/community channel
2. Mobile user longtaps on image
3. Observe error on mobile client

**Actual result:** "Object is not a function" error appears. Besides that, opened image is cropped. 

[Status-debug-logs (39).zip](https://github.com/status-im/status-mobile/files/12003120/Status-debug-logs.39.zip)
![photo_2023-07-10 17 33 53](https://github.com/status-im/status-mobile/assets/97245802/2ab6bcdf-74e6-49b7-856c-d53157d7c6b3)
![photo_2023-07-10 17 33 58](https://github.com/status-im/status-mobile/assets/97245802/9a643842-8ba6-4dd3-8e37-f3a4c5d46f8f)

https://github.com/status-im/status-mobile/assets/97245802/612729a6-a80f-4e8f-adc3-6bc519b10106

### Additional Information

- Desktop version: master (08 Jul 2023)
- Status version: nightly (10 Jul 2023)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Image cropped issue: https://github.com/status-im/status-mobile/issues/16048

**Comment by OmarBasem** [comment]
The image cropped issue is because the desktop client is not sending the image dimensions. I have opened an issue there https://github.com/status-im/status-desktop/issues/11510

**Comment by Parveshdhull** [comment]
Issue already logged on desktop side https://github.com/status-im/status-desktop/issues/10944

**Comment by Parveshdhull** [comment]
btw, cropping issue fixed in https://github.com/status-im/status-mobile/pull/16571
