### ISSUE TITLE
Jump To: white circle around online status dot

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#16552]
# Problem

When opening the Jump To there's a white margin around the online green dot next to the user profile picture.
This only seems to happen on Android.

## Screen

![IMG_0041](https://github.com/status-im/status-mobile/assets/122543089/bcacbffb-9a19-42c4-893f-c7d6ce112a5e)

**Comment by cammellos** [comment]
This might be address by https://github.com/status-im/status-mobile/issues/16552 , we should check after to make sure

**Comment by cammellos** [comment]
Assigning @yqrashawn for now, let me know if this is not addressed in your PR
