### ISSUE TITLE
The online status and device type (mobile/laptop) indicators are not shown after syncing

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16550]
### Steps:
1. `User_A` generates the QR code
2. `User_B` Scans a valid QR code
3. `User_B` Wait until 'device sync complete' screen opens

### Actual result:
- Mobile indicator is not shown. Only the laptop indicator icon is shown for all types of devices
- Online status is not shown

### Expected result:
- The mobile indicator should be shown for mobile devices.
- The online status of the synced device should be displayed if the current device is online
![image](https://github.com/status-im/status-mobile/assets/52490791/cdded980-1705-40f4-b300-55b7fa8c3f56)
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-177600&mode=design&t=jHlvwVEapic9srwS-0

### ENV:
[10 Jul 2023]

**Comment by Samyoul** [comment]
This data should already be available, see https://github.com/status-im/status-go/issues/3351

**Comment by cammellos** [comment]
We don't currently have a feature for online indicator, so that's outside the scope for MVP. Only the device type should be fixed.

**Comment by mohsen-ghafouri** [comment]
* [X] The mobile indicator should be shown for mobile devices.
* [ ] The online status of the synced device should be displayed if the current device is online

@cammellos I'm uncertain whether I should close this issue, as the online status indicator is still unresolved.

**Comment by cammellos** [comment]
@mohsen-ghafouri I think we can close it, this will be post MVP, so we can track separately, I also doubt this feature is worth the cost of implementation
