### ISSUE TITLE
Long  "Log Out " occurs when the app remains in the background for an extended period

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16557]
### Steps to reproduce:
1. Login
2. Go to any chat -> send a few messages with images
3. Put the app in the background for an extended period (In my case I took at least 15 minutes).
4. Bring the app back from the background.
5. Log out

### Actual result:
After the app remains in the background for a long time, there is a significant delay when attempting to log out. The log out process takes longer than expected.

https://github.com/status-im/status-mobile/assets/52490791/8e3a019f-28db-4151-a063-f54d90d69bf6

### Expected result:
The log-out process should be prompt and not significantly delayed

### Devices:
Real device: Pixel 7a, Android 13
Real device: iPhone 11 Pro max. IOS 16

### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/12006403/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12006404/geth.log)

### ENV:
Nightly: 11 Jul 2023

**Comment by churik** [comment]
Log out in general is slowed down significantly, and can last 2-4 seconds at least

**Comment by cammellos** [comment]
Logout logs extracted from above, showing 15s of activity after initial logout
[Uploading logout.log…]()

**Comment by cammellos** [comment]
Shutdown task that is taking long is:

`transp.ResetFilters`, so it has to do with the newly enabled filter protocol, investigating

**Comment by cammellos** [comment]
The reason is that unsubscribing from filters is synchronous, we notify each peer and wait for a response, it's a nice thing to do I guess, but probably we want to make an option to be fire and forget in these cases, looking into it

**Comment by cammellos** [comment]
Trying out https://github.com/status-im/status-go/pull/3751 that shorten the shutdown task to 1 second

**Comment by churik** [comment]
Still the case, especially visible after long long time in the background (in particular case > 30 sec)

https://github.com/status-im/status-mobile/assets/4557972/3b0787d6-b1c9-4e82-b73b-7a1f12d4589b
[logs.zip](https://github.com/status-im/status-mobile/files/12051409/logs.zip)
