### ISSUE TITLE
community avatar initials should not be rendered with user-avatar

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#16568]
![image](https://github.com/status-im/status-mobile/assets/15090582/c038a59f-9302-4c86-b97f-b80cc15b55ae)

https://github.com/status-im/status-mobile/pull/16193#issuecomment-1594466429

some community avatars are rendered using user-avatar
the one in the screenshot is a context-tag, and context-tag is using user-avatar to render initials https://github.com/status-im/status-mobile/blob/4a8764c790c7034e9b23ee5e3f08ba620617d516/src/quo2/components/tags/context_tag/view.cljs#L54

#16193 tmp fix this by keeping initials logic in user-avatar (customization color community avatar is not working here)

now that user avatar images/initials are come from status-go
we need to avoid using user-avatar component to render community avatar

better create a separate community avatar component similar to channel avatar and remove initials logic from user-avatar

**Comment by yqrashawn** [comment]
note: future community should all have user defined avatar so this issue might be out of scope

**Comment by ulisesmac** [comment]
@ilmotta The jump-to feature has been removed, is this issue still valid?

**Comment by ilmotta** [comment]
Sure @ulisesmac, this issue can be closed. Thanks for spotting that.

<img src="https://github.com/user-attachments/assets/bb7c95d5-f3c9-4b43-9a0c-b04549da9cc9" width="400">
