### ISSUE TITLE
Create all missing context tag variants 

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#16577]
# Problem

The application lacks of all the variants of the Context Tag component:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1336-34320&mode=dev

We need to create them and make sure the current uses of them are using the correct variant.

## Implementation

Feel free to change or extend the current implementation if needed.

## Acceptance Criteria

- All variants are implemented
- They are being properly used in the app
 - Component tests and aligned with best practices (API matching figma names and `with-theme` wrapper)

**Comment by J-Son89** [comment]
@ulisesmac can you update this acceptance criteria to include - component tests and aligned with best practices ->
e.g it has to be using `with-theme` HOC, in it's own view and style component and the external api should be matching figma etc 👍

**Comment by Parveshdhull** [comment]
Do we need fallback implementation? https://github.com/status-im/status-mobile/issues/14857

**Comment by ulisesmac** [comment]
@J-Son89 Sure, done.

@Parveshdhull oh yes, I will ask designers and update this issue!. Thanks for noticing.

**Comment by J-Son89** [comment]
There is a recent comment from @pedro-et on this component, can whoever takes this ensure it's addressed/correct now? - https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv?node-id=1336:34320&mode=design#500917262

**Comment by ulisesmac** [comment]
> There is a recent comment from @pedro-et on this component, can whoever takes this ensure it's addressed/correct now? - https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv?node-id=1336:34320&mode=design#500917262

Not all the variants are implemented atm, so I will take that comment into account while solving this issue. Thanks Jaime!

**Comment by ulisesmac** [comment]
> Do we need fallback implementation? #14857

I have checked the component @Parveshdhull 
and the circles with images are actually uses of the user-avatar component, so the fallback is the same as the user avatar (Initials)
