### ISSUE TITLE
Text and image icons for sliding not shown when image is opened in landscape mode

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16585]
### Steps to reproduce:
1. Navigate to any chat.
2. Send image with the text
3. Tap on an image to open it
4. Rotate the device to landscape mode.
5. Expand the text

### Actual result:
When the image is opened in landscape mode, the accompanying text and slide preview images are not shown.

https://github.com/status-im/status-mobile/assets/52490791/a9164f42-ae0b-4b20-8fed-f3047fef4460

### Expected result:
When the image is opened in landscape mode, the text and slide preview images should be displayed
![image](https://github.com/status-im/status-mobile/assets/52490791/6ef5a556-1235-44d3-acac-8592e60cce43)

](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6322-404640&mode=design&t=E0GY9QjHc63xWKFk-0)

**Comment by OmarBasem** [comment]
Hi @alwx, letting you know that landscape is post MVP. For now, you would only need to prevent image rotating when text is expanded. FYI, on Android landscape is disabled due to a bug in RNN.

**Comment by alwx** [comment]
Hm @OmarBasem should we then move it out of 1.25.0 milestone?

**Comment by OmarBasem** [comment]
@alwx yes, I think we should. I will create a PR to disable landscape when text is expanded

**Comment by ilmotta** [comment]
I'm closing this issue for now because this seems to be a fairly benign problem for our users since we can safely assume most images are sent without accompanying text and users can always rotate back to portrait to read. As @OmarBasem said, we don't officially support landscape mode.
