### ISSUE TITLE
Missing black and white customization colors

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#16584]
# Issue Design Review

Black and White option for customization color is missing in the color picker.

## Figma frame

Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3374%3A287003&mode=design&t=m9Qi17ZeHywUiJB1-1)

## Screenshot

<img width="290" alt="Screenshot 2023-07-13 alle 11 55 10" src="https://github.com/status-im/status-mobile/assets/122543089/ec62cd2f-821a-4434-bf15-286ec770a88d">

**Comment by churik** [comment]
linking https://github.com/status-im/status-mobile/issues/15442
