### ISSUE TITLE
Unable to swipe through composer link previews in case of multiple links message

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16599]
**Steps:** 

1. Paste message containing multiple links into composer
2. Wait until link previews are fetched
3. Try to swipe through link previews
4. Observe the result

**Actual result:** Unable to swipe through link previews

https://github.com/status-im/status-mobile/assets/97245802/6af7cb22-3d0b-4ff1-a7a0-004ffced72e9

**Expected result:** user is able to swipe through link previews

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Unassigning as I couldn't reproduce locally

**Comment by pavloburykh** [comment]
> Unassigning as I couldn't reproduce locally

@ibrkhalil  so in your case swiping of multiple previews is working fine? Could you please share a video of how it works locally? Thank you!

**Comment by ibrkhalil** [comment]
Blocked by https://github.com/status-im/status-mobile/issues/16457

**Comment by ibrkhalil** [comment]
It works after a few tries, So I can confirm this is an issue.
Sorry for the misunderstanding, Investigating.

**Comment by ibrkhalil** [comment]
https://github.com/status-im/status-mobile/assets/33176106/49eabfb6-5272-4c94-a2b0-6a0639340ba4


So I get that it has some issues with having to try multiple times to get it, Because it conflicts with composer's gesture.
What should we do in this case?

**Comment by FFFra** [comment]
I'm also trying to reproduce this.

**Comment by pavloburykh** [comment]
> So I get that it has some issues with having to try multiple times to get it

I am not able to swipe no matter how many times I'm trying.

**Comment by ilmotta** [comment]
I remember fixing this issue during development, before releasing the first version of the link previews. I'm not surprised this bug exists tbh, but I think something changed in the composer that caused brought this bug to surface.

**Comment by ilmotta** [comment]
I will take a look at this one.
