### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#16590]
# Issue Design Review

The dropdown component needs some design fixes:

- left icon is too small
- spacing between text and right icon doesn't match design
- missing a circle around the right icon (dropdown arrow)
- size doesn't match design even though they should be 40px

## Figma frame

Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3374%3A311523&mode=design&t=UAAEFaABoJ5a0AvU-1)

## Screenshot

<img width="349" alt="Screenshot 2023-07-13 alle 14 49 57" src="https://github.com/status-im/status-mobile/assets/122543089/0b7dc464-30eb-4f25-8d6b-56895a42e443">

**Comment by smohamedjavid** [comment]
completed on #17412
