### ISSUE TITLE
If user deletes group chat then no new messages sent there are shown to the user

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1659]
### Description

*Type*: Bug

*Summary*: User A deleted group chat X from Chats. User didn't leave the chat. After another group member sent new message to group chat X there is new empty chat with random name shown for user A. 
Issues:
1. this new chat does not contains any messages. No messages are shown even after other members are sending messages to the chat.
2. it's not clear that this is group chat: if tap on the avatar then options Profile/search chat/Notifications and sounds are shown as it's 1-1 chat. For group chat there would be Members/Settings/etc...
3. this new chat has only @browse command (no location, send, request commands are shown)
4. after user A re-launches the app this new chat is no longer shown
So, user A deletes group chat and has no option to get it again, as no new messages sent to the group chat are shown to this user.

Expected: because user A didn't leave the group chat 
1 this group chat should be shown again in the Chats after user B sends new message to this group chat.
2. after user A launches the app, group chat X is shown in the Chats (if any new messages were sent after user A deleted the chat)

#### Expected behavior
user A deletes group chat than user B send new message to the group chat. As a result, user A should get same group chat shown in Chats with only new message from user B.

#### Actual behavior
1. this new chat does not contains any messages. No messages are shown even after other members are sending messages to the chat.
2. it's not clear that this is group chat: if tap on the avatar then options Profile/search chat/Notifications and sounds are shown as it's 1-1 chat. For group chat there would be Members/Settings/etc...
3. this new chat has only @browse command (no location, send, request commands are shown)
4. after user A re-launches the app this new chat is no longer shown

### Reproduction

As user B:
- add user A as a contact
- create group chat X with user A
- send text message to user A in the group chat X

As user A:
- check that you see new group chat X with message from B
- delete group chat X in Chats: tap on 3 dots in top right corner, select Edit, tap on 3 dots next to group chat X and select Delete chat
- check all chats you have now in Chats (because issue will be with extra empty chat created)

As user B:
- after user A deleted group chat X: send new text message to the group chat X

As user A:
- after user B sent new text message check that there is extra empty chat in Chats created with random 3 words name
- Open empty chat, check its commands

- As user B send 2-3 more messages to group chat X
- As user A: check that empty chat has no messages, check that no other new group chats are created/shown

As user A: 
- close app
- open app and sign in
- check that empty chat is no longer shown

### Additional Information
* Status version: released 0.9.10 and develop 0.9.10-22-g92f3f9a4+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by lukaszfryc** [comment]
I've retested it on 0.9.12 (TestFlight) on iPhone 6, iOS 11.2.1. After removing a group chat and sending a new message by another group member I didn't get the empty chat you mentioned. The group chat is not available either.

**Comment by annadanchenko** [comment]
can't reproduce after new-protocol. After user B sends new message: user A sees same chat with proper name and content and can send commands/messages into it
