### ISSUE TITLE
Keycard component

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#16596]
# Issue Design Review

The keycard component (under Keycard in the Quo2 Component Library) doesn't match keycard proportions.
Also, testing the preview I can't seem to be able to change the name of the keycard owner.

## Figma frame

Here's the [Figma Frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3407%3A392484&mode=design&t=UAAEFaABoJ5a0AvU-1)

## Screenshot

<img width="642" alt="Screenshot 2023-07-13 alle 17 04 16" src="https://github.com/status-im/status-mobile/assets/122543089/f612aa3f-43ea-46db-a4ff-99507d1118e8">

**Comment by churik** [comment]
Closing as re-doing new designs in keycard
