### ISSUE TITLE
Navigating to chat via the 'Jump to' button breaks composer

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16595]
# Bug Report

## Problem 

The composer and keyboard stop opening on Android, and the composer expands off the screen on iOS, if you open the chat using the chat card in `Shell` (via the `Jump to` button).

### Reproduction

1. Open any chat (1-1/channel/..)
2. Hit `Jump to`
3. Press the chat card on the `Jump to` screen
4. Try to set focus to the input field

**iOS**

https://github.com/status-im/status-mobile/assets/67952253/f78c8ec2-124c-4900-ad4e-5c5ab35c8379

**Android**

https://github.com/status-im/status-mobile/assets/67952253/e7cf72e3-1a67-4b54-a690-d108a0fd890d

### Additional Information

- Status version: nightly 13/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
regression from https://github.com/status-im/status-mobile/pull/16239
