### ISSUE TITLE
Implement Quo2 Wallet / Wallet Activity component #16605

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16609]
Implement this component in the quo2 component library as per the design spec:

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22126-200537&mode=design&t=knWWPvlLzZv4fMJ8-4

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Note
Please align with design team before starting this

**Comment by J-Son89** [comment]
marking as blocked as issues with Context tag should be fixed first: 
https://github.com/status-im/status-mobile/issues/16577

**Comment by vkjr** [comment]
Looks like context tags are [almost here](https://github.com/status-im/status-mobile/pull/16962), so will take this one.
