### ISSUE TITLE
Implement Quo2 Avatar /Wallet Avatar component 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16608]
Implement this component in the quo2 component library as per the design spec:

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=114-7648&mode=design&t=1zcF1YaNy9YuVezt-4

**Acceptance Criteria:**

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

**Note**
Please align with design team before starting this

**Comment by OmarBasem** [comment]
@J-Son89 isn't this already implemented?

**Comment by J-Son89** [comment]
@OmarBasem it looks like it's in place but I suspect the designs have somewhat adjusted since then. This story should be then to ensure it's correct and also use best practices etc because that component was implemented months ago and could do with a refactor even if the designs etc are correct 👍 

see: https://github.com/status-im/status-mobile/blob/develop/src/quo2/components/avatars/wallet_user_avatar.cljs

Also the components method of getting first name and last name is not how we have the user name in the app, it should probably handle that in the component similar to other avatars
