### ISSUE TITLE
Composer overlaps status bar if > 4 links are pasted into it

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16600]
Originally reported [here](https://github.com/status-im/status-mobile/pull/15891#issuecomment-1552900157)

Still reproducible on latest nightly (Jul 13, 2023)

**Steps:** 

1. Open chat
2. Paste more than 4 links into composer, for example
```
https://github.com/status-im/status-mobile/pull/15253

https://m.youtube.com/watch?v=Je7yErjEVt4

https://www.youtube.com/watch?v=OYjZK_6i37M&pp=ygUIZ29kc21hY2s%3D

https://youtu.be/Mp0jlNquSnM

https://bit.ly/41ScFYY

https://youtu.be/Beb8cktBTxY
```
3. Observe how expanded composer looks like

**Actual result:** expanded composer overlaps status bar

**iPhone X:**

https://github.com/status-im/status-mobile/assets/97245802/9cd0b95f-8bb7-4a8c-b825-af72de0acb1e

**Samsung Galaxy A52:**

https://github.com/status-im/status-mobile/assets/97245802/32aac206-df05-4d9b-ac00-73e77710f463

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ibrkhalil** [comment]
What's the expected behavior?

**Comment by pavloburykh** [comment]
> What's the expected behavior?

@ibrkhalil  Composer should not overlap status bar. As you see on the above video - composer is expanded beyond the screen. 
Here is like fully expanded composer should look like. 

![photo_2023-07-20 11 35 22](https://github.com/status-im/status-mobile/assets/97245802/ca3cd4dc-64f4-4bed-9757-827884ba377b)

**Comment by flexsurfer** [comment]
unable to replicate on ios

**Comment by pavloburykh** [comment]
> unable to replicate on ios

@flexsurfer try pasting data below for reproduction

```
Resolved preview 
Bsbd
Sbdb
HShs
ShshS

https://github.com/status-im/status-mobile/pull/15253

https://m.youtube.com/watch?v=Je7yErjEVt4

https://www.youtube.com/watch?v=OYjZK_6i37M&pp=ygUIZ29kc21hY2s%3D

https://youtu.be/Mp0jlNquSnM

https://bit.ly/41ScFYY

https://youtu.be/Beb8cktBTxY
```

**Comment by flexsurfer** [comment]
@pavloburykh still all good

<img width="373" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/ddf789e6-b6c2-487e-9bef-2be75c669d85">

**Comment by pavloburykh** [comment]
> @pavloburykh still all good
> 
> <img alt="image" width="373" src="https://user-images.githubusercontent.com/11790366/262340943-ddf789e6-b6c2-487e-9bef-2be75c669d85.png">

Here is what I observe on my iPhone X IOS 16.6
@VolodLytvynenko is also reproducing it on his iPhone 11 Pro Max
@qoqobolo is reproducing on her iPhone SE 

@flexsurfer what iPhone model and IOS version are you using for replication? 

https://github.com/status-im/status-mobile/assets/97245802/f8b8aa57-f498-45fa-8cb1-4ac562ab7c49

**Comment by flexsurfer** [comment]
<img width="112" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/7b4c05b2-1fae-47a6-bdb7-2e84d8e75308">
but i found a few different bugs, for example if i remove preview, i can't scroll to the bottom of the input

**Comment by pavloburykh** [comment]
> <img alt="image" width="112" src="https://user-images.githubusercontent.com/11790366/262343979-7b4c05b2-1fae-47a6-bdb7-2e84d8e75308.png"> but i found a few different bugs, for example if i remove preview, i can't scroll to the bottom of the input

cannot replicate it. Could you please show with the video? maybe I am miss-understanding it.

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/assets/11790366/694487f0-4a39-43b6-b325-c6110b8014d7

**Comment by pavloburykh** [comment]
> Screen.Recording.2023-08-22.at.14.33.19.mov

thanx @flexsurfer! Reproduced this one, will log a separate issue for that.

**Comment by pavloburykh** [comment]
> unable to replicate on ios

What about Android? Also unable to replicate? Cause this issue is reproducible on both platforms for me.

**Comment by flexsurfer** [comment]
on ios it somehow randomly appears to me, but if i edit the message it fixes itself
<img width="380" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/a672973a-c5c0-4d94-872d-98907988e765">

**Comment by pavloburykh** [comment]
> on ios it somehow randomly appears to me, but if i edit the message it fixes itself 

Yes, it is fixed by itself after interacting with composer. But still, the bug exists.

**Comment by cammellos** [comment]
seems low priority, what do you think @pavloburykh ?

**Comment by pavloburykh** [comment]
> seems low priority, what do you think @pavloburykh ?

agree. Besides that we have a similar issue when adding an image into composer https://github.com/status-im/status-mobile/issues/17842. I have added it to 1.27 milestone.

**Comment by churik** [comment]
Not reproducible anymore on nightly 21/06/24 (IPhone 14, Google Pixel7)
