### ISSUE TITLE
System messages with keys are shown in 1-1 chat when accepting CR

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16629]
# Bug Report

## Problem 
Sender: 
![IMAGE 2023-07-14 12:05:36](https://github.com/status-im/status-mobile/assets/4557972/f1ae87f7-c2eb-49da-8eea-8c9990eab8de)

Receiver:
![IMAGE 2023-07-14 12:06:29](https://github.com/status-im/status-mobile/assets/4557972/751b77ae-8ba1-4746-ba48-3f2e278dfcf0)

#### Expected behavior
no messages with public keys are shown

### Reproduction

1) Open Status
2) Send CR
3) Accept CR

### Additional Information

- Status version: RC 1 (1.24) 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @churik, Is hiding system message with key will work for the release?

**Comment by churik** [comment]
Absolutely
