### ISSUE TITLE
Implement vector icons

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1662]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Implement vector icons using font and fontello.

vector icons is better because we can change size and color in the code, easy to add, less size

**Comment by flexsurfer** [comment]
font icons don't work well ,we decided to implement svg icons

**Comment by asemiankevich** [comment]
Tested, new icons look good 
Android: 0.9.10-37-g0e3648b5+
iOS: 0.9.11d37-1557.37
