### ISSUE TITLE
Add descriptions for Dapps to improve usability

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1664]
### Description

*Type*: Feature

*Summary*: According to https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/837?status=New issue logged in Instabug

#### Expected behavior
It would be nice to see a summary of what each DApp does, wether it be text under the name of each DApp or an icon beside each which can be tapped for more info. Right now it takes a few minutes of navigating the browser to find out what they even do

**Comment by andmironov** [comment]
we should consider adding Dapp description and some more Dapp-specific data to Profile

**Comment by asemiankevich** [comment]
@denis-sharypin any thoughts on this? Current develop does not have dapps descriptions 
![image](https://user-images.githubusercontent.com/28752642/37598126-69b2ca30-2b92-11e8-90fc-ed84ca17cf99.png)

**Comment by denis-sharypin** [comment]
@goranjovic  Do you remember we had them in the previous version of Discovery? Where those descriptions now?

**Comment by lukaszfryc** [comment]
This is for sure needed for curated list of dapps we select for beta release https://github.com/status-im/ideas/issues/88

**Comment by rachelhamlin** [comment]
@lukaszfryc I can provide descriptions once we have our list ready.

**Comment by lukaszfryc** [comment]
OK, I'll assign you to this issue. Btw, let's link this issue to DApp Experience https://github.com/status-im/ideas/pull/122 when it's merged.

**Comment by denis-sharypin** [comment]
@rachelhamlin  we already have a long list of the dapps in the dev builds. Maybe we could already prepare descriptions for them?

**Comment by rachelhamlin** [comment]
@denis-sharypin was wondering why I didn't see the updated list in Status. Does it match the "Status Beta" tab on this sheet? https://docs.google.com/spreadsheets/d/1cPjVu5AizyGgz6J4PJwK62LQfB8LHTnPmAdJvyBqQLE/edit#gid=492008138

<blockquote><div><strong><a href="https://docs.google.com/spreadsheets/d/1cPjVu5AizyGgz6J4PJwK62LQfB8LHTnPmAdJvyBqQLE/edit#gid=492008138">Google Sheets - create and edit spreadsheets online, for free.</a></strong></div><div>Create a new spreadsheet and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Sheets to edit Excel files. Free from Google.</div></blockquote>

**Comment by lukaszfryc** [comment]
@rachelhamlin the PR https://github.com/status-im/status-react/pull/3772 has not been merged yet so it's not in the nightly build.

Here is the build with the dapp list:
iOS: https://i.diawi.com/p5DJWc
Android: https://i.diawi.com/Ma76Dj

<blockquote><div><strong><a href="https://i.diawi.com/p5DJWc">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/Ma76Dj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
