### ISSUE TITLE
Wallet main screen UI discrepancies

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1666]
### Description

*Type*: Bug

*Summary*: Below is the list of issues related to Wallet main screen applicable both for Android and iOS build. All checks were performed against Zeplin screens

https://app.zeplin.io/project/58aac7ae739bb1a592705d34/screen/598b3dbc46cf770e56724800
https://app.zeplin.io/project/58aac7d018d4584d91998e79/screen/5987fd0a9560ffae5b4a3684

#### Actual behavior

- Wallet screen is "jumping" when swiping forward and reverse https://app.testfairy.com/projects/4803622-status/builds/6409307/sessions/4/?accessToken=krT5F9VZS-Tz0S-k2-/CwaRFP9s)
- Wrong icons used for SNT/ETH/GNO assets. **Assets icons will be available in separate PR in the following days**
- Send / Request / Exchange should be uppercase **for Android** **is fixed in develop**
- Add Asset button is missing
- Wrong wallet icon on the Wallet tab: **Wallet tab icon is fixed in develop**

![screenshot_1](https://user-images.githubusercontent.com/28752642/29563920-5a7ba47c-8748-11e7-8b4d-5f43feaa55b5.png)

**Comment by asemiankevich** [comment]
@jeluard I can reproduce the jumping screen when sliding on iOS: https://app.testfairy.com/projects/4803590-status/builds/6490971/sessions/8/?accessToken=W/WsJw5/5bNKt3RjooH1TrZqo0Y (from 1:15)

**Comment by jeluard** [comment]
Fixed in develop
