### ISSUE TITLE
Update quo2.foundations.colors functions to be contextually themeable

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#16669]
# Problem

Functions `quo2.foundations.colors/theme-alpha` and `quo2.foundations.colors/custom-color-by-theme` are not *contextually themeable*, which means they rely exclusively on the global state `quo2.theme/theme-state`.

This means these functions can't be used with the React context `quo2.theme/theme-context`, which is our current approach to make Quo truly themeable.

## Implementation

Given our goal is to make the Quo library fully themeable, we should update such functions and their usages to accept a `theme` argument.

You may prefer to open more than one PR to solve this issue because there may be too many function calls to update.

**Comment by J-Son89** [comment]
@ilmotta is this still needed? :)

**Comment by ilmotta** [comment]
Thanks for asking @J-Son89. The function `theme-alpha` still exists, it's the last one with this issue's problem, and it has only 2 usages. It still doesn't accept a theme as argument, so it exclusively uses the global Reagent `theme` atom.

I think we can probably get rid of it and use `colors/alpha` directly, as some other namespaces do.

**Comment by J-Son89** [comment]
sure I can do 👍

**Comment by ilmotta** [comment]
I'm closing the issue because it's solved already.
