### ISSUE TITLE
Error (red screen) on update account name

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1668]
### User Story

As a user I want to update my account name

### Description

*Type*: Bug

#### Expected behavior
The name is updated, no errors shown.

#### Actual behavior
The error is shown. Name isn't updated.

### Reproduction
Open Status
Log in
Open profile panel and choose Edit (name)
Type in new name
Tap Submit

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
latest develop 8ac1535dab2f7a4b3bf5bbf42171c078e68c14ac
* Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by jeluard** [comment]
Fixed in develop
