### ISSUE TITLE
Optimized counter increment logic for 1-1 chat messages

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16696]
See the original feature description provided by @John-44 in this conversation (see point B) https://discord.com/channels/624634427930312714/928646594314784859/1129407293256122429

Currently, in a 1-1 chat, each message sent increments the counter, regardless of the proximity of the messages in time. To enhance the user experience we should implement an optimized logic for the counter incrementation.

The suggested behavior is as follows: When a 1-1 chat message is sent, the counter will be incremented by 1. However, if another message is sent within 2 minutes of the previous message, the counter will not be incremented, and the 2-minute window will reset. Only when no further messages are received within the subsequent 2 minutes after the most recent message, the counter will increment again upon sending a subsequent message.

By implementing this logic, the counter will accurately reflect the number of distinct messaging events rather than incrementing for each individual message sent within a short time frame. This optimization will provide a more meaningful representation of chat activity while avoiding unnecessary counter increments and reducing visual clutter.

**Comment by pavloburykh** [comment]
@alwx hello. I am re-opening the issue as counters are not working as expected. 


**Little bit of context:** 

We have tested new counters logic in this PR https://github.com/status-im/status-mobile/pull/17442 that includes correspondent go changes (https://github.com/status-im/status-go/pull/3889 and https://github.com/status-im/status-go/pull/4035) which have been recently merged into develop without any testing. 

Status mobile PR https://github.com/status-im/status-mobile/pull/16850 was closed for some reason. So I guess we still need some changes to be made on mobile side in order feature works properly. 

Please, see the issues below


### ISSUE 1 New increment logic has been applied to communities and groups

According to the feature [description](https://github.com/status-im/status-mobile/issues/16696#issue-1805432840) new logic needs to be applied only for 1-1 chats. 

Currently it is applied to communities and groups as well

**Preconditions:** User A and User B are members of the same group/community

**Steps:** 

1. User A sends couple of messages in a row containing mentions/replies to User B in common community/group
2. By User B see if community/group unread counters = quantity of messages with replies/counters send by User A

**Actual result:** 1 unread counter will be displayed for mentions/replies send in 2 minute window

[Android_message_receiver.zip](https://github.com/status-im/status-mobile/files/12764400/Android_message_receiver.zip)

[IOS_message_sender.zip](https://github.com/status-im/status-mobile/files/12764404/IOS_message_sender.zip)

https://github.com/status-im/status-mobile/assets/97245802/fe11c02a-f803-4db8-a411-fbd80ae09a2a


**Expected result:** we should use old counters logic for communities/groups: display counter for each direct message containing reply/mention


### ISSUE 2 Unread dot is not replaced by unread counter when new reply/mention is received in  communities/groups

**Preconditions:** User A and User B are members of the same group/community

**Steps:** 

1. User A sends regular message in group/community (as a result unread notification dot should appear for User B in group/community)
2. User A mentions/sends reply to User B in group/community
3. See if unread dot is replaced by the unread counter for User B

**Actual result:** unread dot is not replaced by unread counter

**Expected result:** unread dot should be replaced by unread counter


https://github.com/status-im/status-mobile/assets/97245802/88f684cd-0c16-4193-972d-5c5f40f3fca4

**Comment by pavloburykh** [comment]
@alwx you are currently assigned to this issue. In case you do not have capacity to take it into work now please unassign yourself in order other devs can take this ticket. Thank you.

**Comment by alwx** [comment]
@pavloburykh on it

**Comment by churik** [comment]
Closing due to https://github.com/status-im/status-mobile/pull/17476#issuecomment-1746752686

**Comment by alwx** [comment]
@churik closing it because you haven't closed :)

**Comment by pavloburykh** [comment]
> @churik closing it because you haven't closed :)

@alwx hello! Is there a followup PR that reverts counter logic in status go?
