### ISSUE TITLE
UI  is freezing if quickly open reply with image from activity center and try to open image

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16706]
# Bug Report

## Problem 
UI freezing has been observed in certain flows, and while we have identified one reliable method to reproduce the issue, it is likely to affect other areas as well.

#### Expected behavior
no freeze;
the app gets back to normal after reopening

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/087c404b-8b8c-4950-b1df-160ac6752c80

### Reproduction
**Prerequisites:** user A (android) and user B are members of the same community

1) User A: send message to the community 
2) User B: reply to user A with an image
3) User A: open the activity center and quickly tap on the image
4) User A: continue to work with an app > navigate back, open community, etc

### Additional Information

- Status version: nightly 
- Operating System: Android
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12071744/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Just to add to the quorum, I faced this weird issue numerous times during development. At one point I could even systematically reproduce it while hot reloading a certain part of the app, but unfortunately I thought this problem didn't happen in release builds so I never bothered to report 🤷🏼
