### ISSUE TITLE
Research chart libraries that may suit our needs for our wallet implementation

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16705]
# Problem

For our new wallet implementation, we will need a chart library.

## Implementation

Research available React Native chart libraries that may suit our needs

## Acceptance Criteria

- Select the best suitable library for implementing required charts 
- Implement an example integration in our quo2 library

**Comment by smohamedjavid** [comment]
We need to confirm the expectations of the chart with the design team as we deal with rendering the trading data (or similar to it).

In my experience with rendering a chart, I faced an issue displaying the [0 x-axis](https://github.com/indiespirit/react-native-chart-kit/issues/541) line irrespective of the data using the `react-native-chart-kit` library. Like these, the design team must list the expectations of chart behaviour, which will help us choose a good chart library.

**Comment by briansztamfater** [comment]
We are using [our own fork of `react-native-gifted-charts`](https://github.com/status-im/react-native-gifted-charts/) and used this library to implement #16739 #16956. Closing this issue as those implementations are approved by design team and seem to fulfill our needs. Will reopen in case we need to revisit this decision.
