### ISSUE TITLE
Unread counter wrong backgoung color on community chats

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#16718]
# Bug Report
Community chats unreact counter badge seems to have a very light version of the blue background color. Reproducible only on android

#### Expected behavior
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=5040%3A188714&mode=design&t=thINoDvjW1LlxNlE-1

#### Actual behavior
<img src="https://github.com/status-im/status-mobile/assets/28704507/95f8a2fe-47a7-4a73-823a-fe76c7a235fe" height="350">

### Reproduction

1) Open Status
2) User A and B join the same community
3) User A sends message in the general channel
4) User B replies the User A message
5) Check unread counter badge on User A device
6) Notice the background color is different from the expected

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
Can whoever implements this update the counter-badge to use the same approach as the button here:

cc @ilmotta - https://github.com/status-im/status-mobile/blob/8c5e6c082d9ff567fa17ceacb6366f674798f3ac/src/quo2/components/buttons/button/view.cljs#L83-L87

**Comment by jo-mut** [comment]
@J-Son89 this does seem to be a bug actually. Its my mistake. I realized the counter inherits the community color for the background-color.

I will close this issue
