### ISSUE TITLE
Implement Quo2 Wallet/ Token Overview

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16725]
Implement this component in the quo2 component library as per the design spec:

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22065-198302&mode=design&t=Y3eE3KsOE35InEBp-4

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

**Comment by ibrkhalil** [comment]
Unassigning as this component is a part of a page and will be done post mvp.

**Comment by J-Son89** [comment]
> Unassigning as this component is a part of a page and will be done post mvp.

Thanks @ibrkhalil - we can add a label as blocked for now so :)

**Comment by briansztamfater** [comment]
@J-Son89 if this component is for Post-MVP, can we remove the `E:Mobile Wallet Foundations MVP` label from this issue?

**Comment by J-Son89** [comment]
Yep definitely! 🙌🏼

**Comment by Rende11** [comment]
I would like to implement it
