### ISSUE TITLE
Implement Quo2 Tags/Network Tags component

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16727]
Implement this component in the quo2 component library as per the design spec:

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22566-204870&mode=design&t=Y3eE3KsOE35InEBp-4

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Note
Please align with design team before starting this

**Comment by andresceballosm** [comment]
@J-Son89
