### ISSUE TITLE
Quo2 Wallet: Keypair component

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16759]
Implement this component in the quo2 component library as per the design spec.

Reuse Quo2 components wherever applicable.

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=24100-241846&mode=design&t=Yui6CQ6Hh2CplG7a-0

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Note
Please align with design team before starting this

**Comment by J-Son89** [comment]
@OmarBasem perhaps blocked is too strong so feel free to remove - but this seems to also need this component first:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=26013-281545&mode=design&t=rKOPIIPZcrOCIReH-4

I'll create an issue for this now unless it already exists?

**Comment by OmarBasem** [comment]
@J-Son89 alright, thanks for spotting this 👍
