### ISSUE TITLE
Quo2 Wallet: Network Routing component

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16755]
Implement this component in the quo2 component library as per the design spec.

Reuse Quo2 components wherever applicable.

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22655-205318&mode=design&t=Yui6CQ6Hh2CplG7a-0

Example where this component is used:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1041-251649&mode=design&t=iUkJ5M70MZN12BUE-4

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Note
Please align with design team before starting this

**Comment by briansztamfater** [comment]
Added a link to a Figma design where this component is used as it adds more context on how the user should interact with it.

**Comment by siddarthkay** [comment]
Assigning to self so that no one considers this issue available (we may need this for a candidate)

**Comment by DawidBisewski** [comment]
@pedro-et 
I need the access with the Figma system.
dawid.bisewski1110@gmail.com

**Comment by briansztamfater** [comment]
Video reference:

https://github.com/status-im/status-mobile/assets/18485527/95ec1984-dbbd-4bd2-9a00-4179eb71ee15

**Comment by ulisesmac** [comment]
Is someone working on this issue?
Is it ready to be taken?

**Comment by briansztamfater** [comment]
> Is someone working on this issue? Is it ready to be taken?

@ulisesmac It is ready to be taken, seems no assignment yet

**Comment by siddarthkay** [comment]
This was earlier reserved for a candidate but is now free for the taking @ulisesmac

**Comment by briansztamfater** [comment]
Any progress on this one @ulisesmac?

**Comment by ulisesmac** [comment]
> Any progress on this one @ulisesmac?

I'm working on this one right now. The animations and the behavior are a bit hard to implement properly, I hope to get a PR for next Monday or Tuesday 👍
