### ISSUE TITLE
Quo2 Wallet: Transaction Summary component

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16757]
Implement this component in the quo2 component library as per the design spec.

Reuse Quo2 components wherever applicable.

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22673-234515&mode=design&t=Yui6CQ6Hh2CplG7a-0

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Note
Please align with design team before starting this

**Comment by smohamedjavid** [comment]
Depends on https://github.com/status-im/status-mobile/issues/16577 for Context Tag Type(s) - Account, Network, and Token.

**Comment by vkjr** [comment]
Taking this, since context tags are almost [here](https://github.com/status-im/status-mobile/pull/16962) and there is very similar implementation of [wallet activity component](https://github.com/status-im/status-mobile/pull/17104), also waiting for context tags merging.
