### ISSUE TITLE
[IOS] Small delay happens after the 'maybe later' button is tapped on Enable biometric screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16774]
### Steps:
1. Start onboarding
2. Tap the 'maybe later' button on Enable biometric screen

### Actual result: 
After tapping the 'Maybe Later' button on the Enable Biometric screen, a small delay of 1-2 seconds occurs before the next page is displayed.

https://github.com/status-im/status-mobile/assets/52490791/4207368e-57ba-48a1-9b6d-1b62019579fd

### Expected result:
The next page should be displayed immediately or with a minimal delay after the 'Maybe Later' button is tapped.

### Additional Information
- Status version: nightly [25 Jul 2023]
- Operating System: iOS

**Comment by flexsurfer** [comment]
interesting that this happens only if you press `maby later` right after this screen is opened, if wait and then press it opens instantly

**Comment by flexsurfer** [comment]
mhm now its random, i can't replicate it anymore

**Comment by VolodLytvynenko** [comment]
> mhm now its random, i can't replicate it anymore

Hi. Same for me. I think it can be closed
