### ISSUE TITLE
Unable to edit the phone number from the profile screen

### ISSUE THREAD

**Issue by x-goose-x** [status-im/status-react#1677]
### User Story

As a user, I want to set my phone number from the profile screen.

### Description

*Type*: Bug

*Summary*: The handler for updating phone numbers is currently nonexistent, resulting in an error in dev-mode to that effect.

#### Expected behavior
Keyboard pops to edit the phone number

#### Actual behavior
No registered handler for :my-profile/change-phone number

### Reproduction
- Open Status
- Go to profile
- Click edit on phone number

### Solution
- [ ] Add an appropriate handler for ```change-phone-number```, note this is distinct from ```update-phone-number``` which is triggered by /phone in console.

### Additional Information
* Status version: develop as of 2585a32c7a0a0e2eb0563af50f5bf5ec58b3b2a7
* Operating System: Android

#### Logs
```
...
```

**Comment by annadanchenko** [comment]
Phone feature is removed
