### ISSUE TITLE
[Android] Enable biometrics screen skipping issues

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16773]
Follow up for https://github.com/status-im/status-mobile/pull/16744
### Steps:
1. Don't set up the fingerprint in the device settings.
2. Create an account (now during account creation the Enable biometrics screen is skipped, that is correct)
3. Log out of the current account.
4. Set up the fingerprint in the device settings.
5. Start creating a new account
6. Observe if Enable biometrics screen is shown during new account creation

### Actual result:
During the creation of a new account, the Enable Biometrics screen, which allows users to enable biometric authentication, is skipped when the fingerprint is set in the device settings.

### Expected result:
The Enable Biometrics screen should be shown for all newly created accounts when the fingerprint is set

### Device:
- Real device: Pixel 7a, Android 13

### ENV:
Nightly 25 Jul 2023

CC: @flexsurfer

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: [Android] An error is displayed during the setup process if a new account is created after the fingerprint is removed from the device settings

### Steps:
1. Set up a fingerprint in the device settings (before installing the Status app).
2. Install the Status app.
3. Create an account.
4. Log out of the current account.
5. Disable the fingerprint in the device settings.
6. Start creating a new account.
7. Tap "Enable biometric" verification during onboarding.

### Actual result:
An error is displayed during the setup process if a new account is created when the app is set up and the fingerprint is removed from the settings.

![image](https://github.com/status-im/status-mobile/assets/52490791/99b24544-f95b-47c2-a787-00c8ab32d839)


### Expected result:
The Enable Biometrics screen should be skipped for all newly created accounts when the fingerprint is not set


### Device:
- Real device: Pixel 7a, Android 13

### ENV:
Nightly 25 Jul 2023

**Comment by pavloburykh** [comment]
fixed by https://github.com/status-im/status-mobile/pull/17960
