### ISSUE TITLE
Inherit custom colour for unread notification dots

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16784]
# Bug Report

#### Expected behavior
Custom color applied to:

- tabs inside the activity center
- notifications inside the activity center
- tabs on home screens (e.g. `Contacts`)
- main bottom tabs `Communities`, `Chats`, `Wallet`, `Browser` (currently they inherit the color, but it needs to be checked if the refactoring is needed; see [comment](https://github.com/status-im/status-mobile/issues/16784#issuecomment-1663637196) below)

<img width="314" alt="Screenshot 2023-08-03 at 14 06 53" src="https://github.com/status-im/status-mobile/assets/67952253/277e58b4-a74f-4482-9b8c-0a95e1daa800">
<img width="390" alt="Screenshot 2023-08-03 at 14 07 15" src="https://github.com/status-im/status-mobile/assets/67952253/8d22c1d1-4546-46a1-b85d-c054d76614c7">

**Comment by J-Son89** [comment]
@alwx @qoqobolo - the real fix for this is to update/ensure that the respective design system components are setup correctly.
For example `tabs` & `tab` should be responsilbe for rendering the notification-item and as such the customization-color should be handled within that component as we do in other components.
see designs here: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=57-13215&mode=design&t=HH92WNxCwlio6ADs-4

Let's align a similar approach for the other components and make the refactors in the design system where necessary 👍

**Comment by alwx** [comment]
Doing it for `notification-dot` component which currently don't support custom colors and always has a color of `colors/primary-50`
