### ISSUE TITLE
Messages in synced device can be lost (reproduced on group chats)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16786]
# Bug Report

## Problem 
Currently when taking the synced app back from the background may cause or significant delay or loss of messages on one of the devices.

It is reproducible in group chats (not 100%). I reproduced it a couple of times but then couldn't - messages arrived quickly. 
The initial messages that were lost did not get delivered whatsoever.

#### Expected behavior
messages are coming to both devices

#### Actual behavior
Device B(mobile): received all the PNs, but only part of the messages (>50% were missing)
On the photo it is an example of the part which is missing:
<img width="816" alt="Status Desktop 2023-07-26 16-33-39" src="https://github.com/status-im/status-mobile/assets/4557972/b9a5ca8f-0702-40e2-b7a9-785bda441907">

The video is about real-time messages fetching on synced device (only 14 of 40, re-login didn't help)

https://github.com/status-im/status-mobile/assets/4557972/1cd8f04a-0069-4aa2-ab8e-9a000370fb7c

The state of these messages is "Delivered" on the sender side.

### Reproduction

**Three devices: Device A (desktop) and B(mobile) with synced User1, Device C with User2**'

1. **User2**: start four group chats including User1 
2. **Device B(mobile)**: put the app to background
3. **Device A(desktop)**:  minimize desktop app
4. **User2**: send 10 messages to each chat
5. **Device B(mobile)**: check new messages
6. **Device A(desktop)**: check new messages

### Additional Information

- Status version: nightly 26/07/2023
- Operating System: Android, iOS

Logs from device B(mobile), receiver on synced device:  [logs (53).zip](https://github.com/status-im/status-mobile/files/12173826/logs.53.zip)
Logs from sender:  [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12173836/Status-debug-logs.zip)

An example of bunch of not-received 10 messages is on the screenshot: from 12:43 to 14:28 (Madrid time) in `gr ch1` group chat

**Comment by churik** [comment]
cc @Samyoul

**Comment by churik** [comment]
сс @siphiuel

**Comment by cammellos** [comment]
```
t=2023-07-26T10:48:32+0000 lvl=info msg="publishing message via relay" envelopeHash=0x0eb5907fd438a9939d03ec9cf3bc32fc5d11959ce708cedc1f42d52798cda042
t=2023-07-26T10:48:32+0000 lvl=eror msg="could not send message" envelopeHash=0x0eb5907fd438a9939d03ec9cf3bc32fc5d11959ce708cedc1f42d52798cda042 error="not enough peers to publish"
t=2023-07-26T10:48:32+0000 lvl=info msg="publishing message via relay" envelopeHash=0x610cddb3480606d577c13de8fd4c916120b6af3850177c28034a6a499c2059cd
t=2023-07-26T10:48:32+0000 lvl=eror msg="could not send message" envelopeHash=0x610cddb3480606d577c13de8fd4c916120b6af3850177c28034a6a499c2059cd error="not enough peers to publish"
t=2023-07-26T10:48:32+0000 lvl=info msg="publishing message via relay" envelopeHash=0x3cab4f1283205b60d1ee059821fbcaf0a5857408d62484757f9ae722c240a1b4
t=2023-07-26T10:48:32+0000 lvl=eror msg="could not send message" envelopeHash=0x3cab4f1283205b60d1ee059821fbcaf0a5857408d62484757f9ae722c240a1b4 error="not enough peers to publish"
t=2023-07-26T10:48:32+0000 lvl=info msg="publishing message via relay" envelopeHash=0x901b749782764cc832e3b0175dc22d9f77a682a64005c67f94e6602b8e77c3a2
t=2023-07-26T10:48:32+0000 lvl=eror msg="could not send message" envelopeHash=0x901b749782764cc832e3b0175dc22d9f77a682a64005c67f94e6602b8e77c3a2 error="not enough peers to publish"
t=2023-07-26T10:48:32+0000 lvl=info msg="publishing message via relay" envelopeHash=0x53672fb45f207b472316f40ae92f51c78973db0ee7728f6398032d1a8b16e70d
t=2023-07-26T10:48:32+0000 lvl=eror msg="could not send message" envelopeHash=0x53672fb45f207b472316f40ae92f51c78973db0ee7728f6398032d1a8b16e70d error="not enough peers to publish"
t=2023-07-26T10:48:32+0000 lvl=info msg="publishing message via relay" envelopeHash=0x5d967bed0228c3fd85f9a4c28686624cf2977624af489f69466a1aa03f6c6342
t=2023-07-26T10:48:32+0000 lvl=eror msg="could not send message" envelopeHash=0x5d967bed0228c3fd85f9a4c28686624cf2977624af489f69466a1aa03f6c6342 error="not enough peers to publish"
```

One issue on the logs of receiver, is that is using `relay` to send messages, instead of `lightpush`, that looks like it's not configured correctly. 
It does not have enough peers to publish, so most likely not enough peers to receive messages either.

Investigating further.

**Comment by cammellos** [comment]
overall the receiver seems also to have some network connectivity issues:

```
t=2023-07-26T10:52:53+0000 lvl=warn msg="error bumping delivery tag: no decaying tag registered for topic /waku/2/default-waku/proto"
t=2023-07-26T10:52:53+0000 lvl=info msg="connecting to peer" peerID=16Uiu2HAm9yccg5B2Am6LN3deci22WPf2LEqtW4gkw3GMXvGDiaQM error="failed to dial 16Uiu2HAm9yccg5B2Am6LN3deci22WPf2LEqtW4gkw3GMXvGDiaQM:\n  * [/ip4/178.237.238.71/tcp/43541] dial tcp4 0.0.0.0:63810->178.237.238.71:43541: i/o timeout"
t=2023-07-26T10:52:53+0000 lvl=info msg="connecting to peer" peerID=16Uiu2HAmJH7keH57LHQdVUVmbr5DabjdF2BurvvyNoz2nPKpVYyG error="failed to dial 16Uiu2HAmJH7keH57LHQdVUVmbr5DabjdF2BurvvyNoz2nPKpVYyG:\n  * [/ip4/46.28.206.70/tcp/45945] dial tcp4 0.0.0.0:63810->46.28.206.70:45945: i/o timeout"
t=2023-07-26T10:52:53+0000 lvl=info msg="connecting to peer" peerID=16Uiu2HAm7PXF6hFc1NGMBbj8qBcMYX93kL3WKLdBXVvMdugyjx2H error="failed to dial 16Uiu2HAm7PXF6hFc1NGMBbj8qBcMYX93kL3WKLdBXVvMdugyjx2H:\n  * [/ip4/186.241.215.48/tcp/63008] dial tcp4 0.0.0.0:63810->186.241.215.48:63008: i/o timeout"
t
```

**Comment by cammellos** [comment]
```
WakuV2Config\": {\n        \"Enabled\": true,\n        \"Host\": \"0.0.0.0\",\n        \"Port\": 0,\n        \"KeepAliveInterval\": 0,\n        \"LightClient\": true,\n        \"FullNode\": false,\n        \"DiscoveryLimit\": 20,\n        \"DataDir\": \"\",\n        \"MaxMessageSize\": 0,\n        \"EnableConfirmations\": false,\n        \"CustomNodes\": null,\n        \"PeerExchange\": true,\n        \"Nameserver\": \"8.8.8.8\",\n        \"EnableDiscV5\": true,\n        \"UDPPort\": 0,\n        \"AutoUpdate\": true,\n        \"EnableStore\": false,\n        \"StoreCapacity\": 0,\n        \"StoreSeconds\": 0\n    }
```
Is the configuration it was started, LightClient is true, so should not be using relay?

**Comment by cammellos** [comment]
I see both lines:

`t=2023-07-26T09:19:10+0000 lvl=info msg="publishing message via lightpush" envelopeHash=0x74aca12a9aea0ee9c11e7c4ba41646d738090cbfc77cbb0015beb18d5b9192c2`
and
`t=2023-07-26T10:53:33+0000 lvl=info msg="publishing message via relay" envelopeHash=0x78cbe0d10070b8543c78e50ce86a56a250bae2ec4e6f094372d883ad274b7d2a`

which almost looks like both relay and lightpush are enabled? this is unexpected I think

**Comment by vitvly** [comment]
@cammellos yes i think this is wrong, with LightClient=true relay should be off

**Comment by cammellos** [comment]
```
t=2023-07-25T13:17:21+0000 lvl=eror msg="Marshalling signal envelope" package=status-go/signal error="json: error calling MarshalJSON for type *protocol.MessengerResponse: json: error calling MarshalJSON for type *settings.SyncSettingField: json: error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input"
```
Another suspicious error

**Comment by cammellos** [comment]
There's also a lot of:

```
t=2023-07-26T09:18:27+0000 lvl=eror msg="receiving FilterSubscribeResponse" error=EOF
t=2023-07-26T09:18:27+0000 lvl=info msg="not querying bootnodes" seeded=true peer-count=11
t=2023-07-26T09:18:27+0000 lvl=eror msg="receiving FilterSubscribeResponse" error=EOF
t=2023-07-26T09:18:27+0000 lvl=eror msg="could not unsubscribe from peer" peerID=16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD error=EOF
t=2023-07-26T09:18:28+0000 lvl=eror msg="receiving FilterSubscribeResponse" error=EOF
t=2023-07-26T09:18:28+0000 lvl=info msg="not querying bootnodes" seeded=true peer-count=11
t=2023-07-26T09:18:28+0000 lvl=info msg="received message push" peer=16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e
t=2023-07-26T09:18:28+0000 lvl=eror msg="receiving FilterSubscribeResponse" error=EOF
t=2023-07-26T09:18:28+0000 lvl=eror msg="could not unsubscribe from peer" peerID=16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD error=EOF
```
not sure if that's an issue

**Comment by cammellos** [comment]
Correction above lightpush & relay enabled at the same time, it was an issue with the logs, for some reason node config wasn't printed in the last log session, that made me think that it was the same, but in fact they were two different sessions.

**Comment by ilmotta** [comment]
@cammellos, @vitvly @churik Is this issue still relevant given the last comment is from almost one year ago and many things changed since then?

**Comment by churik** [comment]
we can close it for now and reopen when we have capacity to recheck the pairing, if it is still relevant
