### ISSUE TITLE
Communities are not restored when recovering a user (waku-backup)

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#16787]
# Bug Report

## Problem 
We have an e2e test  [test_restore_multiaccount_with_waku_backup_remove_switch](https://ethstatus.testrail.net/index.php?/tests/view/3201388) that always recovers one certain user and checks that his contacts and communities are restored. As mentioned in https://github.com/status-im/status-mobile/issues/15500 we had an issue with restored contact names. But from yesterday we see that no communities restored at all for this user

#### Expected behavior
All 4 communities are restored from backup

#### Actual behavior
No communities are restored from backup

### Reproduction

1. Having a user is in 4 communities:
    - admin in an open community
    - admin in a community with a restricted access
    - member in an open community
    - member in a community with a restricted access
2. Recover this user
3. Open Communities view

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
[log_recover.txt](https://github.com/status-im/status-mobile/files/12174122/log_recover.txt)

[test_restore_multiaccount_with_waku_backup_remove_switch_geth1.log](https://github.com/status-im/status-mobile/files/12174344/test_restore_multiaccount_with_waku_backup_remove_switch_geth1.log)

**Comment by pavloburykh** [comment]
**UPDATE:** 

Contacts are not restored as well. Tested on nightly August 1, 2023.
