### ISSUE TITLE
Language selection in signing phrase generation

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1679]
### User Story

As a user I want my signing phrase to be generated in a language I'm familiar with and able to memorize it easily (the whole point of a mnemonic phrase)

### Description

*Type*: Feature

For the implementation of this feature we need signing phrase dictionaries for a reasonable number of languages (ideally all).

One complicating factor is that signing phrases are persistent (at least locally on the device) whereas the current system language can be changed at any time externally. Signing phrase will remain in the language that was selected when it was generated, e.g. I get a new phone, it's still in English, I create an account, get a phrase and switch the language to say Spanish. Should we stick to the English passphrase?

**Comment by yenda** [comment]
This will be replaced by the emoji guard
