### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by aj07** [status-im/status-react#1680]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a <user|developer|...>, I want to fix the typo error on the doc page.

### Description

doc page

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- ...
- Step 3, etc.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by annadanchenko** [comment]
Hey @aj07 Please, provide details about the typo (link to the doc and sentence with a typo, typo, expected text) Currently, it's not clear what is to be fixed.

**Comment by annadanchenko** [comment]
closing issue as there is no feedback
