### ISSUE TITLE
No notification in Activity center when replying with image (Desktop <-> Mobile)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16800]
# Bug Report

## Problem 

This issue reproduces in different ways depending on the direction of interaction between clients (mobile<>mobile, desktop<>mobile, etc.). All 4 scenarios and their associated issues will be described below.

**Main case:** UserA receives a reply to their message with an image from UserB. 

### 1. Desktop > Mobile

**Steps to reproduce:**
1. Mobile user and Desktop user: join a community
2. Mobile: send a message in the channel and open the home community screen
3. Desktop: send a reply to the message with an image
4. Mobile: keep an eye on the unread indicator on the community and AC
**Actual result:** no message, no unread indicator on the community, no notification in AC
5. Mobile: send the app to background, reopen the app
6. Mobile: check the notifications
**Actual result:** the number of unread messages is displayed on the community/channel; but still no notification in AC (reopening the app doesn't help)

Also, sometimes Desktop user needs to send another message in order for the reply to be received by Mobile.

**Expected result:** the reply is delivered to the Mobile user without sending another message and sending the app to background; notification in AC is received.

#### Mobile logs

After background
[geth.log](https://github.com/status-im/status-mobile/files/12184708/geth.log)

https://github.com/status-im/status-mobile/assets/67952253/852779b4-36c1-476d-9e50-cfe98416d0ab

### 2. Desktop > Desktop

The steps are the same: Desktop1 sends a reply with an image to Desktop2

**Actual result:** 
- No notification in AC 
- Loading skeleton is shown in the channel until reopening the desktop app (you can’t see any history)

https://github.com/status-im/status-mobile/assets/67952253/85914245-3be0-4587-8b99-b13cbf4ff1cb

### 3. Mobile > Desktop

1. Mobile user sends a reply with an image to Desktop user
2. Desktop users checks AC when the notification is received

**Actual result:** the notification comes to AC, but the image is not displayed there
**Expected behavior:** can see the image in the notification

<img width="1263" alt="Screenshot 2023-07-27 at 11 25 15" src="https://github.com/status-im/status-mobile/assets/67952253/46bc7d6f-d1bc-4115-ad49-79236e4dceb4">

### 4. Mobile (UserA) > Mobile (UserB)

Mobile1 sends a reply with an image to Mobile2

<img width="301" alt="Screenshot 2023-07-27 at 13 58 22" src="https://github.com/status-im/status-mobile/assets/67952253/f1ad2fac-cf8a-4613-bb45-1387bcc8a0fc">

### Additional Information

- Status version: Mobile: nightly 27/07, Desktop: master 26/07 https://ci.infra.status.im/job/status-desktop/job/master/2722/
- Operating System: Android, iOS, macOS Ventura 13.4

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
I'm not sure if this issue was introduced on the mobile or desktop side.
Adding this to the mobile repo, but please let me know if the issue needs to be moved to the desktop one.

cc @jrainville @ilmotta (Icaro, tagging you because Andrea is on vacation, and you were doing a lot of activity center stuff, maybe you have some thoughts about this issue from the mobile perspective)

**Comment by jrainville** [comment]
@qoqobolo It's hard to tell where exactly it's broken. I feel like somehow we don,t use exactly the same API between mobile and desktop, or maybe it's just a different status-go version.

Either way, the Desktop to Desktop scenario is definitely broken, so feel free to open this issue in desktop (can be a copy paste) and I'll take a look

**Comment by qoqobolo** [comment]
> Either way, the Desktop to Desktop scenario is definitely broken, so feel free to open this issue in desktop (can be a copy paste) and I'll take a look

Logged [here](https://github.com/status-im/status-desktop/issues/11695), thank you!

**Comment by ilmotta** [comment]
Thanks for tagging me @qoqobolo. I can work on this issue next week or the one after if nobody picks it up until then. It's also not clear to me the cause of the problem. Let me know if this is too disruptive and I'll deprioritize other things I'm working on now.

**Comment by jrainville** [comment]
I've just tested Desktop to Desktop and the image/message itself doesn't propagate to the client, so it will be a fix in status-go. 

@ilmotta I'm working on it, hopefully I can fix it all with that fix. If possible, don't start work on it before I have a PR.

**Comment by ilmotta** [comment]
> I've just tested Desktop to Desktop and the image/message itself doesn't propagate to the client, so it will be a fix in status-go.
> 
> @ilmotta I'm working on it, hopefully I can fix it all with that fix. If possible, don't start work on it before I have a PR.

That's great news if it's in status-go. Thank you @jrainville. Once you open the PR I can test it on mobile.

**Comment by jrainville** [comment]
Here is the status-go fix https://github.com/status-im/status-go/pull/3816

It fixes the issue in Desktop to Desktop where the message didn't appear.

The AC in Desktop is still empty, but that is a separate Desktop only issue.

I believe this will fix the Mobile issues. @qoqobolo or @ilmotta you can test it

**Comment by ilmotta** [comment]
@jrainville 🎈 cool, that was fast! @qoqobolo I'll test on mobile this Friday and open the PR.

**Comment by qoqobolo** [comment]
@ilmotta I'm already on it :) Mobile PR for testing is here: https://github.com/status-im/status-mobile/pull/16807

Activity center notifications work great to me now, @jrainville thanks for the fix💥

However, cases 3 and 4, where the image is not displayed in AC both for mobile and desktop, are still reproducible. Could this be something else, some other issue? 

Also, I noticed some weird behavior of profile pictures: _sometimes_ they are not displayed for another mobile user. I'm still investigating this, but if you have any thoughts that it might be related to the Go PR changes, let me know pls @jrainville 

<img width="337" alt="Screenshot 2023-07-28 at 12 54 32" src="https://github.com/status-im/status-mobile/assets/67952253/2f7f59e7-57d6-4ece-b998-09dd51ee6be2">

**Comment by jrainville** [comment]
> However, cases 3 and 4, where the image is not displayed in AC both for mobile and desktop, are still reproducible. Could this be something else, some other issue?

Yes, for Desktop, we just never supported images in the AC. I reopened an issue on our side for that, but we'll need designs.

> Also, I noticed some weird behavior of profile pictures: sometimes they are not displayed for another mobile user. I'm still investigating this, but if you have any thoughts that it might be related to the Go PR changes, let me know pls @jrainville

I sadly don't have an idea. My changes just make it so status-g doesn't error when trying to save the AC notification, so it shouldn't affect anything related to profile pictures.
