### ISSUE TITLE
Offset half circle on selected color in the Color Picker

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#16815]
# Bug Report
Quo2 component library `color picker` component has an offset half circle on the selected color.

## Problem 
Happened both in the `color picker` component as well as in every component that uses the `color picker` as part of testing (i.e. `gradient cover` component), on Android only (tested on a Xiaomi Red 5 Plus).

#### Expected behavior

<img width="221" alt="Screenshot 2023-07-31 alle 08 57 51" src="https://github.com/status-im/status-mobile/assets/122543089/13b809bc-de31-42e0-baa8-3de1add28ef4">

#### Actual behavior

![](https://user-images.githubusercontent.com/122543089/256863331-a058ccb0-b5ea-44ee-be22-1f9d21bdb238.jpg)

### Reproduction

1. Open Status
2. Go to the Quo2.0 preview
3. Go to colors > color picker component

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @Francesca-G, Thank you for reporting the issue.
I tried provided steps, but issue is not reproducible for me. Maybe device specific.

**Comment by churik** [comment]
@Francesca-G Reopen if still relevant, closing as stale issue
