### ISSUE TITLE
Implement non-native card dashed border 

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#16828]
This issue refers to  [#16801](https://github.com/status-im/status-mobile/pull/16801)

## Problem
During the implementation of the account-card component, the team noticed that the dashed border is not the same as Figma. For reference please check the Review 3 here:

https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3356-276830&mode=design&t=4HgK5AwVqRGvZyxG-0

The goal of this issue is to achieve a custom SVG border that match exactly the design provided

#### Expected behavior
The design should follow Figma. In the case of the card account component, the dashed border is applied to the type "Add-Account". Here's the Figma file:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=19513-197699&mode=design&t=AyTZe7l184ev1VcK-0

#### Actual behavior
React Native does not allow us to customize the dashed border as we need (e.g. space in between each dash), it's limited to :border-width and :border-color in that case.

### Reproduction

1. Please navigate to "Profile and Quo.2.0 Preview" and locate the component under "Wallet/account-card."

### Additional Information

- Operating System: Android, iOS

Also, during the implementation of the account_card we came to this piece of code which can be used as an example to achieve what we need:

```

(defn- add-account-view
  [{:keys [on-press customization-color theme metrics?]}]
  [rn/view {:style {:flex 1 :justify-content "center" :align-items "center"}}
    [:> svg/Svg
      {:height (if metrics? 88 68)
       :width  161}
      [:> svg/Path
        {:d (if metrics? 
              "M16,0 h129 a16,16 0 0 1 16,16 v56 a16,16 0 0 1 -16,16 h-129 a16,16 0 0 1 -16,-16 v-56 a16,16 0 0 1 16,-16"
              "M16,0 h129 a16,16 0 0 1 16,16 v36 a16,16 0 0 1 -16,16 h-129 a16,16 0 0 1 -16,-16 v-36 a16,16 0 0 1 16,-16")
         :stroke (colors/theme-colors "pink" colors/white-opa-5 theme)
         :strokeWidth "1"
         :fill "none"
         :strokeDasharray "4"}]]
    [rn/view {:style {:position "absolute" :height (if metrics? 88 68) :justify-content "center" :align-items "center"}}
      [button/button
        {:type               :primary
         :size               24
         :icon               true
         :accessibility-label :add-account
         :on-press           on-press
         :customization-color customization-color}
        :i/add]]])

```

**Comment by clauxx** [comment]
@cammellos can be closed, since after discussing with @pedro-et, the position/size of individual dashes is not as important as consistency with other components. There are potential solutions with using svg as seen below, but reaching the design **exactly** can get very tricky. For more context, check the discord [discussion](https://discord.com/channels/624634427930312714/928625369542713396/1156617535861555260).

```clj
(defn- dashed-border
  [{:keys [width height border-color border-width gap-length dash-length border-radius container-style]}
   children]
  [rn/view
    {:style (merge {:width         width
                    :height        height
                    :border-radius border-radius
                    :overflow      :hidden}
                   container-style)}
    [svg/svg
     {:width            width
      :height           height
      :background-color :transparent
      :position         :absolute
      :left             0
      :top              0}
     [svg/rect
      {:x                0
       :y                0
       :width            width
       :height           height
       :stroke-width     border-width
       :rx               border-radius
       :ry               border-radius
       :stroke           border-color
       :stroke-dasharray (str dash-length "," gap-length)
       :fill             :none}]]
    children])

```
