### ISSUE TITLE
Keyboard keys are randomly highlighted during onboarding (IOS)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16824]
Reproducible on IOS (in my case iPhone X, IOS 16.5.1)

#### Actual behaviour

![photo_2023-08-01 11 11 29](https://github.com/status-im/status-mobile/assets/97245802/2454bec9-f0d6-4170-89dc-d8a266a73102)

### Reproduction

1. Install app
2. Proceed with onboarding (for example creation of new account)
3. Pay attention at keyboard on Create profile/Set password steps

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
We have zero control over how the keyboard looks like and what gets highlighted on it so I'm curious if it's not just some weird bug on your particular device.

**Comment by pavloburykh** [comment]
> We have zero control over how the keyboard looks like and what gets highlighted on it so I'm curious if it's not just some weird bug on your particular device.

It's definitely not a bug of my particular device as it is reproducible by all QA team folks.  But I guess this is some bug related to IOS 16.5.1 as @churik has faced the same issue in IOS Discord app this morning. 

So based on that I believe we need to close this issue. Though the bug is really weird. I haven't faced this issue before and I have not updated my IOS version.
