### ISSUE TITLE
Quo2 Wallet: Wallet Overview

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16834]
Implement this component in the quo2 component library as per the design spec.

Reuse Quo2 components wherever applicable.

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=470-23418&mode=design&t=9dGnEoVkqZnkIklJ-0

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

**Comment by J-Son89** [comment]
@OmarBasem - this requires Network dropdown component first, so whoever is doing this should make sure those components are ready 👍

**Comment by J-Son89** [comment]
I think this is a duplicate @OmarBasem and this is already done? 🤔

**Comment by OmarBasem** [comment]
> I think this is a duplicate @OmarBasem and this is already done? 🤔

Yes!
