### ISSUE TITLE
Unread messages from group chats are included to the tab unread counter

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16839]
# Bug Report

## Problem 
Follow-up on https://github.com/status-im/status-mobile/pull/16610 
Unread messages from group chats are still counted as unread only in messages tab.

#### Expected behavior
Counter matches all unread messages - so should be dot in particular case.

#### Actual behavior

![IMAGE 2023-08-02 14:57:44](https://github.com/status-im/status-mobile/assets/4557972/5abfac2e-81db-4325-9f48-cd90841dca87)

### Reproduction

1. Receive some messages in the group chat while you're on `Messages` home

### Additional Information

- Status version: nightly 02/08/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cc @ulisesmac

**Comment by ulisesmac** [comment]
@churik 
AFAIK, 
when one or more messages arrive to a group chat, the component should show the grey dot.

When messages with a mention arrive to group chats, they are count ed the component should show the badge number.

Am I right?
The screenshot it shows a message without mention arriving to a group chat, so I think it's correct to show a gray dot.

**Comment by churik** [comment]
@ulisesmac I'm  talking about messages tab here - it should be dot in group chat and in messages tab as well
<img width="327" alt="Unread messages from group chats are included to the tap unread counter · Issue #16839 · status-im:status-mobile 2023-08-04 12-46-47" src="https://github.com/status-im/status-mobile/assets/4557972/65ea3c81-1017-47c3-9353-057ed4c086fc">

**Comment by ulisesmac** [comment]
> @ulisesmac I'm  talking about messages tab here - it should be dot in group chat and in messages tab as well
> 
> <img width="327" alt="Unread messages from group chats are included to the tap unread counter · Issue #16839 · status-im:status-mobile 2023-08-04 12-46-47" src="https://github.com/status-im/status-mobile/assets/4557972/65ea3c81-1017-47c3-9353-057ed4c086fc">
> 
> 

Ok! Thanks for clarifying!
