### ISSUE TITLE
Implement Quo2 Network dropdown component

### ISSUE THREAD

**Issue by erikseppanen** [status-im/status-react#16830]
Implement this component in the quo2 component library as per the design spec:

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=21702-196840&mode=design&t=nat2qAwzQ4KyKjHM-4

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

**Comment by vkjr** [comment]
@erikseppanen, just noticed that you created this 5 minutes ago) Did you open it for yourself? I can unassign)

**Comment by erikseppanen** [comment]
> @erikseppanen, just noticed that you created this 5 minutes ago) Did you open it for yourself? I can unassign)

No, thanks @vkjr!

**Comment by erikseppanen** [comment]
btw, implementation might be similar to [network tags](https://github.com/status-im/status-mobile/pull/16747)
