### ISSUE TITLE
Signing phrase security concerns

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1684]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want my signing phrase to be secure, so that I am safe from phishers.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

1. How do we generate it? Is our RNG secure?
2. How do we secure the stored signing phrase? 
3. Is realm db safe from access by other apps?
4. ~Do we actually need it in plain text for the workflow to work?~ yes,we do

Re 1 - We can consider this one: [react-native-randombytes](https://www.npmjs.com/package/react-native-randombytes)

**Comment by flexsurfer** [comment]
Do we want to leave it in a message in the console?

**Comment by goranjovic** [comment]
@flexsurfer It's a tempting idea, but it wouldn't be a safe one. It would be better if the user had a password protected way to see and change it. And by change, I mean re-generate.

**Comment by flexsurfer** [comment]
@goranjovic i'm asking because in current implementation passphrase and signing phrase staying in console chat messages, so maybe better to delete this messages over time

**Comment by goranjovic** [comment]
@flexsurfer  A good catch. This was being cleared in the previous versions, I'll try to see in what change was it reverted.

**Comment by goranjovic** [comment]
superseded by onboarding swarm
