### ISSUE TITLE
Wrong buttons' background color on community home screen when overlay layer is applied (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16845]
Followup of https://github.com/status-im/status-mobile/pull/16772 cc @J-Son89 

**Steps:** 

1. Open community home page
2. Open Context menu bottom sheet
3. Pay attention at cancel/3 dots buttons' background

**Actual result:** 

![photo_2023-08-01 14 36 53](https://github.com/status-im/status-mobile/assets/97245802/7f479bdc-cf96-4c48-bac7-88b267ae3b0e)

https://github.com/status-im/status-mobile/assets/97245802/a16c037d-3918-4aa7-9e3c-03fd8f942e91

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1561-125067&mode=design&t=m43Z00HffrgciimR-0) 

<img width="354" alt="Communities for Mobile – Figma 2023-08-01 17-30-36" src="https://github.com/status-im/status-mobile/assets/97245802/cee64344-fb5c-4308-b0d5-fb6e121ce9b9">
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Blocked by https://github.com/status-im/status-mobile/issues/17017

**Comment by cammellos** [comment]
This is not blocked anymore @ibrkhalil

**Comment by J-Son89** [comment]
was this issue not fixed from @ulisesmac recent changes to that [age nav component? 🤔

**Comment by ulisesmac** [comment]
> was this issue not fixed from @ulisesmac recent changes to that [age nav component? 🤔

The page-nav component I fixed is being used inside another component:
`status-im2.common.scroll-page.view/f-scroll-page-header`

And it's only contemplating a switch between `:blur` and `:photo` page-nav variants according to scrolling state. 
The `f-scroll-page-header` component is not generalized enough to display a `page-nav` in other variants so it is still a pending task.

**Comment by ibrkhalil** [comment]
waiting for https://github.com/status-im/status-mobile/pull/17412 to get merged
