### ISSUE TITLE
Wrong color of composer buttons

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16844]
сс @J-Son89 followup of https://github.com/status-im/status-mobile/pull/16772

**Actual result:** 

![photo_2023-08-01 14 19 15](https://github.com/status-im/status-mobile/assets/97245802/dd906b4e-8bb7-4431-9d8a-5a3b68cf95d4)

**Expected result:** 

[Figma](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8438-538622&mode=design&t=GsYjbzFe6Llu9kHy-0)

<img width="300" alt="Messages for Mobile – Figma 2023-08-01 14-18-48" src="https://github.com/status-im/status-mobile/assets/97245802/e6db4ec0-3921-46b0-bc47-40e17e4e2ec7">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
Thanks @pavloburykh! will get on this now :)
