### ISSUE TITLE
Design review: context drawer 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16866]
- [x] 1. Align title and icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510573462)  
- [x] 2. The title and icon should be the same color - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510048139)

**Comment by ibrkhalil** [comment]
Issue 2 is already solved.
![image](https://github.com/status-im/status-mobile/assets/33176106/ffab1950-1e58-4107-bd1c-9eab069ab0df)
