### ISSUE TITLE
update toast component to encapsulate styles and update usages

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#16878]
ref :https://github.com/status-im/status-mobile/pull/16852#discussion_r1282773455

Setting a colour to toast should be an inbuilt property of the toast component to better align with figma properties.

Please check figma designs before picking this issue up.

ref : https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=3928-77614&mode=design&t=koUw7AJxFQ4bjfEy-0

**Comment by churik** [comment]
Closing as not planned and due to the lack of activity.

Reopen if still relevant.
