### ISSUE TITLE
Design review: sharing profile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16874]
- [ ] 1.  Margins in "Link to profile" - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3682:98959&mode=design#510227012)
  - Related issue reported in 1.25 design review - [comment](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8254&mode=design#567187175)
- [ ] 2. Paddings - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3682:98959&mode=design#510227534)
  - Related issue reported in 1.25 design review - [comment](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8254&mode=design#567187464)

**Comment by cammellos** [comment]
small issues, adding to 1.25

**Comment by cammellos** [comment]
@siddarthkay are you still working on this?

**Comment by siddarthkay** [comment]
Yes @cammellos : sorry will make progress this week 🙏🏻

**Comment by churik** [comment]
Can be closed in favor of https://github.com/status-im/status-mobile/issues/17569
