### ISSUE TITLE
Designer review: message drawer

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16872]
- [x] #16927
- [x] #16928
- [ ] 3. Composer > Reply - composer height is not aligned   - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226735)  
Needs to be clarified with @Francesca-G because of 2 comments https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3679:38431&mode=design#510745007 and https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3679:38431&mode=design#511409707

**Comment by Francesca-G** [comment]
> * [ ]  3. Composer > Reply - composer height is not aligned   - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226735)
>   Needs to be clarified with @Francesca-G because of 2 comments https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3679:38431&mode=design#510745007 and https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3679:38431&mode=design#511409707

Composer height should be 140px, as you can see in the design

<img width="412" alt="Screenshot 2023-08-04 alle 10 32 05" src="https://github.com/status-im/status-mobile/assets/122543089/97913072-57a3-4a80-8cb6-c786c92b6b7d">

but on iOS is slightly shorter (see red rectangle for comparison):

<img width="412" alt="Screenshot 2023-08-04 alle 10 33 12" src="https://github.com/status-im/status-mobile/assets/122543089/d77d5f08-fa61-487c-9d21-f47fc9da298e">

and on Android is slightly taller:

<img width="412" alt="Screenshot 2023-08-04 alle 10 33 29" src="https://github.com/status-im/status-mobile/assets/122543089/9b23ea0e-9795-4e7d-bad0-0972771929ee">

**Comment by cammellos** [comment]
1 & 2 are small issues, I'd include them in 1.25

I'd be a bit more wary of 3, it could be annoying to fix, if someone wants to take a look great, but otherwise looks like something we can descope for 1.25

**Comment by churik** [comment]
Composer is simplified, I guess no reason to keep it open anymore.
 Reopen if still relevant.
