### ISSUE TITLE
Design review: wallet overview

### ISSUE THREAD

**Issue by erikseppanen** [status-im/status-react#16886]
- [ ] 1. "spacing" (time frame: 3 month in screenshot)
- [ ] 2. "the danger color looks darker, I think this is danger/60 (for dark theme), instead of danger/50" (light theme)
- [ ] 3. "I know it's a placeholder but the spacing between balance value and network rectangle doesn't match design"
- [ ] 4. "spacing" (in skeleton loading bars)
- [ ] 5. "this is danger/50 instead of danger/60" (dark theme)

[design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3446%3A227419&mode=design&t=fxku3lC2V9UiKVNu-1)

![Screen Shot 2023-08-04 at 10 50 29 AM](https://github.com/status-im/status-mobile/assets/1012859/99a976f0-2967-40f0-8ade-0b28a7ad31c7)

**Comment by erikseppanen** [comment]
@Francesca-G

For 1, can you confirm that this is a problem, perhaps with the same text in both design and implementation? When I compare "1 month" between design and implementation, I see no difference.

For 3, it seems like you're saying the distance doesn't match. But when I compare the figma properties to the implementation's, they should be displaying identically. Could you confirm this problem?

UPDATE: I compared figma with implementation, and (horizontally at least) for 1 & 3 it looks correct:
![Screen Shot 2023-08-17 at 1 48 06 PM](https://github.com/status-im/status-mobile/assets/1012859/a421bfb5-6fea-4e74-b785-d4d9bd4e0b74)

**Comment by Francesca-G** [comment]
> @Francesca-G
> 
> For 1, can you confirm that this is a problem, perhaps with the same text in both design and implementation? When I compare "1 month" between design and implementation, I see no difference.

Looks fixed now, vertical spacing shouldn't vary based on the text :)
> 
> For 3, it seems like you're saying the distance doesn't match. But when I compare the figma properties to the implementation's, they should be displaying identically. Could you confirm this problem?
> 
As you can see from the red line the spacing doesn't match, but maybe it's a matter of screen res

<img width="500" alt="Screenshot 2023-08-21 alle 11 09 14" src="https://github.com/status-im/status-mobile/assets/122543089/f254cfd0-b1c3-4ba0-8e7c-7e1ab39c3a26">
