### ISSUE TITLE
App crashes with "Doesn't support name" error during onboarding (BLOCKER)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16883]
**Steps:** 

1. Install app
2. Tap I'm new to Status
3. Observe an error

**Actual result:** 

[Status-debug-logs (46).zip](https://github.com/status-im/status-mobile/files/12259384/Status-debug-logs.46.zip)

![photo_2023-08-04 12 40 41](https://github.com/status-im/status-mobile/assets/97245802/0762b47e-2f70-4504-93c0-ad4846a9a2f6)

https://github.com/status-im/status-mobile/assets/97245802/b83e90d8-1636-4338-aecb-2124514fac5f

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
hi @pavloburykh, Thank you very much for reporting this issue.
I am trying on latest develop, but issue is not reproducible for me.

**Comment by Parveshdhull** [comment]
Maybe issue fixed in develop, or only happening in release builds :thinking:

**Comment by Parveshdhull** [comment]
Yes @smohamedjavid confirmed issue is in release builds. He have more context on the issue, will look into this.
Thank you @smohamedjavid

**Comment by pavloburykh** [comment]
Hmm. It's weird. I am reproducing in latest nightly build. 

Also, I see that e2e run has failed because of this error in this PR https://github.com/status-im/status-mobile/pull/16879 But manually I am not reproducing it there.

**Comment by pavloburykh** [comment]
> Yes @smohamedjavid confirmed issue is only in release builds. He have more context on the issue, will look into this. Thank @smohamedjavid

oh, I see, thank you @Parveshdhull

**Comment by pavloburykh** [comment]
seems like not only release, but also nightly and e2e builds

**Comment by smohamedjavid** [comment]
@pavloburykh - Please check: https://github.com/status-im/status-mobile/pull/16884
