### ISSUE TITLE
Implement Select Account functionality on Select Address page

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16888]
# Feature Issue

### User Story

As a user, I want to switch between accounts in the Select Account page **so that** I send tokens from the desired account and see recent transactions / saved contacts / etc from the selected account

### Description

Follow Figma designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=916-232625&mode=design&t=1faxSWpX3vREG4M4-4

Visual reference:
<img width="193" src="https://github.com/status-im/status-mobile/assets/18485527/b38ef330-1474-4410-94f6-aef21f878232">

### Acceptance Criteria

Should implement pixel perfect design

**Comment by J-Son89** [comment]
@smohamedjavid this is a duplicate, right?

**Comment by smohamedjavid** [comment]
> @smohamedjavid this is a duplicate, right?

Yes @J-Son89

**Comment by smohamedjavid** [comment]
Completed in https://github.com/status-im/status-mobile/pull/18100
