### ISSUE TITLE
Improve floating shell button

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#16887]
### Summary

Improve floating shell button and fix spacing as mentioned in https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511287891

**Comment by Parveshdhull** [comment]
issue 4 in https://github.com/status-im/status-mobile/issues/16859

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull, it seems that the Figma link in the description is referring to the wrong comment. Could you please update it to refer to the correct one?

**Comment by Parveshdhull** [comment]
> Hi @Parveshdhull, it seems that the Figma link in the description is referring to the wrong comment. Could you please update it to refer to the correct one?

done
