### ISSUE TITLE
Add preview and counters for CR system messages

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16898]
Followup of https://github.com/status-im/status-mobile/pull/16775 cc @flexsurfer 

### 1. Add counters for "you were removed from contact" and "now is contact" system messages

**Steps:** 

1. Generate "you were removed from contact" and "now is contact" system messages
2. See if unread counter is generated for these types of messages

**Actual result:** unread counter is not generated

**Expected result:** unread counter should be generated

### 2. Add preview for "you were removed from contact"/"you removed from contact" system messages

**Steps:** 

1. Generate "you were removed from contact"/"you removed from contact" system messages
2. See if messages are shown in chat preview and in within chat card in Shell

**Actual result:** preview is not shown

**Expected result:** preview should be shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
ISSUE 3 will be implemented with new profile

**Comment by flexsurfer** [comment]
ISSUE 2 better to create a separate issue as a feature, not as bug
