### ISSUE TITLE
Indeticon rings are different on mobile and desktop

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16895]
# Bug Report

## Problem 
![image](https://github.com/status-im/status-mobile/assets/4557972/f73577df-1af2-4f17-b3f4-722a30030185)

#### Expected behavior
Indeticoins should be the same through the clients

### Reproduction

1. Scan QR any user from the desktop and compare identiocoin rings

### Additional Information

- Status version: nightly 07/08/23
- Status desktop: 0.14
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qfrank** [comment]
Hi @churik , i found this [PR](https://github.com/status-im/status-go/pull/3671) which result in the difference between desktop and mobile, because this PR mainly solved matching the designs, so proberbly i think desktop team need align this? cc @osmaczko @alwx @cammellos

**Comment by qfrank** [comment]
I can revert the changes to ring color set back if you like 😉

**Comment by churik** [comment]
I'm not sure who should align in particular case:) let's wait for other dev opinions

**Comment by osmaczko** [comment]
> Hi @churik , i found this [PR](https://github.com/status-im/status-go/pull/3671) which result in the difference between desktop and mobile, because this PR mainly solved matching the designs, so proberbly i think desktop team need align this? cc @osmaczko @alwx @cammellos

I've looked into the issue you linked, but I couldn't locate the color palette for the color hash on mobile. @alwx, would you mind sharing where you sourced these color values? status-go previously aligned with the desktop's colors prior to your update: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=1837-335130&mode=design&t=fWjSnD6MidcFo6KR-0

> I'm not sure who should align in particular case:) let's wait for other dev opinions

If there is indeed inconsistency in the designs, we should fix the designs first and then make clients aligned accordingly.

**Comment by alwx** [comment]
I got them from Figma!
- here is the component itself: https://www.figma.com/file/IBmFKgGL1B4GzqD8LQTw6n/Design-System-for-Desktop%2FWeb?type=design&node-id=115-6785&mode=design&t=wBzsq2TgttIGlHD7-0
- it uses colors from `Security/Identicon`. It's 32 colors that are here: https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=619-10143&mode=design&t=1ap1CEpymvNGMkZd-0

It seems like there is a mismatch in Figma designs.

**Comment by qfrank** [comment]
> I got them from Figma!
> 
> * here is the component itself: https://www.figma.com/file/IBmFKgGL1B4GzqD8LQTw6n/Design-System-for-Desktop%2FWeb?type=design&node-id=115-6785&mode=design&t=wBzsq2TgttIGlHD7-0
> * it uses colors from `Security/Identicon`. It's 32 colors that are here: https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=619-10143&mode=design&t=1ap1CEpymvNGMkZd-0
> 
> It seems like there is a mismatch in Figma designs.

cc @churik @cammellos

**Comment by churik** [comment]
@Francesca-G can you please confirm https://github.com/status-im/status-mobile/issues/16895#issuecomment-1669347320 ?
Thank you!

**Comment by mariocnovoa** [comment]
Maybe I'm skipping something, but I don't see the problem 😓 .
The old desktop identicon ring colours and mobile/web colours are exactly the same

Kuba Desktop file
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=662%3A320379&mode=design&t=gj7eonD771RnQGlL-1

Foundations
https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=619%3A10143&mode=design&t=5sVuGe8lqsBr6FKH-1

**Comment by osmaczko** [comment]
> Maybe I'm skipping something, but I don't see the problem sweat . The old desktop identicon ring colours and mobile/web colours are exactly the same
> 
> Kuba Desktop file https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=662%3A320379&mode=design&t=gj7eonD771RnQGlL-1
> 
> Foundations https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=619%3A10143&mode=design&t=5sVuGe8lqsBr6FKH-1

Oh.. :eyes: They are not the same, the indexing is different.
![image](https://github.com/status-im/status-mobile/assets/33099791/e800af06-735c-40e0-9546-2e4121876622)

Would you mind fixing the order in Foundations?

**Comment by mariocnovoa** [comment]
That's the order in desktop code? Because in Kuba there's nothing specified
Can you send us the order in desktop?

**Comment by osmaczko** [comment]
> That's the order in desktop code? Because in Kuba there's nothing specified

I believe we assumed the implicit indexing from left to right ( for programmers there is no other way :sweat_smile: ).
0 1 2 3 4
5 6 7 8 9

> Can you send us the order in desktop?

Exactly as in Kuba figma, ordered from left to right: https://github.com/status-im/status-desktop/blob/ba89daa737d0ed71d64380f50650b2d85bfef232/ui/StatusQ/src/StatusQ/Core/Theme/StatusLightTheme.qml#L89-L94

![image](https://github.com/status-im/status-mobile/assets/33099791/f41c5337-52fb-472e-b5be-529170dac0d9)

**Comment by mariocnovoa** [comment]
Updated!
https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=619%3A10143&mode=design&t=s9sU5ABfd2A7JVaZ-1
