### ISSUE TITLE
"Jump to" button is displayed inside the composer after editing a message

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16900]
# Bug Report

## Problem 

That's more visible for long messages but also reproducible for short ones. 

_There seems to be some issue with playing the attached videos in GH. Adding also a screenshot just in case, but if you need the video, ping me in DM/comments here_

https://github.com/status-im/status-mobile/assets/67952253/add335da-284b-4226-97b7-d148ef88902b

<img width="339" alt="Screenshot 2023-08-07 at 14 24 45" src="https://github.com/status-im/status-mobile/assets/67952253/05e7a9ff-9600-4154-8169-5639655033dc">

### Reproduction

1. Send a message
2. Long tap > Edit
3. Expand composer
4. Tap `x` to close the edit mode
5. Collapse the composer

### Additional Information

- Status version: nightly 07/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Was able to reproduce the same issue if I did the same behavior but with replying to a message instead of editing it.
