### ISSUE TITLE
Implement Select asset page

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16914]
# Feature Issue

### User Story

As a user, I want to see all the available tokens **so that** I select the token I want to send.

### Description

Figma design: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-193169&mode=design&t=Nt07uzj0YkMEcocF-4

Visual reference:
<img width="267" src="https://github.com/status-im/status-mobile/assets/18485527/435c6eca-b44c-4a91-a26d-f0009c7107a0">

### Acceptance Criteria

- [ ] Options shown should be `Assets` and `Collectibles`, but only `Assets` should be implemented in this issue.
- [ ] Search will be implemented in a separate issue
- [ ] Light and dark mode should be implemented
- [ ] Navigate to amount selection screen (if that screen is not implemented, it can be done in a follow up issue)

**Comment by Rende11** [comment]
I would like to implement it
