### ISSUE TITLE
Channels colours do not match with desktop (may be desktop issue?) 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16924]
# Bug Report

## Problem 
On desktop, every channel uses the custom color, which is not used on mobile

<img width="516" alt="photo_2023-08-08 13 46 57 jpeg 2023-08-08 13-47-26" src="https://github.com/status-im/status-mobile/assets/4557972/dc044376-1371-4625-bba3-fb18c8bc581c">, but according to design on mobile: [here](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10283-425360&mode=design&t=s2caXe9Bz98BIH7d-4) - custom colors are not used
![image](https://github.com/status-im/status-mobile/assets/4557972/67b676f0-90a9-4e23-8e26-93cfd5b372f9)

Not sure where alignment should be done

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
can you please find out @Francesca-G ? 
Should every channel on the desktop has a custom color, it is a mistake on the desktop side or in the design?

**Comment by Francesca-G** [comment]
> can you please find out @Francesca-G ?
> Should every channel on the desktop has a custom color, it is a mistake on the desktop side or in the design?

AFAIK Desktop channels are being redesigned, the correct use of channel colors is in the mobile designs

**Comment by churik** [comment]
I'll just then send an issue to desktop channels, just in case, and closing this issue.
Thank you.
