### ISSUE TITLE
Implement Send page > Calculate and show network routes breakdown

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16929]
# Feature Issue

### User Story

As a user, I want to input the amount of tokens I want to send **so that** I see the networks breakdown
### Description

Figma Design 1: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2361-525589&mode=design&t=QNEqrWQp5rtESmaX-4
Figma Design 2: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-505518&mode=design&t=QNEqrWQp5rtESmaX-4

Visual reference:
<img width="165" src="https://github.com/status-im/status-mobile/assets/18485527/60996c1e-c17b-4eec-ab0f-c68f0d8c0b5c"> <img width="165" src="https://github.com/status-im/status-mobile/assets/18485527/01625a56-9900-4b80-aa54-8a9ea4fe6676">

### Acceptance Criteria

- [x] Show network routes. Fees and amount is NOT included in this issue
- [x] When in loading state, Continue button should be disabled
- [x] Network routing edit should be implemented in another issue

**Comment by J-Son89** [comment]
leaving this until after 1.27

**Comment by briansztamfater** [comment]
> leaving this until after 1.27

@J-Son89 maybe we should show fees for 1.27 and leave just network routing part for post-1.27? wdyt?

happy to break this into multiple issues if necessary

**Comment by J-Son89** [comment]
Yeah sounds good to me!

**Comment by briansztamfater** [comment]
Updated this one and created #18186

**Comment by briansztamfater** [comment]
I think we can close this one, we already implemented network routing in Send and Bridge flows. We can follow up con other issues for bugs enhancements.
