### ISSUE TITLE
"Error" message shown when tapping History tap in Wallet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1692]
### Description

*Type*: Bug

*Summary*: History screen should be available in Wallet redesign 

#### Actual behavior
"Error" message is shown

### Reproduction

- Open Status
- Go to Wallet tab
- Click History

![screenshot_2017-08-25-14-58-54-882_im status ethereum 1](https://user-images.githubusercontent.com/28752642/29713378-f13699f2-89a6-11e7-8c94-6299e2810336.png)

### Builds

iOS: 0.9.11d28
Android: 0.9.10-28-ga2b717cf+

**Comment by jeluard** [comment]
Tabs are not implemented yet (see limitations in #1686 ). Will be fixed in a later PR.
