### ISSUE TITLE
Implement Send page > Input amount

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16926]
# Feature Issue

### User Story

As a user, I want to input the amount of tokens I want to send **so that** I can specify the precise transaction value.

### Description

Figma design: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=921-233460&mode=design&t=YkMt1bwxJ6CdyM1n-4

Visual reference:
<img width="234" src="https://github.com/status-im/status-mobile/assets/18485527/d8112720-5473-4d23-8028-1c38c4c8fa76">

### Acceptance Criteria

- [ ] Amount must not exceed the max amount
- [ ] Continue button should be enabled when a value is entered
- [ ] Networks breakdown and fees will be implemented in a separate issue
- [ ] Add a component test to cover some basic functionality on the page

**Comment by Rende11** [comment]
I would like to implement it
