### ISSUE TITLE
Make tabs naming in uppercase for Transactions screens on Android

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1693]
### Description

*Type*: Bug

*Summary*: both Unsigned and History tabs as well as Sign All button should be uppercase for Android

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/29713722-9ae91ece-89a8-11e7-966a-a0d7a2c25a03.png)

Android: 0.9.10-28-ga2b717cf+

**Comment by jeluard** [comment]
Fixed in develop
