### ISSUE TITLE
Implement "Wallet Button" Component

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#16949]
# Feature

Implement the "Wallet Button" component in the quo2 component library.

<img width="250" alt="Screenshot 2023-08-09 at 5 33 18 PM" src="https://github.com/status-im/status-mobile/assets/19339952/7c64eee5-00d7-4a5d-a4eb-9fca05f8977b">

### Designs

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1%3A413&mode=design&t=kFyYCJ2r6DsZsfP5-1)

### Acceptance Criteria:

- Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
- Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)
- Should add an export from the `quo2.core` namespace
- Add a preview for this component under the `button` category in the Quo2 preview screen

**Comment by OmarBasem** [comment]
Isn't this the same as the composer button, except it has no blur state? If the values are identical maybe they can be one component, (or the composer button can extend the wallet button) cc @J-Son89

**Comment by J-Son89** [comment]
@OmarBasem yea that seems a reasonable suggestion, but best to follow the design system. let's leave a comment on the figma file or discuss directly with designers and see if they think it's worth adjusting these. Cc @mariocnovoa

**Comment by OmarBasem** [comment]
@J-Son89 I see the wallet icons are black and white, while the composers are grey. 

Since they are fairly small components, I think we can keep them separated, there wouldn't be many repetitions, may be better than using conditions. I will work on it.
