### ISSUE TITLE
Implement Empty state UI for Account Screen

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#16945]
# Feature Issue

### User Story

As a user, I should be able to see the empty state of the newly created account in the wallet.

### Description

- Implement a navigation bar with a close button.
- Implement the "Account Overview" component.
- Add an empty red "Illustration here" box.
- Add quick actions Buy, Send, Receive, and Bridge.
- Implement Scrollable Tabs.

#### :warning: Scope not covered:

- Navigation bar with the Networks tag and Account switcher (the `Nav bar` component needs to be updated separately).
- The quick actions don't need to do any functionality. Implement just the UI.
- Data or UI displayed under each Scrollable Tab.

### Design

[Link to Figma](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2224%3A463447&mode=design&t=NTSx9HMnt9a0qhaL-1)

Edit: [Related Figma flow](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-46867&mode=design&t=l0Ire3lFHginT8mK-0)

<img src="https://github.com/status-im/status-mobile/assets/19339952/8dca1b2d-6d9d-448d-839a-c73d87f7b2b0" width="200" />

**Comment by OmarBasem** [comment]
@smohamedjavid I think that's a duplicate for that flow in figma https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-45672&mode=design&t=l0Ire3lFHginT8mK-0 🤔 
cc @J-Son89
