### ISSUE TITLE
Sort communities in order of joining them

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16942]
# Bug Report

## Problem 

Currently, communities are added to the communities list in random order.
We should display the last joined ones on top of the list. 

<img width="395" alt="Screenshot 2023-08-09 at 11 59 28" src="https://github.com/status-im/status-mobile/assets/67952253/6f310acd-008d-4565-8dd9-dae9fdf99c1f">

#### Expected behavior
Random order

#### Actual behavior
New communities on top

### Reproduction

1. Join several communities
2. Check their order on the home community screen

### Additional Information

- Status version: nightly 9/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
closing as the other one is included to scope already https://github.com/status-im/status-mobile/issues/17337
