### ISSUE TITLE
Implement Change account action in Token input

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16955]
# Feature Issue

### User Story

As a user, I want to switch between accounts in the Token Input page **so that** I send the tokens from the desired account

### Description

Figma Design 1: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-509284&mode=design&t=HUmtev01QbEue8sV-4
Figma Design 2: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503863&mode=design&t=HUmtev01QbEue8sV-4
Figma Design 3: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503786&mode=design&t=HUmtev01QbEue8sV-4
Figma Design 4: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-507516&mode=design&t=w7yLPvpvYH8Csnzk-4

Visual reference:
<img width="173" src="https://github.com/status-im/status-mobile/assets/18485527/16b435c8-4a9d-4b6b-9f18-88bcee9e9bef"> <img width="173" src="https://github.com/status-im/status-mobile/assets/18485527/0b1eee44-6433-4b36-8598-9d57bedec18b"> <img width="173" src="https://github.com/status-im/status-mobile/assets/18485527/3b5abaa8-32ac-46c7-a764-56eac5daa52c"> <img width="230" src="https://github.com/status-im/status-mobile/assets/18485527/1537ccc6-8096-4439-9a0c-f5fcd924e0a4">

### Acceptance Criteria

- [ ] When user clicks account icon at the top-right in the navigation bar, bottom sheet should appear with account selection list
- [ ] If user taps on an account and the account contains the same token, bottom sheet should dismiss and change the account icon in the navigation bar, re-validate token amount in the token input, recalculate fees and network breakdown
- [ ] If user taps on an account and the account does not contains the same token, bottom sheet should dismiss and change the account icon in the navigation bar, clear token input and navigate to token selection screen

**Comment by J-Son89** [comment]
@smohamedjavid is this feature already completed? or are we still missing some details to make this work? 🤔

**Comment by smohamedjavid** [comment]
@J-Son89 - No, we have the account switcher in place but it doesn't update the token, routes and other dependencies in the send flow. This issue explains missing pieces perfectly. 

EDIT: Made one update in the issue for the edge case.

**Comment by FFFra** [comment]
Discussed with design and decided to simplify the approach by resetting the input/page on swapping the account.
handled here: https://github.com/status-im/status-mobile/pull/19568
