### ISSUE TITLE
Implement Change currency action in Token input

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16952]
# Feature Issue

### User Story

As a user, I want to change the currency of the token input **so that** I can see the value in the currency of my preference

### Description

Figma Design 1: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-509053&mode=design&t=okuda3Z4bIOTwvRi-4
Figma Design 2: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-509284&mode=design&t=w7yLPvpvYH8Csnzk-4

Visual reference:
<img width="553" src="https://github.com/status-im/status-mobile/assets/18485527/2fcabac2-fab4-4c0e-b611-a8775360614e">

### Acceptance Criteria

- [ ] When user clicks button at the right of the input, should show the amount value and max value in the user preferred currency, and converted to the other currency at the right, below the button
- [ ] Can toggle currency by clicking again in the button

Feel free to break up this issue in smaller issues if necessary

**Comment by FFFra** [comment]
It's already implemented.
