### ISSUE TITLE
Implement Send page > Edit Receiver networks 

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16958]
# Feature Issue

### User Story

As a user, I want to edit which networks the receiver will receive the assets on **so that** I can optimize transaction efficiency and align with their preferred blockchain networks, while maintaining the flexibility to accommodate non-preferred networks if needed.

### Description

Figma Design 1: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503644&mode=design&t=HUmtev01QbEue8sV-4
Figma Design 2: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503675&mode=design&t=HUmtev01QbEue8sV-4
Figma Design 3: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503714&mode=design&t=HUmtev01QbEue8sV-4
Figma Design 4: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503755&mode=design&t=HUmtev01QbEue8sV-4

Visual reference:
<img width="180" src="https://github.com/status-im/status-mobile/assets/18485527/fa984e52-f468-4720-84a4-0b3db4b4014f"> <img width="180" src="https://github.com/status-im/status-mobile/assets/18485527/ae7ce34c-842a-4426-8c1f-d015506a0713"> <img width="180" src="https://github.com/status-im/status-mobile/assets/18485527/40bd48a9-83e2-4c31-93e3-5dc2b71229fa"> <img width="180" src="https://github.com/status-im/status-mobile/assets/18485527/4ad35e25-ff7b-4000-a000-0d18be9b76a8">

### Acceptance Criteria

- [ ] When user taps on plus button in the receiver column, `Edit receiver networks` bottom sheet should be shown 
- [ ] Should show receiver preferred and non-preferred networks (Mainnet, Optimism, Arbitrum)
- [ ] If user checks a non-preferred network, an alert should be shown to the user ([Figma reference](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503750&mode=design&t=V0dXiJUCqM0Jo7Od-4))
- [ ] Fees should be re-calculated when receiver networks are edited and user taps on `Apply changes` button

Feel free to break up this issue in smaller issues if necessary

**Comment by J-Son89** [comment]
@OmarBasem - is this a duplicate/ now it's complete? 🤔

**Comment by OmarBasem** [comment]
> @OmarBasem - is this a duplicate/ now it's complete? 🤔

Yes completed
