### ISSUE TITLE
Implement Send page > Tap to disable a network

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16959]
# Feature Issue

### User Story

As a user, I want to tap to disable a network **so that** I can prevent asset transfers through that specific network, ensuring security and avoiding accidental or unwanted transactions.

### Description

Figma Design 1: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503644&mode=design&t=V0dXiJUCqM0Jo7Od-4
Figma Design 2: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2396-514803&mode=design&t=V0dXiJUCqM0Jo7Od-4
Figma Design 3: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2436-520431&mode=design&t=V0dXiJUCqM0Jo7Od-4

Visual reference:
<img width="185" src="https://github.com/status-im/status-mobile/assets/18485527/2379c831-f5da-40dd-be2e-bbf824c541b2"> <img width="185" src="https://github.com/status-im/status-mobile/assets/18485527/f908f21b-bd1b-4cb9-b9be-f8006553616b"> <img width="185" src="https://github.com/status-im/status-mobile/assets/18485527/bdf31279-22f8-4275-a3e9-ce71342c2444">

### Acceptance Criteria

- [ ] When user taps on a network card, it should be toggle its enabled / disabled state
- [ ] Network breakdown and fees should be re-calculated every time a network is disabled on enabled

**Comment by FFFra** [comment]
Closed in favor of:

https://github.com/status-im/status-mobile/pull/19392
