### ISSUE TITLE
Move Top Nav component to quo2

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#16964]
Currentyl we have Top Nav component under `status-im2.common.home.view`. It should be moved to quo2. 

[Designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=145-6203&mode=design&t=vbtCUjtfumUCfzZL-0)

**Comment by OmarBasem** [comment]
Hey @J-Son89, I have opened an issue for moving the top nav component if you would like to work on it

**Comment by OmarBasem** [comment]
Duplicated

**Comment by OmarBasem** [comment]
Hey @J-Son89, I have opened an issue for moving the top nav component if you would like to work on it. 

I am not sure if there is an open issue already so feel free to close this one if it is a duplicate

**Comment by J-Son89** [comment]
Thanks @OmarBasem, yep I have another issue for this and just opened the pr :)
