### ISSUE TITLE
Can't invite user to closed community

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#16968]
# Bug Report

## Problem 
We need an ability to create communities on mobile for e2e tests. Currently we can't test closed community properly. That's not reproducible in  https://github.com/status-im/status-mobile/pull/16806 where this feature was presented 

#### Expected behavior
Community is shared

#### Actual behavior

[259719671-f04ea1b9-520a-4851-8521-cb6e34719bc7.webm](https://github.com/status-im/status-mobile/assets/29711298/10ee8399-9f1b-4f1e-9722-66a443c7965f)

### Reproduction

1. Create closed community
2. Click Invite people from contact list or  Share community
3. Select contacts to invite
4. Click Invite button

### Additional Information

- Status version: nightly e2e (x86)
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
Reproducible in any community regardless where it was opened - on desktop or on mobile

**Comment by churik** [comment]
So turned out that Invite flow is not working as before anymore and we need to use Share for now for the same purpose. I'll adjust the tests to do this, closing the current issue
