### ISSUE TITLE
Image is not sent if added while editing message

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16971]
**Steps:** 

1. Send message containing text
2. Edit message by adding an image
3. See if image is added during message editing

**Actual result:** image is not added

https://github.com/status-im/status-mobile/assets/97245802/9198041a-d805-4d3e-aa7d-7cbaff166392

**Expected result:** image is added

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@pavloburykh this is actually not supported at the protocol level, we can only edit text, so it should be disabled.

**Comment by cammellos** [comment]
We should probably have a word with design, the simplest solution is likely to disable adding an image, or we could otherwise implement the changes so you can edit a text message into an image.

**Comment by churik** [comment]
![IMAGE 2024-06-21 11:38:33](https://github.com/status-im/status-mobile/assets/4557972/14bb8b4e-8a23-44f9-aded-6d862bddf6cd)
