### ISSUE TITLE
Show collectible information in Transaction Confirmation page

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16979]
# Feature Issue

### User Story

As a user, I want to see a summary of my collectible transaction **so that** I can review the details and sign to confirm it.

### Description

Figma Design: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-317327&mode=design&t=nilAPUyk59K54DQh-4

Visual reference:
<img width="252" src="https://github.com/status-im/status-mobile/assets/18485527/9fc62c80-7770-495f-bcad-cd6862543c9e">

### Acceptance Criteria

- [x] Show title that specifies which collectible you are sending, from which account and who is the reciever 
- [x] Show `From` and `To` detail cards with collectible title
- [x] Show `Details` card
- [x] Show `Slide to sign` slider and add authentication process
- [x] Execute transaction if the user slides and authentication succeeds
- [x] Light and dark mode should be implemented
- [x] Background gradient color should be based on account color

**Comment by briansztamfater** [comment]
@ulisesmac I am adding this stuff as part of https://github.com/status-im/status-mobile/issues/18260 as it is easier to work on it while implementing UI, let me know if I can assign this issue as I have some progress already!

**Comment by ulisesmac** [comment]
Hey @briansztamfater !

Cool, I've been working on this too, I did some changes related to some events (maybe you already solve it), I'll add a detailed comment with my changes so you can evaluate what to add or what you already added.

It makes sense that this is soved as part of the issue you mentioned 👍

**Comment by ulisesmac** [comment]
I've just rebased on develop, and I'd like to add a suggestion.

We have these events in:
```clojure
;; ns  status-im.contexts.wallet.send.events
(rf/reg-event-fx :wallet/select-send-account-address
 (fn [{:keys [db]} [{:keys [address stack-id]}]]
   {:db (-> db
            (assoc-in [:wallet :ui :send :send-account-address] address)
            (update-in [:wallet :ui :send] dissoc :to-address))
    :fx [[:navigate-to-within-stack [:wallet-select-asset stack-id]]]}))

(rf/reg-event-fx :wallet/select-send-address
 (fn [{:keys [db]} [{:keys [address stack-id]}]]
   {:db (-> db
            (assoc-in [:wallet :ui :send :to-address] address)
            (update-in [:wallet :ui :send] dissoc :send-account-address))
    :fx [[:navigate-to-within-stack [:wallet-select-asset stack-id]]]}))
```

I think `:wallet/select-send-account-address` was initially created, they are almost the same, to avoid duplicating subscriptions to get the `:to-address` account and the `:send-account-address`, I believe is better to just use one of them (`:wallet/select-send-account-address`) and remove the other one and its usages.

(I did that change in my branch, pretty small but important).

The other changes are related to set up the data for the page, so nothing else to add.
