### ISSUE TITLE
App stuck on QR scanning with desktop on particular wi-fi networks

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16987]
# Bug Report

## Problem 
When scanning valid QR from[ status desktop 0.13.3 ](https://github.com/status-im/status-desktop/releases/tag/0.13.3) app is stuck.

It is not reproducible for all users (i.e. not for @qoqobolo on another network), for me it is reproducible every time on Android only.

#### Expected behavior
be redirected to "syncing" screen

#### Actual behavior
App Stuck in "syncing" state, something went wrong after 5-10 mins.

https://github.com/status-im/status-mobile/assets/4557972/649b3f41-629e-4327-9df4-1d5774c0a23a

### Reproduction

1. Open desktop app > Generate sync code
2. Scan valid QR from Sign in

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12320546/Status-debug-logs.zip)

**Comment by churik** [comment]
cc @Samyoul @ulisesmac

**Comment by cammellos** [comment]
```
08-11 10:20:34.897 16795 16894 D ReactNativeJS: DEBUG [utils.re-frame:21] - Handling re-frame event:  :signals/signal-received
08-11 10:20:34.900 16795 16894 I ReactNativeJS: INFO [status-im.signals.core:33] - local pairing signal received {:event {:type "connection-error", :error "dial tcp 192.168.1.189:58654: connect: connection timed out", :action 1}}
```
Seems like a connection error cc @Samyoul

**Comment by Samyoul** [comment]
> `dial tcp 192.168.1.189:58654: connect: connection timed out`

Hmm

> for me it is reproducible every time on Android only.

Hmmmm

> App Stuck in "syncing" state, something went wrong after 5-10 mins.

Hmmmmmmmm

**Comment by Samyoul** [comment]
A little update, I'm going to implement a rough diagnostics / debugger functionality https://github.com/status-im/status-go/issues/3885, this will give us more info.

You've reported `App Stuck in "syncing" state, something went wrong after 5-10 mins.` and the logged error shows `dial tcp 192.168.1.189:58654: connect: connection timed out`. Which means roughly that the scanning device attempted to connect to the QR code device for 5ish minutes and failed.

We need to know a little bit more information about this, and the device / network diagnostics will help.

**Comment by ajayesivan** [comment]
Experiencing this on latest develop.
Syncing from an iPhone Simulator to Android Device(Pixel 7a).

**Comment by churik** [comment]
@ajayesivan are you sure it is latest-latest develop and issue is the same? 
we had this https://github.com/status-im/status-mobile/issues/17137 - I rechecked it on rebased PR and it was working

I'll recheck on nightly-nightly (mobile-mobile) and master> nightly too (desktop>mobile)

**Comment by churik** [comment]
Ok, now it is blocked because of: https://github.com/status-im/status-mobile/issues/17156

**Comment by ajayesivan** [comment]
> @ajayesivan are you sure it is latest-latest develop and issue is the same? we had this #17137 - I rechecked it on rebased PR and it was working
> 
> I'll recheck on nightly-nightly (mobile-mobile) and master> nightly too (desktop>mobile)

I tested it today morning in develop. I will check again and confirm.

**Comment by ajayesivan** [comment]
@churik Still facing this issue on the latest develop when scanning the QR code from an Android device.

The error I'm getting in terminal(Metro)
```
INFO  INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"route ip+net: netlinkrib: permission denied\"}", :event :syncing/input-connection-string-for-bootstrapping}
```

It's working fine on iOS.

**Comment by churik** [comment]
Still getting this issue on particular network (public wi-fi) 

Reproducible for me for both Android / IOS > desktop master 15/09

**Comment by VolodLytvynenko** [comment]
Also experienced with getting [this](https://github.com/status-im/status-mobile/issues/16987#issue-1846599920) issue when used a public wi-fi

[android_logcat4.txt](https://github.com/status-im/status-mobile/files/12647314/android_logcat4.txt)

**Comment by Samyoul** [comment]
> route ip+net: netlinkrib: permission denied

Hmmm @ajayesivan , that is not good, I thought that all calls to `net.Interfaces()` had been removed for Android. Unless they've been reintroduced some where.

**Comment by Samyoul** [comment]
This problem appears to be related to https://github.com/status-im/status-desktop/issues/12126

```
14:19:01.727  I  INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"failed to connect to any of given addresses. failed to connect to any of given addresses. connecting to 'https://192.168.1.136:61302' failed: dial tcp 192.168.1.136:61302: connect: no route to host; \"}", :event :syncing/input-connection-string-for-bootstrapping}
14:19:01.732  D  DEBUG [utils.re-frame:21] - Handling re-frame event:  :signals/signal-received
14:19:01.737  I  INFO [status-im.signals.core:33] - local pairing signal received {:event {:type "connection-error", :error "failed to connect to any of given addresses. failed to connect to any of given addresses. connecting to 'https://192.168.1.136:61302' failed: dial tcp 192.168.1.136:61302: connect: no route to host; ", :action 1}}
```

**Comment by VolodLytvynenko** [comment]
I am still able to reproduce the issue when app is stuck [both Android/IOS]  on QR code scanning if the mobile user tries to be synced with the **Desktop [Status go 0.167.2]**. The current issue occurs rarely and Wi-Fi public network is very low

### Logs:
[android_logcat4.txt](https://github.com/status-im/status-mobile/files/12716470/android_logcat4.txt)

### ENV:
- Master Desktop, Status go 0.167.2
- Mobile Device: Nightly [25 Sep 2023]

**Comment by cammellos** [comment]
```
17:03:45.025  I  INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"Get \\\"https://192.168.1.199:56087/pairing/challenge\\\": dial tcp 192.168.1.199:56087: connect: network is unreachable\"}", :event :syncing/input-connection-string-for-bootstrapping}

```

**Comment by Samyoul** [comment]
@VolodLytvynenko does this problem only happen on a public Wi-FI network?

`connect: network is unreachable` is a OS level error and it reports an issue with the network, rather than the device or connection.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko does this problem only happen on a public Wi-FI network?
> 
> `connect: network is unreachable` is a OS level error and it reports an issue with the network, rather than the device or connection.

@Samyoul I was able to reproduce it only for public Wi-Fi. But the signal was really very low

**Comment by churik** [comment]
I think this is acceptable; I'll check tomorrow on other public wi-fi where I wasn't able to sync before fix and post results here

**Comment by cammellos** [comment]
Though we should be checking and making sure we retry correctly and we surface the error to the user @Samyoul @qfrank

**Comment by Samyoul** [comment]
Surfacing the right error is something we need to improve, because there are some https client errors that should be intercepted and wrapped in more informative errors.

Example, a 403 error when getting the challenge has a special meaning. Ie https server's session is locked.

We can scope this out and ensure we give the user as meaningful messages as possible.

In addition we can implement a much more robust process for retrying pairing when the connection has been dropped part way through the transfer of data.

**Comment by qfrank** [comment]
> Surfacing the right error is something we need to improve, because there are some https client errors that should be intercepted and wrapped in more informative errors.
> 
> Example, a 403 error when getting the challenge has a special meaning. Ie https server's session is locked.
> 
> We can scope this out and ensure we give the user as meaningful messages as possible.
> 
> In addition we can implement a much more robust process for retrying pairing when the connection has been dropped part way through the transfer of data.

Yes, I believe there are still many opportunities for improvement. It depends how far we want to go. 
Also I saw many places just return err but didn't log it which make locating error not that easy. e.g. [NewBaseClient](https://github.com/status-im/status-go/blob/2afe5a269de11bad5412a64e27d33bd49a28d588/server/pairing/client.go#L89) .

**Comment by churik** [comment]
So:
- on my home wi-fi syncing is working perfectly.
- on public wi-fi (cafe) it is not working and not giving a feedback 

https://github.com/status-im/status-mobile/assets/4557972/649b3

I suggest improving feedback and warn user that they should not use guest public wi-fi network, if it is not supposed to work there as pointed by @Samyoul 
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12740520/Status-debug-logs.zip)
f41-629e-4327-9df4-1d5774c0a23a

**Comment by churik** [comment]
It is working better now, the most important part is to display the error and allow to start the process over 

Will be handled in the scope of https://github.com/status-im/status-mobile/issues/17634
