### ISSUE TITLE
Implement Send collectible from Collectibles details page

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16990]
# Feature Issue

### User Story

As a user, I want to be able to send a collectible from the collectible detail screen so that I can quickly initiate the sending process without navigating back to the account page, streamlining the overall experience.

### Description

Pre-requisites: Collectible details screen should be implemented.

This issue is more related to flows rather than implementing UI, UI should be already implemented at this point.

Figma design 1: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-315956&mode=design&t=PQXlpA0Kw075Q09Y-4
Figma design 2: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-316125&mode=design&t=PQXlpA0Kw075Q09Y-4
Figma design 3: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-317327&mode=design&t=PQXlpA0Kw075Q09Y-4

Visual reference:
<img width="545" src="https://github.com/status-im/status-mobile/assets/18485527/3cfcb38d-65e6-4269-9b1f-36f4b878ec44"> <img width="208" src="https://github.com/status-im/status-mobile/assets/18485527/566244e2-5013-4118-a914-1798264727de">

### Acceptance Criteria

- [ ] When user taps on `Send` button within a Collectible detail screen, should navigate to Select Address page
- [ ] When user inputs or selects an Address / Contact / Account / Saved Address, should navigate to Transaction Confirmation page to confirm the transaction (#16979)

**Comment by J-Son89** [comment]
@ulisesmac - just tagging you for reference. The issue with collectibles/wizard navigation will address this anyway 👍
