### ISSUE TITLE
Implement "Add network preferences" functionality in Save address flow

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#16995]
# Feature Issue

### User Story

As a user, I want to be able to set network preferences **so that** transaction network choices are automatically optimized based on my saved preferences for efficient calculations.

### Description

On tap of the preferences icon next to the address, the network preferences sheet should be shown and the user should be allowed to select any network of choice for that address

NOTE: The network preference selection is not allowed if the address is added from ENS.

<img width="809" src="https://github.com/status-im/status-mobile/assets/19339952/6698690a-345c-4519-b012-da4d467eb0c2">

### Design

[Link to Figma](https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=1395-60328&t=QFZQHEfCuyRyrDG5-1)

### Acceptance Criteria

- [ ] In the Save address bottom sheet, when user taps on preferences icon at the right of the address card, `Add network preferences` bottom sheet should be shown.
- [ ] "Add preferences" button at the bottom should start in a disabled state.
- [ ] User can enable and disable Mainnet, Optimism and Arbitrum networks.
- [ ] When user toggles a network, address suffix should reflect network preferences (`eth:` in blue if mainnet is enabled, `opt:` in red if Optimism is enabled, `arb:` in turquoise if Arbitrum is enabled).
- [ ] When preferences are modified, "Add preferences" button at the bottom should be enabled.
- [ ] When "Add preferences" button at the bottom is tapped, `Add network preferences` bottom sheet should be dismissed, preferences should be updated and reflected in Save address bottom sheet

**Comment by J-Son89** [comment]
related to this @briansztamfater - I created an issue just to implement the ui side of this -https://github.com/status-im/status-mobile/issues/17699  but we will need to hook it up properly to save address page etc 👍

**Comment by OmarBasem** [comment]
Hey @shivekkhurana, are you working on this issue? I see you linked it in a PR
