### ISSUE TITLE
Error Null is not an object (evaluating 'd.charAt')

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1699]
### Description

*Type*: Bug

*Note*: I can't reproduce the issue locally

*Summary*: An error Null is not an object (evaluating 'd.charAt') received from Instabug report . Error received when tapping the phone number setup

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/29774697-19365ec2-8c0b-11e7-8aba-2a150b601bc8.png)

### Additional Information

* Status version: 0.9.10-1-gc9335d0b (1558)
* Operating System: Android OS Level 24
* Device samsung SM-G935F
* Instabug report https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/855
* iOS 10.3.2/ iPhone 6s  https://dashboard.instabug.com/applications/status/beta/bugs/427
*  iOS 10.3.2/ iPhone 7 Plus, Chinese UI https://dashboard.instabug.com/applications/status/beta/bugs/505

**Comment by annadanchenko** [comment]
Phone feature is removed
