### ISSUE TITLE
Create missing preview-list variants

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17008]
# Feature Issue

The preview list component lacks of some variants that are expected to be used for other components (such as context-tags)

### Description

Implement all the variants for the Preview list component. 

Designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2214-33298&mode=design&t=wj1DftANRfnzMHB1-4

### Acceptance Criteria

The resulting API must  match figma name properties and follow our best practices (use the `wit-theme` function, component tests, etc).

### Notes

The component has some variants already implemented, but feel free to refactor or just extend the implementation.
If the current API is not matching figma, we should fix the API and its uses across the code.

**Comment by smohamedjavid** [comment]
Closing the issue as it's fixed in PR: https://github.com/status-im/status-mobile/pull/17051
