### ISSUE TITLE
New wallet shows default `...` until sync is done

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1701]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be warned that sync is not finished yet when looking at wallet so that I don't get confused by the display of `...` in place of my ETH amount.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Show a warning that the blockchain is still syncing

#### Actual behavior
[comment]: # (Describe what actually happened.)
Currently the wallet shows `...` when the blockchain is still syncing

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status (on a fresh install)
- Recover or create account
- Check wallet before the blockchain is synced

**Comment by oskarth** [comment]
Proposal:

New design: ![image](https://user-images.githubusercontent.com/1552237/29814590-2a7d0c6e-8cae-11e7-8445-326da24a4327.png)

- Display this when we never synced, and possibly when we haven't synced for a long time
- When pull to refresh, display progress next to amount like design before

**Comment by yenda** [comment]
There is a warning when wallet is syncing now
