### ISSUE TITLE
App crashes when opening community with banner image.

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#17017]
# Bug Report
As a user, I want to be able to access communities with a banner image
When I am invited to a community with a banner image and I go there, I get this error

## Problem 
Can't access a community with banner image
![image](https://github.com/status-im/status-mobile/assets/33176106/778308ff-3d1d-464c-b26a-208a76b5a76a)

[comment]: # (A problem description)

#### Expected behavior
Shouldn't receive this error

#### Actual behavior
Receiving this error

### Reproduction

1. Create a community from desktop
2. Add a user from mobile to it by copying mobile public key and adding user from desktop
3. Open community invitation on mobile

### Additional Information

- Status version: latest develop

**Comment by pavloburykh** [comment]
@ibrkhalil I am not reproducing the described crash on my Android 12, Samsung Galaxy A52

https://github.com/status-im/status-mobile/assets/97245802/5de63dee-0bcd-4ef6-9049-99da57be5996

Mobile version: Android nightly 22/08/23

Desktop version: release 0.13.3

**Comment by VolodLytvynenko** [comment]
Can't reproduce this issue either. Able to open and join the communities with banner

![image](https://github.com/status-im/status-mobile/assets/52490791/2c604b85-4f81-427d-838e-b24af1130632)

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro max, IOS 16

### ENV: 
Android nightly 22/08/23

**Comment by ibrkhalil** [comment]
Can you try in syncing or sign-in when you press the info page-nav right action?

**Comment by pavloburykh** [comment]
> sign-in when you press the info page-nav right action?

What do you mean by "sign-in when you press the info page-nav right action"?

Would be helpful if you provide exact steps or video of reproduction.

**Comment by ibrkhalil** [comment]
I think this resolved itself, Me and @ulisesmac were facing this issue at some point but I don't think it's reproducible anymore.
