### ISSUE TITLE
Implement "Bottom Actions" component 

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#17028]
# Feature

Implement the "Bottom Actions" component in the quo2 component library.

⚠️ NOTE: The component has the property `scroll` in Figma. Please exclude that prop for this issue, as we have an issue with Blur. We will implement it once we resolved the Blur issue.

<img width="500"  src="https://github.com/status-im/status-mobile/assets/19339952/2b013385-000e-4e66-b9f5-116f809caa75">

### Designs

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2500%3A41324&mode=design&t=Fx9sPvHE1N10Zx4e-1)

### Acceptance Criteria:

- Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
- Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)
- Should add an export from the `quo2.core` namespace
- Add a preview for this component under the `drawer` category in the Quo2 preview screen

**Comment by ulisesmac** [comment]
Keep in mind that this component should be able to contain a slide-button:
![image](https://github.com/status-im/status-mobile/assets/90291778/f907b18c-21a4-4d6f-a9ad-f1978e8d658e)

I think we should add a note about what components are expected bottom-actions to contain, or even better, add the designs for those possible components. 
As developer, we may think that implementing the component as it's listed in the Design System is enough but this is not the case for this one.

CC: @cammellos @pedro-et

**Comment by J-Son89** [comment]
This can be closed now @tumanov-alex ? 🤔
