### ISSUE TITLE
Implement "Wallet Legacy" and "Wallet Multichain" variants in the "Share QR Code" component

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#17023]
# Feature

Implement the following variants in the `Share QR Code` component:
- Wallet Legacy
- Wallet Multichain

<img width="550" src="https://github.com/status-im/status-mobile/assets/19339952/51d9e643-01c9-47d9-8ff9-f45f45f250cb">

### Designs

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1338%3A34510&mode=design&t=qU6dXrSmurRpwPXT-1)

### Acceptance Criteria:

- Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
- Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)

**Comment by smohamedjavid** [comment]
Depends on #17026

**Comment by ulisesmac** [comment]
I'll start working on this issue since
- #17026

already has a PR

**Comment by ulisesmac** [comment]
Depends on:
- #16329

I'm solving it and will take this one once it's ready

**Comment by OmarBasem** [comment]
Hey @ulisesmac,

Have you started working on this one already? I started working on this but did not notice this issue. If you already started then I can discard my branch.

**Comment by ulisesmac** [comment]
> Hey @ulisesmac,
> 
> Have you started working on this one already? I started working on this but did not notice this issue. If you already started then I can discard my branch.

Hey @OmarBasem 

Yes, I already started. I'm planning to create a PR soon 👍
