### ISSUE TITLE
Add possibility to remove user-selected avatar so default one will be displayed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1703]
### Description

*Type*: Feature

*Summary*: During the weekly call was encountered that it would be useful for user to have possibility to delete avatar which he has set up (using photo or custom picture) so randomly generated picture is shown again.

#### Expected behavior
User is able to delete avatar. Default picture is shown as result of deletion

**Comment by asemiankevich** [comment]
@denis-sharypin are we still up for it?

**Comment by denis-sharypin** [comment]
Let's make a small bounty of it:
1. If you have a custom user picture you will see a menu where on top of the list we have `Remove current` picture option  (on the right)

2. If you don't have a custom picture or you have deleted it and open this menu again you will see our current context menu. (on the left)

![remove current photo](https://user-images.githubusercontent.com/6559881/37643828-63060bf8-2c54-11e8-8adf-23ed02a1f53c.jpg)

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/4108 is duplicating this, closing this old one
