### ISSUE TITLE
[Android] 'facebook.react.bridge.JSApplicationIllegalArgumentException' Error after login/log out

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17036]
Unfortunately, there are no exact steps on how to reproduce this issue. However, once it occurs for a particular user, it will be repeated then after each attempt to log in and log out.

### Steps to reproduce:
1. Create an account
2. Add any contact
3. Send any message in 1-1 chat
4. Leave the device in the background for 2-3 minutes.
5. Log out -> log in

### Actual result:
The error is shown after login or log out

https://github.com/status-im/status-mobile/assets/52490791/4151b231-f5b3-4bbd-952e-54e9f5de5414

### Expected result:
The user is logged in without error

### Additional result:
Initially, I thought this issue might be related only to one account, possibly due to wrongly generated keys for that specific account. However, I was able to reproduce this problem on three newly created accounts.

### Device:
Real device: Pixel 7a, Andorid 13

### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12367708/android_logcat.txt)

**Comment by cammellos** [comment]
```
                         at java.lang.Thread.run(Thread.java:1012)
                 Caused by: java.lang.IllegalArgumentException: Unknown value: small
```

**Comment by VolodLytvynenko** [comment]
HI @cammellos the issue is not reproducible anymore. looks like it was fixed after recently reverting https://github.com/status-im/status-mobile/pull/17039
