### ISSUE TITLE
Wallet: Create account screen

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17059]
# Feature Issue

### Description

Implement the basic flow for the screen to add the account details:
![image](https://github.com/status-im/status-mobile/assets/90291778/8ded478c-423f-4318-8c5f-2afd89b292b6)

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-132380&mode=design&t=ce0nlAaMOlwFE1XF-4

This issue only considers the flows contemplated in the figma link and it doesn't include the emoji picker/selector, it will be addressed in a separate issue (#17058).

- We don't need to handle the action when the "slide to create account" button is activated.

### Acceptance Criteria

- The user is able to set the account's name
- The user is able to pick a customization color
- The screen is looking as designs
- The data to be sent is prepared so that when a following issue has to send it it's in a single place and ready. 

### Notes

Related issue:
- #17058

Depends on:
- #17028

**Comment by ulisesmac** [comment]
@OmarBasem Since this screen depends on the Bottom Actions component, please make sure to create a follow up issue to add the Bottom Actions component to it once it's completed, also remember to add the label and board to the issue.

**Comment by OmarBasem** [comment]
@ulisesmac there is a follow up https://github.com/status-im/status-mobile/issues/17126
Updated it with the Bottom Actions component
