### ISSUE TITLE
Wallet: create account - emoji selector

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17058]
# Feature Issue

### Description

Implement the emoji selector flow to create an account:

![image](https://github.com/status-im/status-mobile/assets/90291778/bbf07db5-b001-4e4c-9020-fad29cf86469)
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-132496&mode=design&t=ce0nlAaMOlwFE1XF-4

### Acceptance Criteria

- The emoji picker is looking as designs
- the user is able to select an emoji and change it successfully.

### Notes

Depends on:
-  #17057

**Comment by Vinod-Mane3021** [comment]
![Screenshot 2023-08-21 223915](https://github.com/status-im/status-mobile/assets/92261457/331f97d7-9b04-4cf6-b682-48781136e84e)

Figma file not opening

**Comment by ulisesmac** [comment]
Hello @Vinod-Mane3021 
The figma file link is still working, might it be related to permissions?
CC:  @J-Son89

**Comment by J-Son89** [comment]
I think this might be a duplicate - @smohamedjavid wdyt? 
Can you close if so 🙏

**Comment by smohamedjavid** [comment]
Yes, this is a duplicate. 
Thanks for spotting this!

**Comment by smohamedjavid** [comment]
Duplicate https://github.com/status-im/status-mobile/issues/17057
