### ISSUE TITLE
Remove the option to choose recipient in 1-1 chat when sending funds

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1705]
### Description

*Type*: Bug

*Summary*: The option to choose recipient in 1x1 looks unnecessary because there is no other participants in this chat, so funds will be send directly to the person whom you have 1x1 chat with

#### Expected behavior
Eliminate the option to choose recipient in 1x1 chat

### Reproduction

- Open Status
- Add account to contacts list
- Go to 1x1 chat and /send

### Additional Information

* Status version: 0.9.10-34-gf07eff4a+
* Operating System: Android, iOS

![image](https://user-images.githubusercontent.com/28752642/29816959-e7fd7c6e-8cbe-11e7-96f1-4d80e6d22b09.png)

**Comment by annadanchenko** [comment]
done in 0.9.12
