### ISSUE TITLE
Drawer to add account

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17056]
# Feature Issue

### Description

Implement the following drawer:

![image](https://github.com/status-im/status-mobile/assets/90291778/14fb37e3-28b4-4db3-9166-8be904a56896)

that is displayed when the user wants to add a new account.

Figma: 
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2041-448903&mode=design&t=ce0nlAaMOlwFE1XF-0

Please check that the overlay behind the drawer is looking as expected, if it's not, we must correct it before solving this issue.

### Acceptance Criteria

- The drawer is looking as designs
- The drawer is shown when the user presses on the add address icon 

[extra]
- Create the skeleton empty screens and navigate to them when the user presses the options in the drawer (add account, add address to watch)

### Notes
(feel free to add more dependencies if required)
Depends on 
- #17021

**Comment by OmarBasem** [comment]
Already implemented in https://github.com/status-im/status-mobile/pull/17118
