### ISSUE TITLE
Wallet: Emoji picker

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17057]
# Feature Issue

### Description

Implement the emoji picker drawer:
![image](https://github.com/status-im/status-mobile/assets/90291778/91a0b4c7-327f-4f4e-be03-74d43198ecf0)

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2090-503817&mode=design&t=ce0nlAaMOlwFE1XF-4

This component isn't created as part of our quo2 library, but we must align with the design team to check if we will reuse it and ask for complete specifications about it.

### Acceptance Criteria

- The search is implemented
- All the buttons in the component are working
- A preview screen is also implemented or a way to easily test it
- It receives a `:on-select` (or similar named) callback so that we can get access to the selected item.

**Comment by J-Son89** [comment]
cc @smohamedjavid as I think you already have some context/knowledge on this 👍

**Comment by smohamedjavid** [comment]
> This component isn't created as part of our quo2 library, but we must align with the design team to check if we will reuse it and ask for complete specifications about it.

@ulisesmac will also be used in the composer. So, we need to build it as a global (bottom) sheet.

The Status Desktop app uses the Unicode v14 emoji set. We can use the same set on mobile, and create this emoji picker. We can't use external libraries as they are difficult to style and won't match our design.

I can pick up this issue 👍 

On the same note, as you can see from the screenshot attached to the issue, the emojis are using [Twemoji](https://twemoji.twitter.com/). I'm researching Twemoji integration on mobile https://github.com/status-im/status-mobile/pull/17072. There are a few pitfalls to the emoji library which I'm exploring.

**Comment by smohamedjavid** [comment]
Depends on the `Showcase nav` https://github.com/status-im/status-mobile/issues/17096 and `Divider label` https://github.com/status-im/status-mobile/pull/17035

**Comment by ulisesmac** [comment]
Thanks for adding details on it @smohamedjavid  😄
