### ISSUE TITLE
All replies and mentions are removed in AC for receiver after sender removes the last message in community chat

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17052]
### Steps to reproduce:
1. `User_A` and `User_B` are both in the same community.
2. `User_A` sends several replies or mentions to `User_B`.
3. `User_A` sends one more message and then deletes it using the 'delete for everyone' option.
4. `User_B` checks the AC.

### Actual result:
All mentions and replies in the AC are removed for `User_B`.

### Expected result:
Mentions and replies should not be removed from the AC after the last message is deleted.

### Additional info:
This issue is similar in group chats, with the exception that only replies are removed from the AC. Mentions are not removed and

**Comment by cammellos** [comment]
@ajayesivan any update on this?

**Comment by ajayesivan** [comment]
@cammellos unread-notification count & notification list values coming from status-go API is wrong. I'm looking into the `DeleteActivityCenterNotificationForMessage` function in status-go.

**Comment by churik** [comment]
still valid and very weird bug (checked on nightly 21/06/24)

**Comment by yqrashawn** [comment]
![CleanShot 2024-07-15 at 13 22 13@2x](https://github.com/user-attachments/assets/6b710492-aadf-46f3-9a7d-c400d17aedb0)

so all notifications have the same last-message
and status-go delete notification by matching 
`to-be-deleted-message-id`
with both `notification message id` and `notification last-message id`
code at 

https://github.com/status-im/status-go/blob/131cfe7b3daec24f2ea56bdfa3b26ab931ea7a0f/protocol/activity_center_persistence.go#L62-L70

```go
	for _, notification := range notifications {
		if notification.LastMessage != nil && notification.LastMessage.ID == messageID {
			withNotification(notification)
		}

		if notification.Message != nil && notification.Message.ID == messageID {
			withNotification(notification)
		}
	}
```

**Comment by yqrashawn** [comment]
last message check is added at https://github.com/status-im/status-go/pull/2854
in order to fix https://github.com/status-im/status-mobile/issues/13933

**Comment by yqrashawn** [comment]
next up: https://github.com/status-im/status-go/pull/5520#issuecomment-2270223309
