### ISSUE TITLE
user avatar broken in preview-list

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17055]
# Bug Report

## Problem 
With the recent changes to the `user-avatar` component (quo2.components.avatars.user-avatar.view), the preview-list component is broken.

![image](https://github.com/status-im/status-mobile/assets/90291778/f6e78e23-1343-472f-998d-5b5b07a8b8a5)

#### Expected behavior
Correctly display the avatars.

#### Actual behavior

Nothing but the counter is displayed

### Reproduction

1. Navigate to quo2 preview screens -> list-items -> preview-lists
2. The component is not displayed correctly

### Additional Information

- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

This issue has been rised because the PR for `context-tags` relies on the user-avatar component for some variants, after rebasing on the latest changes of user-avatar, the component layout have changed and is no longer displayed.

Probably the causing PR is
- #16193

**Comment by smohamedjavid** [comment]
The props for the user avatar component need to be updated. 
There are no issues with the components.
I fixed it in the PR https://github.com/status-im/status-mobile/pull/17051 👍

**Comment by ulisesmac** [comment]
> The props for the user avatar component need to be updated. There are no issues with the components. I fixed it in the PR #17051 👍

@smohamedjavid Has the user-avatar component changed to match figma API? 
if not, I think the user-avatar should keep its old API calls as valid instead of updating every component using it.

Also, the uses should have been updated in the same issue where the API changed (or a direct follow-up).

**Comment by smohamedjavid** [comment]
> @smohamedjavid Has the user-avatar component changed to match figma API?
> if not, I think the user-avatar should keep its old API calls as valid instead of updating every component using it.
>
> Also, the uses should have been updated in the same issue where the API changed (or a direct follow-up).

Apologies @ulisesmac,

I was reading the issue in the context of the Preview-list component. 

You are right. The user avatar component is yet to be updated to match Figma APIs. The user avatar component broken is NOT due to the preview-list component. 

The recent changes https://github.com/status-im/status-mobile/pull/16193 on User Avatar have refactored the `source` prop of the image component inside the `user-avatar` component. The mock images we pass from resources (for preview) are rendered trying to render as a remote image (through `:uri`) and fail.

I have added another check in user-avatar to bring back support to render the mock images for testing purposes 👍 

PR: #17051 / Commit: 2ee75852620a8890ac116459410c983a42dd4ab6

**Comment by ulisesmac** [comment]
> > @smohamedjavid Has the user-avatar component changed to match figma API?
> > if not, I think the user-avatar should keep its old API calls as valid instead of updating every component using it.
> >
> > Also, the uses should have been updated in the same issue where the API changed (or a direct follow-up).
> 
> Apologies @ulisesmac,
> 
> I was reading the issue in the context of the Preview-list component. 
> 
> You are right. The user avatar component is yet to be updated to match Figma APIs. The user avatar component broken is NOT due to the preview-list component. 
> 
> The recent changes https://github.com/status-im/status-mobile/pull/16193 on User Avatar have refactored the `source` prop of the image component inside the `user-avatar` component. The mock images we pass from resources (for preview) are rendered trying to render as a remote image (through `:uri`) and fail.
> 
> I have added another check in user-avatar to bring back support to render the mock images for testing purposes 👍 
> 
> PR: #17051 / Commit: 2ee75852620a8890ac116459410c983a42dd4ab6
> 
> 
> 

Thank you so much! :)
 @smohamedjavid

**Comment by smohamedjavid** [comment]
Closing the issue as it's fixed in PR: https://github.com/status-im/status-mobile/pull/17051
