### ISSUE TITLE
'Join' instead of 'Request to join' button when owner node is offline at the moment of sending the request

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17065]
Follow up for https://github.com/status-im/status-mobile/pull/16917

### Steps:
1. `Owner node` creates the opened community 
2. `Owner node` shares community to `User_B`
3. `User_B` opens community

### Actual result: 
The "Join" button is displayed on the Community Overview and the Rules of Community overlay.
![image](https://github.com/status-im/status-mobile/assets/52490791/119b6836-987c-4f6e-9ca9-3dec0db232f4)

![image](https://github.com/status-im/status-mobile/assets/52490791/796acc0e-3f7e-4733-9399-e987a216abfc)

### Expected result:
Regardless of whether the owner node is online or offline, the "Request to Join" button should always be displayed on the opened community and the community rules overlay.

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7035-462899&mode=design&t=RbgVOzUoHQAFvq8U-0

**Comment by jo-mut** [comment]
Closing this as the necessary updates have been merged in #17094
