### ISSUE TITLE
Wallet: Account details screen

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17060]
# Feature Issue

### Description

Implement the screen to see the details of a recently added wallet account:
![image](https://github.com/status-im/status-mobile/assets/90291778/6da31b5d-7342-42b0-9cd8-031144ac3b12)

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=711-199027&mode=design&t=ce0nlAaMOlwFE1XF-4

### Acceptance Criteria

- The back button returns the user to the main wallet screen.
- It is looking as designs
-  Please add a dummy callback with an alert to non working buttons.

### Notes

- Depends on
- #16982
-  #17005

**Comment by OmarBasem** [comment]
@tumanov-alex closing this issue as it is already implemented https://github.com/status-im/status-mobile/pull/17077
