### ISSUE TITLE
Processing information banner is shown when community owner is offline

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17066]
Follow up for https://github.com/status-im/status-mobile/pull/16917

### Steps:
1. User A shares opened the community to User B
2. User A goes offline
3. User B requests to join to community

### Actual behavior:
A processing information banner is shown when a request is made to join an opened community while the community owner is offline.
![image](https://github.com/status-im/status-mobile/assets/52490791/acddaf7c-6a90-4597-8979-f78f027e41a1)

### Expected behavior
The processing information banner should not be shown regardless of whether an opened or closed community is requested.
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7199-474795&mode=design&t=RbgVOzUoHQAFvq8U-0

**Comment by cammellos** [comment]
Closing this as not relevant, as discussed with design
