### ISSUE TITLE
App crashes when opening Find sync code/How to scan screen (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17067]
Reproducing on Android 12, Samsung Galaxy A52

**Steps:** 

1. Open Sync page
2. Tap Find sync code or How to scan button
3. Observe the result

**Actual result:** app crashes

[Status-debug-logs (52).zip](https://github.com/status-im/status-mobile/files/12395253/Status-debug-logs.52.zip)

https://github.com/status-im/status-mobile/assets/97245802/d4da1847-0434-43d2-9a95-744f602b5891

**Expected result:** Find sync code/How to scan is opened
### Additional Information

- Status version: nightly 
- Operating System: Android

**Comment by ajayesivan** [comment]
@pavloburykh I'm unable to reproduce this issue after [this commit](https://github.com/status-im/status-mobile/commit/0f7e98cbe22f436b9d0f82bb8ca7baa32b6c941c). Could you please check the latest develop and confirm whether this issue has been solved.

**Comment by pavloburykh** [comment]
> @pavloburykh I'm unable to reproduce this issue after [this commit](https://github.com/status-im/status-mobile/commit/0f7e98cbe22f436b9d0f82bb8ca7baa32b6c941c). Could you please check the latest develop and confirm whether this issue has been solved.

Hi @ajayesivan! You are right, issue seems to be resolved. Closing it.
