### ISSUE TITLE
Wallet: Prepare re-frame events to call status-go to create an account

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17061]
# Feature Issue

### Description

We must make sure that we have the entire re-frame events to pass create a new wallet account.
The flow is the following:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-134934&mode=design&t=ce0nlAaMOlwFE1XF-4
![image](https://github.com/status-im/status-mobile/assets/90291778/b45308dc-6a9c-4cfe-bc33-e750a9b9edaf)

We proobably would need to know about the status-go endpoints and the way to call them.

### Acceptance Criteria

- New re-frame events are created to add a new wallet account
- They can be tested from the REPL
- Please include examples of the creation in the PR related

### Notes

If there's a missing feature, please create an issue and reference it in this section.

**Comment by J-Son89** [comment]
I believe this is a duplicate/implemented now
