### ISSUE TITLE
Refactor `system-messages` component

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17076]
# Probelm
The `system-messages` component is not implemented as per the [guidelines](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md).

Design: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=3905-82812&mode=design&t=bedkcdghlsQLuWJV-4

Current implementation path: `src/quo2/components/messages/system_message.cljs`

- Make sure this component is being rendered as expected and split the code into `style` and `view` namespaces.
- Update this component to use the with-theme function.
- Add component tests.

# Acceptance Criteria
- Match component api's with Figma
- Component is rendered as expected.
- Quo2 preview
- Update component usages if required
- Code has been refactored.
- Component tests.

**Comment by churik** [comment]
Closing as not planned and due to the lack of activity.

Reopen if still relevant.
