### ISSUE TITLE
[Android] "Jump to" button not responding in chat after app returns from background

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17079]
introduced by https://github.com/status-im/status-mobile/pull/16981

### Steps:
1. Open any chat.
2. Send the app into the background. (background should be active for at least 1 minute)
3. Return the app from the background.
4. Tap the 'Jump to' button.

### Actual Result:
The "Jump to" button does not redirect to the intended screen after being tapped.

https://github.com/status-im/status-mobile/assets/52490791/27594b75-b3e7-476c-b886-5a822b9536a2

### Expected Result:
The "Jump to" button should correctly redirect to the "Jump to" screen after being tapped

### Devices:
- Real device: Pixel 7a, Android 13
- Android Emulator: Pixel 6 Pro API 31

### logs:

[Status.log](https://github.com/status-im/status-mobile/files/12406772/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12406773/geth.log)

CC: @Parveshdhull

**Comment by Parveshdhull** [comment]
hi @VolodLytvynenko, Thank you very much for reporting the issue. I tried above steps in `Pixel_5_API_30` and `S21 FE` Android 13 and was unable to reproduce issue.

https://github.com/status-im/status-mobile/assets/17097240/4539180e-babd-4bea-9f6a-5d2d69ba49cd

**Comment by Parveshdhull** [comment]
Hi @VolodLytvynenko, Thank you very much for reporting the issue.
Please can you upload a video with the full process for reproduction?
Not sure If I am missing something, but using the above steps I am not able to reproduce the issue.

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko, Thank you very much for reporting the issue. Please can you upload a video with the full process for reproduction? Not sure If I am missing something, but using the above steps I am not able to reproduce the issue.

Hi @Parveshdhull, unfortunately, we don't have exact steps to reproduce this issue. In my experience and during e2e tests, the "jump to" functionality becomes unresponsive after the app has been in the background for a certain amount of time. 

Initially, it took only around 1 minute to trigger this issue, but now I am not able to reproduce it either with such steps. It seems the issue can occur even without enabling the background.

In this case, as on record, it reproduced when a user taps the "jump to" button after receiving several messages from another user, even without backround enabling. However, even these steps are not consistently exact, seems like this issue occurs randomly


https://github.com/status-im/status-mobile/assets/52490791/c13b7057-f732-4171-97ab-a80eed1a0c92



Probably logcat logs can help:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12409053/android_logcat.txt)

**Comment by Parveshdhull** [comment]
hi @VolodLytvynenko, I tried this method too but was not able to reproduce the issue myself.
If we don't have exact steps to reproduce the issue, but it is quite often reproducible by qa team then please let me know. 
Because, In that case, I can create a PR and we can try a few fixes.

**Comment by Parveshdhull** [comment]
@OmarBasem, any thoughts, why this issue might be happening?

**Comment by Parveshdhull** [comment]
Not sure, but problem might be related to z-index.
Please can you check out https://github.com/status-im/status-mobile/pull/17085, and let me know if this fixes the issue.

**Comment by OmarBasem** [comment]
@Parveshdhull honestly I am not sure, seems random. Since it happens on Android only it could be because of the `z-index` as you said
