### ISSUE TITLE
Unable to scroll input to the bottom after removing links preview in composer (IOS)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17084]
Reproducing on IOS 16.6, iPhone X

**Steps:** 

1. Open any chat
2. Paste data containing links into composer
Example of data: 
```
Resolved preview 
Bsbd
Sbdb
HShs
ShshS

https://github.com/status-im/status-mobile/pull/15253

https://m.youtube.com/watch?v=Je7yErjEVt4

https://www.youtube.com/watch?v=OYjZK_6i37M&pp=ygUIZ29kc21hY2s%3D

https://youtu.be/Mp0jlNquSnM

https://bit.ly/41ScFYY

https://youtu.be/Beb8cktBTxY
```
3. Close the composer
4. Remove links previews from composer
5. Expand the composer
6. Try to scroll data in the input field to the bottom
7. Observe the result

**Actual result:** unable to scroll to the bottom

https://github.com/status-im/status-mobile/assets/97245802/c06c0bbd-e63d-4ed7-b10c-e8a516f30a4a

**Expected result:** able to scroll to the bottom
### Additional Information

- Status version: nightly 
- 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
I think this is better picked up by someone familiar with latest implementation of composer.

**Comment by cammellos** [comment]
@alwx any update on this one?

**Comment by ilmotta** [comment]
@pavloburykh, do you know if this issue always existed? I don't recall seeing this bug before. But good thing @alwx already picked it up

**Comment by pavloburykh** [comment]
> @pavloburykh, do you know if this issue always existed? I don't recall seeing this bug before. But good thing @alwx already picked it up

@ilmotta I am not sure how long does this issue exists or when it has been introduced. But I can say for sure that it is still reproducible now so needs to be addressed.

**Comment by alwx** [comment]
Would take a closer look and hopefully finish it this week.

**Comment by churik** [comment]
@alwx 

please, unassign it if you're not working on it

**Comment by alwx** [comment]
Sorry, it had much lower priority compared to the rest so it ended up being postponed. Unassigning because there are other issues now as well.

**Comment by churik** [comment]
Not reproducible anymore on nightly 21/06/24 (IPhone 14, Google Pixel7)
