### ISSUE TITLE
Chat module refactoring

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#1709]
Refactor chat module so the logic is cleaner and easier to follow, user atomic events instead of long event chains and cut down code-redundancy. Build atop of #1671

**Comment by annadanchenko** [comment]
cant use the app: "'Property' must be of type: string" popup is shown if run app 1st time. if close the popup then no password request is shown. same after re-starting the app.
https://app.testfairy.com/projects/4803622-status/builds/6490485/sessions/6/?accessToken=SBvlNMBBszYOogxjtvbLNMmaQHY from 00:08
 0.9.10-45-g64b83e78+ both android and ios
![screenshot_20170904-163245](https://user-images.githubusercontent.com/6584810/30028784-18171084-918f-11e7-8530-1fe021e87569.png)

installed from Branch: feature/chat-module-refactoring-#1709
Android: https://i.diawi.com/nPLrKL
iOS: https://i.diawi.com/JEw7yp

**Comment by annadanchenko** [comment]
Tested ok in develop. Will be in 0.9.12 release
