### ISSUE TITLE
Discuss and implement top nav notifications for activity centre

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17102]
in the designs for top nav - https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=145-6203&mode=design&t=UpGe9fZrkJqebRul-4

there is a notification dot being used for new notifications and unread notifications. However in the application this is currntly not used and some clarifications are needed. 
Discuss with the design team what is expected here, update this issue and implement it accordingly

**Comment by ilmotta** [comment]
It's unclear to me what's the problem in this issue because we already implemented the AC unread indicator in 3 states. See issue https://github.com/status-im/status-mobile/issues/14851

I'm closing the issue for that reason.
