### ISSUE TITLE
Check and fix button blur

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17119]
There are some inconsistencies between the button blur in [this flow](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-132380&mode=design&t=ox4rOyYprrjcV9ww-0) and the [button blur designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=57-15962&mode=design&t=rDsHWeFzphsDrIoG-0). The blurred buttons in the top nav component have a background of `neutral-80-opa-5` and the reaction button has a blur of `white-opa-5`, meanwhile both buttons have the same exact properties.

It needs to be checked and fixed whether there is a mistake in the main button designs, or in the flow, or in our implementation.

Also, currently, the implementation would display a blurred button only when the background is of type `photo`. It should display blurred button when the background if of type `blur` also.

cc @J-Son89

**Comment by J-Son89** [comment]
@OmarBasem can we close this issue now?

**Comment by OmarBasem** [comment]
@J-Son89 I think that part is not fixed yet?

> Also, currently, the implementation would display a blurred button only when the background is of type photo. It should display blurred button when the background if of type blur also.

**Comment by J-Son89** [comment]
I'm not sure we actually want that. Let's check with the designers 👍

**Comment by J-Son89** [comment]
Discussed with @pedro-et, current button implementation is correct 👍
