### ISSUE TITLE
Button text is not vertically centered with size 24

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17125]
Designs: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=57-15962&mode=design&t=j8AjWV3NcPznKSHW-0

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, Please can you attach some screenshots? Issue is not clear by link, it redirects to all buttons.

**Comment by OmarBasem** [comment]
Hi @Parveshdhull, please check the button component in quo2 with size 24. The text is slightly moved up.
