### ISSUE TITLE
Wallet Create Account screen follow up

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17126]
Dependencies: 

- https://github.com/status-im/status-mobile/issues/17124
- https://github.com/status-im/status-mobile/issues/17122
- https://github.com/status-im/status-mobile/issues/17120

**Comment by J-Son89** [comment]
@OmarBasem what exactly is this issue? the description is a bit vague. Could you please include one of the epics which narrow down the scope too. e.g `E:Mobile Wallet Main Page MVP`

**Comment by OmarBasem** [comment]
@J-Son89 some components in the wallet Create Account screen need to be updated, then I need to update the screen. I added an epic tag
