### ISSUE TITLE
Quo2: Implement Settings Item component

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17124]
Update settings list component to match Figma designs:

- [ ] Should be able to accept avatar icon
- [ ] Should be able to accept subtitle
- [ ] Should be able to accept button with label
- [ ] Check for any other missing details

Designs: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1650-31097&mode=design&t=j8AjWV3NcPznKSHW-0

Edit: Component need to be reimplemented

**Comment by mohsen-ghafouri** [comment]
@OmarBasem It looks like the blur variant hasn't been implemented either. can you please check this too?

mentioned in my PR
https://github.com/status-im/status-mobile/pull/17133#pullrequestreview-1602058297
