### ISSUE TITLE
Implement "Bottom Actions" component

### ISSUE THREAD

**Issue by tumanov-alex** [status-im/status-react#17142]
Issue link: https://github.com/status-im/status-mobile/issues/17028

Implement the "Bottom Actions" component in the quo2 component library.

⚠️ NOTE: The component has the property scroll in Figma. Please exclude that prop for this issue, as we have an issue with Blur. We will implement it once we resolved the Blur issue.

![Image](https://user-images.githubusercontent.com/15213331/264106276-3abf88ff-97e8-4ce1-aa38-26fc20f827ec.png)

Designs
[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2500%3A41324&mode=design&t=Fx9sPvHE1N10Zx4e-1)

Acceptance Criteria:
Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)
Should add an export from the quo2.core namespace
Add a preview for this component under the drawer category in the Quo2 preview screen

Note: screens that use this component not as a quo2 component would have to be updated within this issue or in a follow up

**Comment by J-Son89** [comment]
@tumanov-alex this is a duplicate issue of https://github.com/status-im/status-mobile/issues/17028 - can we close one of them?
