### ISSUE TITLE
Spacing between last message and composer top edge is different from Figma

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#17144]
# Problem
The spacing is different from the proposed design
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=4966:121633&mode=design#539022831
## Implementation
Spacing needs to be adjusted to match Figma.

**Comment by churik** [comment]
Can be closed for now are Jump to was removed and app needs to be revised again
