### ISSUE TITLE
Delayed display of 'Add Unknown as contact to send a Message' text after joining opened community

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17153]
### Problem:
The text "Add unknown to send a message" is displayed 5-10 seconds after a user has joined an open community when they open the chat immediately after joining.

### Preconditions:
The users are just created

### Steps:
1. `User A` creates an open community and shares it with User B.
2. `User B Android` joins the community.
3. `User B Android` immediately opens the chat.

### Actual result:
The "Add unknown to send a message" text is shown 5-10 seconds after opening the chat.
![image](https://github.com/status-im/status-mobile/assets/52490791/fd1d61ba-b092-4331-9d29-668f6fb27321)
 
### Expected result:
Potential solutions:
- The chat should be opened without displaying the "Add unknown to send a message" text.
- Display a loading skeleton while the chat data is being loaded.
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3071-278296&mode=design&t=kSP2OocDNfuQ5IxV-0

### logs:
[Status.log](https://github.com/status-im/status-mobile/files/12484194/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12484195/geth.log)

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! 

Reopening this issue, as it is reproducible again. 

In fact we have 2 problems here:

### Problem 1 "Add Unknown as contact to send a Message" is displayed again until chat is loaded

[Status-debug-logs (62).zip](https://github.com/status-im/status-mobile/files/12671128/Status-debug-logs.62.zip)

![photo_2023-09-20 11 46 12](https://github.com/status-im/status-mobile/assets/97245802/1cfd9e63-0254-4bf5-a561-18d7dd5908b9)

https://github.com/status-im/status-mobile/assets/97245802/5ada92d4-b51c-4d89-87ec-2c1f279f0ea8


### Problem 2 Sometimes chat is not being loaded for >20 seconds or until re-login 
This issue appears to be blocker for our e2e. 

Here  is a [link to video](https://app.eu-central-1.saucelabs.com/tests/196d61de3d9148bdab81ea53990f89c1?auth=40b6753bec5289588dfb3009cf22d54d#96) from e2e run. User waits for chat to be loaded during 20 seconds. Chat has not been loaded and test has failed.

[logcat (7).log](https://github.com/status-im/status-mobile/files/12671102/logcat.7.log)
[TestCommunityMultipleDeviceMerged_geth1.log](https://github.com/status-im/status-mobile/files/12671103/TestCommunityMultipleDeviceMerged_geth1.log)
