### ISSUE TITLE
`Reveal` sync code is broken on Android (stays blurred) 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17156]
# Bug Report

#### Expected behavior
can see QR

#### Actual behavior

Uploading FILE 2023-08-31 13:59:32.mp4…

### Reproduction

1. Open Profile > Syncing> +
2. Reveal sync code, enter valid password

### Additional Information

- Status version: nightly 31/08/2023
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12485827/Status-debug-logs.zip)

**Comment by churik** [comment]
Upload video is not working in GH right now, can send in DM in case if it is required

**Comment by smohamedjavid** [comment]
`GetConnectionStringForBootstrappingAnotherDevice` method returns `{"error":"route ip+net: netlinkrib: permission denied"}` on Android.

> https://github.com/ipfs/kubo/issues/9513#issuecomment-1615341881

CC: @Samyoul @siddarthkay

**Comment by Samyoul** [comment]
Hmmm, ok I know a quick dirty way to fix this. It won't be pretty but it will stop this bug. 😭

**Comment by Samyoul** [comment]
I will do the quick fix and then I will add an issue to better address the problem.

Thank you @smohamedjavid for your research on this issue. We can implement https://github.com/wlynxg/anet when we have more time 🙈
