### ISSUE TITLE
Onboarding screens layout is broken

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17152]
Reproducing on IOS 16.6 iPhoneX; Android 12, Samsung Galaxy A52

1. Enable biometrics screen

![photo_2023-08-31 11 05 25](https://github.com/status-im/status-mobile/assets/97245802/09cc6a51-72e6-4265-b764-8e10b8010a44)

2. Enable notifications screen

![photo_2023-08-31 11 05 15](https://github.com/status-im/status-mobile/assets/97245802/b3a30f0a-606f-4c38-b3bb-29fdf4085180)

3. Welcome screen

![photo_2023-08-31 11 05 17](https://github.com/status-im/status-mobile/assets/97245802/0f58acb2-49c3-43a2-aa79-355305abb2a7)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
Related issue: https://github.com/status-im/status-mobile/issues/17151

**Comment by ajayesivan** [comment]
<img src="https://github.com/status-im/status-mobile/assets/19279756/06c1fe78-c70b-46fc-b5a4-dc46a001a2fa" width=350/>

**Comment by pavloburykh** [comment]
> <img alt="" width="350/" src="https://user-images.githubusercontent.com/19279756/264952180-06c1fe78-c70b-46fc-b5a4-dc46a001a2fa.png">

@ajayesivan thanks for pointing it out! cc @flexsurfer

**Comment by flexsurfer** [comment]
thanks, its the same component, should be fixed in all places
