### ISSUE TITLE
PNs delivery sometimes takes > 60 sec

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17160]
# Bug Report

## Problem 
e2e blocker - it fails a lot of cases from time to time, I do not think it makes sense to wait for PN > 60 sec.

Possible solutions:
- extend the wait time for PNs (worst way, will 
- check for message status (should be Delivered as far as I know) from sender and only after that start checking PNs

or to look at message reliability :)

#### Expected behavior
Can get PN

#### Actual behavior
I can see that the message was delivered at [14:35](https://app.eu-central-1.saucelabs.com/tests/0df04e279e954b47bebe8557f6b99160?auth=8edfc18798123b56cb6d764e5ce4a722#320) (it might be earlier, no option to check now), so it took > 90 sec for message to be delivered

### Reproduction

1. Device2: 12:45 > message is sent [step](https://app.eu-central-1.saucelabs.com/tests/1a7ca875d68c4598b96720807ab54d9c?auth=37ab191f1ae8ab05f069372f3fb8f7eb#224)
2. Device1: 12:51 > start to wait for PNs [step](https://app.eu-central-1.saucelabs.com/tests/0df04e279e954b47bebe8557f6b99160?auth=8edfc18798123b56cb6d764e5ce4a722#299)
3. Device1: 13:48 > No PN > device considers test as failed.

Device1 log (receiver): [logcat (23).log](https://github.com/status-im/status-mobile/files/12487073/logcat.23.log)
Device1 geth.log: [test_1_1_chat_push_emoji_geth1.log](https://github.com/status-im/status-mobile/files/12487079/test_1_1_chat_push_emoji_geth1.log)

Device2 log (sender): [logcat (22).log](https://github.com/status-im/status-mobile/files/12487055/logcat.22.log)
Device2 geth.log: [test_1_1_chat_push_emoji_geth2.log](https://github.com/status-im/status-mobile/files/12487076/test_1_1_chat_push_emoji_geth2.log)

### Additional Information

- Status version: nightly 31/08/23
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@cammellos experimented as we discussed - added in all tests waiting for the message to be sent from the sender side + increased PN waiting to 90 sec, and putting the app in the background + opening the notification center on the receiver side BEFORE sending the message.

Nothing helped.
Side effect: time increased from 30 mins to 36

Test results are [here](https://github.com/status-im/status-mobile/pull/17150#issuecomment-1702671598)

Example of failed e2e:
1) Receiver: put app to background [21:50](https://app.eu-central-1.saucelabs.com/tests/e43dfce78ca2496c82708efa152c0464?auth=41b2cb76f5222d0e96c61cf0dd54304a#456)
2) Sender: send message [21:54](https://app.eu-central-1.saucelabs.com/tests/cdaaeb213c694265abea5af1903fdaf1?auth=b1b2cb316be660e823f5f8553230d499#405)
Receiver: 
3) Receiver: start checking for new PN from [21:59](https://app.eu-central-1.saucelabs.com/tests/e43dfce78ca2496c82708efa152c0464?auth=41b2cb76f5222d0e96c61cf0dd54304a#457) to 23:29

Logcat for receiver:
[logcat (24).log](https://github.com/status-im/status-mobile/files/12498466/logcat.24.log)
Geth.log for receiver: 
[test_1_1_chat_text_message_delete_push_disappear_geth1.log](https://github.com/status-im/status-mobile/files/12498493/test_1_1_chat_text_message_delete_push_disappear_geth1.log)


Logcat for sender: 
[logcat (25).log](https://github.com/status-im/status-mobile/files/12498473/logcat.25.log)
Geth.log for sender: 
[test_1_1_chat_text_message_delete_push_disappear_geth2.log](https://github.com/status-im/status-mobile/files/12498496/test_1_1_chat_text_message_delete_push_disappear_geth2.log)

Code snippet:
```
self.device_2.just_fyi("Send one more message and check that PN will be deleted with message deletion")
        message_to_delete = 'DELETE ME'
        self.home_1.put_app_to_background()
        self.home_1.open_notification_bar()
        self.chat_2.send_message(message_to_delete)
        self.chat_2.chat_element_by_text(message_to_delete).wait_for_sent_state()
        if not self.home_1.get_pn(message_to_delete):
            self.home_1.click_system_back_button()
            self.home_1.status_in_background_button.click()
            self.errors.append("Push notification doesn't appear")
```

**Comment by cammellos** [comment]
```
09-01 12:16:29.080  6973  7095 E PushNotification: failed to send push notification
09-01 12:16:29.080  6973  7095 E PushNotification: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.getPerson(PushNotificationHelper.java:687)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.createMessage(PushNotificationHelper.java:697)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.addStatusMessage(PushNotificationHelper.java:753)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.handleConversation(PushNotificationHelper.java:187)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.sendToNotificationCentreWithPicture(PushNotificationHelper.java:210)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper$2.call(PushNotificationHelper.java:175)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationPicturesAggregator.finished(PushNotificationPicturesAggregator.java:132)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationPicturesAggregator.setBigPicture(PushNotificationPicturesAggregator.java:41)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationPicturesAggregator.setBigPictureUrl(PushNotificationPicturesAggregator.java:46)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.sendToNotificationCentre(PushNotificationHelper.java:180)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at im.status.ethereum.pushnotifications.PushNotification.presentLocalNotification(PushNotification.java:117)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at java.lang.reflect.Method.invoke(Native Method)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at android.os.Handler.handleCallback(Handler.java:883)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at android.os.Looper.loop(Looper.java:214)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
09-01 12:16:29.080  6973  7095 E PushNotification: 	at java.lang.Thread.run(Thread.java:919)
09-01 12:16:29.090  6928  7917 I appium  : channel read: POST /session/0686c217-5df0-498e-962b-552062b0dae2/element

```
Thanks @churik, indeed it's not a timing issue, the error is the above, is because we removed the identicon and the code still expects it in the push notification. that's easy to fix, I can have a quick look on monday. feel free to revert the tests changes.

**Comment by pavloburykh** [comment]
**UPDATE:**

bug can be manually reproduced on **IOS**. It turned out that PNs are not delivered at all. 

Reproduced on IOS 16.6, iPhone X. 

build: nightly 4 Sep, 2023.

**Comment by cammellos** [comment]
@pavloburykh they would be separate issues, the push notification code is different from IOS/Android, so unlikely they are related. Could you create a new issues adding as many details as you can please? (repro steps, geth.log sender, geth.log receiver)
thank you

**Comment by pavloburykh** [comment]
> @pavloburykh they would be separate issues, the push notification code is different from IOS/Android, so unlikely they are related. Could you create a new issues adding as many details as you can please? (repro steps, geth.log sender, geth.log receiver) thank you

sure, done https://github.com/status-im/status-mobile/issues/17173
