### ISSUE TITLE
Push notifications are not delivered to IOS app

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17173]
Reproducing on IOS 16.6, iPhoneX

**Preconditions:** User A - message sender (any device), User B - PN receiver, IOS device

**Steps:** 

1. User B enables PN notifications
2. User B backgrounds app
3. User A sends messages to any common chat with User B (1-1, group, community channel)
4. See if User B received PN about new message

**Actual result:** PN is not received by User B

[receiver_ios.zip](https://github.com/status-im/status-mobile/files/12513021/receiver_ios.zip)
[sender_android.zip](https://github.com/status-im/status-mobile/files/12513022/sender_android.zip)

https://github.com/status-im/status-mobile/assets/97245802/3548bc41-5d58-45c4-843a-16f8f8282540

**Expected result:** PN is received by User B

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@cammellos 
So it surprisingly looks like receiving PNs is limited like 1 app / per apple id.

Receiver stat per users

**User1:**
IPhone SE:
Status PR build - no PN
Status nightly build - no PN
IPhone 12:
Status PR build -  PNs +
**User2:**
Status PR build -  PNs +
Status nightly build - no PN
**User3:**
Status PR build -  no PNs
Status nightly build - PNs +

Moreover, after a while if you reinstall PR, PNs starting to be received in PR build, but at the same time stopped on nightly build (User2)
We couldn't get any other PNs on nightly builds again.

Sender logs (try to send messages to nightly, PNs never arrive there) :

[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12547766/Status-debug-logs.zip)

**Comment by churik** [comment]
@cammellos 

yesterday I got PNs to IOS app, today I can't 
Sender logs (Android) : 
[Status-debug-logs 2.zip](https://github.com/status-im/status-mobile/files/12584530/Status-debug-logs.2.zip)

**Comment by VolodLytvynenko** [comment]
NOTE for QA: 
- Check the mentions are displayed as a display name

**Comment by churik** [comment]
not completely sure how it should work and how to switch PN to work on PR build or to nightly;
works though on release build

**Comment by pavloburykh** [comment]
fixed by @cammellos on fleet side. Closing the issue.
