### ISSUE TITLE
Photos of others users are not visible in common chats unless users are not mutual contact

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17182]
# Bug Report

## Problem 
A global issue shared between desktop and mobile clients. When users are not mutual contacts, the profile picture is not visible even if it is set.

#### Expected behavior
Can see user pictures of other users by default for all users

#### Actual behavior
User1 (mutual contact with User2 and User3): 

![IMAGE 2023-09-05 11:00:15](https://github.com/status-im/status-mobile/assets/4557972/19d8bd37-3a23-44de-b9b0-2568aa501332)

User2 (mobile):

![IMAGE 2023-09-05 11:03:14](https://github.com/status-im/status-mobile/assets/4557972/84158c81-edf7-43d0-ba59-074402652b40)

User3 (desktop): 

![image](https://github.com/status-im/status-mobile/assets/4557972/e81fad02-260b-49fc-932f-5f98258caa20)

### Reproduction
**Prerequisites:** User1/User2 on mobile, User3 on desktop - all have profile pictures set

1. User1 (mobile): add User2 and User3 to contacts, confirm from User2 and User3 
2. User1 (mobile): start group chat with User2 and User3
3. User2 (mobile): send couple of messages
4. User3 (desktop): send couple of messages
5. check chat for all users

### Additional Information

- Status version: nightly 05.09.23 / master 04.09.23
- Operating System: Android, iOS, Mac OS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
This likely has to do with status-go, and it will have to do with how/when profiles pictures are published and how they are retrieved.

**Comment by cammellos** [comment]
Most likely is fairly complex, but if anyone wants to dig down it will give you a good insight on status-go

**Comment by churik** [comment]
it has been fixed in status-go, cannot reproduce it anymore
