### ISSUE TITLE
Connect Wallet Account Page to backend (basic)

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17183]
From the designs the wallet account page has some simple data based on the specific account
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1348-316521&mode=design&t=qVI9Rq3N7CCZkSRh-0

Implement the respective functionality needed to get this data from the backend
<img width="351" alt="Screenshot 2023-09-05 at 10 16 30" src="https://github.com/status-im/status-mobile/assets/22799766/8c446b9f-f9f0-433b-bc11-cb0201d2d628">

**Acceptance Criteria:**
- unit testing for subs and events (jest or cljs)
- reframe events are newly defined events and no code used from status-im.* namespaces is used

**Comment by smohamedjavid** [comment]
Completed in #17700
