### ISSUE TITLE
Overlaying elements on small screens on the 'Create Password' step

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17184]
# Bug Report

## Problem 

These overlapping elements don't look right.
@Francesca-G could you tell us if there is a design for small screens (since we're also going to support iPhone SE, for example)?
What should it look like in this case?

<img width="356" alt="Screenshot 2023-09-05 at 11 37 17" src="https://github.com/status-im/status-mobile/assets/67952253/1e4073d0-a3c4-42bb-96d0-90b58e8eea88">

<img width="362" alt="Screenshot 2023-09-05 at 11 36 06" src="https://github.com/status-im/status-mobile/assets/67952253/eef19cda-390a-4c6a-b4ef-479ee41f7609">

https://github.com/status-im/status-mobile/assets/67952253/715d61fd-cab0-4b56-a2be-d6ea30eaf514

### Reproduction

1. Create a password on a small-screen device

### Additional Information

- Status version: nightly 5/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
@qoqobolo, do you happen to know more or less which devices (iPhones/Androids) are affected by this problem, at least those that QAs verified? Thanks!

**Comment by qoqobolo** [comment]
> @qoqobolo, do you happen to know more or less which devices (iPhones/Androids) are affected by this problem, at least those that QAs verified? Thanks!

I can only reproduce it on iPhone SE I mentioned in the description, the video and screenshots were taken on this device as well. 
Unfortunately, we don't have an Android device with a small screen to test this case, but it may depend more on the screen size and not on the OS, but I'm not sure.

**Comment by ilmotta** [comment]
> I can only reproduce it on iPhone SE I mentioned in the description, the video and screenshots were taken on this device as well. Unfortunately, we don't have an Android device with a small screen to test this case, but it may depend more on the screen size and not on the OS, but I'm not sure.

Thanks @qoqobolo. Yes, that makes sense because the vast majority of Android devices are reasonably large to probably not suffer from the bug reported in this issue, even devices from 5 years ago.

**Comment by Francesca-G** [comment]
> These overlapping elements don't look right. @Francesca-G could you tell us if there is a design for small screens (since we're also going to support iPhone SE, for example)? What should it look like in this case?
> 
We have designs for it [here](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-90131&t=OeXkymndXikus74o-1) that cover this specific _Create Password_ screen with scroll behavior 👍
We also have the _Create Profile_ case [here](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-90600&t=OeXkymndXikus74o-1)

<img width="250" alt="Screenshot 2024-06-28 alle 10 45 11" src="https://github.com/status-im/status-mobile/assets/122543089/1479d69d-4985-482b-8b71-09d2ad0cad10">

**Comment by qoqobolo** [comment]
thank you @Francesca-G 🙏
cc @ilmotta
