### ISSUE TITLE
Connect Wallet Home Page to backend

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17181]
From the designs the wallet home page has some data based on the users accounts
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1348-316521&mode=design&t=qVI9Rq3N7CCZkSRh-0

Implement the respective functionality needed to get this data from the backend

<img width="321" alt="Screenshot 2023-09-05 at 10 03 50" src="https://github.com/status-im/status-mobile/assets/22799766/5b7b87f9-87eb-4997-9781-005884997295">

Acceptance Criteria:
- unit testing for subs and events (jest or cljs)
- reframe events are newly defined events and no code used from status-im.* namespaces is used

**Comment by smohamedjavid** [comment]
Superseded by #18196
