### ISSUE TITLE
Request message is not user-specified in group chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1719]
### User Story

As a user I want my request messages to be specified to the person whom I requesting the funds from

### Description

*Type*: Bug

*Summary*: In a group chat any member can click on the request message and send funds even the request message was sent to specified user

#### Expected behavior
Make the request message personalized so no one else can send the TXN except the person I am requesting the funds from

#### Actual behavior
Anyone in group chat can click the request message and proceed

### Reproduction

- Open Status
- Sync app
- Create group chat
- As contact A send /request message to contact B
- As contact C click the /request message and send the funds

### Additional Information

* Status version: 0.9.1-36-g9a06417b+
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
@denis-sharypin would you mind to look into this ? Probably it will be redesigned soon? What is the design of this behavior ?

**Comment by denis-sharypin** [comment]
I need help from @chadyj  and @hesterbruikman for this. More like a product decision. 
My question would be even: do we want to show 1-to-1 transactions for everyone in a group chat?

**Comment by hesterbruikman** [comment]
I would say yes; even though it feels undesireable. It is a logical result of starting a 1:1 transaction within a group chat. Also, it gives the highest level of user control.

That said, my gut feeling is that people will switch to 1:1 chat for transactions and it needs to be easy to select a group chat member to start a 1:1 chat.

**Comment by denis-sharypin** [comment]
@asemiankevich Give your confirmation for `Expected behavior`.  Send and request messages should be tappable only for a user to whom it refers.

**Comment by asemiankevich** [comment]
@denis-sharypin yes, that is what i expect. I think it will be done some day soon? Seen it somewhere in mocks

**Comment by denis-sharypin** [comment]
@asemiankevich, AFAIK @andmironov is working on chat

**Comment by andmironov** [comment]
i don't think it should be possible to make a request in a group chat. at least for now, before we dive deeper into this problem and figure out a smooth solution. 
For instance, if a request has been sent to a certain person in a group chat, there might me a 1-1 chat created. But this needs some research to be done

**Comment by asemiankevich** [comment]
lets close it for now. no gorup chats functionality now in app
