### ISSUE TITLE
iOS: app crashes when sharing an image message

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#17203]
## Problem 
When sharing an image message on iOS, the app crashes soon after selecting the image

#### Expected behavior
No crash

#### Actual behavior

https://github.com/status-im/status-mobile/assets/28704507/6750def7-295f-4199-a8f3-aee4dd1d8875

### Reproduction

1. Launch app
2. Open a 1-1 chat
3. Try to share an image message
4. As soon as you confirm to send the image, app crashes

### Additional Information
- Operating System: iOS

**Comment by ajayesivan** [comment]
I'm facing this same issue on the latest develop.
