### ISSUE TITLE
Incorrect mentions alignment

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17207]
**Steps:** 

1. Send text + mention in any chat
2. Check if mention text bottom is aligned to regular text bottom

**Actual result:**  mention text bottom is not aligned to the regular text bottom

**IOS:**
![photo_2023-09-06 16 29 39](https://github.com/status-im/status-mobile/assets/97245802/1a56f444-d603-4b89-98ca-23eb5562d69d)

**Android:**
![photo_2023-09-06 16 29 43](https://github.com/status-im/status-mobile/assets/97245802/2cec3c8c-54ee-41cf-a289-7a51800f59b8)

**Expected result:**

[Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=3188-50051&mode=design&t=4e6n7aaGkHHhVQtR-0)

<img width="793" alt="Design System for Mobile – Figma 🔊 2023-09-06 16-32-14" src="https://github.com/status-im/status-mobile/assets/97245802/6670fca8-645b-4d31-ac25-d19128d71f5b">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mohsen-ghafouri** [comment]
@pavloburykh It seems it only has an issue when the mention tag is at the beginning; the rest is fine. Can you confirm?

<img src="https://github.com/status-im/status-mobile/assets/71308738/a4264a05-3252-40e6-aff8-118ca4e396e6" width="375px"/>

**Comment by pavloburykh** [comment]
> @pavloburykh It seems it only has an issue when the mention tag is at the beginning; the rest is fine. Can you confirm?

@mohsen-ghafouri thanx for looking at the issue. In my case there is no dependency on mention's position in message. It is not aligned in all cases. 

Maybe it is OS dependent? Which OS and device are you using for testing? 
My are: Android 12, Samsung Galaxy A52; IOS 16.6 iPhoneX

## Android:

![photo_2023-09-06 21 43 27](https://github.com/status-im/status-mobile/assets/97245802/be475801-0e09-46a5-8b64-4e0086e3c08a)

## IOS:

![photo_2023-09-06 21 43 29](https://github.com/status-im/status-mobile/assets/97245802/8b6c26e6-c65c-4bdc-8bdf-295cb3475698)

**Comment by mohsen-ghafouri** [comment]
Yeah, in your screenshots the issue is really noticeable. My screenshot is related to iPhone 14 (iOS 16.4). I will investigate further.
