### ISSUE TITLE
Long Nicknames and display names overlap other chat elements

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17217]
### Steps:
1. `User A` sets a nickname for `User B`
2. `User A` checks the following places
3. `User B` sends a message to `User A`
4. `User A` checks in the following places:
  - In first line of message
  - In the chat preview
  - Contacts tab
  - 'new chat' overlay

### Actual result: 
Nickname overlaps the display name in the following places:
-  In first line of message
![image](https://github.com/status-im/status-mobile/assets/52490791/5538faa1-7c2d-47ca-b384-f2a8a96134e1)
-  In the chat preview![image](https://github.com/status-im/status-mobile/assets/52490791/3991a687-9e37-4017-bc3b-77c68960342a)
- Contacts tab
![image](https://github.com/status-im/status-mobile/assets/52490791/b09c807f-f8a2-4b6b-830e-3ce5a72e0034)
- 'new chat' overlay
![image](https://github.com/status-im/status-mobile/assets/52490791/2929eb07-33bc-4a1c-95e4-a8de1114f0bc)

### Expected result: 
The display name should be shown in the right part after the nickname.
![image](https://github.com/status-im/status-mobile/assets/52490791/04a1211a-9c12-4ef1-8f5a-b9964f165e0d)

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: Timestamps shown in the next line and overlapping messages if long capital case display name is set

### Steps:
1. Set a long display name during onboarding, making all letters in a capital case.
2. Send the message in any chat

### Actual result:
Timestamps are shown in the next line and overlap messages
![image](https://github.com/status-im/status-mobile/assets/52490791/ce68f09f-0b46-4030-b0a9-54f03ac9b96e)

### Expected result:
Potential solution:
- Timestamps should remain on the same line as the display name
- If there isn't enough space for  the timestamp, it might be more suitable to truncate the display name or the chat key

**Comment by ajayesivan** [comment]
Checking with the design team: https://discord.com/channels/624634427930312714/928625369542713396/1151461750684790816

[WAITING FOR DESIGN](https://discord.com/channels/624634427930312714/928625369542713396/1151476572566593556)

**Comment by ajayesivan** [comment]
[Message from Mario with the design](https://discord.com/channels/624634427930312714/928625369542713396/1153355805496709211)
Hello!
We've designed here a few scenarios with the nickname and the name. 
The idea is to give space to the nickname, but leave a max-width of 40px for the name (more or less 4-5 letters) when there're long nicknames
Also we updated the form design to show to the user the number of characters
You can see the designs here: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1731%3A399787&mode=design&t=jv63oFn44kLnUeBc-1
