### ISSUE TITLE
Wallet Design - Assets List - Adding assets

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1722]
Part of the Wallet UI update - part of the wallet's main screen #1523.

#### Wallet Asset - Adding asset
- [ ] I can add new asset by providing its details - contract address, token name, token symbol
- [ ] I can copy and paste from/to any of the 3 fields using system commands
- [ ] I can open asset's details
- [ ] I can edit existing asset
- [ ] I can delete existing asset from the list
- [ ] I cannot edit the default ETH asset!

Outbound flows should be presented but not required to be implemented in the scope if this issue (each flow will have its own acceptance):
- [ ] I can upload/update the asset icon from gallery
- [ ] I can paste link to the the asset's hi-res image

Mockup image for reference 
![image](https://user-images.githubusercontent.com/1944596/30076326-27f0df9c-9281-11e7-8cb3-c93e99d0c679.png)

The recent mockup can be found in Zeplin 
zpl://screen?pid=58aac7d018d4584d91998e79&sid=5987fd0a9560ffae5b4a3684

**Comment by jeluard** [comment]
A harcoded list of predefined ERC20 tokens will be used (including all necessary details to access relevant information).

**Comment by jeluard** [comment]
Missing:

* define a list of assets with associated details
* reflect assets impact on total

**Comment by asemiankevich** [comment]
@sla-shi please clarify the following:

> I can add new asset by providing its details - contract address, token name, token symbol 

**All the fields are required? Where I can find relevant info for valid combinations of all the 3 parameters to successfully enter an asset (like a list of possible assets? Are there any limitations by adding assets?**

 > I can copy and paste from/to any of the 3 fields using system commands

**Which commands exactly are mentioned there?**

**Comment by sla-shi** [comment]
I think we need to revisit the asset management UX in the coming design calls.

**Comment by geniusmaster33** [comment]
Is this story completely developed. or still the app supports only STT
