### ISSUE TITLE
Sync is hanging in "syncing devices" stage

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17223]
# Bug Report

![IMAGE 2023-09-08 11:38:38](https://github.com/status-im/status-mobile/assets/4557972/e33cd7e2-9fa4-4dce-b84d-8755144eea26)

## Problem 
Android won't go further after sync with latest desktop RC (0.14.0-rc.4 with go [0.166.6](https://github.com/status-im/status-go/tree/v0.166.6))

#### Expected behavior
can sync 

#### Actual behavior
sync is stuck

### Reproduction

1. Desktop: open Profile > Syncing > setup Syncing > generate QR
2. Android: Sign in > Scan QR

### Additional Information

- Status version: nightly  08.09.23
- Operating System: Android
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12558011/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@churik logs are mostly empty unfortunately, could you please provide them again?

**Comment by qfrank** [comment]
only on Android? @churik

**Comment by churik** [comment]
no IOS build for today unfortunately, on yesterday build it is not reproducible

**Comment by churik** [comment]
> @churik logs are mostly empty unfortunately, could you please provide them again?

sure, 5 mins

**Comment by churik** [comment]
It was reproducible 30 mins ago on 3 different devices - now Sync for some reason is working, checking on other devices. Will keep updated

**Comment by churik** [comment]
@qfrank 
So for me it is reproducible when it is first device to sync with.

Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12558498/Status-debug-logs.zip)

**Comment by qfrank** [comment]
emm.. got something useful this time:
```
09-08 12:31:47.432  6764  6872 I ReactNativeJS: INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"Get \\\"https://192.168.1.132:54494/pairing/challenge\\\": x509: certificate has expired or is not yet valid: current time 2023-09-08T10:31:47Z is before 2023-09-08T10:31:53Z\"}", :event :syncing/input-connection-string-for-bootstrapping}
```

**Comment by qfrank** [comment]
There is slightly difference in seconds with the time between android device and desktop , properbly desktop is more acurrate i guess? @churik cc @Samyoul

**Comment by cammellos** [comment]
@qfrank @Samyoul we should accommodate clock differences, as we can't expect clocks to be always synchronized, so there should be some +/- tolerance

**Comment by Samyoul** [comment]
The problem is that the clock difference comes from the TLS library. We could back date the cert. Set the cert time 1 minute in the past.

**Comment by churik** [comment]
I have no idea, here and there everything is set automatically based on time zone.

@VolodLytvynenko seems to have another issue, will post here

**Comment by cammellos** [comment]
@Samyoul can we set the notbefore notafter date on the certificate?

**Comment by Samyoul** [comment]
Yeah we can. It is easy to do. I sent my message a little early, but we can back date the cert. I added the helpful info later.

**Comment by qfrank** [comment]
<img width="978" alt="image" src="https://github.com/status-im/status-mobile/assets/12406719/eb3d1ecd-139f-49b8-af54-23056f426ff5">
easy thing

**Comment by Samyoul** [comment]
@qfrank maybe add 1 minute to the before and after time, because we need the cert to be valid for the duration of the timeout period.

**Comment by VolodLytvynenko** [comment]
The same issue is occurring for me on Android. In my case, after scanning the QR code, the 'Oops, something went wrong' page is displayed, and the syncing process becomes stuck after tapping the 'try again' button

https://github.com/status-im/status-mobile/assets/52490791/291e8c76-71d0-4545-911b-f486c5a93603

### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12558692/android_logcat.txt)

### Env: 
Mobile: Last nightly
Desktop: 0.14.0 RC4

**Comment by qfrank** [comment]
> @qfrank maybe add 1 minute to the before and after time, because we need the cert to be valid for the duration of the timeout period.

let me create the PR 🫶

**Comment by qfrank** [comment]
> The same issue is occurring for me on Android. In my case, after scanning the QR code, the 'Oops, something went wrong' page is displayed, and the syncing process becomes stuck after tapping the 'try again' button
> 
>  sync_pr.mp4 
> ### Logs:
> [android_logcat.txt](https://github.com/status-im/status-mobile/files/12558692/android_logcat.txt)
> 
> ### Env:
> Mobile: Last nightly Desktop: 0.14.0 RC4

not the same in technique:
```
13:55:28.191  I  INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"failed to connect to any of given addresses. connecting to 'https://192.168.0.103:53196' failed: dial tcp 192.168.0.103:53196: connect: no route to host; \"}", :event :syncing/input-connection-string-for-bootstrapping}
13:55:28.191  E  failed to connect to any of given addresses. connecting to 'https://192.168.0.103:53196' failed: dial tcp 192.168.0.103:53196: connect: no route to host; 
13:55:28.199  I  INFO [status-im.signals.core:33] - local pairing signal received {:event {:type "connection-error", :error "failed to connect to any of given addresses. connecting to 'https://192.168.0.103:53196' failed: dial tcp 192.168.0.103:53196: connect: no route to host; ", :action 1}}
```
no route to host

**Comment by cammellos** [comment]
@qfrank @Samyoul do we retry connections?

**Comment by qfrank** [comment]
> @qfrank @Samyoul do we retry connections?

no, i can add it

**Comment by cammellos** [comment]
that's something we should do I believe

**Comment by Samyoul** [comment]
@qfrank be aware that recently @igor-sirotin changed the code so that the client makes an attempt to access every valid IP address the server device shares.

It may be a good idea to retry the whole list of IP addresses if none succeed, rather than retry the same IP individually. Because there may be a number of IP addresses that the server has shared that the client does not have access to.
