### ISSUE TITLE
No profile icon is displayed in mention list near users with pub key instead if display name

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17228]
**Area:** communities' channels/group chats

**Preconditions:** 

1. User A is mutual contact with User B and User C. 
2. User B and User C are not mutual contacts

**Steps:** 

1. User A creates community and invites User B and User C
2. User B joins the community and **goes offline**
3. User C joins the community
4. Open mentions list by User C in #general channel of newly joined community (See User's B pub key)
5. See if profile icon is displayed in mention list near User B

**Actual result:**
Profile icon of User B is not displayed in mentions list for User C

[User_C_logs.zip](https://github.com/status-im/status-mobile/files/12559203/User_C_logs.zip)

<img width="364" alt="Monosnap 2023-09-08 13-13-11" src="https://github.com/status-im/status-mobile/assets/97245802/ca6d99aa-ebe1-41eb-98ba-71d6b7a17847">

https://github.com/status-im/status-mobile/assets/97245802/d16c629e-4a19-40b6-8cde-780905349f14

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
Let's hold on on this one, I think it might be fixed by https://github.com/status-im/status-mobile/pull/17232

**Comment by churik** [comment]
closed, as PR was merged.
Reopen if still reproducible
