### ISSUE TITLE
3 random name instead of public key in mention 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17227]
**Area:** communities' channels/group chats

**Preconditions:** 

1. User A is mutual contact with User B and User C. 
2. User B and User C are not mutual contacts

**Steps:** 

1. User A creates community and invites User B and User C
2. User B joins the community and **goes offline**
3. User C joins the community
4. Open mentions list by User C in #general channel of newly joined community (See User's B pub key)
5. User C mentions User B
6. Observe how pub key mention is displayed

**Actual result:**
3 random name instead of pub key is displayed when User C mentioning User B

[User_C_logs.zip](https://github.com/status-im/status-mobile/files/12559203/User_C_logs.zip)

<img width="363" alt="Monosnap 2023-09-08 13-14-05" src="https://github.com/status-im/status-mobile/assets/97245802/7655478f-cdba-4f1a-8683-85143f27dc13">

https://github.com/status-im/status-mobile/assets/97245802/d16c629e-4a19-40b6-8cde-780905349f14

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by FFFra** [comment]
I removed my assignment until I can reproduce it locally (to not block the issue in case someone is able to reproduce it). 

So far I was just able to reproduce on the main Status community.

**Comment by alwx** [comment]
Working on it in this PR: https://github.com/status-im/status-mobile/pull/17384
