### ISSUE TITLE
Issues related to users' data fetching in chats

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17225]
We are facing quite noticeable issues related to fetching display names, profile icons and pictures in chats.

You can follow the below steps for reproduction but mind that those issues can be easily observed if you restore your main account (which is member of Status comm) on mobile, go to any channel in Status community and check mentions list. You will see bunch of users with pub keys with absent profile icons etc. 

**Area:** communities' channels/group chats

**Preconditions:** 

1. User A is mutual contact with User B and User C. 
2. User B and User C are not mutual contacts

**Steps:** 

1. User A creates community and invites User B and User C
2. User B joins the community and **goes offline**
3. User C joins the community
4. Open mentions list by User C in #general channel of newly joined community
5. See which User's B data is fetched for User C

**Actual result:**

1. Profile icon of User B is not displayed in mentions list for User C 
2. Display name of User B is not fetched for User C i.e. pub key is displayed
3. 3 random name instead of pub key is displayed when User C mentioning User B

User's B data is fetched for User C in one of the following cases:

1. User C opens profile page of User B
2. User B goes back online
3. There is a message from User B in chat which is fetched by User C

On the video below you can observe the described behaviour (User C is from the right part of the screen)

[User_C_logs.zip](https://github.com/status-im/status-mobile/files/12558316/User_C_logs.zip)

<img width="364" alt="Monosnap 2023-09-08 13-13-11" src="https://github.com/status-im/status-mobile/assets/97245802/25459c75-8fa5-49da-ad98-516783ca9124">

<img width="363" alt="Monosnap 2023-09-08 13-14-05" src="https://github.com/status-im/status-mobile/assets/97245802/bb6f398b-c7a5-48ed-ad8d-c545f26b8bb1">

https://github.com/status-im/status-mobile/assets/97245802/392fedc6-3cac-4ad2-8fdd-dfa43fab6e62

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
can be also related to https://github.com/status-im/status-mobile/issues/17182

**Comment by pavloburykh** [comment]
As agreed with @cammellos separate issues were created. Closing this one

https://github.com/status-im/status-mobile/issues/17230
https://github.com/status-im/status-mobile/issues/17229
https://github.com/status-im/status-mobile/issues/17228
https://github.com/status-im/status-mobile/issues/17227
