### ISSUE TITLE
Composer is separated from the footer at the moment of loading chat history (when skeleton is displayed)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17237]
Could be regression of https://github.com/status-im/status-mobile/pull/17169 cc @FFFra 

**Steps:** 

1. Enter chat
2. Pay attention at composer while chat is being loaded

**Actual result:** composer is separated from the footer

<img width="355" alt="photo_2023-09-08 18 03 51 jpeg 2023-09-08 18-04-05" src="https://github.com/status-im/status-mobile/assets/97245802/8f221241-13cc-40fa-bd88-07254e8d2141">

https://github.com/status-im/status-mobile/assets/97245802/5c2b43c1-eacf-48b6-8c46-94773f8d4a80

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by FFFra** [comment]
I found the fix for iOS. Let's test on Android and see if that also works
