### ISSUE TITLE
[ANDROID] The app hangs on the splash screen when trying to open it after it has been in the background for an extended period (2 hour or more) with notifications activated.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17243]
### Steps:
1. Activate notifications.
2. Leave the app running in the background for 2 hours or more.
3. Attempt to open the app.

### Actual result:
The app hangs on the splash screen.

https://github.com/status-im/status-mobile/assets/52490791/daa18d26-04f0-4209-adfc-2f9b4b8af74f

### Expected result:
The app should open successfully.

### Device: 
- real device: Pixel 7a, Android 13
- Android sudio: Pixel 6 Pro API 31
### Logs:
[android_logcat3.txt](https://github.com/status-im/status-mobile/files/12573816/android_logcat3.txt)

**Comment by qoqobolo** [comment]
I was also able to reproduce this on my Pixel. 
In addition to the app freezing on the splash screen, it crashed the next time I opened it. The app launched successfully only on the third try.
I couldn’t reproduce the issue again though (tried it on two Android devices).  

Attaching logcat, the crash happened on Sep 8 between 10:20 and 10:30.

[backgroundcrash.log](https://github.com/status-im/status-mobile/files/12573925/backgroundcrash.log)

<img width="350" alt="Screenshot 2023-09-11 at 10 40 47" src="https://github.com/status-im/status-mobile/assets/67952253/8326ee1c-2d61-4b68-aa61-7352f8cbaf80">

**Comment by churik** [comment]
Should be rechecked once https://github.com/status-im/status-mobile/pull/17241 is merged

**Comment by churik** [comment]
Closing in favour of https://github.com/status-im/status-mobile/issues/20262
