### ISSUE TITLE
Finish the quo2/react component and fix it's location

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#17245]
# Problem

Follow-up for #17224

The `react-selector` component lacks the `Use Case` property from the Design System. Also, the component is located under `reactions`, when it should be under `selectors` and split the `react-selector` and `add-react-selector` components into separate files.

EDIT: As [agreed](https://github.com/status-im/status-mobile/issues/17245#issuecomment-1714155657), also adding the `react` component to quo2, which currently is embedded within the chat context.

EDIT: Wrap the `status-im2.contexts.quo-preview.selectors.reactions` component with the preview container, as it was [missed during migration](https://github.com/status-im/status-mobile/pull/17224#issuecomment-1715344635). Also rename it according to the design system (`reactions-selector`).

## Notes

@Francesca-G we have two different components here: `react` and `add-react` (the one with the +). Should they go into separate previews under `selectors` or keep them in the same preview?

 Also, what is the difference between the `React` and `React selector` components?

**Comment by Francesca-G** [comment]
> @Francesca-G we have two different components here: `react` and `add-react` (the one with the +). Should they go into separate previews under `selectors` or keep them in the same preview?
> 
I think we should keep them in 2 separate previews under the `selectors` section.
>
> Also, what is the difference between the `React` and `React selector` components?
>
this is `React selector`, the single reaction with its different state (pressed by someone, pressed by me, and add)
[Figma link](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=5626%3A158308&mode=design&t=G3qEhdu5tC1EFztt-1)

<img width="300" alt="Screenshot 2023-09-11 alle 14 55 50" src="https://github.com/status-im/status-mobile/assets/122543089/2d1534c6-4c1d-4034-a013-4306eba24f7f">

> 
this is `React`, which include various `React selector`, in a single row with or without the option to add another reaction and on 2 rows.
[Figma link](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=12375%3A140482&mode=design&t=G3qEhdu5tC1EFztt-1)

<img width="400" alt="Screenshot 2023-09-11 alle 14 59 32" src="https://github.com/status-im/status-mobile/assets/122543089/eba0290f-fc46-4971-a616-3a2411bde8da">

> 
The theme options for both components are light, light pinned, dark and dark pinned.

**Comment by clauxx** [comment]
> this is React, which include various React selector, in a single row with or without the option to add another reaction and on 2 rows.

ok, so it seems like `react` is not in quo2 at all and was directly added to the chat. Should I add another issue for that as well @cammellos?

**Comment by cammellos** [comment]
> > this is React, which include various React selector, in a single row with or without the option to add another reaction and on 2 rows.
> 
> ok, so it seems like `react` is not in quo2 at all and was directly added to the chat. Should I add another issue for that as well @cammellos?

Up to you, it makes sense to have a separate issue, sure, but maybe @J-Son89 has an opinion on it

**Comment by J-Son89** [comment]
I think it's fine to have in a single issue 👍 but make sure the description gets updated with it :) thanks for checking!

**Comment by J-Son89** [comment]
> > @Francesca-G we have two different components here: `react` and `add-react` (the one with the +). Should they go into separate previews under `selectors` or keep them in the same preview?
> 
> I think we should keep them in 2 separate previews under the `selectors` section.
> 
> > Also, what is the difference between the `React` and `React selector` components?
> 
> this is `React selector`, the single reaction with its different state (pressed by someone, pressed by me, and add) [Figma link](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=5626%3A158308&mode=design&t=G3qEhdu5tC1EFztt-1)
> 
> <img alt="Screenshot 2023-09-11 alle 14 55 50" width="300" src="https://user-images.githubusercontent.com/122543089/267026828-2d1534c6-4c1d-4034-a013-4306eba24f7f.png">
> > 
> 
> this is `React`, which include various `React selector`, in a single row with or without the option to add another reaction and on 2 rows. [Figma link](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=12375%3A140482&mode=design&t=G3qEhdu5tC1EFztt-1)
> 
> <img alt="Screenshot 2023-09-11 alle 14 59 32" width="400" src="https://user-images.githubusercontent.com/122543089/267027953-eba0290f-fc46-4971-a616-3a2411bde8da.png">
> > 
> 
> The theme options for both components are light, light pinned, dark and dark pinned.

Yep I agree, let's just keep the mapping of preview screens consistent with Figma design system too 👍
