### ISSUE TITLE
Android 11: 'Status is not responding' in activity center 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#17261]
# Bug Report

## Problem 
Constantly getting an issue with e2e application on Android 11 - the app is closed or crashed when navigating to activity center  view. In some cases it happens immediately when activity center is open, sometimes when an action is done in activity center (accepting a contact  request) and sometimes after closing activity center.
**Update: Got application crash on real Android11 too**

#### Expected behavior
Can accept or decline CR and close activity center

#### Actual behavior
'Status app is not responding' alert is shown. But in some cases the application is just closed without any alert

### Reproduction

1. User A sends a contact request to user B
2. User B opens activity center to accept/decline a contact request 

### Additional Information

- Status version: nightly e2e
- Operating System: Android 11
- SauceLabs session: https://app.eu-central-1.saucelabs.com/tests/80b2549ed4054105bbee69c5410ac5a9?auth=4192cf255c8f8a8ef4995c783b920c09#62
- Logcat: [logcat (1).log](https://github.com/status-im/status-mobile/files/12586585/logcat.1.log)

**Comment by yevh-berdnyk** [comment]
One more example from **Android 10** (e2e test) - the app was just closed without any error:
SauceLabs session: https://app.eu-central-1.saucelabs.com/tests/fa7e1ab335794b6ba3a43e629d51bc0f?auth=6ea5d57fa8e1f03ee907c38818e91705#68
Logcat log: [logcat_android_10.log](https://github.com/status-im/status-mobile/files/12999479/logcat_android_10.log)
Geth log: [TestGroupChatMultipleDeviceMergedNewUI_geth1.log](https://github.com/status-im/status-mobile/files/12999489/TestGroupChatMultipleDeviceMergedNewUI_geth1.log)

**Comment by yevh-berdnyk** [comment]
Reproduced on Samsung Galaxy A12 with Android11 (real device).
SauceLabs session: https://app.eu-central-1.saucelabs.com/tests/4919bcc86b8e4bef9d4bd49f7d8e96b6
Device log: [android11.log](https://github.com/status-im/status-mobile/files/13666401/android11.log)

**Comment by Horupa-Olena** [comment]
Not reproduced on Samsung Galaxy A12 with Android11
SauceLabs session: https://app.eu-central-1.saucelabs.com/tests/47eeb7a29db04d91a07c25fd7502fb65
https://app.eu-central-1.saucelabs.com/tests/69ae6e22b2dd444eb4dd2a2a89631608

Also tested and not reproduced on Samsung Galaxy A51 with Android10
SauceLabs session: https://app.eu-central-1.saucelabs.com/tests/cdd0f73b436046e98d2c75e8c2b581ac

Also tested and not reproduced on Samsung Galaxy A03s with Android12
SauceLabs session: https://app.eu-central-1.saucelabs.com/tests/68acf7e4edcd4d7cb2fb8bdfde3c9991
