### ISSUE TITLE
Separate channel and community requirements 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17267]
# Bug Report

## Problem 
Potential members of token-gated communities can't see whether they can join a community or not, and they can join even if they don't meet the requirements.

#### Expected behavior
3. User1: can see that meets the requirement

#### Actual behavior
3. You hold 0 from 1.000000 SNT

https://github.com/status-im/status-mobile/assets/4557972/211351d2-da92-4e52-a6e4-74f7e1473dfd

5. User2 shouldn't be able to enter a channel
7. Error in sending a message
![IMAGE 2023-09-12 18:22:47](https://github.com/status-im/status-mobile/assets/4557972/9ffd94f6-fb1d-4d16-bbd5-5195b524a569)

### Reproduction

1. Desktop: create a token-gated community with the following permission:
![image](https://github.com/status-im/status-mobile/assets/4557972/0f9cef0a-3092-40a3-a49f-675669e66759)
2. Invite User1 (meets the requirement) and User2 (doesn't meet the requirement)
3. User1: check the community invite and join the community
5. User2: check the community invite and join community
6. User1: send message 
7. User2: send message

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Logs of user2: 

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
## Scenario 1
Permission: Anyone who holds **1 SNT** is allowed to **Become a Member**
<img width="592" alt="Screenshot 2023-10-25 at 19 06 33" src="https://github.com/status-im/status-mobile/assets/19279756/5beab387-7edf-4c91-a9cc-52ab18a1ea5f">


User has: **1 SNT**
<img src="https://github.com/status-im/status-mobile/assets/19279756/cccb190c-bc2a-478d-ae14-fdd8fd8958cd" width=350/>

## Scenario 2
Permission: Anyone who holds **2 SNT** is allowed to **Become a Member**
<img width="582" alt="Screenshot 2023-10-25 at 19 09 01" src="https://github.com/status-im/status-mobile/assets/19279756/3ba94fbb-80f3-447c-b54c-d15f0a5c3dd1">


User has: **1 SNT**
<img src="https://github.com/status-im/status-mobile/assets/19279756/b9456b18-abca-417b-b90e-781186b6f2b9" width=350/>

## Scenario 3
Permission: Anyone who holds **10 SNT** is allowed to **View and Post** in #general
<img width="585" alt="Screenshot 2023-10-25 at 19 10 04" src="https://github.com/status-im/status-mobile/assets/19279756/b485a7c0-2b32-4132-a605-1f04227a08db">

User has: **1 SNT**
<img src="https://github.com/status-im/status-mobile/assets/19279756/505bb616-63b5-4088-abb3-e01bbb2eb789" width=350/>

-----

As far as I can tell, Scenarios 1 and 2 are functioning as intended.

@churik, I'd like to discuss Scenario 3 further. The eligibility card appears somewhat unclear to me. From what I understand, in this case, users should be allowed to join the community without being restricted by the tokens they hold. Is there a Figma design that illustrates this scenario when a community only has channel permissions in place?

**Comment by churik** [comment]
@ajayesivan my understanding is that if there are no permissions for `Become a member` but there are permissions to separate channels at least for now we can show "show a lock if you don't have access, but that's all" (copied from Discord)
Others should be unlocked (where there is no permission set).

And these channel permissions definitely should not be displayed as they are for joining the community. 
The task of handling token permissions will be handled separately as flows are still TBD and in the process of designing and depend on  "Sharing the address" feature.
I'll create a follow-up feature issue after this release.

**Comment by churik** [comment]
Also in [designs](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7828-524581&mode=design&t=A0LRL3HS6RjQQVbM-4) would be nice to display decimals if they are there (I mean if the set permission is not integer). otherwise `.00000000000000` does not make a lot of sense from my POV
![image](https://github.com/status-im/status-mobile/assets/4557972/08b51ccd-b23e-43f6-9226-52060046b020)

**Comment by churik** [comment]
### Acceptance criteria: 

#### Channel permissions: 

- [ ] 1. Lock channel icon when the the channel is token-gated
Design: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7898-523613&mode=design&t=yJBpgHu6fWdphPol-4 
- [ ] 2. The channels that do not have token-gated permissions set, should not contain a lock icon 
- [ ] 3. Do not show channel requirements on the community page

The unlock mechanism for the channels will be implemented separately.

#### Community permissions:

- [ ] 1. Shown on the community page (permissions only `Become an Admin`, `Become a member`)
- [ ] 2. Contains decimals only if it matches the amount (so should be an integer, if the amount is an integer) 
 
![image](https://github.com/status-im/status-mobile/assets/4557972/08b51ccd-b23e-43f6-9226-52060046b020)
