### ISSUE TITLE
Broken colours issues

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17295]
### ISSUE 1 Request join community button in not visible

https://github.com/status-im/status-mobile/assets/97245802/58933805-3a1a-4b5a-922c-77dec25efaeb

### ISSUE 2 Unread community channel counters are not visible

**Light mode:** 

![photo_2023-09-15 12 00 35](https://github.com/status-im/status-mobile/assets/97245802/8a7746fb-1917-4233-b019-be92c096a838)

**Dark mode:**

![photo_2023-09-15 12 00 38](https://github.com/status-im/status-mobile/assets/97245802/72696da8-998e-4e36-9fc1-0a26021a683e)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
I can take a look 👍
