### ISSUE TITLE
Re-run e2e job is failing 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17296]
Re-run e2e job is constantly failing

Links to e2e run console log

https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/3069/console

https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/3068/console

**Comment by churik** [comment]
So far linux-03 and linux-02 are affected, linux-01 and linux-05 are fine.

We need to re-run it sometimes 3-4 times to get a server that can install lib successfully.

**Comment by jakubgs** [comment]
Looks like the same issue as:

* https://github.com/status-im/infra-role-bootstrap-linux/pull/33

**Comment by jakubgs** [comment]
I think you can fix this yourself by using `Cython<3.0` in your `requirements.txt`.

**Comment by churik** [comment]
will try that, thanks!

**Comment by yakimant** [comment]
If it will not help, try full solution, installing `PyYAML` and `Cython` in advance (note the `--no-build-isolation` key):
```
pip install "Cython<3.0"
pip install "PyYAML==5.4.1" --no-build-isolation
pip install -r requirements.txt
```

Or as alternative downgrade the `PyYaml`:
`PyYAML==5.3.1`
(missing some security patches though)

**Comment by jakubgs** [comment]
I have ran bootstrap on `ci-slave-linux` hosts to apply he fix we have. Not sure, maybe it will help with E2E PIP runs too.
