### ISSUE TITLE
Display name is not shown on Profile page after sync

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17308]
Followup of https://github.com/status-im/status-mobile/pull/17127 cc @qfrank 
If this issue turns out not to be related to your changes - then we can ping status-go team to provide a fix. But first we need to find out which commit has caused this issue. 

**Steps:** 

1. Device 1 generates sync QR
2. Device 2 scans QR
3. See if display name is displayed on Profile page for Device 2 when sync is completed

**Actual result:** name field is empty

[Status-debug-logs (58).zip](https://github.com/status-im/status-mobile/files/12620155/Status-debug-logs.58.zip)

![photo_2023-09-15 17 18 07](https://github.com/status-im/status-mobile/assets/97245802/5100c3b3-30ab-4f80-9e21-17d8ff92470a)

https://github.com/status-im/status-mobile/assets/97245802/3df99f3d-523c-4534-8cb4-5b14d06d928f

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qfrank** [comment]
let me fix it, i think i'm also part of `status-go` team 🙂 @pavloburykh

**Comment by pavloburykh** [comment]
@qfrank hello! 

For some reason the issue is still reproducible in latest nightly (Sep 21, 2023) despite the fix has been merged couple of days ago. Re-opening the issue. 

Display name is not displayed after sync for the User who scans sync QR code.

[User_who_generates_code.zip](https://github.com/status-im/status-mobile/files/12684624/User_who_generates_code.zip)
[User_who_scans_code.zip](https://github.com/status-im/status-mobile/files/12684625/User_who_scans_code.zip)

![photo_2023-09-21 15 47 45](https://github.com/status-im/status-mobile/assets/97245802/acb31212-e81e-461a-addb-4329b7705b3a)

**Comment by pavloburykh** [comment]
@qfrank please, ignore it. It turned out that I have used outdated PR build instead of nightly. My apologies. Closing the issue.
