### ISSUE TITLE
Make sure network-specific fields are marked as such in app-db

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1730]
As a user, the ETH I own on main net is not the same as the ETH on test net. For example.

For network switching we need to:
(a) List the things that are network-dependent
(b) Make sure they are indexed properly in app-db

Type: Feature

**Comment by janherich** [comment]
We should also make sure that DB is properly normalised while we do it - all unique "entities" are indexed and referenced in relations, as to maintain integrity and keep redundancy at minimum.

**Comment by flexsurfer** [comment]
i believe all wallet things shouldn't be stored in app-db

**Comment by oskarth** [comment]
@flexsurfer could you elaborate?

Perhaps specifics of wallet db are better discussed in https://github.com/status-im/status-react/issues/1653

**Comment by rasom** [comment]
@oskarth @flexsurfer @janherich @jeluard 
should we just close this issue? Or is there anything that should be done now?

**Comment by oskarth** [comment]
@rasom Fine by me, up to you and wallet squad

**Comment by jeluard** [comment]
Fine for me too, if we need something more we can create more specific issues.

**Comment by flexsurfer** [comment]
Fine for me
