### ISSUE TITLE
Make sure compilation warnings fail the build

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#1731]
Default ClojureScript compiler configuration does not let build fail when warnings are found.

This is not useful in our case are warnings are always errors.

See:

* http://jakemccrary.com/blog/2015/12/19/clojurescript-treat-warnings-as-errors/
* https://github.com/emezeske/lein-cljsbuild/blob/master/README.md#custom-warning-handlers

**Comment by oskarth** [comment]
Created separate issue instead, sorry for the noise.
