### ISSUE TITLE
3 random name is displayed as 1-1 chat name during loading of chats list

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17313]
**Steps:** 

1. Create 1-1 chat
2. Open Chats tab
3. Perform re-login
4. Pay attention at 1-1 chat names after login (at the moment of chat list loading)

**Actual result:** 3 random name is displayed as 1-1 chat name for a moment until chat list is loaded

Below video in slow-mo

https://github.com/status-im/status-mobile/assets/97245802/1b2a945b-7b0d-4533-9e62-4accff7db247

**Expected result:** 3 random names should not be displayed in any place in the app. User's public key should be shown until Displaye name/ENS/nickname is loaded. 

**Additional info:**

This issue has been initially reported by @jo-mut here https://discord.com/channels/1103692771585433630/1103692773363810317/1153270331222536192

In his case there is additional weird bug: group icon is displayed in front of 1-1 chat until it is loaded. None of QAs were able to reproduce this issue. In our case icon is not displayed until chat list is loaded. 

Screenshot from @jo-mut phone. 

<img width="363" alt="simulator_screenshot_94D2F4F1-A7FF-41DA-816C-D9FD5" src="https://github.com/status-im/status-mobile/assets/97245802/d9f1b124-d3bd-4497-8355-f108497bfb28">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by alwx** [comment]
Working on it as part of this: https://github.com/status-im/status-mobile/issues/17285
