### ISSUE TITLE
Implement collectible menu

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#17323]
# Feature Issue

### User Story

As a user, I want to see the menu for collectible **so that** I know a list of possible actions to do with it

### Description

Figma designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-310651&mode=design&t=Upgum07x1OxZT1AP-4

<img width="236" alt="Screenshot 2023-09-18 at 13 42 33" src="https://github.com/status-im/status-mobile/assets/5786310/c76f1c1a-9bc0-4dcd-8410-9250e1c6c7b5">

### Acceptance Criteria

- [ ]  menu accessible from the collectible overview page

**Comment by Rende11** [comment]
I would like to implement it

**Comment by vkjr** [comment]
@Rende11, do you still want to implement it? Because I assigned it to myself without noticing your previous comment)
