### ISSUE TITLE
The communities sorted randomly on the list of communities page.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17337]
### Steps:
1. User_A: Creates at least 3-4 communities -> share them to User_B
2. User_B: Joins them
3. User_B: Check the list of communities in the 'joined' tab

### Actual result:
The communities are sorted randomly
![image](https://github.com/status-im/status-mobile/assets/52490791/9527c03e-6132-4b99-8705-ed8c11b68f08)

### Expected result:
- The communities are sorted in order of joined
https://discord.com/channels/624634427930312714/842696205213368331/1151526646675947651

- In the 'pending' tab, the communities should be sorted in the order they were requested.
- For 'opened' communities, they should be sorted based on the order they were shared.

**Comment by clauxx** [comment]
@VolodLytvynenko @cammellos one thing I noticed is that the "opened" tab in communities acts more like like an "invited" tab, because it shows communities that were shared with you, even if you didn't open them. Do we want to keep it this way or rather track communities that the user explicitly opened? 

Given that the user can also discover communities, I think the "opened" tab should only show the communities that the user actually opened, in the order by which they were opened and not when they were shared. I guess this question would be relevant to the design team as well.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko @cammellos one thing I noticed is that the "opened" tab in communities acts more like like an "invited" tab, because it shows communities that were shared with you, even if you didn't open them. Do we want to keep it this way or rather track communities that the user explicitly opened?
> 
> Given that the user can also discover communities, I think the "opened" tab should only show the communities that the user actually opened, in the order by which they were opened and not when they were shared. I guess this question would be relevant to the design team as well.

@clauxx Thank you for your question. Yep, have approval from the design team. The recently opened community  should be at the top of 'opened' tab 
https://discord.com/channels/624634427930312714/842696205213368331/1159774794875686954
![image](https://github.com/status-im/status-mobile/assets/52490791/f56ddde9-8213-4938-ac88-307aa55fe686)

**Comment by cammellos** [comment]
```
`joined-at`
`requested-at`
`spectated-at`
```
can be used for sorting

**Comment by Samyoul** [comment]
@cammellos / @VolodLytvynenko I notice that we have 2 states that we need to track:

States for when a user spectates, requests to join and joins a community:

```
`joined-at`
`requested-at`
`spectated-at`
```

But according to Alisher's message we also just order opened pages:

![image](https://github.com/status-im/status-mobile/assets/5702426/5418573c-0780-4fa9-8ef5-0659bd0a4c6a)

So does `spectated_at` mean the same as `recently opened`? And if so do we also need to add an API endpoint to update the `spectated_at` whenever a community has been visited to maintain the order of communities by the last visited time?

Or does `spectated_at` mean that we order opened communities in the order we visited them (only setting the `spectated_at` value once)?

Or does `opened` and `spectated` mean 2 different things? Is `spectate` a special type of joining state, and opened applies to all communities?

**Comment by Samyoul** [comment]
**Answer:**

We will need to track when communities were last opened to maintain the order of communities by the last visited time.

https://discord.com/channels/624634427930312714/842696205213368331/1184084706577354814
<img width="878" alt="Screenshot 2023-12-12 at 12 26 19" src="https://github.com/status-im/status-mobile/assets/5702426/ece5d26b-8d43-498f-947f-b213109d7dc7">
<img width="891" alt="Screenshot 2023-12-12 at 12 26 59" src="https://github.com/status-im/status-mobile/assets/5702426/28442d02-3030-4168-a6e5-980e7e9614ed">

<details>
<summary>Full conversation</summary>
<pre>
Samuel — Today at 10:49
When should a community be considered "opened"?
When should a community be considered "spectated"?

---

Alisher — Today at 11:37
From UX POV it should work like this.

Community goes to "Joined" tab  if :
User is a member of community.
List sorted by order of joining. We'll add manual reordering post-MVP

Community goes to "Pending" tab if:
User has pending request to join.
List sorted by order of requests. Community with recent request is on top.

Community goes to "Opened" tab  if : 
Not a member of community opened a community page / channel
User was kicked from community.
Request to join is timed out.
List sorted by order of opening. Recent opened on top.

@Samuel I don't know what is spectated-at 

CC @Pedro

---

Samuel — Today at 11:40
Thank you. Ok spectated must be an internal status-go state that presumably tracks communities that a user is not a member of.
List sorted by order of opening. Recent opened on top.
@Alisher do you know if this changes every time a user visits a community? Example:

Starting state
Opened
community B
community A

Opens another community
Opened
community C
community B
community A

Opens a community previously opened (community A)
Opened
community A
community C
community B

---

Alisher — Today at 11:44
I will expect this behavior, but I don't aware of implementation details.

---

Samuel — Today at 11:45
Thank you. That's fine, I can handle the  implementation details.
</pre>
</details>

**Comment by VolodLytvynenko** [comment]
Hey @Samyoul thank you for finding more detailed requirements for this feature and sharing it

**Comment by Samyoul** [comment]
Action Points:

- [x] Make an issue for adding the `joinedAt` field and the logic to set this value implicitly when a user fully joins a community.
    - Likely when the community `Joined` bool is set to true.
- [x] Make an issue for adding the `lastOpenedAt` field and add a new API endpoint to call something like `CommunityOpened(communityID)` so that the UI can call it when a particular component is rendered.
- [x] Do the actual work

**Comment by ibrkhalil** [comment]
The PR adding the attributes is merged
https://github.com/status-im/status-mobile/pull/18439

**Comment by ibrkhalil** [comment]
I need this to be fixed first so that I can have data to work against to test my soluion
https://github.com/status-im/status-mobile/issues/18637#issuecomment-1918308780
