### ISSUE TITLE
Implement Tiny tag component

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#17341]
# Feature

Implement the "Tiny tag" component from the Tags category in the quo2 component library.

<img width="653" src="https://github.com/status-im/status-mobile/assets/18485527/4acd12b3-e058-4fa7-9b5b-fcce18ef0364">

### Designs

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22562-203907&mode=design&t=FLdnfT1abM1btBM2-4)

### Acceptance Criteria:

- Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
- Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)
- Should add an export from the `quo2.core` namespace
- Add a preview for this component under the `list-items` category in the Quo2 preview screen

**Comment by briansztamfater** [comment]
Once we implement this, we need to integrate it in Account List Item component (check TODO in #17303)

**Comment by Rende11** [comment]
I would like to implement this.
