### ISSUE TITLE
Zoom controls don't work in chat camera

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17358]
# Bug Report

## Problem 

The `0,5x`, `1x`, `2x`, `3x` zoom buttons don't work in camera in the chat view. Pinch works fine. 

https://github.com/status-im/status-mobile/assets/67952253/5d7904e8-18eb-456d-a847-ab6bfc4da81c

### Reproduction

1. Open chat
2. Open camera
3. Try to zoom in or out using `2x`, `3x`etc  zoom controls 

### Additional Information

- Status version: nightly 20/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Unassigning as I'd need XCode 15 to work on this, And I still need to install Ventura on my Hackintosh to get XCode 15.
Will do it later if no one picks it up.

**Comment by ibrkhalil** [comment]
Upgraded, Reassigning myself.

**Comment by ibrkhalil** [comment]
Had to unassign as I don't have capacity, Will pick it up if no one did when I finish what I have.

**Comment by ibrkhalil** [comment]
I researched the issue, And I found that controlling the zoom programmatically is still in pre-release of react-native-camera-kit, Check the changelog [here](https://github.com/teslamotors/react-native-camera-kit/releases/tag/v14.0.0-beta4)

**Comment by ibrkhalil** [comment]
I'll give integrating the beta a shot.

**Comment by ibrkhalil** [comment]
Done 😄
