### ISSUE TITLE
Implement "Token network" component

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#17369]
# Feature

Implement the "Token network" component from the List items category in the quo2 component library.

<img width="500" alt="Screenshot 2023-09-20 at 10 55 07 PM" src="https://github.com/status-im/status-mobile/assets/19339952/588ce0c2-0152-4f41-80d1-f55a64a5a4f6">

### Designs

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=109%3A5278&mode=design&t=lxrRN09MPlnlJcIM-1)

### Acceptance Criteria:

- Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
- Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)
- Should add an export from the `quo2.core` namespace
- Add a preview for this component under the `list-items` category in the Quo2 preview screen

**Comment by Rende11** [comment]
I would like to implement this feature
