### ISSUE TITLE
Composer: can't see the entire multiline message in collapsed composer after reopening the chat [Android]

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17361]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/67952253/fd897a1a-edfd-4c73-8f77-a6e21e345b32

#### Steps:
1. Open chat
2. Type a multiline message
3. Close the chat and open it again
4. Try to set the cursor to the end of the message

### Additional Information

- Status version: nightly 20/09
- Operating System: Android

**Comment by mohsen-ghafouri** [comment]
I gave it my best shot, but as I delved into fixing this issue, it led me to discover a few more lurking problems. So, I'm stepping back from it for now, hoping that our team members with a deeper understanding of the composer can tackle these issue more effectively
