### ISSUE TITLE
'Scroll down' button is not hidden behind the top bar when the composer is expanded [iOS]

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17364]
# Bug Report

### Reproduction

1. Open a chat with some history
2. Scroll up until the `Scroll down` arrow-button appears
3. Expand the composer

iPhone SE
<img width="357" alt="Screenshot 2023-09-20 at 17 51 08" src="https://github.com/status-im/status-mobile/assets/67952253/5ce0004a-d48e-4886-abc9-a613a6f01126">

iPhone 11 pro max
<img width="292" alt="Screenshot 2023-09-20 at 17 51 31" src="https://github.com/status-im/status-mobile/assets/67952253/473c40a5-4fdd-4827-827f-69a78cd515d3">

iPhone 12 mini
<img width="293" alt="Screenshot 2023-09-20 at 17 51 56" src="https://github.com/status-im/status-mobile/assets/67952253/e501753f-450f-4b77-a3a8-dd3464653e43">

#### Expected behavior

This is how it works on Android: the `Scroll down` button is hidden behind the top bar

https://github.com/status-im/status-mobile/assets/67952253/10a8923c-306c-419e-8f56-1a40a491157b

### Additional Information

- Status version: nightly 20/09
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
I couldn't find a solution for this, Do you think I should animate the increasing of the opacity of the scroll to down button so that when composer is expanded to it's maximum height it disappears?
CC: @Francesca-G 
I don't know if it's going to be okay to have a different behavior for something between iOS and Android, But I guess RN has it's limitations.

I am going to keep trying making it the same as Android.

**Comment by ibrkhalil** [comment]
Here's a sample PR of what I mean if you want to see how it looks CC: @qoqobolo 
https://github.com/status-im/status-mobile/pull/17466

**Comment by qoqobolo** [comment]
Thanks @ibrkhalil , it looks good to me in https://github.com/status-im/status-mobile/pull/17466 on Android, much better than how it looks now in develop. 


https://github.com/status-im/status-mobile/assets/67952253/7a895882-8503-4a44-92b4-14df072fc840



However, we still need the designers' opinion on this matter (how it currently looks on Android and about the difference between iOS and Android). Would you mind asking about this on design Discord?

**Comment by qoqobolo** [comment]
Thanks @ibrkhalil , it looks good to me in https://github.com/status-im/status-mobile/pull/17466 on iOS with an empty expanded composer. 
However, if the composer expands as you type, the problem still reproduces.


https://github.com/status-im/status-mobile/assets/67952253/6eef8bf3-bc95-41b1-8e9d-2fef744c79d7

<img width="324" alt="Screenshot 2023-10-02 at 15 40 05" src="https://github.com/status-im/status-mobile/assets/67952253/1ed18fd8-f4dc-4e34-8ec4-d4c2a823ea4c">



Also, we still need the designers' opinion on this matter (how it currently looks on Android and about the difference between iOS and Android). Would you mind asking about this on design Discord?

**Comment by ibrkhalil** [comment]
> Thanks @ibrkhalil , it looks good to me in https://github.com/status-im/status-mobile/pull/17466 on iOS with an empty expanded composer. 
> 
> However, if the composer expands as you type, the problem still reproduces.
> 
> 
> 
> 
> 
> https://github.com/status-im/status-mobile/assets/67952253/6eef8bf3-bc95-41b1-8e9d-2fef744c79d7
> 
> 
> 
> <img width="324" alt="Screenshot 2023-10-02 at 15 40 05" src="https://github.com/status-im/status-mobile/assets/67952253/1ed18fd8-f4dc-4e34-8ec4-d4c2a823ea4c">
> 
> 
> 
> 
> 
> 
> 
> Also, we still need the designers' opinion on this matter (how it currently looks on Android and about the difference between iOS and Android). Would you mind asking about this on design Discord?

Thanks for taking a look Diana, I'll discuss it with them so that I can fix it only once.

**Comment by ibrkhalil** [comment]
Got a response from Design, We will hide the button if composer is active.
[ref](https://discord.com/channels/624634427930312714/928625369542713396/1158706594591289354)
