### ISSUE TITLE
Implement profile view

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#17393]
We should change the styling of the profile section in the app.

You should be reusing existing components where available, and create new ones if necessary, according to the dev guidelines.

https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?node-id=3773%3A221861&mode=dev

**Comment by nguyentruongky** [comment]
@cammellos Hi Andrea, just requested for the access to the figma file. Please check your inbox. Thanks.
