### ISSUE TITLE
Can't 'Delete for everyone' and unpin the message that was 'Deleted for me'

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17390]
# Bug Report

## Problem 

The feature was added in [this PR](https://github.com/status-im/status-mobile/pull/15689)

> it also adds the ability to Delete message for everyone that have Deleted for me (discussed with John) and the ability of unpin messages that have been deleted for me.

But it doesn't work anymore, there is no way to long-press the system message:

https://github.com/status-im/status-mobile/assets/67952253/1906bb62-44d0-482e-bea6-2c6db2b63d6c

#### Expected behavior
- The user can unpin `Deleted for me` message
- The user can `Delete for everyone` the message that was `Deleted for me`

#### Actual behavior
Long press on system messages doesn't work > you cannot take any action on such messages

### Reproduction

1. Open chat
2. Send a message
3. Pin the message
4. `Delete for me` the message
5. Open `Pinned messages` and try to unpin that message
6. Open chat again and try to `Delete for everyone` the `deleted for me` message

### Additional Information

- Status version: nightly 22/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
seems somehow long press won't work on deleted pinned message, checking pinned message list

**Comment by yqrashawn** [comment]
ok, this happens twice in pinned msg render fn and `message/message`
maybe on long press in implemented in `message/message` not `content.deleted/deleted-message`

``` clojure
(if (or deleted? deleted-for-me?)
    [content.deleted/deleted-message message context]
    [message/message message context (atom false)])
```

https://github.com/status-im/status-mobile/blob/08689e568a44d991fe5dc6c0c32972eaf646e0a1/src/status_im2/contexts/chat/menus/pinned_messages/view.cljs#L25
https://github.com/status-im/status-mobile/blob/08689e568a44d991fe5dc6c0c32972eaf646e0a1/src/status_im2/contexts/chat/messages/content/view.cljs#L238

**Comment by yqrashawn** [comment]
deleted and deleted for me messages are "system message" in design
they are not system message based on content type https://github.com/status-im/status-go/blob/ba5cd9c1a462ef57431dd69ccfd88b9dafd7d744/protocol/protobuf/chat_message.pb.go#L78

because we don't show deleted message before, we mark deleted message `Hide=true` and skip rendering it in the frontend
we reuse the hide logic when implementing new deleted message instead of using message content type 

now there're user message, deleted message, system message in the frontend https://github.com/status-im/status-mobile/blob/08689e568a44d991fe5dc6c0c32972eaf646e0a1/src/status_im2/contexts/chat/messages/content/view.cljs#L237

``` clojure
(if (or (system-message? content-type) deleted? deleted-for-me?)
     (if (or deleted? deleted-for-me?)
       [content.deleted/deleted-message message-data]
       [system-message-content message-data])
     [user-message-content
      {:message-data    message-data
       :context         context
       :keyboard-shown? keyboard-shown?
       :show-reactions? true}])
```

should fix the long press first

**Comment by yqrashawn** [comment]
~`log/spy` won't work again~

**Comment by yqrashawn** [comment]
ok, on long press got deleted at https://github.com/status-im/status-mobile/pull/16775/files#diff-f19099d11cab857c4ab6061a65d7054b139f4e5feebd3d01860382f554cdd7c4L27
wondering why, will add it back

**Comment by yqrashawn** [comment]
ok, `system-message` no longer support `on-long-press`, no `animate-landing?` either. these features got removed completely

https://github.com/status-im/status-mobile/pull/16775/files#diff-07804a4aa53d86bfec5907032607dc58b11e0e4a1a1d5801625c0be2ad27f738L149-L161

**Comment by yqrashawn** [comment]
Hey @flexsurfer! I noticed that `on-long-press` and `animate-landing` got removed from the system-message. Do you know why? I'm planning on adding them back. Do you have any suggestions on where to add these? Should I put them in the deleted-message or the system-message? Thanks!

**Comment by flexsurfer** [comment]
probably it was removed by mistake because i thought it was not used, sorry

**Comment by flexsurfer** [comment]
i'm still not sure about `animate-landing`

**Comment by yqrashawn** [comment]
> i'm still not sure about `animate-landing`

me too, I tend to add on-long-press in delete-message, but the style is implemented in system-message
I will take another look at the code and think about it again.
