### ISSUE TITLE
component tests fail after upgrading react native to 0.72.x

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#17409]
# Problem

After upgrading react-native,
`make component-test` fails with :

```
 SyntaxError: /Users/siddarthkumar/code/experiments/status-mobile/node_modules/@react-native/js-polyfills/error-guard.js: Missing semicolon. (14:4)

      12 | let _inGuard = 0;
      13 |
    > 14 | type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         |     ^
      15 | type Fn<Args, Return> = (...Args) => Return;
      16 |
      17 | /**
```      

# Assumptions
- Caused due to upgrading versions of `jest`.
- This code is either not transformed properly so could be a change we need to make in `babel` config or `jest` config.
- Probably this file should have been ignored by `jest` and this looks like flow(react native uses flow for type checking) code so most likely a `babel` `typescript` plugin won't help.

# Related links 
- https://github.com/jestjs/jest/issues/12978 (This is the exact same error we have)
- https://jestjs.io/docs/configuration#transformignorepatterns-arraystring
- https://github.com/facebook/react-native/issues/33426 (same error in react-native repo)
- https://github.com/swc-project/jest/issues/85

Blocks https://github.com/status-im/status-mobile/pull/17241

**Comment by siddarthkay** [comment]
The issue was fixed by downgrading jest to 26.x
upgrading jest requires significant changes to our test suite and can be an independent task in itself
cc @J-Son89 @ilmotta

**Comment by ilmotta** [comment]
> The issue was fixed by downgrading jest to 26.x upgrading jest requires significant changes to our test suite and can be an independent task in itself cc @J-Son89 @ilmotta

Thanks @siddarthkay. I forgot the number of times in my life I read the sentence "upgrading jest requires significant changes".
