### ISSUE TITLE
Missing padding around QR code in setup syncing screen - iOS

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17407]
Missing padding on the left & right side of the QR code in the setup syncing screen on iOS.

Design: https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-178207&mode=design&t=RNC9sY3rVHOTVUU8-4

### Screenshots
iOS | Android
-|-
<img width=340 src="https://github.com/status-im/status-mobile/assets/19279756/51fce0c3-18f7-4b41-8f42-c47075e099ee"/> | <img width=340 src="https://github.com/status-im/status-mobile/assets/19279756/90422891-ba80-428e-bab0-a52e494b80e7"/>

**Comment by ajayesivan** [comment]
It seems like https://github.com/status-im/status-mobile/pull/16916 brings some changes to the 'Setup syncing' screen. Maybe it's a good idea to wait until it gets merged before taking this up.

cc: @J-Son89

**Comment by churik** [comment]
Not reproducible anymore on nightly 21/06/24 (IPhone 14, Google Pixel7),  reopen if still relevant.
