### ISSUE TITLE
Request/send messages has no "From/To" line in group chat for sender [bug/from-missing-group-#1448]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1741]
### Description

*Type*: Bug

*Summary*: For sender of the /request message in the group chat: no "from line" is shown. For recipient and other members of the group chat this line is shown. Same issue is for /send command - no "to" line is shown for a sender
![img_0571](https://user-images.githubusercontent.com/6584810/30021519-4e6f81d0-9170-11e7-8994-ac3854936ad2.jpg)

#### Expected behavior
 1. For sender of the /request message in the group chat: "from line" is shown
2.  For sender of /send command -  "to" line is shown 
#### Actual behavior
1.  For sender of the /request message in the group chat: no "from line" is shown
2.  Same issue is for /send command - no "to" line is shown for a sender
### Reproduction

- Open Status
- Open group chat
- send request message to some of the member 
- check that sent request message contains "from"
- send some eth in group chat and check "to" in the send message

### Additional Information
* Status version: PR `bug/from-missing-group-#1448` 0.9.10-48-g804a1882
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by annadanchenko** [comment]
already tested OK as part of #1448 verification

**Comment by jeluard** [comment]
Fixed in develop
