### ISSUE TITLE
Can access device media gallery on the "Create Profile" step without granting permissions to Status app [Android]

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17421]
# Bug Report

### Reproduction

1. Install Status
2. Go to the `Create profile` screen
3. Press the `camera` icon on avatar
4. **_Quickly_** tap the `Select from gallery` button several times

#### Expected behavior
Cannot access the device gallery

#### Actual behavior
Can access the gallery without allowing it to Status

Pixel 7a

https://github.com/status-im/status-mobile/assets/67952253/74145246-5855-41e7-b21c-edd1775c6ffc

Huawei p40 lite

https://github.com/status-im/status-mobile/assets/67952253/ef8fcca6-871e-4c07-9ed6-b1bd3e9ed7fe

### Additional Information

- Status version: nightly 26/09
- Operating System: Android 

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
might be fixed by https://github.com/status-im/status-mobile/pull/17241, should be rechecked after merge

**Comment by siddarthkay** [comment]
this is fixed in https://github.com/status-im/status-mobile/pull/17241

**Comment by siddarthkay** [comment]
Assigning myself because we need not do anything yet, and this issue is fixed in the upgrade PR.

**Comment by siddarthkay** [comment]
fixed here : https://github.com/status-im/status-mobile/pull/17241
