### ISSUE TITLE
The composer remains expanded when the cancel button is tapped during message editing or after sending message with picture and long description

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17433]
#### Expected behavior
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=8666-42639&mode=design&t=0tR9e9C8vBDJzDXT-0
In the case of message editing, if the cancel button is tapped, the composer should return to its original state.
Discussed with the design team:
![image](https://github.com/status-im/status-mobile/assets/52490791/1bce1f9b-094c-44f4-a444-15c74989b817)

#### Actual behavior
The composer remains expanded even after tapping the cancel button during message editing.

https://github.com/status-im/status-mobile/assets/52490791/4f5dc70c-49b4-4072-954a-243be1cf109c

### Reproduction
1. Start editing a long message in the composer.
2. Tap the cancel button.

### Additional Information
- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
Composer does not collapse when sending long message with picture(design review 1.25, https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#567094662)

**Comment by clauxx** [comment]
@FFFra are you working on it atm? I know you're working on communities, so I could take this one from u if you didn't start yet.
