### ISSUE TITLE
Make part of next color picker visible in color pickers scroll bar

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17443]
Followup of https://github.com/status-im/status-mobile/pull/17405 cc @OmarBasem 

Discussed [here](https://discord.com/channels/624634427930312714/928625369542713396/1156865341092274256)

Currently part of next color picker is not visible wich makes it not obvious for user that color pickers are scrollable. 

We should make part of next color picker visible as it is shown on the designs 

**Expected result:** 

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2241-250931&mode=design

<img width="324" alt="Onboarding for Mobile – Figma 2023-09-28 11-35-17" src="https://github.com/status-im/status-mobile/assets/97245802/6009163b-e790-4ec6-915f-2b96d4b8cb4b">

**Actual result:** 

![photo_2023-09-28 11 07 33](https://github.com/status-im/status-mobile/assets/97245802/08bb4bdf-bb63-4886-850b-b008bbfe4082)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ibrkhalil** [comment]
Hey @pavloburykh
This is how it looks like for me on 14 Pro emulator
![image](https://github.com/status-im/status-mobile/assets/33176106/8ed7412c-823c-4ca4-b165-ac0ad9e6eda9)
May I know what device you're using for testing this?

**Comment by pavloburykh** [comment]
> May I know what device you're using for testing this?

Hi @ibrkhalil 
This is how it looks for me

**iPhone X:**

![photo_2023-09-28 11 07 33](https://github.com/status-im/status-mobile/assets/97245802/42c98bec-7294-4729-9529-bc55469f624d)


**Samsung Galaxy A52:**

![photo_2023-09-28 11 07 35](https://github.com/status-im/status-mobile/assets/97245802/d701e94b-316c-4572-a26c-4b1ee0eede45)

**Comment by ibrkhalil** [comment]
Thinking more about implementing it, I think it's not possible to make the same look on all devices while having each circle the same width because devices have different widths and the number of visible circles and how they look is very much dependant on device width.
So I'd ask permission from Design to allow me to make the widths of the circles dynamic (By finding their ratio for iPhone 11 Pro and applying that for all devices)
CC: @Francesca-G
I used ratios in my branch and this how it looks like with a ratio applied instead of values.

![CleanShot 2023-10-08 at 19 51 44](https://github.com/status-im/status-mobile/assets/33176106/44952db9-fd67-4bf4-8098-e1a4c4bb5488)

**Comment by OmarBasem** [comment]
@ibrkhalil we can make the margins dynamic

**Comment by ibrkhalil** [comment]
> @ibrkhalil we can make the margins dynamic

Let me give it another attempt with dynamic margins and report back.
I tried it already yesterday but couldn't get it to look good enough.
Maybe I missed something..

**Comment by OmarBasem** [comment]
@ibrkhalil A circle's total size is its width plus its margin. So making the width dynamic or the margin dynamic should give the same result

**Comment by Francesca-G** [comment]
> Thinking more about implementing it, I think it's not possible to make the same look on all devices while having each circle the same width because devices have different widths and the number of visible circles and how they look is very much dependant on device width. So I'd ask permission from Design to allow me to make the widths of the circles dynamic (By finding their ratio for iPhone 11 Pro and applying that for all devices) CC: @Francesca-G I used ratios in my branch and this how it looks like with a ratio applied instead of values.
> 
As mentioned [here](https://discord.com/channels/624634427930312714/928625369542713396/1156875457854181393) we shouldn't change the circle size but margins between circles should be flexible :)

**Comment by ibrkhalil** [comment]
Ookay, Let me give it a shot.

**Comment by cammellos** [comment]
@ibrkhalil could you give us an update on this one please?

**Comment by ibrkhalil** [comment]
> @ibrkhalil could you give us an update on this one please?

I mentioned @pavloburykh on the PR, Telling him that I did the dynamic margin and it's ready for a rereview

**Comment by pavloburykh** [comment]
> I mentioned @pavloburykh on the PR, Telling him that I did the dynamic margin and it's ready for a rereview

Thank you. I will review today and provide feedback in the PR.
