### ISSUE TITLE
Wallet - Add new assets to a wallet

### ISSUE THREAD

**Issue by x-goose-x** [status-im/status-react#1745]
### User Story

As a user, I want to be able to add other assets to the wallet in the main wallet screen so that I can see my token balance across all assets.

### Description

*Type*: Feature

*Summary*: The main wallet screen currently reflects ETH balance. User can provide details to have custom ERC20 token listed 

This will add an `Add Asset` button to the main wallet screen, which will allow the user to provide ERC20 token details then used to add this asset user amount in main list

**Comment by sla-shi** [comment]
More details in #1722
