### ISSUE TITLE
Implement browser main view

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#17460]
Implement browser main view:

As part of this task, you should implement the browser main view.
A fair amount of components should be already available, while for the remaining they should be created according to the guidelines and and added to the quo preview system.

### Figma
https://www.figma.com/file/VsV8jYZc7jYUHkPkOUrkyR/Browser-for-Mobile?node-id=811%3A13670&mode=dev

The quo2 components ("dApp Item", "dApp Favourites" and "New Tab") can be seen in isolation here: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=927-27391&mode=design&t=7gHBFHYSc5E8Z8Ks-0

For quo2 components the guidelines can be found here: 
 https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md
 these components should be created in src/quo2/components and exported from quo2/core.cljs
 
 following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md
 and also https://github.com/status-im/status-mobile/blob/develop/src/quo2/README.md
 
please also add some basic component tests for these -  https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md

**Comment by ndlonghi** [comment]
Hi, I got the project set up, but I have a couple of questions:
1. @cammellos : every time I make a change the whole app restarts (seems like fast refresh is not working properly), is there some way to fix it? any ideas of what I may be doing wrong or is it normal behavior?
2. @pedro-et should I ask you for access to figma?

CC: I'm talking here because I couldn't find you on Discord

**Comment by cammellos** [comment]
@ndlonghi we have our own hot reload system, you should disable fast refresh and restart the app, I'll chase @pedro-et for access tomorrow and we can create a group chat on discord

**Comment by ndlonghi** [comment]
Hi, please don't forget about this, specially about access to designs. Thanks

**Comment by cammellos** [comment]
@ndlonghi sent you a friend request & you should have access to the designs

**Comment by ilmotta** [comment]
Closing as _not planned_ because the browser feature is currently not implemented and descoped.
