### ISSUE TITLE
Syncing - Scanning QR code to set up secondary device does nothing

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17474]
# Bug Report

When the user tries to set up a secondary device by scanning the QR code on their current primary device during the onboarding phase, nothing is shown, and nothing is logged as well. It's as if literally nothing is happening.

#### Expected behavior

The user can proceed with syncing after scanning the QR code.

### Reproduction

1. Install the desktop client from from https://ci.infra.status.im/job/status-desktop/job/master/3438/, commit `9c1bd1`
2. Install the mobile client on Android, revision fe404ab005f9de2d6c550aa3e7be1900335408fa (I used `make release-android` to do a fresh install on the real device).
3. Create an account `A` on the desktop client, go to Syncing and generate a sync QR code.
4. In the mobile client, in a fresh install, tries to scan the QR code. Then nothing happens on screen.

Android 13, Samsung Galaxy A71

### Logs

These logs are generated from a fresh install on the mobile device, pressing "Sign in" in the onboarding screen, accepting the camera permission and scanning the QR code in the desktop client.

```
t=2023-10-02T13:47:01+0000 lvl=info msg="logging initialised" logSettings="{\"Enabled\":true,\"MobileSystem\":false,\"Level\":\"INFO\",\"File\":\"\\/storage\\/emulated\\/0\\/Android\\/data\\/im.status.ethereum\\/files\\/Download\\/geth.log\"}"
t=2023-10-02T13:47:01+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-02T13:47:01+0000 lvl=info msg="Network state change" package=status-go/api.GethStatusBackend old=unknown new=wifi
t=2023-10-02T13:47:29+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-02T13:47:30+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-02T13:47:46+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-02T13:47:47+0000 lvl=warn msg="messenger nil, not reporting app state change"
```

### Notes

In the mobile device, I created a separate account `B` (not synced), and made it friends with `A` (in the desktop client), just to see if both clients can exchange messages, and they did, so everything is working normally as far as I tested.

**Comment by churik** [comment]
@ilmotta would you mind to add logs? `adb logcat` ?

**Comment by ilmotta** [comment]
Will do @churik

**Comment by churik** [comment]
I believe it should be improved in 1.26 significantly - the error has to be shown or the issue itself should be fixed. 
When you have capacity @ilmotta would be awesome to try to reproduce this - if it is not reproducible, we can close the issue, thank you!

**Comment by ilmotta** [comment]
@churik, I believe the original problem has been significantly improved after @qfrank made a few improvements some weeks ago (I can't pinpoint exactly when). I will try to reproduce this issue again this week to see if we can close it.

**Comment by ilmotta** [comment]
@churik, I'm closing this issue because I just verified it's not reproducible anymore due to sync improvements made in the last month by @qfrank. 

------

I just found a small bug while testing this issue, but it's unrelated. Reproduction steps on Android 13:

Bug: **Camera is not shown after pressing "Try again" after sync failure. User is forced to go back to first screen and press "Sign in" again to arrive at "Scan QR code" tab.**

1. Enable firewall, blocking all ports in the high range on the primary device or some other way to force sync to fail.
2. Try to sync from the "Scan QR code" screen.
3. Once the QR code is scanned, you should see a screen similar to what's shown below, but probably with a different error message than mine.
4. Press "Try again" to go back.
5. You'll now arrive at the previous screen, but the camera won't be shown anymore, you will need to go back one more screen and press "Sign in" again.

Note: I think ideally the user shouldn't see low-level error messages, especially in the in-app notification like in the screenshot.

<img src="https://github.com/status-im/status-mobile/assets/46027/07b3ce74-786e-42d6-ab94-244cf0a3a214" width="375" />
