### ISSUE TITLE
"Recent" album in photo gallery misses images count

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17486]
**Steps:** 

1. Open any chat
2. Open photo selector (tap on Gallery button in the composer) 
3. Open list on the albums by tapping the name of currently opened album
4. Pay attention if "Recent" album has images counter

**Actual result:** "Recent" album misses images count

![photo_2023-10-03 17 49 43](https://github.com/status-im/status-mobile/assets/97245802/065a0e7c-fd35-4ca6-b89e-9e5a4191ae3e)

**Expected result:** 

[Figma](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372320&mode=design&t=B4uH12Zwl7Sy0PYH-0) 

<img width="213" alt="Composer for Mobile – Figma 2023-10-03 17-53-41" src="https://github.com/status-im/status-mobile/assets/97245802/7e754639-79c4-4216-86dd-17ece8039add">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ibrkhalil** [comment]
What should the recent count be?
All images?

**Comment by pavloburykh** [comment]
> All images?

@ibrkhalil all images which "Recent" folder includes.
