### ISSUE TITLE
Sometimes the "Sign in" screen animation gets stuck in you open and close it several times

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17499]
# Bug Report

## Problem 

Originally reported by @Francesca-G in 1.25 design review: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-67316&mode=design&t=ckBZsH8vjzt83XB4-4

I wasn't able to reproduce it exactly as shown in her screenshot (below the video), but here's what I got:

https://github.com/status-im/status-mobile/assets/67952253/5bf9ba77-6a13-4c5e-a42b-10fbb877ed70

Looks similar (problem with animation not working properly) but let me know if these are different issues

<img width="341" alt="Screenshot 2023-10-04 at 10 42 13" src="https://github.com/status-im/status-mobile/assets/67952253/9b908db5-3947-4cfb-8950-ae3ce9df2f86">

### Reproduction

1. Install Status
2. Quickly open and close the `Sign in` screen multiple times

### Additional Information

- Status version: nightly 4/10
- Operating System: iOS, Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
was not able to reproduce it on nightly 21/06/24 (IPhone 14, Google Pixel7)

 Reopen if still relevant.
