### ISSUE TITLE
[Android] Unexpected lines are shown in the chat

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17497]
### Steps:
1. Open any chat
2. Sent at least  4-5 messages
3. Check the chat

### Actual result:
Unexpected lines are displayed between messages in the chat.
![image](https://github.com/status-im/status-mobile/assets/52490791/504f740b-5923-41a1-9355-607109bfd456)

### Expected result:
No lines should be displayed between messages in the chat, providing a clean and uncluttered conversation view.

### Device:
Pixel 7a, Android 13

### ENV:
Nightly [4 Oct 2023]

**Comment by clauxx** [comment]
@VolodLytvynenko  I can't seem to reproduce it on device nor simulator:

<img src="https://github.com/status-im/status-mobile/assets/21865759/a24d4372-ed80-4477-ade1-5449e3427a43" width=250 />

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I can't seem to reproduce it on device nor simulator:
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/21865759/272935295-a24d4372-ed80-4477-ade1-5449e3427a43.png">

hi @clauxx Apologies for the initial lack of device details in the issue report. 

After further investigation, I discovered that the issue doesn't occur on Android Studio emulators or on real iOS devices. However, it consistently happens on a Pixel 7a with Android 13 for both me and @qoqobolo. 

https://github.com/status-im/status-mobile/assets/52490791/c3b42524-b066-44cc-8e63-19fd7c0163df


hope logs might help to understand what going on
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/12820392/Status-debug-logs.2.zip)

**Comment by clauxx** [comment]
Thanks for the update. I can't test it on a Pixel 7a, so will un-assign myself and leave it for somebody that has a device.

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko there is a temporary solution that i sent PR for it and a permanent solution for it in #17241 , so i guess we can wait for Upgrade RN PR and i will close my PR . JFYI

**Comment by cammellos** [comment]
Removing from milestone

**Comment by churik** [comment]
Not reproducible anymore on nightly 21/06/24 (IPhone 14, Google Pixel7)
