### ISSUE TITLE
Design review: Onboarding identifiers

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#17502]
- [ ] 1. Spacing between header and card is too small - [comment](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#569640200)
- [ ] 2. Update button copy (Skip -> Continue) - [comment](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#569640475)

**Comment by BalogunofAfrica** [comment]
2 fixed by https://github.com/status-im/status-mobile/pull/17487

**Comment by BalogunofAfrica** [comment]
1 is also fixed, can't find the PR linked to this fix
