### ISSUE TITLE
Follow up: Wallet - Add address to watch

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17501]
Follow up to https://github.com/status-im/status-mobile/pull/17479.

- [x] Add button at the bottom when `bottom actions` component is completed https://github.com/status-im/status-mobile/pull/17190
- [ ] Find out if it is possible to change text input font on the fly to update font from regular to monospace when starting to type

**Comment by J-Son89** [comment]
@OmarBasem - still relevant?
