### ISSUE TITLE
Design review (onboarding): create profile

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#17508]
* [ ] 1. "Create profile" title should not opaque on scroll - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:153&mode=design#567046822)

**Comment by alwx** [comment]
There should be a better approach to this because we have multiple screens with the same issue (for example, the login screen or the account selector screen). Maybe some umbrella issue needs to be created instead.

**Comment by ilmotta** [comment]
Closing this issue because in the new simplified onboarding the user won't be able to pick a customization color, so the scroll issue won't be a problem https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15097-57508&node-type=frame&t=fV27maAYcPlrz1gn-0
