### ISSUE TITLE
wrong message preview animation

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#17517]
# Bug Report

> preview of message should be the  original message that animates into postion rather than showing a new one that appears from the bottom.

design feedback: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8259&mode=design#567178407

<img width="826" alt="CleanShot 2023-10-04 at 20 16 27@2x" src="https://github.com/status-im/status-mobile/assets/15090582/603363e9-4acf-494a-bfdf-f8d13d0a8125">

**Comment by Samyoul** [comment]
Whoever picks this item up ping @Parveshdhull because he knows more about this.
