### ISSUE TITLE
Wrong margin around on-long-press menu separator

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#17515]
# Bug Report

1.24 feedback: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510223774
1.25 feedback: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8249&t=BpzZ5GTnwcCRiIIf-0&locale=en&type=design#567184094

**Comment by BalogunofAfrica** [comment]
Seems to have been fixed here:

https://github.com/status-im/status-mobile/commit/933a5a1a9e4d2a4a151a935c33c5c78127d70258#diff-d331c0a53edd85acc0ee32875a27f6c561724a000c7953365c8055a829f5895dR235
