### ISSUE TITLE
The app becomes stuck on sync process and 'logged in keyID not the same as keyUID in payload' error is shown when syncing via profile

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17518]
### Steps:
1. User A: Generates a QR sync code (mobile or desktop user, no matter)
2. User B: Goes to Syncing  -> tap [+] -> Scan or enter sync code (now the "Oops, something went wrong" screen is shown with 'logged in keyID not the same as keyUID in payload' error)
3. Tap 'try again' button

### Actual result:
-  'logged in keyID not the same as keyUID in payload' error shown after syncing
- The app is stuck on sync process

https://github.com/status-im/status-mobile/assets/52490791/dddc0b4b-0ec9-4272-b8f5-6e22bf558a86

### Expected result:
Error should be shown and user should be able to sync new QR

### Device:
- IOS and Android

### ENV:
[4 Oct 2023]

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12803414/Status-debug-logs.zip)

**Comment by churik** [comment]
@VolodLytvynenko User A and User B are different users, did I get the issue correctly?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko User A and User B are different users, did I get the issue correctly?

@churik correct

**Comment by cammellos** [comment]
This is not supported, if user A & user B are two different users (i.e different seed phrases), and we are trying to pair the two, it should show an error, so the behaviour seems correct to me, or am I misunderstanding?

**Comment by churik** [comment]
@cammellos 
Yes, this is a bug in the issue - we need to show an error, you're right, but instead of this the user ends up there:
![image](https://github.com/status-im/status-mobile/assets/4557972/5c41e978-2920-4aa4-8a45-92644736ad11)

**Comment by mohsen-ghafouri** [comment]
Hi @VolodLytvynenko , please let me know if this is the correct behavior, i will send PR then. 

https://github-production-user-asset-6210df.s3.amazonaws.com/71308738/281714520-c61a2b2d-6783-453c-aaa6-3c9465b5a976.mp4

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko , please let me know if this is the correct behavior, i will send PR then.
> 
>  Simulator.Screen.Recording.-.iPhone.11.Pro.-.2023-11-09.at.14.21.26.mp4

hi @mohsen-ghafouri yes. This behavior is incorrect. The correct behavior in case of valid sync code entering is the following:  
    **Given** UserA generates a valid sync code
    **When** UserB enters the generated sync code
    **Then** UserA should be synced with UserB (navigated to sync process page)
The design for this flow [here](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=4121-312197&mode=design&t=S4uuDKBO17yHIqnC-0) 

By the way, the error page shown in your recording is valid only in cases where something goes wrong :) . Unfortunately, I don't have the answer yet for which exactly events (errors, environments) the "something went wrong" page should be shown, but definitely not in case of valid sync code pasting. 
I'll ask sync crew team to see if anyone has insights

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko i think this issue is just related to sync failure scenario. User A and User B in my video are 2 different users so the sync failed with this toast message 'logged in keyID not the same as keyUID in payload' and it shows the error page. i just found there is an issue when you click on try again and i just tried to fix that.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko i think this issue is just related to sync failure scenario. User A and User B in my video are 2 different users so the sync failed with this toast message 'logged in keyID not the same as keyUID in payload' and it shows the error page. i just found there is an issue when you click on try again and i just tried to fix that.

Hi @mohsen-ghafouri, I've reread the comments on this PR, and I completely agree with you. That's the correct behavior. Thanks!
