### ISSUE TITLE
Local Storage and cookie get deleted upon closing the app

### ISSUE THREAD

**Issue by wighawag** [status-im/status-react#1751]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I expect my game/app saved data to be still there after closing and reopening the status app

As a developer, I expect to be able to save my user's data so when the users come back I can let them continue where they left off. 

In the worst case, if status do not want to support saving local storage and cookie across restart, it should disable them entirely so the dapp can explain to the user that data cannot be saved locally

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # I consider it a bug. Many dapp will require data to be saved locally. For a game it can be the sound preferences but for more complex games it can be a lot more. In case of smart contract enabled dapp, there is often the need to store secret between 2 transactions too.
This is what local storage can be used for

But cookies are also useful for session related stuff.

Both cookie and local storage get reset upon closing status.im

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- navigate to any wesbite that save data to local storage or cookie
- force close Status
- Open Status
- navigate again to the website

### Solution
- ensure local storage and cookie are saved across restart

(if not possible, it would be better to disable local storage and cookie entirely so the dapp can let the user know that saving data is not possible)

### Additional Information
* Operating System: Tested only on Android

**Comment by wighawag** [comment]
Any update on this ?

**Comment by yenda** [comment]
@flexsurfer isn't it fixed already ?

**Comment by jeluard** [comment]
Closing as too old. Please reopen with specifics if needed.

**Comment by cammellos** [comment]
@flexsurfer closing this for now, I take it has been fixed, feel free to re-open if not  the case

**Comment by flexsurfer** [comment]
we clear storage on sign in because we don't want to share it between multiaccounts, so we need somehow store the previous account and clear only if it has changed

**Comment by wighawag** [comment]
Hi @flexsurfer , do you mean, you are planning to delete the storage if the user switch account back and forth ?

This would not be what users expect .You'll need to keep the local storage for each multi account separately, so they are retrieved when logged in.
if this is not possible, `localStorage.setItem` should then throw to not give false expectation to users and applications

**Comment by flexsurfer** [comment]
yeah , thanks, if possible we should first try to switch

**Comment by churik** [comment]
can be closed in favour of https://github.com/status-im/status-mobile/issues/10309
