### ISSUE TITLE
Posts & attachments - Pinned messages drawer - Avatars have identicon rings

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17525]
# Bug Report

The avatar shown in the pinned messages context drawer has an identicon ring.

<img src="https://github.com/status-im/status-mobile/assets/46027/4aa3747d-9f67-404c-88fe-3c690f0919ba" width="375" />

## Expected 

No identicon ring should be display in the context drawer.

<img width="375" alt="Pinned Message" src="https://github.com/status-im/status-mobile/assets/46027/b1af52cc-184c-4ebb-8931-b951b921f810" />

## Resources

Reported at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380080&mode=design&t=tqru9be4o4mYQhQm-0

**Comment by yqrashawn** [comment]
Fixed localy, PR not created yet, put screenshot here

![simulator_screenshot_C93A5154-BCC8-462B-AAE4-E54872EA0159](https://github.com/status-im/status-mobile/assets/15090582/15d4f6ae-e448-4d13-b8ce-af4b9811d081)
