### ISSUE TITLE
Posts & attachments - Pinned messages drawer - Add empty state illustration

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17522]
## Problem

Missing implementation for the empty state for pinned messages. There should be an illustration.

<table>
  <thead>
    <tr>
      <th>Actual</th>
      <th>Expected</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/23732992-5c9a-4ddd-930e-d659921b84b7" width="375" /></td>
      <td><img width="375" src="https://github.com/status-im/status-mobile/assets/46027/edd92b8a-1f73-45cd-a329-1d4b056256df"></td>
    </tr>
  </tbody>
</table>

### Resources

Reported at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380099&mode=design&t=tqru9be4o4mYQhQm-0

**Comment by alwx** [comment]
Gonna be done in combination right after the picture for empty state is added in Figma file.

https://github.com/status-im/status-mobile/issues/17522
https://github.com/status-im/status-mobile/issues/17523
https://github.com/status-im/status-mobile/issues/17524
https://github.com/status-im/status-mobile/issues/17527
