### ISSUE TITLE
Posts & attachments - Pinned messages drawer - incorrect spacing between name and message

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17527]
# Bug Report

In the pinned messages context drawer, the spacing between the name and message are incorrect.

<img src="https://github.com/status-im/status-mobile/assets/46027/404fce18-7197-4164-a2f5-bee113fe846f" width="600" />

## Expected

<img src="https://github.com/status-im/status-mobile/assets/46027/eb74d8b4-edda-4fe5-8d9e-46a5a645105b" width="600" />

## Resources

Reported at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380080&mode=design&t=tqru9be4o4mYQhQm-0

**Comment by alwx** [comment]
Gonna be done in combination right after the picture for empty state is added in Figma file.

https://github.com/status-im/status-mobile/issues/17522
https://github.com/status-im/status-mobile/issues/17523
https://github.com/status-im/status-mobile/issues/17524
https://github.com/status-im/status-mobile/issues/17527
