### ISSUE TITLE
Posts & attachments - Pinned messages drawer - Empty state text doesn't match Figma

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17523]
# Bug Report

The pinned message empty state text should have a line break and should use two lines.

<table>
  <thead>
    <tr>
      <th>Actual</th>
      <th>Expected</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/02eabca7-f2c6-42d2-a178-89f1e2d8a1d0" width="375" /></td>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/edd92b8a-1f73-45cd-a329-1d4b056256df" width="375" /></td>
    </tr>
  </tbody>
</table>

## Resources

Reported in: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380099&mode=design&t=tqru9be4o4mYQhQm-0

**Comment by alwx** [comment]
Gonna be done in combination right after the picture for empty state is added in Figma file.

https://github.com/status-im/status-mobile/issues/17522
https://github.com/status-im/status-mobile/issues/17523
https://github.com/status-im/status-mobile/issues/17524
https://github.com/status-im/status-mobile/issues/17527
