### ISSUE TITLE
Visible additional ring inside identifier ring on Identicon tab

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17529]
### Steps:
1. Set up image during onboarding
2. Open the Identifier page.
3. Navigate to the Identicon tab.
4. Check the avatar

### Actual Result:
An additional ring is slightly visible inside the identifier ring on the Identicon tab.

![image](https://github.com/status-im/status-mobile/assets/52490791/bd05e531-dfd5-4833-9a29-6f73caec5319)

### Expected Result:
The identifier ring should display without any additional or visible rings

### ENV:
Nightly: 4 Oct 2023

**Comment by yqrashawn** [comment]
fixed locally, PR not created yet, put screenshot here
<img width="105" alt="CleanShot 2023-10-05 at 10 20 04@2x" src="https://github.com/status-im/status-mobile/assets/15090582/5c62591f-30e7-4b93-bb0b-94e550595f75">
<img width="81" alt="CleanShot 2023-10-05 at 10 19 03@2x" src="https://github.com/status-im/status-mobile/assets/15090582/4d8bbe02-1a4f-4c12-a617-61d78612374f">
![Simulator Screenshot - 11p - 2023-10-05 at 10 20 03](https://github.com/status-im/status-mobile/assets/15090582/2d5becb4-2a38-4515-b5e5-16337f0aff0e)
