### ISSUE TITLE
Identifier rings wrong displaying for recovered user with backed up ENS

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17526]
### Steps:
1. Recover user with backed up ENS (You can use the following seed phrase: `fatigue inquiry accident utility today tone renew steak lawn reject found lawn`)
2. Go to the identifier screen
3. Wait until the identicon tab is shown 

### Actual result:
- The contour of the ring is highlighted, but the identifier rings do not appear for the current user with backed-up ENS.
![image](https://github.com/status-im/status-mobile/assets/52490791/777f9ddf-1ba3-4369-b42d-df50ad636c04)

### Expected result:
Design is required @status-im/design-team https://discord.com/channels/624634427930312714/978950099910676480/1153626751071698974

### ENV:
Nightly [4 Oct 2023]

**Comment by yqrashawn** [comment]
last checked, design not ready yet 
design probably will be added at https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2885-319352&mode=design&t=pFL851mR5dl6KYsC-4

**Comment by ilmotta** [comment]
Closing as _not planned_ because we're descoping further fixes/improvements related to identity rings. For more context see https://github.com/status-im/status-mobile/issues/20617
