### ISSUE TITLE
Underlay view shows when chat is over scrolled

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#17538]
# Bug Report
When a user over-scrolls on the chat on it bounces, thereby revealing the underlay (parent) view

Design review here: [https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#567179730
Figma https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6142-39869&mode=design&t=ubqE6hsvEReLwNyb-0#567179730](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:45897&mode=design#567159058)

**Comment by pavloburykh** [comment]
@BalogunofAfrica hello! Please leave reply to every Figma comment that you take into work. In case if you log issues related to the comment reply should contain a link to this issue. Check the [message](https://discord.com/channels/1103692771585433630/1103692773363810317/1159792397497147443) left by @Samyoul today. Thank you!
