### ISSUE TITLE
Design review: chats / top bar

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#17530]
Figma: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6142-39869&mode=design&t=F1FEhvRES6X5T8vX-0

1. Animations might end up in a weird state when the text is cut off or when some elements are covered by other.
<img width="344" alt="Screenshot 2023-10-04 at 15 56 17" src="https://github.com/status-im/status-mobile/assets/911127/5e89973b-32fd-4453-a938-e696258a9589">
<img width="381" alt="Screenshot 2023-10-04 at 15 56 45" src="https://github.com/status-im/status-mobile/assets/911127/3357a7b2-2f47-42d4-9622-b0df1cde3dc6">

---

2. Sometimes the top bar gets hidden when it needs to be shown (requires playing around to reproduce)

<img width="382" alt="Screenshot 2023-10-04 at 15 56 58" src="https://github.com/status-im/status-mobile/assets/911127/24bbb745-1cec-4cb4-b3e8-7804fd810a63">

**Comment by churik** [comment]
fixes #17582

**Comment by qoqobolo** [comment]
> 2. Sometimes the top bar gets hidden when it needs to be shown (requires playing around to reproduce)

One of the easiest ways to reproduce this is to jump between the chat view and the shell several times


https://github.com/status-im/status-mobile/assets/67952253/7bf71803-7d0c-4079-bb3d-9abdff4bc9d6

**Comment by cammellos** [comment]
1 is fixed on develop, 2 still reproducible

**Comment by ilmotta** [comment]
Closing the issue. Feel free to open if this is still relevant.
