### ISSUE TITLE
wrong color in delete and clear chat

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#17541]
# Bug Report

The delete and clear chat buttons have a wrong shade of red

Design review here: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#570738478

**Comment by yqrashawn** [comment]
Similar issue https://github.com/status-im/status-mobile/issues/17516
Found there's no color difference between mobile inspector and Figma design

**Comment by yqrashawn** [comment]
![CleanShot 2023-10-05 at 10 29 12@2x](https://github.com/status-im/status-mobile/assets/15090582/88f57bd7-b886-4ce3-9550-6312a30f4c3c)
![CleanShot 2023-10-05 at 10 28 09@2x](https://github.com/status-im/status-mobile/assets/15090582/638806a8-3bbb-467a-8d08-a255af279c47)

**Comment by BalogunofAfrica** [comment]
Yeah, same. The color is the one used in Figma
