### ISSUE TITLE
Universal/deep link in safari/chrome should auto trigger app

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#17550]
# Feature Issue

As a user, I'd like to open a `https://status.app/` URL shared from another user in Safari and **have it automatically opened in the status mobile app** if the app is already installed.

- PR: https://github.com/status-im/status-mobile/pull/17480

- design: https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=2233-305322&mode=design&t=SANbuNsTQsvxCxie-4

Note:
- **this issue focus on link in safari auto-trigger app open (when app already installed)**, feature that handle links in app (when app is in the foreground) is already implemented in https://github.com/status-im/status-mobile/pull/17480
- introduction of ios universal link: https://developer.apple.com/ios/universal-links/
- apple recommend universal link over custom scheme URL
- crew page: https://www.notion.so/Chainmakers-b78f651f5aa04539ad4ac2a93218d1a7?pvs=4

---

ios: https://status.app/.well-known/apple-app-site-association
android: https://status.app/.well-known/assetlinks.json

**Comment by yqrashawn** [comment]
got this in safari now
we need `im.status.ethereum.pr` in https://status.app/.well-known/apple-app-site-association

![IMG_5504a](https://github.com/status-im/status-mobile/assets/15090582/31b36898-5e0e-4f77-b2bd-8d586d9a4c58)

**Comment by yqrashawn** [comment]
issue created https://github.com/status-im/status-website/issues/421

**Comment by yqrashawn** [comment]
same after `im.status.ethereum.pr` added
![IMG_0330](https://github.com/status-im/status-mobile/assets/15090582/f1e32991-0a76-4600-9c7c-53f22d352fc8)

**Comment by yqrashawn** [comment]
according to this one https://stackoverflow.com/questions/74866698/how-do-i-access-apples-aasa-validator-app-search-api-validation-tool

I tried 
- apple validation, ~not found~ https://app-site-association.cdn-apple.com/a/v1/status.app
- spotify works fine https://app-site-association.cdn-apple.com/a/v1/spotify.com
- yURL iOS, ~not work~: https://yurl.chayev.com/ios-results?url=https%3A%2F%2Fstatus.app%2Fu%2FG10A4B0JdgwyRww90WXtnP1oNH1ZLQNM0yX0Ja9YyAMjrqSZIYINOHCbFhrnKRAcPGStPxCMJDSZlGCKzmZrJcimHY8BbcXlORrElv_BbQEegnMDPx1g9C5VVNl0fE4y%23zQ3shwQPhRuDJSjVGVBnTjCdgXy5i9WQaeVPdGJD6yTarJQSj&prefix=&bundle=
- yURL, Android, not work: https://yurl.chayev.com/android-results?url=https://status.app/u/G10A4B0JdgwyRww90WXtnP1oNH1ZLQNM0yX0Ja9YyAMjrqSZIYINOHCbFhrnKRAcPGStPxCMJDSZlGCKzmZrJcimHY8BbcXlORrElv_BbQEegnMDPx1g9C5VVNl0fE4y#zQ3shwQPhRuDJSjVGVBnTjCdgXy5i9WQaeVPdGJD6yTarJQSj&prefix=&bundle=
- yURL, Figma works fine: https://yurl.chayev.com/ios-results?url=https%3A%2F%2Ffigma.com&prefix=&bundle=

Maybe caused by https://status.app/.well-known/apple-app-site-association guarded by a password?

**Comment by felicio** [comment]
> For the CDN to successfully cache the file, it must be hosted on a domain that is available to all IP addreses and ranges, does not redirect, and is not blocked by access policies. – https://developer.apple.com/documentation/technotes/tn3155-debugging-universal-links#Understand-Apples-CDN

PR pending https://github.com/status-im/status-website/pull/444.

Cc @yqrashawn

**Comment by felicio** [comment]
fyi @yqrashawn, merged the above.

`curl -v https://status.app/.well-known/apple-app-site-association`

**Comment by yqrashawn** [comment]
It's working now but the user still needs to click on the button.

Maybe we need to define the paths in web or ios if we want auto-trigger, will check the doc

```json
            "appID": "8W66MEA7DD.com.spotify.client",
            "paths": [
                  "/pair",
                  "/onlyyou",
                  "/onlyyou/",
                  "/*/onlyyou",
                  "/*/onlyyou/",
                  "/wrapped",
                  "/wrapped/",
                  "/*/wrapped",
                  "/*/wrapped/"
            ]
```



https://github.com/status-im/status-mobile/assets/15090582/6f10c26c-63d4-4f4f-9a84-f05662d5b675

**Comment by yqrashawn** [comment]
for android https://join.status.im/.well-known/assetlinks.json
doc: https://developer.android.com/training/app-links/verify-android-applinks

although the link already works in android https://github.com/status-im/status-mobile/pull/17480#issuecomment-1763356811

**Comment by yqrashawn** [comment]
Hi @felicio  
Could you please add this to status.app/.well-known/assetlinks.json, Thank you!
https://join.status.im/.well-known/assetlinks.json

**Comment by felicio** [comment]
> Hi @felicio
> Could you please add this to status.app/.well-known/assetlinks.json, Thank you!
> https://join.status.im/.well-known/assetlinks.json

PR pending https://github.com/status-im/status-website/pull/491

Cc @yqrashawn

**Comment by yqrashawn** [comment]
hi @felicio could you please add another fingerprints to the `sha256_cert_fingerprints` array
it's `FA:C6:17:45:DC:09:03:78:6F:B9:ED:E6:2A:96:2B:39:9F:73:48:F0:BB:6F:89:9B:83:32:66:75:91:03:3B:9C`
and it's from the debug.keystore https://github.com/status-im/status-mobile/blob/61792d5ec711c3fe9a7a0e7224943df7c664d552/android/app/debug.keystore

Also need to add another target for `im.status.ethereum.pr`
can't find the keystore file, asking for help, will add it later

**Comment by yqrashawn** [comment]
hi @felicio, seems we use the same keystore for pr and release build, this should do
```json
[
  {
    "relation": [
      "delegate_permission/common.handle_all_urls"
    ],
    "target": {
      "namespace": "android_app",
      "package_name": "im.status.ethereum",
      "sha256_cert_fingerprints": [
        "29:58:6A:6B:A0:CA:FA:A5:38:AA:CE:EA:DF:60:55:1C:EC:22:E9:65:68:40:35:D4:75:B7:9A:0A:8B:13:E2:9F",
        "FA:C6:17:45:DC:09:03:78:6F:B9:ED:E6:2A:96:2B:39:9F:73:48:F0:BB:6F:89:9B:83:32:66:75:91:03:3B:9C"
      ]
    }
  },
  {
    "relation": [
      "delegate_permission/common.handle_all_urls"
    ],
    "target": {
      "namespace": "android_app",
      "package_name": "im.status.ethereum.pr",
      "sha256_cert_fingerprints": [
        "29:58:6A:6B:A0:CA:FA:A5:38:AA:CE:EA:DF:60:55:1C:EC:22:E9:65:68:40:35:D4:75:B7:9A:0A:8B:13:E2:9F"
      ]
    }
  }
]
```

**Comment by felicio** [comment]
fyi @yqrashawn, merged the above.

```sh
curl -v https://status.app/.well-known/assetlinks.json
```

**Comment by yqrashawn** [comment]
Thanks @felicio

**Comment by yqrashawn** [comment]
iOS PR build works on real device
build is the `#15` from https://github.com/status-im/status-mobile/pull/17465#issuecomment-1742037860

[RPReplay_Final1698041828.webm](https://github.com/status-im/status-mobile/assets/15090582/5bc59d35-3e07-4cbc-ba4f-29bcc2c6aa51)

**Comment by yqrashawn** [comment]
PR build works on android real device
one plus 5, android 9

build is the `#15` from https://github.com/status-im/status-mobile/pull/17465#issuecomment-1742037860

[23-10-23-16-01-50 - 01.webm](https://github.com/status-im/status-mobile/assets/15090582/5cf2122c-73c8-4065-9a5c-8218fb787f6f)

**Comment by yqrashawn** [comment]
iOS nightly build works on real device, no Status PR installed
`StatusIm-Mobile-231023-020800-04a7f7-nightly.ipa`

[RPReplay_Final1698049550.webm](https://github.com/status-im/status-mobile/assets/15090582/40781ddf-5a30-4c73-925d-f2fd1ecde5d6)

**Comment by yqrashawn** [comment]
android nightly build works on real device, no Status PR 
one plus 5, android 9

android build at
<img width="174" alt="CleanShot 2023-10-23 at 17 11 30@2x" src="https://github.com/status-im/status-mobile/assets/15090582/f23e6930-abdc-4cb6-87fe-aaf3dcca3ee7">



[23-10-23-17-00-29 - 01.webm](https://github.com/status-im/status-mobile/assets/15090582/95558101-f4e3-442a-b324-3d4152dfd515)

**Comment by yqrashawn** [comment]
PR build:
- iOS: https://github.com/status-im/status-mobile/issues/17550#issuecomment-1774516762
- Android: https://github.com/status-im/status-mobile/issues/17550#issuecomment-1774673168

Nightly build:
- iOS: https://github.com/status-im/status-mobile/issues/17550#issuecomment-1774697338
- Android: https://github.com/status-im/status-mobile/issues/17550#issuecomment-1774757282

Local build is still not working

**Comment by yqrashawn** [comment]
android local build works
tested on simulator

https://github.com/status-im/status-mobile/assets/15090582/f0b8087a-7ca4-49ad-9ca8-0ff05305ac45

**Comment by yqrashawn** [comment]
ok, iOS local app has `im.status.ethereum.debug` as bundle identifier

- iOS
	- release `im.status.ethereum`
	- pr `im.status.ethereum.pr`
	- local `im.status.ethereum.debug`
- Android
	- release `im.status.ethereum`
	- pr `im.status.ethereum.pr`
	- local `im.status.ethereum`

**Comment by yqrashawn** [comment]
Hi @felicio, sorry to bother you again.
Could you please add another app id to `https://status.app/.well-known/apple-app-site-association`, it's app id for iOS local build. Thanks.

```json
{
  "appID": "8B5X2M6H2Y.im.status.ethereum.debug",
  "paths": [
    "*"
  ],
  "appIDs": [
    "8B5X2M6H2Y.im.status.ethereum.debug"
  ]
}
```

**Comment by yqrashawn** [comment]
Test again for https://status.app

- android (debug and pr won't work on simulator but works on real device)
	- debug ✅
	- pr ✅ on real device (chrome works, builtin-browser doesn't work)
	- nightly ✅
- ios
	- debug ❌
	- pr ✅
	- nightly ✅

**Comment by yqrashawn** [comment]
ios debug still won't work, will try on real device

**Comment by yqrashawn** [comment]
upgraded macos to 14
upgraded xcode 15
building debug build for real device

**Comment by yqrashawn** [comment]
No luck, ios debug build still won't trigger jumping to app

**Comment by yqrashawn** [comment]
Close in favor of https://github.com/status-im/status-mobile/issues/18490
