### ISSUE TITLE
Design review: Communities/Discovery

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17557]
# Bug Report

## Issues:

- [ ] **Close Button Overlap Issue on iOS**

**Description:** The close button overlaps with the title in the iOS version.
**Screenshot/Design:** [View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#567182752)

- [ ] **Unexpected Box-Shadow on Cards**

**Description:** An unexpected box-shadow appears on the cards.
**Screenshot/Design:** [View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#570717594)

#### Expected behavior

![image](https://github.com/status-im/status-mobile/assets/5999878/d952fa0f-6167-42eb-a58b-ea36893e0e84)

#### Actual behavior

![image](https://github.com/status-im/status-mobile/assets/5999878/67144346-78e2-4fb3-a370-d841bbdd031f)
![image](https://github.com/status-im/status-mobile/assets/5999878/94b8788f-8266-44ea-b626-96ca509334a9)

### Reproduction

Navigate to Communities->Discover Communities

**Comment by BalogunofAfrica** [comment]
This whole flow has been redesigned, here: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7202-475069&mode=design&t=eetTaKihrS4bGxwX-0

Also related to: https://github.com/status-im/status-mobile/issues/17560#issuecomment-1877414660

**Comment by ajayesivan** [comment]
@BalogunofAfrica As far as I recall, the designs for the Discover screen haven't changed much. What led you to believe this design part has been changed?

**Comment by BalogunofAfrica** [comment]
> @BalogunofAfrica As far as I recall, the designs for the Discover screen haven't changed much. What led you to believe this design part has been changed?

Oh my bad then. Thought there was a difference based on the new design. Would work on this then

**Comment by BalogunofAfrica** [comment]
For the shadow issue on Android:

https://github.com/status-im/status-mobile/pull/18504 is aiming to address it

**Comment by BalogunofAfrica** [comment]
Overlap fix https://github.com/status-im/status-mobile/pull/18620

**Comment by BalogunofAfrica** [comment]
Closed by https://github.com/status-im/status-mobile/pull/18620 and  https://github.com/status-im/status-mobile/pull/18504
