### ISSUE TITLE
Design review: Communities/Join/Bottom-Sheet

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17560]
# Bug Report

[Figma File](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=LkXZMJM46LxxBKYM-0)

**Related issue**  #17559 

## Issues

**Bottom sheet**

- [ ] The context tag width should not be 100%
[View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:45899&mode=design#567167069)

- [ ] On iOS, enabling password mode doesn't automatically trigger the drawer keyboard 
[View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:45899&mode=design#567167866)

- [ ] The action button should be disabled if the password field is empty
[View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:45899&mode=design#567168340)  
 
### Reproduction

Navigate to Communities-> Join a community

**Comment by BalogunofAfrica** [comment]
There seem to be a new design for this flow as seen here:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-285065&mode=design&t=eetTaKihrS4bGxwX-0

**Comment by ajayesivan** [comment]
We are currently in the process of implementing the [new request-to-join flow](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-285065&mode=design&t=dMFvO3TTSvB4hPSh-4), and it is currently disabled in the 'develop' branch. I suggest refraining from making any design review fixes to this specific area at the moment, as the entire flow will be replaced soon.

**Comment by BalogunofAfrica** [comment]
Closing this since there's new work to be done.
