### ISSUE TITLE
Dark border around community display picture

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17565]
A dark border around the community display-picture in the request to join the community screen.

Review comment: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:55521&mode=design#567052004

### Steps to reproduce
- Open a community with a light display picture.

Already reported in the 1.24 design review https://github.com/status-im/status-mobile/issues/16862 (issue 2) and fixed, but somehow it's been reintroduced.

Reproducible on both iOS & Android

**Comment by BalogunofAfrica** [comment]
@jo-mut i believe this should be covered by the redesign for communities as seen in this board:

https://github.com/orgs/status-im/projects/100/views/1

**Comment by jo-mut** [comment]
@BalogunofAfrica unless am missing something the designs for communities have not been updated right. This issue is part of the Ui fit & Finish project board and not the communities

**Comment by ajayesivan** [comment]
@BalogunofAfrica John is correct. I apologize if our Discord conversation led to any confusion. The current feature we're implementing focuses solely on updating the request-to-join flow, initiated when a user clicks the "Request to Join" button. We aren't making changes to anything preceding that point. The issue tracked here should be addressed separately. @jo-mut, thanks for pointing it out.
