### ISSUE TITLE
Implement QR code scanner screen

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17574]
Design: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=451-18994&mode=dev

Currently, we are using a minimal version of the camera for QR code scanning.

Reported in design feedback [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:43281&mode=design#567103359)

**Comment by churik** [comment]
cross-linking with https://github.com/status-im/status-mobile/issues/17658 - would be awesome to fix it in one PR

**Comment by clauxx** [comment]
Fixed by https://github.com/status-im/status-mobile/pull/17767

**Comment by alwx** [comment]
@clauxx why did you close it? 

This is what currently happens when you click the scan QR button:
<img width="565" alt="Screenshot 2024-01-10 at 12 59 19" src="https://github.com/status-im/status-mobile/assets/911127/cf0edb6f-80f4-4298-85ea-7cbaf2ee44a5">

**Comment by clauxx** [comment]
@alwx Right, I guess we should re-define the scope of the task (or have a different one) as the scanner was updated according to the design already (see screenshot from the "add contact" flow from messages).

![0](https://github.com/status-im/status-mobile/assets/21865759/619c7314-e4be-4bd5-a77d-e8385c8154ab)

**Comment by alwx** [comment]
Yes, I will check it out today and update the issue.

**Comment by alwx** [comment]
@jo-mut wait, but you are basically doing the same in https://github.com/status-im/status-mobile/pull/18604? Why?

**Comment by jo-mut** [comment]
@alwx I am aware you are working on this, so I do not intend to merge the draft pr. I just created it incase you can pick up something from it as the screen as @J-Son89 and I had paired on this. Knowledge sharing. Thats all

**Comment by jo-mut** [comment]
@alwx looking at the scope of work particularly on this screen I think we can split this into separate issues 

I understand in some case like scanning the QR for community, channels, profiles have not been implemented. I think its okay to limit the scope of this to just adding the qr-code scan screen and follow it up with a different pr for the differnent scenarios specified in the figma. wdyt?

**Comment by alwx** [comment]
@jo-mut I think the overhead of creating different issues for different types of scanning will be bigger than doing it all in one issue, to be honest. There are certain scenarios that are a bit more complicated but most are limited to just calling one function once the QR is scanned. 
Anyway, I'll update it today if my opinion changes after taking a closer look and implementing the rest of the scenarios.

**Comment by alwx** [comment]
Encountered a bit of an issue with contact scanning and I think I will limit the PR only to it.
