### ISSUE TITLE
Design Feedback Communities: channel name isn't aligned with the left and right buttons

### ISSUE THREAD

**Issue by codemaster115** [status-im/status-react#17595]
## Problem 
[comment]: # (A problem description)
Communities channel name isn't aligned with the left and right buttons.
Design feedback: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:84651&mode=design#567170945

#### Expected behavior
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6166-44858&mode=design&t=R6v2Aqc1s3n8aahu-4
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
should be fixed by https://github.com/status-im/status-mobile/pull/17582

**Comment by pavloburykh** [comment]
> should be fixed by #17582 

Confirming the fix. Closing the issue.
