### ISSUE TITLE
Community header issues

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17601]
### ISSUE 1 Joined/pending tag overlays community banner

**Steps:** 

1. Open community screen
2. Send request to join the community
3. Pay attention at Joined/pending tags position

**Actual result:** tags overlay community banner

![photo_2023-10-10 12 23 56](https://github.com/status-im/status-mobile/assets/97245802/c87c80e8-86cf-4609-94fc-510654fb3489)
![photo_2023-10-10 12 23 59](https://github.com/status-im/status-mobile/assets/97245802/01bd6895-2afe-46f7-afc4-1fb09fd1e906)

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733-127837&mode=design&t=Eb3FaNbz3IY0FKMd-0)

<img width="335" alt="Communities for Mobile – Figma 2023-10-10 12-24-34" src="https://github.com/status-im/status-mobile/assets/97245802/6f2e3005-2427-4f9e-954e-c1fc272467e4">

### ISSUE 2 Community name and logo are located too close to the banner and go beyond the screen

**Steps:** 

1. Join community
2. Reopen home community screen
3. Pay attention at community name and logo position

**Actual result:** 

![photo_2023-10-10 12 26 44](https://github.com/status-im/status-mobile/assets/97245802/3d1a74e0-bdb4-49ea-9f9b-7e3088e5ba37)

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-409196&mode=design&t=Eb3FaNbz3IY0FKMd-0)

<img width="287" alt="Communities for Mobile – Figma 2023-10-10 12-03-35" src="https://github.com/status-im/status-mobile/assets/97245802/b7f4606f-6167-4e10-b422-452e02ce8fa0">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment]
### ISSUE 3 Community banner corners are not rounded

**Actual result:**

![photo_2023-10-13 11 42 01](https://github.com/status-im/status-mobile/assets/97245802/019aa9e7-31eb-4770-823d-b67834ebf2fc)


**Expected result:**

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-409196&mode=design&t=84Jqac74b0pKhDgm-0)

<img width="269" alt="Communities for Mobile – Figma 2023-10-13 11-34-20" src="https://github.com/status-im/status-mobile/assets/97245802/695e9c28-d881-4e7d-a7bd-dba0de06ae4d">

**Comment by pavloburykh** [comment]
Hey @alwx I have added one more issue related to community header https://github.com/status-im/status-mobile/issues/17601#issuecomment-1761143617 

If you consider this is better to be reported separately please let me know.

**Comment by churik** [comment]
Also cross-posting https://github.com/status-im/status-mobile/issues/17622

**Comment by alwx** [comment]
The thing is community header is a completely separate component that has nothing to do with top bar 😀
Working on fixing this issue, will probably be done tomorrow.

**Comment by churik** [comment]
fixed by https://github.com/status-im/status-mobile/pull/17799

**Comment by pavloburykh** [comment]
> fixed by #17799

closing this one as fixed.
