### ISSUE TITLE
Community/Discover – Discover communities not loading  

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17620]
# Bug Report
[Figma design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=BNlP5YQ740n4i2xY-0)

## Problem 
The "Discover Communities" feature is not loading on the develop branch; it's stuck at the loading skeleton. On the nightly build, it does eventually load but requires a few attempts.

#### Expected behavior
![image](https://github.com/status-im/status-mobile/assets/5999878/3eae360c-1676-4936-aeb2-b4038f00030a)

#### Actual behavior
![image](https://github.com/status-im/status-mobile/assets/5999878/32556efe-e6c4-494a-9ac5-cebfe6b708f1)

### Reproduction

1.  Navigate to Community->Discover

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
Loading for me though; 
Is is reproducible after re-login?
