### ISSUE TITLE
Community/Discover – Closing a community navigates to Community Home instead of Discover Screen

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17621]
# Bug Report

[Figma design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=BNlP5YQ740n4i2xY-0)

## Problem 
When navigating to a specific community and then closing it using the top-left button, the app navigates back to the Community Home instead of the expected Discover Screen.

#### Expected behavior
After closing the community, it should navigate back to the Discover Screen.

#### Actual behavior
It navigates back to the Community Home instead.

 

https://github.com/status-im/status-mobile/assets/5999878/dee0b4e9-c157-41a1-a297-d3f6b4ce0c2d

### Reproduction

1. Open the app and go to the Discover Screen.
2. Click on any community to navigate to that community's page.
3. Close the community by clicking the top-left button.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
fixed in https://github.com/status-im/status-mobile/pull/17586
