### ISSUE TITLE
Community/Discover – Community header design deviates from Figma mockups (corners are not rounded)

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17622]
# Bug Report
[Figma design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=BNlP5YQ740n4i2xY-0)

## Problem 
The community header in the app does not match the Figma design. Specifically, the header should be overlaid by a rounded card, an effect that is missing in the current implementation.

#### Expected behavior

![image](https://github.com/status-im/status-mobile/assets/5999878/60fd1147-3894-4216-85e4-2c09f4dddbc3)

#### Actual behavior

<img width="439" alt="image" src="https://github.com/status-im/status-mobile/assets/5999878/85f16f6e-dc4d-44f5-b487-895a7d1f5546">

### Reproduction

1. Navigate to any community page in the app.
2. Observe the header design.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
The bug reported here is fixed in this PR https://github.com/status-im/status-mobile/pull/17799, so I think we can close this one. cc @alwx
