### ISSUE TITLE
Communities/Discover – Statistics of Users and Active Users missing on Communities card

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17623]
# Bug Report

[Figma design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=BNlP5YQ740n4i2xY-0)

## Problem 
The statistics for the total number of users and active users in each community are not displayed on the communities card. It is unclear whether this feature is not yet implemented or if this is a bug.

#### Expected behavior
![image](https://github.com/status-im/status-mobile/assets/5999878/4365b662-8bdd-4daa-8822-550504bd77a5)

#### Actual behavior
![community-card](https://github.com/status-im/status-mobile/assets/5999878/a1a2a065-fef9-4dd6-ab77-9d2b628c3068)

### Reproduction

1. Open the app and navigate to the Discover Screen.
2. Observe the communities card on this screen.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
It has never been implemented, good point that we need a fallback until we're able to show these numbers (however, afaik there are some technical difficulties to display them)

**Comment by churik** [comment]
can be closed for now,  we are already showing a number of members, reopen if still relevant.
