### ISSUE TITLE
Feature: Extend Face ID Authentication Across Various Application Functions

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17630]
# Feature Issue

Face ID authentication is currently only available on the login screen and can be enabled during onboarding. This feature should be extended to various functionalities across the app for better security and user experience. 

- [x]  On **Join Community**: Display Face ID authentication instead of password Bottom Sheet when Face ID is available
[View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:45899&mode=design#567168921) logged separately here https://github.com/status-im/status-mobile/issues/19188
- [x] Enable Face ID on **Sign Transaction** (will be implemented in scope of Wallet)
- [x] Enable Face ID on **Reaveling QRCode** [View Figma Design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3682-98959&mode=design&t=idJkYQmWH5Grsbno-0)

### User Story

Face ID is only available for login and can be enabled during the onboarding process. We need to add a centralized way to enable Face ID within the app.

### Description

1. Add a centralized way to enable Face ID within the app (Profile > Post MVP?)
2. Implement Face ID authentication for joining communities.
3. Implement Face ID authentication for signing transactions.
4. Implement Face ID authentication for revealing QR codes.

### Acceptance Criteria

- [x]  Face ID option is available and can be enabled from a centralized location within the app.
- [x]  When Face ID is enabled and available, the app shows Face ID authentication as an option instead of the password Bottom Sheet.
- [x]  Face ID authentication is functional and secure when joining a community.
- [x]  Face ID authentication is functional and secure for signing transactions.
- [x]  Face ID authentication is functional and secure for revealing QR codes.
- [x]  Appropriate fallback mechanisms are in place if Face ID authentication fails (e.g., revert to password or other secure methods).
- [x]  The feature works consistently across different devices that support Face ID.
- [x]  Unit and integration tests confirm that the feature works as expected - #18694

### Notes

This is considered a bigger issue and may require subdividing into smaller tasks for easier tracking and implementation.

**Comment by J-Son89** [comment]
Thanks for this issue @FFFra - We have implemented a standard authorization mechanism - 
The feature set in this code should be used for all of these locations - wallet, syncing, communities - see pr: https://github.com/status-im/status-mobile/pull/16916

For this reason we need to extend the logic in _src/status_im2/common/standard_authentication_ to handle faceID/biometric authentication and then set that up correctly in the appropriate screens. 👍

**Comment by J-Son89** [comment]
also I believe communties should probably get updated to use the password authentication within _src/status_im2/common/standard_authentication_ for consistency across the codebase. Afaik it is currently not pointing to that code 👍

**Comment by clauxx** [comment]
@J-Son89 is this already done with `standard-authentication`, or not fully?

**Comment by J-Son89** [comment]
Nicely detailed issue @FFFra!! 🙏

**Comment by J-Son89** [comment]
@clauxx - some parts of this are done yes.

i.e we have a standard authentication module (inluding face-id/biometrics) for in app authorizations.
This still needs to be added for Communities but they were updating the flow for accounts to share/expose etc - @FFFra can you provide an update if you are using standard-authorization/ something similar there yet?

there is some other features in this issue which are not yet complete.
i.e the settings menu to enable/disable biometrics within the application.

Perhaps @mohsen-ghafouri can let us know if that is part of the pre MVP scope? and if so where are we with that?

**Comment by clauxx** [comment]
> there is some other features in this issue which are not yet complete.
> i.e the settings menu to enable/disable biometrics within the application.

@J-Son89 this part I did already

**Comment by J-Son89** [comment]
ok then we can update the issue by checking off the boxes 👍 

and how about sufficient testing?

**Comment by clauxx** [comment]
what would be sufficient testing here 😆? Tests for biometrics events and the standard-auth component-specs?

if so I'd make a separate issue for it

**Comment by J-Son89** [comment]
I was hoping to leave that criteria to you 😀 
At least one test would be great 👍 
Sure a separate issue is better. Tbh this issue is really a feature epic and should link to the other smaller issues.


Similar to this - https://github.com/status-im/status-mobile/issues/18568

**Comment by clauxx** [comment]
@J-Son89 @FFFra do you know if there's a task for adding biometrics to joining communities? cause seems like that's the only thing left here. If so, I could take it as a follow-up to the "adding tests" task after it's merged and assign myself to this one.

**Comment by pavloburykh** [comment]
> @J-Son89 @FFFra do you know if there's a task for adding biometrics to joining communities? cause seems like that's the only thing left here. If so, I could take it as a follow-up to the "adding tests" task after it's merged and assign myself to this one.

Hey @clauxx! I have logged a task on that https://github.com/status-im/status-mobile/issues/19188. So feel free to assign yourself. Thank you!

**Comment by clauxx** [comment]
Hey @pavloburykh! Thanks, but I guess it goes to a different crew :(

**Comment by pavloburykh** [comment]
> Hey @pavloburykh! Thanks, but I guess it goes to a different crew :(

Oh, I see. That's okay, devs from Community crew will take care of it then. Thank you.

**Comment by churik** [comment]
On the state of the app  nightly 21/06/24 (IPhone 14, Google Pixel7) - Join Community flow is already implemented. Closing this issue.
