### ISSUE TITLE
Wallet: New keypair followup

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17632]
New keypair ui followup: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=7823%3A76184&mode=design&t=G3PZQ3lAQZpjvuuC-1

**Comment by J-Son89** [comment]
still relevant @OmarBasem ??

**Comment by OmarBasem** [comment]
> still relevant @OmarBasem ??

Nope, not relevant anymore
