### ISSUE TITLE
Indicate progress and error in case of syncing devices

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17634]
# Bug Report

## Problem 
Currently app just stuck on the same screen in case of syncing / getting error

#### Expected behavior
1) Syncing is shown as per design [here](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179660&mode=design&t=XLVqA7gTpM88imPD-4) 

2) In case of error[]( https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179641&mode=design&t=XLVqA7gTpM88imPD-4) - or at least display an error somehow in a raw format

#### Actual behavior
Video: https://github.com/status-im/status-mobile/assets/4557972/649b3f41-629e-4327-9df4-1d5774c0a23a

### Reproduction

1. Try to sync for example devices on different networks
2. Observe the result

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@alwx how is it going with this? could you give us an update please?

**Comment by VolodLytvynenko** [comment]
The current issue occurs randomly. Here are the logs I fetched when it was reproduced.
[logs.zip](https://github.com/status-im/status-mobile/files/13177359/logs.zip)

**Comment by churik** [comment]
@VolodLytvynenko 
The reason for this task is to indicate progress and display an error, not prevent this error from happening.
It can be caused by a lot of reasons - but we need to handle an error gracefully.

**Comment by ibrkhalil** [comment]
Do you have network provided time enabled?
There's a 2 hour difference between timestamps in Status.log?, That's why certificates expired.
But I am not an expert on syncing ..
Working on the progress indication and error indication parts.
```
2023-10-26T10:31:47.724Z INFO [status-im2.contexts.syncing.events:73] - Initiated local pairing {:response "{\"error\":\"Get \\\"https://192.168.35.132:43517/pairing/challenge\\\": x509: certificate has expired or is not yet valid: current time 2023-10-26T10:31:47Z is before 2023-10-26T12:31:40Z\"}", :event :syncing/input-connection-string-for-bootstrapping}
```

**Comment by siddarthkay** [comment]
There is a known issue in android emulators. Their clocks are not reliable.
When attempting to sync you can try on iOS Simulator with iOS Real Device or Android Real Device.

**Comment by ibrkhalil** [comment]
> There is a known issue in android emulators. Their clocks are not reliable. When attempting to sync you can try on iOS Simulator with iOS Real Device or Android Real Device.

Thank you!
Let's wait for @VolodLytvynenko to tell us if he reproduced it on emulator or physical device.

**Comment by siddarthkay** [comment]
yeah however the ask here to show some form of progress indicator during syncing process. 
Sometimes it takes many seconds to get feedback from UI so this issue is created to tackle that and provide feedback to user when syncing is in progress

**Comment by BalogunofAfrica** [comment]
When on different networks and scanning from`Android`, we get this error from `status-go` `failed to connect to any of given addresses. failed to connect to any of given addresses. IP 192.168.x.xx: connecting to 'https://192.168.x.xx:49507' failed: dial tcp 192.168.x.xx:49507: i/o timeout; `. With the same condition (different networks) and scanning from `iOS`, we do not get any response from `status-go`, hence no way for the UI to know the current state and what to do next.

**Comment by siddarthkay** [comment]
Hi @BalogunofAfrica : is this on Android Emulator or real device?
cc @qfrank

**Comment by BalogunofAfrica** [comment]
> Hi @BalogunofAfrica : is this on Android Emulator or real device? cc @qfrank

It is a real device, Pixel 4a.

**Comment by siddarthkay** [comment]
I think staying on same network is a core requirement for local pairing 🤔?
cc @Samyoul

**Comment by BalogunofAfrica** [comment]
> I think staying on same network is a core requirement for local pairing 🤔? cc @Samyoul

Yeah, it is a requirement and we stated it in the UI. But in a case where the user still tries to carry out this task while on different networks there's no error response for iOS from `status-go`, but we do get an error response for Android.

**Comment by qfrank** [comment]
> > I think staying on same network is a core requirement for local pairing 🤔? cc @Samyoul
> 
> Yeah, it is a requirement and we stated it in the UI. But in a case where the user still tries to carry out this task while on different networks there's no error response for iOS from `status-go`, but we do get an error response for Android.

thank you @BalogunofAfrica , i'll look into this
