### ISSUE TITLE
Community/Discover/Home – Header animation lacks smoothness during scrolling

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17635]
# Bug Report

## Problem 
Header animation exhibits inconsistencies when scrolling (Design Team confirmation pending)

- [ ] Address header animation issue on Discover screen
- [ ] Rectify animation glitches on Community Home screen

#### Expected behavior
Header animations should provide a smooth and consistent user experience during scrolling.

#### Actual behavior
Animations for the header appear jittery or inconsistent while scrolling.

**Discover:**

https://github.com/status-im/status-mobile/assets/5999878/6c37f07a-a903-4a4f-91b8-50d17dff696e

**Community Home:**

https://github.com/status-im/status-mobile/assets/5999878/d97923c7-f7d8-4d5e-b320-39cef92a6c1f

### Reproduction

1. Navigate to either the Discover or Community Home screen.
2. Scroll up and down to observe the header animation behavior.

### Additional Information

- Status Version: nightly, develop 
- Operating System: Android, iOS

**Comment by churik** [comment]
Still can see the issue with the header (spacing), attaching video from nightly 21/06/24 (IPhone 14):

https://github.com/status-im/status-mobile/assets/4557972/0b7fdfdb-86bd-44c0-8417-5b5cd350c567

**Comment by ilmotta** [comment]
Closing as _not planned_ because animation work is currently descoped.
