### ISSUE TITLE
Wallet: Buy token drawer

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17644]
Implement the wallet buy tokens drawer displaying the different third-party suppliers

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1581-361927&mode=design&t=MfTrnyDwZ3NuydVK-0

**Comment by J-Son89** [comment]
I added this issue to the Wallet project board :)

**Comment by OmarBasem** [comment]
> I added this issue to the Wallet project board :)

Thank you :)
