### ISSUE TITLE
App hangs on key generation screen for iOS

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17646]
### Actual Behavior:
- The app hangs on the key generation screen
![image](https://github.com/status-im/status-mobile/assets/52490791/94697554-e85d-4cf4-80f5-75dc65f84f13)

- DB is dirty after migration version 16971123149 error is shown if to attempt to reopen the app and to try login
![image](https://github.com/status-im/status-mobile/assets/52490791/4bb24980-bfa0-4d6d-bc91-0cf5cf55f246)

### Expected Behavior:
The app should generate keys and progress to the next screen without hanging or becoming unresponsive.

### Device:
- IOS

### Logs:
[geth.log](https://github.com/status-im/status-mobile/files/12914406/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/12914408/Status.log)

**Comment by VolodLytvynenko** [comment]
The issue is reproduced on the last build of the [this](https://github.com/status-im/status-mobile/pull/17573) PR

**Comment by churik** [comment]
was introduced by  https://github.com/status-im/status-go/pull/4153

**Comment by qoqobolo** [comment]
Fixed in https://github.com/status-im/status-mobile/pull/17642
