### ISSUE TITLE
Implement discover communities screen jump-to animation

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#17665]
### Summary

leftover from https://github.com/status-im/status-mobile/pull/17586

- [ ] As the discover communities screen doesn't have its card, it should be minimized to the communities bottom tab on pressing jump-to (Discuss with the design team for animation details)
- [ ] Open communities discover screen in the background when opening community using the switcher-card, which was originally minimized with the communities discover screen. (more details: [issue](https://github.com/status-im/status-mobile/pull/17586#issuecomment-1764417639), [discord](https://discord.com/channels/624634427930312714/928625369542713396/1163473020887781477))

**Comment by ilmotta** [comment]
Closing because Jump To feature is disabled and descoped.
