### ISSUE TITLE
Notifying toast is not shown for member when user joins the community

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17676]
### Steps:
1. `User A`  is owner the community
2. `User A` is online
3. `User B` joins a community.
4. `User B` checks the received toast

### Actual result:
Toast is not shown after `User B` joins the community

### Expected result:
You  joined to  "community name" toast is shown
![image](https://github.com/status-im/status-mobile/assets/52490791/b62fd7c8-4db9-4624-8222-18cec7f8fc9a)

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1386-110589&mode=design&t=bfQAViAhM9H82Gpk-0

### ENV:
- Nightly [18 Oct 2023]

**Comment by jo-mut** [comment]
I have been having network issues for a while now  which makes it hard to reproduce and work on this issue. I am unassigning myself this reason to pick up something else i can work on in the meantime
