### ISSUE TITLE
Wallet: Receive screen

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17677]
Implement wallet receive screen initial UI

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=850-220368&mode=design&t=zSIydpOKhjRVcuga-0

**Comment by OmarBasem** [comment]
Dependency: https://github.com/status-im/status-mobile/issues/17023

**Comment by J-Son89** [comment]
@OmarBasem should you be assigned to this? 🤔
