### ISSUE TITLE
Wallet: Share QR Code 

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17693]
Implement wallet legacy and wallet multichain share qr codes

Designs: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1338-34510&mode=design&t=f0Y1oqYS1As0ss5R-0

**Comment by smohamedjavid** [comment]
Duplicate of https://github.com/status-im/status-mobile/issues/17023
