### ISSUE TITLE
Debug mode -> On makes /location message shown as plain text when sent right after [1710]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1770]
### Description

*Type*: Bug

*Summary*: if i send `/location` command in Console chat and then `/debug->On` the debug message is overlapped with location so I can see the location plain text

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/30117806-f9a7d614-9329-11e7-9b9a-dab253cca3cd.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Send `/location` to Console
- Send `/debug-On` to Console

### Additional Information
* Status version: 0.9.10-73-g3095b32f+
* Operating System: Android

**Comment by annadanchenko** [comment]
ok on PR build for `feature/chat-module-refactoring-#1709` 0.9.10-96-gef6a9ac2+  (Android and iOS)
