### ISSUE TITLE
Wallet - Create Account Page - Add edit derivation path screen UI

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17712]
Taking the designs for:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2228-489317&mode=design&t=r8vdi1g192OGyaxx-4

implement the UI for the edit derivation path screens.

Acceptance criteria:
no backend hookup needed.
use mock data where required
use quo2 components
- a component spec test to cover the page

**Comment by Rende11** [comment]
I would like to implement it
