### ISSUE TITLE
Add support for the new profile link format and remove the old one for the "Add a new contact" field

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#17725]
# Bug Report

## Problem 

Follow-up of https://github.com/status-im/status-mobile/pull/17480 @yqrashawn 

We should not support the old user profile format like `https://status.app/u/zQ3shrgSaffLisbiqj2brkDK8Le7wpbpbpzriWd8kPUmdYhs1` when adding a contact using a deep link

#### Expected behavior

Formats that should be supported:

`https://status.app/u/G10A4B0JdgwyRww90WXtnP1oNH1ZLQNM0yX0Ja9YyAMjrqSZIYINOHCbFhrnKRAcPGStPxCMJDSZlGCKzmZrJcimHY8BbcXlORrElv_BbQEegnMDPx1g9C5VVNl0fE4y#zQ3shwQPhRuDJSjVGVBnTjCdgXy5i9WQaeVPdGJD6yTarJQSj`

`https://status.app/u/Ow==#zQ3shwQPhRuDJSjVGVBnTjCdgXy5i9WQaeVPdGJD6yTarJQSj`

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/174fc8d0-7046-4f1f-b043-29981549ca19

### Reproduction

1. Create a profile
2. Open the chat home screen
3. Press the `+` button > `Add a contact`
4. Paste the link

### Additional Information

- Status version: nightly 23/10
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
could possibly be combined with an invalid link validation issue https://github.com/status-im/status-mobile/issues/17723

**Comment by cammellos** [comment]
@qoqobolo this issue is only to disable the old format? if so I don't think it needs to go in release 1.26, as that's not something that negatively impact the user, what do you think?

**Comment by qoqobolo** [comment]
> this issue is only to disable the old format?

@cammellos to disable the old format and add support for the new one for this particular field.

But this would mean that we'd have to develop the ability to generate the new format in the mobile app as well, which is not actually currently in the scope iirc.
But I checked with Rashawn just in case if this part was in the scope, and he said yes, so I added it to 1.26. 
However, I agree that it’s better to implement the whole feature of generating a new link format in the mobile app later. 
So no objections from my side on postponing this.
cc @yqrashawn

**Comment by yqrashawn** [comment]
Yes, I already changed the shared profile URL to status.app in the merged PR

although there's no encoded data in it so it's broken

now that I found out we also generate community chat deep link in status-go
I'll just update all places that generate universal/deeplink URL to new format
