### ISSUE TITLE
Wallet - Create initial send screen

### ISSUE THREAD

**Issue by x-goose-x** [status-im/status-react#1773]
### User Story

As a user, I want to be able to navigate to the send screen from the wallet
to begin a send transaction.

### Description

*Type*: Feature

*Summary*: 

This task involves creating and styling the initial send screen that takes
contact information for the desired recipient.

Style should be consistent with [Zeplin](zpl://screen?pid=5863cdcee68455850f1929f2&sid=5991fb3a0f0692af9117d1ee)

Currently first screen is covered, the following things need to be fleshed out:
- QR scanning/QR permissions
- Browse photos
- Select contact.

Paste from clipboard does currently work.

Relevant story: #1525

**Comment by andmironov** [comment]
Hey guys, heres the actual mockup, here are the things that i would like to mention:

**Comment by asemiankevich** [comment]
This is tested with reference to list of open wallet issues to be resolved https://github.com/status-im/status-react/issues/584#issuecomment-329427213. Design review showed several remarkes that should be fixed

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
