### ISSUE TITLE
Add “resource-ids” to elements for e2e tests

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#1776]
### User Story

As automation engineer I need resource-ids to be added for specific elements.

### Description

Such elements could be found by class and position of the class, however structure of the app is changing and each time position and class should be updated in automation framework. Such approach leads to unstable e2e tests.
The issue can be resolved by adding unique indicators as "resource-id"

Please add resources-ids for elements on screens below:

<img width="404" alt="screen shot 2017-09-07 at 12 24 11 pm" src="https://user-images.githubusercontent.com/12611990/30156562-ada8c38c-93c8-11e7-9c01-38ed0dc49850.png">
toolbar-hamburger-menu
<img width="403" alt="screen shot 2017-09-07 at 12 14 09 pm" src="https://user-images.githubusercontent.com/12611990/30156571-aff3d92e-93c8-11e7-94e7-a4695428072a.png">
drawer-profile-icon
<img width="401" alt="screen shot 2017-09-07 at 12 14 20 pm" src="https://user-images.githubusercontent.com/12611990/30156574-b1b8b2b6-93c8-11e7-9c57-698cf158938d.png">
profile-address
profile-public-key
profile-phone-number
<img width="400" alt="screen shot 2017-09-07 at 12 16 17 pm" src="https://user-images.githubusercontent.com/12611990/30156578-b284d0d0-93c8-11e7-8232-e05481a49c3e.png">
<img width="400" alt="screen shot 2017-09-07 at 12 35 45 pm" src="https://user-images.githubusercontent.com/12611990/30156821-60f5a504-93c9-11e7-9b8d-345fd259baaa.png">

**Comment by jeluard** [comment]
We used to rely on [accessibility labels](https://facebook.github.io/react-native/docs/accessibility.html) for this.
Please comment if this is acceptable.
