### ISSUE TITLE
Share QR Code designs updated

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17769]
# Feature Issue

### Description

The designs of the Share QR Code component have been modified, we must implement the new designs:

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1338-34510&mode=design&t=CYN46DVqhc97AZzZ-4

![image](https://github.com/status-im/status-mobile/assets/90291778/a1d56125-f770-4a25-af77-147b9c8743fa)

### Acceptance Criteria

- Component Test updated
- The implementation matches the designs
- Fix screens/components where the previous one is used and make sure to update them properly

**Comment by Pau1fitz** [comment]
PR here - https://github.com/status-im/status-mobile/pull/18503

**Comment by J-Son89** [comment]
I think this is a duplicate/done so will close for now 👍
