### ISSUE TITLE
Community invites for token gated communities are not shown in 1-1 chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17777]
# Bug Report

## Problem 
There is no way to see an invite to community, as it is not shown in 1-1 chat

## Steps to reproduce
**Prerequisites:** User A on desktop, User B is on mobile
- User A: create a token-gated community (in a particular case with these permissions):

![Status Desktop 2023-10-31 13-02-37](https://github.com/status-im/status-desktop/assets/4557972/e5125ba3-0edc-41e7-a91a-2038c5bd45e3)

- User A: add User B to contacts
- User A: add User B to the token-gated community

#### Expected behavior
User B: Can see the community info from the invite, can see the requiremtns

#### Actual behavior
User B: no invite (however I can see a red border for invite)
<img width="227" alt="Monosnap 2023-10-31 13-35-40" src="https://github.com/status-im/status-mobile/assets/4557972/562330ce-1205-4568-82b3-d69b25dd3e9a">

### IMPORTANT NOTES
Current behaviour on desktop: https://github.com/status-im/status-desktop/issues/12593
Likely related to https://github.com/status-im/status-desktop/issues/12481 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Logs:  [logs (63).zip](https://github.com/status-im/status-mobile/files/13216367/logs.63.zip)

**Comment by igor-sirotin** [comment]
Just to note, we discussed with @John-44  that "community invitations" should not be used anymore.
Instead we should send a shared URL with a link preview.

Here's the desktop issue with more details: https://github.com/status-im/status-desktop/issues/12570

**Comment by ilmotta** [comment]
@churik, I tried to reproduce the issue's bug, but the invited user does see the message correctly. I re-invited the user a few times, but the message always arrives.

Could you double-check again with latest mobile build? Maybe something was fixed recently in status-go.

[Screencast from 2023-11-06 20-01-38.webm](https://github.com/status-im/status-mobile/assets/46027/679e0ccb-e637-460d-b1f7-8132e7a0a84c)

**Comment by ajayesivan** [comment]
I saw this bug sometime back, but as @ilmotta said above, I'm getting invites properly now.

**Comment by pavloburykh** [comment]
@churik closing this issue as it is not reproducible any more. Feel free to reopen in case you face it again.
