### ISSUE TITLE
Error Data Loading error is shown in new wallet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1777]
### Description

*Type*: Bug

*Summary*: Error message is shown in new wallet and the asset is not updated . I can see recent values for %, asset and USD only when I re-launch the app however the error message is still in place

#### Actual behavior
Error Data loading message is shown,

![image](https://user-images.githubusercontent.com/28752642/30156991-c86e5bfe-93c9-11e7-8fa2-b0025b04cda5.png)

### Solution (maybe)

- [ ] separate the different errors in the wallet
- [ ] clear the error in case of success
- [ ] show better error message ?

### Reproduction

- Open Status
- Create account
- /faucet some ETG
- go to new wallet tab

### Additional Information
* Status version: 0.9.10-63-g03a9a844+
* Operating System: Android, iOS

#### Logs
[logcat 0709.txt](https://github.com/status-im/status-react/files/1284187/logcat.0709.txt)

**Comment by yenda** [comment]
This is a UX bug because there is a real error behind it (phone fails to fetch prices from API) but the problem is that the error is not clear when a successful refresh is done.

I edited the issue with a task list
