### ISSUE TITLE
Wrong opacity is applied during QR scanner use on light mode

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17787]
### Steps:
1. Activate the light mode within app
2. Go to new wallet 
3. Tap on account
4. Tap 'send'
5. Tap 'Scan' icon
![image](https://github.com/status-im/status-mobile/assets/52490791/3f25e82c-55ff-4543-865b-193f9d4f4943)

### Actual result:
The opacity is applied differently for the upper and lower sections of the screen. (For Android only for lower section)

- IOS
![image](https://github.com/status-im/status-mobile/assets/52490791/a6a897f2-63ad-464c-9a51-341cae9b3d51)

- Android
![image](https://github.com/status-im/status-mobile/assets/52490791/1b45d4f6-dd16-4bd9-a7ac-8fb346c16bd8)

### Expected result:
The same opacity should be applied for the entire screen during the scanning process

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-193099&mode=design&t=u7A2TPQkGQ0sNkIQ-0

### Additional info:
This current issue occurs randomly on Android devices.

### Device:
- Real device: Pixel 7a, Android 13
- Real device: iPhone 11 Pro max, IOS 16

**Comment by churik** [comment]
not an issue anymore on nightly 21/06/24 (IPhone 14, Google Pixel7)

 Reopen if still relevant.
