### ISSUE TITLE
Username of the first account is changed to the username of second account on same device [bug/username-changed-to-default]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1778]
### Description

*Type*: Bug

*Summary*: Account with username "one" is created. Than user creates account "two" on the same device. After signing in to the account "one" and opening a drawer there is username "two" instead of "one". After switching users there are 2 accounts with same username "two" on Sign in screen

#### Expected behavior
Each account contains only its own info and does not share usernames, statuses etc
#### Actual behavior
Account "one" gets username from account "two"

### Reproduction
from 01:19 to 01:44
https://app.testfairy.com/projects/4803622-status/builds/6511348/sessions/7/?accessToken=6ffm6NazEJOne42MIo29wV/uqUc
- Open Status first time and create new account
- Open drawer, tap on username, delete default one and type "one"
- Tap on empty place in the drawer
- Tap on switch users
- On Sign in screen tap on Create new account
- In Console provide a password for new account
-  Open drawer, tap on username, delete default one and type "two"
- Tap on empty place in the drawer
- Tap on switch users. Now on Sign in screen there are 2 accounts: "one" and "two"
- Sign in to account "one"
- Open drawer and check username shown
- Tap on Switch users
- Check usernames shown on sign in screen

### Additional Information
* Status version: PR `bug/username-changed-to-default`   0.9.10-70-g9044db9e+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by oskarth** [comment]
> After a quick glance at the code it appears to me that the app-db is not cleared when switching account, only some fields are overwritten when the accounts is initialized. Do you have any suggestions as of how this could be improved to avoid bugs such as https://github.com/status-im/status-react/issues/1778 (I was storing :profile/default-username and it was surviving the switch, maybe this one was useless the idea was just not to recompute it everytime it is needed) ? -- yenda

Discussion / confusion in Slack about whether app-db is cleared or not. See https://github.com/status-im/status-react/blob/e169949e0a4d77a011793fdd7dfa70f2abe1de42/src/status_im/ui/screens/events.cljs#L134

Look at this more closely during code review of PR that fices this.

**Comment by annadanchenko** [comment]
works ok on develop build 0.9.10-84-g3e1d7311+
