### ISSUE TITLE
[IOS]  Avatars and generated QR code show [x] after changing device date into the past

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17789]
### Steps to Reproduce:
1. Go to device settings.
2. Set the time into the past.
3. Check avatars within the app and generated QR codes.

### Actual Result:
The [x] icon is displayed for avatars and generated QR codes.

https://github.com/status-im/status-mobile/assets/52490791/f4d9e47e-24ae-410e-ba85-dacc9f615962

### Expected Result:
Avatars and QR codes should be generated without displaying the [x] icon.

### Logs:
[logs (2) 2.zip](https://github.com/status-im/status-mobile/files/13228498/logs.2.2.zip)

### ENV:
- Real device: iPhone 11 Pro Max, IOS 16,6

**Comment by yqrashawn** [comment]
it's TLS cert issue.
A TLS cert is generated every time app in on or user login
the cert's validity is now till now+1 year
now is from [online resource,](https://github.com/status-im/status-go/blob/d198ac63fc6b88c9ee8a109b15547e13238d0ad1/timesource/timesource.go#L33) not from operating system
https://github.com/status-im/status-go/blob/d198ac63fc6b88c9ee8a109b15547e13238d0ad1/server/certs.go#L85

**Comment by churik** [comment]
hepofully the fix will also fix the issue with random [x] avatars after background
