### ISSUE TITLE
custom linter for i18n/label translation keywords does not currently lint a lot of usages of utils.i18n/label

### ISSUE THREAD

**Issue by akatov** [status-im/status-react#17782]
#17610 provided custom linting of the keywords passed to `utils.i18n/label` (to enforce namespacing them with `:t/`).

There are still instances where these keywords aren't linted:
- within forms that are marked to be linted as `clj-kondo.lint-as/def-catch-all`, in particular, within `utils.re-frame/defn` macros.
- when the keyword isn't passed to the `utils.i18n/label` directly, but is e.g. inside an `if` form.

The 2nd case is harder and probably impossible to solve in general during linting and would require run-time checks instead.

**Comment by ilmotta** [comment]
> within forms that are marked to be linted as clj-kondo.lint-as/def-catch-all, in particular, within utils.re-frame/defn **macros.**

FYI @akatov, recently we officially deprecated the usage of `utils.re-frame/defn`. For many reasons, one being that code inside it is not linted by clj-kondo. So it's better if we don't invest time on that macro.
