### ISSUE TITLE
Second send transaction can't be sent as send button does nothing and fee value is not shown [feature/upgrade-status-go-g0270590]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1779]
### Description

*Type*: Bug

*Summary*: User can create 1 send transaction in 1-1 chat. If user does not confirm this transaction and returns to 1-1 chat in order to make 2nd send transaction then it's stuck on Fee step: 
1. There is no fee value shown
2. If tap on send button wile input filed contains `/send username 0.2` then nothing happens. Expected: Unsigned screen is shown with 2 transactions.

![img_0579](https://user-images.githubusercontent.com/6584810/30162725-9eded380-93de-11e7-856a-a29b99efa254.jpg)

#### Expected behavior
can send second time send transaction
#### Actual behavior
can't send 2nd transaction as tap on send does nothing

### Reproduction
from 00:12 https://app.testfairy.com/projects/4803590-status/builds/6511547/sessions/5/?accessToken=1xw9BL-p5dEIONbItbxAqqE99xg
- Open Status
- Open 1-1 chat
- tap on /send, select username and type some sum that can be send from your wallet (enough balance), e.g `/send username 0.1`
- on unsigned `transaction screen tap on x in top left corner to close the screen
- in 1-1 chat tap on /send, select username and type some other sum to send. As a result Fee will be shown. Tap on send button

### Additional Information
* Status version: PR `feature/upgrade-status-go-g0270590`  0.9.11d60 (1429.188)
* Operating System: 
Real device iPhone 6s, iOS 10.3.3

**Comment by rasom** [comment]
should be resolved with https://github.com/status-im/status-go/pull/293

**Comment by annadanchenko** [comment]
verified ok on release 0.9.11 build 0.9.10-120-g971d1104
