### ISSUE TITLE
Replace `RequestCommunityInfoFromMailserver` with new `FetchCommunity` status-go endpoint

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-react#17796]
# Problem

`RequestCommunityInfoFromMailserver` is deperecated now, use `FetchCommunity` instead.,
more details here: https://github.com/status-im/status-go/pull/4238

**Comment by igor-sirotin** [comment]
@churik was this implemented indeed?

**Comment by churik** [comment]
I believe @ilmotta checked it in the codebase, that's why we closed it
