### ISSUE TITLE
Emoji Picker should be able to take customization-color to have a correct background color

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17807]
In the designs the emoji picker has a solid background color. Update the emoji picker to match these designs

<img src="https://github.com/status-im/status-mobile/assets/22799766/f09e2eb5-0926-415f-a3e0-91aae4eac6b0" width="300px" />
Align with the design team on the expected behaviour.

Ensure this is not breaking the emoji picker for it's other uses on different pages

**Comment by OmarBasem** [comment]
@J-Son89 can you please clarify more what needs to be done in this issue? Any link to designs?

**Comment by J-Son89** [comment]
Actually I think this issue has been addressed @OmarBasem. it looks right in the app on development now.

**Comment by J-Son89** [comment]
@OmarBasem it's to use the watch only variant for account avatar ->
see the designs:
 https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522184&mode=design&t=5NEcFjupudWCyMby-0
see watch-only variant
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=24107%3A223984&mode=design&t=smsWNzemzXhDY9Er-1

so this is a 2/3 liner :)
