### ISSUE TITLE
Sometimes channel is not fetched if opened after joining community (E2E blocker)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17801]
According to @Parveshdhull [comment](https://github.com/status-im/status-mobile/pull/17704#issuecomment-1778973906) this issue might require fix on status-go side.

This issues is often caught by our e2e causing the whole group of tests to fail. So it can be considered as test blocker. 

Sometimes this bug is also reproducible manually.

**Steps:** 

1. User A creates community which does not require admin manual approval. Use PR build to create community from mobile. 
2. User A sends community invite to User B
3. User B sends Request to join the community
4. Wait until community status is changed to Joined for User B
5. User B opens community channel
6. See if channel is fetched

**Actual result:** sometimes channel is not fetched

[logs (11).zip](https://github.com/status-im/status-mobile/files/13068070/logs.11.zip)

https://github.com/status-im/status-mobile/assets/97245802/162146e5-2e12-4589-ae82-7f0e1dc9a318

**Expected result:** channel is fetched

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by mohsen-ghafouri** [comment]
Hi @pavloburykh , I attempted to reproduce the issue within the `develop` branch but wasn't able to encounter it when testing on an iOS simulator. Do you have any suggestions on how I might increase the likelihood of observing this issue?

**Comment by VolodLytvynenko** [comment]
> Hi @pavloburykh , I attempted to reproduce the issue within the `develop` branch but wasn't able to encounter it when testing on an iOS simulator. Do you have any suggestions on how I might increase the likelihood of observing this issue?

@mohsen-ghafouri Unfortunately, the issue occurs infrequently. I was able to reproduce it once today, but since then, I haven't been able to replicate it.

 I've attached the logs, hopefully, they can provide some details.
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13295430/Status-debug-logs.zip)

**Comment by pavloburykh** [comment]
> Hi @pavloburykh , I attempted to reproduce the issue within the `develop` branch but wasn't able to encounter it when testing on an iOS simulator. Do you have any suggestions on how I might increase the likelihood of observing this issue?

Hey @mohsen-ghafouri! Thank you for looking at the issue. It is really hard to reproduce. 

BTW, are you creating community from mobile? As for now we have faced this issue in the flow when we are creating community from mobile PR builds (not from Desktop). Try to follow the steps below (though they do not guarantee reproduction) 

**Steps:** 

1. Create new mobile users A and B. 
2. Create 'open community' by User B
3. User B shares community to User A 
4. Stay online by User B admin node
5. User A opens shared community card from 1-1 chat
6. User A sends community join request
7. Wait until community status is changed to Joined for User A. 
8. User A opens community channel 
9. See if channel is fetched. 

**Actual result:** sometimes channel is not fetched after joining the community. But indeed, this issue is kind a random. It is hard to reproduce.

**Comment by mohsen-ghafouri** [comment]
Yes i did it from mobile and exactly these steps but couldn't reproduce it , will try some more and if i could reproduce it will assign the issue to my self 
@pavloburykh

**Comment by ilmotta** [comment]
@mohsen-ghafouri 

Since the community is created on the Mobile client we might be doing this incorrectly, which means the issue could be in how we create the community.

If the issue can never be reproduced when creating the community from the Desktop client, it's a strong indicator that there's no problem in status-go, and we might just need to fix our test-only code that creates communities.

**Comment by mohsen-ghafouri** [comment]
@ilmotta yes but the issue is i couldn't reproduce the issue with mobile community either. i created many communities with mobile and didn't see this kind of issue.

**Comment by pavloburykh** [comment]
@ilmotta @mohsen-ghafouri  

**UPDATE:**

I have just managed to reproduce this bug with Desktop community. So issue is not related only to test communities created on mobile. 

As you can see from video below channel is not fetched after joining the community. After re-login it works as expected. 

[logs (15).zip](https://github.com/status-im/status-mobile/files/13392072/logs.15.zip)

https://github.com/status-im/status-mobile/assets/97245802/7bdee2f8-aa4d-4bbd-bf3e-b53f93c4344c

**Comment by siddarthkay** [comment]
I'll look into this, since it blocks my PR : https://github.com/status-im/status-mobile/pull/17773

**Comment by siddarthkay** [comment]
I am able to reproduce this issue very easily on android emulator when building for x86_64 crash fix branch.
Seems like a TCP socket issue from the surface, this could be the reason why it happens less on develop and more on my branch.
The goal however is to find a fix for develop.
Debugging further, will post my investigations here.

**Comment by siddarthkay** [comment]
Another key thing I noticed is that, although on opening a the community channel we see a loading indicator.
as soon as I send a message from Device A ( creator of community ) on general channel, Device B ( where we see loading channel ) immediately loads up the channel.

<img width="345" alt="Screenshot 2023-11-25 at 10 17 52 AM" src="https://github.com/status-im/status-mobile/assets/64726664/4da33e09-033c-423f-bdc9-794beba13f66">

**Comment by siddarthkay** [comment]
Just curious about the flow, 
@pavloburykh @yevh-berdnyk @churik : does it make sense for E2E to add another step in this flow, right after step 5 of issue description : Device A sends a message on channel, then step 6 : Device B checks to see if channel is loaded?
cc @cammellos

**Comment by siddarthkay** [comment]
As mentioned by @pavloburykh  the empty channel does load up when you sign out and sign back in.

<img width="344" alt="Screenshot 2023-11-25 at 11 02 19 AM" src="https://github.com/status-im/status-mobile/assets/64726664/78c7cfb4-aea9-4543-9ba8-6f06d0ccaf0c">

So probably something happens when we logout and log back in that causes the channel to load up.
A similar thing happens when creator of open community sends a message on that channel.
The fix maybe on both status-mobile and status-go side.

**Comment by siddarthkay** [comment]
Messages are fetched by this function `messages-by-chat-id-rpc`  here : https://github.com/status-im/status-mobile/blob/develop/src/status_im/data_store/messages.cljs#L83-L93 

This code calls `wakuext_chatMessages` at status-go which returns `nil` as a call back when user navigates to general channel. Could be because there are no messages.

However from what I see when this re-frame event is dispatched `:chat.ui/load-more-messages-for-current-chat` 
The UI updates and resolves the loading screen to an empty chat view.. This is what should have happened when the user visits the channel the first time as well.

This only happens when we log out and log back in and then open the community channel.

This event is dispatched inside `list-on-end-reached` here : https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/chat/messages/list/view.cljs#L71-L84

Which passes a callback to update a few shared values in re-animated, I wonder if modifying this code will solve this issue.

**Comment by siddarthkay** [comment]
We see the loading skeleton view because this sub returns false/nil `(rf/sub [:chats/all-loaded? chat-id])`

**Comment by Parveshdhull** [comment]
The problem is after joining the community, app-db (`:chats/..`) don't have chat data for the general channel chat-id, and that's why UI is not shown and just a loading skeleton shown.

Not sure why this chat is never returned by status-go when joining the community in case of PR builds, but when I was debugging this issue status-go always returned the chat, but sometimes with significant delay.

**Comment by Parveshdhull** [comment]
> So probably something happens when we logout and log back in that causes the channel to load up.
> A similar thing happens when creator of open community sends a message on that channel.

So, somehow community joining process is failing or delaying sending signal related to chat data, but we still are able to get that chat in other ways.

**Comment by siddarthkay** [comment]
I added some extensive logging here : https://github.com/status-im/status-mobile/pull/17773/commits/d25a5a92e2063b68e05437195db49278bf84a324

These are the relevant logs
```
INFO  2023-12-01T06:06:23.048Z INFO [status-im2.contexts.chat.events:218] - chat-id inside 
navigate-to-chat is ->  
0x0358e69a8dd380c2fe2a1b0783e87bed7446c282313dc572896b003e84e5691a2355ac7ba5-dd0b-4860-9eb3-7ef99c9d88a7
 INFO  2023-12-01T06:06:23.051Z INFO [status-im.data-store.messages:89] - messages-by-chat-id-rpc called 
with following params  {:chat-id
 "0x0358e69a8dd380c2fe2a1b0783e87bed7446c282313dc572896b003e84e5691a2355ac7ba5-dd0b-4860-9eb3-7ef99c9d88a7"
, :cursor nil, 
 :limit 20}
 INFO  2023-12-01T06:06:23.063Z INFO [status-im.data-store.messages:94] - on-success ->  nil
 INFO  2023-12-01T06:06:23.108Z INFO [status-im2.subs.chats:152] - inside :chats/current-raw-chat for 
current-chat-id ->  
0x0358e69a8dd380c2fe2a1b0783e87bed7446c282313dc572896b003e84e5691a2355ac7ba5-dd0b-4860-9eb3-7ef99c9d88a7  
and for chats -> 
{"0x0489644501d19339e8af11456964c6a09357eeedf93f297849e274a87e152c85f020425363c0f629432afcf3bab50834cc3c3861f
4e2eeef1d0b1d3f82f2cbdfc1"
 {:description "",
  :emoji "",
  :muted-till "0001-01-01T00:00:00Z",
  :joined 1701410609368,
  :identicon "",
  :color "",
  :muted false,
  :contacts #{nil},
  :last-clock-value 1701410689032,
  :highlight false,
  :admins #{},
  :members-joined #{},
  :name "0x048964",
  :last-message
  {:command-parameters nil,
   :quoted-message nil,
   :identicon "",
   :message-id
   "0x120c249c761dbae0963e3e3ba59cca6bb59d22fb7ea237261702d96a2fae11a1",
   :replace "",
   :community-id
   "0x0358e69a8dd380c2fe2a1b0783e87bed7446c282313dc572896b003e84e5691a23",
   :content
   {:sticker nil,
    :rtl? false,
    :ens-name "",
    :parsed-text
    [{:type "paragraph",
      :children
      [{:literal
        "Community open community has been shared with you"}]}],
    :response-to "",
    :chat-id
    "0x04f839b13aa3cda9eb9a073a4667cbbdff5c127255fe2bc9e79e02312071bf4b4990b0c614ebf70332eedf55ac44e7d6b5064f
18489b8caa6adbe9a964af4326db",
    :image nil,
    :line-count 0,
    :links nil,
    :text "Community open community has been shared with you"},
   :outgoing-status nil,
   :compressed-key "zQ3shotRfHCu5o6zdpQ35MmeDFgMRcWQShy5xCpzqDW9nLp6j",
   :whisper-timestamp 1701410689000,
   :link-previews (),
   :message-type 1,
   :clock-value 1701410689032,
   :alias "zQ3...9nLp6j",
   :seen false,
   :from
   "0x0489644501d19339e8af11456964c6a09357eeedf93f297849e274a87e152c85f020425363c0f629432afcf3bab50834cc3
c3861f4e2eeef1d0b1d3f82f2cbdfc1",
   :chat-id
   "0x0489644501d19339e8af11456964c6a09357eeedf93f297849e274a87e152c85f020425363c0f629432afcf3bab50834cc3c
3861f4e2eeef1d0b1d3f82f2cbdfc1",
   :content-type 9,
   :display-name "Device A",
   :emojiHash
   ["🤾🏻‍♀️"
    "🤱🏿"
    "🧜"
    "♣️"
    "🦺"
    "🆎"
    "🪓"
    "👨🏼‍🍼"
    "🪡"
    "🏊🏻‍♀️"
    "👳🏿"
    "🧑‍💻"
    "🔣"
    "✌🏻"],
   :timestamp 1701410689032,
   :new? true,
   :outgoing false},
  :unviewed-messages-count 0,
  :alias "zQ3...9nLp6j",
  :active true,
  :chat-type 1,
  :group-chat false,
  :public? false,
  :chat-id
  "0x0489644501d19339e8af11456964c6a09357eeedf93f297849e274a87e152c85f020425363c0f629432afcf3bab50834cc3c3861f
4e2eeef1d0b1d3f82f2cbdfc1",
  :unviewed-mentions-count 0,
  :ReadMessagesAtClockValue 1701410632401,
  :timestamp 1701410691369,
  :deleted-at-clock-value 0,
  :membership-update-events nil, 
  :invitation-admin nil}}
 INFO  2023-12-01T06:06:23.280Z INFO [status-im2.subs.chats:210] - inside re-frame/reg-sub 
:chats/current-chat current-chat is -> nil
 INFO  2023-12-01T06:06:23.281Z INFO [status-im2.subs.chats:211] - inside re-frame/reg-sub 
:chats/current-chat community is -> nil
 INFO  2023-12-01T06:06:23.287Z INFO [status-im2.contexts.chat.messages.view:50] - chat object inside 
f-chat is ->  {}
 INFO  2023-12-01T06:06:23.736Z INFO [status-im2.contexts.chat.messages.view:50] - chat object inside 
f-chat is ->  {}
 INFO  2023-12-01T06:06:23.794Z INFO [status-im2.contexts.chat.messages.list.view:131] - not all-loaded? 
-> true for chat-id -> nil
 INFO  2023-12-01T06:06:23.864Z INFO [status-im2.contexts.chat.messages.list.view:131] - not all-loaded? 
-> true for chat-id -> nil
```

**Comment by siddarthkay** [comment]
> or delaying sending signal related to chat data

<img width="1274" alt="Screenshot 2023-12-01 at 11 57 52 AM" src="https://github.com/status-im/status-mobile/assets/64726664/294aa863-1310-407d-b4b7-57ad4be77126">


So something happens when admin sends a message on general channel that causes this device to get the signal.
A similar thing also happens when Device B logs out and logs back in.
They mean that the bug is indeed in status-go implementation of when an open community was joined and further investigation must go in that direction.

**Comment by siddarthkay** [comment]
The entry point in status-go which gets invoked by status-mobile for creating "Open community" is here : 
https://github.com/status-im/status-go/blob/develop/protocol/messenger_community_for_mobile_testing.go#L93-L103

I hope to write a failing test in status-go to try and replicate this behaviour.

**Comment by siddarthkay** [comment]
Special Thanks to @cammellos for helping me identify that in the log message below `chatID` key should not have been empty, this helped me solve this issue.
 
```
 INFO  2023-12-02T04:25:45.313Z INFO [status-im.signals.core:99] - signal with type  messages.new was received with
  data  #js {:type "messages.new", :event #js {:requestsToJoinCommunity #js [#js {:id 
  "0x9984a48830cbf4f776f6142776a43c430912b28e823e4245cacf34420b26e354", :publicKey
"0x0444b43634a04ccb5edf9e5b69f5322a4c7a7f7d77dc688c99e3e08b985ba081c20b454ea63b9ca94f14aa2d4fbf66
  c6f53a4aeb4c902bc7d5d7365e3a95bef508", :clock 1701491142, :chatId "", :communityId 
  "0x02a30b66916aa242e4883cad9acf13a8393a480f0deba795db94d4cca1623ad606", :state 3, :our false, :deleted 
  false}], :notifications nil, :communities #js [#js {:id 
  "0x02a30b66916aa242e4883cad9acf13a8393a480f0deba795db94d4cca1623ad606", :memberRole 0, :isControlNode 
  false, :verified false, :joined true, :spectated false, :requestedAccessAt 0, :name "open community",
   :description "open community to join with no requests", :introMessage "", :outroMessage "", 
   :tags nil, :chats #js {"23e49edb-9190-4584- 9522-07771975e49e" 
   #js {:id "23e49edb-9190-4584-9522-07771975e49e", :name "general", :color "#26a69a", :emoji "", 
   :description "General channel for the community", :members
#js{"0x0444b43634a04ccb5edf9e5b69f5322a4c7a7f7d77dc688c99e3e08b985ba081c20b454ea63b9ca94f14aa2d4fbf6
  6c6f53a4aeb4c902bc7d5d7365e3a95bef508" #js {},
"0x0489644501d19339e8af11456964c6a09357eeedf93f297849e274a87e152c85f020425363c0f629432afcf3bab5083
  4cc3c3861f4e2eeef1d0b1d3f82f2cbdfc1" #js {:roles #js [1]}}, :permissions #js {:access 1}, :canPost true, :position 0, 
  :categoryID ""}}, :categories #js {}, :images nil, :permissions #js {:access 1}, :members #js 
{"0x0444b43634a04ccb5edf9e5b69f5322a4c7a7f7d77dc688c99e3e08b985ba081c20b454ea63b9ca94f14aa2d4fbf6
6c6f53a4aeb4c902bc7d5d7365e3a95bef508" #js {}, 
"0x0489644501d19339e8af11456964c6a09357eeedf93f297849e274a87e152c85f020425363c0f629432afcf3bab5083
4cc3c3861f4e2eeef1d0b1d3f82f2cbdfc1" #js {:roles #js [1]}}, :canRequestAccess false, :canManageUsers false, 
:canDeleteMessageForEveryone false, :canJoin false, :color "#26a69a", :requestedToJoinAt 1701491142, :isMember true, 
:muted false, :muteTill "0001-01-01T00:00:00Z", :adminSettings #js {:pinMessageAllMembersEnabled false}, :encrypted 
false, :pendingAndBannedMembers #js {}, :tokenPermissions #js {}, :communityTokensMetadata nil, 
:activeMembersCount 0, :pubsubTopic "", :pubsubTopicKey "", :shard nil}], :communitiesSettings #js [#js {:communityId 
"0x02a30b66916aa242e4883cad9acf13a8393a480f0deba795db94d4cca1623ad606", :historyArchiveSupportEnabled 
true, :clock 0}], :activityCenterNotifications #js [#js {:id 
"0x9984a48830cbf4f776f6142776a43c430912b28e823e4245cacf34420b26e354", :chatId "", :communityId 
"0x02a30b66916aa242e4883cad9acf13a8393a480f0deba795db94d4cca1623ad606", :membershipStatus 2, :name "", 
:author "", :type 7, :lastMessage nil, :message nil, :replyMessage nil, :timestamp 1701491143484, :read false, :dismissed 
false, :deleted false, :accepted false, :contactVerificationStatus 0, :updatedAt 1701491145942, :albumMessages nil}], 
:activityCenterState #js {:hasSeen false, :updatedAt 1701491145942}, :discordOldestMessageTimestamp 0}}

 ```
