### ISSUE TITLE
Allow devs to run tests in watch mode and run only a subset

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#17805]
```
As a developer
I want to run tests in watch mode
So that I can make changes and check the tests without having to manually run them

As a developer
I want to run only a subset of tests
So that I can quickly check that the test I am working on passes
```

### Description

We want to be able to run a script, that watches the cljs tests and re run them whenever any of the`cljs` files changes. 
We would also like to be able to run a subset of tests (by regex, or by namespace for example, either is fine). 

Some documentation in`doc/` should also come with the PR, so other devs know how to run it.

These tests are currently run with `make test`

**Comment by ilmotta** [comment]
This is already possible, so we can close the issue.

The make targets `test-contract`, `test-integration`, `test-unit`, and `test` can all take a `WATCH` and/or `SHADOW_NS_REGEXP` argument.

```sh
make test-unit SHADOW_NS_REGEXP='.*-test$' WATCH=true
```

https://github.com/status-im/status-mobile/blob/00f1463e94e34c26fa5f698c04c66881f6d5139e/Makefile#L334-L335
