### ISSUE TITLE
Wallet: Add testnet setting for new wallet

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17826]
The Testnet feature needs to be added for the new wallet. 

In Testnet mode the behaviour is exactly the same, except the UI will have an orange banner at the top saying in Testnet - reach out to design for exact details.

Please discuss behaviour with design team and desktop team about how this should behave.
e.g do all assets need to be reloaded? 
should the user basically login again?

Acceptance Criteria :
- Add this toggle in the Profile Settings page, it can be done in the old UI for the moment. 
- update relevant wallet subs to pull in the correct data for chain-id's etc.

**Comment by J-Son89** [comment]
This issue might be a duplicate of the issue solved here: 
https://github.com/status-im/status-mobile/pull/17879

**Comment by ajayesivan** [comment]
We still need this issue in #17879 we are not adding the orange banner. We can consider this one as the follow-up of #17879.

**Comment by J-Son89** [comment]
Thanks @ajayesivan !
