### ISSUE TITLE
Refactor wallet tokens data in app-db

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#17823]
Depends on #17798

- The tokens data are currently stored in the (root) key `:wallet/tokens` and it needs to be moved under the `:wallet` key (along with the accounts and other data). The `:token` key (under `wallet`) will be a map which will contain the `data` and `loading?` keys.
- The keys inside the token data need to be renamed (kebab-case) and the helper methods should be placed in `status-im2.common.data-store.wallet ` ns.
- The subscriptions need to be updated to attach the token data for each account along with the account data.
- The helper methods for the calculation of balances should be moved to `status-im2.contexts.wallet.common.utils` ns.
- The usage should be updated across the wallet.

### Acceptance Criteria

The app should work as before

**Comment by ulisesmac** [comment]
@smohamedjavid 

There are more root key subs, we need to investigate what's the app-db structure being used for these keys and check if they need to be refactored.

The current subs are:
`:wallet/scanned-address`
`:wallet/create-account`
`:wallet/networks`
`:wallet/scanned-address`
`:wallet/local-suggestions`
`:wallet/valid-ens-or-address?`
`:wallet/send-address`

**Comment by smohamedjavid** [comment]
@ulisesmac - Yes, we have a bunch of `:wallet/*` keys in app-db and subs. 

The motive of this issue is to tackle one problem (tokens) at a time. Additionally, the token data is not dependent on other subs. It would be safe to refactor.

We will eventually create more issues to handle the rest of the keys as we progress.

**Comment by ulisesmac** [comment]
> @ulisesmac - Yes, we have a bunch of `:wallet/*` keys in app-db and subs.
> 
> The motive of this issue is to tackle one problem (tokens) at a time. Additionally, the token data is not dependent on other subs. It would be safe to refactor.
> 
> We will eventually create more issues to handle the rest of the keys as we progress.

Got it! Just wanted to spot them.
Also It'd be good to have an event to clearly initialize `:wallet/initialize` the new wallet :)
