### ISSUE TITLE
Permissions are still not requested during profile photo setting (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17849]
This one is related and should be fixed is scope of RN upgrade PR https://github.com/status-im/status-mobile/pull/17241

Reproducing on Android 12, Samsung Galaxy A52

**Preconditions:** media permissions are not granted

**Steps:** 

1. Proceed to "Create profile" onboarding step
2. Open gallery to set up profile photo
3. See if permission pop up appeared when opening gallery

**Actual result:** permissions are not requested. Gallery is opened all the images are available for selection. User can set up gallery image as profile photo. 

https://github.com/status-im/status-mobile/assets/97245802/70e5b501-426c-46bf-b671-99733b2c3b57

**Expected result:** permissions should be requested. User should not have access to gallery images until permissions are granted. 
### Additional Information

- Status version: RN upgrade PR build https://github.com/status-im/status-mobile/pull/17241
- Operating System: Android

**Comment by siddarthkay** [comment]
Logging my findings below,

In case of profile picture we rely on `react-native-image-crop-picker` library to show us a native image picker with cropping capabilities ref : https://github.com/ivpusic/react-native-image-crop-picker
In case of showing image picker from chat screen we rely on `react-native-cameraroll` library ref : https://github.com/react-native-cameraroll/react-native-cameraroll

In case of `react-native-cameraroll` (used in chatview) we explicitly ask for user permissions before invoking any of the camera/gallery related functions, however in case of `react-native-image-crop-picker` we don't.

There would be good reasons for having 2 separate libraries for this purpose in the past I assume.

**Comment by siddarthkay** [comment]
Explicitly asking for media permissions for consistent behaviour here : https://github.com/status-im/status-mobile/pull/17241/commits/fe7d02148a9e31173a70671f9bb7aa3913cadd0c 

@pavloburykh I verified this on 2 android emulators, API 29 and 33.

Could you pls verify?
Thank you.

**Comment by pavloburykh** [comment]
> Could you pls verify?

Hi @siddarthkay! Quickly checked, the issue is gone for me. Thank you! 
Currently we are busy with release testing, will be able to continue more deeply testing after we finish with the release.

**Comment by siddarthkay** [comment]
Thanks for checking @pavloburykh !

> we are busy with release testing, will be able to continue more deeply testing after we finish with the release.

Awesome! Sure, take your time :)

**Comment by siddarthkay** [comment]
fixed here : https://github.com/status-im/status-mobile/pull/17241
