### ISSUE TITLE
[Android] Endless logout spinner is displayed randomly

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17845]
There are no specific steps to reproduce this issue. It appears to occur rarely and without clear steps. I hope the logs can provide more  info what might be happening

### Steps:
1. Log out

### Actual result:
Randomly, an endless spinner is displayed when trying to log out.
![image](https://github.com/status-im/status-mobile/assets/52490791/ed4be246-a17b-4b88-9763-cc7610b2c371)

### Expected result:
The user is navigated to the login page

### ENV:
- Android 
- Nightly [7 Nov 2023]

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13285273/Status-debug-logs.zip)

**Comment by ibrkhalil** [comment]
I am trying to reproduce locally but I can't since it's not consistent.
Reproduction locally will help me identify the cause of the issue.
Do you think you can get Logcat's logs?

**Comment by VolodLytvynenko** [comment]
> I am trying to reproduce locally but I can't since it's not consistent. Reproduction locally will help me identify the cause of the issue. Do you think you can get Logcat's logs?

Hey @ibrkhalil it seems the issue is gone. Can't reproduce it anymore
