### ISSUE TITLE
Wallet - Implement Network Configuration 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17840]
The Network Configuration page on the wallet designs has the UI implemented, 
see: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=900-230906&mode=design&t=vpLa1xN6Dn8Cb6nJ-4

now we need to hook this up to the db etc.

Each account will have it's own network configuration - 

The approach decided on by the team for handling this data is to have a list of networks set by each wallet account

e.g
```
:wallet {
 :network-details ( collection of map of extensive network details)
 :accounts {
  "0x1..." {
    :network-preferences #(:ethereum :arbitrum)
    ...
    }
    "0x2..." {
    :network-preferences #(:ethereum)
    ...
    }
 }
}
```

so the sub for each account's network details will be something dependent on 
`:wallet/network-details` and `:wallet/account` (or whatever its name is) 

acceptance criteria:
- create the required subs
- create the required events 
- tests for the subs and events (make test)
- this feature should work and the corresponding UI details should be relevant for this, i.e update uses of network-details sub where correct to do so

**Comment by Rende11** [comment]
I would like to implement it!
