### ISSUE TITLE
Scrolling chat history is broken (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17850]
This one is related and should be fixed is scope of RN upgrade PR https://github.com/status-im/status-mobile/pull/17241
¸
**Steps:** 

1. Open any chat
2. Generate some chat history (send multiple messages)
3. Scroll the chat and see if messages are visible

**Actual result:** chat history is not visible when user scrolls to the bottom. History becomes visible when scrolling up. 

https://github.com/status-im/status-mobile/assets/97245802/76257ca3-ee36-425b-ba19-1c7a0c0955a4

### Additional Information

- Status version: RN upgrade PR build https://github.com/status-im/status-mobile/pull/17241 
- Operating System: Android

**Comment by flexsurfer** [comment]
fixed in the RN upgrade PR

**Comment by siddarthkay** [comment]
fixed here : https://github.com/status-im/status-mobile/pull/17241
