### ISSUE TITLE
Handle timeout for network failure in utils.utils/http-get and http-post

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1785]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want http calls to have timeout in order to handle network failures gracefully.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:

#### Expected behavior
An http call such as the one that occurs when fetching prices in the new wallet should not hang forever in case of network failure

#### Actual behavior
The call hangs indefinitely

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to wallet
- Put phone in airplane mode
- Update wallet
- Error should be shown after timeout of x seconds (3 should be enough)

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

I don't have a solution yet. The http-get and post functions are using fetch which doesn't seem to support timeouts without tweaking https://github.com/facebook/react-native/issues/2556

There is https://github.com/JulianBirch/cljs-ajax that uses Xhrio and allows timeout, implemented as an effect for re-frame in https://github.com/Day8/re-frame-http-fx but I wasn't able to find out without experimentation if it works or not with react-native

First step would be to have some more input on whether or not we have to use fetch / can use xhrio, if there is a way to set timeout in fetch that I missed, or any other solution for this problem.

**Comment by rasom** [comment]
We can write our own `fetch` with timeout in Java/Obj-c

**Comment by yenda** [comment]
@rasom there is https://github.com/robinpowered/react-native-fetch-polyfill

**Comment by yenda** [comment]
@rasom Maybe you were right and we should write our own because the problem with these libraries (that try to add timeout to fetch) is that it is a response timeout and not a connection timeout. So the request keeps going even after the timeout is reached.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0xff96d75896f629d4f539ad3cd091fba76eaf0b8d](https://etherscan.io/address/0xff96d75896f629d4f539ad3cd091fba76eaf0b8d)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
