### ISSUE TITLE
 Curated communities are not fetched

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17852]
**Steps:** 

1. Create/restore an account
2. Open Discover communities screen
3. See if Curated communities are fetched

**Actual result:** Curated communities are not fetched

[Status-debug-logs (79).zip](https://github.com/status-im/status-mobile/files/13294348/Status-debug-logs.79.zip)

https://github.com/status-im/status-mobile/assets/97245802/9359a404-3885-4db2-b0ef-fac482862d21

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
So on desktop:
- when test mode is enabled: https://community-dapp-git-review-status-im-web.vercel.app/directory
- if testnet is not enabled it should reflect: https://curate.status.app/directory

I'm not sure we're aligned on mobile

**Comment by ajayesivan** [comment]
I checked the last desktop nightly I got from here: https://ci.status.im/job/status-desktop/job/nightly/

Mainnet:
<img width="1728" alt="Screenshot 2023-11-08 at 22 29 46" src="https://github.com/status-im/status-mobile/assets/19279756/40d2c4c8-eff2-458f-b7d4-4f45cb147c69">

Testnet:
<img width="1728" alt="Screenshot 2023-11-08 at 22 28 07" src="https://github.com/status-im/status-mobile/assets/19279756/e9e930eb-a45e-439c-aa2d-1ff1d9af3b32">

**Comment by ajayesivan** [comment]
status-go api we use to fetch communities is giving nothing.
API: [CuratedCommunities](https://github.com/status-im/status-go/blob/d909faf5044be563c0c7b2637fd2afa5ffe8e6e9/services/ext/api.go#L405-L407)
Response: 
```
{:contractCommunities nil, :contractFeaturedCommunities nil, :communities {}, :unknownCommunities nil}
```

**Comment by ajayesivan** [comment]
We are showing the loading screen when the curated communities list is empty: https://github.com/status-im/status-mobile/blob/abbf29d4cad563613d9602b2dfca306710b92e5d/src/status_im2/contexts/communities/discover/view.cljs#L154-L157

**Comment by ajayesivan** [comment]
In mobile there is no design for empty discover screen: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7202%3A475069&mode=design&t=7DEoalWujv2AG993-1

**Comment by ajayesivan** [comment]
> So on desktop:
> 
> * when test mode is enabled: https://community-dapp-git-review-status-im-web.vercel.app/directory
> * if testnet is not enabled it should reflect: https://curate.status.app/directory
> 
> I'm not sure we're aligned on mobile

This is what I see in the links you shared,
https://community-dapp-git-review-status-im-web.vercel.app/directory:
<img width="977" alt="Screenshot 2023-11-08 at 23 12 57" src="https://github.com/status-im/status-mobile/assets/19279756/03be154f-943d-4835-aad7-eccb468289fc">

https://curate.status.app/directory:
<img width="983" alt="Screenshot 2023-11-08 at 23 13 03" src="https://github.com/status-im/status-mobile/assets/19279756/69357a99-da8e-4714-8365-878cca49766d">

@churik Is it expected to load the lists displayed in these links onto the discover screens?

**Comment by ajayesivan** [comment]
The Mainnet [Community Directory Curation](https://curate.status.app/directory) is currently empty and we don't have an empty variant for the discover screen, which is why the loading screen is displayed in this scenario.

**Comment by ajayesivan** [comment]
- Even in testnet `status-go` thinks the app is running in mainnet, `m.settings.GetTestNetworksEnabled()` - returns `false` - when running with mobile.
- When I forced the code to fetch testnet communities it return one community public key but status-go fails to fetch the corresponding community data.

I tried importing the community with the public key on desktop and it returning nothing, see the screenshot below
<img width="663" alt="Screenshot 2023-11-10 at 16 01 38" src="https://github.com/status-im/status-mobile/assets/19279756/5c018408-5c25-4092-879a-d21ad9cc8a5f">

**Comment by ajayesivan** [comment]
I was looking at the wrong place 🥲. In order to get communities on the test network we need to switch to **status.test** fleet.

**Status App -> Settings -> Advanced -> Fleet -> status.test**

**Comment by ajayesivan** [comment]
When we are on testnet & status.test fleet atm there is only one community in the curated communities list:

<img width="1728" alt="Screenshot 2023-11-10 at 16 35 32" src="https://github.com/status-im/status-mobile/assets/19279756/1b00b94a-fa0b-49f1-8204-bcd375b25eec">

**Comment by pavloburykh** [comment]
Hey @ajayesivan 

I have checked status.test on mobile and curated community still not fetched for me

![photo_2023-11-10 13 27 28](https://github.com/status-im/status-mobile/assets/97245802/efa5879d-20de-4c90-a081-bf247df993c3)
![photo_2023-11-10 13 27 31](https://github.com/status-im/status-mobile/assets/97245802/701f2c34-49da-4443-b776-2ce0c7649a56)

**Comment by pavloburykh** [comment]
So, as far as I understand, we are not able to fetch community on Mainnet as the The Mainnet [Community Directory Curation](https://curate.status.app/directory) is currently empty as you mentioned above. 

At the same community is not fetched on testnet (on mobile) despite there is 1 community that should be fetched. 

Could it be the reason that mobile is looking at the wrong endpoints?

**Comment by ajayesivan** [comment]
@pavloburykh, on mobile there is some issue with testnet or test fleet. It definitely needs a fix, I will ping you once it's ready for testing.

I was adding all my findings here.

**Comment by pavloburykh** [comment]
We can ask felicio to add some community to Mainnet [Community Directory Curation](https://curate.status.app/directory) and see if it will be fetched on mobile. But I have an assumption that it will not be fetched.

**Comment by pavloburykh** [comment]
> @pavloburykh, on mobile there is some issue with testnet or test fleet. It definitely needs a fix, I will ping you once it's ready for testing.
> 
> I was adding all my findings here.

got it. Thank you for your investigation @ajayesivan

**Comment by ilmotta** [comment]
@pavloburykh, should we move this issue to release 1.27?

**Comment by pavloburykh** [comment]
> @pavloburykh, should we move this issue to release 1.27?

Yes. I have moved it to 1.27. Thanks @ilmotta

**Comment by ajayesivan** [comment]
Removing myself, not working on this currently.

**Comment by cammellos** [comment]
Not sure what's the state of curated communities as of now, will check, but I'd leave on hold for the time being

**Comment by cammellos** [comment]
This could be critical, but let's wait until the status community is added to the list, @jrainville could you let us know when is available please? thank you

**Comment by jrainville** [comment]
> This could be critical, but let's wait until the status community is added to the list, @jrainville could you let us know when is available please? thank you

It is since last Thursday :smile: 

![image](https://github.com/status-im/status-mobile/assets/11926403/334b4f9c-75d8-4d63-909b-83033b8d8cec)

**Comment by churik** [comment]
![IMAGE 2024-05-01 11:00:40](https://github.com/status-im/status-mobile/assets/4557972/ce3a6d61-50b2-469f-94a2-f385215a0a5e)
