### ISSUE TITLE
[IOS] The tutorial video animation keeps playing after opening a Status link

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17854]
### Steps:
1. Send  the link into chat "http://status.im"
2. Open current link
3. Close it
4. Navigate to any other page in the Status app.

### Actual result:
The Status tutorial continues to play and follows you around the app, regardless of where you navigate.

https://github.com/status-im/status-mobile/assets/52490791/61b9895d-6e8c-4f3b-85e9-1d333dcb389a

### Expected result:
The tutorial should play until the current video is closed.

### Logs:
[geth.log](https://github.com/status-im/status-mobile/files/13298526/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/13298527/Status.log)

### ENV:
- iPhone 11 Pro max, IOS 16
- Nightly 8 Nov 2023

**Comment by flexsurfer** [comment]
hey @Parveshdhull any thoughts? i think its related somehow how to new shell screens structure

**Comment by pavloburykh** [comment]
@flexsurfer can you please cherry pick this fix into release branch? thank you!
