### ISSUE TITLE
Unable to Accept Join Requests in Token-Gated Community

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17861]
### Summary
When attempting to accept a join request sent from a mobile device for a token-gated community, it erroneously indicates that the user doesn't have the required tokens, despite having sufficient tokens in the account wallet.

### Steps to Reproduce

1. Create a community with the 'request to join required' option enabled (desktop).
2. Add 'become a member' permission, e.g., 0.001 ETH to become a member (desktop).
3. Send an invite to a mobile user for this community (desktop).
4. The mobile user opens the invite, and the account meets the token requirements (mobile).
5. Mobile user sends a join request (mobile).
6. Admin tries to accept the invite (desktop).

### Actual Result
A pop-up message appears, stating that the mobile user doesn't hold enough tokens anymore.

<img width="1728" alt="Screenshot 2023-11-09 at 13 49 18" src="https://github.com/status-im/status-mobile/assets/19279756/9dc1f835-cb72-4b3b-a475-17184c93a92e">

### Expected Result
The admin should be able to accept the request without any issues

## Screenshots
Token requirements:
<img width="500" alt="Screenshot 2023-11-09 at 14 03 09" src="https://github.com/status-im/status-mobile/assets/19279756/060593d7-e32f-46ca-9ad6-3b414498ad36">

Community overview - mobile:
<img src="https://github.com/status-im/status-mobile/assets/19279756/3b07a39d-baba-465c-a9b0-9ce2cb3bfb9b" width=350/>

### Relevant info 
Recently the request to join flow was updated both in [status-go](https://github.com/status-im/status-go/pull/4178) & [status-mobile](https://github.com/status-im/status-mobile/pull/17800).

**Comment by ajayesivan** [comment]
https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803905065

**Comment by pavloburykh** [comment]
Also user is not able to join token gated community that does not not require admin's manual approval

**Preconditions:** community has set permission requirements for becoming community member. Mobile user meets the permission requirements

**Steps:** 

1. Desktop user shares community to mobile user
2. Stay online by Desktop admin control node
3. Mobile user sends community join request
4. See if community status has automatically changed to Joined

**Actual result:** community remains in Pending status. 


https://github.com/status-im/status-mobile/assets/97245802/ae44bb08-ef34-460a-b6c2-26a1c75c69a8


**Expected result:** community status should be automatically changed Joined for mobile user.

**Comment by pavloburykh** [comment]
Another related issue:

### ISSUE  "You are not a member of this group" is displayed in "view only"/"view and post" channels for user who meets permission requirements

**Steps:** 

1. Create token gated community: set permissions "view only" or "view and post" for one of the channel
2. Share community to mobile user. Mobile user should meet permission requirements. 
3. Join community by mobile user
4. Open channel with permissions by mobile user
5. Observe the result

**Actual result:** "You are not a member of this group" is displayed in the bottom. User is not able to view or post messages in the channel. 

[Status-debug-logs (80).zip](https://github.com/status-im/status-mobile/files/13308303/Status-debug-logs.80.zip)

<img width="1062" alt="Status Desktop 2023-11-09 14-49-09" src="https://github.com/status-im/status-mobile/assets/97245802/7551df09-9cf9-46fb-8cab-f8339428c971">


https://github.com/status-im/status-mobile/assets/97245802/44c9ba59-ab07-4e1a-a34c-0973c6d89ed9

**Comment by pavloburykh** [comment]
> Another related issue:
> 
> ### ISSUE "You are not a member of this group" is displayed in "view only"/"view and post" channels for user who meets permission requirements

@FFFra as has been agreed on standup call I have created a separate issue for this one https://github.com/status-im/status-mobile/issues/17876
