### ISSUE TITLE
Share Screen -> Implement Share Wallet Address

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17865]
From the designs:
https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=2937-643562&mode=design&t=r1UAixLCMYOEphsl-4

- Please align with @ulisesmac for the correct components to use for this as some adjustments were recently made for the QR sharing components.

Check with design of what account is to be shared here - is it the default wallet account or like the last viewed account? 

Acceptance Criteria:
- implement the UI and use real data where possible.
- Component spec test covering the screen. (entry added in status_im2/core_spec.cljs)

**Comment by ulisesmac** [comment]
@tumanov-alex The designs for the QR code have been updated.

So I think it's better to first update the design of the component in an issue and then solve this one (that is using that component in this screen).

Have you started? if not, I could help with it

**Comment by J-Son89** [comment]
@tumanov-alex, @ulisesmac - imo, this feature is needed for 1.27 release and we have a tight schedule. It would be better to implement the screen/feature first  so users have the ability to share their accounts and the UI looks pretty good. We can then update the design system component to make the small UI adjustments once this screen is in place. I don't think it will create too much tech debt this way. Wdyt @ulisesmac ? I think it's the safer approach to ensure delivery 👌

**Comment by ulisesmac** [comment]
> @tumanov-alex, @ulisesmac - imo, this feature is needed for 1.27 release and we have a tight schedule. It would be better to implement the screen/feature first so users have the ability to share their accounts and the UI looks pretty good. We can then update the design system component to make the small UI adjustments once this screen is in place. I don't think it will create too much tech debt this way. Wdyt @ulisesmac ? I think it's the safer approach to ensure delivery 👌

Totally agree! @J-Son89  Let's proceed in this way :+1:

**Comment by Pau1fitz** [comment]
I will pick this one up

**Comment by pavloburykh** [comment]
@Pau1fitz thanx for the PR!

Please, take a look at the issues

### ISSUE 1 Share wallet address button does not respond on IOS

Reproducible on IOS only
Tested on IOS 16.7.2, iPhone X

**Steps:** 

1. Open share wallet tab
2. Tap in share button
3. See if share button responses

**Actual result:** share button does not respond

![photo_2024-01-10 16 33 25](https://github.com/status-im/status-mobile/assets/97245802/6deea40d-31a2-4449-bf38-4c4bd9231f5e)

**Expected result:** bottom sheet with receivers list should open

**Comment by pavloburykh** [comment]
### ISSUE 2 Share wallet elements are not fixed (can be tapped and moved to different directions) IOS 

Reproducible on IOS only
Tested on IOS 16.7.2, iPhone X

**Steps:** 

1. Open Share wallet tab
2. Tap QR element and try to move it. 

**Actual result:** elements are not fixed, can be moved to different sides. 


https://github.com/status-im/status-mobile/assets/97245802/3d689a8e-1ce8-4c01-a871-817b656a8023

**Expected result:** user should only be able to slide the element in case of multiple addresses.

**Comment by pavloburykh** [comment]
### ISSUE 3 Selected app is opened within Status app tap during sharing of wallet address (Android)

Tested on Android 12, Samsung Galaxy A 52

**Steps:** 

1. Open share wallet tab
2. Tap share button
3. Select app for sharing 
4. See if app is opened in the new tab

**Actual result:** selected app is opened within Status app. User needs to tap system back button to come back to Status app screens. 

![photo_2024-01-10 17 07 25](https://github.com/status-im/status-mobile/assets/97245802/74a4dd85-8a35-4bcf-8923-5c4c50115bae)

**Expected result:** selected app should be opened in separate tab.

**Comment by pavloburykh** [comment]
### ISSUE 4 Background of selected wallet does not inherit selected wallet colour 

**Actual result:** background colour is always the same

![photo_2024-01-10 17 12 22](https://github.com/status-im/status-mobile/assets/97245802/f3d7185b-0c6b-443d-ab51-59855b44f95a)


**Expected result:** background color inherits selected wallet colour

[Figma](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=2937-665825&mode=design&t=bZthfgXXubuoY6Xr-0)

<img width="398" alt="Shell for Mobile – Figma 2024-01-10 17-09-09" src="https://github.com/status-im/status-mobile/assets/97245802/d80c2896-0dcc-48ab-b034-36e91228e052">
