### ISSUE TITLE
Community Invites Not Updating After Changing Permission Requirements

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17860]
### Issue
Existing community invites are not reflecting updated permission requirements when permission criteria are changed. Sending a new request does reflect the new permissions.

### Summary
After creating a token-gated community with 'become a member' permissions on desktop, sending an invite on desktop, and opening that invite on mobile, editing the token requirements on desktop does not update the invite on mobile.

### Steps to Reproduce

1. Create a token-gated community with 'become a member' permissions (desktop).
2. Send an invite (desktop).
3. Open that invite (mobile).
4. Edit the token requirements (desktop).
5. Check the invite again (mobile).

### Actual Result
The token requirements are not updated on the mobile invite.

### Expected Result
The mobile invite should show the new token requirements.

Note: Sending a new request will correctly display the updated requirements.

**Comment by ilmotta** [comment]
Closing issue because community invites will be handled as URLs. This PR https://github.com/status-im/status-mobile/pull/17958 will be the first to use the new invitation strategy on mobile.
