### ISSUE TITLE
Trailing zeros formatting Issue for numerical token value in token gated communities permission requirements

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17871]
Followup of https://github.com/status-im/status-mobile/pull/17799 cc @ilmotta 

**Steps:** 

1. Open token gated community screen
2. Pay attention at formatting of token value in permission requirements description

**Actual result:** 

![photo_2023-11-10 13 58 26](https://github.com/status-im/status-mobile/assets/97245802/fa0b7f41-69cb-4136-b69a-5c351ccea7f4)

**Expected result:** 

<img width="375" alt="Communities for Mobile – Figma 2023-11-10 13-59-45" src="https://github.com/status-im/status-mobile/assets/97245802/9972b8cd-af6c-4b56-bd90-6cad43a3005a">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by clauxx** [comment]
Got de-prioritized by higher priority issues on my side and now I'm out till the end of the week, so will un-assign myself.

**Comment by Parveshdhull** [comment]
**More info:**  https://github.com/status-im/status-mobile/pull/17799
> We know we want to better format the number 0.00100000, but the problem is that this value arrives from status-go already as a string. I would like to fix this issue in a separate PR, with more care, given that the formatted output varies depending on the locale. Additionally, there are good practices to format large numbers to users and I couldn't figure out from Figma alone the full requirements.

**Current PR and discussion:** https://github.com/status-im/status-mobile/pull/18483

**Comment by ibrkhalil** [comment]
Is this fixed in https://github.com/status-im/status-mobile/pull/18766?
CC: @pavloburykh

**Comment by pavloburykh** [comment]
> Is this fixed in #18766? CC: @pavloburykh

yes. closing this issue.
