### ISSUE TITLE
Token icons are not fetched in token gated communities' requirements description

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17873]
Followup of https://github.com/status-im/status-mobile/pull/17799 cc @ilmotta 

**Steps:** 

1. Open token gated community screen
2. Pay attention if token icon is fetched for token value requirement

**Actual result:** token icons are not fetched

![photo_2023-11-10 14 19 05](https://github.com/status-im/status-mobile/assets/97245802/2512eac3-9e61-4523-9c2a-93151a36718a)

**Expected result:** token icons are fetched

<img width="367" alt="Communities for Mobile – Figma 2023-11-10 14-16-25" src="https://github.com/status-im/status-mobile/assets/97245802/b43cbd5b-fac4-481c-a38e-c5e0fb876b10">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mohsen-ghafouri** [comment]
to resolve this issue in need token list that will be done here #17965, i will continue working on it after they merged it

**Comment by ilmotta** [comment]
@mohsen-ghafouri, there's nobody assigned to https://github.com/status-im/status-mobile/issues/17965, so maybe if we really want to fix the token icons bug we should also pick 17965 and not wait.

@J-Son89 do you know if https://github.com/status-im/status-mobile/issues/17965 will be picked up soon? Or perhaps that's not a priority for the wallet team?

**Comment by J-Son89** [comment]
Someone from wallet can take it unless @mohsen-ghafouri has capacity to take it now? No problem for either way 👍

**Comment by mohsen-ghafouri** [comment]
@ilmotta @J-Son89 i'm currently working on this issue #17909 , if no body pick that one i will be happy to work on it. hopefully i can finish my current task by tomorrow

**Comment by ulisesmac** [comment]
@ilmotta @mohsen-ghafouri I already took that issue :+1:

**Comment by ulisesmac** [comment]
@mohsen-ghafouri 

PR done:  #18018

**Comment by ulisesmac** [comment]
@mohsen-ghafouri I'm taking this issue since I was involved in a very close solution :)
