### ISSUE TITLE
Theming the toast

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17878]
# Problem

The current toast implementation needs an `:icon-color` which needs to be provided along with the current app theme.
The toast should read the theme as other components in the app: using our theme HOC.

Example in  `status-im2.contexts.wallet.edit-account.view`:

```clojure
(rf/dispatch [:toasts/upsert
              {:id         :edit-account
               :icon       :i/correct
               :icon-color (colors/resolve-color :success theme)
               :text       (i18n/label message)}])
```

## Acceptance Criteria
App is working as expected and the toast is showing in the expected ways for every screen,

## Notes

Related issue:
- https://github.com/status-im/status-mobile/issues/16878

**Comment by codemaster115** [comment]
@ulisesmac I don't think the component needs `:icon-color` property.
But by following the figma design, it requires to have `:type` property to match proper icons

**Comment by ulisesmac** [comment]
> @ulisesmac I don't think the component needs `:icon-color` property. But by following the figma design, it requires to have `:type` property to match proper icons

@codemaster115 Interesting.

This issue could be a good opportunity to properly implement the toast :+1:  then.
Also 
- #16878 

is about refactoring the implementation.

So we could do everything in a single issue
