### ISSUE TITLE
Sometimes the updated community requirements are not being updated in mobile UI until user opens new invite to this community

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17874]
Followup of https://github.com/status-im/status-mobile/pull/17799 cc @ilmotta 

Issue is not reproducible every time. Sometimes it works, sometimes not. 

**Steps:** 

1. Desktop user creates non token gated (with no permissons)
2. Desktop user send invite to Mobile user
3. Mobile user opens community invite card
4. Desktop user changes non token gated community to token gated by setting  X permissions (for example 1 SNT to become a member)
5. See if community permissions are updated for Mobile user community UI

**Actual result:** permissions are not updated for Mobile user community UI. "Request to join" button is still active, user is able to send request although will not join the community if does not meet the requirements. The requirements are updated after Desktop user sends new invite and Mobile user follows this new invite. 

**Expected result:** community requirements should be updated once they are updated by community admin.  

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
Duplicate issue: https://github.com/status-im/status-mobile/issues/17860

**Comment by pavloburykh** [comment]
closing as duplicate
