### ISSUE TITLE
You are not a member of this group" is displayed in "view only"/"view and post" channels for user who meets permission requirements

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17876]
**Steps:** 

1. Create token gated community: set permissions "view only" or "view and post" for one of the channel
2. Share community to mobile user. Mobile user should meet permission requirements. 
3. Join community by mobile user
4. Open channel with permissions by mobile user
5. Observe the result

**Actual result:** "You are not a member of this group" is displayed in the bottom. User is not able to view or post messages in the channel. 

[Status-debug-logs (80).zip](https://github.com/status-im/status-mobile/files/13308303/Status-debug-logs.80.zip)

<img width="1062" alt="Status Desktop 2023-11-09 14-49-09" src="https://github.com/status-im/status-mobile/assets/97245802/7551df09-9cf9-46fb-8cab-f8339428c971">

https://github.com/status-im/status-mobile/assets/97245802/44c9ba59-ab07-4e1a-a34c-0973c6d89ed9

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by FFFra** [comment]
I wanted to give you a quick update on this issue: 

Earlier this week, I managed to reproduce the bug, but then it unexpectedly resolved itself. Could someone from QA please check if it's still working on your end? Depending on your findings, we can decide whether to adapt our approach or close the issue.

The backend call also appears to be functioning correctly (shared some logs). 
![image](https://github.com/status-im/status-mobile/assets/5999878/28aedae5-683b-4c73-acdf-138755c91947)

Below you can see one test where the flow is correct.
(Please note that If the permissions are set to view-only, the user can still post.) 

https://github.com/status-im/status-mobile/assets/5999878/94a760b4-89d6-4d76-b3d2-3d9cca49c1ab

One last thing to decide with the design team: what should be the behavior if the admin updates permissions? So it only updates the settings once the user leaves the community.

https://github.com/status-im/status-mobile/assets/5999878/07562ce3-e9f4-47c8-8f15-d8717140fbcb

**Comment by pavloburykh** [comment]
@FFFra thank you. Confirmong that the issue is no longer reproducible in develop. So I will close it. 

I have opened a separate issue for an edge case when channel permissions are updated by admin at the moment when mobile member is located on channel/community screen https://github.com/status-im/status-mobile/issues/17990.
