### ISSUE TITLE
Continue button is hidden behind active keyboard on create Watch-only account screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17888]
**Steps:** 

1. Open create "Watch-only" account screen
2. Open keyboard
3. See if continue button is displayed above active keyboard

**Actual result:** 

**IOS**

![photo_2023-11-13 10 57 46](https://github.com/status-im/status-mobile/assets/97245802/d3b9fe44-5a69-4be6-8a72-6d763db84b5a)

**Android**

![photo_2023-11-13 10 57 49](https://github.com/status-im/status-mobile/assets/97245802/6ae72855-21e0-4a7d-b8ff-0bf6c3e902a4)

**Expected result:** "Continue" button should be located above active keyboard

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
The solution should make use of https://github.com/status-im/status-mobile/pull/17737 👍
