### ISSUE TITLE
Contact requests are not delivered

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17898]
# Bug Report

## Problem 
CRs are not delivered to the recipient

#### Expected behavior
can see CR

#### Actual behavior
no CR

### Reproduction

1. User A: create profile
2. User A: scan profile of UserB > tap add to contacts
3. User B: wait for contact request (5 mins)

### Additional Information

- Status version: release 1.26 RC1 
- Operating System: Android, iOS
- User B: [logs (64).zip](https://github.com/status-im/status-mobile/files/13349581/logs.64.zip)
- User A: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13349593/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by vitvly** [comment]
Update on findings: we did some testing with @cammellos , turns out that the problem is related to filter, and affects both mobile and desktop. Whenever light client mode is enabled, the device is not able to receive to receive contact requests, but is able to send them successfully.

**Comment by churik** [comment]
It should be fixed on latest status-go develop, reopen if it is still the case
