### ISSUE TITLE
"java.lang.NullPointerException" error is shown if  app while is relaunched in the flight mode

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17909]
### Steps:
1. Close the app
2. Turn on the flight mode
3. Open the app again

### Actual result:
Error on the Android "java.lang.NullPointerException" error is shown for Android

![image](https://github.com/status-im/status-mobile/assets/52490791/fc207d01-bbca-4742-b554-270ca9ccd5bf)

Error on the IOS "No protocols method IMap. - dissoc defined"

https://github.com/status-im/status-mobile/assets/52490791/759d5944-55f4-455a-8064-0da40190f5e3

### Logs:
[logs (3).zip](https://github.com/status-im/status-mobile/files/13363509/logs.3.zip)

### ENV:
- Nightly: 15 Nov 2023

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko what's expected behavior? any proper message or design for when ever user doesn't have network ?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko what's expected behavior? any proper message or design for when ever user doesn't have network ?

hi @mohsen-ghafouri the expected result for this scenario is that the login page should appear, similar to when the user has an internet connection.

https://github.com/status-im/status-mobile/assets/52490791/f4cbdc17-407a-44db-b163-d5802e3194be
