### ISSUE TITLE
Double arrow icon is misplaced in new wallet [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1792]
### Description

*Type*: Bug

*Summary*: Double arrow icon should be centered and not top-aligned

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/30215330-5916cd82-94b8-11e7-9cac-7e5ff4249201.png)

### Additional Information
* Status version: 0.9.10-75-gad7c6b85+
* Operating System: Android

**Comment by annadanchenko** [comment]
ok on Android and iOS build 0.9.10-78-g8381f00e+
