### ISSUE TITLE
Wallet - Fix or re-implement wallet integration tests

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17921]
# Problem

We recently merged a PR that mistakenly disabled integration tests due to larger refactors. They have been re-enabled by the merged PR https://github.com/status-im/status-mobile/pull/17900.

Right now the wallet integration tests in `status-im2.integration-test.wallet-test` are failing and were skipped temporarily by 17900 to get it merged. 

## Root cause

My best guess is that commit https://github.com/status-im/status-mobile/commit/45df308dd0d0e2b3945a70f514dcf5fc5f596abe broke the wallet integration tests because it was merged before I re-enabled integration tests in `develop`.

## Acceptance Criteria

Fix, or re-implement (if they don't make sense anymore) the existing wallet integration tests. Not required as an acceptance criteria, but consider using this issue as an opportunity to improve them.

**Comment by J-Son89** [comment]
old wallet will be dropped in 1.27 - we can remove these old tests. Can we update this issue to remove that skipped test and write new wallet integration tests? 🤔

**Comment by ilmotta** [comment]
@J-Son89, please, feel free to update the issue as you see fit.

**Comment by J-Son89** [comment]
Thanks, will update it!

**Comment by OmarBasem** [comment]
@ilmotta @J-Son89 is this issue still relevant?

**Comment by ilmotta** [comment]
@OmarBasem, thanks for spotting this. Issue can be closed :)

Side note: I noticed `contract-test.wallet-test/wallet-search-ens-test` is commented and that it was disabled by this commit 2b40a4d0c42fca8e14de1cbc92d50de7acf9001f (Feature/remove reagent atom from theme (#19706)). Maybe something you and the wallet team are aware already?

**Comment by OmarBasem** [comment]
> @OmarBasem, thanks for spotting this. Issue can be closed :)
Side note: I noticed contract-test.wallet-test/wallet-search-ens-test is commented and that it was disabled by this commit https://github.com/status-im/status-mobile/commit/2b40a4d0c42fca8e14de1cbc92d50de7acf9001f (Feature/remove reagent atom from theme (https://github.com/status-im/status-mobile/pull/19706)). Maybe something you and the wallet team are aware already?

@ilmotta thanks for noting!

@J-Son89 I think you know about contract tests?
