### ISSUE TITLE
 Unable to Open ETH Account on BSC Network or BSC Testnet

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17935]
### Steps:
1. Switch on the BSC Network or BSC testnet
2. Attempt to open any existing account in **NEW** wallet page

### Actual result:
The account continuously remains in a loading state, preventing successful access.
![image](https://github.com/status-im/status-mobile/assets/52490791/7e966c1b-3fe3-4c2b-9245-b168cc7ad2b0)

### Expected result:
The account is able to be opened

### Logs:
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/13393865/Status-debug-logs.2.zip)

**Comment by J-Son89** [comment]
do we still need this @VolodLytvynenko ?

**Comment by VolodLytvynenko** [comment]
> do we still need this @VolodLytvynenko ?

@J-Son89 Can be closed. Thanx!
