### ISSUE TITLE
Support URL preview for universal community URL

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#17954]
# Feature Issue

### User Story

```txt
As a user, 
I want to send a message with community link
So that message receivers can see basic community info without click on the URL
```

### Description
design link https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=3963-305465&mode=design&t=Ik6dByDrKbbWFmxw-4

<img width="659" alt="CleanShot 2023-11-21 at 15 18 01@2x" src="https://github.com/status-im/status-mobile/assets/15090582/0e16482e-e09a-4815-9733-bf7f9739cfea">

### Acceptance Criteria
- show loading skeleton when fetching community data from waku
- show correct community info in the preview

### Notes
this relies on the [internal link card component](https://github.com/status-im/status-mobile/issues/17961), which is not implemented yet https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=11182-147560&mode=design&t=bK9svcl7KnEyiSAQ-4 
related issue on fetching community data https://github.com/status-im/status-mobile/issues/17770

**Comment by ibrkhalil** [comment]
I can pick it up since I am working on a new implementation of sharing community links.

**Comment by yqrashawn** [comment]
thanks @ibrkhalil 
just created another issue for internal link card component https://github.com/status-im/status-mobile/issues/17961

**Comment by yqrashawn** [comment]
> since I am working on a new implementation of sharing community links.

Do you have an issue for this? Because I have [this issue using the new universal link when sharing community](https://github.com/status-im/status-mobile/issues/17585) but didn't find any sharing community feature implemented in the app

**Comment by ibrkhalil** [comment]
> > since I am working on a new implementation of sharing community links.
> 
> Do you have an issue for this? Because I have [this issue using the new universal link when sharing community](https://github.com/status-im/status-mobile/issues/17585) but didn't find any sharing community feature implemented in the app

Currently I have a bugfix WIP on status-go for this https://github.com/status-im/status-mobile/issues/17116

**Comment by ibrkhalil** [comment]
They have different bottom sheet options, One for inviting and one for sharing I think.
But the link preview should work for both I think.

**Comment by ibrkhalil** [comment]
To be done, Create the community channel preview and the user link preview.
I'll do them once I have capacity.
