### ISSUE TITLE
Messages sent prior to joining community are fetching randomly 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17959]
# Bug Report

## Problem 
Joining a community that has a history of 24+ hours leads to fetching ~1h of messages for new members.
Some of the messages are fetched partially

#### Expected behavior
can see all messages for a certain period (7 days?) 

#### Actual behavior
see messages for the last hour, message that contains 6 images contains only 2

Check the history from mobile(member):

https://github.com/status-im/status-mobile/assets/4557972/28f00b71-3c73-4fd6-b2b8-68313db10557

History from desktop (admin):

https://github.com/status-im/status-mobile/assets/4557972/3eec5f4d-8414-4e9f-91ab-3c4a880313e6

<img width="788" alt="Status Desktop 2023-11-21 18-54-35" src="https://github.com/status-im/status-mobile/assets/4557972/9787c022-0c55-4167-aade-7d7195983646">

### Reproduction
**Prerequisites:** have a community with history (in a particular case - non-token-gated, has token-gated channels only)

1) Admin: invite a user
2) Member: join community and check the history 

### Additional Information

- Status version: [RC4](https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F0.15.x/) , 1.26 RC mobile
- Operating System: Android, iOS, Mac OS
- Logs(member): 
[logs (67).zip](https://github.com/status-im/status-mobile/files/13429530/logs.67.zip)
- Logs (admin): [geth copy 2.log](https://github.com/status-im/status-mobile/files/13429533/geth.copy.2.log)

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
**UPDATE (Jan 05, 2024):** issue still exists

**Example of community with history:** https://status.app/c/G8EAAMR_fz8tsCQ-aR2gq2w3CSTUy-_Nz00e4ED4ST-nHDjkzSNsObUDXY_3gJsiBI6x9V9szT-jiCmAfMb7FZlRKmmOv1Dip_1XfDKeFNiGpNAJjwgcIRRFZEYHyiLF5CHubDlkrHOQ5Ig3knI7kcElAuUUIUx8egoQkl0SCooEGCWwsuSjQzz0m4E0RucwoDzbzK1A-j6cLeurx8vpenpYl8-HDg==#zQ3shwQnEfMtcXpHXF4qJPyCGgw2F18N3nbGzYbzsVHnMq4yK

**Actual result:** 

By Admin control node (Desktop) I see the history starting from Jan 14. 2024

https://github.com/status-im/status-mobile/assets/97245802/c0fba797-0805-4634-bf1c-c6592c289915

By newly joined mobile user only some part of history starting from Jan 29, 2024 has been fetched.  Aside from this the problem with broken mentions still exists, re-opened the [issue](https://github.com/status-im/status-mobile/issues/17229#issuecomment-1927544288) on that. 

https://github.com/status-im/status-mobile/assets/97245802/05a56df2-5bd6-4325-88a1-5d77399b1d02

[Status-debug-logs (100).zip](https://github.com/status-im/status-mobile/files/14169066/Status-debug-logs.100.zip)

cc @cammellos

**Comment by churik** [comment]
Part of message-reliability problem, might be not possible to fix it on our side, descoping

**Comment by qfrank** [comment]
hi @churik , is this issue still valid? I tried create closed community use iOS simulator, made some messages history, wait 2-3 days, create another userC to join the community, userC has no issues on fetching all the messages, maybe I should wait longer, > 7 days?

**Comment by churik** [comment]
I'll try to recheck it on nightly, thanks!

**Comment by churik** [comment]
Yes, I tried to fetch the histrory from 3 days, also was fetched in full for several users, closing the issue for now
