### ISSUE TITLE
Too small space between channel category and bottom of the screen on community home page (IOS)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17967]
Reproduced on IOS 16.7.2 iPhone X

**Steps:** 

1. Open home page of community that has at least 1 channel category
2. Fold the category with channels
3. Scroll to the bottom of channels list
4. Pay attention at the space between channel category and bottom of the screen

**Actual result:** 

![photo_2023-11-22 13 54 52](https://github.com/status-im/status-mobile/assets/97245802/0664cb53-bce5-4933-8e35-34b856b46611)

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-404249&mode=design&t=eJ7rvsFVjIlvexyi-0)

<img width="247" alt="Communities for Mobile – Figma 2023-11-22 13-59-29" src="https://github.com/status-im/status-mobile/assets/97245802/dabc8b71-3971-4fbe-92e2-a5e0696356a8">

### Additional Information

- Status version: nightly 
- Operating System: iOS

**Comment by Parveshdhull** [comment]
related conversation: https://discord.com/channels/624634427930312714/928625369542713396/1177561187446169650

**Comment by Parveshdhull** [comment]
expected result: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16465-74314&mode=design&t=PgeZhBinrfZmYADF-0

**Comment by Parveshdhull** [comment]
![image](https://github.com/status-im/status-mobile/assets/17097240/0b18fe10-63e6-415a-bb6a-2ab6df1469b6)
