### ISSUE TITLE
Wallet: Improve emoji screen gesture/scrolling performance 

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17964]
A follow up of: https://github.com/status-im/status-mobile/pull/17891

The emoji screen experiences some lagging when scrolling fast, or when scrolling and then trying to swipe down the screen with a gesture.

**Comment by ulisesmac** [comment]
I'd like to take this issue, @OmarBasem  are you planning or working on it?

I'd start it within some days since I'm still busy with other more relevant issues rn.

**Comment by OmarBasem** [comment]
@ulisesmac sure you can take it. But please wait for https://github.com/status-im/status-mobile/pull/17891 to be merged first.
