### ISSUE TITLE
Wallet: ENS name resolving

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17963]
Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-192881&mode=design&t=cd4DDxR6QRAU9CSo-4

**Comment by briansztamfater** [comment]
Not sure if the figma link in the description is right
If its for the Send flow it should be this https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-192881&mode=design&t=cd4DDxR6QRAU9CSo-4 (btw designs are mostly already in place, but we need to make the backend integration)

**Comment by OmarBasem** [comment]
Thanks @briansztamfater, the link was indeed incorrect.
