### ISSUE TITLE
Create token component

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17965]
For the wallet designs the token image assets are all stored locally. Rather than have a long hardcoded list of assets it would be better to create a component similar to icon component which handles the resolving of token images. These assets should be resolved by their symbol - eg "SNT"

In the case of no asset being available for a given token there is a fallback image - align with Desktop/design for this image.

Also there is a community token which are passed as a base64 string 

Consider creating a new folder for the assets if there is unused/old assets in the old tokens folder.

Acceptance criteria:
Token component to resolve by symbol, base64 string or fallback image.
Add some test coverage if possible.
Verify image assets are correct

**Comment by ulisesmac** [comment]
Hey @J-Son89, about:

> Also there is a community token which are passed as a base64 string

Do you know where is it (namespace or file)?

**Comment by J-Son89** [comment]
You can check with @mohsen-ghafouri . You need to get invite to a token gated community link with custom asset to see how this data structure looks. @FFFra or @ajayesivan might know about this too

**Comment by mohsen-ghafouri** [comment]
@J-Son89 @ulisesmac there is an issue with latest changes that we can't see token gated community with custom assets, but here is relevant codes

https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/communities/overview/view.cljs#L137
https://github.com/status-im/status-mobile/blob/develop/src/status_im/communities/core.cljs#L85
