### ISSUE TITLE
Discrepancy in community joining process between desktop and mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17971]
# Bug Report

## Description
Currently, there is a visible difference between mobile and desktop when the community channels are available and when we share address.

**On desktop:**
- you can see a list of channels and view non-token-gated ones prior to sharing address

![image](https://github.com/status-im/status-desktop/assets/4557972/3b8a3716-e04f-4ead-8c1e-3912b7a3153c)

**On Mobile:**
- prior to joining **non-token gated community** you can see only channel list for non-token gated communites and they are not availble, you can't view channels inside:
![IMAGE 2023-11-22 14:26:55](https://github.com/status-im/status-desktop/assets/4557972/b4a3105a-6f2f-4a53-8ec7-60be9b97e459)
- prior to joining any community with token-gated permissions (even if it was set for the channels only) even the list of channels is not available.
![IMAGE 2023-11-22 14:29:19](https://github.com/status-im/status-desktop/assets/4557972/73007e65-8c9f-4d90-ab60-f09c61e47a74)
Mobile [design](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7035-462899&mode=design&t=wVQzOh8qhSjMMad6-4 ): (that actually does not explain the situation with list not available for communities with token-gated channels(was implemented here: https://github.com/status-im/status-mobile/pull/17866), but I suppose it will be addressed separately later) 

### Conclusion

We should align flows of joining community and available channels with desktop.
Mobile design: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1538%3A129984&mode=design&t=jdMaZhyqV8tOkosL-1 

So non-taken gated channels should always be available to "View" if there is no "Become a member" token-gated permssion is set on community level.
Post action should be available after joining.

**Comment by yqrashawn** [comment]
Updates:

removed the `joined` checker on mobile when pressing channel

no message, chat not found

```log
 ERROR  2023-12-04T07:06:23.652Z ERROR [status-im.chat.models.loading:57] - failed loading messages 0x02ea197bb58ee0c53c38cc6edef686e232f639d419f1c1df03c254dcaa47151093b01517f0-c2b0-4b8e-8da0-5d99f8da6d11 {:code -32000, :message "can't find chat"}
 ERROR  2023-12-04T07:06:23.862Z ERROR [status-im.chat.models.reactions:52] - failed loading reactions 0x02ea197bb58ee0c53c38cc6edef686e232f639d419f1c1df03c254dcaa47151093b01517f0-c2b0-4b8e-8da0-5d99f8da6d11 {:code -32603, :message "method handler crashed"}
 WARN  2023-12-04T07:06:23.875Z WARN [status-im2.common.json-rpc.events:63] - :json-rpc/error
 wakuext_markAllRead :error
 {:code -32000, :message "chat not found"}
 :params
 ["0x02ea197bb58ee0c53c38cc6edef686e232f639d419f1c1df03c254dcaa47151093b01517f0-c2b0-4b8e-8da0-5d99f8da6d11"]
```

![CleanShot 2023-12-04 at 15 07 16@2x](https://github.com/status-im/status-mobile/assets/15090582/554a4542-ffba-43ca-85f1-2aa6ab226ad5)

**Comment by churik** [comment]
@yqrashawn may it be https://github.com/status-im/status-go/pull/4416 ?

**Comment by yqrashawn** [comment]
@churik seems it's not related

https://github.com/status-im/status-go/pull/4416 changes the response of join community request
we need to somehow subscribe to community message without joining in this issue

**Comment by yqrashawn** [comment]
desktop code https://github.com/status-im/status-desktop/blob/02589421bbfac5afea1d861f69307e5a32e2d178/src/app/modules/main/communities/module.nim#L299
might be related

`spectateCommunity`
