### ISSUE TITLE
ENS displaying inheriting on mainnet after sync with user on goerli

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17982]
### Steps to Reproduce:
1. `DeviceA` switch the app to  Goerli network 
2. `DeviceA`purchases an ENS using ETHgo 
3. `DeviceB` syncs with `DeviceA` using a release or nightly build (builds where the mainnet is enabled by default after onboard or sync)

### Actual result:
After the sync, `DeviceA's` ENS is displayed for `UserB` on mainnet and resolved for other users

### Expected result:
After the sync, `DeviceA's` display name is displayed for `UserB` (in case if current users use different networks)

**Comment by VolodLytvynenko** [comment]
CC: @qfrank

**Comment by qfrank** [comment]
<img width="474" alt="image" src="https://github.com/status-im/status-mobile/assets/12406719/1ce47888-798e-4b18-8abe-cb8dc5bc5b4d">

Do you think adding chainID to the VerificationRecord would make it look better? @cammellos

**Comment by qfrank** [comment]
<img width="736" alt="image" src="https://github.com/status-im/status-mobile/assets/12406719/c125246a-f0fd-4590-9131-4bc8eb151b19">

Should we consider supporting multi-chain here? @cammellos

**Comment by qfrank** [comment]
> and resolved for other users

Hi @VolodLytvynenko, regarding "resolved for other users", could you share more details about how you managed to reproduce the issue?

**Comment by VolodLytvynenko** [comment]
@qfrank take a look more detailed steps
### Steps:
1. `Device1` as `User1` (**first screen**) is on goerli. The ENS is purchased using goerli ETH (at the **6th** second he checks to prove he is on Goerli network )
2. `Device2` (**second screen**)  using release build sync with `Device1` (**at 30th second**)
3. `Device1` login as `User2` and check network is mainnet  (**at 50th second**)
4. `Device2` add current `User2` to contacts and chat with him (**on 2:12**) **(the ens is not resolved yet. At least 1 minute should be passed)**
5. ENS of `User1` `Device2`  is resolved  for `Device1`which uses 'User1' (**at 2:44**) 
6. Both users check if they are on mainnet (at 3:00)

https://github.com/status-im/status-mobile/assets/52490791/000a4eaa-334a-48ce-89fb-46f765852d5e

**Comment by qfrank** [comment]
From the video, I can't tell if user2 has been newly created. Could it be that user2 was already a contact of user1 before being set as a mutual contact in the video? @VolodLytvynenko
If they were mutual contacts prior to the creation of this video, it's possible that the database already contains the ENS name for user2. If that's the case, we might need to consider multi-chain support for the VerificationRecord. cc @cammellos

**Comment by VolodLytvynenko** [comment]
> From the video, I can't tell if user2 has been newly created. Could it be that user2 was already a contact of user1 before being set as a mutual contact in the video? @VolodLytvynenko If they were mutual contacts prior to the creation of this video, it's possible that the database already contains the ENS name for user2. If that's the case, we might need to consider multi-chain support for the VerificationRecord. cc @cammellos

@qfrank No. `User2` was just created and has never been a mutual contact for `User1`. I created him just before the record creation

**Comment by qfrank** [comment]
Can you share the logs relate to user2? thanks @VolodLytvynenko

**Comment by qfrank** [comment]
> Verification of ENS should be on mainnet unless specifically set in the config. This is a build time config, and not something the user can change (i.e if you change from mainnet to goerli, verification is not impacted, it's set at build time). Testing builds can be set to goerli, but release build should be set to mainnet and cannot be changed.

So after checking the code and according statement from @cammellos , could you( @VolodLytvynenko ) tell me what's the version for Device1 ? PR version or release version? If it's a PR version, then the result is normal not bug. If it's release version, then i have to check the logs relate to User2. cc @cammellos @churik

**Comment by VolodLytvynenko** [comment]
> > Verification of ENS should be on mainnet unless specifically set in the config. This is a build time config, and not something the user can change (i.e if you change from mainnet to goerli, verification is not impacted, it's set at build time). Testing builds can be set to goerli, but release build should be set to mainnet and cannot be changed.
> 
> So after checking the code and according statement from @cammellos , could you( @VolodLytvynenko ) tell me what's the version for Device1 ? PR version or release version? If it's a PR version, then the result is normal not bug. If it's release version, then i have to check the logs relate to User2. cc @cammellos @churik

@qfrank Yes. It was a PR version. Only on the PR version the goerli ENS can be purchased

**Comment by VolodLytvynenko** [comment]
The issue is not valid
