### ISSUE TITLE
Communities - Share Community Channel

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17994]
Designs: https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=2344-285051&mode=design&t=Uaz0GGpOtwjH8nfl-4

Add this to the options for On Long Press of a community on the home page
Add this to the options for in community page

<img width="666" alt="Screenshot 2023-12-20 at 16 17 41" src="https://github.com/status-im/status-mobile/assets/22799766/5026e8fd-283c-4d4e-b5ae-a4c495b78e6d">

Similar method to:
https://github.com/status-im/status-mobile/issues/18260

https://github.com/status-im/status-mobile/pull/18124

**Comment by J-Son89** [comment]
@ajayesivan @FFFra @ilmotta

**Comment by Pau1fitz** [comment]
I can take this one

**Comment by J-Son89** [comment]
@alwx, @OmarBasem , @smohamedjavid  any of you have idea where the details for the share community channel can be found? Eg the url etc? Or at least how that's built?

**Comment by OmarBasem** [comment]
@J-Son89 which details? Are you asking for designs?

**Comment by Pau1fitz** [comment]
I believe @J-Son89 wants to know where the share sheet should link to. In the [PR referenced above](https://github.com/status-im/status-mobile/pull/18124/files#diff-f38aa0d04f9fa859f3c9efc4fe82470baf44d15e545d9ee0e7ea3d422dbecc8eR122) you can see that it shares a `profile-link`

```
{:on-press    #(share/open {:url profile-link})
```

See [here](https://react-native-share.github.io/react-native-share/docs/share-open#supported-options) for a list of options which the react-native-share library supports

**Comment by smohamedjavid** [comment]
> @alwx, @OmarBasem , @smohamedjavid any of you have idea where the details for the share community channel can be found? Eg the url etc? Or at least how that's built?

@J-Son89 

The URL schema for 
- community channels is `https://status.app/cc/{community-channel-id}#{community-id}`
- community is `https://status.app/c/{community-id}`

I'm not sure whether we have helper methods for generating share links (except for profiles). 

Maybe @ilmotta or @ajayesivan can help.
