### ISSUE TITLE
Communities - Share Community Channel QR

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#17993]
Designs: https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=2345-300688&mode=design&t=Uaz0GGpOtwjH8nfl-4

- Add this to the options for On Long Press of a community on the home page
- Add this to the options for in community page

**Comment by J-Son89** [comment]
cc @ilmotta @FFFra @ajayesivan

**Comment by Pau1fitz** [comment]
I can pick this one up @J-Son89
