### ISSUE TITLE
Enable logs in Testfairy

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1799]
### User Story

As a dev/tester, I want to see app device logs in Tesfairy so we can quickly diagnose problems.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: We now (or soon) have support for logs in release build, but these aren't pushed to Testfairy for some reason. See https://github.com/status-im/status-react/pull/1788 for introduction of prefix file. There might be some knob we forgot to turn.

#### Expected behavior
See logs in Testfairy.

#### Actual behavior
Don't see logs in Testfairy.

### Additional Information
* Operating System: iOS

**Comment by oskarth** [comment]
Notes:

- Official iOS docs, which we've followed AFAICT: https://docs.testfairy.com/iOS_SDK/Integrating_iOS_SDK.html

- TF logs are called via NSLog macro, which might not be on same log level as RN calls.

- https://docs.testfairy.com/Platforms/React_Native.html => might need separate logging for RN stuff, this wouldn't get us most important logs though (iOS weirdness), but it might give us CLJS logs via `log` macro.

**Comment by oskarth** [comment]
If I put the following `+  NSLog(@"*********** NSLog called");` in `AppDelegate.m` I can see the following in TestFairy: "00:00 4/Status: *********** NSLog called".

However, I also redefined the NSLog macro to print all instances of macro being used, but something seems to be off (recursive macro call? not sure.), since (a) TFLog is obviously called (b) it doesn't print "NSLog macro called".

See https://github.com/status-im/status-react/pull/1800/files for experiment

UPDATE:

Tracing log call I believe RN uses `asl_log` (`man asl`): https://github.com/facebook/react-native/blob/master/React/Base/RCTLog.mm#L80 Also see https://github.com/facebook/react-native/commit/d1b14ef0627dc04847500faa7fef75fd3c22c900

This means the question has turned into: How do we call `TFLog` on `asl_log` calls? Since there are standard tools for dealing with ASL this should be doable.

UPDATE 2:

It appears we can use `RCT_EXTERN void RCTAddLogFunction(RCTLogFunction logFunction);`. Investigating.

**Comment by annadanchenko** [comment]
Can see logs for iOS on TestFairy, sample session https://app.testfairy.com/projects/4803590-status/builds/6530686/sessions/1/?accessToken=sIKeZ2tn6pG6UbUH9-cc5g-1sjo

**Comment by oskarth** [comment]
Fixed in develop.
