### ISSUE TITLE
UI issues in new Wallet on Transactions History tab

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1801]
Issues:
1. Grey colour of the icons for incoming/outgoing transactions. Expected: as in design: green for incoming, blue for outgoing. Both Android and iOS.
2. No "phone icons" on iOS (carrier, time, battery percentage..)
3. Tab titles "Unsigned/History" are too small on iOS
4. Postponed/Pending sections are always empty now - remove them or check with design team how to show they are empty... Now there are 2 words on the screen where it's not clear they are Section titles. both Android and iOS
5. If pull down list of the transaction then no loading indicator is shown, on iOS
6. ">" icon on the right side of transaction is of different colour (not light grey but dark grey) and size. both Android and iOS
7. There is no line under tabs Unsigned/History with blue line under active tab. In the design there is such line. both Android and iOS
8. There should be no line between header with word Transaction and the rest of the screen

![img_0582](https://user-images.githubusercontent.com/6584810/30241353-803563ba-958a-11e7-9ce3-740b3f9c85d7.jpg)

Design (iOS):

<img width="385" alt="screen shot 2017-09-09 at 15 50 30" src="https://user-images.githubusercontent.com/6584810/30240306-b0e96d58-9576-11e7-9d0f-d84723be8cd9.png">

Design (issues 7,8 - should be as in design below 2, 1)
<img width="1069" alt="screen shot 2017-09-09 at 15 58 01" src="https://user-images.githubusercontent.com/6584810/30241332-1a0b946a-958a-11e7-84af-bb4bb684f902.png">

real iOS device iPhone 7 plus
develop build 0.9.11d77

**Comment by asemiankevich** [comment]
Transaction history is cut in the end
![image](https://user-images.githubusercontent.com/28752642/30268134-657f5ba2-96ed-11e7-85a4-5833531ffa18.png)

**Comment by annadanchenko** [comment]
Fix for this issue introduced regression bug:
When syncing is in progress then no progress bar for syncing is shown on Chats screen, inside chats and on new Wallet screen
Expected: when syncing is in progress then progress bar (narrow blue line) is shown in Chats, inside Chat (1-1 chat, console, group chat, etc) and Wallet screen

![screenshot_20170911-150948](https://user-images.githubusercontent.com/6584810/30273926-d34cb57e-9703-11e7-88d2-a8fdc0ede935.png)

**Comment by jeluard** [comment]
Fixed now.

**Comment by annadanchenko** [comment]
Regression bug "Syncing progress bar" is fixed and shown now as expected. Issues 1-8 are fixed. @asemiankevich can we close this issue and open a separate one about last item not fully shown? (added as a comment by you).
