### ISSUE TITLE
Wrong spacing on the channel-actions component

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#18032]
# Bug Report

## Problem 
[comment]: # (A problem description)
On iPhone 13 the `channel-actions` component is misaligned i.e. there's extra space to the right, since we were using dimensions from the old designs (iPhone 11 Pro). 

The design team was [notified](https://discord.com/channels/624634427930312714/928625369542713396/1179739828112330752) and they will review it @pedro-et.

<img src="https://github.com/status-im/status-mobile/assets/21865759/2a08b3c7-a4b5-4eb1-a70a-8791d27ca4c1" width=200/>
<img src="https://github.com/status-im/status-mobile/assets/21865759/7c006d4d-185d-4c42-8b7c-b7859675c0fc" width=200/>

#### Expected behavior
The `channel-actions` component fills the entire width of the screen.

#### Actual behavior
The `channel-actions` component has extra space to the right.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Closing because PR https://github.com/status-im/status-mobile/pull/21313 made this issue irrelevant.
