### ISSUE TITLE
 Incorrect total account balance calculation  for default and watch only accounts

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18038]
The fixing of this issue should begin after merging https://github.com/status-im/status-mobile/pull/17879

Reference to https://github.com/status-im/status-mobile/pull/17868#issuecomment-1832019529 and to https://github.com/status-im/status-mobile/pull/17821#issuecomment-1831870173

### Steps:
Log in as a user with various tokens located on various networks

### Actual result:
The account balance calculation appears incorrect for default and for watch-only accounts

![image](https://github.com/status-im/status-mobile/assets/52490791/0756b89c-11bf-4457-8d12-46c9516f6124)

### Expected result:
How the balance is calculated for the same user within Metamask (in fact current user has only on Arbitrium: 0.001 ETH = 2.06 USD). So, the total amount should be 2.06 USD)

![image](https://github.com/status-im/status-mobile/assets/52490791/33312d4b-8758-4eeb-bd6b-444e473562ee)

How the balance is calculated for the same user within Desktop (Take a look, there is bridget USDC = 4.99 usd which is not included into total balance calculation.)
![image](https://github.com/status-im/status-mobile/assets/52490791/f08bc972-2ef8-4989-bfe3-068160848b56)

### Additional info:

Please let me know if you don't have an account with specific tokens, and I can share the seed phrase via private message

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - I believe this issue is fixed in https://github.com/status-im/status-mobile/pull/18078. Please help us verify.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - I believe this issue is fixed in #18078. Please help us verify.

hi @smohamedjavid that's correct. Thank you!
