### ISSUE TITLE
Quo - fix longname for component wallet/account card

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18044]
If the name is too long on a wallet account it should be an ellipsis at the end of the name to make it sit right.

 The account name should stay on one line and end with ellipsis (...)
<img width="232" alt="Screenshot 2023-12-01 at 12 31 08" src="https://github.com/status-im/status-mobile/assets/22799766/861141b3-d07a-4577-b589-2c058878d618">

Here's an example:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7014%3A65125&mode=design&t=AYBw5yLYHfVclhgo-1

**Comment by Pau1fitz** [comment]
I can take this one

**Comment by OmarBasem** [comment]
> I can take this one

cc @J-Son89
