### ISSUE TITLE
Sometimes username is not displayed after sync

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18041]
This bug is reproducible by @qoqobolo on her account. So ping her for additional details. 

**Steps:** 

1. User A (Desktop) generates sync QR
2. User B (Android) scans sync QR
3. Check if username is displayed for User B in Profile

**Actual result:** username is blank

![IMAGE 2023-11-29 11:34:07](https://github.com/status-im/status-mobile/assets/4557972/0fcd602e-75d9-49aa-8fa5-738db54f5846)
![IMAGE 2023-11-29 11:34:26](https://github.com/status-im/status-mobile/assets/4557972/b1b7a5b1-6075-4d5e-9009-ca69058137f4) 

**Expected result:** username is displayed
 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by qoqobolo** [comment]
The issue is not reproducible in develop.
