### ISSUE TITLE
Refactor protocol listeners

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1805]
Namespace `status-im.protocol.listeners` should be refactored as pipeline (composition) of functions that each correspond to one step in the payload transformation. Each of those functions has to conform with the following rules:

- in case of a successful transformation, return value has the following format `{:message VALUE}`
- in case of any error or failure, return value in a format like this `{:error DESCRIPTION}`
- finally, if the input to the current function is in the error format, it should just return that same input and that's it

This will allow us to have a simple `comp` or even `->` in the `message-listener` callback instead of lots of nested conditionals. Also, each individual step would be a bit more unit testable.

(Basically, this would be Either monad, for the theoretically inclined)

**Comment by asemiankevich** [comment]
I would say the message exchange works as expected after the refactoring
