### ISSUE TITLE
Some tokens are missing titles

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18072]
While testing the new wallet I have noticed that some of the tokens are missing titles. So far I have faced USDC and STORJ tokens without titles but there definitely can be more of such cases. 

![photo_2023-12-05 13 22 17](https://github.com/status-im/status-mobile/assets/97245802/e9f97267-6999-4605-b2ac-60468e1a792a)
![photo_2023-12-05 14 01 37](https://github.com/status-im/status-mobile/assets/97245802/b4f37a55-6337-445a-80ff-cad476950efc)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by OmarBasem** [comment]
@shivekkhurana issue not relevant anymore, was fixed in https://github.com/status-im/status-mobile/pull/18136
