### ISSUE TITLE
Communities: Share airdrop address in non token-gated community

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#18081]
# Feature Issue

### User Story

- As a User
  - Joining a community
- I want to select my airdrop address from my full account / address list
- So that I can maintain access to the community if it becomes token-gated
- And I can be granted community permissions

### Technical tasks
- [x] Use component `settings.settings-item.view/view` to display a summary of the selected airdrop addresses.
- [x] Use component `quo.components.list-items.account.view` to display the list of possible airdrop addresses.
  - PR with the above 2 changes: https://github.com/status-im/status-mobile/pull/18189
- [ ] Answer questions in the `Questions` section below.
- [x] Add validations in status-go to fulfill the requirement that airdrop addresses should be a subset of the selected addresses to share.
      
**Note**: It is okay to focus on the functionality first and polish in future PRs.

### Questions

- Should airdrop addresses be a subset of the previous address selection?
  - Yes, see this [Figma node](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-293400&mode=design&t=UNMQM7sTa7XQyn15-0 ) from designers 
- What is the default airdrop account? First account in list?
- What should happen when deselecting the *selected airdrop account* from the list of *shared accounts*?
  - Does the airdrop address change to the next address in the selected list?
- Does the UI / backend prevent deselection of a selected airdrop account?
- What is the behaviour when the user selects an account derived from an imported private key, then joins the community with that private key account, then recovers their *Status Account* and doesn’t still have access to the private key account when the user attempts to access the community?

**Comment by ajayesivan** [comment]
https://github.com/status-im/status-mobile/pull/18189 only partially implemented this story.
