### ISSUE TITLE
Can't join an open community when node owner is offline on x86_64 Android 12

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18087]
As reported by @yevh-berdnyk 

### Problem

Steps:

- User A creates an open community and invites User B
- User A goes offline
- User B requests to join this community
- User A goes back online

Actual result:
  Community is shown as pending endlessly
  
Expected result:
User B has joined the community
[user_A_logcat.log.zip](https://github.com/status-im/status-mobile/files/13572071/user_A_logcat.log.zip)
[user_B_logcat.log.zip](https://github.com/status-im/status-mobile/files/13572073/user_B_logcat.log.zip)
[user_A_geth.log.zip](https://github.com/status-im/status-mobile/files/13572090/user_A_geth.log.zip)
[user_B_geth.log.zip](https://github.com/status-im/status-mobile/files/13572095/user_B_geth.log.zip)
Note: As we can create communities only on e2e mobile builds I need also a desktop build with this status-go version to check this functionality

Related to PR : https://github.com/status-im/status-mobile/pull/17773

**Comment by churik** [comment]
@siddarthkay @yevh-berdnyk https://github.com/status-im/status-mobile/issues/17678 - isn't is the same?

**Comment by cammellos** [comment]
@siddarthkay 
```
ERROR[12-05|04:05:07.134|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:162]                                          Error getting new mailserver             error="error during polling loop: recvfrom: socket operation on non-socket"
```

**Comment by yevh-berdnyk** [comment]
> @siddarthkay @yevh-berdnyk #17678 - isn't is the same?

Scenario is the same but this issue is only reproducible on x86_64 Android 12 emulators for now. So I'm not sure if the reason of these 2 issues is the same

**Comment by pavloburykh** [comment]
@siddarthkay @yevh-berdnyk closing this one as a duplicate of https://github.com/status-im/status-mobile/issues/17678

I have moved [logs](https://github.com/status-im/status-mobile/issues/17678#issuecomment-1842575614) and this [comment](https://github.com/status-im/status-mobile/issues/17678#issuecomment-1842576665) from this issue to the old one. Assigned you @siddarthkay to the old issue.
