### ISSUE TITLE
App gets stuck on syncing process screen when scanning  QR code via recovered profile with different passwords

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18113]
### Preconditions:
- `User A` is recovered on both `Device 1` and `Device 2 `devices
- During onboarding both users create different passwords

### Steps:
`Device 1` on the generates sync QR
`Device 2`  goes to "Syncing" -> [+] button -> tap 'Scan or enter sync code code' -> scan the QR code

### Actual result:
Upon scanning the QR code via a recovered profile with different passwords, the app gets stuck in the syncing devices process

https://github.com/status-im/status-mobile/assets/52490791/a8e4c1b9-7505-4d65-ad91-082f4bcc83db

### Expected result:
The devices should be synced. However the passwords should not be synced in such case.

Example:
 **Given** `UserA` is restored ion `Device 1` with the password "12345"
    **And** `UserA` is restored on `Device 2` with the password "99999999999"
    **When** `UserA` syncs `Device 2` with `Device 1`
    **Then** the devices should be synchronized
    But the passwords for `UserA` on `Device 1` ("12345") and `Device 2` ("99999999999") should not be synchronized

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13600847/Status-debug-logs.1.zip)

### ENV:
- Nightly 7 Dec 2023

**Comment by qfrank** [comment]
reproduced, will investigate deeper
