### ISSUE TITLE
Separate Integration tests into two separate make commands.

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18112]
Currently running `make test` runs a set of integration tests (covering RPC endpoints in Status Go) and a set of unit tests covering reframe subs and events etc.

We should split these into two separate jobs. This will make it clearer and also allow these tests to be run externally, there is currently some discussion about running these as part of Status Go pr's and this will be needed to make that happen.

This might involve extending the current CI job in our codebase to handle this change.

**Comment by J-Son89** [comment]
@ilmotta - I had this issue. Maybe we can link in pr - https://github.com/status-im/status-mobile/pull/18304

**Comment by ilmotta** [comment]
I missed this issue, thank you @J-Son89
