### ISSUE TITLE
Communities: Show relevant tokens in Addresses for Permissions screen

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#18126]
# Feature Issue

### User Story

- As a user joining a not token-gated community
- I want to be able see which tokens are relevant to which address
- So that I can make a more informed decision about which addresses to share.

<img src="https://github.com/status-im/status-mobile/assets/46027/e9563cae-ceef-46a4-b92d-b557d6653836" width="700" />

### Additional requirements

- When *Share all current and future addresses* is disabled, no tokens are shown.
- When *Share all current and future addresses* is enabled, we show for each address which tokens are available to fulfill the highest permission.

### Suggestions

- Consider moving more logic to status-go to keep the client thin, but double-check with desktop team if something is already available or in the making. For example, consider having one or more new status-go endpoints to do the heavy lifting.
- The status-go work can be done in parallel, even before issue https://github.com/status-im/status-mobile/issues/18012 is started/finished.

### Technical tasks

- [ ] https://github.com/status-im/status-mobile/pull/18224

### Resources

- Figma https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-289257&mode=design&t=AIWaz4wOOOzVbMok-0
- Account permissions component https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=31645-45625&mode=design&t=eJwmmYo456i73Z6s-0

**Comment by yqrashawn** [comment]
unassign myself since it's not really started and I'm taking time off.
