### ISSUE TITLE
Communities: Show highest permission role according to current address selection

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#18127]
# Feature Issue

### User Story

- As a user joining a token-gated community
- When I am selecting addresses for permissions
- I want to see the highest permission role I can join
- So that I can make a more informed decision about which addresses to share.

### Additional requirements

There are 4 places that would show the user's highest permission role:

<table>
  <thead>
    <tr>
      <th>Overview screen</th>
      <th>Request to join screen</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/a790ea09-4b17-45eb-bf83-b6d1a3f1717c" width="375" /></td>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/7c23ac13-6554-4a74-b6ff-85b32d1596d0" width="375" /></td>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Address selection screen</th>
      <th>All permissions drawer</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/ca8a4aa3-805d-4056-92ee-7d35743afb3b" width="375" /></td>
      <td><img src="https://github.com/status-im/status-mobile/assets/46027/0b1070fa-4895-471e-9a9e-0975d0295989" width="375" /></td>
    </tr>
  </tbody>
</table>

### Suggestions

- The highest permission role should ideally come from status-go. Double-check if this is not already implemented there. We may consider returning this piece of data in the same endpoint (may not exist now on 2023-12-08) that returns the data with all addresses and relevant tokens (implemented as part of https://github.com/status-im/status-mobile/issues/18126)

#### Action Point

Ask desktop team if this functionality (highest permission role should ideally come from status-go) has been implemented.

### Resources

- Figma https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-289598&mode=design&t=AIWaz4wOOOzVbMok-0

### Blocked by

- #18126
- status-go work, TODO add issue link once created.

**Comment by yqrashawn** [comment]
The fourth one in `All permissions drawer` is not implemented yet, waiting for #18638
