### ISSUE TITLE
Use text-combinations/page-top component in request to join sheet.

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#18125]
Replace[ custom page top](https://github.com/status-im/status-mobile/blob/de4e233884f938b0b4c7a5e127c9ffb2bfa9f6ca/src/status_im2/contexts/communities/actions/accounts_selection/view.cljs#L21-L33) implementation with [text-combinations/page-top](https://github.com/status-im/status-mobile/issues/18083) component once implemented.

**Comment by ajayesivan** [comment]
Blocked by https://github.com/status-im/status-mobile/issues/18083

**Comment by ilmotta** [comment]
@ajayesivan It seems like this issue was unblocked by the recently merged PR https://github.com/status-im/status-mobile/pull/18163, so I removed the `blocked` label. Can we move this issue to the TODO status?

**Comment by ajayesivan** [comment]
Hi @ilmotta, I have moved this issue to Todo.
