### ISSUE TITLE
On History tab dates are not sorted [1524]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1813]
### Description

*Type*: Bug

*Summary*: On History tab dates are not sorted - have Aug, Jul and Jun dates mixed

![image](https://user-images.githubusercontent.com/28752642/30274332-ad187e54-9705-11e7-80e6-1e82cd091e84.png)

*Operation system*: Android, iOS

**Comment by asemiankevich** [comment]
I can confirm its fine on Android now, @annadanchenko to confirm on iOS

**Comment by annadanchenko** [comment]
ok on iOS (real device iphone 6s, iOS 10.3.3)

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
