### ISSUE TITLE
Wrong buttons background

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#18145]
This is to track separately a sub item on [#16860](https://github.com/status-im/status-mobile/issues/16860) 
- Buttons background on `x` and `...` is wrong - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255)

**Comment by jo-mut** [comment]
@pavloburykh  This is feedback from 1.24 seems to have been fixed

- On scroll the correct background is applied on both button

https://github.com/status-im/status-mobile/assets/28704507/05743255-5af6-4e41-a6fe-2c880f5c3c9f

**Comment by pavloburykh** [comment]
@jo-mut all the issues from https://github.com/status-im/status-mobile/issues/16860 should pass design review and approval as those are the issues based on design review of the app UI. So please, request a review from Francesca on all the sub issues https://github.com/status-im/status-mobile/issues/18143 https://github.com/status-im/status-mobile/issues/18145 https://github.com/status-im/status-mobile/issues/18146 that you have recently created. Thank you!
