### ISSUE TITLE
Doubling category names

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#18143]
This is to track separately a sub item issue on [#16860](https://github.com/status-im/status-mobile/issues/16860) 
- Issue on  channel scroll with doubling category names - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510230062)

**Comment by jo-mut** [comment]
@pavloburykh  This seems to have been fix as the bug is not reproducible anymore

https://github.com/status-im/status-mobile/assets/28704507/56abe130-527b-4129-9b4b-ae0c4bc0a0c2

**Comment by pavloburykh** [comment]
@jo-mut confirming this is fixed. Thank you.
