### ISSUE TITLE
The watch-only page is selectable on the "send to" page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18144]
Follow up for https://github.com/status-im/status-mobile/pull/18071

### Description:
The 'send to' page is restricted to non-editable, watch-only accounts. However, a user can access it by selecting it using the select account icon (shown in the right upper corner

### Steps:
1. User adds watch-only account
2. User opens default account -> tap 'send' -> tap icon in right upper corner -> select watch only account

### Actual result:
The user lands on the 'send to' page of the watch-only account and can view accounts from the 'my account' tab to send assets.

https://github.com/status-im/status-mobile/assets/52490791/99cfee14-52ef-4aed-9636-49ce27e64277

### Expected result:
Potential solution:
The watch-only page is not included in the select accounts drawer
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-192739&mode=design&t=qKubUig7uuPjm0Bh-0
![image](https://github.com/status-im/status-mobile/assets/52490791/e119f2dc-fd03-4bcb-8f59-6e0dace6fae4)

**Comment by smohamedjavid** [comment]
Fixed in https://github.com/status-im/status-mobile/pull/18100
