### ISSUE TITLE
Wallet: Receive screen

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18152]
Implement the receive screen UI inside account screen, and sharing the address.

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=850-220368&mode=design&t=LiGka1ERPbcjgCSI-0

**Comment by smohamedjavid** [comment]
Duplicate of https://github.com/status-im/status-mobile/issues/17677
