### ISSUE TITLE
ETH address displayed in loading state after enabling Testnet Mode

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18158]
Introduced in https://github.com/status-im/status-mobile/pull/17879

### Steps:
1. Go to Advanced -> enable 'testnet mode'
2. Go to new wallet
3. Check eth address 

### Actual result:
Upon enabling "testnet mode" in the Advanced settings and subsequently accessing the new wallet, the ETH address is displayed but remains in a loading state.

https://github.com/status-im/status-mobile/assets/52490791/d2af033a-b4e7-47ef-87ee-8b35a5c7a754

### Expected result:
After enabling "testnet mode" and accessing the new wallet, the ETH address should be  accessible without being stuck in a loading state

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13648721/logs.zip)

**Comment by VolodLytvynenko** [comment]
@ajayesivan Please take a look, this might have been addressed after the rebase of this PR: [link](https://github.com/status-im/status-mobile/pull/17879). Encountered in the latest build of this PR

**Comment by ajayesivan** [comment]
@VolodLytvynenko, it seems that the issue is resolved in the latest develop branch. I think we can close this issue now.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko, it seems that the issue is resolved in the latest develop branch. I think we can close this issue now.

@ajayesivan Apologies. You are right
