### ISSUE TITLE
Empty chats list screen when navigating to chats tab after onboarding

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18161]
Unfortunately we have not reproduced the bug manually yet. 

At the same time it has been caught by e2e in different PRs. 

Here is example from this [PR](https://github.com/status-im/status-mobile/pull/18131)

You can see all the steps executed by Virtual device here https://app.eu-central-1.saucelabs.com/tests/a168c55e88e246639054758569923e4a?auth=fcae19d250dcdfa75d6eab0adc7e2994#0

**Steps:** 

1. User A starts onboarding https://app.eu-central-1.saucelabs.com/tests/a168c55e88e246639054758569923e4a?auth=fcae19d250dcdfa75d6eab0adc7e2994#2
2. After finishing onboarding User A goes to Profile - opens QR code https://app.eu-central-1.saucelabs.com/tests/a168c55e88e246639054758569923e4a?auth=fcae19d250dcdfa75d6eab0adc7e2994#44
3. User A taps system back button and closes QR code https://app.eu-central-1.saucelabs.com/tests/a168c55e88e246639054758569923e4a?auth=fcae19d250dcdfa75d6eab0adc7e2994#47
4. User A taps system back button and closes Profile screen. Now he is located at Communities tab https://app.eu-central-1.saucelabs.com/tests/a168c55e88e246639054758569923e4a?auth=fcae19d250dcdfa75d6eab0adc7e2994#53
5. User A taps Chats tab https://app.eu-central-1.saucelabs.com/tests/a168c55e88e246639054758569923e4a?auth=fcae19d250dcdfa75d6eab0adc7e2994#56

**Actual result:** User A is navigated to empty Chats list screen. 

[TestActivityMultipleDevicePR_geth1.log](https://github.com/status-im/status-mobile/files/13649980/TestActivityMultipleDevicePR_geth1.log)

<img width="465" alt="Test Results | Test Details | Sauce Labs 2023-12-12 17-29-15" src="https://github.com/status-im/status-mobile/assets/97245802/904fb33a-3741-4b39-ae5f-eaef772f2c6f">

### Additional Information

- Status version: nightly 
- Operating System: Android

**Comment by churik** [comment]
Haven't seen it in e2e for a while.
Reopen if still relevant. 

cc @yevh-berdnyk
