### ISSUE TITLE
Sometimes iOS crashes after logout 

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18162]
# Bug Report

## Problem 
[comment]: # (A problem description)
I am facing the random crashes on iOS. Not 10/10 but approximately 7/10.

#### Expected behavior
No crashes. User sees Onboarding screen with the ability to login with his user
![photo_2023-12-12_20-00-07](https://github.com/status-im/status-mobile/assets/147824399/862b6d71-e9c1-42ed-9d05-698deede5e60)

#### Actual behavior
App crashes right after user tap on Logout

https://github.com/status-im/status-mobile/assets/147824399/6d4f4c7d-0688-4d7c-8483-d5a4605bbf97

### Reproduction

1. User A (iOS): Create 5-6 new users
2. Go to Messages -> + -> Add a contact
3. Scan QR-code of User B (you should have an access to him)
4. As User B accept the request
5. As User A wait till new 1 to 1 with User B appear
6. As User A go to Profile-> Sign out-> Logout

### Additional Information

- Status version: nightly 11.12
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@mariia-skrypnyk still the case?

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk still the case?

No @churik.
Haven't seen it for ages.

**Comment by siddarthkay** [comment]
Freeing this one up so that others can pick this up

**Comment by churik** [comment]
closed at seems not reproducible anymore
