### ISSUE TITLE
Inaccurate calculation of available assets on Optimism and Arbitrum networks

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18160]
### Steps:
1. Recover the user with some assets within Optimism or Arbitrium network
2. Open the eth address where current assets are shown

### Actual result:
all assets available on Optimism and Arbitrum networks are shown with the balance of 0
![image](https://github.com/status-im/status-mobile/assets/52490791/4ac0451f-f672-4787-8b2c-9e266b5aed05)

### Expected result:
Assets available on Optimism and Arbitrum networks reflect the actual amounts held by the user within these networks.

Please, refer to me directly if you need seed phrase with assets available on Optimism or Arbitrium

**Comment by smohamedjavid** [comment]
Fix in https://github.com/status-im/status-mobile/pull/18078

**Comment by VolodLytvynenko** [comment]
@smohamedjavid thanks. 
Closed as dublicat
