### ISSUE TITLE
Share QR Code Gradient

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18168]
Share QR code component needs to have a gradient background color.

Designs: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1338-34510&mode=design&t=uZ8OClmzODbilGse-0

**Comment by smohamedjavid** [comment]
Duplicate of https://github.com/status-im/status-mobile/issues/17769

**Comment by Pau1fitz** [comment]
PR here - https://github.com/status-im/status-mobile/pull/18503

**Comment by J-Son89** [comment]
closing as this is a duplicate an already handled now
