### ISSUE TITLE
Chat follow-up design fixes

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#18179]
# Bug Report
Address the follow-up chat [design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=8065%3A58901&mode=design&t=gv0MnVcExvcN5Emp-1) issues and the [additional comment](https://github.com/status-im/status-mobile/pull/18059#pullrequestreview-1779868687) from #18059.

Parent issue for: 
1. #19013 
2. #19021 
3. https://github.com/status-im/status-mobile/issues/19053
4. https://github.com/status-im/status-mobile/issues/19058
5. https://github.com/status-im/status-mobile/issues/19095

**Comment by churik** [comment]
I believe can be closed, reopen if still relevant
