### ISSUE TITLE
Wallet: Scroll does not work on History tab [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1817]
### Description

*Type*: Bug

*Summary*: For the recovered account with a long list of transactions: list of transactions on History tab can't be scrolled. Nothing happens if scroll the list down.
Issue is only on Android (real Samsung Galaxy S6, S7 and Google Pixel XL)
Expected: list can be scrolled

#### Expected behavior
list can be scrolled
#### Actual behavior

If scroll down then nothing happens, so can't see the rest of the list that is not shown on the screen
### Reproduction

- Open Status
- Recover account with lots of transactions
- Open Wallet -> Transactions -> History
- Scroll transactions list 

### Additional Information
* Status version: develop  0.9.10-87-gf21f9ddf+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

**Comment by jeluard** [comment]
Fixed by #1807

**Comment by annadanchenko** [comment]
on build #5 of `Branch bug/#1801` same issue exists on same devices

**Comment by jeluard** [comment]
According to `nastya` this only happens when sync is in progress.

**Comment by yenda** [comment]
See also this report for when sync is in progress: https://github.com/status-im/status-react/issues/1902

(should be fixed with the update of react-native-swiper)

**Comment by annadanchenko** [comment]
Tested ok in develop  0.9.11d266 Will be in release 0.9.12
