### ISSUE TITLE
Add API keys for Sepolia & Rarible

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18188]
recently desktop client and status-go added a couple of API keys.
 
Chains Eth Sepolia and Arb Sepolia supported for Alchemy (https://github.com/status-im/status-go/pull/4332/files#diff-a000fb44bf83c0af6a0ae08c002167ca516892e992f4e528ed53236f51b7e717R176)

New provider Rarible (https://github.com/status-im/status-go/pull/4376/files#diff-10ff00a15ef58da7485fedeca3906c73cb236fde4b143a9d61601c63cbf1ffe8R535)

Please get in touch with Infra ( @yakimant ) as jakubgs is on break until early 2024.

**Comment by J-Son89** [comment]
@smohamedjavid is this a duplicate?

**Comment by smohamedjavid** [comment]
We can use this issue to track the Infra progress. 

The keys are added in the Infra but the build currently fails 
with error `Could not find credentials entry with ID 'alchemy-arbitrum-sepolia-devel'`
https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fios/detail/PR-18519/7/pipeline/

**Comment by apentori** [comment]
Pipeline fixed : https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fios/detail/PR-18519/8/pipeline/32

**Comment by smohamedjavid** [comment]
Thank you @apentori! 🚀

**Comment by vkjr** [comment]
"@smohamedjavid assigned apentori and unassigned @vkjr yesterday"
That was a backstab :) 😈

**Comment by smohamedjavid** [comment]
@vkjr - Apologies 🙏 . That was not intentional.

This issue mainly deals with adding the keys in Infra which Alex did in the `status-jenkins-lib` repo. I assigned it to him. Additionally, keeping this issue open until #18519 is tested and merged.
