### ISSUE TITLE
Remove old tailrecursion/cljs-priority-map dependency

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#1818]
### User Story

As a developer, I don't want to depend on unmaintained dependency. `tailrecursion/cljs-priority-map` is used in 2 functions of status codebase, replace it with local code.
Also `tailrecursion/cljs-priority-map` prevent us from upgrading to latest cljs compiler.

*Type*: Bug

**Comment by oskarth** [comment]
Accidentally merged into develop before QA. Small fix/refactor, so let's hope there are no regressions.
