### ISSUE TITLE
Community invite link does not receive update when it has been already opened once 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#18184]
# Bug Report

## Problem 
Detested on https://github.com/status-im/status-mobile/pull/18170#issuecomment-1854227498, but the issue is presented on current `develop` as well.
Basically, if the admin changes any info (name / description / permissions) the info is not updated if you reopen the link.

**The issue is not reproducible on desktop**

**Steps:**
1) create  community on desktop 
2) send a link to the community to mobile, open it
3) add a permission (i.e. 10 SNT to be a member).
3) open it on mobile

| **Expected result:** | **Actual result:** |
|-|-|
| <img height="640" alt="IMAGE 2023-12-13 16:58:07" src="https://github.com/status-im/status-mobile/assets/4557972/1cc10762-56b4-4956-bc6f-68d49630aee8"> | <img height="640" alt="MAGE 2023-12-13 16:58:40" src="https://github.com/status-im/status-mobile/assets/4557972/2e2c1417-c848-402f-98cf-b336ba88d6a0"> |

**OS:** IOS, Android
### Additional Information

- Status version: nightly  14/12/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cc @Samyoul @codemaster115

**Comment by smohamedjavid** [comment]
This could be fixed in https://github.com/status-im/status-mobile/pull/18070

**Comment by ibrkhalil** [comment]
Status-desktop doesn't have latest status-go changes, They need to be there so that this can be worked on.

**Comment by yqrashawn** [comment]
this should be fixed now 
it's ISSUE2 in this PR https://github.com/status-im/status-mobile/pull/18070#issuecomment-1862358520
and the community data do get updated  after some time https://github.com/status-im/status-mobile/pull/18070#issuecomment-1866598031

**Comment by pavloburykh** [comment]
closing as issue is not reproducible anymore.
