### ISSUE TITLE
Push notifications: use status-go PN branch and use new interface

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1821]
### User Story

As a user, I want my message to a contact to trigger a push notification for them.

### Description

*Type*: Feature

*Summary*: Use status-go feature/notifications-refactor#249 branch and trigger push notifications from device to device B via intermediary wnode and Firebase.

### Details

The scope of this issue is uncertain because the interface of what we are consuming is uncertain. This issue description will this be updated as more clarity is gained. This is the state of things on September 12th.

status-go has written a notification service that is currently in a branch. More details will be available here: https://github.com/status-im/status-go/pull/266

To get end to end push notifications we need to include this branch of status-go and run it on two devices that has push notification capabilities (say, Genymotion and real iOS device). In addition, we need an intermediary wnode. This will be setup as part of status-cluster, which is something status-go is working on here: https://github.com/status-im/status-go/issues/307

Additionally, we are currently using two different Firebase setup (different accounts, one device and one topic (?) based). This will be dealt with but possibly in another issue.

- [ ] compile with new status-go branch
- [ ] ensure communication with device A to wnode works from status-react
- [ ] ...
- [ ] send message on device A and trigger notification on device B

**Comment by pedropombeiro** [comment]
Closing as we since created more fleshed out issues in the scope of PN v2
