### ISSUE TITLE
[Android] Wallet home screen overlaps status bar

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18233]
### Steps:
1. Access the wallet section within the application.
2. Observe the positioning of the status bar.

### Actual result:
The status bar is shifted to the top and overlaps the system top bar (battery, time)

https://github.com/status-im/status-mobile/assets/52490791/2f8d242f-44be-4202-9448-a4149f38994c

### Expected result:
The status bar is aligned and positioned on the same position as shown within 'chat preview' screen

### ENV:
- Nightly [19 Dec 2023]

**Comment by smohamedjavid** [comment]
Fixed in https://github.com/status-im/status-mobile/pull/18247.
