### ISSUE TITLE
[IOS] Partial visibility of quoted text in composer upon chat reopening

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18238]
### Steps:
1. Send a message to any chat that includes text enclosed in quotes  (example of the text [text.txt](https://github.com/status-im/status-mobile/files/13718018/text.txt))
2. Long tap on the message and select the 'edit message' option without sending the edited message.
3. Close the chat and reopen it.

### Actual result:
Upon reopening the chat, only the text enclosed in quotes is displayed. The text out of quotes is not visible in the composer.

https://github.com/status-im/status-mobile/assets/52490791/0b73a1f6-d656-450c-97bb-acf97dd49984

### Expected result:
The text is fully visible in the composer

**Comment by churik** [comment]
Reopen if still relevant.  Not reproducible anymore on nightly 21/06/24 (IPhone 14, Google Pixel7)
