### ISSUE TITLE
Delayed display of top bar in chat after sending messages

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18240]
Follow up for https://github.com/status-im/status-mobile/pull/18055

### Steps:
1. Open an empty chat. (or clear the existing one)
2. Send messages sequentially, one by one.
3. Observe the behavior of the top bar.
4. Scroll up within the chat.
5. While at the top, send an additional message.

### Actual result:
The top bar does not appear promptly after sending a message, particularly when the user is positioned at the top of the chat,

On IOS

https://github.com/status-im/status-mobile/assets/52490791/78071f42-8733-4ac4-bf7f-00fab4132a89

On Android

https://github.com/status-im/status-mobile/assets/52490791/f7aac4c2-4d0c-4721-8360-b6abe6d1d225

### Expected result:
The top bar should be shown when the 1-1 avatar is hidden

How it worked on the nightly [18 Dec 2023]

https://github.com/status-im/status-mobile/assets/52490791/3d59d5e0-b02d-4fb7-88d7-6a76e053ce96

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by churik** [comment]
Check also this case with long message (the screenshot is from 1.26): 
![IMAGE 2023-12-22 12:24:37](https://github.com/status-im/status-mobile/assets/4557972/cc1e6098-d7d2-4f44-8f9c-20e0356ed0dd)
