### ISSUE TITLE
[Android] The parallax image is not shown on the 'Enable notifications' screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18250]
### Steps:
1. Go to "Enable notifications" during onboarding using Android device

### Actual result:
The parallax image is not shown on the 'Enable notifications' screen
![image](https://github.com/status-im/status-mobile/assets/52490791/4f8a55b3-f82e-4164-94e6-3852492ce5c1)

### Expected result:
![image](https://github.com/status-im/status-mobile/assets/52490791/75acd88f-fa3e-4397-8b6d-fdb4adc8d416)

### ENV:
- Nightly [20 Dec 2023]

**Comment by ibrkhalil** [comment]
I don't think it's optimized/built for Android yet, Because we are [hardcoding a whitelist](https://github.com/status-im/status-mobile/blob/49c6a44824c0d2d4318f0fda3bd7841bd09569fb/src/status_im/common/parallax/whitelist.cljs#L9) of devices to show the video for
![Screenshot_20231223_122121](https://github.com/status-im/status-mobile/assets/33176106/2c100c72-dc1a-4010-bd2c-c719d04310f5)

**Comment by pavloburykh** [comment]
> I don't think it's optimized/built for Android yet, Because we are [hardcoding a whitelist](https://github.com/status-im/status-mobile/blob/49c6a44824c0d2d4318f0fda3bd7841bd09569fb/src/status_im/common/parallax/whitelist.cljs#L9) of devices to show the video for 

@ibrkhalil but for those devices which are not is the list we used to show static image before. In my case both Android and IOS devices are not in white list and static image is not displayed. 

Also, regarding parallax, we used to show it on some Android devices as well, for example on Pixel 7a (correct me if I am wrong @VolodLytvynenko). 

So, we have 2 issues:

1. Parallex is not shown for Android devices on which we used to show it before. 
2. The fallback static images are lost for those devices (IOS and Android) which are not in the whitelist.

**Comment by ibrkhalil** [comment]
> > I don't think it's optimized/built for Android yet, Because we are [hardcoding a whitelist](https://github.com/status-im/status-mobile/blob/49c6a44824c0d2d4318f0fda3bd7841bd09569fb/src/status_im/common/parallax/whitelist.cljs#L9) of devices to show the video for
> 
> @ibrkhalil but for those devices which are not is the list we used to show static image before. In my case both Android and IOS devices are not in white list and static image is not displayed.
> 
> Also, regarding parallax, we used to show it on some Android devices as well, for example on Pixel 7a (correct me if I am wrong @VolodLytvynenko).
> 
> So, we have 2 issues:
> 
> 1. Parallex is not shown for Android devices on which we used to show it before.
> 2. The fallback static images are lost for those devices (IOS and Android) which are not in the whitelist.

In that case, I'll take a closer look.

**Comment by VolodLytvynenko** [comment]
> Also, regarding parallax, we used to show it on some Android devices as well, for example on Pixel 7a (correct me if I am wrong @VolodLytvynenko).

@pavloburykh ,  Correct. In the nightly build [15 Dec 2023], before the creation of this issue, the parallax was present on Pixel. I didn't investigate after which PR it disappeared
