### ISSUE TITLE
Wallet: Prepare events to send a collectible with Status Go Integration 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18260]
As a User I want to be able to send a collectible from my status wallet:

The Wallet flows require sending a collectible. Implement the re-frame event to dispatch this collectible using the RPC endpoint:
"wallet_getSuggestedRoutes" 

Same endpoint used here as sending a token:
https://github.com/status-im/status-mobile/pull/18242/files#diff-089fb8d72eefa455e3dc6437b0bc11c3ca3cc0fb4063e20f129b09929aeae3a9

and additionally test out:
"wallet_createMultiTransaction" also used there.

Check the params according to status go. Most notably transfer type has to be to send a collectible.

Related designs:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-505518&mode=design&t=g48GU4TLWabatwfK-4

**Comment by briansztamfater** [comment]
Closing as implemented in https://github.com/status-im/status-mobile/pull/18473
Will open new issues if needed when properly testing is done
