### ISSUE TITLE
Offline fetching and resending messages is not working from mobile devices on `shards.test`

### ISSUE THREAD

**Issue by churik** [status-im/status-react#18272]
# Bug Report

## Problem 
The bug is not reproducible on the current `develop` branch and was not reproducible during testing https://github.com/status-im/status-mobile/pull/18115

#### Expected behavior
- can fetch messages from offline (4,5,6) + new channel
- can resend messages while sending from offline after getting back online (1,2,3)

#### Actual behavior
- no messages  and community updates are received while getting back from offline
- messages are stuck in "Sending" forever

### Reproduction
As a desktop: create community
1. Mobile: join community 
2. Mobile: go offline 
3. Mobile: post messages 1,2,3
4. Desktop: post messages 4,5,6 + add channel2 
5. Mobile: go online 

### Additional Information

- Status version: RC 17  
- Operating System: Android, iOS

https://github.com/status-im/status-mobile/assets/4557972/ed25a1dd-22bf-4239-8d43-426a5f673be3

### Logs
Desktop ([build]( https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F0.15.x/37/ )): [geth.log](https://github.com/status-im/status-mobile/files/13744043/geth.log)
Mobile ([build]( https://ci.infra.status.im/job/status-mobile/job/release/job/release%2F1.26.x/17/ )): [logs (78).zip](https://github.com/status-im/status-mobile/files/13744036/logs.78.zip)

**Comment by churik** [comment]
cc @anastasiyaig @richard-ramos @cammellos

**Comment by VolodLytvynenko** [comment]
I confirm everything that @churik  described [here](https://github.com/status-im/status-mobile/issues/18272#issue-2052727448) 
Tested in case Mobile -> Mobile

**Reproduction**
As a desktop: create community share to `Mobile 1:` and `Mobile 2:`

`Mobile 1:` join the community and send message 1
`Mobile 2:`join community (Now message 1 is not visible)
`Mobile 2:` go offline
`Mobile 1:` send 3-5 messages
`Mobile 2:` go online

### Actual result:
no messages and community updates are received while getting back from offline

https://github.com/status-im/status-mobile/assets/52490791/b3127614-f3b8-4e18-85f2-b2137b1fa500

### Logs:
-  **Mobile 2:** Real device. Device Pixel 7a.  (right on the record)    [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13744329/Status-debug-logs.zip)

- **Mobile 1:** Android studio. Pixel XL API 33 (left on the record)  [android_logcat4.txt](https://github.com/status-im/status-mobile/files/13744315/android_logcat4.1.txt)

**Comment by richard-ramos** [comment]
I see a lot of `cannot do on demand discovery for non-waku protocol` errors that were fixed in go-waku in https://github.com/waku-org/go-waku/pull/951. I'll update the status-go branch with that go-waku version and this mobile PR

**Comment by richard-ramos** [comment]
Hm, the `test-shard-test` branch of status-go does contain the changes, yet the feature/peersyncing does not. I ended up updating go-waku on that branch. So we'd need to update the mobile branch to use this https://github.com/status-im/status-go/commit/c3739edc0ca3bfb1277def0c824244564f3c6bd7

But IMO the way to go should be to create a branch in status-go that uses `test-shard-test` as base, and include the commits from `feature/peersyncing`.

**Comment by richard-ramos** [comment]
I'm also not sure which branch is being used in status-mobile so I can update its status-go version

**Comment by churik** [comment]
Bug was introduced due to invalid rebase, fixed in build 18
