### ISSUE TITLE
Use Jenkins DigitalOcean slave to build status-react Android

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1828]
### User Story

As a developer/QA, I want builds to finish faster to speed up feedback cycle. By having Android builds split from iOS they would finish faster (slack notification/artifact) and also cause less strain on expensive xcloud instances.

### Description

*Type*: Feature (tooling)

*Summary*: Use Jenkins AWS slave instance https://github.com/status-im/status-go/issues/309 to separate build step of Android and iOS. We can do this concurrently with current Jenkins build.

Waiting for https://github.com/status-im/status-go/issues/309

**Comment by antdanchenko** [comment]
Please, get AWS instance with defined location in USA. The location will make e2e tests twice faster and will remove Internal Server errors.

**Comment by oskarth** [comment]
@antdanchenko Can you please put this comment in the appropriate issue? https://github.com/status-im/status-go/issues/309 This is issue is about consuming the AWS instance status-go will create.

**Comment by oskarth** [comment]
We now have a linux node up, need to set up Jenkins stuff there though. Then:

`node ('linux1') { <android specific stuff> }`
`node ('macos') { <macos specific stuff> }`

Naive test currently fails with: `java.nio.file.NoSuchFileException: /home/jenkins/env.groovy`
https://jenkins.status.im/job/status-react/job/pull%20requests/job/bug%252Fjenkins-test/7/console

**Comment by yenda** [comment]
@jakubgs can we close this now that the CI has been completely changed ?

**Comment by jakubgs** [comment]
I think we can.
