### ISSUE TITLE
Background color of the top bar is incorrect on History transactions screen on iOS [1524]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1829]
### Description

*Type*: Bug

*Summary*: 

#### Expected behavior
Please check mocks for iOS

![image](https://user-images.githubusercontent.com/28752642/30321331-4e220668-97be-11e7-9d8d-ca8ed5e158ed.png)

#### Actual behavior

Background color of the top bar (battery, carrier…) is currently black with white text. 

![image](https://user-images.githubusercontent.com/28752642/30321218-f893bc46-97bd-11e7-9fd1-953864386e64.png)

### Reproduction

- Open Status
- Go to new wallet tab -> Transactions
- Pay attention to the top bar

### Additional Information
* Status version: 0.9.11d87
* Operating System: iOS

**Comment by flexsurfer** [comment]
fixed here https://github.com/status-im/status-react/pull/1859

**Comment by annadanchenko** [comment]
tested ok on iOS in epic/wallet branch
