### ISSUE TITLE
"Oops, wrong password" when joining a community after creating a new wallet account

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18308]
# Bug Report

## Problem

You cannot join any community after creating a new wallet account - a valid password is no longer verified.

### Reproduction

1. Create a profile
2. Create a new wallet account
3. Request to join a community > Enter your password

#### Expected behavior
Can send a request to join 

#### Actual behavior
`Oops wrong password` when entering your correct password

https://github.com/status-im/status-mobile/assets/67952253/4ad6b6db-3111-4409-a2a5-4a10b37fc202

### Additional Information

- Status version: nightly 27/12
- Operating System: Android, iOS

### Logs

[geth.log](https://github.com/status-im/status-mobile/files/13779502/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/13779503/Status.log)

**Comment by pavloburykh** [comment]
@ajayesivan Are we okay with closing the issue? As it turned out that it is reproducible only on broken accounts, created before Andrea's and Jamie's fixes. Or you still have some concerns about that?

**Comment by ajayesivan** [comment]
Yes, we can close this. Thank you @pavloburykh
