### ISSUE TITLE
Wallet: Account origin info bottom sheet

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18317]
Implement the account origin bottom sheet to display info on the origin and the derivation path.

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-134201&mode=design&t=w6wYfw4lpyRMDKbm-4

Copy should be:

Account origin
To create a new account, you can generate a key pair in the app or import an existing account.

Origin
Origin is where your key pair (your private and public key) comes from. You can generate a new key pair or import an existing private key. 

Derivation path
Derivation paths are the routes your Status Wallet uses to generate addresses from your private key.

Link: https://status.app/help/wallet/create-wallet-accounts

**Comment by OmarBasem** [comment]
Blocked: the text currently used is mock text

**Comment by Rende11** [comment]
I would like to implement it
