### ISSUE TITLE
Upgrade nixpkgs to release `23.11`

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18311]
A `nixpkgs` upgrade is available `23.11` -> https://github.com/NixOS/nixpkgs/releases/tag/23.11

This solves our requirement to upgrade `golang` beyond `1.20` 

changes form our existing 23.05 -> https://github.com/NixOS/nixpkgs/compare/23.05...23.11

**Comment by siddarthkay** [comment]
first challenge I faced when building with 23.11 is with `zprint` **1.2.8** 
```
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /private/tmp/nix-build-zprint-1.2.8.drv-0/zprint (executable)
========================================================================================================================
Finished generating 'zprint' in 5m 51s.
buildPhase completed in 5 minutes 54 seconds
installing
post-installation fixup
checking for references to /private/tmp/nix-build-zprint-1.2.8.drv-0/ in /
nix/store/32l504qgj32mh1yxwmgs9qsz2wdykvvl-zprint-1.2.8...
patching script interpreter paths in /nix/store/32l504qgj32mh1yxwmgs9qsz2wdykvvl-zprint-1.2.8
stripping (with command strip and flags -S) in  
/nix/store/32l504qgj32mh1yxwmgs9qsz2wdykvvl-zprint-1.2.8/bin
error: output '/nix/store/32l504qgj32mh1yxwmgs9qsz2wdykvvl-zprint-1.2.8' is not allowed to refer 
to the following paths:
/nix/store/gy4xl9nhyyc17fsxjqnq4inyncwbqcv8-graalvm-ce-21.0.1
error: build of '/nix/store/1gng5my9ipv4yghm4y16chna3bz9chkf-zprint-1.2.8.drv',
'/nix/store/ngkg5qa2702a4vcc9axj606gww190p8m-clj-kondo-2023.09.07.drv',
'/nix/store/zrbjql28c6rsiv2z8jsba3l07pm9a8gb-clojure-lsp-2023.08.06-00.28.06.drv' 
 failed
```

maybe @yqrashawn can help?

**Comment by siddarthkay** [comment]
This issue is potentially related to java being bumped up to 21 in this nixpkgs release...

**Comment by yqrashawn** [comment]
It's fixed here https://github.com/NixOS/nixpkgs/pull/269479
But not in 23.1.1
Can we use master? Or it's too unstable?

**Comment by siddarthkay** [comment]
Nice, thanks for the reference @yqrashawn : I too was trying to remove those references manually.
But I can try using the commit mentioned in this PR :)

**Comment by siddarthkay** [comment]
That error is fixed now the next challenge is building go-mobile for android
stacktrace below
```
error: builder for '/nix/store/hmv9pf8szjdpw34nhybim221zrr0vvia-status-go-0.171.39-debfe1c-android.drv' 
failed with exit code 1;
       last 10 log lines:
       > building
       >
       > Building status-go for: android/arm64
       > /nix/store/cpm4xfas3c0s5zl0k70wsybl4a39llz7-gomobile-unstable-2022-05-18/bin/gomobile: 
       /nix/store/cpm4xfas3c0s5zl0k70wsybl4a39llz7-gomobile-unstable-2022-05-18/bin/gobind -lang=go,java 
       -outdir=/private/tmp/nix-build-status-go-0.171.39-debfe1c-android.drv-0/gomobile-work -tags=
       gowaku_skip_migrations,gowaku_no_rln github.com/status-im/status-go/mobile failed: exit status 1
       > unable to import bind/java: [-: # golang.org/x/mobile/bind/java
       > go/src/golang.org/x/mobile/bind/java/context_android.go:9:10: fatal error: 'jni.h' file not found
       > #include <jni.h>
       >          ^~~~~~~
       > 1 error generated.]
       >
       For full logs, run 
       'nix log /nix/store/hmv9pf8szjdpw34nhybim221zrr0vvia-status-go-0.171.39-debfe1c-android.drv'.
error: build of '/nix/store/9d6c6zba0dwva2r6xj86zc4hlzxy3zcf-watchman-4.9.0.drv',
 '/nix/store/hmv9pf8szjdpw34nhybim221zrr0vvia-status-go-0.171.39-debfe1c-android.drv', 
 '/nix/store/nam12rxlzaiwgnkr2cr55cg1lw73khsj-status-mobile-node-deps-1.25.0-patched.drv' failed
make: *** [run-android] Error 1
```

**Comment by jakubgs** [comment]
>Can we use master? Or it's too unstable?

@yqrashawn I would avoid using `master` as indeed it is unstable. Either we should wait for the fix to go into `nixos-23.11` or we have to fork `nixos-23.11` and apply the fix there.

**Comment by siddarthkay** [comment]
> That error is fixed now the next challenge is building go-mobile for android stacktrace below
> 
> ```
> error: builder for '/nix/store/hmv9pf8szjdpw34nhybim221zrr0vvia-status-go-0.171.39-debfe1c-android.drv' 
> failed with exit code 1;
>        last 10 log lines:
>        > building
>        >
>        > Building status-go for: android/arm64
>        > /nix/store/cpm4xfas3c0s5zl0k70wsybl4a39llz7-gomobile-unstable-2022-05-18/bin/gomobile: 
>        /nix/store/cpm4xfas3c0s5zl0k70wsybl4a39llz7-gomobile-unstable-2022-05-18/bin/gobind -lang=go,java 
>        -outdir=/private/tmp/nix-build-status-go-0.171.39-debfe1c-android.drv-0/gomobile-work -tags=
>        gowaku_skip_migrations,gowaku_no_rln github.com/status-im/status-go/mobile failed: exit status 1
>        > unable to import bind/java: [-: # golang.org/x/mobile/bind/java
>        > go/src/golang.org/x/mobile/bind/java/context_android.go:9:10: fatal error: 'jni.h' file not found
>        > #include <jni.h>
>        >          ^~~~~~~
>        > 1 error generated.]
>        >
>        For full logs, run 
>        'nix log /nix/store/hmv9pf8szjdpw34nhybim221zrr0vvia-status-go-0.171.39-debfe1c-android.drv'.
> error: build of '/nix/store/9d6c6zba0dwva2r6xj86zc4hlzxy3zcf-watchman-4.9.0.drv',
>  '/nix/store/hmv9pf8szjdpw34nhybim221zrr0vvia-status-go-0.171.39-debfe1c-android.drv', 
>  '/nix/store/nam12rxlzaiwgnkr2cr55cg1lw73khsj-status-mobile-node-deps-1.25.0-patched.drv' failed
> make: *** [run-android] Error 1
> ```

This was an issue with `gomobile` and was fixed by upgrading go to `1.20` and using this commit as a patch : https://github.com/golang/mobile/commit/406ed3a7b8e44dc32844953647b49696d8847d51

**Comment by siddarthkay** [comment]
new issues yay : 

iOS build fails on CI with : 

```
[2024-03-22T16:10:36.477Z] [StatusImPR] Processing Info.plist
[2024-03-22T16:10:36.477Z] [StatusImPR] Running script Bundle React Native code and images
[2024-03-22T16:10:36.477Z] ** ARCHIVE FAILED **
[2024-03-22T16:10:36.477Z] 
[2024-03-22T16:10:36.477Z] 
[2024-03-22T16:10:36.477Z] The following build commands failed:
[2024-03-22T16:10:36.478Z] 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/jenkins/
Library/Developer/Xcode/DerivedData/StatusIm-duvifmrkbphbxndmvvwbjhurkcbx/Build/
Intermediates.noindex/ArchiveIntermediates/StatusImPR/IntermediateBuildFilesPath/StatusIm.build/
Release-iphoneos/StatusImPR.build/Script-3AAD2AD524A3A60E0075D594.sh 
(in target 'StatusImPR' from project 'StatusIm')
[2024-03-22T16:10:36.478Z] (1 failure)
[2024-03-22T16:10:36.478Z] [StatusImPR] Generating Status\ PR.app.dSYM
[2024-03-22T16:10:36.478Z] [18:10:35]: Exit status: 65
```

**Comment by siddarthkay** [comment]
second issue locally when running `make shell TARGET=ios` is : 

```
error: builder for '/nix/store/y9mrh8y22ggnj1j7l1pxnq1cxamrbwpq-xcode-wrapper-plus-15.0.drv' 
failed with exit code 141
```

and when trying to inspect the derivation i get : 
```
[nix-shell:/nix/store]$ nix derivation show yng7zcgghnwyharghq09rncg74hwi2yd-xcode-wrapper-15.0.drv
path '/nix/store/yng7zcgghnwyharghq09rncg74hwi2yd-xcode-wrapper-15.0.drv' 
does not contain a 'flake.nix', searching up
error: could not find a flake.nix file
```
