### ISSUE TITLE
[Android] User doesn't see Request to join community screen after tap on invitation link

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18315]
# Bug Report

## Problem 
[comment]: # (A problem description)
User doesn't see Request to join community screen after tapping on the invitation link.

Reproduced randomly in all PRs stating from 28.12.23 (before it was working with 5 sec of waiting) 

#### Expected behaviour
User sees Request to join community screen after tap on invitation link (pause between screens can be but not more than 2-4 seconds)

https://github.com/status-im/status-mobile/assets/147824399/3b8f95fa-b4b9-44f3-a149-093d653afff2

#### Actual behavior
User sees this screen (1 minute and more)  and doesn't move to the Request to join community screen 
![photo_2023-12-28_15-27-45](https://github.com/status-im/status-mobile/assets/147824399/ff22cb16-99c1-4e67-8db5-05370e3960b1)

**Precondition**
PR build installed from this PR https://github.com/status-im/status-mobile/pull/17839

### Reproduction

1. User A (desktop) adds User B as a member to his community
2. User B opens 1 to 1 chat with User A and taps on invitation link

### Additional Information

- Status version: PR build from here https://github.com/status-im/status-mobile/pull/17839
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

Log from failed test (last 20 seconds matters):

[TestCommunityMultipleDeviceMerged_geth1 (5).log](https://github.com/status-im/status-mobile/files/13787473/TestCommunityMultipleDeviceMerged_geth1.5.log)

**Comment by churik** [comment]
Added wait for 120 sec, let's see if it helps the situation - like temp sulution for 120 sec
https://github.com/status-im/status-mobile/pull/18316

**Comment by churik** [comment]
Important considerations:
- what is the expected waiting time for "Request to join community" button to appear? 
- what should be shown while user is waiting? 
- why the time for this button to appear has been increased?

cc @pavloburykh @cammellos @yevh-berdnyk 

After fix the changes with waiting should be reverted.

**Comment by churik** [comment]
Ok, seems the "temp fix" is not working - nothing is changed in 120 sec
The user is tapping on the link and the info is not fetching

Video:  from here 2 minutes - https://app.eu-central-1.saucelabs.com/tests/863dd66e873f483e97064ec393985ce1?auth=30a0167ad98f8e2e8ac206b82c258a99#86 

Log: [TestCommunityMultipleDeviceMerged_geth1 (6).log](https://github.com/status-im/status-mobile/files/13792470/TestCommunityMultipleDeviceMerged_geth1.6.log)

**Comment by ibrkhalil** [comment]
@pavloburykh Should we close this?

**Comment by pavloburykh** [comment]
> @pavloburykh Should we close this?

sure. Closing the issue as fixed on the fleet side.
