### ISSUE TITLE
Wallet - Fix Navigation after Creating an account or watch only account

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18323]
After creating an account the current navigation approach is to navigate back and then forwards to the new account page. There is a better approach using navigate-within-stack.
e.g
` :fx [[:navigate-to-within-stack [:wallet-account-page stack-id]]`

Align with @briansztamfater on this if there's any doubts 👍 

see: https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/events.cljs#L34

**Comment by briansztamfater** [comment]
@J-Son89 I remember I had an old branch with the fix, I rebased it and created the PR here: #18324

Let me know if I missed something else here
