### ISSUE TITLE
Can't view pdf in browser

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1833]
### Description

*Type*: Bug

*Summary*: As a user I want to be able to read pdfs within browser as well as images and other content

#### Expected behavior
PDF is opened correctly (probably in new tab), but anyway user should be able to read the content easily

#### Actual behavior
Pdf content is shown in wrong encoding

![image](https://user-images.githubusercontent.com/28752642/30325869-1c40cf42-97cf-11e7-9323-e3e294151f76.png)

### Reproduction

- Open Status
- Open browser and go to  the following URL https://dentacoin.com/white-paper/Whitepaper-en.pdf

### Additional Information

* Status version: last seen in 0.9.10-77-gd5981c65+ (1634) 
* Operating System: Android, iOS

**Comment by jeluard** [comment]
@asemiankevich Is this still an issue? (cc @Serhy )

**Comment by Serhy** [comment]
Indeed, @jeluard it's not an not an issue anymore, however now `.pdf` files are just blank page on Android app browser.  E.g. try to open http://swap.tech/airswap-terms-of-use.pdf in Android webview.
It's a separate issue though anyway I described in #5650 issue

<blockquote></blockquote>
