### ISSUE TITLE
Upgrade Clojurescript to latest

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1837]
As a developer, I want to run recent version of Clojurescript so we can use fixes and enhancements.

We are currently at `[org.clojure/clojurescript "1.9.671"]` which was released June 30th. Latest version is `1.9.908`. We are no longer blocked by `cljs-priority-map` with https://github.com/status-im/status-react/pull/1836. There might be other unknown blockers though, and as far as I know we don't currently have any _specific_ reasons to upgrade, so this isn't a priority task.

jeluard Sep 12: I believe it might be required if we move to latest reagent version (currently alpha)

**Comment by yenda** [comment]
We currently use 1.10.238
