### ISSUE TITLE
Wallet: token value is displayed incorrectly inside the wallet account if the balance is zero

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18394]
# Bug Report

## Problem 

Leftover of https://github.com/status-im/status-mobile/pull/18267
cc @OmarBasem take a look at this issue please

<img width="310" alt="Screenshot 2024-01-04 at 15 19 02" src="https://github.com/status-im/status-mobile/assets/67952253/2f3d738e-404c-462b-922e-b3a2200c7a49">

#### Expected behavior
0 SNT - $0
0 DAI - $0
etc

#### Actual behavior
<0 SNT - <$0.01
<0.01 DAI - <$0.01
etc

### Reproduction

1. Create a brand new Status profile
2. Open wallet
3. Open the wallet account

### Additional Information

- Status version: nightly 4/01
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mmilad75** [comment]
I just checked with a brand new account and it was fine. Can you please check again on your side? @qoqobolo 

<img width="488" alt="Screenshot 2024-01-11 at 18 44 40" src="https://github.com/status-im/status-mobile/assets/55688834/94dec941-5626-4cd1-be8f-110bbb427a85">

**Comment by qoqobolo** [comment]
Hey @mmilad75 , thanks for checking! 
This is indeed no longer reproducible, so closing the issue.
