### ISSUE TITLE
[Android] Profile avatar quickly moves to the left while user closes keyboard

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18409]
# Bug Report

## Problem 
[comment]: # (A problem description)
Animation of Profile's avatar works incorrectly while user closes keyboard: it quickly moves to the left

#### Expected behavior
Profile's avatar shouldn't move to any side

#### Actual behavior
Profile avatar quickly moves to the left while user closes keyboard

### Reproduction

1. Login to app
2. Open 1 to 1 chat
3. Tap on text field and close the keyboard
I've made video from my device and from saucelabs real device:

https://github.com/status-im/status-mobile/assets/147824399/917af0f6-383e-4c83-aabd-fe178a073e86

https://github.com/status-im/status-mobile/assets/147824399/d0d0f829-82d4-4888-a9a8-c646d17d481d

](url)

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
depends on https://github.com/status-im/status-mobile/issues/18467

**Comment by churik** [comment]
Don't think it makes sense to have it open, since we  are simplifying the animations across the app. 
Also I was unable to reproduce it as described in the issue on nightly 21/06/24


 Reopen if still relevant.
