### ISSUE TITLE
Migrate all list to components.list

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#1840]
### User Story

As a developer, I want to rely on a single efficient list implementation

### Description

Migrate all code using `react/list` to `components.list/flat-list` or `components.list/section-list`.

*Type*: Bug

**Comment by oskarth** [comment]
Also note that `ListView` is deprecated in latest React Native: https://facebook.github.io/react-native/docs/listview.html

**Comment by oskarth** [comment]
Possible duplicate: https://github.com/status-im/status-react/issues/1517 - lets keep this one since it is more detailed in terms of actions.
