### ISSUE TITLE
Wallet - Update default name for watched address when adding it

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#18416]
# Feature Issue

When adding a new watched address, the placeholder should  be `Watched address (x)` where `x` is the total number of watched addresses in the profile + 1.

<img width="200" src="https://github.com/status-im/status-mobile/assets/19339952/c852d700-4921-4d2e-94e3-dbbbf074cbe2" />

### Design

[Figma Link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052%3A522184&mode=design&t=H2vraH5nSHXL10D8-1)

### Acceptance Criteria

- The placeholder name for the watched address should display `Watched address (x)` 
- The placeholder name for a generated account should display `Account (y)` where `y` is the total number of accounts (not watched) in the profile + 1.
- the actual name should be empty and the user has to input some value themselves

**Comment by Rende11** [comment]
I would like to implement it

**Comment by Rende11** [comment]
@smohamedjavid I'm bit confused with `+1`. As I understand i should be something like this:
| action/state | account name |
| -- |-- |
| user have only default account | account name -> `Account (1)` |
| add one more account | `Account (2)` |
| add watched address | `Watched address (1)` |
| add watched address  again | `Watched address (2)` |
| add usual account | `Account (3)` |

Right?
Account number should be in parentheses?

**Comment by smohamedjavid** [comment]
> Right?

You are right @Rende11. The table makes the requirements understandable much simpler.

>  Account number should be in parentheses?

No, The account number should not be in parentheses.
