### ISSUE TITLE
Wallet-  “Doesn't support name” error when selecting ETH token on “Select asset” screen.

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18411]
There is a issue that occasionally crashes the app on Select Asset screen.

“Doesn't support name” error when selecting ETH token on “Select asset” screen. - original comment: https://github.com/status-im/status-mobile/pull/18242#issuecomment-1877386557

Safe handle the use of `name` function in that screen otherwise there is the potential for the app crashing.

**Comment by briansztamfater** [comment]
Maybe this was fixed here #18326 or is it a separate issue?

**Comment by J-Son89** [comment]
looks like it! will close this for now. Thanks @briansztamfater :)
