### ISSUE TITLE
Wallet - Implement remove account confirmation UI for generated account and watched address

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#18421]
# Feature Issue

Implement remove account confirmation UI for 
- Generated account 
- Watched address

<img width="212"  src="https://github.com/status-im/status-mobile/assets/19339952/83daaa8d-f520-451a-a27a-d7298f9f6d5b">

### Designs
[Figma Link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=900%3A233949&mode=design&t=PjyYX6y911TQlcCl-1)

### Description

The remove account confirmation will be shown to the user 
 - when the user taps on the trash icon (in the top right corner) in the account edit screen
 - on tap of `Remove account` action in the account options bottom sheet

### Acceptance Criteria

- The confirmation UI is shown on both entry points

### Notes
- The integration with `status-go` will be handled in a separate issue
- The `Recovery phase` flow in the design would be for the generated account flow
- The `Private key` flow is not covered in this issue as we need to implement the keypair flows.

**Comment by Rende11** [comment]
I would like to implement it
