### ISSUE TITLE
Wallet - Connect RPC for removing account 

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#18422]
# Feature Issue

Connect `status-go` RPC for removing wallet accounts.

### Description

- On confirmation, the RPC should be called with the address of the account to be removed
- On successful removal, the toast with the message `Account has been removed` (`Watched address has been removed` for watched address) is shown
- Call the `:wallet/get-accounts` event upon successful removal to refresh the accounts list

### Acceptance Criteria

- Toast message is shown upon successful removal
- The account is removed successfully with no listings in Wallet home, Account Switcher,...etc.
- The total accounts balance should reflect to the new list of accounts

### Notes

The default account can not be removed.

**Comment by Rende11** [comment]
I would like to implement it
