### ISSUE TITLE
Wallet - Send transaction, layer 1

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1843]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

Implementing 2-5 from https://docs.google.com/document/d/13eItUUqlfkRpx7iSutPRvThzTSrhirnKBcgxhOD3m6g/edit

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/1975 logged

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/1975 is now closed. However we still have https://github.com/status-im/status-react/issues/1774 which I would like to have fixed

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
