### ISSUE TITLE
Group chat content is not shown on Huawei Honor 8

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1844]
### Description

*Type*: Bug

*Summary*: During test session with @oskarth it was found that he is not able to see group chat content on his Honor 8

#### Expected behavior
Group chat should be displayed

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/30373080-cc16036a-9888-11e7-8c2a-67e38e4c2271.png)

### Additional Information
* Status version: 0.9.10-87-gf21f9ddf+
* Operating System: Android 7.0 EMUI 5.0 Huawei Honor 8

**Comment by oskarth** [comment]
I have issues with Honor 8 messages appearing in preview but not in actual chat even in regular 1on1 chat.

**Comment by asemiankevich** [comment]
@oskarth i think we can close this one?
