### ISSUE TITLE
Wallet: Password field contains saved data once user put it before while transaction confirmation

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18447]
# Bug Report

## Problem 
[comment]: # (A problem description)
Password field contains saved user's password: 

- when user goes back from transaction confirmation and then return to finish it 
- if user goes to create one more Account and before it he entered password while transaction confirmation
- if user goes to create one more Account and before it he entered password while he crated new Account before it

#### Expected behavior
Password field should not contain any saved data

#### Actual behavior
Password field contains saved data

### Reproduction

1.  Login with user that has tokens
2. Go to Wallet -> Send
3. Use the address of another user
4. Put the amount you want to send and Slide to send
5. Enter your password on Enter Password form
6. Do not tap Confirm and go back then Slide to send one more time

I captured a video but Password field is empty on it in terms of privacy. You can use it anyway.
Also, this video contains another issue with Confirmation, it is known and located [here](https://github.com/status-im/status-mobile/issues/18413) 

https://github.com/status-im/status-mobile/assets/147824399/79231936-994a-4bbe-8414-d5132f05d3b0

### Additional Information

- Status version: nightly 10.01.2024
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
Just posting a video of an issue described above, may give the cc more clarity. 

https://github.com/status-im/status-mobile/assets/19279756/c7afeec7-3231-4405-bca7-b19e38ded451

**Comment by J-Son89** [comment]
@mariia-skrypnyk - I believe this issue has since been resolved and we can close now? 🤔

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk - I believe this issue has since been resolved and we can close now? 🤔

Yes, no issue on nightly, can be closed 👏
Should I do it @J-Son89 ?
