### ISSUE TITLE
Update Wallet: Share QR Code

### ISSUE THREAD

**Issue by mmilad75** [status-im/status-react#18454]
Add `watched address` prop to the component.

Figma Design:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1338-34510&mode=design&t=Ba1qa0KHHBMyIfNJ-0

<img width="290" alt="Screenshot 2024-01-10 at 20 31 21" src="https://github.com/status-im/status-mobile/assets/55688834/8e8d970f-dca5-4895-b121-d3c06a1be746">

**Comment by OmarBasem** [comment]
@mmilad75 I am not sure what changes here?

**Comment by mmilad75** [comment]
> @mmilad75 I am not sure what changes here?

The watched-account has been added. We don't have that in the codes
