### ISSUE TITLE
Sometimes channels do not randomly appear in test community after its creation

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18455]
# Bug Report

## Problem 

Sometimes channels do not randomly appear in the test community after its creation, this leads to failures in e2e tests and is also reproducible manually.

Example:
https://github.com/status-im/status-mobile/pull/18374#issuecomment-1884660314 in `1. test_community_hashtag_links_to_community_channels, id: 702948`
On the [video](https://app.eu-central-1.saucelabs.com/tests/f4c8fcc2d8b145fbbd06c0718dd7cf14?auth=cf2405c3f14cb355888676d06d06f72c#245) (14:19) you can see that the `#general` channel is not displayed on the channel list and this caused the test to fail.

### Reproduction

1. Install any PR build 
2. Open the `Communities` screen
3. Tap `+`
4. `Create closed community`
5. Open the community

You may have to repeat these steps several times until the community opens without one of the channels.
Full list of channels: #general, #cats, #dogs, #rules

#### Expected behavior
<img width="316" alt="Screenshot 2024-01-10 at 18 23 08" src="https://github.com/status-im/status-mobile/assets/67952253/0aa4b358-ac68-4e27-a06a-ad41f331ae82">

#### Actual behavior

No `#rules` channel
<img width="316" alt="Screenshot 2024-01-10 at 18 23 54" src="https://github.com/status-im/status-mobile/assets/67952253/9c0e0ac4-2ba8-4b7a-b296-ea5d194ee930">

### Logs

[geth.log.zip](https://github.com/status-im/status-mobile/files/13891149/geth.log.zip)
[Status.log.zip](https://github.com/status-im/status-mobile/files/13891150/Status.log.zip)

### Additional Information

- Status version: nightly (only for x86 builds used for e2e), PR builds
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qfrank** [comment]
relate error seems to be: `2024-01-31T11:53:16.625Z ERROR [legacy.status-im.communities.e2e:14] - failed to create closed community. {:error {:code -32000, :message "chat not found"}}`

**Comment by qfrank** [comment]
Identified the [cause](https://github.com/status-im/status-go/blob/e4745d01b46562026ca0ffee7aed17e475979c3f/protocol/communities/manager.go#L1728) that inadvertently overrides `community.config.CommunityDescription` asynchronously. I plan to submit a pull request to address this issue tomorrow.
