### ISSUE TITLE
Wallet - Account Switcher - Update Share Account UI & Functionality

### ISSUE THREAD

**Issue by mmilad75** [status-im/status-react#18452]
The design for the share account modal has been updated.

Figma:
https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=2937-659374&mode=design&t=imlyBtnrEEDlhDvv-0

Blocked: https://github.com/status-im/status-mobile/issues/18454

<img width="973" alt="Screenshot 2024-01-10 at 20 22 09" src="https://github.com/status-im/status-mobile/assets/55688834/e62d1cd0-6f53-4d92-be46-8abd2693ca49">

**Comment by Pau1fitz** [comment]
@mmilad75 just as an FYI I have already fixed this issue

**Comment by mmilad75** [comment]
> @mmilad75 just as an FYI I have already fixed this issue

Was this https://github.com/status-im/status-mobile/pull/18479 also included in your PR?

**Comment by Pau1fitz** [comment]
@mmilad75 , no just the indicators at the bottom of the screen demonstrating the number of wallets and the current wallet that you are viewing. Example below:


https://github.com/status-im/status-mobile/assets/6873736/4edb4215-1649-4480-9703-ad2389ff7862
