### ISSUE TITLE
Inability to Input new value before the previous value on the send assets page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18459]
introduced in https://github.com/status-im/status-mobile/pull/19750

### Steps:
1. Enter any single number into the ETH textbox (e.g., "2").
2. Move the cursor before the entered data and input another value (e.g., "1").

### Actual result:
The new value (e.g., "1") is appended after the previous value (e.g., resulting in "21"). The new value is not inserted before the previous entry.

https://github.com/status-im/status-mobile/assets/52490791/867c9a51-46af-4ed0-87c6-1fc3f07a1732

### Expected result:
The new value (e.g., "1") should be inputted before the previous value (e.g., should display "12"), allowing the user to insert values in between existing entries.

cc: @vkjr

**Comment by vkjr** [comment]
We decided to get rid of the cursor in token input editing.
