### ISSUE TITLE
Jump-to screen empty container gradient overlay height is small in some devices

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#18476]
### Summary

Jump-to screen empty container gradient overlay height is small in some devices (needs further investigation)

![image](https://github.com/status-im/status-mobile/assets/17097240/3ebaabfb-e141-4bb8-bfaf-90d59b665613)

**Comment by ilmotta** [comment]
I'm closing this issue given the _Jump To_ feature is disabled at the moment. When/if we bring this feature back we can always re-open the issue.
