### ISSUE TITLE
'No ethereum node running' error is shown

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1847]
### Description

*Type*: Bug

*Summary*: Error message "No ethereum node running" received on iphone 6s

#### Actual behavior

Error message is shown despite the wifi is on
![image](https://user-images.githubusercontent.com/28752642/30375817-a3d4f618-9892-11e7-9ee9-6437fcd93831.png)

### Reproduction

I can't reproduce it on my iPhone still. The feedback from @oskarth sounds like it worked before, then stopped working suddenly despite wifi access

### Additional Information

* Status version: 0.9.11d92 - 1234.415, 0.9.10-99-g9e3bfdb6+
* Operating System: iOS, Android

**Comment by oskarth** [comment]
FWIW I just saw this on iOS simulator too (6s, develop@a85929e7). Intermittent issue.

**Comment by oskarth** [comment]
And Genymotion. Intermittent issue.

**Comment by asemiankevich** [comment]
The same behavour just seen using Play Market build
![image](https://user-images.githubusercontent.com/28752642/30595806-efbf68ca-9d5a-11e7-8e57-cd94afad452e.png)

I noticed it happened when I was running Status under 3G and then switched to WiFi

**Comment by asemiankevich** [comment]
havent seen this for a while, closing
