### ISSUE TITLE
Wallet total value is calculated when no ETH is on balance

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1848]
### Description

*Type*: Bug

*Summary*: When I created new account from scratch with 0 ETH balance I can see the Total value is calculated which is not correct.

#### Expected behavior
Total value is 0 for brand new account without ETH on balance

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/30376715-062e898e-9896-11e7-951b-202abf638d64.png)

### Reproduction

- Open Status
- Create account
- Go to wallet tab

### Additional Information

- Status version: 0.9.10-87-gf21f9ddf+
- Operating System: iOS, Android

**Comment by jeluard** [comment]
Currently `total value %` reflects variation of ETH value in USD last 24 hours (data provided by cryptocompare). It is not related to the current wallet.

Current value is indeed misleading, we have 2 options:

* modify how it is displayed (e.g. move label to each asset line)
* update the algorithm used to generate the value

Updated algorithm should reflect 3 parameters:

* 24 hours changes to wallet assets amount
* 24 hours changes to assets conversion rate
* how ETH and ERC20 assets changes are merged into final value

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/1653 for relevant assumptions.

I'll do a quickfix of this one and write up some thoughts on how we can grow this, and then we can revisit assumptions and see to what extent they make sense or not.

Reminder: also add explicit examples of expected portfolio value change.

**Comment by oskarth** [comment]
Wrote up thoughts and examples here: https://github.com/status-im/status-react/issues/1912

**Comment by asemiankevich** [comment]
Closed as fixed
