### ISSUE TITLE
Send flow: Asset need to be selected twice

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18495]
When going back from send_input screen to select_asset screen to choose a different asset, the selected asset does not update. 

The user needs to go back again and select the asset again (twice)

**Comment by ulisesmac** [comment]
I've just noticed there's a subscription being called only on component mount:

`(rf/sub [:wallet/wallet-send-token])` inside the ns `status-im.contexts.wallet.send.input-amount.view`.

It has given some problems before, such as the well know `"doesn't support name:"`, addressed some weeks ago by @briansztamfater.

The PR:
https://github.com/status-im/status-mobile/pull/18326#discussion_r1439726961

We need to solve this problem by properly calling the sub.
It also lacks of an effect to clean the db when navigating back.


I'm taking this issue
