### ISSUE TITLE
Sepolia network is not supported

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18510]
### Steps:
1. Go to Advanced
2. Check available networks

### Actual result:
Only goerli is presented in the test networks

### Actual result:
- The Goerli is updated to Sepolia test network, 
- The available collectibles and assets should be shown in the wallet supported by Sepolia

**Comment by VolodLytvynenko** [comment]
### NOTE: 
Retest ability to send collectibles. Sepolia collectibles can be mint here https://www.testnetmint.com/

**Comment by J-Son89** [comment]
assigning @smohamedjavid for now as there is a WIP with this. Feel free to remove yourself if I mixed things up :)
