### ISSUE TITLE
Wrong asset is shown on the 'sent assets' screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18524]
### Steps:
1. Go to the 'select assets' screen.
2. Select any asset (now the user is navigated to the send asset page where the selected asset is not shown initially).
3. Go back to the 'select assets' screen.
4. Select any other asset.

### Actual result:
- No asset is shown after the initial asset selection. (After step 2. See 3rd  second on the record)
- The previously selected asset is shown (After step 4. Ethereum is selected but DAI is shown instead, see 7th second on the record)

https://github.com/status-im/status-mobile/assets/52490791/11036214-7627-4158-8477-0d3ec877a4ff

### Expected result:
The selected asset should be shown.

### Device:
iPhone 11 Pro max, IOS 16

### Logs:

[logs.zip](https://github.com/status-im/status-mobile/files/13947449/logs.zip)

### ENV:
NIghtly [16 Jan 2024]

**Comment by ulisesmac** [comment]
@VolodLytvynenko I'm fixing this in
-  #18532
