### ISSUE TITLE
Wallet: Bridge - Add UI for Bridge token to page 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18529]
Implement the UI for the "bridge token to" page

- Add the screen to screen.cljs
- use real data
- use quo components 

the page does not need to navigate to the next page as we can address the issue that follows this.

designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=851-214299&mode=design&t=XVpZwIuZMewps38d-4

**Comment by Pau1fitz** [comment]
I can pick this one up @J-Son89
