### ISSUE TITLE
Implement QR scanning in Wallet Send

### ISSUE THREAD

**Issue by x-goose-x** [status-im/status-react#1853]
### User Story

As a user, I want to be able to scan a receiver's QR code to send currency.

### Description

*Type*: Feature

*Summary*: The basic elements of QR scanning are implemented, we just need to complete permissions requests for android and ios

**Comment by flexsurfer** [comment]
generating qr is implemented in epic/wallet branch, i used json https://github.com/status-im/status-react/blob/epic/wallet/src/status_im/ui/screens/wallet/request/views.cljs#L33

**Comment by x-goose-x** [comment]
closed due to design changes
