### ISSUE TITLE
[iOS] Cursor jumps to the end of the message when there is a line break in the middle of the composer

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18535]
# Bug Report

## Problem 
[comment]: # (A problem description)
User see how cursor jumps when we try to devide multiline line message into several messages

#### Expected behavior
No jumps of a cursor

#### Actual behaviour
Cursor jumps to the end of the message when there is a line break in the middle of the composer
No jumps of a cursor

### Reproduction

1. Open chat
2. Type multiline message
3. Put a cursor at the end of one message string at the half of a multiline message
4. Tap enter on the keyboard once and then twice 

https://github.com/status-im/status-mobile/assets/147824399/52991a95-4779-4afc-8fd6-b1a65ca6ddb5

### Additional Information

- Status version: nightly from the 17 of January
- Operating System:  iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
https://github.com/status-im/status-mobile/issues/18537#issuecomment-1897997613

**Comment by mariia-skrypnyk** [comment]
> [#18537 (comment)](https://github.com/status-im/status-mobile/issues/18537#issuecomment-1897997613)

Hi @ibrkhalil !

I've checked this behaviour on your old PR and it looks not good there too:


https://github.com/status-im/status-mobile/assets/147824399/87a3cfd1-cabe-4026-a2cd-ff64470f3a12

**Comment by mariia-skrypnyk** [comment]
Issue still exist, rechecked on nightly 08/04.

**Comment by ibrkhalil** [comment]
> Issue still exist, rechecked on nightly 08/04.

What iOS version did you check on please?

**Comment by ilmotta** [comment]
@mariia-skrypnyk, similar to #18534, since this issue was created, the composer was revamped. Maybe this bug is resolved. Could you verify again this issue is reproducible from nightly? Thanks

**Comment by mariia-skrypnyk** [comment]
Thanks @ilmotta will check.

**Comment by mariia-skrypnyk** [comment]
Hey @ilmotta !
Initially issue was detected on iOS.
I've rechecked it there and it doesn't exist anymore in our updated composer! 👏
