### ISSUE TITLE
[iOS] Cursor hides at the bottom of the composer and new entered text jumps

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18534]
# Bug Report
followup of  https://github.com/status-im/status-mobile/pull/18089

## Problem 
[comment]: # (A problem description)
If user type some text and then tap on return 10-20 (or less) times the cursor hides and after scroll down jumps appear

#### Expected behaviour
Cursor should be always visible during he moves up and down, no hidding and jumps of text

#### Actual behaviour
Cursor hides during he moves down, new typed text jumps

https://github.com/status-im/status-mobile/assets/147824399/0efdcef2-b50d-4dfd-91ca-64614ed49f78

https://github.com/status-im/status-mobile/assets/147824399/80a67574-3182-49bc-88c5-c191ff652a78

### Reproduction

1. Open composer
2. Put text with short rows like I do on the video
3. You should have a lot of text to make cursor be at the bottom of composer
4. Tap on Return 10-20 times (at this step my cursor start hiding)
5. Try to type short text rows again

### Additional Information

- Status version: nightly 
- Operating System: iOS
- Devices: iPhone 13 iOS 17.2.1 and  iPhone X, IOS 16.7.2

[comment]: # (Please, add logs/notes if necessary)

**Comment by clauxx** [comment]
blocked by https://github.com/status-im/status-mobile/issues/18137, which optimises the composer.

**Comment by ilmotta** [comment]
@mariia-skrypnyk, since this issue was created, the composer was revamped. Maybe this bug is resolved. Could you verify again this issue is reproducible from nightly? Thanks

**Comment by mariia-skrypnyk** [comment]
Thanks @ilmotta will check.

**Comment by mariia-skrypnyk** [comment]
Yes @ilmotta !

Rechecked and this issue is resolved too! 

🙌
