### ISSUE TITLE
iOS build fails via `make run-ios` but works with `Xcode.app` after upgrading `react-native` to `0.73.x`

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18548]
# Problem

`make run-ios` fails with : 
```
error Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, 
consider building your app with Xcode.app, by opening 'StatusIm.xcworkspace'.
info Run CLI with --verbose flag for more details.
```

Since we do not want to rely on opening Xcode app I try running `xcodebuild` with -verbose flag like this 
`cd ios && xcodebuild -workspace StatusIm.xcworkspace -configuration Debug -scheme StatusIm -verbose | xcbeautify`

Thats when I get more details on the failure : 

```
[FBReactNativeSpec] Running script [CP-User] Generate Specs
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/siddarthkumar/Library/Developer/Xcode/DerivedData/
	StatusIm-fxiitjbbybrcsqcxqartjfyvqxdo/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/
	FBReactNativeSpec.build/Script-46EB2E00021AC0.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)
```

My knee jerk reaction when i spotted `DerivedData` in the error message was that this issue could be cache related (but it wasn't)
I ran `make xcode-clean` and `make clean` just and this issue was consistently reproducible.

## Notes

- We had faced a similar issue in the past where the iOS side would build via `Xcode.App` but fail via `xcodebuild` CLI -> [https://github.com/status-im/status-mobile/issues/15911](https://github.com/status-im/status-mobile/issues/15911#issuecomment-1549689514)

- guidelines by React Native team on how to deal with `FBReactNativeSpec` failures -> https://reactnative.dev/docs/0.71/new-architecture-troubleshooting#xcode-build-issues

blocks #16721

**Comment by siddarthkay** [comment]
First thing I try is to manually execute `Script-46EB2E00021AC0.sh` and It obviously fails, this time with an error message 
```
[nix-shell:~/code/experiments/status-mobile/ios]$ sh /Users/siddarthkumar/Library/Developer/Xcode/
DerivedData/StatusIm-fxiitjbbybrcsqcxqartjfyvqxdo/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/
FBReactNativeSpec.build/Script-46EB2E00021AC0.sh
/bin/sh: /../../scripts/xcode/with-environment.sh: No such file or directory
```
inside this bash script, the path to `WITH_ENVIRONMENT` is determined like this
`WITH_ENVIRONMENT="$RCT_SCRIPT_RN_DIR/scripts/xcode/with-environment.sh"`

the variable `RCT_SCRIPT_RN_DIR` comes from here https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/react_native_pods_utils/script_phases.rb#L12

This could mean that since this variable is not properly set the script execution could fail.
Investigating further.

**Comment by siddarthkay** [comment]
The issue is indeed in this script, after adding some logs to `script_phases.rb` we get the following logs : 

```
RCT_SCRIPT_RN_DIR is -> /Users/siddarthkumar/code/experiments/status-mobile/ios/Pods/../../node_modules/
react-native/React/FBReactNativeSpec/../..

WITH_ENVIRONMENT is -> /Users/siddarthkumar/code/experiments/status-mobile/ios/Pods/../../node_modules/
react-native/React/FBReactNativeSpec/../../scripts/xcode/with-environment.sh

Node found at: /nix/store/ihji2bc16a7kj8d9z3xglj619v9ywmbi-nodejs-20.2.0/bin/node
cp: invalid option -- 'X'

``` 

we can see that `cp` command is failing, which seems to be the core problem.

**Comment by siddarthkay** [comment]
so `-X` is used along with `cp` here at : https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/react_native_pods_utils/script_phases.sh#L107

```bash
moveOutputs () {
    mkdir -p "$RCT_SCRIPT_OUTPUT_DIR"

    # Copy all output to output_dir
    cp -R -X "$TEMP_OUTPUT_DIR/." "$RCT_SCRIPT_OUTPUT_DIR" || exit 1
    echo "$LIBRARY_NAME output has been written to $RCT_SCRIPT_OUTPUT_DIR:" >> "${SCRIPT_OUTPUT_FILE_0}" 2>&1
    ls -1 "$RCT_SCRIPT_OUTPUT_DIR" >> "${SCRIPT_OUTPUT_FILE_0}" 2>&1
}
```

and that is why when this script fails they just exit 🥲👌🏻👏🏻

**Comment by siddarthkay** [comment]
Fixed by patching `-X` out of [script_phases.sh#L107](https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/react_native_pods_utils/script_phases.sh#L107) 

ref :  https://github.com/status-im/status-mobile/pull/18255/commits/9fb9e698386be487936a9100681cdd7ebc362c8c

**Comment by sandipndev** [comment]
Indeed, this was a great find. Thanks for solving this. I fixed using patch-package method.
https://github.com/GaloyMoney/galoy-mobile/pull/3181/commits/f409797ecc9351e372bb6b84b71198476a8372d6

I see you use nix (we use it too, via flakes) and really wish there was a way to handle Xcode inside nix dips but Apple and it's lock-in.

**Comment by siddarthkay** [comment]
@sandipndev : we recently moved over to using .patch files instead with this PR -> https://github.com/status-im/status-mobile/pull/19451

We just don't use patch-package npm library, we apply the patches ourselves in a patch phase inside nix.

and our patch now is also pretty similar -> 
https://github.com/status-im/status-mobile/blob/6e854428f22cdafccfba52c110c4e73bb606822d/patches/react-native-script.patch#L9
