### ISSUE TITLE
Quo - Create list items - Network list component

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18540]
Create the List Item - Network list component
Designs: 
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=23459-209602&mode=design&t=KsjHUcCaRAgCU0JT-4

<img width="260" alt="Screenshot 2024-01-17 at 12 33 27" src="https://github.com/status-im/status-mobile/assets/22799766/f603cba0-3c72-406d-8ec7-e106892465d4">

Acceptance Criteria
- Component Spec added (jest tests)
- Quo Preview Screen
- Align with best practices
- Light & Dark theme

**Comment by Pau1fitz** [comment]
I can pick this one up @J-Son89
