### ISSUE TITLE
Wallet Request screen UI issues [1526]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1855]
### Description

*Type*: Bug

*Summary*: issues found and to be fixed for https://github.com/status-im/status-react/issues/1526

#### Actual behavior

- [x]  CR code should not be scrollable and must be centered.
- [x]  Wallet amount is not shown
- [x]  Amount field doesn't highlight in focus
- [x]  Contacts screen looks wrong on Android (2.1 can't be fixed because https://github.com/facebook/react-native/issues/7474)
- [ ]  Amount rules (let's create separate issue for this because design is needed)

## 1. iOS/Android:

Currently max length of the amount: 15 characters including separator (./,). This is different from the amount user can type for /send command in chat. It should be consistent in both places and seems like Wallet is a place to adjust:
1.1 Expected: Amount before separator - seems like can be of any length or I can't find the limit
1.2 Expected: Amount after separator - should be not more than 18 digits after comma (e.g 0.123456789012345678). Currently, it's possible to enter only 13 digits after comma (e.g. 0.1234567890123)
1.3 "0" is now not allowed as a sum to send. In some cases, it's valid to send "0" (e.g https://contribute.status.im/sgt.html ), so it should be fine to request it too.

## 2. Android
2.1. Select contact screen, top part with phone icons (carrier, battery status, time) is on black background. Expected: white background, black text/icons
2.2 There is some empty space between "Contacts" heading
![image](https://user-images.githubusercontent.com/28752642/30420588-b37e1832-9942-11e7-8f23-07e75916a712.png)

### Additional Information
* Status version: 0.9.10-98-g82f6a82b+
* Operating System: Android, iOS

**Comment by yenda** [comment]
Fix merged in develop

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
