### ISSUE TITLE
Composer not closing after cancelling edit message after reopening chat

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#18550]
### Video

https://github.com/status-im/status-mobile/assets/17097240/90022cb2-6ba9-462d-92e8-dc2da6706d55

**Comment by Parveshdhull** [comment]
Also note: composer opens in expanded state

**Comment by clauxx** [comment]
I think the expected behaviour here would be to still open it in expanded state, but also focus the input when re-entering. I vaguely remember having to fix this a while back.

**Comment by Parveshdhull** [comment]
> I think the expected behaviour here would be to still open it in expanded state, but also focus the input when re-entering. I vaguely remember having to fix this a while back.

https://github.com/status-im/status-mobile/issues/17825

> Expected behavior
> The input is not focused when re-entering the screen.

**Comment by clauxx** [comment]
Yup, was the other way around then 👍

**Comment by churik** [comment]
I couldn't reproduce the issue on  nightly 21/06/24 (Google Pixel7)  Reopen if still relevant.
