### ISSUE TITLE
Incorrect drawer for non-members in community chat

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18554]
### Steps:
1. Open a community where you are a member.
2. Send some messages.
3. Leave the community.
4. Open the channel of the current community.
5. Long-tap on your message.

### Actual result:
Community non-members see the following options in the drawer after the message is long-tapped:
- Ability to react.
- Edit message.
- Pin/Unpin.
- Delete for everyone.
![image](https://github.com/status-im/status-mobile/assets/52490791/4753f963-24fc-45a9-868f-a1bec682a21f)

### Expected result:
Community non-members should see the drawer as per the [design](https://www.figma.com/file/apCsJHT8J58JXbJD2igtbd/Context-Drawers-for-Mobile?type=design&node-id=1-3573&mode=design&t=iq6aSpK2V9nagAdj-0), excluding the ability to show reactions. Reference to design team reply [here](https://discord.com/channels/624634427930312714/842696205213368331/1197485033309622332).

### ENV:
Nightly [18 Jan 2024]

**Comment by ilmotta** [comment]
I removed the label `wont-fix` because this bug is actually significant because users shouldn't see actions in the app that have no effect. This type of problem is an obvious source of confusion and frustration to users.
