### ISSUE TITLE
Cannot add existing ENS owned by user ("Username does not belong to you" error appears)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18557]
**Steps:** 

1. Recover a user who owns ENS
2. Open Legacy settings
3. Tap ENS usernames
4. Try to add existing ENS owned by this user 
5. Observe the result

**Actual result:** "Username does not belong to you" error appears despite ENS is owned by user. I have tried to add ENS that are owned on Mainnet and Goerli networks but result is the same. 

https://app.ens.domains/pavlotest.eth

[Status-debug-logs (95).zip](https://github.com/status-im/status-mobile/files/13975713/Status-debug-logs.95.zip)
![photo_2024-01-18 13 04 57](https://github.com/status-im/status-mobile/assets/97245802/e38bd3cd-b85d-4871-939b-c7fd6719a19b)

https://github.com/status-im/status-mobile/assets/97245802/51e6b086-1bea-4f83-a63c-6fed765648d0

![photo_2024-01-18 13 06 54](https://github.com/status-im/status-mobile/assets/97245802/7daaa19c-1516-4d75-a223-9b0ce1832726)

**Expected result:** user is able to add ENS which he owns. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by bz404** [comment]
Hey,guys
Seems this issue was fixed and Merged into version 2.27,when the mobile of 2.27 will release in appstore?

**Comment by pavloburykh** [comment]
> Hey,guys Seems this issue was fixed and Merged into version 2.27,when the mobile of 2.27 will release in appstore?

cc @John-44

**Comment by bz404** [comment]
> > Hey,guys Seems this issue was fixed and Merged into version 2.27,when the mobile of 2.27 will release in appstore?
> 
> cc @John-44
Thank you Sir.
