### ISSUE TITLE
No routes are found in case of valid amount in fiat is entered

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18561]
I believe the root-cause of the bug is that after switching input to fiat the app still validates this amount as if we would enter amount in crypto.  

**Steps:** 

1. Open sending token screen
2. Switch to input in fiat
3. Enter the amount that would be valid in fiat but not valid in crypto
4. See if routes are found

**Actual result:** No routes are found. 

https://github.com/status-im/status-mobile/assets/97245802/f6b9d92e-faf7-4eca-b0ae-6914766d4172

**Expected result:** routes are found

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@pavloburykh is it still the case?

**Comment by pavloburykh** [comment]
> @pavloburykh is it still the case?

At this moment it is working fine. The problem is on provider's side and @dlipicar is conducting communication with Alchemy's support. Am not sure if the issue will not appear again but at this moment I guess we can close this ticket.

**Comment by pavloburykh** [comment]
> @pavloburykh is it still the case?

@churik yes, it is valid.
