### ISSUE TITLE
Create reanimated worklets directly in Clojure

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#18566]
# Problem

Current worklets need to be written in JS, then imported and called in ClojureScript, it leads to code hard to maintain and we need to create those worklets by hand for evey new operation we want to perform.

So it'd be really good if we can create reanimated worklets directly in ClojureScript.
The main goal is to improve the developer experiece while not hurting the performance, as well as improve the reanimated API.

### Story

I've done several attempts to do this, one of them being succesfully able to execute the following:
```clojure
(let [loading-interpolation (animated/use-shared-value 0.1)
      color-1               "#627BD2"
      color-2               "#408C6A"
      color-4               "transparent"
      loading-colors        (animated/use-animated-style
                             (w/worklet
                              {:background-color (animated/interpolate-color loading-interpolation [0 1] [color-1 color-2])
                               :border-color     (animated/interpolate-color loading-interpolation [0 1] [color-2 color-4])
                               :opacity          (+ (- 1 loading-interpolation) 2)}))])
```

backed by a general worklet written in JS and a `w/worklet` macro that passes JS objects containing the instructios for that macro to execute.

I was happy enough with this implementation, but then I realized at Status we are writting things like:
```js
return useDerivedValue(function () {
    'worklet';
    const r = parseInt(color.substring(1, 3), 16);
    const g = parseInt(color.substring(3, 5), 16);
    const b = parseInt(color.substring(5, 7), 16);

    return progress.value <= 25 ? `rgba(${r}, ${g}, ${b}, .4)` : `rgba(${r}, ${g}, ${b}, .2)`;
  })
```

To process it, I'd need to pass all those instructions (`substring`, string concat, `if`, ...) to the general worklet... and that's like reimplement the ClojureScript compiler.

I was thinking about adding [squint](https://github.com/squint-cljs/squint)  instead, but not sure how to do it, it'd need experimentation.

### How to solve it now

I know the reanimated plugin isn't working for our ClojureScript compiled code, but I think there's a way to make it work.
I did an experiment in a JS script to apply that plugin and...  :tada:  and it worked! :tada: 

I was able to perform an animation using the `animated-styles` here:
```clojure
(let [sv              (reanimated/use-shared-value 0)
      animated-styles (animated/useAnimatedStyle
                       (fn my-worklet-fn []
                         (js* "'worklet;'") ;; <- Not really needed
                         (js/console.log "hola")
                         #js{:transform #js[#js{:translateX (.-value sv)}]}))])
```

It just needed to execute that script after building.

Now the goal is to actually integrate it into Status, I'm aiming to add it as a [shadow-cljs Build Hook](https://shadow-cljs.github.io/docs/UsersGuide.html#build-hooks).

This is not the definitive solution, but for most of our animated code it'll work well.

## Acceptance Criteria

- Nothing is broken, particularly, animations are working exactly as before. 
- We can define worklets directly in ClojureScript

## Notes

Limitations:

We still won't be able to use Clojure custom data structures inside the worklets, same for Clojure functions, it's writing JS but using ClojureScript.

## Future Steps

If this is sucessfully done, we can start thinking about improving the API, some ideas:

- A macro that receives Clojure maps using kebab-case keywords and returns JS objects using camelCase strings. it has the common macro limitations, but it may work well for most of the cases
- Consider adding squint, if it emits very lightweight JS code that is able to run in a worklet, it'd be like just using Clojure inside the worklets
- Improve the Reanimated API we created to make it more transparent to the Reanimated code we find in internet (recently, the support to pass a vector of styles has been added, check #18381)

**Comment by Parveshdhull** [comment]
Hi @ulisesmac, Thank you very much for sharing your research on migration of worklets from js to cljs.

Please also keep an eye on performance and make sure we are not losing it.

Btw, a related suggestion from [Thomas Heller](https://github.com/thheller) (creator of shadow-cljs)

[My advice would be to keep those "worklets" in JavaScript.](https://stackoverflow.com/a/72513996)

**Comment by ulisesmac** [comment]
Hi @Parveshdhull!

First of all, thanks for sharing your opinion on this, it's highly appreciated! since you were in the process of integrating reanimated!

Probably I'll be solving this issue for the next moth, we are busy right now. Also I'd like to get even more feedback.


> Please also keep an eye on performance and make sure we are not losing it.

Yes, actually while addressing these things, performance is something I'm taking care of.

For the scope of this issue, the code transformation will get done at compile stage, so it won't impact negatively. Actually, we won't need many of the wrapper functions we are using, so it'll get slightly improved.

For future work:

  > A macro that receives Clojure maps using kebab-case keywords and returns JS objects using camelCase strings. it has the common macro limitations, but it may work well for most of the cases

  A macro performs the transformations at compile time, but it needs the data to be there (pass the maps, instead of passing a var containing the maps). so the performance won't get hurt. For a more general solution we could evaluate the tradeoffs between the performance impact vs flexibility.

  > Consider adding squint, if it emits very lightweight JS code that is able to run in a worklet, it'd be like just using Clojure inside the worklets

  Again, this would be done at compile time :)


Related to What Thomas Heller said:

> The main hurdle is that those directives need to be processed by the react-native build tools and it likely won't understand the ClojureScript code in the first place.

I'm solving that part.

The directive (`"worklet;"`) is no longer needed for the plug-in to work, as an example we have some JS worklets in our code not having that directive and they still work. Reanimated plugin looks at the usages of Reanimated hooks to decide if the function should be converted or not.

If we no longer need the directive, you may wonder: why our code isn't converted then?
well, our code is being written as a string by shadow-cljs, and the plug-in isn't able to convert it.

My experiments showed me that we can apply the plug-in to those strings and we can get a worklet running :) 

The aim of this issue is adding the plug-in to the build process that shadow-cljs does, before they are being written as strings in `result/index.js`, so we'd get the worklet transformation in our compiled JS code.

**Comment by ilmotta** [comment]
Hey @ulisesmac, this is a very cool issue! Even if, eventually, you find out it doesn't fully work as you anticipated (e.g. perf reasons or dev ergonomics) it's still worth exploring. `squint` is fascinating in the Clojure ecosystem. Even JSX can be produced by it (gives some ideas...).

**Comment by ulisesmac** [comment]
Closing this issue because the idea was explored, here's the output, if anyone in the future is interested, please check the PR:
- #18795

Where it has a working version and a better explanation of everything.

Basically, it worked but there were three main problems:

1. There's a step in our compilation process that kills the node subprocesses executing the babel plugin, this issue is only present in our release process, shadow-cljs in release mode is not the problem.

2. I created a new subprocess each time a file was parsed using the babel plugin, this is inefficient. maybe the subprocess could be reused but I wasn't sure how to do it. Shadow-cljs also uses a node process, but I couldn't manage to reuse it.

3. Limitations in the code, the worklets were only able to be declared in a `let` binding.
