### ISSUE TITLE
Schema error after recent changes on token-tag

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#18581]
token image src might be `nil`

- sub :community/token-gated-overview
- token-requirement-list
- token-tag
- token view

related changes https://github.com/status-im/status-mobile/blob/eeb3c9853bab99c6311cc0cef47c352ee9814326/src/quo/components/tags/token_tag/view.cljs

![CleanShot 2024-01-22 at 09 53 43](https://github.com/status-im/status-mobile/assets/15090582/34322909-7978-46fb-895e-28ed13d30344)

![CleanShot 2024-01-22 at 09 59 03@2x](https://github.com/status-im/status-mobile/assets/15090582/e5937e61-438e-4083-bb35-2244130858ff)

![CleanShot 2024-01-22 at 09 54 19@2x](https://github.com/status-im/status-mobile/assets/15090582/7a778a07-6249-41e6-aabe-27d19e6fd59b)

cc @ulisesmac

**Comment by ulisesmac** [comment]
Right now the token is optional.

I see we need to also accept `nil` as a valid token in order to remove this warning.

Feel free to address it as part of a PR, or I could just add it in my following PR.
