### ISSUE TITLE
Improve main wallet screen pull-to-refresh 

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#1858]
### User Story

As a user, I want to have a nice visual effect when doing a pull-to-refresh

### Description

When doing a pull-to-refresh the whole screen should be pullable (both `assets` and `actions` lists must not be pullable individually)
The visual indication then appears on top of the amount.

*Type*: Feature

**Comment by jeluard** [comment]
@denis-sharypin @andmironov Do you have new mockups for pull to refresh with the new wallet design?

**Comment by denis-sharypin** [comment]
It's quite a standard behavior. You can read about here:
iOS
https://developer.apple.com/ios/human-interface-guidelines/controls/refresh-content-controls/
Android
https://material.io/guidelines/patterns/swipe-to-refresh.html#

I believe a user should allow updating the whole screen not only part with assets.
![wallet reload](https://user-images.githubusercontent.com/6559881/36035855-7c30099a-0db8-11e8-9e0c-811640270770.pn

## Known bugs

### 1.Scrolling through main actions area is not a correct behavior.
![img_2759](https://user-images.githubusercontent.com/6559881/36035962-cc179cb6-0db8-11e8-8e24-5ed471314e35.PNG)

## 2.Assets auto update on tapping wallet tab in the tab bar should be removed.
![img_2791](https://user-images.githubusercontent.com/6559881/36158669-29b91666-10dd-11e8-82bb-a1e942dfd232.jpg)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0xb9f2e804f8977f418304b3f59734b8b114760ab4](https://etherscan.io/address/0xb9f2e804f8977f418304b3f59734b8b114760ab4)
Network: Mainnet
Paid to: jeluard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
