### ISSUE TITLE
Update UI and data model (re-frame) on Select Input Page to handle Bridging flow

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18591]
The transaction confirmation page needs a few adjustments to handle the bridging
designs
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1344-291019&mode=design&t=RuyhufmiW7Y5H6pU-4

Also ensure the re-frame data model is correctly setup and that the correct data is passed to the next step of the flow.

This task probably depends on some other issues being completed in advance so check the associated epic 👍

refactor where needed so that the screens handle the various transaction types - i.e bridigin, send-asset, send collectible

**Comment by Pau1fitz** [comment]
@J-Son89 happy to pick this one up once [this](https://github.com/status-im/status-mobile/pull/18560) is merged

**Comment by OmarBasem** [comment]
@Pau1fitz I think this issue would require real asset data on the bridge screen to be implemented first. I have made a PR for that https://github.com/status-im/status-mobile/pull/18713

**Comment by J-Son89** [comment]
Nice one @OmarBasem, I'm pretty sure it's okay to do in parallel as the mock data coming through is matching the real data (afaik)👌
Probably we shouldn't open up any further bridging issues until your pr is merged though!
