### ISSUE TITLE
Collectible scroll view header is buggy

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#18595]
# Bug Report

## Problem 

When a user visits the collectible scroll view, the blur header has an erratic behavior

#### Expected behavior

Designs:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-318949&mode=design&t=o9pEMRpAgIbY54R4-4

![image](https://github.com/status-im/status-mobile/assets/90291778/7d81c06d-08ed-499b-89cf-94409840423b)

![image](https://github.com/status-im/status-mobile/assets/90291778/b9a4bb70-58b8-4cb5-9282-4a7f3e497c06)

![image](https://github.com/status-im/status-mobile/assets/90291778/d8b1d16d-00ca-4cdc-ab05-532ff848205d)

#### Actual behavior

[Screencast from 2024-01-22 23-29-02.webm](https://github.com/status-im/status-mobile/assets/90291778/a1ac8a3f-0089-4f64-ab4b-914049c060ca)

### Reproduction

1. Go to wallet tab
2. Add an account owning collectibles
3. Click on a collectibe to see its details.

### Additional Information

It seems we are inheriting this issues from a reused component for communities, we need to check the differences and create one that behaves well for the wallet.

One difference I've noticed at the moment is that we don't need to make it appear with an animation (from top to bottom), so the left and right buttons don't need to change.

**Comment by FFFra** [comment]
@ulisesmac  this is a duplicate?
