### ISSUE TITLE
Add visualisation for errors in collectible loading

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#18609]
# Feature Issue

Add designs for cases when errors occurred during collectible loading and we unable to display them .

![Screenshot 2024-01-24 at 14 53 15](https://github.com/status-im/status-mobile/assets/5786310/9a68569e-c4b1-4451-add8-cf02e4f9e07d)

[Figma link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=8980-203703&mode=dev)

### User Story

As a user, I want to see information about errors in collectible loading **so that** I have understanding of what happens. 

### Acceptance Criteria
Errors shown to user

**Comment by FFFra** [comment]
Already done
