### ISSUE TITLE
Support collectibles that owned multiple times

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#18610]
# Feature Issue

Collectibles that owned multiple times should be recognizable on collectible info page

![Screenshot 2024-01-24 at 15 04 06](https://github.com/status-im/status-mobile/assets/5786310/42aab817-7e3f-4711-8f96-2041e045a741)

[Figma link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7247-86242&mode=dev)

**Blocked:** needs clarification when this case is possible and if this already supported on status-go side

### User Story

As a user, I want to collectible page to show information that collectible owned multiple times **so that** I know how many of them I own.

**Comment by OmarBasem** [comment]
@vkjr do you know if this issue is till relevant or if we are having this feature for mvp? cc @J-Son89

**Comment by J-Son89** [comment]
yeah I think we have this now. closing!
