### ISSUE TITLE
Popup 'undefined is not a function' is shown after sending /phone command on Android [feature/chat-module-refactoring-#1709]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1862]
### Description

*Type*: Bug

*Summary*: Sent /phone command with valid phone number and got popup `undefined is not a function ..'
![screenshot_20170914-195618](https://user-images.githubusercontent.com/6584810/30444514-ef372172-998b-11e7-82d2-10990ef31cbe.png)

#### Expected behavior
No popup after sending phone command
#### Actual behavior
 popup `undefined is not a function ..'

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/6557981/sessions/5/?accessToken=Nld0GDNt86xLeeRg/Ir0u1ZZD-Q 

- Open Status
- Open Console
- tap on /phone command, provide valid phone number and send it

### Additional Information
* Status version: PR `feature/chat-module-refactoring-#1709`   0.9.10-96-gef6a9ac2+ 
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1 and avd emulator Nexus 5, API 23

**Comment by asemiankevich** [comment]
This is fixed in `0.9.10-120-ge1b2dd32+`

**Comment by annadanchenko** [comment]
tested ok in develop. will be in 0.9.12 release
