### ISSUE TITLE
The static images are not shown in for collectible on collectible list

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18631]
### Steps:
1. Add a watch-only account using the address 0x8d2413447ff297d30bdc475f6d5cb00254685aae.
2. Scroll through the list of collectibles.

### Actual result:
An uploading spinner is always displayed for animated/audio/video collectibles, and static images are not shown.

https://github.com/status-im/status-mobile/assets/52490791/b8a1871d-395b-4340-8bac-9c597bb2e57e

### Expected result:
The static snapshot should be displayed in the collectible list for animated/audio/video collectibles.

reference https://discord.com/channels/624634427930312714/1200162022189441104/1200390987038609418

### ENV:
Nightly [25 Jan 2024]

**Comment by mmilad75** [comment]
BLOCKED: At the moment, the data that are coming from the backend don't include a preview image for the videos, svgs, etc.

**Comment by clauxx** [comment]
@mmilad75 do you mind if I take this one over? Already started on fixing the collectibles performance by generating preview images. This seems to be in the same realm of changes.

**Comment by mmilad75** [comment]
> @mmilad75 do you mind if I take this one over? Already started on fixing the collectibles performance by generating preview images. This seems to be in the same realm of changes.

Sure, you can take it over. @clauxx

**Comment by J-Son89** [comment]
@clauxx - can you update on why you unassigned this? What findings did you get in the end?

**Comment by clauxx** [comment]
@J-Son89 i unassigned it due to a change in priorities. I was working on generating thumbnails with the media server (which seemed related to this task, hence i assigned this to myself), but we started working with crews and prepping for the release so I stopped working on it and unassigned myself. This specific task i didn't start on.

**Comment by J-Son89** [comment]
thanks @clauxx

**Comment by J-Son89** [comment]
@VolodLytvynenko - I think we updated the collectible component since this. Is this issue still relevant?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - I think we updated the collectible component since this. Is this issue still relevant?

hi @J-Son89 Thank you for the update. The issue can be closed
