### ISSUE TITLE
Broken profile QR after syncing with desktop

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18639]
**Steps:** 

1. User A (Desktop) generates sync QR
2. User B (mobile) scans sync QR
3. Wait until sync process is completed
4. Open Share screen on mobile
5. Observe the result

**Actual result:** 

**IOS:** Profile QR is not displayed

![photo_2024-01-26 15 11 10](https://github.com/status-im/status-mobile/assets/97245802/b2641ec8-837f-4b8e-a865-5356f19b1a1f)

https://github.com/status-im/status-mobile/assets/97245802/8782ee46-c418-4062-aaa4-5a93e097e579

**Android:** app crashes with below error

![photo_2024-01-26 15 09 10](https://github.com/status-im/status-mobile/assets/97245802/8fb9803a-8065-4f25-992b-ffd9553d0957)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
I was not able to reproduce this maybe its because am using an old desktop version. Seems to work just fine. I will try with an older the latest desktop version

**Comment by pavloburykh** [comment]
> I was not able to reproduce this maybe its because am using an old desktop version. Seems to work just fine. I will try with an older the latest desktop version

Hey @jo-mut! Seems that @clauxx already has a fix https://github.com/status-im/status-mobile/pull/18643 So there is no need for you to continue investigation.
