### ISSUE TITLE
add quo counter / collectibles counter component

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18632]
implement counter / collectibles counter component
designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=33720-16685&mode=design&t=sUbgfcjeioSMj1mf-4

Acceptance Criteria:
Component Spec test
Preview screen
code matching best practices

**Comment by Rende11** [comment]
I would like to implement it
