### ISSUE TITLE
Communities: Implement permission drawer

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18638]
As a user joining a community
I want to be able to see all the permissions for this community that I am able to fullfil, independently of which addresses I have selected
So that I would know which tokens are needed to join for a specific role

### Description

When opening the permission drawer, we should show the user all the roles that he can fullfill, independently from which addresses are actually selected:

```
Permission drawer should show all availiable roles relevant to content of all addresses (shared and not shared)
```

### Designs
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=15348%3A171381&mode=dev

Potentially that's something that can re-use the same endpoint @ilmotta is working on.

**Comment by FFFra** [comment]
Updated description with the newest Figma design
