### ISSUE TITLE
Broken wallet icon after sync with desktop

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18640]
**Steps:** 

1. User A (Desktop) generates sync QR
2. User B (mobile) scans sync QR
3. Wait until sync process is completed
4. Check how wallet icon looks like in different places (i.e. wallet QR, wallet screens etc)

**Actual result:** 

![photo_2024-01-26 15 21 00](https://github.com/status-im/status-mobile/assets/97245802/8a7535c4-7480-4db6-9ef4-9bde253b6220)
![photo_2024-01-26 15 21 03](https://github.com/status-im/status-mobile/assets/97245802/058d7217-f38e-47b8-888a-7be3c274a25b)
![photo_2024-01-26 15 21 06](https://github.com/status-im/status-mobile/assets/97245802/8e935817-5d79-4095-8359-25de515a154d)
![photo_2024-01-26 15 21 10](https://github.com/status-im/status-mobile/assets/97245802/19a67889-1757-4239-a537-e4cbc716c872)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
please see: https://www.notion.so/1-27-Mobile-Testing-session-cc4b9dd5ede9406ebeb1c0cd8dd5ac70

and discuss with @smohamedjavid before fixing this.

In short this is due to the previous way Desktop was handling emojis. 👍
