### ISSUE TITLE
Communities - implement View Members Option 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18648]
Currently the view members of a community is using the old-ui.
Update the ui to match the designs.
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=5933-272883&mode=design&t=9nkvcTkWQnza6FyZ-4

<img width="388" alt="Screenshot 2024-01-26 at 16 54 03" src="https://github.com/status-im/status-mobile/assets/22799766/84b796c9-31df-4b32-a127-0d643a160d91">

Acceptance Criteria:
This page should be visible from all possible entry points 
- home page, community overview page
- this should use real data (same as old ui)

add-ons
if possible migrate any events in src/legacy/ folder into src/status-im folder

**Comment by ibrkhalil** [comment]
Similar to: https://github.com/status-im/status-mobile/pull/18489

**Comment by J-Son89** [comment]
Thanks @ibrkhalil, sorry this went unnoticed for some reason. IT's a duplicate for sure 👍
