### ISSUE TITLE
Component: Amount input

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18641]
Implement amount input component as per design in figma:

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=34338-34752&mode=design&t=SeROiNTNfQhZhbb6-0

Acceptance Criteria:
Component Spec test
Preview screen
code matching best practices
add malli spec

**Comment by nazariifenii** [comment]
Working on this issue
