### ISSUE TITLE
Unable to find routes for asset transfer

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18652]
### Steps:
1. Recover the user with available assets to sent
2. Go to the send page
3. Attempt to send the available amount

### Actual result:
Routes for the asset transfer are not found (no matter testnet or mainnet network is used)

https://github.com/status-im/status-mobile/assets/52490791/7f2f60f0-e00c-4217-a336-20ad9e1282e8

### Expected result:
Routes are found

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14237135/logs.zip)

### ENV:
Nightly 12.02.2024

**Comment by briansztamfater** [comment]
As this has been reopened, I have removed the assignment so that any developer can pick it up. I might do it later if nobody else does.

**Comment by J-Son89** [comment]
@VolodLytvynenko - is this still relevant?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - is this still relevant?

Hey @J-Son89, this issue is still relevant for my physical devices (ios and android). The routes can't be found. I'm using the Android Studio emulator to test features related to asset sending. The issue does not reproduce on the Android Studio emulators

**Comment by J-Son89** [comment]
@briansztamfater, @VolodLytvynenko  this issue is still relevant should we close?

**Comment by VolodLytvynenko** [comment]
> @briansztamfater, @VolodLytvynenko this issue is still relevant should we close?

Can be closed
