### ISSUE TITLE
Incorrect display of collectible images from Status Go

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18657]
Reference to https://github.com/status-im/status-mobile/pull/18577#issuecomment-1911326449

### Steps:
1. Add as watch only the following account `0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E` (Note: Sometimes, collectibles may not be displayed immediately after initial account recovery. It is recommended to wait at least one minute after recovering and reloggin)
2. Open current watch-only account -> check collectibles tab

### Actual result:
Images of collections are shown instead of the expected collectible images.

https://github.com/status-im/status-mobile/assets/52490791/f1636176-4f75-40ec-85cd-b542083cf57f

### Expected result:
The images of collectibles should be displayed. The actual images of collectibles for the user can be found here https://opensea.io/chuqa/collected

### ENV:
Nightly [29 Jan 2024]

**Comment by ulisesmac** [comment]
Waiting for:

https://github.com/status-im/status-mobile/issues/19086 (Collectibles' new component implementation)

to get solved

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac, it seems that the issue https://github.com/status-im/status-mobile/issues/19086 has been resolved, and the current problem is no longer blocked. I have removed the 'blocked' label. Please feel free to add it back (block lablel) if there are other circumstances still preventing this PR from progressing

**Comment by ulisesmac** [comment]
@VolodLytvynenko thanks, yeah, it's ready to be taken.

But I believe this should be part of the issue that incorportates the new collectible component to the listing, since this one is very small.

If I recall correctly, @mmilad75  is working on it

@J-Son89 or maybe no one is working on it?

**Comment by J-Son89** [comment]
@ulisesmac - we have that component added now. Not sure what needs to be done here? 🤔

**Comment by ulisesmac** [comment]
@J-Son89 Nothing else, we can close this issue.
