### ISSUE TITLE
Wallet: Disable "From" networks in send & bridge flow

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18655]
As a user
I want to be able to disable some routes when sending a token

- [ ] Implement UI
- [ ] Implement functionality

Desings: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2396-514803&mode=design&t=TjDFfH5wuwKsAop1-4

**Comment by J-Son89** [comment]
It seems that this is a duplicate of:
https://github.com/status-im/status-mobile/issues/16974
Maybe we can just combine the two together as the other issue seems to have more details (but perhaps too much in some ways)

**Comment by OmarBasem** [comment]
@J-Son89 these are different issues. This issue is about disabling some network/route. The linked issue is about inputing specific amount for a network/route.

The linked issue is actually a duplicate of https://github.com/status-im/status-mobile/issues/18672

**Comment by briansztamfater** [comment]
@OmarBasem I am assigning myself this one and probably start working on it tomorrow, let me know if you did any progress on this so we don't collision 🙏

**Comment by OmarBasem** [comment]
@briansztamfater sure feel free to work on it. I haven't started on it
