### ISSUE TITLE
Push notifications end to end v1

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1866]
### User Story

As a user, I want to receive a push notification when a person in my contacts messages me and I have the app in background, so that I don't have to have the app in the foreground all the time.

### Description

*Type*: Feature

*Summary*:  If A has B as a contact, send a push notification to B.

Belongs with https://github.com/status-im/status-go/pull/327. No payload in notifications. Bindings only with iOS. Update: now it comes with Android bindings too.

### Notes to reviewers

Minimal v1 end to end. It will be expanded and cleaned up in future PRs.

- `fcm-token` is exchanged upon contact request and persisted in memory, just like name/status etc. To know a person is to have an address to them. In later iterations this might be replaced.
- Bindings for iOS. Signature will change in future iterations for status-go. Bindings for Android to trigger notifications will come later.
- Notifications trigger will be sent alongside a normal 1on1 message if `fcm-token` is present in 1on1 chats.

### Notes to testers

- Account A: Use iOS simulator or real iOS device.
- Account B: Use a notification-enabled device (Android real device, iOS real device, or Android genymotion with google-play services).
- A adds B as a contact. This way A gets B's `fcm-token` (like an address to someone's device).
- B backgrounds app.
- A sends message to B.
- B should now see a push notification that says they got a message.

**Comment by oskarth** [comment]
Did some QA and here's the current state as of latest build.

All new accounts, all have each other as contacts (some added via public key, some added with 'add to contact').

| Name      | Device  | Type           | Receive | Trigger | Regressions |
| ----------| ------- | -------------- | --------| ------- | ----------- |
| Gripping  | iOS     | Real 6s        | YES     | YES     | R2          |
| Timely    | iOS     | Simulator      | N/A     | YES     | R2          |
| Buttery   | Android | Real Honor 8   | NO*     | NO(R1)      | R1, R2      |
| Plastic   | Android | Simulator Geny | YES     | NO(R1)     | R1, R2      |

R1: Android NoSuchMethod FFI when trying to trigger PN, known issue and debugged with @roman - seems like it is because we have to versions of status-go in app (react-native-webview). UPDATE: New build triggered after noon CET time hopefully solves this.

R2: Trying to grok exactly what this is, but even if notifications appear messages can be lost. Even if in foreground. Will update table as I investigated more.

UPDATE: It appears R2 is just something with my Honor 8 setup and has been captured in other issues. R1 has been solved by latest build.

**Comment by asemiankevich** [comment]
What i have found so far: 

1. Android NoSuchMethod FFI
![image](https://user-images.githubusercontent.com/28752642/30538522-12379114-9c77-11e7-893f-c6f0e1a86ed1.png)

2. Send message from Android to iOS -> Receive Android NoSuchMethod FFI -> Send any message from iPhone to Android: message is not shown for Android in 1x1 chat. However the Huawei to iPhone messaging works still

**Comment by asemiankevich** [comment]
NOTE: the Android NoSuchMethod FFI is not reproducible in latest build https://i.diawi.com/cZHGBb

**Comment by oskarth** [comment]
Fixed in develop since a few weeks back, will be in 0.9.12
