### ISSUE TITLE
Broken profile icon on profile share screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18663]
**Steps:** 

1. Open profile share screen
2. Pay attention at the profile icon (located before username above the QR code)

**Actual result:** 

![photo_2024-01-29 16 55 36](https://github.com/status-im/status-mobile/assets/97245802/b69b4f53-9690-43e1-ab59-775e79761310)

**Expected result:** 

[Figma](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=2937-629712&mode=design&t=1UuKHoHAyE2SJ4b8-0)

<img width="378" alt="Shell for Mobile – Figma 2024-01-29 16-56-47" src="https://github.com/status-im/status-mobile/assets/97245802/eff74873-d4a3-4e88-80e9-a7c005e512e0">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
@pavloburykh looks like this issue has been resolved in this pr https://github.com/status-im/status-mobile/pull/18479. 

The designs however, show with identity ring which currently is not shown.

**Comment by mariia-skrypnyk** [comment]
> @pavloburykh looks like this issue has been resolved in this pr #18479.
> 
> The designs however, show with identity ring which currently is not shown.

Hi @jo-mut !

I've checked it on https://github.com/status-im/status-mobile/pull/18479 and it is really works there.
![photo_2024-02-07_16-08-11](https://github.com/status-im/status-mobile/assets/147824399/65377bcb-411b-4665-ad2d-2bc1cd795a47)

I'll close it. 
Thanks for help!
