### ISSUE TITLE
Wallet: add amount rules for Request transaction screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1867]
### Description

*Type*: Bug

*Summary*: For Request transaction screen now we do not have any field validation. 

#### Expected behavior

1. iOS/Android:

Currently max length of the amount: 15 characters including separator (./,). This is different from the amount user can type for /send command in chat. It should be consistent in both places and seems like Wallet is a place to adjust:
1.1 Expected: Amount before separator - seems like can be of any length or I can't find the limit
1.2 Expected: Amount after separator - should be not more than 18 digits after comma (e.g 0.123456789012345678). Currently, it's possible to enter only 13 digits after comma (e.g. 0.1234567890123)
1.3 "0" is now not allowed as a sum to send. In some cases, it's valid to send "0" (e.g https://contribute.status.im/sgt.html ), so it should be fine to request it too.
1.4 I can send request with empty amount field / invalid data in the field - should not allow to proceed to another screen as there is no sense in it

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
