### ISSUE TITLE
Wallet: send flow - routes - specific network amount

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18672]
As a user
I should be able to specify the amount to be sent from a specific network

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503852&mode=design&t=ixZfAk9WMF6w4KRx-4

**Comment by J-Son89** [comment]
same with this issue - https://github.com/status-im/status-mobile/issues/16930 
I think it's a duplicate so can we combine the necessary details and close one of them? 🤔

**Comment by OmarBasem** [comment]
@J-Son89 I think they are different issues (although related). This issue is for inputting a specific amount after you long-press on a network ([see design](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503852&mode=design&t=ixZfAk9WMF6w4KRx-4)). The other issue linked is changing input using that draggable bar after pressing on the configurations button on the bottom left.

**Comment by OmarBasem** [comment]
@J-Son89 this issue is a dup of another issue https://github.com/status-im/status-mobile/issues/16974

**Comment by OmarBasem** [comment]
Closing this one

**Comment by J-Son89** [comment]
Cheers @OmarBasem! 🙌🏼
