### ISSUE TITLE
Scanned eth address not pasted in 'Send to' screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18681]
### Steps:
1. Go to the 'Send to' screen
2. Open any non-default tab (for instance: 'saved' or 'my accounts')
3. type some data into the 'Send to' input field
4. Tap [x] to clear this field
5. Scan any valid eth address QR

### Actual result:
The scanned address is not pasted

https://github.com/status-im/status-mobile/assets/52490791/d8cc59c2-1f5b-40dd-b3ab-57761217052b

### Expected result:
The scanned address should be pasted into the 'Send to' input field

### ENV:
Nihglty [30 Jan 2024]

**Comment by J-Son89** [comment]
low priority - moving to February bugs https://github.com/status-im/status-mobile/issues/18611
