### ISSUE TITLE
Profile photo of a new contact is not dispayed after accepting contact request 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18686]
# Bug Report

## Problem 

The avatar of a newly added contact is not displayed until re-login.
Sometimes the avatar disappears after working with the app for some time, which makes the bug more visible, since it can occur at a random moment and requires re-opening the app.

It is not always reproducible at the first attempt.
There are logs below for the described case with adding a contact.

**Steps:**

1. UserA creates a profile and adds a profile photo on onboarding
2. UserB creates a profile
3. UserB sends a contact request to UserA
4. UserA accepts the request
5. UserB checks the chat and UserA's profile

Receiving a message doesn't help in this case. It only starts working fine after reopening the app. 

#### Expected behavior
Photo is displayed

#### Actual behavior
Blank space on Android / `x` icon on iOS in place of the user photo

https://github.com/status-im/status-mobile/assets/67952253/0f305bc2-73c3-4eed-8aaa-9d998e5be8a4

<img width="315" alt="Screenshot 2024-01-30 at 16 06 42" src="https://github.com/status-im/status-mobile/assets/67952253/89253727-a5d7-407a-83ce-9c8cd14fec8d">

### Additional Information

- Status version: nightly 31/01
- Operating System: Android, iOS
- Logs (UserB): 
[Status-debug-logs (86).zip](https://github.com/status-im/status-mobile/files/14421495/Status-debug-logs.86.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
Note: the issue is also sometimes reproducible when opening chat from push notification, or when the user changes their online status manually in Profile

**Comment by VolodLytvynenko** [comment]
Noticed that the [described issue](https://github.com/status-im/status-mobile/issues/18686#issue-2110442262) is more likely to be reproducible if the following steps are performed:
1. `UserA` goes offline
2. `UserB` sends a Contact Request to `UserA`
3. `UserA` goes online

### Actual result:
`UserB's` photo is not resolved for `UserA`

**Comment by qoqobolo** [comment]
Can't reproduce this issue on nightly 14/03 .
Closing for now
