### ISSUE TITLE
Incomplete data removal with Long Tap on 'Remove' button in 'Send Assets' Screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18685]
Follow up for https://github.com/status-im/status-mobile/pull/18594

### Steps:
1. Go to the 'send assets' screen.
2. Enter a few numbers.
3. Long tap on the 'remove' button.

### Actual result:
Only one character is removed.

https://github.com/status-im/status-mobile/assets/52490791/b2ab54f4-bb89-418b-8068-bbc4bf89bc0d

### Expected result:
Potential solutions:
- All characters should be removed one by one when the remove button is long-tapped (example below how it is implemented for Binance).

https://github.com/status-im/status-mobile/assets/52490791/cf872d95-d508-4ce8-a19d-75c547e5cdcf

- All characters should be removed at once (an example of how it works for Metamask).

https://github.com/status-im/status-mobile/assets/52490791/e3cb31e2-155f-495b-847f-5a7f06f8d82b

**Comment by J-Son89** [comment]
@pavloburykh - this seems low priority for the release so moving to bugs for February 👍 https://github.com/status-im/status-mobile/issues/18611
