### ISSUE TITLE
'Slide to Send' Button not appearing for ERC-1155 type collectibles

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18691]
Follow up for https://github.com/status-im/status-mobile/pull/18679#issuecomment-1920109079

### Steps:
1. Recover the user with available ERC-1155 collectibles
2. Tap 'send' -> paste valid eth address -> Tap 'collectibles' tab -> Select ERC-1155 collectible.

### Actual result:
The 'Slide to send' button does not appear when the collectible is opened.

https://github.com/status-im/status-mobile/assets/52490791/8cf85c1d-4e9a-4955-8761-b12ab384430c

### Expected result:
The 'Slide to send' button should appear after ERC-1155 collectible is opened.
![image](https://github.com/status-im/status-mobile/assets/52490791/07a52233-8d4e-4fe5-83e5-1e3969c7033a)

### Logs:
[logs (2).zip](https://github.com/status-im/status-mobile/files/14115139/logs.2.zip)

### Additional info:
Feel free to reach out to me directly if you need the seed phase of user with available ERC-1155 collectibles

**Comment by ulisesmac** [comment]
@VolodLytvynenko Is this still happening?
I think now it's been fixed.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko Is this still happening? I think now it's been fixed.

@ulisesmac Yes. It is fixed. thanx
