### ISSUE TITLE
'Send' button on collectible not navigating user to sent to page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18695]
### Steps:
1. Recover the user with available  collectibles
2. Open any collectible
3. Tap 'send' button

### Actual result:
The user is not navigating to  "sent to" screen

https://github.com/status-im/status-mobile/assets/52490791/271b2271-6ece-4310-b1cc-f4b42e782b5e

### Expected result:
The user is navigated to  "sent to" screen 

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-315956&mode=design&t=1eIZ6rkdXhrEplJ8-0

### Additional info:
Feel free to reach out to me directly if you need the seed phase of user with available ERC-1155 collectibles

**Comment by mmilad75** [comment]
It's already fixed in the latest branch of `develop`
