### ISSUE TITLE
[Android] 'Sending...' screen skipped after 'Slide to Send'

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18704]
### Steps:
1. Go to send assets page
2. Send tokens
3. Check if 'Sending...' screen is shown after 'Slide to send' is slided

### Actual behavior:
The 'Sending...' screen is omitted, and the 'Transaction confirmed' screen is immediately shown after sliding the 'Slide to send' button.

https://github.com/status-im/status-mobile/assets/52490791/49094725-69ad-4a57-bcc8-69843e54745c

### Expected behavior:
'Sending...' screen is shown after sliding 'Slide to send' button

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7701-158136&mode=design&t=IzMtWOxco99EZfij-0

### Additional Information
- Status version: nightly 
- Operating System: Real device Pixel 7a, Android 14

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14139018/Status-debug-logs.1.zip)

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - I tried on Pixel 7a (Android 14). I could see both statuses. 

| Sending... | Confirmed |
| -- | -- |
|<img width="300" src="https://github.com/status-im/status-mobile/assets/19339952/2e1eb48f-39d5-4787-b063-6cd9caba807e" /> | <img width="300" src="https://github.com/status-im/status-mobile/assets/19339952/ae76e0b9-555c-4553-aaa5-b273e17e83ca" />|

Can you try once again and let me know if the issue persists?

**Comment by VolodLytvynenko** [comment]
@smohamedjavid I can't reproduce it anymore. It's strange, maybe it's fixed or there are some other conditions required for this issue, which I haven't figured out yet. Thanks for checking
