### ISSUE TITLE
Wallet: error null is not an object received for Send screen on iOS [1839]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1870]
### Description

*Type*: Bug

*Summary*: Error null is not an object received when clicking Send button in new wallet

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/30496166-42fa8634-9a57-11e7-896c-cde5447cb641.png)

build: 0.9.11d100-1557.100

https://status-im.slack.com/archives/G53FWGDCM/p1505425804000081

**Comment by asemiankevich** [comment]
This issue is fixed in ` 0.9.11d117-1557.117`

**Comment by sla-shi** [comment]
@asemiankevich closing this?

**Comment by asemiankevich** [comment]
@sla-shi yes. Closed.
