### ISSUE TITLE
"Community admins will review your request" message after joining community

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18706]
# Bug Report

Bug is reproducible only with communities that have no permissions. 

### Reproduction

1. UserA: create a community (**without any permissions**), invite UserB
2. UserB: join the community (UserB: accept the membership request if manual approval is required)
3. UserA: check the community screen after joining

#### Expected behavior
No "Community admins will review your request" message

#### Actual behavior
<img width="316" alt="Screenshot 2024-02-02 at 12 45 05" src="https://github.com/status-im/status-mobile/assets/67952253/4b94a725-d7a1-40f1-9ec3-f7ccd3d1e22d">

### Additional Information

- Status version: nightly 2/01
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
FYI @BalogunofAfrica, this was a regression from merge commit 4633fc22ed02f6f08188b91aaeb36524a74be21d. 

Probably the ~fix~ bug is due to the missing `joined` check.

```diff
-     (when (not (or joined pending? token-permissions))
+     (when (not (or pending? role-permissions? can-join?))
```

**Comment by pavloburykh** [comment]
@BalogunofAfrica please note that the bug is reproducible only with communities that have no permissions.
