### ISSUE TITLE
Crash on onboarding on iPhone SE

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18719]
# Bug Report

## Problem 

The app always crashes on onboarding on iPhone SE.
Sometimes it happens right after confirming the password (and the user is not created in this case), sometimes on the generating keys step, and sometimes you can get to the last steps, but the animations and transitions between screens become very laggy (more visible in the second video).

As @cammellos  suggested, we can try disabling some onboarding animations/parallax videos to see if they are the cause of the crash.

https://github.com/status-im/status-mobile/assets/67952253/bf1bf4b1-8983-4c18-b4b7-0f3acb56eb05

https://github.com/status-im/status-mobile/assets/67952253/556bfb80-7516-48f8-8133-9291a001724b

### Reproduction

The issue is only reproducible on my real device iPhone SE. 

1. Install Status on SE
2. Create a profile

### Additional Information

- Status version: nightly 5/02
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
Hmm looking at the video it does seem like the app is struggling for resources.
Would be nice If we had some logs OR a way to reproduce ( other than having an iPhone SE device handy)

I'll try to see if this is reproducible on iPhone SE Simulators, but I doubt I'll re-rproduce the crash..

**Comment by siddarthkay** [comment]
@qoqobolo : could you also find out the iOS version in that phone, that info could come handy when we try to reproduce this crash.

**Comment by qoqobolo** [comment]
> Would be nice If we had some logs

Unfortunately, we don't know how to get crash logs from ios :(
we tried to find out many times, but no one could help with this yet.

> Hmm looking at the video it does seem like the app is struggling for resources.

Yeah I checked my storage, it doesn't look full
<img width="407" alt="Screenshot 2024-02-05 at 11 17 06" src="https://github.com/status-im/status-mobile/assets/67952253/53fe1def-23cd-435b-b765-3b128bdf9c93">

> could you also find out the iOS version in that phone, that info could come handy when we try to reproduce this crash.

Sure, it's iOS 17.2.1

**Comment by qoqobolo** [comment]
@siddarthkay forgot to mention, sometimes onboarding becomes laggy (barely noticeable) on faster devices: 13 iPhone (17.2.1), 12 mini (17.2.1), and 11 pro max (17.2.1). 

I most often notice this on 12 mini when I tap the `Start using Status` button, sometimes it seems that I don't tap it, so I tap it again and in the end I see that I tapped it twice (this screen slides twice before the home page opens). Unfortunately, I can't catch it on video yet :(

**Comment by siddarthkay** [comment]
Hmm double taps should be fixed with : https://github.com/status-im/status-mobile/pull/18478
I'll do some automated benchmarking of onboarding flow using flashlight and try to find these lags.
I also have an old iPhone 11 I will try there as well. 
Thank you

**Comment by qoqobolo** [comment]
Hey @siddarthkay, my SE stopped crashing on onboarding 👀
Closing the issue for now, let's see how it goes
