### ISSUE TITLE
Refetch collectibles without images

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#18710]
# Problem

Currently some collectibles arrive from `status-go` without images. There is a possibility that on `status-go` side they are still in process of fetching.
In mobile, we filter out such collectibles within `:wallet/store-collectibles` event and do not display them to users.
Within the scope of this issue, an assignee needs to clarify with `status-go` team why collectibles can arrive without any image URLs and if they need to be refetched later - that mechanism should be implemented.

Can overlap with #18609

**Comment by vkjr** [comment]
@ulisesmac, could you please take a look if I correctly described the issue and add any relevant information? Thanks!

**Comment by ulisesmac** [comment]
Yeah! it's totally correct!
Thanks for creating the issue!

**Comment by ulisesmac** [comment]
The solution will be the same to solve:
- https://github.com/status-im/status-mobile/issues/18657

**Comment by ulisesmac** [comment]
I investigated this and the Wallet Desktop team is looking for a solution, in the meantime this is blocked and the performance related issues are blocked too, since it's still unsure what are the changes and we might change the data structure

**Comment by ulisesmac** [comment]
An update:

According to desktop team, non-minted collectibles should be completely fetched, but our providers sometimes aren't returning the data, this might be due to various reasons, they are investigating the issue.


Since collectibles don't need to be refetched/updated to receive their images, this issue is no longer valid.
