### ISSUE TITLE
Wallet: recovered user can not create both types accounts untill all data recovered

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18720]
# Bug Report

## Problem 
[comment]: # (A problem description)

In both scenarios: add Account and watch only Аccount user tap on "Add..." button and nothing happens

#### Expected behaviour
User can create additional wallet accounts of both types

#### Actual behaviour
User can not finish accounts creation

### Reproduction

1. Recover a user account that contains account/assets/communities
2. Go through onboarding flow
3. Open Wallet 
4. Try to create Account
5. Try to create watch only Account 

https://github.com/status-im/status-mobile/assets/147824399/f3bd9da1-f1cf-4e6e-b28f-097c0e452082

### Additional Information

- Status version: nightly from 5th of February
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by VolodLytvynenko** [comment]
will be resolved after fixing of https://github.com/status-im/status-mobile/issues/18875
