### ISSUE TITLE
Wallet: no special image placeholder for collectibles without an image

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18721]
# Bug Report

## Problem 
[comment]: # (A problem description)
User is scrolling collectible list and blank spaces appears. For user it is unclear if there should be something or it's some kind of extra space there.

#### Expected behaviour
No blank spaces, show the special image placeholder for collectibles without an image

#### Actual behaviour
User see blank spaces while scrolling collectible list

### Reproduction

1. Recover a user account with a substantial number of collectibles (be aware, collectibles sometimes are not displayed. You need to wait at least 1 minute after recovering and relogin
2. Add watch only account 0x8d2413447ff297d30bdc475f6d5cb00254685aae
3. Open "collectibles" tab to see all collectibles available for all added adresses
4. Scroll through the collectibles list consistently.

https://github.com/status-im/status-mobile/assets/147824399/b83a588b-1346-4b10-bd56-d5b5aab353c4

### Additional Information

- Status version: nightly from 5th of February
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
This issue is handled in new designs and will be handled as a separate feature. See: 
https://github.com/status-im/status-mobile/issues/19086
