### ISSUE TITLE
Issue - Accent color is not applied to the avatar placeholder in chat history and contact list

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#18733]
follow up for issue 2 and 3 in [#8517#issuecomment-1914867210](https://github.com/status-im/status-mobile/pull/18517#issuecomment-1914867210)

- New accent color is not applied to the avatar placeholder in chat history
- New accent color is not visible for my contact in chat

**Comment by mohsen-ghafouri** [comment]
It requires a bit of work on status-go, contact doesn't have customization-color at all. as it is not a priority, I will work on high priority ones

**Comment by yqrashawn** [comment]
note: no customization-color for contact

code might related/starting point:
- type ContactUpdate struct https://github.com/status-im/status-go/blob/23ee898754f71341dc53e71657ef0633165f7bd3/protocol/protobuf/contact.pb.go#L94
- type Contact struct https://github.com/status-im/status-go/blob/23ee898754f71341dc53e71657ef0633165f7bd3/protocol/contact.go#L84

**Comment by siddarthkay** [comment]
cc @flexsurfer
