### ISSUE TITLE
Watch-Only Addresses Available for Bridging

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18737]
### Steps:
1. Open a regular account.
2. Navigate to the bridge ->  tap on the avatar in the top-right corner.
3. Check the available accounts for bridging.

### Actual Result:
Watch-only accounts are shown and can be selected for bridging.

https://github.com/status-im/status-mobile/assets/52490791/eb726820-2192-454e-a4c8-c2c4569af8c9

### Expected Result:
Watch-only accounts should not be displayed as options for bridging

**Comment by OmarBasem** [comment]
@J-Son89 I think none of the actions "Buy, Send, Receive, Bridge" should be available for watch-only accounts?

**Comment by J-Son89** [comment]
Yes you are right, however I think receive is possible because we have the qr code possible to show for watch only accounts - although on the receive page itself there is no account switcher button.

**Comment by OmarBasem** [comment]
@J-Son89 hmm.. But the word "receive" implies that the user owns the account which may not be the case for watch-only accounts

**Comment by J-Son89** [comment]
True!

**Comment by J-Son89** [comment]
@OmarBasem - is this issue still relevant? Can we prioritise if so as it's been here a while.

**Comment by VolodLytvynenko** [comment]
@J-Son89 Still reproducible on latest develop

**Comment by OmarBasem** [comment]
@J-Son89 @VolodLytvynenko should the send action also be removed for watch-only accounts?

**Comment by VolodLytvynenko** [comment]
> @J-Son89 @VolodLytvynenko should the send action also be removed for watch-only accounts?

@OmarBasem Yes, it should. As far as I know, the send action was removed. Are there still places where the send action is available for watch only?
