### ISSUE TITLE
Predefined account names Incorrectly set in edit flow

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18735]
### Steps:
1. Create at least 2 ETH accounts (default or watch-only).
2. Navigate to the edit flow of the first account and rename it (e.g., "test1").
3. Go to the edit flow of the second account.
4. Check the predefined name of the second account.

### Actual result:
The predefined name of the second and subsequent accounts is set to the name of the first account ("test1").

https://github.com/status-im/status-mobile/assets/52490791/9a5359d2-3eb1-4613-a450-24589d237d14

### Expected result:
The predefined name of the second and subsequent accounts should be set to the initial name with which each account is created, not copying the name of the first account.

### ENV:
Nightly [6 Feb 2024]

**Comment by OmarBasem** [comment]
@VolodLytvynenko I am not able to reproduce this bug on latest develop. Is it still reproducible for you?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I am not able to reproduce this bug on latest develop. Is it still reproducible for you?

hi. @OmarBasem  The issue is not reproducible anymore. Thank you for checking it
