### ISSUE TITLE
ENS resolution depends on build instead of testnet mode

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18739]
### Problem
Currently, ENS resolution is tied to the builds. In PRs, testnet ENS addresses are resolved, regardless of the testnet toggle's state. In Nightly builds, mainnet ENS addresses are resolved, regardless of the testnet toggle. The intention of this issue is to make ENS resolving related to the testnet toggle

### Steps:
1. Open Nightly
2. Enable the Testnet toggle
3. Go to the wallet -> open any eth address -> tap 'send'  
4. Type any eth address (example: qoqobolo.stateofus.eth) on "Send to" screen

### Actual result:
ENS resolution is not dependent on the selected selected testnet toggle

https://github.com/status-im/status-mobile/assets/52490791/59da6842-b641-46e7-9af5-e0d04ad7e3eb

### Expected result:
The ENS resolving depends on the selected  testnet toggle in Advanced -> testnet mode
- If testnet toggle is enabled, then testnet ENS should be resolved
- If testnet toggle is disabled, then mainnet ENS should be resolved

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-192865&mode=design&t=MMs1GoYDn4hNtbL6-0

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - We decided to remove the `Network` and `Network Info` from Advanced Settings as it was used in the old wallet and it's creating confusion with the new wallet.

Ref: @J-Son89's PR https://github.com/status-im/status-mobile/pull/18955

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - We decided to remove the `Network` and `Network Info` from Advanced Settings as it was used in the old wallet and it's creating confusion with the new wallet.
> 
> Ref: @J-Son89's PR #18955

@smohamedjavid Thank you. I think current issue is not valid anymore

**Comment by VolodLytvynenko** [comment]
Reopens this issue with updated [description](https://github.com/status-im/status-mobile/issues/18739#issue-2122574947)
