### ISSUE TITLE
[Android] Frozen login screen occurs randomly upon logout

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18738]
Unfortunately, there are no exact steps to reproduce this issue. It seems to occur randomly and very rarely. Hopefully, the logs can help understand what's going on.

### Steps:
1. The user is logged in for a while.
2. Log out.
3. Check the login screen.

### Actual result:
The login screen becomes frozen, and the buttons are unresponsive.

[Status-debug-logs - 2024-02-21T125126.144.zip](https://github.com/status-im/status-mobile/files/14358374/Status-debug-logs.-.2024-02-21T125126.144.zip)

https://github.com/status-im/status-mobile/assets/97245802/e01c9c92-b99d-457c-bc00-1335dfac9bb7

### Expected result:
The buttons on the login screen should remain responsive after logout, allowing the user to interact with them.

### Device:
Real device: Pixel 7a, Android 13

**Comment by qfrank** [comment]
```
02-21 12:39:02.219 32605 32754 D ReactNativeJS: 2024-02-21T10:39:02.211Z DEBUG [status-im.common.signals.events:91] - Event  node.stopped  not handled
...
02-21 12:39:04.511 32605 32754 D ReactNativeJS: 2024-02-21T10:39:04.507Z DEBUG [status-im.contexts.profile.login.events:166] - [signals] node.login error nil
```

it seems status-go performed well in this case since frontend received signal `node.login` , i guess proberbly relate to frontend, i'll remove my assignment cc @cammellos

**Comment by siddarthkay** [comment]
Thanks! @qfrank  I'll try to recreate crash with Android Studio + Logcat.

**Comment by churik** [comment]
Descoping for now, as there are no clear steps to reproduce and according to updated priorities
cc @cammellos

**Comment by VolodLytvynenko** [comment]
I think this issue has gone
