### ISSUE TITLE
Communities: "Become an admin" permission issues

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18746]
# Bug Report

Found in this branch: https://github.com/status-im/status-mobile/pull/18530

### ISSUE 1: The `become an admin` permission is displayed as `become a member` for the user who does not have enough tokens to become an admin

That is a non-token gated community becomes a gated token + a permission is displayed, which should not be displayed if the user does not hold enough required tokens

**Steps:**
1. Desktop: create a community, add permission: `Anyone who holds 1 ETH is allowed to become an admin`
<img width="421" alt="Screenshot 2024-02-07 at 13 40 23" src="https://github.com/status-im/status-mobile/assets/67952253/cfc691f6-1d76-4fd2-822e-f3e9a201351b">

2. Desktop: Invite mobile user who has <1 ETH 
3. Mobile: open the community 

**Expected result:** the community is NON-token-gated for the user, no permissions are shown on the `Join community` page
**Actual result:**
<img width="371" alt="Screenshot 2024-02-07 at 13 44 24" src="https://github.com/status-im/status-mobile/assets/67952253/3c3f20bf-4467-4dc2-b274-a55ecf50829e">

### ISSUE 2: The `become an admin` permission is displayed as `become a member` for the user who HAS enough tokens to become an admin

**Steps:**
1. Desktop: create a community, add permission: `Anyone who holds 0.0001 ETH is allowed to become an admin`
 
<img width="432" alt="Screenshot 2024-02-07 at 13 55 46" src="https://github.com/status-im/status-mobile/assets/67952253/a439f3d2-c396-45e5-918a-5414f7b6174e">

2. Desktop: Invite mobile user who has 0.0001 ETH or more
3. Mobile: open the community 

**Expected result:** mobile user sees`You're eligible to join as Admin` 
**Actual result:**

<img width="317" alt="Screenshot 2024-02-07 at 13 59 26" src="https://github.com/status-im/status-mobile/assets/67952253/bffbe4d0-e802-4814-9b8d-15ffc3467ceb">

### Additional Information

- Status mobile version: https://github.com/status-im/status-mobile/pull/18530
- Desktop version: https://ci.status.im/job/status-desktop/job/nightly/179/
- Operating System: Android, iOS

**Comment by pavloburykh** [comment]
### ISSUE 3 "You must hodl" is missing when user is not eligible to join

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7828-524576&mode=design&t=spSVfmYBSrgOucKp-0)

<img width="264" alt="Communities for Mobile – Figma 2024-02-08 19-56-45" src="https://github.com/status-im/status-mobile/assets/97245802/750bad04-35d3-45f9-abc4-0cde760005b8">

**Actual result:**

![photo_2024-02-08 20 15 17](https://github.com/status-im/status-mobile/assets/97245802/d1ced059-210d-4235-82f9-e2b1db0d5598)

**Comment by pavloburykh** [comment]
fixed by https://github.com/status-im/status-mobile/pull/18766
