### ISSUE TITLE
Account selection: error and app freezing when deselecting account one by one

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18753]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/67952253/68e94bab-7c3d-4f4f-87e7-5e0a20bab0f5

### Reproduction

1. Create several accounts
2. Go to the account selection page
3. Start deselecting accounts one by one

#### Actual behavior
Error occurs and the app freezes 

#### Logs

[Status-debug-logs (85).zip](https://github.com/status-im/status-mobile/files/14199678/Status-debug-logs.85.zip)

### Additional Information

- Status version: https://github.com/status-im/status-mobile/pull/18530
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @qoqobolo, Thank you very much for finding this issue.

Error occurs when we deselect account which makes us eligible for joining.
I fixed the bug and error don't occur anymore.

But even if there is no error, app is in weird state at the time. Please can you check out pr and let me know what should be the expected behavior. Is no error enough?

(Also please can you share designs related to these files. Thank you)

**Comment by Parveshdhull** [comment]
pr https://github.com/status-im/status-mobile/pull/18759

**Comment by qoqobolo** [comment]
> Error occurs when we deselect account which makes us eligible for joining.

Oh interesting, that was my first thought but I failed to reproduce it this way for some reason. 
Thanks for making it clear and for the fix @Parveshdhull !

> But even if there is no error, app is in weird state at the time

Could you elaborate please on what you mean by weird state?
This missing icon? 
<img width="311" alt="Screenshot 2024-02-08 at 12 56 12" src="https://github.com/status-im/status-mobile/assets/67952253/6157f971-1cf0-4443-a2ab-e9a506645558">

> Also please can you share designs related to these files

Sure, here it is 
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-288058&mode=design&t=wQ3Qe2ZFSVFQCUFD-4

**Comment by Parveshdhull** [comment]
Hi, Thank you very much for designs, by weird state I mean (Once we deselect account with required token)
1. In `Addresses for permissions` screen, should we keep showing `Eligible to join as Member` or hide it, or instead display `You are not eligible anymore.`
2. In `Request to join` screen there are no indicator about eligibility but `Slide to request to join` is still enabled. Should we disable it?
3. Once we deselect required account, overview screen just shows `You are not eligible to join` and don't let accounts to be selected again. Until community reopened.

Maybe they only looks confusing to me, or they are still in under development. Please let me know if removal of error is enough? In that case PR is ready :)

**Comment by Parveshdhull** [comment]
> Oh interesting, that was my first thought but I failed to reproduce it this way for some reason.

Yes, also in my case sometime error only logged in metro without any crashes or freezing.

**Comment by Parveshdhull** [comment]
> 1. In Addresses for permissions screen, should we keep showing Eligible to join as Member or hide it, or instead display You are not eligible anymore.

Ok, in this case we should display `These addresses don’t contain tokens needed to join` ([ref](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-290601&mode=design&t=qQwvovGmDNtZ9Hnx-0))

**Comment by Parveshdhull** [comment]
And disables confirm button. Cool I will disable this button and this will solve other 2 issues.

**Comment by qoqobolo** [comment]
> Cool I will disable this button and this will solve other 2 issues.

Thank you very much @Parveshdhull!
Yes the account selection feature is still under development, and it will be a great help from your side to the Ledger Drops crew who is working hard on it!
We've just started testing the [branch](https://github.com/status-im/status-mobile/pull/18530) and there is still a lot of work to be done
