### ISSUE TITLE
Add /location, /send, /request sending flow to Push notifications

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1876]
### User Story

As a user I want to receive push notifications when sending /location, /send, /request messages in 1x1 chat

### Description

*Type*: Feature

*Summary*:  In terms of implementation of Push notifications feature I would like to see the notifications when sending `/location, /send, /request` command in 1x1 chat. Its not implemented yet 'cause its separate flow different from text messagin flow. I spoke to @oskarth and there was a decision made to have it implemented as well.

#### Expected behavior
User is able to receive `/location, /send, /request` message within Push notification on his device

#### Actual behavior
For now this flow is not implemented

### Reproduction

- Open Status
- Create 1x1 chat with someone from your contacts list
- Send `/location, /send, /request` message and check receiver is able to see the PN

**Comment by oskarth** [comment]
I believe this is related to a point @janherich brought up in https://github.com/status-im/status-react/pull/1872#discussion_r139356028 which is that notifications are sent `send-message` whereas, I think, locations are sent using `send-command`. This is a good and hopefully not too difficult enhancement that anyone should be able to make. I agree it's medium priority but that it should be done at some point soonish.

**Comment by annadanchenko** [comment]
now PNs are shown for send and receive messages in 1:1 chats. location is removed
