### ISSUE TITLE
Inability to set up ENS on 1.20 and in legacy settings in new app

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18763]
### Steps:
1. Recover the user with available ENS purchased on testnet https://app.ens.domains/
2. Navigate to Profile -> Legacy Settings -> Advanced -> Set up available testnet  -> enable Testnet mode
3. Go to 'Your ENS Name' section -> Get Started.
4. Enter your testnet ENS

### Actual result:
'Username does not belong to you' message is shown

![image](https://github.com/status-im/status-mobile/assets/52490791/c72c533f-19b2-4b9f-9285-0567ce92cef9)

### Expected result:
The testnet ENS should be successfully recognized and accepted

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14209902/Status-debug-logs.1.zip)

**Comment by churik** [comment]
This is reproducible on 1.20 on mainned with names `.eth` and names `.stateofus.eth`

**Comment by churik** [comment]
I'll close this in favour of https://github.com/status-im/status-mobile/issues/20468
