### ISSUE TITLE
Button colors have become darker

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18762]
# Bug Report

## Problem 

Most likely regression from https://github.com/status-im/status-mobile/pull/18517
@mohsen-ghafouri could you check what colors are actually correct, please?

![photo_2024-02-08_13-04-43](https://github.com/status-im/status-mobile/assets/67952253/b2d25127-7a51-48a1-a102-7e66c3c9a91c)

![image](https://github.com/status-im/status-mobile/assets/67952253/911cf88d-354a-4cea-9aff-78cc66b1eaad)

#### Expected behavior
colors are lighter

#### Actual behavior
colors are too dark

### Additional Information

- Status version: nightly 08/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mohsen-ghafouri** [comment]
Thank you @qoqobolo for reporting this issue. I can't see any changes in that PR that effect this kind of issue. probably some changes in button component as you can see the issue also in notification center. 

I will investigate about the issue after my current task

**Comment by qoqobolo** [comment]
@mohsen-ghafouri oh okay, it just looked related and matched the merge time of that PR, but apparently it’s just a coincidence. 
Thank you for looking into it 🙏
