### ISSUE TITLE
Wallet: cursor jumps to the right when user enters incorrect token amount

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18779]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
No cursor jumping. In any case cursor should be placed to the right of entered amount.

#### Actual behavior
Cursor jumps to the right when user enters incorrect token amount.

https://github.com/status-im/status-mobile/assets/147824399/3a8f98b8-8c3a-4ef3-ae22-91235deac039

### Reproduction

1. Go to Wallet -> Send
2. Enter any existing address
3. Put "9999999999" value into the Amount field

### Additional Information

- Status version: nightly 09/02
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
Just sharing an easier approach to handling the amount input and preventing further bugs.

We can make the text input inside the `token-input` component to be non-editable.
https://reactnative.dev/docs/0.72/textinput#editable

This would result in: 
- No cursor is shown, and the user is not allowed to edit from the middle of the text
- No jumping of cursors

This restricts the user actions to our custom keyboard (we display it on the screen) and keeps the page bug-free. 
This is a common behaviour on most banking/crypto applications.

**Comment by J-Son89** [comment]
@mmilad75 - this issue has been around for a while now. Maybe we can prioritise it or if you don't have capacity perhaps someone else could take it? 🙏

**Comment by OmarBasem** [comment]
@mmilad75 is this still an issue?

**Comment by OmarBasem** [comment]
@mmilad75 if you are not currently/actively working on this issue better unassign yourself

**Comment by J-Son89** [comment]
@vkjr - I saw your recent pr - is this still relevant?
https://github.com/status-im/status-mobile/pull/20564

**Comment by vkjr** [comment]
Not relevant because the cursor is not there anymore.
