### ISSUE TITLE
"times() not number: null" error occurs after returning from the backround 

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18777]
Unfortunately, the provided steps do not accurately reproduce the issue. Hopefully, the logs can help to understand what's going wrong

### Steps:
1. Recover the user with available assets.
2. Go to the 'Select assets' page.
3. Put the application in the background.
4. Wait for at least 10 - 15 minutes.
5. Return from the background.

### Actual result:
The "times() not number: null" error occurs after returning from the backround 

https://github.com/status-im/status-mobile/assets/52490791/8a9ac532-8eed-4cc5-a9e4-96affd03a4dd

### Expected result:
No error should occur after returning from the background.

### Logs:
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/14223505/Status-debug-logs.2.zip)

**Comment by ulisesmac** [comment]
As mentioned here:
https://github.com/status-im/status-mobile/pull/19065#issuecomment-2010114382

the solution has been merged
