### ISSUE TITLE
Account selection: show correct token balance on the relevant tokens screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18771]
# Bug Report

## Problem 

The token balance is displayed as 0 if the actual token balance is <0.001 (? not sure about the exact reason here)

We should display the real token balance. 

Discussion [here](https://discord.com/channels/@me/1176849358147293194/1205469728072667226)

![image](https://github.com/status-im/status-mobile/assets/67952253/69994f6e-27d6-41e8-8116-8689f5a3f84c)

#### Expected behavior
Balance in relevant tokens is shown as `0.00022392 WBTC`

#### Actual behavior
Balance is 0

### Reproduction

For the case from the screenshot
1. Desktop: set permission 0.0002 WBTC (you should have them on your balance on mobile user)
2. Mobile: open the account selection page

### Additional Information

- Status version: nightly https://github.com/status-im/status-mobile/pull/18530
- Operating System: Android, iOS

cc @ilmotta

**Comment by pavloburykh** [comment]
fixed by https://github.com/status-im/status-mobile/pull/18806
