### ISSUE TITLE
Letter-spacing on Android

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1879]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a designer I want to be able to use letter spacing

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
Currently the letter-spacing attribute is not available on Android

Blocked by https://github.com/facebook/react-native/pull/13877
https://github.com/facebook/react-native/pull/13199

Most promising PR:
https://github.com/facebook/react-native/pull/17398

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf9327beed210922f5b71644ba1c7c59a057f23d4c13412c03bd1fab768ccdd10](https://etherscan.io/tx/0xf9327beed210922f5b71644ba1c7c59a057f23d4c13412c03bd1fab768ccdd10)
