### ISSUE TITLE
Wallet - Import private key flow - Add UI for Key Pair Name

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18817]
Add the UI for this screen.
Designs:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-595415&mode=design&t=d987JsFas3Z5NQ67-4

<img width="140" alt="Screenshot 2024-02-14 at 10 49 32" src="https://github.com/status-im/status-mobile/assets/22799766/41d4cb36-8e58-408e-b421-a3c26af7f09b">

This page should make use of [status-im.common.floating-button-page.view :as floating-button-page] to help with the device on smaller screens.

Connect up the re-frame data model so that the data is stored in reframe for when this page navigates to the next page - back to create account page - (the UI on that page needs some adjustment but that is a separate issue)

**Comment by Rende11** [comment]
I would like to implement it.

**Comment by OmarBasem** [comment]
@J-Son89 closing this issue as we already have this screen

**Comment by J-Son89** [comment]
@OmarBasem - there is an open pr for this issue in progress.
It connects this page in the flow and handles some other details. 
Thanks for monitoring the issues though 🙏
