### ISSUE TITLE
Wallet - Add UI for Import private key screen

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18816]
This is the first issue of the Feature Epic.

** Add a new feature flag for this feature ** 
Designs
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-595431&mode=design&t=d987JsFas3Z5NQ67-4

Visual Ref:
<img width="132" alt="Screenshot 2024-02-14 at 10 43 57" src="https://github.com/status-im/status-mobile/assets/22799766/1e7138f6-dd83-479c-b01e-42e5d40b5198">

This page should make use of `[status-im.common.floating-button-page.view :as floating-button-page]` to help with the device on smaller screens.

Connect up the re-frame data model so that the data is stored in reframe for when this page navigates to the next page ( doesn't need to navigate yet - following issue adds the next page)

**Comment by Pau1fitz** [comment]
@J-Son89 I can pick this one up

**Comment by Rende11** [comment]
I would like to implement it
