### ISSUE TITLE
The colors of elements in 1-1 chat are not dependent on the color preference of the receiving user

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18829]
### Steps:
1. User A sets a particular color during onboarding (e.g., yellow).
2. User B opens a 1-1 chat with User A.

### Actual result:
`User B` sees the elements such as 'pin messages' and 'mute chat' sections within the chats as always blue, regardless of `User A's` selected color.

### Expected result:
`User B` should see the elements within the chats corresponding to the selected color of `User A`.

Refferencе 
https://discord.com/channels/624634427930312714/975775548007678033/1207409033225445427

**Comment by clauxx** [comment]
@jo-mut are you still working on this? asking cause it was added as part of the chat crew recently.

**Comment by jo-mut** [comment]
@clauxx I have been investigating this. Looks like it need some work on status-go which i have not yet started working on. I would probably just un-assign myself so i can focus a lot more on work in the communities crew

**Comment by jo-mut** [comment]
we dont currently save the receiver's color in app-db and its not implemented on status-go

**Comment by clauxx** [comment]
Depends on https://github.com/status-im/status-mobile/pull/19087 and https://github.com/status-im/status-go/pull/4869

**Comment by seanstrom** [comment]
Can we close this issue?
I think #19087 resolved this issue, and some other color fixes seem to be happening in #19503

cc @yqrashawn @VolodLytvynenko

**Comment by clauxx** [comment]
@seanstrom yeah this was already done

**Comment by yqrashawn** [comment]
It's done in the way that the color is not always blue now
although the color is incorrect and there's an issue for it https://github.com/status-im/status-mobile/issues/19503

**Comment by clauxx** [comment]
> It's done in the way that the color is not always blue now although the color is incorrect and there's an issue for it #19503

could you add this issue to your PR so that it's closed when it's done?

**Comment by yqrashawn** [comment]
added this issue number to the PR
