### ISSUE TITLE
The avatar is on the wrong place in the opened 1-1

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18827]
### Steps:
1. Open 1-1 with messages
2. Scroll a bit to the down
3. Check avatar

### Actual result:
The avatar is located above the display name
![image](https://github.com/status-im/status-mobile/assets/52490791/34e786fd-52c4-4680-b821-f04e0ad4a7f7)

### Expected result:
The avatar is located on the same line as a display name
![image](https://github.com/status-im/status-mobile/assets/52490791/9d96d97b-8ff9-47e6-90d0-c7f8f40efbfb)

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8451-543358&mode=design&t=i0Ojj0uIoJWoDvQP-0

### ENV:
Nightly [14 Feb 2024]

**Comment by BalogunofAfrica** [comment]
Hi @jo-mut, are you working on this task? 

It was added to the chat crew recently

**Comment by jo-mut** [comment]
@BalogunofAfrica I had started working on it but you can take it up from me so i just focus on communities crew
