### ISSUE TITLE
Create more communities in e2e (x86_64) builds

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#18825]
# Problem

In order to check token gated communities and communities with permissions by e2e tests we need an ability to create such communities in e2e mobile builds. Now we can create open and closed communities in e2e builds but we need to extend this functionality with the options described below.

## Implementation
When clicking the Plus button on the Communities view we should see the next options:

- [ ] _Create token gated community_. This option already exists in e2e builds. Created community name is **SNT community** but should be renamed to **Token Gated Community**. Membership permission costs 10 SNT. **Join Community** button should be renamed to **Request to Join**. Requests to join should be manually approved. This community should contain 5 channels:
    - General - open for all and free to view and post
    - Lions - user should have 1 SNT to view this channel
    - Birds - user should have 1 ETH to view this channel
    - Trees - user should be able to view and post in this channel if having 1 SNT otherwise it’s locked
    - Flowers - user should be able to view and post in this channel if having 1 ETH otherwise it’s locked

- [ ] _Create 1 SNT to become an admin community_. Created community name should be **SNT Admin community**. A user should have 1 STT to become an admin of this community. Requests to join are accepted automatically. The next channels to include:
    - General - open for all and free to view and post
    - Sounds - user should have 1 SNT to view this channel
    - Colors - user should have 1 ETH to view this channel
    - Books - user should be able to view and post in this channel if having 1 SNT otherwise it’s locked
    - Sports - user should be able to view and post in this channel if having 1 ETH otherwise it’s locked

- [ ] _Create community with admin and membership permissions_. The created community name to be is **Admin and Member Community**. A user should have 1 ETH to become an admin or 1 SNT to become a member of this community. Requests to join are accepted automatically. The next channels to include:
    - General - open for all and free to view and post
    - Party - user should have 1 SNT to view this channel
    - Birthday - user should have 1 ETH to view this channel
    - Travel - user should be able to view and post in this channel if having 1 SNT otherwise it’s locked
    - Cars - user should be able to view and post in this channel if having 1 ETH otherwise it’s locked

## Acceptance Criteria

E2e (x86_64) and PR builds - can create listed communities and join them
Nightly and release builds - still not available to create any communities

**Comment by yevh-berdnyk** [comment]
Note: view-only channels are broken now - a user with view permission can also post in this channel #19041

**Comment by churik** [comment]
Descoping it for now, as the focus is shifting

**Comment by ilmotta** [comment]
> Descoping it for now, as the focus is shifting

@churik when do you think we could come back to this? I have the impression we'll only be able to prioritize this in a few months, when the stars and planets are aligned again for communities. If that's the case, we can probably close the issue as a cleanup measure, but of course, reopen it in the future given its importance for QA.

**Comment by churik** [comment]
yes, I think it makes sense, I'll close it for now.

**Comment by pavloburykh** [comment]
Hey @churik! Actually there is a PR by @cammellos https://github.com/status-im/status-mobile/pull/19257 Based on the fact that large amount of work has been already done maybe it makes sense finish it?

**Comment by churik** [comment]
still too many issues; I'll ask Yevhenia if it makes sense to merge it as-it-is, otherwise we just close it
