### ISSUE TITLE
Fiat currency marks not displayed for accounts synced with Desktop

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18838]
### Steps:
1. Generate a Synd code via the desktop
2. Sync with Desktop user using mobile

### Actual result:
Upon accessing the wallet the fiat currency marks do not appear.

![image](https://github.com/status-im/status-mobile/assets/52490791/88513b1a-40f4-4834-b1d1-98c639e5bd29)

### Expected result:
The fiat currency marks should be visibly displayed alongside accounts and assets after sync with the desktop

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14296165/Status-debug-logs.zip)

**Comment by ulisesmac** [comment]
@VolodLytvynenko I tried to replicate this issue but it seems is no longer valid.

Here's a video:

[Screencast from 2024-03-20 14-15-29.webm](https://github.com/status-im/status-mobile/assets/90291778/91c47bea-e598-4798-950e-44f6ec52515b)


Could you please confirm?

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac Correct. This is not reproducible anymore. Thank you for checking
