### ISSUE TITLE
Push notifications: investigate possibilities of hiding payload

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1883]
Current implementation of push notifications hardcodes a "ping" message. This can obviously be changed to the message itself, but then it would be plaintext via Firebase. Instead, we probably want to encrypt the payload, show a generic ping message and then decrypt it when it is received on the device.

Investigate where this: https://github.com/status-im/status-go/blob/develop/geth/api/api.go#L206-L210 shows up and the possibilities of intercepting it, either as the push notification appears or as the app is foregrounded.

Acceptance criteria:
- Understanding of how we can hide payload and when/where we can intercept it

**Comment by oskarth** [comment]
Partially superseded by the two linked issues. Hopefully it works fine with Android too, once confirmed this can be closed.

It also seems there is is an option on iOS to preview message and call a function before them. Unclear how that will work though, and there doesn't seem to be an Android equivalent either. This thus seems like an optimization we can revisit at a later point in time.

Pausing on this for now. See https://docs.google.com/document/d/1YPMLHgojwz-wmhwKQ3lPi9vyT_dZftkK5tSRxtWIiZU/edit# for priority discussion.

**Comment by tiabc** [comment]
By the way, Telegram, for example, shows something like "You got a new message" when you chat in a secret chat so this is sort of common behaviour, I think.

**Comment by oskarth** [comment]
@tiabc Yep, Signal too.

On iOS there is supposedly some way of doing end to end encryption while previewing message. Might be useful at some point, but there are definitely higher priority tasks right now.

**Comment by pedropombeiro** [comment]
I believe this is now known to work, closing.
