### ISSUE TITLE
Account selection: wrong "i" icon on the Addresses for permissions screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18840]
# Bug Report

## Problem 

![image](https://github.com/status-im/status-mobile/assets/67952253/f3432795-367b-46a0-a78c-cf8e5edc108e)

Design

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-288400&mode=design&t=1b28s4gVRi61BpEG-4

<img width="447" alt="Screenshot 2024-02-15 at 12 56 38" src="https://github.com/status-im/status-mobile/assets/67952253/0b82c89f-4074-4c8b-9ef9-1c2dedfee651">

### Reproduction

1. Open a community invite
2. Go to account selection 
3. Open addresses list

### Additional Information

- Status version: nightly 15/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
Duplicate: https://github.com/status-im/status-mobile/issues/18616
