### ISSUE TITLE
Slider issues on the "Create wallet account" screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18841]
** NOTE: Please use `status-im.common.floating-button-page.view` as part of the solution for this. It is a generic solution which should help resolve this issue 👍 If there is any issues when doing this please reach out to @ulisesmac / @J-Son89 

# Bug Report
https://github.com/status-im/status-mobile/pull/17496

## Problem 
[comment]: # (A problem description)

### ISSUE 1: [currently reproducible on Android] Slide button on create wallet account is transparent
<img width="212" alt="Screenshot 2024-02-15 at 12 43 46" src="https://github.com/status-im/status-mobile/assets/147824399/40e96327-0606-4bbc-bf8a-97c5232e3b02">

#### Expected behavior
[design](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522184&mode=design&t=QLMimk4GRjs7ExWR-0)
<img width="289" alt="Screenshot 2024-02-15 at 13 08 34" src="https://github.com/status-im/status-mobile/assets/147824399/bd6d669d-e35b-4b13-8dc7-d0d0992e045c">

### ISSUE 2: [iOS] Slider stays behind the keyboard at the bottom of the screen

https://github.com/status-im/status-mobile/assets/67952253/87eaaf39-d942-4abc-ac4b-81dbae9b5e39

#### Expected behavior

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-132380&mode=design&t=fqxvhN4qndUU2GVX-4

![image](https://github.com/status-im/status-mobile/assets/67952253/e63ba41d-66f0-4352-b8ad-1974e231ded3)

### Reproduction

1. Open App
2. Go to wallet
3. Create wallet 
4. Type your new account name

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ulisesmac** [comment]
Closing this since it has been addressed in:

- #19160
