### ISSUE TITLE
Can't send transaction - error `intrinsic gas too low` [0.9.11]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1885]
### Description

*Type*: Bug

*Summary*: If send transaction with default or max fee - then it's not sent because of error `intrinsic gas too low`
![img_0604](https://user-images.githubusercontent.com/6584810/30580480-552ed014-9d25-11e7-93d6-533aaac650ab.jpg)

#### Expected behavior
Transaction is sent 
#### Actual behavior
- error `intrinsic gas too low`
- transaction is not sent
- transaction in chat has red line "Transaction failed"

### Reproduction
iOS: https://app.testfairy.com/projects/4803590-status/builds/6583595/sessions/4/?accessToken=Da/7s1FIzORyOoB9c11YYMdemmI
Android (from 00:29) https://app.testfairy.com/projects/4803622-status/builds/6583606/sessions/7/?accessToken=hTbP8p2eQGDrxkMIfiEaIR5VC1w
- Open Status
- Open 1-1 chat
- send to contact 0.1 eth with default fee (you can also try with max fee - same issue will happen)
- on Unsigned transaction screen tap Confirm Transaction
- provide valid password and tap Confirm
- 1-1 chat is shown with error message `intrinsic gas too low`. In chat message has "transaction failed" note

### Additional Information
* Status version: release candidate 0.9.11   0.9.10-103-g4672df2b+
* Operating System: 
Real device iPhone 7 plus, iOs 10.3.2
Real device Google Pixel XL, Android 8.0

**Comment by oskarth** [comment]
Reproduced 'intrinsinc gas too low' issue on `release/0.9.11` branch. Locally compiling with latest status-go develop (`gba963cc`) transaction goes through. Tested on iOS simulator.

**Comment by annadanchenko** [comment]
On Branch: bugfix/upgrade-status-go-g283ae3e can send eth with default fee 
on iOS tried 7 times - once got “transaction underpriced” error and failed transaction. Others are sent ok
on Android tried 7 times - twice got “transaction underpriced” error and failed transactions. Others are sent ok

**Comment by adambabik** [comment]
It can be related to the problem reporter here: https://github.com/ethereum/go-ethereum/issues/14838. I will work on this.

**Comment by annadanchenko** [comment]
closing the issue as the initial error is solved

**Comment by marcusdworm** [comment]
hi, my current build is 1.7.3 and I am getting the same error:

Error: intrinsic gas too low
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:3021:24
    at <anonymous>:1:23

Note: I'm trying to run the contract is private network.
May I know how you guys fixed the error?

**Comment by autonome** [comment]
Just saw this when trying to register my .stateofus.eth username on iOS app. There's no default fee populated which is weird too.
