### ISSUE TITLE
[Wallet] Incorrect placeholder color in Watch only account

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18856]
# Bug Report
https://github.com/status-im/status-mobile/pull/18683
## Problem 
[comment]: # (A problem description)
Placeholder has incorrect color.

#### Expected behavior
[Design](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522184&mode=design)
<img width="403" alt="Screenshot 2024-02-16 at 10 55 20" src="https://github.com/status-im/status-mobile/assets/147824399/e70e149d-ff2f-47d6-bf80-8acc31c1027b">

#### Actual behavior

<img width="347" alt="Screenshot 2024-02-16 at 10 55 12" src="https://github.com/status-im/status-mobile/assets/147824399/19aeb881-6619-47f9-a85b-3e1e3affd545">

### Reproduction

1. Go to the Wallet
2. Create Watch only account

### Additional Information

- Status version: PR
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ulisesmac** [comment]
Hi @mariia-skrypnyk 

I think the expected and actual screenshots are swapped :thinking: 

Additionally, we are currently using a placeholder, is this issue about the placeholder color (to make it darker) or about showing the screen with a prefilled input?

**Comment by ulisesmac** [comment]
@mariia-skrypnyk  AFAIK this has also been addressed in:
- #19160

could you please confirm? if so, feel free to close this issue

**Comment by J-Son89** [comment]
@mariia-skrypnyk - a bump on this. See. @ulisesmac's comment. This is already addressed. Can we close this issue?

**Comment by OmarBasem** [comment]
Closing this issue as I see it has been addressed. Reopen if necessary.
