### ISSUE TITLE
Small bottom margin of slider button on request to join community screen (IOS)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18860]
This is IOS only issue. 
Reproducible on iPhone X, IOS 16.7.4
**Steps:**

1. Open community home screen
2. Tap Join a community
3. Pay attention at bottom margin of slider button

**Actual result:** 
![photo_2024-02-16 14 05 22](https://github.com/status-im/status-mobile/assets/97245802/a50fbced-e170-48fe-ae6f-5ce71d65ec7e)

**Expected result:**

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-285299&mode=design&t=jkx87ddOU8rMnqbU-0)

![photo_2024-02-16 14 05 22](https://github.com/status-im/status-mobile/assets/97245802/16a9f7b5-90b2-43c4-ba90-f545204d7520)

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
https://github.com/status-im/status-mobile/pull/18866#issuecomment-1948849265
