### ISSUE TITLE
Removed transactions are displayed in 1x1 and group chat as pending/failed when closing Sign Transaction screen [0.9.11]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1886]
### Description

*Type*: Bug

*Summary*: In release candidate `0.9.11` when I remove transaction on Sign transaction screen and close the screen I can see this transaction is shown in 1x1 chat as `failed` and `pending` in group chat

#### Expected behavior
Transaction is not shown when I removed it and did not sign

#### Actual behavior

1x1 chat
![image](https://user-images.githubusercontent.com/28752642/30583089-a4b42e1e-9d2e-11e7-94b9-fe4584ebfe49.png)

Group chat
![image](https://user-images.githubusercontent.com/28752642/30583104-b51dab90-9d2e-11e7-9c57-5591ce568688.png)

### Reproduction

- Open Status
- Add somebody as contact
- Send txn in 1x1 chat / group chat
- Delete this transaction on Sign screen
- Pay attention to the chat

### Additional Information
* Status version: release `0.9.11` 0.9.10-103-g4672df2b+ (1660) 
* Operating System: Android, iOS
* TF: https://app.testfairy.com/projects/4803622-status/builds/6583606/sessions/11/?accessToken=3zuhuKI2ABGFcvXMxEDN8jwtlsc (from 0:42)

**Comment by annadanchenko** [comment]
even if send transaction was successful, recipient sees in 1-1 chat message with "transaction pending". Would expect something like transaction sent/delivered or anything else that ways about completed transaction. Note: transaction was done from 0.9.10 released version.
![image](https://user-images.githubusercontent.com/6584810/30590204-480cf098-9d46-11e7-85c2-ab9b9575cc23.png)

**Comment by annadanchenko** [comment]
1. No "pending", "failed" statuses are shown inside send message in chat.
2. If transaction is sent successfully then message send is shown in chat.
3. If transaction was deleted from Unsigned transactions then
3.1  no messages inside send message is shown. 
3.2 there is error message "Transaction failed" in chat screen

Looks ok, can merge
