### ISSUE TITLE
[IOS] Incorrect UI for the frame and placeholder within the input field is applied on the QR generation screen when the keyboard is opened.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18871]
### Steps:
1. Onboard -> Go to Syncing screen -> tap [+]  -> Slide to reveal code
2. Focus on field within 'authentication process' drawer to open the keyboard
3. Check the frame.

### Actual result:
Incorrect UI is applied to the frame and placeholder on 'authentication process' drawer when the keyboard is opened
![image](https://github.com/status-im/status-mobile/assets/52490791/f1ee1dd6-6076-4822-82ca-cec831e02d8b)

### Expected result:
Correct UI is applied to the frame and placeholder on 'authentication process' drawer 
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=1104-178735&mode=design&t=X6ZvyHAJ3q95nLJq-0

### ENV:
- Nightly 16 Feb 2024

**Comment by ibrkhalil** [comment]
Hey @VolodLytvynenko 
I tried to find the file in Figma to find the color values, But it looks like this
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=1112-140473&mode=design&t=qtt7mZcaoje6sPAX-4
Which is the correct source of truth?
And can you provide a Figma file for the screenshot so that it can be done according to it?
Thanks!

**Comment by VolodLytvynenko** [comment]
> Hey @VolodLytvynenko I tried to find the file in Figma to find the color values, But it looks like this https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=1112-140473&mode=design&t=qtt7mZcaoje6sPAX-4 Which is the correct source of truth? And can you provide a Figma file for the screenshot so that it can be done according to it? Thanks!

Hey @ibrkhalil, thank you for pointing this out in Figma. I couldn't find this initially and that's why provided an image of how it looked in the nightly build when it was not changed. However, based on the design, I see that the opacity is correct. Apologies for the incorrect issue, and thank you for finding the correct design.

I have updated the description in the current issue. The priority for this issue is now low.

**Comment by VolodLytvynenko** [comment]
The issue is not reproducible anymore
