### ISSUE TITLE
Not all eth accounts are recovered until relogin.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18875]
### Steps:
1. Recover an account with at least 2 ETH addresses.

### Actual result: 
Only one address is shown until the first relogin.

https://github.com/status-im/status-mobile/assets/52490791/97a5c19e-d3ae-4fe6-aa31-8f2c710e7532

### Expected result:
All addresses should be shown after recovery.

### Additional info:
Feel free to reach out to me directly if you'd like to get seed phrase of user with several eth accounts

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/15126924/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
@smohamedjavid - why did you remove assignment from this issue? 
Is it still relevant/ did you have any findings which might help someone finish this issue?

**Comment by smohamedjavid** [comment]
I removed it last week as it had a larger scope/feature. But, I will assign it back as I will try to handle the backup signals for now as Andrea suggested.
