### ISSUE TITLE
Amount is 0.00 ETH in "specify amount" section instead of amount typed for send command [0.9.11]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1888]
### Description

*Type*: Bug

*Summary*: User types amount to be sent in the input field. The typed amount is not shown in the Specify amount section (above slider)
![img_0612](https://user-images.githubusercontent.com/6584810/30590866-1eb33092-9d49-11e7-9d47-360f95966f07.jpg)

#### Expected behavior
Typed amount is shown the Specify amount section (above slider), e.g if user types 0.1234 then it's shown as 0.1234 ETH

#### Actual behavior
The typed amount is not shown in the Specify amount section (above slider)

### Reproduction
https://app.testfairy.com/projects/4803590-status/builds/6583595/sessions/17/?accessToken=pWO4HtWTX4FicCToB81wxIHJS3o
- Open Status
- Open 1-1 chat
- tap on /send command
- select the recipient from suggestions
- next screen is shown with slider to change fee and 0.00 ETH above slide. Start typing amount in the input field, e.g 0.1234. Check that amount 0.00 above slider is changing as you type (currently it's not even if wait for 2-3 minutes after typing)

### Additional Information
* Status version: release candidate 0.9.11   0.9.10-103-g4672df2b+
* Operating System: 
Real device iPhone 7 plus, iOs 10.3.2
Real device Google Pixel XL, Android 8.0

**Comment by goranjovic** [comment]
@annadanchenko What branch is this?

**Comment by oskarth** [comment]
@goranjovic `release/0.9.11` (I had this issue)
