### ISSUE TITLE
`make run-android` is flaky

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18888]
On latest develop, when I run make run-android I get the following output at the end of it, and it also causes metro which is already running in another tab to shut down:
```
removed '/tmp/tmp-status-mobile-eef8f25d6/tmp.4KSS4uAywR'
Performing Streamed Install
Success
Waiting for Metro server...
nohup: ignoring input
....warn Package react-native-blob-util contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warning: the transform cache was reset.
.                Welcome to Metro v0.79.1
              Fast - Scalable - Integrated


  bash arg: -p
  bash arg: im.status.ethereum.debug
  bash arg: 1
args: [-p, im.status.ethereum.debug, 1]
 arg: "-p"
 arg: "im.status.ethereum.debug"
 arg: "1"
data="im.status.ethereum.debug"
Events injected: 1
## Network stats: elapsed time=29ms (0ms mobile, 0ms wifi, 29ms not connected)
runMetro
```

**Comment by yqrashawn** [comment]
Can you try `run-clojure` then `run-android`

https://github.com/status-im/status-mobile/pull/18784

we don't use `run-metro` after this PR

**Comment by OmarBasem** [comment]
> Can you try `run-clojure` then `run-android`
> 
> #18784
> 
> we don't use `run-metro` after this PR

I have tried that also. Same error

**Comment by siddarthkay** [comment]
Hi @OmarBasem : can you pls share contents of `metro-server-logs.log`

**Comment by OmarBasem** [comment]
> Hi @OmarBasem : can you pls share contents of `metro-server-logs.log`

Under which directory is that file?

**Comment by siddarthkay** [comment]
should be in root directory, it gets created when you run `make run-android`, don't quit it, else it gets cleaned up ;)

**Comment by OmarBasem** [comment]
@siddarthkay thank you, here it is:
[metro-server-logs.log](https://github.com/status-im/status-mobile/files/14327499/metro-server-logs.log)

**Comment by siddarthkay** [comment]
Hmm all of this looks okay, what happens on the simulator or connected device? Do you see any error there?
I don't see any failure message.

**Comment by OmarBasem** [comment]
@siddarthkay `make run-android` does not complete. It fails with the above error. And metro does not start (and if it is already running, it gets shut down) so the device does not connect.

**Comment by siddarthkay** [comment]
> above error

Whatever text you have posted in issue description are **_just log messages_** there is **_no error_** message.

It may take a while for metro to finish loading and yes the metro loading indicator does not show which might give you an impression that nothing is happening.

When I tried to reproduce this behaviour the builds work fine on my machine ™️ 

Screenshot:
<img width="1448" alt="Screenshot 2024-02-19 at 1 10 04 PM" src="https://github.com/status-im/status-mobile/assets/64726664/a699d98d-7696-4a95-858e-9e0608c92685">


> metro does not start (and if it is already running, it gets shut down)

Yes that is the intended behaviour, _it is a feature and not a bug_.
If your intent is to just start `clojure` terminal and `metro` terminal and open an already built & installed app then you can do the following : 
- `make run-clojure`
- `make run-metro`
- Open your Simulator, and tap on the installed app.

But,
If you wish to build the app then the new workflow is : 
- `make run-clojure`
- `make run-android`

**Comment by OmarBasem** [comment]
> But,
If you wish to build the app then the new workflow is :

make run-clojure
make run-android

@siddarthkay  when I run the above the app actually builds and installs successfully on the device, but I get a red screen error: `unable to load script. Make sure you're either running Mero or that your bundle is packaged correctly for release`

**Comment by siddarthkay** [comment]
Okay I will improve this in my next PR 
I'm already experimenting with `tmux` and `screen`
as a temporary workaround, tapping on "reload" on the simulator should work for you

**Comment by OmarBasem** [comment]
@siddarthkay does not work 😢 

I get another error: `could not connect to development server. Try the following to fix the issue: Ensure that metro is running...`

**Comment by siddarthkay** [comment]
hmm, I guess for the time being you could revert these changes locally so that you're not blocked..

https://github.com/status-im/status-mobile/pull/18784/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L281-L285

I'll send a PR to make this better shortly.
