### ISSUE TITLE
User who holds testnet tokens can join community with permissions set on Mainnet

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18896]
cc @cammellos 

**Preconditions:** 

User A (desktop) - has enabled Mainnet network 
User B (mobile) - has enabled testnet and has some ETH on Goerli

**Steps:** 

1. User A (Desktop) creates community and sets membership permissions (e.g. 0.003 ETH to become a member)
2. User A shares community to User B
3. See if User B can join community using his testnet tokens (User B holds 0.01 ETH on Goerli)

**Expected result:** User B should not be able to join community using testnet tokens. 

**Actual result:** User B can join community

[UserA_DesktopAdmin.log](https://github.com/status-im/status-mobile/files/14330109/UserA_DesktopAdmin.log)
[UserB_mobile.zip](https://github.com/status-im/status-mobile/files/14330111/UserB_mobile.zip)

https://github.com/status-im/status-mobile/assets/97245802/3514d708-6214-433d-ac41-c803c0facde4

### Additional Information

- Desktop  [StatusIm-Desktop-v2.27.0-rc.2-da3e24-aarch64](https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/15/)
- Status version: nightly 
- Operating System: Android, iOS

**Comment by glitchminer** [comment]
@endulab , do we need a separate issue to cover the fact that it is not possible for the user to identify the chain that a permission was created on?  

For example, when I create a permission while on mainnet then switch to testnet and edit that permission there is no indication that the permission no longer applies to mainnet.

**Comment by endulab** [comment]
@glitchminer Considering that we want to block the testnet functionality for end users, then I think that we do not need this.
Right @John-44 ?

**Comment by benjthayer** [comment]
> @glitchminer Considering that we want to block the testnet functionality for end users, then I think that we do not need this. Right @John-44 ?

We currently have this flow where the admin area is disabled for Owners, TM's or Admins while in testnet mode - permission creation / editing is therefore not available from the admin area while in testnet mode. 
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=34976-596521&mode=design&t=hIMrg7URNQoAhQqn-4

However, the user can create a new / edit an existing permission via the create new / edit channel dialog while in testnet mode I believe?. We could perhaps consider removing the permissions area from the create new / edit channel dialog when in testnet mode - or we could prevent the user from selecting testnet tokens when creating / editing a permission? WDYT @John-44 ? 

https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=2975-495819&mode=design&t=hIMrg7URNQoAhQqn-4
<img width="482" alt="Screenshot 2024-02-21 at 9 54 37 AM" src="https://github.com/status-im/status-mobile/assets/110033914/c9a30c13-02bf-4e81-84ff-7ff383d29295">

**Comment by John-44** [comment]
We def want to fix the attack vector (which @Michal) is doing, but we are also going to remove the 'testnet mode for communities' toggle from Advanced Settings in all release builds, so there won't be any way for to use communities in testnet build via our UI.

We don't need anything beyond this, we only need to fix the attack vector and we shouldn't spend any time making 'testnet mode for communities' work better or have less bugs, we just prevent people from using 'testnet mode for communities' enterally.

As it will be impossible for any user to enable 'testnet mode for communities' via the UI, we just need to make sure all security attack vectors are closed, and nothing more.

**Comment by jrainville** [comment]
Completed in https://github.com/status-im/status-desktop/pull/13637
