### ISSUE TITLE
Blank screen after tap on community invitation link

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18898]
# Bug Report

## Problem 
[comment]: # (A problem description)
User gets invitation to the community. Taps on link and see blank white screen with only Jump to button.
Sometimes is changes into correct screen after 3sec but in my case I stayed there and nothing have changed.

#### Expected behavior
User is redirected to the community screen

#### Actual behavior
Blank screen after tap on community invitation link

### Reproduction

1. Login to app as user A
2. Get the invitation to the community from user B
3. Tap on community invitation link

<img width="298" alt="Screenshot 2024-02-19 at 13 21 13" src="https://github.com/status-im/status-mobile/assets/147824399/54d7b45c-7109-4ddf-8e27-23906f6066a8">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
probably related to https://github.com/status-im/status-mobile/pull/18890, cc @yqrashawn

**Comment by yqrashawn** [comment]
Also might be related to https://github.com/status-im/status-mobile/issues/18624

**Comment by yqrashawn** [comment]
Having trouble reproducing this. 
But do managed to find a potential issue in status-go when fetching community, there's log in status-go says failed to fetch but there's no response in mobile rpc request

**Comment by mariia-skrypnyk** [comment]
> Having trouble reproducing this. But do managed to find a potential issue in status-go when fetching community, there's log in status-go says failed to fetch but there's no response in mobile rpc request

Hi @yqrashawn !

I catched android logs today during testing https://github.com/status-im/status-mobile/pull/18923 on Android.
[white-screen.log](https://github.com/status-im/status-mobile/files/14449352/white-screen.log)

Let me know if you'll need something else!

**Comment by qoqobolo** [comment]
Not reproducible recently, please reopen if you encounter it again.
