### ISSUE TITLE
Artifactory: disk space at 91% used, free up disk space by deleting old builds

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1890]
Seeing 

> Datastore disk is too high: Warning limit: 85%, Used: 91%, Total: 188.80 GB, Used: 172.00 GB, Available: 16.79 GB

We should probably clean out some old builds / temp files.

**Comment by yenda** [comment]
@jakubgs since you were working on artifactory yesterday do you think this we can close this issue ?

**Comment by jakubgs** [comment]
Not entirely. I'm pretty close tough. I might be able to kill this next week.

**Comment by jakubgs** [comment]
Definitely stale. Artifactory is DEAD. :fireworks:

**Comment by oskarth** [comment]
YOU WOKE IT @jakubgs Now we gotta wait another couple of months

**Comment by jakubgs** [comment]
Forgot to close =].
