### ISSUE TITLE
after upgrading `react-native` to `0.73.4` the Android App crashes at runtime because of foreground service

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18911]
## Problem

When running the android app on simulator with `make run-android`
The app crashes with the following error message 

```
java.lang.RuntimeException:
Unable to start service im.status .ethereum.pushnotifications•ForegroundService@6fb4493 with Intent { 
cmp=im.status.ethereum.debug/im.status.ethereum.pushnotifications.ForegroundService}: 
java.lang.IllegalArgumentException: im.status.ethereum.debug: Targeting U+ (version 34 and above) 
disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without 
FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. 
To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new Pending Intent 
with an implicit Intent use FLAG_IMMUTABLE.
```

## Reproduction Requirements
- This was reproduced on a Pixel Emulator running API 34
- This happens after you complete your onboarding journey and you must give permissions for notifications.
- Usually you would see this error after you've completed the communities screen, but its really triggered when the push notification code tries to start the foreground service.
 
## Screenshot
<img width="461" alt="Screenshot_2024-02-20_at_11 44 07_AM" src="https://github.com/status-im/status-mobile/assets/64726664/f5fd8eff-4386-4e61-916f-22cc8a9f9e5c">

## Acceptance Criteria
must not crash

**Comment by jo-mut** [comment]
hey @siddarthkay just ran this branch https://github.com/status-im/status-mobile/pull/18563 and it works well without the above mentioned crash. Am wondering when does the crash occur? and is there a pattern you are aware of to reproduce it?

**Comment by siddarthkay** [comment]
Ah yes this issue happens after you enable push notifications

**Comment by siddarthkay** [comment]
fixed with : https://github.com/status-im/status-mobile/pull/18563/commits/5e92c3709131bd4820b20a78c0fc26a40909b0c1
