### ISSUE TITLE
[IOS only] The 'Continue' button disappears in the keypair name screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18925]
Follow up for https://github.com/status-im/status-mobile/pull/18790
it would be nice to fix this along with the following bug https://github.com/status-im/status-mobile/issues/18833

### Steps:
1. Go to keypair name [screen](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-592401&mode=design&t=fOuc10SVirG3d61s-0)
2. Focus on the keypair name input field

### Actual result:
The 'Continue' button is not shown when keyboard is opened

![image](https://github.com/status-im/status-mobile/assets/52490791/73cbc567-0a6c-48a9-99e4-bf1271419e55)

### Expected result:
The 'Continue' button is visible when keyboard is opened
![image](https://github.com/status-im/status-mobile/assets/52490791/e7960687-c2e1-4118-839c-8160b611e439)

**Comment by J-Son89** [comment]
@OmarBasem, @mmilad75 - is this issue still relevant? Can we close if not or prioritise it otherwise.

**Comment by VolodLytvynenko** [comment]
> @OmarBasem, @mmilad75 - is this issue still relevant? Can we close if not or prioritise it otherwise.

@J-Son89 fixed already
