### ISSUE TITLE
Bottom sheet with save and send options not displayed after scanning wallet QR using universal scanner

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18928]
Follow up for https://github.com/status-im/status-mobile/pull/18677
### Steps:
1. Open universal scan
2. Scan the ETH address

### Actual result:
The user is navigated to the address sсreen

https://github.com/status-im/status-mobile/assets/52490791/8925b62f-200c-4203-866d-21de57610acd

### Expected result:
- The user is navigated to the main wallet page.
- The bottom sheet is shown with options to save the address and send to this address.
https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8175-25622&mode=design&t=aqQfAbZ0VaTlOxnu-0
- In case when a multichain ETH address is scanned, the labels ETH, OPT, and ARB1 are shown, depending on whether they are set.
![image](https://github.com/status-im/status-mobile/assets/52490791/c3670224-a2a6-4f82-946d-83f1123c258b)

https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8175-47408&mode=design&t=aqQfAbZ0VaTlOxnu-0

**Comment by VolodLytvynenko** [comment]
Jamie mentioned [here](https://github.com/status-im/status-mobile/pull/18677#issuecomment-1943896110) that it would be better to align with @briansztamfater

**Comment by J-Son89** [comment]
I would not classify this as a bug as it is functionality not implemented yet 👍
