### ISSUE TITLE
Universal scanner is not triggered via eth address share screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18934]
Follow up for https://github.com/status-im/status-mobile/issues/18928

### Steps:
1. Open wallet -> open any eth account -> tap 'receive'
2. Tap 'scan' button

### Actual result:
The universal scanner is not triggered

https://github.com/status-im/status-mobile/assets/52490791/0d0c8c6b-0f4c-4cb3-b15f-00b891148bd1

### Expected result:
The universal scanner is triggered

**Comment by J-Son89** [comment]
align with @alwx when implementing this! -> this is the same as the universal scanner but with a subset of the features (afaik) - 
best to align with design too. 
i.e what happens if you use this scanner but scan something non related to the wallet (e.g community channel qr)

**Comment by VolodLytvynenko** [comment]
> align with @alwx when implementing this! -> this is the same as the universal scanner but with a subset of the features (afaik) - best to align with design too. i.e what happens if you use this scanner but scan something non related to the wallet (e.g community channel qr)

Just aligned this with a design team. The universal scanner should be triggered https://discord.com/channels/624634427930312714/852533718790570015/1209862462481109034
