### ISSUE TITLE
Transactions history: cannot scroll to the last 2 transactions

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1893]
## Test case 1

Accounts with 12 transactions on the same day. scrolling until bottom of history

Current (2 missing transactions):

![screenshot_1505832506](https://user-images.githubusercontent.com/1181225/30598615-81dc1e20-9d5a-11e7-8153-e3efb618cef0.png)

Without menu header (can see the 2 transactions are actually there but they are hidden at the bottom):

![screenshot_1505832283](https://user-images.githubusercontent.com/1181225/30598658-a2d96812-9d5a-11e7-9b09-9f8cbccb196c.png)

With margin 130 (can see all transactions):

![screenshot_1505832384](https://user-images.githubusercontent.com/1181225/30598709-ca5af6c6-9d5a-11e7-8956-91fb2d074b19.png)

**Comment by yenda** [comment]
The section list is here:
https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/wallet/transactions/views.cljs#L92

But in a screen alone it displays fine so it has to do with the fact that it is within the react-native-swipper with tabs.

Tabs are here:
https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/wallet/transactions/views.cljs#L188

Again the swipper in a screen alone displays fine so it is like it doesn't account for the space occupied by the tabs and acts like it is occupying the full screen so there is part of the view that is beyond the bottom of the screen

**Comment by asemiankevich** [comment]
Fixed in 0.9.10-117-g08d1f94e+
