### ISSUE TITLE
[Scanner] Nothing happens when users scans community channel QR-code

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18935]
# Bug Report

## Problem 
[comment]: # (A problem description)
User tries to scan QR-code to join a community channel and gets no result

#### Expected behavior
Community with a shared channel opens

#### Actual behavior

Nothing happens when users scans community channel QR-code

https://github.com/status-im/status-mobile/assets/147824399/a8f4de63-5b30-46d0-bd08-1b34f2dd4f2e

### Reproduction

1. Login as User A
2. Generate channel QR-code as user A
3. Login as user B (on another device)
4. Open QR-code scanner inside the Status app.
5. As User B can QR-code of User A

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Not really a bug, this feature was simply never implemented. There is even an issue for that: https://github.com/status-im/status-mobile/issues/18743

**Comment by churik** [comment]
Closed in favor of https://github.com/status-im/status-mobile/issues/18743
