### ISSUE TITLE
The user is not navigated to the save address screen after the eth QR is scanned by universal scanner

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18933]
this issue implementation should be started after the https://github.com/status-im/status-mobile/issues/18928 is merged

### Steps:
1. Open universal scan
2. Scan the ETH address
3. Select 'save address' option in the opened bottom sheet

### Actual result:
The user is navigated to the address sсreen

### Expected result:
The user is navigated to 'save address' flow
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&mode=design&t=N2xV3WFXo87lNZlk-0

Aligned it with the design team [here](https://discord.com/channels/624634427930312714/852533718790570015/1209445187684929546)

**Comment by VolodLytvynenko** [comment]
Hey @shivekkhurana Jamie asked [here](https://discord.com/channels/624634427930312714/852533718790570015/1209489333107822633) to tag you after this issue creation

**Comment by J-Son89** [comment]
> Hey @shivekkhurana Jamie asked [here](https://discord.com/channels/624634427930312714/852533718790570015/1209489333107822633) to tag you after this issue creation

thanks @VolodLytvynenko - yes, whoever works on this should align with @alwx (implemented generic scanner) 
and @shivekkhurana - currently working on the save address feature. 
This issue will be blocked until the save address feature is complete 👍

**Comment by VolodLytvynenko** [comment]
fixed in https://github.com/status-im/status-mobile/pull/19250
