### ISSUE TITLE
Quo add component Slideshow - Slider bar

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18942]
Designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=34841-2817&mode=design&t=wM6XXnmZzh8HIBy6-0

Acceptance Criteria:
- Preview Screen
- aligned with best practices
- component spec
- malli schema

**Comment by Rende11** [comment]
I would like to implement it
