### ISSUE TITLE
Spike on which messages are retried

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18959]
For any kind of message that status-go sends, we should figure out:

1) If it's retried or not
2) Which mechanism is used for retrying (datasync/raw messages)

We should collate this information in a spreadsheet in order to evaluate next actions.

**Comment by qfrank** [comment]
relate [spreadsheet](https://docs.google.com/spreadsheets/d/1VI4S9orTqkCsTNbMBN5eZesV1XGkcGJp-cVAOUjXyAY/edit#gid=0)
