### ISSUE TITLE
Unable to send transaction - confirm button does not respond

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18951]
At some point 'confirm' button stopped responding though it was working couple of transactions ago. 

**Preconditions:** before current issue occured I have been able to sent 4 transactions which for some reason were not appearing in blockchain for a long time. So current issue might be related to this problem which is logged on Desktop side https://github.com/status-im/status-desktop/issues/13685. I believe that attached logs might tell more about the root cause. 

**Steps:** 

1. Start token transaction flow
2. Try to confirm transaction
3. See the result

**Actual result:** at some point confirm button stops responding. 
[logs (18).zip](https://github.com/status-im/status-mobile/files/14377058/logs.18.zip)

https://github.com/status-im/status-mobile/assets/97245802/80ab118f-ee6f-45f8-9494-86e47f8020e7

### Additional Information

- Status version: release 2.27
- Operating System: iOS

**Comment by J-Son89** [comment]
@briansztamfater any idea what this is related to?

**Comment by J-Son89** [comment]
@pavloburykh - is this still happening?

**Comment by pavloburykh** [comment]
> @pavloburykh - is this still happening?

need to recheck, I believe it is not so easy to reproduce. Will be able to recheck once we update go version, so testnet balances appear again.

**Comment by OmarBasem** [comment]
@pavloburykh can this issue be closed?

**Comment by pavloburykh** [comment]
> @pavloburykh can this issue be closed?

Let's close it. Will re-open in case we face again.
