### ISSUE TITLE
Wallet - Creating a watched address account with a multichain address goes unresponsive at the confirmation screen

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#18950]
# Bug Report

## Problem 

Creating a watched address account with a multichain address goes unresponsive at the confirmation screen

| Enter multichain address | Confirm page where `Add watched address` btn is unresponsive |
| -- | -- |
| <img width="300" src="https://github.com/status-im/status-mobile/assets/19339952/4f469946-0ca8-4233-980d-7ec34d064fd3" /> | <img width="300" src="https://github.com/status-im/status-mobile/assets/19339952/3a0cd93b-e1ec-428c-8c52-579b2f037ecb" /> |

⚠️ NOTE: The reason why the creation is stuck is because `status-go` doesn't accept multichain addresses on account creation. It returns the following error:
```
invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go struct field Account.address of type types.Address
```

#### Expected behaviour

The app should not accept multichain addresses on the address input (same as Desktop behaviour)

### Reproduction

1. Open Status
2. Navigate to the Wallet tab
3. Tap on `+` to add new watch address
4. Enter a multichain address (Eg: `eth:opt:arb1:0x9bf27d0c9aba562dc33bc4b60c233a6609ce2987`)
5. Tap on `Confirm` to navigate to the next screen
6. Enter a name
7. Tap on `Add watched address`

### Additional Information

- Operating System: Android, iOS

**Comment by ulisesmac** [comment]
Hey @smohamedjavid 

> The app should not accept multichain addresses on the address input (same as Desktop behaviour)

According to designs, the input should accept it:

![image](https://github.com/status-im/status-mobile/assets/90291778/cef24185-29bb-49c4-b0e6-c1834fde22db)

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522338&mode=dev

Probably a status-go issue instead?

**Comment by briansztamfater** [comment]
@ulisesmac @smohamedjavid I am thinking that maybe just ignoring the prefix would be a solution to this issue. For example, if user enters `eth:opt:arb1:0x9bf27d0c9aba562dc33bc4b60c233a6609ce2987` we can send just `0x9bf27d0c9aba562dc33bc4b60c233a6609ce2987` to the status-go endpoint, and therefore prevent blocking the UI. WDYT?

**Comment by ulisesmac** [comment]
@briansztamfater 

Sounds good as long as there's no difference for a multi-chain address on status-go
