### ISSUE TITLE
[Android] Long community name is not split into two lines if before joining it took one line

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18966]
# Bug Report

## Problem 

To reproduce this bug, you need to create a community on Desktop with a name that will initially take one line on most screens, e.g. `Sepolia community tkn gated` (27 characters), and join it on an Android device.

In this case, after changing the community overview screen state after re-opening the community, its name won't start splitting into two lines, it'll just go off the screen. 

**Before joining and reopening (relogin due to a bug)**

<img width="316" alt="Screenshot 2024-02-23 at 15 39 02" src="https://github.com/status-im/status-mobile/assets/67952253/807a7a72-c079-4e94-ab7d-226a4acd21c3">

**After joining and reopening** 

<img width="315" alt="Screenshot 2024-02-23 at 15 40 09" src="https://github.com/status-im/status-mobile/assets/67952253/e9441d59-871b-4984-a512-6c13682dd4eb">

#### Expected behavior
The name is split into two lines

### Reproduction

1. Create a community on Desktop with a name of ~27 characters (e.g. `Sepolia community tkn gated` as in the example)
2. Join it on your Android device
3. Reopen the app and open the community again

### Additional Information

- Status version: nightly 23/02
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ajayesivan** [comment]
@qoqobolo, I couldn't find any designs for this state. Do you know where it is? Also, the message 'community admin will review your request' is still shown even after joining the community. It seems like a bug. Can you confirm?

**Comment by qoqobolo** [comment]
> I couldn't find any designs for this state. Do you know where it is?

Hey @ajayesivan , yeah that wasn't easy to find, it turned out that it was in `Channels` 😅
Here:

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-409196&mode=design&t=1L8wbysfkOIExg8g-4

> Also, the message 'community admin will review your request' is still shown even after joining the community. It seems like a bug. Can you confirm?

Yes, this issue is logged: https://github.com/status-im/status-mobile/issues/18706
It's assigned to @BalogunofAfrica but you can discuss who would be more comfortable picking it up
