### ISSUE TITLE
Add feature flag and an empty view for new contact profile

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#18960]
Add a feature flag and an empty view with text in the middle "not implemented new contact profile view" for the new contact profile view, disabled by default

No need to implement the empty view if #18961 is finished

feature flag example https://github.com/status-im/status-mobile/blob/4421789f25937a20fb2220b5ad2a7e08d55084e7/src/status_im/config.cljs#L170

old contact view at https://github.com/status-im/status-mobile/blob/4421789f25937a20fb2220b5ad2a7e08d55084e7/src/legacy/status_im/ui/screens/screens.cljs#L491

**Comment by seanstrom** [comment]
Here's a small note I wanted to share about feature flags:
* Based on a discussion with @J-Son89, I think all new feature flags are meant to be integrated with the Feature Flag UI
* Here's a reference for how feature flags can be integrated with the Feature Flag UI:
https://github.com/status-im/status-mobile/pull/18602/files
