### ISSUE TITLE
Detailed community page UI does not update correctly until a relogin is performed

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18970]
### Steps:
1. `User A` share community to `User B`
2.  `User B` joins the community
3. `User B` closes the community and reopens it again

### Actual result:
The community still displays with a big avatar, even after reopening it.

https://github.com/status-im/status-mobile/assets/52490791/74f02e88-1626-4761-bd05-9cf749186d00

### Expected result:
The community should display with a small avatar if the current community is opened more than once after joining.

Design for how the avatar should be shown when the community is opened for the first time after joining:https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10303-428036&mode=design&t=gOWXaS8AuA7zewR2-0

Design for how the avatar should be shown when the community is opened more than once after joining:
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10303-428433&mode=design&t=gOWXaS8AuA7zewR2-0

**Comment by cammellos** [comment]
@VolodLytvynenko I am inclined to mark it as won't fix/close it. 
I think it works in the majority of the cases, since the collapsed avatar is shown for the majority of the cases and solves the issue of power users of a community not having to scroll. What do you think?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I am inclined to mark it as won't fix/close it. I think it works in the majority of the cases, since the collapsed avatar is shown for the majority of the cases and solves the issue of power users of a community not having to scroll. What do you think?

@cammellos I have to agree with you :) I close this issue
