### ISSUE TITLE
Wallet: Initial Send screen is not aligned on iOS [1839]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1897]
### Description

*Type*: Bug

*Summary*: Initial SEND screen is not aligned on iPhone 5S real device and does not match mocks 

#### Actual behavior
**### Please note that it is not full list of discrapencies . The UI should match the mocks 1x1 , check https://zpl.io/a3eexl2**

![image](https://user-images.githubusercontent.com/28752642/30632657-94bdeea0-9df1-11e7-8014-06e8f9b2af92.png)

Should be left aligned
![image](https://user-images.githubusercontent.com/28752642/30633498-8305f31c-9df4-11e7-9804-32a1cf9d3264.png)

Should be centered
![image](https://user-images.githubusercontent.com/28752642/30633551-bc3d7b78-9df4-11e7-994d-939557667e16.png)

QR windown should be bigger
![image](https://user-images.githubusercontent.com/28752642/30633603-edeeb222-9df4-11e7-9405-6af5af466543.png)

Icon should be transparent
![image](https://user-images.githubusercontent.com/28752642/30633681-3e8695ec-9df5-11e7-9a69-1c0c6beb75b8.png)

Should not be bold
![image](https://user-images.githubusercontent.com/28752642/30633731-6ccd120a-9df5-11e7-8e19-3118a13d53f2.png)

### Expected
Please check Zeplin https://zpl.io/a3eexl2
![image](https://user-images.githubusercontent.com/28752642/30633464-67015e72-9df4-11e7-8cf4-5fdfbcfedaff.png)

### Reproduction

- Open Status
- Go to New wallet tab
- Click Send

### Additional Information
* Status version: 0.9.11d117-1557.117
* Operating System: iOS

**Comment by andmironov** [comment]
Hey guys, heres the actual mockup, you can compare it with the screenshots above. here are the things that i would like to mention:
- let's get rid of the loading/syncing line from all screens except the chats, contacts and discover. it just looks wrong on blue background and there is no indication what it actually means, so there's no point in it.
- the qr reader is always square;
- the width of the buttons are the same as the width of the QR reader
- the border radius of the QR reader should be the same as the border radius of the buttons.

![ios_wallet-send-recipient](https://user-images.githubusercontent.com/3115606/30636332-cd3256ca-9dfd-11e7-838b-37baca3b778b.png)

**Comment by sla-shi** [comment]
@asemiankevich can we close this, because we have updated the Send transaction UX?

**Comment by asemiankevich** [comment]
@sla-shi yes
