### ISSUE TITLE
Implement context action "View community rules"

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18978]
As a user,
I want to be able to see the community rules,
So I know how to behave in the community.

### Description

Currently we show some canned text for community rules, the actual rules should be displayed.

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15927-431360&mode=design&t=j9xL4xn1wE0KKjY0-4

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1388-104275&mode=design&t=nBBw5iB9Gl8L6cGt-0

**Comment by jo-mut** [comment]
the reported issues on this [#19200](https://github.com/status-im/status-mobile/issues/19200) are already fixed in the PR for this issue https://github.com/status-im/status-mobile/pull/19044
