### ISSUE TITLE
User should not be able to unselect all networks in multichain/network preferrences bottom sheet

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18972]
Discussion here, see point 2) https://discord.com/channels/624634427930312714/928625369542713396/1210596959312936972

**Steps:** 

1. Open Shell => Share => Wallet => Multichain => Network preferences
2. Try to unselect all networks
3. See if it is possible to update settings

**Actual result:** it is possible to unselect all networks. Update button is active. 

https://github.com/status-im/status-mobile/assets/97245802/75a92a78-4f80-415b-a1d2-73ec48dffd69

**Expected result:** I am not sure what is the expected result here. From [Figma](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=9650-194298&mode=design&t=EitbPMUCaZdghr5X-0) it is not clear for me what happens if user unselects all networks or if it should be possible to unselect all of them. I beleive we will need input from design team here. 

 
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
@smohamedjavid - I believe you looked at networks settings pieces recently, was this resolved elsewhere/already?

**Comment by smohamedjavid** [comment]
This is not fixed yet. I will add a fix in the open PR #19150 as it updates that sheet. 👍

**Comment by J-Son89** [comment]
Thanks @smohamedjavid
