### ISSUE TITLE
Polish "New chat" view

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18981]
### Description

The new chat view has some bits and pieces missings:
- New chat is displayed instead of new group chat when selecting multiple users
- The header with the letter is not sticky
- There's no blur under the button

Feel free to create separate issues, address separately

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720-549016&mode=design&t=nplOuMxagSfPr29p-4

**Comment by BalogunofAfrica** [comment]
Hi @cammellos by the button here, you mean the cancel button right?
