### ISSUE TITLE
[Communities] Implement Community Detail Token Gating component

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#18995]
Follow up #18638 

[Figma design system](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=35933-64264&mode=design&t=tOndjZ5fVHct6hh1-0)

### Description
While implementing the permissions drawer, it was discovered that our design system lacks a specific component essential for this feature. As a result, the feature was implemented without the integration of this missing component.

### Design

![image](https://github.com/status-im/status-mobile/assets/5999878/270b6602-e8bf-4254-b61d-cd9969d36273)

### Acceptance Criteria

- Follow Figma
- Pass correct props
- Keep interactions
- Follow [guidelines](https://github.com/status-im/status-mobile/pull/18926/files)
### Notes

Probably the current code can be reused and adapted.

**Comment by ibrkhalil** [comment]
I think this component is already implemented.

**Comment by cammellos** [comment]
closing as completed

**Comment by ajayesivan** [comment]
Hi @cammellos, I'm reopening this issue since it is still relevant, I'm working on it. A similar component exists but it doesn't fully comply with the design system(Figma). It also doesn't support collectibles. Let me know if there is any other reason for closing it.
