### ISSUE TITLE
'No protocol method IDeref...' when opening notifications settings

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19012]
**Steps:** 

1. Go to Profile => Notifications
2. Observe the result

**Actual result:** 'No protocol method IDeref. -deref defined for type underfined' when opening Notifications settings

![photo_2024-02-27 12 05 32](https://github.com/status-im/status-mobile/assets/97245802/016662b9-2f7c-4ede-ab74-0f5c441b5eea)
[Status-debug-logs - 2024-02-27T120507.781.zip](https://github.com/status-im/status-mobile/files/14417776/Status-debug-logs.-.2024-02-27T120507.781.zip)

https://github.com/status-im/status-mobile/assets/97245802/756a3bbe-bccf-4fcd-af74-b0dce33e88c0

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
ERROR  re-frame: no subscription handler registered for: :push-notifications/wallet-transactions. Returning a nil subscription.
 ERROR  re-frame: no subscription handler registered for: :push-notifications/wallet-transactions. Returning a nil subscription.
most likely was removed here https://github.com/status-im/status-mobile/pull/18749
