### ISSUE TITLE
Universal link inserted into the search field instead of chat key when scanning a profile QR code

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19022]
# Bug Report

## Problem 

<img width="318" alt="Screenshot 2024-02-27 at 16 05 49" src="https://github.com/status-im/status-mobile/assets/67952253/d7dabf33-c745-4e54-bfcd-fe20ef0f9b75">

#### Expected behavior

Chat Key or ENS should be inserted when scanning a QR code

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1694-380170&mode=design&t=Seto34wFS3970w4Y-4

### Reproduction

1. UserA opens sharing screen with a QR code
2. UserB: press `+` button on the `Messages` home screen > `Add a contact` tap the `scanner` button > Scan the QR

### Additional Information

- Status version: nightly 27/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1694-380170&mode=design&t=w9otIanVGb6ao9uF-4
