### ISSUE TITLE
App crashes after restore via seed phrase

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19023]
Wait until this one https://github.com/status-im/status-mobile/pull/19024 will be merged (status go version bumped) in order to reproduce in mobile develop. 

**Steps:** 

1. Restore user via seedphrase
2. See if app does not crash after restoration

**Actual result:** app crashes. Works fine after relogin. 

[crashlog_restore.log.zip](https://github.com/status-im/status-mobile/files/14418458/crashlog_restore.log.zip)

https://github.com/status-im/status-mobile/assets/97245802/04ae5327-3fc8-4727-b422-3eea63ecfc34

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by mohsen-ghafouri** [comment]
@pavloburykh please check if they are related https://github.com/status-im/status-mobile/issues/18622

**Comment by pavloburykh** [comment]
> @pavloburykh please check if they are related #18622

Hey @mohsen-ghafouri! These issues seem to be different: current issue is reproducible constantly on all platforms and has been introduced recently. This one https://github.com/status-im/status-mobile/issues/18622 is reproducible randomly and only on certain IOS versions. But we will see, maybe this PR https://github.com/status-im/status-go/pull/4821 will fix both issues.
