### ISSUE TITLE
Cannot scroll transaction history when app is syncing

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#1902]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

When the app is syncing I cannot scroll the transaction history (this probably applies to other lists ?)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Replace the subscription by `(atom :in-progress)` here https://github.com/status-im/status-react/blob/develop/src/status_im/components/sync_state/gradient.cljs#L77

Use an account with enough transactions to require scrolling in history tab (more than 10 depending on screen size)

Try to scroll

**Comment by asemiankevich** [comment]
Fixed in 0.9.10-117-g08d1f94e+

**Comment by annadanchenko** [comment]
Tested ok in develop  0.9.11d266 Will be in release 0.9.12
