### ISSUE TITLE
The scanned valid ETH address is not pasted into the "Send to" page field after QR scanning.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19050]
### Steps:
1. Go to the Send to page
2. Scan eth address

### Actual result:
The scanned valid eth is not pasted into the Send to page field

https://github.com/status-im/status-mobile/assets/52490791/500e1cc2-04d5-439e-9d41-b9822be02b13

### Expected result:
The scanned valid eth address should be automatically pasted into the "Send to" page field.

### Devices:
IOS, Android

### ENV:
nightly 29 Feb 2024

**Comment by mmilad75** [comment]
This issue is implemented here https://github.com/status-im/status-mobile/pull/19250 which should be merged soon
