### ISSUE TITLE
Make changes to Choose Recipient screen

### ISSUE THREAD

**Issue by x-goose-x** [status-im/status-react#1905]
### User Story

As a developer, I want to update the choose recipient screen to match design changes.

### Description
There have been changes to the design of the wallet send screens. The Choose Recipient screen was initially the first screen in the flow, but this has now changed. Additionally, there have been some style changes to the QR viewport, to text in the window, and icons.

*Type*: Feature

*Summary*: 
- [ ] Update text
- [ ] Style changes to QR viewport
- [ ] Style changes, ios
- [ ] Style changes, android

[design link, ios](zpl://screen?pid=58aac7d018d4584d91998e79&sid=59c2944b51a607371b6650cd)

[design link, android](zpl://screen?pid=58aac7ae739bb1a592705d34&sid=59c299224a9ed6d71ae42fe3)

**Comment by sla-shi** [comment]
Part of #1773 and eventually #1525

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
