### ISSUE TITLE
Push notifications: surface notification and data payload on iOS

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1906]
### User Story

As a developer, I want to see data (invisible) and notification (visible) payload passed through when app is backgrounded and you click on notification.

Android is a different issue because it requires additional logic.

Related to https://github.com/status-im/status-react/issues/1883

Type: Feature
Platform: iOS only

### Notes for testing

1. Trigger a push notification by chatting with a contact with app in background
2. Click on the notification
3. Check logs and grep for `on-notification` - this should print something like:

```
on-notification aps:  {:alert {:title "Status - new message", :body "ping"}}
on-notification data:  {:sum "Happy Day", :msg "Hello World1"}
```

**Comment by annadanchenko** [comment]
After tap on notification, there are these lines in log:
`default	16:30:22.794767 +0300	StatusIm	DEBUG [status-im.utils.notifications:46] - on-notification aps:  {:alert {:title "Status - new message", :body "ping"}}

default	16:30:22.795366 +0300	StatusIm	DEBUG [status-im.utils.notifications:47] - on-notification data:  {:sum "Happy Day", :msg "Hello World1"}`

iOS only
build  0.9.11d120 
Branch: feature/notification-payload-#1906
iOS: https://i.diawi.com/KZ7XNi

**Comment by oskarth** [comment]
Fixed in develop. For clarity of parent issue.
