### ISSUE TITLE
'failed to send a message: {:code -32000, message: "can't post in chat"}' error and blocked input field in token gated channel

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19069]
Reproduced the issue in release branch and in this PR https://github.com/status-im/status-mobile/pull/19049

Example of community with token gated channels https://status.app/c/G7oAAGS97fu-b48K2keTDhMK06pUxAA24MAt00Qn32xQGyZyFljSdqArH8TXpp4XZJHqHqwr35ShtoCJ8-jT9ikYjQA=#zQ3shrEJ1GuDRnSnCBuJpGW88ovc2UiQQsQ8PGatYKGJy4KTY

**Preconditions:** User A is a member of community and meets channel requirements to View and Post in token gated channels

**Steps:**

1. Recover User A
2. Wait until communities are recovered
3. Open community with token gated channels
4. Post some messages in token gated channel
5. Observe the result

**Actual result:** 
at some point posting messages results in ```failed to send a message: {:code -32000, message: "can't post in chat"}``` error 
after channel re-opening input field becomes disabled. 

[logs (24).zip](https://github.com/status-im/status-mobile/files/14457972/logs.24.zip)

https://github.com/status-im/status-mobile/assets/97245802/5cad62ad-39a8-4696-8e02-3119080c6eaf

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by anastasiyaig** [comment]
We tested it together with @pavloburykh and i faced the same. When i post the messages in the channel, they are not showing up at all, and i dont get any errors from client at all. However, there is an error in geth.log

```
DEBUG[03-04|16:31:25.790|github.com/status-im/status-go/protocol/messenger_communities.go:571]                       watching communities to unmute 
DEBUG[03-04|16:31:25.845|github.com/status-im/status-go/wakuv2/waku.go:1673]                                         not querying bootnodes                   seeded=true peer-count=4
DEBUG[03-04|16:31:25.850|github.com/status-im/status-go/protocol/communities/community_description_encryption.go:83] failed to decrypt community private data keyIDSeqNo=0cea362bc1e8d9fcdd1c784d6ff0f80c42785b38f59b54a82e753e6b1a9cb0232 error="no ratchet key for given keyID"
DEBUG[03-04|16:31:25.850|github.com/status-im/status-go/protocol/communities/community_description_encryption.go:83] failed to decrypt community private data keyIDSeqNo=d16007f455e32b8328f82564dea84d9937d1f06aa0a790e292de07f66593f2fd2 error="no ratchet key for given keyID"
```

@jrainville @osmaczko can you pls take a look as well?

**Comment by jrainville** [comment]
ah, so this is from a recovered account. It makes sense why I never saw it before.

Can rachet keys be recovered from the store nodes? I think they should, but with the state of the store nodes being uncertain at most points, maybe it's worth implementing some kind of signal when a node sees that it doesn't have any ratchet key to a community. They send that message to the control node in the hopes that it will send back the ratchet key?

Would that make sense @cammellos @osmaczko ?

**Comment by igor-sirotin** [comment]
Looks to me like it's related to all other channel permission issues 🤔

**Comment by cammellos** [comment]
I think this might be related to infura tokens, I have restarted desktop using an infura token that is valid, and it works fine, is it possible that it's due to that?

**Comment by anastasiyaig** [comment]
@alaibe i remember we had some issue with fetching collectibles where we were suspecting api keys as well in ci builds, could it be the case? @dlipicar do u have insight on this maybe?

**Comment by cammellos** [comment]
ok, a bit more complicated I guess :) , it stopped working now, after I created a few channels, the member gets the same error

**Comment by cammellos** [comment]
ok, it's probably both maybe, but most likely there's an issue with encyrption and community description channel keys, we fixed that for the main community ecnryption, but the issue is still there for channels, looking into it

**Comment by jrainville** [comment]
Does either of you have a bad network or low peers? Seems like when you create a channel, the keys don't reach them fast enough?

> I think this might be related to infura tokens, I have restarted desktop using an infura token that is valid, and it works fine, is it possible that it's due to that?

This for sure doesn't help. If the control node has difficulty with Infura/Pokt, the yes, it will not be able to evaluate the member correctly, so indeed, they would not receive the key because they won't be in the member list.

Don't forget the OpenSea key too. Also, just in case, Goerli is not very good anymore

**Comment by dlipicar** [comment]
@anastasiyaig the CI keys were fine, there was an issue in our code. 

Rarible is throttling our requests since they implemented paid plans and we got "downgraded" to the free tier. We've got a retry mechanism in such cases, and after some time we're supposed to drop that provider and try with another one (Alchemy), but that part wasn't working OK.

**Comment by dlipicar** [comment]
@jrainville The most reliable ones are Alchemy and Rarible, so I'd make sure to have those keys set up. Opensea will randomly consider your NFT is spam and not include it in the results when requesting owned NFTs for a given account.

**Comment by pavloburykh** [comment]
seems like it is fixed by https://github.com/status-im/status-mobile/pull/19153
