### ISSUE TITLE
Push notifications: surface notification and data payload on Android

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1907]
### User Story

As a developer, I want to see data (invisible) and notification (visible) payload passed through when app is backgrounded and you click on notification.

### Summary
Same as https://github.com/status-im/status-react/issues/1906 but for Android.

Android appears to require setting click_action at the top level (this would be a change on status-go side too), and there seems to be some issues in setting notif and data payload concurrently.

`react-native-fcm` documentation on how to handle this case:
> When app is running in background (the tricky one, I strongly suggest you try it out yourself)

and there's also an open issue with `question` label at https://github.com/evollu/react-native-fcm/issues/569 which isn't very encouraging, hence platform specific issue.

Related to https://github.com/status-im/status-react/issues/1883

Type: Feature
Platform: Android

### Notes for testing

1. Trigger a push notification by chatting with a contact with app in background
2. Click on the notification
3. Check logs and grep for `on-notification` - this should print something like "hello1" and "ping"

**Comment by pedropombeiro** [comment]
Replaced with https://github.com/status-im/status-react/issues/3451
