### ISSUE TITLE
Implement Material You themed icon

### ISSUE THREAD

**Issue by du82** [status-im/status-react#19077]
All of my apps follow the Material You icon theming except for Status, so that decentivizes me from putting it on the home screen.

![signal-2024-03-01-09-10-36-019](https://github.com/status-im/status-mobile/assets/65834069/f84cf9ee-89e0-41ba-b035-af1f5b065102)

**Comment by siddarthkay** [comment]
link to technical implementation for whoever picks this up -> https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by du82** [comment]
Merged PR, closing issue
