### ISSUE TITLE
Improve debug build times for android 

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#19081]
# Problem

The debug build variant rules need to be tweaked a little so that we improve the build times.

Sometimes due to unrelated changes, the nix derivation still does a full rebuild of the android code and it takes upto 10 minutes on each `make run-android`

Ideally we want to only do a full derivation rebuild when any files are touched which are supposed to make it into the `apk` and changes to other files should be ignored when considering a `nix` derivation build.

At the moment we use git to see if anything has changed or not, so that logic could be tweaked to further improve local debug build times.

**Comment by OmarBasem** [comment]
Hey @siddarthkay any updates on this issue :)

> takes upto 10 minutes

Btw it takes about 15+ minutes on my machine :(

**Comment by siddarthkay** [comment]
Hey @OmarBasem : Still working on this one. I definitely feel bad for the 15 minutes per build on your end.

I have a linux box (NixOS) and over there the 1st time android build times are 3 mins and on my macbook m2 its close to 8-9 minutes.

I'll update the issue here in comments with progress.

**Comment by OmarBasem** [comment]
Hey @siddarthkay, I was trying to test how often it attempts to go through the whole build process, and it seems if there is a single line of code change in the `cljs` code it will rebuild the whole app, even if the app was just built.

**Comment by siddarthkay** [comment]
Hey @OmarBasem : apologies for silence on this issue.
Yeah what you observed happens because our build step relies on building the `jsbundle` derivation.

The initial idea was to keep the debug build process identical to the release one on CI so that there are fewer discrepancies in build issues. i.e what would fail/pass on CI would also fail/pass locally.

I am working to make debug builds a bit faster and would update this issue, this week.

Thanks for the patience.
