### ISSUE TITLE
[Android] Blink of shell screen occurs when the [Enter or enter sync code] button is tapped on the Syncing screen.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19096]
### Steps:
1. Go to Syncing
2. Tap [+] 
3. Tap [Enter or enter sync code] button
4. Tap 'back' button

### Actual result:
- The shell screen blinks when the [Enter or enter sync code] button after step 3
- Wrong navigation after step 4

https://github.com/status-im/status-mobile/assets/52490791/398cadf3-8c20-483a-a94c-d506ff1f8adc

### Expected result:
- The "Pair devices to sync" screen should be shown without blinking when the [Enter or enter sync code] button is tapped.
- When the back button is tapped, the user should be navigated to the 'Pair devices to sync' screen

### ENV:
Nightly [4 Mar 2024]

**Comment by Parveshdhull** [comment]
Hi @VolodLytvynenko, Thank you for reporting the issue.
Please can you try reproducing this in latest develop? (Issue should have been fixed in https://github.com/status-im/status-mobile/pull/19080)

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko, Thank you for reporting the issue. Please can you try reproducing this in latest develop? (Issue should have been fixed in #19080)

Hi @Parveshdhull Correct, the initial issue is fixed. Now new blink and wrong navigation are introduced after merging https://github.com/status-im/status-mobile/pull/19080. I have changed the description in https://github.com/status-im/status-mobile/issues/19096#issue-2167330453
