### ISSUE TITLE
Routes are not found after initially entering the available amount.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19099]
### Steps:
1. Restore the account with available assets.
2. Go to the Send to page.
3. Enter an approximate sum close to the available amount.

### Actual result:
Routes are not found when the available mainnet assets are entered. The routes are found only after entering the amount multiple times.

https://github.com/status-im/status-mobile/assets/52490791/dc105e0a-119a-4068-8783-11cb00d20b35

### Expected result:
Routes should be found when the available mainnet assets are entered.

### Notes:
When I enter 0.01 ETH, the routes already can't be found. I thought it might be due to not enough ETH for the gas fee, but as I checked in MetaMask, the gas fee is only 0.0034 ETH)

### Logs:
[logs (2).zip](https://github.com/status-im/status-mobile/files/14485037/logs.2.zip)

### ENV:
Nightly [4 Mar 2024]

**Comment by briansztamfater** [comment]
@VolodLytvynenko When you have time, can you check if this is still happening? I fixed a similar bug while implementing #18986 and I wonder if that fixed this one

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko When you have time, can you check if this is still happening? I fixed a similar bug while implementing #18986 and I wonder if that fixed this one

Hi. Issue is fixed. @briansztamfater thank you
