### ISSUE TITLE
After logging out, the list of profiles is not displayed

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19094]
Unfortunately, there are no exact steps to reproduce this issue. It seems to happen randomly. Hope that the logs can provide more info what's going on

### Steps:
1. Leave logged in user for a while (2-3 minutes)
2. Tap log out
3. Navigate to the list of profiles
![image](https://github.com/status-im/status-mobile/assets/52490791/15ae873e-3346-47a9-bf8d-fed8b2e7017f)

### Actual result:
The empty screen is shown

https://github.com/status-im/status-mobile/assets/52490791/5ce47226-e032-4c8b-ac37-df38eacc7ec5

### Expected result:
The list of profiles is shown

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14484427/logs.zip)

### Env:
Env [4 Mar 2024]

**Comment by mohsen-ghafouri** [comment]
I did these steps and there is high chance to see this issue 

https://github.com/status-im/status-mobile/assets/71308738/67263d89-d96a-4aff-847b-c02e319b2c39
