### ISSUE TITLE
Bring back and fix audio recording in the chat

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19109]
# Bug Report

## Problem 
[comment]: # (A problem description)
Currently audio recording is [disabled](https://github.com/status-im/status-mobile/issues/16084). We should bring it back, but some of the things that must be fixed are:
1. Use a different audio playback library, as `@react-native-community/audio-toolkit` is no longer maintained and causes issues e.g. https://github.com/status-im/status-mobile/issues/13467
2. Replace ratoms with `use-state` and atoms with `use-ref-atom`
3. Use `react-native-gesture-handler` for the gestures

#### Expected behavior
Audio recording and playback are responsive to gestures and the animations are smooth

#### Actual behavior
Audio recording is currently disabled, but if enabled
1. it's unresponsive to gestures (dragging the button is lagging behind the gesture by ~1s)
2. animations feel slow
3. moves only along the y or x axis, but never in between

**Comment by J-Son89** [comment]
@clauxx - why is this an active issue? Is this agreed upon in terms of priorities? 
cc @cammellos @ilmotta ?

**Comment by clauxx** [comment]
I assigned it before going the offsite as something to look into, but since the priorities and team structure changed, I'll un-assign myself cause it's not going to be a priority for a while I guess.

**Comment by cammellos** [comment]
> @clauxx - why is this an active issue? Is this agreed upon in terms of priorities?

Not for now, I'll be closing this and we can reopen once ready to be worked on
