### ISSUE TITLE
Frozen login screen occurs after specific user is logged in

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19116]
Thank you @ulisesmac for debugging this issue and pointing some details [here](https://github.com/status-im/status-mobile/pull/18921#issuecomment-1979600575)

### Steps:
1. Recover user with data (communities, contacts, wallets)
2. Log out.
3. Check the login screen.

### Actual result:
The login screen becomes frozen, and the buttons are unresponsive.

https://github.com/status-im/status-mobile/assets/52490791/325ea048-9924-485f-82da-3bce6f5a038c

### Expected result:
The buttons on the login screen should remain responsive after logout, allowing the user to interact with them.

### NOTE:
It's interesting because this issue is reproducible only for this specific user that has a lot of data (communities, contacts, wallets), but it's not reproducible for other users who also have a lot of data. Initially, I thought it might be related to an old issue, but in the old issue https://github.com/status-im/status-mobile/issues/18738, it was reproducible randomly and very rarely

### Logs:
[logs.txt](https://github.com/status-im/status-mobile/files/14496723/logs.txt)

**Comment by pavloburykh** [comment]
related to https://github.com/status-im/status-mobile/issues/19042. Closing this issue.

**Comment by VolodLytvynenko** [comment]
It seems the current issue is related to one  https://github.com/status-im/status-mobile/issues/19042 that's already been created. Close it as a duplicate.
