### ISSUE TITLE
Pinned messages on the "Group details" screen are displayed for members only after opening the chat view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19114]
# Bug Report

## Problem 

If some message was pinned in a group chat, and I, as a member, go to `Group details` by long-press on the chat > `Group details`, pinned messages will not be updated there.
I'll need to open the chat view so that pinned messages are also updated in the `Group details` view. 

https://github.com/status-im/status-mobile/assets/67952253/b6b9f907-d334-4c86-87b4-1688ae85f8d8

#### Expected behavior
Pinned messages in the `Group details` view are updated without opening the chat

#### Actual behavior
Need to open the chat first to see new pinned messages on the `Group details` screen

### Reproduction

1. UserA: create a group chat, add UserB
2. UserA: send a message, pin it
3. UserB: long tap on the group on the home screen (without opening the group) > `Group details`

### Additional Information

- Status version: nightly 05/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@codemaster115 maybe you would like to have a look at this one since you are working a bit on pinned messages?

**Comment by flexsurfer** [comment]
hey @codemaster115 I already fixed this in my PR
