### ISSUE TITLE
Add "Change password" screen to settings

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19111]
# Bug Report

## Problem 
[comment]: # (A problem description)
Add the "Change password" screen to the settings according to the current state of the designs (might change in the future). The design is not very different from the onboarding "Create password" screen, so we're not loosing much by just adding it but we're gaining the ability to change the password at least.

[Design link](https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=6638-397016&mode=design&t=buA3cDaY8vTO0BeZ-4)
> Discussed with @cammellos and decided to add it to this crew's project
#### Expected behavior

Can change the password from the new settings

#### Actual behavior

Cannot change the password from the new settings

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Can you add link to the designs?

**Comment by clauxx** [comment]
> Hi @clauxx !
> 
> Can you add link to the designs?

Hi @mariia-skrypnyk! Added to the description the [design link](https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=6638-397016&mode=design&t=buA3cDaY8vTO0BeZ-4)
