### ISSUE TITLE
Wallet: portfolio management and calculations (long-term)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1912]
### User Story

As a user, I want the Status wallet to show how all assets in my portfolio are doing, so I know what my financial health is and it can inform financial decisions.

### Description

This issue is too big as it stands, but I'm using it as an opportunity to capture and clarify how I envision the wallet portfolio calculation working. I'll do this by way of example.

As we progress with these capabilities and we have a better understanding of the problem space, this issue can be closed. There is thus no specific deliverable or end in this issue, other than what has been described in the user story above.

A portfolio consists of multiple assets. Each assets has some valuation in a certain currency (henceforth USD, for simplicity's sake). This valuation fluctuates from day to day. The amount a user has of a certain asset also fluctuates, but usually not on a day to day basis by that much.

As an end user, if I invest $100 USD in crypto and this includes ETH, SNT, etc I want to know roughly how much my portfolio is worth in USD if I were to liquidity it. I also want to know how I'm doing - is my portfolio going up or down in terms of USD? Of course, USD is arbitrary and it could be measured in ETH, BTC or number of second-hand Saabs 93s.

### Example 1 -  Not all asset allocations are equal

I own two assets, A and B. 10 A and 10 B. One A is worth $100 and one B is worth $10. The whole portfolio is thus worth $1000+$100=$1100. In terms of portfolio composition, 90% of my money is in A. If A goes up 10% and B down 10%, my total portfolio, valued in USD, has gone from 1100 to 1100+90=1190. This represent a 8% increase in portfolio value.

### Example 2: Day trading gone wrong

Same portfolio but I sell my assets A before the market starts moving and don't capture any gains. I thus have $1000 that I liquidated from A, and when market closes (or 24h later, say) B has gone down 10%. After 24h my portfolio value is 1000+90=1090, which represent a 1100/1090 a 1% decrease.

This case is a bit tricker since we don't necessarily have all the trading data. Thus it makes sense to assume a static portfolio and only compare last 24h with now. At least for now.

### Example 3: Starting from nothing

If I don't own any assets, or, equivalently, only own USD (or whatever you measure portfolio value in), then the portfolio value never changes. It thus makes sense to say this represent a 0% (or -%) change on any time horizon.

### Example 4: A new kid on the block

A new asset C is introduced and we don't have any pricing information on it, but it still part of the wallet. I suggest we visually indicate this by greying out that asset somehow, to make it clear that it's not part of the portfolio calculation. This seems like a design question though.

Those are all the scenarios I can think of now, on a high level.

cc @jeluard @yenda

**Comment by asemiankevich** [comment]
Issue moved to [status-im/ideas #30](https://github.com/status-im/ideas/issues/30) via [**ZenHub**](https://www.zenhub.com/)

**Comment by asemiankevich** [comment]
Issue moved to [status-im/ideas #29](https://github.com/status-im/ideas/issues/29) via [**ZenHub**](https://www.zenhub.com/)
