### ISSUE TITLE
Feature: Mark known contact as untrusted

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19136]
depends on #19133 

Here's link to [the Figma designs](https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=29-72884&mode=design&t=dRUoRN1hi4s0DCDk-4).

### User Story

As a user, I wish to mark a known contact as untrusted, and ideally 

- [ ] I would find a "mark as untrusted" action inside a contact's profile action menu:
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/65c23f3c-fb08-4137-95c3-79ae55b218a5)
- [ ] I would see a confirmation modal after pressing the "mark as untrusted" action:
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/7e93f48c-754f-4a97-a13f-c81f83b98119)
- [ ] I would be allowed to optionally remove the user as a contact 
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/41d879d4-5161-44ab-b9f0-e13fedf7f9d5)
- [ ] And if I choose to mark the user as untrusted then I would see a toast
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/b6ee9480-0319-4525-bad9-5bfe6d077ff8)
- [ ] Or If I choose to mark the user as untrusted and remove them as contact then I would see a toast
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/dbf289b2-2f3b-40d7-9527-f1c39d67df57)

**Comment by ilmotta** [comment]
Closing the issue because contact verification features are not in the roadmap.
