### ISSUE TITLE
Feature: Mark unknown contact as untrusted

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19133]
Here's a link to [the Figma designs](https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=19-59370&mode=design&t=dRUoRN1hi4s0DCDk-4)

### User Story

As a user, I wish to mark an unknown contact as untrusted, and ideally 

- [ ] I would find a "mark as untrusted" action inside a contact's profile action menu:
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/ad326f67-8d6b-4bcc-bd5e-b24f48f27911)
- [ ] I would see a confirmation modal after pressing the "mark as untrusted" action:
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/96ca9a2f-f267-4f78-b9db-33d24b392cc7)
- [ ] I would see a toast reporting that I did untrust a contact
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/47be3904-07d4-429e-86aa-ab80ad5163d3)

**Comment by J-Son89** [comment]
Can we move to 2.31? 🤔

**Comment by J-Son89** [comment]
closing as Trusted contacts is not being actively developed for a good while.
