### ISSUE TITLE
"Optimism is down" toast after switching to testnet mode on login

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19135]
# Bug Report

## Problem 

Leftover of https://github.com/status-im/status-mobile/pull/18850
@smohamedjavid could you check this please? Apparently, I missed this when testing the latest PR build.

### Reproduction

1. Create a profile
2. Settings > Switch to the testnet mode
3. Log in

#### Expected behavior
No banner since the Optimism network seems to be okay

#### Actual behavior
<img width="317" alt="Screenshot 2024-03-07 at 18 50 50" src="https://github.com/status-im/status-mobile/assets/67952253/9f95cb93-5434-47f8-a64a-7ad5f9166251">

### Additional Information

- Status version: nightly 7/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
Fix in https://github.com/status-im/status-mobile/pull/19155
