### ISSUE TITLE
fix unnecessary re-render in contact list

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#19130]
Contact list re-renders when not needed, which makes the user avatar flash. 

Follow up based on comment here https://github.com/status-im/status-mobile/pull/19054#issuecomment-1979274959

**Expectation:**
Contact list should not re-render unnecessarily which would cause avatar image to flash

**Actual Result:**
https://github.com/status-im/status-mobile/pull/19054#issuecomment-1979274959

**Comment by flexsurfer** [comment]
fixed here https://github.com/status-im/status-mobile/commit/446d71063c6c31b51913a046b993b48c82c56e14
