### ISSUE TITLE
No validation error "Insufficient funds.." in chat if try to send more than available in Wallet [0.9.11]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1913]
### Description

*Type*: Bug

*Summary*: There is no error message if user tries to send more ETH than available. Expect to have "Insufficient funds..." error shown in chat after user taps on send button. 

Sometimes error happens after first attempt, sometimes after 3-4 attempts

#### Expected behavior
"Insufficient funds..." error shown in chat after user taps on send button.
#### Actual behavior
Unsigned transactions screen is shown. User can provide password and tap on Confirm. After this chat is shown with error "Transaction failed" 

### Reproduction
3rd attempt: https://app.testfairy.com/projects/4803590-status/builds/6582146/sessions/19/?accessToken=4FowjUu/M30wmK4NtLpi098H7T4
1st attempt: https://app.testfairy.com/projects/4803590-status/builds/6582146/sessions/23/?accessToken=jE8GqqUNqYUK5/nf2gVp4-OEGc0
After sync is done, when 0 eth in Wallet 
- Open Status
- Open 1-1 chat with Jarrad (in Contacts tap on Jarrad)
- Tap on /send command, select Jarrad as recipient, type 100 as amount and tap on button send (at the end of input field, button with arrow up)
- If error message "Insufficient funds.." is shown then delete the amount, type 20 and send
- If error is shown again type 0 next to 20, so amount is 200 and tap send 

Note: it's easier to get an issue when app is just launched or when it was not used for some time, but it's also possible to get it in normal situation just need to make more than 1-2 attempts
 

### Additional Information
* Status version: release candidate 0.9.11   0.9.11d105 
* Operating System: 
Real device iPhone 7 plus, iOs 10.3.2
Real device Samsung Galaxy S6, Android 6.0.1

**Comment by annadanchenko** [comment]
issue also exists in `bugfix/eth-send-tx-#1899` with fix from go team `bugfix-eth-send-transaction-routing-#350`

https://app.testfairy.com/projects/4803622-status/builds/6609816/sessions/8/?accessToken=9jo934IjoVP97js8q1s0eFSGNoY

**Comment by jeluard** [comment]
@annadanchenko Is this still relevant?

**Comment by annadanchenko** [comment]
can't reproduce on nightly March 19
