### ISSUE TITLE
Wallet(Collectibles/Send) - Add backend support for sending multiple collectibles

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#19143]
once the UI is added for sending multiple collectibles -
i.e these issues:
https://github.com/status-im/status-mobile/issues/19141
and possibly https://github.com/status-im/status-mobile/issues/19142 - although it is not definitely needed.

update the rpc calls for sending a collectible to support sending multiple collectibles

**Comment by BalogunofAfrica** [comment]
Closed here https://github.com/status-im/status-mobile/pull/20045
