### ISSUE TITLE
No banners working for recovered by a seed phrase account

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19147]
# Bug Report

## Problem 
[comment]: # (A problem description)
User created by using a seed phrase doesn't receive any banners inside the app. It only fixes by a logout.

#### Expected behavior
Banners are working for every user.

#### Actual behavior
No banners working for recovered by a seed phrase account

https://github.com/status-im/status-mobile/assets/147824399/14ef5c35-e380-4af6-ac22-cb1eadbc7878

### Reproduction

1. Sign up a new user by a seed phrase
2. Add one contact
3. Open chat with your contact
4. Add 7 images to the message 

### Additional Information

- Status version: nightly (8/03)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Unfortunately, Can't reproduce.

**Comment by churik** [comment]
@mariia-skrypnyk is it reproducible consistently for you?

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk is it reproducible consistently for you?

No it happens not only for me, @ibrkhalil just have no time to reproduce it once again.

**Comment by flexsurfer** [comment]
hey @mariia-skrypnyk could you pls add the expected result for Reproduction steps, and could you pls elaborate on what you mean by banners? thank you

**Comment by jo-mut** [comment]
not reproducible for me

**Comment by Parveshdhull** [comment]
> could you pls elaborate on what you mean by banners?

@flexsurfer, I think @mariia-skrypnyk means this banner
![image](https://github.com/status-im/status-mobile/assets/17097240/b3a44afc-48c8-4f28-98bb-7a83d438af27)

I also just tried above steps and for me too banner visible as expected.

> It only fixes by a logout.

If logout fixes this, then I think this is low priority issue.

**Comment by mariia-skrypnyk** [comment]
Hey all! @flexsurfer @Parveshdhull @jo-mut 

Thanks for trying to reproduce it.
I've rechecked it and I also doesn't see it anymore.

So I will close it. Thanks for help!
