### ISSUE TITLE
The colors for netwroks attributes are not resolved during adding eth into watch-only address

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19156]
### Steps:
1. Go to watch-only address flow
2. Add a multichain ETH address to the "eth address" field. ( Example: eth:arb1:opt:0x42dd716de01943e40fc1d7f53feb4ffe16056c85)

### Actual result:
The color is not resolved for **eth:arb1:opt:** attributes 
- On the Add address to watch screen
![image](https://github.com/status-im/status-mobile/assets/52490791/baec83f5-3229-4e51-9d76-e639e5047617)

- On the color picker screen
![image](https://github.com/status-im/status-mobile/assets/52490791/ad21dd08-fb71-40a2-bb15-e63fe08eded8)

### Expected result:
The color is resolved for **eth:arb1:opt:** attributes 
- https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522339&mode=design&t=KPbzlfDAyyuHzlau-0
- https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522184&mode=design&t=KPbzlfDAyyuHzlau-0

**Comment by J-Son89** [comment]
@mmilad75 does your recent work on that address component resolve this.
Perhaps it's separate but will use the same mechanism.

In any case, I think the network configuration for the watch only address stuff needs to be revisited so perhaps this issue could just be more generic and be to ensure the network configuration is working correctly & design wise for watch address flow?

**Comment by shivekkhurana** [comment]
I have a similar component with save address feature. The prefix is not added inline, but made available to select when you click the "Setting Knobs" button.


Here's the save address flow: 
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2087-615282&mode=design&t=c14riy23vGNdXsct-4

**Comment by J-Son89** [comment]
@shivekkhurana , @VolodLytvynenko , please note that one example is an input the other is not.

Adding this to a text input component could be very complicated. @mmilad75 experimented with this and found this to be the case.

Perhaps we should discuss with designers about having plaint text within inputs unless anyone knows of a trivial solution for it

**Comment by Parveshdhull** [comment]
might be possible to implement using masked view - https://github.com/react-native-masked-view/masked-view

**Comment by ulisesmac** [comment]
> @shivekkhurana , @VolodLytvynenko , please note that one example is an input the other is not.
> 
> Adding this to a text input component could be very complicated. @mmilad75 experimented with this and found this to be the case.
> 
> Perhaps we should discuss with designers about having plaint text within inputs unless anyone knows of a trivial solution for it

@mmilad75 
What is the strategy that you are using?

I think if we generate the text hiccup instead of directly edditing the input might work :thinking:

**Comment by J-Son89** [comment]
I will close this issue for now as we likely won't handle this 👍
