### ISSUE TITLE
Feature: Add option to mark contact as untrusted while removing contact

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19151]
depends on #19148 

Here's a link to [the Figma designs](https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=22-68824&mode=design&t=dRUoRN1hi4s0DCDk-4).

### User Story

As a user, I wish to remove a contact and optionally mark the contact as untrusted, and ideally 

- [ ] I would find a "remove contact" action inside a contact's profile action menu:
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/2b64af59-2764-436a-942c-1b9b5306d706)
- [ ] I would see a confirmation modal, along with an option to mark the contact as untrusted, after pressing the "remove contact" action: 
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/3c0634f1-68b5-4492-af76-93855be72001)
- [ ] I would see a toast reporting that I did remove a contact and marked the contact as untrusted
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/a7f24f9c-27db-43e9-9705-edfdeaf4b49d)

**Comment by ilmotta** [comment]
Closing the issue because contact verification features are not in the roadmap.
