### ISSUE TITLE
Creation of regular address instead of watch-only after removing current address

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19157]
### Steps:
1. Create an additional regular ETH address
2. Save the address of the created ETH address
3. Remove current address (take a look, for removing the feature flag should be enabled into Profile -> Feature flags -> enable 'remove account')
4. Go to watch-only address flow
5. Create watch-only address by pasting the ETH address of the removed regular address

### Actual result:
The regular address is created instead of a watch-only

https://github.com/status-im/status-mobile/assets/52490791/cf3f6453-c8e0-4c54-998d-3a348870099b

### Expected result:
The watch-only address is created

### ENV:
Nightly [8 Mar 2024]

**Comment by J-Son89** [comment]
nice catch @VolodLytvynenko!!

**Comment by ulisesmac** [comment]
@VolodLytvynenko I'm not sure if this is unexpected.
Do we have designs (or something else) that let us know what is the expected flow?

A derived address comes from the same seed phrase that we already own :thinking: so I think it's correct that it is added as one account we control.

Additionally, we create the addresses to watch and the derived accounts using the same status go function, so if this is a bug, this is the root of the problem.

@smohamedjavid @briansztamfater  @OmarBasem wdyt?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I'm not sure if this is unexpected. Do we have designs (or something else) that let us know what is the expected flow?
> 
> A derived address comes from the same seed phrase that we already own 🤔 so I think it's correct that it is added as one account we control.
> 
> Additionally, we create the addresses to watch and the derived accounts using the same status go function, so if this is a bug, this is the root of the problem.
> 
> @smohamedjavid @briansztamfater @OmarBasem wdyt?

@ulisesmac  Yes, you are right. After your message, I thought about it and think that I need to discuss this with the design team. I'll close this issue for now, and I think that this is a very rare edge case
