### ISSUE TITLE
Implement Quo - Drawer/Drawer Action component

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#19159]
Implement component
designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1931-31190&mode=design&t=ZqnluWYxsx6YSwOa-4

Acceptance Criteria:
component_spec tests
malli schema for component
preview screen
aligned with best practices

**Comment by Rende11** [comment]
I would like to implement it
