### ISSUE TITLE
Unable to input data into the "Send To" page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19158]
### Steps:
1. Go to the Sent to page
2. Attempt to input more than 2 characters into the input field.

### Actual result:
Only 1 character can be inputted into the field.

https://github.com/status-im/status-mobile/assets/52490791/6017cf23-573a-4f98-ab1e-0b8ba9992788

### Expected result:
The user should be able to input more than 1 character into the "Send To" input field.

### ENV:
nightly  [8 Mar 2024]

**Comment by ulisesmac** [comment]
@VolodLytvynenko 
I've tested it on Android and iOS and it's no longer reproducible on latest develop.

Are there any specific steps? if not, I think we can close this issue

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I've tested it on Android and iOS and it's no longer reproducible on latest develop.
> 
> Are there any specific steps? if not, I think we can close this issue

hey @ulisesmac
For me, this issue is still reproducible. There are no exact specific steps. I'm just trying to type data using keyboards. It's reproducible on both Android and iOS.


https://github.com/status-im/status-mobile/assets/52490791/6420b4f6-1b00-4e8b-abf8-8bb9f209340b




iPhone 11 Pro max, IOS 17
Pixel 7a, Android 14

**Comment by ulisesmac** [comment]
> > @VolodLytvynenko I've tested it on Android and iOS and it's no longer reproducible on latest develop.
> > Are there any specific steps? if not, I think we can close this issue
> 
> hey @ulisesmac For me, this issue is still reproducible. There are no exact specific steps. I'm just trying to type data using keyboards. It's reproducible on both Android and iOS.
> ios_type.mp4
> 
> iPhone 11 Pro max, IOS 17 Pixel 7a, Android 14

Maybe this is not the right video? :thinking:

**Comment by qoqobolo** [comment]
Hey @ulisesmac, I can reproduce the issue:


https://github.com/status-im/status-mobile/assets/67952253/b96d66c1-edad-48a4-bc76-503527047883

Steps:
1. Open wallet account
2. Tap `Send` 
3. Start typing in the `Send to` field

**Comment by VolodLytvynenko** [comment]
> > > @VolodLytvynenko I've tested it on Android and iOS and it's no longer reproducible on latest develop.
> > > Are there any specific steps? if not, I think we can close this issue
> > 
> > 
> > hey @ulisesmac For me, this issue is still reproducible. There are no exact specific steps. I'm just trying to type data using keyboards. It's reproducible on both Android and iOS.
> > ios_type.mp4
> > iPhone 11 Pro max, IOS 17 Pixel 7a, Android 14
> 
> Maybe this is not the right video? 🤔

Apologies for the wrong video. Just updated
