### ISSUE TITLE
[Android] push notifications are not received when local nofications are enabled

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#19161]
# Problem

After upgrading to react native 0.73.5 push notifications are not received. The foreground service is not launched immediately when notifications are enabled during onboarding which leads not push notifications not working even though local notifications are enabled

## Acceptance Criteria

App should receive push notifications when local notifications is enabled

**Comment by jo-mut** [comment]
if the push notifications permissions have already been granted, the foreground service launches without any issues and notifications seems to work well

the issue is only reproducible notifications when permission for push notifications have not been granted before when enabling notification during onboarding

**Comment by siddarthkay** [comment]
> the issue is only reproducible notifications when permission for push notifications have not been granted before when enabling notification during onboarding

wow this is strange, onboarding is the correct place to grant these notifications.
You observed this on Emulator or real device?

**Comment by jo-mut** [comment]
i have observed these on both emulator and real device

**Comment by jo-mut** [comment]
the issue affects android 13 and 14. After disabling and enabling location notifications, the foreground service is launch and the app can receive push notifications. This worked on android 13

**Comment by siddarthkay** [comment]
should be fixed with : https://github.com/status-im/status-mobile/pull/18563/commits/b9feb07ad676e7fc391b3aa9404afb89822e89a2 can you verify pls?

**Comment by jo-mut** [comment]
just a good articles on notifications FLAGS
https://medium.com/androiddevelopers/all-about-pendingintents-748c8eb8619

**Comment by jo-mut** [comment]
@siddarthkay notifications now work, thanks for fixing this
