### ISSUE TITLE
Feature: Reply to ID Verification request

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19170]
Here's a link to [the Figma designs](https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=30-99601&mode=design&t=bnvnO6HhhKErMm5a-4).

### User Story

As a user, I wish to be able reply to an ID Verification request, and ideally:

- [ ] I would find a "Reply to ID verification request" button inside a contact's profile
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/1b762c8f-4094-4f6a-87be-abd40d0de97b)
- [ ] I would see a "Reply to ID verification request" modal after pressing the "Reply to ID verification request" button
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/2686bc2c-b42b-4185-856f-3f220bef8cf7)
- [ ] I would be able to send a personalised answer with an ID Verification reply
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/0604b5b5-5bff-460b-94e7-d1f5c1241e6f)
- [ ] If I choose to send a reply, I would see a toast acknowledging that a reply was sent to the ID Verification request
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/afb1e8b4-52a0-455d-b0b5-ccade62003d5)
- [ ] If I choose to decline the ID Verification request, I would see a toast acknowledging that the ID Verification request was declined.
  * ![Image](https://github.com/status-im/status-mobile/assets/2845768/74ed51ec-24d0-4981-95cf-099386ce6134)

**Comment by ilmotta** [comment]
Closing the issue because contact verification features are not in the roadmap.
