### ISSUE TITLE
Onboarding - Spacing between Profile card and text

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19175]
# Design Feedback 2.27

## Spacing between Profile card and text
Figma comment [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727624801)

Tha spacing between the text and the Profile card is too narrow compared to design:

<img width="500" alt="Screenshot 2024-03-11 alle 15 31 38" src="https://github.com/status-im/status-mobile/assets/122543089/2b524e59-c472-43bd-964e-4cfdc2f54abc">

### Reproduction

1. Complete the Onboarding flow
2. Profile card is located in the _identifiers_ screens

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Closing the issue because the screen showing the unique identifiers is no longer displayed in the onboarding nor in other parts of the app.
