### ISSUE TITLE
Shell - Jump To screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19179]
# Design Feedback 2.27

## [Shell] Jump To screen
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=3%3A68309&mode=design&t=OeK3GHXzoVCNnZog-1)

- **No Status bar showing** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=3%3A68309&mode=design&t=OeK3GHXzoVCNnZog-1)] Changing the theme of status bar on the fly is not working in iOS due to a library issue [logged here: status-im/status-mobile/issues/15260
/ library issue: wix/react-native-navigation/issues/5446]
- **Close button on cards** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=3:68309&mode=design#711280486)] should have blur [logged here: status-im/status-mobile/issues/16836 (1)]
- **Photo placeholder in cards** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=34:5633&mode=design#716175333)] shouldn't be visible, when sending a photo to someone the chat card should display the actual photo that was sent, not the placeholder from the designs

<img width="500" alt="Screenshot 2024-03-11 alle 16 19 08" src="https://github.com/status-im/status-mobile/assets/122543089/8fcd5736-709c-4c78-871a-7f0c8ef4eff3">

### Reproduction

1. Open Jump To after opening a community / chat
2. Send a photo in a chat and re-open Jump To to see the chat card with the photo placeholder

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Closing as _not planned_ because Jump To feature is descoped and disabled by a feature flag.
