### ISSUE TITLE
Shell - Jump To tab animation issue

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19184]
# Design Feedback 2.27

## [Shell] Jump To tab animation
Opening and closing tab animation in the Jump To screen isn't smooth and isn't behaving correctly

#### Actual behavior

https://github.com/status-im/status-mobile/assets/122543089/e19b0d2a-ed33-43fe-85d2-bd166bbfd3cc

### Reproduction

1. Navigate to the Jump To by pressing the Jump To floating button
2. Open and close the tabs

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices used: iPhone 13, iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Closing because Jump To feature is disabled and descoped.
