### ISSUE TITLE
Missing cutout around the dot/counter on bottom nav [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19180]
# Design Feedback 2.27

## [Android] Missing cutout around the dot/counter on bottom nav
Figma frame with review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=3%3A68309&mode=design&t=OeK3GHXzoVCNnZog-1)

When receiving a notification the counter/dot in the bottom nav is missing a cutout, a margin between the color and the icon in the bottom nav:

<img width="393" alt="Screenshot 2024-03-11 alle 16 26 55" src="https://github.com/status-im/status-mobile/assets/122543089/78ef0bb1-371d-40c2-8f3b-8774f9459da6">

>
Design:

<img width="375" alt="Screenshot 2024-03-11 alle 16 27 26" src="https://github.com/status-im/status-mobile/assets/122543089/6ed8b674-74f0-4453-88e6-a1d096dd72e9">

>
**Reported:** https://github.com/status-im/status-mobile/issues/15577 
https://github.com/status-im/status-mobile/blob/c5de05432436798a87a205edc91082d8e4f07161/src/quo2/components/navigation/bottom_nav_tab.cljs#L52

### Reproduction

1. Receive a notification (message or mention in community) that will show a dot or a counter in the bottom nav bar

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Closing because this issue no longer exists since 2.30.0.
