### ISSUE TITLE
Add biometrics support on join community screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19188]
Currently user can confirm sending community request only using password even if biometric auth is enabled. 

As a user I want be able to confirm sending community request using biometric auth. 
 
Figma https://www.figma.com/file/zG04IdiVCb4ZNC5n3nH9yg/Authentication-for-Mobile?type=design&node-id=771-16206&mode=design&t=2bTm9zpVhhorYPcQ-0

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ibrkhalil** [comment]
Unassigning to focus more on quality.
