### ISSUE TITLE
Text color in disable state buttons [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19199]
# Design Feedback 2.27

## [Android] Disable state buttons have a wrong colored text
Different instances where the text color of a disabled button is wrong, making it hard to read:

- **Address for permissions screen:**

<img width="393" alt="Screenshot 2024-03-12 alle 14 32 35" src="https://github.com/status-im/status-mobile/assets/122543089/6e38d72a-9d23-42f6-bd0b-b07f7dc2380d">

>
- **Join community:**

<img width="393" alt="Screenshot 2024-03-12 alle 14 34 01" src="https://github.com/status-im/status-mobile/assets/122543089/f78cc13a-1d43-40aa-a9f6-8ccb1b4eef77">

>
- **View profile:**

<img width="393" alt="Screenshot 2024-03-12 alle 14 35 05" src="https://github.com/status-im/status-mobile/assets/122543089/82b7429a-4b0f-46c0-831b-7989b318a059">

### Expected behavior

<img width="375" alt="Screenshot 2024-03-12 alle 14 36 45" src="https://github.com/status-im/status-mobile/assets/122543089/38320c8d-83b1-45f5-9474-ea5768c47ec2">

### Reproduction

1. Find a disabled button anywhere in the app from an Android device

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
removed my assignment as @ibrkhalil has a linked pr

**Comment by ibrkhalil** [comment]
@Francesca-G PR here
https://github.com/status-im/status-mobile/pull/19461

**Comment by Francesca-G** [comment]
> @Francesca-G PR here #19461

Seems fixed for the most part, but now we have a similar issue in the onboarding flow:

<img width="400" alt="Screenshot 2024-04-04 alle 14 10 05" src="https://github.com/status-im/status-mobile/assets/122543089/d1f77f84-b8f7-401f-8c2a-9b20f8eb0405">
<img width="400" alt="Screenshot 2024-04-04 alle 14 10 22" src="https://github.com/status-im/status-mobile/assets/122543089/7e022196-bcf1-4ef1-ac7c-bcad834a9135">


>
**Expected behavior**

<img width="375" alt="Screenshot 2024-04-04 alle 14 11 22" src="https://github.com/status-im/status-mobile/assets/122543089/7cd7ed63-9a13-4409-8b99-92d85e79258e">

**Comment by ibrkhalil** [comment]
> > @Francesca-G PR here #19461
> 
> Seems fixed for the most part, but now we have a similar issue in the onboarding flow:
> 
> <img alt="Screenshot 2024-04-04 alle 14 10 05" width="400" src="https://private-user-images.githubusercontent.com/122543089/319576384-d1f77f84-b8f7-401f-8c2a-9b20f8eb0405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MTA1MjAsIm5iZiI6MTcxMjQxMDIyMCwicGF0aCI6Ii8xMjI1NDMwODkvMzE5NTc2Mzg0LWQxZjc3Zjg0LWI4ZjctNDAxZi04YzJhLTliMjBmOGViMDQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxMzMwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTBlMWRlODcwMDc0NTgxYWIzZTEwY2E5YTQyZmUzMjMwZTI2MjIyOTQyNjk5MTZmY2U2MTIxZGUzNjhkNDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0FWiKUE5lK3gqacUYT7le3YirXzTBR-mXaR-j3qFepI"> <img alt="Screenshot 2024-04-04 alle 14 10 22" width="400" src="https://private-user-images.githubusercontent.com/122543089/319576469-7e022196-bcf1-4ef1-ac7c-bcad834a9135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MTA1MjAsIm5iZiI6MTcxMjQxMDIyMCwicGF0aCI6Ii8xMjI1NDMwODkvMzE5NTc2NDY5LTdlMDIyMTk2LWJjZjEtNGVmMS1hYzdjLWJjYWQ4MzRhOTEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxMzMwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzM2OGVkMmUxMTEzYzhiMDFjNDg1N2FiYTVjOGZkNTIxMjAwMWZkYWQ3ODhjZDMzMGJlMTllZGMzNDVmNzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fGX8H8vy-I8QV2a7rqDN3WpNComW2FNECXcSYlYQVJY">
> > 
> 
> **Expected behavior**
> 
> <img alt="Screenshot 2024-04-04 alle 14 11 22" width="375" src="https://private-user-images.githubusercontent.com/122543089/319576767-7cd7ed63-9a13-4409-8b99-92d85e79258e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MTA1MjAsIm5iZiI6MTcxMjQxMDIyMCwicGF0aCI6Ii8xMjI1NDMwODkvMzE5NTc2NzY3LTdjZDdlZDYzLTlhMTMtNDQwOS04Yjk5LTkyZDg1ZTc5MjU4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxMzMwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmI1ZDA5M2M3Mjg3NTIzNWY4NTY5YjVmMGRjMDZlOWQ5MWQ0YjVhYmE3OTQzMTNiZmZlMDFhODZlMzg4YjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M6pSR6S4PdeK7NBwJcgQa55GlVDjUJgWu8LGX9ztRXs">

Fixed
![CleanShot 2024-04-06 at 16 04 08](https://github.com/status-im/status-mobile/assets/33176106/7dadb0e0-6f89-4178-b883-0bbef092be86)

**Comment by Francesca-G** [comment]
> Fixed ![CleanShot 2024-04-06 at 16 04 08](https://private-user-images.githubusercontent.com/33176106/320211152-7dadb0e0-6f89-4178-b883-0bbef092be86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjI5MjUsIm5iZiI6MTcxMjU2MjYyNSwicGF0aCI6Ii8zMzE3NjEwNi8zMjAyMTExNTItN2RhZGIwZTAtNmY4OS00MTc4LWI4ODMtMGJiZWYwOTJiZTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODRmMjlhOTA0NjA0MmNlYzhkOTJlOTZjZDViZGY2MzMzNmQ0OGYwZWU1MWEyMzhhMGU5MWJkOTIyZjAyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N72W6vOx6ncxWMXwg6gsAGhrSazCFZVPjYN5ZCmQgCE)

Thank you ✨🙏
