### ISSUE TITLE
Shadow issues [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19191]
# Design Feedback 2.27

## [Android] Shadows
Shadows on Android look very different from both design and iOS implementation. 
I remember reviewing and approving a PR that solved this issue but it looks like it wasn't implemented in the 2.27 build.

### Expected behavior
- Discover communities screen
- Invite friends card in Messages homepage

<img width="300" alt="Screenshot 2024-03-12 alle 11 07 33" src="https://github.com/status-im/status-mobile/assets/122543089/0a767d24-64e2-4e72-b968-edd5d7d55f4b">
<img width="300" alt="Screenshot 2024-03-12 alle 11 08 03" src="https://github.com/status-im/status-mobile/assets/122543089/4aefd321-2d01-40ca-8ed8-60573b43535e">

### Actual behavior

<img width="300" alt="Screenshot 2024-03-12 alle 11 09 06" src="https://github.com/status-im/status-mobile/assets/122543089/a066d4da-0520-4c97-90e1-febc3a56ab50">
<img width="300" alt="Screenshot 2024-03-12 alle 11 09 27" src="https://github.com/status-im/status-mobile/assets/122543089/7edecfbf-fa27-4dd8-a933-ef1981857622">

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
@Francesca-G might be related to your Android version.

Here how it looks like on my Android 12. Please check if shadows are correct on screenshots below. If they are correct  then I propose to close the issue as Android 8.1 is very old and I don't think we should resolve specific UI issues related to Android versions < 11. 

I remember that sometime ago Design team approved that we can ignore specific UI issues related to Android version < 11. We can re-open a discussion with Pedro to confirm it. 

![photo_2024-03-12 18 16 46](https://github.com/status-im/status-mobile/assets/97245802/e60f82b6-616f-4119-86d6-731da3b91a38)
![photo_2024-03-12 18 16 48](https://github.com/status-im/status-mobile/assets/97245802/83ccfa17-1f5d-40f9-b0b6-8e1c250d3ebe)

**Comment by Francesca-G** [comment]
> @Francesca-G might be related to your Android version.
> 
> Here how it looks like on my Android 12. Please check if shadows are correct on screenshots below. If they are correct then I propose to close the issue as Android 8.1 is very old and I don't think we should resolve specific UI issues related to Android versions < 11.
> 
I 100% agree with you, the weird thing Is that when I tested the correct shadows I used the same phone I'm using for this review (with the same Android 8.1) so that is a bit of a mystery 😅

Anyway, the shadows in the screenshot you provided look correct like I remembered them 👍

**Comment by pavloburykh** [comment]
> when I tested the correct shadows I used the same phone I'm using for this review (with the same Android 8.1) so that is a bit of a mystery

Might be related to updates of React Native version which happened after your testing. There might be different reasons why the problem appeared again in old Android version but for us it is essential that newer versions look okay. 

Thank you for you reply @Francesca-G! I am closing the issue.
