### ISSUE TITLE
Communities - Request to Join drawer issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19197]
# Design Feedback 2.27

## [Communities] Request to join drawer screen issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=4%3A111403&mode=design&t=IwKFMlZGTBic5nwK-1)

- **Upper margin** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=103:77903&mode=design#714520830)] between the top of the drawer and the close button
- **Account list preview** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#726026933)] size is smaller than design
- **Community rules** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=103:77903&mode=design#714528125)] list has a random spacing after the 2nd rule

<img width="500" alt="Screenshot 2024-03-12 alle 14 10 24" src="https://github.com/status-im/status-mobile/assets/122543089/e31e92ae-eef2-46d9-b0d5-c2fe229e0c24">

### Reproduction

1. Join a community

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
The rules part is caused by the person who wrote the rules copy on status-desktop.
He added _two_ line breaks in the part highlighted.

**Comment by Francesca-G** [comment]
> The rules part is caused by the person who wrote the rules copy on status-desktop. He added _two_ line breaks in the part highlighted.

I thought that was the issue too, but there aren't two line breaks when opening the Community rules drawer after joining:

<img width="300" alt="Screenshot 2024-03-18 alle 09 35 48" src="https://github.com/status-im/status-mobile/assets/122543089/dcf7719a-7e9a-4088-9158-f70a28c2edb3">

**Comment by ibrkhalil** [comment]
> > The rules part is caused by the person who wrote the rules copy on status-desktop. He added _two_ line breaks in the part highlighted.
> 
> I thought that was the issue too, but there aren't two line breaks when opening the Community rules drawer after joining:
> 
> <img alt="Screenshot 2024-03-18 alle 09 35 48" width="300" src="https://private-user-images.githubusercontent.com/122543089/313604215-dcf7719a-7e9a-4088-9158-f70a28c2edb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTQ1NzksIm5iZiI6MTcxMDc1NDI3OSwicGF0aCI6Ii8xMjI1NDMwODkvMzEzNjA0MjE1LWRjZjc3MTlhLTdlOWEtNDA4OC05MTU4LWY3MGEyOGMyZWRiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwOTMxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGEyNGMzZWYwODNiZWZjNDJlMmFjYmFiNjg2ZDhkZWZmZGVlNzhkMzcxNmQ3NTA3YzYyOWU4OGRiOWVkYWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TT5bFB7aJ0GAsdHdNF-P9U_Z_5rRBWxHU_PSWQnUgts">

Okay, Cool
Can you share the community URL with me please?

**Comment by Francesca-G** [comment]
> 
> Okay, Cool Can you share the community URL with me please?

➡️ [Here](https://status.app/cc/G68AAGRoXptfCUynNCK-EQrAGt4pBw5B0rKog-nFDnRPWSiqMeP1S-xPxxKlxWmlNpEkhMFjBq7x-tyuwOJyOr3Ou-cPibhU97yKIXViqenq8QTLCfTaR5IQ1MBlhmMQViDm1yMvIBEHgV-qhxKbL-Ys4gVrI_RCT7VcY6k6iyBUZzNrrs7ns8B3zcBy_BA=#zQ3shisKwF1dRjThmWeNK8NtXjaMCuR6BDM2qe6aiEb4naFDR)

**Comment by ibrkhalil** [comment]
@Francesca-G Unfortunately, Coudn't reproduce .. Maybe it was fixed?
![image](https://github.com/status-im/status-mobile/assets/33176106/b709fec3-bef2-4178-a8d4-3ac94665cd22)

**Comment by ibrkhalil** [comment]
Merging the PR as it was approved on the design review.
