### ISSUE TITLE
Authentication drawer keyboard bug when joining community [iOS]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19194]
# Design Feedback 2.27

## [iOS] Authentication drawer keyboard bug when joining community
When joining a community the keyboard should open automatically with the opening of the authentication drawer, as tracked here status-im/status-mobile/issues/19193 it doesn't behave correctly.
➡️ **Additional bug on iOS** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#726028476)] instead of the keyboard the channel list underneath the drawer is visible

#### Expected behavior

<img width="375" alt="Screenshot 2024-03-12 alle 11 42 53" src="https://github.com/status-im/status-mobile/assets/122543089/6512f70f-f262-4e7b-81da-2f858a652d1b">

#### Actual behavior

<img width="430" alt="Screenshot 2024-03-12 alle 11 43 37" src="https://github.com/status-im/status-mobile/assets/122543089/0f0795bf-e081-4956-bc77-7960f809472f">

### Reproduction

1. Open a community on an iOS device
2. Tap the Join button

### Additional Information

- Status version: nightly 
- Operating System: iOS
- Device: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@jo-mut what's the state of this?

**Comment by jo-mut** [comment]
channel list underneath the drawer is not reproducible. Might be an issue that affects only or iPhone 15 / iPhone 15 Pro Max. I have not done much apart from trying to reproduce the issue

**Comment by jo-mut** [comment]
I will unassign myself from this one, I have not been able to reproduce it on multiple devices

**Comment by yqrashawn** [comment]
Keyboard won't open for contact request message drawer as well

https://github.com/status-im/status-mobile/assets/15090582/39e3c29f-4e9b-4a1d-938b-233538f08176
