### ISSUE TITLE
Implement generic jump-to button using overlays

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#19192]
more info: https://github.com/status-im/status-mobile/pull/19134#discussion_r1517333107

Implement generic jump-to button using overlays, something like: https://github.com/status-im/status-mobile/pull/19011

Also, should use same fade in-out animation for jump-to button as used at home-stack. Confirm with design team

**Comment by Parveshdhull** [comment]
floating shell button `status-im.contexts.profile.settings.view` improve uses - https://github.com/status-im/status-mobile/pull/19134/files#r1529035948

**Comment by Parveshdhull** [comment]
navigate-back is needed for now, because it seems navigate-to-jump-to was implemented only considering shell screens (chat, home etc.)

**Comment by Parveshdhull** [comment]
we probably also should call :pop-to root, will fix it.

**Comment by J-Son89** [comment]
@Parveshdhull - adding this as blocked for the moment as Jump to is currently on hold afaik

**Comment by Parveshdhull** [comment]
Lets just close this issue. Screens already have jump-to embed-ed in them, and method of overlay already having some issues with alert banner.
