### ISSUE TITLE
Communities - Discover Communities screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19190]
# Design Feedback 2.27

## [Communities] Discover Communities screen
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=4%3A111403&mode=design&t=IwKFMlZGTBic5nwK-1) might be related to https://github.com/status-im/status-mobile/issues/17852

- **Featured Communities** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#716253260)] are missing, as well as the divider - 👀 This might be out of scope / not implemented yet
- **Missing shadow** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#716252603)] inside the community cards

<img width="500" alt="Screenshot 2024-03-12 alle 10 57 55" src="https://github.com/status-im/status-mobile/assets/122543089/c2fe5955-a73a-4de9-9eb8-d44eadf2eec1">

### Reproduction

1. Open the Communities homepage
2. Tap on the Discover card

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by BalogunofAfrica** [comment]
@cammellos Should this be removed from the [communities project](https://github.com/orgs/status-im/projects/116/views/1)

**Comment by cammellos** [comment]
thank you @BalogunofAfrica , removed!

**Comment by ilmotta** [comment]
Closing for the following reasons:

> Featured Communities [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#716253260)] are missing, as well as the divider - 👀 This might be out of scope / not implemented yet

Feature was descoped.

> Missing shadow [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#716252603)] inside the community cards

We won't implement this improvement in the foreseeable future.
