### ISSUE TITLE
No Bio data updated for User A if User's B Bio has changed

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19209]
# Bug Report

https://github.com/status-im/status-mobile/pull/19030#
## Problem 
[comment]: # (A problem description)
The only moment User A get "Bio" data of User B is when User B accepts contact request. If User B updates his Bio in the desktop app User A won't have an updated data.

#### Expected behavior
Bio data should be updated if it's updated on the Status Desktop

#### Actual behavior
No Bio data updated in User's B Profile

### Reproduction

***User A** - mobile
  **User B** - desktop

1. Login to mobile app as User A (new-contact-ui flag is OFF)
2. As User B make sure you have text in your Bio field
3. As user A send contact request to User B
4. Accept contact request as user B
5. As user A turn ON new-contact-ui flag
6. As User A go to Contacts - User B profile
7. As User B change test in your Bio field
8. As User A close re-open User B again

### Additional Information

- Status version: PR https://github.com/status-im/status-mobile/pull/19030#
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by seanstrom** [comment]
Hey @mariia-skrypnyk 👋 
I recently tested if bio updates are updating between two different accounts on mobile devices while testing #19237, and it seems that updates are working. However, it does not seem to be working when updating a bio from status desktop. So this issue could be related to a bug in Status desktop. There might an issue with how the desktop client is sending contact updates after modifying the user bio, but I'm not sure.

**Comment by seanstrom** [comment]
For context, here's a video showing two mobile accounts with profile bios and one of them updating their profile bio.

https://github.com/status-im/status-mobile/assets/2845768/7eb88f95-7254-4fec-b90c-5a61eb01be73

**Comment by cammellos** [comment]
Closing as it seems it might be desktop related, also seems like low-priority, maybe @anastasiyaig if you'd like to triage (up to you of course)
