### ISSUE TITLE
Add blur to sticky header

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#19201]
Add blur to the sticky header section once it sticks towards the top.

**Expectation:**
Sticky header should have blur and blend with the rest of the header as seen in the design here: https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=47-60636&mode=design&t=5vXB0qfMiyj8tSBN-0

![Image](https://github.com/status-im/status-mobile/assets/45393944/9f2fa171-c0bd-46d4-824d-8e66af4bab4c)

**Result:**
Sticky header doesn't have header when it sticks

![Image](https://github.com/status-im/status-mobile/assets/45393944/810208b1-31c7-41dc-846c-7c3f88bf49e6)

**Comment by BalogunofAfrica** [comment]
One detail also worth noting is that the border top width would get removed when the header sticks and turns blurred

**Comment by BalogunofAfrica** [comment]
On checking ways to achieve this, I narrowed the option down to implementing our own custom sticky component via the `StickyHeaderComponent` prop.

The component would handle the logic of keeping the item docked to the top (or bottom) and also showing the blur.

For context, this is the default `StickyHeaderComponent` used when we don't pass that prop as seen in `React Native` code base https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js.

**Comment by churik** [comment]
@cammellos do we need to worry about blur now? I believe it can be descoped

**Comment by cammellos** [comment]
that's correct, can be descoped
