### ISSUE TITLE
User is allowed to to add more than 19 members to group chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19206]
# Bug Report

## Problem 

The maximum number of group members should be limited to 20, including the group creator.

#### Expected behavior

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720-548968&mode=design&t=MiwpT60QOS46oBU1-4

<img width="397" alt="Screenshot 2024-03-12 at 15 24 14" src="https://github.com/status-im/status-mobile/assets/67952253/fe361df7-25c7-4c9d-8660-c7e4664056ad">

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/c674a041-cf9b-4615-9173-87468d4aed5b

### Reproduction

1. Add 19+ contacts
2. Create a group chat with all of them

### Additional Information

- Status version: nightly 12/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
should be fixed in https://github.com/status-im/status-mobile/pull/19066

**Comment by BalogunofAfrica** [comment]
Related https://github.com/status-im/status-mobile/issues/18980
