### ISSUE TITLE
Communities - Spacing issue in rules drawer 

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19200]
# Design Feedback 2.27

## [Communities] Spacing in the community rules drawer
**Spacing between title and community tag** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#727726948)] doesn't match design

#### Expected behavior
<img width="375" alt="Screenshot 2024-03-12 alle 14 43 13" src="https://github.com/status-im/status-mobile/assets/122543089/b955db31-51cf-4ab8-b45b-76b54e9987db">

#### Actual behavior
<img width="430" alt="Screenshot 2024-03-12 alle 14 44 39" src="https://github.com/status-im/status-mobile/assets/122543089/116757fc-0b11-48f6-b26b-124e9f30c11c">

### Reproduction

1. Open a Community you're a member of
2. Tap the options button at the top right corner of the screen
3. Tap on _View community rules_

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
closing this one as it fixed in #19044
