### ISSUE TITLE
Handle only selected Universal Links for status.app

### ISSUE THREAD

**Issue by felicio** [status-im/status-react#19216]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior

- Handle only selected Universal Links for status.app pages (i.e. `/u`, /c`, `/cc`)

#### Actual behavior

- App opens https://status.app

### Reproduction

1. On mobile, click on https://status.app

If not reproducible, try

1. Pasting https://status.app to Notes.app
2. Long press the link > Open in "Status"
3. Go back to Notes.app
4. Click on the link again

### Additional Information

- Status version: 2.27.0 (20240229153900) 
- Operating System: iOS 17.3.1 (21D61)

[comment]: # (Please, add logs/notes if necessary)

**Comment by felicio** [comment]
Cc @yqrashawn

**Comment by felicio** [comment]
note: maybe adding `"paths": [ "/test/*", NOT "/path/1/*"]` as per https://developer.apple.com/documentation/technotes/tn3155-debugging-universal-links would be enough

**Comment by yqrashawn** [comment]
```json
{
  "applinks": {
    "details": [
      {
        "appIDs": [
          "DTX7Z4U3YA.im.status.ethereum",
          "DTX7Z4U3YA.im.status.ethereum.test",
          "46H86FR76G.im.status.ethereum.test",
          "7JLRC79H5J.im.Status.NimStatusClient",
          "8B5X2M6H2Y.im.status.ethereum",
          "8B5X2M6H2Y.im.Status.NimStatusClient",
          "8B5X2M6H2Y.im.status.ethereum.pr",
          "8B5X2M6H2Y.im.status.ethereum.debug"
        ],
        "components": [
          {
            "/": "/c/*",
            "comment": "Community overview",
          },
          {
            "/": "/cc/*",
            "comment": "Community channel"
          },
          {
            "/": "/u/*",
            "comment": "User"
          },
          {
            "/": "/p/*",
            "comment": "Private chat"
          },
          {
            "/": "/b/*",
            "comment": "Browser"
          },
          {
            "/": "/cr/*",
            "comment": "Community request"
          },
          {
            "/": "/g/*",
            "comment": "Group chat"
          },
          {
            "/": "/wallet/*",
            "comment": "Wallet"
          }
        ]
      }
    ]
  }
}
```

**Comment by yqrashawn** [comment]
Hi @felicio, can you update the `public/.well-known/apple-app-site-association` file to the above comment?

It should work according to apple's `swcutil`, although it won't work when I tested it on mobile PR build with a MITM proxy

![CleanShot 2024-03-22 at 21 07 18@2x](https://github.com/status-im/status-mobile/assets/15090582/a886181f-132d-4c5e-a94b-61a4e87ba161)

**Comment by felicio** [comment]
Awaits https://github.com/status-im/status-website/pull/914.

@yqrashawn I'm only adding the currently known and supported paths, but if you'll tell me that the rest is actually supported too, I'll add them too.

**Comment by felicio** [comment]
Also, @jkbktl caught this https://github.com/status-im/status-website/pull/914#discussion_r1537367062.

**Comment by yqrashawn** [comment]
> Awaits https://github.com/status-im/status-website/pull/914.
> 
> 
> 
> @yqrashawn I'm only adding the currently known and supported paths, but if you'll tell me that the rest is actually supported too, I'll add them too.

Those links are currently supported by the mobile app. Mobile e2e test might broken if they are removed.

**Comment by yqrashawn** [comment]
I've updated the comment, `exclude` has been removed

**Comment by felicio** [comment]
Deployed.

**Comment by yqrashawn** [comment]
tested with PR build, https://status.app still trigger app open

**Comment by felicio** [comment]
Wanna try with the paths (ref https://github.com/status-im/status-mobile/issues/19216#issuecomment-2011083017) instead?

**Comment by felicio** [comment]
Feel free to open a PR for https://github.com/status-im/status-website/blob/main/public/.well-known/apple-app-site-association anytime, I'll try to approve it whenever I can.

**Comment by yqrashawn** [comment]
> Wanna try with the paths (ref [#19216 (comment)](https://github.com/status-im/status-mobile/issues/19216#issuecomment-2011083017)) instead?

@felicio I've created a PR https://github.com/status-im/status-website/pull/920

**Comment by yqrashawn** [comment]
https://github.com/status-im/status-mobile/assets/15090582/6140964d-18ac-4c7e-8d12-9661f05245a2


it works 🎉
