### ISSUE TITLE
No Bio data in User's B Profile if User A made a logout

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19211]
# Bug Report
https://github.com/status-im/status-mobile/pull/19030#

## Problem 
[comment]: # (A problem description)
If user A has User B in a contacts and sees User's B bio then do a logout - no Bio data in User's B Profile

#### Expected behavior
Data should't disappear after relogin

#### Actual behavior
No Bio data in User's B Profile

https://github.com/status-im/status-mobile/assets/147824399/6563d478-75a1-4b01-993d-ec6414fdc05e

### Reproduction

**Steps:**

1. Login to mobile app as User A (new-contact-ui flag is OFF)
2. As User B make sure you have text in your Bio field
3. As user A send contact request to User B
4. Accept contact request as user B
5. As user A turn ON new-contact-ui flag
6. As User A go to Contacts - User B profile (sees Bio data)
7. Logout as User A
8. As User A go to Contacts - User B profile

### Additional Information

- Status version: (https://github.com/status-im/status-mobile/pull/19030#)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
There's no bio in contacts table

https://github.com/status-im/status-go/blob/22615010e6b4909cc4750db390c34ed55fb47f90/protocol/persistence.go#L961-L983

**Comment by seanstrom** [comment]
I'm closing this issue since the status-go PR https://github.com/status-im/status-go/pull/4916 has been merged. And the status-mobile PR https://github.com/status-im/status-mobile/pull/19237 has been closed. Note, that the status-go version will be bumped in the next release branch.
