### ISSUE TITLE
Communities - Empty channel screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19220]
# Design Feedback 2.27

## [Communities] Empty channel screen issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=4%3A111403&mode=design&t=tEdiDXvMnX8RBq7a-1)

- **Missing shadow** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=115:104785&mode=design#727526425)] of the content card
- **Avatar has the wrong style** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=115:104785&mode=design#726030784)] preventing it from being visible in the chat
- **Alignment of the contact icon** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=115:104785&mode=design#727532127)] next to the user name in the chat is wrong

<img width="500" alt="Screenshot 2024-03-13 alle 11 10 51" src="https://github.com/status-im/status-mobile/assets/122543089/b5251018-9cce-42a1-a3ab-2b93dd715496">

### Reproduction

1. Open a channel in a community you're a member of
2. See messages sent from a contact (for contact icon alignment issue)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by codemaster115** [comment]
I will close this issue as it's already done. Confirmed with @Francesca-G
