### ISSUE TITLE
Dark overlay changes button blur appearance [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19228]
# Design Feedback 2.27

## [Android] Dark overlay changes button blur appearance
**Dark overlay** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=120:73939&mode=design#728952708)] changes the blur appearance of the buttons underneath the overlay. The buttons have the correct appearance without the dark overlay, this only occurs when the overlay is present.

This happened when opening a drawer (_Leave community_ drawer in this case) in a Community page:

<img width="393" alt="Screenshot 2024-03-13 alle 13 39 49" src="https://github.com/status-im/status-mobile/assets/122543089/f73fd7d9-8ab7-4cb5-84af-b21c37a76a06">

#### Expected behavior

<img width="373" alt="Screenshot 2024-03-13 alle 13 43 23" src="https://github.com/status-im/status-mobile/assets/122543089/a96ac703-ced6-4f70-8ae5-6824ddf46e33">

### Reproduction

1. Open a Community you're a member of
2. Tap on the options button at the top right of the screen
3. Tap on _Leave community_

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
I believe as blur is removed for Android, can be closed.  Reopen if still relevant.
