### ISSUE TITLE
Wallet: user is navigated to the wrong screen when sending a token from the drawer and selecting one of their accounts

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19225]
# Bug Report

## Problem 

If you long-press a token to send it from the drawer, after selecting **one of your accounts** as a receiver, you'll be redirected to the `Select asset` screen, which doesn't look right, since you're already sending a particular asset. 

### Reproduction

1. Open Wallet
2. Open an account
3. Long-press on a token
4. Press `Send`
5. Open the `My accounts` tab, select one of your accounts

#### Expected behavior

The screen with the token amount input field is opened

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7701-157251&mode=design&t=i4lglrtuSUyZWRSc-4

<img width="610" alt="Screenshot 2024-03-13 at 11 46 12" src="https://github.com/status-im/status-mobile/assets/67952253/b09f9af5-9c7e-4fc9-8cb8-3a06c1e8574d">

#### Actual behavior

The `Select asset` screen is opened

https://github.com/status-im/status-mobile/assets/67952253/7d72eabc-664d-4571-8442-896a992e69c1

### Additional Information

- Status version: nightly 13/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@qoqobolo - thanks for raising this. 
@ulisesmac, this is related to the discussion we were having earlier.
Can you either make use of this issue or close this issue when you create the other one? (@qoqobolo the solution for this is somewhat generic as we will leverage the code @mmilad75 is adding here: https://github.com/status-im/status-mobile/pull/19123

**Comment by ulisesmac** [comment]
Thanks @J-Son89 nad @qoqobolo 

I'm taking this issue and I'll solve it when @mmilad75's PR gets merged,

**Comment by J-Son89** [comment]
In fact @mmilad75's pr might even solve this already 👍

**Comment by J-Son89** [comment]
I'm pretty sure Milad's pr resolves this 👍

**Comment by ulisesmac** [comment]
Thanks, I'm assigning this to @mmilad75 then
