### ISSUE TITLE
No ability to create additional ETH account after removal

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19232]
### Steps:
1. Go to the wallet and create an additional ETH account (e.g., "test account 2"). (The current account is created with Derivation path `m/44/60/0/0/1` for this account).
2. Create one more ETH account (e.g., "test account 3").
3. Remove "test account 2".
4. Go to the account creation flow.
5. Check the Derivation path on the color picker screen during ETH account creation (The current account is created with Derivation path `m/44/60/0/0/2` instead of `m/44/60/0/0/1`).
6. Try to finish the account creation.

### Actual Result:
- The Derivation path for the new account is incorrect.
- The account is not created after confirming the slide to create account button.

https://github.com/status-im/status-mobile/assets/52490791/e523a4fc-f59c-4c9e-a716-2787adbdff00

### Expected Result:
- The Derivation path for the newly created account should be the same as it was when the account was removed.
- The account should be created successfully.

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14589082/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
@ulisesmac - is this issue still relevant?

**Comment by VolodLytvynenko** [comment]
> @ulisesmac - is this issue still relevant?

@J-Son89 the issue still exists

**Comment by ulisesmac** [comment]
@VolodLytvynenko @J-Son89 

Yeah, this is still reproducible, I've opened a PR for it:
- #19531
