### ISSUE TITLE
[IOS] "Null is not an object (evaluating 'n.toLowerCase')" error is shown after attempt to log out

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19239]
Unfortunately, there are no exact steps to reproduce this issue. It occurs randomly and very rarely. I hope the logs might help understand what's going on.

### Steps:
1. Tap log out

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/3ef66d2d-eac1-4110-95e0-18542150346a

### Expected result:
No error after log out

### Device:
- iPhone 11 Pro max, IOS 17

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14592311/logs.zip)

### ENV:
Nightly [13 Mar 2024]

**Comment by Parveshdhull** [comment]
Hi @VolodLytvynenko, Thank you for finding this issue. Please can you tell when this started to happen, is this bug recent?

**Comment by Parveshdhull** [comment]
probable cause

```
(defn save-credentials
  "Stores the credentials for the address to the Keychain"
  ([server username password]
   (save-credentials server username password identity))
  ([server username password callback]
   (-> (.setInternetCredentials ^js react-native-keychain
                                (string/lower-case server)
```

**Comment by Parveshdhull** [comment]
`:keychain/clear-user-password` can also be the cause, they all are lowering case to server. But unfortunately I am not able to reproduce this issue. Maybe just add nil check

**Comment by Parveshdhull** [comment]
`key-uid may be nil after restore from local pairing`
