### ISSUE TITLE
"Cannot set property 'reagent-compiler2' of null" Error when blocking a contact

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19240]
### Steps:
1. UserA adds UserB to contacts
2. UserA or UserB tap 'block' button

### Actual result:
"Cannot set property 'reagent-compiler2' of null" error is shown 

https://github.com/status-im/status-mobile/assets/52490791/39ac5bd4-5d30-437a-8850-c29e13cba2b1

### Expected result:
The blocking drawer should be shown with the ability to block a contact.
![image](https://github.com/status-im/status-mobile/assets/52490791/0fd7afde-c3fa-4e75-8829-13cc3d1cdf4c)

### ENV:
IOS, Android

### Logs:
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/14593441/Status-debug-logs.2.zip)

**Comment by VolodLytvynenko** [comment]
Hey @mohsen-ghafouri, it seems this issue was introduced after merging [this](https://github.com/status-im/status-mobile/pull/19213) PR. Could you take a look?

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko I reviewed again my PR and there is no changes related to the legacy logics. how can we check if the issue wasn't there? can we compare with previous build?

**Comment by mohsen-ghafouri** [comment]
I reverted this changes locally and the issue gone, it happens after that. #19068
