### ISSUE TITLE
🎨 Gradient backgrounds for modals

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#19258]
# Feature Issue

Currently, there is no uniform support for gradient backgrounds on modals. This issue was surfaced while developing UI for `Save Address` feature #19079. 

This proposed feature allows for setting gradient-backgrounds on modals in the screen config:
```clj
    {:name      :screen/wallet.save-address
     :options   {:gradient-background? true :customization-color :blue}
     :component wallet-save-address/view}
```

It will also allow for changing the color on the fly:
```clj
(rf/dispatch [:modal :update-customization-color
                     {:screen :screen/wallet.save-address :customization-color :red}]
```

It happens by adding a gradient-background section in the `bottom-sheet-screen` component
```clj
          [reanimated/view {:style (style/main-view translate-y theme)}
          
           (when (or gradient-cover? true)
             [quo/gradient-cover {:customization-color customization-color}])
             
           [rn/view {:style style/handle-container}
            [rn/view {:style (style/handle theme)}]]
 ```
 
We can also put it at the level of `navigation.view/screen`. This way, gradient background will be available for every screen. 

And then build an event handler to change the screen color of any screen id on the fly. 

This can also be extended to gradient-color option for full page navigation too (not just modals). This will streamline the process of adding the gradient-background to most views.

**Comment by flexsurfer** [comment]
i don't think this is needed, it works fine with current components

**Comment by shivekkhurana** [comment]
The problem was that I wrapped `floating-button-page` in an `rn/view`. Floating button page should be the topmost component.
