### ISSUE TITLE
Messages - Add a contact screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19263]
# Design Feedback 2.27

## [Messages] Add a contact screen issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=7%3A111976&mode=design&t=hS39AbDcBnA1KjAm-1)

- **Placeholder in input field** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=118:72067&mode=design#712621783)] isn't centered
- **Button copy** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=118:72067&mode=design#727629930)] isn't centered inside the button

<img width="500" alt="Screenshot 2024-03-15 alle 10 18 44" src="https://github.com/status-im/status-mobile/assets/122543089/dfcd7b90-c60e-4607-8e5a-3ce7c000eae7">

>
- **Update copy** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35485&mode=design#725934600)] of the input field label [Chat key ➡️ Chatkey]
- **~Chatkey~ moved to issue 19267** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35485&mode=design#725934138)] has a weird break line (also logged here: https://github.com/status-im/status-mobile/issues/19267)

<img width="500" alt="Screenshot 2024-03-15 alle 10 22 25" src="https://github.com/status-im/status-mobile/assets/122543089/8b604f3c-bc75-4697-b9fd-1bb21d5d0c43">

### Reproduction

1. Open the messages home
2. Tap the ➕ button at the top right corner
3. Tap on _Add a new contact_

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
chatkey copy, placeholder and button center issue and Chat Key copy issue will be fixed in #19565

**Comment by yqrashawn** [comment]
let's move chatkey break line issue out of this one to #19267 since it's bit complicated
will close this issue if all other sub issues are fixed
