### ISSUE TITLE
Messages - Messages home issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19260]
# Design Feedback 2.27

## [Messages] Messages home page issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=7%3A111976&mode=design&t=hS39AbDcBnA1KjAm-1)

- **Status bar isn't visible** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#711383498)] tracked here: https://github.com/status-im/status-mobile/issues/15260
- **Illustration in the _Invite friends_ card** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#716254834)] needs to be updated

<img width="500" alt="Screenshot 2024-03-15 alle 09 45 38" src="https://github.com/status-im/status-mobile/assets/122543089/da0e2d85-8edd-4c7f-87fa-b406b8db3282">

>
- **Date and icon alignment** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#716257387)] next to the contact name in the _Recent_ tab is wrong
- **Vertical spacing** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#728610632)] between contacts in the _Contacts_ list tab doesn't match design

<img width="500" alt="Screenshot 2024-03-15 alle 09 46 12" src="https://github.com/status-im/status-mobile/assets/122543089/4a59c474-5d14-4ad4-89cd-17bfd2612224">

### Reproduction

1. Open the Status app
2. Go to the Messages home page

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max, iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
The vertical spacing between contacts in the Contacts list looks okay, there is a difference of 1px and that is the best it gets. Looking at the design feedback, the screens compares the vertical spacing of two contacts with different naming specifications. The first screen with `Ampersand.eth` also does not have the profile key right below the name like in the second case hence the difference in spacing.

This part seems to be well implemented as is

<img src="https://github.com/status-im/status-mobile/assets/28704507/836516ba-d7a4-46a5-8094-9415a18ea959" width="375">

**Comment by Francesca-G** [comment]
> The vertical spacing between contacts in the Contacts list looks okay, there is a difference of 1px and that is the best it gets.

Yes I was referring to that px, I'm aware it's a minor detail so feel free to ignore the _Vertical spacing_ issue 👍

**Comment by cammellos** [comment]
@jo-mut could you please update the illustration? the rest are probably not needed for 2.29
