### ISSUE TITLE
☁️ Floating action button get's cut off by keyboard on iOS

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#19272]
# Bug Report
This issue is to track various bugs popping up on the floating action button page. 

## Problem
The button get's cut off by the keyboard

<details><summary>📸 Screenshot</summary>
<p>

![](https://cdn.discordapp.com/attachments/775301545649766441/1218143176037109780/simulator_screenshot_1FB84D8A-7071-49DC-91AB-52CED2315A3C.png?ex=6606973d&is=65f4223d&hm=001818f5c1bb2681c21b1b231923ae2c4aa1bb43f4117daae7259810397b351a&)
</p>
</details>

### Reproduction
```clj
(rf/dispatch [:open-modal :screen/wallet.save-address])
```
Focus on input and open keyboard (Cmd K on simulator). You'll notice that the button is cut off by the keyboard.

### Additional Information

- Status version: nightly 
- Operating System: iOS (not tested on Android)

**Comment by ilmotta** [comment]
@shivekkhurana, could you update this issue or close it if it's not relevant? The screenshot URL is dead, so I don't know what this issue is all about to help.

**Comment by shivekkhurana** [comment]
Closed as it was probably fixed.
