### ISSUE TITLE
Onboarding sreen overlapping if Satatus app is reopened from a background

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19276]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
Screens changing one by one and do not overlapping

#### Actual behavior
Onboarding sreen overlapping if Satatus app is reopened from a background

https://github.com/status-im/status-mobile/assets/147824399/0023d391-716a-4b02-b35c-3345ab03382a

### Reproduction

1. Install Status app
2. Start creating new user 
3. Minimize app 
4. Open any other app on your device
5. Reopen Status from the background
6. Go next on onboarding

### Additional Information

- Status version: nightly (15/05)
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
regression from: https://github.com/status-im/status-mobile/pull/19163/files#r1526359038

will be fixed in https://github.com/status-im/status-mobile/pull/19274
