### ISSUE TITLE
Can't login with biometric ID

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19277]
# Bug Report

## Problem 

<img width="313" alt="Screenshot 2024-03-15 at 13 06 01" src="https://github.com/status-im/status-mobile/assets/67952253/3bd9f29d-086e-4860-ae37-75d842a92d63">

### Reproduction

1. Create a user, enable biometric ID on onboarding
2. Close the app
3. Open the app, try to log in

### Additional Information

- Status version: nightly 15/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
![image](https://github.com/status-im/status-mobile/assets/17097240/e6c083fe-c81d-4a91-8b6d-5a2cd079a27d)

**Comment by Parveshdhull** [comment]
regression from https://github.com/status-im/status-mobile/pull/19005
