### ISSUE TITLE
Posts & Attachments - Reaction drawer screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19280]
# Design Feedback 2.27

## [Posts & Attachments] Reaction drawer screen issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=8%3A140759&mode=design&t=PQCRedZgtXOKGara-1)

- **No pressed state** [[comment ](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717915349)] of the reaction button
- **Reaction isn't visible** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717915153)] in the message preview, even if the message has correctly displayed reactions in the chat
- **Bottom margin** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717915153)] is too narrow

<img width="500" alt="Screenshot 2024-03-15 alle 14 03 45" src="https://github.com/status-im/status-mobile/assets/122543089/da7c8841-123b-4d04-83a0-22e24fdb5594">

### Reproduction

1. Open a chat
2. React to a message
3. Press on the _React_ button to open the reaction drawer

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by codemaster115** [comment]
@Francesca-G The first item is already fixed and you can see the pressed state on reactions.

**Comment by Francesca-G** [comment]
> @Francesca-G The first item is already fixed and you can see the pressed state on reactions.

Looks fixed 👍
