### ISSUE TITLE
Request to join community stays Pending for non manual approval required community despite control node is online

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19291]
# Bug Report

## Problem 
[comment]: # (A problem description)
User tries to join non manual approval required community but status is still Pending and not Joined
It's not a one User problem. Issue was catched by me and by Diana as well (logs are below)

#### Expected behavior
User should be able to join community without admin approve if the community is open

#### Actual behavior
Request to join community stays Pending for open communities
Masha's logs of User A
[Request-joined-logs-1.txt](https://github.com/status-im/status-mobile/files/14636241/Request-joined-logs-1.txt)

Diana's logs of User A
[Request-join-logs-2.zip](https://github.com/status-im/status-mobile/files/14636188/Request-join-logs-2.zip)
 

### Reproduction

1. Login to Status App as user A
2. As User B add User A to your non manual approval required community
3. As User A go to chat with User B and tap on link to invited community
4. As User A send a request to join community

### Additional Information

- Status version: nightly 15/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
I think the community owner needs to be online for the request to be auto-accepted
related code at https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/communities/manager.go#L2748

cc @cammellos

**Comment by pavloburykh** [comment]
> I think the community owner needs to be online for the request to be auto-accepted related code at https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/communities/manager.go#L2748

@yqrashawn we know about this requirement. According to @mariia-skrypnyk control node was online

**Comment by cammellos** [comment]
@mariia-skrypnyk could you try to replicate using the latest desktop? if it's still a bug this likely will need fixing in 2.29

**Comment by mariia-skrypnyk** [comment]
Thanks @cammellos!
Do not see this issue now and will close this PR.
