### ISSUE TITLE
Toast appearance issue [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19304]
# Design Feedback 2.27

## [Android] Toast appearance issue
**Toast** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=56:35843&mode=design#719379373)] looks like it's glowing, not sure if it's a color, blur or even shadow issue. This happened on the Edit profile page

<img width="393" alt="Screenshot 2024-03-18 alle 10 34 26" src="https://github.com/status-im/status-mobile/assets/122543089/e06a4e86-ff2e-4ce1-9f98-e632fd07292b">

#### Expected behavior
<img width="375" alt="Screenshot 2024-03-18 alle 10 41 07" src="https://github.com/status-im/status-mobile/assets/122543089/11f392aa-6f67-4659-8510-9497a40f0c4d">

### Reproduction

1. Open profile settings by tapping the user avatar at the top left corner of the screen
2. Change a setting like profile picture, bio or customization color
3. Save changes, toast appears

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
I believe this issue no longer exists in `develop`. Please reopen otherwise.
