### ISSUE TITLE
Profile - Edit profile screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19303]
# Design Feedback 2.27

## [Profile] Edit profile screen issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=36%3A115879&mode=design&t=O3UNQJbRpr0lqKTe-1)

- **Wrong error message** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=47:31015&mode=design#716141545)] when using an apostrophe in the profile bio
- **Allowed symbols in bio** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=47:31015&mode=design#716141545)] should include apostrophes, commas, dots and dashes

<img width="500" alt="Screenshot 2024-03-18 alle 10 25 29" src="https://github.com/status-im/status-mobile/assets/122543089/2d18a846-ffe0-4718-b7e1-5a15b6bd5acf">

>
- **Photo button** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#727735372)] shouldn't be a circle
- **Toast copy** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=56:35209&mode=design#719297061)] if the profile picture was changed (not added for the first time) the toast should say _"Profile picture updated"_ not "added". This also applies to bio, custom color, etc.

<img width="500" alt="Screenshot 2024-03-18 alle 10 25 56" src="https://github.com/status-im/status-mobile/assets/122543089/92f8cbfd-3c90-44ff-8d64-079418c5593e">

### Reproduction

1. Open profile settings by tapping on the avatar picture at the top left corner of the screen
2. Tap on _Bio_ to edit a pre existent bio
3. Save changes

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by mohsen-ghafouri** [comment]
about bio validations, we agreed about accepting ASCII + Emoji and show errors for UFT-8 characters. here is desktop design with latest changes, the same logic for mobile as well 
https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=4621-461562&mode=design&t=nGT7ParxL7vVk7qh-4
