### ISSUE TITLE
Create wallet account slider issues [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19309]
# Design Feedback 2.27

## [Android] Create wallet account slider issues
**Slider** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=103:86532&mode=design#719385411)] has no background behind it and it should be disabled when there's no account name yet

<img width="393" alt="Screenshot 2024-03-18 alle 11 51 24" src="https://github.com/status-im/status-mobile/assets/122543089/a2a714bc-d6f3-49c2-ab26-e6dc6a7716d1">

#### Expected behavior

<img width="375" alt="Screenshot 2024-03-18 alle 11 51 41" src="https://github.com/status-im/status-mobile/assets/122543089/383619d6-0737-464e-bdc1-d774a7e76474">

### Reproduction

1. Open wallet
2. Tap on the empty card
3. Select _Add account_

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@ulisesmac - you have addressed this recently?

**Comment by ulisesmac** [comment]
@J-Son89 

Yes, it's being fixed in:
https://github.com/status-im/status-mobile/pull/19186
