### ISSUE TITLE
No ability to send assets from additional accounts

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19310]
### Steps:
1. Recover user  with additional accounts where assets are available 
2. Attempt to send assets using an additional account

### Actual result:
The assets are not sent. The app does not respond after attempting to confirm transaction in the authentication drawer.

https://github.com/status-im/status-mobile/assets/52490791/f689aad8-e0e1-4d57-99b4-1917d4dbc1c3

### Expected result:
The assets are sent

### ENV:
Nightly 18 Mar 2024

### NOTE:
Unfortunately, I didn't find the exact steps to reproduce this issue. It seems the issue occurs only for my user. Please refer to me directly, I can share the seed phrase of the user where this issue is reproducible.

### Logs
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14635306/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
@briansztamfater still relevant?

**Comment by VolodLytvynenko** [comment]
Hi @briansztamfater I am not able to reproduce this issue anymore with fresh users.  But still reproducible for the old one. Probably this issue is already gone and old one user specific. WDYT?

**Comment by briansztamfater** [comment]
@VolodLytvynenko actually this issue should only be reproducible with recovered accounts. So, should still be relevant. But, the solution should be related to account recovery which is a bigger issue that should be implemented.

Probably @smohamedjavid can add more context.

**Comment by briansztamfater** [comment]
Marked as blocked until syncing keypairs functionality is implemented, that would be the solution to fix non-operable accounts cc @smohamedjavid @VolodLytvynenko @J-Son89

**Comment by churik** [comment]
@VolodLytvynenko is this issue still relevant?

**Comment by VolodLytvynenko** [comment]
@churik can be closed. We have issue with more detailed steps https://github.com/status-im/status-mobile/issues/20394
