### ISSUE TITLE
Navigating back to chat without displaying top bar

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19327]
### Steps:
1. `UserA` Opens the chat with `UserB` 
2. Tap three dots in the right corner -> tap View profile
3. Remove or block the user
4. Tap [x] to close the profile page

### Actual result:
User is navigated to the chat where the top bar is not displayed

https://github.com/status-im/status-mobile/assets/52490791/f731dd04-6b4e-477c-bb93-360b8215175b

### Expected result:
The user is navigated to the chat, and the top bar is displayed

**Comment by Parveshdhull** [comment]
related to https://github.com/status-im/status-mobile/issues/19334, should be handled together

**Comment by Parveshdhull** [comment]
Hi @VolodLytvynenko, Please can you confirm whats expected behavior when contact is removed. Should we also remove chat from home screen as same as https://github.com/status-im/status-mobile/issues/19334

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko, Please can you confirm whats expected behavior when contact is removed. Should we also remove chat from home screen as same as #19334

Hi @Parveshdhull thank you for asking.  Chat should not be removed when the 'remove contact' button is used. Chat should be removed only when contact is blocked
