### ISSUE TITLE
're-find match against the string' error is shown after Show QR code option is selected when user is blocked

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19325]
Follow up for https://github.com/status-im/status-mobile/pull/19246
Reference to https://github.com/status-im/status-mobile/pull/19246#issuecomment-2003655694
![image](https://github.com/status-im/status-mobile/assets/52490791/bbe3824e-3d92-4fda-8151-750930de0a08)

### Steps:
1. `UserA` blocks `UserB` 
2. Open right up three dots to open the drawer
3. Select 'Show QR code' option

### Actual result:
're-find match against the string' error is shown after Show QR code option is selected
![image](https://github.com/status-im/status-mobile/assets/52490791/77654b5d-65af-4ee6-89b6-d366bff6bb54)

### Expected result:
no error when 'Show QR code' option is selected

### Logs:
[logs (4).zip](https://github.com/status-im/status-mobile/files/14625213/logs.4.zip)

**Comment by seanstrom** [comment]
Is this still an issue? I don't think I am able to access the Show QR screen anymore when a user is blocked.
cc @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> Is this still an issue? I don't think I am able to access the Show QR screen anymore when a user is blocked. cc @VolodLytvynenko

Hi @seanstrom , correct. @mohsen-ghafouri temporarily removed the 'Show QR' screen for blocked users. However, this issue is also reproducible if a user is removed. So, the steps are:

1. `UserA` removes `UserB`
2. Open right up three dots to open the drawer
3. Select 'Show QR code' option
4. `UserA` adds `UserB` to contacts again (send CR and accept CR)

After at least 10 times of repeating those steps, the issue occurs
