### ISSUE TITLE
QR code scanner doesn't work when you try Sign in by syncing

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19330]
# Bug Report

## Problem 
[comment]: # (A problem description)
If you tap quickly "While using the app" on permission popup before sync then QR code scanner will be broken

#### Expected behavior
QR code scanner works fine

#### Actual behavior
QR code scanner is broken

### Reproduction

1. Download app
2. Choose Sign in
3. Tap "While using the app" permission very quick on Sign in by syncing screen

https://github.com/status-im/status-mobile/assets/147824399/73cf0482-d8f0-4e4b-8685-35ee5468d19b

### Additional Information

- Status version: nightly (19/03)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@mariia-skrypnyk if the user goes back and restart the process, does it work then? if so we can probably descope for 2.29?

**Comment by mariia-skrypnyk** [comment]
Hi @cammellos !

Sorry for such a delay with my answer.
I've rechecked current issue on the latest build and it doesn't exist anymore.

I will close this PR.
