### ISSUE TITLE
1-1 Chat not removed after user is blocked

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19334]
Follow up for https://github.com/status-im/status-mobile/pull/19246

### Steps to Reproduce:
1. `UserA` and `UserB` are mutual contacts.
2. `UserA` goes to the profile of `UserB `-> tap three dots -> Block.
3. Check 1-1 chat after user blocking.

### Actual Result:
The 1-1 chat is still shown for `UserA`.

https://github.com/status-im/status-mobile/assets/52490791/047a7767-dd42-4911-8ef0-66af2336436f

### Expected Result:
The 1-1 chat should not be shown after the user is blocked.

**Comment by Parveshdhull** [comment]
related to https://github.com/status-im/status-mobile/issues/19327, should be handled together
