### ISSUE TITLE
Enable Testnet mode by default in e2e/PR builds 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#19347]
# Problem

In order to check wallet functionality in more effective way we need to have e2e automated tests created for that. Now our e2e tests take quite a long time, 35-40 min, and we need to avoid increasing that time as much as we can. So it would be very effective to have **Testnet mode** enabled by default in e2e builds instead of turning it on each time when running the tests.

## Acceptance Criteria
1. Open Profile
2. Click Advanced button

On **e2e and PR builds** Testnet mode toggle is turned on.
On **nightly and release builds** Testnet mode toggle is turned off

**Comment by smohamedjavid** [comment]
Enabling Test networks by default for Dev, E2E, and PR builds is done here https://github.com/status-im/status-mobile/pull/19365. 

**NOTE:** This enables in create account or restore account flow. If you upgrade the app from the old build with an existing profile, it will use the last saved (test networks enabled) state of that profile.
