### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method error in /location command[0.9.11]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1936]
### Description

*Type*: Bug

*Summary*: **NOTE:** this issue is difficult to reproduce
I catched a random crash with `java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapView.onResume()' on a null object reference` error when sending `/location` messages in 1x1 chat. Suppose it relates to slow map rendering or so but further investigation needed.

![image](https://user-images.githubusercontent.com/28752642/30866756-ccca05e0-a2e2-11e7-947a-e0fb6259ad41.png)

#### Expected behavior
App should not crash

### Additional Information

* Status version:  0.9.10-109-gf5e394b9+ (1666)
* Operating System: Android
#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/6636790/sessions/6/?accessToken=HQF4LvNimf3R0oRDJE0jkTeBcog

**Comment by annadanchenko** [comment]
Location command is removed
