### ISSUE TITLE
Channel permissions do not ignore unselected shared Addresses

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19363]
might be related to https://github.com/status-im/status-desktop/issues/14117#issuecomment-2022154947. Currently being investigated by Desktop team. 

**Preconditions:** 

Community A has token gated channel (let's say 0.001 to View only)

Mobile User A has Account 1 with 0.01 ETH and Account 2 with 0 ETH

**Steps:** 

1. User A opens share addresses screen of Community A
2. User A unselects Account 1 which has required tokens to View token gated channel
3. User A confirms changes and joins the Community A
4. See if token gated channel is locked for User A

**Expected result:** token gated channel is locked as User A has not shared Account 1 which has required tokens

**Actual result:** token gated channel is unlocked for User A. Same issue exists in case of editing shared addresses after joining the community. 

[UserA.zip](https://github.com/status-im/status-mobile/files/14721539/UserA.zip)

https://github.com/status-im/status-mobile/assets/97245802/0a249864-a8e6-470a-94eb-bcc4c5c990ce

<img width="1075" alt="Status Desktop 2024-03-22 12-51-16" src="https://github.com/status-im/status-mobile/assets/97245802/0ddf54d8-0f8a-44af-8e5e-e47874f21cba">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by anastasiyaig** [comment]
@cammellos i logged similar ticket for desktop with actual behavior https://github.com/status-im/status-desktop/issues/14117

**Comment by anastasiyaig** [comment]
@cammellos @jrainville i logged kinda similar ticket but perhaps it is not the same, if it is - feel free to close https://github.com/status-im/status-desktop/issues/14385

**Comment by jrainville** [comment]
> @cammellos i logged similar ticket for desktop with actual behavior [status-im/status-desktop#14117](https://github.com/status-im/status-desktop/issues/14117)

I'm pretty sure it's the same issue, so @kounkou 's PR should fix it for mobile too

**Comment by churik** [comment]
Fixed in https://github.com/status-im/status-mobile/commit/66a69e5eaa2e0c83e1876c936aae98f0ce25bd78

**Comment by anastasiyaig** [comment]
nice one, i need that in 2.28.1  @jrainville could you please help me to ensure this change lands to 2.28.1 pls?
