### ISSUE TITLE
The text within buttons is slightly visible when buttons are in a disabled state

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19373]
Seems this is a global issue affecting all buttons when disabled state is used in the app. In the steps below
### Steps:
1. Go to quo preview -> button -> make  Disabled option as 'True'

### Actual result:
![image](https://github.com/status-im/status-mobile/assets/52490791/91ed6b45-19ce-471b-8988-37e14c8f9f5b)

### Expected result:
![image](https://github.com/status-im/status-mobile/assets/52490791/98c35c50-c7b0-4650-9146-a4f2125af6ff)
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-590589&mode=design&t=bzdIrdu8kG3xUfx7-0

**Comment by ibrkhalil** [comment]
Similar to https://github.com/status-im/status-mobile/issues/19199

**Comment by VolodLytvynenko** [comment]
> Similar to #19199

@ibrkhalil thank you! Close it as dublicat
