### ISSUE TITLE
Amount input field is highlighted red despite valid amount is entered

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19372]
This issue rarely occurs on real devices but is reproducible in Android Studio emulators. I hope fixing it in Android Studio will resolve it for real devices too.

### Steps:
1. Recover user with some assets.
2. Go to the sent assets page.
3. Enter an available amount.

### Actual result:
The whole input field is highlighted in red.

https://github.com/status-im/status-mobile/assets/52490791/cd3f6207-ae51-4f69-9b65-43d3a8b17a4b

### Expected result:
The input field should only be highlighted in red if the user enters an amount that exceeds what they own.

### Devices:
Android Studio Pixel XL API 33

**Comment by churik** [comment]
couldn't reproduce it on real Google Pixel7, nightly 21/06/24

 Reopen if still relevant.
