### ISSUE TITLE
Regression in interpolation from Reanimated 3.6

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#19387]
There is a visible regression when interpolating height and spacings in our version of Reanimated which was updated here https://github.com/status-im/status-mobile/pull/18216. This result in janky animations

![Simulator Screen Recording - iPhone 11 Pro - 2024-03-25 at 14 10 57](https://github.com/status-im/status-mobile/assets/45393944/c608c8c7-2375-470d-ab79-e2dae0ef9f9e)

This is a known issue reported here: https://github.com/software-mansion/react-native-reanimated/issues/5685, and the latest version (3.8.1) doesn't solve it.

**Comment by ilmotta** [comment]
Closing as _not planned_ because animation work is currently descoped.
