### ISSUE TITLE
Sometimes token gated channels appear to be locked despite user is eligible to access them

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19380]
**Preconditions:** 

1. Here is a community for reproduction https://status.app/c/GykAAETdVs4Pj395FC1GQTEksfTDQ1uagoxEhZ10qg-MNHLBuJCFDOoyzr7rfQ==#zQ3shwfHwDmSkriERFJMwBD3Rt6TEqkgBaBgnpK47s1LwtQPt 
I was able to reproduce the issue with 2 different users, using this community, although for @qoqobolo was not able to reproduce by her user. 

Ping me up, when you will be reproducing the issue, so I make sure the community control node is online, otherwise you will be unable to join.  

2. For reproduction you need a user who has at least 0.001 ETH on Sepolia. See community permissions below:

<img width="1251" alt="Status Desktop 2024-03-25 12-05-48" src="https://github.com/status-im/status-mobile/assets/97245802/e7afb7c6-9633-4700-8f78-0cb21e43b8ef">

**Steps:** 

1. Join given community by mobile user who is eligible to join and access token gated channels. 
2. See if token gated channels are unlocked after join. 

**Actual result:** 
1. Token gated channels appear to be locked after user joined the community. 
2. After user leaves and re-joines the community, 2 of 3 channels become unlocked. 
3. After user leaves and re-joines  the community once again, all 3 channels appeared to be unlocked.

My assumption is that in communities with token gated channels which were created some time ago (in my case it is 2-3 days ago), new members (and maybe even current members) are not treated as eligible to access channel despite they own the required tokens. Only after couple of re-joinings the permissions are updated and start working correctly for the user. 

I haven't reproduced the issue with newly created communities with new token gated channels, although I know that @cammellos has faced with new ones as well. 

See video below

[Desktop_comm_aadmin_logs.log.zip](https://github.com/status-im/status-mobile/files/14742000/Desktop_comm_aadmin_logs.log.zip)
[mobile_user_community_member.zip](https://github.com/status-im/status-mobile/files/14742001/mobile_user_community_member.zip)

https://github.com/status-im/status-mobile/assets/97245802/9388ee26-99f0-4c41-be9f-0be687f6cfe6

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment]
Another example from Release 2.28:

1. User A is a member of token gated communities with token gated channels
2. User A receives token that makes user eligible to 'View only' token gated communities

**Actual result:** token gated communities remain to be locked for User A. After re-joing the community some of channels have become unlocked but some of them remained locked. 

[Status-debug-logs - 2024-03-27T155044.231.zip](https://github.com/status-im/status-mobile/files/14774303/Status-debug-logs.-.2024-03-27T155044.231.zip)

<img width="1073" alt="Status Desktop 2024-03-27 15-47-52" src="https://github.com/status-im/status-mobile/assets/97245802/944d6596-0b8b-442a-94fe-84cf4371982d">


https://github.com/status-im/status-mobile/assets/97245802/4ee70b3f-8081-4a58-acfb-e3a9307f0b0b

**Comment by cammellos** [comment]
@pavloburykh is this still an issue?

**Comment by churik** [comment]
as there were no clear steps to replicate, I believe we can descope it for now (taking into accounts new priorities) 

cc @cammellos

**Comment by churik** [comment]
Reopen if still relevant @pavloburykh
