### ISSUE TITLE
1-1 Chat not appearing after contact request is declined and contact request is resend

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19391]
### Steps to reproduce:
1. `User A` sends a Contact Request to `User B`.
2. `User B` declines the Contact Request.
3. `User B` sends a Contact Request to `User A`.

### Actual result:
`User A` and `User B` become mutual contacts, but the 1-1 chat does not appear for them.

https://github.com/status-im/status-mobile/assets/52490791/54ff71b5-b81f-4beb-9953-cbdda97f35eb

### Expected Result:
The 1-1 chat should appear for both users after `User A` and `User B` become mutual contacts.

### Nightly [25 Mar 2024, 02:08]

**Comment by seanstrom** [comment]
@cammellos can you confirm if this expected behaviour please? 🙏

**Comment by cammellos** [comment]
It's expected that they become contact, whether the chat is created or not, I am not sure it matters, so would be marking it as wont-fix as it's a bit of an edge case, as long as the user can actually send messages both direction (i.e they are able to create a chat).
