### ISSUE TITLE
Add IPFS / ENS To Status! 

### ISSUE THREAD

**Issue by kylerchin** [status-im/status-react#1939]
### User Story

As a developer and user, I want to run my decentralized apps server-less so that everybody can access apps without censorship.

### Description

The current standard is to call a web server for the data and DApp, however, these servers can be blocked, censored, or even taken offline with a DDOS attack. Also, this is the blockchain age. Servers are useless... right?

### Solution

My proposal is to add the IPFS daemon directly into Status, allowing apps to be resistant to censorship and dapps to be called from IPFS and run using HTML / JS stack. Users sharing links and other content can also view them directly in the app.

Then, we use ENS to update our dapps by using some domain and updating the txt.

Hopefully this gets worked out. I would really like to see this.

**Comment by jeluard** [comment]
ENS support is duplicated by #4747 and #5028. IPFS will be considered later.
