### ISSUE TITLE
Use EIP55 checksum for address encoding

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#194]
It is possible to encode Ethereum addresses into IBAN address, the benefit for this would be future integration with existing banking systems and checksum against malformed addresses.

https://github.com/ethereum/wiki/wiki/ICAP:-Inter-exchange-Client-Address-Protocol

We should make this the default (whilst also handling normal ethereum addresses)

**Comment by sla-shi** [comment]
@jarradh can we skip this for the Beta?
