### ISSUE TITLE
Incorrect user shown on login page after logout

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19404]
### Steps:
1. Create `UserA`
2. Log out
3. Recover `UserB`
4. Log out
5. Check the login page

### Actual result:
The login in page of `UserA` is shown instead of `UserB`

https://github.com/status-im/status-mobile/assets/52490791/0ecd1ee5-7695-4d95-93bb-bb8a9b181bb4

### Expected result:
The login page for `UserB` should be shown after logging out.

### ENV:
[26 Mar 2024]

**Comment by Parveshdhull** [comment]
Interesting issue happens when I use account shared in video, but If I use another account it works normally.

**Comment by Parveshdhull** [comment]
`:timestamp 0` intersting

**Comment by Parveshdhull** [comment]
It seems timestamp is 0 while recovering accounts with profile picture

**Comment by Parveshdhull** [comment]
We are updating timestamp inside `startNodeWithAccount` and I checked in logs, timestamp got updated fine. Have to check why it returning 0 at app start

**Comment by Parveshdhull** [comment]
If I call GetAccount in `startNodeWithAccount` thenb timestamp is ok, but in getAccounts at time of login timestamp is 0

**Comment by Parveshdhull** [comment]
So we are overwriting timestamp somewhere with 0 value at the time of account creation for above account
![image](https://github.com/status-im/status-mobile/assets/17097240/b9743ced-842d-457d-bb5e-98b2bf2eb108)

**Comment by Parveshdhull** [comment]
So account creation works fine, overwrite happens at later stage 

Below are stages in order of being called, and removing any of stage fixes the issue for me.


-> `profile.login/login-node-signal` -> `profile.login/login-existing-profile` -> `:profile.login/get-chats-callback` -> `wakuext_startMessenger` -> [Start function](https://github.com/status-im/status-go/blob/e9a2f19c17237017bae1fdd64be7f46624d65996/protocol/messenger.go#L747) -> [StartMailserverCycle](https://github.com/status-im/status-go/blob/e9a2f19c17237017bae1fdd64be7f46624d65996/protocol/messenger.go#L853) -> [StartMailserverCycle Function](https://github.com/status-im/status-go/blob/e9a2f19c17237017bae1fdd64be7f46624d65996/protocol/messenger_mailserver_cycle.go#L54) -> [verifyStorenodeStatus](https://github.com/status-im/status-go/blob/e9a2f19c17237017bae1fdd64be7f46624d65996/protocol/messenger_mailserver_cycle.go#L81) -> [verifyStoreNodeStatus function](https://github.com/status-im/status-go/blob/e9a2f19c17237017bae1fdd64be7f46624d65996/protocol/messenger_mailserver_cycle.go#L664) -> [m.disconnectStorenodeIfRequired](https://github.com/status-im/status-go/blob/e9a2f19c17237017bae1fdd64be7f46624d65996/protocol/messenger_mailserver_cycle.go#L671)

**Comment by flexsurfer** [comment]
hey @VolodLytvynenko are these the only steps that are reproduced? for example, if i have two profiles and login one after another will there be the same bug?

**Comment by VolodLytvynenko** [comment]
> hey @VolodLytvynenko are these the only steps that are reproduced? for example, if i have two profiles and login one after another will there be the same bug?

@flexsurfer  I can log in to other profiles. The issue is that after logging out as a specific user, the profile of another user is shown on the login page. It seems this only happens for one of my users, so the issue seems to be user-specific. I haven't encountered this issue anymore when used some fresh users, probably because I didn't find the exact steps how to reproduce it.
