### ISSUE TITLE
 [Android] 'cannot set property “reagent-compiler2” of null' error is shown after an attempt to scan wallet QR via universal scanner

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19411]
### Steps:
1. `UserA` Scans the QR of `UserB`
![image](https://github.com/status-im/status-mobile/assets/52490791/2303e155-572f-44cf-b3bc-ad252b963c33)

### Actual result:
'cannot set property “reagent-compiler2” of null' error is shown

https://github.com/status-im/status-mobile/assets/52490791/6ebf1fc3-a1a6-45db-a3b5-277436f198c3

### Expected result:
The wallet is opened

### Device:
Pixel 7a, Android 14

### Logs:
[Status-debug-logs (3).zip](https://github.com/status-im/status-mobile/files/14724875/Status-debug-logs.3.zip)

**Comment by Parveshdhull** [comment]
fixed in https://github.com/status-im/status-mobile/pull/19409
