### ISSUE TITLE
Update usage of Login/Create/Restore account

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-react#19419]
# Problem

This PR introduces breaking changes to `LoginAccount`/`CreateAccountAndLogin`/`RestoreAccountAndLogin`:
- https://github.com/status-im/status-go/pull/4980

## What changed?

- Added `FetchBackup` parameter to `RestoreAccount`. 
It's `false` by default, this is a change of default behaviour.
If you want to keep your current behaviour, set this to `true`.

- Added `ImageCropRectangle` to `CreateAccount`. 
Don't know if you want to reuse it. Cropping already works for you now.

- Allow `CreateAccount.displayName` to be empty when an account is being restored. 
This is to create an account, then fetch the backup and save the displayName from backup.
Since you don't currently support restoring an account without setting a new `displayName`, maybe you don't need this.

- `CreateAccount.CurrentNetwork` is deprecated. Just remove it, no need to pass anything instead

- `CreateAccount.NetworkID` is now optional. Default network is selected automatically.

## QA

@qoqobolo it would be nice to make sure that those workflows are fine with my status-go changes:
- login into account
- create a new account
- restore an account from seed phrase

**Comment by qoqobolo** [comment]
Hi @igor-sirotin, thank you for submitting these changes for testing!

@seanstrom created a [PR on the mobile side](https://github.com/status-im/status-mobile/pull/19420), we are waiting for reviews and e2e tests. We'll let you know as soon as we get the results.
Thanks for waiting
