### ISSUE TITLE
Wallet - Skip steps while sending an asset picked from an account overview

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#19410]
# Bug Report

## Problem 
[comment]: # (A problem description)

We need to use the recently created wizard mechanism to skip the needed steps while sending an asset from the account overview screen in the wallet.

By long pressing an asset, we get the following image:

<img src="https://github.com/status-im/status-mobile/assets/90291778/f9286d69-b84e-4aa0-96d9-e54b92bc458f" height="500" >

The flow to fix is the **Send** one.

Figma:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7701-154896&mode=design&t=VEZquM5jvvYIUGvQ-4

This issue is also present in other flows:

- Send a Collectible: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-315956&mode=design&t=VEZquM5jvvYIUGvQ-4

Split this issue if needed

#### Expected behavior

Skip steps that add already known information

#### Actual behavior

All the steps are presented to the user

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
related issue https://github.com/status-im/status-mobile/issues/16990

**Comment by OmarBasem** [comment]
@ulisesmac isn't the step to pick a token already skipped when going to the send flow the from token's drawer?
