### ISSUE TITLE
Share all addresses toggle is replaced by check box

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19421]
Looks like regression from https://github.com/status-im/status-mobile/pull/19296 cc @ibrkhalil 

**Actual result:**

![photo_2024-03-27 18 51 48](https://github.com/status-im/status-mobile/assets/97245802/456ee1a3-894f-4c6d-90fe-eb37fd8d2ab2)

**Expected result:** 

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16113-139629&mode=design&t=UKL9L4I9IC4gOEl5-0

![photo_2024-03-27 18 54 28](https://github.com/status-im/status-mobile/assets/97245802/eb7340fb-8a84-422a-b7a1-bf54c8c5156b)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Yup, This is a mistake from me
Will fix it asap

**Comment by ibrkhalil** [comment]
Added a PR
