### ISSUE TITLE
The "Pinned messages" button displaces the "Mute chat" button if a long message is pinned

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19438]
# Bug Report

## Problem 

<img width="314" alt="Screenshot 2024-03-28 at 14 46 50" src="https://github.com/status-im/status-mobile/assets/67952253/d4113704-d0fa-4d14-9f8f-a8fd56b91e01">

<img width="317" alt="Screenshot 2024-03-28 at 14 48 38" src="https://github.com/status-im/status-mobile/assets/67952253/caa9064b-3710-4a41-af0a-4ee84691e2db">

#### Expected behavior

The button has a fixed width regardless of the content

### Reproduction

1. Pin a long message in any chat/channel
2. Check the top of the chat

### Additional Information

- Status version: RC 2.28 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
cc @clauxx (related PR https://github.com/status-im/status-mobile/pull/19031)
