### ISSUE TITLE
Fees always displayed as 0 for all networks on the send assets page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19431]
### Steps:
1. Recover user with some assets.
2. Go to send assets page.
3. Enter available assets value.
4. Check fees.

### Actual result:
The fees are always shown as 0 for all networks.

![image](https://github.com/status-im/status-mobile/assets/52490791/eef58956-1f65-427e-84cf-5c5402baa67a)

### Expected result:
The fees should be calculated and displayed for each network.
Here is a screenshot of using MetaMask to estimate the fee for the main network.
![image](https://github.com/status-im/status-mobile/assets/52490791/5ec3af32-5637-4582-b9dc-00d4eec66689)

**Comment by FFFra** [comment]
It only happens on recovered accounts?

**Comment by VolodLytvynenko** [comment]
> It only happens on recovered accounts?

Hey. @FFFra this happens for recovered and for new users (who were not recovered) as well
