### ISSUE TITLE
Routes not found after navigating back to Send Assets page from confirmation screen

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19442]
### Steps:
1. Go to send assets page
2. Enter an available value that the user has.
3. Go to confirmation page
4. Tap back

### Actual result:
The user is navigated back to the send assets page where the available assets value is predefined, but the routes are not found.

https://github.com/status-im/status-mobile/assets/52490791/42d41377-25d1-4011-8104-9afbf98e4669

### Expected result:
Potential solutions:
- The user should be navigated back to the send assets page where the value of the available assets is predefined, and the routes are not found.
- The user could be navigated back where the value of the available assets is not predefined, and the user should enter a new value to find the routes.

### ENV:
NIghlty 28 Mar 2024

**Comment by OmarBasem** [comment]
@VolodLytvynenko I think this issue is not reproducible anymore

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem. Correct. Thank you!
