### ISSUE TITLE
Link to community channel with it's preview pasts by default to any user's message

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19446]
# Bug Report

## Problem 
[comment]: # (A problem description)
User types message with any text and when he posts it he sees his entered text + community link with link preview
<img width="208" alt="Screenshot 2024-03-28 at 17 37 30" src="https://github.com/status-im/status-mobile/assets/147824399/640fbe1f-fc5f-4796-9d5c-86f53cd5751f">

#### Expected behavior
User types message and it contains only visible information entered by the user

#### Actual behavior
Link to community channel pasts by default to any user's message

### Reproduction

1. Login to app
2. Open any of your communities
3. Share your community to any of your contacts (this step we use just to have smth to copy in our next step)
4. Go to chat with contact from previous step
5. Copy link to community from chat
6. Paste copied linked to chat and post it
7. Enter any text to composer and post

https://github.com/status-im/status-mobile/assets/147824399/871f592c-b89e-475e-844f-24f9e9563ead

### Additional Information

- Status version: Release build 28/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
fixed in https://github.com/status-im/status-mobile/pull/19359
