### ISSUE TITLE
Error Lodaing Data error is shown for newly created accounts [0.9.11]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1944]
### Description

*Type*: Bug

*Summary*: `Error Loading Data' message is shown in new wallet and the asset is not updated . I can see recent values for %, asset and USD only when I re-launch the app however the error message is still in place

Per Goran: I think this is the same issue I found. The problem there is that `calculatePrice` in wallet bot sometimes throws error "Invalid JSON RPC response: undefined". The only thing of note that happens in that function are `web3.eth.estimateGas` and `web3.eth.gasPrice`

Per Oskar: I would assume https://github.com/status-im/status-react/blob/9f5d808702d9512e9f906e7d6f9b18d92dbee8e8/src/status_im/ui/screens/wallet/events.cljs#L112 is event that fails (can be verified by grepping logs for `update-balance` or `update-price`)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/30911285-b68e46b6-a390-11e7-921c-587920184cd6.png)

### Reproduction

- Open Status
- Create new account
- Open Wallet tab

### Additional Information
* Status version: 0.9.10-112-ga8cda54b+ (1669)
* Operating System: Android

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/6644531/sessions/8/?accessToken=Mw-7DSHu8PFXb4yFbyooUU8xems

**Comment by oskarth** [comment]
@asemiankevich It seems like the majority of logs are gone. Is that a special build of some kind? Anyway it seems like it isn't a blocker for the release so I guess it isn't a high-prio fix.

**Comment by sla-shi** [comment]
Got the same issue in the epic/wallet build, but instead of 0 it displays ...
![image](https://user-images.githubusercontent.com/1944596/30930747-494ddd24-a3cb-11e7-8fc5-bb5e99b80d83.png)

**Comment by flexsurfer** [comment]
`Unable to get balance:  Error: can't fetch trie key b1c65793e228f499aed19828c37310908c12549b33b23ea516ef3da6bdf688fa: no suitable peers available`

**Comment by yenda** [comment]
This issue is probably outdated as of today

**Comment by asemiankevich** [comment]
this isssue it not reproducible anymore in latest develop
