### ISSUE TITLE
 Accounts can't be changed on send assets page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19444]
### Steps:
1. Restore the user with 2 accounts in the wallet (both shouldn't be watch only)
2. Go to Send Assets page
3. Change the account
4. Check the balance

### Actual result:
After changing the account, the balance is not updated. The user still sees the max value related to the first account selected before the change.

https://github.com/status-im/status-mobile/assets/52490791/08a4aaf6-711c-4a06-b68c-fbdee993bff2

### Expected result:
After the account change, the balance is of new  changed account should be shown

### ENV:
28 Mar 2024

**Comment by J-Son89** [comment]
should be working now
