### ISSUE TITLE
The synced data is not displayed correctly for a synced user after initial syncing

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19455]
Probably this issue will be fixed together with https://github.com/status-im/status-mobile/issues/19454

### Steps:
1. `Device A`  performs the following actions:
   1. Receive contact Request and approve it from `User1`
   2. Receive and send a few messages in 1-1 chat from `User1`
   3. Receive contact Request and decline it  from `User2`
2. `Device A` generates QR code
3. `Device B` scans this QR code generated by `Device A`

### Actual result 
i. The approved contact request from `User1` is not shown in the Activity Center for `Device B`, but in fact both users are mutual contacts
ii. Messages are not shown for `Device 2` in 1-1 chat
iii. The declined Contact request from `User2` is not shown in Activity Center for `Device 2`

What `Device 1` sees in the Activity center
![image](https://github.com/status-im/status-mobile/assets/52490791/644a8d99-056a-486c-a859-3a2d3f1f734b)

What `Device 2` sees in the Activity center
![image](https://github.com/status-im/status-mobile/assets/52490791/51cad358-83e1-4aaf-9003-8321e5b2543e)

### Expected result:
All data should for synced `Device B` should be shown in the same way as for `Device A`

### logs of `Device B`
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/15219035/Status-debug-logs.zip)

**Comment by ibrkhalil** [comment]
@VolodLytvynenko Can we validate this is still reproducible?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko Can we validate this is still reproducible?

@ibrkhalil unfortunately can't check it due recent blocker  https://github.com/status-im/status-mobile/issues/19655

**Comment by cammellos** [comment]
@VolodLytvynenko would you mind trying again after the fix?

**Comment by VolodLytvynenko** [comment]
@cammellos @ibrkhalil Thanks for the ping. Today I will check this one more time

**Comment by qfrank** [comment]
> @cammellos @ibrkhalil Thanks for the ping. Today I will check this one more time

Hi @VolodLytvynenko , any update on this?

**Comment by VolodLytvynenko** [comment]
> > @cammellos @ibrkhalil Thanks for the ping. Today I will check this one more time
> 
> Hi @VolodLytvynenko , any update on this?

Hi @qfrank issue still reproduced. Just updated the issue description and logs [here](https://github.com/status-im/status-mobile/issues/19455#issue-2215753480). Sorry for testing delay

**Comment by qfrank** [comment]
relate error log for `HandleSyncContactRequestDecision`

```
ERROR[05-07|05:11:00.179|github.com/status-im/status-go/protocol/messenger_contacts.go:282]                                                 contact request not found                contactRequestID=0x9ed553fbdab12c1db4f91b14851abae76d9c49e8ab95ee12db515ba9ccf55188 error="record not found"
ERROR[05-07|05:11:00.179|github.com/status-im/status-go/protocol/messenger_sync_raw_messages.go:187]                                        failed to HandleSyncContactRequestDecision when HandleSyncRawMessages error="record not found"


INFO [05-07|05:11:00.177|github.com/status-im/status-go/protocol/messenger_contacts.go:165]                                                 declineContactRequest 
ERROR[05-07|05:11:00.178|github.com/status-im/status-go/protocol/messenger_sync_raw_messages.go:187]                                        failed to HandleSyncContactRequestDecision when HandleSyncRawMessages error="record not found"
```
