### ISSUE TITLE
The synced data is not displayed correctly for a synced user returning from offline

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19454]
Probably this issue will be fixed together with https://github.com/status-im/status-mobile/issues/19455

### Steps:
1. `Device A` and `Device B` are synced
2. `Device B` goes offline
3. `Device A` performs the following actions:
   1. Receive contact Request and approve it from `User1`
   2. Receive contact Request and decline it  from `User2`
   3. Receive a contact request from`User3`, but doesn't approve it

### Actual result 
i. The approved contact request from `User1` is not shown in the Activity Center for `Device B`, but in fact both users are mutual contacts
ii. The declined Contact request from `User2` is not shown in Activity Center for `Device 2`
iii. The received a contact request from`User3` is not shown in Activity center and if profile of`User3` is opened, the 'send request' button is shown instead of 'Contact request is pending'

What `Device 1` sees in the Activity center
![image](https://github.com/status-im/status-mobile/assets/52490791/e71ba988-57e2-4bda-ac4a-1b1432ccf38b)

What `Device 2` sees in the Activity center
![image](https://github.com/status-im/status-mobile/assets/52490791/721f4f57-a703-4b92-a86c-9bfd5acc5fc8)

### Expected result:
All data should for synced `Device B` should be shown in the same way as for `Device A`

**Comment by ibrkhalil** [comment]
@VolodLytvynenko Can we validate this is still reproducible?

**Comment by ilmotta** [comment]
@VolodLytvynenko can we close this issue given https://github.com/status-im/status-mobile/issues/19455 has been closed already?

**Comment by VolodLytvynenko** [comment]
hi @ilmotta just checked. The issue can be closed
