### ISSUE TITLE
User stops receiving messages at some point although his messages are delivered to receivers

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19453]
Facing the issue in Release 2.28 build. 

There are no specific steps. At some moment user stopps receiving messages in communities or 1-1 chats but at the same time his messages are delivered to the receivers. 

Relogins/app reopening do not help. 

Please, check attached logs, maybe something helpful will be found. 

[receiver_does_not _receive_messages.zip](https://github.com/status-im/status-mobile/files/14805635/receiver_does_not._receive_messages.zip)
[sender_andr_user.zip](https://github.com/status-im/status-mobile/files/14805636/sender_andr_user.zip)

https://github.com/status-im/status-mobile/assets/97245802/39f65f26-d50d-4d0e-966e-6e9ac3f72f0a

### Additional Information

- Status version: release 2.28 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment]
@vitvly  **UPDATE:**

After some time (20-30 minutes) messages were delivered to the Receiver. 

Here are updated logs after receiver started receiving messages again

[receiver_logs_after_he_started_receiving_messages_again.zip](https://github.com/status-im/status-mobile/files/14805853/receiver_logs_after_he_started_receiving_messages_again.zip)

**Comment by cammellos** [comment]
```
ERROR[03-29|14:57:56.353|github.com/status-im/status-go/vendor/github.com/status-im/mvds/node/node.go:346]                                  error while mapping sync state           namespace=mvds error="sql: database is closed"
```
same error, this is something new and a critical issue, not related to message reliability per se though

**Comment by jrainville** [comment]
I just learned that you experience this. We also had this issue. It turned out that the message receiving thread was hanging and that's why we didn't receive anything.

It was fixed by removing the hanging code. See the last comments here: https://github.com/status-im/status-desktop/issues/13710

**Comment by cammellos** [comment]
@jrainville did you see 
"ERROR[03-29|14:57:56.353|github.com/status-im/status-go/vendor/github.com/status-im/mvds/node/node.go:346]                                  error while mapping sync state           namespace=mvds error="sql: database is closed"
"
in the logs?

as otherwise I think it might be two separate issues?

**Comment by jrainville** [comment]
@cammellos We saw it once or twice, but it turned out to be a red herring iirc

**Comment by churik** [comment]
should be fixed according to discussion here https://github.com/status-im/status-desktop/issues/13710 , closing for now - reopen if it is still relevant
