### ISSUE TITLE
Wallet - design review - main screen

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1946]
![image](https://user-images.githubusercontent.com/11790366/31083178-a85b12c4-a799-11e7-8b04-4731adaf135c.png)
![image](https://user-images.githubusercontent.com/11790366/31083200-baf95738-a799-11e7-870b-b1c9e1049ddf.png)

**Comment by andmironov** [comment]
hey guys, let's trim the wallet's name with `...` on android?

**Comment by jeluard** [comment]
@andmironov Indeed that's an issue but shouldn't we try to have short name in most languages?

**Comment by sla-shi** [comment]
smaller font maybe?

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
