### ISSUE TITLE
Not all communities are synced after sync process

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19464]
### Steps:
1. `Desktop User` Creates at least 3-5 communities (No matter which community type)
2. Moblie User Joins to all of the communities using `Device 1`
3. Moblie User scans the sync QR code of  `Device 1` using  `Device 2`
4. `Device 2` checks the synced communities

### Actual result:
Only some communities are synced. In my case, if Device 1 has communities A, B, and C, only community A is synced to Device 2.

Device 1 communities:
![image](https://github.com/status-im/status-mobile/assets/52490791/c3d25094-e54c-4421-a8b4-20ce0d911ce5)

Device 2 communities after sync with Device 1:
![image](https://github.com/status-im/status-mobile/assets/52490791/3efa693c-4763-4fb3-addf-44c481ab6c6f)

### Expected result:
All communities are synced

### ENV:
- Desktop release build 2.28.0 Status go 0.177.0
- Mobile release build [29 Mar 2024]

### Logs:
Device 1 logs
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14822077/Status-debug-logs.zip)

Device 2 logs
[logs.zip](https://github.com/status-im/status-mobile/files/14822074/logs.zip)

**Comment by ibrkhalil** [comment]
Cannot sync
https://github.com/status-im/status-mobile/assets/33176106/9704a9f3-c802-4e66-bcc8-ea58dc6f3217

**Comment by VolodLytvynenko** [comment]
> Cannot sync https://github.com/status-im/status-mobile/assets/33176106/9704a9f3-c802-4e66-bcc8-ea58dc6f3217

Hi @ibrkhalil, are your devices using the same local network? Try regenerating the QR code and syncing again. If the issue persists, could you please share the logs in [this](https://github.com/status-im/status-mobile/issues/19452) issue? 

Also, to resolve this and sync successfully, just reinstall the builds, as it may help.

**Comment by VolodLytvynenko** [comment]
Not reproduced anymore
