### ISSUE TITLE
Synced mobile user sees a request to join a community in the Activity Center, even though the request has already been accepted

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19465]
### Steps:
1. `Desktop User` Creates an admin manual required approval community
2. `User B` sends a Contact request to join the community
3.  `Desktop User` accepts `User B`s request
4. `Mobile user` syncs with `Desktop User`  via sync QR code

### Actual result:
The `mobile user` sees the request to join the community in the Activity Center of `User B`, even though User B is already a community member.
![image](https://github.com/status-im/status-mobile/assets/52490791/16bc1d68-a6eb-4014-8d01-1ee16d052713)

### Expected result:
All accepted/declined requests to join should be synced

### ENV:
- Desktop release build 2.28.0 Status go 0.177.0
- Mobile release build [29 Mar 2024]

**Comment by cammellos** [comment]
This looks like a low priority issue, I would be inclined to consider a wont-fix and close it, what do you think?

**Comment by VolodLytvynenko** [comment]
> This looks like a low priority issue, I would be inclined to consider a wont-fix and close it, what do you think?

Hi @cammellos . Indeed, priority is low. Can be left as 'won't fix'
