### ISSUE TITLE
The synced user does not receive the request to join the community

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19471]
### Preconditions:
- `User A` of `Device 1`  is an owner of a community that requires manual acceptance

### Steps to reproduce:
1.`Device 2` syncs with  `Device 1` (this step should only be done when `Device 1` has already created a community)
2. `User A` receives a request to join the community from `User B`
3. `Device 2` checks Activity Center

### Actual result:
`Device 2` does not receive requests to join to community in Activity Center

### Expected result:
`Device 2` receives requests to join to community  in Activity Center

### Logs:
Desktop logs of `Device 1` user:
[logs.txt](https://github.com/status-im/status-mobile/files/14824026/logs.txt)

Mobile logs of `Device 2` user:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14824033/Status-debug-logs.1.zip)

**Comment by jo-mut** [comment]
@VolodLytvynenko Here is a video trying to reproduce this. It seems to work just okay, I am able to receive request to join notification on both devices of User A

The recording is of two simulators but I also tried with User A of device 1 being the desktop client and device 2 being the simulator and user B being an android client and still works fine

Please advise if a may have missed something in the reproduction

https://github.com/status-im/status-mobile/assets/28704507/3685ef2e-412d-4756-8545-3ec2a68ffdbd

**Comment by VolodLytvynenko** [comment]
@jo-mut not reproducible for me as well. Can be closed
