### ISSUE TITLE
Incorrect derivation path for newly generated keypair accounts and theirs derived acccounts

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19472]
### Steps:
1. Create an account with a newly generated keypair (see flow [here](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-596827&mode=design&t=iugkFHlUKh8btaCh-0) how to generate keypair)
2. Check the derivation path for newly created account

### Actual result:
The number is incremented at the end for the Derivation path for keypair account and = m/44/60'/0'/0/`<incremented account number>`
 
### Expected result:
The derivation path for master (keypair) accounts should not have an incremented number at the end; it should be m/44/60'/0'/0/0. Only accounts that are derived from the master (keypair) accounts should have an incremented path.

For example, if a user has two generated keypairs and two additional accounts  derived for each keypair account then derivation path hierarchy should looks so:

- Keypair account first: m/44/60'/0'/0/0
  - Test account 2 (derived from Keypair account first): m/44/60'/0'/0/1
  - Test account 3 (derived from Keypair account first): m/44/60'/0'/0/2
- Keypair account second: m/44/60'/0'/0/0
  - Test account 4 (derived from Keypair account second): m/44/60'/0'/0/1
  - Test account 5 (derived from Keypair account second): m/44/60'/0'/0/2

discussed in https://discord.com/channels/1210237582470807632/1217175448828514344/1224605345461047326
in the same way it works for Desktop.

**Comment by ulisesmac** [comment]
Related:
- https://github.com/status-im/status-mobile/pull/19531#issuecomment-2045894436

**Comment by J-Son89** [comment]
@ulisesmac - since derivation path flows have been descoped can you unassign this issue and block it for now?
Or what's the status of this issue? 🤔

**Comment by ulisesmac** [comment]
@J-Son89 

We must generate a default derivation path for a new derived account in wallet. This issue isn't about the derivation path flow (where you can set a custom one) it's about adding a new account in wallet.

Currently, we are stuck, seems Android is not creating a keystore file so maybe there's a bug on Status go side, this issue has become very complex.

BTW, @OmarBasem did you replicate the issue we had for new keypairs? If you did, it's time to align with Sale and check what's the problem in Status go.

**Comment by OmarBasem** [comment]
Hey @ulisesmac,
What I had in mind did not work also. 

> maybe there's a bug on Status go side

I think it works properly on Desktop (?)
