### ISSUE TITLE
Wallet - design review - choose recipient

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1947]
![image](https://user-images.githubusercontent.com/11790366/31083279-facd8096-a799-11e7-8e4e-cd9257ee6011.png)
![image](https://user-images.githubusercontent.com/11790366/31083286-0204f6be-a79a-11e7-9ddd-768d1e08d5d1.png)

**Comment by andmironov** [comment]
the paddings in buttons seem to be a little off on both platforms, please double check
