### ISSUE TITLE
📱 `make run-ios` doesn't work with XCode 15.3

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#19479]
# Bug Report

## Problem 
After (accidently) upgrading Xcode to 15.3, the `make run-ios` command stopped working. This was the logged error:
<img width="1792" alt="Screenshot 2024-04-02 at 4 42 04 PM" src="https://github.com/status-im/status-mobile/assets/1925158/de983672-c0a8-427d-b0d3-c76774b116ba">

```
error: builder for '/nix/store/y9mrh8y22ggnj1j7l1pxnq1cxamrbwpq-xcode-wrapper-plus-15.0.drv' failed with exit code 141
error: build of '/nix/store/3gv3w4dc15268ac230xf9az6k2q42xpr-status-mobile-node-deps-2.27.0-patched.drv', '/nix/store/9caw7c2b48nkiy6wr965f8yn6nwjaxih-status-go-0.178.0-eb13459-ios.drv', '/nix/store/d0f0h8gk24k50ls3j714dfd6hyg747pw-watchman-4.9.0.drv', '/nix/store/jp4zphn5qyja5dc5979aqmn4j93rzn4z-fastlane-2.217.0.drv', '/nix/store/y9mrh8y22ggnj1j7l1pxnq1cxamrbwpq-xcode-wrapper-plus-15.0.drv' failed
make: *** [run-ios] Error 1
```

I tried to clean up the dirctory in questions with :
- `make clean`
- `make ios-clean` and `make xcode-clean`
- `make purge`
- manually removing the problematic directory

But @siddarthkay told me that XCode was a problem. And the temporary solution was to downgrade to Xcode 15.1.

#### Expected behavior
The app should build.

### Reproduction

1. Upgrade to Xcode 15.3
2. `make run-ios` 

### Additional Information

- Operating System: iOS

**Comment by siddarthkay** [comment]
This is issue is fixed by a combination of PRs.
1) modification of XcodeWrapper -> https://github.com/status-im/status-mobile/pull/19822 and
2) adding Xcode 15.3 to supported versions list -> https://github.com/status-im/status-mobile/pull/20127

Pls feel free to re-open if you observe any iOS build failures with Xcode 15.3
