### ISSUE TITLE
Wallet - design review - transactions-history

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1948]
![image](https://user-images.githubusercontent.com/11790366/31083357-2c5cde68-a79a-11e7-8903-15877d218f66.png)
![image](https://user-images.githubusercontent.com/11790366/31083369-31696278-a79a-11e7-9fff-7a4b747c1245.png)
![image](https://user-images.githubusercontent.com/11790366/31083385-3a8d5d32-a79a-11e7-9f8b-d7cee51f4226.png)
![image](https://user-images.githubusercontent.com/11790366/31083395-412f717a-a79a-11e7-9872-756275668b79.png)

**Comment by andmironov** [comment]
- a corner radius issue in `Sign` button on IOS screen
- did we solve this technical issue with letter-spacing in tab names on Android?

**Comment by jeluard** [comment]
Corner radius is now correct.

@yenda Can you comment on the `letter-spacing` issue?

**Comment by annadanchenko** [comment]
@jeluard corner radius for Sign button is OK only on Android now, on iOS it's still a square (checked on last develop build 0.9.11d179)

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
