### ISSUE TITLE
 In case of many too many failed biometric attempts user is unable to confirm via password [ANDROID]

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19488]
Android only. 

Reproducible in the following flows: sending community request, creating wallet, revealing sync QR code. 

**Steps:** 

1. Enable Fingerprint in app settings
2. Open sending Request to join community screen (creating wallet, revealing sync QR code)
3. Scan wrong finger to generate 'Too many attempts error' 
4. See if you will be able to confirm via password

**Expected result:** password bottom sheet should be opened so user be able to confirm via password. 

**Actual result:** error appears every time user tries to send request, password bottom sheet does not appear. 

https://github.com/status-im/status-mobile/assets/97245802/9eed7af3-bab8-4921-941e-b435a78c1ff7

### Additional Information

- Status version: nightly 
- Operating System: Android 12, Samsung Galaxy A52

**Comment by clauxx** [comment]
Most likely due to the ERROR_LOCKOUT [error](https://developer.android.com/reference/androidx/biometric/BiometricPrompt).
