### ISSUE TITLE
Sepolia optimism collectibles are not fetched on mobile

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19494]
Might be related to https://github.com/status-im/status-mobile/pull/19445 cc @jakubgs @dlipicar 

Collectibles minted on Sepolia optimism network are not fetched in mobile app

**Steps:** 

1. Login/recover user holding collectibles minted on Sepolia optimism network
2. See if collectibles are displayed

**Actual result:** collectibles are not displayed. 

[Status-debug-logs - 2024-04-03T135300.312.zip](https://github.com/status-im/status-mobile/files/14850944/Status-debug-logs.-.2024-04-03T135300.312.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by jakubgs** [comment]
The release tokens for both mobile and desktop have not been used in the past 24 hours:

![image](https://github.com/status-im/status-mobile/assets/2212681/06467835-c134-4f11-aae0-2ecf062ae6ce)

As far as I can tell they are correct in Jenkins credentials. But I updated them just in case.

**Comment by jakubgs** [comment]
Release branch does not have any of the recent CI changes made in `develop`, so I've cherry picked them:

- [`status-mobile#183a78ae`](https://github.com/status-im/status-mobile/commit/183a78ae) - ci: bump jenkins-lib to fix sepolia token typo
- [`status-mobile#408f461e`](https://github.com/status-im/status-mobile/commit/408f461e) - ci: make contract tests stage optional
- [`status-mobile#c54830dd`](https://github.com/status-im/status-mobile/commit/c54830dd) - ci: use new Alchemy API tokens from env file

**Comment by dlipicar** [comment]
The log shows multiple successful collectible fetches from optimism Sepolia.
Opensea shows no collectibles for the account on that chain
https://testnets.opensea.io/0x217FD1c473393A1AC24114b89a6cc5c5Ca8A6EAb?search[chains][0]=OPTIMISM_SEPOLIA

**Comment by dlipicar** [comment]
Hmm interesting. Alchemy also shows 0 collectibles
![image](https://github.com/status-im/status-mobile/assets/11161531/9527c8d8-4b11-4da3-a4f7-83b02dc23dfe)

But etherscan shows me one
https://sepolia-optimism.etherscan.io/address/0x217FD1c473393A1AC24114b89a6cc5c5Ca8A6EAb

I'll ping Alchemy support

**Comment by pavloburykh** [comment]
> I'll ping Alchemy support

Thank you @dlipicar!

**Comment by pavloburykh** [comment]
closing this issue for now, as Sepolia optimism collectibles seem to be fetched okay now. The issue was on Alchemy's side. Thanks @dlipicar for communication with their support.
