### ISSUE TITLE
Multichain address is not recognized by the "Send to" input field

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19496]
# Bug Report

## Problem 

The `Confirm` button doesn't become active when pasting a multichain address.
It recognizes the address if you remove the prefixes. 

https://github.com/status-im/status-mobile/assets/67952253/b4db1b78-f025-483e-b3de-7faab1c565dc

#### Expected behavior
Can paste a multichain address and continue the sending flow

#### Actual behavior
The `Confirm` button stays inactive, you need to remove the prefixes

### Reproduction

1. Open Wallet
2. `Send`
3. Paste a multichain address, e.g. `eth:opt:arb:0xe8386a6e2657ae8d5c3a94e687e43e41d35f27bd`

### Additional Information

- Status version: nightly 3/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
@J-Son89 not sure if it's a bug or an unfinished feature (couldn't find anything related in the repo). Please, feel free to adjust/close the issue

**Comment by J-Son89** [comment]
Thanks @qoqobolo - I'm not sure either 😀 
Thanks for raising this issue anyway we'll get it sorted! 🙏

**Comment by J-Son89** [comment]
@qoqobolo there's a bug in the bug :)
the address should be "arb1" - eth:opt:arb:0xe8386a6e2657ae8d5c3a94e687e43e41d35f27bd
and it works correctly with that. Where did you find this address btw? because probably we need to correct that!

**Comment by pavloburykh** [comment]
Thank you @J-Son89! The address was most likely taken from Desktop app. They use wrong ```arb``` format. Looks like in mobile app the format is correct. Closing the issue.
