### ISSUE TITLE
"Testnet mode enabled" banner issues

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19506]
# Bug Report
followup https://github.com/status-im/status-mobile/pull/19348

## Problem 
[comment]: # (A problem description)

#### Expected behavior
Send button is present as designed
<img width="212" alt="Screenshot 2024-04-03 at 18 23 06" src="https://github.com/status-im/status-mobile/assets/147824399/3fe8dd14-bec9-4237-98ab-10e80f9d4430">

#### Actual behavior
<img width="210" alt="Screenshot 2024-04-03 at 18 21 39" src="https://github.com/status-im/status-mobile/assets/147824399/f53b9823-7092-4227-83ca-0427df414850">

### Reproduction

1. Install app
2. Make sure you have min 1 contact
3. Open chat with your contact
4. Try to send any message in this chat

### Additional Information

- Status version: PR https://github.com/status-im/status-mobile/pull/19348
- Operating System: iOS
- iPhone 13 17.3.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
@alwx thanks for assigning the issue! 
Please note that the issue also affected the following screens and buttons:

The `Join community` screen and the `Jump to` button (both iOS and Android)
<img width="407" alt="Screenshot 2024-04-04 at 12 32 33" src="https://github.com/status-im/status-mobile/assets/67952253/30e4c268-d06f-46ba-b695-e1c41873415f">

The slider in wallet when creating a new account (iOS only, probably only on small screen devices)
<img width="277" alt="Screenshot 2024-04-04 at 12 33 23" src="https://github.com/status-im/status-mobile/assets/67952253/7dd5b370-adc5-4227-8224-b4e5a26a4d3a">

**Comment by alwx** [comment]
@mariia-skrypnyk perfect, thank you for the information. The PR will hopefully be ready tomorrow.

**Comment by seanstrom** [comment]
Hey there 👋, just wanted to leave another example here of some issues with the testnet banner.

#### When Testnet mode is active some Legacy screens are clipped.

https://github.com/orgs/status-im/projects/125/assets/2845768/b35ecad8-29a7-4610-8c40-6ad6a8fd602f

**Comment by alwx** [comment]
Please don't take this issue unless you're very sure what you're doing :) The testnet banner is disabled by this PR: https://github.com/status-im/status-mobile/pull/19762
