### ISSUE TITLE
[Android] Account Page not displayed after sending collectible

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19519]
### Steps to Reproduce:
1. Go to the collectible send flow.
2. Confirm sending the collectible.

### Actual Result:
After confirming the sending of the collectible, the confirmation page is still shown.

https://github.com/status-im/status-mobile/assets/52490791/478cbc96-6933-4e0a-9b5b-6eb588fe31c8

### Expected Result:
User should be navigated to the Account Page after confirming the sending of the collectible.

### Device:
Pixel 7a, Android 13

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14849160/Status-debug-logs.1.zip)

**Comment by J-Son89** [comment]
@VolodLytvynenko - on the offisite we agreed to remove this page for now and instead the user should be directly redirected to the Account Page with the activity tab open. 
I think we can close this issue for now and instead we will have other issues to address this once activity tab is implemented properly.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - on the offisite we agreed to remove this page for now and instead the user should be directly redirected to the Account Page with the activity tab open. I think we can close this issue for now and instead we will have other issues to address this once activity tab is implemented properly.

Hi @J-Son89, got it. I agree with you. However, another issue still exists. I have slightly modified the description in the current one.

**Comment by J-Son89** [comment]
thanks @VolodLytvynenko!

**Comment by J-Son89** [comment]
@VolodLytvynenko - still relevant? 
I think I fixed this recently, right?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - still relevant? I think I fixed this recently, right?

@J-Son89 correct. Can be closed
