### ISSUE TITLE
Randomly appearing 1 ETH permission when joining community

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19524]
# Bug Report

## Problem 

We are facing a weird bug related to permissions in two communities on a particular user. It reproduces pretty randomly now, and we cannot yet find any pattern and specific steps, but I will outline below all the available information.

**Problem:** when opening a community, the user sees permission of `1 ETH`, although it is not set in the community.

This is currently only being reproduced on one user, in two communities, created on Desktop. Both communities have minted Owner and TokenMaster tokens.

**Community 1** is used in e2e, and the bug causes its failures:
https://status.app/c/G8EAAMTPn465VRV5AYerRC45llA_7aW55I_JEB7pccqBQ948wpZTO9D1eA-4KULgGAf_-mD5jCKmAPIZ9x0Ko1TSHL9Q4rP41U_GkwLbkBQ64RGBI4SiiMLoQEWkmDxEyZZDwboCSY64kZTbiQwuEaiiCGHi01OAkOySUFAkwCiBlSUfHeKh3wykMbqCAeXZZm4F0mVWX3XXx22-yw-bZmOaAQ==#zQ3shwQnEfMtcXpHXF4qJPyCGgw2F18N3nbGzYbzsVHnMq4yK

Its permissions:

<img width="1387" alt="Screenshot 2024-04-04 at 11 25 43" src="https://github.com/status-im/status-mobile/assets/67952253/1521dad4-c17a-4afe-b0cf-b41731389d59">

**Community 2** is just a test one:
https://status.app/c/G8EAAGTw5n4H-_Rt2OUokED-Eww92IADx1hjDsQXvxFosowg_1C23-553ac7j3Wq3K2a9r173W3a3651y0L54HQKoV5pQV8IkijM8phj1eE=#zQ3shNLkjAbuqkaFzHgB8R4E39LRgQBiiG65bA55qQmcANKev

Its permissions:

<img width="1376" alt="Screenshot 2024-04-04 at 11 26 06" src="https://github.com/status-im/status-mobile/assets/67952253/16aac2e0-186e-4fa6-b624-cdd16cc722cc">

**1 ETH permit was definitely added earlier in **Community 2**, but then removed. Perhaps it was previously added in **Community 1** as well, but unfortunately I'm not 100% sure.**

This is what it looks like for two real mobile users and the one used in e2e:

<img width="252" alt="Screenshot 2024-04-04 at 11 28 12" src="https://github.com/status-im/status-mobile/assets/67952253/320df7d5-dcc2-4383-85d4-ce10beda027d">

<img width="223" alt="Screenshot 2024-04-04 at 11 28 45" src="https://github.com/status-im/status-mobile/assets/67952253/91253621-fd71-4ffb-b83b-610f59a8538f">

Moreover, while in **Community 1** (`Status mobile QA community`) this permission appears _randomly_ in e2e, in **Community 2** (`test sepolia mainnet minted TG`) you always see it, although it's removed.

Same if you open it from Desktop:

<img width="716" alt="Screenshot 2024-04-04 at 11 42 38" src="https://github.com/status-im/status-mobile/assets/67952253/8d812176-8059-4911-81c9-2f63ce51887b">

As you can see, the 1 ETH permission is displayed, although it is not set in any community.

---

About the user: this is a very old test user, restored from the seed phrase on different devices many times.

Sepolia testnet is enabled everywhere. 

Failing e2e test: it failed for the first time in this PR on March 27: https://github.com/status-im/status-mobile/pull/19386

https://app.eu-central-1.saucelabs.com/tests/cfe4d0274dbb42648e9efa3c976d8c0c?auth=598a8a5dadf1c8885502566beda1d1f5#276

### Logs

[mobile user.log.zip](https://github.com/status-im/status-mobile/files/14864356/mobile.user.log.zip)
[Desktop Community admin logs.zip](https://github.com/status-im/status-mobile/files/14864367/Desktop.Community.admin.logs.zip)

### Additional Information

- Status mobile version: nightly 4/04
- Status desktop version: nightly 4/04 https://ci.status.im/job/status-desktop/job/nightly/273/
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
Haven't seen it for a while, please reopen if still relevant.
