### ISSUE TITLE
Jump to button is hidden on the Community screen because of Testnet mode banner

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19535]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
Design is [here](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=650-30484&mode=design&t=nV36Y2Zy73n1ML7Y-0). 
<img width="204" alt="Screenshot 2024-04-05 at 11 00 19" src="https://github.com/status-im/status-mobile/assets/147824399/0082a236-a594-415a-a07f-176adf57f661">

#### Actual behavior
<img width="213" alt="Screenshot 2024-04-05 at 11 01 58" src="https://github.com/status-im/status-mobile/assets/147824399/96fcf873-d09f-43c5-adfe-32eb9c955883">

### Reproduction

1. Install app
2. Go to Profile -> Advanced -> Turn Testnet mode on
3. Login to app (Testnet mode banner appeared)
4. Open any chat where is a link to any community you are not a Member
5. Tap on this link

### Additional Information

- Status version: nightly 5/04
- Operating System: Android, iOS
- Devices: iOS 13 (17.3.1) Samsung A34 (14.0)

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Thank you @mariia-skrypnyk for reporting the issue. Its already logged in https://github.com/status-im/status-mobile/issues/19493
