### ISSUE TITLE
Invalid malli schemas should fail the tests

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19538]
# Bug Report

## Problem 
[comment]: # (A problem description)

It seems like _invalid*_ schemas don't fail the tests but only show up as logs (see [issue](https://github.com/status-im/status-mobile/issues/19537)). 

_*invalid here means that the schema definition itself is not valid_
#### Expected behavior
invalid schemas fail the tests so they're easier to identify and fix

#### Actual behavior
invalid schemas only show up as logs during tests

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
@clauxx do you think this issue is still relevant? Do you have an example to demonstrate the case where the schema is not causing a test to fail?

**Comment by clauxx** [comment]
@ilmotta the tests are failing as they should when the schema is invalid. I guess something changed in the meantime. Will close this one 👍
