### ISSUE TITLE
Community data disappears when user taps cross icon or sends request on the Request to join screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19539]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
All data is stable and do not disappear and blink

#### Actual behavior
Community rules, community name, address to share disappears

https://github.com/status-im/status-mobile/assets/147824399/c7129e80-eb6a-4d3b-90bb-b519b6c78468

### Reproduction

1. Install app as User A
2. Add User B to contacts
3. As User B share community to User A
4. Tap on link to a shared community as User A
5. Tap on cross or send Request to join as User A

### Additional Information

- Status version: nightly 5/04
- Operating System: Android, iOS
- Devices: iOS 13 (17.3.1) Samsung A34 (14.0)

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
this looks like a small issue, i'd lean towards a won't fix (it's purely cosmetical and doesn't impact the user flow, if that's correct) would you agree?

**Comment by churik** [comment]
Designers might not agree, but I descope it for now if no objections @mariia-skrypnyk

**Comment by cammellos** [comment]
Thank you, closing for now then

**Comment by mariia-skrypnyk** [comment]
> Designers might not agree, but I descope it for now if no objections @mariia-skrypnyk

Yep, NP.
