### ISSUE TITLE
The network labels identifier depends on whether the token is supported on the current network on send assets page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19534]
### Steps:
1. Recover user with some assets on particular network (example: eth)
2. Go to "send assets" page
3. Check network label

### Actual result:
The network labels identifier depends on whether the token is supported on the current network.

The ETH in this case has all three labels because it is supported on both L1 and L2, regardless of whether the user has ETH on only one network
![image](https://github.com/status-im/status-mobile/assets/52490791/99db34e6-d479-461e-9d1e-b65a25d1302a)

### Expected result:
The network labels identifier should depend on whether the user owns the token.

discussed with design team https://discord.com/channels/624634427930312714/852533718790570015/1225517260685312041

**Comment by OmarBasem** [comment]
Needs confirmation from design team: https://discord.com/channels/624634427930312714/852533718790570015/1243490229713633280

**Comment by churik** [comment]
@shivekkhurana why this issue is added to 2.31, maybe I missed something or it was added by mistake?

**Comment by churik** [comment]
@clauxx does it make sense to work on it now before Send flow simplification?

**Comment by clauxx** [comment]
> [@clauxx](https://github.com/clauxx) does it make sense to work on it now before Send flow simplification?

it's a very small change tbh, so I don't think it should interfere too much
