### ISSUE TITLE
Other checkboxes are unselected when one checkbox is selected on the network preferences bottom sheet

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19543]
### Preconditions:
 The user has an account with one or more networks selected.

### Steps to Reproduce:
1. Open the eth account Edit flow
2. Open the network preferences.
3. Check any checkbox.

### Actual Result:
When a checkbox is selected, other checkboxes are automatically unchecked.

https://github.com/status-im/status-mobile/assets/52490791/e9b8fcb8-79a4-4063-9f97-58a80bc5de39

### Expected Result:
After a checkbox is checked, it should not influence the unchecking of other checkboxes.

### ENV:
Nightly 5 Apr 2024

**Comment by mmilad75** [comment]
@VolodLytvynenko One question. When only one network is selected, and user unchecks that selected one, what should happen? The current behavior is that in this situation, all of them will be selected

**Comment by Festival8** [comment]
> @VolodLytvynenko One question. When only one network is selected, and user unchecks that selected one, what should happen? The current behavior is that in this situation, all of them will be selected

Hi, @mmilad75 correct. If the last selected checkbox is unselected, then all should be shown as selected

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko One question. When only one network is selected, and user unchecks that selected one, what should happen? The current behavior is that in this situation, all of them will be selected

Hi, @mmilad75 correct. If the last selected checkbox is unselected, then all should be shown as selected

**Comment by VolodLytvynenko** [comment]
Invalid issue
