### ISSUE TITLE
Show the users that the keycard feature will be coming soon

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19547]
# Bug Report

## Problem 
During onboarding, when pressing on the keycard feature, we show the "not implemented" alert. We should either disable the button or let the user know that the feature will be coming soon. Best is to discuss with the design team (maybe there could be a generic solution to show "coming soon" functionality within the app).

#### Expected behavior
The keycard onboarding flow shows the "not implemented" alert

#### Actual behavior
The user can see that the feature will be coming soon

**Comment by flexsurfer** [comment]
Designers decided to just hide the button for now
