### ISSUE TITLE
UI freezes when creating a new wallet account on synced device if the second device is online / before the first relogin on a recovered profile

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19540]
# Bug Report

## Problem

In some cases, the UI freezes when creating a new wallet account on a synced device.

https://github.com/status-im/status-mobile/assets/67952253/eefe0ea3-fa5b-417c-9e8d-64402985d0ba

### Reproduction

1. Sync device1 and device2
2. Try to create a new wallet account on some of the devices while the second device is online

For me this issue is not always reproducible, sometimes I need to create several accounts to get frozen UI.

More likely it can be reproduced when adding W/O addresses, in which case the steps will be as follows:

1. Sync device1 and device2
2. Add a WO address on device1
3. Add a WO address on device2
4. Create a new account on device1 (UI freezes here)

Another way to reproduce:
1. Recover a profile which already has additional wallet accounts 
2. Try to create another account 

**Actual result:** right after recovering there is only account is shown until relogin 

#### Logs

[geth.log.zip](https://github.com/status-im/status-mobile/files/14883847/geth.log.zip)

### Additional Information

- Status version: nightly 5/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@qoqobolo - what priority do you think this is? It seems like low to me as it is quite the edge case all things considered? 🤔

**Comment by qoqobolo** [comment]
@J-Son89 this is definitely a low priority, especially considering the current goals for the next releases👍

**Comment by churik** [comment]
setting medium priority here, as it is common case to use status on both devices now.

**Comment by ulisesmac** [comment]
@qoqobolo It'd be great if you had and shared the `Status.log` file too.

**Comment by qoqobolo** [comment]
I cannot reproduce this issue anymore, so closing it for now.
Please, reopen if you face it again.
cc @ulisesmac
