### ISSUE TITLE
Fix loading screen for fetching community

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19555]
Dependent on designs for loading illustration for fetching the community.

# Bug Report
Remove the red square around fetching community when opening a newly shared community. Discuss with the design team or just make it somewhat presentable. Maybe add a button to cancel in case it takes too long or is stuck. Currently there seem to be no designs for this.

**Comment by ibrkhalil** [comment]
@Francesca-G Do you have designs ready for this state?

**Comment by clauxx** [comment]
I don't think there's designs for this, but we could remove the red box and add a button to cancel or go back for now. In case the illustrations are not ready, we can add them later on.

NOTE: We could also add the `cat-in-box` illustration to make it less jarring until the real illustrations are ready.

**Comment by Parveshdhull** [comment]
![image](https://github.com/status-im/status-mobile/assets/17097240/51bf9500-27b2-4dc7-8355-e1e454a21dba)

@seanstrom Please can you confirm if this issue is addressed?

**Comment by seanstrom** [comment]
Hey @Parveshdhull 👋
I don't think the issues has been addressed yet. I think we're waiting for some official designs / illustrations, but I think it's been discussed that we can make a temporary screen that looks better than the current red box with text. For example, we could re-use some assets from our other screens that have empty or pending states.

@clauxx did you start some of this already? I remember us looking at the different cat images 😸

**Comment by clauxx** [comment]
@seanstrom no I didn't. I guess any solution works for now, but most important is to get rid of the red square around the text. Would be nicer if it's pretty tho 🐱
