### ISSUE TITLE
Add unpairing devices that were synced before

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19552]
# Bug Report

## Problem 
[comment]: # (A problem description)
The user should be able to unpair previously synced devices. 

The feature should be available in the old UI, so it should be moved out of `legacy` 

#### Expected behavior
when pressing unpair on a device, it's unpaired

#### Actual behavior
when pressing unpair we get "not implemented"

### Reproduction

1. Login
2. Go to profile
3. Syncing
4. Sync with another device
5. Press Unpair on the synced device

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
Hey @clauxx!

Could you please expand on this, I am not sure I understand correctly:

> The feature should be available in the old UI, so it should be moved out of legacy

Does this mean we need to remove Syncing from Legacy settings or you mean something different? 

![photo_2024-04-24 15 19 51](https://github.com/status-im/status-mobile/assets/97245802/0dd58f57-fd23-4bfc-8a25-27099dca7cb2)

**Comment by clauxx** [comment]
Not exactly, although would be best to also remove Syncing from legacy. Here it's more about adding the "unpairing" functionality in the new settings, which was already available in the old settings.

**Comment by pavloburykh** [comment]
> Not exactly, although would be best to also remove Syncing from legacy. Here it's more about adding the "unpairing" functionality in the new settings, which was already available in the old settings.

oh, I've got you. Thank you for explanation.
