### ISSUE TITLE
Chore: setup feature-flag for not-implemented features

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19585]
### Summary
At the moment, we have several features that are not-implemented or unfinished. For the moment, we should create a feature-flag that allows us to hide these features until they're implemented.

#### Notes

* Perhaps we can use the name `show-not-implemented-features?` for the feature-flag.

**Comment by flexsurfer** [comment]
hey @seanstrom do we know where we want to still show these settings? like in PR builds for example? probably we want to keep them for e2e?

**Comment by seanstrom** [comment]
@flexsurfer I'm not sure when we need to show them, but I suppose they'll be useful in dev and perhaps CI.

@status-im/mobile-qa do E2E tests need to be aware of new feature flags?

**Comment by pavloburykh** [comment]
> @status-im/mobile-qa do E2E tests need to be aware of new feature flags?

@seanstrom as far as I understand new feature flags should not have impact on e2e. Based in the results https://github.com/status-im/status-mobile/pull/19591#issuecomment-2047152731 e2e are okay.
