### ISSUE TITLE
Wrong text is shown within share drawer when sharing own profile

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19597]
Follow up for https://github.com/status-im/status-mobile/pull/19559

### Steps:
1. Go to own profile
2. Tap 'share'

### Actual result:
'Connect with new share button' text is shown in the share device's system drawer
![image](https://github.com/status-im/status-mobile/assets/52490791/4ffc0af0-febc-49ba-9269-f1b36dad23be)

### Expected result:
"My profile on Status" text is shown
![image](https://github.com/status-im/status-mobile/assets/52490791/9716b00d-23a4-4351-835c-d6ae85ffcccd)

https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?type=design&node-id=3802-259522&mode=design&t=bER4ncK0x1ysPefS-0

### OS: 
- IOS

### Devices:
- iPhone 11 Pro Max, IOS 17

**Comment by ibrkhalil** [comment]
@VolodLytvynenko Unfortunately, To add custom text we'd have to lose the icon.
It's an issue of [react-native-share](https://github.com/react-native-share/react-native-share/issues/848) will pick up something else in the meantime.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko Unfortunately, To add custom text we'd have to lose the icon. It's an issue of [react-native-share](https://github.com/react-native-share/react-native-share/issues/848) will pick up something else in the meantime.

hi @ibrkhalil got it. thank you for clarification

**Comment by churik** [comment]
I believe might be closed then, thank you for clarifications
