### ISSUE TITLE
Validation error not displayed for Incorrect eth address in "Sent To" page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19599]
### Steps:
1. Open wallet
2. Go to 'send to' page 
3. Paste valid eth account address
4. Update  account address making it as invalid

### Actual result:
The "Confirm" button is shown as enabled, and an error is shown after tapping on it when an invalid ETH address is in the "sent to" input field.

https://github.com/status-im/status-mobile/assets/52490791/f6bb8611-217f-448d-97f2-a2fcd951cda3

### Expected result:
- Only in case of correct multichain or regular eth address entering/pasting the 'confirm' buttons should be enabled
- The validation "This is not valid Ethereum address" error message should be shown upon entering an invalid ETH address.

discussed with design team https://discord.com/channels/624634427930312714/1221764463732981790/1225799935065198693

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### Logs

**Comment by mmilad75** [comment]
BLOCKED: Designs are in progress and are not finished yet.

**Comment by VolodLytvynenko** [comment]
hi @mmilad75 design is ready https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=12971%3A163144&mode=dev
