### ISSUE TITLE
Universal QR scanner navigates to wallet when scanning unsupported addresses

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19607]
### Steps:
Scan the following addresses using the universal QR scanner:

QR with chain id
![image](https://github.com/status-im/status-mobile/assets/52490791/fdce7cf3-e134-4038-9386-5d498c545355)

QR with predefined assets
![image](https://github.com/status-im/status-mobile/assets/52490791/445fade4-513d-47a0-8cd7-1f81a3cd6c3e)

### Actual result:
Nothing happens. The scanner is just closed

https://github.com/status-im/status-mobile/assets/52490791/e752ddad-33d2-421b-92be-b050bfcf9e0e

### Expected result:
- In case of scanning non-supported eth address, the notification error should be shown https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8005-6029&mode=design&t=545G1nNN08lEaQc4-0
- Only multichain and regular addresses should be supported. Regular addresses can also be prefixed with "ethereum:" (screenshot of address with prefixed ethereum is below)
![image](https://github.com/status-im/status-mobile/assets/52490791/a78ff210-1a64-4147-97a5-99c4d4f64e95)

discussed with a design team https://discord.com/channels/624634427930312714/852533718790570015/1225795996555022478

### Nightly:
[11 Apr 2024]

**Comment by alwx** [comment]
@VolodLytvynenko hey! I just tried scanning "ethereum:0x8d2413447ff297d30bdc475f6d5c00254685aae@3" and got "Unsupported QR code". Isn't it the intended result?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko hey! I just tried scanning "ethereum:0x8d2413447ff297d30bdc475f6d5c00254685aae@3" and got "Unsupported QR code". Isn't it the intended result?

Hi @alwx . Interesting. This is the intended result. But it does not work so for me. I always navigated to the wallet page. 

Hope logs might help what's going on

https://github.com/status-im/status-mobile/assets/52490791/ce1dd3b0-cd1f-4b5d-9962-c1db04881287


### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs.zip](https://github.com/status-im/status-mobile/files/15023585/logs.zip)

**Comment by J-Son89** [comment]
@alwx - any update on this issue?

**Comment by VolodLytvynenko** [comment]
> @alwx - any update on this issue?

@J-Son89 I think we should close this issue. For now, a new specifications were discovered for the eth address https://github.com/status-im/status-mobile/issues/19986 validation which is still being discussed

**Comment by VolodLytvynenko** [comment]
asked design team https://discord.com/channels/624634427930312714/852533718790570015/1251237144115150859

**Comment by xAlisher** [comment]
Ready for development - https://github.com/status-im/status-mobile/issues/19986

**Comment by VolodLytvynenko** [comment]
can be closed
