### ISSUE TITLE
Clean up project from raster images

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1961]
[comment]: # (Please replace ... with your information. Remove < and >)

Most images have been moved to vector https://github.com/status-im/status-react/tree/develop/resources/icons

We need to clean up ios and Andorid (https://github.com/status-im/status-react/tree/develop/android/app/src/main/res) projects from raster images

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0xb0cd5f653f069f2ae81b779c744ba2edfc3f1136](https://etherscan.io/address/0xb0cd5f653f069f2ae81b779c744ba2edfc3f1136)
Network: Mainnet
Paid to: monokh
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by monokh** [comment]
Working on this :slightly_smiling_face: expect a PR soon

**Comment by churik** [comment]
Checked:
*install 
- all default avatars: 1-1 Chat, group Chat, Public Chat,
- icons on discover screen
- icons on contacts screen
- messaging in 1-1, Group chat
*upgrade
with 1-1 chat, group chat users with default profile picture and profile picture which is set from Gallery.
in IOS works correct, on android upgrade check is blocked by #2762
