### ISSUE TITLE
[UI Bug] Align chat avatar in the center

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#19615]
# Bug Report

## Problem 
[comment]: # (A problem description)
Followup of https://github.com/status-im/status-mobile/pull/19459

Issue: the Card shouldn't "cut" the channel avatar in the exact middle.
The avatar is 80px (blue rectangle) but the card meets the avatar at 44px (red rectangle), not at the exact middle:
![image](https://github.com/status-im/status-mobile/assets/33176106/f20e45a6-6602-412f-ab05-66e13cb3ac34)

The red guideline is where the card should stop.
As you can see here it looks like the card reaches the exact middle (40px instead of 44), so it looks shorter than design
![image](https://github.com/status-im/status-mobile/assets/33176106/6303c6a5-5f8d-4718-ae1a-f29955f788e3)

![image](https://github.com/status-im/status-mobile/assets/33176106/77b05639-6f27-435f-a86e-da37216d014f)

#### Expected behavior
Avatar should be centered at the top

#### Actual behavior
Avatar is not centered

### Reproduction

1. Open chat

**Comment by ilmotta** [comment]
I'm closing as "Not planned". As soon as the user scrolls we show the smaller avatar version, therefore the full size avatar is barely useful in real life. The complexities to handle a top header with custom animations is significant, and has been a common source of bugs.
