### ISSUE TITLE
App crashes after attempting to send assets with minimum value

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19610]
Unfortunately, there are no exact steps to reproduce this issue. in my case, the issue usually happens for the particular user after attempting to send WETH available on the L2 network

### Steps:
1. Recover the account with available assets (in my case it is always reproducible with WETH assets)
2. Go to 'send to' page
3. Enter a minimum value to send assets

### Actual result:
App crashes after attempting to send assets with minimum value

https://github.com/status-im/status-mobile/assets/52490791/8ad19cee-fd3a-493b-9702-1de627c63b11

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs:
Status app logs [logs (13).zip](https://github.com/status-im/status-mobile/files/14946472/logs.13.zip)
geth logs  [logs (2).txt](https://github.com/status-im/status-mobile/files/14946499/logs.2.txt)

**Comment by OmarBasem** [comment]
@VolodLytvynenko I tried to reproduce this issue with WETH but did not crash. Are you still able to reproduce the issue?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I tried to reproduce this issue with WETH but did not crash. Are you still able to reproduce the issue?

Hi @OmarBasem, unfortunately, I can't check it because I'm always facing the issue described in https://github.com/status-im/status-mobile/issues/19999, which might overlap with the current crash

**Comment by OmarBasem** [comment]
> > @VolodLytvynenko I tried to reproduce this issue with WETH but did not crash. Are you still able to reproduce the issue?
> 
> Hi @OmarBasem, unfortunately, I can't check it because I'm always facing the issue described in #19999, which might overlap with the current crash

Is that issue recent?

**Comment by VolodLytvynenko** [comment]
> > > @VolodLytvynenko I tried to reproduce this issue with WETH but did not crash. Are you still able to reproduce the issue?
> > 
> > 
> > Hi @OmarBasem, unfortunately, I can't check it because I'm always facing the issue described in #19999, which might overlap with the current crash
> 
> Is that issue recent?

@OmarBasem yes. Just yesterday encountered it

**Comment by briansztamfater** [comment]
I was able to reproduce this. Trying to figure out the cause, because I coudln't find anything in the logs or in debug terminal. I suspect this might be a status-go bug, but not sure, I'll continue debugging. Assigning this to myself and see if I can find something or fix it.

**Comment by briansztamfater** [comment]
@VolodLytvynenko Indeed, I tried the same on Status Desktop, and it crashed. So it is for sure a status-go bug.

Attaching error report: 
[reportstatusdesktop.txt](https://github.com/status-im/status-mobile/files/15348332/reportstatusdesktop.txt)

Please can you make this bug visible for the desktop team as well so they can propertly fix in on the status-go side?
