### ISSUE TITLE
Zero addresses are selected by default when joining a community

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19624]
**Steps:**

1. Open any community
2. Tap Request to join
3. Check how many addresses are selected for sharing

**Actual result:** 0 addresses are selected. Despite of it user is able to send community request and join a community.

https://github.com/status-im/status-mobile/assets/97245802/63d73c15-c06b-4e64-865e-88633b546fe7

**Expected result:** all addresses are selected by default. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
regression from https://github.com/status-im/status-mobile/pull/18989
сс @ibrkhalil
