### ISSUE TITLE
Chat is not unmuted after expected time if changing device time

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#19627]
# Bug Report

## Problem 
When a chat is muted for 1 hour and the device time is changed it's not being unmuted after the expected time

#### Expected behavior
The chat is unmuted

#### Actual behavior
It takes more than 61 min to unmute the chat

https://github.com/status-im/status-mobile/assets/29711298/6bc13f49-2575-47ae-8680-c4205173bd69

### Reproduction

1. Create a chat
2. Mute it for 1 hour
3. Change the device time (+61 minute)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
This task will require us to decrease the ticking interval on status-go to know when a chat should be unmuted, And we might have to use timezones to know if the time has been updated or not.
I think querying all chats/communities on a short interval might be expensive in terms of resource consumption.
CC: @cammellos @igor-sirotin

**Comment by cammellos** [comment]
@ibrkhalil it doesn't look right though, we should store dates in relative time in unix epochs (i.e unmute in x amounts of seconds) and it should not be tied to a particular timezone, maybe we can have a quick chat later

**Comment by ibrkhalil** [comment]
After discussing the currently implemented behavior of calculating mute time with @cammellos, We agreed that our app behaves correctly and shouldn't react to device time change.
Let's say you're traveling and you muted a chat for one hour, It doesn't make sense for the mute duration to change when we didn't ask for it to change.

**Comment by churik** [comment]
@yevh-berdnyk in this case we might exclude this particular check from tests
