### ISSUE TITLE
Profile - Settings category item animation

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#19621]
# Description

Related to #19299

- Opening animation [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#726065519)] of the category should be from right to left, not coming from the bottom

### Note
right to left animation is not applicable to old screens right now. it should be done once we redesign them

### Reproduction
Open Profile settings by pressing the user avatar at the top left corner of the screen

**Comment by ilmotta** [comment]
Closing as _not planned_ because animation work is currently descoped.
