### ISSUE TITLE
Title is shifted to the right in 'page top' of quo components preview

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19634]
### Problem:
When navigating to the quo components preview and opening 'page top', the titles related to 'page top' are shifted to the right, impacting pages such as 'add contacts' and 'add watch-only wallet', 'share address'.

### Steps:
1. Go to the quo components preview ->  combination -> open 'page top'

### Actual result:
The titles related to  'page top' are shifted to the right
![image](https://github.com/status-im/status-mobile/assets/52490791/bfb3a56f-e464-463b-9b71-eb6d0c4073fd)

impacted pages examples:
- add contacts:
![image](https://github.com/status-im/status-mobile/assets/52490791/33136036-bb37-4a38-97e0-af9caa990f62)

- add watch-only wallet
![image](https://github.com/status-im/status-mobile/assets/52490791/c610e46f-3709-4bec-b974-fb2264c58375)

### Expected result:
The titles should be properly aligned without any shifting.

![image](https://github.com/status-im/status-mobile/assets/52490791/60cca9f0-7cd3-4b0c-a660-992d3054cecc)

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by churik** [comment]
Not a priority afaik for 2.29

Descoping for now

**Comment by OmarBasem** [comment]
Issue is already fixed
