### ISSUE TITLE
UI in the upper section of the chat differs from the lower section when light mode is enabled

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19633]
### Steps:
1. Enable light mode
2. Go to any chat or channel

### Actual result:
The UI in the upper section of the chat differs from the lower section, with a visible line dividing them.

![image](https://github.com/status-im/status-mobile/assets/52490791/4a753bcc-d29e-4689-9645-30a4bc8037b7)

### Expected result:
The UI in the upper section should be consistent with the lower section, without any visible line dividing them.

### OS: 
IOS, Android

### Nightly:
[15 Apr 2024]

**Comment by Parveshdhull** [comment]
regression from https://github.com/status-im/status-mobile/pull/19459
cc @ibrkhalil
