### ISSUE TITLE
Increase time of Undo button to be shown when deleting a message

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#19644]
# Problem

One of the cases that we covered by automation in our e2e tests is deleting a message in a chat, undoing that action and checking that the message is restored. This test was stable for a long time, the functionality worked as expected but recently it started failing because of insufficient time for clicking Undo button. Actually we started facing this failure in and after #19270 merged. To have an ability to continue checking this important feature we need a little bit longer timeout for this button to be shown. It can be increased only in e2e apk leaving other builds as it is.

## Implementation

Increase time when the toast with Undo button is shown in e2e builds

## Acceptance Criteria

Undo button is shown and clickable for 8-10 sec

## Steps to test

1. Send a message in a chat
2. Delete the message
3. Check the time while Undo button is present

**Comment by Parveshdhull** [comment]
curious how its related to https://github.com/status-im/status-mobile/pull/19270, @flexsurfer ?

**Comment by Parveshdhull** [comment]
probably related to `requestAnimationFrame(fn)`

**Comment by Parveshdhull** [comment]
So there are two ways to implement this
- Find out why it don't work after #19270
- Or just bump timer to 8000 ms for e2e builds

**Comment by flexsurfer** [comment]
i'll take a look thanks

**Comment by flexsurfer** [comment]
> So there are two ways to implement this
> 
> * Find out why it don't work after [migrate reagent part6 #19270](https://github.com/status-im/status-mobile/pull/19270)
> * Or just bump timer to 8000 ms for e2e builds

probably it was slower before, and now it works as designed, exactly 4 seconds, but I'm wondering why we can't fix e2e test, because for mute chat it works fine? cc @yevh-berdnyk

**Comment by yevh-berdnyk** [comment]
> > So there are two ways to implement this
> 
> > 
> 
> > * Find out why it don't work after [migrate reagent part6 #19270](https://github.com/status-im/status-mobile/pull/19270)
> 
> > * Or just bump timer to 8000 ms for e2e builds
> 
> 
> 
> probably it was slower before, and now it works as designed, exactly 4 seconds, but I'm wondering why we can't fix e2e test, because for mute chat it works fine? cc @yevh-berdnyk 

For our e2e we use Appium and running in SauceLabs which is not so fast. It's just not enough time in this case to find the element and click on it having only 4 seconds. That's why we can't make this test stable
