### ISSUE TITLE
Token gated channels are locked for Admins/Token masters

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19641]
**Steps:** 

1. By mobile user join as Admin or Token Master the community which has token gated channels
2. See if mobile user can accesss token gated channels

**Expected result:** Admins/Token Masters should be able to access token gated channels

**Actual result:** cannot access token gated channels. 

[Status-debug-logs - 2024-04-15T170023.031.zip](https://github.com/status-im/status-mobile/files/14980044/Status-debug-logs.-.2024-04-15T170023.031.zip)

https://github.com/status-im/status-mobile/assets/97245802/9e428d68-8622-403c-bcf8-34efda90f97e

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
Whoever works on this, please timebox the investigation to 4/5 hours to start with

**Comment by flexsurfer** [comment]
it seems like it's a known issue, the members list is empty for tg channel, there are no keys to decrypt it, but after some time ~10-20min it works as expected sometimes, so it can't be fixed on mobile side, and desktop team is aware of this problem

**Comment by pavloburykh** [comment]
Based on investigation conducted with @flexsurfer it turned out channels become unlocked after some time. Sometimes it is 30 minutes, sometimes several hours. Closing this issue. Thank you for investigation @flexsurfer.
