### ISSUE TITLE
USDC assets not available for sending

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19646]
### Steps:
1. Restore user with USDC (in my case USDC is available on Optimism and on Arbitrium)
2. Select USDC as asset for sending
3. Go to the send page

### Actual result:
The value is not available for sending.

![image](https://github.com/status-im/status-mobile/assets/52490791/b0de5468-633b-4d6d-9095-64c6526cd073)

https://github.com/status-im/status-mobile/assets/52490791/01bf9ec7-f49e-41cd-90b6-0860efee4df1

### Expected result:
The value is available for sending

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Additional info:
- Current USDC is available in my case on two networks, on Optimism 1.28 and on arbitrium 1.27, you can check it in Watch-only `0xed620c9dc11401b63b35dfe8e93f2b11db0f6f9e`
- Feel free to reach out to me directly if you need a user with collectibles. I will provide the seed phrase

**Comment by churik** [comment]
I guess it might be not available because of the route problem; basically currently I cannot find any route for L2 networks - it might be the cause of the issue

**Comment by VolodLytvynenko** [comment]
> I guess it might be not available because of the route problem; basically currently I cannot find any route for L2 networks - it might be the cause of the issue

@churik routes are successfully found for me. I can send assets such as eth using l2 mainnet networks using mobile. Here are today's transactions:
https://arbiscan.io/address/0xed620c9dc11401b63b35dfe8e93f2b11db0f6f9e
https://optimistic.etherscan.io/address/0xed620c9dc11401b63b35dfe8e93f2b11db0f6f9e
