### ISSUE TITLE
Implement navigation to profiles and chats from contact requests inside Activity Center

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19649]
### Summary

* When someone opens the activity center, and views their contact requests, then pressing on the contact tag should open a profile and/or a 1-1 chat?
  * At the moment:
    * an accepted contact request will navigate to 1-1 chat when the contact tag is pressed
    * a pending contact request will not navigate anywhere when the contact tag is pressed
    * a declined contact request will not navigate anywhere when the contact tag is pressed
    * a contact acceptance notification will not navigate anywhere when the contact is pressed
  * Ideally:
    * an accepted contact request will navigate to 1-1 chat when the contact tag is pressed
    * a pending contact request will navigate to the contact profile contact tag is pressed
    * a declined contact request will navigate to the contact profile when the contact tag is pressed
    * a contact acceptance notification will navigate to the contact profile when the contact is pressed

### Example

https://github.com/status-im/status-mobile/assets/2845768/416cfe94-e494-4a5e-bdf3-cc8057bfd553

**Comment by flexsurfer** [comment]
hey @seanstrom just wondering if it's by design? when the request is accepted the entire log item is clickable not the contact item, so it's not possible to do it when it's not accepted because there are active buttons inside

**Comment by seanstrom** [comment]
@flexsurfer sorry for the delay 🙏 
I had asked design about the the behaviour and we had discussed that it would be ideal for the user to be able to navigate to the contact profile of a pending contact request and a declined contact request.

I suppose if we want we can use the entire the contact request notification as the press-area for navigating, and we can still have the buttons for accepting and dismissing (ignore) a contact request. Thoughts?
