### ISSUE TITLE
Error on long tap on token-gated channel from the join community screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#19648]
# Bug Report

## Problem 
On a long tap on the community channel we got an error:

https://github.com/status-im/status-mobile/assets/4557972/f3543dab-ea3e-421f-ad0b-d7c70f3d5080

Very recent regression.

### Reproduction

1. Share the community with token-gated channel (i.e. https://status.app/c/ixGACiIKCmNvbW1fc250XzESCWRmZGZkZmdmZxgBIgcjNDM2MERGAw==#zQ3shuBEA9NraTd6Aw8YqWquRbcECAFhhrcSKDeQpktEePJET ) 
2. Navigate the community link -> try to long tap the token-gated community

### Additional Information

- Status version: nightly 15/04.24
- Operating System: Android, iOS

[status_logs.zip](https://github.com/status-im/status-mobile/files/14980863/status_logs.zip)

**Comment by Parveshdhull** [comment]
regression from https://github.com/status-im/status-mobile/pull/19529
