### ISSUE TITLE
Decorate browser as "under construction"

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#19656]
Dependent on designs for "under construction" illustration

### Summary

At the moment, the status-mobile browser is still being implemented. For the moment, we should show the browser feature as being "under construction".

Ideally, we would keep the browser icon in the app navigation but on-press the button will display an "under construction" illustration. Also, there should be a setting for turning on the browser feature, and that setting should be somewhere inside the advanced user settings. When a user enables that setting, the browser button should navigate to the browser screen.

**Comment by ilmotta** [comment]
Closing as _not planned_ because the browser feature is currently not implemented and descoped.
