### ISSUE TITLE
Several DApps (Auction House, Flight Delays, Etherplay) consider app not connected to the network

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1965]
### Description

*Type*: Bug

*Summary*: 
1. web3.version.network in Console returns ```{:message "The method net_version does not exist/is not available", :name "Error"}'```
2. If open several DApps (Auction House, flight Delays Sucks..) they do not show network, address and balance as expected. Instead they consider app not in the network:
![img_2342](https://user-images.githubusercontent.com/6584810/31018141-a8930764-a533-11e7-8d72-a3ba23f5145b.jpg)

if open DApps then they do not consider app to be in the network:
![screenshot_20170929-162617](https://user-images.githubusercontent.com/6584810/31018103-89189f52-a533-11e7-8885-19145d3a757f.png)

![screenshot_20170929-160534](https://user-images.githubusercontent.com/6584810/31018094-8232122c-a533-11e7-9df0-c99eb445377b.png)

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/6666962/sessions/14/?accessToken=o-TMypG45nORtb4ZbH9OitEePwM
- Open Status
- Open Contact
- Open Auction house, scroll to the bottom to see "Ethereum Status" section, it's red now, expected to get info about address, balance and network
- Open Flight Delays Sucks DApp - it also says "Not connected to the network" instead of expected address, balance and network

### Additional Information
* Status version: release candidate 0.9.11    0.9.10-118-g3b5e39eb+
* Operating System: 
Real device iPhone 7 plus, iOs 10.3.2
Real device Google Pixel XL, Android 8.0

**Comment by divan** [comment]
Should be fixed in https://github.com/status-im/status-go/pull/377

**Comment by annadanchenko** [comment]
tested ok on release 0.9.11 build 0.9.11d120
