### ISSUE TITLE
The routes are not found when entered data is changed

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19650]
Follow up for https://github.com/status-im/status-mobile/pull/19392

### Steps:
1. Recover the user with assets on at least 2 networks.
2. Enter a value available for 2 networks (e.g., 0.01 ETH on Mainnet and 0.01 ETH on Optimism, enter 0.01 ETH).
3. Disable the Mainnet network.
4. Clear the value in the input field and enter a new value (e.g., 0.2 ETH).

### Actual result:
The route searching is not performed

https://github.com/status-im/status-mobile/assets/52490791/bcf7abb3-79d6-42b2-9023-97e590043874

### Expected result:
Potential solutions:
- All routes should be found again, even if a route was disabled in a previous attempt, because a new entered value should trigger new route searching.
- Disabled routes should be shown as disabled, informing the user that they entered an available amount, but the route for the disabled network is not accessible.

**Comment by mariia-skrypnyk** [comment]
Also observe such issue when I change amount and see blink.
It is visible on my video: 

https://github.com/status-im/status-mobile/assets/147824399/ae380219-e42f-4da0-b8ca-f1eb13730fe3

Hope it will help to fix this issue.

**Comment by OmarBasem** [comment]
@VolodLytvynenko are you still able to reproduce this bug?

**Comment by OmarBasem** [comment]
@mariia-skrypnyk are you still able to reproduce the blink bug you mentioned?

**Comment by OmarBasem** [comment]
@VolodLytvynenko @mariia-skrypnyk I think this issue can be closed?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko @mariia-skrypnyk I think this issue can be closed?

hi @OmarBasem agree with you. Thanx
