### ISSUE TITLE
Channel fetching screen issues 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19659]
Channel screen which appears in fetching state looks broken

**Steps:** 

1. Open any community which has not been opened/fetched on this account before
2. Open any channel while data is being fetched
3. Observe the result

**Expected result:** I have not found corresponding designs. Please, contact design team. 

**Actual result:** 

### ISSUE 3 'Add <no value> as contact to send a message' is displayed in footer

![photo_2024-04-16 12 59 39](https://github.com/status-im/status-mobile/assets/97245802/601368f0-04da-4aae-bdc5-7ba2eb36d832)

### ISSUE 4 Channel avatars are missing on community overview screen

![photo_2024-04-16 12 59 43](https://github.com/status-im/status-mobile/assets/97245802/17db7bc6-18a8-43c2-a41e-ec523922fdef)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
I think this behavior is because we don't have chat item fetched yet in :chats.
But probably we can fix few bugs by just accessing required info from :communities :thinking:
