### ISSUE TITLE
Incorrect margin in the header on the collectible details screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19658]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/67952253/236fb4c9-1798-4603-bf1d-762ba21ea966

### Reproduction

1. Open Wallet
2. Open collectibles
3. Open some collectible to see details

### Additional Information

- Status version: nightly 16/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ulisesmac** [comment]
This one should have been fixed in:

- https://github.com/status-im/status-mobile/pull/20024

Here's a video attached to the PR:

https://github.com/status-im/status-mobile/assets/19279756/32a69324-dc7f-45bc-b5e4-cc9201889a2e
