### ISSUE TITLE
Channel header is broken when opening channel with chat history after joining the community

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19671]
Example of community https://status.app/c/iw6AChwKCE5ldyBjb21tEgVkYXNzZBgXIgcjNDM2MERGAw==#zQ3shibjPWsBFi527PL5hyBWVq9tWjuXdSXwBscTKgEEx3YwM

Steps: 

1. Join given community
2. Wait a little bit before community is fully fetched (5-10 seconds)
3. Open general channel
4. Pay attention at header

**Actual result:** Header is broken. Message history is overlapping status bar. 

![photo_2024-04-16 16 19 37](https://github.com/status-im/status-mobile/assets/97245802/9838f30c-de08-436f-9839-9d6facfc544f)

https://github.com/status-im/status-mobile/assets/97245802/765cd920-eb47-44e5-8802-3895abf21cb0

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
probable regression from https://github.com/status-im/status-mobile/pull/19459

**Comment by pavloburykh** [comment]
> probable regression from #19459

cc @ibrkhalil

**Comment by Parveshdhull** [comment]
fixed in https://github.com/status-im/status-mobile/pull/19677
