### ISSUE TITLE
No information about absent route

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#19676]
# Bug Report

## Problem 
When I try to to optimism address and don't have any assets on optimism itself, no meaningful message displayed.

![Simulator Screenshot - iPhone 13 - 2024-04-16 at 16 24 05](https://github.com/status-im/status-mobile/assets/5786310/f60683c4-2e09-4427-8f00-7757e9c283c3)

#### Expected behavior
Some message displayed. Designs TBD

#### Actual behavior
Nothing displayed

### Reproduction

1. Go to wallet account with no optimism funds
2. Start sending assets to address `opt:0x000000000000000000000000000000000000dEaD`
3. Select eth to send and input amount
4. Wait)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vkjr** [comment]
@J-Son89, @churik fyi.

**Comment by vkjr** [comment]
@briansztamfater, cc.

**Comment by briansztamfater** [comment]
Not relevant anymore IMO cc @vkjr
