### ISSUE TITLE
Discover DApps preview

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1968]
### User Story

As a user I want to be able to discover interesting dapps to interact with.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: A section in new Discover screen should show a carousel with all (currently hardcoded dapps). 

When user taps on any dapp icon, they should be redirected to a dapp detail screen.
When user taps on `All`, they should be redirected to all dapps list screen.

https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59ca26fd3db52a686d640e98

This issue is a sub-task of this one: #1874

**Comment by oskarth** [comment]
![image](https://user-images.githubusercontent.com/1552237/31093653-ad4d22fe-a7b2-11e7-84f1-3636beb07ca6.png)

carousel part (middle)

**Comment by oskarth** [comment]
Done in develop, pixel perfect in separate issue
