### ISSUE TITLE
Discover Public chats teaser

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1969]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see how public chats discovery will look like when it is added to the app.
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: A section in new Discover screen should show a grayed out widget with hardcoded samples of discovered public chats.

https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59ca26fd3db52a686d640e98

This issue is a sub-task of this one: #1874

**Comment by oskarth** [comment]
Looks like the bottom part of main screen:
![image](https://user-images.githubusercontent.com/1552237/31093684-d102a1d8-a7b2-11e7-8778-591b73b12fd5.png)
