### ISSUE TITLE
Shadow broken on share channel screen

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#19699]
# Bug Report
![image](https://github.com/status-im/status-mobile/assets/33176106/f10038fc-dcb0-452d-8c89-767c5d82594e)

## Problem 
Shadow shown behind QR code is not aligning correctly and should be adjusted 

#### Expected behavior
https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=2345-299699&mode=design&t=yHja9BSSrw1ojVK7-4

#### Actual behavior
Shown in Bug report

**Comment by churik** [comment]
![IMAGE 2024-06-21 17:47:16](https://github.com/status-im/status-mobile/assets/4557972/e11bc27b-d823-4bab-980c-9363770aff51)
Not reproducible anymore on nightly 21/06/24
