### ISSUE TITLE
The routes are not found on Mainnet/Testnet Arbitrium network

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19703]
Unfortunately, the issue does not occurs consistently, and there are no exact steps to reproduce it. It seems to happen randomly. I hope the logs might help

### Steps:
1. Disable testnet
2. Go to send assets page
3. Enter available Arbitrium assets
4. Enable only Arbitrium network

### Actual result:
The Mainnet Arbitrium is not found

https://github.com/status-im/status-mobile/assets/52490791/e24edfe3-036d-4a04-9c27-5161949b4ea0

### Expected result:
The Mainnet Arbitrium is found

### ADDITIONAL INFO:
Same is on desktop side

### OS: 
IOS, Android

### Devices:
- Desktop Nightly. Status go 0.179.2
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
desktop logs [logs.txt](https://github.com/status-im/status-mobile/files/15021411/logs.txt)
Mobile logs  [Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/15021483/Status-debug-logs.2.zip)

**Comment by churik** [comment]
I believe this one and other routing issues should be fixed in scope a bit later, reference https://github.com/status-im/status-desktop/issues/14569

Removed from milestone for now

**Comment by churik** [comment]
closing for now, seems not possible to reproduce now
