### ISSUE TITLE
Jenkins - Deploy to iOS fails silently if upload is unsuccessful

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1970]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer I want to have successful builds and when they do fail I want them marked as such.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Upload to diawi fails, but script proceeds all green and posts a link like this: `https://i.diawi.com/null`

http://185.90.37.243:8080/blue/organizations/jenkins/Github%20Org%20Builder%2Fstatus-react/detail/feature%2Fdiscover-facelifting-%231874/1/pipeline/58

**Comment by oskarth** [comment]
@goranjovic do you know if this is still an issue?

**Comment by chadyj** [comment]
Fastlane handles Diawi uploads and logic now. Should be fixed.
