### ISSUE TITLE
Channel links are not fetched in web browsers

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19713]
Could it be regression of https://github.com/status-im/status-mobile/pull/19566 cc @Parveshdhull ?

Example of channel link https://status.app/cc/G4IAAOT-57YN0bREwtPcEo_oId19Qb2R0IgkUxXXp_kXm1WyhbPuyDUKD_oAOqyNPDewJlOlaHZn7NNfs-vluIP-5frcnXaPU59cTqfXeff8yW36APoACpuOJCwJUs0Z-8jjyHW4TgixdY87oQ4-d3XP9YIgxChETgE=#zQ3shbLK4hDRnJh6oHvssoAbWeEPA7Hca34ZMt7P5ez3EZRub

**Steps:** 

1. Open channel link in web browser
2. See if web page is loaded

**Actual result:** Couldn't fetch the link

<img width="1390" alt="Status - Make the jump to web3 2024-04-18 16-37-32" src="https://github.com/status-im/status-mobile/assets/97245802/1b883640-bb39-4567-b81d-0fb55262eb2c">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
hi @pavloburykh, Thank you very much for reporting the issue.

Even the links shared in https://github.com/status-im/status-mobile/pull/19566#issuecomment-2058945882 are not working. I don't think its related to mobile, its probably website issue.

**Comment by Parveshdhull** [comment]
might be related to https://github.com/status-im/status-web/pull/544

**Comment by Parveshdhull** [comment]
@felicio please can you check if this issue is related to https://github.com/status-im/status-website/pull/934 or https://github.com/status-im/status-web/pull/544

**Comment by felicio** [comment]
I've just merged the fix. Thanks for letting me know and apologies for not catching it earlier.

**Comment by pavloburykh** [comment]
> I've just merged the fix. Thanks for letting me know and apologies for not catching it earlier.

@Parveshdhull @felicio thank you guys. Issue is fixed. Closing the ticket.
