### ISSUE TITLE
status bar is black in a dark theme

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#19720]
Devices: iOS 13 (17.3.1) Samsung A34 (14.0)

Steps:

- Login to app
- Go to Profile-> Appearance
- Change theme to dark
- Return to Messages or Community screens

Actual result:

![image](https://github.com/status-im/status-mobile/assets/11790366/5eb8d6eb-6a89-41b9-a079-fe50f9b313f4)

**Comment by Parveshdhull** [comment]
hi @pavloburykh about [Issue 1](https://github.com/status-im/status-mobile/pull/19735#issuecomment-2072579930) in https://github.com/status-im/status-mobile/pull/19735 and this issue with the status bar, is this only occurs on theme change after login?

If yes, is the status bar color gets fixed after pressing the bottom tab?

**Comment by Parveshdhull** [comment]
If this only happens after changing theme, this issue might not be fixable. Please check Known Issues -> Android, in https://github.com/status-im/status-mobile/pull/19089 for more details
