### ISSUE TITLE
Discover Dapps - show all screen

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1972]
### User Story

As a user I want to be able to discover interesting dapps to interact with.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: A screen where all discoverable dapps are shown. The list is hardcoded in this iteration and it is the same as in the contacts.

When user taps on any dapp icon, they should be redirected to a dapp detail screen.
When user taps on `Back`, they should be redirected to main Discover screen.

https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59ca26fd3db52a686d640e98

This issue is a sub-task of this one: #1874

**Comment by oskarth** [comment]
@goranjovic To clarify, is this the DApps list screen in Zeplin? 
![image](https://user-images.githubusercontent.com/1552237/31093424-0315aab8-a7b2-11e7-9436-b7c9791ff51f.png)

**Comment by denis-sharypin** [comment]
@oskarth yes

**Comment by oskarth** [comment]
Just for my own reference

![image](https://user-images.githubusercontent.com/1552237/31220049-7bce5c98-a9bf-11e7-8e47-7870b806b1a8.png)

**Comment by oskarth** [comment]
Known issue in current implementation. Some of these belong in carousel issue but taking them from merged PR so it is saved.

- All dapps list not straight columns and rows
- Icon size and badge (scratch badge, looks like on purpose)
- Carousel (just WIP, not main issue here) show more dapps at a time
- Uppercase headline for all dapps
- QA: the daps are not clickable neither in carousel nor in ALL view and not all the dapps are present in the ALL list. It will be done in future tickets

**Comment by oskarth** [comment]
Closing in favor of more targeted issues. Main deliverables done, functionally hooked up. Pixel perfection will done in other issues. Main acceptance criteria missing is "click to go to details". This is easier done after details screen. Capured here:

https://github.com/status-im/status-react/issues/2042
https://github.com/status-im/status-react/issues/2041

**Comment by oskarth** [comment]
Closing for real, main issue solved in develop.
