### ISSUE TITLE
Reagent atom from theme regression

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19729]
Could it be regression of https://github.com/status-im/status-mobile/pull/19706 ?  cc @flexsurfer 
Let me know if some of the issues are not regression of https://github.com/status-im/status-mobile/pull/19706 , I will log separately.

### ISSUE 1 Wrong font colour on recovery phrase screen

**Steps:** 

1. Open recovery phrase screen
2. Start typing seed phrase
3. Pay attention at font colour

**Expected result:** font colour should be white

**Actual result:** font colour is black

![photo_2024-04-19 14 17 44](https://github.com/status-im/status-mobile/assets/97245802/add931eb-13fe-4cde-a1b0-7c4ac17eed13)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### ISSUE 2 Wrong font colour of amount value

**Steps:** 

1. Open asset amount screen
2. Start typing some decimal value, i.e 0.001 
3. Pay attention at value font colour

**Actual result:** colour is white

https://github.com/status-im/status-mobile/assets/97245802/cef5a215-b2eb-4331-a016-7c716b37873d

**Comment by pavloburykh** [comment]
### ISSUE 3 Black skeleton when opening wallet screen

**Steps:**

1. Open Wallet tab
2. Pay attention at skeleton colour on top left

**Actual result:** skeleton is black

![photo_2024-04-19 14 41 43](https://github.com/status-im/status-mobile/assets/97245802/c8894aa8-c56b-4688-811c-bf8614ff4e7e)

**Comment by flexsurfer** [comment]
yes ,thank you @pavloburykh will fix asap

**Comment by qoqobolo** [comment]
### ISSUE 4: Black line on the emoji page in wallet (edit account flow)

<img width="322" alt="Screenshot 2024-04-19 at 14 25 15" src="https://github.com/status-im/status-mobile/assets/67952253/b721e6fd-f916-4710-8d35-1c3f07ef93a3">

### ISSUE 5: Black line between two L2 networks

<img width="323" alt="Screenshot 2024-04-19 at 14 25 47" src="https://github.com/status-im/status-mobile/assets/67952253/cd1bd77a-2086-48b9-a625-84db6a8bc434">

**Comment by flexsurfer** [comment]
ISSUE 6 : black stripe on legacy Settings screens
![image](https://github.com/status-im/status-mobile/assets/11790366/7fa9e798-1e48-4216-a226-a39a51906d4f)

**Comment by flexsurfer** [comment]
- [x] ISSUE 1 Wrong font colour on recovery phrase screen
- [x] ISSUE 2 Wrong font colour of amount value
- [x] ISSUE 3 Black skeleton when opening wallet screen
- [x] ISSUE 4: Black line on the emoji page in wallet (edit account flow)
- [x] ISSUE 5: Black line between two L2 networks
- [x] ISSUE 6 : black stripe on legacy Settings screens

**Comment by qoqobolo** [comment]
### ISSUE 7: Add wallet account screen

<img width="316" alt="Screenshot 2024-04-19 at 15 20 47" src="https://github.com/status-im/status-mobile/assets/67952253/5277314f-ab3a-4895-9a2c-413cd5c044ce">

**Comment by qoqobolo** [comment]
### ISSUE 8: Toasts on the wallet screen should be dark when the light theme enabled

Steps:
1. Open an account
2. Edit smth, e.g. select a new emoji

<img width="420" alt="Screenshot 2024-04-19 at 15 21 22" src="https://github.com/status-im/status-mobile/assets/67952253/41d600c3-e11c-4788-90ee-f12798b329c9">

**Comment by qoqobolo** [comment]
### ISSUE 9: Buttons on the `Buy token` bottom sheet

<img width="323" alt="Screenshot 2024-04-19 at 15 22 58" src="https://github.com/status-im/status-mobile/assets/67952253/30ae3414-4eaf-4419-bb3a-be77635841c4">

**Comment by qoqobolo** [comment]
### ISSUE 10: Request to join a community

<img width="350" alt="Screenshot 2024-04-19 at 15 24 07" src="https://github.com/status-im/status-mobile/assets/67952253/a29eaa8a-1ca5-4ab3-a7e0-520f7e1807d9">

**Comment by qoqobolo** [comment]
### ISSUE 11: Invite to community screen

<img width="345" alt="Screenshot 2024-04-19 at 15 24 52" src="https://github.com/status-im/status-mobile/assets/67952253/39dd1036-b04e-47b0-82f2-bc7426e89c31">

**Comment by flexsurfer** [comment]
- [x] ISSUE 7: Add wallet account screen
- [x] ISSUE 8: Toasts on the wallet screen should be dark when the light theme enabled
- [x] ISSUE 9: Buttons on the Buy token bottom sheet
- [x] ISSUE 10: Request to join a community
- [x] ISSUE 11: Invite to community screen

**Comment by qoqobolo** [comment]
### ISSUE 12: When you enter the amount when sending a transaction the numbers are white

<img width="322" alt="Screenshot 2024-04-19 at 15 28 41" src="https://github.com/status-im/status-mobile/assets/67952253/92dbd1ea-2dd7-4cbc-b782-2244932ff11b">

**Comment by qoqobolo** [comment]
> * [ ]  ISSUE 12: When you enter the amount when sending a transaction the numbers are white

Sorry @flexsurfer , I removed the comment, it's the same as ISSUE 2. You can ignore it

**Comment by pavloburykh** [comment]
### ISSUE 12 Black circle around community avatar

![photo_2024-04-19 17 28 41](https://github.com/status-im/status-mobile/assets/97245802/56dc26e9-9a9c-4a63-a3d1-9ec3abcda328)

**Comment by flexsurfer** [comment]
- [x] ISSUE 12 Black circle around community avatar

**Comment by pavloburykh** [comment]
> * [ ] [ ISSUE 12](https://github.com/status-im/status-mobile/issues/19729#issuecomment-2066705355) Black circle around community avatar

Hey @flexsurfer! What about this issue? Still reproducing it in https://github.com/status-im/status-mobile/pull/19735. Should I log it separately?
