### ISSUE TITLE
📜 Show a list of saved addresses and details

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#19727]
# Feature Issue

### User Stories

👀 As a user,
I want to see a list of all addresses I have saved

### Acceptance Criteria

| Screen | Description | Acceptance Criteria |
|--------|--------|--------|
| ![image](https://github.com/status-im/status-mobile/assets/1925158/1dddbdb0-6e53-4aac-a11d-2a35e2532297) | List to show all saved addresses, grouped by first letter of the Name | 1. There should be a header<br/>2. The back button should take back to "Wallet Setttings" Screen<br/>3. Clicking on an address should open the address options in the bottom sheet (covered in separate issue https://github.com/status-im/status-mobile/issues/19728)  <br/>4. The "Plus" button is **not** supposed to work in this issue |
| ![image](https://github.com/status-im/status-mobile/assets/1925158/fa0a5fc6-6470-4cde-83c0-adac635ee097) | Filter where no address is found | 1. If no address found, this illustration should be rendered | 

### Notes
Figma flow: https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=74%3A33979&t=LgB4MQG7Gp4rue7y-1

**Comment by ibrkhalil** [comment]
After discussing this issue with @churik
We agreed that it's better to descope the searching feature of this issue for now.
