### ISSUE TITLE
Discover - DApp details screen

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1973]
### User Story

As a user I want to be able to discover interesting dapps to interact with.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: A screen where details about a dapp reached via discover are shown.

When user taps on Open icon, the chat should start with the dapp (or browse?)
When user taps on `Back`, they should be redirected to main Discover screen or all Dapps screen (depending on navigation path)

https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59ca26fd3db52a686d640e98

This issue is a sub-task of this one: #1874

**Comment by oskarth** [comment]
![image](https://user-images.githubusercontent.com/1552237/31093617-928eda48-a7b2-11e7-9efd-e30147b3d0c0.png)
