### ISSUE TITLE
Store nodes are not available on IOS

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19736]
Regression of https://github.com/status-im/status-mobile/pull/19564 cc @siddarthkay 
Tested on IOS 16.7.7, iPhone 10

**Steps:**

1. Login Status on IOS
2. Check if store node is found

**Actual result:** Store nodes are not found on IOS. Unable to fetch communities / restore data, etc. 

[logs (33).zip](https://github.com/status-im/status-mobile/files/15040940/logs.33.zip)
![photo_2024-04-19 16 20 46](https://github.com/status-im/status-mobile/assets/97245802/9b7ef72b-bed6-4f27-8974-a33143f9bab9)

**Comment by siddarthkay** [comment]
@pavloburykh : does this happen only on iOS? Could you pls check if this happens on Android too?

**Comment by siddarthkay** [comment]
As discussed @jo-mut will take this over

**Comment by pavloburykh** [comment]
> @pavloburykh : does this happen only on iOS? Could you pls check if this happens on Android too?

I am not reproducing on Android, that's why I mentioned in the issue that this is IOS only.

**Comment by pavloburykh** [comment]
@jo-mut @siddarthkay hey guys! Curious if there are any updates on this? It kinda blocks us from testing some features (which require connection to store node) on IOS. Maybe we should think about reverting [changes](https://github.com/status-im/status-mobile/pull/19564) in case it is not an easy fix and requires more time for investigation?

**Comment by jo-mut** [comment]
@pavloburykh  we may need sometime to investigate it, we are looking into it, we will give an update in the afternoon

**Comment by pavloburykh** [comment]
> @pavloburykh we may need sometime to investigate it, we are looking into it, we will give an update in the afternoon

Great! Thank you @jo-mut!

**Comment by jo-mut** [comment]
> @pavloburykh : does this happen only on iOS? Could you pls check if this happens on Android too?

I am actually reproducing this on Android too, seems not to be ios only


<img src="https://github.com/status-im/status-mobile/assets/28704507/9ebdb7dc-121e-472a-b6af-658ffe319083" width="325">


```
INFO [04-23|14:11:00.423|github.com/status-im/status-go/protocol/messenger_mailserver.go:834]                                               synced topic                             mailserverID=store-01.do-ams3.shards.test chatIDs=[] fromString=2024-03-23T14:11:00Z toString=2024-04-23T14:11:01Z topic=[0x9dd744bf] from=1,711,203,060 to=1,713,881,461
INFO [04-23|14:11:00.423|github.com/status-im/status-go/protocol/messenger_store_node_request_manager.go:346]                               request finished                         requestID="{RequestType:0 DataID:0x033a350ed1b0de3870a3905d054f7b43af48fe0b809a1ec4bccb2df710f94512cb}" communityFound=false contactFound=false shardFound=false
WARN [04-23|14:11:00.561|github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:305]                          Served wakuext_communityUpdateLastOpenedAt reqid=39 duration="973.177µs" err="community not found"
INFO [04-23|14:11:00.885|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/connectedness.go:90]                peer disconnected                        peer=16Uiu2HAkw3d2VhXuEhTy7DD1GYWSF9pHD18MadEfyyK295SHW6sN
ERROR[04-23|14:11:04.082|github.com/status-im/status-go/vendor/go.uber.org/zap/sugar.go:222]                                                failed to resolve local interface addresses error="route ip+net: netlinkrib: permission denied"
ERROR[04-23|14:11:04.964|github.com/status-im/status-go/vendor/go.uber.org/zap/sugar.go:222]                                                failed to resolve local interface addresses error="route ip+net: netlinkrib: permission denied"
INFO [04-23|14:11:04.966|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:334]                   listening addresses update received      multiaddr="[/dns4/boot-01.ac-cn-hongkong-c.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /dns4/boot-01.ac-cn-hongkong-c.shards.test.status.im/tcp/443/wss/p2p/16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /ip4/127.0.0.1/tcp/40603/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /ip4/8.218.23.76/tcp/30303/p2p/16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y]"
ERROR[04-23|14:11:05.012|github.com/status-im/status-go/vendor/go.uber.org/zap/sugar.go:222]                                                failed to resolve local interface addresses error="route ip+net: netlinkrib: permission denied"
INFO [04-23|14:11:05.014|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:334]                   listening addresses update received      multiaddr="[/dns4/store-01.do-ams3.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /dns4/store-01.do-ams3.shards.test.status.im/tcp/443/wss/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /ip4/127.0.0.1/tcp/40603/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /ip4/8.218.23.76/tcp/30303/p2p/16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /dns4/boot-01.ac-cn-hongkong-c.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /dns4/boot-01.ac-cn-hongkong-c.shards.test.status.im/tcp/443/wss/p2p/16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /dns4/store-01.do-ams3.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y /ip4/159.223.242.94/tcp/30303/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT/p2p-circuit/p2p/16Uiu2HAkvbFbom7Zy1ECxdJD6fnFLmPi1yBPp9rdioEvN8LT4c4y]"

```

**Comment by pavloburykh** [comment]
> I am actually reproducing this on Android too, seems not to be ios only

Hi @jo-mut. 

The fact that you are unable to fetch community does not mean you are facing the issue which is described here. Could you please provide me a link to community you are trying to fetch?

The reason why community is not fetched for you might be the following:

1. Community you are trying to fetch is outdated (control node has been offline more than 30 days.). Try creating a new community. 
2. Recently we had troubles with fetching token gated communities which have minted tokens or set permissions on Sepolia. This was due to problems with Sepolia network (sepolia assets have not been fetched as well). But I am not reproducing this issue now. 

Unable to fetch communities (as well as unable to restore backed upa data) is not the bug which is described in this issue but only one of the symptoms of the problem. 

The main problem is **unable to connect to store node** (this is actually described in [issue description](https://github.com/status-im/status-mobile/issues/19736#issue-2253009491)). 

Have you checked if your Android device is connected to store node?

In order to check if your device is connected to store node you need to go to Profile - Legacy settings - Sync settings - Status nodes. Check if connected store node is displayed in Status nodes. 

In my case it is empty for IOS and displayed on Android (see screenshots below). 

**IOS:**

![photo_2024-04-23 22 29 39](https://github.com/status-im/status-mobile/assets/97245802/5168a7a7-ae7d-488a-ba10-7f5d843f0194)

**Android:**

![photo_2024-04-23 22 29 36](https://github.com/status-im/status-mobile/assets/97245802/0833ac2e-dfa5-481d-80c2-c0aaf623ac02)

Also, if you check IOS geth log which I have attached to this issue (in the description) you will see the following: 

```
INFO [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:283]                                         connecting error                         err="lookup store-02.gc-us-central1-a.shards.test.statusim.net on [::1]:53: read udp [::1]:55417->[::1]:53: read: connection refused"
INFO [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:283]                                         connecting error                         err="lookup store-01.ac-cn-hongkong-c.shards.test.statusim.net on [::1]:53: read udp [::1]:63509->[::1]:53: read: connection refused"
INFO [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:283]                                         connecting error                         err="lookup store-02.ac-cn-hongkong-c.shards.test.statusim.net on [::1]:53: read udp [::1]:57690->[::1]:53: read: connection refused"
INFO [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:283]                                         connecting error                         err="lookup store-01.do-ams3.shards.test.statusim.net on [::1]:53: read udp [::1]:57641->[::1]:53: read: connection refused"
INFO [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:283]                                         connecting error                         err="lookup store-02.do-ams3.shards.test.statusim.net on [::1]:53: read udp [::1]:53965->[::1]:53: read: connection refused"
INFO [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:283]                                         connecting error                         err="lookup store-01.gc-us-central1-a.shards.test.statusim.net on [::1]:53: read udp [::1]:53716->[::1]:53: read: connection refused"
WARN [04-19|13:18:51.256|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:290]                                         No mailservers available 
```

This means the app is unable to connect to mailservers. And it happens to me only on IOS.

**Comment by siddarthkay** [comment]
@pavloburykh : https://github.com/status-im/status-mobile/pull/19798 should fix this issue.
