### ISSUE TITLE
The routes are not found when attempting to send a collectible using the 'send' button in the opened collectible

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19746]
can be taken after merge of https://github.com/status-im/status-mobile/pull/19515

### Steps:
1. Restore the account with collectibles
2. Open collectible
3. Tap 'send'

### Actual result:
The routes are not found

https://github.com/status-im/status-mobile/assets/52490791/d90ccee5-ae90-4f86-879f-91a1e793e0a3

### Expected result:
The routes are found

### Logs:
[Status-debug-logs (8).zip](https://github.com/status-im/status-mobile/files/14960326/Status-debug-logs.8.zip)

**Comment by briansztamfater** [comment]
@VolodLytvynenko is this still relevant? I've tested and couldn't reproduce. Attaching a video:

https://github.com/status-im/status-mobile/assets/18485527/b2c89a3d-9e07-459d-967f-89560263912c

**Comment by VolodLytvynenko** [comment]
hi @briansztamfater Issue can be closed.  fixed in recent PR
