### ISSUE TITLE
Wallet - Integrate backend for Import Private Key Screen

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#19759]
Integrate backend for Import Private Key Screen
Designs
https://www.figma.com/file/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?type=design&node-id=2070-595431&mode=design&t=sHzsuzxZ9uVUWPW6-4

Align with desktop on what is needed for this to happen.

**Comment by Rende11** [comment]
I would like to implement it
