### ISSUE TITLE
The Sepolia testnet assets are not shown in the wallet

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19752]
### Steps:
1. Recover account with some Sepolia testnet assets
2. Enable testnet toggle
3. Go to wallet
4. Check balances

### Actual result:
The Sepolia testnet assets are not shown in the wallet.

![image](https://github.com/status-im/status-mobile/assets/52490791/64b71c41-f118-43e4-86a2-08a58812342b)

### Expected result:
The testnet assets are shown

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs:
[logs (2).zip](https://github.com/status-im/status-mobile/files/15059550/logs.2.zip)

**Comment by pavloburykh** [comment]
Communities with permissions set on testnet are not fetched as well.

**Comment by VolodLytvynenko** [comment]
hi @briansztamfater this issue seems to have resolved itself. I haven't seen any related PRs, so I'm unsure why it disappeared :)  Should I close it, or leave it open until the API limits you mentioned [here](https://discord.com/channels/1210237582470807632/1217175448828514344/1231902750191784016) will be discussed and fixed to prevent this from happening again?

**Comment by OmarBasem** [comment]
Closing this issue for now to reduce the [noise](https://github.com/status-im/status-mobile/issues/19466). Reopen if necessary.
