### ISSUE TITLE
No protocol method IDeref in profile -> set currency

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#19769]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/29711298/3e77f5ec-2a8c-4935-a2a1-32f18ae82a91

#### Expected behavior
Can change currency

#### Actual behavior
No protocol method IDeref error is shown

### Reproduction

1. Open profile
2. Click Advanced -> Set currency

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@seanstrom, @smohamedjavid, @mohsen-ghafouri - can we leave this issue for you settings guys ;)

**Comment by smohamedjavid** [comment]
@yevh-berdnyk - The ability to set currency is removed in https://github.com/status-im/status-mobile/pull/19795. Not sure if this issue is valid now.
