### ISSUE TITLE
Preferred routes not fetched when sending assets to additional account

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19779]
Follow up for https://github.com/status-im/status-mobile/pull/19668

### Steps:
1. Create an additional account -> Open -> edit -> open network preferences of current account -> Select particular network as preferences
2. Go to send flow using your first main account
3. Select your additional account in the 'accounts' tab to send assets

### Actual result:
All routes  are fetched 

https://github.com/status-im/status-mobile/assets/52490791/e326561c-1f2d-4227-95c8-c44ebc167b33

### Expected result:
Only the preferred routes selected in step 1 for the additional account in network preferences should be fetched

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
### NOTE for QA: 
take a look, at the preferable test cases https://ethstatus.testrail.net/index.php?/cases/view/730716 which can be run as sanity after the fixing of this issue

**Comment by churik** [comment]
I believe this one and other routing issues should be fixed in scope a bit later, reference https://github.com/status-im/status-desktop/issues/14569

Removed from milestone for now

**Comment by OmarBasem** [comment]
@J-Son89 I think this one is now out of scope for 2.30-2.31?

**Comment by churik** [comment]
I'd say out of scope for 2.30

**Comment by churik** [comment]
Doesn't make sense because of re-design and simplification the whole sending flow

**Comment by VolodLytvynenko** [comment]
This issue is not actual after new simplification flow https://github.com/status-im/status-mobile/pull/21595
