### ISSUE TITLE
Unable to run the app on ios

### ISSUE THREAD

**Issue by mmilad75** [status-im/status-react#19770]
# Bug Report
After running `make clean` and `make run-clojure`, I ran `make run-ios` but I faced this issue. I also tried to run `make run-metro` then run the app on ios simulator, but the same thing was happening.

<img width="1166" alt="Screenshot 2024-04-23 at 20 44 14" src="https://github.com/status-im/status-mobile/assets/55688834/c041a99e-02bb-4cad-8e3f-28daa6977182">

[ios_simulators_list.log](https://github.com/status-im/status-mobile/files/15080395/ios_simulators_list.log)
[react-native-xcode.log](https://github.com/status-im/status-mobile/files/15080396/react-native-xcode.log)

## Problem 
[comment]: # (A problem description)

### Reproduction

1. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
This happens when developers don't have Xcode 15.1, @mmilad75 @qfrank  and @Rende11 had the same issue with Xcode 14.3
