### ISSUE TITLE
Discover - Implement recent statuses and statuses per popular tags

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1977]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see all recent statuses posted by my contacts.
As a user I also want to see the most popular hashtags used in statuses shared with me and I want to browse the statuses by those tags.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

This issue was retroactively extracted from #1874 and it encompasses the first group of checkboxes.

**Comment by asemiankevich** [comment]
Assuming the UI part will be implemented in later PRs that is moved to Tested
