### ISSUE TITLE
 Incorrect message is shown in case of changes within 'edit receiver networks' drawer

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19777]
follow up for https://github.com/status-im/status-mobile/pull/19668

### Steps:
1. Go to 'send to' page
2. Select an asset for sending
3. Open 'edit receiver networks' drawer
4. Check or uncheck any checkbox

### Actual result:
![image](https://github.com/status-im/status-mobile/assets/52490791/f9c80ce6-db3f-4712-a82f-22a2e0984e4c)

### Expected result:
![image](https://github.com/status-im/status-mobile/assets/52490791/1eced9de-f0d2-4eb4-b8ac-a4169ac8a2ec)
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2388-503714&mode=design&t=bF6mMU3KcgYWlOBr-0

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
### NOTE for QA: 
take a look, at the preferable test cases https://ethstatus.testrail.net/index.php?/cases/view/730716 which can be run as sanity after the fixing of this issue

**Comment by mmilad75** [comment]
This issue is fixed and not reproducible anymore.

https://github.com/status-im/status-mobile/assets/55688834/1b472641-5068-45cc-a32a-6e48b52be3f6

**Comment by VolodLytvynenko** [comment]
> This issue is fixed and not reproducible anymore.
> 
>  Screen.Recording.2024-06-04.at.13.08.29.mov

@mmilad75 thank you for checking. Issue is fixed
