### ISSUE TITLE
Route still shown as available despite Insufficient balance on current network

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19774]
Follow up for https://github.com/status-im/status-mobile/pull/19668

Unfortunately, the issue does not happen consistently, hope the logs might help

### Steps:
1. Go to `send to` page
2. Enter addresses with 2-3 multichain prefixes (example: `eth:opt:0x000000000000000000000000000000000000dEaD`)
3. Go to page of assets value input
4. Enter value available only on 2 network
5. Diselect the fetched route
6. Enter value which is available on the deselected route

### Actual result:
The route is still shown as available.

https://github.com/status-im/status-mobile/assets/52490791/80e1014a-6901-4a6a-ad84-579839d9d9e8

### Expected result:
'The routes are not found' message should be shown if Insufficient balance is entered

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (4).zip](https://github.com/status-im/status-mobile/files/15075623/logs.4.zip)

**Comment by VolodLytvynenko** [comment]
### NOTE for QA: 
take a look, at the preferable test cases https://ethstatus.testrail.net/index.php?/cases/view/730716 which can be run as sanity after the fixing of this issue

**Comment by OmarBasem** [comment]
@J-Son89 I think this multichain issue is out of scope now?

**Comment by churik** [comment]
postponed due to limited capacity for 2.30

**Comment by VolodLytvynenko** [comment]
can be closed since the ability to focus on the input is disabled
