### ISSUE TITLE
[IOS] Profile page close and 'jump To' buttons unresponsive

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19786]
Unfortunately, the issue occurs very rarely, and there are no exact steps to reproduce it. It seems to happen randomly. I hope the logs might help

### Steps:
1. Open own profile page
2. Tap [x] to close the profile page or tap 'jump to' button 

### Actual result:
 The 'close' profile and 'jump to' buttons do not respond 

https://github.com/status-im/status-mobile/assets/52490791/5e086f39-a085-4ff0-8f00-82d4551a0a6b

### Expected result:
The buttons should  close the profile page and navigate jump to

### ENV: 
- IOS
- Nightly 24 Apr 2024

### Devices:
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (8).zip](https://github.com/status-im/status-mobile/files/15096062/logs.8.zip)

**Comment by ilmotta** [comment]
Closing as _not planned_ because Jump To feature is descoped.
