### ISSUE TITLE
Implement switcher cards for Wallet MVP

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#19784]
**Designs**: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=38196-48475&mode=design&t=3bH5dqkpV5i1enQ9-0

**Acceptance Criteria**:

For initial implementation card component and preview in quo screen will be enough.
We can populate jump-to screen with cards in follow up PRs.

**Comment by ilmotta** [comment]
Closing as _not planned_ because Jump To feature is descoped.
