### ISSUE TITLE
Wallet - design review - transactions details

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1979]
![image](https://user-images.githubusercontent.com/11790366/31083454-60d078da-a79a-11e7-9e0d-cde4f0e00644.png)
![image](https://user-images.githubusercontent.com/11790366/31083480-794f0624-a79a-11e7-9fa0-590bcdc43ab6.png)

**Comment by andmironov** [comment]
let's give some more space to labels
![Uploading IOS_Wallet-transaction-details Copy 3.png…]()
