### ISSUE TITLE
Recalculate max value when network is disabled

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19791]
As a user, when I disable a route in the 'From' column on the sending assets page (as shown in [this](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=2396%3A514833&mode=dev) flow), I expect the max value to be recalculated based on the rest of the enabled networks. 
Additionally, the disabled network label should not be shown in the max value. For example, if I disable `eth` route, then in the max value label, I should only see `arb1` and `opt`.

Discussed with a design team https://discord.com/channels/624634427930312714/852533718790570015/1232324734511878329

**Comment by OmarBasem** [comment]
@briansztamfater is that issue also fixed there https://github.com/status-im/status-mobile/pull/19768 ?

**Comment by briansztamfater** [comment]
No, we should implement this

**Comment by briansztamfater** [comment]
> As a user, when I disable a route in the 'To' column

@VolodLytvynenko shouldn't it be in the 'From' column?

**Comment by VolodLytvynenko** [comment]
> > As a user, when I disable a route in the 'To' column
> 
> @VolodLytvynenko shouldn't it be in the 'From' column?

@briansztamfater Correct. My fault. Updated in description

**Comment by BalogunofAfrica** [comment]
There is a case where if a user disables routes that have a balance leaving only the one with 0 balances, we display an error on the input and do not search further for routes which means we do not show the routes again and the user doesn't get to select the routes where they have some money. 

How should this be handled?

**Comment by VolodLytvynenko** [comment]
can be closed
