### ISSUE TITLE
Changing theme not working properly

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#19794]
Check video at 00:20 sec

https://github.com/status-im/status-mobile/assets/17097240/29449d16-3d5a-45b4-89cc-a9a2e07707c9

**Comment by flexsurfer** [comment]
i'm unable to replicate this

**Comment by Parveshdhull** [comment]
weird, on my emulator several screens broke using above steps but on android device only activity center icon broken in wallet screen 
![image](https://github.com/status-im/status-mobile/assets/17097240/e0f3c275-85fa-4fa9-8f3b-0308a9c2a52d)

**Comment by flexsurfer** [comment]
super weird

**Comment by Parveshdhull** [comment]
if its only happening in emulator we can close the issue. Please can you confirm if activity center icon is correct for you after theme changes?

**Comment by flexsurfer** [comment]
but still strange why it happens on emulator

**Comment by Parveshdhull** [comment]
probably some timing issue, it happens randomly. So maybe timing problem with hot-reload and theme change

**Comment by flexsurfer** [comment]
btw why do we need hot-reload?

**Comment by Parveshdhull** [comment]
do we even need hot-reloatd anymore

**Comment by Parveshdhull** [comment]
> btw why do we need hot-reload?

I don't remember why we needed, have to check

**Comment by Parveshdhull** [comment]
> btw why do we need hot-reload?

found it, https://github.com/status-im/status-mobile/pull/14811#issuecomment-1387051022

**Comment by Parveshdhull** [comment]
But from implementation it seems, initially we added hot-reload for all builds not only debug. Not sure when and why we changed it to only debug build. Still, we probably don't need it :thinking:

**Comment by Parveshdhull** [comment]
Closing issue for now, if we ever want to fix this issue, probably removing these lines should be solution
https://github.com/status-im/status-mobile/blob/d8e3934a050893f9e21e5e5fbd037e9836d8c1fd/src/status_im/contexts/profile/settings/effects.cljs#L34-L35

Currently don't want to remove them without knowing what will be side-effects
