### ISSUE TITLE
Error Etherscan link opens after click on View on Etherscan on Collectible screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19801]
# Bug Report

**Steps:**

1. Login as a User with exist collectibles
2. Go to Wallet -> Collectibles 
3. Tap on any Collectible from your list
4. Tap on three dots -> View on Etherscan

#### Expected behavior
Collectible transaction hash detailed page on Etherscan should be opened

#### Actual behavior
<img width="199" alt="Screenshot 2024-04-25 at 16 42 50" src="https://github.com/status-im/status-mobile/assets/147824399/2342c27b-e897-470c-8181-86b6dc625aa4">

### Additional Information

- Status version: nightly 24/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by FFFra** [comment]
I'm taking a look. It might be related to another issue Im finding regarding Collectibles

**Comment by ulisesmac** [comment]
@mariia-skrypnyk 
Could you please provide an address to watch with an specific collectible to reproduce this issue?

I can't reproduce it.

**Comment by mariia-skrypnyk** [comment]
Hi @ulisesmac !
Thanks for paying attention to this issue.
I've retested on all collectibles that I have and it works fine now.
Etherscan page with contract details successfully opens.

Will close this issue.
