### ISSUE TITLE
The color of the  'continue' button does not inherit the color of the account

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19809]
Follow up for https://github.com/status-im/status-mobile/pull/19702#event-12619811557

### Steps:
1. Set up a particular color picker for the account
2. Go to 'Use recovery phrase' page 

### Actual result:
The 'continue' button does not inherit the color of the account and is always shown as blue
![image](https://github.com/status-im/status-mobile/assets/52490791/24ef2162-2aac-4090-8505-31d48c9d07b5)

### Expected result:
The 'continue' button  inherits the color of the account

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by OmarBasem** [comment]
Hey @VolodLytvynenko,

I think the current implementation is correct. You can see in [this flow](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-595222&mode=design&t=vIXgqSyTg8yr3P0q-4) the current selected is light-blue (new account color) and the button color is dark-blue (profile color)

**Comment by OmarBasem** [comment]
Closing this issue to reduce [the noise](https://github.com/status-im/status-mobile/issues/19466). Reopen if necessary.
