### ISSUE TITLE
Wallet - design review - send transaction

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1980]
![image](https://user-images.githubusercontent.com/11790366/31083526-9931c8be-a79a-11e7-979f-7587cf2c74ae.png)
![image](https://user-images.githubusercontent.com/11790366/31083531-9d9d4900-a79a-11e7-8aa9-afd4a98b4006.png)
![image](https://user-images.githubusercontent.com/11790366/31083537-a1da310e-a79a-11e7-8209-8afb6e844184.png)
![image](https://user-images.githubusercontent.com/11790366/31083542-a62edae8-a79a-11e7-8ce9-c6c1ad068c3e.png)
![image](https://user-images.githubusercontent.com/11790366/31083553-aae2d6c0-a79a-11e7-8a66-fb4e31cf66a5.png)
![image](https://user-images.githubusercontent.com/11790366/31083569-b3cf7540-a79a-11e7-9796-12778d414fdf.png)
![image](https://user-images.githubusercontent.com/11790366/31083598-c2f1b114-a79a-11e7-8ef0-710dec121012.png)
![image](https://user-images.githubusercontent.com/11790366/31083613-c8cea20e-a79a-11e7-9f98-600cfe289380.png)
![image](https://user-images.githubusercontent.com/11790366/31083619-cd51a376-a79a-11e7-9578-3cea9f8c2830.png)

**Comment by andmironov** [comment]
- the field labels are a little cut on the bottom (this looks very bad, please fix) :-)
- let's use monospace typeface (Roboto Mono) for the security phrase
- the `Transaction Sent` on success screen should be semibold
