### ISSUE TITLE
Max Amount is zero if user tries to send ETH to his another account

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19813]
# Bug Report

#### Expected behavior
Max amount is equal to the real amount of tokens user has

#### Actual behavior
Max Amount is zero.
Issue reproduces only on Tetiana's account.
Please, ask a seed phrase ONLY in case you are going to work on this issue as it is a private account with real money.

https://github.com/status-im/status-mobile/assets/147824399/ff1d6587-e71f-4953-9b13-6b447e6c6da8

### Reproduction

1. Login to app as a user with real ETH tokens
2. Go to Wallet
3. Create one more account
4. Go to Send -> ETH
5. Select your second account as a receiver

### Additional Information

- Status version: nightly 25/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by VolodLytvynenko** [comment]
potential duplicate https://github.com/status-im/status-mobile/issues/19646
