### ISSUE TITLE
More reagent atom regression

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19812]
# Bug Report

### ISSUE 1: `Scroll to the bottom` button

<img width="323" alt="Screenshot 2024-04-26 at 12 10 17" src="https://github.com/status-im/status-mobile/assets/67952253/a703975c-4db5-485e-b207-8bc8267f7384">

### ISSUE 2: Link preview inside the composer

<img width="313" alt="Screenshot 2024-04-26 at 12 12 26" src="https://github.com/status-im/status-mobile/assets/67952253/24c57b07-c1bf-48b2-aa53-aa994da69b57">

### ISSUE 3: Loading skeleton on iOS

It's easier to reproduce when you open a channel of the community that you haven't joined yet

https://github.com/status-im/status-mobile/assets/67952253/5fcd9670-7756-4925-9a8c-4933edcd4f1d

### ISSUE 4: Wrong letter and background color of the channel avatar

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16876-89050&mode=design&t=XlIs4xoeCOqHz6b3-4

<img width="391" alt="Screenshot 2024-04-26 at 12 14 08" src="https://github.com/status-im/status-mobile/assets/67952253/c374ab6f-197a-4c6d-99dc-a2048d97c42c">

### Additional Information

- Status version: nightly 26/04
- Operating System: Android, iOS

@flexsurfer 

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
- [x] ISSUE 1: Scroll to the bottom button
- [x] ISSUE 2: Link preview inside the composer
- [x] ISSUE 3: Loading skeleton on iOS
- [ ] ISSUE 4: Wrong letter and background color of the channel avatar (not related to the theme, its a customization color)
