### ISSUE TITLE
Incorrect Gas Fee estimation on Optimism network

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19817]
### Steps:
1. Recover user with assets on Optimism  (no matter sepolia optimism or mainet optimism)
2. Check the estimated fee when the asset is entered into input asset field

### Actual result:
In Optimism Mainnet, the gas fee is usually higher than estimated. in fact 0.30 usd, but Status (mobile and Desktop) gas fee typically shows as 1.30 USD
![image](https://github.com/status-im/status-mobile/assets/52490791/558b2c86-024f-489b-ba44-d1071e507c6b)

Optimism Sepolia etherscan [link](https://sepolia-optimism.etherscan.io/tx/0x6c4cf7987fe068e7733d79c8ad71d1f7f5004a3ea71ed8d5c9be29a9c263883a
)
Optimism mainnet etherscan [link](https://optimistic.etherscan.io/tx/0xd2977ec93278a3bcf430fad3d620433f6c1e93609da9eb62a9be3afdc1b7d41a
) 

### Expected result:
The fee is calculated correctly

### Additional info:
- The same issue is on the desktop
![image](https://github.com/status-im/status-mobile/assets/52490791/fed1ed01-bfdc-4b9b-baff-a5a2800ce140)

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by churik** [comment]
cc @saledjenic

**Comment by saledjenic** [comment]
@churik that's something we will try to fix by improving the router logic on the statusgo side.

**Comment by churik** [comment]
should be fixed in v2, reopen if still relevant
