### ISSUE TITLE
The route cannot be disabled when sending assets using the receiver's address with the preferred network.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19818]
### Steps:
1. Recover the User with available assets on a few networks (for example: Mainnet and Optimism)
2. Enter into 'send to' page a multichain address using the network preferences of a receiver (example: opt:0x8d....23)
3. Go to the routes fetching page 
4. Enter available amount on both of your networks (now you see the route is built like this: Sender Mainnet -> Receiver Optimsm)
5. Tap on Mainnet route into 'to' section to disable it

### Actual result:
The route for sender is not disabled

https://github.com/status-im/status-mobile/assets/52490791/f9cce174-916c-4a67-9961-2c1864d1964b

### Expected result:
The route should be disabled, and a new route with available assets should be fetched (similar to how it works for desktop).

https://github.com/status-im/status-mobile/assets/52490791/a3501745-7fb1-421f-b3b7-30fe7898ecb7

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by OmarBasem** [comment]
@briansztamfater is this issue fixed in your PR https://github.com/status-im/status-mobile/pull/19768 ?

**Comment by briansztamfater** [comment]
_I think_ it is, I am currently AFK so I can't check, but I would suggest to wait until the refactor is merged to work on routes related issues

**Comment by VolodLytvynenko** [comment]
@OmarBasem Today I'll check in on https://github.com/status-im/status-mobile/pull/19768 and let you know. If it's fixed, I'll close the current issue, or I'll ping you if it's not fixed

**Comment by VolodLytvynenko** [comment]
**it's work)** correctly here https://github.com/status-im/status-mobile/pull/19768 
cc: @briansztamfater @OmarBasem

**Comment by briansztamfater** [comment]
Sorry I didn't understand if this was fixed on https://github.com/status-im/status-mobile/pull/19768, @VolodLytvynenko is this still relevant?

**Comment by VolodLytvynenko** [comment]
> Sorry I didn't understand if this was fixed on #19768, @VolodLytvynenko is this still relevant?

Hi @briansztamfater I forgot to close this after merging of https://github.com/status-im/status-mobile/pull/19768
Now it works correctly in develop and this issue can be closed
