### ISSUE TITLE
Navigation to chat review page after tapping 'Block' button

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19824]
### Steps:
1. `UserA` and `UserB` are mutual contacts
2. `UserA` sends a few messages into 1-1 chat
3. `UserA` Taps '...' dots into the right corner of opened chat -> tap 'view profile' option
5. `UserA` blocks `UserB`

### Actual result:
The user is navigated to the chat preview page.

https://github.com/status-im/status-mobile/assets/52490791/fba177a4-0447-427f-8108-d7b809e9a579

### Expected result:
The user should remain on the same page after blocking a user, rather than being navigated to the chat preview page.

https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=19-59400&mode=design&t=jbYw9bXQT1PKajnP-0

**Comment by Parveshdhull** [comment]
Thank you @VolodLytvynenko for reporting this issue.

> The user should remain on the same page after blocking a user, rather than being navigated to the chat preview page.

We [remove](https://github.com/status-im/status-mobile/issues/19327#issuecomment-2024762679) chat on blocking user,  if we keep user on this screen and he/she navigates back without unblocking user will navigate to an empty chat screen.

I guess we can avoid removing chat until user navigates back to home screen :thinking:

**Comment by Parveshdhull** [comment]
> I guess we can avoid removing chat until user navigates back to home screen

@VolodLytvynenko Please can you confirm if this will work?

**Comment by VolodLytvynenko** [comment]
> > I guess we can avoid removing chat until user navigates back to home screen
> 
> @VolodLytvynenko Please can you confirm if this will work?

hi @Parveshdhull this still works. Reproduced on today's nightly
