### ISSUE TITLE
Choose Recipient navigation fixes

### ISSUE THREAD

**Issue by x-goose-x** [status-im/status-react#1983]
### User Story

As a user, I want QR code scans and pastes to navigate back to the Send Transaction screen.

### Description

*Type*: Bug

*Summary*:  QR scanning and pasting from clipboard used an outdated data model and didn't navigate the user to the correct screen.

#### Expected behavior
- Scanning a QR code should navigate the user to Send Transaction
- Pasting an address from clipboard should navigate the user to Send Transaction

#### Actual behavior
- No navigation takes place

### Reproduction
- Open Status
- Navigate to wallet
- Navigate to send
- Attempt a QR scan or a paste from clipboard.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [x] Fix navigation events and update db handlers

**Comment by annadanchenko** [comment]
tested in develop, will be in release 0.9.12
