### ISSUE TITLE
Wallet - Crypto on ramps to use data with Status Partner ID's

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#19836]
The current "Buy" on ramps do not use the correct provider id's.

it should be enough to use the list of providers returned by this
![image](https://github.com/status-im/status-mobile/assets/22799766/9353f68d-e259-4dfd-baeb-f3e0529c6614)

 We can get this info from Status-Go, then update the file isrc/status_im/contexts/wallet/sheets/buy_token/view.cljs
<img width="441" alt="Screenshot 2024-04-30 at 11 08 49" src="https://github.com/status-im/status-mobile/assets/22799766/2aa8a917-614b-4de8-9242-82c4fe4448e3">

**Comment by ajayesivan** [comment]
<img width="619" alt="Screenshot 2024-05-17 at 10 59 24" src="https://github.com/status-im/status-mobile/assets/19279756/d0bc7835-9ffc-4d92-bd9f-6c16a51dc808">
