### ISSUE TITLE
Red screen error when switch tabs on chat home screen with one contact request in contacts tab (no contacts)

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#19845]
# Bug Report

## Problem 
Red screen error when switching tabs on the chat home screen with one contact request in the contacts tab (no contacts)

#### Expected behavior
no error

### Reproduction

1. open the app with only one pending contact request and without contacts 
2. switch to the contacts tab, switch to the group or recent tab
3. crash

Also sometimes when scrolling groups in the middle and then switching to contacts, contacts tabs are in the wrong state
<img width="376" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/f4e82713-5d85-4541-941d-f8d13d4d5df7">

**Comment by VolodLytvynenko** [comment]
can't reproduce it. Maybe I miss some additional steps. Tried on the last nightly [30 Apr 2024] both Android and IOS. Could you add more details about your device?

https://github.com/status-im/status-mobile/assets/52490791/3d77a133-79d9-4386-96a7-d24f887ea945


### Devices:
- iPhone  11 max pro, IOS 17
- Pixel 7a, Android 13

**Comment by Parveshdhull** [comment]
> App crashes when switching tabs on the chat home screen with one contact request in the contacts tab 

is this only happening in debug builds? might be related to hot-reload https://github.com/status-im/status-mobile/issues/19794#issuecomment-2084615572

**Comment by flexsurfer** [comment]
probably it doesn't crash in release, and this error is just ignored
