### ISSUE TITLE
incorrect routes is fetched  for sender in case when L2 prefix is used for receiver address

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19846]
### Steps:
1. Recover user with available assets on Mainnet and on any L2 network
2. Enter the receiver address with L2 network prefix for address (example: opt:0x8d....23)

### Actual result:
The mainnet route is fetched for the sender, and the L2 route is fetched for the receiver

Example:
Sender: Mainnet route -> Receiver: Optimism route
![image](https://github.com/status-im/status-mobile/assets/52490791/0d6b09dc-1944-463b-8fe9-e0c4732b32a1)

https://github.com/status-im/status-mobile/assets/52490791/e7e64419-91e5-4000-bc15-50a0049c4000

### Expected result:
The most optimal route based on fees should be fetched. For example, both sender and receiver should have the Optimism route fetched when the sender intends to send assets to an address with the `opt` prefix.

Example:
Sender: Optimism route -> Receiver: Optimism route

reference
https://discord.com/channels/1210237582470807632/1217175448828514344/1234414135241085019

### Additional info:
Same issue is on the desktop
![image](https://github.com/status-im/status-mobile/assets/52490791/a3610ff5-8667-469a-9660-3145073ea56c)

### OS: 
IOS, Android, Desktop

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
- Desktop master status go 0.179.8

### Logs
[logs.txt](https://github.com/status-im/status-mobile/files/15166600/logs.txt)

**Comment by churik** [comment]
should be resolved in v2, closing for now
