### ISSUE TITLE
Border around activity item icon

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#19853]
The border around activity item icon (arrow) is not displayed.
[Designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22134-223442&mode=design&t=EvwHaw8JWFNmGAfF-4)

![Screenshot_20240501_104001_Status](https://github.com/status-im/status-mobile/assets/29354102/6eb325d5-2217-482a-abec-d8804c6c2410)

**Comment by churik** [comment]
![IMAGE 2024-06-24 13:42:04](https://github.com/status-im/status-mobile/assets/4557972/5ea6f061-9ca7-4659-81d8-9383c9ac0218)
Not reproducible anymore
