### ISSUE TITLE
Wallet: Activity - Unknown Tokens

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#19851]
Some of the activity items does not have a symbol token returns. That would require a request to status-go to fetch that token's data using its contract address and chainId. In case the token does not exists, then we display an unknown token placeholder (to be checked with design team).

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1070-284225&mode=design&t=05G37UXdKebXGVOI-4

**Comment by shivekkhurana** [comment]
This issue might be invalid now, given the new system of saving activity. Closing.
