### ISSUE TITLE
Change "Offline" section in group chat members

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#19883]
The "Offline" section in group chat->View members->Manage members section should be changed to just show:
"Members" (there should not be an "online"/"offline" section, only "members"). As it looks the behavior is buggy and is better to simplify instead of fixing for now.

**Comment by flexsurfer** [comment]
hey @cammellos could you please elaborate, we don't have online/offline on "manage members" page, and on "view details" we have but it works fine
<img width="712" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/9b5693c6-4a57-43e6-9d3a-7412307e4e6c">

**Comment by cammellos** [comment]
> hey @cammellos could you please elaborate, we don't have online/offline on "manage members" page, and on "view details" we have but it works fine <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/11790366/328146402-9b5693c6-4a57-43e6-9d3a-7412307e4e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTEzMzAsIm5iZiI6MTcxNDk5MTAzMCwicGF0aCI6Ii8xMTc5MDM2Ni8zMjgxNDY0MDItOWI1NjkzYzYtNGE1Ny00M2U2LTlkM2EtNzQxMjMwN2U0ZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEwMjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZjkxODQyNTIxMWU5ZjQ4MjFhZTA1ZDlhNTQyZWNmM2E5Mjk0YjY2OGNhNjU1YjBjNzc0YjRmNWNjZjM2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5kbpgFG0bZMhAME6wGgpj8bnFB6IXv9GIfaHvLq2UQs">

We saw it not working on our walkthrough, users were marked as `offline`, but had a green dot on it (we I take should not happen). 
Not critical I guess, if it's working some of the times is fine and happy to close it, either ways is a small issue.
