### ISSUE TITLE
Hide private channel if created with the "hidden option"

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#19885]
# Feature Issue

### User Story

As a community admin
I want to be able to hide private channel from those who don't have access
So that I don't disclose private information about my community

### Description

Private channel of a community can be set so that they are hidden when adding permissions/creating the channel.
Those channels should not be shown to users who don't have access. If a category has no visible channels, it should not be shown.

**Comment by Parveshdhull** [comment]
probably this functionality is already implemented
https://github.com/status-im/status-mobile/blob/8a24185ad6ef81f069c1a41f31ef8192992a27a3/src/status_im/subs/communities.cljs#L311

Currently unable to verify because blocked by https://github.com/status-im/status-desktop/issues/14608

**Comment by Parveshdhull** [comment]
upd: still blocked - https://github.com/status-im/status-desktop/issues/14608#issuecomment-2106231755

I will break the issue in two parts, and will fix hiding of empty categories for now and we can address hiding private channel once issue is fixed.
