### ISSUE TITLE
Profile picture and identity ring are not shown after syncing if initially profile picture was not set

### ISSUE THREAD

**Issue by churik** [status-im/status-react#19892]
# Bug Report

## Problem 
Initially profile picture is not set on the desktop side, so it is shown as "CH"

![image](https://github.com/status-im/status-mobile/assets/4557972/959ed265-bece-47cb-873b-677d5a684a39)

#### Expected behavior
can see identity ring and default "CH"

#### Actual behavior
https://github.com/status-im/status-mobile/assets/4557972/85311dda-0300-4b3a-839d-c521a5701641

### Reproduction

1. Desktop: create a profile without picture
2. Mobile: sign in by syncing

### Additional Information

- Status version: desktop nightly 03/05 - mobile nightly 03/05
- Operating System:  iOS (haven't check on Android) 
- Logs: [logs (80).zip](https://github.com/status-im/status-mobile/files/15199795/logs.80.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cross-referencing with https://github.com/status-im/status-mobile/issues/17193

**Comment by qfrank** [comment]
It seems desktop does not support custom account color(`CustomizationColor`), and it just leave `CustomizationColor` as empty when creating account, will desktop support in the future? @iurimatias 

relate error:
```
handleAccountInitials: no bgColor
```

Whatever, my solution would be:
- update backend and set a default value `blue` if frontend not passing the param when creating account
- set the default value `blue` if it's empty when syncing on the receiver side
cc @yqrashawn WDYT?

**Comment by churik** [comment]
@qfrank for me this solution appears perfect, as we need to use blue as a fallback color.

**Comment by yqrashawn** [comment]
I'm not sure about desktop's usage. Cause I remember there're similar colors in desktop code. 
It's wallet account color? 
Also there're different colors in different places. 
I remember customization colors in status-go are actually profile customization color + wallet color. 

But I guess that does matter that much in this situation. 
I prefer the first option. It makes sure customization color is always set. @qfrank

**Comment by qfrank** [comment]
> I prefer the first option

No, I meant we need both of the options, otherwise it won't solve the issue @yqrashawn

**Comment by qfrank** [comment]
Thank you for your input, I'll make a PR based on our discussion @yqrashawn @churik

**Comment by qfrank** [comment]
Just found there's a [validation](https://github.com/status-im/status-go/blob/d8a49c538b744fbde10acff5b395cef91e24cd78/protocol/requests/create_account.go#L123) on `CustomizationColor` when creating account, also I checked latest desktop source code, it does passed "primary" as `CustomizationColor` so I guess this issue only exist for old status-desktop, and I tried [2.29.0-beta](https://github.com/status-im/status-desktop/releases/tag/2.29.0), yeah, the result turns out my guess is right. WDYT? @churik

**Comment by churik** [comment]
Yes, it is not reproducible with latest master, closing, thank you!!
