### ISSUE TITLE
Wallet: Error message shown when tapping Sign all button on Unsigned transactions screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1989]
### Description

*Type*: Bug

*Summary*: Sign all functionality allows user to sign all tarnsactions on Unsigned transactions screen, however it is not working now and error message is shown

#### Expected behavior
Sign all functionality is not implemented now

#### Actual behavior
Error ` *no print-fn* fn set for evaluation environment`

![image](https://user-images.githubusercontent.com/28752642/31121889-925082b2-a842-11e7-9d63-e81721f9f339.png)

### Reproduction

- Open Status
- Go to Wallet tab
- Click Send
- Select recipient -> Sign Transaction
- Tap sign later
- Go to History screen
- Tap sign all 
- Enter password and tap sign again

### Additional Information
* Status version: 0.9.10-159-g4b6f920e+ (1716)
* Operating System: Android, iOS

**Comment by rasom** [comment]
https://github.com/status-im/status-react/blob/8d2992d1a41601596c42f46afcebbef7d3bbf6a8/src/status_im/ui/screens/wallet/transactions/views.cljs#L69

**Comment by annadanchenko** [comment]
We do not implement Sign All in 0.9.12 release. Removing label

**Comment by jeluard** [comment]
@annadanchenko This particular error is gone anyway (some debug left out).
