### ISSUE TITLE
Error when entering two zeros in a row in the 'Amount' field in wallet

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19908]
# Bug Report

### Reproduction

1. Open wallet
2. Go to the `Send` flow
3. Select a recipient and an asset
4. In the amount field enter 0 two times

#### Expected behavior

The field displays just one "0"

#### Actual behavior

<img width="308" alt="Screenshot 2024-05-06 at 13 14 05" src="https://github.com/status-im/status-mobile/assets/67952253/c0847afd-14a4-407e-9d39-a9aae9a37b01">

https://github.com/status-im/status-mobile/assets/67952253/5aaec290-98b3-4d6b-b0db-ae2ba0193dcf

### Additional Information

- Status version: nightly 6/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by VolodLytvynenko** [comment]
hi @OmarBasem I see you have already created a PR with a fix. Please take a look at an additional error that is shown if a user attempts to enter more than 2 dots

https://github.com/status-im/status-mobile/assets/52490791/d7e423cc-c9f9-480f-9ecd-818e80dd3273

Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/15220784/Status-debug-logs.1.zip)

**Comment by OmarBasem** [comment]
@VolodLytvynenko same fix :)
