### ISSUE TITLE
Handle 'No routes found' error and Invalid Input when disabling chains after route discovery

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#19910]
# Feature Issue

### User Story

As a user, I want to instantly see a "No routes found" and invalid input errors when disabling a chain after a route was found and I don't have sufficient amounts in the remaining enabled chains to continue performing that transaction **so that** I can re-enter a new valid amount to search for a new valid route.

### Description

There could be a situation in the send flow where the user enters an amount, the algorithm suggests a route with different chains being used on the sender side, and then the user disables one of the chains. When that happens (and it a pre-requisite to implement this issue), [the max amount to be sent should be re-calculated taking only into account the enabled networks](https://github.com/status-im/status-mobile/issues/19791). If the re-calculated max amount is less than the amount the user wanted to send initially, the input text should be red, the network tag showing the max amount should be in error state, `No routes found` error should be displayed and the Confirm button should be disabled (no `Try again` button).

NOTE: This is a different error from the `No routes found` error caused by an empty response from the algorithm, we should implement this check locally, no need to interact with status-go endpoint in this flow / case because we already have the input value and the new max amount.

Visual reference:
<img width="400" src="https://github.com/status-im/status-mobile/assets/18485527/1d19abad-111a-440d-9973-38eac6b83fd7">

Please refer to Figma designs for up-to-date flows: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=13182-97852&mode=design&t=zTPO4fewPKXg4zw2-4

### Acceptance Criteria

If the re-calculated max amount is less than the amount the user wanted to send initially...
- [ ] The input text should be red
- [ ] The network tag showing the max amount should be in error state
- [ ] `No routes found` error should be displayed
- [ ] The Confirm button should be disabled (no `Try again` button because it is not an error from the endpoint)
- [ ] And of course we should not break current implementation for other route discovery flows

**Comment by BalogunofAfrica** [comment]
Most of the criteria here is already addressed here https://github.com/status-im/status-mobile/pull/19953

Only bit not addressed is the "Try again" button

![Simulator Screen Recording - iPhone 11 Pro - 2024-05-10 at 12 46 10](https://github.com/status-im/status-mobile/assets/45393944/64502113-7798-4b3d-8902-fceabc58a152)

**Comment by briansztamfater** [comment]
@BalogunofAfrica Not only the Try again button, we should not fetch routes again if the input amount is greater than max amount, that is another issue I can see from your recording

**Comment by BalogunofAfrica** [comment]
> @BalogunofAfrica Not only the Try again button, we should not fetch routes again if the input amount is greater than max amount, that is another issue I can see from your recording

The issue with that is that once an input is invalid we clear all the suggested routes info (which would prevent users from then selecting routes with amount)

**Comment by VolodLytvynenko** [comment]
Hi @briansztamfater, I just wanted to clarify the difference between 'routes are not found' and 'routes are not found: Try again'.

- 'Routes are not found' occurs when the entered amount exceeds the value in the max value field.
- 'Routes are not found: Try again' happens when something goes wrong (some bridge error etc.), or the user can't cover the transaction with the gas fee.

Is that correct?

**Comment by briansztamfater** [comment]
> Hi @briansztamfater, I just wanted to clarify the difference between 'routes are not found' and 'routes are not found: Try again'.
> 
> * 'Routes are not found' occurs when the entered amount exceeds the value in the max value field.
> * 'Routes are not found: Try again' happens when something goes wrong (some bridge error etc.), or the user can't cover the transaction with the gas fee.
> 
> Is that correct?

@VolodLytvynenko Sorry I haven't seen this until now.

The `Try again` button should be shown when the algorithm / status-go endpoint does not return any route for the given input.

The only case where we should **not** show the Try again button (which is the use case this issue should implement) is when:
1) The user enters a valid amount and routes are found
2) Then the user disables a network that makes the previously valid amount be now invalid because the new calculated max value is now reached
3) When that happens, we don't need to fetch suggested routes again because we already know it is an invalid amount, so we should just wait for the user to re-enable networks or modify the amount.

**Comment by VolodLytvynenko** [comment]
Hi @briansztamfater, thank you for the clarification. If the user does not have enough ETH to cover the transaction fee, should 'No routes found' be shown with or without 'Try again'? For example, if the user has 1.01 ETH, enters 1.00 ETH, and the transaction fee is 0.02 ETH.
