### ISSUE TITLE
Wallet: implement validation for scanned QR code and copypasted content in Choose recipient flow

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1991]
### Description

*Type*: Bug

*Summary*: Need to add validation for scanned QR code and copy pasted content when selecting recipient on Choose Recipient screen

#### Expected behavior
- choose recipient -> scan QR code with opened qr scanner -> popup should be shown for all scnned content except valid account address
- choose recipient -> use address from clipboard ->popup should be shown for all previously copied content except valid account address

In both above listed cases recipient field should not be populated with incorrect content until user scans/copies valid account address

### Additional Information
* Status version: 0.9.10-159-g4b6f920e+ (1716)
* Operating System: Android, iOS

**Comment by annadanchenko** [comment]
Tested ok in develop. Will be in 0.9.12 release
