### ISSUE TITLE
Wallet: Show loading indicator when Sign Transaction is tapped (same loading as for Sign in screen)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1992]
### Description

*Type*: Bug

*Summary*: Show loading indicator when Sign Transaction is tapped (same loading as for Sign in screen)

#### Expected behavior
Loading indicator (same as for Sign in screen) is shown when tapping Sign Transaction

### Additional Information

* Status version: 0.9.10-159-g4b6f920e+ (1716)
* Operating System: Android, iOS

**Comment by annadanchenko** [comment]
Tested in develop, will be in release 0.9.12
