### ISSUE TITLE
Wallet: Main wallet amount is not updated 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1993]
### Description

*Type*: Bug

*Summary*: Main wallet shows 0 USD with no respect of actual user balance

#### Expected behavior
Main wallet should reflect actual user balance

#### Actual behavior

Actual balance is shown on Wallet main screen but is not updated in Main wallet 
![image](https://user-images.githubusercontent.com/28752642/31123215-a38ae0b8-a847-11e7-8c88-9066a6bf7385.png)

![image](https://user-images.githubusercontent.com/28752642/31123221-acb52144-a847-11e7-9ef9-cc70e6316445.png)

### Reproduction

- Open Status
- Go to Wallet
- Click Main wallet drop-down
- Pay attention to Main wallet value

### Additional Information
* Status version: 0.9.10-159-g4b6f920e+ (1716)
* Operating System: Android, iOS

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
