### ISSUE TITLE
GethStatus Failed to Initialize Accounts DB leads to crash

### ISSUE THREAD

**Issue by daferna** [status-im/status-react#19932]
# Bug Report

## Problem 
[comment]: # (A problem description)
Status can't launch. I have setup sync between my Desktop and Mobile, and was trying out the Communities feature yesterday, today I can't launch. See attached logcat.txt

#### Expected behavior
Login screen

#### Actual behavior
"Vector's key for assoc must be a number."

### Reproduction

1. Launch Status
2. Observe "Vector's key for assoc must be a number."

### Additional Information

- Status version: [2.28](https://github.com/status-im/status-mobile/tree/2.28.0)
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
[logcat.txt](https://github.com/status-im/status-mobile/files/15240165/logcat.txt)

**Comment by churik** [comment]
@daferna thank you for reporting!
Did you install Status on mobile from scratch or upgrade from 2.27 and with what desktop version do you have your device synced?

**Comment by daferna** [comment]
I skipped upgrading for a couple versions, because I was chatting with people on the old fleet "eth.prod", so I think I upgraded from [1.25.0](https://github.com/status-im/status-mobile/releases/tag/1.25.0). But I had to re-enter my seedphrase, meaning presumably I created a new accounts db. My desktop is the latest tagged release: https://github.com/status-im/status-desktop/releases/tag/2.28.0

**Comment by daferna** [comment]
I also started sync *after* entering my seedphrase on both mobile and desktop, so my flow was:
1. Enter seed into 2,28 on mobile
2. Enter seed into 2.28 on desktop
3. Generate a QR synccode on desktop and scan on mobile
4. Wait a day, or perhaps reboot?
I could try these steps and see if it reoccurs.

**Comment by churik** [comment]
@daferna 
Can you please try the other flow? 
As far as I understand you have your account worked and set on desktop.
Can you go to profile > Syncing > Setup syncing on desktop and on mobile try flow + > Add existing profile and scan QR? 

That should pair your accounts and transfer your data from desktop to mobile.
For this flow, you need to be in the same Wi-FI network.
Appreciate your help!

**Comment by jo-mut** [comment]
> I also started sync _after_ entering my seedphrase on both mobile and desktop, so my flow was:
> 
> 1. Enter seed into 2,28 on mobile
> 2. Enter seed into 2.28 on desktop
> 3. Generate a QR synccode on desktop and scan on mobile
> 4. Wait a day, or perhaps reboot?
>    I could try these steps and see if it reoccurs.

currently syncing does not support this flow

**Comment by mariia-skrypnyk** [comment]
Hey @daferna !

Thanks for your feedback!

I tried your scenario on Desktop 2.28 and 2.28.1 and my android device Samsung A34 (14.0): 

1. Enter seed into mobile
2. Enter seed into desktop
3. Generate a QR synccode on desktop and scan on mobile

I have a successful sync on my mobile.
<img width="300" alt="Screenshot 2024-05-16 at 16 29 11" src="https://github.com/status-im/status-mobile/assets/147824399/f23011fe-028a-4aa8-9788-66cf4966ff44">

Please, let us know our updates!
Maybe smth will work for you.

**Comment by daferna** [comment]
Currently, I haven't been able to replicate the bug (I've briefly tried going back to an earlier APK version and then upgrading the APK w/ a new account), if I can't get it to reoccur, I assume it was some idiosyncrasies from running an old APK and  upgrading with sync that are unlikely to happen again

**Comment by mariia-skrypnyk** [comment]
Hi @daferna !

It really make sense and hope it was a one time issue.

Thanks for your feedback!
