### ISSUE TITLE
Wallet implement send command transaction signing UI and remove old transactions UI

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#1994]

**Comment by annadanchenko** [comment]
Scope of the issue:
1. Send command In 1-1 chat and in group chat: user selected recipient, typed amount and taps on Send button. After this 
 * Transaction is sent to Unsigned - THIS IS TO BE CHANGED AFTER #2033 is implemented. Transaction should not be added to Unsigned upon tapping on send button
* "Send transaction" screen is shown with pre filled values for recipient and amount
* User can Sign Transaction and if all is ok -> screen is closed, chat is shown with new send message
* User can select "Sign Later"  -> currently, no alerts/info is shown that tx is moved (THIS IS TO BE CHANGED AFTER #2033 is implemented.)
* If tap on "x" then screen "Send transaction" is closed and chat is shown but tx is already in Unsigned (THIS IS TO BE CHANGED AFTER #2033 is implemented.)
* After user types correct password and transaction is Signed then  screen "Send transaction" is closed and chat is shown with new send message in it
2. Unsigned tab in Transactions
* if tap on Sign button under transaction then screen  "Send transaction" is shown with prefilled values. 
* tap on Sign Later or "x" closes the screen and Unsigned tab with same tx is shown
* tap on Sign Transactions and provide valid password -> currently no "Transaction sent" screen shown. User sees Unsigned tab with wrong count and no transactions in the list, even if there are more items there. - separate bug TODO
* tap on Delete under Transaction -> deletes the transactin from the list. All other tx are also not shown, need to switch tabs to see them again - separate bug TODO

**Comment by annadanchenko** [comment]
tested in develop, will be in release 0.9.12
