### ISSUE TITLE
Wallet:Activity - Missing transactions in Activity tab

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19956]
@J-Son89 and @smohamedjavid should have more details on this. 

Some of transactions appear to be missing in Activity tab. 

I have checked my old account that has a long history of activity on Mainnet. 

**Expected result:** 

According to Etherscan 37 transactions have been performed on Mainnet https://etherscan.io/txs?a=0x527d22094166ad33e7523d2cbca287798e149c7f

**Actual result:** only 18 transactions have been fetched in Activity tab in Status Mobile app. At the same time, all 37 transactions are fetched on latest Desktop master app. 

[Status-debug-logs - 2024-05-09T173052.604.zip](https://github.com/status-im/status-mobile/files/15263570/Status-debug-logs.-.2024-05-09T173052.604.zip)

https://github.com/status-im/status-mobile/assets/97245802/937834b8-121c-4be4-b5e4-bef803a73323

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
moving to 2.31

**Comment by ulisesmac** [comment]
For unknown or unreliable data in the assets involved we should  implement these designs:
![image](https://github.com/user-attachments/assets/4c93154b-1c9e-475f-bafa-e75a53d7df4b)

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=16388-422969&t=QOSlHe5E91j2BSqo-4

**Comment by churik** [comment]
new tx activity is planned, so this issue will be closed as irrelevant 

cc @shivekkhurana

**Comment by shivekkhurana** [comment]
Closing the issue, as we intend to solve activities in a different way.
