### ISSUE TITLE
nice have: Navigate to profile screen from shown status

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1996]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to be able to navigate to profile screen of the person whose status I am viewing in Discover.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: When status is rendered in various Discover screens, it includes the display name and profile image of its author. When any of those is clicked, app should navigate to the author's profile screen. 

A similar feature already exists in Chat screens, but it is a bit specific to that use case and maybe depends on multiple events to populate app-db (when I tried to just dispatch the same event it sent me to an empty profile screen).

#### Expected behavior
When username or profile image are tapped, status author's profile is shown.

**Comment by jeluard** [comment]
It makes sense to consider #1592 when implementing this. We might also want to let deep links point to those profiles.

**Comment by oskarth** [comment]
@goranjovic FYI I connected PR with issue so board gets updated automatically with state of issue/PR

**Comment by annadanchenko** [comment]
1. Tap on profile image does nothing in Recent statuses list (Discover -> Recent Statuses -> All) and in Popular hashtags list  (Discover ->  Popular hashtags -> All). Would expect that user profile will be opened.
![screenshot_20171201-110310](https://user-images.githubusercontent.com/6584810/33478119-7d97f70a-d688-11e7-92d6-9ff792fec1de.png)

both real iphone 6s, iOs 10.3.3 and Pixel XL Android 8.0
build 6 for PR feature/status-navigate-author-1996. version  0.9.11d396 (1557.396)

from 00:21 https://app.testfairy.com/projects/4803590-status/builds/7178534/sessions/11/?accessToken=9Li1RT8RMB62dwV6EMLKcaMawNI

**Comment by annadanchenko** [comment]
2. If user taps on own username/picture then we show empty profile now.
![img-0775](https://user-images.githubusercontent.com/6584810/33500167-2c0258e0-d6d8-11e7-924f-044aab57f0e1.png)

from 00:11 https://app.testfairy.com/projects/4803590-status/builds/7178534/sessions/14/?accessToken=/qIpAA16Tomzj34kiIP9DbaMoA8
both iOs and Android

 I would expect: 
- we do not open anything for the user (it'll be not consistent) 
- we show the profile with all user data and some extra hint "It's you"

**Comment by goranjovic** [comment]
Fixed the bug from first screenshot.

The one from second screenshot (empty profile screen) is a side effect of another known bug - https://github.com/status-im/status-react/issues/2306

**Comment by oskarth** [comment]
@goranjovic Can this be closed?
