### ISSUE TITLE
Images bridged from Discord to Status app are displayed as links

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19979]
**Steps:** 

1. Join Status community on mobile
2. Send message containing image using Discord app
3.  See how image looks like in Status app

**Actual result:** link is displayed instead of image

**Message in Status app:**
![photo_2024-05-10 17 40 40](https://github.com/status-im/status-mobile/assets/97245802/ead7f240-2b22-4fc8-854b-2eb04dd68ea6)

**Same message in Discord app:**

<img width="821" alt="#mobile | Status - Discord 2024-05-10 17-38-24" src="https://github.com/status-im/status-mobile/assets/97245802/6fe15886-0561-4aaf-8b3e-db5fd94ac162">

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
it is OK to shown them as a links (the same on desktop), but link should be tappable, or show it as "Image" placeholder

**Comment by pavloburykh** [comment]
> it is OK to shown them as a links (the same on desktop), but link should be tappable, or show it as "Image" placeholder

FYI: for not tappable links there is a separate issue https://github.com/status-im/status-mobile/issues/19976

**Comment by cammellos** [comment]
Closing this then, as what we want to implement is tracked elsewhere
