### ISSUE TITLE
Render a shortened version of status in main Discover screen

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#1997]
### User Story

As a user I don't want my Discover screen real-estate to be monopolized by chatty status authors. Instead, I want too long statuses to be shown shortened to three lines and when or if I want to read all of it I can tap it and be redirected to the full status in author's profile screen.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

For example see: https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59ca26fd3db52a686d640e98

Depends on: #1996

**Comment by annadanchenko** [comment]
Discover feature is removed
