### ISSUE TITLE
Support Metamask address QRs

### ISSUE THREAD

**Issue by xAlisher** [status-im/status-react#19986]
**User Story**

As a Status app user, I want to be able to scan Metamask QR addresses, so I can send assets or save the address, if Status supports the network.

**Description**

Metamask stores addresses in QR codes with the following format:
ethereum:0x38cf6E0Ba4C4530735616e1Ee7ff5FbCB726fBd2@0xa

**ethereum:** - prefix described in [EIP-67](https://github.com/ethereum/EIPs/issues/67) 
**0xa** -  chain ID suffix described in [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)

Since Status addresses do not include these parts, we need to convert the data from Metamask QR addresses to a format our app can work with for sending, saving, and editing network preferences.

**Conversion**
1. **ethereum:** - prefix should be ignored and removed on our side

2. Status addresses follow the [EIP-3770](https://eips.ethereum.org/EIPS/eip-3770) format, which maps hexadecimal chain IDs to readable chain prefixes. 

| Name | EIP-155 (HEX) | DEC | EIP-3770 |
| ------------- | ------------- | ------------- | ------------- |
| Mainnet  | 0x1 | 1 | eth: | 
| Binance Smart Chain | 0x38 | 56 | bsc: | 
| Linea | 0xe708 | 59144 | linea: | 
| Polygon | 0x89 | 137 | matic: | 
| Arbitrum | 0xa4b1 | 42161 | arb1: | 
| Optimism | 0xa | 10 | oeth: | 

More networks: [chains_mini.json file on chainid.network](https://chainid.network/chains_mini.json)

After converting, **ethereum:0x38cf6E0Ba4C4530735616e1Ee7ff5FbCB726fBd2@0xa** should become **oeth:0x38cf6E0Ba4C4530735616e1Ee7ff5FbCB726fBd2**

This conversion should happen in all instances of scanning addresses, such as 
- universal scanner on home pages
- scanner for saving addresses in wallet settings
- scanner for sending

It should be implemented on all supported platforms.

If the address contains an unsupported network, the user should receive an error "Address contains unsupported network" Users should not be able to save addresses with unsupported network prefixes to avoid problems in the send flow and sending assets to wrong networks.

**Implementation.** 
1. Design cases for all relevant instances of QR scanner in Figma
2. Implement the conversion and validation logic 
3. Submit the feature for review and approval by the Status QA team 

**Acceptance Criteria**
 
- User scans Metamask QR addresses with relevant scanner instances
- Chain IDs are converted to prefixes according to EIP-3770
- ethereum: prefix is ignored and removed from address
- User receives a designated error for unsupported networks
- User can save addresses with supported and unsupported network prefixes

**Future Steps**
Consider supporting Metamask's "Payment request" QR format including additional data like requested amount and token ID.

**Comment by xAlisher** [comment]
**Designs**
Universal scanner - https://www.figma.com/design/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=9463%3A6641&t=wFbzKm9rir4nA4YV-1

Saving addresses - https://www.figma.com/design/QWJV5WRbroXVDsdubEDjAT/Wallet-settings-for-Mobile?node-id=2321%3A47009&t=P6QiIOmVtrEz40XJ-1

Sending:
- Scanner https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15915-403319&t=rsd5uduUCKyVBRzX-1

![image](https://github.com/status-im/status-mobile/assets/7700914/84acad3a-50a9-4d52-b3ba-b592be90ce05)


- Paste/type
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15363-64592&t=rsd5uduUCKyVBRzX-1
![image](https://github.com/status-im/status-mobile/assets/7700914/d0356b18-f0fa-4caf-97c4-26c09c28447c)

**Comment by xAlisher** [comment]
After discussing this issue with John  it needs to be updated. Hold on...

**Comment by churik** [comment]
put the label "blocked" when it is under the discussion

**Comment by xAlisher** [comment]
Issue discussed with John and updated.

**Comment by churik** [comment]
cc @J-Son89 should it be included in 2.30?

**Comment by J-Son89** [comment]
It does seem like something worth having, let's put it lower priority than the `high` priority bugs, but once we get through them we can look at it? wdyt? 🤔

**Comment by churik** [comment]
Yes, I think it is required feature to be honest, agreed

**Comment by churik** [comment]
postponed due to limited capacity for 2.30
