### ISSUE TITLE
Jump to overlaps last asset item in the list on Wallet screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19980]
Looks like leftover from https://github.com/status-im/status-mobile/pull/19732 cc @OmarBasem 

**Steps:** 

1. Login account with long list of assets
2. Open wallet tab
3. Scroll assets list to the bottom
4. Pay attention at Jump to button location

**Actual result:** 

https://github.com/status-im/status-mobile/assets/97245802/1076a6cc-17e0-47f8-a15d-df020ff23eff

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by OmarBasem** [comment]
@pavloburykh thanks for opening the issue. It is a regression from https://github.com/status-im/status-mobile/pull/19831

I can take it anyways 👍

**Comment by pavloburykh** [comment]
> @pavloburykh thanks for opening the issue. It is a regression from #19831
> 
> I can take it anyways 👍

Got it! Thanks a lot @OmarBasem!
