### ISSUE TITLE
Network label not displayed on wallet screens

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19998]
### Description: 
This issue occurs randomly. Unfortunately, there are no exact steps on how to reproduce this issue. Hope the logs might help

### Steps:
1. Go to wallet overview page

### Actual result:
The network label is not shown until page is reopened
![image](https://github.com/status-im/status-mobile/assets/52490791/46377293-a588-4925-b2d4-cd2054fa8c4b)

### Expected result:
The network label is not shown without wallet page reopening

![image](https://github.com/status-im/status-mobile/assets/52490791/bd274345-0501-4f06-95b7-60938c8261fb)

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/15296152/Status-debug-logs.2.zip)

### ENV:
Nightly 13 May 2024

**Comment by churik** [comment]
can't see it for quite a while, re-open if still relevant
