### ISSUE TITLE
[Android] Group Image can't be set up during group creation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19993]
Also, if you select/take a photo, the selected color will be reset once the group chat is created. 

### Steps:
1. Go to group creation flow
2. Set up image during group creation
3. Select color 
4. Check if the image is set up and the color is the same after the group is created

### Actual result:
The image for the group is not set up

https://github.com/status-im/status-mobile/assets/52490791/78ce5224-ed8c-4f39-9685-2daef9de02f5

### Expected result:
The image for the group is set up

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/15291219/Status-debug-logs.zip)

**Comment by qoqobolo** [comment]
There is also an issue with iOS which looks similar, although it can only be reproduced when you open your camera in the app for the first time:

1. Start creating a group chat
2. Add a group avatar by taking a photo with the camera
3. Select a color
4. Create the group (at this step you can see that the photo is not set and the color differs from one you selected)
5. Reopen the group chat (the photo and selected color are in place) 


https://github.com/status-im/status-mobile/assets/67952253/81d51df5-c2c9-420c-88d0-48cef202e032
