### ISSUE TITLE
Delay in iOS Performance during contact request acceptance

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19992]
### Problem: 
There is a noticeable delay in iOS performance, particularly when  accepting contact requests, and using the universal scanner. This delay is less pronounced on Android devices

### Steps:
1. Create a new user.
2. Receive a contact request and accept it.
3. Observe the duration of the contact request acceptance process.

### Actual result:
The performance on iOS is delayed contact acceptance, and universal scanner usage

Contact request acceptance

https://github.com/status-im/status-mobile/assets/52490791/e33894b2-d4e8-49ed-839b-55c628d759fc

### Expected result:
The performance should be smoother and without significant delays.

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (2).zip](https://github.com/status-im/status-mobile/files/15290999/logs.2.zip)

### ENV:
Nightly 13 May 2024

**Comment by Parveshdhull** [comment]
> There is a noticeable delay in iOS performance, particularly when logging in

Not only ios, it seems android is also taking a little more time than before while logging in.

**Comment by pavloburykh** [comment]
I have updated the issue and logged slow login bug separately https://github.com/status-im/status-mobile/issues/20059

**Comment by yqrashawn** [comment]
Hi @VolodLytvynenko, I can't reproduce this issue on my side, I'm able to accept contract request right after press the accept button.

The mobile and status-go log shows status-go can't find this contact in db. 
Do you remember how this contact request was made?

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko, I can't reproduce this issue on my side, I'm able to accept contract request right after press the accept button.
> 
> The mobile and status-go log shows status-go can't find this contact in db. Do you remember how this contact request was made?

Hi @yqrashawn, this issue was related to all contact requests received. But at the moment this is no longer reproducible for me.  @status-im/mobile-qa Please reopen this issue if it is still reproducible for you.
