### ISSUE TITLE
[EPIC] Implement missing UI components

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-react#19997]
- [x] #20081
- [x] #20088
- [x] #20089
- [x] #20090
  - [x] #20128
  - [x] #20129
  - [x] #20130

### New Variants/Changes
- [x] #20375
- [x] #20376
- [x] #20505
- [x] #20507

**Comment by churik** [comment]
@dlipicar all tasks are done, we can close this?

**Comment by dlipicar** [comment]
@briansztamfater ?

**Comment by briansztamfater** [comment]
We can close it, all needed UI components have been created and integrated. In case we need anything else, we can open a separate issue.
