### ISSUE TITLE
Address is shown with network prefixes  on 'Send To' page when valid ENS is entered

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20001]
### Problem: 
When entering a valid ENS (e.g., 'volodymyr.eth') on the 'send to' page, the address is shown with the preferred network prefix (e.g., eth:opt:) instead of without any prefix.

### Actual result:
The address is shown with the preferred network prefix after entering a valid ENS.
![image](https://github.com/status-im/status-mobile/assets/52490791/f267a005-7125-482d-af92-6724e704b41e)

### Expected result:
The address should be shown without the preferred network prefix after entering a valid ENS.

![image](https://github.com/status-im/status-mobile/assets/52490791/86ca33e2-2fb8-4b86-8c85-2e41d6c6c2b9)

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-192894&mode=design&t=UH4x1vm2Rv3yCLv8-0

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 13 May 2024

**Comment by OmarBasem** [comment]
@VolodLytvynenko I am facing a different bug. When I try to enter a valid ENS name I get error "It's not Ethereum address or ENS name". Are you getting the same error on latest develop?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I am facing a different bug. When I try to enter a valid ENS name I get error "It's not Ethereum address or ENS name". Are you getting the same error on latest develop?

hi @OmarBasem I haven't encountered this issue. I think the problem might occur if you enter a mainnet ENS address when the testnet is available, or if you enter a testnet ENS address when the mainnet is available. 
When the mainnet is enabled, I use the following ENS addresses and do not encounter the issue you mentioned
- volodymyr.eth
- ditest.stateofus.eth 
- pavlotest.eth

**Comment by J-Son89** [comment]
@OmarBasem, @VolodLytvynenko - what do you think about removing this issue from 2.30 with the intention that we likely move away from network preferences by the next release?
IT seems we have more critical issues to be focused on at this point!

**Comment by OmarBasem** [comment]
> @OmarBasem, @VolodLytvynenko - what do you think about removing this issue from 2.30 with the intention that we likely move away from network preferences by the next release? IT seems we have more critical issues to be focused on at this point!

I agree!

**Comment by VolodLytvynenko** [comment]
> @OmarBasem, @VolodLytvynenko - what do you think about removing this issue from 2.30 with the intention that we likely move away from network preferences by the next release? IT seems we have more critical issues to be focused on at this point!

@J-Son89 agree as well. I have moved it to 2.31. correct?

**Comment by churik** [comment]
Clearing milestone, as removing prefixes is planned in wallet, which makes this issue irrelevant
