### ISSUE TITLE
"Fallback Failed with 429 Too Many Requests" Error on confirmation transaction screen when assets of Arbitrium network attempts to be sent

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20009]
### Steps:
1. Recover user with available assets on Arbitrium Sepolia network
2. Attempt to send assets

### Actual result:
'Fallback failed with 429 too many requests' error is shown on the transaction confirmation page

https://github.com/status-im/status-mobile/assets/52490791/9405a12f-fa02-45f8-9aac-cf861d3b6a42

### Expected result:
No error

### NOTE:
The issue occurs both on testnet and mainnet arbitrium networks

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (5).zip](https://github.com/status-im/status-mobile/files/15304116/logs.5.zip)

**Comment by churik** [comment]
Not the case anymore, as ETH are sent in e2e in Optimizm Sepolia
