### ISSUE TITLE
Formalize requirements for SVG files we include in the app

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2001]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer I need to have a clear checklist of requirements for any SVG resources that need to be included in the app.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Documentation

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

We currently have some limits on what may or may not be used in a svg file in order for the app to work properly, e.g. transforms do not work at all. My understanding is that this is a limitation imposed by the svg library we are using.

We should list the steps we need to do in order to clean up and prepare svg files. Or alternatively, outline a different approach, e.g. maybe a script that does that automatically or something..

**Comment by flexsurfer** [comment]
https://wiki.status.im/Adding_new_icon_to_status-react

**Comment by goranjovic** [comment]
Haha, awesome :+1: Wiki Friday ftw
