### ISSUE TITLE
The providers for Arbitrum, Mainnet, Optimism are down

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20011]
### 

The providers for Arbitrum, Mainnet, Optimism are down are constantly down. 

- Balances are bieng updated only from time to time. 
- Routes are not found when trying to perform transaction 
- Error about network provider is down is constantly appearing 

[Status-debug-logs - 2024-05-14T135506.934.zip](https://github.com/status-im/status-mobile/files/15307318/Status-debug-logs.-.2024-05-14T135506.934.zip)

![photo_2024-05-14 13 53 37](https://github.com/status-im/status-mobile/assets/97245802/cc3996dc-cbfc-4fdd-bf5e-0efd66929d94)

https://github.com/status-im/status-mobile/assets/97245802/48c38d13-289c-42e1-bd87-ced25edef2ca

https://github.com/status-im/status-mobile/assets/97245802/3a36c731-24fe-4c38-8c2a-167dbc7de1d1

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by briansztamfater** [comment]
@J-Son89 What we should do with this issue? Any modification on the behavior for the toasts that we should do on our side or we should just wait for router changes to be completed?

**Comment by J-Son89** [comment]
So yeah, either way this will probably be solved. There is some discussions happening on how best to handle the rate limit problems so tbat should for the most part address the provider down toasts.
However saying that, I still think we should improve upon this solution to some degree as the app becomes extremely irritating once the providers are down and toasts are just rolling in 😅 .

Let's discuss among ourselves on some solutions that will work to show these toasts a lot less, or have some other easy way to display this to the user.

**Comment by churik** [comment]
Can be close in favour of proxy service, which is discussed here: https://github.com/status-im/infra-proxy/issues/1
