### ISSUE TITLE
Keyboard remains open on other app screens if some website is open in browser [Android]

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20017]
# Bug Report

## Problem 

This looks like an edge case, but maybe it's some kind of navigation regression and someone might want to take a look at it (maybe @Parveshdhull when you have some spare time?🙂).

### Reproduction

1. Open browser
2. Open any website 
3. Go to the `messages` screen
4.  `Add a contact`
5.  Set the cursor in the input field to open the keyboard
6. Close the `Add a contact` bottom sheet without minimizing the keyboard

The video below also shows that the issue is reproducible for the wallet account creation flow. 

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/63a8904c-dcf7-4948-a0a4-579a5bc3af81

#### Expected behavior

The keyboard is closed with the bottom sheet

### Additional Information

- Status version: nightly 14/05
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
@qoqobolo @Parveshdhull browser will be hidden soon no need to fix that

**Comment by qoqobolo** [comment]
Good to know, thanks @flexsurfer 🙏
@Parveshdhull from your perspective, is the root cause in browser, that is, could a similar problem appear somewhere else? If not, feel free to close it

**Comment by Parveshdhull** [comment]
hi @qoqobolo, Thank you for reporting the issue.

I didn't tested the issue, but I think I know why it might be happening.

When add contact screen is closed in the first case, then text-input looses the focus and closes keyboard.
But in second case we have two text-input, So even if add contact screen is closed, browser input still remains in focus and keeps keyboard open.

So if we are disabling the browser, I think its ok to close issue.
