### ISSUE TITLE
[Wallet - Send to] "Paste" and "Scan" buttons instead of "Remove" button when focus is in the input field

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20014]
# Bug Report

## Problem 

If you set focus in the input field, then when the cursor appears, the `Paste` and `Scan` buttons will appear there.
If you delete at least one character the button will change to `x` (`Remove`). 
This behavior seems incorrect. Probably the desired result would be for the  `Paste` and `Scan` buttons to change to `x` as soon as you place the cursor into the field so you can clear the field with one tap.

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/e60ac2d5-879f-4768-a4f8-19b5ef0ca12b

#### Expected behavior

Unfortunately, I couldn't find a design for this particular case, so attaching the closest one. Let me know if designers' opinions are needed here

https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=689-192881&m=dev

<img width="1104" alt="Screenshot 2024-05-14 at 14 43 41" src="https://github.com/status-im/status-mobile/assets/67952253/4ddc7d43-09ce-462b-a263-24e68479f47e">

<img width="395" alt="Screenshot 2024-05-14 at 14 44 05" src="https://github.com/status-im/status-mobile/assets/67952253/f1f6d2e0-c7fd-4a33-89b1-bca900ae49e1">

### Reproduction

1. Go to the `Send` flow
2. Enter/paste some text into the `Send to` field
3. Tap an empty space on the screen to remove the cursor
4. Tap the field again to set the cursor

### Additional Information

- Status version: nightly 14/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
fixed in this PR https://github.com/status-im/status-mobile/pull/20005
