### ISSUE TITLE
Check community discovery entries

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20030]
@flexsurfer reported seeing extra communities in the Opened tab on communities home (Status Inu community)

Whoever pick up this issue should try to replicate, and close if it's not able. He used a recovered account, that might be the reason. He doesn't remember whether he clicked previously on the Status Inu community, but he thinks he didn't.

We confirmed that the contract returns the right communities.

Here the initial description:

```
Currently we show more communities that we should in both the "Opened" tab on communities home, and the discovery screen.

In the "Opened" tab, we should only show the communities a user has actually clicked on (with the possible exception of the Status community).

In the discovery section, it should only show communities that have been included (not the ones that there are still being voted on for inclusion).

Whoever picks this up, should make sure that the behavior of the app is correct (i.e check which ones are included in discovery, and check that is correctly reflected in the app).
```

**Comment by pavloburykh** [comment]
Hey @cammellos! Looks similar to what I have reported here https://github.com/status-im/status-mobile/pull/19905#issuecomment-2107408002 In my case I see Status old community within Opened tab. 

We (@qfrank and me) decided it is not a blocker cause it happens only to users who have backed up some old community. I also have user for reproduction so feel free to ping me up for a seedphrase whoever will be working on this issue.

**Comment by cammellos** [comment]
I think this can be closed, most likely due to recovered accounts
