### ISSUE TITLE
Filter github hooks by branch and send discord webhook messages

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#20034]
We would like to send discord webhook messages whenever there is a push on a branch that starts with `release/.*`

Most of the work to filter and send the webhook messages is already done in this repo https://github.com/status-im/github-webhook-filter. What remains to is make sure that the code is updated to filter push on release branches and to send a discord hook message to a discord channel

**Comment by cammellos** [comment]
@jo-mut is this completed? if so you can close it, thank you

**Comment by jo-mut** [comment]
yeah this task is done, I will close it
