### ISSUE TITLE
Display missing key pairs in wallet settings

### ISSUE THREAD

**Issue by seanstrom** [status-im/status-react#20033]
# Feature Issue

### User Story

As a user,
I want to be able to see any of my missing (not imported) key pairs and accounts inside the wallet settings.

### Description 
Implement the initial UI for displaying the missing (not imported) or un-operable key pairs and accounts.

### Designs

Figma flow: [the Figma designs](https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=232-32244&t=3gekg5HDrRdVjAye-4)

### Notes

* The designs for importing missing key pairs include an "import" button. This feature is not in scope for this issue and will be tracked in a separate issue.
* The designs for importing missing key pairs include an action menu for each missing key pair. This feature is partially in scope because we already support renaming and removing key pairs. The other features related to importing the key pair will be tracked in a separate issue.

### Acceptance Criteria

| Screen | Description |
|--------|--------|
| ![Wallet Settings](https://github.com/status-im/status-mobile/assets/2845768/aca10927-f553-4255-bcd8-9aaf9fa451aa) | Users can choose to view the key pairs and accounts settings (inside wallet settings) by pressing on the "Key pairs and accounts" menu button. |
| ![Missing Key Pairs and Accounts](https://github.com/status-im/status-mobile/assets/2845768/1614620d-0f10-44d6-b162-299ce2696f04) | Users should be able to see any missing key pairs and accounts. Missing key pairs and accounts would exist on other devices but not on the current device. |
| ![Missing Key Pairs and Accounts Action Menu](https://github.com/status-im/status-mobile/assets/2845768/2ffef02c-edc4-4cb5-8fcb-77a9a7f89405) | Users should be able to open the action menu for a missing key pair. |

**Comment by seanstrom** [comment]
Hey @smohamedjavid 👋 
I have a question about how we could potentially detect which key pairs are not imported.

Should we check all the accounts for which ones are not `operable`, and then find their related key-pair and consider that as technically a "missing" key-pair?

**Comment by smohamedjavid** [comment]
Yes, @seanstrom - In other words

```
if any of the accounts in a key pair is NON OPERABLE 
    The whole key pair will be NON OPERABLE.

if any of the accounts in a key pair is PARTIALLY OPERABLE 
    The whole key pair will be PARTIALLY OPERABLE.

else key pair is FULLY OPERABLE
```
