### ISSUE TITLE
Details overlapping on Wallet Send screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20039]
# Bug Report

#### Expected behavior

https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=220-148036&t=qIeoFmxPkmCAMFt1-0

<img width="239" alt="Screenshot 2024-05-15 at 14 51 59" src="https://github.com/status-im/status-mobile/assets/147824399/7c3d8730-edd4-4eab-8355-aee6f2a6cba0">

#### Actual behavior
<img width="331" alt="Screenshot 2024-05-15 at 14 48 54" src="https://github.com/status-im/status-mobile/assets/147824399/a489b38d-a7ab-42f7-86af-204583a9a9d6">

Full page 
<img width="328" alt="Screenshot 2024-05-15 at 13 33 13" src="https://github.com/status-im/status-mobile/assets/147824399/bedf4697-9ab1-41a4-b382-973bb4ddccb9">

### Reproduction

1. Install app
2. Login to app as user with a balance
3. Go to wallet
4. Send some tokens to another user

### Additional Information

- Status version: nightly 15/05
- Operating System: Android
- Device: Samsung A34 (14.0)

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
@J-Son89 we currently display the address instead of the user's name. Is displaying the user's name out of scope?

**Comment by J-Son89** [comment]
Thanks @OmarBasem - it seems this page needs design input for smaller screens right (sorry if that's already mentioned)

I think we should have the page looking perfect for addresses, once that's all working we can add support for the account names, saved addresses and contacts etc.
I would say this part is lower priority though.

**Comment by J-Son89** [comment]
Or is the designs 'recipient gets ...' because that is much easier and the address is already in two places on the page

**Comment by OmarBasem** [comment]
@J-Son89 "Recipient gets ..." sounds good to me

**Comment by OmarBasem** [comment]
@J-Son89 looking at the designs again, I am wondering what's the point of that part. Even what the recipient gets is already mentioned. I think displaying the time and max fees would be enough in that block

**Comment by J-Son89** [comment]
Yeah that's true, can you raise this with design. It will help with the smaller screen issues too
