### ISSUE TITLE
Adjust onboarding illustration size to fit smaller iOS screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20038]
# Bug Report

## Problem 

Here's what the illustrations look like on the iPhone SE after removing parallax

![image](https://github.com/status-im/status-mobile/assets/67952253/9cb6fdcd-86bf-45e9-8c39-1a7ffc3f9f07)

![image](https://github.com/status-im/status-mobile/assets/67952253/d93a44d2-99a4-4cd5-b4b0-c9c91792a7c7)

#### Expected behavior

iPhone 12 mini

<img width="323" alt="Screenshot 2024-05-15 at 14 47 20" src="https://github.com/status-im/status-mobile/assets/67952253/7cf03da9-f193-45a3-8741-888459efee88">

<img width="324" alt="Screenshot 2024-05-15 at 14 47 33" src="https://github.com/status-im/status-mobile/assets/67952253/65bca43d-2dfa-4972-afe2-defe40d78d5b">

### Additional Information

- Status version: https://github.com/status-im/status-mobile/pull/20026
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
cc @J-Son89

**Comment by ilmotta** [comment]
@qoqobolo, is this issue related to the problem you reported recently in this comment? https://github.com/status-im/status-mobile/pull/20506#issuecomment-2180930670 If it is, then this issue's scope can be adjusted to account for Android devices as well.

**Comment by qoqobolo** [comment]
> @qoqobolo, is this issue related to the problem you reported recently in this comment? [#20506 (comment)](https://github.com/status-im/status-mobile/pull/20506#issuecomment-2180930670) If it is, then this issue's scope can be adjusted to account for Android devices as well.

Thanks @ilmotta , you're right, they're pretty much the same issue, I just forgot about this logged one 🤦🏻

I'll close it in favor of https://github.com/status-im/status-mobile/issues/20518 and will add there the `Enable biometrics` screen.
