### ISSUE TITLE
Don't rely on the master key when generating accounts under the bip 0044 path m/44'/60'/0'/0/0

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20048]
Currently we use the master key to derive addresses under the `bip 0044` path.

This key is not stored in v1 accounts, so the wallet root key m/44'/60'/0'/0/0 should be used instead and relative path should be derived.

### V1 

https://specs.status.im/spec/2 this is how the old account worked.

On creation we would store 4 keys in the keystore file directory:

1) Root chat key
2) Root wallet key
3) Generated chat key
4) Generated wallet key

When deriving a new wallet account, we would derive from 2).

### V2

On creation v2 stores 5 keys in the keystore file directory:
1) Master key
2) Root chat key
3) Root wallet key
4) Generated chat key
5) Generated wallet key

When generating a new account, it will derive from 1). This will not be possible for user upgrading the app, as 1) is not stored.

We should instead change the code to generate from 3) (same as v1) if the path is non-custom

**Comment by qfrank** [comment]
close this as it's done
