### ISSUE TITLE
Discover: initial account status is missing on Discover screen in specific scenario [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2004]
### Description

*Type*: Bug

*Summary*: On Discover screen I don't see the initial status for account which was set up prior the account was added to someone's contacts

#### Expected behavior
Status list is updated real time on discover screen for all the participants

#### Actual behavior
Contact B can see his own hastag and A's hashtag. Contact A can see only its own hash tag.

### Reproduction

Use 2 Android devices. 
- On device 1: create an account (for ex. account A)
- On device 2: create an account (for ex. account B)
- Set up hashtag for Account A
- Set up hashtag for Account B
- As Account B add Account A to contacts
- As Account A add Account B to contacts
- Pay attention to the Discover screen for Account A

**Screenshot for Account B**
![image](https://user-images.githubusercontent.com/28752642/31175320-94fa9608-a917-11e7-8d53-90925b1d4336.png)

**Screenshot for Account A**
![image](https://user-images.githubusercontent.com/28752642/31175337-a92b46a4-a917-11e7-8464-b050e73148a1.png)

### Additional Information
* Status version: 0.9.10-162-gcede0957+
* Operating System: Android

**Comment by goranjovic** [comment]
This turns out to be by design. Any statuses posted before accounts A and B added each other do eventually get sent (every 10 minutes). So they will get there, just not instantly as it is the case after they become friends and add each other.

**Comment by goranjovic** [comment]
By design
