### ISSUE TITLE
[EPIC] Mobile Wallet Crypto Recurring Purchases

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-react#20051]
Desktop equivalent: https://github.com/status-im/status-desktop/issues/14791

Figma: https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=1581-361927&t=RryynEYhIAsIWI2V-0

### Description
Implement recurring crypto purchases.

## UI Components
- [x] #19804

## Mobile Client
- [x] #19836
- [x] #20072
- [x] #20390

**Comment by ajayesivan** [comment]
Closing as complete!
