### ISSUE TITLE
Syncing/Sync failed screens are missing illustrations

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20068]
For now, we should remove the red box from both, until we get under 100MB and then revisit.

### ISSUE 1 Syncing screen missing illustration

![photo_2024-05-16 16 14 16](https://github.com/status-im/status-mobile/assets/97245802/32e7c13a-cc49-4b16-9fad-cba29e7e02e4)

### ISSUE 2 Syncing failed screen missing illustration

**Actual result:** 

![photo_2024-05-16 16 43 58](https://github.com/status-im/status-mobile/assets/97245802/8399b0cd-98fe-4fc3-852e-e8d21c86382b)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
From discord: `let's just remove both for the time being, until we get the app to < 100MB`
