### ISSUE TITLE
Collectibles transactions are not successful when ethereum sepolia network is used

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20062]
### Steps:
1. Restore the user with some available collectibles on Sepolia
2. Turn on the test
3. Send collectible (Any type: erc-721 or erc-1455)

### Actual result:
The sending process page is shown, but the collectible transaction is not successful 
![image](https://github.com/status-im/status-mobile/assets/52490791/3b547bac-abf8-4708-8767-91849fcac161)

### Expected result:
Collectible is sent succesfully

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (6).zip](https://github.com/status-im/status-mobile/files/15334482/logs.6.zip)

**Comment by churik** [comment]
put low-prio, as it is testnet only
