### ISSUE TITLE
Sending page displayed after confirming transaction in bridging/collectibles sending/tokens sending flows

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20067]
### Description:
After completing a transaction in the bridging, collectibles sending, or tokens sending flow, the sending page is displayed. The sending page should be descope from these flows 

### Steps:
1. Recover user with available assets
2. Go to tokens or collectibles sending flow or bridging
3. Confirm the transaction

### Actual result:
The sending page is shown after the transaction is confirmed
![image](https://github.com/status-im/status-mobile/assets/52490791/e708ca42-254c-4d72-bca6-04c2fb3aad46)

### Expected result:
The user should be navigated to account account page after transaction is confirmed
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=14511-223181&t=XX61jV5jlsljPPLc-0

### ENV:
- Nightly 16 May 2024

**Comment by churik** [comment]
removed in https://github.com/status-im/status-mobile/pull/19984
