### ISSUE TITLE
"Discover communities" is not loading or loading exteremely slowly

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20092]
# Bug Report

## Problem 
The issue is not reproducible on status-desktop, so need investigation how it is loaded on desktop side; 
it is reproducible on latest ststus-go version (in https://github.com/status-im/status-mobile/pull/20060)

If it gets loaded once, it stays in the curated communities directory.

#### Expected behavior
can see communities

#### Actual behavior
![image](https://github.com/status-im/status-mobile/assets/4557972/c6806075-5b5d-4cf2-91f9-788a5d0620e6)

### Reproduction

1. Create new account
2. Open Discover communities

### Additional Information

- Status version: nightly 17/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
Logs: [logs (83).zip](https://github.com/status-im/status-mobile/files/15348882/logs.83.zip)
```
ERROR[05-16|15:00:21.027|github.com/status-im/status-go/protocol/messenger_curated_communities.go:49]                                       failed to get curated communities from contract error="fallback failed with 'Post \"https://optimism-goerli.infura.io/v3/40ec14d9d9384d52b7fbcfecdde4e2c0\": dial tcp: lookup optimism-goerli.infura.io: no such host'. run error was 'Post \"https://optimism-goerli.infura.io/v3/40ec14d9d9384d52b7fbcfecdde4e2c0\": dial tcp: lookup optimism-goerli.infura.io: no such host'"
```

**Comment by flexsurfer** [comment]
can't repro in the latest develop

**Comment by churik** [comment]
@flexsurfer 

Reproducible for me on fresh profiles on the latest nightly.
As I mentioned, it is reproducible for new users usually and if it was opened and loaded once, after that the issue will be not reproducible.


https://github.com/status-im/status-mobile/assets/4557972/2a932bfe-dc4c-4022-a95f-efa3242aec7a

**Comment by yqrashawn** [comment]
The domain `optimism-goerli.infura.io` is no longer live
infura deprecated goerli and switched to sepolia https://www.infura.io/blog/post/deprecation-notice-for-all-infura-supported-goerli-endpoints


![Image](https://github.com/status-im/status-mobile/assets/15090582/560c8f0d-4e4f-4af3-80d5-8a2c1cc12fe1)

**Comment by yqrashawn** [comment]
[status-go code](https://github.com/status-im/status-go/blob/4a1a29b6a5ccf5e87ee9f3ff956904d8d3e5d2fb/protocol/messenger_curated_communities.go#L94) where chooses optimism goerli for curated communities query

directory contract address on different networks (only op mainnet and goerli) https://github.com/status-im/status-go/blob/4a1a29b6a5ccf5e87ee9f3ff956904d8d3e5d2fb/contracts/directory/address.go#L13



question:

- deploy this contact on op sepolia 
  - who is responsible for deploying this contract

- or use rpc server from other provider for op goerli
  - I saw there's `grove.city`, so we can use that one?

**Comment by churik** [comment]
@yqrashawn thank you for taking this!
Maybe the best people to ask are the desktop team, as it is working on their side?

**Comment by cammellos** [comment]
@churik @yqrashawn from what I can see, it should work if testnet mode is not enabled, is that correct?

**Comment by churik** [comment]
@cammellos unfortunately, it doesn't really depend on that

On nightly Testnet is disabled by default, and issue is still there

**Comment by yqrashawn** [comment]
Current behavior

- create account
- turn off testnet mode and login
- discover community infinite loading
- logout then login
- discover community showing status community

**Comment by yqrashawn** [comment]
mainnet
daily relay limit
`ERROR[05-28|01:45:59.280|github.com/status-im/status-go/protocol/messenger_curated_communities.go:49]                                              failed to get curated communities from contract error="fallback failed with '401 Unauthorized: project id required in the url\n'. run error was 'endpoint xxxxxx has passed its daily relay limit'"`
