### ISSUE TITLE
Wallet: do not rely on default gas

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2009]
### User Story

As a developer I want to control default gas used when calling `sendTransaction`. This allows to provide better feedback to users and provide consistent experience across `web3` providers.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

#### Expected behavior

When sending ethers a warning should be displayed if user balance is lower then amount + gasPrice * gas.

**Comment by kylerchin** [comment]
+1
