### ISSUE TITLE
Wallet - "Send to" flow after pressing “Confirm bridge”

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20106]
# Bug Report

## Problem 

The user is redirected to the `Send to` page after pressing `Confirm bridge` instead of the bridge confirmation page. 
UI is broken when going back to the amount page. 

#### Expected behavior

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=10232-108495&m=dev

<img width="1787" alt="Screenshot 2024-05-20 at 11 29 31" src="https://github.com/status-im/status-mobile/assets/67952253/917b8aaf-907a-4a6e-b1cd-253bdfe83fc2">

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/5d180d73-eba1-48b3-aff9-2f5ba183bef4

### Reproduction

1. Open wallet
2. Open an account
3. Press `Bridge`
4. Select asset
5. Select network
6. Enter amount
7. Press `Confirm bridge`

### Additional Information

- Status version: nightly 20/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@ulisesmac - maybe this is a duplicate ? I'll assign you for now just to block it but please close the issue if not, or lmk and I can this if you don't plan to do this 👍

**Comment by ulisesmac** [comment]
@J-Son89 
Thanks for assigning it to me!

Yeah, I'm solving this, since I'm fixing the bridge flow for both "wallet home" and "account overview" entry points :+1:

**Comment by J-Son89** [comment]
Bridging flow is also wrong from the home page. We can handle this separately though if that suits better?

https://github.com/status-im/status-mobile/assets/22799766/74577f67-7e9b-4666-a604-0b7c65730843

**Comment by ulisesmac** [comment]
> Bridging flow is also wrong from the home page. We can handle this separately though if that suits better?
> 
> https://github.com/status-im/status-mobile/assets/22799766/74577f67-7e9b-4666-a604-0b7c65730843
> 
> 
> 

Hey @J-Son89 
I'm about to open the PR and the flow you are showing is being fixed there too 👍
