### ISSUE TITLE
fix(wallets): no routes render on input amount

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#20111]
Fixes the issue noted here https://github.com/status-im/status-mobile/pull/19953#issuecomment-2120331458 introduced by this PR https://github.com/status-im/status-mobile/pull/19953.

"No routes found" is rendered every time there is an invalid amount:
<img width="350" src="https://github.com/status-im/status-mobile/assets/18485527/51610e56-0bb6-4d75-8138-10393e6fcda7">

It should only be rendered based on the flows in [1](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=14748-115594&t=lQvwHHeejDvtoUFB-0) and [2](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=14748-115593&t=cm5o3qlBgSmYQwo3-0)

**Comment by vkjr** [comment]
@BalogunofAfrica, I think it would be convenient if the problem details were moved from a linked comment to the description section of this issue, wdyt?

**Comment by BalogunofAfrica** [comment]
> @BalogunofAfrica, I think it would be convenient if the problem details were moved from a linked comment to the description section of this issue, wdyt?

Yeah makes sense. I have updated the description.
