### ISSUE TITLE
No banner if user updates preferred networks during Account editting

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20116]
# Bug Report

### Reproduction

1. Install app
2. Go to `Wallet`
3. Open `Account` -> `Edit Account`
4. Tap on preferred networks
5. Make some changes there
6. Tap `Confirm` button

#### Expected behavior
Network Preferences should close.
"Account network preferences has been updated" banner appeared on Edit Account screen
<img width="244" alt="Screenshot 2024-05-20 at 18 18 42" src="https://github.com/status-im/status-mobile/assets/147824399/5474ef08-fb65-4620-8058-fdd3bdef9aa7">

https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=838-215786&t=7eZAR4CmYPv5Je2n-0

#### Actual behavior
No "Account network preferences has been updated" banner

### Additional Information

- Status version: nightly 20/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
@mariia-skrypnyk I do get a banner when I follow the above steps. Are you still able to reproduce this issue?

**Comment by OmarBasem** [comment]
I think this issue can be closed. If someone thinks otherwise feel free to reopen

**Comment by mariia-skrypnyk** [comment]
Sorry for a long answer @OmarBasem !

Thanks for checking, banner is working fine now!
