### ISSUE TITLE
No Delivered status for sent and delivered messages in group chats

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20126]
# Bug Report

### Reproduction

1. Install app
2. Create a group chat or use the existing one
3. Send any text message
4. Wait for some time to see the Delivered status

#### Expected behavior
Delivered message appears right after Sent when message is really delivered

#### Actual behavior
No Delivered status. Only Sent status is present.
<img width="251" alt="Screenshot 2024-05-21 at 11 04 29" src="https://github.com/status-im/status-mobile/assets/147824399/6274b236-003b-48f3-b428-3e42fa8e4191">

### Additional Information

- Status version: nightly 21/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vitvly** [comment]
Some findings:
1. Have been investigating the message delivery flow, added unit tests and logs to verify in https://github.com/status-im/status-go/tree/fix/group-chat-message-delivery. 
2. Could be that https://github.com/status-im/status-go/pull/4962 is related
3. Trying to ascertain it via testing against different status-go versions.

**Comment by vitvly** [comment]
Having finally resolved ios build issues, was able to verify 2 and 3 - it's a different status-go issue. Continuing debug.

**Comment by vitvly** [comment]
Not reproducible in latest develop, after pulling the latest changes from yesterday.

**Comment by vitvly** [comment]
Just verified that it is this commit that fixed delivery status for group chats: https://github.com/status-im/status-go/commit/0061c563f2d50679d812c5dc2978a96c49a93314

**Comment by vitvly** [comment]
Fixed with https://github.com/status-im/status-mobile/pull/20255
