### ISSUE TITLE
Wallet UI stucks after disabling available network on Sending screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20136]
**Steps:** 

1. Open sending page of some asset that has funds only on part of networks. For example SNT
2. Enter valid amount
3. Disable available network, in case of SNT - disable Mainnet
4. Oberve the result

**Actual result:** UI stucks, unable to select another network or edit input value

https://github.com/status-im/status-mobile/assets/97245802/75bd0295-b938-4056-81f0-00f1ffa4b26e

**Expected result:** I am not sure about expected result as I still hardly understand our current logic of networks selection. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by briansztamfater** [comment]
@pavloburykh should be fixed here #20112 

The expected behaviour should be the one described in #19910 

Something like this:

https://github.com/status-im/status-mobile/assets/18485527/22b85208-449e-450a-9bec-9e1cac537892
