### ISSUE TITLE
Wallet - incorrect "+" button position on the key pair selection page

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20158]
# Bug Report

#### Actual behavior

<img width="389" alt="Screenshot 2024-05-23 at 12 26 00" src="https://github.com/status-im/status-mobile/assets/67952253/09ff3432-bcc2-4e68-98fb-a69fd1d7b038">

#### Expected behavior

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=2052-520783&t=kyxYIZI9sxY0LmCP-4

<img width="306" alt="Screenshot 2024-05-23 at 12 27 22" src="https://github.com/status-im/status-mobile/assets/67952253/1fa6bd2a-31f2-468e-9092-98f2feee4c10">

### Reproduction

1. Open wallet
2. Press `Add account`
3. On the account creation page press `Edit` in `Origin`
4. Check the `+` button position

### Additional Information

- Status version: nightly 23/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ulisesmac** [comment]
@seanstrom :eyes:
