### ISSUE TITLE
Only show the Wallet Connect requests for the logged in user

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20155]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to only see the connection/signing requests on the status profile/account that was connected, so that I can correctly proceed with signing/connecting.

### Description

An edge case, where if the user connected to a dapp on status profile A and logs out, then logs in to status profile B, they shouldn't see the request triggered by profile A's session. But, when logging back into profile A, the user should see the request.

### Acceptance Criteria

- [ ] The user can see only the requests that were created within the profile that initiated the session
- [ ] The user can see no requests from other profiles' sessions
- [ ] The user can see the request from the other profile once they login with the appropriate profile

**Comment by alwx** [comment]
This one is actually already done in this PR: https://github.com/status-im/status-mobile/pull/20711

**Comment by smohamedjavid** [comment]
@alwx - Thanks for the update 🙏 

I checked the latest [build 9](https://github.com/status-im/status-mobile/pull/20711#issuecomment-2220604883) from your PR https://github.com/status-im/status-mobile/pull/20711 and the requests initiated from another user's session (User B) are shown to User A.

<img width="200" src="https://github.com/user-attachments/assets/966abb66-c35c-4365-95ac-8fca211d5f89" />

I guess that we need to handle it on the `:wallet-connect/on-session-request` event by checking whether the address in the request belongs to the user. Thoughts?

**Comment by clauxx** [comment]
> @alwx - Thanks for the update 🙏
> 
> I checked the latest [build 9](https://github.com/status-im/status-mobile/pull/20711#issuecomment-2220604883) from your PR #20711 and the requests initiated from another user's session (User B) are shown to User A.
> 
> <img alt="" width="200" src="https://private-user-images.githubusercontent.com/19339952/348767501-966abb66-c35c-4365-95ac-8fca211d5f89.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzIwMjYsIm5iZiI6MTcyMTEzMTcyNiwicGF0aCI6Ii8xOTMzOTk1Mi8zNDg3Njc1MDEtOTY2YWJiNjYtYzM1Yy00MzY1LTk1YWMtOGZjYTIxMWQ1Zjg5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMjA4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGVkMjAyYWViYWEwMmRiMDcyOGMxNDJkMjJlYjRjMDYwZGE3MGVhNjdlN2UwYjI1NTllNmFkNTY1MjZjZmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AdD2lq_CJxSnlnqlMBYBccUEc3YbCeohE4Oj6h-APmc">
> I guess that we need to handle it on the `:wallet-connect/on-session-request` event by checking whether the address in the request belongs to the user. Thoughts?

thanks for testing it 🙏, I believe @alwx should've fixed it now in the latest commits.
