### ISSUE TITLE
"Import key pair using recovery phrase" flow issues

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20168]
# Bug Report

## Problem 

Now, when trying to complete the `Import key pair using recovery phrase` flow, an alert appears at the last step

<img width="266" alt="Screenshot 2024-05-24 at 10 55 41" src="https://github.com/status-im/status-mobile/assets/67952253/4c8565e7-ecd8-4c6e-92ea-98545a0da055">

Potential reason for the alert: https://github.com/status-im/status-mobile/pull/19747

Also, after discussion, it turned out that the `Import key pair using recovery phrase` flow itself should be redone, since even before the alert appeared it was not working correctly.
Please let me know/open a separate issue for that if needed

#### Expected behavior

Import key pair using recovery phrase works as expected

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/485f473c-e46e-413a-ba4e-59272a77b015

### Reproduction

1. Open wallet
2. Add account > Edit
3. Press `+` on the `Key pairs` page
4. Press `Import key pair using recovery phrase`
5. Enter recovery phrase
6. Press `Continue`
7. Enter key pair name
8. Press `Continue`

### Additional Information

- Status version: nightly 24/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
@ulisesmac @smohamedjavid 
tagging you both here because I'm not sure which team should take care of this: Wallet Core or Wallet Settings.
Please add the appropriate label if needed, thanks!

cc @J-Son89

**Comment by J-Son89** [comment]
'Core' can take it 🙏
