### ISSUE TITLE
[wallet] Scientific notation is shown for small amounts in transaction history and unsigned transactions list

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2016]
### Description

<img width=320 src=https://user-images.githubusercontent.com/1181225/31222265-d816a2c4-a9c6-11e7-9133-43bff53e9291.png />

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Send a transaction with an amount of 0.0000001 ETH

### Solution

Use ```(money/wei->str :eth amount)```

**Comment by yenda** [comment]
Already fixed on latest develop

**Comment by annadanchenko** [comment]
Fixed for release 0.9.12, verified in develop  0.9.10-179-g3225d1a2
