### ISSUE TITLE
Wallet -Improve lmage loading on Collectibles Overview Page

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20179]
Currently the collectibles loading transition is not so smooth.
Implement some improvement to this screen.

Also the "Can't fetch" variants are not displaying correctly at all and we need to display the correct variant when this happens.

The solution can be implemented similar to the collectible list item component which handles a similar usage to both of these.

**Can't fetch not correct**

https://github.com/status-im/status-mobile/assets/22799766/a510d9a0-fa96-4814-aadb-437c73d8a7be

**Current loading on overview page**

https://github.com/status-im/status-mobile/assets/22799766/3b809863-ac47-48c7-864d-0fc8a1bc55ee

**Comment by ulisesmac** [comment]
@J-Son89 Could you please provide the figma links to what screen and component are you referring to?
Thank you!

**Comment by J-Son89** [comment]
sure!

**Comment by BalogunofAfrica** [comment]
@ulisesmac Would the loading/transition state also be addressed as noted in the duplicate issue

https://github.com/status-im/status-mobile/issues/20103

> - there should be some loading/ transition on collectible overview page

**Comment by ulisesmac** [comment]
> @ulisesmac Would the loading/transition state also be addressed as noted in the duplicate issue
> 
> #20103
> 
> > * there should be some loading/ transition on collectible overview page

Hey @BalogunofAfrica 
I'm not adding a loading transition since we may need design feedback and currently we are focusing on other areas.
