### ISSUE TITLE
Wallet - Cursor disappears from the amount field when you start typing

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20186]
# Bug Report

## Problem 

It appears again if you set the focus on the field by tapping it.
Introduced in https://github.com/status-im/status-mobile/pull/20099

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/48a33a25-a0ac-4779-b085-096557c94a32

#### Expected behavior

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=8598-295077&t=7ZyEezNjwk194yV4-4

<img width="215" alt="Screenshot 2024-05-27 at 16 48 48" src="https://github.com/status-im/status-mobile/assets/67952253/f657c8d1-7a92-46a1-b907-b395d9d78a69">

How it worked before:

https://github.com/status-im/status-mobile/assets/67952253/91306e9e-aff8-48fe-8fd7-a4138dc862e1

### Reproduction

1. Go to `Send` / `Bridge` 
2. Start typing in the amount field
3. Pay attention to the cursor 

### Additional Information

- Status version: nightly 27/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
moving to 2.31 as low priority

**Comment by vkjr** [comment]
Closing because we don't have cursors anymore
