### ISSUE TITLE
No opacity on the text on inactive buttons on the dark-themed screens

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20185]
# Bug Report

## Problem 

The text looks white instead of slightly grey when the button is in inactive state

#### Actual behavior

<img width="313" alt="Screenshot 2024-05-27 at 10 36 17" src="https://github.com/status-im/status-mobile/assets/67952253/5dfaa7f0-38c4-43f8-8245-df05e8a8eb1d">

<img width="312" alt="Screenshot 2024-05-27 at 10 36 35" src="https://github.com/status-im/status-mobile/assets/67952253/34bbbe64-bf14-4e49-9419-b1a1f85c7f5b">

#### Expected behavior

https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-89599&t=3v4WIrMchj6zOxZa-4

<img width="315" alt="Screenshot 2024-05-27 at 10 39 47" src="https://github.com/status-im/status-mobile/assets/67952253/ef4199e9-2778-48f1-842d-1041329d6929">

### Reproduction

Check the dark-themed screens in the app, e.g. on onboarding (name, password screens), enable biometrics screen in settings, etc

### Additional Information

- Status version: nightly 27/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
i believe it was changed here https://github.com/status-im/status-mobile/issues/20056

**Comment by flexsurfer** [comment]
cc @qoqobolo
