### ISSUE TITLE
Replace listview with flat-list in Discover screens

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2019]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to rely on a single efficient list implementation

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Refactor

*Summary*: This issue is a subset of #1840 restricted specifically to views in Discover module. This issue is also a subset of #1874

**Comment by oskarth** [comment]
Not Discover specific and refactor only issue, closing in favor of https://github.com/status-im/status-react/issues/1840 which encompasses it.

cc @goranjovic
