### ISSUE TITLE
Reduce apk size to less < 100MB

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20195]
As a user,
I want to be able to get updates of the status app through the playstore
So that I can benefit from the new features

### Description

Currently the app size is > 100MB. We need to make it smaller in order to be able to release to the play store. 
There's a few open issues on this:

https://github.com/status-im/status-mobile/issues/20075

https://github.com/status-im/status-go/issues/5146

After these two are closed, we should re-evaulate and close if necessary.

**Comment by flexsurfer** [comment]
it seems like both tasks have been implemented, this is mobile PR for torrents https://github.com/status-im/status-mobile/pull/20393

should we re-evaulate and close? cc @cammellos

**Comment by cammellos** [comment]
@flexsurfer thanks, yes, if it's all merged and we are happy, we can close this

**Comment by ilmotta** [comment]
The result for Android is ~94MB, which is just shy of 100MB. @cammellos, @flexsurfer, @Samyoul, @siddarthkay do you think there's any other relatively low-hanging fruit to pick to reduce the APK size even further to give us more room to spare?

I'm just slightly worried about being too close to the threshold and then finding in a future release, in a very inconvenient moment, that we went a little over the 100MB mark and are blocked.

If no low-hanging fruits are left to pick, do you have any other idea about what to attack in case we need in the future?

**Comment by flexsurfer** [comment]
just looked at our current release in stores and it's 102Mb, most of which libgojni.so, we pack it 4 times, so I'm not sure there is something we could attack

**Comment by ilmotta** [comment]
> just looked at our current release in stores and it's 102Mb, most of which libgojni.so, we pack it 4 times, so I'm not sure there is something we could attack

Closing this issue because we are under 100MB and we don't have low-hanging fruits left to pick. Thanks @flexsurfer 👍

**Comment by cammellos** [comment]
It looks like it's gone above 100MB https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F2.30.x/ 
reopening, it'd be probably wise to think about how to test it, although seems a bit tricky.

**Comment by cammellos** [comment]
cc @ilmotta

**Comment by ilmotta** [comment]
@cammellos By testing do you mean having a step on the CI to block merges that increase the APK size beyond 100MB?

@siddarthkay do you have a rough idea of how feasible that would be?

**Comment by cammellos** [comment]
> @cammellos By testing do you mean having a step on the CI to block merges that increase the APK size beyond 100MB?
> 
> @siddarthkay do you have a rough idea of how feasible that would be?

Ideally yes, or at least we want to identify the commit that introduces the issue

**Comment by siddarthkay** [comment]
> step on the CI to block merges that increase the APK size beyond 100MB?

That should be fairly easy to implement

**Comment by ilmotta** [comment]
> > step on the CI to block merges that increase the APK size beyond 100MB?
> 
> That should be fairly easy to implement

I'll create the issue then @siddarthkay 👍🏼 not because we should do this improvement now necessarily (although that would be good of course), but to avoid this cat and mouse game after 2.30.

**Comment by siddarthkay** [comment]
Thanks @ilmotta : I made this PR -> https://github.com/status-im/status-mobile/pull/20683 and noticed that PR builds are still under 100 MB?
ref -> https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fandroid/detail/PR-20683/3/pipeline/121
so must be something weird with the build made from release branch...

**Comment by ilmotta** [comment]
@cammellos, with @siddarthkay's PR https://github.com/status-im/status-mobile/pull/20683 in `develop`, if builds continue to pass after that it means we can close this issue again. Does that make sense to you?

**Comment by cammellos** [comment]
we need to figure out probably why it's above 100MB in release, since that's the only build that we need to be less < 100MB, or we understood what the issue is?

**Comment by ilmotta** [comment]
@siddarthkay, with the PR https://github.com/status-im/status-mobile/pull/20683 merged, can we now close this issue?

**Comment by siddarthkay** [comment]
Yes, we can consider this as done.
