### ISSUE TITLE
[IOS] "No protocol method IMap" error is shown when 'OpenSea' button is tapped on collectible detailed page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20207]
### Steps:
1. Open any collectible
2. Tap 'OpenSea' button
3. Swipe back 

### Actual result:
The error is shown
![image](https://github.com/status-im/status-mobile/assets/52490791/87e5094c-ba54-4848-835a-f91d466001b6)

### Expected result:
"No protocol method IMap"  error is not shown

### OS: 
IOS

### Devices:
- iPhone 11 Pro Max, IOS 17
### Logs
[logs.zip](https://github.com/status-im/status-mobile/files/15467712/logs.zip)

**Comment by mmilad75** [comment]
This is the same issue as https://github.com/status-im/status-mobile/issues/20177 which is solved in https://github.com/status-im/status-mobile/pull/20193

**Comment by ulisesmac** [comment]
@mmilad75 Thanks for reporting
