### ISSUE TITLE
Empty screen when opening I'm new to Status screen after closing Sing in screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20213]
**Steps:** 

1. Open fresh installed app
2. Open Sign in screen and quickly close it
3. Open I'm new to Status screen
4. Observe the result

**Actual result:** empty screen is opened. 

https://github.com/status-im/status-mobile/assets/97245802/64b4c510-0613-48ee-8fef-8693878eed86

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by qoqobolo** [comment]
probably related https://github.com/status-im/status-mobile/issues/17499
