### ISSUE TITLE
Wallet - hide old wallet Dapp 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#2021]

**Comment by annadanchenko** [comment]
On 1st run (right after creating account):

go to Chats and see no Wallet (it's OK)
go to Contacts and see Wallet in Contacts (it's not OK). Would expect that there is no Contact "Wallet"
https://app.testfairy.com/projects/4803590-status/builds/6822809/sessions/4/?accessToken=4myVLunuFNF6A3-AV/QvuaD2h9M
both iOS and Android,  0.9.11d208

**Comment by asemiankevich** [comment]
Tested in `0.9.11d209-1557.209`: Both Android and iOS look good to me
1. No wallet contact
2. No wallet chat
3. Old wallet is not used when sending txns in 1x1 or group chat
4. Old wallet contact/chat is not shown when upgrade
5. No wallet chat created when sending txn from new wallet
