### ISSUE TITLE
Unable to open collectible detailed page after backgrounding

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20229]
### Description:
After adding watch-only accounts containing a sufficient amount of collectibles, attempting to open any collectible's detailed page after being in the background for 3-5 minutes does not work.

### Steps:
1. Add watch only account with a sufficient amount of collectibles: (example: `0x8d51191dd7e371bd88ab9797b11b03da3084de6e`, `0x8d2413447ff297d30bdc475f6d5cb00254685aae`) 
2. Relogin to fetch all collectibles
3. Background the app for 3-5 minutes.
4. Return to the collectibles section.
5. Attempt to open any collectible's detailed page.

### Actual result:
The collectibles detailed page is not opened

https://github.com/status-im/status-mobile/assets/52490791/46c636e8-0d52-4a6f-88d6-b6e1c79457a5

### Expected result:
A collectible detailed page is opened

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/15480962/Status-debug-logs.2.zip)

**Comment by ulisesmac** [comment]
@VolodLytvynenko 

Maybe no other functionality that depends on Status go is available too, not only the collectibles.
Do you know if everythig else is working (e.g. the send flow, creating an account, etc).

Currently, we navigate to the collectible page once we receive the data, so if we aren't navigating it's because we get no response from Status go (we should improve the navigation condition).

CC: @cammellos do you know if this is a known problem?

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac Today, I tried to reproduce this issue several times with different accounts and amounts of collectibles, but was not successful. It seems the issue is resolved, possibly after the Status Go update. Previously, it was easy to reproduce. I am closing it for now.

Hi @pavloburykh. I remember you faced this problem too. If you encounter this issue again, please reopen it. Thank you.

**Comment by VolodLytvynenko** [comment]
Unfortunately, the issue is reproducible again. Hope logs might help


https://github.com/status-im/status-mobile/assets/52490791/11b8f978-5429-4ab1-a619-a1c414a9ee24

### Device:
iPhone 11 Pro max, IOS 17

### logs
[logs (3).zip](https://github.com/user-attachments/files/15838584/logs.3.zip)

**Comment by ulisesmac** [comment]
Hi @VolodLytvynenko 

I'm taking this issue, but it'd be great if you also confirm if other functionality depending on Status go is available or not.

Thank you

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac Yes, messages work well in this case, as does other Status Go functionality (sync, account creation). Interestingly, this issue only occurs on Android devices. I have never encountered it on iOS

**Comment by ulisesmac** [comment]
> Hi [@ulisesmac](https://github.com/ulisesmac) Yes, messages work well in this case, as does other Status Go functionality (sync, account creation). Interestingly, this issue only occurs on Android devices. I have never encountered it on iOS

@VolodLytvynenko Thank you, I'll check it.

The video is recorded on iOS, so I guess it is affecting both platforms
