### ISSUE TITLE
Wallet: Can't scan white QR codes using wallet QR scanner

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2023]
### Description

*Type*: Bug

*Summary*: Can't scan white QRs using new wallet QR scanner

#### Expected behavior
I can scan any QR code using new wallet QR scanner

#### Actual behavior
Can't scan white QRs

### Reproduction

- Open Status
- Go to Wallet
- Click Send  and scan white QR (or Request-> scan generated white QR)

I can scan this
![image](https://user-images.githubusercontent.com/28752642/31232488-ae0197f6-a9f2-11e7-9235-66d486440441.png)

And can't scan those white qrs
![image](https://user-images.githubusercontent.com/28752642/31232530-d7beec88-a9f2-11e7-94c7-0ba15aed4aaf.png)

![image](https://user-images.githubusercontent.com/28752642/31232537-e1598db6-a9f2-11e7-9794-31b1cd73bb7e.png)

### Additional Information
* Status version:  0.9.10-163-ga7950af3+ (1720)
* Operating System: Android, iOS
* TF https://app.testfairy.com/projects/4803622-status/builds/6726661/sessions/20/?accessToken=rwv/44y0B9XmFngUwQeMd7Yx9vo

**Comment by jeluard** [comment]
I tried using `imToken` and `toshi` on my device and they can't read white qr code while it works fine for black ones.
