### ISSUE TITLE
Error when tap on Terms of use during Onboarding flow

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20239]
# Bug Report

### Reproduction

1. Install app
2. Tap on Terms of use on Intro screen

#### Actual behavior
Cannot set property 'reagent-compiler2' of null error
<img width="328" alt="Screenshot 2024-05-29 at 11 57 33" src="https://github.com/status-im/status-mobile/assets/147824399/859bd070-847e-4486-b206-21f99b213b0d">

#### Expected behavior
<img width="253" alt="Screenshot 2024-05-29 at 11 55 51" src="https://github.com/status-im/status-mobile/assets/147824399/ca8fb394-f3b4-4707-8af2-dff98557f244">

https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-88185&t=jQQHDemuPVlCtWel-0

[status_logs.zip](https://github.com/status-im/status-mobile/files/15482634/status_logs.zip)

### Additional Information

- Status version: release 2.29 and nightly 28/05
- Operating System: Android/iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
We can link to the github desktop terms for the hotfix, and fix properly afterward https://github.com/status-im/status-desktop/blob/master/ui/imports/assets/docs/terms-of-use.mdwn , just make sure it's a permalink.
