### ISSUE TITLE
[EPIC] Integration for native Swap

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-react#20246]
- [x] [SPIKE] Identify issues

UI components
- [x] #20291
- [x] #20300
- [x] #20331
- [x] #20332
- [x] #20333
- [x] #20335
- [x] #20336
- [x] #20334
- [x] #20330

Business logic
- [x] #20380
- [x] #20337
- [x] #20338
- [x] #20339
- [x] #20340
- [x] #20342
- [x] #20271
- [x] #21296
- [x] #20341
- [x] #20343
- [x] #20381
- [x] #20344
- [x] #20345
- [x] #21309
- [x] #21310
- [x] #21342
- [x] #21362

**Comment by alwx** [comment]
All the sub-issues were closed and since it's an umbrella issue, I'm closing it as well.
