### ISSUE TITLE
[Android] Some collectibles' names are not fetched on Android devices

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20256]
### Steps:
1. Add the address `0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e` as a watch-only address.
2. Check the names of collectibles 

### Actual result:
Collectibles names are not fetched for some collectibles
![image](https://github.com/status-im/status-mobile/assets/52490791/d7be07f4-4adc-463a-b14d-8487310c5968)

### Expected result:
The names of some collectibles are not fetched.

Same collectibles on IOS devices
![image](https://github.com/status-im/status-mobile/assets/52490791/cd736550-63b1-47b3-b03e-bc76af96811d)

### OS: 
Android

### Devices:
- Pixel 7a, Android 13
- Android studio emulator: Pixel XL API 33

### Logs
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/15488090/Status-debug-logs.2.zip)

**Comment by ulisesmac** [comment]
@VolodLytvynenko I think this has been solved in 
- #20657

Could you please confirm?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I think this has been solved in
> 
> * [[#20463] Multiple fixes on Collectibles #20657](https://github.com/status-im/status-mobile/pull/20657)
> 
> Could you please confirm?

@ulisesmac Thank you for an update. The issue is not reproducible. Can be closed
