### ISSUE TITLE
wallet: improve loading after login

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20265]
Currently the initial loading of the wallet on login goes as follows.

It starts off balance 0
then goes to loading state 
and then loaded (see video)

Expected: It should just go straight to loading state

see:
https://github.com/status-im/status-mobile/assets/22799766/9d1dd661-64ab-4caf-bc5d-8fce6d45ecf3

**Comment by OmarBasem** [comment]
@J-Son89 probably for a different issue, I think we also need to improve the loading time. It takes long before it shows any information. I think we currently fetch all the accounts data in `initialize` which is unnecessary. I think we need to fetch in initialize the data that would be displayed on the home screen, and then fetch each account's data when opened (or delay it until home screen's data is fetched)

**Comment by J-Son89** [comment]
> @J-Son89 probably for a different issue, I think we also need to improve the loading time. It takes long before it shows any information. I think we currently fetch all the accounts data in `initialize` which is unnecessary. I think we need to fetch in initialize the data that would be displayed on the home screen, and then fetch each account's data when opened (or delay it until home screen's data is fetched)

agreed @OmarBasem - I think that involves some investigation and document what is currently happening there and then we need to plan out how we can best improve that. Can you create an issue to handle that spike? 🤔

**Comment by OmarBasem** [comment]
> > @J-Son89 probably for a different issue, I think we also need to improve the loading time. It takes long before it shows any information. I think we currently fetch all the accounts data in `initialize` which is unnecessary. I think we need to fetch in initialize the data that would be displayed on the home screen, and then fetch each account's data when opened (or delay it until home screen's data is fetched)
> 
> agreed @OmarBasem - I think that involves some investigation and document what is currently happening there and then we need to plan out how we can best improve that. Can you create an issue to handle that spike? 🤔

Done https://github.com/status-im/status-mobile/issues/20275
