### ISSUE TITLE
Scrollbar is shown in the middle of the page (IOS only)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20268]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/4557972/3a819a54-bda9-4570-98dd-b32d8d838fc8

#### Expected behavior
Scrollbar is not overlapping with chat view

### Reproduction

1. Open chat with a long history
2. Start scrolling in the area of user avatars (left) 
3. If still can't see the issue - reopen community > chat view, it is not reproducible every time, but in general quite easily

### Additional Information

- Status version: nightly 30/05/24 (and allegedly release 2.29)
- Operating System:  iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
im unable to replicate on ios simulator

**Comment by churik** [comment]
Descoped; seems to be specific to IOS or device (in my case it is IPhone 14 Pro, IOS 17.4.1)

**Comment by pavloburykh** [comment]
> Descoped; seems to be specific to IOS or device (in my case it is IPhone 14 Pro, IOS 17.4.1)

@churik @flexsurfer prioritising this issue, as it seems to be dependent on the fetched content in community channel. It is indeed not reproducible in every chan. 

I am able to reproduce this issue in this community in general channel https://status.app/c/ixSACigKDm5ldyBjb21tIDMxIDA1EgZkYXNkYXMYASIHIzQzNjBERioDAAUGAw==#zQ3shPeHsqFDjTUkna1WKwDcHS2zGrDg9bkbS5d7Li3kCkwvr


**Steps:** 

1. Open given community
2. Wait for some time for data to be fetched (at least 30 seconds)
3. Go to general channel
4. Scroll the history
5. Observe the result


https://github.com/status-im/status-mobile/assets/97245802/e4524d7d-4c42-4845-8b9e-35af2e7be549

**Comment by flexsurfer** [comment]
unfortunately unable to replicate even in this channel
![image](https://github.com/status-im/status-mobile/assets/11790366/dc91356d-3aba-42bd-b134-eb042afe69c9)

**Comment by flexsurfer** [comment]
https://stackoverflow.com/questions/73974494/react-native-scroll-bar-in-the-middle-of-the-screen

`Adding scrollIndicatorInsets={{ right: 1 }} within FlatList properties worked fine for me` lets try this change
