### ISSUE TITLE
Valid swap proposal

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-react#20271]
Depends on https://github.com/status-im/status-mobile/issues/20340
https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=47-68307&t=X2bJJ4L19W3S1mbS-0

Covers the "Not enough gas" scenario and the happy path
![image](https://github.com/status-im/status-mobile/assets/11161531/f3c1270e-2317-4a78-94d3-017ca7f0e353)

![image](https://github.com/status-im/status-mobile/assets/11161531/d19811f7-2a66-447a-86d6-a743134999fd)

**Comment by briansztamfater** [comment]
This is mostly already implemented, the no gas fee case will be covered in #21261
