### ISSUE TITLE
wallet. - remove goerli support

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20273]
We no longer need support for testnet Goerli, remove all uses of it 👍

**Comment by churik** [comment]
@shivekkhurana why this issue is added to 2.31, maybe I missed something or it was added by mistake?

**Comment by churik** [comment]
Postponed for the next release due to time constraint and no steps to reproduce. 

cc @ilmotta @shivekkhurana

**Comment by friofry** [comment]
fixed by @saledjenic in status-go https://github.com/status-im/status-go/pull/5945

Keeping this issue for possible changes required in status-mobile.

**Comment by smohamedjavid** [comment]
If no one is working on removing Goerli-related code on mobile, I can pick this up 👍
