### ISSUE TITLE
Rejecting Wallet Connect requests and sessions

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20288]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I would like to be able to reject a session/request, so that the dapp is aware of the interaction state and the user can continue using it.

### Acceptance Criteria

- [ ] the session/request should be rejected when the user presses the `x` button in the navigation header
- [ ] the session/request should be ignored when the user dismisses the sheet by dragging it down
- [ ] the dapp should show the rejected state when the user rejects the session

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by xAlisher** [comment]
Just for reference 

![image](https://github.com/status-im/status-mobile/assets/7700914/8f04d7b2-9cc7-42b2-8070-46a08ebcfdc8)

**Comment by shivekkhurana** [comment]
There are two aspects to feature:
1. Rejecting requests as shown in Alisher's comment and
2. Rejecting session proposals
