### ISSUE TITLE
App crashes when attempting to build a new route on the routes generation page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20287]
Unfortunately, I can't find the exact steps to reproduce this issue. It seems to happen randomly without any pattern when a new value is entered or if some network is enabled or disabled to generate new routes. I hope the logs might provide more insight into what's going on.

### Steps:
1. Recover user with an available token on at least 2 networks (I used ETH token).
2. Go to the routes generation page.
3. Input an available value.
4. Make some changes to the receiver's preferred networks to build a new route or input a new value.

### Actual result:
The app is crashed

### Expected result:
The app is not crashed

### Devices:
- Pixel 7a, Android 13

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/15512636/Status-debug-logs.zip)

### ENV:
Nightly [31 May 2024]

**Comment by VolodLytvynenko** [comment]
can't reproduce it anymore(

**Comment by VolodLytvynenko** [comment]
I just got an error again when trying to build a new route.   Again without exact steps. Hope the DEBUG logs can help.
The same issues happened to @qoqobolo

### Device:
Pixel 7a, Android 13

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/15777436/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
I've encountered the same issue on the desktop
[logs routes crash desktop.txt](https://github.com/user-attachments/files/15881445/logs.routes.crash.desktop.txt)

**Comment by vkjr** [comment]
@VolodLytvynenko, was this issue ever encountered on iOS? or it is an Android-specific one?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko, was this issue ever encountered on iOS? or it is an Android-specific one?

@vkjr I will try to investigate. I don't remember crashes on IOS

**Comment by vkjr** [comment]
@VolodLytvynenko, I've tested the scenario on Android simulator and physical device (Galaxy A23) and wasn't able to reproduce is. So closing this one as we were discussing.
cc @J-Son89
