### ISSUE TITLE
Biometric settings issues

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20293]
# Bug Report

**ISSUE 1:** [iOS] Extra screen appears when user should approve his face

### Reproduction

1. Install app
2. Go to your Profile -> Password
3. Tap on switcher with FaceID/Fingerprint

#### Actual behavior

https://github.com/status-im/status-mobile/assets/147824399/9c05bcdb-d0bc-4fed-bd6e-284a77801cbd

#### Expected behavior

face id check should appear above Password screen and not on extra white/black screen

<img width="220" alt="Screenshot 2024-05-31 at 16 09 31" src="https://github.com/status-im/status-mobile/assets/147824399/085064e3-b917-4404-8c61-390669495043">

https://www.figma.com/design/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?node-id=6638-397016&t=UdfCPzSt6muyZlkB-0

**ISSUE 2:** [Android] Switcher doesn't turn on when user approves his fingerprint 

*issue reproduces in case you didn't allow biometric permission on onboarding and go to Profile -> Password settings to turn biometry for the firs time

#### Expected behavior

switcher should be turned on and green

<img width="231" alt="Screenshot 2024-05-31 at 16 11 09" src="https://github.com/status-im/status-mobile/assets/147824399/39d0a6f9-9295-4a98-940b-a997fbae3c28">

### Additional Information

- Status version: release build 31/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Hey @mariia-skrypnyk, would be good to avoid GH issues with multiple ISSUEs because it makes categorizing the issues and prioritizing them more difficult. In this example, ISSUE 1 wouldn't be considered a bug, but rather labeled `ui-polish` because the functionality still works. ISSUE 2 on the other hand seems to be a real bug. Could you split this issue in two? Thank you 👍🏼

**Comment by mariia-skrypnyk** [comment]
Thanks @ilmotta for highlighting it.

Will do.

**Comment by mariia-skrypnyk** [comment]
**ISSUE 1: [iOS]** Extra screen appears when user should approve his face - **doesn't exist on nightly anymore** 🙌 
**ISSUE 2: [Android]** Switcher doesn't turn on when user approves his fingerprint - **doesn't exist on nightly anymore** 🙌
