### ISSUE TITLE
Fetching  unread messages from community directory leads to unread notifications and counters prior joingin or opening community

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20294]
# Bug Report

## Problem 
This behavior differs from the status-desktop. 
Once we open the profile on status mobile and log in, the app automatically fetches all messages from all communities in a community directory, which leads to:
- unread counter on the tab 
- in case "everyone" mention in community channels - unread badge and notification in activity centre

Discussion is [here](https://discord.com/channels/1210237582470807632/1217172571917647932/1246093240915070997)

#### Expected behavior
no new messages before I open this community manually

#### Actual behavior
all community messages are shown in unread badges/activity centre
https://github.com/status-im/status-mobile/issues/18584

### Reproduction

1. Create new profile
2. Log in

### Additional Information

- Status version: release 2.29 
- Operating System: Android, iOS

![IMAGE 2024-05-31 16:08:44](https://github.com/status-im/status-mobile/assets/4557972/4de2b787-8543-41bc-888c-6575161d8ed4)

[logs (87).zip](https://github.com/user-attachments/files/15514832/logs.87.zip)

**Comment by cammellos** [comment]
Fixed both in release & develop
