### ISSUE TITLE
Long-press message/chat preview is missing

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20312]
# Bug Report

## Problem 

We should display a message/chat preview on long press. 

### Reproduction

1 - Message
1. Send a message
2. Long press on the message

2 - Chat
1. Open the home screen
2. Long press on the chat 

3 - Reactions
1. Send a message
2. Add a reaction
3. Long press on the reaction

#### Expected behavior

https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447-349773&t=Oz48qhdeErsOTl7W-4

https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1803-400893&t=Oz48qhdeErsOTl7W-4

https://www.figma.com/design/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2869-259157&t=zFLgxEKPDjeSSnGu-4

<img width="327" alt="Screenshot 2024-06-03 at 17 49 05" src="https://github.com/status-im/status-mobile/assets/67952253/8f593416-87ba-4dbc-a4ee-20f05079702d">

<img width="325" alt="Screenshot 2024-06-03 at 17 49 24" src="https://github.com/status-im/status-mobile/assets/67952253/be9c099a-df74-4048-ab36-ecf47ded80dd">

<img width="438" alt="Screenshot 2024-06-03 at 17 51 51" src="https://github.com/status-im/status-mobile/assets/67952253/d90218c8-6b80-4951-b0ea-67916c96691b">

#### Actual behavior

<img width="315" alt="Screenshot 2024-06-03 at 17 48 37" src="https://github.com/status-im/status-mobile/assets/67952253/dad888a7-4819-46ea-9089-ed37f3baa68f">

<img width="392" alt="Screenshot 2024-06-03 at 17 51 05" src="https://github.com/status-im/status-mobile/assets/67952253/5c0b9f2d-ad6a-493c-b000-574568c733af">

<img width="394" alt="Screenshot 2024-06-03 at 17 52 46" src="https://github.com/status-im/status-mobile/assets/67952253/fe6ba5ac-fba6-4576-b0d8-15582d6d7a8f">

### Additional Information

- Status version: RC 2.29 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
this happened [before](https://github.com/status-im/status-mobile/pull/19630#pullrequestreview-2049414985) and was fixed by removing overflow hidden in bottom sheet here https://github.com/status-im/status-mobile/pull/19630/files#diff-3106cb7d6b9fa0b0c3f3a96271519c0b7a076d993ecb87fe34dd5c0dd529bd7bL11
