### ISSUE TITLE
[iOS] Can't navigate back from a community channel if opened by tag 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#20313]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
User is navigated back to the community channels list

#### Actual behavior
White screen is shown, after that we need to restart the app 

https://github.com/status-im/status-mobile/assets/29711298/c392850f-22ea-4918-9365-b85bc811917e

### Reproduction

1. Create 2 or more channels in a community (channel-A and channel-B)
2. Navigate to the channel-A and send a message tagging #channel-B 
3. Click on the message with the channel tag to navigate to the channel-B
4. Click back button being inside the channel-B

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
probably regression from https://github.com/status-im/status-mobile/pull/20069

**Comment by Parveshdhull** [comment]
Quick solution might be just navigate back before navigating to other chat.
(Issue might be caused because we are pushing chat screen twice, and on navigating back we navigate to empty chat)

**Comment by qoqobolo** [comment]
@jo-mut the issue is only reproducible on iOS
