### ISSUE TITLE
Remove identifier section from onboarding

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20314]
As a user
I want to go straight from generating keys -> enable notifications without going through the identifier section
So that I can start using the app as soon as possible

### Description

In an effort to simplify the onboarding, we should move from Generating keys screen, directly to Enable notifications https://www.figma.com/design/3XXfGrRNGl36GkrdicFQod/Design-Explorations?node-id=13934-59303&t=kExExKDKwuYu7UAc-4 
The identifier section therefore can be removed

**Comment by ilmotta** [comment]
Hey @yqrashawn, given that you are assigned to the issue but it's in the `Iteration Backlog`, should it go to `In Progress` instead? If not, could you unassign yourself?

**Comment by yqrashawn** [comment]
Sure I'm not started
