### ISSUE TITLE
Transaction is sent right after tapping on send button (no Send Transaction screen shown)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2031]
### Description

*Type*: Bug

*Summary*: No Send transaction screen is shown if send transaction in 1-1 chat. Right after tap on send button there is screen Transaction Sent shown. This issue happens only if previously user sent a transaction from new Wallet.  No issue happens and expected Send Transaction screen is shown if send feature in the new Wallet was not used.

#### Expected behavior
For send command with valid parameters in 1-1 chat: After tap on send button there is screen Send Transaction shown with pre filled data (recipient and amount)
#### Actual behavior
User sees Transaction Sent screen after tapping on send button.

### Reproduction
from 00:26 https://app.testfairy.com/projects/4803590-status/builds/6748397/sessions/3/?accessToken=GoxijWt4cjjsCaKT23q7jfY-eIU
- Open Status
- Open new Wallet
- send some ether to Jarrad from new Wallet
- open 1-1 chat with Jarrad
- tap on send command, select Jarrad as recipient, type valid amount and tap on send button

### Additional Information
* Status version: 
- develop build 0.9.11d171 and 
- PR branch `feature/sign-transaction-in-chat-and-remove-old-wallet` 0.9.11d168
* Operating System: 
Real device iPhone 7 plus, iOs 11.0.2
Real device Google Pixel XL, Android 8.0

**Comment by asemiankevich** [comment]
Works fine on Android `0.9.10-207-gae5b3863+` both 1x1 and group chat

**Comment by annadanchenko** [comment]
Tested OK on iOS `0.9.11d207` 1-1 chat, group chat, DApp transaction
