### ISSUE TITLE
Asset to Pay selection drawer (From Setup Swap screen)

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#20333]
Implement Asset to Pay selection drawer

https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=76-130105&t=DgFnr1o1B4N17NwC-1

![image](https://github.com/status-im/status-mobile/assets/19279756/c0f00578-b813-4f90-b00a-922f0a922403)

Dependency #20380

**Comment by alwx** [comment]
Taking this one to work on it together with https://github.com/status-im/status-mobile/issues/20380
