### ISSUE TITLE
Autorefresh swap proposal

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#20341]
Every 15 seconds the swap proposal needs to be recalculated.

We need to implement this logic and be sure it is reflected on the UX with the proper loading states

Depends on https://github.com/status-im/status-mobile/issues/20271

**Comment by J-Son89** [comment]
it would be nice to have a description of what this issue entails. perhaps why it's needed, how this should look, how often it should auto refresh etc 👍
