### ISSUE TITLE
find alternative to react-native-camera-kit

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#20346]
# Problem

`react-native-camera-kit` is not compatible with new architecture on Android and the library maintainers have expressed that implementing support for the new architecture is not in their roadmap/interest.

ref -> https://github.com/teslamotors/react-native-camera-kit/issues/537

I have opened a thread in react-native working group to see if I can generate any interest from react-native team to send a PR for react-native-camera-kit enabling support for new architecture on Android.

ref -> https://github.com/reactwg/react-native-new-architecture/discussions/167#discussioncomment-9674242

However we must find alternatives to this library since we can not rely on them to add support and this blocks our migration to new architecture on Android.

# Way forward

- Experiment with : https://github.com/mrousavy/react-native-vision-camera or any other library which has support for new architecture.
- Once a suitable library is found, remove `react-native-camera-kit` and update usages with the new library from previous step.

**Comment by mrousavy** [comment]
Try react-native-vision-camera :)

**Comment by siddarthkay** [comment]
@mrousavy : `react-native-vision-camera` is indeed one of the options we are considering.
I plan to do a quick experiment with it and see how it behaves with new architecture.

Thank you.

**Comment by siddarthkay** [comment]
update : we no longer need to change the camera library because we were able to move to new architecture on android with the help of : https://github.com/reactwg/react-native-new-architecture/discussions/135
ref -> https://github.com/status-im/status-mobile/pull/20950
