### ISSUE TITLE
Activity list

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#20345]
Integrate activity items of type Swap in Activity list
![image](https://github.com/status-im/status-mobile/assets/11161531/65c5de67-514a-4080-8223-8d42b9e22968)

**Comment by alwx** [comment]
Server currently doesn't provide swap activities.
After the server does that, implementing this feature is very trivial: we would simply need to add a branch in `status-im.subs.wallet.activities/process-activity-by-type` that handles activities with type `wallet-activity-type-swap` and then add a UI function to `status-im.contexts.wallet.common.activity-tab.view`. Can be done in less than 1 hour but the precondition is that the go side actually needs to send us activities with type swap (`3`)

**Comment by churik** [comment]
Moving to the next milestone because of limited capacity in 2.31 and the fact that feature is blocked

**Comment by shivekkhurana** [comment]
Will be handled in #19849 

Closing this issue as it's managed better there, and ready to be tested.
