### ISSUE TITLE
Wallet: Error message for wrong address scanned/copied is shown on wrong screen [1991]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2035]
### Description

*Type*: Bug

*Summary*: We need to show error message on the same screen where error appears.  Like if I am scanning wrong QR or pasting invalid value from clipboard I dont want to get back to previous screen - just show error message and when I click OK I can scan again.

#### Actual behavior
Error message is shown on next screen

![image](https://user-images.githubusercontent.com/28752642/31272148-9fd742a2-aa92-11e7-8dc0-88b14ae1aca2.png)

### Reproduction

- Open Status
- Click send in New wallet
- Scan QR with invalid content
- Paste invalid content from clipboard

### Additional Information
* Status version: PR ` 0.9.10-172-gcc632d90+ (1729)`
* Operating System: Android, iOS

**Comment by oskarth** [comment]
@asemiankevich @rasom can this be closed?

**Comment by asemiankevich** [comment]
@oskarth closing
