### ISSUE TITLE
No fetching / fetched community screens

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20354]
# Bug Report

## Problem 
Most likely regression from https://github.com/status-im/status-mobile/commit/53d32ed6b1216e5f03a242d71cff1bcd69b0c407 

#### Expected behavior
"Fetching" -> "Failed to fetch"

![IMAGE 2024-06-05 14:16:33](https://github.com/status-im/status-mobile/assets/4557972/5e86c9d6-e9ca-4da3-a351-0242f3df00fc)

#### Actual behavior
![IMAGE 2024-06-05 14:16:42](https://github.com/status-im/status-mobile/assets/4557972/d56a437a-b909-4966-9d6f-610b862eaf14)

https://github.com/status-im/status-mobile/assets/4557972/4f6c2f73-2c6a-40d7-8c34-2a9b619be50c

### Reproduction

1. Open community that has failed to fetch (i.e. https://status.app/c/iw6AChwKCWNvbW11bml0eRIEYXNkZhgBIgcjODhCMEZGAw==#zQ3shfeXdHMVQJtF1s2PL9SfmPgC57eeeUR2i4MSSpW4xpoZU )

### Additional Information

- Status version: release 2.29 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
```
2024-06-05T12:59:41.260Z ERROR [status-im.contexts.communities.events:318] - {:message "Failed to spectate community",
 :error {:code -32000, :message "community not found"}}

```

**Comment by flexsurfer** [comment]
ok i see , we set `:spectating false` and don't `re-fetch` the community

**Comment by flexsurfer** [comment]
<img width="767" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/c5e7a749-6ac2-4102-adbc-2a58435320f3">
this is the reason

**Comment by flexsurfer** [comment]
so to fix that we need to understand how this spectate works, so the problem is that we rely on existance of community object in many places, and now we set it with only one field spectate
