### ISSUE TITLE
[User story] Interact with dApps in testnet mode

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20362]
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user/developer, I want to interact with dApps in testnet mode, so that I can test out it’s functionality without spending my funds.

[User story and acceptance criteria](https://www.notion.so/I-want-to-interact-with-dApps-in-testnet-mode-614d783d21ea4ce3884ba558648ab12f?pvs=4)

**Comment by clauxx** [comment]
Make sure this [reported issue](https://github.com/status-im/status-mobile/pull/20693#issuecomment-2228288723) is tackled here as well.

cc: @pavloburykh

**Comment by mohsen-ghafouri** [comment]
Hey @clauxx, i think we can close this one, right? anything else to do for it?

**Comment by clauxx** [comment]
Yeah, I think it can be closed, I guess it wasn't attached to the PR
