### ISSUE TITLE
Missing "Backup Recovery Phrase" option in profile

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20370]
### Steps:
1. Open profile
2. Check "backup recovery phrase" option

### Actual result:
The "Backup Recovery Phrase" option is not present in the profile settings.

### Expected result:
The "Backup Recovery Phrase" option should be available in the profile settings, allowing the user to initiate the backup process for their recovery phrase.

![image](https://github.com/status-im/status-mobile/assets/52490791/fc396b47-2f47-4bbe-8acb-2a55d587623a)

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### ENV:

Nightly [6 Jun 2024]

**Comment by flexsurfer** [comment]
unable to reproduce in latest develop

**Comment by flexsurfer** [comment]
the reason: https://github.com/status-im/status-go/commit/631b1afe428fc079b550eb274a30be300bc8197c
