### ISSUE TITLE
Adjust "sync or recover" page in onboarding

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20379]
As a user with a recovery phrase
I want messaging to be clear on where I should restore my seed phrase
So that I can use the status app with my wallet/account 

### Description

The onboarding messaging wasn't super clear in the case the user wanted to restore their seed phrase, some changes have been made to make it clearer so that the user is better guided through the flows.

![web](https://github.com/status-im/status-mobile/assets/1017008/38aba44f-adb4-4add-b687-145b56eb2ae3)

### Designs

https://www.figma.com/design/3XXfGrRNGl36GkrdicFQod/Design-Explorations?node-id=14474-44715&t=YxwhAQQpY5NQKXGY-1

**Comment by yqrashawn** [comment]
this new view is already included in https://github.com/status-im/status-mobile/pull/20386

**Comment by jo-mut** [comment]
> this new view is already included in #20386

@yqrashawn I have been working on this but now I just saw your comment, I think am basically doing the same thing so I will unassign myself from this one
