### ISSUE TITLE
Get full list of supported tokens from backend

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-react#20380]
We need to fetch list of supported tokens from backend and store them on re-frame so we can use the list on screens like
#20332
#20333
#20927

Check the comments for more context. This is already implemented in status-desktop so we can also check their implementation to replicate on mobile

**Comment by dlipicar** [comment]
@Khushboo-dev-cpp could you point us to the status-go endpoint we need to use to get the full list of collectibles? I think mobile does not have this at the moment

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp could you point us to the status-go endpoint we need to use to get the full list of collectibles? I think mobile does not have this at the moment

collectibles? or tokens? erc 20?

**Comment by dlipicar** [comment]
> > @Khushboo-dev-cpp could you point us to the status-go endpoint we need to use to get the full list of collectibles? I think mobile does not have this at the moment
> 
> collectibles? or tokens? erc 20?

I'll blame it on lack of sleep.
I meant erc20 tokens. Basically what we use to fill the all_tokens model

**Comment by Khushboo-dev-cpp** [comment]
Hey so we get a list of supported tokens which can include repeating entries for each token for each network via this api `wallet_getTokenList`
We then process it to combine it to non repeating items per token.
`wallet_fetchMarketValues` `wallet_fetchTokenDetails` `wallet_fetchPrices`  are used to get other details about the tokens. 

https://github.com/status-im/status-desktop/blob/dc554f8ea2f9611d919051763b523dab4e28d0bd/src/app_service/service/token/service.nim#L357 is file that handles all of it

**Comment by alwx** [comment]
Taking this one to work on it together with https://github.com/status-im/status-mobile/issues/20380
