### ISSUE TITLE
Allow non admin to add members to group chats

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20396]
As a private group chat user
I want to be able to add members to the group
So I don't have to ask the admin to add them

### Description

This is already implemented in the backend, I think it's just a matter of removing a check.

**Comment by flexsurfer** [comment]
https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2105-522742&t=9pjpwioEH9lB8W3m-1

it should be a  different label "Add members" and other members should be disabled, member can only remove themselves, and add other members, removing should be disabled
