### ISSUE TITLE
Improve speed when first signing in

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2039]
### User Story

As a user, I want to login without noticeable lag.

### Description

Login takes significant time. This is due to the fact embedded `geth` node is started at this time.
By starting geth asynchronously when the application starts login could be instantaneous.

This will require changes `status-go` side and careful synchronization to make sure login works even if node hasn't finish started.

*Type*: Feature

**Comment by yenda** [comment]
@jeluard could you confirm with your slow phone that it is faster now :D ?

**Comment by jeluard** [comment]
Wow almost 1 year old!
