### ISSUE TITLE
Routes are not build in the bridge flow

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20406]
### Steps:
1. Recover a user with available tokens on at least two networks (e.g., using ETH).
2. Navigate to the bridge flow.
3. Input a valid value to generate routes.

### Actual Result:
The app does not build the routes as expected.
![image](https://github.com/status-im/status-mobile/assets/52490791/53d4e193-367c-4462-b5cc-aabb1ff79b1a)

### Expected Result:
The app should build the routes successfully without any errors.

### ENV:
Mobile: Nightly 10 Jun 2024
Desktop: Status go 0.179.8, 2.29.0-rc.7

### Logs:
Desktop logs:
[logs.txt](https://github.com/user-attachments/files/15759203/logs.txt)

Mobile logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/15759240/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
Hi, @saledjenic. Could you take a look at this issue, please? Recently (a month ago) bridge routes were able to be built

**Comment by saledjenic** [comment]
@VolodLytvynenko from the screenshot you've provided I see that theoretically 2 routes should be possible Opt -> Mainnet and Arb -> Mainnet, but from the entered amount I think that's not enough for paying the bonder fee and that's why it results in no routes. Try to increase the input amount (but also be sure that you have enough on a certain network enough assets).

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko from the screenshot you've provided I see that theoretically 2 routes should be possible Opt -> Mainnet and Arb -> Mainnet, but from the entered amount I think that's not enough for paying the bonder fee and that's why it results in no routes. Try to increase the input amount (but also be sure that you have enough on a certain network enough assets).

I tried different amounts of available assets using different networks for bridging, but I couldn't build the routes. The user has an available balance on mainnet:
- Optimism: 0.07 ETH
- Arbitrum: 0.012 ETH
- Mainnet: 0.01 ETH

@saledjenic I initially also thought the issue was due to insufficient funds to cover the fee, but it still doesn't work when using a user with more funds. For example, I used a user with 0.15 ETH on mainnet and attempted to bridge 0.001 or 0.01 ETH to L2, but it didn't succeed.

https://github.com/status-im/status-mobile/assets/52490791/f14ca104-5131-4965-9e6a-191b2c9ff460

**Comment by saledjenic** [comment]
@VolodLytvynenko I've made some improvements to the Router, could you review this PR https://github.com/status-im/status-go/pull/5321 and check the app against it, should be good now.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I've made some improvements to the Router, could you review this PR [status-im/status-go#5321](https://github.com/status-im/status-go/pull/5321) and check the app against it, should be good now.

@saledjenic thank you. I will check it within PR with updated Status Go and let you know how it goes

**Comment by VolodLytvynenko** [comment]
@saledjenic Thank you for PR. Routes bridge routes are fixed. Issue can be closed
