### ISSUE TITLE
[Wallet] Show Recipient name if available in Unsigned/History

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2040]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see the name of the contact in the transaction history/unsigned-transaction list when the address I am sending to/receiving from belongs to one of my contact

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Steps to test
- Open Status
- Send eth to a contact
- Check if the name of the contact appears in the transaction history

**Comment by annadanchenko** [comment]
Tested in develop. Will be in 0.9.12 release
