### ISSUE TITLE
No user's name in system message in a Group chat if he is not your contact

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20431]
# Bug Report

### Reproduction

1. Login as `user A` with a lot of contacts
2. Login as a newly created `user B` (on another device or create a multiaccount)
3. As `user A` create a group chat with User B and +1 contact
4. As `User B` open group chat from step 3 and look at system message

#### Expected behavior
System message contains user's names that all are visible

#### Actual behavior
No user's name in system message in a Group chat if he is not your contact

<img width="435" alt="Screenshot 2024-06-11 at 11 39 58" src="https://github.com/status-im/status-mobile/assets/147824399/73acaeb7-e0d4-4ff9-8c4c-0af7ca8ff7ef">

### Additional Information

- Status version: nightly 11/06
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
there are more repercussions of the same problem:
1) how the added user is shown in a group chat members list (no name, no avatar)
2) "Remove from contacts" is available when the user is not your contact


https://github.com/status-im/status-mobile/assets/4557972/7612ac38-da2b-4f1f-9011-182312f159d3

**Comment by Parveshdhull** [comment]
fixed remove from contact issue in https://github.com/status-im/status-mobile/pull/20541
missing contact data issue still requires some research and being discussed in https://github.com/status-im/status-mobile/issues/20520 (both issues are caused by same problem)
