### ISSUE TITLE
Allow users from v1 to login with keycard

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20434]
As a v1 keycard user
I want to be able to login in status using keycard when upgrading to v2
So that I can continue using my account and I am not locked out

### Description

V2 doesn't support currently keycard.
We should at least allow the user to login if they created an account using v1.

The flows are here https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2941-332836&m=dev but we should focus on the functionality in the scope of this task (a simple textfield for the input is fine to start with), we can polish the UI later. Please coordinate with @saledjenic and @bitgamma as they are the domain expert.

**Comment by xAlisher** [comment]
@cammellos "a simple textfield for the input is fine" Are you referring to entering a PIN code?

**Comment by flexsurfer** [comment]
> @cammellos "a simple textfield for the input is fine" Are you referring to entering a PIN code?

I've already implemented designs from figma, it wasn't the hardest thing, same effort as for textfield

**Comment by xAlisher** [comment]
> > @cammellos "a simple textfield for the input is fine" Are you referring to entering a PIN code?
> 
> I've already implemented designs from figma, it wasn't the hardest thing, same effort as for textfield

Cool! Please let me know, when it will be available for testing.
