### ISSUE TITLE
Refactor: replace global platform-specific styles with local styles

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2044]
As a developer, I want to have one place for platform-specific styles.

*Type*: Bug / refactor

We have two different ways of declaring platform specific styles. Some screens use `:ios`/`:android` inline in `style.cljs` (e.g. https://github.com/status-im/status-react/blob/883b702fcba7d94b93828ccfaa6d6053100fe52d/src/status_im/ui/screens/group/styles.cljs#L42-L48), whereas others declare styles in a global platform specific `platform.cljs` namespace (https://github.com/status-im/status-react/blob/develop/src/status_im/ios/platform.cljs#L7-L66).

The former makes more sense to me in terms of locality. The latter is legacy code.

Probable offenders:

```
Oskars-MacBook-Pro:status-react oskarth$ ag component-style -l
src/status_im/android/platform.cljs
src/status_im/chat/screen.cljs
src/status_im/chat/views/actions.cljs
src/status_im/chat/views/input/animations/expandable.cljs
src/status_im/chat/views/input/animations/responder.cljs
src/status_im/chat/views/input/utils.cljs
src/status_im/chat/views/toolbar_content.cljs
src/status_im/components/chat_icon/styles.cljs
src/status_im/components/status_bar.cljs
src/status_im/components/text_field/styles.cljs
src/status_im/components/toolbar/view.cljs
src/status_im/components/toolbar_new/styles.cljs
src/status_im/ios/platform.cljs
src/status_im/ui/screens/chats_list/styles.cljs
src/status_im/ui/screens/contacts/new_contact/views.cljs
src/status_im/ui/screens/contacts/views.cljs
src/status_im/ui/screens/discover/all_dapps/views.cljs
src/status_im/ui/screens/discover/components/views.cljs
src/status_im/ui/screens/discover/views.cljs
src/status_im/ui/screens/group/views.cljs
src/status_im/ui/screens/profile/styles.cljs
```
(sans platform.cljs)

**Comment by oskarth** [comment]
Also consider fixing platform-specific styles that aren't styles strictly speaking. For example, discover has a "uppercase" defstyle hack that could be improved on. Probably a separate issue though.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x3bffbdde761c9eb31452459018f7a9c1e6048ee0](https://etherscan.io/address/0x3bffbdde761c9eb31452459018f7a9c1e6048ee0)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by foopang** [comment]
I will start working on it.
