### ISSUE TITLE
The last available network can be deselected in the bridge flow

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20441]
### Steps:
1. Restore a user with an available asset on all networks (e.g., ETH).
2. Go to the bridge flow.
3. Generate routes.
4. Deselect all networks in the FROM section.

### Actual result:
All networks can be deselected.

https://github.com/status-im/status-mobile/assets/52490791/ada40e8a-0c8c-4d15-926a-b186cefff10c

### Expected result
The last available network can't be deselected, 
similar to how it works in the send flow.
![image](https://github.com/status-im/status-mobile/assets/52490791/d68bcc57-9178-4909-a89f-095aea36243a)

### ENV:
Nightly 12 Jun 2024

**Comment by J-Son89** [comment]
@churik - wdyt if we move this to 2.31 is it so important? 🤔

**Comment by churik** [comment]
if there is no crash - no problem to move it, I'll move it

**Comment by churik** [comment]
added `blocked` because it does not make sense with simplified flow, which is planned

**Comment by VolodLytvynenko** [comment]
This issue is resolved in the new simplification flow https://github.com/status-im/status-mobile/pull/21595
