### ISSUE TITLE
Show collectibles in Activity tab

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#20446]
### User Story

As a user, I want to see the collectibles sent and received in the activity tab **so that** I can see if a collectible has been successfully sent or received. 

### Description

Currently the activity tab only properly displays the transactions for tokens, this issue is about adding support for transactions with collectibles.

### Acceptance Criteria

The collectible transactions should be properly displayed in the activity tab.

**Comment by OmarBasem** [comment]
@ulisesmac potentially related or dup https://github.com/status-im/status-mobile/issues/17318

**Comment by ulisesmac** [comment]
> @ulisesmac potentially related or dup #17318

@OmarBasem I checked it and it's a different issue, this one is about showing the details of the collectible transactions in the main activity tab.

Maybe they could be related, not completely sure.

Thank you!
