### ISSUE TITLE
Channel members are shown as community members on mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20465]
# Bug Report

## Problem 
Instead of showing members with access to the channel (like on desktop), the full member community list is shown on mobile. 

#### Expected behavior
only members who have  access to a particular channel
<img width="416" alt="Status Desktop 2024-06-14 14-56-35" src="https://github.com/status-im/status-mobile/assets/4557972/26289a1d-00dd-42a7-b73f-30d49c451cd8">

#### Actual behavior
all community members are shown
![IMAGE 2024-06-14 14:54:07](https://github.com/status-im/status-mobile/assets/4557972/767e94a5-dec4-4517-a45d-6af664ca246f)

### Reproduction

1. Desktop: Create a community, set a permission for channel
2. Desktop: Add several members to this channels, who have access to this channel
3. Mobile: Check the members for the channel

### Additional Information

- Status version: nightly 14/06/24
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Related status-go PR https://github.com/status-im/status-mobile/pull/20414

**Comment by churik** [comment]
closed in https://github.com/status-im/status-mobile/pull/20414
