### ISSUE TITLE
[IOS] "Unsupported file" shown on detailed collectible view for some collectibles while images are fetched on list view

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20463]
### Steps:
1. Restore a user with collectibles from this https://testnets.opensea.io/collection/the-monkey-chainz collection or add the address as watch only '0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e' (NOTE: current collectibles are on the testnet)
2. Go to collectibles tab
3. Open collectible to see the detailed view

### Actual result:
"Unsupported file" message is shown on the detailed collectibles view, while the images are fetched on the list view.

https://github.com/status-im/status-mobile/assets/52490791/13de5823-8acb-4a09-b5a9-db8279892b55

### Expected result:
If the collectible image is fetched on the list view, it should also be fetched for the detailed view.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15837245/Status-debug-logs.zip)

### ENV:
Nightly 14 Jun 2024

**Comment by VolodLytvynenko** [comment]
Reopened this issue. The issue still exists on my IOS device after merging https://github.com/status-im/status-mobile/pull/20657 

### Steps:
1. Add watch only: `0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5`
2. Check collectibles

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/d717f781-4c68-428f-a631-986b1020b677

### Device:
iPhone 11 Pro max, IOS 17

### ENV:
Nightly 10 Jul

### logs:
[logs.zip](https://github.com/user-attachments/files/16157207/logs.zip)

**Comment by ulisesmac** [comment]
Thank you for reporting it @VolodLytvynenko 

Is it an iOS only issue?
I'll check it soon.

Btw, this this is not an "unsupported" error as the issue says, it shows a "can't fetch info" error, maybe due to the network connection.

**Comment by VolodLytvynenko** [comment]
> Thank you for reporting it @VolodLytvynenko
> 
> Is it an iOS only issue? I'll check it soon.
> 
> Btw, this this is not an "unsupported" error as the issue says, it shows a "can't fetch info" error, maybe due to the network connection.

@ulisesmac Yes, you're right. The "can't fetch info" issue is different from the original one. For me, It sometimes happens after adding a watch-only account or after relogining. I only encounter this on IOS device

https://github.com/status-im/status-mobile/assets/52490791/edb508bd-1f4c-451f-8af9-4f326c33dfd9

**Comment by ulisesmac** [comment]
@VolodLytvynenko I've opened a PR to address this issue, you were right, this is happening on iOS, and it's due to the navigation timing differences between platforms. It should be solved now.

Again, thanks for reporting it! :+1:
