### ISSUE TITLE
User can not set his ENS name in his Profile on v.1 application

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20474]
# Bug Report

#### Actual behavior
User can not connect his profile with his existing ENS 

<img width="306" alt="Screenshot 2024-06-14 at 15 05 39" src="https://github.com/status-im/status-mobile/assets/147824399/f49bd2ad-d1bd-4677-961c-6976c8110ee6">

#### Expected behavior
User can connect his profile to his existing ENS 

### Reproduction

1. Install v.1 app (you can use android build from https://github.com/status-im/status-mobile/pull/20123)
2. Restore user that has ENS 
3. Go to Profile -> ENS
4. Type your test ENS name

### Additional Information

- Status version: v.1 app
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mariia-skrypnyk** [comment]
@qfrank are you ok that I've assigned you to https://github.com/status-im/status-mobile/issues/20468 as this PR is a duplicate? I'll close this one.

**Comment by qfrank** [comment]
close according to [comment](https://github.com/status-im/status-mobile/issues/20474#issuecomment-2173554813)
