### ISSUE TITLE
Twitter links preview are not fetched 1-1 chats/group chats or channels

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20478]
# Bug Report

### Reproduction

1. Login to app
2. Open any chat (1-1/group or community channel)
3. Past link to the composer : https://mobile.twitter.com/dcbatmanrun 

#### Expected behavior

Twitter links preview are fetched

<img width="267" alt="Screenshot 2024-06-17 at 17 18 52" src="https://github.com/status-im/status-mobile/assets/147824399/a0e2af79-ce21-49c7-b15e-d1231559c0d4">

https://www.figma.com/design/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2102-232933&t=R9tC9tfxkVSY6MyN-0

#### Actual behavior

Twitter links preview are not fetched

https://github.com/status-im/status-mobile/assets/147824399/a30909e2-22d7-48ea-a698-f3a7c7833191

### Additional Information

- Status version: nightly 17/06
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
hey @mariia-skrypnyk thank you for the issue, could you pls elaborate on why we think this link should work?

**Comment by mariia-skrypnyk** [comment]
> hey @mariia-skrypnyk thank you for the issue, could you pls elaborate on why we think this link should work?

Hey @flexsurfer ! 
Are you asking regarding my test link or Twitter links in general?

**Comment by flexsurfer** [comment]
> Are you asking regarding my test link or Twitter links in general?

both

btw this particular link doesn't work on desktop as well

**Comment by mariia-skrypnyk** [comment]
@flexsurfer  Will try to find any requirements for this.
Sorry, these days are very busy during release testing.

**Comment by churik** [comment]
cross-referencing https://github.com/status-im/status-mobile/issues/15656

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer!

I will close this issue due to this comment https://github.com/status-im/status-mobile/issues/15656#issuecomment-1516574908

Thanks for your time anyway!
