### ISSUE TITLE
Wallet: update use of GetWalletToken endpoint to GetWalletTokenBalances

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20473]
For 2.31 release:
Following from the work on Status-Go
https://github.com/status-im/status-go/issues/5320

Mobile wallet needs to migrate to the new status go endpoint `GetWalletTokenBalances`

**Comment by J-Son89** [comment]
cc @alaibe

**Comment by churik** [comment]
@shivekkhurana why this issue is added to 2.31, maybe I missed something or it was added by mistake? afaik we need to cut the branch in several days, so it won't be possible to complete that.

**Comment by churik** [comment]
Postponed due to time constraints to the next release, also we'll recheck it as the issue is fairy old

cc @shivekkhurana

**Comment by pavloburykh** [comment]
Re-checked. According to request logs we are still using GetWalletToken. So the issue is still valid. [requests.log](https://github.com/user-attachments/files/17305712/requests.log)

**Comment by vkjr** [comment]
Related status-go PRs:
[Get rid of wallet.Reader.GetWalletToken method ](https://github.com/status-im/status-go/issues/5320)
[chore(wallet)_: split getWalletTokenBalances into multiple functions](https://github.com/status-im/status-go/pull/5312)
