### ISSUE TITLE
The wallet is shown as white after upgrade from V1 to V2

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20476]
Follow up for https://github.com/status-im/status-mobile/pull/20151
### Steps:
1. Create new user in old apk https://github.com/status-im/status-mobile/pull/20123
2. Install new apk
3. CHeck how wallet is migrated

### Actual result:
The wallet is shown as white.
![image](https://github.com/status-im/status-mobile/assets/52490791/4551a47c-4877-4804-9409-d0bfe9b0d86b)

### Expected result:
The wallets should be shown with the default color (blue).
![image](https://github.com/status-im/status-mobile/assets/52490791/fb02b3f3-7e18-4345-baf2-9eae17cd65aa)

### ENV:
Nightly 17 Jun 2024

**Comment by qoqobolo** [comment]
Custom color is not visible also for:
- account switcher
- slider
- account icon on the tx review page

<img width="433" alt="Screenshot 2024-07-26 at 11 28 24" src="https://github.com/user-attachments/assets/3e2fa4db-4586-41d1-9ed5-e774bb738077">

<img width="435" alt="Screenshot 2024-07-26 at 11 28 03" src="https://github.com/user-attachments/assets/61efa0ed-de90-4f64-9afa-f3314a1a74c0">

**Comment by churik** [comment]
will be fixed in https://github.com/status-im/status-mobile/pull/20896
