### ISSUE TITLE
Collectibles: Hide account switcher in send flow

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20472]
It might be good to fix this together with https://github.com/status-im/status-mobile/issues/20479

The account switcher in the collectibles account flow makes things a bit more complicated.

We should hide the account switcher when we know the user is trying to send a collectible.

For example here is one screen where it can cause this issue:
<img src="https://github.com/status-im/status-mobile/assets/22799766/2ec8e088-e8f5-44ee-af4f-281372a25483" />

Please consider other entry points to the sending flow. when verifying this feature works.

**Comment by ulisesmac** [comment]
@J-Son89 

Another options are:
1. To keep the account switcher, but make it unpressable
2. [I'd prefer this one] Make the account switcher pressable, but show only one account to switch:
    Example:
    <img src="https://github.com/user-attachments/assets/9a18678a-b1d0-41b4-9dff-ed47ebdfadca" height="600">
    Show the bottom sheet with only one option instead of two

My main concern with removing the account switcher is that it helps to know the account the user is using to send assets. Also I think it's better to keep consistent designs, some  users may wonder why the account switcher disappeared.


wdyt?

**Comment by ulisesmac** [comment]
> @J-Son89
> 
> Another options are:
> 
>     1. To keep the account switcher, but make it unpressable
> 
>     2. [I'd prefer this one] Make the account switcher pressable, but show only one account to switch:
>        Example:
>        <img alt="" height="600" src="https://private-user-images.githubusercontent.com/90291778/348396723-9a18678a-b1d0-41b4-9dff-ed47ebdfadca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NzQwNzksIm5iZiI6MTcyMTc3Mzc3OSwicGF0aCI6Ii85MDI5MTc3OC8zNDgzOTY3MjMtOWExODY3OGEtYjFkMC00MWI0LTlkZmYtZWQ0N2ViZGZhZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDIyMjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZmQ5Nzk3MTdjOWZiZjAzYTUxZjA0NTRjYzg3YTg4MjJiMDAxZGJiNzEwYjlmOTJlNjMwOGNlOWQ4ZTg4N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b7npntOJD_rrmyKdK8S0MGWDqfN9Oqy96Nnt5Q-5oUc">
>        Show the bottom sheet with only one option instead of two
> 
> 
> My main concern with removing the account switcher is that it helps to know the account the user is using to send assets. Also I think it's better to keep consistent designs, some users may wonder why the account switcher disappeared.
> 
> wdyt?

This has been discused with the design team. The decision is to remove the account switcher, as the issue says

**Comment by J-Son89** [comment]
Thanks @ulisesmac !
