### ISSUE TITLE
 Incorrect transaction amount after transaction amount value customization on the "Send To" page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20484]
### Steps:
1. Go to send transaction flow
2. Add the multichain address into the input field (all available networks must be included in the recipient address)
3. Enter a value on the "Send To" page that is available on all networks (e.g., User has 0.01 on Arbitrum, 0.1 on Optimism, 1 on Ethereum. Enter a value within the range, such as 0.005).
4. After a route is found, go to the 'Custom' tab and change the value for the found route (e.g., change the value for Arbitrum to 0.001).
Confirm the transaction.

### Actual result:
After the transaction is confirmed, the amount sent on the blockchain is less than the amount entered during customization, and in fact, it equals 0.0009962871.

https://github.com/status-im/status-mobile/assets/52490791/82a666ca-b6e7-4290-bec4-86da621c0ad0

https://sepolia.arbiscan.io/tx/0x858e254e2ae15ec0bc84e68dd2f404b537532d2c86951d7d76a8f8c31501e0b7

For other networks, the sum is not recalculated as expected. If the entered value was 0.005 as described in step 3 and for some network the custom value is set to 0.001, then the rest of the value (0.004) should be distributed among other networks, which does not happen.

https://github.com/status-im/status-mobile/assets/52490791/a1a7df31-1a34-4bdc-8161-12dfd12c6ca5

### Expected result:
- The amount in the transaction should be the same as set up in the customization.
- The rest of sum  distributed among other networks 

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
- Desktop 
![image](https://github.com/status-im/status-mobile/assets/52490791/ecc3e325-5568-4eb8-8b1e-39f40855e004)

**Comment by VolodLytvynenko** [comment]
Potentially, it should be fixed by https://github.com/status-im/status-go/pull/5426

**Comment by J-Son89** [comment]
@VolodLytvynenko - 
This seems like a front end issue to me too 🤔 
From discussing with @xAlisher the custom amounts should never exceed the total amount put into the main amount input.
e.g in the mobile video attached the main amount input is 0.005. So the custom amounts should not exceed that, but this happening then creates this bug.



cc @briansztamfater, @vkjr, @BalogunofAfrica do you think we should prevent this on frontend side? 🤔

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - This seems like a front end issue to me too 🤔 From discussing with @xAlisher the custom amounts should never exceed the total amount put into the main amount input. e.g in the mobile video attached the main amount input is 0.005. So the custom amounts should not exceed that, but this happening then creates this bug.
> 
> cc @briansztamfater, @vkjr, @BalogunofAfrica do you think we should prevent this on frontend side? 🤔

@J-Son89 probably this https://github.com/status-im/status-mobile/issues/20578 issue has the same cause

**Comment by J-Son89** [comment]
I will close this issue for now as Multi-chain routing is descoped for 2.31 and by 2.30 we will remove route customisation/locking
