### ISSUE TITLE
[iOS] No Notification settings ON after v.1 - v.2 migration

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20491]
# Bug Report
https://github.com/status-im/status-mobile/pull/20412

**Steps:**

1. Install v.1 version
2. Create a user
3. Allow notifications
4. Go to Profile -> Notifications
5. Make sure they are turned on
6. Update app with v.2 app

#### Expected behavior

Notification swithcer is on as it was on v.1

<img width="341" alt="Screenshot 2024-06-17 at 15 47 13" src="https://github.com/status-im/status-mobile/assets/147824399/c20f380f-0727-43f5-9c92-e895b711115e">

#### Actual behavior

Notification switcher is off

<img width="326" alt="Screenshot 2024-06-17 at 15 45 49" src="https://github.com/status-im/status-mobile/assets/147824399/658be24b-4ec7-47c3-a14c-a6781552c3e6">

### Additional Information

- Status version: PR build from https://github.com/status-im/status-mobile/pull/20412
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
seems like an important issue, but still there is no capacity in 2.30, postponed

**Comment by churik** [comment]
As it is possible to fix with re-enabling PNs in profile and most of the users already upgraded, don't think that it makes sense to keep this open
