### ISSUE TITLE
No migration of Status nodes setting from v.1 to v.2 app 

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20490]
# Bug Report
https://github.com/status-im/status-mobile/pull/20412

**Steps:**

1. Install app with v.1 app on your android device
2. Go to Profile -> Sync settings
3. Set Mobile data, backup settings and Sync hystory for
4. Update your app to v.2
5. Go to your Profile -> Legacy settings -> Sync settings
6. Check if your settings migrated

#### Expected behavior
All settings migrated succesfully

#### Actual behavior
No Status nodes data setting
*`Sync hystory for` is already fixed

<img width="319" alt="Screenshot 2024-06-18 at 14 19 17" src="https://github.com/status-im/status-mobile/assets/147824399/3dd09b5c-de2a-4fd1-bfad-f2461be3a35e">

### Additional Information

- Status version: PR build from https://github.com/status-im/status-mobile/pull/20412
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
I don't think that this is important part for migration, as it was done for waku-v1
cc @ilmotta
