### ISSUE TITLE
Error after sending assets to multichain address (cannot unmarshal non-string...)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20499]
# Bug Report

## Problem 
After sending to a multichain address error is shown:
![IMAGE 2024-06-18 17:40:46](https://github.com/status-im/status-mobile/assets/4557972/f869263b-2b58-4a02-9930-17cb8d95e1f6)

#### Expected behavior
no error

#### Actual behavior
https://github.com/status-im/status-mobile/assets/4557972/0aaa0b94-3704-43e0-825c-90e1cceb733a

### Reproduction

1. Scan multichain address and send some amount of any assets to it (reproducible on Mainnet and Testnet)

### Additional Information

- Status version: nightly 18/06/24
- Operating System: Android, iOS
- Logs: 
[logs (92).zip](https://github.com/user-attachments/files/15889138/logs.92.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment]
@churik I am not able to reproduce this issue. Are you still getting that error?

**Comment by OmarBasem** [comment]
@status-im/mobile-qa can someone confirm if this issue is still reproducible?

**Comment by VolodLytvynenko** [comment]
> @status-im/mobile-qa can someone confirm if this issue is still reproducible?

hi @OmarBasem I encountered this error yesterday. I will try to reproduce it one more time and share the logs

**Comment by VolodLytvynenko** [comment]
@OmarBasem seems I found more exact steps. For me, it is reproducible consistently when the arbitrium network is used, but it reproduces on optimism as well

### Steps:
1. Recover a user with available L2 assets (e.g., Arbitrum).
2. Open 'account 1' where assets are located.
3. Tap the 'send' button.
4. Select 'account 2' as the receiver.
5. Build an Arbitrum route on the routes generation page.
6. Edit the input value to be slightly less than the available tokens on your account (e.g., if you have 0.01 ETH available, enter 0.0099).
7. Confirm the transaction.

### Actual result:
Error after sending assets.

https://github.com/status-im/status-mobile/assets/52490791/3fc687ed-9ab8-4e70-9309-37325ea53d4a


### Expected result:
No error is shown.

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/16180698/Status-debug-logs.zip)

**Comment by OmarBasem** [comment]
@J-Son89 considering that [announcement](https://discord.com/channels/1210237582470807632/1254827811873620068/1262765305160142950) on discord should this issue and other issues related to L2 be removed from 2.30 and 2.31?

**Comment by J-Son89** [comment]
thanks for raising this question @OmarBasem - so L2's should still work. 
Going forward we will still be working with L2's, it's just that we won't be doing the multi transaction process.
We will only be doing a single transaction at a time, which could be on any network (mainnet,arb, opt). 
Similar for bridging.

**Comment by OmarBasem** [comment]
> thanks for raising this question @OmarBasem - so L2's should still work. Going forward we will still be working with L2's, it's just that we won't be doing the multi transaction process. We will only be doing a single transaction at a time, which could be on any network (mainnet,arb, opt). Similar for bridging.

Thanks @J-Son89, sounds good!

**Comment by churik** [comment]
Seems fixed in https://github.com/status-im/status-mobile/pull/20631
