### ISSUE TITLE
Incorrect calculation in bridge route generation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20502]
### Steps:
1. Restore user with available assets on any mainnet network
2. Go to the routes generation page or the bridge page
3. Input available value to generate any bridge route

### Actual result:
The calculation for the route in the FROM section is lower than in the TO section.

![image](https://github.com/status-im/status-mobile/assets/52490791/e9581f48-7837-4c35-878e-b0714ef57b4b)

### Expected result:
The calculation for the route in the FROM section should be higher than in the TO section. In the TO section, the amount should match the value set in the input field.

![image](https://github.com/status-im/status-mobile/assets/52490791/314a4ddd-d758-44fe-93ba-e23ac5417b66)

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 18 Jun 2024

**Comment by churik** [comment]
@VolodLytvynenko I believe that you discussed it, and it is expected or I'm mixing it up?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I believe that you discussed it, and it is expected or I'm mixing it up?

@churik that's not expected how it works on Mobile builds. Behavior on the desktop is correct

**Comment by J-Son89** [comment]
@VolodLytvynenko - this issue is blocked as briding is currently broken, right?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - this issue is blocked as briding is currently broken, right?

@J-Son89 Not exactly so. We can see the bridge routes, but we can't confirm the bridge transaction itself. This issue is not blocked and can be reproduced
