### ISSUE TITLE
Write testing instructions for RPC methods

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20516]
## Description

> As a QA tester, I want to know where and how to test each individual RPC method, so that I can assure that they all work as expected.

Write a documentation on Notion that gives examples of dApps for each RPC method and how they can be triggered in the dApp. This would help the testing teams to assure we support said methods.

### Acceptance criteria

- [ ] the following methods have testing instructions
  - [x] eth_sign
  - [ ] eth_signTypedData (optional, as in if we don't find examples of dApps using this, we shouldn't bother too much as it might be deprecated)
  - [x] eth_signTypedData_v4
  - [x] personal_sign
  - [ ] eth_signTransaction
  - [x] eth_sendTransaction
- [ ] each method has at least on dApp that supports it
- [x] each method has a step-by-step instruction on how it should be triggered in the dApp

**Comment by shivekkhurana** [comment]
Testing instructions for famous dapps: https://www.notion.so/Testing-Wallet-Connect-interactions-0739f176856848999f0ea1671e5dfbe0

**Comment by clauxx** [comment]
Looks great! Thank you!
