### ISSUE TITLE
Profile picture missing after migration from v1 to v2

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#20512]
# Bug Report

## Problem 

Users can't see their old profile pictures after installing Status v2 on top of Status v1 (migrating to v2).

Reported by @flexsurfer 

#### Expected behavior

After installing Status v2, the user should see the same old profile picture.

#### Actual behavior

After installing Status v2, the old profile picture is missing and not displayed to the user.

### Reproduction

1. Create user in v1.
2. Log in and add a profile picture.
3. Log out, check the avatar is shown.
4. Install Status v2 (any recent build will do).

### Additional Information

- Status version: from release branch `1.20.x`
- Operating System: Android, iOS

cc @qfrank

**Comment by flexsurfer** [comment]
`handleAccountInitialsImpl: no public key, can't draw ring keyUid=0x.......`
that's because no ColorHash in db,
https://github.com/status-im/status-go/blob/dbed69d1551e3fc9b29a125a36f97cc3fa8af6f3/server/handlers.go#L492

so probably we should generate it during v2 migration

**Comment by ilmotta** [comment]
I checked on Android 13 on a real device, and I can't set the profile picture on v1 (when pressing on the edit pencil icon, nothing happens). I think this is the reason why QAs couldn't test the profile picture migration from v1. cc @mariia-skrypnyk

**Comment by qfrank** [comment]
[profile-pic.webm](https://github.com/status-im/status-mobile/assets/12406719/a0a38320-e7ac-48d7-b735-bbdf214efea6)
no luck to reproduce, am I missing something?

**Comment by flexsurfer** [comment]
@qfrank Actually i didn't try the profile picture, for me it was an avatar with initials

**Comment by qfrank** [comment]
> @qfrank Actually i didn't try the profile picture, for me it was an avatar with initials

could you make a record on how to reproduce? @flexsurfer

**Comment by flexsurfer** [comment]
1)install 1.20.x
2)generate a new account
3)install the latest nightly on top
4)open the app, no avatar on a profile card

**Comment by qfrank** [comment]
> 1)install 1.20.x 2)generate a new account 3)install the latest nightly on top 4)open the app, no avatar on a profile card

I reproduced with keycard, so the key difference is keycard here :) @flexsurfer

**Comment by qfrank** [comment]
I believe this issue can be closed now? 🙂 @ilmotta

**Comment by ilmotta** [comment]
@qfrank, the PR https://github.com/status-im/status-mobile/pull/20538 references this issue and will automatically close it, but 20538 is not merged yet.

**Comment by qfrank** [comment]
> @qfrank, the PR #20538 references this issue and will automatically close it, but 20538 is not merged yet.

goddamn, sorry, I opened the wrong issue link and commented 🫣
