### ISSUE TITLE
"No Routes Found" message displays with 'Try Again' button when minimum value is set during network customization

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20526]
Follow up https://github.com/status-im/status-mobile/pull/20413

### Steps:
1. Restore the user with available network assets on at least one network.
2. Enter a valid asset value to build the route (e.g., 0.001 ETH).
3. Long press on the built network.
4. Set a value less than the entered value on the route generation page (e.g., 0.0005 ETH).
5. Apply the changes with the 'Don't auto recalculate <network>' checkbox checked.

### Actual result:
The No Routes Found is shown with 'Try again' button 
![image](https://github.com/status-im/status-mobile/assets/52490791/19f7e78f-4550-4fae-a32e-7351155b4a51)

### Expected result:
The No Routes Found is shown without 'Try again' button 
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15902-47969&t=RXJiUXvnHGNFNIZZ-0

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by xAlisher** [comment]
Agreed. "Try again" makes sense only if it's router internal error. If "No routes found" is logical result of user action we should not have "Try again" button.

**Comment by J-Son89** [comment]
I will close this issue for now as Multichain routing is descoped for 2.31 and by 2.30 we will remove route customisation/locking
