### ISSUE TITLE
Contact list reloads when selecting/unselecting contacts (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20532]
Android only. Reproducing on Android 12, Samsung Galaxy A52

Areas affected: default contact list, contact list in group chat

**Steps:** 

1. Open contact list
2. Select/unselect contacts
3. Try scrolling contact list

**Actual result:** looks like contact list is reloading after selecting/unselecting contacts which leads to scrolling gets stuck or list does not react on tap. 

https://github.com/status-im/status-mobile/assets/97245802/43c9cb20-fb00-4d48-8123-a8ebf36bf816

- Status version: nightly 
- Operating System: Android

**Comment by churik** [comment]
postponing because of time constraint for 2.30

**Comment by flexsurfer** [comment]
hey @pavloburykh could you confirm it's still the issue? thank you

**Comment by pavloburykh** [comment]
> hey @pavloburykh could you confirm it's still the issue? thank you

Hey @flexsurfer! Yes, the issue is still valid. 


https://github.com/user-attachments/assets/36fa1998-af9c-44bd-abf5-df47f8364f01
