### ISSUE TITLE
Toast error messages issues when scanning a "missing key pair" QR code

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20548]
# Bug Report

## Problem 

Two unhappy flows that were initially reported in https://github.com/status-im/status-mobile/pull/20464#issuecomment-2186348441 are described here, but further investigation may be needed on how we should handle toast errors in all possible cases.

**Designs:** https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=232-33031&t=hioBwxRjpwpVBl41-0

### 1. Wrong error text when scanning a QR from a wrong key pair when attempting to import a missing key pair

**Steps:**
1. Create a profile on Device1
2. Sync Device2 with Device1
3. Create a new key pair on Device1
4. On Device1: open `Profile` > `Wallet` > `Key pairs and accounts` > press three dots on some key pair, other than needed one (e.g. on the default key pair) > `Show encrypted QR of key pairs on device`
5. On Device2: press three dots on the missing key pair > `Import by scanning encrypted QR` > Scan the wrong QR

**Expected error:** `This is not the QR you are looking for` (pls correct me if I'm wrong here)
**Actual error:** 

<img width="313" alt="Screenshot 2024-06-24 at 12 59 25" src="https://github.com/status-im/status-mobile/assets/67952253/779955eb-f8c2-48a5-8605-a6f5f8daf9ff">

### 2. Wrong error text when scanning an already used QR

This might be an edge case, but I honestly don't know how else to reproduce the "QR code has already been used" error, so I tried this scenario

**Steps:**
1. Create a profile on Device1
2. Sync Device2 and Device3 with Device1
3. Create a new key pair on Device1
4. Scan the required QR code for the missing key pair on Device2
5. Scan **_the same_** QR code for the missing key pair on Device3

**Expected error:** `QR code has already been used`
**Actual error:**

<img width="394" alt="Screenshot 2024-06-24 at 13 25 35" src="https://github.com/status-im/status-mobile/assets/67952253/c2731018-a95f-415f-8e6a-fbc23a536ddf">

### Additional Information

- Status version: https://github.com/status-im/status-mobile/pull/20464 
- Operating System: Android, iOS

cc @smohamedjavid

**Comment by qoqobolo** [comment]
@smohamedjavid I'm also not sure about adding this to 2.30. Please add the corresponding milestone if needed, thanks!

**Comment by smohamedjavid** [comment]
Thank you @qoqobolo 🙏

**Comment by smohamedjavid** [comment]
> 1. Wrong error text when scanning a QR from a wrong key pair when attempting to import a missing key pair

We will update the text to `This QR does not contain {{name}} key pair` as per the updated [design](https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=5914-23785&t=dGnwCpVswPR2CPOD-1). 

> 2. Wrong error text when scanning an already-used QR

We haven't implemented this validation in `status-go` to know whether a QR (connection string) is already used or expired. Most likely this will not be done for this milestone or the next one as this is an update to the local pairing feature in general. We will defer it for now.
