### ISSUE TITLE
 Incorrect black background behind Saved addresses button

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#20543]
# Bug Report

#20475

### Steps:

- Login to app
- Go to Profile -> Wallet -> Saved addresses
- Tap on +
- Add an address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)
- Tap Continue

#### Actual behavior
![image](https://github.com/status-im/status-mobile/assets/71308738/f0cfc4f2-a8b8-4af0-a4ca-3d30fbd85ab6)

#### Expected behavior
![image](https://github.com/status-im/status-mobile/assets/71308738/4ee53283-5461-4eb3-8951-23a50ab5e0db)

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Will add one more place where this issue appears:

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Add an address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)
5. Tap on + (
6. Type the same address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)

**Actual result:**

<img width="257" alt="Screenshot 2024-06-26 at 11 43 05" src="https://github.com/status-im/status-mobile/assets/147824399/950a7f92-0ba9-4fa0-9b44-69efe5ce5652">
