### ISSUE TITLE
The "Not enough assets to pay gas fees" message is below 'fees' and 'Recipient gets' section

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20562]
### Steps:
1. Recover user with available assets
2. Enter a max value into the routes generation page

### Actual result:
- The "Not enough assets to pay gas fees" message is below 'fees' and 'Recipient gets' section
- Try again button is shown
![image](https://github.com/status-im/status-mobile/assets/52490791/9f8aa8a2-c05c-4fb7-94bf-56c8f31c15a3)

### Expected result:
![image](https://github.com/status-im/status-mobile/assets/52490791/5bb0a6dc-0147-4929-9b99-be9f9812ceb3)

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15329-122613&t=IkBLWZnxdyOqwZLn-0

### ENV:
Nightly 25 Jun 2024

**Comment by VolodLytvynenko** [comment]
still valid. Not related to new rpc from https://github.com/status-im/status-mobile/pull/21378

**Comment by clauxx** [comment]
@VolodLytvynenko what is the intended way to show this, since we don't get any routes/fees when this happens? Also, is it really a blocker @shivekkhurana?

**Comment by VolodLytvynenko** [comment]
> [@VolodLytvynenko](https://github.com/VolodLytvynenko) what is the intended way to show this, since we don't get any routes/fees when this happens? Also, is it really a blocker [@shivekkhurana](https://github.com/shivekkhurana)?

@clauxx, sorry if there was any confusion. The intention of this issue is to fix some UI elements:

1. The "Not enough assets to pay gas fees" message is currently displayed below the "Fees" and "Recipient gets" sections. It should be shown above. (Although fee value is zero because we don’t get the fee from Status Go, we have a separate [issue](https://github.com/status-im/status-mobile/issues/20560) for this.)

2. When the "Not enough assets to pay gas fees" message appears, the "Try again" button is shown, but it shouldn't be.

Let me know if this makes sense.

Also, it's definitely not a blocker. @shivekkhurana, would it be better to move this to the next milestone? WDYT?

**Comment by clauxx** [comment]
> > [@VolodLytvynenko](https://github.com/VolodLytvynenko) what is the intended way to show this, since we don't get any routes/fees when this happens? Also, is it really a blocker [@shivekkhurana](https://github.com/shivekkhurana)?
> 
> [@clauxx](https://github.com/clauxx), sorry if there was any confusion. The intention of this issue is to fix some UI elements:
> 
>     1. The "Not enough assets to pay gas fees" message is currently displayed below the "Fees" and "Recipient gets" sections. It should be shown above. (Although fee value is zero because we don’t get the fee from Status Go, we have a separate [issue](https://github.com/status-im/status-mobile/issues/20560) for this.)
> 
>     2. When the "Not enough assets to pay gas fees" message appears, the "Try again" button is shown, but it shouldn't be.
> 
> 
> Let me know if this makes sense.
> 
> Also, it's definitely not a blocker. [@shivekkhurana](https://github.com/shivekkhurana), would it be better to move this to the next milestone? WDYT?

Thanks, I'll un-assign myself then

**Comment by churik** [comment]
Based on previous discussion I suppose can be deferred. cc @shivekkhurana
