### ISSUE TITLE
Incorrect amount division between networks in route generation page after some network amount is customized

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20578]
Unfortunately, I can't validate this issue on the desktop side. Desktop does not show the calculation for each network if routes are built.

### Steps:
1. Restore a user with available assets on at least 2 networks.
2. Disable testnet mode
3. Go to the routes generation page.
4. Enter an asset value that is available for both networks (in my case, 0.003 ETH, referred to as "total value").
5. Disable some routes in the 'TO' section to enable bridge routes building (e.g., if assets are available on ETH and ARB, disable OPT in network preferences).
6. Long press on the network where the route is not built (e.g., ETH network).
7. Enter an available value in the customization drawer (note: this value should not exceed the "total value").
8. Apply the changes.
9. Check the amount division between networks.

### Actual result:
The entered amount is divided such that the total exceeds the entered value.

In my case:
**WHEN:** Entered amount = 0.003 ETH
**THEN** the following routes are built after network customization:
  0.0001 ETH (Mainnet) -> 0.0001 ETH (Opt)
  0.004969 ETH (ARB) -> 0.004969 ETH (ARB)

https://github.com/status-im/status-mobile/assets/52490791/ebbce137-a918-41b4-909a-82c0dc71e034

### Expected result:
The entered amount should be divided such that the total does not exceed the entered value. For example:

**WHEN:** Entered amount = 0.003 ETH
**THEN** the following routes are built after network customization:
0.0001 ETH (Mainnet) -> 0.0001 ETH (Opt)
0.002 ETH (ARB) -> 0.002 ETH (ARB)

### OS: 
IOS, Android

**Comment by J-Son89** [comment]
I will close this issue for now as Multi-chain routing is descoped for 2.31 and by 2.30 we will remove route customisation/locking

**Comment by IvanBelyakoff** [comment]
@VolodLytvynenko 

> WHEN: Entered amount = 0.003 ETH
> THEN the following routes are built after network customization:
> 0.0001 ETH (Mainnet) -> 0.0001 ETH (Opt)
> 0.002 ETH (ARB) -> 0.002 ETH (ARB)

Should be this instead to make it even with total value?
WHEN: Entered amount = 0.003 ETH
THEN the following routes are built after network customization:
0.001 ETH (Mainnet) -> 0.001 ETH (Opt)
0.002 ETH (ARB) -> 0.002 ETH (ARB)

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko
> 
> > WHEN: Entered amount = 0.003 ETH
> > THEN the following routes are built after network customization:
> > 0.0001 ETH (Mainnet) -> 0.0001 ETH (Opt)
> > 0.002 ETH (ARB) -> 0.002 ETH (ARB)
> 
> Should be this instead to make it even with total value? WHEN: Entered amount = 0.003 ETH THEN the following routes are built after network customization: 0.001 ETH (Mainnet) -> 0.001 ETH (Opt) 0.002 ETH (ARB) -> 0.002 ETH (ARB)

hi @IvanBelyakoff Yes, it should work that way, but it didn't. We didn't have multi-routing showing via [this issue](https://github.com/status-im/status-mobile/issues/20700). So, the only way to build a multi-route is to make some customizations.

**Comment by IvanBelyakoff** [comment]
<img width="557" alt="Screenshot 2024-07-19 at 11 48 35" src="https://github.com/user-attachments/assets/58cb3260-c1d0-415b-9a02-eeeacdc56955">
On desktop multi-routing seems to work. Not sure about all the cases, but this tx worked and was successfully executed on both sepolia mainnet and optimism:
https://sepolia.etherscan.io//tx//0xbe0baaa1d97b1d759537dc06a772cb5073afef256c737cf7081e6aebc312b8c5
https://sepolia-optimism.etherscan.io/tx/0x5228e64026dc4af1c5f4da914197e070b6f7df25bc4327fdd5e9a26487446909

The only issue with this dialog was that it displayed No gas on optimism, while that is not true (I made sure there was enough ETH for gas on optimism)

But this tx automatically suggested the route. No manual customisation. What is broken on desktop - locking the value in Send modal. If we try to lock it on some chain, it is not respected and reset

**Comment by VolodLytvynenko** [comment]
> <img alt="Screenshot 2024-07-19 at 11 48 35" width="557" src="https://private-user-images.githubusercontent.com/15627093/350363258-58cb3260-c1d0-415b-9a02-eeeacdc56955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODc1MDMsIm5iZiI6MTcyMTM4NzIwMywicGF0aCI6Ii8xNTYyNzA5My8zNTAzNjMyNTgtNThjYjMyNjAtYzFkMC00MTViLTlhMDItZWVlYWNkYzU2OTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDExMDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZDA0NTZjNTdhMDA3NWExMzFhYTZmMDUxZDdkZmQxODAwOWRiODU4ZWIwNGYxY2EyMDAyMWExZGFjZGU5ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zdQRPbEhK06daoDQANJ7HvRezzyIPQSzkaaubOvsFgY"> On desktop multi-routing seems to work. Not sure about all the cases, but this tx worked and was successfully executed on both sepolia mainnet and optimism: https://sepolia.etherscan.io//tx//0xbe0baaa1d97b1d759537dc06a772cb5073afef256c737cf7081e6aebc312b8c5 https://sepolia-optimism.etherscan.io/tx/0x5228e64026dc4af1c5f4da914197e070b6f7df25bc4327fdd5e9a26487446909
> The only issue with this dialog was that it displayed No gas on optimism, while that is not true (I made sure there was enough ETH for gas on optimism)
> 
> But this tx automatically suggested the route. No manual customisation. What is broken on desktop - locking the value in Send modal. If we try to lock it on some chain, it is not respected and reset

@IvanBelyakoff That's good news! thanx for update
