### ISSUE TITLE
Mismatch of collectibles on watched address

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#20579]
# Bug Report

## Problem 
For collectibles from watched addresses, we have a mismatch in the assets displayed versus the assets that exists for that account. For example for this account `0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5` they have 3 assets collected according to open sea https://opensea.io/0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5, those 3 are the same fetched on the desktop app:

![image](https://github.com/status-im/status-mobile/assets/45393944/dc3f9d18-3e0a-481a-9e31-f9734f76d55c)

on the mobile app, the collectibles are fetched but it shows other collectibles not belonging to the current account:
![Simulator Screen Recording - iPhone 11 Pro - 2024-06-25 at 13 45 47](https://github.com/status-im/status-mobile/assets/45393944/54395be3-1143-4e62-bf28-0fe67df541bf)

#### Expected behavior
The fetched collectibles should be the same as what the address has

#### Actual behavior
The collectibles includes other collectibles not belonging to the address

### Reproduction

1. Go to wallet
2. Add this address `0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5` as watched address
3. Click on the collectibles tab for the address added
4. Observe the collectibles dispalyed

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ulisesmac** [comment]
@BalogunofAfrica 

I don't think this is an issue, the collectibles shown in the mobile app are on Optimism, on OpenSea Optimism is not a listed network.

**Comment by ulisesmac** [comment]
Tagging @J-Son89 @VolodLytvynenko  to get their perspective

**Comment by VolodLytvynenko** [comment]
hi @BalogunofAfrica I think this is not an issue. I use a Desktop and see the same collectibles as on mobile for this `0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5 ` address. Here is a screenshot:

![image](https://github.com/status-im/status-mobile/assets/52490791/895d59c4-d0e3-4e43-8188-150896f6a3e6)

Moreover, the same collectibles are shown on OpenSea. To enable showing all of the collectibles, select the 'hidden' option:
![image](https://github.com/status-im/status-mobile/assets/52490791/d45e4b2e-a960-46bb-8a18-46c4ba27eb33)

Alternatively, you can add this address as a watch-only wallet in TrustWallet, and all collectibles will be shown for this wallet as well:
![image](https://github.com/status-im/status-mobile/assets/52490791/6b16f435-45de-47c5-834b-4e202fcc7a9f)
