### ISSUE TITLE
Balances not fetched for some networks after account restoration until relogin

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20587]
Unfortunately, the issue does not reproduce frequently. I hope the logs might help.

### Steps:
1. Restore a user with available assets on networks (mainnet).
2. Check the balances fetching.

### Actual result:
For some networks, the balances are not fetched. (In my case, for the ETH asset, the L2 balances = 0).

https://github.com/status-im/status-mobile/assets/52490791/51dde803-cf91-4f73-95dc-2ec1ce3f665c

### Expected result:
The balances are fetched for all networks after account restoration.

### ENV:
- Nightly: Moblie: [27 Jun 2024]
- Desktop:  Nightly: [27 Jun 2024] 

### Logs
[desktop routes.txt](https://github.com/user-attachments/files/16012107/desktop.routes.txt)

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - is this issue still valid?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - is this issue still valid?

@smohamedjavid For me, it hasn't happened again after restoring. However, it often occurs when the app is left in the background and then returned from it. Not sure if the cause is the same. I will try to reproduce it and add the logs

**Comment by briansztamfater** [comment]
Just to confirm, this is happening on both desktop and mobile, right?

**Comment by VolodLytvynenko** [comment]
> Just to confirm, this is happening on both desktop and mobile, right?

@briansztamfater correct

**Comment by VolodLytvynenko** [comment]
@briansztamfater just got this issue one more time. After login the balance is not fetched fully until wallet is refreshed

https://github.com/user-attachments/assets/8288aaef-859e-494d-9b4c-6ddd479b004a

### Logs:
[Uploading Status-debug-logs.zip…]()

**Comment by J-Son89** [comment]
re: https://github.com/status-im/status-mobile/issues/20587#issuecomment-2252144576
@VolodLytvynenko, @briansztamfater - seems we should communicate this issue to the Desktop team since they're mostly responsible for issues in Status-Go around Wallet etc.
cc @alaibe, @dlipicar

**Comment by alaibe** [comment]
@J-Son89 Can this be tested now that we have: https://github.com/status-im/status-go/pull/5647/files

**Comment by J-Son89** [comment]
Sure, we'll check that. Thanks @alaibe!

**Comment by churik** [comment]
I believe this can be related to https://github.com/status-im/status-mobile/issues/20975 and it might be better after finding the reason.

Anyway, due to time constraints, I'll exclude this one from 2.30 and we'll get back to it in 2.31

**Comment by churik** [comment]
It is related to RPC provider issues, so should be fixed along with more stable solution

**Comment by VolodLytvynenko** [comment]
can't reproduce it anymore
