### ISSUE TITLE
Routes are not recalculated If at least one locked network Is disabled

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20584]
### Steps:
1. Recover a user with available assets on at least two networks.
2. Enter the amount you are going to send to build the route. (NOTE: The current amount should be available on each network. In my case, the user has: 0.005 ETH, 0.005 OPT, 0.01 ARB. Total entered amount = 0.002 ETH).
3. Go to the 'Custom' tab.
4. Mark the built network as 'locked' by entering a 0.001 ETH value (now the additional route is built).
5. Disable the current 'locked' network in the 'Advanced' tab.

### Actual result:
The amount is not recalculated for other enabled networks

https://github.com/status-im/status-mobile/assets/52490791/feb316ab-0f83-4c97-b094-e59bce7b4c1c

### Expected result:
The amount is recalculated for other enabled networks

### ENV:
Nightly: 26 Jun 2024
Desktop: Master: Status go 0.179.9, Version 0.9.90

### Logs
[logs (1).txt](https://github.com/user-attachments/files/15993635/logs.1.txt)

**Comment by VolodLytvynenko** [comment]
Potentially, it should be fixed by https://github.com/status-im/status-go/pull/5426

**Comment by J-Son89** [comment]
I will close this issue for now as Multichain routing is descoped for 2.31 and by 2.30 we will remove route custoimisation/locking
