### ISSUE TITLE
No routes found when network is marked as locked

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20583]
### Steps:
1. Recover user with available assets
2. Enter the amount you are going to send to build the route.
3. Disable all other networks except the built one in the 'Advanced' tab -> in the "Send From" section.
4. Go to 'custom' tab
5. Mark the network as 'locked'

### Actual result:
No routes are found

Desktop:

https://github.com/status-im/status-mobile/assets/52490791/2d4d9a9c-bd6c-488e-bf93-d4cdf08e9d51

Mobile:

https://github.com/status-im/status-mobile/assets/52490791/c0a03d54-3be8-45fa-bf36-e1fe52936849

### Expected result:
The route is still shown when the network is marked as 'locked'.

### ENV:
- Nightly: 26 Jun 2024
- Desktop: Master: Status go 0.179.9, Version 0.9.90

### Logs
[logs.txt](https://github.com/user-attachments/files/15992826/logs.txt)

**Comment by VolodLytvynenko** [comment]
Potentially should be fixed by https://github.com/status-im/status-go/pull/5426

**Comment by J-Son89** [comment]
I will close this issue for now as Multi-chain routing is descoped for 2.31 and by 2.30 we will remove route customisation/locking
