### ISSUE TITLE
Save Address bottom sheet menu item is present and is not implemented

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20588]
# Bug Report

#### Expected behavior
Save Address bottom sheet menu should be hidden as it is not in the 2.30 scope

#### Actual behavior
Save Address bottom sheet menu is visible
<img width="331" alt="Screenshot 2024-06-25 at 17 08 49" src="https://github.com/status-im/status-mobile/assets/147824399/ee510c7c-e79e-4524-988f-4efcb23a2615">

### Reproduction

1. Login to app
2. Go to Wallet - Collectibles tab
3. Tap Scanner icon on the top of the screen
4. Scan smb address

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
@J-Son89 - Shall we remove this entry point to save the address for 2.30?

**Comment by J-Son89** [comment]
thanks @smohamedjavid - I addressed this here already: https://github.com/status-im/status-mobile/pull/20494

i.e I feature flagged it. Will close this issue
