### ISSUE TITLE
Spectated communities are never closed

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#20594]
# Problem

When a user opens a community but never joins it, the community stays in the `spectated` state and accessible in the `Opened` tab in the home screen, forever, even after logout. Each spectated community will eat considerable resources, much like a community the user has joined. This is a form of resource leak.

The main performance cost here for the mobile app comes from the overhead of keeping the state in sync as signals arrive for a community (esp. a large one), given that we globally process signals independently of the current screen the user is at.

Original discussion in https://github.com/status-im/status-mobile/pull/20508#issuecomment-2188587426.

## Implementation

Based on a private discussion with @cammellos:

1. Spectated communities would be sort of garbage collected every X time (like once every 7 days if the user hasn't interacted with the spectated community).
2. Limit the insertion of new spectated communities to a max number of 5-10, or any small(ish) number and in a FIFO fashion.

This automatic approach should be preferred because it could be confusing to users to leave/close/unspectate communities manually. Additionally, it wouldn't be obvious to users why manually closing spectated communities is necessary.

## Scope

Although the problem exists in theory, it shouldn't affect users at the moment because creating communities is disabled on status-desktop and creation is also not available on mobile, therefore we should postpone work on this issue.

**Comment by ilmotta** [comment]
I checked the Desktop app and it does something different. It actually allows the user to close a spectated community by right clicking and choosing the option "Close Community". The endpoint called is `wakuext_leaveCommunity`.

We should do the same and not go for the more complicated garbage collection approach mentioned in the issue description. Ideally, this issue should be solved alongside https://github.com/status-im/status-mobile/issues/20762, otherwise the user will have to frequently close spectated communities because we incorrectly spectate them automatically whenever Discover Communities is opened.

In the desktop app, the user doesn't see any confirmation pop-up when leaving a spectated community. We can add an option to the community drawer saying "Close Community" when long pressing on a spectated community.

To anyone working on this issue, please confirm with designers this is the expected behavior before proceeding with implementation.

**Comment by churik** [comment]
I don't think that we have a capacity for it in 2.32, given the desired release cut date.
Deferring the issue, please be free to move it bak if you think there is a room for it @ilmotta

**Comment by ilmotta** [comment]
@seanstrom do you have any work in progress solution for this issue? If yes, then if it's simple to implement and finish still this week and QA it would be worth including in 2.32. If no, then it's perfectly fine to move to 2.33 as @churik suggested.

**Comment by seanstrom** [comment]
@ilmotta Yeah I do have something ready for review: https://github.com/status-im/status-mobile/pull/21687

I think it mainly needs to be reviewed, but we also need some opinions on whether to open a confirmation modal to leave/close a community. And whether the action to close a community should be rendered in red text. Otherwise, I think the PR is ready to go 👍

**Comment by ilmotta** [comment]
> [@ilmotta](https://github.com/ilmotta) Yeah I do have something ready for review: [#21687](https://github.com/status-im/status-mobile/pull/21687)
> 

Sorry I somehow missed your PR.

> I think it mainly needs to be reviewed, but we also need some opinions on whether to open a confirmation modal to leave/close a community. And whether the action to close a community should be rendered in red text. Otherwise, I think the PR is ready to go 👍

Given the amount of things @xAlisher has to deal with nowadays, I think the best way for us to get answers about mobile designs is discussions in channels tagging him.

@seanstrom it's a good idea to signal somehow in the PR that it's not ready to be merged if there are open points. Sometimes I used the `blocked` label when the feedback came live from reviewers, or sometimes I just transform back to draft. I know you know all this, just reiterating.

That PR probably needs to be QAed since it's a new feature and QAs have some other processes to document mobile features. Edit: Adding the label `request-manual-qa` would be good in this case.
