### ISSUE TITLE
Can't create a profile after navigating to "Sync or recover profile" > "Use recovery phrase" and back to new profile creation

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20598]
# Bug Report

## Problem 

The `Continue` button on the `Create profile` screen stops responding after entering a profile name.
To reproduce it you need to take the following steps:

1. Install Status
2. Go to `Sync or recover profile`
3. Press `Use recovery phrase`
4. Press `back` two times to get back to the intro (the first) screen
5. Press `Create profile` > `Let's go`
6. Enter name > press `Continue`

https://github.com/status-im/status-mobile/assets/67952253/3ba3349b-7e90-4927-9087-d78761781381

#### Expected behavior
Can continue the profile creation flow

#### Actual behavior
Nothing happens, the `Continue` does not respond

### Additional Information

- Logs: [navigation.log](https://github.com/user-attachments/files/16028731/navigation.log)

- Status version: nightly 28/06
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
I bumped the priority from low to medium because friction during onboarding should be considered of greater importance at this stage of the product.
