### ISSUE TITLE
Endless loading skeleton for some empty channels on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20599]
# Bug Report

## Problem 
Some channels are stuck forever in "loading" state.
For Android all channels, including empty ones are loaded in ~5 mins

#### Expected behavior
can see the chat view

#### Actual behavior
https://github.com/status-im/status-mobile/assets/4557972/f0ff7190-4095-4dc3-b923-ba1e784c1f6e

### Reproduction

1. Open Status community
2. Go through several channels and back to catch the skeleton

### Additional Information

- Status version: nightly 28/06/24
- Operating System:  iOS

[comment]: # (Please, add logs/notes if necessary)

[logs (93).zip](https://github.com/user-attachments/files/16029627/logs.93.zip)

**Comment by Parveshdhull** [comment]
hi @churik https://github.com/status-im/status-mobile/pull/20602 is merged. If you still encounter this issue please reopen the issue and let me know.
