### ISSUE TITLE
No Unsigned Transaction screen is shown if send tx in chat with 2 members [feature/command-scopes]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2061]
### Description

*Type*: Bug

*Summary*: 
User can't send a transaction in group chat with 2 members because Unsigned transaction screen is not shown after tap on send button. Instead, same chat is shown with nothing in the input field

#### Expected behavior
If send command gets valid parameters and user taps on send button then Unsigned transaction screen is shown
#### Actual behavior
same chat is shown with nothing in the input field

### Reproduction
(from 00:41) https://app.testfairy.com/projects/4803622-status/builds/6783719/sessions/8/?accessToken=ONT3syhpY2Zo72TKoD0cPycUZQM
- Open Status
- Create group chat with 1 member, so in total there are 2 members: you and e.g. Jarrad 
- In group chat tap on send command. Note that there is no suggestions shown
- type valid amount and tap on send button

### Additional Information
* Status version: feature/command-scopes  0.9.10-175-g9a4ef51a
* Operating System: 
Real device iPhone 7 plus, iOs 11.0.2
Real device Google Pixel XL, Android 8.0

**Comment by asemiankevich** [comment]
This is fixed in `0.9.10-215-g45b94306+` both android and ios
