### ISSUE TITLE
Update Sign in flow on Profiles list screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20628]
Recently we have updated onboarding flow here https://github.com/status-im/status-mobile/pull/20386

Following this update we should also make corresponding changes on Profiles list screen and update old "Add existing Status profile" flow to a new "Sync or recover profile" flow. 

**Expected result:** 

old "Add existing Status profile" flow is replaced by "Sync or recover profile" flow. 

https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4357-629658&t=vvOfUvedfeFY2Zbj-0

<img width="749" alt="Onboarding for Mobile – Figma 2024-07-02 16-31-20" src="https://github.com/status-im/status-mobile/assets/97245802/43efb148-9fa3-473a-a9de-136236489c77">

**Comment by churik** [comment]
not sure about urgency of this one, seems currently we do not have capacity to do this; however, the current flow might be confusing.

For now moved it to 2.31
