### ISSUE TITLE
Scan missing keypair keep scanning after success attempt 

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#20638]
# Bug Report

## Problem 

When you try to scan a key pair QR, the user will be shown the password authentication bottom sheet, while on the sheet, try to keep your phone camera directed at the QR, the bottom sheet will be closed and shown again until you move the phone away.

#### Expected behavior

It should navigate back from scanner and then open password authentication bottom sheet.

#### Actual behavior

It keep scanning the QR code in scanner page and re-open password authentication bottom sheet. 

https://github.com/status-im/status-mobile/assets/71308738/61bd04b7-816f-4373-a035-0d79d17fb993

**Comment by mariia-skrypnyk** [comment]
Hey @mohsen-ghafouri !

Will have an ability to test your PR when this fix will be merged https://github.com/status-im/status-mobile/pull/20611 as now we do not have three dots menu working.
Hope it will take 1 extra day.

**Comment by mariia-skrypnyk** [comment]
Hey @mohsen-ghafouri !
I've checked your fix on both platforms and it works correct.
As we have issues with e2e tests at the moment I'v checked regression places that could be affected:

- Sync QR coscanning
- Wallet QR scanning
- Profile QR scanning

So, you can merge your PR.
