### ISSUE TITLE
Preferred networks not saved for watch-only Account

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20644]
### Steps:
1. Go to watch-only account creation.
2. Add an address with a prefix of the network (e.g., `eth:0x300e31aaf34ab0327eaf6624c543dbe19f44bbd3`).
4. Complete the watch-only account creation.
5. Check the network preferences of the newly created watch-only account.

### Actual Result:
Preferred networks specified during account creation are not saved as preferred.

https://github.com/status-im/status-mobile/assets/52490791/6e028e50-64f9-49bd-8c7b-36333d3244b3

### Expected result:
Preferred networks specified during account creation should be saved as preferred.
![image](https://github.com/status-im/status-mobile/assets/52490791/8ee2d0fd-9251-449b-94a7-99eb6376ca34)

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### ENV:
Nightly 3 Jul 2024

**Comment by churik** [comment]
closing for now, as adding watch-only accounts in removed
