### ISSUE TITLE
Activity validation message not shown in "Add address to watch" screen

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#20651]
# Bug Report

## Problem 
Next messages not shown: 

- Scanning for activity..., 
- This address has not activity, 
- This address has activity, 
- Scanning failed. 

Design can be found here: https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=2052-522327&t=wPZRaDaaPtefkWLl-0 This validation worked in previously version Mobile Status nightly (1.07)# 

### Reproduction

1. Open wallet
2. Click the button "Add"
3. Choose the option "Add address to watch"
4. Paste the correct ETH address or ENS name

### Expected behavior
Info message is shown.

https://github.com/status-im/status-mobile/assets/150926723/83264660-cf5b-42f2-8d09-a0332f647de9

### Actual behavior
Info message is NOT shown.

https://github.com/status-im/status-mobile/assets/150926723/a1976585-3d44-4d7f-8367-02b80c586747

### Additional Information

- Status version: nightly/4.07 
- Operating System: Android, iOS

**Comment by churik** [comment]
closing for now, as adding watch-only accounts in removed
