### ISSUE TITLE
Add metrics to the app

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20664]
As a status cc
I would like to see usage metrics
So we can better understand with features are used and which ones are not, to help us drive product decisions

### Description

We agreed to add opt-in metrics to the app. 
In the scope of this issue we should make sure that metrics are sent and at least one path is covered (that's to be defined). 
The metrics should be opt-in, @pedro-et will provide a design in due time.

### Acceptance criteria
- When a user upgrade the app, they should see an opt-in screen for metrics
- When a user installs the app for the first time, they should see an opt-in screen for metrics
- Metrics collected should be sent to our provider if the user has opted in
- The user should be able to toggle on/off metrics from settings
- At least one path should be covered by metrics (path to be defined)

**Comment by xAlisher** [comment]
Mobile:
Onboarding https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=13726-29112&t=FqVNGdWQxOXNwUaH-1

Settings https://www.figma.com/design/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?node-id=7845-4152&t=dDP5v2iKx3OqhAvM-0

**Comment by churik** [comment]
@ilmotta that can be closed or postponed? 
I believe initial implementation has been made and nobody is working on that anymore

**Comment by ilmotta** [comment]
@churik, we are already tracking a few actions, like:

- App started
- Navigating to the create profile screen
- Opening the communities, wallet and the chats tabs.

There are ongoing discussions and a meeting scheduled for early next week to align which metrics we want to track. I believe it might be possible that some new actions will be tracked for 2.30 if we can easily cherry pick them on the release branch and are easy to implement.

**Comment by ilmotta** [comment]
We can keep this issue open at least until next Tue/Wed and then we can re-evaluate if it's worth tracking something else. Does that sound good for you?

**Comment by churik** [comment]
sure, thanks!

**Comment by ilmotta** [comment]
- Linking with PR that can close this issue https://github.com/status-im/status-mobile/pull/20926
