### ISSUE TITLE
User is navigated to transaction confirmation page if multi-collectible is selected during single collectible sending flow

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20678]
The current issue will probably be fixed with [this one](https://github.com/status-im/status-mobile/issues/20677), as they seem to have the same root cause.

### Steps:
1. Go to wallet
2. Open account
3. Tap 'send'
4. Select collectible on the "Select assets" page
5. Go back to "Select assets" page
6. Select multi collectible

### Actual result:
User is navigated directly to confirmation transaction page after multi collectible is selected 

https://github.com/status-im/status-mobile/assets/52490791/f95034ef-4b72-4e1d-9a90-dcfd7173e37b

### Expected result:
User is navigated to collectible page to specify count of collectibles which going to be sent

https://github.com/status-im/status-mobile/assets/52490791/2ec5e11d-05cf-4c43-aac5-36c2dc92d9a7

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly [8 Jul 2024]

**Comment by ulisesmac** [comment]
@VolodLytvynenko 
It's no longer reproducible, video:

https://github.com/user-attachments/assets/09fe3cd4-6c3f-43e1-9871-9bda9fdca94c
