### ISSUE TITLE
User is navigated to transaction confirmation page if asset is selected during collectible sending flow

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20677]
The current issue will probably be fixed with [this one,](https://github.com/status-im/status-mobile/issues/20678) as they seem to have the same root cause.

### Steps:
1. Go to wallet
2. Open account
3. Tap 'send'
4. Select collectible on the "Select assets" page
5. Go back to "Select assets" page
6. Select token

### Actual result:
User is navigated directly to confirmation transaction page after token is selected

https://github.com/status-im/status-mobile/assets/52490791/faee5b1c-7014-4a80-8fa2-85b6035c049d

### Expected result:
User is navigated to route generation page 

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly [8 Jul 2024]

**Comment by churik** [comment]
postponing due to time constraint
