### ISSUE TITLE
User is navigated to transaction confirmation page when multi-collectible is selected

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20686]
The current issue will probably be fixed with https://github.com/status-im/status-mobile/issues/20678, as they seem to have the same root cause.

### Steps:
1. Restore user with multi-collectible.
2. Go to wallet main page.
3. Tap on multi-collectible.
4. Tap 'send' 
5. Navigate to the transaction confirmation page.
6. Tap back to the 'send to' page.
7. Go forward again

### Actual result:
The transaction confirmation page is shown after user navigates forward from the 'send to' page

https://github.com/status-im/status-mobile/assets/52490791/1635b8fc-417e-4d13-b565-9bbb9d60d8da

### Expected result:
The collectible review send page is shown 
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15329-122196&t=yK8IMGkT0DvfkWqc-0

### ENV:
Nightly 8 Jul, 2024

**Comment by shivekkhurana** [comment]
Is this still an issue ? the alleged root cause issue was closed.

**Comment by ulisesmac** [comment]
No longer reproducible, video:

https://github.com/user-attachments/assets/74f90095-9e5b-4bd5-8568-b0cefa49ab35
