### ISSUE TITLE
'Open' and 'Gated' tabs on Communities Discovery screen do not filter anything

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20682]
**Steps:** 

1. Open Communities Discovery screen
2. Wait until curated communities are loaded (make sure you are not using testnet mode)
3. Navigate to 'Open' and 'Gated' tabs
4. See if any communities are filtered within those tabs

**Expected result:** communities are filtered. Or we can temporary hide those tabs. cc @ilmotta 

**Actual result:** filter does not work, both tabs are empty 

https://github.com/status-im/status-mobile/assets/97245802/3dd17fc6-c073-46fc-85d3-81a282f606a5

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ilmotta** [comment]
Let's hide the tabs as you suggested @pavloburykh. I'll do it now.
