### ISSUE TITLE
App randomly gets stuck on login page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20688]
### Problem:
The app can randomly get stuck on the login page. Unfortunately, there are no exact steps to reproduce it. This usually happens if the user has been active within the app for a while and then returns to the login page. Hope the logs might help

### Actual result:
The app randomly stuck on the login page

https://github.com/status-im/status-mobile/assets/52490791/ab693ae7-3b9e-401c-8508-87b972bf4562

### Expected result:
The app should not get stuck on the login page and should allow the user to log in without issues.

### logs:
[login logs.txt](https://github.com/user-attachments/files/16141486/login.logs.txt)

**Comment by qoqobolo** [comment]
Closing this one in favor of https://github.com/status-im/status-mobile/issues/21001
