### ISSUE TITLE
Background overlay image missing in android

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#20696]
# Bug Report

### Design
![image](https://github.com/status-im/status-mobile/assets/17097240/e8ac9599-0231-44f9-8a5d-d3aad7742686)

### Develop

https://github.com/status-im/status-mobile/assets/17097240/b5990268-1405-4bd5-b4f3-a0de39a47dab

**Comment by Parveshdhull** [comment]
https://discord.com/channels/1210237582470807632/1217173176086302821/1260245834889564200

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/pull/20308
