### ISSUE TITLE
The currency doesn’t show up in the mobile app when you change it on the desktop

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#20694]
# Bug Report

## Problem 
The currency doesn’t show up in the mobile app when you change it on the desktop. Also, it doesn’t convert from dollars to the new currency. If the currency is changed back to dollars, the issue persists.

### Reproduction
1. Sync the mobile app with the desktop.
2. Desktop Settings -> Language&Currency -> Set Display Currency
3. Choose EUR
4. Open wallet on desktop and mobile

#### Expected behavior
Money is converted to the new currency, and the currency symbol is displayed. The data in both apps matches.

#### Actual behavior
Money is not converted to the new currency, and the currency symbol is not displayed. The data in both apps does not match.

### Additional Information

- Status version: nightly (9/07/2024)
- Operating System: Android, iOS

![before](https://github.com/status-im/status-mobile/assets/150926723/721d6789-0066-4b84-8f69-34639e6b4699)
![after](https://github.com/status-im/status-mobile/assets/150926723/c64158e4-4787-4eef-92c4-f14776820c17)
![mobile](https://github.com/status-im/status-mobile/assets/150926723/3697fbaf-ea6a-45bb-bc31-66c1170fd473)

**Comment by J-Son89** [comment]
@smohamedjavid / @churik - so should we move this issue to 2.31, and in the interim we default the fallback value to USD? wdyt? 🤔

**Comment by smohamedjavid** [comment]
@J-Son89 - Yes, Let's move it to 2.31 👍 . I will make a PR for fallback to USD.
