### ISSUE TITLE
Show the right message when users are added or removed from a group chat

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#20716]
# Bug Report

When adding users to a group chat for the first time things look okay however when you select and deselect a few users to add to the group members you get a mix of system message that the selected users have been added and the same users have left the group. 

https://github.com/status-im/status-mobile/assets/28704507/088ced71-3631-4e76-b1ec-39b9506e2e64

#### Expected behavior
The new message should show users have either been added or left and not both at the same time

#### Actual behavior
The new message shows that users have either been added and have left the group chat whether its true they have or not 
<img width="228" alt="Screenshot 2024-07-20 at 00 31 33" src="https://github.com/user-attachments/assets/8f0a1b27-a95d-457d-9538-7179eff38229">
### Reproduction

1. Open Status app
2. Navigate to messaging tab
3. Navigate to create a new chat
4. Select more than one contact and save
5. Select more contacts and deselect some group members
6. Observe the new message in chat
7. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
can be closed because of https://github.com/status-im/status-mobile/pull/21082
