### ISSUE TITLE
List of issues on Onboarding screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20719]
# Bug Report

Here are several leftovers from https://github.com/status-im/status-mobile/pull/20503

#### Actual behavior

1) No blur on `Enable Notifications` and `Welcome to web3!` screens

<img width="227" alt="Screenshot 2024-07-11 at 12 07 25" src="https://github.com/status-im/status-mobile/assets/147824399/97c445c6-ee32-48db-8d4b-b1104be012d8"> <img width="230" alt="Screenshot 2024-07-11 at 12 07 35" src="https://github.com/status-im/status-mobile/assets/147824399/2e630c23-ee0f-4246-abf9-98c23acf31af">

2) No smooth transition from `Key Saved!` to `Enable Notifications` screen
Please, look what I am talking about : 

https://github.com/status-im/status-mobile/assets/147824399/7858f9cd-8477-48a9-af2e-2dd59486d705

3) Pixel 7a (Android 14) has unexpected white space at the bottom of the screen:

<img width="327" alt="Screenshot 2024-07-09 at 16 29 31" src="https://github.com/status-im/status-mobile/assets/147824399/4872f42f-67bd-4932-8776-042c35d27be6">

### Reproduction

1. Install app
2. Tap `Let's go`
3. Go through onboarding screens

### Additional Information

- Status version: nightly 11/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
@flexsurfer looking at this comment here https://github.com/status-im/status-mobile/pull/20503#discussion_r1662187192 do you suggest that we involve design to some how reconfigure how we navigate onboarding

**Comment by Parveshdhull** [comment]
Maybe we avoid init-root approach and

1. Instead of navigating to onboarding/navigate-to-identifiers, keep onboarding/navigate-to-enable-notifications (which uses navigate-to-within-stack in develop)
2. Then as @jo-mut  already did, get rid of back button - https://github.com/status-im/status-mobile/pull/20503/files#r1654635905
3. Also disable hardware back button for this screen for android and ios (as we do for chat screen)

This way, we will still have overlay and without back button

**Comment by J-Son89** [comment]
@ilmotta, @pedro-et - I believe there was already discussion to remove the "Welcome to Web3" page as there is not much need for it? 🤔

**Comment by jo-mut** [comment]
> Maybe we avoid init-root approach and
> 
> 1. Instead of navigating to onboarding/navigate-to-identifiers, keep onboarding/navigate-to-enable-notifications (which uses navigate-to-within-stack in develop)
> 2. Then as @jo-mut  already did, get rid of back button - https://github.com/status-im/status-mobile/pull/20503/files#r1654635905
> 3. Also disable hardware back button for this screen for android and ios (as we do for chat screen)
> 
> This way, we will still have overlay and without back button

am not sure of any other approach to fix this without involving designers. I had already done this before so am up open to ideas @flexsurfer

**Comment by yqrashawn** [comment]
Agree with @Parveshdhull, keep nav stack, remove nav back
Or make a fake starter screen as new root and nav to the notification screen right after it, but nav back is still an issue

**Comment by flexsurfer** [comment]
yes as i many times said in the prev PR, we should just close the current stack or navigate within the current stack, last one is better and simpler I guess if we remove back navigation
