### ISSUE TITLE
[Spike] Look into making syncing more robust

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20717]
There's a wide variety of network configurations, and currently syncing struggles to be reliable in some cases.

This spike will look into at least providing a fallback for such cases. We want to answer the question:
1) How much work is involved into providing a fallback to the users (i.e scan through qr code), so that in case the network fails, users will still be able to have a basic account working on both devices?

It's timeboxed to 12/07/24 end of day.

**Comment by cammellos** [comment]
We had a few conversations, and for 2.30 the most likely solution is to fallback on seed phrase, discussion is ongoing.

**Comment by ilmotta** [comment]
Linking with PRs:

- https://github.com/status-im/status-mobile/pull/20940
- https://github.com/status-im/status-mobile/pull/20921
- https://github.com/status-im/status-go/pull/5614

**Comment by ilmotta** [comment]
@cammellos can we consider the spike done and close this issue?

**Comment by cammellos** [comment]
Yes, I think this can be closed
