### ISSUE TITLE
Improve `ChatMentionOnChangeText` and only return first 15 matches

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#20722]
Original Report: https://github.com/status-im/status-mobile/pull/20619#issuecomment-2222782325

> We only show 15 mentions at a time, not sure why we are returning whole members list on call of `wakuext_chatMentionOnChangeText` with text "@". I think returning first 15 matches will be enough

When we return whole member list, Mentions are delayed as shown in https://github.com/status-im/status-mobile/pull/20619#issuecomment-2222545233

Also time taken https://github.com/status-im/status-mobile/pull/20619#issuecomment-2222751526

**Comment by churik** [comment]
postponed due to limited capacity for 2.30
