### ISSUE TITLE
The count of multi collectibles is incorrectly shown on the wallet main page after sending it on the additional address

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20728]
### Steps:
1. The user has 2 wallet addresses
2. Send multi collectible form "Address 1" to "Address 2"
3. Check the result within the wallet main page

### Actual result:
- The Collectible is doubled on the collectible list view
- The count of Collectibles is incorrectly  shown on the collectible detailed page (shown as 5, but in fact = 9895)

https://github.com/user-attachments/assets/634be942-ad59-4609-84e2-66b28900da8c

- The collectible count is shown incorrectly on the list view of opened "account 1" (in my case shown as 19790, but if fact = 9895)
![image](https://github.com/user-attachments/assets/b9505b83-649d-4eec-8897-994f6af5aad0)

### Expected result:
The collectible is not doubled on the wallet main page; On the wallet main page the counf of collectible = total count of all collectibles on all available accounts

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Notes:
Problem can be solved on `status-mobile` side but there is also a [status-go issue](https://github.com/status-im/status-go/issues/5827) that causes it.

**Comment by churik** [comment]
postponed due to limited capacity for 2.30

**Comment by vkjr** [comment]
@xAlisher, during work on this task I noticed the lacking design solution.
When we have same multiple collectible on different accounts, lets say 10 one first account and 40 on second account, on the main page we should show that there are 50 total and display them as one item. But when we click on that item, collectible detail screen has owner `Account` record and it is unclear what to display when collectible exists on few accounts. Currently I display the first one, but maybe we have any other design solution already?

**Comment by vkjr** [comment]
@dlipicar, during work on this task I found out that part of the problem was that `status-go` returns duplicated record of collectible ownership, for example when I have collectible on 2 accounts, the ownership part of collectible structure looks like this:
```
[{:address "0xf90014b2027e584fc96e6f6c8078998fe46c5ccb",
  :balance "40",
  :tx-timestamp 1725278508}
 {:address "0xf90014b2027e584fc96e6f6c8078998fe46c5ccb",
  :balance "40",
  :tx-timestamp 1725278508}
 {:address "0x9d130330889345c7819f0d92574086a26e71e5c5",
  :balance "10", 
  :tx-timestamp -1}]

```
Do you know what could be the reason?

**Comment by dlipicar** [comment]
@vkjr huh that totally looks like a bug, must be messing up the query in some weird way. Or the DB got messed up and you've got duplicate entries for some reason :D

**Comment by vkjr** [comment]
@dlipicar, thanks, I will open an issue in `status-go` then!

**Comment by churik** [comment]
@vkjr please, link it to this issue, thanks!

**Comment by vkjr** [comment]
@churik, done

**Comment by Horupa-Olena** [comment]
@vkjr Your PR https://github.com/status-im/status-mobile/pull/21237 fixed only the duplication issue, the rest of the problems mentioned in the description remain. Therefore, I think it's too early to close it.
