### ISSUE TITLE
Frequent "network provider down" toast notification appears on all pages of the wallet

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20736]
### Steps:
1. Use the app as usual.
2. Observe the toast notifications appearing frequently.

### Actual result:
The toast "the provider for the following chains is down <network>" is shown repeatedly, regardless of the page the user is on.

https://github.com/user-attachments/assets/2a28c631-d564-4c28-84c4-2685da66d40e

### Expected result:
The toast notification should either: be removed entirely, or
Only be shown on the routes generation page.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### Logs:
[logs (4).zip](https://github.com/user-attachments/files/16612697/logs.4.zip)

### ENV:
Release 2.30 (20240814141744)

**Comment by VolodLytvynenko** [comment]
The issue is still reproducible within Release 2.30 (20240814141744). Updated logs

**Comment by shivekkhurana** [comment]
The notifications were fixed in #21055, but the issue still persists on the Go Side. 

~Should be fixed externally.~

**Comment by ulisesmac** [comment]
@shivekkhurana Should this issue be closed then?

**Comment by shivekkhurana** [comment]
@ulisesmac: @friofry  Is working to make the go side more reliable. Once his fix is in place, we can close this.

**Comment by churik** [comment]
I believe that issue can be closed, please reopen if it still makes sense to keep it opened 

cc @shivekkhurana @friofry
