### ISSUE TITLE
📷 DyDx missing profile photo on connection screen

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#20732]
# Bug Report

The connection screen of WalletConnect has issues when connection to DyDx.

| Design | Implementation |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/eee64c8d-b0fe-4a5e-a97f-0a647be8e73a) | ![IMG_9529](https://github.com/user-attachments/assets/c3c1ded6-962e-472e-a46f-966fc28a5f67) | 

## Problem 
- [x] Dapp logo not visible (likely an issue with DyDx as it is visible for many other dapps / related to #20731)
- [x] The info message box theme doesn't adapt to darkness
- [x] The actions buttons below have extra horizontal padding (was fixed by someone else already)

### Reproduction

1. Try to connect to dydx exchange

**Comment by Rende11** [comment]
I would like to fix it

**Comment by shivekkhurana** [comment]
Hi @Rende11. Thank you for the initiative to fix this issue. Unfortunately, we have a release coming soon and this is something that needs to be fixed quickly. 

So I've taken the liberty to unassign you and assign myself. I suggest you look at #20760 or #20758  if you want to contribute. Sorry for my action, but I hope you'll understand the urgency.

**Comment by Rende11** [comment]
Hi @shivekkhurana.
Got it! No problems =)
