### ISSUE TITLE
"insuffucient funds for gas" Insufficient funds for gas error shown after transaction confirmation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20739]
Unfortunately, I can't reproduce this issue again. It seems that when the user navigates to the confirmation page, the fee changes, and the user does not have enough assets to cover it. We should handle this issue by providing information in the 'activity' tab of the account, indicating that the transaction failed, without showing a toast notification. I hope the logs might help

### Steps:
1. Go to the routes generation page
2. Enter a boundary value to execute the transaction (e.g., if the user has 1 ETH, enter 0.99999 ETH).
3. Confirm transaction

### Actual result:
The toast with the error "arbitrum-sepolia-archival.rpc.grove.city.error:insuffucient funds for gas " error  is shown
![image](https://github.com/user-attachments/assets/ab5b79d2-5860-4773-9622-59b8c91895c6)

### Expected result:
Potential solution:
- The error toast is not shown.
- The user is navigated to the activity tab as usual.
- The failed transaction is shown as failed within the activity tab

### Logs:
[Status-debug-logs (3).zip](https://github.com/user-attachments/files/16192594/Status-debug-logs.3.zip)

**Comment by pavloburykh** [comment]
**UPDATE (Aug 7, 2024):** 

confirming that issue is still reproducible in release 2.30
![photo_2024-08-07 14 57 16](https://github.com/user-attachments/assets/857636d3-1beb-4442-9415-4fd7323786ca)

https://github.com/user-attachments/assets/79a1ffbd-fab4-481a-b39f-5a3e43ca6462

**Comment by mohsen-ghafouri** [comment]
Hello @pavloburykh @VolodLytvynenko do you have any suggestion to increase the chance to reproduce the issue, I was testing it on testnet and couldn't reproduce it. 

Also do you think it can be related to price volatility (for example in route generation page ETH price is 2500 and when user try to send transaction in confirmation page, price go higher like 2550) in this case you expect this behaviour? 
`We should handle this issue by providing information in the 'activity' tab of the account, indicating that the transaction failed, without showing a toast notification`

**Comment by mohsen-ghafouri** [comment]
This issue seems to be broader than just the confirmation page. The team has also encountered this error on the routing page, even when users had enough funds. It’s not limited to mobile, so it’s more likely a status-go side issue. 
![image](https://github.com/user-attachments/assets/41ff94ca-009f-4d76-872f-24c9576f0afe)

**Comment by pavloburykh** [comment]
> This issue seems to be broader than just the confirmation page.

Oh yes, for sure @mohsen-ghafouri There is another issue https://github.com/status-im/status-mobile/issues/20970 which we have discussed [here](https://discord.com/channels/1210237582470807632/1217172571917647932/1276097702471663648) and [here](https://discord.com/channels/1210237582470807632/1270072144067563520/1275842560140644477).

We can link this issue to 20970 or close current in favour of 20970. WDYT?

**Comment by mohsen-ghafouri** [comment]
@pavloburykh looks fine to me, we can open it again if we found it only related to confirmation page.
