### ISSUE TITLE
After adding an old account as watch-only there is incorrect sorting in the account list and it is impossible to delete

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#20741]
# Bug Report

## Problem 
If you add old watch-only accounts that have the address 0x0000000000..., the account display behaves incorrectly:

- The account appears first in the list, even though it should be last according to the rules.
- It cannot be deleted. The delete button does not work.

### Reproduction

1. Open Wallet in mobile app
2. Click to button "+"
3. Choose "Add  address to watch"
4. Enter ENS - tony.eth (or testtesttest.eth) 
5. CLick on button "Continue" and create new watch-only account.

#### Actual behavior

https://github.com/user-attachments/assets/5bb6024f-4c3e-48a5-9e9a-087f9c49dc53

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # This was also found by the user at 2:29, and their ENS is "tony.eth."

**Comment by churik** [comment]
Watch-only accounts are currently removed, don't think that will be introduced any time soon, closing the issue for now
