### ISSUE TITLE
Discover pixel perfect: Main screen (empty states)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2078]
Skeleton issue. Awaiting PR.

### User Story

As a user, I want to discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: Main Screen (empty states)

#### Expected behavior

![image](https://user-images.githubusercontent.com/1552237/31394509-cd264c36-adde-11e7-9824-9145297176a9.png)
![image](https://user-images.githubusercontent.com/1552237/31394519-d2480934-adde-11e7-9fc4-3518d200372f.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/1552237/31604061-72b692be-b262-11e7-9c93-bda709dbaa35.png)
![image](https://user-images.githubusercontent.com/1552237/31604070-79deb7e2-b262-11e7-9bf3-2012d3e4b505.png)
![image](https://user-images.githubusercontent.com/1552237/31604073-7ee3c7d2-b262-11e7-909c-ee5a2be93c2e.png)

## Must have
- [ ] Too wide top margin toolbar ( for iOS it should be 76, for android 80, check other tabs in our app please) (Oskar done in checkout, PR coming Oct 17)
- [ ] *Goran* If can fix in 1 hr do it otherwise move to nice to have  -  All content hidden behind right edge on smaller screen (check 5s)

## Nice  have
- [ ] Font weight "Recent statuses" etc bolder 
- [ ]  Titles for sections should be without letter spacing
- [ ] "No statuses text" should be grey ( color-gray4 [#939BA1] )
- [ ] Reduce size between title Dapps and dapps icons. it should be 24px
- [ ] Names os public chats are too bold, they need medium font weight
- [ ] Let's add a stroke to dapps icons. It will be much better with it. Use color: color-gray-transparent-light 
- [ ] improve the central alignment of empty state. Move icon a bit up
- [ ] check dapp name font size. In the mocks it's 14. 

- [ ] UI checklist
- [ ] Check Android

**Comment by goranjovic** [comment]
![simulator screen shot oct 17 2017 11 11 07 am](https://user-images.githubusercontent.com/711764/31656645-7fa2f70e-b32c-11e7-8313-68dea5ebb82b.png)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
