### ISSUE TITLE
`Undefined is not a function` when declining connection request

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20796]
Originally reported here https://github.com/status-im/status-mobile/pull/20711#issuecomment-2235953261

**Steps:** 

1. Scan wallet connect QR
2. Tap decline in connection modal
3. Observe the result

**Actual result:** `Undefined is not a function` error appears. 

[Status-debug-logs - 2024-07-18T113910.949.zip](https://github.com/user-attachments/files/16280210/Status-debug-logs.-.2024-07-18T113910.949.zip)

https://github.com/user-attachments/assets/79da100e-0889-4c80-bd27-94f96bf7fb86

**Expected result:** no error

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by clauxx** [comment]
@pavloburykh is it still reproducible for you? @alwx tried to reproduce it, but without success.

**Comment by alwx** [comment]
@clauxx not reproduceable for me either, was trying to do it several times with different dapps this morning.

**Comment by alwx** [comment]
@status-im/mobile-qa could you either provide more specific steps or at least validate if it's still the case?

**Comment by qoqobolo** [comment]
@alwx reproducible in 100% of cases for me on both iOS and Android, Mainnet (real dapps) and testnet (https://lab.web3modal.com/library/wagmi-siwe/). No specific steps. 


https://github.com/user-attachments/assets/2716f175-0e15-4a0b-9692-def29b2e97d4

**Comment by pavloburykh** [comment]
> @status-im/mobile-qa could you either provide more specific steps or at least validate if it's still the case?

I have tried in this [PR](https://github.com/status-im/status-mobile/pull/20811) and I am reproducing the issue.  

> provide more specific steps

I do not know how the steps can more specific than described [here](https://github.com/status-im/status-mobile/issues/20796#issue-2416344009). I have nothing to add. @alwx have you tried reproducing the issue using physical device + some rebased PR build?
