### ISSUE TITLE
Discover pixel perfect: Recent statuses

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2079]
Skeleton issue. Awaiting PR.

### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: Recent statuses.

#### Expected behavior

![image](https://user-images.githubusercontent.com/1552237/31394855-a7554b28-addf-11e7-8390-253456258549.png)
![image](https://user-images.githubusercontent.com/1552237/31394867-aa63da96-addf-11e7-8d78-d973abc2d53c.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/1552237/31394799-81e64e00-addf-11e7-9cb1-1b055d308b09.png)

## Must have

- [ ] margins from the screen edges should be 16 px (from the chat button to the right edge, 16 px from the left side to an userpick and status)  
- [ ] top status' text has a wrong margin from the top of the card. It should be 16px
- [ ]  the margin between chat button and the bottom of the status' card should 12px
- [ ]  separation lines between statuses should go from the edge to the edge. Check design in zepplin

## Nice have 
- [ ] Name icon not centered
- [ ] Grey background missing
- [ ] Toolbar lack of margin, not centered
- [ ] TEST Chat button missing / style

Probably more but start for now.

**Comment by goranjovic** [comment]
![screenshot_2017-10-11-13-54-04](https://user-images.githubusercontent.com/711764/31439418-5bde9836-ae8c-11e7-8b9c-de89a1d50ba8.png)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
