### ISSUE TITLE
Console/Wallet: Coinbase integration

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#208]
We should look at how users can get ETH in quickly with credit cards, otherwise p2p exchange for cash

**Comment by rabbit** [comment]
would be nice to also roll this functionality into a send operation so you can more easily gift ether to someone.

**Comment by jarradh** [comment]
That's a great idea! Do you mean funding your account from sending but have 0 balance or how do you imagine that would work?

@andmironov, that reminds me, we need to come up with the sending transaction flow to support erc20 tokens and GUI in suggestions (as opposed to simple number param)

**Comment by rabbit** [comment]
I left it open since I don't know what the exchange integration looks like and I'm unsure what the limitations are on commands. can they have multiple steps? my ideal scenario would augment the !send command to show my current balance and a purchase link that switches to the exchange integration. I fill my wallet up to my liking then it resumes the normal !send flow. starting with a 0 balance would disregard the first step or replace it with a teaser view to proceed to the purchase link.

**Comment by annadanchenko** [comment]
Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/415

**Comment by asemiankevich** [comment]
@goranjovic seems a separate swarm to me, wdyt?

**Comment by asemiankevich** [comment]
i am removing `wallet` label and we can probably discuss it like having a separate swarm in nearest future! :) @chadyj @jarradh i really like the idea of this issue, just concerned how urgent it is? like Q3 seems fine? (after Beta release)

**Comment by asemiankevich** [comment]
according to @chadyj we can do it in 170-wallet-improvement swarm

**Comment by chadyj** [comment]
Coinbase has a `Buy Widget` feature that makes purchasing small amounts of ETH easy with a US credit card. https://developers.coinbase.com/docs/buy-widget

The implementation looks straightforward but there may be potential Play and App Store guidelines to deal with.

<blockquote><img src="https://developers.coinbase.com/images/coinbase.png" width="48" align="right"><div><strong><a href="/docs/buy-widget/">Coinbase Buy Widget</a></strong></div><div>>APIs and developer tools to make it easier to build bitcoin, litecoin and ethereum blockchain applications.</div></blockquote>
