### ISSUE TITLE
Edit button appears below TO section on bridge screen when entering Invalid amount

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20809]
### Steps:
1. Go to the routes generation page using the bridge flow
2. Enter the valid amount (amount which is available to build the route)
3. Enter an invalid amount (an amount which is a bit less than the max value).

### Actual result:
The "edit" button appears below "TO" section

https://github.com/user-attachments/assets/34ff30e0-fb09-424b-8c0e-e3d8ba526adb

### Expected result:
The edit button is not shown on the bridge at all 

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 18 Jul, 2024

**Comment by OmarBasem** [comment]
@VolodLytvynenko I am not sure which edit button is this issue referring to, I don't see an edit button

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I am not sure which edit button is this issue referring to, I don't see an edit button

Hey. Apologies. This one. 
![image](https://github.com/user-attachments/assets/d5cdc356-998d-422f-b8c1-1cc0bbcfddce)

It is shown on the 27 second of the record [here](https://github.com/status-im/status-mobile/issues/20809#issue-2416899227)
