### ISSUE TITLE
Dapp requests are displayed for wrong Users restored within one Status app

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20800]
Originally reported here https://github.com/status-im/status-mobile/pull/20711#issuecomment-2236096885

Related to https://github.com/status-im/status-mobile/issues/20155

**Steps:** 

1. Create/restore User A and User B within one Status app
2. Login via User A
3. Connect to dApp
4. Logout User A and login via User B
5. Trigger any dApp request for User A
6. Observe the result

**Actual result:** request modal appears while being logged as User B

https://github.com/user-attachments/assets/617e40e6-9c1e-46ec-bc05-23abba79849e

**Expected result:** request modal should not appear as it has been triggered for another user 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by clauxx** [comment]
@pavloburykh is this related to https://github.com/status-im/status-mobile/issues/20155?

**Comment by pavloburykh** [comment]
> @pavloburykh is this related to #20155?

@clauxx yes

**Comment by alwx** [comment]
Potentially fixed by https://github.com/status-im/status-mobile/pull/20815
