### ISSUE TITLE
Discover pixel perfect: Popular hashtags

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2081]
Skeleton issue. Awaiting PR.

### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: Popular hashtags.

#### Expected behavior

![image](https://user-images.githubusercontent.com/1552237/31395729-bfcfd6b2-ade1-11e7-9b1a-511a17f48e41.png)
![image](https://user-images.githubusercontent.com/1552237/31395734-c25c450a-ade1-11e7-98ac-f39f3c979626.png)

#### Actual behavior

iOS only for now:

![image](https://user-images.githubusercontent.com/1552237/31395756-ce84f930-ade1-11e7-9e53-e832a581cf37.png)

#### List of things to fix (non-exhaustive)

- [ ] Wrong title text  and non-i18n too
- [ ] Toolbar missing margin, center title
- [ ] Grey bg
- [ ] Left align tag cloud
- [ ] Tag box style
- [ ] Scrollable tag list
- [ ] Name icon center #2119 
- [ ] Chat icon style #2119 

## Nice have 
- [ ] margins from the screen edges should be 16 px (from the chat button to the right edge, 16 px from the left side to an userpick and status)  
- [ ] improve alignment of hashtags in the top scroll view (checked on ios, they are not in the center of cell)
- [ ] top status (under hashtags) text has a wrong margin from the top of the card. It should be 16px
- [ ]  separation lines between statuses should go from the edge to the edge. Check design in zepplin
- [ ]  the margin between chat button and the bottom of the status' card should 12px

**Comment by goranjovic** [comment]
Chat icon is intentionally missing when it's your own status.

**Comment by goranjovic** [comment]
![screenshot_2017-10-11-13-54-17](https://user-images.githubusercontent.com/711764/31439456-79819348-ae8c-11e7-90eb-608b3e8a4685.png)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
