### ISSUE TITLE
app navigates to profiles screen displays a skeleton screen after generate keys

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#20819]
# Bug Report

After generate keys for a brief moment the profiles screen is shown and a skeleton screen before the user is navigated to enable notifications screen
https://github.com/user-attachments/assets/7c2205fc-16dc-4073-939a-dceb4fc1d43e

#### Expected behavior
After generate keys app should navigate to enable notifications and not show profiles screen and the skeleton

#### Actual behavior
App shows profiles screen and soon after a skeleton screen after generate keys screen

### Reproduction

1. Recover an account using seed phrase
2. Navigate through onboarding to generate Keys
3. You will notice that after generating keys, the app briefly navigates to profiles screen

### Additional Information

- Status version: nightly
- Operating System: iOS (simulator only)

**Comment by churik** [comment]
postponed due to limited capacity for 2.30

**Comment by flexsurfer** [comment]
unable to reproduce

**Comment by churik** [comment]
should be reopen if is reproducible
