### ISSUE TITLE
Discover Communities has no cards with an endless loading state

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20812]
# Bug Report

**Steps:**

1. Install app
2. Create a user
3. Tap on discover at Community screen

#### Actual behavior

<img width="275" alt="Screenshot 2024-07-18 at 15 13 37" src="https://github.com/user-attachments/assets/5f6a1329-8145-428d-accc-bdc8555fdb45">

#### Expected behavior
At least default card of Status Inu community should be visible
Nightly 👇
<img width="345" alt="Screenshot 2024-07-18 at 15 12 13" src="https://github.com/user-attachments/assets/5d922adf-4cee-4a8e-b0a9-cf5927233987">

### Additional Information

- Status version: nightly 18/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
issue is because of testnet, closing
