### ISSUE TITLE
Not all toasts are shown for Wallet Connect

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20828]
# Bug Report

## Problem 
[comment]: # (A problem description)
We're currently not showing all toasts based on the current [design](https://www.figma.com/design/HOJ4lV2ko3jzMjorsDzaoP/Wallet-%2F-dApp-notifications?node-id=0-1&t=LhhTwRIpZ9vjjb9w-0). Should include all the toasts/ephemeral from the "dApps interactions" category.

#### Expected behavior
All relevant toasts from the design are shown

#### Actual behavior
Most toasts from the design are not shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@clauxx I suppose it can be postponed for now, please move it back if you feel there is a capacity for it

**Comment by clauxx** [comment]
sounds good :+1:

**Comment by mohsen-ghafouri** [comment]
@clauxx can i work on this one? i saw you had a PR for it and it's closed

**Comment by clauxx** [comment]
@mohsen-ghafouri I made the PR before the first release, but it was de-prioritized and too many changes happened in the meantime, so it was closed. It's free to be taken, but maybe the old PR can still be useful.

**Comment by mohsen-ghafouri** [comment]
Great, I will reuse codes from that PR, thanks @clauxx
