### ISSUE TITLE
Discover pixel perfect: Hashtags

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2082]
### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: Hashtags

#### Expected behavior
![image](https://user-images.githubusercontent.com/1552237/31397013-25b436f0-ade5-11e7-8b9d-4cab86cd16c2.png)
![image](https://user-images.githubusercontent.com/1552237/31397021-2b327060-ade5-11e7-92a5-10371e1612a4.png)

#### Actual behavior

iOS only for now:
![image](https://user-images.githubusercontent.com/1552237/31397063-40b4369e-ade5-11e7-8419-b8e13f941a03.png)

## Nice have
- [ ] iOS toolbar title wrong
- [ ] Grey bg
- [ ] Icon name thing
- [ ] Chat button missing

**Comment by goranjovic** [comment]
![screenshot_2017-10-11-13-54-54](https://user-images.githubusercontent.com/711764/31439482-8d85d93a-ae8c-11e7-8272-e3a501e5bfcd.png)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
