### ISSUE TITLE
Enable wallet connect feature flag by default

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20835]
### User Story

As a user, I want to have a access to the wallet connect functionality, so that I can interact with dapps.

### Description

Should enable the wallet connect feature flag by default, so it's available to the users. 

> **Must be the last PR before the branch is cut.**

### Acceptance Criteria

* The users of the production build have access to wallet connect without toggling the feature flag

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by J-Son89** [comment]
@clauxx are you taking this issue?
