### ISSUE TITLE
Discover pixel perfect: DApps List

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2083]
### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: DApps List

#### Expected behavior
![image](https://user-images.githubusercontent.com/1552237/31397316-f8e33e7c-ade5-11e7-8680-286084813f6d.png)
![image](https://user-images.githubusercontent.com/1552237/31397320-fc75fe76-ade5-11e7-955e-5889237dad02.png)

#### Actual behavior

iOS only for now:

![image](https://user-images.githubusercontent.com/1552237/31397350-0bb5706a-ade6-11e7-956b-8a72fd9141c7.png)

## Nice have
- [ x] Icon size bigger
- [ ] Margin grey a tad too high
- [ ] Check small resolution (smallest iPhone) if rows should be two instead of three
- [ ] iphone 5s - to close to the edges (icons are too close) It should be 16 px between dapp icon and the edge of the screen, we could reduce distance between dapps on smaller screens 

Check Android too.

**Comment by goranjovic** [comment]
![screenshot_2017-10-11-13-55-54](https://user-images.githubusercontent.com/711764/31439500-a69a8164-ae8c-11e7-9dad-45ed0e3000da.png)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
