### ISSUE TITLE
Events stuck in waiting for approval on dApp's side after signing in Status app

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20840]
**Preconditions:** https://react-app.walletconnect.com/ dApp is used for testing

**Steps:** 

1. Connect to dApp (let's say using Mainnet (Ethereum + Optimism) see the video in Actual result below
2. Trigger `eth_signTypedData_v4` event on dApp's side using Optimism network
3. Sign event in Status app
4. See if event status is changed on dApp's side

**Actual result:** event is still waiting approval on dApp's side. Trying triggering another events does not result in appearing in Status app. Every time user re-logins Status modal with expired `eth_signTypedData_v4` is appearing

Some events are being signed successfully. Try triggering and signing different events while reproducing the bug.  

https://github.com/user-attachments/assets/71f6b2f9-efd1-4f51-8ed8-91c6602649a2

[Status-debug-logs - 2024-07-22T141412.110.zip](https://github.com/user-attachments/files/16332067/Status-debug-logs.-.2024-07-22T141412.110.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by qoqobolo** [comment]
Note: for me `eth_signTypedData_v4` worked on Mainnet Ethereum and didn't work on Testet on the https://react-app.walletconnect.com/ dApp

**Comment by pavloburykh** [comment]
> Note: for me `eth_signTypedData_v4` worked on Mainnet Ethereum and didn't work on Testet on the https://react-app.walletconnect.com/ dApp

thanks @qoqobolo. Please try signing `eth_signTypedData_v4` triggered on Mainnet Optimism as shown on the video and tell if you are reproducing the issue.

**Comment by qoqobolo** [comment]
> > Note: for me `eth_signTypedData_v4` worked on Mainnet Ethereum and didn't work on Testet on the https://react-app.walletconnect.com/ dApp
> 
> thanks @qoqobolo. Please try signing `eth_signTypedData_v4` triggered on Mainnet Optimism as shown on the video and tell if you are reproducing the issue.

Yep, the issue is reproducible for me on Optimism, even if I'm only connected to Optimism (i.e. it is not necessary to connect to Ethereum + Optimism).

1. Connect to dApp on Optimism Mainnet
2. Trigger the `eth_signTypedData_v4` event on dApp's side using Optimism
3. Sign event in the Status app


It looks like the signature only works for Ethereum Mainnet

**Comment by pavloburykh** [comment]
Thank you @qoqobolo @clauxx Closing the issue as it turned out to be a duplicate of https://github.com/status-im/status-mobile/issues/20757
