### ISSUE TITLE
Limit the asset selection for bridge for ETH and stablecoins

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20842]
**Description**
For the assets available for selection on Bridge modal, please limit the list to ETH, USDT, USDC and DAI

**Note:**
same as the issue on desktop:

https://github.com/status-im/status-desktop/issues/15703#issuecomment-2242893232

**Comment by churik** [comment]
just re-posting to avoid confusion https://github.com/status-im/status-desktop/issues/15697#issuecomment-2242585365
