### ISSUE TITLE
No result if user searches address by address with chains

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20841]
# Bug Report

**Steps:**

1. Login to app
2. Go to `Profile` -> `Wallet`-> `Saved addresses`
3. Save address (e.g. eth:arb1:oeth:0x37e34eecb98105c510c8ab6fcdfada8b66c5a83f) as `Test Address`
4. Enter `eth:arb1:oeth:0x37e34eecb98105c510c8ab6fcdfada8b66c5a83f` into search field

#### Expected behavior

Search result should show `Test Address`

#### Actual behavior

No search results 

https://github.com/user-attachments/assets/3d04787b-4b8a-4cc7-a773-24bb99f1f631

### Additional Information

- Status version: nightly 22/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by shivekkhurana** [comment]
@alwx Are you working on this ? Is the assignment still relevant ?

**Comment by churik** [comment]
I don't think it makes to work on this as we're removing prefixes

cc @shivekkhurana

**Comment by VolodLytvynenko** [comment]
this issue is redundant. We are not using prefixes anymore
