### ISSUE TITLE
Discover pixel perfect: DApps Profile / Details

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2084]
### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: DApps profile

#### Expected behavior
![image](https://user-images.githubusercontent.com/1552237/31397476-70bd428a-ade6-11e7-8625-dbb96d0d043c.png)
![image](https://user-images.githubusercontent.com/1552237/31397484-7396dd68-ade6-11e7-941a-0c77d4d5839b.png)

#### Actual behavior

iOS only for now:
![image](https://user-images.githubusercontent.com/1552237/31397597-b7bf6942-ade6-11e7-9524-b31fab8e6574.png)

## Must have
- [ ] open button - make it smaller — 64px for iOS, 72px for Android
- [ ] Description and URL - 16px between text and the bottom edge 
- [ ] add a title to the screen? like `DApp Profile`
## Nice have
- [ ] iOS toolbar title wrong
- [ ] Grey bg
- [ ] Wrong icon bg
- [ ] Description bg
- [ ] Open icon should also be tappable, not just text
- [ ] Dapp icon is now too small, should be 56
- [ ] Wrong font color in Open text on android

**Comment by goranjovic** [comment]
![screenshot_2017-10-11-13-56-17](https://user-images.githubusercontent.com/711764/31439518-b3993414-ae8c-11e7-814f-fd72ba556ec3.png)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
