### ISSUE TITLE
App crashes after attempt to send collectible

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20850]
### Steps:
1. Go to send a flow of any collectible
2. Confirm collectible sending

### Actual result:
App crashed after entering a password on the confirmation page of collectible sending

https://github.com/user-attachments/assets/4eb9c7c3-4d45-4ae1-bfe5-17341cbafb3f

### Expected result:
The collectible is sent (this flow works correctly on the desktop)

### Logs:
[mobile.txt](https://github.com/user-attachments/files/16338384/mobile.txt)

### ENV:
Nightly 22 Jul

**Comment by OmarBasem** [comment]
The error seems to be from status-go side. The error happens on opening an account after a collectible has been sent when calling method [`wallet_filterActivityAsync`](https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/common/activity_tab/events.cljs#L37) inside `wallet/fetch-activities-for-current-account`

**Comment by OmarBasem** [comment]
> The error seems to be from status-go side. The error happens on opening an account after a collectible has been sent when calling method [`wallet_filterActivityAsync`](https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/common/activity_tab/events.cljs#L37) inside `wallet/fetch-activities-for-current-account`

Hey @stefandunca, any idea why the above error is happening? It started happening recently. I see a recent [commit](https://github.com/status-im/status-go/commit/89f1feade0ea3ddd71185ca15b8b89e4e593d0ff) into status-go that modifies the method `wallet_filterActivityAsync`, are there any changes expected on the client-side when calling that method? (or maybe before sending a collectible?)

**Comment by stefandunca** [comment]
> Hey @stefandunca, any idea why the above error is happening?

No, please share more information, like the `geth.log` entries after you call the `filterActivityAsync` if the crash is in status-go.

> I see a recent [commit](https://github.com/status-im/status-go/commit/89f1feade0ea3ddd71185ca15b8b89e4e593d0ff) into status-go that modifies the method `wallet_filterActivityAsync` ... 

The changes look good there. How about bisecting and check the commits before to be sure which one is the culprit.

Maybe @Cuteivist can share if there were some other changes that I missed and you can check?

> are there any changes expected on the client-side when calling that method? (or maybe before sending a collectible?)

No, not really. The implementation will source the information from pending or transfers depending on the state it is in. Maybe @saledjenic can share if there are any recent changes on how do we handle the sending of collectibles that you should consider. However, nothing should excuse a crash.

**Comment by OmarBasem** [comment]
[Status-debug-logs (2).zip](https://github.com/user-attachments/files/16346230/Status-debug-logs.2.zip)

Here is the `geth.log` @stefandunca 

I see the following error at the timestamp I sent the collectible:

```
ERROR[07-23|08:53:33.687|github.com/status-im/status-go/protocol/common/message_sender.go:992]                                                     failed to handle an encrypted message    site=handleEncryptionLayer error="hash ratchet group id not found"
ERROR[07-23|08:53:33.688|github.com/status-im/status-go/protocol/common/message_sender.go:992]                                                     failed to handle an encrypted message   
```

> The changes look good there. How about bisecting and check the commits before to be sure which one is the culprit.

I will try debugging with an earlier commit from status-go and see if the error happens

**Comment by stefandunca** [comment]
> I see the following error at the timestamp I sent the collectible:

Those look like log entries from messenger on handling waku payloads unrelated to wallet.

> Here is the geth.log @stefandunca

I checked the provided logs and the call to `filterActivityAsync` doesn't appear in the logs, this entry more precisely https://github.com/status-im/status-go/blob/40c3b1df335ceac2cecec272d10bbbe4c66b4815/services/wallet/api.go#L717

It looks to me like the call for activity filtering is not done.

**Comment by OmarBasem** [comment]
@stefandunca found the commit that is causing the problem https://github.com/status-im/status-go/commit/094d26dc663500e0261049ccba6d90dd6d0c9abf

cc @Cuteivist

**Comment by Cuteivist** [comment]
@OmarBasem This commit consist of 2 changes that could affect mobile.
Activity changes would crash also on our side too.

Would it be possible that pending transaction could cause crash on mobile UI side?
Did you try doing normal Send tx with same changes?

**Comment by OmarBasem** [comment]
> This commit consist of 2 changes that could affect mobile.

@Cuteivist So are there changes required to the arguments on client side before sending a collectible?

> Did you try doing normal Send tx with same changes?

Yes normal send transaction works fine.

> Activity changes would crash also on our side too.

So currently sending a collectible on desktop causes a crash also?

cc @churik

**Comment by Cuteivist** [comment]
@OmarBasem There is no crash on our side. Sending works just fine.

Looking through the changes. The only option would be tx or any field being empty. Could you debug https://github.com/status-im/status-go/blob/develop/transactions/transactor.go#L185 this function for any possible nils ?

Second thing would be something incorrect in handling pending transaction for erc1155 or erc721 on your side.

**Comment by OmarBasem** [comment]
@Cuteivist The following is the arguments we give to `wallet_createMutliTransaction` when sending a collectible:

```

 [{:fromAddress 0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5, :toAddress 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be, :fromAsset 6862557749886761972171460736418269646159429268958860760319867204574481814272, :toAsset 6862557749886761972171460736418269646159429268958860760319867204574481814272, :fromAmount 0x0, :type 7} [{:BridgeName ERC1155Transfer, :ChainID 11155111, :ERC1155TransferTx {:ChainID 11155111, :MaxFeePerGas 0x106bde3cf4, :From 0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5, :MaxPriorityFeePerGas 0xa4c8846, :TxType 0x02, :Gas 0x9f75, :Input , :Data 0x, :Nonce nil, :TokenID 0xf2c11ee273d1a00000000000000000000000000000000000000000000000000, :Value nil, :Amount 0x1, :To 0x0635513f179d50a207757e05759cbd106d7dfce8, :Recipient 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be}, :CbridgeTx {:ChainID 11155111, :MaxFeePerGas 0x106bde3cf4, :From 0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5, :MaxPriorityFeePerGas 0xa4c8846, :TxType 0x02, :Gas 0x9f75, :Input , :Data 0x, :Nonce nil, :Value nil, :Amount 0x1, :To 0x0635513f179d50a207757e05759cbd106d7dfce8, :Recipient 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be, :Symbol 0xf2c11ee273d1a00000000000000000000000000000000000000000000000000}}] 0xd2ba8e95bcd1bc4c11534462b758f835aa482cda4194858fdbe89297e8ef8582]

```

I see that `MultiTransactionID` and `Symbol` are not present under `ERC1155TransferTx`, but are being read from the function `StoreAndTrackPendingTx` on status-go. Are these 2 arguments required for all erc1155 transfers?

**Comment by Cuteivist** [comment]
@OmarBasem Those looks correct. Multi tx is created in `CreateMultiTransaction` on status-go side. Even missing symbol shouldn't affect it as it is simply string.

Did you check database whether pending transaction is added ? It's guess game whether crash is on tx activity side or signing tx side.

**Comment by OmarBasem** [comment]
> @OmarBasem Those looks correct. Multi tx is created in `CreateMultiTransaction` on status-go side. Even missing symbol shouldn't affect it as it is simply string.
> 
> Did you check database whether pending transaction is added ? It's guess game whether crash is on tx activity side or signing tx side.

@Cuteivist I found the exact line causing the crash. That [line](https://github.com/status-im/status-go/blob/develop/services/wallet/activity/activity.go#L266) inside `multiTransactionTypeToActivityType` function. I think the type should be `transfer.MultiTransactionSend` of value `0` but for some reason the type is of value `7`, therefore it reaches the `panic` line.

I tried to debug the issue further, when I removed the function [StoreAndTrackPendingTx](https://github.com/status-im/status-go/blob/develop/services/wallet/router/pathprocessor/processor_erc1155.go#L168) inside `sendOrBuild` the crash did not happen. Below are the values of the arguments given to the function StoreAndTrackPendingTx:

- `from`: `0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5`
- `sendArgs.ERC1155TransferTx.Symbol`: `1`
- `sendArgs.ChainID`: `11155111`
- `sendArgs.ERC1155TransferTx.MultiTransactionID`: `1722234631124`
- `tx`: `&{0x40047cae80 {13952692201109512282 325255156439 0x7d75e51e80} 0 {<nil>} {<nil>} {<nil>} {<nil>}}`

I see some `nil` values inside `tx`, which could be the issue causing an incorrect type (?)

Regarding `multiTransactionTypeToActivityType` maybe we can return a default `unknownType` instead of raising an error to crash the app?

cc @stefandunca

**Comment by Cuteivist** [comment]
Thank you @OmarBasem for great analysis. I will jump to it today and see what I can do.

**Comment by OmarBasem** [comment]
@briansztamfater I think this issue is relevant to your [PR](https://github.com/status-im/status-mobile/pull/20902)? Is sending collectibles working there?

**Comment by Cuteivist** [comment]
> @Cuteivist The following is the arguments we give to `wallet_createMutliTransaction` when sending a collectible:
> 
> ```
> 
>  [{:fromAddress 0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5, :toAddress 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be, :fromAsset 6862557749886761972171460736418269646159429268958860760319867204574481814272, :toAsset 6862557749886761972171460736418269646159429268958860760319867204574481814272, :fromAmount 0x0, :type 7} [{:BridgeName ERC1155Transfer, :ChainID 11155111, :ERC1155TransferTx {:ChainID 11155111, :MaxFeePerGas 0x106bde3cf4, :From 0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5, :MaxPriorityFeePerGas 0xa4c8846, :TxType 0x02, :Gas 0x9f75, :Input , :Data 0x, :Nonce nil, :TokenID 0xf2c11ee273d1a00000000000000000000000000000000000000000000000000, :Value nil, :Amount 0x1, :To 0x0635513f179d50a207757e05759cbd106d7dfce8, :Recipient 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be}, :CbridgeTx {:ChainID 11155111, :MaxFeePerGas 0x106bde3cf4, :From 0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5, :MaxPriorityFeePerGas 0xa4c8846, :TxType 0x02, :Gas 0x9f75, :Input , :Data 0x, :Nonce nil, :Value nil, :Amount 0x1, :To 0x0635513f179d50a207757e05759cbd106d7dfce8, :Recipient 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be, :Symbol 0xf2c11ee273d1a00000000000000000000000000000000000000000000000000}}] 0xd2ba8e95bcd1bc4c11534462b758f835aa482cda4194858fdbe89297e8ef8582]
> ```
> 
> I see that `MultiTransactionID` and `Symbol` are not present under `ERC1155TransferTx`, but are being read from the function `StoreAndTrackPendingTx` on status-go. Are these 2 arguments required for all erc1155 transfers?

@OmarBasem Please look at at the payload mobile is sending. It is passing: `:type 7`
Only possible types are: 
```
  MultiTransactionType* = enum
    MultiTransactionSend = 0,
    MultiTransactionSwap = 1,
    MultiTransactionBridge = 2,
    MultiTransactionApprove = 3
```

I will create change to status-go that validates the MultiTxType before doing anything, but there is clear bug on mobile side.

**Comment by Cuteivist** [comment]
status-go validation: https://github.com/status-im/status-go/pull/5619

With this change it should clearly fail the send.

**Comment by briansztamfater** [comment]
> @briansztamfater I think this issue is relevant to your [PR](https://github.com/status-im/status-mobile/pull/20902)? Is sending collectibles working there?

I tested with some collectibles and it worked on my branch!

**Comment by OmarBasem** [comment]
> > @briansztamfater I think this issue is relevant to your [PR](https://github.com/status-im/status-mobile/pull/20902)? Is sending collectibles working there?
> 
> I tested with some collectibles and it worked on my branch!

Okay great!

**Comment by OmarBasem** [comment]
> Please look at at the payload mobile is sending. It is passing: :type 7

@Cuteivist So the problem should be fixed in that [PR](https://github.com/status-im/status-mobile/pull/20902)

> status-go validation: [status-im/status-go#5619](https://github.com/status-im/status-go/pull/5619)
> 
> With this change it should clearly fail the send.

Thank you for looking into this.
