### ISSUE TITLE
The max value is not updated when network is disabled on the bridging page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20851]
Follow up for https://github.com/status-im/status-mobile/pull/20604

### Steps:
1. Go to the routes generation page of the bridge page.
2. Disable a network in the "FROM" section.

### Actual result:
The max value is not updated when a network is disabled.

https://github.com/user-attachments/assets/558909d2-5aaa-46db-a10e-f18688f27905

### Expected result:
The max value should be updated to reflect the available networks after a network is disabled.

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

**Comment by J-Son89** [comment]
@VolodLytvynenko - I think we should just skip this issue altogether, after 2.30 is out this will not be an issue as we will move to single chain sending. I think we should close it 👍

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - I think we should just skip this issue altogether, after 2.30 is out this will not be an issue as we will move to single chain sending. I think we should close it 👍

@J-Son89 Yes. Agree
