### ISSUE TITLE
Wallet: Disable complex routing

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20869]
Currently the app does not have the infrastructure to handle complex routing, it brings in many secondary issues and is outright complex to a user.
Since we will be moving away from this by 2.31 it makes sense to block it for the 2.30 release as it is a simple fix to do and will reduce some user confusion if they end up making a multichain transaction.

It can be blocked in 
src/status_im/contexts/wallet/send/events.cljs
<img width="274" alt="Screenshot 2024-07-24 at 12 37 23" src="https://github.com/user-attachments/assets/b3aec187-bb72-4f6a-86d6-24e5f22073f7">
by updating the `best` route to be `nil` if it is a multichain route.

**Comment by churik** [comment]
follow up on https://github.com/status-im/status-mobile/pull/20631
