### ISSUE TITLE
From is shown when user goes to sending flow via bridge

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20877]
Follow up for https://github.com/status-im/status-mobile/pull/20773

### Preconditions:
User has only one "Account 1" account on the wallet page with available asset 

### Steps:
1. Long tap the asset with the available amount
3. Tap "bridge"

### Actual result:
The user sees the FROM page

https://github.com/user-attachments/assets/0b130e15-3e7d-4c5c-8368-c5095ad00170

### Expected result:
- If the user has Account 1 (with 1 DAI) and Account 2 (with 0 DAI), the FROM page should be skipped.
- If the user has Account 1 (with 1 DAI), Account 2 (with 1 DAI), and Account 3 (with 0 DAI), the FROM page should display only Account 1 and Account 2. Account 3 should be hidden.

### ENV:
Nightly 25 Jul 2024

**Comment by shivekkhurana** [comment]
Is this still relevant ?

**Comment by VolodLytvynenko** [comment]
> Is this still relevant ?

hi @shivekkhurana still relevant. But priority is very low.  WDYT to include it to 2.32 or higher?

**Comment by ulisesmac** [comment]
@VolodLytvynenko The bridge option is not shown on the wallet home screen, even if the flag `FLAG_BRIDGE_TOKEN_ENABLED` is enabled. So it's no longer reproducible/relevant.
