### ISSUE TITLE
Mobile app crashes consistently after about 60s after opening.

### ISSUE THREAD

**Issue by chair28980** [status-im/status-react#20872]
# Bug Report

## Problem 
Mobile app crashes consistently after about 60s after opening.

### Reproduction

1. Open Status mobile app
2. Navigate around, or keep it open to any page
3. App crashes and iPhone crash report screen appears.

### Additional Information

- Status version: nightly 
- Operating System: iOS

**Comment by siddarthkay** [comment]
Logs by shaking device : [logs (18).zip](https://github.com/user-attachments/files/16370126/logs.18.zip)
Crash Logs via Testflight : [testflight_feedback (2).zip](https://github.com/user-attachments/files/16363778/testflight_feedback.2.zip)

**Comment by churik** [comment]
not reproducible anymore on nightly
