### ISSUE TITLE
FDroid build failing due to react-native-camera-kit dependencies

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#20876]
The FDroid build is [currently failing](https://gitlab.com/cammellos/fdroiddata/-/jobs/7418712679) because of dependencies in the `react-native-camera-kit` package, which relies on Google ML Kit for QR scanning. This issue needs to be addressed to ensure our app is compliant with FDroid guidelines.

**Steps to Reproduce:**
1. Attempt to submit PR on FDroid repository and let job build the app for FDroid.
2. Notice the build failure due to Google dependencies.

**Proposed Solutions:**
1. Fork the `react-native-camera-kit` library and remove the Google ML Kit dependencies.
2. Submit a PR to the original library to remove these dependencies.
3. As a last resort, remove the `react-native-camera-kit` library only for FDroid builds, though this is not preferable since QR scanning is a crucial feature of our app.

**Action Items:**
1. Investigate the feasibility of forking `react-native-camera-kit` and removing the Google ML Kit dependencies.
2. Track and prioritize the work needed for this change.

**Additional Context:**
QR scanning is an essential feature of our app, and we need a solution that maintains this functionality while being compliant with FDroid requirements.

**Comment by briansztamfater** [comment]
Some findings:
- On Status v1, our scanning library used ZXing as a dependency
https://github.com/status-im/status-mobile/blob/3f02500797eeffd995089fdf08f54ec8fa3e5566/nix/deps/gradle/deps.list#L383
- After upgrading `react-native-camera-kit` here https://github.com/status-im/status-mobile/pull/16248 we introduced Google dependencies, mostly MLKit related.
https://github.com/status-im/status-mobile/blob/672358fbceed261a768f3beb0db94594eb5f823c/nix/deps/gradle/deps.list#L576

IMO we have two options:
a) Downgrade the library back to a version where it uses ZXing. The risks are reintroducing old bugs already fixed by upgrading the lib. Maybe @smohamedjavid you remember which were the bugs that were solved on the upgrade PR?
b) Fork the library to remove MLKit dependencies and use ZXing instead, which should not be too complicated as using MLKit only for QR Scanning is a bit too much. The risks are introducing bugs to the library.

A third option would be to downgrade the package for FDroid builds.

**Comment by smohamedjavid** [comment]
@briansztamfater - It was upgraded mainly due to this issue: https://github.com/status-im/status-mobile/issues/16226 where the camera dimensions don't cover the whole screen in Android. So, we upgraded from `v8.0.4` to `v13.0.0`. We can downgrade to `v10.0.0` (the last version to use `ZXing`) and check.

IMO, if the package/QR scanning feature is removed, it would be the worst UX as the user will be forced to enter the address.
