### ISSUE TITLE
Broken screen when syncing fails

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#20885]
# Bug Report

## Problem 

Upon failure in the syncing process, we present a broken screen to the user both in the onboarding and from the settings screen. The second problem is that the `Try again` button doesn't work **when the user is syncing from within the settings**.

#### Expected behavior

It should look as in Figma https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675-179635&t=btGB9vN5GCYgNE5i-0 as this should be a straightforward implementation.

Additionally, the user should be able to retry the syncing process, as if they started from scratch. After pressing `Try again`, we should bring the user back to the `Scan Sync Code screen`, so that they can decide if they want to use the sync code or scan a QR code.

https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675-179635&t=btGB9vN5GCYgNE5i-0

<img src="https://github.com/user-attachments/assets/1c3b8352-2bb8-49ad-8dd6-1652d6558716" width="300" />

#### Actual behavior

1. The screen looks broken.
2. While syncing from within the settings (thus logged in), the user presses on `Try again`, the modal just closes and no action is taken.

<img src="https://github.com/user-attachments/assets/0b85785f-b1ce-4b9a-99bb-9e25b85d0452" width="300" />

Note: the PR from https://github.com/status-im/status-mobile/pull/20883 @Parveshdhull already fixed the screen not expanding correctly.

### Reproduction

1. Open the desktop app and copy the sync code. The desktop version doesn't matter.
2. Close the desktop app.
3. Open the mobile app and paste the sync code in `Settings > Syncing > Add > Scan or enter sync code`
4. Optionally, press on the `Try again` button to see it just closes the modal.

Any failure on the sync process will cause the error screen to be displayed, but the above steps are a sure way to reproduce.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Thank you @ilmotta for creating the issue. I am assigning myself, as I have context and probably already done related work in https://github.com/status-im/status-mobile/pull/20766. (So basically some cherry-picking should fix the issue)

**Comment by ilmotta** [comment]
> Thank you @ilmotta for creating the issue. I am assigning myself, as I have context and probably already done related work in #20766. (So basically some cherry-picking should fix the issue)

Very much appreciated @Parveshdhull, thank you!
