### ISSUE TITLE
Transactions History is empty for the account that has history of transactions [feature/upgrade-status-go-geth17]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2089]
### Description

*Type*: Bug

*Summary*: For both accounts no History of transactions is shown. Accounts:
1. recovered account with more than 700 transactions in history
2. new account with some incoming transaction (can see it on etherscan)

Opened new Wallet -> Transactions and there is empty list on History tab that is wrong. Expected to see list of transactions in the History. 

### Reproduction
https://app.testfairy.com/projects/4803590-status/builds/6796434/sessions/10/?accessToken=s1xuQ7XiDoF4ZiOcazddX5vRulw
- Open Status
- Recover account that has some transactions done in the past
- open new Wallet
- tap on right top icon to open Transactions
- on tab History check the list 

### Additional Information
* Status version:  feature/upgrade-status-go-geth17 0.9.11d186 
* Operating System: 
Real device iPhone 6s, iOs 10.3.1

**Comment by jeluard** [comment]
@annadanchenko Could you share the eth `address` ? Also could you confirm this is on ropsten?

**Comment by annadanchenko** [comment]
https://ropsten.etherscan.io/address/0x234b4d00832c5589bd7859bcbf4218e975b3df52
it's on default network "Ropsten with upstream RPC"

Also note that issue happens with any account that has history of transactions not just with this only one.

**Comment by rasom** [comment]
ok, so i found that we are requesting eth with such call now `http://46.101.129.137:3001/donate/0x0x1975660C234848F9235BFB9f1429E0efdB3a9BF6`, which means that we are adding extra `0x` and that's why transactions history can't be fetched

**Comment by annadanchenko** [comment]
verified ok on new build for `feature/upgrade-status-go-geth17` 0.9.11d189
