### ISSUE TITLE
Token value is sent with 0 in multi-routing transaction confirmation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20895]
### Steps to Reproduce:
1. Restore a user with available assets on at least 3 networks.
2. Build the multi-route.
3. Confirm the transaction.

### Actual Result:
Only one transaction is sent with the correct value, visible in etherscan.
Other networks send transactions with 0 value, leading to users paying fees for empty transactions.

https://github.com/user-attachments/assets/9009e766-3ea5-496c-a522-8cfaba7b29d3

Example: After confirming a multi-route transaction:
- L1 1.9 USDC ->  is sent successfully. [etherscan](https://etherscan.io/tx/0xf6fb9c7b0c4de613b4b5dc8e4c0a6e55aff413fc3ea9d760f57e39ea134a1392)
- L2 ARB 2.2 USDC ->  is sent with 0 value. [etherscan](https://arbiscan.io/tx/0x0da402b6b6fd5eceea5f90a07ce7c8207e4ee782ae955677a2a99568f175add8)
- L2 OPT 1.2 USDC -> is sent with 0 value. [etherscan](https://optimistic.etherscan.io/tx/0x528088cc08dc36909405130914b34bfb068f9c3f870261d682f0e7fef58c702d)

### Expected Result:
All transactions should be sent with the correct value across all networks involved in the multi-route. OR we should disable multi routing transactions

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/16393161/Status-debug-logs.zip)

### ENV:
Nightly 27 Jul

**Comment by churik** [comment]
follow-up on https://github.com/status-im/status-mobile/pull/20631
