### ISSUE TITLE
#react-native-platform macOS/Linux/Windows

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#209]
Port Status to Desktop

**Comment by adrian-tiberius** [comment]
maybe we can use something like https://github.com/necolas/react-native-web .

**Comment by jarradh** [comment]
not a bad idea, lets keep it in our back pocket, i'm worried about web performance native extensions

There are ports for each;
https://github.com/ptmt/react-native-macos
https://github.com/ReactWindows/react-native-windows
https://github.com/CanonicalLtd/react-native < Ubuntu

**Comment by flexsurfer** [comment]
https://github.com/status-im/react-native-desktop

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-desktop">status-im/react-native-desktop</a></strong></div><div>react-native-desktop - A Desktop port of React Native, driven by Qt, forked from Canonical</div></blockquote>
