### ISSUE TITLE
👨‍💻 Correct dapps (for the corresponding network) only appear on the list after relogin

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#20908]
It's related to https://github.com/status-im/status-mobile/issues/20794

**Steps:**
1. Connect to a mainnet app (Uniswap)
2. Put the app in Testnet mode
3. Check the connected dapps
**Expected result:** no Uniswap in the list
**Actual result:** Uniswap is still visible
4. Re-open the app/relogin
**Actual result:** the list is empty (as expected)

It works the same way for both the dapps connected on testnet and mainnet

https://github.com/user-attachments/assets/87b9a77c-36fd-48f9-a51c-7b769fcaebde

_Originally posted by @qoqobolo in https://github.com/status-im/status-mobile/issues/20799#issuecomment-2250189049_

**Comment by mohsen-ghafouri** [comment]
Hey @qoqobolo, sorry i couldn't reproduce this issue, could you please confirm if it still reproducible with latest develop changes or not, if so does it happen 100% time or randomly?

**Comment by qoqobolo** [comment]
Hey @mohsen-ghafouri, the issue is indeed no longer reproducible.
Thanks for checking!
