### ISSUE TITLE
Buy through Mercuryo doesn't work

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#20927]
### Description

Attempting to purchase crypto using the mercuryo link we have in the Buy section results in a`Signature is invalid.` error after entering payment details.

The link needs to include a signature based on a secret key and the destination address, which needs to be predetermined when creating the URL parameters.

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=16428-59853&t=xZ3A8FbB2tBBj86G-0

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=16428-62308&t=MQSMXdWbuVicDLvV-1

**Comment by churik** [comment]
Thank you @briansztamfater !

We didn't check it yet

**Comment by dlipicar** [comment]
@churik @shivekkhurana 
We probably want to split this into 2 issues for mobile
- One with milestone 2.30, to ensure the status-go changes don't break compatibility with mobile and the user can perform purchases with Mercuryo (we won't be getting fees for those)
- One with milestone 2.31, to make use of the new API and get the proper Mercuryo URL that gives us partner fees.

@churik will ping you before merging the status-go PR to validate the first point (https://github.com/status-im/status-go/pull/5656)

**Comment by shivekkhurana** [comment]
I will also reccomend the 2 issues idea. 

It's okay to lose some fee on mobile in 2.30, given the release priority.

**Comment by dlipicar** [comment]
@briansztamfater @shivekkhurana  I'd say the PR (https://github.com/status-im/status-go/pull/5656) is ready for testing, could you raise a status-mobile PR pointing to that branch to trigger a build?
I did some validation on desktop with no client-side changes (so basically, the scenario we expect mobile to have for 2.30) and it worked fine.

We should have:
- Working purchases on Ramp, with Partner Fees
- Working purchases on Moonpay, with Partner Fees
- Working purchases on Mercuryo, without Partner Fees

**Comment by churik** [comment]
@briansztamfater 

If you can elaborate on where we should check Partner fees and the result that all the params, mentioned in the description, are set correctly, we can take this to test ASAP.

If there is no such option - please, make sure that it is working (because we have 0 requirements for this feature) and I believe we should cherry-pick it to 2.30.

Thank you!

**Comment by briansztamfater** [comment]
@dlipicar I'll create a new PR pointing to that status-go PR for 2.30. Things should work as they are currently working as far as I understand.

@churik Not sure how to check partner fees, probably @dlipicar can provide more context on this, but for 2.30 we decided to not collect fees for Mercuryo on mobile because implementing will take more time #20962 (new designs, new logic, new flow, etc) and also has a dependency on #20380 for showing the asset selector.

**Comment by dlipicar** [comment]
@churik expectations:
- Ramp, Moonpay and Mercuryo are listed in the Buy/Single section
- Mercuryo is listed in the Buy/Recurrent section
- All links let you successfully perform a crypto purchase
- (Only Ramp and Moonpay) Ping me the receipts of the transactions done and I'll check fees are collected in each provider's dashboard.

**Comment by briansztamfater** [comment]
Thanks for the clarifications @dlipicar!

@churik Created PR to point to status-go PR branch: https://github.com/status-im/status-mobile/pull/20993
I tested it locally and worked fine, but let's confirm it through QA.

**Comment by churik** [comment]
I guess the intention is to get it to 2.30?

**Comment by dlipicar** [comment]
@churik yeap, this is something we want in 2.30

Additional validation details added here: https://www.notion.so/Status-Wallet-Partner-Fees-8437e198a5804f79ab70472469c25b78?pvs=4#206b187d3ccc4b9db3ca255b5860dad5

**Comment by briansztamfater** [comment]
To clarify, for mobile we won't fix Mercuryo partner fees in 2.30, this will be implemented for 2.31 (linked PR).

**Comment by dlipicar** [comment]
Yeap yeap, but still, my PR introduces fixes for Ramp and Merucuryo that mobile wants in 2.30 :D

**Comment by churik** [comment]
@briansztamfater I'm not sure whether we should test it now or later? and what exactly to test? I got confused.

**Comment by churik** [comment]
@briansztamfater what is the state of it?

**Comment by briansztamfater** [comment]
Needed to wait for #21139 and #21140 to be merged. Now that both PRs were merged, I rebased and integrated them. All the logic is done and flow is implemented, I need to do a minor UI tweak to adapt the asset selector view to the designs and I'll send it to review today
