### ISSUE TITLE
"Usage data" bottom sheet reappears with wrong theme after reopening the app if you swipe it down on onboarding 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20932]
# Bug Report

## Problem 

https://github.com/user-attachments/assets/95dd8897-df04-4e2e-9c4e-b1b59c86bb59

<img width="478" alt="Screenshot 2024-07-31 at 12 47 00" src="https://github.com/user-attachments/assets/075a3381-1c94-4456-9173-e2816563f85f">

### Reproduction

1. Install Status
2. On onboarding: swipe the "Usage data" bottom sheet (don't press the buttons `Not now` or `Share usage data`)
3. Enable biometric ID
4. Finish onboarding
5. Close the app
6. Open the app
7. Log in with biometric ID

#### Expected behavior
- Theme is not broken
- Also not sure, at what point should we show this message if we swipe it down during onboarding?

#### Actual behavior

- The theme is broken
- The bottom sheet is shown both on the login screen and after login on the home screen

### Additional Information

- Status version: RC1 2.30 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
> Also not sure, at what point should we show this message if we swipe it down during onboarding?

From the implementation it seems if we swipe it down on the onboarding screen, it should be shown again on the profiles screen.
In the video, it looks like that is what happened, but as you have biometrics enabled, profiles screen got skipped quickly while the bottom sheet stayed there with that theme.

**Comment by Parveshdhull** [comment]
I think easiest solution will be to dismiss bottom sheet while navigating to home screen or disable "automatic" bio-metric auth at app start, until bottom sheet have any feedback. (User can always use bio-auth again, by manually pressing auth icon)

If we want to fix the theme, We can dismiss bottom sheet while navigating to home screen and reopen again. Which option you prefer @qoqobolo @ilmotta

**Comment by Parveshdhull** [comment]
> disable "automatic" bio-metric auth until bottom sheet have any feedback

This looks somewhat better to me, as user will kind of forced to make a choice and in next session automatic auth will be back

**Comment by qoqobolo** [comment]
> > disable "automatic" bio-metric auth until bottom sheet have any feedback
> 
> This looks somewhat better to me, as user will kind of forced to make a choice and in next session automatic auth will be back

Maybe there is a way to show it on top of the biometrics pop-up? So that the user is forced to first perform an action on the bottom sheet and only then log in using biometric auth?

For me any simpler solution is fine. But I think we should wait for @ilmotta  or maybe ask @xAlisher  for advice

**Comment by Parveshdhull** [comment]
> Maybe there is a way to show it on top of the biometrics pop-up?

I think we probably can't show our sheet on top of the native biometric pop-up, but I think we can delay this automatic auth and do it after bottom sheet is dismissed.

**Comment by ilmotta** [comment]
I don't have any strong opinion @Parveshdhull @qoqobolo. On apps I use, the biometrics auth pop-up always appears first. From this perspective, the bottom sheet would always appear behind the bio auth pop-up. The user would first do the auth interaction and then be able to interact/dismiss the bottom sheet, but not the other way around.

> The bottom sheet is shown both on the login screen and after login on the home screen

If I understood the bug correctly, the problem is more that the UI looks completely broken after authentication, not so much that it appears on login and home screen. If after login the bottom sheet looks as it should, I would imagine the user would not see any problem that it also appeared behind the auth pop-pop for a few seconds.
