### ISSUE TITLE
[Android] Failed to update release v1 with v2

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20934]
# Bug Report

### Reproduction

1. Install v1 app from PlayMarket
2. Update v1 with release build from [here](https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F2.30.x/).
*tried all types of build architecture:
<img width="481" alt="Screenshot 2024-07-31 at 15 21 24" src="https://github.com/user-attachments/assets/e766161f-298e-4d8d-b763-874bc7e1a3eb">

#### Actual behavior

https://github.com/user-attachments/assets/4f44eee0-3d8e-4af7-93bb-73877d5823e9

[intall.log](https://github.com/user-attachments/files/16440437/intall.log)

#### Expected behavior

App is updated

### Additional Information

- Status version: release 2.30
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by mariia-skrypnyk** [comment]
I had a successful update from v1 to v2 when I did it from Google files.
But such warning appeared:

<img width="230" alt="Screenshot 2024-08-02 at 09 06 58" src="https://github.com/user-attachments/assets/b919e3c4-2274-46f1-9127-ac2ec3a8b2b4">

*sorry for such picture quality, it was made like this because of blocked ability of screenshots

Here are my device extra info:

![photo_2024-08-01_12-36-59](https://github.com/user-attachments/assets/f115a18c-2d42-4087-9d4e-ba071caee854)
![photo_2024-08-01_12-37-02](https://github.com/user-attachments/assets/2189b0d3-f47e-451e-aad8-96ca0b430025)

**Comment by J-Son89** [comment]
@ilmotta, @cammellos wdyt?

**Comment by cammellos** [comment]
It'd be good to know android version, also, what we can do, is setup closed testing with 1.20.6, and try to upgrade to 2.30 through it, that's a better test than upgrading from apks

**Comment by ilmotta** [comment]
@mariia-skrypnyk I successfully upgraded from v1 in Play Store using the APK [StatusIm-Mobile-v2.30.0-45cf31-arm64-v8a.apk](https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F2.30.x/lastSuccessfulBuild/artifact/StatusIm-Mobile-v2.30.0-45cf31-arm64-v8a.apk). I installed the v2 APK directly from the device (thus not via `adb` to be more realistic). Android 13, Galaxy A71.

Do you know if this problem appears in other devices?

> It'd be good to know android version, also, what we can do, is setup closed testing with 1.20.6, and try to upgrade to 2.30 through it, that's a better test than upgrading from apks

Good idea about using closed testing 👍🏼 Curious @cammellos, have you seen problems like this before in the old releases and did you guys use closed testing before?

**Comment by mariia-skrypnyk** [comment]
Hi @ilmotta !

Only I faced this issue during release testing.
I have Samsung A34 (Android 14.0, One UI version 6.1) 

The only success way to install update was to do it using Google Files app as @smohamedjavid advices.
Let me know if you need smth extra.

**Comment by churik** [comment]
@ilmotta we used beta testing ages ago;
I don't think we had issues like this before, but it might be because it was Android 11 :) 

A lot of security updates and general upgrades have arrived since then;

afaik @mariia-skrypnyk you were able to install it in the end, right?

It of course might affect the first impression of the app, but given the hard deadline and uncertainty on how to deal with this issue and the fact that on Google Pixel 7a (Android 14 as well) it is installed without issues, I suggest to defer this one to 2.31

@ilmotta feel free to move it if you think differently

**Comment by mariia-skrypnyk** [comment]
> afaik @mariia-skrypnyk you were able to install it in the end, right?

yes @churik

**Comment by ilmotta** [comment]
> > afaik @mariia-skrypnyk you were able to install it in the end, right?
> 
> yes @churik

Can the issue be closed @mariia-skrypnyk?

**Comment by churik** [comment]
Yes, as it is only one-time thing, I'm closing the issue
