### ISSUE TITLE
Admin cannot re-add users to the group chat after removing them using the "Manage members" option.

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#20959]
# Bug Report

### Reproduction Steps

1. Create a group chat with User1 and User2.
2. Open the context menu in the group chat.
3. Select the "Manage members" option.
4. Uncheck User1 and User2 in the list to remove them from the chat.
5. Click the "Save" button.
6. Reopen the context menu in the group chat.
7. Select the "Manage members" option again.
8. Check User1 and User2 in the list to add them back to the chat.
9. Click the "Save" button.

### Expected Behavior

1. User1 and User2 are successfully removed from the group chat.
2. The system displays correct and relevant messages in the chat history, indicating that User1 and User2 have been removed.
3. Admin is able to re-add User1 and User2, with correct messages reflecting their addition.

### Actual Behavior
The system displays the following incorrect/extra messages:

1. "Admin (user that created the chat) has added" (this message is unnecessary or misleading).
2. When an admin tries to add User1 and User2 back using the "Manage members" option, incorrect messages about previously removed users are duplicated
3. Additionally, after re-adding users, there is inconsistent information about the count of users in the chat. For example, the admin may see that users have not been added back to the group.

https://github.com/user-attachments/assets/7046c6e0-5bed-45d0-bf85-08d0abd4b8e8

### Additional Information

- Status version: release 
- Operating System: Android, iOS

**Comment by J-Son89** [comment]
this issue is just about the messaging or what is happening?

If it is just about messaging but the functionality is working then I think we should not handle this for 2.30.
