### ISSUE TITLE
Stickers sent from desktop are displayed as a blank message on mobile (Only on release Jenkins builds)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#20958]
# Bug Report

### Reproduction

1. Make mobile and desktop users mutual contacts
2. Desktop: send a sticker to the chat
3. Mobile: check the chat

#### Expected behavior
The sticker is visible

#### Actual behavior
The sticker is not visible

<img width="390" alt="Screenshot 2024-08-05 at 14 58 26" src="https://github.com/user-attachments/assets/468135c3-febb-4bbe-85f5-b9b8ffe3b0e4">

### Additional Information

- Status version: RC 2.30 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@ilmotta, @cammellos  wdyt? 
I personally would not worry about this for 2.30 👍

**Comment by Parveshdhull** [comment]
hi @qoqobolo, Thank you very much for reporting this issue.

I tried latest develop with [2.30.0-rc.5](https://github.com/status-im/status-desktop/releases/tag/2.30.0-rc.5), and stickers are working fine for me. Please can you check using this version.

![image](https://github.com/user-attachments/assets/8781d8d5-d642-4bcb-8fea-083ec93e4cb7)

**Comment by qoqobolo** [comment]
Hey @Parveshdhull, thanks for checking!

> I tried latest develop

This is the reason why it's not reproducible for you.
I'm using the **mobile release** version with 2.30.0-rc.5 desktop, and it's still there.

But on develop there is no issue indeed. 

---
Maybe it's a matter of build type settings, i.e. `release` vs `nightly/PR`. 
I'm not sure how stickers actually work in this context. Maybe @flexsurfer  can help us with that?

**Comment by Parveshdhull** [comment]
Thank you @qoqobolo for checking. I will try to reproduce the issue in release builds and see what might be causing the issue.

**Comment by Parveshdhull** [comment]
URL: https://Localhost:34577/ipfs?hash=e30101701220f4aab0a4ff5a5fb2c565ab114d76dd42693302999d6392b467d6753ea9b55c12

Error: error unknown image format

**Comment by Parveshdhull** [comment]
```
def ipfsGatewayUrl() {
  if (utils.isReleaseBuild() || utils.isNightlyBuild()) {
    return 'https://status-im.infura-ipfs.io/ipfs/'
  } else {
    return 'https://ipfs.status.im/'
  }
}
```
https://github.com/status-im/status-jenkins-lib/blob/267c022e3af4cde9d416ce49c7399ce89ee7157e/vars/creds.groovy#L38

**Comment by Parveshdhull** [comment]
https://status-im.infura-ipfs.io/ipfs/

> Dedicated Gateway Not Found

**Comment by Parveshdhull** [comment]
> https://status-im.infura-ipfs.io/ipfs/
> 
> > Dedicated Gateway Not Found

It seems like ipfs gateway we use for release/nightly builds is down. @jakubgs please can you take a look?

**Comment by jakubgs** [comment]
I have no idea who created that, we have no such thing configured in our Infura account.

**Comment by siddarthkay** [comment]
I see : 
- https://github.com/status-im/status-go/pull/2795 
- https://github.com/status-im/status-jenkins-lib/pull/44

and https://ipfs.status.im/ is accessible publicly whereas https://status-im.infura-ipfs.io/ipfs/ is not.
A simple solution would be to just use https://ipfs.status.im/ for all builds : PR, release and nightly.
I'll make the change in `status-jenkins-lib`

cc @jakubgs

**Comment by jakubgs** [comment]
The https://ipfs.status.im/  endpoint is deployed via this repo: https://github.com/status-im/infra-ipfs

That setup is probably running quite outdated IPFS software and doesn't really have much monitoring, so if we intend to use it more extensively it might make sense to improve that.

**Comment by jakubgs** [comment]
@siddarthkay opened an issue for alerting config for IPFS cluster:

- https://github.com/status-im/infra-ipfs/issues/21
