### ISSUE TITLE
(1) notification shown on 1:1 chat tab but no new messages in chats and private groups

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-react#20952]
# Problem

See picture. I can see a (1) on the chat tab but when I click on it, and even after keeping it open for a while, I still don't see which chat has a new message.

I did sync a new desktop as a first step. but don't see a new message on desktop either

![Screenshot_20240805-112305](https://github.com/user-attachments/assets/b9101419-5f16-4d9f-afe5-1d3e1a2f3efd)

# Version

2.29.0 (20240717215311)
Commit 97b19c544

**Comment by churik** [comment]
@fryorcraken 
Without logs it is impossible to debug this sort of issues.
Is it still the case or unread notification indicator got in sync after some time? 

Thanks!

**Comment by fryorcraken** [comment]
Hasn't happened for a while. I enabled debug logs. WIll reopen and attach logs if it happens again.
