### ISSUE TITLE
User is not redirected to external browser when trying to open invalid Status link (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20951]
Reproducing on Android only (Samsung Galaxy A52, Android 12). 

Example of invalid Status link https://status.app/u/0x04fbce10971e1cd7253b98c7b7e54de3729ca57ce41a2bfb0d1c4e0a26f72c4b6913c3487fa1b4bb86125770f1743fb4459da05c

**Steps:** 

1. Post given link 1-1 chat/group/comm channel
2. Tap on the link
3. Tap Open in Android
4. See if user is redirected to external browser

**Expected result:** user should be redirected to external browser

**Actual result:** user is not redirected to external browser. Browse pop up keeps re-opening.

https://github.com/user-attachments/assets/ffd4b343-0bb5-464f-8c41-f652c49c57f0

### Additional Information

- Status version: release 2.30 
- Operating System: Android

**Comment by Parveshdhull** [comment]
hi @pavloburykh, Thank you very much for reporting this issue. I tried the above steps, but unfortunately, I cannot reproduce it.

1. Please can you confirm, that you have other browser applications on your device?
2. Other apps can launch the browser without any issue? For example link press in the notes app etc.
3. Is the cancel button working fine and able to break this loop?

**Comment by Parveshdhull** [comment]
Also just to be sure, please can you try removing and reinstalling the app. Maybe status is default browser etc. and launching itself on pressing "Open in Android"

**Comment by Parveshdhull** [comment]
hi @churik @qoqobolo, can you please check if you can reproduce this issue?

If it's device-specific and not easily reproducible, should we move this to the next milestone?

**Comment by pavloburykh** [comment]
> hi @pavloburykh, Thank you very much for reporting this issue. I tried the above steps, but unfortunately, I cannot reproduce it.

Hi @Parveshdhull! Thank you for looking at the issue. 

> 1. Please can you confirm, that you have other browser applications on your device?

yes
> 2. Other apps can launch the browser without any issue? For example link press in the notes app etc.

yes
> 3. Is the cancel button working fine and able to break this loop?

yes


@Parveshdhull just to make sure: which link are you trying to open? Current issue is about invalid Status links. Like the one I have left in the description https://status.app/u/0x04fbce10971e1cd7253b98c7b7e54de3729ca57ce41a2bfb0d1c4e0a26f72c4b6913c3487fa1b4bb86125770f1743fb4459da05c 

Other links work fine, user is successfully redirected to external browser.

**Comment by pavloburykh** [comment]
> hi @churik @qoqobolo, can you please check if you can reproduce this issue?
> 
> If it's device-specific and not easily reproducible, should we move this to the next milestone?

As far as I know @churik is reproducing this issue as well.

**Comment by Parveshdhull** [comment]
hi, @pavloburykh,

Thank you very much for confirming. Please can you try these steps and check if this fixes the issue.

https://github.com/user-attachments/assets/8fb7224a-79cf-44a7-bbcb-0dd358c2d965

**Comment by pavloburykh** [comment]
> hi, @pavloburykh,
> 
> Thank you very much for confirming. Please can you try these steps and check if this fixes the issue.

@Parveshdhull I am not sure how to reproduce your steps on physical device using release build. I do not have options to select where to open current link. Also, there is no option "Open in Status" which you have in Debug build. We have removed this option as we have hidden Status browser. 


https://github.com/user-attachments/assets/9f2975f5-56a3-4149-b911-e2831d4bc6da

**Comment by flexsurfer** [comment]
i'm wondering how this link is different from others that work, it is also a valid link because the page is opened, user id is invalid but it's only related to the status page, not browser

**Comment by flexsurfer** [comment]
so most likely there is a loop, statusapp->browser->universal link->status app, but why it works only for invalid id idk

**Comment by pavloburykh** [comment]
> i'm wondering how this link is different from others that work, it is also a valid link because the page is opened, user id is invalid but it's only related to the status page, not browser

BTW, we had a similar issue some time ago related to Status browser https://github.com/status-im/status-mobile/issues/17869 which was fixed by https://github.com/status-im/status-mobile/pull/18020

**Comment by Parveshdhull** [comment]
![image](https://github.com/user-attachments/assets/728fefba-030c-483a-8e73-4ef7ba862abc)

I think we are in the loop because of this setting. Our intent for using the system browser is working fine, it's just that due to this setting, that intent is relaunching the app.
(For testing purposes, please disable this and see if the browser opens fine. This way we will know at least our browser launch code is working)

**Comment by Parveshdhull** [comment]
> i'm wondering how this link is different from others that work, it is also a valid link because the page is opened, user id is invalid but it's only related to the status page, not browser

I think even if we try to open valid status link from this device from notes etc, it will always launch status not browser. @pavloburykh please can you confirm.

From notes app, simple link google etc, should launch browser but valid or not all status links should launch app.

**Comment by Parveshdhull** [comment]
> so most likely there is a loop, statusapp->browser->universal link->status app, but why it works only for invalid id idk

If we click valid link in status app(not other app like notes), then we use app navigation and go to that screen.
In case of invalid we launch browser.

**Comment by pavloburykh** [comment]
> (For testing purposes, please disable this and see if the browser opens fine. This way we will know at least our browser launch code is working)

Confirming that browser opens fine when "Open supported links" option is disabled. 

> I think even if we try to open valid status link from this device from notes etc, it will always launch status not browser. @pavloburykh please can you confirm.

Confirming. This is expected behaviour.

**Comment by Parveshdhull** [comment]
https://www.reddit.com/r/Android/comments/qrxsh7/guide_how_to_fix_horrible_handling_of_links_on/?rdt=58840

> 3. You can't allow multiple apps to handle the same link (if it was approved manually by you, at least), which means that you can't choose from a list of supported apps when you open a link.

**Comment by Parveshdhull** [comment]
Removing my assignment, as this doesn't seem like a fixable bug and seems drawback of Android 12 itself. (Either we allow all status links to be processed by the app or none)

**Comment by pavloburykh** [comment]
> Removing my assignment, as this doesn't seem like a fixable bug and seems drawback of Android 12 itself. (Either we allow all status links to be processed by the app or none)

thank you for your investigation @Parveshdhull

**Comment by churik** [comment]
Thank you, REmoved it from milestone
