### ISSUE TITLE
Token-gated permissions are not displayed on community's homepage

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20965]
Example of token gated community: https://status.app/c/ixSACigKD0NvbW0gVEcgbWFpbm5ldBIKZmRzZmRzZmRzZhgBIgcjNDM2MERGAw==#zQ3sho5t6z3H7JxpoTDGfoDky4yQuQ79SAeVTKLagYYX6Y2st

The above community has set permission of 1 ETH to become a member. NOTE: this permission is set on Mainnet, so ensure testnet is disabled in your account. 

**Steps:** 

1. Open token gated community
2. See if community permissions block is displayed on home page

**Actual result:** community permissions block is not displayed. 

[Status-debug-logs - 2024-08-06T175233.672.zip](https://github.com/user-attachments/files/16512003/Status-debug-logs.-.2024-08-06T175233.672.zip)

https://github.com/user-attachments/assets/1c6c7634-f7a6-44c7-af49-03abe95acb55

**Expected result:** community permissions are displayed. If user is not eligible to join - Request to join button should be disabled. 

https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=15331-284865&t=WYF9G3aEs6TICJhk-0

<img width="245" alt="Communities for Mobile – Figma 2024-08-06 17-51-00" src="https://github.com/user-attachments/assets/296251c7-62fb-49cc-9131-8105e73d7314">

### Additional Information

- Status version: nightly, release 2.30
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
most likely this is the reason https://github.com/status-im/status-mobile/commit/c1d2d44da4704679085b2e2c8f1019f19a37347b#diff-885467636bce29c58c7696c154939470533bafcbe4927ffd0e99deeafa55a41aR83
