### ISSUE TITLE
User redirected to confirmation page instead of 'Send to' page during collectible sending

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20972]
### Steps:
1. Scan wallet QR using universal scanner
2. Go to a transaction confirmation page
3. Go back to wallet main page
4. Open collectible -> tap 'send' button

### Actual result:
The user is redirected to the confirmation page, skipping the 'send to' page.

https://github.com/user-attachments/assets/fadd5a4e-787c-4edb-af11-ffbc13b348b3

### Expected result:

The user should be redirected to the 'send to' page.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
- 
### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16521185/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
any idea if this is related to wizard type navigation needing to be adjusted @ulisesmac ?

we could just disable this path to sending for 2.30?

**Comment by ulisesmac** [comment]
> any idea if this is related to wizard type navigation needing to be adjusted @ulisesmac ?
> 
> we could just disable this path to sending for 2.30?

Hey @J-Son89 

This is another issue related to the wizard and complex navigation. I guess this is bug happens because we don't clean some re-frame value, and we can't easily clean it because there are multiple flows/entry-points being affected.

> we could just disable this path to sending for 2.30?

I think we can do any: fix it or remove it

**Comment by J-Son89** [comment]
For sure, it's just the at removing is a safer bet as it doesn't introduce new bugs then. Time is tight at this point
