### ISSUE TITLE
After "daily request count exceeded, request rate limited" balance shows as 0, constant "provider is down" error, routes are hard to get

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20975]
# Bug Report

## Problem 

Balance randomly shows as 0, "Provider is down" toasts, routes are not possible to found after several hours of wallet usage (made a couple of transactions, did pull to refresh several times)

#### Expected behavior
error is properly handled or it shouldn't appear

#### Actual behavior
https://github.com/user-attachments/assets/07d21147-cff3-4ec9-94ba-da616b31a2fe

### Reproduction

1. Use a wallet for 1-2 hours

### Additional Information

- Status version: release 2.30
- Operating System: Android, iOS
- Logs:  [logs (110).zip](https://github.com/user-attachments/files/16526088/logs.110.zip)

**Comment by anastasiyaig** [comment]
https://github.com/user-attachments/assets/a4be9e5d-bbb9-4188-9ff2-458fec5f1948

on desktop i can see balances and collectibles/assets but cant send

**Comment by churik** [comment]
Observations:
1) limits on Grove are not hit, the problem is in Infura limits, more [context](https://discord.com/channels/1210237582470807632/1217172571917647932/1270755174104694794)

2) seems we are hitting Infura because one request must be in error and trigger the circuit breaker, more context [here](https://discord.com/channels/1210237582470807632/1217172571917647932/1270759782353080371)

**Comment by anastasiyaig** [comment]
@dlipicar please update here if you find anything

**Comment by cammellos** [comment]
Recap of the situation:

1) We have seen a fair amount of 401 logs in the app, while investigating with Jakub. I don't have access to logs yet, so can't confirm 100%. If I do get access, I can confirm. In the meantime I can check logs on our side. 
2) An issue was identified with `eth_getLogs` call, https://discord.com/channels/1210237582470807632/1217172790642212946/1271211212075438120 where begin is before end. Someone should ideally take a look at it. 
3) We have access to `test` proxy and @shivekkhurana had a working locally configuration for nginx that we can test. It needs to be extended to support `latest` etc, but should in theory work. That's on myself and @seanstrom .
4) There's a suspicion that infura key has been leaked, if we cross check access logs for prod with infura dashboard, we should get a better idea if that's the case.

cc @ilmotta @shivekkhurana

**Comment by Samyoul** [comment]
A little update on the proxy server access logs. I've pulled down yesterday's logs and ran analysis over them.

The full report can be accessed here https://github.com/status-im/samyoul-notes/raw/master/attachments/2024-08/2024-08-08_access_report.html

I'll share some head lines.

**Comment by Samyoul** [comment]
## Top level statistics

<img width="1336" alt="Screenshot 2024-08-09 at 12 15 41" src="https://github.com/user-attachments/assets/c71a10c6-9e0d-4fd9-ba6e-41b0d17ac27a">

**Comment by Samyoul** [comment]
## Unique visitors per day - Including spiders

<img width="655" alt="Screenshot 2024-08-09 at 12 16 21" src="https://github.com/user-attachments/assets/713d7d01-8c8c-4607-96ae-2afba9f4d198">

**Comment by Samyoul** [comment]
## Requested Files (URLs)

<img width="653" alt="Screenshot 2024-08-09 at 12 17 26" src="https://github.com/user-attachments/assets/089ca1c6-8463-4b0f-bb30-bb7f6cf8c76c">
<img width="654" alt="Screenshot 2024-08-09 at 12 18 04" src="https://github.com/user-attachments/assets/5c9bcdf8-af1f-4e82-a584-1d27c4af41d1">
<img width="651" alt="Screenshot 2024-08-09 at 12 18 21" src="https://github.com/user-attachments/assets/f0c243ab-1081-4cf9-88bf-d978b68915b3">

**Comment by Samyoul** [comment]
## Not Found URLs (404s)
<img width="656" alt="Screenshot 2024-08-09 at 12 20 03" src="https://github.com/user-attachments/assets/8be858ae-8b6f-42ab-acc4-c7bcecd4aba7">

**Comment by Samyoul** [comment]
## Operating Systems
<img width="648" alt="Screenshot 2024-08-09 at 12 21 23" src="https://github.com/user-attachments/assets/ff8c52cb-f0f0-4f48-9b30-9eec4f5e4aee">
<img width="649" alt="Screenshot 2024-08-09 at 12 21 42" src="https://github.com/user-attachments/assets/69e2e49e-4e1f-49d0-ae7c-f9449e8c3d73">

### Crawlers

<img width="654" alt="Screenshot 2024-08-09 at 12 23 38" src="https://github.com/user-attachments/assets/8ea472c9-9af4-45c2-a57b-984b3928ca47">

### Unknown
<img width="642" alt="Screenshot 2024-08-09 at 12 24 49" src="https://github.com/user-attachments/assets/68160bd8-0bed-44ab-a013-9d068b1c2233">

**Comment by Samyoul** [comment]
Looking at the above statistics the majority of the calls ~756.6k of the total ~822.4k come from `Cloudflare-Traffic-Manager/1.0`

50,372 calls come from an unknown which may include `Go-http-client/2.0`

**Comment by Samyoul** [comment]
## Browsers

<img width="645" alt="Screenshot 2024-08-09 at 12 29 41" src="https://github.com/user-attachments/assets/736bc046-41a6-4213-85ea-cdbe0ce61682">

### Crawlers

<img width="647" alt="Screenshot 2024-08-09 at 12 30 19" src="https://github.com/user-attachments/assets/7101f5e0-4e0c-4173-907d-13841e78bc1e">

### Others

<img width="646" alt="Screenshot 2024-08-09 at 12 30 47" src="https://github.com/user-attachments/assets/5dd860be-e246-4e08-be6f-7e6fb6b28678">

**Comment by Samyoul** [comment]
Looking at the above items ~46.6k calls came from our `Go-http-client/2.0`

**Comment by Samyoul** [comment]
## HTTP Status Codes

<img width="648" alt="Screenshot 2024-08-09 at 12 33 35" src="https://github.com/user-attachments/assets/96211851-42ba-497f-ad6d-004b7afabe15">

**Comment by Samyoul** [comment]
30721 401s

**Comment by Samyoul** [comment]
The `error.log` from yesterday shows a lot of errors like this:

```
2024/08/08 16:39:53 [error] 2213327#2213327: *8225470 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.35, server: test.api.status.im, request: "POST /grove/optimism/sepolia/ HTTP/1.1", host: "test.api.status.im"
2024/08/08 16:39:53 [error] 2213327#2213327: *8225471 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.138, server: test.api.status.im, request: "POST /infura/optimism/sepolia/ HTTP/1.1", host: "test.api.status.im"
2024/08/08 16:39:53 [error] 2213327#2213327: *8225472 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.31, server: test.api.status.im, request: "POST /infura/optimism/sepolia/ HTTP/1.1", host: "test.api.status.im"
2024/08/08 16:40:26 [error] 2213327#2213327: *8225751 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.85, server: test.api.status.im, request: "POST /grove/arbitrum/mainnet/ HTTP/1.1", host: "test.api.status.im"
```

These are pinging our relay endpoints such as `/grove/optimism/sepolia/`, using user `coCwfZWuqHQ5niYq`

**Comment by cammellos** [comment]
> The `error.log` from yesterday shows a lot of errors like this:
> 
> ```
> 2024/08/08 16:39:53 [error] 2213327#2213327: *8225470 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.35, server: test.api.status.im, request: "POST /grove/optimism/sepolia/ HTTP/1.1", host: "test.api.status.im"
> 2024/08/08 16:39:53 [error] 2213327#2213327: *8225471 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.138, server: test.api.status.im, request: "POST /infura/optimism/sepolia/ HTTP/1.1", host: "test.api.status.im"
> 2024/08/08 16:39:53 [error] 2213327#2213327: *8225472 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.31, server: test.api.status.im, request: "POST /infura/optimism/sepolia/ HTTP/1.1", host: "test.api.status.im"
> 2024/08/08 16:40:26 [error] 2213327#2213327: *8225751 user "coCwfZWuqHQ5niYq" was not found in "/etc/nginx/auth_basic/proxy", client: 141.101.76.85, server: test.api.status.im, request: "POST /grove/arbitrum/mainnet/ HTTP/1.1", host: "test.api.status.im"
> ```
> 
> These are pinging our relay endpoints such as `/grove/optimism/sepolia/`, using user `coCwfZWuqHQ5niYq`

This looks like it's using maybe prod credentials on test proxy? @siddarthkay @dlipicar ?

**Comment by siddarthkay** [comment]
@cammellos : from CI standpoint we provide prod credentials only to release builds and test credentials to only PR builds.
The choice of the server url however is a status-go concern so if indeed thats really the case, then that logic should be validated.

**Comment by dlipicar** [comment]
@siddarthkay do we have different credentials for Desktop and Mobile? Would like to know which client those requests are coming from.

**Comment by siddarthkay** [comment]
@dlipicar : with the help of @qfrank in this PR here -> https://github.com/status-im/status-mobile/pull/20931 we made mobile app use the appropriate credentials via Jenkins. 
I'm quite confident that desktop app is not using these credentials ( at least not from the builds made in CI )

**Comment by Samyoul** [comment]
This PR https://github.com/status-im/status-desktop/pull/16093 will hopefully resolve the `401` errors we see from the desktop
<img width="991" alt="Screenshot 2024-08-14 at 15 21 10" src="https://github.com/user-attachments/assets/92371774-1d19-45a7-9207-a18b88eca7dd">

**Comment by dlipicar** [comment]
@Samyoul this is needed as well to properly use Proxy credentials on Release builds https://github.com/status-im/status-desktop/pull/16102

**Comment by Samyoul** [comment]
Thank you @dlipicar, I've approved it, hopefully you can get those changes into the next RC

**Comment by churik** [comment]
I believe we can close this one already and deal with a rest of issues related to proxy / caching separately
