### ISSUE TITLE
ERC-1155 Collectible not sent successfully within etherscan on L1

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20973]
### Steps:
1. Send an ERC-1155 Collectible using L1
2. Check the transaction status on Etherscan.

### Actual result:
- The collectible is not sent, even though the fee is estimated as 0.6 USD and the user has 17 USD available.
- The collectible shows an error within Etherscan. Example transaction https://etherscan.io/tx/0xadcc10dc9743c71ea564dc1567e9c644fd0e1f5079fe8a0f03484c5bb4b6243f
![image](https://github.com/user-attachments/assets/97397463-b45e-4c8e-bf2f-f490ac8e7402)

### Expected result:
Collectible is sent

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Release 2.30

**Comment by J-Son89** [comment]
what's the status of this on Desktop?
cc @anastasiyaig, @alaibe
