### ISSUE TITLE
Bridging of assets is blocked unless user has a positive balance of this asset ("Network is not available")

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20988]
### Preconditions:
Recover user that has an asset on  network 1 only (current asset should not be ETH, DAI, or SNT)

### Steps:
1. Recover user with assets that are supported on 3 networks (Example: USDC)
2. Go to the routes generation page
3.Attempt to bridge assets from the network where the user holds assets to another network.

### Actual result:
**On send page:** "Network is not available" is shown in the TO section for the receiver, even though asset (a token available on all networks) is selected for sending.

https://github.com/user-attachments/assets/e8567210-8210-4c4a-9fd9-455345f933b2

**On Bridge Page:** The user cannot select networks on which they do not hold the asset (e.g., if the user has USDC on Optimism, they cannot select Arbitrum or Mainnet for bridging).

![Image](https://github.com/user-attachments/assets/e54b81e9-09ee-443f-9c6e-7d80d3405a3e)

### Expected result:
The app should allow the user to select networks where the asset is supported, even if the user does not have an available balance on those networks.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16548840/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
@shivekkhurana, @ilmotta @status-im/mobile-qa @xAlisher @vkjr - If simple send is happening in 2.31 will this still be needed?
I think you should properly plan ahead for this to spare any double work.

**Comment by ilmotta** [comment]
Good question @J-Son89. I don't know as well. It depends on how _simple send_ will overlap with the existing _complex send_ feature. Will _complex send_ be removed/disabled and will we only support _simple send_ until we reach a butter smooth experience?

**Comment by J-Son89** [comment]
> Good question @J-Son89. I don't know as well. It depends on how _simple send_ will overlap with the existing _complex send_ feature. Will _complex send_ be removed/disabled and will we only support _simple send_ until we reach a butter smooth experience?

Imo it should absolutely be this, remove the complexity complete and have the simple things working exceptionally. 
The network preferences should be removed as even that is another set of complications to support and add no value with simple send.
@xAlisher should have the clearest picture on this but I think both of us agreed on that approach

**Comment by vkjr** [comment]
@J-Son89, good point! No work done yet regarding this issue and there is no reason to do anything before simple send is in place. But when implemented, it is worth rechecking the simple send with the account @VolodLytvynenko mentioned in the description. So we can put `blocked` label until that time. Wdyt, @shivekkhurana @ilmotta ?

**Comment by xAlisher** [comment]
@J-Son89 @ilmotta @vkjr I'm working on it. Will share with you ASAP.

**Comment by VolodLytvynenko** [comment]
still valid. Not related to new rpc from https://github.com/status-im/status-mobile/pull/21378

**Comment by churik** [comment]
Issue wouldn't be valid after re-design of Send flow (as per [this comment](https://github.com/status-im/status-mobile/issues/20988#issuecomment-2298606221) ), also it is not really block user from sending tx, so I don't think that we need to work on anything blocked now.

Removed from milestone, cc @shivekkhurana

**Comment by churik** [comment]
More context: 
![Image](https://github.com/user-attachments/assets/066bd208-6a49-4c29-94ac-f5211210564f)

**Comment by VolodLytvynenko** [comment]
Additionally, such wrong validation is performed within the network edit drawer
![Image](https://github.com/user-attachments/assets/0c911037-d77b-4a89-82b0-f6fcd34a8fb2)

**Comment by shivekkhurana** [comment]
@pavloburykh @churik 

1. Is this needed for 2.31 or not ? 
2. Is this still a bug ?

**Comment by churik** [comment]
@shivekkhurana  
It is still a bug and it blocks bridging, but there are more problems with bridging, i.e. https://github.com/status-im/status-mobile/issues/21180 and https://github.com/status-im/status-mobile/pull/21116, which basically make our bridge not usable. 


Up to you and @ilmotta to decide, but I'd consider to block this functionality if we're facing these issues.

More info: [this thread](https://discord.com/channels/1210237582470807632/1217172571917647932/1295334939960807449)

**Comment by smohamedjavid** [comment]
**Preliminary update:**

Mobile actually depends on the token data (balances-per-chain key) for networks supported by the token.

<img width="250" src="https://github.com/user-attachments/assets/d42ee1d5-3511-4421-8ff6-8d4c83f22158" />

If the token is actually supported in a network but has no positive balance, mobile expects 0 balance in that chain ID/network. I will check how Desktop does.
