### ISSUE TITLE
Java exception 

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-react#20985]
# Bug Report

Crash see screenshots.
Happened when I opened app after cache clear and Force kill due to #20930

![Screenshot_20240808-201318.png](https://github.com/user-attachments/assets/59c3d0a9-466c-4205-8dbd-d6376f4e6924)

Version
![Screenshot_20240808-200928_1.png](https://github.com/user-attachments/assets/9f81cab9-ee73-41da-8bc9-acf8db49749d)

## Problem 
[comment]: # (A problem description)

### Reproduction

1. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by fryorcraken** [comment]
Version cab8ee1d8b4fbc70b722f5798ca238cba56d60ba

**Comment by Parveshdhull** [comment]
related: https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows

**Comment by Parveshdhull** [comment]
Note: This is related to [issue #20930](https://github.com/status-im/status-mobile/issues/20930). It will most likely be fixed automatically once that issue is resolved.

**Comment by Parveshdhull** [comment]
Related: https://developer.android.com/google/play/requirements/target-sdk

**Comment by Parveshdhull** [comment]
> Happened when I opened app after cache clear and Force kill due to https://github.com/status-im/status-mobile/issues/20930

I am closing this issue, as resolving [issue #20930](https://github.com/status-im/status-mobile/issues/20930) should address this problem.
