### ISSUE TITLE
Network Switching: Error shown when sending transaction in 1x1 using Rinkeby network

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2099]
### Description

*Type*: Bug

*Summary*: Slider issue shown when I am trying to send transaction under `Rinkeby` network, fee slider is not displayed

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/31440168-9747c946-ae97-11e7-8032-86fab9384965.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Switch to Rinkeby network
- Go to 1x1 chat
- Perform `/send` command
- **Pay attention that slider with transaction fee is not displayed**

### Additional Information
* Status version:  0.9.10-187-g3286b475+ (1744)
* Operating System: Android

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/6808051/sessions/18/?accessToken=rMyQHrimkR-CStj3/jilBT-mF0I

**Comment by rasom** [comment]
Is this Rinkeby with or without upstream RPC? Can't reproduce issue

**Comment by asemiankevich** [comment]
tested in develop, will be in release 0.9.12
