### ISSUE TITLE
Network Switching: Send transaction screen is shown in 1x1 chat with 0 ETH balance under Rinkeby with upstream RPC network

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2100]
### Description

*Type*: Bug

*Summary*: **NOTE: this happens in specific scenario**

#### Expected behavior
I dont have to proceed to Sign transaction screen if I have 0 ETH balance when sending transaction in 1x1 chat

#### Actual behavior
User can reach Sign transaction screen when sending funds having 0 balance. Tapping on 'sig' button calls error message which is shown on background.

### Reproduction

- Open Status under Rinkeby network
- Send transaction in 1x1 chat and receive error with slider
- Switch to Rinkeby with upstream RPC network
- Go to 1x1 chat and try to send transaction having 0 balance

### Additional Information
* Status version:  0.9.10-187-g3286b475+ (1744)
* Operating System: Android

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/6808051/sessions/23/?accessToken=rcbm5f1Qdyc3hlRxeOyhiajcroU

**Comment by rasom** [comment]
Did this happen in Rinkeby with LES or Rinkeby with upstream RPC? Can't reproduce on second, as can't sync Rinkeby with LES...

**Comment by rasom** [comment]
Can't reproduce in latest develop, most likely was related to https://github.com/status-im/status-go/issues/372

**Comment by asemiankevich** [comment]
@rasom i can see slider issue is still in place. Logged https://github.com/status-im/status-react/issues/2170 in this regard. Current original issue should be closed as I can't reproduce it in latest develop.
![image](https://user-images.githubusercontent.com/28752642/31616429-5e9ea860-b295-11e7-9ad5-52025684b2b4.png)
