### ISSUE TITLE
Add beta hints to Messages and Communities titles

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21006]
# Feature Issue

<img src="https://github.com/user-attachments/assets/4311ad97-8259-4228-a976-7d7469b1c4b8" height="500" />

### User Story

As a user, I want to understand how stable/complete certain features are, so that I can adjust my own expectations and not be as frustrated when certain features don't work as I expected.

### Description

We want to add small hints to the user that certain features are still in beta. FYI We are updating the website as well with beta hints.

### Acceptance Criteria

- One _beta_ hint besides the Communities title in the home screen.
- One _beta_ hint besides the Messages title in the home screen.
- Check with a designer how the hint should look in dark mode because in Figma we only see designs for the light theme.

The browser is out of scope because it's disabled/hidden at the moment.

### Resources

- Figma https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=12860-106177&t=BRWDfFvCG72jieo3-0

**Comment by pavloburykh** [comment]
@seanstrom thanks for the PR! Ready for merge and cherrypick.
