### ISSUE TITLE
Set `Gas amount` tx settings screen

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#21025]
# Problem

Implement set `Gas amount` tx settings screen
![image](https://github.com/user-attachments/assets/9c5c8cab-64a3-4ba7-8984-05b33fc00230)

[Figma](https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=2018-419220&m=dev).

**Blocked by** #21017 
## TBD: 
- where to get `safe estimate`? 
- Possible errors? 
- Limits?

**Comment by shivekkhurana** [comment]
Superseeded by #21023 and #21024
