### ISSUE TITLE
Set `per-gas price limit` tx settings screen.

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#21027]
# Problem

Implement `per-gas price limit` tx settings screen.

![image](https://github.com/user-attachments/assets/7ff7f3e3-0f46-44c5-beb9-1bfd4ae62cc3)

[Figma](https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=2018-419240&m=dev)
**Blocked by #21017**

## TBD 
- where to get `current base fee`? 
- Possible errors? 
- Limits?

**Comment by shivekkhurana** [comment]
Superseeded by #21023 and #21024
