### ISSUE TITLE
Set `per-gas tip limit` tx settings screen.

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#21026]
# Problem

 Implement `per-gas tip limit` tx settings screen.
![image](https://github.com/user-attachments/assets/37dfe078-0504-4d54-8f2e-a474eec2038d)

[Figma](https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=2018-419230&m=dev). 

**Blocked by** #21017
## TBD: 
- where to get `current average`? 
- Possible errors? 
- Limts?

**Comment by shivekkhurana** [comment]
Superseeded by #21023 and #21024
