### ISSUE TITLE
Allow users to independently enable Waku telemetry and in-app analytics

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21035]
# Feature Issue

### User Stories

1. As a new Status user, I want to make an informed decision about whether I want to help improve Status by sharing usage data, so I'll clearly understand what data will be shared from all profiles and what data will be shared from the current one.

2.  As a more experienced user, I want to have explicit control over the sharing status of data from all profiles and the current profile, so I can better manage the data that might expose my identity.

### Description
Onbording:
- Added Waku telemetry options.
- Created separate sections for "All profiles" and "Current profile" data items.
- Changed the CTA to "Help us improve Status" to address legal concerns. (This avoids phrasing around agreeing to share usage data, as some data will be shared regardless of the decision. The focus is on offering help, not agreeing to data sharing.)

Settings:
- Added Waku telemetry options.
- Created separate sections for "App interactions (Shared from all profiles)" and "Network behavior (Shared from the current profile)" items.
- Updated the bottom copy to address legal concerns.

### Acceptance Criteria

Onboarding:
Design matches (same drawer in 3 places): 
- Create profile https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=13726-23136&t=fASRgmUgi4BQtcGb-1
- Restore profile https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=13726-29112&t=fASRgmUgi4BQtcGb-1
- Update app https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14097-4045&t=fASRgmUgi4BQtcGb-1

Settings:
- Design matches: https://www.figma.com/design/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?node-id=8477-8868&t=c1MBMhpUvDR9ZthO-1
- Users can toggle both flags independently.

**Comment by ilmotta** [comment]
FYI: After a suggestion from @J-Son89, we are going to go live with 2.30 release without this issue resolved. We will consider this issue on a smaller, subsequent release, like 2.30.1.

**Comment by fryorcraken** [comment]
Note that this issue blocks the following Waku milestones:

- [Milestone Direct Message Reliability](https://github.com/waku-org/pm/milestone/28)
- [Milestone Bandwidth optimization and protocol review](https://github.com/waku-org/pm/milestone/31)

**Comment by ilmotta** [comment]
@fryorcraken we understand this limitation and we will try to release the improvements from this issue as soon as it's ready.
