### ISSUE TITLE
Network switching - notify user about the need to login again after the network is switched

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#2103]
Add alert with text that user will need to login again after the network is switched.
When applicable - can we combine this message with the restart message and don’t display 2 alerts in the row?

**Comment by annadanchenko** [comment]
@pablanopete when select another network in Network settings: popup is shown "This app will stop and close. When you reopen it, the selected network will be used". There is no second alert shown. It looks like this issue can be closed. Agree?
