### ISSUE TITLE
Edit button is doulbed if try again button is tapped a few times

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21043]
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Recover a user with available assets on at least two networks.
2. Navigate to the routes generation page.
3. Enter a value that is available on both networks (e.g., if the user has 1 ETH on Optimism and 1 ETH on Arbitrum, enter 1.5 ETH).
4. Tap the "Try Again" button multiple times.

### Actual Result:
The "Edit" button appears multiple times on the screen.

![image](https://github.com/user-attachments/assets/1648cc7f-a7aa-4192-8aed-a004384f50eb)

### Expected Result:
The "Edit" button should be displayed only once, regardless of how many times the "Try Again" button is tapped

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16610842/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
@shivekkhurana, @ilmotta @status-im/mobile-qa @xAlisher - afaik this issue becomes obsolete if it is 2.30 because the simple send will mean this part of the UI no longer exists.

**Comment by churik** [comment]
That's true, not only this. I'll review all issues after release and if the desicion about simplification hass been made, I can close quite a bunch of issues

**Comment by xAlisher** [comment]
@J-Son89 @churik I agree. Hopefully, we’ll reach a final conclusion about the simplification this week or next.

**Comment by shivekkhurana** [comment]
> That's true, not only this. I'll review all issues after release and if the desicion about simplification hass been made, I can close quite a bunch of issues

Simplification doesn't guarantee resolution. The issue might be happening at network level.

**Comment by churik** [comment]
This issue is purely front-end, as far as I understood from the conversation with @shivekkhurana yesterday, we are staying with this approach for quite a while, so better to take it

**Comment by smohamedjavid** [comment]
Fixed there: #21306
