### ISSUE TITLE
Community banner and logo are often missing

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21048]
There are no specific steps. At some point community logos/banners stop fetching. They can be fetched after relogin but after some time they disappear again. 

Hope attached logs will help to identify the issue

[logs (40).zip](https://github.com/user-attachments/files/16615554/logs.40.zip)
![photo_2024-08-14 18 30 32](https://github.com/user-attachments/assets/7e880229-ef2d-4f4d-9a5e-d03b37d87178)

https://github.com/user-attachments/assets/8e6d7c90-cdbb-4b8d-b213-eb1b7e5bdff4

### Additional Information

- Status version: release 2.30 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
duplicate of https://github.com/status-im/status-mobile/issues/20982

**Comment by pavloburykh** [comment]
closing as duplicate of https://github.com/status-im/status-mobile/issues/20982 Thanks for noticing @Parveshdhull
