### ISSUE TITLE
"underfined is not a function error is shown" error is randomly shown

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21045]
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Login
2. Start sending flow

### Actual result:
"underfined is not a function error is shown" error is randomly shown

https://github.com/user-attachments/assets/8cb7a349-5be4-450e-bbed-5d153e3664dc

### Expected result:
No error is shown

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (6).zip](https://github.com/user-attachments/files/16613795/logs.6.zip)

### ENV:
Release 2.30 (20240814141744)

**Comment by qoqobolo** [comment]
Faced it in two more cases:

1. When entering 7 or more decimals when sending a tx

<img width="374" alt="Screenshot 2024-08-14 at 15 32 48" src="https://github.com/user-attachments/assets/75693279-2902-4d8a-a54a-11bfa98adf98">

2. Just one time on re-login (that was a keycard account, couldn't reproduce)

<img width="338" alt="Screenshot 2024-08-14 at 15 34 04" src="https://github.com/user-attachments/assets/3db45c18-2087-4abe-b339-b13f9bc7334e">

**Comment by pavloburykh** [comment]
Can't reproduce. Feel free to reopen in case you face it @status-im/mobile-qa
