### ISSUE TITLE
Nothing happens on pressing "Try again" button when searching routes

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#21044]
# Bug Report

## Problem 

The easiest way to reproduce the issue is to enter an amount close to MAX, e.g. if you have 0.00697 ETH on your balance (see the video), try to enter 0.0069

https://github.com/user-attachments/assets/1d27d9b7-91e4-4728-8d4f-9a4557520b34

However, the issue is also reproducible for a smaller amount (just harder to get the `Try again` button):

https://github.com/user-attachments/assets/ae187a8f-e95b-4dbe-ac13-a1aaf487b385

### Reproduction

1. Wallet > Send tx > Select a recipient
2. Enter an amount close to MAX token amount on your balance _or_ just keep trying until you get the message `No routes found` and the `Try again` button
3. Press `Try again`

#### Expected behavior
The route search process is initiated again

#### Actual behavior

Nothing happens on pressing the button

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16613492/Status-debug-logs.zip)

### Additional Information

- Status version: RC 2.30 https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F2.30.x/17/ 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
@status-im/mobile-qa - this issue seems to not be reproducible on latest release branch/version

**Comment by pavloburykh** [comment]
> @status-im/mobile-qa - this issue seems to not be reproducible on latest release branch/version

Hey @J-Son89! Let's close it. I have not faced this issue lately.
