### ISSUE TITLE
Provider is down error investigation

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21056]
# Bug Report

## Problem 
Seems there is no clear understanding of when and why we are getting "Provider is down" errors (currently we have it hidden because of https://github.com/status-im/status-mobile/issues/21054), and proper investigation is needed.

#### Expected behavior
"Provider is down" only when we get errors from providers (currently it is not the case; we investigated it with @Samyoul and even after getting `200` from pokt that app is falling back to infura)

### Reproduction

1. Open wallet and use it for 10-15 mins

## Accepted criteria

(followup onhttps://github.com/status-im/status-mobile/pull/21055)

### Improved Error Handling:
Differentiate between types of errors (e.g., rate limits, connectivity issues, authorization failures).
Implement more nuanced responses, such as using local cache when rate limits are hit, informing the user when they are offline, or providing specific feedback for unhandled errors.

### Investigation and Refinement:
Allocate time to investigate the root causes of the "flip-flapping" connection state and refine the logic to reduce false positives for the chain down signal.

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cc @shivekkhurana

**Comment by J-Son89** [comment]
I would consider this higher than `low-priority` if it's work available at the beginning of a development cycle. It makes the app experience horrendous 😓

**Comment by ilmotta** [comment]
- Linking with issue https://github.com/status-im/status-mobile/issues/21071. They seem to be slightly different, but can probably be closed together.

**Comment by friofry** [comment]
Agreed, I'm currently delving into that part of the code. So I've assigned this ticket to myself

**Comment by churik** [comment]
cross-posting: https://github.com/status-im/status-mobile/issues/21401

**Comment by friofry** [comment]
https://github.com/status-im/status-go/pull/5924
