### ISSUE TITLE
Unable to tap on chats/channels after opening profile link from chat or after opening group details

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21065]
# Bug Report

### Reproduction
1. Open a chat and send a link to your profile.
2. Tap the link to open your profile.
3. Return to the Messages screen.
4. Attempt to tap on any other chat or community channel.

#### Expected behavior
Chats and community channels are not tappable. The user is unable to open any chat or community channel.

#### Actual behavior
Chats and community channels are not tappable. The user is unable to open any chat or community channel.

https://github.com/user-attachments/assets/dcf87ec5-6c45-45b8-84bc-d32ed4db5b68

### Additional Information
- Status version: release
- Operating System: Android, iOS

**Comment by ulisesmac** [comment]
Blocked until the new navigation library is integrated.

For more context check:
https://github.com/status-im/status-mobile/pull/21142#issuecomment-2477267536

**Comment by churik** [comment]
It is pretty wide on cases, basically if you open managing screen from group details, it will be blocked as well.
