### ISSUE TITLE
No photo preview in mention notifications from Group chat/ communities

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21060]
# Bug Report

### Reproduction
1. Open a group chat or community in User 1
2. Mention a User 2 in a message and include a photo in the same message
3. Login as User 2 and open Activity center
4. Observe the notification received by the mentioned User 2

#### Expected behavior
The notification should display a preview of the photo included in the mention

#### Actual behavior
The notification does not display a photo preview, only the text of the mention

https://github.com/user-attachments/assets/92fc047a-8f90-48aa-baa9-1b3804453935

### Additional Information
- Status version: release
- Operating System: Android, iOS

**Comment by churik** [comment]
@ulisesmac I'd say if there will be not even preview but text like "3 photos %text%" it is also acceptable, as getting preview from status-go might be tricky based on previous issues

**Comment by ulisesmac** [comment]
> @ulisesmac I'd say if there will be not even preview but text like "3 photos %text%" it is also acceptable, as getting preview from status-go might be tricky based on previous issues

Thank you, I haven't started this issue yet  but I'll consider it 👍
