### ISSUE TITLE
⛓️ ⬇️ Investigate Chain Down Issues

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#21071]
# Bug Report

## Problem 

The `status-go` backend emits a chain-down signal if it's not able to connect to a provider. This happens due to a variety of reasons outlined in the Context PR below (check PR comments).

When the chain down signal is emitted, the mobile used to show a Toast stating a chain went down. 

Discord Conversation 1: https://discord.com/channels/1210237582470807632/1217172790642212946/1273600305866608641
Context: #21055 

#### Expected behavior

- The chain should not go down (and not flip-flop statuses)
- We need to handle all known errors on the chain and emit chain down signals responsibly. 
- At UI level, a toast might not be the best option as we are trying to convey a state, where as a toast is good to convey a message ( or event)

#### Actual behavior
- Chain goes down (flip flops state)
- All errors are not handled
- The UI showed toasts which have been disabled

### Reproduction

1. Undo changes done in #21055 
2. Use the app as normal
3. Turn off wifi and data (go offline)
4. Turn wifi on again, try to navigate in the app

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ilmotta** [comment]
- Linking with issue https://github.com/status-im/status-mobile/issues/21056. They seem to be slightly different, but can probably be closed together.

**Comment by friofry** [comment]
Quick update from me
After discussion with @cammellos and @IvanBelyakoff, I'm focusing on 3 issues:

1) RPC client should not make requests while the app/device is offline and should queue them.
2) Do not treat whitelist errors as API failures.
2) Fix API response error handling. Each provider should have it's own error handling.
