### ISSUE TITLE
[iOS] No address parsing when user scans QR code on Add Address screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21092]
# Bug Report

## Problem 
[comment]: # (A problem description)
Empty screen when user scans somebody's Wallet QR code during creation of Saved Address record

### Reproduction

1. Login to app
2. Go to `Profile -> Wallet -> Saved Addresses`
3. Tap on `+`
4. Scan smd's Wallet QR code

#### Actual behavior

https://github.com/user-attachments/assets/30555a41-dc4e-436a-b29c-d74a6ecb916c

#### Expected behavior

<img width="215" alt="Screenshot 2024-08-20 at 14 55 47" src="https://github.com/user-attachments/assets/16ce02b6-06ad-4d07-bd76-8482abfc387a">

### Additional Information

- Status version: release
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
Fixed here: https://github.com/status-im/status-mobile/pull/21100
