### ISSUE TITLE
The wrong addresses are derived from default keypairs after upgrade

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21096]
# Bug Report

## Problem 
Currently the addresses that derived using the same deriviation path (i.e. `m/44'/60'/0'/0/1`) are different in case of recover the same keypair on the fresh build and on upgraded.

#### Expected behavior
the same account on both devices

#### Actual behavior
same deriviation path, different address

On device 1:
![IMAGE 2024-08-20 20:41:45](https://github.com/user-attachments/assets/185aebf3-f5ae-47e9-b575-2e860d3d9e8c)

On device 2: 

![IMAGE 2024-08-20 20:41:39](https://github.com/user-attachments/assets/7edfe788-66e2-40f3-8b11-2d6b366d5821)

### Reproduction

1. Device1: recover account from seed phrase on v1 
2. Device2: recover the same account using same seed phrase on v2
3. Device1: upgrade to v2
4. Device1: add account from default keypair, check `About`
5. Device2: add account from default keypair, check `About`

### Additional Information

- Status version: release 2.30 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
Fixed by https://github.com/status-im/status-mobile/pull/21099. Cherry picked into release branch.
