### ISSUE TITLE
Cannot create derrived account from imported key pair after upgrade

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21103]
**Steps:** 

1. Install V1 app
2. Import new account using private key / seed phrase
3. Upgrade to V2
4. Try to create derrived account based on key imported pair 
5. Try to remove imported account

**Actual result:** 

1. Cannot create derrived account
2. Cannot remove such improted account

[Status-debug-logs - 2024-08-21T143909.954.zip](https://github.com/user-attachments/files/16691341/Status-debug-logs.-.2024-08-21T143909.954.zip)

https://github.com/user-attachments/assets/658103fe-1ffb-4bc0-b612-279b7518d38c

https://github.com/user-attachments/assets/ca328e0e-c499-47f0-8f4c-a916f1e1ff20

**Expected result:** 

1. Disable possibility to create derived accounts using key pairs with empty origin
2. Disable possibility to Remove accounts with empty origin

### Additional Information

- Status version: nightly, release 
- Operating System: Android, iOS

**Comment by smohamedjavid** [comment]
Fixed here: https://github.com/status-im/status-mobile/pull/21104
