### ISSUE TITLE
Exchange ERC-20 using wallet connect throws an error ("Something went wrong")

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21137]
# Bug Report

## Problem 
At attempt to exchange any asset (not ETH) through decentralized exchanged (i.e. Uniswap or 0X) there is error at attempt to perform last step required for exchange

#### Expected behavior
can exchange Rare

#### Actual behavior

https://github.com/user-attachments/assets/9a6ddea4-4434-4bee-b1cd-648de96ac003

### Reproduction

1. Connect wallet to Uniswap
2. Try to exchange any ERC20 to ETH

### Additional Information

- Status version: release 2.30  
- Operating System: Android, iOS
- Logs: [logs (1).zip](https://github.com/user-attachments/files/16784092/logs.1.zip)

**IMPORTANT NOTE:** seems after a while it was possible to finish the transaction, but behavior makes user think that there is something wrong with a flow. 

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cc @clauxx

**Comment by clauxx** [comment]
Most likely it's the issue of us using the old geth version, where not all typed data types were accepted as valid. If that's the case, the potential fix was already merged in status-go in [this PR](https://github.com/status-im/status-go/pull/5755). Should test with the latest status-go to make sure it all works.

**Comment by pavloburykh** [comment]
Successfully swapped DAI to WBTC using 1inch Dapp. Closing the issue. 

Adding test-cases-required label, so we test exchange of tokens different from ETH during release testing.
