### ISSUE TITLE
Crash when trying to add Waku settings in Advanced Settings

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21155]
# Bug Report

## Problem 

Crash when user attempts to add Waku settings.

### Expected behavior

User should be able to manage Waku custom settings. **Note**: This feature is not working on mobile already for a long time (many months).

### Actual behavior

In a release build the app crashes, in debug this is the error:

```
Error: No protocol method IDeref.-deref defined for type undefined:

This error is located at:
    in edit-node (created by legacy.status_im.ui.screens.wakuv2_settings.edit_node.views.edit_node)
    in legacy.status_im.ui.screens.wakuv2_settings.edit_node.views.edit_node
```

<img src="https://github.com/user-attachments/assets/111594a7-9a02-45f9-bbd3-b9dd17b02f11" width="350" />

### Reproduction

1. Go to Advanced Settings
2. Open Wakuv2 settings
3. Press plus button

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
@flexsurfer 
https://github.com/status-im/status-mobile/issues/21159#issuecomment-2324763724 

Can we move conversation here?

**Comment by flexsurfer** [comment]
does anyone know if we still need this setting and who will be using it?

**Comment by churik** [comment]
@richard-ramos may be?

**Comment by richard-ramos** [comment]
Which `wakuV2` settings are these? Based on the error message I suppose it's to add custom nodes. Ideally we should be able to add custom multiaddresses and enrtrees for nodes we want to connect to as a way to make the app more decentralized, but it's likely this is not a priority now, so this setting can be probably hidden.

**Comment by ilmotta** [comment]
For this issue I think we should make a call of removing or fixing, instead of hiding. Fixing could be easy given the stack trace, if not, we can remove, but that would be a shame. I think the feature for advanced users is nice and fits well with Status' principles.

@flexsurfer have you ever used this feature in the old days of v1? Maybe if you could take a quick look you'd be able to figure out why there's a nil atom being deref'ed.

**Comment by flexsurfer** [comment]
i've never used this settings, and i don't remember that anyone ever used it, but sure I can take a look and fix, don't this there is something difficult
