### ISSUE TITLE
Crash when interacting with the Add button in WakuV2 settings

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21159]
**Steps:** 

1. Go to Profile - Advanced - WakuV2 settings
2. Tap Add button (+ pus button) in top right corner
3. Observe the crash

**Expected result:** not sure that we need WakuV2 settings at all. Probably we need to hide it. WDYT @ilmotta @churik 

**Actual result:** app crashes with `No protocol method IDeref.-deref defined for type undefined:`

![photo_2024-09-02 13 39 11](https://github.com/user-attachments/assets/0863e4c3-ddda-4a70-b0d2-8f770871f3ae)
[Status-debug-logs - 2024-09-02T133906.537.zip](https://github.com/user-attachments/files/16836359/Status-debug-logs.-.2024-09-02T133906.537.zip)

https://github.com/user-attachments/assets/d2b21158-0189-43f1-a803-1b0d496d02bc

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
@pavloburykh, this feature hasn't been working for a long time as far as I checked. I opened an issue last week about this, they are duplicates https://github.com/status-im/status-mobile/issues/21155.

I think one of the waku members was expecting to use this feature in the new version and reported as a bug. The fix could be simple, but I never used this feature to understand it.

@flexsurfer do you remember how this feature used to work? Do you think it's valuable and why/why not?

**Comment by churik** [comment]
close this as a duplicate, re-add https://github.com/status-im/status-mobile/issues/21155 to milestone
