### ISSUE TITLE
 Hidden community appears on "Opened" Tab with unread message counter from 1-1 chats

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21169]
# Bug Report

## Problem 
When adding a new community on the "Opened" tab, a hidden community (I assume it's a default community "Status Iny" that was later hidden) is displayed. This community pulls the unread message counter from 1-1 chats. Tapping on it shows a popup with an error, but if you long tap, it opens the menu as it would in a regular community.

### Reproduction
1. Create a new User 1.
2. Add User 2 to User 1's contact list.
3. User 2 sends an invite to a community 'Commun'.
4. User 1 joins the community.
5. User 2 send messages in 1-1 chat

#### Expected behavior
The "Opened" tab shows 2 communities: the default 'Status' and the new 'Commun'.

#### Actual behavior
The "Opened" tab shows 3 communities: the default 'Status', the new 'Commun', and one additional hidden community. This hidden community pulls the unread message counter from 1-1 chats. 

https://github.com/user-attachments/assets/6f13c250-051f-4b6b-acda-68c4fc516af3

### Additional Information

- Status version: nightly 03.09.2024 or app version: 2.29.0 (20240903020837)
- Operating System: Android, iOS
- Logs: [Status-debug-logs (8).zip](https://github.com/user-attachments/files/16850273/Status-debug-logs.8.zip)

**Comment by ilmotta** [comment]
Related to https://github.com/status-im/status-mobile/issues/20762
