### ISSUE TITLE
status mobile app crash randomly on ios simulator

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#21174]
# Bug Report

### Reproduction

1. create a new status account let's say userA
2. create a closed community 
<img width="409" alt="image" src="https://github.com/user-attachments/assets/ee07f4d9-86b2-4fea-b99c-dcc596065801">

3. create another account userB and send some messages
4. userB join the closed community
5. keep the app running in the front and do nothing for userA for a while, then app may crash randomly.

Sometimes the crash happen soon after userA login

### Additional Information

- Status version: latest `develop` branch, commit id: `2983af67d6e7d465d813020ed5688d0d3f2fdb1a`
- Operating System: iOS(simulator)

key log information which shows it's relate to waku:
```
Thread 15 Crashed:
0   ???                                    0x10c699a78 ???
1   <translation info unavailable>         0x10ca8259c ???
2   libsystem_pthread.dylib                0x11a963ebd pthread_kill + 262
3   libsystem_c.dylib                      0x11a1ac2a0 raise + 24
4   StatusIm                               0x1056c5e4b runtime.raise_trampoline.abi0 + 11
5   StatusIm                               0x1056c3ce8 runtime.asmcgocall.abi0 + 104
6   StatusIm                               0x1056ad9de runtime.libcCall + 94
7   StatusIm                               0x1056ace86 runtime.raise.abi0 + 38
8   StatusIm                               0x1056a4265 runtime.dieFromSignal + 69
9   StatusIm                               0x10568d465 runtime.fatalpanic + 133
10  StatusIm                               0x10568cbac runtime.gopanic + 940
11  StatusIm                               0x10568aa3c runtime.goPanicIndex + 124
12  StatusIm                               0x10637a634 */publish.(*envelopePriorityQueue).Less + 180
13  StatusIm                               0x1058c2df4 */heap.up + 116
14  StatusIm                               0x1058c2b35 */heap.Push + 85
15  StatusIm                               0x106378ccd */publish.(*MessageQueue).Start + 205
16  StatusIm                               0x106837348 */wakuv2.(*Waku).Start.func8 + 40
```
<img width="698" alt="image" src="https://github.com/user-attachments/assets/882f5c8b-9d00-42dd-8030-70a4061a776d">

[status-ios-crash-details.log](https://github.com/user-attachments/files/16869274/status-ios-crash.log)

**Comment by churik** [comment]
@richard-ramos mayb eyou know what might be the reason?

**Comment by qfrank** [comment]
reopen this until https://github.com/status-im/status-mobile/pull/21177 get merged
