### ISSUE TITLE
Implement Request Logging in status-go

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21176]
# Feature Issue

### User Story

As a QA/developer, I want to view the requests made from status-go **so that** I can gather more information and effectively communicate it with developers.

### Description

Currently, there is no mechanism in place to view the status-go requests made from the client side, resulting in a lack of logging regarding what has been sent to the backend. Additionally, the existing `geth.log` lacks the necessary information and is cluttered with noise from Waku, making it challenging to use for other purposes.

After conducting an experiment with a [new tool](https://github.com/status-im/status-go/blob/develop/integration-tests/README.MD) (thanks to @antdanchenko), after building [PR #5498](https://github.com/status-im/status-go/pull/5498) I got this entry in `geth.log`. 

![Request Logging Example](https://github.com/user-attachments/assets/ccb375af-1632-4c3b-bb23-dbd1ff9f50e1)

This demonstrates that logging requests is feasible, and we should implement this feature. By doing so, both QA and developers will gain valuable insights into the application's behavior, enhancing our ability to cover more scenarios in integration tests. Currently, the absence of specifications hampers our ability to expand testing effectively.

I propose making a configuration variable, such as `REQUESTS_GO`(use it similarly to env variable from https://github.com/status-im/status-mobile/blob/develop/.env.e2e). 

When set to true, this variable would log all requests from the backend to a separate file, `requests.log`. 
This setting should be enabled by default for PRs and end-to-end builds, while for other types, it should default to false (meaning no file should be created)
I understand that it might be not applicable to any method which we're calling from status-go, but it is crucial to start logging more, as currently we're testing almost blindly.

### Acceptance Criteria

- A configuration variable `REQUESTS_GO` (or any other) is created to control logging of requests.
- When `REQUESTS_GO` is set to `TRUE`, all requests from the client to status-go are logged to a file named `requests.log`.
- enabled for PR/e2e builds
- `REQUESTS_GO` is disabled for nightly/release builds
- Documentation is updated to reflect the new logging feature and configuration variable.

### Notes

- This feature will enhance debugging capabilities and provide clearer insights into request handling.
- This will allow us to expand on status-go integration tests

**Comment by ilmotta** [comment]
> REQUESTS_GO is disabled for nightly/release builds

An addendum to this point, I think we should go as far as to add an explicit assertion in the code that `REQUESTS_GO` cannot be set to true in release builds, just so we eliminate the potential for compromising on privacy (e.g. by a mistake in CI builds). The assertion would throw an exception at **compile-time**.

**Comment by antdanchenko** [comment]
@churik @ilmotta we already have this logging on test.proxy side (ONLY for internal test builds) [here](https://github.com/status-im/infra-proxy/blob/master/ansible/group_vars/proxy.test.yml) 
I am not sure if it makes sense to reimplement on client side, maybe it is better just to expand logging for text.proxy

Overall It would be great to keep this kind of logging on test.proxy side (ONLY for internal test builds) rather then on client side

We’re encountering numerous intermittent errors from the provider's side, right now. For instance, we can successfully query eth_getBalance multiple times and get accurate results, but occasionally, RPC starts responding with 0 for accounts that definitely have funds, across various networks. 
This is just one example among many, and we need this kind of centralised monitoring (ONLY for internal test builds) to gather, identify and report this issues back to providers so they can address them properly.

Having the ability to browse these logs gathered from many internal test clients in a single place would be a bit better, as it provides a global view of the situation. While with logging on client side we have to use a client to catch these issues which isn’t easy cause most of the issues are not constant

**Comment by churik** [comment]
@antdanchenko but from the client side we still need device_id to search logs, right? 

If you can point where we can get it, I can ask @qfrank to log it somewhere for us to have ability to filter through logs. 

And also as far as I understand the goal is to log both responses and requests (to both waku and grove) on the proxy side? 

Wouldn't it affect message reliability?

**Comment by qfrank** [comment]
I thought this feature targets not only proxy requests/responses but also any requests/responses between the frontend and backend, no?

**Comment by antdanchenko** [comment]
@churik 
we haven't talked about waku, yet, I guess it can be possible for test builds ONLY
speaking of device_id, not sure about device_id but anything in headers, like any UUID that will help us to identify unique session per test client

@qfrank it targets only RPC requests that are going through test.proxy for test builds ONLY, now
My point is to have similar approach to logging requests/responses to other services when possible or at least not to reimplement those that we are already have on test.proxy side

**Comment by qfrank** [comment]
> it targets only RPC requests that are going through test.proxy for test builds ONLY

if so, re-implement logging request/response relate to proxy between frontend<->status-go doesn't make much sense as we already have logging on the proxy server side.

what I thought was implement a feature logging any request/response between frontend<->status-go(backend) , this is different from the things we have done on proxy server side.

**Comment by qfrank** [comment]
> My point is to have similar approach to logging requests/responses to other services when possible 

what do you mean regarding `other services` ? having a centralised place(server) to store the request/response logs? @antdanchenko 

if yes, it still make sense as our first step 👇 🤔 we can implement collecting the content later if needed
> what I thought was implement a feature logging any request/response between frontend<->status-go(backend) , this is different from the things we have done on proxy server side.

**Comment by ilmotta** [comment]
I'm jumping back to the problem statement shared by @churik.

1. As a QA/developer, I want to view the requests made from status-go so that I can gather more information and effectively communicate it with developers.
2. Currently, there is no mechanism in place to view the status-go requests made from the client side, resulting in a lack of logging regarding what has been sent to the backend

To solve problem 1, we could log directly in the test.proxy environment and for non-release builds as @antdanchenko already said. We could send a device ID as pointed out.

To solve problem 2 we would need to log requests/responses sent from the client to status-go. This would be an easy extension because we already have a bit of this code in place. Those are very useful to devs because we can call status-go endpoints from the client and see how the app reacts, not just status-go+proxy, therefore useful for debuggability.

One side note: I'm worried about enabling request/response logs in the test proxy for dev builds because it's very easy for a developer to forget about this and use an account of "more importance" or sometimes it's the only way to reproduce a bug. Logging request/responses should be opt-in for developers (disabled by default), but could be automatic in PR builds.

----

So there are two problems to increase observability, can we do both?

**Comment by antdanchenko** [comment]
> what do you mean regarding `other services` ? having a centralised place(server) to store the request/response logs? @antdanchenko

@qfrank yes, It would be amazing to have a centralised place(server) to store and browse the request/response logs for test builds only

**Comment by churik** [comment]
@qfrank if it makes sense and doesn't take a lot of time, I'd prefer to have to log requests/responses sent from the client to status-go. It might be duplication of work to some extent, I'm just not exactly sure what we can have in centralized services. 

May be there are more requests that is impossible to store in proxy. And we'll have more info on them, therefore it will help with debugging immensly

**Comment by ilmotta** [comment]
> @qfrank if it makes sense and doesn't take a lot of time, I'd prefer to have to log requests/responses sent from the client to status-go. It might be duplication of work to some extent, I'm just not exactly sure what we can have in centralized services.
> 
> May be there are more requests that is impossible to store in proxy. And we'll have more info on them, therefore it will help with debugging immensly

@churik that's significantly more work than only logging on the proxy.test and separated by device ID. How would the requests/responses from client to status-go be helpful to QAs? They are higher-level, they won't show the request/responses sent to web3 providers, for example.

> May be there are more requests that is impossible to store in proxy.

@antdanchenko how long do you think it could be reasonable to retain logs in proxy.test? Assuming only internal CCs are accessing it? Better question, how much storage you think is reasonable to provide to keep rotating these logs for request/responses?

**Comment by antdanchenko** [comment]
@ilmotta at least for 3 days, while a couple of weeks would be perfect
not sure about the size of the storage, we can start with few days to see the volume first

**Comment by ilmotta** [comment]
> at least for 3 days, while a couple of weeks would be perfect
not sure about the size of the storage, we can start with few days to see the volume first

If we could go up to at least a week it would be quite good because it would give the QA team and devs a more realistic time to react to bugs.

On the other hand, I think logging responses can get prohibitively expensive for storage and quickly, but let's see how it all goes. If it gets tricky we can always improve the solution by persisting requests separately from responses and rotating them differently. Requests we would be able to log for much longer periods of time.
