### ISSUE TITLE
Not able to accept friend request

### ISSUE THREAD

**Issue by chair28980** [status-im/status-react#21182]
# Bug Report

## Problem 

Accept friend request not working when pressing button or slide to confirm.

#### Expected behavior

When pressing Accept or sliding left to confirm friend request should be accepted.

#### Actual behavior

App does not change state after clicking accept or sliding button to confirm.

### Reproduction

1. Receive new friend request
2. Attempt to accept

### UPDATE

I was able to accept the request on Desktop.

### Additional Information

- Status version: nightly 
- Operating System: iOS

https://github.com/user-attachments/assets/d560d94b-325c-4d0d-955b-484e33a894bf

**Comment by churik** [comment]
@chair28980 it happens when the state was changed, but was not synced to my understanding, so I don't think this is related to mobile itself - rather it is message reliability issue
Next time if you see this, please, enable logs first by Advanced>Log level> Debug and attach them here, thanks!

**Comment by churik** [comment]
I suppose can be closed in favour of https://github.com/status-im/status-mobile/issues/21438 and other messsage reliability issues, reopen if it will be possible to get logs, as without them it is not possible to identify and debug the issue
