### ISSUE TITLE
Onboarding - No text formatting in Terms of Use & Privacy Policy

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21185]
# Design Feedback 2.30

## [Onboarding] Text formatting is missing
When opening the **Terms of Use** and **Privacy Policy** links in the Onboarding landing page the text formatting is missing, leading to no visual hierarchy in the drawer.

Figma frame of the review[ here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj/Release-Reviews?node-id=2249-7147&t=FirZdcl9rTe4w2kZ-1)

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-06 alle 09 39 45" src="https://github.com/user-attachments/assets/9743ab18-8c34-4963-afbc-1d53111fc4f2">

#### Actual behavior

<img width="190" alt="Screenshot 2024-09-06 alle 09 41 27" src="https://github.com/user-attachments/assets/dc4a1c9c-8ea4-4414-93f1-c42937ff0245">

### Reproduction

1. Go to the first step of the Onboarding flow
2. Tap on the **Terms of Use** and **Privacy Policy** links

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

**Comment by ilmotta** [comment]
I'm closing this issue as not planned and tagging it as a feature because of the markdown support.
