### ISSUE TITLE
Onboarding - Create profile screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21189]
# Design Feedback 2.30

## [Onboarding] Create profile screen issues

- **Copy** [[1](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#934540407)] isn't updated from _Accent colour_ to just _Colour_ 
-------------------------------------
### Android only
- **Selection stroke** [[2](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#937944767)] is missing from the selected colour

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-06 alle 10 56 49" src="https://github.com/user-attachments/assets/d6cedbc6-f7d0-4606-becb-4a2e8c0ec1a2">

#### Actual behavior

<img width="175" alt="Screenshot 2024-09-06 alle 10 57 19" src="https://github.com/user-attachments/assets/3c109e19-d8d0-4799-9ec5-e8daf7822e99">

### Reproduction

1. Create a profile
2. Select a colour

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, Realme 10

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
I'm closing this issue because in the new simplified onboarding for milestone 2.32 the user won't be able to pick a customization color problem https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15097-57508&node-type=frame&t=fV27maAYcPlrz1gn-0
