### ISSUE TITLE
Discover pixel perfect: Status widget

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2119]
### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: Status snippet. This snippet appears on the following screens:

- Discover main screen
- Popular hashtags
- Recent hashtags 
- Search by hashtag

## Expected behavior:

Android: 
![good-android](https://user-images.githubusercontent.com/711764/31496296-2214fe4a-af5b-11e7-8ec9-5329b23788e7.png)

IOS:
![good-ios](https://user-images.githubusercontent.com/711764/31496311-2a8c76e8-af5b-11e7-8ecc-aad985b598e5.png)

## Actual behavior:

Android:
![actual-android](https://user-images.githubusercontent.com/711764/31496514-fdde3f18-af5b-11e7-8d98-1a7d149b0190.png)

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

## Nice Have
- [ ] Chat button style is wrong
- [ ] Specifically colors are wrong (purple)
- [x] Author icon is not centered with respect to his name (ios)

**Comment by oskarth** [comment]
@goranjovic I believe I fixed "Author icon is not centered with respect to his name (ios)"

**Comment by goranjovic** [comment]
Android:

![screenshot_2017-10-16-13-21-18](https://user-images.githubusercontent.com/711764/31609854-15034798-b276-11e7-834d-84395d154e2f.png)
![screenshot_2017-10-16-13-21-29](https://user-images.githubusercontent.com/711764/31609855-15223d6a-b276-11e7-8a48-5cd6612141ab.png)

ios:

![simulator screen shot oct 16 2017 1 25 33 pm](https://user-images.githubusercontent.com/711764/31609856-154070fa-b276-11e7-89d1-650c9c35be98.png)

**Comment by oskarth** [comment]
@goranjovic This was autoclosed because it had words "Fix XXX" in PR. Please write "Addresses XXX" or something if QA should check it.

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
