### ISSUE TITLE
Unable to pair devices in iOS

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21199]
# Bug Report

## Problem 

- [ ] User can't scan QR code to pair devices despite granting Local Network access in the iOS settings.
- [ ] Pressing on the button Enable network access from within Status does nothing.
- [ ] Pasting a sync QR code fails immediately, showing the `Try again` screen.

Reported by @Francesca-G and @ilmotta separately

**Probable root cause**: it appears that the local network detection in the app is not working and because of that, pairing doesn't work.

### Expected behavior

If the user allowed network access in the iOS settings for Status, the user should be able to scan a QR code to pair.

### Actual behavior

In screen `Scan Sync Code`, tab `Scan QR code`, an iOS user who has already allowed local network access still sees the button `Enable network access`, forcing the user to manually enter the sync code. But after pasting the sync code the user is still unable to pair.

<img src="https://github.com/user-attachments/assets/f0664fa4-5aaf-45d7-8d40-97ed1c129aa0" width="290" />

### Reproduction

1. Create a new account on device A using Desktop 2.30.0
2. On mobile device B, choose "Add an existing profile".
3. On device A, generate a new sync QR code.
4. On Device B, try to scan or paste the sync code.

**Notes**

- Both devices are on the same wifi network, firewall is disabled, VPN is disabled.

### Additional Information

- Status Mobile version: 2.30.0 (public release)
- Status Desktop version: 2.30.0
- Operating System: iOS, (didn't check Android)
- [logs.zip](https://github.com/user-attachments/files/16908866/logs.zip)

**Comment by Parveshdhull** [comment]
hi @ilmotta, thank you for creating this issue.

Are you only facing this issue in ios while pairing with desktop or also android? I tried pairing both ways with android<-> ios in https://github.com/status-im/status-mobile/pull/21090, and its working as expected.

> Pressing on the button Enable network access from within Status does nothing.

For me it took few seconds but pressing Enable network access button worked.

**Comment by churik** [comment]
it was checked several times on release as well, and for some people is working, for some - not

https://github.com/status-im/status-mobile/issues/20525 is the most painful issue about sync. Also is it expcted that it should work in airplane mode like on this screen? I doubt about that and we didn't consider this scenario

**Comment by ilmotta** [comment]
Thank you for investigating @Parveshdhull 😍 

@Parveshdhull @churik, the problem appears to be related to our faulty detection of the local network access and not the actual pairing mechanism. Francesca and I had given local network access in iOS settings, but the app still shows the "Enable network access" button, and pasting the sync code doesn't work. This means it's unrelated to which device we tried to pair with. Pressing on the button to enable local network did nothing.

> Also is it expected that it should work in airplane mode like on this screen?

My phones are almost always in airplane mode @churik, but wifi access was enabled. Since I'm trying to pair devices on the same local network, only wifi is needed. The video below shows the button "Enable network access" working (in airplane mode). Sync worked now for mysterious reasons, but kind of matches with what Francesca told me that eventually after she tried restarting and what not a few times, eventually it worked.

https://github.com/user-attachments/assets/11b19d81-7627-45b2-86fd-f5e54df9cb88

**Comment by ilmotta** [comment]
I'm closing the issue and we can keep watching for this problem.

There are two problems:

- "Enable network access" button doesn't work sometimes.
- Local network access detection is not working because the setting is already enabled in the iOS settings for the Status app and we still show the button to enable.

**Comment by nileshsamin** [comment]
I'm having the same issue.  I have "Local Network" enable on my iphone for Status.  I have Private Relay and VPNs disabled on my Iphone.  I have Norton disabled on my Windows PC.  Both devices are connected to my local wifi network. 

I keep getting "Oops, something went wrong ... Make sure both devices are powered on and connected to the internet ... Try Again" when I scan the QR code displayed on my Windows.

Any ideas on what I can do sync my account to my Iphone?  Thanks

**Comment by ilmotta** [comment]
Hi @nileshsamin,

If pairing is not working and you are sure both devices are on the same network, no VPN and no firewall blocking random ports, please, try to restart the desktop app after making network changes in the system. Restarting the desktop app did the trick for me more than once on GNU/Linux. Additionally, make sure you are using the latest versions of Status, that is, 2.30 on both devices.

If that doesn't work, our last option is to check debug logs, but you will need to attempt to pair devices while being logged in. Logs are disabled by default in release builds. You can enable and share them with us by doing the following steps:

1. If you don't have any profile on the mobile device, restore from the seed phrase first.
2. While logged in, open `Settings` > `Advanced` > `Log level` and choose `DEBUG`. You will be automatically logged out.
3. Login again with the same profile.
4. Go to `Settings` > `Syncing` > `Paired devices`, press on the plus icon and follow the instructions to read the pairing QR code from the desktop app.
5. After trying to pair and seeing the screen containing the "Try again" button, shake the device and choose `Share logs`. You should now be able to share a zip file with us containing 3 files with logs or choose the option `Report a bug` and send the logs via email if you are worried about sharing logs publicly (although there shouldn't be anything to be concerned about).

For more information about pairing devices: https://status.app/help/profile/sync-your-profile-across-devices.

Thank you for the patience :)

**Comment by nileshsamin** [comment]
Thank Icaro,

 

Restarting the desktop app worked.

 

Nilesh

**Comment by ilmotta** [comment]
@Parveshdhull, even with the issue closed, I would like to know if we should create a separate issue for the following problem. What are your thoughts?

In iOS, if the user already enabled local network access in the OS settings, we still show the user the button "Enable network access". Not a deal breaker, but this is a bug from the user's perspective. Do you know if there's any technical limitation causing this behavior?

It appears that, in iOS, the preflight check starts as false and is only set to true if the user presses the button "Enable network access", even if the setting is enabled in the OS.

https://github.com/status-im/status-mobile/blob/fa4ea0640d408397009f505b7b8eba7e4bc3ee66/src/status_im/contexts/syncing/scan_sync_code/view.cljs#L195-L201

----

About the button not having any effect after being pressed, I don't know how Francesca and I reached this bug, but it happened many times, but we can ignore if others can't replicate.

**Comment by Parveshdhull** [comment]
@ilmotta as per `LocalPairingPreflightOutboundCheck` function [comment](https://github.com/status-im/status-go/blob/develop/mobile/status.go#L1113)  and Stackoverflow [answer](https://stackoverflow.com/a/64242745) it seems we don't know in advance if setting is enabled. We have to trigger an outbound request for showing the Allow Network access popup/Or checking if already allowed.

 > I would like to know if we should create a separate issue for the following problem.

I think we can create few issues, as this functionality still needs some improvement.
- [ ] We should also not allow pasting code as same as QR scan until we know if permission is allowed.
- [ ] Also, I think we need to figure out why it doesn't work sometimes. Probably something wrong with the [CheckOutbound](https://github.com/status-im/status-go/blob/e3dd2b2377142100c16db2489c64b0884d5f5670/server/pairing/preflight/preflight.go#L129) function which either gets stuck or fails silently, causing the Enable Network access button not to be hidden (in callback). So I think we also need to show some error(or fix it), for those cases.

**Comment by Parveshdhull** [comment]
Also,
- [ ] If this check is slow we should also show a progress bar.

**Comment by ilmotta** [comment]
Super, thanks for the quick investigation @Parveshdhull. I will create both issues then.

> We should also not allow pasting code as same as QR scan until we know if permission is allowed.

👍🏼 This improvement would have helped significantly because the user would have reported a different bug saying something like "I can't pair because the camera to scan doesn't show up and the input field is disabled". This would have pointed us directly in the right path instead of questioning if the actual pairing wasn't working.

**Comment by ilmotta** [comment]
> * [ ]  If this check is slow we should also show a progress bar.

Good idea. Disabling the button while the check is in-flight could solve the problem too. Do you think just disabling further presses would be sufficient? Edit: @Parveshdhull

**Comment by Parveshdhull** [comment]
Hi @ilmotta, Currently we don't know what is wrong with `LocalPairingPreflightOutboundCheck`. If it is fast but just failing silently then we can just disable the button and show the end result (error/or success). But if it is just slow then a progress bar will help to keep the user engaged.

Btw, I just tried downloading a fresh build from the App Store to check if it was slow, but I also got stuck on the button not working.


https://github.com/user-attachments/assets/c5d6fb45-fea7-4ea4-890a-5f98cf2005f7

**Comment by Parveshdhull** [comment]
> Do you think just disabling further presses would be sufficient?

Most probably it is just failing silently, and disabling button will be enough

**Comment by Parveshdhull** [comment]
> In iOS, if the user already enabled local network access in the OS settings, we still show the user the button "Enable network access".

Maybe we can rename button to "Enable or Check Network access" or just "Check Network access" and show popup if needed. wdyt? @ilmotta

**Comment by ilmotta** [comment]
> Btw, I just tried downloading a fresh build from the App Store to check if it was slow, but I also got stuck on the button not working.

Thanks, you being the third person confirms more strongly the problem exists.

> Maybe we can rename button to "Enable or Check Network access" or just "Check Network access" and show popup if needed. wdyt?

I sincerely don't know what's the best solution. I slightly prefer just "Check local network access" if we can't reliably detect if local network access is enabled. I'm guessing the UX was defined that way because it was assumed we would be able to reliably detect the iOS setting, but we can't as you researched.

Perhaps as you said, the first thing we should do is find out why exactly the button sometimes doesn't work.

I will open the issue today with the insights from our discussion. Thanks again!
