### ISSUE TITLE
Onboarding - Create profile password issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21191]
# Design Feedback 2.30

## [Onboarding] Create profile password issues

- **Icon** [[1](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#934543711)] in the info message has a lower opacity than design
- **Checkbox colour** [[2](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#934542400)] is incorrect, it should be white

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-06 alle 13 13 36" src="https://github.com/user-attachments/assets/f123cf7b-0108-46d6-a772-aeffff8d2ccb">

#### Actual behavior

<img width="190" alt="Screenshot 2024-09-06 alle 13 14 13" src="https://github.com/user-attachments/assets/71874b67-0b01-487c-823d-5c1ad77cd32c">

### Reproduction

1. Create an account
2. Follow the flow until the Create password screen

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

**Comment by seanstrom** [comment]
Based on a discussion in discord about the checkbox colour for the Create Password and Change Password forms, it seems like we can now use the user's profile colour (customization-color) for the disclaimer checkbox inside the onboarding designs.

I've created a PR #21544 to ensure both the Change Password and Create Password screens use the correct checkbox colour and the correct icons for the password hints.

For context here's some links related to the discussion:
  * Here's the original question in discord about the checkbox colour: https://discord.com/channels/1210237582470807632/1270778024005996657/1301341694188458024
  * And a response towards the question about which colour to use for the checkbox: https://discord.com/channels/1210237582470807632/1270778024005996657/1301493120017629195
