### ISSUE TITLE
Update application page metadata for F-Droid

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21205]
# Problem

The Status' about page in F-Droid https://f-droid.org/en/packages/im.status.ethereum/ should match other app stores. ~We should try to merge the updates in `status-mobile` approximately at the same time as the merge request in Gitlab is merged~ https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15445 In future issues updating F-Droid we must update the repo assets before merging the merge request.

## Implementation

According to the official docs https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/, we merely need to update assets and text files in our own repo, at `fastlane/metadata/android`.

> Metadata from the repository is copied to the F-Droid repo automatically (thus no merge requests are needed)

> F-Droid will only use metadata files from the latest release. This means that fdroidserver will check out the latest version it knows and scan the repository at the state of that version for metadata files.

## Localization

Only use the languages defined in https://www.notion.so/Translations-ccc6b1532c0441e1821d6202dacee349. Delete language directories we are not supporting in `fastlane/metadata/android/`.

**Product description**: https://www.notion.so/Translations-ccc6b1532c0441e1821d6202dacee349
**Product title**: `Status`
**Product subtitle**: `Crypto Wallet & Private Messenger` (ping @ilmotta for the translations)
**Assets**: https://www.figma.com/design/skL9NPo713hUNE3UkBKDML/Assets?node-id=3020-12165&node-type=CANVAS&t=faAuY1S7IFw6HSUs-0

## Resources

- https://monitor.f-droid.org/builds/needsupdate
- https://monitor.f-droid.org/builds

**Comment by Fhiss** [comment]
Congratulations on the release of Status Mobile 2.30! Thank you very much for your work and efforts. I would appreciate it if you could update the app in F-Droid as soon as possible.
