### ISSUE TITLE
Placeholder text in the token gated communities info drawer

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21211]
# Design Feedback 2.30

## Placeholder text in the token gated communities info drawer
When tapping the info button in a token gated community a drawer with placeholder text appears

Figma design for context [here](https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?m=auto&node-id=8091-547073&t=UKLpBGZrIEzt5odb-1)

<img width="300" alt="Screenshot 2024-09-09 alle 08 56 49" src="https://github.com/user-attachments/assets/840881c2-b832-4a8f-9472-4d4ca0b3bbef">

>
The correct copy to replace the placeholder text will be provided by @Fabiomorais87 🙏

### Reproduction

1. Open a token gated community
2. Tap on the info button in the _Community token gating_ component

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS

**Comment by jorge-campo** [comment]
Text to add, @Francesca-G , @ulisesmac 

Title: `Token-gated communities`
Text:

```
If you want to join a token-gated community, you need to meet the token requirements set by the community Owner.

The Status app automatically checks if you meet the community requirements. If you meet the requirements, the option to join the community is available.
```

cc/ @Fabiomorais87
