### ISSUE TITLE
Bottom Nav icons issues that compromise UX

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21220]
# Design Feedback 2.30

## Bottom Nav icons issues

- **Icons order** should be 1. Wallet - 2. Messages - 3. Communities 
**Communities and Messages are still in beta and we're currently focusing on the Wallet** ➡️ it makes sense to not have them as the 2 first features when somebody opens the app, wallet should be

Figma design review [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2296-16569#931781425)

#### Expected behavior

<img width="300" alt="Screenshot 2024-09-09 alle 11 30 56" src="https://github.com/user-attachments/assets/f7718659-10d3-4e7a-ae08-b70f60636eea">

#### Actual behavior

<img width="300" alt="Screenshot 2024-09-09 alle 10 20 28" src="https://github.com/user-attachments/assets/ed5d8df6-cab9-497a-9160-f57a53143eea">

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

**Comment by Parveshdhull** [comment]
Hi @Francesca-G, thank you for creating this issue.
Small question: Now that we've changed the order of the bottom tabs, should we direct users to the Wallet tab instead of the Communities tab when a new account is created?

**Comment by Parveshdhull** [comment]
> should we direct users to the Wallet tab instead 

I believe this topic was discussed before, and there was an associated issue, but I can't seem to locate it. I can address this in the current [PR](https://github.com/status-im/status-mobile/pull/21240). @shivekkhurana @smohamedjavid, do you know if there is a related issue I can link?

**Comment by Francesca-G** [comment]
> Hi @Francesca-G, thank you for creating this issue. Small question: Now that we've changed the order of the bottom tabs, should we direct users to the Wallet tab instead of the Communities tab when a new account is created?

as far as I know, yes. The landing will be directly on Wallet 👍

**Comment by smohamedjavid** [comment]
> do you know if there is a related issue I can link?

We don't have a GH issue for that yet 🙏

**Comment by Parveshdhull** [comment]
> > do you know if there is a related issue I can link?
> 
> We don't have a GH issue for that yet 🙏

Thank you for confirming. Changed default tab to wallet-stack in https://github.com/status-im/status-mobile/pull/21240
