### ISSUE TITLE
Wallet - Bridge screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21224]
# Design Feedback 2.30

## [Wallet] Bridge screen issues

- **Currency** [[1](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2224-52505#938001507)] should be set to € by default
- **Icon in the button** [[2](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2224-52505#936326581)] shouldn't be there
- **Button colour** [[3](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2224-52505#936326581)] should be the Wallet account colour

------------------------------
### Android only

- **Currency** [[4](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2224-52505#937861419)] in the input field is misaligned 

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-09 alle 12 51 36" src="https://github.com/user-attachments/assets/5c5c7f6a-fce8-4ae6-8947-c9f58ac8bfa0">

#### Actual behavior

<img width="190" alt="Screenshot 2024-09-09 alle 12 52 00" src="https://github.com/user-attachments/assets/f4e01b50-5d2c-4427-b963-50c969a406b8">

### Reproduction

1. Open Wallet
2. Tap Bridge

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, Realme 10

**Comment by clauxx** [comment]
@shivekkhurana @xAlisher should EUR be the default currency for both desktop and mobile, since this change has to be done on status-go?
