### ISSUE TITLE
Simpler and improved design for empty chats and channels

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21227]
# Design Feedback 2.30

## Simpler and improved design for empty chats and channels
The empty chat screen (1:1, group, channel) was redesigned to simplify the implementation process and user experience.

Review on Figma [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2227-54819#933276211)

#### New design

| 1:1 chat  | Group chat | Channel |
| ------------- | ------------- | ------------- |
| <img width="175" alt="Screenshot 2024-09-09 alle 13 52 21" src="https://github.com/user-attachments/assets/0e8e11a6-c9e2-497b-a5c5-f814feefe74d">   | <img width="175" alt="Screenshot 2024-09-09 alle 13 52 53" src="https://github.com/user-attachments/assets/8ca696ab-5fc3-475a-8dc5-3ea32cee8fb3">  | <img width="175" alt="Screenshot 2024-09-09 alle 13 53 16" src="https://github.com/user-attachments/assets/4005a196-ab30-419a-8585-6ba0d4fddb15"> |
| [Figma](https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=12397-64254&t=O8q6qwKgkmKzTQNx-1) | [Figma](https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=12397-143299&t=O8q6qwKgkmKzTQNx-1) | [Figma](https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?m=auto&node-id=22005-90999&t=IoWmDC7lj1yP3Url-1) |

#### Actual behavior

<img width="190" alt="Screenshot 2024-09-09 alle 13 56 23" src="https://github.com/user-attachments/assets/ff3a9e36-5911-4ec4-bb3d-d3fc3749e468">

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, Realme 10

**Comment by ilmotta** [comment]
Linking with https://github.com/status-im/status-mobile/issues/20680. Both can be closed together.

**Comment by Parveshdhull** [comment]
Maybe we address this issue and #20680, once https://github.com/status-im/status-mobile/pull/20125 is merged to avoid conflict? cc @flexsurfer

**Comment by ulisesmac** [comment]
@Parveshdhull Sounds good to me
