### ISSUE TITLE
Lack of contrast between Chats and Communities with new messages compromises UX

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21231]
# Design Feedback 2.30

## Lack of contrast between Chats and Communities with new messages compromises UX
The colour difference between chats/communities without new messages and chats/communities with notifications is not being implemented correctly. 

Figma review [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2227-55758#931801674)

We received [feedback](https://status.app/cc/G8IAAOT314Z6YqSHpFOJaCNpsn9miJfMOol1QiNGdHLgcPxOdvtaAJbmAeYpC000gcx-F37xQoalBs6t9P_9-kIn251IA4YfYo9CZnZBl-u5sZ47JkhMcN5fT7oJhqnP5K-BezYN0E_Pw2UP-j486xWpEsxogA4HCloRxTXPFExfrQvbPFGwap78XajmJ9XJdrm-0J-IWDJR5bmeiExGMUVEyiziSYFlTBIpikCyhmrIEuJ4CYk=#zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9) complaining about how hard it is to see the notification dot next to chats with new messages ➡️ problem is the whole chat name should be a different colour, making it easier for the user, as per design

#### Expected behavior

<img width="300" alt="Screenshot 2024-09-09 alle 15 27 08" src="https://github.com/user-attachments/assets/9c2c682c-81de-4cdc-af28-7fab16b1f72c">

##### [Light mode]
- if there's no mention or notification the community name should be grey (Neutral/Solid/50)
- notification or mention ➡️ community/chat is black

>
>
<img width="300" alt="Screenshot 2024-09-09 alle 15 29 03" src="https://github.com/user-attachments/assets/c5ccb256-4efe-42ca-b7eb-2ab91893b2d7">

##### [Dark mode]
- if there's no mention or notification the community name should be grey (Neutral/Solid/40)
- notification or mention ➡️ community/chat is white

--------------------
#### Actual behavior

<img width="300" alt="Screenshot 2024-09-09 alle 15 30 41" src="https://github.com/user-attachments/assets/f025958f-c85e-4c63-8596-9d94436a1038">
<img width="300" alt="Screenshot 2024-09-09 alle 15 31 01" src="https://github.com/user-attachments/assets/cf17b708-4550-45c8-b7da-cb34e83b5d7a">

>
All the same colour with just the dot, making it hard for the user to see which chats/communities have new messages.

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, Realme 10

**Comment by Parveshdhull** [comment]
> problem is the whole chat name should be a different colour,

@Francesca-G, thank you for creating this issue. Just to confirm, are you referring to the community name here? According to the messages [design](https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1424-342512&node-type=frame&t=Li22cEJiz2xeZimz-0), the name remains the same, with only the color of the message changing.

**Comment by Francesca-G** [comment]
> @Francesca-G, thank you for creating this issue. Just to confirm, are you referring to the community name here? 

Yes, I'm referring to the Community name and as you said, for the messages only the color of the message will be changing 👍
