### ISSUE TITLE
Normalize cryptocompare API usage

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2123]
### User Story

As a developer, I want to use cryptocompare API as expected.

### Description

Make sure we follow cryptocompare API restrictions:

* proper advertising: `add extraParams=Status.im at the end of the query strings`
* make sure per IP (per app) limits are respected ([per second](https://min-api.cryptocompare.com/stats/rate/second/limit) and [per hour](https://min-api.cryptocompare.com/stats/rate/hour/limit))

Limits are pretty high compared to our usage so it should be fine.

*Type*: Feature

**Comment by sla-shi** [comment]
Can we detect high usage and display some message to the user?

**Comment by jeluard** [comment]
We could now I don't think it's worth it given the very high limit compared to our usage: `50` prices call per second or `15000` per hour for each running application.
