### ISSUE TITLE
'Undefined not a function' error is constantly shown after transaction confirmation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21249]
Follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Go to the routes generation page
2. Build the route
3. Go to a transaction confirmation page
4. Go back to the wallet main page or confirm the transaction

### Actual result:
'Undefined not a function' error is constantly shown

https://github.com/user-attachments/assets/2fd26a54-8f4e-405f-8c78-9ce4d3079fb9

### Expected result:
no errors are shown

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16945706/Status-debug-logs.zip)

**Comment by shivekkhurana** [comment]
Might get fixed by #21281
