### ISSUE TITLE
Wrong UI is shown after changing the token or account on the routes generation page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21254]
follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Go to routes generation page
2. Build the route
3. Tap the asset to open asset list
4. Change the asset or account via account switcher

### Actual result:
The previous route is still shown

https://github.com/user-attachments/assets/d2f942eb-58f4-4c6f-b41c-9b9ff2bdb9ca

### Expected result:
The previous route is not shown when asset is changed
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-177511&node-type=frame&t=oUNwiDs8Zn9W1JsO-0

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by smohamedjavid** [comment]
@alwx - if you haven't started, Please ignore this issue 🙏 . I have fixed it here: #21306

**Comment by smohamedjavid** [comment]
Re-opening this issue as this will be closed upon merging #21306. I have added this issue in the PR as well.
