### ISSUE TITLE
The сonfirmation keyboard auto-closes while entering the password

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21250]
Follow up for https://github.com/status-im/status-mobile/pull/21235

Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Navigate to the transaction confirmation page.
2. Attempt to enter the password.

### Actual Result:
The confirmation keyboard constantly auto-closes, preventing the user from entering the password properly.

Pixel 7a, Android 13

https://github.com/user-attachments/assets/450a660b-9cec-4d32-92d7-02dccdb7c653

iPhone 11 Pro Max, IOS 17

https://github.com/user-attachments/assets/53b48b90-82fd-4948-a97b-cac95b5012fb

### Expected Result:
The keyboard should remain open, allowing the user to enter the password without interruptions

### Logs:
[logs (6).zip](https://github.com/user-attachments/files/16947601/logs.6.zip)

**Comment by shivekkhurana** [comment]
Might get fixed by #21281
