### ISSUE TITLE
Lost the syncing state in fallback recovery, when first enter the seed phrase for the wrong account 

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21258]
# Bug Report

## Problem 
Follow up: #21090 
In seed phrase fallback recovery, if you first enter the seed phrase for the wrong account and press 'Continue,' then go back and enter the seed phrase for the correct account, you will lose the syncing state.

### Reproduction

1. Initiate the fallback flow.
2. Enter the correct seed phrase for syncing two devices.
3. Click 'Continue' (expected to open the screen for creating a password).
4. Return to the previous screen.
5. Enter the correct seed phrase, but from a different status profile not used on this device.
6. Click 'Continue' (expected to open the screen for creating a new account).
7. Return to the previous screen.
8. Enter the correct seed phrase for syncing two devices.
9. Click 'Continue'.

#### Actual result: 
The screen for creating a new account is opened (this happens every time if the user triggers account creation in the fallback flow).

https://github.com/user-attachments/assets/2ece11ad-da89-4a3c-8a4a-c6a627dc239b

#### Expected result: 
The screen for creating a password should be opened.

### Additional Information

- Status version: PR build #21090 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Original report: https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345966991
