### ISSUE TITLE
Discover: Dapp selection

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2125]
For new Discover we need a list of dapps we want to showcase under all dapps. Each dapp needs to fulfill some requirements (incomplete list):

- Name
- DApps icons in PNG format, at least 240x240px
- Description

@jarradh is working on compiling a list.

## Nice Have
Acceptance criteria:

- [ ] Define requirements for DApps
- [ ] Selection of Dapps done
- [ ] Meeting all defined requirements
- [ ] Selected dapps have a brief description
- [ ] Hardcoded in app and visible

cc @goranjovic

**Comment by annadanchenko** [comment]
Discover feature is removed
