### ISSUE TITLE
"Native token not found" error message randomly occurs on the routes generation page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21252]
Follow up for https://github.com/status-im/status-mobile/pull/21235

Unfortunately, this issue doesn't occur consistently, and there are no exact steps to reproduce it. However, it seems to happen after attempting to find routes upon entering valid data into the input field. Hopefully, the logs will help.

### Steps:
1. Enter valid data into the routes generation page to build the routes

### Actual result:
"Native token not found" error message is shown
![image](https://github.com/user-attachments/assets/727291b5-4e95-4458-a0a4-374ad6eda9f2)

### Expected result:
No errors are shown, routes are build

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs (2).zip](https://github.com/user-attachments/files/16959963/Status-debug-logs.2.zip)

**Comment by VolodLytvynenko** [comment]
still valid. Not related to new rpc from https://github.com/status-im/status-mobile/pull/21378

**Comment by churik** [comment]
postponing as there are no exact steps and the issue is not so often, it might go away with new send flow, as the process of finding routes will change. 

@pavloburykh  might know more.

So far postponing it to the next release

**Comment by pavloburykh** [comment]
> @pavloburykh might know more.

I think it might be related to the logic of checking available routes and throwing errors then specific route not found. It is described here https://github.com/status-im/status-mobile/issues/21292#issuecomment-2363275012

Though, I am not sure in which case do we get `Native token not found`. Maybe @saledjenic can check issue [description](https://github.com/status-im/status-mobile/issues/21252#issue-2519754636) and attached logs and explain the logic, why user receives this error.

**Comment by saledjenic** [comment]
@pavloburykh thanks for reporting this and mentioning me here. At first, reading this conversation and the description of this issue I thought this was impossible to get an error that the native token for the chain is not found, then checked the code once again thoroughly and figured out that this issue may happen only on the fast chains (those that generates new block very fast, like optimism and arbitrum).

This PR fixes this issue:
https://github.com/status-im/status-go/pull/5931
