### ISSUE TITLE
On the recovered device - The syncing screen only shows paired label after the restart

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21259]
# Bug Report

**Follow up:** https://github.com/status-im/status-mobile/pull/21090

### Reproduction
1. Device A1 syncs with Device A.
**Actual result:**  
**Device A1**: immediately shows Device A in the list with the 'pairing' state, but the name of Device A is not displayed
**Device A:** in the settings, Device A1 is shown with the 'Unpair' state and with its name

3. On Device A, click the 'Pair and Sync' button in the sync popup.
**Device A1**: the name of the paired device appears in the list.
**Device A:** nothing will visually change on the list ,but pairing and syncing have occurred (if you send messages in 1-1 chats, they will appear on both devices).

**Expected results:**
In my opinion, both devices should change each other's states to "Pair" and visually display this to the user in the settings simultaneously after clicking the 'Pair and Sync' button.

Video from device A1: 

https://github.com/user-attachments/assets/ce7fd793-af8a-4e2d-aa5f-be73d91027f2

Screen from device A before and after click on button:
![photo_2024-09-12_12-40-22](https://github.com/user-attachments/assets/a524bfab-8c10-4a79-957d-802a9c26d1d7)
![photo_2024-09-12_12-40-14](https://github.com/user-attachments/assets/82452773-827f-4a3d-876c-7f5d01d0f638)

### Additional Information

- Status version: PR build #21090
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Original report: https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345801098

**Comment by Parveshdhull** [comment]
When we press 'Pair and Sync' on the old device, the client receives a signal with enabled: true. But, this signal contains the installation ID of the old device itself (the device where we pressed the button) instead of the installation ID of the new device (device where we recovered account using fallback). This is why the UI is not updating

cc @qfrank @jrainville 

https://github.com/user-attachments/assets/c9d3e572-88f7-4a46-82af-f030afdf4a77

**Comment by qfrank** [comment]
> When we press 'Pair and Sync' on the old device, the client receives a signal with enabled: true. But, this signal contains the installation ID of the old device itself (the device where we pressed the button) instead of the installation ID of the new device (device where we recovered account using fallback). This is why the UI is not updating
> 
> cc @qfrank @jrainville
> 
>  output-2024-09-23_14.41.46.mp4

I'll take a look tomorrow, thank you! @Parveshdhull
