### ISSUE TITLE
Can't enter chat and messages are auto read after following own profile link from chat/channel

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21271]
Hey @Parveshdhull! Maybe you will be interested in taking a look at this when you have a chance, as I remember you have fixed similar issues in the past. Thank you!

**Steps:** 

1. Send your own profile link in chat/channel
2. Open this link from chat/channel
3. Start receiving messages in chat/channel
4. See if you can enter chat and observe the behaviour of unread counters

**Actual result:** Can't enter chat and messages are auto read. Looks like the chat is not properly closed in this case which results in this issue. 

https://github.com/user-attachments/assets/b5f0c061-05dd-4348-821c-b22238d9e6fa

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Thank you @pavloburykh for pinging me. I think https://github.com/status-im/status-mobile/pull/21142 might fix the issue. cc @ulisesmac

**Comment by pavloburykh** [comment]
> Thank you @pavloburykh for pinging me. I think #21142 might fix the issue. cc @ulisesmac

Oh, thank you very much for clarification @Parveshdhull. I am closing this issue as a duplicate of https://github.com/status-im/status-mobile/pull/21142
