### ISSUE TITLE
Dapps disappear from connected list after relogin (IOS) 

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21275]
Reproducing on IOS only. IPhone 15, IOS 17.6.1

**Steps:**

1. Connect to any dapp
2. Open connected Dapps list and make sure new Dapp is listed there
3. Close the app and relogin
4. Open connected Dapps list
5. See if Dapp is still displayed in the list

**Actual result:** Dapp disappeared from the list

[logs (47).zip](https://github.com/user-attachments/files/17027459/logs.47.zip)

https://github.com/user-attachments/assets/f3421aa8-2c19-4645-8fdd-4949ef992f01

### Additional Information

- Status version: nightly 
- Operating System:  iOS

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh, thanks for reporting this issue, I checked the flow on latest develop changes multiple time with test dapp and also 1inch dapp. couldn't reproduce the issue, the dapp list may took time but didn't see it not load at all. 

could you please check and if still happens give me more info( device timezone, is this a recovered account or new one)? 

https://github.com/user-attachments/assets/ffc2b7d9-67fd-4f86-94a0-b7abe896cff5

**Comment by pavloburykh** [comment]
> could you please check and if still happens give me more info( device timezone, is this a recovered account or new one)?

@mohsen-ghafouri thank you for your investigation. I will test a potential fix by Cristian https://github.com/status-im/status-mobile/pull/21350

Answering your questions: 

1. I am still facing the issue, but dapps are not disappearing forever. As you have mentioned it takes some time in order dapps to be fetched. But in my case it takes more that 20 seconds (see video below). 


https://github.com/user-attachments/assets/050f3a23-c740-4054-a62e-914da585c6a4



3. My timezone is GMT +3

4. It happens both on new and recovered accounts.
