### ISSUE TITLE
Watch-only collectibles stuck in upload state and cannot read property 'h' of null error is shown on tap

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21270]
### Steps:
1. add watch only accounts `0x8d2413447ff297d30bdc475f6d5cb00254685aae`, `0x00000000219ab540356cbb839cbe05303d7705fa`, `0x8d51191dd7e371bd88ab9797b11b03da3084de6e` (enable watch only feature flag)
2. Check the collectible image
3. Tap the collectible

### Actual result:
- On iOS, watch-only collectibles are perpetually in the upload state.
![image](https://github.com/user-attachments/assets/5d246f5b-c56b-40c4-af21-590c19115b95)

- On both iOS and Android, tapping a watch-only collectible results in the error: Cannot read property 'h' of null.
![image](https://github.com/user-attachments/assets/3d6cd982-0b1a-4f35-bc0f-e318f8481bf5)

### Expected result:
Collectibles are uploaded, no errors when watch-only collectible is tapped

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/17015317/Status-debug-logs.zip)

**Comment by churik** [comment]
I'd postpone it for now, as it seems better for accounts with a less multiaccounts and watch-only is blocked because of activity refinment

**Comment by VolodLytvynenko** [comment]
> I'd postpone it for now, as it seems better for accounts with a less multiaccounts and watch-only is blocked because of activity refinment

@churik As for me, having watch-only accounts is a nice feature for help in testing. It was the only way to test displaying different collectible formats and to assess smooth scrolling and app performance without crashes, after adding watch-only accounts with huge amounts of collectibles.

**Comment by churik** [comment]
I agree that it is nice feature, but still I think it is not required for 2.31, that's why I removed it from milestone
