### ISSUE TITLE
Compress Image for 'Preparing Status for You' Screen and Create Reusable Script

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#21287]
### Summary

We need to create a reusable script for compressing the image used in the "Preparing Status for You" screen. This will include collaborating with the design team to establish agreed-upon compression parameters for future use.

Lefover from https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345829086
Image https://github.com/status-im/status-mobile/blob/develop/resources/images/ui2/preparing-status%402x.png

cc @Horupa-Olena @ilmotta

**Comment by 1234abd** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by ilmotta** [comment]
https://github.com/status-im/status-mobile/pull/20076#issuecomment-2117871369

In that comment I shared a script to compress images and I remember John used it to compress images quite nicely. In a way, that solution is proven to be good enough, so we could go with that.
