### ISSUE TITLE
Cannot input message when sending contact request

### ISSUE THREAD

**Issue by vpavlin** [status-im/status-react#21291]
# Bug Report

## Problem 
[comment]: # (A problem description)

When I try to send a contact request it requires me to put in a message, but when I tap the input field the keyboard pops up and disappears again, so I have no way to input anything there, hence I am not able to send contact requests

#### Expected behavior

The keyboard shows and stays up, so that I can input message

#### Actual behavior

Keyboard pops up and dissappears immediately

### Reproduction

1. Open app through profile QR
2. Hit Send contact request
3. Attempt to input a required message

### Additional Information

- Status version: nightly 
- Operating System: Android 14, Nothing OS 2.6

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
Nothing OS 2.6, Nothing  Phone 1 

https://github.com/user-attachments/assets/f004eba7-dc37-423a-ad63-65c368387a38

Let me know if the issue appears again
