### ISSUE TITLE
Text element doesn't show the last row

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#213]
<img width="427" alt="2016-09-01 14 06 16" src="https://cloud.githubusercontent.com/assets/2364994/18165342/66025e34-704d-11e6-9a8d-976dd7fb611f.png">

Looks like React Native issue. The first message is "long-public-key left", but the word "left" is not shown there...

**Comment by rasom** [comment]
Works fine on iOS devices.

**Comment by alwx** [comment]
Can't reproduce it on my Android device.There is a change that this bug has gone because we've updated React Native several times after its creation.

**Comment by rasom** [comment]
Thanks, will check it again today.

**Comment by rasom** [comment]
@alwx, it is still there 
![qwe](https://cloud.githubusercontent.com/assets/2364994/19863131/b6865824-9f9b-11e6-800e-3afd23959211.gif)
