### ISSUE TITLE
Increase hit area on checkboxes in the onboarding flows

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21308]
# Feature Issue

Some users have reported having difficulties pressing on the initial checkbox to accept the _Terms of Use and Privacy Policy_. This same problem exists in other checkboxes in the app, for example, the checkboxes the user has to enable before proceeding to pair devices.

**Why?** Especially during onboarding, we want to minimize frustration and number of user interactions to create a functioning profile.

For more details about the feedback, reach out to @pedro-et.

## Scope

Checkboxes in the onboarding flows.

## Acceptance Criteria

- iOS has a guideline for the hit area to be at least 44x44px https://developer.apple.com/design/human-interface-guidelines/accessibility#Buttons-and-controls and https://developer.apple.com/design/human-interface-guidelines/buttons. A similar recommendation may exist for Android.
- Verify pressing the checkboxes at different angles of the thumb and index fingers enables the checkbox with minimal misses.
- Verify the hit area of the checkbox for Terms of Use and Privacy Policy doesn't overlap the button "Create profile".

**Comment by ulisesmac** [comment]
Just adding a reference to the [Android docs](https://support.google.com/accessibility/android/answer/7101858?hl=en) about it:

> Consider making sure these elements have a width and height of at least 48dp,

**Comment by briansztamfater** [comment]
FYI, touchable area can be increased by using the `hitSlop` property: https://reactnative.dev/docs/view#hitslop
