### ISSUE TITLE
Feedback screen and popup for modal transactions

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2130]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to 
- see the `transaction send` screen after sending a transaction, and the `moved to unsigned` popup when choosing to `sign later` with the `/send` command.
- see the `transaction send` screen after sending a transaction from the `unsigned transaction` tab

### Description
*Type*: Bug

#### Expected behavior
Show the send screen/popup 

#### Actual behavior
Nothing is shown

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Use same logic as in the wallet `send`

**Comment by annadanchenko** [comment]
Tested ok in develop. Will be in 0.9.12 release
