### ISSUE TITLE
Keycard - Allow user to migrate existing Profile to the new (blank) Keycard

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21316]
# Feature Issue

## User Story

As a user, I want to be able to migrate my existing Profile key pair to my purchased and unused Keycard, so that I can use a simpler and more secure mechanism to login to Status and sign all my transactions.

## Description

The flow starts at the `Keycard` Settings (user is logged in), and the user should be able to successfully migrate their existing Profile to an unused Keycard. Flows in [Figma](https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=119-16075&node-type=frame&t=yHrO9lXoBTEPIIqh-0)

The various error conditions should all be handled gracefully in the UI. In order to release a minimum viable feature (MVF), we won't support all features in the Mobile app. Instead, we will ask the the user to use the Desktop app in such cases. For example, when a [Keycard is locked](https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=2002-110180&node-type=frame&t=yHrO9lXoBTEPIIqh-0).

## Implementation

The feature must be implemented using a feature flag, disabled in release
builds.

- [x] https://github.com/status-im/status-mobile/issues/21318
- [x] https://github.com/status-im/status-mobile/issues/21334
- [x] https://github.com/status-im/status-mobile/issues/21382
- [x] https://github.com/status-im/status-mobile/issues/21366
- [x] https://github.com/status-im/status-mobile/issues/21367
- [x] https://github.com/status-im/status-mobile/issues/21368
- [x] https://github.com/status-im/status-mobile/issues/21420
- [x] https://github.com/status-im/status-mobile/issues/21443
- [x] https://github.com/status-im/status-mobile/issues/21446
- [x] https://github.com/status-im/status-mobile/issues/21470
- [ ] - More issues will be added here

**Comment by 86doteth** [comment]
will there be any way for users with existing keycards configured on desktop to import/sync their accounts into mobile? it doesnt seem
like any of these issues will fix that problem.


> we won't support all features in the Mobile app. Instead, we will ask the the user to use the Desktop app in such cases. For example, when a [Keycard is locked](https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=2002-110180&node-type=frame&t=yHrO9lXoBTEPIIqh-0).

i hope this part doesnt mean that my case as in the screenshot wont ever be fixed. that would mean id have to choose between using a keycard account exclusively either on desktop or mobile (which is the case now for my main account 8️⃣6️⃣.eth) 😅

 ![Image](https://github.com/user-attachments/assets/7ba09f07-61c0-4ca4-bb85-04be2056c663)

**Comment by flexsurfer** [comment]
hi [86doteth](https://github.com/86doteth) , could you please share the steps how you get the sate on the screenshot, thanks

**Comment by 86doteth** [comment]
@flexsurfer 
1. move keypair onto keycard using the desktop app
2. import account into mobile by going through flow for ‘i already have status account on different device’ and getting the sync code from desktop. in my case (ios) desktop and mobile do say they recognized each other and then mobile stays in the syncing screen for a while but then briefly on that same syncing progress screen a lot of message banners suddenly fill up the screen (they appear to be community history from past few days) and then mobile app crashes. desktop then says syncing is done. 
4. reopen mobile app see login screen with proper profile pic (but just public key instead of ens name for some reason)
5. enter pin (as it does recognize its a keycard login) and scan keycard
6. then it shows the screenshot in previous message

**Comment by 86doteth** [comment]
as an aside on 2.30 and testflight i have constantly had crashes after having the app open for about 4-5 minutes while not even doing anything so it might be that the crash in step 2 is simply due to having the app open for a few minutes and its time to crash again

**Comment by ilmotta** [comment]
Hi @86doteth, thank you for always sharing very detailed steps for reproduction.

> will there be any way for users with existing keycards configured on desktop to import/sync their accounts into mobile?

The upcoming release 2.32 will _at least_ support one major flow, the one this GH issue describes. The focus will be on users who already have an **unused keycard** and are using the Mobile app v2. We understand this is not the use case you described. The 2.31 release going out soon won't solve your problem yet.

But, I do want to believe that in 2.32 we will be able to support sign-in in the mobile app via a keycard that already has a keypair in it, but we have other priorities to tackle concurrently, so we can't promise. The solution probably won't be via pairing & syncing as you tried because that is more complicated and pairing is quite unreliable.

If we resolve issue https://github.com/status-im/status-mobile/issues/21446 for release 2.32 you will be able to reuse your keycard across both desktop & mobile. 2.32 will likely be released until the EOY.

> as an aside on 2.30 and testflight i have constantly had crashes after having the app open for about 4-5 minutes while not even doing anything so it might be that the crash in step 2 is simply due to having the app open for a few minutes and its time to crash again

We noticed that many iOS users with push notifications enabled face frequent crashes (I suffer from this too). Push notifications as a whole is yet another part of the product that we will eventually tackle with a fresh spirit, but not for 2.32. If you want a bit more stability in iOS, we recommend disabling push notifications in the Settings.

**Comment by 86doteth** [comment]
> The upcoming release 2.32 will _at least_ support one major flow, the one this GH issue describes. The focus will be on users who already have an **unused keycard** and are using the Mobile app v2. We understand this is not the use case you described. The 2.31 release going out soon won't solve your problem yet.
> 
> But, I do want to believe that in 2.32 we will be able to support sign-in in the mobile app via a keycard that already has a keypair in it, but we have other priorities to tackle concurrently, so we can't promise. The solution probably won't be via pairing & syncing as you tried because that is more complicated and pairing is quite unreliable.
> 
> If we resolve issue [#21446](https://github.com/status-im/status-mobile/issues/21446) for release 2.32 you will be able to reuse your keycard across both desktop & mobile. 2.32 will likely be released until the EOY.

so i guess in any case this means i wont be able to sync my desktop keycard profile to mobile and the only way to get the profile on mobile is by importing the profile by seedphrase on mobile iiuc? and then once thats done move the keypair to keycard through mobile keycard settings? but then id have to remove the keypair already on there from desktop, will this new keycard configuration set by mobile work in desktop or will i get issues there again as a result of this? or should i just forget using keycard for the profile if i want to use my profile on both devices?

> We noticed that many iOS users with push notifications enabled face frequent crashes (I suffer from this too). Push notifications as a whole is yet another part of the product that we will eventually tackle with a fresh spirit, but not for 2.32. If you want a bit more stability in iOS, we recommend disabling push notifications in the Settings.

i experimented a bit with this in the past few days btw. before turning off push notifications it regularly crashed after about 5-10 mins. then when turning it off it crashed on average after 10-20 mins. but then when turning push notifications back on it doesnt seem to crash anymore, maybe once it did after an hour. and funnily when turning push notifications back off it also doesnt crash anymore. all of this is for the case where i just leave my phone with status mobile open without touching it the whole time. maybe there is something magical about the simple act of toggling this setting

**Comment by ilmotta** [comment]
> so i guess in any case this means i wont be able to sync my desktop keycard profile to mobile and the only way to get the profile on mobile is by importing the profile by seedphrase on mobile iiuc?

@86doteth, this week we will have further definitions about the scope of keycard for release 2.32. What we would like is for users to not have to use their seed phrase if possible and use the keycard they already set-up to login to any device.

The following sequence of steps in the desktop app allows a user to login with their keycard in multiple desktop instances without pairing devices.

1. Add an existing Status user
2. I don't have other device
3. Login with Keycard
4. Enter pin
5. Fetching data for 2 min screen
6. Login

Ideally the mobile app should support this feature as well. This I hope would help you because you would not have to factory reset your keycard between mobile & desktop apps.

Let's hope we can fit this feature in 2.32. Please, stay tuned 📻
