### ISSUE TITLE
Bottom sheet shows networks with 0 balance for ETH, DAI, or SNT during swap flow

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21329]
### Steps to Reproduce:
1. Recover a user with some balance on only one network for default tokens like ETH, DAI, or SNT.
2. Tap the swap button.
3. Go to the "Select assets to pay" page.
4. Select the current token.

### Actual Result:
The bottom sheet shows all 3 networks for selection, even if a network has a 0 balance.

![image](https://github.com/user-attachments/assets/9d19860f-69d7-4ad0-8987-449586e0452c)

### Expected Result:
- The bottom sheet should display networks only if the token is available on at least two networks.
- Networks with a 0 balance should not appear.
- If all networks have a 0 balance, the user should be navigated to the sending flow after asset selection where an L1 network should be selected  [design](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=121-118995&node-type=instance&m=dev)

**Comment by briansztamfater** [comment]
@VolodLytvynenko unfortunately, I couldn't reproduce this issue. Can you check if this is still valid?

**Comment by VolodLytvynenko** [comment]
can't reproduce it anymore. This issue was fixed in recent PR
