### ISSUE TITLE
Incorrect Select Network appears after navigation back from the changed account

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21323]
# Bug Report
Followup https://github.com/status-im/status-mobile/pull/21269
It’s better to address the current issue after or alongside Issue [#21557](https://github.com/status-im/status-mobile/issues/21557), as only once the FROM page is implemented will we be able to link the network balances drawer to the selected assets from the account chosen on the FROM page.

#### Expected behavior
The drawer with networks should display the balances of selected accounts in [FROM page list](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48511&node-type=instance&m=dev)

#### Actual behavior
- The network drawer displays the balance related to default account (Account 1)
- The network drawer with an unexpected appearance is shown if the default account does not hold the long-tapped asset, even if the secondary account does.
<img width="569" alt="Screenshot 2024-09-25 at 14 55 52" src="https://github.com/user-attachments/assets/26c8c27c-8f31-4ae9-9404-e2aee866c1a1">

### Reproduction
1. Go to wallet main page
2. Long-tap on an asset available only on both `account 1` and `account 2`
3. Tap `swap` option.

### Additional Information
Here is a [list of test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) related to the current feature

[comment]: # (Please, add logs/notes if necessary)

**Comment by VolodLytvynenko** [comment]
created more updated issues https://github.com/status-im/status-mobile/issues/21557 and https://github.com/status-im/status-mobile/issues/21323 related to network drawer and updated design
