### ISSUE TITLE
Optimism assets not fully fetched in "Popular Assets" section on swap page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21339]
### Steps to Reproduce:
1. Go to the swap page and select the Optimism network.
2. Check the "Popular Assets" section in the "Asset to Pay" or "Asset to Receive" sheets.

### Actual Result:
Only 4 tokens are shown in the "Popular Assets" section for Optimism.

https://github.com/user-attachments/assets/1a26a6c4-72b6-4c92-8584-35e459ef14bb

### Expected Result:
More popular tokens should be displayed in the "Popular Assets" section for the Optimism network, as on Desktop

https://github.com/user-attachments/assets/d7f98098-2c2f-44a6-9cc5-2cc5914c88ca

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs:
[logs.zip](https://github.com/user-attachments/files/17161776/logs.zip)

**Comment by VolodLytvynenko** [comment]
It seems that Status Go isn't returning the full list of tokens, but I checked, and it works well with the latest desktop.

**Comment by briansztamfater** [comment]
Based on my investigation, this is not a status-go issue. I pushed the fix in #20962 because the bug was affecting the implementation of that flow as well.

**Comment by VolodLytvynenko** [comment]
> Based on my investigation, this is not a status-go issue. I pushed the fix in [#20962](https://github.com/status-im/status-mobile/pull/20962) because the bug was affecting the implementation of that flow as well.

hi @briansztamfater Thank you for checking it. I thought this was related to the status go based on https://github.com/status-im/status-mobile/pull/21140#issuecomment-2378841535 after reporting this issue in [PR](https://github.com/status-im/status-mobile/pull/21140#issuecomment-2378811726)
