### ISSUE TITLE
"Something Went Wrong" Validation message blinks randomly after autorefresh or token change on Swap page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21349]
follow up for https://github.com/status-im/status-mobile/pull/21140

### Steps to Reproduce:
1. Go to the swap page.
2. Enter a valid value in the send or receive field.
3. Wait for the autorefresh or change the token in the send or receive field.

### Actual Result:
The "Something went wrong" validation message blinks randomly, even though the entered value is valid.

https://github.com/user-attachments/assets/cdef5ca1-9bb9-47e4-af35-193099ac6125

### Expected Result:
The validation message should only appear when an actual error occurs, and it should remain stable after an autorefresh or token change.

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/17190867/Status-debug-logs.zip)

**Comment by churik** [comment]
I don't think that this is a blocker for 2.31, deferred to 2.32

cc @shivekkhurana

**Comment by alwx** [comment]
That's probably fixed by the last transactions update. @VolodLytvynenko could you confirm if you've experienced it recently?

**Comment by VolodLytvynenko** [comment]
> That's probably fixed by the last transactions update. [@VolodLytvynenko](https://github.com/VolodLytvynenko) could you confirm if you've experienced it recently?

@alwx correct. Thank you for pointing out this issue
