### ISSUE TITLE
'Undefined not a function' error is shown after quick back navigation

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21354]
# Bug Report
follow up from https://github.com/status-im/status-mobile/pull/21306

**Steps:**

1. Go to the routes generation page
2. Build the route
3. Go to a transaction confirmation page
4. Go back to the wallet main page or confirm the transaction

#### Actual behavior

https://github.com/user-attachments/assets/5ede3057-7ebf-46c5-a028-626bf9a2a120

#### Expected behavior

No errors

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mariia-skrypnyk** [comment]
Hi @ulisesmac !

Had a chance to check this issue one more time on nightly build and I see no crash on iOS.
It still exist on Android.

**Comment by ulisesmac** [comment]
> Hi @ulisesmac !
> 
> Had a chance to check this issue one more time on nightly build and I see no crash on iOS.
> It still exist on Android.

Great! Thank you for the details
