### ISSUE TITLE
Chats and message history loading after login takes too much time (30-40 seconds)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21358]
**Precondition:** 

In my case user is a member of 4 communities (including Status community) and has two 1-1 chats

**Steps:** 

1. Close the app
2. Generate some unread messages in 1-1 chats and communities. In my case there were 20 unread 1-1 messages and 5 unread mentions in community. 
3. Login the app
4. See how much time is needed to fetch chats and messages

**Actual result:** in my case it takes 30-40 seconds for complete fetching of chats and chat history. I suspect the culprit of such delay is Status community which has a lot of channels and messages. 

As has been reported by @86doteth [here](https://github.com/status-im/status-mobile/issues/21120#issuecomment-2371885924) it can take even more time for messages to be fetched (more than 4 minutes). 

[Status-debug-logs - 2024-10-01T163043.807.zip](https://github.com/user-attachments/files/17210529/Status-debug-logs.-.2024-10-01T163043.807.zip)

https://github.com/user-attachments/assets/f9b09685-f84e-4df3-9eb0-146745326960

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by 86doteth** [comment]
the order magnitude difference for ios might be because it cant do any messaging stuff in the background? but still 3-4 mins does seem like a bug to me. it’s really only new messages for the two communities im in were probably talking a few dozen at most in between times of login

**Comment by ilmotta** [comment]
- Linking to possible duplicate https://github.com/status-im/status-mobile/issues/20816

**Comment by qfrank** [comment]
could you try this [PR](https://github.com/status-im/status-mobile/pull/21411) to see if it make any difference? @pavloburykh cc @churik
