### ISSUE TITLE
Routes building while bridging from L1 to L2 results in error `abi: cannot use func as type ptr as argument`

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21385]
cc @saledjenic 

**Steps:** 

1. Recover account which has some tokens on L1 (in my case Eth)
2. Try to bridge/perform transaction from L1 to L2
3. See if routes are built successfully 

**Actual result:** building route results in `abi: cannot use func as type ptr as argument` error

[logs (50).zip](https://github.com/user-attachments/files/17246021/logs.50.zip)
![photo_2024-10-03 17 52 07](https://github.com/user-attachments/assets/24d60206-f338-4d68-b1e6-5fcd17f46f6e)

https://github.com/user-attachments/assets/8fd3c127-767e-403d-9744-dae548d837f7

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by saledjenic** [comment]
@pavloburykh should be fixed here:
https://github.com/status-im/status-go/pull/5915

Please update the mobile app to point to that commit and test.
