### ISSUE TITLE
The wallet page takes too long to load, and routes are not generated

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21409]
### Steps:
1. Login to app
2. Take a look wallet page
3. Go to routes generating page or swap
4. Try to build transaction using optimism network

### Actual result:
- Wallet page loading is too long
- Routes are not built on optimism network

https://github.com/user-attachments/assets/28b79c61-311a-485c-b75d-dc174a379336

### Expected result:
- The wallet page should load quickly.
- Routes should be successfully generated when using the Optimism network.

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

### Logs:
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/17307990/Status-debug-logs.1.zip)

**Comment by saledjenic** [comment]
@VolodLytvynenko comparing `requests.log` from the logs you provided with what I see in the recorded video in the description I have some doubts. But before that, would be good to provide new clean log with only actions that are recorded which means, delete local logs, run the app, do and record the swap flow that is problematic and close the app. That way I will have logs only for that running session, cause current log has much more logged swap flows than recorded.

So getting back to some doubts:
- searching the log I couldn't find any call to `wallet_getSuggestedRoutesAsync` where `"tokenID":"ETH"` and `"toTokenID":"DAI"` for `"sendType":8`, that made me think if the mobile app requests the route properly?
- then I see that the `amountIn` should be `0.001` ETH, which is `1000000000000000` WEI, which is `0x38D7EA4C68000` and the only 2 logs that have that amount are:
  - `t=2024-10-09T11:10:06+0000 lvl=dbug msg=callPrivateRPC params="[{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"wallet_getSuggestedRoutesAsync\",\"params\":[{\"disabledFromChainIDs\":[10,42161],\"sendType\":8,\"tokenID\":\"ETH\",\"disabledToChainIDs\":[10,42161],\"amountIn\":\"0x38d7ea4c68000\",\"toTokenID\":\"SNT\",\"gasFeeMode\":1,\"fromLockedAmount\":{},\"addrFrom\":\"0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5\",\"uuid\":\"48fec58f-2802-4a9a-8137-f67c0e33edc8\",\"addrTo\":\"0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5\"}]}]" resp="{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":null}"  duration=2.993164ms` 
  - `t=2024-10-09T11:10:26+0000 lvl=dbug msg=callPrivateRPC params="[{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"wallet_getSuggestedRoutesAsync\",\"params\":[{\"disabledFromChainIDs\":[10,42161],\"sendType\":8,\"tokenID\":\"ETH\",\"disabledToChainIDs\":[10,42161],\"amountIn\":\"0x38d7ea4c68000\",\"toTokenID\":\"SNT\",\"gasFeeMode\":1,\"fromLockedAmount\":{},\"addrFrom\":\"0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5\",\"uuid\":\"2f47e1ee-7752-4fe9-901a-bd575aa9f76b\",\"addrTo\":\"0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5\"}]}]" resp="{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":null}" duration=3.893148ms`
  and you can notice that both have `toTokenID` set to `SNT`, which is not what the recording show
- then I see that you're calling `wallet_stopSuggestedRoutesAsyncCalculation` and `wallet_getSuggestedRoutesAsync` on each digit change, can we do that a bit better? We should think better when we need to call those endpoints. 
For example, when user changes "selected account" or "from token" or "to token", it's ok to do those calls, but if user is updating the amount, like you were doing in that video, we should not call those endpoints on every digit change, but do it better and notice when the update is done. 
Like, if the amount input field loses focus or there is not amount value update longer than 1000ms (maybe 500ms, maybe 1200ms, up to us to define) then we can consider that user has finished updating the amount and do the calls then. That will save our rpc calls for sure and improve app performances.

**Comment by churik** [comment]
@saledjenic 
today the routes are found, mentioned it [here](https://discord.com/channels/1210237582470807632/1270072144067563520/1293865926072205374) - issue is gone, and seems it is not related to the app.

>  that made me think if the mobile app requests the route properly?

UI:
![Image](https://github.com/user-attachments/assets/47baf99b-6914-4501-916d-d76e996c6671)
Params:
`t=2024-10-10T09:17:58+0000 lvl=dbug msg=callPrivateRPC params="[{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"wallet_getSuggestedRoutesAsync\",\"params\":[{\"disabledFromChainIDs\":[1,42161],\"sendType\":8,\"tokenID\":\"USDC\",\"disabledToChainIDs\":[1,42161],\"amountIn\":\"0xf4240\",\"toTokenID\":\"1INCH\",\"gasFeeMode\":1,\"fromLockedAmount\":{},\"addrFrom\":\"0xcf2272205cc0cf96cfbb9dd740bd681d1e86901e\",\"uuid\":\"e6973742-b24e-4963-a07e-266df2219227\",\"addrTo\":\"0xcf2272205cc0cf96cfbb9dd740bd681d1e86901e\"}]}]" resp="{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":null}" duration=1.071041ms`
, where "sendType" is 8, if it is wrong, please let us know what type where should be used, as we checked it from UI POV, and as a QAs we didn't get any specs how it should be done.

> then I see that you're calling wallet_stopSuggestedRoutesAsyncCalculation and wallet_getSuggestedRoutesAsync on each digit change, can we do that a bit better?

Good point, I'd suggest also to make some pause in between calling new route.

Though I'm not sure what exactly from this is a blocker for 2.31, may be you know better 

cc @shivekkhurana @alwx @briansztamfater

**Comment by churik** [comment]
after the desicion what should be tweaked in params, I'll close this issue and move the tasks to separate ones, thanks!

**Comment by shivekkhurana** [comment]
@churik Not a blocker, but a good issue for 2.32.

**Comment by saledjenic** [comment]
@churik send type `8` is ok, cause it refers to `Swap`, here are related costs for the send type field: https://github.com/status-im/status-go/blob/develop/services/wallet/router/sendtype/send_type.go#L19-L29

Also, the request you provided is well-formed and corresponds to the screenshot you provided.

That was not the case with the logs provided in the description and recorded video.

**Comment by churik** [comment]
ok then, I'll create a separate issue for 2.32 for optimzation this part:
> then I see that you're calling wallet_stopSuggestedRoutesAsyncCalculation and wallet_getSuggestedRoutesAsync on each digit change, can we do that a bit better? We should think better when we need to call those endpoints.
For example, when user changes "selected account" or "from token" or "to token", it's ok to do those calls, but if user is updating the amount, like you were doing in that video, we should not call those endpoints on every digit change, but do it better and notice when the update is done.

Thanks :)

**Comment by churik** [comment]
closing this one as not reproducible in the moment

**Comment by VolodLytvynenko** [comment]
The issue with long wallet loading has occurred again. Additionally, routes are not being built while this issue persists on both Desktop and Mobile. I used the build from [this PR](https://github.com/status-im/status-mobile/pull/21445) where we have a fresh status go, but the issue is also reproducible on the latest master as well

https://github.com/user-attachments/assets/81cff6a6-5def-48b5-9397-c10c746f5cb6


Mobile logs:
[logs (3).zip](https://github.com/user-attachments/files/17431556/logs.3.zip)

Desktop logs:
[geth copy 2.log](https://github.com/user-attachments/files/17431549/geth.copy.2.log)
