### ISSUE TITLE
Network selection not shown during Swap for Assets on multiple networks if current asset located on a few accounts

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21414]
### Preconditions:
1. User has `Account 1` and `Account 2`
2. On `Account 1` user has tokens on Network 1 only (note: The tokens should not be ETH, DAI or SNT)
3. On `Account 2` user has tokens on Network 2 only (note: The tokens should not be ETH, DAI or SNT)

### Steps:
1. Go to wallet main page
2. Long tap the token
3. Tap 'swap'

### Actual result:
The Network selection is not shown, user is navigated directly to swap page

https://github.com/user-attachments/assets/fad933ed-6c32-4b88-b7a8-21b8a4aba324

### Expected result:
The Network selection is shown if the tapped asset exists on a few networks
![Image](https://github.com/user-attachments/assets/a0933681-eb5a-49d8-9478-f7043cb6db68)

https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=774-39096&node-type=instance&m=dev

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 10 Oct, 2024

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Is this issue still valid?

**Comment by briansztamfater** [comment]
Not sure if this is valid, on the wallet main screen we should assume we are using the first account, and if the first account has the token in only one network, we shuold not show the network selection drawer. cc @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> Not sure if this is valid, on the wallet main screen we should assume we are using the first account, and if the first account has the token in only one network, we should not show the network selection drawer. cc [@VolodLytvynenko](https://github.com/VolodLytvynenko)

Hi @briansztamfater, understood, thank you for the clarification! Just to confirm, does this mean that [issue #21463](https://github.com/status-im/status-mobile/issues/21463) is also not valid and that the drawer should only display balances within network drawer that are related to the default account?

Additionally, based on the [message](https://discord.com/channels/1210237582470807632/1270072144067563520/1293947917635424338), it seems the swap option shouldn't appear if the user has no assets. Should this apply only if there are no assets on the default account? 
For example, if the default account has 0 Uniswap but Account 2 has 1 Uniswap, should the swap option still be visible on the main wallet page?

**Comment by briansztamfater** [comment]
@VolodLytvynenko Let's confirm with design team, but I think #21463 is not valid neither.

About the question about hiding the swap option if the main account has not balance but another account has, it is a really great question, and I don't think we have a specific flow or defined logic for that case. Maybe, when the user is in the wallet main screen, we should pre-select the account that at least has any amount of that token on any of out supported networks.

Feel free to start a discussion with the design team about this and tag me.

**Comment by VolodLytvynenko** [comment]
I suggest closing this issue and I will create an updated one. The design and logic are changed for this feature
