### ISSUE TITLE
Consistent "Intrinsic gas too low" Error on swap page after transaction approval attempt on Arbitrum network

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21423]
### Steps to Reproduce:
1. Go to the swap page and select the Arbitrum network.
2. Select any valid pair for the swap (e.g., USDC → ETH).
3. Put the app in the background for 5 minutes.
4. Return to the app.
5. Attempt to approve the transaction.
 
### Actual Result:
The error toast "status-proxy-0.error: intrinsic gas too low" is consistently shown after the approval attempt, blocking the transaction process.

https://github.com/user-attachments/assets/a87d3a46-d828-4591-8e78-719e3d5a98f1

### Expected Result:
The transaction should be approved without errors, and the swap should proceed to completion.

### Additional info:
- I've rechecked this issue using the same account and the same or higher amount, and I wasn't able to reproduce it there. However, it consistently reproduces on mobile.
- The transaction doesn’t appear on Arbiscan.

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

### OS:
iOS, Android

### Logs:
[logs (3).zip](https://github.com/user-attachments/files/17343014/logs.3.zip)

### Env:
Nightly 11 Oct, 2024

**Comment by VolodLytvynenko** [comment]
issue is not reproducible in the scope of https://github.com/status-im/status-mobile/pull/21445

**Comment by VolodLytvynenko** [comment]
the issue is still reproducible. Encountered on release 2.31
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/17586292/Status-debug-logs.1.zip)

**Comment by VolodLytvynenko** [comment]
potentially fixed by https://github.com/status-im/status-mobile/pull/21523

**Comment by VolodLytvynenko** [comment]
The issue comes back. 

https://github.com/user-attachments/assets/dac2d34a-afe3-4fea-aa09-1bb77174924f


[Status-debug-logs.zip](https://github.com/user-attachments/files/17777885/Status-debug-logs.zip)

### ENV:
Nightly 15 November, 2024

**Comment by alwx** [comment]
Might be fixed by this: https://github.com/status-im/status-mobile/pull/21541

**Comment by VolodLytvynenko** [comment]
fixed by https://github.com/status-im/status-mobile/pull/21541
