### ISSUE TITLE
🔁 Update swap final screen to show Terms of Services below the slider

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#21427]
# Feature Issue

### User Story

As a user, 
I want to know my rights, and agreements with the swap provider (Paraswap),
So that I can take informed decisions

### Description

We need to make the Paraswap ToS more explicit in the Swap Summary screen (The screen where the users moves the slider to sign and enters her password).

This updated design for the view is on Figma: https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=860-41069&t=rjgpkkg14jGvc89b-1

### Acceptance Criteria

- [ ] When the user is about to swap, we show them the link to terms of services below the slider
- [ ] The link and description should match the designs
- [ ] On clicking the link, a web view should open as a modal inside the app
- [ ] [Optional] If the pdf doesn't work inside the web view, we can redirect the user to their native phone browser
- [ ] This webview should load Paraswaps latest terms of services: https://files.paraswap.io/tos_v4.pdf

### Notes

- [ ] Use bottom sheet for WebView (@xAlisher to confirm)
- [ ] Confirm that PDF is visible on both Android and iOs devices

**Comment by smohamedjavid** [comment]
@shivekkhurana @xAlisher

The design update to place the Terms and Conditions under the slider is already done in https://github.com/status-im/status-mobile/pull/21311 by @briansztamfater. However, we open the PDF in the system browser. This issue talks about opening the PDF in the web view to preserve the UX of the Swap flow without the user having to feel cut off from the app. We can display the PDF in WebView, and I have created a new WebView screen with a page-nav component to display the close icon. There are no designs on how the web view screen should look.

| System browser | WebView |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/7544c712-1e98-4379-ac81-3c2ec2eec048" /> |  <video src="https://github.com/user-attachments/assets/7f842be4-7ea2-41fd-b57e-aa1a398dbdad" />  |

Let me know your thoughts. If it's all good, I will make a PR.
