### ISSUE TITLE
Unexpected error should be handled and feedback shown after Signing a transaction

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2142]
### Description

*Type*: Bug

*Summary*: If something goes wrong (not enough funds to cover amount +fee, network error, etc) after user provided valid password and tap on Sign Transaction we need to show the feedback about it. For example, a popup with error and stack trace or we re-use Transaction Sent screen and put their some other text instead of `Transaction is sent`. Such error handling should be on Sign Transaction screen if user
- sends funds from Wallet via Send
- sends tx from Unsigned 
- sends tx from chat

Currently (wrong behaviour): After user taps on Sign Transaction loading indicator is shown for a while and that's it. So, user stays on the same screen with same password request and does not know what happened.

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/6833063/sessions/8/?accessToken=ayids-dPjUKPoS-OQrSAPOV-iwk
- Open Status
- Open Wallet
- Send all funds you have (it's not handled now as a separate error) or as another error state: switch off wifi to get offline mode and type valid amount you have
- Type password and tap on Sign Transaction

### Additional Information
* Status version: develop
* Operating System: 
Real device iPhone 6s, iOs 10.3.1, Galaxy S6 Android 6.0.1

**Comment by flexsurfer** [comment]
added error tooltip
![image](https://user-images.githubusercontent.com/11790366/31662529-61b32c08-b347-11e7-96f7-07c7b002da26.png)

**Comment by annadanchenko** [comment]
now instead of error above the password field there is a popup with error. In addition, if something wrong happens (no connection, not enough balance) on unsigned transaction then it's deleted from the Unsigned list

**Comment by annadanchenko** [comment]
Tested ok in develop. Will be in 0.9.12 release
