### ISSUE TITLE
Add a max length verification for the password and increase the limit to 100 characters

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21433]
# Feature Issue

### User Story

As a user, I want the system to enforce a maximum password length of 100 characters during registration, login and password change flow **so that**  can crate secure passwords without exceeding the allowed limit and have consistent behavior across platforms.. 

### Description

Design for error message for desktop: https://www.figma.com/design/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023-298171&node-type=canvas&t=1Gmu9iQ8zkv57pux-0
https://www.figma.com/design/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=7860-189803&node-type=frame&t=hnWzqq4UThCTihkJ-0

### Acceptance Criteria
**Max Length Validation:** The system should validate the password length during user registration and login, ensuring it does not exceed 100 characters.
**Error Message:** If the password exceeds 100 characters, an error message should be displayed, informing the user that the maximum length has been reached.
**UI Consistency:** The max length validation should be applied consistently across all platforms (desktop and mobile apps).
**Existing Passwords:** Existing users with passwords shorter than 100 characters should not be affected by this change.

**Comment by Horupa-Olena** [comment]
@anastasiyaig Hi! This issue and https://github.com/status-im/status-desktop/issues/16239 are related. However, we’ve decided to increase the maximum password length to 100 characters. Please take note of this.

**Comment by anastasiyaig** [comment]
there is a clear statement for this in https://github.com/status-im/status-desktop/issues/16239#issuecomment-2413400374 @Horupa-Olena . Is there anything else i should look into?

**Comment by Horupa-Olena** [comment]
> there is a clear statement for this in [status-im/status-desktop#16239 (comment)](https://github.com/status-im/status-desktop/issues/16239#issuecomment-2413400374) [@Horupa-Olena](https://github.com/Horupa-Olena) . Is there anything else i should look into?

Sorry, I didn't see it. No, it's all. Thank you.

**Comment by ilmotta** [comment]
- Linking with https://github.com/status-im/status-mobile/issues/21567
