### ISSUE TITLE
[Android] Scanner not reacting to metamask QR code generated via plugin

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21444]
### Steps to Reproduce:
1. Open the app's QR scanner.
2. Attempt to scan a QR code generated from the Metamask plugin in the browser (with the format: `ethereum:0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5`. In my case it looks so:
![Image](https://github.com/user-attachments/assets/fa691f72-8dcb-42ff-a1b9-f6d250f00e03)
).
3. Observe the behavior of the scanner.

### Actual Result:
The scanner does not react  QR code generated by Metamask.

https://github.com/user-attachments/assets/a113dc8e-f634-49e2-8784-2331fe8bab71

### Expected Result:
The scanner should be able to react and decode the QR code generated by the Metamask browser as it does with other similar QR codes.

### Additional Info:
The decoded QR string looks so `ethereum:0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5`
I've generated this address by other tools, like the one on https://brunobar79.github.io/eip681-link-generator/#, and QR was scanned successfully

Example:
![Image](https://github.com/user-attachments/assets/82b47909-c9fb-4628-b088-2425b13fb1de)

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/17392765/Status-debug-logs.zip)

### Devices:
Pixel 7a, Android 13

#### Environment:
Nightly build 16 Oct 2024

**Comment by churik** [comment]
@VolodLytvynenko 
I suppose that QR is not generated by default in MM, right?

I just tried to use it with MM in Chrome, when I'm scanning QR from wallet it displays wallet address, which I consider expected - so postponing for now

**Comment by VolodLytvynenko** [comment]
Now, this issue is not reproducible to me at all. Seems it was fixed
