### ISSUE TITLE
Wallet - show warning when app is syncing to tell user that it's not possible to use Wallet

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#2144]
Show warning when app is syncing to tell user that it's not possible to use Wallet.
@denis-sharypin can you pls update the mockup with the warning icon.

Per discussion - https://status-im.slack.com/archives/G75AL6HFS/p1507910859000298 : 
- If user attempts to tap any button or pull to refresh when the app is syncing then just display the label and ignore the requested action.
- When the app us syncing display the `Syncing` warning label

![image](https://user-images.githubusercontent.com/1944596/31609555-5d88d5d0-b27d-11e7-9189-0a6a635ddaa8.png)

https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59e494f4c25c11a0a5aa5b1d

**Comment by yenda** [comment]
fixed in develop

**Comment by annadanchenko** [comment]
tested on develop build  0.9.11d270 and see no Syncing label:
- Switched from default Ropsten with Upstream RPC to Ropsten
- signed in to the app
- waited till syncing is started (opened console and see Syncing ... )
- switched to Wallet

Currently: 
- loading indicator is shown 
- no Error or Syncing labels are shown

Expected:
- Syncing label is on Wallet screen

TF session: https://app.testfairy.com/projects/4803590-status/builds/6895408/sessions/9/?accessToken=ksOuPbhYVExCOE4axMmJfybgDis

both on iOS  and Android 
Real device iPhone 6s, iOs 10.3.3
Real device Samsung Galaxy S6, android 6.0.1

**Comment by annadanchenko** [comment]
Tested in develop  0.9.11d272. will be in release 0.9.12
