### ISSUE TITLE
[Android] Long numbers in swap receive field not properly displayed

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21462]
### Steps:
1. Go to swap
2. Select some 18 decimals token in the receiving value

### Actual result:
- The number is not shown from the beginning in the receive field.

Pixel XL API 33 (Android studion)
![image](https://github.com/user-attachments/assets/fc51cef0-1b63-465c-8cc1-e2f1044a0529)

Pixel 7a, Android 13
![image](https://github.com/user-attachments/assets/6939aafa-632e-4c20-83f4-525d54a2041e)

### Additional info:

[NOTE] There's an Android bug in our current version of React Native (0.73) that prevents us to position the text input at the start of it (https://github.com/facebook/react-native/issues/44171), thus will be fixed once we update to 0.74+ where this seems to be fixed (https://github.com/reactwg/react-native-releases/issues/283)

**Comment by briansztamfater** [comment]
Currently blocked, depends on https://github.com/status-im/status-mobile/pull/21268
