### ISSUE TITLE
The network drawer shows the balance of default account instead of balance of total accounts on wallet main page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21463]
### Preconditions:
1. User has 2 or more accounts
2. User has an asset with available value on 2 or more accounts

### Steps:
1. Go to the wallet main page
2. Long tap the asset that is present within 2 or more accounts
3.  Observe the value

### Actual result:
The value shown within the network selection drawer is related to main default account

https://github.com/user-attachments/assets/a4bd5f7e-227a-45fe-a01b-56648134228c

Example:
The user has a total of 1 DAI, with 0.01 DAI in the default account and 0.99 DAI in other accounts. However, the network drawer only displays 0.01 DAI.

### Expected result:
The network selection drawer should display the total balance of the asset across all accounts, not just the default account.

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### ENV:
Nightly 18 Oct, 2024

**Comment by ajayesivan** [comment]
I will take this up.

cc: @ilmotta

**Comment by VolodLytvynenko** [comment]
I suggest closing this issue and I will create an updated one. The design and logic are changed for this feature

**Comment by VolodLytvynenko** [comment]
created more updated issues https://github.com/status-im/status-mobile/issues/21557 and https://github.com/status-im/status-mobile/issues/21323 related to network drawer and updated design
