### ISSUE TITLE
Create a uniform color palette

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2146]
### User Story

As a developer, I want to have a uniform color palette so I can quickly and accurately translate designs into real screens, without second guessing what colors to use.

As a user, I want to have a visually pleasing and consistent experience with a few deliberately chosen colors.

### Description

*Type*: Feature

*Summary*: A deliberately chosen set of colors with meaningful names that the whole app can use. A primary, secondary and teritiary palette.

#### Expected behavior
Something like this: 
![image](https://user-images.githubusercontent.com/1552237/31575192-0269dc6e-b0e1-11e7-88b4-9eaa2fff1358.png)
https://ustyle.guide/brand/colours.html

#### Actual behavior
I extracted all the colors we use from the `style.cljs` namespace. We surely have more and do things in an even more ad hoc manner in some other namespaces, but this is the closest thing we have to a global color selection right now.

![image](https://user-images.githubusercontent.com/1552237/31575185-f6685a94-b0e0-11e7-894a-0e363196d5d6.png)
https://jsfiddle.net/nvgmqobp/5/embedded/result/

#### Pieces of work

- [ ] Ensure all colors we use are defined in styles.cljs
- [ ] Reduce the ones we already have somewhat so we don't have 11 shades of grey
- [ ] Design: Make a color palette of expected colors to use with meaningful names
- [ ] Consistency: Decide on hex vs rgb and hex8 vs rgba, as well as rules for applying opacity etc

**Comment by andmironov** [comment]
WIP https://share.goabstract.com/61f72263-8edc-4223-b77d-d141c97315f4

![color pallette](https://user-images.githubusercontent.com/3115606/42090978-37584776-7bac-11e8-98a8-1c0acd654191.png)

**Comment by oskarth** [comment]
@andmironov Did something happen with this?

**Comment by andmironov** [comment]
yes cc @denis-sharypin

**Comment by denis-sharypin** [comment]
@oskarth yep it's done from the design side. We asked @flexsurfer to implement this. 
More info on Slack #design-system 
![image](https://user-images.githubusercontent.com/6559881/46155113-de852f80-c276-11e8-85aa-3dba9abff31a.png)

**Comment by oskarth** [comment]
@flexsurfer @denis-sharypin Just for posterity, what happened with this issue? OK if we aborted it, would be nice to tie this up with comment here

**Comment by flexsurfer** [comment]
Fixed here https://github.com/status-im/status-react/pull/6160
