### ISSUE TITLE
Receiver does not receive messages from sender after offline

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21499]
### Steps:
1. `User A` and `User B` are in a 1-1 chat.
2. `User B` goes offline for 1-3 minutes and then reconnects.
3. `User A` and `User B` start the conversation.

### Actual result:
`User A` does not receive messages from `User B`, but `User B` receives messages from `User A`.

https://github.com/user-attachments/assets/0449ac23-23e5-4a3a-9af3-64a8e3682ba6

### Expected result:
Both `User A` and `User B` should receive each other's messages after reconnecting.

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

### Logs:
UserA's logs [logs.zip](https://github.com/user-attachments/files/17506179/logs.zip)
UserB's logs [Status-debug-logs.zip](https://github.com/user-attachments/files/17506191/Status-debug-logs.zip)

### ENV:
Release 2.31

**Comment by churik** [comment]
can be related to https://github.com/status-im/status-mobile/issues/21172 and https://github.com/status-im/status-mobile/issues/21173 

In general when there is a status change without relogin the app picks up the state with significant delay; 
according to @VolodLytvynenko even re-login didn't help in particular case

**Comment by VolodLytvynenko** [comment]
This issue is invalid. It occurred because I manually set a different timezone and forgot to set it back. The timezone issue exists separately https://github.com/status-im/status-mobile/issues/17739
