### ISSUE TITLE
No tabs are available in the app on Graphene OS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21509]
# Bug Report

## Problem 
No tabs available on Pixel 7A, Graphene OS.

Issue is not reproducible on the same device on Android.
It was not the case for 2.30, so it is regression.

#### Expected behavior
can see tabs

#### Actual behavior
no tabs available

https://github.com/user-attachments/assets/a9d06f41-7ab4-4927-bac1-198e2ca619bb

### Reproduction

1. Install 2.31 

### Additional Information

- Status version: release 2.31 
- Operating System: **Graphene OS**
- Logcat: [logcat_no tabs.log](https://github.com/user-attachments/files/17542978/logcat_no.tabs.log)

**Comment by Parveshdhull** [comment]
Thank you @churik for creating the issue.

> It was not the case for 2.30, so it is regression.

Seems weird, I don't see any related changes 🤔 .

Just a guess but adding z-index to bottom-tabs container, might fix the issue
(UPD: Probably not, might be issue with home-stack height. Most probably height calculation is different in graphene OS)
https://github.com/status-im/status-mobile/blob/4aef76281cc7c145c038b613b7ac58709bcfd429/src/status_im/contexts/shell/jump_to/components/bottom_tabs/style.cljs#L8

**Comment by Parveshdhull** [comment]
> Just a guess but adding z-index to bottom-tabs container, might fix the issue

Sorry, I don’t have access to a Graphene OS device for testing. Can I push a PR with the changes for verification to see if it works?

**Comment by Parveshdhull** [comment]
> (UPD: Probably not, might be issue with home-stack height. Most probably height calculation is different in graphene OS)

I am just thinking out loud, if anyone has access to graphene OS, please feel free to pick the issue.

**Comment by churik** [comment]
@Parveshdhull  sure, I can help to verify that, just dm me whenever you have a PR

**Comment by churik** [comment]
@Parveshdhull you are right, it is reproducible with new account on my device in 2.30 as well - but it was not the case when I upgraded, so I'm confused.
