### ISSUE TITLE
communties dont fetch at all from anywhere on first login after import by sync code

### ISSUE THREAD

**Issue by 86doteth** [status-im/status-react#21525]
# Bug Report

## Problem 
[comment]: # (A problem description)
[EDIT: for those that remember some of my previous issues, this issue is not on my main account 86.eth, but on my test account 86doteth-test that doesnt have keycard nor ens and never was an owner/admin of a community]

after reinstalling 2.30 and importing my account through sync code im unable to fetch any communities:

- not from a community link sent through dm: it will stay on the fetching screen for a minute or so before telling that it failed to fetch
- not from the discover page: only get endless loading screens
- not from any community link outside the app: it will navigate to the app but then just display an ‘open in ios’ browser popup button which doesnt do anything

also when trying the links on https://curate.status.app/directory they give what seem to me malformed links like status-app://c (see attached video) but that should probably be an issue for the web team i think

#### Expected behavior
communities get fetched whether in discover section, links in the app or links outside the app
EDIT: also this same account was already a member of status and status inu communities in my other installs so i expected these to simply be listed in my 'joined' tab, but instead the joined tab is empty

#### Actual behavior
communities dont get fetched at all

### Reproduction

1. install 2.30 on ios
2. import existing profile with sync code from desktop light client
3. after successful sync navigate to discover communities section - observe nothing gets fetched even after waiting many minutes
4. try sending community links in dms to this mobile install: observe that none of these linked communities get fetched

### Additional Information

- Status version: 2.30
 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)
### Video
https://github.com/user-attachments/assets/b3aedb1f-314c-4780-86cc-c4483bd70919

i would have liked to add logs but idk how. when shaking the device the ‘share logs’ option doesnt give any logs and idk what happens when i tap ‘submit by email with logs archive’ after tapping ‘report a bug’ so 🤷‍♂️

**Comment by 86doteth** [comment]
hmm i tried reproducing with a profile newly generated in the mobile app and that account does seem to be able fetch communities sent through dm and eventually also from the discover screen (but not from outside the app but that seems a web team issue)

so i think the only odd thing about 86doteth-test profile is the following. i originally created it on mobile months ago in the testflight. then i imported it to a few desktop instances through sync codes in the months after. then some hours ago i removed the status mobile app which removed that 86doteth-test profile from the device for the first time since creation. i then reinstalled the app and reimported the profile by sync code using one of the other desktop instances. that desktop instance was originally itself imported by sync code from another desktop instance and _that_ desktop instance was originally imported by sync code from the original mobile 86doteth-instance. so maybe there is some (broken) circularity of sync code imports that is causing this issue?

**Comment by 86doteth** [comment]
a day later i logged back into the 86doteth-test profile after being logged in with the other newly generated test profile from my previous comment. this time communities did fetch for 86doteth-test

so the way to resolve this seems to be
- logging out of the account that was imported by sync code (not just closing the app),
- perhaps log into a different account that wasnt imported by sync, 
- and then log back into the first account. 

so i changed the title of this issue accordingly. i hope the reproduction to get the bug and the reproduction to solve it gives some insight on how to fix the bug. otherwise do tell on how i can share better logs

**Comment by churik** [comment]
actually that sounds like an issue that we already fixed in 2.31, see https://github.com/status-im/status-mobile/issues/21303 

I hope that 2.31 bring you a better experience

**Comment by churik** [comment]
@86doteth 

I re-read your initial issue and I suppose that it can be related to https://github.com/status-im/status-mobile/issues/21181 as we do not fetch infor on 4G by default (it can be changed in settings)
Also the amount of communities that were fetched after initial sync was fixed in 2.31 https://github.com/status-im/status-mobile/issues/21303 

Please, reopen if still relevant. 
Thanks!
