### ISSUE TITLE
Wallet - extend the tapping area of the sign commands in the Send transaction screen

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#2152]
We want to extend the tapping area of `Sign later` and `Send transaction` buttons to improve usability of this screen.

![image.png](https://images.zenhubusercontent.com/5975f08f61b4ca3b0a757622/ecea5ba8-56e4-4e6a-bada-28fd08f53711)

@flexsurfer: and also, "Cancel" on this screen, and "Got it" on sent screen

**Comment by flexsurfer** [comment]
and also, "Cancel" on this screen, and "Got it" on sent screen

**Comment by annadanchenko** [comment]
tested in ios and android
Fixed in develop 0.9.10-238-g82363020; will be in release 0.9.12
