### ISSUE TITLE
"Spending cap failing" Error is shown  when attempting to approve ERC-20 on Arbitrium

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21539]
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Recover user with non approved ERC-20 tokens.
2. Go to the swap page.
3. Go to background 5 minuts
4. Attempt to approve erc-20 for the swap transaction.

### Actual Result:
"Spending cap failing" Error is shown  when attempting to swap erc-20

https://github.com/user-attachments/assets/ff75eac3-06fb-49c2-8e9e-3cd61b424f04

https://arbiscan.io/tx/0xb09be76f993792ed8ed58bf73c3cdd110da17326e71f7b5776fcd37a851b9bed

https://arbiscan.io/tx/0xd4017a4f01f7fcae9d1b5e520ec5f4d001f2961f52e675f0b8487e48075cd12c

### Expected Result:
The approval should be successful 

### Devices:
Pixel 7a, Android 13
iPhone 11 pro max, IOS 17

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/17586130/Status-debug-logs.zip)

**Comment by briansztamfater** [comment]
My guess is that both issues happen because of reaching gasLimit, that may have already fixed by #21523 cc @smohamedjavid

**Comment by VolodLytvynenko** [comment]
hi @briansztamfater @smohamedjavid @pavloburykh, I can't reproduce this issue anymore. Seems it was fixed

**Comment by briansztamfater** [comment]
<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcjA0dGFpaWJlb2NkNnBjY3ZvanNuNGNhdzB5OGRxa2ozNGZ1ZTNjNSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9r75ILTJtiDACKOKoY/giphy.gif" />

**Comment by VolodLytvynenko** [comment]
@briansztamfater @smohamedjavid, I also can't reproduce [this issue](https://github.com/status-im/status-mobile/issues/21423) after returning to the background. Do you think it’s possible that [PR #21523](https://github.com/status-im/status-mobile/pull/21523) may have resolved it as well?

**Comment by briansztamfater** [comment]
@VolodLytvynenko @smohamedjavid  It is possible, the new changes increase the gasLimit, and the error of that issue is related to that. Let's keep it in the radar and close it if we can't reproduce it for a period of time.

**Comment by VolodLytvynenko** [comment]
сс @briansztamfater 

> ![](https://camo.githubusercontent.com/95e90a6930f08cbe64f9b465d823070e416acd452b150eaa12cd6632846fa3fd/68747470733a2f2f692e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578636a41306447467061574a6c62324e6b4e6e426a59335a76616e4e754e474e68647a42354f47527861326f7a4e475a315a544e6a4e535a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f39723735494c544a74694441434b4f4b6f592f67697068792e676966) [ ![68747470733a2f2f692e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578636a41306447467061574a6c62324e6b4e6e426a59335a76616e4e754e474e68647a42354f47527861326f7a4e475a315a544e6a4e535a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f39723735494c544a74694441434b4f4b6f592f67697068792e676966](https://camo.githubusercontent.com/95e90a6930f08cbe64f9b465d823070e416acd452b150eaa12cd6632846fa3fd/68747470733a2f2f692e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578636a41306447467061574a6c62324e6b4e6e426a59335a76616e4e754e474e68647a42354f47527861326f7a4e475a315a544e6a4e535a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f39723735494c544a74694441434b4f4b6f592f67697068792e676966) ](https://camo.githubusercontent.com/95e90a6930f08cbe64f9b465d823070e416acd452b150eaa12cd6632846fa3fd/68747470733a2f2f692e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578636a41306447467061574a6c62324e6b4e6e426a59335a76616e4e754e474e68647a42354f47527861326f7a4e475a315a544e6a4e535a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f39723735494c544a74694441434b4f4b6f592f67697068792e676966) [ ](https://camo.githubusercontent.com/95e90a6930f08cbe64f9b465d823070e416acd452b150eaa12cd6632846fa3fd/68747470733a2f2f692e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578636a41306447467061574a6c62324e6b4e6e426a59335a76616e4e754e474e68647a42354f47527861326f7a4e475a315a544e6a4e535a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f39723735494c544a74694441434b4f4b6f592f67697068792e676966)

I believed in magic for a while, but unfortunately, the magic is gone—the issue has returned :(

https://github.com/user-attachments/assets/34ac8001-d9ff-4f05-a325-bc2a0f12fa8b

[Status-debug-logs (1).zip](https://github.com/user-attachments/files/17777976/Status-debug-logs.1.zip)


### ENV:
Nightly 15 Nov, 2024

**Comment by alwx** [comment]
Might be fixed by this: https://github.com/status-im/status-mobile/pull/21541

**Comment by VolodLytvynenko** [comment]
fixed in https://github.com/status-im/status-mobile/pull/21541#issuecomment-2504280789
