### ISSUE TITLE
ERC20 bridge and swap transactions are broken

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21555]
### Steps to Reproduce:
1. Navigate to the swap/bridge page.
2. Attempt to perform a swap/bridge transaction of erc20 token.

### Actual Result:
In case of swap transaction fails with "price route not found" error. In case of bridge - no errors in UI but transaction does not appear in blockchain. 

https://github.com/user-attachments/assets/0ff2426f-acda-4b42-9c37-943afe53bbca

### Expected Result:
The swap transaction should proceed successfully

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

### Logs:
[logs.zip](https://github.com/user-attachments/files/17617778/logs.zip)

### ENV:
Nightly 4 Now, 2024

**Comment by alwx** [comment]
Might be fixed by this PR: https://github.com/status-im/status-mobile/pull/21541

**Comment by pavloburykh** [comment]
> Might be fixed by this PR: [#21541](https://github.com/status-im/status-mobile/pull/21541)

Thanks @alwx I have checked in https://github.com/status-im/status-mobile/pull/21541 and didn't reproduce the issue. So you can link this issue in your PR.

**Comment by pavloburykh** [comment]
> > Might be fixed by this PR: [#21541](https://github.com/status-im/status-mobile/pull/21541)
> 
> Thanks [@alwx](https://github.com/alwx) I have checked in [#21541](https://github.com/status-im/status-mobile/pull/21541) and didn't reproduce the issue. So you can link this issue in your PR.

@alwx UPDATE: your PR does not fix the issue. Most likely your branch was outdated when I checked, that's why I didn't reproduce. But I am reproducing now in the latest rebased build.

it should be fixed by https://github.com/status-im/status-go/pull/6059

**Comment by smohamedjavid** [comment]
Mobile PR: https://github.com/status-im/status-mobile/pull/21600

**Comment by pavloburykh** [comment]
Reopening the issue. Will close once we verify the fix in https://github.com/status-im/status-mobile/pull/21541
