### ISSUE TITLE
Onboarding - New opt-in usage data screen

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21563]
# Feature

### Description

We are changing the opt-in usage data pop-up to be more friendly. Notable changes:

- The usage-data pop-up is changed from a bottom sheet to a full screen size.
- The user has to press on "Learn more" to see more details about what will be collected.
- Upon pressing on "Learn more" the user will see a high-level bottom-sheet with an overview of what will/won't be collected. For the full details the user will need to read the Privacy Policy, which the user can press to open a bottom sheet ([Figma](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44480&node-type=text&m=dev))

<img src="https://github.com/user-attachments/assets/686d8ebb-100b-4ec4-8db8-a36b635977a2" width="350" />

<img src="https://github.com/user-attachments/assets/6fd80278-18e5-4809-93f3-ee92a3662d34" width="350" />

### Acceptance Criteria

- Images in Figma are not ready as of Nov 5 2024. It's fine to work in this issue without the assets because they can be updated in a follow-up PR.
- The new usage data views should be updated in the Settings as well. Double-check with the Design team how the Settings should look like.

### Resources

- Figma https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44428&node-type=frame&m=dev

**Comment by Parveshdhull** [comment]
> The new usage data views should be updated in the Settings as well. Double-check with the Design team how the Settings should look like.

Hi @xAlisher @pedro-et do we have designs ready for share-usage data screen for settings?

**Comment by du82** [comment]
Status really is going down the shitter, telemetry?!?! this is nolonger a privacy app, its just Discord for crypto bros

**Comment by ilmotta** [comment]
> Status really is going down the shitter, telemetry?!?! this is nolonger a privacy app, its just Discord for crypto bros

@du82 you have your right to disagree, but there are other FOSS projects with an opt-in system and this is what Status does. If you don't **opt-in**, life goes normal. We also built the integration with analytics to not share private data and we are committed to respect our Privacy Policy. The user's IP address will be exposed to the analytics tool if the user opt-in, but we want to improve this in the future by integrating the client first with the Status proxy. The rest of the data sent to analytics does not contain private data that allows somebody to identify a user. And to reiterate, it's all opt-in and you can enable/disable at will from the app settings.
