### ISSUE TITLE
Onboarding - Remove step to choose profile name and update password step

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21567]
### Description

From the new "Create profile" screen, when the user presses "Let's go", the new profile creation flow should start at the password creation step.

<img src="https://github.com/user-attachments/assets/ca081ea3-9a6b-4376-9333-420004af3573" width="350" />

### Out of scope

- Password validation improvements are out of scope, such as [Password too common](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44100&node-type=instance&m=dev) or [Password found in data breach](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44072&node-type=instance&m=dev)

### Acceptance criteria

- Remove the step allowing the user to choose a name, profile picture, or accent color.
- New subtitle "This password can't be recovered".
- Removal of the checkbox "I understand my password can't be recovered"
- The password should be limited to a maximum of 100 characters.
- The code should pick a random accent color for the user.
- The profile picture should be kept nil/unset.
- The default name should be the compressed key, but without the prefix `zQ3`. For example `shWiuC....rhf`. Double-check with designers if this is in fact the correct expectation because Figma is outdated.

### Resources

- Figma https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-43915&node-type=frame&m=dev

**Comment by Parveshdhull** [comment]
should be implemented after https://github.com/status-im/status-mobile/issues/21571

**Comment by ulisesmac** [comment]
Starting with this to properly test #21571 later.


Update:
Figma for these is still in progress (🚧 icon). Waiting for it to be ready to start with both flows.

**Comment by ilmotta** [comment]
> Figma for these is still in progress (🚧 icon). Waiting for it to be ready to start with both flows.

@ulisesmac My recommendation is talk directly with @xAlisher and start work on this as soon as possible because I thought we agreed on the flows. Maybe designers would like to adjust some details, but we don't have the luxury to wait much longer anymore if we want to include in 2.32 (which we do because in 2.33 we may not be able to prioritize this work).

**Comment by ulisesmac** [comment]
@ilmotta OK! I'll align with @xAlisher to solve it 👍
