### ISSUE TITLE
Onboarding - New intro screen

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21562]
# Feature

### Description

The new intro screen is less intrusive and easier to understand. Notable changes:

- There's no checkbox to accept the Terms of Service and Privacy Policy.
- Buttons have been renamed to "Create profile" and "Sign in".
- When the user first proceeds from "Create profile" or "Sign in", an opt-in usage data screen is shown (not a bottom sheet).
- The usage data screen is simpler and the user has to press on "Learn more" to see more details about what will be collected.

<img src="https://github.com/user-attachments/assets/1bff8007-c6da-41df-8d07-2cb1d476e6f3" width="350" />

### Acceptance Criteria

- Images in Figma are not ready as of Nov 5 2024. It's fine to work in this issue without the assets because they can be updated in a follow-up PR.

- We have separated the changes for the new usage data screen, so they are out of scope.

### Resources

- Figma https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44520&node-type=frame&m=dev

**Comment by Parveshdhull** [comment]
Notable changes:

+ \+ Order/text of background slides
