### ISSUE TITLE
Onboarding - Update carousel

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21561]
# Feature

### Description

We are changing the order of images in the onboarding carousel. Wallet and Keycard images are shown first. Communities image is gone. The new order is:

- Own your crypto
- Store your assets on Keycard
- Chat privately with friends
- Discover web3

Figma: https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44523&node-type=instance&m=dev

### Acceptance Criteria

Images in Figma are not ready as of Nov 5 2024. Before working in this issue, check if the assets are ready.

**Comment by Parveshdhull** [comment]
Already updated in: https://github.com/status-im/status-mobile/pull/21607/files

cc @ulisesmac

**Comment by ulisesmac** [comment]
@Parveshdhull OK, thanks for noticing, I'm assigning you this issue, and also it'd be great if you link it top your PR.
