### ISSUE TITLE
Keycard [Wallet] - Sign dapps requests

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#21576]
Sign dapps requests

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=409-58818&t=VFIzh8BRInCRKpP9-1

**Comment by churik** [comment]
As was discussed on wallet call, likely will be the part of 2.33

cc @shivekkhurana

**Comment by flexsurfer** [comment]
duplicate? https://github.com/status-im/status-mobile/issues/21618

**Comment by churik** [comment]
I belive so, I'll close this one as the other is already assigned
