### ISSUE TITLE
Keycard [Wallet] - Sign Swap transactions

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#21574]
Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=409-58818&t=VFIzh8BRInCRKpP9-1

**Comment by churik** [comment]
As was discussed on wallet call, likely will be the part of 2.33

cc @shivekkhurana

**Comment by flexsurfer** [comment]
duplicate? https://github.com/status-im/status-mobile/issues/21619
