### ISSUE TITLE
Popup “Vector’s key for assoc must be a number” if launch upgraded app with location message in chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2158]
### Description

*Type*: Bug

*Summary*: 
Can reproduce on Android.
App with location message in chat with Jarrad (released version 0.9.11) is upgraded with develop build. After launching and logging in: Popup “Vector’s key for assoc must be a number” 

<img width=300 src=https://user-images.githubusercontent.com/6584810/31608536-f3dd0806-b270-11e7-98a0-66444dc8afe3.png />
<img width=300 src=https://user-images.githubusercontent.com/6584810/31608574-0882fb44-b271-11e7-8c90-a8b3a3c91459.png />

#### Expected behavior
1. no popups, can open chat with Jarrad 
2. location command is in list of commands in the chat
3. location message in chat (map)

#### Actual behavior
1.  After launching and logging in: Popup “Vector’s key for assoc must be a number” 
2. location command is not in the list of commands, there are only browse, send and request
3. location message is shown as plain text in chat

### Reproduction
from 00:18 https://app.testfairy.com/projects/4803622-status/builds/6866829/sessions/14/?accessToken=1VETmQiCXOO3vhYmon5zPsQtkqs
- Install Status from playStore (ver 0.9.11)
- Open Status
- Open 1-1 chat with Jarrad
- Send location command 
- close app
- update app with develop build 
- open Status
- open chat with Jarrad

### Additional Information
* Status version: develop
* Operating System: 
Real device Galaxy S6, Android 6.0.1

**Comment by annadanchenko** [comment]
Can't be reproduced in build for https://github.com/status-im/status-react/pull/2238 Most likely is fixed together with other issues.

**Comment by alwx** [comment]
Me neither. It's a good news.

**Comment by leafcutterant** [comment]
Requesting reopening. I have this is issue. Just upgraded a mid-January nightly APK installation to the recent 1.0.1 via APK, and I get the message right after opening the app. Pressing cancel results in an unresponsive white screen.

**Comment by leafcutterant** [comment]
Will anyone see this request? None of the other participants in the issue seem to work at Status anymore.
