### ISSUE TITLE
🙈 Hide Mercuryo from the list of on-ramp providers

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#21615]
# Feature Issue

### User Story

As a lawyer, 
I want to hide Mercuryo from the list of on-ramp providers
**so that** we stay compliant with UK law. 

### Description

Mercuryo doesn't have the license to operate in UK. Having non-licensed financial providers can lead to legal troubles. So we have decided to hide it in the interim.

This is a UI only change, ie the Mercuryo provider should be hidden behind a feature flag. 
Mercuryo might make a comeback as they are already working on the license.

### Acceptance Criteria

- [ ] A feature flag hides Mercuryo from the list of on-ramp providers

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to report your request, initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@shivekkhurana
