### ISSUE TITLE
Group chat name is missing in confirming clear history dialog

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21639]
# Bug Report

## Problem 
Open group chat > options > clear history, there is an icon and name is missing

#### Expected behavior
can see group name

#### Actual behavior
![Image](https://github.com/user-attachments/assets/a754b157-6285-495e-9485-0c6255aa4e17)

### Reproduction

1. Create group chat 
2. Open it
3. Tap options > Clear history

### Additional Information

- Status version: nightly 19/11/2024
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
I can take sometimes some low-impact issues when they are quick to fix like this one.

**Comment by ilmotta** [comment]
@churik I couldn't reproduce the issue. The Clear History drawer shows the correct group name, even after editing.

**Comment by churik** [comment]
@ilmotta it is not reproducible from chat list, check the video; for me it is reproducible for both Android and IOS

https://github.com/user-attachments/assets/89906e74-ca12-4edb-b365-c8b377115e52

**Comment by ilmotta** [comment]
Perfectly reproducible now, thanks for the video.
