### ISSUE TITLE
No warning text regarding PIN attempts during login by Keycard

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21645]
# Bug Report
https://github.com/status-im/status-mobile/pull/21612

## Problem 
[comment]: # (A problem description)

User doesn't know how many attempts left before his card will be locked.

#### Expected behavior vs Actual behavior

![Image](https://github.com/user-attachments/assets/34c52f0c-aa58-4fd6-ad40-1b236f7a6d24)

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&node-type=canvas&t=t0IkcfqJEaXgHC90-0

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
i'm unable to reproduce, help is needed
