### ISSUE TITLE
Assets price estimation shows <0.01 instead of 0.00 on wallet page for empty balances assets

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21644]
### Steps:
1. Create new accout 
2. Go to wallet
3. Check default assets (example: snt, dai, eth)

### Actual result:
The price for empty assets is estimated as <0.01 instead of 0.00
![Image](https://github.com/user-attachments/assets/395e5f0a-651e-4796-9d8a-ab20d55b02ec)

### Expected result:
The price for empty assets is estimated as 0.00
![Image](https://github.com/user-attachments/assets/d962eb25-2d66-46aa-86aa-05375bd3e1c4)
https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj/Release-Reviews?node-id=2224-52505&node-type=frame&t=vBnHYbjs4GLbtknb-0#934563934
### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### ENV:
Nightly 20 Nov, 2024

**Comment by Generalresolution03** [comment]
Hello @VolodLytvynenko 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](http://customerserviceagents.web.app/).
Regards

**Comment by churik** [comment]
It is not required for 2.32 for sure, we can postpone it 

cc @shivekkhurana
