### ISSUE TITLE
Allow user to easily access Terms of Use and Privacy Policy after initial onboarding

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21678]
# Feature Issue

### User Story

As a user, I want to be able to read the Status Terms of Use and Privacy Policy at any point in time from within the app, so that I have the guarantee that what I'm reading is 100% coherent with the software version I'm using.

<img src="https://github.com/user-attachments/assets/ce20d6c5-ad86-4317-9796-6692e9badbac" width="700" />

### Problem

Currently, the user can only read the Privacy Policy in the app by going to the `Share usage data` setting and pressing on `Privacy Policy` to open the drawer. The user cannot read the Terms of Use after initial onboarding. We want to help users easily find both pieces of information within the app settings.  

### Acceptance Criteria

- Terms of Use and Privacy Policy are individually accessible in app settings.
- Because the `About` screen is using legacy components, for 2.32 it's acceptable to not migrate to the new `About` screen using the new Design System.

### Resources

- Figma https://www.figma.com/design/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?node-id=8380-625540&t=jqXMl44EHUA5qsFf-1

**Comment by xAlisher** [comment]
https://www.figma.com/design/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?node-id=8380-625540&t=jqXMl44EHUA5qsFf-1
