### ISSUE TITLE
Web3 suggestions are missing in Console chat [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2167]
### Description

*Type*: Bug

*Summary*: No suggestions shown when entering `web3` in console

#### Expected behavior
Suggestions should be displayed

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/31613661-77bac594-b28c-11e7-8629-d146c96fbc81.png)

### Reproduction
- Open Status
- Go to Console
- Type `web3`

### Additional Information
* Status version: develop `0.9.10-238-g82363020+ (1795)`
* Operating System: Android, iOS

**Comment by alwx** [comment]
Fixed here: https://github.com/status-im/status-react/pull/2216

**Comment by annadanchenko** [comment]
Tested ok, can be merged.

**Comment by oskarth** [comment]
Fixed in develop

@rasom Can you cherry-pick this to 0.9.12 release branch? Once that's done this can be closed

**Comment by jeluard** [comment]
It is part of branch `0.9.12` now.
