### ISSUE TITLE
User can not sign transactions after Login/Sign up flows using Keycard

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21686]
# Bug Report

### Reproduction

**Part 1** (is not necessary but i've started from it just to check all the scenarios)

1. Migrate key pair to empty Keycard using such flow:

- Profile -> Keypair (use empty Keycard)

2. Login to your user from Step 1 using your Keycar
3. Go to Wallet
4. Send some assets/collectibles to check that signing is working in this scenario (Testnet/Mainnet works fine)

**Part 2**

1. Delete your Profile from Part 1
2. Use your Keycard from Part 1
3. Go to Log in -> Log in with Keycard
4. Go through Log in flow
5. Inside of your Profile send some assets/collectibles to check that signing is working ((Testnet/Mainnet no matter)

**Part 3**

1. Logout
2. Go to Create new profile
3. Use empty Keycard (Factory reset on Desktop can clear your card)
4. Go through Sign up with Keycard flow
5. Inside of your Profile send some assets/collectibles to check that signing is working (Testnet/Mainnet no matter)

#### Actual behavior

**Part 1**

-signing transactions works fine on both platforms, Testnet/Mainnet (ERC-20, not ERC-20, Collectible)

**Part 2** 

- iOS shows error and no password drawer oped

![Image](https://github.com/user-attachments/assets/53ea4743-788c-4ea1-b419-711681a9fefd)

- Android slide button just slides and nothing happen

https://github.com/user-attachments/assets/9445e697-b5c7-4381-a568-b9461f513054

**Part 3**

- iOS shows error and no password drawer oped
- Android shows error and no password drawer oped

![Image](https://github.com/user-attachments/assets/89002a6f-449a-483d-8f35-62d022bc00db)

**Android logs:**

[Android_Keycard_Sign.zip](https://github.com/user-attachments/files/17921305/Android_Keycard_Sign.zip)

#### Expected behavior

user can sign in his transactions by his Keycard in all flows: Migration, Login and Sign up.

### Additional Information

- Status version: nightly 26/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
cross-posting with https://github.com/status-im/status-mobile/pull/21541#issuecomment-2501204362

I believe it should be waiting for new endpoints as well, though I'm not sure.
