### ISSUE TITLE
"cannot resolve route id" error is shown after an attempt to send collectible

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21702]
### Steps:
1. Go to collectible sending flow
2. Send collectible

### Actual result:
Collectible is not sent. Toast with "cannot resolve route id" error is shown

### Expected result:
Collectible is sent

### Logs:
[Status-debug-logs (6).zip](https://github.com/user-attachments/files/17947948/Status-debug-logs.6.zip)

https://github.com/user-attachments/assets/962ca67d-93f6-46df-9679-ac884c125a92

### Additional info:
For IOS send button is shown just as disabled
![image](https://github.com/user-attachments/assets/3be39ff2-4eec-4a32-b3ad-0e60c1804020)

**Comment by VolodLytvynenko** [comment]
NOTE for QA: Retest the ability to see sent collectibles within activity tab and navigation to the blockchain as described in https://github.com/status-im/status-mobile/pull/21596

**Comment by vkjr** [comment]
@VolodLytvynenko, do you always have `slide to send` button active? Because I faced the issue that it is not even active most of the times.
