### ISSUE TITLE
[Android] Login with Keycard stucks on Preparing screen from time to time

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21708]
# Bug Report

## Problem 
[comment]: # (A problem description)

User stucks and nothing happens.
Only close the app helps.

### Reproduction

1. You need a Keycard with a key pair on it
2. Install app
3. Go to Log in -> Log in with Keycard
4. Go through the flow

#### Actual behavior

Log in stops on Prepare screen.
![Image](https://github.com/user-attachments/assets/9a68391a-e4ea-4ce2-9dec-77db2c3e59f2)

Today I've faced that my Log in stuck 5 times.
Logs: [Log_in_keycard.zip](https://github.com/user-attachments/files/17950039/Log_in_keycard.zip)

#### Expected behavior

User is successfully Logged in.

### Additional Information

- Status version: nightly and https://github.com/status-im/status-mobile/pull/21705
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
https://github.com/status-im/status-mobile/pull/21496

> Navigate to next screen once onboarding animation and account creation both are complete.
> 
> Note: If account creation fails, user will get stuck on loading screen.

As per logs,
> [signals] node.login error nil

> 2024-11-28T13:01:05.375Z	ERROR	mobile/status.go:551	failed to restore account	{"error": "failed to prepare for keycard: failed to get keycard pairings: file does not exist", "errorVerbose": "file does not exist\nfailed to get keycard pairings\ngithub.com/status-im/status-go/api.(*GethStatusBackend).prepareForKeycard
