### ISSUE TITLE
"ParaSwap error: not enough "token_name"  TokenTransferProxy" error shown after 'approve' button is tapped when arbitrium network is selected

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21704]
### Steps:
1. Go to swap selection arbitrium network
2. Select any ERC-20
3. Tap 'swap' button

### Actual result:
"ParaSwap error: not enough "token_name"  TokenTransferProxy" error shown

https://github.com/user-attachments/assets/91683c30-2553-4711-8f87-40ca47462473

### Logs:
[logs (2).zip](https://github.com/user-attachments/files/17937221/logs.2.zip)

### Additional info:
current issue doesn’t occur on desktop or Paraswap

**Comment by churik** [comment]
@VolodLytvynenko is it still the case or it was temp?

**Comment by VolodLytvynenko** [comment]
> [@VolodLytvynenko](https://github.com/VolodLytvynenko) is it still the case or it was temp?

@churik it seems it was a temporary issue. Can't reproduce it anymore. Fixed on Paraswap side. I close this issue
