### ISSUE TITLE
Unable to enter data into Input field after switching to fiat

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21711]
### Steps:
1. Navigate to the Send or Bridge Flow setup page.
2. Tap the "Switch to Fiat" button.
3. Attempt to enter any value in the input field.

### Actual Result:
When the "Switch to Fiat" button is tapped, the input field displays 0.00 and does not allow the user to enter any data until the existing value is manually removed.

https://github.com/user-attachments/assets/c8c86988-b865-4d20-b972-bb51d94f05bc

### Expected Result:
After tapping the "Switch to Fiat" button, the user should be able to input values directly into the field without needing to remove any pre-filled data.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 28, 2024

**Comment by clauxx** [comment]
@VolodLytvynenko fixed this issue as part of [#21732](https://github.com/status-im/status-mobile/pull/21732) already. Can be moved to 2.32?

**Comment by VolodLytvynenko** [comment]
> [@VolodLytvynenko](https://github.com/VolodLytvynenko) fixed this issue as part of [#21732](https://github.com/status-im/status-mobile/pull/21732) already. Can be moved to 2.32?

@clauxx thank you! Just moved to 2.32
