### ISSUE TITLE
Asset value displays as 0 in Activity Tab after sending transaction

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21728]
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Send asset (in my case USDT with 26 value on L1)
2. Check balances in the activity tab

### Actual result:
The asset is shown with 0 value

https://github.com/user-attachments/assets/a98cc672-3a22-4c42-aafb-58840ed5f8d1

### Expected result:
The sent asset should display its correct value in the Activity tab, matching the amount sent.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs (9).zip](https://github.com/user-attachments/files/17976423/Status-debug-logs.9.zip)

**Comment by smohamedjavid** [comment]
Fixed here: https://github.com/status-im/status-mobile/pull/21745
