### ISSUE TITLE
Sometimes balances are not updated until relogin

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21725]
**Steps:**

1. Select asset for bridge
2. Remember the balance before bridge
3. Perform bridge
4. Check if balance has been updated (try pull to refresh)

**Actual result:** Balances are not updated after bridge until relogin

[Status-debug-logs - 2024-11-29T174836.792.zip](https://github.com/user-attachments/files/17961198/Status-debug-logs.-.2024-11-29T174836.792.zip)

https://github.com/user-attachments/assets/f0670b8b-ac8e-4bdd-8fdb-ca80d9ba76ab

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by churik** [comment]
Reproduced today on Send flow. 
The balance of the requested account already for 12 mins is changed, but the balance remains the same.

The balance only updates after a **manual logout and relogin.** (pay attention to Account1)

https://github.com/user-attachments/assets/46809a28-180d-4e30-8e4d-d968ec667d62

[logs (24).zip](https://github.com/user-attachments/files/17993083/logs.24.zip)
