### ISSUE TITLE
Not a default wallet account is blocked in case we have a default account migrated on the Keycard

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21749]
# Bug Report

## Problem 
[comment]: # (A problem description)

If we have 2 or more wallet accounts:

original
extra one (imported or newly created)

And then do a migration then transactions will work only for that original default migrated key pair. For extra one sign doesn't work.

**Please pay attention:** we have the same error also on Swap sometimes https://github.com/status-im/status-mobile/issues/21701

#### Actual behavior

![Image](https://github.com/user-attachments/assets/25c094f5-a972-4fa1-b651-3e1df1cb35c0)

[Send_Keypair.zip](https://github.com/user-attachments/files/18006947/Send_Keypair.zip)

#### Expected behavior

Under discussion

### Reproduction

1. Install app
2. Create user by a standard flow
3. Go to Wallet -> Create new "Not a Keypair" account -> New key pair
4. Make sure you have assets on both accounts
5. Go to Profile -> Keypair and do a migration
6. Go to Wallet -> Send from "Not a Keypair" account to default one.

### Additional Information

- Status version: nightly 04/12
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by DonaldDeVo** [comment]
@mariia-skrypnyk Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.
