### ISSUE TITLE
Sync is not available for mobile keycard accounts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21755]
# Bug Report

## Problem 
As there is no option to sync current mobile keycard wallet with desktop, users cannot continue the flows that are not available on mobile

#### Expected behavior
can sync (or use a fallback feature), see all accounts on desktop and continue to use it.

#### Actual behavior
cannot sync, as Showing QR code is blocked
![Image](https://github.com/user-attachments/assets/d6889435-aa01-471c-bb26-125586da3c5a)

### Reproduction

1. Open profile > sync
2. Try to generate new QR

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by swissDev-cloud** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[StatusMobile Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
