### ISSUE TITLE
Dapps Interaction unavailable for Keycard users

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#21763]
# Description
Display interactions unavailable for dapps

design 
https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=4588-149473&t=La4CcSHCelLKtUDs-4

## Unavailable Features

- dApps Connection

<img src="https://github.com/user-attachments/assets/abb9e24c-63c7-4935-bf5f-7f4e9eca418b" width="370px"/>

**Comment by pavloburykh** [comment]
Hey @mohsen-ghafouri! I see @smohamedjavid implemented keycard support for swaps here https://github.com/status-im/status-mobile/pull/21764 So guess we do not need to add unavailable modal for swaps. cc @shivekkhurana

**Comment by pavloburykh** [comment]
@mohsen-ghafouri sorry, I missed your conversation here https://github.com/status-im/status-mobile/pull/21764#issuecomment-2520802533

**Comment by ilmotta** [comment]
> Anything that not works for Keycard users should see this modal

@mohsen-ghafouri are you going to literally update all places to use this modal while resolving this issue? Could you share which flows will be affected? I just want to make sure this issue isn't just related to the wallet context, but if it is only related to the wallet, please let us know.

Thanks!

cc @shivekkhurana

**Comment by churik** [comment]
@ilmotta should not we update the copy and not mention Status-desktop?

**Comment by mohsen-ghafouri** [comment]
@ilmotta My changes is only about dapps interaction. here is draft PR https://github.com/status-im/status-mobile/pull/21771

Also not anymore about swap as already we support swap for keycard user

**Comment by ilmotta** [comment]
> [@ilmotta](https://github.com/ilmotta) should not we update the copy and not mention Status-desktop?

That's correct @churik. @mohsen-ghafouri please check with @xAlisher the correct copy. I believe he already updated in Figma, but the source code in the draft PR is outdated (mentioning the Desktop app) https://github.com/status-im/status-mobile/pull/21771/files#diff-6fca8a289be2fa658792936fc459e6e36e6fa56d9187da43c01ec491f9f8a6b5R669

> @ilmotta My changes is only about dapps interaction. here is draft PR https://github.com/status-im/status-mobile/pull/21771

Thanks @mohsen-ghafouri. Could you update the issue description? I read `Anything that not works for Keycard users should see this modal` and the *anything* word made me think last week that this issue would cover all flows. I'll create an issue about other flows outside the scope of this issue.

**Comment by mohsen-ghafouri** [comment]
If we refer to `dApps` copy i can see other place in the app we use it like that. I'm not sure what should be the correct copy?

**Comment by ilmotta** [comment]
Issue created for mobile-core https://github.com/status-im/status-mobile/issues/21778

cc @flexsurfer @seanstrom @churik
