### ISSUE TITLE
Closed Keycard drawer with PIN doesn't open again

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21768]
# Bug Report

## Problem 
[comment]: # (A problem description)

### Reproduction

1. Login to acc with a Keycard
2. Go to Wallet -> Send
3. Slide to send
4. Close drawer with PIN
5. Try to slide once more

#### Actual behavior

https://github.com/user-attachments/assets/08001078-f084-4ee6-a936-6da32970beae

#### Expected behavior

User can slide again and see PIN drawer

### Additional Information

- Status version: nightly 06/12
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mariia-skrypnyk** [comment]
Hey @smohamedjavid !

We have this issue appeared on Send again.
But it has some specifics:

issue appears in case we to the send from default key pair to additional one (e.g. imported)

On my video I did two send flows:

1) from imported key pair `Scream` to default one `Account 1` - drawer works fine
2) from default one `Account 1` to imported key pair `Scream` - drawer is not opening after closing

https://github.com/user-attachments/assets/1264b9a2-5c01-4ea4-baa2-44cff7292239

Hope it will help to detect an error 🙏

**Comment by smohamedjavid** [comment]
Fixed here: https://github.com/status-im/status-mobile/pull/21831 🙏 

Regression from #21753 as it introduced new methods to handle keycards. Now it's properly handled 👍
