### ISSUE TITLE
Keycard - Disable or hide unsupported Keycard flows

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21778]
# Problem

In Status 2.32 Keycard users won't be able to use their keycards in all possible flows. We want to provide a better user experience to those users so that they don't waste time in flows that will surely fail at some point.

## Acceptance Criteria

In case a Profile is set-up with a Keycard: 

- Request to join a community should show a drawer stopping the user from proceeding https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=4588-67142&node-type=instance&m=dev
- Show the special _unsupported feature_ drawer when the user tries to **enable** biometrics.
- Hide option to edit password.

<img src="https://github.com/user-attachments/assets/e7e55e8c-18c5-4c8e-9359-d2c722c352de" width="400" />

## Out of scope

- Ignore editing shared addresses in Figma https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=4588-104535&node-type=shape_with_text&m=dev (this feature is disabled behind a feature flag, so we don't need to worry about it).
- Wallet-related flows.

## Resources

- Check PR https://github.com/status-im/status-mobile/pull/21771 because this issue can reuse some of the code related to the drawer.

**Comment by churik** [comment]
@ilmotta @xAlisher 
I would not remove `Settings > Password > Face ID`, as we have several flows to consider:
1) upgrading from v1 + bio enabled + "Do not use a kycard for login" -> upgrade to 2.32 = can login on 2.32 without card
2) on 2.32 enabled bio > migrate to kk = can login, need to use bio + PIN + keycard. I suppose this is acceptable for now.


Settings > Password > Change password should be reomoved from kk accounts, for sure

**Comment by ilmotta** [comment]
@churik is completely right. I'm updating the issue description to only show the pop-up when the user tries to enable the setting (because that's when the password authentication will kick-in), but keep the option visible to avoid a nasty regression for v1 users. The user will still be able to disable biometrics because disabling doesn't require authentication from the `Settings > Password` screen.

**Comment by ilmotta** [comment]
Good idea to resolve this issue and https://github.com/status-im/status-mobile/issues/21755 together since they can all share the same drawer solution.
