### ISSUE TITLE
Profile photo is not updated until re-login when it is not empty

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21787]
# Bug Report

## Problem 

The picture is not updated on mobile after setting it (if it is not the first time). So far most visible on IOS.

#### Expected behavior

The profile picture is updated

#### Actual behavior

https://github.com/user-attachments/assets/ef50eec2-1aeb-46f1-add3-ada03f8ca963

On both apps the profile picture will be updated after reopening.

### Reproduction

1. Open profile
2. Change the picture several times.

### Additional Information

- Status version: release 2.32 
- Operating System: Android, iOS, desktop

[logs (25).zip](https://github.com/user-attachments/files/18081237/logs.25.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment]
@ulisesmac issue we discussed

**Comment by ulisesmac** [comment]
@churik @ilmotta Seems this issue is related to something different. The profile picture fix mentioned in https://github.com/status-im/status-mobile/pull/21782 is different (check point 2 in that description)

**Comment by seanstrom** [comment]
Updated this issue to focus on the changing the profile photo locally, and I created a separate issue for resolving the profile photo not syncing: https://github.com/status-im/status-mobile/issues/21848

**Comment by churik** [comment]
Thanks A LOT @seanstrom
