### ISSUE TITLE
Random freezes throughout the app (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21799]
At some some point Android Status app randomly freezes. It happens on different screens (i.e. chats, wallet etc) 

Below you can see video and logs. Mind that attached logs are not related to the attached video.

In logs search for events within timeline approx from 12:26 (UTC+2).

[logcat3.txt](https://github.com/user-attachments/files/18093989/logcat3.txt)

https://github.com/user-attachments/assets/bf4db2ff-62fa-4708-bc37-d8e2b34db95f

**Comment by vkjr** [comment]
@pavloburykh, could you please specify the build on which you encounter such behaviour?

**Comment by pavloburykh** [comment]
> [@pavloburykh](https://github.com/pavloburykh), could you please specify the build on which you encounter such behaviour?

unfortunately I cannot say for sure at which point issue has arised. It is difficult to identify cause it happens randomly and we do not have any reproduction steps.

**Comment by pavloburykh** [comment]
@vkjr I have managed to reproduce the issue again in the build with enabled logs. Attaching video and logs below. 

Time on device in video is UTC +2. Not sure about timezone in logs. So we need to look for logs around 20:39 (UTC +2)

https://drive.google.com/drive/folders/1k9JJMg-uFp4dsbKeN1iOmc0ySF2L0yhe?usp=sharing

https://github.com/user-attachments/assets/83087771-eaa9-4511-abf6-8bd02279946c

**Comment by pavloburykh** [comment]
> [@vkjr](https://github.com/vkjr) I have managed to reproduce the issue again in the build with enabled logs. Attaching video and logs below.
> 
> Time on device in video is UTC +2. Not sure about timezone in logs. So we need to look for logs around 20:39 (UTC +2)
> 
> https://drive.google.com/drive/folders/1k9JJMg-uFp4dsbKeN1iOmc0ySF2L0yhe?usp=sharing


@vkjr just in case, attaching logcat as well https://drive.google.com/file/d/1RPWUyn1QPMWxZLT1PBVQBuXmTAlTbJG6/view?usp=sharing

**Comment by Parveshdhull** [comment]
Thank you @pavloburykh for sharing the logs. Probably issue is in go side.

```
12-11 17:07:01.429 32724   525 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 525 (Thread-15), pid 32724 (status.ethereum)
12-11 17:07:04.706 18836 18836 F DEBUG   : backtrace:
12-11 17:07:04.706 18836 18836 F DEBUG   :       #00 pc 000000000102a358  /data/app/~~-rF5cXFgqvhu_eSlwtArEA==/im.status.ethereum-ozKicltaKfMZQMn98YqXGA==/lib/arm64/libgojni.so
```
Another error probably related
```
12-11 20:36:58.199 18683     0 E Go      : fatal error: concurrent map iteration and map write
```

**Comment by vkjr** [comment]
@Parveshdhull, thanks for analysing the log file! The last error record looks especially suspicious regarding to the freeze.
Btw, do you use any specific tools for analysing log files?

**Comment by Parveshdhull** [comment]
> Btw, do you use any specific tools for analysing log files?

Nothing special, just using vim search to locate crashes.

**Comment by vkjr** [comment]
Current assumption is that waku error leads to freezes.
So as far as I understand we are waiting for this [status-go PR](https://github.com/status-im/status-go/pull/6187) to be merged. And then to be included in status-mobile, here is [the PR](https://github.com/status-im/status-mobile/pull/21809) for this.
@pavloburykh, plese correct me if I'm wrong 🙏

**Comment by pavloburykh** [comment]
> [@pavloburykh](https://github.com/pavloburykh), plese correct me if I'm wrong 🙏

@vkjr that's correct. Thank you for your investigation.

**Comment by vkjr** [comment]
@pavloburykh, I just encountered [this comment](https://github.com/status-im/status-mobile/pull/21809#issuecomment-2542027057). 
So it looks like needed waku changes are already in mobile, so this issue can be re-checked

**Comment by pavloburykh** [comment]
> [@pavloburykh](https://github.com/pavloburykh), I just encountered [this comment](https://github.com/status-im/status-mobile/pull/21809#issuecomment-2542027057). So it looks like needed waku changes are already in mobile, so this issue can be re-checked

@vkjr the fix has been merged into release branch but not in develop yet. Let's wait until the fix is in develop and then re-check and close this issue.

**Comment by vkjr** [comment]
@pavloburykh, sure!
Did you notice any freezes on release build after the merge?

**Comment by pavloburykh** [comment]
> [@pavloburykh](https://github.com/pavloburykh), sure! Did you notice any freezes on release build after the merge?

Nope, everything is good so far.
