### ISSUE TITLE
Cannot perform transactions/create derived account via keycard using NON default keypairs which existed before keycard migration

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21803]
Probably regression of https://github.com/status-im/status-mobile/pull/21753 cc @flexsurfer 

**Steps:** 

1. Create user
2. Import additional keypairs
3. Migrate account to keycard
4. Try to perform transactions/create derived account  using NON default keypairs

**Actual result:** cannot perform transactions/create derived account using NON default keypairs. At the same time user is able to add new keypairs after migration and use accounts derived from them, as well as create/use accounts based on default keypair. 

[Status-debug-logs - 2024-12-11T195028.929.zip](https://github.com/user-attachments/files/18100049/Status-debug-logs.-.2024-12-11T195028.929.zip)

https://github.com/user-attachments/assets/b30cdfca-a811-41a4-9f79-facafe1e2568

https://github.com/user-attachments/assets/ed361f0f-3bba-4fd1-93e8-34a0cef907df

**Comment by ilmotta** [comment]
@flexsurfer @pavloburykh 

@churik and I believe this issue should be moved to 2.33, unless the fix is very safe to be introduced with low risk of regressions and is done by today. The reason for that is that we are looking for finishing testing by Friday so we need now to cut off risky changes and which can be difficult to test.

**Comment by flexsurfer** [comment]
hey @ilmotta better to include it https://github.com/status-im/status-mobile/pull/21808

**Comment by ilmotta** [comment]
> hey [@ilmotta](https://github.com/ilmotta) better to include it [#21808](https://github.com/status-im/status-mobile/pull/21808)

That PR is quite safe indeed in terms of code changes, approved now @flexsurfer 👍🏼
