### ISSUE TITLE
Wrong derived address on kk accounts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21819]
# Bug Report

## Problem 
Addresses are not derived from main account correctly (so deriviation path that is shown is right, but the derived address is wrong) 

#### Expected behavior
they will be the same

#### Actual behavior
On DeviceA:
![Image](https://github.com/user-attachments/assets/26852689-8078-49b7-9049-26e359f4c527)

On DeviceB:
![Image](https://github.com/user-attachments/assets/4fe73a6b-04d9-464c-9d3d-98df7dcd379e)

### Reproduction

1.  Device A: Recover user with a seed:`upon benefit able affair order control six gaze visa truck assume pear`
2. + Add account, check address and deriviation path
3.  Device B: Recover same account, migrate to kk
4. + Add account, check address and deriviation path

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qfrank** [comment]
Hi @churik , could you help check if [PR](https://github.com/status-im/status-mobile/pull/21824) fixed the issue? thank you

**Comment by churik** [comment]
replaced with https://github.com/status-im/status-mobile/issues/21870, as the fix was merged to `develop`, but there us other critical issue
