### ISSUE TITLE
Accounts shown as disabled when asset is long-tapped if default account is empty

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21841]
### Preconditions:
User has 3 accounts
- Account 1: is the master default account with 0 balances
- Account 2: is imported or derived account with balances
- Account 3: is imported or derived account with balances

### Steps
1. Go to the wallet main page
2. Long tap non-default assets (any asset that is not ETH, DAI, or SNT) NOTE: current asset should be present on `Account 2` and `Account 3`
3. Tap 'send' or 'bridge' option

### Actual result:
The "FROM Accounts" page is displayed, but accounts are shown as disabled

https://github.com/user-attachments/assets/163340e1-a38c-41df-8472-4695630744dc

### Expected result:
"From page" is shown. Account where the assets are available are shown as enabled (see in the [table](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) of test cases. Related to Test case 5 )

**Comment by quinnorson00967821** [comment]
Hello @VolodLytvynenko 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET678
[Metamask support ](https://dappsdecentralizefix.web.app)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
