### ISSUE TITLE
Route built despite Insufficient ETH for Gas Fees coverage

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21847]
### Preconditions:
The user does not have or has an insufficient amount of ETH to cover gas fee

### Steps:
1. Go to the Send or Bridge Setup page using an account with insufficient ETH to cover gas fees.
2. Attempt to build a route for the transaction using ERC-20 asset

### Actual result:
The route is built, 'review send' button is enabled, user can navigate to tx confirmation page

https://github.com/user-attachments/assets/74f94721-e64a-4f89-b02f-daf04aa2d6ae

### Expected result:
The route is not built. Validation is shown
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-222681&m=dev
![Image](https://github.com/user-attachments/assets/5f9de4f9-ca35-498a-9356-a42b5d0147a7)

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by Lisa238-Dev** [comment]
> ### Preconditions:
> The user does not have or has an insufficient amount of ETH to cover gas fee
> 
> ### Steps:
> 1. Go to the Send or Bridge Setup page using an account with 0 ETH or insufficient ETH to cover gas fees.
> 2. Attempt to build a route for the transaction.
> 
> ### Actual result:
> The route is build, 'review send' button is enabled, user can navigate to tx confirmation page ![Image](https://github.com/user-attachments/assets/c94d5fb9-3b9a-4658-9e4b-a617a9e8cbac)
> 
> ### Expected result:
> The route is not built. Validation is shown https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-222681&m=dev ![Image](https://github.com/user-attachments/assets/5f9de4f9-ca35-498a-9356-a42b5d0147a7)
> 
> ### Devices:
> * Pixel 7a, Android 13
> * iPhone 11 Pro Max, IOS 17



Hello @VolodLytvynenko 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID E11092
Please see the link below to our dedicated support line:
[ETH Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by VolodLytvynenko** [comment]
### Additional steps:
1. Go to the Send or Bridge Setup page using ETH
2. Input the max value in ETH

### Actual result:
validation is not shown
![Image](https://github.com/user-attachments/assets/4c266c49-166c-4472-b9fa-380f7a0c2cf3)

### Expected result:
validation is not shown https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-222681&m=dev
