### ISSUE TITLE
After upgrade faucet, send and location messages are shown as plain text, request is shown without a text

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2185]
### Description

*Type*: Bug

*Summary*: After upgrade from 0.9.11 (both iOs and Android)
1. For sender in Console chat faucet message is shown as plain text
2. For sender in 1-1 chat send and location messages are shown as plain text. Request message is shown without a text (it shows only blinking green icon)
3. Note that received location, send and request messages are shown fine in 1-1 chat, so issue happens only with messages sent by this contact, not with messages received
If re-launch the app then same issue persists

![img_2371](https://user-images.githubusercontent.com/6584810/31661178-181e0f98-b33a-11e7-9ed5-5ca032a51818.jpg)

![img_2372](https://user-images.githubusercontent.com/6584810/31661209-24c2d15c-b33a-11e7-94c8-c74eaa26c773.jpg)

### Reproduction
On 0.9.11 (installed from PlayStore or TestFlight)
- on 2 devices: each of the users should send location, send, request and text message in 1-1 chat
- upgrade both devices to develop build
- open 1-1 chat

iOS: https://app.testfairy.com/projects/4803590-status/builds/6879016/sessions/12/?accessToken=pKobsPKp8kEIQAlYUx6FxHbAaLE
Android: https://app.testfairy.com/projects/4803622-status/builds/6870654/sessions/5/?accessToken=Ba6r8NyEGH5eFGV6HJckkgloqL0

### Additional Information
* Status version: develop  0.9.10-243-g47c4b901
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device Galaxy S6, Android 6.0.1

**Comment by oskarth** [comment]
Debugging notes trying to minimize reproduction.

Device 1 (simulator):
- Checkout tag 0.9.11
- Add device 2 running development (`fd09a16ca55a59b4ad178aa64b76943f94917b0c`)
- Send location, shows up fine
- Change to develop and notice location now is plain text
- Notice can't send location (not in suggestions)
![image](https://user-images.githubusercontent.com/1552237/31733201-3621d25c-b43b-11e7-883a-6afb6a1da0eb.png)


Device 2 (real iOS):
- Run development and chat with device 1

**Comment by oskarth** [comment]
Mailman isn't set to mixable, which is necessary to show /location suggestion in 1on1 chat. Changing code to (hacky fix, not real fix):

```
(defn mixable-or-mailman? [x]
  (or (:mixable? x)
      (= (:name x) "Mailman")))

(defn get-mixable-identities
  "Returns a lazy-seq of all mixable contacts. Each contact contains only one key `:identity`."
  [{:contacts/keys [contacts]}]
  (->> contacts
       (vals)
       (filter mixable-or-mailman?)
       (map (fn [{:keys [whisper-identity]}]
              {:identity whisper-identity}))))
```

Shows location as a suggested command again.

**Comment by annadanchenko** [comment]
Upgraded iOS and Android. Location, send and request commands look ok in group and 1-1 chat

**Comment by alwx** [comment]
Let's merge it!

**Comment by asemiankevich** [comment]
I am reopening this . Reproducible for google play build upgraded to `0.9.10-311-gf37a5a39+` 
![image](https://user-images.githubusercontent.com/28752642/31947348-cad85678-b8dc-11e7-9fc1-078afd32b6f2.png)

**Comment by asemiankevich** [comment]
The issue is partially reproducible in latest develop upgrade (to ` 0.9.10-313-g21a80d71+ (1870)`). Case: using google play build recover account with some ETH and send 2 transactions to contact. Upgrade. Actual result: first `/send` is shown as plain text. 

![image](https://user-images.githubusercontent.com/28752642/31989133-141a5e74-b97a-11e7-8a47-41efa691ab55.png)
TF https://app.testfairy.com/projects/4803622-status/builds/6954360/sessions/3/?accessToken=OD7HJXQt1-AUIkedaU5QN9GdSXM

**Comment by jeluard** [comment]
@asemiankevich Is this still an issue?

**Comment by asemiankevich** [comment]
@jeluard it is not. tested with develop `0.9.10-339-g089cd821+`
