### ISSUE TITLE
Wrong derived addresses are created after upgrade from v1 Status app after keycard migration

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21870]
Follow up on https://github.com/status-im/status-mobile/pull/21824

**Steps:** 

1. Install Status v1 app
2. Create account
3. Upgrade to Status 2.32
4. Migrate user to Keycard
5. Create additional wallet account via keycard (from default keypair) 
6. Check if new account address is correct 

**Actual result:** account address is incorrect

[Status-debug-logs - 2024-12-16T172321.128.zip](https://github.com/user-attachments/files/18152746/Status-debug-logs.-.2024-12-16T172321.128.zip)

![photo_2024-12-16 17 22 05](https://github.com/user-attachments/assets/b41bc7d8-cdce-499c-b140-3d29dd899d53)

**Expected result:** 

![photo_2024-12-16 17 23 04](https://github.com/user-attachments/assets/777a0e89-e671-4db8-8cf9-7a4a1b00aac6)

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by churik** [comment]
close in favor of https://github.com/status-im/status-mobile/issues/21836
