### ISSUE TITLE
Better notification for Sign transaction screen when app is offline [2193]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2200]
### Description

*Type*: Bug

*Summary*: Being offline should not prevent user from using the application however we need to standartize the flow for all the screens. When I try to sign transaction while being offline I receive not user friendly red pop-up that should be changed to the standart we apllied to the app.

Moreover I suggest to disable the `Sign Transaction` button when there is no internet connection

#### Actual behavior

Android
![image](https://user-images.githubusercontent.com/28752642/31680629-88421434-b37d-11e7-9f1c-60cb729c412b.png)

iOS even doesnt have the notification
![image](https://user-images.githubusercontent.com/28752642/31682394-99f822fe-b382-11e7-9047-3772f1d0d1f0.png)

### Reproduction

- Open Status
- Turn off the internet
- Proceed with sending transaction

### Additional Information
* Status version: branch '0.9.10-253-gea9e0055+`
* Operating System: Android, iOS

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/6881676/sessions/1/?accessToken=UxV8re71z6s9axRhrQLHvbPsnis

**Comment by sla-shi** [comment]
@asemiankevich can we close this?

**Comment by asemiankevich** [comment]
@sla-shi current behavior looks like:

![image](https://user-images.githubusercontent.com/28752642/32484041-8dbe023c-c3af-11e7-9422-9e640b09d127.png)

@flexsurfer is there something we gonna fix ? Like the pop up looks prefect, but do we want to change the text inside to make it more userfriendly ?
