### ISSUE TITLE
[Discover] Disable 'All' link for Recent statuses and Popular hashtags screens when Discover is empty

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2205]
### Description

*Type*: Bug

*Summary*: Disable 'All' link for empty Discover so user is not confused clicking it and seeing empty screen

#### Expected behavior
'All' is disabled on Discover empty screen

![image](https://user-images.githubusercontent.com/28752642/31710281-32178adc-b3fd-11e7-95b4-c53ade46e75b.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/31710234-1193a642-b3fd-11e7-98fc-fe23a9f5e7d3.png)

**Comment by oskarth** [comment]
Fixed in develop, will be in release 0.9.12

**Comment by oskarth** [comment]
@rasom Can you please cherry pick above commit into 0.9.12 branch? Once that's done this can be closed.

**Comment by oskarth** [comment]
In 0.9.12 branch, closing.
