### ISSUE TITLE
Webview with DApp is reloaded after sending a transaction 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2212]
### Description

*Type*: Bug

*Summary*: After user sends a transaction initiated from the webview with a DApp  (e.g AuctionHouse) there is 
1. Transaction Sent screen is shown (it's ok)
2. If close the Transaction Sent screen then webview with DApp is reloaded and initial page is shown (this is wrong). Would expect to stay on the same page/state from which transaction was initiated

### Reproduction
from 00:17 https://app.testfairy.com/projects/4803622-status/builds/6895380/sessions/5/?accessToken=o2-X/kZlh3BvoeLhycKdOtKiggM
- Open Status
- Open Contacts
- Tap on Auction House
- Tap on button  Create an auction. As a result, new page with "First reserve a name..." text is shown
- In field Name To Reserve type some random name e.g. "sdfkhdfjh.eth"
- tap on button Register Name. As a result Send transaction screen will be shown
- tap on Sign transaction
- provide valid password and tap on Sign transaction. As a result, Transaction Sent screen is shown
- Tao on Got It
- Check which page of Auction House is shown, it's expected to get same page with text  "First reserve a name..." Currently, (it's a bug) home page is shown

### Additional Information
* Status version: develop  0.9.10-270-gfd09a16c+
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device Samsung Galaxy S6, android 6.0.1

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
