### ISSUE TITLE
No blue line is shown when syncing is in progress on Android

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2213]
### Description

*Type*: Bug

*Summary*: Only on Android: when app syncs there should be blue line in Chats and inside individual chat (e.g. Console). Now, there is no line shown, only text, note that on iOS line is shown.
![screenshot_20171018-210721](https://user-images.githubusercontent.com/6584810/31737876-2b3af39c-b449-11e7-8841-4539e340306d.png)

#### Expected behavior
line is shown in Chats and in individual 1-1 chat
#### Actual behavior
no line

### Reproduction
- switch to network where app will start syncing (e.g. Ropsten)
- Open Status
- Open Chats -> check for blue line
- Open Console chat -> check for blue line

### Additional Information
* Status version: develop
* Operating System: 
Real device Google Pixel XL, Android 8.0
Real device Samsung Galaxy S6, android 6.0.1

**Comment by chadyj** [comment]
We no longer have syncing. Closing.
