### ISSUE TITLE
Mainnet/Mainnet with upstream RPC: Text messages are not received 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2219]
### Description

*Type*: Bug

*Summary*: Text message is not received if sender and recipient use app with Network set to
Mainnet or Mainnet with upstream RPC. 

#### Expected behavior
Text message is received if sender and recipient are on Mainnet. Same for Mainnet with upstream RPC. 
#### Actual behavior
No text message is received

### Reproduction
Sender and recipient are on Mainnet (or on with Mainnet upstream RPC)
- Open Status 
- Open 1-1 chat
- As sender: Send text message
- As recipient: check that text message is received

### Additional Information
* Status version: develop
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0
Real device Samsung Galaxy S6, android 6.0.1

**Comment by jeluard** [comment]
Main net has been disabled for this release (see #2239).

**Comment by yenda** [comment]
Also this is a status-go issue, messages are not received on mainnet because the PoW on our whisper messages is too low

**Comment by oskarth** [comment]
Effectively not high priority considering how long it has been dormant.

@annadanchenko thoughts on state of this?

**Comment by annadanchenko** [comment]
rechecked on nightly build from March 29. Text messages sent when on "Mainnet with upstream RPC" are received ok. Nothing received and Messages connection problem grey line is shown for Mainnet.

**Comment by annadanchenko** [comment]
Mainnet will be removed in the network options. Works fine on MAinnet with upstream rpc
