### ISSUE TITLE
Add Wallet tests

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#2225]
##### test_insufficient_funds

Steps:

1. Set password for user from scratch
2. Wait for syncing complete
3. Go to Wallet view and click 'Send' button
4. Enter 0.1 ETH to the 'Amount' edit box
* **verify:** Message 'Insufficient funds' is shown

##### test_transaction_from_wallet_sign_now

Steps:

1. Set password for user from scratch
2. Recover user with funds
3. Wait for syncing complete
4. Add Recipient's contact
5. Go to Wallet view and click 'Send' button
6. Choose Recipient in 'Choose from contacts'
7. Enter 0.1 ETH to the 'Amount' edit box
8. Click on 'Sign transaction', enter password, click on 'Sign transaction'
9. Click on 'Got It' button
* **verify:** Recipient balance was updated via http://ropsten.etherscan.io/api?module=account&action=balance&address=0x + recipient address + &tag=latest

##### test_transaction_from_wallet_sign_later

Steps:

1. Set password for user from scratch
2. Recover user with funds
3. Wait for syncing complete
4. Add Recipient's contact
5. Go to 'Wallet' view and click on 'Send' button
6. Choose Recipient in 'Choose from contacts'
7. Enter 0.1 ETH to the 'Amount' edit box
8. Click on 'Sign Later'
* **verify:** 'Transaction Moved' popup is shown
9. Click on 'OK' button
10. Go to 'Transactions' view
11. Click on 'Unsigned' tab
12. Click 'SIGN' on under the transaction
13. Click on 'Sign transaction', enter password, click on 'Sign transaction'
14. Click on 'Got It' button
* **verify:** Recipient balance was updated via http://ropsten.etherscan.io/api?module=account&action=balance&address=0x + recipient address + &tag=latest

**Comment by oskarth** [comment]
@antdanchenko PR is merged, can this issue be closed now?

**Comment by antdanchenko** [comment]
@oskarth More tests will be added in scope of the issue, or we have a rule regarding single PR per issue?

**Comment by oskarth** [comment]
@antdanchenko No hard and fast rules (except try to make issues and PRs as small as possible as long as they solve some problem), just thought that was it, my bad. Gotcha!

**Comment by yevh-berdnyk** [comment]
**test_balance_and_eth_rate**
Steps:

1. Recover user with funds
2. Navigate to ‘Wallet’ view

- **Verify:** 
   1. ETH rate (USD total value divided on ETH value from wallet) equals rate from https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD
   2. Balance in wallet equals balance in http://ropsten.etherscan.io/api?module=account&action=balance&address=0x + recipient address + &tag=latest

 
Added steps to **test_send_transaction_from_wallet**:

1. Open ‘Wallet’ -> Transactions History tab
2. Find the latest transaction

- **Verify:** 
   1. Transaction is present in http://ropsten.etherscan.io/api?module=account&action=txlist&address= + recipient address + &sort=desc
   2. Transaction is successful in https://ropsten.etherscan.io/api?module=transaction&action=getstatus&txhash= + transaction_hash
