### ISSUE TITLE
Allow transaction filtering

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2228]
### User Story

As a user, I want to filter my transaction history as detailed in designer mockups.

### Description

When listing transaction history a button allows to navigate to a new modal. this modal allows to filter transactions based on pre-defined criteria.

*Type*: Feature

**Comment by asemiankevich** [comment]
Since we dont have `postponed` implemented yet there was a decision made to remove it from filtring options. @jeluard will make appropriate changes in corresponding PR
