### ISSUE TITLE
Ordering of messages

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#224]
Currently we don't guarantee that all messages will be received in the same order.
For example, user A sends 5 messages: "1", "2", "3", "4", "5"
User B receives "1", "3", "4", "2", "5"

**Comment by jarradh** [comment]
yes we should guarantee order, by UTC time ?

**Comment by rasom** [comment]
What if the user will have wrong time settings on his device?

**Comment by jarradh** [comment]
then some logical clock? https://en.wikipedia.org/wiki/Logical_clock
Vector Clock ?

**Comment by jarradh** [comment]
https://www.npmjs.com/package/vectorclock ?

**Comment by rasom** [comment]
@jarradh, sounds great
