### ISSUE TITLE
Full screen in webview overlaps with phone top bar

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2241]
### Description

*Type*: Bug

*Summary*: Full screen in webview overlaps with phone top bar
![img_2381](https://user-images.githubusercontent.com/6584810/31812500-7e928e16-b583-11e7-9308-6c128dc5a593.jpg)

#### Expected behavior
No overlap, as in 0.9.11 released version (see iOs screenshot below)

![93518](https://user-images.githubusercontent.com/6584810/31816922-71fc293c-b592-11e7-9a81-14ecc46abcf1.jpg)

#### Actual behavior
 Full screen in webview overlaps with phone top bar

### Reproduction

- Open Status
- Open 1-1 chat
- browse to some url, e.g `@browse bol.com`
- tap on bottom right icon to switch to full screen and check the top part of the page

### Additional Information
* Status version: develop
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0

**Comment by oskarth** [comment]
When testing, please make sure to check Android (didn't check) and if there are any other expandable views with fullscreen mode where there might be regressions.

**Comment by annadanchenko** [comment]
tested ok in release 0.9.12 build
