### ISSUE TITLE
Statusgo/Statusgo.h file not found

### ISSUE THREAD

**Issue by hprobotic** [status-im/status-react#2246]
I try to run Status on iOS and saw this error. Installed all packages without errors
![image](https://user-images.githubusercontent.com/5791885/31816938-67b5cce2-b5bc-11e7-8a34-eb1468a12c68.png)

**Comment by oskarth** [comment]
@hprobotic Did you run `mvn -f modules/react-native-status/ios/RCTStatus dependency:unpack`?

**Comment by hprobotic** [comment]
Ahh, so sorry, when i run command above, that show this error:
![image](https://user-images.githubusercontent.com/5791885/31857933-10558596-b715-11e7-8e58-d94c13dc9871.png)

**Comment by hprobotic** [comment]
Hi, This issue has been resolved by run this command: `mvn -o clean package` before command above :)

**Comment by oskarth** [comment]
Closing the issue as it has been resolved.

**Comment by kuzdu** [comment]
I got the same/similar error. 

I cleaned the project but when I'm running `mvn -f modules/react-native-status/ios/RCTStatus dependency:unpack` 

I got:
> Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (default-cli) on project Messenger: Unable to resolve artifact.: Could not transfer artifact status-im:status-go-ios-simulator:zip:develop-gad9a877 from/to ci.status.im (http://139.162.11.12:8081/artifactory/libs-release-local/): Connect to 139.162.11.12:8081 [/139.162.11.12] failed: **Operation timed out**

So the following link is dead: [http://139.162.11.12:8081/artifactory/libs-release-local/status-im/status-go-ios-simulator/develop-gad9a877/status-go-ios-simulator-develop-gad9a877.zip](url)

Does anybody know a solution for this?

**Comment by hprobotic** [comment]
@kuzdu use my solution above

**Comment by kuzdu** [comment]
Oh I did.

In my folder ´myUser/RCTStatus´ I execute `mvn -o clean package` 
Then I receive following messages
![cleanresult](https://user-images.githubusercontent.com/7271766/33114662-2a1f73e0-cf5e-11e7-94b2-2d110d0c15a2.png)

After that I execute `mvn -f modules/react-native-status/ios/RCTStatus dependency:unpack`

But I doesn't work because the `**Operation timed out**`

**Comment by oskarth** [comment]
@kuzdu Sorry about this, we had a lot of issues with Artifactory recently which likely caused the timeouts. Can you try again please?

**Comment by Saemy1** [comment]
for mac users, at least at my end, it works only when I add /pom.xml:

`mvn -f modules/react-native-status/ios/RCTStatus/pom.xml dependency:unpack`

**Comment by Jonathansoufer** [comment]
Leaving here just for historical purpose. Everything you need to build the app is found here: https://status.im/technical/build_status/

**Comment by pavunato** [comment]
@Saemy1 Actually the pom.xml was ignored from git. How can I generate pom.xml?
