### ISSUE TITLE
"Anonymous" vs address/public-key

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#225]
In which cases do we need to display "Anonymous" label instead of address/public-key? Do we need to display this label anywhere? 
Now the situation is a bit strange — we sometimes display "Anonymous" and sometimes display address for the same user in different parts of the app. As for me, "Anonymous" label looks much better, but we definitely need to work on uniformity.

**Comment by jarradh** [comment]
How will "Anonymous" stack up ie "Anonymous", "Anonymous 1", "Anonymous 2" etc.. 
public key imo is more apt, even if uglier.

**Comment by jarradh** [comment]
lets use public key #298
