### ISSUE TITLE
Phone number is not updated in profile and shows 'Not Specified` value if use /phone command

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2256]
### Description

*Type*: Bug

*Summary*: No phone number is shown in user profile after providing a valid phone number in Console and entering correct confirmation code

#### Expected behavior
Phone number is set or updated each time after user provides a phone number for /phone command in Console
#### Actual behavior
No phone number is shown in user profile after providing a valid phone number in Console and entering correct confirmation code. Field shows "Not Specified" string

### Reproduction

- Open Status
- Open Console
- tap on /phone command and type valid phone number you have access to
- wait for confirmation code to arrive to that phone number
- Tap on message "Thanks! we've sent you a text message..." to get /confirmation-code command in the input field
- type confirmation code and send
- agree to provide acces
- after Success message open user Profile and check field "Phone number" (epxected that provided number will be there) 

### Additional Information
* Status version: release 0.9.12 branch  0.9.10-292-g88326d4b
* Operating System: 
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0

**Comment by asemiankevich** [comment]
Confirmation code is not arriving in `0.9.10-351-gc9c5c579+` Reflected in https://github.com/status-im/status-react/issues/894
