### ISSUE TITLE
Info about an address is shown for Add new contact where only public key is used 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2259]
### Description

*Type*: Bug

*Summary*: Info about an address is shown under public key field on screen Add new contact. This might be confusing for a user because the screen contains no address. Would expect that or we explain what is public key or just remove the info what is an address on this screen.

![screenshot_20171021-103346](https://user-images.githubusercontent.com/6584810/31850003-ec004416-b64b-11e7-84b8-54e4a186549a.png)

### Reproduction

- Open Status
- Add new user
- Read text on screen Add new contact

### Additional Information
* Status version: release branch
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0
Real device Samsung Galaxy S6, android 6.0.1

**Comment by oskarth** [comment]
Fixed in develop and merged to 0.9.12 branch
