### ISSUE TITLE
wrong etherscan url on screen Transaction details

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2260]
### Description

*Type*: Bug

*Summary*: Wrong url is shown in menu for Transaction screen
![1963](https://user-images.githubusercontent.com/6584810/31850229-f5711702-b64e-11e7-9d44-9154249d8712.jpg)

Expected: etherscan url depends on the network we use, it can be:
- https://ropsten.etherscan.io/
- https://rinkeby.etherscan.io/
- https://etherscan.io/

### Reproduction

- Open Status
- Open Wallet -> Transactions -> History with at least 1 transaction
- Tap on Transaction to open its details screen
- tap on "3 dots" icon to open a menu and check the option "open on etherscan" for the text  0.9.11d293

### Additional Information
* Status version: branch 0.9.12, 0.9.11d293
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0
Real device Samsung Galaxy S6, android 6.0.1

**Comment by sla-shi** [comment]
We changed to Etherscan.io to help user realize that this command will result a web page to open, it's non intended to display the full URL.
