### ISSUE TITLE
New DApp descriptions are not shown on DApp profile in Discover 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2262]
### Description

*Type*: Bug

*Summary*: default_contacts.json contains new descriptions for some of the DApps (ones used on Discover -> DApps) but if open the profile of any Dapp from Discover section then there is old text "Description goes here" instead of new string
<img width=320 src=https://user-images.githubusercontent.com/6584810/31850576-ccabef12-b654-11e7-9df2-004292d0f0b2.jpg />

Expected to see new strings from default_contacts.json e.g. for 
For Oaken Water Meter: `Project Oaken is a secure, autonomous, machine to machine IOT platform built to provide the underlying infrastructure needed to power smart cities`

### Reproduction

- Open Status
- Open Discover
- In section Dapps tap on any icon, e.g on Oaken Water Meter. DApp profile will be opned
- Check the text in Description section

### Additional Information
* Status version: branch release 0.9.12  0.9.10-293-g0ebd4fbd
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0
Real device Samsung Galaxy S6, android 6.0.1

**Comment by sla-shi** [comment]
@goranjovic can you pls check if DApps descriptions correctly propagated here from the JSON file https://github.com/status-im/status-react/blob/bd7f256e8383a03af5c89059a1c6d16708526dd4/src/status_im/ui/screens/discover/dapp_details/views.cljs#L45
