### ISSUE TITLE
Wrong username shown in author box on incoming statuses in Discover

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2270]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I don't want to see statuses attributed to wrong authors.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

#### Expected behavior
Author's name in incoming statuses seen in Discover is the username of the user who actually posted the status.

#### Actual behavior
Author's name is incorrect and belongs to another recipient's contact

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Prepare 3 devices and/or simulators: A, B and C (tested with android real, ios simulator and ios real)
- Add them to each others contacts (all to all)
- Post a Status by A
- A should see it as own status, B and C as A's status
- Post a status by B
- B should see it as own status, A as B's, but C as A's
- Post a status by C
- C should see it as own status, A as B's, but B as A's

### Notes:
- ~The exact order of who gets to see the correct or incorrect author may differ - seems to be random.~
- The new status always gets both author name and identicon of the previously received status
- When recipient posts a new status, screen is updated to show correct authors for the received ones.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 95d2a6b1ee013c7f0bfa10e71344d67393ded54d
* Operating System: both

Found during a test session with @asemiankevich along with #2230 - initially thought they were related.

**Comment by asemiankevich** [comment]
marked as tested ok as I can't catch thois behavour for now in latest develop
