### ISSUE TITLE
Overwrite default contacts with default_contacts.json (incl descriptions)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2276]
### User Story

As a developer, I want to be able to change `default_contacts.json` and have changes show up in app without having to write custom, time-consuming and error-prone migrations.

As a user, I want default contacts description to be up to date.

### Description

*Type*: Feature

*Summary*: See https://github.com/status-im/status-react/pull/2267 for PR that partially fixes this. Previous issue is https://github.com/status-im/status-react/issues/2262.
Three possible solutions:

- Fix prepare-default-contacts-events and update-pending-status to overwrite default contacts - unclear what implications this has, especially wrt pending? contact
- Manual migrations for all descriptions in Realm (seems ugly to me)
- Leave it as it is

#### Expected behavior
Changing `default_contacts.json` should update dapp details.

#### Actual behavior
It doesn't because default contacts aren't updated once they've been imported.

**Comment by oskarth** [comment]
At second thought, perhaps some form of migration is preferable. There is a bunch of info in `contacts/contact` that we might not want to migrate.

**Comment by alwx** [comment]
I think that we can leave it as it is for now because we will need to find a better way to share information about new dapps in the future anyway. Maybe in the form of "DApps Marketplace" or even sharing using "Discover", but `default_contacts.json` looks more like a workaround, that is not perfect, has limitations, but works.

Just my opinion, of course.

**Comment by oskarth** [comment]
@alwx We need it for some devcon stuff. Agree we want a better way to share information about new dapps in the future.

**Comment by oskarth** [comment]
I forgot what the state of this was. Removing myself and leaving it open for now. Possibly it's been solved already, or that it can be closed.
