### ISSUE TITLE
Migrate ns chat to ui.screens.chat

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2284]
### User Story

As a developer, I want to have all UI related ns in `ui.screens`. `chat` is the last one to migrate

*Type*: Bug

**Comment by flexsurfer** [comment]
and rename files according to https://wiki.status.im/Refactoring_Guidelines

**Comment by flexsurfer** [comment]
and maybe move bots and commands into chat

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf4da6841d1d0e47b46781b15ae47a0661f7148266acdad2596e2c0be36c1710f](https://etherscan.io/tx/0xf4da6841d1d0e47b46781b15ae47a0661f7148266acdad2596e2c0be36c1710f)

**Comment by janherich** [comment]
I'm against the idea at this point - we have `experiment/new-protocol-app` branch with potentially huge gains to be made in perf + protocol layer code quality and any cosmetic changes like this will make it super hard to rebase that branch.
I mean, I agree it would be nice to move it to that ns for consistence sake, but now (in coming ~2 weeks) it's particularly poor time to do it.

**Comment by andytudhope** [comment]
OK, will not fund this bounty for now then. @jeluard do you have any rebuttal? 😉

**Comment by jeluard** [comment]
Sure let's delay that.

@janherich  Can we make sure the `protocol` part is as much as possible decoupled from the UI part of the `chat` ns?

**Comment by janherich** [comment]
@jeluard Sure, that's what we are actually doing there - current situation where you for example call  protocol functions from chat event namespaces and have to extract and pass`web3` object to them is just crazy - that's something which is purely the responsibility of transport (protocol) layer.
