### ISSUE TITLE
Push Notifications: Use status-go NotifyUsers instead of Notify

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2287]
As a developer, I want to use the most up to date version of a status-go API call to have access to the additional capabilities it provides.

As a far first step, introduce bindings for and use  `func NotifyUsers(message, payloadJSON, tokensArray *C.char) (outCBytes *C.char)` rather than `func Notify(token *C.char) *C.char`.

*Checklist*:
- [ ] Android Java bindings
- [ ] iOS ObjC bindings
- [ ] Replace `notify fcm-token` with `notify-users ...`

*Acceptance criteria*:
- Exercise NotifyUsers API parameters and make sure it shows up properly (i.e. payloadJSON unencrypted test).
- Replace usage of Notify with NotifyUsers, without regressions

*Future work*:

Use the improved capabilities to create a better UX (notification payload, data payload, multi-PN, etc). Requires thinking about encryption and permission model. This will be tracked in separate issues.

*Type*: Feature

**Comment by oskarth** [comment]
Note to self: this is not on critical path right now but want this done at some point. Right now it requires too much context and access to special environments (Firebase). This should probably be paired down in terms of scope and formulated as an open bounty.

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0xa66ce5fb7430bfe55b6e5b1d36ae0f88e836ed39](https://ropsten.etherscan.io/address/0xa66ce5fb7430bfe55b6e5b1d36ae0f88e836ed39)
![QR Code](http://7d1f0959.ngrok.io/qr/status-im/status-react/bounty/2287/0455cafe699f636d2c01f5f1784b9858141784a8d675ffd5ff5c606123ce6921/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [http://7d1f0959.ngrok.io](http://7d1f0959.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.

**Comment by pedropombeiro** [comment]
Starting to work on this.

**Comment by oskarth** [comment]
Thanks @PombeirP, let me know if you have any questions.

**Comment by pedropombeiro** [comment]
Thanks @oskarth! This is the first time I've had contact with ClojureScript, or any LISP-inspired language for that matter, so I'd welcome any input as to whether I'm killing any baby seals here :-)

Could you please take a look at my commit, and check if I'm going in the right direction? https://github.com/PombeirP/status-react/commit/971a506df1b13921212c89dbd61a8d4004ee1c5b

For the [payload](https://github.com/PombeirP/status-react/commit/971a506df1b13921212c89dbd61a8d4004ee1c5b#diff-d20f50de78d011b1377e718e4c82fbb5R75), I'm not sure how/if it's being used, so I don't know what we should be passing for the values.

**Comment by oskarth** [comment]
@PombeirP without looking at it in detail, in general it seems like the right direction! If you open a PR I can review more thoroughly.

Payload: I forgot exactly how this worked, but right now we aren't using it due to end to end encryption concerns (Firebase untrusted and unclear interception for Android and iOS). For now we just want to make sure some payloadJSON shows up in e.g. console logs on receiving end. Input can be a simple CLJS/JS map of hardcoded nonsense data, unless status-go requires a specific format. Once QA has checked this we can disable this in PR before merging.

**Comment by pedropombeiro** [comment]
@oskarth OK, the current code should be fine then, since I see the data from the CLJS side appear on the Android side logs. I'll create a PR then, thanks!
