### ISSUE TITLE
No margin between text and screen edges for hashtag search results

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2290]
### Description

*Type*: Bug

*Summary*: There should be some margin, now it's too close to the screen edge
![img_2439](https://user-images.githubusercontent.com/6584810/31937341-5c7b9a32-b8b4-11e7-8408-b0c09dc8c61a.jpg)

### Reproduction

- Open Status
- Open Discover with some hashtag
- Search for that hashtag -> search result screen will be shown

**Comment by flexsurfer** [comment]
not only left, top too

**Comment by oskarth** [comment]
@flexsurfer yes, did this too

**Comment by annadanchenko** [comment]
tested ok in develop for 0.9.12
