### ISSUE TITLE
Public chats in discover: create list of chats that can be opened and explain how to join any public chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2292]
### Description

*Type*: Bug

*Summary*: Currently, Public chats in Discover can't be used. We need
1) Create a list of predefined public chats that user will see, e.g #status #ethtrader
2) make it possible to open public chat when user taps on the chat title in Discover, so user joins a chat and can start typing/reading
3) explain to the user how to join any public chat (by typing it's name as topic in Join public chat)the
### Reproduction

- Open Status
- Open Discover
- In section Public chats check the list of chats
- tap on any of them -> public chat with that topic should open, so user can start typing or reading

**Comment by sla-shi** [comment]
@andytudhope would you follow up with the copy after we have the design update?

**Comment by annadanchenko** [comment]
quick fix to show and open 3 public chats from discover is OK.
We still need some some text line to explain there how to join other public chats.

**Comment by asemiankevich** [comment]
Moving to Tested assuming new issue will be created to track the progress of adding Public Chats descriptions and some onboarding things for users as commented above

**Comment by oskarth** [comment]
New issue created; closing this one.
