### ISSUE TITLE
[RFC] Improve developper experience

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2294]
The goal of this RFC in to pinpoint the different tasks that will need to be tackled in order to improve the developer experience on the status-react project.

The idea is that each comment to this issue should be edited in that first post and once a consensus is reached we can create an epic out of this RFC.

### Rationale

Some coeffects are passed as function, that is not how coeffects are suppose to work, they should be passed as data.

This is important because it makes it easier to work on and debug events who gets coeffects as data rather than function. Also the fact that a coeffects actually provides a function is confusing, especially if we want to have more new  developpers joining in.

https://github.com/status-im/status-react/blob/2e57d476a825742863bbd416862b7b69f08e3672/src/status_im/chat/events.cljs#L30-L33

There is also some coeffects that are unnecessary because the data is already in the app-db:

### Execution

This repo can give exemples of how to do parametrized coeffects https://github.com/deg/re-frame-storage-fx/blob/master/src/com/degel/re_frame/storage.cljs

- [ ] create issue

### Rationale

This is important because right now the mix of old/new style of events is confusing and the old style is harder to test. It will enable the next step which is to have way more tests

- [ ] Remove the last u/side-effects to finish transition to more idiomatic re-frame application

### Rationale

It is necessary because there is a known issue with XCode 9 and the old version of realm that we are using.
Also it is the database which is an important component of the application so it makes sense to use it properly and update it regularly to be able to quickly respond to security patches for instance.

### Execution: Update realm usage 

- [ ]  modify, deleted data as effects
- [ ]  get data as coeffect

This repo can be useful https://github.com/deg/re-frame-storage-fx/blob/master/src/com/degel/re_frame/storage.cljs

### Execution: update realm 

- [x] Issue https://github.com/status-im/status-react/issues/1926
- [x] PR https://github.com/status-im/status-react/pull/2236

### Rationale

This is annoying because a figwheel reload is basically useless. It will be even more important once we can start the app where we want because we can then fix the red screen and figwheel reload get us back there without any further action. But until this is fixed it won't be possible when trying to connect to an account after a red screen and figwheel reload, I always get this node is already running error when connecting to an account

### Execution

- [ ] create issue

#### Goal

As a developer I want to be able to start the application with a specific configured state
a configuration file should allow me to choose the account, the screen and the initial app-db I want to work with.

I can see this also being useful for onboarding, a new developper could quickly get to work on a feature if we provide him with the configuration file and mockup of the feature he has to work on.

#### Current situation

As a developper I have to login and go to the screen I am working on manually everytime I restart the application
If the data is deleted I also have to recover the account and add contacts, messages and so on to recover the state I was working on.

### Execution

- [ ] create issue

### Rationale

We should not duplicated fields in the app-db, subscription are cached, map lookups have a negligeable cost, so duplicating a field to make it "more accessible" is just a potential source of potential inconsistency and additional refactoring burden

### Execution

- [ ] create issue
 
## Update react/react-native and tolling

This one is last because it is huge. I have already done part of it in https://github.com/status-im/status-react/pull/2217

There is multiple issues with that upgrade

### from 0.47 there is a breaking change preventing most deps from compiling
the easy fix is to upgrade them, most patched this but only in their later version, which introduces more breaking changes, for instance splash screen changed it's package name

### some of status deps are owned by us and not updated yet
I patched all of them to make it work and I still need to submit PRs but some are referenced by github repo iirc so that would be a issue if it is merged in their master because the builds with old react won't work, I don't think the fixes are retro compatible

### nodify doesn't seem to work anymore
apparently we are using some modules from node which were ported in react-native with a hack and it doesn't seem to work anymore, that is the current state of my PR, stucked on an issue with the module "child_process"

### this effort could be merged with upgrade to reagent 8 and latest cljs
when reagent 8 will be out of alpha we should upgrade. It makes uses of the latest cljs functionnality which makes it possible to require npm dependencies in the project.clj file and require the modules in the ns form which will clean up our code a bit and simplify the tooling and building of the app for newcomers.

## Get devtools to work

I don't know if I am the only one but when trying to use the remote dev tools I never get passed the login because it is too slow

**Comment by rasom** [comment]
> Some coeffects are passed as function, that is not how coeffects are suppose to work, they should be passed as data.

please add links to examples

**Comment by janherich** [comment]
Example of `:coxf` containing function instead of data: https://github.com/status-im/status-react/blob/develop/src/status_im/chat/events.cljs#L31

The problem here is that the coeffect is dynamic, eq dependent on the event parameter/s and `inject-coeffect` middleware is executed at the event registration time.

So standard parametric coeffects can't be used in this case, because the data is looked up upon parameter unknown at the event registration time.

I still think it's better to have those function coeffects rather then no coeffects, this way, at least the dependencies of the handler are stated explicitly and you don't have to mock/re-define symbols during unit testing, you just pass some deterministic function for the coeffect, instead of the "real" one.

The only way how I can see this could be solved is with some custom middleware for injecting coeffects and I don't know if it's worth the effort.

**Comment by jeluard** [comment]
Great plan!

About `start the app in a specific state`: in case of exception / crash we could also dump users `app-db` and push them somewhere (if they agree).
