### ISSUE TITLE
Transaction cards are too close to edges in 1x1 or group chat on small screens

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2303]
### Description

*Type*: Bug

*Summary*:  `/send` cards (messages) appear too close to screen edges on iPhone 5S

#### Expected behavior
Card should take less space on small screens

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/31998087-22e35c68-b997-11e7-881a-e18879322f96.png)

### Reproduction

- As A: Create 1x1 chat or group chat with a contact (B) who runs app on small screen (5S for example)
- As A: Send transaction with 8 or more digits after comma
- As B: open chat and pay attention to `/send` cards 

### Additional Information
* Status version: `0.9.12` release build 0.9.11d314-1557.314
* Operating System: iOS

**Comment by annadanchenko** [comment]
acceptance is not clear: what is the exact solution for the message to take less space if screen is too small and number is too long to fit? should we show less digits after comma or round it or show dots? It's a generic decision for all sums we are going to show. Maybe we can have some design solution to show that there is some "not-shown" part of the message with too long number? @pablanopete right now it's not ready for the bounty: acceptance criteria is not clear.

**Comment by annadanchenko** [comment]
with new design for send/request messages can't repro on jun 17 nightly build. Used iphone 5s
