### ISSUE TITLE
Add descriptions to Public chats and some tips for users how to join other public chats

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2305]
### Description

*Type*: Bug

*Summary*: As a second part left for the issue https://github.com/status-im/status-react/issues/2292 we want to add some description to public chats and some guidance to the users how to join another public chats (part of onboarding process). This issue perhaps requires input from design team

#### Expected behavior
User can understand the purpose of any public chat present in Discover tab as well as join it quickly.

### Reproduction

- Open Status
- Open Discover
- In section Public chats check the list of chats
- tap on any of them -> public chat with that topic should open, so user can start typing or reading

### Additional Informatio
* Status version: last seen in release candidate `0.9.12`
* Operating System: Android, iOs

**Comment by oskarth** [comment]
cc @denis-sharypin

**Comment by annadanchenko** [comment]
Discover feature is removed
