### ISSUE TITLE
Cannot chat with non-contacts from Discover

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2306]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want Chat button to work and to allow me to chat with another user.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

#### Expected behavior
Tapping on Chat button in Discover allows the user to chat with the author of the status.

#### Actual behavior
Chatting is only possible with contacts. It is offered but not possible for non-contacts - a chat with an invalid username appears.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Set up 3 devices: A, B and C
- A and B add each other to contacts
- B and C add each other to contacts
- A posts a new status with hashtag
- B sees it in Discover almost immediately
- C sees it in Discover after around 10 minutes
- C taps chat on the discovered status
- C swipes to chats - there is a new chat with "Revolving Wide Pikeperch" (should be A)
- There is no new chat on A's device
- When C sends text messages to Revolving Wide Pikeperch, none are received by A

The additional manifestation of the same bug is that when you click either user image or username in the discovered status for any user who is not in your contacts (including yourself), you'll get an empty profile screen. This was caught here: https://github.com/status-im/status-react/issues/1996#issuecomment-348455987

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

The solution is to either:
- make it possible to chat with non-contacts
- change the Discover call to action from "Chat" to "Add" for non-contacts

Possibly related to #2230 

### Additional Information
* Status version: develop
* Operating System: both

**Comment by annadanchenko** [comment]
Discover feature is removed
