### ISSUE TITLE
Reworked jail calls throttling/chunking/de-duplicating

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#2310]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to haw easy way to specify jail call throttling/chunking/de-duplicating so that whenever I need to do that, I can just use already prepared primitives which are tested/known to work without problems..

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Primitives for jail call throttling/chunking/de-duplicating
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
jail call throttling/chunking/de-duplicating is achieved by easy to use encapsulated primitives which are unit tested
#### Actual behavior
[comment]: # (Describe what actually happened.)
jail call throttling/chunking/de-duplicating is achieved using one-off not reusable piece of code which is not unit-tested
### Steps to test
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open any chat
- Type `/send` command and edit the amount/fee slider, everything should work smoothly and correctly (no regression)

**Comment by rasom** [comment]
ready for testing in develop
