### ISSUE TITLE
Password message in Console is shown as plain text when upgrading 0.9.11 to 0.9.12

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2315]
### Description

*Type*: Bug

*Summary*: Security issue - password message is shown as plain text afyer upgrade

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/32102347-8e8a1acc-bb24-11e7-89f5-05d7b0bb17ec.png)

### Reproduction

- Install 0.9.11 version and set up account
- Upgrade to 0.9.12 from google play
- Check password message in Console

### Additional Information
* Status version: release 0.9.12
* Operating System: Android, iOS

**Comment by rasom** [comment]
ready for testing in develop
