### ISSUE TITLE
New status from the same sender should overwrite any old ones

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2317]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user (status recipient in Discover)  I only want to receive the most recent and accurate statuses from my contacts and other participants in the network.
As a user (status author) I want to be able to overwrite my current status at any time by creating a new one that will replace it in all nodes it eventually reaches.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

#### Expected behavior

1. User A writes a status S1 with a hashtag 
2. His contacts and and their contacts see S1 in Discover
3. User A writes another status S2 - also with a hashtag
4. All of his contacts and their contacts eventually see S2, but don't see S1 any more

#### Actual behavior

1. User A writes a status S1 with a hashtag 
2. His contacts and and their contacts see S1 in Discover
3. User A writes another status S2 - also with a hashtag
4. All of his contacts and their contacts eventually see S2, but also see S1 in Discover

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:  Basically, whenever any account receives a new status from a user, that status should be saved in the discoveries, but any previous statuses from the same user should be removed.

* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: both

**Comment by annadanchenko** [comment]
Discover feature is removed
