### ISSUE TITLE
Generate username as Unknown instead of "Revolving Wide Pikeperch" for nil public key

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2329]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer or tester I want to easily recognize an invalid state (public key being nil) 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: Default Status user names are deterministically generated using public key as the seed. That means that every public key has a corresponding combination in format _adjective adjective animal_. In case that the supplied public key is nil or 0, that combination is "Revolving Wide Pikeperch".

Public key being nil or zero is already an invalid state, so in normal circumstances this should never happen. However, if or when it does the generated name should be something that more obviously shows that the contact info is not valid, e.g. __Unknown__

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Acceptance criteria*: 

- Function `generate-gfy` evaluates to Unknown when supplied with zero or nil
- Unit tests to verify the correct behavior are in place.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x6c4878a773e758494cff541c31b58e7fa9fd43aa](https://etherscan.io/address/0x6c4878a773e758494cff541c31b58e7fa9fd43aa)
Network: Mainnet
Paid to: mlahia
