### ISSUE TITLE
Translate App Strings to Ukrainian

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2334]
### User Story

As a Ukranian language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Ukrainian to translate all the latest strings in Status from English. We would like to invite our community members to take on these tasks in order
a) To become a bit more acquainted with the Status repos and perhaps wander further into the codebase and set of issues we need help with, earning yourself Open Bounties all the way down this rabbit hole, and
b) To make sure that the product we deliver has been built by the same community that uses it, in a virtuous feedback loop of increasing understanding and value-generation.

#### Expected behavior
The Ukrainian translation ought to be as up-to-date as the English one.

#### Actual behavior
We have not yet updated it, preferring to leave this open as an opportunity for our community to get involved again.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/uk.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).
- How you translate is a matter of your preference. There were significant updates to the English file for the 0.9.12 release, with lots of strings both add and REMOVED. We need you to make sure that the files are exact mirrors of each other, except in different languages.
- It might be easier to simply take the new English file and translate from scratch rather than going through the current translated files line by line (though we leave this up to you).

### Additional Information

* Status version: 0.9.12+

There are bounties available for these translations. Please see the QR codes that will be added below after the DevCon 3 announcement.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0xa4862be7d3e27781cfe5393af1c4a3ae0a419f3b](https://etherscan.io/address/0xa4862be7d3e27781cfe5393af1c4a3ae0a419f3b)
Network: Mainnet
Paid to: dyrkin
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by SteengraySS** [comment]
as a native inhabitant of Ukraine and a native speaker, I want to participate in this task

**Comment by MrVuuu** [comment]
How to claim bounty?

**Comment by andytudhope** [comment]
Hi @MrVuuu. The PR submitted here: https://github.com/status-im/status-react/pull/2362 was slghtly better/more accurate than yours. However, there are still a bunch of comments needing to be fixed on ti and the original contributor seems to have lost interest. If you'd like to rebase onto his branch, fix the outstanding review comments and submit, then you'll likely be awarded the bounty.

**Comment by Lvivyanyn** [comment]
I am a native Ukrainian speaker and I would like to participate.

**Comment by tomohavvk** [comment]
I am a native Ukrainian speaker and I would like to participate. I found some spelling errors, I want to help you in fixing them. Please approve.

**Comment by mixeliusini** [comment]
I am a native Ukrainian speaker and I would like to participate too. Is the bounty still relevant?
