### ISSUE TITLE
Translate App Strings to Swedish

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2335]
### User Story

As a Swedish language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Swedish to translate all the latest strings in Status from English. We would like to invite our community members to take on these tasks in order
a) To become a bit more acquainted with the Status repos and perhaps wander further into the codebase and set of issues we need help with, earning yourself Open Bounties all the way down this rabbit hole, and
b) To make sure that the product we deliver has been built by the same community that uses it, in a virtuous feedback loop of increasing understanding and value-generation.

#### Expected behavior
The Swedish translation ought to be as up-to-date as the English one.

#### Actual behavior
We have not yet updated it, preferring to leave this open as an opportunity for our community to get involved again.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/sv.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).
- How you translate is a matter of your preference. There were significant updates to the English file for the 0.9.12 release, with lots of strings both add and REMOVED. We need you to make sure that the files are exact mirrors of each other, except in different languages.
- It might be easier to simply take the new English file and translate from scratch rather than going through the current translated files line by line (though we leave this up to you).

### Additional Information

* Status version: 0.9.12+

There are bounties available for these translations. Please see the QR codes that will be added below after the DevCon 3 announcement.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x30e8e32b63e50cc1dd65d1b8419e013d776aa3ec](https://etherscan.io/address/0x30e8e32b63e50cc1dd65d1b8419e013d776aa3ec)
Network: Mainnet
Paid to: pafcu
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by Legogris** [comment]
Your link is pointing to the Swahili file, Swedish is here: https://github.com/status-im/status-react/blob/develop/src/status_im/translations/sv.cljs

Just so that Swahili doesn't get overwritten.

**Comment by andytudhope** [comment]
Haha, totally my bad, thanks for the catch @Legogris!

**Comment by pafcu** [comment]
@andytudhope Feel free to check my PR if you feel something could be rephrased or improved.
