### ISSUE TITLE
status.response doesn't seem to work

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#2342]
`status.response` doesn't work in either the demo_bot file or this one (https://gist.github.com/gretzke/c71fb7d57f67ef068c3570d48e5086b0) that a user is currently working on. 
Was working before, but something seems to have broken with the latest release.

**Comment by alwx** [comment]
Closed because it's fixed here: https://github.com/status-im/status-react/pull/2409

**Comment by janherich** [comment]
@alwx responses has not been removed, they are now only treated in the same way as normal commands and are working. But you are correct that we can close this, because it will be solved in develop soon.
