### ISSUE TITLE
Translate App Strings to Chinese (Shaghaiese zh_wuu)

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2343]
### User Story

As a Shaghaiese language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Shaghaiese to translate all the latest strings in Status from English. We would like to invite our community members to take on these tasks in order
a) To become a bit more acquainted with the Status repos and perhaps wander further into the codebase and set of issues we need help with, earning yourself Open Bounties all the way down this rabbit hole, and
b) To make sure that the product we deliver has been built by the same community that uses it, in a virtuous feedback loop of increasing understanding and value-generation.

#### Expected behavior
The Shaghaiese translation ought to be as up-to-date as the English one.

#### Actual behavior
We have not yet updated it, preferring to leave this open as an opportunity for our community to get involved again.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/zh_wuu.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).
- How you translate is a matter of your preference. There were significant updates to the English file for the 0.9.12 release, with lots of strings both add and REMOVED. We need you to make sure that the files are exact mirrors of each other, except in different languages.
- It might be easier to simply take the new English file and translate from scratch rather than going through the current translated files line by line (though we leave this up to you).

### Additional Information

* Status version: 0.9.12+

There are bounties available for these translations. Please see the QR codes that will be added below after the DevCon 3 announcement.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 2000.00
Contract address: [0x939c0f124e161ad1c72815c1aec82db038040c97](https://etherscan.io/address/0x939c0f124e161ad1c72815c1aec82db038040c97)
Network: Mainnet
Paid to: pablanopete
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by difengJ** [comment]
is this for Cantonese or Shaghaiese

**Comment by andytudhope** [comment]
Shaghaiese - although if you join our chat.status.im, I am sure I can make a plan to get a bounty going for Cantonese if that is your language?

**Comment by foreseaz** [comment]
@andytudhope , from the User Story it says "as a Cantonese speaker", so is this issue for Cantonese translation (but your response to @difengJ said it's for Shanghaiese, which is zh_wuu).

I live in Hong Kong for a long time and more than happy to help translate to Cantonese (zh_hk)

**Comment by andytudhope** [comment]
Hi @foreseaz! Thanks for picking that up - have edited it. We don't really have anyone on the team who can verify a Cantonese translation but would love for you to do it. Is there anyone with an active/verifiable GH profile that you could convince to review your work? If so, I can organise a bounty for you?

**Comment by foreseaz** [comment]
@andytudhope Thanks for your response, may I know GH profile stands for?

**Comment by andytudhope** [comment]
Sorry, GitHub profile. We generally tend to look more kindly on contributor's who are active here and have submitted open source code to various repos before.

**Comment by foreseaz** [comment]
@andytudhope noticed, I will try to find an active friend as the reviewer. 
Btw, I also saw the traditional Chinese [zh_hant](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/zh_hant.cljs) is already there, which is fairly enough for Taiwan, Hong Kong, Macau and Singapore / Malaysia for now. According to [Comparison of national standards of Chinese](https://en.wikipedia.org/wiki/Comparison_of_national_standards_of_Chinese#Linguistic_differences) so it may not necessarily open a bounty only for Hong Kong Traditional Chinese now, I suggest open a bounty for standardization of different Traditional Chinese right before version 1.0.
Thanks for your response, I also joined the Riot group as @foreseaz, ping me anytime for any enquiries.  :）

**Comment by andytudhope** [comment]
Hi @foreseaz - if you could create an issue for what you would want to see in the standardization of different traditional Chinese, that'd be great (it's not a strong suit of mine, unfortunately). Then I can assign a bounty once discussed with the rest of the team.

**Comment by foreseaz** [comment]
@andytudhope [issue](https://github.com/status-im/status-react/issues/2528) created.
