### ISSUE TITLE
Translate App Strings to Lithuanian

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2351]
### User Story

```Please note: we have no speakers of this language on the team, so it's difficult to check the validity of translations. Therefore, on issues like this, we will wait for at least 2 PRs before merging anything (within a sane timeframe). If you submit a PR, please also justify why your translation is better than any that have previously been submitted, so we can make an informed choice about which to merge. In the case that we need to use elements of both, we will most likely reward bounties to both contributors, for making and verifying the translations.```

As a Lithuanian language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Lithuanian to translate all the latest strings in Status from English. We would like to invite our community members to take on these tasks in order
a) To become a bit more acquainted with the Status repos and perhaps wander further into the codebase and set of issues we need help with, earning yourself Open Bounties all the way down this rabbit hole, and
b) To make sure that the product we deliver has been built by the same community that uses it, in a virtuous feedback loop of increasing understanding and value-generation.

#### Expected behavior
The Lithuanian translation ought to be as up-to-date as the English one.

#### Actual behavior
We have not yet updated it, preferring to leave this open as an opportunity for our community to get involved again.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/lt.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).
- How you translate is a matter of your preference. There were significant updates to the English file for the 0.9.12 release, with lots of strings both add and REMOVED. We need you to make sure that the files are exact mirrors of each other, except in different languages.
- It might be easier to simply take the new English file and translate from scratch rather than going through the current translated files line by line (though we leave this up to you).

### Additional Information

* Status version: 0.9.12+

There are bounties available for these translations. Please see the QR codes that will be added below after the DevCon 3 announcement.

**Comment by ghost** [comment]
I updated the existing translation done before by me.
just waiting for bounty to be added as we spoke.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x7165fdbf2e976852e7d2413513794a23faaf87ab](https://etherscan.io/address/0x7165fdbf2e976852e7d2413513794a23faaf87ab)
Network: Mainnet
Paid to: poiga

**Comment by andytudhope** [comment]
@poiga you can now submit the PR to begin the claim process on this. Please see if you can find someone to verify/vouch for you translation. Please also make sure that you include the string `Fixes #2351` in your PR description so our webhooks can pick it up correctly. See here for how it's done: https://github.com/status-im/status-react/pull/2347

**Comment by ghost** [comment]
thanks, I am doing so.

**Comment by ghost** [comment]
coool.

**Comment by ghost** [comment]
i am Lithuanian

**Comment by poiga** [comment]
very good :) could you please check if the translation is good? thanks!

**Comment by realusinvestment** [comment]
thank you
