### ISSUE TITLE
Translate App Strings to Japanese

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2352]
### User Story

```Please note: we have no speakers of this language on the team, so it's difficult to check the validity of translations. Therefore, on issues like this, we will wait for at least 2 PRs before merging anything (within a sane timeframe). If you submit a PR, please also justify why your translation is better than any that have previously been submitted, so we can make an informed choice about which to merge. In the case that we need to use elements of both, we will most likely reward bounties to both contributors, for making and verifying the translations.```

As a Japanese language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Japanese to translate all the latest strings in Status from English. We would like to invite our community members to take on these tasks in order
a) To become a bit more acquainted with the Status repos and perhaps wander further into the codebase and set of issues we need help with, earning yourself Open Bounties all the way down this rabbit hole, and
b) To make sure that the product we deliver has been built by the same community that uses it, in a virtuous feedback loop of increasing understanding and value-generation.

#### Expected behavior
The Japanese translation ought to be as up-to-date as the English one.

#### Actual behavior
We have not yet updated it, preferring to leave this open as an opportunity for our community to get involved again.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/ja.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).
- How you translate is a matter of your preference. There were significant updates to the English file for the 0.9.12 release, with lots of strings both add and REMOVED. We need you to make sure that the files are exact mirrors of each other, except in different languages.
- It might be easier to simply take the new English file and translate from scratch rather than going through the current translated files line by line (though we leave this up to you).

### Additional Information

* Status version: 0.9.12+

There are bounties available for these translations. Please see the QR codes that will be added below after the DevCon 3 announcement.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0xa9d4cb6ad2f05e161d06f6ed2c56d79d959856d0](https://etherscan.io/address/0xa9d4cb6ad2f05e161d06f6ed2c56d79d959856d0)
Network: Mainnet
Paid to: dumiz
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by CrypoNinja** [comment]
hi, just update everything with a perfect japanese. but not sure the update was properly reflected. can you check it?

**Comment by t4sk** [comment]
@CrypoNinja Can you create a pull request? Once the pull request is created, you should be able to see "File Changed" link at the top of this page.

**Comment by CrypoNinja** [comment]
give me a couple of days, cuase i am traveling aisan islands where internet
is unstable. mikio

On Jan 4, 2018 3:30 PM, "Tasuku Nakamura" <notifications@github.com> wrote:

@CrypoNinja <https://github.com/cryponinja> Can you create a pull request?
Once the pull request is created, you should be able to see "File Changed"
link at the top of this page.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/status-im/status-react/issues/2352#issuecomment-355208708>,
or mute the thread

**Comment by dumiz** [comment]
Done the translation, please take a look
