### ISSUE TITLE
/phone command is not avaliable after upgrade from 0.9.12 build [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2376]
### Description

*Type*: Bug

*Summary*: After upgrade from 0.9.12 release to recent develop  `0.9.10-335-g55164b8e+ (1892)` I can't access `/phone` command. This command was hidden in `0.9.12` but we want to bring it back in next release. So we need to handle this case to let users who will upgrade their app to 0.9.13 (or any other release) add their phone numbers

#### Expected behavior
`/phone` command is avaliable after upgrade from 0.9.12 release

#### Actual behavior
`/phone` command is not shown

### Reproduction

- Istall 0.9.12 build (from google play for ex)
- Make sure /phone command is 
- Upgrade to develop `0.9.10-335-g55164b8e+ (1892)`

### Additional Information
* Status version:  0.9.10-335-g55164b8e+ (1892)
* Operating System: Android

**Comment by annadanchenko** [comment]
Phone feature is removed
