### ISSUE TITLE
Broadcast public chat discoveries

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2377]
### User Story

As a user I want to be able to discover public chats in which other users are participating, so that I can join the chat and engage the discussion.

### Description

*Type*: Feature

*Summary*: Apps need to broadcast open public chats so that those public chats are discoverable by other users.

*Workflow*:

1. Every app node needs to broadcast a list of all public chats currently open on that account to all its contacts.
2. Those contacts will broadcast its own open public chats and any other chats they received.
3. All public chat discoveries are stored in local database with public key as the primary key and a string array as the list of public chat identifiers.

Then those public chat discoveries can be aggregated by public chat identifiers and we can have a list of most popular public chats by number of participants. However that falls outside the scope of this particular issue, see #2378

**Comment by annadanchenko** [comment]
Discover feature is removed
