### ISSUE TITLE
Error undefined is not a function (evaluating 'e.remove()')

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2379]
### Description

*Type*: Bug

*Summary*: Error `undefined is not a function (evaluating 'e.remove()')` shown when adding `confirmation code` in latest develop 

#### Expected behavior
No errors

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/32444960-5cb90b86-c315-11e7-9a5c-e25099301aea.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- open Status
- using /phone command add phone number
- decline permissions when asked
- enter code from sms

### Additional Information
* Status version:  0.9.10-337-gdfe68a2d+ (1894)
* Operating System: Android

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/7035778/sessions/1/?accessToken=xhCIhTlDL6lOTmAv3zTXAUl3D6s

**Comment by oskarth** [comment]
@janherich @asemiankevich can this be closed?

**Comment by asemiankevich** [comment]
@oskarth this is still present in latest develop (reproduced as described). I noticed that error is a bit different though 
![image](https://user-images.githubusercontent.com/28752642/32839744-78649ebe-ca26-11e7-97eb-ebae0d6fb3bf.png)

**Comment by asemiankevich** [comment]
Reproduced as described in `0.9.10-377-g7c0ecef3+ (1934)` branch https://app.testfairy.com/projects/4803622-status/builds/7123488/sessions/1/?accessToken=YbrbkcUNUxaDTSXK2YZfmpEqtfE
http://prntscr.com/hd7mt4

**Comment by asemiankevich** [comment]
![image](https://user-images.githubusercontent.com/28752642/34340505-fc622fc2-e995-11e7-9464-da7422fb9125.png)
in  0.9.10-474-gc8168e9f+ (2031)

**Comment by asemiankevich** [comment]
closing this one as we dont have /phone command anymore
