### ISSUE TITLE
Update payment request support to ERC681

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2391]
### User Story

As a user, I want to be able to read / generate QR code following [ERC 681 standard](https://github.com/ethereum/EIPs/pull/681)

ERC67 support is currently implemented but it has been recently superseded by ERC681.

### Description

*Type*: Feature

**Comment by oskarth** [comment]
@jeluard @asemiankevich  Can this be closed?

**Comment by jeluard** [comment]
I think so yes.
