### ISSUE TITLE
Find an alternative to setTimeout for long timers

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2408]
#In the latest version of react-native there is a warning in Status regarding setTimeout:

> Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, amd timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
> (Saw setTimeout with duration 180000ms)

As far as I know this only concerns this line of code:
https://github.com/status-im/status-react/blob/edd4df85f95b42a459b9b189918c3b3f76102e3f/src/status_im/ui/screens/discover/events.cljs#L80-L82

`dispatch-later` is not a viable alternative because it uses setTimeout internally as well.

**Comment by jeluard** [comment]
It looks like the snippet mentioned above is not the only one triggering this warning.
To fully solve this issue we must ensure no more warnings are generated.

**Comment by jeluard** [comment]
`core-async` might be the culprit. Also note `dispatch-n` is not a viable alternative as it use `setTimeout` underneath.

Proposed solution should workaround all guilty `setTimeout` / `setInterval` with background timers (see [some details](https://facebook.github.io/react-native/docs/timers.html) and look for @yenda associated commit).

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 660.00
Contract address: [0xaa8ebd54c4d7fff5523b262fe107c406af5ddc71](https://etherscan.io/address/0xaa8ebd54c4d7fff5523b262fe107c406af5ddc71)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pablodip** [comment]
Confirmed that core async uses setTimeout internally: https://github.com/clojure/core.async/blob/master/src/main/clojure/cljs/core/async/impl/dispatch.cljs#L36

**Comment by foopang** [comment]
I am working on a fix now:)
