### ISSUE TITLE
"Insufficient funds" error at attempt to send ETH with sufficient funds on balance 

### ISSUE THREAD

**Issue by Chu127001** [status-im/status-react#2417]
### Description

*Type*: Bug

*Summary*:  cannot send 0.001 ETH using /send command in Chat because of "Insufficient funds" error after receiving ETH to own account (account balance is checked with https://ropsten.etherscan.io/, it was 0.1 ETH) before opening "Wallet" interface.

#### Expected behavior
I can send 0.001 ETH, because account balance is 0.1 ETH

#### Actual behavior
"Insufficient funds" error

### Reproduction

- Open Status app
- Login with existing user (balance is X ETH)
- Use /faucet command in order to receive 0.1 ETH
- Check balance on https://ropsten.etherscan.io/ (that 0.1 ETH are received, and current balance is X+0.1 ETH)
- Wait 5 min
- using /send command send X+0.001 ETH  to User B

### Solution
After opening "Wallet" section balance inside the app will be synchronized

### Additional Information
* Status version: 0.9.12
* Operating System: iOS 10.3.2

#### Logs
Video: http://take.ms/R5obd

**Comment by anna04test** [comment]
@Chu127001 for how long have you waited after balance is updated on etherscan and you try to send some funds with send command?

**Comment by Chu127001** [comment]
@anna04test approximately 5 mins

**Comment by asemiankevich** [comment]
removed this `bounty` label for a while - lets wait new branch for ERC20 support, Julien and Goran have made a lot of changes to Wallet so this may be fixed already

**Comment by jeluard** [comment]
Cannot reproduce with latest develop.

**Comment by churik** [comment]
reproducible with current release branch 0.9.13 (2080.21)

**Comment by jeluard** [comment]
Ok I now can reproduce the issue.
