### ISSUE TITLE
A message is not send to group chat, 'Assert failed' error is shown

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#2418]
### Description

*Type*: Bug

*Summary*:  A message is not send to group chat, an error is shown

#### Expected behavior
User should be able to send a message to group chat

#### Actual behavior
Can't send a message to group chat due to an error - "Assert failed: (valid? :message/ keypair keypair)

### Reproduction

- Open Status on 2 devices
- Set passwords from scratch for 2 new users (user_a, user_b)
- As 'user_a' add 'user_b' to contacts
- As 'user_a' create a group chat with 'user_b'
- As 'user_a' send a message to 'user_b' in the group chat
- As 'user_b' send a message to 'user_a' in the group chat

### Additional Information
* Status version: 0.9.10-363-g2ff2bfac+
* Operating System: Android

### Screenshot
<img width="616" alt="screen shot 2017-11-13 at 6 32 02 pm" src="https://user-images.githubusercontent.com/12611990/32737768-9e088506-c8a3-11e7-95b1-5ed3076c53fe.png">

**Comment by annadanchenko** [comment]
tf session with an issue: https://app.testfairy.com/projects/4803622-status/builds/7078681/sessions/3/?accessToken=OW4KgD7ksDf5QMJ2x7dikzeV/LI

**Comment by annadanchenko** [comment]
@antdanchenko `As 'user_b' send a message to 'user_a' ` should the message be sent in the newly created  group chat?

**Comment by antdanchenko** [comment]
@annadanchenko I think it should, however in my case there was a message from 'user_a' to 'user_b' before the message from 'user_b' to 'user_a', I am going to update the steps.

**Comment by annadanchenko** [comment]
it's still not clear from the steps if the message should be sent in 1-1 chat or in group chat, can you specify it please?

**Comment by antdanchenko** [comment]
In the group chat, description has been updated

**Comment by asemiankevich** [comment]
Fixed in `0.9.10-373-g16fcef90+`
