### ISSUE TITLE
"Description" is partly overlapped by "Save" button on  "Profile > Edit" screen (IPhone 5S, "Predictive" is enabled)

### ISSUE THREAD

**Issue by Chu127001** [status-im/status-react#2419]
### Description

*Type*: Bug

*Summary*: 
Last row in "Description" is overlapped by "Save" button, so user cannot see what he types. Scrolling to the bottom fixes text in the same state, so "Save" button covers last row.

"Predictive" option on IPhone settings  should be enabled.

#### Expected behavior
"Save" button does not overlap last row, "Description" is shown correctly

#### Actual behavior
Last row in "Description"  is overlapped by "Save"

### Prerequisites
- "Predictive" option should be enabled (Settings > General > Keyboard)

### Reproduction
- Open Status
- Login with existing account
- Open Profile
- Tap on Edit
- Fill up "Description" (more than 4 rows)

### Additional Information

* Status version: 0.9.12

* Operating System: IOS 10.3.2

*Device: IPhone 5s

![txt](https://user-images.githubusercontent.com/33398967/32740119-93e37dfe-c8aa-11e7-968b-1937f198a34b.png)

**Comment by ahmetmertugrul** [comment]
I can't see the third line because of the save button when I write in the profile biography box.

Video: https://drive.google.com/file/d/1u3_k4tT6SetAtHs-mQ6B0U_4WymB_IJf/view

    Status version: 0.9.12+

    Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by churik** [comment]
The same behavior for Iphone 5s:
![biogr_overlap](https://user-images.githubusercontent.com/4557972/34556645-d5da73ee-f13f-11e7-9b2b-d8fa60657fa4.png)

v0.9.11d499 (build with PR #2833)
