### ISSUE TITLE
Loading indicator instead of error is shown on "Send location" screen if location access is disabled for "Status" app

### ISSUE THREAD

**Issue by Chu127001** [status-im/status-react#2420]
### Description

*Type*: Bug
*Summary*: when user disables access to location and tries to send location in Chat (using /location command), he sees only loading indicator without any descriptive error
![location](https://user-images.githubusercontent.com/33398967/32741010-7625d246-c8ad-11e7-9f00-f1892d1012ef.png)

#### Expected behavior
Error or popup kind of "Enable location in Settings or type address manually"

#### Actual behavior
Only loading indicator is shown

### Reproduction
- Go to Settings > Status
- Allow Status to access Location > set "Never" (workflow for IPhone)
- Open Status
- Login with existing user
- Open 1-1 or Group chat
- Tap on /location command

### Additional Information
*Status version: 0.9.12
*Operating System: iOS 10.3.2

**Comment by annadanchenko** [comment]
Location command is removed
