### ISSUE TITLE
Null is not an object (evaluating 'e.substring') error when clicking /phone command

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2425]
### Description

*Type*: Bug

*Summary*: `Null is not an object (evaluating 'e.substring')` error when clicking /phone command

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/32771875-410fb9b8-c935-11e7-9f76-b26ee8bd2e91.png)

### Reproduction

- Open Status
- Create account
- Click `/phone` command

### Additional Information

* Status version: 0.9.10-360-g190e841f+ (1917)
* Operating System: Android

#### Logs
*TF (0.58) https://app.testfairy.com/projects/4803622-status/builds/7078352/sessions/5/?accessToken=7fvdrqYNb3Afk/dPpXSsxC4SsgU

**Comment by janherich** [comment]
@asemiankevich Is this still happening on develop ?

**Comment by asemiankevich** [comment]
its not happenin in `0,9.10-407-g2b8acc15+` develop, closing
