### ISSUE TITLE
Same transaction is multiplied on Unsigned screen as many times as user taps on [send]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2426]
### Description

*Type*: Bug

*Summary*: in 1x1 chat if I tap on [send] button when sending transaction many times the same txn will be multiplied in Unsigned screen even original one was proceeded. We have simialr issue with /request. I would say its a general problem - need to prevent multi-tapping right after user tapped on [send] once

on iOS Tapping multiple times on Send button makes the app unsuable. Go to 1x1 chat - > /request -> tap ~20 times green send button

https://app.testfairy.com/projects/4803622-status/builds/7170527/sessions/28/?accessToken=tsJMUzhy/tmn6-e-7ZTOenqfgc0

### Reproduction

- Open Status
- Go to 1x1 chat
- Call send command
- Enter valid values and tap green send button several times

OR 
- Open Status
- Go to 1x1 chat
- Call request command

### Additional Information

* Status version: 0.9.10-360-g190e841f+ (1917)
* Operating System: Android, iOS

#### Logs
TF : https://app.testfairy.com/projects/4803622-status/builds/7078352/sessions/9/?accessToken=6ROKNg2tagmBHVilaut8BfEgdyU

**Comment by oskarth** [comment]
Part of 55/Fast-status. @asemiankevich comment on it being a compact bad case:

> Tapping multiple times on Send button makes the app unsuable.
Go to 1x1 chat - > /request -> tap ~20 times blue send button
https://app.testfairy.com/projects/4803622-status/builds/7170527/sessions/28/?accessToken=tsJMUzhy/tmn6-e-7ZTOenqfgc0
This happens on iOS, i tried Andriod and was not able to re-create.
