### ISSUE TITLE
User is not being returned to Send transaction screen after scanning address

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2427]
### Description

*Type*: Bug

*Summary*: When I want to send transaction to recipient via scanning QR (using qr reader in wallet) it is actually scanned but user is not redirected back to Transaction Details screen

#### Expected behavior
User is redirected back to Transaction Details right after he scanned the address of recipient

#### Actual behavior
User remains on the Select Recipient screen even the address was scanned

### Reproduction

- Open Status
- Go to wallet
- Click Send
- Click Select Recipient
- Scan any valid QR with address

### Additional Information
* Status version: 0.9.10-360-g190e841f+ (1917)
* Operating System: Android

#### Logs
TF : https://app.testfairy.com/projects/4803622-status/builds/7078352/sessions/10/?accessToken=tH5M/m6Oow9zAWNsBoy7r8GH69I (from 6:0)

**Comment by churik** [comment]
now the problem is changed a bit. When uses scans address, he does not remain on the Select Recipient (is redirected to main wallet screen):
03:34 - 03:39 - https://app.testfairy.com/projects/4803622-status/builds/7392127/sessions/1/?accessToken=50sCII-PfNe1ATrHmaQ5x/dg7kk
0.9.10-491-g153cd02b

**Comment by asemiankevich** [comment]
when i scan QR for user address i am still on send transaction screen to specify other details i need before signing transaction and this is expected now. Closing
