### ISSUE TITLE
User doesn't receive a message when it is sent from offline mode (1-1 Chat)

### ISSUE THREAD

**Issue by Chu127001** [status-im/status-react#2428]
### Description

*Type*: Bug

*Summary*: 
after sending messages from offline mode they are not shown in receiver chat even when 2 users are online.
Log off\log in process doesn't help.

#### Expected behavior
receiver (user B) can see message (in my case "Offline 2") when sender goes online 

#### Actual behavior
offline messages are lost

### Reproduction

- Open Status (user A)
- Go to 1-1 Chat with another user (user B)
- Switch on Airplane mode (user A)
- Send message from offline mode (user A, with text i.e. "Offline 2")
Status should be "Delivered"
- Switch off  Airplane mode(user A)
- Open "Chat" screen (user B)
- Wait until messages are getting synchronized (I waited for 5 min just in case).
In account of User B should appear  +1 message in 1-1 Chat with user A
- Open chat with user A (user B). 

### Additional Information
* Status version: 0.9.12
* Operating System: iOS 10.3.2

#### Logs

* Video: https://drive.google.com/open?id=1cIU4297suA1_0kONF09XVt0gxZkjB6RN

**Comment by churik** [comment]
Is not reproducible with current develop
