### ISSUE TITLE
High CPU consumption and Disk IO usage during typing in chat

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#2429]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I don't want my phone heated and drained battery during using application

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

https://www.youtube.com/watch?v=24eFVH1VtDQ

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open chat
- Start typing

**Comment by flexsurfer** [comment]
this 
```(ns env.android.main
   (:require [status-im.android.core :as core]
             [taoensso.timbre :as log]))
(log/set-level! :error)
 (core/init)```

**Comment by oskarth** [comment]
@rasom @flexsurfer can this issue be closed now or was that PR just part of the work needed?
