### ISSUE TITLE
Can't select recipient in group chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2435]
### Description

*Type*: Bug

*Summary*: Account 2 (iOS) was added to group chat and he is not chat owner. This account can't select recipient in current group chat therefore can't send funds

### Reproduction

- Create account 1 on Android and /faucet some funds
- Create account 2 on iOS and /faucet some funds
- As account 1 create group chat with account 2
- As account 1 send some funds to account 2 in group chat
- As account 2 call /send command in group chat

### Additional Information
* Status version: 0.9.11d365 (1557.365)
* Operating System: <Android, iOS
* Device iPhone 7, iOS 11.1.1

#### Logs
* TF: https://app.testfairy.com/projects/4803590-status/builds/7091484/sessions/7/?accessToken=v8Iplj3EhY-hrB3GXdGRcJdbbwc

**Comment by janherich** [comment]
Hi @asemiankevich, is this still happening ?

**Comment by asemiankevich** [comment]
Seems its gone in develop `0.9.10-412-g16930cf4+`
