### ISSUE TITLE
No hint shown when entering spaces in [Password] field

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2437]
### Description

*Type*: Bug

*Summary*: Looks like spaces are not recognized as symbols in `Password` field so when I set up password which contains only spaces (no matter how many) and tap `send` button in console - nothing happens. From app behaviour it is correct (spaces is weak password to accept) but it is better to infrom user about it right after the attempt

#### Expected behavior
Show user-friendly hint for attempts setting password like 6 or more/less spaces in Password field so user is not confused

#### Actual behavior
Nothing is shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Set password like `6 spaces` 
- Hit send

### Additional Information
* Status version: 0.9.10-365-g777c9d04+ (1922)
* Operating System: Android, iOS

#### Logs
* TF: https://app.testfairy.com/projects/4803622-status/builds/7085013/sessions/11/?accessToken=LKMOUI7h-4iwHCI2RwnSS8HhwUk

**Comment by pablanopete** [comment]
@trybeee Hey are you still working on this? Just following up - seems you've made a bunch of commits.

**Comment by dmitryn** [comment]
@pablanopete thanks for reminding me. I'm going to ask guys who are reviewing that PR to look at my changes.

**Comment by flexsurfer** [comment]
@asemiankevich i think it works as design, so if you type empty parameter for command you can't send it, here the same, but it doesn't look empty because we have dots for security, so nobody wants to create empty password, let's close this issue because it not worth it, because it requires changes for all commands

**Comment by dmitryn** [comment]
@flexsurfer i agree no one should use 6 spaces as a password, though it's a technically valid password in current implementation.
 And yes, it's a very rare case that someone would enter this type of password so maybe the bugfix doesn't worth it really.

**Comment by asemiankevich** [comment]
I am closing this issue as discussed above
