### ISSUE TITLE
Error commands.js console error in-jail ReferenceError: 'status` is not defined

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2440]
### Description

*Type*: Bug

*Summary*: The following error was found during automation tests running:

`Error commands.js console error in-jail ReferenceError: 'status' is not defined`

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/32841831-802aad86-ca2c-11e7-886a-d46fd4d27a3a.png)
![image](https://user-images.githubusercontent.com/28752642/33125606-357f7b0c-cf92-11e7-9f5f-0df3e204e91a.png)

### Reproduction
http://138.197.185.225:8080/job/end-to-end-test-automation/21/sauce-ondemand-report/jobReport?jobId=9e9d5e25aa96432cb241d74038b0e722

https://saucelabs.com/beta/tests/cb929a3e1e1e43d881bda8a4712d3236

### Additional Information

* Status version: seen in latest develop and other versions so no build specific
* Operating System: Android

#### Logs
[logcat.txt](https://github.com/status-im/status-react/files/1475111/logcat.txt)

https://saucelabs.com/beta/tests/e117ffd4223349079de350369a0d23dd

**Comment by mandrigin** [comment]
Closing because we have removed the jail, feel free to reopen if you disagree
