### ISSUE TITLE
Refactoring jail loading + commands/responses processing

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#2442]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want the jail loading and commands/responses to be easy to use, efficient and most importantly correct and predictable under all circumstances.

**Comment by janherich** [comment]
@annadanchenko @asemiankevich As the related PR was already tested & merged, can we move this to closed ?

**Comment by asemiankevich** [comment]
closing
