### ISSUE TITLE
Endless error message when scanning invalid QR using iPhone

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2444]
### Description

*Type*: Bug

*Summary*: Error message appears as many times as long I am scanning wrong QR (iOS)

#### Expected behavior
Scanning stops when error message appears.

#### Actual behavior
Endless count of error messages can be received. Need to close them all before I can proceed

### Reproduction

- Open Status and create account on iPhone
- Go to wallet and scan someone's public key using wallet qr reader

### Additional Information
* Status version:  0.9.11d368 (1557.368)
* Operating System: iOS

#### Logs
* TF: https://app.testfairy.com/projects/4803590-status/builds/7098665/sessions/1/?accessToken=O6PsWET3oRylG6A6W6ZheQjh0Yo

**Comment by annadanchenko** [comment]
can't repro on las nightly jun 17, iOs 11, real device
