### ISSUE TITLE
Insifficient Funds error when sending transaction to dApp

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2449]
### Description

*Type*: Bug

*Summary*: When I try to create an auction via Auction House Dapp I receive `insufficient finds` error message

#### Expected behavior
Price is received and autofilled in Amount field

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/32898449-4081ce26-caf9-11e7-9c14-55170f8c4382.png)

### Reproduction
https://saucelabs.com/beta/tests/f3d0ad51f3d5411c8ee16070a4009288/watch#61

- Open Status
- Request some ETH in Console via /faucet
- Go to Contacts -> dApps
- Select Acution House dapp
- Create an auction

### Additional Information
* This happens also to another dApp (dentacoin), so worth investigating
* Status version:  0.9.10-370-g7e6507be+ (1927)
* Operating System: Android

#### Logs
[logcat (1).txt](https://github.com/status-im/status-react/files/1479020/logcat.1.txt)

**Comment by jeluard** [comment]
Is it a regression? What was the behavior before?

**Comment by asemiankevich** [comment]
@jeluard I was able to send a transaction to dApp while interacting with the dApp. Like for example when I create auction in Auction house dApp I should pay for it - so I need to send some funds to this app. I was able to do so in previous versions.
