### ISSUE TITLE
Specs for translations

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2456]
### User Story

User story 1: As a translator, I want to ensure I translate all english strings to my language. If I don't tests/CI should fail.

User story 2: As a reviewer, I want to ensure a submitted PR translates all the necessary strings, if it doesn't CI should fail.

User story 3: As a developer, if I add a new english string this shouldn't make CI crash because of lack of translations.

User story 4: As someone concerned with UX, I should be able to see (a) which translations we currently support up to a certain degree (b) how far these originally drifted from current english translations.

### Description

*Type*: Feature

*Summary*: Write specs for translations depending on the state they are in.

#### Expected behavior

Use clojure.spec, set logic and tests to solve the three user stories above in the following fashion:

1. Create a spec for english translations at present time that includes all its keys. This is full support, and will rarely be implemented by all translations, but is useful for new translations.

 2. Create a "checkpoint" spec for english translations at a given time. Below is a list from 3 days ago, but we might want to have one on a version basis. Nothing has changed since 0.9.12, but this latest one is still best.

```
#{:validation-amount-invalid-number :transaction-details :confirm :description :phone-national :amount :open :close-app-title :members-active :chat-name :phew-here-is-your-passphrase :public-group-topic :debug-enabled :chat-settings :offline :update-status :invited :chat-send-eth :address :new-public-group-chat :datetime-hour :dropped-pin :wallet-settings :datetime-ago-format :close-app-button :block :camera-access-error :wallet-invalid-address :address-explication :remove :transactions-delete-content :transactions-unsigned-empty :transaction-moved-text :add-members :sign-later-title :sharing-cancel :yes :dapps :popular-tags :network-settings :twelve-words-in-correct-order :transaction-moved-title :phone-number :photos-access-error :hash :removed-from-chat :done :remove-from-contacts :delete-chat :new-group-chat :edit-chats :wallet :wallet-exchange :wallet-request :sign-in :datetime-yesterday :create-new-account :sign-in-to-status :dapp-profile :sign-later-text :datetime-ago :no-hashtags-discovered-body :contacts :search-chat :got-it :delete-group-confirmation :public-chats :not-applicable :move-to-internal-failure-message :active-online :password :status-seen-by-everyone :edit-group :not-specified :delete-group :send-request :paste-json :browsing-title :wallet-add-asset :reorder-groups :transactions-history-empty :sharing-copy-to-clipboard-coordinates :discover :wallet-error :browsing-cancel :faucet-success :intro-status :name :gas-price :phone-number-required :view-transaction-details :validation-amount-is-too-precise :copy-transaction-hash :unknown-address :received-invitation :show-qr :edit-network-config :connect :choose-from-contacts :edit :wallet-address-from-clipboard :account-generation-message :remove-network :no-messages :passphrase :recipient :members-title :new-group :phone-e164 :suggestions-requests :connected :rpc-url :settings :remove-from-group :specify-rpc-url :contacts-syncronized :transactions-sign-all :gas-limit :wallet-browse-photos :add-new-contact :no-statuses-discovered-body :add-json-file :delete :search-contacts :chats :transaction-sent :transaction :public-group-status :leave-chat :transactions-delete :mainnet-text :image-source-make-photo :chat :start-conversation :topic-format :add-new-network :save :enter-valid-public-key :faucet-error :phone-significant :all :confirmations-helper-text :search-for :sharing-copy-to-clipboard :your-wallets :phone-international :sync-in-progress :enter-password :enter-address :switch-users :send-transaction :confirmations :recover-access :incorrect-code :image-source-gallery :sync-synced :currency :status-pending :delete-contact :connecting-requires-login :no-hashtags-discovered-title :datetime-day :request-transaction :wallet-send :mute-notifications :invalid-phone :scan-qr :contact-s :unsigned-transaction-expired :status-sending :gas-used :transactions-filter-type :next :recent :confirmation-code :open-on-etherscan :share :status :from :your-current-location :wrong-password :search-chats :transactions-sign-later :in-contacts :transactions-sign :browsing-browse :sharing-share :type-a-message :type-a-command :usd-currency :existing-networks :node-unavailable :url :shake-your-phone :add-network :unknown-status-go-error :contacts-group-new-chat :and-you :wallets :clear-history :wallet-choose-from-contacts :signing-phrase-description :no-contacts :here-is-your-signing-phrase :soon :close-app-content :status-sent :status-prompt :testfairy-title :delete-contact-confirmation :datetime-today :add-a-status :web-view-error :notifications-title :error :transactions-sign-transaction :edit-contacts :more :cancel :no-statuses-found :can-not-add-yourself :transaction-description :add-to-contacts :available :open-map :paste-json-as-text :You :main-wallet :process-json :testnet-text :transactions :transactions-unsigned :members :intro-message1 :public-chat-user-count :eth :transactions-history :not-implemented :new-contact :datetime-second :search-results :status-failed :is-typing :sharing-copy-to-clipboard-address :recover :wallet-total-value :places-nearby :suggestions-commands :nonce :new-network :contact-already-added :datetime-minute :location :browsing-open-in-web-browser :delete-group-prompt :wallet-insufficient-funds :edit-profile :active-unknown :testfairy-message :search-tags :transaction-failed :public-key :error-processing-json :status-seen :transactions-filter-tokens :status-delivered :profile :wallet-choose-recipient :no-statuses-discovered :none :removed :empty-topic :no :transactions-filter-select-all :transactions-filter-title :message :here-is-your-passphrase :wallet-assets :image-source-title :current-network :left :edit-network-warning :to :data :cost-fee}
```

3. Create a spec which is a list of all language code ["fr", "de"] that supports above checkpoint. A PR that adds translations should at a minimum  implement a given checkpoint. Make sure tests fail if you add language to list and spec doesn't match (i.e. not just runtime spec).

4. Make sure each additional checkpoint is composable, i.e. only add additional keys to it.

5. Add a spec that emits a warning during tests about how far a given spec has drifted. I.e. it shouldn't fail, just print something like `WARNING: "fr" missing #{:foo :bar} compared to ::english-full-spec`.

#### Actual behavior
No specs / ad hoc tooling.

### Bounty size

Medium.

### Additional Information
See https://github.com/status-im/status-react/pull/2422#event-1344784313 thread

**Comment by andytudhope** [comment]
I really like this @oskarth. My only concern is how easy we can make it for people doing translations to test/run CI. Most translators are not devs, so we need to keep the process as simple as possible. However, the benefits of this outweigh the cons of adding one or two extra steps (if we can keep it to that). Have a feeling that the checkpoints might confuse people, but can make sure we have good documentation covering how exactly to do it if we do implement this.

**Comment by yenda** [comment]
This will be good for new translations, translator only has to add his language to the list of translations to check. But it will be harder to make for existing ones that need to be curated. Part of resolving this issue might be to figure a good solution for these cases. Unless you want to keep the scope to new languages.

**Comment by oskarth** [comment]
@andytudhope CI should be run automatically against PR. And yes this is true, so we need to make it clear in issue what translations we expect to be supported. Perhaps we can simply copy paste the key set from latest english checkpoint into the issue and say this is the minimum expectation? Then as a translators you only add your language code to a vector, and then we take care of the rest. So right now we're trying to get up to speed with 0.9.12 state of things, but then later we might decide "this is expected scope of translations for release XXX", so we update spec/tests to reflect this and then create issue from scratch. How does that sound?

@yenda So existing ones should meet some checkpoint, for example at least all strings in 0.9.12 release. All other translations we can count as being unsupported because they are too out of date, imo.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0xb3ecc4cd192d01640a8d3ec4a6fc5808338efcb4](https://etherscan.io/address/0xb3ecc4cd192d01640a8d3ec4a6fc5808338efcb4)
Network: Mainnet
Paid to: pablodip

**Comment by Alonski** [comment]
I was thinking about this a few days ago.
Would an online Web UI for translations be a good idea?

- It would always be up to date with the last build/nightly in regards to English translations.
- Translators can come in and find their language to see if it needs updating. 
- They can update the translations in the UI, which will probably look nicer than staring at cj files 😄 

Other ideas:
- Users could connect with Github account and then this could be used to actually commit and create PR so all bounty/admin work will be done through Github.
- Status Open Bounty could be integrated directly into this new translation web app.

What does everyone this?
I could create an RFC for this if needed 😄

**Comment by kenrestivo** [comment]
Is this bounty still open? I see pull requests, does that mean someone is already working on it?

**Comment by andytudhope** [comment]
There are some folks working on it already @kenrestivo, but feel free to poke around other bounties if you're interested, or this one if you feel you can do it better. @Alonski that does sound interesting, but seems like a lot of work for not too much gain (this is not a major pain point for us). I'm not sure how easy it would be to integrate a web UI with gh webhooks and ensure the correct contributor receives the correct bounty, but it would not be impossible either.

**Comment by yenda** [comment]
@Alonski @andytudhope This is a really good idea. 

We already agreed in the team that translations are more data than code so at some point we would move it to edn or json files, which would make things even simpler. 

I had this idea of a web UI or a special mode in the app to change translations but we really don't have the time in the core team to work on that kind of side tracks. So if you want to create an issue and work on it it is more than welcomed.

**Comment by Alonski** [comment]
@yenda @andytudhope Could I help in migrating the translations to JSON in the process?

**Comment by andytudhope** [comment]
@Alonski so some of the devs have been questioning whether the complexity introduced in other PRs with checkpoints etc is not worth it, and they would prefer "translations as data and a UI to do the translations.We don't have time for that, so if an external contributor does it it would be great. This PR was a good way to test the candidate anyway, it makes me pretty confident about him he's a good communicator and he delivers." So, please do take a crack at this if it is something that interests you. Something like: https://weblate.org/en/

**Comment by Alonski** [comment]
@andytudhope Ok so I will write up an RFC for both features and find some time. Glad to be able to help 😀
