### ISSUE TITLE
Fail build when updating realm from 2.0.7 to 2.0.8 

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2460]
`react-native run-android` fails when building the app for Android after updating realm to latest minor version

Follow https://github.com/realm/realm-js/issues/1506 for eventual resolution upstream

* Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module realm : Configuration with name 'default' not found.
```

**Comment by yenda** [comment]
It would be interesting to know if it is also the case on iOS if someone can give it a shot

**Comment by guy-shahine** [comment]
I noticed that `./node_modules/realm/android` folder is missing in version 2.0.8

**Comment by yenda** [comment]
Thanks @chlela so that's probably only a problem on android then
