### ISSUE TITLE
Group-Chat Command List: Duplicate Commands Displayed in list.

### ISSUE THREAD

**Issue by 0xCourtney** [status-im/status-react#2463]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After creating a group chat with several members it was observed that some commands listed (i.e. @browse, /request, /send, /location, etc) were displayed multiple times when the command list is selected. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The command list should display the same commands that are shown above the message input field.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The command list contains duplicate commands. 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
- Select chat tab, start a new chat
- Select 'New group chat'
- Add multiple members to group chat (i.e. Auction House, Console, Demo Bot, Jarrad, Maker Market)
- Access chat room, select command list
- Verify duplicate commands are displayed

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: TBD

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: v0.9.12+
* Operating System: Android-v7.1.1

#### Screenshots
https://scontent.fatl1-1.fna.fbcdn.net/v/t34.0-12/23758267_911284862359671_1704669583_n.jpg?oh=e8acc7692e390af83f2ec0b306fa33f5&oe=5A150E75

https://scontent.fatl1-1.fna.fbcdn.net/v/t34.0-12/23758283_911284865693004_84025465_n.jpg?oh=d78151f53664e6af2ab5f265dab575b0&oe=5A151D43

**Comment by asemiankevich** [comment]
Fixed in branch `0.9.10-377-g7c0ecef3+`
