### ISSUE TITLE
Assets - Market Value tab with mocked data

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2466]
### User Story

As a user I want ERC20 tokens to be supported in Status Wallet

### Description

*Type*: Feature

*Summary*: Add the Market Value tab as shown in the designs. The scope of this issue is restricted to the tab layout and structure with hardcoded mock data, excluding the line chart svg component.

Line chart visualization and any live data or behavior are outside the scope. See #2467 and #2468 

![selection_007](https://user-images.githubusercontent.com/711764/33212397-2eb13af8-d123-11e7-9887-55426c2d9b26.png)

https://zpl.io/blwD8ka (second and third screen)

**Comment by jeluard** [comment]
Removed from current scope.
