### ISSUE TITLE
Assets - Line chart SVG component

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2467]
### User Story

As a developer I want a generic easy to use visualization component - line chart.

### Description

*Type*: Feature

*Summary*: Create the line chart SVG visualization as a generic component to be used in Assets screen

https://zpl.io/blwD8ka (second  screen)

**Comment by charlesg3** [comment]
I've had pretty good success with the thi.ng/geom-viz library (see: https://github.com/thi-ng/geom/blob/master/geom-viz/src/index.org ). I've ended up creating some sort of wrapper functions to get graphs and what not to look exactly like I want.

**Comment by jeluard** [comment]
Removed from current scope.
