### ISSUE TITLE
Commands are displayed with ? (e.g. ?send) instead of /send [2409]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2469]
### Description

*Type*: Bug

*Summary*: 
some of commands are shown with ? in the beginning instead of /

#### Expected behavior
/send command in chat is displayed as "/send"

#### Actual behavior
/send command and some others  in chat are displayed with ? instead of /
<img width="320" alt="image uploaded from ios" src="https://user-images.githubusercontent.com/4557972/33018554-8e83c5a8-cdff-11e7-95f4-35eaae5069ff.png">

`/send`
`/confirmation-code`
`/phone`

### Reproduction

- Open Status
- Use commands in Console or 1-1 Chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
Is reproducible in Android and Ios
* Status version:  0.9.11d373 
* Operating System: Android, iOs

**Comment by asemiankevich** [comment]
Fixed in branch ` 0.9.10-377-g7c0ecef3+ (1934) `
