### ISSUE TITLE
"@browse" command is not available after joining to public chat [2409]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2472]
### Description

*Type*: Bug

*Summary*: 
after you joined any public chat, there is no @browse command available (if you are not owner of public chat)
![browse](https://user-images.githubusercontent.com/4557972/33019976-2cf06d04-ce05-11e7-9945-5e68998a8282.png)

#### Expected behavior
@browse command is available after joining to public chat

#### Actual behavior
@browse command is not available 

### Reproduction

- Open Status
- Join any existing Public Chat ( in my case I created public #testchu as User A on device A, and join to #testchu as User B on device B)

### Additional Information

* Status version: 0.9.11d373
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
Fixed in ` 0.9.10-377-g7c0ecef3+ (1934) ` branch
