### ISSUE TITLE
Error null is not an object (evaluating 'e.toLowerCase') shown

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2473]
### Description

*Type*: Bug

*Summary*: `null is not an object (evaluating 'e.toLowerCase')` error is shown when runnning the smoke automated test

#### Expected behavior
No errors

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/33020321-f6b84680-ce0e-11e7-92eb-b6980876f3ea.png)

### Reproduction
http://138.197.185.225:8080/job/end-to-end-test-automation/32/sauce-ondemand-report/jobReport?jobId=98da5f74941840a38dfc781f5b925a4a

### Additional Information
* Status version:  0.9.10-373-g7923313f+ (1930)
* Operating System: Android

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7122077/sessions/3/?accessToken=B-GXvXvTtmn2XDSCwXximgfetjk

**Comment by janherich** [comment]
Hi @asemiankevich could you please let me know which steps the automated test is trying to reproduce ?

**Comment by asemiankevich** [comment]
@janherich Clicking Back button in group chat

**Comment by asemiankevich** [comment]
Fixed in ` 0.9.10-377-g7c0ecef3+ (1934) ` branch

**Comment by andytudhope** [comment]
So, can we close these issues you have noted as fixed @asemiankevich?

**Comment by churik** [comment]
Can be reproduced on upgraded version from 0.9.12 > 0.9.10-379-g945ccecf+ (Android)
0.9.12 > 0.9.11d379 (IOS)

Can reproduce:
1) on first login after upgrade
2) on tap "Back" from any Chat

I order to use app again, you need to quit it or make force stop

**Comment by annadanchenko** [comment]
@churik please, see #2602 closing this issue as initial problem described is not connected with upgrade and comment about upgrade does not have any specific data to use to reproduce the issue
