### ISSUE TITLE
App is freezing after "Transaction failed" message [2409]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2478]
### Description

*Type*: Bug

*Summary*: 
when you send transaction from "Wallet" screen (amount to send = balance in ETH) - after message Transaction Failed application is freezing 
![transactionfailed](https://user-images.githubusercontent.com/4557972/33029269-d2a40704-ce20-11e7-8e7d-996f84fe02b8.png)

#### Expected behavior
application is not freezing

#### Actual behavior
app is freezing and unresponsive

### Reproduction

- Open Status
- Go to wallet 
- Try to send transaction (amount = balance)
- Sign transaction
- On message "Transaction Failed" tap OK

### Additional Information

* Status version: 0.9.10-376gff0f5b5d+
* Operating System: Android

**Comment by oskarth** [comment]
Part of 55/Fast-status. @asemiankevich comment on it being a compact bad case:

> Unresponsive app after 'unsifficient funds' message is received

**Comment by asemiankevich** [comment]
i was not able to repro it - can you pelase give it a try and close if so ?  @churik
