### ISSUE TITLE
Console message order is broken [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2484]
### Description

*Type*: Bug

*Summary*: Message order in Console chat looks to be randomized.

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/33063343-3c3b040a-ceb3-11e7-8c0c-f296c1b448f9.png)

### Reproduction
- Open Status
- Go to Console
- Call some commands
- Pay attention to the message order

### Additional Information
* Status version: `0.9.10-377-g91a0d40c+`
* Operating System: Android|iOS

**Comment by annadanchenko** [comment]
verified ok in PR build and merged to develop. should be fixed in 0.9.13 release
