### ISSUE TITLE
Confirmation-code command is present in suggestions after valid code input

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2485]
### Description

*Type*: Bug

*Summary*: ...

#### Expected behavior
`/confirmation-code` command should be removed from suggestions and should not be avaliable after user enters correct confirmation code for provided phone number

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/33063726-5fa34b72-ceb4-11e7-8a0e-f5814185f7ab.png)

### Reproduction
- Open Status
- Call `/phone` command
- Enter non-existent phone and decline for sms permissions
- Enter random value for confirmation code in Console
- Call `/phone` command
- Enter phone number you have access to
- Enter received in sms value for confirmation code in Console
- Pay attention to the commands' suggestions

### Additional Information
* Status version: `0.9.10-377-g91a0d40c+ (1934)`
* Operating System: Android|iOS

#### Logs
TF: https://app.testfairy.com/projects/4803622-status/builds/7123529/sessions/3/?accessToken=GDDiuUakK07sfI7f9/LEA8bgUVQ

**Comment by annadanchenko** [comment]
Phone feature is removed
