### ISSUE TITLE
After upgrade from 0.9.12: commands sent on previous version are displayed without icons [2409]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2488]
### Description

*Type*: Bug
*Summary*: 
"/send", "request", "/debug" etc. commands are displayed without icons in chat (all chat types). 
![1faucet](https://user-images.githubusercontent.com/4557972/33067911-4ee381cc-ceb8-11e7-957d-daa9d658fd5f.png)
![2faucet](https://user-images.githubusercontent.com/4557972/33067993-8c7e91c0-ceb8-11e7-89be-40325003c9a8.png)

#### Expected behavior
all commands are displayed as before upgrade

#### Actual behavior
commands are shown without icons

### Reproduction
Prerequisites:
- you have Status.im installed from TestFlight(PlayStore) with 1-1 chat, group chat, Console where you used all commands

Steps:
- Upgrade Status
- Log in
- Open chats

### Additional Information

* Status version: 0.9.10-377-g7c0ecef3+ Android, 0.9.11d377 IOS
* Operating System: Android, iOS

**Comment by janherich** [comment]
@churik As the related fix was already merged into develop some time ago, testing doesn't need to happen on a branch.

**Comment by annadanchenko** [comment]
@janherich Request message does not show the icon both for recipient and for sender. It means that recipient can't click on the request message to get the send command with pre-populated data.
![screenshot_20171130-203620](https://user-images.githubusercontent.com/6584810/33451534-9cd82d2a-d60f-11e7-8d3d-e848f42188ae.png)

See from 00:36 https://app.testfairy.com/projects/4803622-status/builds/7191960/sessions/1/?accessToken=Zz/p5QvxkE1Q69g/Gav8M-qQFJo

Installed 0.9.12b from TestFlight and PlayStore on real iPhone 7 plus and real Pixel XL.
Upgraded with nightly build 88.

Steps: 
1. before upgrade create group chat and exchange request messages
2. upgrade
3. open the group chat with request messages 

Note: 
1. other messages in the 1-1 chat, group chat and in Console seem to be ok - can see icons where it was an issue in the initial bug report.
2. If send request message after the upgrade - it's shown ok with expected icon

**Comment by asemiankevich** [comment]
Fixed in PR (merged) and looks good in latest develop `0.9.10-411-gf07b5363+`
