### ISSUE TITLE
Fix Wallet screens Russian localization 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2491]
### Description

*Type*: Bug

*Summary*: adjust fonts and translation to fit the wallet screen. We dont need each word capitalized as well as all items should be aligned

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/33077014-a0e6dfe2-cedf-11e7-99a7-e4be669a7b54.png)

![image](https://user-images.githubusercontent.com/28752642/33077174-22ce9b62-cee0-11e7-8492-fbb5b72deed7.png)

![image](https://user-images.githubusercontent.com/28752642/33077208-3d75c4f4-cee0-11e7-9fd0-7ea04ff01c2d.png)

### Reproduction
- Open Status
- Go to Choose recipient screen in wallet

### Additional Information
* Status version: `0.9.10-380-g122bcec8+`
* Operating System: Android

**Comment by asemiankevich** [comment]
i think we can do more research on this as well as translations would not be in scope for Beta (only english for now). Removing this from scope of this swarm

**Comment by chadyj** [comment]
Coinbase has a `Buy Widget` feature that makes purchasing small amounts of ETH easy with a US credit card. https://developers.coinbase.com/docs/buy-widget

The implementation looks straightforward but there may be potential Play and App Store guidelines to deal with.
