### ISSUE TITLE
Error missing value for property 'chat.name'

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2494]
### Description

*Type*: Bug

*Summary*:  Error `missing value for property 'chat.name' `randomly shown. This was encountered in test session last night and i've seen it in develop build however I can't reproduce it now. 

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/33117113-5650b914-cf78-11e7-96a7-c49d6ca91812.png)

### Reproduction
- Open Status
- using iOS add Android to contacts

### Additional Information
* Status version: `0.9.10-381-g8fe9306c+` develop , also seen in previous versions
* Operating System: Android|iOS

#### Logs
https://app.testfairy.com/projects/4803590-status/builds/7099280/sessions/13
https://app.testfairy.com/projects/4803590-status/builds/7099280/sessions/14

**Comment by janherich** [comment]
@asemiankevich can you confirm that it was never encountered in develop after #2409 PR was merged in ? If that's the case, I'm pretty sure it's already fixed.

**Comment by yenda** [comment]
@janherich seems to me that it's the same bug I fixed today in #2497

**Comment by janherich** [comment]
Indeed, it's very likely #2497 fixed this.

**Comment by lukaszfryc** [comment]
Could not be reproduced anymore
