### ISSUE TITLE
Implement basic design for offline inboxing

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2503]
Specifics capabilities TBD. Probably one of the following, in order of complexity:

(1) Visually indicate that a wnode exists (basic skeleton UI for extension)
(2) Visually indicate that you are connected to a wnode
(3) Make it possible to toggle whether you are connected to a wnode (depends on payment specifics)

Part of Offline inboxing MVP: https://github.com/status-im/ideas/pull/36

Also see: https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/5a156473600e43d319cd1e54? and https://github.com/status-im/ideas/pull/23

**Comment by oskarth** [comment]
Pending https://github.com/status-im/ideas/pull/23

**Comment by chadyj** [comment]
Can this be closed?

**Comment by oskarth** [comment]
cc @dmitryn  your call, you touched this most recently

**Comment by dmitryn** [comment]
@chadyj @oskarth i would close this as it's too broad. But some ideas could be extracted from current like
>(2) Visually indicate that you are connected to a wnode

Also, (1) and (3) already implemented in some way or another.

**Comment by chadyj** [comment]
Closing as per the suggestion
