### ISSUE TITLE
Make a build to verify CPU/temp impact from slower LES header writes

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2504]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I don't want my phone to burn in my pocket.

As a developer, I want to verify my assumptions on real world devices before running further with them.

As a tester, I want to have a simple build I can check CPU/temperature on to see if dev fix worked or not.

### Description
See https://github.com/status-im/status-go/pull/464

Make a custom build with this flag on. Investigate if it can easily be toggled by QA or if we need separate builds for this.

Look into what is needed to trigger flag from status-react. Should be passed through start-node, I believe.

**Comment by oskarth** [comment]
See https://github.com/status-im/status-go/pull/464

**Comment by oskarth** [comment]
Awaiting build in Jenkins. If this doesn't work I'll make a build with locally linked Statusgo.framework for iOS at least.

**Comment by oskarth** [comment]
Blocked by lack of `geth.log` on device:

```
Oskars-MBP:Devices oskarth$ pwd
/Users/oskarth/Library/Developer/CoreSimulator/Devices
Oskars-MBP:Devices oskarth$ find . -iname "geth.log" | xargs ls -ll | awk '{print $5 " " $6 $7}'
0 Sep25
0 Oct24
0 Oct13
87867808 Sep9
0 Oct18
0 Nov27
0 Nov24
40297416 Aug2
0 Oct19
0 Sep25
0 Oct13
```

Asked in Go channel

**Comment by oskarth** [comment]
Env variables not supported by default, forking part of issue to https://github.com/status-im/status-react/issues/2544

**Comment by divan** [comment]
To test this build, first checkout original hypothesis link: https://github.com/status-im/status-go/issues/432#issuecomment-341201789 — we've identified a strong correlation between introduced delay for writing headers on disk and CPU usage, which assumed to be the main factor for heating the phone.

The test should go with this scenario:
 - Set delay to 0 (or just don't set it), perform fresh install (or remove all blockchain data from phone somehow) and run Status app
 - Create user and measure time needed to sync blockchain (by observing progress in the UI). Also, note phone temperature increase (I'm planning to get USB thermal sensor for this)

Then, cool down the phone if it's heated, reinstall Status (or remove blockchain data), set the delay to some value (100 for example), and repeat the same procedure, writing down the time to sync and temperature observations. (edited)

**Comment by annadanchenko** [comment]
For the iOS build with a delay (experiment/cpu-test-#2504 - build 11): https://app.testfairy.com/projects/4803590-status/builds/7191826/sessions/2/?accessToken=A5Y0jy44mSxpTil9bPhVUTbwcWo
it took ~10 minutes, 21:06 started, 21:17 finished syncing on Ropsten. Phone was not hot/warm when started. Phone become moderate warm when syncing.

Waiting for 15 minutes to get it cold for sure.

For the iOS nightly build 89 (0 delay): https://app.testfairy.com/projects/4803590-status/builds/7191993/sessions/3/?accessToken=vnVLJ0L-XAQnq6wuQxlWegYfNxQ

it took ~4 minutes, 21:32 started, 21:36 done for syncing on Ropsten. Phone was not hot/warm when syncing is started. Phone become moderate warm during syncing. Can't tell that it was warmer than for the build with a delay, but it took really just 4 minutes, maybe it would increase if more time is spent. 

From the CPU PERFORMANCE stats in both sessions I can see that 100% of CPU was achieved more frequently in session without a delay. 

Device used: real iPhone 6s, iOS 10.3.3

**Comment by annadanchenko** [comment]
let's make same build for Android (as TestFairy shows also Temperature stats for Android devices) and perform same measurements @oskarth

**Comment by annadanchenko** [comment]
Android, with delay, build cpu_test 14:

Ropsten, ~15 mins to sync on Samsung Galaxy S6, temperature went from 23.5C to 29.9C (+6.4): https://app.testfairy.com/projects/4803622-status/builds/7198135/sessions/1/?accessToken=tdhIKtjb-iEGJtrL6tFfdt3VZjw

Android, Develop build (no delay):

Ropsten, ~6 mins to sync on Samsung Galaxy S6, temperature went from 22.5C to 25.5C (+3): 
https://app.testfairy.com/projects/4803622-status/builds/7191960/sessions/39/?accessToken=UWp7KTQjVUrvTIwANXnKWCjZMyY

**Comment by oskarth** [comment]
Done, but not necessarily critical for product MVP.
