### ISSUE TITLE
Support CreateAndInitJail

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2515]
### User Story

As a developer, I want to use the latest status-go interfaces to get all the improvements they have been working on, such as jail perf/semantics.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Move from using `Parse` to `CreateAndInitJail`.

Additionally, it seems like this move requires some change around bot subscriptions. @rasom has more context for this (tried to find his comment in Slack but to no avail). @janherich you wouldn't happen to know?

See https://github.com/status-im/status-go/pull/472 and https://github.com/status-im/status-go/pull/401 for context.

**Comment by oskarth** [comment]
This might also be impacted by https://github.com/status-im/status-react/pull/2450. Something to keep in mind.

**Comment by rasom** [comment]
we are not using `otto` anymore
