### ISSUE TITLE
Assets UI - Transactions list in My Token screen

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2518]
### User Story

As a user I want ERC20 tokens to be supported in Status Wallet

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: UI markup for the transactions list in My Token screen/tab. Use actual data from etherscan API. 

*Expected look:*

android:

![selection_005](https://user-images.githubusercontent.com/711764/33212224-58d37946-d122-11e7-811f-f03a57e3e543.png)

ios:

![selection_006](https://user-images.githubusercontent.com/711764/33212309-be6a80c4-d122-11e7-8cff-a3bf8a277a2c.png)

**Comment by goranjovic** [comment]
Expanding the scope of this task to also include the token transaction data

**Comment by jeluard** [comment]
Removed from current scope.
