### ISSUE TITLE
New messages in the group chat are shown not at the end of the chat but in the middle (e.g 17th message is shown after 8th)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2520]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In the group chat user sends 17 messages "1", "2" .... "17". Message "17" is shown not at the end of the list but after message "8". Next messages "18", "19" are also shown in the mid of the chat.

Note that same scenario works fine on the released 0.9.12 on the same devices for the same steps.
![screenshot_20171124-191845](https://user-images.githubusercontent.com/6584810/33221151-d2e77c7a-d14d-11e7-9dae-e1a5eccaaecd.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
message 17 is shown at the end of the chat.
#### Actual behavior
[comment]: # (Describe what actually happened.)
Message "17" is shown not at the end of the list but after message "8". 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
From 01:35 https://app.testfairy.com/projects/4803622-status/builds/7146204/sessions/19/?accessToken=lsi84O/7/NuAHSU797z2/AiyY2Y 
- Open Status
- Create new Group chat, add Jarrad to the chat
- Send to the chat "1".
- Send to the chat "2". Increase a number and send  it one by one, so you see the sequence of numbers 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
- send to the chat "17" - check where message is shown
- send to the chat 18 and after it 19 - check their position in the chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build  0.9.10-388-g3933ded3+ 
[comment]: # (Android or iOS.)
* Operating System: Android and iOS

**Comment by oskarth** [comment]
Grepping through log file for `clock-value` it's clear message 17 isn't received properly. According to the contract it should always increment it when receiving a message: https://github.com/status-im/status-react/blob/develop/src/status_im/utils/clocks.cljs#L31-L32

So it seems likely something has changed the way messages are received. This assumes this used to work, which IIRC you said it did @annadanchenko? That area of the code, receive-messages.cljs, has been touched a lot and it is hard to tell what has changed, but that would be a good starting point IMO @janherich.

**Comment by annadanchenko** [comment]
Updated the description: yes it used to work, at least on the latest released 0.9.12 version. 
On the same devices with the same steps messages are shown in the expected order, so 17 goes after 16

**Comment by annadanchenko** [comment]
verified ok in PR build and merged to develop. should be fixed in 0.9.13 release
