### ISSUE TITLE
Identify a minimal repeatable procedure that causes bad perf problems

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2521]
### User Story

As a developer, I want to have a minimal bad case for bad perf so that I can work to fix it.

### Description

*Type*: QA

*Summary*: Identify a series of repeatable steps that leads to a bad experience w.r.t perf.

See https://docs.google.com/document/d/1OZtzfojToJtZhj2LnokA9-YU7aL_gm9NzaGtI-vuZ6E/edit#

**Comment by asemiankevich** [comment]
1. Tapping multiple times on `Send` button makes the app unsuable.
Go to 1x1 chat - > /request -> tap ~20 times green send button
https://app.testfairy.com/projects/4803622-status/builds/7170527/sessions/28/?accessToken=tsJMUzhy/tmn6-e-7ZTOenqfgc0
This happens on iOS, i tried Andriod and was not able to re-create.
https://github.com/status-im/status-react/issues/2426

2. Sending a lot of requests causes hot phone issue (old devices, for ex iPhone 5S)
https://app.testfairy.com/projects/4803590-status/builds/7178001/sessions/22/?accessToken=dMvajQBcXlV/FTQ5QjuQluS3nEo
Do not have any other android old device by hand but it may be not platform-specific
https://github.com/status-im/status-react/issues/2559
3. Slow map rendering even on new device https://app.testfairy.com/projects/4803622-status/builds/7170527/sessions/30/?accessToken=L0lrqOkdM4F9zXRTQ0pA9nR008Y (1552)

Iphone 7 is rendering map faster ,  this current lag was noticed on Android device

4. Unresponsive app after 'unsifficient funds' message is received
https://github.com/status-im/status-react/issues/2478

5, One more thing was noticed today: Discover screen becomes very slow and phone is getting hot when adding multiple hashtags or adding symbols like `>`  or `:` or some letters with dots , etc as hashtag. Only testfairy for now
https://app.testfairy.com/projects/4803590-status/builds/7225894/sessions/20/?accessToken=kHrIDkuCyE0LHKFcewH/rsL5ahM

**Comment by oskarth** [comment]
@asemiankevich This is really good, great starting point to tie these minimal repeatable qualitative problems into quantitative things we can test and fix.

**Comment by oskarth** [comment]
@asemiankevich To clarify, are all these issues reproducible on iOS and Android? Does it matter if it is a high-end or low-end device?

**Comment by asemiankevich** [comment]
@oskarth updated comment

**Comment by oskarth** [comment]
Closing for now as links to issues have been captured. Will sync/repro this with:

(a) supported devices
(b) supported user stories (product MVP)
