### ISSUE TITLE
Measure CPU and disk usage during minimal bad perf case (as well as other metrics)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2522]
### User Story

As a developer, I want to have a quantified baseline in bed perf case so that we can test hypotheses.

### Description

*Type*: Feature / Tooling

*Summary*: Measure CPU and disk usage during minimal bad perf case (as well as other metrics), as well specific instructions for how to do this test.

Platform specific as Android and iOS are different.

It might turn out that Xcode with profiling settings on is enough, for example. In that case the instructions should explain that and how to use it.

See https://docs.google.com/document/d/1OZtzfojToJtZhj2LnokA9-YU7aL_gm9NzaGtI-vuZ6E/edit#

See https://github.com/status-im/status-react/issues/2521

Can even be something as simple as: “I can toggle between tab 1 and tab 2 5 times in 10 seconds, but in Telegram I can do it 20 times”, at least as a start. Just something that we can actually measure.

**Comment by chadyj** [comment]
As a start can we list the primary metrics?

Where possible lets phrase the metrics in terms of users and tangible app experiences. 

Lastly, metrics vary considerably per device and OS. Can we come up with a handful of widely used devices that we benchmark against?

**Comment by oskarth** [comment]
Effectively not high priority considering how long it has been dormant.

Also badly formed and superseeded by 71 and 76. Closing for now.
