### ISSUE TITLE
Ru translation fixes

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2523]
### Description

*Type*: Bug
***NOTE* still collecting all the discrapencies please do not build any pr untill this is done**
*Summary*: 

1. in line 330 change `не применимо` to `неприменимо`
2. Remove line 123 as this case is no more valid
3. Make line 201 and 202 alike so make ether `скопировать` for both or `копировать` for both
4. Fix usage. Please put this:

line 66 :datetime-second                       {:one   "секунда"
line 67                                                     :other "секунд(ы)"}
line 68 :datetime-minute                       {:one   "минута"
line 69                                                    :other "минут(ы)"}
line 70  :datetime-hour                         {:one   "час"

5 Line 71 - need to fix the usage, please check examples
 - 1 `час назад`
 - 2 `часа назад`
 - 5 `часов назад`
6. Line 72 fix the usage:
- 1 день
- 2 дня 
- 5 дней
7. `Send location` modal header is not translated 
#### Expected behavior
`неприменимо для неподписанных транзакций`
 - 1 `час назад`
 - 2 `часа назад`
 - 5 `часов назад`

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/33260762-f3bbb99a-d371-11e7-82b1-d0870b500a7b.png)

![image](https://user-images.githubusercontent.com/28752642/33270874-92b94fb6-d396-11e7-8380-fcee3c142c0c.png)

### Additional Information
* Status version: latest develop

#### Logs
https://github.com/status-im/status-react/blob/develop/src/status_im/translations/ru.cljs

**Comment by dmitryn** [comment]
@asemiankevich fixing chat header text "last online N minutes ago" requires adding new pluralization rule for RU language – we only support `:one` and `:other` for now. Ideally, it should be:
* 1 минуту назад
* 2 минуты назад
* 5 минут назад

Adding new pluralizator seems like work out of scope for current issue. Please also keep in mind that other languages would also require proper pluralization http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

Example on how it can be done for Russian language is here: https://github.com/fnando/i18n-js/blob/master/README.md (Pluralization section)
