### ISSUE TITLE
QR code in profile wrongfully has chain id suffix

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2526]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

When I scan the current code in the user profile (to add it as contact for instance) I get an invalid address because there is '@3' appended at the end of the address.

The suffix is in the QR code itself, you can see it when scanning the code with an external reader as well

**Comment by jeluard** [comment]
@yenda How do you scan it? Is it with status?

**Comment by jeluard** [comment]
@yenda Can you confirm this is fixed now?

**Comment by yenda** [comment]
@jeluard I confirm qr codes are just incompatible between versions so not a bug
