### ISSUE TITLE
Separate App Strings zh_hant to Localised Traditional Chinese

### ISSUE THREAD

**Issue by foreseaz** [status-im/status-react#2528]
### User Story

As a user from different regions using traditional Chinese (1. Hong Kong / Macau, 2. Taiwan, 3. Singapore / Malaysia), I want to see the localised indicating message.

### Description

*Type*: Feature

*Summary*: We need someone eloquent and versatile in different Traditional Chinese (including HK/Macau standard, Taiwan Standard, Singapore/Malaysia Standard) to separate the latest `zh_hant` strings in Status to localised string files, say `zh_hk`, `zh_tw`, `zh_sg`.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The three different traditional Chinese translation (`zh_hk`, `zh_tw`, `zh_sg`) ought to be as up-to-date as the English one.

#### Actual behavior
There is only `zh_hant` for all regions / countries using traditional Chinese.

### Solution
*Summary*: 
- [ ] Three new files: `zh_hk.cljs`, `zh_tw.cljs`, `zh_sg.cljs` need to be added to the directory [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations)
- [ ] How you translate is a matter of your preference. But noticed that, there are significant updates of the English file for the 0.9.12 release, with lots of strings both add and **REMOVED**. Make sure that the files are exact mirrors of each other, except in different languages.

### Additional Information
* Status version: 0.9.12+

**Comment by andytudhope** [comment]
Ok great! Next question @foreseaz, can you do all 3? 😉

**Comment by foreseaz** [comment]
A reference of [Comparison of national standards of Chinese](https://en.wikipedia.org/wiki/Comparison_of_national_standards_of_Chinese#Linguistic_differences) could found here. For example, `Message` in `HK/Macau traditional Chinese` should be `訊息` and in `TW/SG ~` should be `簡訊`.

**Comment by foreseaz** [comment]
@andytudhope I am more than happy to dig into them.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x9e4c7a8b8c48bc4d5efc97a039d293fde2f30652](https://etherscan.io/address/0x9e4c7a8b8c48bc4d5efc97a039d293fde2f30652)
Network: Mainnet
Paid to: foreseaz
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
