### ISSUE TITLE
xcode build failing with /bin/sh git related issue

### ISSUE THREAD

**Issue by asaphko** [status-im/status-react#2531]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to follow the Building Status wiki page so that I can build status ;)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Following the instructions on the wiki page, everything works fine until building with xcode fails. the exact error is:
`fatal: ambiguous argument 'master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: bad revision '^'
Command /bin/sh failed with exit code 128
`
and it's failing on at `...../Xcode/DerivedData/StatusIm-etbswbefmtlphahasnnjnzmsyhby/Build/Intermediates/StatusIm.build/Debug-iphonesimulator/StatusIm.build/Script-E3914A731DF919ED00EBB515.sh`

git branch is `develop 0403a7cd Echo apkUrl and ipaUrl`
xcode is 8.3.3. log attached.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Build succeeds 

#### Actual behavior
[comment]: # (Describe what actually happened.)

Build fails

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Follow instructions on the wiki page
- open the workspace file in xcode
- run

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
[build.txt](https://github.com/status-im/status-react/files/1507799/build.txt)

```

**Comment by oskarth** [comment]
@asaphko try: `git clone git@github.com:status-im/status-react.git -b master && cd status-react && git checkout -b develop` or the equivalent (master branch needs to be created)

From https://github.com/status-im/wiki.status.im/pull/51 - if this works we should update wiki with this.

**Comment by asaphko** [comment]
Ok - this works up to `mvn -f modules/react-native-status/ios/RCTStatus dependency:unpack`

which return:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (default-cli) on project Messenger: Unable to find artifact.: Could not find artifact status-im:status-go-ios-simulator:zip:bug-whisper-on-geth1.6.1-g3f6f0fa+ in ci.status.im (http://139.162.11.12:8081/artifactory/libs-release-local/)`

**Comment by asaphko** [comment]
the full error is:
`[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=status-im -DartifactId=status-go-ios-simulator -Dversion=bug-whisper-on-geth1.6.1-g3f6f0fa+ -Dpackaging=zip -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=status-im -DartifactId=status-go-ios-simulator -Dversion=bug-whisper-on-geth1.6.1-g3f6f0fa+ -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   status-im:status-go-ios-simulator:zip:bug-whisper-on-geth1.6.1-g3f6f0fa+
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   ci.status.im (http://139.162.11.12:8081/artifactory/libs-release-local/, releases=true, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

and full debug log
[build.txt](https://github.com/status-im/status-react/files/1507842/build.txt)

**Comment by oskarth** [comment]
Did you checkout develop after this branch switching dance? master only needs to be created, we still use develop for everything.

`bug-whisper-on-geth1.6.1-g3f6f0fa` is an old branch of status-go and indicates you are still on master branch (https://github.com/status-im/status-react/blob/master/modules/react-native-status/android/build.gradle#L18)

**Comment by dbalatero** [comment]
@oskarth I think I know what to do to fix this, and I can open a PR against develop for it. Since my machine is broken in the same way it will be easy for me to validate it.

The thing to do will be to update all references to `master` in this Xcode build script to be `develop`, since that's what we want our "master" to be for all intents and purposes.

Let me know if that sounds good and I'll open a quick PR for it:

<img width="1129" alt="screenshot 2017-11-29 10 34 15" src="https://user-images.githubusercontent.com/59429/33392471-07ce660a-d4f1-11e7-9059-a2c02e7a2a5d.png">

**Comment by asaphko** [comment]
I had to switch back to xcode 9 after finding out 8.3.x doesn't work with ios 11 (.........).
will test if this fixes the built for xcode 9 as well.

**Comment by dbalatero** [comment]
@asaphko Great! Follow the repro steps here: https://github.com/status-im/status-react/pull/2553

And if you can add a comment to my PR indicating whether it worked or not, that would help me get it merged :)
