### ISSUE TITLE
status-go logs stopped logging to geth.log on iOS simulator

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2534]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to see geth logs so I can see what is going on status-go side and actually debug issues.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Make geth.log logs show up again.

#### Expected behavior
geth.log should have stuff in it.

#### Actual behavior
geth.log doesn't have stuff in it, and doesn't appear to have worked locally since around end/mid September.

### Reproduction
1. Use latest status-react, run iOS simulator
2. Go to`~/Library/Developer/CoreSimulator/Devices`
3. `find . -iname "geth.log" | xargs ls -ll` notice how logs after certain date are 0kb in size.

You can find your device ID with`instruments -s devices`.

### Additional Information
* Status version: develop
* Operating System: iOS simulator

#### Logs
```
-rwxrwxrwx  1 oskarth  access_bpf         0 Sep 25 14:07 ./3DFE45B4-574F-4DCB-860B-2FB5CFB22BD7/data/Containers/Data/Application/616C794F-5FAC-4038-AC32-BE7FD6C0A9B3/Documents/ethereum/testnet/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Oct 24 15:04 ./55D9EE9F-73A9-4753-87BE-08033398A028/data/Containers/Data/Application/219F4273-0078-4BFE-A9A9-02E2803DB874/Documents/ethereum/testnet_rpc/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Oct 13 14:57 ./585E973B-0F30-4CB3-83B6-7A4D127CEA47/data/Containers/Data/Application/A20C0CF7-0406-4F9E-818D-2095B678699C/Documents/ethereum/testnet_rpc/geth.log
-rwxrwxrwx  1 oskarth  staff       87867808 Sep  9 11:08 ./7280F630-AD5F-4159-A88E-9BC0B78C2C19/data/Containers/Data/Application/193999E4-156B-4FAC-98CA-E88DB56D5E67/Documents/ethereum/testnet/geth.log
-rwxrwxrwx  1 oskarth  staff              0 Oct 18 15:01 ./7280F630-AD5F-4159-A88E-9BC0B78C2C19/data/Containers/Data/Application/193999E4-156B-4FAC-98CA-E88DB56D5E67/Documents/ethereum/testnet_rpc/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Nov 28 11:17 ./9C95EE2B-47A5-498E-8085-6A3FFB769E8F/data/Containers/Data/Application/9D62EE13-581F-4CCE-8F4A-8D935684E87E/Documents/ethereum/testnet_rpc/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Nov 24 19:20 ./A3C3E1F2-98C8-40A7-8A66-3266033985F6/data/Containers/Data/Application/82E464B1-6535-4FBF-B2E4-38F0712484FD/Documents/ethereum/testnet_rpc/geth.log
-rwxrwxrwx  1 oskarth  staff       40297416 Aug  2 17:21 ./DA70F14B-CD68-476B-A86F-D851F2C3D5A0/data/Containers/Data/Application/010337F2-1F2E-40AF-86F1-C356C139CCC3/Documents/ethereum/testnet/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Oct 19 13:04 ./E193DC67-61FB-4896-B165-B12054B5192C/data/Containers/Data/Application/6642DCB1-310E-4CCD-A1D5-89F3C978A26F/Documents/ethereum/testnet_rpc/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Sep 25 11:47 ./E2C805C6-84E6-4ADA-928D-38EA72E2DCEE/data/Containers/Data/Application/61E03CD7-D52E-4D4E-BC2D-D846A1234E8B/Documents/ethereum/testnet/geth.log
-rwxrwxrwx  1 oskarth  access_bpf         0 Oct 13 15:08 ./F9A37F70-2866-4DDA-90E2-7CFF23FCB187/data/Containers/Data/Application/718FD7D3-FA95-47F0-8C38-915EF8563675/Documents/ethereum/testnet_rpc/geth.log
```

**Comment by adambabik** [comment]
I had some issues with CWD on iOS using Go. What we can do is to create a `geth.log` file in `RCTStatus.m` and use its absolute path in `LogFile` config property. Basically, all paths set in the config passed to Go should be absolute.

Can we verify this assumption (absolute path to `geth.log`) first?

**Comment by oskarth** [comment]
@adambabik Sure. Will do this soon.

**Comment by oskarth** [comment]
@adambabik Not sure what counts as root directory in this execution context but:

```
[resultingConfigJson setValue:@"/Documents/ethereum/testnet_rpc/geth.log" forKey:@"LogFile"];
```
or

```
    [resultingConfigJson setValue:@"/ethereum/testnet_rpc/geth.log" forKey:@"LogFile"];
```

Both results in `SetLogFile err filehandler: open /Documents/ethereum/testnet_rpc/geth.log: no such file or directory`.

This used to work though. status-react has always passed "geth.log" as far as I can tell. What has changed on status-go side last few months in this regard?

**Comment by oskarth** [comment]
Fixed in develop.

**Comment by adambabik** [comment]
I believe it's this commit https://github.com/status-im/status-react/commit/5739bcbb7bcb6b518979cc7a6a97867d7dba9ae0?
