### ISSUE TITLE
npm install breaks lock files across developer machines

### ISSUE THREAD

**Issue by dbalatero** [status-im/status-react#2541]
### User Story

As a developer, I want to have consistent package lock files so that I don't go crazy.

### Description

*Type*: Bug

*Summary*: `npm` is kind of busted–running `npm install` on my machine modifies the existing `package-lock.json` file. This is wrong behavior, as I have not added/removed/upgraded any packages.

#### Expected behavior

Running `npm install` out of the box does not swap around the lock file.

#### Actual behavior

Probably depending on your machine, the lock file will change. They should call it `package-lock-except-for-a-few-packages.json`

Here is the diff that gets produced on my machine:

```
diff --git i/package-lock.json w/package-lock.json
index 207e0166..6fef781f 100644
--- i/package-lock.json
+++ w/package-lock.json
@@ -446,12 +446,56 @@
           "resolved": "https://registry.npmjs.org/babel-register/-/babel-register-6.26.0.tgz",
           "integrity": "sha1-btAhFz4vy0htestFxgCahW9kcHE=",
           "requires": {
+            "babel-core": "6.26.0",
             "babel-runtime": "6.26.0",
             "core-js": "2.5.1",
             "home-or-tmp": "2.0.0",
             "lodash": "4.17.4",
             "mkdirp": "0.5.1",
             "source-map-support": "0.4.18"
+          },
+          "dependencies": {
+            "babel-core": {
+              "version": "6.26.0",
+              "resolved": "https://registry.npmjs.org/babel-core/-/babel-core-6.26.0.tgz",
+              "integrity": "sha1-rzL3izGm/O8RnIew/Y2XU/A6C7g=",
+              "requires": {
+                "babel-code-frame": "6.26.0",
+                "babel-generator": "6.26.0",
+                "babel-helpers": "6.24.1",
+                "babel-messages": "6.23.0",
+                "babel-register": "6.26.0",
+                "babel-runtime": "6.26.0",
+                "babel-template": "6.26.0",
+                "babel-traverse": "6.26.0",
+                "babel-types": "6.26.0",
+                "babylon": "6.18.0",
+                "convert-source-map": "1.5.0",
+                "debug": "2.6.9",
+                "json5": "0.5.1",
+                "lodash": "4.17.4",
+                "minimatch": "3.0.4",
+                "path-is-absolute": "1.0.1",
+                "private": "0.1.8",
+                "slash": "1.0.0",
+                "source-map": "0.5.7"
+              }
+            },
+            "babel-generator": {
+              "version": "6.26.0",
+              "resolved": "https://registry.npmjs.org/babel-generator/-/babel-generator-6.26.0.tgz",
+              "integrity": "sha1-rBriAHC3n248odMmlhMFN3TyDcU=",
+              "requires": {
+                "babel-messages": "6.23.0",
+                "babel-runtime": "6.26.0",
+                "babel-types": "6.26.0",
+                "detect-indent": "4.0.0",
+                "jsesc": "1.3.0",
+                "lodash": "4.17.4",
+                "source-map": "0.5.7",
+                "trim-right": "1.0.1"
+              }
+            }
           }
         }
       }
@@ -7001,9 +7045,9 @@
       }
     },
     "realm": {
-      "version": "2.0.3",
-      "resolved": "https://registry.npmjs.org/realm/-/realm-2.0.3.tgz",
-      "integrity": "sha1-F+vG4qBx9AaFZxdeQ6bIrFfQaT0=",
+      "version": "2.0.7",
+      "resolved": "https://registry.npmjs.org/realm/-/realm-2.0.7.tgz",
+      "integrity": "sha1-1SbWxzksVklafHgASDwG61hcbdY=",
       "requires": {
         "command-line-args": "4.0.7",
         "decompress": "4.2.0",
```

Either someone forgot to update `package-lock.json` when adding/upgrading some packages, or I'm seeing the same old `npm` behavior I'm used to.

### Reproduction

For me it was checking out the repo (OS X), and running `npm install` out of the box.

### Solution

Here are some links I tracked down today:

* https://github.com/npm/npm/issues/17722
* https://github.com/npm/npm/issues/18135
* https://github.com/npm/npm/issues/18712
* https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

To fix this on other projects, I've found the easiest and cheapest thing to do was to just switch to Yarn:

* Takes about 15 minutes.
* Yarn caches your builds in `~/.yarn/cache`, so future `yarn install` runs are really fast (~1-2 seconds if you haven't changed your packages)
* The lock files don't change until you tell them to

There's a bit of an extra cost here, which is adding one more dependency (`brew install yarn`). After that it's smooth sailing though!

### Additional Information

* Operating System: OS X building

**Comment by jeluard** [comment]
If there is an issue with the existing `package-lock.json` then the simplest is probably to fix it. `yarn` might introduced unforeseen issues.

**Comment by yenda** [comment]
Does rn-nodeify hack still work with yarn ?

**Comment by dbalatero** [comment]
@yenda Looks like it does: https://github.com/mvayngrib/rn-nodeify/pull/51

@jeluard You're probably right, I was just having extreme deja vu having been down this road at work and eventually flipping the bar table and switching to `yarn` 😉 

One thing to consider is that I'd like the new `scripts/setup-osx` script to be ran fairly often by devs as dependencies change, and `npm install` is taking a large amount of that script time. Being able to run `yarn check || yarn install` would cut down on that time significantly, as it has fast caching.

I definitely don't want to introduce issues though. In my experience it's been very drop-in, although the rn-nodeify hack will need investigation. I might just spike something in 30 minutes and see if it's worthwhile and if it builds everything correctly and nicely, to get from "if there's an issue" to "there is/isn't an issue" and make a better call from there. We can always just fix `package-lock.json` and hope it doesn't change again.

**Comment by jeluard** [comment]
`yarn` might be a better tool but it's only useful if it works in the context of our project.

If you can do some tests to validate it works I will give it a try to check it in real dev conditions.

**Comment by dbalatero** [comment]
I absolutely agree!

**Comment by alwx** [comment]
Fixed here: https://github.com/status-im/status-react/pull/5056
