### ISSUE TITLE
Add support for env variables / flags to status-go

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2544]
### User Story

As a developer, I want to be able to set ENV variables - such as flags - that show up on status-go so that I or anyone with access to CI can easily try different behaviors and test assumptions around perf.

### Description

*Type*: Feature

*Summary*: Add binding for changing environment on status-go side.

#### Expected behavior
Set env variables on status-react side that impacts status-go side easily.

#### Actual behavior
Unable to set variables status-go ENV variables.

**Comment by oskarth** [comment]
Blocked by https://github.com/status-im/status-go/pull/483

**Comment by yenda** [comment]
@oskarth is this still relevant ?
