### ISSUE TITLE
Fix text styles in a chat list view

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#2546]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to clearly understand which message is read and which isn't for system messages. 

### Description

*Type*: Bug

We have to fix how systems messages are shown now in a chat list view.

#### Expected behavior
1. Seen system messages should have a grey color as a normal chat seen messages
2. System messages regarding geo position should be shown in one line as other messages. 

#### Actual behavior
1. Seen system messages look like as unseen new messages because they have a black color.
2. System message regarding geo position is shown in 2 lines and brake layout.

![slice](https://user-images.githubusercontent.com/6559881/33370162-0b287984-d4f7-11e7-87c4-72d3851134e7.png)

**Comment by churik** [comment]
All messages (not only system) are greyed out (screen)
![grey](https://user-images.githubusercontent.com/4557972/34000922-51314012-e0f7-11e7-8615-08cbbbc715c3.png)

**Comment by dmitryn** [comment]
@churik it's okay by current design. Showing badge is enough for now (acknowledged by design team)
