### ISSUE TITLE
Need an easy setup script for linux boxes

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2548]
### User Story

As a developer, I want to be able to get going quickly with Status on my Linux machine so that I don't get blocked by trivial things I shouldn't need to worry about before getting my hands really dirty.

### Description

*Type*: Feature

*Summary*: I would love @dbalatero (or any other contributor) to write a bash script for Linux that devs can use to build Status easily.

#### Expected behavior
Easy as 1, 2, 3 to setup and build Status on a Linux box.

#### Actual behavior
Currently, you need to read the wiki and follow a lot of steps with plenty of room for error, which can be discouraging.

### Solution
*Summary*: 

- Farm it out to Open Bounty and let our amazing community get to work!

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.12+
[comment]: # (Android or iOS.)
* Operating System: Linux

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x09fd3155e1fc33581d6cfcb19f3295b91accbeb0](https://etherscan.io/address/0x09fd3155e1fc33581d6cfcb19f3295b91accbeb0)
Network: Mainnet
Paid to: dbalatero
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dbalatero** [comment]
I'll jump on this as soon as we get #2525 merged!

**Comment by dbalatero** [comment]
After having experimented a bunch this evening with bootstrapping my own base Linux dependencies, I've found some libraries might have different install procedures depending on which Ubuntu version you're on. This might increase the complexity of this script, as I'm not sure what Ubuntu version people use and which libraries might deviate until diving deeper in.

**Comment by oivoodoo** [comment]
Hi @dbalatero is it possible to have docker environment via docker-compose setup? usually I am using in all my projects compose for making release version and local dev. it's much faster to get a teammate on board to help.  if you need help with it I can give a try to setup the env for this case.

**Comment by dbalatero** [comment]
@oivoodoo Definitely possible yeah. Making it a dependency might be heavy. Docker should run the same scripts that a normal Ubuntu dev machine would to bootstrap.

At this point we're just getting the base dependencies setup to reduce that friction and to focus on that one problem. Scripts for building+running I think will come next!
