### ISSUE TITLE
`gte() not a number: null` if initiate transaction from the DApp Action House

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2558]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Initiate transaction from DApp Action House (try to Register Name) -> popup `gte() not a number: null` is shown. No Send transaction screen is shown. On the same device with released 09.9.12b it works as expected.
![screenshot_20171130-100630](https://user-images.githubusercontent.com/6584810/33423859-4d92f402-d5ba-11e7-9e28-9e1f3def9029.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
 Send transaction screen is shown. User can Sign transaction
#### Actual behavior
[comment]: # (Describe what actually happened.)
popup `gte() not a number: null` is shown. No Send transaction screen is shown to type a password.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status (make sure you have some test ether, e.g. 0.005)
- Open Contacts
- Tap on Auction House
- Tap on Create an auction
- In the field `Name to Reserve` type some random name. e.g. `sfkshfdfhgdfg.eth`
- tap on Register Name button

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  develop build 0.9.10-404-gd78e0ca4+ 
[comment]: # (Android or iOS.)
* Operating System: real device Pixel XL, Android 8.0

#### Logs
From 00:32 https://app.testfairy.com/projects/4803622-status/builds/7185068/sessions/3/?accessToken=3FWIN0q7oaZOjXJiOzdY4HfkPGI

**Comment by jeluard** [comment]
Fixed by PR #2542
