### ISSUE TITLE
Sending a lot of requests causes hot phone issue (old devices, for ex iPhone 5S)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2559]
### Description

*Type*: Bug

*Summary*: Sending a lot of requests causes hot phone issue (old devices, for ex iPhone 5S)

#### Actual behavior
Phone becomes hot

### Reproduction
1. Open Status
2. Go to 1x1 chat
3. Call /request and tap  SEND multiple times

TF https://app.testfairy.com/projects/4803590-status/builds/7178001/sessions/22/?accessToken=dMvajQBcXlV/FTQ5QjuQluS3nEo

**Comment by oskarth** [comment]
Part of 55/Fast-status. @asemiankevich comment on it being a compact bad case:

> Sending a lot of requests causes hot phone issue (old devices, for ex iPhone 5S)
https://app.testfairy.com/projects/4803590-status/builds/7178001/sessions/22/?accessToken=dMvajQBcXlV/FTQ5QjuQluS3nEo
Do not have any other android old device by hand but it may be not platform-specific
#2559

**Comment by oskarth** [comment]
@asemiankevich Can this be reproduced on either:

- iPhone 6s (or above), or
- Samsung Galaxy 6 (or above)

Answer to this question would let us know if this is a prio for 55/Fast status or not.

**Comment by asemiankevich** [comment]
iPhone 7 looks much better, Android is hard to say as sending multiple requests make the app unresponsive. I assume there is a fix for that somewhere on its way.

**Comment by oskarth** [comment]
> Android is hard to say as sending multiple requests make the app unresponsive

@asemiankevich is this captured somewhere? do you know what issue?

**Comment by asemiankevich** [comment]
it is known issue https://github.com/status-im/status-react/issues/2757

**Comment by asemiankevich** [comment]
@oskarth can we move the issue in backlog or somewhere else then?

**Comment by oskarth** [comment]
@asemiankevich Sorry, of course. Done!
