### ISSUE TITLE
Translations Web App + Overhaul

### ISSUE THREAD

**Issue by Alonski** [status-im/status-react#2560]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

User story 1: As a translator, I want to ensure I translate all English(Default) strings to my target language in the simplest way and in a not overly technical way.

User story 2: As a reviewer, I want to ensure any updated translations create a PR with the necessary translated strings for all relevant Default strings.

User story 3: As a developer, if I add a new Default string, other languages shouldn't break and all translations should automatically update to include this new untranslated string. I don't need to think about other languages while developing.

User story 4: As a Product/Project Manager, I should be able to see:
1. which translations we currently support up to a certain degree (100%, 80%, 50% etc)
2. how far each translation has drifted from the current Default translations.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Create a Translations Web App for use with the Status-React Repo (Possible expansion in the future) that will allow translators, developers and managers a simpler and more intuitive translation experience. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
1. Step one is to change the current translation mechanism to work with JSON files and format which will probably be easier and simpler for the general community to understand and won't be as tightly coupled to the actual code.
1. Step two is the build out a Web App that will allow reading these JSONs from Github and showcasing them in a simple and intuitive UI for translations.
1. Step three is to allow for the Web App to be used to translate and add new translations and languages. This will also allow adding new translations to the Default language in the Web App instead of the code and will create a one source of truth in regards to Translations
1. Step four is to integrate this app with the current Bounty system.

All of this will be managed straight from Github and all Users will be signed in using Github. This will allow a no database approach and will keep everything centralized. 

#### Actual behavior
[comment]: # (Describe what actually happened.)
Currently translators are required to edit Clojurescript files and submit PRs themselves which takes away from their core goal: to translate. They also don't get notified when a new translation is needed.

Developers add a new translation token directly into the code and then go about adding it to the translation file.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

I propose building this Web App in Ember.js from scratch.
Another option is to use something like: https://weblate.org and bend it to our needs.

### Additional Information
[comment]: # (Please do your best to fill this out.)
This is open to suggestions/feedback.

**Comment by andytudhope** [comment]
@pablodip might be interested by this...

**Comment by puilp0502** [comment]
Can I tackle this? This seems to be interesting!

**Comment by Alonski** [comment]
Hey @puilp0502! I would love some help. Can you send me a message on Riot we can chat about this?

**Comment by puilp0502** [comment]
Sure. What's your Riot ID?

**Comment by Alonski** [comment]
@puilp0502 My Riot ID is `alon`

**Comment by chadyj** [comment]
Closing. We are using Lokalise and it provides all of the user stories
