### ISSUE TITLE
Make it easier for all contributors to use CI tools (jenkins)

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2566]
### User Story

As an external contributor I want some CI to give me feedback in PR if build was successful or not. I either want Jenkins to build my PR and deliver it much like Travis-CI or CircleCI does so that I can easily see if my submission passes all the necessary tests etc., or we should move over to one of the others to see if we can improve a bunch of processes and handle some sensitive info in `ENV` variables in the CI instead.

### Description
*Type*: Feature

*Summary*: Currently it is very hard for external contributors to see if their changes pass the CI build as this integration is only available on our closed slack. Furthermore, we need manually to log in to Jenkins and trigger builds from external people, which is not very automated. We should change this by either switching tools, or finding a neat way to integrate Jenkins more closely with GH.

#### Expected behavior
Should be as easy as possible for external contributors to get feedback in PR if their build was successful or not.

#### Actual behavior
Jenkins integration currently only available in team slack.

### Solution
*Summary*: Either find a neat way to integrate Jenkins and GH and then think about how to automate external builds in Jenkins, or move over to another CI tool.

Let the debates begin 😉

**Comment by dbalatero** [comment]
I think moving to Travis-CI makes sense to me as it seems like a lot of OSS projects use it and it supports a number of build matrices. It seems easier to work with from a setup standpoint as well. Jenkins feels like older clunkier software to me (this isn't a reason to switch though, just my personal bias).

I think out of the box it will support building forked repos, and we could fix Slack notification as well on builds while in there.

Discovery would be easier on a more open service as well–being able to find the builds and where they live.

I'd be passionate to take this on if it's something we want to explore and see if it's possible. I like setting up CI builds.

**Comment by Alonski** [comment]
I also recommend moving to Travis which is free for OSS as @dbalatero said.
I can also help with this.
Can I get access to the Jenkins tool so that I can remodel it for Travis?

**Comment by jeluard** [comment]
What problem would moving away from Jenkins solve for us? (assuming Jenkins is available for everyone)

Jenkins offers us great flexibility (integration with external tools with slack) and we can control its scalability (especially macOSX builds are well known to be slow on TravisCI).
Ultimately Jenkins interactions will be automated so no one has to look at it.

**Comment by Alonski** [comment]
Maybe Jenkins can be setup to build every pull request and comment if it succeeds or fails? I am not as familiar with Jenkins but can look into it

**Comment by jeluard** [comment]
@Alonski Yes we already have such behavior but it publishes result in an internal slack. What would be great is to have it published to GH too (and share build details at the same time).
This way everyone could see the result of the build.

See our current Jenkins config [here](https://github.com/status-im/status-react/blob/develop/Jenkinsfile)

**Comment by Alonski** [comment]
I'll try playing around with it this week. Hopefully I'll be able to get it working in my own branch

**Comment by dbalatero** [comment]
If builds for Mac are slow on Travis that's a great reason to not switch.
Ultimately what I want as a non-core-team member is to see every commit
build status in Github via integration, and to be able to click through to
a URL and see exactly what failed. Other than that I'm good.

Someone with admin rights to Github/Jenkins will likely have to set this up
though.

**Comment by dbalatero** [comment]
@Alonski see here: https://jenkins.io/solutions/github

Most CI solutions I've seen hook into Github's API, vs posting a comment. Using an API hook would be nicer integration, if possible.

Also I think Jenkins should be publicly open, at least as a read-only URL. That way everyone sees the same view of CI.

**Comment by dbalatero** [comment]
I wanted to check in and see what the status is on this and/or if there is an open PR to track this work? Thanks!

**Comment by andytudhope** [comment]
Hi @dbalatero! I thought you were on holiday 😉 So, our new devops guy @v2nek is working on this, and last I heard there may be a OAuth solution to allowing some external contributors access to Jenkins. Though I also think that moving over to yarn with @oskarth is maybe more pressing right now.

**Comment by dbalatero** [comment]
Sounds good, I'll jump back on that yarn PR. I'm back as of yesterday!

**Comment by oskarth** [comment]
@dbalatero Welcome back! Our new devops guy is looking into GH auth or so at https://github.com/status-im/status-cluster/issues/14 (private repo unfortunately)

**Comment by eskp** [comment]
Hi all, is there an update / anyone currently working on this?

**Comment by andytudhope** [comment]
Not really if I'm honest. @oskarth @jakubgs is this still something we need?

**Comment by jakubgs** [comment]
This has already been resolved. There is now anonymous read-only access enabled to Jenkins Build logs.
Example:
https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-4919/13/pipeline
I'm gonna close this issue in a day or few if this is enough.

<blockquote><div><strong><a href="https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-4919/13/pipeline">Jenkins</a></strong></div></blockquote>

**Comment by jeluard** [comment]
@jakubgs Great! Could you document this in https://github.com/status-im/docs.status.im ? :grin: 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/docs.status.im">status-im/docs.status.im</a></strong></div><div>Contribute to docs.status.im development by creating an account on GitHub.</div></blockquote>

**Comment by jakubgs** [comment]
Updated as requested by @jeluard:
https://github.com/status-im/docs.status.im/pull/28

**Comment by jeluard** [comment]
Thanks @jakubgs !

**Comment by jakubgs** [comment]
I'm closing this since I consider this handled by the read-only access to the Blue Ocean UI.
