### ISSUE TITLE
Investigate: battery drain status issue

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2569]
### Description

*Type*: Bug

*Summary*: Investigate and capture battery consumption by status app as there were several complains about that. I heard Jarrad experienced the same issue.

Not too much details for now, so need to investigate both platforms. I saw similar issue using iPhone 5S but it is quite old and that is may be the case.

This ticket is for tracking purposed and investigation - will be transformed into issue once I get enough details for that.

**Comment by graemerycyk** [comment]
I assume this can be measured in Xcode using Instruments to evaluate the energy impact. Just an idea.

**Comment by lukaszfryc** [comment]
Already done as part of https://github.com/status-im/ideas/blob/master/ideas/083-energy-efficient.md swarm

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/ideas">status-im/ideas</a></strong></div><div>ideas - Swarm Home. New, completed and in-progress features for Status</div></blockquote>
