### ISSUE TITLE
Add proper pluralization rules for supported languages

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2571]
### Description

*Type*: Bug

*Summary*: In scope of this issue:

- add new pluralization rule for RU language – we only support ` :one` and `:other ` for now. Ideally, it should be:

1 минуту назад
2 минуты назад
5 минут назад

Example on how it can be done for Russian language is here: https://github.com/fnando/i18n-js/blob/master/README.md (Pluralization section)

- add the same rules for other languages we cupport in app
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

@trybeee Feel free to add any details to this issue

**Comment by yenda** [comment]
@asemiankevich has it been done already ?
