### ISSUE TITLE
Edit chat stays open after entering on other menu and coming back. 

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#2582]
When editing a group chat, if the menu is not closed it will remain opened even if entering on other menu like "Wallet" and coming back to that group chat. 

Operating system: Android 4.4.0

**Comment by annadanchenko** [comment]
@andmironov @denis-sharypin  from UX perspective is it ok that Group chat menu (with options Members, Search chat, Notifications, Settings) stays open after user press device Back button and navigates from Group chat to Chats? So when user returns back to the Group chat then menu stays open.  I assume it's OK as I've returned to the same state where I left the screen...
![screenshot_20171207-174059](https://user-images.githubusercontent.com/6584810/33726697-0cd6e254-db76-11e7-8a01-7dbe4c27e199.png)

**Comment by denis-sharypin** [comment]
@ardielgonzalez  Hey, thanks for a feedback. As a part of a Status design team, I agree with a @annadanchenko 's comment above. We should try to keep a state of the screen while we are jumping between different screens/tabs

**Comment by lukaszfryc** [comment]
We've changed UI. Issue is not relevant anymore
