### ISSUE TITLE
No amount is shown in Wallet field on Send Transaction screen (`Main Wallet ETH` instead of `Main Wallet 0.1 ETH`)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2589]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

On Send Transaction screen there is no value shown in the Wallet field. It happens for both cases when user has 0 ETH or some ETH, e.g 0.1 ETH.

![img_0778](https://user-images.githubusercontent.com/6584810/33526963-deafe3f6-d848-11e7-8de8-132876b94b38.jpg)

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Amount of ETH in the Wallet is shown in Wallet field, e.g. if user has 0.1 ETH then Wallet field contains `Main Wallet 0.1 ETH`
#### Actual behavior
[comment]: # (Describe what actually happened.)
When user has 0.1 ETH: Send Transaction screen contains `Main Wallet ETH` instead of `Main Wallet 0.1 ETH` in the Wallet field
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803590-status/builds/7202630/sessions/4/?accessToken=CWjx0x4oq93Kkad0XyT/pW6Jj20
- Open Status
- Sign in
- Request some eth
- Open Wallet
- Tap on Send button
- Check content of the field Wallet

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build 93. Version  0.9.11d411 (1557.411)
* Operating System: Android and iOS. 
* Devices: real iPhone 7 plus, iOS 11.0.3 and real Pixel XL Android 8.0

**Comment by asemiankevich** [comment]
fixed in branch (0.9.10-431-g7f028ef5+, 0.9.11d431-1557.431)
