### ISSUE TITLE
Blank QR code on a quick double tap of the 'Show QR code'

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2590]
**Type: Bug**

***Summary***: Blank QR code appears if quickly tap twice (or more) on the 'Show QR code' on profile page for 'Show QR code' area, 'Show QR code' of the 'Address' and 'Public key' area.   

***Expected behaviour:***
QR code of the 'Public key'/'Address' is displayed if to tap twice (or more) times on 'Show QR code'
***Actual behaviour:***
Blank area on a place where QR code should be displayed. 

***Reproduction:***
Video: https://drive.google.com/file/d/1goHJrACA3B0CbRSMqTVMPZQwaULYlyH3/view?usp=sharing
1) Open Status
2) Open Profile page
3) Quickly tap twice on 'Show QR code' area. *Result:* QR code is not shown. 
4) Return back to profile page and reveal three-dots menu of 'Address'.
5) Quickly tap twice on 'Show QR code' area. *Result:* QR code is not shown. 
6) Return back to profile page and reveal three-dots menu of 'Public key'.
7) Quickly tap twice on 'Show QR code' area. *Result:* QR code is not shown.

**Additional Information**
* Status version: 0.9.12+
* Operating System: Android 6.0.0 (on Samsung Galaxy S6)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0xff904a4dd0c0d70f14ccf375869cefeb7e8826fe](https://etherscan.io/address/0xff904a4dd0c0d70f14ccf375869cefeb7e8826fe)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
