### ISSUE TITLE
java.lang.SecurityException on /location request with denied access of the device location

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2594]
***Type***: Bug

***Summary***: There is an exception happens 
*java.lang.SecurityException: Looks like the app doesn't have the permission to access location. Add the following line to your app's AndroidManifest.xml: <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />*
when /location is requested while user denied Status app to access device location: 
![screenshot_20171207-213415](https://user-images.githubusercontent.com/6584810/33737578-f2df8434-db96-11e7-9700-0479a6cef7ef.png)

**Expected behavior:**
/location feature is available for further usage and user is able to type location details
**Actual behavior:**
java.lang.SecurityException exception and 'Unfortunately, Status has stopped' upon hit 'Exit' on the error popup. 

**Reproduction**
Video: https://drive.google.com/file/d/1JPjW80ADj2YicY9b8Q5MnD5NTq6xPPbw/view?usp=sharing

*Precondition:* Clear all data previously used by app
1) Open Status
2) Submit valid password for the new account
3) Navigate to the list of contacts
4) Find 'Jarrad' and start 1-1 chat with this contact
5) Tap /location option
6) On the 'Allow Status to access this device location' pop up tap 'Deny' (note: on emulator it requires to deny three times)
7) Clear /location from the message box and tap on /location again to request 'Send location' feature
8) 'Allow Status to access this device location' pop up appears again. Set checkmark on 'Don't ask again' checkbox and 'Deny' (if on emulator then Deny 3 times)

**Additional Information:**
* Status version: 0.9.12+
* Operating System: Samsung Galaxy S6, Android 6.0.0 (API 23)

**Note:** It's all OK on Samsung Galaxy S6 Android 5.1.0 (API 22) and real device LG D325 with Android 4.4.2. I haven't been requested to 'Allow Status to access this device location' (the 6th and 8th steps above) on the this two android versions.

**Comment by annadanchenko** [comment]
Can reproduce it if Location setting is set to ON.
- real Samsung Galaxy S6, Android 6.0.1 on a nightly build, Status version 0.9.10-427-ga68f0652+ Video and log: https://app.testfairy.com/projects/4803622-status/builds/7234321/sessions/49/?accessToken=WvFC/nuC-4m3NzirEozrIq6uQOo
- real Google Pixel XL, Android 8.0 on a nightly build, Status version 0.9.10-427-ga68f0652+ 
Video and log: https://app.testfairy.com/projects/4803622-status/builds/7234321/sessions/48/?accessToken=uJeVu2AV7E/mhVSAPq/ictQd6oQ

Settings for Location in Galaxy S6:
![screenshot_20171207-213441](https://user-images.githubusercontent.com/6584810/33737804-acab8eb2-db97-11e7-86fe-ca453bbae866.png)


![screenshot_20171207-213444](https://user-images.githubusercontent.com/6584810/33737772-98868d2e-db97-11e7-944c-d9f7667f5092.png)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x69f823163ba7b8250ce1e30603cd8c530d32134f419b639ab6c8e2fa60a1bc88](https://etherscan.io/tx/0x69f823163ba7b8250ce1e30603cd8c530d32134f419b639ab6c8e2fa60a1bc88)

**Comment by Chumalaka** [comment]
Hi @andytudhope, is this still an issue? I would like to check it out.

**Comment by andytudhope** [comment]
Hi @Chumalaka, you can be sure that if the issue is still open and there is a bounty on it, then it is still an issue. Please do go ahead - no need to comment on issues really - PRs are always better proof than comments anyway 😉 Looking forward to seeing you skillz!

**Comment by ghost** [comment]
is this deprecated by #3164 of #3007 ?

**Comment by flexsurfer** [comment]
@audriu yes, we decided to remove this functionality and review it later
