### ISSUE TITLE
Emoji are not visible in 1-1 chat message bubbles

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2598]
***Type***: Bug

***Summary***: ...
Emoji in 1-1 chat messages are not visible on Android 4.4.2. 
If they accompanied by the text - only text is shown. 
If the message consist only emoji - empty message bubble is present. However, it's all fine in group or public chat.

**Expected behavior**
Emoji are visible in 1-1 chat messages

**Actual behavior**
No emoji are visible in 1-1 chat messages
![no_emoji_android_4_4_2](https://user-images.githubusercontent.com/8749671/33569513-9a19aa2a-d932-11e7-836e-9c60fd11094a.png)

**Reproduction**
1) Open Status
2) Log in with your account (or create a new one)
3) From the list of contacts tap on 'Jarrad' contact to create 1-1 chat
4) Send any emoji from the app list of emoji
5) Send any emoji from the native device list of emoji

**Additional Information**
* Status version: 0.9.12+
* Operating System: Android 4.4.2 (real device LG L70)

**Comment by annadanchenko** [comment]
Can reproduce on nightly develop build from Dec 7. http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk
Status version:  0.9.10-427-ga68f0652+ (1984)
Device: real device from BitBar cloud,  
LG Optimus L70, Android 4.4.2
See video and log from 01:53 https://app.testfairy.com/projects/4803622-status/builds/7234321/sessions/50/?accessToken=9zML5l0rXbnJ4ifs68U4jzlLlQo

**Comment by lukaszfryc** [comment]
Could not be reproduced anymore
