### ISSUE TITLE
After upgrade: null is not an object (evaluating 'e.toLowerCase') if last message in chat is Request

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2602]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

In the upgraded app (if last sent message in the chat was Request message) after sign in:
1. Popup `null is not an object (evaluating 'e.toLowerCase') is shown each time after sign in 
2. If open chat and tap on back button then same popup is shown and no navigation happens, so user stays in the chat and need to re-launch app
3. if user taps on the input field in the chat (to send something else) then popup `undefined is not an object (evaluating 'this._component.getScrollableNode')` shown and focus is out of the input field, so can't type. 
  
![img_2535](https://user-images.githubusercontent.com/6584810/33575161-fea90478-d93b-11e7-8541-a5264752722c.jpg)
![img_2538](https://user-images.githubusercontent.com/6584810/33575174-0b22f452-d93c-11e7-8d65-9e85d38b9c28.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After upgrade user can sign in, no popups with errors are shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
If chat contains request message then after upgrade:
1. Popup `null is not an object (evaluating 'e.toLowerCase') is shown each time after sign in 
2. If open chat and tap on back button then same popup is shown and no navigation happens, so user stays in the chat and need to re-launch app
3. if user taps on the input field in the chat (to send something else) then popup `undefined is not an object (evaluating 'this._component.getScrollableNode')` shown and focus is out of the input field, so can't type. 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Before upgrade:
- Open Status
- Open chat with Jarrad 
- Send to Jarrad /request 0.00004 ETH
- Close app
- upgrade
- Launch app
- Sign in (check if any popups are shown)
- Open chat with Jarrad  (check if any popups are shown)

### Additional Information
after upgrade: https://app.testfairy.com/projects/4803590-status/builds/7202630/sessions/29/?accessToken=iBR/7sEA7dfI5qIk6iOh4UoDbqk
* Status version:  
version 0.9.11d411  
upgraded from 0.9.12 TestFligh version to nightly build https://jenkins.status.im/job/status-react/job/nightly/94/ 
* Operating System: found on iOS, real device iPhone 6s, iOS 10.3.3

**Comment by annadanchenko** [comment]
also mentioned in comment https://github.com/status-im/status-react/issues/2473#issuecomment-346013566 but no special data described there. Because initial issue there is different, I've created this one and closed #2473

**Comment by churik** [comment]
Faced with issue on Android as well (Galaxy S7).
I have several /request in group chat and one in 1-1 chat before upgrade.
After upgrade and sign in (worked with app for 2 min after sign in, can see in TF session for first 2 min) I see same error with more details (debug is on):
![egtolower](https://user-images.githubusercontent.com/4557972/34577691-bafc8c1a-f18a-11e7-87ab-e07b584d6d57.png)
TF session (popup appears on 02:08): 
https://app.testfairy.com/projects/4803622-status/builds/7435076/sessions/2/?accessToken=vT/PcPtOfl4GQ3reoGBvJqqhS5E

**Comment by annadanchenko** [comment]
initial issue can't be reproduced. https://github.com/status-im/status-react/issues/2602#issuecomment-355355979 is moved to https://github.com/status-im/status-react/issues/3081
