### ISSUE TITLE
Expansion problem with Status emojis in Message Box

### ISSUE THREAD

**Issue by ahmetmertugrul** [status-im/status-react#2604]
### Description

*Type*: Bug

I wrote a lot of emojis with Android keyboard's emojis in Message Box. Message Box expands as I write. I wrote a lot of emojis with Status emojis in Message Box. Message Box don't expands as I write.

Video: [https://drive.google.com/file/d/1FHMWOQBTUkbFc0WeTVTLCHqpArY4WGcs/view](https://drive.google.com/file/d/1FHMWOQBTUkbFc0WeTVTLCHqpArY4WGcs/view)

### Reproduction

- Open Status
- Sign in
- Chat with Jarrad
- Click Message Box
- Open Android keyboard's emojis
- Write emojis
- Scroll up on Message Box
- Send message
- Click Message Box
- Open Status emojis
- Write emojis
- Scroll down on Message Box

### Solution

- Message box expanded as Status emojis are written.

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by ahmetmertugrul** [comment]
I can't see the third line because of the save button when I write in the profile biography box.

Video: [https://drive.google.com/file/d/1u3_k4tT6SetAtHs-mQ6B0U_4WymB_IJf/view](https://drive.google.com/file/d/1u3_k4tT6SetAtHs-mQ6B0U_4WymB_IJf/view)

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by annadanchenko** [comment]
@ahmetertugrul please, next time report the issue separately if it's from the other area. Do not add a comment to the existing issue unless the area/outcome are completely the same. Right now, we have a mix of 2 problems mentioned in one report: 1. initial issue with emoji and 2. your comment about profile field. They are different and it will be misleading for the developer who will try to fix the initial issue.  

Also seems like your comment about profile field was already reported in https://github.com/status-im/status-react/issues/2419

**Comment by ahmetmertugrul** [comment]
@annadanchenko I found the white screen error in 2 different ways. When I published this error as two different titles, you said 'you closed the second'. So I wrote this error here.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0x4b6efb1d5fafd71994dec549ef2fa17214e28792](https://etherscan.io/address/0x4b6efb1d5fafd71994dec549ef2fa17214e28792)
Network: Mainnet
Paid to: mlahia
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
