### ISSUE TITLE
White screen error

### ISSUE THREAD

**Issue by ahmetmertugrul** [status-im/status-react#2605]
### Description

*Type*: Bug

I quickly switch between submenus and History and Unsigned menus. Screen was white and Status wasn't open.

Video 1: [https://drive.google.com/file/d/1Lsfv4a46EshLUu3VPSB75x8241J6OwsK/view](https://drive.google.com/file/d/1Lsfv4a46EshLUu3VPSB75x8241J6OwsK/view)

Video 2: [https://drive.google.com/file/d/1-toJCcuCYLGQJijjtLtNSqpxDBZxCsqG/view](https://drive.google.com/file/d/1-toJCcuCYLGQJijjtLtNSqpxDBZxCsqG/view)

### Reproduction

- Open Status
- Sign in
- Open Discover
- Open Wallet
- Open Contacts
- Open Discover
- Open Chats
- Open Wallet
- Open Contacts
- Show white screen
- Close Status

- Open Status
- Sign in
- Open Wallet
- Open Transactions
- Open Unsigned
- Open History
- Open Unsigned
- Open History
- Show white screen
- Click back button

### Solution

- There should not be an error when switching quickly between submenus.

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by annadanchenko** [comment]
can't reproduce yet :( 
@ahmetertugrul Can you reproduce the bug on this development build: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk ? Please, use wifi so we can get extra log and video to investigate the problem. If it's reproduced then comment on the date-time-minute when app was launched, your country and device used, so we can find your recorded session. Thanks in advance!

**Comment by ahmetmertugrul** [comment]
Video: [https://drive.google.com/file/d/1tCEnAzQtyjsx2zQJqcWD2NXCQjP4YxuK/view](https://drive.google.com/file/d/1tCEnAzQtyjsx2zQJqcWD2NXCQjP4YxuK/view)

"im.status.ethereum-a68f06.apk" is troubled.

- Status version: 0.9.10-427-ga68f0652+ (1984)

- Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by graemerycyk** [comment]
Just change tabs very fast, straight up monkey testing, I think being offline helps. I was able to reproduce this several times, I can add a video see video -> http://share.xctest.io/Nx0tsJ

iPhone SE | iOS 11.2 | Status v0.9.12

**Comment by Monali109-zz** [comment]
Same thing observed on 
Status Version -  http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk
Device - Mi Redmi Note 4
OS -       Android  - 6.0.1
Please see following link 
https://drive.google.com/file/d/13spn7r-k3KzZnBtPtIEgB58Mpu11NkBe/view

**Comment by Monali109-zz** [comment]
can't reproduce on latest build. Please see  latest build.
OS Android 6.0.1
Status Version  - Latest
