### ISSUE TITLE
White screen error 2

### ISSUE THREAD

**Issue by ahmetmertugrul** [status-im/status-react#2610]
### Description

*Type*: Bug

I quickly switch between History and Unsigned. Screen was white.

Video: [Video](http://sendvid.com/6wywo6hf)

### Reproduction

- Open Status
- Sign in
- Open Wallet
- Open Transactions
- Open Unsigned
- Open History
- Open Unsigned
- Open History
- Show white screen
- Click back button
- Open Transactions
- Open Unsigned
- Open History
- Open Unsigned
- Open History
- Show white screen
- Click back button

### Solution

- There should not be an error when switching quickly between History and Unsigned.

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4

**Comment by annadanchenko** [comment]
@ahmetertugrul Please, add the info as another way to reproduce #2605 and close this one
