### ISSUE TITLE
Long username is not cut with ... so button Chat goes outside of the card in Discover

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2613]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
Button `Chat` is moved outside of the card if username is too long in Discover, Discover -> Popular hashtags -> All and in Discover -> Recent Statuses -> All 
![img_2543](https://user-images.githubusercontent.com/6584810/33633133-0d819ab2-da10-11e7-8214-410a7224f35a.jpg)

![img_2544](https://user-images.githubusercontent.com/6584810/33633127-09439db0-da10-11e7-8617-d8661202f2e0.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If user name is too long to fit on the card with button Chat then end of the username is removed and "..." is shown, like here (from the release 0.9.12):

![screenshot_20171205-225650](https://user-images.githubusercontent.com/6584810/33633281-95561742-da10-11e7-9dd9-2b095d5d56dd.png)
![screenshot_20171205-225654](https://user-images.githubusercontent.com/6584810/33633289-99e7447a-da10-11e7-8b06-344e3ccd2930.png)

#### Actual behavior
[comment]: # (Describe what actually happened.)
If name is too long then it's not cut but button `Chat` is moved outside of the card or outside of the edges
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status 
- Add some contact with a long username e.g. "Username is long enough to check how it's shown on Discover" and some hashtag in status (below username) 
- That contact should add you as a contact too
- Add some hashtag in status (below username) e.g. #test
- As another contact: add some hashtag to the status, e.g. #test
- open Discover
- Check how button Chat is shown next to the long username
- open All for 2 sections: Popular hashtags and Recent Statuses to check how button Chat is shown there

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build 96. Status version 0.9.10-422-g6d5251ad
* Operating System: 
real device Pixel XL, Android 8.0
real device iPhone 6s, iOS 10.3.1

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x677294cf0cc96484c147de0fb2cebb0a185416af98b9fd62684afba3cea590b1](https://etherscan.io/tx/0x677294cf0cc96484c147de0fb2cebb0a185416af98b9fd62684afba3cea590b1)

**Comment by poiga** [comment]
is there an error in the bounty page? https://openbounty.status.im/app shows reward is 0.

**Comment by annadanchenko** [comment]
@poiga contract is still deploying so haven't sent any SNT to it yet

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x9e5d7caa676b6e3ef43d305055812b09708b2432](https://etherscan.io/address/0x9e5d7caa676b6e3ef43d305055812b09708b2432)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by ankitjain28may** [comment]
I would like to fix this

**Comment by SatadruGanguly** [comment]
I want to fix this. How do you begin? Do you have any code to act on?

**Comment by andytudhope** [comment]
What do you mean @SatadruGanguly? All the relevant code is in this repo? If you've not used GitHub before, I'm not sure you'll be able to fix this... Our codebase in this repo is mostly Clojure with some React Native thrown in, so if those are strengths of yours, finding the correct files to fix should not be too hard.

**Comment by foopang** [comment]
Is anyone working on this task? If not, I can submit a fix soon.

**Comment by andytudhope** [comment]
@foopang please go ahead, doesn't seem like we have any PRs submitted for this yet.

**Comment by ScriptsAndCodes** [comment]
Would like to help wth this..

**Comment by churik** [comment]
Issue is still reproducible with Iphone 5S, build 0.9.11d462 
It is not truncated enough for such screen size.
Followed the steps described in issue.
![5s](https://user-images.githubusercontent.com/4557972/34158835-b4906968-e4cf-11e7-99c8-7a96f814897b.png)

**Comment by churik** [comment]
And for Iphone 7 - big gap between name and "Chat" button
![11](https://user-images.githubusercontent.com/4557972/34159607-85024c2c-e4d2-11e7-96cd-9ecdf8f0e877.png)

**Comment by Serhy** [comment]
The same behaviour as above on Android on Popular #hashtags, Recent statuses: 
![screenshot_2017-12-19-16-03-25](https://user-images.githubusercontent.com/8749671/34161649-fa3e81d4-e4d9-11e7-9fc0-0a608e35425e.png)


Similar on 'Popular #hashtags' -> 'All', 'Recent statuses' -> 'All' screen view:
![pop_hashtg_all_4_5_inch](https://user-images.githubusercontent.com/8749671/34161470-7024758a-e4d9-11e7-8b15-05e4f47ebb1a.png)


On a wider screen (5.5”) on Android devices there is the same gap as described above for iPhone7

What happens at the moment on ‘Popular #hashtags’, ‘Recent statuses’ cards on Discover tab is that we have a limit of 20 chars (so 17 chars + three dots). On ‘Popular #hashtags’ -> ‘ALL’, ‘Recent statuses’ -> ‘ALL’ list of cards limit is 30 chars (27 chars + 3 dots) 
So it keeps the issue on small width of screen and introduces the gap on wide screen (like 5.5” devices)
It would be great dynamically fit the ‘Chat’ button next to username length, depending of the screen width.

**Comment by foopang** [comment]
@Serhy @churik fixed again in the latest commit. Please try again.

**Comment by Serhy** [comment]
Dynamic cut of the long names happens right now, yes. However, we cut username too soon. So there is a large gap stays on any screen width:
For instance Android on 4.5” screen:
Popular hashtag/Recent statuses view:
![popular_4_5](https://user-images.githubusercontent.com/8749671/34204308-cc21caf6-e586-11e7-910b-9232b376e5c8.png)

Popular hashtag/Recent statuses -> ‘All’ view:
![popular_all_4_5](https://user-images.githubusercontent.com/8749671/34204315-d18e2c1e-e586-11e7-8171-f9662c0802cf.png)

Android on 5.5” screen
Popular hashtag/Recent statuses view:
![popular_5_5](https://user-images.githubusercontent.com/8749671/34204327-dbf1ec18-e586-11e7-86d9-97d2f05b2c1d.png)

Popular hashtag/Recent statuses -> ‘All’ view:
![popular_all_5_5](https://user-images.githubusercontent.com/8749671/34204333-e1cce692-e586-11e7-8e4f-d0d3c2782476.png)

iOS screens:
Discover view with no Chat button:
![iosdiscover](https://user-images.githubusercontent.com/8749671/34204609-f5882754-e587-11e7-8ece-5eed5c11117c.png)

Popular hashtag -> ALL, iOS view:
![popular_all_ios](https://user-images.githubusercontent.com/8749671/34204625-05c4f7be-e588-11e7-8769-cfc47f20c3e4.png)

Recent hashtag -> ALL, iOS view:
![recent_all_ios](https://user-images.githubusercontent.com/8749671/34204637-1867075e-e588-11e7-8bde-cca7d2155559.png)

@foopang Could you increase, please, the number of chars we display before cut username off?
Also, lets do the same for usernames on cards without Chat button (users own cards - see iOS screen above)

Implementation may look similar to this: 
Calculate the available space for username before chat button (if there is no Chat button then take a width of the card). Calculate width of username, - if username length exceed the available space -> cut username and prolong with three dots.

**Comment by foopang** [comment]
@Serhy Sorry, should have checked more carefully by myself first. It looks fine on Android now for me. I am not able to check on iOS yet, appreciate if you could help me check on iOS.

![screenshot from 2017-12-21 00-35-54](https://user-images.githubusercontent.com/4666757/34217914-bf372712-e5e7-11e7-9688-1b60bede27c5.png)

**Comment by foopang** [comment]
Looks fine too on iOS now...

![simulator screen shot - iphone 5s - 2017-12-21 at 11 04 31](https://user-images.githubusercontent.com/4666757/34238919-397f0ede-e63f-11e7-8c32-cdab09526869.png)
![simulator screen shot - iphone 6 - 2017-12-21 at 11 04 22](https://user-images.githubusercontent.com/4666757/34238921-3f2fff64-e63f-11e7-9189-0d8c52344546.png)

**Comment by Serhy** [comment]
Yes! That looks great now! Thanks @foopang 
Long usernames on Android, iOS on the small and large screens doesn't move Chat button now on Discover neither on Popular hashtag -> ALL, Recent hashtag -> ALL pages.
