### ISSUE TITLE
Offline message after turn on cellular data

### ISSUE THREAD

**Issue by shonefos** [status-im/status-react#2614]
After I turned off the cellular data and started it up again the offline message remained in the chat, I had to do it cold start on iPhone to make the Offline message disappear

*Type*: Bug

#### Expected behavior
[comment]: # Once I'm online , the Offline message should be disappear automatically
![img_6953](https://user-images.githubusercontent.com/6567655/33633765-388ee082-da12-11e7-85b7-f09b4b0a27e0.PNG)

### Reproduction

1. Turn on app ,
2. Turn off cellular data 
3. Turn off app
4. Turn on cellular data

* Operating System: iPhone 6 (11.2)

**Comment by annadanchenko** [comment]
@shonefos Please, review steps to reproduce - I can't reproduce the issue if following them. What I've done:
1. Launch app
2. Sign in
3. Open existing group chat
4. Turn on Flight mode. As a result, see "Offline" grey line in the group chat
5. Close the app
6. Turn off flight mode
7. Launch app
8. Sign in
9. Open group chat -> see no grey "Offline" message

Video might be also helpful.

**Comment by shonefos** [comment]
@annadanchenko https://youtu.be/JEHyjDBqWi4
