### ISSUE TITLE
Message sent when i was offline

### ISSUE THREAD

**Issue by shonefos** [status-im/status-react#2615]
[comment]: Although I was offline, the message was sent to my chat window

*Type*: <Feature>

![img_6953 2](https://user-images.githubusercontent.com/6567655/33634037-14593e5a-da13-11e7-80d8-42740f105f6e.PNG)

#### Expected behavior
[comment]: There should be an answer, the message is not sent

[comment]: # (Android or iOS.)
* Operating System: iPhone 6+ (11.2)

**Comment by annadanchenko** [comment]
@shonefos It looks message is sent and it's shown in the chat. This does not depend if app is offline or not. If it message would get Delivered status then yes it would be an issue. So far, it's just sent to the node that will try to send it to the network when online.
