### ISSUE TITLE
 Don't get a message for repeat password

### ISSUE THREAD

**Issue by shonefos** [status-im/status-react#2618]
After I add the password for the first time again, I get a message to enter the password, so it seems a bit confusing.

*Type*: <Feature>

Expected behavior
After the first entry of the password need to get message / repeat your password"

* Operating System: <iOS>
iPhone 6+

**Comment by annadanchenko** [comment]
@shonefos  Thanks for the bug report! We will re-design on-boarding, so the way password is handled will be changed. Closing it as "won't fix" for now
