### ISSUE TITLE
Placeholder overlaping

### ISSUE THREAD

**Issue by shonefos** [status-im/status-react#2619]
Placeholder overlap under the action 

*Type*: <Bug>

#### Expected behavior
After tapping on the input field, the placeholder should disappear

 ( iOS.)
* Operating System: <Android|iOS>
iPhone 5
iPhone 6+
![img_6961](https://user-images.githubusercontent.com/6567655/33635550-9fcbeb4a-da18-11e7-9639-b2b3b717f2bf.PNG)

**Comment by annadanchenko** [comment]
@jeluard seems like #1286  is back. Can you, please, check if it can be reproduced on your device (as it was before)?

**Comment by shonefos** [comment]
Maybe I got an older version via Testflight.

**Comment by annadanchenko** [comment]
@shonefos if it's iOs 10.X then you can check it in device settings -> general -> Storage & iCloud usage -> Manage Storage -> Status. If iOS 11.X - there is some similar settings but shorter path - somewhere in the Storage, sorry don't have now device to check exact path - will find in about 10 hours

**Comment by shonefos** [comment]
0.9.12(1557.321)

![img_6962](https://user-images.githubusercontent.com/6567655/33636267-bd50a432-da1b-11e7-8404-ff977df8dbe5.PNG)

**Comment by annadanchenko** [comment]
also good idea @shonefos :) so you have 0.9.12 and it looks like we have a regression for the fixed issue

**Comment by shonefos** [comment]
@annadanchenko sorry, I didn't know which is the latest version , good luck :)

**Comment by jeluard** [comment]
@annadanchenko I had this appear sporadically. I guess it never has been fixed.

**Comment by jeluard** [comment]
Some big related changes are in flux so maybe not worth looking at: https://github.com/status-im/ideas/issues/45

**Comment by yenda** [comment]
This is gone
