### ISSUE TITLE
Back button brings user to Discover instead of Popular hashtags or Recent Statuses if Chat was opened from one of these screens

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2620]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User opens Discover -> All (in Popular hashtags), so Popular hashtags screen is opened -> tap on Chat button, so 1-1 chat is opened. After this user taps on "<" to go back. In the released 0.9.12 we go back to Popular hashtags screen. In nightly build we go back to initial Discover screen (this is wrong)

Same issue with Back button if open Chats from Recent Statuses (Discover -> All under Recent Statuses -> Chat button -> `<` button)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- If user was in Popular hashtags screen, opened Chat and goes back by tapping on `<` or Android device button then Popular hashtags screen should be shown (in the same state as before user left it)
- If user was in Recent statuses screen, opened Chat and goes back by tapping on `<` or Android device button then Recent statuses screen should be shown (in the same state as before user left it)
#### Actual behavior
[comment]: # (Describe what actually happened.)
- User was in Popular hashtags screen, opened Chat and goes back by tapping on `<` or Android device button. As a result, Discover screen is shown (not Popular hashtags)
- User was in Recent statuses screen, opened Chat and goes back by tapping on `<` or Android device button. As a result, Discover screen is shown (not Recent statuses)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803590-status/builds/7225894/sessions/11/?accessToken=7ya5mkxXOWPOfO-24m1DqP/PqZ4
- You need to have 2 devices that added each others as contacts in Status. They also need to have some hashtags (e.g #test) in their statuses (field under username in Profile)
- Open Discover
- Tap on All in section Popular hashtags -> Popular hashtags screen will be shown
- in Popular hashtags screen tap on Chat button -> 1-1 chat with a contact is opened
- Tap on `<` button or on Android device back button
- Check the screen shown to you
- Repeat same steps for All in section Recent statuses

### Additional Information
* Status version: nightly build 96. Status version 0.9.10-422-g6d5251ad
* Operating System: 
real device Pixel XL, Android 8.0
real device iPhone 6s, iOS 10.3.1

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8c4386a1c0201a1262e47866488aca7e858febad19591ba5f50ae497ed3708c7](https://etherscan.io/tx/0x8c4386a1c0201a1262e47866488aca7e858febad19591ba5f50ae497ed3708c7)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x05bf21d5c7727b5e37ad147b249c4ea595a2ca96](https://etherscan.io/address/0x05bf21d5c7727b5e37ad147b249c4ea595a2ca96)
Network: Mainnet
Paid to: nrakochy
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
