### ISSUE TITLE
messaging inconsistencies

### ISSUE THREAD

**Issue by kodalim** [status-im/status-react#2621]
### Messages not sent always.

As a tester verifying if Status messages are sent across properly

### Description

[comment]: # Defect
*Type*: Bug

#### Expected behavior
Messages should be working between two Status apps just like Whatsapp

#### Actual behavior
Doesn't work so. After a period of inactivity, when we try to send messages, messages are not received. The online status on phones reflects that they have been active a while ago. At the same time Whatsapp messages are being sent successfully across.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Scenario 1:
- Open Status on Phone A and Phone B and sign in on both.
- Add Phone B contact to A and send a message to B
- Message received by B
- Send message from Phone B to Phone A
- Message received by A
- After a while note that the chat windows are still open
- Send message from phone A to Phone B and viceversa
- Messages not sent
- At the same time send whatsapp messages across 
- Whatsapp messages are successfully received

Scenario 2
- Phone A not signed into Status
- Phone B - Status chat window left from a while ago
- Sign in to PhoneA
- Send message from Phone B to Phone A
- Message received successfully on PhoneA
- Send message from PhoneA to PhoneB
- No message is received
- Sign out from Phone B and sign in again.
- Message now received on Phone B from A

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by annadanchenko** [comment]
@kodalim thanks for the bug report! Please add details about
1. `After a while note` - how much time is it? Like 10 minutes or 2 hours?
2. What are the device models and OS versions of the phone A and phone B?

**Comment by kodalim** [comment]
@annadanchenko 

1. I definitely noticed it after two hours but I also note it always for much shorter times as I am continuing my testing. I see that a big hindrance to my testing. I need to always sign back in to keep getting the messages. If it is due to network, I don't notice such issues with Whatsapp messaging.

2. The device models are Mi Redmi 6.0.1 (Phone B) and Samsung Galaxy 7.0 (Phone A)
