### ISSUE TITLE
Message ordering incorrect if messages are received after a time lag

### ISSUE THREAD

**Issue by kodalim** [status-im/status-react#2623]
### User Story

As a tester, I am verifying if messages sent from one phone are received in the order that have been sent.

### Description
Type - Bug
*Summary*: Messages are not always received in the order that they have been sent. 

#### Expected behavior
Messages sent should be received by the receiver in the order sent

#### Actual behavior
First, there are inconsistencies in sending and receiving of messages. Despite those inconsistencies, one would think that the messages should be received in the order sent. But it is often not.

### Reproduction
- Phone A of android version 7.0 and Phone B of android version 6.0.1
- Open Status in Phone A and sign in
- In Phone B, user is already signed in to Status and chat window open from previous time.
- User from Phone B sends messages to User on Phone A.
- Messages received successfully by User on Phone A
- Sends messages from Phone A user to Phone B User.
- Messages not received by Phone B
- Wait a while
- Send a few more messages from Phone A
- Messages not received by Phone B
-Sign out of Status or exit out of Chat window by clicking Switch users on Phone B
- Sign in to Status now in Phone B
- All the messages that were sent earlier are now received.
- The latter messages are received first.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: testing done on Dec 4th,5th,6th versions

* Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by lukaszfryc** [comment]
Already fixed
