### ISSUE TITLE
User profile edit information isn’t updated for other users iOS

### ISSUE THREAD

**Issue by graemerycyk** [status-im/status-react#2628]
### User Story

As User A, when User B edits his or her information I want those changes to be reflected in User A's chat/contact/search results for User B.

### Description

*Type*: Bug

*Summary*: User information isn’t updated on from one user to another, ie User A updates their status/name/picture and then these changes are not updated in User B's information for User A.

#### Expected behavior
All User profile information when updated by the user is updated in the UI of all other users

#### Actual behavior
Profile updates are not refelcted in the UI of other users

### Reproduction

- Open Status
Part One
- Sign in with User A (choose a user)
- Open the fly out menu
- press the "..." / more actions button
- Edit Status / Name or Image
- Save changes
Part Two
- Go to another user on different device -> open app, login (choose a different user)
- Search or open chat history with the user from part one
- user profile updates will not be reflected in the UI

### Solution
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information

* Status version: 0.9.12

* Operating System: iOS 11.2 iPhone SE

#### Logs

n/a

**Comment by annadanchenko** [comment]
@grycyk thanks for the bug report! How many times can you reproduce it? Like 3 out of 3 attempts. How long have you waited after info was updated? Was it all data (name, status, picture) updated or only part of it? Can you add a video if possible?

**Comment by graemerycyk** [comment]
All data it seems, I have tried several times to update and nothing is pushed through. I can try again with new users?

**Comment by graemerycyk** [comment]
@annadanchenko looks like it has been fixed, now I am seeing the profile updates occurring almost right away! 🙌

**Comment by annadanchenko** [comment]
closing as it can't be reproduced anymore
