### ISSUE TITLE
Invalid predicate error is displayed when the user uses foreign characters in hashtags

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#2635]
### Description

*Type*: Bug

*Summary*: 
invalid predicate error is displayed when the user uses foreign characters in hastags.

#### Expected behavior
The user should be able to type and save foreign characters or get an user friendly message when foreign characters are nor allowed.

#### Actual behavior
invalid predicate error is displayed when the user uses foreign characters to update the profile.

### Reproduction

- Open Status.
- Select the hamburger menu icon at the top left of the from the chat/discover/contacts page.
- Edit the profile and type foreign characters in the description under the profile name: Change the profile name to : **“Darkred tromsø Vulture”** and save, error message from screenshot 3) is displayed.
- Change the profile name to a  name without foreign characters and save, the name is saved.
- Change the status to : “**Não #esquire questions hoje é a comemoração #design development de Juán**” and save, the error message from screenshot 4) is displayed.

1)
![b1](https://user-images.githubusercontent.com/33925578/33664808-cdd6c1c6-da8c-11e7-924c-596636d01ddf.PNG)

2)
![b2](https://user-images.githubusercontent.com/33925578/33664812-cfa2c126-da8c-11e7-849b-59f2b55c74e0.PNG)

3)
![b3](https://user-images.githubusercontent.com/33925578/33664815-d4e05c48-da8c-11e7-97c2-8439652d5c1e.PNG)

4)
![b4](https://user-images.githubusercontent.com/33925578/33665441-e4162c90-da8e-11e7-995f-f7122539542f.png)

### Additional Information

* Status version: 0.9.12 (1557.321)

* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
@ReneeAB thanks a lot for the bug report! Please, specify exact content of the status with foreign characters, so anyone can type the same characters in status and reproduce the issue.

**Comment by ReneeAB** [comment]
Hi @annadanchenko, I included the exact text you need to enter in order to reproduce the issue.

**Comment by foopang** [comment]
Cannot reproduce it in Android emulator (Google Nexus 5 - 6.0.0 - API23 - 1080x1920).

**Comment by andytudhope** [comment]
Difficult to reproduce and likely that this UI will disappear in MVP, so removing bounty labels.

**Comment by annadanchenko** [comment]
Discover feature is removed
