### ISSUE TITLE
Sending Transaction - Choosing the recipient via 'Use Address From Clipboard' results in error

### ISSUE THREAD

**Issue by kodalim** [status-im/status-react#2637]
![screenshot_20171206-161925](https://user-images.githubusercontent.com/34264946/33669855-8ff331a4-dac9-11e7-886b-f2c5bb4606b2.png)
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a tester trying to choose recipient for sending a transaction from the clipboard selection results in error

#### Expected behavior
Should choose the user public key copied to the clipboard

#### Actual behavior
When the user public key is copied from clipboard, it should display the QR code

### Reproduction
- Open and sign in Status
- Choose a contact and view their profile
-In profile choose 'Copy to Clip board' beside the public key
-Select Wallet
- Choose Send Transactipn
- Choose recipient by using the option 'Copy from Clipboard'
- An error is displayed:

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by annadanchenko** [comment]
@kodalim thanks for the bug report! Please, specify 
- Status version, 
- build you are using for testing (link to apk or  is it from PlayStore/TestFligh)
- OS version (e.g. Android 6.0.1)
- device model (e.g. Galaxy S6)

**Comment by jeluard** [comment]
Pasted address is not a proper ethereum address (incorrect format, it is too long).

**Comment by andytudhope** [comment]
Hi @kodalim. It looks like you have tried to use the Public Key there, rather than the address, which is what is needed. Ethereum addresses have the form: 0x27b4eC0EA57F2149AA115DA28C7E6dFC393D3FdB (i.e. a fair bit shorter than what it seems you were trying to pass in there).

**Comment by kodalim** [comment]
Status version: 0.9.12+
Build: From PlayStore
OS version: Android 7.0
Device : Samsung Galaxy Note5/7.0, 

@annadanchenko - Please note the above information. I have tested this on Android version of 6.0.1 on other devices and the behavior is the same. 

@andytudhope - Agree that I have used the Public Key copied in the clip board instead of the address. I  verified using the address in the clipboard and there was no error. However, I would think the correct behavior should be to not enable the clipboard if the clipboard contains something else besides the needed Address. So, this would still be a defect but not a Critical defect.
