### ISSUE TITLE
Status app installation

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2639]
### Description

Type: Bug

_Summary_
Status App not able to install.
#### Expected behavior
Should display install option.

#### Actual behavior
On Lenovo device - OS Android 6.0, on store tried to install, but install option is not visible.
It's displaying as following screenshot(Early Access) -
![screenshot_2017-12-06-20-43-14](https://user-images.githubusercontent.com/20433356/33670230-9baebbd4-daca-11e7-82b3-6178cadd9b0d.png)
On another device(other then Lenovo other 2 different devices) it's displaying as following screenshot.
![screenshot_20171206-204620](https://user-images.githubusercontent.com/20433356/33670353-df009646-daca-11e7-8b4a-c581bc93be8a.png)

**Comment by andytudhope** [comment]
Hi @Monali109! Thanks for the report. Our App Store invites are full, but you can always get the latest nightly apk files from here: http://artifacts.status.im:8081/artifactory/nightlies-local/

Just navigate to that link on your phone and click on the lastest .apk file and give it permission to install on your device. These are not necessarily stable, but at least you can see all the latest developments and changes.
