### ISSUE TITLE
Cleanup react-native source folder

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2640]
### User Story

As a developer, I want to remove useless code.

### Description

React Native way of loading images (via `require`) used to be an issue when running tests under `nodejs`. This is not the case anymore.

Code in [react-native/resources](https://github.com/status-im/status-react/blob/develop/react-native/src/status_im/react_native/resources.cljs) should be integrated in the main `src` structure. Remove the now useless [test glue](https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/react_native/resources.cljs) and make sure tests still pass.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0xa194b6de9ed0eed3ed7044a4bf0beae92a8b8f95](https://etherscan.io/address/0xa194b6de9ed0eed3ed7044a4bf0beae92a8b8f95)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
