### ISSUE TITLE
Allow to send/request ERC20 token: command

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2643]
### User Story

As a user, I want to send ERC20 tokens from the chat.

### Description

Modify the `send` and `request` commands so that they support ERC20 tokens.

*Type*: Feature

**Comment by jeluard** [comment]
Postponed due to MVP changes: `send` and `request` will be simpler and only accept `contact` as an optional argument.
This requires deep linking support and changes to the API.

**Comment by chadyj** [comment]
Dupe of https://github.com/status-im/status-react/issues/3233 and https://github.com/status-im/status-react/issues/3234
