### ISSUE TITLE
Displaying an error on UI

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2644]
### Description

 Type: Bug

*Summary*: ...
Sign in status. Go to contacts list. click on State of the DApps option. Displaying an error on UI as Undefined is not an object(evaluating 'u[n]'). 
![screenshot_2017-12-06-22-22-40-360_im status ethereum](https://user-images.githubusercontent.com/20433356/33674411-6dd0b61c-dad5-11e7-8f52-b18b99ff8fb7.png)

#### Expected behavior
Shouldn't display an error on UI
#### Actual behavior
Displaying an error as undefined is not an object.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...0.9.12

* Operating System: Android - 6.0

**Comment by annadanchenko** [comment]
@Monali109 Please, search for the known bugs before reporting new one. We are happy that you help but regret you will waste time for reporting already known issues. If search for "undefined is not" phrase then you can find  #2577 

I'm closing this one as it's a duplicate bug report
