### ISSUE TITLE
Status and usernames are not properly updated in some cases, as a result, some messages do not reach the recipient.

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#2648]
### Description

*Type*: Bug

*Summary*:
Status and usernames are not properly updated in some cases, as a result messages to not reach the recipient.

#### Expected behaviour
When a users change their status and name, they should see their updated status and name on the discovery page and the chat, the others users should see the changes as well on the discovery page and on the chat.

#### Actual behaviour
When a users change their status and name, they will see their updated status and name however, the others users will see the updated status but they will still see the old name, not the updated name. And message sent by others users on the chat will not reach the user whose name were not properly updated.

### Reproduction

- User 1 opens Status using an iPhone (iOS)
- User 2 opens Status using Samsung (Android)
- As User 1, navigate to the "Discover" page and stay there.
- As User 2, edit you profile then, edit and change your status and your name, save.
- User 1 will see the new status and the new name on the discovery page, everything is correct.
- As User 2, navigate to the "Discover" page and stay there.
- As User 1, edit your profile then, edit and change your status and your name, save (see screenshot 1).
- User 2 will see the new status however, the name has not been updated and the old one is still displayed (see screenshot 2).
-  As User 2, on the "Discover" page, tap the "Chat" button displayed next to User 1 name on the Chat page, the User 1 previous status and name are still displayed on the chat.
-  As User 1, select the chat with the new message on the "Chat" page, notice that on the User 2 update name is correctly displayed on the chat but User 2 previous status is still displayed.
- As User 2 send a text to User 1 on the chat, User 1 will see the text.
- As User 1 send a text to User 2 on the chat (reply to User 2 using the same chat), User 2 will not see the text.

**Note:** 
Screenshot 4) shows User 2 screen and Screenshot 5) shows User 1 screen after exchanging messages. 
User 2 sent "Hello Test 0" which User 1 received but, User 2 did not received "Hello test 1" sent by User 1. Later on, User 1 sent "Hello test 2" which User 2 received.

1) 
![img_2043](https://user-images.githubusercontent.com/33925578/33688549-af187972-dad3-11e7-95d9-7ed4fee1d44b.PNG)

2)
![screenshot_20171206-214319](https://user-images.githubusercontent.com/33925578/33688590-dd2e3842-dad3-11e7-8c5d-95530aa1e450.png)

3)
![screenshot_20171206-220010](https://user-images.githubusercontent.com/33925578/33688626-f952a74c-dad3-11e7-97df-ac073045c8ac.png)

4)
![screenshot_20171206-222831](https://user-images.githubusercontent.com/33925578/33689368-15fb0be8-dad7-11e7-8f4c-e6dd6f3ed42c.png)

5)
<img width="320" alt="file_001" src="https://user-images.githubusercontent.com/33925578/33690335-fc30bdbc-dada-11e7-82dd-7c92d8670226.png">

### Additional Information

* Status version: 0.9.12 (1557.321)

* Operating System: Android, iOS

**Comment by graemerycyk** [comment]
possibly related to #2628 ?

**Comment by ReneeAB** [comment]
Hi @grycyk , I just read issue #2628 and I can confirm that it is the same issue.

**Comment by ReneeAB** [comment]
Issue closed as duplicated of #2628
