### ISSUE TITLE
Reorder groups option on User Interface unable to reorder

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2650]
### User Story
1. As a User I want to Reorder the groups. 
2. As a Tester I want to test the UI of option Reorder groups & see that I am able to reorder the groups.

### Description
 Type: Bug
*Summary*: ...
1.Sign in to status.
2.Select Contacts option.
3.Select the option Reorder groups.

#### Expected behavior
After Selecting Reorder groups on UI, User should be able to reorder the groups, using drag & drop.**Reorder Alphabetically**, or according to User selection should be able to reorder.

#### Actual behavior
Here after selecting the option Reorder groups, UI components not able to drag & drop or reorder.
Please see the attached screenshot.
![screenshot_2017-12-07-12-23-45-334_im status ethereum](https://user-images.githubusercontent.com/20433356/33705859-f5ea98c4-db57-11e7-97c2-35c0a3319453.png)

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: After clicking the option **Reorder groups** , User should be able to drag & drop according to User's selection or move the items on UI & should be able reorder &  **Save**.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
Same on latest build
* Operating System: Android 6.0.1

**Comment by annadanchenko** [comment]
Contacts tab and groups are removed
