### ISSUE TITLE
Wallet: Asset screen does not match UI mocks

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2652]
### Description

*Type*: Bug

*Summary*: I will list the UI discrapencies which are currently taking place in ERC20 implementation (https://github.com/status-im/ideas/issues/3)

#### Expected behavior

- Asset main screen: https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/5991fb08dd2ec4ce5e3978c5
- Wallet main screen:
https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/5991fb488fea42dc85f90b5e

#### Actual behavior

1. Asset main screen: **Android**

- [ ] remove the gray line under Token name
- [ ] adjust `SEND SNT`, `EXCHANGE`, `REQUEST` buttons
- [ ] add devidors for `SEND SNT`, `EXCHANGE`, `REQUEST` buttons
- [ ] make tabs naming in bold
![image](https://user-images.githubusercontent.com/28752642/33709471-8f82b6ce-db4e-11e7-9dbb-5944db57e87b.png)

2. Asset main screen: **iOS**

- [ ] make tabs naming in bold and lowercase (starting with Uppercase)
- [ ] make lables under asset name in bold
- [ ] add missing horizontal line above Transactions list
- [ ] make `SEND SNT`, `EXCHANGE`, `REQUEST` buttons in bold
- [ ] make devidors for buttons thiner

![image](https://user-images.githubusercontent.com/28752642/33709692-36122b1e-db4f-11e7-8d18-2725f6ed1d7f.png)

**Comment by jeluard** [comment]
Removed from current scope.
