### ISSUE TITLE
'Error registering name' after sending a transaction to dApp

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#2653]
### Description

*Type*: Bug

#### *Summary*: The error is shown after creation of an auction.
 Please note, the error is shown in dApp, however the issue should be on our side:
* **The issue first occurred in im.status.ethereum-6d5251.apk (05-Dec-2017 19:01)**
* **The issue can not be reproduced in im.status.ethereum-afd7fc.apk (05-Dec-2017 03:15)**

#### Expected behavior
Auction is created, 'You are the proud owner of the name: Auction Name'' caption is shown 

#### Actual behavior
<img width="353" alt="screen shot 2017-12-07 at 11 33 02 am" src="https://user-images.githubusercontent.com/12611990/33711161-4a3deb3e-db43-11e7-93bf-9a587d282859.png">

### Reproduction

- Open Status
- Request some ETH in Console via /faucet
- Go to Contacts -> dApps
- Tap on Acution House dApp
- Tap on Create an auction
- Enter unique name to 'Register Name' input
- Click on 'Register Name'
- Tap on Sign transaction
- Provide valid password and tap on Sign transaction. As a result, Transaction Sent screen is shown
- Tap on Got It
- Scroll the page to 'Ethereum Status' section

### Additional Information
* Status version: 0.9.10-427-ga68f0652+
* Operating System: Android

**Comment by annadanchenko** [comment]
Can reproduce on nightly build from Dec 7
 0.9.11d523 (2080)
TF (iOS real device): https://app.testfairy.com/projects/4803590-status/builds/7452263/sessions/16/?accessToken=/F8oSNaEJBwWXzv/d/7rH1R5zjI

**Comment by oskarth** [comment]
@rasom do you think you have time to look at this?

**Comment by rasom** [comment]
https://github.com/status-im/status-go/issues/547

**Comment by adambabik** [comment]
I tried to reproduce this issue on iOS and couldn't do it:

<img width="280" alt="screen shot 2018-01-11 at 17 09 10" src="https://user-images.githubusercontent.com/277870/34834454-523cec16-f6f2-11e7-9880-ba8e5c7ce392.png">
<img width="280" alt="screen shot 2018-01-11 at 17 09 48" src="https://user-images.githubusercontent.com/277870/34834470-574cbb5a-f6f2-11e7-9326-801601461e04.png">

**Comment by oskarth** [comment]
@adambabik Hm, but you reproduced the failing sequence that @rasom found on status-go side right? Do you think this isn't the problem?

**Comment by adambabik** [comment]
@oskarth no, I could not reproduce the problem with a test using neither local nor remote node.

**Comment by annadanchenko** [comment]
verified ok on release candidate and nightly builds (0.9.11d600), ios and Android
