### ISSUE TITLE
Wallet: Missing (default) icons for assets

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2655]
### Description

*Type*: Bug

*Summary*: There is a hardcoded (for now) list of tokens under Mainnet and some of them are displayed with default picture. 

#### Expected behavior
I want all tokens that are avaliable shown with associated icon

#### Actual behavior
Missing icons for the following tokens:

`REP`, `AdEx` + `Metal` + `Target Coin` + `BitDice` + `Enjin Coin` + `AVT`, + `TIME` + `PRG`

![image](https://user-images.githubusercontent.com/28752642/33716555-b4cc8586-db67-11e7-9af6-b66a1a2ef7aa.png)

### Reproduction
- Open Status
- Change network to Mainnet
- Go to Assets list

@denis-sharypin please assist with that when you have time

**Comment by denis-sharypin** [comment]
Hey, @asemiankevich we decided to go with ≈100 popular tokens (at that moment) for our MVP. We have to come up with a process of adding remaining token pics
