### ISSUE TITLE
Inadequate behaviour of the "chat name" input in the "new group chat" form

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#266]
![ezgif-88600092](https://cloud.githubusercontent.com/assets/2364994/18809414/35048f9e-8283-11e6-8708-c24003844fd9.gif)

**Comment by rasom** [comment]
Perhaps the same issue #253

**Comment by alwx** [comment]
https://github.com/status-im/status-react/pull/273 fixes this problem
