### ISSUE TITLE
AuctionHouse Dapp - Initiating transactions 

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2660]
### Description

Type: Bug

*Summary*: ...
Sign in Status
start AuctionHouse Dapp
click on create auction.

#### Expected behavior
Should validate _before_  initiating transactions, that, Wallet Balance > 0 ETH.

#### Actual behavior
Please see the attached screenshot.
![screenshot_2017-12-07-21-15-57-579_im status ethereum](https://user-images.githubusercontent.com/20433356/33728157-8cd5d112-db9f-11e7-9e7a-6e8ec0bebdb1.png)

### Solution
Before initiating transaction should validate that Wallet Balance > 0 ETH

* Status version: ...0.9.12

* Operating System: Android 6.0.1

**Comment by annadanchenko** [comment]
not a Status app issue. Dapp can choose what to do but we can't fix it as it's in scope of the Dapp
