### ISSUE TITLE
Scroll view doesn't seem to be implemented on the DApp profile view iOS (see link for screenshot)

### ISSUE THREAD

**Issue by graemerycyk** [status-im/status-react#2662]
### User Story

As User when I open a DApp profile I want to be able to scroll to see the whole page.

### Description

*Type*: Bug

*Summary*: When the a DApp is opened from the "Discover" tab is open and you are looking at the whole view, if the DApp has a long "Description" then this can lead to the URL being below the screen and a scroill view is not implimented here it seems. See screenshot -> http://share.xctest.io/TYsTnB

NOTE: "Dynamic Type" (iOS system text size) could also play a part in this issue occuring.

#### Expected behavior
Whole page should be scrollable if loading below the view.

#### Actual behavior
Scroll view not implimented.

### Reproduction

- Open Status
- Sign in
- Open "Discover" tab
- Oen Melonport
- URL isn't 100% visible
- 
### Solution
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information

* Status version: 0.9.12

* Operating System: iOS 11.2 iPhone SE

#### Logs

n/a

**Comment by goranjovic** [comment]
Hey, thanks for the report @grycyk 
Do you have a non-default system text size, i.e. is this why you suspect that dynamic text size may have some effect on this?

**Comment by asemiankevich** [comment]
I can reproduce it on 4 " screen with the following device config (iOS): settings -> Display and Brightness -> Text Size -> Move the slider to maximum value. NOTE: restart Status to apply changes.

@goranjovic I would say we need to think about this a bit more since that change ^ reflects though all the app UI

**Comment by graemerycyk** [comment]
@goranjovic yeah, was a hunch I had, the text is not too large, and I normally use a little larger font type to QA on iPhone in general to check these sorts of issues and general font issues.

Just fyi is the default setting -> http://share.xctest.io/HaRrll and this is what i normally use -> http://share.xctest.io/G3DLvl 🙌
