### ISSUE TITLE
Edit chat/ Delete chat feature on UI

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2666]
### Description
Any text of message is editable, only after sending them or typing. If nothing messages are there on UI, means there is nothing to delete or edit or no chat then **Delete chat** option, shouldn't be enable. 
Type: Feature

#### Expected behavior
Option **Delete chat**, this should be enable only when there are any messages/chat. If no messages are there it should be disable.

#### Actual behavior
Before sending any messages/chat, Delete chat option is enable & after clicking on that, that contact itself getting deleted.
Please see the attached screenshot.
![deletechat](https://user-images.githubusercontent.com/20433356/33754404-1167a4ba-dc12-11e7-9d91-7da8055abef6.png)

### Additional Information

* Status version: ...0.9.12+

* Operating System: Android 6.0.1

**Comment by annadanchenko** [comment]
@Monali109 Delete chat feature does not delete messages in the chat. It deletes a chat from the list in Chats. Let's say you have 20 chats and want only 5 of them to be shown on Chats tab then you use Delete Chat for the rest of 15 chats. No matter if they contain messages or not. So, the feature works now as expected and deletes a chat.

Regarding Actual behaviour description:`Before sending any messages/chat, Delete chat option is enable & after clicking on that, that contact itself getting deleted.` Contact can be found on Contacts tab. For example, there is "Oaken Water Meter" contact in Contacts. If you open it then new chat "Oaken Water Meter" is shown in Chats. If you delete chat with "Oaken Water Meter" on Chats then only this chat is deleted. Contact "Oaken Water Meter" is still available in Contacts. So all works as expected.
