### ISSUE TITLE
After changing the language settings in Phone, app's language is not changing according to changed language settings

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2667]
### Description
After changing to language settings app also should display according to changed language.
 Type: Bug

#### Expected behavior
Changed the language input settings in phone. All app's language changed according to that. Here status app's not getting sync with phone's language settings(after changing the language from english to any other language.)

#### Actual behavior
Please see the attached screenshot. 
![phonesettings](https://user-images.githubusercontent.com/20433356/33757519-8c1d017e-dc20-11e7-9773-6994103f668a.png)

### Additional Information
* Status version: ...0.9.12

* Operating System: Android 6.0.1

**Comment by annadanchenko** [comment]
@Monali109 It's expected, we do not translate app name
