### ISSUE TITLE
Remove dependency on user.clj

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2669]
### User Story

As a developer, I want to have a predictable environment.

### Description

`user.clj` is loaded automatically by clojure runtime. This loading can't be controlled.
This is an issue as we are using it to setup and load figwheel dependencies even when it's not required.
e.g. `lein cljsbuild once android` never terminates 

The modern way to manage complex `figwheel` workflow is to rely on [figwheel API](https://github.com/bhauman/lein-figwheel#scripting-figwheel) and run it via `lein run -m clojure.main --init`. This will also allow to have all figwheel related code in a single location (currently spread in `env/dev` and `user.clj`).

*Type*: Feature

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x5dff394cb22e3c4f3ba71e8f5773ad98ebe126c4](https://etherscan.io/address/0x5dff394cb22e3c4f3ba71e8f5773ad98ebe126c4)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
