### ISSUE TITLE
Augur App - Unable to open

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2672]
### Description

 Type: Bug

#### Expected behavior
Sign in to  Status.
Open DApp - Augur
App should be able to open

#### Actual behavior
Unable to connect to network.
Please see attached screenshot.
![screenshot_2017-12-08-19-59-00-769_im status ethereum](https://user-images.githubusercontent.com/20433356/33770350-3e32a7c4-dc53-11e7-8bf0-fc05c8c1020f.png)

Same for other DApp - Melon port also.
![screenshot_2017-12-08-20-15-13-223_org mozilla firefox](https://user-images.githubusercontent.com/20433356/33770978-6f299c46-dc55-11e7-91da-9c1e1d786f53.png)
After selecting _open in web browser_  option also, unable to connect.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ... App reinstalled from url- 
http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk  

* Operating System: Android 6.0.1

**Comment by asemiankevich** [comment]
Hi @Monali109 ! Thanks for reporting this. This behaviour is no longer present in latest nightly build (http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk) P
