### ISSUE TITLE
After Reinstallation app, @browse cmd not working

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2673]
### Description

Type: Bug

#### Expected behavior
Should work @browse cmd & message shouldn't receive from unknown contact.

#### Actual behavior
1. Messsage received from unknown contact.
2.@browse command not working. Previously it was working.
![unknownct](https://user-images.githubusercontent.com/20433356/33773373-a412bd72-dc5d-11e7-925c-01c3373f58f2.png)

* Status version: ...App reinstalled from url-
http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk
* Operating System: Android 6.0.1

**Comment by asemiankevich** [comment]
@Monali109 Seems you are observing some known problem (https://github.com/status-im/status-react/issues/2661) that is already fixed in http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk. Would you mind to check this new build?
