### ISSUE TITLE
After clicking on Phone number - Edit option displaying an Error

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2674]
### Description

Type: Bug

#### Expected behavior
Shouldn't display error.

#### Actual behavior
Sign to status.
Go to edit  - phone number option & click.
It's displaying an error. Please see attached screenshot.
![nullobject](https://user-images.githubusercontent.com/20433356/33774871-ae81307c-dc62-11e7-96ca-d41b7b3acf6c.png)

### Additional Information

* Status version: ...After Reinstallation

* Operating System: Android 6.0.1

**Comment by asemiankevich** [comment]
@Monali109 could you please specify build and device? I dont see this error in last nighlty http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk

**Comment by Monali109-zz** [comment]
@asemiankevich   Re installed from this url - 
http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk , 
still exists same error.
Device -  Redmi Note 4
OS - Android 6.0.1

**Comment by asemiankevich** [comment]
@Monali109 that looks very odd to me, I can't find your session in TestFairy. Can you please try again? Also , i did the same on my Xiaomi and still can't reproduce this issue https://app.testfairy.com/projects/4803622-status/builds/7268381/sessions/31/?accessToken=tHiWi05ogqL4DtPjYVWn-1kcubg

**Comment by Monali109-zz** [comment]
@asemiankevich  Please see, done screen recording.
https://drive.google.com/file/d/12H-7cOTLMbDL7xbAmSo04TryfREUu000/view?usp=sharing

**Comment by Monali109-zz** [comment]
@asemiankevich  Re tested twice, now not able to reproduce. Fixed. Thanks. Closing for now

**Comment by Monali109-zz** [comment]
@asemiankevich  Twice didn't display error, but after sometime, it's still  reproducible.

@asemiankevich  After reinstallation latest app, the account which is created with previous version exists. So after reinstallation with new version the account which is created for that initially this error doesn't display. After swicth user & open the account which was created with previous version & click  on edit - phone number , then swicth User & sign to another account which created with latest version. Then again it's reproducible.

**Comment by annadanchenko** [comment]
@Monali109 we support upgrade only from the released version (available on PlayStore or TestFlight). Please, see https://wiki.status.im/How_to_help_with_testing for the procedure 

When reporting issues on upgrade, please, specify initial version of Status app and the Status app version after the upgrade. In case you perform upgrade where initial version in not the released one - it's not a valid issue and should be closed.

**Comment by Monali109-zz** [comment]
@annadanchenko  ok. Thanks
