### ISSUE TITLE
App stopped, after clicking on Wallet Assets & On Mobile screen it's displaying an error summary

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2676]
**### Description**

**Type**: Bug

**_Summary*: ..._**
1.Sign to Status.
2.Go to wallet option.
3.click on Assets STT.Please see attached screenshot.
![assertfailed](https://user-images.githubusercontent.com/20433356/33794202-51e7b9ae-dced-11e7-834f-88f185dfe2cb.png)
4.click on ok. click on ETH.(Screen is displaying an error)
![java](https://user-images.githubusercontent.com/20433356/33794213-80a34e20-dced-11e7-98d9-bb2b286abd4c.png)
5. After that it's displaying as following screenshot.
![status](https://user-images.githubusercontent.com/20433356/33794215-90caa78a-dced-11e7-9471-d36c81958bd4.png)
6. View Summary 
![bugsummary](https://user-images.githubusercontent.com/20433356/33794259-3fff3734-dcee-11e7-9f5b-e233a9b657f7.png)

#### Expected behavior
Application shouldn't stop/close.

#### Actual behavior
As explained in Summary.

### Additional Information
* Status version: ... Reinstalled from url -
http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-f22796.apk

* Operating System: Android 6.0.1

**Comment by asemiankevich** [comment]
Hi @Monali109 ! Thanks for reporting this problem! This is already fixed in latest develop, would you like to check http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk ?
