### ISSUE TITLE
lein prod-build throws exceptions when using Java 9

### ISSUE THREAD

**Issue by jameszaghini** [status-im/status-react#2678]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to follow the build instructions so that I can build and run the project.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I followed the [build  instructions](https://github.com/status-im/wiki.status.im/blob/master/docs/contributing/development/building-status.md)
and installed the dependencies.

`lein prod-build` threw an exception

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Running `lein prod-build` should run successfully.

#### Actual behavior
[comment]: # (Describe what actually happened.)

> Compiling ClojureScript...
> Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Install [dependencies](https://github.com/status-im/wiki.status.im/blob/master/docs/contributing/development/building-status.md)

Note, brew installed java version 9.0.1 and this seems to be the cause based off this discussion:
https://github.com/bhauman/lein-figwheel/issues/612

Then run `lein prod-build`

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)

add this line to `project.clj`:
`:jvm-opts ["--add-modules" "java.xml.bind"]`

I'm not really familiar with Clojure/Java so I don't want to open a PR and have it break for others with a different environment.

### Additional Information
[comment]: # (Please do your best to fill this out.)

Commit ee2904efcc6b6622767d7d66d0bb65bcefc3d194
macOS 10.13.1
java 9.0.1

**Comment by andytudhope** [comment]
@jameszaghini did you try run our new script with `./scripts/setup-osx`? We are in the process of merging some PRs which also set up everything correctly for Linux and will update the instructions as soon as that is done in one go. Meanwhile, that script should set up everything correctly for you...

**Comment by jeluard** [comment]
@jameszaghini Thanks for the report!

This is a tooling issue that has been [fixed](https://dev.clojure.org/jira/browse/CLJS-2377). We just have to wait for next ClojureScript release.

In the meantime I suggest you continue to rely on your fix!
