### ISSUE TITLE
Location selection is not displayed after /location command was called in chat (Android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2680]
### Description

*Type*: Bug

*Summary*: When `/location` comamnd was called in 1x1 chat - endless spinner is show to end user, however map is not displayed, as well as location selection is not avaliable

#### Expected behavior
Map is shown after `/location` command is called

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/33823659-f2fddf82-de6c-11e7-9eb8-83b981f8ff03.png)

### Reproduction

Enable your GPS on device first

- Open Status
- Go to 1x1 chat with Jarrad
- Call /location command - grant permissions when asked

### Additional Information
* Status version: `0.9.10-431-g7f028ef5+`
* Operating System: Android, real device LV V20, android 7.0
* Not reproducible for iOS

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/7245823/sessions/3/?accessToken=bMPORCmjPSU2mFssYMDwwpfLf5o

**Comment by annadanchenko** [comment]
Location command is removed
