### ISSUE TITLE
Picture in user profile is not updated when selecting from gallery or capture [2217]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2682]
### Description

*Type*: Bug

*Summary*: Can't update picture niether selecting from gallery nor capturing

#### Expected behavior
Profile picture is updated

#### Actual behavior
Profile pictrure remains default

### Reproduction

- Open Status
- Go to profile-> Edit -> Select from gallery
- Edit -> Capture

### Additional Information
* Status version:  0.9.10-433-g25ec3602+ (1990)
* Operating System: Android
* TF https://app.testfairy.com/projects/4803622-status/builds/7246163/sessions/6/?accessToken=zv5r3ev/n0u-/zvNZ1Juf9JnUQo

**Comment by yenda** [comment]
Fixed in the branch

**Comment by asemiankevich** [comment]
Fixed in branch `0.9.10-438-g6948dd17+`
