### ISSUE TITLE
Do not run sync state loop on upstream RPC networks

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#2683]
We don't need sync state on upstream RPC networks because they do not need to sync

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0x0abeadbb9e15b734a37e38cc6bd585b539f771d8](https://etherscan.io/address/0x0abeadbb9e15b734a37e38cc6bd585b539f771d8)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by foopang** [comment]
Not sure if I understand the requirement correctly, but I wanna give it a try. So here is the PR https://github.com/status-im/status-react/pull/2799

**Comment by flexsurfer** [comment]
you understand correctly, thanks @foopang , i just added small comments in PR

**Comment by asemiankevich** [comment]
@flexsurfer @foopang no syncing indicator on main wallet  when on Rikeby / Ropsten?
