### ISSUE TITLE
Send location is running in infinite loop

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2686]
### Description
Sign to Status.
Go to chats.
Select Contact 
click on /location
Select Deny
After selecting Deny also, app is trying to Send the location & screen is appearing as following screenshot.
![sendloc](https://user-images.githubusercontent.com/20433356/33834896-a5ed4cc6-deaa-11e7-9deb-098de035b318.png)
Note - Please see Time is also varying with actual  time & app time.
*Type*: Bug

*Summary*: ...
After selecting Deny, then it shouldn't send the location. 

#### Expected behavior
After selecting Deny, then app shouldn't send the location. 

#### Actual behavior
It's sending the location after User deny, then also & running in infinite loop.

### Solution
Should verify whether User is allowing or denying to send the location.

### Additional Information

* Status version: ...
artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk

* Operating System: Android 6.0.1

**Comment by asemiankevich** [comment]
@Monali109 Hi this is known issue reported (https://github.com/status-im/status-react/issues/2680) so I will close this one to aviod duplicates
