### ISSUE TITLE
Tap on Deny to Status app to send/view sms, then also app is sending the confirmation code - /Phone 

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2688]
### Description
Sign to Status.
Go to Console
click on  /Phone.
Enter Phone number - Pop up message will display that - Allow Status to send //view sms ?
Click on Deny on UI
![phoneview](https://user-images.githubusercontent.com/20433356/33846403-ba2c485a-decc-11e7-982e-a525e1ed278f.png)
After clicking on Deny option then also confirmation message app is sending.
![confirm](https://user-images.githubusercontent.com/20433356/33846426-cd598c8a-decc-11e7-931f-5015e7d0d9aa.png)
*Type*: Bug

*Summary*: ...
Please see Description.

#### Expected behavior
After clicking on Deny to send messages, app shouldn't send messages/confirmation code.

#### Actual behavior
As explained in Summary
Tap on Deny action is behaving contradictory.
https://drive.google.com/file/d/1xL1_pXCucJNw2mQ0jfaGdfKHsTy6FQz3/view 

### Additional Information

* Status version: ...
latest build
[comment]: # (Android or iOS.)
* Operating System:  Real Device - Android 6.0.1

**Comment by annadanchenko** [comment]
Phone feature is removed
