### ISSUE TITLE
Online/Offline & Blockchain Synchronisation Indicators

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#269]
Currently theres no visual feedback for the user to know if they are in sync with the blockchain and online/offline.

**Comment by andmironov** [comment]
Could you please provide some details about the moment when the sync will be happening. If would take place in chat screen then it could look like this (the throbber line's backgroud gradient should animate to indicate that the process)

![sync](https://cloud.githubusercontent.com/assets/3115606/18933982/fc24dbf6-85df-11e6-8271-35355bc4a5af.png)

**Comment by jarradh** [comment]
Sync will be happening as a background process, it'll start immediately from application open, and periodically from time to time.

The user may or may not be within a chat (so indication on any screen), animating gradient is great - can you provide an animation of the colour switch?

Offline looks fine as well.

**Comment by andmironov** [comment]
Updated image below and a prototype here http://share.framerjs.com/gqxy070ggvyd/
![sync](https://cloud.githubusercontent.com/assets/3115606/18996907/e65ab19a-873a-11e6-9ca1-58a2cea1f7fe.png)

**Comment by jarradh** [comment]
Where can we find the assets for the anim?

**Comment by andmironov** [comment]
Uploaded to Zeplin https://zpl.io/Z2q1Yli with a description. Will be adding more detailed descriptions and spitting screens to states for other parts of the app as well.
