### ISSUE TITLE
Recover access does not have error validation

### ISSUE THREAD

**Issue by gholmes86** [status-im/status-react#2693]
Description
Type: Bug

When entering an invalid recover access paraphrase(less than 12 words) and invalid password, no error message is displayed for incorrect information.  Error checking is needed for recover access

[comment]: # ()
![recoveracess](https://user-images.githubusercontent.com/9959969/33868168-0251e9b0-dec7-11e7-90f3-3340943bb54f.PNG)

*Summary*: ...

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Load the application
Click Recover access
Enter an invalid Paraphrase
Enter an invalid password
Click Recover access button

Expected: Error message should display for invalid paraphrase and password

Actual: No message displays

### Additional Information
Status version:0.9.12(1557.321)
Device:iphone7
Version:10.3.3
OS:iOS

**Comment by yenda** [comment]
done
