### ISSUE TITLE
Offline inboxing iteration 1: Support public chat

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2701]
### User Story

User A enters public chat room X. User A goes offline and people keep chatting. When User A comes back they instantly see all the missed messages in X.

### Description

*Type*: Feature

*Summary*: Add support for group chat

#### Expected behavior
User A enters public chat room X. User A goes offline and people keep chatting. When User A comes back they instantly see all the missed messages in X.

#### Actual behavior
When User A they don't see all missed messages in X.

### Solution
*Summary*: 

- [x] Cherry-pick / use https://github.com/status-im/status-react/pull/2670 as starting point
- [x] (Optional) Update to latest status-go develop artifact
- [x] Ensure you can reproduce for 1on1 chat and see "offline inbox" logs
- [x] Add filter for public chat with allowp2p under offline inbox flag
- [x] Make a test protocol (see https://github.com/status-im/status-react/issues/2664) where success/fail is apparent depending on flag on or off
- [x] If it isn't this straightforward, check logs with 'offline inbox' and begin to understand why / decompose into additional tasks

### Additional Information
Check difference between public chat and group chat. AFAIK it should be same thing but might not be. Right now main capability is public chat.

**Comment by dmitryn** [comment]
Testing how it works in group chats. It seems working well, the only thing i've noticed is the warning:
```
[warn][tid:com.facebook.react.JavaScript] WARN [status-im.protocol.web3.delivery:163] -
 :shh-post-error Error: invalid argument 0: 
json: cannot unmarshal non-string into Go value of type hexutil.Bytes 
{:sig "0x04fce15dcb084db53453a1328a7cde44d2f7820009897ca268a0dc58059367ddc52bf85e8bf39fa5553c6b6a8537158415f57958f4d72ccbb06f18541b71b27986", 
:topic "0xaabb11ee", 
:payload "0x7b3a6d6573736167652d69642022313531333130373539323836382d37646438366130392d356337372d353836632d626332302d356131623363613630646631222c203a67726f75702d69642022313531333130373537393734312d66396434396264652d396137622d353561632d623430372d353062353133393834643331222c203a636f6e74656e7420227b5c2269765c223a5b2d3139333939323733362c3634373035323131312c2d323130373135313438342c2d3938343234313538355d2c5c22765c223a312c5c22697465725c223a313030302c5c226b735c223a3132382c5c2274735c223a36342c5c226d6f64655c223a5c2263636d5c222c5c2261646174615c223a5c225c222c5c226369706865725c223a5c226165735c222c5c2263745c223a5b2d313434393532303639302c2d323038353038373935312c3538373535343535315d2c5c227461675c223a5c223436333064393831316130343338303663383036346261363465356434623263353631633166306561333361323961666137393263643761346162366633613539303532316131616566383130306234613339373838643062316633666435393063636330336135376462326132336132396133636662356566666330626531346439313738663464386361653730363862303838363730323965366339323861313863376234656433323132306635313533383065366433643639386463305c227d222c203a757365726e616d65206e696c2c203a74797065203a67726f75702d6d6573736167652c203a73686f773f20747275652c203a636c6f636b2d76616c756520312c203a72657175697265732d61636b3f20747275652c203a636f6e74656e742d747970652022746578742f706c61696e222c203a74696d657374616d7020313531333130373539323930377d0a", 
:pubKey nil, 
:ttl 60}
```

I get this immediately after sign in (with existing group chat  but with no new chat messages in it)

UPD: notified @JekaMas about this warning

**Comment by dmitryn** [comment]
>(Optional) Update to latest status-go develop artifact

There is no artifactory build for https://github.com/status-im/status-go/commit/ba6c96532bfdfcc1bc95d5535d3d6b04ee7de49e yet, not sure i need to build it myself with `make statusgo`. Still good to use `feature-add-enode-to-requestMessages-params-g4509f423-41`

UPD: not relevant, updated to latest develop build

**Comment by annadanchenko** [comment]
@dmitryn @oskarth #2701 is mixing terms "public" and "group" chats.

Summary: Add support for group chat
Title: Offline inboxing iteration 1: Support public chat 

Status app has public chats and has group chats. Do we address both types of chats or only one of them. If one then is it public chat or group chat?

**Comment by dmitryn** [comment]
@annadanchenko we address both types of chats here. The reason behind mixing terms is that they work similar to each other from the dev standpoint.

**Comment by annadanchenko** [comment]
Tested OK (ios and Android real devices), for public and for group chats
 1. when users are not in contact of each other 2. whey they are contacts 3. when several messages are sent 4. location command is sent, when emoji is sent 5. in group chat (same things as above) + send, request commands

Extra notes:
1. New user joins public chat -> will receive old messages (from all time he was not in the chat)
2. Sometimes messages are received in the other order than were sent (older messages come after new messages)
