### ISSUE TITLE
Edit box of messages is not getting clear automatically in an app

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2703]
### User Story
1. As a **User** I want to send a message, but forgot something so I navigate to other options like discovery, contacts etc. & come back again to type the message, but Edit box is not cleared. It's displaying previous message on Edit box, even though didn't send.
2. As a **Tester** I want to test that, after typing message, suppose, User goes back or navigate to other options & come back again to type the message, then Edit box is cleared & not retaining previous message.
3. As a **Developer**, I need to see that, once Edit box is used(whether User is sending the message or not, Or only typing then too), & navigating to other options on User Interface ,when User comes back to same element- _Edit box, it should be automatically cleared Or typed message should automatically saved to draft._

### Description

*Type*: Bug.

*Summary*: ...
1.Sign to status.
2.open chats.
3.open any contact 
4.type a message , but don't send it.
5.Go back or navigate to other options on UI - Discover, contact
6.Again come back to  same contact & open.
7. Notice the Edit box option on User Interface. 

#### Expected behavior
Should clear automatically Edit boxes.

#### Actual behavior
Not getting cleared automatically.
Please see attached screenshot 
![testmsg](https://user-images.githubusercontent.com/20433356/33924697-3cd7bc86-dffd-11e7-8a7c-378c24e2558d.png)
https://drive.google.com/file/d/1kTpUc4qH97jjtEtBGJNJjsZeTCMhH3kT/view

### Solution
After typing the msg, _**If**_ User ( doesn't send typed message) 
then,
Edit box -> Clear ||  EditBox msg -> Save To Draft

### Additional Information

* Status version: ...

* Operating System: Android 6.0.1

**Comment by andytudhope** [comment]
I disagree with this user story. Personally, I prefer it that my messages stay in the edit box - as I can navigate away to check something and then come back and pick up where I left off. It is the default behaviour in almost any other messaging service I currently use, from Slack to WhatsApp and FB messenger.

**Comment by Monali109-zz** [comment]
@andytudhope  Depends on Requirements of App & User view. Thanks
