### ISSUE TITLE
Add personal message sign support

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#2704]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a Dapp's developer, I want to sign messages in Status.

### Description

Some [things have changed](https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527) with signing data in Ethereum.

The methods `personal_sign` and its partner, `personal_ecRecover `have replaced the previous signature methods, `eth_sign` and `eth_recover`. That’s because the previous methods signed raw data unmodified, making it vulnerable to chosen ciphertext attacks, as well as potentially signing transactions you didn’t intend to. You can read more about the reasoning behind this change on the [go-ethereum repository](https://github.com/ethereum/go-ethereum/pull/2940).

In order for many DApps to work, and to work securely in Status, we need to support these different signing methods. Further links are given below and in the comments.

https://github.com/MetaMask/metamask-extension/pull/1149

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

**Comment by jeluard** [comment]
Looks like it is implemented by latest [web3](https://github.com/ethereum/web3.js/blob/develop/lib/web3/methods/personal.js#L60)

**Comment by jeluard** [comment]
See also some [example usage](https://github.com/danfinlay/js-eth-personal-sign-examples)

**Comment by pablanopete** [comment]
Needed for CryptoKitties

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbcca941bf7a0fdc331a7bfe2488056aaf027144a8b9388d8cc0323a2ff172411](https://etherscan.io/tx/0xbcca941bf7a0fdc331a7bfe2488056aaf027144a8b9388d8cc0323a2ff172411)

**Comment by msuess** [comment]
Taking a crack at this :)

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 4500.00
Contract address: [0xb3bf7f041757997f33c15565c7d225b048ff4606](https://etherscan.io/address/0xb3bf7f041757997f33c15565c7d225b048ff4606)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by mandrigin** [comment]
@flexsurfer we have `web3.personal.sign` support which is exactly that `personal_sign`. Does that mean, that we need to provide a signal from the Go side for Status to show a password dialog, just like with transactions?

**Comment by flexsurfer** [comment]
@mandrigin yeah i think so, do you need a password for this function?

**Comment by jeluard** [comment]
@mandrigin Maybe we could think about making this mechanism more generic? Are there any other call that would require authentication?

**Comment by mandrigin** [comment]
@jeluard emm... signing a transaction? 😅

**Comment by mandrigin** [comment]
@flexsurfer it assumes that the account is locked, as I can see https://ethereum.stackexchange.com/a/25610

<blockquote><img src="https://cdn.sstatic.net/Sites/ethereum/img/apple-touch-icon@2.png?v=fcf6615497f4" width="48" align="right"><div><strong><a href="https://ethereum.stackexchange.com/questions/25601/what-is-the-difference-between-web3-eth-sign-web3-eth-accounts-sign-web3-eth-p/25610">What is the difference between web3.eth.sign, web3.eth.accounts.sign, web3.eth.personal.sign functions?</a></strong></div><div>Which function should be used to sign message locally? Which function is the most secure?</div></blockquote>

**Comment by jeluard** [comment]
:D I was thinking maybe https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcall and potentially others might fit this scenario.
Also maybe an opportunity to think how we could offer alternative authentication methods (fingerprint, face recognition, ..)

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/wiki">ethereum/wiki</a></strong></div><div>wiki - The Ethereum Wiki - </div></blockquote>

**Comment by mandrigin** [comment]
@jeluard as I understand, at the moment, when a TX is created, we (status-go) give you (status-react) a notification, then you show a dialogue and call our `completeTransaction` API with a password to unlock the account.
I can see how the same mechanics can be made more generic to support other types of methods that require a signature.

**Comment by mandrigin** [comment]
I got a branch with the implementation (https://github.com/status-im/status-go/tree/igorm/implement-personal-sign).
It has API changes.
1) Method renames:
- `CompleteTransaction` becomes `ApproveSignRequest`
- `DiscardTransaction` becomes `DiscardSignRequest`

2) Signal changes
`transaction.queued`→  `sign-request.queued`
`transaction.failed`→ `sign-request.failed`

3) Signal logic changes
When any of `personal_sign` or `eth_sendTransaction` is called, `sign-request.queued` will come. It's `args` will contain either Tx metadata (like before) or account and data to sign for `personal_sign`.
So both `personal_sign` and `eth_sendTransaction` should call `ApproveSignRequest` to proceed.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>
