### ISSUE TITLE
Not able to cancel the account while creating, nor able to delete account after creation

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2705]
### User Story
1. As a **User** I want to cancel the account while creating or after creation of account want to delete it.
 If already one account is created, then while creating another account want to cancel & switch to another account.
2. As a **Tester** I want to test that, after creation of account, I am able to delete it, or While creating the account able to Cancel account .
3. As a **Developer**, I need to see that, once account is created, account should be able to delete or cancel, with the consent of User. 

### Description

*Type*: **<Bug|Feature>**

*Summary*: ...
N/A
#### Expected behavior
Should be able to cancel account while creating & delete account after created.

#### Actual behavior
Currently, unable to cancel & delete too.
Untill & Unless create the account, status app is not allowing to come out from the app!
If already account created & while creating new account, if want to switch then after Power off of phone & switch on, then only able to sign in another account.

**- ## Solution**
_**Graphical User Interface - Include options - 1. Cancel 2. Delete**_

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-ee2904.apk

* Operating System: Android & iOS

**Comment by annadanchenko** [comment]
remove account: duplicate for https://github.com/status-im/status-react/issues/1126
cancel while creating: won't fix
