### ISSUE TITLE
Invariat Violation error shown when opening transaction history screen [2217]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2709]
### Description

*Type*: Bug

*Summary*: Error `Invariat Violation: Native anumated module is not available` shown when opening txn history screen

#### Expected behavior
Able to see History of transactions

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/33953298-8fe4a310-e045-11e7-9a85-9772f95abf64.png)

### Reproduction

- Open Status
- Go to Wallet
- Open Transaction History screen

### Additional Information
* Status version: `0.9.11d445-1996.6` https://webapp.diawi.com/install/UdNxYz
* Operating System: iOS

#### Logs
No TF unfortunatley as there were issues with iOS builds and Roman rebuilded it locally , seems whithout TF

**Comment by janherich** [comment]
Already fixed in the branch
