### ISSUE TITLE
Group Chat Name if edited is not reflected in the corresponding member accounts.

### ISSUE THREAD

**Issue by kodalim** [status-im/status-react#2711]
![img_0380](https://user-images.githubusercontent.com/34264946/33955649-42c778c4-e062-11e7-984e-aace96d2f661.JPG)

### User Story

As a tester trying to edit the Group Chat name.

#### Expected behavior
The group chat name modified should be reflected in the chat window of all the members.
#### Actual behavior
The edited Group chat name is not reflected in the members chat window. It shows the original name

### Reproduction
- Phone A - Open and sign in Status
- In the Chats window click on '+' to open the Start new chat.
- Click on New group chat and add the member belonging to Phone B
- Click on Next to add the group name and Save.
- A new group chat is created. 
- Send message in the group chat window
- Group chat created in the members chat window with the messages in Phone B
- Messages can be exchanged across the members
- Click on the top right hand side to view the Members and Settings
- Click on Settings and note the members.
- Edit the name of the chat in Phone A
- Send messages
- Messages are sent across but the Group Chat name is not updated in the member chat window of Phone B.

### Solution
The change should be reflected
- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.12+
Phone A - Samsung Galaxy Note5 7.0
Phone B - Motorola -Moto E4 7.1.1

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```
![img_0380](https://user-images.githubusercontent.com/34264946/33955440-91e73526-e061-11e7-9301-3709cbc91134.JPG)

**Comment by annadanchenko** [comment]
expected. Works as rename contact and is visible only to the one who renamed it.
