### ISSUE TITLE
Group chat settings does not indicate owner in settings.

### ISSUE THREAD

**Issue by kodalim** [status-im/status-react#2712]
### User Story

As a user, I would like to see the number of members in a group chat. 
### Description

Type - Feature
The Group Chat name indicates 4 members but the settings list only three members that were added by the owner of the Group chat.

#### Expected behavior
Would like to see all the members listed including the owner of the chat displayed as 'You'

#### Actual behavior
'You' is not displayed confusing the user with the member count shown on the top.

### Reproduction
- Create a Group chat for the user
- Add members 
-View Settings and note the number of members. The number of members displayed does not match the count displayed beneath the Group Chat name.
### Solution
'You' should be included in the list of members
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.12
* Operating System: Android 7.0 on Samsung Galaxy Note5 

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by lukaszfryc** [comment]
Duplicate
