### ISSUE TITLE
Black bars are shown when using iPhone X

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#2719]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a iPhone X user, I want to use Status so that it is optimized for my device.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There are black bars shown at the top and bottom of an iPhone X screen. As a user, this is jarring and detracts from the user experience. Instead, the app should take up the entire screen and be optimized for the safe areas and notch.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Expected behavior is for the app to fill the black bars, respect safe areas, have the status bar display correctly, and cater to the notch.

#### Actual behavior
[comment]: # (Describe what actually happened.)
See the black bars in the screenshot.

![img_0018 2](https://user-images.githubusercontent.com/116099/33998901-f44b281c-e0b6-11e7-9ad4-c130372626db.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Open Status on an iPhone X.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:  Apple has a full list of [required updates](https://developer.apple.com/ios/update-apps-for-iphone-x/).

Also possibly relevant, React Native introduced a [new API in 0.50.1](https://medium.com/react-native-training/react-native-iphonex-92ff511282af) for easily dealing with the safe area of an iPhone X. More [info here](https://blog.callstack.io/react-native-meets-iphonex-a0f5034f7a41).

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.12
* Operating System:iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by andytudhope** [comment]
@chadyj could we put this issue up for bounty given that the steps to solve seem fairly easy to follow? Suggest a small bounty.

**Comment by yenda** [comment]
@andytudhope the update to react-native 50.3 will be merged in develop soon, it's better to wait for it

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 750.00
Contract address: [0x8bd841ba3010c667bd80146597377fa8ec3bcfd0](https://etherscan.io/address/0x8bd841ba3010c667bd80146597377fa8ec3bcfd0)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
