### ISSUE TITLE
Revise multiline input 

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#272]
We are supporting multiline input fields but it currently looks ugly, can you please advise?

![2016-09-27 14 01 35](https://cloud.githubusercontent.com/assets/2714786/18870929/9ca55e6c-84e5-11e6-9ac1-e60466e6aa23.png)

**Comment by andmironov** [comment]
Added screen to Zeplin https://zpl.io/KnzFL
1. Note that the color and line-height of the input should be the same as the message text. The muted grey text is for placeholders
2. Input should contain max 3-4 lines (then it should start scrolling)
3. Input should have proper top and bottom paddings (32dp)
![_chat2_long_input](https://cloud.githubusercontent.com/assets/3115606/18871247/38b6a62c-84bd-11e6-8fb3-2336c12d43d9.png)

**Comment by jarradh** [comment]
thanks @andmironov looks much better
