### ISSUE TITLE
Counter of unread messages is reset after reopening app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2720]
### Description

*Type*: Bug

*Summary*: 
user want to see unread messages after reopening the Status app, but when you close app and then open it with unread messages - they are marked as read after log in.

#### Expected behavior
user can see amount of unread messages after reopening app

#### Actual behavior
no unread messages after reopening app

### Reproduction

- Open Status
- Start 1-1 chat
- Leave some messages unread
- Close app
- Open app
- Log in

### Additional Information

* Status version: 0.9.11d441 (IOS), 0.9.10-441-gbd017457+ (Android), nightly 14/12/17
Can be reproduced on release builds.

* Operating System: reproducible for Android 7.0 and IOS 11.0.3

Video: https://drive.google.com/open?id=1gf67KpkKgqmp-doH-P3xNs39SCYF-DMg

**Comment by annadanchenko** [comment]
can't reproduce on nightly and on release builds anymore
TF release build: 
https://app.testfairy.com/projects/4803622-status/builds/7525714/sessions/86/?accessToken=2mWQWelqKLBVaYN0dmi13ZsPA6A
https://app.testfairy.com/projects/4803622-status/builds/7525714/sessions/87/?accessToken=7avJsqHecS1XGTFi4VZxLD3T5U0
