### ISSUE TITLE
Unresponsive app after /send in 1-1  and group chat (android)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2721]
***Type***: Bug

***Summary***: Application becomes unresponsive in 1-1 chat screen after /send with the valid amount of ETH (doesn't matter if /send ETH value exceed the wallet amount). On the video example it happens on the second attempt, thought it's not stick to 3nd try of /send request. On real device reproduced from the first try for new user several times.

**Expected behavior:**
"Insufficient funds for gas + price value (balance 0 ETH)" error message, app is responsive on further commands 
**Actual behavior:**
Application is unresponsive. Nothing happens if to tap on any of 'X' (close) or back (including device's 'Back') buttons.

**NOTE** applicable for group chats as well

**Reproduction**
Video: https://drive.google.com/open?id=16qt7oBye0JT7ev9q3WIab3S0xKNNqVw-

1) Open Status
2) Enter valid password to create a new user
3) Navigate to 'Chats' window
4) Tap '+' button to navigate on 'Start new chat' window
5) Find 'Jarrad' and start new chat with this contact
6) Tap on /send command
7) Type valid value number and tap on send message
8) If 'insufficient funds for gas...' error appeared - edit the amount in message box next to the /send and try to send it again
8) Try to perform any action with app (except edit message in messagebox) 

**Additional Information**
* Status version: 0.9.10-443-g460f6a38+ (https://jenkins.status.im/job/status-react/job/pull%20requests/job/develop/15/)
* Operating System: Android 6.0.0(emulator Samsung Galaxy S6), Android 7.0 (real device Samsung J7 2017)

**Comment by annadanchenko** [comment]
can reproduce on develop build  0.9.10-443-g460f6a38+ (2000), https://jenkins.status.im/job/status-react/job/parametrized%20build/129/

Created account, requested ETH, opened chat with Jarrad, typed 0.0001 (was very slow in updating the number) and tapped on send icon (maybe even before the number 1 was shown)

See log/video from 01:08 https://app.testfairy.com/projects/4803622-status/builds/7291119/sessions/15/?accessToken=6qH2YO1A/rFS31LA4qO1kM3mZrU

**Comment by churik** [comment]
can reproduce on nightly 18/12 develop build. 
0.9.10-458-ga7f8526c+

See log/video from 05:38: https://app.testfairy.com/projects/4803622-status/builds/7310246/sessions/1/?accessToken=8RF6ZU0pkIv4rYAmRnTei7G4pN0

**Comment by oskarth** [comment]
@churik @Serhy or @annadanchenko can you confirm https://github.com/status-im/status-react/pull/2835 solves it for time being? If so we can edit issue to say "Under JSC flag" (and possibly adjust priority).

**Comment by Chu127001** [comment]
@oskarth  It is not reproducible in current dev, so #2835 solves it for now.

**Comment by oskarth** [comment]
Adding release tag:

- so it shows up in bug fixing day filter https://github.com/status-im/status-react/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Abug+label%3Arelease

-we need to solve it, and preferably soon

- it might simplify/get rid of other bugs

**Comment by oskarth** [comment]
Adding release tag so it shows up in bug fixing day filter https://github.com/status-im/status-react/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Abug+label%3Arelease

We need to solve it, and preferably soon. It might also simplify/get rid of other classes bugs.
  
That said it if this issue isn't solved it won't be in 0.9.13 release.

cc @rasom
