### ISSUE TITLE
A new account is created when trying to recover an account with invalid passphrase and password.

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#2725]
### Description
A new account is created when trying to recover an account with invalid passphrase and password. when you log in the account it does not seems that account existed before.

*Type*: Bug

*Summary*: 

#### Expected behavior
An error message stating the the account does not exist should be displayed

#### Actual behavior
A new account is created when trying to recover an account with invalid passphrase and password.

### Reproduction

- Open Status
- Select "Recover access", the "Recover access" page is displayed.
- Tap the space bar 15 times on the "Passphrase" field.
- Tap the space bar 15 times on the "Password" field, the "Recover Access" button is activated.
- Tap the Recover Access" button,  the "Recover access"  disappears, the "Sign in status" page is displayed again and an account is added to the page.
- Log in the account using the prevuois password, it seems like a new account has been created instead of recovering an existing one.

### Additional Information

* Status version: Nightly build: 0.9.10-432-g2bd7652b+
Samsung Galaxy S6 & iPhone SE
* Operating System: <Android> Android version: 6.0.1 &  IOS version: 11.1.2

**Comment by annadanchenko** [comment]
it's expected. To recover account you need the exact passphrase and password as were used in your account. If you are using others then you get an account for that passphrase/password.
