### ISSUE TITLE
Error "message.chat-id must be type of ‘string’ got null (null)" if member of group chat leaves the chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2727]
***Type***: Bug

***Summary***: When participant of group chat leaves the chat - all members receives an error " message.chat-id must be type of ‘string’ got null (null)" message. Doesn't matter if it's chat owner or joined members leaves the chat. 
It's also doesn't matter if the chat member who receives the error message - been on chat screen or any other screen (e.g. the list of chats or wallet page)

**Expected behavior**
No error messages on chat member side who keep stay in the group chat.
**Actual behavior**
Error " message.chat-id must be type of ‘string’ got null (null)" message appears on side of chat members who kept in the created chat.

**Reproduction**
1) Open Status on device A
2) Open Status on device B
3) Create new user on device A and submit valid password (this will be UserA from this moment)
4) Create new user on device B and submit valid password (this will be UserB from this moment)
5) On UserB side navigate to 'Chats' -> Account details -> Show QR code
6) Navigate to 'Add new contact' on UserA side.
7) UserA scan QR code of UserB and adds in contact list
8) Navigate on UserA side to 'Start new chat' screen and create 'New group chat'.
9) Add UserB and enter valid name (I user 'newgroupchat' value) of new group chat.
10) On UserB side - navigate to 'Chats' screen. Find new group chat ('newgroupchat' in my case) created by UserA.
11) Tap on chat logo at top-right to get to 'Chat settings'.
12) Tap on 'Leave chat' option.
13) Check UserA screen.

**Additional Information**
From 10th-13th step above you can interchange users (so instead UserA use UserB and vice versa)  - so it doesn't matter who leaves the chat: chat owner or added participant -> in any case participant who kept in group chat - will receive the error message.

**Status version:** 0.9.10-443-g460fa38+ nightly develop build (https://jenkins.status.im/job/status-react/job/nightly/108/) (links to .apk - http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-460f6a.apk)

**Operating System:** 
Android 7.0 Samsung J7 2017 (real device)
Android 6.0 Samsung Galaxy S6 (Genymotion emulator)

Screenshot of error: 
![screenshot-2017-12-15_12 16 49 150](https://user-images.githubusercontent.com/8749671/34037588-031f9c34-e192-11e7-8c30-10450558ca79.png)

**Comment by annadanchenko** [comment]
works ok on nightly build (from january 21)
