### ISSUE TITLE
Allow switching between wnodes for offline messaging

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#2751]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to select wnode i want to use for offline messaging.

### Description

Settings screen should have "offline message settings" where user could select wnode to use for offline messaging. This feature should be toggled by configuration flag.

### Notes

Check idea https://github.com/status-im/ideas/pull/23 for more information and screenshots

<img width="375" alt="screenshot 2017-12-25 15 42 42" src="https://user-images.githubusercontent.com/23836/34339810-54c104ba-e98a-11e7-8f8c-e7137c66e78a.png">

**Comment by oskarth** [comment]
Moving to blocked as https://github.com/status-im/status-react/issues/2764 has been extract from this, and we probably want to factor this out into bounties once above PR and refactoring is done.

**Comment by oskarth** [comment]
Not part of iteration 1, will bounty up at some point.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0xa17cce7e404871395406f25793e107b5707a95c9](https://etherscan.io/address/0xa17cce7e404871395406f25793e107b5707a95c9)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
