### ISSUE TITLE
Decide on supported devices for product MVP

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2752]
### User Story

As a developer, I want to know which devices we want to support (i.e. have acceptable perf on) in order to do relevant profiling, testing and fixing.

### Description

*Type*: Feature/Decision

*Summary*: Make a list of supported devices on Android and iOS respectively. Alternatively set a minimum/reference device version for each platform that we can use for benchmarking.

#### Expected behavior
A clear list or pair of devices we want to support for each platform.

#### Actual behavior
No such thing.

### Notes

Some considerations:

- QA and devs should have access to these
- It's OK to be a bit bleeding edge because users will catch up
- But perhaps not "iPhone X only" bleeding edge
- Android market share is very fractured, there's a long tail and seems difficult to get 80/20 (80% market share out of few devices), see e.g. https://docs.google.com/spreadsheets/d/1HAK3KstFqbVThQxWzLGoJXcq-U3x2NojZyt6_RIg4Ak/edit#gid=1051777509

Premium for quick decision on this front; easy to iterate. Example: iPhone7+ and Samsung Galaxy S7+ (not based on anything, just two reasonably new models)

**Comment by chadyj** [comment]
I looked at current device market share to get a sense for device usage and popularity.

On iOS the current top phones are:

iPhone 6s
iPhone 7
iPhone 7 Plus
iPhone 6
iPhone X
iPhone 8 Plus
iPhone 8


On Android, the current top phones are:

Samsung Galaxy J7
Samsung Galaxy Grand Prime
Samsung Galaxy J2
Samsung Galaxy J5
Samsung Galaxy J7(2016)
Samsung Galaxy S7 Edge
Samsung Grand Prime Plus

Top android manufacturers are:

Samsung | 47.9 %
Huawei | 6.6 %
LG | 4.6 %
Xiaomi | 4.4 %
Motorola | 4.2 %



Source: 
https://www.appbrain.com/stats/top-android-phones
https://mixpanel.com/trends/#

**Comment by oskarth** [comment]
After talking with @chadyj and @annadanchenko, to keep it simple we can use the following two reference devices:

- iOS: iPhone 6s
- Android: Samsung Galaxy S6

This doesn't mean "if it works on these everything is fine perf wise", it means "if it doesn't work on these we have a big problem" (and same goes for S6+/6s+ of course).

Marking this issue as done for now as getting more high-granular view isn't necessary from 55/Fast Status POV AFAIK. QA already have their own process for doing these checks which involve real user data and a multitude of devices.
