### ISSUE TITLE
Allow easy status-go log level modification

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2756]
### User Story

As a developer, I want to easily modify `status-go` log level via feature flags

### Description

*Type*: Feature

`status-go` log level is hardcoded. It should be possible to set it via [feature flag](https://github.com/status-im/status-react/blob/develop/.env)

Log levels are set here:

* android https://github.com/status-im/status-react/blob/develop/modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java#L182
*ios https://github.com/status-im/status-react/blob/develop/modules/react-native-status/ios/RCTStatus/RCTStatus.m#L205

**Comment by oskarth** [comment]
Additionally it is set here in a slightly different format (mostly for TFLogs): https://github.com/status-im/status-react/blob/ed3597fd7ce52fbcf96351338edc49180818e49e/ios/StatusIm/AppDelegate.m#L71

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0xff1506214cd6ffbad8cecef35f93e8bc67680cbd](https://etherscan.io/address/0xff1506214cd6ffbad8cecef35f93e8bc67680cbd)
Network: Mainnet
Paid to: PombeirP
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pedropombeiro** [comment]
I'm giving this a go.

**Comment by pedropombeiro** [comment]
@jeluard Noticed that in `.env` we have a setting that seems redundant, given that we already have a `LOG_LEVEL` entry:
```
DEBUG_LOGS_ENABLED=0
LOG_LEVEL=info
```
Given that we now will actually be using `LOG_LEVEL` everywhere, there's no reason why we shouldn't replace `DEBUG_LOGS_ENABLED` with `LOG_LEVEL`, right?

**Comment by oskarth** [comment]
@PombeirP Correct, provided this code is adjusted to respect LOG_LEVEL:

```
  if([debugLogsEnabled isEqualToString:@"1"]){
    RCTSetLogThreshold(RCTLogLevelInfo - 1);
    RCTSetLogFunction(RCTTestFairyLogFunction);
  }
```

see `AppDelegate.m`.

**Comment by pedropombeiro** [comment]
Exactly, thanks!
