### ISSUE TITLE
Errors 'no protocol method' and  'null is not an object' shown when signing in

### ISSUE THREAD

**Issue by treebeard** [status-im/status-react#2760]
### Description

*Type*: Bug

*Summary*: During the first attempt to sign in, error 'no protocol method lAssociative' shows up, and all subsequent sign in attempts show error 'null is not an object (evaluating 'cljs.core.deref(status_im.data_store.realm.core.account_realm).path') until app is restarted.

#### Expected behavior
No errors when logging in.

#### Actual behavior
![screenshot_20171219-023600](https://user-images.githubusercontent.com/11672497/34145831-a97ec980-e465-11e7-9797-a74bfab8e4f7.png)

![screenshot_20171219-021714](https://user-images.githubusercontent.com/11672497/34145379-c8058d1e-e463-11e7-8793-d14feef962a1.png)

### Reproduction

- Open Status
- Enter login credentials
- Click 'Sign In'
- First error is displayed, click 'ok'
- Click 'Sign In'
- Second error is displayed

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.12+
* Operating System: Android

**Comment by mplsvbhvr** [comment]
I have the same error - was a fix ever found?
