### ISSUE TITLE
App not installed message when upgrading

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2762]
### Description

*Type*: Bug

*Summary*: Can't upgrade - `app not installed` message shown when installing any build on exisiting 0.9.12b release (android)

#### Expected behavior
Upgarde is successful

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/34155932-304a6e72-e4cc-11e7-81f2-339c9f87b884.png)

### Reproduction

- Install release 0.9.12b
- Create account
- Upgarde to develop

### Additional Information

* Status version: any, take latest develop
* Operating System: Android
* Real device Huawei P10 lite, Android 7.0

**Comment by rasom** [comment]
> Install release 0.9.12b

Do you mean Play Market version? I tried to upgrade it using lates nightly http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-279ebc.apk and it was upgraded successfully.

**Comment by Serhy** [comment]
Tested on Android 7.0 (Samsung real device), Android 4.4.4 (Nexus 5 emulator), Android 6.0.0 (Samsung S6 emulator), Android 5.1.0 (Samsung S6 emulator), Android 6.0.0 (Nexus 5.0.0)
In all case I could successfully upgraded from 0.9.12b in PlayMarket to latest develop (0.9.10-481-g279ebc31+)
