### ISSUE TITLE
java.lang.NullPointerException error when rendering the map [0.9.12b]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2763]
### Description

*Type*: Bug

*Summary*: Error shown when closing map inline. This happens when location command is called for the first time and I assume its  because of slow map rendering however the device is not that old. 

#### Expected behavior
Error `java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapView.onResume()' on a null object reference`

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/34156145-047b56c0-e4cd-11e7-8a44-afbd2494861e.png)

### Reproduction

- Open Status
- Add a contact
- in 1x1 chat call `/location` command and close the inline when map is being loading

### Additional Information
* Status version: 0.9.12b
* Operating System: Android
* Real device Huawei P10 Lite , Android 7.0

**Comment by annadanchenko** [comment]
Location command is removed
