### ISSUE TITLE
Unable to connect to CLJS REPL

### ISSUE THREAD

**Issue by foopang** [status-im/status-react#2771]
### User Story

As a developer, I want to be able to connect to CLJS REPL so that I can do interactive stuff via CLJS REPL.

### Description

*Type*: Bug

Seems that it happens after [this commit](https://github.com/status-im/status-react/commit/56c59c741fc6f915135e2d6dec44a21ab296ea99), the CLJS REPL is not accessible anymore.

*Summary*: ...

#### Expected behavior
Figwheel connects to the application and CLJS REPL prompt shows.

#### Actual behavior
`(start-cljs-repl)` ran infinitely waiting for connection and CLJS REPL prompt won't show.

### Reproduction

- Build the application for development and then open it in a real device or an emulator.
- Type `lein repl` in the console to start nREPL. Then type `(start-cljs-repl)` in the nREPL prompt.

**Comment by dmitryn** [comment]
@foopang it works for me. Try `(cljs-repl "ios")` where argument is device you're using.

**Comment by ghost** [comment]
@foopang you mai want to set some params before launching REPL, like: "BUILD_IDS="ios" lein repl"

**Comment by foopang** [comment]
@dmitryn @poiga Thanks! I tried both methods you mentioned, still no luck. Maybe just me couldn't get the CLJS REPL up and running? Strange...will seek further solutions myself.

----
Leiningen 2.7.1 on Java 1.8.0_144 OpenJDK 64-Bit Server VM
node v8.9.3
npm 5.5.1
