### ISSUE TITLE
App is not responsive when user type a wrong URL under / faucet on the Console page/chat.

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#2772]
### Description
The app does not respond when the user enter a wrong URL after selecting "/faucet" during the chat with the Console.
*Type*: Bug

*Summary*: 

#### Expected behavior
The "incorrect faucet please select one from the list." error message disappear when the user send a valid URL and the user recseives ETH.

#### Actual behavior
The "incorrect faucet please select one from the list." error message does not disappear and the app does not respond.

### Reproduction
- Open Status
- Select the "Chats" tab the select"Console" to open the console conversation. (or log in as a new user)
- Tap "/faucet" at the top of the message field and enter: **http://51.15.45.169:3000** the "incorrect faucet please select one from the list." message is displayed.
- Change it to **http://51.15.45.169:3001** and click the send button several times, the app does not respond anymore when you try to:  send the new URL ,delete what was typed, click the back button. 

### Additional Information
* Status version: 0.9.10-462-geb8d0a8a+
# Android 
* Operating System: Android 6.0.1 (Samsung Galaxy S6 (real device)).

**Comment by annadanchenko** [comment]
can't reproduce on nightly build from March 19
