### ISSUE TITLE
/location command is displayed as json in Chats until message is unread for not added contact

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2773]
### Description

*Type*: Bug

*Summary*: 
if you have unread messages with locations, last of them is displayed as json (red) until you
1) open 1-1 chat with user
2) add user as contact

![loc](https://user-images.githubusercontent.com/4557972/34209669-c9a8b842-e59b-11e7-9227-1426775bf69e.png)

#### Expected behavior
location is displayed like user readable content
marked green on screen

#### Actual behavior
json instead of readable location
### Reproduction

- Open Status
- Start 1-1 chat (user A)
- Send location (user B)
- Open "chats" tab

### Additional Information

* Status version: 
0.9.11d463
* Operating System: Android, iOS

From 02:40: https://app.testfairy.com/projects/4803590-status/builds/7336016/sessions/15/?accessToken=FkAfrJD6QjjhIkc1yeuWtPAtCno

**Comment by janherich** [comment]
@churik Can you confirm that while it's initially displayed as json, after some time (couple of second at most), its changed to the readable text of location ?

**Comment by churik** [comment]
@janherich nope, for me it is till message is unread for new chat (contact is not added).
Also I added TF session
After I open 1-1 chat > go back to "Chat" tab - everything is displayed as plain text (as expected)

**Comment by churik** [comment]
Is not reproducible with 0.9.11d481
