### ISSUE TITLE
Discover: Popular hashtags counter is misplaced

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2775]
### Description

*Type*: Bug

*Summary*: counter on Discover screen is misplaced

#### Expected behavior
Should be right aligned on the card

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/34213978-06ae0a38-e5b2-11e7-828f-1d08af6dac3b.png)

### Reproduction

- Open Status
- Set up a status with hashtag
- navigate to discover tab

### Additional Information
* Status version: `0.9.10-464-g9ca54e9a+` develop
* Operating System: Android. iOS

**Comment by foopang** [comment]
@asemiankevich should it be placed to the right most?

![screenshot from 2017-12-22 20-50-17](https://user-images.githubusercontent.com/4666757/34298686-fb4b1b8c-e759-11e7-90d5-a5b37ae9f47d.png)

**Comment by asemiankevich** [comment]
@foopang that's true

**Comment by foopang** [comment]
@asemiankevich submitted a fix https://github.com/status-im/status-react/pull/2797
