### ISSUE TITLE
Refactor colors

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#278]
There is a styles namespace (`status-im.components.styles`) and there are colors in this namespace. However, it is still possible to see styles which look that way:

`(def scan-text
  {:flex          1
   :flexDirection :column
   :color         "#7099e6"
   :margin-left   8})`

It is, of course, not important, but we should spend some time replacing colors with pre-defined colors from `status-im.components.styles`

**Comment by mintheredonethat** [comment]
Hey, I submitted a PR for this issue, hopefully I followed the guidelines correctly?
