### ISSUE TITLE
Prevent re-frame misleading messages when reloading

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2780]
### User Story

As a developer, I don't want to have spurious warning messages.

### Description

*Type*: Feature

`re-frame` generates some warnings when a `handler` is re-defined. While great in theory it generates lots of unwanted messages when reloading the code via `figwheel`.
Implement one of the described [workaround](https://github.com/Day8/re-frame/issues/204) so that it does not happen.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0xbf4a82af0722b4c3e2cad58e2a8de53f9e234044](https://etherscan.io/address/0xbf4a82af0722b4c3e2cad58e2a8de53f9e234044)
Network: Mainnet
Paid to: pablodip
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
