### ISSUE TITLE
User avatar is misplaced in 1-1 chat when chat history is more than one day

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2782]
### Description
*Type*: Bug
*Summary*: 
if history in 1-1 chat contains more than 1 day - user avatar is placed under current day messages
![ios1](https://user-images.githubusercontent.com/4557972/34253877-1c3c9a22-e652-11e7-80b6-0d9529e3c5e4.png)

#### Expected behavior
user avatar in 1-1 chat in the beginning of chat history

#### Actual behavior
user avatar in 1-1 chat in the beginning of current day chat 

### Reproduction

- Open Status
- Start 1-1 chat
- Send some messages
- Continue chat tomorrow

### Additional Information

* Status version: 0.9.11d463
* Operating System: Android, iOS

#### Logs
TF session: https://app.testfairy.com/projects/4803590-status/builds/7336016/sessions/19/?accessToken=A0r1lkWYYEipgAJnwwWCo90AB2U

**Comment by janherich** [comment]
Hi @churik are we sure we want that behaviour (user avatar always at the very beginning of the chat history) ?
As the current user status is displayed in the user avatar and the current user status is something which can be changed and user would want to communicate that to other, it would be very hard for him to actually do that in chat with let's say 1000 old messages - nobody would see the user avatar and his/her actual status unless scrolling to the very top of the conversation, quite impractical.

In my opinion the whole idea of displaying User avatar + status as a normal message in stream with all others is wrong - we would ideally want that information to be always available to the user when he is typing/scrolling/looking at the chat, so it should be pinned to one place, but let's have @andmironov have a final word about that :)

**Comment by churik** [comment]
@janherich as for me idea of displaying User avatar + status as a normal message is redundant, because all this data is already displayed in header.
But if we have this feature, it is wrong to place message with ava to the middle of conversation just because next day came)

**Comment by janherich** [comment]
@churik We have *almost* all data displayed in header as well, but one crucial piece (current user status - `the future belongs to those who...`) is missing there. 
I agree that user-message in the middle of the conversation feels super strange from visual point of view, even if it makes easier for recipient to discover the current status of the sender.

**Comment by andmironov** [comment]
There is a slight UI update coming with no avatar + name in the empty chat, but just `There are no messages in this chat yet` text instead

![ios_chat-12](https://user-images.githubusercontent.com/3115606/34257103-80f37d52-e669-11e7-881c-d28b70e71cc6.png)

**Comment by janherich** [comment]
@andmironov the question is more about the situation when we have many messages in chat (message history spans several days). We can then do some choices:
1. (Current behavior) Always pin user message (with his/her photo & current status) to the last message group (current day messages) - this makes sense from the usability view, as whenever recipient wants to look-up current status (expression of mood) of the sender, he just needs to scroll over today's messages and he/she can see it. On the other hand, it's quite disrupting from the visual point of view and feels weird.  
2. Always pin the user message to the oldest message group in the chat, so it's effectively always the first message in the chat - it doesn't look that weird, but in any longer conversation (say conversation spanning multiple weeks/months), the ability to look-up status of the sender is virtually lost for the recipient - he/she would have to scroll to the very first message in the chat to see it, not fun.
3. Get rid of the user message with photo and chat altogether and find some other place where to show sender status so it's always pinned on the screen no matter how the recipient scroll through the messages - user name & photo are already displayed in the status bar, so we just need to find some place for the user status :)

**Comment by oskarth** [comment]
@annadanchenko Given the above discussion, coming change in UI and the fact that this isn't really a bug per se (more unexpected, for some user), I don't think it makes sense to see this as a priority issue. I think we should remove this from release scope.

**Comment by annadanchenko** [comment]
@oskarth I disagree as user avatar+status shown in the mid of the chat is confusing and does not look nice. It will affect all users who open chat for more than 1 day, so will be very visible. 

I propose to remove all username, avatar and status from chat (as name and avatar are shown on the top of the chat) and status will be removed with discover.

@andmironov agree?

**Comment by janherich** [comment]
Implemented according to @annadanchenko 's suggestion - https://github.com/status-im/status-react/pull/2944
