### ISSUE TITLE
Error at attempt to send location with scandinavian letters after invalid input with Demo Bot

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2789]
### Description
*Type*: Bug
*Summary*: after you send some invalid input in Demochat (like "aaa") and got message "seems that you don't want to send a money:( cnt=2" -  at attempt to use /location with Scndinavian/German ect specific letters - got an error on Android 
![andr1](https://user-images.githubusercontent.com/4557972/34257032-c94f4cec-e660-11e7-9fc9-b7ed931bcbc9.png)

#### Expected behavior
can use location with any letters

#### Actual behavior
error on command Handling

### Reproduction

- Open Status
- Go to Contacts
- Tap on Demo Bot 
- send "aaa". Should get "seems that you don't want to send a money:( cnt=2"
- go to 1-1 chat
- use location with German-specific letters (like Neumünster, Germany)

### Additional Information

* Status version: 
21.12.2017 dev build
0.9.10-469-g1837623c+
* Operating System: Android

#### Logs

TF: https://app.testfairy.com/projects/4803622-status/builds/7344802/sessions/6/?accessToken=/FQi46D8rEboB30DIMeJzKwekmM

**Comment by annadanchenko** [comment]
Location command is removed
