### ISSUE TITLE
Time lag in messaging (iOS - Android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2792]
### Description

*Type*: Bug

*Summary*: Sometimes there is a weird messaging behaviour like messages are sent but not received on the other side. That is mostly happening when I use iOS - Android pair. I was able to re-create this once using release build and @chadyj has seen it in develop . My assumption is something weird is in messaging itself (no matter of the build) but we need to investigate it further. I dont have clear steps to reproduce but i have some TF sessions that will be attached. 

So the issue is: sometimes messages are sent but not delivered and this could be fixed partially by app relaunch.

#### Expected behavior
I should be able to text to my contact and receive messages in real time.

#### Actual behavior
Time lags between messages are delivered. 

### Additional Information
* Status version: last seen in  0.9.10-469-g1837623c+ (2026), / 0.9.11d469 (2026)
* Operating System: Android|iOS

#### Logs
https://app.testfairy.com/projects/4803590-status/builds/7345353/sessions/7/?accessToken=/ikC62mEkdgZ4E8CmP6fnjNtEIU

https://app.testfairy.com/projects/4803622-status/builds/7345058/sessions/9/?accessToken=Y7FbEJiMMqcbVqLEgEdnaqULE6o

Adding one more log from test session today: https://app.testfairy.com/projects/4803622-status/builds/7371377/sessions/23/?accessToken=RqTGsnFcWhF1i9iVs84GuauPIUg

**Comment by divan** [comment]
I was able to reproduce it with iPad<->Android pair as well.

**Comment by churik** [comment]
@divan , could reproduce it again
IOS TF (chat starts from 06:53)
 https://app.testfairy.com/projects/4803590-status/builds/7354057/sessions/3/?accessToken=0vbxKvcyadgnRiwTCIUsk-cvdRY - all messages is visible, works fine.

Android TF (started chat 35:50)- https://app.testfairy.com/projects/4803622-status/builds/7354051/sessions/1/?accessToken=coJTk8jLKLEFaaQO8kvWgFsaSXc

Steps for me:
- scan QR on Android (User A acc)
- send location to new chat on IOS (User B)
- reply on Android (User A)
Actual:
see all messages on IOS and only messages of User A on Android
Expected:
see all messages on both Android and IOS

**Comment by flexsurfer** [comment]
Messages don't work at all on Android https://app.testfairy.com/projects/4803622-status/builds/7416814/sessions/59/?accessToken=b8Vc8pYbYJZ4v8UQaMyqTC8H0hA

**Comment by oskarth** [comment]
@churik @flexsurfer thinks it could be offline inboxing, I doubt it (@annadanchenko tested it on Android), but could you make a build with this flag off to make sure?
