### ISSUE TITLE
Rely on latest re-natal config.cljs

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2793]
### User Story

As a developer, I don't want to have files part of `git` automatically modified by tools (e.g. `re-natal`)

### Description

Currently [android](https://github.com/status-im/status-react/blob/develop/env/dev/env/android/main.cljs) and [ios](https://github.com/status-im/status-react/blob/develop/env/dev/env/ios/main.cljs) main files are modified each time `re-natal` is run.
Rely on latest re-natal [changes](https://github.com/drapanjanas/re-natal/commit/5f6da94ae72f5a3fc162f79acc73843ff43925b0) that introduced [config.cljs](https://github.com/status-im/status-react/blob/develop/env/dev/env/config.cljs) to make sure those files won't be modified.
Make sure `re-frisk` configuration is also updated.

`config.cljs` will then be modified by `re-natal` but listed in `.gitignore`.

*Type*: Feature

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0xb50ed998e4e59d593269d303dedeb842200b8d5e](https://etherscan.io/address/0xb50ed998e4e59d593269d303dedeb842200b8d5e)
Network: Mainnet
Paid to: t4sk
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
