### ISSUE TITLE
Crash when choosing recipient (iPhone X)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2798]
### Description

*Type*: Bug

*Summary*: There was a crash encountered by @oskarth on iPhone X. There are no stable steps to reproduce it and I can't dig into because I don't have this device.

#### Expected behavior
No crashes

#### Actual behavior
App crashed

### Reproduction
- Open Status
- go to Wallet -> Send -> Choose recipient 
- app crashes

### Additional Information
* Status version: `0.9.11d471-2028`
* Operating System: iOS

#### Logs
TF : https://app.testfairy.com/projects/4803590-status/builds/7353468/sessions/16/?accessToken=w-99S6dguJr2DNeQew-BgTQHFcQ

**Comment by oskarth** [comment]
I tried reproducing it once right after it crashed and was unable to.

**Comment by asemiankevich** [comment]
havent seen this issue since the ticket was logged. Closing
