### ISSUE TITLE
User stays on 'Add new contact' page when public key submitted after recover account 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2805]
***Type***: Bug
***Summary***: When user adds new contact which exists in chat list in unconfirmed state - the user stays on 'Add new contact' view 

**Note**: passphrase and password of the user which received transaction from another user is provided in the steps below .

#### Expected behavior
User redirected to 1-1 chat view after submitting public key 
#### Actual behavior
User stays on 'Add new contact' view after submitting public key 

### Reproduction
Video: https://app.testfairy.com/projects/4803622-status/builds/7354880/sessions/19/?accessToken=HvYLlOhhrHUqUxlbk2H2IUSPxns

1) Open Status
2) Select 'Recover'
3) Enter passphrase and password: `general speed suit organ spawn confirm into reason special dinner yellow tennis` / `Aaaaaa`
5) On 'Sing in' screen select recovered user ( 'Outstanding Opulent Fireant')
6) Type password 'Aaaaaa'
7) On 'Chat' view click on '+' button
8) Tap on '+ Add new contact'
9) Paste the key: `0x04396451d8c193016979914e0e9cec9c217d9b5d5e1d4542528f0fa949fa43855999f3154903eae55dc8c99dc81d9b28b319aefbfd9f104a32cbcd428799144cfd` and submit it with top-right button.

### Additional Information
Status version: 0.9.10-472-gbcc2b120+
Operating System: Android 7.0 (Samsung J7 real device), Android 6.0 (Samsung Galaxy S6 emulator), iPhone7

**Comment by churik** [comment]
Reproducible only after recovering account

**Comment by goranjovic** [comment]
Can't reproduce on latest develop.
After I add the public key I just get the chat with that contact, as normal.

**Comment by churik** [comment]
Isn't reproducible with current release 0.9.13 (2080.21)
