### ISSUE TITLE
No redirection to "Add new contact" after scanning QR with public key(after first app launch)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2808]
### Description

*Type*: Bug
*Summary*: 
when you scan QR of new user in order to add him to your contacts (when you add new user for 1 time), app does not redirect you to screen "Add new contact" for confirmation. It redirect to "Chats" tab.

#### Expected behavior
"Add new contact" screen with scanned QR

#### Actual behavior
tab "Chats" opens

### Reproduction

- Open Status
- Set up password 
- Go back to Chats
- Tap on "add new contact"
- Scan QR (scan QR of Status app installed on Iphone)

### Additional Information
* Status version: 
25/12/2017 nightly
0.9.10-474-gcc8168e9f+

* Operating System: Android

#### Logs

TF (from 09:10)  -https://app.testfairy.com/projects/4803622-status/builds/7358884/sessions/1/?accessToken=8uxbq-gVFjHNjTbvwaNjD24n-ts
If you add new user account (user B) to your Status, issue is not reproduced anymore for initial user and user B as well.

Also I noticed that scanning QR works slow (first QR scanning takes more 30 sec, all next 10+ sec
TF (00:30 - 01:15) https://app.testfairy.com/projects/4803622-status/builds/7416814/sessions/69/?accessToken=aWN0l33f2NqWcb-PcChtbUUR9Go

**Comment by churik** [comment]
Can be related to #2805

**Comment by asemiankevich** [comment]
@churik Can't reproduce it with last nightly : https://app.testfairy.com/projects/4803622-status/builds/7371377/sessions/35/?accessToken=v52lmRmTtVfcdTlOyNpu7eq7cDk 

Can you please double check ?

**Comment by churik** [comment]
I cannot reproduce it anymore as well on today nightly.

**Comment by churik** [comment]
TF (00:50 - 01:20) https://app.testfairy.com/projects/4803622-status/builds/7416814/sessions/60/?accessToken=iitQI2auyVyOD2RcugI0chfRiH8

build 0.9.10-5022-g2f4c750d+ (nightly 02.01.18)

**Comment by churik** [comment]
Floating issue, cannot reproduce on current dev build (05.01.18) again
