### ISSUE TITLE
Offline inbox:  Support requestMessages in web3.js

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2809]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a Clojure developer, I want to use web3.js API so that our API calls are consistent.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature/Refactor

*Summary*: Mirror shh_requestMessages so we can call it via HTTP-RPC.

#### Expected behavior
Request messages like right now but using updated web3.js.

#### Actual behavior
Using JSON-RPC.

### Solution

- [ ] PR to web3.js https://github.com/status-im/web3.js/issues/4
- [ ] Update web3.js dependency in status-react
- [ ] Replace https://github.com/status-im/status-react/blob/develop/src/status_im/protocol/web3/inbox.cljs#L46 with web3 call

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 220.00
Contract address: [0x3d13381dad2c892d45ccc6416311c66511edb5bd](https://etherscan.io/address/0x3d13381dad2c892d45ccc6416311c66511edb5bd)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by foopang** [comment]
Hi, I am working on this issue along #2810, just not sure how to test and verify everything works as expected.

**Comment by dmitryn** [comment]
@foopang check the logs with "offline inbox" prefix and make sure you don't see any errors. From UI POV you could send message to public chat, wait for 3min, sign in with another account and verify you have unread messages in that public chat.
