### ISSUE TITLE
Offline inbox: Support markTrustedPeer in web3.js

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2810]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a Clojure developer, I want to use web3.js API so that our API calls are consistent.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature/Refactor

*Summary*: Mirror shh_markTrustedPeer so we can call it via HTTP-RPC.

Essentially same as https://github.com/status-im/status-react/issues/2809 but different method.

#### Expected behavior
Mark trusted wnode peer like right now but using updated web3.js.

#### Actual behavior
Using JSON-RPC.

### Solution

- [ ] PR to web3.js
- [ ] Update web3.js dependency in status-react
- [ ] Replace https://github.com/status-im/status-react/blob/develop/src/status_im/protocol/web3/inbox.cljs#L33 with web3 call

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0xb6984bb365a88412818b72a6efd001bd7c734aee](https://etherscan.io/address/0xb6984bb365a88412818b72a6efd001bd7c734aee)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
