### ISSUE TITLE
/phone suggestions are not localized therefore I can't enter phone using significant format

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2811]
### Description

*Type*: Bug

*Summary*: 

when entering /phone command on Android device under Airplane mode it shows suggestions that are not localized so local phone number is not acceptable in Significant format. The same case works fine on iOS under Airplain mode.  I assume suggestions are based on sim-card installed in the phone even its in airplaine. 

#### Expected behavior
I should be able to enter phone number on android in significant format

#### Actual behavior
Can't enter phone nubmer  on Android in any other format except International, suggestions are not localized, Significant format is not acceptable

![image](https://user-images.githubusercontent.com/28752642/34339760-8e6433a0-e989-11e7-927e-f809c10abba5.png)

![image](https://user-images.githubusercontent.com/28752642/34339767-a1ee1544-e989-11e7-8dd8-060f628cde54.png)

### Reproduction

- Open Status on Android and create account
- Make sure you are under Wi-Fi with airplane mode - on
- call /phone command and check suggestions
- enter local phone number in significant format you have access to and hit send

### Additional Information
* Status version:  0.9.10-474-gc8168e9f+ (2031)
* Operating System: Android, iOS

#### Logs

https://app.testfairy.com/projects/4803590-status/builds/7370858/sessions/4/?accessToken=S9Dy0EkgKAYdrhmyqnsY7nSV298

https://app.testfairy.com/projects/4803622-status/builds/7358884/sessions/6/?accessToken=PkhU5HeeRp3zIGP9n4g2yybhGgA

**Comment by annadanchenko** [comment]
Phone feature is removed
