### ISSUE TITLE
Bash script that allows one to see a five-number summary of PR open time

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2812]
### User Story

As a developer, I want to know how long PRs stay open over time so that I can improve the code delivery speed.

### Description

*Type*: Feature/Tooling

*Summary*: Write a bash script that allows one to see a five-number summary of PR open time.

`./scripts/pr-statistics.sh` => 

```
Min: ...
Q1: ...
Mid: ...
Q3: ...
Max: ...
```

Additionally, the following options don't have to be exposed as arguments but should be changeable in the script:

- repo
- start time and end time
- print Q3 PR URLs

### Notes
https://en.wikipedia.org/wiki/Five-number_summary

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1200.00
Contract address: [0xab907a8c2c480e0d0f99cba9f4618517088f8798](https://etherscan.io/address/0xab907a8c2c480e0d0f99cba9f4618517088f8798)
Network: Mainnet
Paid to: StudioEtrange
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by onbjerg** [comment]
I'm working on this one, but I have a few q's:

- What are some acceptance criteria?
- What tools are assumed to be available on the platform (or, what platforms are targeted)?

Some tools, even basic ones like `date`, differ wildly for macOS users compared to Linux users. 😔

**Comment by michaelsbradleyjr** [comment]
Following on @onbjerg's question:  would it be acceptable (or better, even) to implement this as a standalone executable/bundle (for mac, win, linux)? That's possible with quite a few languages, of course, some closer to the Clojure/Script family than others.  OCaml/Reason and Racket might be good options, though the latter would definitely produce a small portable bundle vs. a single static binary.

**Comment by michaelsbradleyjr** [comment]
If having it be a shell script is the preferred way, then [creationix/nvm](https://github.com/creationix/nvm)'s [nvm.sh](https://github.com/creationix/nvm/blob/master/nvm.sh) demonstrates a wealth of well-honed feature detection and portability practices.

**Comment by rubberbird** [comment]
Can you please confirm linux distro and version?

**Comment by oskarth** [comment]
Hi all, sorry for the late reply!

@onbjerg 

1. What it says in description, other than that fairly free form :)

2. Minimal but reasonable assumptions, e.g. if math is annoying in bash then OK to to use small unix utility that is available on OSX and Linux, at least. I'd assume OSX and Ubuntu LTS to keep it simple, since most devs are on one of these platforms (or something very similar).

Re date: good point, not sure what best way to deal with this is. OK if it is using something like `epoch time` IMO, or do basic platform check (https://stackoverflow.com/questions/394230/detect-the-os-from-a-bash-script - check if Darwin else assume Linux, for purposes of this PR).

@michaelsbradleyjr: Good point! Assuming it is a simple portable executable this would also work :)

@rubberbird: Ubuntu 16.04 LTS.

**Comment by StudioEtrange** [comment]
Ok then, done.
How we submit this ? Is it just a PR to do ?

**Comment by ghost** [comment]
please read https://wiki.status.im/Building_Status contributing paragraph :)

**Comment by StudioEtrange** [comment]
Ok, that's rule on coding convention. But what about the bounty mechanism.
Do I have just to submit a new PR relating to this issue ?

**Comment by poiga** [comment]
Yes

**Comment by ghost** [comment]
Also read ' status-open-bounty commented 8 days ago •'

> Network: Mainnet
To claim this bounty sign up at https://openbounty.status.im and make sure to update your Ethereum address in My Payment Details so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by StudioEtrange** [comment]
Ok, then
I made some guess. Mainly about the info you wanted to be printed out for the five number summary.
For now I print creation date of PR. The oldest one, the newest one, and I compute date for mean, q1 and q3, by using every creation date of opened PR.
Is that the result expected ?
  
Or, you want spent five number summary of spent time (so only for closed issue) ?
 
I have the both solution implemented, so tell me

## Solution 1 output

Print creation date of only opened PR

> Tested on https://github.com/status-im/status-react
> Min: lundi 20 novembre 2017, 23:28:45 (UTC+0100)
> Q1: vendredi 22 décembre 2017, 13:17:41 (UTC+0100)
> Mean: jeudi 28 décembre 2017, 17:00:31 (UTC+0100)
> Q3: dimanche 31 décembre 2017, 22:13:41 (UTC+0100)
> Max: mercredi 3 janvier 2018, 22:19:03 (UTC+0100)

NOTE : output is in french here cause of my system, on other system, it will output local date.

## Solution 2 output

Print amount of time spent on closed PR.
As github API use 30 PR max by page, it could be slow when there is a lot of closed PRs


> Tested on https://github.com/status-im/status-dev-cli
> Min: 12
> Q1: 22656
> Mean: 245305
> Q3: 7546970
> Max: 10459664

**Comment by oskarth** [comment]
Copy paste from PR as I realize it wasn't really clear from issue:

@StudioEtrange Oh right, I realize this wasn't super clear in initial issue, but what I meant by:

> start time and end time

Is that one should be able to run `./scripts/pr-statistics.sh` with some variable like:
```
START_TIME=2017-11-01
END_TIME=2017-12-01
```
And then script should only check PRs in that interval.

The use case is to track how we improve merge speed over time.

**Comment by StudioEtrange** [comment]
Ok, done : )
PR is approved
Waiting for merge :)

**Comment by rubberbird** [comment]
so your only getting real values for the newest and oldedt PR? surely you need to get all the created_at values for all open PR's to have a valid data set, otherwise your jist guessing.

**Comment by oskarth** [comment]
@rubberbird Could you elaborate? Is this a comment on this solution https://github.com/status-im/status-react/pull/2893/files? If so would you mind reviewing and pointing out where you think the logic is faulty? Thanks!

**Comment by StudioEtrange** [comment]
> you need to get all the created_at values for all open PR's to have a valid data set,


@rubberbird That's what is done for now in https://github.com/status-im/status-react/pull/2893/files all PR in the selected period are fetched.

Then, depending of the use mode :
* "open" : **ALL** PR of the chosen period with state open (not merged nor closed) are selected. Here to compute stats `created_at` values from json are checked to be selected as the PR selection. Then It computes spent time between `created_at` and today to get spent times until now for each selected PR. Then to do some stats (five number) with this.

* "merge" : **ALL** PR of the chosen period with state close AND merge are selected. Here to compute stats `created_at`, `merged_at` and `closed_at` values from json are checked (so non "null" values) to be selected as the PR selection. Then It computes spent time between `created_at` and `closed_at` to get spent times for each selected PR. Then to do some stats (five number) with this.


  
**To be more comprehensive of what I have described the output are these :**

- **stats on open PRs**
- verbose mode active
- with START_TIME="2017-01-01" and END_TIME="2017-12-01"
```
[Fetching open PR stats from status-im/status-react]
[Analysing PR lists: 1/1]
[Stats computed on 30 PR between 2017-01-01 and 2017-12-01]
             Min |               Q1 |             Mean |               Q3 |              Max
  0d 00h:36m:08s |   0d 23h:45m:24s |   6d 11h:34m:26s |  10d 20h:55m:20s |  44d 21h:43m:29s
```

- **stats on already merged PRs**
- verbose mode active
- with START_TIME="2017-01-01" and END_TIME="2017-12-01"
```
[Analysing PR lists: 34/41]
[Stats computed on 15224 PR between 2017-01-01 and 2017-12-01]
             Min |               Q1 |             Mean |               Q3 |              Max
  0d 00h:00m:07s |   0d 00h:52m:31s |   0d 16h:07m:08s |   3d 06h:50m:58s |  71d 01h:44m:14s
```
