### ISSUE TITLE
Flag hygiene: Remove NOTIFICATIONS_WIP_ENABLED flag

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2813]
### User Story

As a developer I want flags to be up to date so we know what behaviors we want to toggle.

### Description

*Type*: Feature/Refactor

*Summary*: Remove NOTIFICATIONS_WIP_ENABLED flag while keeping behavior for flag ON.

See https://github.com/status-im/status-react/blob/develop/src/status_im/utils/config.cljs#L19

#### Expected behavior
PNs work with flag.

#### Actual behavior
Same behavior without flag.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 380.00
Contract address: [0xd4b5c3deb7102bad105817dc4661de872f9bed46](https://etherscan.io/address/0xd4b5c3deb7102bad105817dc4661de872f9bed46)
Network: Mainnet
Paid to: taylorjdawson
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
