### ISSUE TITLE
Benchmark and investigate crypto perf by changing library

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2814]
### User Story

As a developer, I want to use the fastest safe crypto possible, so I have a good user experience.
### Description

*Type*: Feature/Perf

*Summary*: Replace ECCJS (SJCL) library with libsodium/chloride while keeping interface and check perf.

- [ ] Try libsodium/chloride while keeping interface same
- [ ] Make a solid benchmark comparing current encrypt/decrypt function vs libsodium/chloride

See https://github.com/status-im/status-react/blob/23399c63e172479876fe2a76b4eb9f5b9785f9b5/src/status_im/protocol/encryption.cljs

Additional context:
- Following our eccjs lib and issues I see perf is basically untouched. Someone who has done a lot of work on this a guy called Dominic Tarr (see https://github.com/jpillora/eccjs/issues/3 and https://dominictarr.github.io/crypto-bench/ and https://github.com/dominictarr/chloride ).
- https://twitter.com/oskarth/status/944289740739801088 (EDIT: Oops, I cleaned all my tweets, his reply: https://twitter.com/dominictarr/status/944428656591388672)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc75f00705082a7c7ec68886862a81fd7a0e7b3b31a5a35981f50511bbf26f352](https://etherscan.io/tx/0xc75f00705082a7c7ec68886862a81fd7a0e7b3b31a5a35981f50511bbf26f352)

**Comment by msuess** [comment]
Would love to have a look at this. Is this still relevant?

@oskarth AFAICT libsodium uses Curve25519 instead of P384. While the interface could stay the same, we won't be able to decrypt old messages using the new implementation. Is this a problem?

**Comment by oskarth** [comment]
cc @yenda @janherich who can answer this better wrt new protocol development.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc12c9f951fe1669418d3752b8429fddb05c2bd747df07e42683064b9d6f51b5e](https://etherscan.io/tx/0xc12c9f951fe1669418d3752b8429fddb05c2bd747df07e42683064b9d6f51b5e)

**Comment by yenda** [comment]
@msuess Hi thanks for your interest, we have removed crypto libraries from clojure side as they were used to generate a keypair for message encryption, with the benefit that we don't need nodeify hack anymore to use them. 

However it can still be interesting if one of these libs can work without the crypto node module, for local data encryption. We probably need to flesh out the requirements for that if we want to move further though.

**Comment by cryptohazard** [comment]
Hi, is there any update on this task?

**Comment by yenda** [comment]
@cryptohazar at this point we moved all encryption to status-go, so I think we can close this issue @oskarth
