### ISSUE TITLE
"Back" in Console chat doesn't redirect to Sign In screen (when user has several accounts in one device)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2820]
### Description

*Type*: Bug
*Summary*: when you create new account in Console chat "Back" arrow is not working until you set up password
![back](https://user-images.githubusercontent.com/4557972/34357451-f1aab512-ea4f-11e7-9901-c344f75d91dd.png)

#### Expected behavior
"Back" redirects to main screen with list of users ("Sign in to Status")
![1](https://user-images.githubusercontent.com/4557972/34414870-6bb2668e-ebf4-11e7-90e2-7655bad1fd36.jpg)

#### Actual behavior
nothing happens, user remains in Console Chat

### Reproduction

- Open Status with existing users
- Tap on "Create new account"
- Tap on "Back"

### Additional Information

* Status version: 0.9.11d481, nightly 26/12
* Operating System: Android,iOS

#### Logs
TF (0:07 - 0:28) https://app.testfairy.com/projects/4803622-status/builds/7371377/sessions/37/?accessToken=AoUwjTzk3g1mQ0oarMXcMRhVIwI

**Comment by annadanchenko** [comment]
@churik please 
1. modify description of the actual result 

> Back doesn't work  
> 

so it describes what's happening. Currently, it only indicates that there is an issue but does not tell exactly what happens after you tap on Back button. See https://wiki.status.im/Bug_Report#Good_Bug_Title for details 
2. update

> "Back" redirects to main screen with list of users

> 
with the screen title and preferably its picture

**Comment by churik** [comment]
@annadanchenko done, thanks for comment

**Comment by yenda** [comment]
@asemiankevich please test in develop it should be fixed by https://github.com/status-im/status-react/pull/3198

**Comment by churik** [comment]
Is not reproducible in beta
