### ISSUE TITLE
Rows and focus are overlapped by keyboard when text in input field (Chat) contains more than 2 rows of text or 8 rows emoji 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2822]
### Description
*Type*: Bug

*Summary*: when you type more than 2 rows of text or 7 rows of emoji focus goes below input field and all next rows are overlapped by keyboard, so you cannot see what you are typing
![andr_20](https://user-images.githubusercontent.com/4557972/34386376-fbac5a84-eb30-11e7-8e12-d76e693ffeb8.png)

#### Expected behavior
user can see what he types and top row goes upper input field

#### Actual behavior
user can see what he types and bottom row goes under input field and overlapped by keyboard

### Reproduction

- Open Status
- Go to Chats
- Open any chat
- Type text which contains more than 2 rows of text (or 8 emoji rows)

### Additional Information

* Status version: 
 is reproducible on current develop 27/12 (0.9.11d486)

* Operating System: Android

#### Logs

TF session (with text): (01:50 -
 2:20) 
https://app.testfairy.com/projects/4803622-status/builds/7375901/sessions/9/?accessToken=uKmkdE9nlLqNRLqXoHe1N-UHdfE
TF session (with emoji): (0:08 - 01:05)
https://app.testfairy.com/projects/4803622-status/builds/7375500/sessions/5/?accessToken=XAuk/hwAEY7q5VlI1H9Mz1Cc0Xs

**Comment by oskarth** [comment]
@churik does this solve it? https://github.com/status-im/status-react/pull/2858 sorry, it was in review queue for a long time.

**Comment by churik** [comment]
@oskarth yes, it is

**Comment by oskarth** [comment]
Solved in https://github.com/status-im/status-react/pull/2858 but PR didn't close issue.
