### ISSUE TITLE
App is freezing after cutting/deleting long text from input field in Chat (more than 7 rows)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2823]
### Description
*Type*: Bug

*Summary*: when input field in Chat contains several rows of text (7+ rows), user cut part of this text or all text or just quickly delete symbols,  input field doesn't restore initial state and app becomes unresponsive with this size of input field
![andr_2](https://user-images.githubusercontent.com/4557972/34380449-2b231de2-eb0a-11e7-9c5b-6da5ec67eb58.png)

#### Expected behavior
input field restores initial size;
app is responsive.

#### Actual behavior
input field doesn't go back to  initial size;
app is unresponsive.

### Reproduction

- Open Status
- Go to Chats
- Open any chat
- Type text which contains more than 7 rows of text 
- cut part of it
- quickly delete all remaining text

### Additional Information

* Status version: 
 is reproducible on current develop 27/12 (0.9.11d486)

* Operating System: Android

#### Logs

TF session (0:30 - 02:25): https://app.testfairy.com/projects/4803622-status/builds/7375901/sessions/13/?accessToken=c2gsnGGHnpch6lwZjOwFHwoLMEg

**Comment by annadanchenko** [comment]
@churik can you reproduce it?

**Comment by churik** [comment]
Cannot reproduce on current develop.
