### ISSUE TITLE
'bot.js loading failed browse TypeError: null is not an object' if quickly tap on send button for password creation in console

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2824]
***Type***: Bug

***Summary***: If quickly send password on a first password submission (i.e to tap twice on 'Send message' button), - second step (to confirm the password) does not hide characters under asterisks ('••••••') and after password confirmation got submitted - the error `bot.js loading failed browse TypeError: null is not an object (evaluating 'params["password-confirmation"].length')` appears.

#### **Expected behavior**
Characters hidden under asterisks, no errors appears, password submitted and created successfully.  
#### **Actual behavior**
Confirm password (second step of password creation) is not hidden under asterisks,`bot.js loading failed browse TypeError: null is not an object (evaluating 'params["password-confirmation"].length')` error appears.
![bot_js_loading_failed](https://user-images.githubusercontent.com/8749671/34381942-665d74f2-eb14-11e7-968d-de6ed3668414.png)

### Reproduction
Video: https://app.testfairy.com/projects/4803622-status/builds/7375901/sessions/29/?accessToken=3FfucVToB58R4/OubUsTzspA7WY

1) Open Status
2) Tap on `+ Create new account`
3) In Console type 6 (or more) characters (I used `123456` as value)
4) Quickly tap several times on 'Send message' button
5) Type the password value again (`123456` in my case). *Note:* it is not hidden under asterisks now.
6) Tap on 'Send message'

### Additional Information
* Status version: 0.9.10-486-g5206f297+ (develop)
* Operating System: Android 7.0 (Samsung J7 real device), Android 6.0 (Samsung Galaxy S6 emulator), iOS

**Comment by Serhy** [comment]
Root cause of the issue might be similar (or same) as in the https://github.com/status-im/status-react/issues/1604

**Comment by annadanchenko** [comment]
closing because of new onboarding flow (password is no longer in console)
