### ISSUE TITLE
Migrate android build to latest gradle plugin

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2834]
### User Story

As a developer, I want to use latest tools to benefit from greater performance

### Description

*Type*: Feature

Migrate to latest [gradle plugin](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html) as it provides greater compilation performance.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 750.00
Contract address: [0x23d368d696d568cb267c3fc1fdc025c678909ffe](https://etherscan.io/address/0x23d368d696d568cb267c3fc1fdc025c678909ffe)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
