### ISSUE TITLE
Several cards are added in "Popular #hastags" after adding one hashtag [2483]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2842]
### Description

*Type*: Bug

*Summary*: when user add #one hashtag, than #another (in Profile status) and go "Popular #hashtags> All - several items for  #another hashtag are displayed.
first hashtag -> one item on "Popular #hashtags"
second hashtag -> two items on "Popular #hashtags" and so on.

#### Expected behavior
amount of items in "Popular #hashtags" is equal number of hashtags

#### Actual behavior
amount of items in "Popular #hashtags" is more than number of hashtags
![hsgtg](https://user-images.githubusercontent.com/4557972/34417029-02fef0fc-ebff-11e7-9ec7-da68c7861a32.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status and create account
- Open Discover - check there is no Recent statuses and hashtags
- Open drawer, tap inside status string and add "#" in front of some word, e.g. "#begins"
- Tap on Username, so status is saved
- Close drawer. Check that Discover shows added hashtag in Recent statuses and in Popular #hashtags
- tap on "all" in Popular #hashtags. One hashtag "#begins" displayed and one card with status.
- Open drawer, tap inside status string and add "#" in front of some another word, e.g. "#yours"
- Tap on Username, so status is saved
- Close drawer. Check that Discover shows added hashtag in Recent statuses and in Popular #hashtags (counter is 2 on last card in Popular #hashtags)
- tap on "all" in Popular #hashtags

### Additional Information

* Status version: 
PR #2483 status-im:feature/refactor-discover-events
0.9.11d466
is not reproducible with current develop

* Operating System: Android, iOS

After relaunch app number of "Popular #hashtags" becomes equal to number of hashtags (so is changed).
Add new hashtag - issue is reproduced with new one
#### Logs
(00:12-00:55) https://app.testfairy.com/projects/4803590-status/builds/7392168/sessions/7/?accessToken=mryGvR-PIpFriRx/QuXdPelE5Y8

**Comment by oskarth** [comment]
Marking as low priority since Discovery won't be in MVP.

**Comment by annadanchenko** [comment]
Discover feature is removed
