### ISSUE TITLE
Search in Discover leads to Search in Chats [2483]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2843]
### Description
*Type*: Bug

*Summary*: tap on Search icon in Discover redirects to Chats with open Search field (focus outside Search field).
So, functionality of searching status by tag is blocked.

#### Expected behavior
focus in search field in Discover, so I can search tags

#### Actual behavior
redirected on Chats (focus outside Search field)

### Reproduction

- Open Status
- Install Status and create account
- Open Discover - check there is no Recent statuses and hashtags
- Open drawer, tap inside status string and add "#" in front of some word, e.g. "#begins"
- Tap on Username, so status is saved.
- Go to Discover
- Tap on Search icon

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 
PR #2483 status-im:feature/refactor-discover-events
0.9.11d466
is not reproducible with current develop
* Operating System: iOS

#### Logs

00:15 - 00:18 
https://app.testfairy.com/projects/4803590-status/builds/7392168/sessions/12/?accessToken=VpcUaKRrZEQgqkyjKxchVweM2bQ

**Comment by annadanchenko** [comment]
Discover feature is removed
