### ISSUE TITLE
Provide correct gas estimate default for ERC20

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2848]
### User Story

As a user, I want the gas default to match the ERC20 token I am sending.

### Description

*Type*: Feature

Leverage `estimateGas` to provide a proper gas estimation.

**Comment by asemiankevich** [comment]
@jeluard i assume this is done already?

**Comment by andytudhope** [comment]
Removing bounty labels due to inactivity; re-add if in error @jeluard

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x6743059eee238e9fa1836235e823aa2bd5bbf979177bc8ac33db6044ef3bd7e9](https://etherscan.io/tx/0x6743059eee238e9fa1836235e823aa2bd5bbf979177bc8ac33db6044ef3bd7e9)

**Comment by debragail** [comment]
![58295dd2-3d20-417e-a97a-d64b9cb45f01](https://user-images.githubusercontent.com/552529/39797159-75b82ba0-530f-11e8-96a2-94fe52347857.jpeg)

**Comment by debragail** [comment]
Is this the only place that needs to reflect the estimate as the currency being sent?  This is iOS screenshot but also for Android the page is the same in simulator.

**Comment by debragail** [comment]
what other currencies will be accepted?  Is it fair to model the data as `asset` instead of `eth`?

**Comment by jeluard** [comment]
Idea is to support any ERC20 token. Based on the contract address, rely on [estimateGas](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethestimategas) to get an estimation of the gas cost to [transfer](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#transfer) tokens.

**Comment by debragail** [comment]
i started this and i'll try to finish, i just can't do a Status build on Yosemite.  :(

**Comment by pablanopete** [comment]
@jeluard is this issue still relevant to a bounty? Revoking bounties and then triaging correctly if they are no longer relevant.

**Comment by jeluard** [comment]
@pablanopete It can be closed for now
