### ISSUE TITLE
Cannot Scan QR code from DApp

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#2854]
### User Story

As a developer, I want to be able to build DApps that can scan QR codes.

### Description

*Type*: Feature

*Summary*: In line with this idea for Decentralart: https://github.com/status-im/ideas/issues/66, we need to be able to scan QR codes directly from a DApp within Status.

#### Expected behavior
Can scan a QR code easily and get the returned data to display.

#### Actual behavior
Permission request for access to camera never shows up. 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Navigate to Console
- `@browse` to either https://schmich.github.io/instascan/ or https://webqr.com/
- Notice that a request for permission to use the camera never materialises and that you cannot scan anything.

### Solution

*Summary*: 

- Bug @jeluard @flexsurfer or @alwx to figure out how to give DApps access to our scanning a QR code screen, or allow DApps to request these sort of permissions.

### Additional Information
* Status version: 0.9.12+
* Operating System: Android and iOS

**Comment by grishick** [comment]
my DApp also needs this feature

**Comment by andytudhope** [comment]
@grishick check here and let me know if this works for you: https://github.com/status-im/status-react/pull/3354

**Comment by PeterTheOne** [comment]
Didn't work for me on Version 0.9.27 (7656); node v0.13.1 or maybe I'm doing something wrong?
