### ISSUE TITLE
Onboarding Password Request

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#286]
<img width="478" alt="passwordrequest" src="https://cloud.githubusercontent.com/assets/2714786/18942510/2c750ae4-864c-11e6-9965-e16fb0dc3fba.png">

- [x] "Keypair password" should just be "Password" + with " Request" appended = "Password Request"
- [x] Password Icon is in Response header is a green $ symbol when it should be "inverted" icon that user tapped on, ie.
![image](https://cloud.githubusercontent.com/assets/2714786/18942410/6f102024-864b-11e6-85a0-b7822e4713ff.png)

- [x] Response header information is by ??? and has no timestamp?
- [x] Password Request parameter says "Type" when it should say the param prompt "Type your password"
- [x] Password does not ask for re-entry, second param should have a param prompt "Please re-enter password to confirm", throwing validation error, should the password not match first
<img width="358" alt="screen shot 2016-09-29 at 1 57 09 pm" src="https://cloud.githubusercontent.com/assets/2714786/18942585/a30c90c8-864c-11e6-9b9f-6d1fb66ecbbb.png">

- [x] Displaying the send icon should only happen once the parameter has some value.

**please watch keynote presentation carefully**
**How password request works should also be generalised as if using Chat API.**

**Comment by rasom** [comment]
@jarradh, imagine a scenario when a wrong password was entered and a user can not confirm it, how the user can return to the first stage?

**Comment by jarradh** [comment]
on Nth try, validation handler could return react-native gui with link "N tries remaining" until hits 0 then resets to first, to set a new password.

Alternatively the user cancel the response and try again

**Comment by rasom** [comment]
I thought that better to implement `password` parameter type on `status-react` than implement some specific logic exactly for [`password`](https://github.com/status-im/status-react/blob/64e1a7e844caa9c5183dd9eb770c1f540ff8964e/resources/console.js#L180-L180) command because in this case it could be used by other dapps. And in this case, there will no be any returned react-native gui.  

But ok, the user will have N attempts and then will be returned to the first stage, got it.

**Comment by jarradh** [comment]
Well, it's an interesting idea, we can have a password type that hides the input text, but at what point will we ever start using our API instead of writing custom logic for everything? The idea is maintain generality and using our API so we can learn to work with it and adapt it and make it usable for other DApps to be able to create whatever they need.

Besides, we do have custom logic for entering passwords, thats the whole purpose of the transaction management.
