### ISSUE TITLE
Error loading data when entering wallet

### ISSUE THREAD

**Issue by Kimoa85** [status-im/status-react#2864]
Type: Bug

Summary:
When entering my wallet I see an error on top "error loading data" after changing network

Expected behavior
I suppose it should be able to load the data

Actual behavior
there is an error on top of the page saying it is unable to load the data

Reproduction
In any of your Status accounts, try entering the wallet and look at the top part of the screen.

Additional Information
Status version: release 0.9.12
Operating System:
Xiaomi redmi note 4, android 6.0.1

**Comment by asemiankevich** [comment]
i cant reproduce it
