### ISSUE TITLE
message "aaaa" is not defined appears as: {:message "aaaa" is not defined"}

### ISSUE THREAD

**Issue by Kimoa85** [status-im/status-react#2866]
Type: Bug

Summary:
When messaging the console a non-defined message it appears ass: {:message "aaaa" is not defined"}
rather than just appear as: message "aaaa" is not defined 

Expected behavior
message "aaaa" is not defined 

Actual behavior
{:message "aaaa" is not defined"}

Reproduction
Enter a chat with console, type "aaaa" receive the reply {:message "aaaa" is not defined"}

Additional Information
Status version: release 0.9.12
Operating System:
Xiaomi redmi note 4, android 6.0.1

**Comment by churik** [comment]
no console chat anymore
