### ISSUE TITLE
'from [username]'/'to [username]' is not shown in request/send message bubble in group chat on message sender screen

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2868]
***Type***: Bug
***Summary***: When UserA request/send ETH in group chat from/to UserB - there is no recipient in /request (/send) message bubble is shown on the message sender screen (on UserA chat screen in this case). However, it is displayed on receiver's side (UserB in this case). 

#### Expected behavior
'from [username]'/'to [username]' is visible in request/send ETH message bubble in group chat on sender's side

#### Actual behavior
'from [username]'/'to [username]' is not visible in request/send ETH message bubble in group chat on sender's side
![screenshot_20180102-172752](https://user-images.githubusercontent.com/8749671/34489109-8b243fd6-efe3-11e7-907a-7c1f8a12201e.png)

### Reproduction

1) Open Status on UserA device
2) Open Status on UserB device
3) Send /faucet request by UserA (wait until you receive 0.1ETH in Wallet)
4) UserA adds UserB in contacts 
5) UserA creates group chat with UserB
6) In the group chat UserA taps on /request, selects UserB from the 'Request ETH' list, specifies amount and sends the message.
7) Check message bubble on UserA screen
8) In the group chat UserA taps on /send, selects UserB from the 'Send transaction' list, specifies valid amount of ETH (I used 0.01) and sends the message.
9) Check message bubble on UserA screen

### Additional Information
* Status version: 0.9.10-503-g3e940b5b+ (
* Operating System: Android 7.0 (Samsung J7 real device), iOS 11.1.2 (iPhone X)

**Comment by janherich** [comment]
@Serhy just to be clear, this happens on develop, #2807 branch, or both ?

**Comment by Serhy** [comment]
@janherich both branches affected: develop and #2807
