### ISSUE TITLE
Command Messages missing !,  Password using ** 

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#287]
<img width="388" alt="screen shot 2016-09-29 at 2 06 17 pm" src="https://cloud.githubusercontent.com/assets/2714786/18942811/1eb105b4-864e-11e6-9815-edd3be39c28b.png">

- [x] keypair should be !password
- [x] password using *** instead of ●●●
- [x] font looks off? is it Roboto Regular?

**Comment by rasom** [comment]
@jarradh `password` is the response and once we decided don't start responses with "!", only commands. Should it be changed now?

**Comment by jarradh** [comment]
how about "?" , blank doesn't look great

**Comment by rasom** [comment]
ok, let it be "?" for all requests

**Comment by rasom** [comment]
Regarding fonts, as far as I can see: 

`sans-serif/sans-serif-medium` are used in android
https://github.com/status-im/status-react/blob/80ec3eeef3c816b5ed24bf992fac4115523ca378/src/status_im/android/platform.cljs#L20-L20  

and `SFUIDisplay-Regular/SFUIDisplay-Medium` in ios version
https://github.com/status-im/status-react/blob/80ec3eeef3c816b5ed24bf992fac4115523ca378/src/status_im/ios/platform.cljs#L25-L25

**Comment by jarradh** [comment]
iOS is correct, Android however is not, in Zeplin Styleguide for Android shows Roboto, all texts are variants of Roboto on Android.

**Comment by rasom** [comment]
in zeplin `SFUIText-Regular/Medium` is used for iOS, is it the same font?

**Comment by jarradh** [comment]
hmmm, I imagine not, so iOS is also incorrect and sould be using `SFUIText-Regular` variants, I don't see `SFUIDisplay-Regular` in any screen

**Comment by alwx** [comment]
`Roboto` = `sans-serif` in most cases.
But sometimes manufacturers like Samsung or HTC include their own fonts instead of Roboto, thus by specifying `sans-serif` we actually specify a default device font. IMO this is better than simply including Roboto, but we can of course force our app to use `Roboto` in any case.

**Comment by jarradh** [comment]
you're right @alwx and I agree. So if it's not the font, it's the weight ?

```
130|root@vbox86p:/system # cat /system/etc/fonts.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
    NOTE: this is the newer (L) version of the system font configuration,
    supporting richer weight selection. Some apps will expect the older
    version, so please keep system_fonts.xml and fallback_fonts.xml in sync
    with any changes, even though framework will only read this file.

    All fonts withohut names are added to the default list. Fonts are chosen
    based on a match: full BCP-47 language tag including script, then just
    language, and finally order (the first font containing the glyph).

    Order of appearance is also the tiebreaker for weight matching. This is
    the reason why the 900 weights of Roboto precede the 700 weights - we
    prefer the former when an 800 weight is requested. Since bold spans
    effectively add 300 to the weight, this ensures that 900 is the bold
    paired with the 500 weight, ensuring adequate contrast.
-->
<familyset version="22">
    <!-- first font is default -->
    <family name="sans-serif">
        <font weight="100" style="normal">Roboto-Thin.ttf</font>
        <font weight="100" style="italic">Roboto-ThinItalic.ttf</font>
        <font weight="300" style="normal">Roboto-Light.ttf</font>
        <font weight="300" style="italic">Roboto-LightItalic.ttf</font>
        <font weight="400" style="normal">Roboto-Regular.ttf</font>
        <font weight="400" style="italic">Roboto-Italic.ttf</font>
        <font weight="500" style="normal">Roboto-Medium.ttf</font>
        <font weight="500" style="italic">Roboto-MediumItalic.ttf</font>
        <font weight="900" style="normal">Roboto-Black.ttf</font>
        <font weight="900" style="italic">Roboto-BlackItalic.ttf</font>
        <font weight="700" style="normal">Roboto-Bold.ttf</font>
        <font weight="700" style="italic">Roboto-BoldItalic.ttf</font>
    </family>
```
