### ISSUE TITLE
Show unread message badge notifications

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#2871]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see unread notifications so that I can know if I have unread messages whilst in other chats or other parts of the app.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Whilst using the app, users want to know if there are new messages waiting. In other chat apps it is common to see badge notifications so that the user can see at a glance how many unread messages there are. 

This is an important feature for beta as users can be frustrated if they don't see new messages. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I expect that from within a chat, or another part of the app I should know if there are unread messages.

#### Actual behavior
[comment]: # (Describe what actually happened.)
No notifications are shown. To see if there is a message the user has to view the Chat list.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Chat with User A and receive a message from User B. There is no indication a new message is waiting.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Show an unread badge icon on the tab bar. This will alert the user to unread items from other tabs.

<img width="366" alt="list" src="https://user-images.githubusercontent.com/116099/34492297-f3ac7656-efb4-11e7-88a9-ee65ea8b90a9.png">

- [ ] Show an unread badge in the chat Navbar. This will alert the user that there are other unread chats within the chat context.

<img width="376" alt="screen shot 2018-01-02 at 12 07 51 pm" src="https://user-images.githubusercontent.com/116099/34492452-a48e9562-efb5-11e7-8ce9-5ee9b8ca7cf3.png">

- [ ] Show an unread badge count in the chat list. This will alert the user to which chats have unread messages.

<img width="374" alt="screen shot 2018-01-02 at 12 08 58 pm" src="https://user-images.githubusercontent.com/116099/34492489-d1f5b0a8-efb5-11e7-9ce2-3a318341d7b6.png">

- [ ] App icon badge count

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: All
* Operating System: All

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x2a2c00ceb099b5dcde878732fca2375007a398f1d79c5b208b1bcc480ee02570](https://etherscan.io/tx/0x2a2c00ceb099b5dcde878732fca2375007a398f1d79c5b208b1bcc480ee02570)

**Comment by enricrp8** [comment]
I am new in Status, so I'm not used  to how do you apply for a project.
I would like to help you with that project, but I need more information:
Do you wanted in React, just Android,just iOS or both(using java and swift)?

**Comment by chadyj** [comment]
Hey @enricrp8 thanks for your interest. Check out the [wiki](https://wiki.status.im/Developer_Documentation) for tips on how to [get started](https://wiki.status.im/Developer_Documentation).
