### ISSUE TITLE
Refactoring of e2e automation framework

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#2874]
### User Story

As an automation engineer I would like to keep automation framework in readable state, decrease running time and bypass minor issues which blocks automated tests from testing core features.

### Description
The framework should be refactored in order to increase readability, so each test team member could be easily involved in creation of e2e tests, 
Decrease running time.
Bypass minor product bugs e.g. #2805  #2417 etc.

**Comment by oskarth** [comment]
@antdanchenko Can you add PRs to QA Pipeline projects in the future? Should end up in right column by default then.

**Comment by oskarth** [comment]
@antdanchenko Oops my bad, thought this was a PR. Meant to comment on https://github.com/status-im/status-react/pull/2875 - removing issue from pipeline (PR already there)
