### ISSUE TITLE
Wallet Icon & Phone Number Request Icon

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#288]
We need an icon for the Wallet DApp as well as an icon for phone number request (for contact sync)

<img width="359" alt="screen shot 2016-09-29 at 2 10 08 pm" src="https://cloud.githubusercontent.com/assets/2714786/18942943/03dd0854-864f-11e6-980c-8bf0935a523f.png">

**Comment by andmironov** [comment]
About the wallet icon, wanted to make it clear: are you talking about the dollar?
![icons](https://cloud.githubusercontent.com/assets/3115606/18997680/2d228c1c-873e-11e6-9129-94c507ae2d5f.png)

**Comment by jarradh** [comment]
Oh I thought that was a placeholder, we're talking about the Wallet DApp (not a command icon) - like an icon for the user profile of the Wallet DApp, a $ symbol doesn't really do it justice and doesn't really make sense in the context of a wallet. A $ symbol would be better suited for a stablecoin that tracked USD - which we don't have and won't have for awhile

**Comment by andmironov** [comment]
Here they are. In Zeplin https://zpl.io/2cvab9 and https://zpl.io/Z1fimyJ

![dapp_avatars](https://cloud.githubusercontent.com/assets/3115606/19806236/3e88c2e2-9d22-11e6-84f4-776f06078444.png)
![request_icons](https://cloud.githubusercontent.com/assets/3115606/19806235/3e865458-9d22-11e6-9a86-5a4d355abc3c.png)
