### ISSUE TITLE
Offline inboxing: Confirm `admin_peers` and `admin_addPeer` are available when called via `CallRPC` binding.

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2885]
Converting old note to issue so this doesn't get lost. Not a priority right now, but for correctness this might come up at some point.

Confirm `admin_peers` and `admin_addPeer` are available when called via `CallRPC` binding.

Context: AddPeer -> wait resp -> markTrustedPeer possible race condition. Possible solution: poll for isPeerAdded (or check peers list directly as above)

**Comment by oskarth** [comment]
^ @dmitryn @yenda @cammellos  haven't touched this code in a while - do you know if this issue is still relevant or if we should close it?

**Comment by yenda** [comment]
I don't think it is still relevant, currently the peer is added then nothing happens until there is a signal from the discovery protocol that a peer was added and the added peer was the mailserver we are connecting to, only then does it proceeds to mark the peer as trusted
