### ISSUE TITLE
Random names are shown instead of a users chosen name

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#2892]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see the profile names of users I interact with in p2p chats, group chats, and public chats so that I can identify users and follow along with chats.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When I've been testing the beta and adding friends I never know who I'm chatting with since the app shows me names like "descriptive striped marten" even if the user has set a profile name. After adding a few contacts my chat list is full of random names and it is very confusing to know who is who. Group chats are impossible to follow since the random names aren't easily recalled and remembered by humans since they are all meaningless.

<img width="311" alt="whodis" src="https://user-images.githubusercontent.com/116099/34539850-515d2a70-f0a0-11e7-8c6d-59425d349c7d.png">

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Like all other chat programs I expect to see the chosen profile names of people I'm chatting with. 

If I scan the QR code of my friend Tom, and start chatting with Tom and he has set his profile name to Tom, I expect to see "Tom" as his name.

#### Actual behavior

If I scan the QR code of my friend Tom, and start chatting with Tom and he has set his profile name to Tom, I to see "octopus underwear thursday" (or some other meaningless name) as his name. Since my contact list is full of other names I can't no longer find Tom's message.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

P2P:
- User 1 sets their profile name.
- User 2 adds user 1 and starts chatting.
- User 2 doesn't see User 1's profile name.

Public Chat:
- Create a new account
- Join a public chat
- Nobody's profile names are shown.
EDIT: this is completed in https://github.com/status-im/status-react/pull/3128

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
I propose we show the user's set profile name in all interactions.

(A workaround exists where I can add every friend to my contacts, but this isn't intuitive, and isn't practical in group chats. It doesn't help with privacy and only adds hurdles for the user)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: All
* Operating System: All

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by flexsurfer** [comment]
changed label because it works as designed

**Comment by VoR0220** [comment]
I like the anonymity aspect of it and the plausible deniability aspect. Perhaps it should be a setting for random names determined by address to pop up and from there allow for people to change the name client side themselves. No need to be broadcasting your identity to certain accounts. Or better yet, compress identity into an encrypted whisper packet, and from there open it alongside the first message to give you...the identity described...problem is this could lead to some nasty scammers...Uport comes to mind for some assertion of identity here.

**Comment by chadyj** [comment]
Closing this as as Andrey said "it works as designed"
