### ISSUE TITLE
Street is not found by name when sending location

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#2894]
### Description

*Type*: Bug

*Summary*: 
Entered street name is not found in the list of suggestions when typing an address with a real street to /location command

#### Expected behavior
Entered street is found

#### Actual behavior
Not relevant list of locations is displayed when typing part of street name
![part](https://user-images.githubusercontent.com/29711298/34540444-40e04abe-f0dd-11e7-9ff7-9e13e139d969.jpg)

No results found when typing full street name
![full](https://user-images.githubusercontent.com/29711298/34540448-4548a740-f0dd-11e7-8a3d-14c12ca36dd6.jpeg)

### Reproduction

1. Open Status app
2. Go to one-to-one chat with another user
3. Tap on /location command
4. Type ‘Kyiv’ in the input field after the ‘/location’
5. Type comma
6. Type part of existing street name - ‘Amoso’
7. Type full existing street name - ‘Amosova’

### Additional Information
Status version: 0.9.12+
Operating System: Real device OnePlus A5000, Android 7.1.1

**Comment by asemiankevich** [comment]
Hi @yevh-berdnyk ! Thanks for your bug report. We are using 3-d party map service so if it does not have particular street / address / location - we can't send it within Status as well.
