### ISSUE TITLE
Wallet DApp missing from chat list 

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#290]
Although technically the user hasn't started a chat with contact list, since it's next screen users see, lets have it available.

<img width="319" alt="screen shot 2016-09-29 at 2 17 16 pm" src="https://cloud.githubusercontent.com/assets/2714786/18943007/753c53c4-864f-11e6-8efe-077e99514622.png">

**Comment by rasom** [comment]
How did you get there? After registration?

**Comment by jarradh** [comment]
yes
