### ISSUE TITLE
Unread badge counter doesn't fit large numbers

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#2900]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Unread messages counter badge doesn't fit large numbers on chat list screen.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
ios: number is inside the badge
android: number is not cut off

#### Actual behavior
ios: Number is outside the badge
android: number cut off (maximum 3 symbols shown)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

#### ios
- Open Status
- Have chat with more than 300+ unread messages (join #status public channel for example)
- Go to chat list
- Number is out of badge container

#### android
- Open Status
- Have chat with 1234 (any 4-digit number) unread messages (join #status public channel for example)
- Go to chat list
- You will see "123" unread counter, not "1234"

[comment]: # (Android or iOS.)
Operating System: iOS (simulator) and Android (simulator)

<img width="528" alt="screenshot 2018-01-04 11 46 11" src="https://user-images.githubusercontent.com/23836/34556324-e705e6b0-f146-11e7-9e4d-0a95906463fd.png">

<img width="555" alt="screenshot 2018-01-04 13 30 23" src="https://user-images.githubusercontent.com/23836/34559620-918d661a-f153-11e7-98ac-f0e4f7b44766.png">

**Comment by andytudhope** [comment]
Pretty cool that there were 357 messages in the status chat this morning though 😉 🎉 Can we maybe bounty this @dmitryn?

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Contract address: [0x976f8e12fa1494eadfae905e1a625f56027e8d97](https://etherscan.io/address/0x976f8e12fa1494eadfae905e1a625f56027e8d97)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by Emnnke** [comment]
For Android: if you need to show a number greater than 999, mb, you can use the reduction for 1000 messages of 1k, for the number of messages more than 1000 - 1k+ ?
