### ISSUE TITLE
Error Invalid arity: 0 shown in several cases

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2903]
### Description

*Type*: Bug

*Summary*: when I am switching between networks (RPCs) I can receive Error `Invalid arity:0 `.  This happens when I have more than 1 account on Ropsten for ex and then switch to Rinkeby and vise versa.

or

Error `Error invalid arity:0`  when try to recover access with valid passphrase and password. The same happens if to try to recover user with invalid passphrase/password.

or

Open Status (**## iOS**)
Login on a account witht transactions
Go in airplane mode
Open transaction details
#### Expected behavior
no errors

#### Actual behavior
Error `invalid arity: 0`

![image](https://user-images.githubusercontent.com/28752642/34561802-ce350fec-f15c-11e7-8cb3-9289ee19d5f5.png)

![image](https://user-images.githubusercontent.com/28752642/34719900-b863734e-f54d-11e7-89b6-fd7a6a223dd5.png)

### Reproduction 
- Open Status under Ropsten RPC
- Create account
- Click Switch users
- Create account
- Switch to Rikneby RPC

or 

- Open Status
- From login screen select 'Recover Access'
- Type random words in Passphrase (e.g. 'test lucky qwerty') and use any characters for password (e.g. 'qwerty')
- Submit this data

### Additional Information
* Status version: 0.9.11d512 (2069)
* Operating System: Android, iOS 
* Real device iPhone 7, Huawei P10 Lite, Android 7.0 Samsung, iPhone X

#### Logs
TF https://app.testfairy.com/projects/4803590-status/builds/7434230/sessions/13/?accessToken=5vuVl9Vx7W-Mz6lSOUJvQ60AgpA

TF https://app.testfairy.com/projects/4803622-status/builds/7430381/sessions/18/?accessToken=hMn-tl7TypdpSn/pKg/5MZ7CmwI

**Comment by oskarth** [comment]
@asemiankevich Can we only add PRs to the board? That way it is clear for devs what to REVIEW and MERGE, and we don't get duplicates. All PRs addressing issues should link to these in their PR summary.

**Comment by asemiankevich** [comment]
@oskarth yeah sure, sorry

**Comment by oskarth** [comment]
Blocked by this when testing https://github.com/status-im/status-react/issues/2920

**Comment by dmitryn** [comment]
Similar error `Error: invalid arity 0` happens if you have 2 accounts and try to visit sign in screen.
Cannot copy-paste stacktrace from ios simulator, but seems to be related to flat-list call from: `ui.screens.accounts.views.accounts`
  
<img width="528" alt="screenshot 2018-01-08 19 50 13" src="https://user-images.githubusercontent.com/23836/34681589-68205d84-f4ad-11e7-9db3-b61220f68c87.png">

**Comment by asemiankevich** [comment]
First 2 cases should be fixed by https://github.com/status-im/status-react/pull/2968 by Dmitry. Eric is working on this iOS issue.

**Comment by asemiankevich** [comment]
Reopened as there is one more PR coming to fix this completely
