### ISSUE TITLE
'Error invalid arity:0' appears on recover account with valid (or invalid) passphrase and password

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2904]
### Description

***Type***: Bug

***Summary***: Error `Error invalid arity:0` when try to recover access with valid passphrase and password. The same happens if to try to recover user with invalid passphrase/password.

#### Expected behavior
Account recovered and I'm able to log in.
#### Actual behavior
`Error invalid arity:0` error appears
![screenshot_20180104-134818](https://user-images.githubusercontent.com/8749671/34562301-5fb92810-f156-11e7-9f64-f80f0f20c262.png)

### Reproduction
TF session: https://app.testfairy.com/projects/4803622-status/builds/7430381/sessions/18/?accessToken=hMn-tl7TypdpSn/pKg/5MZ7CmwI

- Open Status
- From login screen select 'Recover Access'
- Type valid Passphrase (e.g this: 'because order okay foil swear slow resist brief boat eye enemy error') and valid password (for above passphrase - 'Aaaaaa')
- Submit this data

### Additional Information
* Status version: Develop build (0.9.10-512-gb42df648+)
[comment]: # (Android or iOS.)
* Operating System: Android 7.0 Samsung real device), iOS 11.1.2 (iPhone X)

**Comment by asemiankevich** [comment]
closing this one due to merge with https://github.com/status-im/status-react/issues/2903
