### ISSUE TITLE
New Profile screen tab

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2906]
### User Story

As a user I want to easily access my profile in a dedicated tab

### Description

*Type*: Feature

*Summary*: The new profile screen contains the following items:
- username 
- profile image
- main currency - hardcoded to USD and not selectable
- network settings
- log out

To be done in the scope of a separate issue:
- #3051 notification settings - to link to OS native notification settings screen for the app 

To be omitted:
- phone settings

https://zpl.io/VQo59qn

**Comment by oskarth** [comment]
Removing from Pipeline as we want PRs here, probably better to track issues in swarm boards like 61-app-structure.

**Comment by goranjovic** [comment]
gotcha

**Comment by denis-sharypin** [comment]
Hey @goranjovic or QA team if you need to check design files they are here:
https://zpl.io/2vyZWqJ

**Comment by denis-sharypin** [comment]
@goranjovic Hey, I found really small issues. It would be nice of you if you fix them. Thanks!

![slice](https://user-images.githubusercontent.com/6559881/35111256-20ad3104-fc7b-11e7-93c9-d35c484f122e.png)

**Comment by denis-sharypin** [comment]
And one more thing: could you update a button label style for Android? I made a mistake and used a wrong one. I made an update in the Zeplin prototype
<img width="425" alt="screenshot 2018-01-18 18 57 11" src="https://user-images.githubusercontent.com/6559881/35113358-722f114a-fc81-11e7-8159-1600343374d1.png">
