### ISSUE TITLE
0.00 ETH is shown instead of specified amount (with comma) on "Send transaction" screen after /send command

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2908]
### Description
*Type*: Bug

*Summary*: 
when you open chat and use /send command with some amount (with comma i.e. 0,001) , enter amount - Send transaction with 0.00ETH instead of specified amount
![oldamount](https://user-images.githubusercontent.com/4557972/34567518-47f1cccc-f16b-11e7-94fd-68a8d5498760.png)

#### Expected behavior
specified amount is shown

#### Actual behavior
0.00 ETH

### Reproduction

- Open Status
- Use /faucet in Console chat (in order to get some ETH). After balance is updated, go to next step.
- Start 1-1 chat
-Type /send 0,0001 (for example) 

### Additional Information

* Status version: 0.9.11d512 (nightly 04.01)
* Operating System: iOS, Android

#### Logs

TF 03:20 - 
https://app.testfairy.com/projects/4803590-status/builds/7434230/sessions/18/?accessToken=8cTDnCTUoalcGAMAiMTQNUx3xVY

**Comment by kylerchin** [comment]
Android too
