### ISSUE TITLE
Chat screen does not look like design

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#291]
<img width="851" alt="chat-screen" src="https://cloud.githubusercontent.com/assets/2714786/18943121/17f1dddc-8650-11e6-9a83-a81a6d146628.png">

- [ ] in many designs the top bar colour does not change with header, instead it is semi-transparent black, i saw @alwx do this correctly in past, we should make this uniform
- [x] dates and messages unread are missing? 
- [x] horizontal line seperator between chat sessions is missing
- [x] there should be grey empty area beneath end of chat screen if screen real estate is available

**Comment by alwx** [comment]
Finished.
Transparent StatusBar will be available later (I've submitted a PR to React Native with this fix: https://github.com/facebook/react-native/pull/10185)

**Comment by jarradh** [comment]
nice work committing upstream and getting accepted! woo!
