### ISSUE TITLE
Wrong icon shown for Android push notification

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#2912]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to know to that Status sent a push notification so that I can read unread messages.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: A square blank icon is shown instead of the Status logo icon for Android push notifications. This is a problem for users since they don't know the push notification originated from Status. 

#### Expected behavior

See the status logo icon for notifications

#### Actual behavior
[comment]: # (Describe what actually happened.)

See a blank icon for notifications.

<img width="391" alt="android_icon" src="https://user-images.githubusercontent.com/116099/34584407-a544f9e6-f169-11e7-8332-2899acde94f6.png">

<img width="393" alt="notifications" src="https://user-images.githubusercontent.com/116099/34584412-a91ece3e-f169-11e7-8bb7-fc19724e06e9.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Receive a push notification

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- Implement new b&w and color icons

### Additional Information

* Status version: 0.9.10-517-g5a582117+
* Operating System: Android 8.1.0
* Device: Pixel

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by asemiankevich** [comment]
![image](https://user-images.githubusercontent.com/28752642/34612828-67a24db8-f23c-11e7-9d46-27dbf8506034.png)

just to inform - it looks fine on Android 7

**Comment by denis-sharypin** [comment]
I created a notification/status bar icon. @asemiankevich  please assign to somebody who can upload it to the Android project
[ic_stat_status_android_8.zip](https://github.com/status-im/status-react/files/1607611/ic_stat_status_android_8.zip)

**Comment by asemiankevich** [comment]
@goranjovic @jeluard would mind to look into this?

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 350.00
Contract address: [0x7c3594a1f84bf47b929706fd0772e72b8aaabdd7](https://etherscan.io/address/0x7c3594a1f84bf47b929706fd0772e72b8aaabdd7)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by chadyj** [comment]
Potentially this solution could solve this issue https://stackoverflow.com/a/38000102
Denis made new transparent png files here https://github.com/status-im/status-react/issues/2912#issuecomment-355638548 ready to be dropped in. Hopefully that will fix it.

<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div><strong><a href="https://stackoverflow.com/questions/37997610/android-notification-icon-showing-as-white-block/38000102">android notification icon showing as white block</a></strong></div><div>I have been having trouble with a icon showing with my notification. I have gone trough the material designs page for icons and Notification doc.

I used different scales, in BMP 256 color format: ...</div></blockquote>

**Comment by enricrp8** [comment]
Still having the problem?

**Comment by chadyj** [comment]
@enricrp8 Yes. Thanks for taking a look.
