### ISSUE TITLE
Chat list rendering incorrectly when new chat appears

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#2914]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The recent move to `FlatList` introduced bug when chat list is not properly re-rendered for each item in data source.
Sometimes old data is used for the new item added to the list, or at least that's how it appears in UI.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on fresh devices A and B
- Observe that on device A, only console chat is present
- Create new 1-1 chat on device B by adding device A public key
- Observe that on device A, the new chat with device B appears,
but it's incorrectly rendered in the chat-list with icon & last message from console chat

**Comment by churik** [comment]
can be reproduced with any chat (1-1 Chat, Group chat)
Faced on IOS 11, IPhone 7

**Comment by annadanchenko** [comment]
Scenario 1 (as described in issue): device A (with wrong Console icon for chat with B): https://app.testfairy.com/projects/4803622-status/builds/7443571/sessions/140/?accessToken=ENMz5wtsxCPZxCHs08McI1jebL4 from 2:30
device B: https://app.testfairy.com/projects/4803590-status/builds/7452263/sessions/5/?accessToken=-CdWBt0sJh3sWKJU2vGiSGLcgFo

note on steps: you need to paste the key when adding a contact, not scan qr code

Scenario 2:

- Device B adds Device A to the contacts and send message "hi"
- Device A opens new chat with Device B, adds it to the Contacts and replies "hey"
- on Device A: return to Chats and open Console. In Console send faucet request and return to Chats screen. Note: now chat Console is on the top of the list and chat with B is second in the list
- As device B: send to A message "Now"
- on Device A observe Chats screen
Currently: 
![screenshot_20180107-232800](https://user-images.githubusercontent.com/6584810/34655005-d9d92280-f403-11e7-88d0-78ecbe8c48cf.png)


TF device A: https://app.testfairy.com/projects/4803622-status/builds/7443571/sessions/141/?accessToken=11qb4JFiol3/fKzvaBLX035m92E from 1:46

Nightly build for december 7
 0.9.10-523-gf90e1a4e+ (2080)
device A: Pixel XL, Android 8.1.0
device B: iPhone 7 plus, iOS 11.0.3

**Comment by oskarth** [comment]
Reopening until this has been put in release branch. In develop.

**Comment by oskarth** [comment]
Changes in develop re home tab that makes this brittle to merge; Jan will create separate PR with same diff targeting release branch.

**Comment by oskarth** [comment]
Cherry-picked https://github.com/status-im/status-react/pull/3018 that targets release branch into release. Closing.
