### ISSUE TITLE
[Perf] Experiment: spike out using many topics for chat

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2920]
Based on https://github.com/status-im/ideas/issues/55#issuecomment-355511183 findings

Trying naive things.

## Additional work

- [ ] Extend asym basic for spike: https://github.com/status-im/status-react/pull/2922#issuecomment-355561775
- [ ] Get status-go custom build with envelopes
- [ ] Validate open/recv envelopes differ with flag on and off, possibly with background noise (#status desktop chat)
- [ ] Assuming open envelopes drastically smaller for real world device, measure CPU and verify this etc (@divan can maybe help with this?)
- [ ] Possibly also fix symmetric key filters, e.g. by replacing with chat id or password (no coordination) if required for getting open envelopes on par of status-go perf benchmarks

- [ ] Later (only if we can verify above makes diff): Start to consider upgradability (talk from older version to new), path for breaking change

**Comment by yenda** [comment]
Closing since new protocol has been implemented with many topics
