### ISSUE TITLE
Implement sending / receiving STT (SNT) in chats

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2923]
### Description

*Type*: Bug

*Summary*: In terms of implementation of `ERC20` support we did not achieve the following:

1. Send command (no token support) (upgrade to API, support for deep linking), so we have disabled `send request` button when currency is set to STT due to this reason

2. Can't see the token history , this is the problem @goranjovic was trying to resolve however etherscan API blocks us to implement that. 

3. Request disabled for tokens (upgrade to API)

Those things above are 3 major things that were not achieved however the scope may be reduced as we may hide group chats for MVP ( I am still not sure about that).

**Comment by denis-sharypin** [comment]
Some small UI tweaks
![artboard](https://user-images.githubusercontent.com/6559881/34665623-42077cb4-f461-11e7-8c73-804baf68711f.jpg)

**Comment by asemiankevich** [comment]
closing this one as we have https://github.com/status-im/status-react/issues/3233 and separate issue for history https://github.com/status-im/status-react/issues/3976
