### ISSUE TITLE
Currency style is broken on wallet screen when sending funds in 1x1 chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2924]
### Description

*Type*: Bug

*Summary*: Asset indicator is black

#### Expected behavior
Currency should be white font matching other styles

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/34776855-53054e3c-f629-11e7-8d83-2547bc296f19.png)

### Reproduction

- Open Status
- Faucet some funds and call /send command in 1x1 chat
- Pay attention to wallet screen

### Additional Information

* Status version: latest develop 0.9.10-522-g0a1c3bcd+
* Operating System: Android, iOS

**Comment by dmitryn** [comment]
Going to merge it after https://github.com/status-im/status-react/pull/2973 will be merged (due to conflicts)

**Comment by oskarth** [comment]
@dmitryn Where is the PR for this? Can't see it

**Comment by dmitryn** [comment]
>@dmitryn Where is the PR for this? Can't see it

I was waiting for dependent PR #2973

**Comment by annadanchenko** [comment]
“Currency should be white font matching other styles” right? I still see black on iOS (if send from 1-1 chat) complete tf session from acc creation, see 02:19: https://app.testfairy.com/projects/4803590-status/builds/7470489/sessions/3/?accessToken=wTYIjyFBDkJCBpcUBtgpxj2Yziw or https://s3.amazonaws.com/testfairy/screenshots/4803590/7470489/89181943/87_cefbafeae52cd22f8a180c513719cf9766b2fcb3_o.jpg (84 kB)

**Comment by annadanchenko** [comment]
android is ok (tried 1-1, group chats and inititating tx from Dapp - all ETH are white)

**Comment by dmitryn** [comment]
@annadanchenko fixed that for ios too, let's wait for another build

**Comment by annadanchenko** [comment]
tested on build 4 for PR on iOs and Android:
1. send form 1-1 chat: see ETH white, can complete sending tx
2. send from group chat: see ETH white, cand complete sending
3. in Auction House Dapp: initiated transaction, see ETH white
4. In TX from unsigned: if Sign -> see ETH white
