### ISSUE TITLE
Error :No matching Clause (android) or Error: Invalid arity: 0 (IOS) at attempt to open transaction on unsigned screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2927]
### Description

*Type*: Bug
*Summary*: when you try to send some ETH from wallet and choose "Sign later", than you cannot sign transaction because of error
Android:
![unsigned](https://user-images.githubusercontent.com/4557972/34612480-b182c728-f232-11e7-9074-41175b8fb283.png)
IOS:
![unsignediphone](https://user-images.githubusercontent.com/4557972/34613098-3547e604-f235-11e7-934b-13cdf5b24935.png)

#### Expected behavior
can send transaction from "Unsigned transactions"

#### Actual behavior
Error: No matching clause :ETH

### Reproduction

- Open Status (user should have some amount of ETH, e.g. 0.1 )
- Sign in
- Tap on "Wallet"
- Tap on "Send"
- Choose recipient from contacts
- Enter some ETH amount (e.g. 0.00003)
- Tap on Sign Later
- Go  to Transactions -> Unsigned
- Tap on last transaction

### Additional Information

* Status version: nightly 0.9.10-520-gfa61ef8e+ (nightly 05/01/18)

* Operating System: Android, IOS

TF (from 00:20): https://app.testfairy.com/projects/4803622-status/builds/7435561/sessions/13/?accessToken=T1drzrybTp2L1QAa4-guQFJkCV8

**Comment by jeluard** [comment]
@churik Fixed by #2928
