### ISSUE TITLE
npm install mapbox step slow and unreliable

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2933]
### User Story

As a developer, I want fast builds so I can work more effectively.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature/Tooling

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Make mapbox install step faster/more reliable by for example vendoring dependency.

> npm install
> node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 3.3.1 [this step can take a long time / timeout]

#### Expected behavior
Fast and reliable builds.

#### Actual behavior
Not so fast builds and not always reliable.

### Reproduction

```
rm -rf node_modules
npm cache clear --force
rm -rf package-lock.json
rm -rf build
npm install
```

### Solution
*Summary*:  Consider vendoring. Or forking mapbox library and fixing their hacky install script.

**Comment by oskarth** [comment]
See https://github.com/mapbox/react-native-mapbox-gl/issues/916 for possible root cause

**Comment by oskarth** [comment]
See https://github.com/mapbox/react-native-mapbox-gl/issues/916 for possible root cause

**Comment by jeluard** [comment]
We don't use mapbox anymore.
