### ISSUE TITLE
Documentation for protocol namespace and function/defs for chat, listeners, group

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2934]
### User Story

As a developer, I want to have up to date documentation for core namespaces so I know what the code is supposed to be doing.

### Description

*Type*: Feature/Documentation

*Summary*: Write documentation for protocol/{chat,listeners,group}.cljs namespace and core functions/definitions.

#### Expected behavior
Documentation inline.

#### Actual behavior
No documentation.

### Notes

Inspiration: https://github.com/clojure/clojure/blob/master/src/clj/clojure/pprint.clj#L14-L36 https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj etc
 
Also see https://wiki.status.im/Whisper_Messaging for inspiration of what should be captured.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x15b4224e9f35a76c1b506eca2aa1756a57e0e75ae0c22a3ef676d4f59601ddc6](https://etherscan.io/tx/0x15b4224e9f35a76c1b506eca2aa1756a57e0e75ae0c22a3ef676d4f59601ddc6)

**Comment by pet3r-pan** [comment]
Still needed?

**Comment by yenda** [comment]
Hi @pet3r-pan , the protocol namespaces have been heavely refactored and are now better documented than before. But if you think you can improve the documentation further you are welcome to do so. We would increase the scope of the issue to the utils namespaces as well though.

**Comment by andytudhope** [comment]
@oskarth @yenda can we close here? Bounty has been revoked.
