### ISSUE TITLE
Uncomment and fix failing tests

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2935]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want tests to work so that I can verify modules work as expected.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature/Tests

*Summary*: Uncomment https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/test/runner.cljs tests, fix them and make sure it runs.

 ;;'status-im.test.contacts.events
 ;;'status-im.test.utils.pre-receiver

#### Expected behavior
Tests enabled and run.

#### Actual behavior
Not enabled.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 250.00
Contract address: [0xa7bcfcf1262ccff376930d3aef3c740a7b8fabf2](https://etherscan.io/address/0xa7bcfcf1262ccff376930d3aef3c740a7b8fabf2)
Network: Mainnet
Paid to: cammellos
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by Chumalaka** [comment]
Hi @oskarth, I can take care of this. :)
