### ISSUE TITLE
Status & Name, quick profile change in drawer

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#294]
![quick-profile-change](https://cloud.githubusercontent.com/assets/2714786/18943678/af090b48-8653-11e6-9e87-c0153fe5b998.gif)

- [x] Instead of having to go to the profile to change name and status, you should also be able to do it quickly within the drawer.
- [x] tapping on the icon should open up profile page

**Comment by rasom** [comment]
Seems that on iOS `status` input is not centered horizontally and has different value for `margin-top`:
 
![2016-10-05 09 17 08](https://cloud.githubusercontent.com/assets/2364994/19103007/dbe24340-8adc-11e6-8a69-6047415fe9c4.png)
