### ISSUE TITLE
No matching Clause (android) at attempt to open transaction 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2957]
### Description

*Type*: Bug

*Summary*: can't open transaction details no matter online or offline

#### Expected behavior
can view transaction details

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/34680769-fcb310ca-f4aa-11e7-8884-1e22874cd1a4.png)

### Reproduction

- Open Status
- Faucet some funds
- Open transaction details

### Additional Information
* Android: https://i.diawi.com/faqSde
* iOS: https://i.diawi.com/WJVhL3

**Comment by yenda** [comment]
@jeluard could it be because there is no default clause in your fix ?

**Comment by dmitryn** [comment]
Similar error `Error: invalid arity 0` happens if you have 2 accounts and try to visit sign in screen.
Cannot copy-paste stacktrace from ios simulator, but seems to be related to flat-list call from: `ui.screens.accounts.views.accounts`
