### ISSUE TITLE
Bug:Android:Not able to recover access (Invalid arity - Screenshot provided) 

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#2959]
### User Story
As a user, I wanted to recover access

### Description
*Type*: Bug

*Summary*: 
I forgot the password so I wanted to recover access. I entered the 12 words and double checked to make sure they were right, I entered a new password to the "password" textbox assming that's what it's asking (Which logically must be the case) after tapping the button, the following happened:
https://drive.google.com/file/d/19ha_DLNJE94QB9zp7Xelm-wvUEi6laRQ/view?usp=drivesdk
Then I exited the app to come back to a blank page, and reentering the app again I just saw the error again

#### Expected behavior
Described in the summary 

#### Actual behavior
Described in the summary

### Reproduction
Also described in the summary :D

- Open Status
- Forget the password :D
- Tap recover access
- Enter the phrases and the password 
- Tap on the button
- Voilà

### Solution
Um... 
### Additional Information
* Status version: 0.9.10-530-g266ffba9+
* Operating System: Android 8.0.0
Huawei Mate 10 (ALP-L29) if that helps
#### Logs
Sorry no root or adb shell :(

**Comment by asemiankevich** [comment]
Hi @RasaKh , thanks for report! We have already this documented - please see https://github.com/status-im/status-react/issues/2903
