### ISSUE TITLE
Beginning of chat

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#296]
Beginning of chat should have profile pic, and status at the top and messages aligning underneath the first date indicator.

<img width=370 src=https://cloud.githubusercontent.com/assets/2714786/18942011/5123375c-8648-11e6-8459-363a7b9cd222.png>

**Comment by alwx** [comment]
what do we need to display instead of status for group chats?

**Comment by jarradh** [comment]
I think @andmironov was suggesting having the first few chat members icons overlaid ontop of each other, the chat text underneath could be the names. I think thats probably too much effort for alpha so we can do group admin for now (and participants names up to 140 chars) or just nothing.

We can defer this to beta milestone

**Comment by yenda** [comment]
@andmironov @denis-sharypin can we close this ?

**Comment by denis-sharypin** [comment]
yes
