### ISSUE TITLE
[Perf] Test hypothesis 2: Many Whisper topics increase performance

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2964]
## Identified Behavior

@b00ris and @jeka found in simulation testing that CPU usage of status-go can be drastically reduced by moving from one to many Whisper topics.

No end user behavior has been identified yet.

- [x] Part of MVP scope
- [ ] Identified end user behavior

## Hypothesis

Changing from one topic to many topics to drastically decrease number of opened envelopes will lead to better perceived performance for end user.

## Assumptions

1) Assuming better status-go performance will lead to better user experience
2) Assuming simulation accurately reflects user behavior in real-world network
3) Assuming using many topics is feasible

## Experiment

- [ ] Spike out switch to using many topics on status-react side for 1on1 chat (started)
- [ ] status-go build that prints open envelopes
- [ ] Ad hoc way of simulating real network (e.g. #status and spam in Desktop concurrently)
- [ ] CPU metrics on two builds where open envelopes drastically differ
- [ ] Write up of feasibility of using many topics for group/public chats w/o coordination

## Acceptance criteria

- [ ] Real-world (status-react) observable difference in open envelopes
- [ ] Numbers on basic metrics like CPU that compares one vs many topics

## Notes

- One topic problem: https://github.com/status-im/ideas/issues/55#issuecomment-355511183

- PR https://github.com/status-im/status-react/pull/2922

- Part of https://github.com/status-im/ideas/issues/71

**Comment by oskarth** [comment]
@yenda do you want to own this?

@b00ris and @JekaMas can you please assist @yenda?

**Comment by oskarth** [comment]
If I understand things correctly, this https://github.com/ethereum/go-ethereum/pull/15811 needs to be in our status-go for our RPC filters to work. @b00ris can you confirm?

If so, is this available in status-go status-go repo so we can use this from status-react?

**Comment by b00ris** [comment]
@oskarth Yes, it's true. I try to push https://github.com/ethereum/go-ethereum/pull/15811 today.  
I think i could make separated branch with go-ethereum fix. 
@yenda @oskarth Yes, of course. How could we help you now?

**Comment by oskarth** [comment]
@yenda Are you still blocked by tooling for this?

**Comment by oskarth** [comment]
@yenda @b00ris @JekaMas  What's the state of this?

**Comment by yenda** [comment]
Closing since many topics has been implemented and network and bandwith consumption have greatly improved
