### ISSUE TITLE
[bash] make sure the merge-pr scripts prompt when there is multiple commits

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#2971]
### User Story

As a developper I want the merge-pr scripts in `status-react/scripts/merge-pr.sh`  to prompt for confirmation if the PR has more than 1 commit, so that we do not accidentally merge commits that should have been squashed beforehand
  
Reuse code in `status-react/scripts/merge-external-pr.sh` for that

**Comment by andytudhope** [comment]
@yenda I am pretty sure the `merge-external-pr.sh` script does this already? https://github.com/status-im/status-react/blob/develop/scripts/merge-external-pr.sh#L93
