### ISSUE TITLE
Error "Doesn't support name" shown if send ETH in 1-1 chat [2915]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2972]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In PR build for #2915: If use send command in 1-1 chat then error is shown and if close it then white screen, so need to relaunch app. Error:
```
Error: Doesn't support name: 

This error is located at:
    in view-currency
    in reagent147
    in RCTView
    in RCTView
    in RCTView
    in RCTView
    in RCTScrollView
    in ScrollView
    in RCTView
    in RCTView
    in reagent141
    in reagent140
    in send-transaction-modal
    in reagent139
    in RCTView
    in RCTModalHostView
    in t
    in RCTView
    in RCTView
    in RCTView
    in RCTView
    in n
    in main
    in root
    in reagent1
    in RCTView
    in RCTView
    in t

name@index.android.bundle:12:679439
index.android.bundle:12:7583058
index.android.bundle:12:4493507
wrap_render@index.android.bundle:12:4494164
do_render@index.android.bundle:12:4495360
index.android.bundle:12:4496410
in_context@index.android.bundle:12:4456638
deref_capture@index.android.bundle:12:4456827
run_in_reaction@index.android.bundle:12:4486443
index.android.bundle:12:4496337
l@index.android.bundle:49:70939
index.android.bundle:49:72624
beginWork@index.android.bundle:49:72635
u@index.android.bundle:49:99536
f@index.android.bundle:49:100152
p@index.android.bundle:49:101226
m@index.android.bundle:49:103204
y@index.android.bundle:49:102584
enqueueForceUpdate@index.android.bundle:49:64799
forceUpdate@index.android.bundle:15:2587
run_queue@index.android.bundle:12:4452177
flush_queues@index.android.bundle:12:4453449
run_queues@index.android.bundle:12:4453596
index.android.bundle:12:4453025
index.android.bundle:32:1346
a@index.android.bundle:32:506
callTimers@index.android.bundle:32:2765
value@index.android.bundle:27:3177
index.android.bundle:27:911
value@index.android.bundle:27:2606
value@index.android.bundle:27:883
[native code]
```

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Send transaction screen is shown where user can type a password to send tx
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
TF: https://app.testfairy.com/projects/4803622-status/builds/7462683/sessions/20/?accessToken=COrqqlndflJGgV23-O6NrRfajwk
- Open Status
- Open 1-1 chat
- Send 0.0001

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  6092ecfc+ (2074)
PR build 5 for 2915
* Operating System: Android and iOS
Real devices Android 6.0.1 Galaxy S6, Iphone 7 plus, iOS 11.0.3

**Comment by asemiankevich** [comment]
just FYI @annadanchenko @janherich i dont see this in latest develop 

Branch: status-im:develop
Android: https://i.diawi.com/U2MSdm
iOS: https://i.diawi.com/2MsZf8

**Comment by janherich** [comment]
I'm not able to simulate the issue on this branch, tested on iOS simulator, `/send` command in 1-1 chat works fine
There is one thing which is wrong though, and that's this warning when trying to send something:
![screen shot 2018-01-10 at 14 27 00](https://user-images.githubusercontent.com/1910609/34775199-89814928-f612-11e7-97d5-178a9253c23a.png)
But that's not related to this PR.
