### ISSUE TITLE
Currency selector is broken [iOS]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2974]
### Description

*Type*: Bug

*Summary*: in iOS currency selector is broken 

#### Expected behavior

UI looks good

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/34729611-3d726ffc-f56e-11e7-88c7-ddb43522e794.png)

### Reproduction

- Open Status
- Go to Wallet
- Tap Send
- Pay attention to currency selector

### Additional Information
* Status version: latest develop
* Operating System: iOS

**Comment by oskarth** [comment]
Closing this as it has been fixed in PR above.
