### ISSUE TITLE
Advanced button is broken (iOS)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2975]
### Description

*Type*: Bug

*Summary*: fix Advanced button styling and appearance on iOS

#### Expected behavior
no broken styles

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/34730025-4dd583a6-f56f-11e7-9722-11bb9e99ffbf.png)

### Reproduction

- Open Status
- Go to wallet
- tap send 
- pay attention to advanced button

### Additional Information
* Status version: latest develop
* Operating System: iOS

**Comment by oskarth** [comment]
Closing this as it has been merged into release branch. @asemiankevich re-open if you feel this is in error.
