### ISSUE TITLE
Chat input has 2 lines when a long url is used in the browse command  

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2977]
### Description

*Type*: Bug

*Summary*: Chat input seems to be showing an empty line when a long url is used in the browse command.

#### Expected behavior
Long url should be truncated and displayed in one line.

#### Actual behavior
Input shows 2 lines:

![pasted graphic 1-kopia](https://user-images.githubusercontent.com/7532782/34741962-d2a6cecc-f584-11e7-96a5-3198b318095e.png)

### Reproduction

- Open Status
- Go to Chats
- Open a chat that has browse command available
- Select browse command and paste a long url

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Tested on: iPhone 6, iOS 11.2.1

**Comment by annadanchenko** [comment]
no browse command anymore
