### ISSUE TITLE
No explanation in iOS Settings why Status needs location access

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2978]
### Description

*Type*: Bug

*Summary*: There is no explanation in iOS Settings why Status app needs a location access. The explanation maybe necessary before submitting the app to AppStore. It also builds confidence. 
Here is a Chrome app example: "Get a better experience in Chrome based on your location."

#### Expected behavior
There is an "App explanation" in Location Settings. 

#### Actual behavior
"App explanation" is empty:

![image](https://user-images.githubusercontent.com/7532782/34742178-98ef848e-f585-11e7-9fc6-0be7721ce6d1.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Settings app on iOS 
- Find Status app and open it
- Go to Location options

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Operating System: iOS 11.2.1

**Comment by annadanchenko** [comment]
Location command is removed
