### ISSUE TITLE
Allow to open a location in Google Maps iOS app

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2979]
### User Story

As a user, I want to open a location in Google Maps iOS app because I don't use the native Maps app.

### Description

*Type*: Feature

*Summary*: Currently there is no option to open a location in Google Maps app. "Open Map" option redirects to native iOS Maps app or asks to install Maps app in case it's not installed. Since Google Maps are quite popular it's maybe worth to support it.

#### Expected behavior
Allow to open location in Google Maps in addition to Maps app.

#### Actual behavior
Location can be only seen in Maps app.

### Reproduction

- Open Status
- Go to a chat
- Send a location 
- Long press on the location
- There is no option to open the location in Google Maps 

### Solution
When "Open Map" is clicked for the first time, there maybe a dialog asking which app to use.

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Tested on: iPhone 6, iOS 11.2.1

**Comment by annadanchenko** [comment]
Location command is removed
