### ISSUE TITLE
Map image in a location message is blurred

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2980]
### Description

*Type*: Bug

*Summary*: Quality of a map image in the  location message is poor. Map seems to be blurred. I'd expect the same quality as in Send Location picker:

![image](https://user-images.githubusercontent.com/7532782/34743634-aaeb28b4-f58a-11e7-8295-948b24388dbe.png)

![image](https://user-images.githubusercontent.com/7532782/34743666-d5efb25a-f58a-11e7-81eb-fffab0e8d155.png)

#### Expected behavior
Sharp map image in location messages. 

#### Actual behavior
Map image is blurred.

### Reproduction

- Open Status
- Go to Chats
- Open a chat 
- Send or receive a location message

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Operating System: iOS
* Tested on: iPhone 6, iOS 11.2.1

**Comment by annadanchenko** [comment]
Location command is removed
