### ISSUE TITLE
Long address overlaps next chat when that chat is clicked (Chats tab)

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2981]
### Description

*Type*: Bug

*Summary*: When the last message in a chat contains a long address it overlaps the next chat when that chat is clicked: 

![image](https://user-images.githubusercontent.com/7532782/34744396-594fb530-f58d-11e7-9b81-8f7e890c2506.png)

In this example the overlapping text appears only while clicking "Console" chat.
  

#### Expected behavior
First chat should not overlap the next one. 

#### Actual behavior
If a first chat contains a long message it overlaps the next one when that chat is clicked. 

### Reproduction

- Open Status
- Open Chats tab
- Open first chat and send a long location message
- Go back to Chats
- Long click on the second chat. It should be overlapped by the first chat as shown in the screenshot.

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Operating System: iOS
* Tested on: iPhone 6, iOS 11.2.1
* Related to: https://github.com/status-im/status-react/issues/1436

**Comment by annadanchenko** [comment]
same as #1436 
It exists in 0.9.12 from testFlight and already fixed for next 0.9.13 release
