### ISSUE TITLE
"Invalid arity: 0" error if open transaction history on iOS [release]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2982]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Only on release build (ok in develop), so maybe some commit is not included? if open transaction history then error "Invalid arity: 0" is shown. IF close it then white screen is shown instead of Wallet
![img_1943](https://user-images.githubusercontent.com/6584810/34744823-c6bd01b2-f58e-11e7-9b84-a798a6b7e8ec.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Transaction history screen is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
error "Invalid arity: 0" 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
tf: https://app.testfairy.com/projects/4803590-status/builds/7463701/sessions/4/?accessToken=nNDsguyRwKPCFqxWaf0eTC0JLFg
- Open Status
- Open Wallet
- Open Transaction history

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  0.9.11d538
Release build from Jan 9, 18:03 (from slack)
Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-bb35e4.apk
iOS: https://i.diawi.com/M8qnkF

Develop build where it works fine: 
Branch: status-im:develop Jan 9, 18:55 (from slack)
Android: https://i.diawi.com/U2MSdm
iOS: https://i.diawi.com/2MsZf8

* Operating System: only iOS

**Comment by yenda** [comment]
@annadanchenko can you recheck the release now that this commit that was fixing it in develop has been cherry picked into the release ? https://github.com/status-im/status-react/pull/2919/commits/b1baa8e906662303fe1bc31fdc57b125ebfdc331

**Comment by annadanchenko** [comment]
@yenda yes, now can't reproduce it on release build, so closing the issue
