### ISSUE TITLE
Send transaction screen is scrolled so that it does not show recipient or amount fields

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2983]
### Description

*Type*: Bug

*Summary*: Sometimes when "Send transaction" screen is opened it does not show recipient, wallet or amount fields. It looks like the screen is being scrolled when the keyboard appears. The screen can be fixed by scrolling it a little bit in any direction.

![image](https://user-images.githubusercontent.com/7532782/34745095-aca01eb2-f58f-11e7-94ae-28b1d6e6c3c1.png)

Or sometimes:

![image](https://user-images.githubusercontent.com/7532782/34745434-cdbdf41a-f590-11e7-866c-66f3c229dfef.png)

#### Expected behavior
Showing keyboard should not break the scroll in "Send transaction" screen. 

#### Actual behavior
Sometimes when keyboard is shown the screen is scrolled and does not show all fields.

### Reproduction

- Kill Status app
- Open Status
- Go to Wallet
- Click Send

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Operating System: iOS
* Tested on: iPhone 6, iOS 11.2.1
* Can be reproduced 5/7 times. Especially when the app is killed and opened again.

**Comment by asemiankevich** [comment]
@lukaszfryc is it still in place?

**Comment by lukaszfryc** [comment]
I haven't seen it for a while. It needs to be retested.

**Comment by lukaszfryc** [comment]
I could not reproduce it on latest nightly
