### ISSUE TITLE
Incoming message notification is shown even though user has logged to a different account 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2984]
### Description

*Type*: Bug

*Summary*: When user logs out she still receives notifications about incoming chat messages. It happens even after the user has logged in to a different account. 

#### Expected behavior
User that has logged out should not receive any notifications.

#### Actual behavior
Incoming message notifications are shown even though user is logged out. It happens even after the user has logged in to a different account. 

### Reproduction

- Open Status on 2 devices: A and B
- Device A and B should be contacts in Status
- Device A: Open a chat with B and send a messae
- Device B: Open the chat with A
- Device A: Go to Switch User to log out
- Device A: Lock the device screen
- Device B: Send a message to A. Device A receives a "Status - new message" notification with "ping" content even though the user was logged out
- Device A: Log in as different user
- Device B: Send a message to A. Device A still receives notifications. 
 
### Additional Information
* Status version: 0.9.12 (TestFlight)
* Operating System: iOS
* Tested on: iPhone 6, iOS 11.2.1

**Comment by lukaszfryc** [comment]
If it's really a bug, it should probably be resolved as part of https://github.com/status-im/ideas/issues/86

**Comment by lukaszfryc** [comment]
Still valid

**Comment by t1MZXxBn6pAAtTqKTy5UotdeMqBw2CfGrUF** [comment]
I hope this issue is resolved.

**Comment by t1MZXxBn6pAAtTqKTy5UotdeMqBw2CfGrUF** [comment]
I hope this issue is resolved.

**Comment by pedropombeiro** [comment]
This should be resolved in the context of https://github.com/status-im/status-react/issues/3451

**Comment by lukaszfryc** [comment]
FYI: It still happens on latest nightly.

**Comment by pedropombeiro** [comment]
Looks like we'll need to implement https://github.com/status-im/status-react/issues/3451 in order to properly address this.

**Comment by lukaszfryc** [comment]
FYI: I tested latest nightly (Aug 31) and the isssue is still there.

**Comment by lukaszfryc** [comment]
@PombeirP are you going to work on it?

**Comment by pedropombeiro** [comment]
It would probably be better to have one of the Clojure devs look into how we'd be able to know the last logged-in account so we can test for that in the background service (since from the background service we don't necessarily have access to the realm db). If it's a question of saving a separate file from the main app and reading it from this bg service, that would be something I can tackle. Otherwise, it'd need to be someone who thoroughly knows the code. cc @rasom.

**Comment by pedropombeiro** [comment]
@lukaszfryc with https://github.com/status-im/status-react/pull/6893, this will only happen if the app is not running, or running in the background. So we'll need to adapt the description of this GHI once that PR is merged.

**Comment by pedropombeiro** [comment]
@asemiankevich we should see if we can close this due to #7268, it should fix it.

**Comment by churik** [comment]
I'll check it in nightly, but I can say that it was fixed in PR
