### ISSUE TITLE
Transaction is not immediately visible in Transactions History

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#2985]
### Description

*Type*: Bug

*Summary*: When a user sends ETH and then goes to Transactions History the transaction is not visible there. User needs to wait until the transaction has at least couple of confirmations to see it in history. Not seeing the transaction immediately may lead him to think that something went wrong.  

#### Expected behavior
Transaction that was sent is immediately visible in Transactions History. Or, at least there is an indicator that transaction is being processed.

#### Actual behavior
Transaction becomes visible after couple of confirmations.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Wallet 
- Send a transaction and go to Transactions History

### Additional Information
* Status version: 0.9.12 (TestFlight)
* Operating System: iOS
* Tested on: iPhone 6, iOS 11.2.1

**Comment by annadanchenko** [comment]
we need to show pending transactions in history. Is it a good candidate for bug fixing day @goranjovic @jeluard ?
