### ISSUE TITLE
Improve screen navigation

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2987]
### User Story

As a developer, I want to easily pass arguments to screens I navigate to.

### Description

Our current navigation logic involves [defining](https://github.com/status-im/status-react/blob/7c4d2f2ece00838cf458e661daa468587efe533d/src/status_im/ui/screens/views.cljs#L116) a screen by a key, [dispatching](https://github.com/status-im/status-react/blob/7c8aa7572400f1e6e200511795d11ff351d07e78/src/status_im/ui/screens/network_settings/views.cljs#L48) to this key with eventual parameters and providing a separate preload [hook](https://github.com/status-im/status-react/blob/cf7a9845c6083b8c621a20187f2ed82ee6fe3a1e/src/status_im/ui/screens/network_settings/navigation.cljs#L4) that will be able to modify the `app-db` before the [view](https://github.com/status-im/status-react/blob/1657f189ba6874b547860b5d254cb2fe070c6373/src/status_im/ui/screens/network_settings/network_details/views.cljs#L24) is shown.

This is cumbersome - I want to have my view directly receive the dispatched parameters as arguments.

The proposed solution is to use a generic navigation event that takes optional parameters, stores them in a special placeholder in app-db specific for that view. Views can then use a subscription to get the passed parameters.

E.g.

```clojure
;; The generic navigate event with optional params
;; we call it the same way as regular :navigate-to except
;; we also give it one extra parameter - typically a map of params
;; It puts the params in app-db, namespaced per view-id
(handlers/register-handler-fx
  :navigate-to
  (fn [{:keys [db]} [_ view-id params]]
    (-> db
        (assoc-in [:screen-params view-id] params)
        (status-im.ui.screens.navigation/navigate-to view-id)))

;; Then we have one almost generic subscription that extracts the params for us.
;; Note that if we could only be sure that only current view is being rendered, 
;; we could remove the view-id param and just use the value of the currently 
;; shown view, i.e. (:view-id db)
(reg-sub :view-params
  (fn [db [_ view-id]]
    (get-in db [:screen-params view-id])))

;; Finally in the view, use the subscription to get the value of params.
;; This method requires knowledge of the view-id for the current view. 
;; It shouldn't be too much of a hassle if we stick the the convention of 
;; using the same name for the view var and the navigation keyword.
;;
;; Again, if we can ensure that only the current view is being rendered, 
;; we can remove the parameter altogether.
(defview some-view
   (letsubs [the-params-we-want [:view-params :some-view]]
     ;markup markup
        ))

```
https://gist.github.com/goranjovic/e68e85fde88aa7d3a3fe38cdcb07991b

Since, the outlined solution depends on the convention to use the same name for view var and navigation keyword, any refactoring to make that so retroactively is within the scope of this issue.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 520.00
Contract address: [0xf7c1fbf14c86044f3b557c1dcf7b2d4022f214cc](https://etherscan.io/address/0xf7c1fbf14c86044f3b557c1dcf7b2d4022f214cc)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
