### ISSUE TITLE
Counter of unread messages shows amount for already read messages [2915]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2991]
### Description

*Type*: Bug
*Summary*: 
- in console chat: counter of unread messages shows 2 unread messages when you open "Chats" after setting app password; after receiving faucet request shows 1 unread message; 

- in 1-1, Group Chat: when you go back after receiving /send command or text message, you also see unread message.

#### Expected behavior
no new mesaages

#### Actual behavior
scenario 1: 2 unread messages
scenarion 2: 
1 unread message (User A)
1 unread message (User B)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Scenario 1:
- Open Status
- Set up password
- Go back to "Chats" screen

Scenario 2:
- Go 1-1 chat (User A)
- Open chat with User B (user A)
- send  0.0001 (via /send command) or text message (User B)
- wait for receive  /send command or text message (user A)
-  Go back to "Chats" screen  (user A)
-  Go back to "Chats" screen  (user B)
### Additional Information

* Status version: 4d975fcd+ (2095) PR-2915
* Operating System: Android, iOS

TF (scenario 1 - 00:11  to 00:30): https://app.testfairy.com/projects/4803590-status/builds/7469503/sessions/7/?accessToken=kEK/fFhV6V1A5tsSQfLJphCIMuI

TF (scenario 2 - 11:00  to 11:30): https://app.testfairy.com/projects/4803622-status/builds/7469498/sessions/13/?accessToken=fJWNPkFLk-wyx-GTs071S4DxmTM

**Comment by janherich** [comment]
@churik I'm unable to simulate the scenario with unread messages counter when sending/receiving. Maybe the build you are using for testing is outdated and doesn't include the unread counter fix already merged in develop, I will trigger a new build to be sure.

**Comment by annadanchenko** [comment]
Updated bug description, same comment is in PR https://github.com/status-im/status-react/pull/2988#issuecomment-356640505

@janherich took latest PR build (created on 20:21 today)
can reproduce issues with send and it's more wide: even if text message is sent when i'm in chat then unread counter shows 1 if go back to Chats

1st run: android receiver, when 1st message is received and i’m in chat -> went to Chats, no unread counter (ok) then go back to Chat, second message received, go back to Chats - unread counter shows 1 (not OK)
Android receiver:
from 1:19 https://app.testfairy.com/projects/4803622-status/builds/7470566/sessions/1/?accessToken=9wI6B0cYS8H/J4soAUucf0mTDuU

2nd run same device, i'm in chat, got 1 message and see it, wait, go back to Chats -> 1 unread message (not Ok) 00:34: https://app.testfairy.com/projects/4803622-status/builds/7470566/sessions/3/?accessToken=7r2uogipnZNWXraet-HrBOmPH4Y

**Comment by oskarth** [comment]
@janherich @annadanchenko can we close this one after https://github.com/status-im/status-react/pull/2915 or no?
