### ISSUE TITLE
Remove ERC20_ENABLED flag

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3001]
### User Story

As a developer, I want to have a clean codebase

### Description

ERC20 support has now be finalized and enabled. `ERC20_ENABLED` flag is now useless

*Type*: Feature

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 160.00
Contract address: [0x1017e2c08ff5eeb78f5a93e3e03fe9d5824b83bb](https://etherscan.io/address/0x1017e2c08ff5eeb78f5a93e3e03fe9d5824b83bb)
Network: Mainnet
Paid to: cammellos
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
