### ISSUE TITLE
Add media API support for DApps

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3003]
### User Story

As a developper, I want to be able to leverage all web technologies in my DApp.

### Description

Some web API usages require user permission (usually some popup a user has to confirm).
Those API should be available to DApps authors.

As we already asks specific user permission (e.g. camera) it would be great to reuse those and not asks for already granted permission.

At least media permissions should be working and the following site should be usable: https://davidwalsh.name/demo/camera.php

*Type*: Feature

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 520.00
Contract address: [0x8074a5d6e8008296ec83ced284e1917a05626f88](https://etherscan.io/address/0x8074a5d6e8008296ec83ced284e1917a05626f88)
Network: Mainnet
Paid to: rasom
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by nrakochy** [comment]
It looks like this feature probably needs to be added to the [WebChromeClient](https://developer.android.com/reference/android/webkit/WebChromeClient.html), which is part of the [React Native Webview Bridge](https://github.com/alinz/react-native-webview-bridge) module. 

However, [React Native Webview Bridge](https://github.com/alinz/react-native-webview-bridge) has not accepted a PR in over a year, so I am not sure if that is the best direction. 

The other option would be to migrate to [react-native webviews](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L360) and open a PR to get more permission handling on the WebView there. 

I am not sure if `status` uses the `RPC` functionality that the `Webview Bridge` provides?
Thoughts?

**Comment by jeluard** [comment]
@nrakochy We do have our own [fork](https://github.com/status-im/react-native-webview-bridge/) for `react-native-webview-bridge` so you can make changes here.

Moving to the bundled webview support is definitively on our radar. We have some hacks currently in the webview support so probably not straightforward but worth considering. I will open a dedicated issue to track that.

**Comment by jeluard** [comment]
@nrakochy I just created a new issue (#3046) for the webview migration. In case you continue enjoying hacking on status ;) (probably longer term so this issue still applies)
