### ISSUE TITLE
Rework chat UI

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3009]
### User Story

As a user, I want a clean chat experience.

### Description

Find mockup details [here](https://projects.invisionapp.com/share/KXEWN9XHM#/screens/268975254)

e.g. 

![selection_021](https://user-images.githubusercontent.com/711764/35666926-25c1b24e-072c-11e8-98b4-5bc4a86997f1.png)

![selection_022](https://user-images.githubusercontent.com/711764/35666933-2912b24a-072c-11e8-81fc-777d4faecf6a.png)

This issue does not include chat details screen.

*Type*: Feature

**Comment by denis-sharypin** [comment]
Couple moe things:
1. The second line in the navigation bar should be also aligned to the left. Also, mind the gap between
userpick and name.

2. Message states (Sent, Delivered, Sending…) should have a bit different design. Sorry, we didn't introduce them into Zeplin mocks. It has a text style as names except for color. Keep current color for it 


![slice](https://user-images.githubusercontent.com/6559881/36157835-04e06af8-10db-11e8-8dcd-d17cf05a1078.png)
