### ISSUE TITLE
Chat swipe based deletion

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3013]
### User Story

As a user, I want to delete chats 

### Description

A deleted chat will not appear in the Home tab list anymore.

Find mockup details [here](https://projects.invisionapp.com/share/KXEWN9XHM#/screens/272559937)

*Type*: Feature

**Comment by denis-sharypin** [comment]
Hey! To be more precise there are mockups for iOS and Android and [an SVG icon of a trash bin](https://www.dropbox.com/s/gz3jytu9ftoun39/icon_delete-red.svg?dl=0). 
![swipe to delete](https://user-images.githubusercontent.com/6559881/34942683-d6539c94-f9f8-11e7-902b-38eeb8cefa3a.jpg)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x0c3dbe8c9f53aa9e27f80fc77c531b231e11b1ad](https://etherscan.io/address/0x0c3dbe8c9f53aa9e27f80fc77c531b231e11b1ad)
Network: Mainnet
Paid to: hanwencheng
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by bryanlynn8** [comment]
I can code this out, let me know.

**Comment by pablanopete** [comment]
@kingbean no need to ask! Pull requests are encouraged on bounties issues

**Comment by hanwencheng** [comment]
working on it, will send the PR soon.

**Comment by jeluard** [comment]
@hanwencheng Would you mind sharing a screenshot of the existing implementation?

**Comment by hanwencheng** [comment]
Sure, here you go, on iphone 6
![simulator screen shot - iphone 7 - 2018-02-06 at 22 00 15](https://user-images.githubusercontent.com/6014309/35883888-2674a80c-0b89-11e8-842e-1bcbf5f8f5a7.png)

**Comment by flexsurfer** [comment]
PR has been reverted, new PR with fixes is required

**Comment by asemiankevich** [comment]
@hanwencheng pelase see the comment above

**Comment by chadyj** [comment]
Hey @hanwencheng is there any chance you could take another look at this? We'd love to have it in the next release. If you need any help or other assistance please let me know.
