### ISSUE TITLE
Default gas price is different for send command from 1-1 Chat and wallet screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#3021]
### Description
*Type*: Bug
*Summary*: default gas price is different, when you go to "Send transaction" screen via /send command from chat with default fee OR when you go to "Send transaction" screen via "Send" from wallet, so seems that gas limit / gas price is calculated in different way.
![gasprice](https://user-images.githubusercontent.com/4557972/34883373-24cfc7d2-f7c2-11e7-8ce0-b19a47d5ba22.png)

#### Expected behavior
default gas price is the same

#### Actual behavior
default gas price is different (20 GWEI / 21 GWEI)

### Reproduction

Prerequisites: user has 0.1 ETH on balance and 1-1 chat

1) 
- Open Status
- Log in
- Go to 1-1 chat
- Tap on /send 
- Enter 0.003
- Tap on blue button to send command
- Tap on "Advanced". Check out Gas Price (can be 40 GWei, 20 Gwei)

2) 
- Open Status
- Log in
- Go to Wallet
- Tap on "send"
- Choose any contact
- Enter 0.003
- Tap on "Advanced". Check out Gas Price (21 Gwei)

### Additional Information
* Status version: 
* Operating System: Android, iOS

**Comment by jeluard** [comment]
@goranjovic Do we still have this issue?

**Comment by goranjovic** [comment]
@jeluard I think so, the difference is that Wallet gas price is hardcoded

**Comment by goranjovic** [comment]
Related to #3288

**Comment by asemiankevich** [comment]
i think we can close it, @jeluard ? i can't repro it anymore

**Comment by jeluard** [comment]
@asemiankevich Please!
