### ISSUE TITLE
Unable to access the profile section for a user

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#3028]
### User Story

As a user, I want to be view the profile section so that I can remove a contact.

### Description

*Type*: Bug

I was trying to replicate issue #2960 , but it would throw an error every time I tried to access that panel, seems like a needed icon ( icons/chats) has been removed.

#### Expected behavior

I am able to access the view profile section

#### Actual behavior

An error is thrown.

### Reproduction

- Open Status
- Login with username/password
- Click on any user (Jarrad)
- Click on their profile picture
- Click on Profile

### Solution

I have added back the icons/chats icon and the section seems to be loading ok.

### Additional Information

* Status version: develop
* Operating System: Android

**Comment by goranjovic** [comment]
Good catch!
