### ISSUE TITLE
Blockly GUI Re-skin

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#304]
We'd like to start thinking of how Status users can program smart contracts on smartphones, coding directly in solidity is out of the question but a intuitive "lego-like" blocks that you can snap together to produce smart contracts would be a fantastic start.

The Google Blockly GUI seems like a great candidate but the GUI looks a little .. dated. 
It would be great if we could reskin/reimagine what this would look like, in the Status look-and-feel.

An example of such an effort can be found here
http://etherscripter.com/

Our version should behave very similar to how Etherscripter does in terms of snapping on inputs and outputs, expanding their sizes to fit.

Pinch in/out to zoom in and out of the designer space
Touch off blocks to pan around designer space

An example would be creating a multi-sig wallet or creating an escrow contract. Creating their own custom commands/requests inside Status.

**Comment by andmironov** [comment]
Hello, Jarrad! i had been sketching a little on the weekend and here's what i came up with.
What i thing about this thing is that it looks viable but it has to be done really good in terms of technical implementation and UX. I mean it should zoom in and out automatically in the right moment, auto-scroll left and right when drag and drop, and much more UX stuff we have to test and research and update and so on. 

It feels like for this UI there's a tiny step between the "wow, it's nice" and "why the hell should i use this, i'd better write code"

![ios_blocky](https://cloud.githubusercontent.com/assets/3115606/19232894/175d7388-8eeb-11e6-883d-fa6a1d3fef0c.png)

**Comment by jarradh** [comment]
great start thanks! Yes this is definitely going to take alot of time and thought. 
Any time we ask the user to use the keyboard we really need to think how we can do it better. (the note being an exception)

I'll think about this more over the coming weeks and this definitely gives something for my brain to sink it's teeth into!

**Comment by status-sync** [comment]
➤ Sync Bot commented:
Ignore (Asana Sync Test)
