### ISSUE TITLE
Improve svg color handling

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3041]
### User Story

As a developer, I want to easily manipulate `svg` fragments color at run time.

### Description

*Type*: Feature

`svg` colors are handled at startup time were a color argument can be provided per icon instance that will be used to replace all `svg` `prefill`s attribute.
This prevent having `svg` with colors for only parts of the design and is inherently static. Find a way to fix both limitations.

References:
* [slurp-svg](https://github.com/status-im/status-react/blob/develop/src/status_im/utils/slurp.clj#L20)
* [icons](https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/icons/vector_icons.cljs#L28)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x80d641904f488877e73db9ef37bb6ed747fda617e71ce60d7987909b9eed5c04](https://etherscan.io/tx/0x80d641904f488877e73db9ef37bb6ed747fda617e71ce60d7987909b9eed5c04)

**Comment by joedooley** [comment]
Seems like a good first issue. Mind if a give it a go? Thanks

**Comment by andytudhope** [comment]
Yeah absolutely @joedooley!! Looking forward to that PR 🎉
