### ISSUE TITLE
Implement webview using react-native features

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3046]
### User Story

As a developer, I want to use supported libraries

### Description

*Type*: Feature

Our webview support currently relies on an [unsupported library](https://github.com/alinz/react-native-webview-bridge). 
Migrate to the native react-native [webview support](https://facebook.github.io/react-native/docs/webview.html).

Note that our [fork](https://github.com/status-im/react-native-webview-bridge) contains a number of hooks and hacks which have to be considered.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x73f57b290dfc6a1d6035950ed7ce00307e18ca6f455823e50045bb04d5acce83](https://etherscan.io/tx/0x73f57b290dfc6a1d6035950ed7ce00307e18ca6f455823e50045bb04d5acce83)

**Comment by andytudhope** [comment]
@jeluard is this issue still relevant or can we close?

**Comment by jeluard** [comment]
You ca close it yes!
