### ISSUE TITLE
Migrate EIP681 to latest draft

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3047]
### Description

*Type*: Feature

Some recent changes have been published to https://github.com/ethereum/EIPs/pull/681:
* https://github.com/ethereum/EIPs/pull/681/commits/b5444e4c94d0d402ae6b4d1de42652a861e36f39
* https://github.com/ethereum/EIPs/pull/681/commits/f4ba09d033f7ea3f08b96922be0f8e1ae90971f9
* https://github.com/ethereum/EIPs/pull/831/files

Update our implementation to reflect those.

**Comment by ligi** [comment]
might be bundled with another change that seems to come as @pirapira found a flaw in the current spec https://github.com/ethereum/EIPs/pull/831#discussion_r161771262 - the issue was found via 861 - but the same problem is in 681
