### ISSUE TITLE
No messages received (1x1 or group chat) on some devices

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3049]
### Description

*Type*: Bug

*Summary*: No messaging apperas on some devices. I have this problem with Huawei and @flexsurfer with his Xiaomi. List will be updated

#### Expected behavior
user can chat no matter which device is used

#### Actual behavior
can't chat chat using:

- iPhone 5S
- Xiaomi Redmi Note 4
- Xiaomi Redmi 3
- Huawei P10 Lite

### Additional Information
* Status version: latest nightly
* Operating System: Android
* Real device Huawei P10 Lite, Android 7 , EMUI version 5.1
* Real device Xiaomi Redmi 3
* TF (for logs) https://app.testfairy.com/projects/4803622-status/builds/7504970/sessions/16/?accessToken=PVLxZ7N9KQVgfnVKYaFiWpING5g

**Comment by flexsurfer** [comment]
Node is active, you can send and receive transactions, open Dapps, and also message label is sent, but whisper messages are not propagated to other devices

**Comment by adambabik** [comment]
Is it possible to run the app with `LogLevel` set to `DEBUG` and collect `geth.log` file? TF logs are of no use here. From `geth.log` we can figure out peers the session was using and inspect them.

**Comment by flexsurfer** [comment]
@adambabik  [geth.log](https://github.com/status-im/status-react/files/1651224/geth.log)

**Comment by adambabik** [comment]
Thanks @flexsurfer. From this log, it looks like the app received some very old Whisper messages and in such a case, the protocol disconnects from the peers who sent these old messages (`envelope.Expiry + 10 seconds * 2 < now`). What is strange is that all Whisper nodes sent these old messages which may suggest that something is wrong with the clock settings on this device. Can you make sure the clock is synced properly? We can also create a branch of status-go with more logs that will report exact dates.

**Comment by flexsurfer** [comment]
yes @adambabik , thats the reason, switched clock sync with the net back and messages work
