### ISSUE TITLE
Explore getting token transaction history entry

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#3050]
### User Story

As a user I want to see my ERC20 token transactions in the transaction history along with eth transactions.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: Right now ERC20 token transactions do not show in the transaction history screen, simply because we get that information from Etherscan API and there is no publicly available service that offers that data. However, token transactions still leave some trace in the transaction history - there are special 0 ETH entries with some extra ether for the spent gas for every token transaction.

We should explore getting the needed data (token amount, specifically) from those entries.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x61169dc4582ba128288a05206f5051dd6dc54a89039c06572ae57f834bb0e15d](https://etherscan.io/tx/0x61169dc4582ba128288a05206f5051dd6dc54a89039c06572ae57f834bb0e15d)

**Comment by vikmeup** [comment]
We already figured this out at Trust Wallet.
Open source repo: https://github.com/TrustWallet/trust-ray

`/transactions?address=0xe47494379c1d48ee73454c251a6395fdd4f9eb43` will return all the ether and ERC20 transfers.
 
Documentation available: https://github.com/TrustWallet/trust-ray/wiki/API

<blockquote><img src="https://avatars2.githubusercontent.com/u/32179889?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/TrustWallet/trust-ray">TrustWallet/trust-ray</a></strong></div><div>trust-ray - :cloud: API for the Trust Wallet</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/32179889?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/TrustWallet/trust-ray">TrustWallet/trust-ray</a></strong></div><div>trust-ray - :cloud: API for the Trust Wallet</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd872f15c294a79ccdd008842fbf33e4dc4043c78c234041ab0b0c984b0efa420](https://etherscan.io/tx/0xd872f15c294a79ccdd008842fbf33e4dc4043c78c234041ab0b0c984b0efa420)

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0xd9f7b78d7940867e503dd0dabd1b4da2e7f339ec](https://etherscan.io/address/0xd9f7b78d7940867e503dd0dabd1b4da2e7f339ec)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/3050/04353576bf222cf9bb34bbad3f1438e3727e369051c564887f4c844f74383064/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by jeluard** [comment]
@vikmeup Care to share some details about how you implemented it? :)

**Comment by vikmeup** [comment]
It is open source, you take a look, but in the short summary. 
We build trust-ray for three main reason:
- fetch transactions per specific address
- fetch all the tokens for specific address
- send push notifications for received and sent transfers or tokens for specific address 

Trust-ray parses every block on the blockchain and look for events that’s generated by ERC20 contracts or ether and stored them in DB(MongoDB).

**Comment by ricburton** [comment]
You are doing the lord’s work Viktor

Cheers,

Richard

**Comment by jeluard** [comment]
@vikmeup Nice! Will take a look at it.

**Comment by goranjovic** [comment]
Obsolete, replaced by TBA issue
