### ISSUE TITLE
Redirect to native app notification settings from Profile screen

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#3051]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to be able to easily navigate from the Profile screen to the appropriate OS settings screen where I can set notification preferences for the app.

### Description

*Type*: Feature

*Summary*: 

Notifications button on Profile tab should open OS native screen with Notification preferences for Status app.

Adding any new dependencies in order to fix this issue should be avoided.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 370.00
Contract address: [0xb0f6d5e2d4151034e8e9e727d7e89cbcd7fd4815](https://etherscan.io/address/0xb0f6d5e2d4151034e8e9e727d7e89cbcd7fd4815)
Network: Mainnet
Paid to: jeluard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
