### ISSUE TITLE
Error chat-contact.identity must be of type 'string', got 'object' shown for group chat members after new member is added

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3057]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: Error ```chat-contact.identity must be of type 'string', got 'object' (['0x0428c9d6c1aaaa8369a7c63819684f30e34396dc0907d49afeac85a0a774ccb919b3482097d992e66bcc538e7a0c6acf874c77748f396f53c0a102e10d1a37765b'])``` is shown to all group chat members after admin added new member. If close the error then can continue using the app
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New member is added, info about X added Y is shown in the group chat,
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error message is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add 1 contact, it should add you as a contact too
- Create group chat with that 1 contact
- send some hi message
- edit Settings and add Jarrad to the group members
- check on other device if there any error shown

From 1:08 https://app.testfairy.com/projects/4803622-status/builds/7512524/sessions/4/?accessToken=RBWKtxNivaRwMwIAr-8P4tzzhgU

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release build 56 and nightly build for Jan 16
[comment]: # Android and iOS
real devices Galaxy S6 and iPhone 6s. Android 6.0.1, iOs 10.33.3

**Comment by oskarth** [comment]
PR closed by accident, issue still open https://github.com/status-im/status-react/pull/3063#issuecomment-358218218
