### ISSUE TITLE
Text box takes too much space when using /browse 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3059]
### Description

*Type*: Bug

*Summary*: text box is too large when browsing with /browse command for long urls. 

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/34997393-7702a0f0-faed-11e7-813b-f2d1480312a7.png)

### Reproduction
- Open Status
- Select chat with Jarrad
- /browse for google.com

### Additional Information
* Status version: develop  0.9.10-581-geb17f24f+ (2138) 
* Operating System: Android, iOS

#### Logs
TF: https://app.testfairy.com/projects/4803622-status/builds/7512907/sessions/3/?accessToken=b1qX9onokV5FXOgqiKT6nvMgERo (untill 2:00)

**Comment by chadyj** [comment]
`/browse` is being removed in favour of a better DApp browser in https://github.com/status-im/status-react/issues/3007

**Comment by lukaszfryc** [comment]
@asemiankevich looks like it's a duplicate of https://github.com/status-im/status-react/issues/2977

**Comment by annadanchenko** [comment]
no browse command anymore
