### ISSUE TITLE
Explicitly define keyExtractor for list

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3064]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to be sure list elements don't behave funky because of incorrect `keyExtractor`.

### Description

*Type*: Bug

[list](https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/list/views.cljs) provides a default [keyExtractor](https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/list/views.cljs#L97) but it proved to be a source of [issues](https://github.com/status-im/status-react/pull/3061).

Remove it and make sure all `list` provide a correct `keyExtractor` as part of their definition (as `key-extractor`). FlatList [documentation](https://facebook.github.io/react-native/docs/flatlist.html) might provide some context.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 300.00
Contract address: [0xaa75c6224373ba9a8e038ee3562f5871de70ec11](https://etherscan.io/address/0xaa75c6224373ba9a8e038ee3562f5871de70ec11)
Network: Mainnet
Paid to: voxlet
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by hanwencheng** [comment]
What is the problem with current metaData solution, is there a way to reproduce the error?

**Comment by jeluard** [comment]
@hanwencheng What error?

This issue is about removing the default generic behavior (most of the time incorrect) and replace it with per list usage `keyExtractor`.

**Comment by hanwencheng** [comment]
@jeluard What is the incorrect behavior? I'm trying to first figure out if there is another solution rather than explicitly defining keyExtractor. I have Checked #3061 , it seems can not be tested in local environment, i.e. how to initialize a group chat? is there any mock address for anyone else except Jarrad?

**Comment by jeluard** [comment]
The incorrect behavior is due to generic `keyExtractor` so we want explicit `keyExtractor` per list. There is not issue to fix, rather style change to make sure we don't introduce subtle issues later on.

**Comment by annadanchenko** [comment]
@jeluard if you are fine with the implementation based on the review we can merge. Haven't found any functional bugs with "light weight" regression tests (send messages and ETH in 1:1 and group chats)
