### ISSUE TITLE
Replace incorrect aget access

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3067]
### User Story

As a developer, I want to rely on good dev practises

### Description

*Type*: Feature

`aget` is only supposed to be used for `array` access and not `object fields` access. Replace all incorrect usages with proper access (to be defined).

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 350.00
Contract address: [0xed672385ac7f2c18acecc948c44dab03552f5bcb](https://etherscan.io/address/0xed672385ac7f2c18acecc948c44dab03552f5bcb)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pablodip** [comment]
@jeluard 

Proper access with raw Clojurescript is this one: https://github.com/status-im/status-react/blob/develop/src/status_im/core.cljs#L12

My recommendation is to use [this library](https://github.com/binaryage/cljs-oops), which comes with some [superpowers](https://github.com/binaryage/cljs-oops#benefits), including [better development](https://github.com/binaryage/cljs-oops#play-it-safe-during-development).

Hope this help. :)

**Comment by jeluard** [comment]
@pablodip Thanks for the details!

I am reluctant to depend on an external library for this as we try to minimize those for security reasons.
We could just incorporate the relevant code (small?) in our codebase.
