### ISSUE TITLE
On recent iPhone versions: null is not an object (evaluating 'e.schema') after password submitted when creating new user

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3069]
*Type*: Bug

*Summary*: `null is not an object (evaluating 'e.schema')` after password submitted when creating new user. I can proceed to use the app after the error, can add new user and chat. Happens on iPhoneX with 11.1.2 version. Android 7.0, android 6.0, iPhone 7 - are OK.

#### Expected behavior
No error after password submitted when creating new user
#### Actual behavior
`null is not an object (evaluating 'e.schema')` after password submitted when creating new user.

![image uploaded from ios 1](https://user-images.githubusercontent.com/8749671/35037597-a92f9d60-fb80-11e7-84f1-ba22fe491d3b.png)

### Reproduction 
- Open Status
- Submit valid password value

### Additional Information
* Status version: Confirmed in latest Release (Jenkins 64th release job) and latest develop (nightly) 0.9.11d588 (17th of January) 
* Operating System: iOS 11.1.2

TF session: (from 00:10) https://app.testfairy.com/projects/4803590-status/builds/7520228/sessions/1/?accessToken=N0betVJ48IIrN6FjIXQNKgv1wFc

**Comment by janherich** [comment]
I very strongly suspect the reason for the bug is `iPhone X` being considerably faster, so it's some race condition happening with our super fragile app-startup process :/
Systematic way to fix it is to rework the app startup process, getting rid of imperative, time dependent dispatches, I planned to do that after new year, but release bugfixing got priority.

**Comment by HofmannZ** [comment]
The same bug also occurs on an iPhone 8 Plus

**Comment by annadanchenko** [comment]
also happens on iOhone 7 plus sometimes

**Comment by chadyj** [comment]
Is this still happening? I haven't seen in in a while.

**Comment by Serhy** [comment]
Could not reproduce it iPhoneX (where error appeared all the time on new user creation process). Neither on latest nightly (247 Jenkins build) nor on Release 0.9.14

**Comment by Serhy** [comment]
Happy to close this!
