### ISSUE TITLE
Fix merge-pr script prompt

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3075]
The merge-pr script is prompting ```"There are multiple commits in this PR. Are you sure you wish to continue without squashing?"``` even when there is only one commit.

**Comment by oskarth** [comment]
@andytudhope Do you want to take this one? Bring your bash skillz to the next level :P

Unless we do in https://github.com/status-im/status-react/pull/2919

**Comment by andytudhope** [comment]
I'm suitably embarrassed 😛  Sorry guys... Not really bash skillz, more like git fu and that I struggle with... Maybe we do merge the two scripts though - seems like a neater solution and good bounty?

**Comment by yenda** [comment]
I agree with merging the two scripts and starting with the merge-external-pr.sh script as base as it is already better

**Comment by oskarth** [comment]
Agree, let's do it, @andytudhope do you want to write this up and we can close one of these issues? I can add details if needed.

**Comment by andytudhope** [comment]
@oskarth I have updated #3074 to reflect the need to merge scripts and check that PRs from core team members are indeed squashed. Please review there and then I will assign a bounty.
