### ISSUE TITLE
Separate figwheel from dev lein profile

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3076]
### User Story

As a developer, I want control on my build files and minimize surprises

### Description

*Type*: Bug

With current lein configuration you can't run `lein cljsbuild once` without starting fiwheel (so it never finishes).

Proposed improvement: create a separate `figwheel` profile that will have all necessary dependencies and source-paths (like `env/dev`) and simplify the `dev` profile so that it does not interact with figwheel.
Then running figwheel will require using the `figwheel` profile.

Make sure figwheel reload features are still ok (even when reloading for both iOs and android).

Note: this regression has been introduced by https://github.com/status-im/status-react/pull/2997

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 300.00
Contract address: [0x7611d0f09048e178d57773eb097f64f0c4ce75cf](https://etherscan.io/address/0x7611d0f09048e178d57773eb097f64f0c4ce75cf)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
