### ISSUE TITLE
Allow devtools debugging

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3078]
### User Story

As a developer, I want to have access to existing debugger 

### Description

*Type*: Feature

RN applications can be [debugged](https://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools) using chrome devtools allowing to benefit from its advanced perf tools.
For some reason it is very slow with our apps. Figure out what is causing this slowness (might be related to realm).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe7d0db96a42b574c6b7a15c46b5d1ccf7d11b4d738f25ad8badba52efd5f3777](https://etherscan.io/tx/0xe7d0db96a42b574c6b7a15c46b5d1ccf7d11b4d738f25ad8badba52efd5f3777)

**Comment by debragail** [comment]
@jeluard has anyone tested on android?

**Comment by jeluard** [comment]
Yes I tried on android

**Comment by pablanopete** [comment]
@jeluard will this bounty still be relevant when we start re-bountying issues?

**Comment by jeluard** [comment]
We are good for now!
