### ISSUE TITLE
Chat "more options", delete, and profile

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3083]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see actions available from within a chat, so that I can delete a chat or view a profile

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: From within a chat, when a user taps "more options/..." they will see a list of available options that includes `Delete chat` and `View Profile`.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: Mockups are available on [Invision](https://projects.invisionapp.com/share/ETFEE1QGD8N#/screens/268744122_Chat).

- [x] From within chat window add more options icon "..."
- [x] Add `Delete chat` action
- [x] Add `View profile` action

**Comment by denis-sharypin** [comment]
<img width="891" alt="screenshot 2018-02-13 14 50 24" src="https://user-images.githubusercontent.com/6559881/36153032-422b03cc-10cd-11e8-8df7-44aafc99252d.png">
