### ISSUE TITLE
Application crash during installation

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3089]
### Description

*Type*: Bug

*Summary*: Sometimes Status crashes during install. Can't reproduce on real device but it could be due to lack of knowledge about the root cause.

#### Expected behavior
I can install app on emulator

#### Actual behavior

https://saucelabs.com/beta/tests/5eb199e375e04f6b905bdf7de52aac66/metadata#6

![image](https://user-images.githubusercontent.com/28752642/35150990-9ef5c942-fd2d-11e7-9ec6-f522c6e3dfce.png)

### Reproduction
- using emulator install status

### Additional Information
* Status version: release 0.9.13
* Operating System: Android

#### Logs
[status.ethereum-1d6b94.apk.txt](https://github.com/status-im/status-react/files/1646499/status.ethereum-1d6b94.apk.txt)

**Comment by asemiankevich** [comment]
adding fix-them-all label as this is annoying bug that fails our autotests

**Comment by annadanchenko** [comment]
according to @antdanchenko it's not reproducible last 2-3 weeks, so closing
