### ISSUE TITLE
Uniformative modal window opened when clicking "read" indicator in a group chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3093]
### Description

*Type*: Feature

*Summary*: There is an indicator uder a message in a group chat which appears when the message is read by someone. When I tap it - modal is shown without any relevant info.

@denis-sharypin can we please perform some research on it? like do we need this feature at  all and if yes - how it should look like? Honeslty it has never been tested and therefore it hard to say anything before we understand do we need this at all or not.

#### Expected behavior
I am not quite sure what exactly should be there so I am asking design team for assistance. @denis-sharypin please take a look.

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/35160211-92cdc190-fd4d-11e7-88fc-90c555e23c82.png)

![image](https://user-images.githubusercontent.com/28752642/35160179-762dd75a-fd4d-11e7-87f4-a653ad1c4a6e.png)

**Comment by denis-sharypin** [comment]
@jeluard what options for message statuses we could have here? Sending, Sent, Seen?
and we can use a modal popup component for this right?

**Comment by jeluard** [comment]
@denis-sharypin Good question. Maybe @rasom or @flexsurfer can give some details?

**Comment by rasom** [comment]
We have `sending`, `sent`, `delivered`, `seen` atm
