### ISSUE TITLE
Not all group chat participants are shown in /send suggestions 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3094]
### Description

*Type*: Bug

*Summary*: I have 7 participants in a group chat. Not all of them are added to my contacts. When i tap /send in this group chat to send some funds somebody - I can see only those members in suggestions which I have added to my contacts personally. This seems to be wrong as I can send funds to anyone easily from wallet or in 1x1 chat without adding contact to a list.

#### Expected behavior
All members from group chat are shown in suggestions when sending funds in current group chat

#### Actual behavior
Only my conctacts shown in suggestions

![image](https://user-images.githubusercontent.com/28752642/35161537-9575a620-fd51-11e7-8ef7-5ed333527980.png)

### Reproduction
- Open Status
- Create group chat with several participants
- Add some of them to your contacts and make sure you haven't added them all
- Type /send and pay attention to suggestions shown

### Additional Information
* Status version: develop
* Operating System: Android|iOS

**Comment by goranjovic** [comment]
Closing since group chat and its send command are disabled for the time being.
