### ISSUE TITLE
No bubble background on messages with > 200 lines

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3097]
***Type***: Bug

***Summary***: When the message is really huge (exact number depends from device, but in case of Samsung Galaxy S6 emulator - it's > 190 lines, in a case on Samsung J7 on Android 7.0 it's > 220 messages), such sent or received message on Android is not wrapped up in bubble. 
On iOS message wrapped up in bubble disregard the line number in message. However, empty bubbles are present at some point of such huge-message conversation (see the steps below). 

#### Expected behavior
Message with 10000 lines wrapped up in bubble on Android
#### Actual behavior
Message with 10000 lines wrapped up in bubble on Android

### Reproduction

1) Open Status on iPhone and create new user
2) Open Status on Android and create new user
3) iPhone user adds Android user in contacts (iPhone user wind up on 1-1chat after that)
4) Android user navigates to 1-1chat with iPhone user
5) Android user sends message with 10000 lines (see txt file in attachment)
**Actual result:** sent message does not have message bubble on background. But it's all fine on iPhone side at this moment.

![screenshot_20180119-211447](https://user-images.githubusercontent.com/8749671/35167375-fb81fa2a-fd5d-11e7-8333-0761e918c570.png)

6) iPhone user sends message with 10000 lines
**Actual result:** Empty message. There is no text is present in bubble. However if to copy it's empty message in clipboard  - appropriate content copied fine. So in fact text content is present - but not displayed. 

![image uploaded from ios 2](https://user-images.githubusercontent.com/8749671/35167655-003fd270-fd5f-11e7-8cf6-95bb9e64ffbb.png)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Develop (0.9.11d598)
* Operating System: Android 7.0, Android 6.0, iOS 11.2.1

Txt file with 10000 lines 
[10000lines.txt](https://github.com/status-im/status-react/files/1647642/10000lines.txt)

**Comment by Serhy** [comment]
Reproducible with 0.9.26 Release app version.

**Comment by Serhy** [comment]
Re-opening because it's still an issue in 0.11.0 app version.

**Comment by churik** [comment]
I believe we have the same issue https://github.com/status-im/status-react/issues/9485 - it is discussed there, so I can close this one
