### ISSUE TITLE
Sign and Delete buttons are not shown for unsigned transaction

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3099]
### Description

*Type*: Bug

*Summary*: When a transaction is added to be signed later there is no way to sign or delete it - expected buttons don’t appear

#### Expected behavior
Sign and Delete buttons are shown
![2018-01-20 18 35 28](https://user-images.githubusercontent.com/29711298/35185672-cf7a35ce-fe10-11e7-9bce-7203e2d451dd.jpg)

#### Actual behavior
Sign and Delete buttons are not shown
<img width="511" alt="screen shot 2018-01-20 at 6 20 33 pm" src="https://user-images.githubusercontent.com/29711298/35185694-0d6fa4ae-fe11-11e7-9311-695fa5eb321f.png">

### Reproduction

1. Open Wallet 
2. Click Send Transaction
3. Choose recipient from contacts
4. Input valid amount
5. Click Sign Later button
6. From Wallet view click Transaction history button
7. Open Unsigned tab

### Additional Information
* Status version: Develop (0.9.10-600-g54e83c58)
* Operating System: Android 6.0

**Comment by annadanchenko** [comment]
can also reproduce on iOS
