### ISSUE TITLE
Add accessibility labels to all listed elements for e2e tests

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3102]
### User Story

As an automation engineer I need accessibility labels to be added for specific elements

### Description

Accessibility labels are required for building stable mobile test automation solution
Please, add accessibility labels for all listed elements:

**Sign in view:**
- sign-in-view
- create-account-button
- recover-access-button
<img width="518" alt="sign-in-view" src="https://user-images.githubusercontent.com/29711298/35197821-1fa0cb7a-feee-11e7-9e2e-c9e4a6a9fb26.png">

- back-button
- password-input
- sign-in-button
<img width="514" alt="sign-in-view-1" src="https://user-images.githubusercontent.com/29711298/35197823-2d0dcaf6-feee-11e7-81ef-0e127454728a.png">

**Recover Access view:**
- recover-access-view
- passphrase-input
- password-input
- recover-access-button
<img width="517" alt="recover-access-view" src="https://user-images.githubusercontent.com/29711298/35197828-3eaf30ba-feee-11e7-96fd-04d3e0f86d03.png">

**Console view:**
- console-view
- recover-button
- requests-button
- password-command
- emoji-icon
<img width="518" alt="console-view" src="https://user-images.githubusercontent.com/29711298/35197847-93c39154-feee-11e7-93fd-6a0bacb67bbb.png">

**Console view after creating account:**
- passphrase
- signing-phrase
- faucet-command
- phone-command
<img width="513" alt="console-view-after-account-creating" src="https://user-images.githubusercontent.com/29711298/35197855-c3da7754-feee-11e7-9d4e-1f3f2519f3ed.png">

**Home view:**
- home-view
- plus-button
- home-button
- wallet-button
- profile-button
<img width="515" alt="home-view" src="https://user-images.githubusercontent.com/29711298/35197864-dbbb367e-feee-11e7-8a63-8539731d2b80.png">

**Start New Chat view:**
- start-new-chat-view
- search-icon
- group-chat-button
- public-chat-button
- new-contact-button
<img width="515" alt="start-new-chat-view" src="https://user-images.githubusercontent.com/29711298/35197872-f7a2594e-feee-11e7-9866-8e62546fb7a3.png">

**New Group Chat view:**
- new-group-chat-view
- search-icon
- checkbox
- next-button
<img width="518" alt="new-group-chat-view" src="https://user-images.githubusercontent.com/29711298/35197884-138e054a-feef-11e7-9ba6-d574178b32cc.png">

- chat-name-input
- save-button
<img width="516" alt="new-group-chat-view-1" src="https://user-images.githubusercontent.com/29711298/35197885-1e9076c6-feef-11e7-97a4-62998218d9b0.png">

**Chat settings view:**
- chat-settings-view
- chat-name-input
- add-members-button
- options-icon
- mute-button
- chat-history-button
- leave-chat-button
<img width="516" alt="chat-settings-view" src="https://user-images.githubusercontent.com/29711298/35197890-3326a8a8-feef-11e7-8b4b-e8e72b1a30d0.png">

- remove-member-button
<img width="511" alt="chat-settings-view-1" src="https://user-images.githubusercontent.com/29711298/35197892-3af3465e-feef-11e7-986e-47e938794931.png">

**Join Public Chat view:**
- join-public-chat-view
- check-mark-icon
- topic-input
<img width="513" alt="join-public-chat-view" src="https://user-images.githubusercontent.com/29711298/35197904-6fd299b0-feef-11e7-8b94-e22f822cd9eb.png">

**Add New Contact view:**
- add-new-contact-view
- check-mark-icon
- public-key-input
- scan-qr-code-button
- public-key-error-text
<img width="513" alt="add-new-contact-view" src="https://user-images.githubusercontent.com/29711298/35197909-7d0314f2-feef-11e7-9303-f968aa850964.png">

**Chat menu:**
- name-text
- profile-button
- delete-button
- search-chat-button
- notifications-button
<img width="519" alt="chat-view" src="https://user-images.githubusercontent.com/29711298/35197918-a733721c-feef-11e7-8f43-84730da1ead9.png">

**Chat view:**
- add-to-contacts-button
- browse-command
- location-command
- request-command
- send-command
<img width="513" alt="chat-view-1" src="https://user-images.githubusercontent.com/29711298/35197921-b9954520-feef-11e7-8af2-28ccc97503d1.png">

- request-message
- location-message
- send-message
- text-message
- sender-profile-picture
<img width="515" alt="chat-view-2" src="https://user-images.githubusercontent.com/29711298/35197924-c430d6fc-feef-11e7-8786-be3d6f57519d.png">

- cross-icon
- amount-text
- fee-text
- fee-slider
<img width="516" alt="chat-view-3" src="https://user-images.githubusercontent.com/29711298/35197927-ca363d8a-feef-11e7-95a2-b84edce2d11c.png">

**Wallet view:**
- options-button
- total-usd-amount
- send-transaction-button
- receive-transaction-button
- transaction-history-button
- eth-amount
- stt-amount
<img width="516" alt="wallet-view" src="https://user-images.githubusercontent.com/29711298/35197930-e3d58296-feef-11e7-8d8f-d18fd9fab0a5.png">

- manage-assets-button
<img width="521" alt="wallet-view-1" src="https://user-images.githubusercontent.com/29711298/35197931-ec022474-feef-11e7-9bc0-c46d6226d4ae.png">

**Manage Assets view:**
- done-button
- assets-view
- checkbox
<img width="518" alt="manage-assets-view" src="https://user-images.githubusercontent.com/29711298/35197934-019c6cae-fef0-11e7-8142-4e6c76621d7b.png">

**Send Transaction view:**
- back-button
- send-transaction-view
- choose-recipient
- choose-asset
- amount-input
- advanced-button
- transaction-fee
- sign-later-button
- sign-transaction-button
<img width="517" alt="send-transaction-view" src="https://user-images.githubusercontent.com/29711298/35197945-1e728dcc-fef0-11e7-8ffb-d9b6190547b1.png">

- signing-phrase
- password-input
- cancel-button
<img width="518" alt="send-transaction-view-1" src="https://user-images.githubusercontent.com/29711298/35197948-29482338-fef0-11e7-9bc5-52a56e3ba0fd.png">

**Choose Recipient view:**
- back-button
- choose-recipient-view
- flash-button
- choose-from-contacts
- address-from-clipboard
- browse-photos
<img width="514" alt="choose-recipient-view" src="https://user-images.githubusercontent.com/29711298/35197952-3d58be28-fef0-11e7-9212-f18bfbcc53bf.png">

**Contacts to choose recipient view:**
- search-button
<img width="514" alt="contacts-to-choose-recipient-view" src="https://user-images.githubusercontent.com/29711298/35197956-52552d7a-fef0-11e7-9a5b-d4117b63df4c.png">

- search-contacts-input
<img width="512" alt="contacts-to-choose-recipient-view-1" src="https://user-images.githubusercontent.com/29711298/35197960-57362880-fef0-11e7-86eb-034e373aba8e.png">

**Transaction Fee view:**
- cross-icon
- transaction-fee-view
- gas-limit-input
- gas-price-input
- amount-text
- total-fee-text
<img width="519" alt="transaction-fee-view" src="https://user-images.githubusercontent.com/29711298/35197963-7a1b85c0-fef0-11e7-9281-f5068956c59f.png">

**Transaction Sent view:**
- got-it-button
<img width="514" alt="transaction-sent-view" src="https://user-images.githubusercontent.com/29711298/35197965-847f143c-fef0-11e7-8347-a7f0c78d8895.png">

**Request Transaction view:**
- back-button
- request-transaction-view
- amount-input
- choose-asset
- share-button
- send-request-button
<img width="511" alt="request-transaction-view" src="https://user-images.githubusercontent.com/29711298/35197977-9b8aa70e-fef0-11e7-9a52-b7fdb9b73f83.png">

**Transactions view:**
- transactions-view
- filter-button
- history-tab
- unsigned-tab
<img width="516" alt="transactions-view" src="https://user-images.githubusercontent.com/29711298/35197982-afee4ca0-fef0-11e7-934a-2d7d22c20fcc.png">

**Transaction Filter History view:**
- done-button
- select-all-button
- checkbox
<img width="518" alt="transactions-filter-history" src="https://user-images.githubusercontent.com/29711298/35197986-bb6354c2-fef0-11e7-9ee7-9b1a8ab166eb.png">

**Transaction Details view:**
- transaction-details-view
- options-button
<img width="514" alt="transaction-details-view" src="https://user-images.githubusercontent.com/29711298/35197992-c771fe62-fef0-11e7-8f94-c7da6c716773.png">

- copy-hash-button
- open-etherscan-button
<img width="516" alt="transaction-details-view-1" src="https://user-images.githubusercontent.com/29711298/35197996-cc5a6c02-fef0-11e7-8897-b661daf22643.png">

**Comment by lukaszfryc** [comment]
This is out of date now. Here is a new bounty for Wallet accessibility labels #3394
