### ISSUE TITLE
hanged on reloading screen.

### ISSUE THREAD

**Issue by hanwencheng** [status-im/status-react#3103]
### User Story

As a developer, I want to contribute to the project and debug it.

### Description

*Type*: Bug (actually configuration issue)

Hi, I want to make some contribution but meet build problem, tried ask on dev-status channel but get no response, so I post here as well:
In IOS simulator the app is **successful installed and run**, but I cannot do `reload` or `remotely debug`, if I click the button, the screen will be hanged on as the screenshot below, I followed the build instructions and tried on both mac desktop and laptop, also pulled from two different day, uese node `v8.8` and `v9.4`. My flow is `make prepare` -> `make dev-ios-simulator` -> `make repl-ios` -> `make run-ios`. I searched document and stackoverflow but find nothing. Any help would be appreciated, thanks!

#### Expected behavior

Can reload and remotely debug with iOS simulator

#### Actual behavior
<img width="353" alt="screen shot 2018-01-19 at 11 39 02 pm" src="https://user-images.githubusercontent.com/6014309/35199713-4b95ccd0-ff02-11e7-9bb7-c0678367c047.png">

### Reproduction
 My flow is `make prepare` -> `make dev-ios-simulator` -> `make repl-ios` -> `make run-ios`. 

### Additional Information
* Status version: Latest develop branch
* Operating System: iOS

#### Logs

No console error is loged out

**Comment by flexsurfer** [comment]
hey @hanwencheng why do you want to reload project manually? it reloads automatically, while you change code

**Comment by hanwenc** [comment]
Hey, @flexsurfer, I actually want to debug it with chrome-dev-tools, but by click `remotely debug` and `reload`, I get the same result as the screenshot shows.

**Comment by flexsurfer** [comment]
hey @hanwenc you can use re-frisk `http://localhost:4567/` for debug purposes, you don't need to use chrome-dev-tools, also you can see logs in ios console (or android adb )

**Comment by dmitryn** [comment]
Also, `react-devtools` works fine for me without "remote debug" and "reload"

**Comment by hanwencheng** [comment]
@flexsurfer That helps, thanks!

**Comment by flexsurfer** [comment]
but let's do not close this issue, because we should fix this reload issue anyway

**Comment by jeluard** [comment]
@flexsurfer See https://github.com/status-im/status-react/issues/3078

**Comment by flexsurfer** [comment]
@jeluard yeah i mean sometimes i want to reload app using cmnd+R, and it hangs, i need to close it and reopen, lets fix this in this issue

**Comment by jeluard** [comment]
@flexsurfer Oh right reload is different.. Maybe we can create a bounty for it?

**Comment by flexsurfer** [comment]
@jeluard i think yes, would be good

**Comment by jeluard** [comment]
@flexsurfer @hanwencheng  See #3118

**Comment by hanwencheng** [comment]
@flexsurfer I open the system log window and run`$react-native log-ios`, the logs from `taoensso.timbre` does not appear. Is there any config need to be set? I tried to edit the `LOG_LEVEL` in `config.cljs`, but it seems does not work.

**Comment by dmitryn** [comment]
@hanwencheng related issue https://github.com/facebook/react-native/issues/9441

You can see your logs in Console.app though or in Xcode if you run app from there.

**Comment by hanwencheng** [comment]
@dmitryn thanks!
