### ISSUE TITLE
[Perf] User story 6: Visible timelag on creating account

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3111]
### Description

*Type*: Bug

*Summary*: There is a visible time lag when creating account. Password message is hanging for 2-3 seconds visible for user when is should be hidden after user set up a password confirmation. Sometimes password message overlaps other messages in Console.

#### Expected behavior
No lags when creating account. After I confirm password - confirm password message dissaperas and other messages are shown in correct logical order.

#### Actual behavior

User able to see this picture for a couple of seconds which gives a chance to  him to consider this as an app lag

![image](https://user-images.githubusercontent.com/28752642/35219556-278232b6-ff84-11e7-93f3-5a5ab98349cb.png)

### Reproduction
- Open Status
- Set up password

### Additional Information
* Status version: latest develop
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7534654/sessions/44/?accessToken=3VL9CAvzYkIhL/tVKGFtClsHQWo

**Comment by dmitryn** [comment]
I would close this since we have new onboarding
