### ISSUE TITLE
The screen flickers when the user try to add new contact from the wallet and the Invalid address error is displayed.

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#3112]
### Description

*Summary*: 
When the user wants to send a transaction to a new recipient the screen flickers when trying to add a new user using the QR code, the error message Invalid address is displayed.
#### Expected behavior
Users should not see the screen flickering when adding a new contact usong the QR code.

#### Actual behavior
The screen flickers when users scan the QR code.

![image 3](https://user-images.githubusercontent.com/33925578/35221554-75a162b2-ff72-11e7-92da-350aa31a7c54.png)

### Reproduction

- As user 1, open Status using the iPhone SE.
- As user 2, open Status using the Samsung Galaxy S6 (user 2 wallet is not empty).
- As user 1 navigate to the user profile and display the QR code.
- As User 2, select the "Wallet", seledt "Sen transaction", tap the "recipient" and scan user 1 QR code, notice the screen flickers and the error message is displayed. (The screen does not flicker when scanning with the iPhone).

### Additional Information
* Status version: 
Real Galaxy S6, status version 0.9.10-600-g54e83c58+
Real iphone SE status version 0.9.12 (testFlight)
* Operating System: Android 6.0.1, iOS: 11.2.2

**Comment by andytudhope** [comment]
Removing bounty votes due to lack of votes for sustained period of time.
