### ISSUE TITLE
Allow app reloading in development mode

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3118]
### User Story

As a developer, I want to be able to reload the app while developing

### Description

Type: Feature

RN applications can be reloaded while developing using react-native developer menu.
This is currently broken and forces to restart the whole application.

**Comment by yenda** [comment]
@jeluard could you specify the difference between a reload and a restart ?

**Comment by jeluard** [comment]
@yenda This is the reload option as available in RN developer menu. Not sure what it is doing but it does not work with status.

**Comment by goranjovic** [comment]
@jeluard What I noticed is that automatic reloading via figwheel stops working as soon as first red screen is shown. Whenever that happens, only app restart helps. Maybe it's related.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 370.00
Contract address: [0xd40a88a9d8696d847f9b727c11be6acfc5a96e52](https://etherscan.io/address/0xd40a88a9d8696d847f9b727c11be6acfc5a96e52)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
