### ISSUE TITLE
Synchronisation Indication (Sync/Finished/Offline)

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#312]
We need to implement #269 
A prototype can be found here:
http://share.framerjs.com/gqxy070ggvyd/

State are;
- Online: as we have it now
- Offline: Animate offline banner down above chat view, under header bar
- Syncing: 
  - In-progress: blue/purple animation underneath header bar
  - Complete: animation animates to green momentarily then to Online state

The states & assets can be found here;
https://zpl.io/Z2q1Yli

I imagine we can use `eth.syncing` object to determine where we are in sync and i imagine we can use `admin.peers.length > 0` to determine if we're online/offline. Open to better ideas

**Comment by jarradh** [comment]
should we have this on other screens as well (the coloured gradien bar) like the chat list ?

**Comment by alwx** [comment]
@jarradh yes, probably. Will move my code from the chat tomorrow.

**Comment by alwx** [comment]
https://github.com/status-im/status-react/pull/330
