### ISSUE TITLE
Error on joining chat with many messages

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#3126]
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: 

App shows redbox error "No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer" when you join #status public channel.

#### Expected behavior
No error is shown.

#### Actual behavior
Redbox error is shown.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join #status public channel

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:

As error message suggest we should consider using windowed buffers.

- [ ] check usage of unbounded channels across the app (created with `(async/chan)`)
- [ ] consider using buffered channels instead

<img width="411" alt="screen shot 2018-01-24 at 14 10 19" src="https://user-images.githubusercontent.com/23836/35332187-23866496-011b-11e8-9412-bda61cf24b5b.png">

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x781f72f5b4eea89d4ff2756e1de261b435a7e717](https://etherscan.io/address/0x781f72f5b4eea89d4ff2756e1de261b435a7e717)
Network: Mainnet
Paid to: janherich
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dmitryn** [comment]
This looks like the place we create async chan which is getting overwhelmed
https://github.com/status-im/status-react/blob/develop/src/status_im/protocol/web3/delivery.cljs#L56

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by dmitryn** [comment]
@janherich is going to make PR to fix that
