### ISSUE TITLE
Back button is inactive when creating account

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3127]
### Description

*Type*: Bug

*Summary*: Back button is inactive when creating account

#### Expected behavior
User is redirected back to Home screen when tapping back button. No new account was created.

#### Actual behavior
Back button is not active. User has to kill the app to get back to Home screen

### Reproduction
- Open Status
- Create one account and logout
- On home screen tap create account
- Tap back button at the top left corner of the application screen

![image](https://user-images.githubusercontent.com/28752642/35333076-689fd9c4-011e-11e8-87e7-31f0da9424f0.png)

### Additional Information
* Status version: 0.9.10-608-gbf95603b+ (2165)
* Operating System: Android, iOS

#### Logs
TF: https://app.testfairy.com/projects/4803622-status/builds/7561898/sessions/19/?accessToken=woJYmVqH6SaGylC1jMNOMNORwGA

**Comment by yenda** [comment]
@asemiankevich please test in develop it should be fixed by https://github.com/status-im/status-react/pull/3198
