### ISSUE TITLE
Sign transaction button is available when having 0 funds for some dapps (CK, Auction house) and tokens

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3130]
### Description

*Type*: Feature

*Summary*: we have now several edge cases when sending tokens from wallet: 
1 - I send tokens with gas price and gas limit set to 0 and i receive this `transaction underpriced` https://prnt.sc/i4y92k 

2 - when i set too high gas price or gas limit and transaction fee is more than i have on my balance. In this case i am receiving `insufficient funds` https://prnt.sc/i4ya6i 

3 - when having 0 ETH sign button is available for some dapps (CK or Auction House), so i am able to send txn (even the red error message is showing insufficient funds) and then error pop up is shown

Need to implement some kind  of real time validation for both cases so me as a user is not confused tapping Got it button and expecting the transaction sent and then seeing errors.

#### Expected behavior
Validation is performed real time so I:

- can't send tokens when transaction fee is more than my current ETH balance
- can't send tokens with 0 gas limit and 0 gas price
- can't perform txn to dapp (CK , Auction House) when i dont have enough funds

### Reproduction

- Open Status
- Claim some tokens
- Send tokens having transacton fee more than current balance
- Send tokens having gas limit and gas price = 0
- Try to buy expensive kitty
- Having 0 ETH try to set up auction

### Additional Information
* Status version: latest develop
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
> 1 - I send tokens with gas price and gas limit set to 0 and i receive this transaction underpriced https://prnt.sc/i4y92k

In addition to setting gas price and gas limit to 0 there is also another case. @Serhy found that if there is no network when requesting for "lowest gas price" the gas limit and gas price fields are empty. If then user tries to send transaction he gets `transaction underpriced`. It can happen not only in wallet but in a chat as well (`/send`). 

First thing we could do is to display more meaningful message than "transaction underpriced" and suggest the user what to do next. Also, if we got the lowest fee at least once we should store it and use it as default value. This way we can minimize risk of not getting the lowest fee every time send transaction screen is opened.


 

<blockquote><img src="https://image.prntscr.com/image/NDopyIiMT56mT0haIPLX5g.png" width="48" align="right"><div>Lightshot</div><div><strong><a href="https://prnt.sc/i4y92k">Screenshot</a></strong></div><div>Captured with Lightshot</div></blockquote>
