### ISSUE TITLE
Screen cut off when using ERC dEX DApp

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3131]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use ERC dEX so that I can trade.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When I search for a token I can no longer see half the screen. If I scroll down I only see white

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I expect to see the rest of the screen

#### Actual behavior
[comment]: # (Describe what actually happened.)
The screen is cut off and I only see white.

<img width="319" alt="img_0533_png" src="https://user-images.githubusercontent.com/116099/35349700-a961aad8-0109-11e8-86c1-ff24f1877ca1.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and go to console
- Use Mainnet
- /browse https://app.ercdex.com/
- type `set` into the search box

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Remove the white overlay to see the screen behind.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightly Jan 23
* Operating System: iOS
* Device: iPhone X

cc @lukeautry from ERC Dex

**Comment by lukeautry** [comment]
That is weird. FWIW (and you can see the intended layout just in mobile mode in Chrome or your desktop browser), the tab bar is a fixed position element stuck to the bottom of the screen - the fact that anything can appear below that is quite strange. Is that white panel rendered in the browser, or does it belong to status?

**Comment by pablanopete** [comment]
CC @rasom @jeluard @oskarth ^

**Comment by dmitryn** [comment]
@chadyj i don't have this issue using iOS simulator (iPhone 6) and real android (oneplus 5)

**Comment by dmitryn** [comment]
Cannot reproduce this on iPhone X in simulator as well.

**Comment by goranjovic** [comment]
@dmitryn Can't reproduce it either on last nightly with iPhone 6s real device

**Comment by chadyj** [comment]
I just tried it with the nightly and the problem is still happening.
To reproduce make sure you search for a token then scroll.

Tested with real iPhone X.

![ercdex-scroll](https://user-images.githubusercontent.com/116099/38617464-6e343d5c-3d97-11e8-85a7-39c1960c7675.gif)

**Comment by dmitryn** [comment]
>To reproduce make sure you search for a token then scroll.

Still not reproducible for me (i don't have real iPhone X though)

**Comment by goranjovic** [comment]
Ok I see it now (real 6s)

**Comment by dmitryn** [comment]
@goranjovic i suggest you to look at this further

**Comment by flexsurfer** [comment]
@goranjovic as i remember i could reproduce this in chrome so the problem not in status

**Comment by chadyj** [comment]
I tried to reproduce in Chrome on iOS and it worked as expected.

**Comment by goranjovic** [comment]
Looks ok in Toshi too. Seems related to keyboard somehow

**Comment by flexsurfer** [comment]
@goranjovic it reproduced for specific webview size, so if you play with browser window size on a desktop you will reproduce it for sure

**Comment by flexsurfer** [comment]
imo we can't fix it in status

**Comment by lukaszfryc** [comment]
The Getting Started screen is also cut off. Someone reproduce it on Android 24, SM-G935F: 

<img src="https://user-images.githubusercontent.com/7532782/39118180-0d1f2d64-46e9-11e8-92de-6a1ac1b37b68.png" width="300">

@chadyj do you think we should contact the app creators like we do in #3887?

**Comment by chadyj** [comment]
@lukaszfryc I tested with a few other mobile dapp browsers and they all correctly displayed the page. Seems like the issue is with Status.

Also @lukeautry (commented [above](https://github.com/status-im/status-react/issues/3131#issuecomment-360230927)) is from ERCDex if you have any questions for the developer.

**Comment by rachelhamlin** [comment]
Same issue when I try to register for Etherbots. Keyboard opens and a box covers the text input: 
<br>
<img src="https://user-images.githubusercontent.com/15470435/39815063-2dde6b2c-5397-11e8-863d-5f68f6da6027.jpg" width="300"/>

**Comment by chadyj** [comment]
@lukeautry Would you mind grabbing the latest Status build and switch to Mainnet and checkout ERC dEX in Status? There are a few responsive issues.

**Comment by lukeautry** [comment]
Thanks @chadyj, I'll take a look.

**Comment by rachelhamlin** [comment]
Still seeing Chad's original keyboard issue in Status, but not other browsers. @jeluard @flexsurfer I think it's our problem. 

https://willalways.love/
<img src="https://user-images.githubusercontent.com/15470435/42211903-f43e5f96-7eb4-11e8-95e6-a483d822e067.png" width=250 />
In this case, the modal is so short that you can't see what's happening in the frame.

ddex
<img src="https://user-images.githubusercontent.com/15470435/42212176-adc8c87a-7eb5-11e8-9e87-31402b4b4975.png" width = 250/>



<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://willalways.love/">Engrave your love on the blockchain - willalways.love</a></strong></div></blockquote>
