### ISSUE TITLE
Lost conversation parts on 1-1 chats

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#3132]
### User Story

As a user, I want to send messages so that to be sure that the other side would receive them.

### Description

*Type*: Bug

*Summary*: I've created 2 virtual Android devices and started a 1-1 conversation between them. Then I left the devices for some time and resumed the conversation.

#### Expected behavior

I expected to receive the messages sent from each of the accounts when navigating to each of the virtual devices.

#### Actual behavior

Some of the messages got lost, no matter that the following ones were received successfully.

### Reproduction

1. Create 2 virtual devices (I don't have real ones to test with them)
2. Setup a Status account for each of them
3. Make them "friends"
4. Start a chat conversation between them
5. Stop it at some point for a while (~ 10 minutes in my case)
5. Resume the conversation

### Additional Information

* Status version: 0.9.12b
* Operating System: Android

![screenshot 4](https://user-images.githubusercontent.com/5781465/35351273-149b7286-0149-11e8-8776-1670be97282e.png)

**Comment by lukaszfryc** [comment]
Already fixed
