### ISSUE TITLE
Ethereum node problems when unlocking ZRX permission using ERC dEX DApp

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3134]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user using ERC dEX I want to unlock ZRX allowance permission so that I can exchange tokens.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When using ERC dEX on Mainnet, I tap the padlock icon next to ZRX and get an error.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Tap the padlock icon and approve the transaction.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Tap the padlock and see an error `Error setting allowance: TOKEN_CONTRACT_DOES_NOT_EXIST`

<img width="321" alt="token_conract" src="https://user-images.githubusercontent.com/116099/35353075-07c67dc4-0114-11e8-9b5a-07d19bc81b2f.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Use Mainnet
- Open Status and go to console
- /browse https://app.ercdex.com/
- tap the red padlock next to ZRX

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightly Jan 23
* Operating System: iOS
* Network: Mainnet
* Device: iPhone X

ERC dEX support @lukeautry said:

> Technically, what's happening is that we are using the ERC20 function of allowance to grant the 0x contract an allowance to move your tokens for you.  It seems that the Ethereum node you're connected to is giving bad information about where the token contract lives, so allowance can't be set.
> 
> Our first inclination is that it looks like your web3 client is just connected to the wrong network (Kovan, Rinkby, etc.)... but if you're sure that's not the case, then there's an issue with the Ethereum node it's connected to.

**Comment by lukeautry** [comment]
Are you guys hosting your own Mainnet nodes? Is it possible that any of the nodes in the cluster are out of sync?

For it to be saying the token contract doesn't exist would mean that the node is somewhere in a block prior to August 2017.

**Comment by chadyj** [comment]
Update: In Status I was using `Mainnet`.
I then tried `Mainnet with upstream RPC` and it worked as expected.
