### ISSUE TITLE
The @browse command doesn't handle properly Cyrillic URLs 

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#3135]
### User Story

As a user, I want to see the Cyrillic URLs properly.

### Description

*Type*: Bug/Feature

*Summary*: The Cyrillic URLs should be handled properly.

#### Expected behavior

To see the proper URL

#### Actual behavior

![capture](https://user-images.githubusercontent.com/5781465/35353148-ec394bfa-014e-11e8-940f-ba393b450156.JPG)

### Reproduction

1. Open Status
2. Start a group/1-1 conversation/Open a dApp
3. Enter @browse + some Cyrillic URL (for example чанти.net)

### Additional Information

* Status version: 0.9.12b

* Operating System: Tested on Android emulator only

**Comment by mandrigin** [comment]
Coming from the browser development background, I probably will add my $0,02 here.

Showing unicode URLs as they are (non-punicoded) opens a huge security hole in the system: URL spoofing. 
For instance, if I register domains:
- "fаcebook.com" (Cyrillic а);
- "ассounts.gооglе.com" (Cyrillic o and e in the URL). 
It wouldn't be possible for a user to distinguish them from the real domain names.

So if we decide to implement that, we need to also make sure that there isn't any mixed ascii/unicode symbols in the URL.

Or just keep punicode as it is.

UPD: a few links on this topic:
https://arstechnica.com/information-technology/2017/04/chrome-firefox-and-opera-users-beware-this-isnt-the-apple-com-you-want/
https://en.wikipedia.org/wiki/IDN_homograph_attack
https://www.chromium.org/developers/design-documents/idn-in-google-chrome (See April 2017 update)
