### ISSUE TITLE
Add a line under profile image when editing profile

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3136]
### Description

*Type*: Bug

*Summary*: Add a line to profile for both platforms to match the mock

#### Expected behavior

![image](https://user-images.githubusercontent.com/28752642/35380383-2479f232-01ca-11e8-9471-7aa6e197dfe4.png)

iOS 
![image](https://user-images.githubusercontent.com/28752642/35380233-bb0c12bc-01c9-11e8-9334-b7c2ee58871b.png)

Android
![image](https://user-images.githubusercontent.com/28752642/35380262-d077dc30-01c9-11e8-9974-c610811b66ea.png)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
- Open Status
- Tap Profile
- Tap edit
- Pay attention to the user profile

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 200.00
Contract address: [0x3cd45f8982c6fab0a0f2fabce01ea582f1f7526a](https://etherscan.io/address/0x3cd45f8982c6fab0a0f2fabce01ea582f1f7526a)
Network: Mainnet
Paid to: salax
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by denis-sharypin** [comment]
@asemiankevich  great bug description!
