### ISSUE TITLE
Migrate hiccup properties to kebab-case

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3139]
### User Story

As a developer, I want to follow good coding convention

### Description

*Type*: Feature

`reagent` allows to define component properties in `kebab-case` (e.g. `:background-color`). Make sure all existing `camel-case` usages (e.g. `:backgroundColor`) are migrated to `kebab-case`.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x061f7e7db956d1d8bb26bf33007eaf0ff52d6941](https://etherscan.io/address/0x061f7e7db956d1d8bb26bf33007eaf0ff52d6941)
Network: Mainnet
Paid to: rcullito
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by rcullito** [comment]
Hello, @jeluard I am just noticing that this contract address is linked to Testnet, rather than the Mainnet... and also doesn't carry any tokens. Is there an error with this bounty?

**Comment by jeluard** [comment]
@andytudhope Can you take a look at that?

**Comment by rcullito** [comment]
thanks @jeluard and @andytudhope for following up on fixing this contract. Is it possible to have it allocated now that the issue has been resolved via #3315 ?

**Comment by jeluard** [comment]
@rcullito I understand this is fixed now?

**Comment by rcullito** [comment]
@jeluard yes, thanks for following up. The contract itself is fixed... but since it was fixed after my PR was merged the balance has not been transferred yet. So it seems like it might take a manual kick?

**Comment by jeluard** [comment]
@rcullito Supposedly it has been done @siphiuel can you confirm?

**Comment by rcullito** [comment]
awesome, thank you @jeluard. looks like it is "Pending maintainer confirmation" so I assume all is well now.

**Comment by vitvly** [comment]
Yes, it was executed. We should now wait for the bounty owner to confirm it in SOB UI.
