### ISSUE TITLE
Cannot sign in to Cryptokitties

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3143]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to sign in to CryptoKitties so that I can collect and breed digital cats.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: CryptoKitties doesn't work with Status.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- Sign in, and start collecting digital cats

#### Actual behavior
[comment]: # (Describe what actually happened.)
An adorable error message saying that a desktop browser is required.

<img width="321" alt="screen shot 2018-01-25 at 11 43 31 am" src="https://user-images.githubusercontent.com/116099/35400526-02231e16-01c5-11e8-9bea-c5ca0e5f63a9.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Browse to https://www.cryptokitties.co
- Click sign in

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

### Additional Information
* Status version: Any
* Operating System: Both

**Comment by chadyj** [comment]
Arthur from Cryptokitties suggested this fix:

> CryptoKitties detects the browser by checking for window.chrome and window.chrome.webstore. if you simply inject window.chrome = { webstore: true } for instance, you will bypass that message and be able to interact with CryptoKitties entirely (provided that web3 is injected as well)

**Comment by flexsurfer** [comment]
related to https://github.com/status-im/status-react/issues/2704

**Comment by andytudhope** [comment]
@flexsurfer seeing as we have a large bounty on 2704, can I remove the `bounty-awaiting-approval` label here?

**Comment by flexsurfer** [comment]
@andytudhope this still needs a small bounty to inject window.chrome = { webstore: true }

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x8a754904a1a463270ef712d04dec03a79f9e8f80](https://etherscan.io/address/0x8a754904a1a463270ef712d04dec03a79f9e8f80)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
