### ISSUE TITLE
Update Ethereum to Ether asset name

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3145]
### Description

*Type*: Bug

*Summary*: We want to use `Ether` in asset name 

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/35431615-359e8842-028e-11e8-9b0f-e893c2773632.png)

### Reproduction

- Open Status
- Go to Manage assets on wallet tab

### Additional Information
* Status version: latest develop
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 225.00
Contract address: [0x2f825461003745235c41b1b8ca31dd80ad29ee7e](https://etherscan.io/address/0x2f825461003745235c41b1b8ca31dd80ad29ee7e)
Network: Mainnet
Paid to: hanwencheng
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
