### ISSUE TITLE
[Perf] Test Hypothesis 5: synchronous realm reads/writes are the major factor contributing to bad UI performance and event processing speed

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#3146]
### Identified Behavior

The app UI is very slow to respond in certain cases, it's most visible when receiving a lot of messages, but also when sending a new message, user perceives noticeable lags between hitting the `send` button and UI updated as a result of such action (new message is rendered, etc.)

- [x] User story part of MVP scope
- [x] Identified end user behavior

### Hypothesis

According to preliminary testing (done in `dev` mode), synchronous realm reads/writes always take **7-8ms** which completely dwarfs any time spent in actually updating persisting datastructure representing our app state (`re-frame` app-db) - doing even complicated nested update on app-db is basically not measurable using the `time` function. 
Following facts also hold true:
* While 7-8ms doesn't seem like much at the first glance, frequent usage paths (like receiving/sending message) involves **many** of such operations done in sequence, easily pushing it to **50-100ms**, already taking much more then time of one 16fps frame, not even mentioning that in case of message receiving, it could happen that more of such events are queued on the `re-frame` event queue which blocks till all the events are processed (we "solved" that critical case with hacky workaround)
* For app to work (eq UI is responsive) we strictly don't need anything else other then operate on `re-frame` app-db (and changes there are automatically reflected through subscriptions->views to UI). Network communication can happen asynchronously (this is already the case in some times), the same holds true for persisting data through any DB we decide to use (realm currently).
By separating lightning-fast, pure functional data events from other effects and putting those (potentially much more expensive) other effects on separate queue (or more queues), we can leverage good default `re-frame` performance (which is fine when used as its meant to be, primary updating `app-db`) and fine-tune the other queues so that their throughput is just enough and not blocking anything.

### Assumptions

- The app responsiveness suffers because of the architecture mixing functional data updates & side effect IO together
- App responsiveness is generally bad for MVP user flows

### Experiment

To quickly test the hypothesis, focus on just one user path (let's say, receiving messages) and make sure nothing like sync IO (realm reads/writes, web3 callbacks, etc.) is happening on the main `re-frame` queue, offload it to separate queue + make sure that realm reads (necessary for that path) all happen at the app-startup, so when new message arrives, everything necessary for processing is already in `re-frame` app-db.

#### Responsiveness metrics
1. UI performance (time to receive 50 messages much better then now)

### Acceptance criteria

- [ ] Measure UI performance
- [x] Make sure that UI is not blocking

**Comment by janherich** [comment]
Branch testing the hypothesis is called `feature/offband-realm-#3146`

**Comment by oskarth** [comment]
@janherich @dmitryn What's the state of this experiment?

**Comment by janherich** [comment]
@oskarth Hypothesis was basically proved and fixed in most critical places slowing down the app.

**Comment by dmitryn** [comment]
@oskarth some of my PRs related to this hypothesis are still in TO TEST state:
https://github.com/status-im/status-react/pull/3212
https://github.com/status-im/status-react/pull/3225
https://github.com/status-im/status-react/pull/3265

I'm not going to add anything more to this experiment. As Jan said, experiment could be considered over.

**Comment by oskarth** [comment]
@janherich @dmitryn  Ok cool! Sounds like we can close this issue then?
