### ISSUE TITLE
no visual feedback after add contact arrow

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#315]
need to think on what should happen
goto contact, open chat?
needs some kind of visual confirmation

**Comment by jarradh** [comment]
had thought about this and i think open chat is the next conclusion, pressing back button would take you to the chat list

**Comment by alwx** [comment]
My solution is easy — I simply open the chat but doesn't redirect the user to the chat list (on back press user will see the list of contacts). If it is not okay, I will spend more time working on it, but the solution may be much more time-consuming and complicated in this case.

**Comment by jarradh** [comment]
open chat is great
