### ISSUE TITLE
Typing ".0" is not replaced by 0.0 in "Specify amount" field on 'Send transaction' wallet screen

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3151]
***Type***: Bug

***Summary***: The dot disappears and replaced with '0' when you start typing the amount you want to send to recipient from the 'Send Transaction' screen with the dot followed by '0'. 
This is not the case for any other figures after dot other than 0. For instance `.1` - replaced with `0.1`, or `.3` - with the `0.3`

**Expected behavior**
Typing `.0` value in 'Specify amount' edit box on the 'Send transaction' screen - replaced by the`0.0`
**Actual behavior**
Typing `.0` value in 'Specify amount' edit box on the 'Send transaction' screen - replaced by the `0`

### Reproduction

- Open Status and log in to account
- Navigate to Wallet screen 
- Navigate to 'Send transaction' screen
- Type in the 'Specify amount' field dot value (`.`) and then `0` value

### Additional Information
* Status version: Latest develop (5ecdb1 (Android) / 0.9.11d616 (iOS), latest release 0.9.13
* Operating System: Android 7.0, iOS 11.2.2

TF session: https://app.testfairy.com/projects/4803590-status/builds/7578759/sessions/6/?accessToken=AMnR5hVBJG0vaOwnJiAfqtR3nrI

**Comment by goranjovic** [comment]
@Serhy As `0` is equal to `0.0`, I'm not quite sure what the problem is here. 

Maybe the key issue here is automatic truncation of zeros in trailing decimals. 
Say, what would you expect to happen if you type in 5.000 ?

**Comment by Serhy** [comment]
@goranjovic Typing `5.000` keep staying in the editbox as it is until focus put outside of the `Amount` editbox. Once the cursor is outside the `Amount` editbox  - the trailing decimals cut off. So `5.001000`- value parsed as `5.001`. That makes sense. 

There are two ways to enter numbers < 1.
 - Type `0`, then `.` and then the rest of digits 
 - Type `.`, and then the rest of digits 

In the last instance, there is a different behaviour in replacing the value in editbox when user enters `0` after a dot or any other figure other than `0`. E.g.:
* `Amount` field empty -> I type `.` then `1` -> the value replaced by `0.1` and I can proceed entering the values I need-> Expected
* `Amount` field empty -> I type `.` then `9` -> the value replaced by `0.9` and I can keep entering the values I need -> Expected
* `Amount` field empty -> I type `.` then `0` -> the value replaced by `0` and I have to understand that there is only way to enter `0.003`-amount like by having first `0` in editbox, then type `.` and then the rest of digits  -> Not Expected

**Comment by goranjovic** [comment]
@Serhy Ah ok, just tried it, I see the problem

**Comment by goranjovic** [comment]
@Serhy Let's agree  what should be the expected behavior:

1. We accept only one way to enter numbers - with the leading zero, e.g. 0.1 or 0.00001 and ensure it's consistent that way
2. We make 0 the default payment amount so that users can easily append the dot and decimals to it avoiding the initial situation
3. We remove the automated parse/replace behavior. Right now the amount is automatically reformatted to the canonical format whenever the underlying value changes. If we keep displaying the original format, the way user entered but actually use the canonical value in the underlying transaction.

My own preference is for (1) or (2) or rather against (3) since it's way too much logic over one number format that's probably not even used by many people. 

cc @denis-sharypin @hesterbruikman

**Comment by goranjovic** [comment]
Alternatively, we could agree on a default number of decimal places, too. E.g. always one or two digits after the point

**Comment by hesterbruikman** [comment]
I would always prefer user control in cases to do with money. So agree with 1 or 2 and not using the canonical value in the underlying transaction. This seems to lack transparency and is likely confusing when getting to the transaction overview.

Between 1 and 2 I would suggest 1 or an alternative to 1, using the most common format as a hint text. The median transaction value for ETH at the moment is 0.00074 ETH, so I suggest 0.0001 as a hint text.

**Comment by hesterbruikman** [comment]
At a more sophisticated level, we might want to consider adjusting the hint text/format to the selected currency. I'm not sure about this. Benefit is that it gives a sense of 'what's normal'. Downside is that this would create some inconsistency.

**Comment by goranjovic** [comment]
This issue is a special case of amount formatting bug, fixed by @mandrigin 

@Serhy do you mind verifying if it's fixed and if yes, we can close this.

**Comment by Serhy** [comment]
Latest nightly build (5aae87a), - confirmed as fixed! 
Awesome! Thanks, @goranjovic and @mandrigin !
Closing this issue.
