### ISSUE TITLE
Transaction failed 'known transaction' error on Wallet screen 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3156]
***Type***: Bug

***Summary***: Transaction failed: 'known transaction' error popup displayed on wallet screen. It was appeared on iPhoneX, however we can't reproduce it now. 

#### Expected behavior
No error "Transaction failed: 'known transaction''

#### Actual behavior
![wdfsdfsdf](https://user-images.githubusercontent.com/8749671/35481482-0206bebe-042d-11e8-8202-7b8edd35ac2c.JPG)

### Reproduction

- Open Status
- Navigate to Wallet screen
- Tap 'Send' to get on 'Send transaction' screen
- Choose 'Jarrad' as recipient
- Specify amount to `0.01`
- Sign this transaction

### Additional Information
* Status version: 0.9.13 (70th build in Jenkins)
* Operating System: iPhoneX with iOS 11.2.2

**Comment by asemiankevich** [comment]
agreed with @Serhy to close it as it is not reproducible for now
