### ISSUE TITLE
TypeError: null is not an object (evaluating 't.length') when 'Show QR' of DApp address 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3157]
***Type***: Bug

*Summary*: The `TypeError: null is not an object (evaluating 't.length')` error appears when request to 'Show QR code' for Address field is made from DApp profile. App is unresponsive and stays on white screen after I tap 'OK' on the pop-up with this error.
Same relates to 'Console' profile screen. 
Apparently we had the same issue in #2233 (second item from description)

#### Expected behavior
No error when 'Show QR code' for 'Address' is requested from DApp profile screen.

#### Actual behavior
`TypeError: null is not an object (evaluating 't.length')` error when 'Show QR code' for 'Address' is requested from DApp profile screen.
![asdasdasd](https://user-images.githubusercontent.com/8749671/35482475-9ad25264-043e-11e8-836c-f66090d81dcd.png)

### Reproduction

- Open Status
- On 'Chats' list screen tap `+` blue button
- From 'Start new chat' select 'Auction house'
- Close the opened browse screen appeared for 'Auction house'
- Tap on profile icon of DApp at the top-right and select 'Profile' option
- Select 'Show QR code' next to Address field

### Solution
At the moment 'Show AR code' is the only option on Address field of DApp's profile screen. As the possible solution we may just hide the three-dot button on Address field which opens 'Show QR code'. (note: it's for DApp and Console profiles only!)

### Additional Information
* Status version: latest develop (`0.9.11d617` iOS / `c41515` for Android) and Release 0.9.13
* Operating System: Android 7.0, iOS 11.2.2

TF session: https://app.testfairy.com/projects/4803590-status/builds/7587415/sessions/4/?accessToken=w3PveVV8j5oehgVyRjkOCekYYH8

**Comment by goranjovic** [comment]
This one is no longer reachable after a PR by @flexsurfer  There is no chat with dapps, so no way to reach the profile.

**Comment by jeluard** [comment]
@goranjovic Shall we close this?

**Comment by goranjovic** [comment]
Yeah, let's close it.
