### ISSUE TITLE
'Invalid URL: should be a string. Was: null' error is shown upon tap 'Open on etherscan.io' for unsigned transaction

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3161]
***Type***: Bug

***Summary***: 
1) `Invalid URL: should be a string. Was: null` error is shown upon tap on 'Open on Etherscan.io' for unsigned transaction's 'Transaction details' screen.
2) 'Not applicable for unsigned transactions' value has copied upon tap on 'Copy transaction hash' option for unsigned transaction's 'Transaction details' screen.

#### Expected behavior
To not show 'Open on Etherscan.io' and 'Copy transaction hash' options on 'Transaction details' screen for unsigned transaction. (See 'Solution' part)

#### Actual behavior
1) 'Not applicable for unsigned transactions' value has copied upon tap on 'Copy transaction hash' option for unsigned transaction's 'Transaction details' screen.

2) `Invalid URL: should be a string. Was: null` error is shown upon tap on 'Open on Etherscan.io' for unsigned transaction's 'Transaction details' screen.
<img width="296" alt="screen shot 2018-01-28 at 16 32 56" src="https://user-images.githubusercontent.com/8749671/35483299-fc546bd0-0448-11e8-944a-a0ef3829c330.png">

### Reproduction

- Open Status
- Navigate to Wallet -> Send transaction screen
- Select Jarrad as recipient, specify any valid amount (e.g. 0.1 ETH)
- Submit this transaction as 'SIGN LATER' 
- Navigate to transaction history -> Unsigned -> Transaction Details
- Tap on three-dot menu button at the top-right
- Tap on 'Copy transaction hash'
- Tap on 'Open on Etherscan.io'

### Solution
Both options, offered for unsigned transaction, brings nothing useful for user:
- 'Not applicable for unsigned transactions' is copied the default meaningful 'Hash' value we display on Transaction details screen for unsigned transaction. 
- No 'Hash' value for unsigned transaction -> nothing to use in URL to check in etherscan.io

As the fix here - we need just hide both options on Transaction details screen for any unsigned transaction. And so three-dot button also redundant in that case since it will show nothing upon tap (so to hide it as well). 
That was greed with design team. 
 

### Additional Information
* Status version: Release 0.9.13, latest develop (0.9.11d617 iOS / c41515 for Android)
* Operating System: Android 7.0, iOS11.2.2

TF session: https://app.testfairy.com/projects/4803590-status/builds/7587415/sessions/6/?accessToken=ftGk2JBkMyin3wP51EDdwVCjpm4

**Comment by goranjovic** [comment]
Closing since Unsigned transactions are no longer available in the app, so this can't happen any more.
