### ISSUE TITLE
npm install stuck on fresh install of Ubuntu 17.10.1 or Linux Mint 18.3

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#3166]
### Description
after cloning the repository and running `scripts/setup` it is stuck in npm install (high cpu load for like 6 hours without progress).
Wiki provided workaround (downgrade to npm@5.5.1) did not help.

### Reproduction
- install new Ubuntu 17.10.1 or Linux Mint 18.3
- clone repository
- run `scripts/setup`
- observe it stuck in `npm install`

**Comment by yenda** [comment]
I had the same problem Saturday, have you tried restarting your computer ? My problem was lack of ram

**Comment by ghost** [comment]
Restarting the computer - sounds like very windows-ish solution :D I tried rebooting :)
Actually of all things I have googled - one thing worked: to use "yarn install" instead of "npm install".

**Comment by audriu** [comment]
Do you think I am putting it to the wiki?
