### ISSUE TITLE
null is not an object (evaluating 'e.schema')

### ISSUE THREAD

**Issue by HofmannZ** [status-im/status-react#3170]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to add an additional account so that I can keep my assets separate.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I already had an account for a long time, I decided to test the setup flow to find possible bugs. After confirming my password I got an error message `null is not an object (evaluating 'e.schema')`. It did actually generate a passphrase and signing phrase and was even able to finish the phone verification.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
n.a.

#### Actual behavior
[comment]: # (Describe what actually happened.)
n.a.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create a second account
- Fill in a password
- Verify you password
- Get an error

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Investigate the bug
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.13 installed from TestFlight
[comment]: # (Android or iOS.)
* Operating System: iOS v11.2.5

### Screenshot
![img_0197](https://user-images.githubusercontent.com/17142193/35570356-429b5cc0-05cf-11e8-94e1-5a68d03ca2f7.png)

**Comment by oskarth** [comment]
Possible duplicate: https://github.com/status-im/status-react/issues/3069

**Comment by HofmannZ** [comment]
Please update the effected devices on #3069 and consider this issue closed.
