### ISSUE TITLE
Can return to Home after log out if tap device back button [android]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3172]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After user taps on log out it's still possible to return to Home and see chats if tap on device back button. It should not be possible. To see Home tab user needs to log in again

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
if tap on device back button after user logged out then same Sign in screen should be shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
if tap on device back button after user logged out then Profile tab is shown and it's possible to swith to other tabs and see/use chats
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
TF (00:19) https://app.testfairy.com/projects/4803622-status/builds/7593342/sessions/18/?accessToken=bLHV9vPSiihDLFAV03qgvylhkOE
- Open Status
- Sign in
- Open Profile
- Tap on log out
- On Sign in screen use device back button
- Check what screen is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build from January 30, 0.9.15
* Operating System: Android only

**Comment by yenda** [comment]
I will fix this one, I see @foopang made a PR for it but we will need a broader fix, we should get rid of accounts/accounts key in app-db and wipe the whole app-db on logout.

**Comment by foopang** [comment]
@yenda I am closing my PR then if you fix. Thanks!

**Comment by yenda** [comment]
@annadanchenko can we close this ? I believe it was fixed with the new protocol,

**Comment by annadanchenko** [comment]
can't reproduce on nightly build for Apr 17 on Android device. If tap on Back button after logout then app is put on background if switch back to the app then Sign in screen is shown with list of accounts
