### ISSUE TITLE
getting "web3 is not defined" error in webview on Android

### ISSUE THREAD

**Issue by grishick** [status-im/status-react#3174]
I am loading my DApp in webview on Android and getting error "web3 is not defined". This works fine on iOS, but latest playstore build for Android does not seem to inject web3.

**Comment by annadanchenko** [comment]
I've tried Status app from PlayStore (version 0.9.13) and can use Dapp Auction House to register name/send transaction. I also can send web3.eth.blockNumber in Console and get current block number. @grishick can you share your DApp url or provide more details, please?

**Comment by grishick** [comment]
@annadanchenko thanks for looking into this. Here is the code for my dapp https://github.com/grishick/turnsypwa/tree/develop, and here it is deployed: https://goo.gl/7Cu59M. I can see it load fine in Status on my iPhone 5SE, but on Android (Samsung J2) I get "web3 is undefined" error.

**Comment by grishick** [comment]
here's the error report from my ionic dashboard:

Exception Detail:
```
ReferenceError: web3 is not defined
```

at v.initAccount (providers/ethnetwork/ethnetwork.ts:103:11)
```
if(this.accountReady) {
  cb(null, this.myAddress);
} else {
  var context = this;
  if (web3) {
    if(typeof web3 !== 'undefined') {
      context.provider = web3.currentProvider;
      context.localEth = new Eth(context.provider);
```


at ? (pages/friends/friends.ts:54:27)

```
}
loadFriendList() {
  var context = this;
  context.ethProvider.initAll(function() {
    context.ethProvider.initAccount(function (error) {
      if (error) {
        console.log("Need to login");
      } else {
at e.http.get.map.subscribe.l [as _next] (providers/ethnetwork/ethnetwork.ts:77:13)
    requestedConfirmationEventTopic:data.requestedConfirmationEventTopic,
    token_name:data.token_name
  };
  console.log("Found coin contract at", context.ethContractMeta.address);
  cb();
} else {
  cb("FILE_NOT_FOUND");
}
```

**Comment by grishick** [comment]
I see that auction house works on my Android as well. Any idea what I am doing wrong?

**Comment by grishick** [comment]
strangely, this works in Toshi Dev on Android just fine. Only the Status webview gives me this trouble

**Comment by dmitryn** [comment]
Just tested sample DApp on Android emulator (genymotion) - it works fine for me.

<img width="1232" alt="screenshot 2018-02-02 14 23 22" src="https://user-images.githubusercontent.com/23836/35730899-d8793166-0824-11e8-9c72-e65a0304d500.png">

But i see errors loading "Turnsy" DApp

<img width="1235" alt="screenshot 2018-02-02 14 27 17" src="https://user-images.githubusercontent.com/23836/35731028-44913c5e-0825-11e8-9fab-d62f10223dde.png">

**Comment by dmitryn** [comment]
Seems like JS from https://github.com/status-im/status-react/blob/7e78acc0cc492951e299b73c83eb0b78d067275d/src/status_im/ui/screens/browser/views.cljs#L86-L88 not getting loaded for Turnsy DApp. 

It relates to the way how we inject JS into webview https://github.com/status-im/react-native-webview-bridge/blob/master/android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java#L487

My assumption that `shouldInterceptRequest` doesn't get triggered when requests come from ServiceWorker /cc @rasom not sure how well WebView and ServiceWorker work together.

I don't even see request for `https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/index.html` in 
WebViewBridgeManager logs:
```
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: new request
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: url https://api.ionicjs.com/monitoring/70677f09/u
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: host api.ionicjs.com
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: path /monitoring/70677f09/u
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: main false
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: headers {Access-Control-Request-Headers=content-type, Referer=https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/index.html, Origin=https://s3-us-west-1.amazonaws.com, Accept=*/*, User-Agent=Mozilla/5.0 (Linux; Android 7.1.1; Google Pixel XL - 7.1.0 - API 25 - 1440x2560 Build/NMF26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36, Access-Control-Request-Method=POST}
02-02 08:55:26.030 22521 22554 D WebViewBridgeManager: method OPTIONS
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager:
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: new request
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: url https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/assets/icon/favicon.ico
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: host s3-us-west-1.amazonaws.com
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: path /turnsy/dapp/www/assets/icon/favicon.ico
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: main false
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: headers {Accept=*/*, User-Agent=Mozilla/5.0 (Linux; Android 7.1.1; Google Pixel XL - 7.1.0 - API 25 - 1440x2560 Build/NMF26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36, Referer=https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/index.html}
02-02 08:55:26.036 22521 22554 D WebViewBridgeManager: method GET
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager:
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: new request
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: url https://api.ionicjs.com/monitoring/70677f09/u
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: host api.ionicjs.com
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: path /monitoring/70677f09/u
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: main false
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: headers {Referer=https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/index.html, Origin=https://s3-us-west-1.amazonaws.com, Accept=*/*, Content-Type=application/json, User-Agent=Mozilla/5.0 (Linux; Android 7.1.1; Google Pixel XL - 7.1.0 - API 25 - 1440x2560 Build/NMF26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36}
02-02 08:55:29.163 22521 22554 D WebViewBridgeManager: method POST
```

For example, debug log from sample DApp:
```
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: new request
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: url http://nifty-goldwasser-f53eed.bitballoon.com/
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: host nifty-goldwasser-f53eed.bitballoon.com
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: path /
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: main true
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: headers {Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, User-Agent=Mozilla/5.0 (Linux; Android 7.1.1; Google Pixel XL - 7.1.0 - API 25 - 1440x2560 Build/NMF26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36, Upgrade-Insecure-Requests=1}
02-02 08:56:50.114 22521 22554 D WebViewBridgeManager: method GET
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: response headers Cache-Control: public, max-age=0, must-revalidate
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Content-Type: text/html; charset=UTF-8
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Date: Fri, 02 Feb 2018 13:56:56 GMT
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Etag: "49df7a2d38f64b1f4bf64d4a1751be39-ssl-df"
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Age: 1
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Connection: keep-alive
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Server: Netlify
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: Vary: Accept-Encoding
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: response code 200
02-02 08:56:56.890 22521 22554 D WebViewBridgeManager: response suc true
```
As you see from last line, this request is considered succesful and we proceed with JS injection.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-webview-bridge">status-im/react-native-webview-bridge</a></strong></div><div>react-native-webview-bridge - React Native Webview with Javascript Bridge </div></blockquote>

**Comment by antecasa** [comment]
any update on this issue

**Comment by dmitryn** [comment]
@antecasa no updates so far. 

But i think this might be a direction to work on https://developer.android.com/reference/android/webkit/ServiceWorkerController.html
```
 ServiceWorkerController swController = ServiceWorkerController.getInstance();
 swController.setServiceWorkerClient(new ServiceWorkerClient() {
   @Override
   public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
     // Capture request here and generate response or allow pass-through
     // by returning null.
     return null;
   }
 });
```

As far as i could tell, we need to intercept requests inside `shouldInterceptRequest` for Service Worker the same way we do with regular requests https://github.com/status-im/react-native-webview-bridge/blob/react-native-0.49/android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java#L455

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1449.53
Contract address: [0x0f27ab0cbea63ba26724430062ae6a3dae722ce3](https://etherscan.io/address/0x0f27ab0cbea63ba26724430062ae6a3dae722ce3)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dmitryn** [comment]
Hi @grishick ! 

I've just checked your DApp and it seems loading without errors. I do see web3 object in Chrome console when loading https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/index.html.

Console log:

<img width="616" alt="screenshot 2018-04-10 15 45 01" src="https://user-images.githubusercontent.com/23836/38557659-5b9c7658-3cd6-11e8-9456-55f5ecb407be.png">

How page looks like:

<img width="416" alt="screenshot 2018-04-10 15 45 08" src="https://user-images.githubusercontent.com/23836/38557677-67210c28-3cd6-11e8-8f19-a7d5cd8fd4b1.png">

Please check if it works on your side.

NOTE: I'm using Ethereum mainnet.

<blockquote><div><strong><a href="https://s3-us-west-1.amazonaws.com/turnsy/dapp/www/index.html">Ionic App</a></strong></div></blockquote>

**Comment by dmitryn** [comment]
On Ropsten it still has no access to web3:

<img width="626" alt="screenshot 2018-04-11 15 08 20" src="https://user-images.githubusercontent.com/23836/38615731-638f0208-3d9a-11e8-83ab-f605e53e309c.png">

@grishick what network does your ÐApp support?

**Comment by dmitryn** [comment]
Actually, it's not network (ropsten,mainnet,etc) related. 
This bug is non-deterministic – sometimes web3 object is successfully injected, sometimes not. Needs more debugging.

**Comment by dmitryn** [comment]
It only works well when you uninstall Status, install again and open this DApp. 
On second run it doesn't inject web3 for some reason. Removing DApp from DApp list on Home screen and opening it again doesn't help either.

**Comment by dmitryn** [comment]
>this works in Toshi Dev on Android just fine.

Doesn't work in Toshi on second run as well. DApp loads with web3 on first run only (same as in Status).
