### ISSUE TITLE
Accents characters (è, ù) in webview are shown as question marks [Android]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3175]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: Only on Android: accents characters (è, ù) are shown as question marks on webpages if opened in Status app. Same pages if open on same device via Chrome or Android Web browser look ok.
![screenshot!UNITO-UNDERSCORE!20180131-101709](https://user-images.githubusercontent.com/6584810/35615123-874649a0-0671-11e8-89fb-0db167572e98.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Accents characters (è, ù) on webpages are shown

#### Actual behavior
[comment]: # (Describe what actually happened.)
Accents characters (è, ù) are shown as question marks

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803622-status/builds/7599983/sessions/2/?accessToken=-jxDfarrj/ngtQ3frMvmYZLejaw

* Open Status and sign in
* Tap on + to open "Start new chat" screen
* Tap on Open URL
* paste this url http://www.lantidiplomatico.it/dettnews-un_eroismo_sovrumano_anche_per_i_nemici_il_ruolo_poco_conosciuto_dellurss_nella_seconda_guerra_mondiale/11_22978/ and tap on checkmark on keyboard
* After page is loaded check if there are any question marks shown instead of characters in the article text

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly build from January 31. 0.9.10-621-g8f1bc58b+
* Operating System: Android only. Real Samsung Galaxy S6, Android 6.0.1 and Google Pixel XL, Android 8.1.0

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x5f7195c29c3e507ae053f2561fa0521b0417e42422483a3bac69ff3c38e75d7c](https://etherscan.io/tx/0x5f7195c29c3e507ae053f2561fa0521b0417e42422483a3bac69ff3c38e75d7c)

**Comment by trowacat** [comment]
Does this still need to be worked on?

**Comment by annadanchenko** [comment]
can reproduce on Google pixel xl, android 9
can't reproduce on Galaxy S6, Android 6.0.1

**Comment by annadanchenko** [comment]
can reproduce on Google pixel xl, android 9 
Release 0.11.0 of mobile app

**Comment by KubebatHaMachatz** [comment]
Do you still need help with this issue? it looks like an encoding issue.

**Comment by churik** [comment]
still relevant on Status 1.0.1 (Android10)

**Comment by cammellos** [comment]
can't replicate, closing for now, feel free to re-open

**Comment by churik** [comment]
still the case on Android 10, status 1.6.1

**Comment by churik** [comment]
not relevant anymore
