### ISSUE TITLE
icon_public-chat and icon_group-chat on Home screen view are not aligned with chat name text

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3176]
***Type***: Bug

*Summary*: The icon_public-chat and icon_group-chat on Home screen view are not aligned with the respective chat name. Additionally, on Android the icon_group-chat looks cut off. 
The icon alignment should be made for both Android and iOS.

Android current view:
![screenshot_20180131-114801](https://user-images.githubusercontent.com/8749671/35616188-2f373240-067d-11e8-8f5f-fd6c68c10839.png)

iOS current view:
![image uploaded from ios 1](https://user-images.githubusercontent.com/8749671/35616205-3ac95eb2-067d-11e8-9041-885a807d4705.png)

And mockups representing the alignment:
<img width="361" alt="screen shot 2018-01-31 at 11 33 25" src="https://user-images.githubusercontent.com/8749671/35615472-e4c299ae-067a-11e8-8685-e3a7d02d9121.png">

<img width="362" alt="screen shot 2018-01-31 at 11 33 11" src="https://user-images.githubusercontent.com/8749671/35615501-f89264e6-067a-11e8-9e1b-25884d9a53ac.png">

#### Expected behavior
icon_public-chat and icon_group-chat are aligned with the chat name on Home screen
#### Actual behavior
icon_public-chat and icon_group-chat are not aligned with the chat name on Home screen

### Reproduction

- Open Status
- Create public chat and GroupChat and navigate to Home screen
- Check the icon_public-chat and icon_group-chat alignment 

### Additional Information
* Status version: Develop 8f1bc5 / 0.9.11d621 (31st of January)
* Operating System: Android 7.0, iOS 11.2.2 (iPhoneX)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0xf10343a344a14443bab0852cf0085600ed463873](https://etherscan.io/address/0xf10343a344a14443bab0852cf0085600ed463873)
Network: Mainnet
Paid to: TheCriw
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by flexsurfer** [comment]
@Serhy and also icon color should be different
