### ISSUE TITLE
Back button doesn't work on 'New group chat' screen

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3178]
***Type***: Bug 

***Summary***: Nothing happens when I tap `<` Back button on the 'New group chat' screen with the list of contacts to add. 
Note: it's works fine for 'Join public chat' and 'Add new contact' screen. And the bug is not present in 0.9.13 release.

#### Expected behavior
I navigate back to 'Start new chat' when I tap `<` Back button on the 'New group chat' screen

#### Actual behavior
Nothing happens when I tap `<` Back button on the 'New group chat' screen with the list of contacts to add. 

### Reproduction

- Open Status
- From Home screen tap `+` button to add new chat
- Tap 'New group chat'
- Tap `<` back button at the top-left

### Additional Information
* Status version: develop 0.9.10-621-g8f1bc58b+ / 0.9.11d621 (31st of January)
* Operating System: Android 7.0, iOS 11.2.2

TF session: https://app.testfairy.com/projects/4803622-status/builds/7599983/sessions/6/?accessToken=ksYTsGPrYz2bmoThK-uZNoMKy2k

**Comment by alwx** [comment]
I already fixed it here: https://github.com/status-im/status-react/pull/3173

**Comment by chadyj** [comment]
Closing since @alwx fixed it.
