### ISSUE TITLE
discover screen doesn't get populated when status changes?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#318]
When user changes Status, the Discover screen should autopopulate with their status, even if it's the only status available it should appear in popular cards and recent list immediately.

Online contacts should also be notified of the status update, this was working before but doesn't appear to be in `develop`

Steps to reproduce
- run instance of status on ios and android
- add contact (scanned qr code from profile)
- chat with each other to confirm connectivity
- android device goes to profile, changes status to "buy some #butter"
- on android device goto discovery screen, it's in blank state
- on ios device goto discovery screen, it's in blank state
- conform chat communication between both devices

**Comment by rasom** [comment]
```
When user changes Status, the Discover screen should autopopulate with their status, even if it's the only status available it should appear in popular cards and recent list immediately.
```
^ Does it mean that user will see his own status on Discovery screen?

**Comment by jarradh** [comment]
yes
