### ISSUE TITLE
No italic font in messages in 1-1, group and public chats for text wrapped up in tildes [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3180]
***Type***: Bug

***Summary***: Text wrapped up in tildes not displayed with italic font style in 1-1 chat, group and public chats for iOS. 
It's all fine for Android and text in message bubbles like `~ItalicText~` -> displays as _ItalicText_

#### Expected behavior
Text in message bubble wrapped up in tildes displayed with italic font style in 1-1, group and public chats on iOS

#### Actual behavior
Text in message bubble wrapped up in tildes **not** displayed with italic font style in 1-1, group and public chats on iOS

See screens from 1-1 chat of Android user and iOS user:

iOS screen:
![image uploaded from ios 2](https://user-images.githubusercontent.com/8749671/35621994-fab53c76-068e-11e8-91c9-bb2ead90271d.png)

And same chat on Android screen (where it's all fine):
![androidviewscreenshot_20180131-135643](https://user-images.githubusercontent.com/8749671/35622018-0cbfa276-068f-11e8-80ce-ebdea90f6307.png)

### Reproduction

- Open Status
- Start 1-1 chat with Jarrad contact
- Sent text message wrapped up in tildes (e.g.` ~This is a text with italic font~`)
- Check if the text in message bubble with italic font style

### Additional Information
* Status version: Develop (0.9.11d621),  Release 0.9.13 
* Operating System: iOS 11.2.2 (iPhoneX used)

**Comment by nikitalukianov** [comment]
@Serhy , can we use this lib? https://github.com/chirag04/react-native-tooltip

**Comment by Serhy** [comment]
Reproduced with 0.9.26 Release app version

**Comment by SlizkovaGanna** [comment]
This issue is no longer valid - a different one was created :)
https://github.com/status-im/status-react/issues/6361
Tested on Release 0.9.30 (10755) - a nightly from 17 Oct 2018
