### ISSUE TITLE
Script to measure bounties issued over time period

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#3193]
### User Story

As a dev interested in improving monthly active contributors, I want to see and encourage people who post bounties.

As a dev interested in posting more bounties, I want to see how I'm doing over time so I feel incentivized to post more bounties.

### Description

*Type*: Feature/Tooling

*Summary*: Write a script that outputs a CSV to STDOUT with format something like `PERIOD, GITHUB_NAME, BOUNTIES_POSTED`. This will later be used in a spreadsheet to check (opt-in) bounties posted over some timeframe, such as per week.

PERIOD could be either a specific date or a weekly period such as 2018-01-01-2018-01-08 (e.g.).

### Solution

Inspiration from https://github.com/status-im/status-react/blob/develop/scripts/pr-statistics.sh

Should check issues in a given repo (such as status-react) or over a whole organization. Count issues with `bounty` label. Ideally it should be based on who adds the `bounty-awaiting-approval` label first, but it can also be based on who made the issue that has the `bounty` tag on it.

### Size

Not sure if it is a small or medium bounty.

**Comment by oskarth** [comment]
Might be small one, not sure.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbc14001ac6ef0c7c290aa1b2fbc71e043a5c1731bfaf53da338b01d492bc62e4](https://etherscan.io/tx/0xbc14001ac6ef0c7c290aa1b2fbc71e043a5c1731bfaf53da338b01d492bc62e4)

**Comment by StudioEtrange** [comment]
Hello

> Ideally it should be based on who adds the bounty-awaiting-approval label first, but it can also be based on who made the issue that has the bounty tag on it.

So, which one to use ? In which case we should use the people who create the issue or put the bounty label on the issue ?

Can you describe more clearly the different cases please ?

**Comment by oskarth** [comment]
> Ideally it should be based on who adds the bounty-awaiting-approval label first, but it can also be based on who made the issue that has the bounty tag on it.

> So, which one to use ? In which case we should use the people who create the issue or put the bounty label on the issue ?

Both solutions are acceptable, but the former is better. They aren't different cases as much as different ways of solving the same problem (trade-off: ease of implementation vs accuracy).

**Comment by chuck-sys** [comment]
Would there be multiple `GITHUB_NAME`s per time range? Or would there be a single `GITHUB_NAME` within a bounded time range, but multiple time ranges with different `GITHUB_NAME`s?

So, something like this:

```csv
PERIOD,GITHUB_NAME,BOUNTIES_POSTED
2018-01-01-2018-01-08,oskarth StudioEntrange,5
```

Or like this:
```csv
PERIOD,GITHUB_NAME,BOUNTIES_POSTED
2018-01-01-2018-01-08,oskarth,3
2018-01-01-2018-01-08,StudioEntrange,2
```
