### ISSUE TITLE
Script to measure active contributors over time

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#3194]
### User Story

As a dev interested in improving monthly active contributors, I want to measure it to see how we are doing. See https://wiki.status.im/Status_Organisational_Design#Goals_of_Organisation

### Description

*Type*: Feature/Tooling

*Summary*: Write a script that outputs a CSV to STDOUT with format something like `PERIOD, GITHUB_NAME, COMMITS*`. This will later be used in a spreadsheet to check regular committers over some timeframe, such as per month.

*Commits is just one form of contribution. Further iteration might capture things like reviews and issue comments. If this is straightforward to add that'd be a great bonus too :)

It'd also be OK to measure COMMIT as just y/n since primary importance is on monthly activity contributors, not on specific number of commits for one contributor.

PERIOD could be either a specific date or a weekly period such as 2018-01-01-2018-01-08 (e.g.). By default week or month seems reasonable. Similar to: https://github.com/status-im/status-react/pulse

Example:

```
2017-11-01-2017-12-01, foo, 10
2017-11-01-2017-12-01, bar, 1
2017-12-01-2018-01-01, foo, 5
2017-12-01-2018-01-01, quux, 2
2017-12-01-2017-01-01, bar, 1
```

### Size

Not sure if it is a small or medium bounty.

**Comment by mandrigin** [comment]
There are https://github.com/arzzen/git-quick-stats or `git-fame` that do similar things.

<blockquote><img src="https://avatars0.githubusercontent.com/u/6382002?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/arzzen/git-quick-stats">arzzen/git-quick-stats</a></strong></div><div>git-quick-stats - ▁▅▆▃▅ Git quick statistics is a simple and efficient way to access various statistics in git repository.</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 450.00
Contract address: [0x3fb20e7adab0c23e26624d4bc739e2fd5bcfaadb](https://etherscan.io/address/0x3fb20e7adab0c23e26624d4bc739e2fd5bcfaadb)
Network: Mainnet
Paid to: pablanopete
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by oskarth** [comment]
Already solved internally. @andytudhope we can remove this one
