### ISSUE TITLE
Not aligned 'Share' icon, no shadow on app top bar, contact name is not in bold - on QR code screens

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3196]
***Type***: Bug

***Summary***: There are UI issues on both public key and address QR code screens:
1) ~On **iOS and Android** there is a black status bar~ (moved into separate issue #3227)
2) On Android only there is no shadow at the bottom line of app top bar
3) On iOS only the 'Share' icon should be aligned to the right to 12px
4) On iOS only - the contact name is not in the bold font style

**iOS screen:**
<img width="722" alt="ios" src="https://user-images.githubusercontent.com/8749671/35742964-ce121808-0844-11e8-80a3-5e36a87bbad9.png">

**Android screen:**
<img width="853" alt="andoro" src="https://user-images.githubusercontent.com/8749671/35742978-da6dc2fa-0844-11e8-8abd-2f2461583c8e.png">

#### Expected behavior
Aligned Share icon to the right with 12 px, shadow at the bottom line of app top bar on Android, bold font of contact name on iOS - on the QR code screens
#### Actual behavior
Not aligned Share icon to the right on iOS, no shadow at the bottom line of app top bar on Android, no bold font of the contact name on iOS - on the QR code screens

### Reproduction
- Open Status and create account
- Navigate to Profile -> Share my contact code screen (Note: this is for public key QR screen)
- Navigate to Home -> Start new chat -> 1-1 chat with Jarrad -> Profile screen at top-right -> Show QR code for Address

### Additional Information
* Status version: Develop 0.9.11d626 (iOS) / 03e625 (Android) 
* Operating System: Android 7.0 (Samsung J7 real device), iOS 11.2.2 (iPhoneX)

**Comment by jeluard** [comment]
@Serhy Could we split status-bar issue to a separate ticket? Those will require some more global thinking.

**Comment by Serhy** [comment]
@jeluard Done. #3227 created as separate for status-bar issue

**Comment by Serhy** [comment]
#3247 fixed it. Closing the issue.
