### ISSUE TITLE
Review status-im.ui.components.chat-icon.screen and introduce one universal component for contact's "icon" 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#3205]
Problem:
`status-im.ui.components.chat-icon.screen` ns  out of date and can be simplified 

Introduce components in ui ns
something like `[contact-icon contact {:size 56}]` and `[chat-icon chat {:size 56}]`
 
https://github.com/status-im/status-react/pull/3195#discussion_r165902528

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9b5733c1e3afbf8aa44df5e5e4fec4f19202587a0a7f67c66f36ae7e72841ee4](https://etherscan.io/tx/0x9b5733c1e3afbf8aa44df5e5e4fec4f19202587a0a7f67c66f36ae7e72841ee4)

**Comment by oskarth** [comment]
@flexsurfer Can we please put the problem in issue as opposed to using a pointer to some comment?

**Comment by pablanopete** [comment]
@flexsurfer is this issue still relative? Could we re-bounty it?

**Comment by flexsurfer** [comment]
@pablanopete it's not, we can close it, thanks
