### ISSUE TITLE
Introduce common styles for labels

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#3206]
Problem: We have a lot of duplication in styles for text components

Introduce common styles , and use these styles for all text components in code

https://github.com/status-im/status-react/pull/3195#discussion_r165903231

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x26c661bd04c2f74c259cf32cd6ee69b7d467a3153ecc5bedc85e33a3a6d06b24](https://etherscan.io/tx/0x26c661bd04c2f74c259cf32cd6ee69b7d467a3153ecc5bedc85e33a3a6d06b24)

**Comment by oskarth** [comment]
Same here, not clear what acceptance criteria is
