### ISSUE TITLE
[Perf] Test hypothesis 7: Use another JS thread for heavy computations

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#3211]
### Identified Behavior

Sometimes view rendering is slow as main thread is occupied with heavy computations. As an example, account creation process is slow and laggy, message could appear in slow motion, etc.

### Hypothesis

Using another JS thread to do heavy computations could free main JS thread to do UI related computations (subscriptions, hiccup rendering, react diffs, etc).

### Assumptions

Main JS thread responsible for UI rendering is sometimes occupied by other computations which prevents UI to be updated smoothly.

### Metrics

As UI metric we could use https://github.com/status-im/status-react/issues/3111 to test against. Moving heavy computations to another thread should let UI render smooth during account creation.

### Acceptance criteria

- [ ] Spawning second JS thread works on both Android and iOS
- [ ] App memory usage doesn't grow much and stay within accepted range (to be defined)
- [ ] Ability to run any ClojureScript code on another thread.

### Notes
Among many libraries that implement RN threading capabilities , this library seems good to try for our needs https://github.com/joltup/react-native-threads

Also,  https://github.com/seantempesta/cljsrn-re-frame-workers could provide insights on how to use ClojureScript with RN threads (workers) library.

**Comment by dmitryn** [comment]
Closing for now. 
We planned to use it to run Realm operations on another thread, but this seems have no significant impact on performance and work needed to be done not worth possible perfomance benefits. 
Thanks @rasom for researching this hypothesis.

**Comment by oskarth** [comment]
@mandrigin @rasom @janherich maybe worth revisiting this approach, wdyt?
