### ISSUE TITLE
Question mark is missing on Gas details screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3214]
### Description

*Type*: Bug

*Summary*: Add `?` mark (hint) in oval as shown on the mocks below

## Android:

![image](https://user-images.githubusercontent.com/28752642/35810259-3429f3dc-0a9c-11e8-8701-6fec0c3aa5d4.png)

![image](https://user-images.githubusercontent.com/28752642/35810285-51b644b4-0a9c-11e8-8995-8720c200b38c.png)

## iOS

![image](https://user-images.githubusercontent.com/28752642/35810311-6b502778-0a9c-11e8-9b49-4e99bd302f11.png)

![image](https://user-images.githubusercontent.com/28752642/35810333-7b7145ba-0a9c-11e8-8fc6-d710de5b44a5.png)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction

- Open Status
- Tap Wallet
- Tap Send -> Advanced -> Transaction Fee

### Additional Information
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 807.57
Contract address: [0x1ef968d03fdd187f55c36f3f705d724b97873578](https://etherscan.io/address/0x1ef968d03fdd187f55c36f3f705d724b97873578)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
