### ISSUE TITLE
Transaction Fee screen does not fit mocks

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3221]
### Description

*Type*: Bug

*Summary*: Adjust Transaction Fee screen to make it pixel perfect to mocks
#### Expected behavior

1. Done button is present on Gas details screen and is garded-out when no changes done
2. Done button is present and active when user has made some changes 
3. Footer line is present at the bottom of the screen
4. Line and button match mocks
5. Line under header for iOS is present and matches mocks
6. Amount , Gas limit, Gas Price and Total fee boxes match mocks. Text inside the boxes is Left-aligned

![image](https://user-images.githubusercontent.com/28752642/35850141-e4314814-0b34-11e8-8326-278114dc21e6.png)

## iOS

![image](https://user-images.githubusercontent.com/28752642/35850187-0ba765c2-0b35-11e8-93c9-8786256f1678.png)

![image](https://user-images.githubusercontent.com/28752642/35848328-d0142cd0-0b2e-11e8-804b-c3e825637d8f.png)

![image](https://user-images.githubusercontent.com/28752642/35848410-23daba00-0b2f-11e8-9061-d78846c20f06.png)

![image](https://user-images.githubusercontent.com/28752642/35850050-a8cebfea-0b34-11e8-81ee-abaf50855243.png)

![image](https://user-images.githubusercontent.com/28752642/35850271-41e0caca-0b35-11e8-9fb7-7f974c4f51a5.png)

![image](https://user-images.githubusercontent.com/28752642/35850283-4ca9a2d8-0b35-11e8-89ef-da8f1150e781.png)

![image](https://user-images.githubusercontent.com/28752642/35850383-ac0e8626-0b35-11e8-9c93-a17b3433e085.png)

![image](https://user-images.githubusercontent.com/28752642/35850391-b4a24bf6-0b35-11e8-8333-743dfeb3ae53.png)

## Android

![image](https://user-images.githubusercontent.com/28752642/35848348-e343beba-0b2e-11e8-9085-fa3068c03761.png)

![image](https://user-images.githubusercontent.com/28752642/35848427-33c6bf86-0b2f-11e8-926e-0235f064e763.png)

![image](https://user-images.githubusercontent.com/28752642/35850067-b781b1d2-0b34-11e8-8e40-16912bad7e42.png)

![image](https://user-images.githubusercontent.com/28752642/35850300-5eaa3c0e-0b35-11e8-9c15-9a9aaeffb82b.png)

![image](https://user-images.githubusercontent.com/28752642/35850309-6679ff8c-0b35-11e8-9f67-4d8cfb5672fd.png)

![image](https://user-images.githubusercontent.com/28752642/35850400-c09f0002-0b35-11e8-9eba-65614c8fe60a.png)

![image](https://user-images.githubusercontent.com/28752642/35850409-c7572276-0b35-11e8-9a19-6654b5069f74.png)

### Reproduction
- Open Status
- Tap wallet
- Tap send transaction
- Tap Advanced
- Tap Transaction fee

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8b9eee13517ac85d527038f1b2d93d26ecf41bdc221cb34c6fe2c0105a88616f](https://etherscan.io/tx/0x8b9eee13517ac85d527038f1b2d93d26ecf41bdc221cb34c6fe2c0105a88616f)

**Comment by lukaszfryc** [comment]
Here is a related UI bug. Would be good to fix it (truncate long text "...") as part of the issue. 
  
<img src="https://user-images.githubusercontent.com/7532782/37960771-c22b55e0-31b6-11e8-9f63-ae01cf6e0504.png" width="300">

**Comment by asemiankevich** [comment]
@lukaszfryc this is a separate issue already for this https://github.com/status-im/status-react/issues/3911

**Comment by asemiankevich** [comment]
@pablanopete revoke the bounty here please and close the issue. Thanks
