### ISSUE TITLE
Enter contact code screen does not fit mocks on iOS

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3223]
### Description

*Type*: Bug

*Summary*: Adjust the screen to match mocks

#### Expected behavior

1. Text box

![image](https://user-images.githubusercontent.com/28752642/35851376-f2855a14-0b38-11e8-8bbc-d670bb791acf.png)

2. Text alignment
![image](https://user-images.githubusercontent.com/28752642/35851363-e8eb9f72-0b38-11e8-9a59-aef9c46bfe49.png)

3. Header line

![image](https://user-images.githubusercontent.com/28752642/35851416-00eb60f8-0b39-11e8-9e62-c4f3127adf90.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/35851478-3684e2fc-0b39-11e8-93ce-787322e41cd6.png)

### Reproduction
- Open Status
- Tap wallet
- Tap Specify recipient
- Tap enter contact code

### Additional Information
* Status version: develop
* Operating System: iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 240.00
Contract address: [0x0ed67228241801ff8270db0b3ec1958f5900db47](https://etherscan.io/address/0x0ed67228241801ff8270db0b3ec1958f5900db47)
Network: Mainnet
Paid to: dongwoo-kim
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dongwoo-kim** [comment]
Hi @asemiankevich, I'm working on this issue. 
I can understand the (1) Text box and (2) Text alignment, but (3) Header line is not clear to me.
I found that other pages in the wallet tab has no header line, although looks very similar. 
Is it OK for only this page to have a header line?

**Comment by asemiankevich** [comment]
Hello @dongwoo-kim the line under header for Recipient screen should be present for iOS according to the mocks attached

**Comment by dongwoo-kim** [comment]
@asemiankevich Thanks. I just made a PR for this.
