### ISSUE TITLE
Introduce label component

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#3226]
`[react/text {:style styles/total-balance-currency} (i18n/label :t/usd-currency)]]` - thats how we develop labels

Problems
1) noisy, because style object and i18n/label
2) impossible to search translation key usage because `:t`
3) requires `i18n/label`

Introduce label component
`[label styles/total-balance-currency :usd-currency]`
`[label :usd-currency]` - default , most usable style should be used (https://github.com/status-im/status-react/issues/3206)

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 480.00
Contract address: [0xee03fd07483872937c79a99b48c6814c43d4638e](https://etherscan.io/address/0xee03fd07483872937c79a99b48c6814c43d4638e)
Network: Mainnet
Paid to: cheukyin699
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by chuck-sys** [comment]
I'm currently working on this. But say for instance besides a `:style` there is also an `:on-press` key. Should the component also handle these, or should it only handle the default, where only `:style` is specified?

**Comment by flexsurfer** [comment]
hey @cheukyin699 , thanks for working on this, what do you mean about `:on-press` key, could you provide an example? thanks
