### ISSUE TITLE
New home Add button does not match mocks (iOS)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3229]
### Description

*Type*: Bug

*Summary*: New home Add button does not match mocks

#### Expected behavior

![image](https://user-images.githubusercontent.com/28752642/35859938-25719fd6-0b53-11e8-8cbb-61170ba587e7.png)

![image](https://user-images.githubusercontent.com/28752642/35859947-3057b8fe-0b53-11e8-97ad-f18f2cca7986.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/35859958-3d18865e-0b53-11e8-8bdb-80002837807e.png)

### Reproduction

- Open Status
- Tap Home tab

### Additional Information
* Status version: develop
* Operating System: iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0x2465ba86150fb8e2a64c5631fee545dad588b5e5](https://etherscan.io/address/0x2465ba86150fb8e2a64c5631fee545dad588b5e5)
Network: Mainnet
Paid to: KatieStarks
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
