### ISSUE TITLE
Implement theme support for components

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3230]
### User Story

As a developer, I want to have theme support for my component
### Description

*Type*: Feature

Most component are defined with white background in mind. Some screens (e.g. `wallets`) have dark backgrounds.

It should be possible to define themes (like `background-color`, `text-color`) that could be externally applied to whole screen without having to modify each component.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x80bed170094cedcec0f0fea609c5e92dc9c7cd7958bac9c8c92703acef657c6e](https://etherscan.io/tx/0x80bed170094cedcec0f0fea609c5e92dc9c7cd7958bac9c8c92703acef657c6e)
