### ISSUE TITLE
Profile picture can't be set - nothing happens if select from gallery and crash if use capture

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3232]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In profile: 
1. If select picture from gallery then it's not updated on profile, so sema system-generated picture is shown instead of selected picture
2. If use Capture then app crashes
``` com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `null'
	at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
	at com.lwansbrough.RCTCamera.RCTCameraModule.processImage(RCTCameraModule.java:585)
	at com.lwansbrough.RCTCamera.RCTCameraModule.access$200(RCTCameraModule.java:38)
	at com.lwansbrough.RCTCamera.RCTCameraModule$3$1.run(RCTCameraModule.java:539)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)```
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
User can set new profile picture by selecting it from Gallery or by using Capture (to create new picture)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
from 27:00 https://app.testfairy.com/projects/4803622-status/builds/7647839/sessions/5/?accessToken=cs1T3CUsir4hKQNSU3O4R46uNkw
- Open Status
- Open Profile
- Tap Edit in top right corner
- Tap on Edit in Profile picture circle
- Agree to give access to the pictures (if it's first time)
- Tap on Select from gallery
- Select some picture
- Tap on checkbox in top right corner -> Expected that picture will change to new one but it stays old
- Tap on in top right corner
- Tap on Capture
- Tap on camera icon -> app crashed

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightly build from Feb 6,  0.9.10-637-g790655b6+ (2194) 
* Operating System: real Android and iOS devices:
Pixel XL, Android 8.0.1
iPhone 6s

**Comment by feuGeneA** [comment]
Also this after dismissing error listed in OP. Though it might help.
![ascreenshot_20180209-083441](https://user-images.githubusercontent.com/7883777/36030318-af24a084-0d74-11e8-8f2b-0049e385c2b1.png)
