### ISSUE TITLE
Clean app DApps list, leave only working DApps

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3240]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I don't want to be confused with non-working DApps opened from Status app. So, we need to remove DApps that are no longer working in Testnet

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
Remove these DApps from the list, because they are no longer available (oops, error or 404 error is shown if try to open them):
- bchat
- Dentacoin
- Gnosis
- Melonport
- Oaken Water Meter

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
All DApps in the Contacts list can be loaded
#### Actual behavior
[comment]: # (Describe what actually happened.)
404 error or oops, error or other errors are shown if try to open 
- bchat
- Dentacoin
- Gnosis
- Melonport
- Oaken Water Meter
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open list of DApps
- Tap on each DApp and check that its page is shown in the browser

version: 0.9.13 release

**Comment by annadanchenko** [comment]
@rasom re-checked the DApps list and more should be removed:
- Ethcro does not load on iOS, 
- Augur - can’t connect account from Status, 
- Maker Market - when open in Status says Not Connected to Ethereum.

**Comment by rasom** [comment]
ok, thanks
