### ISSUE TITLE
Adjust Default Gas price to the lowest Standard instead of using hardcoded 21 Gwei

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3241]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a  user, I want to send ETH so that I do not pay high Gas price and I do not need to adjust it manually each time

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, Gas price is hardcoded to 21 Gwei. We need to adjust it and use lowest Standard price of mainnet.  There is a JSON-RPC method to get the current gas price https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gasprice that can be used

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Gas price is adjusted to match current lowest Standard price
#### Actual behavior
[comment]: # (Describe what actually happened.)
Gas price is hardcoded and is always 21 Gwei, so user need to go to wallet and manually adjust it for each transaction. 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Wallet
- Send Transaction
- Open Advanced
- Tap on field with fee
-On Transaction Fee screen check Gas Price

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.13 and develop build 
* Operating System: Android and iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3f9e972dcc8672d8cdd40948777f37300bcd83290e9993975812e4446ee69532](https://etherscan.io/tx/0x3f9e972dcc8672d8cdd40948777f37300bcd83290e9993975812e4446ee69532)

**Comment by jeluard** [comment]
`go-ethereum` will [adapt](https://www.ethnews.com/ethereum-foundations-nick-johnson-on-gwei-transaction-fees) it's estimation algorithm in the short term.
Current approach seems to be sufficient.

**Comment by asemiankevich** [comment]
@annadanchenko agree to close?

**Comment by andytudhope** [comment]
@annadanchenko let me know if this needs to be re-opened.
