### ISSUE TITLE
Can't remove participants in a group chat (iOS)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3244]
### Description

*Type*: Bug

*Summary*: Cant remove participants from group chat when being a chat owner.

#### Expected behavior
I should have an option to remove people from chat i am administrator for

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/35910139-ac09be9e-0c06-11e8-9484-fc2d53a41c1b.png)

### Reproduction

- Open Status
- Create a group chat with several members
- Tap chat profile picture 
- Tap Settings
- Tap three dots next to any chat participant to see options

### Additional Information
* Status version: 0.9.11d644
* Operating System: iOS

**Comment by denis-sharypin** [comment]
Let's use our component for this action even it looks ridiculous with one option
![send-dropdown copy](https://user-images.githubusercontent.com/6559881/36030363-2c8274b6-0da7-11e8-8301-e294d7abd2df.png)

**Comment by asemiankevich** [comment]
closing this one as it is fixed in https://github.com/status-im/status-react/pull/3260
