### ISSUE TITLE
Rework Contact profile details UI

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3248]
### User Story

As a user, I want a clean profile screen for user I chat with

Designs: https://zpl.io/2pxZQol (7th and 8th from left)

Type: Feature

**Comment by denis-sharypin** [comment]
Mockups (last screens) — https://zpl.io/2pxZQol

<img width="891" alt="screenshot 2018-02-13 14 32 10" src="https://user-images.githubusercontent.com/6559881/36152339-fdf0ed36-10ca-11e8-9fcf-f7d5aa40691b.png">

If we don't have the block functionality right now, ignore it
<img width="916" alt="screenshot 2018-02-13 14 31 57" src="https://user-images.githubusercontent.com/6559881/36152346-044e975a-10cb-11e8-813e-b8058042c8d8.png">



<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by jeluard** [comment]
@denis-sharypin Indeed no blocking support for now

**Comment by denis-sharypin** [comment]
Do not forget to delete a wallet address from the current profile
