### ISSUE TITLE
Cleaned messages are shown if Clear History in group chat and relaunch app 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3249]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user who cleaned the History of the chat I expect that cleaned messages will never be shown in  this chat again. New messages will be shown but old are deleted forever.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Cleaned messages are shown again in group chat if user relaunches app

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Cleaned messages are not shown at all

#### Actual behavior
[comment]: # (Describe what actually happened.)
Cleaned messages are shown again in group chat if user relaunches app
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open group chat with some messages or create one. Remember what messages were in the chat
- Open Group settings and use Clear History option. Check that there are no messages shown in the chat
- Close app
- Open app again  and sign in
- Open Group chat where you've cleared history and check if same messages are shown

Clearing history (00:21) https://app.testfairy.com/projects/4803590-status/builds/7648994/sessions/26/?accessToken=50-s/iHBjBNfEupQT1A/0fJNbHE
After app relaunched: https://app.testfairy.com/projects/4803590-status/builds/7648994/sessions/27/?accessToken=kJaEXc1Qjct4awcG5u7KQOlZGQs

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by janherich** [comment]
This is fixed in https://github.com/status-im/status-react/pull/3228 PR
