### ISSUE TITLE
Remove dependency on react-native-autolink

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3252]
### User Story

As a developer, I want to rely on dependency only when mandatory

### Description

*Type*: Feature

`react-native-autolink` is used in a [single place](https://github.com/status-im/status-react/blob/80fb8dde8baea957d37cdf94f0ea88f74b7c810a/src/status_im/chat/views/message/message.cljs#L142) to detect URL and give them proper styling.
This is trivial to do with a regexp, not need to rely on an external dependency for this.

Each dependency is an extra security concern.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 480.00
Contract address: [0xb64d29b5c18a4a8c5fbdbeb7df46485bc038dee6](https://etherscan.io/address/0xb64d29b5c18a4a8c5fbdbeb7df46485bc038dee6)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
