### ISSUE TITLE
No 'Show QR'/'Copy to clipboard'/'Share' button for public key and address on user Profile [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3261]
***Type***: Bug

***Summary***: No 'Show QR'/'Copy to clipboard'/'Share' button for public key and address on user Profile on iOS. So there is no way at the moment to get from added contact the public key or address data.
It's present on Android though.

#### Expected behavior
'Show QR'/'Copy to clipboard'/'Share' button are present for public key and address on user Profile on iOS

#### Actual behavior
No 'Show QR'/'Copy to clipboard'/'Share' button for public key and address on user Profile on iOS

![image uploaded from ios 8](https://user-images.githubusercontent.com/8749671/35967774-93e87746-0cca-11e8-9eec-4a5ee8ab74b4.jpg)

### Reproduction

- Open Status
- Navigate to 'Home' -> 'Start new chat' -> 'Jarrad'
- From 1-1 chat screen navigate to Profile via top-right button
- On Address and Public key tap three-dot button

### Additional Information 
* Status version:  0.9.11d654 (8th of February)
* Operating System: iOS 11.2.2

**Comment by Serhy** [comment]
Similar (maybe with the same root cause) as https://github.com/status-im/status-react/issues/3244

**Comment by asemiankevich** [comment]
@Serhy this issue is not present in release candidate 0.9.14 so i will remove the label `release`

**Comment by Serhy** [comment]
This is not reproducible anymore. Neither in release nor on develop builds.
Closing the issue.
