### ISSUE TITLE
Replace "Ping" with "You have a new message" in push notification 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3269]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "Ping" is shown in the text of the push notification when user gets new message and Status app is not run on foreground. It's confusing as user expects to see some text "ping" in the messages. As we don't want to reveal message text on the notification popup, we can be more explicit and say "You have a new message" 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No header because there is already an app icon and app name on the top of notification
Notification text is "You have a new message"
#### Actual behavior
[comment]: # (Describe what actually happened.)
Notification header: "Status - new message"
Notification text is "ping"

iOS:
![54663](https://user-images.githubusercontent.com/6584810/35983291-0506fd86-0cf2-11e8-89a0-4175de549579.jpg)

Android:
![screenshot_20180208-170608](https://user-images.githubusercontent.com/6584810/35983607-a28b8234-0cf2-11e8-8a9c-9eab83c8b6ef.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- As A: Open Status
- As A: Send some text in 1:1 chat to the contact B that has Status installed but it's closed now
- As B: Check notification text shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.13
* Operating System: Android and iOS

**Comment by adambabik** [comment]
At least on iOS, you can decide if the notification message is displayed immediately or only after you unlock the phone. Maybe we can at least provide who is the author of the message?

**Comment by annadanchenko** [comment]
already implemented
