### ISSUE TITLE
Command messages are lost in console when upgrading app (0.9.13 -> 0.9.14 or 0.9.12b -> 0.9.14)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3277]
### Description

*Type*: Bug

*Summary*: 

1. no password message 
2. no faucet message
3. no debug message

![image](https://user-images.githubusercontent.com/28752642/36032369-d3ca2aae-0dbe-11e8-85ec-ef3a0b928993.png)

![image](https://user-images.githubusercontent.com/28752642/36032386-e3036864-0dbe-11e8-8f1f-5a3770b8a336.png)

![image](https://user-images.githubusercontent.com/28752642/36032395-eae6e68c-0dbe-11e8-8507-4364c75db687.png)

#### Expected behavior
command messages are present

### Suggestion: if user has called /phone command on 0.9.13 and then upgraded to 0.9.14

- remove "thanks we send confirmation code.." message 
- remove "tap here to validate your phone number .." message 

from Console as /phone command was removed from scope and the messages are not necessary anymore.

### Reproduction
- Open Status (release 0.9.13 clean)
- Set password
- Send /phone command
- send /faucet command
- send /debug command
- upgrade to 0.9.14 release build 14

### Additional Information
* Status version: 0.9.13 -> 0.9.14; 0.9.12b -> 0.9.14
* Operating System: Android, iOS
* **NOTE: 0.9.12b -> 0.9.13 upgrades fine**

0.9.14 release builds:
Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-748b0f.apk
iOS: https://i.diawi.com/Yji8bZ

#### Logs
TF https://app.testfairy.com/projects/4803622-status/builds/7663292/sessions/125/?accessToken=KSodp3NWI0KNnK6ZRRKKMUdhmMA

**Comment by rasom** [comment]
should be fixed here #3297

**Comment by rasom** [comment]
should be fixed here #3298
