### ISSUE TITLE
Automated tests (Profile) should be created/reworked according to sanity test cases

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3284]
### User Story
As an automation engineer I would like 'Profile' tests to be created/reworked according to [sanity test cases](https://ethstatus.testrail.net/index.php?/suites/view/15&group_by=cases:section_id&group_order=asc&group_id=388)

### Description

- Add visual assertion to the framework, use PIL or openCV (main goal is to have an ability to compare image template with an area from the screenshot taken during test run)
- Create separate test suite with tests listed below:
  - [x] 3. C1937 | Profile view of contact from list of contacts (like Jarrad profile)
  - [x] 4. C2088 | Can switch network to Rinkeby with upstream. Sign in. Rinkeby with upstream is shown in 
  - [x] 5. C2089 | Can open QR code, can share public key

  - **Tests with visual verefications:**
    - [x] 1. C2081 | Can change username and select profile picture (from Gallery and from Capture)
    - [x] 2. C1932 | Changed username and avatar is visible to another contact

-  All tests should be marked as `@pytest.mark.pr`
- Test steps for a test should be added in [sanity test cases](https://ethstatus.testrail.net/index.php?/suites/view/15&group_by=cases:section_id&group_order=asc&group_id=388) after creation of the test

**Comment by Serhy** [comment]
C1937, C2088, C2089 - added in #3311

**Comment by Serhy** [comment]
@antdanchenko could you please add C2081 and C1932 tests?
