### ISSUE TITLE
Automated tests (Sign in, DApps and browsing) should be created/reworked according to sanity test cases

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3285]
### User Story
As an automation engineer I would like 'Sign in', 'DApps and browsing' tests to be created/reworked according to [sanity test cases](https://ethstatus.testrail.net/index.php?/suites/view/15&group_by=cases:section_id&group_order=asc&group_id=388)

### Description
- Create separate test suite with tests listed below:
  - [x] C1933 | Auction house - can complete transaction
  - [x] C1934 | Browse site from link sent in 1-1 chat (in Status, if possible in separate browser)
  - [x] C2082 | Browse link for Open DApp - can open, when closed - new Chat in Home
  - [ ] C2079 | Create account, log out and sign in
-  All tests should be marked as `@pytest.mark.pr`
- Test steps for a test should be added in [sanity test cases](https://ethstatus.testrail.net/index.php?/suites/view/15&group_by=cases:section_id&group_order=asc&group_id=388) after creation of the test

**Comment by Serhy** [comment]
`C1933 | Auction house - can complete transaction` will be added in scope of #3281
`C1934 | Browse site from link sent in 1-1 chat (in Status, if possible in separate browser)` - will be added by @yevh-berdnyk in scope of #3282 (`C1929`s test)

@antdanchenko could you please add `C2079 | Create account, log out and sign in` with additional logic to stop the automation PR test suite execution if this test fails?

**Comment by antdanchenko** [comment]
`C1933 | Auction house - can complete transaction` added in scope of https://github.com/status-im/status-react/pull/3287
`C1934 | Browse site from link sent in 1-1 chat (in Status, if possible in separate browser)` added in scope of https://github.com/status-im/status-react/pull/3324
