### ISSUE TITLE
Error Attempt to invoke virtual method when capturing a photo

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3289]
### Description

*Type*: Bug

*Summary*: App crashes with `java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference` on Android when multitapping when capturing user picture

#### Expected behavior
no crash

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/36089892-1ddb6734-0fef-11e8-90d6-96f8cd5254d5.png)
 as well as

`java.lang.RuntimeException: Camera is being used after Camera.release() was called`

### Reproduction
- Open Profile
- Tap edit - capture
- Tap the screen several times in fast manner

### Additional Information

* Status version: 0.9.10-663-gd0dff14e+ (2220) develop
* Operating System: Android

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7671704/sessions/2/?accessToken=EzO1CCG3FCs91s5XA/0RimxKjMA

**Comment by rasom** [comment]
can't reproduce this on Android devices, only see the next exception when press camera icon multiple times:
<img src="https://user-images.githubusercontent.com/2364994/36097242-1abc6210-1035-11e8-9c63-af8c7239d54c.png" width=320 />

**Comment by asemiankevich** [comment]
Just repro it within latest develop, using LGE - LG-H990 Android 7.0. Can reproduce the error @rasom has found too

**Comment by rasom** [comment]
https://github.com/react-native-community/react-native-camera/issues/1173

**Comment by asemiankevich** [comment]
reopened as this commit needs to be rolled back. It does not fix the problem.

**Comment by lukaszfryc** [comment]
I've just reproduced it on Samsung Galaxy S8, Android 7.0. Here is [TS](https://status-im.testfairy.com/projects/4803622-status/builds/7756643/sessions/5).
