### ISSUE TITLE
Update etherscan URL

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3294]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to reflect etherscan API URL changes

### Description

*Type*: Bug

etherscan API URL have been [updated](https://etherscancom.freshdesk.com/support/solutions/articles/35000051806-change-of-testnet-api-service-endpoint-url). Reflect those changes in our codebase.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 250.00
Contract address: [0x68434751c9ab9ce51db1364f4c288cf786e27b00](https://etherscan.io/address/0x68434751c9ab9ce51db1364f4c288cf786e27b00)
Network: Mainnet
Paid to: tarekskr
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by tarekskr** [comment]
Hi! I just created a pull request that fixes this.
