### ISSUE TITLE
Add a timestamp to an every message

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3295]
### User Story

As a user, I want to know at what time my message was sent.

### Description

*Type*: Feature

**Comment by flexsurfer** [comment]
and was received

**Comment by annadanchenko** [comment]
what about grouping by Today, Yesterday, past date (Feb 20)

**Comment by chadyj** [comment]
Adding `design-blocked` until these ^ issues can be resolved.

**Comment by chadyj** [comment]
Dupe of https://github.com/status-im/status-react/issues/3793
