### ISSUE TITLE
Use clojurescript core inst-ms function for timestamps

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3304]
We have 2 different timestamp functions in `protocol.web3.utils` and `utils.datetime` namespaces. Replace them by clojurescript core `inst-ms` function

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 250.00
Contract address: [0x207dbe68d84d84d89f90d346541c568c225f9a8f](https://etherscan.io/address/0x207dbe68d84d84d89f90d346541c568c225f9a8f)
Network: Mainnet
Paid to: voxlet
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
