### ISSUE TITLE
Invite friends opens share sheet with download link

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3312]
### User Story

As a user, I want to share Status with my friends so that they can download the app and start chatting.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: From the "new" menu on Home, tap `Invite friends` which will open the system share sheet. The app will share a message saying `Get Status at https://status.im`

Note, this is a fast interim measure until friend discovery can be thoroughly explored.

**Comment by andytudhope** [comment]
Can we not make the link more precise and perhaps build in a small reward in SNT for users who do this when their friends download the app?

**Comment by chadyj** [comment]
@andytudhope Great idea! We are going to keep this issue simple for the restructure swarm, but will make a note of this for a future form about improving finding friends.

What exactly did you mean with `make the link more precise`?

**Comment by andytudhope** [comment]
I mean that you attach a code to the link: `Get Status at https://status.im?refCode=1234` and that allows us to reward a wallet address with some SNT. Apologies for late response, this slipped through my notifications...

**Comment by jeluard** [comment]
Note to bounty hunters: it is as simple as calling `#(list-selection/open-share {:message "Get Status at blah"})`

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0x116f5f4b06edd92bb4edc7ba366a213ad669022e](https://etherscan.io/address/0x116f5f4b06edd92bb4edc7ba366a213ad669022e)
Network: Mainnet
Paid to: jeluard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
