### ISSUE TITLE
Join existing public chat or create a new channel

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3313]
### User Story

As a user, I want to view a featured list of public chats so that I can join them and start chatting.

As a user, I want to create a public chat so that I can create a community and start chatting.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: From Home hit `New`, then `Join public chat` and either a) enter a channel name to create a topic, or tap on a topic to join an existing public chat.

[Zeplin designs](https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5a70317c76365a893ce40c22).

*Topics*:
* #status 
* #openbounty  
* #ethereum

**Comment by jeluard** [comment]
@chadyj Do we have a list of public chat we want to include?
