### ISSUE TITLE
Black screen when using camera (Android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3317]
### Description

*Type*: Bug

*Summary*: adresses https://github.com/react-native-community/react-native-camera/issues/1234 and logged for tracking purposes

#### Expected behavior
user is able to use camera:
- to scan QRs
- to make a user picture

#### Actual behavior
black screen shown when using camera on Android

### Reproduction

- Open Status
- Tap Profile -> Edit ->Capture

### Additional Information

* Operating System: Android

#### Logs
<RNCamera
ref={(cam) => { this.camera = cam; }}
type={RNCamera.Constants.Type.back}
// onBarCodeRead={this.barcodeRead}
barCodeTypes={[RNCamera.Constants.BarCodeType.qr]}
style={styles.preview}
>
<Text style={styles.capture} onPress={this.emulateScan}>[id: 4 code: 5K0C3H]</Text>
<TouchableOpacity onPress={() => Alert.alert('Alert', 'Keyboard pressed')}>
<Image source={imgKeyboard} style={[styles.icon]} />
</TouchableOpacity>
</RNCamera>

**Comment by GaneshSaiKumar** [comment]
is this solved?
