### ISSUE TITLE
STT/SNT tokens are not shown by default for recovered account

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3319]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: For newly created account we show ETH and STT in the Assets list on Wallet. For recovered account we show only ETH. It should be consistent, so when account is recovered - show ETH and STT in Assets.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After account is recovered: on Wallet screen in the Assets there are ETH and STT with amounts that this address has on Ropsten. If switch to mainnet: Assets ETH and SNT are shown by default with amounts this address has.
#### Actual behavior
[comment]: # (Describe what actually happened.)
After account is recovered: on Wallet screen in the Assets there is only ETH with amount that this address has. If enable STT from Manage assets then it's shown with proper amount. If switch to mainnet then SNT also not listed in the assets. 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Recover account that had some STT
- Open Wallet
- Check Assets shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.13 and nightly build Feb 14
* Operating System: Android and iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x2bcb741bbed93cc5914b95da5dc44f0213187f31](https://etherscan.io/address/0x2bcb741bbed93cc5914b95da5dc44f0213187f31)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
