### ISSUE TITLE
Amount field is hidden behind keyboard if tap inside it on some Android screens (Galaxy S6, S7,  ZTE A2017G) 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3322]
### Description

*Type*: Bug

*Summary*: Send transaction screen: if tap inside Amount field then keyboard is opened but field is hidden, so user can't see what's being typed. I would expect that focus is in the Amount field and that field is fully visible to me, so I do not need to scroll to it. It happens on several Android phones, e.g. Samsung galaxy S6, S7 and  ZTE A2017G (screenHeight 2560, screenWidth 1440)

#### Expected behavior
focus is in the Amount field and that field is fully visible to me, so I do not need to scroll to it. 
![screenshot_20180214-163710](https://user-images.githubusercontent.com/6584810/36207151-f13766f2-11a5-11e8-8bbf-378401e215e5.png)

#### Actual behavior
Amount field is hidden behind keyboard. To see what's being typed I need to scroll the screen
![screenshot_20180214-163703](https://user-images.githubusercontent.com/6584810/36207145-ed947f1c-11a5-11e8-9728-4dececd968d3.png)

### Reproduction
From 00:18 https://app.testfairy.com/projects/4803622-status/builds/7699096/sessions/28/?accessToken=qUKITizgAWjQdFbXqsuMyIjaXpU
- Open Status
- Open Wallet
- Tap on Send transaction
- Tap on Amount field and start typing the amount
- Check that you can see the field and what's typed
Same issue happens if select recipient and after this tap in Amount field.
Note: if scroll to the amount field once then second time you tap on the field screen scrolls as expected.

### Additional Information
* Status version: 0.9.13 and nightly build Feb 14
* Operating System: Android and iOS

**Comment by alwx** [comment]
Have no way to verify, but it's likely that this bug is fixed here: https://github.com/status-im/status-react/pull/3540

**Comment by jeluard** [comment]
@asemiankevich Can you confirm this has been fixed while fixing #3540 ?

**Comment by asemiankevich** [comment]
yes , confirm @jeluard
