### ISSUE TITLE
Harmonize status-bar

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3330]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have nice `status-bar` depending on the app background color

### Description

*Type*: Feature

Our current usage of `status-bar` is fairly complex and fragile. As a result of this incorrect colors are used in some screens.

**Comment by annadanchenko** [comment]
e.g. on Wallet screen in Android there are black icons:
![screenshot_20180214-214032](https://user-images.githubusercontent.com/6584810/36221648-d4659f10-11cf-11e8-9480-9d0e5993bafb.png)

**Comment by jeluard** [comment]
See also  #3227
