### ISSUE TITLE
No messages received if sender is offline and receiver runs the app 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3333]
### Description

*Type*: Bug

*Summary*: 
1. Receiver closed the app, so it's not running
2. Sender sends message in 1:1 chat to receiver and closes the app
3. Receiver gets push notifications and runs the app to read messages. Unfortunately, no new messages are shown even if wait for 10 minutes 

#### Expected behavior
Receiver gets messages sent to him when app was not run

#### Actual behavior
No new messages are received
### Reproduction

1. Receiver closed the app, so it's not running
2. Sender sends message in 1:1 chat to receiver and closes the app
3. Receiver gets push notifications and runs the app to read messages. Wait for 10 minutes to see if messages will arrive

TF receiver (has ``` offline inbox: flag enabled ```)  https://app.testfairy.com/projects/4803622-status/builds/7699096/sessions/47/?accessToken=nrD0whZ1ySUs7TzuTIdgxqrpvS4

### Additional Information
* Status version: nightly build Feb 14
* Operating System: Android receiver and iOS sender

**Comment by oskarth** [comment]
```
06:48 I/ReactNativeJS: INFO [status-im.protocol.handlers:307] - Peer enode://08d8eb6177b187049f6c97ed3f6c74fbbefb94c7ad10bafcaf4b65ce89c314dcfee0a8bc4e7a5b824dfa08b45b360cc78f34f0aff981f8386caa07652d2e601b@163.172.177.138:40404 is not registered. Retrying fetch peers.
06:53 I/ReactNativeJS: INFO [status-im.protocol.handlers:301] - offline inbox: fetch-peers response [{:id "0f7c65277f916ff4379fe520b875082a56e587eb3ce1c1567d9ff94206bdb05ba167c52272f20f634cd1ebdec5d9dfeb393018bfde1595d8e64a717c8b46692f", :name "Geth/v1.7.3-stable/linux-amd64/go1.9.2", :caps ["eth/62" "eth/63" "les/1" "les/2" "shh/5"], :network {:localAddress "192.168.1.228:46383", :remoteAddress "51.15.54.150:30303"}, :protocols {:shh "unknown"}} {:id "12d52c3796700fb5acff2c7d96df7bbb6d7109b67f3442ee3d99ac1c197016cddb4c3568bbeba05d39145c59c990cd64f76bc9b00d4b13f10095c49507dd4cf9", :name "Geth/v1.7.3-stable/linux-amd64/go1.9.2", :caps ["eth/62" "eth/63" "les/1" "les/2" "shh/5"], :network {:localAddress "192.168.1.228:39836", :remoteAddress "51.15.63.110:30303"}, :protocols 
```

*is not registered. Retrying fetch peers.* seems key

EDIT:
https://github.com/status-im/status-react/issues/3055#issuecomment-363824262 and historical? https://github.com/ethereum/go-ethereum/issues/3466

**Comment by dmitryn** [comment]
Should be fixed by https://github.com/status-im/status-react/pull/3384

**Comment by annadanchenko** [comment]
yes it's fixed
