### ISSUE TITLE
App crashed with property 'chat.message-overhead' has been removed after upgrade to d12c9b.apk

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3337]
***Type***: Bug

*Summary*: App crashed with property 'chat.message-overhead' has been removed after upgrade to d12c9b.apk

#### Expected behavior
No crash after upgrade 
#### Actual behavior
App crashed with property 'chat.message-overhead' has been removed after upgrade to d12c9b.apk

![screenshot_20180215-111516](https://user-images.githubusercontent.com/8749671/36248876-9cfcc5ea-1241-11e8-85b2-c737b287137a.png)

### Reproduction

- Nightly eba8df.apk installed (or lower version)
- Upgrade to latest nightly d12c9b.apk
- Open Status

### Additional Information
* Status version: Upgrade to d12c9b.apk (15th of February)
* Operating System: Android, iOS

### Additional Information 2: 
It's all OK on fresh install of the d12c9b.apk
#### Logs

https://app.testfairy.com/projects/4803622-status/builds/7706465/sessions/9/?accessToken=kzvUe-IfTesntVvl7djSfpPcuh4

**Comment by rcullito** [comment]
<img width="315" alt="chat message-overhead" src="https://user-images.githubusercontent.com/909156/36354531-f4fd40ee-14a3-11e8-8bee-e7c783e77211.png">

I have been experiencing this issue also on trying to build the latest version from `develop` branch.

**Comment by ihor-lev** [comment]
@rcullito as guys mentioned in referenced issues you can simply uninstall/reinstall the app. it worked for me.

**Comment by rcullito** [comment]
nice, thanks for the heads up @ikysylevych !
