### ISSUE TITLE
Play a sound for new messages

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3352]
### User Story

As a user, I want to be notified with a sound/vibration so that I know there is a new private message.

As a user, I want to edit sound preferences on the profile/settings screen, so that I can turn on/off sounds.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sounds and haptic notifications are a standard way to alert users when there is a new message, and is quite common for IM clients.  This issue will add a sound for new messages, along with settings to enable/disable.

* Add setting for sounds/vibration/notification (designs below)
* Play sound for new private messages ([Download MP3 sound](https://github.com/status-im/status-react/files/1767705/Notification.In.App.wav.zip))

**Comment by denis-sharypin** [comment]
Hey @chadyj could you check a prototype that I have prepared?
https://invis.io/FAFYVDU3VJG#/280636991_01

**Comment by denis-sharypin** [comment]
Hey @chadyj I prepared another prototype based on your feedback and our conversation.
https://invis.io/CTG3A478FZR#/282066912_01
Now we have:
1. A link to a general notifications settings where you can turn off all PN or choose a style of alerts.  
2. You can adjust Message Notifications: choose if you want to see alerts on the locked screen or not and hear a sound. If you switch off alerts, sound toggle automatically will switch to off as well.
3. In-App notifications (renamed them to Notifications while your app is open) could work even PN are off on a general level. You can adjust vibration for them but we can't control vibration of PN

**Comment by chadyj** [comment]
Sound to use for new message notifications.
[Notification In App.wav.zip](https://github.com/status-im/status-react/files/1767705/Notification.In.App.wav.zip)

**Comment by denis-sharypin** [comment]
After discussion with Chad, we decided to go with a simpler version.

Couple things:
1. The first row redirects you to a device settings
2. We need to introduce native platform switchers. Different for iOS and Android
ios: https://developer.apple.com/documentation/uikit/uiswitch
android: https://material.io/guidelines/components/selection-controls.html#selection-controls-switch

There is 2x pic:
![notifications handoff](https://user-images.githubusercontent.com/6559881/36800201-387547d2-1caf-11e8-8993-7681132b133e.png)

Also, there is a source sketch file:
https://www.dropbox.com/s/wzvb5v3fw8hr0pi/Notifications%20%3A%20handoff.sketch?dl=0

If somebody needs more precise specs, ping me

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1200.00
Contract address: [0xe8b12d7080c054f916489d475b4c8758f943f3b9](https://etherscan.io/address/0xe8b12d7080c054f916489d475b4c8758f943f3b9)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by enricrp8** [comment]
Is it still unfixed?

**Comment by denis-sharypin** [comment]
@enricrp8  still open, yep

**Comment by chadyj** [comment]
@foopang Any interest in this one?

**Comment by foopang** [comment]
@chadyj Yes, looks like a relatively easy task. I will give it a try when I have time.
