### ISSUE TITLE
cocoapods-1.4.0 causes error when running scripts/setup

### ISSUE THREAD

**Issue by rcullito** [status-im/status-react#3359]
### User Story

As a developer, I expect to run scripts/setup without any issues. However, if cocoapods is not already installed on OS X, the latest version 1.4 will be installed and this causes an error later on during pod install, specifically around the podspec for `yoga`

### Description

[comment]: # I uninstalled 1.4 and manually installed cocoapods 1.3 as this version was referenced in the Podfile.lock in the status-react repo. Clearing out the existing pods and re-running the setup script then resulted in no more errors. 

### Solution 

update documentation to explicitly suggest using cocoapods 1.3

OR 

update yoga pod so that it is compatible with the latest version of cocoapods 1.4

#### Logs

```
$ cd ios && pod install && cd ..

Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-background-timer` from `../node_modules/react-native-background-timer`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "yoga":
  In snapshot (Podfile.lock):
    yoga

  In Podfile:
    yoga (from `../node_modules/react-native/ReactCommon/yoga`)

It seems like you've changed the constraints of dependency `yoga` inside your development pod `yoga`.
You should run `pod update yoga` to apply changes you've made.
Error running dependency install
```
<img width="770" alt="podinstallerror" src="https://user-images.githubusercontent.com/909156/36354609-11419664-14a5-11e8-89a7-054f04e0e294.png">

**Comment by vemv** [comment]
Updated https://wiki.status.im/Building_Status:

```diff 
- sudo gem install cocoapods
+ sudo gem install cocoapods -v 1.3.1
```
