### ISSUE TITLE
test results for nightly: run autotests (at least pr set) on nightly.

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3360]
As an automation engineer I would like to run automated tests against each nightly build. Right now tests are running only against each PR.

**Comment by lukaszfryc** [comment]
@antdanchenko but why [status-app-end-to-end-tests](https://jenkins.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/) runs tests from `tests/nightly-runs-#3360` for every pull request?

![image](https://user-images.githubusercontent.com/7532782/36755731-64c59852-1c0d-11e8-9eb1-9404d90654f2.png)

Shouldn't it run tests from the same branch that the app was built?
