### ISSUE TITLE
Error `No protocol method IDeref.` when confirming password via native keyboard on user creation

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3361]
### Description

The error `No protocol method IDeref.` is shown if user confirms password using phone's native keyboard, instead of send message button.

#### Expected behavior
`Confirm` password input is shown

#### Actual behavior
The error is shown
![0005screenshot](https://user-images.githubusercontent.com/12611990/36370940-40bd36b8-1569-11e8-89c0-7f843b4a7ac2.png)

### Reproduction
- Open Status
- Tap `Request password` icon
- Enter valid passowrd
- Tap `Confirm` **on native keyboard**

### Additional Information
* Status version: <img width="293" alt="screen shot 2018-02-19 at 11 38 52 am" src="https://user-images.githubusercontent.com/12611990/36371010-7d04defa-1569-11e8-9ad5-be64590726f0.png">

* Operating System: Android and IOS

**Comment by annadanchenko** [comment]
will be changed in onboarding, so no reason to fix
