### ISSUE TITLE
Console chat could be deleted

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3364]
*Type*: Bug

*Summary*: Looks like this is an issue with migration to new UI - in old one we could not remove Console chat and this was by design. Nevertheless I still can reopen Console chat by choosing it from contacts I suggest to get back to previous decision and prevent Console chat from deletion
@denis-sharypin I did not find anything for this in https://projects.invisionapp.com/share/MJFOBUUTFE4#/screens/273529253 , maybe it will be redesigned?

#### Expected behavior
User is able to remove Console chat

#### Actual behavior
Console chat should not be deleted as it contains sensitive info for users 

### Reproduction

- Open Status
- go to Console chat
- tap three dots at the very right
- tap delete chat

### Additional Information
* Status version: latest nightly 244 02/19/2018
* Operating System: Android, iOS

**Comment by denis-sharypin** [comment]
Hey guys,
The whole interaction flow with a Console will be redesigned as a part of #80-onboarding swarm. 
Let's leave deletable feature for now.

**Comment by asemiankevich** [comment]
Thanks! I need mocks)

**Comment by denis-sharypin** [comment]
@asemiankevich 
Development mode switcher will be resposible for showing console or not. 
You are right, a console should not have a possibility of manual deletion only through that swither. 
 But we have to keep eye on that in the future releases.  
<img width="328" alt="screenshot 2018-02-28 19 33 08" src="https://user-images.githubusercontent.com/6559881/36805689-5d2b3cd0-1cbe-11e8-9276-fd007dae3292.png">

**Comment by asemiankevich** [comment]
closing this one as outdated
