### ISSUE TITLE
web3. suggestions in Console overlap taskbar (Android) and are not scrollable 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3366]
### Description

*Type*: Bug

*Summary*: Console full screen suggestions overlap the taskbar on Android  and the list is not scrollable on both platforms

#### Expected behavior

1. Console suggestions window is fixed height 180 px
2. Console suggestions are scrollable

![image](https://user-images.githubusercontent.com/28752642/36378331-72627814-158b-11e8-983d-100f1fafa785.png)

https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5a66f94aba218e7607157afa

#### Actual behavior

1. Console suggestions window is full screen
2. List is not scrollable

![image](https://user-images.githubusercontent.com/28752642/36378175-d8291e6a-158a-11e8-919c-8ebf6c18547f.png)

### Reproduction

- Open Status
- Type web3. in Console chat
- Pay attention to the suggestions window

### Additional Information
* Status version: 02/19/2018 nightly 244
* Operating System: Android|iOS

**Comment by annadanchenko** [comment]
night be same cause as in https://github.com/status-im/status-react/issues/3349
