### ISSUE TITLE
Migrate checkboxes to native widget

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3369]
### User Story

As a user, I want to use native checkboxes on my mobile platform.

### Description

*Type*: Feature

Latest react native releases support native checkboxes. Migrate our existing checkboxes implementation to this.

As it does not yet exist for iOS we want to polyfill it (so that we use the native syntax). It should be a squared checkbox (as current one))

* https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/checkbox/view.cljs#L6
* https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/list/views.cljs#L80
* https://facebook.github.io/react-native/docs/checkbox.html

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1120.00
Contract address: [0xfba7723f5786693f3a93f280d64fb576e1fd1ddd](https://etherscan.io/address/0xfba7723f5786693f3a93f280d64fb576e1fd1ddd)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
