### ISSUE TITLE
Upgrade to latest React Native

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3377]
### User Story

As a developer, I want to rely on latest library versions

### Description

*Type*: Feature

Each new release of React Native brings fixes and new features. We don't want to lag behind too long.
Upgrade to React Native `0.53` (or `0.54` if available).

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0x5ebbc6b68e904cc101dd76131aebb15711c9420d](https://etherscan.io/address/0x5ebbc6b68e904cc101dd76131aebb15711c9420d)
Network: Mainnet
Paid to: voxlet
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
