### ISSUE TITLE
Get rid of `(get-in platform-specific [:uppercase?])` 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#3379]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to simply use `:uppercase?` prop for `[text]` component, so it should be 

`[text {:uppercase? true} "Text"]` - for Android

`[text {:force-uppercase? true} "Text"]` - for both ios and Android

```clojure
(defn text
  ([t]
   (reagent/as-element [text-class t]))
  ([{:keys [uppercase? force-uppercase?] :as opts} t & ts]
   (reagent/as-element
     (let [ts (cond->> (conj ts t)
                       (or :force-uppercase? (and uppercase? platform/android?)) (map #(when % (string/upper-case %))))]
       (vec (concat
              [text-class (add-font-style :style opts)]
              ts))))))
```

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0x240f422db6404c25cda92048800f49d6e9060458](https://etherscan.io/address/0x240f422db6404c25cda92048800f49d6e9060458)
Network: Mainnet
Paid to: dongwoo-kim
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
