### ISSUE TITLE
Unknown chat is created and messages can't be sent if remove chat with a contact and try to start new 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3382]
### Description

*Type*: Bug

*Summary*: User is in my contacts and there is a chat with the user. If this chat is deleted then I can start new chat with this user. Unfortunately, 
1. If I tap on the username to start new chat then its profile is opened. Expected: new 1:1 chat with the user is created (if previous chat was deleted) or existing 1:1 chat with the contact is created
2. If in the opened profile tap on Start conversation then 1:1 chat with title Unknown is created. If start typing in the input field then commands button is shown instead of send button, so no message can be sent in the chat

#### Expected behavior
If I deleted a chat and then create new then I can talk with a contact in a new 1:1 chat

### Reproduction

- Open Status
- Add some contact
- Send a message to the contact in this 1:1 chat
- Delete this 1:1  chat
- Tap on + and select same contact to open new 1:1 chat with it
- Check that both of you can send and receive messages in this 1:1 chat

### Additional Information
* Status version: nightly build Feb 20
* Operating System: found on iOS, not checked on Android yet

**Comment by lukaszfryc** [comment]
@annadanchenko I think we should increase priority of this issue. Especially know when it's so easy to delete chats (swipe to delete). Users may simply delete chats to clean up some space. Then, they can't start new chat which is quite critical.

**Comment by annadanchenko** [comment]
cant' reproduce anymore after new-protocol. If tap on the contact then 1:1 chat is shown with this contact and no history. IF you or contact send any message then previous history and new message are shown
