### ISSUE TITLE
Multiple dialogs about invalid wallet address when scanning QR code  

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3383]
### Description

*Type*: Bug

*Summary*: On iOS, when QR code of an invalid address is being scanned, there are multiple dialogs about invalid address appearing on top of each other. Usually it's 2 of them (sometimes more). Then user is taken back to the Wallet screen instead of Send Transaction screen.
Note that when another invalid QR code is scanned again the app works as expected. Only one dialog is shown.

#### Expected behavior
Only one dialog about incorrect address appears and user is taken to Send transaction screen.

#### Actual behavior
Multiple dialogs with the same content appears on top of each other. User is redirected to Wallet screen.

### Reproduction
- Kill Status app
- Open Status app again
- Go to Wallet
- Click Send transaction and then choose recipient by scanning QR code
- Scan invalid QR code like the one below
<img src="https://user-images.githubusercontent.com/7532782/36424180-b6f16ad2-1642-11e8-8bf2-79c572077e0b.png" width="200">

### Additional Information
* Status version: 0.9.11d693
* Operating System: iOS 11.2.1 
* Works on Android
* Tested on: iPhone 6 (iOS), Samsung Galaxy S2 (Android)
* Can be reproduced every time the app is killed and opened again

**Comment by asemiankevich** [comment]
duplicate https://github.com/status-im/status-react/issues/2444
