### ISSUE TITLE
Upgrade TestFairy

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3388]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a PM, I want to submit app to App Store.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: App uses non-public APIs, which is not permitted on the App Store.

#### Expected behavior
App accepted by Apple.

#### Actual behavior
App not accepted by Apple.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Submit app to Apple for release.

To reproduce symptom:

```
find . -type f -exec grep -H 'SCRCException' {} \; Binary file ./ios/libTestFairy.a matches
```

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Upgrade TestFairy
- [ ] Make sure app still runs in release mode

Alternatively:

- [ ] Release build script that deletes the Testfairy files (suggested by @rasom as quickfix).

### Additional Information
* Status version: all
* Operating System: iOS

During an app review Apple flagged the following problem:

> Guideline 2.5.1 - Performance - Software Requirements
> 
> Your app uses or references the following non-public APIs:
> 
> PrivateFrameworks/ScreenReaderCore.framework (SCRCException)
> 
> The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change. 
> 
> Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.
> 
> Next Steps
> 
> If you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.
> 
> Resources
> 
> For information on the "nm" tool, please review the "nm tool" Xcode manual page.

#### Logs

**Comment by yenda** [comment]
That's TestFairy

`Erics-Mac-mini:status-react yenda$ find . -type f -exec grep -H 'SCRCException' {} \;
Binary file ./ios/libTestFairy.a matches`

**Comment by Zanther** [comment]
Let me just say you are a life saver. I have been wracking my brain with this looking at code and trying to find it.  Thank you so much.

**Comment by BorisDutkin** [comment]
Sorry I didn't get it...so how I fix the problem?

**Comment by chadyj** [comment]
@rasom fixed this manually for 0.9.14, but for a permanent fix we will need to create a release build script that will remove TF.

**Comment by vijaysharm** [comment]
Hello, I work for TestFairy. I'm sincerely sorry for the inconvenience. I'm not sure what version of the React native SDK you've included in your project, but this exact issue was resolved in v2.3.0 of the React native TestFairy SDK. The current version of the SDK is 2.7.0. If possible, you can upgrade and see if that resolves the issue for you. If you have any further issue, please do not hesitate to reach out to us at support@testfairy.com

**Comment by yairba** [comment]
Hey guys, the problem was fixed three months ago, in SDK version 1.11.1.
Here is the iOS SDK changelog: https://docs.testfairy.com/iOS_SDK/Changelog.html
Here is the list of React Native releases: https://github.com/testfairy/react-native-testfairy/releases

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2129.15
Contract address: [0xa4fec41f181c290fe5e0526bff35d80dbf7d5dce](https://etherscan.io/address/0xa4fec41f181c290fe5e0526bff35d80dbf7d5dce)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dmitryn** [comment]
This issue might be resolved  by https://github.com/status-im/status-react/pull/3660 as we're switching to react-native-testfairy 2.8.0
