### ISSUE TITLE
[Perf] User story 5: Time lags in message sending in chats having a lot of data 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3397]
### User Story

As a user I want my message to appear in the chat in <0.3 seconds after I tap the 'Send' message button  

***Type***: Bug

***Summary***: There are noticeable lags when sending a message in chat when this particular chat has already a lot of messages. The higher number of exchanged messages - the higher delay between the tap on 'Send message' button and appearance of actual message in the chat. Any type of chat affected. 

Two points impacts on the lags (depends on a device - numbers are below taken from Samsung J7 on Android 7.0): 
- **number of messages** 
For instance: contact starts 1-1 chat with another contact and sends the very first text message (e.g. 'Hello'). It takes <0.3 seconds for the message to appear in the chat.
Both contacts exchange with 100+ one-line text messages. 
Now when the same contact sends the message - it takes 2-3 seconds for the message to appear in the chat.

- ~**message content size**~
~For instance: contact starts a public chat with another contact and sends the very first one-line text message (e.g. 'Hello'). It takes <0.3 seconds for the message to appear in the chat.
The same contact sends seconds huge message with 1000 lines in total. Third one-line text message sending takes <2-3 seconds for the message to appear in the chat.~

**UPDATE: after new protocol integration!**
The responsiveness improved: I don't see a dependency between message content size and time lags on message sending.
The number of messages still matters though. Figures are twice lower since the issue originally has been reported, - but lags are still noticeable (see 'Reproduction' scenario below) 

Goal here: disregard of the data size in the chat - message should appear in <0.3 seconds after contact tap on 'Send message' button. 

#### Expected behaviour
No lags in message sending in the chats having a lot of messages 

#### Actual behavior
Lags in message sending in the chats having a lot of messages 

### Reproduction (related to 'number of messages')
- Open Status and create a new account
- Start 1-1 chat with contact (or Group Chat, or join public chat) 
- Send the first one-line message (e.g. 'Hey') and pay attention to delay between the tap on 'Send message' button and when the message appears in chat.
- Send (or receive) 100 one-line messages
- Send one-line message again and pay attention to the delay between the tap on 'Send message' button and when the message appears in chat.

### Additional Information
* Status version: 338th develop (15st of April), release 0.9.17
* Operating System: Android, iOS

TF session: https://app.testfairy.com/projects/4803622-status/builds/8101280/sessions/39/?accessToken=kwALQm6gV6bUKr08VQEVj/hhJe0

**Comment by Serhy** [comment]
Since the new protocol changes - this issue looks much better! 
I don't see any dependency between message content size and time delays on message sending like we had before.
But still the number of messages matter. 

So the description slightly updated keeping the scenario of how the number of messages impacts to the delay between tap 'Send message' button and when the actual message appears in the chat.

**Comment by lukaszfryc** [comment]
@Serhy what device you used to test it? For me there is no significant difference between first and 100th message. But, I use relatively fast devices - iPhone 8, Galaxy S8.

**Comment by Serhy** [comment]
Samsung Galaxy Note 4 and Samsung J7 has similar behavior for me in this relation: almost instant message appearance when I send a message in empty chat and ~3 seconds lag if I have 100-150 messages in the chat.

**Comment by mandrigin** [comment]
@lukaszfryc there are the same lags if you receive messages too, you just don't see them that obviously. @janherich found the main reason, now we just need to fix it 😄

**Comment by Serhy** [comment]
https://github.com/status-im/status-react/pull/4221 fixed this issue. 
Withing the chat with the 2000+ of messages on Galaxy Note 4 I don't have any lags sending a message.
