### ISSUE TITLE
Create a Clojure(Script) library replacing re-natal (as used by status)

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3398]
### User Story

As a developer, I want a smooth dev experience reducing dependency on external (brittle) command line tools

### Description

*Type*: Feature

Part of the dev process involves running `re-natal use-YOUR-DEVICE` and `re-natal use-figwheel`. Failing to do so might end up with weird state.

Both tasks don't do much: replace some variable in files essentially.

Came up with a Clojure(Script) library (so `cljc`) replacing those tasks that we will be able to directly use in build process (`lein`, maybe `clj` later) to simplify things and have a more robust build process.

Please feel free to discuss your ideas! Things are not completely settled on this.

__NOTE__ Relevant repository ownership must be switched to status/

**Comment by voxlet** [comment]
@jeluard I can see this growing into something useful for the wider community, very exciting!

For the PR, would covering the usage scope of re-natal in Makefile be sufficient, or are there any additional use cases we want to consider initially?

**Comment by jeluard** [comment]
@voxlet Right! Specifically I think we can restrict ourself to `re-natal use-figwheel` and `re-natal use-*-device *` for now. Ideally associated function would be idempotent (so only make changes when switching target platform).

Feel free to reorganize differently those 2 methods if that makes sense. What we want to cover is dev mode (figwheel) and prod mode, for all iOS/android/emulator/real device combinations.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2840.00
Contract address: [0xb15811d5d0ff9a8af2cebeaed29277795c784bd4](https://etherscan.io/address/0xb15811d5d0ff9a8af2cebeaed29277795c784bd4)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by jeluard** [comment]
@foopang By any chance were you able to take a look at this ? :)

**Comment by foopang** [comment]
@jeluard Sorry, don't have time to look at this issue yet. I think I might not be able to work on this unfortunately.

**Comment by psdp** [comment]
I have some work in progress. Please expect a PR soon :)

**Comment by dmitryn** [comment]
@psdp great news, this might be helpful:
*So what did re-natal add over the react-native template?*
https://gist.github.com/olivergeorge/d233fede8b3262e05c16b06ae5158861
or
https://confluence.condense.com.au/pages/viewpage.action?pageId=28082699

Actually, i see you as a member of #cljsrn channel on clojurians slack, so you're probably aware of that

<blockquote><img src="https://avatars2.githubusercontent.com/u/99447?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/olivergeorge/d233fede8b3262e05c16b06ae5158861">00 So what did re-natal add over the react-native template?.md</a></strong></div><div>GitHub is where people build software. More than 27 million people use GitHub to discover, fork, and contribute to over 80 million projects.</div></blockquote>

**Comment by psdp** [comment]
@dmitryn thanks! It's useful. I'm not aware not of that.
