### ISSUE TITLE
Implement 'setup' and 'full-prod-build' targets in Makefile

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#3399]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a contributor, I want to have an easy way to get bootstrapped with the latest local build of status-react and status-go. Although the scenario has improved in recent weeks with the addition of [scripts/bundle-status-go.sh](https://github.com/status-im/status-react/blob/develop/scripts/bundle-status-go.sh), there's still room for improvement by wrapping the procedure in a Makefile target.

In the same vein, [scripts/setup.sh](https://github.com/status-im/status-react/blob/develop/scripts/setup.sh) can be exposed in the Makefile through a `make setup` target, giving it more visibility.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I'd like to be able to get the `status-react` and `status-go` repositories, set up the appropriate environment variables and then just run `make setup && make full-prod-build` to have a working status-react build for iOS and Android which uses the current `status-go` binaries that it just built on my machine.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Implement a `setup` target which calls `scripts/setup.sh`
- [ ] Implement a `full-prod-build` target which calls `scripts/status-go.sh android` and `scripts/status-go.sh ios`, and then triggers the `prod-build` target.

**Comment by commiteth** [comment]
![Contract deploying](http://localhost:3003/img/deploying_contract.png)
Transaction: [0x964db935c4c9a854ca2d6db049a01e7425eff072360d2c577e4210b86f053fe0](https://ropsten.etherscan.io/tx/0x964db935c4c9a854ca2d6db049a01e7425eff072360d2c577e4210b86f053fe0)

**Comment by commiteth** [comment]
![Contract deploying](http://localhost:3003/img/deploying_contract.png)
Transaction: [0x964db935c4c9a854ca2d6db049a01e7425eff072360d2c577e4210b86f053fe0](https://ropsten.etherscan.io/tx/0x964db935c4c9a854ca2d6db049a01e7425eff072360d2c577e4210b86f053fe0)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x52847b9a3bc220e01dfc172492252e936398a30b459477b39562b18cadbb9a6e](https://etherscan.io/tx/0x52847b9a3bc220e01dfc172492252e936398a30b459477b39562b18cadbb9a6e)
