### ISSUE TITLE
The UI shifts down too far and unnecessarily.

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/status-react#3407]
**Title:** 	 The UI shifts down too far and unnecessarily.

**App Version:** 	 0.9.12 (1557.321)

**Current View:** 	 UIViewController

**Device:** 	 iPhone 6, iOS 11.2

**Duration:** 	 354

**Memory:** 	 778.0/809.0 MB

**Storage:** 	 13.694/15.248 GB

**Battery:** 	 100, Charging

**Console Log:**
```

```

[![image attachment](https://s3.amazonaws.com/instabug-pro/attachments/states/130518492/22f4e40b8dbee49d32018835fe355e78_original/51563543/2018012305385016808.jpg?1516750732)](https://s3.amazonaws.com/instabug-pro/attachments/states/130518492/22f4e40b8dbee49d32018835fe355e78_original/51563543/2018012305385016808.jpg?1516750732)

**Comment by lukaszfryc** [comment]
Thanks @jarradh. The issue is already reported here #2983
