### ISSUE TITLE
Wrong password hint that shows while signing transaction is slightly misplaced

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3411]
### Description
*Type*: Bug

#### Expected behavior
The wrong password hint is displayed right above the password field.  

#### Actual behavior
The hint is displayed too high in relation to the password field: 

<img src="https://user-images.githubusercontent.com/7532782/36543246-7e053e9a-17e3-11e8-985b-f2a2a9c16a93.png" width=300>

### Reproduction
- Open Status
- Go to Wallet, then Send transaction
- Set amount and click sign transaction button
- Type incorrect password
- Click sign transaction button

### Additional Information
* Status version: nightly, 22 Feb
* Operating System: Android and iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 680.00
Contract address: [0xc43fa413c65eaed8e20151c539ccaaf41b5423da](https://etherscan.io/address/0xc43fa413c65eaed8e20151c539ccaaf41b5423da)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
