### ISSUE TITLE
Tapping outside the commands window does not close it

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3412]
### Description

*Type*: Bug

*Summary*: This is from `status-everyday` feedback @vkjr has provided cc @denis-sharypin 

#### Expected behavior

when press on a commands list icon, list of commands slides out. Intuitively I want to close it by pressing on the messages area (outside the list of commands)

#### Actual behavior
^ it is not possible, I need to select message edit field again and remove ‘/’ character 

### Reproduction

- Open Status
- Press commands list icon
- Tap outside the commands window

### Additional Information
* Status version: last nightly 248
* Operating System: Android, iOS

**Comment by yevh-berdnyk** [comment]
It is still reproducible on Android in the latest nightly build (0.9.10-793-gd692ddc7+), real device LG V20, Android 7.0
