### ISSUE TITLE
User is not redirected to previous screen after scanning wallet QR code. Transaction details are lost

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3414]
### Description
*Type*: Bug

*Summary*: When user scans QR code of a wallet address she is being redirected to main Wallet screen. This results in transaction details being lost. Instead, user should be redirected to Send Transaction screen to finish the transaction. 
Issue does not occur when address is typed or recipient is selected from a list.

Note: issue happens only on iOS.

#### Expected behavior
After scanning address QR code user is redirected to Send Transaction screen to finish the transaction. 

#### Actual behavior
After scanning address QR code user is redirected to main Wallet screen.

### Reproduction
- Open Status
- Go to Wallet, then Send transaction
- Choose recipient by scanning correct QR code of a wallet address

### Additional Information
* Status version: nightly, Feb 22
* Operating System: iOS, 11.2.1
* Device: iPhone 6

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1350.00
Contract address: [0x97e7d53d41ba699ceedc940f967150f4efd89a57](https://etherscan.io/address/0x97e7d53d41ba699ceedc940f967150f4efd89a57)
Network: Mainnet
Paid to: flexsurfer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by Serhy** [comment]
I can still reproduce it (iPhoneX with the latest Nightly build). It's happens very often to me (maybe -> 99% happens for the first attempt to scan Wallet QR code for a new account. Steps are:

- Install fresh nightly build
- Create account
- Navigate to `Wallet` -> `Set up your Wallet` -> `Send transaction` -> `Specify recipient` 
- `Scan QR code` -> hit 'Allow' for Camera permission -> scan valid QR code

It doesn't mean that it is the only case when issue reproduced. I've seen it in the past after contact used account and successfully scanned wallet QR codes and at some point, the issue appeared.

**Comment by asemiankevich** [comment]
looks good to me! can't say it is fixed 100% but i tried with new and recovered accounts and scanning is great.
