### ISSUE TITLE
STT asset changes to ETH after scanning QR code in Send Transaction

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3416]
### Description
*Type*: Bug

*Summary*: When user wants to send a STT transaction, the asset type changes to ETH after QR code of wallet address is scanned. It looks like the asset is reverted to default one (ETH). Everything works fine when recipient is selected from a list or address is typed.

Happens only on Android. iOS has related issue: #3414

#### Expected behavior
STT is selected as asset after scanning QR code.

#### Actual behavior
ETH is selected as asset after scanning QR code even though STT was choosen in the first place. 

### Reproduction
- Open Status on Android
- Go to Wallet and then to Send transaction
- Select STT as asset
- Choose recipient by scanning a valid QR code

### Additional Information
* Status version: nightly, Feb 22
* Operating System: Android 7.0
* Device: Samsung Galaxy S8

**Comment by jeluard** [comment]
This is not a bug but expected. QR code standard encapsulates asset types which by default is ETH.

**Comment by lukaszfryc** [comment]
@jeluard got it. Thanks for the info.
