### ISSUE TITLE
App crashed when accessing camera view but access to camera denied for app [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3417]
***Type***: Bug

***Summary***: If user denied access to camera for app on iOS and tries to access the camera view 
 app crashes with the error
`Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMetadataOutput setMetadataObjectTypes:] Unsupported type found - use -availableMetadataObjectTypes'
`
Two ways to deny the access to camera: 
1) When app asks permissions to Camera and user submits 'Deny Access' from requesting pop up
2) If user denied access from app setting 

**Note**:  Android is OK. iOS affected only.

#### Expected behavior
Pop up with request to access camera view if access was denied previously
#### Actual behavior
App crash on access camera view if access was denied previously

### Reproduction 1
- Instal fresh build 
- Open Status and create account
- Navigate to `Profile` -> `Edit` -> `Edit profile image`
- Tap 'Capture' 
- On request to access camera pop up tap - 'Don't allow'

### Reproduction 2
- Instal fresh build 
- Open Status and create account
- Navigate to `+` -> `Start new chat` 
- Tap on scan QR code button from 'Enter contact code' field
- On request to access camera pop up tap - 'Don't allow'

### Reproduction 3
**Precondition:** App installed, account created and access to camera allowed before

- From device settings for app - disable access to 'Camera'
- Open Status
- Log in to account (or create a new one)
- Navigate to `Wallet` -> `Send transaction` -> `Specify recipient`
- Tap 'Scan QR code'

### Additional Information
* Status version: Develop 22nd of February (0.9.11d711)
* Operating System: iOS

TF session with logs: https://app.testfairy.com/projects/4803590-status/builds/7756060/sessions/63/?accessToken=RkbcobWCuuHuS-TBCL6PBOvuedY

**Comment by asemiankevich** [comment]
also can't select picture from gallery when access to camera denied

**Comment by lukaszfryc** [comment]
@jeluard any update on this one?

**Comment by jeluard** [comment]
@lukaszfryc Not working on it right now. Unassigned myself.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2200.00
Contract address: [0x49c46bfa994bdb9f1fa6d2846cc30d9560bc9107](https://etherscan.io/address/0x49c46bfa994bdb9f1fa6d2846cc30d9560bc9107)
Network: Mainnet
Paid to: okilimnik
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
