### ISSUE TITLE
Password request message is not shown after application is launched after install

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3418]
***Type***: Bug
*Summary*: Password request message is not shown after application is launched after install (same as #2925)

#### Expected behavior
I can set up password
#### Actual behavior
![screenshot_20180222-180354](https://user-images.githubusercontent.com/8749671/36549225-e6e7ba8e-17fa-11e8-8a1f-524443ebf46c.png)

### Reproduction
- Install fresh build
- Open Status

### Additional Information
* Status version: 0.9.15 release http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-74819e.apk / iOS: https://i.diawi.com/ESM7s5
* Operating System: Android, iOS

**Comment by dmitryn** [comment]
@jeluard `JSC_ENABLED=0` setting disables json->clj data conversion for jail calls so "password" command data doesn't get into app-db.
