### ISSUE TITLE
Navigator problems

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#343]
There are several navigator-related issues (everything was tested on iOS):

- [x] 1) Sometimes there is no way back. When you open the app for the very first time it shows you the `console` chat, and there is a back button, but this button doesn't work. There are some questions to @jarradh: do we need to open the `console` chat when a user opens the app for the very first time? If yes, how the back button should behave?
- [x] 2) If you open the login screen and go back instead of entering your password, you will see the `console` chat with useless back button again.
- [x] 3) `Start new chat` -> `New group chat` -> `Back`. Something is also broken here.

**Comment by alwx** [comment]
@jarradh need your answer :)

**Comment by jarradh** [comment]
1 back button should be hidden then appear when user has set password

2 if there is no account you shouldn't be able to get to login screen

3 agreed
