### ISSUE TITLE
Do not allow to tap on the send button until recipient of the token is specified in group chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3431]
### Description
*Type*: Bug

*Summary*: In group chat, when `/send` is clicked a user may not select a recipient but still be able to proceed to next step (specify amount). He then ends up in a state where tapping on the send button does nothing because the recipient was not provided: 

<img src="https://user-images.githubusercontent.com/7532782/36605458-11df5e1a-18c1-11e8-8b36-68b889cd121b.png" width="300">

Maybe in this case the send button should be disabled until user selects or types the recipient? @denis-sharypin wdyt? 

### Reproduction
- Open Status
- Open a group chat
- Type `/send`
- Click the send button without providing the recipient

### Additional Information
* Status version: nightly, Feb 23
* Operating System: Android, iOS

**Comment by chadyj** [comment]
We've discussed redoing this flow with a consistent wallet UI so we don't need to tweak this. We can just fix it with a better flow.

**Comment by lukaszfryc** [comment]
Can you link it to some wallet UI issue?

**Comment by denis-sharypin** [comment]
we got rid of this UI
