### ISSUE TITLE
Cannot clear topic input when joining public chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3432]
### Description
*Type*: Bug

*Summary*: The first character in the topic input can't be cleared. In result, user can't clear the whole topic to type a new one. She needs to leave public chat screen and open it again to start with an empty topic.

In the screenshot below, "j" can't be cleared. Also, please note a misalignment (iOS only) between "#" and topic name: 

<img src="https://user-images.githubusercontent.com/7532782/36627710-24cc01fa-1947-11e8-9265-02ab84ff6856.png" width="300">

#### Expected behavior
Whole topic can be cleared. 

#### Actual behavior
The first character of the topic can't be cleared.

### Reproduction
- Open Status
- Go to Home
- Click "+" and join public chat
- Write a chat topic
- Try to clear the topic

### Additional Information
* Status version: 0.9.15, 834ae3
* Operating System: Android and iOS
* Tested on iPhone 6 (iOS 11.2.1) and Samsung Galaxy S2 (Android 7)

**Comment by Serhy** [comment]
Misalignment part of this issue will be fixed in the scope of #3372
