### ISSUE TITLE
Improve Github test report for end-end tests

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3433]
## Summary
Our current report is really long and maybe hard to read. Having in mind that we are going to extend our test suite, we need to make sure the test report is still easy to understand and does not clutter thread of a Github issue.

[Example of current test report](https://github.com/status-im/status-react/pull/2962)

## Who should read end-end test report and why?

* developers (internal and external contributors)
   * high level overview of end-end tests that were executed
   * understand which tests failed
   * have link to full report (and video) to dig into why the tests failed
* test engineers
   * same reasons as developers + understand what tests were executed to be aware of the exact test coverage

**Comment by lukaszfryc** [comment]
@antdanchenko here is how I think we could better present the test report. Let me know what you think.

## 80% end-end tests has passed
```
Total executed tests: 10 
Failed tests: 2
```

### Todo
- [ ] Review failed tests and either fix the bugs or fix the the tests 

### Failed tests (2)  

| Platform | Test | Error |
| ------------- | ------------- | ------------- |
| Android | [test_contact_profile_view](https://saucelabs.com/beta/tests/3dd6367b01ef4737bb2b0204e2836c2a?auth=10df308ecc433608867823a9d10d3df0)  | `E selenium.common.exceptions.NoSuchElementException: Message: 'RecoverButton' is not found on screen, using: 'xpath://*[@text='Recover']'`  |
| Android | [test_one_to_one_chat_messages_and_delete_chat](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48)  | `E selenium.common.exceptions.WebDriverException: Message: The test with session id 5a4432a768884231b0a38f7e99fe584f has already finished, and can't receive further commands. You can learn more at https://saucelabs.com/jobs/5a4432a768884231b0a38f7e99fe584f For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages`  |

### Passed tests (8)

|Platform | Test |
| ------------- | ------------- |
| Android | [test_browse_link_entering_url_in_dapp_view](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) | 
| Android | [test_network_switch](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) |
| Android | [test_browse_link_entering_url_in_dapp_view](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) | 
| Android | [test_network_switch](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) |
| Android | [test_browse_link_entering_url_in_dapp_view](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) | 
| Android | [test_network_switch](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) |
| Android | [test_browse_link_entering_url_in_dapp_view](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) | 
| Android | [test_network_switch](https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48) |

----

[Continue to review full report at Jenkins](https://jenkins.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/350/testReport/)

**Comment by lukaszfryc** [comment]
## 80% end-end tests have passed
```
Total executed tests: 10 
Failed tests: 2
```

### Failed tests (2)  

<table style="width: 100%">
<colgroup>
<col span="1" style="width: 20%;">
<col span="1" style="width: 80%;">
</colgroup>

<tbody>
<tr>
  <th>Test</th>
  <th>Failure</th>
</tr>
<tr>
  <td>
    test_contact_profile_view
    </td>
  <td>
    <p>
      <blockquote>
        <div>Looking for PassphraseInput</div>
        <div>Tap on SignTransactionButton</div>
        <div>(FAILED) Looking for full text: 'Wrong password'</div>
      </blockquote>
    </p>
    <p>
      <details>
        <summary>Click to expand full logs</summary>
          <br/>
          <p><ins>Test steps:</ins></p>
          <blockquote>
            <p>Device started..</p>
            <div>Tap on OkButton</div>
            <div>Looking for ContinueButtonAPK</div>
            <div>Tap on ContinueButtonAPK</div>
            <div>Looking for RecoverButton</div>
            <div>Tap on RecoverButton</div>
            <div>Looking for PassphraseInput</div>
            <div>Tap on SignTransactionButton</div>
            <div>(FAILED) Looking for full text: 'Wrong password'</div>
          </blockquote>
          <code>
            E selenium.common.exceptions.NoSuchElementException: Message: 'RecoverButton' is not found on screen, using: 'xpath://*[@text='Recover']
          </code>
          <hr/>
          <ins>Device sessions:</ins>
          <p>
            <ul>
              <li><a href="https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48">Device 1<a/></li>
              <li><a href="https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48">Device 2<a/></li>
            </ul>
          </p>
      </details>
    </p>
  </td>
</tr>
<tr>
  <td>
    test_network_switch
  </td>
  <td>
    <p>
      <blockquote>
        <div>Looking for PassphraseInput</div>
        <div>Tap on SignTransactionButton</div>
        <div>(FAILED) Looking for full text: 'Wrong password'</div>
      </blockquote>
    </p>
    <p>
      <details>
        <summary>Click to expand full logs</summary>
          <br/>
          <p><ins>Test steps:</ins></p>
          <blockquote>
            <p>Device started..</p>
            <div>Tap on OkButton</div>
            <div>Looking for ContinueButtonAPK</div>
            <div>Tap on ContinueButtonAPK</div>
            <div>Looking for RecoverButton</div>
            <div>Tap on RecoverButton</div>
            <div>Looking for PassphraseInput</div>
            <div>Tap on SignTransactionButton</div>
            <div>(FAILED) Looking for full text: 'Wrong password'</div>
          </blockquote>
          <code>
            E selenium.common.exceptions.NoSuchElementException: Message: 'RecoverButton' is not found on screen, using: 'xpath://*[@text='Recover']
          </code>
          <hr/>
          <ins>Device sessions:</ins>
          <p>
            <ul>
              <li><a href="https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48">Device 1<a/></li>
            </ul>
          </p>
      </details>
    </p>
  </td>
</tr>
</tbody>
</table>


### Passed tests (8)

<details>
<summary>Click to expand</summary>
<br/>
<table style="width: 100%">
<colgroup>
<col span="1" style="width: 20%;">
<col span="1" style="width: 80%;">
</colgroup>

<tbody>
<tr>
  <th>Test</th>
  <th>Logs</th>
</tr>
<tr>
  <td>
    test_contact_profile_view
  </td>
  <td>
    <p>
      <details>
        <summary>Click to expand full logs</summary>
          <br/>
          <p><ins>Test steps:</ins></p>
          <blockquote>
            <p>Device started..</p>
            <div>Tap on OkButton</div>
            <div>Looking for ContinueButtonAPK</div>
            <div>Tap on ContinueButtonAPK</div>
            <div>Looking for RecoverButton</div>
            <div>Tap on RecoverButton</div>
            <div>Looking for PassphraseInput</div>
            <div>Tap on SignTransactionButton</div>
            <div>Looking for full text: 'Wrong password'</div>
          </blockquote>
          <hr/>
          <ins>Device sessions:</ins>
          <p>
            <ul>
              <li><a href="https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48">Device 1<a/></li>
            </ul>
          </p>
      </details>
    </p>
  </td>
</tr>
<tr>
  <td>
    test_network_switch
  </td>
  <td>
    <p>
      <details>
        <summary>Click to expand full logs</summary>
          <br/>
          <p><ins>Test steps:</ins></p>
          <blockquote>
            <p>Device started..</p>
            <div>Tap on OkButton</div>
            <div>Looking for ContinueButtonAPK</div>
            <div>Tap on ContinueButtonAPK</div>
            <div>Looking for RecoverButton</div>
            <div>Tap on RecoverButton</div>
            <div>Looking for PassphraseInput</div>
            <div>Tap on SignTransactionButton</div>
            <div>Looking for full text: 'Wrong password'</div>
          </blockquote>
          <hr/>
          <ins>Device sessions:</ins>
          <p>
            <ul>
              <li><a href="https://saucelabs.com/jobs/9d6b3591ec194ebcaade721ebf63626c?auth=c92ffe644ad8b14ce658406fe1e16d48">Device 1<a/></li>
            </ul>
          </p>
      </details>
    </p>
  </td>
</tr>
</tbody>
</table>
</details>

----

[Continue to review full report at Jenkins](https://jenkins.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/350/testReport/)

**Comment by lukaszfryc** [comment]
@antdanchenko please check. I've added:
- test steps
- device sessions
- collapsing
- fixed scrolling in columns

Who do you think we can ask for a feedback?

**Comment by antdanchenko** [comment]
@lukaszfryc looks great
and what do you think about adding such option?

e.g.
- by default all failed tests are marked as `Failed`
- `Failed` can be manually changed to:
  - `feature changed`
  - `bug (link to the issue)`
  - `false failure`
  - `infrastructure issue`

**Comment by lukaszfryc** [comment]
This will be handled in #3469
