### ISSUE TITLE
Toolbar with dark content

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#344]
React Native 0.36.0-rc.0 introduces Toolbar `dark-content` property which is required for us if we want to make our Android app look the same way as Zeplin sketches. 

https://github.com/facebook/react-native/releases/tag/v0.36.0-rc.0

**Comment by jarradh** [comment]
is this related to the top bar being purple on android ?

**Comment by alwx** [comment]
it is for white status bars with black texts on them

for example: https://app.zeplin.io/project.html#pid=570c07ce7d73d11c3c6709ae&sid=57136ff546cec0e935546c85
