### ISSUE TITLE
No response for /debug command in Console

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3440]
### Description

*Type*: Bug

*Summary*: No response for /debug command in Console

#### Expected behavior
I can see response for `debug - On / Off` interaction in Console

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/36672611-f9754fe0-1b10-11e8-8881-05236e98b511.png)

### Reproduction

- Open Status
- call /debug command

### Additional Information
* Status version: nightly 253
* Operating System: Android, iOS

**Comment by nabgilby** [comment]
in the latest status version on the Android store [ 0.9.19 (6034)] and latest released nightlies [0.9.20 (6058]) /debug no longer works, again it seems.

What version does it work in so I can go back to it?
