### ISSUE TITLE
Insufficient funds error when sending transaction with low balance

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3441]
### Description

*Type*: Bug

*Summary*: Insufficient funds error when sending transaction to dApp with low balance. Logged a ticket for AuctionHouse devs https://github.com/dob/auctionhouse/issues/42. The ticket is closed for now. The problem is that gas cost is not considered when showing warnings in wallet

#### Expected behavior
Prevent signing transaction (to dApp or when sending tokens or when sending ETH) if balance is less then required to perform the transaction

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/36717656-f907e06e-1baf-11e8-9fb3-58b085e01eb7.png)

![image](https://user-images.githubusercontent.com/28752642/36717742-4790230e-1bb0-11e8-936e-88599f5e9060.png)

### Reproduction

- Open Status
- Having 0 balance send transaction to Auction house
- Having 0 balance send txn to any contact
- Having 0 balance send tokens to any contact

### Additional Information

* Status version: nightly 253
* Operating System: Android, iOS

**Comment by jeluard** [comment]
@asemiankevich Prevent how? This should be done at the DApp level. Not clear what status could do here.

**Comment by asemiankevich** [comment]
@jeluard then we can send this to dApp developers :) Not sure if we have separate bug tracker for this :)

**Comment by jeluard** [comment]
Yes to `Auction house` developers! :) https://github.com/dob/auctionhouse

<blockquote><img src="https://avatars2.githubusercontent.com/u/10389?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dob/auctionhouse">dob/auctionhouse</a></strong></div><div>auctionhouse - Ethereum based auction platform for non fungible on chain goods</div></blockquote>

**Comment by asemiankevich** [comment]
wow! I will move this bug here! thanks @jeluard i was not aware about it

**Comment by ericxtang** [comment]
@jeluard hmm... What do you guys propose here? Just set an arbitrary gas amount and check against that? Isn't this the correct behavior is gas is too low?

**Comment by jeluard** [comment]
Hi @ericxtang ! Thanks for joining :)
Not sure what could be done. @asemiankevich what would you expect here?

**Comment by asemiankevich** [comment]
@ericxtang Hi Eric! Thanks for joining! 

I am expecting:
1. Friendly error message saying `Insufficient balance` when user does not have enough funds to complete the transaction
2. Sign button is disabled so user is not confused sending transaction which will fail in an error later due to low balance

We have similar implemented in wallet:

![image](https://user-images.githubusercontent.com/28752642/36717405-07783a5a-1baf-11e8-91a1-e9618ef34fc0.png)

**Comment by asemiankevich** [comment]
so @ericxtang the problem is ours :) sorry for bothering and thanks for the response. I closed the ticket on your side.

**Comment by jeluard** [comment]
@ericxtang Sorry for the confusion! We will work on improving our own wallet to make sure DApps users get an even better experience using you DApp!
