### ISSUE TITLE
Import Status Workspace Directory contacts for internal builds

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3443]
Status has almost 100 employees, but (as yet) there isn't an easy mechanism that allows for Status members to easily find, add and start chatting with each other. By making it easy to find workmates it will be much easier to use status everyday https://github.com/status-im/ideas/issues/75 for internal chats.  

Todo:
- [x] Generate static json member directory for quick prototyping
- [x] Automate this json directory from the work done in https://github.com/status-im/status-workspace-directory with @jacqueswww 
- [ ] In the Status app, read this json file and add the members as contacts
- [ ] Only works in dev builds

The goal is to have this done this week in time for the offsite.

**Comment by jacqueswww** [comment]
So just for more detail, I will make the status-workspace-directory, just host a json file on HTTP. The format will look like this:
``` 
{
"0x0428c9d6c1aaaa8369a7c63819684f30e34396dc0907d49afeac85a0a774ccb919b3482097d992e66bcc538e7a0c6acf874c77748f396f53c0a102e10d1a37765b":
    {
        "name":
        {
            "en": "Jarrad"
        },
        "photo-path": "contacts://jarrad",
        "add-chat?": false,
        "dapp?": false
    },
```

**Comment by chadyj** [comment]
I generated a static member json file for prototyping @goranjovic 

@jacqueswww That's awesome.

Gist:
https://gist.github.com/chadyj/cec8310f2e8f65ab10657db397ab9a7d

or raw link:
https://gist.github.com/chadyj/cec8310f2e8f65ab10657db397ab9a7d/raw

**Comment by jacqueswww** [comment]
@goranjovic So this will be the auto-updating url we can use, Status Workspace Directory will update it every hour, if there is a change in keys.

https://gist.githubusercontent.com/jacqueswww/0debd3f20efd99b827df62d1f21f3e9f/raw/

My idea was the we can just issue something like this on console `/import_contacts <url to json file>` ?
Also would be super cool if the command would follow redirects, for making tiny urls (which would make it super easy to import contacts for testers) :smile:

**Comment by chadyj** [comment]
@goranjovic Is it worth picking this up again? Any new thoughts on doing it differently?

**Comment by chadyj** [comment]
@jacqueswww What do you think about doing a HTML version of the above json that has QR codes? Until we bring the directory into Status it can be an easy page to find and add contacts.

**Comment by jacqueswww** [comment]
Yeah sure I can do that, the whole "0x..." Strng just encoded in the qr code?

**Comment by chadyj** [comment]
@jacqueswww Yep so that Status can read it when adding a contact.

**Comment by chadyj** [comment]
Also nice to show the name and photo too.

**Comment by chadyj** [comment]
I'm going to close this. We didn't get it in the app, but we did get a nice html directory :)
Thanks y'all!
