### ISSUE TITLE
Improve diawi publishing from Jenkins

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3455]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want reliable access to diawi artifcats

### Description

*Type*: Bug

Frequently diawi links published in `jenkins` slack are incorrect (`null`).
This is probably due to not waiting long enough to get the proper link from diawi API. (see [this part of the script](https://github.com/status-im/status-react/blob/develop/Jenkinsfile#L61))

Update the script so that diawi links are never nil.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1600.00
Contract address: [0xab68e3bf970b4f9e58e517de7e354787794d098a](https://etherscan.io/address/0xab68e3bf970b4f9e58e517de7e354787794d098a)
Network: Mainnet
Paid to: PombeirP
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by chadyj** [comment]
@jeluard It should be pretty straight forward to get Fastlane working with Diaiwi with this plugin.
https://github.com/pacification/fastlane-plugin-diawi

After installing the plugin this lane would be added `fastlane/Fastfile` in the appropriate lane

```
diawi(
    token: "your_api_token",
    file: "path_to_ipa_or_apk_file"
)
```

<blockquote><img src="https://avatars0.githubusercontent.com/u/2921634?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pacification/fastlane-plugin-diawi">pacification/fastlane-plugin-diawi</a></strong></div><div>https://rubygems.org/gems/fastlane-plugin-diawi</div></blockquote>
