### ISSUE TITLE
Publish diawi links in relevant PR

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3456]
### User Story

As a user, I want easy access to diawi links from github PR

### Description

*Type*: Feature

Each time a build is successful associated diawi links should be published to associated PR.
Also make sure build version number is accessible.

**Comment by andytudhope** [comment]
Same question as @oskarth asked on another one of the awaiting-approval bounties to do with builds - how will external contributors access the necessary info to get the diawi links published correctly? Need more info here for a M bounty especially.

**Comment by jeluard** [comment]
Diawi links are already in our `Jenkins` files so it's a matter of correctly hooking this with github task.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x5bf80c9cc859baa2ec679c449b2b1e47b31ecc74](https://etherscan.io/address/0x5bf80c9cc859baa2ec679c449b2b1e47b31ecc74)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
@jeluard @andytudhope Hi! I've started on a solution for this: https://github.com/status-im/status-react/pull/4129 . Normally like to have a more or less fully tested solution before creating a PR but obviously by nature of this task, need the PR and jenkins to test and develop it!

I think it needs at least one reviewer's approval to unlock the jenkins build? If so, could you please do that? (i.e. a dummy approval to unlock jenkins, not really signifying changes are complete). :beers:

**Comment by pacamara** [comment]
Status of https://github.com/status-im/status-react/pull/4129 is now "ready" :)

**Comment by jeluard** [comment]
@pacamara Great job! I'm wondering if there is no better approach than using the API directly (we don't want to have a public GH token in the repo).

@PombeirP Can you comment on that?

**Comment by pacamara** [comment]
@jeluard Thanks! :beers:  We don't need the GH token in the repo, it's only using the existing GIT_HUB_TOKEN Jenkins credential. I.e. the token only is stored in Jenkins not github, and also does not get logged. Will add a note to the PR documenting which jenkins variables are used. (done)

**Comment by jeluard** [comment]
Oh right so comments would show up as Jenkins comments?

**Comment by pacamara** [comment]
Comments show up as as github comments :) The GIT_HUB_TOKEN credential enables the code in Jenkinsfile running on the jenkins server to post comments to github. You can see examples at the bottom of https://github.com/pacamara/status-react/pull/4 which is the PR I used to test this against. 

Screenie attached! Notes:
* the URLs in the examples are either fake or null, as in my tests it wasn't really uploading to diawi, but this doesn't affect the validity of the tests.
* the branch name in the case of the release will contain the version number, whereas here it's the temporary branch PR-4 created for the pull request build.
![githubcommentsexample](https://user-images.githubusercontent.com/19371062/39801534-0fa471f6-535b-11e8-813c-789fd53ddd93.png)

**Comment by jeluard** [comment]
Right, looks great!
Surely after we merge the PR it won't be your username sharing those comments?

**Comment by pacamara** [comment]
Cheers!  :D 
Right, I've hardcoded the username to "status-im", however per the note I just added to the PR, this could be factored out to a credential called GIT_HUB_USER if you prefer?

The tests in https://github.com/pacamara/status-react/pull/4 were run via that branch's Jenkinsfile, there I hardcoded the username to pacamara. If you look at https://github.com/pacamara/status-react/blob/develop_tj/Jenkinsfile you can see the evolution of the solution, as well as various hacks I made to get enough of the build working to make a valid test of the comments. PR https://github.com/status-im/status-react/pull/4129 is the cleaned-up version of those changes.
