### ISSUE TITLE
Share logic between Jenkins files

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3457]
### User Story

As a developer, I want to reduce code duplication between `Jenkins` files

### Description

*Type*: Feature

Our Jenkins files (`Jenkins`, `Jenkins.nightly`, `Jenkinsfile.parameters`and `Jenkins.release`)

Make sure those rely on a [shared file](https://jenkins.io/blog/2017/10/02/pipeline-templates-with-shared-libraries/). Some tasks will probably accept parameters relevant to the concrete task used.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x41a0b6fa1c5403e79aacf8c728c6564b85c5ca984212fa66d88e9e0d96f494d3](https://etherscan.io/tx/0x41a0b6fa1c5403e79aacf8c728c6564b85c5ca984212fa66d88e9e0d96f494d3)

**Comment by chadyj** [comment]
This has happened!

**Comment by pablanopete** [comment]
@guyghost could you please share your preferred address for this bounty to be paid out? There are some problems with the dashboard and we need to send this out of band. If you'd like you can email me directly at Chris.hutchinson@status.im if you wouldn't like to share here.

**Comment by guyghost** [comment]
@pablanopete my address 0x41B63B9A9F96abc4A71D3Be7A3d8DF68Ff176B73

Thanks
