### ISSUE TITLE
Let Jenkins build use all nodes

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3458]
### User Story

As a developer, I want to have fast Jenkins builds

### Description

*Type*: Feature

Our current Jenkins file hardcode node to [`macos1`](https://github.com/status-im/status-react/blob/develop/Jenkinsfile#L17).
Part of the build could run on Linux so relax this constraint.

**Comment by oskarth** [comment]
Also see https://github.com/status-im/status-react/issues/2880

@jeluard How do you imagine someone solving this without access to Jenkins?

**Comment by jeluard** [comment]
@oskarth Good point needs some more details for sure. Also are jenkins logs accessible to everyone?

**Comment by oskarth** [comment]
Not sure, for specific PRs possibly. But this one requires priv access and is maybe not a great bounty, unfortunately.
