### ISSUE TITLE
Done button in Recipient screen is hard to click since the clickable area is small

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3459]
### Description
*Type*: Bug

*Summary*: The "Done" button in "Recipient" screen is hard to click since the clickable area is really small. Let's make the whole row clickable like we have for "Got it" in "Sent transaction". It's confirmed with @denis-sharypin 

#### Expected behavior
Whole row is clickable and height of the button (from the keyboard to white line) is 54px

#### Actual behavior
Only small part of the button is clickable and height of the button is small

<img src="https://user-images.githubusercontent.com/7532782/36725226-eac7ccfc-1bb5-11e8-922e-350992c62c2b.png" width="300">

### Reproduction
- Open Status
- Go to Wallet
- Click Send transaction
- Choose recipient by entering its address 

### Additional Information
* Status version: nightly, Feb 27
* Operating System: iOS. 
* Not tested on Android yet

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 655.00
Contract address: [0x20ac9223d2765e08c43eea4e66abf7fdeef37486](https://etherscan.io/address/0x20ac9223d2765e08c43eea4e66abf7fdeef37486)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
