### ISSUE TITLE
Remove script dependency on develop

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3462]
### User Story

As a developer, I want a simple build workflow (no inter branch dependency)

### Description

*Type*: Feature

To get access to some build number information, this [script](https://github.com/status-im/status-react/blob/develop/ios/scripts/set_xcode_version.sh) requires the `develop` branch to be locally checkout. This has proved to make our workflow quite complex (including [Jenkins files](https://github.com/status-im/status-react/blob/develop/Jenkinsfile#L32)).

Simplify this script so that `develop` is not necessary anymore.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1400.00
Contract address: [0x0a6475d45f6e1078d92971577ea5fb027facf777](https://etherscan.io/address/0x0a6475d45f6e1078d92971577ea5fb027facf777)
Network: Mainnet
Paid to: jeluard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
