### ISSUE TITLE
No messages received in Group Chat by old members after admin removed a contact from GroupChat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3463]
***Type***: Bug

***Summary***: Messages are not received by Group Chat members who stayed in the GC after removing one (or more) other GroupChat members by admin.

#### Expected behavior
Messages are received in Group Chat by old members after admin removed a contact from GroupChat
#### Actual behavior
No messages received in Group Chat by old members after admin removed a contact from GroupChat

### Reproduction

- Open Status on Device 1, Device 2 and Device 3
- Create three accounts on each device (Contact 1, Contact 2 and Contact 3 respectively)
- Each contact adds another two in contacts 
- Contact 1 creates GroupChat with Contact2 and Contact3
- All contact can exchange with text messages fine 
- Contact 1 removes Contact 2 from the GroupChat members
- Contact 1 and Contact 3 send text message in GroupChat 

### Additional Information
* Status version: Develop (nightly 254th), Release 0.9.15
* Operating System: Android, iOS

#### Logs

TF for Device 1 above: https://app.testfairy.com/projects/4803590-status/builds/7782432/sessions/53/?accessToken=vot3zxvTSCj8KpqMiiwOEXF9Ick
TF for Device 3 above: https://app.testfairy.com/projects/4803622-status/builds/7782434/sessions/38/?accessToken=M1ePc9x7oEAZg6or8EbgRiu0waU

**Comment by lukaszfryc** [comment]
Not high priority anymore since admin can remove existing or add new members now (3221da4).

**Comment by Serhy** [comment]
I rechecked this issue in latest nightly develop build (357th in jenkins) and all fine!
Old chat members who left in the Group Chat after admin removed one participant - exchange messages fine!
Glad to close this issue!!
