### ISSUE TITLE
No messages are received in Group Chat by old members after admin adds a contact in GroupChat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3464]
***Type***: Bug

***Summary***: Old chat members does not receive messages after new member is added in group chat. 
**Note**: the newly added member and group chat admin - see the messages of each other. 

#### Expected behavior
Messages are received in Group Chat by old members after admin adds a contact in GroupChat
#### Actual behavior
No messages are received in Group Chat by old members after admin adds a contact in GroupChat

### Reproduction

- Open Status on Device 1, Device 2 and Device 3
- Create three accounts on each device (Contact 1, Contact 2 and Contact 3 respectively)
- Each contact adds another two in contacts 
- Contact 1 creates GroupChat with Contact2
- Both contacts can exchange by text messages fine 
- Contact 1 adds Contact 3 in the GroupChat
- Contact 1 and Contact 2 send text message in GroupChat 

### Additional Information
* Status version: Develop (nightly 254th), Release 0.9.15
* Operating System: Android, iOS

#### Logs

TF session for Contact 1 (GroupChat admin): https://app.testfairy.com/projects/4803590-status/builds/7782432/sessions/55/?accessToken=QeHjMERJgPhhXWOR-fTxoHWN9CY
TF session for Contact 2: https://app.testfairy.com/projects/4803622-status/builds/7782434/sessions/42/?accessToken=FA4IkZyigdarddehNoqdIUOrnhg

**Comment by lukaszfryc** [comment]
Not high priority anymore since admin can remove existing or add new members now (3221da4).

**Comment by Serhy** [comment]
Will re-check once https://github.com/status-im/status-react/issues/3892 is fixed.

**Comment by janherich** [comment]
@Serhy Can you please check #3892 and this ticket as well in https://github.com/status-im/status-react/pull/3904 (I know that there is still #3891 happening in the PR and I'm working on fix, but I don't think that should block testing other issues tackled by the PR)

**Comment by Serhy** [comment]
@janherich so in the latest builds of #3904 (Android: https://i.diawi.com/2TTctg and 
iOS: https://i.diawi.com/PMQ8J3) the #3892 issue still present.

However, current issue seem to be fixed, yes. 
Anyway, we can't close this issue until the fix for #3892 merged in develop (either in the scope of #3904 or another PR) and we re-check this bug in the scope of develop build.
