### ISSUE TITLE
Push notification is shown but no message received 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3467]
### Description

*Type*: Bug

*Summary*:  Push notification is shown but no message received
#### Expected behavior
Push notification is received. When open app then message is received too

#### Actual behavior
Push notification is received. When open app then no new messages are received even if wait for 10-15 minutes  

### Reproduction

1. transit app to background on device A
2. turn on airplane mode on device A
3. send message from device B to device A
4. close app on device B
5. wait 3-5 minutes
6. turn off airplane mode on device A

In result you will receive PN but not message

### Additional Information
* Status version: nightly build Feb 27
* Operating System: Android and iOS

**Comment by oskarth** [comment]
> so now it works for the simplest cases (like: entering background, turn off wifi, send message from another device, close app on another device, wait 2 minutes, open app, turn on wifi) but still sometimes messages are not received even if requested history timeframe is correct (it’s from the first “entering bg event” or “lost connection event” minus 60 seconds till now). When this happens PNs are received, which means that messages actually were sent, and i’m quite sure that device which should receive messages requests history and does this successfully (from logs), but messages don’t arrive. Also if in this case i log out from account and log in again, this initiates request for 24h history, but messages are not received anyway.

-- Roman from Slack re https://github.com/status-im/status-react/pull/3493

**Comment by pedropombeiro** [comment]
One way to fix this is with https://github.com/status-im/status-react/issues/3451 from the `#086-push-notif-v2` swarm. They are not mutually exclusive though.
