### ISSUE TITLE
Add accessibility labels for Profile screens

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3472]
### User Story
As an automation engineer I need accessibility labels to be added for specific elements so I could use them in my Appium scripts.

### Description
Accessibility labels are required for building stable mobile test automation solution. Please, add accessibility labels for all elements listed below.

#### Profile
- edit-button
- share-my-contact-code-button
- notifications-button
- network-button
- offline-messages-settings-button
- log-out-button
- profile-tab-button

<img src="https://user-images.githubusercontent.com/7532782/36791789-ff22e6e4-1c98-11e8-8ac8-d70026c1e5e4.png" width="300">

#### Edit profile
- done-button
- edit-profile-photo-button
- username-input
<img src="https://user-images.githubusercontent.com/7532782/36791876-36c25666-1c99-11e8-823d-34b1d88fe782.png" width="300">

#### Edit profile
- done-button
- edit-profile-photo-button
- username-input
<img src="https://user-images.githubusercontent.com/7532782/36791876-36c25666-1c99-11e8-823d-34b1d88fe782.png" width="300">

#### Contact code 
- done-button
- share-code-button
- qr-code-image
- address-text
<img src="https://user-images.githubusercontent.com/7532782/36792090-d10df338-1c99-11e8-81be-14236ffee265.png" width="300">

#### Log out
- cancel-button
- log-out-button
<img src="https://user-images.githubusercontent.com/7532782/36792182-1943ab7a-1c9a-11e8-8e97-88991f644130.png" width="300">

#### Network settings
- back-button
- network-item
  - connected-text 
<img src="https://user-images.githubusercontent.com/7532782/36792248-5a71b416-1c9a-11e8-9820-fcd542614db9.png" width="300">

#### Network settings details
- back-button
- network-details-text
<img src="https://user-images.githubusercontent.com/7532782/36792299-841f359a-1c9a-11e8-99b5-b46ae151626a.png" width="300">

#### Offline messages settings
- back-button
- mailserver-item
<img src="https://user-images.githubusercontent.com/7532782/36792339-a381cf7e-1c9a-11e8-8fde-c5e95d63ed0d.png" width="300">

**Comment by lukaszfryc** [comment]
#3394 is related

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 350.00
Contract address: [0x4e0e8508c75307d004bf3c3ba3f0efaef365c57a](https://etherscan.io/address/0x4e0e8508c75307d004bf3c3ba3f0efaef365c57a)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
