### ISSUE TITLE
No input field is shown if use emoji keyboard on iPhone 7 plus 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3474]
### Description

*Type*: Bug

*Summary*: only on big iOS screens (iphone 7 plus): When emoji keyboard is opened then no input field is shown, so user can't see what emoji are typed and can't see send button.
![16968](https://user-images.githubusercontent.com/6584810/36793545-f4ce9044-1c9d-11e8-81d8-ae187e926058.jpg)

#### Expected behavior
Input field and send button are shown, so user can see its content when typing emoji and can send them

#### Actual behavior
When emoji keyboard is opened then no input field is shown, so user can't see what emoji are typed and can't see send button.
### Reproduction
video (00:17) https://app.testfairy.com/projects/4803590-status/builds/7798752/sessions/18/?accessToken=iSJnsGm5/SNdV7BwOnDnljFZgTk
- Open Status
- Open 1:1 chat
- tap on emoji device keyboard and tap on emoji. Check if input field is shown and you can send typed emojis
- switch to text keyboard, type "hello" and switch to emoji keyboard. Tap on any emoji. Check if input field is shown and you can send typed emojis

### Additional Information
* Status version: nightly build Feb 28
* Operating System: iPhone 7 plus, iOS 11.0.3.

**Comment by lukaszfryc** [comment]
Happens on iPhone 6 as well. Tested on nightly from March 1.

**Comment by lukaszfryc** [comment]
Android works fine.

**Comment by alwx** [comment]
Tested the latest `develop` on iPhone 6s, 7 and 7 Plus, everything works fine.

**Comment by annadanchenko** [comment]
Can reproduce on the real iphone 7 plus on last nightly build (March 13)
See from 00:10 https://app.testfairy.com/projects/4803590-status/builds/7880187/sessions/2/?accessToken=5j0kkP33JJ50MYk1cW7jHJ8/2ro

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb6cd29983714ccde9fbdeafb3ef8fcb072bc4b301288610657b6e1d6edb62a1d](https://etherscan.io/tx/0xb6cd29983714ccde9fbdeafb3ef8fcb072bc4b301288610657b6e1d6edb62a1d)

**Comment by annadanchenko** [comment]
can;t repro on 0.9.33
