### ISSUE TITLE
Add accessibility labels for New Chat screens

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3477]
### User Story
As an automation engineer I need accessibility labels to be added for specific elements so I could use them in my Appium scripts.

### Description
Accessibility labels are required for building stable mobile test automation solution. Please, add accessibility labels for all elements listed below.

### Related Issues
- #3394
- #3472

#### New chat
- back-button
- start-1-1-chat-button
- start-group-chat-button
- join-public-chat-button
- open-dapp-button
- invite-friends-button
<img src="https://user-images.githubusercontent.com/7532782/36796546-0bd21bc8-1ca6-11e8-92bc-f069edf19c34.png" width="300">

#### New 1-1 chat
- back-button
- done-button (if contact is selected)
- enter-contact-code-input
- scan-contact-code-button
- contact-item
<img src="https://user-images.githubusercontent.com/7532782/36796665-5de7b0a8-1ca6-11e8-99e5-88289e3d5275.png" width="300">

#### Scan contact QR code
- back-button
<img src="https://user-images.githubusercontent.com/7532782/36796877-e3304842-1ca6-11e8-94a9-a6e5b0161c6b.png" width="300">

#### New group chat
- back-button
- next-button (if contact is selected)
- contact-item
  - checkbox-button
<img src="https://user-images.githubusercontent.com/7532782/36796778-af01bd62-1ca6-11e8-8866-17f0c1c96490.png" width="300">

#### Provide group chat name
- back-button
- create-button
- chat-name-input
- chat-member-item
<img src="https://user-images.githubusercontent.com/7532782/36797019-4046cefc-1ca7-11e8-8afb-8a5247b0f8d5.png" width="300">

#### Join public chat
- back-button
- next-button
- chat-name-input
<img src="https://user-images.githubusercontent.com/7532782/36796942-0983d694-1ca7-11e8-9eb6-eb240347e43c.png" width="300">

#### Open DApp
- back-button
- dapp-url-input
- dapp-item
  - dapp-name
<img src="https://user-images.githubusercontent.com/7532782/36797224-b6c5d3f2-1ca7-11e8-9575-9387ac9c8a2b.png" width="300">

#### DApp profile
- back-button
- dapp-name-text
- open-dapp-button
<img src="https://user-images.githubusercontent.com/7532782/36797302-e2b92644-1ca7-11e8-9ab4-4bf56914772c.png" width="300">

#### DApp screen
- back-button
- dapp-name-text
- previou-page-button
- next-page-button
<img src="https://user-images.githubusercontent.com/7532782/36797359-06969ace-1ca8-11e8-99c2-ec374fc2662c.png" width="300">

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 350.00
Contract address: [0x27bf54bb6a06ea735fd2fa948f4d10514566f750](https://etherscan.io/address/0x27bf54bb6a06ea735fd2fa948f4d10514566f750)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by foopang** [comment]
@lukaszfryc I think **Join public chat** is outdated in your screenshot. There are some items missing. I assume you want to provide accessibility labels for that?

![screenshot from 2018-03-13 11-08-23](https://user-images.githubusercontent.com/4666757/37320515-fed8bbb2-26ae-11e8-9f5d-89da0c89ef4a.png)

**Comment by lukaszfryc** [comment]
@foopang yes, please provide labels for the list of items like "status", "openbounty". The label can be named "chat-item".
