### ISSUE TITLE
Add accessibility labels for Chat screens

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3479]
### User Story
As an automation engineer I need accessibility labels to be added for specific elements so I could use them in my Appium scripts.

### Description
Accessibility labels are required for building stable mobile test automation solution. Please, add accessibility labels for all elements listed below.

### Related Issues
- #3394
- #3472
- #3477

#### Home
- new-chat-button
- chat-item
  - chat-name-text
  - chat-url-text
  - no-messages-text
  - unread-messages-count-text
  - last-message-time-text
- home-button
<img src="https://user-images.githubusercontent.com/7532782/36801540-b87a1950-1cb2-11e8-96af-666e66f0bc39.png" width="300">

#### Chat
- back-button
- chat-name-text
- last-seen-text
- chat-menu-button
- add-to-contacts-button
- chat-item
- type-message-input
- chat-commands-button
<img src="https://user-images.githubusercontent.com/7532782/36801689-0ec3f434-1cb3-11e8-867c-2925e995776a.png" width="300">

#### Chat commands
- request-payment-button
- send-payment-button
- send-message-button
<img src="https://user-images.githubusercontent.com/7532782/36802238-b5a76028-1cb4-11e8-9624-553dad794553.png" width="300">

#### Send payment in chat
- amount-text
- fee-text
- adjust-fee-slider-button
<img src="https://user-images.githubusercontent.com/7532782/36802324-e184bf60-1cb4-11e8-93ca-4ca958c4118c.png" width="300">

#### Chat menu
- view-profile-button
- delete-chat-button
- cancel-button
<img src="https://user-images.githubusercontent.com/7532782/36801803-564d9da0-1cb3-11e8-8004-666a6079cf89.png" width="300">

#### Contact profile
- back-button
- options-button
- in-contacts-button and add-to-contacts-button
- start-conversation-button
- send-transaction-button
- wallet-address-text
- wallet-address-menu
- public-key-text
- public-key-menu
<img src="https://user-images.githubusercontent.com/7532782/36801894-8f2bab12-1cb3-11e8-9a3c-d46481f69b6a.png" width="300">

#### Contact profile menu
- remove-from-contacts-button
- cancel-button
<img src="https://user-images.githubusercontent.com/7532782/36802002-d1f6e0c4-1cb3-11e8-8811-234f8ee7c4f3.png" width="300">

#### Group chat menu / Public chat menu
- view-chat-settings-button
- delete-chat-button
- leave-group-chat-button
- cancel-button
<img src="https://user-images.githubusercontent.com/7532782/36802435-26cd61c6-1cb5-11e8-9eca-cf4822d9bbff.png" width="300">

#### Group chat settings
- back-button
- chat-name-input
- add-members-button
- member-item
  - member-name-text
  - menu-option
- mute-notifications-button
- clear-history-button
- leave-chat-button
<img src="https://user-images.githubusercontent.com/7532782/36802551-83a62978-1cb5-11e8-8ebb-8e72161b0d62.png" width="300">

#### Public chat settings
- back-button
- chat-name-input
- mute-notifications-button
- clear-history-button
- leave-chat-button
<img src="https://user-images.githubusercontent.com/7532782/36802689-e5ce8258-1cb5-11e8-9830-1e6de868d51c.png" width="300">

#### Add chat members
- back-button
- save-button
- member-item
  - member-name-text
  - checkbox-button
<img src="https://user-images.githubusercontent.com/7532782/36802580-9f899094-1cb5-11e8-897e-082784c0636e.png" width="300">

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 700.00
Contract address: [0x0391227f3f673d658d79785f20472e508945f362](https://etherscan.io/address/0x0391227f3f673d658d79785f20472e508945f362)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by lukaszfryc** [comment]
@foopang would you be interested in implementing it?

**Comment by foopang** [comment]
@lukaszfryc sure, I will work on it tomorrow. But again, accessibility labels cannot be added for those OS native menu items.

**Comment by lukaszfryc** [comment]
@foopang yes. Let's skip them.
