### ISSUE TITLE
whats this purple bar?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#348]
on develop branch, on first run and in chat, contacts the top bar of android is purple instead of the appropriate colour for each design? potentially related to #344 

![purple-bar](https://cloud.githubusercontent.com/assets/2714786/19385140/ae813e64-923f-11e6-95ff-074e5d745463.png)

**Comment by alwx** [comment]
what's your android version?

**Comment by jarradh** [comment]
This test is on Samsung Galaxy S7 Edge running 6.0.1

**Comment by rasom** [comment]
fixed in #345
