### ISSUE TITLE
Increase tap zones for rows with checkboxes

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3485]
### User Story

As a user, I want to tap at any place of a row with a checkbox so it will be selected without extra hustle.

### Description

*Type*: Feature

In the current implementation, you have to make a precise tap to a checkbox which is not convenient.
It's better to expand an tap zone to the whole row for lists elements with checkboxes. 

This functionality could be found in the following cases:
1. Choosing members for group chats
2. Adding member to a group chat
3. Filtering transaction history
4. Managing assets screen in the wallet

#### Expected behavior
Increased tap zone for rows with checkboxes
<img width="439" alt="screenshot 2018-03-01 11 19 18" src="https://user-images.githubusercontent.com/6559881/36839463-71466594-1d42-11e8-92ac-db4e6409993c.png">

#### Actual behavior
Small tap zone for rows with checkboxes
<img width="460" alt="screenshot 2018-03-01 11 19 22" src="https://user-images.githubusercontent.com/6559881/36839478-7d4fcbfa-1d42-11e8-8753-5dfeb9e3e49c.png">

### Choosing members for group chats
- Open Status
- Tap the plus button on the home screen
- Tap the Start group chat button

### Adding member to a group chat
- In the created group chat 3 dots in the right corner
- Choose Group info
- Tap Add members

### Filtering transaction history
- Choose wallet tab on the tab bar
- Tap Transaction History
- Tap 3 lines icon in the right corner

### Managing assets screen in the wallet
- Choose wallet tab on the tab bar
- Tap 3 dots in the right corner of the screen
- Choose Manage assets

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 700.00
Contract address: [0xe9545844f693bf3e4102c5ac0434e8da09b4db7c](https://etherscan.io/address/0xe9545844f693bf3e4102c5ac0434e8da09b4db7c)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
