### ISSUE TITLE
Notifications about previous messages should disappear when chat is opened

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3487]
### Description
*Type*: Bug

*Summary*: Let's say you have 3 notifications about messages for one chat. When the last notification is clicked which opens the chat. Now, the previous 2 notifications should probably be dismissed. The messages were already seen by the user. Instead, user needs to handle the notifications by herself. 

Ideally we should dismiss only notifications of messages that we are sure have been seen by the user. It may happen that there is some old message that user needs to scroll to see. But, the simple solution is to dismiss all related notifications when the chat is opened. I think it's much better than seeing 10 other notifications of a chat that was already seen (the case right now).

#### Expected behavior
Dismiss notifications when a chat was seen.

#### Actual behavior
Chat notifications stay even though the messages were seen.

### Reproduction
- User 1: Open Status
- User 2: Keep Status app in the background  
- User 1: Send 2 messages to User 2
- User 2: Click on the first message and open the chat with User 1
-> 2nd notification is still visible.

### Additional Information
* Status version: nightly, March 1
* Operating System: iOS, Android

**Comment by lukaszfryc** [comment]
It was not fixed by #86 nor #119 

@PombeirP are you aware of any swarm that can fix it?

**Comment by pedropombeiro** [comment]
@lukaszfryc https://github.com/status-im/ideas/blob/master/ideas/86-push-notif-v2.md is still in draft mode (it was closed in favor of a pull request to add a Markdown file). It should start soon.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/ideas">status-im/ideas</a></strong></div><div>ideas - Swarm Home. New, completed and in-progress features for Status</div></blockquote>

**Comment by lukaszfryc** [comment]
Any update on this issue?

**Comment by pedropombeiro** [comment]
Although this was planned to be fixed in 086-push-notif-v2, there's no reason why work can't start outside that scope. The work that needs to be done is well known (we should send message ID in PN payload (`data` field), and we should look into dismissing a PN once that message ID appears on screen)
