### ISSUE TITLE
Clicking message notification does not open the chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3488]
### Description
*Type*: Bug

*Summary*: Right now, clicking a chat notification opens latest visited screen (e.g. Profile). Instead, the chat containing the message should be opened. 

#### Expected behavior
When clicking a chat notification, chat with the message should be opened. 

#### Actual behavior
Last visited screen is opened. 

### Reproduction
- User 1: Open Status
- User 2: Go to Profile in Status
- User 2: Put Status app in the background
- User 1: Send a message to User 2
- User 2: Click on the message notification. The Profile screen opens.

### Additional Information
* Status version: nightly, March 1
* Operating System: iOS, Android

**Comment by asemiankevich** [comment]
Probably will be a part of https://github.com/status-im/ideas/issues/86,  i have added appropriate label so @lukaszfryc feel free to use it wherever you see related issues, i think it will help to collect them

**Comment by yenda** [comment]
It will require deep linking first

**Comment by lukaszfryc** [comment]
The issue is still valid.

**Comment by pedropombeiro** [comment]
This issue will be fixed within https://github.com/status-im/status-react/pull/6893
