### ISSUE TITLE
Edit photo needs to be tapped twice to open it. First tap dismisses the keyboard

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3489]
### Description
*Type*: Bug

*Summary*: When edit button is clicked in Profile the focus is put in the username input. This means that before user can click edit photo button she first needs to close the keyboard. In the end, 2 clicks are needed to open the edit photo. 

#### Expected behavior
Maybe the username input should not get the focus in the first place. When edit button is clicked the username is underlined which indicates that it's editable.  

#### Actual behavior
Keyboard appears immediately when edit profile button is clicked:

<img src="https://user-images.githubusercontent.com/7532782/36841854-058f6a32-1d4a-11e8-85d0-5da111914f7c.png" width="300">

### Reproduction
- Open Status
- Go to Profile
- Click Edit button

### Additional Information
* Status version: nightly, March 1
* Operating System: Android, iOS

**Comment by denis-sharypin** [comment]
fixed here https://github.com/status-im/status-react/issues/3678
