### ISSUE TITLE
"Confirm" headline should be changed to "Confirm password"

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3491]
### Description
*Type*: Bug

*Summary*: "Confirm" headline should be changed to more "Confirm password" to be more informative:

<img src="https://user-images.githubusercontent.com/7532782/36849338-14a2fc86-1d64-11e8-9122-52ea311e7763.png" width="300">

Note, that Zeplin design is correct, it says: "Confirm password":

<img src="https://user-images.githubusercontent.com/7532782/36849374-31d52cc0-1d64-11e8-9678-cf5c0e14e199.png" width="300">

### Reproduction
- Open Status
- Create new account

### Additional Information
* Status version: nightly, March 1
* Operating System: iOS, Android
* Part of #3326 (cc @flexsurfer)

**Comment by flexsurfer** [comment]
080 onboarding swarm are working on copies, so they all will be rewritten, so this issue is not relevant anymore
