### ISSUE TITLE
User still receives notifications from contact he has removed

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3497]
### Description
*Type*: Bug

*Summary*: User still receives notifications from a contact he has removed.

#### Expected behavior
When user removes a contact we may assume that he does not want to receive incoming message notifications from him. 

#### Actual behavior
There is no notification when first message is received from an unknown contact. **But**, when this contact is added and then removed the notifications are still being received.

### Reproduction
- Open Status
- User 1: Start a chat with User 2
- User 2: Accept User 1 as contact
- User 2: Delete User 1 from contacts
- User 2: Put Status in the background
- User 1: Send message to User 2. He sees notification

### Additional Information
* Status version: nightly, March 1
* Operating System: iOS 11.2.1. Not tested on Android

**Comment by lukaszfryc** [comment]
Currently, there is no option to remove a contact https://github.com/status-im/status-react/issues/3585 So, even when a chat is deleted, a new message will trigger a notification. This issue should be discussed again when #3585 is fixed.

**Comment by pedropombeiro** [comment]
https://github.com/status-im/status-react/pull/6893 will allow easily controlling whether to show a PN at the destination (just need to check if sender is in contacts before creating visual PN)
