### ISSUE TITLE
Minor UI glitch in QR code scan on Android

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3498]
### Description
*Type*: Bug

*Summary*: There is a strange strap while scanning qr code to choose recipient. Happens on Android only. I can reproduce it on Samsung Galaxy S8, Android 7.1.

#### Expected behavior
Screen does not have the strap. This area should be dimmed.

#### Actual behavior
<img src="https://user-images.githubusercontent.com/7532782/36856822-4255d802-1d77-11e8-8b42-ee1cebe6cd11.png" width="300">

### Reproduction
- Open Status
- Go to Wallet
- Click Send transaction
- Choose recipient by scanning qr code

### Additional Information
* Status version: nightly, March 1
* Operating System: Android, iOS
* Happens on Android only. iOS works fine

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc0e36ce2871d15b836ca22afc4e640997c1a5b2872824d8ef5d70cc652961356](https://etherscan.io/tx/0xc0e36ce2871d15b836ca22afc4e640997c1a5b2872824d8ef5d70cc652961356)

**Comment by okilimnik** [comment]
Cannot reproduce in current Google Play version (0.9.17)
Samsung J7 Android 7
Meizu M5s Android 6

**Comment by javier-tarazaga** [comment]
Which device and version of Android was this issue discovered? I have also tried the latest version of the app in Google Play and a Samsung S7 Edge with Android 8.0.0 and I couldn't reproduce the issue.

**Comment by lukaszfryc** [comment]
Still happens on my side. I tested on 0.9.23 on Samsung Galaxy S8, Android 7.1.

Looks like it affects only subset of Android phones. I'll add low-severity label.
