### ISSUE TITLE
No spinner when signing in to existing account 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3499]
### Description
*Type*: Bug

*Summary*: There is no spinner when signing in to existing account. Sign in button can be clicked multiple times. User may not understand that she is being signed in. 

#### Expected behavior
After clicking the sign in button there is an info (and spinner) that I'm being signed in. I understand what is happening.

#### Actual behavior
No spinner. User can interact with the screen (can edit inputs, press sign in multiple times, etc.)

### Reproduction
- Install Status
- Open the app
- Go to add existing account
- Provide passphrase and password. Then click sign in button 

### Additional Information
* Status version: nightly, March 1 (new onboarding screens, #3326)
* Operating System: Android, iOS

**Comment by yevh-berdnyk** [comment]
The same thing (but only on Android) for sign in to an account which already has been used on current device: spinner appears for a moment when tapping Sign in button and disappears after that.
To reproduce:

- Open Status
- Create an account
- Go to profile and log out
- Select the same user, provide password and click Sign in button
