### ISSUE TITLE
'Creating your account' view appears before name is set

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3503]
### Description

*Type*: Bug

*Summary*: When creating new user **Creating your account on the blockchain...** view and loading indicator appears before name input but should be after it

<img width="374" alt="screen shot 2018-03-02 at 12 22 18 am" src="https://user-images.githubusercontent.com/29711298/36872995-d85c7e0e-1daf-11e8-9e11-c4d2f555b48f.png">
#### Expected behavior
**Creating your account on the blockchain...** is shown after name is set
#### Actual behavior
**Creating your account on the blockchain...** is shown after password confirmation instead of Name input

### Reproduction
- Open Status
- Click Create new account
- Input password
- Input password once to confirm it
- Click Next button

### Additional Information
Status version: 0.9.11d.737 (develop build from 01.03.2018)
Operating System: 
iPhone 8 Plus, iOS 11.1.1
OnePlus 5, Android 8.0.0

**Comment by andmironov** [comment]
Nice point, although it was not an issue for UX test sessions participants
