### ISSUE TITLE
Error: No item 1 in vector of length 1

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3505]
### Description

*Type*: Bug

*Summary*: Error when relogin

`1:37 I/ReactNativeJS: NAME: "Error"
01:37 I/ReactNativeJS: MESSAGE: Error: No item 1 in vector of length 1
01:37 I/ReactNativeJS: 
01:37 I/ReactNativeJS: This error is located at:
01:37 I/ReactNativeJS:     in home
01:37 I/ReactNativeJS:     in reagent21
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in reagent20
01:37 I/ReactNativeJS:     in with-activity-indicator
01:37 I/ReactNativeJS:     in reagent18
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in main-tabs
01:37 I/ReactNativeJS:     in reagent17
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in main
01:37 I/ReactNativeJS:     in root
01:37 I/ReactNativeJS:     in reagent1
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in t`

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/36892295-5fded0ec-1e15-11e8-882e-1a9306a85181.png)

#### Scenario 1:
- Open Status
- Logout
- Login back and wait for some time
It happens also when deleting chat and loggin back

#### Scenario 2:
On Pixel XL Android 8.1.0/Galaxy S6 Android 6.0.1(Android only). Can't reproduce in Genymotion emulator Nexus 6P:
- Install Status
- Create account (share usage data)
- as soon as first screen shown - close the app (do not use any ui elements)
- run app
- log in and error is shown

Creating account: https://app.testfairy.com/projects/4803622-status/builds/7812304/sessions/23/?accessToken=SbPb3WEndfneUNeRjHdJHHY4u/U
Log in (error): https://app.testfairy.com/projects/4803622-status/builds/7812304/sessions/24/?accessToken=dk-8Z6AZxuXAkORAYxICvT5F6/k

### Additional Information
* Status version: latest nightly 260
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7812289/sessions/3/?accessToken=t8sODtp2IvtLTkVG4nOrqNGFttY

**Comment by yenda** [comment]
Note if this error shows up in the future:

If you deconstruct a vector and you don't pass a vector with enough items you get `No item 1 in vector of length 1` and somehow it won't necessary show up in develop mode.
So one of the first thing to check is reg-fxs and their calls

**Comment by yenda** [comment]
Race condition in the intialization sequence fixed by @dmitryn
