### ISSUE TITLE
Empty space below the "Type a message" input after sending ETH

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3508]
### Description
*Type*: Bug

*Summary*: After sending an asset and returning back to the chat the place for keyboard does not collapse. There is an empty space below the "Type a message" input. It does not happen on every device though. Can be reproduced on iPhone 6 but not on a faster device like iPhone X.  

<img src="https://user-images.githubusercontent.com/7532782/36907184-404713d4-1e38-11e8-8edd-6101fae5364f.png" width="300"> 

#### Expected behavior
There is no empty space. "Type a message" input is at the very bottom of the screen.

#### Actual behavior
There is an empty space. It fixes when user clicks on the input and keyboard appears.

### Reproduction
- Open Status
- Go to a chat
- Click `/send`
- **Expand the "Advanced" in Send transaction**
- Sign transaction
- Click "Got it" and return to the chat

### Additional Information
* Status version: nightly, March 2
* Operating System: iOS 11.2.1
* Device: iPhone 6
* Couldn't reproduce on iPhone X or Android devices

**Comment by lukaszfryc** [comment]
Can be reproduced on nightly from April 26

**Comment by annadanchenko** [comment]
@lukaszfryc can't reproduce on jun 17 nightly (ios and android). If you also can't repro, please close it

**Comment by lukaszfryc** [comment]
Can't reproduce it anymore. Tested on iPhone 6 and 8.
