### ISSUE TITLE
Default name is displayed for user who has not added back to contacts

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3510]
### Description

*Type*: Bug

*Summary*: When adding some user to contacts default name is displayed for him until he also adds me to contacts

![img_2d9131101abb-1](https://user-images.githubusercontent.com/29711298/36917728-44cc98c0-1e60-11e8-9ccf-c33f5fbf388e.jpeg)

#### Expected behavior
Contact is shown with a name selected by him

#### Actual behavior
Default name is shown on the chats, group chat and user's profile

### Reproduction
- Open Status
- Add some user to contacts scanning his QR code

### Additional Information
Status version: 0.9.10-740-gba056bee+, 0.9.11d740 (nightly build from 02.03)
Operating System: 
OnePlus 5, Android 8.0.0
iPhone 8+, iOS 11.1.1

**Comment by yenda** [comment]
This is normal behavior you cannot know the name of a contact until he adds you back.

**Comment by asemiankevich** [comment]
@yenda I do know this is working this way right now. We want to change it to work like any other messenger (viber or watsapp)

**Comment by yenda** [comment]
@asemiankevich Do I understand right what you want is:

- you add someone, he sees your name but you don't see hia name
- he adds you back and you see his name

If that's the case it's already in the new protocol
