### ISSUE TITLE
'Error on command handling' when requesting ETH in chat

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3513]
### Description

*Type*: Bug

*Summary*: Error appears when requesting funds in one-to-one chat and as added member in group chat with only 2 members

<img width="513" alt="screen shot 2018-03-02 at 11 10 44 pm" src="https://user-images.githubusercontent.com/29711298/36922770-c684db3c-1e71-11e8-9e47-2bb0691a1ed0.png">

#### Expected behavior
Request is sent without error

#### Actual behavior
'Error on command handling...' appears

### Reproduction
Group chat:
- Open Status
- User A creates a group chat with only 1 member - user B
- User B requests funds in the group chat

One-to-one chat:

- Open one-to-one chat between users A and B
- Send ~10 text messages from user A to user B and vice versa
- User A requests funds in 1-1 chat
- User B sends funds to the request
- User B requests funds
- User B requests funds again

### Additional Information
Status version: 0.9.10-740-gba056bee+ (nightly build from 02.03)
Operating System: 
Genymotion emulator Google Nexus 5, Android 6.0.0
Real devices: 
LG V20, Android 7.0
OnePlus 5, Android 8.0

#### Logs

```
1:17:15 D/ReactNativeJS: DEBUG [status-im.commands.handlers.jail:78] - Error on command handling 
["0x04b69daaca800324600393299016eec207a0a408fbddc99e22e159dc00c39a237428c8bcb6585
32445b07cb29cc0634d061d62af6766103e0423994e8c0233f81d" {:message "/request 0.000007", 
:command {:command {:description "Request a payment", :bot "transactor", :color "#5fc48d", :ref 
["transactor" :command 83 "request"], :name "request", :params [{:name "amount", :type "number"}], 
:type :command, :icon "money_white", :scope #{:global :personal-chats :registered :humans}, :title 
"Request ETH", :has-handler true, :preview {:markup ["view" {:style {:flexDirection "column"}} ["text" {} 
"Requesting  0.000007 ETH"]]}, :short-preview {:markup ["chat-preview-text" {} "Requesting  
0.000007 ETH"]}, :scope-bitmask 83, :owner-id "transactor"}, :params {:amount "0.000007", :bot-db 
nil}, :to-message nil, :created-at 1523026216687, :id "1523026216687-084c4ebe-3fca-5833-b5b6-
40a134c2f1e2", :chat-id 
"0x04b69daaca800324600393299016eec207a0a408fbddc99e22e159dc00c39a237428c8bcb6585
32445b07cb29cc0634d061d62af6766103e0423994e8c0233f81d"}, :chat-id 
"0x04b69daaca800324600393299016eec207a0a408fbddc99e22e159dc00c39a237428c8bcb6585
32445b07cb29cc0634d061d62af6766103e0423994e8c0233f81d", :identity 
"0x040d2783af435a5dfb38576de4d059c9ea5bfa77fbf733274f7c5c167215aaec9535fd6f993de60dd
a69c63882ed16957d799d4800887ceb5e1ae0878d325f420f", :address 
"49d7a03060792d171d661a12b15fde16feae6a46"} {:result {:returned {:event "request", :request 
{:command "send", :params {:amount "0.000007"}, :prefill ["0.000007"]}}, :context {}, :messages []}, 
:error "TypeError: null is not an object (evaluating 'params[\"bot-db\"]')", :bot-id "transactor"}]
```

**Comment by yevh-berdnyk** [comment]
Reproduced it for 1-1 chat in the latest nightly http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-74281a.apk



<blockquote></blockquote>

**Comment by asemiankevich** [comment]
i can reproduce it as well in latest nightly http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a0a795.apk

<blockquote></blockquote>
