### ISSUE TITLE
Cannot start 1-1 from public chat

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#3520]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

When i tap on profile pic on public chat member and select "Start conversation" then "Unknown" chat opened, but not 1-1 with that member.

I also see "chat.chat-id must be of type 'string', got 'null' (null)" error after i tapped "Start conversation".

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- join public chat (#bkk in my case)
- Tap on profile pic of any member
- Tap on "Start conversaion"

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: https://i.diawi.com/CTqLiU
[comment]: # (Android or iOS.)
* Operating System: Android (OnePlus 5)

![screenshot_20180305-132940](https://user-images.githubusercontent.com/23836/36960602-47407d44-207a-11e8-91f0-15b2f9d0b7c8.jpg)
![screenshot_20180305-132911](https://user-images.githubusercontent.com/23836/36960603-477e55c4-207a-11e8-87ca-d6a7f7332055.jpg)

**Comment by Marina-Kovalevich** [comment]
Also can't start 1-1 chat from group chat.
Opeating system: Android.
Status version: 2018/03/06 03:19:52 UTC
