### ISSUE TITLE
Metrics opt-in toggle in settings

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3538]
Add a toggle in Settings to opt-out of metric collection (for those already opted-in).

Related to https://github.com/status-im/status-react/issues/3537.

Possible copy that mirrors the onboarding opt-in:

Help improve Status?
Share anonymous usage data with Status to help improve the product. [Toggle]

**Comment by jeluard** [comment]
@denis-sharypin Could you add this to existing mockups?

**Comment by denis-sharypin** [comment]
@chadyj hey,
we are showing a screen ((it will be implemented) during onboarding where we describe stuff about metrics. I' think it would be consistent to reuse it one more time. Let me know what you think.

![metrics opt-in](https://user-images.githubusercontent.com/6559881/37416337-12c36a14-27e0-11e8-8915-56687ebc48f5.png)

**Comment by chadyj** [comment]
Thanks @denis-sharypin !

Nice idea to reuse the screen, since that has more info and context, and is familiar.

The implementation though seems a bit mixed. The setting doesn't have an arrow like the others that push to a new screen, just as the `Network` one above. It also seems at odds with `development mode` which is also a on/off switch, but is shown differently. And while I like the idea of combining onboarding with the setting, the button/toggle just feels wrong in that context as it misses the direct action and clarity of the button.

What do you think? Could we finesse just a little?

**Comment by denis-sharypin** [comment]
@chadyj  thanks for a feedback. 
For the second screen, you were right and I fixed it.
For the last screen: def we could use buttons but I believe we are missing an interface lightness.
Feel free to decide which option is better.
![metrics opt-in 02](https://user-images.githubusercontent.com/6559881/37550705-92d04a16-29c4-11e8-817d-c82cb77bd781.png)

**Comment by chadyj** [comment]
@jeluard @flexsurfer Any feedback on the designs?

**Comment by jeluard** [comment]
@chadyj @denis-sharypin Looks good! Maybe hard to spot diff between sharding on or off?

**Comment by denis-sharypin** [comment]
@jeluard 
The mockup with the second version of design could be found here: https://zpl.io/blN3WPG
When a user taps a button it pushes back to the main settings screen.  Focus of the screen should be the same as it was before (bottom of the screen).  State of the row should have changed from on to off or vice-versa.
User could easily spot diff between sharing on or off from the settings screen

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by jeluard** [comment]
@denis-sharypin Is the `Learn more` screen something we want during the onboarding process too? It's not there currently. BTW what does it points to?

**Comment by jeluard** [comment]
@denis-sharypin Also what do you think about having the exact same screen for both profile and onboarding? Currently the user activation part is slightly different.

**Comment by denis-sharypin** [comment]
@jeluard 
1. It will be fixed here https://github.com/status-im/status-react/issues/3539
2. I see what you mean, but this screen in the onboarding flow doesn't have any states because we show it once. But this screen should have states since it could be open by the user anytime

**Comment by jeluard** [comment]
@denis-sharypin About 2. : if we don't show both alternatives to users it forces them to change the sharing value even so they might navigate to this screen by mistake or curiosity.
Also I feel it's more consistent (and simpler :D) to have the exact same screen for both.

**Comment by chadyj** [comment]
Whatever the solution, can we make sure to keep the the onboarding as-is? 1 tap to opt-in is easier than a toggle then text. 1 tap should be the goal for signup.

**Comment by asemiankevich** [comment]
@jeluard @chadyj @nikitalukianov @denis-sharypin so what is the final decision ?

**Comment by jeluard** [comment]
@denis-sharypin WDYT?
