### ISSUE TITLE
`Help improve Status` learn more page

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3539]
Status asks new users if they would like to help improve the product by sending anonymous usage stats. To help users make an informed choice we will create a `learn more` page that explains what/why/how we collect data. This page is available from the opt-in screen shown during onboarding as well as the opt-in toggle in settings.

* [x] Create copy for page
* [x] Create page and host at https://wiki.status.im/Help_Improve_Status#Help_Improve_Status
* [ ] Link page from within the app: a) onboarding opt-in screen, b) settings opt-in toggle screen

**Comment by chadyj** [comment]
The wiki page is up at https://wiki.status.im/Help_Improve_Status#Help_Improve_Status

Final step is to add a `Learn more` link to the opt-in screen and settings opt-in toggle screen. This should open a web view of the wiki page that can be easily closed. (we don't want to take users away from the signup flow)

<img width="294" alt="learnmore" src="https://user-images.githubusercontent.com/116099/38026360-23c8afa2-328c-11e8-95fc-d706653e1be6.png">


<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Help_Improve_Status">Help Improve Status - Status Wiki</a></strong></div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 550.00
Contract address: [0x6dfdac64bc043ff5bed2fffd2661c85880589d75](https://etherscan.io/address/0x6dfdac64bc043ff5bed2fffd2661c85880589d75)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
