### ISSUE TITLE
Callback not working for requestMultiple

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3544]
### Description

*Type*: Bug

When prompting the user for a permission request the promise never executes the callback `.then` of `requestMultiple()`

See https://facebook.github.io/react-native/docs/permissionsandroid.html

#### Expected behavior
Callback is executed

#### Actual behavior
Callback is ignored

Blocks #3509 

### Acceptance criteria
When using camera for the first time in the app, the user should be prompted for permissions and camera should open without the workaround described in https://github.com/status-im/status-react/pull/3516

**Comment by jeluard** [comment]
@yenda Do you think this is a RN issue or a status issue?

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x617a9debce6c9f856b49f8eeae0852108342f45a99753ce4f0086d3020090951](https://etherscan.io/tx/0x617a9debce6c9f856b49f8eeae0852108342f45a99753ce4f0086d3020090951)

**Comment by dmitryn** [comment]
@andytudhope hey, this bounty seems "locked" here (PR closed 2 issues at once which is not supported yet). Should be processed manually i guess.

**Comment by dmitryn** [comment]
Related issue https://github.com/status-im/open-bounty/issues/357
