### ISSUE TITLE
pressend send password makes status so slow

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#355]
as soon as you press send on password message, status pauses for like 5-6 seconds and grinds to a halt, becoming very sluggish/slow ... 

I can see that this is because geth is instantiated at this point ?!

**Comment by adrian-tiberius** [comment]
I think this is fixed in `feature/#218`, since service was move to another process.

**Comment by rasom** [comment]
It works faster with separate process, but not instantly anyway

**Comment by rasom** [comment]
@jarradh, that's how it works on genymotion now, is it fast enough for now?

![ps](https://cloud.githubusercontent.com/assets/2364994/19559934/d7ecdd4a-96da-11e6-81fe-2848f10d157f.gif)

**Comment by jarradh** [comment]
yes thats fine
