### ISSUE TITLE
Prevent statusbot from moving issues from Contributor back to To Test queue

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3550]
### Description

When a Github issue is put in Contributor, the statusbot is moving it back to To Test queue. This triggers autotests rerun which is useless.

#### Expected behavior
Issue stays in Contributor

#### Actual behavior
Issue is moved from Contributor to To Test queue:

<img src="https://user-images.githubusercontent.com/7532782/37345869-247f3854-26ce-11e8-9072-990a0e9251b9.png" width="500">

[PR example](https://github.com/status-im/status-react/pull/3362#issuecomment-372665565)

**Comment by lukaszfryc** [comment]
@antdanchenko @jeluard do you have any idea how to fix it?

**Comment by lukaszfryc** [comment]
Some time ago I used to add a negative review which prevented statusbot from doing it. But, it’s not the way github reviews should be used. So, we need to fix it in a different way

**Comment by antdanchenko** [comment]
@PombeirP please, take a look

**Comment by pedropombeiro** [comment]
@lukaszfryc let's track the issue [here](https://github.com/status-im/status-github-bot/issues/20). I'll see if I can fix that tomorrow.
