### ISSUE TITLE
Faucet request error in latest nightly

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3551]
### Description

*Type*: Bug

*Summary*: i am receiving faucet request error in status ui however faucet seems to be alive http://51.15.45.169:3001/faucet-info

#### Expected behavior
no faucet error, can request some test eth

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/37346842-80ad8fb4-26e1-11e8-8a3f-d854f9a6caac.png)
### Reproduction

- Open Status
- Faucet funds

### Additional Information

* Status version: nightly 
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7880085/sessions/7/?accessToken=gCYnYgKktvQEnym4fR50Kyd9pPc

**Comment by dmitryn** [comment]
<img width="451" alt="screenshot 2018-03-13 17 46 06" src="https://user-images.githubusercontent.com/23836/37349030-8c7791a0-26e6-11e8-9917-6262677e2872.png">

Get this on current develop

**Comment by cammellos** [comment]
seems like it's working now in current develop branch, could it be a temporary issue with faucet server?
