### ISSUE TITLE
Upgrade Instabug SDK for new features

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3555]
Instabug has several new features that can be beneficial to the test, UX, and product teams, and will be useful as an enhanced source in OKR measurement.

Some of the new features:

> Enhanced User Steps: To easily reproduce the bug reports your users have encountered and reported, Instabug automatically tracks the steps users have taken in the app before a bug is reported or a crash has occurred. We are enhancing our User Steps making them more structured, readable; alongside with capturing more gestures so you easily collect the needed insights to solve your bugs faster. We are capturing your UI components from text to labels and bringing them associated with the bug reports for better understanding. For iOS, we are now capturing the tap, long press, force touch, swipe, scroll and the pinch gestures. Check out the structure of the user steps you will receive on your dashboard for iOS in our docs.
> 
> New Surveys Experience: The more you interact and collect feedback from your users the better you know what to build and how. In-App Surveys will help you gain more insights from your users. Definitely, keeping your users away from any disruption is a key, that’s why we enhanced the in-App Surveys to provide a better, seamless experience that will increase the surveys responses through a better showing and dismissal experience.
> 
> Support For Cross-Platform Apps. You’ll receive one token to be used in your initialization code, and all your bugs and chats will be grouped in the same place.
> 
> Network Performance Monitoring.  We alert you about the three most common network request errors: network request failures, network requests that timed out, and network requests that took too long to complete.

https://github.com/Instabug/instabug-reactnative

In addition to upgrading, we have switched from two project for iOS and Android, and have setup a new RN Instabug project.  Both iOS and Android now have a single shared token: `758630ed52864cbad9c5eeeac596c60c`.

This should be moved to the .env file (@dmitryn suggestion).

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x8dd56bbb479c0d9709bc44fb7baab10986c6a8c6](https://etherscan.io/address/0x8dd56bbb479c0d9709bc44fb7baab10986c6a8c6)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by FiberJW** [comment]
Do you mind if I tackled this?

Would this be getting off of your status-im/instabug-reactnative fork and upgrading to the latest 2.8.0 version? Do you imagine anything breaking to support the new features? Are their and things from your fork that would need to cherrypicked into the latest update?

Thanks

**Comment by chadyj** [comment]
@fiber-god Go for it!
Yes, see if you can use the official package to make future upgrades easier.

**Comment by chadyj** [comment]
In addition to upgrading, we have switched from two project for iOS and Android, and have setup a new RN Instabug project.  Both iOS and Android now have a single shared token: `758630ed52864cbad9c5eeeac596c60c`.

This should be moved to the .env file (@dmitryn suggestion).

**Comment by FiberJW** [comment]
Sorry, I just got swamped with a bunch of school work and it will be a while before I can tackle this. If anyone else wants this bounty, go for it!
