### ISSUE TITLE
Show the revision of status-go in the version label

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#3558]
blocked by
- https://github.com/status-im/status-go/issues/732 (status-go API for getting revision)
- https://github.com/status-im/status-react/issues/889 (version label)

### User Story

As a developer, I want to see the exact version of status-go in the UI of Status client.

### Description
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: the version label should display information about status-go in parenthesis (`status-go <short sha>`).

Too see how to handle new status-go API see: https://github.com/status-im/status-react/commit/b1ce44af3a1bd9b4fb8abb36c41707c88960623c

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 600.00
Contract address: [0x23b09c93872ae84fc87aa172b10838d8f4ecdf18](https://etherscan.io/address/0x23b09c93872ae84fc87aa172b10838d8f4ecdf18)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
