### ISSUE TITLE
Some messages were missing in the middle of 1-1 chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3562]
### Description
*Type*: Bug

*Summary*: When app was in the background it received ~70 messages from single 1-1 chat. When the chat was opened, some messages were missing. Scrolling up through messages and then loading them again by scrolling to the bottom to the last message fixed it. Note that it cannot be easily reproduced. It's happend only once for 5 tries.

#### Expected behavior
Chat contains all messages that have been sent.

#### Actual behavior
Some messages were missing:

<img src="https://user-images.githubusercontent.com/7532782/37401392-32e57786-2788-11e8-998a-231d99fab149.png" width="300">

Refreshing the chat by scrolling to the top and then scrolling back to see the messages fixed it.

### Steps I did
- Open Status
- Create 1-1 message with another user
- Kill the app
- The other user sends 70 messages
- Open the app again and log in
- Go to the 1-1 chat and see if there are no missing messages before the last received message.

### Additional Information
* Status version: nightly, March 14
* Operating System: iOS, not tried to reproduce on Android

**Comment by lukaszfryc** [comment]
Hey @janherich are your working on this? Do you need any help?

**Comment by janherich** [comment]
Hi @lukaszfryc I'm working on that as a part of the new protocol which will be hopefully merged very soon

**Comment by janherich** [comment]
This is already fixed in current develop, please make sure it's working and when yes, we can close it @lukaszfryc
