### ISSUE TITLE
Randomly generated name is shown for opponent until i am added to contacts

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3564]
### Description

*Type*: Bug

#### Expected behavior
Since we have new onboarding and I am able to set up my custom name right after I have my account being set I want this name to be shown for the people I am trying to add to my contacts list or want to chat with. I talked to @denis-sharypin and this  is accepted to be expected behavior. 

#### Actual behavior
Randomly generated user name is shown until i am added to contacts list

### Reproduction

- Open Status
- As Device A set up account and configure any name you like
- As Device A add any existing account to your contacts (device B)
- As device B Pay attention to the contact name

### Solution
This issue was discussed many times with @rasom and @flexsurfer - as far as i remember its not very complex fix.

### Additional Information
* Status version: nightly Mar 14
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
#3579 is related

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/3510 is more recent - closing this one
