### ISSUE TITLE
Validation error 'Password confirmation doesn't match password' is shown after you fix value in 'Confirm password'

### ISSUE THREAD

**Issue by churik** [status-im/status-react#3571]
### Description
*Type*: bug-bounty
*Summary*: on screen 'Confirm password' after typing wrong Password and appearing 'Password confirmation doesn't match password' is shows even you fix value in input field until you tap on 'Next'
![password](https://user-images.githubusercontent.com/4557972/37445509-286734c2-2821-11e8-80b3-cfb32408fce3.png) 

#### Expected behavior
'Password confirmation doesn't match password' disappears when you start to fix value in 'confirm password' field
* Note: expected behavior is based on experience with https://google.com

#### Actual behavior
'Password confirmation doesn't match password' doesn't disappear even when you entered correct value in 'confirm password' field
### Reproduction

- Open Status
- Tap on 'Create new account'
- Enter password, proceed to Confirm password
- Enter wrong password in 'Confirm password' field
- Fix value in  'Confirm password' field

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  Nightly build for March 15 (https://status-im.github.io/nightly/)
* Operating System: Android, iOS

#### Logs
* Video: http://take.ms/Jz0wxo

**Comment by andmironov** [comment]
+ we need to define how the error tooltips work when field becomes valid in general
