### ISSUE TITLE
List PRs based on a commit range

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3573]
### User Story

As a developer, I want an easy way to list PRs related to new commits in a release. 

### Description

*Type*: Feature

A simple script that takes a range as input (2 branches, tags or commits) and returns a list of all PRs that have contributed commits in this range.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 3984.88
Contract address: [0xa349771ebcd7e683aba7fb2551774050e0ee2d81](https://etherscan.io/address/0xa349771ebcd7e683aba7fb2551774050e0ee2d81)
Network: Mainnet
Paid to: jwagener
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
