### ISSUE TITLE
Document steps to setup iOS remote build

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3574]
### User Story

As a linux developer, I want to have an easy way to build .ipa remotely using a headless Mac

### Description

*Type*: Feature

Provide step by step documentation on how to setup remote iOS build from linux using a headless Mac machine.
It should be as easy as executing a command and getting the binary back (using `ssh` or similar).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3fe2c8954f380ef0b72215f13d05242b61e1a49d836069dde2ed41700ab6b4a6](https://etherscan.io/tx/0x3fe2c8954f380ef0b72215f13d05242b61e1a49d836069dde2ed41700ab6b4a6)

**Comment by endenwer** [comment]
@jeluard Can you present server for this task so I can test all steps from clean mac. Something like www.macincloud.com.

**Comment by jeluard** [comment]
@endenwer The idea is to reuse my own local mac machine, in a headless way.

**Comment by endenwer** [comment]
@jeluard I can document how to build .ipa on mac with installed dependencies (need to run `make setup` and have installed xcode). Is it something you need?

**Comment by jeluard** [comment]
What I need is the following: my computer is a linux machine. I have access via ssh to a remote mac (no screen no keyboard). 
I want a super easy way to get back the ipa from source code I am currently modifying.

**Comment by endenwer** [comment]
You basically want to do manually what Jenkins do. I can create `make` task for that and you just need to run it and download generated .ipa. But you need to setup your mac first.

**Comment by jeluard** [comment]
What would that make task do exactly?

**Comment by endenwer** [comment]
Install js dependencies, install lein dependencies, create prod build for ios and generate .ipa. That's what jenkins do now but also upload generated .ipa to diawi.

**Comment by jeluard** [comment]
We already have this part. This is the other side I am interested with.

**Comment by endenwer** [comment]
Sorry, I don't get what you need then.
As I understand you want to connect to your mac using ssh, run one command and download .ipa. Now there is no command that you can run to generate .ipa.

**Comment by jeluard** [comment]
No worries i will spend some time clarifying my needs.

**Comment by zacck-zz** [comment]
@jeluard  perhaps I can try this one out. 
So as I understand 

1. You have a developer on a linux machine 
2. Said developer edits some code and wants to test their work 
3. The developer should then be able to connect to a headless mac 
4. Push their code to the mac 
5. Have the mac build a `.ipa`
6. Then have the `.ipa` dowloaded back to their linux box 

Is this what you are aiming for?

**Comment by jeluard** [comment]
@zacck Sounds about right! Does that make sense? Any idea how to achieve that?

**Comment by zacck-zz** [comment]
@jeluard  It makes sense, I have some ideas on how do to do this.
Key seems to be figuring out how to communicate with a `headless` mac from Linux, everything else seems to be straightforward

**Comment by cammellos** [comment]
@jeluard seems what you want is some setup like:
`srcs` directories and output are shared between linux and the headless mac as `NFS` for example, that avoids having to `push` the code & `pull` the `ipa` each time.

**Comment by jeluard** [comment]
I'd rather have everything done over ssh (with tars and all). NFS sounds like an great way to have something broken all the time :D

**Comment by zacck-zz** [comment]
@cammellos good idea!  maybe instead we can only do `checkouts` instead of pushing all the code every time we can just push changes .... basically, use the mac as a ci machine

**Comment by cammellos** [comment]
@zacck I guess it depends how often you would like to regenerate the `ipa` and how fast you want your feedback loop.
I personally use `vnc` server on my mac and then just keep everything running with `fighweel` etc, so I can get a quick feedback loop using the simulator, loading files & genrating `ipa` is too slow for development, so seem like it solves a different problem, so `ssh`/`rsync` seems like it would do fine (`pushing` I am not sure, as you might clutter a bit the repo). I don't have really this use case, so best person to ask is @jeluard
