### ISSUE TITLE
Create clj script

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3575]
### User Story

As a developer, I want to have a simple hackable dev workflow.

### Description

*Type*: Feature

Provide a `clj` based script that offers similar feature as our `lein` script.
Specifically:
* prod builds
* figwheel+repl based dev

Keep existing lein script for now.
As a first step we might want to keep `package.json`. Later we can migrate to `:npm-deps` usage.

**Comment by dmitryn** [comment]
@jeluard do you suggest moving away from `lein` to using `deps.edn`? https://clojure.org/guides/deps_and_cli

<blockquote><img src="../images/clojure-logo-icon-32.png" width="48" align="right"><div><strong><a href="https://clojure.org/guides/deps_and_cli">Clojure - Deps and CLI Guide</a></strong></div></blockquote>

**Comment by jeluard** [comment]
Yes, maybe not soonish but at least investigate.

**Comment by dmitryn** [comment]
This repo provide an example of how it may work out https://github.com/aroemers/clojure-cli-tools-build

<blockquote><img src="https://avatars2.githubusercontent.com/u/1654946?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/aroemers/clojure-cli-tools-build">aroemers/clojure-cli-tools-build</a></strong></div><div>clojure-cli-tools-build - Example build script for developing ClojureScript projects using Clojure 1.9 CLI tools</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0xf2ec8a8c0c0c4bac68d38f9ea11ef1bccc8c56c2](https://etherscan.io/address/0xf2ec8a8c0c0c4bac68d38f9ea11ef1bccc8c56c2)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
