### ISSUE TITLE
Clicking send transaction in profile screen should open keyboard to specify amount 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3577]
### Description
*Type*: Bug

*Summary*: When "Send transaction" is clicked in profile screen, the "/send" command is placed into the chat input but the input does not have focus. In result, the keyboard and "Specify amount" popup are not present. 

#### Expected behavior
I'd expect that focus is put into the input to allow me to type transaction amount.

#### Actual behavior
"/send" is put into the chat input but the input does not have focus

### Reproduction
- Open Status
- Go to profile of a contact
- Click "Send transaction"

### Additional Information
* Status version: latest nightly
* Operating System: **Android only**, works on iOS

**Comment by churik** [comment]
@lukaszfryc it is still reproducible?

**Comment by lukaszfryc** [comment]
I think so. Anyway it's so low prio that I'd close it.
