### ISSUE TITLE
Avatar should be displayed on the same line as the bottom of the message instead of its top

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3587]
### Description

*Type*: Bug
See issue marked with "2": Avatar next to the message is shown on the same line as username while in designs it's shown on the same line as the last line of the message
![img_1976](https://user-images.githubusercontent.com/6584810/37472195-c6ea6ae8-286b-11e8-8ca1-7d90cced11c7.jpg)

design
<img width="377" alt="screen shot 2018-03-15 at 15 29 03" src="https://user-images.githubusercontent.com/6584810/37472281-f9492af6-286b-11e8-9109-b7cc402b575e.png">

### Reproduction

- Open Status
- Open 1:1 chat 
- Send some message that is 2-3 lines long and check where is your avatar displayed 

### Additional Information
* Status version: PR-3255
* Operating System: Android and iOS

**Comment by denis-sharypin** [comment]
👀

**Comment by annadanchenko** [comment]
looks ok in recent builds
