### ISSUE TITLE
"There are no messages in this chat yet" is left-aligned instead of centred as in design

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3588]
### Description

*Type*: Bug

*Summary*: 
"There are no messages in this chat yet" is left-aligned instead of centred as in design
Now:
![32743](https://user-images.githubusercontent.com/6584810/37472739-1661c200-286d-11e8-90df-a3c5d974344d.jpg)

Design:
<img width="372" alt="screen shot 2018-03-15 at 16 21 52" src="https://user-images.githubusercontent.com/6584810/37472732-1329e914-286d-11e8-9ace-af12ec701391.png">

### Reproduction
- Open Status
- Create new group chat or start 1:1 chat with new contact
- check the text shown in the empty chat window and its alignment

### Additional Information
* Status version: PR-3255
* Operating System: Android and iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Contract address: [0xe02fbffb3422ddb8e2227c3495f710ba4f8e0c10](https://etherscan.io/address/0xe02fbffb3422ddb8e2227c3495f710ba4f8e0c10)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
