### ISSUE TITLE
Crash after error Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3590]
### Description

*Type*: Bug

*Summary*: App hangs and crashes with error `Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference` if put app to background and then tap on Status icon on device screen to open it again. If try same steps in released 0.9.14 version then app is launched ok and can be used 

#### Expected behavior
App is launched with same state as it was before going to background

#### Actual behavior
Android 6.0.1 real Galaxy S6: error `Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference` is shown and app crashes
Android 8.1.0 real Pixel XL: app hangs and then system says that it does not respond

### Reproduction
TF (Android 6.0.1, real Galaxy S6) https://app.testfairy.com/projects/4803622-status/builds/7897877/sessions/10/?accessToken=5kYVrO3ZAvnfRKv5n0T7HD7hC1k
TF (Android 8.1.0 real Pixel XL): https://app.testfairy.com/projects/4803622-status/builds/7897610/sessions/2/?accessToken=7Nbd2KUO6Ii3dTRSdDKgyczuYKU
- Open Status
- Sign in
- move app to background
- tap on app icon on device screen

### Additional Information
* Status version: nightly build March 15
* Operating System: Android only

**Comment by lukaszfryc** [comment]
Same has happened for me on Samsung S8, Android 7.0. I tried to click on a notification when app was in the background.
