### ISSUE TITLE
url text is truncated in the middle so user can't see full link text when tapping on it

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3591]
### Description

*Type*: Bug
url sent to the chat is not fully shown because some text in the middle is replaced with "...". 
![screenshot_20180315-175227](https://user-images.githubusercontent.com/6584810/37478233-f3710d8e-2879-11e8-8522-d3d8c35d509d.png)

*Summary*: 

#### Expected behavior
According to the design we need to show full url text
<img width="364" alt="screen shot 2018-03-15 at 15 56 14" src="https://user-images.githubusercontent.com/6584810/37478320-2e5a13c8-287a-11e8-8c2c-00a26f615a7b.png">

#### Actual behavior
PArt of the url text in the middle is replaced with ...
### Reproduction

- Open Status
- Open 1:1 chat with Jarrad
- Send https://wiki.status.im/Send_Transaction_flow and check how it's displayed in the chat

### Additional Information
* Status version: nightly build March 14
* Operating System: Android and iOS

**Comment by naghdy** [comment]
I personally think truncation is better, because pasting really long URL's always turn out ugly. However, it could be used maliciously.

**Comment by yenda** [comment]
@naghdy unless we have a way to show the full URL on long tap for instance the most prudent thing to do is to always show the full URL

**Comment by naghdy** [comment]
Ok that makes sense.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x55be51b459d858d989e86a32def8e45fab13b242](https://etherscan.io/address/0x55be51b459d858d989e86a32def8e45fab13b242)
Network: Mainnet
Paid to: kixi
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by jeluard** [comment]
Apparently @lukaszfryc requested short URLS: https://github.com/status-im/status-react/pull/3299#issuecomment-368461587

**Comment by denis-sharypin** [comment]
I vote for always showing a full URL b/c of fishing cc @lukaszfryc

**Comment by lukaszfryc** [comment]
I think long urls have been truncated even before #3299. I suggested to
keep it this way. But, I agree that it could be used maliciously.
