### ISSUE TITLE
No message history appears until i send any new message to previously removed chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3599]
### Description

*Type*: Bug-Bounty

*Summary*: No message history until i type in the chat again after deletion

#### Expected behavior

If i deleted chat with a person i do see 2 possible options when i start chatting with him again:

1. totally new chat is created and started with no history as i removed it (like Viber, Watsap)
2. if we use offline inboxing and storing the messages they should appear immediately when i start the chat and not after i send new message there as this is confusing

#### Actual behavior
No message history until i type in the chat again after deletion

### Reproduction

- Open Status
- Open chat with Jarrad, send some messages, delete chat
- Start the chat again and dont send anything there - no history
- Send a message - history appears

### Additional Information
* Status version: nightly 03/16/2018
* Operating System: Android

**Comment by cammellos** [comment]
@asemiankevich this one should be fixed, when you delete a chat you won't be getting old messages anymore, could you make sure it's the case?
