### ISSUE TITLE
Can't open URL from chat in web browser

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3600]
### User Story

As a user I want to open sent/received URLs in web browser on my phone

### Description

*Type*: Bug-Bounty

*Summary*: Nothing happens when trying to open URL from a chat in web browser

#### Expected behavior
URL is opened in web browser 

#### Actual behavior
Application chooser dialog is hidden. URL is not opened

### Reproduction
- Open Status
- Navigate to a chat (one-to-one, group or public)
- Send some URL in the chat
- Tap the URL
- Tap 'Open in Web browser'

### Additional Information
* Status version: 0.9.10-776-g9cae0a5d+ (nightly build 277 from March 16)
* Operating System: 
Real device LG V20, Android 7.0
Real device iPhone 8+, iOS 11.1.1

**Comment by flexsurfer** [comment]
it reproduced for links without protocol, for example `google.com` for `http://google.com` it works
