### ISSUE TITLE
No guidance shown to change user picture when app is not allowed to access gallery (iOS)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3601]
### Description

*Type*: Bug-Bounty

*Summary*: When i restrict access of the status app to my pictures i want this ether to be asked again or any other visible and informative app feedback to user

#### Expected behavior
When the application is not able to access my photos i want this to be announced when i try to change my user picture

#### Actual behavior

I am still able to tap Edit - Select from gallery however nothing happens cause the app can't access my photos

### Reproduction
- Deny Status to access photos in Settings
- Open Status
- Go to Profile - tap Edit -> Select from gallery

### Additional Information
* Status version: nightly 03/16/2018
* Operating System: Android, iOS

**Comment by denis-sharypin** [comment]
It has to be designed before fixing. Let me do it

**Comment by denis-sharypin** [comment]
@asemiankevich  Also if you deny access to camera and chose Capture — app crashes. It was caught on nightly 17/03/18 and 0.9.14

**Comment by asemiankevich** [comment]
@denis-sharypin yeah this is known

**Comment by denis-sharypin** [comment]
Could you have a look if you have time @errorists ?
