### ISSUE TITLE
Tabs are visible along with keyboard when focusing on input field (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3603]
### Description

*Type*: Bug-Bounty

*Summary*: tabs are visible along with keyboard when focusing on input field

#### Expected behavior

when i focus on a input field keyboard is opened along with tabs so i can switch to tabs. As an edge case i can see keyboard overlapping wallet screen

#### Actual behavior

tabs are visible with keyboard

![image](https://user-images.githubusercontent.com/28752642/37533981-8265c7de-2954-11e8-944d-4ba75031a0a1.png)

### Reproduction

- Open Status
- Profile - Edit
- Wallet - Send - Specify amount

### Additional Information
* Status version: nightly 16/03/2018
* Operating System: Android

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7898835/sessions/45/?accessToken=YbcxvnxV4p4sQiLchj0Vmb0nFZI

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1300.00
Contract address: [0xce4647694612d1a1489375592faa618e6ce17ec8](https://etherscan.io/address/0xce4647694612d1a1489375592faa618e6ce17ec8)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by rasom** [comment]
@asemiankevich i can't reproduce this bug on real device using nightly, can you confirm that it still exists?

**Comment by asemiankevich** [comment]
@rasom just did that. Performed steps described + tapped Home

**Comment by rasom** [comment]
What device are you using?

**Comment by asemiankevich** [comment]
@rasom Huawei P10 Lite, Android 7.0
