### ISSUE TITLE
Wallet address is copied/shared without 0x prefix

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3606]
### User Story

As a user I want to share my wallet address so that other users can send me ETH.

### Description

*Type*: Bug-Bounty

*Summary*: Wallet address is shared and copied without 0x prefix 

#### Expected behavior
Wallet address is copied/shared with 0x prefix

#### Actual behavior
Wallet address is copied/shared without 0x prefix
<img width="413" alt="screen shot 2018-03-02 at 11 10 44 pm" src="https://user-images.githubusercontent.com/29711298/37537524-88ca0552-2956-11e8-82bc-1652030c159a.jpg">

### Reproduction

- Open Status
- Navigate to Wallet view
- Click Receive Transaction button
- Click Share button to share wallet address
- Select sharing method (e.g message or copy to clipboard)

### Additional Information
* Status version: 0.9.10-776-g9cae0a5d+ (nightly build 277 from March 16)
* Operating System:
Real device LG V20, Android 7.0
Real device iPhone 8+, iOS 11.1.1

**Comment by annadanchenko** [comment]
users can't send ETH from myetherwallet using address without 0x
