### ISSUE TITLE
Remove showing users profile from 'Creating New Chat' flow

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3609]
### User Story

As a user, I want to start a chat with a friend from a contact list without seeing his profile, so we need to delete this step from the flow.

### Description

*Type*:Bug

Delete step number 2 in the flow during you starting a chat with a user from your contacts 

![artboard](https://user-images.githubusercontent.com/6559881/37552114-34fd04ca-29e1-11e8-9866-b3406e5e4a15.png)

#### Expected behavior
Have a chat screen right after have chosen a user from contact list 

#### Actual behavior
Have a user's profile instead of seeing a screen with a chat

### Reproduction
- Open Status
-  Tap Plus button on the home tab
- Tap Start a new chat
- Tap on a user in the contacts list

### Additional Information
* Status version: 0.9.15
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 0.00
Contract address: [0x07aa907ff6179bd1d0cce6b875ce33e049d5647c](https://etherscan.io/address/0x07aa907ff6179bd1d0cce6b875ce33e049d5647c)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
