### ISSUE TITLE
Can't recieve new messages in Group Chat after it was deleted

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3610]
### Description

*Type*: Bug

*Summary*: When member deletes Group chat without leaving it, he is still shown to the rest of the members of the Group chat as a member but he has no access to this chat anymore.

#### Expected behavior
When member deletes Group chat he leaves it automatically by default.
Or as Viber has it: when member leaves Group Chat he recieves message like delete chat and leave it or don't recieve push notifications from this chat.

#### Actual behavior
Member deletes Group chat but other members still see him as a member, but he has no access to chat and doesn't see any further messages as this chat is not shown anymore.

### Reproduction
- Open Status
- Create GroupChat from device A
- Add to this Chat devices B and C
- Delete GroupChat from device A
- Check members of the Groupchat from device B or C
- Send some messages in this Chat

* Status version: Nightly Build 17/03/2018

* Operating System: Android

**Comment by asemiankevich** [comment]
@denis-sharypin please take a look!

**Comment by denis-sharypin** [comment]
@asemiankevich  yep, it's a bug.

**Comment by asemiankevich** [comment]
@denis-sharypin do we want any notification for user when deleting group chat ( like in Viber or something)?

**Comment by denis-sharypin** [comment]
@asemiankevich I believe we have it already!

**Comment by denis-sharypin** [comment]
No group chats anymore
