### ISSUE TITLE
No timestamp for Group Chat till messages are sent

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3611]
### Description

*Type*: Bug

*Summary*: No timestamp for Group chat creation on the homescreen till messages are sent. 
In Viber Group chat has timestamp of creation even if there is no messages in it.

#### Expected behavior
When Group chat is created it has timestamp on homescreen even there is no messages in it.

#### Actual behavior
No timestamp for new Group chat till some messages are sent.

### Reproduction
- Open Status
- Create Group Chat
- Check homescreen

![screenshot_2018-03-17-20-40-03-872_im status ethereum](https://user-images.githubusercontent.com/36479997/37558407-ab7ea700-2a24-11e8-9fb7-ae73e81d0f71.png)
![img-0555](https://user-images.githubusercontent.com/36479997/37558408-ad5d969e-2a24-11e8-989d-db1e4675587c.JPG)

* Status version: Nightly build 17/03/2018

* Operating System: Android

**Comment by asemiankevich** [comment]
@denis-sharypin is this some part of onboarding?

**Comment by denis-sharypin** [comment]
@asemiankevich nope
but let's add it, seems like a good idea

**Comment by asemiankevich** [comment]
@denis-sharypin let's make it a bounty! :)

**Comment by denis-sharypin** [comment]
@asemiankevich  could you double check on Android group chat icon is half shown. If so please create an issue from that. Thanks!

**Comment by asemiankevich** [comment]
@denis-sharypin on it

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1018.64
Contract address: [0x00c4650f3d64dd2ee31def87735174b351207c3a](https://etherscan.io/address/0x00c4650f3d64dd2ee31def87735174b351207c3a)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
