### ISSUE TITLE
User is redirected to previously opened Chat when sending transaction from user profile

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3612]
### Description

*Type*: Bug

*Summary*: When tap Send transaction from someone's profile user is redirected to the previously opened chat.

#### Expected behavior
When tap Send transaction in someone's profile, send transaction message must be shown in the chat with selected User.

#### Actual behavior
Previously opened chat is shown. If no chats were opened before user is redirected to Console chat.

### Reproduction
- Open Status
- Tap someone's profile (Jarrad)
- Tap send transaction

* Status version: Nightly build 17/03/2018

* Operating System: Android

**Comment by cammellos** [comment]
This one should be fixed by #3596

**Comment by cammellos** [comment]
Actually, correct that, might be fixed :)

**Comment by asemiankevich** [comment]
yes it is fixed now - other part (opening /send dialog) is here https://github.com/status-im/status-react/issues/3577
