### ISSUE TITLE
Error chat-id="{:updated-at nil, :unviewed-messages nil, :last-from-clock-value 0, :group-admin nil

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3619]
### Description

*Type*: Bug

*Summary*: Error `chat-id="{:updated-at nil, :unviewed-messages nil, :last-from-clock-value 0, :group-admin nil, :color \"#a187d5\", :contacts [{:identity \"0x044cc1996bbe9635ca48763c41e710700fd463b453ead0877e0b292b43aba0766ce7c4cda4c94487c4c3eb67bb6f8ed2ae6fdc653ed29895daf04aad81a3fbfd66\", :is-in-chat true}], :name \"%##}{]{#%^+=\u2022\xA3\u20AC$>~|\\\\_.??\u2019\", :requests nil, :removed-from-at nil, :contact-info \"{:whisper-identity \\\"0x044cc1996bbe9635ca48763c41e710700fd463b453ead0877e0b292b43aba0766ce7c4cda4c94487c4c3eb67bb6f8ed2ae6fdc653ed29895daf04aad81a3fbfd66\\\", :public-key \\\"38470eb05e06680c03fba05e2900b8094166d31af31f6159479496ae78326162ab335ee63e1177cc92ad85a7308abff9a4d37767fe9d538a5e952fd26bdca056c031f594c5b80db33e95f36bfbb135b6284b24ab41af251e2d992d6ec87ead82041\\\", :private-key \\\"384e32b962b237e14a99f5db4091f051554cadb4c9c041c3f2b40f264092e98c60295ff0df2a16bbb29ba7a09d510e128b5\\\", :address \\\"0dcd5cea2417ebadabff09f3c462d9d5a707c5e7\\\", :status \\\"fight for greater course than for greater loss\\\", :photo-path \\\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAMAAAC7IEhfAAADAFBMVEXw8PCy2IwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPF67jAAABAHRSTlP//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKmfXxgAABnNJREFUeNoBaAaX+QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEAAAAAAAABAQEBAQEAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAEBAQEBAQAAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAQEBAQEBAAAAAAAAAQEBAQEBAAAAAAAAAAAAAAABAQEBAQEAAAAAAAABAQEBAQEAAAAAAAABAQEBAQEA
00:55 I/HwPointEventFilter: do not support AFT because of no config`

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
able to remove chat

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/37587216-bd63d732-2b6f-11e8-9069-8d7ea5a7d8a1.png)

### Reproduction

- Open Status
- as iOS device set up `%##}{]{#%^+=•£€$>~|\_.??’` name in user profile 
- as Android - add iOS to contacts and send a message to 1x1 chat
- as Android - remove the chat with iOS device

### Additional Information

* Status version: nightly 19/03/2018
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7912666/sessions/44/?accessToken=6KPRNHVrcdeYdbBhAIkaNwE6bg8

`There was an error collecting entropy from the browser:
00:03 I/ReactNativeJS: { [TypeError: undefined is not an object (evaluating 'f.random')] line: 335, column: 471, sourceURL: 'index.android.bundle' }
00:05 I/ReactNativeJS: Running application "StatusIm" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
00:05 I/HwPointEventFilter: do not support AFT because of no config
00:06 I/hwaps: JNI_OnLoad
00:10 I/art: Do partial code cache collection, code=45KB, data=55KB
00:10 I/art: After code cache collection, code=42KB, data=53KB
00:10 I/art: Increasing code cache capacity to 256KB
00:35 I/HwSecImmHelper: mSecurityInputMethodService is null
00:38 I/HwSecImmHelper: mSecurityInputMethodService is null
00:38 I/HwSecImmHelper: mSecurityInputMethodService is null
00:39 I/WebViewFactory: Loading com.android.chrome version 60.0.3112.116 (code 311211652)
00:39 I/cr_LibraryLoader: Time to load native libraries: 4 ms (timestamps 8547-8551)
00:39 I/chromium: [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
00:39 I/cr_LibraryLoader: Expected native library version number "60.0.3112.116", actual native library version number "60.0.3112.116"
00:39 I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
00:39 I/ReactNativeJS: INFO [status-im.protocol.core:95] - offline inbox: flag enabled
00:39 I/ReactNativeJS: INFO [status-im.protocol.web3.filtering:27] - FLAG: many-whisper-topics-enabled OFF
00:40 I/ReactNativeJS: INFO [status-im.ui.screens.accounts.events:191] - Need to send account-update:  false
00:45 I/ReactNativeJS: INFO [status-im.protocol.handlers:289] - offline inbox: initialize
00:45 I/art: Do full code cache collection, code=119KB, data=125KB
00:45 I/art: After code cache collection, code=91KB, data=83KB
00:46 I/ReactNativeJS: INFO [status-im.protocol.handlers:298] - offline inbox: add-peer response enode://fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce@163.172.168.202:30303 true
00:46 I/ReactNativeJS: INFO [status-im.protocol.handlers:307] - offline inbox: fetch-peers response [{:id "03f3661686d30509d621dbe5ee2e3082923f25e94fd41a2dd8dd34bb12a0c4e8fbde52247c6c55e86dc209a8e7c4a5ae56058c65f7b01734d3ab73818b44e2a3", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["les/1" "les/2" "shh/6"], :network {:localAddress "192.168.1.36:50534", :remoteAddress "188.166.33.47:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}} {:id "90cbf961c87eb837adc1300a0a6722a57134d843f0028a976d35dff387f101a2754842b6b694e50a01093808f304440d4d968bcbc599259e895ff26e5a1a17cf", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["shh/6"], :network {:localAddress "192.168.1.36:35317", :remoteAddress "51.15.194.39:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}} {:id "dffef3874011709b12d1e540d83ddb19a9db8614ad9151d05bcf813585e45cbebba5aaea223fe315786c401d8cecb1ad2de9f179680c536ea30311fb21fa934b", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["les/1" "les/2" "shh/6"], :network {:localAddress "192.168.1.36:35802", :remoteAddress "188.166.100.178:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}} {:id "fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["shh/6"], :network {:localAddress "192.168.1.36:51349", :remoteAddress "163.172.168.202:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}}]
00:46 I/ReactNativeJS: INFO [status-im.protocol.handlers:328] - offline inbox: mark-trusted-peer response enode://fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce@163.172.168.202:30303 true
00:47 I/ReactNativeJS: INFO [status-im.protocol.handlers:337] - offline inbox: get-sym-key response 1e1d71bb27960aa1c5f5007cb749a775d379678826389c8b18233e0d8962dc2e
00:47 I/ReactNativeJS: INFO [status-im.protocol.web3.inbox:70] - offline inbox: sym-key-id 1e1d71bb27960aa1c5f5007cb749a775d379678826389c8b18233e0d8962dc2e
00:47 I/ReactNativeJS: INFO [status-im.protocol.web3.inbox:74] - offline inbox: request-messages request
00:47 I/ReactNativeJS: INFO [status-im.protocol.web3.inbox:75] - offline inbox: request-messages args {:mailServerPeer "enode://fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce@163.172.168.202:30303", :topic "0xaabb11ee", :symKeyID "1e1d71bb27960aa1c5f5007cb749a775d379678826389c8b18233e0d8962dc2e"}
00:47 I/ReactNativeJS: INFO [status-im.protocol.handlers:348] - offline inbox: request-messages response true
00:54 E/ReactNativeJS: 're-frame: no handler registered for effect: "', { ns: null,
00:54 E/ReactNativeJS:   name: 'delete-chat-messages',
00:54 E/ReactNativeJS:   fqn: 'delete-chat-messages',
00:54 E/ReactNativeJS:   _hash: 398932478,
00:54 E/ReactNativeJS:   'cljs$lang$protocol_mask$partition0$': 2153775105,
00:54 E/ReactNativeJS:   'cljs$lang$protocol_mask$partition1$': 4096 }, '". Ignoring.'
00:54 E/unknown:ReactNative: console.error: "re-frame: no handler registered for effect: "", {"ns":null,"name":"delete-chat-messages","fqn":"delete-chat-messages","_hash":398932478,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096}, "". Ignoring.", stack:
00:54 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$5@12:348480
00:54 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$4@12:348265
00:54 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$3@12:347993
00:54 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:347729
00:54 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:353001
00:54 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$variadic@12:4598088
00:54 E/unknown:ReactNative: <unknown>@12:4655643
00:54 E/unknown:ReactNative: invoke_interceptor_fn@12:4604667
00:54 E/unknown:ReactNative: invoke_interceptors@12:4604968
00:54 E/unknown:ReactNative: execute@12:4606586
00:54 E/unknown:ReactNative: handle@12:4616390
00:54 E/unknown:ReactNative: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@12:4651123
00:54 E/unknown:ReactNative: re_frame$router$IEventQueue$_run_queue$arity$1@12:4631859
00:54 E/unknown:ReactNative: <unknown>@12:4637611
00:54 E/unknown:ReactNative: re_frame$router$IEventQueue$_fsm_trigger$arity$3@12:4641822
00:54 E/unknown:ReactNative: <unknown>@12:4634377
00:54 E/unknown:ReactNative: <unknown>@32:1369
00:54 E/unknown:ReactNative: x@32:643
00:54 E/unknown:ReactNative: callTimers@32:2788
00:54 E/unknown:ReactNative: value@27:3582
00:54 E/unknown:ReactNative: <unknown>@27:1067
00:54 E/unknown:ReactNative: value@27:3009
00:54 E/unknown:ReactNative: value@27:1039`

**Comment by annadanchenko** [comment]
will be fixed in scope of https://github.com/status-im/ideas/issues/87

**Comment by lukaszfryc** [comment]
Note: Happens only for swipe to delete. It works fine when chat is removed from chat option menu (Delete chat)

**Comment by janherich** [comment]
@annadanchenko could you please check if this is already fixed in develop ? If yes, please close the issue

**Comment by asemiankevich** [comment]
@janherich i checked that in develop and can't reproduce anymore. Closing
