### ISSUE TITLE
Deleted chats are shown after relaunch

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3620]
### Description

*Type*: Bug

*Summary*: 

When I delete 1-1 chat(s) with previously read messages I had with another contacts (so no Unread message counter displayed on Chat screen), after I log out and log back in - all deleted chats reappear and display all messages I had with the contacts, that were deleted, - like they were Unread.
The main issue is that we should not resurrect deleted 1-1 chats at all.

#### Expected behavior
No deleted 1-1 chat appears if to log out and log back in to account

#### Actual behavior
Previously deleted 1-1 chat appears if to log out and log back in to account

### Reproduction
Open Status on Device1
Open Status on Device2
Create UserA on Device1
Create UserB on Device2
UserA adds UserB in contacts.
UserA sends message to UserB
UserB navigates to 1-1 Chat with UserA to read the message.
UserB navigates back to 'Chats' list. Confirm no unread messages counter present.
UserB deletes the chat with UserA
UserB logs out
UserB logs back in and stays on Chats list.

NOTE: the same for group chats and public chats
the same behavior is reproducible for `Leave  group chat`, not only for delete

### Additional Information
* Status version: 19/03/2018 nightly
* Operating System: Android, iOS

#### Logs
we did have the same issue https://github.com/status-im/status-react/issues/2870

**Comment by annadanchenko** [comment]
will be fixed in scope of https://github.com/status-im/ideas/issues/87

**Comment by oskarth** [comment]
When I delete chat using "Delete chat" option it appears to work as expected. When I delete chat using swipe-based deletion in iOS simulator I get the following error:

> re-frame: no handler registered for effect ... name: delete-chat-messages

The message then disappears. If I logout and login again I then see the chat that was swipe-deleted.

Thus it seems likely https://github.com/status-im/status-react/commit/502a28ec7a82894dea97e5ae0e7a9ceeef1cc9ca is the culprit.

@lukaszfryc @asemiankevich Please confirm if you see the same behavior.

**Comment by yenda** [comment]
No it's not  502a28e, the whole chat.events namespace is screwed, someone probably failed a rebase, there is events overwritten by wrong events, especially :remove-chat that is replaced by one using events that don't exist anymore.

**Comment by lukaszfryc** [comment]
@oskarth I see the same behaviour on my side.
