### ISSUE TITLE
No hint shown on transaction history screen when all filter checkboxes are unchecked

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3625]
### User Story

As a user if I uncheck all checkboxes in wallet transaction history I see blank field in transaction history. This may be confusing. 
If user don't have any transactions there is message "No transactions in your history yet". 
If there are no unsingned transactions there is message "You don't have any unsigned transactions"

### Description

*Type*: Bug

*Summary*: No hint that there is no transactions to display if all checkboxes are unchecked in wallet transaction history

#### Expected behavior
Message No transactions to display in transaction history if all checkboxes are unchecked.

#### Actual behavior
Blank field in transaction history in wallet.

### Reproduction

- Open Status
- Wallet->Transaction history
- Uncheck all checkboxes in filter history

![screenshot_2018-03-19-22-53-51-549_im status ethereum](https://user-images.githubusercontent.com/36479997/37619468-aaadc50c-2bca-11e8-83c3-974c213cf6ae.png)
![screenshot_2018-03-19-22-53-09-594_im status ethereum](https://user-images.githubusercontent.com/36479997/37619470-abd2240a-2bca-11e8-96bb-3e2ef370e984.png)
![screenshot_2018-03-19-22-52-29-849_im status ethereum](https://user-images.githubusercontent.com/36479997/37619478-af7153c4-2bca-11e8-9277-6713f64b66ff.png)

* Status version: Nightly build 19/03/2018

* Operating System: Android

**Comment by asemiankevich** [comment]
@denis-sharypin it may be confusing to the user if he faces with this edge case like I diselected all filters and forgot about it and then got back to transactions and saw this blank screen. What do you think?

**Comment by denis-sharypin** [comment]
On it!
