### ISSUE TITLE
Extra hyphenation of description text on the empty home tab 

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3629]
### User Story

As a user, I want to to see good right formatting.

### Description

*Type*: Bug

Delete extra hyphenation between first sentence and second. 

#### Expected behavior
![ios_signup_12_1 copy 18 1x](https://user-images.githubusercontent.com/6559881/37645340-2213f95c-2c59-11e8-988a-f63c3932347f.jpg)

#### Actual behavior
![img_3740](https://user-images.githubusercontent.com/6559881/37645295-032420bc-2c59-11e8-9674-8eb1ff409552.PNG)

### Additional Information
* Status version:  nightly 20.03.18
* Operating System: <Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x7b490424e030d25f211857071ac7c106eeb62792](https://etherscan.io/address/0x7b490424e030d25f211857071ac7c106eeb62792)
Network: Mainnet
Paid to: msuess
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
