### ISSUE TITLE
Wallet DApp Transaction History Messages

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#363]
When wallet sends a transaction (either via send command or via form) the chat history should populate, for alpha lets have a simple "Sent X ETH from Y to Z"

**Comment by alwx** [comment]
Just to be sure that I got it correctly: did you mean this transaction history?

<img width="361" alt="screen shot 2016-10-20 at 15 57 08" src="https://cloud.githubusercontent.com/assets/911127/19560630/efb13702-96dd-11e6-8252-d872dcc55cbd.png">

**Comment by rasom** [comment]
@jarradh should transactions that come outside the jail be in this history too?

**Comment by jarradh** [comment]
only the ones related to wallet dapp and its command (!send & !request)
