### ISSUE TITLE
Improve dynamic image sizing

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3630]
### User Story

As a user, I want to see that illustrations fits the screen of the app.

### Description

*Type*: Bug

Images that we are using in the app should have the dynamic size to properly fit the screen.  

#### Expected behavior
Image doesn't touch the grey line on the top
![right](https://user-images.githubusercontent.com/6559881/37646264-c7f840ba-2c5b-11e8-8cde-810b30c2e150.jpg)

#### Actual behavior
Image touches the grey line on the top
![img_3738](https://user-images.githubusercontent.com/6559881/37646206-99f2cf14-2c5b-11e8-9e4c-9325bc47f877.PNG)

### Additional Information

* Status version: Nightly 20.03.18
* Operating System: catch it on iPhone6, please double check on different devices.

**Comment by yevh-berdnyk** [comment]
Checked on Android, real device LG V20 and emulator Google Nexus 5:
<img width="605" alt="screen shot 2018-03-20 at 8 35 33 pm" src="https://user-images.githubusercontent.com/29711298/37675710-a312af42-2c7e-11e8-9862-b900701a3ef1.png">
