### ISSUE TITLE
Spinner disappears when sign in

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3635]
### User Story

As a user I want to where I am when performing sign in 

### Description

*Type*: Bug

*Summary*: When a user is signing in spinner disappears earlier than sign in is performed so user sees a screen with password input

#### Expected behavior
Spinner with info message is shown all the time while sign in is being performed 

#### Actual behavior
After Sign in button is tapped spinner is shown for a moment and after it disappears but user is not signed in yet

### Reproduction

- Open Status
- Create an account
- Go to profile and log out
- Select the same user, provide password and click Sign in button

### Additional Information
* Status version: 0.9.10-782-d4145a31a+
* Operating System:  LG V20, Android 7.0.0

**Comment by asemiankevich** [comment]
@yevh-berdnyk seems like a duplicate of https://github.com/status-im/status-react/issues/3499

**Comment by lukaszfryc** [comment]
Yes, I think it's a duplicate

**Comment by yevh-berdnyk** [comment]
@asemiankevich , @lukaszfryc the difference is this issue about login with newly created account (or any account which was already logged in with on current device) and #3499 (if I understood correctly) is about recovering account with passphrase

**Comment by asemiankevich** [comment]
yeah @yevh-berdnyk would you mind to keep it in any one issue? Having 2 separate does not look too much reasonable :) @lukaszfryc

**Comment by yevh-berdnyk** [comment]
@asemiankevich ok, I'll add a comment and close this issue
