### ISSUE TITLE
Can't add or remove group chat members

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3637]
### Description
*Type*: Bug

*Summary*: Since #3502 a group chat admin can't remove or add members. This should be fixed. 

#### Expected behavior
Group chat admin can add or remove members

#### Actual behavior
There is no option to add or remove group chat members by admin.

### Reproduction
- Open Status
- Create group chat
- Open group chat settings and try to add or remove a member

### Additional Information
* Status version: nightly, 21 March
* Operating System: iOS, Android

**Comment by oskarth** [comment]
In previous discussions around group chat we said we'd wanted to disable this for MVP/Beta to stay focused, so I propose we cut this from scope and flesh out proper group chat as part of a swarm. Thoughts?

cc @chadyj

**Comment by lukaszfryc** [comment]
@oskarth yes, I think we can remove it from the Beta scope. I can't remember when I wanted to add or remove a friend in Messanger group chat for example. It maybe very useful for chats with long history of messages. But, I think we are fine without it for the Beta. User can always create a new group chat.

**Comment by chadyj** [comment]
@lukaszfryc Can we apply the same thinking to other related issues?

**Comment by lukaszfryc** [comment]
@oskarth I will remove the bounty. This issue is already implemented and is just temporary disabled by #3502. Once we have the new protocol we can revert it to re-enable this feature (adding and removing group chat members).

**Comment by lukaszfryc** [comment]
Closing. Group chats are enabled
