### ISSUE TITLE
Persist browser history to allow to go back & forth when user returns to DApp

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3639]
### Description

*Type*: Feature

*Summary*: We have back & next buttons in Status browser. But, when you leave a Dapp (or web page) and then go back the browsing history is not persisted. Meaning, you can't press back button to go to a page you've been previously. I believe this would be a nice to have feature someday in the future.

#### Expected behavior
When returning to a dapp the browser history is restored. User can press back to go to previous page.

#### Actual behavior
Browser history is not persisted. When returning to a dapp, the back and next buttons can't be clicked.

### Reproduction

- Open Status
- Open dapp with custom url like google.com
- Click some links to go to different urls
- Now leave the dapp, go back to Chats screen
- Open the dapp again
- You can't press the back button because the browser history was not persisted 

### Additional Information
* Status version: nightly, March 21
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1800.00
Contract address: [0xf174ee769fbb10bda966c4fe56c7b682fade758f](https://etherscan.io/address/0xf174ee769fbb10bda966c4fe56c7b682fade758f)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by rachelhamlin** [comment]
Feels buggy not to have back option - https://insta.co/bugs/VQBI7BZZ_ZLLlr_s-gguVw

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://insta.co/bugs/VQBI7BZZ_ZLLlr_s-gguVw">Bug #VQBI7BZZ_ZLLlr_s-gguVw | Instabug</a></strong></div></blockquote>

**Comment by pacamara** [comment]
Hi @rachelhamlin @lukaszfryc Posted https://github.com/status-im/status-react/pull/4919 for this. Still a few tweaks left to do, but is 95% done and works already. :beers:

**Comment by rachelhamlin** [comment]
@pacamara yo, that's awesome. Thanks for your contribution! I'll look forward to testing it out.
