### ISSUE TITLE
No Join button when joining public chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3640]
### Description
*Type*: Bug

*Summary*: I think we miss "join" button in New Public Chat screen. It would be probably more clear if instead of pressing "Return" on native keyboard, the join button would appear in the top rigth corner. Or maybe "Return" text could change to "Join"?    

#### Expected behavior

<img src="https://user-images.githubusercontent.com/7532782/37719224-d29f6998-2d24-11e8-9947-54f81a82808c.png" width="300">

#### Actual behavior
There is only "Return" (iOS) or "Done" (Android) button.

### Reproduction
- Open Status
- Create new public chat

### Additional Information
* Status version: nightly, March 21
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@denis-sharypin wdyt?

**Comment by denis-sharypin** [comment]
@lukaszfryc Nice catch!
We will fix this by following mobile browsers behavior and simply change keyboard type.
![image](https://user-images.githubusercontent.com/6559881/37749856-8afd11b0-2dbc-11e8-8867-7a63df37b04e.png)

**Comment by denis-sharypin** [comment]
Please set a` keyboard type web-search` for this input

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 460.00
Contract address: [0xa521d679091c972657dc2518f127bead238b5c60](https://etherscan.io/address/0xa521d679091c972657dc2518f127bead238b5c60)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
