### ISSUE TITLE
"Welcome to Status" image has low quality on Samsung Galaxy S8 screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3642]
### Description
*Type*: Bug

*Summary*: Welcome to Status image is low quality on Samsung Galaxy S8 screen.

#### Expected behavior
Image is sharp

#### Actual behavior
Image is low quality.

### Reproduction
- Install Status
- Open Status on a device with high resolution like Galaxy S8

### Additional Information
* Status version: nightly, March 21
* Operating System: Android

**Comment by lukaszfryc** [comment]
Jarrad has mentioned it in Instabug report as well: 

<img src="https://user-images.githubusercontent.com/7532782/41024440-891dfdac-696f-11e8-857d-082b4102435c.png" width="200">

@denis-sharypin can you provide high-res image or svg?

**Comment by denis-sharypin** [comment]
For devices with the screen density 4 (xxxhdpi) please use this pic:
![welcome-image-xxxhdpi](https://user-images.githubusercontent.com/6559881/41087046-f46068bc-6a3b-11e8-992e-252b0d818aea.png)

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 700.00
Contract address: [0x68802a106598624489074c2a5e0b970e389a20c2](https://etherscan.io/address/0x68802a106598624489074c2a5e0b970e389a20c2)
Network: Mainnet
Paid to: alwx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
