### ISSUE TITLE
Can't open app settings on Android 8

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3644]
### Description

*Type*: Bug

*Summary*: On Android 8.0 it's impossible to open application settings from profile - error `The app wasn't found in the list of installed apps` is shown. Only reproducible on Android 8.0, checked on other devices and it's ok

#### Expected behavior
App settings is opened

#### Actual behavior
`The app wasn't found in the list of installed apps` error is shown

<img width="413" alt="screen shot 2018-03-21 22 27 15 pm" src="https://user-images.githubusercontent.com/29711298/37735570-1ff3121c-2d57-11e8-94ff-ea22cdc6f5bd.jpg">

### Reproduction
- Open Status
- Navigate to the profile
- Tap Notifications

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.10-786-g02d46c34+ (Mar 21 nightly build)
* Operating System: 
Real device OnePlus 5, Android 8.0.0
Emulator Google Pixel, Android 8.0.0

**Comment by asemiankevich** [comment]
@jeluard i remember this issue in PR but it was reproducible for Android 7 and u fixed that , would you mind to take a look?

**Comment by jeluard** [comment]
Sure! Just added in on the pile! ;)
