### ISSUE TITLE
Set "mainnet with upstream" from the profile screen as the default for dev/internal builds.

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3648]
### User Story

As a (dev/nightly) user, I want to use Status on Mainnet so that I can use wallet and Dapps properly.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

Mainnet is needed for a proper and realistic user experience when using Status. Currently all status-everyday testing and usage is on Testnet, however all beta use will be on Mainnet. In order to bridge this divide the default and primary experience for testing on dev/nightly should be on Mainnet in order to surface any potential issues before it gets in the hands of users.

NOTE: This does not impact alpha builds where Mainnet isn't available. This is only for dev/internal/nightly builds.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
A new install of nightly Status will have the default network set to Mainnet with Upstream RPC. 

Alpha release network settings should be unchanged.

#### Actual behavior
[comment]: # (Describe what actually happened.)
A new install of nightly Status has the default network set to Ropsten with upstream RPC

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account or recover
- Go to Profile, then Advanced
- View the Network setting

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

For dev/nightly builds change the default network from Ropsten with Upstream RPC to Mainnet with upstream RPC

@asemiankevich raised a point that we don't want to confuse nightly users that may be used to Testnet so we should edit the existing [warning message](https://github.com/status-im/status-react/blob/946a44d257bb3c2a76e128cf519e7c83b245b84c/src/status_im/translations/en.cljs#L379) to add

> You are using an app installed from a nightly build. **Do not send real ETH or SNT.** For testing purposes...

The app also currently shows a message on the send transactions screen letting users know about Mainnet saying  “You’re on the mainnet. Real ETH will be sent”.  Both of these should be a sufficient disclaimer.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 
All
* Operating System: <Android|iOS>
All

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9a389e624074fbdb4587bff9bc9a22a6f69f9b6e24a140727ac97bec99aa2d6d](https://etherscan.io/tx/0x9a389e624074fbdb4587bff9bc9a22a6f69f9b6e24a140727ac97bec99aa2d6d)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2200.00
Contract address: [0x5f289a636680e1a55e2842b7eae75395eeff5480](https://etherscan.io/address/0x5f289a636680e1a55e2842b7eae75395eeff5480)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
