### ISSUE TITLE
Open dapp button should be blue

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3650]
### Description

*Type*: Bug

*Summary*: Arrow and `_` sign should be blue by design

#### Expected behavior

![image](https://user-images.githubusercontent.com/28752642/37762371-2624ab48-2dcd-11e8-9800-d907ba16fbfb.png)

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/37762393-37aa32e8-2dcd-11e8-9db6-7026612d06fa.png)

![image](https://user-images.githubusercontent.com/28752642/37762412-42f23876-2dcd-11e8-9f5e-d70083b4b5a7.png)

### Reproduction

- Open Status
- Tap Open dapp
- Tap any dapp

### Additional Information

* Status version: nightly
* Operating System: Android, iOS

**Comment by flexsurfer** [comment]
@asemiankevich and also there should be background circle on Android, not only on ios

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 550.00
Contract address: [0x65f3a55352ba16e17ad37c94ee5678debd73044b](https://etherscan.io/address/0x65f3a55352ba16e17ad37c94ee5678debd73044b)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
