### ISSUE TITLE
Make Console icon style look like dev tool

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3651]
### User Story

As a developer, I want to see that console is more look like terminal/bash so that  I can trust it more and could find it through a list of chats easily.

### Description

*Type*: Feature

I would like to restyle a Console user pick and replaced empty state text to achieve the user story. 

The scope of the issue:
—  Rename Console to Status Console
—  Delete small icon with two dots 
—  Change the userpick and double check that size of it is 40px x 40 px
—  Change empty screen text to `Look under the hood! Console is a javascript runtime environment that exposes the whole web3 API. <br>Type "web3." to get started.`
—  Double check that console userpick is replaced in the chat view

#### Actual behavior
![artboard 2](https://user-images.githubusercontent.com/6559881/37752342-458e6242-2dca-11e8-8b51-8b22bebd155a.jpg)

#### Expected behavior 
![artboard 2 copy](https://user-images.githubusercontent.com/6559881/37752349-4fd6daae-2dca-11e8-80a1-9981dbdc3967.jpg)

### Additional Information
 Operating System: Android|iOS

**Comment by denis-sharypin** [comment]
Pic @2x:
![statusconsole 2x](https://user-images.githubusercontent.com/6559881/37766439-80602eb2-2df9-11e8-9784-52114c376037.png)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0xb247f56c74c8a805ec90130702ce0d063f2eb99e](https://etherscan.io/address/0xb247f56c74c8a805ec90130702ce0d063f2eb99e)
Network: Mainnet
Paid to: msuess
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by flexsurfer** [comment]
it should be svg not image

**Comment by msuess** [comment]
Taking a stab at this!
