### ISSUE TITLE
Add parameter for building the app with specified default network

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3654]
### User Story
As an automation engineer I would like an option to build an app with default network set to `Ropsten with upstream RPC' to be added

### Description
In order to run transaction automated tests against each PR on daily basis we need to build the app with default network set to 'Ropsten with upstream RPC' instead of 'Mainnet' (assuming that 'Mainnet' is going to be the default network when [#58](https://github.com/status-im/ideas/issues/58) is done)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x406dc24c61d08840f8be3488e267ea7edab2b66b](https://etherscan.io/address/0x406dc24c61d08840f8be3488e267ea7edab2b66b)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
