### ISSUE TITLE
Outdated name and profile picture are shown for contact who changed them when user was offline

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3666]
### Description

*Type*: Bug

*Summary*: When user changes his name and profile picture in the time when his contact is offline outdated name and picture are shown for the contact when he comes back online

#### Expected behavior
New name and profile picture are shown in user's A profile and a chat with him

#### Actual behavior
Outdated name and profile picture are shown in user's A profile and 1-1 chat

### Reproduction
- Open Status on two devices
- User A changes his profile picture and username
- Users A and B adds each other as contacts
- User B closes the app so it's not running on background
- User A changes his profile picture and username again
- User B opens the app and proceed to the user's A profile

### Additional Information
* Status version: 0.9.10-793-gd692ddc7+ (Mar 23 nightly build)
* Operating System:
Real device LG V20, Android 7.0
Real device iPhone 8+, iOS 11.1.1

**Comment by Serhy** [comment]
Can not reproduce anymore on 0.9.27 develop version. 
Closing this issue.
