### ISSUE TITLE
Show spinner when refreshing wallet on iOS

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3667]
### User Story

As a user, I want visual feedback showing wallet refreshed on iOS

### Description

*Type*: Bug

When refreshing wallet on iOS no spinner is shown.
Make sure a spinner is shown (can be for a fixed amount of time) while keeping a smoothing pulling (no jump)

**Comment by andytudhope** [comment]
Does there not need to be some design direction given here @jeluard @denis-sharypin?

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x611b1fe60ad0a46e558ca1f4f602aef501fd1496](https://etherscan.io/address/0x611b1fe60ad0a46e558ca1f4f602aef501fd1496)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by denis-sharypin** [comment]
You can spot an idea of how it should work here ( don't pay attention to the old wallet design) It should a typical pull-to-refresh behaviour 
https://framer.cloud/fBQyZ
