### ISSUE TITLE
Group chat profile doesn't show users who are not in the contacts list 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3670]
### User Story

As a user I want to see the other members of a group chat I was added to

### Description

*Type*: Bug

*Summary*: If members of a group chat didn't add each other as contacts their are not shown in the group chat's profile members list

#### Expected behavior
All group chat members and admin should be listed in the group chat profile

#### Actual behavior
'3 members' caption is shown in the group chat header but only one member (user A) who is in contacts is shown in group chat profile
<img width="630" alt="screen shot 2018-03-23 at 9 01 37 pm" src="https://user-images.githubusercontent.com/29711298/37848720-d6f58fbc-2edd-11e8-8449-5a55e68eeb37.png">

### Reproduction
- Open Status in two devices
- User A adds users B and C to contacts (users B and C are not contacts of each other)
- User A creates a group chat with users B and C
- User B views the group chat profile

### Additional Information

- Status version: 0.9.10-793-gd692ddc7+ (Mar 23 nightly build)
- Operating System:
Real device LG V20, Android 7.0
Real device iPhone 8+, iOS 11.1.1

**Comment by asemiankevich** [comment]
related to https://github.com/status-im/status-react/issues/3094

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1500.00
Contract address: [0x30a9122b1bb887f693605ed98b533ab2f59c14b0](https://etherscan.io/address/0x30a9122b1bb887f693605ed98b533ab2f59c14b0)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by lukaszfryc** [comment]
Already fixed as a part of bringing back group chats.
