### ISSUE TITLE
Add lookback integration for iOS

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3675]
### User Story

As a user, I want to be able to use [Lookback](https://lookback.io/) on iOS

### Description

*Type*: Feature

Make sure lookback work on iOS. An option is to integrate https://github.com/negativetwelve/react-native-lookback
Also provide details about the size and permission impact on the resulting ipa file.

Lookback must be disabled on release build by default and the lookback token must be configurable.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf74bba7007f0a9dec4e05ad529d1878f4d2eda2ca3575687596f29a91f775648](https://etherscan.io/tx/0xf74bba7007f0a9dec4e05ad529d1878f4d2eda2ca3575687596f29a91f775648)

**Comment by chadyj** [comment]
The new Instabug has a screen recording feature available. @hesterbruikman @jpbowen 
Not sure if it meets your needs, but check it out. Here is an example of a recording. https://insta.co/bugs/nfErq1qd

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://insta.co/bugs/nfErq1qd">Bug #nfErq1qd | Instabug</a></strong></div></blockquote>

**Comment by KriszNeumann** [comment]
Lookback Live and Self-Test for iOS both work with any prototype that can be publicly viewed in a browser using a URL. For example, InVision, Marvel, Axure, and Proto.io all allow for prototypes to be accessed via a browser whereas some others can only be viewed within their own app.

To use Lookback with a prototype that can viewed in a browser:

Go to your project settings (cog icon in upper right when viewing a project).
Set the URL of the prototype in the Landing page field in the settings pane.
