### ISSUE TITLE
Remove extra state for editing userpic  

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3678]
### User Story

As a user, I want to tap once on a userpick to edit it to get a context menu.

### Description

*Type*: Bug

Currently, while you are in the editing mode on the profile tab you have to tap twice on the userpick to open a context menu. Take a look at the Actual behavior

#### Actual behavior
![artboard](https://user-images.githubusercontent.com/6559881/37901473-7b3cbcf0-311b-11e8-8256-f81afd15982f.jpg)

#### Expected behavior
Remove `State 02`. After you tapped on an userpick a context menu should appear 

### Reproduction

- Open Status
- Go to `Profile` Tab
- Tap `Edit`
- Tap on userpick

### Additional Information

* Operating System:  Android and iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2200.00
Contract address: [0xf44da88ccabecdce7c62099c2d2fc08823b5479b](https://etherscan.io/address/0xf44da88ccabecdce7c62099c2d2fc08823b5479b)
Network: Mainnet
Paid to: kwingram25
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
