### ISSUE TITLE
No commands shown (release 0.9.16 branch)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3681]
### Description

*Type*: Bug

*Summary*: no commands shown on android and ios neither in console nor in chats

#### Expected behavior
/faucet , /debug , /send and /request are avaliable

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/37905871-f35d555e-3108-11e8-87d3-c9cb0b112434.png)

### Reproduction

- Open Status
- Turn on development mode
- Go to console and tap commands button
- go to 1x1 chat or group chat and tap commands button

### Additional Information
* Status version: release 0.9.16 branch
* Operating System: Android

**Comment by lukaszfryc** [comment]
Also, when receive request is sent from Wallet the message in 1-1 chat is not formatted properly:

<img src="https://user-images.githubusercontent.com/7532782/37959294-1770d54c-31b3-11e8-8039-b1ce24a43abe.png" width="300">

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1713924118c6394e42592d0c96620cb82b24d609728efc53b9bcf24a53cde88f](https://etherscan.io/tx/0x1713924118c6394e42592d0c96620cb82b24d609728efc53b9bcf24a53cde88f)

**Comment by dmitryn** [comment]
@asemiankevich not reproducible in develop on Nexus 5X - is it on release branch only?

**Comment by asemiankevich** [comment]
it was in last nightly and release @dmitryn

**Comment by lukaszfryc** [comment]
So maybe https://github.com/status-im/status-react/commit/49a53645fb9002ac038e89160aa259ddec2c6c3c fixed it. @alwx @dmitryn @jeluard any idea? Btw, it could be cherry picked to `release/0.9.16` anyway to make Andy even more happier :)

**Comment by dmitryn** [comment]
@lukaszfryc hard to tell, maybe that was a fix. I think it's easier to cherry-pick and check if it resolves the error in release/0.9.16

**Comment by lukaszfryc** [comment]
Does not work on iOS as well. Tested on iPhone 6, iOS 11.2.1

**Comment by flexsurfer** [comment]
Maybe some race conditions?

**Comment by dmitryn** [comment]
Not reproducible on real nexus 5x with develop build

**Comment by flexsurfer** [comment]
Not reproducible on real xiaomi with nightly build

**Comment by lukaszfryc** [comment]
Please try the release branch as well.

2018-03-28 17:17 GMT+02:00 Andrey Shovkoplyas <notifications@github.com>:

**Comment by alwx** [comment]
trying to understand and fix it.

got an information that it seems to work fine when JSC flag is set to 1.

**Comment by asemiankevich** [comment]
@alwx maybe 0 ? JSC is enabled by default i think

**Comment by lukaszfryc** [comment]
@alwx coud you create a built with it? @asemiankevich isn't it the same build you has made?

**Comment by alwx** [comment]
@asemiankevich sorry, 0, you're right. the issue was introduced here: https://github.com/status-im/status-react/commit/e0f42d28d7b8061141ca1eee266d94cb93d5a055
