### ISSUE TITLE
Spinner is missing for pull-to-refresh gesture (iOS)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3682]
### Description

*Type*: Bug

*Summary*: We have a `pull-to-refresh` gesture on main wallet screen that is currently missing spinner when i pull to refresh (iOS)

#### Expected behavior
i see spinner when i pull to refresh

![image](https://user-images.githubusercontent.com/28752642/37906479-ef2618de-310a-11e8-83e9-0b9d3bec2f92.png)

#### Actual behavior
no spinner

### Reproduction

- Open Status
- Go to wallet
- pull to refresh the screen

### Additional Information
* Status version: nightly 26/03/2018
* Operating System: iOS

**Comment by jeluard** [comment]
Duplicates https://github.com/status-im/status-react/issues/3667 ?
