### ISSUE TITLE
Advanced option does not autoscroll the screen up

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3683]
### Description

*Type*: Bug

*Summary*: When i tap `Advanced` button anywhere it exists - i dont want to scroll the screen - the options should appear via autoscroll 

#### Expected behavior
screen is autoscrolled when I tap Advanced so I dont need to scroll

#### Actual behavior
I need to scroll the screen to reach the Advanced options. Here is the list of them:

1. Home -> Profile -> advanced
2. Home -> 1x1 chat (Jarrad) -> Send transaction -> advanced
3. Home -> Open dapp -> Send transaction to dapp -> advanced
4. Home -> Group chat - Send transaction -> advanced

![image](https://user-images.githubusercontent.com/28752642/37906977-79b03aa6-310c-11e8-82da-b1a5934e5f84.png)

### Additional Information
* Status version: nightly 26/03/2018
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 700.00
Contract address: [0x6c818d5486229618a89c494cebfe9a776170df5c](https://etherscan.io/address/0x6c818d5486229618a89c494cebfe9a776170df5c)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
