### ISSUE TITLE
Move alert asking about Push Notifications (iOS) to the home tab

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3684]
### User Story

As a user, I want to have a better context before letting Status sends me Push Notifications so that I'll give this permission easily.

### Description

*Type*: Feature

Move permission alert asking about Push Notifications to the Home tab 

![slice](https://user-images.githubusercontent.com/6559881/37906782-56d13d02-312d-11e8-9123-e78634c04e91.jpg)

#### Expected behavior
Having this alert on the first run of the Home tab

#### Actual behavior
Having this alert on the first screen

### Additional Information
* Status version: nightly 
* Operating System: iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa88446f4af8af0e1e2369f4fc81061ce2691a0e6eb663eedc2c7f3a482400d03](https://etherscan.io/tx/0xa88446f4af8af0e1e2369f4fc81061ce2691a0e6eb663eedc2c7f3a482400d03)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2200.00
Contract address: [0x2ede3dc568b443a6f3b9885e80f7089cf44b97d3](https://etherscan.io/address/0x2ede3dc568b443a6f3b9885e80f7089cf44b97d3)
Network: Mainnet
Paid to: kwingram25
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
