### ISSUE TITLE
Remove JSC_ENABLED flag and turn on behavior by default

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#3689]
### User Story

As a developer, I want flags to reflect possible variables in app, so it's clear what configurations app can be in and options are minimized.

### Description

We always want to use JSC since this is required for App store releases, and behavior is stable enough.

*Type*: Feature/Tooling

*Summary*:  Remove JSC_Enabled flag everywhere and turn on behavior by default.

#### Expected behavior
No JSC_ENABLED flag

#### Actual behavior
JSC_ENABLED flag

### Additional Information
Additionally, we probably want to remove old jail code on status-go side, but this is out of scope of this issue.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1100.00
Contract address: [0xd67e9ab3487bb23e907986333fbf38b81be6cc01](https://etherscan.io/address/0xd67e9ab3487bb23e907986333fbf38b81be6cc01)
Network: Mainnet
Status: Pending user to save ETH address
Winner: ambilo
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
