### ISSUE TITLE
Use thread pool instead of new threads on Android

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#3690]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to leverage thread pools so that I don't incur the cost of creating a new thread every time.

### Description

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is some old code that is too simplistic and just creates a new `Thread` object every time, instead of pushing a new action into a `ThreadPool`.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When there is code that needs to run in a background thread, we'd post that to a thread pool instead of creating a new short-lived thread specifically for that.

#### Actual behavior
[comment]: # (Describe what actually happened.)
A new `Thread` object is created everytime (see e.g. [JSCJail.java](https://github.com/status-im/status-react/blob/develop/modules/react-native-status/android/src/main/java/im/status/ethereum/module/JSCJail.java#L105))

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Save a global reference to a [shared thread pool](https://developer.android.com/reference/java/util/concurrent/Executors.html#newCachedThreadPool())
- [ ] Replace situations where we're creating a new thread by usage of the saved thread pool

### Additional Information
[comment]: # (Please do your best to fill this out.)
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 550.00
Contract address: [0xada243d5513dfa17f2fa4ec7d1cb69f6809aa514](https://etherscan.io/address/0xada243d5513dfa17f2fa4ec7d1cb69f6809aa514)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
@PombeirP Hi, here's an implementation for this requirement: #3889 :beers:
