### ISSUE TITLE
"Network request failed" dialog appears every time a new screen is opened in offline mode

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3694]
### Description
*Type*: Bug

*Summary*: "Network request failed" dialog is useful to let user know that some request has timed out because of a network issue. But, the dialog has started appearing every time a new screen is opened or message sent which makes it really annoying.

#### Expected behavior
The dialog appears only when there was a network timeout while executing some request.

#### Actual behavior
The dialog appears when you switch tabs (like Chats -> Wallet), open a chat or open any other screen. Even when sending a message.

<img src="https://user-images.githubusercontent.com/7532782/37960419-e5f47eee-31b5-11e8-8f7b-df63f4b7d3ac.png" width="300">

### Reproduction
- Open Status
- Go offline (make sure to turn off wifi)
- Go to chats sreens
- Go to wallet screens

### Additional Information
* Status version: nightly, March 27
* Works in 0.9.15
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1100.00
Contract address: [0xae1cf7459bc48886deb786534c4814293dc96835](https://etherscan.io/address/0xae1cf7459bc48886deb786534c4814293dc96835)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
