### ISSUE TITLE
Decrease tapping area to make the version number not clickable

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3698]
### Description

*Type*: Bug

*Summary*: Decrease tapping area in the Profile tab so tapping version will not ask me to log out.

#### Expected behavior

![image](https://user-images.githubusercontent.com/28752642/37963335-a371cffc-31c6-11e8-8656-9e28f366263d.png)

I want to have the tapping area related to log out button and not for the version

#### Actual behavior
tapping version asks me if i really want to log out

### Reproduction

- Open Status
- Go to Profile
- Tap Version

### Additional Information
* Status version: nightly 27/03/2018
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 593.29
Contract address: [0x412be54fb414dcc28763bc3ad2d140bbc1ee109f](https://etherscan.io/address/0x412be54fb414dcc28763bc3ad2d140bbc1ee109f)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
