### ISSUE TITLE
Can't go to settings in android

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#3700]
### User Story

As an android user, 
I want to access the settings of the app 
so that I can change them easily.

### Description

*Type*: Bug

*Summary*: 
When clicking on Notifications from profile in the app on android, I am not redirected to the settings in android.

#### Expected behavior
I am redirected to the settings view in android
#### Actual behavior
Nothing happens
### Reproduction

- Open Status
- Click on profile
- Click on Notifications

### Additional Information

It only happens on android afaik.

`android/app/src/main/java/im/status/ethereum/MainActivity.java` contains some related code.

Tested on 2 devices:

Pixel running 7.1.0 , does not work
Nexus 6 running 7.0 works as expected

**Comment by jeluard** [comment]
Probably duplicates #3644

**Comment by asemiankevich** [comment]
duplicate
