### ISSUE TITLE
[87-new-protocol] No contacts on Group Info screen of the non-admin group chat member

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3701]
***Type***: Bug

***Summary***: Any of contacts (even admin) are not present on Group Info screen in the Group Chat member side (non-admin group chat member). Even those who are in my contact list. 
(Related issue exist already https://github.com/status-im/status-react/issues/3670) 

#### Expected behavior
All contacts who are members of the group chat are listed in the Group Info screen

#### Actual behavior
No contacts who are members of the group chat are listed in the Group Info screen

### Reproduction

- Open Status on Device A and Device B
- Create 'Contact A' and 'Contact B' respectively
- Contact A adds Contact B in contacts
- Contact A creates group chat with Contact B
- Contact B checks 'Group Info' screen of the group chat he was invited to

### Additional Information
* Status version: b33bd65f
* Operating System: Android and iOS

TF session for non-admin Group chat member: https://app.testfairy.com/projects/4803622-status/builds/7985879/sessions/16/?accessToken=9X4k7YZkLZvsSEEv/trq2kbYI3Q

**Comment by janherich** [comment]
@Serhy I believe this is already fixed in develop.

**Comment by Serhy** [comment]
Confirmed! Thanks, @janherich, the #3670 is still relevant though. 
Closing current issue.
