### ISSUE TITLE
Message from 'System' appears in group-chat after contact re-login

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3702]
***Type***: <Bug|Feature>

*Summary*: Contact has been added in group chat. When he re-logins to account group chat receives the message from 'system' like `1522162060304-1968bcd3-e7c4-5dfb-b176-42c79a5cfa5b invited 0x04fd04ef1873c822f8585abf1f0e8636ca765e821156b8c506ef13ce1790bfd44e554b6e5d5c8d132eaa66451638c4585feff253ab9d7d188c4d4504e83e88efc8 and removed {:identity "0x04fd04ef1873c822f8585abf1f0e8636ca765e821156b8c506ef13ce1790bfd44e554b6e5d5c8d132eaa66451638c4585feff253ab9d7d188c4d4504e83e88efc8", :is-in-chat true}` each time. The next message received then - displayed above 'system' message. The next messages listed after 'system' one. See TF session below what is going on.
**Note**: I noticed the number group chat members increments each time the contact re-logins. On screenshot below there are '9 members' while only 2 initial contacts has been invited.

#### Expected behavior
No message from 'System' in group-chat after contact re-login
#### Actual behavior
Message from 'System' appears in group-chat after contact re-login
<img width="297" alt="screen shot 2018-03-27 at 18 35 39" src="https://user-images.githubusercontent.com/8749671/37978030-b89323aa-31ed-11e8-83a0-d8d1a405ffa9.png">

### Reproduction

- Open Status on Device A and Device B
- Create 'Contact A' and 'Contact B' respectively
- Contact A adds Contact B in contacts
- Contact A creates group chat with Contact B
- Contact B re-logins to account 

**UPDATE**: In next builds (194th build for experiment/new-protocol-app) it was noticed that when 
- Contact B navigates to Group Chat with 'System' message
the next error followed by app crash appears:
![screenshot_20180403-195026](https://user-images.githubusercontent.com/8749671/38263555-0aaa7036-3779-11e8-9b44-f71683b145b1.png)

### Additional Information
**Status version:** b33bd65
**Operating System:** Android and iOS

TF session: https://app.testfairy.com/projects/4803622-status/builds/7985879/sessions/21/?accessToken=GJ7iA0e4oKkPm3WYe5hLRr8pnYA

**Comment by Serhy** [comment]
While testing fix for https://github.com/status-im/status-react/issues/3719 (194th build for experiment/new-protocol-app) it was noticed that now, navigating to the chat with 'System' message appeared after re-log - fires the error followed by app crash: `TypeError: null is not an object (evaluating 'e.lastIndexOf')`.

**Comment by yenda** [comment]
@Serhy thanks, we will address this separately as discussed on Slack, I will make a build for tomorrow with all the latest fixes and disabling group-chat, so the testing should be focused on verifying that everything else works fine. Then we will make a PR to fix all the private group-chat bugs

**Comment by janherich** [comment]
@Serhy To be honest, I didn't test the group chat since it will be disabled anyway, so I suggest to make separate Issue for that.

**Comment by Serhy** [comment]
Tested latest nightly develop (337th jenkins build) - it's not reproducible anymore! 
Awesome! Closing the issue!
