### ISSUE TITLE
Adding contact via scanning QR code redirects to Home instead 1-1 chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3703]
***Type***: Bug

***Summary***: When user scans QR code to add new contact - instead of 1-1 chat redirect happens on Home screen.
**Note**: it's all fine when adding new contact via paste-submit public key

#### Expected behavior
Redirect to 1-1 chat when adding new contact via QR code 
#### Actual behavior
Redirect to Home screen when adding new contact via QR code 

### Reproduction

- Open Status and log in to account
- Navigate to 'Start new chat' -> 'New chat' 
- Add new contact by via QR code

### Additional Information
Status version: b33bd65
Operating System: Android and iOS

TF session: https://app.testfairy.com/projects/4803622-status/builds/7985879/sessions/23/?accessToken=KapIzk3cWuathUQHZFcqHbq0-zc

**Comment by yenda** [comment]
Should be fixed in the latest build of new-protocol-app branch

**Comment by Serhy** [comment]
Confirmed as fixed. Closing this one.
