### ISSUE TITLE
Admin is not shown in send/receive suggestions on non-admin group-chat member side 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3705]
***Type***: Bug

**Summary**: There is a group chat created. Admin can see the list of contacts in /send or /receive suggestion screen. However, any other group chat member (even if everyone is in contacts of each other) can not see the group chat **admin**  in the list of contacts when viewing the list of recipients of the /send or /receive screens. 
Any group chat member should be able to see all group chat members in the 'Choose recipient' list of 'send' or 'receive' feature.

#### Expected behavior
Any group chat member can see the list of other chat members in the 'Choose recipient' list of 'send' or 'receive' feature in Group Chat

#### Actual behavior
Group chat admin is not shown in send/receive suggestions on non-admin group-chat member side 

### Reproduction

- Open Status on Device A and Device B and Device C
- Create 'Contact A' and 'Contact B' and 'Contact C' respectively
- Each contact adds another two in contacts
- Contact A creates group chat with 'Contact B' and 'Contact C'
- Contact B taps `/send` to select 'Contact A'
**Actual result:** 'Contact B' doesn't see 'Contact A (admin) on the list, but sees 'Contact C'
- Contact B taps `/receive` to select 'Contact A'
**Actual result:** 'Contact B' doesn't see 'Contact A' (admin) on the list, but sees 'Contact C'

### Additional Information
Status version: b33bd65
Operating System: Android and iOS

TF on non-admin GC side: https://app.testfairy.com/projects/4803622-status/builds/7985879/sessions/27/?accessToken=qVTq4BZRTGx1cVwAYHSVoFfwBhw

**Comment by Serhy** [comment]
This issue and #3701 - are related to each other - the root of both is that non-group chat member fails to receive (or maybe just to display) group chat members.

**Comment by lukaszfryc** [comment]
Contacts also do not appear in the group chat profile screen. Members section is empty. See more in #3854
