### ISSUE TITLE
Collect mixpanel events while offline

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#3706]
### Description

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
When app goes offline, we cannot track mixpanel events because we do it in realtime by calling `mixpanel/track` which does http API call. As a result, we simply drop/ignore the events when app is offline.

### Solution

Possible solution would be collecting events during offline and sending them later when app goes back online.

Use mixpanel batch API to send events https://mixpanel.com/help/reference/http

### Notes

Related issue https://github.com/status-im/status-react/issues/3694

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2373.15
Contract address: [0x69764a52f4dec97bf80b06238bf462ce5e8d4703](https://etherscan.io/address/0x69764a52f4dec97bf80b06238bf462ce5e8d4703)
Network: Mainnet
Paid to: msuess
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
