### ISSUE TITLE
Restoring account event is treated as account created by Mixpanel

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3716]
### Description

*Type*: Bug

*Summary*: Restoring account is treated as account created by Mixpanel

https://mixpanel.com/report/1541909/live/#chosen_columns:!('$browser','$city',mp_country_code,distinct_id,'$referring_domain'),column_widths:!(200,100,223,153,96,366,182),query:(distinct_ids:!(),is_or_query:!f,on:'(%2225b7e2df%22%20in%20properties%5B%22app-version%22%5D)%20and%20(defined%20(properties%5B%22app-version%22%5D))',property_selectors:!((defaults:(filter_state:(),human_readable_params:!(),query:''),distinct_id_operator:and,distinct_ids:!(),human_readable_params:!((type:property,val:app-version),(type:operator,val:contains),(type:operand,val:'25b7e2df')),query:'(%2225b7e2df%22%20in%20properties%5B%22app-version%22%5D)%20and%20(defined%20(properties%5B%22app-version%22%5D))',valid_segfilter:(filters:!((filter:(operand:'25b7e2df',operator:in),property:app-version,selected_property_type:string,type:string)),op:and)))),resized_columns:!(!f,!f,!f,!f,!t,!t,!t)

#### Expected behavior

we should use {:label "Account restored"
:trigger [:account-recovered]} i guess for Recover account event in Mixpanel https://github.com/status-im/status-react/blob/83b5312a05e1d5bd4e1ed8716a013828b3d765c1/src/status_im/utils/mixpanel_events.edn

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/38030964-c4bc6d52-32a2-11e8-896a-dced5c755c0a.png)

### Reproduction

- Open Status
- Recover account and agree to share user data
- go to Mixpanel and check the events for current session / build

### Additional Information

* Operating System: Android, iOS

**Comment by chadyj** [comment]
Nice catch!
