### ISSUE TITLE
Console and Wallet dapps in new group chat screen

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#373]
<img src=https://cloud.githubusercontent.com/assets/2364994/19510030/1b3112b6-95ea-11e6-8d48-2eb930a315f1.png width=320 />

**Comment by jarradh** [comment]
technically this is fine? dapps will be allowed in group chat, it's what command permissions are for

**Comment by rasom** [comment]
oh, ok, if it is fine then i will close issue
