### ISSUE TITLE
Unknown contact indicator (blue circle) maybe hard to understand

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3734]
### Description
_Type_: Bug

_Summary_: 

Update new contact indicator to:

![](https://user-images.githubusercontent.com/4932774/42817671-145cbf32-89cf-11e8-95ba-8c8eb92d8f36.png)

Behaviour:

1) The indicator ("NEW") should only appear on the chat list in Home tab
2) The indicator should disappear once the chat is opened
3) Remove old indicator (blue dot) from chat screen

![](https://user-images.githubusercontent.com/7532782/42821804-ae2fa76e-89d9-11e8-9035-47e650fc9694.png)

### Reproduction

* Open Status
* Receive a message from unknown contact 

### Additional Information

* Status version: latest nightly
* Operating System: Android, iOS, all desktop

**Comment by lukaszfryc** [comment]
@denis-sharypin @andmironov what do you think?

**Comment by denis-sharypin** [comment]
@lukaszfryc  Hi,
I'will try to fix this on the scope of #096-tribute-to-talk swarm

**Comment by errorists** [comment]
<img width="833" alt="screen shot 2018-07-17 at 14 37 31" src="https://user-images.githubusercontent.com/4932774/42817671-145cbf32-89cf-11e8-95ba-8c8eb92d8f36.png">
Here's an idea, we could use a more descriptive label, it's similar to what Messenger does. cc @andmironov

**Comment by lukaszfryc** [comment]
@errorists I love it! Looks much more clear and encouraging :) 

If we would have it, how do you plan to change this screen? Can we remove that blue dot and leave only "Add to contacts" button? 

<img src="https://user-images.githubusercontent.com/7532782/42821804-ae2fa76e-89d9-11e8-9035-47e650fc9694.png" width="200">

**Comment by errorists** [comment]
@lukaszfryc yeah totally, I believe the 'Add to contacts' button implies sufficiently that the person is not a contact yet, and having the label next to the username would be redundant.

**Comment by errorists** [comment]
Complete design: [Zeplin](zpl.io/V1eE37B)

**Comment by lukaszfryc** [comment]
@errorists it looks great. Btw, should "NEW" disappear once you open the chat but do not add the contact? I imagine that someone may not want to add another person as a contact immediately. He may first have a conversation and only after that add the contact to reveal his real name and avatar.

**Comment by errorists** [comment]
@lukaszfryc Good point, no it should not disappear until you add him as contact and reveal identity.

**Comment by lukaszfryc** [comment]
@errorists I'd think that it will disappear once I open it to check it. Please note that I will know his real name and avatar because the user sent me the contact request. I may not want to add him to my contact list but I don't want to see this "NEW" label that should encourage me to click it.

**Comment by errorists** [comment]
@lukaszfryc Yeah went through the flow in the app, it makes sense 👍 To recap, it should disappear once you view the chat with that contact. Also, on a side note, in our [designs](https://zpl.io/V1eE37B) the 'Add to contacts' snackbar has a dismiss button that's missing from the build, maybe you're aware if we have an issue for that?

**Comment by lukaszfryc** [comment]
@errorists cool. Yes, there's should be dismiss button. Good catch! I created https://github.com/status-im/status-react/issues/5440

**Comment by lukaszfryc** [comment]
Reopening it as the issue is still there and desings are ready.

**Comment by mandrigin** [comment]
@StatusSceptre @yenda should we make it a bounty?

**Comment by flexsurfer** [comment]
@errorists is this still relevant?

**Comment by errorists** [comment]
@flexsurfer I'd ask to close this one, it's not 100% accurate anymore. Once we start working on chat again, I'll create a proper issue.
