### ISSUE TITLE
Send user events to Instabug so that surveys can be triggered

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3738]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a UXR, I want to create Instabug surveys after specific app events so that I can survey users with relevant context.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

UXR is tasked with creating surveys to measure user feedback and OKR results such as ">95% of 20+ people surveyed trust Status for messaging".  In order to ensure the survey responses are relevant they need to be shows to users at the right time. For example, showing a messaging reliability survey to users when they first open the app won't yield meaningful answers, but showing the same survey to users after they send a message will ensure the users have the proper messaging context.

Instabug has a feature that can show surveys to users based on events and conditions, but in order for it to work events need to be sent to Instabug. Currently no events are sent.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

UXR creates a survey and sets a conditions to show the survey after a specific event.
When the app users completes the event, the survey is shown.

#### Actual behavior
[comment]: # (Describe what actually happened.)

UXR creates a survey, but can't set conditions because no events are being sent. 
Without conditions the survey is shown to all users at the same time.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Status now sends (opt-in) user events to Mixpanel (see here https://github.com/status-im/status-react/pull/3605). The same events (see https://github.com/status-im/status-react/blob/develop/src/status_im/utils/mixpanel_events.edn for a list of events) can be sent to Instabug using the logging feature described here https://docs.instabug.com/docs/react-native-logging#section-user-steps.

Like Mixpanel, we should only send these events for users that opt-in.

cc @hesterbruikman @jpbowen 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://docs.instabug.com/docs/react-native-logging#section-user-steps">Logging</a></strong></div><div>You can send a variety of logs types with each crash or bug report. They will appear withing each report on your Instabug dashboard as shown below.   ## Instabug Log  You can log messages throughout your application's lifecycle. Those logs are going to be sent with each report.  ## User Steps  Insta...</div></blockquote>

**Comment by dmitryn** [comment]
I'd suggest to also collect events during offline app usage.

Check if Instabug library handles this. If not, it could be implemented like here:

https://github.com/status-im/status-react/pull/3733

**Comment by dmitryn** [comment]
I've sent several events using `(.logUserEventWithName instabug "send-current-message")` but i don't see i can use this event as a condition/trigger for survey. Please make sure we could use this feature before starting to work on current issue.

**Comment by chadyj** [comment]
@dmitryn Events are now showing up in surveys and on user profiles. Looks like there can be a delay in events being sent or received. But they are there now!

<img width="518" alt="screen shot 2018-03-30 at 7 33 46 pm" src="https://user-images.githubusercontent.com/116099/38147178-651253b6-3451-11e8-8ff8-024dd78dc51e.png">

<img width="506" alt="screen shot 2018-03-30 at 7 35 19 pm" src="https://user-images.githubusercontent.com/116099/38147216-838bb346-3451-11e8-93f6-04340eb0fdb6.png">

**Comment by chadyj** [comment]
Looks like you'll need to do something like `Instabug.logUserEventWithNameAndParams("tap",{"key": "send-current-message"});` so in the Instabug UI we could do 

"tap" equals "send-current-message"

I've asked Instabug about instead doing "if exists" or "count > 5" or something for more flexibility.

**Comment by chadyj** [comment]
> I've asked Instabug about instead doing "if exists" or "count > 5" or something for more flexibility.

This feature exists :-)

<img width="503" alt="screen shot 2018-04-03 at 12 50 13 pm" src="https://user-images.githubusercontent.com/116099/38245220-9422a1bc-373d-11e8-936a-c152af630135.png">

For this condition a survey would be shown to a user that sent 5 messages.

**Comment by hesterbruikman** [comment]
Couldn't get the same view of custom conditions to select:( Any advice @dmitryn ?

**Comment by dmitryn** [comment]
- [ ] Merge this to https://github.com/status-im/status-react/tree/release/0.9.17

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by chadyj** [comment]
@dmitryn Any updates from Instsabug?
I can post on their RN repo to help get their attention.

**Comment by dmitryn** [comment]
>Any updates from Instsabug?

@chadyj we're still in a debug process. I've just sent new batch of test events to allow them verify if they receive it. 

If you could ping them somewhere else to speed that up, it would be helpful.

**Comment by dmitryn** [comment]
I was able to create Instabug User Events (https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/31 look for `"Tap" {"target": "home"}` event). But cannot select custom params in survey conditions (for example, show survey after 5 Taps on Home. It can only be like, show it after any 5 Taps). Figuring out with their support if that technically possible to do. Otherwise, we would be sending events without custom parameters, e.g. "tap-home", "send-current-message", etc.

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/31">Login | Instabug</a></strong></div></blockquote>
