### ISSUE TITLE
Messages connection problem tooltip is shown when messages are received

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3745]
### User Story

As a user, I want to understand when messages can't be received so that I see 'Messages connection problem' tooltip is shown.

### Description

*Type*: Bug

*Summary*: Sometimes when 'Messages connection problem' tooltip is shown user is still able to receive new messages and see new chats added

#### Expected behavior
'Message connection problem' tooltip is not shown when it's possible to receive messages

#### Actual behavior
New chats appear on Home screen and messages are received when 'Message connection problem' tooltip is shown
![image](https://user-images.githubusercontent.com/29711298/38206983-ff2bf1b8-36b4-11e8-9275-6add31c5c483.png)

### Reproduction
- Open Status on 2 devices
- Start chatting

### Additional Information
* Status version: 0.9.10-827-g-38c9bb72+ (Apr 2 nightly build)
* Operating System: Android emulator 6.0

Video:
new chat appearing: https://drive.google.com/open?id=1XPc1D8o_KPedAsR58lmmaqXk5hGQ36kP
new message appearing: https://drive.google.com/open?id=1ruMk1AyzWN23U0OQsgVFvNfh13Ye6Yvq

<blockquote><img src="https://lh5.googleusercontent.com/GJ9Y2VPHZq9385eyIFPmorqlT1FZL4pCD5ITCMGRHOr4on1KnKwPXXcT4tE=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1XPc1D8o_KPedAsR58lmmaqXk5hGQ36kP/view?usp=drive_web&usp=embed_facebook">new_chat_appears.mov</a></strong></div></blockquote>
<blockquote><img src="https://lh6.googleusercontent.com/P-byk5iXztGEvu_QMRnEvY-UMHn3RZxA6NjwQPGFK0TKJY-na1XDSLUg6ak=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1ruMk1AyzWN23U0OQsgVFvNfh13Ye6Yvq/view?usp=drive_web&usp=embed_facebook">new_message_appears.mov</a></strong></div></blockquote>

**Comment by antdanchenko** [comment]
I would really like to get the issue fixed.
Since half of transactions via request and chat tests are suffering from the error (it's not possible to interact with elements if any error is present, in order not to miss an error)

**Comment by lukaszfryc** [comment]
Is it still appearing when it should not? I haven't seen it for a long time.

**Comment by yevh-berdnyk** [comment]
The same for me, so closing the issue.
@lukaszfryc thanks!
