### ISSUE TITLE
Adjust settings screens to match the mocks (ios)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3749]
### Description

*Type*: Bug

*Summary*: There are a lot of screens that are missing the top line (delimiter) on iOS. 

#### Expected behavior

1. Network settings screen has top delimiter (line) under the header as shown on the mocks
![image](https://user-images.githubusercontent.com/28752642/38236657-8b7d0382-372d-11e8-8093-054178f57cef.png)

2. Offline messages settings screen has delimiter (line) under the header and all the list items are separated with line too , as shown on mocks
![image](https://user-images.githubusercontent.com/28752642/38236721-c0ac736c-372d-11e8-9ad4-2bb055d09789.png)

3. New chat screen
![image](https://user-images.githubusercontent.com/28752642/38560276-f12ed0c4-3cdd-11e8-9bd0-b86c4b520db0.png)

4. Join public chat screen
![image](https://user-images.githubusercontent.com/28752642/38560331-14b327ca-3cde-11e8-8e37-d4cf9fc44525.png)

5. Group chat screen
![image](https://user-images.githubusercontent.com/28752642/38560897-5e8d78c2-3cdf-11e8-80d8-55eee3223ce8.png)

#### Actual behavior

Some screens are missing this top line, for ex: 
1. No line under header on the **Network settings** screen
![image](https://user-images.githubusercontent.com/28752642/38236789-ee3af5f6-372d-11e8-9e08-66c4943e00fb.png)

2. No delimiters on **Offline messages settings** screen
![image](https://user-images.githubusercontent.com/28752642/38236855-1b8422bc-372e-11e8-9895-ba16822899d1.png)

### Reproduction

- Open Status
- Go to Profile
- Tap Advanced -> Network
- Tap Back -> Advanced -> Offline messages
- From Home tab -> + -> new chat
- From Home tab -> + -> join public chat
- From Home tab -> + -> create group chat

### Additional Information
* Status version: nightly 03/04/2018
* Operating System: iOS

**Comment by denis-sharypin** [comment]
We need to implement a line for header on iOS like everywhere not only on the setting screen. For instance, chat doesn't have it right now. Maybe it's to create a separate a bit bigger issue for that?

**Comment by asemiankevich** [comment]
I removed the label for bounty as I need to list all the screens where the top line is missing on iOS.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x6d7432986dc283f7920beceadc24c553eed31109ba708627e80e6a9276b556e8](https://etherscan.io/tx/0x6d7432986dc283f7920beceadc24c553eed31109ba708627e80e6a9276b556e8)

**Comment by asemiankevich** [comment]
@pablanopete please revoke the bounty here and close the issue. Thanks!
