### ISSUE TITLE
Wallet: lots of UI bugs (iOS)

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#375]
Most probably some of the bugs below have already been added to the list of wallet bugs (https://github.com/status-im/wallet/issues).

- [x] You can copy everything from the WebView;
- [x] You can zoom in and out;
- [x] Vertical scrolling is also possible;
- [x] "Wallets" title is not centered correctly;
- [x] There is no visual feedback;
- [ ] There is a strange black line on the bottom on iOS;

![rec](https://cloud.githubusercontent.com/assets/911127/19517160/30f297a0-9608-11e6-8ef8-d95d698d0392.gif)

**Comment by alwx** [comment]
Bottom line looks like a React Native bug. Everything else was fixed.

https://github.com/status-im/wallet/pull/20

**Comment by rasom** [comment]
I'm not sure that this is a big problem, but zoom still works on iOS:

![zoom](https://cloud.githubusercontent.com/assets/2364994/19557677/8ac5118c-96cf-11e6-8ccc-e45fb62e0e56.gif)

**Comment by jarradh** [comment]
lets not worry about the zoom for alpha - after all it is supposed to be a webview

**Comment by rasom** [comment]
And it is the webview :)
