### ISSUE TITLE
chat-id = "{:updated at nil.... error when leaving the group chat having formatted text messages

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3751]
***Type***: Bug

***Summary***: `chat-id = "{:updated at nil....` error when leaving the group chat having formatted text messages

#### Expected behavior
No error error when leaving the group chat having formatted text messages
#### Actual behavior
![image](https://user-images.githubusercontent.com/8749671/38252416-bfbc34d6-375c-11e8-8fea-77cf0474acc5.png)

### Reproduction

- Open Status on Device 1 and Device 2
- Create accounts Contact 1 and Contact 2 respectively
- Contact 1 adds Contact 2 in contacts
- Contact 1 creates GroupChat with Contact 2
- Contact 1 sends two messages: in bold and italic fonts (e.g. `*Bold*` and `~Italic~`)
- Contact 2 navigates to GroupChat 
- Contact 2 taps and submits 'Leave group chat' 

### Additional Information
* Status version: Develop (324th nightly), 0.9.16
* Operating System: Android and iOS

#### Logs

TF session with error 01:00 - 01:30:https://app.testfairy.com/projects/4803622-status/builds/8030567/sessions/19/?accessToken=MGrepawqbwz26SUBUmSOWo1yi/Q

**Comment by annadanchenko** [comment]
@Serhy can't reproduce for public chat in nightly jun 17 build, can you re-check, please? If it's not in pub chat anymore - let's add label for `group chat` and remove public chat from description/title

**Comment by Serhy** [comment]
Me neither!
Updated the description keeping `group chat` only.
