### ISSUE TITLE
Can't message in Rinkeby

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3752]
### Description

*Type*: Bug

*Summary*: It appears that i can't see messages under Rinkeby / Rinkeby with RPC network. After i switch back to Ropsten - I can see all the messages coming

#### Expected behavior
I can exchange messages under Rinkeby network

#### Actual behavior
Messages are not delivered

### Reproduction

- Open Status
- Having 2 accounts under Rinkeby try to exchange messages

### Additional Information
* Status version: nightly 03/04/2018
* Operating System: Android, iOS

**Comment by adambabik** [comment]
I will investigate first the state of our Rinkeby cluster.

**Comment by adambabik** [comment]
One node was down, I fixed it. There should be three Rinkeby nodes available now. However, there are no mailservers for Rinkeby so only online messaging works.

**Comment by Serhy** [comment]
This is not reproduced anymore. 
Having 2 accounts under Rinkeby network - exchange messages fine. Offline inboxing between two also works fine. 

Issue now only that Rinkeby user can't receive any message from Mainnet or Ropsten (while Mainnet <-> Ropsten message exchange works fine).
Issue for message exchange between Rinkeby <-> Mainnet/Ropsten created in #5188 separately. 

Closing this one.
