### ISSUE TITLE
TypeError: null is not an object (evaluating `e.lastindex0f`) in public and group chats after receiving a message which starts with `/`

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3757]
### Description
*Type*: Bug
The error `TypeError: null is not an object (evaluating 'e.lastindex0f')` is shown when a user receives a message which starts with `/` in opened public or group chat

#### Expected behavior
Message which starts with `/` is received and displayed for a user in  in opened public or group chat, no error is shown.

#### Actual behavior
`TypeError: null is not an object (evaluating 'e.lastindex0f')` error is shown right after receiving a message which starts with `/` in opened public or group chat
![0016screenshot](https://user-images.githubusercontent.com/12611990/38308314-60662b04-381f-11e8-94a1-240114323911.png)

### Reproduction
Create two new users
As `user a` create new public (e.g. #asdasd1weew) or group chat
As `user b` join the chat and stay on the chat screen
As `user a` send `/text` into the chat

### Additional Information
* Status version: <img width="240" alt="screen shot 2018-04-04 at 3 46 14 pm" src="https://user-images.githubusercontent.com/12611990/38308300-555afcd0-381f-11e8-90c5-f3415b970492.png">

* Operating System: Android and iOS

**Comment by flexsurfer** [comment]
@antdanchenko the reason not in "/" it's because empty image-path of one of participants
