### ISSUE TITLE
App DB contains clear text password under :accounts/create

### ISSUE THREAD

**Issue by msuess** [status-im/status-react#3761]
### User Story

As a user, I want my password to be protected so that no one can steal it.

As a developer, I want sensitive data to be removed from app-db as soon as possible so that I can't accidentally leak it.

### Description

*Type*: Bug

*Summary*: After account creation, data under the `:accounts/create` key stays there, containing `:password` and `:password-confirm`.

#### Expected behavior
Sensitive data gets removed from DB when it is no longer needed.

#### Actual behavior
Sensitive data stays in DB.

### Reproduction

- install handler or interceptor that logs `(:accounts/create db)`
- Open Status
- trigger handler
- observe `adb logcat`

### Solution
*Summary*: Remove the passwords after completing account creation.

### Additional Information
* Status version: latest code on `develop` branch
* Operating System: Android and iOS

#### Logs

This log was produced using a custom interceptor.

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
04-04 20:13:09.225  5915  5999 I ReactNativeJS: INFO [status-im.utils.handlers:96] - Track interceptor {:step :enter-name, :password "thepassword", :password-confirm "thepassword", :error nil, :name "mtest", :show-welcome? true}
```

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1500.00
Contract address: [0x322cd97010a717fbb114cf214bd04588d8a1feb3](https://etherscan.io/address/0x322cd97010a717fbb114cf214bd04588d8a1feb3)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by oskarth** [comment]
@andytudhope Can we bump this up to a medium?
