### ISSUE TITLE
Hide three dots menu and swipe-to-delete for Console chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3765]
### Description

*Type*: Bug

*Summary*: after Console redesign, we still have three dots options to remove console chat and view profile, it seems to be outdated to me as removing/displaying Console chat is now controlled with Dev mode toggle in profile. And viewing Console profile does not have any use cases.

#### Expected behavior
three dots menu is not shown when viewing console chat so the user does not have access to its' options

#### Actual behavior

1. Three dots menu is present, so I can tap it, however, none of the user actions are present from a user perspective
2. Swipe-to-delete gesture is present but is should not be 

![image](https://user-images.githubusercontent.com/28752642/38354351-fc0d114c-38c1-11e8-9159-84a7109fa7d7.png)

![image](https://user-images.githubusercontent.com/28752642/38358023-db49954c-38cc-11e8-8519-c9c78a536add.png)

### Reproduction
- Open Status
- Create account
- Tap profile
- Tap Development mode toggle
- Tap Home
- Tap Status Console chat
- Pay attention to the top right corner

### Additional Information

* Status version: nightly 05/04/2018
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Contract address: [0x28ad489de2f21554be79b540f3f5684a1342be07](https://etherscan.io/address/0x28ad489de2f21554be79b540f3f5684a1342be07)
Network: Mainnet
Paid to: kwingram25
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
