### ISSUE TITLE
'Help to improve Status' popup is not disappearing after tapping on 'Share'/'Don't share' buttons after recovering of a user

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#3770]
### Description

*Type*: Bug
'Help to improve Status' popup doesn't disappear after tapping on `No, I don't want to share` or `Share usage` after recovering a user
Please note, home screen is displayed for several seconds and only after the popup appears. In previous version home screen wasn't displayed before the popup.

#### Expected behavior
Popup disappears after tapping on `No, I don't want to share` or `Share usage` buttons. Usages is shared or not shared according to the selection.

#### Actual behavior
'Help to improve Status' popup is present after tapping on `No, I don't want to share` or `Share usage` buttons after user recovering

### Reproduction
- open Status
- Click on 'I already have an account', if the app is fresh installed, or 'Add existing account' if it's not.
- Recover user by entering passphrase and password and tapping on 'Sign in'

### Additional Information
* Status version: <img width="187" alt="screen shot 2018-04-05 at 1 44 23 pm" src="https://user-images.githubusercontent.com/12611990/38361850-76ebb53e-38d7-11e8-8224-f4fb7488532d.png">

* Operating System: Android & iOS

**Comment by asemiankevich** [comment]
@flexsurfer is this condition also fixed? https://github.com/status-im/status-react/issues/3773

**Comment by flexsurfer** [comment]
@asemiankevich yes here https://github.com/status-im/status-react/issues/3757
