### ISSUE TITLE
Error: null is not an object (evaluating 'e.lastIndexOf')

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3773]
### Description

*Type*: Bug

*Summary*: 

#### Expected behavior
no error

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/38363612-ff05c1e8-38dd-11e8-9a0a-4e677c8f45f1.png)

`NAME: "TypeError"
MESSAGE: TypeError: null is not an object (evaluating 'e.lastIndexOf')

This error is located at:
    in member-photo
    in reagent112
    in RCTView
    in RCTView
    in TouchableHighlight
    in reagent14
    in RCTView
    in RCTView
    in RCTView
    in reagent104
    in message-content
    in RCTView
    in RCTView
    in TouchableHighlight
    in reagent14
    in RCTView
    in RCTView
    in n
    in message-container
    in reagent103
    in chat-message
    in reagent102
    in message-row
    in RCTView
    in t
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in t
    in t
    in reagent22
    in messages-view
    in reagent100
    in RCTView
    in n
    in with-activity-indicator
    in reagent17
    in messages-view-animation
    in reagent81
    in RCTView
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in chat
    in reagent79
    in RCTView
    in main
    in root
    in reagent1
    in RCTView
    in RCTView
    in t
`

### Reproduction

- Open Status on 2 devices
- On device 1 create second account
- On device 2 join any public chat and send message
- On device 1 join the same public chat and send message
- Pay attention to the device 2 screen

### Additional Information
* Status version: nightly 05/04/2018
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803590-status/builds/8023502/sessions/83/?accessToken=qPv/2UKzZTf4QuNKY7l4Z6F4L7Q

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8023502/sessions/83/?accessToken=qPv/2UKzZTf4QuNKY7l4Z6F4L7Q">TestFairy: Status 0.9.16 (2283) @83</a></strong></div></blockquote>

**Comment by antdanchenko** [comment]
@asemiankevich The issue sounds like https://github.com/status-im/status-react/issues/3757

**Comment by flexsurfer** [comment]
@asemiankevich @antdanchenko yes this is the same issue and it's fixed here #3757
