### ISSUE TITLE
iOS random crash

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3774]
### Description

*Type*: Bug

*Summary*: random crash for ios in new protocol branch
#### Expected behavior
no errors

#### Actual behavior
0   JavaScriptCore                      0x189f70a2c bmalloc::Heap::allocateLarge(std::__1::lock_guard&, unsigned long, unsigned long) (in JavaScriptCore) + 24
1   JavaScriptCore                      0x189f6e2a0 bmalloc::Allocator::allocateLarge(unsigned long) (in JavaScriptCore) + 92
2   JavaScriptCore                      0x1895c8cd4 WTF::fastMalloc(unsigned long) (in JavaScriptCore) + 112
3   JavaScriptCore                      0x189e818c0 JSC::stringProtoFuncReplaceUsingRegExp(JSC::ExecState*) (in JavaScriptCore) + 6568
4   JavaScriptCore                      0x189d4ceb4 llint_entry (in JavaScriptCore) + 29668
5   JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
6   JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
7   JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
8   JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
9   JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
10  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
11  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
12  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
13  JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
14  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
15  JavaScriptCore                      0x189d45900 vmEntryToJavaScript (in JavaScriptCore) + 272
16  JavaScriptCore                      0x189c24170 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) (in JavaScriptCore) + 184
17  JavaScriptCore                      0x189609294 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) (in JavaScriptCore) + 400
18  JavaScriptCore                      0x189ca8a94 JSC::JSObject::ordinaryToPrimitive(JSC::ExecState*, JSC::PreferredPrimitiveType) const (in JavaScriptCore) + 1256
19  JavaScriptCore                      0x189ca8d4c JSC::JSObject::toPrimitive(JSC::ExecState*, JSC::PreferredPrimitiveType) const (in JavaScriptCore) + 540
20  JavaScriptCore                      0x189ca8db0 JSC::JSObject::getPrimitiveNumber(JSC::ExecState*, double&, JSC::JSValue&) const (in JavaScriptCore) + 48
21  JavaScriptCore                      0x18960229c llint_slow_path_jngreater (in JavaScriptCore) + 700
22  JavaScriptCore                      0x189d4bcf8 llint_entry (in JavaScriptCore) + 25128
23  JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
24  JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
25  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
26  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
27  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
28  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
29  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
30  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
31  JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
32  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
33  JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
34  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
35  JavaScriptCore                      0x189d4c8bc llint_entry (in JavaScriptCore) + 28140
36  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
37  JavaScriptCore                      0x189d4c454 llint_entry (in JavaScriptCore) + 27012
38  JavaScriptCore                      0x189d4c3f0 llint_entry (in JavaScriptCore) + 26912
39  JavaScriptCore                      0x189d45900 vmEntryToJavaScript (in JavaScriptCore) + 272
40  JavaScriptCore                      0x189c24170 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) (in JavaScriptCore) + 184
41  JavaScriptCore                      0x189609294 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) (in JavaScriptCore) + 400
42  JavaScriptCore                      0x189c5ca9c JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) (in JavaScriptCore) + 476
43  JavaScriptCore                      0x189d45a48 vmEntryToNative (in JavaScriptCore) + 280
44  JavaScriptCore                      0x1896092dc JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) (in JavaScriptCore) + 472
45  JavaScriptCore                      0x18986d2e4 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) (in JavaScriptCore) + 168
46  JavaScriptCore                      0x189609044 JSObjectCallAsFunction (in JavaScriptCore) + 392
47  StatusIm                            0x102aca844 0x1029e4000 + 944196
48  StatusIm                            0x102af30dc 0x1029e4000 + 1110236
49  StatusIm                            0x102af9d6c 0x1029e4000 + 1138028
50  StatusIm                            0x102a65208 0x1029e4000 + 528904
51  StatusIm                            0x102a5b980 0x1029e4000 + 489856
52  CoreFoundation                      0x182bab590 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ (in CoreFoundation) + 20
53  CoreFoundation                      0x182baae60 __CFRunLoopDoBlocks (in CoreFoundation) + 288
54  CoreFoundation                      0x182ba8b4c __CFRunLoopRun (in CoreFoundation) + 1032
55  CoreFoundation                      0x182ac8c58 CFRunLoopRunSpecific (in CoreFoundation) + 436
56  StatusIm                            0x102a3d448 0x1029e4000 + 365640
57  Foundation                          0x1835ff0f4 __NSThread__start__ (in Foundation) + 996
58  libsystem_pthread.dylib             0x18282c2b4 _pthread_body (in libsystem_pthread.dylib) + 308
59  libsystem_pthread.dylib             0x18282c180 _pthread_body (in libsystem_pthread.dylib) + 0
60  libsystem_pthread.dylib             0x18282ab74 thread_start (in libsystem_pthread.dylib) + 4

### Reproduction

- Open Status
- Wait for some time

### Additional Information
* Status version: iOS: https://i.diawi.com/7C6zwL
* Operating System: iOS
* https://app.testfairy.com/projects/4803590-status/builds/8047552/sessions/33/?accessToken=c58rqi62ALYw3Xfty0XlzfxaP7k

<blockquote><div><strong><a href="https://i.diawi.com/7C6zwL">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8047552/sessions/33/?accessToken=c58rqi62ALYw3Xfty0XlzfxaP7k">TestFairy: Status 0.0.2407 @33</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
I could not reproduce it while testing release/0.9.17 branch
