### ISSUE TITLE
Protocol versionning

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3783]
With the new protocol we can now easely introduce versionning in message-types by changing the tag of a message type that needs to be upgraded. 

For that to be usefull we need to display a comprehensive warning to the user when a message-type that the application cannot read has been received, which would mean they are using an older version of the app and that they should update.

**Comment by chadyj** [comment]
Along these lines is it worth considering introducing some app-level system instructing users to upgrade? I've seen Instabug reports about issues from really old versions that have been fixed by a new update, but the user didn't know.

**Comment by yenda** [comment]
@chadyj It can hardly be done without any kind of centralization, if it seems really necessary in the future, we can have all new account subscribe by default to an update topic, on which we would then post warning for new updates
