### ISSUE TITLE
Provide users with delivery status feedback when sending messages

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3784]
### User Story

As a user, I want to see feedback when sending messages so that I can be certain the message was sent.

As a user, I want to know if messages failed to send so that I can take action.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

Users should have confidence in their messaging, and one aspect is getting feedback on message states. Behind the scenes, there are multiple steps from when the user taps send until the message leaves the device, however, this is not reflected in the current UI and can give users the impression that a message was sent when it actually didn't. 

For example, open Status in offline mode and send some messages. The UI states the message was sent.

To fix this, Status will accurately show message states: "sending", "sent", and "failed".

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Successful message: The user hits send, a label says `sending`, and when successfully delivered the label changes to `sent`.

Failed message: The user hits send, a label says `sending`, and after an error or timeout the label changes to `failed`. The message can be resent or deleted.

#### Actual behavior
[comment]: # (Describe what actually happened.)

Status briefly shows a label `sending`, then `sent` as the message is sent to the local node. These are regardless of delivery success or failure.

### Solution

Requires https://github.com/status-im/status-go/issues/810

- [ ] update the UX to reflect the different states and flow.
- [ ] add action to delete/resend failed messages

Designs:

![sending_messages_android](https://user-images.githubusercontent.com/33906272/38554684-310043c0-3ccc-11e8-907c-789c9150ffb5.png)
![sending_messages_ios](https://user-images.githubusercontent.com/33906272/38554685-311e90fa-3ccc-11e8-9f64-08a4f4c44288.png)

**Comment by nikitalukianov** [comment]
feedback when sending messages, all states:
![errors_states](https://user-images.githubusercontent.com/33906272/38428361-41d865ac-39c4-11e8-8d81-e89b507498be.png)

**Comment by nikitalukianov** [comment]
![sending_messages](https://user-images.githubusercontent.com/33906272/38551829-dfc9991a-3cc2-11e8-88a8-ee599bf29244.png)

**Comment by nikitalukianov** [comment]
![sending_messages_android](https://user-images.githubusercontent.com/33906272/38554684-310043c0-3ccc-11e8-907c-789c9150ffb5.png)
![sending_messages_ios](https://user-images.githubusercontent.com/33906272/38554685-311e90fa-3ccc-11e8-9f64-08a4f4c44288.png)

**Comment by nikitalukianov** [comment]
There are new updates for Android & iOS states. It's a new design of chat, cause i optimised space into messages, removed avatars from "yours" messages. The different btw Android & iOS screens — is space to states below the message (4px — Android, 3px — iOS). It's because the different font space etc.

**Comment by lukaszfryc** [comment]
> when successfully delivered the label changes to sent

How do we know that a message was delivered? I'd like to test that.

> and after an error or timeout the label changes to failed

So the timeout is 30s. After it, the spinner which indicates `sending` status, changes to the error message. 
What logic will trigger the error? One example I think of is that message didn't leave the device for some reason. Another one may be that a node did not accept it for some reason. Do I understand this correctly?

**Comment by chadyj** [comment]
> What logic will trigger the error? One example I think of is that message didn't leave the device for some reason. Another one may be that a node did not accept it for some reason. Do I understand this correctly?

Yep that sounds right. That is two failure modes. @rasom can you think of others?

**Comment by lukaszfryc** [comment]
@nikitalukianov what should happen when a device is offline and I sent a message? FB Messanger shows a circle indicator that the message has not been sent yet. In our case, should we keep the spinner going on until the network is back? 

I'd not show the red error "Not sent.." in this case.

**Comment by nikitalukianov** [comment]
@lukaszfryc when a device is offline and I sent a message, we immediately show "Not sent. Tap for options" and then we show the spinner and if we still offline, we show "Not sent. Tap for options" again

**Comment by lukaszfryc** [comment]
@nikitalukianov does it mean the message I sent while being offline will not be automatically delivered after I'm back online? Will I need to tap sent again button manually?

**Comment by chadyj** [comment]
After the timeout the message will need to be sent manually via the tap>resend method.

**Comment by nikitalukianov** [comment]
@lukaszfryc @chadyj yes it fits
