### ISSUE TITLE
Messages are not received in chats or stay in 'Waiting for message to arrive...' state

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3786]
***Type***: Bug

***Summary***: With the new protocol changes made in latest nightly develop build there are issues with message receiving.  What happens is that even device stays online - the app frequently loses connection, so messages sent to this Contact are not received. After some time once message sender sends one more message - it picks up all previous messages from offline inbox (from offline inbox - because bunch of unreceived messages appears in 'Waiting for message to arrive...' state - very similar to that described in #3778 but here Contact does not even need to go into offline mode).

#### Expected behaviour
No lost messages when exchanging in 1-1 / public chat

#### Actual behavior
Messages are not received in 1-1 / public chat. If to keep send messages then at some point the last sent message is received by the recipient and everything that were previously not received appears as 'Waiting for a message to arrive...' and keep stay in that state (I waited > 10 minutes).
![2018-04-06 14 36 48](https://user-images.githubusercontent.com/8749671/38420688-4a5d294a-39ad-11e8-8bfb-cbb102595874.jpg)

### Reproduction

- Install fresh build on Device 1 and Device 2
- Create Contact1 and Contact2 respectively
- Contact1 adds Contact2 in contacts 
- Both contacts navigate to 1-1 chat
- Contact1 sends 20 messages to Contact2
- Contact2 sends 20 messages to Contact1

### Additional Information
* Status version: 0.9.10-847-g74281a74+ (nightly for the 6th of April)
* Operating System: Android and iOS

#### Logs

TF logs for two device sessions can be seen here:
https://app.testfairy.com/projects/4803590-status/builds/8054021/sessions/6/?accessToken=5EmvIeVdbOvjg1c6LzLgFonSOV0
https://app.testfairy.com/projects/4803622-status/builds/8053965/sessions/61/?accessToken=tQkFFR5W8TznDXPHnSjyUStFgq4

**Comment by flexsurfer** [comment]
fixed by https://github.com/status-im/status-react/pull/3836

**Comment by Serhy** [comment]
In the develop build which includes #3836 fix (336 nightly) - can't reproduce anymore on Android 6.0 (Note 4 real device), Android 7.0 (Samsung J7 real), iPhoneX.
All messages arrive at accounts, no lost messages as well as no 'Waiting for a message to arrive anymore...'. 
Gladly closing this issue!
