### ISSUE TITLE
[WIP] Improve network offline and mail server error messaging

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3787]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to know when problems are preventing me from sending or receiving messages so that I can wait or take other action

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Errors such as being offline or mail server issues prevent users from chatting. Therefore we should clearly surface these to inform the user. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

When a user can't send or receive messages, they should know the state. The user can either wait or take action (eg, connect to wifi)

#### Actual behavior
[comment]: # (Describe what happened.)

When a user can't send or receive messages, they have no idea of the state and can get frustrated.

### Solution

Todo: designs.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2800.00
Contract address: [0x487fa83df50215e8f07fccbc67971de02849d6a5](https://etherscan.io/address/0x487fa83df50215e8f07fccbc67971de02849d6a5)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by lukaszfryc** [comment]
Note that this status should be shown in chats list (Home tab) as well.

**Comment by denis-sharypin** [comment]
Do we have somewhere a documentation with all possible errors and what copy we use?  Or shall we create it
