### ISSUE TITLE
Can't delete a chat swiping it 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3788]
### User Story

As a user I want to be able to delete chat swiping them

### Description

*Type*: Bug

*Summary*: Unable to delete a chat when clicking Delete button after swiping a chat on the chat's list

#### Expected behavior
Chat is deleted

#### Actual behavior
Delete button disappears but chat is not removed from the list

### Reproduction

- Open Status
- Create a chat (1to1 or join public one)
- Swipe a chat element
- Press Delete button

### Additional Information
* Status version: 74281a74 (nightly build from Apr 6)
* Operating System: 
Real device iPhone 8+, iOS 11.1.1
Real device LG V20, Android 7.0

**Comment by kwingram25** [comment]
Not sure where this was introduced but it seemed to be calling :delete-chat and crashing, instead of :remove-chat.
