### ISSUE TITLE
Measure message send/receive ratio on internal builds

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3792]
### User Story

As a developer, I want to measure the ratio of sent and received messages on real devices with real users so that I can benchmark deliverability reliability.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Message reliability is a crucial feature of Status, but it in a decentralized environment it can be difficult to measure. To ensure that Status is working as expected we can collect additional information on internal/dev builds for deliverability analysis. 

We use Mixpanel for event tracking and this can be modified to include extra data such as local client states and message ID for both sending and receiving events. Later, this data can be analyzed to determine the send/receive ratio.

### Solution

On dev builds modify Mixpanel:

- [ ] Modify the opt-in to be always enabled
- [ ] For sending, add extra events for local node received and local node delivered with the message ID as a property
- [ ] For receiving, add extra events for local node received and local node displayed with the message ID as a property

Create a script to query this data:

- [ ] Query the [Mixpanel Data Export API](https://mixpanel.com/help/reference/data-export-api#segmentation) to grab events created above with message ID
- [ ] Match sent message ID's to received message ID's to determine the send/receive ratio

**Comment by oskarth** [comment]
Requires closed access, unable to bounty.

**Comment by lukaszfryc** [comment]
We could track message ID and timestamp. As you've said, we would connect IDs of sent and received message to determine if the message was delivered and how much time it took (after filtering out cases when a user was offline).

We also need to know if a recipient of message enabled sharing usage data. If not, we never know if the message was delivered. The simple solution is to always track the messages in our internal builds.

Maybe it could be tracked below the UI level (status-go), stored in Elastic and visualized/queried in Kibana? Kibana allows for advanced querying. I wonder if we could track this data on production builds. This would be our ultimate metric for "99% send/delivered" KR. @chadyj do you think we can ask users for it or it's really a privacy issue?

**Comment by cammellos** [comment]
Elasticsearch would handle this fine, you can use aggregations to get the send/receive ratio, you might need to be a bit careful on how to structure your data, just to make sure it's easy to query.

**Comment by lukaszfryc** [comment]
Yeah, I think it could be much more powerful in terms of processing the data. We could also put there some other technical logs.

**Comment by chadyj** [comment]
> @chadyj do you think we can ask users for it or it's really a privacy issue?

No. We don't want to track metadata.

**Comment by lukaszfryc** [comment]
> We also need to know if a recipient of message enabled sharing usage data. If not, we never know if the message was delivered. The simple solution is to always track the messages in our internal builds.

@chadyj what do you think? If we don't know if a recipient has data sharing enabled, we may mess up our results. Some messages may never be delivered.

**Comment by lukaszfryc** [comment]
How about tracking the timestamp to calculate time it took to deliver a message?

**Comment by chadyj** [comment]
> what do you think? If we don't know if a recipient has data sharing enabled, we may mess up our results. Some messages may never be delivered.

@lukaszfryc First checkbox in the issue 😎 

> How about tracking the timestamp to calculate time it took to deliver a message?

Cool idea

**Comment by cammellos** [comment]
@lukaszfryc tracking the timestamp would only be accurate if the two clocks are synchronized ( or sender and receiver are on the same box). 

We can still track it but we need to take that into account when analyzing the data.

Otherwise you can track the receiving of the tracking event on mixpanel/elasticsearch, under the assumption that the server/cluster clocks are synchronized. 

Time Taken = Time "received event" received - Time "sent event" received

You still would have to take into account the average network delays, but it would probably start smoothing as we collect more data.

**Comment by lukaszfryc** [comment]
@cammellos what does it mean that two clocks are synchronized? Can't we just track utc time of "sent" and "received" events?

**Comment by cammellos** [comment]
@lukaszfryc depends on what you mean. 

I took that in the previous comment you meant to use the message timestamp to check how long it would take, but maybe I misunderstood.

If you use the time of "sent" and "received" events, as long as you calculated it on the server (elasticsearch/mixpanel), then you should get fairly accurate timing, provided you account for network delays.

**Comment by lukaszfryc** [comment]
Yes, I was thinking about time it takes for messages to be delivered.

> If you use the time of "sent" and "received" events, as long as you calculated it on the server (elasticsearch/mixpanel), then you should get fairly accurate timing, provided you account for network delays.

Yes, this is what I meant. I wonder if we are going to be able to calculate it in Mixpanel. Probably not. So, I think we can start with just send/delivered ratio (what this issue is about) and then extend it (if we still think it's important) to calculate delivery time (then we would probably need elasticsearch and kibana).

**Comment by cammellos** [comment]
It seems mixpanel does export the time an event arrived https://mixpanel.com/help/reference/exporting-raw-data , we will not be able to calculate it on mixpanel, but if we export the data we could.

<blockquote><div><strong><a href="https://mixpanel.com/help/reference/exporting-raw-data">Mixpanel | Product AnalyticsExporting Raw Data - Mixpanel | Product Analytics</a></strong></div><div>Learn how people use your app with the world's most advanced mobile & web analytics. Try it for free.</div></blockquote>

**Comment by lukaszfryc** [comment]
That would be great. cc @rasom
