### ISSUE TITLE
Improve timestamps in chat messages

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3793]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see timestamps so that I know when messages were sent.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Show timestamps of messages on messages. When messages are sent in quick succession they will be grouped.

#### Expected behavior
Display timestamps with grouping.

### Solution

![time_stamps_preview_final](https://user-images.githubusercontent.com/33906272/38620551-5ce8fdf2-3da7-11e8-9649-13383c4d1a51.png)

**Comment by lukaszfryc** [comment]
@chadyj is it always going to be the time message has been sent (presented in device timezone)? E.g I'm sending a message now and Status shows current time in my timezone. The message is delivered after 30min because the recipient was offline. The time recipient sees is the time message was sent (the same time that I saw). She sees it in her local timezone.

**Comment by chadyj** [comment]
@lukaszfryc Not sure what is implemented in Go currently, but this issue is just surfacing that internal time.

**Comment by cammellos** [comment]
@lukaszfryc correct, it will always be the time of the sender. 
@chadyj  do we have any designs ready for this? I had a look around but could not find any. Adding the timestamp in the message bubble a la whatsapp seems like a good starting point, what do you think?

**Comment by chadyj** [comment]
@cammellos Should be ready tomorrow. @nikitalukianov is working on it.

Here is a WIP from old designs for reference.

<img width="572" alt="screen shot 2018-04-10 at 8 16 49 pm" src="https://user-images.githubusercontent.com/116099/38575637-2d4fb56e-3cfc-11e8-811c-2da617ae9e95.png">

**Comment by nikitalukianov** [comment]
![time_stamps_preview_final](https://user-images.githubusercontent.com/33906272/38619699-6766fccc-3da5-11e8-8fbd-95e15ce93246.png)

**Comment by cammellos** [comment]
@nikitalukianov thanks, just to make sure `Yesterday 1:15 PM` should be `Yesterday`, correct? 

Also I would not mind having a go at this, I have yet to write any UI code, would that be ok if I remove the bounties?

**Comment by nikitalukianov** [comment]
This variation more easiest and understandable for our users. We need to make time stamps to the next each messages, and make it this color: #939BA1 50% opacity.
@cammellos you're right, lets make just "Yesterday". I can reload this image in correct form, ok?

**Comment by cammellos** [comment]
@nikitalukianov I think it's ok, it is clear from the comments, thanks!

**Comment by nikitalukianov** [comment]
![time_stamps_preview_final](https://user-images.githubusercontent.com/33906272/38620551-5ce8fdf2-3da7-11e8-9649-13383c4d1a51.png)

**Comment by nikitalukianov** [comment]
@cammellos sorry I just wanted to upload the right option :)

**Comment by denis-sharypin** [comment]
@nikitalukianov hey please provide font size of the timestamp, a margin between the timestamp and chat bubble.

**Comment by nikitalukianov** [comment]
I prepared this screens in Zeplin: https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/dashboard?seid=5ad5db84c95888398402eb0d

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by lukaszfryc** [comment]
I've been playing with latest nightly that has the timestamps. It seems for me that having them always visible for every message maybe distracting. Also, a timestamp takes a lot of vertical space, causing the message bubbles to shrink. 

@nikitalukianov @hesterbruikman Have you considered displaying timestamps only when a user taps on the message like in Facebook Messanger? 

@nikitalukianov In case we had this discussion and decided to always display them, maybe we should put the timestamp inside the message bubble? This would allow us to maximize the space which would allow us to show more messages in one screen:

<img src="https://user-images.githubusercontent.com/7532782/38918740-e431f5ce-42ee-11e8-9fe3-c1b30ad65956.png" width="300">

**Comment by hesterbruikman** [comment]
Thanks for checking @lukaszfryc! I would opt for option 2 timestamp inside message bubble.

Given that issues with ordering and delivery of messages are likely to occur, I believe the timestamp is to important to 'hide'. Also, it adds information such as scanning for the amount of time between messages, which would otherwise require a back and forth of tapping in individual messages.

@nikitalukianov, I'm sure you've put more thought into this. What do you think?
