### ISSUE TITLE
Cannot find entry file index.android.js when running "react-native run-android"

### ISSUE THREAD

**Issue by blockchain1977** [status-im/status-react#3797]
### User Story

As a developer, I want to run compile and deploy status-react into Android Emulator so that debug the code of status-react.

### Description

Cannot find entry file index.android.js in any of the roots when running "react-native run-android"

### Reproduction

On Ubuntu 16.04, I downloaded status-react source code and ran "scripts/setup". It hang somewhere. So that I ran "yarn install" to do the setup instead and it finished successfully.
I ran "Metro Bundler". Then, in another terminal, I ran"react-native run-android" to deploy it to emulator. It build successfully, but in Metro bundler terminal, I got below error:
error: bundling failed: NotFoundError: Cannot find entry file index.android.js in any of the roots: ["/home/yplyf/status-react-develop"]
    at DependencyGraph.getAbsolutePath (/home/yplyf/status-react-develop/node_modules/metro/src/node-haste/DependencyGraph.js:317:11)
    at /home/yplyf/status-react-develop/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:280:416
    at Generator.next (<anonymous>)
    at step (/home/yplyf/status-react-develop/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:11:445)
    at /home/yplyf/status-react-develop/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:11:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 BUNDLE  [android, dev] ./index.android.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

- Open Status
- ...
- Step 3, etc.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by mukulverm4** [comment]
Hey @blockchain1977 , I'm having the same issue, how did you solve this?
