### ISSUE TITLE
Missing iOS App Store Icon

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3799]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to iOS builds to iTunes Connect so that there aren't any errors.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

Every iOS submission Apple complains about an error on submission:

> We identified one or more issues with a recent delivery for your app, "Status - Ethereum. Anywhere.". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Missing App Store Icon - iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

THis should be fixed to make sure it isn't a blocker for beta.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

iOS can be submitted without issue

#### Actual behavior
[comment]: # (Describe what actually happened.)

iOS is submitted with an error

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Submit iOS to iTC

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

A possible solution here https://stackoverflow.com/a/47051829

@andmironov @denis-sharypin Can you add the 1024x1024px App Store Icon in PNG format?

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: All
* Operating System: iOS

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/">App Icon - Icons and Images - iOS Human Interface Guidelines</a></strong></div><div>Learn about designing apps for iOS.</div></blockquote>
<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div><strong><a href="https://stackoverflow.com/questions/46987694/missing-app-store-icon-ios-apps-must-include-a-1024x1024px-app-store-icon-in/47051829">Missing App Store Icon. iOS Apps must include a 1024x1024px App Store > Icon in PNG format</a></strong></div><div>when I try to submit the app 
  Missing App Store Icon. iOS Apps must include a 1024x1024px App Store
  Icon in PNG format. Without providing the icon in the Asset Catalog or
  via iTunes Connect,...</div></blockquote>

**Comment by denis-sharypin** [comment]
We haven't updated all our ios and android icons with new color and fixed glyph shape.  Do you think it could be fixed here as well? I provide you with AppStore icon but with new color and the new glyph. What do you think? 
——
Here it is:
![app store 1024px x 1024px](https://user-images.githubusercontent.com/6559881/38494813-84d4963e-3bf7-11e8-9e5b-2b3cea819c4c.png)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x424f8556fe694606ae2f4d83c2e5bf8a9b8ec0fcdc41454f7c42a324e4511ca5](https://etherscan.io/tx/0x424f8556fe694606ae2f4d83c2e5bf8a9b8ec0fcdc41454f7c42a324e4511ca5)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0xf501dc1282f69ccc3156dac31d30d47ba2e8093e](https://etherscan.io/address/0xf501dc1282f69ccc3156dac31d30d47ba2e8093e)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
