### ISSUE TITLE
Can't open ERC dEX DApp twice

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3805]
### User Story

As a user I want to have an ability to open DApps again after deleting already opened DApps from chats list 

### Description

*Type*: Bug

*Summary*: Can't open ERC dEX DApp more that once after deleting it from the chat's list

#### Expected behavior
Can open ERC dEX DApp 

#### Actual behavior
Loading indicator is showing for a long time and the DApp page was not finally loaded

<img width="330" alt="aa" src="https://user-images.githubusercontent.com/29711298/38436629-cd74a030-39dd-11e8-87fe-a9924b33839b.jpeg">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click Plus button -> Open DApp -> ERC dEX -> Open
- Click Metamask on the appeared pop up, click Back and close the pop up
- Click Back button
- Swipe and delete ERC dEX chat element
- Click Plus button -> Open DApp -> ERC dEX -> Open

### Additional Information
* Status version:
Android: https://i.diawi.com/b2mNK3
iOS: https://i.diawi.com/G3CwoP
* Operating System: 
Real devices LG V20 (Android 7.0), iPhone 8+ (iOS 11.1.1)

<blockquote><div><strong><a href="https://i.diawi.com/b2mNK3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/G3CwoP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
can't reproduce on ios

**Comment by rachelhamlin** [comment]
I can't reproduce this either, using https://i.diawi.com/DUNFmn on iOS.

<blockquote><div><strong><a href="https://i.diawi.com/DUNFmn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by yevh-berdnyk** [comment]
It's still reproducible for me on the recent nightly (3af05bcb), please see the video: https://app.testfairy.com/projects/4803590-status/builds/8260990/sessions/11 (from 00:35)
Looks like it's because of some clicks inside the DApp webview, I'll update steps

**Comment by jeluard** [comment]
@yevh-berdnyk Can you share something public (logs)? We don't have TF access.
Also do you have more precise steps to reproduce the issue?

**Comment by yevh-berdnyk** [comment]
Checked and now can't reproduce also so closing the issue
