### ISSUE TITLE
Disable external bots

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#3813]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to disable unused features that might introduce a security risk. External bots is one of them.

### Description

*Type*: Bug

Disable the ability to execute external bots. This is done by removing the `debug` command available in the console.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 880.00
Contract address: [0x8179fe0a1b9ad641f5dcdd080fca14bd4fc90116](https://etherscan.io/address/0x8179fe0a1b9ad641f5dcdd080fca14bd4fc90116)
Network: Mainnet
Paid to: debragail
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by endenwer** [comment]
@jeluard Does this issue cancel this #3884?

**Comment by jeluard** [comment]
@endenwer It does indeed! Thanks for the heads up!
