### ISSUE TITLE
Disable iOS predictive text for passphrase

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3817]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to type my passphrase so that iOS doesn't track and store sensitive information.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

iOS learns the passphrase after recovering the same account multiple times. After learning the phrase iOS will then suggest the exact phrase when recovering with its predictive text feature.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When recovering the account iOS should have no knowledge of my passphrase

#### Actual behavior
[comment]: # (Describe what actually happened.)
When recoving the account iOS suggests my exact passphrase through its predictive text feature.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Recover an account several times
- Eventually iOS will suggest the passphrase

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Remove the predictive text feature from the passphrase recovery, and any other place the passphrase is entered.

Possible solution here https://developer.apple.com/documentation/uikit/uitextinputtraits/1624453-autocorrectiontype

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightly
* Operating System: iOS 11.3

<blockquote><img src="/documentation/__assets/favicon.ico" width="48" align="right"><div><strong><a href="https://developer.apple.com/documentation/uikit/uitextinputtraits/1624453-autocorrectiontype">autocorrectionType - UITextInputTraits | Apple Developer Documentation</a></strong></div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 900.00
Contract address: [0x965f94d30964eaf345f57ddc0fa220f77feb0f6e](https://etherscan.io/address/0x965f94d30964eaf345f57ddc0fa220f77feb0f6e)
Network: Mainnet
Paid to: kwingram25
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by lukaszfryc** [comment]
It seems to be only iOS issue. I did some research on Android and have not found anything like that.
