### ISSUE TITLE
If a message contains only an emoji, show it without chat bubble

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3818]
### User Story

As a user, I want to see a big emoji and don't want to have them in the 'chat bubble jail' so that I will get more fun.

### Description

*Type*: Feature

*Summary*: Currently when you send emoji in a chat it appears in a chat bubble that makes it really small to recognize. We would like to remove this bubble for messages that contain only emojis. 

#### Expected behavior
![emoji free](https://user-images.githubusercontent.com/6559881/38541433-5b902f88-3c9f-11e8-8ee8-8a41d7d33601.jpg)

#### Actual behavior
![emoji jail01](https://user-images.githubusercontent.com/6559881/38541441-61457c12-3c9f-11e8-9571-5c3021b82862.jpg)

### Solution

- use fontSize:40, lineHeight: 45 for emoji
- you need to render an emoji without a chat bubble right after it's sent to a chat
- this should work not only for one emoji also for multiple emojis  

### Additional Information

* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2800.00
Contract address: [0xceebb14acc54511a4bcd68691f18d68401e900ba](https://etherscan.io/address/0xceebb14acc54511a4bcd68691f18d68401e900ba)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by ovx** [comment]
I have a commit which fixes this issues here https://github.com/ovx/status-react/commit/7a4d1adea8165e379f059e4171b5fb6941755d30 but the problem with emoji is that this simple regex doesn't necessarily match all of them.

I ES6 there is a unicode mode for regex (https://github.com/tc39/proposal-regexp-unicode-property-escapes#matching-emoji) which should work better but this mode doesn't currently work in react native (not sure whether this is a problem with react-native or clojurescript transpiler).

If anyone has an idea how to make the regex more reliable or how to enable the unicode mode, please let me know.

![screenshot_1523428840](https://user-images.githubusercontent.com/536331/38600327-5fb58c82-3d96-11e8-8931-b21f087b0089.png)
![screenshot_1523428847](https://user-images.githubusercontent.com/536331/38600329-5fece6a0-3d96-11e8-9522-f06b636a5f3d.png)
![screenshot_1523428855](https://user-images.githubusercontent.com/536331/38600330-60225f2e-3d96-11e8-86aa-2615c6cca86b.png)




<blockquote><img src="https://avatars3.githubusercontent.com/u/1725583?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/tc39/proposal-regexp-unicode-property-escapes">tc39/proposal-regexp-unicode-property-escapes</a></strong></div><div>proposal-regexp-unicode-property-escapes - Proposal to add Unicode property escapes `\p{…}` and `\P{…}` to regular expressions in ECMAScript.</div></blockquote>

**Comment by denis-sharypin** [comment]
@goranjovic  @jeluard  @flexsurfer  Could you assist guys? ↑

**Comment by jeluard** [comment]
@ovx This [article](https://medium.com/reactnative/emojis-in-javascript-f693d0eb79fb) might help. Specifically it mentions a regexp used by lodash we could use.
Please also consider the performance impact of this.

**Comment by ovx** [comment]
@jeluard Thanks! lodash's regex helps a lot, with some additional tweaking for this guy (☺️) it handles all emoji in my test screen, but there probably will be more codes which are not handled by this regex.

It has, of course, some performance impact, but I don't see any other solution for detection of emoji. (Except for the unicode mode which should be fast I assume)

**Comment by janherich** [comment]
@ovx The thing is, regex lookups are expensive, so we should probably think about caching them (have a look at the private `parse-text` function in the namespace, and how is used), because view functions by default are NOT cached and will be run each time something in subscription changes (react VDOM diffing will make sure that even when those functions are run and producing output multiple times, actual expensive DOM changes will be performed only when necessary).

That's the reason why view functions must be:
1. side effect free
2. as lightweight and fast as possible

Point 2. is of the particular concern here :)

**Comment by endenwer** [comment]
I also wanted to do this. But I thought to add flag `emoji-only?` to message and set that flag when saving message to data store. It would be more performant but wont work for messages what already in the store.

**Comment by ovx** [comment]
@janherich I understand that, but you have any other idea how to detect emoji? Ad `memoize`, does it actually have some sort of upper limit for memory usage and garbage collection or does the memory consumption grow into infinity? I didn't find any documentation for that.

**Comment by janherich** [comment]
The performance of running regex once when new message is being rendered is most probably super negligible (we already have more complicated regexes which are also run each time message is being rendered to transform url's in message text into clickable actions), it will be overshadowed by actual rendering.
The problem is naive implementation when we just call the regex in view function without any caching.
The cleanest solution would be to push all those expensive regex stuff (existing + this new one) into subscriptions, because those are cached by default.

**Comment by jeluard** [comment]
@ovx Do you mind running some basic bench on long lines on real hardware? To get some ballpark figure.
Also no, `memoize` is not bound, you control when you don' want to call it.

**Comment by janherich** [comment]
@ovx Detecting via regex is fine, we just have to make sure that this detection happens only when necessary. Memoize not having upper bound is not a problem, we have lazy loading and don't render every message in chat when it's opened + it will be just minor (constant) increase of memory for each message rendered (we will still have way more messages in app-db then that, unless you open all the chats and scroll to the very top in each of them, in which case it will be the same :) )

**Comment by ovx** [comment]
@jeluard @janherich I will implement `memoize` and also apply regex match only on very short messages (let's say <= 20 chars, which would allow 10 emoji and if there's more it will simply have a bubble). I'll also try to get some benchmarks with and without matching.

**Comment by cammellos** [comment]
Another option is to just store that in the database, at the expenses of storage, you only check on receive if the message contains an emojii ( say you have a message-type of :emoji), not sure whether is worth considering for this though.

@janherich while I agree that will likely never be a problem using an unbound memory structure, I would avoid it if not necessary (`clojure.core.memoize` has a few cache eviction policies and it's already pulled in by core.async I believe).

I feel that makes it much simpler to track down memory leaks, which are already hard to deal with ( If I know this code does not leak, I don't have to worry about it when debugging a memory leak).

**Comment by janherich** [comment]
@cammellos Sure, that's why I said the cleanest solution would be to pull all those more expensive things into `re-frame` subscriptions, which do "proper caching" :)
Additional benefit would be logic free uncluttered view functions, more portable to desktop project, etc.

**Comment by cammellos** [comment]
@janherich yes, agree with you

**Comment by ovx** [comment]
@janherich thanks, re-frame subs sound like a good solution, I'll check them out.

**Comment by ovx** [comment]
@jeluard ad benchmarks: both versions, with and w/out the change, report the same UI frame rate when opening and scrolling (59 FPS on my device which is the maximum it reports when idle). Everything feels just about the same in both versions, smooth and responsive. Tested with about 150 messages, mostly emoji-only messages mixed with short and long text.

**Comment by endenwer** [comment]
My implementation  endenwer/status-react@c97678d20db0f1e940f2c4cd97df6ce69d83230b. I don't know if I can submit it or not cause I am not first.
