### ISSUE TITLE
User is redirected to Home tab when changes to Profile applied

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3819]
### Description

*Type*: Bug

*Summary*: When changes to the profile applied (like user name or user picture) user is redirected to Home tab instead of staying on Profile 

#### Expected behavior
Profile tab is still shown when i save changes to my profile

#### Actual behavior

home tab is shown

### Reproduction
- Open Status
- Tap profile
- Edit user name and save

### Additional Information
* Status version: nightly 09/04/2018
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
Fixed in https://github.com/status-im/status-react/pull/3801
