### ISSUE TITLE
Ability to "block" chat UI completely

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#382]
![screen shot 2016-10-21 at 15 21 51](https://cloud.githubusercontent.com/assets/911127/19598216/48353c24-97a2-11e6-9ce4-b5254698866c.png)

**Comment by jarradh** [comment]
steps to reproduce?

**Comment by alwx** [comment]
@jarradh just add a location 3 times

**Comment by jarradh** [comment]
ah it's in staging area ??

**Comment by alwx** [comment]
@jarradh yes. sorry, there is a lack of details in this description.
But I am working on this task now :)
