### ISSUE TITLE
Can't scroll assets when having more than 3 in the list

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3820]
### Description

*Type*: Bug

*Summary*: Assets are not shown when having more than 3 in the list

#### Expected behavior
I want to scroll list of assets

#### Actual behavior
I can't scroll the list

![image](https://user-images.githubusercontent.com/28752642/38543316-f465bb08-3cac-11e8-918b-17d86e459c72.png)

### Reproduction

- Open Status
- Switch to Mainnet
- Go to Wallet -> Manage assets -> select any 4 assets
- Try to scroll assets list

### Additional Information
* Status version: nightly 10/04/2018
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803590-status/builds/8071890/sessions/27/?accessToken=DftjZmJcxg7vYepZJ3j5To9iI9A

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8071890/sessions/27/?accessToken=DftjZmJcxg7vYepZJ3j5To9iI9A">TestFairy: Status 0.9.16 (2408) @27</a></strong></div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x61169dc4582ba128288a05206f5051dd6dc54a89039c06572ae57f834bb0e15d](https://etherscan.io/tx/0x61169dc4582ba128288a05206f5051dd6dc54a89039c06572ae57f834bb0e15d)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x81c1bca764f23cce5d15886a3b6d212a42ee212c](https://etherscan.io/address/0x81c1bca764f23cce5d15886a3b6d212a42ee212c)
Network: Mainnet
Paid to: goranjovic
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
