### ISSUE TITLE
Wallet screen loads longer than usual because of lots of :update-prices-* events

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3821]
### Description
*Type*: Bug

*Summary*: Switching to Wallet screen is really slow on the latest nightly. It takes 2-4s. Seems to be related to lots of`:update-prices-*` events being dispatched.

#### Expected behavior
Wallet screen loads as fast as usual. There are no unnecessary `:update-prices-*` events.

#### Actual behavior
<img src="https://user-images.githubusercontent.com/7532782/38545053-717b8c8e-3ca9-11e8-9bd1-78a01462c937.png" width="200">

### Reproduction
- Open Status
- Go to Home 
- Switch to Wallet

### Additional Information
* Status version: nightly, April 10
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0xb43886468798cd1686981b6aa6a1e1021bba06c6](https://etherscan.io/address/0xb43886468798cd1686981b6aa6a1e1021bba06c6)
Network: Mainnet
Paid to: yenda
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
