### ISSUE TITLE
Message content cleared from message input box after tap on chat view screen

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3825]
***Type***: Bug

***Summary***: When a user has message content in the message input box and taps on the chat screen area, - we hide the keyboard. However, along with that, we clear the message content which is entered. We need to keep it.
**Note:** If user taps on back to Home screen button (`<` one) or chat settings (`...` one) in the app top bar - keyboard hides but message input box content is not cleared after the user returns back to chat screen, as expected.  

#### Expected behaviour
Message content is kept in message input box after a tap on chat view screen

#### Actual behaviour
Message content cleared from message input box after a tap on chat view screen

### Reproduction

- Open Status
- Start any type of a new chat (e.g. join public chat `tappingoutside`)
- Tap inside message input box
- Type a text (any text with/without emoji)
- Tap inside chat view above message input box

### Additional Information
* Status version: 333rd nightly develop, release 0.9.15
* Operating System: Android and iOS

TF video with the issue: https://app.testfairy.com/projects/4803590-status/builds/8073365/sessions/21/?accessToken=XDtUp-4DWxbJKB92KwMtPA0DwBU

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8eca0730ad1fd8af1d55aca60354a7a4c0499d6aaa15b848ac8e49c89746c7bc](https://etherscan.io/tx/0x8eca0730ad1fd8af1d55aca60354a7a4c0499d6aaa15b848ac8e49c89746c7bc)

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/pull/3860#issuecomment-383835863

**Comment by Serhy** [comment]
I've retested this issue and can confirm it's fixed!
