### ISSUE TITLE
TestFlight Invite Problem

### ISSUE THREAD

**Issue by skypper** [status-im/status-react#3828]
I receive the following error when I try to opt-in to test the iOS app.
_Something went wrong, please contact the application owner: {"code"=>"ITC.apps.tf.max.app.testers", "description"=>"Failed to create tester."}_

PS: I couldn't find any contact form on the website to report the issue.

**Comment by chadyj** [comment]
Thanks for the bug report.

I tried to reproduce the issue but didn't encounter the problem. Maybe there was a temporary issue, or perhaps an issue with your account.

Would you mind trying again and seeing if the issue is still there?

**Comment by skypper** [comment]
Now it works. Thanks!

**Comment by Wmaxson** [comment]
I just got the error too. Does it fix with time?

Something went wrong, please contact the application owner: {"code"=>"ITC.apps.tf.max.app.testers", "description"=>"Failed to create tester."}
