### ISSUE TITLE
Hide tab bar when editing userpick in the profile

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3832]
### User Story

As a user, I don't want to see a tab bar while editing the photo so that I could be fully focused on that process.

### Description

*Type*: Bug

*Summary*: Fun Android bug that keeps showing a tab bar above keyboard while a user is editing userpick or name. Tab bar should be hidden. Check iOS build for reference.  

#### Expected behavior
<img width="428" alt="screenshot 2018-04-11 11 10 45" src="https://user-images.githubusercontent.com/6559881/38607479-0874fbd2-3d79-11e8-9946-3a61b2180937.png">

#### Actual behavior
![image 2018-04-11 11 08 55](https://user-images.githubusercontent.com/6559881/38607372-ba737684-3d78-11e8-93d1-1295365817dd.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open profile tab
- Tap Edit in the right top corner

### Additional Information
* Status version: nightly 10.05.2018
* Operating System: Android

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x424f8556fe694606ae2f4d83c2e5bf8a9b8ec0fcdc41454f7c42a324e4511ca5](https://etherscan.io/tx/0x424f8556fe694606ae2f4d83c2e5bf8a9b8ec0fcdc41454f7c42a324e4511ca5)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 900.00
Contract address: [0x0369f02310d0ee904063617a495005e7d725b0bf](https://etherscan.io/address/0x0369f02310d0ee904063617a495005e7d725b0bf)
Network: Mainnet
Paid to: kwingram25
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
