### ISSUE TITLE
Move to yarn instead of npm

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#3838]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer,
I would like to use yarn instead of npm,
because it's faster (in our case) and does not get stuck installing packages

### Description

We agreed to move to yarn instead of npm.

We tried to do so but failed as we were not able to build a release in a reasonable amount of time.

Moving to yarn is a trivial code change, but after:
`lein prod-build`

and

`cd android && ./gradlew assembleRelease`

it would take a very long time to create the artifact, around 6 hrs on my local machine ( compared to 6 minutes when installing packages through npm). 

This has been replicated locally, on docker and on the macos build server.

The steps that fails is `app:bundleReleaseJsAndAssets`.

We see `jest-worker` hogging the CPU at 100%, memory consumption is also quite high, once it actually failed because the node engine could not allocate memory.

### A few scattered thoughts that might help

There are a few issues (some closed) https://github.com/facebook/react-native/issues/11696 which seems to indicate that it's bundling files that it should not be (realm files for example).

Some people mentioned `.babelrc` was the culprit, but did not elaborate any further.

### What we tried, but did not work

Increase node memory from 4GB to 8GB
Increase gradlew memory from 1GB to 4GB
Add `___tests__` to `inputExcludes` in `android/app/react.gradle`
Decrease the number of `jest-workers`

Currently we don't have the bandwidth to look into this any further, but if anyone wants to have a go at this it would be helpful.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xee349053ea260f7e5577f15f2806c67df9257ac53520ac768c842189ad47e69d](https://etherscan.io/tx/0xee349053ea260f7e5577f15f2806c67df9257ac53520ac768c842189ad47e69d)

**Comment by andytudhope** [comment]
@dbalatero got quite far with this before getting busy with his own work. Do you have any thoughts?

References:  
https://github.com/status-im/status-react/issues/2541
https://github.com/status-im/status-react/pull/2649

**Comment by cammellos** [comment]
thanks @andytudhope 
#2541 is not an issue anymore, as we don't use rn-nodeify anymore I believe
#2649 seems the same issue I believe, only happens on android

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 880.00
Contract address: [0x19de46086225f3e3355c16344a07ef6e886cf95e](https://etherscan.io/address/0x19de46086225f3e3355c16344a07ef6e886cf95e)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/3838/0d4ca89ccf64a0bc02c113d39476f306d9797f569b9eba540a10c73a357e125e/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by jeluard** [comment]
Closing for now as it appears moving to yarn is not practical for us.

**Comment by jeluard** [comment]
@alwx Can you share the gist of your findings?
