### ISSUE TITLE
Browse input in wrong place

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#384]
![ww](https://cloud.githubusercontent.com/assets/2364994/19600667/b8f81b5a-97ae-11e6-8005-fff7fcc87c4a.gif)

**Comment by rasom** [comment]
Might be related to these changes https://github.com/status-im/status-react/issues/349

**Comment by jarradh** [comment]
yeah thats not a smooth experience

**Comment by rasom** [comment]
iOS version isn't perfect too 

![ios](https://cloud.githubusercontent.com/assets/2364994/19601200/eef9be46-97b0-11e6-922e-6a6bb2c0a286.gif)

**Comment by jarradh** [comment]
`Obese Unused Fairyfly` :joy:

**Comment by alwx** [comment]
There is the same problem with suggestions (try to open it in fullscreen and then open a keyboard). Will also be fixed.
