### ISSUE TITLE
Half of the line is cut in the input field if focus is on the next line [Android]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3847]
### Description

*Type*: Bug

*Summary*:  Only on Android: First visible line in the input field is cut if focus is in the beginning of the other lines. 
![screenshot_20180412-115613](https://user-images.githubusercontent.com/6584810/38667108-43068164-3e49-11e8-885c-319220f472ec.png)

#### Expected behavior
All visible lines, including top line are fully shown (including capital letters) if focus is on the next lines. This happens to any line above the previous (2nd, 3rd...). This also happens if move away from the input field with typed text  and return back to the chat (e.g. go back from the Chat to Home and then open the Chat again, hide keyboard and then tap inside input field again...). 

#### Actual behavior
First visible line in the input field is cut if focus is in the beginning of the other lines. 

### Reproduction

- Open Status
- Open any chat, e.g. chat with Jarrad
- Start typing long sentence that will go to the next line. Check how the first line is shown when focus is moved to the next line. Proceed typing to get 9 lines in the input field and check how the top visible line is shown.

### Additional Information
* Status version: nightly build Apr 12
* Operating System: Android only

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x2722471b75387100c5d36972d5f986023e1b2803](https://etherscan.io/address/0x2722471b75387100c5d36972d5f986023e1b2803)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
Hi @annadanchenko , I've posted a fix for this at https://github.com/status-im/status-react/pull/4030 :cocktail: :beer:
