### ISSUE TITLE
Delete Jarrad contact

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3851]
The `Jarrad` default contact doesn't have the proper settings to work with the new protocol. This causes one to one chat with this contact to throw errors.
To fix is to simply delete the contact

**Comment by chadyj** [comment]
I recall Jarrad saying we should remove him as a default contact. 

From a UX point of view, if he doesn't reply it can be a bad experience for users to send messages that never get a reply.

**Comment by yenda** [comment]
Ok I updated the issue accordingly
