### ISSUE TITLE
User is redirected to new chat screen after pressing back button in a chat screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3852]
### Description
*Type*: Bug

*Summary*: When new chat is created and I press the back button, I get redirected to the new chat screen. I'd expect to be redirected to Home tab instead. 
Note that it also happens for chats that are already on the list but were reopened by selecting them from the new chat screen.

#### Expected behavior
A user is redirected to Home tab when pressing back button in the chat screen.

#### Actual behavior
A user is redirected to the previous screen she was on - New Chat. It seems logical but it's not intuitive (UX). 

### Reproduction
- Open Status
- Create new chat
- Press back button

### Additional Information
* Status version: Android, iOS
* Operating System: nightly, April 12

**Comment by lukaszfryc** [comment]
@denis-sharypin what do you think? Note that it also happens for chats that are already on the list but were reopened by selecting them from the new chat screen.

**Comment by denis-sharypin** [comment]
@lukaszfryc yep makes sense. I'm thinking about the more generic rule than an exceptional behavior for chats. Do you have ideas what this rule could be?

**Comment by lukaszfryc** [comment]
@denis-sharypin our general rule should probably be the default behaviour. Use the back button to always navigate to previous screen user was in. And this works fine for most of the cases. But, there are some exceptions like:
1. If you are on a main screen for a tab (Home, Wallet, Profile), the back button should close the app (**it does not work this way now but probably should**)
2. Navigation described in this issue

Please note that neither iOS nor Android gives any strict guidelines about the back button. The only thing they say is:

> **iOS**
The back button always performs a single action—returning to the previous screen. If you think people might get lost without the full path to the current screen, consider flattening your app’s hierarchy.
https://developer.apple.com/ios/human-interface-guidelines/bars/navigation-bars/
 
> **Android**
The system Back button is used to navigate, in reverse chronological order, through the history of screens the user has recently worked with. It is generally based on the temporal relationships between screens, rather than the app's hierarchy.
https://developer.android.com/design/patterns/navigation.html

So, it maybe worth to create a graph with screens and navigations. This can give us some idea of the patterns we may have.





<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://developer.apple.com/ios/human-interface-guidelines/bars/navigation-bars/">Navigation Bars - Bars - iOS Human Interface Guidelines</a></strong></div><div>Learn about designing apps for iOS.</div></blockquote>
<blockquote><img src="https://developer.android.com/_static/4817e41f83/images/android/favicon.png" width="48" align="right"><div><strong><a href="https://developer.android.com/design/patterns/navigation.html">Navigation with Back and Up | Android Developers</a></strong></div><div>Consistent navigation is an essential component of the overall user experience. Few things frustrate users more than basic navigation that behaves in inconsistent and unexpected ways. Thoughtfully following the guidelines for Back and Up will make your…</div></blockquote>

**Comment by lukaszfryc** [comment]
Related to #3903

**Comment by denis-sharypin** [comment]
@lukaszfryc  
What's the scope then:

1. Always navigate to the Home Tab from any chat screen with the back button 

2. Android only: If you are on the main screen for a tab (Home, Wallet, Profile), the back button should close the app 

What do you think?

**Comment by lukaszfryc** [comment]
@denis-sharypin sounds good. Re 1, we need to make sure that it happens only for chat screens. For instance, pressing back button in view profile screen should redirect back to the chat screen.
