### ISSUE TITLE
Can't receive offline inbox messages until re-login to account

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3853]
*Type*: Bug
*Summary*: Messages sent to contact which is offline - are not received after contact appears online. However, after re-login to account - sometimes not from the first try, - but offline messages received and in the appropriate order.
**Note:** It was confirmed that offline messages are received (after several account re-logins) while both contacts on Mainnet with upstream RPC and Ropsten with upstream RPC.

#### Expected behavior
Messages are received from an offline inbox after contact appears online 

#### Actual behavior
Messages are not received from an offline inbox after contact appears online 

### Reproduction
1) Install fresh develop build on Device 1 and Device 2
2) Create Contact1 and Contact2 respectively
3) Both contacts are online and exchanged a text messages
4) Contact2 enables airplane mode on device
5) Contact1 sends 10 text messages to Contact2
6) Contact2 disables airplane mode and stays on Home/1-1chat screen for 5+ minutes
**Actual result:** No messages received.

7) Contact2 re-logins to the account (or stops and starts the app)
**Actual result:** Messages are received from offline inbox. **Note:** It may require repeating several times this step as not always it works.

### Additional Information
* Status version: Develop nightly build (336th in Jenkins)
* Operating System: Android and iOS

#### Logs

From TF session https://app.testfairy.com/projects/4803622-status/builds/8092250/sessions/36/?accessToken=d6n--lIHkdqqi2Qo-9-ovwyxejc
noticed in logs:
```00:55 I/ReactNativeJS: INFO [status-im.transport.inbox:154] - Peer enode://fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce@163.172.168.202:30303 is not registered. Retrying fetch peers.
00:55 E/ReactNativeJS: ERROR [status-im.transport.inbox:157] - Could not connect to mailserver
00:55 E/unknown:ReactNative: console.error: "ERROR [status-im.transport.inbox:157] - Could not connect to mailserver", stack:
cljs$core$IFn$_invoke$arity$3@12:347932
cljs$core$IFn$_invoke$arity$2@12:347729
cljs$core$IFn$_invoke$arity$2@12:353001
c@12:5508618
r@12:5508800
<unknown>@12:3240368
<unknown>@12:3259703
cljs$core$IKVReduce$_kv_reduce$arity$3@12:545631
_kv_reduce@12:158196
reduce_kv@12:268208
cljs$core$IFn$_invoke$arity$10@12:3257009
<unknown>@12:6012645
<unknown>@12:3950520
invoke_interceptor_fn@12:3878457
invoke_interceptors@12:3878758
execute@12:3880455
handle@12:3890180
re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@12:3924913
re_frame$router$IEventQueue$_run_queue$arity$1@12:3905649
<unknown>@12:3911401
re_frame$router$IEventQueue$_fsm_trigger$arity$3@12:3915612
<unknown>@12:3908167
<unknown>@32:1369
x@32:643
callTimers@32:2788
value@27:3582
<unknown>@27:1067
value@27:3009
value@27:1039
02:27 D/ViewRootImpl: ViewPostImeInputStage ```

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8092250/sessions/36/?accessToken=d6n--lIHkdqqi2Qo-9-ovwyxejc">TestFairy: Status 0.9.10-869-g7148734e+ (2426) @36</a></strong></div></blockquote>

**Comment by yenda** [comment]
So in some cases messages are received by offline inbox ? It is a bit surprising because it seems that the mailservers in the config are ropsten mailservers and not mainnet so you should never receive any offline message

**Comment by Serhy** [comment]
Correct. Offline messages received (after tricks with re-login / stop-starting and app) in both cases: When contacts are on Mainnet with upstream RPC or Ropsten with upstream RPC. 
Updated description with this note.
TF session for offline inbox message receiving while contact is on the Mainnet RPC: https://app.testfairy.com/projects/4803622-status/builds/8092250/sessions/43/?accessToken=bVdRPEP8cp-R5hX308SwIyKh1oA

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8092250/sessions/43/?accessToken=bVdRPEP8cp-R5hX308SwIyKh1oA">TestFairy: Status 0.9.10-869-g7148734e+ (2426) @43</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
i am receiving this
![image](https://user-images.githubusercontent.com/28752642/39047633-3e0545f0-44a3-11e8-8d96-c97879f09c5a.png)
and i am able to receive messages @yenda . Is it something we can improve

i also noticed some time lag when receiving messages from offline, it is quite annoying

**Comment by yenda** [comment]
It's probably because mailserver is saturated. Regarding lag it can be improved by only fetching messages since last time it was done, I'll look into this next week
