### ISSUE TITLE
Contacts are not shown in group chat profile or commands suggestions (/send, /receive)

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3854]
### Description
*Type*: Bug

*Summary*: When a user is invited to a group chat by her contact, the contact is not listed in the group chat profile neither it is visible in commands suggestions. When `/send` is typed only the default contact ("Jarrad") appears. The user that created the group chat sees all members.

#### Expected behavior
All group chat members should be listed in profile (#3670) and commands suggestions (#3094).

#### Actual behavior
No contact or non-contact except the default one ("Jarrad") is listed in profile or in suggestions. 

<img src="https://user-images.githubusercontent.com/7532782/38689287-7f89c786-3e7b-11e8-8eb3-e7f0dcfea2fe.png" width="300">
<img src="https://user-images.githubusercontent.com/7532782/38689311-91fc55f0-3e7b-11e8-9ae6-b40e38f9422b.png" width="300">

### Reproduction
- Open Status on 2 devices
- Device A: Create 1-1 chat with Device B
- Device B: Add Device A as contact
- Device A: Create a group chat with Device B
-> Device B: Group chat profile shows empty list of members. "/send" suggestions are empty as well.  

### Additional Information
* Status version: nightly, April 12
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
cc @Serhy @asemiankevich @yevh-berdnyk

**Comment by yevh-berdnyk** [comment]
@lukaszfryc probably a duplicate of #3705 ?

**Comment by lukaszfryc** [comment]
Yes, it's a duplicate
