### ISSUE TITLE
Add ATT tokens support in Status

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3869]
### Description

*Type*: Bug

*Summary*: as we discussed with @andytudhope and @jeluard , Andy will be able to add ATT tokens support so we can exchange the tokens in Status app

#### Expected behavior
I can exchange ATT tokens in Status under Ropsten testnet

#### Actual behavior
no ATT support now

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1800.00
Contract address: [0xf673b783b7117903f240cd6c840fd2c469e20f57](https://etherscan.io/address/0xf673b783b7117903f240cd6c840fd2c469e20f57)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
