### ISSUE TITLE
Release 0.9.17 app version crash if message was sent to it's contact by the contact using Develop app version

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3870]
***Type***: Bug

***Summary***: If message sent (in 1-1 / public chat) by the contact who using latest develop to the contact who using current release 0.9.17 build -> app is crashed on 0.9.17 side. 
However viceversa works OK: 0.9.17 sends message to latest develop -> message is received 

#### Expected behavior
No crashes and message is received by the user who is on 0.9.17 app version if message sender sent it from develop app version 
#### Actual behavior
App crashes on the user side who using 0.9.17 app version if message was sent to him by contact using Develop app version. No any errors appears - app just freeze for ~ 1 minute and stops.

### Reproduction

- Install fresh Develop build on Device 1 
- Install latest 0.9.17 build on Device 2
- Create Contact 1 and Contact 2 respectively
- Both contacts join the same public chat (use unique public chat name here, e.g. `releasevsdevelop`)
- Contact 1 (Develop version) sends a message in public chat

### Additional Information
* Status versions:

Nightly Delelop builds: 
Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-32711c.apk
 iOS: https://i.diawi.com/Ww8DvR

0.9.17 release candidate build:
Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-d1bb3e.apk
 iOS: https://i.diawi.com/ExfX9b

* Operating System: Android and iOS

### Additional Information 2 (where it was introduced!)
Contact with Develop build (334rd in Jenkins) 11th of April -> sends a message in 1-1 / public chat to contact with Develop build (333th in Jenkins) crashes the app. 

#### Logs

Logs from the app version where: https://app.testfairy.com/projects/4803622-status/builds/8073247/sessions/55/?accessToken=nwc/OwkJyzsNa1IQcYJyB-viKb4
It's visible that after 01:20 (the time when message was sent to this contact) - memory performance starts to grow pretty much which ends up at some point on stopping the app.

**Comment by lukaszfryc** [comment]
I believe this was fixed by #3658. @yevh-berdnyk is that correct?

**Comment by yevh-berdnyk** [comment]
@lukaszfryc yes, fixed in the build [#12](https://jenkins.status.im/job/status-react/job/release/job/release%252F0.9.17/12/) so closing the issue
