### ISSUE TITLE
Hide sensitive data fields (passwords, seed phrase words) in TestFairy

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3876]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
In the following cases fields with sensitive data should be not visible in the TestFairy video:

On Android: 
1. When user confirms requested words from seed phrase, they should be hidden (Step 2 and 3)
(see on 00:43) https://app.testfairy.com/projects/4803622-status/builds/8101280/sessions/44/?accessToken=F5S4lagpWttVdDTbW6lrKY5hmss 

On iOS:
1. When account is created, password field on screens to enter and to confirm password should be hidden
2. When user confirms requested words from seed phrase, they should be hidden
https://app.testfairy.com/projects/4803590-status/builds/8112310/sessions/12/?accessToken=sjjlm6BzJwjorBeKojPlAkystK4
3. Sometimes seed phrase is visible for a short time (on 00:23) https://app.testfairy.com/projects/4803590-status/builds/8112310/sessions/13/?accessToken=5l/2ZZUIyRUwgOp8jugVa4iDjFI
4. When entering password to sign transaction https://app.testfairy.com/projects/4803590-status/builds/8112310/sessions/16/?accessToken=3XzWpaZUDMyc32DccsHqIDSi160 (on 00:17)

How to do this: https://docs.testfairy.com/Security/Hiding_Sensitive_Data.html
Also see https://github.com/status-im/status-react/issues/3593 where similar task was done for seed phrase

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly apr 16
* Operating System: Android and iOS

**Comment by dmitryn** [comment]
- [x] Android 1, iOS 2:  Fixed
- [x] iOS 1,4:  Having conversation with TF support team on why inputs with `secureTextEntry=true` attribute is not hidden anymore on iOS.
- [x] iOS 3: https://github.com/testfairy/react-native-testfairy/issues/18 Getting in touch with TF support on why this doesn't work as expected.

**Comment by dmitryn** [comment]
Update from TF support regarding `secureTextEntry`:
>So regarding the iOS side of things, this was indeed a bug on our end. I've since patch the offending code, and will cut a release at the end of the week. In the interim, the only work around is to manually add the view to your list of hidden views with hideView

**Comment by dmitryn** [comment]
Update on issue where `hideView()` doesn't work on Android:
https://github.com/testfairy/react-native-testfairy/blob/master/android/src/main/java/com/testfairy/react/TestFairyModule.java#L223
needs to be changed to `TestFairy.hideView(tag);`

We need to wait for updated TF version or use our own fork. Have asked about that from TF support.

<blockquote><img src="https://avatars0.githubusercontent.com/u/6095613?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/testfairy/react-native-testfairy">testfairy/react-native-testfairy</a></strong></div><div>react-native-testfairy - React Native component for TestFairy SDK</div></blockquote>
