### ISSUE TITLE
Top blue area in the Wallet takes too much space

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3878]
### Description

*Type*: Bug

*Summary*: Blue area takes too much space on Wallet screen on large screens (iPhone 7 plus and Google Pixel XL)
iOS:

![ios](https://user-images.githubusercontent.com/6584810/38798527-844e45ac-416a-11e8-91e8-a9caff59071e.jpg)

Android:
![android](https://user-images.githubusercontent.com/6584810/38798535-8976304e-416a-11e8-9f65-0445ca6af271.png)

#### Expected behavior

<img width="1251" alt="screen shot 2018-04-16 at 11 14 10" src="https://user-images.githubusercontent.com/6584810/38797640-d0e6575e-4167-11e8-8476-5f8a9ec2a11a.png">

### Reproduction

- Open Status
- Open Wallet
- Check how much space is used by blue area with Send Transaction , Receive Transaction and Transaction History buttons

### Additional Information
* Status version: nightly build Apr 14
* Operating System: Android and iOS, real iPhone 7 plus and Google Pixel XL

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0xc22be836cc4f9b9b0d9f9bfe0700f36bd5d9d671](https://etherscan.io/address/0xc22be836cc4f9b9b0d9f9bfe0700f36bd5d9d671)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
