### ISSUE TITLE
Profile image captured sideways?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#388]
What determines the orientation of the photo? on Android 6.0.1 , Galaxy S7 Edge it appears to come in sideways...

also "Profile Image" text in header is not centered

![2016-10-25 22_55_41](https://cloud.githubusercontent.com/assets/2714786/19691307/5e6cd666-9b06-11e6-965e-84bc10f9ab5c.gif)

**Comment by rasom** [comment]
https://github.com/status-im/status-react/issues/186

**Comment by jarradh** [comment]
ahh
