### ISSUE TITLE
Don't allow group chat admin to leave it 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3880]
### User Story

As a user, I want to have an ability to completely disable communication in group chats created by me

### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Group chat admin after leaving the chat still receives new messages in it

#### Expected behavior
Group chat is disabled and it's not possible to send new messages by it's members after admin left

#### Actual behavior
User A (group chat admin) receives new message after leaving it

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on 2 devices
- Create 2 accounts 
- As user A add user B as a contact
- As user A create a group chat with user B as a member
- As user A (group chat admin) leave the group chat (Chat options -> Leave group chat -> Leave)
- As user B send a message to the group chat

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- Change 'Leave group chat' option for something like 'Disable group chat' for it's admin
- Make further communications impossible in a group chat after its admin disabled it

### Additional Information

* Status version: will be in develop after #3842 is merged
* Operating System: Android and iOS

**Comment by yevh-berdnyk** [comment]
@denis-sharypin please review

**Comment by denis-sharypin** [comment]
@yevh-berdnyk  good catch, thanks!

`Leave group` in the chat profile for admin should trigger the Expected behavior.  To make it more clear we should adapt copy in the following `alert message`. 
Now we have: `Are you sure you want to leave this group? `
Should be:  `Are you sure you want to leave this group? This group will be deleted and nobody won't receive any new messages`
What do you think? How does this sound?

**Comment by yevh-berdnyk** [comment]
@denis-sharypin it's a good message for alert but I'd rename also the button to be something more obvious initially like disable, cancel or archive the group.
And I think we should not delete the chat and message history in it for group members for being able to access some information etc.

**Comment by denis-sharypin** [comment]
No group chats anymore
