### ISSUE TITLE
Web3 commands are links instead of text in Console chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3881]
### Description

*Type*: Bug

*Summary*:  web3 commands are treated as links which is not correct since they are not links :)

#### Expected behavior
web3 commands are not clickable when being sent to console chat

#### Actual behavior

web3 commands are shown as links

![image](https://user-images.githubusercontent.com/28752642/38807576-b914e1a4-4185-11e8-80b7-5a4b31728a60.png)

### Reproduction
- Open Status
- Enable Console chat in Profile
- Switch to Ropsten
- Send web3.eth.blocknumber command in console chat

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd78c435258d4af5b7ea6163ed1f68845f44124e181628bffa4f328b311c75fe6](https://etherscan.io/tx/0xd78c435258d4af5b7ea6163ed1f68845f44124e181628bffa4f328b311c75fe6)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1571a58334de465178c5c2c970e82831e05b68fd28bf96deef24934efcbd1ec2](https://etherscan.io/tx/0x1571a58334de465178c5c2c970e82831e05b68fd28bf96deef24934efcbd1ec2)

**Comment by annadanchenko** [comment]
useful? https://github.com/status-im/status-react/issues/1206#issuecomment-346031231

**Comment by jeluard** [comment]
This issue will be addressed by making changes to the type of message used to send web3 commands.

**Comment by pablanopete** [comment]
@jeluard is this issue no longer relevant? Looking to revoke the bounty if so.

**Comment by jeluard** [comment]
@pablanopete Not relevant anymore indeed.
