### ISSUE TITLE
Add Web3 to commands list and update empty console copy

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3883]
### Description

*Type*: Bug

*Summary*: when interacting with Console i want to have `Web3` commands under my hand using `/` or tapping the command button 

#### Expected behavior

1. i do see `web3` suggestion when typing `/` symbol in console chat along with /faucet and /debug
2. i do see `web3` suggestion when tapping commands button in console chat along with /faucet and /debug
3. empty console placeholder is updated:
`Look under the hood! Console is a javascript runtime environment that exposes the whole web3 API. Use "web3." to get started.`

4. when typing web3 command manually it still should work fine

#### Actual behavior
In order to call any web3 command, i need to type it manually 

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb4336c712efd86de2aaac71ca021ad6885d17160701e43f220e6493a0651529c](https://etherscan.io/tx/0xb4336c712efd86de2aaac71ca021ad6885d17160701e43f220e6493a0651529c)
