### ISSUE TITLE
Wrong response order for /debug command

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3884]
### Description

*Type*: Bug

*Summary*: the response for /debug command is shown upper than the command call which is incorrect in terms of chat behavior 

#### Expected behavior

/debug command response is shown after the /debug command call

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/38810194-acbf9a62-418e-11e8-9d6f-1a9f8128931a.png)

### Reproduction

- Open Status
- Enable Console in Profile
- Go to Console chat and call `/debug` command
- Pay attention to the order of response

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x891f0976431aa2f7e72ef96430d7c5e4c12078498e6d7f97c1b4a6d04f0e7185](https://etherscan.io/tx/0x891f0976431aa2f7e72ef96430d7c5e4c12078498e6d7f97c1b4a6d04f0e7185)

**Comment by jeluard** [comment]
@asemiankevich External bots will be disabled for now as this feature is currently broken and introduces security risks.

**Comment by asemiankevich** [comment]
@jeluard got it, thanks

**Comment by debragail** [comment]
Is this still a bounty?

**Comment by jeluard** [comment]
@debragail It is not as we are disabling external bot feature. Sorry for the confusion.

If you are interested with this you can take a look at this bounty https://github.com/status-im/status-react/issues/3813
