### ISSUE TITLE
Console navigation bar text is not centered

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3885]
### Description

*Type*: Bug

*Summary*: Header is not centered in last nightly

#### Expected behavior
Console header is centered

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/38810432-679c605e-418f-11e8-8082-fe31774ed32f.png)

### Reproduction
- Open Status
- Enable Console in Profile
- Open Console chat

### Additional Information
* Status version: nightly
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xfd3b36711b0fcfaaf68067738bbfa4e662ef511b5852cf20a02f5827245b261a](https://etherscan.io/tx/0xfd3b36711b0fcfaaf68067738bbfa4e662ef511b5852cf20a02f5827245b261a)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x67a80209101048d980666c47f8a7cb40b9a70a51](https://etherscan.io/address/0x67a80209101048d980666c47f8a7cb40b9a70a51)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
