### ISSUE TITLE
Removed member in the group chat can see it in Home and can write messages that will be received by the group members

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3891]
### Description

*Type*: Bug

*Summary*:  User who is removed from group chat can
1. See the group chat in Home tab
2. Write messages to the group chat and these messages will be visible to the other group members

#### Expected behavior
After user is removed from the group chat:
1. User gets the message that he was removed
2. If user writes any messages after he was removed then these messages are not sent to the group chat, so other members do not see messages from the removed member
3. Group chat should be listed in the Home tab. All previous messages should be still visible. Last message would be "You was removed by user X". If user relaunches the app this group chat is still present (until user will delete it)

#### Actual behavior
After being removed user can write messages to the group chat and other members will see these messages

### Reproduction

- Open Status
- Create new group chat with users A and B
- each user can write some message to see that everyone can get it
- remove user A from chat. Check if there is any message from "system" to inform user A that he was removed from chat. Check if there is message for all other users to inform that user A was removed
- as user A: write new message to the group chat. As other users check if you can see new message
- as other users: write new message to the group chat. Check that user A does not see new messages

### Additional Information
* Status version: nightly build Feb 17
* Operating System: Android and iOS

**Comment by janherich** [comment]
Group chats are currently disabled and being completely reworked, closing for now
