### ISSUE TITLE
Group chat that user has left is shown again after app is relaunched and new messages are recieved

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3893]
### Description

*Type*: Bug

*Summary*: Group chat that user has left is shown after app is relaunched. In addition, if new message is sent by other participants then user can see all previous conversation and new messages. 

#### Expected behavior
When user left the chat then he does not want to receive new messages, so 

#### Actual behavior
After app is relaunched the chat is shown again (without any messages). When new message is sent to the chat then user can see both old and new messages
### Reproduction
00:13 group chat that user has left is shown again https://app.testfairy.com/projects/4803622-status/builds/8118108/sessions/20/?accessToken=fHoxA46UmZRqkuIsOUMS4Q1HB6g
- Open Status
- Create group chat "leave me" with user A and B
- send several messages to the chat to see everyone can get them
- as user A: Leave group chat (being in chat tap 3 dots in the top right corner to open menu)
- as user A: close app and launch it again
- As user A: wait on Home tab for ~30 seconds and check if the chat "leave me" will appear

### Additional Information
* Status version: nightly build Apr 17
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8118108/sessions/20/?accessToken=fHoxA46UmZRqkuIsOUMS4Q1HB6g">TestFairy: Status 0.9.16-9-g3c43a622+ (2436) @20</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
I reproduced it in a dogfooding session today. Group chat reappeared after logging in again. Also, a user that left is still visible on the member list: #3977

**Comment by yevh-berdnyk** [comment]
Reproducible also for deleting a chat and after re-login

**Comment by janherich** [comment]
Group chats are currently disabled and being completely reworked, closing for now
