### ISSUE TITLE
Random names instead of user names are shown in public chat if users are not in contacts for each other 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3894]
### Description

*Type*: Bug

*Summary*: Despite https://github.com/status-im/status-react/pull/3128 there are random "3 words" names in public chats shown if users are not in contacts for each other
![87884](https://user-images.githubusercontent.com/6584810/38856707-d9fb4480-422f-11e8-8b84-1d8927dde418.jpg)

#### Expected behavior
User name that was set by the user when account was created is shown in public chat (as implemented by https://github.com/status-im/status-react/pull/3128)
#### Actual behavior
 random "3 words" names in public chats shown if users are not in contacts for each other
### Reproduction

- Open Status
- Join public chat "abc" as user A and user B (they should be not in contacts for each other)
- both users write text message in the public chat. check how user A see the username of the user B in public chat

### Additional Information
* Status version: nightly build Apr 17
* Operating System: Android and iOS

**Comment by lukaszfryc** [comment]
This should be fixed together with https://github.com/status-im/status-react/issues/3579
