### ISSUE TITLE
Old messages appear for contact in a public chat if he joins this chat very first time

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3898]
***Type***: Bug

***Summary***: When new contact joins a public chat, then messages which were sent before this contact joined are pulled. So at the moment if I create a very new account and join #status public chat - I see previous messages sent in this chat by other contacts. 

Contact should see the message history in public chat **only** since the time he joins the chat. 

#### Expected behavior
No historic messages appear for very new joiners in public chat

#### Actual behavior
Old messages appear for contact in a public chat if he joins this chat very first time

### Reproduction
- Open Status
- Create new account
- Join #status public chat

### Additional Information
* Status version: Nightly develop 343rd jenkins build (3c43a622)
* Operating System: Android and iOS

#### Logs

TF session (from 01:00) https://app.testfairy.com/projects/4803622-status/builds/8118108/sessions/60/?accessToken=PvWJTnLT/W0rXnGMyouh5C0UmMs

**Comment by lukaszfryc** [comment]
This is actually by desing. https://status-im.slack.com/archives/C9B1T4B9B/p1525950103000250

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/C9B1T4B9B/p1525950103000250">Slack</a></strong></div></blockquote>
