### ISSUE TITLE
While adding members to group chat don't display dapp list.

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3900]
### User Story

As a user, I want to add only users (not dapps) to a group chat.

### Description

*Type*: Bug

#### Expected behavior
![artboard](https://user-images.githubusercontent.com/6559881/38874196-d555fdda-4257-11e8-9f31-7046d445d85f.png)

#### Actual behavior
![img_4544](https://user-images.githubusercontent.com/6559881/38871791-132367a2-4252-11e8-84a2-7191986746c2.PNG)

### Reproduction
- Open Status
- Create a group chat
- Add members to this chat from the chat profile

### Solution
*Summary*: 
- delete dapps from this list

### Additional Information
* Status version:  nightly 17.04.18
* Operating System: Android|iOS

**Comment by lukaszfryc** [comment]
Looks like a regression. I think we've already fixed it some time ago.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x845b3bce53a6daa45579eaf51fc3fe28d5d14cb5c7094879e2c9d31f8c3c77cd](https://etherscan.io/tx/0x845b3bce53a6daa45579eaf51fc3fe28d5d14cb5c7094879e2c9d31f8c3c77cd)

**Comment by janherich** [comment]
Group chats are currently disabled and being completely reworked, closing for now
