### ISSUE TITLE
Back button should not redirect to sign in screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3903]
### Description
*Type*: Bug

*Summary*: When user logs in and presses device back button she is being redirected to sign in screen. Instead, the app should go into the background. 

#### Expected behavior
When device back button is pressed, instead of going to sign in screen the app should go into background.

#### Actual behavior
When back button is pressed in home screen, user is redirected to sign screen. When she tries to log in again, the app crashes. 

### Reproduction
- Open Status
- Sign in and wait for the home screen to appear
- Press device back button

### Additional Information
* Status version: nightly, April 17
* Operating System: Android

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 680.00
Contract address: [0x5a0c6c00850454f946646accf9b053755638daa1](https://etherscan.io/address/0x5a0c6c00850454f946646accf9b053755638daa1)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
