### ISSUE TITLE
Replace accounts/accounts by account/account in app-db

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3907]
### User Story

As a developper I want to share the minimal amount of informations between accounts and I don't need other accounts infos when the user is logged in.

### Description

*Type*: Bug

- move all informations that are not necessary to login from the base realm to account specific realm
- remove accounts/accounts and accounts/current-account-id from app-db, replace by account/account when user is logged in (logged out can have dedicated key)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1370.00
Contract address: [0x073506bbe2061cf5538f603dc38d8181f8905b9a](https://etherscan.io/address/0x073506bbe2061cf5538f603dc38d8181f8905b9a)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
