### ISSUE TITLE
Add Wallet Icon & Missing Request Icons

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#391]
The follow icons and their 'cutout' counterparts (on requests) need to be added
- [x] Wallet DApp icon https://zpl.io/2cvab9
- [x] Phone & Send/Request command icons https://zpl.io/Z1fimyJ

**Comment by jarradh** [comment]
i also noticed icons are missing from command/request list?

**Comment by rasom** [comment]
oops, yes, will fix this too

**Comment by rasom** [comment]
Just checked again and seems that there are no icons in commands list in design https://zpl.io/Z1N94uY, so this is implemented exactly as in design

**Comment by jarradh** [comment]
its a fault in design, please add
