### ISSUE TITLE
Remove non-upstream networks: "Mainnet", "Rinkeby" and "Ropsten" from the network list

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3910]
### Description

*Type*: Bug

*Summary*:  For Beta scope: remove options "Mainnet", "Rinkeby" and "Ropsten" from the network list. It does not do anything (no syncing too , so only networks with upstream RPC make sense now.

#### Expected behavior
Networks list in user Profile (Advanced) contains no options "Mainnet", "Rinkeby" and "Ropsten"
Default selected network: Mainnet with upstream RPC

### Reproduction

- Open Status
- Open Profile
- Tap Advanced
- Check if there is option "Mainnet" (or "Rinkeby" or  "Ropsten") in the networks list

### Additional Information
* Status version: nightly build Apr 17
* Operating System: Android and iOS

**Comment by rachelhamlin** [comment]
We are showing testnets with RPC for developer mode, right?

**Comment by annadanchenko** [comment]
yes, @rachelhamlin
