### ISSUE TITLE
Asset value does not fit the field

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3911]
### Description

*Type*: Bug

*Summary*: Value in the Asset field goes over the field edge
Wallet -> Send Transaction -> Asset field
![36463](https://user-images.githubusercontent.com/6584810/38924129-c4924604-4304-11e8-8bef-cbbb5f45c268.jpg)

#### Expected behavior
Value fits the field:
1. Do not show "full token title" e.g. Status Network Token, but show only abbreviation, e.g. SNT. 
2. Also, if amount does not fit the field then show first 5 digits and "..." at the end. If amount fits the field then show full amount.

It can be done by making field 2 lines instead of 1 when it can't fit the text or showing "..." at the end of the value if it does not fit but user should see most of the amount

### Reproduction

- Open Status
- Get some tokens in the Wallet with long name , e.g. Status Network Token SNT and some long value e.g. 10.12345678901234567
- Open Wallet -> Send Transaction -> Asset field and check how value in the Asset field is shown

### Additional Information
* Status version: nightly build Apr 17
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
@denis-sharypin please specify the expected result, I can see several options but for bounties we need exact one

**Comment by annadanchenko** [comment]
agreed to not show "full token title" e.g. Status Network Token, but show only abbreviation, e.g. SNT. Also, if amount does not fit the field then show first 5 digits and "..." at the end

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 340.00
Contract address: [0xf93292007279108e28c4eec3b018954775d3c767](https://etherscan.io/address/0xf93292007279108e28c4eec3b018954775d3c767)
Network: Mainnet
Paid to: goranjovic
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by churik** [comment]
The same for fields Transaction Fee ("Wallet" screen), "Total fee" ("Transaction fee" screen) if you specify amount with 9 decimals (it is valid value, i.e. 11.000000002)
![image](https://user-images.githubusercontent.com/4557972/40620986-a084e168-62a3-11e8-8589-4bbb75df9a24.png)

**Comment by denis-sharypin** [comment]
@annadanchenko Let's use this layout. For issues with gas prices, pls create a separate issue. It requers a bit different fix 
<img width="516" alt="screenshot 2018-08-03 14 08 30" src="https://user-images.githubusercontent.com/6559881/43644488-c52ce0b2-9726-11e8-85ae-af984a1c73fd.png">
