### ISSUE TITLE
Typing comma separator in Gas limit or Gas price fields removes entered value and sets default one

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3912]
### Description

*Type*: Bug

*Summary*: In Transaction fee screen, Gas limit or Gas price fields: value typed after comma separator is removed and default value is set.  

#### Expected behavior

User can use comma or dot separators in  Gas limit and Gas price fields. The value entered by user is shown and used.

#### Actual behavior
If default value is deleted and then new value is typed then as soon as comma is typed the content of the field shows default value instead of the one that is being typed. Can reproduce in Gas limit and Gas price fields
### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/8118108/sessions/87/?accessToken=knVv6jwEFt/A2tkOEgfGEFroy-c
- Open Status
- Open Wallet
- Tap Send Transaction
- Tap Advanced
- Tap on the field Transaction Fee
- Delete content inside field Gas limit. As a result, field shows hint 0.000
- Type 123,5 in the field. Check what is shown in the field after you typed ","
- Delete content inside Gas price field. As a result, field shows "0"
- Start typing 87,12 in Gas price field. Check what is shown in the field after you typed ","

### Additional Information
* Status version: nightly build Apr 17
* Operating System: Android and iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 340.00
Contract address: [0x71dfb4ccf7848e19549adeef569e2ad46e24221c](https://etherscan.io/address/0x71dfb4ccf7848e19549adeef569e2ad46e24221c)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
