### ISSUE TITLE
Update `enter your full name` placeholder

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3915]
### Description

*Type*: Bug

*Summary*: we are using `enter your full name` placeholder when creating account now and it sounds a bit weird to me personally like why do i need my full name there? Some design input it required there @denis-sharypin @andmironov @hesterbruikman 

#### Expected behavior
Copy is updated, for ex `Choose your name` or `Display name`. Should be confirmed with design team

#### Actual behavior
`enter your full name` placeholder when creating account 

### Reproduction

- Open Status
- Create account

### Additional Information
* Status version: develop
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x17826313121d386951df9361aea10364a6fbac7a4b9482d3a44da242ae5c651e](https://etherscan.io/tx/0x17826313121d386951df9361aea10364a6fbac7a4b9482d3a44da242ae5c651e)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 375.00
Contract address: [0x35951c9459c0f541c3138e8edc519ed10e9b13b1](https://etherscan.io/address/0x35951c9459c0f541c3138e8edc519ed10e9b13b1)
Network: Mainnet
Paid to: debragail
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
