### ISSUE TITLE
Automated tests (Transacting) should be created/reworked according to nightly build regression test suite

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3920]
### User Story

As a test engineer, I want next scenarios related to Transactions (as part of the [regression test suite](https://ethstatus.testrail.net/index.php?/suites/view/42&group_by=cases:section_id&group_order=asc&group_id=663)) to be covered by automated test scripts

### Description

* Create separate test script for the next test scenarios:

- [x] C3422 | View Tx history for recovered acc. Can copy tx hash from tx history. Can open transaction on etherscan io.

- [x] C3425 | Check: Wallet error handling. Sign in Tx with incorrect pass. Sign in Tx with amount >= have, enter wrong address code when Send tx.

* Leave a comment on each test script with the test ID and short description of what does the test do

**Comment by antdanchenko** [comment]
@Serhy and @lukaszfryc each case from the task is already covered by actual tests which are running against a PR, please review those tests one more time

**Comment by Serhy** [comment]
Reviewed and updated the scope in the description. C3422 and C3425 should be added in the scope of this issue.
