### ISSUE TITLE
Align avatar, name and status in top toolbar to the left (1x1, group and public)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3921]
### Description

*Type*: Bug

*Summary*: in mocks we have avatar, name and status shown in title of the chat  for 1x1 , group and  public chats. 

#### Expected behavior

1. For 1 x 1 chat: avatar should be aligned as in mocks (to the left of the chat name), next to the avatar there is also username and status (Unknown, Online, etc). Currently, avatar is shown but it's a bit misplaced and username is not shown next to it, there is too much empty space. Mocks to implement:

![image](https://user-images.githubusercontent.com/28752642/38934011-4506de1c-4323-11e8-82c0-e68939d4f172.png)

2. for group chat: show avatar, chat name and number of members as in mocks below. Currently, avatar is not shown at all and chat name is shown in the center instead of being aligned to the left. Mocks to implement:

![image](https://user-images.githubusercontent.com/28752642/38934034-52548de4-4323-11e8-9f20-4cf477cb5908.png)

3. for public chat: add avatar for public chat and its name, same as for group chat. Mocks to implement:

![image](https://user-images.githubusercontent.com/28752642/38934055-63062f12-4323-11e8-9802-3e0e8c985b40.png)

4. Check that unread counter fits ok when displayed for 1:1, group and public chats (blue circle with number of unread messages)

Check mocks here https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5a66f94aba218e7607157afa

#### Actual behavior
No avatar is shown for none of chats

### Reproduction
- Open Status
- Start 1x1 chat
- Start group chat
- Join public chat

### Additional Information
* Status version: develop
* Operating System: Android|iOS

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 650.00
Contract address: [0x5f0219af85883c59e83ec7ac0653f0fc8df6aaf1](https://etherscan.io/address/0x5f0219af85883c59e83ec7ac0653f0fc8df6aaf1)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
