### ISSUE TITLE
Add (rework) notification for user when being added to 1x1 or group chat 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3923]
### Description

*Type*: Bug

*Summary*: As a user I want to be notified when I am added to group chat or someone has added me to contacts (but did not send anything yet)

#### Expected behavior

I want to be notified in both cases. Some design should be done there, @denis-sharypin please assist :)

#### Actual behavior

1. When someone scanned my contact code - new chat is created on my device on Home tab, but I am not notified about it (no new badge is shown or any other notification received)

2. When someone has added me to group chat - new chat is created on my device on Home tab, but I am not notified about it (no new badge is shown or any other notification received)

![image](https://user-images.githubusercontent.com/28752642/38934556-c130892e-4324-11e8-94f8-9f678bf27ed0.png)

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by denis-sharypin** [comment]
@asemiankevich Good catch! We show notification badge with a number on the home icon in the tabbar (as you have it on the profile icon on your screenshot ) We could use show with cases that you have mentioned

**Comment by lukaszfryc** [comment]
@denis-sharypin I think it's a good idea. Btw, does the unknown contact indicator clear for a user #3734 ?
