### ISSUE TITLE
Automated tests (Chats management) should be created/reworked according to nightly build regression test suite

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3924]
### User Story

As a test engineer, I want next scenarios related to Chats management (as part of the [regression test suite](https://ethstatus.testrail.net/index.php?/suites/view/42&group_by=cases:section_id&group_order=asc&group_id=663)) to be covered by automated test scripts

### Description

* Create separate test script for the test scenarios:

- [x] C3412 | Delete 1-1 chat via 'Delete chat' option. 1-1 chat should be with the text, /request, /send messages from both sides. Re-login and check there is no chat. Start 1-1 chat again from list of Contacts

- [x] C3413 | Delete 1-1 chat via 'Swipe-to-delete' option  
- [ ] C3414 | Clear history of the Group Chat. 2 members. Exchanged with the text messages. Re-login -> no history there
- [ ] C3415 | Delete Group Chat via 'Delete chat' option. 2 members. Re-login -> no chat. Sender sends a message -> Group chat appears
- [ ] C3416 | Leave group chat. 2 members. Sender sends message -> nothing received. Re-login -> no chat 
- [ ] C3400 | Group chat. 3 contacts. Admin removes 1 contact. Check 'Group Info' screen of each member
- [ ] C3417 | Group chat. 2 contacts. Admin adds one more contact. Everyone exchange messages fine
- [x] C3418 | Delete Group chat via 'Swipe-to-delete' option. Re-login -> no chat present.
- [x] C3419 | Public chat. Clear history + Delete chat + Leave public chat. 2 contacts.

* Leave a comment on each test script with the test ID (from testrail) and short description of what does the test do

**Comment by asemiankevich** [comment]
Gonna work on C3413 | Delete 1-1 chat via 'Swipe-to-delete' option  and C3418 | Delete Group chat via 'Swipe-to-delete' option. Re-login -> no chat present for now

**Comment by lukaszfryc** [comment]
I'll take rest of them 😁

**Comment by yevh-berdnyk** [comment]
Remaining tests will be added after group chats enabling
