### ISSUE TITLE
Sort Assets in alphabetical order on Wallet -> Manage Assets screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3926]
### Description

*Type*: Feature

*Summary*: Sort assets in alphabetical order

#### Expected behavior
i can look up for assets quickly as they are sorted in aplhabetical order

#### Actual behavior
no sorting

<img width="224" alt="screen shot 2018-04-25 at 1 49 19 pm" src="https://user-images.githubusercontent.com/116099/39243980-7b712464-488f-11e8-8050-98ed6dd75e99.png">

### Reproduction

- Open Status
- Go to Wallet - Manage assets

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by chadyj** [comment]
Sorting by alphabetical order is enough for now to let users easily find tokens.
Achieves the same goal with a fraction of the work :-) 

Want to update the issue?

**Comment by asemiankevich** [comment]
@chadyj just to clarify - i asked for search on Wallet - Manage assets screen (not on the main wallet screen). If you feel that it is overkill - well i won't be fighting for it :)

**Comment by chadyj** [comment]
Ah yes sorry I was thinking of the manage asset screen. That screen really needs sorting!

How many assets do you have in your wallet that you need search to find them?

**Comment by asemiankevich** [comment]
@chadyj on Mainnet we have ~100 and we have now about 5-6 under Ropsten, but Ropsten is not in focus for this issue, since it was originally logged when i was surfing the app under Mainnet

**Comment by chadyj** [comment]
Oh so it seems we are talking about the same thing :)
Alphabetical sort is great for now to get users finding tokens without the need for UX and more work

**Comment by asemiankevich** [comment]
@chadyj updated and put a bounty for it

**Comment by denis-sharypin** [comment]
Shall we keep our token and ETH on the top of the list without respect of sorting?

**Comment by chadyj** [comment]
> Shall we keep our token and ETH on the top of the list without respect of sorting?
Wrong screen. 
The manage list only has tokens. I added a screen to the issue for clarity.

**Comment by goranjovic** [comment]
But a good question regarding the main Wallet screen

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x2ab98fe9cd1907ad1d9884831d8eb2429fe0c3c447546b62f85642d6af5751b5](https://etherscan.io/tx/0x2ab98fe9cd1907ad1d9884831d8eb2429fe0c3c447546b62f85642d6af5751b5)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 350.00
Contract address: [0xc8982372bf605ca38a7e880f0345be912d29de2c](https://etherscan.io/address/0xc8982372bf605ca38a7e880f0345be912d29de2c)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
