### ISSUE TITLE
Update timestamps according to latest designs 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3927]
### Description

*Type*: Bug

*Summary*: Update timestamps due to newest mocks 

#### Expected behavior

![image](https://user-images.githubusercontent.com/28752642/38945324-dfb1d2a8-433e-11e8-9ff4-f21cee8f45bd.png)

#### Actual behavior
timestamps are out of the message bubbles

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by denis-sharypin** [comment]
@nikitalukianov  please add design specs here

**Comment by nikitalukianov** [comment]
here is mockups in zeplin: https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/dashboard?seid=5ad5db84c95888398402eb0d

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by lukaszfryc** [comment]
@nikitalukianov no chat bubbles for emoji #3818 has been implemented recently. Where should we put the timespan and username for this kind of message? Could you add this as an example to Zeplin?

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 750.00
Contract address: [0x12b487d7e2e003c0a48c45e9ecbe603545bbcd89](https://etherscan.io/address/0x12b487d7e2e003c0a48c45e9ecbe603545bbcd89)
Network: Mainnet
Paid to: cammellos
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
