### ISSUE TITLE
Geth not detected?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#393]
it's possible to close application and reopen it and tap on the password message and have this error appear. having difficulties reproducing
![ohhh](https://cloud.githubusercontent.com/assets/2714786/19828400/52aea022-9df7-11e6-9470-606f411be81e.png)

**Comment by jarradh** [comment]
i can reliably reproduce this;
- build release
- open application, close it
- forget about phone for awhile (i assume until android kills service)
- open application, tap password message
```
$ adb forward tcp:8545 tcp:8545
$ build/bin/geth attach http://localhost:8545                                                                                                                      
Fatal: Unable to initialize console - Post http://localhost:8545: EOF
```

**Comment by rasom** [comment]
I tested this on the real device, it works fine after 5/10/30 minutes. Can not reproduce

**Comment by jarradh** [comment]
i'll try come up with more repeatable steps to reproduce

**Comment by rasom** [comment]
```
if we can [restart node] - maybe have console send a message saying "Hmm Geth is not available, one moment - restarting it"
```

**Comment by jarradh** [comment]
same as #652
