### ISSUE TITLE
Chat: Update empty state for active public chats

### ISSUE THREAD

**Issue by heyhaigh** [status-im/status-react#3930]
### User Story

As a user, I want to have a clearer indication that a public chat is active so that I am more likely to engage with the channel and don't close the chat thread.

### Description

*Type*: Feature

*Summary*:
As a new user, I need a visual indication that a public chat has been utilized (and is still utilized) upon my initially entering the chat room. Without a message indicating that the chat thread is currently active, the likelihood of a user bouncing off of the thread is higher.

#### Expected behavior
I'd expect to see a general message prompting each new user to "Take a moment to say hello" and wait for a response + a status indicting the last time a user posted a message (e.g. _userA commented 5 mins ago_).

![Expected first time user experience](https://i.imgur.com/AVw3faa.jpg)

#### Actual behavior
See photo below for _existing first time user experience_...

![Existing first time user experience](https://i.imgur.com/lwrx8eU.jpg)

### Reproduction
• Sign up for a Testflight account (iOS)
• Create a new account
• Select the "+" affordance
• Join a public chat thread, such as #status

### Solution 1.0

*Summary*: 

- [ ] Create an introduction message for first time users
- [ ] Provide a status of the last user comment (e.g. _userA commented 5 mins ago_)

### Solution 1.1

*Summary*: 
- [ ] Create an introduction message for first time users
- [ ] Provide a status of the last user comment (e.g. _userA commented 5 mins ago_)
- [ ] Showcase inbox of previous chat responses within the public thread

### Additional Information
* Status version: 0.9.16 (2283.1)

* Operating System: iOS

**Comment by heyhaigh** [comment]
Emoji included in Expected Behavior screen merely a placeholder. Use of iconography should align with Status aesthetic and guidelines.

**Comment by chadyj** [comment]
cc @andmironov @hesterbruikman. Thoughts?

**Comment by jbostick00** [comment]
I like the idea of the time since last comment. This would also give an indication of how popular the chat is. Maybe instead of time since last post it could be the number of posts to the chat in the last 24 hours.
