### ISSUE TITLE
Sign in: Cannot paste text within password field

### ISSUE THREAD

**Issue by heyhaigh** [status-im/status-react#3931]
### User Story

As a user, I want to copy text from a text editor or password manager so that I can log into my Status account.

### Description

*Type*: Bug

*Summary*: When logging back into the Status iOS alpha, I was prompted to enter my password in order to sign into my account. I use a password manager to manage my passwords and accounts. Upon copying my Status password from the password manager, I tapped+held the password input field in order to paste my password. The paste feature was not available, no matter where I tapped+held my finger, no matter the duration, or the pressure.

#### Expected behavior
[Assumes behavior prior to touch ID integration]
I would expect to be able to switch apps outside of the Status iOS alpha, copy text in another app, and paste that text into the Status app. Additionally, if there were a password manager hyperlink within the password field itself, that would be even more ideal.

#### Actual behavior
[See GIF of current behavior here](https://i.imgur.com/bwlC1Qe.gifv) for interactive bug

### Reproduction
• Open Status app
• Leave Status app and copy text within a third-party app or text edit app
• Toggle 'switch app' via Home Button
• Navigate back to the Status app
• Tap + hold into the 'password' field

### Solution
Create a clear, easy to use tap + hold to paste text interaction. This gesture isn't currently available.

### Additional Information
* Status version: 0.9.16 (2283.1)
* Operating System: iOS

**Comment by dickolsson** [comment]
I'm having the same issue on iOS and Status version 0.9.21 (6123).

When I create the new password I can paste in a password generated by my password manager. This sets the expectation that I would be able to do the same when entering that password for login. But I'm not.

No matter how I try, it's not possible to paste in the password during log-in.

I had to re-create my Status account with a simpler and more insecure password that I could remember/type in order to work around this issue.

I'm sure this is just a miss, since I can't see any particular reason for not being able to paste in the password (it's commonly possible for most/all other apps on my phone).

**Comment by dickolsson** [comment]
One additional thing to note: it's possible to paste the password into the field when you do a transaction. But again, not when you log in. This leads me to think that's really just an oversight with the password field for the login field.

Should probably be labelled as a bug?

**Comment by dickolsson** [comment]
Picking up on more people having issues with this:

https://twitter.com/vietlq/status/1015565874542141441?s=21

https://twitter.com/logonaut/status/1015611164544335875?s=21

**Comment by chadyj** [comment]
Also seeing a few bug reports for this too.

**Comment by rasom** [comment]
hm, i can't reproduce this on iphone X

**Comment by chadyj** [comment]
Thank you @dickolsson and @heyhaigh for the bug report. We are looking into this.

**Comment by annadanchenko** [comment]
Can reproduce issue from https://github.com/status-im/status-react/issues/3931#issuecomment-402523894 on real iPhone 6s, iOS 11.4.1 and real iPhone 5s, iOS 11.4. 
Can't reproduce issue for the same steps (see below) on real iPhone 7 plus, iOS 11.4 step 15 from list below works fine
Used last nightly build from  https://i.diawi.com/6EsmgH (Updated: 2018/07/10 03:36:11 UTC)

Steps:
1. in the Notes app on the iPhone create new note with text `QWERTY`
2. Select all and copy text QWERTY in Note
3. Install and Launch Status app, tap Create account
4. In Password field long tap to get Paste option
5. Tap on Paste. As a result ****** dots are shown in the field
6. tap Next button
7. In Confirm field long tap to get Paste option
8. Tap on Paste. As a result ****** dots are shown in the field
9. tap Next button
10. type some Name in the Name field, e.g. "password" and tap Next button
11. after account is created: Do not share data, Allow notifications
12. switch to Profile and tap Log out
13. Confirm to Log out
14. on the Sign in to Status screen tap on newly created account "password"
15. In Password field long tap to get Paste option - in my case Paste option is not shown
16. Close Status app
17. Run Status app, so Sign in screen is shown with "password" account
18. Long tap on Password field - in my case Paste option is not shown

Note: if I tap on return on device keyboard, so keyboard is not shown and then long tap on Password field then Paste option is shown 



<blockquote><div><strong><a href="https://i.diawi.com/6EsmgH">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
@heyhaigh  @dickolsson fix should be available in the next release 0.9.23

**Comment by dickolsson** [comment]
@annadanchenko Thanks a ton!

**Comment by heyhaigh** [comment]
Wonderful, thanks all! Cc @annadanchenko + @dickolsson
