### ISSUE TITLE
Can't see participants profiles in group chat settings (non-admin)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3934]
### Description

*Type*: Bug

*Summary*: as a group chat participant i want to be able to view others' profiles no matter i am admin or not

#### Expected behavior
group chat member is able to navigate to other participants' profile within tap 3 dots -> group info -> tap member's profile

#### Actual behavior
i am not able to see profile of any other member if i am not an admin of group chat

### Reproduction

- Open Status
- In a group chat (non-admin) tap 3 dots -> group info -> tap member's profile

### Additional Information
* Status version: develop
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 750.00
Contract address: [0xa6eedcc9b8dd4666ca6755d584175a6155a26e9e](https://etherscan.io/address/0xa6eedcc9b8dd4666ca6755d584175a6155a26e9e)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
