### ISSUE TITLE
Ethergoo Doesn't Work

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3935]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to play Ethergoo so that can get Goo.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
Ethergoo doesn't work with Status

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

1. Go to http://ethergoo.io
2. Click Play Now
3. Confirm Transaction

This works in Metamask.

#### Actual behavior
[comment]: # (Describe what actually happened.)

1. Go to http://ethergoo.io
2. Click Play Now
3. Nothing happens

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Dapp http://ethergoo.io
- Click Play Now

<blockquote><div><strong><a href="http://ethergoo.io/">EtherGoo - Crypto Idle Game</a></strong></div><div>Competitive Ethereum Idle Game</div></blockquote>
<blockquote><div><strong><a href="http://ethergoo.io/">EtherGoo - Crypto Idle Game</a></strong></div><div>Competitive Ethereum Idle Game</div></blockquote>
<blockquote><div><strong><a href="http://ethergoo.io/">EtherGoo - Crypto Idle Game</a></strong></div><div>Competitive Ethereum Idle Game</div></blockquote>

**Comment by flexsurfer** [comment]
we need to set `web3.eth.defaultAccount` same problem for https://giveth.github.io/liquidpledging-ui/#contract=0x18658A1A7cB8b0Be97b155D051769b3651b2943c&pageId=pledges&provider=
