### ISSUE TITLE
Show all users in group chat members list

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3938]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see myself in a group chat members list

### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: All users should be listed in a group chat members list including one who is viewing group chat info. If all members except one leave a group chat it can be confusing to see empty members list

<img width="330" alt="aa" src="https://user-images.githubusercontent.com/29711298/39011108-3dbebd40-4419-11e8-9c5f-a5d5c3ae7f1a.png">

#### Expected behavior
User who is viewing a group chat info should see himself in the members list

#### Actual behavior
Neither group chat admin nor other members see themself in the chat members

### Reproduction
- Open Status
- Add a user to contacts
- Create a group chat
- Click Chat options -> Group info

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 750.00
Contract address: [0xa2cb74f03f749ba0248da9001c5eaef6e303ddb2](https://etherscan.io/address/0xa2cb74f03f749ba0248da9001c5eaef6e303ddb2)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
