### ISSUE TITLE
Introducing wallet / signing phrase

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3940]
### User Story

As a user I want to know about signing phrase that I use in transactions.

### Description

*Type*: Feature

*Summary*: Mockups here, bottom line: https://zpl.io/agGv1j1

#### Expected behavior
<img width="860" alt="screenshot 2018-04-20 09 19 34" src="https://user-images.githubusercontent.com/6559881/39035889-0052dfbe-447c-11e8-8d3b-237f09e468d5.png">

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by asemiankevich** [comment]
@denis-sharypin i am confused about `you won't be able to see the whole signing phrase again' because i definitely will when signing transactions . Can we change the copy a bit? Like saying that are you sure you remembered this phrase bla bla :)

**Comment by denis-sharypin** [comment]
@asemiankevich Confirm it with @hesterbruikman please
