### ISSUE TITLE
Introducing wallet / notification not for new user

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3941]
### User Story

As a current user, I want to to have access to signing phrase so that will keep my account safe.

### Description

*Type*: Feature

*Summary*: Mockups here, bottom line: https://zpl.io/agGv1j1

#### Expected behavior
<img width="375" alt="screenshot 2018-04-20 09 33 58" src="https://user-images.githubusercontent.com/6559881/39036626-5b65f0f6-447e-11e8-9ef8-507c325d006c.png">

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by asemiankevich** [comment]
@annadanchenko all issues with `wallet` label are go now to `170-wallet-improvement` swarm, i see it is in onboarding project now, should i move it there?

**Comment by denis-sharypin** [comment]
@asemiankevich it was part of the onboarding swarm in the beginning

**Comment by denis-sharypin** [comment]
@alwx  my apologies, I messed up with the user story here
The actual user story should be: `as a user if I haven't finished backing up my seed phrase and got some money on the wallet I will get this notification.`
