### ISSUE TITLE
Update welcome image on the home tab

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3942]
### User Story

As a user, I want QUALITY images

### Description

*Type*: Bug

*Summary*: Seems like we use @ 1x image for retina devices. Please double check.
Bug report https://status-im.slack.com/archives/C90325XL6/p1524085907000048

#### Expected behavior
Each device size should have their appropriate file size . Please check all images https://github.com/status-im/status-react/tree/develop/resources/images/ui

#### Actual behavior
Retina devices use @ 1x images

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Create account

### Additional Information

* Status version: nightly/release 
[comment]: # (Android or iOS.)
* Operating System: Android|iOS

**Comment by denis-sharypin** [comment]
![welcome-image](https://user-images.githubusercontent.com/6559881/39037388-a0442402-4480-11e8-89cf-e7ecb4239e00.png)
![welcome-image 2x](https://user-images.githubusercontent.com/6559881/39037389-a0726934-4480-11e8-8496-cc91edb6588c.png)
![welcome-image 3x](https://user-images.githubusercontent.com/6559881/39037391-a0a28326-4480-11e8-96fd-46fbe4b48e16.png)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Contract address: [0x6841c84a3896885bd34b5ab6ec66e861c3e781f3](https://etherscan.io/address/0x6841c84a3896885bd34b5ab6ec66e861c3e781f3)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
