### ISSUE TITLE
Improve metrics opt-in screen

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3944]
### User Story

As a user, I want to fully understand the metrics opt-in screen so that I can make an informed decision about.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

A core principle of Status is [Privacy, by default](https://blog.status.im/privacy-by-default-with-ethereum-6b1045afeab2) where "sharing any data at all is completely transparent and optional".  To this end, we want to ensure that users opting-in to share anonymous usage patterns are fully informed, and give explicit consent.

Here is the current UI:
<img width="269" alt="screen shot 2018-04-20 at 10 05 45 am" src="https://user-images.githubusercontent.com/116099/39037971-6ea53ec0-4482-11e8-9f92-4410f7597ac0.png">

#### Expected behavior

When a user creates or restores an account the opt-in screen is well understood, the UX is clear, and the user makes an informed choice.

##### Improved texts: 

— Screen

Header: Help improve Status by sharing usage patterns

Body: We collect anonymous data to understand how Status is used and inform future development. Whilst we appreciate your help to make Status better, this is an optional choice and can be changed at any time.

Link: Learn more about what we collect  [link to: https://wiki.status.im/Help_Improve_Status]

Buttons:  [Share data] [ Do not share]

— Alert
header: Share data with Status?
body: Are you sure you want to share anonymous data with Status?
buttons: [Cancel] [Share]

##### don't forget to replace this screen in the user profile — advanced — Help improve Status?

—  Designs:

Zepplin project: https://zpl.io/blm6BM5

![slice 1](https://user-images.githubusercontent.com/116099/39365100-7e8d49c8-4a30-11e8-8e71-52c116453928.jpg)

**Comment by denis-sharypin** [comment]
![status-privacy](https://user-images.githubusercontent.com/6559881/39367835-302c85b6-4a38-11e8-921f-cfc99fc789fa.png)
![status-privacy 2x](https://user-images.githubusercontent.com/6559881/39367836-305c9c38-4a38-11e8-83bb-fe3bbb4403ac.png)
![status-privacy 3x](https://user-images.githubusercontent.com/6559881/39367838-30908dfe-4a38-11e8-9f86-6925eb8a29f9.png)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1350.00
Contract address: [0x9f08f57fbe4e19522054666129ecf12da7484e5d](https://etherscan.io/address/0x9f08f57fbe4e19522054666129ecf12da7484e5d)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
Hi @chadyj  I have posted an implementation of the changes at https://github.com/status-im/status-react/pull/4098  :beer: :hamburger: 

(Haven't got access to the Zepplin project so some of the numbers on margins etc might need tweaking).

**Comment by chadyj** [comment]
Fantastic @pacamara! Thank you for your contribution!
Can you attach some screenshots to the PR and @denis-sharypin can review, and perhaps see about Zeplin access too.

**Comment by pacamara** [comment]
Cheers @chadyj , you're welcome! Will attach those now.

**Comment by chadyj** [comment]
Also you got 2 birds with one stone! 
Grab https://github.com/status-im/status-react/issues/3539 too as you covered it here.

**Comment by denis-sharypin** [comment]
@pacamara hey, thanks for a contribution. Can you provide your emaik address pleas and I will send you an invite to Zeplin

**Comment by pacamara** [comment]
> Grab #3539 too as you covered it here.

@chadyj Wow total bargain, thanks mate!

@denis-sharypin I already tried registering on Zepplin under the same username as here (pacamara), are you able to add that account please?

**Comment by denis-sharypin** [comment]
@pacamara nope, it doesn’t work. Need your email

**Comment by pacamara** [comment]
@denis-sharypin My email's pacamara.code@gmail.com

**Comment by denis-sharypin** [comment]
@pacamara sent!

**Comment by pacamara** [comment]
@denis-sharypin Got it, thanks! :beers:

**Comment by pacamara** [comment]
@denis-sharypin Could you resend the invite please? I followed it and there's no error, but once I'm logged in Status doesn't show in my list of projects, and there's no obvious option to search for it.

**Comment by denis-sharypin** [comment]
@pacamara done!

**Comment by pacamara** [comment]
@denis-sharypin  Worked that time, thanks!  :beers:
