### ISSUE TITLE
Add empty state for Recipients screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3945]
### Description
*Type*: Bug

*Summary*: There is no empty state for "Recipients" screen.

#### Expected behavior
There is an empty state placeholder that says something like: "There are no recent recipients here yet.".  

Similar to: 

<img src="https://user-images.githubusercontent.com/7532782/39040456-953e97fc-4487-11e8-96f2-0031c687b158.png" width="200">

#### Actual behavior
The screen is empty: 

<img src="https://user-images.githubusercontent.com/7532782/39040384-74ab6aa6-4487-11e8-9362-b25737c5fcc3.png" width="200">

### Reproduction
- Open Status
- Have no contacts

### Additional Information
* Status version: nightly, April 20
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
looks like a partial dupe for https://github.com/status-im/status-react/issues/3918, can we combine them?

**Comment by lukaszfryc** [comment]
Both are related. I'd just reference them as you did.
