### ISSUE TITLE
Improve "oops, error" placeholder in Status browser

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3946]
### Description
*Type*: Feature

*Summary*: The "oops, error" that appears when url could not be reached could be improved. Let's at least improve the text, center it and make it similar to other placeholders we have.   

#### Expected behavior

Let's use placeholder like: _Oops, this site can't be reached. Status could not found the server "wrongservername.com"_ and center it same way as it's done in other screens:

<img src="https://user-images.githubusercontent.com/7532782/39040456-953e97fc-4487-11e8-96f2-0031c687b158.png" width="200">

How Safari does it: 

<img src="https://user-images.githubusercontent.com/7532782/39042002-214cdc20-448a-11e8-832e-97c63652a850.png" width="200">

#### Actual behavior

<img src="https://user-images.githubusercontent.com/7532782/39041494-275a3c30-4489-11e8-8d7e-88b0c0c8a68a.png" width="200">

### Reproduction
- Open Status
- Go to dapp browser (new chat, join public chat) and type a wrong url

### Additional Information
* Status version: nightly, April 20
* Operating System: Android, iOS

**Comment by denis-sharypin** [comment]
<img width="469" alt="screenshot 2018-05-16 11 45 55" src="https://user-images.githubusercontent.com/6559881/40109865-b98d0892-58fe-11e8-9604-13ae1ab267fb.png">

Link to Zeplin https://zpl.io/agnlM1O

cc @jeluard 


<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>
