### ISSUE TITLE
Some messages were lost because of a time drift

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3948]
### Description
*Type*: Bug

*Summary*: Some messages that had been sent to 1-1 and public chat have been lost. From the logs it looks that the clients time has drifted, so they are unable to communicate, so they would need to check that their clocks are synced. (It could also be that the mailserver clock has drifted, but probably less likely, worth checking though).

Based on logs from mailserver it seems they are getting kicked because they have a time drift
```
[31mERROR[0m[04-19|11:04:12] bad envelope received, peer will be disconnected [31mpeer[0m=0a346f9db199cd6b [31merr[0m="envelope created in the future [ad7cd4aced574eb96b218d8204850c0bb51a995e4bc663d44ab3986833e52ed8]"
[31mERROR[0m[04-19|11:04:12] bad envelope received, peer will be disconnected [31mpeer[0m=0a346f9db199cd6b [31merr[0m="envelope created in the future [c3d288ace0ff9d865a81d769ec06f265e2c9049c8ce408363e7296704915344e]"
[31mERROR[0m[04-19|11:04:12] bad envelope received, peer will be disconnected [31mpeer[0m=0a346f9db199cd6b [31merr[0m="envelope created in the future [ee1793d02faf9c68b923f55ee3235528c78b4fe0aa8afd390236175c82b043de]"
```

### Reproduction
- Open Status
- Open public chat
- Try to send some messages

### Additional Information
* Status version: nightly, April 19
* Operating System: Android, iOS

**Comment by oskarth** [comment]
@dshulyak @rasom does this https://github.com/status-im/status-go/pull/864 PR address this issue completely or are there more/different cases?

**Comment by dshulyak** [comment]
I expect it to solve all known cases

**Comment by rasom** [comment]
So we just need to upgrade status-go in status-react in order to check this?

**Comment by pedropombeiro** [comment]
Hi @lukaszfryc. https://github.com/status-im/status-go/pull/864 has been merged for a while now. Can this GHI be moved to Done?

**Comment by lukaszfryc** [comment]
Yes!
