### ISSUE TITLE
Newly added member of a group chat doesn't see the chat

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3950]
### User Story

As a user, I want to be notified that I was added to a group chat so that I can start messaging in it.

### Description

*Type*: Bug

*Summary*: Newly added members of existing group chat doesn't see it and can't send and receive message in it. Old group chat participants doesn't see new members. Only group chat admin receives a message that new user is added

#### Expected behavior
New user receive message about he was added to a group chat and can send messages to it

#### Actual behavior
Newly added user doesn't receive message that he was added to a group chat and don't see the chat on his home tab. Old member of the group chat don't receive a notification about new user is added and don't see him in the chat participants  

### Reproduction

- Open Status on 3 devices and create 3 accounts
- As user A create a group chat with user B
- As user A add user C to the group chat

### Additional Information
* Status version: #350 nightly build
* Operating System: Android, iOS

**Comment by Serhy** [comment]
This one https://github.com/status-im/status-react/issues/3892 is a blocker for now to re-test this issue.

**Comment by janherich** [comment]
Group chats are currently disabled and being completely reworked, closing for now
