### ISSUE TITLE
Convert tokens fails in Bancor DApp because only 1 transaction out of 2 is signed in Status

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3958]
### Description

*Type*: Bug

*Summary*: `Convert tokens` fails in Bancor DApp because it creates 2 transactions but only 1 can be signed by Status. 

Tried 10 times to convert SNT to BNT and other tokens, all attempts failed. In the same time if buy same token for ETH then it works fine (probably, because only one signing request is created when purchasing with ETH)

geth.log if search by `request` (2 signing requests created, only 1 of them is completed):
```
t=2018-04-22T14:20:35+0000 lvl=info msg="signing request is created" package=status-go/sign.PendingRequests   ID=c46b3c4a-aa61-4080-a705-9a88d4c43eb9
t=2018-04-22T14:20:35+0000 lvl=info msg="signing request is created" package=status-go/sign.PendingRequests   ID=67ad4b67-489c-4277-9c40-232ac98a8061
t=2018-04-22T14:20:42+0000 lvl=info msg="complete sign request"  package=status-go/sign.PendingRequests   id=67ad4b67-489c-4277-9c40-232ac98a8061
t=2018-04-22T14:20:43+0000 lvl=info msg="completed sign request " package=status-go/sign.PendingRequests      id=67ad4b67-489c-4277-9c40-232ac98a8061   response="[88 236 132 251 17 172 249 75 129 101 190 135 112 211 171 191 51 166 228 78 28 206 244 68 236 147 50 12 205 187 86 195]" err=nil


```

#### Expected behavior
Both transaction requests can be signed, so user can convert tokens in Bancor DApp

#### Actual behavior
"Oh no" error is shown in the DApp, user lost some ETH on 1 failed transaction, second transaction was never done

### Reproduction
Prerequisite: you need to have about 30 SNT and 0.01 ETH in your Wallet in Status app

- Open Status
- In Home tab tap on "+" and select Open DApp
- Tap on Bancor, tap Open
- When Bancor DApp is loaded: on Tokens tab tap on BNT token
- On Token Summary page tap on Buy button
- select Localhost and tap Next button
- In "Pay with" field tap on dropdown with ETH. As a result, there is a list of tokens shown, select SNT there. As a result, there is SNT instead of ETH next to PAY WITH field
- In Enter Amount type "30" (so 30 SNT)
- Receive field will be automatically filled in with BNT amount that can be purchased
- Tap Next button
- "You are almost there" screen is shown with SNT -> BNT amount and Transaction fee. In my case, fee was about 0.005 ETH
- tap Proceed button
- Send Transaction screen from Status Wallet will be shown. Tap on Sign Transaction, enter password and tap Sign Transaction. As a result, Transaction sent screen is shown. Tap Got it
- Proceed button becomes inactive and there is spinning indicator shown for quite some time. 
- Check if it ends successfully (there is confirmation in Bancor Dapp shown, Transaction id shown that you can watch, eventually BNT sent to your account). In my case it wasn't: Oh, no Error is shown

### Logs
Geth log: [geth (10).log.zip](https://github.com/status-im/status-react/files/1935720/geth.10.log.zip)
TestFairy session (start from 4:11) https://app.testfairy.com/projects/4803622-status/builds/8149726/sessions/31/?accessToken=4H5yLZvP7OEKASMBtpUm6Y2CLWc
 

### Additional Information
* Status version: nightly build Apr 22
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
we `must` sign 2 transactions in proper order (1st and then 2nd) otherwise  converting will fail. https://support.bancor.network/hc/en-us/articles/360001679911--Oh-no-error-message-debug-option-1

<blockquote><img src="https://theme.zdassets.com/theme_assets/2207736/15da6e069859e96d5a0d6bcf7164c6c76122c674.png" width="48" align="right"><div>Bancor Help Center</div><div><strong><a href="http://support.bancor.network/hc/en-us/articles/360001679911--Oh-no-error-message-debug-option-1">"Oh no" error message - debug option #1</a></strong></div><div>If you are seeing the "Oh no" error screen when trying to convert tokens it may be because you are sending transactions in the wrong order. 
If you are using MetaMask, consider the below ...</div></blockquote>

**Comment by flexsurfer** [comment]
@annadanchenko i think this two transactions flow is not good from UX pov, what if i accidentally reject the second transaction. But for status there is one more problem, we have 5 min timeout for transactions, what if i sign first one but second will timeout?

**Comment by flexsurfer** [comment]
@annadanchenko you can use simple dapp to test this issue 
![image](https://user-images.githubusercontent.com/11790366/39471191-6a2ac2e0-4d4a-11e8-9457-da52154c5913.png)

**Comment by asemiankevich** [comment]
works fine with Simple Dapp - can sign 2 txns in a row without any issues.

**Comment by asemiankevich** [comment]
@annadanchenko i am waiting for some snt/eth on mainnet to test it, if you have some - would you mind to take a look?
