### ISSUE TITLE
Can't send funds in group chat - transaction screen is not shown (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3959]
### Description

*Type*: Bug

*Summary*: Transaction screen is not shown when tapping send in group chat or 1x1 chat quickly (dont wait until slider is fully loaded)

#### Expected behavior
i can send funds 

#### Actual behavior
transaction screen is not shown sometimes when sending funds in group chat or 1x1 chat

### Reproduction

- Open Status
- As Device A (android) faucet some funds on Ropsten with RPC
- As Device A (android) create a group chat with another device B (ios)
- As Device A call /send command, enter any valid amount and tap send quickly while slider is still being loaded

Or from 1 device to another request any sum that user is able to send and then tap this request message and send quickly

### Additional Information
* Status version: nightly 353
* Operating System: Android, iOS

**Comment by annadanchenko** [comment]
no screen with slider Fee anymore
