### ISSUE TITLE
User with restored account gets no chats and messages from the past contacts

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3963]
### Description

*Type*: Bug

*Summary*: Alice and Bob are in contacts of each other and had conversation in 1:1 chat. Then Alice restores her account and see empty Home screen (expected for now). Bob sends to Alice new message. Alice see no new chats/messages on her side (this is bug) 

#### Expected behavior
When Alice restores account and Bob sends her a new message then Alice can see chat with Bob

#### Actual behavior
Alice sees no new chats
### Reproduction

- As Alice and Bob: add each other to the contacts and send several messages in 1:1 chat to see you can get all of them
- As Alice: remember you seed phrase and password. uninstall Status app and install it again. Restore the account and log in
- As Bob: after Alice logged to Status and see empty Home screen, write her new message in 1:1 chat. 

You might also want to check how it works if Alice and Bob talked in Group and public chats

### Additional Information
* Status version: nightly build Apr 17
* Operating System: Android and iOS

**Comment by chadyj** [comment]
I'm using a restored account and also having this issue with *new* contacts too.

**Comment by cammellos** [comment]
This can be closed now https://github.com/status-im/status-react/pull/4144 should have fixed the issue
