### ISSUE TITLE
Multiline message input is broken

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#397]
![qwe](https://cloud.githubusercontent.com/assets/2364994/19863100/8f7392ba-9f9b-11e6-88a7-8eba60a7581d.gif)

**Comment by alwx** [comment]
@rasom you've removed all multiline input functionality in this commit: https://github.com/status-im/status-react/commit/6effc91d3c496053e41d457c16b828d7f525b5d6 
Don't know why.

**Comment by rasom** [comment]
Obviously, I don't remember why id did that. That's actually why PR reviews are needed :)
https://github.com/status-im/status-react/pull/306
