### ISSUE TITLE
User can export the chat history

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#3988]
### User Story

As a user, I'd like to have more control over my chat history and export it anytime.

### Description

*Type*: Feature

*Summary*: Currently, it's unclear how long the chat history is stored. The minimal requirements are to have an ability to export my chat history. 

### Solution
*Summary*: 
- add a new option in Profile tab to export my chat history,

Originally included https://github.com/status-im/status-react/issues/4215

**Comment by chadyj** [comment]
@adambabik Can i edit this just to have the `clear chat` feature? 
Export can be done separately.

**Comment by adambabik** [comment]
@chadyj of course! That totally makes sense to split these two concerns.

**Comment by mandrigin** [comment]
very abandoned issue, closing it.
please reopen if disagree
