### ISSUE TITLE
No new chat created when sending Txn from unsigned to previously deleted chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3993]
*Type*: Bug

*Summary*: I have scanned QR code of someone. I went to this chat and wanted to send a transaction. While being on transaction screen i tapped sign later. I deleted the chat with this person. Then i went to Unsigned and signed the transaction. I do expect the chat which i deleted earlier is shown again.

#### Expected behavior
i want the chat to be re-opened after deletion when i trigger it by sending transaction from sign later screen. 

#### Actual behavior
chat is not shown on the sender side

### Reproduction
- Open Status
- Faucet some funds
- Scan valid QR code of any person
- call /send command and tap sign later on transaction screen
- on the home tab delete the chat with this person
- tap wallet - transaction history - unsigned
- sign the transaction
- pay attention that no chat was re-created

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by goranjovic** [comment]
Closing since we no longer have Sign later, so this state is not reachable.
