### ISSUE TITLE
Allow to specify different upstream endpoint

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#3994]
### User Story

As a user, I'd like to use Status with upstream node but I'd like to specify the upstream address by myself.

### Description

*Type*: Feature

*Summary*: It's important that even if one decides to use upstream node, there is a choice. Currently, the upstream networks use infura and it's not possible to change it. 

### Solution
*Summary*: 
- allow specifying a custom upstream address when selecting the upstream network

**Comment by oskarth** [comment]
Do we need some designs for this? Can we re-use components that we use for other custom data entry? Would probably be easiest

cc @chadyj @denis-sharypin

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 3000.00
Contract address: [0x55c5c9daf2ef4f9914c5e9c995b91f755c07c524](https://etherscan.io/address/0x55c5c9daf2ef4f9914c5e9c995b91f755c07c524)
Network: Mainnet
Paid to: ConnorChristie
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by debragail** [comment]
is there a design for this?

**Comment by Coffee-Boyy** [comment]
@debragail @oskarth @chadyj @denis-sharypin 
How does an added option to the network settings look? Possibly bringing up a modal for user input when selected: (I also think the networks should be categorized)

![image](https://user-images.githubusercontent.com/1206980/39795238-e4eb2f98-53a2-11e8-9e8d-9a63557cc97d.png)

**Comment by adambabik** [comment]
I like the categories! It looks nice. 

One thing I would change is `Testnet` category. `testnet` term is interchangeable with `Ropsten` (from `geth -h` output):
```
  --testnet                                  Ropsten network: pre-configured proof-of-work test network
  --rinkeby                                  Rinkeby network: pre-configured proof-of-authority test network
```

To avoid confusion, maybe we can call this category `Public test networks` or something similar that is descriptive and avoids using a single term `testnet`.

What's gonna happen when the user taps on `Custom upstream RPC`? I believe there should appear a modal window to enter the URL and, similarly to `Connected` label, it should display the currently entered upstream RPC address. 

And the final case, what if one would like to have multiple custom upstream RPC addresses? It may be a valid case.

**Comment by Coffee-Boyy** [comment]
Instead of the mockup that only includes the ability to add one custom network, maybe there could be a plus button in the top right to add a custom network and those would show under the custom section?

As a side note, at first glance when switching to a testnet, I found the two different (local and upstream) options for each network confusing. Would it be intuitive if they were merged into one option and upon selection a modal is shown that allows them to either select local or upstream?

**Comment by adambabik** [comment]
That sounds good! Then the flow would be (1) tap `+` to display the modal to enter a custom network address, (2) after tapping OK the modal disappears, (3) the new custom network is displayed in the list. I guess we would also need to provide a way to delete custom networks and maybe edit option.

**Comment by Coffee-Boyy** [comment]
The deletion could be the infamous swipe row to show delete button. It isn't the most intuitive but it will most likely be devs or power users adding and removing custom upstreams so I am sure they'd be able to figure it out since many other apps use the swipe to delete functionality

**Comment by debragail** [comment]
I think swipe row for deletion is a good ux in this case,

**Comment by oskarth** [comment]
@ConnorChristie good idea!

Let's remove design blocked, better get something working here for release candidate and we can add designs later.

**Comment by oskarth** [comment]
cc @mandrigin mobile app

@adambabik do we need to do anything on P2P side for this?

**Comment by adambabik** [comment]
I don't think so. Currently, when I switch to an upstream network, I am presented with a view with a JSON config and the upstream URL. This should work the same for custom upstream URLs so no changes on status-go side should be required.

**Comment by oskarth** [comment]
@ConnorChristie do you want to give this a go? It's one of our blockers for beta release :)

@mandrigin Since we aren't pushing for improvements to LES (instead awaiting ULC) this would be very useful from a decentralization POV.

**Comment by Coffee-Boyy** [comment]
@oskarth Sure, I can work on this!
