### ISSUE TITLE
Make incoming and outgoing transactions clearer

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#3996]
### User Story

As a user, I want to more easily discern between my incoming and outgoing transactions so that I can understand my transaction history at a glance.

### Description

*Type*: Improvement

*Summary*:
During testing, users had difficulty distinguishing between their sent and received transactions on the Transactions History screen because they are too similar looking.

Currently we use purple and green arrows and a “To/From” line to indicate transfer directions. 

![txn history](https://user-images.githubusercontent.com/15470435/39255461-2abad7fe-48df-11e8-93f9-4fefad79acbc.png)

#### Expected behavior
When a user looks at their transactions history, they do not have to question whether a transaction was incoming or outgoing; visual cues make it perfectly clear.

### Solution

*Summary*: 

-  Add visual cues to indicate whether a transfer is positive (incoming) or negative (outgoing), with + or - symbols in front of transfer amount.
-  Make either positive or negative transfers stand apart, e.g. with colored font on incoming transactions.
- The color purple isn’t typically associated with a negative transaction; it may be beneficial to use a neutral color for outgoing transaction symbols.

**Comment by denis-sharypin** [comment]
Still WIP
