### ISSUE TITLE
Users can set currency

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4008]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to set the currency so that I can see crypto value in my chosen currency.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
The wallet is fixed to show USD, but not everyone lives in the US! There have been several requests to change the currency so let's make Status useful for non-USD people.

#### Expected behavior
A user can set their local currency.

<img width="854" alt="screenshot 2018-04-26 12 42 09" src="https://user-images.githubusercontent.com/6559881/39301431-5599e15c-494f-11e8-8eeb-e026740917e1.png">

#### Actual behavior
USD is fixed

### Solution

On the Profile tab there is already a `Main currency` item with USD fixed.
Create a new screen with a alphabetically sorted list of currency eg:
> Australian Dollar (AUD)
> United States Dollar (USD)

Then change the app to show the local currency when fiat is displayed.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x3023576ca2a8289f3fd8610aefdf03e2bcc5eaca](https://etherscan.io/address/0x3023576ca2a8289f3fd8610aefdf03e2bcc5eaca)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by denis-sharypin** [comment]
Specs:

icon name: [icons/icon :icons/ok]

<img width="708" alt="screenshot 2018-04-26 12 50 22" src="https://user-images.githubusercontent.com/6559881/39301722-7c2996c2-4950-11e8-89d7-70f6c522c1db.png">

<img width="255" alt="screenshot 2018-04-26 12 50 40" src="https://user-images.githubusercontent.com/6559881/39301723-7c5b543c-4950-11e8-8ced-d8afdd6cb0ed.png">

Font size
<img width="1096" alt="screenshot 2018-04-26 12 52 32" src="https://user-images.githubusercontent.com/6559881/39301786-b67f1644-4950-11e8-96ea-bc9f911e5d01.png">

**Comment by chadyj** [comment]
My apologies if this is a bit late, but this issue was supposed to have a full list of supported currencies. The AUD/USD/RUB was just for the mockup.

Here is the list of currency's to support: https://gist.github.com/chadyj/baf3a6a430a03e3760df8d628e02de8f

For simplicity lets default to USD.

<blockquote><img src="https://avatars3.githubusercontent.com/u/116099?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/chadyj/baf3a6a430a03e3760df8d628e02de8f">Currency, codes, and symbol</a></strong></div><div>Currency, codes, and symbol</div></blockquote>

**Comment by flexsurfer** [comment]
thanks @psdp awesome job, we added 300SNT bonus
