### ISSUE TITLE
Show fiat value of wallet assets

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4009]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see the fiat value of assets so that I know value.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

The asset list in the wallet only shows the ETH/token amount, but it can be hard to know the value of `0.0034` ETH. Let's bring confidence and clarity here by showing the fiat amount.

#### Expected behavior
A user looking at the asset list can see the fiat value.

#### Actual behavior
A user is oblivious of asset list value

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Show the fiat value next to the crypto amount.

<img width="219" alt="show-fiat" src="https://user-images.githubusercontent.com/116099/39290576-5abcd3b6-4930-11e8-9e26-6c24362ff447.png">

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1500.00
Contract address: [0x0e1fc51eb9da54b0300bad097742867d2250ca4d](https://etherscan.io/address/0x0e1fc51eb9da54b0300bad097742867d2250ca4d)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
