### ISSUE TITLE
Allow both release and develop version to coexist

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#4010]
### User Story

As a developer, I want to have both release and developer version running at the same time on iOS.

### Description

Currently both versions share same identifier preventing to keep the released version installed.

*Type*: Feature

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1500.00
Contract address: [0xf3e9c57115f60704c397da150e3aebdc1609d7cf](https://etherscan.io/address/0xf3e9c57115f60704c397da150e3aebdc1609d7cf)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
