### ISSUE TITLE
Consistent transaction flow from wallet and chat

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4012]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want a consistent transaction UI so that I can easily make and understand transactions from both Wallet and Chat.

As a user, I want a send tokens in chat.

As a developer, I don't want to duplicate UI's and flows so that I can have cleaner code.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

Sending and receiving transactions should be a consistent experience (easier for both users, designers, and developers), but currently, there are different screens and flows when initiating from Wallet or a chat. We can easily fix this to streamline transactions and UX as users don't need to learn 2 UI's and see redundant screens, and developers don't need to maintain it.

#### Expected behavior
Consistent and delightful transaction flows

#### Actual behavior
Inconsistent transaction flows. 
Users have complained in Instabug about slider UI.

<img width="169" alt="screen shot 2018-04-26 at 11 54 13 am" src="https://user-images.githubusercontent.com/116099/39299421-f4b8848e-4948-11e8-85b6-4d3d6b9cf983.png">

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

A consistent flow from both wallet and chat screens (note screenshot if for illustration purposes)
<img width="636" alt="screen shot 2018-04-26 at 11 32 20 am" src="https://user-images.githubusercontent.com/116099/39299435-fb682028-4948-11e8-8769-a63fa94afdce.png">

From wallet, flow is unchanged.
For chat, a user can invoke the transaction screen by doing:
```
/send 
/send 100
/send 100 SNT
/send 100 ETH
```
The wallet screen is prefilled with the recipient, and amount/asset if it was entered. The slider screen is skipped.

### Additional

This flow would fix https://github.com/status-im/status-react/issues/2923 by allowing tokens to be sent in chats.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1500.00
Contract address: [0x666ff81085bc23a07399bb9acaeb34e36d282dfc](https://etherscan.io/address/0x666ff81085bc23a07399bb9acaeb34e36d282dfc)
Network: Mainnet
Paid to: goranjovic
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
