### ISSUE TITLE
Create icon for debug builds

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#4018]
[comment]: # (Please replace ... with your information. Remove < and >)
### User Story

As a developer, I want a specific icon for debug builds

### Description

*Type*: Feature

Debug builds can now live together release builds. To easily distinguish them a new icon will be created.

**Comment by denis-sharypin** [comment]
@jeluard @endenwer 

![icon_83 5 2x](https://user-images.githubusercontent.com/6559881/39373435-e1deeaf6-4a47-11e8-9d69-45ec83ac50e0.png)



Android — 
[ic_launcher — debug.zip](https://github.com/status-im/status-react/files/1955868/ic_launcher.debug.zip)


iOS — 
[iOS — Debug.zip](https://github.com/status-im/status-react/files/1955863/iOS.Debug.zip)
