### ISSUE TITLE
Amount and total fee fields are overlapped by keyboard on Advanced screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4020]
### Description

*Type*: Bug

*Summary*: `Reset to default` and `Done` buttons overlap `Amount` and `Total Fee`

#### Expected behavior
A keyboard should not overlap wallet screen details, screen should be adjusted dynamically

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/39310438-09d56682-4973-11e8-8c74-71c2707a58da.png)

### Reproduction
- Open Status
- /faucet some funds
- Tap wallet
- Tap specify amount and enter some valid amount
- Tap advanced
- Tap into transaction fee
- Tap into gas limit or gas price

### Additional Information
* Status version: develop
* Operating System: Android 7.0 Huawei P10 lite 5.2"

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc8acd041c8dded146635baff76b6aa00c76c2e5635fb278e50dc2a30786e687c](https://etherscan.io/tx/0xc8acd041c8dded146635baff76b6aa00c76c2e5635fb278e50dc2a30786e687c)

**Comment by okilimnik** [comment]
redesign should be considered to achieve this, because even with fixed empty space in top of screen, a keyboard can overlap the details. Android has much more different sizes than Iphone. 
Maybe scrollview will be useful.
![screenshot_1525963238](https://user-images.githubusercontent.com/11755521/39875587-b0db9df0-5479-11e8-88ab-908a7c0c3749.png)

**Comment by knightmike** [comment]
getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)

Put this in the onCreate Method

OR

<activity
...
android:windowSoftInputMode="adjustPan">

In the layout.

PS- New here. Still trying to figure out the way around the code and how to claim bounty.

**Comment by knightmike** [comment]
<activity
   ...
   android:windowSoftInputMode="adjustPan"> 
</activity>

Even better
