### ISSUE TITLE
"user left" message in group chat is shown twice

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4024]
### Description

*Type*: Bug

*Summary*: "user left" message in group chat is shown twice

<img src="https://user-images.githubusercontent.com/7532782/39313661-d23190f2-4972-11e8-9212-626e9ccd76a0.png" width="200">

#### Expected behavior
"user left" message should be shown only once.

#### Actual behavior
"user left" message is shown twice.

### Reproduction

- Open Status
- User A: Create group chat with user B
- User B: Leave group chat
- User A: Check group chat messages 

### Additional Information
* Status version: nightly, Android 26
* Operating System: Android, iOS

**Comment by janherich** [comment]
Group chats are currently disabled and being completely reworked, closing for now
