### ISSUE TITLE
Gas Price value is not fully shown (only first 4 digits) on iOS

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4026]
### Description

*Type*: Bug

*Summary*: Gas Price field on the Advanced screen shows only 4-digit value

#### Expected behavior
All digits are shown in Gas Price field

#### Actual behavior
only 4 digits shown

![image](https://user-images.githubusercontent.com/28752642/39314840-de707d1e-497d-11e8-910a-e65ef11b86e3.png)

### Reproduction

- Open Status
- Tap wallet
- Tap send transaction
- Tap advanced
- Tap Gas Price field
- Enter 1234567 value to Gas Price field

### Additional Information
* Status version: develop
* Operating System: iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 325.00
Contract address: [0x287ab513269dfaed565f2dece853c0c8967db1a5](https://etherscan.io/address/0x287ab513269dfaed565f2dece853c0c8967db1a5)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
