### ISSUE TITLE
Add script to dump and restore app state

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#4027]
### User Story

As a developer, I want to replicate app state so that I could reproduce a bug on my local machine and fix it.

### Description

It should basically have 2 commands: dump and restore.

Script should be able to dump app state by downloading realmdb and account keys from simulator/device and restore app state by uploading realmdb and account keys to simulator/device.

### Additional Information

Support both Android an iOS platforms.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7103ae2cd06eec603a25f47ea314493081f30e1068a247ca47486ea471ac0080](https://etherscan.io/tx/0x7103ae2cd06eec603a25f47ea314493081f30e1068a247ca47486ea471ac0080)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc04085ed8bd43e96b4c44c26309944ad0999259b5014e70aca72d8b59235d388](https://etherscan.io/tx/0xc04085ed8bd43e96b4c44c26309944ad0999259b5014e70aca72d8b59235d388)

**Comment by pablanopete** [comment]
@dmitryn is this issue still relevant?

**Comment by dmitryn** [comment]
@pablanopete i think we can close it as we don't need that functionality at the moment.
