### ISSUE TITLE
When group chat member is removed, the public key is shown instead of username

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4028]
### Description

*Type*: Bug

*Summary*: When a group chat member was removed, other users see "admin removed **{public key}**". Instead of the public key, the real name should be shown. 

#### Expected behavior
Real or default name (if user didn't set it) should be shown. 

#### Actual behavior
Public address is shown:

<img src="https://user-images.githubusercontent.com/7532782/39315508-19252466-4977-11e8-87b0-fe8c8e385716.png" width="200">

### Reproduction

- Open Status
- Create group chat with 2 other users
- Remove 1 user from the group chat
- The other user sees the incorrect message

### Additional Information
* Status version: nightly, April 26
* Operating System: Android, iOS

**Comment by janherich** [comment]
Group chats are disabled and being completely reworked, closing for now
