### ISSUE TITLE
Make tribute to send a new message [UI]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4033]
### User Story

As a user, I want to pay someone I find interesting so that I can send them a message.

### Description

*Type*: Feature

*Feature summary*: 
See the [#096 Tribute to Talk idea](https://github.com/status-im/ideas/pull/165) for context.

User A does not have User B in their contact list. User A has a minimum tribute of 200 SNT set for non-contacts to message them.

When User B starts a new chat with User A, they receive a system message asking for the minimum tribute.

User B then completes a transaction flow to send User A the tribute. Once confirmed, User B may send their message.

*Implementation*:
The scope of this issue is to code the UI only. Values can be hard coded. 

Request transaction messages require updating. (https://github.com/status-im/status-react/issues/4136)

[System messages are being updated](https://github.com/status-im/status-react/issues/3901), and #3233 and #3234 will add ERC20 support to chat. For this issue, we can work with existing system messages.

#### Mockups
[InVision prototype](https://projects.invisionapp.com/share/P5HQFU23BNA#/screens/294312819) - Zeplin screens TK

![request flow 01](https://user-images.githubusercontent.com/15470435/39350363-8a742108-4a30-11e8-8a8d-ba18df2a0700.png)

#### Additional Information

[TtT contract documentation](https://github.com/status-im/contracts/blob/096-tribute-to-talk/TributeToTalk.md#contract-deployment)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x780125b0119da531000b8843f70863d7a786d81bcf666cb8e03b6491ef21457e](https://etherscan.io/tx/0x780125b0119da531000b8843f70863d7a786d81bcf666cb8e03b6491ef21457e)

**Comment by georgiemathews** [comment]
I'll start working on this.

**Comment by pablanopete** [comment]
@rachelhamlin do you know what is the state of this issue? Should we revoke the bounty for the current time as we are in the process of revoking stale / bounties with no active work on them currently.

**Comment by rachelhamlin** [comment]
Totally fine to remove @pablanopete 👌🏼

**Comment by pablanopete** [comment]
CC @andytudhope
