### ISSUE TITLE
Can't recover from key exchange failure when contact request message is lost

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#4034]
When a contact request is sent by A to B, if the contact request is not received by B, the key exchange doesn't occur and following messages from A to B will never be received by B. B will not even know that A tried to contact him and A won't be able to send a new contact request to B.
From A perspective it looks like B has still not accepted his invite
From B perspective it looks like nothing ever happened.

**Comment by Serhy** [comment]
Looks like related (or even the same) what is in the #3984 issue.

**Comment by oskarth** [comment]
How about extending https://github.com/status-im/status-react/pull/3964 behavior to also include contact request? So user can see contact request didn't go through and that this is necessary in order to talk to each other at a all. Can add some copy/content to this as well as to make it clear this improves security/privacy.

**Comment by cammellos** [comment]
@oskarth #3964 would only tell us that the contact request has left the node, not that the user has received it, we would need to implement some Ack (which I believe we might already have for contact requests , ContactRequestConfirmed, but don't know if it is sent automatically).
At that point we still have a few things to consider (should you allow the user to send messages before a contact request is confirmed? If so should you send them using the shared secret or pk until the request is confirmed? etc).
I think relying on a message to be delivered to allow communication is something we should avoid if possible, until we know for a fact that whisper/mailserver is reliably sending sending/delivering messages, which given the nature of the protocol might never happen.

**Comment by oskarth** [comment]
\o/
