### ISSUE TITLE
All symbols after dot/comma erased if editing decimal number in the transaction amount field

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#4038]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to edit transaction amount in the wallet by deleting certain number of symbols

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: All symbols after dot/comma erased if editing decimal number in the amount field when sending/requesting transaction from wallet 

#### Expected behavior
Only the last symbol is deleted 

#### Actual behavior
All symbols after the dot are deleted, only `0` left in the amount field 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Navigate to Wallet
- Click Send transaction button
- Type `0.0005` into the Amount field
- Tap Delete (backspace) button on the keyboard once

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build from April 27
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 340.00
Contract address: [0x75e2ca09897b853e8ef4fd888ba7552d0d499481](https://etherscan.io/address/0x75e2ca09897b853e8ef4fd888ba7552d0d499481)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
