### ISSUE TITLE
[Design] Improve send transaction screen

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4040]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to send prepare a transaction so that I can send a transaction.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

The send transaction screen is at the heart of every Ethereum transaction and core to Status so we need users can seamlessly send transactions.

#### Expected behavior
At a glance users can understand the transaction detail and sign.

#### Actual behavior
Users get confused about the recipient, account balances, amounts, etc.

<img width="216" alt="screen shot 2018-04-27 at 2 47 40 pm" src="https://user-images.githubusercontent.com/116099/39363261-f4f4c64c-4a29-11e8-9eca-1f7faabfa135.png">

### Solution

- Clearly shows what the transaction is for. Eg person, dapp, etc.
- Shows Fiat cost
- Shows crypto cost
- Shows fees
- Emphasize final price
- Offer escape route
- Shows balance
- Removes "sign later"

Also let's explore adding a confirmation screen

### Additional

UXR insight:
<img width="876" alt="screen shot 2018-04-13 at 3 29 06 pm" src="https://user-images.githubusercontent.com/116099/39363024-07cf768c-4a29-11e8-844e-adb3b8850699.png">
<img width="804" alt="screen shot 2018-04-13 at 3 30 29 pm" src="https://user-images.githubusercontent.com/116099/39363038-18e25c8c-4a29-11e8-82ff-363811b028e9.png">

**Comment by goranjovic** [comment]
I'd like to break this down into smaller, more specific tasks. Then we can put some of them in Beta scope and leave others out

**Comment by chadyj** [comment]
👍 
Shall we start with the design exploration that Denis is kicking off and then review screens as a team and break up into small issues?

**Comment by goranjovic** [comment]
Sounds much Beta

**Comment by Coffee-Boyy** [comment]
A great and beautiful example of an application that shows all the metrics in a clear and concise way to the user is the [Balance Manager app](https://manager.balance.io/):

This could serve as a great foundation for a new and improved send transaction flow which isn't terribly different than the current design.

There's nothing about gas or gas costs, only information on the speed of the transaction and the fees for that delivery speed. Along with allowing the user to enter the amount in either ETH or $$ which automatically converts the values for them.

![image](https://user-images.githubusercontent.com/1206980/39995015-2b1960b8-57cf-11e8-9c2a-6ac39df5189c.png)

**Comment by chadyj** [comment]
Closing, as designs are being tested. Implementation will be in smaller issues.
