### ISSUE TITLE
'GOT IT' screen is not shown after signing an unsigned transaction

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#4043]
### Description

'GOT IT' screen with the information 'Please wait for 12 confirmations...` is not shown after signing an unsigned transaction from "unsigned tab"

#### Expected behavior
'GOT IT' screen is shown
![0026screenshot](https://user-images.githubusercontent.com/12611990/39364187-d06d73d0-4a35-11e8-8157-fd21cf2142ee.png)

#### Actual behavior
User is redirected to 
![0030screenshot](https://user-images.githubusercontent.com/12611990/39364247-00c8c3e0-4a36-11e8-9795-865095dda774.png)
"unsigned tab"

### Reproduction

- Open Status
- Create new user and send `/faucet` request for getting ETH (required for future steps)
- Go to Wallet, tap on `Send transaction`, enter valid amount, specify recipient, tap `Sign Later` and tap yes/ok on popups 
- Go to Transaction History and click on "unsigned tab"
- Sign the transaction

Status version: nightly build from April 27 2018
Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 340.00
Contract address: [0x58c88b761317b3676b63d95af1052b929950a1a5](https://etherscan.io/address/0x58c88b761317b3676b63d95af1052b929950a1a5)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by ghikio** [comment]
Seems like this bug has been introduced last month, I have a build from April 7 where the screen works fine. I'll give it a try to see if I can find what's the problem :smiley:
