### ISSUE TITLE
[WIP] Show metrics opt-in reminder after 7 days

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4044]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user that choose to share opt-in metrics, I want to be reminded of my choice after 1 week so that I can reconsider and reconfirm my choices.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Collecting metrics touches on issues of privacy so Status needs to ensure users make the right decisions. For users choosing to share metric data we should remind them after 7 days and ask them to re-confirm their choice.

#### Expected behavior
After 7 days show an alert asking users to reconfirm their choice

### Solution

Copy tbd, but it should convey this sentiment:

> We know you were ok with sharing your data last week, but we care and know people change their mind. You may have even been distracted or time pressed when you said yes. We are a company that helps people guard their privacy and therefore we are proactively checking if you are still ok with sharing your usage data. Just to be sure.
> ooh and by the way, you can also see what we're getting out of the usage data. <link to public dashboard>

**Comment by hesterbruikman** [comment]
Looking at this from two sides, format and message as format impacts the message.

**Format**
I have my concerns about using a _system dialog_. This would block interaction and I'm not sure we want to do that with a reminder. Could we use the backup seedphrase reminder/notification in stead?

**Message system dialog**

> Hi! Thanks for sharing your [anonymous usage data](url) with us. They help us focus on the right ways to improve this app. :-)
> 
> Just checking in: are you still OK sharing these data with Status? 
>
> Yes                No

**Message notification (homescreen)**
> Hi! Thanks for sharing your [anonymous usage data](url) with us. They help us focus on the right ways to improve this app. :-) 
> 
> You can switch off sharing anytime by switching off "Help improve Status" in your [profile settings](url).
