### ISSUE TITLE
Android build hangs on :app:preDebugBuild > Resolve dependencies

### ISSUE THREAD

**Issue by kwingram25** [status-im/status-react#4050]
### User Story

As a developer I want to build the app and install on a device for testing

### Description

*Type*: Bug

The command `make run-android` suddenly stopped working about a day ago apparently because of a missing maven repository. The problem appears to be a remote URL `maven { url "http://139.162.11.12:8081/artifactory/libs-release-local" }` (build.gradle)

#### Expected behavior
The app installation continues and finishes
#### Actual behavior
The app installation hangs at 13% during the phase
`:app:preDebugBuild > Resolve dependencies :app:debugRuntimeClasspath > maven-metadata.xml`
and never completes
### Reproduction
- Clone Status repo
- Follow commands to build and run dev on android
`make dev-android-real`
`make run-android`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build from April 27
* Operating System: Android

**Comment by subeeeee** [comment]
!! 我也遇到了一样的问题
