### ISSUE TITLE
Blue 'rims' around profile pictures?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#406]
With upgrade to ReactNative 0.36 blue rims have appeared around profile pictures.

![bluerims-console](https://cloud.githubusercontent.com/assets/2714786/19932621/b99b8410-a14b-11e6-999f-b5b7eddd550c.png)
![bluerims-contact-list](https://cloud.githubusercontent.com/assets/2714786/19932622/b99d28d8-a14b-11e6-8156-77259df768f3.png)

**Comment by rasom** [comment]
https://app.zeplin.io/project.html#pid=570c07ce7d73d11c3c6709ae&sid=5813428923bec6152132df38
```
Notice the border, it’s not part of the image, 
it should be in code so that avatars with plain
white backgrounds looked good.
The actual image is below.
```

**Comment by jarradh** [comment]
This was never discussed with me, nor does it look good, sorry for letting this get to you guys. 
Also I notice he is trying to change to DApp icon wtf

**Comment by jarradh** [comment]
Can we please revert this change across all profile pics

**Comment by rasom** [comment]
It's easy to fix. Sorry, I will doublecheck with you suspicious think like this next time

**Comment by jarradh** [comment]
I've added a red dot note and will be more vigilant!

**Comment by rasom** [comment]
In result Wallet icon doesn't look very cool
 
<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/19961913/e4f35102-a1bd-11e6-9528-c4a6bf0bd065.png />

**Comment by jarradh** [comment]
yeah it's ugly, i took it back to @andmironov but no response yet.. we'll sort it out

**Comment by jarradh** [comment]
to clarify the icon looks more like a command/request icon rather than the profile for a dapp, which is why it looks out of place

**Comment by andmironov** [comment]
Hey, what do you think of making them colorful like this?

![dapp_avatars](https://cloud.githubusercontent.com/assets/3115606/20000830/868a4a4e-a28a-11e6-8566-82a617743eee.png)

Also, as i mentioned before, you should add that 1px inside border with 50% so that avatars with plain white backgrounds looked okay.

**Comment by andmironov** [comment]
this border is almost invisible on colorful images, but is visible on plain white

<img width="813" alt="border" src="https://cloud.githubusercontent.com/assets/3115606/20001149/e36ad2e6-a28b-11e6-9e36-00cb363ba82d.png">

**Comment by jarradh** [comment]
The colour feels better, but I think its also the icon is just very small and alot of negative space around it. It feels abit sterile?

**Comment by jarradh** [comment]
Maybe we can mildly personify the wallet, like Console is with the eyes ?

**Comment by rasom** [comment]
@andmironov @jarradh so i still don't understand what to do with this wallet icon and rims, can you clarify?

**Comment by jarradh** [comment]
remove them please

**Comment by jarradh** [comment]
the wallet icon, leave as is, i'll get a replacement in
