### ISSUE TITLE
Make it easier to get STT without requiring special knowledge

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4062]
## Problem

In order to test the app it is useful to be able to get STT quickly. Currently this requires the following steps, and most importantly, awareness of this being a thing:

```
# How do I get STT?
1. Be on Ropsten
2. Advanced settings -> Development mode
3. Chat with console and use /faucet <StatusFaucet> to get ETH
4. For STT simply send a transaction (can be 0 ether) with Gas limit 105000 (you need to set the value manually!) to the following address: 0x34358C45FbA99ef9b78cB501584E8cBFa6f85Cef (https://wiki.status.im/Testing_FAQ_(core_team))
You should have 1000 STT
```

(from https://github.com/status-im/ideas/blob/8728f8cab8fec3f3f1a3ef018993ab5e63b5d2e1/ideas/168-paid-master-nodes/stt-payment-testing.md#how-do-i-get-stt - also see above wiki link with more relevant addresses)

## Solution

Figure out a way to collapse the above steps. For example, maybe we can prefill STT as faucet? Or we could make a dev dapp that does the two 'faucet requests' sequentially. Or add address as a default somewhere. Whatever is easiest.

## Acceptance criteria

Can get STT from app quickly without having to look up special instructions, similar to ETH faucet.

## Notes

Just rough notes to capture above issue, feel free to edit issue liberally.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/ideas">status-im/ideas</a></strong></div><div>ideas - Swarm Home. New, completed and in-progress features for Status</div></blockquote>

**Comment by chadyj** [comment]
I like this alternative:

1. Be on Ropsten
2. Advanced settings -> Development mode
3. Go Home, New, Open Dapp, then open `Simple Dapp`
4. Tap `Assets`, then request STT, or another test token.

<img width="221" alt="screen shot 2018-05-08 at 8 18 02 pm" src="https://user-images.githubusercontent.com/116099/39775033-ee517282-52fc-11e8-9112-162e59f4882e.png">

**Comment by annadanchenko** [comment]
@oskarth are you ok with the provided solution in Simple DApp? if yes, can you close the issue, please?

**Comment by oskarth** [comment]
Seems great!
