### ISSUE TITLE
it should be possible to see transaction data in advanced while signing

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#4066]
![image](https://user-images.githubusercontent.com/11790366/39519918-5d9eb4d8-4e11-11e8-98a2-d244aa91a368.png)
![image](https://user-images.githubusercontent.com/11790366/39519930-6974dc06-4e11-11e8-9273-c81784f387ae.png)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x968508579b73fde64003e386266378d40bd266e8f81706ba60ac01c558ff7d62](https://etherscan.io/tx/0x968508579b73fde64003e386266378d40bd266e8f81706ba60ac01c558ff7d62)

**Comment by okilimnik** [comment]
it's impossible to create a modal view from another modal view, "Send Transaction" view will be destroyed.

**Comment by okilimnik** [comment]
It's not a problem to add "Included data" below "Transaction fee", but it's impossible to create a modal screen from another modal screen in current navigation implementation.

**Comment by flexsurfer** [comment]
@okilimnik you're right, @denis-sharypin could you help, any ideas how we can implement this?

**Comment by denis-sharypin** [comment]
When you are sending TX from the wallet it's possible to call such modal to enter a recipient address.
Why we can't use it?
![img_4880](https://user-images.githubusercontent.com/6559881/39930280-934b26ea-553a-11e8-93a7-f84cdbf5dc03.PNG)

**Comment by okilimnik** [comment]
parent screen is not modal in this case

**Comment by flexsurfer** [comment]
because in wallet we don't have data, and wallet is not modal, but from dapp we are opening modal wallet

**Comment by denis-sharypin** [comment]
ah ok.
Tbh currently I'm working on the redesign of the whole Send Transaction flow here https://github.com/status-im/status-react/issues/4040 Make sense to wait until it will be ready then. Sorry for inconvenience

**Comment by flexsurfer** [comment]
sorry @okilimnik let's wait then

**Comment by Coffee-Boyy** [comment]
The technicalities of this are actually not as bad, the transaction data is already being passed to the prepare-transaction function but not being used.

https://github.com/status-im/status-react/blob/6eea090ef80d9f6d52c1caeeafc5d1c1d6387500/src/status_im/ui/screens/wallet/send/events.cljs#L107-L110

**Comment by pablanopete** [comment]
Is this one still relevant @denis-sharypin or @jeluard  ? Working on old bounties / revoking those that don't make sense any longer.

**Comment by flexsurfer** [comment]
hey @pablanopete not relevant anymore

**Comment by pablanopete** [comment]
Ready to be revoked cc @andytudhope
