### ISSUE TITLE
Fix build.clj script

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#4072]
We would like to move from lein to the new clj cli tool for project task.
There is currently an error with the figwheel task that prevents us from using it.

#### Expected behavior
`clj -R:repl build.clj figwheel android` works like `lein figwheel-repl android`

#### Actual behavior
`clj -R:repl build.clj figwheel android` produces the following error in the android simulator when running the app:

```
05-01 12:42:07.448  5046  5102 E ReactNativeJS: Error rendering component (in status_im.android.core.app_root)
05-01 12:42:07.452  5046  5102 E ReactNativeJS: ReferenceError: Can't find variable: performance
05-01 12:42:07.452  5046  5102 E ReactNativeJS: 
05-01 12:42:07.452  5046  5102 E ReactNativeJS: This error is located at:
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in status_im.android.core.app_root (created by env.android.main.reloader)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in env.android.main.reloader
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in Unknown (at renderApplication.js:35)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:102)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:122)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in AppContainer (at renderApplication.js:34)
05-01 12:42:07.458  5046  5102 E ReactNativeJS: { [ReferenceError: ReferenceError: Can't find variable: performance
05-01 12:42:07.458  5046  5102 E ReactNativeJS: 
05-01 12:42:07.458  5046  5102 E ReactNativeJS: This error is located at:
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in status_im.android.core.app_root (created by env.android.main.reloader)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in env.android.main.reloader
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in Unknown (at renderApplication.js:35)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:102)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:122)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in AppContainer (at renderApplication.js:34)] line: 60, column: 22 }
05-01 12:42:07.485  1446  1446 D SurfaceFlinger: duplicate layer name: changing im.status.ethereum/im.status.ethereum.MainActivity to im.status.ethereum/im.status.ethereum.MainActivity#2
```

**Comment by dmitryn** [comment]
`js/perfomance` is referenced by re-frame. We have re-frame 0.10.5 dependency in status-react while re-frisk-remote has re-frame 0.10.1 in deps.

For some reason `clj -R:repl build.clj figwheel android` compiles code with re-frame 0.10.1 https://github.com/Day8/re-frame/blob/v0.10.1/src/re_frame/interop.cljs#L41 and 
`lein figwheel-repl android` compiles code with re-frame 0.10.5 (where they added `(exists? js/perfomance)` check https://github.com/Day8/re-frame/commit/3b960ea5e9ca02a79c07f7e4c264fc93ac5ed5ca)

<blockquote><img src="https://avatars0.githubusercontent.com/u/3033386?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Day8/re-frame">Day8/re-frame</a></strong></div><div>re-frame - A Reagent Framework For Writing SPAs, in Clojurescript.</div></blockquote>
