### ISSUE TITLE
Clear invalid contact code error message [iOS]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4075]
### User Story

As a user, I don't want to see leftover error messages when I return to a previous screen.

### Description

*Type*: Bug

*Summary*: The error message for an invalid contact code does not clear if the user navigates away from the new chat screen without either deleting or correcting the code.

#### Expected behavior
Error message disappears once a user navigates to any other screen. 

On returning to the "Start new chat" screen, the contact code field should not display an error.

#### Actual behavior
[comment]: # 
When the user returns to the "Start new chat" screen, the error message still appears but the text has been cleared.

<img src="https://user-images.githubusercontent.com/15470435/39475299-0ac5d976-4d58-11e8-90af-43d13253692c.png" width="300">

### Reproduction
[comment]: # 

- Start new chat
- Begin typing any invalid contact code
- Go back OR to recent contact OR QR code
- Return to "Start new chat" screen 

### Additional Information
* Status version: Develop 2018-05-01
* Operating System: iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 340.00
Contract address: [0xed72214b751245a6cf506dc53684e2230273e1c6](https://etherscan.io/address/0xed72214b751245a6cf506dc53684e2230273e1c6)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
