### ISSUE TITLE
`JavascriptException: Migration is required due to the following errors` is shown after upgrading 0.9.17 to 0.9.18

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#4077]
### Description
The exception is shown only for Android. The app crashes on IOS after upgrading and the exception is not shown

*Type*: Bug

#### Expected behavior
An alert about excluded upgrade option from the release is shown, no crashes, user can create new account or recover the old one
![screenshot_2018-05-01-18-21-30](https://user-images.githubusercontent.com/12611990/39479070-daefe68c-4d6c-11e8-8bff-b4a400c48578.png)

#### Actual behavior
The error is shown, the app crashes if user taps on 'EXIT' bbutton
![screenshot_2018-05-01-17-52-38](https://user-images.githubusercontent.com/12611990/39477947-80f30144-4d69-11e8-9e8c-de01742f90ec.png)

### Reproduction
0.9.17 is installed, an account is created
upgrade 0.9.17 to [0.9.18 80a0bc](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-80a0bc.apk) version 

### Additional Information
* Status version: upgrade 0.9.17 to [0.9.18 80a0bc](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-80a0bc.apk)
* Operating System: Android and iOS

**Comment by antdanchenko** [comment]
@denis-sharypin please, create a text for alert message (the screenshot is in "Expected behavior") for the release 0.9.18

**Comment by denis-sharypin** [comment]
@chadyj  please help

**Comment by lukaszfryc** [comment]
@antdanchenko should we close it now?

**Comment by antdanchenko** [comment]
@lukaszfryc yep
