### ISSUE TITLE
No user avatar next to message bubble in 1-1 chat for contact who sends me a message  

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4078]
***Type***: Bug

***Summary***: User avatar is gone in 1-1 chat (near message bubbles) for a contact who sends me a message. 

#### Expected behavior
User avatar is present in 1-1 chat near message bubbles for a contact who sends me a message. 
<img width="253" alt="screen shot 2018-05-01 at 19 56 04" src="https://user-images.githubusercontent.com/8749671/39483146-249b61fa-4d7a-11e8-8d05-7796ea0ad292.png">

#### Actual behavior
User avatar is gone in 1-1 chat (near message bubbles) for a contact who sends me a message. 
<img width="390" alt="screen shot 2018-05-01 at 20 01 51" src="https://user-images.githubusercontent.com/8749671/39483291-8bf9eb50-4d7a-11e8-897a-3821884ebf7d.png">

### Reproduction

- Open Status on two devices and create two accounts (ContacA and ContactB)
- ContactA adds ContactB in contacts
- ContactB sends a message in 1-1 chat to ContactA
- ContactA checks ContactB's avatar next to message bubble he received

### Additional Information
* Status version: Develop (360th nightly build)
* Operating System:  Android and iOS

TF session: https://app.testfairy.com/projects/4803622-status/builds/8209535/sessions/58/?accessToken=yjxl5z4SbqoxpxGsIOiDaapAexs

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8209535/sessions/58/?accessToken=yjxl5z4SbqoxpxGsIOiDaapAexs">TestFairy: Status 0.9.16-59-gc145c8a1+ (2486) @58</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@Serhy I believe that's per design ( I made that change), @denis-sharypin ?

**Comment by denis-sharypin** [comment]
@Serhy  could you test it for group/public chats, please? `Expected:` for group/public chats we should have userpicks  of other participants (edited)

**Comment by Serhy** [comment]
Yes, that's how it looks now: Group and public chats display userpics of other contacts.
Great! Thanks, @denis-sharypin, @cammellos !

Closing this issue as expected!
