### ISSUE TITLE
Require payment to mail server before connecting to it (hidden under flag)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4080]
# Problem

Users want maximum uptime, reliability and security in messaging. By offering mail servers as a paid resource, we allow them to choose one of many competing providers that best satisfies their needs.

As part of an MVP for this, we want to ask user to send a transaction to the mailserver's address before they connect to it.

# Implementation

When a user selects a mail server under advanced settings, they should first be prompted with a transaction screen. This transaction screen should have have a prefilled amount, address and gas limit., and transaction should be in STT (Status test token).

For the purposes of this issue, all of this can be hardcoded to some reasonable numbers. Say 5 SNT, a template address like 0xdeadbeef, etc. Later on this information will come from the mailserver (wnode) data, but for now this can be bound in a sample let binding.

All this flow should be hidden under a feature flag, see issue linked to in notes.

The transaction id returned upon completion of the transaction should be saved as part of the `save-wnode` call. Example spec: `wnode/payment <unspecified-map>` (see `status-im.ui.screens.offline-messaging-settings.db`). I.e. something like: `wnode/payment {:tx-id <TXID>}`. The specifics of this data format will be specified at a later stage, so whatever gets the job done and is least specified works.

This transaction id will then be used in `request-messages` call to mail server as proof of payment (later issue).

If transaction doesn't go through, the user should not be able to choose that wnode.

The flow is thus:
Click mailserver -> Pay transaction screen -> Sign transaction -> Connect to wnode

# Acceptance Criteria

Rules for the future PR to be accepted.

- Prompt for payment upon connecting to wnode
- Save transaction id to wnode
- All behavioral changes hidden under a flag
- No change in behavior when flag is off

# Notes

- https://ideas.status.im/ideas/168-paid-master-nodes/README - also see notes on running a mail server and getting test STT
- https://github.com/status-im/status-react/issues/4003

# Future Steps

Steps which should be taken after this issue has been resolved.

- Issue for capturing data in wnode data structure
- Issue for intermediate screen(s), showing user what they are paying for, what happens next etc (UXR)
- Issue for request message with proof of payment

<blockquote><div>Status - Ideas</div><div><strong><a href="http://ideas.status.im/ideas/168-paid-master-nodes/README">Paid master nodes</a></strong></div><div>Swarm Home. New, completed and in-progress features for Status.</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x5980fd349902a4ba96c710532d99bd0ce53619b02d11bbce7ec21f8f377d38bd](https://etherscan.io/tx/0x5980fd349902a4ba96c710532d99bd0ce53619b02d11bbce7ec21f8f377d38bd)

**Comment by Coffee-Boyy** [comment]
I can start working on this issue :)

**Comment by oskarth** [comment]
Great @ConnorChristie! Let me know if you have any questions.

**Comment by Coffee-Boyy** [comment]
I do have one question, I am using the event from below to trigger the send transaction modal using an already filled out unsigned-transaction. My problem is that the event logic is using this id but I am unsure where that id gets generated and saved. Is there some way I can generate my own and save it?

https://github.com/status-im/status-react/blob/de03fc2d6a8619860ee9333a787345dae84bca37/src/status_im/ui/screens/wallet/send/events.cljs#L106-L118

**Comment by Coffee-Boyy** [comment]
@oskarth Okay so I got past that issue and it was because I was calling that handler with an unsigned-transaction instead of a send-transaction. I am however running into another wall with obtaining the transaction hash upon sending. web3 offers a callback which contains the hash but there is nothing handling that in the code currently. And the other time the hash is obtained is in the `sign-request-queued` method but since I am opening a modal, I am unable to pass any callbacks to either the web3 method or the sign-request-queued method...

Is there a strategy that would work in this case? Is there some way to listen for a db event and respond to that? Can I in-fact send a callback through to a modal? Thx!

**Comment by oskarth** [comment]
(Conversation kept going in PR, above seems to have been addressed)
