### ISSUE TITLE
Random name is shown instead of user settings

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4082]
### Description

*Type*: Bug

*Summary*: Custom name is not shown after i set up account. Random name is displayed

#### Expected behavior
User selected a name when setting up an account and status should show it in user profile

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/39510424-6241f3a2-4df2-11e8-8c98-541df7991efe.png)

### Reproduction

- Open Status
- set up account and enter any name u like
- go to profile

### Additional Information
* Status version: nightly 361
* Operating System: Android, iOS

**Comment by Serhy** [comment]
Fixed in 362nd nightly builds (Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-2c7063.apk
 iOS: https://i.diawi.com/FPpc1g)

#4084 PR fixed the issue.

<blockquote></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/FPpc1g">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rachelhamlin** [comment]
@Serhy @asemiankevich is it expected that the user's display name should show when they are added as a new contact? 

I have created a user with display name "Rachel."

When I add this user as a contact from any other account, the contact appears as "Portly Cute Malamute"—but has the same user pic.

**Comment by Serhy** [comment]
@rachelhamlin could you clarify please this part: `- but has the same user pic`. You mean this contact has **default** userpic or the one which was **set by you**?

For this moment the logic of revealing contact names and userpics is next:
1) You and me have a contact with the non-default username and userpic.
2) You want to chat me and send a request following by text message. However until I "share" my details to you (via 'Add to contacts' button in 1-1 chat) you see me with the default username and userpic. But I want to know who is going to message me - so on my side your contact name and userpic are revealed (i.e. non-default)
3) I add you to my contacts and you see my "real" name and avatar.

So it is expected that non-default contact name and userpic of other contacts are shown to me when other contacts are sending me a contact request.
It is not expected that one of two - contact name or userpic - is shown as non-default but another with the default value.
