### ISSUE TITLE
Set tribute to talk [UI]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4087]
### User Story

As a user, I want to set a minimum "tribute" required for non-contacts to send me a message, so that I can block spam and monetize my attention.

### Description

*Type*: Feature

*Feature summary*:
See [#096 Tribute to Talk idea](https://github.com/status-im/ideas/pull/165) for context.

All users will have a "Tribute to talk" setting on the profile screen. 

On a user's first run, the setting is highlighted as NEW and leads to an explainer screen. The user can then input some amount of SNT, set the tribute and receive confirmation.

On later runs, the setting is displayed with the user's existing tribute. "NONE" if no tribute is set.

If an amount is set, the user can Edit or Remove the tribute. 

*Implementation*:
The scope of this issue is to code the UI only. Values can be hard coded and the button mocked.

### Mockups
Logic in [InVision Prototype](https://invis.io/7GHQDUSFYTD)
Mockups in Zeplin — https://zpl.io/amDRxl3
(please provide your email to be added to Zeplin project)

#### First Run
![requester flow](https://user-images.githubusercontent.com/6559881/39709183-782d751c-5219-11e8-9a00-92786769b847.jpg)

#### Tribute Set
<img width="843" alt="screenshot 2018-05-07 12 20 45" src="https://user-images.githubusercontent.com/6559881/39697408-20e6f832-51f1-11e8-9fda-6493f5d9e20f.png">

#### Additional Information

[TtT contract documentation](https://github.com/status-im/contracts/blob/096-tribute-to-talk/TributeToTalk.md#contract-deployment)

**Comment by flexsurfer** [comment]
@denis-sharypin why xl? The scope of this issue is to code the UI only.

**Comment by denis-sharypin** [comment]
@flexsurfer okay, I thought there too many screens for  `m` bounty

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xea0543fc20853b1e52001a467ab589c0e661bb0c8955c74cbe970e16d3956c23](https://etherscan.io/tx/0xea0543fc20853b1e52001a467ab589c0e661bb0c8955c74cbe970e16d3956c23)

**Comment by georgiemathews** [comment]
@rachelhamlin I'll take a look at this, could you add my email: georgie@nud.ge

**Comment by rachelhamlin** [comment]
@georgiemathews awesome! @denis-sharypin can you please add Georgie to Zeplin?

**Comment by denis-sharypin** [comment]
@georgiemathews invite sent!
