### ISSUE TITLE
Localize currency according to selected currency

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4099]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see currency in the selected format so that it looks correct and readable.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

*Summary*: Users can now set their desired currency in https://github.com/status-im/status-react/issues/4008 but Status doesn't show the selected currency according to localized display conventions.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The fiat currency should be displayed as per the selected currency conventions. Eg
USD: $7.89 ($ symbol, 2 decimal places, period as decimal separator)
JPY:   ‎¥83 ($ symbol, no decimal places)

#### Actual behavior
[comment]: # (Describe what actually happened.)

1.  USD isn't shown consistently with 2 decimal places. Eg Status inconsistently shows 15 (no decimal places), 15.1 (1 decimal place) or 15.13 (2 decimal places).
2. Currency without decimal places such as JPY are incorrectly shown with decimal places like 150.05
3. Wallet "total value" doesn't show the currency symbol, but the fiat value of assets do. We should be consistent, and also show the currency symbol in the correct position.

### Additional Information

The solution should not introduce additional dependencies.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 680.00
Contract address: [0xc17f277483d7e84f896b7732bc3aff673ab7a624](https://etherscan.io/address/0xc17f277483d7e84f896b7732bc3aff673ab7a624)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
Hi @chadyj , fix for this posted at https://github.com/status-im/status-react/pull/4176   :beers: 

![issue4099_screenie](https://user-images.githubusercontent.com/19371062/39842182-0c6dfbfe-53d5-11e8-8d17-14ce823a93c2.png)
![issue4099_screenie2](https://user-images.githubusercontent.com/19371062/39842187-10af3732-53d5-11e8-920e-a15967c586a6.png)

**Comment by chadyj** [comment]
That's awesome @pacamara! What a nice surprise to see that :)

**Comment by pacamara** [comment]
@chadyj You're welcome! 💯
