### ISSUE TITLE
Submit Annual Self Classification Report to BIS

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4102]
### User Story

As a company, I want to file with BIS so that the iOS App store encryption requirements are satisfied.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Chore

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Apple [requires](https://help.apple.com/itunes-connect/developer/#/dev88f5c7bf9) export compliance for apps using encryption in order to submit to the App Store.

Background questions, answers, comment, and info in[ this doc](https://docs.google.com/document/d/1-BnTpeBGaqX17ogBe2Gn5WGe_UaCcBkrzpo3QIaKnU8/edit?usp=sharing).

<img width="565" alt="screen shot 2018-05-04 at 9 56 33 am" src="https://user-images.githubusercontent.com/116099/39617816-716870c8-4f81-11e8-8da3-0f5da0a9ac52.png">

### Solution

- [Submit an annual self-reporting compliance submission with BIS](https://www.bis.doc.gov/index.php/policy-guidance/encryption/4-reports-and-reviews/a-annual-self-classification)

### Other

Similar to https://github.com/status-im/status-react/issues/4109

**Comment by chadyj** [comment]
Done. 
Emailed crypt-supp8@bis.doc.gov and enc@nsa.gov a CSV with application details.
This needs to be done annually.

**Comment by ijm700** [comment]
can you post an example of how your CSV looked like ?

**Comment by chadyj** [comment]
You can grab it from here https://www.bis.doc.gov/index.php/policy-guidance/encryption/4-reports-and-reviews/a-annual-self-classification

> First line of the annual self-classification report must consist of the following 12 entries: PRODUCT NAME, MODEL NUMBER, MANUFACTURER, ECCN, AUTHORIZATION TYPE, ITEM TYPE, SUBMITTER NAME, TELEPHONE NUMBER, E-MAIL ADDRESS, MAILING ADDRESS, NON-U.S. COMPONENTS, NON-U.S. MANUFACTURING LOCATIONS.

<blockquote><img src="/templates/allrounder-3/favicon.ico" width="48" align="right"><div><strong><a href="https://www.bis.doc.gov/index.php/policy-guidance/encryption/4-reports-and-reviews/a-annual-self-classification">a. Annual Self-Classification</a></strong></div></blockquote>

**Comment by HuguesRousseau** [comment]
The link for the sample does not exist anymore. Does anyone have an example to share?

**Comment by ijm700** [comment]
@HuguesRousseau luckily I downloaded a copy last month, does anyone know when the deadline is for this ?
[Sample Annual Self Classification Report.xlsx](https://github.com/status-im/status-react/files/2683866/Sample.Annual.Self.Classification.Report.xlsx)

**Comment by HuguesRousseau** [comment]
I found it was before Feb 1 of the following year: https://www.bis.doc.gov/index.php/policy-guidance/encryption/4-reports-and-reviews/a-annual-self-classification

<blockquote><img src="/templates/allrounder-3/favicon.ico" width="48" align="right"><div><strong><a href="https://www.bis.doc.gov/index.php/policy-guidance/encryption/4-reports-and-reviews/a-annual-self-classification">a. Annual Self-Classification</a></strong></div></blockquote>

**Comment by HuguesRousseau** [comment]
@Izzyjm The file helps. One thing I am missing though is that for NON U.S. Component it says NO but the non U.S. manufacturing location example is in China. I would have thought that if there are non US manufacturing location, then there must be non US Component, so it should be YES. Am I missing something.

**Comment by ijm700** [comment]
thats weird to be honest im not sure I think i would also need clarification on that to

**Comment by ijm700** [comment]
I wonder if we use a framework like for example (InMobi Ads) which i think is developed in india do we have to select yes for 'non U.S manufactoring location' ?

**Comment by ijm700** [comment]
hey @chadyj  did you ever hear back from them after sending your email?

**Comment by anonym24** [comment]
@Izzyjm 

so should we put `NO` or `YES` for `NON U.S. Component`? if `non U.S manufacturing location'` is set not to USA?

**Comment by anonym24** [comment]
> With respect to your company's encryption products, do they incorporate encryption components produced or furnished by non-U.S. sources or vendors? Enter 'YES', 'NO', or if necessary, 'N/A' (250 characters or less).

Well it just means if encryption was developed by non-US company.

You can put `NO` because HTTPS was developed by US company: 

> Netscape Communications created HTTPS in 1994 

https://en.wikipedia.org/wiki/HTTPS#History

**Comment by matte5031** [comment]
Hey guys, I just sent this classification report. Do I need to wait for a reply from them now or? If so how long time does it take for them to reach back to you? asking since apple wants you to attach that they approved it I guess, I can't just move on right after I sent it right?

"you must submit a copy of your U.S. Commodity Classification Automated Tracking System (CCATS) approval from the U.S. Bureau of Industry and Security (BIS)."

**Comment by hellocaio** [comment]
hey @matte5031, same here, I emailed the document to them days ago, and now what? Did you figure it out?

**Comment by matte5031** [comment]
@ColdTuna yes I did, they will not answer you. When answering the questions where you add the export compliance on the itunes connect there is a question where you're supposed to answer no instead of yes, or the opposite, don't remember and don't have it open. There you aknowledge that you have sent the documents to BIS and that you will do so yearly. In other words you don't need to upload any document with the approval to apple anymore.

**Comment by NikkotheAIDEV** [comment]
If I'm individual I should write `SELF` under `MANUFACTURER`, right? Also `SUBMITTER NAME` should be the same as the name on my Apple Developer Account, right?

**Comment by artymis** [comment]
My app makes three https calls to a web service so I've had to jump through this hoop too.  I'm not 100% sure all my fields are correct, but if it helps, here's what I've put in my Self Classification Report:

[App Name], [AppSku], SELF, 5D992, MMKT, Mobility and mobile applications n.e.s., [My Name], [My Telephone], [My Email], [My Address], No, N/A
