### ISSUE TITLE
Error calling RCTEventEmitter.receiveEvent when tap on emoji from predictive text panel

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4103]
***Type***: Bug

***Summary***: `java.lang.RuntimeException: Error calling RCTEventEmitter.receiveEvent` error followed by the app crash appear when contact taps the emoji from auto-correction suggestions. Note - it should be a single emoji in auto-correction, it's all OK for text+emoji

#### Expected behavior
No errors when contact taps the emoji from auto-correction suggestions. Emoji appears in message box

#### Actual behavior
`java.lang.RuntimeException: Error calling RCTEventEmitter.receiveEvent` error followed by the app crash appears when contact taps upon emoji from auto-correction suggestions
<img width="389" alt="screen shot 2018-05-04 at 11 31 11" src="https://user-images.githubusercontent.com/8749671/39618967-b179f3f0-4f8e-11e8-9f24-5e2a64024943.png">

### Precondition
You may need to create auto replacement for text by emoji on Android if you don't have any.
For Android 6, for example, it could be done navigating to device `Settings` -> `Language and input` -> `Keyboards` -> `Text shortcuts` -> `Add` and add a text you want to be replace by replacement (e.g. Shortcut='Hello' and Expanded phrase = [Emoji symbol you wish to be replaced by]
Also `Predictive text` option setting should be turned on on the keyboard.

### Reproduction

- Open Status and create an account
- Navigate to any type of chat (e.g. join public chat `predictemoji`)
- In message box type the text you are about to replace by emoji
- Send the text message (Note: auto replacement area with the emoji keep stay)
- Tap on emoji from predictive text

### Additional Information
* Status version: Develop, Release 0.9.17 / 0.9.18
* Operating System: Android

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8227614/sessions/20/?accessToken=pQJq1uPWXf0Ox4ksujA2BAtPwzE

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8227614/sessions/20/?accessToken=pQJq1uPWXf0Ox4ksujA2BAtPwzE">TestFairy: Status 0.9.16-79-gca809264+ (2506) @20</a></strong></div></blockquote>

**Comment by yenda** [comment]
Potatoe bug

(easier to search later)

**Comment by yenda** [comment]
This is a react-native issue, we have to wait for a fix https://github.com/facebook/react-native/issues/18405

**Comment by yenda** [comment]
The PR to follow for a fix https://github.com/facebook/react-native/pull/18443

**Comment by yenda** [comment]
Moved to post-beta as this is unlikely that we can solve this bug before beta since it requires a PR to be merged in react-native and a release of react-native

**Comment by Serhy** [comment]
I can not reproduce this issue anymore!
