### ISSUE TITLE
Generate realm serializers at macro expansion time

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#4106]
### User Story

As a developer, I want write access to realm to be efficient.
### Description

*Type*: Feature

Clojure objects are being stored in realm as JS objects transformed via `clj->js`.

As we have access at compilation time to schemas describing the shape of data stored in realm, this can be optimized.
Create a macro that will generate optimized `realm` serializer per type. Those will then be cached and used to write realm objects.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x273c594f0b3cb79df5678b33bfaca468563ef8c766beff8482aeed58f75e3184](https://etherscan.io/tx/0x273c594f0b3cb79df5678b33bfaca468563ef8c766beff8482aeed58f75e3184)

**Comment by pablanopete** [comment]
@jeluard is this issue still relevant? Will be revoking the bounty in any case but checking where to keep the issues in our SOB project board for future bounties.

**Comment by jeluard** [comment]
@pablanopete Let's close it for now
