### ISSUE TITLE
Reformat project code according to community style guide

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#4107]
### Description

Often new PR contains formatting changes (code indent) which are not related to the new functionality, but have to be committed because the editor auto formats the code. This heavily distracts reviewers and takes more time to review the actual changes in PR.

### Solution

Reformat code according to https://github.com/bbatsov/clojure-style-guide
Use Cursive/Emacs "Reformat code" to recursively format all the code in status-react. 

<blockquote><img src="https://avatars0.githubusercontent.com/u/103882?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/bbatsov/clojure-style-guide">bbatsov/clojure-style-guide</a></strong></div><div>clojure-style-guide - A community coding style guide for the Clojure programming language</div></blockquote>

**Comment by jeluard** [comment]
@dmitryn We should consider how to enforce this automatically with a GH bot.

**Comment by dmitryn** [comment]
@jeluard yes. Once we have all the code correctly formatted, we can enable automatic code quality check for each PR.

**Comment by dmitryn** [comment]
This is already done by @rasom Could be closed
