### ISSUE TITLE
Allow user to remove custom avatar

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4108]
### Description

*Type*: Bug

*Summary*: As a user i want to be able to remove my custom avatar (photo) and restore it to default.

#### Expected behavior
User is able to revert avatar to default one that was created with the account. @denis-sharypin is it possible to add some design?

#### Actual behavior
Once avatar is changed to picture or photo user is not able to restore the default value 

### Reproduction
- Open Status
- Tap profile
- Tap edit 
- Change avatar and save

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 650.00
Contract address: [0x8604629a0ad472a33ce14311490751e9907dc968](https://etherscan.io/address/0x8604629a0ad472a33ce14311490751e9907dc968)
Network: Mainnet
Paid to: 751895405
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by denis-sharypin** [comment]
1. If the user has a custom user picture she will see a context menu where on top of the list she has `Remove current photo` option  (on the right)

2. If the user doesn't have a custom picture or she deleted it once she opens this menu again she will see our current context menu. (on the left)

![remove current photo](https://user-images.githubusercontent.com/6559881/37643828-63060bf8-2c54-11e8-8adf-23ed02a1f53c.jpg)

**Comment by pablanopete** [comment]
Message sent about payment.

**Comment by 751895405** [comment]
@pablanopete thank you send me message and my wallet address: 0x39e494fb02764904a9d89d70a149d19331654e21
