### ISSUE TITLE
Improve chat autoscroll function

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4110]
### User Story

As a user i want to have better experience with chats. 

### Description

*Type*: Bug

*Summary*: When i am in the middle of any chat (1x1, group or public) like i am reading history for example and new message arrives to this particular chat - there is an autoscroll function that scrolls the chat for 1 message down (if 1 new was received). I find this confusing to me comparing to other messengers.

#### Expected behavior

1. chat is scrolled down right after new message arrived. This could be annoying as i want to continue reading history for example, app should not force me to read new messages

2. chat is not scrolled at all when new message arrives, but a notification shown (like a banner) saying `you have 2 unread messages` with dynamic counter (or without counter). the banner is clickable and directs me right at the bottom of the chat when i tap it. The banner does not prevent me from reading history or scrolling chat (like Viber or Skype does).

@denis-sharypin @chadyj please advise

### Reproduction

- Open Status on 2 devices
- Create 1x1 chat with those 2 devices
- Text ~30 messages in chat so user has history
- On 1 device scroll the history to somehwere in the middle
- On 2 device text new message to this chat
- Pay attention to the device 1

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by t1MZXxBn6pAAtTqKTy5UotdeMqBw2CfGrUF** [comment]
I hope this issue gets resolved soon!

**Comment by pablanopete** [comment]
Is this still relevant? Seems to be solved already @asemiankevich?

**Comment by asemiankevich** [comment]
@pablanopete i think it is still relevant

**Comment by chadyj** [comment]
The issue may be better captured here https://github.com/status-im/status-react/issues/4690 and WIP here https://github.com/status-im/status-react/pull/5665

**Comment by asemiankevich** [comment]
@chadyj okay then close this one !
