### ISSUE TITLE
browsing https://app.wandx.co shows blank page

### ISSUE THREAD

**Issue by amitmaurya** [status-im/status-react#4115]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a <user|developer|...>, I want to <task> so that <goal>.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: browsing https://app.wandx.co shows blank page on status android beta app with no error message. https://app.wandx.co is fully responsive app.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
https://app.wandx.co should open without any issue.

<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by flexsurfer** [comment]
dapp is trying to call `eth_coinbase` sync, but we dont' support sync calls

**Comment by rachelhamlin** [comment]
Same thing in iOS.

**Comment by flexsurfer** [comment]
will be fixed here https://github.com/status-im/status-react/issues/3823
