### ISSUE TITLE
Make current user grayed-out from /send and /request suggestions in group chats

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4122]
### User Story

As a user in a group chat i won't request or send any funds to myself as this makes no sense. 

### Description

*Type*: Bug

*Summary*: in a group chat when calling `/send `or `/request` message make current user graded out and not tappable

#### Expected behavior
Being in a group chat i should not be able to select myself from suggestions when calling `send` or `request` commands

#### Actual behavior
I can select myself from suggestions in a group chat

![image](https://user-images.githubusercontent.com/28752642/39693609-4614e69a-51ed-11e8-824e-a20d913c0a22.png)

![image](https://user-images.githubusercontent.com/28752642/39693621-4f50a83e-51ed-11e8-9c9c-559316a210bb.png)

### Reproduction

- Open Status
- Create group chat
- call `send` and `request` commands 
- pay attention to suggestions shown

### Additional Information
* Status version: nightly 367
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
Maybe let's make a bounty of it?

**Comment by asemiankevich** [comment]
@lukaszfryc vote! )

**Comment by lukaszfryc** [comment]
Just voted :) 

Btw, alternatively to graying out we could just remove it from Recipient list. I think it would be more clear solution than graying out.

**Comment by asemiankevich** [comment]
it intersects with the bug that fixed all members presence in a group chat

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe1ed82ffab5bdeefaf258dc8d3f1189be0e4b83b7ee75e366c34ee8cf32ddabd](https://etherscan.io/tx/0xe1ed82ffab5bdeefaf258dc8d3f1189be0e4b83b7ee75e366c34ee8cf32ddabd)

**Comment by pablanopete** [comment]
@asemiankevich / @chadyj is this any longer relevant? Will revoke + close if not.

**Comment by chadyj** [comment]
We don't have group chats, so can be closed.
