### ISSUE TITLE
Sign In button is shown when recovering account (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4127]
### Description

*Type*: Bug

*Summary*: When  i recover my account on android, after i enetered passphrase and password and tapped `Sign In` - this `Sign In` button is shown for several seconds (not less then 3) so I am able to multitap it and this produces bugs https://github.com/status-im/status-react/issues/4105 and https://github.com/status-im/status-react/issues/4126

#### Expected behavior
When i tap `Sign In` i want the screen to be changed to `Signing you in` and sign in button is no longer available (same as on iOS). 

#### Actual behavior
Sign in button is available for multitap 

![image](https://user-images.githubusercontent.com/28752642/39696760-61ad5e28-51f7-11e8-953f-62db204e3e3f.png)

### Reproduction
described in https://github.com/status-im/status-react/issues/4105 and https://github.com/status-im/status-react/issues/4126

### Additional Information
* Status version: nightly 367
* Operating System:Android

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 650.00
Contract address: [0x3f06a4102f992200b05af74469743cdefa399332](https://etherscan.io/address/0x3f06a4102f992200b05af74469743cdefa399332)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
