### ISSUE TITLE
Upgrade Instabug to 2.12.0

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4128]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer and tester, I want to see [crash reports](https://instabug.com/crash-reporting) so that I can debug crashes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

*Summary*: Instabug v2.12.0 now has [crash reporting](https://instabug.com/crash-reporting) which can be useful for debugging

#### Expected behavior

Instabug version is 2.12.0

#### Actual behavior

Instabug version is older

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 340.00
Contract address: [0xd5a3ea2ddb15e0a24b7b97f5437edca72f4a974b](https://etherscan.io/address/0xd5a3ea2ddb15e0a24b7b97f5437edca72f4a974b)
Network: Mainnet
Paid to: debragail
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by debragail** [comment]
https://github.com/status-im/status-react/pull/4140

**Comment by oskarth** [comment]
@mandrigin @PombeirP @dmitryn @chadyj @rachelhamlin Since this is a beta blocker, maybe it makes sense to push to do this ourselves? Last update was in PR 5d ago. Does either mobile or chat team have bandwidth for this?

**Comment by pedropombeiro** [comment]
I have taken a couple of quick stabs at doing this, without any luck so far. I don't see the crash handler getting called when reproducing https://github.com/status-im/status-react/issues/4205. Maybe someone else will have better luck.

**Comment by oskarth** [comment]
How much of a blocker is it really? Maybe it makes sense to remove it from critical path.

**Comment by mandrigin** [comment]
If crash reports don't work, it makes sense to fix it. Otherwise, I don't see it is being a blocker.

**Comment by pedropombeiro** [comment]
Decided to take another stab at this and noticed that the reason Instabug crash reporting wasn't kicking in is that the location where https://github.com/status-im/status-react/issues/4205 crashes doesn't seem to be handled by Instabug (that's a separate issue). I'll focus on just making crash reporting work correctly with an injected exception and then we can open a new issue for ensuring that browser navigation crashes are caught by Instabug.

**Comment by dmitryn** [comment]
@PombeirP i was testing manual exception reporting and it seems working https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/crashes

when using `Instabug.reportJSException(error);`

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/crashes">Login | Instabug</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
@dmitryn do you mean the #4205 crash appears there? By the way, I was expecting to see it in the #instabug Slack channel. I don't think the creds for Instabug dashboard are on LastPass.

**Comment by dmitryn** [comment]
@PombeirP not the #4205 as it seems native exception, only JS exceptions got caught by https://github.com/status-im/status-react/blob/develop/src/status_im/utils/error_handler.cljs#L52 where i placed `Instabug.reportJSException(error)` call. 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by pedropombeiro** [comment]
Will try to see if I can get it to report native exceptions as well, since that would be a shame if we didn't get detailed reports for those as well.

**Comment by chadyj** [comment]
Any progress here?

I'd like to see this included in the beta because we don't have a way to measure app crashes, and without this metric we don't have insight into app reliability. Chat reliability is a P0 OKR so being able to measure app and chat-related crashes is important.

From the data we do have on the Play store I see that we've had over 730 crashes in the last 30 days on Android (for users that opt-in to share), and has increased 130% over the previous period. It seems crashes are a big issue impacting most users, and something we should address.

**Comment by dmitryn** [comment]
Instabug needs to be updated to 2.12.0 to make Surveys work https://github.com/status-im/status-react/pull/4571
As for crash reporting, i'm still waiting for response from Instabug support as we don't have access to their android code to check what is happening (closed source)

**Comment by chadyj** [comment]
Fixed in https://github.com/status-im/status-react/pull/4649

**Comment by dmitryn** [comment]
I can see crash report here https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/crashes/2

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/crashes/2">Login | Instabug</a></strong></div></blockquote>
