### ISSUE TITLE
Red screen :ssh-post-error

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#413]
discovered while reviewing #412 

- copied my own public key and went to add contact
- removed last character and added 7
- pressed tick, get red screen
- tried again but says contact was added, so instead use a 9
- red screen appears
- now this just seems to happen whenever i open application.
![2016-11-03 13_18_16](https://cloud.githubusercontent.com/assets/2714786/19956471/07f771ba-a1c8-11e6-969d-da8fbcaedf6b.gif)

**Comment by jarradh** [comment]
hmm after a `rm -rf node_modules && lein deps && npm install && ./re-natal deps` this seems to have disappeared ?

**Comment by rasom** [comment]
If it happens when you reload app seems that it is related to some data in the database, so you rather need to clean local data
