### ISSUE TITLE
Update Request transaction message on the recipient side 

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#4136]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have a more clear action to respond to incoming requests.

### Description

*Type*: Improvement

#### Expected behavior

I would like to use a more obvious button to interact with.

<img width="464" alt="screenshot 2018-05-07 16 18 53" src="https://user-images.githubusercontent.com/6559881/39706686-78469558-5212-11e8-8bd9-2c45a2c6ab0b.png">

#### Actual behavior

<img width="470" alt="screenshot 2018-05-07 16 18 47" src="https://user-images.githubusercontent.com/6559881/39706696-82cd274e-5212-11e8-8485-0088e3cfe3d8.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create a chat
- Get a transaction request from a requester

### Solution

-  Delete icon with arrows and animation 
- Add `Send` button

After implementation of this https://github.com/status-im/status-react/issues/4012
`Send` button should open wallet screens

### Additional Information

* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xdc0ad003f73299d1c5828d5f8a948b205be2d73d1ab19163d8624907df7b0655](https://etherscan.io/tx/0xdc0ad003f73299d1c5828d5f8a948b205be2d73d1ab19163d8624907df7b0655)

**Comment by denis-sharypin** [comment]
was fixed here https://github.com/status-im/status-react/issues/4415
