### ISSUE TITLE
Messages marked as sent but not delivered

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#4139]
### Description

Messages are marked as sent but none of the peers nor the mailserver receives them.
Basically I was posting in a public chat and seeing my own posts but no one was receiving them.

#### Expected behavior

A message marked as sent is actually sent.

#### Actual behavior

Messages are marked as sent but never delivered to peers.

### Steps to replicate

Unfortunately I can't replicate at will

### Additional Information

At some point the app got in a state it could not recover from:

- Messages were marked as sent but none of the peers nor the mailserver was receiving them.
- No error was shown in the UI.
- During this time I would see a `receive-whisper-message` with my own message.
- Internet connection was up.
- Pulling historical messages from the mailserver was working.

Restarting the app fixed the problem.

**Comment by dshulyak** [comment]
Closed by https://github.com/status-im/status-react/pull/4285
