### ISSUE TITLE
Airswap Dapp can't be used in Status

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4145]
### User Story

As a user, I want to use Airswap so that I can trade tokens.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: [Airswap](https://www.airswap.io/trade) is a decentralized token marketplace with SNT featured as one of its 24 tokens, but it doesn't work within Status. Fixing this would be useful for Status users to buy/sell SNT and other tokens.

#### Expected behavior
Buying and selling SNT works in Status

#### Actual behavior
Doesn't work.
After tapping sell and signing the message the page refreshes.

### Reproduction
In Status, 
- go to https://www.airswap.io/trade, 
- select SNT, then Sell.
- Sign the message
- Can't continue

![2018-05-08 10_42_57](https://user-images.githubusercontent.com/116099/39747101-9cb45084-52ac-11e8-8444-898f17d0399a.gif)

### Additional Information

Tested in Metamask and other mobile Dapp browsers and it worked as expected.

<blockquote></blockquote>

**Comment by flexsurfer** [comment]
yeah weird behaviour , i can see metamask logo, and sometimes i can see the screen after sign in, for couple of seconds, but nothing special, no errors or something, but page is not refreshed for me, i just see sign in button again, some internal logic of dapp

**Comment by asemiankevich** [comment]
same behavior to me as @flexsurfer described, iPhone 7

**Comment by flexsurfer** [comment]
can't repro anymore with latest nightly
