### ISSUE TITLE
Issue signing Dapp Messages

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4149]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to sign messages so that I can use Dapps.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is an error when trying to use dapps and sign messages. When tapping `sign` or `cancel` there is a spinner then the Dapp/page refreshes.

#### Expected behavior

Can sign Dapp messages

#### Actual behavior

A spinner is shown and the page refreshes.

### Reproduction

- In Status go to https://status-im.github.io/dapp/
- Tap Transactions
- Tap sign message
- Sign the message. 
- A spinner should be shown before reloading the `accounts` page

![signing-refresh](https://user-images.githubusercontent.com/116099/39747453-9df9dd0a-52ad-11e8-9a88-99ccb1c4bff4.gif)

### Additional Information

iOS
Nightly
Iphone X

<blockquote><div><strong><a href="https://status-im.github.io/dapp/">DAPP</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@chadyj cant repro it with my iPhone7

**Comment by Serhy** [comment]
Apparently, it's the same what happened in https://github.com/status-im/status-react/issues/3342

**Comment by flexsurfer** [comment]
yes, i can reproduce it on iPhoneX simulator
