### ISSUE TITLE
Slow UI re-appearance and blinking message decorators

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#415]
After sending the password message, there is a significant delay  (3-4 seconds) and the messages just instantly appear (as opposed to animating up).

After this the message decorators disappear only to reappear again.

Also Console dapp icon in top right is missing until this message decorator 'flash'

![2016-11-03 13_48_36](https://cloud.githubusercontent.com/assets/2714786/19956938/87a23572-a1cc-11e6-8fd6-4d162a98746c.gif)

**Comment by rasom** [comment]
```
After sending the password message, there is a significant delay (3-4 seconds)
```
We have to wait for a newly created account to show the message with mnemonic passphrase and seems that account creation (with all that `js->java->go->java->js` communication) is not instant. 
Don't know how we can fix this on `status-react` side

**Comment by alwx** [comment]
Can't we add a message like "Wait a sec, we're creating your account..." immediately right after user submit a password?

**Comment by rasom** [comment]
Yes, this can be done.

**Comment by alwx** [comment]
It is just an idea, of course. Maybe there is something better we can do.

**Comment by jarradh** [comment]
Thats not a bad idea!

I think the problem is that the next 3 messages jaggedly appear instantly, that in combination with the only other animation indicator (the throbbing of the response icon stops) gives the impression that the entire application froze then 'caught up'.

Also whats with the message icons disappearing?

Both of those glitches gives off a flimsy feeling
