### ISSUE TITLE
Broken layout after app was closed using back button and opened again 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4163]
### Description

*Type*: Bug

*Summary*: In some cases, when app is closed by pressing back button and then opened again, the layout is broken. Also, when I click on the screen Android App Info (Android Settings) app is opened. The only way to get out of it is to kill the app and open it again. 

<img src="https://user-images.githubusercontent.com/7532782/39807017-9571b51c-537b-11e8-9154-9e9037d39841.png" width="200">

Another example:

<img src="https://user-images.githubusercontent.com/7532782/39807029-a00e9ac6-537b-11e8-8621-6c7c4394ab61.png" width="200">

#### Expected behavior
App is restored to the most recent screen when it's opened from the background.

#### Actual behavior
When app is opened from the background, the layout is broken and any click opens Android Settings app.

### Reproduction

- Open Status on Android
- Go to Profile
- Click share contact code
- Press device back button and exit the app
- Open list of apps in the background and restore Status  

### Additional Information
* Status version: nightly, May 9
* Operating System: Android
* It does not happen every time back button is pressed. I.e. closing the app by pressing back button in Home screen works fine

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb2f6cab3caa572c6ecb4c7dd40c391de4a1d7048b03ed0e2c9e12c461b25acea](https://etherscan.io/tx/0xb2f6cab3caa572c6ecb4c7dd40c391de4a1d7048b03ed0e2c9e12c461b25acea)

**Comment by pablanopete** [comment]
@lukaszfryc has this issue been resolved?

**Comment by lukaszfryc** [comment]
@pablanopete yes
