### ISSUE TITLE
Forward browsing button stay disabled after navigation to previous page in app browser [Android]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4167]
***Type***: Bug

***Summary***: If often happens in the app browser for Dapps/websites when contact navigates to the previous page via 'Back' browsing button the 'Forward' browser button stays inactive. On the same site/Dapp it may work the first time but fail to work on next try following the same steps.
It's OK for iOS but on Android it's often occurs

#### Expected behavior
`Forward` button in the app browser is active and upon tap it redirects to screen where contact has been  prior tap on 'Back' browsing button

#### Actual behavior
`Forward` button in the app browser is inactive after contact navigated to the previous screen via 'Back' browsing button

### Reproduction 2

- Open Status and create new account
- Navigate to '+' -> `Open Dapp` -> `Auction house` -> `Open`
- Tap `Create auction`
- Tap `Back` browser button
- Tap `Forward` browser button

### Reproduction 1

- Open Status and create new account
- Navigate to '+' -> `Open Dapp` -> type www.wikipedia.org -> `Open`
- Tap `Create auction`
- Tap `Back` browser button
- Tap `Forward` browser button

### Additional Information
* Status version: Develop, release 0.9.17 / 0.9.18
* Operating System: Android (6.0 / 7.1 / 8.0 checked)

#### Logs
TF session for Auction house scenario: https://app.testfairy.com/projects/4803622-status/builds/8248083/sessions/15/?accessToken=vryN4dSmgdZ0fvA/NGv7bv2uBrU
TF session for wikipedia scenario: https://app.testfairy.com/projects/4803622-status/builds/8248083/sessions/18/?accessToken=bUqNK7P7ka7iq4pAj1/rdE1HTmg

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8248083/sessions/15/?accessToken=vryN4dSmgdZ0fvA/NGv7bv2uBrU">TestFairy: Status 0.9.16-91-gdc4e1569+ (2518) @15</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8248083/sessions/18/?accessToken=bUqNK7P7ka7iq4pAj1/rdE1HTmg">TestFairy: Status 0.9.16-91-gdc4e1569+ (2518) @18</a></strong></div></blockquote>

**Comment by churik** [comment]
reproducible on [release build 18](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-f62e7d-rel.apk)

**Comment by flexsurfer** [comment]
@Serhy should be fixed?

**Comment by Serhy** [comment]
Indeed, @flexsurfer, it's not an issue anymore.
Closing.
