### ISSUE TITLE
Disable testnets in Status Beta 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4173]
### Description

*Type*: Feature

*Summary*: Status Beta should only work in Mainnet network. So, for release builds with development mode turned off the network settings screen should only contain mainnet. Debug (nightly) builds and release builds with dev mode on should still have testnets.

#### Expected behavior
Status Beta relase in development mode = off build should only have mainnet networks.

#### Actual behavior
Network list includes testnets

### Additional Information
* Status version: Status Beta
* Operating System: Android, iOS

**Comment by ConnorChristie** [comment]
Are beta users going to want to use the app strictly on the mainnet? Without a proper security audit and lots of testing on testnets, I myself would be scared to use the app with any value on the mainnet especially in beta.

**Comment by oskarth** [comment]
@lukaszfryc do you know if any team is aware of this? Mobile-team perhaps? cc @mandrigin

**Comment by lukaszfryc** [comment]
Yes, it will be done by Mobile Client Team
