### ISSUE TITLE
Handle Discovery V5 signals in the client

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4177]
Impact: Reliability

Effort: Medium

Signals to implement in the client: https://github.com/status-im/status-go/tree/develop/geth/peers

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by oskarth** [comment]
cc @PombeirP @adambabik

**Comment by oskarth** [comment]
Unclear to me right now at what point this will provide utility for end users, but I assume once Discovery protocol has been activated for (Ropsten &) Mainnet. Can we clarify this blocker/dependency with that GHI?

**Comment by adambabik** [comment]
These signals may be useful when we discover some specific behaviour of the Discovery protocol. 

Also, as far as I remember, we already notify the user if the number of peers drops to 0 but we use polling. When Discovery is enabled, these signals can be used instead.
