### ISSUE TITLE
Only 1 push notification shown no matter how many messages were sent while user was offline

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4178]
### User Story

As a user I want to receive as many PNs (or one meaningful PN) as many messages i missed while being out of internet connection

### Description

*Type*: Bug

*Summary*: As a user i want to understand clearly how many messages and events i missed while i  was being offline and my status app was running on background (for ex while i was in subway). Now when i reproduce such situtation i receive only 1 PN no matter how many events i missed

#### Expected behavior
I want to receive either equal number of PNs with respect of messages i missed while being offline or I can receive 1 PN saying something like `you have 50 messages in 4 chats` (like Viber does)

#### Actual behavior
1 PN is shown no matter how many messages were sent to user

### Reproduction

- install status on device A (android)
- install status on device B (ios)
- add each other to contacts
- as device B (ios) go on background and turn off any internet connection
- as device A (android) send several messages to device B (ios) while device B is offline
- as device A (android) kill status app
- wait for several minutes
- as device B (ios) turn on internet connection
- as device B (ios) pay attention to the push notifications received

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
I like "you have 50 messages in 4 chats" much better 👍
