### ISSUE TITLE
Auto-resize message element on "Sign Message" screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4181]
### User Story

As a user, I want to see messages in full on the "Sign Message" screen. 

### Description

*Type*: Bug

*Summary*: 
Any message longer than one line is cut off, forcing user to scroll within the element. 

#### Expected behavior
Text box should auto-resize to fit the length of the message, up to some maximum height. 

#### Actual behavior
The size of the text box is static and messages are hard to read.

<img src="https://user-images.githubusercontent.com/15470435/39861223-3580079c-5440-11e8-89a4-f393d94034b1.jpeg" width="300" />
<img src="https://user-images.githubusercontent.com/15470435/39861215-3071e14e-5440-11e8-9f8f-1e29b58eacd4.jpeg" width="300" />

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Opensea
- Explore the sea
- Buy an item
- Sign transaction
- Enter email address and name
- Submit to load "Sign message" screen

### Solution
*Summary*: 

Auto-expand message element on "Sign message" screen.

### Additional Information
* Status version: https://i.diawi.com/G8ccM5
* Operating System: iOS6s+

<blockquote><div><strong><a href="https://i.diawi.com/G8ccM5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xae930c895a354325722724a10d8e52ee1e4c70cfd688caae1536659fcd9964df](https://etherscan.io/tx/0xae930c895a354325722724a10d8e52ee1e4c70cfd688caae1536659fcd9964df)

**Comment by lukaszfryc** [comment]
Few users mentioned this bug on Instabug. I updated the severity of it to medium and priority to high.

**Comment by flexsurfer** [comment]
fixed https://github.com/status-im/status-react/pull/5875
