### ISSUE TITLE
Token transaction history shows wrong date

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4183]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see token transaction info so that I can know date/amount/sender/etc.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I received a 100 SNT token transfer 22 days ago, but Status is saying it was sent 1 minute ago. I verified when the transaction was sent by tapping more, then viewing on Etherscan

#### Expected behavior
Actual sent date is shown

#### Actual behavior
Todays date and current time are shown)

### Reproduction
Transfer SNT and wait.

### Additional Information
* Status version: Nightly
* Operating System: iOS

**Comment by asemiankevich** [comment]
it is shown fine for me on Android nightly
