### ISSUE TITLE
Enforce an expiration date to backup seed phrase

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#4184]
*Type*: Improvement

Status encourages the user to backup their seed phrase by going through a sequence of questions and challenges about their phrase. The risk with the current workflow is that there is currently no expiration date to complete this workflow and therefore the phrase will never be deleted from the device until the workflow is completed. 

### Solution
> We recommend that Status provide an expiration date to complete the task, and once the expiration date has passed, delete the user’s phrase.

Figure out a flow that wouldn't be too intrusive but at the same time encourage people to back up their seed phrase.

**Comment by mandrigin** [comment]
@hesterbruikman that looks like an important one to have... can we get some design ideas here?

**Comment by hesterbruikman** [comment]
@guylouis can you add this issue to the Wallet backlog, possibly as a requirement or related to in-app notifications? Original design included reminders: 1) badge on Profile and b) warning in Wallet as soon as you have assets.

Ideally, IMO, we encourage more through in-app notifications that are already on the backlog,

cc @andmironov @errorists

**Comment by churik** [comment]
still relevant in Status v1.0.1

**Comment by churik** [comment]
I think it may be closed as it is tracked in https://github.com/status-im/status-react/issues/10163

**Comment by hesterbruikman** [comment]
Thanks for cleaning this up @churik
