### ISSUE TITLE
/request sends string literal to recipient

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#4185]
*Type*: Improvement

> During a `/request` send to another user in a chat, the recipient of the request receives a request
message, indicating Eth has been requested. The message in the chat window is interactive and once the message is clicked on, Status automatically inserts a `/send` command with the amount of Eth
requested. We noticed that the string literal of what was sent is copied into the recipient’s prompt and
not the encoded value.

> Sending the string literal value and not the encoded numerical value is an unnecessary risk and we recommend encoding the value and sending only the trusted numerical value to the recipient. 

### Solution
1. Send the ETH amount as a numerical value or safely parse the incoming value to a numerical value if text must be used,
2. Add a network ID to `/request` payload. If it's a different network than the currently used one by the recipient, the request for ETH should be considered unsafe. The reason is that Whisper is network agnostic and it's possible for two Status apps to communicate while using different networks. This fix should avoid confusion when by accident the request for ETH is sent from a different network.

**Comment by mandrigin** [comment]
@adambabik I guess (2) is fixed, @yenda do you know about (1)?

**Comment by adambabik** [comment]
@mandrigin no idea, I haven't heard about any work on this issue.

**Comment by churik** [comment]
Closed as commands are removed now in #8674
