### ISSUE TITLE
Rooted Android Device Notifications

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#4190]
*Type*: Improvement
 
> Consultants observed that the Status application notifies a user of a rooted Android only during the first initial run of the application but not during the creation or recovery of an account. If an intended use case scenario of the application is to have multiple users on a single device, then a user should be
notified of a possibly compromised device during a creation or recovery of an account.

### Solution

TBD. 

First, we need to evaluate this issue and decide what kind of measures we can take.

**Comment by yenda** [comment]
The notification for rooted devices is in the native part of the code afaik, and it was previously showing up everytime the app was started an got change to show up the first time then on a less frequent basic. We could add an additional warning when creating and recovering an account. We could only show it on first run then. We could add a screen to the onboarding flow for rooted devices ?

**Comment by adambabik** [comment]
> We could add an additional warning when creating and recovering an account. 

> We could add a screen to the onboarding flow for rooted devices ?

I think it's a very good idea. We should also include a warning on the screen when a password is required for signing a transaction.

**Comment by denis-sharypin** [comment]
What information consists this notification for rooted devices?

**Comment by yenda** [comment]
"Your phone appears to be ROOTED, by pressing CONTINUE you understand and accept the risks in using this software."

**Comment by mandrigin** [comment]
@denis-sharypin @yenda I think we need some permanent notification in the UI about that. It would be cool to make some mockups and add it as a bounty. I think we already have a method to detect if the device is rooted, so it is purely a UI work.
