### ISSUE TITLE
App freeze after contact log in when user has a lot of messages

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4195]
***Type***: Bug

***Summary***: Number of messages that were received and read by the contact in 1-1/group or public chat has an impact on UI performance each login. 
When a user logs in to account with several hundreds of messages - there is a noticeable lag on navigation between different app views. It depends from device: for example Galaxy Note 4 user with 500 messages has an app freeze after login for ~8-10 seconds. 

#### Expected behavior
No time lags while navigating through different app screens right after user logged in

#### Actual behavior
Time lags while navigating through different app screens right after user logged in

### Reproduction
Precondition: User exists and has more than 100 messages received and read messages

* Open Status
* Log in to account
* Navigate through different screens (Profile -> Chats -> Wallet -> Chats -> 1-1 chat -> Back to Chats -> etc)

### Additional Information
* Status version: Develop 942c703b / Relese 0.9.18
* Operating System: Android and iOS

#### Logs

TF video and logs for user with 500 received and read messages (200 in public chat and 300 in 1-1 chat): from 00:20 - 01:00 https://app.testfairy.com/projects/4803622-status/builds/8262301/sessions/51/?accessToken=-FGlhJOYENH6QJxjdo1FXKyMQ4M

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8262301/sessions/51/?accessToken=-FGlhJOYENH6QJxjdo1FXKyMQ4M">TestFairy: Status 0.9.16-124-g942c703b+ (2551) @51</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Some work is already done in the scope of https://github.com/status-im/status-react/pull/3980 which showed really good results to fix this issue.

**Comment by mandrigin** [comment]
@Serhy can you please re-test this one?

**Comment by Serhy** [comment]
Retested with the latest nightly develop build (402ns Jenkins build from 24th of May).
Having 2000+ messages in public chat, 300+ messages in 1-1 chat does not has impact on UI performance each login or going background/foreground.
