### ISSUE TITLE
Back button is laggy when having unread message count 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4196]
### Description

*Type*: Bug

*Summary*: Top left back button is super laggy when having unread count and browsing a dapp meantime or chatting in a public chat. Tapping it does nothing for seconds (same as for device back button)

#### Expected behavior
When i am browsing a dapp or reading something interesting in public chats i want to quickly switch to unread messages by tapping back button

#### Actual behavior
back button does nothing when having some unread count

![image](https://user-images.githubusercontent.com/28752642/39871152-9825863e-546c-11e8-9f19-9b5c12ef584c.png)

### Reproduction

- Open Status
- Open dapp and start browsing it
- Receive something while you are browsing
- Tap back button when unread count appears

### Additional Information
* Status version: ...
* Operating System: Android

**Comment by lukaszfryc** [comment]
I didn't notice it today when I tested on Samsung Galaxy S6. I had multiple public chats with 99+ more messages and a 1-1 chat with some unread messages as well. Going back from a chat or dapp was pretty smooth.

**Comment by asemiankevich** [comment]
Okay, lets close it for now. Not 100% confident that it was caused by unread counter though.
