### ISSUE TITLE
Stop adding navigation errors to Home screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4201]
### User Story

As a user, I want my bad browser searches to be ignored, not saved and presented alongside actual DApps and chats.

### Description

*Type*: Bug

*Summary*: 

Bad searches should not be presented on the Home screen.

#### Expected behavior
[comment]: # 
User types a bad address into the URL bar of the "Open DApp" screen. 

There is no record of it on the Home screen when the user navigates back.

#### Actual behavior
User types a bad address into the URL bar of the "Open DApp" screen. Status presents an error. 

When user navigates back, the bad search is listed as if it were a working DApp.

<img src="https://user-images.githubusercontent.com/15470435/39875133-fd91043c-546f-11e8-92cd-48b7b3c2c051.jpeg" width="250">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/15470435/39875136-0141fa00-5470-11e8-89b1-fd10e527a6df.JPG" width="250">

### Reproduction

- Open DApp
- Type any random characters into the URL bar and go
- Go back

### Additional Information
* Status version: https://i.diawi.com/G8ccM5
* Operating System: iOS 6s+ 

<blockquote><div><strong><a href="https://i.diawi.com/G8ccM5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1300.00
Contract address: [0xaa82e32b0b96a2568db4a1ca59efe42fe7e695c7](https://etherscan.io/address/0xaa82e32b0b96a2568db4a1ca59efe42fe7e695c7)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by flexsurfer** [comment]
this issue not relevant anymore , because of https://github.com/status-im/status-react/issues/4269

**Comment by flexsurfer** [comment]
@psdp i closed PR , if you want you can reopen or create new, let's make it simpler, just remove browser item from home on back button if current page has error , thanks

**Comment by psdp** [comment]
@flexsurfer sure, thanks :)

**Comment by rachelhamlin** [comment]
Gentle ping for @psdp - we'd still love to pay you for this bounty if you're interested :)

**Comment by psdp** [comment]
@rachelhamlin Thanks for the reminder. PR submitted https://github.com/status-im/status-react/pull/4365

**Comment by rachelhamlin** [comment]
Awesome @psdp - thank you so much, this is a nice fix for cleaning up the home screen.
