### ISSUE TITLE
App crash when I submit URL with whitespaces 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4205]
***Type***: Bug

***Summary***: App crashes if I submit URL with whitespace in the middle or beginning of URL value. Note: It's OK if whitespace in the end of value though. And it's all fine on iOS

#### Expected behavior
No app crash when I submit URL with whitespace:
- trim URL value before sending a request
- convert whitespace in the middle of URL value to `%20`

#### Actual behavior
App crash when I submit URL with whitespace in the beginning or middle part of URL value

### Reproduction 1
- Open Status and create an account
- Navigate to `Create new chat` -> `Open Dapp`
- In the 'Enter URL' editbox type `       google.com` and submit this value

### Reproduction 2
- Open Status and create an account
- Navigate to `Create new chat` -> `Open Dapp`
- In the 'Enter URL' editbox type `google.      com` and submit this value

### Reproduction 3
- Open Status and create an account
- Navigate to `Create new chat` -> `Open Dapp`
- In the 'Enter URL' editbox type `wiki.com` and submit
- Set whitespace in the (edit to `wik i.com`) and submit

### Solution
- trim URL value before sending a request
- convert whitespace in the middle of URL value to `%20`

### Additional Information
* Status version: Develop / Release 0.9.18
* Operating System: Android 6.0, 7.0 

#### Logs
Logs are in TF: https://app.testfairy.com/projects/4803622-status/builds/8267264/sessions/32/?accessToken=-B-joPZ0ORu8r7FOudx/96kaqks

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8267264/sessions/32/?accessToken=-B-joPZ0ORu8r7FOudx/96kaqks">TestFairy: Status f851d764+ (2553) @32</a></strong></div></blockquote>

**Comment by yevh-berdnyk** [comment]
I've also faced with this issue on Android 8.1 (OnePlus 5)

**Comment by lukaszfryc** [comment]
It can be still replicated on 0.9.23. I think we should fix it asap. It's not so difficult to enter whitespace while typing an url.

**Comment by yevh-berdnyk** [comment]
The issue is still reproducible and should not be closed

**Comment by Swader** [comment]
This issue is still reproducible and should not be closed.
