### ISSUE TITLE
Chat that was deleted shows history

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4206]
### Description

*Type*: Bug

*Summary*: History of a chat that has been deleted should not appear when the chat is opened again. 

#### Expected behavior
When deleted chat is opened again it should not contain any historical messages.

#### Actual behavior
When deleted chat is opened again it contains history.

### Reproduction

- Open Status
- Create 1-1 chat and exchange some messages
- Delete the chat
- Create 1-1 chat with the same user

### Solution

Delete chat contents when a user deletes the chat

### Additional Information
* Status version: nightly, May 10
* Operating System: Android, iOS

**Comment by Serhy** [comment]
The https://github.com/status-im/status-react/issues/4265 covers this issue as well.
