### ISSUE TITLE
Show a warning when the contact is on a different network

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#4208]
# Problem

When users are a different network, there can be confusion regarding transaction request and transaction send commands.

related issue: https://github.com/status-im/status-react/issues/4185

# Solution

 We should show a warning to the user and disable these commands for contacts that are on different networks.

**Comment by chadyj** [comment]
Dupe of https://github.com/status-im/status-react/issues/4171 ?

**Comment by dmitryn** [comment]
Closing as seems duplicate of https://github.com/status-im/status-react/issues/4171
