### ISSUE TITLE
Contact name not shown after contacts add each other

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4212]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see the name of the person I'm chatting to so I don't have to keep asking "who is this"?.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Yesterday I was chatting with 15+ Status people, and after we added each other as contacts we could see each other's name.

However there were 3 or 4 people where the names didn't change. This can create a lot of confusion and erode confidence.

#### Steps to reproduce (based on debug session from @yenda  and @PombeirP)
1. Contact A enters airplane mode
1. Contact B scans contact A's QR code
1. Contact A scans contact B's QR code
1. Contact A exits airplane mode

#### Expected behavior
See the names of people I'm chatting with where both have added each other.

#### Actual behavior
See a random name

**Comment by pedropombeiro** [comment]
By the way, just saw this happen with @annadanchenko during pre-dogfooding https://status-im.slack.com/archives/C93KX711U/p1526371477000030. Both of us scanned each other's QR code.

For context, @annadanchenko didn't see an empty chat once I started a chat with her. Normally she would have seen an empty chat once the contact is requested.
