### ISSUE TITLE
User can clear the chat history

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4215]
### User Story

As a user, I'd like to have more control over my chat history and want to delete it anytime.

### Description

*Type*: Feature

*Summary*: Currently, it's unclear how long the chat history is stored. The minimal requirements are to have an ability to delete it completely. 

### Solution
*Summary*: 
- From a chat, a user can tap "more" then "Clear chat". This will keep the chat but delete its contents.
- This applies to 1-to-1,group-chat and public chats alike.
- Old messages will not be received again

Future idea:
A more advanced option would be to set a timer when chat history should be deleted or delete it if the session is ended (definition of the session also needs to be developed or specified).

Split from https://github.com/status-im/status-react/issues/3988 by @adambabik

**Comment by cammellos** [comment]
Will work on this together with https://github.com/status-im/status-react/issues/4206 as they are closely related
