### ISSUE TITLE
Messages in chats are shown as unread when i recover account

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4216]
### User Story

As a user i dont want to see all the messages that i have already read before showing up as `unread` when i recover my account

### Description

*Type*: Bug

*Summary*: I have read all the messages in all chats and when i recovered same account - unread badge appeared . Same happened to @chadyj . Pretty annoying issue taking into account the app performance 

#### Expected behavior
Chats are not shown unread if i have read them and recovered account after

#### Actual behavior
unread count appears when i recover account

### Reproduction

- Open Status
- Create some chats, read all incoming messages
- Recover same account on another device

### Additional Information
* Status version: ...
* Operating System: Android, iOS

**Comment by janherich** [comment]
This is very difficult to solve properly, as recovered account starts with empty app state and "recovered messages" are just messages received from offline inbox, so effectively new messages.
Maybe go-side de-duplication can solve this properly, I'm not sure...

**Comment by asemiankevich** [comment]
@janherich thanks for looking into this! Maybe we can discuss it later, I have put `post beta` for this issue, so it is not urgent for now, but from my perspective, it is expected behavior for any other messenger.

**Comment by yenda** [comment]
It will be solved once from field is implemented, probably today if you test fast :D
