### ISSUE TITLE
No error when scanning incorrect public key QR code

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#4223]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to to be notified when accidentally scanning incorrect QR code for adding a contact

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: No error when scanning incorrect public key QR code for adding a contact

#### Expected behavior
Error with message about scanning incorrect QR code is displayed to the user

#### Actual behavior
Nothing happens, camera stays open

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Click Plus button on Home view
- Click Start new chat button
- Scan incorrect QR code (e.g. QR code with wallet address of other user)

### Additional Information
* Status version: `7233a5f9`, nightly build from May 11
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1000.00
Contract address: [0x97d354c7c163dabc901edfa84b10f3c74de70a45](https://etherscan.io/address/0x97d354c7c163dabc901edfa84b10f3c74de70a45)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
@yevh-berdnyk Hi! I've posted a fix for this at https://github.com/status-im/status-react/pull/4502 :beers:

**Comment by pacamara** [comment]
@PombeirP @asemiankevich Hi, there seems to have been a misfire with the bounty system on this one, the funds have not been released even though the fix was merged several days ago?

**Comment by asemiankevich** [comment]
@andytudhope ^

**Comment by pablanopete** [comment]
@pacamara checking on this for you! :)

**Comment by pablanopete** [comment]
Would you mind sending a message to me (Hutch) on https://chat.status.im? Thanks! 

<blockquote><img src="https://riot.im/app/img/logos/riot-im-logo-1.png" width="48" align="right"><div><strong><a href="https://chat.status.im/">Riot</a></strong></div></blockquote>

**Comment by andytudhope** [comment]
The reason it was not picked up is likely because the description and title both include the text `Fixes #4223:` and that colon has messed things up. Hutch, we now need to revoke the bounty and pay it manually...

**Comment by pacamara** [comment]
@pablanopete @andytudhope Thanks for looking into this. I've used the same format `Fixes #nnnn:` in all the other PRs previously without there being this problem though! Will avoid it in future since there is the risk of it causing this issue. :+1:

**Comment by andytudhope** [comment]
Hey @pacamara - yeah it's another weird edge case ;)

I have revoked this and here is your bounty: https://etherscan.io/tx/0xee1a23258f4d5d60083db1f0f417a0dcd99a020a3743fa61ccdb4341839cfc57

**Comment by pacamara** [comment]
@andytudhope Haha the weird edge cases are my favourites :D  Thanks a ton for fixing that!  :beers:
