### ISSUE TITLE
Messages, which were sent while desktop-app is closed, are lost

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4229]
### User Story

As a user, I want to see all messages sent when I open the application, even when they were sent when Status desktop app was closed.

### Description
*Type*: Bug
*Summary*: messages sent while status-desktop app is not running are lost

#### Expected behavior
no lost messages

#### Actual behavior
messages are lost
![offl](https://user-images.githubusercontent.com/4557972/39933937-fa64ba5a-554c-11e8-8ac7-af87dddbe6e8.png)

### Reproduction
*Requirements*: 1-1 chat; user A is using status-mobile, User B is using status-desktop
 
- Open StatusIm as User B
- add User A
- send several messages from user A to user B and viсe versa
- quit status-desktop
- send several messages from user A (from status-mobile app)
- open status-desktop
- check chat with User A

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04
**NOTE:** vice versa scenario is working fine, so if you send a message from the desktop app when mobile app will be closed -  everything will appear when you open the mobile app

**Comment by vkjr** [comment]
@churik, is this behavior specific only for desktop? Do we get offline messages sent to mobile version?

**Comment by churik** [comment]
Hey, @vkjr !
I mentioned in the note, that in  mobile version we get offline messages.

**Comment by vkjr** [comment]
@churik, oh, sorry, didn't notice, thanks! :)

**Comment by churik** [comment]
**How it is implemented in Mobile:** this is "Offline messages settings", which should be enabled by default.  User can change "Mailserver" in Profile -> Offline messages settings
![_2](https://user-images.githubusercontent.com/4557972/40474957-f81882ee-5f48-11e8-960c-dac81f802f89.png)

**Comment by churik** [comment]
Fixed in nightly 10/08/2018
