### ISSUE TITLE
Transaction signing phrase is changed after account recovery

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#4235]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to remember transaction phrase and see it after recovering account on another device so that I'm sure my transactions are secure.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If user recovers his account and sends a transaction another signin phrase is shown when entering password without any notification about the phrase change

#### Expected behavior
Set up your wallet screen is shown when user opens wallet after account recovery. User can't send or request any transaction before setting up a wallet
#### Actual behavior
Another transaction phrase is shown for recovered account when signing a transaction

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Set up your wallet and remember transaction phrase (3 words)
- Recover this account on another device
- Open Wallet
- Click `Send transaction` button
- Select recipient and input valid amount
- Click `Sign transaction` button

### Additional Information
* Status version: `7233a5f9`, nightly build from May 11
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
This should be fixed before next release that will include mainnet

**Comment by jeluard** [comment]
Signing phrase is randomly generated for security reason. It can't be deterministic as otherwise third party could generate it.

So this is not possible (and expected to be this way).

**Comment by jeluard** [comment]
What can be done is showing the new signing phrase during the second onboarding. @yevh-berdnyk WDYT?

**Comment by yevh-berdnyk** [comment]
@jeluard let's prompt a user to set up his wallet again with a new phrase after an account recovery.
I'll update description
