### ISSUE TITLE
Push Notification permission is not being asked for some iOS users

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4240]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to grant Status permission to sent PN's so that I can be alerted to new messages.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Some users (@chadyj @jeluard) have reported that when installing a new build they don't get the PN permission alert. Also, in settings, Status is missing.

#### Expected behavior
Status asks for PN permission when onboarding.
This can be managed in settings.

#### Actual behavior
No PN prompt when onboarding.
No setting available to toggle

### Reproduction
Not sure. This has only been reported by 2 people but has persisted across builds.

Can be verified by checking if `notifications` is available in settings.

<img width="225" alt="missing" src="https://user-images.githubusercontent.com/116099/39956852-bde0b010-55e8-11e8-9d85-a79bc74a008f.png">

### Additional Information
* Status version: Nightly
* Operating System: iOS

**Comment by chadyj** [comment]
Update: Since I've been recovering accounts I haven't had the PN option. 
However today I created a new account and I got the PN prompt. When I did logged into my main account PN's were working for there.

**Comment by dmitryn** [comment]
It happens for recovered accounts, because we only ask permissions during onboarding of new account. Will make a fix.
