### ISSUE TITLE
Improve swipe-to-delete gesture both iOS and Android

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4247]
### User Story

As a user, I want to have better `swipe-to-delete` experience when interacting with chats on Home screen (same as I am used to when using other mobile messengers like Viber, Telegram, Whatsapp  or Skype)

### Description

*Type*: Bug

*Summary*: currently `swipe-to-delete` gesture brings a bit poor experience to the user. Please check the following cases:

#### Actual behavior

1. swiping is allowed only when user swipes in strictly horizontal manner but it is not always possible. I think we need to improve the swiping area and directions , so user wont be confused swiping again and again and thinking it is not working

2. when swiping chat the screen is scrolled down very often (this is caused by point 1 i guess)

3. disable `swipe-to-the-right` gesture as it does nothing (no use cases for this) and confuses user

4. make the left `swipe-to-delete` gesture more smoothly (compare with Telegram or Viber). For now, it looks very amateurish 

5. Personally, I don't like the trash icon used - looks too old-fashioned, @denis-sharypin what do you think? Can we use the one Telegram uses? Or just a cross like Viber does?

### Reproduction

- Open Status
- Create any chat
- Swipe-to-delete

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by Coffee-Boyy** [comment]
I started with a react native plugin for this swipe gesture in my custom upstreams story #4239 that performs this very nicely. I was told instead that I should use this current implementation of the swipe to delete gesture due to security concerns of bringing in an outside dependency but I believe it would be well worth the ease of use and small security audit on the dependency.

**Comment by lukaszfryc** [comment]
Also, let's make sure that items do not get stuck half opened:

<img src="https://user-images.githubusercontent.com/7532782/40981955-7c47333e-68dc-11e8-98b5-cfdcec4de813.png" width="200">
