### ISSUE TITLE
Chat header stops displaying after switching between public and 1-1 chats 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4249]
### User Story

As a user, I want always to see chat header.

### Description
*Type*: Bug
*Summary*:  switching between public and 1-1 chats leads to chat header disappearing.

#### Expected behavior
chat header (name) is always visible

#### Actual behavior
no visible chat header
![ghgh](https://user-images.githubusercontent.com/4557972/39992261-e0431a4c-577a-11e8-9b26-f6fd6872fb94.png)

### Reproduction

- Open StatusIm 
- Create 1-1 (`chat A`) and join to public chat (`chat B`)
- Switch between `chat A` and `chat B` 2+ times

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04
* Video: http://take.ms/h3Vwh

**Comment by EugeOrtiz** [comment]
Designs of how headers look like can be found here (Zeplin):
- 1:1 chat, unknown person: zpl.io/aRqj4dv
- 1:1 chat with a contact: zpl.io/am6gW4v
- Public chat: zpl.io/bAv8OjB

**Comment by rcullito** [comment]
these are great, thanks @EugeOrtiz. :ok_hand: timing

**Comment by maxhora** [comment]
@churik this Issue should be re-validated against latest manual desktop build. Hopefully, shouldn't appear any more since https://github.com/status-im/status-react/pull/4578 is merged already.

**Comment by churik** [comment]
Still reproducible on [desktop, build 11](https://jenkins.status.im/job/status-react/job/desktop/job/manual/11/)
Video: [header](http://take.ms/0tdtL)

**Comment by maxhora** [comment]
@rcullito @churik chat headers visibility issue visually looks like the corresponding text label doesn't get the width correctly and brake one line test into multi-line. It seems it somehow depends on the length of available chats titles.

**Comment by churik** [comment]
@MaxRis so the problem is not in react-native side?

**Comment by maxhora** [comment]
@churik I haven't yet checked exactly this issue, but it seems that after recent change in react-native-desktop headers started working better/differently at least for me :)

**Comment by churik** [comment]
It is still trimmed to shortest channel name in the list (for example if you are switching between #tchu channel and 'Testing IOS recover' 1-1 chat, chat header for 1-1 becomes 'Testin')
![reco](https://user-images.githubusercontent.com/4557972/42452562-0e70bc1e-8393-11e8-9d6c-cfaee7a5134b.png)

Build: [build_15](https://jenkins.status.im/job/status-react/job/desktop/job/manual/15/)
Video: [header_build_15](http://take.ms/rK68H)

**Comment by vkjr** [comment]
Will take this while @rcullito is unavailable

**Comment by churik** [comment]
Closed after merging https://github.com/status-im/react-native-desktop/pull/314
