### ISSUE TITLE
No validation in 'Add new contact' and 'Join to public chat' fields

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4250]
### User Story

As a user, I want to get the validation error when adding an invalid key or public channel by mistake.

### Description
*Type*: Bug
*Summary*:  can insert and add invalid contact key; can insert and add invalid value to public chat; can click on 'Add' in field 'Join to public chat' with empty value.

#### Expected behavior
validation errors
3. Please enter a valid contact code
4. The topic name cannot be empty
5. A topic name can contain only following characters: a-z -

#### Actual behavior
3. The new contact is added
4. 
![chat-null](https://user-images.githubusercontent.com/4557972/39993553-ebeb589c-577e-11e8-9e31-929c529ed07b.png)
5. New public chat is added

### Reproduction

1. Open StatusIm, log in
2. Click on +
3. Enter invalid contact key (i.e. '123') in 'Add new contact', click on 'Add'
4. Repeat 2,  click on 'Add' in 'Join to public chat' |(with empty value)
5. Repeat 2, enter invalid topic name (i. e. '123') in 'Join to public chat', click on 'Add'

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

**Comment by EugeOrtiz** [comment]
Designs for test input fields can be found here: zpl.io/a3q3G61 (Zeplin)
Example for New 1:1 chat: zpl.io/aB5mnom
