### ISSUE TITLE
Display seed phrase after creating a desktop account

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4255]
### User Story

As a user, I want to restore my account from seed phrase if it was created in status-desktop

### Description
*Type*: Feature
*Summary*: no seed phrase is displayed in profile after creating an account in status-desktop

#### Expected behavior
you can back up your seed phrase in 'Profile'

#### Actual behavior
no seed phrase is displayed

### Reproduction

- Install `status-desktop` 
- Open StatusIm 
- Create new account
- Go to profile

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

**Comment by asemiankevich** [comment]
seed phrase is used to recover wallet, and we dont have wallet for P0. Adding medium prio for now
