### ISSUE TITLE
Update Opt Metrics screen to match mobile app patterns

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4261]
### User Story

As a user, I want the onboarding flow to use similar patterns both mobile and desktop so I am not confused. 

As developer / QA, I want to introduce latest UI changes in desktop so its design is pretty much similar to the mobile app and does not look outdated

### Description

*Type*: Feature

*Summary*: Update Opt Metrics screen for Status Desktop 

#### Expected behavior
Status Desktop Opt Metrics screen looks similar to mobile (copy and design). Images used are high quality (resolution) so the app does not look blurry. Use dynamic pictures where possible so the layout is not broken in full-screen and collapsed window

![image](https://user-images.githubusercontent.com/28752642/40022393-8895ee7c-57d0-11e8-9f3d-f6e81c4899d3.png)

#### Actual behavior
Old style is used, images are poor quality

![image](https://user-images.githubusercontent.com/28752642/40022421-a5da50a4-57d0-11e8-8e0e-0891f3bba318.png)

### Reproduction

- Open Status Desktop
- Create Account
- Restore Account

### Additional Information
* Status version: have no idea, something we got last week (May 7-11)
* Operating System: macOS

**Comment by asemiankevich** [comment]
added low prio for now as we are not doing this for P0

**Comment by chadyj** [comment]
Opt-in screen has been removed from Status, so we can close this.
