### ISSUE TITLE
Allow to specify new bootnodes

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4264]
### Problem

An adversary can easily block bootnodes IPs and our users won't be able to communicate.

As a user, I'd like to use Status with custom bootnodes in case Status bootnode IPs are blocked.

### Solution

Provide a way to distribute new bootnodes to users. Upon scanning a QR code bootnodes should be updated. App restart is OK.

### Notes

Hardcoded bootnodes: https://github.com/status-im/status-go/blob/develop/geth/params/cluster.go

Cluster config: https://github.com/status-im/status-go/blob/375d5ec8c304e17dedb4358a4222c7742e141c53/geth/params/config.go#L165-L175

Related:
- https://github.com/status-im/status-cluster/issues/92
- https://github.com/status-im/status-react/issues/3994

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by oskarth** [comment]
Problem space questions (follow up from Slack):

1. If user has scanned or somehow retrieved bootnodes in app, how would they get updated here https://github.com/status-im/status-go/blob/develop/geth/params/cluster.go?
2. Would it make sense to use `AddPeer` and add static nodes as opposed to bootnodes? This can be done at run-time, but I guess it wouldn't allow discovery to be run

**Comment by oskarth** [comment]
Probably need separate issue for mail server, or we can fold it in and make it large bounty.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8417eccb7a0ba9945147c3c153769e8bd14098776873a1d010847941cc4ae5f4](https://etherscan.io/tx/0x8417eccb7a0ba9945147c3c153769e8bd14098776873a1d010847941cc4ae5f4)

**Comment by oskarth** [comment]
@andytudhope don't see any current balance here

**Comment by pedropombeiro** [comment]
@cammellos can you please update the state of this GHI (project boards also)? Thanks!

**Comment by cammellos** [comment]
@PombeirP Adding & using bootnodes has been merged in, the outstanding things are:

1) Scan with a QR code
2) Editing
3) Deleting bootnodes

I can either close  this one (or keep this as a sort of Epic) and create new issues for the remaining or update this with the outstanding features. What do you think?

**Comment by pedropombeiro** [comment]
@cammellos We can close this one and create new ones referencing this one.

**Comment by cammellos** [comment]
@PombeirP will do
