### ISSUE TITLE
Selected tab is not highlighted

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4266]
### User Story

As a user, I want to have selected tab being highlighted so I can understand easily which tab I am on

### Description

*Type*: Bug

*Summary*: Selected tab is not highlighted on Status Desktop so I am confused which tab I am on.

#### Expected behavior
A chosen tab is highlighted

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/40043550-7390619e-582d-11e8-9e37-b3035ed7a0b6.png)

### Reproduction

- Install Status Desktop
- Switch between tabs

### Additional Information
* Operating System: MacOS

**Comment by EugeOrtiz** [comment]
Designs for that can be found here >>> zpl.io/aXGDvmE (Zeplin)

<img width="343" alt="captura de pantalla 2018-06-08 a la s 2 33 18 p m" src="https://user-images.githubusercontent.com/37297779/41158376-f7cbc706-6b28-11e8-87fb-2f79924c7718.png">

<img width="339" alt="captura de pantalla 2018-06-08 a la s 2 33 28 p m" src="https://user-images.githubusercontent.com/37297779/41158365-f0f574ae-6b28-11e8-97b9-268b083617e4.png">

**Comment by churik** [comment]
Fixed in #4752
