### ISSUE TITLE
Show app version for Status Desktop

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4267]
### User Story

As a user / developer / QA, I want to understand which version I am on.

### Description

*Type*: Feature

*Summary*: Add version label to Status Desktop for all platforms supported (MacOS, Windows, Linux)

#### Expected behavior
I can find the app version:
1. Clicking Status -> About in top nav bar (macOS)
2. Profile -> next to ` Log out` in Status Desktop App (trying to match mobile app pattern)
3. Similar for Windows / Linux

#### Actual behavior
I can't understand which version I am on because it is not stated anywhere

### Reproduction

- Install Status Desktop
- Click `StatusIm` in the top nav bar (macOS)
- Click `About` in Windows app 
- Similar in Linux
- Click `Profile` in the application

### Additional Information
* Status version: have no idea :)
* Operating System: macOS, Windows, Linux

**Comment by churik** [comment]
**How it is implemented in mobile:**
![vers](https://user-images.githubusercontent.com/4557972/40474529-f50a860c-5f47-11e8-9b86-d52dc58cc23b.png)

**Comment by EugeOrtiz** [comment]
App version can be found in user's profile.
Design here >>> zpl.io/25qZqB3 (Zeplin)
