### ISSUE TITLE
Broken message counter when having more than 999 messages

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4268]
### Description

*Type*: Bug

*Summary*: Message counter layout is broken when there are more than 999 messages unread. 4 digits number is too large to show in this blue circle

#### Expected behavior
Message counter should not be broken. I suggest showing `99+` value when there are more than 99 messages, so we still stick to use 3 digits that are shown fine

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/40045571-57e5825c-5833-11e8-8dfd-708ac89a3c09.png)

### Reproduction

- Open Status
- Receive more than 999 messages in public/group chat
- Pay attention  to unread counter

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 920.00
Contract address: [0x588b647266e05d33871a932ebddd49645895ec57](https://etherscan.io/address/0x588b647266e05d33871a932ebddd49645895ec57)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by morrocco** [comment]
Hi, we need help with ConnectUS.mx
