### ISSUE TITLE
Fonts and images shouldn't look blurry in Desktop app

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4270]
### User Story

As a user I want to have a good experience when using Status Desktop App. Please check https://app.zeplin.io/project/5a324ae5d60d197e7e3369cc/dashboard

### Description

*Type*: Bug

*Summary*: Provide and implement high-quality images for Status Desktop. 

#### Expected behavior
Status Desktop UI is not blurry 

#### Actual behavior
Status desktop UI is poor quality

### Reproduction

- Open Status Desktop
- Click through the app

### Additional Information
* Operating System: macOS

**Comment by churik** [comment]
@MaxRis can we somehow to trigger build with high-quality image resolution?
AFAIK it is only about some option in Jenkins (fix me if I'm wrong)

**Comment by maxhora** [comment]
@churik I believe that it's not so easy, unfortunately. @vkjr Could you please suggest if you have an idea if it's possible to tweak it quickly

**Comment by vkjr** [comment]
@MaxRis, @churik, initially I supposed that adding few lines to info.plist will be enough but after spending an hour or two on this I didn't find the quick solution :( Needs more deep investigation. 
I can take this task since I already worked on it.
