### ISSUE TITLE
Sending message with 'Enter' key is not working (is possible only with button)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4271]
### User Story

As a user, I want to send messages using 'Enter' key

### Description
*Type*: Feature
*Summary*: user can send messages only with button, but not using the keyboard.

#### Expected behavior
message is sent

#### Actual behavior
next row (expect new row when clicking Shift+Enter)

### Reproduction

- Install `status-desktop` 
- Open StatusIm 
- Create new account
- Start 1-1 chat
- Type a message
- Click 'Enter'

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

**Comment by churik** [comment]
## 1. Cannot start the new row in message field

Steps:

- open StatusIm Desktop ([version](https://drive.google.com/open?id=1DzULn8OWZRY5C9lQJJUdfNntLezuscZ9))
- log in
- start new 1-1 chat 
- type message in message field - press Shift+Enter (or Alt+Enter) to start new line

### Actual result:
message is sent 

### Expected result: 
message is not sent; new row is started

**Screen:** 
![newline](https://user-images.githubusercontent.com/4557972/40301969-5fc0c5aa-5cf6-11e8-8e5e-da520eadc633.png)
**NOTE:** common hotkeys are: Shift+Enter, Alt+Enter (works in Slack, Telegram, Skype)
**Wallet**: MetaMask
**OS:**  Mac OS High Sierra

**Comment by churik** [comment]
## 2. Several messages are sent if you press "Enter" several times

Steps:

- open StatusIm Desktop ([version](https://drive.google.com/open?id=1DzULn8OWZRY5C9lQJJUdfNntLezuscZ9))
- log in
- start new 1-1 chat 
- type message in message field - press Enter quickly two times ([video](http://take.ms/otpHP))

### Actual result:
2 messages are sent 

### Expected result: 
one message is sent

**Wallet**: MetaMask
**OS:**  Mac OS High Sierra

**Comment by vkjr** [comment]
@churik, could you please check a new build - https://drive.google.com/open?id=1-tyFYQ0vCCVzup9TNasPlTOKQc4R7sue

- now new line can be started with shift+enter
- quick presses on Enter doesn't result in a message duplication

<blockquote><div><strong><a href="https://drive.google.com/open?id=1-tyFYQ0vCCVzup9TNasPlTOKQc4R7sue">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
