### ISSUE TITLE
Add mentions in a group / public chats

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4272]
### User Story

As a user, I want to mention someone I want to talk to with `@` (same as in Slack) because it is a common pattern in popular messages

### Description

*Type*: Feature

*Summary*: when chatting with someone i want to highlight the person with `@` sign so the person is highlighted in the chat window and gets the notification (pinged)

#### Expected behavior

1. `@` mentions are implemented in a group and public chats
2. once pinged in a group or public chat the person is highlighted visually (bold with yellow for example)
3. once pinged in a group or public chat the person gets push notification to his mobile device

#### Actual behavior
Mentions are not implemented

**Comment by lukaszfryc** [comment]
Really good idea!

**Comment by annadanchenko** [comment]
how should it work in public chat for someone in your Contacts vs a stranger? E.g. if I'm in your Contacts list you will see "Anna" as a name, if not - you will see something anonymous like "Great White Cat". So when name is sent to chat what others will see (will it be Anna and Great White Cat depending on me being in their Contacts)? Will it be possible to tag a stranger and this person will be notified?

**Comment by churik** [comment]
tracking in https://github.com/status-im/status-react/issues/7117
