### ISSUE TITLE
Links are displayed as plain text

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4275]
### User Story

As a user, I want to have links clickable.

### Description
*Type*: Feature
*Summary*: links are displayed as plain text - no possibility to proceed to reference.

#### Expected behavior
links are clickable, looks like in the screenshot below
![rightli](https://user-images.githubusercontent.com/4557972/40054837-d778b654-584e-11e8-8dac-315236133e4e.png)

#### Actual behavior
links are displayed as plain text
![lik](https://user-images.githubusercontent.com/4557972/40054920-02fa04e0-584f-11e8-91b2-8eb542c1a3aa.png)

### Reproduction

- Install `status-desktop` 
- Open StatusIm 
- Create new account
- Start 1-1 chat
- Paste a link
- Send message

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

**Comment by churik** [comment]
**To clarify for P0:**  for now suggestion to open link automatically in user default browser
**How it is implemented in mobile:**
Suggestion - to use option "Open in Web browser" automatically in Desktop for P0
![web](https://user-images.githubusercontent.com/4557972/40473158-11f730a2-5f44-11e8-9656-963557ba4115.png)

**Comment by EugeOrtiz** [comment]
Design of how links look like can be found here >>> zpl.io/Vkml10Z (Zeplin)
The cursor should change to a "hand cursor" when on hover.

**Comment by vitvly** [comment]
Related react-native-desktop issue: https://github.com/status-im/react-native-desktop/issues/278

**Comment by vitvly** [comment]
Above issue #278 is fixed. However, there is an issue with onPress handlers not firing for nested `<Text>` components: https://github.com/status-im/react-native-desktop/issues/290.

**Comment by EugeOrtiz** [comment]
@churik @siphiuel is this still blocked?

**Comment by chadyj** [comment]
Would be lovely to consider channel name links too https://github.com/status-im/status-react/issues/6139

**Comment by chadyj** [comment]
Done!
