### ISSUE TITLE
Click on 'Add to contact' doesn't add user to contact 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4276]
### User Story

As a user, I want to add a person to contacts  - thus share my name and profile photo.

### Description
*Type*: Bug
*Summary*: when a user A from other device start chat with user B (on status-desktop) - user B cannot add user A to his contacts.

#### Expected behavior
'Add to contacts' is working; after click user A can see profile name and photo of User B

#### Actual behavior
no action after click on 'Add to contacts'
![lkj](https://user-images.githubusercontent.com/4557972/40055621-3baf82c2-5851-11e8-9181-860e34007fa8.png)

### Reproduction
**Prerequisites**: 
1) User A is using  `status-mobile`
2) User B is using `status-desktop`

- User A starts a new chat with user B
- User A sends several messages
- User B opens chat with User B

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04
* Video: http://take.ms/R8ouy

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=qAAqsrEhCGBZSyZSIDNPSlB0Vbgzvu&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/qAAqsrEhCGBZSyZSIDNPSlB0Vbgzvu">File "screencast 2018-05-15 14-53-59.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by EugeOrtiz** [comment]
A contact can be added from 2 different places (please check the designs):
- From link next to the name: zpl.io/am6gW4v (Zeplin)
- From user profile's card: zpl.io/Vqx03r6 (Zeplin)

**Comment by rcullito** [comment]
moving this out of "in progress". makes sense to revisit after we've merged develop into desktop
