### ISSUE TITLE
Can't navigate to user's profile

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4279]
### User Story

As a user, I want to check user profile by clicking his user pic

### Description

*Type*: Feature

*Summary*: I want to navigate to user profile from chats or contacts list by clicking his user picture (any other use cases welcome, we don't have it designed, for now, so this is my personal assumption)

#### Expected behavior
Navigate to user profile:

1. Home - Appropriate chat - click user image
2. Contacts list - click user image

### Additional Information
* Operating System: MacOS

**Comment by churik** [comment]
**To clarify for P0:** user should be able to start chat from user profile and see main info (picture, name, "Add to contacts", "Send message", Contact code).
Naviga
Contact code should be available for copying.
Navigation to user profile should be possible from:
- public chat (clicking on user  pic)
- 1:1 chat (clicking on "View profile")
- contact list (clicking on user  pic)
**How it is implemented in mobile:**
User is not added to contacts:
![profile](https://user-images.githubusercontent.com/4557972/40471441-5def0aac-5f3f-11e8-8f2f-9adbea2562fc.png)
User is added to contacts:
![incont](https://user-images.githubusercontent.com/4557972/40471875-9db02620-5f40-11e8-9ece-17a3f828d695.png)
Option "View profile" from 1:1 chat:
![vew](https://user-images.githubusercontent.com/4557972/40472059-0e913654-5f41-11e8-91bb-c2413fe96927.png)

**Comment by EugeOrtiz** [comment]
In the new design, another user's profile can be accessed from:
- 1:1 chat secondary actions > View profile 
- Left panel with the list of chats > Right click on a user's "row" > View profile

Designs here (Zeplin):
- Menu with secondary options: zpl.io/V4J4NX4
- User profile card: zpl.io/Vqx03r6

**Comment by churik** [comment]
@EugeOrtiz also please implement this view when user is already added to contacts.
In mobile: 
![us](https://user-images.githubusercontent.com/4557972/41219433-f7ddd442-6d66-11e8-8549-8c79a5ad4753.png)

**Comment by EugeOrtiz** [comment]
Yeap, is in the user profile card mentioned above zpl.io/Vqx03r6

**Comment by rcullito** [comment]
this issue has since been fixed :+1:
