### ISSUE TITLE
Random crash after using app for a while (1h+)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4280]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: randomly (I faced with issue twice under different circumstances, but both times I used `status-desktop` actively at least for 1 hour)  `StatusIm` process is starting to consume more 100% CPU, the laptop starts to heat and eventually process stops to respond.

#### Expected behavior
no hang and underconsumption 

#### Actual behavior
[comment]: # (Describe what actually happened.)
![image](https://user-images.githubusercontent.com/4557972/40056527-57094672-5854-11e8-9dc3-9d3775d52dd1.png)

### Reproduction
**Scenario 1**
- use the app for chatting for 1 h approximately (during this time add new users, create new chat etc.)
- quickly switching between chats

**Scenario 2**
- use the app for chatting for 1 h approximately (during this time add new users, create new chat etc.)
- log out
- click on 'Create new account'

After both scenarios:
- `StatusIm` process starts to consume 100+ % CPU
- app hangs
- laptop starts heated
- process not responding.
Logs, generated by MacOS after I forced quit the process, are attached.

**Workaround:**  then if you try to start `StatusIm` again - nothing happens UNTIL you quit process `ubuntu-server`. If you quit process then will start `StatusIm` - it'll work as expected.

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4

#### Logs
[crash.log](https://github.com/status-im/status-react/files/2004980/crash.log)

**Comment by vitvly** [comment]
Inability to start app again after crash might be related to https://github.com/status-im/status-react/issues/4689

**Comment by churik** [comment]
Moved to #5012
