### ISSUE TITLE
Contacts list is missing

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4281]
### User Story

As a user, I want to see my contact list so I know whom I did add as well as I can select whom to chat with 

### Description

*Type*: Feature

*Summary*: Add `Contacts` functionality

#### Expected behavior

1. I can select anyone to chat with from my contacts
2. I can create a group chat with my contacts
3. I can monitor my contacts list
4. I can remove contacts from my least easily

We need this to be designed

**Comment by churik** [comment]
**To clarify for P0:** 
- add contact list to "New Chat" screen
- if I click on contact, I should be redirected on 1-1 chat with him
- if I click "Add to contact" from 1-1 chat - user should appear in Contact list (#4276)

**How it is implemented in mobile:**
![cont_list](https://user-images.githubusercontent.com/4557972/40475903-61721398-5f4b-11e8-801f-c8ec80922018.png)

**Comment by EugeOrtiz** [comment]
Designs for this can be found here: 
zpl.io/2ZgvMKw
zpl.io/aBElz8L

(Zeplin)
