### ISSUE TITLE
Copy / paste / quoting options are not available in chats

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4283]
### User Story

As a user, I want to copy, paste and quote messages received/sent in 1x1, group or public chat

### Description

*Type*: Bug

*Summary*: messages operating is not possible for Status desktop. 

#### Expected behavior

As user I want to:

1. copy / paste any message from chat (1x1 chat, group and public)
2. quote the messages (could be done in future iterations)
3. add reactions to messages (could be done in future iterations)

### Reproduction

- Open Status Desktop
- Go to any chat and copy message

### Additional Information
* Operating System: macOS

**Comment by asemiankevich** [comment]
Beta scope

**Comment by churik** [comment]
**To clarify for P0:** user should be able "Copy to clipborad" whole message.
**How it is implemented in mobile:**
![ghghhg](https://user-images.githubusercontent.com/4557972/40471005-f7a7af3e-5f3d-11e8-99d8-295e939ffd39.png)

**Comment by EugeOrtiz** [comment]
Designs for this can be found here >>> zpl.io/V18jyew (Zeplin)

**Comment by vkjr** [comment]
@EugeOrtiz, I think that text also should be selectable and usual copy/paste shortcuts should work in chat.

**Comment by EugeOrtiz** [comment]
@vkjr Definitely! Will add that as a comment on Zeplin :)

**Comment by EugeOrtiz** [comment]
Also @vkjr please have in mind that the user should also be able to select text (all or part of it) from a message using her mouse/trackpad/keyboard to later copy it.

**Comment by churik** [comment]
For quoting separate issue will be added
