### ISSUE TITLE
Manage account recover errors

### ISSUE THREAD

**Issue by gravityblast** [status-im/status-react#4284]
If users try to add an existing account that they already imported, but with a different password, they are stuck in the "recover" screen and they don't receive any error.

Error printed in the logs:
```
:account-recovered {"address":"xxx","pubkey":"","mnemonic":"x y z","error":"could not decrypt key with given passphrase"}
```

Steps to reproduce it:

1. Create a new account with password `000000`
2. Copy your 12 mnemonic words
3. Log out
4. Click on "Add existing account"
5. Use the 12 mnmonic words taken on step 2, and use password `111111` (different from the previous one)
6. You are stuck on that screen without any error message.

Reason:

`status-go` does the following:

1. receives the 12 words
2. generates the keys
3. derives the address
4. check if the address is already imported
5. if it is, it tries to decrypt the key with password `111111`
6. it fails because it's been previously encrypted with password `000000`

One quick solution can be showing an error to the user, but we should ask UX/UI team.

**Comment by goranjovic** [comment]
Closing as outdated. Will be replaced with a redesigned flow (post-Beta), see conversation in #4403 

cc @jeluard
