### ISSUE TITLE
Other user's profile is broken

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#429]
<img width="487" alt="screen shot 2016-11-08 at 18 06 21" src="https://cloud.githubusercontent.com/assets/911127/20104205/2290dfa6-a5de-11e6-92cb-7ac2ecc604bf.png">

**Comment by jarradh** [comment]
also lets remove the remove user

**Comment by alwx** [comment]
What do you think about temporary removing 3-dots icons from this screen? These icons do nothing.
