### ISSUE TITLE
 Allow both nightly and PR branch version to coexist

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4290]
### User Story

As a developer, I want to be able to have both the nightly and PR branch versions co-existing at the same time on Android.

### Description

Currently, both versions share the same identifier preventing keeping reinstalling the nightly build over the PR branch version from the Diawi released version installed. The Diawi version should have a different app ID that doesn't collide with the nightly. This is similar to what was done in the https://github.com/status-im/status-react/pull/4039 bounty PR.

*Type*: Feature

**Comment by asemiankevich** [comment]
i wish i can upvote it more! :) 👍

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1800.00
Contract address: [0x85b961d08f464e5e8517c54bfce2e313fd42fc1d](https://etherscan.io/address/0x85b961d08f464e5e8517c54bfce2e313fd42fc1d)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by endenwer** [comment]
I think the best option here is to use debug build(presented in #4039) for PR branch versions. I can change Jenkins to use that build.

**Comment by endenwer** [comment]
@PombeirP @asemiankevich Hi. Who can answer if I can make it as I described above.

**Comment by asemiankevich** [comment]
@PombeirP Pedro, @jeluard Julien any thoughts?

**Comment by pedropombeiro** [comment]
Hi @endenwer, sorry for the late answer (bank holiday). I think using the debug ID for the PR build should work.
