### ISSUE TITLE
Rename Recent Recipients to Contacts in Wallet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4296]
### User Story

As a user, I don't want to get confused when treating `Recent recipients` incorrectly

### Description

*Type*: Bug

*Summary*: I realized that `Recent recipients` is confusing when sending funds from the wallet. I sent some test ETH to mycrypto account and then I wanted to send some more and realized that I need to scan the code again as nothing is shown in recent recipients

#### Expected behavior
Rename `Recent recipients` to `Contacts` everywhere in Wallet so it would be less confusing

### Reproduction

1. Wallet tab - send transaction - specify recipient
2. Wallet tab - receive transaction - send a transaction request - specify recipient

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 460.00
Contract address: [0x06767c26a1e89ea1242b59bfbba0c77daccc8175](https://etherscan.io/address/0x06767c26a1e89ea1242b59bfbba0c77daccc8175)
Network: Mainnet
Paid to: georgiemathews
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
