### ISSUE TITLE
Security warning for browser view

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4298]
### User Story

As a user, I want to know when I am exposed to security risks in Status browser.

### Description

*Type*: Feature

*Summary*:

Display some form of notification that when viewing user-entered URLs, the security of the page can not be proven because there are no HTTPS certificate details.

#### Expected behavior
When a user navigates to a URL in the browser bar or opens a link from chat, they receive some message or notification about the security risk.

e.g. "Be careful! Security details are not available. You may be at risk of phishing attacks."

This is an interim measure until more security details can be provided, in line with modern standards.

<img width="274" alt="screen shot 2018-05-16 at 13 15 30" src="https://user-images.githubusercontent.com/15470435/40113923-55b35382-590b-11e8-9d4b-9d4500caca07.png">

#### Actual behavior
Users can see only the URL in the browser bar, with no further security detail or risk notice.

<img src="https://user-images.githubusercontent.com/15470435/40113731-b9cfa452-590a-11e8-920d-e62685c0af57.JPG" width="250" />

**Comment by denis-sharypin** [comment]
![ios_browser-website](https://user-images.githubusercontent.com/6559881/40223143-5658af80-5a82-11e8-9c3a-571a189382f8.jpg)

We trigger this notification with _every_ opening of the browser
1.  from the dapps list though address input
2. from any link in the chat
3. from the home tab

If a user closes this notification it disappears only for this browser session

Mockup here — https://zpl.io/2y7goew

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by rachelhamlin** [comment]
@denis-sharypin @flexsurfer this is not as urgent as we thought. Chrome is the only browser that displays full certificate details on mobile. 

Can we alter the copy to say, "Connection is not **proven** secure. Make sure you trust this site before signing transactions or entering personal data."

It would be great if, in the near future, we could add a security symbol in the URL bar next to the address, which the user could click on to trigger this security warning.
