### ISSUE TITLE
Chats and mailserver do not work in Russia

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4299]
### Description

*Type*: Bug

*Summary*: 

Can't read new messages and send messages to public chat because of error `Could not connect to mailserver` 
#### Expected behavior
Can see messages and send messages to public chat

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/8295727/sessions/105/?accessToken=5ZRyMMbJ7KR6NFlS4IHkGBRB170
- Open Status
- Join status public chat
- Send message

### Additional Information
* Status version: nightly build May 16
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8295727/sessions/105/?accessToken=5ZRyMMbJ7KR6NFlS4IHkGBRB170">TestFairy: Status 0.9.16-162-g9a947792+ (2589) @105</a></strong></div></blockquote>

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/4264

**Comment by flexsurfer** [comment]
geth.log
```
t=2018-05-16T12:34:18+0000 lvl=info msg="Status service api is disabled" package=status-go/geth/node
t=2018-05-16T12:34:18+0000 lvl=info msg="Starting peer-to-peer node"     instance=StatusIM/v0.9.9-52cdcf8/android-arm/go1.10.1
t=2018-05-16T12:34:18+0000 lvl=info msg="Starting P2P networking"
t=2018-05-16T12:34:21+0000 lvl=info msg="UDP listener up"                net=enode://9adf4236505ddee353d73471aa63259e059735c4f9c1251f2e78d4f67078472a2bcc92de3535860b661331d84f0c3295877a8ce212581051cc01e6910bbe7cda@[::]:50485
t=2018-05-16T12:34:21+0000 lvl=info msg="RLPx listener up"               self="enode://9adf4236505ddee353d73471aa63259e059735c4f9c1251f2e78d4f67078472a2bcc92de3535860b661331d84f0c3295877a8ce212581051cc01e6910bbe7cda@[::]:35425?discport=0"
t=2018-05-16T12:34:21+0000 lvl=info msg="Mapped network port"            proto=udp extport=50485 intport=50485 interface="UPNP IGDv1-IP1"
t=2018-05-16T12:34:21+0000 lvl=info msg="Mapped network port"            proto=tcp extport=35425 intport=35425 interface="UPNP IGDv1-IP1"
t=2018-05-16T12:34:23+0000 lvl=eror msg="failed to compute offset"       error="RPC failed: read udp 192.168.1.103:38697->79.111.152.13:123: i/o timeout; read udp 192.168.1.103:52460->79.111.152.13:123: i/o timeout; read udp 192.168.1.103:33889->79.111.152.13:123: i/o timeout; read udp 192.168.1.103:41531->79.111.152.13:123: i/o timeout."
t=2018-05-16T12:34:23+0000 lvl=info msg="started whisper v.6.0"
t=2018-05-16T12:34:23+0000 lvl=info msg="Handlers registered"            package=status-go/geth/api.StatusBackend
t=2018-05-16T12:34:23+0000 lvl=info msg="Account reselected"             package=status-go/geth/api.StatusBackend
t=2018-05-16T12:34:23+0000 lvl=info msg="Whisper identity selected"      id=a04ef2011400fdc4539b1b3e9d8f96d779829cdd4be4d2cc6e39c31595089bdb key=0x04e6f0ef8ef109734b15ac5bbdbee78ed66b510b3c9fea2fdae05b48debf95bb9f0e0abdfeffb28fdc1bf20bb8c1e0864725813aa3aa6957979ce9d2d4a2e17c25
t=2018-05-16T12:35:53+0000 lvl=info msg="App State changed"              package=status-go/geth/api.StatusBackend new-state=background
```

**Comment by oskarth** [comment]
See https://github.com/status-im/status-cluster/issues/107

Note that adding custom bootnodes/mailserver is a partial remedy for this, but it requires additional testing w.r.t connectivity. Right now it isn't clear to me that a user in Russia with custom bootnodes/mailserver will be able to connect with users who rely on our nodes.

@adambabik @dshulyak thoughts?

**Comment by adambabik** [comment]
Currently, each of our nodes in the cluster gets a bootnode address so the discovery starts from the server nodes. 

If we allow users to use custom bootnodes, those bootnodes must be aware of our server nodes which means the whole mechanism needs to work in an opposite way (from bootnodes). 

geth's `bootnode` does not support that so we probably need to slightly modify our bootnode in status-go and provide instructions how to start such a bootnode.

**Comment by dshulyak** [comment]
We have such mechanism https://github.com/status-im/status-go/tree/develop/cmd/bootnode

**Comment by oskarth** [comment]
With https://github.com/status-im/status-cluster/issues/107#issuecomment-393140182 this should work, just need to add to default and verify end to end

cc @PombeirP @cammellos @flexsurfer
