### ISSUE TITLE
Update icons for featured DApps

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4300]
### User Story

As a user, I want DApp icons to be clearly visible. 

### Description

*Type*: Feature

*Summary*: 
Update the list of DApp icons: 

- Each must be visible against a white background. 

- Remove the double dot icon from the corner of each.

#### Expected behavior
All featured DApp list icons contrast with the Home screen and have Status ".." element removed.

#### Actual behavior
Certain DApp icons have white backgrounds and the visual effect is poor.
".." badge on every icon. 

<img src="https://user-images.githubusercontent.com/15470435/40116797-1169724c-5915-11e8-9c54-ccbd31ee4003.jpg" width=250/>

**Comment by denis-sharypin** [comment]
Put new icons with the same names to my dropbox acc:
https://www.dropbox.com/sh/cj3leivdetfsgo0/AAB6wp9bl6QihqJV4n4_5VwTa?dl=0

**Comment by status-open-bounty** [comment]
Balance: 0.0 ETH
Contract address: [0x68d93f7ff60523ca363072b952714039166b7ae5](https://etherscan.io/address/0x68d93f7ff60523ca363072b952714039166b7ae5)
Network: Mainnet
Paid to: jeluard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
