### ISSUE TITLE
Do not allow empty command to be sent

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#4309]
### User Story

As a user, I don't want to be allowed to send the empty command (`/`) by mistake 

### Description

*Type*: Bug

Make the send button (arrow on blue background) disabled when no command is selected.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 940.00
Contract address: [0xcafcb858e4da00f3e55acb0a3870defd73ad3b3f](https://etherscan.io/address/0xcafcb858e4da00f3e55acb0a3870defd73ad3b3f)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
@jeluard Hi! Have posted fix for this issue at https://github.com/status-im/status-react/pull/4465  :pizza: :beer:

**Comment by jeluard** [comment]
@pacamara Awesome thanks! Just added some comments.
