### ISSUE TITLE
Add category headers to DApp screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4310]
### User Story

As a user, I want to know what types of DApps are available by category, so I have better context into what they do.

### Description

*Type*: Feature

*Summary*: 
Use text headers to break the DApp list into categories:

- Exchanges: Airswap, Bancor, ERC dEX, Kyber, Oasis Direct
- Marketplaces: CryptoCribs, Ethlance, OpenSea, Name Bazaar
- Fun & Games: CryptoKitties, CryptoFighters, CryptoPunks, Etherbots
- Social Networks: Cent, Peepeth
- Utilities: Hexel

#### Expected behavior

"Open DApp" screen presents a list with category titles. 

<img src="https://user-images.githubusercontent.com/15470435/40165936-8d6d034c-59bd-11e8-8981-14cc5bdf32b4.png" width=250 />

#### Actual behavior

"Open DApp" screen contains an alphabetical list of DApps.

**Comment by flexsurfer** [comment]
@rachelhamlin can we add `For developers` section, which will be visible only in dev mode?
