### ISSUE TITLE
Timeout is not ISeqable error dialog is shown

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4316]
### Description

*Type*: Bug

*Summary*: I got the following error after entering #staus public channel and staying there for ~2 mins waiting for the chat history. The history did not appear.

<img src="https://user-images.githubusercontent.com/7532782/40177830-f2fbd3b0-59df-11e8-8fc5-5f0862919121.png" width="200">

#### Expected behavior
There is no error and the chat history appears.

#### Actual behavior
Error appeared and there was no chat history.

### Reproduction

- Open Status
- Switch to Ropsten
- Join #status public chat
- Wait for some time. The error should appear

### Additional Information
* Status version: nightly, May 17, 436ac1d
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
Maybe related to #4312

**Comment by pedropombeiro** [comment]
I had this the other day and seemed to be related to flaky network, restart helped: https://status-im.slack.com/archives/C8QP8S5UH/p1526370620000250

We should probably just surface a more meaningful error if that's the case.

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/C8QP8S5UH/p1526370620000250">Slack</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
nightly May 18, Android 8.1.0 real Pixel XL: "502 Bad Gateway  is not ISeqable" error shown right after I've logged in.
TF log/video: https://app.testfairy.com/projects/4803622-status/builds/8311330/sessions/53/?accessToken=8CRAKjHvQHPI9fz0uXtIq2-lrpI
geth.log: 
[geth (13).log](https://github.com/status-im/status-react/files/2015966/geth.13.log)

**Comment by mandrigin** [comment]
fixed in #4337
