### ISSUE TITLE
Migrate from `react-native-fcm` to `react-native-firebase`

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4327]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to upgrade from `react-native-fcm` to `react-native-firebase` so that I have access to the latest APIs and bugfixes.

The `react-native-fcm` package is no longer guaranteed to have any active development, while `react-native-firebase` has great backing:

![image](https://user-images.githubusercontent.com/138074/40193000-42365362-5a06-11e8-950b-23d2443adf6f.png)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: Follow steps in https://github.com/evollu/react-native-fcm#to-existing-react-native-fcm-users to upgrade current setup to `react-native-firebase`

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1800.00
Contract address: [0x0df6a1275789b1cbf43c8ac59105de193e24436b](https://etherscan.io/address/0x0df6a1275789b1cbf43c8ac59105de193e24436b)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by georgiemathews** [comment]
I’ll start working on this

**Comment by pablanopete** [comment]
@georgiemathews thank you for your work on this bounty; unfortunately sorry for the slow response on bounty payout, could you drop your wallet address here so I can send you the bounty amount Out of Band while we wait on a dashboard fix in Status Open Bounty.

If you don't feel comfortable putting it here in the comment could you email a ERC20 compatible wallets address to me? chris.hutchinson@status.im

**Comment by pablanopete** [comment]
Payment Sent!
