### ISSUE TITLE
User can add a custom mailserver

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4328]
### User Story

As a user, I want to add a new mailserver so that I can make sure it isn't blocked.

Fixes https://github.com/status-im/status-react/issues/4299

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: An adversary can easily block mailserver IPs and our users won't be able to communicate. To prevent this users should be able to specify their own mailserver addresses.

Similar to https://github.com/status-im/status-react/issues/4264

#### Expected behavior
A user can specify their own mailserver

#### Actual behavior
Only Status mailservers can be selected

### Solution

Status already has an Advanced setting called "offline messages". We can extend this to include adding new mail servers.

The design pattern should follow https://github.com/status-im/status-react/pull/4239

Changes:

- Change copy "Offline messages" to "Mailserver" in advanced settings, and on the settings screen
- Add a ➕ icon to the mailserver listing screen
- Based on the work done in https://github.com/status-im/status-react/pull/4239, add a new screen with `name` and `address` fields.
- Add categories to the mailserver list page with headings "Status mailservers", and when a user has added one show "Custom mailservers"
- Custom mailservers can be tapped with a detail screen showing a connect button, field to edit the address, and a delete button.

**Comment by chadyj** [comment]
Here is a quick wireframe based on the work of https://github.com/status-im/status-react/pull/4239

@andmironov might want to give it some polish 😉

<img width="969" alt="screen shot 2018-05-17 at 7 53 08 pm" src="https://user-images.githubusercontent.com/116099/40194949-538bed56-5a0c-11e8-96cb-8ba98dd042dd.png">

**Comment by cammellos** [comment]
Adding & using a bootnode has been addressed, it's feature flagged but ready to be used/tested in develop builds. Will focus on bootnodes for now as higher priority, and then move to adding QR codes & deleting/edit for both.

**Comment by oskarth** [comment]
@cammellos Are you blocked in some way for this?

**Comment by cammellos** [comment]
@oskarth no, first iteration has been merged and is ready to test in develop, it does not support using a custom password for now, but I will add that later.
