### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#433]
1. Don't add contact to the contacts list until `contact request` will be approved
2. We need some way to "remind" user about pending `contact requests` (in chat, chats screens or elsewhere)

**Comment by jarradh** [comment]
also there is bug, if you add me, then we chat, but i dont add you, then i change status then add you, you do not receive my status

**Comment by jarradh** [comment]
so we have this screen for adding contacts of new participants in group chats, which I don't think is implemented; 
https://zpl.io/1WXKP9

We could repurpose it for new chats also like so;
<img width="364" alt="idea1" src="https://cloud.githubusercontent.com/assets/2714786/20243467/cc9c0db8-a98a-11e6-9e9c-d8ef6e7897c8.png">

**Comment by alwx** [comment]
I don't know why it had happened again, but this feature was finished some time ago, and after that you've removed it without any reason.

https://github.com/status-im/status-react/pull/215
https://github.com/status-im/status-lib/pull/12

It is a bit upsetting by the way :(

**Comment by alwx** [comment]
There are still some methods like `send-contact-request` and `Add to contacts` menu item still exists, but key exchange mechanism is completely broken.
