### ISSUE TITLE
Update to react-native 0.55.4

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#4334]
Update react-native version to 0.55.4

Main advantages:
- performance improvement (more features for native drivers for animations)
- letter spacing in android
- keyboard fix for certain devices
- bug fixes

To check:
- no regressions

Bounty might be increased if it turns out that the update required more changes than expected.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 920.00
Contract address: [0xf0ba9c96f799bbf60b115b2965bef3d76659be56](https://etherscan.io/address/0xf0ba9c96f799bbf60b115b2965bef3d76659be56)
Network: Mainnet
Paid to: pacamara
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pacamara** [comment]
Hi @yenda , have posted fix for this at https://github.com/status-im/status-react/pull/4376  :beers:
