### ISSUE TITLE
Discover double shown messages, message ordering & cannot tap users

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#434]
cannot tap any users in discover and start chat / send contact request

Message ordering is wrong in Recents
this should have been;
Jarrad: #buying #eth and #milk 
Roman: i'm #buying eth also
Jarrad: #buying #eth

![screenshot_20161109-211510](https://cloud.githubusercontent.com/assets/2714786/20141052/8d47461e-a6c9-11e6-92df-da557ea75d57.png)

double shown messages and blank space

![screenshot_20161109-211235](https://cloud.githubusercontent.com/assets/2714786/20141092/bf8949ec-a6c9-11e6-8109-4649123cf9d1.png)

**Comment by alwx** [comment]
I've updated the layouts (now everything looks good on both iOS and Android), made icons tappable and fixed the issue with dupicates + updated the way Discovery works. Going to finish this task completely tomorrow.

<img width="479" alt="screen shot 2016-11-11 at 15 02 43" src="https://cloud.githubusercontent.com/assets/911127/20222919/34eee4a6-a848-11e6-9a6d-5c90c65a8e93.png">
<img width="459" alt="screen shot 2016-11-11 at 15 02 45" src="https://cloud.githubusercontent.com/assets/911127/20222921/35cc2a96-a848-11e6-8b2b-ad0ce21c99c4.png">
