### ISSUE TITLE
TestFlight/Play  nightly uploads should be release versions

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4340]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer and tester, I want release builds to deploy to release platforms so that I can test release candidates in release scenarios. 

### Description

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Jenkins uploads nightly builds to TestFlight/Play, but these are dev builds.  In order to properly test releases and upgrades we should test release builds through Tetflight and Play. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Jenkins/Fastlane uploads nightly release builds. 

#### Actual behavior
[comment]: # (Describe what actually happened.)
Jenkins/Fastlane uploads nightly dev builds.

**Comment by oskarth** [comment]
Removing from Beta milestone as it is in backlog

**Comment by chadyj** [comment]
Closing as nightlies will no longer go to TF

**Comment by rn-g** [comment]
> Closing as nightlies will no longer go to TF
Why is that? Apple restricted this?
