### ISSUE TITLE
Prevent long spammy messages

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4343]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to avoid seeing spammy/junk/empty messages so that I can focus on the chat experience.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Status messages can be full of line feeds that create long empty messages.  Sometimes users take advantage of this to spam the chat and prevent other users from reading messages.

<img width="322" alt="screen shot 2018-05-18 at 4 41 48 pm" src="https://user-images.githubusercontent.com/116099/40241089-62561e2a-5aba-11e8-8b44-35823ed2831f.png">

Other users have pasted dozens of long messages filling the chat window and slowing down the app.

<img width="317" alt="screen shot 2018-05-18 at 8 08 45 pm" src="https://user-images.githubusercontent.com/116099/40250666-4c797c92-5ad7-11e8-9ea0-7650e2ce8d75.png">

#### Expected behavior
Message are shown

#### Actual behavior
Spammy messages can be shown

### Reproduction
Start a chat and insert lots of line endings.
Or copy/paste crazy long messages.

### Solution

Slack and some other apps prevent empty messages by trimming any trailing line endings or spacing. Eg if you enter "hello \n\n\n\n\n\n\n\n\n\n\n\n" slack will only send "hello".

However a user could also do "hello \n\n\n\n\n\n\n\n\n\n\n\n hello \n\n\n\n\n\n\n\n\n\n\n\n" and recreate the issue.  

Possible solutions could be to limit consecutive line endings, or spaces. Or even limit the message length to a certain amount of characters.

@VoR0220 Suggested only showing the first part of a long message, with an option for the user to expand for more.

Other approaches could be adding a 'ban user' feature so that users could remove jerky users.

**Comment by VoR0220** [comment]
Could also have an "expand" option for messages that exceed 300 chars.

**Comment by yenda** [comment]
@chadyj yes I think for beta we need expand feature for messages more than 20 lines, can be a purely UI thing.  What do you think of editing the issue into expand feature and make it a prio for beta ?

**Comment by yenda** [comment]
https://facebook.github.io/react-native/docs/0.53/text.html#numberoflines

I tried this and it doesn't work out of the box, so I'd say this is probably an M issue

<blockquote><img src="/react-native/img/favicon.png" width="48" align="right"><div><strong><a href="https://facebook.github.io/react-native/index.html">Text · React Native</a></strong></div><div>A React component for displaying text.</div></blockquote>

**Comment by chadyj** [comment]
> @chadyj yes I think for beta we need expand feature for messages more than 20 lines, can be a purely UI thing. What do you think of editing the issue into expand feature and make it a prio for beta ?

@yenda Sounds good for beta. I'll add it to the milestone.
cc @andmironov

**Comment by andmironov** [comment]
https://github.com/status-im/status-react/issues/4437
