### ISSUE TITLE
Update launch screens

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#4347]
### User Story

As a user, I want to see a consistent brand across platforms so that.

### Description

*Type*: Improvement

#### Expected behavior
<img width="361" alt="screenshot 2018-05-18 17 40 38" src="https://user-images.githubusercontent.com/6559881/40244262-b2c926d8-5ac2-11e8-9983-7a897c42f69d.png">

#### Actual behavior
<img width="392" alt="screenshot 2018-05-18 17 41 09" src="https://user-images.githubusercontent.com/6559881/40244254-ad5a8ebc-5ac2-11e8-9814-38a7ebdf7933.png">

### Solution

*Summary*:  You need to take new assets from my dropbox https://www.dropbox.com/sh/lj8fa2e75a2ozwe/AADpHMh4mdFX--Y_TyrNp2dQa?dl=0
and replace them here: 

ios:
https://github.com/status-im/status-react/tree/develop/ios/StatusIm/Images.xcassets/LaunchImage.launchimage

Android:
1. https://github.com/status-im/status-react/tree/develop/android/app/src/main/res/drawable-xxhdpi
2. https://github.com/status-im/status-react/tree/develop/android/app/src/main/res/drawable-xhdpi

### Additional Information
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 460.00
Contract address: [0x1982b39ac8b90eaf6a4596e008cb8ac1368260db](https://etherscan.io/address/0x1982b39ac8b90eaf6a4596e008cb8ac1368260db)
Network: Mainnet
Paid to: georgiemathews
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by georgiemathews** [comment]
on it!

**Comment by rachelhamlin** [comment]
@georgiemathews awesome! We'd love to have this and #4362 updated for beta.

**Comment by jeluard** [comment]
@georgiemathews Do you need any help?

**Comment by georgiemathews** [comment]
the LaunchScreen1125x2436.png is missing, seems like this was added 3 months ago for iPhone X, not present in the delivered assets, could I get that one as well?

**Comment by jeluard** [comment]
@denis-sharypin Can you help with that?

**Comment by denis-sharypin** [comment]
@georgiemathews  added here https://www.dropbox.com/s/tdrhqvw8f6h8fo8/LaunchScreen1125x2436.png?dl=0

<blockquote><img src="https://www.dropbox.com/temp_thumb_from_token/s/tdrhqvw8f6h8fo8?preserve_transparency=False&size=1024x1024&size_mode=2" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/tdrhqvw8f6h8fo8/LaunchScreen1125x2436.png?dl=0">LaunchScreen1125x2436.png</a></strong></div><div>Shared with Dropbox</div></blockquote>

**Comment by rachelhamlin** [comment]
@georgiemathews thanks for your help with this!
