### ISSUE TITLE
Setup CI Jenkins builds

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#4352]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a quality assurance engineer, I want to have application binaries for the verification of every made PR or merged commit into master branch.
As a developer, I want automated tests and build run for any new my PR made.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Setup Jenkins builds of StatusIm Desktop

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
It's possible to obtain application binaries for every made PR and latest master branch sources.

#### Actual behavior
[comment]: # (Describe what actually happened.)
There is no Jenkins Pipeline set for StatusIm Desktop.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [x] Jenkins Pipeline for StatusIm Desktop
- [x] Mac OS builds of StatusIm Desktop available for download
- [ ] Windows builds of StatusIm Desktop available for download
- [x] Linux builds of StatusIm Desktop available for download

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: unknown
* Operating System: Windows, Linux, Mac OS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by churik** [comment]
Irrelevant
