### ISSUE TITLE
No mixpanel event for logout

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4359]
### Description

*Type*: Bug

*Summary*: When user logs out, it's not tracked in Mixpanel. But, according to https://github.com/status-im/status-react/blob/develop/src/status_im/utils/mixpanel_events.cljs#L23 there should be `Logout` event.

#### Expected behavior
Logout event is tracked and can be seen in Mixpanel.

#### Actual behavior
Logout event is not tracked.

### Reproduction

- Open Status
- Create account and turn on data sharing
- Log out

### Additional Information
* Status version: nightly, May 21
* Operating System: Android, iOS

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by lukaszfryc** [comment]
@chadyj should logging out be tracked in Mixpanel?

**Comment by chadyj** [comment]
Yep

**Comment by lukaszfryc** [comment]
We do not use Mixpanel anymore
