### ISSUE TITLE
Typing fast on iOS amount field leads to incorrect sums

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4361]
### Description

*Type*: Bug

*Summary*:  when i type fast on iOS small sums like 0,0094 it appears as 94

#### Expected behavior
when i enter anount in Amount field it is shown correctly 

#### Actual behavior
wrong amount is shown (2 instead of 0,02)

### Reproduction
- Open Status
- Go to wallet - send
- Enter 0,02 amount quickly in amount field

**Comment by annadanchenko** [comment]
on 0.9.19 release build 9 can reproduce similar issue: typed 1,001 but got 11 in the amount field
![amountissue](https://user-images.githubusercontent.com/6584810/40418514-e2446f44-5e82-11e8-9db9-d18e09331077.gif)

**Comment by annadanchenko** [comment]
Sometimes when typing 1,000000 it becomes ,000000 or 100000
![amount typing 2](https://user-images.githubusercontent.com/6584810/40430781-304cb8c2-5ea6-11e8-932a-4e13339c6807.gif)
