### ISSUE TITLE
Update app icons

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#4362]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I need to see to consistent brand all over platforms.

### Description

*Type*: Improvement 

We updated our brand glyph and color 4 months ago, but we haven't applied it to app icons yet.

#### Expected behavior
ios
<img width="322" alt="screenshot 2018-05-21 14 12 21" src="https://user-images.githubusercontent.com/6559881/40306994-16e7b1a8-5d01-11e8-9ee8-5c8cd7d749fa.png">

Android:
<img width="510" alt="screenshot 2018-05-21 14 36 37" src="https://user-images.githubusercontent.com/6559881/40307904-88c8f108-5d04-11e8-8ae8-e22fabf1b1dc.png">

#### Actual behavior
![img_5297](https://user-images.githubusercontent.com/6559881/40306951-ef0bc980-5d00-11e8-930a-074d04fcfdc5.png)

### Solution
*Summary*: Replace Android and iOS app icons by new ones

iOS icons — https://www.dropbox.com/sh/xei7mqgvbr9ml5r/AAAgK6DsexQrTJCd_vXk3Ac_a?dl=0
Android icons — https://www.dropbox.com/sh/xzx2j6ixj5fq1bo/AAC3wNcHV97fcM8dSAM2v6dPa?dl=0

### Additional Information
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 460.00
Contract address: [0xc9052464dfed0a1962ae6dd1e4ffe422fb5769a2](https://etherscan.io/address/0xc9052464dfed0a1962ae6dd1e4ffe422fb5769a2)
Network: Mainnet
Paid to: georgiemathews
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by georgiemathews** [comment]
working on it

**Comment by georgiemathews** [comment]
I'm missing the following icon sizes for

android:
res/mipmap-ldpi/ic_launcher.png - 36x36

ios:
AppIcon.appiconset/Icon-72.png
AppIcon.appiconset/Icon-72@2x.png
AppIcon.appiconset/Icon-Small-50.png
AppIcon.appiconset/Icon-Small-50@2x.png
AppIcon.appiconset/Icon.png - 57 x 57
AppIcon.appiconset/Icon@2x.png - 114 x 114

**Comment by denis-sharypin** [comment]
@georgiemathews I added what's left. Would you mind to take a look?

iOS:
https://www.dropbox.com/sh/ums7z6miocrlmh2/AAAJVPeqTP5mw13zJmDtpG_6a?dl=0

Android:
https://www.dropbox.com/sh/hjbah1wy1lqimc2/AAAlXGsUh8CtGiIns32TcB9Ra?dl=0

<blockquote><img src="https://cfl.dropboxstatic.com/static/images/icons128/folder_dropbox.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/sh/ums7z6miocrlmh2/AAAJVPeqTP5mw13zJmDtpG_6a?dl=0">left</a></strong></div><div>Shared with Dropbox</div></blockquote>
<blockquote><img src="https://cfl.dropboxstatic.com/static/images/icons128/folder_dropbox.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/sh/hjbah1wy1lqimc2/AAAlXGsUh8CtGiIns32TcB9Ra?dl=0">left</a></strong></div><div>Shared with Dropbox</div></blockquote>
