### ISSUE TITLE
0 USD showing after adding ether to address on rinkeby network

### ISSUE THREAD

**Issue by mlennie** [status-im/status-react#4371]
### Description

I downloaded the newest status app for android and switched to rinkeby network. 

I sent rinkeby ether via rinkeby faucet to my address given on status. There are more than 300 confirmations but I still see 0 USD. Is that normal?

How can I see the amount I have in my rinkeby account via status?

**Comment by annadanchenko** [comment]
@mlahia If you switched to Rinkeby (not to Rinkeby with upstream RPC) then app needs some time to sync and only after it's completed you can see the balance. Instead, you can switch to Rinkeby with upstream RPC network (so infura is used and no syncing is required).
