### ISSUE TITLE
Improve browser security warning

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4380]
### User Story

As a user, I want to know about the security of websites in the Status browser.

### Description

*Type*: Feature

*Summary*: 
Design update for #4298:

- For **Status curated DApps and websites with valid `HTTPS` certificate**, show security lock icon in the browser bar. Message on-click:
```Connection is secure. Make sure you really trust this site before signing transactions or entering personal data.```

[Link to icon SVG ](https://status-im.slack.com/files/U61UDMS5D/FBDG257GA/icon_lock-black.svg)

e.g.
<img src="https://user-images.githubusercontent.com/15470435/41862274-b9ebee7e-78a3-11e8-9cde-b0354e4ef49b.png" width =400/>
<br><Br>

- For **websites with no SSL certificate**, show warning with icon in the browser bar. Message on-click:
```Connection is not secure! Do not sign transactions or send personal data on this site.```

[Link to icon SVG ](https://status-im.slack.com/files/U61UDMS5D/FBEDL2UNA/icon_lock_opened-black.svg)

- For **websites with invalid `HTTPS` certificate**, block users from navigating to these sites and present an error page. 

@jeluard which error page do we need here? 

#### Expected behavior
For HTTPS sites, a security icon in browser bar displays the appropriate security message on-click.

For others, a warning message about the insecure connection is presented. 

#### Actual behavior
A warning message is displayed for any site.

**Comment by rachelhamlin** [comment]
@jeluard This requires a few other changes, but want to get designs ready. :) 

Is the first bullet accurate? Are we 100% confident in saying that curated DApp connection is secure?

**Comment by jeluard** [comment]
In theory they would trust the website as they trust us. But it's probably safer to have this message anyway.

For second item: connection is proven secure *but* they have to trust the URL they are navigating is the right one. So the same message as first item would be ok.

Then we have https websites with incorrect certificate: we should prevent navigation to those and put a big warning.

Lastly there are http websites. An option could be to not inject web3 for those?

**Comment by rachelhamlin** [comment]
Sounds good on the first item @jeluard.

With regard to HTTP sites, if we don't inject web3, what will be the consequences?

Let's also add a warning to them. Chrome allows users to visit HTTP sites, but this year they'll be [adding a stronger warning](https://www.theverge.com/2018/2/8/16991254/chrome-not-secure-marked-http-encryption-ssl).

With regard to incorrect certificates, should we give users the option to ignore our warning? Sometimes this is possible in browsers like Chrome, under an advanced button, but emphasis is on `Back to safety`.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1000.00
Contract address: [0xf3e77d01fe3e8a3fbcb42a5466a018e891557830](https://etherscan.io/address/0xf3e77d01fe3e8a3fbcb42a5466a018e891557830)
Network: Mainnet
Paid to: flexsurfer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
