### ISSUE TITLE
'Network does not match' error when scan wallet QR code in the same network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4381]
*Type*: Bug 

*Summary*: When I scan wallet QR code - the pop-up with `Network does not match: ethereum: 0x04......... but current chain is <no value>` error appears. It happens when both contacts are on Mainnet RPC / Ropsten RPC networks. 

#### Expected behavior
No errors when scanning Wallet QR code. Specify Recipient value is updated with the wallet code. 

#### Actual behavior
<img width="238" alt="screen shot 2018-05-22 at 16 28 06" src="https://user-images.githubusercontent.com/8749671/40365896-65d3fd2a-5dde-11e8-959b-af93de6be6c2.png">

### Reproduction

- Open Status and create new account (using Develop build you should be on Mainnet RPC by default)
- Navigate to `Wallet` -> `Send transaction` -> `Specify Recipient`
- Tap `Scan QR code` and scan any valid QR code (e.g. see below QR code screen) 
<img width="424" alt="screen shot 2018-05-22 at 16 32 28" src="https://user-images.githubusercontent.com/8749671/40365904-6f858758-5dde-11e8-8d56-a4fd4f5bc080.png">

### Additional Information
* Status version: Develop 398th Jenkins nigtly build (`ff86ea7f`)
* Operating System: Android and iOS

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8320347/sessions/106/?accessToken=eNtJM8MlIYBHm9IuN/e7QNGAgXc

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8320347/sessions/106/?accessToken=eNtJM8MlIYBHm9IuN/e7QNGAgXc">TestFairy: Status build-6005+ (6005) @106</a></strong></div></blockquote>

**Comment by SvenMeyer** [comment]
status.im version : 0.9.28 (9098); node 0.15.0

I have the same problem trying to send ETH on Ropsten from status.im to another MEW account on ropsten.
- display QR code in MEW
- scan (address looks correct)
- ERROR : Network does not match ethereum:0x ... but current chain is 3

![screenshot_20180930-130458](https://user-images.githubusercontent.com/25609/46252923-9ef75700-c4b3-11e8-9507-b8d76b8c56b1.png)
