### ISSUE TITLE
Chat list contains browser duplicates

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4389]
### Description

*Type*: Bug

*Summary*: Duplicated browser chats appears in chat list when the same url in a chat is opened multiple times. Rather than duplicating the chat items, existing chat with the url should be opened and bring on top of the chat list.

#### Expected behavior
There are no duplicates in chat list. When link is opened again, the last chat is brought to the top of the list.

#### Actual behavior
Chat list contains browser duplicates with the same url. 

### Reproduction

- Open Status
- Go to 1-1 or public chat
- Click on a link in the chat
- Go to chat list 
- Open the chat and click on the link again
- Go back to chat list. It contains 2 browser items with the same url:
<img src="https://user-images.githubusercontent.com/7532782/40415713-dbd0360e-5e7b-11e8-9544-c88d5b114e6e.png" width="200">

### Additional Information
* Status version: nightly, May 23
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
Note that if the urls are different, new browser chat item should be created

**Comment by yevh-berdnyk** [comment]
looks like a duplicate of #3604

**Comment by lukaszfryc** [comment]
Yes, closing.
