### ISSUE TITLE
Show Offline when user is connected to public wifi which requires authorization (by sms or whatever)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4392]
### User Story

As a user, I want to use Status anywhere including public wifi. Some of the public wifi networks require authentication, so a user is connected to WiFi but without any internet, until he bypasses the registration (by SMS typically in my place). In this case Status is not shown as offline, however, no messages received (due to the reason described above). 

### Description

*Type*: Bug

*Summary*: I am not shown offline when I am connected to WiFi without internet access. When I get the connection finally and Status is not restarted - I refresh wallet multiple times with no effect, balance is not updated. 

#### Expected behavior

1. Show `Offline` when being connected to WiFi without internet access
2. Reconnect to the network when the internet access is revealed (like i bypass the verification and internet access is granted)

### Reproduction

- Open Status
- Connect to WiFi without internet access (but with authorization) 
- Check Status app

**Comment by yenda** [comment]
@asemiankevich in the latest nightlies with the signal handling should show "Connecting to peers..." ? We could put a timeout of one minute and show "Offline" if it can't connect, it should reconnect automatically already.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa4d2d01681a167324050b3391b4c06c5ac04f609a88eb0e6f2e205c88f7c92be](https://etherscan.io/tx/0xa4d2d01681a167324050b3391b4c06c5ac04f609a88eb0e6f2e205c88f7c92be)
