### ISSUE TITLE
Username overlaps Done button

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4393]
### Description

*Type*: Bug

*Summary*: Long username overlaps done button. Instead, name should have dynamic font that gets smaller if there is no space.

#### Expected behavior
Username does not overlap other texts.

#### Actual behavior
<img src="https://user-images.githubusercontent.com/7532782/40421288-acb859f4-5e8b-11e8-87f9-55ef9ac181d9.png" width="200">

### Reproduction

- Open Status
- Set long username
- Open contact code sharing screen and check the titlebar

### Additional Information
* Status version: nightly, May 23
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 500.00
Contract address: [0x74468960fe2b26cec74edf0a386bbb5bc04851d4](https://etherscan.io/address/0x74468960fe2b26cec74edf0a386bbb5bc04851d4)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: tbenr
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by lukaszfryc** [comment]
@tbenr a long username got smaller but it still covers the done button:

<img src="https://user-images.githubusercontent.com/7532782/44570443-2d264200-a77e-11e8-902f-ab17fa474ab2.png" width="200">

No one will probably use such long names but anyway, let's not make the text smaller but instead truncate it with "..." at the end. By this, we will make sure it always look good even with long usernames on small devices.

Thanks!

**Comment by tbenr** [comment]
@lukaszfryc - going back from vacation. Next week I'll apply the changes.

**Comment by tbenr** [comment]
@lukaszfryc changes applied.

**Comment by pablanopete** [comment]
Any review for this one? @lukaszfryc

**Comment by lukaszfryc** [comment]
@pablanopete it's still in progress. The conversation is happening in https://github.com/status-im/status-react/pull/5229
