### ISSUE TITLE
Hide group chats outside of dev mode

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4396]
### User Story

As a user, I want unusable features to be hidden.

As a developer, I want the option to code against the group chat feature.

### Description

*Type*: Bug

*Summary*: 

Hide "Start group chat" feature unless user is in developer mode, for all builds.

#### Expected behavior
"Start group chat" does not appear in this list unless I am in developer mode:

<img src="https://user-images.githubusercontent.com/15470435/40424297-7553e23a-5e95-11e8-8353-c795dea6bec6.JPG" width=250 />

#### Actual behavior
"Start group chat" is available by default.

### Reproduction

- Open Status nightly
- Go to "+" New screen

### Additional Information
* Status version: Nightly 2018-05-23
* Operating System: iOS

**Comment by pedropombeiro** [comment]
@rachelhamlin I thought this was already taken care of in https://github.com/status-im/status-react/pull/4054 with https://github.com/status-im/status-react/blob/develop/.env.prod#L20 ?

Update: Nevermind, this is about disabling it for nightlies as well :+1:

**Comment by rachelhamlin** [comment]
@PombeirP and also enabling it for dev mode—not sure if that's covered but 0.9.18 doesn't support it
