### ISSUE TITLE
Re-opened application today, wallet transaction message decorators gone?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#440]
- open application
- open wallet in chats
- slide down suggestions area
- see this ;
![reopen-app-message-icons-gone](https://cloud.githubusercontent.com/assets/2714786/20164519/684a76d4-a740-11e6-9f8c-1562ad7473d4.png)

- if i go back, open roman, i see transaction message decorators just fine
- then press back and goto wallet again, transaction message icons appear

**Comment by jarradh** [comment]
@rasom was this fixed in the send transaction messaage type PR ?

**Comment by rasom** [comment]
@jarradh Yes, it was
