### ISSUE TITLE
Show failed transactions in transaction history as failed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4402]
### User Story

As a user I want clear information about transactions I made

### Description

*Type*: Bug

*Summary*: Failed transactions should be shown in transaction history as Failed

#### Expected behavior
https://ropsten.etherscan.io/tx/0x716eefb91b2d33f63687222f2db2125813098f61fb744d9ea0878a3c45e239ed should be shown as Failed so i am clear enough what has happened with my funds

#### Actual behavior
Failed transactions are not marked as such so i am expecting them to be processed normally when it is basically not

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://ropsten.etherscan.io/tx/0x716eefb91b2d33f63687222f2db2125813098f61fb744d9ea0878a3c45e239ed">Ropsten Transaction 0x716eefb91b2d33f63687222f2db2125813098f61fb744d9ea0878a3c45e239ed</a></strong></div><div>Ropsten (ETH) detailed transaction info for 0x716eefb91b2d33f63687222f2db2125813098f61fb744d9ea0878a3c45e239ed</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1000.00
Contract address: [0xcdb353ae7cfece4671ccad2f48e8f32274755c7d](https://etherscan.io/address/0xcdb353ae7cfece4671ccad2f48e8f32274755c7d)
Network: Mainnet
Paid to: goranjovic
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by denis-sharypin** [comment]
Design:
<img width="807" alt="screenshot 2018-06-08 14 43 09" src="https://user-images.githubusercontent.com/6559881/41158993-430764b2-6b2b-11e8-8c82-968935792669.png">
Icon:
https://www.dropbox.com/s/kfdz7s2q8lg2fkf/icon_exclamation_mark-black.svg?dl=0



<blockquote><img src="https://www.dropbox.com/temp_thumb_from_token/s/kfdz7s2q8lg2fkf?preserve_transparency=False&size=1024x1024&size_mode=2" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/kfdz7s2q8lg2fkf/icon_exclamation_mark-black.svg?dl=0">icon_exclamation_mark-black.svg</a></strong></div><div>Shared with Dropbox</div></blockquote>
