### ISSUE TITLE
"Realm file decryption failed" error after app upgrade from release 0.9.18 to develop version

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4409]
***Type***: Bug

***Summary***: `Unable to open a realm at path 'data/data/im.status.ethereum/filesdefault.realm': Realm file decryption failed` error appears when I open the app after upgrade from Release 0.9.18 to Develop build (`build-6009+` nightly 402th Jenkins build)

#### Expected behavior
No error after upgrade

#### Actual behavior
Error appears when I open the app after upgrade

<img width="301" alt="screen shot 2018-05-24 at 10 06 49" src="https://user-images.githubusercontent.com/8749671/40469755-36344572-5f3a-11e8-8524-49ed20ee64f6.png">

### Reproduction

- Install Status 0.9.18 release version
- Upgrade to nightly build and open the app

### Additional Information
* Status version: `build-6009+` nightly 402th Jenkins build
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
no special data required, just create account on 0.9.18 and update to nightly

**Comment by lukaszfryc** [comment]
@cammellos [mentioned](https://github.com/status-im/status-react/pull/4430#issuecomment-392117673) this in #4430  
> we removed the resetting of realm from develop
0.9.19 would have reset the db.

**Comment by janherich** [comment]
This isn't the case when upgrading from `0.9.19`. It would be very tricky to actually solve this properly, is it still necessary given that it doesn't impact users and soon nightly testers as well (upgrade path is `0.9.18` -> `0.9.19` -> `develop`) ?

**Comment by cammellos** [comment]
@janherich we discussed a potential way is to:

1) add a release version to the app, starting from 0.9.19. 
2) Check on startup if the version is < 0.9.19 (or blank) and reset the db if necessary.

What do you think?

**Comment by mandrigin** [comment]
yeah, @jakubgs implemented storing the current version in the `VERSION` file as opposed to the branch, so any build can know it's own version now.

**Comment by janherich** [comment]
That would be indeed the best option, we still have to keep version information in the realm persistent store, but with additional flat file containing the info as well, it's a lot less tricky/error prone to do that front-check.
