### ISSUE TITLE
Kyber app can't detect account

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4410]
### User Story

As a user, I want to log in to Kyber with my Status wallet.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*:
When logging in on Kyber, the app throws an error saying it cannot detect a Metamask account.

#### Expected behavior
Kyber detects the user's account.

#### Actual behavior

<img src="https://user-images.githubusercontent.com/15470435/40473570-d041b9d6-5f3c-11e8-917f-68a1ec0667cb.png" width=250 />

### Reproduction

- Open Kyber from DApp screen
- .Accept Terms and Conditions
- "Get Started"

### Additional Information
* Status version: nightly 2018-05-24
* Operating System: iOS

**Comment by flexsurfer** [comment]
fixed, the reason was in async coinbase request
