### ISSUE TITLE
Can't open CrytptoCribs listing from search results

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4413]
### User Story

As a user, I want to view the listings in my CryptoCribs search results.

### Description

*Type*: Bug

*Summary*: 
When I try to open my search results on CryptoCribs, nothing happens. On other browsers, I can click on each result to view details and make a booking.

#### Expected behavior
I can click on a listing to view more details.

#### Actual behavior
Nothing happens when I click on a listing.

<img src="https://user-images.githubusercontent.com/15470435/40476707-00be2f74-5f45-11e8-97d2-4226bf89cea5.png" width=250/>

### Reproduction

- Open Cryptocribs
- Enter a destination (e.g. Paris, France) and dates
- Search
- Click on a listing

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightly 2018-05-24
* Operating System: iOS

**Comment by flexsurfer** [comment]
can't repro on Android

**Comment by rachelhamlin** [comment]
@flexsurfer a few other instances. In CK, can't click on the buttons in the banner, or the Discourse button in the corner:

![image](https://user-images.githubusercontent.com/15470435/41857264-5f1f52a8-7897-11e8-81da-0096a1ee174a.png)

![image](https://user-images.githubusercontent.com/15470435/41857314-7dca53b0-7897-11e8-96df-0fb1d98ed448.png)

**Comment by flexsurfer** [comment]
that's true, same reason, both trying to open link in new tab

**Comment by flexsurfer** [comment]
will be fixed here https://github.com/status-im/status-react/pull/4919
