### ISSUE TITLE
Text input states 

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#4416]
*Type*: Bug/Feature

Text input update.

Zeplin:
Web: https://zpl.io/VOW4RvQ 
App: zpl://screen?sid=5afea0b1e6337a6f2208b589&pid=5a55d587ba304eed4d2c942f 

![input](https://user-images.githubusercontent.com/3115606/40477772-90acc9d6-5f47-11e8-88d9-5ef07d67a92d.png)

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbd10e1135bf0333f99fab0592cd58ec2749f3ef251fc62d826bba9e6c8c7509f](https://etherscan.io/tx/0xbd10e1135bf0333f99fab0592cd58ec2749f3ef251fc62d826bba9e6c8c7509f)

**Comment by adipurnama83** [comment]
nice
