### ISSUE TITLE
Top bar updates and improvements

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#4417]
*Type*: Bug/Feature

Top bar in 1-1 and Group chats has been updated

Zeplin:
Web: https://zpl.io/bPdK5nD 
App: zpl://screen?sid=5afea68a46fb41163c01a742&pid=5a55d587ba304eed4d2c942f

![top bar](https://user-images.githubusercontent.com/3115606/40477842-c4cd9c04-5f47-11e8-8390-6883aa2c1ac6.png)

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 2000.00
Contract address: [0x94c25ec00c36b57a7a043c4239bc28549dd8a3d3](https://etherscan.io/address/0x94c25ec00c36b57a7a043c4239bc28549dd8a3d3)
Network: Mainnet
Paid to: yenda
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by oskarth** [comment]
Why is this a beta blocker? Seems like enhancement that would be nice to have but not a must.

(The PR addressing this was originally in beta blocking milestone).

**Comment by lukaszfryc** [comment]
I agree. But, there is almost ready PR already: https://github.com/status-im/status-react/pull/4758
