### ISSUE TITLE
Apply  new onboarding designs

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4418]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
1) main difference in Sign Up process in mobile and desktop app is that welcome screen is missing, and after you create new account you are redirected to empty page. 

2) Also, it would be nice to  implement separate design for desktop onboarding (i.e., all these screens should be different than on small mobile screen), so separate design needed
![1_p](https://user-images.githubusercontent.com/4557972/40477279-b4b5e964-5f4e-11e8-9ac3-14b74e797371.png)
![2_p](https://user-images.githubusercontent.com/4557972/40477338-e3dfa2c0-5f4e-11e8-8d4a-71785fdea5ef.png)
![3_p](https://user-images.githubusercontent.com/4557972/40477419-09fdc536-5f4f-11e8-91c5-099876e0343d.png)

3) And for Desktop it would be nice to proceed to Next step using "Enter" key (i.e. on Step, when you enter password instead of click "Next" button just to pross "Enter" key) (moved to https://github.com/status-im/status-react/issues/4728)

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] implement welcome screen
- [ ] provide the separate design for the onboarding process

**Comment by EugeOrtiz** [comment]
Designs for welcome screen (after sign-up/in) can be found here >>> zpl.io/be4M3DP (Zeplin). @churik Onboarding process is not P0.

**Comment by churik** [comment]
@EugeOrtiz I don't see here design with "Sign in" screen before sign in and during Sign Up. Can you please provide them?

**Comment by EugeOrtiz** [comment]
Design currently WIP.

**Comment by churik** [comment]
@EugeOrtiz please provide them once it'll be ready.
Thanks!

**Comment by EugeOrtiz** [comment]
Detailed designs can be found here >> **zpl.io/V41yLW0** (Zeplin)
Examples of how it looks on MacOS here >> **zpl.io/V0yl74Q** (Zeplin)

![create account - password - filled](https://user-images.githubusercontent.com/37297779/43485425-8fc8dc32-94e7-11e8-8393-ca0593ea632b.png)

**Comment by EugeOrtiz** [comment]
@churik @chadyj The description of this issue and the designs provided can lead to confusion: we want to fully implement the new onboarding designs, right?

**Comment by churik** [comment]
Right, agree; description was changed, thanks @EugeOrtiz !
