### ISSUE TITLE
Default avatars for users and group chats

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#4419]
*Type*: Bug/Feature

Default avatars for users and group chats

Zeplin:
Web: https://zpl.io/be4G4nm 
App: zpl://screen?sid=5b0547e0062822812e56f027&pid=5a55d587ba304eed4d2c942f

![avatars](https://user-images.githubusercontent.com/3115606/40477910-f177f27c-5f47-11e8-94e5-1bc246f1029c.png)

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1000.00
Contract address: [0x81186afed105e950f5f9c3c1932e3e0a89efaf8f](https://etherscan.io/address/0x81186afed105e950f5f9c3c1932e3e0a89efaf8f)
Network: Mainnet
Paid to: cammellos
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by andmironov** [comment]
UPD:
Let's add a border to all images (regardless of is it on a white background or not) but add 40% transparency to it:

![avatars](https://user-images.githubusercontent.com/3115606/40930759-44c7f03e-6831-11e8-9c58-34fe4f9eb123.png)
