### ISSUE TITLE
Chat Empty State Updates

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#4421]
*Type*: Feature

Improve the chat empty state and use it as a place to let users know that chat is peer-to-peer and encrypted

Zeplin:
Web: https://zpl.io/2j8KlWr 
App: zpl://screen?sid=5b068b69592aae58467ab0c2&pid=5a55d587ba304eed4d2c942f

![chat empty](https://user-images.githubusercontent.com/3115606/40478849-71f912d0-5f4a-11e8-88c1-c82588f3261d.png)

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by andmironov** [comment]
The lock icon
[icon_lock-gray.svg.zip](https://github.com/status-im/status-react/files/2045278/icon_lock-gray.svg.zip)

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1000.00
Contract address: [0x8cea2242ca286a98211e1bb1e95925e4e18837c7](https://etherscan.io/address/0x8cea2242ca286a98211e1bb1e95925e4e18837c7)
Network: Mainnet
Paid to: cammellos
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
