### ISSUE TITLE
"You tried to send "ssh_version" synchronously." error while browsing a web page

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4423]
### Description

*Type*: Bug

*Summary*: The error appeared couple of times when I was on mobile connection trying to fetch https://cnn.com. I could not reproduce it afterwards.

<img src="https://user-images.githubusercontent.com/7532782/40480718-a44cfa6c-5f4f-11e8-9f09-4498f8329a93.png" width="200">

#### Expected behavior
No error.

#### Actual behavior
The error appeared couple of times when fetching a web page on mobile connection.

### Reproduction

I could not reproduce it when I tried again.

### Additional Information
* Status version: nightly, May 24
* Operating System: happened on iOS

<blockquote><img src="/favicon.ie9.ico" width="48" align="right"><div>CNN</div><div><strong><a href="https://www.cnn.com">CNN - Breaking News, Latest News and Videos</a></strong></div><div>View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN.com.</div></blockquote>

**Comment by flexsurfer** [comment]
@lukaszfryc can you recheck please, could be fixed in latest develop

**Comment by lukaszfryc** [comment]
Sure, I'll recheck tomorrow during nightly testing

**Comment by flexsurfer** [comment]
@lukaszfryc any updates?

**Comment by lukaszfryc** [comment]
I could not reproduce it in recent nightlies. Feel free to close this issue if there is nothing we can do / debug here.

**Comment by flexsurfer** [comment]
thanks @lukaszfryc so i have fixed it then :)
