### ISSUE TITLE
"Status" logo is missing on "Home" screen and has different colours  in "Sign Up" process

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4424]
### User Story

As a user, I want to see what application I'm using.

### Description
*Type*: Bug
*Summary*: 
1) there is no "Status" mention in "Home" screen (no logo neither app header)
![logo](https://user-images.githubusercontent.com/4557972/40480554-9416e754-5f57-11e8-81be-e777f45e1fe6.png)

2) "Status" logo has black instead of white colours ("Sign Up" process)
![wr_col](https://user-images.githubusercontent.com/4557972/40480564-9a1c6a70-5f57-11e8-9c66-5b98d8b719f4.png)

### In Mobile
1) Home Screen
![mog](https://user-images.githubusercontent.com/4557972/40480687-ef7387c4-5f57-11e8-9952-2aaab4fb2ddb.png)
2) "Sign Up" process
![mog](https://user-images.githubusercontent.com/4557972/40480825-4c13a5a4-5f58-11e8-8ecb-4d455faa6bf9.png)

*Summary*: 

- [ ] Add "Status" logo in "Home" and Status app name to header
- [ ] Replace "Status log" in Sign up process

**Comment by EugeOrtiz** [comment]
This is intentionally not shown in new design. @churik  I would remove this as an issue.

**Comment by churik** [comment]
Ok, we just should keep in mind that main logo on "Sign Up" intended to have white colors instead of black.
