### ISSUE TITLE
"Fetching messages..." flashes when there is a contact request in mailbox 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4427]
### Description

*Type*: Bug

*Summary*: Fetching messages still flashes when you have a contact request in the mailbox. It's because it fetches again the messages for the particular topic that gets added.

#### Expected behavior
Fetching messages status should not be repeated when there is a contact request in chat list. It should not distract a user.

#### Actual behavior
Fetching messages still flashes when you have a contact request in the mailbox.

### Reproduction

- Open Status on 2 devices
- Device 1: Add device 2
- Device 2: Do not accept the contact 

### Additional Information
* Status version: nightly, May 24
* Operating System: Android, iOS

**Comment by pedropombeiro** [comment]
One related behavior I've seen is that when a contact has changed his name/picture, whenever the app fetches the historic messages, I see his name/picture change back to the default and later back to the customized name.

**Comment by lukaszfryc** [comment]
Yes! I've also seen it and talked with @yenda about it some time ago
