### ISSUE TITLE
Do not show chat screen before transaction sent screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4431]
### Description

*Type*: Bug

*Summary*: When transaction is signed, a chat screen re-appears for a moment only to be covered by transaction sent screen a second later. Also, when the chat screen appears, the transaction message is marked as "Not sent" which maybe misleading for a user:

<img src="https://user-images.githubusercontent.com/7532782/40482709-f2b3c7f2-5f55-11e8-97a0-caa79b03b38b.png" width="200">

A fix for that would be not to show the chat screen at all but immediately show the transaction sent screen. 

#### Expected behavior
Chat screen does not appear between sign transaction screen and the transaction sent screen.

#### Actual behavior
Chat screen appears for a moment when transaction is signed. It says that transaction is not set which maybe misleading.

### Reproduction

- Open Status
- Create 1-1 chat
- Open chat and call /sent to sent transaction
- Sign transaction in Wallet
-> The chat screen appears for a moment

### Additional Information
* Status version: nightly, May 24
* Operating System: tested only on Android

**Comment by lukaszfryc** [comment]
I could not reproduce it on latest nightly but instead found: https://github.com/status-im/status-react/issues/4534

Anyway, this issue may still be reproducible on slow devices.

**Comment by goranjovic** [comment]
@lukaszfryc Can you please re-test this one? It should be long gone now

**Comment by lukaszfryc** [comment]
I cannot replicate it anymore.
