### ISSUE TITLE
Add option "Delete chat"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4435]
### User Story

As a user, I should be able to delete public channels or to delete 1:1 chat
### Description

*Type*: Feature
*Summary*: in Status Desktop app there is no option to leave public chat or delete chats.
In mobile:
![leave](https://user-images.githubusercontent.com/4557972/40485921-81d73092-5f68-11e8-887e-e81a17869b8a.png)

#### Expected behavior
"Delete chat" is available for Public and 1-1 chats;
"Delete" option for Public chat also make user leave the channel

**Comment by lukaszfryc** [comment]
We've removed "leave chat" from mobile, https://github.com/status-im/status-react/issues/4265

**Comment by churik** [comment]
Thanks, @lukaszfryc! Fixed.

**Comment by EugeOrtiz** [comment]
Designs for this can be found here > zpl.io/agnZz09 (Zeplin)

**Comment by churik** [comment]
According to #4436  it is blocked by  status-im/react-native-desktop#256

**Comment by vkjr** [comment]
https://github.com/status-im/react-native-desktop/issues/256 fixed now, so this probably can be unblocked.

**Comment by churik** [comment]
Design should be implemented in #5314
