### ISSUE TITLE
Implement "Share my contact code"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4438]
### User Story

As a user, I want to share my key using QR code.

### Description

*Type*: Feature

*Summary*: for now QR code is not displayed, so there is no option to share it to smbd.

#### Expected behavior
button "Share my contact code" which leads to separate screen with  QR code where you can copy public key.
In mobile:
![mob_imp](https://user-images.githubusercontent.com/4557972/40486622-7db0e470-5f6a-11e8-8453-f834f1a4fa75.png)![mob_impl_2](https://user-images.githubusercontent.com/4557972/40486621-7d8ad140-5f6a-11e8-90d8-91af505d96cf.png)

#### Actual behavior
![pr_d](https://user-images.githubusercontent.com/4557972/40486658-92f82dca-5f6a-11e8-8231-15d77e4df580.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log in
- Click on "Profile"

**Comment by EugeOrtiz** [comment]
Designs for this can be found here:
- zpl.io/25qZqB3
- zpl.io/bAqjqPO 
- zpl.io/VxY83em (Zeplin)

**Comment by vitvly** [comment]
According to design, this is partially blocked by https://github.com/status-im/react-native-desktop/issues/258.

**Comment by vkjr** [comment]
@siphiuel, should be unblocked now.
