### ISSUE TITLE
Add system warnings ("Offline", "Fetching messages", "Couldn't connect to mailservers" ect)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4439]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to know when my app is offline or fetching messages or connecting to peers

### Description
*Type*: Feature
*Summary*: add warnings.
In mobile (offline message):
![offl_2](https://user-images.githubusercontent.com/4557972/40486972-738e1f34-5f6b-11e8-9a01-e0fdf276d3cf.png)

**Comment by andmironov** [comment]
https://github.com/status-im/status-react/issues/4690

**Comment by churik** [comment]
@EugeOrtiz can you please provide the design?

**Comment by EugeOrtiz** [comment]
Designs here > zpl.io/V1qZyPk (Zeplin)

**Comment by vitvly** [comment]
@Churik Can we close this given that #5241 is done, or is there some stuff still do in scope of this issue?
