### ISSUE TITLE
Change network icon respectively to network (make them easy to distinguish visually)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4440]
### User Story

As a user I want to be notified which network I am in so I won't lose funds

### Description

*Type*: Bug

*Summary*: change a color of the network icon. @denis-sharypin please provide icons

#### Expected behavior
Change network icons' colors ( Mainnet, Ropsten / Rinkeby , Custom)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/40487507-0b664e7a-5f6d-11e8-9bb9-8e45e24616b1.png)

**Comment by chadyj** [comment]
Can we close this since we are re-designing the entire flow and can handle it there?

**Comment by asemiankevich** [comment]
@chadyj we were voting for the icons last week :) not sure if we want to drop it @denis-sharypin ?

**Comment by denis-sharypin** [comment]
I would prefer to go step by step. We voted for the best solution in this case. Number two won 
![image](https://user-images.githubusercontent.com/6559881/40959874-47b396d2-689e-11e8-83f8-bfe08cfd0f2b.png)
