### ISSUE TITLE
App crashes when creating custom networks

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#4450]
### Description

App crashes when creating custom network

#### Expected behavior
Custom network is added
#### Actual behavior
App crashes

### Reproduction

1) Go to profile
2) Enable dev mode
3) Go to networks
4) Click on +
5) Add a network

**Comment by annadanchenko** [comment]
@cammellos when adding a network on nightly build and tap on Save there is no crash, so new network is added to the list. However, if provide not-valid url (e.g. "aaaa") then after switching to this network and trying to log in app crashes (on iOS) Can you share more details on the steps to reproduce, please?
