### ISSUE TITLE
Update status-react with new status-go version (contains new enodes)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4473]
### Problem

Current enodes are running on the old cluster, which lacks monitoring/logs/scalability. Additionally, the IPs are tied to specific hosts, as opposed to floating IPs that can be moved between hosts.

### Solution

Bump status-go version status-react as soon as https://github.com/status-im/status-go/pull/994 is merged.

Additionally, update Whisper enodes in status-react as well.

### Notes

This is expected to break communication with previous cluster, so it requires some extensive testing.

See https://github.com/status-im/status-go/issues/958

Russia issue:
- https://github.com/status-im/status-cluster/issues/107
- https://github.com/status-im/status-react/issues/4299#issuecomment-392414137

**Comment by oskarth** [comment]
Beta blocker as it appears we'll lose connectivity between old and new cluster, so it's a breaking change similar to move to Whisper v6. In the future it should be possible for us to do this more seamlessly.

@adambabik @jakubgs please correct if there's something missing or wrong above.

**Comment by oskarth** [comment]
cc @PombeirP @cammellos

**Comment by cammellos** [comment]
I can take a look at this when merged, as `status-react` requires some changes as well to handle new versions of `status-go` (for some reason it was always passing a `testnet` config & letting `status-go` overriding it, but the behaviour has changed now). If this gets merged first then no changes necessary https://github.com/status-im/status-react/pull/4453.

**Comment by adambabik** [comment]
@jakubgs please paste enodes for mail servers in the new cluster here. They need to be replaced in status-react.

**Comment by gravityblast** [comment]
we should have these:

mail-01:
enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.108.78:30504

mail-02:
enode://77a3a6e179ceac552cb4689bee3ea5fca4003e77a5b470540c27fcfaba18333a43d3b89f3b7f12e386acf8bb340d39da74b5288e44f54cedf24c20f678cade7d@167.99.219.240:30504

mail-03:
enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@206.189.108.63:30504

**Comment by jakubgs** [comment]
The easiest way to find enodes for the new fleet is Consul API:

http://consul.status.im/v1/catalog/service/statusd-mail?tag=eth.beta

The mail-01 and mail-03 I recognize, but I'm not sure where you got the mail-02.

<blockquote><div><strong><a href="http://consul.status.im/v1/catalog/service/statusd-mail?tag=eth.beta">Sign In</a></strong></div></blockquote>

**Comment by gravityblast** [comment]
@jakubgs from http://consul.status.im/v1/catalog/service/statusd-mail

<blockquote><div><strong><a href="http://consul.status.im/v1/catalog/service/statusd-mail">Sign In</a></strong></div></blockquote>

**Comment by gravityblast** [comment]
so maybe it's not for beta

**Comment by jakubgs** [comment]
Oh yeah, that one is from the `eth.test` fleet I made for Andrea to use.
I'm adding a 3rd mail server right now, give me a minute.

**Comment by jakubgs** [comment]
Here you go the proper list:
```json
[
  {
    "node": "mail-01.eth.beta",
    "enode": "enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.108.78:30504"
  },
  {
    "node": "mail-02.eth.beta",
    "enode": "enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@206.189.108.63:30504"
  },
  {
    "node": "mail-03.eth.beta",
    "enode": "enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@206.189.7.30:30504"
  }
]
```
