### ISSUE TITLE
Add a timeout on spamming user's send button

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4474]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have the send button of a spamming user's app be disabled for a certain period after each sent message so that spamming a chat is less feasible for him.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, it is very easy for a user to spam a public chat by pasting some long message over and over again. If we disable the send button for an increasing amount of time each time that a user sends messages in quick succession, we can discourage that behavior.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- User sends message 1
- User sends message 2 within 1 second
- App notices that the user is sending messages in quick succession and increases the timeout during which the Send button is disabled to 2 seconds.
- User sends another message right after the button is enabled again.
- App increases timeout to 5 seconds.

Note: There is a cooldown period of 10 seconds, after which we reset the timeout. These values should be easy to change so we can experiment with them.

#### Actual behavior
[comment]: # (Describe what actually happened.)
- User is able to send messages in quick succession without any limits.

**Comment by oskarth** [comment]
What's the state of this issue? Is it still a beta blocker?

**Comment by pedropombeiro** [comment]
Commented in PR. Basically, I feel we need to do something to address spam attempts, even if it is as crude as this, to begin with.
