### ISSUE TITLE
Error libgnustl_shared.so is 32 bit instead of 64-bit (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4478]
### Description

*Type*: Bug

*Summary*: `libgnustl_shared.so is 32 bit instead of 64-bit`

#### Expected behavior
no errors when launching status

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/40604521-0042b454-6268-11e8-81a7-f80496bd8ddb.png)

### Reproduction
- Open Status with latest nightly on Android

### Additional info
- Huawei P10 lite android 7
- Google Pixel XL android 8

**Comment by annadanchenko** [comment]
can reproduce on Galaxy S6, Android 6.0.1 and Pixel XL, Android 8.1.0
