### ISSUE TITLE
"Back up your seed phrase" is shown for recovered accounts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4483]
### Description

*Type*: Bug

*Summary*: If I restore an account from MetaMask, I don't expect to see "Backup your seed Phrase", because I already used seed phrase for restoring my account.
If I tap on it - an error is returned.

#### Expected behavior
no "Backup your seed Phrase" in Wallet
![seed pnrase](https://user-images.githubusercontent.com/4557972/40609849-a9001fcc-6278-11e8-935d-4ca9afc13397.png)

#### Actual behavior
 "Backup your seed Phrase"  is displayed; on tap "Error:  Index out of bounds."
![err 3](https://user-images.githubusercontent.com/4557972/40610085-99851e7a-6279-11e8-8a94-768ce7591194.png)

### Reproduction
**Requirements:** you are an owner of MetaMask or Status account with some real ETH/SNT on balance
- Open Status
- Restore your MetaMask Account
- Open "Wallet"

### Additional Information

* Status version: nightly 28/05/18 (0.9.19 - 6015)
* Operating System: iOS

#### Logs

* TF session: https://app.testfairy.com/projects/4803590-status/builds/8391694/sessions/5/?accessToken=-HT/y0XIHsrJEZYCEah4yLafgs4 

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8391694/sessions/5/?accessToken=-HT/y0XIHsrJEZYCEah4yLafgs4">TestFairy: Status 0.9.19 (6015) @5</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
closed by #4500
