### ISSUE TITLE
More than one "/request" or "/sent" message is shown when app is opened from notification

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4486]
### Description

*Type*: Bug

*Summary*: When the app is opened from notification with "/request" message, the message is shown couple of times in a row. Also, it sticks to the bottom of the chat even when new messages are sent or received. I could not reproduce it for other types of messages than "/request". 

<img src="https://user-images.githubusercontent.com/7532782/40613002-0e47a59a-627d-11e8-8eb6-7c132030832e.png" width="200">

It's worth nothing that it happens after "connecting to peers" and "fetching messages" statuses appear. 

#### Expected behavior
Only one "/request" message is shown. 

#### Actual behavior
More than one "/request" messages are shown when app is opened from the notification.

### Reproduction

- Open Status on 2 devices
- Create 1:1 chat
- Device A: Open 1:1 chat and then put app in background
- Device B: Request tokens in 1:1 chat (send "/request" message) from device A
- Device A: Open the incoming notification 

### Additional Information
* Status version: nightly, 28 May
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@yenda maybe it's related to handling signals and #4177?

**Comment by mandrigin** [comment]
@lukaszfryc but another device sees only one sent request, right?

**Comment by lukaszfryc** [comment]
@mandrigin yes

**Comment by yenda** [comment]
@lukaszfryc no signal handling is just making it easier to detect disconnections and reconnections

**Comment by janherich** [comment]
I was not able to simulate the problem however hard I tried (on the iOS simulator - iOS real device combo) in this branch - https://github.com/status-im/status-react/pull/4442 (waiting for @rasom approval so testing can begin)
I suspect it solves it, and the problem were broken message-ids, so app-side de-duplication didn't work.

**Comment by lukaszfryc** [comment]
@janherich can we merge #4442 first and then rebase this PR?

**Comment by janherich** [comment]
@lukaszfryc I don't follow, this is issue, not PR and there is not any other PR then #4442 which is solving the bug.

**Comment by lukaszfryc** [comment]
@janherich ops, yes 😆I'll take a look at #4442 then to see if I can replicate it. Thanks!

**Comment by lukaszfryc** [comment]
Can't replicate after https://github.com/status-im/status-react/pull/4322 was merged
