### ISSUE TITLE
Selected value in "Wallet" or "Transaction Fee" screen is not visible

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4488]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug
_Summary_: when I select value on "Send Transaction" or "Transaction Fee" - it is not visible (white font color on white fill color)

#### Expected behavior
can see selected value, can paste it in black font.

#### Actual behavior
![whiiteonwh](https://user-images.githubusercontent.com/4557972/40613622-efe6c6e8-6287-11e8-8bdd-295735af4823.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Go to "Wallet" screen
* Tap on "Send Transaction"
* specify any amount
* select it

### Additional Information

* Status version: 
[comment]: # (Android or iOS.)
* Operating System: Android 
* Device: Galaxy S7

#### Logs

* TF session: https://app.testfairy.com/projects/4803622-status/builds/8391938/sessions/17/?accessToken=0kkfpaXd8DPwQhmqZKXSnfCokIM

NOTE: probably will be fixed with https://github.com/status-im/status-react/issues/3230

**Comment by churik** [comment]
Still can reproduce

**Comment by Swader** [comment]
Still reproducible. Seriously, this is just CSS.

**Comment by flexsurfer** [comment]
@churik  can we close this?

**Comment by churik** [comment]
not relevant anymore after wallet redesign, thx @flexsurfer
