### ISSUE TITLE
Ethos token value is not shown

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4496]
### Description

*Type*: Bug

*Summary*: bought a 1.12345678 amount of Ethos token but Status does not show its price in wallet. Token is present on cryptocompare https://www.cryptocompare.com/coins/ethos/overview

#### Expected behavior
Ethos value is shown

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/40619150-a6b1017c-629c-11e8-97f6-f42681fc779b.png)

### Additional Information
* Status version: nightly 28 may
* Operating System: Android|iOS

**Comment by churik** [comment]
Same problem for `AST` tokens:
*Request:* https://min-api.cryptocompare.com/data/price?fsym=AST&tsyms=USD
*Response:* `USD:  0.2457`
![ast](https://user-images.githubusercontent.com/4557972/40648180-722b2730-6336-11e8-9179-e3fb5d3f73fa.png)
