### ISSUE TITLE
Signing words are not shown when account is recovered

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4498]
### Description

*Type*: Bug

*Summary*: Signing phrase onboarding missing when the account is recovered

#### Expected behavior
I want to know about 3 signing words when my account is recovered

#### Actual behavior
No wallet onboarding about signing phrase when the account is recovered

### Reproduction
- Open Status
- Recover account

### Additional Information
* Status version: nightly 28 may
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
dup https://github.com/status-im/status-react/issues/4456

**Comment by rachelhamlin** [comment]
@asemiankevich what does `to be automated` mean? do you think this needs design? is the idea that the same wallet onboarding screen with new signing phrase appears when user recovers account?

**Comment by asemiankevich** [comment]
@rachelhamlin `to be automated` means that @antdanchenko will add some autotests to check this feature. Idea is that user should know his signing words when account is recovered. Imagine you restored account created in Metamask, so you have no idea about how Status operates with transactions. You should be confident that transacting in Status is secure no matter you created new account or recovered one from Metamask / MyCrypto
