### ISSUE TITLE
Sort assets alphabetically  (send - asset)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4504]
### Description

*Type*: Bug

*Summary*: 

- Send transaction - Asset should be sorted alphabetically 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open wallet
- Send Transaction
- Tap asset

### Additional Information
* Status version: nightly may 28
* Operating System: both

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 500.00
Contract address: [0x2e4371959a6c02ade5f0ff1aadfd1202863302f7](https://etherscan.io/address/0x2e4371959a6c02ade5f0ff1aadfd1202863302f7)
Network: Mainnet
Paid to: ageneau
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
