### ISSUE TITLE
Total value is shown as zero for some currencies and tokens because they are not supported in API

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4508]
### User Story

As a user, I want to see only tokens for which price can be correctly fetched; and currencies only suitable for conversion;

### Description

*Type*: Bug
*Summary*: as we are using https://min-api.cryptocompare.com for fetching tokens price, there are several tokens presented in Status app, but not provided by https://min-api.cryptocompare.com/.
List of tokens:
- ROL
- Centra
- ATMChain

List of fiat currencies: 
BMD, BZD, CPL, GMD, GYD, KYD, LAK, LRD, LTL, MKD, MNT, NIO, SOS, SRD, UGH, YER

**Additionally:**
I found 20 currencies(ALL, AZN,  BSD, BYN, BAM,  BWP, KHR, CLP, SVC, GHC, GIP, GTQ, GGP, HNL, IRR, KGS, LBP, PAB, TRL, UZS) that are presented in cryptocompare API, but missing in Status app.
Probably there is another reason to exclude them from app. 
All currencies + list of requests/responses are listed [here](https://github.com/status-im/status-react/files/2053226/results_missing_curr.txt)

#### Expected behavior

*Scenario 1:*
**Status app:** price in USD
**API:** price in USD returned 

*Scenario 2:*
**Status app:** price in selected currency
**API:** price in selected currency returned

#### Actual behavior

*Scenario 1:*
**Status app:** total value in assets for these tokens will be always 0 (doesn't depend on currency)
API: Error: There is no data for the symbol {token_name}

*Scenario 2:*
**Status app:** total value in assets in selected currency will be always 0 (doesn't depend on tokens)
<img width="390" alt="bmd" src="https://user-images.githubusercontent.com/4557972/40709622-45570a52-63ff-11e8-888b-d824e2ac1f10.png">

**API:** "There is no data for any of the toSymbols {currency_name} ."

### Reproduction

*Scenario 1:*
- Open https://min-api.cryptocompare.com/
- Select "Price"
- Check requests:
https://min-api.cryptocompare.com/data/price?fsym=ROL&tsyms=USD
https://min-api.cryptocompare.com/data/price?fsym=Centra&tsyms=USD
https://min-api.cryptocompare.com/data/price?fsym=ATMChain&tsyms=USD

*Scenario 2:*
- Open https://min-api.cryptocompare.com/
- Select "Price"
- Check requests listed [here](https://github.com/status-im/status-react/files/2052806/results.txt)

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 
Dropping these tokens\currencies will be the simplest solution.

### Additional Information
* Status version: 0.9.19 (6016) - nightly 29.05
* Operating System: Android,iOS

**Comment by goranjovic** [comment]
This will need a migration for any users who previously had account set to any of those currencies or had any of those tokens enabled.
