### ISSUE TITLE
Update Korean translations

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4509]
### User Story

As a Korean language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Korean to translate all the latest strings in Status from English.

#### Expected behavior
The Korean translation ought to be as up-to-date as the English one.

#### Actual behavior
The Korean translations are out of date.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/ko.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).

**Comment by oskarth** [comment]
Note: should probably partially revert https://github.com/status-im/status-react/issues/4398 and also use capabilities added in https://github.com/status-im/status-react/pull/2510 to do this more rigorously, but this works as a skeleton issue for now.

Additionally, provide some context for why KO in particular.

**Comment by yenda** [comment]
Closed by https://github.com/status-im/status-react/pull/5819
