### ISSUE TITLE
Update Japanese translation

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#4510]
### User Story

As a Japanese language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Japanese to translate all the latest strings in Status from English.

#### Expected behavior
The Japanese translation ought to be as up-to-date as the English one.

#### Actual behavior
The Japanese translations are out of date.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/jp.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/4509#issuecomment-392716544

**Comment by oskarth** [comment]
@chadyj Deferring to you regarding new localization efforts, do you want to keep this open or close it?

**Comment by chadyj** [comment]
Let's close it and hand it over to #localization.
@pablanopete got someone in mind?
