### ISSUE TITLE
"Not sent. Tap for options" appears for a moment after sending transaction

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4534]
### Description

*Type*: Bug

*Summary*: After sending transaction, the "not sent.." error appears for a moment which may be strange for a user. The error disappears immediately.

<img src="https://user-images.githubusercontent.com/7532782/40718710-5de835f2-6411-11e8-82fe-8f56662afabe.png" width="200">

#### Expected behavior
No error appears if transaction is sent.

#### Actual behavior
The error appears for a moment.

### Reproduction

- Open Status
- Create 1-1 chat
- Sent transaction in 1-1 chat

### Additional Information
* Status version: nightly, May 30
* Operating System: Android, iOS

**Comment by alwx** [comment]
Tried it (current `develop` branch) and found no way for it to be reproduced. 
@lukaszfryc can you check it again and confirm?

**Comment by lukaszfryc** [comment]
I cannot reproduce it anymore. Closing.
