### ISSUE TITLE
Nothing happens tapping Sign Transaction from 1-1 chat having amount < gas*price + value

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4539]
***Type***: Bug

***Summary***: Nothing happens when tap Sign Transaction from 1-1 chat having amount < gas*price + value. We need to show 'Insufficiend funds for gas*price+value' pop-up message, like we do now when sending TX from Wallet or signing transaction from Dapp

#### Expected behavior
Nothing happens tapping Sign Transaction from 1-1 chat having amount < gas*price + value
#### Actual behavior
Tapping Sign Transaction from 1-1 chat and having amount < gas*price + value calls an 'Insufficiend funds for gas*price+value' pop-up message

### Reproduction

- Open Status and create new account
- Add a new contact to start 1-1 chat 
- Type `/send 0` and tap `Send message`
- On appeared 'Send Transaction' screen tap `Sign Transaction` and enter the valid password
- Tap `Sign transaction`

**Note:** Alternatively, if you have some funds for your contact already, - repeat all steps above but set GasPrice to, let's say '10000' to make a fee > amount.

### Additional Information
* Status version: Release 0.9.19, Nightly develop
* Operating System:  Android and iOS

TF session: https://app.testfairy.com/projects/4803590-status/builds/8405451/sessions/8/?accessToken=MYc3ut1vNCoNeNI9BIQFnU9hlMQ

**Comment by asemiankevich** [comment]
@Serhy may be related to https://github.com/status-im/status-react/issues/3441
