### ISSUE TITLE
Missing value for property 'transport.topic' error appeared after removing a public chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4551]
### Description

*Type*: Bug

*Summary*: "Missing value for property 'transport.topic'" error appered when I removed a public chat. There was "Fetching messages.." in progress. Also, before that, I cleared the chat. When I closed the error, the app worked fine. I could not reproduce it anymore.

<img src="https://user-images.githubusercontent.com/7532782/40769606-b67e8458-64b8-11e8-8d34-84fce91e5cb1.png" width="200">

#### Expected behavior
No such error is shown.

#### Actual behavior
The error appeared. The app worked fine after it was dismissed. I could not reproduce it.

### Reproduction

There are no steps to reproduce. 
 
### Additional Information
* Status version: `release/0.9.19` [25](https://jenkins.status.im/job/status-react/job/release/job/release%252F0.9.19/25/), `08e0ee9`, May 31
* Operating System: happened on iOS

**Comment by rasom** [comment]
got this error while tried to reproduce 
<img width="260" alt="screen shot 2018-05-31 at 11 25 05" src="https://user-images.githubusercontent.com/2364994/40771184-53587746-64c5-11e8-8e84-e96e1bea485e.png">

**Comment by rasom** [comment]
^ so this error can be reproduced if run 
```
(re-frame.core/dispatch [:set-in [:transport/chats "it doesn't exist" :fetch-history?] false])
```
in repl, but i suppose that's a separate bug.

**Comment by rasom** [comment]
ok, so this is the same bug it just looks differently in dev mode.
@lukaszfryc the way to reproduce it is to remove chat before history was fetched.
