### ISSUE TITLE
Mismatch between concept of transaction and transfer

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#4556]
### User Story

As a user I want to have a clear and non-confusing UI to send/receive ether or tokens or use dapps.

### Description

*Type*: Design

*Context*:  

Word "transaction" refers to two different concepts. 
The first is like a bank transaction - an operation where some money goes from A to B.
The second one is a bit more general - a set of operations that changes some state atomically.

Right now we want to focus on the simpler transfer use cases:
- A sends 1 eth to B (and pays for the tx costs)
- A sends 45 HND to B, etc. (and pays for the tx costs)

However, more complex cases are possible:
- A sends 0.02 eth to a smart contract and receives 10 HND back
- A sends 0.03 eth and 20 HND to a smart contract and receives 30 LXS back, B receives a cut of 2 HND, etc.

The simpler use cases will typically be seen in direct interaction between users and the complex ones as result of some kind of dapp usage.

The one thing common to all those transactions, simple or complex alike, is that they cost gas. So, they all actually affect A's ether balance if nothing else.

*Summary*:

Find a way to:
- Display simple and complex transactions in a different way
- Possibly to separate them
- Display transactions where multiple transfers of value occur

**Comment by goranjovic** [comment]
Created #4983 to cover some low hanging fruit improvements we can do to make this look better in the short term.

**Comment by Swader** [comment]
Keep alive.
