### ISSUE TITLE
Different date/time format on "Transaction details" screen 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4558]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see same time format (ideally the same as I specify in my phone settings) across the app.

### Description
*Type*: Bug
*Summary*: in "Chats", "Transaction history" 12h time format is using; the only  place where I can see 24h time format is "Transaction details" screen
#### Expected behavior
30 May, 3:41 PM;
same time format everywhere

#### Actual behavior
May, 30 15:41:08
- Tap on the top transaction to see "Transaction details".
![image](https://user-images.githubusercontent.com/4557972/40775024-bf21a52e-64cf-11e8-95f5-0f2582c85ed1.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to "Wallet" (should have some Transaction History)
- Tap on "Transaction history". Pay attention to datetime format - 30 May, 3:41 PM)
- Tap on the top transaction to see "Transaction details".

### Additional Information

* Status version: nightly 31/05/2018
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 600.00
Contract address: [0xeba57df2a4e8bd75eee0a1883984577f738229aa](https://etherscan.io/address/0xeba57df2a4e8bd75eee0a1883984577f738229aa)
Network: Mainnet
Paid to: tbenr
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pablanopete** [comment]
@tbenr sorry for the slow response on bounty payout, could you drop your wallet address here so I can send you the bounty amount Out of Band while we wait on a dashboard fix in Status Open Bounty. 

If you don't feel comfortable putting it here in the comment could you email a ERC20 compatible wallets address to me? chris.hutchinson@status.im

**Comment by tbenr** [comment]
Hi @pablanopete, no prob, email sent.

**Comment by pablanopete** [comment]
OOB Payment sent; thanks for being part of status! @tbenr
