### ISSUE TITLE
Instabug message reliability survey does not appear inside the app

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4563]
### Description

*Type*: Bug

*Summary*: None of the existing surveys appear in Status even though the user events are visible while bug report is sent.

<img src="https://user-images.githubusercontent.com/7532782/40781806-8f1b8e86-64dd-11e8-85b0-0ad644ba05f8.png" width="200">

#### Expected behavior
The surveys appear after conditions are met.

#### Actual behavior
Surveys do not appear

### Reproduction

- Check conditions of surveys in Instabug
- Replicate the conditions in Status and see surveys

### Additional Information
* Status version: nightly, May 31
* Operating System: Android, iOS

**Comment by oskarth** [comment]
What's the state of this issue? Is it still a beta blocker?

**Comment by lukaszfryc** [comment]
I think we can close this this one. 

Currently the survey is shown, but only after the app is killed and started again. Also, there are https://github.com/status-im/status-react/issues/4687 and https://github.com/status-im/status-react/issues/4627 which are related to showing the surveys.
