### ISSUE TITLE
Chat with request or send commands was not recovered correctly

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4565]
### Description

*Type*: Bug

*Summary*: For some reason, when an account that had unread "request" or "send" messages was recovered, the messages were broken:

<img src="https://user-images.githubusercontent.com/7532782/40782164-cdcaf4cc-64de-11e8-8d73-e6e92006feeb.png" width="200">

Also, there was a following error:

<img src="https://user-images.githubusercontent.com/7532782/40782214-e6495642-64de-11e8-84e4-a5aadc174840.png" width="200">

Unfortunately, this can't be reproduced easily. Happened only on iOS for couple of accounts created on 0.9.19. Here is Slack [conversation](https://status-im.slack.com/archives/C8KB9DR60/p1527762664000134) about it.

#### Expected behavior
When account is recovered, all contacts requests and incoming messages (including request, sent commands) are recovered as well and look correctly.

#### Actual behavior
Request and sent commands were not recovered correctly. There was "DateTimeProtocol" error.

### Reproduction

It's hard to reproduce but the issue has happened when: 

- Create new accounts on 2 devices using Status 0.9.19
- Create 1-1 chat between 2 devices
- Exchange some messages
- Delete app on ios
- Sent "request" and messages from 1st device to ios
- Recover account on ios

### Additional Information
* Status version: release/0.9.19 25, 08e0ee9, May 31
* Operating System: reproduced only on iOS

**Comment by asemiankevich** [comment]
I would say, `send` and `received` were never delivered. However I could see the messages I was not the author of, so when I tap `tap to see options` i can choose `resend` and `delete` which is wrong, moreover the `delete` option causes the same error described in the ticket.

**Comment by pedropombeiro** [comment]
The `no protocol method` error has been captured by @janherich in https://github.com/status-im/status-react/issues/4597.

**Comment by rachelhamlin** [comment]
@lukaszfryc I believe we talked about it in a later Slack conversation, but my account was actually *not* created on 0.9.19. It was created on a previous nightly and recovered in 0.9.19. 

Seems like Nastya only experienced the issue when interacting with me on that account.

**Comment by oskarth** [comment]
In terms of being a beta blocker, is this issue completely subsumed by #4597?

**Comment by lukaszfryc** [comment]
Most probably, I added a comment in https://github.com/status-im/status-react/issues/4597 and I'm closing this issue.
