### ISSUE TITLE
Default username/userpic when recovered account receives a text message from the contact (without contact request)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4573]
***Type***: Bug

***Summary***: There are default username and userpic of a buddy that contact had a chat in the past are displayed for the recovered contact when he receives a message from this buddy.
Apparently, this is because recovered account did not receive actual contact request. 
But we need to take into account this possible use case, - to reveal username and profile image of the contacts who send them just a message (without contact requests).

#### Expected behavior
Real username and userpic are displayed for the recovered contact when he receives a message from a buddy he had a chat in the past (before account recovering)

#### Actual behavior
The default name and userpic displayed for the recovered contact when he receives a message from a buddy he had a chat before account recovering. 

### Reproduction

- Open Status on Device 1 and Device 2
- Device1 - recovers account (use this one for instance `point mutual mountain cook borrow pencil flower lumber tonight luxury earn scatter` / `aaaaaa`) -> Contact1
- Set username and userpic for Contact1 (so it would not default)
- Create new account on Device2 -> Contact2
- Contact1 adds Contact2 and sends a text message
- Contact2 from 1-1 chat adds Contact1 in contacts (tap on `Add to contacts`)
- On Device1 - reinstall the app (or flush all data on existing one)
- Recover the same account on Device1 (Contact1)
- Contact2 sends a text message to Contac1
**Actual result:** Default username and profile image of the Contact2 appears on Contact1 Home screen. There is no indication on profile image that this contact is not in the contact list (a blue small circle on profile image). But if Contact1 navigates to 1-1 chat with Contact2 - the  'Add to contacts' options is present. 
 
### Additional Information
* Status version: Develop, Release 0.9.19
* Operating System: Android and iOS
### Additional Information 2 (Reopened the issue since it still takes place)
* Status version: Develop 0.9.29, Release 0.9.28
* Operating System: Android and iOS

**Comment by churik** [comment]
Update: if contact 1 and contact 2 had 1-1 chat before, then both reinstall the app and both update pics/names - default ones will be displayed.

**Comment by Serhy** [comment]
Reopening this one because it's still actual.

**Comment by yenda** [comment]
@cammellos could this be at least partially solved with syncing?

**Comment by cammellos** [comment]
@yenda partially yes, if you sync the devices you will have the same contacts (currently we don't sync the photo though, only username), but if you can't sync devices (you recovered the only account), then you would still see default username/picture
