### ISSUE TITLE
Keys are overlapped on "Sign in" screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4588]
### Description

*Type*: Bug
*Summary*: public keys are overlapped on "Sign in" screen

#### Expected behavior
public keys are displayed with .. in the end

#### Actual behavior
![pubji](https://user-images.githubusercontent.com/4557972/40835361-ea84e0ba-659b-11e8-871c-92c89ba8c3ae.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create or restore account 
- Log out

### Additional Information
* Status version: nightly 01/06/2018
* Operating System: Android

**Comment by lukaszfryc** [comment]
Strange, I could not reproduce it in release/0.9.19 branch.

**Comment by asemiankevich** [comment]
it is here in nightly

**Comment by mandrigin** [comment]
@asemiankevich looks like new version or RN made this regression. I'll take a look today.
