### ISSUE TITLE
"No protocol method ICollection" error at attempt to change "Gas price" (if you previously reset it to default)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4593]
### Description

*Type*: Bug
*Summary*: 'No protocol method' error appears after resetting value at attempt to set new value in "Gas Price"

#### Expected behavior
no error

#### Actual behavior
<img width="379" alt="nopr" src="https://user-images.githubusercontent.com/4557972/40846814-520452ee-65c3-11e8-9467-be9d537779b3.png">

### Reproduction

- Open Status
- Tap on Wallet
- Tap on Send Transaction
- Tap on Advanced
- Tap on "Reset to default"
- Try to change value in "Gas Price" field

### Additional Information

* Status version: nightly 01/06/2018
* Operating System: iOS, Android
* TF Session (01:50 - 02:05):  https://app.testfairy.com/projects/4803590-status/builds/8421364/sessions/9/?accessToken=/zbGJKWL9MpaUPdDce3IyDQ5Gj8

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8421364/sessions/9/?accessToken=/zbGJKWL9MpaUPdDce3IyDQ5Gj8">TestFairy: Status 0.9.19 (6026) @9</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@goranjovic `Reset to default` does not bring value back for `Gas Limit` field in the following scenario:

1. Go To wallet
2. Tap Send
3. Scan any valid QR
4. enter amount 0
5. Go to Advanced and set Gas Value and Gas Price to 0
6. Tap done
7. Tap Advance
8. Tap Reset to Default

i checked in develop and it is worse there - reset does not affect both fields. Would you mind to fix it in this PR?
