### ISSUE TITLE
Build script hangs at maven step

### ISSUE THREAD

**Issue by the-frey** [status-im/status-react#4600]
### User Story

As a developer, I want to build the software so that I can contribute to Status.

### Description

*Type*: Bug

*Summary*: Running the build script hangs at the `mvn -f modules/react-native-status/ios/RCTStatus/pom.xml dependency:unpack` step. Running it separately results in:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< org.reactjs.native.example:Messenger >----------------
[INFO] Building Messenger 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:unpack (default-cli) @ Messenger ---
[INFO] Configured Artifact: status-im:status-go-ios-simulator:develop-g098053f6:zip
Downloading from ci.status.im: http://139.162.11.12:8081/artifactory/libs-release-local/status-im/status-go-ios-simulator/develop-g098053f6/status-go-ios-simulator-develop-g098053f6.zip
```

Before a hang. Looking at the network, nothing is coming over the wire from that address.

#### Expected behavior

The build script to continue past this step.

#### Actual behavior

The script hangs indefinitely.

### Reproduction

Run the build script, or that step in isolation. However, due to the complexity of the script, I would guess that it might not be deterministic.

### Solution

Somebody with access to the repository to check it is available.

- [ ] Check artifact is available

### Additional Information

* Status version: Head of `develop` branch

**Comment by georgiemathews** [comment]
@the-frey did you manage to resolve this, getting the same issue.

**Comment by the-frey** [comment]
@georgiemathews no I didn't. Reopening in that case, as it seems it's not just my machine.

**Comment by the-frey** [comment]
@georgiemathews are you on OSX?
