### ISSUE TITLE
Not possible to Change gas price in Dapp transactions

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#4602]
### User Story

As a user, I want to set a higher gas price so that my transaction is less likely to be frontrunned or get too late.

### Description

*Type*: Bug

*Summary*: at sign transaction screen I want to easily adjust gas price.

#### Expected behavior

Gas price editable for dapp transactions

#### Actual behavior

Gas price not editável for dapp transactions

### Reproduction

Try buy a cryptokitty with higher gas price.

**Comment by goranjovic** [comment]
duplicate of #4065
