### ISSUE TITLE
Run automated tests on Jenkins CI

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#4604]
### User Story

As a user, I want bugs free application and more stability.

### Description

*Type*: Feature

*Summary*: CI Jenkins builds should be extended with automated tests running.

#### Expected behavior
All available unit tests should run during Jenkins CI builds.

#### Actual behavior
No automated tests are running on Jenkins CI builds.

**Comment by churik** [comment]
Irrelevant now
