### ISSUE TITLE
Add Status app as a share target for the OS

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4605]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see Status listed as a share target on Android and iOS so that I can for instance, share a video link from YouTube app (or any other app, of course).

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Most apps nowadays support receiving data from other apps. We should add the same support to the Status mobile app, otherwise the users are forced to share to the clipboard, open the Status app, navigate to the correct room and paste the link. We should follow the mobile Slack share interface.

![image](https://user-images.githubusercontent.com/138074/40887513-364f98dc-674a-11e8-8b33-91464bd60715.png)

### Expected behaviour

1. User taps Share button on 3rd party app
1. User selects Status app
1. If necessary, Status app asks to sign in to account
1. Status app pops up a window asking for Title and Channel
1. Chat message is sent to selected channel

cc'ing @andmironov for actual Share dialog UI.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x75d54f5e4807a5cb9d74d43855b37262c6788a0a7d2fc5e143f4b70ee1e5bdf7](https://etherscan.io/tx/0x75d54f5e4807a5cb9d74d43855b37262c6788a0a7d2fc5e143f4b70ee1e5bdf7)

**Comment by nirvanaitsolutions** [comment]
There is a NPM package react-native-share-menu which works well for Android. May I give it a try?

**Comment by pedropombeiro** [comment]
@nirvanaitsolutions that sounds interesting. What do you think @jeluard?

**Comment by jeluard** [comment]
@nirvanaitsolutions Is that https://github.com/meedan/react-native-share-menu you are talking about?
In general we rather not rely on extra deps, especially native and unmaintained :sweat_smile: 

The native part looks fairly short. Maybe we could directly add it to our own native layer?

<blockquote><img src="https://avatars2.githubusercontent.com/u/60577?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/meedan/react-native-share-menu">meedan/react-native-share-menu</a></strong></div><div>react-native-share-menu - A module for React Native that adds your app to the share menu of the device</div></blockquote>

**Comment by rachelhamlin** [comment]
I really like the way Telegram and WhatsApp do this. At least on iOS/Safari, Telegram shows a panel of recent chats, and WhatsApp shows a list:

<img src="https://user-images.githubusercontent.com/15470435/69255521-dd683d80-0baf-11ea-9ae8-83f7d748ea35.png" width=250/>

I think we could bounty this one. @errorists would you want to work on something for the mobile browser share window?

**Comment by errorists** [comment]
I'd really like if we had a system going on for anything that's shareable. it can be a chat message, a wallet address, url, and you can pick if you want to share internally with one of your contacts or pass it over to the OS and share it with other apps. or the other way around, share something you like outside of Status, where you'd be asked to provide with who (private chat) or what group / public chat (what this issue describes) tbh I haven't spend much time exploring that, I'd like to take a look if we're positive that can be done without leaking metadata or any icky privacy stuff I'm not aware of.

**Comment by errorists** [comment]
I did simple designs for sharing from outside of Status to Status and the inverse, 👀 [here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=7253%3A35051)

Now sharing inside of Status, that's slightly another thing, we might want to label it as `Forwarding` or I can try bundling thet in the Share outside flow.

**Comment by rachelhamlin** [comment]
Dig the share sheets @errorists, and good call on the sign-in screen for external app to Status.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
