### ISSUE TITLE
User profile picture doesn't update

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4610]
### User Story

As a user, I want to update my profile picture so that other users can recognize me.

### Description

*Type*: Bug

*Summary*: Some users are having trouble updating their profile pictures. Uploading from gallery does not change the avatar. 

#### Expected behavior
Editing the profile photo updates the user's image throughout Status.

#### Actual behavior
Editing the profile photo does not change the user's image. 

<img src="https://user-images.githubusercontent.com/15470435/40890971-7ee7b474-677e-11e8-8cc4-c0b24306044a.png" width=250/>

### Reproduction

- Click "Edit" in the avatar circle
- Choose an image from gallery
- Returning to profile shows default image

### Additional Information
* Status version: 0.9.19
* Operating System: Google Pixel OS Level 27

#### Logs

https://insta.co/bugs/0maI0FFSo0FG-qZAWyHb-w

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://insta.co/bugs/0maI0FFSo0FG-qZAWyHb-w">Bug #0maI0FFSo0FG-qZAWyHb-w | Instabug</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
i dont see it on my devices, i tried hard to reproduce - the picture is shown right after i change it
