### ISSUE TITLE
Bancor doesn't save local host preference

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4611]
### User Story

As a user, I want DApps to remember my preferences so that I can skip unnecessary screens on later runs. 

### Description

*Type*: Bug

*Summary*: Bancor offers to remember the user's preference between the Bancor wallet and "localhost" (Status), but the preference is not saved when selecting local host.

#### Expected behavior
"Remember my selection" saves my preference for the Status wallet and I am not asked again on later use.

#### Actual behavior
The wallet selection screen appears no matter what.

<img src="https://user-images.githubusercontent.com/15470435/40891467-5d8cdfb8-6786-11e8-8b9f-844db5bf2dce.png" width=250/>

### Reproduction

- Open Bancor
- Select wallet "local host"
- Check "Remember my selection"
- Make transaction
- Close Bancor
- Reopen Bancor

### Additional Information
* Status version: 0.9.19
* Operating System: Android OnePlus ONEPLUS A5010 

#### Logs

https://insta.co/bugs/BthG382psRi6IKjY4h-pxg

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://insta.co/bugs/BthG382psRi6IKjY4h-pxg">Bug #BthG382psRi6IKjY4h-pxg | Instabug</a></strong></div></blockquote>

**Comment by churik** [comment]
Also is reproducible on IOS 11 (IPhone 7)
