### ISSUE TITLE
Bancor token transaction doesn't complete

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4612]
### User Story

As a user, I want to buy tokens in Bancor using other tokens.

### Description

*Type*: Bug

*Summary*: Using a token to pay for another token in Bancor does not work. After signing the transaction, the screen hangs. 

#### Expected behavior
I can seamlessly purchase any token using another token as the payment in Bancor. 

#### Actual behavior
I can't complete my transaction and am stuck on this screen:

<img src="https://user-images.githubusercontent.com/15470435/40891595-af2b050a-6788-11e8-87d5-89255fccf364.png" width=250/>

### Reproduction

- Open Bancor
- Make a transaction
- Change payment from ETH to SNT
- Sign transaction

### Additional Information
* Status version: 0.9.19
* Operating System: Both

#### Logs

https://insta.co/bugs/n1qgxwVWwZfagGcM_3uxDQ

<blockquote><img src="/favicon.ico?v=eE5LjeB9Od" width="48" align="right"><div><strong><a href="https://insta.co/bugs/n1qgxwVWwZfagGcM_3uxDQ">Bug #n1qgxwVWwZfagGcM_3uxDQ | Instabug</a></strong></div></blockquote>

**Comment by 3esmit** [comment]
Seems like the error is caused because the web3 dapp needs ERC20Token.approve and another call after that.

**Comment by 3esmit** [comment]
Note: is important that nonces of approve and call are respected. I noticed the client is show (...) at nonce, which can lead to problems in this cases, but thats another bug report.

**Comment by churik** [comment]
Couldn't reproduce it.
TF session: https://app.testfairy.com/projects/4803590-status/builds/8445103/sessions/20/?accessToken=UHmmWevEOxznVeRyKdiFgd543jY (08:20 - 10:50)
Device: IPhone 7, IOS 11
Tokens: buy POWR
Build: nightly 05/06/18
