### ISSUE TITLE
Buttons in sharing data screen do not fit small screens (like iPhone 5)

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4615]
### Description

*Type*: Bug

*Summary*: The buttons go out of screen on small screen devices like iPhone 5:

<img src="https://user-images.githubusercontent.com/7532782/40906716-e8e1256e-67e1-11e8-8341-c11fd47ff2e1.png" width="200">

The issue was reported on [Instabug](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/103). It's a low priority but would be good to fit since it's probably not only iPhone 5 but other small screen devices as well.

#### Expected behavior
Sharing data screen looks good on small devices. Buttons fit inside the screen.

#### Actual behavior
The buttons go outside the screen 

### Reproduction

- Open Status
- Start creating a new account

### Additional Information
* Status version: 0.9.19
* Operating System: Android, iOS

**Comment by chadyj** [comment]
@mandrigin You fixed this right?

**Comment by mandrigin** [comment]
@chadyj I fixed it for the screens *smaller* than iPhone 5
@alwx is looking at a related issue right now.

**Comment by mandrigin** [comment]
@lukaszfryc is this still reproducible?

**Comment by chadyj** [comment]
This flow has been removed so we can close.
