### ISSUE TITLE
Crash when trying to report issue using Instabug

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4619]
### Description

*Type*: Bug

*Summary*: On some devices, the app crashes after shaking the phone, filling the Instabug report and clicking send. The app says "collecting data" and then the screen goes black. It's only reproducible on some set of devices including Nexus 5. 

#### Expected behavior
No crash when reporting an issue using Instabug.

#### Actual behavior
App crashes when "collecting data" is shown.

### Reproduction

- Open Status on affected device
- Shake phone
- Try to report Instabug issue

### Additional Information
* Status version: 0.9.19
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
It has also [happened](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/95) on iPhone X by one of our users. We could not reproduce it locally on the same device

**Comment by Serhy** [comment]
I can reproduce it now on iPhoneX. It doesn't happen on a fresh account and when I shake the device being on Home screen. However, shaking a phone when I'm on browser web view followed by sending an Instabug 'Report Issue' message - crashes the app.
Confirmed on latest nightly develop build (12th of June build)

**Reproduction:**
1) Open Status on iPhone device
2) Create new account
3) Navigate to Open Dapps -> type 'google.com' and hit 'GO'
4) Navigate through some pages, use back/fwd buttons. Stay on web view screen.
5) Shake your device to call 'How can we help you' Instabug pop up
6) Select 'Report an issue'
7) Type your email and text message (the message i used `Test ignore please (iPhone)`)
8) Tap 'Send'

TF session with logs on iPhoneX: https://app.testfairy.com/projects/4803590-status/builds/8486001/sessions/4393835955/?accessToken=SzdNgYDNQtGOr-nA55l5GsYCsyY

**Comment by annadanchenko** [comment]
can reproduce on nightly from june 12 too. iphone 5s, iOS 11.4
https://app.testfairy.com/projects/4803590-status/builds/8486442/sessions/4393837113/?accessToken=fq8HB5LJQdBd3ZjltVMpAjhQ/P4

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8486442/sessions/4393837113/?accessToken=fq8HB5LJQdBd3ZjltVMpAjhQ/P4">TestFairy: Status 0.9.19 (6047) @11</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Still can reproduce in Develop `0.9.29 (9168)` build on iPhoneX (iOS 12)

**Comment by chadyj** [comment]
Removed instabug
