### ISSUE TITLE
Cannot copy address or public key in profile

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#462]
Addresses and public key strings should be copy-able.
Also "Show QR" does not use the show QR screen that we have?

**Comment by alwx** [comment]
It is partially fixed in this PR: https://github.com/status-im/status-react/pull/460
QR screen will be added later today.

**Comment by jarradh** [comment]
These commits seems to be re-implementing the Show QR screen?

Keep in mind the Show QR screen we already have - if you go 
Wallet -> Open -> Receive > Scan QR (this should say Show QR) then you will see the screen.

The idea is to provide a generic Scanning/Displaying of QR codes in Status that can be used from API and is used throughout the application

**Comment by jarradh** [comment]
I had assumed that the button would just dispatch to this screen and we'd be done.

**Comment by alwx** [comment]
ok, got it 
by the way this screen looks ugly
<img width="487" alt="screen shot 2016-11-18 at 10 45 07" src="https://cloud.githubusercontent.com/assets/911127/20422557/2815671c-ad7c-11e6-9e4d-b925c2614e25.png">

**Comment by jarradh** [comment]
lol! yup agreed it does. what do?

**Comment by jarradh** [comment]
i guess the QR code needs to be bigger and centered horizontally and vertically

**Comment by alwx** [comment]
yes, sure
don't worry — I will update the styles

**Comment by rasom** [comment]
Maybe a week ago I made QR smaller because it didn't fit on Android and was useless in the result.

**Comment by jarradh** [comment]
surely we can scale it as a % of screen width/height
