### ISSUE TITLE
Search for dapps is not implemented

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4625]
### User Story

As a user, I want to look up for a dapp 

### Description

*Type*: Feature

*Summary*: I want to be able to search for dapp in dapps list

#### Actual behavior
no search

### Reproduction

![image](https://user-images.githubusercontent.com/28752642/40920364-fba37a20-6814-11e8-9f8e-65bdcba70781.png)

### Additional Information
* Status version: ...
* Operating System: both

**Comment by rachelhamlin** [comment]
Two outcomes I'd love to see here:

1) You can search by DApp name to filter through our curated list.

2) You can search the web by DApp name or keywords to see results, perhaps using [Desearch](https://desearch.com/) or the [State of the DApps API](https://stateofthedappsapiv1.docs.apiary.io/#)?

**Comment by asemiankevich** [comment]
@rachelhamlin i was thinking of search inside our apps curated list
