### ISSUE TITLE
'undefined is not an object (evaluating e.length)' when switching network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4630]
***Type***: Bug

***Summary***: When switching network for an account after right away after returning to app from background and login into account with a switched network - sometimes leads to the continuous pop-up with error `undefined is not an object (evaluating e.length)`  
**Note:** I the error appears almost occasionally but always relates to the fact of switching networks and login in to account with the switched on the different network (from/to `Mainnet RPC` <-> `Ropsten RPC`)

#### Expected behavior
No errors when I log in the account after the network switch

#### Actual behavior 
`undefined is not an object (evaluating e.length)` errors when I log in account after network switch

### Reproduction
**Note:** Steps to reproduce provided below - are actual steps when bug appear, however it not always happens and the key reason of issue not clear. I provide an account to restore where bug appeared twice

- Open Status and restore an account (`spy fly certain occur scale normal vague evolve decide rail advice asset` / `aaaaaa`)
- Put an app on the background and wait > 10minutes
- Open an app 
- Navigate to Networks -> Change network to the different one (`Note:` it happened when I changed from/to `Mainnet RPC`<-> `Ropsten RPC`)
- Log in to account

### Additional Information
* Status version: Develop (430th nightly develop), Release 0.9.19
* Operating System: Android and iOS

#### Logs
```
***
NAME: "TypeError"
MESSAGE: undefined is not an object (evaluating 'e.length')

js_array__GT_seq@index.android.bundle:12:6732239
receive_whisper_messages@index.android.bundle:12:6733019
index.android.bundle:12:2437592
invoke_interceptor_fn@index.android.bundle:12:2359855
invoke_interceptors@index.android.bundle:12:2360156
execute@index.android.bundle:12:2362605
handle@index.android.bundle:12:2371018
re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@index.android.bundle:12:2405567
re_frame$router$IEventQueue$_run_queue$arity$1@index.android.bundle:12:2387906
index.android.bundle:12:2393658
re_frame$router$IEventQueue$_fsm_trigger$arity$3@index.android.bundle:12:2397869
index.android.bundle:12:2390424
index.android.bundle:213:1369
x@index.android.bundle:213:643
callTimers@index.android.bundle:213:2788
value@index.android.bundle:208:3582
index.android.bundle:208:1067
value@index.android.bundle:208:3009
value@index.android.bundle:208:1039
[native code]
```

TF session with log where the error messages appear: 
Android from 23:10 - end https://app.testfairy.com/projects/4803622-status/builds/8438725/sessions/6/?accessToken=13LRVF5NYRMU1B3onTqe3wanbLA
iOS: 07:10 - end https://app.testfairy.com/projects/4803622-status/builds/8438725/sessions/6/?accessToken=13LRVF5NYRMU1B3onTqe3wanbLA

**Comment by lukaszfryc** [comment]
This also happened after enabling bootnodes in Profile. But, I could not reproduce it.
