### ISSUE TITLE
QR code buttons in custom mailservers and bootnodes are hard to tap

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4631]
### Description

*Type*: Bug

*Summary*: Tapping it once always closes the keyboard but does not open the QR scanner (Android and iOS). Tapping it again does not open it sometimes as well (Android only, iOS worked fine). Maybe we should increase the tapping area?

<img src="https://user-images.githubusercontent.com/7532782/40963385-a76548d2-68a8-11e8-86ac-b17a223d6a04.png" width="200">

#### Expected behavior
The QR code button looks and behaves like the button in new chat screen. Notice the big tapping area and that it's separated from the input field:
 
<img src="https://user-images.githubusercontent.com/7532782/40963551-33097b92-68a9-11e8-89e1-2c5f758265c0.png" width="200">

#### Actual behavior
Button is hard to tap.

### Reproduction

- Open Status
- Go to Profile, Advanced
- Open Mailserver option and add mailserver by scanning QR code

### Additional Information
* Status version: build from https://github.com/status-im/status-react/pull/4616
* Operating System: Android, iOS

**Comment by cammellos** [comment]
closed via #4617
