### ISSUE TITLE
Improve random mailserver logic to ensure a mailserver is always selected

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4643]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to always have a mailserver selected so that I can continue receiving expired messages, even when installing a new build which contains mailservers with different IDs.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently the mailserver selection is saved by ID. When the default mailserver IDs are changed, the app shows the list with no selection. When we try to restore a mailserver and the ID is not found, we should execute the random selection logic again.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

- I install a new build which has different IDs for the mailservers
- When I open the mailserver list in Profile, a new mailserver has been selected

#### Actual behavior
[comment]: # (Describe what actually happened.)

- I install a new build which has different IDs for the mailservers
- When I open the mailserver list in Profile, no mailserver is selected

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1400.00
Contract address: [0x23e1fdf5803fbddd520f2e94eda4086455e6151f](https://etherscan.io/address/0x23e1fdf5803fbddd520f2e94eda4086455e6151f)
Network: Mainnet
Paid to: cammellos
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
