### ISSUE TITLE
Add DAI token to tokens list

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4648]
### Description

*Type*: Feature

*Summary*: @pablanopete asks to add DAI https://www.cryptocompare.com/api/data/coinlist/ to list of tokens

#### Expected behavior
DAI asset is added

#### Actual behavior
DAI token is missing 

### Reproduction

- Open Status
- Wallet - Manage Assets

### Additional Information
* Status version: ...
* Operating System: Android, iOS

<blockquote></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 600.00
Contract address: [0x5e2ae47063c55902b160738d6c4c217638df6da7](https://etherscan.io/address/0x5e2ae47063c55902b160738d6c4c217638df6da7)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
