### ISSUE TITLE
A user is not able to send a transaction both on Ropsten and Mainnet

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#4652]
### Description

*Type*: Bug

The issue has been found during `Chain Resynch in progress, indexing has temporarily been paused.` on https://ropsten.etherscan.io/. 

- 0 funds is shown for recovered users which has funds, also inefficient funds is shown when such user is trying to send a transaction
- A user stays on the same screen if he tries to sign any transaction with correct password after getting some funds from /faucet (funds are shown on wallet)

**Please note, the issue is reproducible on Mainnet**

**Actual behavior:**
User stays on the same screen after entering valid password and tapping on 'Sign transaction button'

**Expected behavior:**
A screen with `GOT IT` button and information about 12 confirmations is shown, transaction is signed 

**Steps to Reproduce:**

1. Create a user
2. Request funds from /faucet 
3. Sign a transaction using /send in chat or wallet

### Additional Information
* Status version:  `2136fe`
* Operating System: Android/iOS

**Comment by annadanchenko** [comment]
nightly build, june 7, ropsten network. Nothing happens after tap on Sign transaction in Wallet:
https://app.testfairy.com/projects/4803590-status/builds/8456530/sessions/15/?accessToken=MEkbLeqkCWSjw8gfZPn5j8lRtTg

**Comment by lukaszfryc** [comment]
@PombeirP should we close this issue since https://github.com/status-im/status-react/pull/4659 is merged?

**Comment by goranjovic** [comment]
@lukaszfryc If the issue was resolved by it, please do.

**Comment by goranjovic** [comment]
I see it works now, so closing
