### ISSUE TITLE
Add Help section and links to Profile tab

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4653]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to go to a Help section so that I can learn about Status, submit bug reports and feature requests.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Status has a lot of resources, such as FAQ's, feature requests, bug reporting, etc that are valuable to users, but there is no Help/Support section in the app where users can find information. Further, some functionality is missing (eg FAQ), and some is hidden (eg shake to get instabug). To remedy this and help users we can add a simple `Help` section that is a central in-app resource for users.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Users looking for help can find it on the Profile tab under settings (typical app pattern).

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

* On the profile tab, under settings, add a `Help` item. 
* Tapping `Help` will take the user to a help screen with the following items:
  * Frequently asked questions (opens webview to [FAQ](https://wiki.status.im/Questions_around_beta#firstHeading))
  * Submit a bug (opens Instabug bug reporting)
  * Request a feature ([opens Instabug feature request screen](https://docs.instabug.com/docs/react-native-feature-requests#section-invoking-the-feature-requests))

**Comment by denis-sharypin** [comment]
Hey @chadyj  what do you think?
![help center](https://user-images.githubusercontent.com/6559881/41228326-51f71a4a-6d78-11e8-9274-94aa0100731a.jpg)
