### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4662]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use Status on a tablet so that I can use Status on all of my mobile devices.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Status can be used on a iPad, but instead of running at native resolution the viewport is set to an iPhone 4 and everything is scaled up. Whilst the app is usable, it is a horrible user experience and doesn't take advantage of the devices resolution and screen real estate.

![img_0041 png 2018-06-05 15-11-48](https://user-images.githubusercontent.com/116099/41084672-21724e80-6a35-11e8-958b-080d63ed272a.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Status runs at native resolution

#### Actual behavior
[comment]: # (Describe what actually happened.)
Status runs at a lower resolution and is scaled up

### Solution
* Make Status a universal app as outlined in [this post](https://shellmonger.com/2017/08/14/universal-ios-apps-with-react-native/).
* Additionally, select all device orientation modes so it works in landscape mode too
* Thoroughly test all screens at different tablet resolutions to ensure layouts look/work as expected
* Fix any display bugs that arise
* Bonus: Get split screen mode working ([similar issue](https://github.com/facebook/react-native/issues/16152))

<img width="661" alt="screen shot 2018-06-08 at 1 37 33 pm" src="https://user-images.githubusercontent.com/116099/41156300-9e37a360-6b21-11e8-9806-e92ecc465a3b.png">

**Comment by lukaszfryc** [comment]
More screenshots of current iPad look: https://github.com/status-im/status-react/pull/4658

**Comment by chadyj** [comment]
I did some testing with the fix mentioned above and many of the screens look great on an iPad. Here are [several screenshots](https://docs.google.com/document/d/1GAzCM-s1rmpMhaduwyjnIMBYJsrFPUM_7oWrLnwzjgY/edit).

<img width="998" alt="screen shot 2018-06-08 at 1 25 34 pm" src="https://user-images.githubusercontent.com/116099/41155843-cc6e8e30-6b1f-11e8-823a-77382d8b4089.png">

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1ebe41185e371a79bbcd87b24d381e3ec6e53e6c67067fb10e6bc885f0989872](https://etherscan.io/tx/0x1ebe41185e371a79bbcd87b24d381e3ec6e53e6c67067fb10e6bc885f0989872)
