### ISSUE TITLE
Add Etheremon to DApp list

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4669]
### User Story

As a user, I want to use Etheremon to buy new collectibles for my Status wallet. 

### Description

*Type*: Feature

*Summary*: 
Add Etheremon to the DApp list

DApp icon: https://www.dropbox.com/s/kjvuv14raha7q9t/etheremon.png?dl=0

Description: Decentralized World of Ether Monsters

URL: https://www.etheremon.com/

#### Expected behavior
Etheremon is displayed in the DApp list

#### Actual behavior
Etheremon is not listed

<blockquote><img src="https://www.dropbox.com/temp_thumb_from_token/s/kjvuv14raha7q9t?preserve_transparency=False&size=1024x1024&size_mode=2" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/kjvuv14raha7q9t/etheremon.png?dl=0">etheremon.png</a></strong></div><div>Shared with Dropbox</div></blockquote>
<blockquote><img src="https://www.etheremon.com/assets/images/banner_facebook.png" width="48" align="right"><div><strong><a href="https://www.etheremon.com/">Etheremon - Decentralized World of Ether Monsters</a></strong></div><div>Decentralized World of Ether Monsters (Etheremons) - Train Your Mons & Earn Ether</div></blockquote>

**Comment by asemiankevich** [comment]
@rachelhamlin seems a good bounty candidate! Added labels accordingly

**Comment by rachelhamlin** [comment]
@asemiankevich boom. Thank you!
