### ISSUE TITLE
Set mainnet as default network for beta ⚡️

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4671]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to to be on mainnet by default so that I can easily transact and use dapps.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The key feature of Status beta is mainnet by default. This issue will default all new accounts to mainnet.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New accounts are on mainnet

#### Actual behavior
[comment]: # (Describe what actually happened.)
New accounts are on testnet

### Solution

Mainnet is default network

### Additional Information

This issue will be coordinated with the beta launch. It shouldn't be merged until the beta release is being prepared.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 600.00
Contract address: [0x30f8790c4f98e819225c32b66e84cc919d0b3b9d](https://etherscan.io/address/0x30f8790c4f98e819225c32b66e84cc919d0b3b9d)
Network: Mainnet
Paid to: rasom
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
