### ISSUE TITLE
Timelag and different chats recovered for same account when recovering account as a second record

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4675]
### Description

*Type*: Bug

*Summary*: 

Case 1: I have nightly build and recover the account. Several chats are shown after recovery. I can navigate through the app easily.

![image](https://user-images.githubusercontent.com/28752642/41101878-13ff27bc-6a6e-11e8-9a5f-09b638409bd1.png)

Case 2: I have nightly build with a new account created. I log out from this account and recover known one. Time lag before I can navigate through tabs and more chats are recovered than in case 1

![image](https://user-images.githubusercontent.com/28752642/41101910-28d21596-6a6e-11e8-9fe9-d498527dd2b8.png)

#### Expected behavior

- no time lag between tabs navigation when recovering an account
- message history belongs to a certain account and recovered same way 

#### Actual behavior

Please check TestFairy: https://app.testfairy.com/projects/4803622-status/builds/8452362/sessions/155/?accessToken=nJ1PP73rnTnlJixHFd1VVTNpsvQ

### Reproduction

for case 1:
- Open Status with nightly build and recover account

for case2:
- Open status with nightly build and create the new account
- Log out and recover the account

### Additional Information
* Status version: latest nighlty
* Operating System: Android

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8452362/sessions/155/?accessToken=nJ1PP73rnTnlJixHFd1VVTNpsvQ">TestFairy: Status 0.9.19 (6036) @155</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@asemiankevich At the moment we make no guarantees on chat/contacts recovery (you might get some or none),it only happens to work sometimes, so the behaviour is unspecified, but the lag is still a relevant issue.

**Comment by asemiankevich** [comment]
@cammellos i am just curious why the number is different in those 2 cases for same account?

**Comment by cammellos** [comment]
@asemiankevich hard to say, a few things could be:
1) Different mailservers were used, at the moment the messages are kept in different databases, so likely 2 mailservers don't hold the same messages
2) Some messages might have been lost in transit
I guess there might be other explanations as well, in general it's something we haven't looked much into I believe.
