### ISSUE TITLE
Add to favorites feature for Dapps

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4679]
### User Story

As a user, I want to bookmark a Dapps. 

### Description

*Type*: Feature

*Summary*: I want to have the ability to bookmark a dapp i like most

#### Expected behavior
Users may have favorite DApps that aren't included in our list so we need a feature to allow this

@andmironov please take a look

**Comment by denis-sharypin** [comment]
I think the home tab could be a place for favorite dapps

**Comment by denis-sharypin** [comment]
It requires UXR input before
