### ISSUE TITLE
Implement DiscardTransactions() and CompleteTransactions() on status-react side

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#468]
https://github.com/status-im/status-go/pull/60

**Comment by jarradh** [comment]
I think this issue can be closed?

**Comment by jarradh** [comment]
@rasom what's this issue?

**Comment by rasom** [comment]
In the first place, we had only `DiscardTransaction`/`CompleteTransaction`. These methods are not very convenient when we need to discard/complete more than one transaction at once. But at the same time we have this functionality implemented with `DiscardTransaction`/`CompleteTransaction`, so this is not urgent.

It's easy to implement on `status-react` side, will add this soon.

**Comment by GustavoNunes** [comment]
@rasom `CompleteTransactions` is now implemented, and we are not discarding multiple transactions at once anymore, maybe this could be closed.
