### ISSUE TITLE
Add pre-run checks to merge-pr.sh script

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4681]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to be able to merge as reliably as possible so that I can focus on development tasks.

### Description

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Improve the https://github.com/status-im/status-react/blob/develop/scripts/merge-pr.sh script so that it does some initial precondition checks to avoid failing only at the end.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

When my local `develop` branch is not synced with the `origin/develop` branch, `merge-pr.sh` should inform me of that situation and ask me to sync the local `develop` branch. It could ask to select one of two options:
- do you want to reset local `develop` to `origin/develop`?
- cancel

That would avoid going through the whole script only to find this message at the end:
```
Switched to branch 'develop'
Your branch and 'origin/develop' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Updating 0340a631..af0b64f5
Fast-forward
 src/status_im/ui/screens/add_new/views.cljs | 15 +++++++++------
 src/status_im/ui/screens/profile/subs.cljs  |  4 ++++
 src/status_im/utils/mixpanel_events.cljs    | 15 ++++++++++-----
 3 files changed, 23 insertions(+), 11 deletions(-)
To github.com:status-im/status-react.git
 ! [rejected]          develop -> develop (non-fast-forward)
error: failed to push some refs to 'git@github.com:status-im/status-react.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

#### Actual behavior
[comment]: # (Describe what actually happened.)

1. Fetch the remote repo
2. Compare local `develop` hash with `origin/develop` hash
3. If they differ, provide user with the two options above

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 600.00
Contract address: [0x6e02a41a782e89cd2ad06a993bb6c0ca8342537d](https://etherscan.io/address/0x6e02a41a782e89cd2ad06a993bb6c0ca8342537d)
Network: Mainnet
Paid to: zlita
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by fanmeilexiu** [comment]
en
