### ISSUE TITLE
Blacklist known phishing sites

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4699]
### User Story

As a user, I want to be protected from visiting known scam sites so that I don't accidentally make transactions with a bad actor.

### Description

*Type*: Feature

*Summary*: Use a blacklist of bad URLs to prevent users from easily accessing scam or phishing sites.

By way of example: MetaMask [blacklists a set of known scam/phishing URLs](https://github.com/MetaMask/eth-phishing-detect/blob/4ddbb2cbc6fb40782084fa1ee6e5696944cfdc8a/src/config.json#L308) to protect users, and keeps it up-to-date it using the Levenshtein distance algorithm.  

#### Expected behavior
I receive an error screen when I try to navigate to a blacklisted URL. 

#### Actual behavior
I'm able to load phishing sites in the browser.

<img src="https://user-images.githubusercontent.com/15470435/41215738-0cb2b302-6d52-11e8-8399-83323d30506d.jpg" width = 250/>

### Reproduction

- Open browser
- Navigate to https://ethpubs.com

<blockquote><img src="https://i.imgur.com/Zn8kfwZ.jpg" width="48" align="right"><div><strong><a href="https://ethpubs.com/">Hurry Up! Claim your ETH NOW!</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
maybe we could use this API https://etherscamdb.info/scams 

<blockquote><img src="https://etherscamdb.info/img/logo.png" width="48" align="right"><div><strong><a href="https://etherscamdb.info">Ethereum Scam Database</a></strong></div><div>Keep track of all current ethereum scams in a large open-source database</div></blockquote>

**Comment by sraosha9** [comment]
bitcoinben.io@gmail.com pretending to be the youtuber Bitcoin Ben contacted me to lure me on a website https://www.coinprofitex.ml to send my cryptos there. I sent a test amount since these emails were using very similar language as Ben and couldn't withdraw the test amount anymore. The whole email conversation spanning several days confirmed that this definitely is a scam operation. 

<blockquote><div><strong><a href="https://www.coinprofitex.ml/">Coinprofitex - The Leading Global Digital Asset Exchange, Mining, Trading And Investment Platform</a></strong></div><div>Mining is Bitcoin cloud mining platform Start bitcoin mining free earn profit daily without hardware.</div></blockquote>

**Comment by bobmoff** [comment]
Hi! I have received a similar email from contact.cryptodailyuk@gmail.com pretending to be youtuber Crypto Daily and trying to make me invest in the same site: https://www.coinprofitex.ml 

Watch out!

I did a google image search on one of there testimonials people and found that the images of the people are just copies from this template site: https://www.templatemonster.com/pl/demo/68326.html

<blockquote><div><strong><a href="https://www.coinprofitex.ml/">Coinprofitex - The Leading Global Digital Asset Exchange, Mining, Trading And Investment Platform</a></strong></div><div>Mining is Bitcoin cloud mining platform Start bitcoin mining free earn profit daily without hardware.</div></blockquote>
<blockquote><img src="https://s.tmimgcdn.com/scr/68300/responsywny-szablon-strony-www-rochacoin-cryptocurrency-multipage-html5-68326_68326-big.jpg" width="48" align="right"><div><img src="https://s.tmimgcdn.com/img/logo-touch/android-chrome-192.png?d=900f612" height="14"> TemplateMonster</div><div><strong><a href="https://www.templatemonster.com/pl/demo/68326.html">Demo szablonu #68326</a></strong></div></blockquote>
