### ISSUE TITLE
Back and forward browser buttons do not work for CryptoKitties 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4701]
### Description

*Type*: Bug

*Summary*: For some reason back and forward browser buttons do not work for CryptoKitties DApp. They are inactive. I tried to compare it with Toshi but apparently they delisted CryptoKitties. But, when app is opened on Chrome on a desktop, everything works. 

#### Expected behavior
User can navigate through CryptoKitties DApp by pressing back and forward buttons.

#### Actual behavior
Back and forward buttons are disabled.

### Reproduction

- Open Status
- Open CryptoKitties DApp

### Additional Information
* Status version: nightly, 11 June
* Operating System: Android, iOS

**Comment by rachelhamlin** [comment]
Should also fix #3639

**Comment by antdanchenko** [comment]
The same issue has been described in https://github.com/status-im/status-react/issues/4167

**Comment by lukaszfryc** [comment]
Closing as duplicate of #4167
