### ISSUE TITLE
Update public chats list

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4707]
### User Story

As a user, I want to discover new public chats so that I can discuss topics of interest.

As a core contributor, I want to invite conversation about topics that are newsworthy at Status to get community input.

### Description

*Type*: Feature

*Summary*: 

Add `#cryptostrikers` as a default public chat.

Add `#dapps` as a default public chat.

Remove `#edcon` as a default public chat.

#### Expected behavior
The default public chat list includes #cryptostrikers and #dapps, but not #edcon.

#### Actual behavior
Of these 3 topics, the default public chat list only contains #edcon.

**Comment by annadanchenko** [comment]
@rachelhamlin and other not mentioned existing public chats should stay in the list, right? 
- status
- openbounty
- ethereum

**Comment by rachelhamlin** [comment]
Yes ma'am @annadanchenko!

**Comment by asemiankevich** [comment]
@rachelhamlin no #Chineese #Russian and some other ones @pablanopete has mentioned in https://status-im.slack.com/archives/C8QP8S5UH/p1528411614000289? Not sure what is the decision for these. Sorry if this was discussed and i missed the outcome

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/C8QP8S5UH/p1528411614000289">Slack</a></strong></div></blockquote>

**Comment by rachelhamlin** [comment]
@asemiankevich oh interesting, I did not see that. We need this specific change included in .9.20, but for beta—do you have any thoughts about country or language-specific public chats @chadyj?
