### ISSUE TITLE
Inform beta users that mainnet is default

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4718]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a beta user, I want to be informed of new default network behavior so that I'm aware of the changes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Users upgrading to beta might not be aware that Mainnet is the default network which could cause confusion, or even worse. To be clear about significant changes we should alert users when installing the beta clearly informing them that the default network in now mainnet. 

### Solution
Similar to previous upgrade alerts we have used, let's show an alert:

> Hello
> Thanks for choosing Status! We are now in Beta, which means new installs are automatically connected to the Mainnet. If you upgraded, you may still need to switch networks, which you can do easily by navigating to your Profile -> Advanced Mode -> Switch Developer Mode on -> Choose your network. Now just have fun! Browse DApps, exchange assets, start your own #chats, and message your friends, all from the world's first decentralised, mobile client for Ethereum. 
>
>Please note that this is a beta release and we advise you that using this app should be done for testing purposes only and you assume the full responsibility for all risks concerning your data and funds.

**Comment by asemiankevich** [comment]
i suggest something like
`We are glad to see you here! Proudly announce that Status is now Beta and it means you can easily browse Dapps and exchange assets on Mainnet which is default network you are currently connected to. If you like to browse the app and feel the features on Ropsten - you are still able to switch to it under dev mode (Profile - Dev mode toggle - Network).`

**Comment by annadanchenko** [comment]
1. for new users who install first time and create an account - not sure we need to explain anything. By default they will assume we are on mainnet and they will see it in the settings.
2. for existing users who upgrade - imo, network that was selected before upgrade should `remain`. So, no need to warn about mainnet, existing choice will be re-used.
3. for users who are recovering account - as they might use Status before and expect tesnets, we can add a warning but short one like Mainnet is selected by default…

**Comment by lukaszfryc** [comment]
I agree with Anna. 

Re 2), I checked if network selection is persisted while upgrading from 0.9.19 (testnet by default) to latest nightly (mainnet by default - the case for Beta). And it works fine. But, of course we should recheck it on the Beta release build.

**Comment by andytudhope** [comment]
I disagree with Anna. I think we do need to be explicit that Status is on mainnet, especially for new users.

`
Thanks for choosing Status! We are now in Beta, which means new installs are automatically connected to the Mainnet. If you upgraded, you may still need to switch networks, which you can do easily by navigating to your Profile -> Advanced Mode -> Switch Developer Mode on -> Choose your network.   
Now just have fun! Browse DApps, exchange assets, start your own #chats, and message your friends, all from the world's first decentralised, mobile client for Ethereum.
`

There were lots of questions with 0.9.19 about how to turn Mainnet on, so having explicit directions for toggling this would be great imo. Can also remove the last 2 sentences if too long.

**Comment by chadyj** [comment]
Thanks @andytudhope. Looks good!

**Comment by annadanchenko** [comment]
@chadyj any extra disclaimer that even in beta it's still possible to loose funds etc, so use it for testing purposes... something like we had in the warning for mainnet switching?

**Comment by chadyj** [comment]
@annadanchenko added "Please note that this is a beta release and we advise you that using this app should be done for testing purposes only and you assume the full responsibility for all risks concerning your data and funds." taken from the old warning.  cc @dmitryn

**Comment by dmitryn** [comment]
@chadyj this is how it looks like:

<img width="539" alt="screenshot 2018-06-19 20 04 44" src="https://user-images.githubusercontent.com/23836/41612615-1b42ba38-73fc-11e8-8e63-7341ad79b736.png">
<img width="539" alt="screenshot 2018-06-19 20 04 19" src="https://user-images.githubusercontent.com/23836/41612616-1b67fdf2-73fc-11e8-962e-66a4667dd776.png">

Not sure about text formatting, but i don't like how "Hello" is looking at version 2 so i placed "Hello" into the title.

**Comment by dmitryn** [comment]
@chadyj second question is when exactly (on app start?) and how many times (once, every time?) this warning should be shown.

**Comment by chadyj** [comment]
Looks good! 
This should be shown once when installing/upgrading to this version.  We've had some logic in the app to display similar upgrade messages so there should be a reference out there.

**Comment by asemiankevich** [comment]
@dmitryn keyboard hides the message on iOS and tapping outside the warning does not close the keyboard, neither scrolling is working. Can't read the full warning as result. iPhone 7, iOS 11.4

![image](https://user-images.githubusercontent.com/28752642/41704593-583ca89c-753f-11e8-8d0c-6e4758dbbc2c.png)
