### ISSUE TITLE
Add CryptoStrikers to DApp list

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4719]
### Description

*Type*: Feature

*Summary*: add CryptoStrikers to Dapps curated list in Status

#### Expected behavior

Cryptostrikers dapp icon: https://www.dropbox.com/s/eq0im9xtzi13elg/cryptostrikers.png?dl=0

Description: The Beautiful (Card) Game

URL: https://www.cryptostrikers.com/

<blockquote><img src="https://www.dropbox.com/temp_thumb_from_token/s/eq0im9xtzi13elg?preserve_transparency=False&size=1024x1024&size_mode=2" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/eq0im9xtzi13elg/cryptostrikers.png?dl=0">cryptostrikers.png</a></strong></div><div>Shared with Dropbox</div></blockquote>
<blockquote><img src="https://cfl.dropboxstatic.com/static/images/icons128/folder_dropbox.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/sh/4tm0wxo7ctwh713/AAApwRg8NhPqNP553yJxSxTRa?dl=0">Tokens from dapps</a></strong></div><div>Shared with Dropbox</div></blockquote>
<blockquote><div><strong><a href="https://www.cryptostrikers.com/">CryptoStrikers</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
What is expected Description for this DApp, @rachelhamlin ?

**Comment by annadanchenko** [comment]
Can you give more details on what's expected for "Tokens ( collectibles) from dapps:"? 
Should a new Asset be added to the list of Wallet Assets? If so, with what name and in what cases it will be shown? Is it part of this issue? @rachelhamlin

**Comment by rachelhamlin** [comment]
Good question. Updated with description @annadanchenko. And removed token icons—those will be used when we support CryptoStriker collectibles in the wallet.

Sorry I overlooked the description edits @jeluard!
