### ISSUE TITLE
Back button is inactive when scrolling chat history

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4721]
### Description

*Type*: Bug

*Summary*: when scrolling the chat history I am not able to tap `back`. I have to wait until scrolling finishes to tap Back button and get out from this chat.

#### Expected behavior
back button is enabled and tappable whenever I want to get back so I don't need to wait for scrolling finishes or something else

#### Actual behavior

back button is not responsive when scrolling history

https://app.testfairy.com/projects/4803590-status/builds/8486279/sessions/4393828357/?accessToken=uRsWZcdGR5X/A58hLUkCDhjW9cc

### Reproduction

- Open Status
- Join #status channel
- Scroll history and tap back simultaneously 

NOTE: not reproducible on simulator

### Additional Information
* Status version: develop
* Operating System: iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8486279/sessions/4393828357/?accessToken=uRsWZcdGR5X/A58hLUkCDhjW9cc">TestFairy: Status 0.9.19 (6046) @6</a></strong></div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb902f330d0c243a5603ea73f095504eff0cd64bf550d33920257ca1f210e7abc](https://etherscan.io/tx/0xb902f330d0c243a5603ea73f095504eff0cd64bf550d33920257ca1f210e7abc)

**Comment by andytudhope** [comment]
@asemiankevich can we close here?

**Comment by asemiankevich** [comment]
@andytudhope yes, please do
