### ISSUE TITLE
Make [Enter] button default to proceed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4728]
### User Story

As a user I want to user `Enter` key in the application so i dont need to click Confirm / Proceed with a mouse

### Description

*Type*: Bug

*Summary*: Hitting enter does not confirm user's choice , for example when i set up account and want to confirm my selection i need to click `Continue` with a mouse

#### Actual behavior

Can't use enter key to confirm my choice where necessary 

![image](https://user-images.githubusercontent.com/28752642/41294740-78344d24-6e61-11e8-93dc-eb292e2d3208.png)

**Comment by rasom** [comment]
@asemiankevich can you be more specific where it is necessary?

**Comment by asemiankevich** [comment]
@rasom 
in particular i was thinking of set up password screens: so expecting text input field in autofocused and when i entered password i can hit enter to proceed with next screen (confirm password in this case).

More cases to come when wallet is available in desktop

**Comment by rasom** [comment]
ok
