### ISSUE TITLE
Make stable and reliable messaging between desktop and mobile

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4730]
### User Story

As a user, I want to have stable messaging between desktop and mobile apps.

### Description

*Type*: Bug

*Summary*: messaging does not work when sending something from desktop to mobile. Talked to @MaxRis and @vkjr and here is a possible solution to make it working:

1. ~~Merge new version of react-native into react-native-desktop~~ (moved to #4743)
2. Merge desktop branch into develop.
3. Anything what was added recently and requires some special porting to desktop ( how about db encryption )
4. ~~merge latest status-go changes into status-go desktop branch.~~ (moved to #4841)

#### Expected behavior
Messaging is stable and reliable between desktop and  mobile

**Comment by vkjr** [comment]
@chu, @asemiankevich, PR #5284 will be the last one about merging `desktop` and `develop` branch. I'm wondering, how we will test the `stable and reliable messaging` after it is merged?
Do we have a dedicated tests for that?

**Comment by asemiankevich** [comment]
@vkjr we have message reliability tests for mobile app (automated). Nothing is automated for desktop yet. The only solution I see for now is testing this manually for the desktop. Do you have any suggestions in mind?

**Comment by vkjr** [comment]
@asemiankevich, not really :( Was asking mostly because I'm assigned to this one. Maybe after merge I'll remove the assignment and change description since merge on itself doesn't guarantee reliable messaging.

**Comment by vkjr** [comment]
Merging to `develop` finished. So this issue could be tested to check if messaging is reliable.

**Comment by maxhora** [comment]
Please aware about https://github.com/status-im/status-react/issues/5317 potential issue.

**Comment by vkjr** [comment]
@MaxRis, good point, thanks!

**Comment by churik** [comment]
Fixed since rebased to `develop` branch
