### ISSUE TITLE
Empty Wallet balance while funds are actually exist which is confirmed in etherscan at the same time

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4734]
***Type***: Bug

***Summary***: In some instances when a contact opens application and logs in to account the Wallet balance may be 0 for ETH and other assets while address, in fact, has funds which is confirmed by checking it at the same time in etherscan. 
I experienced this issue several times and re-login to the same account several times haven't made any difference -> assets were empty.
However, app restart followed by login to same account may fetch the correct balance.

#### Expected behavior
Actual wallet balance equal to what is in etherscan for the same address

#### Actual behavior
0 ETH, 0 tokens but etherscan shows funds fine

### Reproduction
**Note**: there are no direct steps to reproduce for now, but TF session with the logs may reveal what actually happened

- Open Status and log in to existing account with funds (on any network)
- Check if balance != 0 on Wallet main screen 
- Repeat above two steps several times if issue is not reproduced

### Additional Information
* Status version: Develop nightly build 12th of June (however, it was seen also on the 0.9.19 (6031) build
* Operating System: Android and iOS

#### Logs

TF session with logs where after login there are 0 ETH and 0 STT on Ropsten: https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393837877/?accessToken=Cmnl/l33g0VlJwtKYFe1eE4BOK4
TF session for same account after app restarted and everything is OK: https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393838804/?accessToken=sS/PYym5mO/Qhk-fnY7enjWChNw

Or later in time: 
TF session where again, 0 funds for same user: https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393840579/?accessToken=KfcXCyz8skvcYe8vtXbR7hwc/rA
TF after session after app reoped again and it's all fine: https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393840579/?accessToken=KfcXCyz8skvcYe8vtXbR7hwc/rA

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393837877/?accessToken=Cmnl/l33g0VlJwtKYFe1eE4BOK4">TestFairy: Status 0.9.19 (6044) @213</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393838804/?accessToken=sS/PYym5mO/Qhk-fnY7enjWChNw">TestFairy: Status 0.9.19 (6044) @219</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393840579/?accessToken=KfcXCyz8skvcYe8vtXbR7hwc/rA">TestFairy: Status 0.9.19 (6044) @221</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393840579/?accessToken=KfcXCyz8skvcYe8vtXbR7hwc/rA">TestFairy: Status 0.9.19 (6044) @221</a></strong></div></blockquote>

**Comment by Serhy** [comment]
The issue appeared for me again in a later build. One by one I restarted an app having a single account and ETH balance was or 0 (wrong) or >0 (correct) 
TF sessions where balance failed to be fetched:
https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393958587/?accessToken=FfTrZskX7Ma-4cBIFnmDuPzPgOE
https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959213/?accessToken=MD19ebMKIZf-ht6M9XA/xC8I9Ao
https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959281/?accessToken=57TA3NivXxMEX5SbkAqRD0LueiA

And the same build with the same account when everything is fine:
https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393958818/?accessToken=ojRJr2YTqYH32ahyVH9gEp1C5c0
https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959170/?accessToken=ZP15U70Gt7kG2e98fA0qmU4bc9I
https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959248/?accessToken=PbvI9IgE4zhTvz4NmdFVQf3erCM

Looking in logs, when balance in 0 what happens is: 

```00:10 D/StatusModule: Received message: { when=0 what=0 target=im.status.ethereum.module.ServiceConnector$IncomingHandler }
00:10 D/StatusModule: Signal event: {"type":"node.ready","event":null}
00:10 D/StatusService: Signal event: {"type":"node.crashed","event":{"error":"node is already running"}}
00:10 D/StatusService: before sendReply true
00:10 D/StatusModule: Received message: { when=-4ms what=0 target=im.status.ethereum.module.ServiceConnector$IncomingHandler }
00:10 D/StatusModule: Signal event: {"type":"node.crashed","event":{"error":"node is already running"}}
00:10 D/ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :signal-event {"type":"discovery.started","event":null}
00:10 D/ReactNativeJS: DEBUG [status-im.ui.screens.events:421] - :event-str {"type":"discovery.started","event":null}
00:10 D/ReactNativeJS: DEBUG [status-im.ui.screens.events:434] - Event  discovery.started  not handled
00:10 D/ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :signal-event {"type":"node.started","event":null}
00:10 D/ReactNativeJS: DEBUG [status-im.ui.screens.events:421] - :event-str {"type":"node.started","event":null}
00:10 D/ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :status-node-started
00:10 D/ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :signal-event {"type":"node.ready","event":null}
00:10 D/ReactNativeJS: DEBUG [status-im.ui.screens.events:421] - :event-str {"type":"node.ready","event":null}
00:10 D/StatusService: Signal event: {"type":"discovery.summary","event":[{"id":"7500e64a9a3b1dd1321da0c7fe725af038d82b20a028b5aeeddd4e52d4f682705f2838cc427937b1f20190cd4a1ea1f0850c6bd9317c08de8b368eb869f575a5","name":"Statusd/v0.9.9-8141657a/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.1.182:40860","remoteAddress":"206.189.108.50:30304","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
00:10 D/StatusService: before sendReply true
00:10 D/StatusModule: Received message: { when=-1ms what=0 target=im.status.ethereum.module.ServiceConnector$IncomingHandler }
00:10 D/StatusModule: Signal event: {"type":"discovery.summary","event":[{"id":"7500e64a9a3b1dd1321da0c7fe725af038d82b20a028b5aeeddd4e52d4f682705f2838cc427937b1f20190cd4a1ea1f0850c6bd9317c08de8b368eb869f575a5","name":"Statusd/v0.9.9-8141657a/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.1.182:40860","remoteAddress":"206.189.108.50:30304","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
00:10 D/ReactNativeJS: DEBUG [status-im.ui.screens.events:434] - Event  node.ready  not handled
00:10 D/ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :signal-event {"type":"node.crashed","event":{"error":"node is already running"}}
00:10 D/StatusService: Signal event: {"type":"discovery.summary","event":[{"id":"7500e64a9a3b1dd1321da0c7fe725af038d82b20a028b5aeeddd4e52d4f682705f2838cc427937b1f20190cd4a1ea1f0850c6bd9317c08de8b368eb869f575a5","name":"Statusd/v0.9.9-8141657a/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.1.182:40860","remoteAddress":"206.189.108.50:30304","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"id":"93d67ae104ab9f28afa253942c7f7efeac300fb2b2cce6e59e661b0781b94365c0d987498022d0a338e7497786cfe5d3fe891173109319b4f92bc7c6df504f73","name":"Statusd/v0.9.9-8141657a/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.1.182:52722","remoteAddress":"206.189.108.76:30304","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
00:10 D/StatusService: before sendReply true
00:10 D/StatusModule: Received message: { when=-1ms what=0 target=im.status.ethereum.module.ServiceConnector$IncomingHandler }
00:10 D/StatusModule: Signal event: {"type":"discovery.summary","event":[{"id":"7500e64a9a3b1dd1321da0c7fe725af038d82b20a028b5aeeddd4e52d4f682705f2838cc427937b1f20190cd4a1ea1f0850c6bd9317c08de8b368eb869f575a5","name":"Statusd/v0.9.9-8141657a/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.1.182:40860","remoteAddress":"206.189.108.50:30304","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"id":"93d67ae104ab9f28afa253942c7f7efeac300fb2b2cce6e59e661b0781b94365c0d987498022d0a338e7497786cfe5d3fe891173109319b4f92bc7c6df504f73","name":"Statusd/v0.9.9-8141657a/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.1.182:52722","remoteAddress":"206.189.108.76:30304","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
00:10 D/ReactNativeJS: DEBUG [status-im.ui.screens.events:421] - :event-str {"type":"node.crashed","event":{"error":"node is already running"}}
```

The ```{"type":"node.crashed","event":{"error":"node is already running"}}```  apparently the reason why in some cases Wallet balance shows 0s.

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393958587/?accessToken=FfTrZskX7Ma-4cBIFnmDuPzPgOE">TestFairy: Status 0.9.19 (6043) @424</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959213/?accessToken=MD19ebMKIZf-ht6M9XA/xC8I9Ao">TestFairy: Status 0.9.19 (6043) @427</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959281/?accessToken=57TA3NivXxMEX5SbkAqRD0LueiA">TestFairy: Status 0.9.19 (6043) @429</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393958818/?accessToken=ojRJr2YTqYH32ahyVH9gEp1C5c0">TestFairy: Status 0.9.19 (6043) @425</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959170/?accessToken=ZP15U70Gt7kG2e98fA0qmU4bc9I">TestFairy: Status 0.9.19 (6043) @426</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8470299/sessions/4393959248/?accessToken=PbvI9IgE4zhTvz4NmdFVQf3erCM">TestFairy: Status 0.9.19 (6043) @428</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
> From the logs it seems that the React side is calling `StartNode` twice at startup for some reason (one at 6s and a second at 9s) and likely interpreting the "already started" warning as an error.

**Comment by dmitryn** [comment]
@PombeirP right, it tries to start it again here https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/accounts/login/events.cljs#L121
if node was not started, i.e. `node.started` signal has not been received which is the case in this TF session https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393840579/?accessToken=KfcXCyz8skvcYe8vtXbR7hwc/rA) Signal `node.started` only received on `00:10`, but not between 6s and 9s where first `StartNode` was called.

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8473772/sessions/4393840579/?accessToken=KfcXCyz8skvcYe8vtXbR7hwc/rA">TestFairy: Status 0.9.19 (6044) @2018</a></strong></div></blockquote>

**Comment by dmitryn** [comment]
I also see `Event  node.crashed  not handled` message as status-react doesn't seem to be handling that signal https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/events.cljs#L425

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by pedropombeiro** [comment]
I do see `Geth node started` twice (once at 8s and another at 9s), so it's maybe just a question of the signal not reaching the react side in time? I'm thinking if the best solution is to just avoid calling it a second time if we're still waiting for the response to the first request.

**Comment by pedropombeiro** [comment]
The alternative (less clean) is to ignore if StartNode returns  `{"type":"node.crashed","event":{"error":"node is already running"}}`

**Comment by dmitryn** [comment]
@PombeirP i just checked how `web3.eth.getBalance` https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/wallet/events.cljs#L23 work after `node.crashed` signal has been received (i specifically called `StartNode` 2 times before) and `getBalance` still work fine.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by pedropombeiro** [comment]
This might be known, but adding it here just so it's captured. Contrary to what is implied in the 2nd post, the `node.crashed` error doesn't seem to be relevant to this issue, as it is also present in logs where the app showed the balance correctly.

**Comment by mandrigin** [comment]
can that be related to something being wrong with Infura?

**Comment by mandrigin** [comment]
```
re-frame event :update-token-balance-fail web3, contract or account-id not available

00:16 D/ReactNativeJS: DEBUG [status-im.ui.screens.wallet.events:207] - Unable to get token balance:  web3, contract or account-id not available
```

**Comment by mandrigin** [comment]
not the most helpful error message tho

**Comment by dmitryn** [comment]
@mandrigin `update-token-balance-fail` seems not related as it tells about token balance update failure only.
We update ETH balance with `update-balance` that have `update-balance-success` and `update-balance-fail` callback events. https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/wallet/events.cljs#L123

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by mandrigin** [comment]
@dmitryn just for sanity, we have one asset that is `nil` that we try to check every time, I don't know why. Maybe it is harmless, but I think we'll need to fix that too so debugging is simpler :)

**Comment by Serhy** [comment]
Reproduced issue once again on Galaxy Note 4 (Andorid 6.0) and Samsung J7 (Android 7.0)
What happens is that being on Ropsten the actual amount of ETH requested from Mainnet.

Confirmed sending in Status Console the `web3.version.network` which replied with `"1"` while all the UI in-app displayed i'm on Ropsten (apart ETH amount which was the same I have in Mainnet).

With the same steps as before:
1) Re-open app and login to account in Ropsten. 
2) Then navigate to Console and request `web3.version.network` to verify if its not `"1"` (if == '"1"' then it's bad). If for your account you have real ETH amount > 0 then check also Wallet main screen: Mainnet ETH value should be displayed.

**Comment by Serhy** [comment]
Here is TF session when issue appeared for Galaxy Note 4: ttps://app.testfairy.com/projects/4803622-status/builds/8501108/sessions/4394466511/?accessToken=RZgJCs4pvkrSwJezv01f751k7cc

And geth.log for above session: 
[geth.log](https://github.com/status-im/status-react/files/2120479/geth.log)

**Comment by Serhy** [comment]
It's worth to be added a couple of non-functional observations for when issue happens and when it's reproducible to me 95%.

We could not reproduce it on iPhoneX. 
But almost always it reproducible on less powerful devices (Confirmed Galaxy Note 4, Samsung J7) if you are really fast in actions to login to account right after Status app opened. It **doesn't matter** when the app was shut down - 5 sec before it was opened again or 10 minutes ago.

In TF sessions posted above it's visible that it takes 12-13 seconds between the time app opened on Galaxy Note4 and when you appear on Home screen. 

If you lets say open an app and stay on 'Log in to account' screen for ~30 seconds (or it takes 20-30 seconds for you to type your password) - I could not reproduce the issue in that case.
So **preconditions** to reproduce the issue: 
1) Low-end device (Note 4 is a good example, while on iPhone7 we could not reproduce it)
2) Existing contact with simple password as a way to enter password value really fast (e.g. `qwerty`/`aaaaaa`/`bbbbbb` - are good one in this relation
3) Contact in Ropsten network set
4) Fast fingers to tap on keyboard and screen elements (password editbox/Sign In button)

Steps to reproduce:
1) Open Status app (you should wind up on 'Sign in to Status' with account you are about to login)
2) Tap in password editbox
3) Enter your password and tap 'Sign In'
