### ISSUE TITLE
Add to contacts button appears after restart

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4735]
### User Story

As a user, I want to add someone to contacts once when the request actually comes in. I don't want to be confused seeing the `add to contacts` button in each 1x1 chat after I restart the app, 

### Description

*Type*: Bug

*Summary*: Side-effect of https://github.com/status-im/status-react/pull/4714. `Add to contacts` button appears after the app restart. 

#### Expected behavior
I don't want to be confused seeing the `add to contacts` button in each 1x1 chat after I restart the app

#### Actual behavior
The button appears no matter I clicked it or not. Seems we are updating local state somewhere but not saving to the realm. 

### Reproduction

- Open Status desktop
- Share your public key with someone
- See new chat on desktop
- Click `add to contacts` button
- Restart desktop app

**Comment by churik** [comment]
Closed in #5145
