### ISSUE TITLE
Update new account password copy

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4739]
### Description

*Type*: Feature request

*Summary*: 

When creating a new account, the password screen says:

> You'll need this password to open the app, confirm transactions **and whenever you need to regain access on a new device or install**.

#### Expected behavior
that part in bold is out of date with the work recently done in accounts

#### Actual behavior
remove part in bold

### Reproduction
- Open Status
- Create new account

**Comment by obi2020** [comment]
@EugeOrtiz and I worked on this as part of onboarding flow improvements. An update has been implemented in this branch https://github.com/status-im/status-react/pull/5089

**Comment by obi2020** [comment]
This should be seen with the next full release
