### ISSUE TITLE
After recover account some of 1:1 chats with only received messages are shown

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4745]
### Description

*Type*: Bug

*Summary*: If user recovered an account and had 1:1 chats before this then 
1. some of 1:1 chats are shown with only received messages
2. Usernames on 1:1 chats are shown with default random 3 words and picture  
3. Contacts are empty
4. public chats opened before recover are not shown

#### Before recover:

![home before recover](https://user-images.githubusercontent.com/6584810/41346504-f748d88c-6f06-11e8-82ab-6b8ff2440071.jpg)
![chat before recover](https://user-images.githubusercontent.com/6584810/41346514-02c5dbf6-6f07-11e8-9c3f-cd532daf8722.jpg)

#### After recover:
![home after recover](https://user-images.githubusercontent.com/6584810/41346542-0da4c078-6f07-11e8-8a76-83b56b59da18.jpg)
![chat after recover](https://user-images.githubusercontent.com/6584810/41346547-1222ba74-6f07-11e8-973b-375c98abf578.jpg)
![contacts after recover](https://user-images.githubusercontent.com/6584810/41346554-16c22b96-6f07-11e8-84af-ddd2c6629dc3.jpg)

#### Expected behavior
imo, we set false expectations by showing 1:1 chats and received messages there. We haven't implemented recover contacts/chats/messages for the case when account is recovered and how it works now is a side effect of offline inboxing. 

I would suggest to not show any chats and their content when account is recovered, so user starts with empty Home tab and Contacts (as it was before). In addition, we can add explanation on the Recover screen warning user that only address/public key will be recovered (thus funds and transaction history will be fine) but no Chats, Contacts and Chats history is recovered.

#### Actual behavior
1:1 chats with only received messages are shown after recovery. 

### Reproduction

- As account A: add account B and C to your contacts and exchange messages in 1:1 chats and public chat
- As account A: uninstall app
- As B and C send new messages to the account A
- install app and recover account A. Wait for some time to get 1:1 chats and check their content. Check what's shown in Contacts

### Additional Information
* Status version: nightly build June 13
* Operating System: Android and iOS

**Comment by lukaszfryc** [comment]
I agree. There is so many things going wrong (not all messages maybe received, default names, etc. you mentioned) that it seems like the way it works now brings more confusion than value. 

I really like the idea of having the clear explanation what and what not will be recovered in the recover screen. 

I believe we should have it in Beta version. @chadyj wdyt?

**Comment by hesterbruikman** [comment]
Sounds good to me. Let's also check if any copy in the backup seed phrase flow is helpful. Communication during recovery is a bit 'after the fact'.

Think it would be cool to experiment after Beta with how we can frame this in a way that does make sense. E.g. 'Last 7 days', 'Recent conversations' anything that clarifies that it's not all messages.

**Comment by asemiankevich** [comment]
upd:
Old transactions are restored in chat after account recovery, `TX not found` is shown for the transactions

![image](https://user-images.githubusercontent.com/28752642/41531508-300a8c30-72fc-11e8-98aa-24bf34db5510.png)
