### ISSUE TITLE
ENS support in wallet and profile

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4747]
### User Story

As a user, I want to use and see ENS names so that I can more easily interact with wallet, accounts, and profiles.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ENS usernames give users a human-readable way of interacting with Ethereum, and can improve Status usability and utility.

#### Expected behavior
Send a transaction by entering an ENS name.

Recipient address should still be supported, but ENS names are more user-friendly. Let's call out support for them by re-labeling the menu button. 

![image](https://user-images.githubusercontent.com/15470435/43190212-cec7101e-8ff8-11e8-9c30-a2addb1fa84a.png)

#### Actual behavior

Wallet supports only recipient address. Users are required to copy and paste these addresses to share them with each other.

**Comment by chadyj** [comment]
Relevant: Adding ENS to chat
https://github.com/status-im/status-react/pull/5407

**Comment by denis-sharypin** [comment]
I think it's better to keep mention of an address on the label button something like: 
`Enter address/ENS name` assuming that entering an address is a more common use case.
