### ISSUE TITLE
Add more localized channels to public chats for beta 

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#4753]
User Story
As a user, I want to discover new public chats so that I can discuss topics of interest in my localized language.

As a core contributor, I want to also be able to join the topic relevant to my dialect 

Description
Type: Feature

Summary:

Add 5 new languages as public channels in the localized language
Chinese: #中文
Japanese: #日本語
Korean: #한국어
Russian: #русский
Spanish: #español

Expected behavior
The default public chat list includes 5 new language options by default as default public channels.

**Comment by pablanopete** [comment]
This was further discussed in a slack channel here https://status-im.slack.com/archives/C8QP8S5UH/p1528411614000289 and approved by UXR and a few others.

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/C8QP8S5UH/p1528411614000289">Slack</a></strong></div></blockquote>

**Comment by chadyj** [comment]
Doesn't appear possible right now

<img width="324" alt="screen shot 2018-06-13 at 6 50 02 pm" src="https://user-images.githubusercontent.com/116099/41365772-9a0e55d2-6f3a-11e8-8157-28efcfdf2164.png">

**Comment by oskarth** [comment]
Feature. Not a beta blocker.

**Comment by pablanopete** [comment]
Following up on some comments here:

by @mandrigin 
we need to figure out how to avoid scam and potential security issues by allowing all of the Unicode there - Also, we still need to limit the character set. Unicode contains a lot of invisible control characters, zero-width spaces, etc.
And we need to make sure that channel names are always normalized somehow.

and reply from @chadyj  to cut scope for this issue

Fair point.
As a workaround would it work to hardcode the unicode channel names in https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/add_new/new_public_chat/view.cljs#L56?

Users can't create unicode channels, but it can be at least in the default list.

mentioned in #4773 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 3500.00
Contract address: [0x03703e5e8fb8c9adfd7f20c957f037693abd3fba](https://etherscan.io/address/0x03703e5e8fb8c9adfd7f20c957f037693abd3fba)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: PombeirP
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
