### ISSUE TITLE
Have to scroll down CK into page to start playing -> Done button does not close the disclaimer

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4757]
### Description

*Type*: Bug

*Summary*: 
- can't skip disclaimer for CK by tapping Done
- have to scroll the page down and tap Start Meow at the very bottom to proceed
- also good to add something about Status here on disclaimer

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/41374322-8170f9b4-6f5b-11e8-96d2-2f76b8b94d30.png)

### Reproduction

- Open Status
- Open CK
- Try to play

**Comment by rachelhamlin** [comment]
Fixed by CK team.
