### ISSUE TITLE
Plus button overlaps with text on Home screen

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#4767]
### Description

Plus button overlaps with text on Home screen after new account created.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 986fc2bc7c2559bb9e788c2582ae973141afef68
* Operating System: Android Emulator API 28

<img width="539" alt="screenshot 2018-06-14 13 04 56" src="https://user-images.githubusercontent.com/23836/41406518-4e443aae-6fd5-11e8-8e44-f4f19d09ed3d.png">

/cc @denis-sharypin @andmironov

**Comment by dmitryn** [comment]
Haven't found the mockup for this screen in Zeplin "Onboarding" section.

**Comment by andmironov** [comment]
working on this

**Comment by andmironov** [comment]
let's move the text up a bit, and add some more complex changes in future interations. 
mockup is here zpl.io/agGv1j1

Left: iOS, Right: Android
<img width="891" alt="ob" src="https://user-images.githubusercontent.com/3115606/41667259-31477d14-74b5-11e8-8a3d-a322c6d2f8e8.png">
