### ISSUE TITLE
[Draft] Resolve ENS domains in browser 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4772]
### User Story

As a user, I want to browse the fully decentralized web and load content from p2p storage platforms like IPFS and Swarm in the Status browser. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: Resolve ENS domains to IPFS/Swarm hashes and redirect to content.

#### Expected behavior
Entering a .eth address into the Status URL bar will redirect to the associated content.

#### Actual behavior
The browser can not resolve .eth addresses.

**Comment by bgits** [comment]
Example implementation via metamask:
https://github.com/MetaMask/metamask-extension/pull/4405

Tutorial for above implementation:
https://gist.github.com/PhyrexTsai/cffcbfa1d752b9cf817d920dfcd1ec9f

<blockquote><img src="https://avatars1.githubusercontent.com/u/4505863?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/PhyrexTsai/cffcbfa1d752b9cf817d920dfcd1ec9f">Integration ENS with IPFS.md</a></strong></div><div>GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.</div></blockquote>

**Comment by jeluard** [comment]
Some notes:

IPFS and SWARM won't be resolved directly (but can be via their respective http gateways).

It has to be decided if we want to go full multishash directly ([EIP1062](https://eips.ethereum.org/EIPS/eip-1062)) or first settle on `getContent` resolving to IPFS hashes (what MetaMask supports for now).

IMO it makes sense to go with option #2 as it supports existing resolvers and matches MetaMask behavior.

Sub resources (e.g. local images, JS and CSS) must be resolved accordingly. Roman pointed out the entry point for [android](https://github.com/status-im/react-native-webview-bridge/blob/master/android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java#L675) and [iOS](https://github.com/status-im/react-native-webview-bridge/blob/master/ios/RCTWKWebView.m#L272).

**Comment by bgits** [comment]
@jeluard These are fair points. IMO it's still better to have baby steps in that direction and use gateways than the current more centralized alternatives.

What are the issues with supporting multihash?
It's already been added to the latest version of the Public Resolver:
https://github.com/ensdomains/ens/blob/master/contracts/PublicResolver.sol#L90

<blockquote><img src="https://avatars0.githubusercontent.com/u/34167658?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ensdomains/ens">ensdomains/ens</a></strong></div><div>ens - Implementations for registrars and local resolvers for the Ethereum Name Service</div></blockquote>

**Comment by jeluard** [comment]
@bgits Just modified my comment :) Here is what I added : `IMO it makes sense to go with option #2 as it supports existing resolvers and matches MetaMask behavior.`

**Comment by rachelhamlin** [comment]
@flexsurfer I would second @jeluard here and say we follow the MetaMask implementation for now.
