### ISSUE TITLE
Can't access the "Password" input box when recovering an account on iPad Mini

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4778]
### User Story

As a user, I want to access the "Password" input box so that I would be able to recover my account. 

### Description

*Type*: Bug

*Summary*: It's not possible to enter any password in the ""Password" field when using iPad Mini A1432

#### Expected behavior

To be able to enter my password.

#### Actual behavior

It's not possible so I'm stuck and can't recover my account. 

### Reproduction

1. Open Status on iPad Mini A1432 or similar device. 
2. Navigate to the "Add existing account" menu. 
3. Try to enter your password in the dedicated "Password" input box. 

### Solution

*Summary*: 

Implementing at least one of the following options should be fine:

- To be able to scroll down to the "Password" input box
- To be able to select it no matter that it's not completely visible
- To be able to hide the virtual keyboard.

### Additional Information

* Status version: 0.9.19 (6031)
* Operating System: iOS

![1](https://user-images.githubusercontent.com/5781465/41457337-01657a6a-708c-11e8-9bd4-759e08f0e034.jpg)

**Comment by annadanchenko** [comment]
@GeorgiG we don't support iPads yet, please close this issue and feel free to recheck after #4662 is done

**Comment by GeorgiG** [comment]
@annadanchenko, I'll keep an eye, thanks!
