### ISSUE TITLE
Can't navigate to the screen containing the Seed Phrase on iPad Mini

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4781]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to access my Seed Phrase so that I would be able to recover my account if needed.

### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: It's not possible to navigate to the screen containing the Seed Phrase.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

To be able to navigate to the screen containing the Seed Phrase. 
#### Actual behavior
[comment]: # (Describe what actually happened.)
It's not possible because the "OK, CONTINUE" button remains hidden.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status on iPad Mini A1432 or similar device
2. Login to your account (create a new one if this is your first time run or you've already accessed your Seed Phrase on another device)
3. Navigate to the "Profile" menu
4. Click on the "Backup your Seed Phrase" menu

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Any of the following options should be enough: 

- Refactor the screen page so the button remains visible 
- Make the page scrollable

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.19 (6031)

* Operating System: iOS

![2](https://user-images.githubusercontent.com/5781465/41458442-4d507760-708f-11e8-8d2b-2e7f0ff3e816.jpg)

**Comment by mandrigin** [comment]
should be fixed when https://github.com/status-im/status-react/pull/4720 is merged

**Comment by GeorgiG** [comment]
@mandrigin, thank you, I'll close the issue for now and will reopen it after the merge if needed.
