### ISSUE TITLE
geth.log is present for release build 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4782]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  geth.log is created for release build. It should not be available on release builds.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No geth.log
#### Actual behavior
[comment]: # (Describe what actually happened.)
Android: Downloads -> geth.log
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status
- Give Storage permission to the Status app
- Run the app
- Check Downloads -> geth.log

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  release build 2 for 0.9.20
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by lukaszfryc** [comment]
@annadanchenko can you take care of updating TestRail scenarios? Let's add scenario about release build and mark it as to be automated
