### ISSUE TITLE
Remove autofocus from public chat screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4783]
### Description

*Type*: Feature

*Summary*: Remove autofocus from input field when opening public chat screen so all chats are visible and not covered under the keyboard

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/41463380-e738bdc4-709e-11e8-8426-34cd37f5f548.png)

### Reproduction
- Open Status
- Tap plus button
- Tap join public chat

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 700.00
Contract address: [0xce2df33908c7f41ae61a724bc12c4e4933c0a8b7](https://etherscan.io/address/0xce2df33908c7f41ae61a724bc12c4e4933c0a8b7)
Network: Mainnet
Paid to: tbenr
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pablanopete** [comment]
@tbenr sorry for the slow response on bounty payout, could you drop your wallet address here so I can send you the bounty amount Out of Band while we wait on a dashboard fix in Status Open Bounty. 

If you don't feel comfortable putting it here in the comment could you email a ERC20 compatible wallets address to me? chris.hutchinson@status.im

**Comment by pablanopete** [comment]
OOB Payment sent; thanks for being part of status! @tbenr
