### ISSUE TITLE
Report JS crashes to Instabug

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#4784]
### Description

We would like to see JS crashes in Instabug, but since we have custom global exception handler https://github.com/status-im/status-react/blob/develop/src/status_im/utils/error_handler.cljs#L52 automatic JS crash reporting seems not working. 

### Solution

Add manual exception reporting to that handler https://docs.instabug.com/docs/react-native-crash-reporting#section-report-exception

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://docs.instabug.com/docs/react-native-crash-reporting#section-report-exception">Crash Reporting</a></strong></div><div> In this page, you will find some APIs specific for the crash reporting. In the [**Reports Data** ](react-native-reports-data) section, you can find more information about the information and data sent with each crash report.   If your [**plan**](https://instabug.com/pricing) has crash reporting, cr...</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0349975030360395bdd21ece62eb9f33d26538cd6e8e99ff5c3901a07286be34](https://etherscan.io/tx/0x0349975030360395bdd21ece62eb9f33d26538cd6e8e99ff5c3901a07286be34)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xcf5bd9e1143219b0291707f73d51af052f2479fe6dea212d931832e59488933b](https://etherscan.io/tx/0xcf5bd9e1143219b0291707f73d51af052f2479fe6dea212d931832e59488933b)

**Comment by pablanopete** [comment]
is this still a WIP @mandrigin? Worth putting a bounty on?
