### ISSUE TITLE
Misleading transactions after getting back to the "Transaction sent" screen and confirming again

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4789]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: A 1-1 chat window may record multiple (fake) transactions If a transaction was sent and the sender selects the back button of his device, followed by a new confirmation with the "Got it" button.
This might be scary for the sender and misleading for the recipient.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New transactions should not be listed.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The chat window indicates that a new transaction has been made every time when the sender selects the "Got it" button. 
The good news is that the "Transaction history" log and respectively etherscan.io don't record the additional transactions logged into the 1-1 chat window.   

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open 1-1 chat window
2. Send ("/send") transaction
3. Sign the transaction
4. Confirm it with the "Got it" button at the "Transaction sent" screen
5. Press the back navigation button of your device.

![screenshot_2018-06-16-12-01-42-398_im status ethereum](https://user-images.githubusercontent.com/5781465/41497400-40612abc-715d-11e8-868e-9676e82af151.png)

6. Confirm once again with the "Got it" button
7. (optional) Repeat steps 4 and 5 a few more times.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 
Implementing any of the options below should be fine:

* Selecting the "Got it" button multiple times should not log a new transaction in the 1-1 chat window 
* Follow the solution proposed in https://github.com/status-im/status-react/issues/4760

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.19 (6034)

[comment]: # (Android or iOS.)

* Operating System: Android / Can't confirm about iOS

![screenshot_2018-06-16-11-23-32-456_im status ethereum](https://user-images.githubusercontent.com/5781465/41497334-38c9170c-715c-11e8-8a7e-5e600c44c412.png)

![screenshot_2018-06-16-11-25-14-671_im status ethereum](https://user-images.githubusercontent.com/5781465/41497333-38aaba8c-715c-11e8-9c95-3c5cb05c2477.png)

**Comment by annadanchenko** [comment]
@GeorgiG looks like #4737 that should be already fixed in nightly build. If agree, please close the issue

**Comment by GeorgiG** [comment]
@annadanchenko, yes, please accept my apologies for the duplicate.
