### ISSUE TITLE
Implement desktop chat design 

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#4790]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want desktop chat to look nice so that it pleases my eyes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Chat design should look like depicted in zeplin.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
1-to-1 chat: zpl.io/Vkml10Z
public chat: zpl.io/anmM6oA

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open chat 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
* Operating System: Desktop

**Comment by churik** [comment]
Small fixes in #4839
