### ISSUE TITLE
Slow keyboard after sending 4 messages, 2 lines of text each

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4794]
### Description

*Type*: Bug

*Summary*: When user sent > 4 messages with 2 lines of text (8-9 words), the keyboard starts lagging. The performance is so poor that it's almost impossible to efficiently type new messages. When the chat is left and opened again, all works fine until another 4 messages are sent. 

The issue appears only on Android in all types of chats (1-1, public). I used Samsung Galaxy S8 (native keyboard) to test it. But can be reproduced on another devices as well.

### Reproduction

- Open Status
- Go to 1-1 chat
- Send 4 messages with 8 words each

### Additional Information
* Status version: nightly, 15 June
* Operating System: Android only
* [Slack thread](https://status-im.slack.com/archives/C8KB9DR60/p1529075554000530) about it 
* [TF session](https://app.testfairy.com/projects/4803622-status/builds/8496015/sessions/4394094867/?accessToken=3FxTuruxjCcADvQNik51WYljyUw) with the issue reproduced on Pixel XL

**Comment by mandrigin** [comment]
@lukaszfryc any idea on the regression point?

**Comment by lukaszfryc** [comment]
@mandrigin no. For sure it works in 0.9.19. Maybe @janherich knows more. If not, I can re-test on some old nightlies

**Comment by janherich** [comment]
Apparently this commit introduced the regression and it has something to do with animated view behaving poorly for android - 
https://github.com/status-im/status-react/commit/6a9c8de0e486659ffa75b23c00770e81c7248934

**Comment by lukaszfryc** [comment]
The extreme slowness were fixed by reverting "Input text styling". The keyboard is still lagging but much less.

**Comment by lukaszfryc** [comment]
This issue will be fixed by https://github.com/status-im/status-react/pull/4878. I'll create a separate GHI to fix the lag completely (probably after upgrading RN).
