### ISSUE TITLE
Can see seed phrase in default.realm file from iOS

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4801]
### Description

*Type*: Bug

*Summary*: If open default.realm file (exported with iExplorer tool) on Windows PC with Notepad++ then can see seed phrase. If rename default.realm to default.real.txt on iOS then it's also possible to read phrase on Mac
![phrase](https://user-images.githubusercontent.com/6584810/41526610-04ccdfb2-72e5-11e8-8e6c-07513c4989f7.png)

![88781](https://user-images.githubusercontent.com/6584810/41526615-090221be-72e5-11e8-9099-05bfb56a6be6.jpg)

#### Expected behavior
Can't see see phrase

#### Actual behavior
Can read seed phrase 
### Reproduction

- Open Status
- Create account
- Install iExplorer tool and Notepad++ on Windows PC
- Make a backup of the iPhone on PC
- using iExplorer navigate to Backup/Backup Explorer/App/im.status.ethereum/Documents and export default.realm file to PC
- open default.realm file with Notepad++ (If rename default.realm to default.real.txt on iOS then it's also possible to read phrase on Mac)
- scroll down to check if there is seed phrase visible (note: search will not find it but you can see it if scroll)

Here is file from my backup: 
[default.realm.txt](https://github.com/status-im/status-react/files/2110582/default.realm.txt)

### Additional Information
* Status version: nightly build Jun 17
* Operating System: iOS

**Comment by oskarth** [comment]
Good find. Would be interesting to do a post-mortem of this and figure out where this was introduced, as I believe this was fixed in https://github.com/status-im/status-react/issues/4476? Would help us avoid whatever changes lead to this in the future.

**Comment by mandrigin** [comment]
@oskarth there are a few issues to that:
1) realm should be encrypted and it isn't for some reason. maybe the key is empty for some reason. we need to investigate _that_ and make some mechanics to prevent it in the future (like, crash if the key is empty of all zeroes or something like that).

2) persisting the seed phrase has almost the same security consequences as persisting the private key, so it should be handled in a similar way (probably, with the user's password or Secure Enclave key or something like that).

**Comment by annadanchenko** [comment]
@cammellos here is TestFairy session from iOS device that was used to reproduce the issue: https://app.testfairy.com/projects/4803590-status/builds/8497703/sessions/4394276852/?accessToken=0Ze88QPm0zxD8LL6wCcJLFs7vW8

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8497703/sessions/4394276852/?accessToken=0Ze88QPm0zxD8LL6wCcJLFs7vW8">TestFairy: Status 0.9.20 (6067) @2018</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
fixed in #4810
