### ISSUE TITLE
`BigNumber Error: times() not a number: null` if open 1:1 chat with special content. Can't use this chat 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4803]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For some chats: If open 1:1 chat then error popup `BigNumber Error: times() not a number: null` is shown. If close it then white screen is shown. Same happens if relaunch the app, so user can't open 1:1 chat. Can reproduce 2 out of 3 attempts when 1:1 chat contains send and request commands. See steps for details.

So for particular 1:1 chat error happens always but I'm still looking for exact steps to get such error for other 1:1 chats.

```
00:20 4/Status: 2018-06-18 12:25:54.348 [info][tid:com.facebook.react.JavaScript] PRETTY PRINTED EXCEPTION

***
NAME: "BigNumber Error"
MESSAGE: BigNumber Error: times() not a number: null

This error is located at:
    in message-content-command-request
    in reagent80
    in RCTView
    in reagent73
    in RCTView
    in RCTView
    in RCTView
    in RCTView
    in reagent70
    in message-content
    in RCTView
    in RCTView
    in TouchableHighlight
    in reagent16
    in RCTView
    in reagent69
    in message-row
    in RCTView
    in t
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in t
    in t
    in reagent22
    in messages-view
    in reagent68
    in RCTView
    in n
    in TouchableWithoutFeedback
    in reagent67
    in with-activity-indicator
    in reagent53
    in messages-view-animation
    in reagent44
    in RCTView
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in chat
    in reagent42
    in RCTView
    in main
    in root
    in reagent1
    in RCTView
    in RCTView
    in t

Q@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:25:4683
A@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:25:10216
W@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:25:2580
mul@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:25:14286
crypto__GT_fiat@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:1363308
usd_amount@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:1364011
/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:7962518
/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2319955
wrap_render@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2320612
do_render@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2321794
/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2322347
in_context@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2285164
deref_capture@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2285307
run_in_reaction@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2313640
/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2322288
f@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:42083
o@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:64674
a@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:65053
T@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:68561
y@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:67997
v@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:67834
h@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:67113
c@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:66367
enqueueForceUpdate@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:234:30993
forceUpdate@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:195:1315
run_queue@/var/containers/Bundle/Application/BFE7CE9A-7F8E-4347-9940-36E5B3333A7F/StatusIm.app/main.jsbundle:12:2280856
flush_queues@/var/containers/Bundle/Application/B
```

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can see content of 1:1 chat and send/recieve new messages
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install status on iOS and Android device. Set ropsten network, get test eth from faucet.
- As Android: open test Dapp and request STT
- As iOS device: add Android to contacts and send "ok" text
- As Android: Add iOS to contacts in new 1:1 chat and send "fine" text
- As Android: send request 0.004 ETH
- As iOS: tap on request and send 0.004 ETH
- As Android: send 500 STT to iOS from Wallet
- As Android: send 0.00088888 ETH to iOS from Wallet
- As iOS: send 3 emojis
- As iOS: send request 3 ETH
- As iOS: send 0.0007 ETH
- As Android: send text "ok"
- As iOS: wait for all tx to be confirmed, close app, launch app, open 1:1 chat with Android

TF session from iOS when issue happens: from 00:19 https://app.testfairy.com/projects/4803590-status/builds/8496218/sessions/4394273809/?accessToken=bWbl4fpYxKr/prbLfc7ha5GJxcE

This how 1:1 chat looks on Android side:
![chat1](https://user-images.githubusercontent.com/6584810/41531915-519f6516-72f5-11e8-9024-435e1874e2f2.png)
![chat2](https://user-images.githubusercontent.com/6584810/41531922-56ea125a-72f5-11e8-9a34-70acf147de46.png)

TX history on Android side (green box is all tx with iOS device)
![tx history android](https://user-images.githubusercontent.com/6584810/41531944-652a21a2-72f5-11e8-8fbe-f270a06ac010.png)

TX history on iOS side
![tx history ios](https://user-images.githubusercontent.com/6584810/41531960-6f59544a-72f5-11e8-919f-2b7ee49fc843.jpg)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: can reproduce on PR build https://github.com/status-im/status-react/pull/4786
* Operating System: iOS, didn't try on Android

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8496218/sessions/4394273809/?accessToken=bWbl4fpYxKr/prbLfc7ha5GJxcE">TestFairy: Status 0.9.20 (6061) @2018</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
also can reproduce:
1. send 0 eth from android to ios in 1x1 chat
2. send 0 eth from ios to android in same 1x1 chat

![image](https://user-images.githubusercontent.com/28752642/41536336-ffd485ea-730d-11e8-989a-f6dacac82823.png)

as well as same error with big number - just request something from android to ios

**Comment by dmitryn** [comment]
Will be fixed by https://github.com/status-im/status-react/pull/4796
