### ISSUE TITLE
Blinking camera screen when capturing a profile photo

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4807]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The camera is blinking when trying to capture a new profile photo.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The camera should not be blinking.

#### Actual behavior
[comment]: # (Describe what actually happened.)
It does. See a recording here: https://www.youtube.com/watch?v=90Vi1Ob9IYg

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status
2. Login
3. Navigate to the "Profile" menu
4. Select "Edit"
5. Select the "Edit"  button over the profile photo circle
6. Select "Capture"

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.20, Nightly build "June 18", http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-b40b04-n-fl.apk

[comment]: # (Android or iOS.)
* Operating System: Android 8.1.0 (can't test on iOS)
* Device: Xiaomi Redmi Note 5

#### Logs

https://gist.github.com/GeorgiG/dd4651c936c3585c83d30f65b391990b

<blockquote><img src="https://i.ytimg.com/vi/90Vi1Ob9IYg/maxresdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=90Vi1Ob9IYg">Camera failed</a></strong></div><div> </div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/5781465?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/GeorgiG/dd4651c936c3585c83d30f65b391990b">camera fail</a></strong></div><div>camera fail</div></blockquote>

**Comment by annadanchenko** [comment]
@GeorgiG as I understood, you are using nightly build from June 18 available via http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-b40b04-n-fl.apk
Can you add this version info for this and other issues if so, please? 
format: version number, Nightly build "date value", link to the build

<blockquote></blockquote>

**Comment by GeorgiG** [comment]
@annadanchenko, sure! :)

**Comment by GeorgiG** [comment]
I noticed that the same issue appears sometimes with the QR but not every time on my device.

**Comment by GeorgiG** [comment]
Works fine on 0.9.20 (6070) from the PlayStore.

**Comment by GeorgiG** [comment]
I got the same issue with Status version: 0.9.21, Nightly build "June 20", http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-77cb0c-n-fl.apk

<blockquote></blockquote>
