### ISSUE TITLE
Can't capture a new profile photo

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4808]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to capture a profile photo with my front camera so that my profile will be updated with it.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: It's not possible to update my profile picture while using the front camera of my cell phone.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
To be able to capture and update my profile picture.

#### Actual behavior
[comment]: # (Describe what actually happened.)
It's not possible.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status
2. Login
3. Navigate to the "Profile" menu
4. Select "Edit"
5. Select the "Edit"  button over the profile photo circle
6. Select "Capture"
7. Click on the shutter button 
8. Click the back button

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: This is a newly introduced bug which I was not able to reproduce on 0.9.19 (6034). The target here is to get back to the normal behavior of the application when the profile photo was updated after step 7 from the reproduction steps above.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.20, Nightly build "June 18", http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-b40b04-n-fl.apk

[comment]: # (Android or iOS.)
* Operating System: Android 8.1.0 (can't test on iOS)
* Device: Xiaomi Redmi Note 5

### Logs
https://gist.github.com/GeorgiG/094e375ea8a7208ad8bb2654fba663dd

**Comment by annadanchenko** [comment]
@GeorgiG please, add logcat log. What's Android version?

**Comment by GeorgiG** [comment]
@annadanchenko, I've updated the description with the required information.

**Comment by GeorgiG** [comment]
Works fine on 0.9.20 (6070) from the PlayStore.

**Comment by GeorgiG** [comment]
I got the same issue with Status version: 0.9.21, Nightly build "June 20", http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-77cb0c-n-fl.apk
I believe this is strictly related with https://github.com/status-im/status-react/issues/4807 

<blockquote></blockquote>
