### ISSUE TITLE
Often OOM crashes when browsing Dapps on Android

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#4816]
***Type***: Bug

***Summary***: There are number of Dapps or websites which leads to Out_Of_Memory on not really productive Android devices. For instance on Samsung Galaxy Note 4 - the opensea.io Dapp ends up with OOM when I scroll through the list on first summary page view of Dapp. Surfing through CryptoKitties ends up with OOM on 5-6th summary page (CryptoKitties -> Marketplace -> scroll to pagination and one by one navigate till 7th page)

It depends from Dapp and the content I browse. But any Dapp in our list can lead to OOM if to 'browse it enough': it could be either at some point or OOM or blank (white/black) page instead of Dapp content. 
Also, it's easily reproducible browsing Google Maps.

Opensea.io, as I noticed, - is just one of the heaviest in this sense.

#### Expected behavior
No OOM when I browse opensea.io and I can load more content (via 'Load More' button) as many times as I wish 
#### Actual behavior
OOM followed by app crash when I browse Opensea.io Dapp on Galaxy Note 4, on the 1st-2nd attempt loading more content via  'Load More' button from its summary page screen

### Reproduction

1) Open Status and create  an account
2) Navigate to `Open Dapp` -> `OpenSea` -> `Open`
3) Tap `Explore the sea` button on Dapp screen
4) Scroll down it's summary page till the 'Load More' button
5) Tap 'Load More' button
6) Repeat 4th - 5th items above 3+ times

### Additional Information
* Status version: Nightly 18th of June, Release 0.9.20
* Operating System: Android

#### Logs

TF logs: 
surfing marketplace of CryptoKitties: https://app.testfairy.com/projects/4803622-status/builds/8497869/sessions/4394293116/?accessToken=9OVPrRA5vCM//x9lcysH8RAse70

Load More content in OpenSea: 
https://app.testfairy.com/projects/4803622-status/builds/8497869/sessions/4394292297/?accessToken=8N2ujP33RViDpr9HDwCtNbDRBVE ends up with 

```01:05 E/chromium: [ERROR:texture_manager.cc(3421)] [.RenderWorker-0x99a18e00]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: <- error from previous GL command
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(5678)] Error: 5 for Command kTexImage2D
01:05 D/JavaScriptCore: [ERROR:texture_manager.cc(3421)] [.RenderWorker-0x99a18e00]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: <- error from previous G
01:05 D/JavaScriptCore:  comman
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 D/JavaScriptCore: [ERROR:gles2_cmd_decoder.cc(5678)] Error: 5 for Command kTexImage2
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 D/JavaScriptCore: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
[ERROR:gles2_cmd_decoder.cc(4573)]
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 D/JavaScriptCore:   GLES2DecoderImpl: Trying to make lost context current.
[ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make
01:05 D/JavaScriptCore: lost context current.
[ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
[ERROR:gles2
01:05 D/JavaScriptCore: cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
[ERROR:gles2_cmd_decoder.cc(4573)]   GLES2Decod
01:05 D/JavaScriptCore: rImpl: Trying to make lost context current.
[ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context
01:05 D/JavaScriptCore: current
01:05 E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
01:05 D/JavaScriptCore: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current
01:07 D/ViewRootImpl: ViewPostImeInputStage processPointer 0```


<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8497869/sessions/4394293116/?accessToken=9OVPrRA5vCM//x9lcysH8RAse70">TestFairy: Status 0.9.20 (6069) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8497869/sessions/4394292297/?accessToken=8N2ujP33RViDpr9HDwCtNbDRBVE">TestFairy: Status 0.9.20 (6069) @2018</a></strong></div></blockquote>

**Comment by Serhy** [comment]
https://github.com/status-im/status-react/issues/4722 - is similar (or even the same by its nature) 
issue

**Comment by lukaszfryc** [comment]
I can also reproduce `GL_OUT_OF_MEMORY` that leads to rendering issues while scrolling "tweets" in Peepeth. I test on a $500 device (Galaxy S8, Android 7.1) where the experience should be really smooth. But instead after couple of scrolls I see: 

<img src="https://user-images.githubusercontent.com/7532782/42754993-f06f3ede-88f6-11e8-8b1d-d3726bf58e7f.png" width="200">

Steps:
- Open Status on Samsung Galaxy S8 or slower Android device  
- Open Peepeth dapp from dapp list
- Click "Just want to browse? Click here" in Peepeth to see "tweets"
- Scroll to the bottom couple of times until you see "black boxes" (rendering issues) on the screen 

Full logs:
```
07-16 02:48:44.935 29523-30188/? E/chromium: [ERROR:texture_manager.cc(3421)] [.RenderWorker-0x6657bd00]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: <- error from previous GL command
    [ERROR:gles2_cmd_decoder.cc(5678)] Error: 5 for Command kTexImage2D
07-16 02:48:44.935 29523-30053/? D/JavaScriptCore: [ERROR:texture_manager.cc(3421)] [.RenderWorker-0x6657bd00]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: <- error from previous G
07-16 02:48:44.935 29523-30188/? E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
07-16 02:48:44.935 29523-30053/? D/JavaScriptCore:  command
    [ERROR:gles2_cmd_decoder.cc(5678)] Error: 5 for Command kTexImage2D
    [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2Decoder
    mpl: Trying to make lost context current
07-16 02:48:45.013 3752-3968/? D/InputReader: Input event(5): value=1 when=684008359761000
    Input event(5): value=1 when=684008359761000
07-16 02:48:45.013 3752-3968/? I/InputReader: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.15585 ] when=684008359761000
07-16 02:48:45.014 3752-3967/? I/InputDispatcher: Delivering touch to (4158): action: 0x4, toolType: 1
    Delivering touch to (29523): action: 0x0, toolType: 1
07-16 02:48:45.014 29523-29523/? D/ViewRootImpl@2b0fe82[MainActivity]: ViewPostImeInputStage processPointer 0
07-16 02:48:45.062 29523-30188/? E/chromium: [ERROR:gles2_cmd_decoder.cc(8213)] [.RenderWorker-0xbf55a000.GpuRasterization]GL ERROR :GL_OUT_OF_MEMORY : glFramebufferTexture2DMultisample: <- error from previous GL command
07-16 02:48:45.062 29523-30053/? D/JavaScriptCore: [ERROR:gles2_cmd_decoder.cc(8213)] [.RenderWorker-0xbf55a000.GpuRasterization]GL ERROR :GL_OUT_OF_MEMORY : glFramebufferTextur
    2DMultisample: <- error from previous GL comman
07-16 02:48:45.062 29523-30188/? E/chromium: [ERROR:gles2_cmd_decoder.cc(5678)] Error: 5 for Command kFramebufferTexture2DMultisampleEXT
07-16 02:48:45.062 29523-30053/? D/JavaScriptCore: [ERROR:gles2_cmd_decoder.cc(5678)] Error: 5 for Command kFramebufferTexture2DMultisampleEX
07-16 02:48:45.062 29523-30188/? E/chromium: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current.
07-16 02:48:45.062 29523-30053/? D/JavaScriptCore: [ERROR:gles2_cmd_decoder.cc(4573)]   GLES2DecoderImpl: Trying to make lost context current
07-16 02:48:45.098 29523-30444/? I/System.out: pool-125-thread-1 calls detatch()
```

Note that I could not reproduce it on Chrome or native os browser. It also worked fine on iPhone 8.

**Comment by lukaszfryc** [comment]
There are some reports on Instabug about this issue. Would be great if we could at least understand how to improve it.

**Comment by Serhy** [comment]
SuperRare Dapp (superrare.co) is the example that crashes Status app very soon after I start scrolling it's marketplace. 
It was noticed that images there, downloaded from ipfs, can be up to 25MB which might be a major reason of bottleneck at some place forcing app to give up in data processing.
