### ISSUE TITLE
Crash while typing chinese characters in chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4818]
### Description

*Type*: Bug

*Summary*: While in a chat, the app crashes when user switch from english keyboard to chinese and sends couple of chinese messages. It seems like it happens only on iOS. I could reproduce it on iPhone 6, 11.2.6 on "Chinese (Traditional) - Zhuyin" keyboard but not on iPhone 8, 11.3.2. There are also 3 Instabug reports related to not being able to user chinese or japanese keyboards in chats on iOS.

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {18446744073709551615, 0} out of bounds; string length 8'
```

- [TestFairy crash report](https://app.testfairy.com/projects/4803590-status/builds/8498863/sessions/4394329414/?accessToken=gxjcwwxu-wek4AirqLXN5Tm03YA)

### Reproduction

- Set "Chinese (Traditional) - Zhuyin" in iOS system settings 
- Open Status
- Open a chat
- Switch to english keyboard
- Send couple of messages
- Switch to "Chinese (Traditional) - Zhuyin" keyboard
- Send few more messages
-> Crash

### Additional Information
* Status version: 0.9.20
* **Works in 0.9.19**
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@mandrigin any update on that? 

Btw, this issue maybe related https://github.com/status-im/status-react/issues/4829

**Comment by mandrigin** [comment]
Can't reproduce on this PR: https://github.com/status-im/status-react/pull/4837
But I don't have 11.2, I only have 11.0 and 11.4, works on both.
