### ISSUE TITLE
Update react-native to 0.56

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#4819]
Update react-native version to 0.56

With recent upgrade to `0.55` RN release, we introduced multiple problems, one is perf regression related to chat input element (#4794) and it's probably causing keyboard crash issue (#4818) as well.
We hope that upgrading to newest RN release will solve those things.

To check:
- #4794 is no more
- no regressions
- no new perf regressions

Bounty might be increased if it turns out that the update required more changes than expected.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1700.00
Contract address: [0xee98babf38e771eb5e5136fa950c4a96c9383ced](https://etherscan.io/address/0xee98babf38e771eb5e5136fa950c4a96c9383ced)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: yenda
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by oskarth** [comment]
@andytudhope can we bump this up to a medium or large to reflect urgency?

**Comment by pablanopete** [comment]
@oskarth ill change it -- More SNT has been sent to reflect size of bounty / priority to contract address as well.

**Comment by oskarth** [comment]
Thanks! I realized after that 56 is still RC and might not solve those perf issues. But it also seems like quite a lot of breaking changes so still worthwhile to have increased bounty.

**Comment by debragail** [comment]
willing to work on this is .56 still the target @oskarth ?

**Comment by pablanopete** [comment]
Looks like this was finished by @yenda -- @andytudhope to revoke / payout (whichever works)
