### ISSUE TITLE
Unread message counter is shown but all messages were read

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4820]
### Description

*Type*: Bug

*Summary*: There are Instabug reports about the unread message counter that does not disappear even if all messages were read. Users have also tried to clear chats and restart the app but the counter was still there. 

I tried to reproduce it on my side with no luck. Things I tried on iOS (11.3.1) and Android (7.0) devices:
1. Recover account with unread messages
2. Upgrade from 0.9.19 to 0.9.20 with unread messages

#### Expected behavior
Unread message counter appears only if there are new messages that user haven't seen it. 

#### Actual behavior
For some reason, the unread message counter does not disappear after all messages were read.

### Reproduction

We don't know how to reproduce it yet.

### Additional Information
* Status version: 0.9.20
* Operating System: Android, iOS
* Recent issues that maybe related: https://github.com/status-im/status-react/issues/4542, https://github.com/status-im/status-react/issues/4726
* Instabug reports: [Android](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/215), [iOS](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/221)

**Comment by lukaszfryc** [comment]
The issue is still present. I just reproduced it on [0.9.21 RC](https://jenkins.status.im/job/status-react/job/public-beta-1-testfairy/14/) (release candidate) `25c417`

**Comment by janherich** [comment]
@lukaszfryc Any special steps how to reproduce the issue ?

**Comment by lukaszfryc** [comment]
Yes, I've just found that I can reproduce it every time when I upgrade from 0.9.20 to 0.9.21. Steps:

1. Install 0.9.20 and add few public channels. Do not read them all so you could have some unread messages.
2. Upgrade to 0.9.21
3. Open the public channels. Scroll to read the messages, the counter is still there. Click options menu and click "Clear all", the chat is cleared but the counter is still there
4. Kill the app and open it again. **Now it works, the counter is not shown anymore.** 

It looks like it's only related to upgrading. It does not happen on a fresh install.

**Comment by lukaszfryc** [comment]
cc @janherich

**Comment by chadyj** [comment]
This comes and goes for me.

**Comment by lukaszfryc** [comment]
Many people on Instabug complain about this issue. Maybe we could prioritize it? 

@janherich have you been able to reproduce it?

**Comment by janherich** [comment]
@lukaszfryc Not yet, but of course I can focus on that if it's priority

**Comment by lukaszfryc** [comment]
No worries. We can prioritize it next week if you have other things right now.
