### ISSUE TITLE
Text input is broken for Korean, Chinese, Japanese characters

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4829]
### Description

*Type*: Bug

*Summary*: With recent [react-native upgrade](https://github.com/status-im/status-react/commit/a2762eb19e45810184671b6c47f11faff0270124#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) we introduced a bug with [Chinese characters not being displayed correctly in chat input](https://github.com/facebook/react-native/issues/19339). The bug occurs only on iOS. 

#### Expected behavior
Users can use Korean, Chinese, Japanese keyboards in Status

#### Actual behavior
Users can't use Korean, Chinese, Japanese keyboards in Status due to https://github.com/facebook/react-native/issues/19339

### Reproduction

- Switch to a Chinese keyboard on iOS
- Open Status
- Send messages in Chinese in a chat

### Additional Information
* Status version: 0.9.20
* Worked in 0.9.19
* Operating System: iOS

**Comment by mandrigin** [comment]
Tried to fix upstream too: https://github.com/facebook/react-native/pull/19809

**Comment by NamITUTC** [comment]
change onChangeText(text=>) =>onKeyPress(text=>)
