### ISSUE TITLE
Crash when scrolling a chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4831]
### Description

*Type*: Bug

*Summary*: @rachelhamlin reported a crash after scrolling through public chat for several minutes:
_I opened a link, then closed it and reopened public chat and started quickly scrolling to get back to where I was._ 

The crash happened on iPhone 6+, iOS 11.2.6. I could not reproduce it on my iPhone 6, iOS 11.2.3. The crash maybe related to out of memory exception. Please investigate the logs below: 

- [TF crash log](https://app.testfairy.com/projects/4803590-status/builds/8497703/sessions/4394331529/?accessToken=UafBcW4X5j91BAeu9bJVVi6Kz9Q) 
- [Instabug report](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/223)

### Reproduction

No steps to reproduce.

### Additional Information
* Status version: 0.9.20
* Operating System: iOS

**Comment by rachelhamlin** [comment]
Thanks Lukasz. Time to get a new phone. 😅

**Comment by lukaszfryc** [comment]
We have not seen it anymore.
