### ISSUE TITLE
Error BigNumber Error: div() not a number: null

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4832]
### Description

*Type*: Bug

*Summary*: Error `BigNumber Error: div() not a number (null)`

#### Expected behavior
Can get back to the app when viewing txn history details

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/41599671-8facfd36-73dc-11e8-8f43-c52de669d6e4.png)

### Reproduction

- Open Status
- Recover account
- Open txn from history
- Copy txn hash
- Tab Back
- Repeat several times
- Stay on transactions sreen

### TF
https://app.testfairy.com/projects/4803622-status/builds/8498824/sessions/4394349349/?accessToken=ztKbNqajr02MB4apm8wk9hpAMZc

`This error is located at:
        in t
        in RCTView
        in t
        in RCTView
        in RCTScrollView
        in AndroidSwipeRefreshLayout
        in RefreshControl
        in ScrollView
        in t
        in t
        in t
        in reagent55
        in RCTView
        in history-list
        in reagent59
        in RCTView
        in transactions
        in reagent57
        in RCTView
        in main
        in root
        in reagent1
        in RCTView
        in RCTView
        in t, stack`

**Comment by lukaszfryc** [comment]
Looks like what we had in https://github.com/status-im/status-react/issues/4639
