### ISSUE TITLE
"Wrong password" validation message partially overlaps "Enter password" placeholder in sign transaction screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4835]
### Description

*Type*: Bug

*Summary*: wrong password validation message overlaps "Enter password" placeholder when sign transaction (or sign message for DApp)

#### Expected behavior
no overlapping

#### Actual behavior
![123](https://user-images.githubusercontent.com/4557972/41604498-14995656-73e8-11e8-8a0d-a61a4371d094.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log in
- Open wallet 
- Tap on send transaction, fill Recipient and amount with valid data
- Tap on Sign transaction
- Paste wrong password
- Erase password

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build [19/06/18](https://i.diawi.com/BbxVyx)
* Operating System: iOS 11, IPhone 7

**Comment by yevh-berdnyk** [comment]
Looks like the issue not only a visual defect. It's not possible to paste a password from clipboard after entering wrong password.

Steps:

- Enter or paste wrong password
- Click Sign transaction button
- Erase password
- Long tap on the enter password input 

After that paste pop up is not shown

**Comment by churik** [comment]
@yevh-berdnyk is it not this one? https://github.com/status-im/status-react/issues/4952

**Comment by yevh-berdnyk** [comment]
@churik I think no because it's possible to enter new password if not hiding a keyboard but it's not possible to paste it anyway.
But they are relative for sure
