### ISSUE TITLE
UI/UX fixes for issue #4791 (Chat design)

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4839]
This is a list of UX/UI improvements for issue #4791 

**Message area**
- [ ] ~~“Sent” label is missing from sent message. **(High prio)**~~ (added as separate feature #5018 )
- [ ] Space between 2+ messages from same sender should be 8px, now they are random paddings (11px, 16px, 8px). (Low prio)
- [ ] Space between last message and bottom of message area should be 24px (now is 63px) - (Low prio)
- [ ] Review color of timestamp (time in message), the contrast is too low now and is hard to read. (Low prio)
- [ ] Review color of date (the label in the middle of the area: “Today” "Sep 3"). (Low prio)
- [ ] Message timestamp is not centrally aligned to the message when it is just 1 line. (Low prio)
- [ ] Max width of message bubble for long messages is 340px (is 335px now). (Low prio)

**1:1 CHAT SPECIFICS**
- [ ] Empty state is missing when talking to somebody for the first time zpl.io/aRqj4dv (Low prio)

**PUBLIC CHAT SPECIFICS**
- [ ] If same user writes 2+ messages in a row, profile img shouldn’t repeat, it should only be in the latest message of the group. (Mid prio)
- [ ] Empty state is missing when joining a public chat for the first time zpl.io/bAv8OjB  (Low prio)

**Comment by churik** [comment]
@EugeOrtiz 
afaik regarding this particular PR only message area is affected.
Chat list/contacts are the part of PR #4752. 
Headers are in #4693.

So I believe there should be left only issues from "Message area" section.
@vkjr can you please highlight what exactly areas were implemented in #4791? (i.e., message area, messages status (like "Sent/not sent"), text input area etc?

**Comment by vkjr** [comment]
@churik, @EugeOrtiz, in current PR only UI for message area was improved.
List of contacts and text input left almost untouched.

In general, I would split this issue into few smaller ones, I think that would be easier to implement and test.

**Comment by EugeOrtiz** [comment]
@churik @vkjr Done! Will move the rest to specific issues.

**Comment by EugeOrtiz** [comment]
I'm moving this back to non-high-priority column since the high prio item in the list was already covered.

**Comment by churik** [comment]
Doesn't make sense in terms of https://github.com/status-im/status-react/pull/7551
