### ISSUE TITLE
Chat name, avatar and last message are not visible when chat is swiped to the right

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4843]
### Description

*Type*: Bug

*Summary*: When chat is swiped to the left and then back to the right it's squeezed. The chat name, avatar, last message, timestamp are not visible. Everything goes back to normal when user visits another screen and goes back to chat list. For instance opens the chat and goes back.  

<img src="https://user-images.githubusercontent.com/7532782/41643699-29b7ed5c-746c-11e8-83cd-7c38ffe43c42.png" width="200">

#### Expected behavior
When chat is swiped to the left and then back to the right it does not have any UI glitches.

#### Actual behavior
When chat is swiped to the left and then back to the right it's squeezed.

### Reproduction

- Open Status
- Have a chat in Home
- Swipe it to the left to see the delete button
- Swipe it to the right

### Additional Information
* Status version: 0.9.20
* Works in: 0.9.19
* Operating System: iOS

**Comment by lukaszfryc** [comment]
I don't consider it Beta blocker. cc @chadyj @annadanchenko

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe260a013d0f884f5af43291910664f334382f739f378958bb7fe15bc1be2347e](https://etherscan.io/tx/0xe260a013d0f884f5af43291910664f334382f739f378958bb7fe15bc1be2347e)

**Comment by andytudhope** [comment]
I can't reproduce this, is it still relevant @lukaszfryc?

**Comment by lukaszfryc** [comment]
I can't reproduce it either.
