### ISSUE TITLE
Username emojis are not fully visible in home and chat screens

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4846]
### Description

*Type*: Bug

*Summary*: Only on iOS, emojis in user name are cutted in following places:

- Home screen
<img src="https://user-images.githubusercontent.com/7532782/41648899-770de116-747a-11e8-9feb-0a16a21023c7.png" width="200">

- Chat screen
<img src="https://user-images.githubusercontent.com/7532782/41648935-8b290964-747a-11e8-9d69-b85be5102d94.png" width="200">

### Reproduction

- Open Status on iOS
- Go to Profile, edit username and set emoji there

### Additional Information
* Status version: 0.9.20
* Operating System: iOS
* Android works fine

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 0.00
Contract address: [0xcca814b81b704b6997a162634eb8406017b2059f](https://etherscan.io/address/0xcca814b81b704b6997a162634eb8406017b2059f)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: 751895405
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by muhammadbilal1999** [comment]
working

**Comment by pablanopete** [comment]
To be paid out once #5560 work is completed -- possibly with an extra bounty incentive for the work gone on here. Once rebase / merged.

**Comment by pablanopete** [comment]
To be revoked @andytudhope
