### ISSUE TITLE
Remove currency indicator from wallet main screen (top left) and replace it with [~] sign

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4848]
### Description

*Type*: Feature

*Summary*: Since we have currency indicator in the assets section, we dont need to have both currency and currency symbol shown at the top ( for ex $ and USD)

#### Expected behavior

- Currency symbol is removed from the top left so only USD is shown (if USD is selected as main currency)
- Currency symbol is replaced with `~` sign

![image](https://user-images.githubusercontent.com/28752642/41649444-3f1382e8-7484-11e8-9630-a28562a14ee9.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/41649474-537abb02-7484-11e8-98bb-f517ce13a70c.png)

### Reproduction
- Open Status
- Tap Wallet

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0.0 ETH
Contract address: [0xe7ce6b3a3f5550eaa4d56a53b128c4bb6eb5c85a](https://etherscan.io/address/0xe7ce6b3a3f5550eaa4d56a53b128c4bb6eb5c85a)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: gnl
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
