### ISSUE TITLE
Replace "passphrase/seed phrase" with "recovery phrase" in texts

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4854]
### User Story

As a user, I want to have a meaningful name for a phrase that I use for recovering my account.

### Description

*Type*: Bug

*Summary*: 

Replace "passphrase/seed phrase" with "recovery phrase" in the following screens:

![recovery](https://user-images.githubusercontent.com/6559881/41660909-b12273bc-749d-11e8-9b60-731f0a703a45.jpg)

<img width="404" alt="screenshot 2018-06-20 15 56 24" src="https://user-images.githubusercontent.com/6559881/41662935-85529078-74a2-11e8-9da0-4f8a7aa4550e.png">

Update recovery phrase input with this text: `Enter the 12 words, separated by spaces`
<img width="350" alt="screenshot 2018-06-29 15 34 24" src="https://user-images.githubusercontent.com/6559881/42095222-45d4f7f8-7bb2-11e8-8962-d505796035f6.png">

### Reproduction

1. Recover existing account
- Open Status
- Tap Add existing account
- Check filed names on `Sign in to another account screen`

2. Profile
- Open Status
- Create account
- Go to the `Profile` screen

3. Import existing wallet with funds
- Have a wallet outside of Status with funds (e.g. Metamask)
- Open Status
- Tap Add existing account
- Got to the `Wallet` screen

### Additional Information
* Status version: nightly build June 20
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
@chadyj @hesterbruikman @jpbowen wdyt about adding some extra explanation on Recover account screen to explain that contacts, chat content, username/picture will not be restored?

**Comment by denis-sharypin** [comment]
Nope, it should be renamed everywhere to `Recovery phrase`. We reached this agreement within design team

**Comment by annadanchenko** [comment]
@denis-sharypin please, capture such agreements in GH issues
Now there is Seed Phrase in Profile and Passphrase in Recover account

**Comment by denis-sharypin** [comment]
Extra explanation regarding contacts etc would not work here, because of one of uses cases: recover a metamask account. And this explanation would not fit this usecase. I know that @hesterbruikman is working on the redesigning this whole flow

**Comment by annadanchenko** [comment]
so, what's exact issue with recovering metamask account?

**Comment by denis-sharypin** [comment]
I mean if you are recovering not a Status account this extra explanation is confusing even more

**Comment by annadanchenko** [comment]
not sure it's true. if you recover from metamask or other place then you by default had no chats, contacts etc. Such case can be also captured in explanation tbh. Like: if you were using Status app before then....

**Comment by denis-sharypin** [comment]
All usescases would be covered in the new flow. Let's wait for them

**Comment by annadanchenko** [comment]
I've created https://github.com/status-im/status-react/issues/4856 to capture work about explanation as separate issue. @denis-sharypin please feel free to close this issue if there is "rename to Recovery phrase" issue

**Comment by denis-sharypin** [comment]
There is no such issue, I will update this issue then

**Comment by hesterbruikman** [comment]
Really happy this has been updated. It's a lot more explanatory and in line with what other apps are doing. An alternative we may consider in the future is _'Access phrase'_. Now that wallets are more interoperable I do believe this is more accurate and can be used in both accessing a previously created Status account and an existing compatible wallet. 

_'Access'_ implies that the wallet remains and you can access it from other places (Metamask, Myetherwallet, etc.). Whereas _'Recovery'_ might create the impression that you recover an account in one unique place.

cc @obi2020
