### ISSUE TITLE
When outgoing transaction message ("/sent") is opened, the transaction details shows outdated info

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4857]
### Description

*Type*: Bug

*Summary*: If I click on a transaction that I've sent, the Transaction Details screen shows initial state of the transaction. It's not getting refreshed but I assume it should be. The only way to refresh it is by going to Transaction History and opening the transaction there.

<img src="https://user-images.githubusercontent.com/7532782/41653495-8e6ba850-7486-11e8-81db-c2b3a181adb2.png" width="200">

<img src="https://user-images.githubusercontent.com/7532782/41653843-a0ce6874-7487-11e8-9c7b-7c6899ea33e2.png" width="200">

#### Expected behavior
When transaction message in chat is clicked, the transaction details shows most up to date info.

#### Actual behavior
The transaction details shows old state of transaction.

### Reproduction

- Open Status on 2 devices
- Create 1-1 chat beteen devices
- Device A: send tokens ("/send") to device B
- Wait for some time until transaction is confirmed or at least has some confirmations
- Device A: click on the transaction message
-> Device A: Transaction Details shows but data is not up to date.

### Additional Information
* Status version: 0.9.20
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
It's related to https://github.com/status-im/status-react/issues/4851 and https://github.com/status-im/status-react/issues/4853

**Comment by dmitryn** [comment]
I think it can be closed after https://github.com/status-im/status-react/pull/5221 was merged that should fix this issue.
