### ISSUE TITLE
Apply design for text input area in chat

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4862]
This is a list of visual and experience bugs for the text input area in chat:

- [ ] **Input area doesn’t grow with long messages zpl.io/brN1Xre. (High prio)**
<img width="691" alt="captura de pantalla 2018-09-17 a la s 10 16 38 a m" src="https://user-images.githubusercontent.com/37297779/45612283-d51fea00-ba62-11e8-87e2-3113476e7ced.png">
See how input fields grow >> zpl.io/brN1Xre (Zeplin)

- [ ] Send button enabled styles are missing (blue) 
<img width="696" alt="captura de pantalla 2018-09-17 a la s 10 18 20 a m" src="https://user-images.githubusercontent.com/37297779/45612559-a1918f80-ba63-11e8-8073-f73c4fe0040a.png">

- [ ] Review Send button disabled styles (grey) 
- [ ] Focus should be on input field when joining a new chat 
- [ ] Input area height should be 68px 
- [ ] Review color of "Type a message” label 
- [ ] "Type a message” label, send button and cursor are not aligned at the middle to the input box
<img width="694" alt="captura de pantalla 2018-09-17 a la s 10 20 05 a m" src="https://user-images.githubusercontent.com/37297779/45612548-8d4d9280-ba63-11e8-93e8-c5e449669716.png">

Designs in Zeplin >> zpl.io/aXGDvmE

**Comment by chadyj** [comment]
<img width="683" alt="screen shot 2018-09-05 at 11 37 11 am 1" src="https://user-images.githubusercontent.com/116099/45353181-7f5ac600-b5ba-11e8-8792-cb8f251c7713.png">
The text box not growing with long text is especially annoying!
