### ISSUE TITLE
New header for 1:1 chat is missing

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4863]
As a user, I want to see who I'm talking too at the top of the message area:

![image](https://user-images.githubusercontent.com/37297779/41658170-facaa638-746b-11e8-923f-d18fe0e49287.png)

Expected behavior: When I'm talking to a person, we need to show the right 1:1 chat header.

[Designs in Zeplin](zpl.io/V4J4NX4)
[Designs in Zeplin](zpl.io/am6gW4v)

**Comment by churik** [comment]
Should be fixed in #4693
