### ISSUE TITLE
New header for public chat is missing

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4864]
As a user, I want to see in which public chat I'm in by looking at the top of the message area:

![image](https://user-images.githubusercontent.com/37297779/41658291-507639bc-746c-11e8-8245-c8e15da6273d.png)

Expected behavior: When I'm in a specific public chat, we need to show the right public chat header.

[Designs in Zeplin](zpl.io/2vlrMQe)

**Comment by churik** [comment]
Should be fixed in #4693
