### ISSUE TITLE
Pending state is shown for transaction in 1:1 chat for sender even if tx confirmed more than 100 times in 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4865]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: On sender side transaction message shows "Pending" for transaction sent in 1:1 chat 20 minutes ago. Transaction has more than 100 confirmations.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If transaction is confirmed then send transaction message in 1:1 chat shows state "Confirmed" for both sender and receiver. 
#### Actual behavior
[comment]: # (Describe what actually happened.)
On sender side send transaction message shows "Pending" state
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open 1:1 chat on iOs and Android devices
- as iOS device: send to Android 0.0001 ETH
- wait ~5 minutes and do not navigate anywhere else on both devices, so 1:1 chats are open. In my case, on Android side transaction will be shown as Confirmed soon. 
- as soon as tx is Confirmed on Android: do not touch iOS and do not do anything else there. On Android you can navigate to Wallet -> transaction history to make sure tx has enough confirmations. As soon as there are more than 12 - look in 1:1 chat on iOS.

See from 2:22:12 start and send transaction message test. https://app.testfairy.com/projects/4803590-status/builds/8500343/sessions/4394438169/?accessToken=ydDyz4laS11IuKUE/CP/K50FKNA

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build June 20
[comment]: # (Android or iOS.)
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8500343/sessions/4394438169/?accessToken=ydDyz4laS11IuKUE/CP/K50FKNA">TestFairy: Status 0.9.21 (6078) @2018</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@annadanchenko I could reproduce it as well. Btw, on my side, the transaction was marked as confirmed when I received a "/send" message from another device. When that message appeared, the outgoing transaction was confirmed.
