### ISSUE TITLE
Message spinner did not disappear when the message was sent

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4868]
### Description

*Type*: Bug

*Summary*: I have noticed few times that a message spinner did not disappear even though the message was sent. It kept spinning forever in the chat (even after restarting the app):
 
<img src="https://user-images.githubusercontent.com/7532782/41666710-6bad3412-74ab-11e8-99bf-c3634f6ec17d.png" width="200">

It happened for me (but can't be reproduced) while:
1. Sending lot of messages very fast, https://github.com/status-im/status-react/pull/4537#issuecomment-397674624
2. Sending transaction ("/send") and killing the app before pressing "Got it". When I went back to the chat the spinner was still there: https://github.com/status-im/status-react/pull/4830#issuecomment-398784021

Maybe there is some race condition?

#### Expected behavior
Message spinner should disappear after message is sent.

#### Actual behavior
Message spinner was shown indefinitely.

### Reproduction

No exact steps to reproduce. See description above for cases when it happened for me.

### Additional Information
* Status version: 0.9.20
* Operating System: Android, iOS

**Comment by flexsurfer** [comment]
reproduced to me when i added a contact with the universal link and sent messages

**Comment by asemiankevich** [comment]
I saw this issue when sending the very first message to a contact i just added via scan qr code functionality

![image](https://user-images.githubusercontent.com/28752642/48894974-0ba82580-ee55-11e8-9e92-3324b3ea3c87.png)

**Comment by SlizkovaGanna** [comment]
I've faced the same issue with group chats, it's reproduced every time.
Will re-check it after https://github.com/status-im/status-react/pull/6857 is merged.

**Steps to reproduce:**
1. Create a group chat on 1 device and send a message
2. On the 2nd device, as a user added to the same group chat, reply to that message 
3. On both devices, check how your sent messages are displayed
**Current result:** Sender sees a message as 'being sent' (infinite spinner), when in reality it's already received.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/43638377/48957242-19969d00-ef60-11e8-8f9c-4ecc1e1b7167.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/43638377/48957259-2adfa980-ef60-11e8-85bc-32d1255f4d38.png">

**Comment by lukaszfryc** [comment]
I will try to reproduce it again.

**Comment by lukaszfryc** [comment]
Still happens for group chats. Will be fixed in #6932
