### ISSUE TITLE
UI/UX fixes for bottom navigation bar 

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4875]
**List of UX/UI fixes for bottom navigation:**

- [ ] Box height should be 68px
<img width="395" alt="captura de pantalla 2018-07-12 a la s 12 08 18 p m" src="https://user-images.githubusercontent.com/37297779/42642036-4d0ade24-85cc-11e8-8ec0-5d8bd78b60c0.png">

- [ ] Font-size should be 12px
- [ ] Distance between icons and labels should be 4px
- [ ] "Home" icon when tab is selected is not the right one. See zpl.io/anmM6oA

App:
<img width="85" alt="captura de pantalla 2018-07-12 a la s 12 04 05 p m" src="https://user-images.githubusercontent.com/37297779/42641795-bcbf8856-85cb-11e8-8703-f184732990f8.png">

Design:
<img width="66" alt="captura de pantalla 2018-07-12 a la s 12 04 37 p m" src="https://user-images.githubusercontent.com/37297779/42641825-cd6437ec-85cb-11e8-9064-c294f8cfe170.png">

- [ ] "Profile" icon when tab is selected is not the right one. See zpl.io/25qZqB3

App:
<img width="80" alt="captura de pantalla 2018-07-12 a la s 12 06 37 p m" src="https://user-images.githubusercontent.com/37297779/42641916-0e2acfb6-85cc-11e8-9c2a-17eb21fb5e74.png">

Design:
<img width="84" alt="captura de pantalla 2018-07-12 a la s 12 07 07 p m" src="https://user-images.githubusercontent.com/37297779/42641949-21c520da-85cc-11e8-85c6-70cf57803fd4.png">

- [ ] Review distance between 2 options (Home/Profile)
<img width="343" alt="captura de pantalla 2018-07-12 a la s 12 07 39 p m" src="https://user-images.githubusercontent.com/37297779/42641985-35d64c48-85cc-11e8-8e65-214ae1e49128.png">

- [ ] Grey labels should be #6e777e

**Comment by EugeOrtiz** [comment]
@churik I'll restore the previous title since bottom nav is already implemented and this list are just fixes  (not a screen per se).

**Comment by churik** [comment]
@EugeOrtiz Ok, thanks

**Comment by churik** [comment]
Doesn't make sense in terms of #7551
