### ISSUE TITLE
Error: Doesn't support name and white screen if open Wallet 1st time after opening transaction screen from Dapp

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4876]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: `Error: Doesn't support name` is shown if user opens Wallet for the first time. If close error message then white screen is shown, so user needs to close app and launch again. If open Wallet after app re-launch then it works fine and shows Wallet screen.

Such error happens if user opened some Send Transaction screen from any DApp (e.g use Sign feature in CryptoKitties) prior to opening Wallet. If user does not interact with Dapp then Wallet can be opened fine for the first time.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No error shown, Wallet screen is opened
#### Actual behavior
[comment]: # (Describe what actually happened.)
If open wallet then error is shown:
```
00:57 E/ReactNativeJS: Error: Doesn't support name: 
00:57 E/ReactNativeJS: 
00:57 E/ReactNativeJS: This error is located at:
00:57 E/ReactNativeJS:     in asset-selector
00:57 E/ReactNativeJS:     in reagent79
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTScrollView
00:57 E/ReactNativeJS:     in ScrollView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in reagent11
00:57 E/ReactNativeJS:     in reagent56
00:57 E/ReactNativeJS:     in reagent76
00:57 E/ReactNativeJS:     in send-transaction
00:57 E/ReactNativeJS:     in reagent75
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in main
00:57 E/ReactNativeJS:     in root
00:57 E/ReactNativeJS:     in reagent1
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in t
```
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
from 00:22 https://app.testfairy.com/projects/4803622-status/builds/8501358/sessions/4394474390/?accessToken=/pX7AYEvRo5MHjOTpineB7jZWSU
- Open Status and create account
- if on mainnet: Open CryptoKitties and Sign in (so there is Sign transaction done). if on ropsten: use Test Dapp -> Transactions - Sign and sign transaction
- open Wallet for the first time, confirm that you've wrote down 3 words and proceed to Wallet screen

Note: on the morning nightly build these issue can't be reproduced but can be reproduced on new nightly triggered in the evening June 20. Merges that were included in the new nightly https://jenkins.status.im/job/status-react/job/nightly/459/changes with this issue:
1. disable gradle daemon to make builds more stable (commit: 499f5b0) (details)
2. [#4829] Add a patch that fixes complex input on iOS in RN 0.55.x. (commit: caba84e) (details)
3. feature #3233 #4095 and #3234 - send and request tokens in chat and (commit: 32bbf4e) (details)
4. [#4821] send /send command before after sending transaction (befor (commit: 6028cca) (details)
5.  [#3642]: High quality welcome image (commit: 41dcb2e) (details)
6.  Add 6 new languages as public channels in the localized language. Closes (commit: 2270146) (details)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build https://jenkins.status.im/job/status-react/job/nightly/459/
[comment]: # (Android or iOS.)
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8501358/sessions/4394474390/?accessToken=/pX7AYEvRo5MHjOTpineB7jZWSU">TestFairy: Status 0.9.21 (6080) @2018</a></strong></div></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by asemiankevich** [comment]
@goranjovic it is https://github.com/status-im/status-react/pull/4796 :( please take a look tomorrow (
