### ISSUE TITLE
Chats/Discover/Contacts tabs menu animation iOS

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#488]
![an](https://cloud.githubusercontent.com/assets/2364994/20529397/a3c618de-b0d8-11e6-9022-e4fd047462bf.gif)

**Comment by alwx** [comment]
It became broken in this commit: https://github.com/status-im/status-react/commit/e84f8c64b53c20d96c9b3511a084614af81ccfa3
Going to fix it now.

Just a note for me and other developers: we should spend more time checking PRs on *both* platforms to avoid these situations.
