### ISSUE TITLE
Make installation/uninstallation process smooth

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4881]
### User Story

As a user, I want to have an obvious and simple way how to install or uninstall application

### Description

*Type*: Feature

*Summary*: 
### Installation notes:
- build is stored in `.zip` format (expected in `.dmg` for Mac OSx), so you need special software to unzip it.
- when you launch StatusIm for the first time, it produces a lot of files in the same folder 
- `StatusIm` app is not registered as separate app, so it cannot be found in Launchpad
- `StatusIm` file cannot be found using Spotlight Search, so you should manually open unzipped folder every time you want launch application
### Uninstallation notes:
- to remove `StatusIm` from your laptop you can use separate app (i.e. `CleanMyMac`) or manually stop application and remove all related files.

All this make user do a lot of additional actions just for install/uninstall app, what is quite inconvenient.

### Solution

*Summary*: 

- [x] installation package - in `.dmg` format
- [x] service files are stored in ~/Library/Application Support
- [ ]  `StatusIm` is separate app, can be found in Applications, Launchpad and through Spotlight Search
- [x]  `StatusIm` can be deleted from Applications folder

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
* Operating System: Mac OSx High Sierre

**Comment by churik** [comment]
@MaxRis you told in `Slack` that it should be implemented for last `desktop` [build](https://jenkins.status.im/job/status-react/job/desktop/job/manual/2/)
But I still can see same behavior if I download  `StatusImBundle.app.zip`.
Am I doing smth in wrong way or additional parameters should be added to Jenkins pipeline to generate `.dmg` file?

**Comment by maxhora** [comment]
Hey @churik , I mainly meant that it's not required to create some directories by hands any more. But really haven't aware about complains described in this ticket. I'm supposing to look into creation of .dmg instead of .zip and others things too hopefully.

**Comment by maxhora** [comment]
Jenkins now should build .dmg . Introduced in https://github.com/status-im/status-react/pull/5010

**Comment by EugeOrtiz** [comment]
@churik should we move this to non-P0 column?

**Comment by churik** [comment]
Closed, most of the features are presented in nightly 13.08.2018
#5423  and #5467 are opened for the rest
