### ISSUE TITLE
Add history support for 721 collectibles

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4889]
### Description

*Type*: Feature

*Summary*: we had a bug https://github.com/status-im/status-react/pull/4888 that was caused by bad 721 history support. We tried to show them as ERC20 and it was crashing the app. We need to have proper support for collectibles (ERC721) in history

### Reproduction

- Open Status
- Receive some collectibles 
- Open history

**Comment by Swader** [comment]
Still a must have

**Comment by cammellos** [comment]
Please add feature requests to https://discuss.status.im/ , thanks for you input!
