### ISSUE TITLE
Error no matching clause when switching accounts

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4892]
### Description

*Type*: Bug

*Summary*: 

![image](https://user-images.githubusercontent.com/28752642/41725239-fc21d47c-7577-11e8-8f32-1fe727d50ec9.png)

#### Expected behavior
No errors

#### Actual behavior
Error `no matching close`

### Reproduction

- Open Status
- Recover account
- Logout
- Tap create new account and stay on the screen for a while

### Logs

`06-21 17:14:03.551 13282 13362 D ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :update-transactions
06-21 17:14:03.561 13282 13362 I ReactNativeJS: PRETTY PRINTED EXCEPTION
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: ***
06-21 17:14:03.561 13282 13362 I ReactNativeJS: NAME: "Error"
06-21 17:14:03.561 13282 13362 I ReactNativeJS: MESSAGE: No matching clause:
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: status_im$utils$transactions$get_api_network_subdomain
06-21 17:14:03.561 13282 13362 I ReactNativeJS: status_im$utils$transactions$get_transaction_url
06-21 17:14:03.561 13282 13362 I ReactNativeJS: status_im$utils$transactions$get_transactions
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$fx$do_fx_after
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$interceptor$invoke_interceptor_fn
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$interceptor$invoke_interceptors
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$interceptor$execute
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$events$handle
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$_process_1st_event_in_queue
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$_run_queue
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$_fsm_trigger
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:3072:26
06-21 17:14:03.561 13282 13362 I ReactNativeJS: _callTimer@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2989:17
06-21 17:14:03.561 13282 13362 I ReactNativeJS: callTimers@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:3196:19
06-21 17:14:03.561 13282 13362 I ReactNativeJS: __callFunction@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2600:49
06-21 17:14:03.561 13282 13362 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2368:31
06-21 17:14:03.561 13282 13362 I ReactNativeJS: __guardSafe@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2562:13
06-21 17:14:03.561 13282 13362 I ReactNativeJS: callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2367:21
06-21 17:14:03.561 13282 13362 I ReactNativeJS: callFunctionReturnFlushedQueue@[native code]
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: ***
06-21 17:14:03.561 13282 13362 E ReactNativeJS: No matching clause:
06-21 17:14:03.742 13282 13362 D ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :show-tab-bar
06-21 17:15:02.282 13282 13362 I ReactNativeJS: INFO [status-im.utils.ethereum.core:133] - {"meta":null,"cnt":2,"arr":[{"ns":null,"name":"code","fqn":"code","_hash":null,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096},-32700,{"ns":null,"name":"message","fqn":"message","_hash":null,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096},"504 Gateway Timeout <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"],"__hash":null,"cljs$lang$protocol_mask$partition0$":16647951,"cljs$lang$protocol_mask$partition1$":139268}`

It fails here https://github.com/status-im/status-react/blob/develop/src/status_im/utils/transactions.cljs#L6

TF: https://app.testfairy.com/projects/4803622-status/builds/8502487/sessions/4394541713/?accessToken=AoZWKsTF5Lt9gtKDLZM9He8ZrRY

**Comment by dmitryn** [comment]
Some details on where it fails exactly https://github.com/status-im/status-react/pull/4872#issuecomment-399121157

**Comment by dmitryn** [comment]
Easy and quick workaround would be adding default case to `case` statement (as `case` really should have default case by design). It would at least hide this ugly error from user.
But we definitely need to solve underlying issue with `update-transactions` running in background after user logged out.

**Comment by annadanchenko** [comment]
When testing it I see another error `user-status.whisper-identity must be of type 'string', got 'null' (null)` see https://app.testfairy.com/projects/4803622-status/builds/8503346/sessions/4394593385/?accessToken=hzQE1ElBsr4/4rWg7HUVJHYUhCk . I propose to continue testing after Beta 

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8503346/sessions/4394593385/?accessToken=hzQE1ElBsr4/4rWg7HUVJHYUhCk">TestFairy: Status 0.9.21 (6100) @2018</a></strong></div></blockquote>

**Comment by janherich** [comment]
@asemiankevich @annadanchenko Is this still happening, or can we close this ?

**Comment by asemiankevich** [comment]
@janherich havent seen this for a while. Closing
