### ISSUE TITLE
Blue Hashtags and new line missing from develop, discovery screen not populated either

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#491]
Hmm for some reason #480 which had solved these seems to not be in develop, even though it was merged?

**Comment by alwx** [comment]
Hm. I've tested it 5 mins ago — eveything is ok on both iOS and Android.

**Comment by jarradh** [comment]
Nope, this is definitely broken, check the nightly build and/or

`rm -rf status-react && git clone git@github.com:status-im/status-react.git -b develop && cd status-react && lein deps && npm install && ./re-natal deps && lein prod-build && react-native run-android --variant=release`

Enter password, press back, open profile drawer tap on status and press enter and you can have new lines, add #hashtags and lose focus, not blue and nothing appears in Discover.

**Comment by alwx** [comment]
Tried it one more time — everything works well on emulator.
Could you please provide some details about your device?
