### ISSUE TITLE
No push notifications if a sender is not added to contacts

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#4910]
### Description

*Type*: Bug
Push notification is not shown if user who sends a notification is not added to contacts by a receiver

#### Expected behavior
Push notification is shown on top of the screen

#### Actual behavior
Push notification is not received

### Reproduction

- Open Status on 2 devices
- Create new account on both devices
- USER_1: add user_2 to contacts via: Scan QR code, or entering public key
- USER_2:  run app on background 
- USER_1 send message to user_2

### Additional Information
* Status version: any
* Operating System: Android and iOS

**Comment by lukaszfryc** [comment]
@antdanchenko @PombeirP isn't it expected? I'd not want to see notifications from non-contacts.

**Comment by antdanchenko** [comment]
@lukaszfryc I believe that we should follow one simple rule:
Notification appears whenever a message is received and the app is on background or turned off

**Comment by pedropombeiro** [comment]
I do see @lukaszfryc's point that this could be abused to spam/troll people. Unless there's a clear need/use case for this behaviour, I'd say the user should not get notifications until he's accepted the contact.
