### ISSUE TITLE
Sent transaction from Wallet is shown in Console / Public chats

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#4914]
### Description

***Type***: Bug

***Summary***: Message about sent funds is shown in the chat that is placed as the very first element on Home screen. Means:
- if Transaction sender has public chat as the place where he sent the message prior to sent Transaction from wallet (so public chat at the top of list on Home screen) -> `/send` message transaction will be shown in this public chat
- if Transaction sender has Console as the place where he sent the message prior to sent Transaction from wallet (so Console at the top of list on Home screen)-> `/send` message transaction will be shown in Console

#### Expected behavior
Message with sent transaction is not shown in any chat. Recipient receives sent tokens.

#### Actual behavior
Transaction sent from Wallet that is reflected in public chat:

<img width="408" alt="screen shot 2018-06-22 at 19 59 54" src="https://user-images.githubusercontent.com/8749671/41792381-5e891a32-7661-11e8-9217-50e1ed5925f7.png">

Message with sent transaction is shown in Status Console. Recipient doesn't receive tokens
![image](https://user-images.githubusercontent.com/29711298/41784962-7b1cc40c-7641-11e8-8e9b-9f4f51e9c14f.png)

### Reproduction #1 (when `/send` message shown in Console)
- Open Status
- Create an account
- Add a contact
- Navigate to profile and switch on development mode (under Advanced button)
- Switch network to Ropsten with upstream RPC
- After login request /faucet in Status Console (**Note**: at this stage Console is the very first element on Home screen)
- After receiving funds request STT in the Status Test DApp (Plus button -> Open DApp -> Status Test DApp -> Open -> Assets -> Request STT)
- Wait for STT to be received
- Proceed to wallet and set up it
- Open Manage assets, select Modest Test Token and click Done button
- Click Send transaction button
- Select asset -> Modest Test Token
- Input 1 in amount field - Isufficient funds error is shown
- Choose recipient -> Contacts -> select a contact
- Change asset to STT
- Input 1 in amount field againg as it was cleaned
- Sign transaction
- Navigate to the Home view and open Status Console

### Reproduction #2 (when `send` message for TX sent from wallet appears in Public chat)

1) Open Status on Device1 (iOS) and Device2 (Android)
2) Create Contact 1 (iOS) and Contact 2 (Android) and request ETH and tokens for them.
3) Both contacts edded each other in contacts (Contact1 sends contact request to Contact2)
4) Contact2 sends `/request ETH 0.0003` in 1-1 chat to Contact1
5) Contact1 taps the `/request` message and sends the requested amount to Contact1 (basically a usual reply to `/request ETH` message)
6) Contact1 and Contact2 joins the same unique public chat (e.g. `#everythingisok`) and exchange messages there
7) Now, Contact1 (iOS) navigates to Wallet -> Send Transaction screen.
8) Contact1 sends STT to Contact2 (tap 'Specify recipient -> Contacts -> shoose Contact2 -> Asset -> STT -> Specif amount = 33 -> Advanced -> finaly `Sign Tx`
9) Check on both devices whether `/send` message is present in public chat

### Additional Information
* Status version: 0.9.21 (6108), node a339d7e
* Operating System: iPhone 8+, iOS 11.3.1, iPhoneX(iOS 11.2.5), Android

TF session for Console case : https://app.testfairy.com/projects/4803590-status/builds/8503790/sessions/4394604944?source=latest-sessions

TF session for Contact1 above  from **Reproduction 2** from 1:13:10 here: https://app.testfairy.com/projects/4803590-status/builds/8504019/sessions/4394617675/?accessToken=fSARMCXpN2amHCvgr-R-J3vu0bE
TF session when Contact2 above from **Reproduction 2** (and Contact1 as well actually) sees transaction in public chat: from 59:50 
 https://app.testfairy.com/projects/4803622-status/builds/8504010/sessions/4394618703/?accessToken=S9L3d8I-bkz37QWkjC9OlsllVJU

**Comment by Serhy** [comment]
I reproduced it by TX of the token sent from Wallet reflected in as `/send` message in public chat.

1) Open Status on Device1 (iOS) and Device2 (Android)
2) Create Contact 1 (iOS) and Contact 2 (Android) and request ETH and tokens for them.
3) Both contacts edded each other in contacts (Contact1 sends contact request to Contact2)
4) Contact2 sends `/request ETH 0.0003` in 1-1 chat to Contact1
5) Contact1 taps the `/request` message and sends the requested amount to Contact1 (basically a usual reply to `/request ETH` message)
6) Contact1 and Contact2 joins the same unique public chat (e.g. `#everythingisok`) and exchange messages there
7) Now, Contact1 (iOS) navigates to Wallet -> Send Transaction screen.
8) Contact1 sends STT to Contact2 (tap 'Specify recipient -> Contacts -> shoose Contact2 -> Asset -> STT -> Specif amount = 33 -> Advanced -> finaly `Sign Tx`
9) Check on both devices whether `/send` message is present in public chat

TF session for Contact1 above from 1:13:10 here: https://app.testfairy.com/projects/4803590-status/builds/8504019/sessions/4394617675/?accessToken=fSARMCXpN2amHCvgr-R-J3vu0bE
TF session when Contact2 (and Contact1 as well actually) sees transaction in public chat: from 59:50 
 https://app.testfairy.com/projects/4803622-status/builds/8504010/sessions/4394618703/?accessToken=S9L3d8I-bkz37QWkjC9OlsllVJU



<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8504019/sessions/4394617675/?accessToken=fSARMCXpN2amHCvgr-R-J3vu0bE">TestFairy: Status 0.9.21 (6108) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8504010/sessions/4394618703/?accessToken=S9L3d8I-bkz37QWkjC9OlsllVJU">TestFairy: Status 0.9.21 (6108) @2018</a></strong></div></blockquote>

**Comment by cammellos** [comment]
At a first sight, seems like the issue might be in `get-current-chat-id` being mistakenly used (it would be set to the last chat you joined)
