### ISSUE TITLE
!js command

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#492]
Hey @adrian-tiberius initial `!js` command is off to a great start. Right now it doesn't flow great you should be able to get nearly all the way through just by tapping through suggestions. 

- [x] when `(!params.code || params.code == "")` lets show a 'Last Message' which would populate the message with the last executed message (if it exists) and underneath that, populate suggestions of base DOC_MAP objects.
- [x] chat input loses focus after tapping a suggestion and keyboard dissapears, abit of an unwanted hurdle
- [x] if the suggestion is an object we should add `'.'` to the suggestion to get the next set of suggestions. ie `var accessor = (typeof global[suggestion] == 'object' ? '.' : '');` and `onPress: [status.events.SET_VALUE, code.substring(0, code.length - lastPart.length) + suggestion + accessor]` this issue with this is we might have to set `global.web3` and `global.status` due to the way Otto/Node work.
- [x] add ```console: {
        log : {
            desc: 'Outputs a message to chat context.'
        }
    },``` to DOC_MAP
- [ ] ideally this suggestions area should be smaller on this command at least on initial run, maybe its too much to ask for alpha
- [ ] it's also possible to get a suggestions area tab just above input without any suggestions, I'll find clear steps to reproduce
- [x] I'm wondering that instead of doing a staging message if we should keep the user in the `!js` command so you can type code then hit enter and see response and type again, instead of tapping, can rethink this for after alpha

**Comment by jarradh** [comment]
- [ ]  `web3.isConnected()` says its not a function ?
- [ ] if i tap `console.log(` then start typing `web3` web3 suggestion doesn't come up anymore
- [ ] if i type `console.log(web3.isConnected())` the suggestion does come up for `log()` and if i tap on log() i get `console.log(web3.isConnectedlog(`

**Comment by adrian-tiberius** [comment]
web3.isConnected() problem is related to https://github.com/status-im/status-go/issues/69
