### ISSUE TITLE
Mixpanel ice age

### ISSUE THREAD

**Issue by arnetheduck** [status-im/status-react#4922]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be sure that mixpanel is disabled in the future so that my privacy is preserved.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

*Summary*:

Enabling mixpanel tracking for more and more users lands us in the territory of diminishing returns and increased risk in case of any unintended privacy leaks or application issues. 

### Exponentially decreasing probability of opt-in offer

Expecting exponential growth from beta onwards, as users flock to our application like crazy, it makes sense to offset this user growth and only ask an ever diminishing fraction of our users to enable mixpanel tracking to begin with. 

Assuming a constant ratio of users opting in to use the application and a deterministic function used for the probability of displaying the opt-in screen, we can also probabilistically determine the actual number of users based on those that enable tracking at any point in time.

### Final time bomb

We've promised that mixpanel will be removed - an easy way to deliver on this promise right now is to include an absolute time bomb on mixpanel usage, beyond which it will simply be disabled. This has several benefits:
* any privacy-leaking bugs in the application come with a limited life span
* we have ample motivation to get our shit together on time
* keeping the tracking beyond the final date requires an active decision, presumably based on good reasons

End-of-year sounds as good as any point in time for this

**Comment by yenda** [comment]
@arnetheduck I suppose we can close this since mixpanel was removed ?
