### ISSUE TITLE
"Error: Doesn't support name" and blank screen after "Insufficient funds for gas" error (if you send transaction from wallet to scanned QR code)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4930]
### Description

*Type*: Bug
*Summary*: if you send transaction from wallet, scan QR code and enter amount = balance, after getting error "Error: Doesn't support name", than "Insufficient funds for gas*price + value"  only blank screen is shown, and you should restart app to proceed work.

#### Expected behavior
app is working after "Insufficient funds for gas*price + value" error

#### Actual behavior
blank screen

### Reproduction

- Open Status
- Go to wallet
- Tap on "Send transaction"
- Scan valid QR code in "Choose recipient"
- in field amount enter value = balance (to trigger "Insufficient funds for gas" error)
- sign transaction

### Additional Information

* Status version: [release build 14](https://jenkins.status.im/job/status-react/job/public-beta-1-testfairy/14/)
* TF session (02:10 - 02:22): https://app.testfairy.com/projects/4803622-status/builds/8504954/sessions/4394741148/?accessToken=sOa71MMoyJlYMcOU7R13UBzOaqE
* Operating System: Android
* Network: Mainnet
* Note: can be reproducible on Ropsten, but for me from the second attempt.
#### Logs
```
02:16 I/ReactNativeJS: NAME: "Error"
02:16 I/ReactNativeJS: MESSAGE: Error: Doesn't support name: 
02:16 I/ReactNativeJS: 
02:16 I/ReactNativeJS: This error is located at:
02:16 I/ReactNativeJS:     in asset-selector
02:16 I/ReactNativeJS:     in reagent136
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in RCTScrollView
02:16 I/ReactNativeJS:     in ScrollView
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in reagent4
02:16 I/ReactNativeJS:     in reagent132
02:16 I/ReactNativeJS:     in reagent131
02:16 I/ReactNativeJS:     in send-transaction
02:16 I/ReactNativeJS:     in reagent130
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in main
02:16 I/ReactNativeJS:     in root
02:16 I/ReactNativeJS:     in reagent1
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in RCTView
02:16 I/ReactNativeJS:     in t
02:16 I/ReactNativeJS: 
```

**Comment by churik** [comment]
Could reproduce for IOS as well.
TF session (06:00 - 07:00): https://app.testfairy.com/projects/4803590-status/builds/8514859/sessions/4395450128/?accessToken=y3VjSWNUpVKU5Q5cMmBDQ1tRmqo

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8514859/sessions/4395450128/?accessToken=y3VjSWNUpVKU5Q5cMmBDQ1tRmqo">TestFairy: Status 0.9.21 (6157) @2018</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@yevh-berdnyk https://ethstatus.testrail.net/index.php?/cases/view/3764

<blockquote><img src="https://static.testrail.io/5.5.0.3731/images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/3764">Login - TestRail</a></strong></div></blockquote>
