### ISSUE TITLE
Add privacy policy to signup and recover

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#4932]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to read a privacy policy before I use the app so that I can be informed.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

A privacy policy is an important part of apps to both offer legal compliance and informed consent on usage, privacy policies, etc.

#### Expected behavior
A user agrees to the privacy policy when signing up and recovering an account. 

#### Actual behavior
No terms or policies available.

### Solution

- Privacy visible on signup
- Privacy visible on recovery
- Privacy visible on the profile tab
- Tapping privacy link opens in a browser (link >> https://www.iubenda.com/privacy-policy/45710059)

[Designs in Zeplin](https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5b5ffebc62ee9cb427271adb?ref=slack).

<img width="641" alt="screen shot 2018-07-31 at 9 09 31 am" src="https://user-images.githubusercontent.com/116099/43443558-855214bc-94a1-11e8-9384-a841b106a11c.png">

**Comment by chadyj** [comment]
More info on the privacy policy >>> https://discuss.status.im/t/mobile-app-privacy-policy/190

<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/mobile-app-privacy-policy/190">Mobile App Privacy Policy</a></strong></div><div>An important value at Status is transparency, but sometimes development moves so quickly that we don’t have the opportunity to pause, document, discuss, and disseminate the various components of the mobile app.  One way to help address this is by adding a privacy policy to the app to let our community know what services we use to make Status work, and how personal data is used. It is also an important reminder that we do have some centralized dependencies and employ services that may expose user...</div></blockquote>

**Comment by errorists** [comment]
Proposed design prototype https://framer.cloud/kBFqz
In the design team, we agreed that the welcome screen is the best place to host the T&C and Privacy Policy. 
In the user profile, I've added a common 'About' section where users will find the T&C and Privacy Policy. I also propose to move the Version number there, it feels like a more natural fit than having in next to 'Log Out'.

<blockquote><img src="https://framer.cloud/kBFqz/2/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/kBFqz">Onboarding Privacy</a></strong></div><div>This project was made with Framer, a design tool for turning original concepts into working prototypes.</div></blockquote>

**Comment by EugeOrtiz** [comment]
@chadyj Do we have the T&Cs copy? I can only see the PP's one.
According to https://github.com/status-im/design/issues/15 we will need to embed the text within the app. For desktop we will need to either embed it or send the user to the browser w/ this info.

**Comment by chadyj** [comment]
Thanks @errorists! Looks good!  To ensure full compliance ould you also add the privacy policy so it is materially connected to the logout > create new, add existing flows? Since terms change, or different users could be using sharing a device we need to show the policy at these points.  Can you also please mock up including the terms within the app so users can refer to this when logged in?  Thanks!

@EugeOrtiz It is fine to open the policy in a browser. No T&C's right now.

**Comment by errorists** [comment]
Uploaded all the mockups to [Zeplin](zpl.io/2ZJ9oAE) 
@chadyj @obi2020 Not sure on the exact wording for the Log Out - > Sign In flow, should we also use a catchall 'By continuing' like on the welcome screen?

_Edit:_ Updated the mockups so that both use the same copy : 'By continuing…'

**Comment by chadyj** [comment]
Thanks @errorists looks great 🍻

**Comment by chadyj** [comment]
Had a thought that the "by continuing" is a bit generic and doesn't help the user understand the nature of the privacy policy.

What do you think about something like "Review our privacy policy to understand how your data is used and shared with third parties."

@obi2020 Thoughts?

**Comment by obi2020** [comment]
I think "by continuing" is meant to communicate that whether you read it or not, creating the account means you've agreed. Do we want to require users to open the Privacy Policy before they continue. A lot of apps do that, though I don't think it necessarily increases reading rates

How about 

> "By creating an account, you agree to our Privacy Policy. Read it to understand how your data is used."

It's longer, which isn't ideal considering there's already soooo much text on this page :-) To that end, I believe that top copy has already been edited down, which may help.

@chadyj

**Comment by obi2020** [comment]
@errorists Sorry I missed your note. Where will this surface during log out?

**Comment by errorists** [comment]
@obi2020 +1 I like the edit with "…Read it to understand how your data is used." We have a second entry point where the policy is placed, once you log out and choose to sign in with another account.

**Comment by hesterbruikman** [comment]
fyi here's a long term view on how we can integrate a more granular solution that will give more control than a accept all during onboarding: https://status-im.slack.com/archives/CA83RN3ML/p1534240566000100

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/CA83RN3ML/p1534240566000100">Slack</a></strong></div></blockquote>
