### ISSUE TITLE
Account is blocked by `Ethereum node started incorrectly` error if custom network url doesn't match chain

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#4935]
### Description
`Ethereum node started incorrectly` error and bunch of `Wrong decimals for token...` errors same to as described in https://github.com/status-im/status-react/issues/6840 issue is shown on login
the app is closed after pressing on 'OK' button, if user provides Mainnet RPC, but selects different chain (ropsten or rinkeby)

#### Expected behavior
User can use the account in order to change the network

#### Actual behavior
- Bunch of `Wrong decimals for token...` errors appears
- App is closed after tapping on `OK` button
- If user re-logins the same error is shown and the app is closed after pressing on `OK` button
- Account can't be used

<img width="268" alt="Screenshot 2019-03-15 at 20 06 27" src="https://user-images.githubusercontent.com/8749671/54452446-dc982580-475d-11e9-86d2-64dc244ad381.png">

<img width="328" alt="Screenshot 2019-03-15 at 20 03 12" src="https://user-images.githubusercontent.com/8749671/54452265-67c4eb80-475d-11e9-80e0-5de586307a4e.png">

### Preconditions
- Go to https://infura.io/
- Click `GET STARTED FOR FREE` and proceed with registrations
- As result you will get an email/will be redirected to a page with URLs + your api key
- Copy `Test Ethereum Network (Ropsten)` url
 
### Reproduction
- Open Status
- Enable development mode in Profile under Advanced 
- Click on network settings
- Click on `+` button in upper right corner 
- Enter any network name
- Select different chain (mainnet or Rinkbey, if url is for Ropsten), under network chain and press Save, as result you will be redirected to `Network settings` screen 
- Select custom network by name on the screen and tap on Connect, as result you will be redirected to `Sign in` screen
- Login

### Additional Information (Updated 15 March 2019)
* Status version: Release 0.10.1, Develop 0.11.0 
* Operating System: Android and iOS

<blockquote><img src="https://infura.io/infura-offering.png" width="48" align="right"><div><strong><a href="https://infura.io">Infura - Scalable Blockchain Infrastructure</a></strong></div><div>Secure, reliable, and scalable access to Ethereum APIs and IPFS gateways.</div></blockquote>

**Comment by jisamathew** [comment]
How to solve this issue?I was able to connect to new custom network first time..later not possible.?

**Comment by Swader** [comment]
This is still a problem.

**Comment by Serhy** [comment]
Updating issue description after retest with 0.11.0 app version:
Now, apart `Ethereum node started incorrectly` error there is a bunch of `Wrong decimals for token...` errors - same as described in the issue https://github.com/status-im/status-react/issues/6840

Now, after user specifies custom network with different chain and logs in to account: `Ethereum node started incorrectly` and `Wrong decimals for token...` errors (same errors as described in the issue https://github.com/status-im/status-react/issues/6840).
As before, `Ethereum node started incorrectly` error forces app to shut down making account unusable. 1 of 5 times, on iOS 12.1.4 on iPhoneX, I was lucky to not catch the `Ethereum node started incorrectly` (only bunch of `Wrong decimals for token...`) and it gives a chance for user to change the network. 

However, issue is still present and confirmed on iOS 12.1.4, Android 6.0.1, but with Android 8.1 there are only bunch `Wrong decimals for token...` errors. 

With Release 0.10.1 app version `Ethereum node started incorrectly` error appears on all mobile environments.

**Comment by rasom** [comment]
I propose to remove selection of "Network chain" from that screen and request network-id using RPC. While request is performing we can show activity indicator, if it fails  we show an alert which states that network can't be added.

As an alternative we can keep "Network chain" selection and compare it with the one we requested by the url, and in case if request failed or resulting id is not the same as expected we can show an confirmation where ask the user whether a new network should be saved anyway. In this case the user will be able to save the network even if they are offline or the network is not available currently (but with no guarantee that app will work properly when the network is selected).

**Comment by rasom** [comment]
> (but with no guarantee that app will work properly when the network is selected)

Although we can check if saved network id corresponds to selected one when the network is actually started.
