### ISSUE TITLE
Default username is shown on tapping on three dots in 1:1 chat (Android only)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4937]
### Description

*Type*: Bug

*Summary*: when you tap on three dots in 1:1 chat to see possible actions, you can see default username instead of custom even user is already in your contact list.

#### Expected behavior
custom username

#### Actual behavior
default username
![wrname](https://user-images.githubusercontent.com/4557972/41858924-ac8dc48c-78a3-11e8-9dde-f7251ff2a56b.png)

### Reproduction

- Open Status
- Start 1-1 chat with user, who set custom name
- Add it to contacts, so custom name is shown as chat header
- Tap on three dots on right top corner

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: [beta release build 14](https://jenkins.status.im/job/status-react/job/public-beta-1-testfairy/14/)
* Operating System: Android

**Comment by cammellos** [comment]
Just more info on this, this is just due to some rendering issues.
To replicate:

1) Send contact request to A
2) On A go to 1-to-1 chat with B
3) On B update username
4) On A click on 3 dots
