### ISSUE TITLE
Change copy for browser options from chat link

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4938]
### User Story

As a user, I want to know the difference between two confusing browser options when I open a link.

### Description

*Type*: Feature

*Summary*: Change copy on the first option when opening a link inside Status. 

<img src="https://user-images.githubusercontent.com/15470435/41860919-24df5e04-78a0-11e8-823e-47112324ee03.png" width=250/>

#### Expected behavior
When a user clicks on a link from chat, the options should read:

`Open in Status`
`Open in web browser`

#### Actual behavior
See above.

### Reproduction
Send someone a link in chat, and click on it.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 250.00
Contract address: [0x8001b8c9ed1d5d7d91d2bf560a94e3d857da9fcd](https://etherscan.io/address/0x8001b8c9ed1d5d7d91d2bf560a94e3d857da9fcd)
Network: Mainnet
Paid to: tbenr
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by chadyj** [comment]
cc @obi2020

**Comment by pablanopete** [comment]
This needs to be merged & confirmed, sending OOB for now (other two issues that @tbenr worked on have been OOB handled)

this has been sent but will be issued x2 once the SOB dashboard is fixed.
