### ISSUE TITLE
The iOS Keyboard Prevents Sign In with an Existing Account

### ISSUE THREAD

**Issue by reinermatthew** [status-im/status-react#4941]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story
As a user, I want to log  into Status using an account created on another device so that I can use my account on both devices.

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The iOS keyboard can't be hidden, and blocks the `Password` field.
![image](https://user-images.githubusercontent.com/3212454/41873228-5f44a828-7892-11e8-968a-a845b64c9268.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I expect to be able to hide the keyboard so I can select the `Password` field so I can enter my password.

#### Actual behavior
[comment]: # (Describe what actually happened.)
I can't hide the keyboard so I can select the `Password` field so I can enter my password.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Tap "I already have an account"
- Enter a seed phrase
- Notice you cannot hide the `keyboard` to view/select the `Password` field

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: Provide an option to hide the keyboard so users can select the password field

- Add a button to hide the keyboard.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.20 (6075)
[comment]: # (Android or iOS.)
* Operating System: iOS on iPad

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by chadyj** [comment]
Hi @reinermatthew thanks for the bug report. 
We are rolling out some fixes for iPad support, so look out for an update soon https://github.com/status-im/status-react/issues/4662
