### ISSUE TITLE
Add universal/deep links

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#4944]
As a user, 
I want to send a link to a public channel 
so I can invite others to join a discussion. 

Eg clicking https://status.im/chats/public/status opens the Status app then joins the #status public channel 

As a user, 
I want to send a link to my profile 
so that others can easily add me as a contact. 

Eg clicking https://status.im/profiles/0x234567890876 opens the Status app, then opens the profile of this user so they can be added to contacts or a 1-1 chat can be started 

#### Chats
When a user clicks on a link in the format:

`https://status.im/chats/public/name-of-the-chat`

* If the user has status installed, it should open up that public chat ( or create and open if necessary).

* If the user has not status installed, it should redirect to the relevant app store.

#### Profile

When a user clicks on  a link in the format:

`https://status.im/profiles/user-public-key`

* If the user has status installed, it should open up that contact profile page

* If the user has not status installed, it should redirect to the relevant app store.

### Solution

Other use cases that we might want to implement in the future and might be helpful to take into consideration when coming up with a solution:

* Link to one-to-one chats `https://status-im/chats/one-to-one/pk`
* Link to a specific message in a chat `https://status.im/chats/public/chat-id/messages/message-id`

Unicode characters should not be allowed when handling urls for now until (add issue link here) is fixed

This should work on both ios & android.

This will ideally pave the way for https://github.com/status-im/status-react/issues/3488 to be implemented.

Some preliminary investigation was done on https://github.com/status-im/status-react/issues/1592 , but a generic solution is not required as long as it fulfills the main use cases.

**Comment by chadyj** [comment]
Created a wiki page with some info on Universal Links https://wiki.status.im/Universal_Links

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>

**Comment by chadyj** [comment]
Found an issue when opening a dapp link FROM a dapp:
1. Go Home > New > Open Dapp
2. Paste in https://wiki.status.im/Universal_Links
3. Scroll down and tap the cryptokitties link

It briefly showed  “unable to load page -1002 unsupported URL”, and seemed to load it twice. Then going back to Home showed 2 Cryptokitties tabs that were opened, and the original has the `status-im://` address which is a problem because I can’t go to that tab to resume my browsing history because tapping it loads the dapp again

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>

**Comment by leafcutterant** [comment]
@chadyj I want to learn more about deep/universal links, but the link to the wiki entry is broken.

**Comment by chadyj** [comment]
@leafcutterant Sorry not sure where that page went. Perhaps there is an archive @andytudhope @jakubgs?

**Comment by leafcutterant** [comment]
Instead of an archive, it may be a good idea to rather incorporate it into what took the place of the wiki (https://status.im/docs/), presuming it still exists somewhere.

**Comment by jakubgs** [comment]
All I found is this:
https://github.com/status-im/wiki.status.im
But it doesn't seem to contain the article you were looking for, so not sure where that might have gone.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/wiki.status.im">status-im/wiki.status.im</a></strong></div><div>It's the wiki... for Status. Contribute to status-im/wiki.status.im development by creating an account on GitHub.</div></blockquote>

**Comment by SlizkovaGanna** [comment]
@cammellos @chadyj 
What would you say about more complex/rare scenarios like:
1. User opens a deep link when app is closed
2. When redirected to the app, creates a new account
3. User logs in under this new account
**Expected result:** Should we still redirect the user to the deep link data, or not? 
**Current result:** Deep link data is not triggered, user is simply logged in.
Also, for similar scenarios, if a user decides to: 
- restore an account after the app is triggered
- switch to a different account (go back to welcome screen and select a different account)
- in the middle of creating a new account, goes back and logs in as an existing account
and so on.
**Should we redirect the user after he finally logs in to this specific deep link data still?**
Thank you.

**Comment by chadyj** [comment]
@jakubgs Was able to find the old wiki content!  @rachelhamlin was planning to add it to the new docs site.  For now here it is:

## Universal Links (iOS) & Deep Links (Android)

#### What are Universal & Deep Links

With universal links (iOS) and deep links (android) mobile users can tap a link to Status and get seamlessly redirected to the Status app and linked to specified screens without going through the browser. If Status isn’t installed, tapping a link to the Status website opens a Status website
with info on the link and instructions to download the mobile app.

#### What Links Are Supported

##### Public Chats

<https://get.status.im/chat/public/>**CHANNEL-NAME** eg
<https://get.status.im/chat/public/status>

##### DApp Browser

<https://get.status.im/browse/>**DAPP-ADDRESS** eg
<https://get.status.im/browse/www.cryptokitties.co>

##### Users

<https://get.status.im/user/>**CONTACT-ADDRESS** eg
<https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx>
<https://get.status.im/user/name.stateofus.eth>

#### Custom URL Scheme

In addition to the deep links the above links can be called with the
status-im:// custom URL scheme, such as status-im://chat/public/status

**Comment by pycckuu** [comment]
https://get.status.im is not working?

**Comment by jakubgs** [comment]
The service for deep linking has been moved to https://join.status.im/.
