### ISSUE TITLE
Enable spam prevention in chats in release builds 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4950]
### Description

*Type*: Bug

*Summary*: Spam prevention in chats (https://github.com/status-im/status-react/pull/4537) is currently only enabled in internal builds. This issue is to enable it in release builds as well.

#### Expected behavior
Spam prevention is enabled in all builds including release.

#### Actual behavior
Spam prevention is enabled only for nighlty/PR builds.

### Reproduction

- Open Status
- Join public channel
- Write 10 messages as fast as you can. There should be a dialog popping up to prevent spamming

### Additional Information
* Status version: 0.9.21
* Operating System: Android, iOS

**Comment by dmitryn** [comment]
Fixed by https://github.com/status-im/status-react/pull/4947
