### ISSUE TITLE
Remote app config

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#4954]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer or product manager, I want to change app configuration  without releasing app upgrade so that i can enable/disable/change features on the fly.

### Description

App configuration settings https://github.com/status-im/status-react/blob/develop/.env.prod should be adjustable on the fly without an app upgrade by using remote config.

### Solution

Since we already using Firebase for Push Notification, possible solution would be using Firebase Remote Config https://firebase.google.com/docs/remote-config/?authuser=0 

Obvious downside of this solution is becoming more dependent on Firebase services. Also, potential security issues may arise. Better alternatives are welcomed.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>
<blockquote><img src="https://firebase.google.com/_static/bdb9b43e5e/images/firebase/favicon.png?authuser=0" width="48" align="right"><div>Firebase</div><div><strong><a href="https://firebase.google.com/docs/remote-config/">Firebase Remote Config  |  Firebase</a></strong></div><div>Change the behavior and appearance of your app without publishing an app update, at no cost, for unlimited daily active users.</div></blockquote>

**Comment by flexsurfer** [comment]
we can use whisper :)

**Comment by lukaszfryc** [comment]
I'm removing "release" label since it's not a blocker for upcoming release (0.9.22).

**Comment by dmitryn** [comment]
@lukaszfryc sure, i didn't mean it's a blocker, but related to how we release the app, i.e. how we can change config on-the-fly after release done.
