### ISSUE TITLE
"Show more" overlaps with time if message contains ~< 12 chars in every row

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4955]
### Description
*Type*: Bug

*Summary*: if message width is ~< 12 chars (for IOS 7) - "Show more" and time are overlapping in 1-1 and public chats

#### Expected behavior
no overlapping

#### Actual behavior
![shmore](https://user-images.githubusercontent.com/4557972/41922577-190664d2-796e-11e8-9173-f693dcb14ac8.png)

### Reproduction

- Open Status
- Log in 
- Open any chat
- Type message with > 20 rows (rows should contain <12 chars, i.e. "1234")
- Send message

### Additional Information

* Status version: [release build 14](https://jenkins.status.im/job/status-react/job/public-beta-1-testfairy/14/)
* Operating System: Android, IOS
* Network: Mainnet

**Comment by churik** [comment]
still reproducible

**Comment by Swader** [comment]
Tested on Android 9+, looks fixed.
