### ISSUE TITLE
Token name and amount overlap in 1:1 chat token list 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#4963]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
Long token name overlaps with long amount in 1:1 chat list of tokens
![screenshot_20180626-170247](https://user-images.githubusercontent.com/6584810/41964151-98ca1778-79f9-11e8-9885-0c7b19f2f4cf.png)
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No overlap - maybe removed token name and keep only abbreviation?
#### Actual behavior
[comment]: # (Describe what actually happened.)
token name and amount overlap that makes it's hard to read
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Have in wallet some token with long name, e.g BAT and some long amount for it as on picture
- Open Status
- Open 1:1 chat
- /send
- Check the list of tokens and if you can read amount for BAT

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: found on Android, Galaxy S6 real device

**Comment by goranjovic** [comment]
In short term, we'll remove the balance from that popup. In the updated design it's placed in the amount param suggestion anyway, so it's not supposed to stay there.
Will add balance back to the amount suggestion box as a part of #4972
