### ISSUE TITLE
Always show wallet address in one line

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4964]
### Description

*Type*: Bug

*Summary*: Instead of showing address in 2 lines we should rather show "..." in the middle of it. Same as for an address in login screen.

<img src="https://user-images.githubusercontent.com/7532782/41964311-ef8d1e16-79f9-11e8-8da3-2c74bfe72ae1.png" width="200">

### Reproduction

- Open Status
- Go to Wallet -> Send transaction
- Choose recipient address

### Additional Information
* Status version: 0.9.21
* Operating System: Android, iOS

**Comment by annadanchenko** [comment]
@denis-sharypin wdyt? 
@lukaszfryc it seems like a UX question and matter of taste imo. Don't you want to see full address of a receiver? For example, I prefer to see exact address to whom I send funds.

**Comment by denis-sharypin** [comment]
It's important to show the full address in this exact case bc this screen is also a confirmation screen of sending transaction. 
Also this issue affects only big-screen phones

**Comment by lukaszfryc** [comment]
OK. So it looks like there is no obvious way to make it look a bit better. Maybe having a bigger padding around the "..." button could help to understand that "A" is still part of the address. Anyway, unless you think it's a good idea and it's worth doing, let's close this issue.

**Comment by denis-sharypin** [comment]
Alright, adding an extra 10 px padding to the left side of the `...` button is a nice idea!

**Comment by lukaszfryc** [comment]
@denis-sharypin should the padding be the same as for the next field (Asset)?

**Comment by denis-sharypin** [comment]
@lukaszfryc yes. that would be more consistent

**Comment by lukaszfryc** [comment]
OK, I'll create a separate issue for the padding. Closing this one.
