### ISSUE TITLE
Message bubble shown in two lines instead of one

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4965]
### Description

*Type*: Bug

*Summary*: Single line message and timestamp should be displayed in single line if there is enough space. See message "1" and its timestamp look like on iPhone X (11.2.1):

<img src="https://user-images.githubusercontent.com/7532782/41964493-6c4d4cd2-79fa-11e8-9593-ba27c57a0287.png" width="200">

#### Expected behavior
The message and timestamp are displayed in single line if there is enough space.

#### Actual behavior
The message and timestamp were displayed in 2 lines.

### Additional Information
* Status version: 0.9.21
* Issue experienced on: iPhone X, 11.2.1
* Could not be reproduced on: Galaxy S8, iPhone 8
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@Serhy could you check if you can reproduce it on iPhone X?

**Comment by Serhy** [comment]
It looks good on iPhoneX (iOS 11.2.5). Screenshot:

<img width="310" alt="screen shot 2018-06-27 at 13 53 18" src="https://user-images.githubusercontent.com/8749671/41969890-96513f90-7a11-11e8-8e44-7fa0d025009b.png">

What is very likely in the message from the description is that contact sent it with the return at the end. In that case, it ends up with timestamp in the second line.

So this issue we could turn out to "Do we need to trim() the message before it sent?"
I think yes. Well, at least that's what WhatsApp and Telegram do.

**Comment by lukaszfryc** [comment]
@Serhy what about that last message on your screenshot. The issue here is that the bubble it's bigger than single line.

**Comment by Serhy** [comment]
@lukaszfryc the last message there was sent in a way: 

1) In message editbox type `1` 
2) Tap `Return` from keyboard
3) Tap `Send message` blue button
**Result**: double line message sent.
**Expected** **result**: one line message. 

So what originally reported is very likely sent in a way I described above. I even found that message in status channel and copied it content via 'Copy to clipboard' action and indeed it's pasted with the line break at the end :)

I guess we can open a separate issue (feature) to `trim message content after user taps 'Send message' button in chats` to avoid message bubbles like
```



1
  1:56 PM
```
or

```
                    1                                                   1:56 PM

**Comment by Serhy** [comment]
#4994 created that should fix the problem described here.
Closing this one.
