### ISSUE TITLE
It's possible to recover an account by entering a valid Passphrase and invalid Password

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4967]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be sure that no one can recover my account without knowing the valid password of my account.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: It is possible to recover an account by entering a valid Passphrase and invalid Password. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

It should not be possible. 

#### Actual behavior
[comment]: # (Describe what actually happened.)

Status recovers the account associated with a Passphrase without checking if the Password is valid.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on 2 separate devices (A and B)
- Note the seed phrase of A
- Navigate to the "I already have an account" menu of B
- Enter the Passphrase of A
- Enter some random password, not the one you've chosen when you created your A account

You can find a recording of my workflow here: https://youtu.be/zrNvnYzxqwo 
 - As you can see, the initial password for my account is "qqq111" and then I use "somerandompass" when recovering it
 - The both devices have the same account when comparing the contact code associated with them

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21 (6129), Nightly build "June 27", http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-d276d5-n-fl.apk

[comment]: # (Android or iOS.)
* Operating System: Tested on Android. Can't confirm about iOS.

#### Logs

https://gist.github.com/GeorgiG/25a56a33d6ccaa203c8ac2be4aac1558

<blockquote><img src="https://i.ytimg.com/vi/zrNvnYzxqwo/maxresdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=zrNvnYzxqwo">Recover an account</a></strong></div><div> </div></blockquote>
<blockquote></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/5781465?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/GeorgiG/25a56a33d6ccaa203c8ac2be4aac1558">Recover an account</a></strong></div><div>GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.</div></blockquote>

**Comment by annadanchenko** [comment]
it's expected: passphrase(seed phrase) is the only thing you need to recover account. 
Password is to log in to the app and sign transaction
