### ISSUE TITLE
Update "open in browser" copies

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4968]
### Description

*Type*: Feature

*Summary*: It may not be clear what's the difference between 2 browsers. These copies could be updated to:
- "Open in Status browser"
- "Open in external browser"

<img src="https://user-images.githubusercontent.com/7532782/41971401-90371c18-7a0e-11e8-9411-fc864126d621.png" width="200">

### Reproduction

- Open Status
- Go to a chat
- Click on a message with link 

### Additional Information
* Status version: 0.9.21
* Operating System: Android, iOS

**Comment by annadanchenko** [comment]
@lukaszfryc duplicate of https://github.com/status-im/status-react/issues/4938 ?

**Comment by lukaszfryc** [comment]
yes
