### ISSUE TITLE
"Fetching messages.." appears too often and may be annoying

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4969]
### Description

*Type*: Feature

*Summary*: Seeing "Fetching messages.." so often (like every time app resumes from bg) maybe annoying. It also covers "Add to contact" button and chat list in Home. However, I'm not sure how to best solve it. Maybe show it no often than 60s or show it only when a chat / chat list is empty?

<img src="https://user-images.githubusercontent.com/7532782/41971824-0559d9b2-7a10-11e8-89f6-0df1ce5d10f2.png" width="200">

### Reproduction

- Open Status

### Additional Information
* Status version: 0.9.21
* Operating System: Android, iOS

**Comment by pedropombeiro** [comment]
This might be a duplicate of https://github.com/status-im/status-react/issues/4345

**Comment by lukaszfryc** [comment]
> Keep progress bar visible if shhext_requestMessages was called less than 10 seconds ago
Keep progress bar visible if a new unread message was added less than 5 seconds ago
Hide progress bar if shhext_requestMessages was called more than 30 seconds ago

@PombeirP yes, this issue should be fixed if #4345 implements such heuristics. cc @errorists
