### ISSUE TITLE
Status-Desktop is not usable after creating account if you click on "Share Data with Status"

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#4970]
Issue found and reported by @churik 

# Status-Desktop is not usable after creating account if you click on "Share Data with Status"
### Steps
- Open StatusIm
- Create account
- Tap on "Share data". Popup with confirmation should appear.
- Tap on "Yes" or "Cancel"

### Expected result
can use Status

### Actual result
![merged status](https://user-images.githubusercontent.com/4557972/41957673-5f8df3c0-79f0-11e8-8644-7071e6d3e6a4.png)

* OS: Mac OSx High Sierra
* Log: https://drive.google.com/file/d/1q5-9vglUXIhUt9znUsIy744QYju6UQRJ/view?usp=sharing
* Note: confirmation popup is missing in `desktop` branch, so the issue is presented only in particular PR. Only workaround is click on "Don't share".

**Comment by EugeOrtiz** [comment]
Are we having a share data feature for desktop as P0?

**Comment by churik** [comment]
@EugeOrtiz you cannot exclude it, it is part of the mobile app. It is not separate feature.

**Comment by maxhora** [comment]
But we can skip processing of button press for now if this feature is not important as P0

**Comment by churik** [comment]
@MaxRis if so, we should exclude it at all from desktop app, because this workflow is most common.
This means two options as I can see:
1 - fix issue
2 - change sign up flow.

**Comment by EugeOrtiz** [comment]
+1 to remove it from V1. This makes more sense when the app is available for a broader audience and metrics can help us make decisions.

**Comment by maxhora** [comment]
+1 for `change sign up flow.`
