### ISSUE TITLE
Clicking on Version number shouldn't log the user out

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4976]
When clicking in version number (under user's profile) I immediately get logged out from the application.

<img width="280" alt="captura de pantalla 2018-06-27 a la s 4 23 30 p m" src="https://user-images.githubusercontent.com/37297779/41994958-82c1fc20-7a26-11e8-9752-6589138bc3d5.png">

Expected behavior:
Only clicking on "Log out" should log the user out of the app, clicking on version number shouldn't do anything.

**Comment by churik** [comment]
Closed in #4978
