### ISSUE TITLE
Logout is missing confirmation dialog

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4977]
This wasn't specified before, but the "log out" functionality should have a confirmation dialog:

<img width="761" alt="captura de pantalla 2018-06-27 a la s 4 30 19 p m" src="https://user-images.githubusercontent.com/37297779/41995295-94cfabf0-7a27-11e8-8693-14d9efcf8ffb.png">

**Expected behavior:**
When user clicks on "Log out", a modal with a confirmation dialog should appear. If the user clicks on "Yes, log out", she should be redirected to the sign in screen. If user clicks on "Cancel", dialog modal should disappear, coming back to the previous screen.

Design (Zeplin) > zpl.io/bLOWk8Y

**Comment by churik** [comment]
blocked by https://github.com/status-im/react-native-desktop/issues/256

**Comment by vkjr** [comment]
https://github.com/status-im/react-native-desktop/issues/256 fixed now, so this probably can be unblocked.

**Comment by churik** [comment]
Still reproducible

**Comment by churik** [comment]
not stale
