### ISSUE TITLE
UI/UX fixes for User Profile (left panel)

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4986]
**Current implementation (June 28th) vs design:**
<img width="283" alt="captura de pantalla 2018-06-28 a la s 3 59 04 p m" src="https://user-images.githubusercontent.com/37297779/42055013-4aa962da-7aec-11e8-8497-c5aa9c84b968.png"><img width="287" alt="captura de pantalla 2018-06-28 a la s 3 59 36 p m" src="https://user-images.githubusercontent.com/37297779/42055021-4eeeff62-7aec-11e8-92b4-dd5ebe48fd73.png">

**LIST OF FIXES:**
- [ ] Left panel width should be 340px (fixed size), now is 280px:
<img width="289" alt="captura de pantalla 2018-06-28 a la s 4 10 07 p m" src="https://user-images.githubusercontent.com/37297779/42055523-c2a703e0-7aed-11e8-8b15-803fddfccc30.png">

- [ ] User name should be centered in left panel (now is aligned to the left)
- [ ] User pic is missing
- [ ] Review user name's font, size and weight (is small, bolder than it should, and not SF)
- [ ] "Share my contact code" button has odd grey lines around it:
<img width="278" alt="captura de pantalla 2018-06-28 a la s 3 59 04 p m" src="https://user-images.githubusercontent.com/37297779/42055120-966f4b08-7aec-11e8-9c5d-a2fdccaa22b5.png">

- [ ] "Share my contact code" button should be aligned in the center of the left panel:
<img width="283" alt="captura de pantalla 2018-06-28 a la s 4 12 31 p m" src="https://user-images.githubusercontent.com/37297779/42055639-196dc236-7aee-11e8-81bf-ff18c3eee202.png">

**Comment by churik** [comment]
Closed because Profile design is not implemented yet (created #4992  for developers) and issues with "Share contact code" button are related to PR #4908 (mentioned here and should be fixed in this PR)

**Comment by EugeOrtiz** [comment]
Good, thanks!
