### ISSUE TITLE
UI/UX fixes for top navigation bar

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4987]
**List of fixes:**

- [x] Plus button is missing blue style (losing hierarchy) **(High prio)**:
<img width="283" alt="captura de pantalla 2018-06-28 a la s 4 35 48 p m" src="https://user-images.githubusercontent.com/37297779/42056671-59363378-7af1-11e8-87d7-22555e92f198.png">

- [ ] Top navigation bar height should be 68px:
<img width="372" alt="captura de pantalla 2018-06-28 a la s 4 35 10 p m" src="https://user-images.githubusercontent.com/37297779/42056643-424058ec-7af1-11e8-913a-a9dd6034b023.png">

- [ ] Top nav bar width should be 340px (fixed width):
<img width="331" alt="captura de pantalla 2018-06-28 a la s 4 36 57 p m" src="https://user-images.githubusercontent.com/37297779/42056715-80621f5c-7af1-11e8-9b9f-df2852a4bc3c.png">

- [ ] Bottom divider color should be #EEF2F5 and should cover the entire width (340px):
<img width="282" alt="captura de pantalla 2018-06-28 a la s 4 51 06 p m" src="https://user-images.githubusercontent.com/37297779/42057412-993f9534-7af3-11e8-9707-ec15818d3036.png">

- [ ] The asset used as the "plus" white icon inside the blue button is not the correct one. Please, use the + asset ready to download from Zeplin. zpl.io/be4M3DP
<img width="68" alt="captura de pantalla 2018-07-03 a la s 5 13 28 p m" src="https://user-images.githubusercontent.com/37297779/42242565-b0109494-7ee4-11e8-91b5-05bc6c9b0d24.png">

- [ ] + button's right padding should be 16px (against right border):
<img width="555" alt="captura de pantalla 2018-07-03 a la s 5 31 33 p m" src="https://user-images.githubusercontent.com/37297779/42243262-2395b384-7ee7-11e8-81cd-dcbc2e4a6aa2.png">

**Comment by churik** [comment]
closed, because should be resolved in #4752 and you comment design there as well

**Comment by EugeOrtiz** [comment]
@churik I don't see these design comments on that issue that you mention. Also, I think that issue doesn't involve the top navigation with + button (as we talked with @siphiuel). I think we should keep this separately, otherwise the other issue is becoming super large and complex.

**Comment by churik** [comment]
Ok, let's keep it opened, but I don't think it is high-prio for now, because at least blue styling will be  added in  #4752.
Are you agree?

**Comment by churik** [comment]
Doesn't make sense in terms of #7551
