### ISSUE TITLE
Implement User Profile screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4992]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see nice profile screen with photo, options, etc

### Description

*Type*: Feature
*Summary*: implement user profile screen according to design zpl.io/25qZqB3

#### Expected behavior
User profile looks like here: zpl.io/25qZqB3

#### Actual behavior
![Uploading Prof.png…]()

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Go to "Profile"

*Summary*: 

- [ ] Add profile icon
- [ ] Left panel width should be 340px (fixed size), now is 280px.
- [ ] User name should be centered in left panel (now is aligned to the left)

### Additional Information
* Status version: [desktop build 29.06/2018](https://jenkins.status.im/job/status-react/job/desktop/job/manual/2/)

**Comment by vkjr** [comment]
@churik, is this one really `in progress`? If so, `assignee, revelio!` :)

**Comment by churik** [comment]
Yes, it is in #4908  PR.
