### ISSUE TITLE
Message history is overlapping when you have several chats with history>1 day (when switching between chats)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4995]
### Description
*Type*:  bug

*Summary*: when you switching between chats with several days history, messages from yesterday and earlier can be overlapping between different chats.
Blocked by  status-im/react-native-desktop#253.

#### Expected behavior
no overlapping

### Actual result:
"Today" disappears
messages from "Yesterday" are overlapping between chats
<img width="325" alt="m1" src="https://user-images.githubusercontent.com/4557972/42038824-895cf41c-7af4-11e8-814b-8a645248bee4.png">

### Reproduction

Steps:
*Requirements:* have 1-1 and public chat with history more than 1 day

1) log in
2) switch between chats with history>1 day (i.e. "Today" and "Yesterday")
3) check history in 1-1 chat

### Expected result: 
no overlapping

* Video: http://take.ms/yMabF
* Log: [StatusIm.log](https://github.com/status-im/status-react/files/2145576/StatusIm.log)

**NOTE**: if you switch to chat with "Today" messages only, and then to chat with several days history - you cannot see an issue until you switch to another chat with several days history.

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=O9DQQCeb6jB67iWQlGsftA45c0ISpL&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/O9DQQCeb6jB67iWQlGsftA45c0ISpL">File "screencast 2018-06-28 16-16-15.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by maxhora** [comment]
@churik this Issue should be re-validated against latest manual desktop build. Hopefully, shouldn't appear any more since https://github.com/status-im/status-react/pull/4578 is merged already.

**Comment by churik** [comment]
Is not reproducible  on [desktop, build 11](https://jenkins.status.im/job/status-react/job/desktop/job/manual/11/)

**Comment by churik** [comment]
Eventually reproduced on [desktop, build 11](https://jenkins.status.im/job/status-react/job/desktop/job/manual/11/)
Can be reproducible with two public channels, one has 1+ day history, second has 2+ day history (i.e., #status).
Steps:
- scroll up to chat with 2+ day history ;
- use pull-to-refresh in order to see history before yesterday;
- switch to chat with 1+ day history ;
- check "Yesterday" history 
Video:  http://take.ms/xNMOh


<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=cgeWtKaxjCvdSsHaRJhKd1fvNsJoo5&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/cgeWtKaxjCvdSsHaRJhKd1fvNsJoo5">File "screencast 2018-07-05 19-05-37.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by churik** [comment]
Cannot reproduce after merging #4752
