### ISSUE TITLE
Add KIN token to Wallet assets

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4999]
### Description

*Type*: Feature

*Summary*: Add support for `KIN` token to Status Wallet. 

### Expected behaviour
`KIN` is shown in Wallet -> Manage Assets and in Wallet itself (if addresss has the token). 

### Actual behaviour
Currently, the wallet shows only first 100 tokens from cryptocompare and the list does not include `KIN`.

### Reproduction

- Open Status
- Open Wallet
- Open options and select Manage Assets

### Additional Information
* Status version: 0.9.21
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb1e8f051ae88ea88548e380f1e007018fe64b054d87518c008d3f423250932d8](https://etherscan.io/tx/0xb1e8f051ae88ea88548e380f1e007018fe64b054d87518c008d3f423250932d8)

**Comment by Neurone** [comment]
@lukaszfryc This feature is present since 0.9.13 but you must be on the main network to see it. KIN tokens [was added last year](https://github.com/status-im/status-react/commit/2256628c97897c05064f8eb57687f69e2ca41c97) by @jeluard, you can assign the bounty to him 😃

**Comment by lukaszfryc** [comment]
thanks @Neurone!
