### ISSUE TITLE
Incorrect timestamp of last message in Home 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5000]
### Description

*Type*: Bug

*Summary*: 

Timestamp in Home screen shows time when a message was received but should show sent date instead:

<img src="https://user-images.githubusercontent.com/7532782/42095237-53045176-7bb2-11e8-8af2-8e77987ff15d.png" width="200">

The message was sent 3:32PM. The chat shows it correctly:

<img src="https://user-images.githubusercontent.com/7532782/42095281-72b3367c-7bb2-11e8-9fe5-9a4bd3852734.png" width="200">

#### Expected behavior
Timestamp of a chat in Home screen shows time of the last message (either sent or received).

#### Actual behavior
Timestamp shows time an incoming message was received. 

### Reproduction

- Open Status on 2 devices
- Create 1-1 chat between devices
- Kill the app on device 1
- Device 2: send a message to device 1
- Device 1: Open the app, login and wait to see the message in Home

### Additional Information
* Status version: 0.9.21
* Operating System: Android, iOS

**Comment by cammellos** [comment]
@lukaszfryc At the moment we show the time the last message received/sent by us, pretty sure is intentional ( we made a few changes to that code some time ago in a PR), should we change the logic to use the last message received timestamp? What should we display when there are no messages?

**Comment by lukaszfryc** [comment]
> At the moment we show the time the last message received/sent by us, pretty sure is intentional

For incoming messages, I think we should show timestamp of when the message was sent (not received). Of course if we can do it. @chadyj wdyt?
