### ISSUE TITLE
Nothing happens upon tap on links in app browser intended to open in new window [iOS] 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5014]
***Type***: Bug

***Summary***: Links in Dapps with target="_blank" attribute suppose to open link in new window. On iOS nothing happens upon tap on such links used in Dapp. 
E.g. of links: 
Oasis Direct dapp -> scroll to the bottom -> any of `Documentation`/`Legal`/`Oasisdex.com` links
CryptoKitties dapp -> at hte very top `Kitty Pride` / `Experimental`
DAI by Maker DAO dapp -> `BUY DAI` button

**Note**: Android app browser opens such link on the same window. 

#### Expected behavior
Redirect to respective URI happens upon a tap on links in-app browser with target="_blank" attribute

#### Actual behavior
Nothing happens upon tap on links in app browser intended to open in new window [iOS] 

### Reproduction
- Open Status **on iOS** and log in to account
- Navagate to `Open Dapp` -> `CryptoKitties` -> `Open`
- Tap upon `Kitty pride` or `Experimental` links at the very top of the Dapp home screen
- Navagate to `Open Dapp` -> `Oasis Direct` -> `Open`
- Scroll to the page bottom and tap any of `Documentation`/`Legal`/`Oasisdex.com` links

### Additional Information
* Status version: Release 0.9.21, Develop 0.9.21 (6148)
* Operating System:  iOS

#### Logs

TF session: https://app.testfairy.com/projects/4803590-status/builds/8512376/sessions/4395269580/?accessToken=KSCdEs7v3mDs-e-26M23bL5qENE

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8512376/sessions/4395269580/?accessToken=KSCdEs7v3mDs-e-26M23bL5qENE">TestFairy: Status 0.9.21 (6148) @2018</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
will be fixed here https://github.com/status-im/status-react/pull/4919
