### ISSUE TITLE
Oasisdex.com Dapp responds with 'Not connected to ethereum' when I open it from Android app browser

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5016]
### User Story

As a user, I want to open and browse oasisdex.com Dapp from Status app browser on Android device.

### Description

*Type*: Bug
*Summary*: Oasisdex.com Dapp could not detect Status as ethereum client and responses with the respective page notifying about Matamask/Mist installation in Android app browser. 
Redirect to oasisdex.com happens from `DAI by Maker DAO` Dapp we have already. Or simply requesting the oasisdex.com URL from `Open Dapp` screen. 

**Note**: oasisdex.com opens fine in iOS Status app browser.
 
#### Expected behavior
oasisdex.com could be opened from Status app browser on Android

#### Actual behavior
'Not connected to ethereum' for oasisdex.com in Android app browser

<img width="371" alt="screen shot 2018-07-02 at 14 09 00" src="https://user-images.githubusercontent.com/8749671/42162474-7e135360-7e07-11e8-985b-18bce2d21e85.png">

### Reproduction

- Open Status and log in to account under Mainnet network on Android device
- Navigate to `Open Dapp` -> `DAI by Maker DAO` -> `Open`
- Tap `BUY DAI` button

### Additional Information
* Status version: Release 0.9.21 / Develop 0.9.21 (6148) build
* Operating System: Android 6.0.1, Android 7.0, Android 8.0

#### Logs

TF logs: https://app.testfairy.com/projects/4803622-status/builds/8512167/sessions/4395274340/?accessToken=eJy0gRAz4Q6hTTyQecP/cevA9KI

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8512167/sessions/4395274340/?accessToken=eJy0gRAz4Q6hTTyQecP/cevA9KI">TestFairy: Status 0.9.21 (6148) @2018</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Still reproducible in the latest 0.9.29 Develop build

**Comment by jeluard** [comment]
@Serhy Does it work on iOS?

**Comment by Serhy** [comment]
@jeluard Yes, it does works iOS.

**Comment by Swader** [comment]
Still an issue. Confirmed on Android 9.0. Privacy mode has no effect.

**Comment by churik** [comment]
I can interact now with Oasis dapp (https://oasis.app) on Status v1.0.1
