### ISSUE TITLE
Implement display of message statuses 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5018]
### User Story

As a user, I want to see whether my message is Sent, Seen or not sent and resend if it attempt was unsuccessful.
### Description

*Type*: Feature

*Summary*: 
* in 1-1 Chat : 
1) Sent - [design](https://zpl.io/Vkml10Z)
2) Seen   
3) Not sent, Tap for options - [design](https://zpl.io/VqEOzY4)
* in Public Chat:
1) Sent - [design](https://zpl.io/Vkml10Z)
2) Not sent, Tap for options - [design](https://zpl.io/VqEOzY4)

**Comment by chadyj** [comment]
Closed in https://github.com/status-im/status-react/pull/5318
