### ISSUE TITLE
Battery life regressed in Beta

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#5022]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

In Beta, our Android users found out that the battery life is not as good as, say in 0.9.19 release.

### Description

Most probable reason for that is a regression introduced by React Native upgrade to 0.55.4.

A symptom that follows that regression is the keyboard being laggy when typing many long messages (over 10 words) at once in the chatroom.

*Type*: Bug

### Additional Information
* Status version: 0.9.21 (beta)
* Operating System: Android only

**Comment by lukaszfryc** [comment]
Removing "release" label since this is not a blocker for upcoming release. Performance was (temporary) fixed by downgrading RN.
