### ISSUE TITLE
Option to use ENS address instead of contact code

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5028]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to add a contact with their ENS address so that I don't need to use the cumbersome whisper contact code.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Soon users will be able to register ENS addresses inside Status, so we want to make ENS available everywhere in the app including adding a contact.

#### Expected behavior
New > Start New Chat > Enter ENS address to chat with a contact

#### Actual behavior
Error message saying "please scan a valid contact code"

### Solution

- Change label text from "Enter contact code" to "Enter contact code or username"
- For an ENS address do a lookup and see if there is a valid Status pubkey
- Adapt error message if pubkey not found
- Require user to type in full address (e.g. `Rachel` does not automatically resolve to `rachel.stateofus.eth`)

<img width="318" alt="ens_resolution" src="https://user-images.githubusercontent.com/116099/42212849-96414e5a-7eb7-11e8-9eac-4d98ebc0e06a.png">
(eg allow for entering in usernames. illustration only :))

**Comment by bgits** [comment]
What would you need from the ENS swarm to read directly from the contract. ABI?

**Comment by flexsurfer** [comment]
hey @bgits yes, ABI should be enough , and method name and params

**Comment by bgits** [comment]
@flexsurfer You can see how we use methods from `PublicResolver` here: https://github.com/status-im/contracts/blob/151-ens-usernames/app/components/ens/nameLookup.js#L184

EmbarkJs gives us a nice interface to use, perhaps you can leverage that.

If you prefer can just generate a JSON.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/contracts">status-im/contracts</a></strong></div><div>Contribute to contracts development by creating an account on GitHub.</div></blockquote>

**Comment by jeluard** [comment]
@chadyj @yenda Can we close this?
