### ISSUE TITLE
Public chat shows double "#" in name 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5031]
### Description

*Type*: Bug

*Summary*: "##" is shown in the options dialog (both on Android and iOS):

<img src="https://user-images.githubusercontent.com/7532782/42217671-60700a50-7ec6-11e8-9de3-ddd2bffa042e.png" width="200">

#### Expected behavior
"#status"

#### Actual behavior
"##status"

### Reproduction

- Open Status
- Open "#status" chat
- Open chat options menu

### Additional Information
* Status version: nightly, July 3
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 5500.00
Contract address: [0x1bcc47901fdaaa09c1693698b06b4647ddce3766](https://etherscan.io/address/0x1bcc47901fdaaa09c1693698b06b4647ddce3766)
Network: Mainnet
Paid to: kdeme
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
