### ISSUE TITLE
Recovered account sees default username instead of custom name

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5036]
### Description

*Type*: Bug

*Summary*: After account is recovered, an other user needs to update their name in profile before the recovered account can see it. Without it, the default name is always shown. This happen when recovered account was on latest version of the app and the other user used 0.9.20 (or older). The issue still even when the other user updates latest version.   

#### Expected behavior
When account is recovered and an old contact is added again, the recovered account sees the custom name of the contact. 

#### Actual behavior
When account is recovered and an old contact is added again, the recovered account sees the default name of the contact.

### Reproduction

- Device A: Installs 0.9.20
- Device B: Installs this PR build
- Device A and B: Adds each other as contacts
- Device B: Backups the seed and uninstalls the app
- Device B: Recovers the account
- Device A: Sends a message to device B. Device B receives it but the sender has default name. If "Add to contact" is clicked, the name updates on Device A.
- Device A: Upgrades to 0.9.21 and sends another message to Device B. Device B still sees the default username
- Device A: Updates the username. Device B: now the updated name is shown

### Additional Information
* Status version: introduced in https://github.com/status-im/status-react/pull/4847
* Operating System: Android, iOS

**Comment by churik** [comment]
Is it not the same https://github.com/status-im/status-react/issues/4573?
