### ISSUE TITLE
Add custom URL scheme to status-desktop

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5038]
### User Story

As a user in want to open universal links directly in my status-desktop app.

### Description

*Type*: Feature

*Summary*: The goal is to eliminate any friction to opening up Status. No more copy/pasting long contact codes, or cumbersome instructions (Open Status, tap Home, then New, then ……..). 
Description of universal links is [here](https://wiki.status.im/Universal_Links). 
Pull request on mobile side: #4944 

### Solution

*Summary*: 

Clicking these links should open Status and deep link to a chat or contact

- [status-im://chat/public/status](status-im://chat/public/status)
- [status-im://user/0x044166fa04e967e333211ae0cc1087c9c74exxx](status-im://user/0x044166fa04e967e333211ae0cc1087c9c74exxx)

**Comment by chadyj** [comment]
Should also work with a custom URL scheme

`In addition to the deep links the above links can be called with the status-im:// custom URL scheme, such as status-im://chat/public/status `

The types of links to test would be:


status-im://chat/public/status

status-im://user/0x044166fa04e967e333211ae0cc1087c9c74exxx

**Comment by gnl** [comment]
Universal links are sadly not supported on macOS, we can only use the `status-im://` URL scheme. #5785 adds basic support, but without any deep-linking for now – that will probably require additional work from the native team.

**Comment by chadyj** [comment]
Thanks @gnl.  Updated the issue to just be about custom URL schemes.

We want these 2 links to work:

status-im://chat/public/status

status-im://user/0x044166fa04e967e333211ae0cc1087c9c74exxx

**Comment by chadyj** [comment]
From Slack:

> 
> George Lipov [3 days ago]
> It would be great if the API was eventually consistent with mobile:
> https://facebook.github.io/react-native/docs/linking
> ..it should be very little work on the ClojureScript side to do this then, because we can likely reuse all code from mobile.
> 
> Max Risuhin [3 days ago]
> @gnl thanks for the link, haven't expected that react-native has special module exactly for this. Then we just need to implement the same if it's not yet there.

<blockquote><img src="/react-native/img/favicon.png" width="48" align="right"><div><strong><a href="https://facebook.github.io/react-native/index.html">Linking · React Native</a></strong></div><div><div class="banner-crna-ejected"></div></blockquote>

**Comment by dmitryn** [comment]
I'm working on it at branch https://github.com/status-im/status-react/tree/feature/deep-linking

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by chadyj** [comment]
🍺 🍻🍺 🍻🍺 🍻🍺 🍻🍺 🍻🍺 🍻🍺 🍻🍺 🍻
Kudos @dmitryn!
