### ISSUE TITLE
"Send" button is not disabled in transaction request after sending transaction 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5048]
### Description

*Type*: Bug
*Summary*: when you send transaction as a response to another user `/request` command, "Send" button should become disabled. Now it is still active and you can tap on it again.

#### Expected behavior
"Send" button is disabled

#### Actual behavior
"Send" button is enabled
![fgdfg](https://user-images.githubusercontent.com/4557972/42276027-dbad1a94-7f9a-11e8-924b-db87fa4ef6a4.png)

### Reproduction

*Preconditions:* User A and User B are contacts and have a chat;

- as User A: in 1-1 chat with User B send `/request` 
- as User B: in 1-1 with User A tap on Send
- as User B: sign transaction, click on Got it to get back to chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 04/07/2019 (0.9.21 (6157) node a339d7e)
* Operating System: Android, iOS

#### Logs

* TF session (01:00 - 01:30): https://app.testfairy.com/projects/4803622-status/builds/8514788/sessions/4395442033/?accessToken=GkRByRS3cLWHeczenGNvkV5sPBU

**Comment by annadanchenko** [comment]
Can't reproduce on July 26 nightly https://jenkins.status.im/job/status-react/job/nightly/522/
tried requesting of ETH and STT. Sent is shown after using Send button and sending requested funds. button becomes disabled as expected after it was used.

My testing: https://app.testfairy.com/projects/4803622-status/builds/8537431/sessions/4397170748/?accessToken=ccVACeXXOagw-oodsS1C0lnvEYA

**Comment by churik** [comment]
Still reproducible with ETHro on Ropsten network, however works fine with real ETH on mainnet and tokens on Ropsten.
