### ISSUE TITLE
Google Play says Status app is incompatible with BlueStacks v3.52.67.1911 (Android v4.4.2).

### ISSUE THREAD

**Issue by antdude** [status-im/status-react#5059]
In my installed BlueStacks v3.52.67.1911 (Android v4.4.2; https://www.bluestacks.com/) in my decade old updated 64-bit W7 HPE SP1 desktop PC, I was unable to install 7/4/2018 Status app from https://play.google.com/store/apps/details?id=im.status.ethereum&hl=en due to its incompatibility error as shown below in my screen shot/capture:
![bluestacks3](https://user-images.githubusercontent.com/998681/42291845-2a06ef48-7f83-11e8-857d-8ee6d18133c3.gif)
![bluestacks3incompability](https://user-images.githubusercontent.com/998681/42291846-2a2392d8-7f83-11e8-9a8e-80b90a9d5da9.gif)

<blockquote><img src="https://cdn-www.bluestacks.com/bs-images/social_network_image.jpg" width="48" align="right"><div><img src="https://cdn-www.bluestacks.com/bs-images/favicon.png" height="14"> Bluestacks - The Best Android Emulator on PC as Rated by You</div><div><strong><a href="https://www.bluestacks.com/">Bluestacks - The Best Android Emulator on PC as Rated by You - Join 200+ million users on the largest, FREE Android Gaming Platform on PC and Mac. Play Clash, Vainglory, Seven Knights + more.</a></strong></div><div>Join 200+ million users on the largest, FREE Android Gaming Platform on PC and Mac. Play Clash, Vainglory, Seven Knights + more.</div></blockquote>

**Comment by annadanchenko** [comment]
Not a bug because minimal supported Android version is Android 6.0 
see https://github.com/status-im/status-react/issues/4651

**Comment by antdude** [comment]
Thanks.
