### ISSUE TITLE
Bump version to 0.9.22

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5060]
### Description

*Type*: Bug

*Summary*: Bump version name in Profile screen from 0.9.21 to 0.9.22. It's done in https://github.com/status-im/status-react/blob/release/0.9.22/VERSION. See PR with previous bumps  like https://github.com/status-im/status-react/pull/4812

### Reproduction

- Open Status
- Open Profile
- See version name

### Additional Information
* Status version: 0.9.22
* Operating System: Android, iOS

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by chadyj** [comment]
When we do this we should also update CHANGELOG.md too
