### ISSUE TITLE
Backup Seed Phrase screen does not correctly fit on screen, gets cut on top and on the bottom. 

### ISSUE THREAD

**Issue by luigar** [status-im/status-react#5071]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

Type: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Backup Seed Phrase screen is incorrectly displayed it get partly cut on top and on the bottom.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Picture and button "Ok, continue" should fit in screen.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Picture and button "Ok, continue" are partly cut from the top and the bottom.

![screenshot_20180704-231059](https://user-images.githubusercontent.com/1890179/42350856-1a8ca582-8067-11e8-8263-62d18201e76a.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Enter Account Password and click Sign In
- Click on Profile Icon/Button
- Click on "Backup your Seed Phrase"

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21
* Operating System: Android 6.0.1
* Cel Phone and Model:  Galaxy J7 Prime SM-C610M

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by lukaszfryc** [comment]
One more user has just reported it on Instabug.
