### ISSUE TITLE
Support non-ascii characters in universal links

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5074]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to join "status 日本語" via a universal link so that I can easily join and chat with my local community.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

For security we disabled non-ascii support for universal links https://github.com/status-im/status-react/pull/5037/commits/db3706493724e0517aafa1a21ab0e386e08c3b6c

But our marketing and community team needs these links to foster non-english communities and make it easy for users to join.

#### Expected behavior
Users can join public channels like "status 日本語" with a universal link

#### Actual behavior
Can't join

### Reproduction

See https://github.com/status-im/status-react/pull/5037#issuecomment-402266738

### Additional Info

We are aiming to introduce in 0.9.23 and at the same time shift the community discussion from Riot to Status so great to get this done for that release.

**Comment by yenda** [comment]
we should only allow punicode though

**Comment by chadyj** [comment]
The better solution (at least in the short term) is to change the channel names from "status 日本語" to "status-nihongo" or "status-japanese".
