### ISSUE TITLE
Browsing history is not saved after contact re-login to account

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5079]
***Type***: Bug

*Summary*: We keep browsing history when a user navigates through different pages in Dapps/websites. However, once contact re-logins to account browsing history is flushed and only latest navigated URI is kept.
It would be nice to keep the browsing history per Dapp even after re-opening of Status app.

#### Expected behavior
Browsing history is kept after contact re-logins to account

#### Actual behavior
Browsing history is cleared per Dapp after contact re-logins to account

### Reproduction

- Open Status and log in to account
- Navigate to Open Dapp -> type `google.com` -> and hit 'GO' button
- Search any keyword and navigate to any link from results
- Tap `Back` browser button 
- Close browser view via top-left `X` button (**Note**: at this point, we have kept browser history - user is able to navigate back and forth if to return back to 'google' record again from Home screen). 
- Close the app
- Open the app and log in to the same account  
- Navigate to google from the Home screen
- Check whether you are able to navigate Back/Fwd through the history you had before closing the app

### Additional Information
* Status version: Develop 0.9.21 (6168) node a339d7e
* Operating System: Android and iOS

#### Logs

TF session with logs: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-784bc2-n-fl.apk

**Comment by rasom** [comment]
This has never beed considered as a feature before so it's hard to say that this is a bug IMO

**Comment by Serhy** [comment]
That's fair remark, @roman, agree. 
This is a “dept” from #3639 feature request that we decided to implement separately. So like a `bug/feature` :)
Changed to `feature`.
