### ISSUE TITLE
Can't create an account on iOS

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#508]
<img width="487" alt="screen shot 2016-11-29 at 16 29 13" src="https://cloud.githubusercontent.com/assets/911127/20712455/2223f710-b655-11e6-9d2d-28e2f294b7d6.png">

Sometimes everything works fine, but sometimes I see this red screen right after I enter my password.

**Comment by rasom** [comment]
That's related to `network` property, it is fixed in `ios-archive`
