### ISSUE TITLE
Provide support for custom react-native-desktop branches in Jenkins builds

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#5081]
**Problem**:
Currently it's not possible to build `desktop` branch against a particular `react-native-desktop` branch.

**Solution**:
One workaround as suggested by @MaxRis is creating ad-hoc branches forked from `desktop` changing `react-native-desktop` repo URL in `package.json`.

However, it would be better if job config included a string parameter designating the target `react-native-desktop` branch that `desktop` should be built against. This implies running a `sed` script performing string substitution inside `package.json` before the build starts.

**Comment by churik** [comment]
Not a priority anymore
