### ISSUE TITLE
[MERGE] Use different package.json/re-natal config for desktop and mobile

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#5082]
**Problem**:
The following node modules have different versions in `develop` and `desktop` branches:
 - react-native
 - react-native-i18n
 - react-native-config
 - react-native-fs
 - react-native-http-bridge
 - react-native-webview-bridge
 - react-native-keychain
 - react-native-securerandom

It might be quite complicated to synchronize the versions of those modules, so a simpler approach is needed.

Also, re-natal config files `.re-natal` are different across branches.

**Solution**:
Use a helper script that will configure `package.json` and `.re-natal` depending on the target platform.

**Comment by vkjr** [comment]
Merge is done, so this one can be closed.
