### ISSUE TITLE
[MERGE] CLJS parameterization depending on platform

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#5085]
**Problem**:
CLJS code has been modified in `desktop` branch, in particular:
  - `status-im.react-native.js-dependencies` ns had some components commented out.
  - `status-im.ui.components.icons.vector-icons` was changed on `desktop` to use Qt's built-in functionality
  - maybe some more

**Solution**:
Parameterize these code sections by wrapping them inside `(if platform/desktop?)` expressions. In cases of commented out dependencies, check if including them back will not present issues.

**Comment by vkjr** [comment]
Merge is done, so this one can be closed.
