### ISSUE TITLE
Login with "I already have an account" needed validation or additional instructions

### ISSUE THREAD

**Issue by juliomvr** [status-im/status-react#5091]
### Description

*Type*: Bug

*Summary*: 
When login clicking the "I already have an account" button using correct passphrase and password is not working, it creates a new wallet instead of recovering wallet and funds.

There is a workarround for this, instead of writing all 12 phrase words separated by a space, try typing the 12 words clicking "enter" for each word(new line for each one) and this way the login does work.
#### Expected behavior
The Recover account option should work when the 12 phrase words are typed line by line or separated by space

#### Actual behavior
The recover account option only works when you type the 12 phrase words one by line, it should also work when the 12 phrase words are separated by spaces

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status IM
- Click "I ALREADY HAVE AN ACCOUNT" button
- Enter your 12 phrase words separated by space
- Enter correct password
- Click "SIGN IN" button

### Solution
*Summary*: 
- [ ] The 12 phrase words should be accepted when typed separated by space also
OR
- [ ] The instructions should specify that all 12 phrase words should be typed one per line

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21
* Operating System: Android 7.0
* Device : Samsung Galaxy J3
* Model: J327

**Comment by annadanchenko** [comment]
@juliomvr can you provide exact passphrase in both formats and screenshots or video for the issue, please? So, it's visible that there are no typos in the passphrase used and what is the contact code for recovered account.

I tried to reproduce it on version 0.9.21 (6130) version on Samsung Galaxy S6, Android 6.0.1 and got same account recovered for both formats. For both recovered accounts public key/contact code is `0x04b1d6b42e073016f41a90cf962b21cb54a53fa15de1132e980c7b3593675dcaa783fbdbb401cbb09bbd11cd943bad196ebe2ee0937dcd0afd02d19c0344b035f5`
1. When words are separated by space. Phrase: fence garden wolf about reunion jungle fix cereal ozone public waste poverty
2. When words are separated by new line. Same phrase: 
fence 
garden 
wolf 
about 
reunion 
jungle 
fix 
cereal
ozone 
public
waste
poverty
Here are mine videos where issue can't be reproduced:

One line with spaces:
![onelinefin](https://user-images.githubusercontent.com/6584810/42449910-bfb19ee6-8382-11e8-9425-a95d5dbd7204.gif)

Multiple lines:
![multilinefin](https://user-images.githubusercontent.com/6584810/42450003-0dc75a62-8383-11e8-883e-4b3267746afb.gif)

**Comment by juliomvr** [comment]
Hello  @annadanchenko ,

I retested this again and now realized I had a mistake during the issue report,  after doing the recovery instead of checking the contact code what I checked was the wallet funds and saw my total funds were USD$0 but the thing is I forgot to switch to Ropsten network, now I did and my funds are there.

In conclusion, there is no issue, sorry

**Comment by annadanchenko** [comment]
ok, thank you for rechecking it :) I'm closing the issue then
