### ISSUE TITLE
"OTHER ACCOUNTS" button disappear after first click

### ISSUE THREAD

**Issue by juliomvr** [status-im/status-react#5093]
### User Story

As a user, I want to have the same user experience every time I come back to the same screen, "Sign in to Status" window in this case.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarize the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
When opening the Status app there is a button with text "OTHER ACCOUNTS", if you click this button and then select one account the app will redirect to the same window but the button won't appear anymore.

![image](https://user-images.githubusercontent.com/25910226/42403273-12595e36-814e-11e8-822e-0948cddaf70a.png)

![image](https://user-images.githubusercontent.com/25910226/42403293-344db3ca-814e-11e8-9d28-9f66767cc29d.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Every time you are on the "Sign in to Status" window the "OTHER ACCOUNTS" button should be there.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The "OTHER ACCOUNTS" button only shows when the app is opened, once you click that button and then come back to the same screen it is not shown anymore.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status app
- Click on "OTHER ACCOUNTS" button
- Select any account
- Search for the button, it isn't there

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21 
* Operating System: Android (7.0 and 8.1)
* Device: Samsung Galaxy J3 and Google Pixel 2 XL

**Comment by annadanchenko** [comment]
@denis-sharypin @andmironov was there special intention to not show Other accounts or we should consider it as a bug?

**Comment by denis-sharypin** [comment]
@annadanchenko  no there is no special intention regarding this. Let's fix it! Thanks, good catch! @juliomvr
