### ISSUE TITLE
No padding in Profile when username>~30 chars

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5098]
### Description

*Type*: Bug
*Summary*: when username contains several words or username is long (around or more 30 chars),it is displayed without padding and text doesn't wrap by words

#### Expected behavior
1) center align
2) padding (same as for Log Out)
3) ... if name is more than 3 rows

#### Actual behavior
![monosnap 2018-07-09 12-58-32](https://user-images.githubusercontent.com/4557972/42444133-037b9cd6-8378-11e8-987d-58b828ad0d6f.png)

### Reproduction

- Open Status
- Sign Up
- on "Name" enter name > 30 chars 

### Additional Information

* Status version: status desktop 09/07/2018
* Operating System:Mac OSx High Sierra

**Comment by churik** [comment]
@EugeOrtiz would you mind providing examples of how it should be when the username is long and contains several or one words?

**Comment by EugeOrtiz** [comment]
Yes, here it is >> zpl.io/2vY99kP (Zeplin):

<img width="918" alt="captura de pantalla 2018-07-09 a la s 12 15 32 p m" src="https://user-images.githubusercontent.com/37297779/42459313-ceef7dee-8371-11e8-9e70-92fe4c05f996.png">
