### ISSUE TITLE
"Share my contact code" should be displayed in popup

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5099]
### Description
_Type_: Feature

_Summary_: according to "Share QR code" designs (zpl.io/25qZqB3, zpl.io/bAqjqPO, zpl.io/VxY83em) qr-code is located in separate popup window.
It was blocked due to status-im/react-native-desktop#258 (should be unblocked now)

#### Expected behavior
![image](https://user-images.githubusercontent.com/4557972/42445114-c3ebec58-837a-11e8-9076-4b0b33a2591e.png)

#### Actual behavior
![now](https://user-images.githubusercontent.com/4557972/42445282-5086a518-837b-11e8-819d-3e57f44afb81.png)

### Reproduction

* Open Status
* Sign Up
* Open Profile
* Click on Share my contact code

### Solution

* [ ] - implement popup
* [ ] - add close button

### Additional Information

* Status version: status desktop 09/07/2018
* Operating System:Mac OSx High Sierra

**Comment by churik** [comment]
Still reproducible

**Comment by churik** [comment]
still relevant

**Comment by adambabik** [comment]
This is actually not a current behaviour, it's worse. I can only see a QR code and can't get back. I can't copy my address at all as it's not displayed.
