### ISSUE TITLE
Offline inboxing doesn't work under Mailservers A, B and C with the Ropsten network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5100]
***Type***: Bug

*Summary*: Users connected to any of `Status Mailservers A`, `Status Mailservers B` or `Status Mailservers C` with the **Ropsten** network keep getting 'Failed to connect to mailserver. Tap to reconnect'. Offline inbox for this settings doesn't work.

Note: it's all **fine on Mainnet** for any mailserver (including A B and C), but fails for Ropsten. Node version for app build is a339d7e

Note2: recently we fixed the issue with Mailservers A B and C with the https://github.com/status-im/status-react/commit/96628caa9ede2f9eca8405b84c792f3134245833 update. 

#### Expected behavior
Offline inbox works for Mailservers A, B and C when a user connected via Ropsten network

#### Actual behavior
Offline inboxing doesn't work under Mailservers A, B and C with the Ropsten

### Reproduction

- Open Status and create new account
- Navigate to Profile -> Mailserver -> set any of mailservers A / B / C
- Navigate to Profile -> Network -> connect to 'Ropsten with upstream RPC' network
- Log in to the same account and join '#status' public channel
- Check that chat history got fetched and appears for public chat you joined 
- Wait +1.5 minute staying on chat screen/Home screen
- Check there is no `Could not connect to mailserver. Tap to reconnect` label appears at the top of the screen
- _(Optional)_ Now switch account to `Mainnet with upstream RPC` network and re-login to the same account. Stay +1.5 minute to check whether there is no `Could not connect to mailserver. Tap to reconnect` notification.

### Additional Information
* Status version: Develop 0.9.21 (6181) node a339d7e (jenkins nightly 486th build from 9th of July)
* Operating System: Android and iOS

#### Logs

See TF logs and geth.log for above scenario on Android session: https://app.testfairy.com/projects/4803622-status/builds/8518521/sessions/4395882172/?accessToken=T1nd47FPhE6sJdGWq65nmSAbWu4

Geth.log above TF session:
[gethlog.log](https://github.com/status-im/status-react/files/2176061/gethlog.log)

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8518521/sessions/4395882172/?accessToken=T1nd47FPhE6sJdGWq65nmSAbWu4">TestFairy: Status 0.9.21 (6181) @2018</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
The servers for both networks - Ropsten and Mainnet - Are exactly the same, use the same ports and the same enode addresses. The fact that the latter works while the former doesn't indicates to me that the issues is not with the infrastructure but rather with implementation of either `status-go` or `status-react`.

**Comment by jakubgs** [comment]
Oh wait, no, the update done in https://github.com/status-im/status-react/commit/96628caa9ede2f9eca8405b84c792f3134245833 did not include a fix for the `testnet`, since it's the same fleet! I'll make a PR.

**Comment by jakubgs** [comment]
Here you go: https://github.com/status-im/status-react/pull/5167

**Comment by jakubgs** [comment]
The fix has been tested and merged.
