### ISSUE TITLE
Apply design for selectable text

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5103]
### Description
*Type*: Feature

*Summary*: apply design from zpl.io/V18jyew (Zeplin), when user selects some part of message to copy it. 

#### Expected behavior
<img width="719" alt="captura de pantalla 2018-07-07 a la s 4 59 21 p m" src="https://user-images.githubusercontent.com/37297779/42414232-1f332ccc-8207-11e8-9336-bb36e3bbcb90.png">

#### Actual behavior
![too contr](https://user-images.githubusercontent.com/4557972/42311573-d5a7da4c-8046-11e8-9800-096f98516a41.png)

### Reproduction

- Open Status
- Sign Up
- Join any public chat
- Select part of message

### Additional Information
* Status version: desktop build 09/07/18 (after merge https://github.com/status-im/status-react/pull/5032)
* Operating System: Mac OsX High Sierra

**Comment by EugeOrtiz** [comment]
This should also happen in these cases:

1. Messages (this issue already described above) 
2. Sharing contact code  (**High prio**)
3. User profile card - Contact code
4. When writing a message
5. New public chat - Input field
6. New 1:1 chat - Input field

![text selection cases](https://user-images.githubusercontent.com/37297779/42463769-73c8e9da-837d-11e8-9196-1ee708c9b6ad.png)

As a general rule: "dark" (light blue) highlight over white backgrounds, "light" (white) highlight over darker backgrounds. 
Designs here >> zpl.io/2pOGExj (Zeplin)

@churik let me know if 2) needs to be a new -high prio- issue.

**Comment by EugeOrtiz** [comment]
[UPDATE] It looks even weirder now (dark highlight over black text):

<img width="307" alt="captura de pantalla 2018-07-12 a la s 4 23 32 p m" src="https://user-images.githubusercontent.com/37297779/42654719-fa32bbe4-85ef-11e8-971e-68d1663b085c.png">

**Comment by rcullito** [comment]
@MaxRis or @vkjr do you have any ideas on this? It looks like an inline alteration of `selection-color` won't do the update here. Seems like this might be a good opportunity to do in `react-native-desktop` if we don't have support yet? Thanks!

**Comment by vkjr** [comment]
@rcullito, we already have support for `selectionColor` property of Text in `react-native-desktop`. So all we need is just add `selectable: true` and `selectionColor: ....` in all the places :)

**Comment by rcullito** [comment]
thanks for chiming in @vkjr ! I've tried with `selection-color` inline on the text (in addition to selectable: true)  but have been unable to alter it as desired. Since the selection color is already being set to dark purple for desktop it seems like we must already be setting the default somewhere?

**Comment by vkjr** [comment]
@rcullito, dark purple goes from qt internals

**Comment by vkjr** [comment]
Will take this while @rcullito is unavailable.

**Comment by chadyj** [comment]
I wouldn't say this is urgent. Great to wrap it up quickly and move on :)
