### ISSUE TITLE
Layout issues in chat list during frequent updates

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#5104]
**Description**:
The problem is reproduced when adding new public channels. Once public channel data start arriving, last message content/timestamp UI elements update frequently, and at some point the layout becomes broken (note timestamp label shifted to the left in the video). However, if user switches tabs and goes back again, the problem disappears.

Related to issue #14 in https://github.com/status-im/status-react/pull/4752.

Attachment: https://monosnap.com/file/EGYMCZ6ELN2n9FDYYvJKfs6bjypSYV

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=EGYMCZ6ELN2n9FDYYvJKfs6bjypSYV&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/EGYMCZ6ELN2n9FDYYvJKfs6bjypSYV">File "screencast 2018-07-09 16-55-09.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

Possible hint: during public chat loading last message label/timestamp are updated several times in a row, as messages are being fetched. Maybe this has got something to do with the cause of the problem.

Update: seems that the problem with unviewed messages indicator might be related (#5156 ), see https://monosnap.com/file/xWdglsaK50CGNAWsSMyMww37gtgGv0.

**Comment by churik** [comment]
Doesn't make sense in terms of #7551
