### ISSUE TITLE
Invalid Name used in 1-1 Chat after starting chat reading Contact Code Image

### ISSUE THREAD

**Issue by luigar** [status-im/status-react#5106]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:   2 Accounts were created on real devices.
a) 
Status version: 0.9.21
Operating System: Android 6.0.1
Cel Phone and Model: Galaxy J7 Prime SM-C610M

b)
Status version: 0.9.21
Operating System: Android 7.0
Cel Phone and Model: Galaxy J7 Prime SM-610M

Account on (A) was renamed to Luis Garcia
Account on (B) was renamed to Luis Test

Account B Started a 1-1 Chat with Account A by reading Accounts A contact code image, from this point a new chat opens but it shows on Account B's chat that Accounts A's name is "Impractical Passionate Hart" while on Account A, Accounts B's name is Luis Test. 

Also when viewing the user profile on Account B's that Accounts A's name is "Impractical Passionate Hart"

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Correct name should be shown on both sides of the 1-1 Chat after rename.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The Contact Code for Accounts does not seem to be updating after name change and keeps original name when reading image to start chat.

View from Device A
![screenshot_20180705-174548](https://user-images.githubusercontent.com/1890179/42458912-a41cc6ac-834f-11e8-823c-dbeb69d176f6.png)

View Device A Profile from Device B
![photo from luis garcia](https://user-images.githubusercontent.com/1890179/42459043-e4b6a764-834f-11e8-9fc7-572598390b9c.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

These steps consist of using 2 devices.

- Open Status
- Create a New Account and Login
- Rename New Account
- Click on Profile
- Click on Share My Contact Code and wait for scan from other device.
#
- On a Different Device
- Open Status and Login
- Go to Home Screen
- Click on the "+" Icon to Start New Chat
- Click on Start New Chat
- Click on Contact Code Image to scan image
- Scan Image from the other device were you created new account

### Additional Information
[comment]: # (Please do your best to fill this out.)
2 Devices were used

a) 
Status version: 0.9.21
Operating System: Android 6.0.1
Cel Phone and Model: Galaxy J7 Prime SM-C610M

Device A Contact Code

![screenshot_20180709-110724](https://user-images.githubusercontent.com/1890179/42459274-3c5ae016-8350-11e8-9c85-f70c32357e62.png)

b)
Status version: 0.9.21
Operating System: Android 7.0
Cel Phone and Model: Galaxy J7 Prime SM-610M

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by cammellos** [comment]
@luigar Thanks for opening the issue.

If I understand correctly account `A` never added the contact back, is that correct?

We only share contact information in 2 cases: 

1) `A` starts chatting with `B` , in that case `A` information is shared with `B`, but **not the other way around** . This is to preserve privacy of `B`, who has never acknowledge to share information.

2) `A` adds `B` as a contact (or viceversa). In this case again `A`'s information will be shared with be `B`, **but not viceversa**, same reason as before, preserving `B`'s privacy who never acknowledge wanting to share information with `A`.

In your case you should see on `A`'s phone in the chat a link (`Add to contacts`), if you click on it you should see `A`'s information on `B`.

If that's not the case then it is a bug and we will look into it, otherwise let me know and I will close the issue.

**Comment by luigar** [comment]
That is correct A never added the contact back.

Only B added A by reading the code image, And B Spoke to A but A did not write back will validate that point.
But checking A's Chats there is/was no link to "Add to contacts"

**Comment by cammellos** [comment]
Just to make sure:
1) If you open on A's phone the 1-to-1 chat with B you don't see `Add to contacts`? Could you send me a screenshot of that chat + a screenshot of `B`'s profile from phone `A`?

Also replying to a message does not disclose your info, only starting a chat does.
Thank you!

**Comment by luigar** [comment]
After verifying on Chat A there is a Link to Add to Contacts seems that the times i verified it coincided with "fetching" or "connecting" i get these messages very often.

This might be a good update to make it more visible and less hidden behind certain popups.

![screenshot_20180709-122423](https://user-images.githubusercontent.com/1890179/42463058-eba9a6de-8359-11e8-8b7e-0acef55b24fd.png)
