### ISSUE TITLE
Joining a Group Chat Brought history from before the user entered it.

### ISSUE THREAD

**Issue by luigar** [status-im/status-react#5107]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:   2 Accounts were used on real devices, for comparison.
a) 
Status version: 0.9.21
Operating System: Android 6.0.1
Cel Phone and Model: Galaxy J7 Prime SM-C610M

b)
Status version: 0.9.21
Operating System: Android 7.0
Cel Phone and Model: Galaxy J7 Prime SM-610M

Account on (A) entered #status español chat on July 4th
Account on (B) entered #status español chat on July 5th

While Account B Entered on the 5th it shows the chat history for the 4th, while Account A shown no such history.

Screen from Account A

![screenshot_20180709-112011](https://user-images.githubusercontent.com/1890179/42459733-281940ec-8351-11e8-8d7d-5b019375ea7e.png)

Screen from Account B

![img-20180709-wa0002](https://user-images.githubusercontent.com/1890179/42459738-2a41d488-8351-11e8-82b5-37a7fdfe9c35.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Chat should start clean from the moment of entry.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Account B brought history from a chat from a time he was not subscribed to.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- On a Different Device
- Open Status and Login
- Go to Home Screen
- Click on the "+" Icon to Start New Chat
- Click on Join Public Chat
- Click on Desired Chat, in my case #status español 

This does not seem to be a constant error, i used 2 devices and it only happened on 1 device.

### Additional Information
[comment]: # (Please do your best to fill this out.)
2 Devices were used

a) 
Status version: 0.9.21
Operating System: Android 6.0.1
Cel Phone and Model: Galaxy J7 Prime SM-C610M

b)
Status version: 0.9.21
Operating System: Android 7.0
Cel Phone and Model: Galaxy J7 Prime SM-610M

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by annadanchenko** [comment]
it's expected that user will get public chat history if any. In 0.9.21 it's 7 day's history, in 0.9.22 it's 1 day history (last 24 hours)
