### ISSUE TITLE
Cannot quickly switch between chats (TouchableHighlight is working slowly)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5112]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to switch between chats without lags or hangs

### Description

*Type*: Bug

*Summary*: when user has several chats, especially with a long history (like #status), during switching application can hang

#### Expected behavior
I can switch between chats

#### Actual behavior
I cannot switch between chats or switching is working extremely slowly

### Reproduction

1. Open status-desktop
2. Sign Up
3. Join to several public channels
4. Switching between them

### Additional Information

MacBook Pro (Retina, 15-inch, Mid 2015)
*OS:* Mac OSx High Sierra 10.13.5
*Status version:* Status version: desktop build 10/07/18 (after merge https://github.com/status-im/status-react/pull/4752)
*NOTE:* according to @siphiuel comments, it is RN-related issue

### Logs
* Video: http://take.ms/g1qNC
* Video when you have several chats with 40+ unread messages: http://take.ms/PMEST
* Log: [StatusIm.txt](https://github.com/status-im/react-native-desktop/files/2179254/StatusIm.txt)

**Comment by vkjr** [comment]
@siphiuel, could you please specify, what issue in `react-native-desktop` impacts this? Thanks.

**Comment by vitvly** [comment]
@vkjr There is no issue yet.

The problem is either that:
  - TouchableHighlight components wrapping chat list items do not respond to onPress events at all in some cases (then this is definitely RN-related)
  - and/or it could be that chat content loads slowly enough for the process to be perceived to the user (in this case I think it would be nice to provide some kind of spinner to the user, like RN's ActivityIndicator, and block user actions until this is finished)

**Comment by vitvly** [comment]
Watched the attached video again. Seems that it is the first problem from the list above, as even smaller chats are not clickable.

**Comment by churik** [comment]
Can be related to #5271

**Comment by maxhora** [comment]
@churik as it was discussed before (since double click issue is solved already, but long loading issue exists), can we modify the task of this Issue to show messages loading indicator? cc: @siphiuel

**Comment by vitvly** [comment]
Agree with @maxris that having some temporary 'messages loading' label in the chat view would be nice, would be happy to implement it :)

**Comment by maxhora** [comment]
@siphiuel I just though that we might use for this purposes "status" label, which we seems supposed to have to show connection status of app. But not sure if it suites here at all.

Interesting that react-native's original ScrollView seems has optional loading bar component. I really haven't looked how it is implemented and when it is triggered, but we don't have such feature in react-native-desktop. I'm starting thinking that this might be the best approach to start from to implement such loading bar directly in react-native-desktop ( if initial investigation will show that it has more benefits than some external loading indicator )

**Comment by vkjr** [comment]
>Interesting that react-native's original ScrollView seems has optional loading bar component

@MaxRis, do you mean original qml ScrollView or react-native ScrollView? Asking because I haven't seen it there.

**Comment by maxhora** [comment]
@vkjr well, sorry, yes, it seems I was wrong about it, please, ignore message about it.

I have meant following functionality in Libararies/Components/ScrollView.js 

https://github.com/status-im/react-native-desktop/blob/master/Libraries/Components/ScrollView/ScrollView.js#L891

But by mistake I've mismatched "refreshControl" functionality with "loading indicator" functionality.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-desktop">status-im/react-native-desktop</a></strong></div><div>react-native-desktop - A Desktop port of React Native, driven by Qt, forked from Canonical</div></blockquote>

**Comment by vkjr** [comment]
@maxris, thanks for pointing to it. Never knew it exists :)
