### ISSUE TITLE
Public chat name is cut when it is selected

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5113]
### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: current chat name is cut even there is enough space to display it fully

#### Expected behavior
full chat name (i.e. #ethereum)

#### Actual behavior
last char is cut ( #ethereu)
![wrchatname](https://user-images.githubusercontent.com/4557972/42221090-92ef89d4-7ed9-11e8-99f5-2a546995a681.png)

### Reproduction

- Open Status
- Sign Up
- Join to any public chat (i.e. `#ethereum`)
- Click on it, pay attention to chat name

### Additional Information
MacBook Pro (Retina, 15-inch, Mid 2015)
*OS:* Mac OSx High Sierra 10.13.5
*Build:* Status version: desktop build 10/07/18 (after merge https://github.com/status-im/status-react/pull/4752)
*Video:* [cut_name](https://monosnap.com/file/urIlw2eNPzWrXuWZCbuIPbtbkLRg2b)
*NOTE:* according to comment in #4752 it is RN-related

**Comment by churik** [comment]
@vkjr do we have issue for this in RN repo?

**Comment by vkjr** [comment]
@churik, I don't think so, probably no one investigated this issue yet.

**Comment by churik** [comment]
got it, thanks @vkjr!
Look please when you have a time.
Thanks!
At least I would prefer to have issue for it in RN repo to track the progress.

**Comment by churik** [comment]
Closed after merging status-im/react-native-desktop#314
