### ISSUE TITLE
`Error: Doesn't support name` if open Send transaction from Dapp and then go to Wallet for 1st time 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5131]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "Error: Doesn't support name" if open Send Transaction screen from Dapp then open Wallet for 1st time.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Wallet screen is opened
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error is shown, if close it then white screen instead of Wallet, so user needs to restart app. After this Wallet screen is shown fine.
``` 
00:57 E/ReactNativeJS: Error: Doesn't support name: 
00:57 E/ReactNativeJS: 
00:57 E/ReactNativeJS: This error is located at:
00:57 E/ReactNativeJS:     in asset-selector
00:57 E/ReactNativeJS:     in reagent97
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTScrollView
00:57 E/ReactNativeJS:     in ScrollView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in reagent4
00:57 E/ReactNativeJS:     in reagent93
00:57 E/ReactNativeJS:     in reagent92
00:57 E/ReactNativeJS:     in send-transaction
00:57 E/ReactNativeJS:     in reagent116
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in main
00:57 E/ReactNativeJS:     in root
00:57 E/ReactNativeJS:     in reagent1
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in t
```
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396006482/?accessToken=-k29U03VA5vrIlYq8g-7i-Yvs9g
1. Install app
2. create new account and switch to ropsten
3. open Test Dapp and request STT -> Send transaction screen is shown
4. close Send transaction screen and close Dapp
5. tap on Wallet tab
6. confirm that you wrote down sign in phrase and proceed to wallet -> currently error is shown. if close it then white screen so need to restart app

Note 1: error does not happen if Wallet screen was opened before opening Send transaction from Dapp. So, if user completes onboarding in the Wallet screen (writes down sign phrase) then no errors.

Note2: error does not happen if initiate tx from chat (/send command): onboarding screen is shown. If user completes onboarding, closes Send Transaction and opens Wallet then no error.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly from Jul 11 and of July 10 https://jenkins.status.im/job/status-react/job/nightly/487/ Didn't try older nightlies

* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396006482/?accessToken=-k29U03VA5vrIlYq8g-7i-Yvs9g">TestFairy: Status 0.9.21 (6186) @2018</a></strong></div></blockquote>
<blockquote><img src="/static/e078d269/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/490/">status-react » nightly #490 [Jenkins]</a></strong></div></blockquote>
<blockquote><img src="/static/e078d269/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/487/">status-react » nightly #487 [Jenkins]</a></strong></div></blockquote>
<blockquote><img src="/static/e078d269/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/490/">status-react » nightly #490 [Jenkins]</a></strong></div></blockquote>

**Comment by noman-land** [comment]
I'm getting "Error: Doesn't support name" for a totally different reason. Not sure if to file it as a separate issue. 

I'm trying to run the `/request` command in a 1-1 chat to request 1 SNT or 0.0001 ETH from a contact and this error pops up.
