### ISSUE TITLE
Add DApps

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5132]
### User Story

As a user, I want to see an updated DApp list in the new release, so that I have more options to explore.

### Description

*Type*: Feature

*Summary*:

Add DApps highlighted in green from July 11 section of this [this spreadsheet](https://docs.google.com/spreadsheets/d/1BLAcybCxF9z9huYxxHu2xctFYahs2T24bdPqWomPZXk/edit#gid=0). 

New additions for 0.9.23:

- [DDEX](https://ddex.io/)
- [Emoon](https://www.emoon.io/)
- [Livepeer](http://livepeer.tv)

Notes: 
- #3131  affects DDEX

#### Expected behavior

DApp list contains 3 new additions. 

#### Actual behavior
No DDEX, Emoon, Livepeer yet.

**Comment by denis-sharypin** [comment]
You can find icons for dapp here https://www.dropbox.com/sh/0loxh6g2out7per/AABsDG5HhQ1v7pfDKwOZzC3Ha?dl=0

<blockquote><img src="https://www.dropbox.com/static/images/spectrum-icons/generated/content/content-folder_dropbox-large.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/sh/0loxh6g2out7per/AABsDG5HhQ1v7pfDKwOZzC3Ha?dl=0">To upload</a></strong></div><div>Shared with Dropbox</div></blockquote>
