### ISSUE TITLE
Custom contact picture and username are not updated after adding user as contact (Public chat, 1-1 chat header)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5147]
### Description

*Type*: Bug

*Summary*: 
contact picture (custom) is not updated after user added you to his contacts in Public Chat, as well as chat header is not updated in 1-1 chat

#### Expected behavior
7) 1-1 chat: chat header is updated;
8) Public chat: can see custom user photo;

#### Actual behavior
7) 1-1 chat: chat header is not updated;
![custname](https://user-images.githubusercontent.com/4557972/42618270-2a2f926e-85bd-11e8-9475-5e7d89740601.png)

8) Public chat: default avatar is displayed
![publ](https://user-images.githubusercontent.com/4557972/42617771-7778e022-85bb-11e8-900f-65ab890f6fa9.png)

### Reproduction
* Prerequisites: 
User A: uses status-desktop
User B: uses status-mobile, has custom photo and username set.

1) (User A) Open Status
2) (User A) Click on +
3) (User A) Start chat with User B, send some message
4) (User A) Join to any public chat (i.e. #test)
5) (User B) Open chat with User A
6) (User B) Click on "Add to contacts"
6) (User B) Send something to public chat #test
7) (User A) open 1-1 chat with User B
8) (User A) open #test

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: [desktop_build_11.07.2018](https://jenkins.status.im/job/status-react/job/desktop/job/manual/47/)
* Operating System: Mac OSx High Sierra

**Comment by EugeOrtiz** [comment]
Note: This also happens when my contact changes his/her name, the old name is shown in chat header and the new name is shown in left panel:

<img width="1429" alt="captura de pantalla 2018-07-17 a la s 6 24 46 p m" src="https://user-images.githubusercontent.com/37297779/42846367-195b9dc6-89ef-11e8-892d-ec6ff509c2f2.png">

**Comment by churik** [comment]
Done in #4636
