### ISSUE TITLE
Add Augur dapp

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5148]
### Description

*Type*: Feature

*Summary*: Add Augur to dapp list. Make sure it's usable.

### Reproduction

- Open Status
- Click new chat button
- Open DApps and select Augur

### Additional Information
* Operating System: Android, iOS

**Comment by pablanopete** [comment]
Does augur have a web view ĐApp?

**Comment by lukaszfryc** [comment]
That's a good question. We've had Augur in our dapp list some time ago so I assume it had web client back then (https://github.com/status-im/status-react/issues/3240). But, looking at https://www.augur.net/get-started/ now I see only desktop client. So, if there is no existing web client we should probably close this issue. Please correct me if I'm wrong. 

<blockquote><img src="https://augur.net/dist/images/meta_logo.png" width="48" align="right"><div><img src="/favicon/favicon-16x16.png" height="14"> Augur | A Decentralized Oracle & Prediction Market Protocol</div><div><strong><a href="https://www.augur.net">Augur | A Decentralized Oracle & Prediction Market Protocol</a></strong></div><div>Augur is a decentralized oracle and prediction market protocol built on the Ethereum blockchain. It allows you to forecast events and be rewarded for predicting them correctly.</div></blockquote>

**Comment by rachelhamlin** [comment]
Yeah, let's close. We also have #5132 - you can update that with any other DApps that should be added as well.
