### ISSUE TITLE
Resizing application window issues

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5151]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to work with application regardless of the app window size.

### Description
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  several issues can be replicated when you resize application window.

**1) Automatic scroll to latest massage after resize**
If initially you are somewhere in the middle of chat history, you automatically pulled back to the latest message after resize
Video is [here](http://take.ms/6k9xv)

**2) CPU consumption jumps to 70-100% during resize**
Video is [here](http://take.ms/vE0hy)
Log is [here](https://github.com/status-im/status-react/files/2187957/StatusIm.txt)

**3) Chat headers and  messages are displayed in a column in a small-size window and doesn't get back if you resize window to normal size again**
#### Regular size
- Chat header
![regul](https://user-images.githubusercontent.com/4557972/42625877-82eeb920-85d1-11e8-9de2-7dafca16f13a.png)
- Messages
![image](https://user-images.githubusercontent.com/4557972/42626172-4f936c78-85d2-11e8-9a00-ce59f80433fb.png)

#### Small size
- Chat header
![png 2018-07-12 12-52-45](https://user-images.githubusercontent.com/4557972/42626346-bebe043c-85d2-11e8-91dc-228b048aceed.png)
- Messages
![am_size](https://user-images.githubusercontent.com/4557972/42626091-0ef6f806-85d2-11e8-80a2-da1e92c66b35.png)

#### Recized to regular size after small
- Chat header
![png 2018-07-12 12-53-26](https://user-images.githubusercontent.com/4557972/42626336-b5869c58-85d2-11e8-977e-752ae0d61070.png)
- Messages
![rel](https://user-images.githubusercontent.com/4557972/42626009-e3c56a32-85d1-11e8-8630-0ac9fab99cee.png)

**4) There is no fixed smallest side for window** 
For Slack smallest window size is: 345X932
For Telegram: 484X873
In all cases user can use most app features.
For Status desktop there are no limits, and you can resize window to a state when it is not possible to work with application (screenshot below is resized window)
![image](https://user-images.githubusercontent.com/4557972/42626832-f905a8c4-85d3-11e8-9e3e-28020b325df6.png)

**5) Tab-bar overlaps with the list of settings in the profile**
<img width="201" alt="dfsdf" src="https://user-images.githubusercontent.com/4557972/52709726-d3187380-2f8d-11e9-8e81-c50087bfcc55.png">

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Add smallest fixed size, where application can be usable
- [ ] Reduce CPU consumption during resize
- [ ] Fix issue with automatic scroll
- [x] Fix issue with displaying messages/chat header in a row
- [ ] Fix issue with overlapping tabs and profile

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: [desktop_build_11.07.2018](https://jenkins.status.im/job/status-react/job/desktop/job/manual/47/)
* Operating System: Mac OSx High Sierra

**Comment by churik** [comment]
3) Chat headers and messages are displayed in a column in a small-size window and doesn't get back if you resize window to normal size again - is fixed in https://github.com/status-im/react-native-desktop/pull/314

**Comment by vkjr** [comment]
@chadyj, this issue was partially resolved by my last (unrelated) PR, but I had no intentions to fully finish it. So moving it back from "in progress"

**Comment by churik** [comment]
Still reproducible

**Comment by vkjr** [comment]
@churik, I see CPU consumption on resize and absence of minimal app size.
Can you also reproduce chat scrolling when window resized? It looks good for me now.
