### ISSUE TITLE
TestFairy warning appears after each logout 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#5152]
### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: TestFairy warning is shown each time when a user performs logout 

#### Expected behavior
TestFairy warning is not shown

#### Actual behavior
TestFairy warning is not shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account or sign in to existing one
- Navigate to profile and logout

### Additional Information
* Status version: 0.9.23 (6197) node a3397e - nightly build from Jul 12
* Operating System: Android, iOS

**Comment by chadyj** [comment]
Testfairy is removed
