### ISSUE TITLE
Wrong value (1) is shown for unread messages counter if user has 9+ unread messages

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5156]
**Description**
Type: Bug.

Summary: When the user receives more than 9 unread messages, the unread messages badge shows "1" instead of "9+".

**Expected behavior**
Show "9+" badge when the user receives more than 9 unread messages.

Design >> zpl.io/V0ypA59 (Zeplin):
<img width="338" alt="captura de pantalla 2018-07-12 a la s 4 48 29 p m" src="https://user-images.githubusercontent.com/37297779/42655761-72373d74-85f3-11e8-80b1-ac9f5515a7c4.png">

**Actual behavior**
The user gets 12 new -unread- messages while in other chat, counter shows "1":

<img width="1435" alt="captura de pantalla 2018-07-12 a la s 4 39 18 p m" src="https://user-images.githubusercontent.com/37297779/42655408-7fd16cee-85f2-11e8-8551-857a38399ce8.png">

When opening the chat with the unread messages, you can see the 12 unread messages:
<img width="1436" alt="captura de pantalla 2018-07-12 a la s 4 39 25 p m" src="https://user-images.githubusercontent.com/37297779/42655480-b9972fea-85f2-11e8-93f8-d7809c71d4ff.png">

### Reproduction
* Prerequisites: 
User A: uses status-desktop
User B: uses status-mobile

1) (User A) Open Status
2) (User A) Click on +
3) (User A) Join to any public chat (i.e. `#test`)
4) (User A) Switch to another chat to see unread messages badge  for`#test`
4) (User B) Join the same public chat; send 12 messages in a row; 
5) (User A) check unread messages badge

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: [desktop_build_11.07.2018](https://jenkins.status.im/job/status-react/job/desktop/job/manual/47/)
* Operating System: Mac OSx High Sierra

**Comment by churik** [comment]
@EugeOrtiz thanks for reporting!

**Comment by churik** [comment]
closed in https://github.com/status-im/status-react/pull/5329
