### ISSUE TITLE
Remove Mixpanel

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5169]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

To ensure Status complies with our values we should remove Mixpanel.

See https://discuss.status.im/t/replacing-mixpanel-a-short-term-brainstorm/149/1 for the background.

This includes the event code that posts to Mixpanel, and the onboarding and settings screens.

#### Expected behavior
No data sent to Mixpanel

#### Actual behavior
Users opt-in, and anon data is sent to Mixpanel

**Comment by mandrigin** [comment]
closing this one because it was done

**Comment by 3esmit** [comment]
Reopening as api.mixpanel.com still being queried, although it only handshakes and apparently does nothing, but I'm skeptical.

**Comment by chadyj** [comment]
Closing https://github.com/status-im/status-react/issues/6200
