### ISSUE TITLE
Error about too precise amount is not shown when requesting an asset from wallet with more than allowed decimals

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#5171]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When requesting tokens from wallet and setting an amount with more than allowed decimals no warning apperas. However it's shown when sending a transaction 

#### Expected behavior
Error `Amount is too precise. Max number of decimals is 8.` should be shown

#### Actual behavior
Error is not shown. It's possible to send a transaction request

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create or recover an account
- Navigate to wallet
- Click 3 dots button in the upper right corner -> Manage assets
- Select a token with 8 decimals (i.e Bytom)
- Click Receive transaction button - Send a transaction request
- In the Asset field select Bytom token
- In the Amount field specify a number with more than 8 decimals (i.e 0.123456789)

### Additional Information
* Status version: 0.9.23 (6197) node a339d7e - nightly build from Jul 13
* Operating System: Android, iOS

**Comment by goranjovic** [comment]
The core issue here is probably that precision validation only works right for decimal format. This is probably displayed in scientific and validation fails because of #5223 

I'm going to try fixing the validation for all formats
