### ISSUE TITLE
Show fiat value in transaction details

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5179]
### Description

*Type*: Feature

*Summary*: We could show USD (or other currency) value of transaction and transaction cost in Transaction Details screen: 

<img src="https://user-images.githubusercontent.com/7532782/42748987-6e309b7a-88e2-11e8-80b2-77fd6ba3109b.png" width="200">

Which is how how a transaction is shown on Etherscan: 

<img src="https://user-images.githubusercontent.com/7532782/42749061-c386718a-88e2-11e8-9fb2-d9ae4c6104ab.png" width="400">

#### Expected behavior
Transaction Details shows fiat value of transaction and transaction fee in selected currency.

#### Actual behavior
Transaction Details does not show fiat value.

### Reproduction

- Open Status
- Send or receive a transaction
- Open Transaction Details from Wallet

### Additional Information
* Status version: 0.9.22
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
This improvement was suggested by @naghdy on [Instabug](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/390).

**Comment by oogetyboogety** [comment]
@lukaszfryc  I'll start this
