### ISSUE TITLE
Add possibility to navigate to user profile from public chat and go back 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5184]
### User Story

As a user, I want to initiate chat  with public chat participants

### Description

*Type*: Feature
*Summary*: user should be able to open profile public chat member by clicking on his profile picture and go back.

#### How it is implemented in mobile

[comment]: # (Describe what you expected to happen.)
When user clicks on user pic of any public chat participant, he is redirectied to:
![lit](https://user-images.githubusercontent.com/4557972/42754333-c81987d6-88fc-11e8-8fd5-b6713a5bac56.png)
The arrow in left top corner is redirecting user back to public chat.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] add redirect to user profile from public chat
- [ ] add way for user to get back to public chat

**Comment by rcullito** [comment]
hey @churik one UX question on here that might also be good to get @EugeOrtiz 's opinion on. Do we want to be able to go straight from a public chat to a user profile to sending that user a direct message without adding them to contacts? Should that be possible to go straight through that workflow or would the user doing the "adding" have to add them before sending the direct message. Just a thought.

**Comment by EugeOrtiz** [comment]
That's a good question. I think that when you start talking to somebody that it is not in your contacts, he/she automatically becomes your contact. 

@churik Are we talking about opening the user profile card by clicking on the picture within the message area, right?:
<img width="375" alt="captura de pantalla 2018-07-24 a la s 10 13 49 a m" src="https://user-images.githubusercontent.com/37297779/43140443-641fb4ce-8f2a-11e8-86d4-c2e318451150.png">

**Comment by churik** [comment]
@rcullito 
The user automatically becomes your contact when you are chat initiator.
So it is right behaviour in #4893.
@EugeOrtiz yes, it is about navigating to profile by clicking on the picture.

**Comment by rcullito** [comment]
Great. Thanks for both of your feedback @EugeOrtiz and @churik. Somewhat related here is including the "back button" on the user profile to get back to the chat. 

That has been done, and now I am wondering if it also makes sense to include the back button on the chat toolbar itself?

Once it is in place for one screen, visually: it quickly becomes difficult to live without :)
