### ISSUE TITLE
User picture borders are not visible for pictures with white background

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5194]
### Description

*Type*: Bug
*Summary*: 
User picture visually doesn't have borders (white on white) in chat list, headers, user profiles.

#### Expected behavior
User profile picture has grey borders, i.e. like on "Sign in" screen.
<img width="506" alt="sign_in" src="https://user-images.githubusercontent.com/4557972/42773015-ba2961c2-8934-11e8-8699-a2033cf5d75a.png">

#### Actual behavior
4.contact list
<img width="328" alt="cont_list" src="https://user-images.githubusercontent.com/4557972/42773236-59865c84-8935-11e8-9061-36dd460a61bd.png">

5. chat list
<img width="171" alt="1" src="https://user-images.githubusercontent.com/4557972/42772725-f4aa5258-8933-11e8-9603-d48f88b69304.png">
6. In chat header
<img width="266" alt="heder" src="https://user-images.githubusercontent.com/4557972/42772771-2215f22e-8934-11e8-8b66-df975c400100.png">
7. on contact profiles ("View profile")
<img width="554" alt="4" src="https://user-images.githubusercontent.com/4557972/42772950-8c287bd2-8934-11e8-88e5-a3b013cfaf02.png">
8. on user profile
<img width="173" alt="profile" src="https://user-images.githubusercontent.com/4557972/42772886-692b717a-8934-11e8-9dba-ccea9263b1f4.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status
2. Sign up
3. Add to contacts user with default picture
4. Pay attention to user picture in Contact list
5. Pay attention to chat list
6. Open chat with user, pay attention to chat header
7. Click on "View profile"
8. Open own profile

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: status desktop 16/07/2018
* Operating System: Mac OSx High Sierra

**Comment by EugeOrtiz** [comment]
Here is the design (color and thickness) of the image border >> zpl.io/V1q4GPB (Zeplin)

<img width="224" alt="captura de pantalla 2018-07-24 a la s 10 34 18 a m" src="https://user-images.githubusercontent.com/37297779/43141770-24fc16fe-8f2d-11e8-9ba4-86922d59d59b.png">

**Comment by churik** [comment]
Still reproducible

**Comment by churik** [comment]
still relevant
