### ISSUE TITLE
Backup user contacts functionality

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#5195]
### User Story

As a User, I want to backup my existing contacts so that if I lose my account or restore it I can easily keep a file of to reload all of my contacts into Status.

### Expected behavior
As a user I expect for there to be a way to save a small file for contact backups as i've built out a long list of friends on status. 

### Actual behavior
No method currently exists to backup contacts in status for restoring at a later point in time. 

### Solution
Create a simple way to backup existing contacts in Status maybe JSON string? Needs design / UX advice. 

Edit has been discussed in #240 it seems like

**Comment by hesterbruikman** [comment]
Suspect this has something to do with unclarity around what is being backup with what we currently call _Backup seedphrase_ (aka Recovery phrase).

Next to explaining that the wallet is backed up, we might need to be explicit about what is not backed up. https://github.com/status-im/status-react/issues/4856


Design effort would need to go into:
- Specifying where in the flow the option to back up is offered
- Specifying the dialogue around it

A principle that was followed in a recent chat discussion: 

> Extreme security is the default, any functionality that lowers security is an option.

**Comment by mariapaulafn** [comment]
I can't be more bullish of this. Just came to say it since i now need to import all my contract and the backup seedphrase did not make the trick, that was a tad underwhelming, still I love the desktop app and it makes my life so much easier, since I use Status quite a lot :) @chadyj

**Comment by chadyj** [comment]
Thanks @mariapaulafn! I'd love to see contacts (and other things like read/unread states, etc) to be sync'd between clients. Soon!

**Comment by pablanopete** [comment]
I think backup is the biggest thing here; what happens when I have to reload my status account or I get a new phone and I lose all my contacts, or dreaded bugs happens and I lose all my contact codes I've built up over a long period of time. @chadyj - can this be considered somewhere? Or is it already.

**Comment by Swader** [comment]
This is a 10xUX fix. Reopening.

**Comment by pablanopete** [comment]
Thanks @Swader for the backup on this one! Good thing @mandrigin is doing a bit of work related to it as well  :D

**Comment by cammellos** [comment]
Please add feature requests to https://discuss.status.im/ , thanks for you input!
