### ISSUE TITLE
Unread messages badge is missing on "Home"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5200]
### User Story

As a user, I want to see that I have unread messages even if I leave chat list. 

### Description

*Type*: Bug

*Summary*: there is no unread messages badge on Home.

#### Expected behavior
unread messages is presented on "Home"
![unread](https://user-images.githubusercontent.com/4557972/42803195-e82968be-89ad-11e8-9ba6-0a00e4cdcb22.png)

#### Actual behavior
no unread messages badge
![unr_e](https://user-images.githubusercontent.com/4557972/42803231-0e45a6a2-89ae-11e8-9540-1cacdf54441d.png)

### Reproduction

- Open Status
- Start chat with User B
- switch to another chat
- Send new messge to chat (User B)
-  Pay attention to Home

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  status desktop[16/07/18]( https://jenkins.status.im/job/status-react/job/desktop/job/manual/49/)
* Operating System: Mac OSx High Sierra

**Comment by EugeOrtiz** [comment]
Designs here >> zpl.io/2ZJ6Zmw (Zeplin):

<img width="496" alt="captura de pantalla 2018-07-17 a la s 12 37 13 p m" src="https://user-images.githubusercontent.com/37297779/42828033-2c4b112c-89be-11e8-8508-a4852e3c5954.png">

**Comment by churik** [comment]
closed in https://github.com/status-im/status-react/pull/5329
