### ISSUE TITLE
Missing value for property transport.topic in 1-1 chat for recovered account

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5204]
*Type*: Bug

*Summary*: Autotest failed with the `Missing value for property transport.topic` erro in 1-1 chat for a recovered account. Could not reproduce for the same account manually but anyway keeping this issue here for now

#### Expected behavior
No errors in 1-1 chat 

#### Actual behavior
Missing value for property transport.topic in 1-1 chat for recovered account

<img width="410" alt="screen shot 2018-07-17 at 14 46 20" src="https://user-images.githubusercontent.com/8749671/42815503-36bc597e-89d0-11e8-89e5-280745b15d7d.png">

### Reproduction 

1) Open Status on Desktop app and create new account (Contact1)
2) Open Status on Device 2 and create new account (Contact2)
3) Remember recovery phrase of the Contact1
4) Log out of Contact1 on Desktop app
5) Recover Contact1 account of Device3
4) Contact1(from Device3) adds Contact2 in contacts and sends a text message
5) Contact2 navigates to 1-1 chat with Contact1 and taps 'Add to contacts'
6) Contact2 sends several text messages to Contact1
7) Contact1 logs in to the account from Desktop App (Note: Contact1 receives text messages from Contact2 from offline inbox after login)
9) Contact1 (on Desktop App) navigates to 1-1 chat with Contact2
10) Contact1 (on Desktop App) taps 'Add to Contacts'

### Additional Information
* Status version: Nightly develop build `0.9.23 (6207)` (498th Jenkins build)
* Operating System: Android 7.1

#### Logs
Logs for this session when error appeared: 
[logcat.txt](https://github.com/status-im/status-react/files/2201455/logcat.txt)

**Comment by churik** [comment]
Got same error at attempt to start chat with user `0x04e9f45075159f4c05502f5f844a1553366715d5a979c1f957f63dd0cb9b1681b68f7d86569d04631f9b4f6a23b3dc62f113dec7b6f10d0accc38b983c2fc33651` (just scan code) for recovered account.

TF session: https://app.testfairy.com/projects/4803590-status/builds/8579833/sessions/4400455602/?accessToken=4IBM8oYxfeNJUbQIsLt3VddQvCs (from 36:40)

*NOTE:* "add to contact" is still available in 1-1 chat after I actually add user to contact and relaunch app.
So every time I relaunch Status user is removed from contacts.
TF session: https://status-im.testfairy.com/projects/4803590-status/builds/8579833/sessions/4400491468?source=latest-sessions


<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8579833/sessions/4400455602/?accessToken=4IBM8oYxfeNJUbQIsLt3VddQvCs">TestFairy: Status 0.9.26 (7624) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://status-im.testfairy.com/projects/4803590-status/builds/8579833/sessions/4400491468?source=latest-sessions">TestFairy: Login</a></strong></div></blockquote>

**Comment by oskarth** [comment]
Same error when trying to add a contact I already added (but shows up as not added).

**Comment by lukaszfryc** [comment]
Jarrad just reported the same issue while adding a contact. His [logcat](https://gist.github.com/dc87e0a45ee19a1eb8b2dc800f7df189).

**Comment by lukaszfryc** [comment]
Jarrad thoughts about it:

> There's a serious problem with the database on both mobile and desktop, it doesn't remember contacts or history beyond some weird state, and when it's like this it gives you a strange 'topic' error when adding a contact. Needs to be fixed asap

**Comment by lukaszfryc** [comment]
@cammellos maybe you could check it?

**Comment by cammellos** [comment]
on holiday until Monday, i can do that then if still an issue, thanks

**Comment by Serhy** [comment]
Got the steps to reproduce. Below they are described in order when transport.topic appears on Desktop app, but it reproduced when all of three Contacts are using mobile devices as well. 

1) Open Status on Desktop app and create new account (Contact1)
2) Open Status on Device 2 and create new account (Contact2)
3) Remember recovery phrase of the Contact1
4) Log out of Contact1 on Desktop app
5) Recover Contact1 account of Device3
4) Contact1(from Device3) adds Contact2 in contacts and sends a text message
5) Contact2 navigates to 1-1 chat with Contact1 and taps 'Add to contacts'
6) Contact2 sends several text messages to Contact1
7) Contact1 logs in to the account from Desktop App (Note: Contact1 receives text messages from Contact2 from offline inbox after login)
9) Contact1 (on Desktop App) navigates to 1-1 chat with Contact2
10) Contact1 (on Desktop App) taps 'Add to Contacts'

**Comment by cammellos** [comment]
Currently I have the feelings that this errors might just be red herrings.
If you see the logs, `update-transactions-success` is dispatched every `200 ms`, both for @churik and @Serhy . This might effectively prevent proper functioning of the app, so it is another possibility to explore.

**Comment by cammellos** [comment]
ah ok, figured out, very simply we just kill the worker on any exception, will push a fix for that.

**Comment by lukaszfryc** [comment]
@Serhy this should be already fixed according to https://github.com/status-im/status-react/pull/6236#issuecomment-428906635, right?

**Comment by Serhy** [comment]
@lukaszfryc well, yes and no. 
Yes, there is no more pop-up like in the description of this issue with `Transport.topic` error. But the `transport.topic` error visible in logs.
However the last deserves a separate issue. Thanks for mentioning it!
Closing this one!
