### ISSUE TITLE
Add way to select different fleets for use with the app

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#5213]
### User Story

As a sysadmin(devops is a buzzword) I want the app to be able to switch between different `eth` fleets without having to re-build the whole application. This is necessary to test infrastructure changes and `statusd` version changes on a __staging__ fleet before it's deployed to the fleet used in the public release.

### Description

Right now we have 3 fleets:
* [`eth.test`](https://consul.status.im/ui/do-ams3/nodes?s=eth.test) - Used by me for developing infra.
* [`eth.staging`](https://consul.status.im/ui/do-ams3/nodes?s=eth.staging) - Intended for `statusd` CI and testing new versions.
* [`eth.beta`](https://consul.status.im/ui/do-ams3/nodes?s=eth.beta) - The fleet currently used in the public releases.

Onle one of them is used in the app currently, the `eth.beta`.

#### Expected behavior
In order to test for example a new `statusd` version on `eth.staging` before deploying it to `eth.beta` we need to be able to select one of those in the App before logging in. This should be done in such a way that the node does not use any of the cached nodes.

#### Actual behavior
Currently when you log in you default to using the `boot`, `whisper` and `mail` nodes defined in two files:
* [`status-im/status-react/blob/develop/src/status_im/constants.cljs`](https://github.com/status-im/status-react/blob/develop/src/status_im/constants.cljs#L88)
* [`status-im/status-go/blob/develop/params/cluster.go`](https://github.com/status-im/status-go/blob/develop/params/cluster.go#L37)

This is hard to maintain and far too static.

### Additional Information
There was an issue cut for the `status-go` repo but it might be superfluous: https://github.com/status-im/status-go/issues/1100

I'm not sure what is the best way to do this but my gut is telling me that the best way would be to have a JSON file that `status-react` loads, that can be edited by devs/testers by hand if need be, that is then used to inform `status-go` library used by `status-react` on what to connect to. This way configuration will be just in one palce(`status-react`) and will be editable without the need to rebuild anything.

Something like:
```json
{
   "mainnet": {
       "default": "eth.beta",
       "eth.beta": {
           "boot": {
                "boot-01.do-ams3.eth.beta": "enode://ABCxyz@174.138.105.243:30404",
                "boot-02.do-ams3.eth.beta": "enode://XYZabc@206.189.243.57:30404",
                ...
           },
           "whisper": {
                ...
           },
           "mail": {
                ...
           }
       },
       "eth.staging": {
          ...
       }
   },
   "ropsten": {
      ...
   }
}
```

**Comment by adambabik** [comment]
Fleet can be selected in the configuration JSON. I propose to add an option in the settings to choose a fleet if "Development Mode" is turned on. That's the easiest.

If we don't want to expose that in the UI, we can have a build tag I believe.

**Comment by annadanchenko** [comment]
We also need UI option to be able to switch between test/staging/beta (default) in the app

**Comment by jakubgs** [comment]
I think the solution that requires rebuilding the app is not sufficient.
* It complicates the build system, which is already complex, and we want to avoid using parameters
* It makes it confusing for devs/testrs. How does one know which version of the app they are running?
* It requires reinstalation of the app in order to check a different fleet.

Having UI selection of fleets will make it easier to test `statusd` versions and infra changes without adding yet another type of build for every single platform(of which there are 5).

**Comment by jakubgs** [comment]
I might add that now we also have https://fleets.status.im/ to get current state of the fleet, which would be a better format for storing fleet configuration than JS or Go files.

<blockquote></blockquote>

**Comment by jakubgs** [comment]
Why did you undo changes in `Jenkinsfile.linus` in the `environment` section? You break the buildnf variables like `ANDROID_NDK` or `ANDROID_SDK` are not set correctly.
