### ISSUE TITLE
Migrate clj scripts to latest clj-rn

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#5226]
### User Story

As a developer, I want to reduce the number of commands/shells I have to use.

### Description

*Type*: Feature

Latest `clj-rn` removes the need for `react-native start`. Migrate clj conf to this model.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 2500.00
Contract address: [0x05e2e2f9a06cb44a456caeda37ab1a42d7e2c2a7](https://etherscan.io/address/0x05e2e2f9a06cb44a456caeda37ab1a42d7e2c2a7)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
