### ISSUE TITLE
Add correct Status icon to OSX dock

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5235]
**User story** 
As a user, I want to quicky identify the Status desktop app by taking a look at the icon on the dock.

**Description**
Type: Fix (visual).
Summary: Replace current square icon with the correct Status logo.

**Current view**:
<img width="374" alt="captura de pantalla 2018-07-19 a la s 5 55 39 p m" src="https://user-images.githubusercontent.com/37297779/42969605-1c2288a0-8b7d-11e8-9fe6-5cc450d86220.png">

**Expected results**:
![dock](https://user-images.githubusercontent.com/37297779/42969988-68d9d30a-8b7e-11e8-9816-9ca8c108ebe0.png)

**Design files**
Images 1024x1024
[Status_icon_1x.png](https://drive.google.com/open?id=1KjnK_qzKX6SbEfzr-kvpqNcRod0rDzRa)
[Status_icon_2x.png](https://drive.google.com/open?id=1P27UlBmROk9UQ-KGDw3Zpfq9WOGwkIjZ)

**Comment by EugeOrtiz** [comment]
It would be great to also include other platforms (linux, etc.) views of this icon.

**Comment by chadyj** [comment]
Looks like this is working now :)
