### ISSUE TITLE
UI: transaction fee value is beyond of "Transaction Fee" field boundary

### ISSUE THREAD

**Issue by hetvart** [status-im/status-react#5246]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: transaction fee value is beyond of "Transaction Fee" field boundary while signing in transaction

#### Expected behavior
Transaction Fee value should be wrapped up.

#### Actual behavior
Transaction Fee value comes out of the field boundary.
![photo_2018-07-20_16-15-18](https://user-images.githubusercontent.com/15172961/43004335-209c6110-8c38-11e8-9298-79053c310002.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account/Use an existing one and login to the app
- Turn development mode on
- Connect to ROPSTEN
- Goto Status Console and request ETH (/faucet http://51.15.45.169:3001)
- Add a contact 
- Send 0.001 ETH to the contact
- On Send Transaction screen expand 'Advanced' section and verify 'Transaction Fee' field

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release 0.9.22 (6164)
* Operating System: IOS 11.4.1

<blockquote></blockquote>

**Comment by denis-sharypin** [comment]
@goranjovic  Let's remove math from this field (gas limit*gas price)

**Comment by Swader** [comment]
Please verify if fixed.

**Comment by denis-sharypin** [comment]
Will be fixed by this https://github.com/status-im/status-react/pull/7263
