### ISSUE TITLE
REP tokens are not shown in Wallet

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5248]
### Description

*Type*: Bug

*Summary*: 
I've bought some REP using Airswap but Wallet still shows 0 REP despite 29 confirmations for the transaction:
<img src="https://user-images.githubusercontent.com/7532782/43011554-25a8d66e-8c44-11e8-8451-8df08d321f39.png" width="200">

Also, I'd expect that the transaction in transaction history will change from ETH to REP after a while. But it's not, instead the ETH value of transaction is shown:
<img src="https://user-images.githubusercontent.com/7532782/43011682-7dcd68be-8c44-11e8-8be4-ebb659c5a7ce.png" width="200">  

#### Expected behavior
- REP funds are shown in Wallet
- Transaction history shows REP transactions

#### Actual behavior
- Wallet shows 0 REP
- Transaction history shows ETH transaction

### Reproduction

- Open Status
- Buy REP in Airswap Dapp
- Wait for REP in Wallet

### Additional Information
* Status version: 0.9.22
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
The bug was originally reported by a user via [Instabug](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/409).

**Comment by goranjovic** [comment]
TX on Etherscan - https://etherscan.io/token/0x1985365e9f78359a9b6ad760e32412f4a445e862

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/token/0x1985365e9f78359a9b6ad760e32412f4a445e862">Reputation (REP) Token Tracker</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>
