### ISSUE TITLE
[Android Transaction] Send transaction is not shown in 1:1 chat when sending to a recipient from within the wallet

### ISSUE THREAD

**Issue by hetvart** [status-im/status-react#5253]
[comment]: # (Please replace ... with your information. Remove < and >)
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: transaction is not shown in 1:1 chat when trying to send ETH from within the Wallet to a recipient who is in Contacts. But funds amount is decreased

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
transaction shoud appear in 1:1 chat when sending ETH from wallet to recipient
#### Actual behavior
[comment]: # (Describe what actually happened.)
after you signed in the transaction it does not appear in 1:1 chat. BUT actual state of wallet is changed: amount is decreased.
See the moment when this happens: http://recordit.co/ycCdO6AZ3i
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on two devices: ios and android. Android is primary device.
- Create accounts on both devices.
- Switch to dev mode with ROPSTEN on both devices
- On primary device goto Home -> Plus -> Start new chat. Open QR contact scanner
- On secondary device goto Profile -> Share my contact code
- On primary device scan the contact code of secondary device
- Send a message to secondary device
- Add to contact the person on secondary device
- On primary request /faucet in Status console. Wait until funds come to the wallet.
- On primary device goto Wallet -> LET'S GET SET UP -> Yes
- On primary device goto Send transaction -> Choose recipient -> Contacts and choose a person from secondary device. Specify all funds you have and sign in transaction.
### Additional Information 
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21 (6121)
* Operating System: primary device Android 8.0 Google Nexus 6P (via Genymotion)
secondary device real iphone 6s with ios 11.4.1. Status version: 0.9.22 (6164)

Reproduced on: July, 22; 5:52 pm Kiev time
[Link to apk](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-f62e7d-rel.apk)

<blockquote><img src="/favicon.ico?v=0.2" width="48" align="right"><div><strong><a href="http://recordit.co/ycCdO6AZ3i">Recordit: Record screencasts fast & free! with GIF Support!</a></strong></div></blockquote>

**Comment by hetvart** [comment]
Just did the same test with STT. The actual result is the same.

**Comment by annadanchenko** [comment]
will be implemented as new feature in 0.9.23 version. It's expected that there is no message if send from Wallet in 0.9.22 and lower versions
