### ISSUE TITLE
[Wallet] Invalid address error is shown when entering recipient address

### ISSUE THREAD

**Issue by hetvart** [status-im/status-react#5255]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: user cannot send a transaction entering contact address manually because an error occurs

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
recipient address appears in `Choose Recipient` field
#### Actual behavior
[comment]: # (Describe what actually happened.)
Invalid address error takes place (see screen enclosed)
![image](https://user-images.githubusercontent.com/15172961/43048248-15b6586c-8ded-11e8-8b2f-aa4b2806f4d2.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on two devices (android and ios)
- Create an account per device and switch both devices to dev mode with ROPSTEN
- On 1st device goto Profile -> Share my contact code -> Copy contact code to clipboard and save it on some shared source 
- On 2nd device goto Wallet -> Send transaction -> Choose recipient -> Enter recipient address -> Paste copied (from shared source) contact code and tap `Done`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: real iphone 6s status version 0.9.22 (6164)
Genymotion Google Nexus 6P status version 0.9.21 (6121)
* Operating System: Android 8.0; ios 11.4.1

REPRODUCIBLE ON BOTH DEVICES AND OSs

**Comment by annadanchenko** [comment]
@hetvart it's expected, as contact code is not Wallet address. You can find address in the Wallet -> Request Transaction screen
