### ISSUE TITLE
Implement web3 provider Opt-in access

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#5260]
### User Story

As a user, I want to make sure my privacy is not at risk when using a DApp.
As a developer, I want to follow community standards.

### Description

*Type*: Feature

Implement web3 provider Opt-in access as defined by [EIP1102](https://eips.ethereum.org/EIPS/eip-1102). This pattern follows the pattern used in our recently merged status web DApp API support.

UX will be augmented so that a user can decide if web3 access should be granted to the DApp (cc @denis-sharypin)

As a first step old behavior will be kept for backwards compatibility: all currently working DApps should still work fine.
Status user can enable privacy aware web3 access in it's profile (cc @denis-sharypin). Once enabled `web3` object won't be injected by default (and old style DApps will be broken).

As this change forces DApps devs to update their DApps we want to have clear documentation detailing steps required to move to this pattern.

### UX considerations

DApps will probably mostly request access at startup. Some access during the lifecycle of a DApp might be expected too.
Permissions are granted on a per DApp level and persistent (i.e. once granted it won't be re-asked). No global permission handling are considered at this stage.
A panel accessible from user profile allows to quickly browse and modify permissions granted per DApp.

**Comment by obi2020** [comment]
FYI, I've started collaborating with @denis-sharypin on dialogues for this and he has some design mocks. We are also making an effort to align with MetaMask team on language

**Comment by denis-sharypin** [comment]
Hey just to catch up on the current phase:
<img width="1018" alt="slice" src="https://user-images.githubusercontent.com/6559881/43964352-952535e8-9cb4-11e8-80b8-0b7c68cc5059.png">

`Manage permissions` opens a screen in the profile

<img width="810" alt="screenshot 2018-08-10 18 14 36" src="https://user-images.githubusercontent.com/6559881/43971513-4900adae-9cc9-11e8-8bdb-b22e8758d46b.png">
