### ISSUE TITLE
Disable "Send" button and change it to "Sent" after transaction is signed

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5261]
### Description

*Type*: Bug

*Summary*: When "/request" message is received, the "Send" button is still active after the transaction is signed. Instead, it should be disabled to indicate that user responded to the "/request" message.

#### Expected behavior
"Send" button should change to "Sent" and become disabled after the transaction is signed.

#### Actual behavior
"Send" button does not change when the transaction is signed.

### Reproduction

- Open 1-1 chat
- Device 1: Send "/request" message
- Device 2: Click on "Send" button on the message and sign the transaction 

### Additional Information
* Status version: 0.9.23
* Operating System: Android, iOS

**Comment by janherich** [comment]
@lukaszfryc Just to be clear, is this the case in recent develop (after `feature/cljs-commands` was merged) as well ?

**Comment by lukaszfryc** [comment]
@janherich yes, it had happened before cljs-commands was merged

**Comment by lukaszfryc** [comment]
duplicate of https://github.com/status-im/status-react/issues/5048
