### ISSUE TITLE
Error message.chat-id must be of type 'string', got 'null' (null) when sending tokens / ETH from wallet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5267]
*Type*: Bug

*Summary*:  Error `message.chat-id must be of type 'string', got 'null' (null)` when sending ETH / tokens from wallet

#### Expected behavior
No errors when sending assets

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/43076504-18dbfcea-8e8d-11e8-96b9-544617e0bf8b.png)

### Reproduction

- Open Status (mainnet)
- Tap wallet
- Tap select recipient and scan any valid contact code
- Choose SNT from asset field and set 0
- Tap Send

### Additional Information

* Introduced here https://github.com/status-im/status-react/pull/5236#issuecomment-406582710
* TF https://app.testfairy.com/projects/4803622-status/builds/8533190/sessions/4396910193/?accessToken=RPjGUDC8/Q2YU8dPeVXdJP2hJ0Y

#### Logs

```
01:32 I/ReactNativeJS: ***
01:32 I/ReactNativeJS: NAME: "Error"
01:32 I/ReactNativeJS: MESSAGE: message.chat-id must be of type 'string', got 'null' (null)
01:32 I/ReactNativeJS: 
01:32 I/ReactNativeJS: create@[native code]
01:32 I/ReactNativeJS: cljs$core$IFn$_invoke$arity$4@index.android.bundle:12:5299895
01:32 I/ReactNativeJS: index.android.bundle:12:5490237
01:32 I/ReactNativeJS: index.android.bundle:12:6415859
01:32 I/ReactNativeJS: write@[native code]
01:32 I/ReactNativeJS: write@index.android.bundle:12:5298909
01:32 I/ReactNativeJS: perform_transactions@index.android.bundle:12:6415375
01:32 I/ReactNativeJS: t@index.android.bundle:12:383170
01:32 I/ReactNativeJS: index.android.bundle:12:5231810
01:32 I/ReactNativeJS: r@index.android.bundle:12:5231078
01:32 I/ReactNativeJS: run_state_machine@index.android.bundle:12:5092244
01:32 I/ReactNativeJS: run_state_machine_wrapped@index.android.bundle:12:5092396
01:32 I/ReactNativeJS: index.android.bundle:12:5092844
01:32 I/ReactNativeJS: index.android.bundle:12:5079167
01:32 I/ReactNativeJS: process_messages@index.android.bundle:12:5072767
01:32 I/ReactNativeJS: index.android.bundle:126:1787
01:32 I/ReactNativeJS: x@index.android.bundle:126:643
01:32 I/ReactNativeJS: k@index.android.bundle:126:1007
01:32 I/ReactNativeJS: callImmediates@index.android.bundle:126:3188
01:32 I/ReactNativeJS: value@index.android.bundle:121:3183
01:32 I/ReactNativeJS: index.android.bundle:121:1516
01:32 I/ReactNativeJS: value@index.android.bundle:121:3009
01:32 I/ReactNativeJS: value@index.android.bundle:121:1486
01:32 I/ReactNativeJS: [native code]
01:32 I/ReactNativeJS: value@index.android.bundle:121:1094
01:32 I/ReactNativeJS: [native code]
01:32 I/ReactNativeJS: 
01:32 I/ReactNativeJS: ***
```

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8533190/sessions/4396910193/?accessToken=RPjGUDC8/Q2YU8dPeVXdJP2hJ0Y">TestFairy: Status 0.9.23 (6236) @2018</a></strong></div></blockquote>

**Comment by janherich** [comment]
@asemiankevich One question - when seeing this error, was the recipient of the funds in sender's contacts, eq was there already existing chat with the recipient on sender's device ?

**Comment by asemiankevich** [comment]
my bad, forgot to mention.
recipient is NOT in contacts @janherich

**Comment by janherich** [comment]
Awesome thanks, it's then super easy to solve, given one condition -> when recipient is not in contacts, we don't expect that sending transaction with open chat with him (so the `/send` message actually has place to land), correct @asemiankevich @annadanchenko @goranjovic ?

**Comment by asemiankevich** [comment]
@janherich i believe this case (sending from wallet creates new chat) is not implemented yet , Goran could confirm . New chat is created when only user has recipient in contacts (for now)

**Comment by goranjovic** [comment]
@janherich @asemiankevich 
If the recipient is in contacts, the payment message should appear in the chat. If no chat exists, it should be created. Either way, if the transaction was initiated from Wallet the app should go to Transaction sent and from there (by tapping Done) to main Wallet screen, i.e. not navigate to that chat automatically.

If the recipient is not in contacts, there should be no payment message added to chat (because we have no whisper id to send the message to.)

**Comment by janherich** [comment]
@goranjovic got it, thanks !
