### ISSUE TITLE
Transaction failed 502 Bad Gateway when signing transaction from wallet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5270]
### Description

*Type*: Bug

*Summary*: Received this error several times today, not sure about stable steps to reproduce yet

#### Expected behavior
No infura issues when signing transaction

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/43079436-ca5de34a-8e95-11e8-9e03-76cc47deb087.png)

### Reproduction

- Open Status (mainnet)
- Go to wallet
- Tap select recipient and scan any valid contact code
- Select asset (for ex SNT) , set value (for ex 0) and sign transaction

### Logs

```
02:02 4/Status: 2018-07-23 15:39:09.313 [info][tid:com.facebook.react.JavaScript] INFO [status-im.utils.ethereum.core:131] - {"meta":null,"cnt":2,"arr":[{"ns":null,"name":"code","fqn":"code","_hash":null,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096},-32700,{"ns":null,"name":"message","fqn":"message","_hash":null,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096},"502 Bad Gateway "],"__hash":null,"cljs$lang$protocol_mask$partition0$":16647951,"cljs$lang$protocol_mask$partition1$":139268}```

**Comment by mandrigin** [comment]
@asemiankevich that is definitely an Infura issue and I don't think there is something we can do about fixing it. What we can do, is to wrap this error message to something more readable and actionable, but that worth a separate issue, I think.
