### ISSUE TITLE
Memory leaks on chats switching

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5271]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to switch chats infinity number of times and do not have crashes because of memory allocation errors.

### Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:

Switching between chats increasing RAM used by app

 #### Expected behavior
On chats switching RAM is not get increased on every switch.

#### Actual behavior
On chats switching used RAM is increased on every switch.

### Reproduction

- Open Status Desktop
- Open multiple chats and start switching between them ( chats with long message history have bigger impact on RAM increasing )
- Monitor amount of RAM used by app

* Status version: ...

* Operating System: Desktop

**Comment by chadyj** [comment]
Status routinely uses over 1.3GB on memory on a Mac.  More than 10x Slack or Chrome.

**Comment by rasom** [comment]
So this is not something Status specific, that's how `FlatList` works in `react-native-desktop`

**Comment by rasom** [comment]
blocked by https://github.com/status-im/react-native-desktop/issues/348

**Comment by chadyj** [comment]
Still having memory issues. My desktop was using 4.6gb ram.

Perhaps some deeper memory profiling needs to be done?

**Comment by Swader** [comment]
Very important
