### ISSUE TITLE
ETH in wallet address not displaying in Status Wallet

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/status-react#5276]
[comment]: # (Please replace ... with your information. Remove < and >)
*User Story*
As a user, I want to see ETH which I have sent to my status wallet address so that I may use it in status.

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 

I transfered 0.2 ETH to my status wallet. The address for my status.im wallet is: 0x997bC170E10F194C5Cd4bDBDC9A14A95B63D7B72. 

According to  #etherscan this wallet address successfully recieved the 0.2 ETH and has had no other transactions. 
https://etherscan.io/address/0x997bc170e10f194c5cd4bdbdc9a14a95b63d7b72

Unfortauntly it has not reflected in status.im. 
![screenshot_20180724-120342_status](https://user-images.githubusercontent.com/7915365/43134364-c0eeb45c-8f39-11e8-8c7e-f1c1b6267a65.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

I expected the 0.2 ETH to reflect in my status.im wallet after I had seen the 0.2 ETH in the wallet via etherscan. 

#### Actual behavior
[comment]: # (Describe what actually happened.)

What actually happened was that the 0.2 ETH did not display in my status.im wallet after several hours and multiple logging in and out. 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Back up wallet seed phrase
- Go to recieve, scan wallet address QR code with computer (current wallet balance is 0)
- Send ETH to wallet address from computer (via ledger live app)
- Check status wallet to reflect ETH
- Check transaction ID on etherscan to see confirmed transaction 
- log out, log in status multiple times
- ETH balance in status wallet still 0.00 ETH. 

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- ETH in wallet address to be reflected in status.im wallet frontend. 
- Maybe linked to #4734 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.23 (6238) node a339d7e 
*Network: Mainnet with upstream RPC 
* Operating System: Android, 8.0.0 
*Phone: Samsung Note 8 
*Link to wallet address in etherscan: https://etherscan.io/address/0x997bc170e10f194c5cd4bdbdc9a14a95b63d7b72
*Screenshot of wallet: 
![screenshot_20180723-192900_status](https://user-images.githubusercontent.com/7915365/43131095-1a9d7ccc-8f30-11e8-8b7c-522dd8f900a4.jpg)
![screenshot_20180724-105606_status](https://user-images.githubusercontent.com/7915365/43131191-57b713d4-8f30-11e8-9fba-3fe43d3e2cc4.jpg)

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/address/0x997bc170e10f194c5cd4bdbdc9a14a95b63d7b72">Ethereum Accounts, Address and Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>
<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/address/0x997bc170e10f194c5cd4bdbdc9a14a95b63d7b72">Ethereum Accounts, Address and Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by goranjovic** [comment]
Hi @Graeme-Code thanks for the bug report! 

Just a few extra questions from me:

1.  Does anything happen when you pull the Wallet screen down? (i.e. pull to refresh).
2. I see on the screenshot that not even asset prices were updated. Is there any specific network condition on that phone, e.g. slow connection (2g, edge, etc), maybe proxy, etc? I assume that other apps on the same phone can access network fine?

**Comment by Graeme-Code** [comment]
Hi @goranjovic  for sure,
1. When pulling the screen down the loading icon in the center top quickly appears and disappears. 
2. I'm on good wifi at the moment and first discovered the issue on my wifi at home (10mbps). Other apps are working well. Switching to 4G doesn't change the result. 

Here is a video of changing from network to wifi as well as the refresh interaction: 
https://drive.google.com/file/d/1bzMnegBNBHWScGPHhgO_iI7X2bpuaDF-/view?usp=sharing


<blockquote><img src="https://lh5.googleusercontent.com/uKFmmrIoL7qzUd4cqJ7vWGVqa-NW2Nxbaor3dgM4q13hdmPr0YTRQfJuKbE=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1bzMnegBNBHWScGPHhgO_iI7X2bpuaDF-/view?usp=sharing&usp=embed_facebook">refresh wallet video.mp4</a></strong></div></blockquote>

**Comment by Graeme-Code** [comment]
Hi @goranjovic , i think I know what is wrong. 

I used my seed phrase for the status wallet to log into Metamask to see if my ETH was there. And it was not there. 

I then looked at the address I transferred to from my hardware wallet. 
https://etherscan.io/address/0x997bc170e10f194c5cd4bdbdc9a14a95b63d7b72

I did the transaction by using the ledger live app to scan the status "receive" QR code using my Mac webcam. 

I then double checked the public key of my meta-mask account which I used the seed phrase from my status.im wallet. 
https://etherscan.io/address/0x997bc170e10f194c5bd4bdbdc9a14a95b63d7b72

No ETH in there. 

So I looked closely at the public addresses and found that they vary. 

Address to which I sent funds: 
0x997bC170E10F194C5Cd4bDBDC9A14A95B63D7B72

Address my status.im seed phrase creates via metamask: 
0x997Bc170e10F194c5bd4BDbDc9a14a95B63D7b72

They differ in that the digit 20 of the address I sent funds to is a "C" and digit 20 of the status.im seed phase account is a "b". 

I'm assuming either:
I've got a bug with either the ledger live app or my mac software responsible for reading QR codes. 
Or
I remember incorrectly and manually entered in my status wallet address, leading to the error. 

Gonna test out the ledger live app again to make sure. I'm pretty sure it is not malicious as the ETH is still sitting in the account. 

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/address/0x997bc170e10f194c5cd4bdbdc9a14a95b63d7b72">Ethereum Accounts, Address and Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>
<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/address/0x997bc170e10f194c5bd4bdbdc9a14a95b63d7b72">Ethereum Accounts, Address and Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by Graeme-Code** [comment]
I retested sending ETH to my status.im wallet via scanning QR code, it worked and the ETH is displaying in my wallet :) I must of messed up the entering of public key on the first attmpt. 

Although the currency value has not updated. 
![screenshot_20180728-085640_status](https://user-images.githubusercontent.com/7915365/43354429-6ecc667a-9244-11e8-8663-69decb57568b.jpg)

**Comment by goranjovic** [comment]
@Graeme-Code Glad to hear your assets are all fine and thanks for letting us know! 

The second issue (0 dollars despite having balance) seems to be related to the conversion to fiat value. We've received reports on this and are working on it. (issue #5356).

Since the original problem seems to be resolved, I'm going to close this issue. If you notice anything weird please either create an issue or  just message me. We really appreciate all the effort you've taken to help us make Status better. Cheers!
