### ISSUE TITLE
Transaction sent twice?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#528]
**Title:** 	 Transaction sent twice?

**Device:** 	 samsung SM-G935F, OS Level 23

**Memory:** 	 2237.0/3562.0 MB

**Storage:** 	 17.413/25.44 GB

**Battery:** 	 71, Unplugged

**App Version:** 	 1.0 (1)

**Duration:** 	 18

**Console Log:**
```
568637397-23cfd087-ee15-5e60-8971-a724443aae96
12-01 15:07:50.114 D/ReactNativeJS( 3343): DEBUG [status-im.protocol.web3.transport:16] - :post-message :from 0x0417f5fbc9d7f3e371d8210b8e4d9fa4f72226281c9578845876fa01326801758789a33af642528914231a5da4f925534d5a321a9cb28ebeda4fa19cfb815b0834, :to nil, :topics [status-dapp-topic], :payload 0x7b3a6d6573736167652d69642022696e74726f2d737461747573222c203a72657175697265732d61636b3f2066616c73652c203a74797065203a7365656e2c203a67726f75702d6964206e696c2c203a636f6e74656e74206e696c7d0a, :ttl 120
12-01 15:07:50.114 D/ReactNativeJS( 3343): DEBUG [status-im.protocol.web3.delivery:123] - :attempt-was-made intro-status
12-01 15:07:50.124 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:50.134 D/ReactNativeJS( 3343): DEBUG [status-im.protocol.web3.delivery:134] - :delivery-callback
12-01 15:07:50.134 I/ReactNativeJS( 3343): Handling re-frame event: :incoming-message
12-01 15:07:50.134 D/ReactNativeJS( 3343): DEBUG [status-im.protocol.handlers:77] - :incoming-message :sent
12-01 15:07:50.134 I/ReactNativeJS( 3343): Handling re-frame event: :message-sent
12-01 15:07:50.164 D/ReactNativeJS( 3343): DEBUG [status-im.protocol.web3.delivery:134] - :delivery-callback
12-01 15:07:50.164 I/ReactNativeJS( 3343): Handling re-frame event: :incoming-message
12-01 15:07:50.164 D/ReactNativeJS( 3343): DEBUG [status-im.protocol.handlers:77] - :incoming-message :sent
12-01 15:07:50.164 I/ReactNativeJS( 3343): Handling re-frame event: :message-sent
12-01 15:07:50.244 I/ReactNativeJS( 3343): Handling re-frame event: :set
12-01 15:07:50.374 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:50.434 D/ViewRootImpl( 3343): ViewPostImeInputStage processPointer 0
12-01 15:07:50.714 D/ViewRootImpl( 3343): ViewPostImeInputStage processPointer 1
12-01 15:07:50.894 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:51.304 D/ViewRootImpl( 3343): ViewPostImeInputStage processPointer 0
12-01 15:07:51.404 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:51.824 D/ViewRootImpl( 3343): ViewPostImeInputStage processPointer 1
12-01 15:07:51.944 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:52.444 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:52.964 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:53.484 I/ReactNativeJS( 3343): Handling re-frame event: :update-sync-state
12-01 15:07:53.744 I/INSTABUG - a( 3343): invokeGeneral
12-01 15:07:53.744 I/Timeline( 3343): Timeline: Activity_launch_request id:im.status.ethereum time:43326304
12-01 15:07:53.784 D/SensorManager( 3343): unregisterListener ::   
12-01 15:07:53.784 D/RelationGraph( 3343): garbageCollect()
12-01 15:07:53.784 W/ResourcesManager( 3343): getTopLevelResources: /data/app/im.status.ethereum-1/base.apk / 1.0 running in im.status.ethereum rsrc of package im.status.ethereum

```

**Current View:** 	 im.status.ethereum.MainActivity

[![image attachment](https://s3.amazonaws.com/instabug-pro/states/files/39109224/screenshots/642e5d2bba8cd65eb429aabe1a042ae0_original.jpg?1480576180)](https://s3.amazonaws.com/instabug-pro/states/files/39109224/screenshots/642e5d2bba8cd65eb429aabe1a042ae0_original.jpg?1480576180)
[![image attachment](https://s3.amazonaws.com/instabug-pro/states/files/39109224/screenshots/57a71e48865a8f9d5c339c8b916a4dba_original.jpg?1480576181)](https://s3.amazonaws.com/instabug-pro/states/files/39109224/screenshots/57a71e48865a8f9d5c339c8b916a4dba_original.jpg?1480576181)
[![image attachment](https://s3.amazonaws.com/instabug-pro/states/files/39109224/screenshots/8583206135fead4c6557083a2f6d933f_original.jpg?1480576184)](https://s3.amazonaws.com/instabug-pro/states/files/39109224/screenshots/8583206135fead4c6557083a2f6d933f_original.jpg?1480576184)

**Comment by jarradh** [comment]
Doesn't appear to be GUI error
https://testnet.etherscan.io/address/0x85148c1ce364cfd3c028fc88eac0caf234979c14

**Comment by rasom** [comment]
1) add a new transaction using "Scan QR" option in wallet dapp
2) press back from transactions confirmation screen
3) add another transaction in the chat
4) confirm two transactions at once

In result, I have only one transaction message in chat history but two transactions are sent. I don't know it it is the bug, and I'm not sure that this is your scenario. Haven't found another way to reproduce this.

**Comment by jarradh** [comment]
i literally went 
- tap on command icon
- tap on send
- type in 0.1 and tap send , then tap send again.
- went to wallet to check and oh...

**Comment by jarradh** [comment]
the only thing I could have done differently was i was switching accounts before and sending between them on the same phone

**Comment by Jas0n-F** [comment]
@rasom 

iOS user reported this bug again last night, still a closed issue?

https://instabug.com/applications/status/beta/bugs/99?status=New

**Comment by rasom** [comment]
@Jas0n-F , yes, the user reported a similar bug but we have to investigate what exactly happened this time. Better to create a new issue.
