### ISSUE TITLE
Welcome screen is missing after sign in

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5288]
### Description

*Type*: Bug
*Summary*: after first sign in user should see welcome screen (design is [here](https://zpl.io/be4M3DP))

#### Expected behavior
after sign in: 
![welcome new](https://user-images.githubusercontent.com/37297779/43415567-4867abf6-940c-11e8-9a76-1f37ecdc3577.png)

#### Actual behavior
<img width="568" alt="2" src="https://user-images.githubusercontent.com/4557972/43194155-682a3e28-900a-11e8-8fc6-ac7464266c90.png">

### Reproduction

- Install Status Desktop
- Create new account
- Allow Keychain access
- Sign in and check content of the Home tab

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: status desktop 23/07/2018
* Operating System: Mac OSx
* Note: should be related to  [#5169] Remove Mixpanel (commit: bb7d31a) (detail / githubweb)
Already reported and fixed in mobile app (#5211)

**Comment by EugeOrtiz** [comment]
@churik  I updated this screen based on findings from user feedback. To keep it simpler, I removed some extra elements. Here is the new design >> **zpl.io/V0yk4QQ** (Zeplin)

![welcome new](https://user-images.githubusercontent.com/37297779/43415567-4867abf6-940c-11e8-9a76-1f37ecdc3577.png)

**Comment by churik** [comment]
Still reproducible

**Comment by churik** [comment]
still relevant
