### ISSUE TITLE
Constant error 'Could not connect to mailserver' if mailserver B is selected

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5292]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Error 'Could not connect to mailserver' if mailserver B is selected both on Ropsten and on Mainnet. If tap to reconnect same error is shown again after ~15 sec

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can connect to mailserver B
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error 'Could not connect to mailserver' if mailserver B is selected 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Profile -> Advanced -> Mailserver -> select B in the list and log in again
- send some message in public chat or 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build from July 25 and released 0.9.23
* Operating System: Android and iOS

#### Logs
[geth.log](https://github.com/status-im/status-react/files/2227768/geth.log)

TF session https://app.testfairy.com/projects/4803622-status/builds/8535945/sessions/4397063332/?accessToken=odMvWwYyeDXoaClyv/Fl9WlvCSg

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8535945/sessions/4397063332/?accessToken=odMvWwYyeDXoaClyv/Fl9WlvCSg">TestFairy: Status 0.9.23 (6249) @2018</a></strong></div></blockquote>

**Comment by divan** [comment]
Seems like this particular mailserver has stuck and stopped processing incoming requests. For now, we just restarted the container, but here are some logs from affected server for future investigation:

Logs before it happened:

a lot of 
`bad envelope received, peer will be disconnected peer=4c4ee27f706a35ad err="very old message"` 
messages, followed by

`failed to send direct message to peer: write tcp 10.18.0.9:30504->88.207.194.215:49560: use of closed network connection`

<img width="2372" alt="screen shot 2018-07-25 at 14 51 15" src="https://user-images.githubusercontent.com/880202/43202136-dc709b0a-901a-11e8-89b2-ca64acb38831.png">

**Comment by adambabik** [comment]
Yesterday, we restarted a container running Mailserver B as it was not responding, after that, we noticed logs suggesting successful delivery of stored messages.

I checked this on today's nightly and Mailserver B worked fine. I did not see any errors and messages synced.

**Comment by asemiankevich** [comment]
work for me in today's nightly as well http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a586d1-n-fl.apk

<blockquote></blockquote>

**Comment by annadanchenko** [comment]
no issue with mailserver B anymore
