### ISSUE TITLE
Status logo is shown and no other screens if run Android app first time

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5299]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Only Status logo screen is shown for ~3-5 minutes if run Android mobile Status app for the first time, after this system proposes to Wait or stop the app. If stop and then launch app then on 2nd-3rd attempt it shows expected Welcome screen with Create account button

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can see screen with create account button
#### Actual behavior
[comment]: # (Describe what actually happened.)
only status logo screen is shown and no more screens even if wait for 1 minute

![screenshot_20180725-184037 1](https://user-images.githubusercontent.com/6584810/43214900-f958a8d2-903a-11e8-9766-bc9fddd7d0da.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status on Android device 
- Run the app

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly https://jenkins.status.im/job/status-react/job/nightly/521/
* Operating System: Android only, works fine on iOS
tested on real Samsung Galaxy S6 (android 6.0.1) and Pixel XL (Android 8.1.0)

#### Logs
[logcat.txt](https://github.com/status-im/status-react/files/2228781/logcat.txt)

<blockquote><img src="/static/b5b8e6f2/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/521/">status-react » nightly #521 [Jenkins]</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
looks  good to me in http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-0aaf20-n-fl.apk

<blockquote></blockquote>

**Comment by annadanchenko** [comment]
also can't reproduce on new nightly and what's strange on the same nightly where it happened yesterday. As @yenda suggested might be an issue with TestFairy
