### ISSUE TITLE
Please scan a valid contact code error shown when tapping Start a new chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5301]
### Description
_Type_: Bug

_Summary_: `Please scan a valid contact code` error shown when tapping Start a new chat

#### Expected behavior
No errors shown when i did not scan anything yet

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/43252321-db53cf66-90ca-11e8-9a5c-2579f3cc9724.png)

### Reproduction

* Open Status
* Tap start new chat

### Additional Information

* Status version: nightly Jul 26 http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-0aaf20-n-fl.apk
* Operating System: both

<blockquote></blockquote>

**Comment by rachelhamlin** [comment]
Still happens now with error message `Please enter or scan a valid contact code or username`.

Also, when I go back a screen and then return, the error has not cleared.

**Comment by Swader** [comment]
Not resolved.

**Comment by asemiankevich** [comment]
no longer valid
