### ISSUE TITLE
Implement chat secondary actions on left panel

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5311]
**Story**
As a user, I want to be able to find secondary actions on 1:1 and public chats when I right-click on the user's row on the left panel.

**Actual behaivor**
Nothing happens when right clicking on a 1:1 or public chat row on left panel.

**Expected behavior**
When right clicking on "Super Violet Coordinated" row:
<img width="813" alt="captura de pantalla 2018-07-26 a la s 4 02 01 p m" src="https://user-images.githubusercontent.com/37297779/43282714-4398bd76-90ed-11e8-8c5a-540a956bc203.png">
When right clicking on "#peoplewholovedogs" row:
<img width="375" alt="captura de pantalla 2018-07-26 a la s 4 06 20 p m" src="https://user-images.githubusercontent.com/37297779/43282935-dc31e440-90ed-11e8-9173-9c1f02fb120a.png">
Note: This behavior was observed on most of participants during [usability test](https://docs.google.com/document/d/1Ny4QRw7zLSmH5rO8ZhwU313BlbWhGGwOj4FTIPwh2tQ/edit?pli=1).
Designs (Zeplin) >> zpl.io/V4J4NX4

**Comment by chadyj** [comment]
Question.... is this a custom styled menu, or can we use system menu?

**Comment by EugeOrtiz** [comment]
I tweaked the style a little bit (more space, highlight based on our color palette). A good-enough V1 could be using native ones.

**Comment by yenda** [comment]
@alwx you can check for right click in touchable highlight with

```
[react/touchable-highlight {:on-press #(when (= "right" (.-button (.-nativeEvent %)))
                                            (utils/show-popup "" "Message copied to clipboard")
                                            (react/copy-to-clipboard text))}
 [react/text "hello"]]
```
