### ISSUE TITLE
Implement public chat secondary actions on left panel

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5313]
**Story**
As a user, I want to be able to find secondary actions on public chats when I right-click on the chat's row on the left panel.

**Actual behavior**
Nothing happens when right clicking on a public chat row on left panel.

**Expected behavior**
When right clicking on "#peoplewholovedogs" row:
<img width="375" alt="captura de pantalla 2018-07-26 a la s 4 06 20 p m" src="https://user-images.githubusercontent.com/37297779/43282935-dc31e440-90ed-11e8-9173-9c1f02fb120a.png">

Designs (Zeplin) >> zpl.io/2vlrMQe

**Comment by churik** [comment]
merged with https://github.com/status-im/status-react/issues/5311
