### ISSUE TITLE
Implement secondary actions on public and 1:1 chat headers

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5314]
**Story**
As a user, I want to be able to perform some actions (clear history, delete chat) on a chat conversation (1:1 and public).

**Current behavior**
<img width="1086" alt="captura de pantalla 2018-07-26 a la s 4 09 52 p m" src="https://user-images.githubusercontent.com/37297779/43283141-71722b3c-90ee-11e8-9255-d4fe0c3cbf6a.png">

**Expected behavior**
<img width="805" alt="captura de pantalla 2018-07-26 a la s 4 11 08 p m" src="https://user-images.githubusercontent.com/37297779/43283164-88416e4a-90ee-11e8-8b06-4c00d0456c7a.png">

To implement:
- Ellipsis (...) icon
- Dropdown/popup menu

Designs (Zeplin) 
1:1 chat >> zpl.io/V4J4NX4
Public chat >> zpl.io/2vlrMQe

**Comment by chadyj** [comment]
Hey @alwx did you make any progress with this before things got busy with devcon?

Either way still interested, or should we unassign so someone else can grab?  cc @siphiuel

**Comment by chadyj** [comment]
Closed in https://github.com/status-im/status-react/pull/6671
