### ISSUE TITLE
Kill all pending http requests on logout

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#5316]
### User Story

As a user I want the fetched data for my different accounts on the same device to be kept separate.

### Description

Whenever user logs out, we should kill all pending http requests so that we would avoid the situations where a request is sent while user is logged in and response handled when he's logged out or logged in with a different account.

This issue is a generic fix for all issues like #5305

*Type*: Bug

**Comment by Swader** [comment]
Still important.
