### ISSUE TITLE
Make sure that actual config .env files are used to create binary distribution packages on Jenkins

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5317]
Make sure that MacOS app bundle and Linux AppImage are built on Jenkins pipeline with actual config .env files.

Currently, for Linux we use separate copy of .env file from `deployment` folder in git. For MacOS, seems, .env file from pre-uploaded .app bundle skeleton is used.

In both above cases .env files are not get updated automatically if default settings are changes for mobile project. This can have heavy impact on application behavior.

**Comment by churik** [comment]
Not a priority anymore
