### ISSUE TITLE
'Error: does not support name' staying on transaction fee screen > 3 min when sending TX to Dapp

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5324]
***Type***: Bug

***Summary***: When contact sends a transaction to Dapp the Send transaction wallet screen has an expiration time (~3 minutes). In a case when transaction times out while user is on the 'Trasaction Fee' screen - the `Error: does not support name` pop-up appears with no way to proceed using the app. 
On iOS this error appears for a very short time but then app is unresponsive. Need to re-open the app to keep use it again.
On Android pop-up with the error follows by blank screen. And again, the only way is only to re-open an app.
**Note:** In a case when wallet screen expires while contact is on the 'Send transaction'  screen, - it closes and user can proceed to use a Dapp on the last screen.

#### Expected behavior
Wallet screen disappears and user can proceed to use a Dapp on the last screen before he requested status app Wallet screen.

#### Actual behavior
'Error: does not support name' appears when wallet transaction fee screen expires while contact was on the transaction fee screen

<img width="366" alt="screen shot 2018-07-29 at 16 39 51" src="https://user-images.githubusercontent.com/8749671/43366961-133a6d7e-934e-11e8-984f-817d4807244f.png">

### Reproduction

- Open Status 
- Open 'Simple Status Dapp'
- Navigate to `Assets` and tap `Request STT`
- Navigate to 'Advanced' -> 'Transaction fee' screen
- Wait > 3 minutes (**Note:** it doesn't matter here whether you put the app on background and reopen it after, or keep an app on foreground, or switch between Send Transaction <-> Trasnaction Fee screen: error appears when transaction expires when you are on the Transaction Fee screen

### Additional Information
* Status version: Develop 0.9.24 (6259), Release 0.9.23
* Operating System: Android and iOS

#### Logs

https://app.testfairy.com/projects/4803622-status/builds/8539028/sessions/4397383326/?accessToken=1n3ov9Ejhrh4COl3Z2oewJ3/xZ0

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8539028/sessions/4397383326/?accessToken=1n3ov9Ejhrh4COl3Z2oewJ3/xZ0">TestFairy: Status 0.9.24 (6259) @2018</a></strong></div></blockquote>

**Comment by goranjovic** [comment]
After the changes in #5455 dapp transactions can no longer timeout, which incidentally fixes this issue too
