### ISSUE TITLE
Can't start the app - Status has crashed upon launch (Android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5326]
### Description

*Type*: Bug

*Summary*: Can't start the app - Status has crashed upon launch

![image](https://user-images.githubusercontent.com/28752642/43381510-950d370c-93dd-11e8-88f2-595a0d5c0754.png)

### Reproduction

- install http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a586d1-n-fl.apk
- Open Status

### Additional Information
* Status version: nightly http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a586d1-n-fl.apk

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by mandrigin** [comment]
@asemiankevich is it any specific device or does it do it on any Android?

**Comment by asemiankevich** [comment]
@mandrigin both my androids (7.0)

**Comment by mandrigin** [comment]
@asemiankevich can you try to rebuild the nightly and check if it persists? looks like something was built incorrectly...

**Comment by asemiankevich** [comment]
sure ! :)

**Comment by annadanchenko** [comment]
on new nightly build https://jenkins.status.im/job/status-react/job/nightly/527/ can launch app and create new account (real Pixel XL, Android 8.1.0)

<blockquote><img src="/static/b5b8e6f2/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/527/">status-react » nightly #527 [Jenkins]</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
https://jenkins.status.im/job/status-react/job/nightly/527/ looks good to me as well, closing

<blockquote><img src="/static/b5b8e6f2/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/527/">status-react » nightly #527 [Jenkins]</a></strong></div></blockquote>
