### ISSUE TITLE
"Connection is not proven secure" for HTTPS secure website

### ISSUE THREAD

**Issue by leonprou** [status-im/status-react#5327]
**Type**: Bug

**Summary**:
Our Dapp has a HTTPS certificate -  https://communities.colu.com/, It looks good both on Chrome and safari. But for some reason the Status Browser shows that the connection ins't secure.

Additional Information:
Status version: Develop 0.9.22 (6182)
Operating System: Android

<blockquote><div><strong><a href="https://communities.colu.com/">CLN Community App</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Confirmed in latest develop build that it's not an issue anymore (we fixed it in #5331).
It will OK with the next release.
Closing for now.
