### ISSUE TITLE
Embed GA on docs.status.im

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5332]
### User Story

As a core team member, I want to see which pages of Status developer docs are most trafficked so that I can gauge the popularity of our tools and the usability of the site.

### Description

*Type*: Feature

*Summary*: We use Google Analytics on the Status site and blogs to measure traffic. Doing the same for developer docs will give us important insight into the interest of the dev community.

*GA tracking ID*
`UA-79146816-6`

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-79146816-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-79146816-6');
</script>
```

#### Expected behavior
GA tracking added to head tags of docs.status.im.

#### Actual behavior
No tracking yet

**Comment by jeluard** [comment]
Done (https://github.com/status-im/docs.status.im/commit/d7dc6d9225d28ebd468e94543d23fd99351e6d94)
