### ISSUE TITLE
Status-react Desktop should use clj-rn

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5339]
Use clj-rn instead of re-natal for dev build of status-react Desktop

### User Story

As a developer, I want to use brand new clj-rn instead of re-natal for dev build of status-react Desktop and figwheel ( ? ) enabling on dev build.

### Description

*Type*: Feature
*Summary*: Replace re-natal with clj-rn

#### Expected behavior
No more hustles with re-natal - lets use clj-rn!

#### Actual behavior
re-natal is used for dev build with fighweel repl

**Comment by maxhora** [comment]
Related to https://github.com/status-im/clj-rn/issues/8

**Comment by dmitryn** [comment]
@vkjr how things are going with this one? As a developer for both mobile and desktop platforms, i'd really like `clj-rn` to work for desktop too. 

I can work on clj-rn support for desktop if you didn't start with this one yet.

**Comment by vkjr** [comment]
I didn't. Thanks for taking this!
