### ISSUE TITLE
Support nightly builds for Desktop

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5342]
As user, I want be able to download status-react Desktop nightly builds from https://status-im.github.io/nightly/

Currently we don't have nightly builds for Desktop project.

**Comment by chadyj** [comment]
cc @jakubgs Help please :)

**Comment by chadyj** [comment]
Done! https://status-im.github.io/nightly/

<blockquote><div><strong><a href="https://status-im.github.io/nightly/">Status.im Nightly Builds</a></strong></div></blockquote>
