### ISSUE TITLE
Some chars are shown as squares in messages 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5344]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see that all chars are handling correctly regardless of language/ chars I'm using

### Description

*Type*: Bug

*Summary*:  squares are displayed  instead of chars in desktop messages.
Examples of chars:
- ❗ Ꞁ  ⅇ ⅊  ⚭ ⚮ ⏠ ⏡ ⏦ ⥰  ⥸ ⥹ ⥺ ⥻ ⥼ ⥽ ⥾ ⥿ ♾ ⎌ ⍼ ⍿ ⎀ ⎁ ⎂ ⎃ ⎄ ⎅ ⎆ ⎉ ⎊ ⎍ ⎎ ⎏ ⎐ ⎑ ⎒ ⎓  ⎖ ⎲ ⎳ ⎴  ❨ ❩ ⸨ ⸩ ❪ ❫ ❮ ❯ ❬ ❭ ❰ ❱ ⎵ ⎶ ⎸ ⎹ ⎺ ⎻  ⏍ ⏐ ⏤ ɂ Ɂ ẟ Ɀ Ȿ ꜠ ꜡ ỻ ℾ ℿ ⅀ ꝋ ꜿ Ꜿ ⱽ ⱺ ⱹ ⱷ ⱶ Ⱶ ⱴ ⱱ Ɒ ⱦ ỽ ⸀ ⸁ ⸂ ⸃ ⸄ ⸅ ⸆ ⸇ ⸈ ⸉ ⸊ ⸋ ⸌ ⸍ ⸎ ⸏ ⸐ ⸑ ⸒ ⸔ ⸕
- figures: ◿ ◺ ◹ ◸ ⟁ ⧋ ⧊ ⧩ ⧨ ⎔ ⎕ ⏣  ⏥ ⏢ ⬖ ⬗ ⬘ ⬙ ⬠ ⬡ ⎔ ⋄ ◊ ⧫ ⬢ ⬣ ▰ ▪ ◼ ▮ ◾ ▗ ▖ ■ ∎  ⬓  ⬒  ◰ ◱ ◳ ◲ ⧇ ⧅ ⧄ ⟡ ⧉ ⦶ ⦸ ◵ ◴ ◶ ◷ ⦇ ⦈ ⦉ ⦊ ⌓ ◦ ⧓ ⧗ ⧑ ⧒ ⧖
- harpoons:  ⥦ ⥧ ⥨ ⥩ ⥪ ⥫ ⥬ ⥭ ⥮ ⥯
- arrows: ⇫ ⇬ ⇭ ⇮ ⇯ ⇱ ⇲ ⇳ ⇴ ⇵ ⇶ ⇷ ⇸ ⇹ ⇺ ⇻ ⇼ ⇽ ⇾ ⇿ ⟰ ⟱ ⟲ ⟳ ⟴ ⟵ ⟶ ⟷ ⟸ ⟹ ⟺ ⟻ ⟼ ⟽ ⟾ ⟿ ⤀ ⤁ ⤂ ⤃ ⤄ ⤅ ⤆ ⤇ ⤈ ⤉ ⤊ ⤋ ⤌ ⤍ ⤎ ⤏ ⤐ ⤑ ⤒ ⤓ ⤔ ⤕ ⤖ ⤗ ⤘ ⤙ ⤚ ⤛ ⤜ ⤝ ⤞ ⤟ ⤠ ⤡ ⤢ ⤣ ⤤ ⤥ ⤦ ⤧ ⤨ ⤩ ⤪ ⤫ ⤬ ⤭ ⤮ ⤯ ⤰ ⤱ ⤲ ⤳ ⤸ ⤺ ⤻ ⤼ ⤽ ⤾ ⤿ ⥀ ⥁ ⥂ ⥃ ⥄ ⥅ ⥆ ⥇ ⥈ ⥉ ⥊ ⥋ ⥌ ⥍ ⥎ ⥏ ⥐ ⥑ ⥒ ⥓ ⥔ ⥕ ⥖ ⥗ ⥘ ⥙ ⥚ ⥛ ⥜ ⥝ ⥞ ⥟ ⥠ ⥡ ⥱ ⥲ ⥳ ⥴ ⥵ ⥶ ⥷ ⬀ ⬁ ⬂ ⬃ ⬄ ⬈ ⬉ ⬊ ⬋ ⬌ ⬍ ⬎ ⬏ ⬐ ⬑
- digram symbols: ⚌ ⚍ ⚎ ⚏
- metrical symbols: ⏑ ⏒ ⏓ ⏔ ⏕ ⏖ ⏗ ⏘ ⏙
- all symbols with palatal hooks : ᶀ ᶁ ᶂ ᶃ ᶄ ᶆ ᶇ ᶈ ᶉ ᶊ ᶋ ᶌ ᶍ ᶎ ᶏ ᶐ ᶑ ᶒ ᶓ ᶔ ᶕ ᶖ ᶗ ᶘ ᶙ ᶚ
- all symbols with middle tilde: ᵯ ᵰ ᵴ ᵶ ᵹ ᵼ ᵽ ᵾ ᵿ
- some greek letters: Ͱ ͱ Ͳ ͳ Ͷ ͷ ͻ ͼ ͽ ϼ Ͻ Ͼ Ͽ
and some others.
I suppose that is because of fonts we are currently using. All symbols are displaying correctly in IOS and Android.
AFAIK we plan to change font in #4860 
Can we please check, are these symbols presented in this fonts before applaying it? 

#### Expected behavior
all symbols are displayed 

#### Actual behavior
some symbols are replaced by squares (missing in fonts)
<img width="568" alt="chd" src="https://user-images.githubusercontent.com/4557972/43460348-08996f82-94d9-11e8-8975-e3ec26ef5362.png">

### Reproduction

- Open Status
- Join any public chat
- Send one message containing several symbols, mentioned in description

### Additional Information
* Status version: status desktop 31/07/18
* Operating System: Mac OSx

**Comment by churik** [comment]
should be verified when https://github.com/status-im/status-react/issues/4860 was fixed

**Comment by churik** [comment]
still reproducible.

**Comment by rasom** [comment]
QT 5.11.2 fixes it, that's not `status-react`'s issue

**Comment by rasom** [comment]
https://github.com/status-im/status-react/issues/6053

**Comment by churik** [comment]
some of then missing also on IOS, not sure that we support them.
Closed for now, most of them are currently displayed with QT upgrade
