### ISSUE TITLE
Topic is not clickable in "Selected for you" until focus isn't in "Topic" field

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5345]
### User Story

As a user, I want to choose any chat from "Selected for you" by clicking on it
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: user cannot go to selected chat when focus is out of "Topic" field.

#### Expected behavior
selected chat is shown

#### Actual behavior
topic is not clickable
<img width="568" alt="topi" src="https://user-images.githubusercontent.com/4557972/43460994-f0db1506-94da-11e8-8773-8d2bbb069234.png">

### Reproduction

- Open Status
- Tap on + 
- Select any topic below "Selected for you", which are not presented in chat list

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: status desktop build 
* Operating System: Mac OSx
* Video: [selectedTopic](http://take.ms/Nd1cQ)

**Comment by EugeOrtiz** [comment]
@churik I think this is working now.

**Comment by churik** [comment]
Yes, agree, thanks @EugeOrtiz
