### ISSUE TITLE
Use time format according to 12/24h device settings

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5347]
Based on #5158.

### User Story

As a user, I want to see timestamps in Status app according to time format chosen by me in phone settings.

### Description

*Type*: Feature
*Summary*: now settings are different in IOS (always 24h) and Android (always 12h for 
 Samsung Galaxy S7, Android 7.0) and they don't depend on device settings.
I suggest to implement detection of user settings (implemented in Telegram, WhatsApp)

#### Expected behavior
timestamps are changed according to user settings

#### Actual behavior
![andr](https://user-images.githubusercontent.com/4557972/43143679-fec3ed36-8f63-11e8-8d62-002e06b89dca.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
*Prerequisites:* 24H format is set
- Open Status, join to several chat
- Change time to 12 H in User settings (General > Date and time)
- reopen Status
- pay attention to timestamps in chat.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 31/07/18
* Operating System: Android, iOS

**Comment by tbenr** [comment]
Already working on this

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 3500.00
Contract address: [0x30110b263e63b1bb9e688b78aabf13f4c92e86ab](https://etherscan.io/address/0x30110b263e63b1bb9e688b78aabf13f4c92e86ab)
Network: Mainnet
Paid to: tbenr
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by mpandam123** [comment]
working

**Comment by pablanopete** [comment]
@tbenr Will need to follow up with you manually like before, does the same address work well for you?

**Comment by tbenr** [comment]
Ok! Yes same address. Thanks!

**Comment by pablanopete** [comment]
Payment sent!
