### ISSUE TITLE
Adding a Recovery phrase and password on a fresh new install throws Error and freezes app with a blank screen

### ISSUE THREAD

**Issue by infebe** [status-im/status-react#5353]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When installing for the first time the application on an Android device and selecting the "I already have an account" option from the first welcome screen, if we insert a random Recovery phrase and password and hit "Sign in", the application throws:
 "Error: No item 1 in vector of length 1 
   This error is located at: 
   in home
   in reagent24
   in RCTView
   in RCTView
..."

![whatsapp image 2018-08-01 at 12 21 38](https://user-images.githubusercontent.com/23058833/43516335-949911d4-9585-11e8-8a0a-aeeff49afe20.jpeg)

Then, the welcome dialog is shown and when hitting ok, the dialog disappears and what is left is a blank screen that does nothing. To continue using the app, it is necessary to hit the back button to exit the app, and relaunch it. 

This issue was reproducible with three different Android devices. Not been able to check on iOS devices.

The issue was reproduced 3 times/3 attempts.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The expected behavior was to either have a new account created from the random data introduced or a dialog saying that this account does not exist.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Error is thrown and an unresponsive blank screen is shown.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
To reproduce the bug it is necessary to install the application on a device that has never had the application installed before. Once installed, open the application and select "I ALREADY HAVE AN ACCOUNT". On the "Sign in to another account" screen, insert a random recovery phrase and password. In this case it was used: "t t t t t t t t t t t t" "popopopopo". Hit "Sign in", and then the Error Dialog will pop up. Here is a video with all the sequence:
https://drive.google.com/file/d/1FS1QxLrJxWNaXtsrAW8wruTE5YNRVmZ2/view?usp=sharing

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.23 July 23
* Operating System: Android
* Devices: Nexus 5 with Android 6.0.1, Zebra TC200J with Android 7.1.2, Moto X Play with Android 7.1.1
* Might be related to bug https://github.com/status-im/status-react/issues/5232

<blockquote><img src="https://lh5.googleusercontent.com/hu3Ns4-LY4zHuFd9gVvfsS-1FjVrVulyUrK-AZQjrmEbNEtXTRvoyYqHGOQ=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1FS1QxLrJxWNaXtsrAW8wruTE5YNRVmZ2/view?usp=sharing&usp=embed_facebook">error_status_app.mp4</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
@infebe thank you for the bug report! 
Can you specify exact Status version including number in () and the source used to install it (PlayStore, nightly build link, etc), please?

**Comment by infebe** [comment]
@annadanchenko You are welcome! :) The Status version was 0.9.23 (6238),  installed using the build available in the PlayStore.

**Comment by lukaszfryc** [comment]
I just replicated it on 0.9.25 version when recovering an account. I installed the app, created new account and use it for ~1 hour, then I recovered my old account and got this error. I had to kill the app and log in again to make it work.

**Comment by annadanchenko** [comment]
@infebe can you reproduce the bug again and attach the logcat log, please? It looks like not on all devices it can be constantly reproduced, so log from your device would be really helpful.

**Comment by infebe** [comment]
To reproduce the same conditions as when I reported the problem, I looked for the build version I had used back then. I have not found the exact version 0.9.23(6238), but the closest I have found is version 0.9.23 (6234). I have had access to this build in the website http://artifacts.status.im:8081/artifactory/nightlies-local/ and it has the name "im.status.ethereum-2d6fdc-rel.apk" with date of 23-Jul-2018 02:37 . This said, the steps to reproduce the problem have been:
- Factory reset the phone
- Install Status 
- On the main screen select "I already have an account"
- On the Sign In screen insert random Phrase and Password (it is important that this random phrase and password have not been used before)
- The error appears, as well as the "Welcome dialog"

The difference this time is that the blank screen appears and when you hit 'Back' you are not forced to get out of the application. It appears a screen with the created user and the box to insert the Password, in other words, the login screen for when you have only one account in the phone.

Here is the log with the exception: 
```
08-11 11:29:27.383 13373-13447/? I/ReactNativeJS: PRETTY PRINTED EXCEPTION
   
    ***
    NAME: "Error"
    MESSAGE: Error: No item 1 in vector of length 1
   
    This error is located at:
        in home
        in reagent24
        in RCTView
        in RCTView
        in main-tabs
        in reagent23
        in RCTView
        in main
        in root
        in reagent1
        in RCTView
        in RCTView
        in t
   
    vector_index_out_of_bounds@index.android.bundle:12:479619
    array_for@index.android.bundle:12:480197
    cljs$core$IIndexed$_nth$arity$2@index.android.bundle:12:486163
    cljs$core$IFn$_invoke$arity$2@index.android.bundle:12:145042
    cljs$core$ICollection$_conj$arity$2@index.android.bundle:12:557664
    _conj@index.android.bundle:12:144166
    cljs$core$IFn$_invoke$arity$2@index.android.bundle:12:228761
    index.android.bundle:12:660482
    cljs$core$IFn$_invoke$arity$4@index.android.bundle:12:214798
    cljs$core$IReduce$_reduce$arity$2@index.android.bundle:12:220999
    cljs$core$IFn$_invoke$arity$2@index.android.bundle:12:266224
    cljs$core$IFn$_invoke$arity$variadic@index.android.bundle:12:660416
    G__29783_29793@index.android.bundle:12:4803112
    index.android.bundle:12:2490223
    index.android.bundle:12:2490235
    in_context@index.android.bundle:12:2290289
    deref_capture@index.android.bundle:12:2290432
    _run@index.android.bundle:12:2310954
    cljs$core$IDeref$_deref$arity$1@index.android.bundle:12:2315940
    _deref@index.android.bundle:12:153854
    deref@index.android.bundle:12:211756
    index.android.bundle:12:7906463
    index.android.bundle:12:2325056
    wrap_render@index.android.bundle:12:2325737
    do_render@index.android.bundle:12:2326919
    index.android.bundle:12:2327472
    in_context@index.android.bundle:12:2290289
    deref_capture@index.android.bundle:12:2290432
    run_in_reaction@index.android.bundle:12:2318765
    index.android.bundle:12:2327413
    f@index.android.bundle:143:83728
    beginWork@index.android.bundle:143:87321
    o@index.android.bundle:143:128242
    a@index.android.bundle:143:128621
    T@index.android.bundle:143:132129
    y@index.android.bundle:143:131565
    v@index.android.bundle:143:131402
    h@index.android.bundle:143:130681
    c@index.android.bundle:143:129935
    enqueueForceUpdate@index.android.bundle:143:60452
    forceUpdate@index.android.bundle:109:1315
    run_queue@index.android.bundle:12:2285981
    flush_queues@index.android.bundle:12:2287253
    run_queues@index.android.bundle:12:2287400
    index.android.bundle:12:2286829
    index.android.bundle:126:1369
    x@index.android.bundle:126:643
    callTimers@index.android.bundle:126:2788
    value@index.android.bundle:121:3582
    index.android.bundle:121:1067
    value@index.android.bundle:121:3009
    value@index.android.bundle:121:1039
    [native code]
   
    ***
```

Here is  the complete Logcat, just in case there is  more information that might help.
[2018-08-11_1129_LogCat_Error_No_Item_1_in_vector.txt](https://github.com/status-im/status-react/files/2280142/2018-08-11_1129_LogCat_Error_No_Item_1_in_vector.txt)

Device used: Zebra TC200J with Android 7.1.2

I have also tried the version 0.9.23 (6234) on an Samsung S8, Android 8.0.0, but I had put the same credentials I had used in a previous test. Here the error didn't appear. 

However, I must say that I have not been able to reproduce this error with these steps, with the latest version in the Google Play Store: 0.9.25 (6360). The tests I have done have been:
- Installing the application in an Android device that never had the Status app installed before: Asus Zenfone 2 Laser KE500KL with Android 6.0.1
- The procedure explained in this post, using Factory Reset on the device Zebra TC200J with Android 7.1.2.



<blockquote><div><strong><a href="http://artifacts.status.im:8081/artifactory/nightlies-local/">Index of nightlies-local/</a></strong></div></blockquote>

**Comment by infebe** [comment]
Following the steps from @lukaszfryc I have been able to reproduce the error in the latest version of Google Play Store: 0.9.25 (6360).

Here is the log with the exception:
```

08-11 13:05:23.820 13786-13864/? I/ReactNativeJS: PRETTY PRINTED EXCEPTION
    
    ***
    NAME: "Error"
    MESSAGE: Error: No item 1 in vector of length 1
    
    This error is located at:
        in home
        in reagent26
        in RCTView
        in RCTView
        in main-tabs
        in reagent25
        in RCTView
        in main
        in root
        in reagent1
        in RCTView
        in RCTView
        in t
    
    vector_index_out_of_bounds@index.android.bundle:12:479619
    array_for@index.android.bundle:12:480197
    cljs$core$IIndexed$_nth$arity$2@index.android.bundle:12:486163
    cljs$core$IFn$_invoke$arity$2@index.android.bundle:12:145042
    cljs$core$ICollection$_conj$arity$2@index.android.bundle:12:557664
    _conj@index.android.bundle:12:144166
    cljs$core$IFn$_invoke$arity$2@index.android.bundle:12:228761
    index.android.bundle:12:660482
    cljs$core$IFn$_invoke$arity$4@index.android.bundle:12:214798
    cljs$core$IReduce$_reduce$arity$2@index.android.bundle:12:220999
    cljs$core$IFn$_invoke$arity$2@index.android.bundle:12:266224
    cljs$core$IFn$_invoke$arity$variadic@index.android.bundle:12:660416
    G__29779_29789@index.android.bundle:12:4798345
    index.android.bundle:12:2487223
    index.android.bundle:12:2487235
    in_context@index.android.bundle:12:2287289
    deref_capture@index.android.bundle:12:2287432
    _run@index.android.bundle:12:2307954
    cljs$core$IDeref$_deref$arity$1@index.android.bundle:12:2312940
    _deref@index.android.bundle:12:153854
    deref@index.android.bundle:12:211756
    index.android.bundle:12:7872628
    index.android.bundle:12:2322056
    wrap_render@index.android.bundle:12:2322737
    do_render@index.android.bundle:12:2323919
    index.android.bundle:12:2324472
    in_context@index.android.bundle:12:2287289
    deref_capture@index.android.bundle:12:2287432
    run_in_reaction@index.android.bundle:12:2315765
    index.android.bundle:12:2324413
    f@index.android.bundle:143:83728
    beginWork@index.android.bundle:143:87321
    o@index.android.bundle:143:128242
    a@index.android.bundle:143:128621
    T@index.android.bundle:143:132129
    y@index.android.bundle:143:131565
    v@index.android.bundle:143:131402
    h@index.android.bundle:143:130681
    c@index.android.bundle:143:129935
    enqueueForceUpdate@index.android.bundle:143:60452
    forceUpdate@index.android.bundle:109:1315
    run_queue@index.android.bundle:12:2282981
    flush_queues@index.android.bundle:12:2284253
    run_queues@index.android.bundle:12:2284400
    index.android.bundle:12:2283829
    index.android.bundle:126:1369
    x@index.android.bundle:126:643
    callTimers@index.android.bundle:126:2788
    value@index.android.bundle:121:3582
    index.android.bundle:121:1067
    value@index.android.bundle:121:3009
    value@index.android.bundle:121:1039
    [native code]
    
    ***
`

```
Here is the complete Logcat:
[2018-08-11_1305_LogCat_Error_No_Item_1_in_vector.txt](https://github.com/status-im/status-react/files/2280164/2018-08-11_1305_LogCat_Error_No_Item_1_in_vector.txt)

Device: Zebra TC200J with Android 7.1.2.

**Comment by goranjovic** [comment]
Managed to consistently reproduce it by tapping the Sign in button rapidly in PR #5494. The root underlying issue was an interface mismatch between subscription functions that became visible when multitapping brought the app to an invalid state. 

I (hopefully) fixed both problems in that PR - being able to multitap and the mismatch issue. As a follow up, we should make sure to check other places where a similar thing can happen - new issue for it is here: #5576
