### ISSUE TITLE
Transactions sent to known token contracts should display the contract name as recipient

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#5354]
### User Story

As a user I want to see a human readable contract/token name in Wallet Send and Transaction History when I interact with a smart contract.

### Description

*Type*: Feature

#### Expected behavior

- Wallet Send displays token (or smart contract) name in addition to the address when transactions are being sent to a contract (i.e. contract methods are invoked)
- Transaction history displays token/contract name in addition to the address (before token transfer info is fetched)

#### Actual behavior
- Wallet Send only shows the address
- Transaction history only shows the address (before token transfer info is fetched)

**Comment by Swader** [comment]
Not stale

**Comment by churik** [comment]
@flexsurfer still makes sense I believe?

**Comment by flexsurfer** [comment]
@churik probably, i don't see how it can be useful for a regular user

**Comment by cammellos** [comment]
Closing as this is going to be part of a large wallet redesign effort and stale
