### ISSUE TITLE
Include contact code deep link in Status invitation message

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5367]
### Description

*Type*: Feature

*Summary*: Currently, the invitation text says "Get Status at http://status.im". We could improve it by adding a deep link with the user user contact code so that he can be easily added after someone downloads the app. The text could say:

_Get Status at http://status.im and add click this link to message me!  https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx_ 

### Reproduction

- Click "+" button
- Click invite users 

### Additional Information
* Status version: 0.9.25
* Operating System: Android, iOS

<blockquote><div><strong><a href="http://status.im/">Status, a Mobile Ethereum OS</a></strong></div><div>Status is an interface to access Ethereum, built for Android & iOS. Enjoy encrypted messaging, a cryptocurrency wallet, and seamless access to DApps.</div></blockquote>
<blockquote><div><strong><a href="http://status.im/">Status, a Mobile Ethereum OS</a></strong></div><div>Status is an interface to access Ethereum, built for Android & iOS. Enjoy encrypted messaging, a cryptocurrency wallet, and seamless access to DApps.</div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx">View user 0x044166fa04e967e333211ae0cc1087c9c74exxx's profile in Status</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@chadyj wdyt?

**Comment by chadyj** [comment]
Nice one Lukasz!  @errorists is working on this right now and will have something to present soon.

**Comment by errorists** [comment]
@chadyj What about this flow we received in a bounty https://github.com/status-im/design/issues/2 ? It offers the advantage of connecting users without having to revisit the deep link after downloading and onboarding. However, it would require a backend service to work

**Comment by chadyj** [comment]
Would be great to first explore how to do this with depending on a central server.

**Comment by errorists** [comment]
Yeah agree. @obi2020 could you suggest an appropriate copy here for inviting users through a shared deep link?

**Comment by chadyj** [comment]
This is fixed now :) (or is WIP at least)
