### ISSUE TITLE
Upload button in Bounties Network dapp does not trigger upload menu

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5369]
### Description

*Type*: Bug

*Summary*: The "Upload" button in Bounties Network Dapp does not work on Android. Note that it works on iOS. Would be great to investigate is it's an issue with our webview or something to be fixed on the dapp side. If the latter, we should contact the Bounties Network devs.

<img src="https://user-images.githubusercontent.com/7532782/43635513-97ed6b56-970f-11e8-9176-c919eb7d711a.png" width="200">

#### Expected behavior
Upload options menu is shown

#### Actual behavior
Nothing happens when Upload button is clicked

### Reproduction

- Switch to Mainnet
- Go to Chat tab, click "+" and Open Bounties Network dapp
- Open "NEW BOUNTY" from the menu on the top right of the screen
- Click "Upload"

### Additional Information
* Status version: 0.9.24
* Operating System: Android
* Tested on: Samsung Galaxy S8, Android 7.1

**Comment by lukaszfryc** [comment]
Logcat when I click the Upload button:

```
08-06 07:15:10.497 3752-3968/? D/InputReader: Input event(5): value=1 when=992298968197000
    Input event(5): value=1 when=992298968197000
08-06 07:15:10.498 3752-3968/? I/InputReader: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.34735 ] when=992298968197000
08-06 07:15:10.500 3752-3967/? I/InputDispatcher: Delivering touch to (4158): action: 0x4, toolType: 1
    Delivering touch to (16245): action: 0x0, toolType: 1
08-06 07:15:10.500 16245-16245/? D/ViewRootImpl@8f94191[MainActivity]: ViewPostImeInputStage processPointer 0
08-06 07:15:10.597 3752-3968/? D/InputReader: Input event(5): value=0 when=992299068080000
    Input event(5): value=0 when=992299068080000
08-06 07:15:10.597 3752-3968/? I/InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=992299068080000
08-06 07:15:10.597 3752-3967/? I/InputDispatcher: Delivering touch to (16245): action: 0x1, toolType: 1
08-06 07:15:10.599 16245-16245/? D/ViewRootImpl@8f94191[MainActivity]: ViewPostImeInputStage processPointer 1
08-06 07:15:10.623 16245-16245/? D/InputMethodManager: HSI from window - flag : 0 Pid : 16245
08-06 07:15:10.623 3752-4551/? V/InputMethodManagerService: Client requesting input be hidden, flags : 0
    hideCurrentInputLocked - !shouldHideSoftInput
```

**Comment by jeluard** [comment]
Fixed in an upstream dependency.
