### ISSUE TITLE
Fetching messages gray status bar covers some part of clickable UI

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5371]
### Description

*Type*: Bug

*Summary*: When the gray status bar appears it covers buttons and makes some of them not clickable. Maybe we could improve how this status bar looks like and where it appears. Note, that the bar can be clickable in some cases like "Tap to reconnect" when you lost connection with your peers.

<img src="https://user-images.githubusercontent.com/7532782/43643697-6cbfbab6-972c-11e8-902b-a8c20e508ebd.png" width="200">

<img src="https://user-images.githubusercontent.com/7532782/43643761-a7bd90f2-972c-11e8-8e59-15823718c5a5.png" width="200">

#### Expected behavior
The status bar does not cover clickable UI. 

#### Actual behavior
The status bar prevents user from clicking "Add to contact" button or clicking on the first row in chat. 

### Reproduction

- Open Status
- Go offline (turn on Airplane mode) and online again 

### Additional Information
* Status version: 0.9.24
* Operating System: Android, iOS

**Comment by errorists** [comment]
I've posted a possible solution over here, wdyt? https://github.com/status-im/status-react/issues/4345

**Comment by lukaszfryc** [comment]
@errorists I like it a lot! 

Here are more cases for you to think of:

1) Snackbar in wallet informing about temporary issues like:

<img src="https://user-images.githubusercontent.com/7532782/45822968-e54afa00-bcec-11e8-8ca1-5bdfd4d93350.png" width="200">

2) Snackbar saying "Cannot sign message in offline mode" in the sign message screen:

<img src="https://user-images.githubusercontent.com/7532782/45823018-07dd1300-bced-11e8-9d99-f5d06699735b.png" width="200">

Do you think that we can use the same pattern for these cases?

**Comment by errorists** [comment]
@lukaszfryc Absolutely, as long as you're offline or otherwise can't establish a connection we should display this notification. I'll prepare a design doc with guidelines on how it can be used against both the light and blue navigation bars and with longer strings like those. 
Do we have a list somewhere with different types of connection states? I'd like to run it by @obi2020 to see if they can't be improved?

**Comment by lukaszfryc** [comment]
We have different states like "Connecting to peers", "Fetching messages", "Offline", etc. @mandrigin is there one place in the code where we can find those states?

**Comment by errorists** [comment]
Here's a solution I propose, whenever a snackbar is displayed we push down the underlying scroll view by the height of the snackbar like in [this prototype ](https://framer.cloud/MsLgV/)
Think of it as adding / removing an additional top padding to the scroll children or offseting the scroll position by the height of the snackbar. Once the snackbar is gone, we push it up to the default location. When the 'Add to contacts' button is present, the snackbar should be rendered below it [like so ](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1254%3A0)

**Comment by lukaszfryc** [comment]
> Here's a solution I propose, whenever a snackbar is displayed we push down the underlying scroll view by the height of the snackbar like in this prototype 

@errorists I like this idea. Also, changing colors of the snackbar when something is done (Connecting... -> Connected) is a nice UX  👍

**Comment by rachelhamlin** [comment]
@errorists @yenda I like the idea of pushing the rest of the view down to create room for the snack bar, but to my mind these blue versions with rounded edges look like buttons. They're static as well, right? 

Changing back to grey might help.

**Comment by yenda** [comment]
@rachelhamlin the buttons are just for the visualization they are not part of the design afaiu

**Comment by rachelhamlin** [comment]
@yenda @errorists ahh I see, and I didn't click. 🙄 Cool, these look great.

**Comment by rachelhamlin** [comment]
@yenda @siphiuel we didn't talk about this one during the call. Is it quick enough that we could do alongside TtT?
