### ISSUE TITLE
Words in messages do not line wrap

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5372]
**Story**
As a user, I want to be able to read the messages seamlessly.

**Current behavior**
Words are cut without a specific consideration besides the size of the "bubble" container. That makes a message hard to read:

<img width="368" alt="captura de pantalla 2018-08-03 a la s 10 22 13 a m" src="https://user-images.githubusercontent.com/37297779/43646113-58e703c2-970a-11e8-8793-c3d3b7a8629f.png">

**Expected behavior**
To cut the words using a word-wrapping method:

<img width="371" alt="captura de pantalla 2018-08-03 a la s 10 46 49 a m" src="https://user-images.githubusercontent.com/37297779/43646204-9fcb1e86-970a-11e8-9858-0936747eccad.png">

**Solution**
Implement a word-wrapping method so if a word doesn't fit in a "bubble" it is pushed to the next line.

**Comment by vkjr** [comment]
Will be fixed here - https://github.com/status-im/react-native-desktop/pull/311

**Comment by churik** [comment]
Fixed in 09/08/2018 nightly
