### ISSUE TITLE
ubuntu_process usage and creation should be documented and automated

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5378]
- ubuntu_process should be renamed to something more suitable like `nodejs_process`
- creation process of ubuntu_process should be documented (it has dependency on realm node.js native modules)
- binary creation should be automated for Jenkins builds

**Comment by chadyj** [comment]
> ubuntu_process should be renamed to something more suitable like nodejs_process

How about adding `status` in there so we can see it is related to Status?

**Comment by maxhora** [comment]
it should be fine, but since `ubuntu_process` is hardcoded in react-native-desktop:
1. react-native-desktop should has some more general naming for that (since it's library for general purposes)
2. react-native-desktop should be extended with possibility to customize title of that process, so we can name it as we want.

**Comment by churik** [comment]
@MaxRis what we can do with this issue?
There are some plans to get rid of separate `ubuntu-process` at all, do we still need this issue?

**Comment by maxhora** [comment]
@churik tracking of progress on ubuntu-process removing is there https://github.com/status-im/status-react/issues/6175
I don't think that it has a lot sense to apply efforts to enhance `ubuntu-server` functionality
