### ISSUE TITLE
Screen "Help improve Status" never appears on Androind 8

### ISSUE THREAD

**Issue by KatrinBrynka** [status-im/status-react#5383]
### Description

*Type*: Bug

*Summary*:  reproduced only on Android 8

#### Expected behavior
After creating new account, screen "Help improve Status by sharing usage patterns" is shown.

#### Actual behavior
Screen "Help improve Status by sharing usage patterns" never appears

### Reproduction

- Create account
- Provide password and confirmation
- Provide name
- Screen "Help improve Status by sharing usage patterns" should appear, but it didn't.

### Additional Information
* Status version: 0.9.24 (6291) node 7ebe0c3
* Operating System: Android 8.0.0

**Comment by chadyj** [comment]
Hey @KatrinBrynka, the usage sharing feature has been removed in the last release, so the opt-in screen is no longer shown.
