### ISSUE TITLE
No messages received if sent in 1:1 chat or public chat on Rinkeby to other recipient on Rinkeby: Could not connect to mailserver

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5390]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Added a contact and sent him a message in 1:1 chat, unfortunately message is `Not sent` If tap to reconnect then warning "Could not connect to mailserver" is shown. Tried on both available servers: mailserver A and B

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can send message in 1:1 and in public chat
#### Actual behavior
[comment]: # (Describe what actually happened.)
no messages sent
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add contact by scanning QR code and send him a message in 1:1 chat
-  check status of the sent message in my case it's Not Sent

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.24 (6290) node 7ebe0c3
* Operating System: Android and iOS

#### Logs
no logs as we don't have them on release build

**Comment by lukaszfryc** [comment]
All works fine since we switched to the same mailservers we use for Mainnet (https://github.com/status-im/status-react/commit/d088fa2568c043257e181592ee1e311674a7fcb4)
