### ISSUE TITLE
Sending payment causes TypeError null is not an object when a user has signed while being offline

### ISSUE THREAD

**Issue by infebe** [status-im/status-react#5392]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sending a payment through the chat, when the user has logged into his account while being offline, produces the following error:

```
TypeError: null is not an object (evaluating 't.minus')
    This error is located at:
        in send-transaction
        in reagent193
        in RCTView
        in main
        in root
        in reagent1
        in RCTView
        in RCTView
        in t
```

This error produces the application to freeze, showing a blank screen. It is necessary to close the application in order to continue using it.

Here is a screen capture with the Error dialog shown to the user:

![device-2018-08-06-125517](https://user-images.githubusercontent.com/23058833/43713819-39b1ca6e-997b-11e8-8511-5bac710bfb01.png)
 
Here is a screen capture of the wallet:
![device-2018-08-06-125544](https://user-images.githubusercontent.com/23058833/43713940-a1953238-997b-11e8-8b69-2826e451c327.png)

Here is a video reproducing the bug:
https://drive.google.com/file/d/1T6hYW85u5KyUngAqYZPTvNMPhmNxWHNa/view?usp=sharing

This issue was reproducible with two different Android devices. Not been able to check on iOS devices.

The issue was reproduced 4 times/4 attempts.

#### Expected behavior
The expected behavior would have been to have a dialog telling the user that he/she can't make the transaction because the app is in offline mode.

#### Actual behavior
The application crashes, shows an error dialog and stays in a blank screen. The user must hit the back button two times to be able to quit the application.

### Reproduction
- Disable Wi-Fi
- Disable Mobile data
- Open Status
- Log into existing account
- Open existing chat with a contact
- Send a payment

### Additional Information
* Status version: 0.9.24 (6291)
* Operating System: Android
* Devices: Huawei ALE-L21 with Android 6.0, Nexus 5 with Android 6.0.1

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
 NAME: "TypeError"
    MESSAGE: TypeError: null is not an object (evaluating 't.minus')
    
    This error is located at:
        in send-transaction
        in reagent193
        in RCTView
        in main
        in root
        in reagent1
        in RCTView
        in RCTView
        in t
    
    check_sufficient_gas@index.android.bundle:12:4927496
    G__30386_30398@index.android.bundle:12:4928796
    index.android.bundle:12:2486676
    index.android.bundle:12:2486688
    in_context@index.android.bundle:12:2286742
    deref_capture@index.android.bundle:12:2286885
    _run@index.android.bundle:12:2307407
    cljs$core$IDeref$_deref$arity$1@index.android.bundle:12:2312393
    _deref@index.android.bundle:12:153854
    deref@index.android.bundle:12:211756
    index.android.bundle:12:7631063
    index.android.bundle:12:2321509
    wrap_render@index.android.bundle:12:2322190
    do_render@index.android.bundle:12:2323372
    index.android.bundle:12:2323925
    in_context@index.android.bundle:12:2286742
    deref_capture@index.android.bundle:12:2286885
    run_in_reaction@index.android.bundle:12:2315218
    index.android.bundle:12:2323866
    f@index.android.bundle:143:83728
    beginWork@index.android.bundle:143:87321
    o@index.android.bundle:143:128242
    a@index.android.bundle:143:128621
    T@index.android.bundle:143:132129
    y@index.android.bundle:143:131565
    v@index.android.bundle:143:131402
    h@index.android.bundle:143:130681
    c@index.android.bundle:143:129935
    enqueueForceUpdate@index.android.bundle:143:60452
    forceUpdate@index.android.bundle:109:1315
    run_queue@index.android.bundle:12:2282434
    flush_queues@index.android.bundle:12:2283706
    run_queues@index.android.bundle:12:2283853
    index.android.bundle:12:2283282
    index.android.bundle:126:1369
    x@index.android.bundle:126:643
    callTimers@index.android.bundle:126:2788
    value@index.android.bundle:121:3582
    index.android.bundle:121:1067
    value@index.android.bundle:121:3009
    value@index.android.bundle:121:1039
    [native code]
```

<blockquote><img src="https://lh4.googleusercontent.com/t-70489O9hLbDFXvbi45ddjgquffVLsI5wPjA5P80jtBybPL9pTIXsRYJM4=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1T6hYW85u5KyUngAqYZPTvNMPhmNxWHNa/view?usp=sharing&usp=embed_facebook">offline_null_currency_error.mp4</a></strong></div></blockquote>

**Comment by dmitryn** [comment]
I don't have the error described above, but have another one:

<img width="539" alt="screenshot 2018-09-12 12 06 23" src="https://user-images.githubusercontent.com/23836/45414858-f0ff4680-b684-11e8-9c48-c29fd4da2a61.png">

**Comment by lukaszfryc** [comment]
@dmitryn I was able to reproduce it on iOS while sending ETH in 1-1 chat and having poor network connection. The error appeared when I clicked "send" button in the chat. I think it maybe related to not having gas or gas prices details.
