### ISSUE TITLE
Send Transaction password box does not prompt again the keyboard when inserting a wrong password and hiding the keyboard

### ISSUE THREAD

**Issue by infebe** [status-im/status-react#5393]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The password box in the Send transaction screen doesn't show again the keyboard when the user has put a wrong password and hides the keyboard. This forces the user to have to quit the screen and do the whole transaction again. This problem has been seen in the password box of the "Send transaction" screen, which is accesible via the chat command "/send" or Wallet->Send transaction.

![textbox_password](https://user-images.githubusercontent.com/23058833/43716715-75f7c80c-9985-11e8-8e70-1114fd9ea717.png)

Here is a video reproducing the problem:
https://drive.google.com/file/d/1mdZMXM7L-vG2z8d3Jx19TczAbHCFyZoX/view?usp=sharing

This issue was reproducible with two different Android devices. Not been able to check on iOS devices.

The issue was reproduced 6 times/6 attempts.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The keyboard should always be prompted when tapping on the EditText or text box where the password has to be inserted.

#### Actual behavior
[comment]: # (Describe what actually happened.)
When putting a wrong password, and hitting back button (which produces the keyboard to get hidden), if the user wants the keyboard to appear again by tapping on the text box, the keyboard does not appear. Then, the user must exit the screen and do again the "send transaction" command.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Enter in an existing chat with a contact
- Send a payment
- In the "Send transaction" screen tap "Sign Transaction"
- Insert a wrong password in the dialog prompted
- Tap "Sign Transaction"
- Tap "Back button"
- Tap text box where the "Wrong password" dialog is

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.24 (6291)
* Operating System: Android
* Devices: Huawei ALE-L21 with Android 6.0, Nexus 5 with Android 6.0.1

<blockquote><img src="https://lh4.googleusercontent.com/mTO7avxNCfP31KCcKQhzoRU_grelCeLpvcXRSiaiZHg7IGGS9GFXPZ20HRk=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1mdZMXM7L-vG2z8d3Jx19TczAbHCFyZoX/view?usp=sharing&usp=embed_facebook">keyboard_does_not_prompt.mp4</a></strong></div></blockquote>

**Comment by goranjovic** [comment]
Hi @infebe, thanks for the report! Luckily, we already fixed this one recently (in #5322). The fix is still only available in the nightly versions, but will be in the release too soon enough.
