### ISSUE TITLE
Allow to mark all messages as read

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5394]
### Description

*Type*: Feature

*Summary*: 
Each of unread message has to be seen in order for the unread message counter to disappear. This can be an issue when you have hundreds of unread messages and you do not want to scroll to see them all. That's why we want to introduce unread messages badge with "X" button that marks all messages as read:

<img src="https://user-images.githubusercontent.com/7532782/46801403-e8209400-cd5a-11e8-867d-92dff8b0d0b4.png" width="500">

Design: https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5b1a79ae98f9b848590fb930

#### Expected behavior
- Badge appreas if there are some unread messages. The counter changes while the user scrolls up to  read messages
- Clicking on the badge takes the user to the first unread message
- User can mark all messages as read by clicking "X" on the badge 

#### Actual behavior
User needs to see all messages manually for unread message counter to disappear.

### Additional Information
* Status version: 0.9.24
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
This issue has been mentioned couple of times on Instabug.

**Comment by lukaszfryc** [comment]
There are couple of solutions to this problem. One which is very simple is to have "Mark all messages as read" button in chat options. The other can be to scroll to the first unread message when a chat is opened and show visual indicator for it similar to what Slack does:

![image](https://user-images.githubusercontent.com/7532782/43716982-4e574376-9986-11e8-8a60-964fb1ee05ed.png)

@errorists I think we need design your input here :) Please check https://github.com/status-im/status-react/issues/4691 which is related.

**Comment by errorists** [comment]
@lukaszfryc are you aware of this design [zpl.io/aN0ZKWQ](https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5b1a79ae98f9b848590fb930) ? Can't find a GH issue for it, but it follows the Slack route of marking messages as read and is ready for implementation.

**Comment by lukaszfryc** [comment]
@errorists this design looks great and I think it has good UX. We should definitely make tappable area for "X" big enough to easily click it. I believe it will be used often.

**Comment by errorists** [comment]
@lukaszfryc I'll be revisiting those snackbars sometime in the near future as they seem to cause some issues, I'll see what can be done about the tappable area to reach the sensible minimum of 44x44pts

**Comment by lukaszfryc** [comment]
More people complain about this Instabug including @jarradh. 

@yenda or @janherich, maybe you could work on this task?

**Comment by lukaszfryc** [comment]
Alternatively we can just mark all messages as read when chat is opened. It's easier to implement but it will not allow us to keep track of new messages in channels. That's why the best solution is https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5b1a79ae98f9b848590fb930

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by lukaszfryc** [comment]
I updated the description of the issue. @errorists could you double check it to see if I got the behaviour of the badge right?

**Comment by oskarth** [comment]
Is this really a blocker? I understand it'd be nice but seems like it can be cut from scope.

cc @rachelhamlin

**Comment by errorists** [comment]
This task is superseded by https://github.com/status-im/status-react/issues/6375

**Comment by oskarth** [comment]
Closing as there's a new issue for this.
