### ISSUE TITLE
null is not an object (evaluating 'e.stopWatching') when changing network/mailserver while in Rinkeby

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5395]
*Type*: Bug
*Summary*: `null is not an object (evaluating 'e.stopWatching')` error followed by the app crash occurs when user changing the network to Rinkeby RPC, or switching mailservers under Rinkeby network. We could not reproduce it so far but there are logs exist when issue happens.

#### Expected behavior
No errors when switching to `Mainnet` <-> `Rinkeby` networks. No error when I switch mailserver under Rinkeby network.  

#### Actual behavior
`null is not an object (evaluating 'e.stopWatching')` when switching the account from `Mainnet` to `Rinkeby`. 
<img width="372" alt="screen shot 2018-08-06 at 15 42 30" src="https://user-images.githubusercontent.com/8749671/43717182-5f6c053a-998f-11e8-925c-c6c42e10221f.png">

### Reproduction

- Open Status and recover your account
- Switch network from `Mainnet` to `Rinkeby` 
- Log in to account under `Rinkeby` network

### Additional Information
* Status version: Release 0.9.24
* Operating System: Android, iOS

#### Logs
Logs when switching networks: 
[Logs1.txt](https://github.com/status-im/status-react/files/2262549/Logs1.txt)

Logs when switching mailserver in Rinkeby netwrork: 
[Logs2.txt](https://github.com/status-im/status-react/files/2262550/Logs2.txt)

**Comment by asemiankevich** [comment]
i was able to repro this on Mainnet having `connect to mailsever` tooltip (switching between mailserver F to E and both were not working). Dont think it depends on network rather than depending on the mailserver connection istead

**Comment by Serhy** [comment]
Haven't seen this issue for a while, and now with 0.9.31 build - can't reproduce with Android 7 (Samsung J7), Android 6.0.1 (Note 4)
Closing this for now.
