### ISSUE TITLE
If Dapp sign in message is too long it cuts off the message + does not display properly

### ISSUE THREAD

**Issue by PhilipandWu** [status-im/status-react#5418]
Type: Bug

### Description
Summary: If the "Message" section is too long  in the "sign" screen as seen for the Airswap dapp the text is somewhat cutoff visually and displays oddly(refer to screenshot 1).
If you scroll super long messages such a the principles it displays oddly (see screen shot 2).
 This does not occur for dapps with shorter messages like Cryptokitties (refer to screenshot 3).

*Screenshot 1 - For airswap the message cuts off as it's too long + does not display within box limit*
![photo 2018-08-07 2 10 40 pm](https://user-images.githubusercontent.com/40644582/43795051-2b5e34ec-9a4e-11e8-9619-c2abb6d76bb7.png)

*Screenshot 2 - If you scroll especially long messages it doesn't display the full message*
![38985135_1086325441520207_1784681318055936000_n](https://user-images.githubusercontent.com/40644582/43966241-5c9a2956-9c8f-11e8-941c-dd6dd0700de8.jpg)

*Screenshot 3 - For cryptokitties app the message does not cut off and displays within box limits*
![38660566_2253211611385631_8881605498948812800_n](https://user-images.githubusercontent.com/40644582/43795048-28d5c99c-9a4e-11e8-809f-a45b35ea826b.jpg)

App verison: 9.24 iOS

**Comment by flexsurfer** [comment]
fixed
