### ISSUE TITLE
Sign Jenkins build artifacts to avoid security warnings

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5421]
**Issue**
* macos security warnings are shown on start of application. 
* Keychain asks to re-enter password on every binary update.

**Type:** Bug.

**Solution**: Above might be solved with signing of .dmg and .app according to https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG17

Makes sense to sign AppImage for Linux as well. Image creation tool supports signing via cli options.

**Comment by churik** [comment]
Set `high-severity` here, because it can affect possibility to install and use Mac OSx builds for automation tests.

**Comment by chadyj** [comment]
<img width="420" alt="screen shot 2018-08-15 at 12 24 22 pm" src="https://user-images.githubusercontent.com/116099/44144036-4e3b4aca-a086-11e8-8f03-624f407d5cd4.png">

> "StatusIM" can't be opened because it is from an unidentified developer.
> 
> Your security preferences allow installation of only apps from the App Store and identified developers.

**Comment by chadyj** [comment]
<img width="434" alt="screen shot 2018-08-15 at 12 27 01 pm" src="https://user-images.githubusercontent.com/116099/44144122-91221a3a-a086-11e8-933f-037ac4173eb4.png">

> StatusIM wants to use your confidential information stored in "org.status.status-im.keychain" in your keychain.
> 
> The authenticity of "StatusIM" cannot be verified. To allow this, enter the "login keychain password.
