### ISSUE TITLE
Refine macos app bundle installation experience

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5423]
**Issue**

It was reported that just replacement of app bundle in Applications directory is not working as expected (old app should be removed to trash manually in advance).
Installation flow is not obvious for users as well.

**Type:** Bug.

**Solution**: Background image for mounted .dmg or at least symlink to Applications folder will enhance app installation user experience. Replacement of available app bundle in Application with new one should work.

**Tasks**:

- [x] add  symlink to Applications folder for mounted .dmg 
- [x] make possible to replace app in Application folder for  reinstalling

**Comment by chadyj** [comment]
Not sure if its related, but I also see this problem `We detected a problem with the encryption key` when upgrading.

I hit apply and then get a blank screen.

I see this after deleting the old version of status, and then dragging a new version to Applications.

<img width="1021" alt="screen shot 2018-08-09 at 7 12 04 am" src="https://user-images.githubusercontent.com/116099/43879284-973465fa-9ba3-11e8-99d1-8a9ed3151125.png">

**Comment by chadyj** [comment]
My log file.
```
Debug: starting ubuntu server...

Debug: wait for started...

Debug: ubuntu-server std:  "outerRealmConstructor: undefined"

Debug: ubuntu-server std:  "Loaded realmConstructor: function Realm() { [native code] }"

Debug: ubuntu-server err:  "-- Server starting"

Debug: waiting finished

Warning: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.

Debug: ubuntu-server err:  "-- Connection from RN client"

Debug: ubuntu-server std:  "outerRealmConstructor: function"

Debug: ubuntu-server std:  "Running application \"StatusIm\" with appParams: {\"initialProps\":{},\"rootTag\":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON"

Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :initialize-keychain"

Debug: ubuntu-server std:  "DEBUG [status-im.utils.keychain.core:57] - initializing realm encryption key..."

Debug: invoked RNKeychainManager::setUsername with username =  "status-im.encryptionkey"

Debug: invoked RNKeychainManager::getGenericPasswordForOptions

Debug: RNKeychainManager::getGenericPasswordForOptions failed:  Password not found

Debug: ubuntu-server std:  "DEBUG [status-im.utils.keychain.core:43] - no key exists, creating..."

Debug: invoked RNSecureRandom::generateSecureRandomAsBase64

Debug: RNSecureRandom::generateSecureRandomAsBase64 result:  "UC/IElliPK3KVcRLHa0u1mfHZx4hHPzNnBKeHDXK+7h/jULTgH3y3I/8GSOZ76/+xGVNL7JRlrmPLSw+z8p4xg=="

Debug: ubuntu-server std:  "DEBUG [status-im.utils.keychain.core:35] - storing encryption key"

Debug: invoked RNKeychainManager::setGenericPasswordForOptions

Debug: RNKeychainManager::setGenericPasswordForOptions failed:  The user name or passphrase you entered is not correct. (OSStatus -25293)

Debug: ubuntu-server err:  "WARN [status-im.utils.keychain.events:10] - invalid key detected"

Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :initialize-app"

Debug: ubuntu-server err:  "WARN [status-im.data-store.realm.core:74] - realm: deleting all realms"


```

**Comment by EugeOrtiz** [comment]
Can we tackle as part of this the fact that the app asks for mac password 2 or 3 times during onboarding?  :)

I also foresee a "Check for updates" feature in a near future.

**Comment by churik** [comment]
@EugeOrtiz does it happen only if you set "Always Allow" when app is asking access to keychain? 
Anyway I believe this can be mentioned in #5135, not here IMO

**Comment by EugeOrtiz** [comment]
@churik It doesn't once I set "Always allow", but it is annoying until somebody gives you the solution :D 
Feel free to add it there too! Thanks

**Comment by gnl** [comment]
@EugeOrtiz The keychain issues are related to #5421, the resolution of which is coming up.
@chadyj can you open a separate issue for this or point to it if you already have?

**Comment by chadyj** [comment]
@gnl I haven't seen the `We detected a problem with the encryption key` error in a while. @churik Have you seen it lately?
