### ISSUE TITLE
Implement app crash or user feedback reporting flow

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5425]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As user, I want to notify developers about issues with app or provide my feedback, request new features.

### Description

Should be a way to report about happened crash or allow users to provide feedback.

*Type*: <Feature>

### Details

Instabug might be used for that purposes
Or https://hockeyapp.net as an option

**Comment by churik** [comment]
@MaxRis in case of crash you still need manually kill process `ubuntu-server`
Should we fix it separately or when implementing fix for this issue, WDYT?
Or it is something related to #5378?

**Comment by maxhora** [comment]
@churik `ubuntu_server` process issue, definitely, should be addressed with higher priority
And it seems it's not directly related to this one

**Comment by churik** [comment]
OK, will add, thanks!

**Comment by churik** [comment]
It is closed via #5580
