### ISSUE TITLE
Document download links

### ISSUE THREAD

**Issue by probonopd** [status-im/status-react#5432]
https://github.com/status-im/status-react/blob/981eb135aabaf2f5fa2232c56f1a03fde404fd14/ci/Jenkinsfile.nightly_desktop#L295

Please provide the download links.

>  Currently the fastest way to get your hands on a binary is to join our Early Access by submitting your email on our website or by building it yourself.

That's a pity. Please just provide the links to the binaries without a need to register or sign up or such, so that we can include them in the AppImageHub directory of available AppImages.

**Comment by probonopd** [comment]
Not doing anything is never a good reason to close anything. I never get why bots like this exist.

**Comment by Swader** [comment]
> Not doing anything is never a good reason to close anything. I never get why bots like this exist.

Agreed

**Comment by cammellos** [comment]
Closed as desktop status-react has been discontinued.
