### ISSUE TITLE
Passwords should be invisible to the accessibility services

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5439]
### Description

*Type*: Feature

*Summary*: Passwords should be ignored for the accessibility service so that malicious apps that are using the accessibility service could not capture all user inputs. 

Android implementation: https://github.com/walleth/walleth/commit/0216a7ce169be590450bffeaf19e6335d48eec3c

Related issues:
- https://github.com/walleth/walleth/issues/268
- https://github.com/bitcoin-wallet/bitcoin-wallet/pull/547

### Additional Information
* Operating System: Android, iOS

**Comment by Dopeso** [comment]
[https://www.yahoo.com/](https://captainaltcoin.com/coinbase-wallet-vs-ledger/)
