### ISSUE TITLE
User should be able to dismiss "Add to contact" snackbar

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5440]
### Description

*Type*: Feature

*Summary*: User should be able to dismiss "Add to contact" bar in 1-1 chat. He/she can always open the user profile and add it to contacts from there.

### Reproduction

- Receive 1-1 message from unknown contact
- Dismiss the "Add to contact" snackbar

### Additional Information
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@errorists could you link the design here?

**Comment by errorists** [comment]
Design over at [Zeplin](zpl.io/aN0ZKWQ)

**Comment by dmitryn** [comment]
This seems as duplicate or partial scope of https://github.com/status-im/status-react/issues/4690 which i'm currently working on.

As for dismiss action, in my current implementation it just closes "add  to contacts" bar, but it will be re-opened next time you visit that 1-1 chat.

**Comment by dmitryn** [comment]
I think it makes sense to continue work in scope of current issue because it is more granular than #4690 and it will be easier to review and test this one.

**Comment by dmitryn** [comment]
@lukaszfryc @errorists do you guys think that dismiss should hide the "add to contacts" badge forever? In that case, it doesn't just close the bar, but also implicitly work like "ignore" action. Instead of `X` icon it might be explicit "Dismiss" or "Ignore" wording.

**Comment by lukaszfryc** [comment]
@dmitryn I think if someone clicked it once it does not want to click it again 5 min later when he opens the chat again. So, I'd say `X` icon should hide it forever. You can always add a user to the contacts from the chat options -> view profile.

**Comment by lukaszfryc** [comment]
@errorists should there be any indicator that a user is not a contact yet? Up to this point, the "Add to contact" button indicated it. But now you can dismiss this button by clicking "X":

<img src="https://user-images.githubusercontent.com/7532782/44021245-9db76334-9ee4-11e8-96af-42c99e6d6169.png" width="200">

Please note that the username you see is the real username since the user that initiated the chat had to reveal it.
