### ISSUE TITLE
Document DApps remote debugging

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#5443]
### User Story

As a developer, I want to have some simple docs detailing how DApps can be remotely debugged (android and ios)

**Comment by Pedro-vk** [comment]
Is it possible in any WebView on Android or needs to be set by the app that contains the WebView? I'm asking that because I've been trying to debug on Status and I was not able. I was able to debug on Coinbase wallet (Toshi).

**Comment by Swader** [comment]
Still relevant

**Comment by jeluard** [comment]
@Swader Can we work together on this one? :)

**Comment by Swader** [comment]
Sure, how can I help?

**Comment by jeluard** [comment]
@Swader I heard you write good docs?

**Comment by Swader** [comment]
@jeluard haha fair enough, yeah I can write something up if you can point me to the process of debugging a dapp if one exists. Was looking for that exact thing when working on [tokenhunt](https://discuss.status.im/t/status-feedback-from-blockconf-io/904).

**Comment by jeluard** [comment]
@Swader How can I reach you in status?

**Comment by Swader** [comment]
bruno.stateofus.eth should work, if not, click my random name on https://nimbus.status.im :)

<blockquote><img src="/img/graphic-licensing.png" width="48" align="right"><div><strong><a href="https://nimbus.status.im/">Nimbus, a Light Client for Ethereum 2.0</a></strong></div></blockquote>
