### ISSUE TITLE
App doesn't start after crash

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5444]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to restart app after crash and continue work.

### Description

*Type*: Bug

*Summary*: when application is crashing, and you try to restart it (for crash example with logs see https://github.com/status-im/status-react/issues/5012) when you open app nothing happens. To continue work you should manually kill `ubuntu-server` process and then restart the app.

#### Expected behavior
app is working when you restart it after crash

#### Actual behavior
nothing happens until you kill `ubuntu-server` process 

### Reproduction

- when you have a crash, restart the app.

### Additional Information
* Status version: nightly 09.08.2017
* Operating System: Mac OSx

**Comment by maxhora** [comment]
@churik this issue should be resolved with changes related to Crash Reporter app.
Sometimes I have seen situations that ubuntu_server process still remains not killed, but it happened for me not often.

**Comment by vitvly** [comment]
@MaxRis @churik I've updated the description in 
https://github.com/status-im/status-react/pull/5784 so that it is clear that only dev-related problem (`Reload JS`) is resolved. As I understand, Crash Reporter can be modified so that it will forcibly quit `ubuntu-server.js` upon intercepting crash, correct?

**Comment by maxhora** [comment]
@siphiuel , yes, but crash handler already terminates ubuntu_server process on handling of crash and no additional changes required.

**Comment by chadyj** [comment]
Heya @MaxRis @siphiuel is this still an issue? It has been 'in progress' for weeks

**Comment by maxhora** [comment]
@chadyj I think we can close it for now (the issue should be fully "resolved" after completion of https://github.com/status-im/status-react/issues/6175)
