### ISSUE TITLE
Apply design for popups 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5445]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see popups according to new design.

### Description

*Type*: Feature

*Summary*: now all confirmation dialogs looks like: 
![image](https://user-images.githubusercontent.com/4557972/43909044-1d47deb6-9c02-11e8-9a58-628855b8d359.png)
Expected, that design will be applied for all popups (e.g.confiramation dialogs, errors etc)
Design examples:
- Clear history confirmation: https://zpl.io/2pdDMxQ
- Delete history confiramtion: https://zpl.io/agnZz09
- Logout confirmation dialog: https://zpl.io/bLOWk8Y

<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>
<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>
<blockquote><img src="https://zeplin.io/img/favicon/228x228.png" width="48" align="right"><div><img src="/img/favicon/256x256.png" height="14"> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by churik** [comment]
Popup to prevent spam:
<img width="590" alt="spam" src="https://user-images.githubusercontent.com/4557972/46526794-f58bd900-c897-11e8-8375-5f3bc0c99c51.png">

**Comment by SlizkovaGanna** [comment]
Popup for 'Message copied to clipboard'
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/43638377/47033829-78594180-d17e-11e8-9615-e45c605fc16a.png">
