### ISSUE TITLE
Do not reload browser every time dapp is opened

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5446]
### Description

*Type*: Bug

*Summary*: Every time a dapp or webpage is opened, it reloads. This is both unnecessary in many cases and time consuming. Maybe we could cache content of dapp or webpage and show it immediately when user clicks on it in Home tab. This way links in Home could act like tabs in Chrome. 

<img src="https://user-images.githubusercontent.com/7532782/43949905-2c202406-9c8f-11e8-8ac4-d8894bd74c6f.png" width="200">

#### Expected behavior
The webview should show cached webpage which users can always refresh on demand by tapping the refresh button.

#### Actual behavior
The webview refreshes every time user re-opens a dapp or webpage. 

### Reproduction

- Open a dapp
- Go back to Home
- Open the dapp again

### Additional Information
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@flexsurfer what do you think of it?

**Comment by flexsurfer** [comment]
@lukaszfryc https://github.com/status-im/status-react/pull/5335

**Comment by rasom** [comment]
yes, it's similar to https://github.com/status-im/status-react/issues/5278

**Comment by lukaszfryc** [comment]
Closing as duplicate.
