### ISSUE TITLE
No scroll bar is shown when you browse chat history

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5447]
### User Story

As a user, I want to see scroll bar to navigate through chat history easily.

### Description
*Type*: Bug
*Summary*: the scroll bar is missing in public and 1-1 chats

#### Expected behavior
scroll bar is presented, so I can pull it and easily navigate through chat history

#### Actual behavior
no scroll bar is presented.
NOTE: on both IOS and Android mobile apps scroll bar is presented.
<img width="568" alt="noscr" src="https://user-images.githubusercontent.com/4557972/43950408-e1e7b6b0-9c98-11e8-97cc-b4b8afe39440.png">

### Reproduction

- Open Status
- Join any public chat with long history (need to scroll to see all messages)
- Scroll to the top to see previous messages

### Additional Information
* Status version: nightly 10/08/2018
* Operating System: Mac OS x High Sierra

**Comment by EugeOrtiz** [comment]
Design references: 

[Scroll bar for left panel](zpl.io/boBy3dE) (Zeplin)
<img width="329" alt="captura de pantalla 2018-09-06 a la s 1 31 43 p m" src="https://user-images.githubusercontent.com/37297779/45154845-3d580b80-b1d9-11e8-982d-7afb0685c40b.png">

[Scroll bar for right panel](zpl.io/aNpAxXk) (Zeplin)
<img width="586" alt="captura de pantalla 2018-09-06 a la s 1 33 26 p m" src="https://user-images.githubusercontent.com/37297779/45154915-7abc9900-b1d9-11e8-8abe-66da7a33d774.png">

**Comment by churik** [comment]
Closed in #6403

**Comment by churik** [comment]
@siphiuel 
merged PR on RN-side https://github.com/status-im/react-native-desktop/pull/372 `Add vertical scroll bar to ScrollViews` is not presented on latest nightly
