### ISSUE TITLE
Add "Frequently added questions" to Menu

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5452]
### Description
*Type*: Feature

*Summary*: to help users get the better experience we need to add FAQ  to Profile. In mobile it is presented in Profile > Help Center > Frequently asked questions.

<img width="163" alt="img_df4d840da4b3-1 jpeg 2018-08-10 15-20-06" src="https://user-images.githubusercontent.com/4557972/43957565-ee70cb84-9cb0-11e8-841c-fd8440dbe4e9.png">
If you tap on it > WIKI page with FAQ is opened.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Same as mobile:
- On profile tab, add `Need help?` item
-  Add submenu:
  - Frequently asked questions (links to https://status.im/docs/FAQ-desktop.html)
  - Ask a question or report a bug (links to #status)

**Comment by churik** [comment]
@EugeOrtiz take a look when you have a time.

**Comment by EugeOrtiz** [comment]
Will do. I think is better to have the actual text outside the app (mobile has it on a wiki) and link it from within the app. That way we can have more flexibility to update any content without having to generate a new version.

**Comment by chadyj** [comment]
Maybe we can do the same as desktop?

Need help? >>>>
- Frequently asked questions
- Submit a bug (links to GitHub)

**Comment by EugeOrtiz** [comment]
Do we need to put this on the UI? I've done some research and most native desktop apps use the MacOS bar options to add items like these (FAQs, submit, about). Like designed here #5547

**Comment by churik** [comment]
I'm pretty sure that it will be enough to put Submit a bug and Frequently asked questions to MacOS Menu Bar.
But not sure when  #5547 will be prioritized. @chadyj WDYT?

**Comment by EugeOrtiz** [comment]
The bar is already implemented, but doesn't have many options. I think we can have a first version starting with these options.

**Comment by churik** [comment]
@chadyj do we still need FAQ?

**Comment by chadyj** [comment]
Desktop should have the equivalent of the "need help?"menu on mobile.
Lets aim for parity where it makes sense.

**Comment by EugeOrtiz** [comment]
[Here are the designs](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=762%3A742) for the improved "new" profile for desktop (Figma), including the Help section.

**Comment by rcullito** [comment]
great, thanks for the design guidance here @EugeOrtiz !

**Comment by churik** [comment]
@yenda can you take care of it?
