### ISSUE TITLE
Edit profile picture

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5456]
Update: Editing username is now working. Leaving this open until editing a picture works.

**Story**
As a user, I want to be able to edit my picture and username so I can maintain my profile updated both on mobile and desktop.

**Current behavior** 
The user  can't edit username and/or image:
<img width="338" alt="captura de pantalla 2018-08-10 a la s 3 29 10 p m" src="https://user-images.githubusercontent.com/37297779/43974863-35aa3a48-9cb2-11e8-8639-8f867e125a5c.png">

**Solution**
Allow the user to edit username and profile. This should be synced between mobile and desktop (a change on any device should be reflected on another device). New UI elements and behavior are introduced.
Designs and anotations >> zpl.io/brE1NdX (Zeplin)
[Prototype here](https://invis.io/C7NGZR7MH25).

![user profile - edit pic and name](https://user-images.githubusercontent.com/37297779/43975019-a0aec57a-9cb2-11e8-9c7c-d340fa3f4fb4.png)

**Platforms**
MacOS & Linux.

**Comment by chadyj** [comment]
Update: Editing username is now working. Leaving this open until editing a picture works.

**Comment by Swader** [comment]
Not stale
