### ISSUE TITLE
Support Swarm URI's in Webview

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#546]
Requires getting swarm running on `status-go` side and redirecting webview uri `bzz` scheme to there on Android & iOS

http://stackoverflow.com/questions/11421048/android-ios-custom-uri-protocol-handling

**Comment by jarradh** [comment]
At the same time we should look at #669

**Comment by jarradh** [comment]
https://github.com/status-im/react-native-webview-bridge/blob/master/android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java#L349 

Needs to redirect `bzz:/...` and `bzzr:/...` to `http://127.0.0.1:8500/bzz:/...` and `http://127.0.0.1:8500/bzzr/...`

**Comment by rasom** [comment]
and here on iOS https://github.com/status-im/react-native-webview-bridge/blob/master/ios/RCTWKWebView.m#L325
