### ISSUE TITLE
Status Desktop feature request: Enable opting out of Mix Panel

### ISSUE THREAD

**Issue by noman-land** [status-im/status-react#5465]
Currently the first connection Status desktop makes is to Mixpanel:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/27938023/44007787-74b97e16-9e69-11e8-95af-2bf441a6adc1.png">

I know the Mixpanel conversation is ongoing but in the meantime it would be nice if users were informed about and were able to opt out of Mixpanel analytics.

**Comment by chadyj** [comment]
What version are you using? Mixpanel is no longer in the codebase. 
Can you try grabbing the latest from https://status-im.github.io/nightly/

<blockquote><div><strong><a href="https://status-im.github.io/nightly/">Status.im Nightly Builds</a></strong></div></blockquote>

**Comment by rasom** [comment]
That's because of realm.js https://github.com/realm/realm-js/search?q=mixpanel&unscoped_q=mixpanel

**Comment by rasom** [comment]
https://github.com/realm/realm-js/blob/5cd969a03e85a8544d74c6de6760997b166425c9/lib/submit-analytics.js#L5

<blockquote><img src="https://avatars3.githubusercontent.com/u/7575099?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/realm/realm-js">realm/realm-js</a></strong></div><div>realm-js -  Realm is a mobile database: an alternative to SQLite & key-value stores</div></blockquote>

**Comment by rasom** [comment]
we need to set REALM_DISABLE_ANALYTICS

**Comment by noman-land** [comment]
Nice find, @rasom. Thanks for the fast turnaround. For posterity, I was using [this nightly (85aad1)](https://status-im-desktop.ams3.digitaloceanspaces.com/StatusIm-85aad1.dmg).

**Comment by lukaszfryc** [comment]
I quickly tested mobile apps and all looks fine there.

@churik please add "Tested - OK" once you finish testing desktop.
