### ISSUE TITLE
`StatusIm` application couldn't be found in Spotlight Search

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5467]
### User Story

As a user, I want to navigate to StausIm through spotlight search

### Description

*Type*: Bug
*Summary*: when I have app installed (copied to`Applications` folder) and try to look it using Spotlight Search, but `StatusIm` app is not suggested so I need manually open `Applications` folder and launch app.

#### Expected behavior
`StatusIm` is suggested, i.e. as `Chrome`
![tequilajazzz 2018-08-13 10-44-18](https://user-images.githubusercontent.com/4557972/44018906-eb95c036-9ee5-11e8-8d3e-f242c7ad8a00.png)

#### Actual behavior
`StatusIm` is not suggested
![tequilajazzz 2018-08-13 10-45-52](https://user-images.githubusercontent.com/4557972/44018981-2ab4a016-9ee6-11e8-9bb9-e83ddd6030e6.png)

### Reproduction

- Download `.dmg` file 
- Open it
- Drag'n'drop `StatusIm` to `Applications` folder
- Open Spotlight Search
- Start type "Status"

### Additional Information
* Status version: nightly 13/08/2018
* Operating System: Mac OSx High Sierra

**Comment by gnl** [comment]
@vkjr 
https://github.com/vkjr/StatusAppFiles/pull/1
