### ISSUE TITLE
No sound when PN arrives for recovered account [iPhoneX]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5482]
***Type***: Bug

***Summary***: When PN arrives to account which has been recovered - there is no sound present along with PN pop-up. It's all fine for newly created accounts, but not for the recovered.
Note: 
#### Expected behavior
Sound notification is present when PN arrives for recovered account on iPhoneX 
#### Actual behavior
No sound notification is present when PN arrives for recovered account on iPhoneX 

### Reproduction

- Open Status and create a new account on Device 1 (let's name it `NewCreatedAcc`)
- Open Status and recover existing account on Device 2 (let's name it `RecoveredAcc`)
- Both accounts add each other in contacts 
- `RecoveredAcc` puts an app on background
- `NewCreatedAcc` sends a text message to `RecoveredAcc`
- `RecoveredAcc` checks that sound has played along with the PN for message from `NewCreatedAcc`

### Additional Information
* Status version: Develop `0.9.26 (6368) node 03bf6e3`
* Operating System: iOS 11.4

**Comment by lukaszfryc** [comment]
@Serhy is it iPhone X specific? It works on my side on iPhone 8 (11.4.1) and Galaxy S8 (Android 7).

**Comment by Serhy** [comment]
Funny enough, the reason was the disabled `Ring/Silent` hardware button.
Enabling it turns on sound when PN arrives in Status.
