### ISSUE TITLE
Update status-go to 0.10.0 breaks compatibility with Desktop

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5483]
According to https://github.com/status-im/status-react/pull/5319

Update to status-go release 0.10.0 breaks possibility to login in Status Desktop or create new account.
It errors out with following log:

```

Debug: call of RCTStatus::emitSignalEvent ... signal:  {"type":"node.crashed","event":{"error":"node is already running"}}

Debug: RCTStatus::startNode StartNode result:  {"error":""}
```
GIT_TAG for status-go 0.10.0 is a6d69eba

**Comment by churik** [comment]
I believe that this should be fixed ASAP because currently mobile and desktop are based on different status-go versions.
