### ISSUE TITLE
test status-go bip32 fix on status-react side

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#5495]
Testing `status-go` PR [fix child keys derivation adding bytes padding](https://github.com/status-im/status-go/pull/1139)).

### status-react builds with status-go artifact from that PR

Branch: status-im:test/bip32-fix
Android: https://i.diawi.com/FNzR7h
iOS: https://i.diawi.com/EVsTS8

### Problem 

The current implementation of `status-go` derives wrong keys/addresses in certain conditions, more info are in the original PR https://github.com/status-im/status-go/pull/1139

### Test 1

With the mnemonic `radar blur cabbage chef fix engine embark joy scheme fiction master release`, the current `status-go` derives the address `0xc154991dd4c2ddb5c089cf2e0fd23f5f1e41ba72`.

With these changes the correct address should be derived: `0xaC39b311DCEb2A4b2f5d8461c1cdaF756F4F7Ae9`.

### Test 2

Old mnemonic phrases should continue to derive the same addresses.

<blockquote><div><strong><a href="https://i.diawi.com/FNzR7h">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/EVsTS8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
1. able to recover 0xaC39b311DCEb2A4b2f5d8461c1cdaF756F4F7Ae9 with radar blur cabbage chef fix engine embark joy scheme fiction master release

2. able to recover my personal wallet 

3. lets wait for e2e run

**Comment by asemiankevich** [comment]
https://ethstatus.testrail.net/index.php?/runs/view/1121&group_by=tests:status_id&group_order=asc

**Comment by asemiankevich** [comment]
@goranjovic @pilu @adambabik please merge it

**Comment by asemiankevich** [comment]
here is the thread for some context https://status-im.slack.com/archives/CA7R1RK0C/p1534182376000174

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/CA7R1RK0C/p1534182376000174">Slack</a></strong></div></blockquote>
