### ISSUE TITLE
Add support for superrare NFT

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#5496]
### User Story

As a user, I want to have access to my [SuperRare](https://superrare.co/) digital art in my Status wallet.

### Description

*Type*:  Feature

Pixura/SuperRare is the next participant in Status' incubator program. SuperRare will have a public chat inside Status and will be added to the list of curated DApps. 

If a user owns SuperRare NFTs, he should be able to see them in his wallet and have access to basic details for each.

#### Expected behavior
I purchase digital art on SuperRare, and the next time I open my wallet, I can see a count of my SuperRare tokens alongside my other collectibles.

When I click in, I can view my full SuperRare collection with basic metadata for each piece, e.g. `name` and `description`. 

### Actual behavior
SuperRare tokens aren't supported by the Status wallet.

### Additional Information

[SuperRare solidity file](https://github.com/Pixura/smart-contracts/blob/master/contracts/SupeRare.sol)

https://api.pixura.io/graphql can be used to get all collectibles 

[Example metadata](https://ipfs.pixura.io/ipfs/QmWVDR4xYaoXpusB5qrj54E4nptoP7EbcKbaM5GrTkx4CB)

Mainnet contract address: `0x41a322b28d0ff354040e2cbc676f0320d8c8850d`

Ropsten contract address: `0xa42e14b40bb22bc3daaf8ecad9d73bdf44056959`

**Comment by jeluard** [comment]
Contract source: https://github.com/Pixura/smart-contracts/blob/master/contracts/SupeRare.sol
Mainnet address: `0x41a322b28d0ff354040e2cbc676f0320d8c8850d`
Ropsten address: `0xa42e14b40bb22bc3daaf8ecad9d73bdf44056959`

**Comment by jeluard** [comment]
NFT MetaData are returned by `tokenUri`.

An example of returned data is:
```
{"name":"Barn swallow with attitude",
 "description":"Oil, Canvas",
 "tags":["art"," coo"," test"],
 "image":"https://ipfs.pixura.io/ipfs/QmYMyg1o72odf1C29wxbkeWbcuBeKDT1NwFKai9277RuBD"}
```

(from https://ipfs.pixura.io/ipfs/QmWVDR4xYaoXpusB5qrj54E4nptoP7EbcKbaM5GrTkx4CB)

<blockquote></blockquote>

**Comment by charlescrain** [comment]
Querying SuperRare's api to get all the collectibles can be done via the graph api endpoint https://api.pixura.io/graphql

Below is an example of querying all the tokens by the owner's ether address.

To explore the available graphql queries, feel free to use https://api.pixura.io/graphiql which is an interactive place to build the queries.

```node
const axios = require('axios');

const collectiblesByAddress = (address) => {
  return {
    query:`{
      collectiblesByOwner: allErc721Tokens(condition: {owner: "${address}"}) {
        collectibles: nodes {
          owner
          tokenId
         tokenImages: superRareSizedImageByTokenId {	
            standard
            thumbnail
          }
          metadata: erc721MetadatumByTokenId {
            metadataUri
            description
            name
            imageUri
          }
          creator: superRareTokenCreatorByTokenId {
            address
          }
          auctionDetails: superRareAuctionDetailByTokenId {
            currentBidder
            currentBid
          }
          marketDetails: superRareMarketDetailByTokenId {
            currentPrice
          }
        }
      }
    }`
  };
}

async function main() {
  // Notice :: The address does not have `0x` and is completely lowercase.
  const address = "ec8c1050b45789f9ee4d09dcc7d64aaf9e233338";
  // Building the query object.
  const gqlQuery = collectiblesByAddress(address);

  const GRAPHQL_ENDPOINT = `https://api.pixura.io/graphql`;
  try {
    const cRes = await axios.post(GRAPHQL_ENDPOINT, gqlQuery);
    console.log(JSON.stringify(cRes.data, null, 2));
  } catch(e) {
    console.log('Oh no an error!', e);
  }

}

main();
```

<blockquote></blockquote>
<blockquote><div><strong><a href="https://api.pixura.io/graphiql">GraphiQL</a></strong></div></blockquote>

**Comment by charlescrain** [comment]
Let me know if there are any questions 😄

**Comment by charlescrain** [comment]
@jeluard I updated the example to have a `tokenImages` property so you can get images not served from IPFS

**Comment by alwx** [comment]
@charlescrain it now gives us the following error: 

```
Field \"owner\" is not defined by type Erc721TokenCondition.
```

Were there any breaking changes made recently?

**Comment by charlescrain** [comment]
Hi @alwx,
it shouldn't have changed, investigating now.

**Comment by charlescrain** [comment]
@alwx @jeluard Can you guys check now? The VM we used ran out of space. My apologies for that.

**Comment by charlescrain** [comment]
@alwx @jeluard I just double checked the graphql in the example i posted and it is working now.

**Comment by jeluard** [comment]
Looks like the vm restart fixed it. @charlescrain please reopen if you see any other issue!
