### ISSUE TITLE
Cookies disabled in Status browser

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5498]
### Description

*Type*: Bug

*Summary*: Cookies are disabled in Status browser so I am not able to log in to my google account for ex

#### Expected behavior
Enable cookies. We can do that as Chrome does - so enabling them by tapping the appropriate message or something. We also need an option to disable them. 

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/44091712-0ab9f4b8-9fd7-11e8-8933-6ac7d8838689.png)

### Reproduction

- Open Status
- Open Status browser
- Go to accounts.google.com
- Provide creds and log in

### NOTE
in the same scenario above:

- android 7 returns 404
- android 8 says about cookies

**Comment by jeluard** [comment]
@asemiankevich Can you confirm this is still happening?

**Comment by flexsurfer** [comment]
can't reproduce in latest release on ios

**Comment by asemiankevich** [comment]
> @asemiankevich Can you confirm this is still happening?

this is not happening anymore
