### ISSUE TITLE
iOS AppCritique Vulnerability Found: No or Insufficient Default File Protection Specified

### ISSUE THREAD

**Issue by corpetty** [status-im/status-react#5506]
### Note: 
This is an issue created from the [Dark Labs AppCritique](https://appcritique.boozallen.com/) Static Analysis Report performed on Aug 14, 2018 on Status version 0.9.26 build 6382

Some of these may be purposeful and taken care of.  If so, please provide reasoning here and it will be closed upon review.  This issue will then serve as a reference for future potential vulnerability disclosures. 

### Description:
The app does not set, or sets an insufficient default file protection
level. Typically, this results in the
NSFileProtectionCompleteUntilFirstUserAuthentication file
protection level, which means that the file will be accessible any
time after the device is first unlocked after boot. This should be
changed to at least the NSFileProtectionCompleteUnlessOpen
level.

[OWASP: 2016-M2-Insecure Data Storage](https://www.owasp.org/index.php/Mobile_Top_10_2016-M2-Insecure_Data_Storage)

###### FDP_DAR_EXT.1.1

[link](https://www.niap-ccevs.org/MMO/PP/-417-/)
Encryption shall cover all protected data.
Application Note: Protected data is all non-TSF data, including all user or enterprise data. Some or all of this data may be considered sensitive data as well.

###### FMT_CFG_EXT.1.2
[link](https://www.niap-ccevs.org/Documents_and_Guidance/view_td.cfm?td_id=333)

**Comment by churik** [comment]
Hello, @corpetty!
Is this one still relevant?

**Comment by churik** [comment]
Closing as not planned and due to the lack of activity
