### ISSUE TITLE
Status Desktop (3a982e5d): Unable to see text that is selected

### ISSUE THREAD

**Issue by noman-land** [status-im/status-react#5511]
### User Story

As a user, I want to be able to see the text I'm selecting so I can properly see where to stop and end my selection.

### Description

*Type*: Bug

#### Expected behavior
The text should be clearly visible even though it's selected

#### Actual behavior
When selecting text with your mouse, it's not possible to see the selected text.

### Reproduction
![select-color](https://user-images.githubusercontent.com/27938023/44130242-84aeee3e-a01a-11e8-8c55-a92a9aaba106.gif)

### Additional Information
* Status version: `v0.0.1 (3a982e5d)`
* Operating System: macOS 10.12

**Comment by churik** [comment]
It is fixed in nightly 15/08/2018
Also was reported previously  in https://github.com/status-im/status-react/issues/5103
