### ISSUE TITLE
Push notifications of 1-1 chat not shown when app is completely closed

### ISSUE THREAD

**Issue by infebe** [status-im/status-react#5513]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In a 1-1 chat when sending a message from user A to user B, if the app is completely closed in user B, push notifications are not shown.

#### Expected behavior
Push notifications should be shown when an added contact sends a message and the app is not running in the background.

#### Actual behavior
Push notifications are not received.

### Reproduction

- In Device 1: Close Status from the ongoing processes in the background (the background processes are shown by using the "square" button in Android).
- Device 2:  send message to an added contact that exists in device 1

### Additional Information
* Status version: 0.9.25(6360)
* Operating System: Android 6.0
* Device: Huawei P8 Lite ALE-L21 

Note: I have only been able to reproduce this behavior in the Huawei device. I have tried it in a Nexus 5 with Android 6.0.1, and there the push notifications work correctly.

**Comment by lukaszfryc** [comment]
I can't reproduce this issue. It was probably something temporary related to push notifications not being generated.
