### ISSUE TITLE
User cannot receive messages in 1-1 chat after he's back from being offline

### ISSUE THREAD

**Issue by ankaqwerty** [status-im/status-react#5520]
### Description

*Type*: *Bug*
*Summary*: User cannot receive messages in 1-1 chat that were sent while he was offline

User B, sending messages (online):

![image](https://user-images.githubusercontent.com/42421835/44176038-db801680-a0f0-11e8-9c32-aedc9eb06f99.png)

User A, receiving messages (was offline, now online)

![image](https://user-images.githubusercontent.com/42421835/44176183-81cc1c00-a0f1-11e8-9b64-a57bf987e175.png)

#### Expected behavior
After user is back online, messages are received in the order they were sent

#### Actual behavior
After user is back online, messages are not received at all, even after re-entering chat, or user re-login

### Reproduction
 - Open one-to-one chat between users A and B
 - Set user A to be offline, user B is online
 - Send messages from user B to user A
 - Set user A to be online and wait for the messages to appear

### Additional Information
User A (receiving messages) is on mailserver F
User B (sending messages) is on mailserver B

* Status version: 0.9.25 (6360) node bccee2a

* Operating System: Genymotion emulator Samsung Galaxy S6/Android 7.1.0
Real device:
Lenovo TAB-8703X/Android 6.0.1

**Comment by SlizkovaGanna** [comment]
The issue does not reproduce, but it takes about a minute to receive the messages for iOS.
User A (receiving messages) is on mailserver mail-02.do-ams3.eth.beta
User B (sending messages) is on mailserver mail-02.gc-us-central1-a.eth.beta
Re-tested with a nightly build (5 Oct 2018) on iOS 11.4.1 and Android 7.0

**Comment by lukaszfryc** [comment]
> The issue does not reproduce

Let's close it then.
