### ISSUE TITLE
Could not connect to mailserver warning and no messages in Status chat if mailserver A is set

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5523]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: no messages shown if join public chat "status" and constant warning "Could not connect to mailserver " shown if mailserver A is selected, network Mainnet / Ropsten

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can see messages in Status publich chat
#### Actual behavior
[comment]: # (Describe what actually happened.)
 no messages shown if join public chat "status" and constant warning "Could not connect to mailserver " 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and create new account
- in Profile select Mailserver A
- sign in again
- Join public chat Status

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly from Aug 16 http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-31924f-n-fl.apk and https://i.diawi.com/ynGb9s
version 0.9.26 (6406) node a6d69ed
* Operating System: real Galaxy S6 (Android 6.0.1) and iPhone 7 plus

#### Logs

Tf session: https://app.testfairy.com/projects/4803622-status/builds/8559654/sessions/4398730282/?accessToken=ivPABypca70kzCfVfB3ZhXIvtm0
[geth.log](https://github.com/status-im/status-react/files/2293191/geth.log)

<blockquote></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/ynGb9s">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8559654/sessions/4398730282/?accessToken=ivPABypca70kzCfVfB3ZhXIvtm0">TestFairy: Status 0.9.26 (6406) @2018</a></strong></div></blockquote>

**Comment by chadyj** [comment]
I also have the same issue when manually switching to `B`

**Comment by annadanchenko** [comment]
worked fine last weeks
