### ISSUE TITLE
Allow overriding status-go log level from UI

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#5527]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to be able to dynamically change the Go log level so that I can get to the information from geth without needing to generate a special build.

As a user, I want to be able to generate geth logs at the level requested by the developers, so that I can help them fix problems I find.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, the geth log level is determined by a build flag in the `.env` files. The goal of this issue is to allow overriding that log level per account (possibly requires restarting the app). When logged out of an account, the default log level defined in `LOG_LEVEL_STATUS_GO` should apply.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

- Open Status
- Go to Profile, open Advanced section
- Choose new geth log level
- Restart app

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by yenda** [comment]
@PombeirP What kind of settings should we offer ? Should we have a toggle between no log and debug level or a list with all possible log levels ?

**Comment by pedropombeiro** [comment]
@yenda ideally we have a list with `disabled`, `info`, `debug`, `trace`. Normally debug level will be the most interesting, but some times we might need to go down to trace level.

**Comment by yenda** [comment]
@PombeirP I think we can close this one ?
