### ISSUE TITLE
Add UI for sharing deep links

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#5529]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to share links to my contacts, DApps and public chats so they can be conveniently accessed through other apps and published on the web.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Buttons for sharing deep links are added to public chats, profiles and DApps. Tapping on them should present a native sharing sheet with the ability to copy the link or pass it to other apps. Text strings which should be used once shared through 3rd party apps will be provided shortly @obi2020 _could you create a spreadsheet with copy for sharing links through other channels like Twitter, Facebook, messaging apps, email, and tags if any to include. thanks!_

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

- Open a public chat, tap the overflow menu button, select Share chat. Native activity sheet is presented with a choice of sharing options.

- Open a DApp, tap the share button. Native activity sheet is presented with a choice of sharing options.

- Open a private chat, tap the overflow menu button, select View profile. User profile is shown, tap the Share profile link button, native activity sheet is presented with a choice of sharing options. 

- Open your profile, tap the Share my profile button, select Share link, a native activity sheet is presented with a choice of sharing options.

#### Design

Prototype: https://framer.cloud/TPUHM/
Zeplin: [Web](http://zpl.io/bLDLvEJ)

<blockquote><img src="https://framer.cloud/TPUHM/12/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/TPUHM/">Sharing Deep Links</a></strong></div><div>This project was made with Framer, a design tool for turning original concepts into working prototypes.</div></blockquote>

**Comment by obi2020** [comment]
See the [spreadsheet here](https://docs.google.com/spreadsheets/d/1eckf-n5EZdklxVz1oc0dAF05Fclbz-EkuizkkQ7gBV0/edit#gid=533164898&range=A1)

I don't quite understand the last two use cases, though. Is it basically to share someone's (or your own) contact code? I don't understand what else in the profile you'd want to share, as it's currently more like a settings menu

**Comment by lukaszfryc** [comment]
This is really cool! It would be great to have it before ETHBerlin
