### ISSUE TITLE
Crash when logging in after switching networks (Mainnet>Rinkeby, Rinkeby>Mainnet)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5543]
### Description
*Type*: Bug

*Summary*: Status app has crashed when trying to log-in after switching network from Mainnet with RPC to Rinkeby. Crash log is different rom #3981. it was reproduced twice when switching from Mainnet to Rinkeby and vice versa.
I cannot replicate it more.

#### Expected behavior
The app is supposed to crash after switching networks but should not crash later on when logging in.

#### Actual behavior
The app crashed during log-in.

### Reproduction
- Open Status
- Log in
- Change network to Rinkeby
- Try to log in again

### Additional Information
* Status version: nightly, August 17
* Operating System: iOS 11.4
* Device: iPhone 7
* I could not replicate it. Tried 5 times with steps from TF sessions (last 2 min)

* TF session (crash when switching from Mainnet to Rinkeby): [from 20:40](https://app.testfairy.com/projects/4803590-status/builds/8561183/sessions/4398806427/?accessToken=os7xDb4zibpe8Ite8sTP-mlzg70)
* TF session (crash when switching from Rinkeby to Mainnet):[from 17:30](https://app.testfairy.com/projects/4803590-status/builds/8561183/sessions/4398806427/?accessToken=os7xDb4zibpe8Ite8sTP-mlzg70) - last minute is cut, but I switched networks as far as I can remember (my iPhone sometimes can lose WI-FI connection)
Log in both cases is the same:
```
0   StatusIm                            0x00000001019b61a0 0x100f68000 + 10805664
1   StatusIm                            0x00000001019b5640 0x100f68000 + 10802752
2   StatusIm                            0x0000000101b62f08 0x100f68000 + 12562184
3   libdispatch.dylib                   0x0000000181748aa0 0x181747000 + 6816
4   libdispatch.dylib                   0x0000000181748a60 0x181747000 + 6752
5   libdispatch.dylib                   0x000000018174fb84 0x181747000 + 35716
6   libdispatch.dylib                   0x0000000181755cac 0x181747000 + 60588
7   libdispatch.dylib                   0x00000001817559fc 0x181747000 + 59900
8   libsystem_pthread.dylib             0x0000000181a7bfac 0x181a7b000 + 4012
9   libsystem_pthread.dylib             0x0000000181a7bb08 0x181a7b000 + 2824
```

**Comment by asemiankevich** [comment]
Got this when switching from Mainnet to Ropsten
![image](https://user-images.githubusercontent.com/28752642/44262423-b213d780-a223-11e8-8b7c-e515e39dcbde.png)
