### ISSUE TITLE
Add MacOS Menu Bar to Status Desktop 

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5547]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have the possibility to use commands and attributes from the Desktop application's menu bar.

### Description

*Type*: Feature

*Summary*: Implement the menu bar on MacOS.

#### Expected behavior
The user should be able to select options from the menu app that allows her to perform different actions.

#### Actual behavior
Menu bar is available with very few useful options:
<img width="227" alt="captura de pantalla 2018-08-17 a la s 10 11 48 a m" src="https://user-images.githubusercontent.com/37297779/44267885-42432400-a206-11e8-98a1-929ad7513477.png">

### Solution
**Menu proposal**

-   _[Apple menu]_
- **Status**
-- About Status
-- Check for Updates
-- Hide Status (⌘H)
-- Hide Others (⌥⌘H)
-- Log Out
-- Quit Status (⌘Q)

- Edit _[only for text editing]_
-- Undo Typing (⌘Z)
-- Redo Typing (⇧⌘Z)
-- Cut (⌘X)
-- Copy (⌘C)
-- Paste (⌘V)
-- Delete (⌫)
-- Select All

- View
-- Full screen / Exit full screen (⇧⌘F)

- Chat  _[app specific options]_
-- Start new chat  _[Opens new 1:1 chat screen zpl.io/a7ynPBE]_
-- Join public chat  _[Opens new public chat screen zpl.io/aBE71Xe]_
-- Share contact code  _[Opens user pop-up with contact code zpl.io/bAqjqPO]_

- Window
-- Minimize (⌘M)
-- Zoom

- Help
-- [Search box for menu options]
-- FAQs _[link to page]_

### Visuals
![menu](https://user-images.githubusercontent.com/37297779/44268547-2a6c9f80-a208-11e8-8733-6dc79acf72cc.png)
 

### Additional Information
* Operating System: MacOS X

**Comment by chadyj** [comment]
Very nice! Feels more Mac like already :)

**Comment by EugeOrtiz** [comment]
There are a couple of issues related to this one. Just commenting so It doesn't get closed.

**Comment by churik** [comment]
Not a priority anymore
