### ISSUE TITLE
Implement navigation between fields using "Tab" key

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5548]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use "TAB" key to navigate to next field.

### Description

*Type*: Feature

*Summary*: navigation in desktop or web applications often implemented with using Enter key to proceed, Tab key - to jump to next field. In status-desktop it alway  inserted a tab character in the selected fields.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
switched to next field 

#### Actual behavior
![tab_char](https://user-images.githubusercontent.com/4557972/44271230-442ad880-a242-11e8-8512-211ac4f09eff.png)

### Reproductio

- Open Status
- Go to  "Sign in to another account"
- Click "Tab"

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 17.08.2018
* Operating System: Mac OsX

**Comment by Swader** [comment]
This is an important accessibility issue and needs to stay open.
