### ISSUE TITLE
For Sender, transaction status does not update in 1-1 chat from Pending

### ISSUE THREAD

**Issue by ankaqwerty** [status-im/status-react#5549]
### Description

*Type*: *Bug*

*Summary*: When a transaction is sent in 1-1 chat, after it's completed transaction status does not update from 'Pending' to 'Completed' for a Sender. 
For a Receiver it is updated to Completed automatically, as expected.

#### Expected behavior
Statuses for transactions should change automatically in 1-1 chat for both Sender and Receiver

#### Actual behavior
Transaction status in the chat changes only for Receiver, but stays as 'Pending' for Sender.
When Sender opens transaction details in the chat, and comes back to the chat after that (using < arrow), only then status is updated to Completed.

### Reproduction

- Open 1-1 chat between users A (Sender) and B (Receiver)
- Send a payment in ETH for any amount from user A to user B
- Go to ropsten.etherscan.io and check transaction's status
- When transaction has 12 confirmations, check it's status in 1-1 chat from perspective of user A and user B
- As user A (Sender), open your transaction's details page in 1-1 chat
- Click an arrow to go back to 1-1 chat 

### Additional Information

* Status version: 0.9.25 (6360) node bccee2a

* Operating System: Genymotion emulator Samsung Galaxy S6/Android 7.1.0
Real device:
Lenovo TAB-8703X/Android 6.0.1

**Comment by lukaszfryc** [comment]
This issue is described in https://github.com/status-im/status-react/issues/4865 and will be included in the next release (0.9.26).
