### ISSUE TITLE
'Amount' area is not accessible for input in 1-1 chat after tapping on it

### ISSUE THREAD

**Issue by ankaqwerty** [status-im/status-react#5550]
### Description

*Type*: _Bug_

*Summary*: This is a UX issue that appears when a user is a bit sloppy. 
If a user misses the usual flow and taps one extra time on 'Amount' field, he will face a UX problem with inserting amount for his transaction. User will need to tap outside the 'Amount' area and move a cursor to set it in the right spot to input the data. 
Similar behaviour reproduces for both /send and /request user scenarios

#### Expected behavior
Cursor should not disappear, user should not be blocked from inserting amount at any point

#### Actual behavior
Cursor disappears when you tap on 'Amount' field, and appears again only after clicking on different areas of the input field
https://drive.google.com/file/d/1oGl8OwSPW_yP1Ev3uMdTXaS6kA4gKWz3/view?usp=sharing

### Reproduction
- Go to 1-1 chat
- Tap on '/' icon
- Tap on '/send Send a payment 
- Tap on 'ETH Ether'
- After cursor appeared, tap on 'Amount' area
Note: Similar behaviour reproduces for /request user scenario
 
### Additional Information
**Status version**: 0.9.25 (6360) node bccee2a

Operating System: Genymotion emulator Samsung Galaxy S6/Android 7.1.0
Real device:
Lenovo TAB-8703X/Android 6.0.1

<blockquote><img src="https://lh5.googleusercontent.com/HVDvOvq9ZyRjnC6Q7iNvNSEUkpt2LshvJuoU4P0T_TcaCOLc9Voqy2Wls2A=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1oGl8OwSPW_yP1Ev3uMdTXaS6kA4gKWz3/view?usp=sharing&usp=embed_facebook">ice_video_20180818-002253.webm</a></strong></div></blockquote>

**Comment by SlizkovaGanna** [comment]
The issue is still valid.
Re-tested with a nightly build (5 Oct 2018) on iOS 11.4.1 and Android 7.0
