### ISSUE TITLE
Deleted chat does not re-appear with new messages for logged out user

### ISSUE THREAD

**Issue by ankaqwerty** [status-im/status-react#5551]
### Description

*Type*: _Bug_

*Summary*: 

When user deletes the chat and logs out, he receives push notifications that lead to nothing. 
General issue is that if user is logged out, his deleted chat does not re-appear if the messages were received while he was logged out.
Note: When user is logged in, the behaviour is expected and chat does re-appear with new messages in it.

#### Expected behavior
User is redirected to Home page with a chat that re-appears with new messages in it

#### Actual behavior
User is redirected to Home page with no chat 

### Reproduction

- Open pre-existing 1-1 chat between users A and B
- Delete chat as user A
- Log out or close the app
- Send a message as user B in the same chat 
- Wait for the push notification to appear, and click on it

### Additional Information

* Status version: 0.9.25 (6360) node bccee2a

Operating System: Genymotion emulator Samsung Galaxy S6/Android 7.1.0
Real device:
Lenovo TAB-8703X/Android 6.0.1

**Comment by lukaszfryc** [comment]
Hi @ankaqwerty, thanks for the issue. Here is how it works on my side (tested on Android, Status 0.9.25)

> General issue is that if user is logged out, his deleted chat does not re-appear if the messages were received while he was logged out.

When I log out, receive a notification, open the app and log in again I see the chat with 1 unread message. And, this is what I expect to see.


> Note: When user is logged in, the behaviour is expected and chat does re-appear with new messages in it.

Actually, the chat **should** re-appear when new message is received.

---

Maybe these issues were due to mailservers unavilability, did you see some warnings about mailservers being offline? Could you try those scenarions once again?

**Comment by ankaqwerty** [comment]
Hi, @lukaszfryc !

There were no messages about mailservers unavailability.
The steps that should be followed are:
1) Create a 1-1 chat between users A and B
2) Delete that chat by user A
3) Log out as a user A
4) Send a message in the chat as user B
5) Login as user A and check that your chat has re-appeared with a message.
The current result is that the chat does **not** re-appear

This is Status version: 0.9.25 (6360) node bccee2a (release)

**Comment by SlizkovaGanna** [comment]
Re-tested with a nightly build (5 Oct 2018) on iOS 11.4.1 and Android 7.0 - issue no longer reproduces
