### ISSUE TITLE
UX updates on Recovery flows

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#5554]
Align recovery enter mnemonic with backup seedphrase flow

User Story
As a user, I want to have a right perception on what kind of password do I need to provide during the recovery flow that I'm not trying to recall my old password.

(Needed to ETHBerlin)

### Description
_Type_: Feature

_Summary_: Current recovery flow confuses users, makes them think they need to provide their old password which is not correct. I propose to add separate 2 steps for password creation and confirmation. Also, I renamed (Hester proposed this many times) action on the main screen from `I already have an account` to `Access account`.

#### Expected behavior
![slice](https://user-images.githubusercontent.com/6559881/44298641-902b5b00-a2de-11e8-929b-8fb140869d29.png)

#### Actual behavior
![](https://user-images.githubusercontent.com/6559881/44298585-9ec54280-a2dd-11e8-9f02-47cbf84c2fa6.png)

**Comment by denis-sharypin** [comment]
Possibly could be a good moment to solve this issue https://github.com/status-im/status-react/issues/4856 @obi2020  please take a look

**Comment by chadyj** [comment]
How about a forgot password flow, or at least info on how to proceed?

**Comment by obi2020** [comment]
What if the user wants to use their old password? Does it matter; should we advise against or explicitly say that it should be a new password? @chadyj

**Comment by rachelhamlin** [comment]
@chadyj @obi2020 you don't need password if you have recovery phrase, so do we need a forgot password flow?

On the flip side, if you know your old pw and want to re-use it, I think that's probably okay—but can investigate if some vulnerability is introduced by doing so. 

If anything, it's probably just not clear that the password essentially doesn't matter for recovery.

**Comment by obi2020** [comment]
Here's what I'm working with, as a starting point: https://docs.google.com/presentation/d/1WPpqaCPEjrmTRayZZQWvuhznSSBW3uN48VpaIMmfEq8/edit#slide=id.p

Please provide you thoughts & feedback either here or in the doc. A couple things I'm grappling with

- The two CTAs on the first screen are not symmetrical, but I feel there's a distinct difference between creating a Status account and importing a wallet. 

- What's not on the page yet: letting the user know that when they import a wallet they also create a Status contact ID (true?)


<blockquote><div><strong><a href="https://docs.google.com/presentation/d/1WPpqaCPEjrmTRayZZQWvuhznSSBW3uN48VpaIMmfEq8/edit#slide=id.p">Google Slides - create and edit presentations online, for free.</a></strong></div><div>Create a new presentation and edit with others at the same time. Get stuff done with or without an internet connection. Use Slides to edit PowerPoint files. Free from Google.</div></blockquote>

**Comment by obi2020** [comment]
<img width="1122" alt="screen shot 2018-08-20 at 4 47 52 pm" src="https://user-images.githubusercontent.com/3373750/44365820-d4faf180-a498-11e8-86ef-4cde2a8496c4.png">

**Comment by rachelhamlin** [comment]
@obi2020 awesome. Just commented with my thoughts. I really like `Import wallet` as the bottom CTA. Why not use an active verb for `New account` as well (e.g. Create account)?

**Comment by obi2020** [comment]
Good point. `Create account` it is. 

Could we talk about what defines an "account" - what is contained within a Status account?

**Comment by obi2020** [comment]
A related discussion is happening here https://discuss.status.im/t/pfs-and-wallet-recovery/335/5 

There's more to do here re: communicating how contacts work for restored accounts

> when a user that has just recovered their wallet receive a message from a previous contact, he will not be able to decrypt it (which is the desired behavior otherwise it would break pfs), but he will know that a message has been received.



<blockquote><img src="https://discuss.status.im/user_avatar/discuss.status.im/obi2020/200/48_1.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/pfs-and-wallet-recovery/335/5">PFS and wallet recovery</a></strong></div><div>{Name generated from public key} sent you a message. Would you like to establish a secure channel with them?”  Ignore / Connect  @cammellos further simplied version of what you wrote. I removed " information they have is outdated" because it hinting as what might be info that’s non-essential to the user.  In fact, could it be used anytime someone is trying to contact you (not just after recovery?  From an product/ experience standpoint, is important to indicate that you were connected to the per...</div></blockquote>

**Comment by rachelhamlin** [comment]
@obi2020 👍 cool. Just shot Andrea a question on the thread. Sounds to me like you recover your wallet but it more or less generates a new "chat account" each time.

**Comment by annadanchenko** [comment]
@rachelhamlin @denis-sharypin @hesterbruikman is Recovery flow still a todo?

**Comment by hesterbruikman** [comment]
Yes, looks like it is, thanks for flagging! Will add this issue to Onboarding on pivotal.

**Comment by rachelhamlin** [comment]
@hesterbruikman ooh, do we have a pivotal board for that, or is it under core? Edit: Looks like core, I see the story.
