### ISSUE TITLE
Sign-in with biometric input (TouchID/FaceID)

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#5556]
### User Story

As a user I want to be able to protect signing in to the app using biometric auth on my phone or tablet.

**Comment by Swader** [comment]
6 months later...

**Comment by mandrigin** [comment]
Was moved to Pivotal, makes no sense to keep
it here too: https://www.pivotaltracker.com/epic/show/4179936


<blockquote><div><strong><a href="https://www.pivotaltracker.com/epic/show/4179936">Protecting login using biometrics (quicker login) - Pivotal Tracker</a></strong></div></blockquote>
