### ISSUE TITLE
Add SuperRare to DApp list

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5561]
### User Story

As a user, I want to see the SuperRare DApp in Status' curated list so I can buy rare digital art.

### Description

*Type*: Feature

*Summary*: Add SuperRare DApp to Status.

Category: Marketplaces

Description: `Buy, sell and collect unique digital creations by artists around the world`

URL: https://superrare.co/market

[SVG on gdrive](https://drive.google.com/open?id=1GptGsOCQw2Fl7xIIAGHv3EEY_bf6n0cT)
[Font on gdrive](https://drive.google.com/open?id=1u4jiotPGnPrMRDdsRU_Gem3OeHUAinya)

#### Expected behavior
SuperRare is listed inside Status curated DApps.

#### Actual behavior
SuperRare not listed.

<blockquote><img src="https://pbs.twimg.com/profile_images/980939084637048833/Hr3WdoK4_400x400.jpg" width="48" align="right"><div>Super Rare Digital Art & Collectibles</div><div><strong><a href="https://superrare.co">SuperRare - Create and Collect Crypto Art</a></strong></div><div>SuperRare - Create, Collect, and trade crypto art and super rare digital collectibles</div></blockquote>

**Comment by errorists** [comment]
![sr-80](https://user-images.githubusercontent.com/4932774/44516683-fbea3b00-a6c5-11e8-978a-39859919aaef.png)
Attached asset
