### ISSUE TITLE
java.lang.NoSuchMethodError: No static method SendTransaction(Ljava/lang/String;Ljava/lang/String;) and crash if send ETH from Wallet 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5563]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Android only. Sent ETH from Wallet and got crash after signing transaction:
``` 
Error java.lang.NoSuchMethodError: No static method SendTransaction(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; in class Lcom/github/status_im/status_go/Statusgo; or its super classes (declaration of 'com.github.status_im.status_go.Statusgo' appears in base.apk!classes84.dex)
	at im.status.ethereum.module.StatusModule$8.run(StatusModule.java:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764) 
```
Note that same scenario for wallet refactoring PR https://github.com/status-im/status-react/pull/5455#issuecomment-413874062 on Android works fine 
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Tx is sent
#### Actual behavior
[comment]: # (Describe what actually happened.)
Crash
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status (Ropsten)
- Wallet -> Send transaction 0.0001 to the contact
- Sign transaction by entering valid passowrd

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build Aug 20
* Operating System: Android 9, Pixel XL; Android 6.0.1 Galaxy S6, also on Android 7 and 8
on iOS 11.0.3 and iOS 11.4 - all is fine, tx is sent as expected
#### Logs

https://app.testfairy.com/projects/4803622-status/builds/8562817/sessions/4398948981/?accessToken=kAy3uOekgBIzGbYeSRzSfg5Q-s4

[geth.log](https://github.com/status-im/status-react/files/2302015/geth.log)

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8562817/sessions/4398948981/?accessToken=kAy3uOekgBIzGbYeSRzSfg5Q-s4">TestFairy: Status 0.9.26 (6453) @2018</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
work fine on next nightly build https://ci.status.im/job/status-react/job/nightly/591/

<blockquote><img src="/static/b2f7dc7b/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/nightly/591/">status-react » nightly #591 [Jenkins]</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
now it happens again for same steps on new nightly build https://ci.status.im/job/status-react/job/nightly/594/ 
See TF session: https://app.testfairy.com/projects/4803622-status/builds/8564857/sessions/4399026405/?accessToken=yGXBA5XqMXcMO0xWwokXp4XbJPc

<blockquote><img src="/static/db91a816/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/nightly/594/">status-react » nightly #594 [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8564857/sessions/4399026405/?accessToken=yGXBA5XqMXcMO0xWwokXp4XbJPc">TestFairy: Status 0.9.26 (6475) @2018</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
I saw this issue with tonight's nightly just by starting the app (it appeared immediately after the nightly popup warning, without user interaction).

![screenshot_20180822-101253](https://user-images.githubusercontent.com/138074/44457032-6e91e280-a602-11e8-88f3-04ef54859cfd.jpg)

**Comment by annadanchenko** [comment]
on Android build from nightly https://jenkins.status.im/job/status-react/job/nightly/600/ can reproduce the issue with sending funds too

<blockquote><img src="/static/db91a816/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/600/">status-react » nightly #600 [Jenkins]</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
on Android build https://jenkins.status.im/job/status-react/job/nightly/609/ if install and run app (not upgrade) then have similar issue as in https://github.com/status-im/status-react/issues/5563#issuecomment-414979259

 TF session https://app.testfairy.com/projects/4803622-status/builds/8566051/sessions/4399093797/?accessToken=G5dyZEBh3wKpTJNkZ-Pl5cIENOo

```
java.lang.NoSuchMethodError: No static method GenerateConfig(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String; in class Lcom/github/status_im/status_go/Statusgo; or its super classes (declaration of 'com.github.status_im.status_go.Statusgo' appears in base.apk!classes41.dex)
	at im.status.ethereum.module.StatusModule.generateConfig(StatusModule.java:159)
	at im.status.ethereum.module.StatusModule.generateConfigFromDefaultConfig(StatusModule.java:211)
	at im.status.ethereum.module.StatusModule.doStartNode(StatusModule.java:297)
	at im.status.ethereum.module.StatusModule.access$000(StatusModule.java:37)
	at im.status.ethereum.module.StatusModule$1.run(StatusModule.java:402)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by mandrigin** [comment]
@annadanchenko we cleaned up all the runners now. is it still happening in the latest nightly and the latest release branch? if not, please close it :)

**Comment by dshulyak** [comment]
In case it will be helpful I had an exactly same error as @PombeirP using this build https://ci.status.im/job/status-react/job/parametrized_build/782/ . It was working fine on IOs, but crashing right after the start on Android.

<blockquote><img src="/static/c32cacaf/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/parametrized_build/782/">status-react » parametrized_build #782 [Jenkins]</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
In case it is helpful, I've come across this yesterday when doing a fully local build (using `scripts/bundle-status-go.sh android`), and the only way to solve it was to run `git reset -xf` to clean any state not kept in git from the local repo. Then I could regenerate the status-go `.aar` file and have it linked correctly. Will do some more testing locally to try to understand what might be causing this.

**Comment by goranjovic** [comment]
didn't happen in a while
