### ISSUE TITLE
Chat history jumps to last message at different actions (scrolling history to the top, switching between chats, hitting send)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5573]
### Description

*Type*: Bug
*Summary*: 
When you are switching between chats instead of showing last message app scrolling through history and then jumps to last message (looks like flickering).
Depends on laptop characteristics, glitches are shown ~50 ms (16 GB onboard memory)  to ~100-150 ms (4 GB onboard memory).
Can be related to https://github.com/status-im/status-react/issues/5271
Also app jumps to last message if you scroll to the top of existing history  (in my case week ago).

#### Expected behavior
1) no glitches when switching between chats  
2) no redirecting to last message when scrolling to the top of chat history

#### Actual behavior
1) (slowed to see glitches)
![glitch](https://user-images.githubusercontent.com/4557972/44397598-96713f80-a549-11e8-8283-7cfd1e61ce1e.gif)
2) chat history jumps to last message

### Reproduction

*Scenario 1:*
- Open Status Desktop
- Open multiple chats and start switching between them

*Scenario 2:*
- Open Status Desktop
- navigate to chat with longest history (i.e. > 1 week)
- scroll to the top of chat history

### Additional Information
* Status version: nightly 21/08/2018
* Operating System: Mac OSx
* Video for scenario 2: http://take.ms/8Wx1N

**Comment by chadyj** [comment]
From Max:

> that might be related to the implementation of optimized ScrollView which was added recently, ScrollView is loaded to first message and it's required to jump to the last message programmatically. Probably, glitch is because of that jump.

**Comment by chadyj** [comment]
This issue also happens when typing a new message and hitting send. For a split-second the screen jumps to the top, then back down again.

**Comment by maxhora** [comment]
Currently, implementation for ScrollView optimization resets underlying data model on any message add/delete. Updating implementation to have data model with incremental data updates support (not required to reset and re-draw all items every time on data change ) and, probably, setting of currentIndex to the last item in model, might help with ui glitches related to strange jumping.
