### ISSUE TITLE
Refactor all subs that use keyword as function 

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#5576]
### Description

Originally found while debugging issue #5353. 

`(re-frame/reg-sub :browsers :browser/browsers)`

What happens in the example above is that keywords as functions accept two params:
1. the map 
2.  result if not entry found.

Subs on the other hand pass params as follows:
1.  `db` i.e. also map
2. vector with sub name and any additional params, e.g. in this case `[:browsers]`

So  #5353 specifically was caused by this sub returning `[:browsers]` if by some obscure reason it didn't have this field in app-db.

*Type*: Bug

*Summary*: 

We shouldn't use keywords as subscription functions to avoid any weird problems like this one, and we should replace any existing cases with actual functions that do not pass the unintended default fallback, e.g. in this case something like this:

`(re-frame/reg-sub :browsers #(:browser/browsers %))`

**Comment by yenda** [comment]
@goranjovic I believe this can be closed ? I saw the commit in develop

**Comment by goranjovic** [comment]
@yenda which one? I only addressed one instance in that PR, there's dozens more, just grep `reg-sub`
