### ISSUE TITLE
Add BRLN coin to mainnet assets

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5582]
### User Story

As an ETHBerlin attendee, I want to be able to use the Berlin coin for completing Bounties on Bounties Network during ETHBerlin (and beyond??). 

### Description

*Type*: Feature

*Summary*: 

Add Berlin coin to mainnet assets.

Contract address: 0x80046305aaab08f6033b56a360c184391165dc2d

[BRLN icon](https://drive.google.com/open?id=1M6N5xfS9gXqGvO04CbxaWv6FH5EvjkEB)

#### Expected behavior
BRLN coin is listed in mainnet assets.

#### Actual behavior
No BRLN coin.

**Comment by goranjovic** [comment]
@rachelhamlin what's a good way to get some tokens for testing?

**Comment by rachelhamlin** [comment]
@goranjovic I knew I forgot something. :) I'll ping them.
