### ISSUE TITLE
Implement Manage permissions screen and option for web3 provider Opt-in access

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5584]
### Description

*Type*: Feature

*Summary*: 
Nov 2 deadline

Continue implementation of https://github.com/status-im/status-react/issues/5260 task. First part was implemented in https://github.com/status-im/status-react/pull/5497 (web3 injection was a priority). This task implements `manage permissions` screen and option.

#### Expected behavior

![image](https://user-images.githubusercontent.com/28752642/44454451-44412480-a604-11e8-9220-293f9a61945b.png)

The design currently shows a link to the `Manage permissions` screen, which has been dropped.

Instead, a user can simply find their settings from the profile screen. The `Web3 permissions` option can be listed beneath `Network`. 

![image](https://user-images.githubusercontent.com/28752642/44454469-51f6aa00-a604-11e8-8473-1c616fc0fdd7.png)

**Comment by rachelhamlin** [comment]
Designs are updated here: https://www.figma.com/file/JEYzJxBPSmuLBffZO0CT9rj2/Web3-and-Status-API-permissions?node-id=41%3A38

In the future, we can explore:
- options to turn these permissions back `On` from this screen later
- making these settings accessible from the browser itself
- whether we can send back a more specific response from the user to the DApp, e.g. `Ignore for now`
