### ISSUE TITLE
Fact check the technical accuracy of marketing

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5585]
From the wall of shame:

> Sometimes we convey that our tech is more decentralized or secure than it really is. Lack of technical proofing of communications leads to this problem.
> 
> This is lying to our users and can create false sense of security. We should be honest and transparent with our flaws

Todo: 
1. Review marketing claims and statements >> [DOC](https://docs.google.com/document/d/14Twg1zPb-NNQmzev1AADETqNpoWZC_jZuF3jhWzUUNM/edit?usp=sharing)
2. Fact check and clarify

**Comment by oskarth** [comment]
How are we measuring success of this?

**Comment by chadyj** [comment]
> How are we measuring success of this?

- Review claims
- Fact check and highlight incorrect statements
- Success is addressing incorrect statements

Ping @j-zerah please make this a priority.

**Comment by j-zerah** [comment]
how do you want me to document this? We have been asking all teams to review new material.
https://docs.google.com/document/d/1j8qX9r5EGmVahPfZnQNJg8HGEInxgSWG2pO81_6Jfg8/edit

We remove any claims from new website copy
https://docs.google.com/document/d/1Ftt5zsvNkbUstt5xeCe8uRYyNdD9gbtYo127yOk8GH8/edit?ts=5bc284bd

without doing an entire audit (which will come after devcon) im not sure how you want to track and measure this

<blockquote><div><strong><a href="https://docs.google.com/document/d/1j8qX9r5EGmVahPfZnQNJg8HGEInxgSWG2pO81_6Jfg8/edit">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>
<blockquote><div><strong><a href="https://docs.google.com/document/d/1Ftt5zsvNkbUstt5xeCe8uRYyNdD9gbtYo127yOk8GH8/edit?ts=5bc284bd">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>

**Comment by chadyj** [comment]
Perhaps if we can have one document with all website copy. Then doing a discuss post asking everyone to fact check and comment, and work on revisions. We need to bridge marketing + engineering. Thoughts?

**Comment by j-zerah** [comment]
that works. Pasted above is the WIP copy deck. Once it is final, we can fact check it. But please note, we have asked people to weigh in on these (i.e. Iuri from embark, Akshi from Studio, Jacek from Nimbus).

**Comment by oskarth** [comment]
FWIW I know it has gotten a lot better, it's just not clear to me what success criteria looks like - some process that is ongoing and is followed everytime there's a big marketing push, perhaps. Don't know.

**Comment by mandrigin** [comment]
@oskarth do we need this issue to stay open?

**Comment by oskarth** [comment]
:man_shrugging:

**Comment by oskarth** [comment]
Success criteria not clear so issue is poorly defined. Closing.

(This doesn't mean this may or may not still be a problem, just that it isn't sufficiently isolated in this issue. Hopefully it'll come up in other forms.)
