### ISSUE TITLE
Perfect Forward Secrecy (PFS)

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5586]
This is a meta issue for implementing PFS and is mostly used as an overview and for visibility.

Discussions

- [Kick off thread](https://discuss.status.im/t/forward-secrecy/150)
- [PFS and wallet recovery](https://discuss.status.im/t/pfs-and-wallet-recovery/335/1)
- [Idea PR discussion](https://github.com/status-im/ideas/pull/289)
- [Slack](https://status-im.slack.com/messages/CC6C0271B)

Idea: 

- [Idea 289](https://github.com/status-im/ideas/blob/master/ideas/289-perfect-forward-secrecy.md)

Issues

- [X3DH key exchange](https://github.com/status-im/status-go-sdk/issues/36)
- [Double ratchet as first step](https://github.com/status-im/status-go-sdk/issues/35)
- [Chat spec and documentation](https://github.com/status-im/status-react/issues/5598)

**Comment by cammellos** [comment]
I will close this for now and create separate issues for the remaining parts
