### ISSUE TITLE
End-to-end Deterministic Builds

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5587]
We have no idea if our build and release pipeline is compromised and the binary in distribution channels is legit. Having multiple parties and then sign reduces our attack surface of hacks/bugs in software to at least the version control and source code is a huge win.

Also having this means we will have deterministic builds, which will dramatically reduce the high barrier of entry for developers to setup their environments. Ideally we should get to 1 command builds.

Links:
- [F droid reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/)
- [reproducible-builds.org](https://reproducible-builds.org/docs/)
- Slack: [#282-deterministic](https://status-im.slack.com/messages/CCEE9F4EP)

Idea:
- [Idea PR](https://github.com/status-im/ideas/pull/297)

**Comment by Graeme-Code** [comment]
Conversation is happening here: https://github.com/status-im/ideas/pull/297

**Comment by Graeme-Code** [comment]
Requires consensus on a first step.

**Comment by pedropombeiro** [comment]
> Also having this means we will have deterministic builds, which will dramatically reduce the high barrier of entry for developers to setup their environments. Ideally we should get to 1 command builds.

This has already been achieved for Android builds with the work I've done earlier in the year on pure Nix e2e builds.
