### ISSUE TITLE
Requires JSON-RPC server to work (SPOF)

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5588]
JSON-RPC is the only means by which a user can connect to Ethereum using Status. It's a trusted intermediary, not decentralized. Light client/ULC is required for decentralization.

Issue:
- [Re-enable LES as option](https://github.com/status-im/status-go/issues/1025)

**Comment by chadyj** [comment]
Update here https://github.com/status-im/status-react/pull/6007

Adding LES as an option

**Comment by cammellos** [comment]
No current effort is being done on this, so closing for now.
