### ISSUE TITLE
Cluster DDoS protection

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5589]
Our cluster is easy to take down and it's also a single point of failure; service stops if it's attacked.

More context:

> Cluster is small and can be taken down, the ultimate solution is to get our changes upstream and Whisper enabled by default (but we should prove that Whisper is indeed scalable, and if not, make it so which requires protocol work) 
> 
> In the shorter term, we can decentralize our specialized nodes by putting Status nodes on DAppNode.io it's very easy all we need to do is provide a Docker Image (which we already have) 
> 
> We can also enable our mail servers for Status Desktop, which was the original idea. (and later users can earn SNT for delivering mailserver requests)
> 
> From Jordi about Dappnode
> You can connect @eduadiez:matrix.org via Riot Check https://dappnode.io
> 
> In addition to this we can introduce a simple Staking model where to fulfil service a user should stake SNT on a trust-basis, where the cluster node can claim the SNT whenever it desires (the "gentleman's agreement" being that the node won't touch the stake except when it beleives there is bad behaviour.
> 
> This can also be extended for public chats, although will require user-client quorum.

**Comment by Graeme-Code** [comment]
Attempting to summarize  #5591 and #5590 as well as #5589 into one post to one thread to understand if its possible one solution can help with all three of these issues. Editing this on https://docs.google.com/document/d/1u3fTT4v3-wZaLlSy2SAurbSYeKUvg9a75ie-RGFtG_c/edit# . 

<blockquote><img src="https://lh6.googleusercontent.com/4Ozks089kKGFJgR2ISxT8xvrowfsBdhtIsEjScIoQBhCMVJ-QCdnZadd_fYisFUUvypy-w=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/document/d/1u3fTT4v3-wZaLlSy2SAurbSYeKUvg9a75ie-RGFtG_c/edit?usp=embed_facebook">Decentralzied spam resistent messaging</a></strong></div><div>Decentralized and stable communications Goal  One of Status’s core principles is to be decentralized. At the moment Status has centralized areas of infrastructure which makes it vulnerable to Ddos attacks as well as been opposed to Status’s principle of decentralization.   This problem affects th...</div></blockquote>

**Comment by oskarth** [comment]
@adambabik @jakubgs What's the state of this?

**Comment by jakubgs** [comment]
We have iptables rate limiting rules in place here:
https://github.com/status-im/infra-eth-cluster/blob/master/ansible/roles/rate-limit/defaults/main.yml
https://github.com/status-im/infra-eth-cluster/blob/master/ansible/roles/rate-limit/tasks/main.yml

I did minimal tests to verify it works, but I guess a proper stress test would be in order.

<blockquote><div><strong><a href="https://github.com/status-im/infra-eth-cluster/blob/master/ansible/roles/rate-limit/defaults/main.yml">Page not found · GitHub</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://github.com/status-im/infra-eth-cluster/blob/master/ansible/roles/rate-limit/tasks/main.yml">Page not found · GitHub</a></strong></div></blockquote>
