### ISSUE TITLE
Whisper spamming protection

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5590]
Whisper uses PoW as an anti-spam mechanism, but we have had to reduce this for mobile usage, combined with a SNT staking mechanism we can disourage spam further and compensate nodes for having to deal with it.

Notes:
- [Notes](https://hackmd.io/UaP81E_QSTe7eOhBb_Caag)

**Comment by oskarth** [comment]
@adambabik what's the state of this?

**Comment by adambabik** [comment]
@dshulyak implemented rate limiting solution that is being finalized I believe. It allows Whisper nodes to monitor the volume of ingress and egress network traffic. PRs: https://github.com/status-im/whisper/pull/1 and https://github.com/status-im/status-go/pull/1222.

**Comment by oskarth** [comment]
Is there a plan to push this to client and do stress testing?

cc @chadyj @annadanchenko

**Comment by oskarth** [comment]
For client protection need to integrate in UI probably, cc @PombeirP as well

**Comment by chadyj** [comment]
> Is there a plan to push this to client and do stress testing?
> 

No plan has been discussed. @adambabik @PombeirP can you please elaborate what is needed for testing in an issue?

**Comment by adambabik** [comment]
Let's wait with the UI work until we specify signals emitted from status-go. What we can collect is some UX scenarios. The obvious one we want to support is to allow unsubscribing from particular public/private channels depending on how much data they generate.

**Comment by hesterbruikman** [comment]
@oskarth can you tell me if this issue is still relevant on Waku?

**Comment by oskarth** [comment]
@hesterbruikman it is mitigated but not completely solved by rate limiting as an option in Waku: https://specs.vac.dev/specs/waku/waku.html

However, it isn't clear to me to what extent this has been enabled (as in actually disconnecting spamming peers, not just disconnecting) and/or battle tested in the actual app. Once https://github.com/status-im/specs/issues/61 is addressed our configuration should be specified in the Status specs.

cc @andremedeiros @Samyoul @jakubgs for any additional info here
