### ISSUE TITLE
Cluster Single Point of Failure

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5592]
Cluster is 'Centralized' thinking and we should be setting our systems up so they are decentralized. Let's not get into a position where we are like Infura (who spends $500k - 1M a month to serve requests) it's unnessary and antithetical to what we're trying to achieve.

**Comment by oskarth** [comment]
See:
- https://github.com/status-im/status-react/issues/6136
- https://github.com/status-im/status-react/issues/6133
- https://github.com/status-im/status-react/issues/6132
- https://github.com/status-im/status-react/issues/6127
- https://github.com/status-im/status-react/issues/6110
