### ISSUE TITLE
Contact back up - PFS and wallet recovery

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5594]
Discussion on [discuss.status.im](https://discuss.status.im/t/pfs-and-wallet-recovery/335)

> A problem that we need to solve is wallet recovery and how to handle this.
> 
> When a user recover their wallet they will lose all the contacts and messages.
> 
> Currently if a contact sends a message to a user who has just recovered their account everything works as expected and the user is able to decrypt the message.
> 
> Because X3DH/DR is a stateful process it means that when a user that has just recovered their wallet receive a message from a previous contact, he will not be able to decrypt it (which is the desired behavior otherwise it would break pfs), but he will know that a message has been received.
> 
> We need a UX solution on how to explain this to the user.
> 
> The most basic thing I can think of is:
> 
> When such messages are received, we display a popup/message/chat/whatever to the user, saying:
> 
> “{Name generated from public key} has sent you a message, but it looks like the information they have are outdated, would you like to (re)establish a secure channel with them?”
> OK/Ignore ,
> 
> ignore will not prompt you anymore upon receiving messages from the same user, OK, will establish a secure channel with the user and (possibly) add it back to your contact list.
> 
> I would like to introduce the concept of “secure channels” to the user as it is something that we will need in some other scenario, as sometimes we might not be able to ensure PFS and a similar message could be displayed.

**Comment by lukaszfryc** [comment]
@PombeirP @cammellos is there anything we can do about this issue? It's really inconvenient to ask users again to add me as contact after I recovered my account.

**Comment by cammellos** [comment]
@lukaszfryc https://github.com/status-im/status-react/pull/6242 had a way to sync your contacts across your devices, unfortunately there were a few issues and I pull the plug on this one (code is in but not enabled), once group-chats & pairing (sending one-to-one messages) are tested ok & merged, I can re-enable, that should alleviate the pain, as long as you have at least one device with the contacts.

**Comment by lukaszfryc** [comment]
@cammellos cool. That should help. But, is there a plan to recover contacts (and other account data) in case I don't have any other device?

**Comment by cammellos** [comment]
That's a difficult choice to make, basically we'd need to allow the user to make a backup, technically it's simple, but we would need to have a discussion on the security implications.

I can say 100% that we don't want messages to be restored in different devices through a online-backup, as that would invalidate PFS (Signal as well does not allow you to do that). Contacts/chats etc we could consider a manual backup option I take, but probably a discuss post is the best place to figure out?

**Comment by lukaszfryc** [comment]
I see. Thanks for info. Let me create a discuss post with it.

**Comment by lukaszfryc** [comment]
> @lukaszfryc #6242 had a way to sync your contacts across your devices, unfortunately there were a few issues and I pull the plug on this one (code is in but not enabled), once group-chats & pairing (sending one-to-one messages) are tested ok & merged, I can re-enable, that should alleviate the pain, as long as you have at least one device with the contacts.

@cammellos Any update on that?
