### ISSUE TITLE
Add emojis to status-desktop

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5595]
### User Story

As a user, I want to have emojis in chat that I'm using

### Description

*Type*: Feature
*Summary*: add emojis to Status-desktop would be a great addition to current chat, because on desktop there is no emoji keyboard unlike in mobile.
How it looks in Slack (desktop client):
<img width="264" alt="sl" src="https://user-images.githubusercontent.com/4557972/44460459-cede4f80-a615-11e8-8cd8-a037eee1fb3b.png">

How it looks in Telegram (desktop client):
<img width="185" alt="tg" src="https://user-images.githubusercontent.com/4557972/44460463-d7368a80-a615-11e8-81b1-cbaf2982f091.png">

#### Expected behavior
Emojis are available on the right corner of input field;

#### Actual behavior
No emojis are available

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Navigate to any 1-1 or public chat

### Solution
*Summary*: 

- [ ] define list of emojis that should be available
- [ ] add design for emojis
- [ ] implement emojis in status-desktop app

### Additional Information
* Status version: nightly 22/08/18
* Operating System: Mac OSx

**Comment by vkjr** [comment]
@EugeOrtiz, do we have a design for popup with emojis?

**Comment by EugeOrtiz** [comment]
Nope, I'll work on that :)

**Comment by chadyj** [comment]
Do you know that on a Mac you can invoke the Emoji menu system wide with `^⌘space`, or by going to the Edit menu of apps?

But unfortunately the keyboard shortcut and the menu item are missing in Desktop.

<img width="275" alt="emoji" src="https://user-images.githubusercontent.com/116099/45353373-f1330f80-b5ba-11e8-9d9f-a7eca6a19750.png">

**Comment by vkjr** [comment]
Never knew this, thanks @chadyj!

**Comment by chadyj** [comment]
Quick fix is adding the `Edit` menu :)

**Comment by vkjr** [comment]
`react-native` doesn't have a concept of menu at all, since it is for mobile. So for desktop we need to add it. That shouldn't be a big task, but probably also not a quick fix :)

**Comment by EugeOrtiz** [comment]
This can be separated in 2: writing with emojis as mentioned above (on message area) and reactions (an emoji reaction to a sent message).

**Comment by chadyj** [comment]
We used to have an emoji picker in mobile. We can bring this back https://github.com/status-im/status-react/pull/558 to desktop.  iOS and Android have decent system emoji pickers so we don't need it on mobile.  @alwx interested in resurrecting this work?  Or maybe @rasom?

Also Status is using [Emojilib](https://github.com/muan/emojilib) so it already has support for typing emoji like `:heart:` and `:smile:`.  The full list is [here](https://github.com/muan/emojilib/blob/master/emojis.json)  but perhaps this needs to be updated as not all emoji are working.

**Comment by Swader** [comment]
A better question is why this was removed at all - all OSes have native emoji pickers. In windows it's WIN+period to summon it, in OS X as state above. Viber and Status are the only apps that block native input for no apparent reason. Right now, the native picker on Windows works but for some reason the emojis are black and white in Status.
