### ISSUE TITLE
Chat spec and documentation

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5598]
* The protocol messages (communication between two status peers) will be defined using `protobuf` so that people can re-use the schema if they wish to do so.

* The protocol interactions will be described in a document similar to https://tools.ietf.org/html/rfc6101#section-5.6.3 

* The public high level RPC api can be described again using protobuf including the endpoints https://developers.google.com/discovery/v1/reference/apis , so that you can generate clients programmaticaly from the protobuf files.

**Comment by pedropombeiro** [comment]
@chadyj @cammellos https://github.com/pseudomuto/protoc-gen-doc could be used to easily generate documentation from the .proto files in Markdown (or some other) format. An example of the output (of course, we'd need to make the existing comments in the .proto files more helpful):

![image](https://user-images.githubusercontent.com/138074/44710553-ab4f5500-aaac-11e8-82c7-023ce3e684da.png)

Here's a fictional [data model](https://github.com/pseudomuto/protoc-gen-doc/blob/master/examples/proto/Booking.proto) from their samples and the resulting [Markdown](https://github.com/pseudomuto/protoc-gen-doc/blob/master/examples/doc/example.md#Booking.proto).

<blockquote><img src="https://avatars2.githubusercontent.com/u/4748863?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pseudomuto/protoc-gen-doc">pseudomuto/protoc-gen-doc</a></strong></div><div>Documentation generator plugin for Google Protocol Buffers - pseudomuto/protoc-gen-doc</div></blockquote>

**Comment by chadyj** [comment]
Fantastic to see PFS [WIP](https://hackmd.io/I3jM-rbYRdS3Sqvwu_ATqg?both#23-Bundle-retrieval)!
