### ISSUE TITLE
Update Bounties Network URL

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5603]
### Description

*Type*: Feature

*Summary*: Change URL for Bounties Network DApp to `https://berlin.bounties.network`. 

#### Expected behavior
Bounties Network DApp launches `https://berlin.bounties.network`. 

#### Actual behavior
Bounties Network URL is `https://moksha.bounties.network'.

<blockquote><img src="https://bounties.network/images/bountiesexplorer.png" width="48" align="right"><div><strong><a href="https://beta.bounties.network/">Bounties Explorer</a></strong></div><div>Bounties on any task, paid in any token on Ethereum</div></blockquote>

**Comment by Serhy** [comment]
PR to update Bounty Network link is ready. The only issue is that `https://berlin.bounties.network` name is not resolved yet and I'm getting a `berlin.bounties.network’s server IP address could not be found. DNS_PROBE_FINISHED_NXDOMAIN.`
 response.
