### ISSUE TITLE
Password tooltip showed in account creation is cropped out

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5604]
### Description

*Type*: Bug

*Summary*: Password tooltip is cut off in the password confirmation screen:

<img src="https://user-images.githubusercontent.com/7532782/44469717-69478e80-a628-11e8-96e5-4459dd7b66dd.png" width="200">

#### Expected behavior
Tooltip is fully visible.

#### Actual behavior
Tooltip is below the logo area.

### Reproduction

- Provide different passwords while creating a new account

### Additional Information
* Status version: 0.9.25
* Operating System: Android, iOS
* Tested on Android

**Comment by wolfgangshilei** [comment]
Firstly, this issue can only be reproduced on the Android platform, and it seems to be linked with the following issue of react-native:
[https://github.com/facebook/react-native/issues/6802](https://github.com/facebook/react-native/issues/6802)

Besides the password confirmation screen shown above, I found other two screens that suffer from the same problem:

Sign-in:
![sign-in](https://user-images.githubusercontent.com/38782954/44538585-5621e500-a734-11e8-949a-b18d067c6e34.png)

Transaction Fee:
![transaction-fee](https://user-images.githubusercontent.com/38782954/44538599-62a63d80-a734-11e8-83e8-32519c22baeb.png)

One possible fix with small efforts is to add top-padding to the the tooltip's parent view.

- Without top-padding (today):
![with-border](https://user-images.githubusercontent.com/38782954/44538741-d8120e00-a734-11e8-82b0-92cff460759e.png)

- With top-padding (a possible fix):
![possible-fix](https://user-images.githubusercontent.com/38782954/44538755-e2340c80-a734-11e8-9099-25ee83e960e8.png)

I would like to contribute to this project, and hopefully I can start with this issue. Thanks.

**Comment by lukaszfryc** [comment]
Hi @wolfgangshilei! Thanks for your investigation. Feel free to contribute!
