### ISSUE TITLE
Continuous "Connecting to peers..." after app appears online after ~10 minutes of device being offline

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5620]
***Type***: Bug

***Summary***: When app is running but a device is offline for some time (2-3 minutes), - when network connection established app cannot connect to any of mailservers. 'Connecting to peers...' appears all the time on Home/Chat screens and it's also visible on 'Mailserver settings' list that app tries to connect to mailservers all the time. 
The same happens if app has stayed in the background (but device all the time online) for 8-10 minutes. 

Note: Restarting the app "fixes" this mailserver connectivity issue.

#### Expected behavior
Connection to mailservers established after app appears online after ~10 minutes of device being offline

#### Actual behavior
Can not connect to mailservers after app appears online after ~10 minutes of device being offline

### Reproduction

- Open Status and log in to account
- Enable Airplane mode and keep it for 10 minutes
- Disable Airplane mode
- Verify whether 'Connecting to peers...' label re-appears all the time during 1 minute
- Connect to any public chat having the messages last 24h and check whether message history 

### Additional Information
* Status version: Develop 0.9.26 (6506); node 19b53030
* Operating System: Android 7, Android 6, iOS 11.4.1

#### Logs
Logs from iPhoneX: on video 00:00 - 04:00 - Connecting to peers,  From 04:00 - end it's visible continuos attempt to connect to mailservers https://app.testfairy.com/projects/4803590-status/builds/8567976/sessions/4399274142/?accessToken=O30OAd/LOw7p-w5KUhxwPTGA0-E

**Comment by lukaszfryc** [comment]
I just had it on iPhone 8 on Ropsten. Here is the [geth.log](https://github.com/status-im/status-react/files/2317909/geth.log)

**Comment by pedropombeiro** [comment]
This issue should be fixed with https://github.com/status-im/status-react/pull/5664 (needs testing).

**Comment by annadanchenko** [comment]
fixed with https://github.com/status-im/status-react/pull/5664
