### ISSUE TITLE
Upgrade react-native to 0.56 or higher for status-react

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#5636]
Currently we cannot build `status-react` on Linux because it fails at:
```
./gradlew react-native-android:installArchives
```
with errors like:
```
> Task :react-native-android:androidJavadoc 
/home/jenkins/workspace/status-react/combined/mobile-android/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/yoga/YogaNode.java:11: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
```
and
```
error: package Build does not exist
error: package Build does not exist
error: package Build does not exist
error: package Build does not exist
```
Which stops us from building Android on Linux Jenkins slaves, which is a problem because it's easier for us to scale up Linux slaves rather than MacOS slaves.

I've figured out that if I upgrade `react-native` from our own fork https://github.com/status-im/react-native which is `0.55.4` to original that is `0.56.0` with:
```
npm install --save github:facebook/react-native#0.56-stable
```
Which seems to fix the issue with weird importing errors.
Although it does cause other erros when running:
```
./gradlew assembleRelease
```
But at least that gives more manageable errors like:
```
jest-haste-map: @providesModule naming collision:
  Duplicate module name: StatusIm
  Paths: /home/jenkins/workspace/status-react/combined/mobile-android/desktop_files/package.json collides with /home/jenkins/workspace/status-react/combined/mobile-android/mobile_files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
```

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native">status-im/react-native</a></strong></div><div>react-native - A framework for building native apps with React.</div></blockquote>

**Comment by dmitryn** [comment]
This is already happening in https://github.com/status-im/status-react/pull/5610

**Comment by jakubgs** [comment]
Oh, I had no idea, thanks for pointing this out! I'll close this then.
