### ISSUE TITLE
Info.plist file should contain a NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription key 

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5637]
Received this email from Apple after a recent app submission:

> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a **NSLocationAlwaysUsageDescription** and **NSLocationWhenInUseUsageDescription**  key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."

Doesn't look like a blocker but is something we should address eventually.

<blockquote><img src="/documentation/__assets/favicon.ico" width="48" align="right"><div><strong><a href="https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy">Protecting the User's Privacy | Apple Developer Documentation</a></strong></div></blockquote>

**Comment by MaBbKhawaja** [comment]
you just have to go to your info.plist file and add NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription in privacy column there as keys and write a string against them telling why your application is using these sensitive datas of user
