### ISSUE TITLE
Change react-native-i18n language files to js

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5649]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want react-native-i18n language files in js so that I can integrate with Lokalise

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

[Lokalise](https://lokalise.co) is a leading platform to manage translations for apps and websites with a git-based integrated and open workflow.  They support react-native-i18n out of the box, but only with js language files.  If we converted our [files from cljs to js](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs) we can easily integrate with the Lokalise service. [See these docs for more info](https://docs.lokalise.co/supported-file-formats/react-native-i18n-js).

This issue is a good contender as it unblocks other team members and workflows to ensure that Status is available in other languages.

#### Expected behavior
[en.cljs](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs) converted to en.js (and other language files)

**Comment by annadanchenko** [comment]
other language files to convert in addion to en.cljs: https://github.com/status-im/status-react/tree/develop/src/status_im/translations

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by annadanchenko** [comment]
note for testing: check after conversion that 
- special chars like é, ự etc are the same as before conversion, 
- same amount of strings exist as before the conversion
