### ISSUE TITLE
Embed solc / Ensure Solidity compiler availability

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#565]
Project Oaken's DApp fails on Contract Deployment on their DApp here:
http://50.112.52.169/pages/index.html

The method `createMeter` that fails can be found in http://50.112.52.169/ethjs/ethFunctions.js

They believe it is because of the account being locked, ideally we should intercept this like sendTransaction and make user aware.

**Comment by jarradh** [comment]
This is abit strange to me, as I was sure contract deployment was via sendTransaction

**Comment by jarradh** [comment]
Yep it is https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L202

**Comment by jarradh** [comment]
http://ethereum.stackexchange.com/questions/6870/create-a-new-contract-by-json-rpc-of-cpp-ethereum

**Comment by jarradh** [comment]
Since solc might be a challenge to embed and execute (will rely on @farazdagi advise on here)
an alternative would be to use the Emscripten compiled version of solc and execute in a JS environment 

https://www.npmjs.com/package/solc 
https://github.com/ethereum/solc-bin

**Comment by jarradh** [comment]
Som updates on this, the current static library cgo wrapper for solc is about 17mb, if we're supporting 3 architectures thats a ~50mb additional size, now we have our own web3 provider in webview, it makes alot more sense to use the npm emcscripten version of solc, as it is only 7mb and would work across all 3 architectures.

**Comment by rasom** [comment]
There is the next error when i'm trying to run `solc-bin` in `Otto`:
```
(anonymous): Line 2:1126536 Invalid regular expression: re2: Invalid (?=) <lookahead> (and 103 more errors)
```

**Comment by rasom** [comment]
That's the part of the code that causes error, as i undertnad
```js
var valid6regx=/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i;
```

**Comment by rasom** [comment]
`?!` (negative lookahead) also causes this error. So we need to rewrite this regex if we are going to run `solc-bin` in Otto, as golang doesn't support lookahead/lookbehind https://github.com/StefanSchroeder/Golang-Regex-Tutorial/issues/11

**Comment by jarradh** [comment]
New emscripten solc in `nightly.2017.1.13`+ 5x speedup

**Comment by jarradh** [comment]
We can possibly close this because  ethereum/EIPs/issues/209

**Comment by Souptacular** [comment]
Having solc as a command line option in geth (accessed through a web3 call) is very rarely used and I believe the geth team has deprecated it (see Jarrad's comment above). At Oaken we no longer need this feature. Because it was opened at our request feel free to close it. Thanks!

**Comment by jeluard** [comment]
`eth_compile` methods have been [deprecated](https://github.com/ethereum/EIPs/issues/209) and removed from `geth`.
