### ISSUE TITLE
Blank page when accessing .pdf files from Android app browser

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5650]
***Type***: Bug

***Summary***: When contacat opens `.pdf` files from Android browser view - a blank screen is shown, no content. It's ok on iOS app webview, though.
When trying to access PDF from Dapp (usually it's `T&Co`, `Terms of use`, `Legal` data) user stays on the same page from where `.pdf` link been tapped on. It's visible, though, that weblink is changed to the respective PDF link (see TF session 2 and Steps to Reproduce 2 below)

Note that the issue might be in the following project: https://github.com/status-im/react-native-webview-bridge

#### Expected behavior
PDF files can be viewed in Android app browser view.

#### Actual behavior
Blank page when accessing .pdf files from Android app browser
<img width="229" alt="screen shot 2018-08-27 at 14 09 01" src="https://user-images.githubusercontent.com/8749671/44656745-c8c7e480-aa02-11e8-8bcb-8296278077cd.png">

### Reproduction 1

- Open Status
- Navigate to `Open Dapp` -> paste `http://swap.tech/airswap-terms-of-use.pdf` in URL editbox and submit

### Reproduction 2

- Open Status
- Navigate to `Open Dapp` -> `Airswap`
- Navigate to list of tokens and scroll to the very bottom. Tap `Terms of Use` link

### Additional Information
* Status version: Develop `0.9.26 (6639); node 19b53030`, Release 0.9.25
* Operating System: Android 6.0+, 7.0, 8.0 

### Additional Information (update)
* Status version: Develop `0.9.29 (9811); node f3880f8f`, Release 0.9.28
* Operating System: Android 6.0+, 7.0, 8.0 

#### Logs
From 00:40 https://app.testfairy.com/projects/4803622-status/builds/8569216/sessions/4399549276/?accessToken=SNUFj4dPHflrU3382SXX0H5ejV4

Access PDF from Dapp: https://app.testfairy.com/projects/4803622-status/builds/8569241/sessions/4399550105/?accessToken=9-DQejLP9zrT8VV-ud06dKF5Yoo

**Comment by jeluard** [comment]
@mandrigin Does that ring a bell?

**Comment by jeluard** [comment]
@Serhy Can you still reproduce?

**Comment by Serhy** [comment]
Yes, Develop 0.9.29, Release 0.9.28 - reproducible there on Android 6, 7, 8 versions.

**Comment by flexsurfer** [comment]
PDF is not supported in webview on Android, so we need to use pdf viewer library (https://github.com/mozilla/pdf.js/ or  https://github.com/wonday/react-native-pdf) or open it in system browser

<blockquote><img src="https://avatars0.githubusercontent.com/u/131524?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/mozilla/pdf.js">mozilla/pdf.js</a></strong></div><div>PDF Reader in JavaScript. Contribute to mozilla/pdf.js development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/3401776?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/wonday/react-native-pdf">wonday/react-native-pdf</a></strong></div><div>a react native pdf view module. Contribute to wonday/react-native-pdf development by creating an account on GitHub.</div></blockquote>
