### ISSUE TITLE
Text in input field is not erased when switching to other chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5656]
### Description

*Type*: Bug
*Summary*: when message field is not empty text should be preserved for selected chat only, so if you are switching to other chat, field should become empty and if you come back again - text should be preserved.
Currently, if text is added in input field, then after switching to another chat - text was preserved. At attempt to send message all text is erased, message is not sent.

#### Expected behavior
the input field is empty

#### Actual behavior
text for previous chat is preserved; at attempt to send message text is erased.

### Reproduction

- Open Status Desktop
- Log in
- Join to any 2 chats (i.e. #status and #status-desktop)
- Start typing text in  #status (i.e., `1234`)
- Switch to other  #status-desktop

### Additional Information
* Status version: nightly 27/08/2018
* Operating System: Mac OSx
* Video: http://take.ms/PDj1U

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=ugVqpEq2OCBoSmLPm4x0ArIzJC6RZ4&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/ugVqpEq2OCBoSmLPm4x0ArIzJC6RZ4">File "screencast 2018-08-27 18-22-22.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by vitvly** [comment]
For now blocked by https://github.com/status-im/react-native-desktop/issues/332

**Comment by churik** [comment]
@rasom 
Issue is still reproducible after first logout and it disappears when you select chat again (nightly 05/10/2018).
So, updated steps:
1) Log in
2) Select any chat (i.e. `#a`)
3) Type message 
4) Switch to other chat (i.e. `#b`)

Input area in `#b`contains text from `#a`
If you switch back to `#a`, issue will disappear.
Video: http://take.ms/6lXSv

**Comment by rasom** [comment]
yep, it was reintroduced actually
