### ISSUE TITLE
Display the build URL link somewhere in the UI

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#5659]
As part of work to improve experience for testers I've added the Jenkins build URLs to Android and iOS metadata:
https://github.com/status-im/status-react/blob/develop/ci/ios.groovy#L12
https://github.com/status-im/status-react/blob/develop/ci/android.groovy#L18

If it's possible I'd like this info made available somewhere in the App UI in the development mode.

**Comment by chadyj** [comment]
`Profile > About` shows app and node version info

**Comment by jakubgs** [comment]
Yes, but test team asked me to add Build URL as well.

**Comment by jakubgs** [comment]
This is not stale, it would still be good to show this.

**Comment by jakubgs** [comment]
Eh, I don't care about this anymore.
