### ISSUE TITLE
Phone number registration adds UK country code before other country codes

### ISSUE THREAD

**Issue by richbodo** [status-im/status-react#566]
Steps to Reproduce:

    I installed the alpha, and when it got to the phone number setup, enter a phone number.
    My phone number was in the format 1 234 567 8901
    (Design Note: All 1s for format choices is a super hard thing to read)

Result:

    I never got an SMS.
    It did say "Thanks, we've sent you a text message..."
    So I assume the format was incorrect or the SMS doesn't actually go out.
    When I look at my profile, I initially saw no phone number.
    30 minutes later, on second look, I see a phone number of the form
    44 1 234 567 8901
    So it added a UK country code to my number, before the US code!

Environment:

    im.status.ethereum-49c604.apk
    I'm using a nexus 6 running Android 6.0.1 at security patch level: 5 Nov 2016
    And I'm using google project fi as my provider.

**Comment by carlbennetts** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/110
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/108
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/107
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/102
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/97
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/92
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/86

**Comment by jarradh** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/120

**Comment by Jas0n-F** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/183

**Comment by Jas0n-F** [comment]
I realise this is closed - but this user is still reporting not receiving the code. 

https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/231?status=New

**Comment by jarradh** [comment]
@Jas0n-F we haven't released the new version with the fixes, that's why almost all reported issues are duplicates.

**Comment by flexsurfer** [comment]
@cammellos why its reopened?

**Comment by cammellos** [comment]
@flexsurfer I think it's a bug with the zenhub autmation, it reopened it a few times already, didn't notice that it did this time, I need to figure out why is reopening this issue specifically (it has to do with the issue number 566)

**Comment by flexsurfer** [comment]
@cammellos is there a timer ?

**Comment by flexsurfer** [comment]
again?
