### ISSUE TITLE
SSL pinning for third party APIs

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5666]
### User Story

As a user, I want to have end-to-end security when sending & receiving data from Status, so that I'm protected from malicious behavior.

### Description

*Type*: Feature

*Summary*: White list SSL certificate keys that the Status client will accept when making requests to a third party API. The goal is to mitigate the risk of man-in-the-middle attacks.

#### Expected behavior
Status only accepts connection from servers that hold white listed certificate keys.

#### Actual behavior
No SSL check before making connections to third party APIs.

**Comment by oskarth** [comment]
@rachelhamlin Has this been addressed in https://github.com/status-im/status-react/issues/5583 or not?

Right now there's a lack of clear mapping to WoS item and milestone:

### 2. Weak certificate checks (SOLVED)

#### Principles violation
security

#### Details
Browser only validates whether SSL certificates are valid or not. Phishing sites can have valid certificates. By comparison, Google Safe Browsing checks suspicious terms from a site against Google servers.

Being tracked here: https://github.com/status-im/status-react/issues/5583

---

Could you please confirm and update https://hackmd.io/p/Bkm45vmqX#/1 as appropriate?

<blockquote><img src="https://avatars.githubusercontent.com/u/1552237?s=400" width="48" align="right"><div><img src="https://hackmd.io/favicon.png" height="14"> HackMD</div><div><strong><a href="https://hackmd.io/p/Bkm45vmqX#/1">HackMD - Collaborative markdown notes</a></strong></div><div>## Principles Seminar v0  **Session 11 - Liberty**  Oskar, 2018-10-18  **Copyright and related right</div></blockquote>

**Comment by rachelhamlin** [comment]
@oskarth no, #5583 was just for browser security; we block known phishing sites using MetaMask phishing detect. We will also add Google Safe Browsing to the browser. 

SSL pinning is separate and I will update the Hackmd, but it seems this is the wrong link?

**Comment by oskarth** [comment]
I am confused, do we have two issues on wall of shame but none of them actually corresponds to the wall of shame item?

**Comment by oskarth** [comment]
Sorry you are right, wrong link. https://notes.status.im/s/wall-of-shame-prague

<blockquote><div><strong><a href="https://notes.status.im/s/wall-of-shame-prague">Wall of shame, Prague edition - CodiMD</a></strong></div><div>  # Wall of shame, Prague edition  More like a book at this point. Alternative title: **Book of gaps</div></blockquote>

**Comment by rachelhamlin** [comment]
I just created a [new issue](https://github.com/status-im/status-react/issues/6398) for Google Safe Browsing and updated the `weak certificate check` item in Hackmd to include that + this issue.

SSL certificate pinning was not identified as a must-have in our WoS discussion, but rather good practice. Thus it's not directly tied to the `weak certificate check` WoS item, but it is related.

**Comment by oskarth** [comment]
Gotcha, thanks!

**Comment by rachelhamlin** [comment]
Sure thing!

**Comment by Swader** [comment]
Reopening.

**Comment by churik** [comment]
Not a priority anymore
