### ISSUE TITLE
New Contact UI is somewhat unclear

### ISSUE THREAD

**Issue by richbodo** [status-im/status-react#567]
Note:

   It's not obvious that you use !browse and the web2 URL of a testnet contract to hit a contract.  I assumed that you had to use the "contacts" function.

To Reproduce:

    Open the contact list.
    The word Dapps appears on the upper left above the console and wallet entries
    Click on the plus sign to add a new contact.  You are asked for a Public Key.
    Try entering valid addresses of contracts. (that's actually what I thought I was supposed to do)

Result:

    None of the valid ethereum addresses you enter cause the check-mark go active, so you can't add an address.  Later I did find a way to visit a Dapp, but there was some poking around and asking involved.  I'm actually still not sure if there is more than one way to get to a Dapp interface.
  
Expected Result:

    If this is where we add Dapp addresses, then we would expect to see some text that would indicate that.
    If this is not where we add contacts for Dapps or individuals by ethereum address, then some other indication should be made in the UI.

Environment:

    im.status.ethereum-49c604.apk
    I'm using a nexus 6 running Android 6.0.1 at security patch level: 5 Nov 2016
    And I'm using google project fi as my provider.

**Comment by rabbit** [comment]
I agree. The add on contacts should be more descriptive and include the ability to add contacts and apps. otherwise contact and app objects should generally be split into their own sections so the context remains clear.

**Comment by sla-shi** [comment]
Revisit this later and align to the roadmap.
