### ISSUE TITLE
Development mode is shown as enabled (actually it is disabled) if create new account after enabling development mode on previous one

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5673]
### Description

*Type*: Bug

*Summary*: if you enable development mode on account A, then creating new account - development mode is shown as enabled, but it is not (you cannot see network switching)
<img width="141" alt="dev" src="https://user-images.githubusercontent.com/4557972/44731013-ec665a00-aaea-11e8-8a05-df98ec8b0f13.png">

#### Expected behavior
development mode is not enabled

#### Actual behavior
development mode is shown as enabled;

### Reproduction

- Open Status
- Create account
- Turn on development mode in Profile > Advanced
- Log out
- Create another account
- Log in
- Open Profile > Advanced

### Additional Information
* Status version: nightly 28/08/18
* Operating System: IOS
* NOTE: issue disappear after app restart or toggling development mode

#### Logs
* TF session: https://app.testfairy.com/projects/4803590-status/builds/8571683/sessions/4399645386/?accessToken=E6kzsvN1XqJ40Slt94hIadgZkMU

**Comment by lukaszfryc** [comment]
Related issue https://github.com/status-im/status-react/issues/4779
