### ISSUE TITLE
Don't upload nightlies to Play/Testflight

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5682]
At some point we uploaded nightlies to Play/Testflight, but this wasn't used by anyone.

Now this feature runs all the time and is necessary.

We should only upload for releases.

The fastlane jobs for nightlies (or PR's or other) can be removed so we shouldn't see this anymore:

<img width="585" alt="screen shot 2018-08-29 at 8 01 54 am" src="https://user-images.githubusercontent.com/116099/44768575-0bec9980-ab62-11e8-8491-e22587dcbdb1.png">

**Comment by jakubgs** [comment]
Yeah, this is becuase `BUILD_TYPE` had at somepoint a `defaultValue` of `nightly`. The problem with that is it changes the definition of the Jenkins job and it's default value for the parameter. So when you remove `defaultValue` it does not change the default value of the job.
@mandrigin has already a PR that addresses this partially:
https://github.com/status-im/status-react/pull/5684
Once merged I will clear out the PR build history, and then merge all PR branches with develop to distribute the fix.

**Comment by chadyj** [comment]
Should be fixed.
