### ISSUE TITLE
Tap on close icon doesn't close "Add to contacts" message 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5695]
### Description

*Type*: Bug
*Summary*: when"Add to contacts" message appears in one chat in both devices - [Close] icon doesn't work; this only appears if you navigate to user profile and create chat via [Send transaction]. This option doesn't add user to contact automatically (unlike [Send message]). I'm suggesting to add user to contact list if using "Send transaction" (as it implemented for  "Send message") for consistency.

#### Expected behavior
message is closed

#### Actual behavior
message isn't closed; 
![gh](https://user-images.githubusercontent.com/4557972/44791042-6d842680-aba9-11e8-954c-af2f12f4a9c8.png)

### Reproduction

- Open Status
- Navigate to public chat
- Tap on user pic (who is not added to your contact list)
- Tap on [Send transaction]
- Tap on [Close] to close "Add to contacts"

### Additional Information
* Status version: nightly 29/08/2018
* Operating System: Android, iOS
* TF session: https://app.testfairy.com/projects/4803590-status/builds/8573399/sessions/4399754140/?accessToken=9SkMFRL4RFnCJbi0Eq-GIX0uVMg

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8573399/sessions/4399754140/?accessToken=9SkMFRL4RFnCJbi0Eq-GIX0uVMg">TestFairy: Status 0.9.26 (6797) @2018</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
It also does not work in a standard scenario when user receives a message from non-contact and sees "Add to contacts" bar.

**Comment by churik** [comment]
Can't reproduce on nightly 24/01/2019

**Comment by annadanchenko** [comment]
Can reproduce on nightly Mar 7 and on 0.10.1 release
both iOS and Android
