### ISSUE TITLE
null is not an object (evaluating 'cljs.core.nth.cljs$core$IFn$_invoke$arity$3(e,1,null).sendToBridge') after signing tx in CK and closing DApp

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5698]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sometimes popup with error `null is not an object (evaluating 'cljs.core.nth.cljs$core$IFn$_invoke$arity$3(e,1,null).sendToBridge')` is shown after closing Dapp CryptoKitties where transaction was recently signed (buy or gift a kitty)  
![img-2412](https://user-images.githubusercontent.com/6584810/44797442-80015e80-abaf-11e8-9633-0aa8080bcad9.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
no errors shown after Dapp is closed
#### Actual behavior
[comment]: # (Describe what actually happened.)
 error `null is not an object (evaluating 'cljs.core.nth.cljs$core$IFn$_invoke$arity$3(e,1,null).sendToBridge')` is shown after closing Dapp CryptoKitties where transaction was recently signed (buy or gift a kitty)  
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
from 11:37 in https://app.testfairy.com/projects/4803590-status/builds/8573437/sessions/4399764244/?accessToken=DgnGIUQh137TRdJlVYVlIoWqlfA
- Open Status and sign in
- Open Dapp CryptoKitties and purchase some kitty or gift existing one. Sign transaction 
- Close DApp
- Check if there is popup shown 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.26 and PR build with updated status go https://github.com/status-im/status-react/pull/5664
* Operating System: iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8573437/sessions/4399764244/?accessToken=DgnGIUQh137TRdJlVYVlIoWqlfA">TestFairy: Status 0.9.26 (6976) @2018</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
can reproduce in 0.9.17 release branch https://i.diawi.com/ACFG5v

<blockquote><div><strong><a href="https://i.diawi.com/ACFG5v">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@andytudhope has also reproduced this issue on 0.9.27

> Scanning a MakerDAO QR to claim DAI and then exiting the browser it redirected to resulted in this issue

**Comment by asemiankevich** [comment]
@flexsurfer 

Can be reproduced in the following case: 
- open status on ropsten
- open test dapp
- quickly tap back while test dapp is not fully loaded

![image](https://user-images.githubusercontent.com/28752642/45347387-a2827700-b5b4-11e8-9455-7ec7af07349c.png)
