### ISSUE TITLE
Can't receive an invite in Peepeth (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5706]
### Description

*Type*: Bug

*Summary*: I try to request an invite in Peepeth on android but i dont see any confirmation or link received on email when tapping Submit. 

#### Expected behavior
I see clear confirmation when i tap Sumbit.
I see link for confirmation sent on my email.

![image](https://user-images.githubusercontent.com/28752642/44845679-e3929700-ac56-11e8-8f9d-3656c34d0d10.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/44845590-a0d0bf00-ac56-11e8-9b18-743bdbc4e502.png)

### Reproduction

- Open Status
- Open peepeth dapp
- Tap request invite

#### NOTE
it works fine in TRUST
Android 8
Huawei P10 Lite

**Comment by flexsurfer** [comment]
`POST https://peepeth.com/invites 422 (Unprocessable Entity)`
