### ISSUE TITLE
Private group chats

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5744]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to create/join/manage group chats so that I can chat with a private group.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

This is a meta/placeholder issue for re-enabling group chats in Status.

There are many different features that group chat could have, but a good way to start is aim for minimum criteria. For example if it adds complexity to add/remove users, then lets not offer that in v1. 

@hesterbruikman has put together a doc with some use cases https://drive.google.com/open?id=1x6MLossXOhhz6Mu7O70hxGQtP2ynWq_vVxHc-4iZpUc

**Comment by chadyj** [comment]
@errorists @denis-sharypin @andmironov @EugeOrtiz Now that this is in the app can we clean up the UI for mobile and desktop?  I think I've seen designs around?

**Comment by errorists** [comment]
I'm working on it atm with some great feedback coming in from @lukaszfryc , here are the designs to follow progress https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=227%3A320

<blockquote><img src="/file/aS1ct66VQ6V0cio7vSqS8UoG/thumbnail?ver=PgMfso6loyuj9vonj5lj6T" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by chadyj** [comment]
Private group chats are in nightlies and are undergoing testing. Closing this issue and we can create specific new issues to release.
