### ISSUE TITLE
Recovering the same account with a different password is stuck

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#5745]
### Description

*Type*: Bug

*Summary*: When I recover an account that already exists in the app but I use a different password, I am stuck on the recover screen.

#### Expected behavior
I should get a notification that such an account already exists and the password does not match.

If I forgot the password, what should I do? Can I delete the previous account and recover it with a different password?

#### Actual behavior
I am stuck on the recover screen without any message and I need to kill the app (remove it from the background) to try to recover a different account or recover it with a correct password.

### Reproduction

- Open Status,
- If you don't have any accounts, create one,
- Logout from the current account and go to the recover screen,
- Recover the existing account but use a different password this time.

### Additional Information
* Status version: 0.9.27, 0.9.28 nightly
* Operating System: Android | iOS

**Comment by chadyj** [comment]
From Anna:

> this issue is very important to be fixed for the next release (0.9.28) as such steps will be used to recover same account with different password because of https://github.com/status-im/status-go/pull/1139 and https://github.com/status-im/status-react/pull/5737
