### ISSUE TITLE
Transaction request with a sum equal to zero or several zeros could be sent.

### ISSUE THREAD

**Issue by jorunnaparva** [status-im/status-react#5756]
### Description

*Type*: Bug

*Summary*: When I request 0 transaction error message doesn’t appear. 

#### Expected behavior
Warning of insufficient amount for transaction.

#### Actual behavior
Transaction request is sent.

### Reproduction
- Open Status
- Login
- Open a chat
- Send `/request ETH 0` or `/request ETH 0000.00000`

### Additional Information
* Status version: Status version 0.9.28
* Operating System: Android
![3](https://user-images.githubusercontent.com/42981338/45060486-50b38b80-b0a0-11e8-8439-197e63f13b50.png)

**Comment by annadanchenko** [comment]
it's expected, 0 ETH can be sent and can be requested
