### ISSUE TITLE
Second transaction fails when submitting bounty in berlin.bounties.network Dapp

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5759]
***Type***: Bug

***Summary***: Attempt to create bounty in berlin.bounties.network Dapp ends up with failed transaction (on the contract level) and continuous 'Confirming your transaction'. 

#### Expected behavior
I can successfully create a bounty in berlin.bounties.network Dapp

#### Actual behavior
Second transaction fails when submitting bounty in berlin.bounties.network Dapp

### Reproduction

- Open Status with funds on Mainnet
- Navigate to `Open Dapp` -> `Bounties Network` -> `Open`
- Sign In and sign a message in Status
- Tap `[+]` at top right to navigate to 'Create bounty' page
- Fill in valid data (for the Payout amount I used `0.01` and `Deposit amount (ETH or whole tokens)` = `0.01`
- Tap 'Create'
- Sign first transaction with default Gas limit and Price
- Sign second transaction with default fee values too

### Additional Information
* Status version: Release 0.9.27
* Operating System: Android and iOS

Logs: As a part of log here is one of my transactions that failed (Bounty attemp to create from Android device)https://etherscan.io/tx/0xfa87ee17f7974d36ac7feeab075f6b337e73e02f2e75be4c2964ed5b0358ab47
Another transaction example for bounty posted from iOS https://etherscan.io/tx/0x126d7478693257d57a8f56aee25c52dad320d3d61a4145fe541575dec2c2f548

**Comment by jeluard** [comment]
@Serhy Is that still relevant?

**Comment by Serhy** [comment]
Not relevant anymore. Also, additionally I've confirmed bounty creation in Bounty Network (explorer.bounties.network) with the latest nightly and it's all fine there.

Closing this issue.
