### ISSUE TITLE
"Save password until logout" overlaps "Other accounts" button when keyboard is opened

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5772]
### Description

*Type*: Bug

*Summary*:

The following screenshot was sent on Instabug. It was taken on iPhone 8, iOS 11.4.1, Status 0.9.27:

<img src="https://user-images.githubusercontent.com/7532782/45153725-4d6dec00-b1d5-11e8-8cce-a993df1001eb.png" width="200">

### Reproduction

I could not reproduce it on iPhone 8.

### Additional Information
* Status version:
* Operating System: Android, iOS

**Comment by churik** [comment]
Can be reproduced on Android 8 (device LG V20) on nightly 19/02/2019
![2019-02-19 17 30 15](https://user-images.githubusercontent.com/4557972/53030901-0bc3bb80-346c-11e9-9b41-6e6cb4dfc510.jpg)
