### ISSUE TITLE
Webview accept self-signed certificate

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#579]
When @farazdagi  `go-ethereum` modifications to support TLS become available the webviews will still block requests due to not allowing self-signed certificates.

In the least, we should make modifications to webview to allow our certificate.

**Comment by farazdagi** [comment]
- we can also use our own certificate and serve local node from, say, https://geth.status.im:8545 (where geth.status.im will resolve to 127.0.0.1 i.e. localhost, per our DNS settings).

- our certificate (for status.im) should be wild-card or we need to have another certificate issued for geth.status.im (or whatever). The thing is, that certificate will not be self-signed anymore, that URL will just resolve to localhost (we just need to update domain's DNS records).

**Comment by jarradh** [comment]
this concentrates power on our domain though, meaning it would give us the ability to switch it out and control json-rpc servers. this is bad.

**Comment by farazdagi** [comment]
well, then we certainly need to make sure that self-signed certificates are acceptable by webview.

**Comment by rasom** [comment]
As I understand we are going to allow self-signed certificate only for `https://localhost:8545`, correct?

**Comment by farazdagi** [comment]
Yep (although RPC port and hostname are configurable, we using default ones - and once TLS is released, the only thing that will be changed is that `localhost:8545` will encrypt its communication, and expect client to communicate using TLS).

I will also expose ability to provide certificate and private key files, therefore, if you can make sure that WebView works with a given certificate/key, then you start Geth node with those certificate/key - and we should be ok.
