### ISSUE TITLE
Tild character in wallet total amount "~15 USD" looks strange

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5798]
### Description

*Type*: Improvement

*Summary*: I have had a brief discussion with Nabil about the tild in wallet total amount. We both think this character looks strange there. Maybe we should get rid of it or have a different indicator of the average fiat amount?

<img src="https://user-images.githubusercontent.com/7532782/45300552-f6d31b80-b50e-11e8-858f-9a8c7cae80cf.png" width="200">

### Additional Information
* Status version: 0.9.27
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
I'd really want to get an opinion of someone from the design team. @errorists or @denis-sharypin? 

Btw, feel free to close this ticket if you think that's this character is clear to users and it looks good.

**Comment by denis-sharypin** [comment]
I think we def don't need a `tild` sign when the amount is zero. But we should keep it in different cases

**Comment by errorists** [comment]
I'd suggest to visually treat the tilde the same way we do with currency, so a lowered opacity / greyed out and stuff.

**Comment by lukaszfryc** [comment]
@denis-sharypin I agree about 0 case.

@errorists should we implement it?

**Comment by errorists** [comment]
@lukaszfryc It's up to Denis to decide, it's just a suggestion, one designer to another

**Comment by denis-sharypin** [comment]
@errorists make sense, thanks! @lukaszfryc could you create a task from this, please?

**Comment by lukaszfryc** [comment]
@denis-sharypin I'd like to avoid creating new tasks. Can't we just link the design here since we already have the full context?

**Comment by denis-sharypin** [comment]
Sure
<img width="864" alt="screenshot 2018-09-12 12 47 47" src="https://user-images.githubusercontent.com/6559881/45420313-20648200-b68a-11e8-8758-b296d54a098d.png">
