### ISSUE TITLE
Default DApp data structure

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#580]
During alpha and building out developer tooling we should allow DApp developers to easily submit their DApps as a PR with a name, URL, and icon, which would create a pseudo contact that opens up the !browse command - similar to Wallet, there is no need for any chat integration.

the dapps would appear in dapps group of contacts screen

ideally this just some list in a file with an icon going into resources dir.

Edit: Actually can we generalise this as well to allow adding contacts to groups, I would like to add "Jarrad" and my Status public key to People group.

**Comment by alwx** [comment]
We can also think about providing translations for DApp titles while working on this task.
https://github.com/status-im/status-react/issues/334
