### ISSUE TITLE
Unexpected spacing in Wallet

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#581]
It happens only when the external keyboard is connected, so this bug is probably not the most important.

STR:
1. Open wallet
2. Tap on "Send ETH" or "Received ETH" field
<img width="487" alt="screen shot 2016-12-24 at 12 06 50" src="https://cloud.githubusercontent.com/assets/911127/21466222/96b58180-c9d2-11e6-93f0-bffc5ac8bfb2.png">

**Comment by rasom** [comment]
I will check on the real device, if it works fine there no need to work on this.

**Comment by alwx** [comment]
I've checked it on my device — it doesn't work with an external keyboard connected (I've used the Bluetooth keyboard). But I don't think that there are people who seriously use keyboard with iPhone, so maybe we should focus on something more important now.

**Comment by jarradh** [comment]
agreed, lets keep ticket open for later

**Comment by yenda** [comment]
Outdated by new wallet
