### ISSUE TITLE
Implement auto-focus on input fields 

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5811]
### User Story
As a user, I want to have autofocus on some input fields, so I don't waste time clicking on them in order to write something.

### Description
*Type*: Bug

*Summary*: Let's implement auto-focus :)

#### Expected behavior
When accessing a screen or component in which the main action is to write something, let's implement auto-focus on the input field, with the cursor blinking and ready to write something. 

#### Actual behavior
E.g. When accessing a chat, the cursor is not on the message area. So, the user needs to spend extra energy clicking on the input field to start writing.

<img width="1029" alt="captura de pantalla 2018-09-12 a la s 1 55 13 p m" src="https://user-images.githubusercontent.com/37297779/45423454-af29cc80-b693-11e8-881d-559a4b467cbf.png">

### Solution
Auto-focus to be implemented in the following cases:
- When opening a chat > focus on "Type a message" input field
- When signing in > focus on password
- When creating a new account > focus on password (step1), then on confirm (step2) and then on name (step3).
- When recovering an account > focus on Recovery phrase, and then -on tab- focus on password.

### Additional
For a "happy form-filling experience", see also #4728 and #5548

**Comment by churik** [comment]
blocked by RN-issue  status-im/react-native-desktop#338

**Comment by churik** [comment]
@vkjr I can retest it?

**Comment by vkjr** [comment]
@churik, I checked, it should be fixed on rnd side, but doesn't work yet in status-react. So needs additional check and implementation.

**Comment by churik** [comment]
@vkjr from clojure side, yes?

**Comment by vkjr** [comment]
@churik, yes

**Comment by Swader** [comment]
Still a thing
