### ISSUE TITLE
Allow "Check for updates" within Status Desktop

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5812]
### User Story
As a user, I want to update the desktop app using a "Check for updates" option on the [MacOS app menu](https://github.com/status-im/status-react/issues/5547), so I can update my app easily. 

### Description
*Type*: Feature

*Summary*: 
Enable a "Check for updates" option in MacOS menu bar. Allow the update and automatic installation of new version.

#### Expected behavior / Solution
The user flow would be:
- The user has Status desktop open
- She selects the new option "Check for updates" on the menu bar #5547 
- A new window shows the new update notes. E.g.
<img width="639" alt="captura de pantalla 2018-09-12 a la s 2 11 18 p m" src="https://user-images.githubusercontent.com/37297779/45424109-c4075f80-b695-11e8-920b-652240ef09c8.png">
- She selects "Install update"
- Update gets extracted (maybe we don't need this step?). Eg.
<img width="419" alt="captura de pantalla 2018-09-12 a la s 2 12 09 p m" src="https://user-images.githubusercontent.com/37297779/45424157-eb5e2c80-b695-11e8-8316-c1f45597ace6.png">
- The user is asked to Install and Relaunch the app
<img width="442" alt="captura de pantalla 2018-09-12 a la s 2 12 13 p m" src="https://user-images.githubusercontent.com/37297779/45424175-f1540d80-b695-11e8-8cd8-2003e6376f49.png">
- After doing so, the new version of the app opens again, already logged in and in the latest chat/section/position of the app.

#### Actual behavior
There is a random button on the profile screen to upgrade:

<img width="342" alt="captura de pantalla 2018-10-24 a la s 1 00 32 p m" src="https://user-images.githubusercontent.com/37297779/47426283-12c41100-d78d-11e8-9f3d-604dd0677fc1.png">

This presents the following problems:
- Compites on hierarchy with "Share contact code"
- Doesn't leave space for more options under profile. If more options are added, it will get lost.
- Not an standard place to check for updates among MacOS apps.

### Additional Information
TBD how to do this on Linux and Windows

<blockquote><div><strong><a href="https://status-im.github.io/nightly/">Status.im Nightly Builds</a></strong></div></blockquote>

**Comment by Swader** [comment]
This is sorely needed
