### ISSUE TITLE
Some strings are hardcoded and not being translated

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5829]
### Description

*Type*: Bug

*Summary*: 

Following strings can't be found in Lokalise. Probably they are hardcoded: 

- [Send a payment](https://github.com/status-im/status-react/blob/988a1ca2e2efcb6164746a7b3ff57fed54776115/src/status_im/chat/commands/impl/transactions.cljs#L438)
- Receive a payment
- Currency
- Amount
- Exchanges, Marketplace, Fun & Games, Social Networks, Utilities, Media (in dapp list categories)
- Please allow Status to use your phone camera
- Photos access is required to give you ability to choose custom profile pictures
- [Error](https://github.com/status-im/status-react/blob/8dc9af891745a810226b1eeb1c02b3750a4ad88b/src/status_im/ui/screens/events.cljs#L85)
- [Dapp descriptions](https://github.com/status-im/status-react/blob/888bd5c2d6b7750f4ef0ad8da05342622d9a5971/src/status_im/ui/screens/browser/default_dapps.cljs)

#### Expected behavior
All of the strings are in Lokalise and can be translated.

#### Actual behavior
Those strings can't be translated because they are hardcoded.

### Additional Information
* Status version: 0.9.27
* Operating System: Android, iOS

**Comment by chadyj** [comment]
> Dapp descriptions

@rachelhamlin WDYT?

**Comment by rachelhamlin** [comment]
@jeluard better ideas for how to handle this?

**Comment by rasom** [comment]
@lukaszfryc can't find "Receive a payment" anywhere in project

**Comment by janherich** [comment]
I will fix command related translations, it's true they are hardcoded for now.
