### ISSUE TITLE
Wrong logo on desktop welcome screen

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5839]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to use the right logo to show a good brand and image.

### Description

This is a very small thing, but with out first release coming up we should put our best foot forward. This is the first screen everyone sees and our logo is wrong! Hopefully a quick fix that will make desktop feel less broken, which will be a little UX win :)

<img width="1024" alt="screen shot 2018-09-14 at 7 41 13 am" src="https://user-images.githubusercontent.com/116099/45532007-8b30cd00-b7f2-11e8-9a21-3edb3d1bda25.png">

**Comment by churik** [comment]
related to #4418

**Comment by EugeOrtiz** [comment]
Asset here > https://drive.google.com/open?id=1P27UlBmROk9UQ-KGDw3Zpfq9WOGwkIjZ

<blockquote><div><strong><a href="https://drive.google.com/open?id=1P27UlBmROk9UQ-KGDw3Zpfq9WOGwkIjZ">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>

**Comment by EugeOrtiz** [comment]
For some reason, that logo is displayed in all the screens of the "create account" flow (pass, re-pass, name). So if it gets fixed, it should cover all these screens too.

**Comment by chadyj** [comment]
Cheers @dmitryn you have been a desktop star!
