### ISSUE TITLE
Desktop security and privacy review

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5845]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a desktop user, I want to know that the app's security and privacy has been reviewed so that I can be safe.

### Description

Placeholder issue: Let's do a security and privacy review ahead of our 0.10.0 release.

**Comment by chadyj** [comment]
@corpetty Can you help with this?

**Comment by yenda** [comment]
`Debug: RNSecureRandom::generateSecureRandomAsBase64 result: ...` shouldn't be logged or at least not the resulting key

**Comment by corpetty** [comment]
For some reason I was not pinged appropriate for this.  

Yes I can help with this.  I would suggest we not go full on 3rd party audit yet, and review internally as we get to a point where we feel it warrants the 3rd party.  This way we have documented tests and results, as well as a proper scope for them to review it.  

I'll start working on this asap.

**Comment by chadyj** [comment]
> Debug: RNSecureRandom::generateSecureRandomAsBase64 result: ... shouldn't be logged or at least not the resulting key

Fixed!  Thanks @yenda for spotting

@corpetty Happy to have you helping out. It would be also useful to have a "framework" (or process or checklist) for the desktop team to look over and consider. Hopefully we might have accrued some useful pointers from mobile?

**Comment by chadyj** [comment]
@corpetty @siphiuel @vkjr @MaxRis @churik The first desktop release is imminent.  

@corpetty Can you please help us get this release out and ensure security and privacy are safeguarded.

**Comment by corpetty** [comment]
> It would be also useful to have a "framework" (or process or checklist) 

I'm working on building/finding something like this for desktop.  Because a bunch of the code is overlapped with mobile, then the associated checklists will overlap.  

> Can you please help us get this release out and ensure security and privacy are safeguarded.

Yes.  It starts with the disclaimer, then an internal audit of dependencies (and what information they gather).  Let's have a chat about this this week. Who else should be included in this chat so we can make a solid action plan to get it done?

**Comment by chadyj** [comment]
FYI There is progress to bring Wallet to desktop https://github.com/status-im/status-react/pull/6312

**Comment by chadyj** [comment]
> Who else should be included in this chat so we can make a solid action plan to get it done?

Would you like to join the desktop sync on Friday to discuss?

**Comment by corpetty** [comment]
yes, please send invite.

**Comment by chadyj** [comment]
@corpetty Desktop team is aiming to ship stable 0.9.0 release Dec 14.

Can you please help facilitate the privacy and security review?

Here is a quick update since we spoke last:
- Security warning added to alpha https://github.com/status-im/status-react/pull/6617
- Logging will be disabled by default in the release https://github.com/status-im/status-react/issues/6569
- Wallet is WIP but it won't be part of the alpha release.

More info on the release can be found here https://github.com/status-im/status-react/issues/6926

**Comment by chadyj** [comment]
@corpetty We are about one week away from cutting our release for testing.  It would be great if you could add your security and privacy discussion points here so the team can discuss and finalize.

**Comment by corpetty** [comment]
All,  I have thought up a list of security related questions for the release.  These are thought up from scratch and are about general application security as applied to the desktop app. 

They are also somewhat general in nature, and are limited as we are looking at an alpha release and are not requiring the same things as a final release.  Please use these to guide your thought process of your domain knowledge of the app.

I also highly encourage discussion of these points so we can hone them for future use.  So please suggest add/remove/edit of them.

https://notes.status.im/zn74OjGLQx2V5ctqSTatgA

<blockquote><div><strong><a href="https://notes.status.im/zn74OjGLQx2V5ctqSTatgA">Desktop Release Security Questions - CodiMD</a></strong></div></blockquote>

**Comment by oskarth** [comment]
@corpetty Can we define a minimal critical path for this? It isn't clear to me what the acceptance criteria is here considering linked TODOs, especially if the target is a release this week.

**Comment by 0xc1c4da** [comment]
➤ Corey Petty commented:

Is this still needed.  I'm not sure of the current status of this thread.

**Comment by corpetty** [comment]
@jarradh, Feel like most of those things aren't watched anymore due to mobile-ui update for desktop.  Am I wrong there?

**Comment by oskarth** [comment]
The backend key store etc is likely different. I.e. if I get malware, can it steal my keys? These types of threat models are slightly different from Android/iPhone AFAIK. Best to check with Core
