### ISSUE TITLE
Log Level Setting on Desktop

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#5848]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a dev and tester, I want to set log level so that I can debug.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Mobile has a feature that allows the setting of log level type. Let's bring this to desktop to help with debugging

![img_cbdf6ff7cd9e-1](https://user-images.githubusercontent.com/116099/45551678-f9938080-b82e-11e8-8be7-ff267ae2f950.jpeg)

#### Expected behavior
On desktop, Profile > Log Level

**Comment by EugeOrtiz** [comment]
@chadyj is this under "Advanced" on mobile? I cannot check latest version

**Comment by chadyj** [comment]
Yep. Screenshot attached.

<img width="284" alt="screen shot 2018-09-17 at 4 09 29 pm" src="https://user-images.githubusercontent.com/116099/45628317-1e3c6200-ba94-11e8-8dbc-9344f3276d81.png">

**Comment by chadyj** [comment]
Removing this from the launch milestone since logs will be disabled in https://github.com/status-im/status-react/issues/6569

**Comment by oskarth** [comment]
@siphiuel Why are we working on this if https://github.com/status-im/status-react/issues/6569#issuecomment-444916015 was the decision for the release?

**Comment by vitvly** [comment]
@oskarth After the security meeting with Corey (log here: https://notes.status.im/zn74OjGLQx2V5ctqSTatgA, not everything in TODO is a release requirement though) it was decided that it is very much desirable to have the option to turn the logs on.
