### ISSUE TITLE
Setup infrastructure for running automated tests against desktop app

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#5856]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- ...
- Step 3, etc.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

**Comment by churik** [comment]
Not a priority anymore
