### ISSUE TITLE
Add sanity test suite for desktop app

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#5858]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: We need to define a sanity suite of tests to run against the desktop app

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [x] Test suite is created in TestRail
- [ ] All tests from the suite are covered by e2e test

**Comment by churik** [comment]
Link to test suite: 
https://ethstatus.testrail.net/index.php?/suites/view/49&group_by=cases:section_id&group_order=asc&group_id=756

All tests with `Critical` priority are marked as `To be automated`

**Comment by churik** [comment]
Not a priority anymore
