### ISSUE TITLE
Pressing back button while creating new account leads to blank screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5877]
### Description

*Type*: Bug

*Summary*: Blank screen is shown when back button is pressed in the create account screen. The issue was introduced by react-navigation PR https://github.com/status-im/status-react/pull/5606. App works fine when killed and opened again.

<img src="https://user-images.githubusercontent.com/7532782/45625209-9d2d9c80-ba8c-11e8-9f1d-8729334a0dd1.png" width="200">

#### Expected behavior
Pressing back button (arrow) in while creating new account returns user back to the first screen.

#### Actual behavior
Pressing back button (arrow) in while creating new account shows blank screen. User has to kill the app and open it again.

### Reproduction

- Install and open the app
- Click create new account
- Click back button (top left corner)

### Additional Information
* Status version: introduced by https://github.com/status-im/status-react/pull/5606 
* Operating System: macOS

**Comment by rasom** [comment]
I can't reproduce this

**Comment by lukaszfryc** [comment]
It was fixed recently by Eric.
