### ISSUE TITLE
Graphics for README.md

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#588]
We need a banner image for Status that shows the name, logo and what Status looks like (if possible)

Also we could have profile pictures of the core contributors further down the page.

**Comment by andmironov** [comment]
Can we add this one for now and then think more about «what Status looks like» and «profile pictures of the core contributors».

![github](https://cloud.githubusercontent.com/assets/3115606/21482367/2846a8ba-cb84-11e6-8c00-1e019acfc924.png)


Also, Github has a mobile version, so it would not scale well if it's a 100% width image, what do you think if we just add the logo and description?

![github2](https://cloud.githubusercontent.com/assets/3115606/21482370/2be3474e-cb84-11e6-9ef8-6582fbd3c246.png)

**Comment by jarradh** [comment]
My first opinion is the logo and text is a little bland and if I were to browse to the readme, it wouldn't really captivate me or quickly show me what Status is.

The 100% width is a good point, I do think it's more likely to be viewed on a desktop 90% of the time, as Github kind of sucks on mobile and it's really hard to code on mobile.

Happy for us to think about this more if you like

**Comment by andmironov** [comment]
> The 100% width is a good point, I do think it's more likely to be viewed on a desktop 90% of the time, as Github kind of sucks on mobile and it's really hard to code on mobile.

Ok, sounds reasonable, here's the image in @2x and @1x
[statusBanner.zip](https://github.com/status-im/status-react/files/672996/statusBanner.zip)

**Comment by jarradh** [comment]
Added, https://github.com/status-im/status-react, 
yeah it could definitely use some work. Feel free to update this without my intervention

**Comment by andmironov** [comment]
thanks, okay!
