### ISSUE TITLE
Apply intended design to "Advanced Settings" options

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5880]
### Description
*Type*: Bug

*Summary*: An initial implementation of "Advanced Settings" (AS) was done so now only "Mailserver" options are displayed on the right panel. Now that we need to add more items under AS, we need to apply a more "condensed" design.

#### Expected behavior
To be able to see all "Mailserver" options under a dropdown, so we can show other options like #5848 also under AS.

#### Actual behavior
Current implementation:
<img width="1023" alt="captura de pantalla 2018-09-17 a la s 5 47 28 p m" src="https://user-images.githubusercontent.com/37297779/45634299-4b900c80-baa2-11e8-8289-8805cf2dd0b9.png">

Original design:
<img width="736" alt="captura de pantalla 2018-09-17 a la s 5 49 56 p m" src="https://user-images.githubusercontent.com/37297779/45634259-31562e80-baa2-11e8-862b-7f66d6536121.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to "Profile"
- Go to "Advanced Options"

### Solution
- [ ] Implement mailserver options under a dropdown. See dropdown behavior design here >> zpl.io/a74lJJE (Zeplin)

**Comment by chadyj** [comment]
Just curious... why have a drop down vs the mobile display? 

The mockup is also missing the ability to add custom mail servers. 

Will this system work for other type of settings, such as bootnodes? How about granular notification settings?

**Comment by chadyj** [comment]
@EugeOrtiz It is time we fix advanced settings and the profile tab.

So far we have:
- Notifications
- Advanced settings
  - Peer connection info
  - Mail server
  - Devices
- About/version

Missing: The mail server screen needs the same UI as mobile to add new mail servers

Very soon we will also have:
- Need Help
- Currency
- About
- Advanced
  - Network
  - Log level
  - Fleet
  - Bootnodes
    - Add boonode
  - Dev mode

With all these options should we just adopt something like mobile has?

**Comment by EugeOrtiz** [comment]
Here are the designs for the "new" profile ([Figma](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=751%3A21)):

![new profile - first time](https://user-images.githubusercontent.com/37297779/49654970-0b448880-fa18-11e8-810e-b3bc9531b9f0.png)

I adjusted some things to adapt them to desktop design. **Let's review it before merge**

**Comment by churik** [comment]
Can be closed because of #7551
