### ISSUE TITLE
Password pop-up 'Sign message' wallet screen overlaps Cancel+Sign buttons on iPhoneX

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5885]
***Type***: Bug

***Summary***: When `Sign message` screen is opened from Dapp - the password pop-up which appears overlaps `Cancel ... Sign` buttons on iPhoneX.
 
#### Expected behavior
<img width="371" alt="screen shot 2018-09-18 at 14 32 56" src="https://user-images.githubusercontent.com/8749671/45684699-c400d700-bb4f-11e8-8aa6-6f36b420fffb.png">

#### Actual behavior
<img width="308" alt="screen shot 2018-09-18 at 14 32 40" src="https://user-images.githubusercontent.com/8749671/45684705-c95e2180-bb4f-11e8-8503-854cb2242dcf.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and log in to account
- Navigate to `Simple Test Dapp` -> `Transactions`
- Tap `Sign message` button

### Additional Information
* Status version: Develop
* Operating System:  iOS (iPhoneX)

#### Logs
https://app.testfairy.com/projects/4803590-status/builds/8596607/sessions/4401753082/?accessToken=f/U-1B0iauIESYORfY9NTzbfmcs

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8596607/sessions/4401753082/?accessToken=f/U-1B0iauIESYORfY9NTzbfmcs">TestFairy: Status 0.9.28 (8472) @2018</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
Looks fine on Galaxy S8 (Android 8.0) and iPhone 8 (iOS 12)
