### ISSUE TITLE
Account recover/login takes 3 times more in 0.9.28 mobile app than 0.9.27

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5889]
***Summary***: When recovering or login into account in 0.9.28 (develop now) there is a **triple** time delay more than in 0.9.27 Release version between user tap on `Sign In` button and when Home screen appears. 
In my case on Android 7 (Samsung J7 real device) when I:
**recover** an account on 0.9.27 Release it **takes ~5 seconds** for me to see Home screen after SignIn button tapped, while the very same steps and account on 0.9.28 develop has ~12-15 seconds delay. 

In some cases it was up to 30 seconds: see TF session https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401756382/?accessToken=azLjgutis8nkYp2dExEhiJzhZOQ (at 00:20 `Sign In` button tapped)

#### Expected behavior
No difference between app versions in order the time that takes for contact to recover/login.
 
#### Actual behavior
Account recover/login takes 3 times more in 0.9.28 mobile app than 0.9.27

### Reproduction

- Install fresh 0.9.28 version
- Paste passphrase (e.g. `radar blur cabbage chef fix engine embark joy scheme fiction master release`) and enter valid password
- Tap `Sign In` button and note the time it takes for you to appear on Home screen
- Relogin to the same account and, again, note the time it takes for you to appear on Home screen

- _Optional:_ Repeat all steps above on 0.9.27 release version to see a difference

### Additional Information
* Status version: Develop `0.9.28 (8468); node 0.14.1`
* Operating System: Android and iOS

#### Logs

https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401756382/?accessToken=azLjgutis8nkYp2dExEhiJzhZOQ

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401756382/?accessToken=azLjgutis8nkYp2dExEhiJzhZOQ">TestFairy: Status 0.9.28 (8468) @2018</a></strong></div></blockquote>

**Comment by yenda** [comment]
Looks like the node is taking 23 sec to start

**Comment by mandrigin** [comment]
There is some performance regression between status-go 0.13.1 and 0.14.1

login times on Galaxy S6 (time between `startNode()` called and `node.ready` is received)

version |  | | | |
-----|-----|------|------|------
| 0.14.1 | 2,1  | 3,3 | 3,6 | 4,4 |
| 0.13.1 | 0,74  | 0,82 | 0,7 | 0,77 |
