### ISSUE TITLE
Emojis are displayed as black squares in Russian, Arabic or Korean messages

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5892]
### Description

*Type*: Bug

*Summary*: 

#### Expected behavior
Can see message with emoji

#### Actual behavior
![messages](https://user-images.githubusercontent.com/4557972/45693179-2fa16f00-bb65-11e8-8cad-bcf9123df409.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log in
- Switch to any chat
- Send message on Russian (or Korean, or Arabic) with emojis.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 18/09/2018
* Operating System:  Mac OS x
* Video: http://take.ms/qB3Gc
* Note: more languages\symbols can be affected, but I think root cause is the same. Let me know if it is needed to recheck with others. Not reproducible with Chinese, English.

**Comment by rasom** [comment]
https://bugreports.qt.io/browse/QTBUG-68060

<blockquote><img src="/s/-fyc67a/711002/7b049b77f66e256a8f5944987495e729/_/jira-favicon-hires.png" width="48" align="right"><div><strong><a href="https://bugreports.qt.io/browse/QTBUG-68060">[QTBUG-68060] [QtQuick, Android] Emoji is not displayed when used with non-Latin text - Qt Bug Tracker</a></strong></div></blockquote>

**Comment by rasom** [comment]
looks more like `react-native-desktop`'s bug as strings are encoded correctly on cljs side

**Comment by rasom** [comment]
is blocked by https://github.com/status-im/react-native-desktop/issues/347

**Comment by rasom** [comment]
https://github.com/status-im/status-react/issues/6053

**Comment by churik** [comment]
Closed with QT upgrade

**Comment by churik** [comment]
again reproducible for me on nightly 13/11/2018
<img width="343" alt="russian" src="https://user-images.githubusercontent.com/4557972/48415632-348e3380-e74e-11e8-92e2-abe99b7190e3.png">

**Comment by churik** [comment]
Done again in 30/11/2018
