### ISSUE TITLE
Application is not responding at attempt to log in with existing account for first time

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5900]
### Description

*Type*: Bug

*Summary*: when I log in with existing account (history ~1 week, several 1-1 and public chats) for first time, the application is not responding. After second/third time I can successfully log in.
Reproducible 3/5 when I started all from scratch for the very first login attempt.

#### Expected behavior
the application is not hanging

#### Actual behavior
the application is not responding

### Reproduction
*Prerequisites: you already have account, that you used for Status-Desktop*
- Open Status
- Log in with existing account

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 19/09/2018
* Operating System: Mac OSx

#### Logs

[Full log](https://drive.google.com/open?id=1UrFFlqvEDhOwQbOhAPtWfdb9XFM8ZsEK) and [video](http://take.ms/IJrOw)

**Comment by churik** [comment]
And one more log (shorter)
[StatusIm.log](https://github.com/status-im/status-react/files/2396776/StatusIm.log)

**Comment by pedropombeiro** [comment]
For the record, this is similar to the behavior observed in https://github.com/status-im/status-react/pull/5786, which up until now was only reproducible with v0.15.0 of status-go.

**Comment by pedropombeiro** [comment]
@churik do you mind testing the fix in https://ci.status.im/job/status-react/job/combined/job/desktop-macos/1258/artifact/StatusImPackage/StatusIm-180919-110543-af4d29-pr.dmg ?

<blockquote></blockquote>

**Comment by churik** [comment]
Thanks @PombeirP!
Yes, it is fixed in build which you are provided. Account creation, log in with existing account, recovering is working a lot faster than in current nightly. 
One question - can this fix affect mobile builds, should they be tested as well?

**Comment by pedropombeiro** [comment]
> can this fix affect mobile builds, should they be tested as well?

The fix is only for desktop builds, but we can do a quick check just to make sure that non-desktop builds weren't broken.

**Comment by churik** [comment]
@PombeirP yes, that's the idea. Can you provide a link to IOS/Android builds just in case?

**Comment by pedropombeiro** [comment]
@churik Here are the latest builds: https://github.com/status-im/status-react/pull/5786#issuecomment-422850615

**Comment by churik** [comment]
@PombeirP These are working fine for me, so I confirm that fix in https://ci.status.im/job/status-react/job/combined/job/desktop-macos/1258/artifact/StatusImPackage/StatusIm-180919-110543-af4d29-pr.dmg is working for desktop and doesn't affect mobile.
