### ISSUE TITLE
Desktop: Long messages cause list of channels to be too tall, with scrolling weirdness

### ISSUE THREAD

**Issue by noman-land** [status-im/status-react#5909]
I'm on the Mac nightly (5467deec9). macOS 10.12.

The list of channels should probably crop the last message with some ellipses or something.

![long](https://user-images.githubusercontent.com/27938023/45792768-3f03e380-bc5d-11e8-9767-eae154622e7c.gif)

**Comment by chadyj** [comment]
Fixed in develop. Look out for the next nightly!
