### ISSUE TITLE
Can't upload a build to the Play Store (metadata error)

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#5921]
We get this error when trying to upload a build to the Play store

```
[11:38:24]: Preparing to upload for language 'pt'...
+---------------+-----------------+
|          Lane Context           |
+---------------+-----------------+
| PLATFORM_NAME | android         |
| LANE_NAME     | android nightly |
+---------------+-----------------+


[11:38:24]: unsupportedListingLanguage: Listing language pt is not supported.
```

(see https://ci.status.im/job/status-react/job/combined/job/mobile-android/2695/console).

<blockquote><img src="/static/c32cacaf/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-android/2695/console">status-react » combined » mobile-android #2695 Console [Jenkins]</a></strong></div></blockquote>

**Comment by chadyj** [comment]
The folder [fastlane/metadata/android/pt](https://github.com/status-im/status-react/tree/develop/fastlane/metadata/android/pt) needs to be renamed `pt-PT`

**Comment by chadyj** [comment]
Issue was from this PR https://github.com/status-im/status-react/pull/5833

**Comment by yenda** [comment]
I made a PR for renaming the folder if that is just that.
