### ISSUE TITLE
Makefile nitpicks for first-time compile on fedora28

### ISSUE THREAD

**Issue by arnetheduck** [status-im/status-react#5928]
on 08c132c8a6f9209fae2fc08dac7cffe29c01e097, fedora 28, tried the makefile - here's an experience report:

* `make setup` missing fedora support - mostly works with below patch (except a few package names being different that get skipped):

```
diff --git a/scripts/lib/setup/packages.sh b/scripts/lib/setup/packages.sh
index 896068773..35e1b1342 100755
--- a/scripts/lib/setup/packages.sh
+++ b/scripts/lib/setup/packages.sh
@@ -66,6 +66,8 @@ function linux_update() {
apt_update
elif program_exists "pacman"; then
pacman_update
+ elif program_exists "dnf"; then
+ dnf_update
else
echo "Unsupported Linux distro."
exit 1;
@@ -79,6 +81,8 @@ function linux_is_installed() {
apt_is_installed "$@"
elif program_exists "pacman"; then
pacman_is_installed "$@"
+ elif program_exists "dnf"; then
+ dnf_is_installed "$@"
else
echo "Unsupported Linux distro."
exit 1;
@@ -95,6 +99,8 @@ function linux_install() {
apt_install "$@"
elif program_exists "pacman"; then
pacman_install "$@"
+ elif program_exists "dnf"; then
+ dnf_install "$@"
else
echo "Unsupported Linux distro."


+###############
+# DNF
+###############
+
+function dnf_update() {
+ sudo dnf update
+}
+
+function dnf_is_installed() {
+ local package=$1
+ dnf list --installed $package >/dev/null 2>&1
+}
+
+function dnf_install() {
+ local package=$1
+
+ if dnf_is_installed "$package"; then
+ cecho "+ $package already installed... skipping."
+ else
+ sudo dnf -y install "$package"
+ fi
+}
+
###############
# RVM
###############
```

* `make run-android` fails with cryptic message when `ANDROID_NDK_HOME` is different from `android/local.properties` - during the build process, it seems both are used without one overriding the other
* `make run-android` fails when `make prepare-android` has not been run (dependency issue)
* `make` prints a helpful message as to what the useful make targets are. these do not coincide with anything that https://docs.status.im/docs/build_status.html says. "checkout-and-make" is the norm for building stuff that has a makefile, so I'd say the docs printed are more useful than whatever docs.status.im has to say
* bash tab completion is able to pick up `run-android` and a bunch of other useful targets - it doesn't find the targets mentioned in docs.status.im (`startdev-*` for example) - this makes it more difficult to use quickly

```
[arnetheduck@fugit status-react]$ make
android-ports geth-connect prepare-android prod-build-android release run-android test watch-android-genymotion watch-ios-simulator
clean help prepare-ios prod-build-ios release-android run-ios test-auto watch-android-real
full-prod-build prepare prod-build react-native release-ios setup watch-android-avd watch-ios-real
```

kudos @mandrigin and @yenda for helping out with wrinkles ;)

<blockquote>![](https://status.im/img/og_logo.png)<div><strong>[Quick Start · Status Technikon](https://status.im/index.html)</strong></div><div>## The easiest way</div></blockquote>

**Comment by yenda** [comment]
I think it doesn't find the start-dev-* because they are not explicitly written in the file

**Comment by oskarth** [comment]
Still relevant probably. Candidate for bounty? At least blocking subset

**Comment by pedropombeiro** [comment]
@arnetheduck have you tried the feature/nix branch yet? Hopefully, we can close this after the branch is merged.

**Comment by pedropombeiro** [comment]
Regarding bash tab completion I had already fixed that maybe a couple months back.
