### ISSUE TITLE
Adapt Status Desktop builds to use Jenkins status-go artifacts

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#5931]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to Desktop builds to not build status-go locally and instead download the official builds, so that builds are reproducible and less time is spent building.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: We need to build on https://github.com/status-im/status-go/issues/1190 and https://github.com/status-im/status-react/pull/5888 to get the status-go build artifacts to the desktop build process. At the same time, remove the status-go build process from the CMake files.

**Comment by churik** [comment]
@PombeirP still relevant?

**Comment by pedropombeiro** [comment]
This was opened more to make sure we remained consistent in how we build mobile and desktop, but doesn't really bring a lot of value right now. I'd leave this to be tackled as part of the Reproducible Builds swarm.
