### ISSUE TITLE
Apply design to name + image editing under "Profile"

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5933]
### Description
*Type*: Bug

Apply the intended design to name+image editing under "Profile" on Status Desktop.

#### Expected behavior
<img width="244" alt="captura de pantalla 2018-09-21 a la s 9 48 13 a m" src="https://user-images.githubusercontent.com/37297779/45867326-7ec4eb00-bd83-11e8-91ad-72dc96ad0090.png">

#### Actual behavior
<img width="327" alt="captura de pantalla 2018-09-21 a la s 9 47 05 a m" src="https://user-images.githubusercontent.com/37297779/45867263-56d58780-bd83-11e8-928f-6d5a6d109452.png">

#### Solution
- [ ] Apply blinking cursor 
- [ ] Apply italic style to font
- [ ] Make image editable
- [ ] Apply overlay and icon on image
- [ ] Remove the name's grey background when on edit mode (temp workaround before https://github.com/status-im/react-native-desktop/issues/338 will be fixed):
<img width="104" alt="captura de pantalla 2018-09-21 a la s 9 54 54 a m" src="https://user-images.githubusercontent.com/37297779/45867736-6a352280-bd84-11e8-898d-7287e04eb424.png">

- [ ] Apply bigger target area to "Edit/Done" action. Right now is hard to click:
<img width="649" alt="captura de pantalla 2018-09-21 a la s 9 51 59 a m" src="https://user-images.githubusercontent.com/37297779/45867598-162a3e00-bd84-11e8-85c4-8ed8ca76c177.png">

- [ ] Put focus to the editable area when the user is in editable mode

When you open Profile -> Edit you should manually set focus to username field. Now it is looking a bit confusing, especially when area is not distinguished from background.
I'm suggesting to set focus automatically to username area when you click on "Edit" (like it is made for mobile)
Video: http://take.ms/8A5ok

*State:* 
blocked by RN issue: https://github.com/status-im/react-native-desktop/issues/338

- [ ]  Input area is not aligned according to design.

![px](https://user-images.githubusercontent.com/4557972/45752722-1e1c9d80-bc1f-11e8-8c8a-59a098b950e1.png)

- [ ] Username is cut in editable mode when it contains emoji
![emoji](https://user-images.githubusercontent.com/4557972/45753475-b287ff80-bc21-11e8-9947-a675b569306a.png)

**Designs in Zeplin** >> zpl.io/brE1NdX

### Reproduction
- Open Status
- Go to Profile
- Click on "Edit" (top right corner)

**Comment by churik** [comment]
Irrelevant in terms of https://github.com/status-im/status-react/pull/7551
