### ISSUE TITLE
App crash when sending Request to contact from Wallet

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5936]
***Type***: Bug

***Summary***: App crashes with an `Error: Error: There is no route defined for key home.
Must be one of: 'wallet-request-transaction','wallet-send-transaction-request','wallet-request-assets','recent-recipients'` when contact sends a `Request` from `Wallet` -> `Receive tranaction` -> `New request` screen.

#### Expected behavior
Request message sent in 1-1 chat

#### Actual behavior
Error: Error: There is no route defined for key home.
Must be one of: 'wallet-request-transaction','wallet-send-transaction-request','wallet-request-assets','recent-recipients'` followed by the app crash

<img width="179" alt="screen shot 2018-09-21 at 11 57 04" src="https://user-images.githubusercontent.com/8749671/45871233-a1f89600-bd95-11e8-8b93-3c143ec01548.png">

### Reproduction

- Open Status and create new account
- Add a contact in the list of contacts
- Navigate to `Wallet` -> `Receive tranaction` -> `New request`
- Choose recipient and specify valid amount
- Tap `Send request` button

### Additional Information
* Status version: Develop `0.9.29 (8885); node 0.15.0` (NOTE: it's all **fine** in **Release 0.9.28**)
* Operating System: Android and iOS

#### Logs
`Error: Error: There is no route defined for key home.
Must be one of: 'wallet-request-transaction','wallet-send-transaction-request','wallet-request-assets','recent-recipients'
`
TF session with logs: https://app.testfairy.com/projects/4803590-status/builds/8601407/sessions/4401998975/?accessToken=CaMnkA1/DSdD4B/6rhFTDg8Su4U

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8601407/sessions/4401998975/?accessToken=CaMnkA1/DSdD4B/6rhFTDg8Su4U">TestFairy: Status 0.9.29 (8885) @2018</a></strong></div></blockquote>

**Comment by janherich** [comment]
I will fix that today
