### ISSUE TITLE
Default name showing up at login instead of my nick/id

### ISSUE THREAD

**Issue by mariapaulafn** [status-im/status-react#5948]
[comment]: # (Please replace ... with your information. Remove < and >)

I've been a status mobile user for long, however when using desktop, my name does not load at login. See screenshots.

As a user, I want to see my name as displayed on mobile.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  I use both mobile and desktop, and while in Mobile when loging in my name + pic are displayed, i get my default status nick on desktop

#### Expected behavior
[comment]: # Load my identity correctly

#### Actual behavior
[comment]: # Get the default one

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: desktop
[comment]: # (Android or iOS.)
* Operating System: iOS

<img width="950" alt="screen shot 2018-09-24 at 09 30 01" src="https://user-images.githubusercontent.com/27913589/45941349-09088b80-bfde-11e8-9d93-4bf12ac49001.png">

![img_3170](https://user-images.githubusercontent.com/27913589/45941375-1e7db580-bfde-11e8-87b8-d24b7f07f18b.PNG)

**Comment by churik** [comment]
@mariapaulafn 
thanks for your issue!

However, there is no sync between mobile and desktop version (known issue, https://github.com/status-im/status-react/issues/4367)
For now, your username and profile pic are stored on the device.
