### ISSUE TITLE
Can't upgrade to 0.9.28 version. Problem with encryption key

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5954]
### Description

*Type*: Bug

*Summary*: 

When app is upgraded from 0.9.27 to 0.9.28 from TestFlight there is an error. When I clicked “Apply”, I ended up on a blank screen with spinner. After couple of seconds, the “encryption key” error popup appeared again. I’m testing on iOS 12.

<img src="https://user-images.githubusercontent.com/7532782/45946653-d2d50700-bff1-11e8-8344-065b455c8016.png" width="200">

### Reproduction

- Install 0.9.27 from TestFlight
- Recover some account
- Upgrade to 0.9.28

### Additional Information
* Status version: release/0.9.28
* Operating System: iOS

**Comment by rasom** [comment]
@lukaszfryc fix pushed directly to `release/0.9.28` 
in `develop` issued will be fixed by upgrading `realm-js`

**Comment by lukaszfryc** [comment]
Works fine
