### ISSUE TITLE
Chat scroll is jumping when input text area edges and message edges are overlapping

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5960]
### Description

*Type*: Bug

*Summary*: chat jumps to several rows in the case when the edge of message and edge of input area are overlapping. Same behavior when scrolling to start of day history (to "Today" label for instance)
![scro](https://user-images.githubusercontent.com/4557972/45949606-184eff80-c005-11e8-88d7-a066f04e1317.png)

#### Expected behavior
no autoscrolling

#### Actual behavior
autoscrolling to several rows or the middle of the previous message

### Reproduction

- Open Status
- Open any public chat 
- Scroll slowly to the edge of the last message

### Additional Information
* Status version: status desktop 24/09/18
* Operating System: Mac OSx
* Video: http://take.ms/3xE2V

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=3sEGptrqYh3C6xxLFAg3dT60nouDO9&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/3sEGptrqYh3C6xxLFAg3dT60nouDO9">File "screencast 2018-09-24 14-25-50.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by churik** [comment]
Same with chat-list - if you scroll smoothly in chat list (should have 10+ chats to see this) to see all chats, autoscrolling jumps to the previous chat or just a bit up on the edges of chat names area.
<img width="568" alt="scroll_1" src="https://user-images.githubusercontent.com/4557972/46663773-a6abaf80-cbc7-11e8-8e1d-4314867af2de.png">


Video: http://take.ms/zXe7P


<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=0UDLtPVlelNcFkKZkmN1d4F3nhl4vr&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/0UDLtPVlelNcFkKZkmN1d4F3nhl4vr">File "screencast 2018-10-09 13-27-39.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by churik** [comment]
@Serhy 
still reproducilble on current nightly 
Video: http://take.ms/r0ebQ

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=t2hRYiUmIvtJSDEdhfiMV3FAOchCYj&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/t2hRYiUmIvtJSDEdhfiMV3FAOchCYj">File "screencast 2018-11-07 18-12-19.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by exiledsurfer** [comment]
this is new behaviour for me since 181126-025916-2d5c4e-nightly

 screen recording: https://d.pr/free/v/j839To

<blockquote><img src="https://cdn-std.dprcdn.net/previews/j839To.preview_medium.jpg" width="48" align="right"><div><strong><a href="https://d.pr/free/v/j839To">Screen Recording 2018-11-26 at 12.17.49.mov</a></strong></div><div>Shared with Droplr</div></blockquote>

**Comment by churik** [comment]
Issue is gone; perhaps not completely but definitely hard to reproduce on nightly 30/11/2018
