### ISSUE TITLE
Chat Scroll on one pane carries over to another pane in Status Desktop

### ISSUE THREAD

**Issue by bitsikka** [status-im/status-react#5962]
### User Story

As a user I expect UX/user interaction to be consistent with standards already established in popular apps with same context.

### Description

*Type*: Bug

*Summary*: There is at the moment two main panes in Status desktop - the chat list pane, and the chat pane. When I start scrolling up or down with mouse on one pane, and then roll the mouse over to other pane, the other pane also scrolls.

#### Expected behavior
Scroll event started on a pane usually do not carry over to other pane

#### Actual behavior
Scroll event initiated on one carries over to the other pane on roll over to other pane

### Reproduction

- Open Status Desktop
- Scroll with mouse up/down on Chat list or chat pane, roll mouse over to other pane

### Additional Information

* Status version: StatusIm-180923-025918-089027-nightly.dmg 

* Operating System: MacOS High Sierra

**Comment by churik** [comment]
@bitsikka 
Can you please attach a video?
I cannot reproduce it on Mac OSx, nightly 24/09/18
Video: http://take.ms/wTO9d

**Comment by bitsikka** [comment]
@churik 
https://youtu.be/BmnqaNW0uBo

<blockquote><img src="https://i.ytimg.com/vi/BmnqaNW0uBo/hqdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=BmnqaNW0uBo">Screen Recording</a></strong></div><div> </div></blockquote>

**Comment by bitsikka** [comment]
what you are missing is quickly rolling over once you scroll(before the elasticity of mouse scroll dies out).
I'm using the wireless magic mouse btw, if that makes a difference.

**Comment by churik** [comment]
@bitsikka can you reproduce this issue on current nightly?
Seems that I'm not able to reproduce it anymore

**Comment by churik** [comment]
Irrelevant in terms of https://github.com/status-im/status-react/pull/7551
