### ISSUE TITLE
Navigation to Wallet main screen happens when tap 'Back' from Wallet onboarding initiated in 1-1 chat 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5967]
***Type***: Bug

***Summary***: If user recovered an account (or created a new one) (s)he need to "Set up a Wallet" (three words phrase). Navigation to Wallet Set Up screen happens when contact wants to send a transaction from 1-1 chat. In a case when user decides to navigate back from ' Wallet Set Up' screen he winds up on main Wallet tab, and NOT 1-1 chat. 
We need to return user back to 1-1 chat if he tap `<` back button on Wallet Set Up screen that appeared from 1-1 chat. 
Please, see steps to reproduce:

#### Expected behavior
New user and wallet not setted up -> sends `/send ETH 0` message in 1-1 chat -> taps Back button from `Wallet Set Up`-> appears on 1-1 chat screen

#### Actual behavior
New user and wallet not setted up -> sends `/send ETH 0` message in 1-1 chat -> taps Back button from `Wallet Set Up`-> appears on Wallet main screen

### Reproduction
- Open Status and create new account (or recover existing account)
- And a new contact
- Navigate to 1-1 chat with the contact
- Send a `/send ETH 0` message
- From `Set up your wallet` screen tap `<` top-left button

### Additional Information
* Status version: `Develop (8943)`
* Operating System: Android and iOS

#### Logs

TF session with video: https://app.testfairy.com/projects/4803622-status/builds/8603658/sessions/4402209174/?accessToken=42iCGiRfzip3DmZWmGbkak67vtw

**Comment by Swader** [comment]
Not resolved.

**Comment by Serhy** [comment]
Still an issue in Release 0.10.1 build. Should be fixed along with Wallet redesign. PR with Wallet redesign decoupled (https://github.com/status-im/status-react/pull/7263#issuecomment-465983635) in several tasks. This issue could be fixed after #7571 is fixed.

**Comment by Serhy** [comment]
Can not reproduce with 0.11.0 Release (and 0.12.0 Develop). Happy to close this one!
