### ISSUE TITLE
Use safeAreaLayoutGuide instead of hardcode check for iPhone X

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#5971]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

Currently the content on iPhones XS/XS Max/XR overlaps notch & control areas (see screenshot).
It happens, because we have hardcoded checks for iPhone X and hardcoded values for the insets.

Instead, we should use [`safeAreaLayoutGuide `](https://developer.apple.com/documentation/uikit/uiview/2891102-safearealayoutguide) to get these values from OS. 

See this tutorial for the RN implementation: https://medium.com/react-native-training/react-native-iphonex-92ff511282af

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on iPhone XS/XS Max/XR (simulator or real).
- Go to the main screen
- Observe controls

<img width="199" alt="iphone xs max - 12 0 2018-09-24 17-36-42" src="https://user-images.githubusercontent.com/466427/45962560-6e31a080-c021-11e8-8f91-233d926af3f0.png">

<blockquote><img src="https://cdn-images-1.medium.com/max/1200/1*MHJzJkvAKnW77iIZ73zmoA.png" width="48" align="right"><div><img src="https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico" height="14"> Medium</div><div><strong><a href="https://medium.com/react-native-training/react-native-iphonex-92ff511282af">React Native & iPhone X – React Native Training – Medium</a></strong></div><div>Easily update and create iPhone X layouts with SafeAreaView</div></blockquote>

**Comment by lukaszfryc** [comment]
Btw, on my side iPhone XS looks fine. The issue is with XR (and probably Max) 

<img src="https://user-images.githubusercontent.com/7532782/46022625-41de5880-c0e3-11e8-91a0-15de7e3ce3e2.png" width="200">
