### ISSUE TITLE
Create "State of the DApps" group and integrate JSON

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#599]
State of the DApps will provide a curated list of Ropsten compatible DApps that will be a group within Status contact list named "State of the DApps".

This depends on EtherCasts/state-of-the-dapps#22

**Comment by viebel** [comment]
A JSON endpoint is now available http://dapps.ethercasts.com/api/dapps-by-tag/status-im.
@jarradh Does it mean that we could start to work on this issue?

**Comment by jarradh** [comment]
Yes :) 👍

**Comment by viebel** [comment]
A couple of questions @jarradh :
1. Do we want to load the apps list at run time or at compile time?
2. Do we want to display all the dapps or only  the ones with the `status-im` tag (there are only 3 apps returned by http://dapps.ethercasts.com/api/dapps-by-tag/status-im)?
3. There is no `photo-path` in the data returned by state-of the-dapps`...

Typical dapp data returned by `state-of the-dapps` looks like this:

```json
{
_id: "559511ad46b1fe01994ce505",
name: "EtherEx",
status: "7. Working Prototype",
platform: "Ethereum POC9",
contact: "caktux",
description: "Decentralized Exchange",
license: "MIT",
tags: ["exchange"],
url: "https://etherex.org/",
last_update: "2015-08-15",
reddit: "https://www.reddit.com/r/etherex",
github: "https://github.com/etherex/etherex",
row_nr: 66
}
```

**Comment by viebel** [comment]
For the moment, all the `status-im` dapps  are already inside status.  Therefore, this feature will not add any new dapp. But the `state-of-the-dapps` will be in a separate group.

**Comment by viebel** [comment]
@jarradh something like that?
![image](https://cloud.githubusercontent.com/assets/955710/22518019/c2278f2a-e8b3-11e6-80af-fcd5d464d84c.png)

**Comment by jarradh** [comment]
why is this issue still open if the PR was merged?

best to use "fixes #599" and github auto-links and auto-closes

**Comment by rasom** [comment]
@jarradh, was the idea of this task the loading of State of the DApps" list on every application start or it should be added statically to the application?

**Comment by jarradh** [comment]
well I thought at compilation time would have been better..

**Comment by jarradh** [comment]
to be frank this task has taken a lot more attention than i thought it would
