### ISSUE TITLE
Add option to switch languages in the application settings

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6001]
### Description

*Type*: Bug

*Summary*: As a user I want to have an option to switch languages in the app 

#### Expected behavior
1. App should follow device language
2. User has the ability to change the language to any other supported in app settings.

 Languages and translations are here
https://github.com/status-im/status-react/blob/develop/src/status_im/i18n.cljs#L16

#### Actual behavior
App language depends on device settings language

### Designs

![image](https://user-images.githubusercontent.com/28752642/46065214-2c683d80-c17a-11e8-9ccd-2a7dbab03ce4.png)

**Comment by yenda** [comment]
Why don't we leave that to the OS ?

**Comment by asemiankevich** [comment]
@yenda it was requested by community
