### ISSUE TITLE
'fx/defn expects a map of cofx...' error trying to clear 1-1/public chat history

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6005]
***Type***: Bug

***Summary***: 
An error appears when contact tries to clear 1-1 / public chat history. 
Chat history is not cleared.
User can proceed to use the app fine. 
Also reproducible for desktop builds.

#### Expected behavior
1-1 / public chat history is cleared upon confirm "Are you sure you want to clear this chat history?" popup 
#### Actual behavior
<img width="216" alt="screen shot 2018-09-26 at 11 51 28" src="https://user-images.githubusercontent.com/8749671/46068738-8c62e200-c182-11e8-93d1-207b0fc55ef3.png">

### Reproduction
- Open Status and create new account
- Add a new contact to start 1-1 chat
- Join `#status` public channel
- In public chat tap top-right menu button -> `Clear history`
- In appeared `Clear history?` pop-up tap `Clear` button
**Actual result:**  `fx/defn expects a map of cofx...` error
- Navigate to 1-1 chat -> top-right chat menu button -> `Clear history` -> `Clear`
**Actual result:**  `fx/defn expects a map of cofx...` error

### Additional Information
* Status version: Develop `0.9.29 (9168); node 0.15.0`
* Operating System: Android, iOS, Mac OSx

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8606183/sessions/4402350466/?accessToken=CMJEQ3G4iyf7/mVaeDG46SXx7io

`fx/defn expects a map of cofx as first argument got yyyt in function function (e) {switch(arguments.length){case 1:return status_im.chat.models.clear_history.cljs$core$IFn$_invoke$arity$1(arguments[0]);case 2:return status_im.chat.models.clear_history.cljs$core$IFn$_invoke$arity$2(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""))}}
`

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8606183/sessions/4402350466/?accessToken=CMJEQ3G4iyf7/mVaeDG46SXx7io">TestFairy: Status 0.9.29 (9168) @2018</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Reproduced in Status Desktop as well

**Comment by churik** [comment]
Got same error when tap on Contact from contact list below (chat is not started).

*Steps:*
- Join to any public chat
- Tap on user icon > add him to contact
- Navigate to Home
- Tap on + > Start New Chat
- Select user from contact list

![err](https://user-images.githubusercontent.com/4557972/46075398-12872480-c193-11e8-8ad3-f0bd0d6596b7.png)

**Comment by lukaszfryc** [comment]
@yenda there is another one when trying to join public chat using universal link `https://get.status.im/chat/public/blah`

<img src="https://user-images.githubusercontent.com/7532782/46076248-4c552c80-c18d-11e8-9859-51365b58d759.png" width="200">
