### ISSUE TITLE
Add USDC token to wallet

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6026]
### Description

*Type*: Feature

*Summary*: Add `USDC` ([Circle](https://www.circle.com/en/usdc-faq) partnership) to the wallet. 

Contract: https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

[USDC icon](https://drive.google.com/open?id=1VC15fFG7rtaX82VD8_fjDHOfTnwDeT4R)

#### Expected behavior
`USDC` appears in the `Manage assets` list.

#### Actual behavior
No `USDC`.

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48">USD//C (USDC) Token Tracker</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by fredbuluku** [comment]
I have an issue with circle USDC,no one in customer care is responding back to my questions,where else can get help?
