### ISSUE TITLE
Transaction history show the wrong symbol on erc-20 token

### ISSUE THREAD

**Issue by 751895405** [status-im/status-react#6029]
### Description
you do some transaction on erc-20 token and eth when you look at the transaction history all erc-20 token symbol show as ETH and amount is 0

#### Expected behavior
erc-20 token show the right symbol and amount correctly on transaction history
#### Actual behavior
all erc-20 token show wrong symbol on transaction history

### Reproduction

- Open Status 0.9.28
- do some real transaction by erc-20 token and eth
- go to transaction history

**Comment by annadanchenko** [comment]
is it same as https://github.com/status-im/status-react/issues/5749 ? See point 2 in its description: `2) Outgoing token transactions are shown as 0 ETH instead of token and amount`

**Comment by 751895405** [comment]
yep i think i should close this issue
