### ISSUE TITLE
Remove logic from desktop messages list view

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#6033]
### User Story

As a developer, I want to remove logic from view

### Description

*Type*: Improvement

*Summary*: Discussed with @yenda that having logic inside view in `src/status_im/ui/screens/desktop/main/chat/views.cljs` isn't ok. At the moment of creating PR #6006 it wasn't clear how to remove it, so this issue created for later fix.

#### Expected behavior
View doesn't contain logic

#### Actual behavior
View contains logic

### Reproduction
- Open `src/status_im/ui/screens/desktop/main/chat/views.cljs`
- check `messages-view` implementation

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:  TBD

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: V0.0.1 (ed2abf910)
[comment]: # (Android or iOS.)
* Operating System: Mac

**Comment by rasom** [comment]
@vkjr @yenda can you elaborate a bit? Is that wrong from the performance pov or it has some other implications?

**Comment by vkjr** [comment]
@rasom, this issue was created per discussion in PR - https://github.com/status-im/status-react/pull/6006/files Not sure about exact implications, probably @yenda can answer it better.


<blockquote><img src="https://avatars0.githubusercontent.com/u/5786310?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/6006">Fix/chat loading time by vkjr · Pull Request #6006 · status-im/status-react</a></strong></div><div>fixes #5112
Summary:
Loading a chat with a lot of messages takes huge time because ScrollView renders all elements at once. Optimizing Text loading time in react-native-desktop didn&#39;t make sign...</div></blockquote>

**Comment by churik** [comment]
Irrelevant in terms of https://github.com/status-im/status-react/pull/7551
