### ISSUE TITLE
Caret position is changed when typing fast in input message field

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6042]
### Description

*Type*: Bug

*Summary*:  carer in field "Type a mesage" moves to several chars inside of text when you are typing fast.
Same as https://github.com/status-im/status-react/issues/5670 but in another field.
Didn't notice the same behavior on other fields.

#### Expected behavior
caret is always in the end of the phrase

#### Actual behavior
caret is moved in the middle of the text

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open 1-1 chat
- Type message (fast)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: status nightly 27/09/18
* Operating System: Mac OSx
* Video: http://take.ms/pDHBk

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=IGmMJt0lEfhFnoknzbV5ksjcssXprx&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/IGmMJt0lEfhFnoknzbV5ksjcssXprx">File "screencast 2018-09-27 18-15-31.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by rasom** [comment]
there is also a bit different issue, caret position is changed when typing fast in the second/third row (exactly when a new row should be started). But it should be fixed separately

**Comment by churik** [comment]
https://github.com/status-im/status-react/issues/6042#issuecomment-425827510 moved to https://github.com/status-im/status-react/issues/6074
