### ISSUE TITLE
Can't log in - shhext_getNewFilterMessages does not exist

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6051]
### Description

*Type*: Bug

*Summary*: @jonathanbarker could not log in recently because of "unknown status go error" after clicking the sign in button. It maybe that status-go crashed. It would be great to investigate it since we have [full logs](https://gist.github.com/lukaszfryc/70f606272e1db4ef3423cf50cd498d94). 

Part of the logs: 

```
(Instabug Logs - Debug) 27-09 11:00:15.805 ERROR [status-im.transport.handlers:50] - Something went wrong Error: The method shhext_getNewFilterMessages does not exist/is not available nil
``` 

<img src="https://user-images.githubusercontent.com/7532782/46205020-89512880-c31f-11e8-917e-d4fcac2875f4.png" width="200">

### Reproduction

No steps to repro.

### Additional Information
* Status version: 0.9.28 (9098)
* Operating System: Android 28, Google Pixel

**Comment by lukaszfryc** [comment]
@jonathanbarker did you try to kill the app and log in again?

**Comment by lukaszfryc** [comment]
cc @yenda @mandrigin

**Comment by J12B** [comment]
More context: I was using the app fine, sent a messge and then turned used another app on my phone. I came back to my phone a while later and had a Status notification in my taskbar (I think it was a new message). When I clicked into it, Status wouldn't log me in. 

I killed the app, restarted and was immediately able to log in.

**Comment by yenda** [comment]
@lukaszfryc is there more complete logs ? the one you send seem to start too late to really understand what happened

**Comment by lukaszfryc** [comment]
No, that's all we have. The bug and logs was reported by Instabug
