### ISSUE TITLE
Universal links to Dapps are returning a "URL not supported" error

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/status-react#6072]
### User Story

As a user,
 I want to be taken to a dapp inside of Status,
 so that I may use the dapp with my funds stored in the Status wallet.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I'd like to use universal deep links to improve discovery of the voting dapp. At the moment when tapping on universal links a user is redirected to the status app but the browser is unable to open the page. 

#### Expected behavior
When universal link to a dapp is tapped, Status app opens with "Open in Status" option:

<img src="https://user-images.githubusercontent.com/7532782/46411808-02d08880-c71d-11e8-83d3-072c1d97c0b4.png" width="200">

If the option is tapped, the dapp opens inside Status.

#### Actual behavior
When the universal link was tapped it was opened inside of my native browser (Safari), then tapped on the option to tap on "open in Status". I was redirected to status, asked if I wanted to open the dapp in status browser or web browser. I selected "status" and received a browser screen with an error message. 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Outside of Status tap on any of the following: 
https://get.status.im/browse/www.cryptokitties.co
get.status.im/browse/https://ipfs.infura.io/ipfs/qmyhtgg88wvjh9k86m3jyow3qxdxmkgk8stktdqy87jozn/
get.status.im/browse/https://ipfs.infura.io/ipfs/QmYhTGg88WvJh9K86m3JYow3QxdXMkgk8stkTDqy87joZn/
https://get.status.im/browse/google.com

You should be directed to Status and asked wether you would like to open in status or web brwoser. Select status. 

<img src="https://user-images.githubusercontent.com/7915365/46279419-f0115480-c560-11e8-863b-d79e10670b96.png" width="200">

Please note that the error happens on ios and android. 

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

From my investigation, it seems that the URL in the browser is the entire universal link. For example https://get.status.im/browse/google.com produces in the browser: status-im://browse/google.com

### Additional Information
iOS and Android.
Status 0.9.28 
#### Logs

![](https://files.slack.com/files-pri/T0PDCGZJQ-FD4G5FVEZ/image_uploaded_from_ios.png)

<blockquote><div><strong><a href="https://get.status.im/browse/www.cryptokitties.co">Browse to www.cryptokitties.co in Status</a></strong></div></blockquote>
<blockquote></blockquote>
<blockquote><div><strong><a href="https://ipfs.infura.io/ipfs/QmYhTGg88WvJh9K86m3JYow3QxdXMkgk8stkTDqy87joZn/">Status.im - Survey</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/browse/google.com">Browse to google.com in Status</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
It works fine on 0.9.27 but stopped working on 0.9.28.

@rasom maybe it's related to #5606, could you check?

**Comment by asemiankevich** [comment]
@lukaszfryc @Graeme-Code it is working now in nightly. However release is still broken. Do we want to release it? @annadanchenko @mandrigin ?

**Comment by lukaszfryc** [comment]
@asemiankevich I'd say let's include it in the release before Prauge event. It is planned on Oct 22th.

**Comment by lukaszfryc** [comment]
I will close it since it's already on develop and we will cut the next release from the develop branch.
