### ISSUE TITLE
App is killed after switching from Ropsten (LES) to Ropsten RPC or other network

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6073]
### Description

*Type*: Bug

*Summary*: When "Ropsten (LES)" is selected as the network, the app is getting killed when network is changed to e.g. "Ropsten RPC". All works fine when app is opened again.

#### Expected behavior
Network should be switched and user logged out.

#### Actual behavior
App is killed.

### Reproduction

- Open Profile, Advanced settings
- Go to Networks and select Ropsten LES
- Log in again and change the network to Ropsten RPC

### Additional Information
* Status version: introduced in https://github.com/status-im/status-react/pull/6007 (on purpose)
* Operating System: Android, iOS

**Comment by Swader** [comment]
Still happens.

**Comment by churik** [comment]
No Ropsten (LES) in Profile > Network Settings anymore on nightky 25/02/2020.
Closing the issue.
