### ISSUE TITLE
"Not sent" message is shown as "Sent" if it was sent during 2 sec after coming online

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6080]
### Description

*Type*: Bug
*Summary*: if you send message immediately after switching off offline mode - it is shown as Sent, but in fact it wasn't sent.

#### Expected behavior
status is "Not sent. Tap for options" with resend option.

 <img width="200" alt="offl" src="https://user-images.githubusercontent.com/7532782/47304308-81d32580-d626-11e8-8ab0-f98061d5e182.png">

#### Actual behavior
status is "sent"
<img width="491" alt="offl" src="https://user-images.githubusercontent.com/4557972/46295006-bdd31780-c59f-11e8-8007-d9d55778167f.png">

### Reproduction

- Open Status
- Type a message
- Turn off WI-FI
- Wait for 10 sec
- Turn on WI-FI and immediately (during 2 sec) send a message

### Additional Information
* Status version: nightly 01/10/2018
* Operating System: Android, IOS, desktop
* TF session: https://app.testfairy.com/projects/4803590-status/builds/8611567/sessions/4402803746/?accessToken=tykYFpL1X6sUO6Njg9IAkpeAVAQ

In status-desktop it is reproducible in another way as well in #5919  (look at https://github.com/status-im/status-react/pull/5919#issuecomment-425896202)

**Comment by lukaszfryc** [comment]
I also experienced it recently. 

I think we should increase sev and priority of this issue as it breaks confidence in chats.

**Comment by lukaszfryc** [comment]
This can be also reproduced in 0.9.30

**Comment by dshulyak** [comment]
The root cause is probably the same as in https://github.com/status-im/status-go/issues/1276
