### ISSUE TITLE
MY ACCOUNT on explorer.livepeer.org is not available on Status Android App.

### ISSUE THREAD

**Issue by chrishobcroft** [status-im/status-react#6083]
### User Story

As a user of **Status Android App** and [**Livepeer open-source video infrastructure**](https://livepeer.org), I want to bond my [Livepeer Tokens (LPT)](https://etherscan.io/token/0x58b6a8a3302369daec383334672404ee733ab239) to Livepeer's Delegated-Proof-of-Stake protocol using Status App's Browser running [Livepeer's Protocol Explorer](https://explorer.livepeer.org/).

This is so that Status Android App's community can also participate in Livepeer's protocol, and become more aware of the opportunities open to them as owners of Livepeer Tokens (LPT).

### Description

*Type*: <Bug|Feature>

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I would like to be able to use Status' browser to interact with Livepeer's protocol via https://explorer.livepeer.org.

#### Expected behavior

I expect that the wallet built in to Status app is visible to [Livepeer's Protocol Explorer](https://explorer.livepeer.org/me), to the extent that a user can see "MY ACCOUNT".

For example, when I load the same page and logged in with MetaMask add-on to Firefox in Android, it gives me the option of "MY ACCOUNT":

![image](https://user-images.githubusercontent.com/2212651/46313778-05ba6480-c5c9-11e8-8184-1793445db069.png)

#### Actual behavior

As above, when I load [Livepeer's Protocol Explorer](https://explorer.livepeer.org/me) in Status Android App, it does not connect that it is Web 3.0 enabled.

### Reproduction

- Open Status
- Go to Home
- Tap the + icon
- Select Open DApp
- Where it says "Enter URL", type `https://explorer.livepeer.org`
- Notice that "MY ACCOUNT" is not an Option, as it is with MetaMask add-on to Firefox.

### Solution

Need to fix integration between Status App Wallet and Status App Browser. Talk to @ligi about Ethereum Foundation Foundations for Wallets on Android. And did you incorporate @peepdroid into your app as a dApp yet?

### Additional Information

* Status version: ...
Android 0.9.28 Status App

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://explorer.livepeer.org/">Livepeer | Protocol Explorer</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
can't repro on ios simulator, but can repro on my Android device

**Comment by chrishobcroft** [comment]
This issue is only on Android.

**Comment by chrishobcroft** [comment]
It works on Android for other browsers, specifically:

- Trust Wallet

![screenshot_20181006-010539](https://user-images.githubusercontent.com/2212651/46570448-90ea8000-c964-11e8-9d38-a858e7db0192.png)

- Firefox + MetaMask

![screenshot_20181006-010737](https://user-images.githubusercontent.com/2212651/46570449-90ea8000-c964-11e8-81ed-47f982d6a1d2.png)

- Cipher Browser

![screenshot_20181005-213645](https://user-images.githubusercontent.com/2212651/46570450-90ea8000-c964-11e8-863f-b2ff51a637e2.png)

**Comment by flexsurfer** [comment]
thanks @chrishobcroft I'm on it
