### ISSUE TITLE
Can't login after app was killed and remember password was disabled

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6090]
### Description

*Type*: Bug

*Summary*: 

When "Set password until logout" was OFF, user logged in and then killed the app, the "Signing you in..." appears when app is opened again. The user is not logged in and there is option to do so as the sign in button is hidden. To fix it, user has to kill the app. All works fine when the "Set password until logout" is ON. The issue happens only on iOS as Android does not have "Set password until logout" feature.

<img src="https://user-images.githubusercontent.com/7532782/46345977-c9c5e480-c646-11e8-81ed-cc5b9302c77e.png" width="200">

#### Expected behavior
When "Set password until logout" was OFF and app is killed, the user is logged out and can log in again.

#### Actual behavior
When "Set password until logout" was OFF and the app is killed, the user is unable to log in.

### Reproduction

- Open app
- Set "Set password until logout" to OFF
- Log in 
- Kill the app and open it again

### Additional Information
* Status version: nightly, 2 Oct
* Operating System: iOS

**Comment by lukaszfryc** [comment]
cc @mandrigin

**Comment by yenda** [comment]
@lukaszfryc I can't reproduce with the steps described but if I open status from a notification after killing it I can reproduce. Could you check https://github.com/status-im/status-react/pull/6060 as this is fixing that

**Comment by lukaszfryc** [comment]
@yenda, yes, #6060 fixes this issue 👍
