### ISSUE TITLE
Push notification (new messages in 1x1 chat) is not received on Android

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6101]
### Description

*Type*: Bug

*Summary*: user is not receiving push notifications for android deivces. NOTE: it works on iOS. So having pair ios - android (both in contacts) user is able to see PN on iOS but Android is not showing any PN

UPDATE:

I am trying to localize the problem and it feels like there is a problem with Android 7 device for now. so sending messages from android 7 to android 8 produces PNs. But it doesnt work in other way.
Both accounts are recovered.

#### Expected behavior
PN is shown when premissions are enabled in settings on Android

#### Actual behavior
No push notification (android 7 probably). Permissions are enabled, contact is added to list of contacts

### Reproduction

- Open Status
- Add iOS and Android to contacts of each other
- Check notification settings on Android and enable when needed
- Send Android app on the  background
- from iOS device send message to Android
- check that no PN received on Android device

### Additional Information
* Status version: develop
* Operating System: Android

**Comment by yenda** [comment]
@asemiankevich is it still an issue?

**Comment by asemiankevich** [comment]
nope i dont think so
