### ISSUE TITLE
"Cannot retrieve a valid key for a given account: could not decrypt key with given passphrase" at attempt to login on desktop  with existing account. 

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6103]
### Description

I installed the latest nightly and tried to login. I entered my password and get a "unknown status go error".

<img width="231" alt="screen shot 2018-10-03 at 11 14 55 am" src="https://user-images.githubusercontent.com/116099/46402010-ddcd1d00-c6fe-11e8-8dab-cf31e0462abe.png">

If I use an incorrect password I see a "Wrong password" error instead.

Here are the [logs](https://gist.github.com/chadyj/bd5ddbc6910772500f6a4f44eb7f1fec) from when I hit "enter". 

I see errors like:

`RCTStatus::login Login result:  "Error: cannot retrieve a valid key for a given account: could not decrypt key with given passphrase"`

**Comment by jpbowen** [comment]
Here is [my log](https://gist.github.com/jpbowen/23e71d18c7ad10e7a9c3e7a44c7377d0) for the same issue.

**Comment by chadyj** [comment]
Turns out this was because I had installed a group-chat/pfs build and there isn't an upgrade path.

To fix the issue I quit the app, deleted `~/Library/Application Support/StatusIm/ethereum/mainnet_rpc/*.db` then re-opened.
