### ISSUE TITLE
Limit log size on Status-desktop

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6106]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I don't want to waste my storage to save huge log files.

### Description

*Type*: Feature

*Summary*: now limit for log size is not set, so after a while of daily usage you can get log more than 1GB.
Suggested options are to set maximum limit for log size (i.e. `100MB`) or to change log-level for PR / nightly builds depending on needs.

**Comment by Swader** [comment]
This needs to stay open until resolved.
