### ISSUE TITLE
Send button is enabled on desktop app when trying to send spaces only

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6111]
### Description

*Type*: Bug

*Summary*: `Send` button is active when having spaces only in text box on Statis desktop. When i hit Enter - nothing is actually sent. There is no harm of such behavior, however, it would be great to align desktop and mobile client.

#### Expected behavior
Here some patterns from some messengers:

1. Status mobile: `send` is not active when having only spaces in text box
2. Viber desktop: `send` is active when having only spaces in text box however hitting send does not actually send this message
3. Watsapp desktop: not able to enter spaces only within desktop. If i copypaste them and try to send - hitting enter does not send such message

#### Actual behavior

I am able to enter spaces only in the text box of Status desktop  (1x1 chat) and send button is enabled however hitting send does not send it actually. 

![image](https://user-images.githubusercontent.com/28752642/46413924-b2f8be00-c72a-11e8-884e-d3a87fce0abb.png)

 
### Reproduction

- Open Status desktop
- Add any contact
- Enter spaces only in the text field and hit enter

**Comment by EugeOrtiz** [comment]
I would go with the Status mobile option: do not activate the send button if only spaces (or until a letter is typed following those spaces).

**Comment by churik** [comment]
Closed in favor #6684 - same problem is described
