### ISSUE TITLE
"We were not able to decrypt your data" on start after using older build 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6112]
### Description

*Type*: Bug

*Summary*: the application cannot start with existing data after you once tried older build on it, fails with error on start "We were not able to decrypt your data". The only way to start app usage again is to clean up all data (https://docs.status.im/docs/build_desktop.html#Clean-up-data).

#### Expected behavior
can use app

#### Actual behavior
<img width="332" alt="errsdf" src="https://user-images.githubusercontent.com/4557972/46413258-374a4180-c729-11e8-8619-48af17e90400.png">

### Reproduction

- Download  current nightly, install it and create account
- Quit app
- Replace app with older build (for example [this one](https://drive.google.com/open?id=1PQK_QgEqfWvz4Ls2ZnxpJNbuhrNDe5nJ))
- Try to login with existing account
- Tap "Apply" on "We detected a problem with your encryption key"
- Quit app
- Download  current nightly, install it and start

### Additional Information

* Status version: nightly 03/10/2018
* Operating System: Mac OSx
* Log: 
[StatusIm.log](https://github.com/status-im/status-react/files/2442284/StatusIm.log)

* NOTE: I also had this issue when clicked on "Cancel" on "We detected a problem with your encryption key"  and then reinstall build. Couldn't replicate.

<blockquote><img src="/img/share.png" width="48" align="right"><div><strong><a href="https://docs.status.im/docs/build_desktop.html#Clean-up-data">Status, a Mobile Ethereum OS</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
I just lost all my account data (contacts, chats history) because of this issue :( I deliberately created backups of `~/Library/Application\ Support/StatusIm` to avoid it but it did not help. After installing some PR desktop build I got the decrypt error. When I restored my `StatusIm` folder from backup and installed latest nightly (or older nightlies) I still have the same error and need to restore my account from scratch to use Status :(

**Comment by mandrigin** [comment]
Do we use keychain to store encryption keys? Maybe that entry got corrupted somehow?

**Comment by cammellos** [comment]
I will take a look at this, a lot of this issue might be explained by running PR builds,probably the main cause for the test team, as generally those will not upgrade cleanly if it contains migrations (the encryption error is just a red-herring in most cases, any db error will show that pop up).
If someone encounters the same error, please save the logs before removing the directory, this PR adds some helpful logging that might help debug. https://github.com/status-im/status-react/pull/6326

**Comment by lukaszfryc** [comment]
@mandrigin @cammellos @churik any idea if this will also happen when upgrading from release builds?

**Comment by cammellos** [comment]
@lukaszfryc if you are debugging that, please PM I would like to try a few things!

**Comment by lukaszfryc** [comment]
not yet, but I will soon. I'll ping you!

**Comment by lukaszfryc** [comment]
I tested upgrade on Android device from 0.9.28 and 0.9.29 to recent develop (build with logs here https://github.com/status-im/status-react/pull/6326) and did not notice any issues. 

Also, I checked macOS upgrades between some of the latest nightlies (02cb5d to 21cda1 and to [the build with logs 870486-pr](https://github.com/status-im/status-react/pull/6326) but also could not replicate the db issue. @cammellos I will let you know if I encounter it in the future

**Comment by churik** [comment]
closed in https://github.com/status-im/status-react/pull/6864
