### ISSUE TITLE
Core public chats are pinned to the left side bar on Status Desktop

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6115]
### Description

*Type*: feature request

*Summary*: Status core team is on its way to migrate to Status Desktop as primary communication tool. In order to simplify desktop usage there is a suggestion to have channels (public chats) pinned at the left sidebar so user is not forced to join them manually each time nightly build is installed.

#### Expected behavior

we can add list of public chats to the list of available public chats in the `Add new` screen. Once you add them, they will persist until account db is erased (to the left panel).
If user is updating desktop (not reinstalling) - those chats will be there forever which is quite handy.

![image](https://user-images.githubusercontent.com/28752642/46417900-41713d80-c733-11e8-9cee-2da6ad63b870.png)

This option could be enabled in nightly builds only and disabled for public releases.

#### Actual behavior
I should join all the public chats each time manually. 

### List of chats to be added:

- core
- core-dapps
- core-wallet
- core-chat
- core-wallet
- core-releases
- core-infra
- designs
- status-hardwallet-lite
- test-team

UPD use this https://hackmd.io/-9Gez_q-TGSAGW82VJVv1Q?e

Anything else that i missed. Could be discussed (added later once requested)

**Comment by churik** [comment]
@asemiankevich WDYT about selecting pinned chats and have limit for 3 or 5 main chats selected by user instead of defined list?
In this case we can also enable it for public releases

**Comment by churik** [comment]
Irrelevant in terms of https://github.com/status-im/status-react/pull/7551
