### ISSUE TITLE
Some characters such as < & > are URL encoded on desktop

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6116]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use < & > and other characters.

### Description

Looks like a recent regression started URL encoding certain characters.

Eg typing `>` changes to `&gt;`

#### Expected behavior
Type `>` and see `>`

#### Actual behavior
Type `>` and see `&gt;`

### Reproduction
Type `>` and see `&gt;`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Desktop nightly
[comment]: # (Android or iOS.)
* Operating System: Mac desktop

**Comment by churik** [comment]
It should be fixed and it is actually fixed on build https://github.com/status-im/status-react/pull/6024#issuecomment-425058192
@rasom would you mind to take a look?

**Comment by rasom** [comment]
The reason is that fix was also added on `react-native-desktop` side and as we pull `master` branch it was upgraded silently.

**Comment by vkjr** [comment]
Sorry, my bad :( Didn't expect this fix to break anything, so pushed it without testing with `status-react`.
