### ISSUE TITLE
No validation is performed when using [done] or [enter] on device keyboard (password or name field)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6126]
### Description

*Type*: Bug

*Summary*: user can set password less than 6 characters if use `Done` or `Enter` buttons on device keyboard. 

#### Expected behavior

`Done` or `Enter` buttons on device keyboard are disabled until user enters not less than 6 characters in the password field

#### Actual behavior

1. I can create account with weak password (like `a` or ` ` or empty)
2. I can create account with less than 6 characters 
3. I can login and use this account created with weak password 
4. I can proceed without setting up name (name will be empty)

Same for recover flow.

![image](https://user-images.githubusercontent.com/28752642/46465463-500e3200-c7d1-11e8-9939-2dd0708cb7e7.png)

### Reproduction

- Open Status
- Tap create account
- Enter 111 in the password field and tap device `Enter` or `Done` button on keyboard

**Comment by churik** [comment]
Presented in PR https://github.com/status-im/status-react/pull/6041

**Comment by annadanchenko** [comment]
If we release with this bug then user can set a short password that will be invalid after the bug is fixed. So, after upgrade user will not be able to sign in. imo, we need to fix it before release. @chadyj
