### ISSUE TITLE
Can't install latest nightly package

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-react#6129]
Hi everyone,

quick heads-up as I ran into this yesterday... I had Status installed on my Android phone (**Google Pixel, Android 9**). I uninstalled it so I could reinstall the latest nightly. After I've downloaded the nightly package, I wasn't able to actually install it.

Normally when tapping an .apk package on Android, the OS will ask you whether it should install the app. In this case however, it simply opened the package and shows the files content. I've tried deleting and re-downloading it for a couple of times but can't find a way to actually make Android install the package.

I'm not sure if this is related to latest changes in the nightly package as I'm not fully aware how package installation is done. I'd assume it's the OS's job to figure that, but maybe this can also be controlled from within an `.apk` file.

Let me know if you need anything else.

**Comment by chadyj** [comment]
Dupe https://github.com/status-im/status-react/issues/6271
