### ISSUE TITLE
Create a screen with node information

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#6132]
### User Story

As a developer, I'd like to know more details about Ethereum node running inside the Status app.

### Description

*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: This is especially useful screen for developers and testers to have more insight into what's going on. 

For Status Desktop, I'd like to share my node to be used by others as a bootnode or static node in case the network block access to Status cluster IPs.

#### Expected behavior
When I open Profile > Advanced screen, I should be able to see a link to Node Information screen.

#### Actual behavior
There is no way to see any information about the p2p node running inside the Status app.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 
The "Node Information" screen should display:
- output of `admin_nodeInfo` nicely formatted,
- output of `admin_peers` nicely formatted,
- cluster config.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.29
* Operating System: Android/iOS and Desktop

**Comment by mandrigin** [comment]
fixed in https://github.com/status-im/status-react/pull/7556
