### ISSUE TITLE
Font on Linux is too big for UI elements

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6134]
### User Story

As a user, I want to see Status on my Linux the same way I see it on Mac OSx.

### Description

*Type*: Bug

*Summary*: fonts / labels are different on Mac OS x / Linux, so would be nice to have more attractive UI on Linux as well.
Most of the issues are related to different fonts on Mac OSx and Linux OS.

#### 1. Chat 

*Mac OSx:*
<img width="514" alt="123mac" src="https://user-images.githubusercontent.com/4557972/46472288-67571a80-c7e5-11e8-9241-b6db6136517e.png">

*Linux:*
<img width="514" alt="123" src="https://user-images.githubusercontent.com/4557972/46472293-69b97480-c7e5-11e8-9438-ceb7b9efdd65.png">
- [ ] 1) text like `gggg`, `fff` is cut in chat list
- [ ] 2) font for chat names in chat list is too big, so when it is bold (chat is selected), there is too little space between timestamp of last message an chat name
- [ ] 3) text sizes in input area for messages and in messages are different

#### 2. Add contact 
*Mac OSx:*
<img width="568" alt="4mac" src="https://user-images.githubusercontent.com/4557972/46472985-85257f00-c7e7-11e8-9b51-722ac740998f.png">

*Linux:*
<img width="512" alt="4linux" src="https://user-images.githubusercontent.com/4557972/46472972-776ff980-c7e7-11e8-822a-c9dccd472115.png">

- [ ] 4) text for button is too large, so `Join new chat` is splitted in two rows

#### 3. Profile
*Mac OSx:*
<img width="513" alt="mac5678" src="https://user-images.githubusercontent.com/4557972/46473536-32e55d80-c7e9-11e8-9429-8b2bd9da3b14.png">

*Linux:*
<img width="515" alt="linux5678" src="https://user-images.githubusercontent.com/4557972/46473469-f580d000-c7e8-11e8-85af-526685e4938d.png">

- [ ] 5) text is too large, when selected it is splitted in two rows
- [ ] 6) font size is too large
- [ ] 7) font size is too small
- [ ] 8) name is cut when edit, font size is too large
#### 4. Back up seed phrase

*Mac OSx:*
<img width="343" alt="mac" src="https://user-images.githubusercontent.com/4557972/46473897-35948280-c7ea-11e8-81f8-4842c9d6dcc6.png">

*Linux:*
<img width="346" alt="linux" src="https://user-images.githubusercontent.com/4557972/46473907-3b8a6380-c7ea-11e8-8d6a-50334a9975de.png">
- [ ] 9) `Wrong word` is overlapped with other labels

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 04/10/18
* Operating System: Linux Ubuntu 18.04

**Comment by EugeOrtiz** [comment]
We should be using Arial for Linux ( #4860 ) , @vkjr do you know which one is being used here? That impacts on the size and legibility.

**Comment by vkjr** [comment]
@EugeOrtiz, In code we have "Arial" set. 
But for macos we package `SFProText` font files together with app. And for linux we hope that `Arial` already exists on the user's computer. Maybe it doesn't?

```
(def fonts-macos
  {:default       {:font-family "SFProText-Regular"}
   :medium        {:font-family "SFProText-Medium"}

   :toolbar-title {:font-family "SFProText-Regular"}
   :monospace     {:font-family "RobotoMono-Medium"}})

(def fonts-linux
  {:default       {:font-family "Arial" :font-weight 400}
   :medium        {:font-family "Arial" :font-weight 800}

   :toolbar-title {:font-family  "Arial" :font-weight 400}
   :monospace     {:font-family "RobotoMono-Medium"}})
```

**Comment by churik** [comment]
Reproducible for Windows as well 
![status 2018-11-13 11 23 35](https://user-images.githubusercontent.com/4557972/48410635-75cb1700-e73f-11e8-9e92-05347faccc90.png)
![status 2018-11-13 11 24 42](https://user-images.githubusercontent.com/4557972/48410636-75cb1700-e73f-11e8-9bf4-4ee72d3b24ec.png)
![status 2018-11-13 11 25 16](https://user-images.githubusercontent.com/4557972/48410637-75cb1700-e73f-11e8-8e47-9fc27024325d.png)

**Comment by churik** [comment]
@vkjr any updates so far?

**Comment by vkjr** [comment]
@churik, not aware about work made in this area.

**Comment by xardinero** [comment]
Size also too big to access settings. 
![screenshot from 2019-01-10 10-10-11](https://user-images.githubusercontent.com/46549216/50943681-01eb8780-14c0-11e9-9d15-5fd904d52c36.png)

**Comment by xardinero** [comment]
Also in split screen on Linux isn't balanced.
![screenshot from 2019-01-10 00-37-44](https://user-images.githubusercontent.com/46549216/50943744-38c19d80-14c0-11e9-9464-5a3f9f915600.png)
