### ISSUE TITLE
No 'Seen' message status on sender side after message receiver read it in 1-1 chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6138]
**Type**: Bug

**Summary**: There is no 'Seen' status next to the message on sender side after message receiver read the message.

### Expected behavior
`Seen` message status displayed on sender side once the actual message is read by the receiver.

### Actual behavior
No `Seen` message status (Always 'Sent') displayed on sender side once the actual message is read by the receiver.

### Reproduction
* Open Status on Device1 and Device2
* Create Contact1 and Contact2 respectively
* Contact1 sends a contact request to Contact2
* Both contacts navigate to 1-1 chat screen
* Contact1 sends a text/emoji/request/send message

### Additional Information
Status version: Develop `0.9.29 (9888); node f3880f8f`
Operating System: Android and iOS

Logs:
Device1 (message sender): https://saucelabs.com/beta/tests/644db3aacfb54e059f0169c347d0a8a6/watch
Device2 (message receiver):  https://saucelabs.com/beta/tests/4b49593769834a8a9c947db2f2cb707e/watch

<blockquote><div><strong><a href="https://saucelabs.com/beta/tests/644db3aacfb54e059f0169c347d0a8a6/watch">Sauce Labs | Dashboard</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://saucelabs.com/beta/tests/4b49593769834a8a9c947db2f2cb707e/watch">Sauce Labs | Dashboard</a></strong></div></blockquote>

**Comment by yenda** [comment]
To discuss:
- are we still sending seen messages?
- should we actually send them?
- how could we give the user a choice?

**Comment by richard-ramos** [comment]
When working with `status-js` we noticed that MessageSeen  (#c5 tag) messages are being replied back for 1:1 messages, so they're still being sent. I think this should be an optional feature, due to possible metadata/privacy leak.

**Comment by corpetty** [comment]
I would like that as a profile preference to respond with a seen message.

**Comment by cammellos** [comment]
I believe they have now been removed as they were not used https://github.com/status-im/status-react/pull/7335 , we can probably start again a discussion on whether we want them or not and in which shape or form.

**Comment by churik** [comment]
Not relevant anymore
