### ISSUE TITLE
Public channels should be clickable 

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6139]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to share links to public channels so that others can easily join.

As a user, I want to click on public channel links in chats so that I can easily join.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Often someone will share a link on Status in a chat such as #status or #status-desktop to inform others about channels to join.  Currently the user has to copy the channel name, then go to ADD >> public chat, and paste the channel name in.  Instead lets make these links clickable so a user can simply click on a link and join the channel

#### Expected behavior
When typing #channel-name a the channel name will be hyperlinked and direct to the channel

#### Actual behavior
Channel names are not linked or clickable.

**Comment by chadyj** [comment]
Fixed in desktop https://github.com/status-im/status-react/pull/6174

Mobile still needs to be done

**Comment by janherich** [comment]
@chadyj I'm working on the feature for mobile as well, by unifying the text content handling among desktop/mobile (necessary prerequisite for mentions as well)

**Comment by janherich** [comment]
This should be closed as it's already implemented @chadyj

**Comment by chadyj** [comment]
Thanks @janherich!
