### ISSUE TITLE
Closing transaction details should navigate back to 1-1 chat if tx was opened from the chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6140]
### Description

*Type*: Bug

*Summary*: When a transaction details are opened by clicking on tx message in 1-1 chat, the back button redirects the user to the wallet tab. Instead, the user should be redirected back to the chat. 

### Reproduction

- Open 1-1 chat
- Receive a transaction
- Click on the transaction message to see the tx details 
- Tap `<` back button on screen (or device Back button if Android)

### Additional Information
* Status version: 0.9.28 (update: still reproducible with 0.9.33 develop)
* Operating System: Android, iOS

**Comment by Serhy** [comment]
#5967 related to this issue too

**Comment by lukaszfryc** [comment]
Yes it is.

**Comment by Serhy** [comment]
Still reproducible with 0.9.33 develop build.

**Comment by asemiankevich** [comment]
no transactions in chats now
