### ISSUE TITLE
Share link button in user's profile does not contain profile universal link

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6156]
### Description

*Type*: Bug

*Summary*: Comes from https://github.com/status-im/status-react/pull/5862. `Share link` in profile contains only public address, should be a universal link instead.

#### Expected behavior

- `Share link` button in my profile produces universal link to my profile that i could share. 
- `Share link` button in someone's profile produces universal link to my profile that i could share. 

https://get.status.im/user/CONTACT-ADDRESS

#### Actual behavior
Share link contains only contact address

### Reproduction

- Open Status
- Open profile
- Tap Share link -> copy -> paste the content to check it (for ex in 1x1 or public chat)

<blockquote><div><strong><a href="https://get.status.im/user/CONTACT-ADDRESS">View user CONTACT-ADDRESS profile in Status</a></strong></div></blockquote>

**Comment by chadyj** [comment]
@alwx Can we please get this fixed for the next release? 
cc @annadanchenko
