### ISSUE TITLE
0 amount for tokens in wallet when connected to Ropsten LES

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6159]
### Description
_Type_: Bug

_Summary_: When connected to Ropsten (LES), Wallet shows 0 for all tokens. It's probably because the local node is not fully synced. 

Logs:

* [geth.log](https://gist.github.com/dca5c5c13330a34c03bfb9656c9a942d)
* [logcat with node settings](https://gist.github.com/4b15ebe2784d607c612b0b9d5af155a9)

### Reproduction

* Switch to Ropsten (LES) in Networks
* Log in again and open Wallet

### Additional Information

* Status version: tested on https://github.com/status-im/status-react/pull/6088
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
Btw, tx history shows transactions correctly.

**Comment by asemiankevich** [comment]
what about ETH ? 
@mandrigin can we just bring the syncing indicator back? cause i think it is not an issue - node was not  synced

**Comment by lukaszfryc** [comment]
> Wallet shows 0 for all tokens

**Comment by lukaszfryc** [comment]
@asemiankevich yes, we will try to bring the sync indicator back:

<img src="https://user-images.githubusercontent.com/7532782/46533487-0d1d8e80-c8a5-11e8-8bc1-9f6c151ad214.png" width="200">

But, for now it will be simple solution mainly for testing/debugging

**Comment by Swader** [comment]
Keeping this alive.

**Comment by mandrigin** [comment]
LES is definitely not a high-severity issue

**Comment by churik** [comment]
No Ropsten (LES) in Profile > Network Settings anymore on nightky 25/02/2020.
Closing the issue.
