### ISSUE TITLE
Attach geth.log to Instabug reports

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6163]
### Description

*Type*: Feature

*Summary*: Status users can send us a bug report using Instabug integration. By default, Instabug attaches console logs to each report. But, we often miss "geth.log" (logs from status-go layer) that are very helpful for debugging issues. To solve that, we could use `Instabug.addFileAttachment(fileUri, "file_name.txt");` option from [Instabug library](https://docs.instabug.com/docs/android-attachments) and attach "geth.log" with every user report. 

Also, we should let user know what data is attached (console and geth logs). But, I haven't found any way to customize the Instabug popovers (https://docs.instabug.com/docs/android-design). 

#### Expected behavior
"geth.log" is also attached to Instabug reports. 

#### Actual behavior
Currently, only only console logs are attached.

### Additional Information
* Status version:
* Operating System: Android, iOS

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://docs.instabug.com/docs/android-design">Design</a></strong></div><div>This section covers how to customize the SDK look to match your app's design.</div></blockquote>

**Comment by oskarth** [comment]
Are we sure there's no private information in these logs?

**Comment by lukaszfryc** [comment]
I think so. @adambabik?

**Comment by adambabik** [comment]
I think `geth.log` was deliberately disabled on releases because we were afraid of data it collects and stores on a disk in an unencrypted way. I wouldn't say for 100% it does not collect private information.

**Comment by chadyj** [comment]
Closing since Instabug was removed.
