### ISSUE TITLE
Don't display login screen when logging in automatically

### ISSUE THREAD

**Issue by saskakol** [status-im/status-react#6165]
### User Story
As a user, I want to have the login screen removed when logging in automatically so that the login flow is clearer and less confusing.

### Description
_Type_: Feature

_Summary_: When logging in to Status with the "remember password" option checked, the app briefly loads the login screen before moving on to the chat screen. Even at the moment, it doesn't stay for long, but still I frequently think that the automatic login didn't work, when in fact it was just loading. I propose that instead of showing the login screen, either nothing at all or a dedicated loading screen should be shown. In my opinion, this would make the login flow feel a bit faster, and make it a bit clearer.

#### Expected behavior
A loading screen (or alternatively a blank screen) would be shown when logging in automatically.

#### Actual behavior
The login screen is shown for about a second while logging in.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status with automatic login enabled.
* Observe, that the login screen is briefly shown before moving onto the chat screen.

### Solution
_Summary_: 

* [ ] Add dedicated loading screen when logging in automatically.

### Additional Information

* Status version: 0.9.29
* Operating System: iOS

**Comment by hesterbruikman** [comment]
Still valid in v1.3
