### ISSUE TITLE
Contact stuck on login screen navigating from universal link with contact code to closed app

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6166]
***Type***: Bug

***Summary***: App is closed. When contact navigates from universal link the app opens and contacts offered to login. However, once "Sign In" button tapped contact stucks on login screen. 
There is 'Other accounts' option is available for tap and once tap it - you return back to 'Sign in to Status' page with no account displayed.

If autologin enabled for the account there is an infinite spinner on blank screen will be present.

**NOTE**: it's all fine when navigate to universal link while app is opened and you loged into account.

#### Expected behavior
After login user appears on respective screen where universal link leads: 
* If it's Dapp universal link > `Open in Status` - `Open in web browser`  pop-up on the Home screen 
* If it's user profile link -> user profile screen of the contact
* If it's user own profile universal link -> Profile tab opens
* If it's public chat universal link -> public chat screen 

#### Actual behavior
App stuck on login page when login into account from universal link

<img width="292" alt="screen shot 2018-10-05 at 18 20 15" src="https://user-images.githubusercontent.com/8749671/46544105-554fa780-c8cb-11e8-89e6-bc53e8aa7809.png">

### Reproduction

- Install Status and create new account. 
- Close Status app
- Open `https://get.status.im/user/0x049191be3d0b0258732a4c3bd66d2e68cf7e536a0a975fd501a3265cba9ff5f7c78f51345417e42f56e16926b685f99448ac05b9608b0d42cf65ee58853f104696` in external browser -> tap `Open in Status`
- On login page enter the valid login and tap 'Sign In'
**Actual result:** Empty login screen like on screen show above is shown

- Close Status app and log in to account with 'Autologin' set to 'ON'
- Close Status app again
- Open `http://get.status.im/chat/public/status` in external browser -> tap `Open in Status`

### Additional Information
* Status version: Develop/Release 0.9.33
* Operating System: Android and iOS

**Comment by SlizkovaGanna** [comment]
This issue is still valid for mobile (specifically).
If, after you are returned to login screen, you try to re-login with an invalid password, the app crushes - both on iOS and Android

**Comment by Serhy** [comment]
Updated build version (happens at the moment with v0.9.33) and scenario with autologin included which is fails

**Comment by Serhy** [comment]
Can't reproduce anymore with 0.10 release. Closing this issue.
