### ISSUE TITLE
Display .eth or other domain rather than IPFS redirect 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6169]
### User Story

As a user, I want to receive permission requests from a specific URL—not `ipfs.infura`—so that I am aware of who is requesting my data.

### Description

*Type*: Feature

*Summary*: Rather than displaying a hash for IPFS-hosted DApps in the browser, keep the human readable format of the redirected domain. 

#### Expected behavior
Instead of `https://ipfs.infura.io/ipfs/QmYhTGg88WvJh9K86m3JYow3QxdXMkgk8stkTDqy87joZn/`, for example, I would see `statusnames.eth` in the URL bar. Any requests from this DApp would come from `statusnames` (if not a default DApp in Status). 

#### Actual behavior
Currently, the browser displays the IPFS hash a domain is redirected to, and this in turn is used when the DApp requests user permissions for something. 

### Reproduction
Navigate to `vote.status.im` in any browser.

**Comment by jeluard** [comment]
The eventual website path should be displayed too. We might want to display associate hash after a long press on the bar.

@denis-sharypin Could you provide some design guidance?

**Comment by denis-sharypin** [comment]
@jeluard , @rachelhamlin  I had this in mind. wdyt?
<img width="841" alt="screenshot 2018-10-08 09 09 45" src="https://user-images.githubusercontent.com/6559881/46595691-ed22e080-cad9-11e8-9287-e7d948e49518.png">

**Comment by jeluard** [comment]
@denis-sharypin Looks great! Can you make sure only the website path is visible? i.e. no `https://ipfs.io/ipfs/Qmxxxx/`but only what comes next? So  `/`, `/index.html`, `/path/document.html` ..

**Comment by rachelhamlin** [comment]
@jeluard why did we want only the path to be visible? Did you mean to have the path following `denis.stateofus.eth`?

**Comment by jeluard** [comment]
@rachelhamlin In case of a website hosted on IPFS there is no real URL. The one we have right now (infura based) and kind of implementation details and I don't think we should show it.

So the only interesting part left is the current path the user is navigating (that's `index.html`, `/folder/user.html?key=value`, ..)

**Comment by rachelhamlin** [comment]
After discussing this in Status, I think that if we want to display file paths, it should come after the ENS name. For example:
`statusnames.eth/page.html`

**Comment by rachelhamlin** [comment]
Curious: what happens when I interact with the browser bar in this mockup? It has two lines. Which text am I editing when I tap it? Should there be some animation to minimize one line?

**Comment by flexsurfer** [comment]
let's make it simple, show only ens, and if you click on it show full url

**Comment by rachelhamlin** [comment]
That works @flexsurfer!

**Comment by flexsurfer** [comment]
@rachelhamlin `Reproduction Navigate to vote.status.im in any browser.` , but `vote.status.im` is regular dns, it's not ens, redirect for it implemented on `status.im` side, we don't do any redirects for it in the status browser

**Comment by rachelhamlin** [comment]
Gotcha @flexsurfer so we can only handle domains that the browser redirects, aka ENS addresses?
