### ISSUE TITLE
Get rid of ubuntu_server

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#6175]
Embed JavaScript engine inside react-native-desktop and eliminate ubuntu_server.

It makes a lot sense to try to figure out how is it possible to use WebEngine modile from Qt. If it doesn't work, then investigate embedding of Node.JS, and, finally, we can stop with integration of JavaScriptCore engine (mobile react-native uses it for iOS and Android, so, why not to use it for Desktop as well, + it's mostly already supported by react-native-desktop and worked fine on Linux)

**Comment by chadyj** [comment]
Hey @MaxRis how is the progress on this issue?

**Comment by maxhora** [comment]
@chadyj was not able to really start this because of issues with desktop notifications, supposing to work on it shortly.

**Comment by chadyj** [comment]
Ok I'll move it out of `in progress` for now

**Comment by maxhora** [comment]
1st step is to investigate possibility to execute custom JS script by Qt-only tools (WebEngine Qt's module)

**Comment by maxhora** [comment]
Was able to use Qt's WebEngine to run JS test app https://github.com/status-im/react-native-desktop/tree/feature/webengine-executor
Blocking thing is realm module used in status-react. Support of WebEngine, probably, will require too much effort.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-desktop">status-im/react-native-desktop</a></strong></div><div>A Desktop port of React Native, driven by Qt, forked from Canonical - status-im/react-native-desktop</div></blockquote>

**Comment by maxhora** [comment]
Update: Extending of realm backend to support qwebengine is in progress.

Update [18.11.2018]. QWebEngine realm support is going to be out of realm [philosophy's](https://realm.io/blog/introducing-realm-react-native/) scope, because QWebEngine doesn't provides direct native API and creation of JS objects should be done via additional QWebChannel layer. At the moment the outcome performance is not clear yet.
Update [22.11.2018]. Custom Realm QObject consumed to WebEngine via QWebChannel.

- [x] Compile realm sources with dummy interfaces for qwebengine platform
- [x] Setup QWebChannel to have ability of setting and communication with custom QObject to/from JavaScript
- [ ] Implement qwebengine platform backend cpp classes to fulfill realm usage by status-react

Work related branches:
[react-native-desktop](https://github.com/status-im/react-native-desktop/tree/feature/webengine-executor)
[realm](https://github.com/status-im/realm-js/tree/feature/qwebengine-support)
[status-react](https://github.com/status-im/status-react/tree/feature/webengine-executor)
