### ISSUE TITLE
Stop/pause Status node when the app goes to background on Android

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6183]
NB! this issue needs to be researched and verified on very specific Android phones

### User Story

As a user, I don't want to waste my precious batttery life for network
connections with Whisper peers if the node will be restarted anyway.

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Currently, when user minimizes the app on Android, Status Node doesn’t stop (it
runs as a background service), so it keeps all connections to whisper peers
alive. That keeps the phone to go to low-power mode.

1. That actually wastes some battery on Android;

1. Different “battery monitors” for Android complain about that.

The idea is to stop node (or at least pause it’s network activity) when the app
is in background for a certain amount of time on Android.

**Comment by Swader** [comment]
Unclear if resolved.
