### ISSUE TITLE
Show more link is not shown in public chats when having long messages (desktop)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6191]
### Description

*Type*: Bug

*Summary*: `Show more` functionality is missing on Status Desktop, that's why long messages are not collapsed and are being shown as is which is not very comfortable. Also we want to align a bit functionality across the platforms. This functionality is present on mobile, so would be nice to have it on desktop as well.

#### Expected behavior

- long messages are collapsed under `Show more` link (public chat)
- `show more` link is clickable. Upon clicking message is expanded to its full content. Another click collapses the message
- message is autocollapsed when having 50 lines (? @errorists please provide some designs here)

#### Actual behavior
`Show more` is not implemented on desktop

### Reproduction

- Open Status
- Send long message (50 lines?) to public chat
- Pay attention to message

**Comment by Swader** [comment]
No longer an issue.
