### ISSUE TITLE
Disable Realm Mixpanel use on build machines

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6200]
*EDIT*
How to disable Realm Analytics: https://github.com/realm/realm-js/issues/769

---

In https://github.com/status-im/status-react/pull/5479 we disabled Realm's Mixpanel analytics, but we got a [report](https://github.com/status-im/status-react/issues/5465) that this is still happening.

Roman suggested we need to configure some env var on the build machine.

**Comment by mratsim** [comment]
Screenshots:

![2018-10-08_16-47-15](https://user-images.githubusercontent.com/22738317/46662247-3303a580-cbbb-11e8-954d-ad12b87e8809.png)
![2018-10-09_11-43-45](https://user-images.githubusercontent.com/22738317/46662253-3565ff80-cbbb-11e8-8fb6-db8843a9458b.png)

**Comment by yenda** [comment]
Can we prioritize this. Privacy is one of the major concerns of our initial user base and this is a serious problem

**Comment by chadyj** [comment]
cc @jakubgs

**Comment by jakubgs** [comment]
I'll take a look at this today, though not sure what this is.

**Comment by mandrigin** [comment]
@jakubgs I think that is what you want to do exactly: https://github.com/realm/realm-js/issues/769

**Comment by chadyj** [comment]
We did it here https://github.com/status-im/status-react/pull/5479/files
But might have been missed with the Jenkins clean up?

<blockquote><img src="https://avatars2.githubusercontent.com/u/2364994?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/5479">[#5465] disable realm's mixpanel analytics by rasom · Pull Request #5479 · status-im/status-react</a></strong></div><div>fix #5465
status: ready</div></blockquote>

**Comment by jakubgs** [comment]
The only thing related I can see on `macos-02` is this stuff:
```
administrator@macos-02.ms-eu-dublin.ci.misc:~ % locate -i realm-js                 
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.2
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.2/Realm-JSONAPI.podspec.json
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.3
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.3/Realm-JSONAPI.podspec.json
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.0
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.0/Realm-JSONAPI.podspec.json
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.1
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.1/Realm-JSONAPI.podspec.json
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.2
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.2/Realm-JSONAPI.podspec.json
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.3
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.3/Realm-JSONAPI.podspec.json
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.4
/Users/administrator/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.4/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.2
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.2/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.3
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.0.3/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.0
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.0/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.1
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.1/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.2
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.2/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.3
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.3/Realm-JSONAPI.podspec.json
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.4
/Users/jenkins/.cocoapods/repos/master/Specs/5/0/5/Realm-JSONAPI/0.1.4/Realm-JSONAPI.podspec.json
/Users/jenkins/workspace/status-react/combined/desktop-macos@2/.git/logs/refs/remotes/origin/feature/upgrade-realm-js
/Users/jenkins/workspace/status-react/combined/mobile-ios/.git/logs/refs/remotes/origin/feature/upgrade-realm-js
/Users/jenkins/workspace/status-react/combined/mobile-ios@2/.git/logs/refs/remotes/origin/feature/upgrade-realm-js
/Users/jenkins/workspace/status-react/upload_release_ios/.git/logs/refs/remotes/origin/feature/upgrade-realm-js
/Users/jenkins/workspace/status-react/upload_release_ios/.git/refs/remotes/origin/feature/upgrade-realm-js
```

**Comment by jakubgs** [comment]
I don't get this issue, the report @chadyj linked is from August 13th. Roman's fix was merged on the 14th.
Are we sure the report isn't just from an old verison of the app?

**Comment by chadyj** [comment]
It was seemingly fixed in the linked issue, but has reappeared in newer builds.
@rasom Suggested it could be the same/similar Realm issue, but it might be something else as well. ¯\_(ツ)_/¯

**Comment by oskarth** [comment]
Would it be worthwhile to revisit getting rid of Realm completely?

**Comment by annadanchenko** [comment]
See same issue on today's nightly build for Windows (ubuntu-server.exe is trying to connect to api.mixpanel.com )
