### ISSUE TITLE
Blank screen when creating new group chat but not having any contacts 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6201]
### Description

*Type*: Bug

*Summary*: When here are no contacts but user wants to start a new group chat, he ends up on a blank screen.

#### Expected behavior
New group chat screen is shown with empty state saying that there are no contacts to start a group chat with.

#### Actual behavior
Blank screen is shown:

<img src="https://user-images.githubusercontent.com/7532782/46605038-6f220200-caf8-11e8-8cbb-bb4e9e326490.png" width="200">

### Reproduction

- Install app
- Open it and try to create a new group chat 

### Additional Information
* Status version: introduced on purpose by https://github.com/status-im/status-react/pull/6142
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@errorists could you link a design for the empty state? I can't find it in [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=227%3A320) project.

**Comment by lukaszfryc** [comment]
Marking as `high-priority` as I think we can't release group chats with that blank page. We need to have some empty state.

**Comment by errorists** [comment]
It's over here [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=469%3A243). The 'invite friends' button there does the same thing as tapping '+' in Home and choosing Invite Friends.

**Comment by lukaszfryc** [comment]
It's done already.
