### ISSUE TITLE
No checkbox when selecting group chat members

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6204]
### Description

*Type*: Bug

*Summary*: There are no checkboxes while creating group chat. I don't know if a contact was selected if I clicked on it:

<img src="https://user-images.githubusercontent.com/7532782/46605147-d2ac2f80-caf8-11e8-83c3-423661a050b6.png" width="500">

Mobile app has the check mark.

### Reproduction

Create group chat on the desktop app

### Additional Information
* Status version: introduced by #6142
* Operating System: Desktop

**Comment by churik** [comment]
@EugeOrtiz 
can you provide design for this issue?

**Comment by EugeOrtiz** [comment]
@churik is all in [this issue](https://github.com/status-im/status-react/issues/6607). It includes more fixes.

**Comment by churik** [comment]
сlosed in favor of #6607
