### ISSUE TITLE
App navigates back to chat screen when group chat member is added or removed

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6206]
### Description

*Type*: Bug

*Summary*: When group chat member is added or removed, the app should navigate back to **the group info** screen. Instead, it navigates back to the chat which is not expected (from pov of views hierarchy).

### Reproduction

- Create group chat
- Open the group info and add a member 

### Additional Information
* Status version: introduced by #6142
* Operating System: Android, iOS, Desktop

**Comment by lukaszfryc** [comment]
Still the case. Low prio though.

**Comment by yenda** [comment]
@cammellos I add you to this one as well though low priority
