### ISSUE TITLE
Add option to leave group chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6208]
### Description

*Type*: Feature

*Summary*: 

Both group chat admin and members should be able to leave the chat to not receive messages anymore. There should be "Leave chat" option in chat menu as well as the group chat info screen. When a member leaves the chat, the admin can add him/her back. 
 
#### Expected behavior
- When chat is removed, it does not mean that the member left it. The chat should reappear when new message is received
- Users should have "Leave chat" option to leave the chat and not receive messages anymore unless they are added back to the chat by the chat admin 

#### Actual behavior
When member removes a chat, it also makes him leave the chat.

### Additional Information
* Operating System: Android, iOS, Desktop

**Comment by lukaszfryc** [comment]
@chad @cammellos should admin be able to leave the group chat? I think it should, otherwise he will always receive messages from the group chat he is not interested in anymore.

**Comment by cammellos** [comment]
@lukaszfryc I believe they should, but at the same time we don't want to leave a chat orphaned (no admin), so I would say to iterate incrementally:
1) Allow admin to make other members admin
2) Allow admin to leave chat if there is at least another admin

**Comment by lukaszfryc** [comment]
Sounds good @cammellos! 

Maybe @errorists could help us with design here. Apart from allowing for multiple admins in group chats, I think we also need designs for cases like: user was removed from a group chat and will not receive any new message, new user was just added to a group chat. @errorists should I create issues for it in https://github.com/status-im/design?



<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/design">status-im/design</a></strong></div><div>Contribute to status-im/design development by creating an account on GitHub.</div></blockquote>

**Comment by lukaszfryc** [comment]
For now, we are collaborating on designs with @errorists here: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=227%3A320

<blockquote><img src="/file/aS1ct66VQ6V0cio7vSqS8UoG/thumbnail?ver=NSiv2SZCnXH9M4xFaw0zBi" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by lukaszfryc** [comment]
Closing this issue as it is already implemented. Currently, a user can leave group chat by simply deleting it. She will not receive messages anymore and can be added back to the chat by the admin.
