### ISSUE TITLE
Interpolation in the phrases better than naive concatination

### ISSUE THREAD

**Issue by rolandkofler** [status-im/status-react#621]
In German you order the sentence differently

        "vor 1 Minute"
not 
        "1 minute ago"

https://github.com/status-im/status-react/blob/develop/src/status_im/translations/de.cljs#L57

So the strategy for I18n should be to always inerpolate the prases, e.g. "{{value}} minute ago", "vor {{value}} Minute".

**Comment by agnivalent** [comment]
Hello!
I've added a format for this type of sentences:
```clojure
:datetime-ago-format  "{{number}} {{time-intervals}} {{ago}}"
```
This is the template for English locale, and translations will fall back to that by default. That corresponds to "1 minute ago" order.

However, if there's a different order for some language, one can override this template, for example for German and Spanish:
```clojure
:datetime-ago-format  "{{ago}} {{number}} {{time-intervals}}"
```
This corresponds to "hace 1 minuto", "vor 1 Minute". There are probably more languages like that, but I don't know those.
