### ISSUE TITLE
'Unknown' username on user Profile for contact who received message with no contact-request 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6210]
***Type***: Bug

*Summary*: When contact receives a message with no contact request we still offer 'Add to contacts' option. However, on user Profile screen such contact username displayed as `Unknown`. 
In the case I tap 'Add to contacts' and 'Send message' from this profile, - the 1-1 chat with `Unknown` user created.
Please see steps to reproduce to see when it's possible for contact to receive a message without contact request.
**Note:** It's all fine on mobile app.

#### Expected behavior
No errors when contact adds a new contact, even there was no contact request.
Default three-words username is displayed on Profile screen for user who received a message without contact request

#### Actual behavior
Default contact name is `Unknown` when you look at the contact profile who didn't sent contact request.
<img width="1011" alt="screenshot 2018-11-30 at 16 06 49" src="https://user-images.githubusercontent.com/8749671/49294461-b35bce00-f4bb-11e8-9c5f-dbe4a28cd4ae.png">

### Reproduction from scratch:

1) Open Status on Device 1 (mobile app) and Device 2 (desktop app)
2) Create new account on Device1 (Contact1) and new account on Device2 (Contact2)
3) Join some unique public chat (e.g. blahuniquesquirrel) with both contacts
4) Contact2 sends a text message in public chat
5) Contact1 sees the message and taps Contact2's user icon to navigate to profile screen
6) Contact1 taps Send transaction option (NOTE: if #6895 is fixed - then further steps may need to be updated)
7) Contact1, - from 1-1 chat sends a message (doesn't matter transaction as the option offered or text message)
8) Contact2 receives message from Contact1 and navigates to it's Profile screen.
**Actual result:** Unknown username is displayed.
**Expected result:** Default three-words username of the Contact1 displayed.
9) Contact2 tap `Add to contacts`
10) Contact2 taps `Send message`
**Actual result:** New 1-1 chat with Unknown user created. Any message sent in this unknown chat are lost in space.
**Expected result:** Contact2 redirected to 1-1 chat with Contact1 

### Additional Information
* Status version: Develop `8ee407b56` (nightly develop build 29th of Nov 2018)
* Operating System: MacOS

**Comment by churik** [comment]
Still reproducible. There is no popup with `contact.whisper-identity must be of type 'string' got 'null' `, but still can see `Unknown` in user profile.

**Comment by chadyj** [comment]
Still reproducible? @churik @Serhy

**Comment by Serhy** [comment]
@chadyj Yes, it is.
So original steps from description are not reproducible anymore. I suspect this is because messages *and contact-request* are received from mailservers after account recover (some time ago, when this issue originally noticed and created we did not send requests for history for the new messages after account recover)

At the moment there are two use cases which can lead to 'Unknown' contact name in User profile on desktop app. First scenario we need to confirm (it require to wait 24h+) and second scenario gives ability to reproduce right away.

### Steps to reproduce #1:

1) Open Status on Device 1 (e.g. mobile app), Device2 (e.g. another Mobile App) and on Desktop app
2) Create new account on Device1 (Contact1)
3) Recover an account on Device2 (Contact2): (e.g. `foot code blue abandon system veteran rare broom satisfy quit aerobic final`)
4) Contact1 adds a new contact (Contact2) and sends a text message.
5) Contact2 receves message from Contact1, sees 'Add to contacts' option. Contact2 tap 'Add to contacts'
6) Contact2 waits >24h (this is offline inbox timing interval we request message history)
7) Contact2 recovers account on Desktop app (to recover `foot code blue abandon system veteran rare broom satisfy quit aerobic final` for our example)
7) Contact1 from mobile app sends a text message to Contact2
8) Contact2 on Desktop app navigates to Profile page of the Contact1

### Steps to reproduce #2:

1) Open Status on Device 1 (mobile app) and Device 2 (desktop app)
2) Create new account on Device1 (Contact1) and new account on Device2 (Contact2)
3) Join some unique public chat (e.g. `blahuniquesquirrel`) with both contacts
4) Contact2 sends a text message in public chat
5) Contact1 sees the message and taps Contact2's user icon to navigate to profile screen
6) Contact1 taps `Send transaction` option (NOTE: if #6895 is fixed - then further steps may need to be updated)
7) Contact1, - from 1-1 chat sends a message (doesn't matter transaction as the option offered or text message)
8) Contact2 receives message from Contact1 and navigates to it's Profile screen.
**Actual result:**  Unknown username is displayed. 
**Expected result:** Default three-words username of the Contact1 displayed. 
9) Contact2 tap `Add to contacts` 
10) Contact2 taps `Send message`
**Actual result:** New 1-1 chat with `Unknown` user created. Any message sent in this unknown chat are lost in space. 

I'm updating the description and title of the issue to show relevant data.

**Comment by SlizkovaGanna** [comment]
Retested on the last nightly from 03/12/2018 (after https://github.com/status-im/status-react/pull/6671 was merged) for Scenario #2 - it does not reproduce.
Tested for scenario #1 and will update this comment in 24 hours

**Comment by churik** [comment]
is not reproduced anymore
