### ISSUE TITLE
Run several Status Desktop builds simultaneously

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#6213]
### User Story

It would be nice to be able to run several Jenkins builds simultaneously on the same machine. For instance, this would help QA team a lot.

### Description
A possible scenario is simultaneous usage/testing of stable, nightly and PR builds.

Note that this is different from https://github.com/status-im/status-react/issues/5581, as it implied using dev builds together with Jenkins builds, not 2 Jenkins builds simultaneously.

### Solution
Each instance of Status Desktop has to use unique values for:
  - Node.js port
  - Status node port
  - Status node datadir
  - App bundle name

A possible solution would e.g. involve modifying Jenkins so that a build configuration can be selected from a list of hardcoded options. There must be some better solutions though.

**Comment by chadyj** [comment]
I'd be happy just for be running one nightly/stable version, and 1 build downloaded from PR's for testing without the risk of messing up my main installation.
