### ISSUE TITLE
Name of previous user is shown in chat replies in message input area if you replace message for reply

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6214]
### Description

*Type*: Bug

*Summary*: when you are going to replace message for replying (from user who is added to your contact list) by the message from other user (who is not added to your contacts),  name + picture of the previous user is shown instead of new name.
On desktop issue is more visible because you can click on message to reply.

#### Expected behavior
name is replaced

#### Actual behavior
right is marked green
<img width="159" alt="wr_name" src="https://user-images.githubusercontent.com/4557972/46670416-d0ba9d00-cbda-11e8-9db9-2bcb19556742.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join any public chats
- Add any user to contacts
- Tap on message owned by this user, select Reply
- Tap on message  owned by another user (who is not is your contact list), select Reply

### Additional Information
* Status version: nightly 09/10/2018
* Operating System: Android, iOS, Desktop

#### Logs

* TF session: https://app.testfairy.com/projects/4803622-status/builds/8619145/sessions/4403534867/?accessToken=R7r3QFIVHNGsj-3G-s4p7k6zOX4

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8619145/sessions/4403534867/?accessToken=R7r3QFIVHNGsj-3G-s4p7k6zOX4">TestFairy: Status 0.9.29 (10032) @2018</a></strong></div></blockquote>

**Comment by yenda** [comment]
@churik is this still an issue?

**Comment by churik** [comment]
@yenda Yes, still an issue
