### ISSUE TITLE
Desktop scrollbar support

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6215]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see a scrollbar in chats so that I can visually see my scroll position in a long chat.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Desktop chat's are missing the standard scrollbar's shown on the right side of the window. These help UX by allow users to see how long a chat is, and give them a sense of their chat scroll position.

#### Expected behavior
System scrollbar shown in chats

#### Actual behavior
No scrollbar

**Comment by churik** [comment]
It is duplicate of https://github.com/status-im/status-react/issues/5447, no?

**Comment by chadyj** [comment]
Dupe!
