### ISSUE TITLE
Strange behaviour with names

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#622]
OS: Android
Phone: Nexus 6
Version: 7.0

The first two times that I tried to set my name in the profile page everything worked correctly, but the name reverted to one of the automatically generated random ones within a minute.

Third time after setting and it seems fine now. Has stayed to what I set it for the past hour. Other users (iamjam) also reporting strange behaviour.

The whole edit page has done some strange things. When trying to set a status, it would exit the keyboard pop up after hitting each letter. I went back out into chats and then returned to the profile page and then it worked fine. 

It might be worth thinking of a modal popup for the actual editing rather than the flow that happens now as I found it a bit counter-intuitive the first time round.

Sorry that there are no screenshots, will do better next time on that front.

**Comment by rasom** [comment]
@annadanchenko can this bug be reproduced?

**Comment by annadanchenko** [comment]
@rasom can't reproduce. Never seen it on my Galaxy devices or as Instabug reports from other users.
