### ISSUE TITLE
Everything below the first line of text in a message input box is gone after switching to a different chat

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6222]
Description

Type: Bug

Summary: When a user inputs a big amount of text, that consists of more than one line, switches to a different chat, and comes back - all besides that firs line of text is not displayed until you click on the area where it's supposed to be.

Expected behavior

There should be no issues with how text is displayed

Actual behavior

All text besides the firs line of text, is not displayed until you click on the area where it's supposed to be

Reproduction

**Steps to reproduce:**
1) Open Status desktop
2) Go to 1-1 chat
3) Input a long amount of text, so that it forms more than 1 line in the input message box
4) Switch to a different chat for about 3 seconds
5) Go back to the previous chat and check out how your input area is displayed
Note: After you click on the area where the rest of your message is supposed to be, it is displayed.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/43638377/46678301-05cfeb00-cbed-11e8-8ebb-6e138af9767d.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/43638377/46678351-2009c900-cbed-11e8-9247-7f648575edae.png">

Additional Information:

Status version: nightly 09/10/2018
Operating System: Mac Sox

**Comment by churik** [comment]
@SlizkovaGanna cannot reproduce it on nightly 30/11/2018. Can you recheck it and close if it is not relevant?

**Comment by SlizkovaGanna** [comment]
Does not reproduce any longer.
Checked on Mac and Linux.
Checked on nightly from 03/12/2018.
