### ISSUE TITLE
Add custom tokens to wallet

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6225]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to add custom tokens that are not available in Status so that I can see my full token portfolio.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
Status has a fixed list of tokens. This is a problem if a user possesses a token that isn't in the list as it can cause confusion because the user expects their assets to be shown. It has results in numerous instabug reports.

The only way to remedy this is for users to submit a Github Pull Request asking for the token to be added.

Instead, we can give users control and let them add their own tokens. We need to do this in a way that can mitigate any phishing or security concerns.

#### Expected behavior
User goes to Wallet, Manage Assets, then `Add custom token` (or Plus, etc)

#### Actual behavior
No tokens can be added.

### Solution

User goes to Wallet, Manage Assets, then `Add token` (or Plus, etc)

Then the user can enter a token address, token symbol, decimals of precision.

Perhaps custom tokens can also be differentiated in the UI so if a user adds `SNT` it would be shown like `SNT custom`.

Design and copy needs to be explored.  

### Additional Information
* Platform: Mobile

cc @errorists @obi2020 @hesterbruikman @PhilipandWu @goranjovic

**Comment by chadyj** [comment]
cc @corpetty for security related input

**Comment by goranjovic** [comment]
The user only needs to add the contract address. We can get the token name, symbol and number of decimals ourselves - these should not be editable by the user (especially not the decimals).

We can validate if contract address is in the right format syntactically. We may also be able to validate if the contract represents something that could be ERC-20 (i.e. if the info with token name, symbol and decimals is missing, something is probably not right). We could also think about allowing only checkummed addresses to be entered, to avoid any chances of accidental copy paste errors or typos.

User might need to add the logo. Our default sizes are 40x40, 80x80 and 120x120.

Custom token info (address and logo) would be stored locally, so this data won't survive account recovery. What that means is that if you add a custom token, then receive some of those tokens and delete/recover your account it will appear as if your custom tokens are "lost". At least until you add the same custom token again.

**Comment by chadyj** [comment]
> The user only needs to add the contract address

Ok cool. The other info was from other wallet example.

> User might need to add the logo. Our default sizes are 40x40, 80x80 and 120x120

Let's skip this as both a way to reduce scope, and a way to differentiate custom tokens.

**Comment by denis-sharypin** [comment]
@chadyj @goranjovic  Please take a look at the solution I'm proposing https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet_Source-of-Truth?node-id=160%3A5124

<blockquote><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet_Source-of-Truth?node-id=160%3A5124">Figma</a></strong></div></blockquote>

**Comment by denis-sharypin** [comment]
Feedback from the wallet meeting where I presented those designs:
— create a custom image for a custom token that should be different from our current default picture for tokens 
— provide functionality to edit token address and delete it from the list

**Comment by chadyj** [comment]
Looks great @denis-sharypin

**Comment by denis-sharypin** [comment]
Updates https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet_Source-of-Truth?node-id=160%3A3954

<blockquote><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet_Source-of-Truth?node-id=160%3A3954">Figma</a></strong></div></blockquote>

**Comment by chadyj** [comment]
Dupe of https://github.com/status-im/status-react/issues/6939
