### ISSUE TITLE
API: requesting to connect to a node that is not available crashes the application

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-react#6228]
### User Story

As a Developer I want to specify automatically which network status should connect to so that I can easily develop dapps.

### Description

*Type*: Bug

Attempting to connect to an invalid address or a valid address that the rpc node is not available. (or wrong port etc.. or blocked by cors) crashes.

#### Expected behavior
Should return an error in the json response.

#### Actual behavior
Crashes the application

### Reproduction

1.
```
POST http://{{PHONE_IP}}:5561/network
{
	"name": "mynetworkname",
	"url": "http://192.168.1.1:9946",
	"chain": "mychainName",
	"network-id": 1337
}
```
2. take the returned id and try to connect
```
POST http://{{PHONE_IP}}:5561/network/connect
{
	"id": "1539122073181c7dbba2567895fbf95c642dba6204a08"
}
```
result: application crashes

### Solution
*Summary*: 

- [ ] Should return an error in a json response that it couldn't connect to the node
- [ ] Should also return an error / not crash if the node is available but the request got rejected due to CORS

### Additional Information
* Status version: 0.0.29 (9846)
* Operating System: iOS

**Comment by flexsurfer** [comment]
Looks like it always can "connect" to any node, but the problem in  status-react UI, with new navigation  https://github.com/status-im/status-react/pull/5606 , when using `navigate-to-clean` the screen routes are strict, so it's impossible to log out from any screen, maybe we could deactivate navigation somehow in dev mode
