### ISSUE TITLE
Per day pagination is off 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6230]
### User Story

As a user, I want Status time/dates and pagination to match my current time zone, so that I'm not confused about when messages are sent and received.

### Description

*Type*: Bug

*Summary*: @yenda sent me a message at 7:47 PM Eastern Time. I first saw it at 11 PM EDT, but Status had placed it under `Yesterday`. 

#### Expected behavior
Per day pagination is accurate to my time zone. A message received at 7:47 PM is from `Today`.

#### Actual behavior
At 11:08 PM - 
![image](https://user-images.githubusercontent.com/15470435/46710860-da162a80-cc17-11e8-9007-d60b703f523f.png)

### Reproduction
- Check day of messages sent later in the evening for time zones behind GMT. 

### Additional Information
* Status version: Desktop nightly
* Operating System: Mac OS

**Comment by churik** [comment]
@rachelhamlin 
Is it not the same as https://github.com/status-im/status-react/issues/5281?

**Comment by rachelhamlin** [comment]
@churik looks like it :) closing, thanks.
