### ISSUE TITLE
Unknown is shown for messages in replies that cannot be fetched (sent more 24h ago)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6234]
### Description

*Type*: Bug

*Summary*: "Unknown"  for initial messages in chat replies can be shown in two cases:
- when you log in \ log out  (because DB writing is done in async manner as @janherich said); after a while, Unknown is replaced by initial message
- when you join public chat and it contains messages from 24 h with replies to messages that are older than 24 h.

#### Expected behavior
as for me best solution is don't show "Unknown" for scenario 1 (just ordinary messages) and show some spinner instead of "Unknown"  for scenario 2 until message can be fetched.

#### Actual behavior
"Unknown" 
<img width="241" alt="unknown_3" src="https://user-images.githubusercontent.com/4557972/46718858-2cd1ff80-cc75-11e8-87b9-54404265c5df.png">

### Reproduction

*Scenario 1:*
- Open Status
- Log in
- Join any channel that contains messages with replies (last 24 h) to messages that are older than 24 hours
- Check chat history

*Scenario 2:*
- Open Status
- Log in
- Join any channel that contains messages with replies
- Log out \ log in
- Pay attention to replies. Some of them can be displayed with "Unknown" until history will be fetched.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 10/10/2018
* Operating System: Android, iOS, Mac OS

**Comment by janherich** [comment]
Already fixed in #6226

**Comment by churik** [comment]
Scenario 1 is still reproducible.

**Comment by lukaszfryc** [comment]
Can we prioritize this issue? It maybe not harmful but lot of people are experiencing it and wondering why it happens. 

In case of older > 24h (or even [7 days](https://github.com/status-im/status-react/pull/6268)) message, can we store this message in local db after replaying? cc @janherich

**Comment by janherich** [comment]
@lukaszfryc Yes, we probably should just probably embed message content and author in reply message. Originally, I didn't want to do it, because it could lead to quite significant increase in message size over the time (reply to reply to reply...) and more problematic implementation of future threads, but given that are message fetching is far from 100% reliable, there is no other way :/
