### ISSUE TITLE
Impossible to partially select a part of the text message in a chat 

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6240]
Description

Type: Bug

Summary: when you are trying to copy part of the text of a message in a chat, the it is impossible. Also, there is no indication that a part of message is being copied (text selection is not displayed), so a process in general is confusing

**Expected behavior**

It should be possible to select a part of the tex, with a visible text selection displayed

**Actual behavior**

It isn't possible to copy only a part of the text message from the chat, also text selection is not visible
Text is not actually copied to clipboard

Note: if you select a full message in that way in 1-1 chat, it is copied.

**Reproduction**

1. Open Status
2. Sign Up
3. Join any public or 1-1 chat with existing messages in it
4. Try to select a part of any message and copy it

Status version: desktop build 10/10/18 
Operating System: Mac OsX

**Comment by churik** [comment]
Is not reproducible on nightly 30/11/2018
