### ISSUE TITLE
Add Custom RPC Providers for POA and DAIChain and change default currencies

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#6250]
### User Story

The developers from POA want us to add some custom RPC endpoints to our `Network settings` screen, so that people at #CryptoLife can easily connect to their chains from Status.

### Description

*Type*: Feature

*Summary*: POA has already tested the endpoints they provided us with, and says most things work as they should, they just need us to add those RPC endpoints to the above screen by default and make UI changes, especially around the default currency and terminology when users are switched to those chains. 

We should also update this for the Ropsten and Rinkeby testnets, as it is a nice idea in general for usability, i.e. ETHro and ETHri.

#### Expected behavior

Ability to connect to custom RPCs easily by default and have the UI change seamlessly to reflect this different network, especially w.r.t the currencies displayed in our wallet.

### Additional Information

The RPC endpoints they have provided for us to test against are as follows:

xDai Chain: https://dai.poa.network (network id 100)
POA Network: https://poa.infura.io (network id 99)

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by rachelhamlin** [comment]
@goranjovic are you working on this one for the release?

**Comment by rachelhamlin** [comment]
@andytudhope @goranjovic hey guys - we'll make the release cut tomorrow or Tuesday. Will the custom RPC endpoints be added?

**Comment by chadyj** [comment]
@goranjovic did you say you are blocked on this?

**Comment by goranjovic** [comment]
@adambabik @andytudhope I'm getting `Ethereum node was started with incorrect configuration` when I switch to the network with `https://poa.infura.io` as its remote rpc. Any ideas?

(The other one seems to start ok)

**Comment by andytudhope** [comment]
@goranjovic am following up now. Also, just to confirm terminology:

Ticker - Network name
XDAI - xDai Chain (Not DaiChain)
POA - POA Network (Not POAChain)

**Comment by phahulin** [comment]
Hey @goranjovic 
when connecting to https://poa.infura.io via Metamask it seems to work fine. I'm not much familiar with how `status` works, are there "steps to reproduce" that we can follow to replicate the issue without `status` on our side?

<blockquote></blockquote>

**Comment by goranjovic** [comment]
@phahulin just to double check, what network id am I supposed to use for the two networks?

**Comment by SiddigZeidan** [comment]
@goranjovic the network ID for POA Network is 99

For xDai Chain, I believe it is 100, however @phahulin can confirm that

**Comment by goranjovic** [comment]
thanks @SiddigZeidan seems like we had some aggressive validations, it works fine now

**Comment by SiddigZeidan** [comment]
@goranjovic Fantastic news! Please let me know if any other issues occur

**Comment by adambabik** [comment]
I would call it proper validation :D Just wording around it was bad and confusing. I believe it is also fixed so in the future it will be very easy to spot network IDs mismatch :)

**Comment by goranjovic** [comment]
Doc all the steps to add a network - https://discuss.status.im/t/dev-tutorial-how-to-add-new-network/598

<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/dev-tutorial-how-to-add-new-network/598">Dev Tutorial - How To Add New Network</a></strong></div><div>This doc lists and explains all the steps needed to add a new network to Status (e.g. side chain or a test network).  Inclusion of POA Network and xDAI Chain was the feature that led to this document, so I’ll use them as an example throughout this doc.  Overview:   add network info to status-im.constants  add chain id and name to status-im.utils.ethereum.core  add native currency info to status-im.utils.ethereum.tokens  add native currency icon to resources/images/tokens/NETWORK/0-native.png  ad...</div></blockquote>
