### ISSUE TITLE
"/send" message contains needless dot character

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6261]
### Description

*Type*: Bug

*Summary*: 

The following dot should not be there:

<img src="https://user-images.githubusercontent.com/7532782/46809147-30957d00-cd6e-11e8-879a-7826bdc7047b.png" width="200">

#### Expected behavior
"0.0007 ETH"

#### Actual behavior
"0.0007.ETH"

### Reproduction

- Open 1-1 chat and /send ETH

### Additional Information
* Status version: 11 October
* Operating System: Android, iOS

**Comment by goranjovic** [comment]
Heads up. I'm already working on this one.
