### ISSUE TITLE
Android nightly installation error

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6271]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a android user, I want to install nightlies so that I can live in the edge.

### Description

At some point in the last month or two something funky started happening to Android nightlies.  There were reports of unspecified errors on Android 8 like `error installing app` and other errors on Android 9 like `can't open file`.

A reported workaround has been to open with a file manager, but sometimes the archive is expanded and the contents can be browsed rather than installed.

#### Expected behavior
Nightlies can be installed on android

#### Actual behavior
Errors on install

### Reproduction

- Use Pixel with Android 9
- Download nightly with Chrome (and ensure Chrome has correct permissions)
- Try to install

**Comment by chadyj** [comment]
This is what it looks like on Android 9 when downloading in Chrome then opening from Downloads.

![cantopenfile](https://user-images.githubusercontent.com/116099/46855798-fb883980-ce04-11e8-8ac9-a5ba6c7e0c64.png)

Here is what I see when opening from Files.

![files](https://user-images.githubusercontent.com/116099/46855950-70f40a00-ce05-11e8-82d3-7b8bddb42dee.png)

**Comment by chadyj** [comment]
Andrea took a look at this and saw that the problem is the content/type.

From https://get.status.im/chat/public/test-team

> ok, the problem is just the content/type
> on cdn: < Content-Type: application/zip
> on jenkins < content-type: application/vnd.android.package-archive
> we just need to update the upload script

@jakubgs Can you please take care of this?  Thanks!

<blockquote><div><strong><a href="https://get.status.im/chat/public/test-team">Join the public chat: #test-team in Status</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
I've merged the fix at: https://github.com/status-im/status-react/commit/33cf6dfd4bca7a5105c009b26347b03ee6e861e6
Can you please check that this APK doesn't have the same problem:
https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181012-132040-011e25-pr.apk

<blockquote></blockquote>

**Comment by chadyj** [comment]
Fixed!  Many thanks :)
