### ISSUE TITLE
Keyboard shortcut support on desktop

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6272]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a desktop user, I want to use keyboard shortcuts for tasks so that I can get common actions done quickly.

### Description

Things like new chat, or search, or emoji, or scrolling chat with keyboard would be 💯 

On a Mac:

- Command N >> "new button" (blue + button)
- Command F >>  Moves keyboard focus to "type here to search chats"
- Keyboard up/down >> scroll chat window up/down
- Control + Command + Space (system shortcut) >> open emoji UI

#### Expected behavior
Keyboard shortcuts work

#### Actual behavior
nada

### Solution

- First define actions
- Then define shortcuts

**Comment by cammellos** [comment]
I'd love to see: Command + k brings up a pop up that allows you to search the open chats, try it out on slack to see what I mean, it's very handy and allows switching chats without using a mouse.

**Comment by chadyj** [comment]
> I'd love to see: Command + k brings up a pop up that allows you to search the open chats, try it out on slack to see what I mean, it's very handy and allows switching chats without using a mouse.

That's a fave of mine in Slack too! (also Command + T)
We could just move the keyboard focus to the search box we already have.

**Comment by cammellos** [comment]
@chadyj yes! and focus on the first chat input box on `Enter`, and then is mouse free
