### ISSUE TITLE
Seeing duplicate messages from myself in the new build

### ISSUE THREAD

**Issue by J12B** [status-im/status-react#6280]
[comment]: # (

### User Story

I updated with the new nightly, and since logging in I see messages that I sent yesterday in duplicate. This only occurs for messages sent yesterday, and only in public channels. 
Messages sent prior to yesterday only show once, and messages in private chats only show once. 
I've attached a screenshot. When I checked first thing this morning the result was fine (only 1 instance of the message I sent) but after updating with the new nightly the result is 2 of the same message with the same timestamp. 

### Description

[comment]: 
*Type*: Bug

#### Expected behavior
[comment]: # Messages sent show only once.

#### Actual behavior
[comment]: # Saw duplicate versions of recent messages I sent yesterday in public chats. 

### Reproduction
[comment]: # Unsure

- Open Status
- ...
<img width="656" alt="screen shot 2018-10-12 at 09 52 44" src="https://user-images.githubusercontent.com/41283474/46859052-9d5b5680-ce04-11e8-83d4-f493c226ccd8.png">

- Step 3, etc.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: V0.0.1 (02cb5dc8d)
[comment]: # (Android or iOS.)
* Operating System: Mac OS High Sierra 10.13.6

**Comment by churik** [comment]
@jonathanbarker still facing this issue?

**Comment by J12B** [comment]
No - this issue fixed with update. Thanks.
