### ISSUE TITLE
Status desktop appears "offline" when online

### ISSUE THREAD

**Issue by J12B** [status-im/status-react#6284]
[comment]: # Status desktop shows as "offline" even when online.

### User Story

Desktop on Mac. Had a brief connection problem on my mac and went offline. As expected, the Status app showed "offline". When i came back online (as confirmed by receiving messages through status and using a web browser), the status app still shows "offline." I've been online for 10 minutes now, but the app still shows offline.

### Description

[comment]: # Bug
*Type*: Bug

#### Expected behavior
[comment]: # The "offline" header should disappear when I'm online.

#### Actual behavior
[comment]: # The "offline" header remained even when I'm online.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: V0.0.1 (02cb5dc8d)
[comment]: # Mac
* Operating System: Mac OS High Sierra 10.13.6

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by dshulyak** [comment]
I can reproduce this issue. Definitely see that i established connections with peers after application was resumed.  But desktop app always shows "offline" message. I think same problem appears on IOs when app moved from background.

@yenda @cammellos when do remove "offline" warning? is it when "discovery.summary" returns peers or there is additional logic? there is definitely a bug, either in handling that event or in status-go module.

**Comment by dshulyak** [comment]
I can reliably reproduce this situation.
Steps:
1. run desktop app
2. simulate network conditions. turn off your wifi, disable interface, or use this tool https://github.com/tylertreat/comcast
3. ensure that all establishrf connections with app disappeared.  `lsof -i -P <status pid>`
4. see in the logs that discovery.summary is empty:
```
17:16:14.543 - D - [RCTStatus] - ::onStatusGoEvent call - event:  {"type":"discovery.summary","event":[]}
```
5. enable network, wait for established connections
6. see in log that discovery.summary was restored
```
17:17:00.262 - D - [jsserver] - [status-im.events:685] - :event-str {"type":"discovery.summary","event":[{"id":"c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49","name":"Statusd/v0.16.4/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.0.107:34888","remoteAddress":"206.189.243.162:30504","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"id":"f34451823b173dc5f2ac0eec1668fdb13dba9452b174249a7e0272d6dce16fb811a01e623300d1b7a67c240ae052a462bff3f60e4a05e4c4bd23cc27dea57051","name":"Statusd/v0.16.4/linux-amd64/go1.10.2","caps":["shh/6"],"network":{"localAddress":"192.168.0.107:36918","remoteAddress":"47.52.173.66:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
```

<blockquote><img src="https://avatars1.githubusercontent.com/u/552817?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/tylertreat/comcast">tylertreat/comcast</a></strong></div><div>Simulating shitty network connections so you can build better systems. - tylertreat/comcast</div></blockquote>

**Comment by cammellos** [comment]
i will take a look it tonight, thanks for the info, very helpful, you are
running latest develop, correct?

**Comment by dshulyak** [comment]
@cammellos i am using builds from tuesday and monday. can reproduce on both of them. should i try to reproduce on latest build?

**Comment by cammellos** [comment]
no, that's ok, just wanted to check was fairly recent, thanks

**Comment by churik** [comment]
@cammellos duplicate? https://github.com/status-im/status-react/issues/6396

**Comment by cammellos** [comment]
seems like, feel free to close one, I will assign both to me, thanks for spotting it

**Comment by cammellos** [comment]
@dshulyak I can't replicate myself, everything works as expected, would it be possible to get all the logs from just before you go offline till you are back online `~/.local/share/Status/Status.log` if you are running an actual build or the output of `node ubuntu-server.js` if you are actually running the development stack.

Also, when it displays `offline` but you are online (error condition), if you go to any chat, and write a message, is the send button visible/enabled?

**Comment by dshulyak** [comment]
I am trying to reproduce it again to get logs but i can't. Not sure why. Button to send a message was blocked, but i was receiving new messages.

It is probably not related to discovery.summary. Now warning switches to "connecting to peers". and gets removed once i have at least one peer in discovery.summary.

**Comment by dshulyak** [comment]
Found logs from yesterday: https://pastebin.com/jACzPFSW

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/jACzPFSW">17:16:14.387 - D - [RCTStatus] - ::onStatusGoEvent call - event:  {"type":"disco - Pastebin.com</a></strong></div></blockquote>
