### ISSUE TITLE
Crash when tapping close (desktop)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6286]
### Description

*Type*: Bug

*Summary*: Status crashed when I clicked the cross button to close the Status window

#### Expected behavior
no crashes

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/46865870-bf1a0500-ce27-11e8-92f5-6472e573907d.png)

### Reproduction

- Open Status
- Run it for ~6h
- Close the app by tapping the cross button

### Additional Information
* Operating System: desktop

#### Logs

https://drive.google.com/open?id=1JOisYCPQniw0lA0XiJi9Mj8dMoLtwedV

<blockquote><div><strong><a href="https://drive.google.com/open?id=1JOisYCPQniw0lA0XiJi9Mj8dMoLtwedV">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>

**Comment by churik** [comment]
@asemiankevich did you face with this issue recently again or it happened only once?

**Comment by asemiankevich** [comment]
@churik nope , not anymore.
