### ISSUE TITLE
Desktop alpha release warning

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6294]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be informed of the risks of using beta software so that I can take necessary safeguards.

### Description

Desktop doesn't have wallet functionality, but the recovery phrase used can belong to a wallet with assets that need to be protected. As such as need to let users know they are using beta software and should use it for testing.

#### Expected behavior

Warning on signup and recovery

### Solution

Show a notification on signup and recovery.
cc @EugeOrtiz @obi2020 

### Additional Information
Platform: Desktop

cc @corpetty

**Comment by chadyj** [comment]
@sonyx6 can you help us with a draft please?

**Comment by chadyj** [comment]
This is the beta warning for mobile:

> Thanks for choosing Status! We are now in Beta, which means new installs are automatically connected to the Mainnet. If you upgraded, you may still need to switch networks, which you can do easily by navigating to your Profile -> Advanced Mode -> Switch Developer Mode on -> Choose your network. Now just have fun! Browse DApps, exchange assets, start your own #chats, and message your friends, all from the world's first decentralized, mobile client for Ethereum.
> 
> Please note that this is a beta release and we advise you that using this app should be done for testing purposes only and you assume the full responsibility for all risks concerning your data and funds.

So as a starting point how about:

> Thanks for trying Status Destkop! This is an early alpha release focused on chat, and is missing several features found in the mobile client and may contain bugs and other issues.
> 
> Please note that this is an alpha release and we advise you that using this app should be done for testing purposes only and you assume the full responsibility for all risks concerning your data and funds.  Status makes no claims of security or integrity of funds in these builds.
>

**Comment by chadyj** [comment]
Hey @dmitryn interested in grabbing this launch blocker for desktop? I think you did the mobile warnings, right?

**Comment by dmitryn** [comment]
@chadyj probably not me, but i can add warning to desktop

**Comment by rasom** [comment]
https://github.com/status-im/react-native-desktop/issues/362
