### ISSUE TITLE
"Fetching messages..." badge is shown where there are no messages to fetch

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6295]
### Description
*Type*: Bug

*Summary*: 
There are 2 problems:

**Problem 1**) "Fetching messages..." badge is shown under specific conversations when there are no messages to fetch. That gives the false impression that the other person wrote or is writing something and the user needs to wait for them. After fetching nothing new appears.
The problem here is that a general fetch is happening, but we are showing the badge under a specific conversation.

**Problem 2**)  "Fetching messages..." badge is shown when creating a new account, and there are no messages to fetch since there is no conversation going on yet.

### Expected behavior / Solution
Problem 1) Show the badge on a more "general" location, not under a specific chat. Old design here > zpl.io/V1qZyPk . Worth exploring new alternatives. But do not show it inside a specific chat (1:1, group or public)

General placement, for general actions/events:
<img width="611" alt="captura de pantalla 2018-10-12 a la s 2 57 26 p m" src="https://user-images.githubusercontent.com/37297779/46870543-3010eb00-ce2f-11e8-83dc-11370b3033f3.png">

Chat specific placement, for chat specific actions/events:
<img width="618" alt="captura de pantalla 2018-10-12 a la s 2 57 31 p m" src="https://user-images.githubusercontent.com/37297779/46870573-4159f780-ce2f-11e8-9e5f-67357cdcb4ad.png">

Problem 2) Show the badge only when there are actions actually being performed at a general level.

### Actual behavior
Problem 1) When chatting with somebody (even the first time) the badge is shown inside the chat conversation area:

<img width="1252" alt="captura de pantalla 2018-10-12 a la s 1 52 39 p m" src="https://user-images.githubusercontent.com/37297779/46870379-bed13800-ce2e-11e8-9f07-b7ef72eaf957.png">

### Reproduction
- Open Status Desktop
- Create new account (observe)
- Open a 1:1, group or public chat (observe)

**Comment by Swader** [comment]
Still present on OS X
