### ISSUE TITLE
Ensure Dether.io works with status

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6300]
### User Story
As a user, I want to use dether DApp from status

### Description
_Type_: Feature

Make sure DEther works fine with status.

Specifically we got this feedback from Dether team:

```
When you click on 'CONTACT' on someone on the map, it suppose to open a navigator windows
with a telegram link (https://t.me/'telegram_name'), and thus,
if you have telegram on your mobile phone, its suppose to open it.

But when I click on the status browser nothing happen,
are you blocking the opening of external browser link inside your browser?
```

Note that the issue might be in the following project: https://github.com/status-im/react-native-webview-bridge

**Comment by jeluard** [comment]
@asemiankevich @Serhy Could you validate the feedback from Dether team?

**Comment by asemiankevich** [comment]
@jeluard thanks for heads up , looking now

**Comment by asemiankevich** [comment]
@jeluard i took a brief look through the app and it is very confusing to me how to use it at all. i was not able to reach the case where `Contact` could be clicked. Here some screenshots btw, from which i could assume:
- the web page asks me to download some app from app store / google play
- location is not working (i am not in prague anymore)
- i was able to tap some shop (?) on the map that i could not close. `Register` button does not trigger anything

![image](https://user-images.githubusercontent.com/28752642/48438432-06801200-e795-11e8-9af5-304d8474503e.png)

![image](https://user-images.githubusercontent.com/28752642/48438444-0aac2f80-e795-11e8-8d6e-6691a8882200.png)

![image](https://user-images.githubusercontent.com/28752642/48438461-13046a80-e795-11e8-9d8e-34469280f97b.png)

From this being said it is very difficult to make any conclusion apart that this dapp is hardly usable in Status browser.
Appreciate some use cases that `should` work so i can check them within Status browser. 
let me know if i could do more here.

**Comment by jeluard** [comment]
@asemiankevich For now we are mostly focused on identifying and fixing the issue highlighted by the Dether team.

**Comment by rachelhamlin** [comment]
Found a seller in London on https://web3.dether.io - the `Chat on Telegram` button gives feedback, but indeed nothing happens.

![img_6653](https://user-images.githubusercontent.com/15470435/48470656-44f7ea00-e7f2-11e8-92fa-012e0945e93f.PNG)


<blockquote><img src="https://app.dether.io/facebook/vignette.jpg" width="48" align="right"><div><img src="/icons/prod/icon-512x512.png" height="14"> Dether - Buy and sell crypto for cash</div><div><strong><a href="https://dether.io/">Dether - Buy and sell crypto for cash</a></strong></div><div>Download the Dether app. Buy cryptocurrency near you. Sell cryptocurrency and make money.</div></blockquote>

**Comment by Fukunaga42** [comment]
Hi Guys Mehdi from Dether here, to use the web3 browser version you need to go on https://web3.dether.io . The problem we have, as Rachel stated, is when we click on 'chat on Telegram' it suppose to open telegram app on the device through a deeplink tg://login , but nothing happen. If you test from the desktop version map, (dether.io), and try to click on someone it will work properly.

<blockquote><img src="https://app.dether.io/facebook/vignette.jpg" width="48" align="right"><div><img src="/icons/prod/icon-512x512.png" height="14"> Dether - Buy and sell crypto for cash</div><div><strong><a href="https://dether.io/">Dether - Buy and sell crypto for cash</a></strong></div><div>Download the Dether app. Buy cryptocurrency near you. Sell cryptocurrency and make money.</div></blockquote>

**Comment by Fukunaga42** [comment]
Hello Guys, any news regarding our problem? Dont hesitate if you need anything from us to ping me here.
Best

**Comment by jeluard** [comment]
Sorry @Fukunaga42  we will look at it next week!

**Comment by hesterbruikman** [comment]
Stuck on verifying address, after connecting account through permission dialog

![Screenshot_20200501-173833_Status.jpg](https://images.zenhubusercontent.com/5eaacc9bd76e4cffd53fcf08/5404e01a-26ae-4fb3-82af-9bd058eb4328)

**Comment by Fukunaga42** [comment]
Hello guys we currently not support WEB3 injected wallet with the actual version. I'll notify you when it will be the case. But beesides that we are currently working on a SDK with JS library and some React Component to easliy interact with the dether protocol. You will be able to easily display the map, and/or easily add tellers on your own on the protocols. I'll keep you updated when we'll publish the documentation website.
