### ISSUE TITLE
Windows platform compatibility

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6304]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a windows user, I want platform-specific features to work nicely.

### Description

Since windows is brand new we haven't tested or implemented some windows niceties and features. Some things we need to look at:

- [ ] Custom url support `status-im://`
- [ ] Deep links
- [x] App icon
- [x] Desktop notifications (https://github.com/status-im/status-react/issues/6728)
- [x] Installer (https://github.com/status-im/status-react/pull/6586)
- [ ] WebKit support
cc @PombeirP @MaxRis

**Comment by bitgamma** [comment]
I was trying without success to change profile picture. Clicking a little around while in edit mode in the profile interface I got this error: https://yadi.sk/i/E3VC6e6Bu8q1Ew. Clicking on reload js did nothing, clicking on dismiss made the screen totally blank (had to restart the app)

<blockquote><img src="https://downloader.disk.yandex.ru/preview/7d54ebce70f50c02897b1de258f840ce69ebf4a0c08cd1d5a7f4c677575e16e1/5bc47be3/958PD-2jjEwujPv6pq62V06XnPWdfWm_gVKdY8H71dTK1eEaveaGPNS97rA7teo7HjgqG999Y_Q_2hSJbVwHWQ%3D%3D?uid=0&filename=2018-10-15_09-33-36.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&crop=1&size=200x200&logo=1" width="48" align="right"><div><img src="https://yastatic.net/disk/public3/_/e9BzZ-OrLJGblsmTiZ_Yw1ASWVB.png" height="14"> Yandex.Disk</div><div><strong><a href="https://yadi.sk/i/E3VC6e6Bu8q1Ew">2018-10-15_09-33-36.png</a></strong></div><div>View and download from Yandex.Disk</div></blockquote>

**Comment by chadyj** [comment]
@bitgamma Thanks for testing!

> I was trying without success to change profile picture.  

Ah interesting. This isn't [yet] possible on Mac and Linux. Look's like we will have to disable it on windows until we introduce this feature on desktop.

**Comment by bitgamma** [comment]
another issue, don't know if it is Windows specific, but after restarting my computer and launching Status I get this: https://yadi.sk/i/ilI8eNFIVEAA-A

<blockquote><img src="https://downloader.disk.yandex.ru/preview/3502edfb2046626fbbce0b40357e192ce2edc9bd78120607159bd6fc556d1270/5bc50eeb/958PD-2jjEwujPv6pq62V3xrazH97_WKgJDikVNL95-dFqRkFFzI-OZgqP5Nh6hiBc2BN_1c91DHGzrotHC0Lw%3D%3D?uid=0&filename=2018-10-15_20-03-09.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&crop=1&size=200x200&logo=1" width="48" align="right"><div><img src="https://yastatic.net/disk/public3/_/e9BzZ-OrLJGblsmTiZ_Yw1ASWVB.png" height="14"> Yandex.Disk</div><div><strong><a href="https://yadi.sk/i/ilI8eNFIVEAA-A">2018-10-15_20-03-09.png</a></strong></div><div>View and download from Yandex.Disk</div></blockquote>

**Comment by chadyj** [comment]
> another issue, don't know if it is Windows specific, but after restarting my computer and launching Status I get this: https://yadi.sk/i/ilI8eNFIVEAA-A

That is a general desktop [problem](https://github.com/status-im/status-react/issues/6112), unfortunately. Fix is here https://docs.status.im/docs/build_desktop.html#Clean-up-data
but for wherever the files are stored on windows.

<blockquote><img src="https://downloader.disk.yandex.ru/preview/245cd8caf49667e5d4f6b9f5e633c0d7f768875a51e62cffcb7148f1e91b8f0d/5bc50f7a/958PD-2jjEwujPv6pq62V3xrazH97_WKgJDikVNL95-dFqRkFFzI-OZgqP5Nh6hiBc2BN_1c91DHGzrotHC0Lw%3D%3D?uid=0&filename=2018-10-15_20-03-09.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&crop=1&size=200x200&logo=1" width="48" align="right"><div><img src="https://yastatic.net/disk/public3/_/e9BzZ-OrLJGblsmTiZ_Yw1ASWVB.png" height="14"> Yandex.Disk</div><div><strong><a href="https://yadi.sk/i/ilI8eNFIVEAA-A">2018-10-15_20-03-09.png</a></strong></div><div>View and download from Yandex.Disk</div></blockquote>
<blockquote><div><strong><a href="https://docs.status.im/docs/build_desktop.html#Clean-up-data">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>

**Comment by bitgamma** [comment]
Yeah I have managed to restore it, the files to delete are in %APPDATA%/StatusIm

**Comment by jrainville** [comment]
Hi, I can't wait to use Status on Windows, as I am currently using a VM with Ubuntu just to use Status.
Is there a way I can help test it or use it right now?

**Comment by maxhora** [comment]
@jrainville Pedro is on vacation, I haven't yet looked, but suppose to look into this to check if I can continue from the point he stopped ( I believe he was able to automate building of Windows version ) and evaluate next steps.

**Comment by chadyj** [comment]
@jrainville Try here https://github.com/status-im/status-react/issues/5807#issuecomment-430594740

**Comment by jrainville** [comment]
Nice. Just installed. It works well for now. Do you want me to report issues here or somewhere else?

**Comment by chadyj** [comment]
> Nice. Just installed. It works well for now. Do you want me to report issues here or somewhere else?

Feedback welcome, thanks!

This thread was for stuff that works on Linux/Mac, but doesn't work in the Windows platform build.  For example a weird icon.

**Comment by jrainville** [comment]
Found my first issue with the Windows build.
When trying to re-open Status after the weekend (computer was closed), I got this error message:
![image](https://user-images.githubusercontent.com/11926403/47291505-e748f700-d5d1-11e8-8d59-60346c5f9971.png)

Than, clicking Apply, it gets stuck on a white screen. 
Closing and re-opening Status doesn't fix it.

Never had that on Ubuntu.

**Comment by Swader** [comment]
Stale but still active
