### ISSUE TITLE
Each message sent before upgrade is shown twice after upgrade from 0.9.29

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#6307]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Each message sent before upgrade is shown twice after upgrade from 0.9.29
https://s3.amazonaws.com/testfairy/screenshots/4803622/8626941/109020185/14_643b03d7310e82ad5fd0f3960e8ff3224fc6032b_o.jpg
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Message is shown once
#### Actual behavior
[comment]: # (Describe what actually happened.)
Message sent once is shown twice after upgrade
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install 0.9.29 Status
- Send 3 messages to public chat, e.g. 1, 2 and 3
- Upgrade to nightly build
- open the public chat and wait for messages to be fetched.
- check how sent 1,2,3 are shown now (in my case it's 1,1,2,2,3,3)

after upgrade: https://app.testfairy.com/projects/4803622-status/builds/8626941/sessions/4403987481/?accessToken=sBz/h9vUxgG03QEz9C1nwqnEpZE

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: upgrade from 0.9.29 from playstore to nightly from Oct 14
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

<blockquote></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8626941/sessions/4403987481/?accessToken=sBz/h9vUxgG03QEz9C1nwqnEpZE">TestFairy: Status 0.9.29 (10419) @2018</a></strong></div></blockquote>

**Comment by chadyj** [comment]
@yenda Are you doing work on this?  
If not @rasom might be able to take it.

**Comment by yenda** [comment]
@rasom if you work on this the most viable solution atm IMO would be to do replace/string on the namespace of the serialized record

```
(pr-str (Message. {:text "hello"} "text/plain" :user-message 123 123))
#status-im.transport.message.protocol.Message{:content {:text \"hello\"}, :content-type \"text/plain\", :message-type :user-message, :clock-value 123, :timestamp 123}
```
