### ISSUE TITLE
Add Ethereum Roulette app

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#631]
A DApp request to add the Eth Roulette app (I'm assuming vdice?)

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/93

**Comment by TheHealthyCat** [comment]
Or maybe Rouleth
rouleth.com

**Comment by jarradh** [comment]
http://wiki.status.im/contributing/development/adding-dapps/

**Comment by jumarko** [comment]
Would you mind setting the "in progress" label, please?

**Comment by rasom** [comment]
@jumarko, done

**Comment by viebel** [comment]
@jumarko are you working on it?

**Comment by jumarko** [comment]
Not really - I just thought that this one was already in progress (since some commit has been pushed: https://github.com/tomby42/status-react/commit/704c5643bd70d2347b47c94292f2ecea16a474b4). Thus I wanted that label to be able to search for the issues that are not in progress :).

**Comment by tomby42** [comment]
@jumarko The problem is that rouleth is on mainnet. So it is not working with ropstent test net account.

**Comment by rasom** [comment]
@jarradh do we still need this?
