### ISSUE TITLE
Recovering an account that was already recovered on that device, with a different password, gives an error

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6315]
**Description**

Type: Feature

Summary: When an account was already recovered on a device, recovering it a second time with a different password gives out an error

**Expected behavior**

When a user has his recovery phrase, but forgot his password - he should be able to recover the account again without having to re-install the application

**Actual behavior**

When inserting a different password, an error 'This account already exists but passwords do not match'

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/43638377/46950722-5bdddc00-d08e-11e8-9d13-cb5eccb5bfbc.png">

**Reproduction**

1. Create a new test account and set a recovery phrase for it
2. On a different device, recover your account with a valid passphrase and a random password
3. After account is recovered, log out of the account
4. On the same device, recover the same account again, with a valid passphrase but a different password from Step 2

**Additional Information**

Reproduces both for desktop and mobile.
MacOS 10.13.4
Real device iPhone 6s, iOS

**Comment by SlizkovaGanna** [comment]
@chadyj @hesterbruikman @errorists please let me know what you think on this one.

This was a fix delivered in https://github.com/status-im/status-react/issues/5745
The thing I’m worried is that in terms of usability we did not solve the issue for someone who forgot their password.
So the only solution for a user (not sure it’s an obvious one) is to re-install the app and recover the account one more time
Perhaps we should recover an account each time the passphrase is valid, no matter the password (so, basically, we would re-set a password for the current user).
Thank you.

**Comment by Swader** [comment]
Keeping this alive until confirmed as no longer relevant.
