### ISSUE TITLE
Add Status ENS registration analytics

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6316]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a community member, I want visibility into Status ENS registrations so that I can see progress.

### Description

ENS registrations is complete in Status and launching in 0.9.30!  Let's update https://analytics.status.im/#ens-registrations so we can see chart progress.

cc @bgits @rachelhamlin 

<blockquote><div>analytics.status.im</div><div><strong><a href="http://analytics.status.im/">Analytics for Status</a></strong></div><div>Analytics for Status</div></blockquote>

**Comment by rachelhamlin** [comment]
Nice! Thanks for this. The contract will be deployed on mainnet soon.

**Comment by chadyj** [comment]
@tersec Did you further investigate [Google Big Query](https://cloud.google.com/blog/products/data-analytics/ethereum-bigquery-public-dataset-smart-contract-analytics) for this use case?

**Comment by tersec** [comment]
@chadyj Sure:
> As a follow-up, here’s a query for measuring a token statistic (transaction count) by time window, specifically the daily count of $OMG tokens transfers, and a Data Studio visualization of these data as a time series from inception through August 2, 2018 from this Google Sheet:

Provides an example query which can be easily modified to point to the https://etherscan.io/address/0x1da022710df5002339274aadee8d58218e9d6ab5 ENS contract address:
```
SELECT 
  from_address AS Source,
  to_address as Target,
  CAST(value AS NUMERIC)/POWER(10,18) AS Weight
FROM 
  `bigquery-public-data.ethereum_blockchain.token_transfers` AS token_transfers, 
  `bigquery-public-data.ethereum_blockchain.blocks` AS blocks
WHERE token_transfers.block_number = blocks.number
AND token_transfers.token_address = '0x1da022710df5002339274aadee8d58218e9d6ab5'
ORDER BY timestamp
LIMIT 50000
```

It doesn't return any results; likely, that's due to its apparently not being on mainnet yet per @rachelhamlin. The exact query of use will be different, but the functionality's there.

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/address/0x1da022710df5002339274aadee8d58218e9d6ab5">Ethereum Accounts, Address And Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by tersec** [comment]
```
SELECT 
  from_address AS Source,
  to_address as Target,
  CAST(value AS NUMERIC)/POWER(10,18) AS Weight
FROM 
  `bigquery-public-data.ethereum_blockchain.token_transfers` AS token_transfers, 
  `bigquery-public-data.ethereum_blockchain.blocks` AS blocks
WHERE token_transfers.block_number = blocks.number
AND token_transfers.token_address = '0x744d70fdbe2ba4cf95131626614a1763df805b9e'
ORDER BY timestamp
LIMIT 50000
```
Seems to be alive. From my understanding, that's capturing ENS lookups. Is that correct? Is it capturing all both registrations and lookups?

Is it only `approveAndCall` calls (looks like methodId `0xcae9ca51` at https://etherscan.io/tx/0xa2a8247f13024e93f12029005e155ad67352c3861a4d44e5d512af3d30538abd)?

`0x744d70fdbe2ba4cf95131626614a1763df805b9e` is the same address as for SNT transactions, so can't be the only filter.

**Comment by tersec** [comment]
@rachelhamlin @chadyj  
```
SELECT 
  from_address AS Source,
  to_address as Target,
  CAST(value AS NUMERIC)/POWER(10,18) AS Weight
FROM 
  `bigquery-public-data.ethereum_blockchain.token_transfers` AS token_transfers, 
  `bigquery-public-data.ethereum_blockchain.blocks` AS blocks
WHERE token_transfers.block_number = blocks.number
AND token_transfers.token_address = '0xdb5ac1a559b02e12f29fc0ec0e37be8e046def49'
ORDER BY timestamp
LIMIT 50000
```

Still returns 0 results, despite https://etherscan.io/address/0xdb5ac1a559b02e12f29fc0ec0e37be8e046def49 showing contract creation from 7-odd hours ago. It probably just takes that long for events to show up -- that end-to-end system latency's useful to know.

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/address/0xdb5ac1a559b02e12f29fc0ec0e37be8e046def49">Ethereum Accounts, Address And Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by chadyj** [comment]
@tersec looks like the queries are working nicely so what do you think about doing daily auto updates for analytics.status.im?

**Comment by tersec** [comment]
```
SELECT transactions.from_address
FROM `bigquery-public-data.ethereum_blockchain.token_transfers` as transactions,
`bigquery-public-data.ethereum_blockchain.blocks` as blocks
WHERE transactions.to_address = '0xdb5ac1a559b02e12f29fc0ec0e37be8e046def49'
AND blocks.number = transactions.block_number
GROUP BY transactions.from_address
```

and

```
SELECT
blocks.timestamp
FROM
  `bigquery-public-data.ethereum_blockchain.token_transfers` as transactions,
  `bigquery-public-data.ethereum_blockchain.blocks` as blocks
SELECT
FORMAT_TIMESTAMP("%Y-%m-%d", blocks.timestamp) as day,
COUNT(FORMAT_TIMESTAMP("%Y-%m-%d", blocks.timestamp)) as daycount
FROM
  `bigquery-public-data.ethereum_blockchain.token_transfers` as transactions,
  `bigquery-public-data.ethereum_blockchain.blocks` as blocks
WHERE transactions.to_address = '0xdb5ac1a559b02e12f29fc0ec0e37be8e046def49'
AND blocks.number = transactions.block_number
GROUP BY FORMAT_TIMESTAMP("%Y-%m-%d", blocks.timestamp)
```

Are the current (by per distinct user and by per day, respectively; one can also combine them) queries, for the record.

@chadyj analytics.status.im is, as far as I know, deprecated; https://status.im/analytics/ is the current URL, with a better design. I'm not sure if it makes sense to keep analytics.status.im updated.

<blockquote><img src="/img/share.png" width="48" align="right"><div><strong><a href="https://status.im/analytics/">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>

**Comment by chadyj** [comment]
> @chadyj analytics.status.im is, as far as I know, deprecated; https://status.im/analytics/ is the current URL, with a better design. I'm not sure if it makes sense to keep analytics.status.im updated.

Ah fantastic! Let's shut the old one down :)

So will you be able to update https://status.im/analytics/ens_registration.html daily?

<blockquote><img src="/img/share.png" width="48" align="right"><div><strong><a href="https://status.im/analytics/">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>
<blockquote><img src="/img/share.png" width="48" align="right"><div><strong><a href="https://status.im/analytics/ens_registration.html">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>

**Comment by chadyj** [comment]
@tersec @rachelhamlin Any updates on ENS registration analytics? Will be useful to see this metric on our analytics site.

**Comment by chadyj** [comment]
@tersec is this still in progress?

**Comment by rachelhamlin** [comment]
Heard from @tersec about this on the 17th. He said this should be possible. Would love to have ENS stats online.
