### ISSUE TITLE
For Linux desktop, there is no Status app icon in Applications

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6318]
**Description**

Type: Bug

Summary: Application is not found in /usr/share/applications for Linux (Mint 19)
It should be listed under 'applications' and have an icon there.

**Expected behavior**

There should be an icon for Status in Applications, the app can be found in search there

**Actual behavior**

There is no icon for Status in Applications, the app cannot be found in search there

**Reproduction**

1. Download Status app on Linux
2. In file properties, allow the file to be executed
3. Open the file
4. Having Status working on background, go to the Menu and search for Status by name

<img width="794" alt="image" src="https://user-images.githubusercontent.com/43638377/46954085-55ecf880-d098-11e8-978f-5c95a248e8b9.png">

**Additional Information**

Status version: develop V 0.0.1 (21cda1899)
Operating System:
Desktop Linux Mint 19

**Comment by churik** [comment]
The same for push notifications - no logo when they are coming, no `Status` picture app is opened in dock.
On the dock (Linux Ubuntu 16.04):
<img width="137" alt="status_l" src="https://user-images.githubusercontent.com/4557972/47301069-54827980-d61e-11e8-84e8-d0f63a8b3f63.png">
Push notifications:
![image](https://user-images.githubusercontent.com/4557972/46796350-20bd6f00-cd55-11e8-9162-cf7d28ccd6f7.png)

**Comment by chadyj** [comment]
This should be fixed now?

**Comment by churik** [comment]
closed in #6097
