### ISSUE TITLE
ERROR [status-im.events:1004] - :send-status-message-error Error: specify either a symmetric or an asymmetric key

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6320]
### Description

*Type*: Bug

*Summary*:

```
console.error: "ERROR [status-im.events:1004] - :send-status-message-error Error: specify either a symmetric or an asymmetric key"

error
    index.ios.bundle?platform=ios&dev=true&minify=false:56965:29
_callTimer
    index.ios.bundle?platform=ios&dev=true&minify=false:3512:17
callTimers
    index.ios.bundle?platform=ios&dev=true&minify=false:3719:19
__callFunction
    index.ios.bundle?platform=ios&dev=true&minify=false:3118:49
<unknown>
    index.ios.bundle?platform=ios&dev=true&minify=false:2895:31
__guard
    index.ios.bundle?platform=ios&dev=true&minify=false:3071:15
callFunctionReturnFlushedQueue
    index.ios.bundle?platform=ios&dev=true&minify=false:2894:21
```

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/46960266-d4e92d80-d0a6-11e8-9aae-773a611941e3.png)

### Reproduction

- Open Status (develop on emulator)
- Recover account that could have some 1x1 chats recovered today
- Join any 1x1 chat that is recovered

**Comment by lukaszfryc** [comment]
1) Does it happen in release builds as well?
2) Is it related to some specific chat from yesterday?

**Comment by asemiankevich** [comment]
@lukaszfryc 
1. it is in develop for a while ago as i got from @flexsurfer 
2. i think it is related to the chats that are recovered with account

**Comment by flexsurfer** [comment]
sorry for confusion, but i can't say it's in develop while ago, i saw this before, but can't say for sure

**Comment by asemiankevich** [comment]
yeah it is fine (c) . Just saying it is here for some time already
