### ISSUE TITLE
mail-01.ac-cn-hongkong-c.eth.beta mailserver is not responsive

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6336]
### Description

*Type*: Bug

*Summary*: When app is connected to `mail-01.ac-cn-hongkong-c.eth.beta`, it can't fetch historical messages. Looks like the server is down. 

### Additional Information
* Operating System: all

**Comment by lukaszfryc** [comment]
@jakubgs do you know what is happening with this server? How I can check it by myself?

**Comment by lukaszfryc** [comment]
@cammellos the app chose this server automatically after I created an account. Is it a bug?

**Comment by cammellos** [comment]
@lukaszfryc the app should pick a random mailserver (if you never pinned it), if the mailserver is unresponsive, and the client knows it is, it should start picking mailserver in a round-robin fashion.

**Comment by lukaszfryc** [comment]
> if the mailserver is unresponsive, and the client knows it is

I guess that did not work or I did not wait long enough. @cammellos what's the logic/timeout behind "the client know it"?

**Comment by cammellos** [comment]
@lukaszfryc I think the client only checks that a connection can be established with the node, but the node might be unresponsive for other reason (long backlog of queues etc), @yenda can probably confirm as he knows that bit of code better.

**Comment by yenda** [comment]
It changes mail server after 2 timeouts of 30s. Is it not responsive or just very slow ? Provide some logs please. My guess is that it is just very slow because it's an Asian server and you are in Europe

**Comment by chadyj** [comment]
https://canary.status.im/icingaweb2/dashboard

<img width="507" alt="screen shot 2018-10-16 at 11 46 52 am" src="https://user-images.githubusercontent.com/116099/47007738-33f78280-d139-11e8-8c63-2ea22fc0b030.png">


<blockquote><div><strong><a href="https://canary.status.im/icingaweb2/dashboard">Sign In</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
thanks @chadyj! 

@yenda unfortunately, I do not have client logs from that session where app connected me to that mailserver (TF is gone). I will try to repro it later today

**Comment by lukaszfryc** [comment]
> It changes mail server after 2 timeouts of 30s. Is it not responsive or just very slow ? Provide some logs please. My guess is that it is just very slow because it's an Asian server and you are in Europe

@yenda unfortunately, I cannot replicate auto connecting to the unresponsive mailserver at this moment.

**Comment by lukaszfryc** [comment]
Btw, looks like `mail-02.ac-cn-hongkong-c.eth.beta` may also have some issues. Canary says it's UP but I do not receive any historical messages from this mailserver. I see "Fetching messages" appearing from time to time. Works fine when I switch to another mailserver. [Here is my logcat](https://gist.github.com/lukaszfryc/5126aab93a8b4d6a81d9ecc8561fbfaf).

**Comment by adambabik** [comment]
This should be in status-go btw. 

We have [metrics](https://prometheus.status.im/graph?g0.range_input=1h&g0.expr=rate(geth_mailserver_archivedEnvelopes_overall%7Bfleet%3D%22eth.beta%22%2Ccontainer%3D~%22statusd-mail.*%22%7D%5B10m%5D)&g0.tab=0) that actually shows that mail servers in HK (mail-01.ac-cn-hongkong-c.eth.beta and mail-03.ac-cn-hongkong-c.eth.beta) are doing poorly (red and blue respectively). 

![screen shot 2018-10-16 at 15 04 39](https://user-images.githubusercontent.com/277870/47018413-f6a0ee00-d154-11e8-80c6-bdec0c8c722f.png)

So the problem should be most visible for mail-01.ac-cn-hongkong-c.eth.beta and less visible for mail-03.ac-cn-hongkong-c.eth.beta. mail-02.ac-cn-hongkong-c.eth.beta should operate just fine.

**Comment by jakubgs** [comment]
Sorry, must have lost this one in all the github notifications.

![cpu](https://user-images.githubusercontent.com/2212681/47105940-5d84dc80-d213-11e8-8b6b-ba6598c05d3f.png)
![load](https://user-images.githubusercontent.com/2212681/47105942-607fcd00-d213-11e8-8662-707de4004f12.png)
![mem](https://user-images.githubusercontent.com/2212681/47105943-607fcd00-d213-11e8-9b22-3f9c61fbe9bb.png)
![net](https://user-images.githubusercontent.com/2212681/47105944-607fcd00-d213-11e8-9c95-6e3f636a8d9b.png)

It does seem like they have CPU and load spikes from time to time, like so:
![cpu_24h](https://user-images.githubusercontent.com/2212681/47106056-a3da3b80-d213-11e8-903d-7d17a8a03341.png)
![load_24h](https://user-images.githubusercontent.com/2212681/47106057-a3da3b80-d213-11e8-8eb4-fd4467e6647c.png)

The size of instance we are using there are `ecs.t5-lc1m2.small` which means:

Instance type | vCPU | Memory (GiB) | CPU credits/hour | Max CPU credit balance | Avg baseline CPU performance
-- | -- | -- | -- | -- | --
__ecs.t5-lc1m2.small__ | 1 | 2.0 | 6 | 144 | 10%
ecs.t5-lc1m2.large | 2 | 4.0 | 12 | 288 | 10%

@adambabik do you think I should bump it to a 2 CPU instance like `ecs.t5-lc1m2.large`?

**Comment by adambabik** [comment]
@jakubgs it's interesting that we use the same type of servers but the performance is so different... We can bump them to 2 vCPU and 4 GB mem and see if that helps. 

When I sshed on one of HK machine, it was visible that the server is struggling with CPU (load was high and everything was super slow).

**Comment by jakubgs** [comment]
It might be related to the concept of CPU credits that exists in Alibaba Cloud:
https://www.alibabacloud.com/help/doc-detail/59977.htm

>Each type of t5 instance provides a baseline level of CPU computing performance, which means that each vCPU core of an instance provides a maximum usage under normal workloads. For example, when the ecs.t5-lc1m2.small instance runs under normal workloads, the maximum CPU usage is 10%.

>Each t5 instance acquires CPU credits at a fixed rate based on the baseline CPU computing performance. A CPU credit is the unit for measuring computing performance, which is related to the number of vCPU cores, CPU usage, and running time. For example:

>t5 instances acquire CPU credits at 1-minute granularity. The CPU credit acquisition rate indicates CPU credits acquired by a t5 instance per unit time (minute). It is determined by the baseline CPU computing performance. The calculation formula is as follows:

So I've decided to try a different family of instances - `sn1ne` - meaning "compute optimized type family with enhanced network performance".

https://www.alibabacloud.com/help/doc-detail/25378.htm#sn1ne

Instance type | vCPU | Memory (GiB) | Local disks (GiB)* | Bandwidth (Gbit/s)** | Packet forwarding rate (Thousand pps)*** | NIC queues**** | ENIs*****
-- | -- | -- | -- | -- | -- | -- | --
ecs.sn1ne.large | 2 | 4.0 | N/A | 1.0 | 300 | 2 | 2

This type does not have a CPU credit system like `t5-lc1m2` family, so we'll see what happens.

**Comment by jakubgs** [comment]
Done and deployed: https://github.com/status-im/infra-eth-cluster/commit/b1ba291a86ecab319cb2b27c1395ddd32342634f

We'll see how the hosts will behave in thd coming days. But I think this issue shows that we either need more performance metrics from whisper/mail nodes or we need more graphs for already existing metrics, to measure performance of not just hosts but the nodes themselves.

I've added the `geth_mailserver_archivedEnvelopes_overall` metric Adam used to the dashboard as a start:
https://grafana.status.im/d/wV77E-4mz/statusd-metrics?orgId=1&from=1540148109197&to=1540191309197&var-host=mail.*&var-fleet=beta&var-dc=ac-cn-hongkong-c&var-dc=do-ams3&var-dc=gc-us-central1-a

**Comment by jakubgs** [comment]
Done and deployed: https://github.com/status-im/infra-eth-cluster/commit/b1ba291a86ecab319cb2b27c1395ddd32342634f

We'll see how the hosts will behave in thd coming days. But I think this issue shows that we either need more performance metrics from whisper/mail nodes or we need more graphs for already existing metrics, to measure performance of not just hosts but the nodes themselves.

I've added the `geth_mailserver_archivedEnvelopes_overall` metric Adam used to the dashboard as a start:
https://grafana.status.im/d/wV77E-4mz/statusd-metrics?orgId=1&from=1540148109197&to=1540191309197&var-host=mail.*&var-fleet=beta&var-dc=ac-cn-hongkong-c&var-dc=do-ams3&var-dc=gc-us-central1-a

**Comment by lukaszfryc** [comment]
The HK mailserver works fine now. I'm closing this issue.

**Comment by lukaszfryc** [comment]
Closing this issue as the HK mailserver works fine now.

**Comment by lukaszfryc** [comment]
Closing this issue as the HK mailserver works fine now.

**Comment by lukaszfryc** [comment]
Closing this issue as the HK mailserver works fine now.
