### ISSUE TITLE
Incorrect names for MKR, DGD, ETHOS and DATA tokens

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6340]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Tokens MKR, DGD, ETHOS, DATA have inconsistencies in names or/and symbols after comparing data from [tokens.cljs](https://github.com/status-im/status-react/blob/develop/src/status_im/utils/ethereum/tokens.cljs) with data from http://api.ethplorer.io/. 

#### Incorrect names and symbols:
- address 0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2: 
token name 'MKR', expected 'Maker'
- address 0xe0b7927c4af23765cb51314a0e0521a9645f0e2a: 
token name 'Digix DAO', expected 'Digix'
- address 0x5af2be193a6abca9c8817001f45744777db30756: 
symbol 'BQX', expected 'ETHOS', 
token name 'Bitquence', expected 'Ethos'
- address 0x0cf0ee63788a0849fe5297f3407f701e122cc023:
 token name 'DATAcoin', expected 'Streamr DATAcoin'

### Reproduction

- Get token info by address in https://api.ethplorer.io
e.g. `https://api.ethplorer.io/getTokenInfo/0x0cf0ee63788a0849fe5297f3407f701e122cc023?apiKey=freekey`

### Additional Information
* Status version: develop

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by andytudhope** [comment]
Maker specifically requested MKR: https://github.com/status-im/status-react/pull/6178

**Comment by goranjovic** [comment]
Related (as a general solution for this kind of problems) - #6509
