### ISSUE TITLE
Remove Instabug

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6346]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As user, I don't want my session details recorded or my data sent to third parties so that I can maintain privacy and security.

### Description

We are dealing with an issue with Testfairy that caused seed phrases in nightlies to be accidentally exposed and sent to a third party service. https://github.com/status-im/status-react/issues/6330

Just like Testfairy, we use Instabug for crash and bug reporting. It is not just used in nightlies, but is also used in release builds, and learning from our mistakes we should continue to remove third party services that harvest personal and device info and send these to remote servers.
 

### Solution

Remove Instabug from Status.

**Comment by lukaszfryc** [comment]
I tried to find some open source project as alternative for Instabug but there aren't many. I only found https://github.com/marcoarment/BugshotKit (iOS only).

If we really want to get rid of 3rd party solutions like Instabug, we could implement our own solution. This could be as simple as redirecting to default mail app with recipient and body partially filled (to: support@status.im, body: "I have an issue with.. I'm attaching screenshot.."). Or some more UX friendly in-app screen with the same things. I'd go for in-app solution to be able attach status-react and status-go (geth.log) logs.

**Comment by oskarth** [comment]
>  we really want to get rid of 3rd party solutions like Instabug, we could implement our own solution. 

Agree, e.g. shake to get to #requests-and-reports or so would be useful.

Don't think it should block removal of Instabug though.

**Comment by corpetty** [comment]
we need a way to get the logs of users who have a bug, and their personal description of what happened.  Isn't that about it?  I'd like the people who sort through these instabug reports to chime in here.

**Comment by lukaszfryc** [comment]
> I'd like the people who sort through these instabug reports to chime in here.

@corpetty It's me. I'm happy to remove Instabug provided users still can relatively easily let us know about their issues. So, let's first create alternative solution, maybe so simple like https://github.com/status-im/status-react/issues/6346#issuecomment-430280350 or shake to get to #requests-and-reports (maybe showing some info screen before it). And then, remove Instabug.

**Comment by chadyj** [comment]
I agree with Oskar. Let’s treat the replacement as a separate issue and for now just remove Instabug. We can go a release without Instabug feedback.

**Comment by lukaszfryc** [comment]
> I agree with Oskar. Let’s treat the replacement as a separate issue and for now just remove Instabug. We can go a release without Instabug feedback.

I think it is not a good idea. We have many Instabug reports every week from both old and new users. Without Instabug replacement, we will lose valuable feedback as well as disappoint some of the existing users.

I'd at least implement redirecting to #status-requests-and-reports public chat when "Submit a bug" or "Request a feature" buttons are clicked in "Help Center" in Profile. This should be really easy as we already have universal links.

**Comment by chadyj** [comment]
There is small UI change needed: Profile >  Need Help > 
We can remove “submit a bug” and “suggest a feature”. 

We can bring this back when we do the replacement.

**Comment by cammellos** [comment]
I would also consider not using status public-chats for bug reports, instead maybe email is preferable (emailto, could be both), but we don't want to rely on our own app to behave correctly in this cases (what if the problem is actually in publishing to public chats?)

**Comment by chadyj** [comment]
Great idea Lukasz. 

On the Need Help menu let’s add something like “Ask a question in #status”. Tapping that will open up the channel. 

Status is probably best for now as that is where the community hangs out.

**Comment by chadyj** [comment]
> but we don't want to rely on our own app to behave correctly in this cases (what if the problem is actually in publishing to public chats?)

Fair point. But big issues like that will be on our radar before users. After all we are chatting in pub chats to build Status.

**Comment by cammellos** [comment]
that's true, we might miss some that are more subtle and depends on the state of the device, I think it will be worth adding an email option eventually, but in the meantime seems like there's consensus:
1) Remove instabug
2) Change links in the help center to redirect to `#status`

anything else?

**Comment by oskarth** [comment]
One reason I like public chats for reporting is that it gives us an opportunity to directly engage with people. People can chat about issues, and see if something is already reported etc. I agree it shouldn't be the only way, but I don't think it's a bad idea to make it the primary way.

**Comment by lukaszfryc** [comment]
I agree that public chats are the best way to handle user feedback for us. It brings openess, engagement, etc. Sure, Status may not work but then, we already know about it as Chad mentioned.

>1. Remove instabug
>2. Change links in the help center to redirect to #status

Yes, I'd change links for “submit a bug” and “suggest a feature” to redirect to a public chat. For visibility, I'd use `#status` for now. Btw, I think this channel is already being used in this way.

**Comment by lukaszfryc** [comment]
> Yes, I'd change links for “submit a bug” and “suggest a feature” to redirect to a public chat. For visibility, I'd use #status for now. Btw, I think this channel is already being used in this way.

@chadyj could you confirm it? We could include it in the https://github.com/status-im/status-react/pull/6359 to have complete solution.

**Comment by chadyj** [comment]
@lukaszfryc yep this looks solid https://github.com/status-im/status-react/issues/6346#issuecomment-430566392
