### ISSUE TITLE
Cannot scan QR code of user because the qr code includes universal link

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6347]
### Description

*Type*: Bug

*Summary*: Scanning qr code results in "Wrong public key" since the qr code includes universal link.  Instead, scanning the code should open 1-1 chat with the user. This bug was introduced by https://github.com/status-im/status-react/pull/6331.

### Reproduction

- Scan QR code from profile tab

### Additional Information
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@rasom could you take this release blocker? It should be a quick fix.

**Comment by rasom** [comment]
ok
