### ISSUE TITLE
Bottom of scrollable area hidden by nav

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#635]
We should pad this so you can scroll/see full list even if just hidden.

![97069e800f190afe1070d9213e1e2d70_original](https://cloud.githubusercontent.com/assets/2714786/21708523/22a86b10-d40c-11e6-98cf-a29994c44e4f.jpg)

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/100

**Comment by carlbennetts** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/136

**Comment by Jas0n-F** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/133

**Comment by flexsurfer** [comment]
a different bottom gap appears on different devices because this https://github.com/leecade/react-native-swiper/issues/154
