### ISSUE TITLE
Add to Contacts tab does not appear

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/status-react#636]
It seems the friend request message does not display sometimes and gets Status into a state where you cannot add the friend as a contact or transact with them.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/76

**Comment by Jas0n-F** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/72
