### ISSUE TITLE
`make startdev-ios-simulator` overrides bundled status-go

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6367]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to be able to test new status-go locally. For that, I use `scripts/bundle-status-go.sh`. Unfortunately, if I run `make startdev-ios-simulator`, it overwrites the `Statusgo.framework` built by the bundling script. 
We should somehow preserve it.

**Comment by mandrigin** [comment]
cc @PombeirP maybe you can help to fix that...

**Comment by pedropombeiro** [comment]
@mandrigin looks like the file is being downloaded [here](https://github.com/status-im/status-react/blob/develop/Makefile#L53) and unzipped [here](https://github.com/status-im/status-react/blob/develop/Makefile#L85). I guess we need to figure out a way to avoid executing those steps if we see that there's a local version already there. I like the way we solve it on Android, we have separate folders for local and downloaded status-go, and we just add the local folder to Maven with a higher priority.

**Comment by mandrigin** [comment]
That would be the perfect solution but I’m not sure iOS is capable of it...

**Comment by pedropombeiro** [comment]
I imagine that if you put a second path for local files at above the line at https://github.com/status-im/status-react/blob/develop/ios/StatusIm.xcodeproj/project.pbxproj#L1884, it should work.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by cammellos** [comment]
Build system has been completely revamped, so closing for now
