### ISSUE TITLE
Build system: keep local cache of dependencies

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6376]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want stable builds on CI. Right now each build tries to download a lot of files from internet. If any of the services that we use to download from is down or something is wrong with any connection, build fails. That slows us down.

At the same time, we don't update our dependencies that often.

We need to investigate and find a way to properly cache these npm packages, jars, pods locally, so network usage is minimal.

In a perfect scenario, rebuilding the same commit again shouldn't even require any network connection.

**Comment by Swader** [comment]
One of the basics of good software development is NOT having your build system talk to the internet. This is absolutely essential, removing Stale.

**Comment by mandrigin** [comment]
> One of the basics of good software development is NOT having your build system talk to the internet.

I 100% agree with that. We have some local caches now. 

But in general the authors of npm, gradle and cocoapods seem to disagree with that statement 😢 , and fighting agains the tools looks not the most productive way to spend our time right now.

Closing
