### ISSUE TITLE
Connect to network via HTTP command fails

### ISSUE THREAD

**Issue by emizzle** [status-im/status-react#6378]
### User Story
As a developer, I want to interact with the Status app via HTTP commands so that I can issue commands from a JS library.

### Description
*Type*: Bug

*Summary*:
Running `POST` commands from Postman application.

#### Expected behavior
1. `POST` to `/network` > get `network-id` response
2. `POST` to `/network/connect` (passing in `network-id` from step 1 response) > get message "Network has been connected.", and the Status app connects to that network.

#### Actual behavior
1. `POST` to `/network` > get `network-id` response
2. `POST` to `/network/connect` (passing in `network-id` from step 1 response) > get message "Network has been connected.", however in the status app, I'm seeing an error dialog in the status app:
![iOS error](https://i.imgur.com/IZeZY8B.png)

After clicking OK to dismiss the dialog, I see a blank app and I'm forced to kill the app. When I reopen the app, I'm required to enter my password.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status
2. `POST` to `/network`:
```
{
    "name": "embark",
    "url": "http://localhost:8555", // <== Have also tried IP of my computer http://192.168.0.15:8555
    "chain": "embark",
    "network-id": 1337
}
```
get `network-id` response
3. `POST` to `/network/connect` (passing in `network-id` from step 2 response)

The network is added to the list of networks successfully. However, if I open the app, and try to connect to the newly created network, the app crashes. I suspect this is a similar error. If i re-open the app after the crash, Status is connected to that network.

### Solution
*Summary*: I would assume Status should not crash on this type of error.

### Additional Information
* Status version: 0.9.29
* Operating System: iOS v12.0 on iPhone 6

**Comment by asemiankevich** [comment]
which build is used here? i tried latest develop @jeluard @emizzle 

![image](https://user-images.githubusercontent.com/28752642/47201118-70b5ba80-d381-11e8-87b5-eba56a7c5f3e.png)

![image](https://user-images.githubusercontent.com/28752642/47201151-8925d500-d381-11e8-966c-9fd9bd46f6c1.png)

**Comment by emizzle** [comment]
I believe this is working in the latest release.
