### ISSUE TITLE
Cannot proceed to user profile from public chats

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6379]
### User Story

As a user, I want to view user profiles by clicking user pictures.

### Description

*Type*: Bug

*Summary*: the feature is lost in https://github.com/status-im/status-react/pull/6243, so for now user cannot proceed to user profile from public chat.

#### Expected behavior
user profile is opened

#### Actual behavior
<img width="341" alt="1_2" src="https://user-images.githubusercontent.com/4557972/47140661-7ea70500-d2c7-11e8-9561-25aa3e54615e.png">

nothing happens

### Reproduction

- Open Status
- Join any public channel
- Click on user profile pic

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 18/10/2018
* Operating System: mac OSx, Linux

**Comment by chadyj** [comment]
Thanks for logging.

Until this is fixed it kinda works if you click in a certain position, like top right of avatar.  If you click around you can usually get it to work.

**Comment by chadyj** [comment]
cc @flexsurfer

**Comment by chadyj** [comment]
This is working for me now.

**Comment by yenda** [comment]
@churik can you check that again ? It's working for me in current nightlies

**Comment by churik** [comment]
Cannot reproduce
