### ISSUE TITLE
Enable links within messages

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#638]
Currently links are plaintext within messages, we should parse these and make them navigatable. 

![e78894b9d23f872ecd3509942106e819_original](https://cloud.githubusercontent.com/assets/2714786/21708682/a2e9928a-d40d-11e6-9318-adfc0b1b806b.jpg)

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/113

**Comment by jarradh** [comment]
Message text needs to be parsed for urls and those areas made tappable and sent to !browse command

**Comment by rabbit** [comment]
ux note, typing uri scheme should be optional as it's annoying to type that on mobile

**Comment by jarradh** [comment]
high priority because how frequently and how useful this is

**Comment by rasom** [comment]
@alwx, sending url to `!browse` command is still needed to be implemented.
