### ISSUE TITLE
[Desktop] Dark color scheme

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6392]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to have choice between dark/bright themes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

*Summary*: Provide a theme switcher in settings that provides a theme with dark background.

One neutral color scheme might be the same as here: https://daringfireball.net

Foreground color: `#EEEEEE`
Background color: `#131D27`

<blockquote><img src="/graphics/favicon.ico?v=005" width="48" align="right"><div><strong><a href="https://daringfireball.net/">Daring Fireball</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@oskarth @andytudhope how to make a bounty out of this issue nowadays?

**Comment by mandrigin** [comment]
@errorists @denis-sharypin your input is also appreciated to iron out the details.

**Comment by oskarth** [comment]
Awesome! I defer to @andytudhope or @pablanopete for latest instructions/docs, not sure where they went.

**Comment by errorists** [comment]
Hey, happy to help but why is it desktop only? 😔

**Comment by mandrigin** [comment]
@errorists I would prefer having a separate issue for mobile... For making it an easier bounty.

**Comment by mandrigin** [comment]
@errorists mobile: https://github.com/status-im/status-react/issues/6392

**Comment by jakubgs** [comment]
Stop, just stop.
