### ISSUE TITLE
auto mail server selection UI

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6393]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to control over how mail servers are chosen.

### Description

By default Status will auto-select a mail server. It status encounters problems it will switch servers. 
 
Status will "pin" a mail server if a user selects a mail server, but there is no way to unpin it. Also, there is no UI indication if a mail server selection is set to auto or pinned.

This is quite confusing!

To help bring clarity we can introduce a explicit "select mail servers automatically" toggle. If this is on then Status will try to slect the best mail server. The mail servers are greyed out to indicate they cannot be chosen.

If "auto" is turned off then the mail servers switch back to regular colours and the selection is sticky.

Here is a quick mockup

<img width="706" alt="screen shot 2018-10-18 at 5 50 39 pm" src="https://user-images.githubusercontent.com/116099/47167522-04927280-d2ff-11e8-8185-d91f4544ae99.png">

THIS IS NOT A DESIGN, but rather a concept sketch. Would love to see @errorists @denis-sharypin take a crack at it.

#### Expected behavior
An auto option that will select mail servers automatically.
When turned off the mail servers can be chosen by the user.

#### Actual behavior
Confusing auto/pin behaviour merged.

### Additional Information

* Operating System: All

**Comment by mandrigin** [comment]
Also, it should behave like that on Desktop too.

**Comment by errorists** [comment]
Some small tweaks, thanks @chadyj for inspiration :) Also I'd love if we could trim down the text there in the toggle, I believe the emphasis on 'best' is important there to understand on what basis is the mailserver selected. 

<img width="767" alt="screenshot 2018-10-19 at 10 02 35" src="https://user-images.githubusercontent.com/4932774/47205438-369ae780-d386-11e8-97fe-4e834cafe4b6.png">

Designs are in this [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=1%3A3) Desktop is exactly the same.

**Comment by chadyj** [comment]
cc @cammellos We discussed something like this in the past

**Comment by pedropombeiro** [comment]
One suggestion that seems to be missing in this issue is that the app should be able to determine that a mailserver is unreachable/unreliable and therefore propose (with a message box) to unpin the pinned mailserver (i.e. enable autoselect).

**Comment by EugeOrtiz** [comment]
[Here the designs for desktop](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=763%3A2331) (Figma)

**Comment by churik** [comment]
closed in #7637
