### ISSUE TITLE
Add custom url support to Linux

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#6394]
### Description

Add custom url support to Linux (MacOS support was added in https://github.com/status-im/status-react/issues/5038)

Links like "status-im://chat/public/status" should open "status" public chat in Status app (https://wiki.status.im/Universal_Links)

### Solution

Possible option might be using `xdg-open` that might work on most linux window managers (gnome, kde, xfce). 

On Ubuntu, I was able to open Status app (just start the app without being redirected to chat screen) by using this configuration:

Create handler config:
```
$ cat ~/.local/share/applications/status-im.desktop 
[Desktop Entry]
Name=status-im
Exec=/home/dmitryn/Downloads/StatusIm %u
Type=Application
Terminal=false
MimeType=x-scheme-handler/status-im
```

Register handler:
```
$ cat ~/.local/share/applications/mimeapps.list 
x-scheme-handler/status-im=status-im.desktop
```

Run app:

```
xdg-open status-im://chat/public/status
```

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
fuck off bot
