### ISSUE TITLE
[Mobile] Dark color scheme

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6399]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to have choice between dark/bright themes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

*Summary*: Provide a theme switcher in settings that provides a theme with dark background.

One neutral color scheme might be the same as here: https://daringfireball.net

Foreground color: `#EEEEEE`
Background color: `#131D27`

<blockquote><img src="/graphics/favicon.ico?v=005" width="48" align="right"><div><strong><a href="https://daringfireball.net/">Daring Fireball</a></strong></div></blockquote>

<blockquote><img src="/graphics/favicon.ico?v=005" width="48" align="right"><div><strong><a href="https://daringfireball.net/">Daring Fireball</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@errorists can you provide some mockups/colorscheme, so we can make a bounty out of it?

**Comment by errorists** [comment]
@mandrigin I know it's a recurring request, however I'm strongly against theme'ing the UI until we actually fix it and arrive at a point where we can rest assured that the stuff in production resembles what we've designed in Figma and our interface is a solid foundation to build on. Sorry Igor, but I must decline. I'd love to help out tho however I can in making the UI we have now performant and designed to not be shy about anything compared to native apps.

**Comment by mandrigin** [comment]
okay, sure, closing this issue then
