### ISSUE TITLE
Laggy emoticon scrolling

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#640]
When scrolling through emoticons there is some delay/lag.

Reports:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/47

**Comment by jarradh** [comment]
issue with upstream react-native-emoji-picker component

**Comment by rasom** [comment]
looks like we can close this issue, @annadanchenko could you please confirm?

**Comment by annadanchenko** [comment]
can't access Instabug issue but there is no lag on Galaxy S6 and iphone 5s, so closing the issue
