### ISSUE TITLE
Log-in activity indicator

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#641]
When logging into an account, an animation, or something to indicate to the user that the login is in progress.

Reports:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/46

**Comment by annadanchenko** [comment]
* Instabug: 
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/250
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/265
  * https://dashboard.instabug.com/applications/status/beta/bugs/125
  * https://dashboard.instabug.com/applications/status/beta/bugs/124
  * https://dashboard.instabug.com/applications/status/beta/bugs/120
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/308
  * https://dashboard.instabug.com/applications/status/beta/bugs/183

**Comment by annadanchenko** [comment]
Note that activity indicator is needed not only for log in action but also for other time consuming operations, like loading DApp

**Comment by rasom** [comment]
@jarradh we already have some default animation, can we close this issue?

**Comment by sla-shi** [comment]
@annadanchenko pls list the screen where the activity indicator is appropriate.

**Comment by sla-shi** [comment]
@andmironov pls confirm that we're using system (not custom) activity indictor on both platforms.

**Comment by sla-shi** [comment]
I checked the login activity indicator is implemented in 0.9.11.
