### ISSUE TITLE
Add gist support to extensions again

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6411]
### Description

*Type*: Bug

*Summary*: gist support is gone when implementing validation that forces user to use Pluto to create extensions.

#### Expected behavior

both gist and ipfs are allowed as extension providers

#### Actual behavior

pluto allows to install extensions from url, but Status doesn't because of this validation function:

```(defn valid-uri? [s]
  (boolean
   (when s
     (re-matches (re-pattern (str "^" uri-prefix "\\w+@\\w+")) (string/trim s)))))```

**Comment by jeluard** [comment]
Fixed by @alw
