### ISSUE TITLE
"Connecting to peers" error after setting custom time until restarting app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6414]
### Description

*Type*: Bug

*Summary*: when you set custom time and go back to status app, "Connecting to peers" error appears and you cannot send/receive messages for a while.
Can be reproduced on Android, desktop, on IOS several times I saw the same issue, but sometimes it is just unusable until restarting (history for chats is missed, you cannot send message. Video is [here](https://monosnap.com/file/X1vojOH6aAi2dJDG6jZYsHEFfTLjsS) )

#### Expected behavior
can send / receive messages and browse history or app requires restarting

#### Actual behavior
"Connecting to peers" error

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join any public channel
- Open time preferences
- Change time
- Open Status again (from background)

### Additional Information

* Status version: nightly 19/10/2018
* Operating System: Android 7.0, iOS 11.4, Mac OSx 10.13.6

#### Logs

* StatusIm.log (desktop): [StatusIm_time.log](https://github.com/status-im/status-react/files/2495860/StatusIm_time.log)
* Geth.log  (desktop): [geth_time.log](https://github.com/status-im/status-react/files/2495854/geth_time.log)
* Video (IOS): [IOS](https://monosnap.com/file/X1vojOH6aAi2dJDG6jZYsHEFfTLjsS)
* Video [Android, after setting time](https://monosnap.com/file/YYOl7QjOekD95MbSS8E9oc4Vi5YwJk)

**Comment by churik** [comment]
On IOS and Android I see constant flickering "Offline" message until restarted app

**Comment by yenda** [comment]
@mandrigin it seems odd that restarting the app works, is status-go fixing time somehow when starting the node?

**Comment by mandrigin** [comment]
@yenda we should have an independent time sync to make sure that messaging works if your time is off. But probably we don't detect the edge case when the time becomes off suddenly 😆
