### ISSUE TITLE
Messages sent when "Connecting to peers" is displayed will be lost

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6415]
### Description

*Type*: Bug
*Summary*: "Connecting to peers" error doesn't lead to disappearing "Send" button, so you can type and send message but in fact it will not be sent. The same for desktop - you can send message, it will be shown in "Sent" state, but in fact will be never received.

#### Expected behavior
**Mobile**
button is hidden on mobile. If for some reason user sent a message before the send button was hidden, there should be a spinner when the message is trying to be sent. It it's not sent after a timeout, the "Not sent. Tap for options" status with resend option. Refer to https://github.com/status-im/status-react/pull/3964 if you need details of how resend should work.

<img width="200" alt="offl" src="https://user-images.githubusercontent.com/7532782/47304501-2190b380-d627-11e8-9bec-295ad5311984.png"> 

**Desktop**
"Not sent" status on desktop (like for Offline mode).

#### Actual behavior
message status is Sent, but in fact messages are lost
<img width="437" alt="genymotion for personal use - samsung galaxy s7 - 7 1 0 - api 25 - 1440x2560 1440x2560 640dpi - 192 168 58 101 2018-10-19 16-10-30" src="https://user-images.githubusercontent.com/4557972/47220363-40d6d900-d3ba-11e8-8e31-b197df58c959.png">

### Reproduction

- Open Status
- Trigger "Connecting to peers" (for exapmle like in issue https://github.com/status-im/status-react/issues/6396 or https://github.com/status-im/status-react/issues/6414)
- Send message

### Additional Information

* Status version: nightly 19/10/2018
* Operating System: Android, iOS, Mac OSx

#### Logs

* StatusIm.log (desktop): [StatusIm_time.log](https://github.com/status-im/status-react/files/2495860/StatusIm_time.log)
* Geth.log  (desktop): [geth_time.log](https://github.com/status-im/status-react/files/2495854/geth_time.log)

Consequence of  https://github.com/status-im/status-react/issues/6414 or https://github.com/status-im/status-react/issues/6396, but I believe should be fixed separately and has higher priority IMO.

**Comment by lukaszfryc** [comment]
I also replicated it today on release/0.9.30. 

cc @chadyj @mandrigin

**Comment by lukaszfryc** [comment]
More context: when Status detects that you are offline, the send button will be hidden. But, it may happen that you may sent a message before the app knows the device is offline. In that case, the message is lost but marked as "sent". Btw, there is no "resend" functionality (https://github.com/status-im/status-react/issues/6449).

@chadyj do you consider it a blocker for release 0.9.30?
