### ISSUE TITLE
Timestamps for messages doesn't match real time if user send message from device with custom time

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6419]
### Description

*Type*: Bug
*Summary*:  when anybody send a message from device with custom time (not another timezone, but custom time, i.e. when there is 10:00 UTC, and user set 09:45) - timestamps for such messages are shown with difference in minutes from nearest timezone, so in chat it looks like wrong message ordering (but it is not, wrong are message timestamps)

#### Expected behavior
timestamps for messages are set according to real message ordering and receiver time settings;

#### Actual behavior
timestamps for messages sent from device with custom time don't match real time
<img width="568" alt="us_t" src="https://user-images.githubusercontent.com/4557972/47223441-9494f280-d3b9-11e8-88d6-98bb1bd9a4db.png">

### Reproduction

*Prerequisites:* for `User A` timezone and time is set automatically; for `User B` time is custom and set 10 minutes earlier)

- `User A`: open Status, join any public channel (i.e. #chuone), send message 
- `User B`: open Status, join any public channel (i.e. #chuone), send message 
- `User A`: check chat history

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 19/10/2018
* Operating System: Android, iOS, desktop

**Comment by SlizkovaGanna** [comment]
Reproduces for me also

<img width="668" alt="image" src="https://user-images.githubusercontent.com/43638377/49367680-6ebb7700-f6f5-11e8-96ca-4e14ddbe2321.png">

**Comment by 0xc1c4da** [comment]
➤ Hester Bruikman commented:

Data sync might improve situation; still inherent to peer-to-peer network.

Can give impression that connectivity is lost even though messages was received, but message order got displaced. How to make sure it's clear that a dated messages is received.

Compare timestamps (local + Whisper timestamp). Define behavior for message based on threshold while preventing 'faking' of historic messages.

**Comment by churik** [comment]
Not reproducible anymore
