### ISSUE TITLE
Can't enter seed to recover password. Random characters generated when typing 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6426]
### Description

*Type*: Bug

*Summary*: 

Ben reported ([Instabug](https://dashboard.instabug.com/applications/status-6b2838c6-8064-445d-ae12-3c35e96f3a69/beta/bugs/637)) that he can't type his seed in the recovery screen. He's getting random characters when trying to type. He's getting the issue on 0.9.29 and latest nightly (Oct 12). He said that the issue does not happen in other apps or previous Status versions. 

This issue maybe react-native issue and may happen only on a very small subset of devices. https://github.com/status-im/status-react/issues/379 is related. Ben uses HUAWEI CLT-L29, OS Level 27.  
 
No steps to reproduce. Maybe device specific.

### Additional Information
* Status version: 0.9.29
* Operating System: happened on Android

**Comment by Swader** [comment]
Reproducible on OnePlus 6T, Android 9, Status 0.9.33. The characters are not random, but a randomly repeated set of already typed characters. Each keypress copies what was already typed, including the backspace to delete. So if I try to type `test` I get:

- t
- tte
- ttettes
- ttettestest

Punching backspace will then copy this set and remove one char.

- ttettestestttettestes
- ttettestestttettestesttettestestttetteste
- ttettestestttettestesttettestestttettestettettestestttettestesttettestestttettest

Holding backspace successfully deletes it all.

Pasting the content works fine, but any keyup event that is NOT the backspace in the first try will cause this copying. Ergo, I was able to paste in my recovery phrase and delete the extras from the end without a problem.

Here is a gif of what it looks like.

![20181207_123529_edited](https://user-images.githubusercontent.com/1430603/49648315-a001b300-fa25-11e8-8fa3-41fce64ef083.gif)

**Comment by mandrigin** [comment]
@Swader It might be a react-native issue. 

Does it happen with any custom keyboard? If you use a default one, can you install a custom one (SwiftKey, GBoard or something) and try to reproduce the issue with this text field?

---
@rasom do you remember we had something similar in the past?

**Comment by Swader** [comment]
It happens with Swiftkey. 
It does not happen with GBoard.

**Comment by Swader** [comment]
Unbelieveable

**Comment by churik** [comment]
Can't reproduce it with Swiftkey keyboard on redesigned flow in Status v1.0.1
