### ISSUE TITLE
Chats are not sorted by time if messages received when user deleted app data

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6427]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When user removes all the app data, receives messages in 1-1 chats and after that recovers his account chats are not sorted by time

#### Expected behavior
Chats with the latest messages are shown on top

#### Actual behavior
Chats with the latest messages are shown after chats with older messages 
<img width="339" alt="screen shot 2018-10-19 at 19 09 47" src="https://user-images.githubusercontent.com/29711298/47230463-eeee7d00-d3d2-11e8-8940-50af3828d295.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account (user A)
- Delete app data from the device
- Send messages to the user A from users B,C,D
- Recover the user A account

### Additional Information
Status version: Oct 19 nightly build - 0.9.30 (11016); node 0.16.3
Operating System: Android, iOS, MacOS

**Comment by yenda** [comment]
could be solved by sorting chats by timestamp of last message in subs
