### ISSUE TITLE
White screen appearing on contacts page

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#643]
White screen:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/45

Back button causing similar issue:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/44

Steps to reproduce:
1. Tap contacts icon in tray
2. Tap back button on device
3. Tap any tray icon again

**Comment by Jas0n-F** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/145

**Comment by flexsurfer** [comment]
not reproduced, because https://github.com/status-im/status-react/issues/747 , now back button exit the application from any tab screen

**Comment by flexsurfer** [comment]
@jarradh i think we can close this issue

**Comment by jarradh** [comment]
let's close, if it happens again someone will tell us :)

**Comment by jarradh** [comment]
reproduced in latest nightly

**Comment by flexsurfer** [comment]
![image](https://cloud.githubusercontent.com/assets/11790366/22797560/c3749a8c-ef0f-11e6-894f-4c2555efe6aa.png)
chat-list always in the :navigation-stack
