### ISSUE TITLE
[ios] [nightly builds] password is printed in the logs when "Save password" option is used

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#6430]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: password is printed in the logs when "Save password" option is used

#### Expected behavior
no password in the logs

#### Actual behavior
password in the logs

### Reproduction

1. on iOS create account
2. log out
3. on Sign in screen turn ON toggle to Save password until login
4. type password and login
5. close app
6. launch app and wait till app will sign in automatically
7. check console log for the password

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] wrap password with `security/mask-data`
- [ ] stop printing of re-frame events' parameters

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly
* Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
default	16:42:31.648572 +0300	StatusIm	DEBUG [status-im.utils.handlers:36] - Handling re-frame event:  :accounts.login.callback/get-user-password-success mypassword
```

**Comment by annadanchenko** [comment]
note that issue happens only in nightly and PR builds. Releases in testFlight are not affected.
