### ISSUE TITLE
Fiat value is 0 in transaction request messages for both request sender and recipient

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6432]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Fiat value if shown as 0 when sending a transaction request from 1-1 chat

#### Expected behavior
Transaction request messages contain correct fiat value in selected currency 

#### Actual behavior
Fiat value is 0 in a transaction request messages for both sender and recipient
<img width="339" alt="aaa" src="https://user-images.githubusercontent.com/29711298/47259682-cbe8c980-d4b5-11e8-9106-b432f1e9b1d2.jpeg">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on 2 devices
- Create users A and B
- Users A and B add each other as contacts
- User A requests funds from user B in 1-1 chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.30 (11083); node 0.16.3
* Operating System: Android, iOS

**Comment by annadanchenko** [comment]
@yevh-berdnyk @janherich it's expected that fiat value for *test* ETH and tokens on Ropsten is 0, as test ether has no value. As I can see on mainnet fiat value is shown as expected. 
![screenshot_20181021-102852](https://user-images.githubusercontent.com/6584810/47264282-58c66e00-d51c-11e8-9f92-ce4abd1af898.png)

**Comment by annadanchenko** [comment]
@goranjovic for some reason, expected 0 value for Ropsten and Rinkeby ETH and tokens is already in develop build, even before https://github.com/status-im/status-react/pull/6388 is merged.

**Comment by goranjovic** [comment]
@annadanchenko @yevh-berdnyk That's ok, it's because of the previous PR #6260 which is already in develop. The one corner case that's not done by #6260 is when sender and receiver are on different networks, but the fix for that is addressed in #6388

Closing this issues as it's fully covered by those two PRs
