### ISSUE TITLE
Duplicated letters in passphrase input with selected Shift key

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6434]
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Letters are duplicated if Shift button is double clicked on passphrase input field when recovering an account 

#### Expected behavior
Letters are entered one by one 

#### Actual behavior
Letters are doubled 
This one supposed to be an `apple`:
<img width="339" alt="aaa" src="https://user-images.githubusercontent.com/29711298/47260054-ae6b2e00-d4bc-11e8-9c61-76948450fd54.jpg">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click `I already have an account` button
- Double click Shift button and start typing a passphrase

### Additional Information
Status version: 0.9.30 (11083); node 0.16.3
Operating System: OnePlus 5, Android 8.1

**Comment by rasom** [comment]
One of the solutions here might be the usage of [autoCapitalize](https://facebook.github.io/react-native/docs/textinput#autocapitalize)='characters'. As long as all characters will be capitalized no need to care about the shift button. 
TextInput's controlled value is quite buggy in RN, so it might be not worth fixing it other way.

**Comment by Swader** [comment]
Not stale.

**Comment by churik** [comment]
Can't reproduce it with Swiftkey keyboard on redesigned flow in Status v1.0.1
