### ISSUE TITLE
Duplicate request messages in 1:1 chat after upgrade from 0.9.29

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#6438]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
Before upgrade there is one request for ETH and one for SNT. After upgrade both requests are shown twice. Before upgrade user switched from mainnet (where requests are sent) to ropsten.

After upgrade:
![after](https://user-images.githubusercontent.com/6584810/47281973-123d4600-d5e6-11e8-91e7-ebc6d7fc2a58.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After upgrade same messages are shown. There are no extra messages
#### Actual behavior
[comment]: # (Describe what actually happened.)
each received request message is shown twice 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- On Android: install 0.9.29 from PlayStore or from apk https://drive.google.com/open?id=1PHnITeXCp3DZGhmhq0SMhjTgcOoUDBe8 (it's same apk as on PlayStore)
- On iOS install 0.9.29 from TestFlight
- both are on mainnet
- iOS: add Android to contacts by scanning QR code and send message "hi from ios"
- Android: open 1:1 chat with iOS, add it to the contacts and send message "hi from android"
- android: send request of 1 ETH in 1:1 chat
- iOs: send request of 2 ETH in 1:1 chat
- iOS: send request of 333 SNT in 1:1 chat
- iOs: send text message and emoji in the same line
- Android: send text message "Thanks"
- Android: switch to Ropsten
- Android: check that you can login and messages look ok (no duplicates)
- Android: upgrade to release build 
- Android: login, wait for messages to be fetched and check messages in 1:1 chat. In my case there are 2 new messages shown for chat, if open chat then each of request messages from iOS is shown twice

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: upgrade from 0.9.29 to release build 15
* Operating System: Android

#### Logs

[logcat.txt](https://github.com/status-im/status-react/files/2500485/logcat.txt)

**Comment by lukaszfryc** [comment]
I can replicate this issue using the same steps (with switching to Ropsten). But, I could not replicate it without switching to Ropsten first (tried 1 test so far).

cc @annadanchenko

**Comment by lukaszfryc** [comment]
I can replicate it using the same steps (with switching to Ropsten). But, I cannot replicate it when without the network switch.

**Comment by chadyj** [comment]
Fixed in https://github.com/status-im/status-react/pull/6488
