### ISSUE TITLE
App crash on empty password at confirmation.

### ISSUE THREAD

**Issue by joshuam10o** [status-im/status-react#644]
Incorrect password at the transaction confirmation screen seems to work fine, but if I leave the password field empty, and attempt to confirm the transaction, the app crashes.

also, related: the password prompt is very discreet and easy to miss.

**Comment by jarradh** [comment]
Thanks for the issue! yes, agreed on both points 
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/91

**Comment by carlbennetts** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/130
