### ISSUE TITLE
[DESKTOP] Push notifications for DM only

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#6445]
# Problem

Enabling push notifications on desktop gives you notifications for all public channels. This is way too noisy and there's no option to just get notifications for DMs, like mobile, as far as I can tell.

# Implementation

Use same code as mobile, or similar with relevant abstraction.

# Acceptance Criteria

Allow for notifications for DMs only and not public chats.

# Notes

N/A

# Future Steps

N/A

**Comment by EugeOrtiz** [comment]
We should only have push notifications for:

1. New 1:1 chat message
2. Someone mentions the @user in a public or group
3. Somebody replies directly to user's message in a group or public chat

**Comment by EugeOrtiz** [comment]
See PN[ designs and specs here](https://github.com/status-im/status-react/issues/6621)

**Comment by churik** [comment]
Still relevant
