### ISSUE TITLE
Localethereum seemingly not supported by Status

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#6446]
# Problem

As a user I want to be able to onboard to crypto with the most secure and best UX possible. Specifically I'd like to be able to use localethereum with Status to go from fiat to ETH as soon as possible.

This is possible in imToken etc and many others https://blog.localethereum.com/localethereum-integrates-with-wallets/

# Implementation

- Ensure officially supported
- Work out any necessary kinks

# Acceptance Criteria

Can use localethereum with Status seamlessly.

# Notes

https://blog.localethereum.com/localethereum-integrates-with-wallets/

# Future Steps

This is a recurring thing, where the best/most usable dapps (etc) are often not working in Status. It'd be useful to do some kind of audit (wallet/dapp front) and more BD on this front. E.g. Localethereum, Peepeth, Ledger HW wallet (MM, so via Desktop presumably).

<blockquote><img src="https://blog.localethereum.com/assets/images/blog/external-wallet/2.png" width="48" align="right"><div><img src="/assets/images/favicon-128.png" height="14"> localethereum.com's official blog</div><div><strong><a href="https://blog.localethereum.com/localethereum-integrates-with-wallets/">LocalEthereum Now Integrates With Popular Ethereum Wallets</a></strong></div><div>You can now connect your favourite wallet to localethereum instead of using a username and password. Sign a message with your wallet to log in, and funds will go directly to and from your wallet.</div></blockquote>

**Comment by Swader** [comment]
Keepalive

**Comment by oskarth** [comment]
@rachelhamlin @jeluard Was there any follow up to this?

**Comment by rachelhamlin** [comment]
@oskarth the latest update is still our email thread from November. I wasn't aware of this specific issue, but as you can see from our swarm docs, localeth integration isn't a q1 browser item.

List here again: https://notes.status.im/browser-research

What would you like to happen?

**Comment by oskarth** [comment]
Well, the main thing I'm aware is missing is a follow up in this issue.  @Swader felt the same, evidently.

Does localethereum work seamlessly in Status now (acceptance criteria)? It isn't clear from email thread. We also never did an announcement like e.g. imToken afaik, so seems like a missed opportunity for low effort partnership.

Last time around it seemed like a small thing, so not sure it makes sense to treat it like a big milestone or anything. If there's anything they need to do, perhaps a ping with a note in this issue would be useful?

@Swader is there something specific you are missing in this regard?

**Comment by rachelhamlin** [comment]
Can't follow up on issues I'm not tagged on :) 

Last time I checked, localethereum does work in Status. I will check again today. Although there might be more we can do to integrate—I haven't looked at other wallet's support—I wasn't planning to follow up on it for the reasons explained (plus Teller Network work).

**Comment by jeluard** [comment]
I just checked now and it looks like it works fine with privacy mode enabled. They even have a nice status logo.

@Swader @oskarth Are you aware of specific issues?

**Comment by Swader** [comment]
Nope. Can be closed. Just checked too and it seems fine. I was mainly pinging a keepalive to encourage this specific discussion and tests from various parties - exactly the kind of feedback an issue should have before being closed. Can be closed now :)

**Comment by oskarth** [comment]
Great, cheers all!

**Comment by oskarth** [comment]
@rachelhamlin you are right, I forgot to ping you in the initial message. My bad.

@Swader @jeluard did you do the whole user journey, including escrow etc, or just front page?

Anyway, agree it can probably be closed. Cheers all!

**Comment by Swader** [comment]
@oskarth only front page, status doesn't work for me on Android all that well so right now it's a bit tough to go through the whole process.
