### ISSUE TITLE
Status marked as battery draining app on Android Samsung S6

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#6447]
#  Problem

Status is marked as a battery draining app by App power monitor on Android. This is obviously a big problem as people will remove apps that drain too much problems. It appears it is due to using battery in the background, unlike other apps.

This problem happens within a few minutes of launching the app and has been reported by many users.

# Implementation

Do whatever is necessary to get rid of this.

# Acceptance Criteria

Make it disappear consistently.

# Notes

This has been reported so many times it isn't funny, and it is so easy to detect.

# Future Steps

Ensure automatic tests of this.

**Comment by oskarth** [comment]
If someone is willing to bet $50 or more they fixed the problem dac-zero (https://discuss.status.im/t/sitg-experiment-2-dac0-liquid-pledging/426) is willing to pay $500, provided you opted in to the SNT pool (https://discuss.status.im/t/be-part-of-the-dao-nao/507).

<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/sitg-experiment-2-dac0-liquid-pledging/426">SITG Experiment #2 - DAC0: Liquid pledging</a></strong></div><div>Welcome to Skin In The Game experiment two! While sitg-one is ongoing, this time we’ll doing something a bit differently, namely play around with a liquid pledging model. As before, we assume a trusted setup (see previous post as to why this is an OK assumption for now).  This experiment directly targets Q3 OKRs re Liquid pledging.  Pre-requisite reading  Future of Giving: https://medium.com/giveth/what-is-the-future-of-giving-d50446b0a0e4  Overview of liquid pledging: https://wiki.giveth.io/doc...</div></blockquote>
<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/be-part-of-the-dao-nao/507">Be part of the DAO NAO</a></strong></div><div>Organizations in the future will be permissionless. They will enable individuals within the organization to fund innovative ideas without any oversight, or permission required from ‘management’. This is another experiment for testing these new funding methods on a small scale, to help us iterate towards a less centralized compensation model.  The goal here is to make compensation more transparent, meritocratic, and more profitable for core contributors. While simultaneously making core contribut...</div></blockquote>

**Comment by lukaszfryc** [comment]
>It appears it is due to using battery in the background, unlike other apps.

@mandrigin @yenda do we have a clear understanding what is causing it? If not, how we can research it?

**Comment by oskarth** [comment]
It'd also be great to understand why this wasn't an acceptance criteria for the swarm/team that dealt with this over a period of a few months. I know we made huge improvements, but this seems like a pretty clear cut case of either it works (according to Android battery monitor, which end users trusts) or it doesn't?

**Comment by oskarth** [comment]
^ @chadyj fyi

**Comment by mandrigin** [comment]
@oskarth thanks for creating this issue, finally.

I'll document my decision chain here.

unlike on iOS, on Android, devp2p node keeps running in the background, that helps Whisper to receive messages even when the app is minimized w/o mailservers.

That is what probably causes SGS app power monitor to freak out. So, there is a compromise between receiving more messages w/o mailservers and app power monitor messages.
I don't think there is a way to keep p2p connections alive in any way in background if we want to address this issue (the required heartbeat is way shorter than the time needed for the battery monitor to stop complaining).

So, we can either keep doing what we are doing now, or change the behaviour and stop the node when the app is backgrounded.
Maybe with the new changes to the mailservers (batch receiving, etc), it might make sense to completely switch to them.

**Comment by oskarth** [comment]
I think it makes sense to do what default Android and iOS apps do and power off by default. Can be advanced mode to turn on battery intensive background fetching.

What do normal mail apps do?

**Comment by mandrigin** [comment]
@oskarth normal apps don't keep multitudes of p2p connections. It's hell of a lot easier not to keep a connection if you only make requests to some rest/soap/graphql APIs.
They can just sync once a few minutes because the response time is very predictable.

**Comment by mandrigin** [comment]
but sure, we can shutdown the node, it will just take a few more seconds to get your messages when you return from background.

**Comment by oskarth** [comment]
No takers for the offer yet. Since I believe this should be a core responsibility, and SNT pool looks likely to change with move to Network, I'm hereby revoking the above extra bounty.

(We can still use a bounty for this, just think there are more valuable things for me to stake my own personal funds to further Status right now. It also makes my own fund management easier so I don't hand out IOUs everywhere :P).

**Comment by Swader** [comment]
Still active

**Comment by Swader** [comment]
![](https://matrix.org/_matrix/media/v1/download/matrix.org/WUIqHOhLSVLhbnqdtQGfQHif)

**Comment by hesterbruikman** [comment]
@Serhy do you know if this is still relevant? I can only test Android 7 :/

**Comment by Serhy** [comment]
Can't reproduce with Android 6.0.1 (Galaxy Note 4)
Also Samsung S6 comes with Android 5 which we do not support.
We didn't have any reports for draining battery after V1 (and especially after Waku upgrade).
This is not relevant anymore, @hesterbruikman

**Comment by hesterbruikman** [comment]
Thanks for checking!
