### ISSUE TITLE
Reply message snippet is not scrollable in chat

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6451]
### Description

*Type*: Bug

*Summary*: 

According to the [design guidelines](https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5b5abafd892d5c933636787d), the reply area/box in a chat should be scrollable to see the full message. Currently it's not.

#### Expected behavior

<img src="https://user-images.githubusercontent.com/7532782/47293301-06637b00-d60a-11e8-8670-f2353f710e48.png" width="200">

#### Actual behavior

The area can't be scrolled: 

<img src="https://user-images.githubusercontent.com/7532782/47293218-ce5c3800-d609-11e8-9f58-9195a638ba30.png" width="200">

### Reproduction

Try to reply to a long message in 1-1 or public chat.

### Additional Information
* Status version: Oct 22, nightly
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
@lukaszfryc I have to rename this to `Reply message snippet is not scrollable in 1x1 chat` what clearly indicates problem and location of the problem

**Comment by lukaszfryc** [comment]
@asemiankevich it's for all chats.

**Comment by asemiankevich** [comment]
@lukaszfryc still should be readable and searchable

**Comment by churik** [comment]
closed after RN-upgarde in nightly 02/04/2019
