### ISSUE TITLE
Push notifications are closed on click instead of redirection to app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6453]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have options "close" and "reply" on PN (like in other messages) and to be redirected to appropriate chat when I click on PNs.

### Description

*Type*:  Bug

*Summary*: PNs on both MAC OSx and Linux don't have options "Close" and "Reply" for quick responses. When I click on PN on Mac OSx - it doesn't maximize window when it is minimized, PN is just closing. On Linux Ubuntu for me on click nothing happens, except that PN becomes a bit blurred.

#### Expected behavior
Can quickly reply to message, on click will be redirected to channel

#### Actual behavior
PNs don't have "Close" and "Reply" options; on click app doesn't become active and isn't maximized.

### Reproduction

- Open Status
- Join any public channel
- Go to profile and turn on Notifications
- Send any message to public channel from another device
- Hover on PN
- Click onPN

### Additional Information

* Status version: nightly 22/10/2018
* Operating System: Linux Ubuntu 16.04
* Video (Linux): http://take.ms/FK9Dr
* Video (Mac OS): http://take.ms/IvDjFw

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=ZG4gQLJxmD1Hyp61azVoBtSCAmiQQw&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/ZG4gQLJxmD1Hyp61azVoBtSCAmiQQw">File "screencast 2018-10-22 15-13-58.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>
<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=6hCy81UzwLD9dUv4M7vj346TfPsDDd&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/6hCy81UzwLD9dUv4M7vj346TfPsDDd">File "screencast 2018-10-22 14-52-32.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by SlizkovaGanna** [comment]
This issue is still very much valid.
For Linux 2.6, when app is opened, clicking on PN maximises the app - but the expected chat is not opened.

**Comment by churik** [comment]
Not stale
