### ISSUE TITLE
Can get only 3 push notifications on Mac OS x unless make cleanup of notification center

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6458]
### Description

*Type*:  Bug

*Summary*: in Mac OSx amount of PNs are restricted to 3, so when you reached the limit you should manually clean notification center to get another 3 notifications.

#### Expected behavior
Can see all notifications, if their amount is restricted - just replaced last notification with the content of new

#### Actual behavior
you can get only 3 notifications

### Reproduction

- Open Status
- Join any public channel
- Go to profile and turn on Notifications
- Send 4 messages to public channel from another device
- Check PNs on desktop

### Additional Information

* Status version: nightly 22/10/2018
* Operating System: Mac OSx

**Comment by chadyj** [comment]
@churik This seems better now. I can get a lot more than 3, but I eventually stop receiving it messages until I clear them on OSX.

Can you verify?

**Comment by churik** [comment]
Still valid. Probably there is some time limit, i.e. 3 messages in 5 min.
But I can still reproduce it if I receive 4 messages in a row - I have only 3 PNs.

**Comment by churik** [comment]
Still relevant
