### ISSUE TITLE
[Desktop] Hack local encrypted backups (import/export to JSON)

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6473]
**Disclaimer**: this task isn't about "make it right", it is about "make it work" with the least possible effort. For me, better to have this feature in an inconvenient way than to lose data every now and then.

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I don't want to lose my data (opened chatrooms & contacts, my profile info) when I upgrade Status. So, for me, *any* backup functionality would be very useful.

It is the top pain point for me personally.

It is different from https://github.com/status-im/status-react/issues/5195 that it doesn't try to make it "right", it is just the absolute minimum that should be backed up.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Implement a few menu items that allows to export and import user's data to an encrypted JSON file. Ask for password when importing and exporting.

What should be backed up:
- user's name
- list of opened public chats
- list of opened 1:1 
- list of contacts (public key + display name)
- list of known display names

What should NOT be backed up (to reduce the potential security risks):
- user's ethereum keys (it is okay to enter 12 words to re-generate it again)
- message history itself
- DB encryption keys

Why JSON instead of realm copy? 
1) Simple to parse with JS/ClojureScript
2) Isn't affected by the DB migrations

#### What happens when you import data?

- User's name in profile → get's overriden
- Missing public/1:1 chatrooms → gets created (empty) just like you joined them but didn't send any message
- Missing contacts get added, missing display names are added. If a display name already exists, it is probably a more fresh one, so ignore the one from the backup file.

**Comment by chadyj** [comment]
+1

Also have you seen this PR that syncs contacts? https://github.com/status-im/status-react/pull/6242

**Comment by Swader** [comment]
keepalive
