### ISSUE TITLE
Implement UI for managing trusted peers in LES/ULC

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6476]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to use my custom LES and ULC servers to test stuff. For instance, if I run my own nodes locally or in DAppNode or somewhere else.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)

*Type*: Feature

devp2p stack has this notion of static peers (`admin_addPeer`) functionality. When we connect to a network using LES or ULC, we need to be able to manage the list of static peers there.

#### How should it work?
1) I should be able to create a custom network with LES or ULC as an option (not just a custom RPC server)
2) When this is selected, I should be able to add/remove custom static peers, just like it is possible to do it with custom mailservers now.

Ping me for more information if needed.

**Comment by Swader** [comment]
Keepalive
