### ISSUE TITLE
Add Dev Mode and Network Switching to Desktop

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#6477]
### User Story

As a developer I want to enable advanced in progress features in the app and use different networks
 
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: Add an option in Profile to enable/disable dev mode. When dev mode is enabled, allow Network switching with the same selection of networks as on mobile.

**Comment by chadyj** [comment]
Nice :)

**Comment by churik** [comment]
Irrelevant in terms of https://github.com/status-im/status-react/pull/7551
