### ISSUE TITLE
Implement JS Console

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6479]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a Status developer or a DApps developer, I find it very useful to be able to call arbitrary web3 methods. We used to have a console account for it, now it is gone.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature
Bring JS console back with 2 modes:
- "unlimited" — calls private RPC methods, useful for those who are hacking on Status itself.
- "restricted"  — calls the methods allowed for DApps, very useful to DApp developers.

**Comment by Swader** [comment]
How does such an important feature go stale?
