### ISSUE TITLE
Indicate loading/sync times in sync feedback

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#648]
In synchronisation we could indicate not only our progress but time remaining.

![9ce31b118026248a1f68bdf8aafbd372_original](https://cloud.githubusercontent.com/assets/2714786/21711563/2835326e-d422-11e6-9071-c1ef3818b485.jpg)

**Comment by Smokyish** [comment]
I think some sort of a clear indicator that you're synced fine in a clearly visible place, like at the top of Chats/Discover/Contacts could be helpful to users and should be considered if it gets requested repeatedly. 

![status_synced_example](https://cloud.githubusercontent.com/assets/21331903/22147782/0ce5e1ba-df13-11e6-83c1-877ddbede3be.jpg)

**Comment by jarradh** [comment]
It's not a bad idea, but it's also not great and should have more thought put into it. In a nut shell we should not require an "[everything is okay alarm](https://www.youtube.com/watch?v=aJFyWBLeM7Q)" .

While I agree these technical details should be (and are) available to more advanced users. It's abit regressive to show all them all the time. Our ultimate users shouldn't need to know or worry too much about blockchain. We should declutter and fade as much information into the background. . Only be notified when something is wrong, and do our best to auto-recover for them.

In spirit that's what I like about macOS, for new users, all they see is "shiny" but for power users they can get under the hood and open a terminal.

**Comment by jarradh** [comment]
I don't think we need this with the Canonical Hash Trie checkpointing
