### ISSUE TITLE
Research vipnode integration

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6480]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

This issue is created to document and keep track integration with vipnode (https://vipnode.org).

cc @oskarth @goranjovic 

<blockquote><img src="https://vipnode.org/img/preview-card.png" width="48" align="right"><div><strong><a href="https://vipnode.org/">Economic incentive for Ethereum full nodes · Vipnode</a></strong></div></blockquote>

**Comment by Swader** [comment]
Keepalive

**Comment by mandrigin** [comment]
okay, we (Status) are a part of https://ethereum-magicians.org/c/working-groups/constrained-resource-client-ring
not much did happen, unless LES/ULC are implemented.
there priority of that is fairly low right now (we won't be able to re-start this work until we solve stuff like onboarding, better message reliability, better error reporting, security audit, etc), so I'll close this one.

<blockquote><img src="https://ethereum-magicians.org/uploads/default/original/1X/4c1d2f876559adc5ce5f4115fe2019d38ccac3db.png" width="48" align="right"><div><img src="https://ethereum-magicians.org/uploads/default/original/1X/e7e24c4c6e978a9d54fc38841bc9503d61acdcb8.png" height="14"> Fellowship of Ethereum Magicians</div><div><strong><a href="https://ethereum-magicians.org/c/working-groups/constrained-resource-client-ring">Constrained Resource Client Ring</a></strong></div><div>This Ring is to coordinate between efforts to utilize client nodes in constrained resource environments, such as mobile apps and browsers.</div></blockquote>
