### ISSUE TITLE
Cannot sign up to CryptoKitties. Nothing happens when sign up button is pressed

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6484]
### Description

*Type*: Bug

*Summary*: 

When "Sign Up" is pressed, the button changes temporary to "Signing in.." but then returns back to "Sign Up". In result, a new user cannot create account in CryptoKitties. I did not find any logs in logcat or chrome dev tools.

<img src="https://user-images.githubusercontent.com/7532782/47359424-05475200-d6cd-11e8-9af4-1edfe6bbb2e0.png" width="200">

Note that signing in to an old account works fine. Signing up using MetaMask works as well. 

### Reproduction

- Create a new account in Status
- Open CryptoKitties on Mainnet and try to sign up

### Additional Information
* Status version: 0.9.29, 0.9.30
* Operating System: Android, iOS

**Comment by flexsurfer** [comment]
can't reproduce @lukaszfryc could you confirm, please?

**Comment by jeluard** [comment]
@lukaszfryc Any news? Should work fine with latest develop

**Comment by lukaszfryc** [comment]
Fixed by https://github.com/status-im/status-react/pull/6627
