### ISSUE TITLE
SuperRare collectibles are not loading when accessed from Wallet

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6486]
### Description

*Type*: Bug

*Summary*: I have a SuperRare collectible but it is not loading when I open it from Wallet tab. I waited for 5 min but the spinner did not disappear. If I go to https://superrare.co dapp and sign in, I can see the collectible there. But when I go back to Wallet -> SuperRare, the spinner is still there.

<img src="https://user-images.githubusercontent.com/7532782/47360139-eb0e7380-d6ce-11e8-8860-fcf3eb3650ee.png" width="200">

### Reproduction

- Have an account with a SuperRare collectible (https://superrare.co)
- Open Wallet -> Manage Assets and show SuperRare
- Try to open the SuperRare collectible

### Additional Information
* Status version: 0.9.29
* Operating System: Android, iOS

<blockquote><div><strong><a href="https://superrare.co/">superrare.co | 502: Bad gateway</a></strong></div></blockquote>

**Comment by jeluard** [comment]
Pixura team restarted a VM their side and it now works fine. @lukaszfryc please confirm.

**Comment by lukaszfryc** [comment]
Great! I’ll check soon

**Comment by jeluard** [comment]
@lukaszfryc Any news?

**Comment by lukaszfryc** [comment]
Works fine now! Closing
