### ISSUE TITLE
No error "Invalid asset - Unknown token" is shown if use Send from request of the token not listed in the Assets

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#6487]
### 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Nothing happens if use Send on the request for the token that is not listed in Wallet's assets. E.g. User A added only SNT to the list of visible Assets. User B send request of 2 OMG to user A in chat. User A taps on Send in this request and nothing happens. Previously (on 0.9.29) we show error in 1:1 chat: Invalid asset - Unknown token OMG

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Error is shown in 1:1 chat
#### Actual behavior
[comment]: # (Describe what actually happened.)
No error, nothing happens if tap on Send
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- as user A: make sure you have only SNT and ETH in the Wallet assets
- as user B: send request to user A in 1:1 chat of 3 OMG
- as  user A: respond to the request by tapping on Send and send /send OMG 3

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release build 21 for 0.9.20
* Operating System: Android and iOS

**Comment by Swader** [comment]
Nope

**Comment by churik** [comment]
Currently, if unknown token is requested, message is shown in 1-1 chat, at attempt to send -> insufficient funds error (Statuv v1.0.1)
Believe that it is enough to close current issue.
