### ISSUE TITLE
No 'Share' option on a long tap on wallet address from Wallet modal screen [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6489]
***Type***: Bug

***Summary***:  There is no 'Share' option on a long tap on wallet address in 'Wallet modal' screen on iOS (it's present on Android). 'Copy' address option is present only. 

#### Expected behavior
'Share' option is present on a long tap on wallet address in Wallet modal screen [iOS]
#### Actual behavior
No 'Share' option is present on a long tap on wallet address in Wallet modal screen [iOS]
<img width="301" alt="screen shot 2018-10-23 at 16 04 33" src="https://user-images.githubusercontent.com/8749671/47362576-5eb77d00-d6dd-11e8-9650-9426c865b152.png">

### Reproduction

- Open Status on iOS
- Create a new account
- Join any public chat (e.g. `#cryptolife`)
- Tap top-right menu button -> `View my Wallet`
- Long tap on address value and check whether 'Share' option appeared

### Additional Information
* Status version: 0.9.30 Release / 0.9.30 Develop (11181)
* Operating System: iOS

**Comment by Serhy** [comment]
Issue still present with 0.9.33 develop

**Comment by churik** [comment]
don't have this option anymore in top-right menu in public chat (Status v.1.0.1)
