### ISSUE TITLE
Nightly cleaning of Testflight users is broken

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6495]
Status has had recurring problems exceeding the 10k Testflight user limit. To address this we implemented a nightly Fastlane script to remove inactive testers.

Every night [Jenkins runs a job](https://ci.status.im/job/status-tools/job/Clean%20Testflight%20Users/) that cleans users with [bundle exec fastlane ios clean](https://github.com/status-im/status-react/blob/develop/fastlane/Fastfile#L143) but this has been [failing for months](https://ci.status.im/job/status-tools/job/Clean%20Testflight%20Users/).

Let's get this working again to keep the testers testing :)

**Comment by chadyj** [comment]
ping @jakubgs

**Comment by jakubgs** [comment]
Oh, right, it's just a path change. We moved all `Jenkinsfile`s to the `ci` folder, so the job config just had to have `ci/` appended before `Jenkinsfile.fastlane.clean`.

Although it appears the run takes ages, we might have to increate the 90 minute timeout.

**Comment by jakubgs** [comment]
I'm bumping the limit to 120 minutes in this PR: https://github.com/status-im/status-react/pull/6709

**Comment by chadyj** [comment]
Thanks @jakubgs things are running again!  Closing!

But the Fastlane plugin seems broken and I can't get it working locally.  Will investigate more.
