### ISSUE TITLE
Timestamp for outgoing emojis messages is hardly visible in chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6497]
### Description

*Type*: Bug

*Summary*: Timestamp for messages containing the only emojis is almost invisible for the sender

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/47369697-ec4e9900-d6ec-11e8-8706-289d1d0f7949.png)

### Reproduction

- Open Status
- Go to any chat
- Send emoji
- Check timestamp

**Comment by churik** [comment]
Still reproducible
