### ISSUE TITLE
Console Javascript Environment does not persist between messages

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#650]
Ideally you could set variables and reference them later.

![c30066be6cfc65691b8f2591ca092992_original](https://cloud.githubusercontent.com/assets/2714786/21711813/994db614-d423-11e6-9016-13f54f635c6e.jpg)

**Comment by flexsurfer** [comment]
@jarradh evaluation of js is happening in the handler's function scope, var inside function in JS creates variable in the "local" scope of this function, and there is no way to access it through code, I found a hack how we can catch this variable, but it doesn't work in the Otto VM :( catches only variables created without var, for example "a = 1", so I see next ways
1)parse message string - not really a good idea
2)cut var from message string before eval - not elegant, but will work
3)give special object for variables, for example - globalVars.a = 5
4)command for variables creation
5)find the way to find variable in the Otto VM - more investigations needed

 i'm Android user, but on iOS it doesn't give you a chance to input "var" it auto changes it on "Var" invalid character

**Comment by flexsurfer** [comment]
@rasom  @alwx what do you think guys?

**Comment by rasom** [comment]
was implemented in https://github.com/status-im/status-react/pull/1248
