### ISSUE TITLE
Desktop chat search being weird

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6500]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

I grabbed the newest nightly and went to start searching for contacts to filter the list, but it isn't working as expected.

For example I see "yenda" in the list

<img width="338" alt="screen shot 2018-10-24 at 8 43 19 am" src="https://user-images.githubusercontent.com/116099/47411498-3c6b4100-d769-11e8-8a32-dae008a1470a.png">

But when I search for "yenda" nothing shows up.

<img width="335" alt="screen shot 2018-10-24 at 8 43 39 am" src="https://user-images.githubusercontent.com/116099/47411511-4725d600-d769-11e8-92fb-0cd1ef4d017e.png">

I try some other searches and display name works

<img width="340" alt="screen shot 2018-10-24 at 8 47 41 am" src="https://user-images.githubusercontent.com/116099/47411582-82280980-d769-11e8-852e-f498208b736f.png">

But when I try a few other display names of people in my chat list I get 0 results

#### Expected behavior
List is filtered when there is a matching search query

#### Actual behavior
no results

### Reproduction

Have a full list and try all the display names

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightly
[comment]: # (Android or iOS.)
* Operating System: Mac

**Comment by churik** [comment]
not reproducible for me, I can search normally for 1-1 chats, public and group chats. Probably you can attach log or add some specific steps/details?
