### ISSUE TITLE
Chats are not sorted by timestamps of last incoming messages 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6501]
### Description

*Type*: Bug

*Summary*: 
Chats should be sorted according to last messages - newest on the top.
For now, when user gets the new message - chat does not move to the top, so it keeps the same postion.

#### Expected behavior
chats with newest messages on the top.

#### Actual behavior
<img width="467" alt="1234567" src="https://user-images.githubusercontent.com/4557972/47415335-793c3580-d773-11e8-821a-50600f75443d.png">

### Reproduction

- Open Status
- Log in
- Join several 1-1 and public chats
- Send some messages to chats from another device
- Pay attention to chat list

### Additional Information

* Status version: nightly 24/10/18
* Operating System: Mac OSx

**Comment by chadyj** [comment]
Fixed in https://github.com/status-im/status-react/pull/6507
