### ISSUE TITLE
Cross network main currency payment messages show wrong fiat value

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#6504]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see fiat prices for my assets on multiple different chains.

### Description

*Type*: Bug

*Summary*: Assets from different chains can have non-zero prices (e.g. sidechains). Those prices need to be applied when we calculate fiat value of said assets. 

Since sender and receiver can use different networks at the moment when payment message (send or request) is exchanged in chat, what this means is that we need the prices of assets from all the chains available at the same time. 

Issue originally found in [#6388](https://github.com/status-im/status-react/pull/6388#issuecomment-432549313) - points 4 and 5

#### Expected behavior

- Outgoing payment message displays correct asset and fiat value on senderss side
- Incoming payment message displays correct asset and fiat value on receiver's side, regardless of the currently selected network
- Test network asset's fiat value should always be zero

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- A is on POA Network and B is on Mainnet
- A and B are each others contacts and have a chat open between them
- A sends 1 POA to B
- Outgoing payment message will display 1 POA and its correct fiat value on A's side (but that's easy, since A is already on POA Network)
- Incoming payment message will display 1 POA on B's side. But in order to display the fiat value correctly, B's account needs to have the price for POA, not just for Mainnet assets

### Solution
*Summary*: 

- Until full solution is prepared, we should remove fiat values from cross network payment messages
- Following that, the solution will involve a change in data structure that keeps the asset prices. One complication that may affect this is that we are fetching prices only for enabled tokens, so we'd need access to enabled tokens on networks other than the one currently selected.

**Comment by Swader** [comment]
Bad bot

**Comment by cammellos** [comment]
closing as related to old commands
