### ISSUE TITLE
UI fixes for bubble-less chat area

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6506]
### Description
Type: UI Fixes

Summary: We are introducing UI fixes in order to improve the design and increase readability of the chat area.

### Solution
UI fixes include:
- New open source font [Inter UI](https://rsms.me/inter/). Note that this font will eventually be used across other Status products (mobile, desktop, websites)
- Adjusted paddings and line heights to improve readability
- Alignment of elements
- Ability to select text (current bug) and its style
- Show timestamps only onHover

### Current implementation

<img width="819" alt="captura de pantalla 2018-10-24 a la s 12 35 03 p m" src="https://user-images.githubusercontent.com/37297779/47424971-4309b080-d789-11e8-9496-965a739adf31.png">

### Design with fixes

<img width="516" alt="captura de pantalla 2018-12-03 a la s 11 27 35 a m" src="https://user-images.githubusercontent.com/37297779/49379684-7a576f80-f6ee-11e8-8915-d374abf4c57a.png">

[Design on Figma + guidelines](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=134%3A1887) 

**Please, share your implementation with the team before merging, so we can find bugs together before they are exposed to a broader audience** 😊

**Comment by churik** [comment]
Irrelevant in terms of #7551
