### ISSUE TITLE
12 Word Seed phrase to 24

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/status-react#6511]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have more secure keys so that I feel more confident in the security of my funds..

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Bump to seedphrase from 12 words to 24, or have an option to choose between them.

**Comment by Swader** [comment]
I still think this would be a good thing to have. No switching, just default to higher security.

**Comment by cammellos** [comment]
Closing for now as we will be tracking feature requests on https://discuss.status.im/ from now on, feel free to create a feature request there. Thanks!
