### ISSUE TITLE
Can't back up pass phrase having Russian app version due to broken translation

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6513]
### Description

*Type*: Bug

*Summary*: Broken translation does not let me see which word i am asked for, so I cant back up my phrase easily

#### Expected behavior

Word number is shown, like `word #12`

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/47428621-7ace2380-d79c-11e8-8cf4-963fcf41a593.png)

### Reproduction

- Change system language to Russian
- Open Status
- Create account
- Ask for some funds
- Go to backup phrase flow

**Comment by Swader** [comment]
Ugh

**Comment by asemiankevich** [comment]
looks okay now
