### ISSUE TITLE
0 fiat value is shown for /request command in 1-1 chat for tokens which are not added to assets

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6515]
### Description

*Type*: Bug
*Summary*: when token is not added to assets, any request in 1-1 chat for this token shows 0 fiat value.

#### Expected behavior
correct fiat value is shown

#### Actual behavior
<img width="188" alt="fiat_value" src="https://user-images.githubusercontent.com/4557972/47430654-48bbc200-d79a-11e8-81e6-329ac3f99cc6.png">

### Reproduction

*Prerequisites:* User A and User B on mainnet, using different devices; 
User B doesn't have any tokens added except default ones.

- User A: open Status
- User A: add user B as contact
- User A:  add any token to assets (i.e. BNT)
- User A: send /request command of BNT to User B
- User B: check fiat value for /request command in chat with User A

### Additional Information

* Status version: release  build 24 for 0.9.30

* Operating System: Android, iOS

**Comment by goranjovic** [comment]
Closely related to #6504

**Comment by Swader** [comment]
Not stale

**Comment by churik** [comment]
Closed as commands are removed now in #8674
