### ISSUE TITLE
Go-ethereum crashes and does not recover

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#652]
In the logs we see `Failed to connect to localhost/127.0.0.1:8545` and is responsible for a host of UI problems and application no longer working.

**Comment by carlbennetts** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/103

**Comment by jarradh** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/119
