### ISSUE TITLE
Standardize desktop build update experience (MacOS)

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6521]
### User Story

As a user, I want a standard way to update my desktop app version on MacOS.

### Description & current behavior
**Type**: Fix

**Current implementation**
<img width="342" alt="captura de pantalla 2018-10-24 a la s 1 00 32 p m" src="https://user-images.githubusercontent.com/37297779/47439653-0d76be80-d7ad-11e8-9269-fbb099f8e59e.png">

The current implementation for upgrading to the latest version has the following issues:

- By being a primary button, it compites with the main action under Profile that is to share your contact.
- Once we add more options under Profile, the button will get lost.
- It is not a standard way to update a MacOS app. 

#### Expected behavior
The update experience should follow [this definition](https://github.com/status-im/status-react/issues/5812).

### Reproduction
- Open Status
- Go to Profile

### Note
TBD how to do it on Windows and Linux

**Comment by churik** [comment]
Irrelevant in terms of #7551
