### ISSUE TITLE
Find a way to manage build numbers without using git tags

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#6522]
Currently we are using git tags with a format of `build-[0-9]+` to globally track build numbers which are then used in metadata for Android and iOS builds. They have to be long integers, they have to be incremented, and they cannot clash across multiple builds.

This is also related to us wanting to release the app on GitHub, but the "Releases" section is cluttered up with `build-*` tags.
Related: https://github.com/status-im/status-react/issues/6273

**Comment by chadyj** [comment]
/// removed the released label since we are using that for mobile release blockers

**Comment by jakubgs** [comment]
Okay, I've merged https://github.com/status-im/status-react/pull/6578. Lets give it some time to see if it works fine, once I'm sure it does I'll remove all the `build-*` tags and that should clean up the release page on GitHub.

**Comment by jakubgs** [comment]
Aaaand we are down to 21 releases:
https://github.com/status-im/status-react/releases

There is still one `build-12853` tag I kept to not break any old PRs that might not have rebased from `develop` in a while, so we still might see a few of those tags here and there, but I'll clean them up as they come, eventually there should be none.

I consider this done.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>
