### ISSUE TITLE
For a specific case, link is not clickable for desktop (emoticons and special characters without spaces after the URL)

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6531]
Description

Type: **Bug**

Summary: For desktop specifically, when a link is inserted in format like 'ukr.net' or 'http://ecase.com.ua' with an emoticon at the end (no space to separate the link from the emoticon), the link is non-clickable. Also, sometimes reproduces for special characters - check the examples attached.

**Expected behavior**

If a link is invalid, 'cannot open this URL should be displayed, all links should be clickable

**Actual behavior**

In this specific case, links are non-clickable

**Steps to reproduce:**
1. Input a link like 'ukr.net' or 'http://ecase.com.ua' in any chat
2. Put an emoticon at the end of this link with no space, ex: 'http://ecase.com.ua😹' 
3. Click on this link on desktop

Other examples of such non-clickable links:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/43638377/47517479-06c17780-d891-11e8-8922-31c73c5ef760.png">
<img width="125" alt="image" src="https://user-images.githubusercontent.com/43638377/47517512-19d44780-d891-11e8-8c7f-8f6ae7bae6df.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/43638377/47517543-28bafa00-d891-11e8-820b-32360da02b6e.png">

**Additional information:**

Status version: desktop build 10/25/18
Operating System: MacOS 10.13.4

**Comment by chadyj** [comment]
cc @janherich

**Comment by SlizkovaGanna** [comment]
Still a valid issue.
Tested on nightly from 30/12/2018

**Comment by churik** [comment]
Irrelevant in terms of #7551
