### ISSUE TITLE
Extension throws error which requires force closing the app and disabling the extension

### ISSUE THREAD

**Issue by morelazers** [status-im/status-react#6534]
### Description

As a developer, I should receive helpful error messages

Type: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I created an extension, installed it and then used it in a chat - the app then crashed with an error which could not be recovered from. App must be force-closed, then logged into again before disabling the extension is possible.

#### Expected behavior

One or more of the following: 

- Receive an error message before installing the extension
- Error message should have information which informs me why the issue arose
- Error message should be dismissable and I should still be able to navigate around the application

#### Actual behavior

Unhelpful error is thrown, after dismissing it, the app stays on a white screen and no other actions can be taken.

![image](https://user-images.githubusercontent.com/2966123/47572523-768c3c80-d93b-11e8-917b-975ad7dd42a1.png)

### Reproduction

- Open Status
- Install this extension (https://get.status.im/extension/ipfs@QmdY2qeffNwYs4cyn2WreHzKisB7opBaCLFuoepmsr7pJe) 
![image](https://user-images.githubusercontent.com/2966123/47572502-67a58a00-d93b-11e8-9f30-5b4e60fc30e5.png)

- Open a 1-1 chat and send the command

### Additional Information
* Status version: 0.9.30
* Operating System: Android

<blockquote></blockquote>

**Comment by jeluard** [comment]
@morelazers Do you remember by any chance what your extensions looked like? Can't access the one on IPFS :)

**Comment by morelazers** [comment]
@jeluard https://ipfs.enzypt.io/ipfs/QmdY2qeffNwYs4cyn2WreHzKisB7opBaCLFuoepmsr7pJe

<blockquote></blockquote>
