### ISSUE TITLE
"There is no route defined for key wallet-transaction-sent" app crash after Sign TX in Dapp

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6540]
***Type***: Bug

***Summary***: It appeared for me when I tried to use `aftifaqts.club` Dapp. After signing the transaction in this Dapp - app crashed with the `There is no route defined for key wallet-transaction-sen` error. 
Note: in a case when using another tx fee (i.e. if I hit 'Done' button from Transaction Fee screen)
Note2: it's all fine when sending transaction two times in a row from SimpleTestDapp
Note3: on iOS after scanning QR code contact navigates back to Dapp (no redirect to wallet screen)

#### Expected behavior
Transaction made fine

#### Actual behavior
`There is no route defined for key wallet-transaction-sent` app crash app crash after Sign TX in the `aftifaqts.club` Dapp
<img width="369" alt="screen shot 2018-10-27 at 16 28 26" src="https://user-images.githubusercontent.com/8749671/47604670-5f198600-da05-11e8-9e10-07ed9386526b.png">

### Reproduction
- Open Status and log in to account
- Navigate to `aftifaqts.club` 
- Tap `Scan QR code` in the Dapp. 
- Sign transaction

### Additional Information
* Status version: 0.9.30 Release
* Operating System: Android and iOS

**Comment by Serhy** [comment]
aftifaqts.club is not available anymore, so closed.

**Comment by Swader** [comment]
You can still test it locally: https://github.com/ConsenSys/artifaqt

<blockquote><img src="https://avatars1.githubusercontent.com/u/10818037?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ConsenSys/artifaqt">ConsenSys/artifaqt</a></strong></div><div>Artifaqts in Prague for Devcon4. Contribute to ConsenSys/artifaqt development by creating an account on GitHub.</div></blockquote>
