### ISSUE TITLE
how can I export my private key (not mnemonic words) from Android wallet?

### ISSUE THREAD

**Issue by maraoz** [status-im/status-react#6542]

**Comment by maraoz** [comment]
Same question for exporting the mnemonic words, can't find it either! :(

**Comment by Swader** [comment]
Still active

**Comment by mandrigin** [comment]
The seed phrase is remove as soon as it is marked as "backed up", for security reasons. Before that, you can find it in your profile.
For the same reasons, it isn't possible and I don't think it is a good idea to be able to export your private keys. You can't just "change password", when the private key is leaked, all the funds in the wallet will be leaked too.
cc @corpetty
Feel free to reopen if you disagree, but I don't think we should implement that.
