### ISSUE TITLE
For desktop, PN are not received when app is closed

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6547]
Type: Bug

Summary: There is a rule listed for mobile in https://github.com/status-im/status-react/issues/4910 :
Notification appears whenever a message is received and the app is on background or turned off
The assumption is that the same behaviour is valid for desktop.

**Expected behaviour**

Push notifications should be received when app is closed on desktop

**Actual behaviour**

Push notifications are not received when app is closed on desktop

**Reproduction**

1. Open desktop app on device A
2. Start 1-1 chat with a different user on device B
3. Close Status app on device A
4. Send a message from device B to device A

And if expected behaviour is not to show the notification when desktop app is closed, 
should it re-appear when app is opened again, or not show at all?
Thank you.

**Comment by maxhora** [comment]
cc: @chadyj 
Currently desktop doesn't support receiving or generation of push notifications, it supports just generation of local desktop notifications in OSX notification center.

That sounds as valid feature request.

**Comment by churik** [comment]
Still relevant
