### ISSUE TITLE
Cannot send SNT in chat using slash command

### ISSUE THREAD

**Issue by lrettig** [status-im/status-react#6550]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to be able to send SNT to my friend in a status chat.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I can send SNT from the Wallet view, but when I try to use `/send SNT` to send it, it says insufficient balance -- but I do have SNT tokens in my wallet.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Make sure you have SNT tokens in your wallet
- Go to a chat
- Type /send SNT 1
- On the transaction screen that appears, it says insufficient balance

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.30
[comment]: # (Android or iOS.)
* Operating System: iOS

**Comment by StatusSceptre** [comment]
Hey @lrettig you may need to first go to your wallet and “manage assets”
At the top right elipses and add the token you have before it shows in chat. 

Just tested and as soon as I have the asset added in my wallet I can send tokens in chat.
