### ISSUE TITLE
Screen flicker in Wallet

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#656]
Entering a value inside the request field on the Wallet DApp creates a screen flicker.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/87

**Comment by rasom** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/199

**Comment by annadanchenko** [comment]
Instabug: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/332
