### ISSUE TITLE
Have the ability to retrieve the seed even after it was backed up

### ISSUE THREAD

**Issue by axic** [status-im/status-react#6562]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user it would be nice to have a way retrieving the seed even after it was backed up.

### Description

*Type*: Feature

*Summary*: I had two different accounts, because started to use the app quite a while back and one of the recent derivation changes caused a new account to be created. I did back up one of them but wasn't sure I had the right key and there was no way to extract the seed again once it was backed up.

**Comment by axic** [comment]
Even if not the seed, at least the private key for an address.  I think this is a major missing feature.

**Comment by mandrigin** [comment]
Seed is removed as soon as it backed up for security reasons. Making private key exportable for a user will also open a hole for an advisory that would like to extract the PK and the money protected by it.
@corpetty correct me if I'm wrong, but I would say that this is not something that we want to implement. Feel free to reopen.

**Comment by axic** [comment]
I would like to open this issue up again.  The app has advanced settings already and exporting private key is practically supported by every client.  Since the wallet stores the keys in an insecure location on the phone anyway and that the industry prefers hardware wallets (even Status has its Keycard), I think it makes sense to allow this **and** encourage users to rely on hardware wallets for extra security.
