### ISSUE TITLE
Click on link quotes the message instead of opening it in browser

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6565]
### Description

*Type*: Bug

*Summary*: in this https://github.com/status-im/status-react/pull/6263 were fixed onPress events (checked on https://github.com/status-im/status-react/pull/6263#issuecomment-433468282), but in current nightly instead of redirecting to browser it is quoting a message in text area

#### Expected behavior
link is opened 

#### Actual behavior
message is quoted; no redirect.

### Reproduction

- Open Status
- Log in
- Join to any channel
- Send message with link
- Click on link

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 01/11/2018
* Operating System: Mac Osx

cc @siphiuel

**Comment by chadyj** [comment]
@janherich Are we expecting some improvements from you that will fix this issue?

**Comment by vitvly** [comment]
There was some bad merge on my part in react-native-desktop. Fixed it, so we can retest in the new nightly where it will pickup the fixed react-native repo.

**Comment by churik** [comment]
Fixed in nightly 05/11/2018
