### ISSUE TITLE
'New group chat' text cut off for Polish users

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#657]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/121
(Perhaps caused by Polish translation being longer)

**Comment by flexsurfer** [comment]
label size is wrong, on all languages

**Comment by jumarko** [comment]
Could you guys, please, copy all the information from instabug to the GitHub for those of us who don't have access to instabug?

**Comment by jumarko** [comment]
Ok, I've set the polish locale and it looks like this:

![image](https://cloud.githubusercontent.com/assets/1083629/22372963/e519dadc-e49f-11e6-9514-20f48a0bb085.png)

**Comment by flexsurfer** [comment]
@jumarko yes, it's because view width, i'm working on this https://github.com/status-im/status-react/pull/767/files#diff-0e2d3e5ac90d36610c02e5894d55e312R136.

**Comment by jumarko** [comment]
great thank you for info :)
