### ISSUE TITLE
Fix scroll stuttering in chat view

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#6570]
### Description
Scrolling the chat view if often laggy and/or stuttering, even after all messages have been fetched from the mailserver, and there is no new content.

**Comment by Swader** [comment]
This issue is still active in some way - on the Windows build (not sure about others) the chat will scroll out of view as if by unbalanced inertia caused by some kind of roll-your-own smooth-scroller. It is impossible to scroll with precision with it.
