### ISSUE TITLE
Provide standard context menus in input fields

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#6571]
### Description
There are some menu actions that are standard across desktop apps and should be available from context menus in edit fields, e.g.:

- Cut
- Copy
- Paste
- etc.
<img width="270" alt="screen shot 2018-11-06 at 16 24 23" src="https://user-images.githubusercontent.com/1019573/48070440-8da31800-e1e0-11e8-867c-f56e9c44baf0.png">

**Comment by EugeOrtiz** [comment]
@siphiuel is this related to issue #5547?

**Comment by vitvly** [comment]
@EugeOrtiz yes, this is mostly a (much less detailed) duplicate. I changed the title and description so that it is context menu-specific.

**Comment by yenda** [comment]
What is needed to make that possible ? Does it need to be implemented in react desktop first ? It should be one of the top priorities as some features really need this

**Comment by chadyj** [comment]
Removing this from the 0.9.0 release

**Comment by Swader** [comment]
Still a problem.
