### ISSUE TITLE
Design token details screen

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#6574]
### User Story

As a user I want to be able to easily check and verify any details on any of my tokens (name, symbol, icon, address, decimals)

### Description

*Type*: Feature

*Summary*: 

User should have an easy way to double check things like contract address of any of his tokens without having to look at the code. This need is increased by the fact that we won't be hardcoding decimals for the default tokens anymore after #6509 so that piece of info will be completely invisible to the user unless we put it some place in the app.

**Comment by denis-sharypin** [comment]
I added screens to the flow of adding custom tokens. https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet_Source-of-Truth?node-id=160%3A3954

<blockquote><img src="/file/XUehMnhyD1FGcWzvGz6SXqvh/thumbnail?ver=thumbnails/8de4d769-18c3-450b-91c4-df12616f0030" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet_Source-of-Truth">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by Swader** [comment]
Still important

**Comment by flexsurfer** [comment]
implemented on long press
