### ISSUE TITLE
Adding a contact from another platform (android/ios) returnes wrong contact

### ISSUE THREAD

**Issue by friedhelmensch** [status-im/status-react#658]
Public key interpretation seems to be different on ios and android
Adding a contact only works if the contact is on the same plattform (ios / android).

Try to add a contact by either scanning the QR code or pasting the textual representation of the public key. 

If the contact uses another platform (You: iOS, Contact: Android or vice versa) you will find a wrong profile. If you are on the same platform you will find the correct profile.

**Comment by Jas0n-F** [comment]
https://instabug.com/applications/status/beta/bugs/37?status=New

**Comment by rasom** [comment]
I was working during the whole day yesterday using iOS and Android devices and communication between them. Will try to downgrade app on iOS to  `0.9.2 (118.957)` version and check how it worked there, but adding a contact from another platform is working in `develop`.

**Comment by alwx** [comment]
The same. My usual dev scenario includes iOS simulator and Android emulator running, and I communicate between two devices all the time but never seen such a problem.

> But it seems the public key they posted returned a different user. The two of them were able to find each other. They are both on android. I am on iOS

Even if you cannot communicate between platforms (which is hard but possible to imagine), it's even harder to imagine the case when one public key belongs not only to you but another user also. Probability theory says it's almost impossible.

**Comment by jarradh** [comment]
Should this be closed?

**Comment by alwx** [comment]
@jarradh let's close it because there is nobody else who can reproduce it. Maybe it has been fixed in one of the previous commits.

**Comment by jarradh** [comment]
sure thing

**Comment by friedhelmensch** [comment]
I´ll check with the new version again!

**Comment by friedhelmensch** [comment]
it is still happening for me with the new version.

**Comment by annadanchenko** [comment]
@friedhelmensch It looks like we can't reproduce the issue, yet. Can you describe steps, Status version and device model/OS version, please?  If you can add a video that demonstrates the issue it would be great. 

Here is how I've tried to reproduce, but iOS and Android device can add each other and send messages.
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7U1BrMnBzR290ajQ
Steps:

- on IOS device:
   - Open Contacts
   -  Tap on "..." icon in top right corner
   -  Tap on "New contact" 
   - On screen "Add new contact" tap on "Scan QR"
   -  Allow access to Camera
- on Android device:
   -  Open Profile
   -  Tap on Share QR. As a result, QR code is shown
- on iOS device:
   -  scan QR code shown on Android device. As a result, public key value is filed in 
   - Tap on check in top right corner 
   -  in new 1-1 chat type "hi android" and send it
- on Android device:
   - Open Chats
   -  Tap on new 1-1 chat with iOS device. Message "hi android" is shown in the chat
   - Type "hi iOS" and send it. As a result, this message is visible on iOS device in 1-1 chat
   -  Tap on "Add to contacts" link on top of the chat. As a result, on iOS device profile picture and display name of the Android contact are shown.

Status version: 0.9.6
Devices: iphone 6s with iOS 10.2.1 and Samsung Galaxy S7 with Android 6.0.1

**Comment by friedhelmensch** [comment]
I tried it again today and could not reproduce it. I'll close it again. Sorry for the trouble
