### ISSUE TITLE
No visual feedback when registering an ENS with no SNT

### ISSUE THREAD

**Issue by jfarid27** [status-im/status-react#6580]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want visual feedback when registering an ENS with no SNT.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The ENS registration at ipfs.infura.io does not appear to work or have any feed back saying what is needed to complete the transaction after going through the ENS search and granting access to my contact code. Granted I don't have SNT, but I expected at least visual feedback saying "you need SNT to complete this transaction."

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Any visual feedback saying what's needed or whether an error occurred.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
- Register an ENS through the Status Profile with no SNT. 

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] When a wallet doesn't have an asset to complete a transaction, generate a visual indicator that the transaction cannot happen.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.30
[comment]: # (Android or iOS.)
* Operating System: Android 8.1.0, Nexus 6P

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by jeluard** [comment]
@jfarid27 Thanks for the feedback! This issue should probably be added to the https://github.com/status-im/ens-usernames repo.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/ens-usernames">status-im/ens-usernames</a></strong></div><div>DApp to register usernames for Status Network. Contribute to status-im/ens-usernames development by creating an account on GitHub.</div></blockquote>

**Comment by jfarid27** [comment]
@jeluard closing and opening in the ens repo
