### ISSUE TITLE
Cryptokitties connection is broken.

### ISSUE THREAD

**Issue by jfarid27** [status-im/status-react#6581]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want visual feedback when completing a cryptokitties connection

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The Cryptokitties connection is not working at all after going through the forms and clicking "sign up".

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Any visual feedback saying what's needed or whether an error occurred.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
- Cryptokitties
- Go through the signup process. You should see no visual feedback on success or error and it won't let you pass.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Some fix for the UI so it does not error.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.30
[comment]: # (Android or iOS.)
* Operating System: Android 8.1.0, Nexus 6P

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by flexsurfer** [comment]
can't reproduce @lukaszfryc  could you confirm, please?

**Comment by lukaszfryc** [comment]
I only see the MetaMask request which is fixed by #6627

**Comment by jfarid27** [comment]
@lukaszfryc I am now also seeing the MetaMask request when trying it out again. So this is fixed in a new release?

**Comment by lukaszfryc** [comment]
@jfarid27 it was fixed in #6627 but it's not released yet. Next release will probably go out around Nov 19.

**Comment by jfarid27** [comment]
@lukaszfryc closing then
