### ISSUE TITLE
Granting profile access to a DApp gives access to any DApp with same host

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6585]
### User Story

As a user, I want to know that my data is granted only to the DApps I specify, so that I have control over my privacy and information. 

### Description

*Type*: Bug

*Summary*: Currently, requests for a user's contact code or Ethereum provider come from the hosting service, typically `ipfs.infura.io/...`. 

Once the user grants permission for their data, the permission is given to _any_ DApp handled by that same host.

#### Expected behavior
User grants permission on a case-by-case basis, as triggered by the DApp. 

An improvement would be to grant permission for a specific DApp—not for any DApp hosted by IPFS/Infura.

#### Actual behavior
My contact code is shared with any `ipfs.infura` DApp once I grant access once.

**Comment by jeluard** [comment]
@flexsurfer Why do we need design here?

**Comment by flexsurfer** [comment]
@jeluard if we want to grant access to full URL, we need to understand how to show it to a user, and if there any sense to show it at all, maybe something like grant access to this Dapp or smth

**Comment by jeluard** [comment]
@denis-sharypin does that makes sense? We need some design love here! :)

**Comment by denis-sharypin** [comment]
Yeah probably better to say something generic then
<img width="374" alt="screenshot 2018-11-05 12 14 31" src="https://user-images.githubusercontent.com/6559881/47995036-62db9580-e0f4-11e8-920b-3a0054cb30e6.png">

**Comment by rachelhamlin** [comment]
Suggest: `This DApp`

**Comment by flexsurfer** [comment]
I've investigated several ways how we can go with this issue, and decided to use dns and ens names for granting permissions, full url doesn't work because dapps have several pages and they can request permissions on the first page and use web3 on the second page, and dapp will be broken, so we should give permission for all dapp pages, using dns name or ens name, if someone hosts several dapps on the same domain we can't do anything with it. We'll show domain to user, and he should decide if he wants to grant access to all dapps hosted on this domain or not

**Comment by rachelhamlin** [comment]
Makes sense @flexsurfer. So, DNS/ENS based permission at the DApp level (with multiple DApps, same domain being an edge case). The interface will show, for example:

`cryptokitties.co wants to access your profile`? 

`localethereum.com wants to access your profile`?

**Comment by flexsurfer** [comment]
yes, or `names.statusnet.eth wants to access your profile`  for ENS
or
 `ipfs.infura.io wants to access your profile` - for vote.status.im , because it redirects to infura, which makes no sense, we need to host it on status.im or register `vote.statusnet.eth`

**Comment by asemiankevich** [comment]
@flexsurfer does not ask me about permissions . Trying to access `names.statusnet.eth`. Previously i granted `vote.statusnet.eth` with access. I thought each dapp will separately ask for permissions no matter of the domain they are hosted on? 

Dapps with different URLs behave as expected:

![image](https://user-images.githubusercontent.com/28752642/48400676-1289b680-e738-11e8-95a5-c50229b90069.png)

![image](https://user-images.githubusercontent.com/28752642/48400939-cb4ff580-e738-11e8-9be7-e1009e307e4f.png)

![image](https://user-images.githubusercontent.com/28752642/48401054-2bdf3280-e739-11e8-9838-639db34faa4a.png)

**Comment by flexsurfer** [comment]
@asemiankevich looks like names.statusnet.eth dapp doesn't support web3-opt-in
I made changes for `vote.status.im`, it should show `ipfs.infura.io`

**Comment by rachelhamlin** [comment]
How was is that `vote.status.im` was displaying as such despite the redirect? Isn't it better that way?

**Comment by flexsurfer** [comment]
@rachelhamlin it was a bug, it showed domain from the previous url, for example, if you have some dapp1.com and you click a link in this dapp, and it redirects you to dapp2.com, and dapp2.com requests permissions, we have shown "dapp1.com wants to access" in this case , but it's wrong it's dapp2.com
Current vote.status.im implementation is wrong if we want to keep vote.status.im we should host dapp on this host without redirect, or we should use ens which will be resolved to ipfs, there is no sense to redirect to infura from vote.status.im

**Comment by rachelhamlin** [comment]
Ah, makes sense @flexsurfer - thanks for that.
