### ISSUE TITLE
IPFS hosted apps should not share cookies/etc

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6587]
### User Story

As a user, I want to know that my data is not shared between different IPFS hosted apps (cookies, localStorage). As we are currently leveraging infura subdomains 

### Description

*Type*: Bug

*Summary*: Currently opening an ENS/IPFS app will redirect to `ipfs.infura.io/..`. Because of web cookies and localStorage policues this leads to share data between DApps. Make sure this type of sharing doesn't happen.

**Comment by flexsurfer** [comment]
To solve this properly and prepare for swarm support we need to implement ens resolution in webview component, it should be possible to set ens name as url and content should be requested and showed, and if we set url as “test.eth” and user navigates to “test.eth/search”, onNavigationStateChange should contain current url as “test.eth/search”

1) ens name  “test.eth” is set into react native webview bridge component
2) ens name is resolved to hash
3) content is requested by hash from ipfs or swarm
4) content is set into native webview component
5) when user navigates to another url , webview bridge component fires onNavigationStateChange event with new ens url “test.eth/search”

**Comment by jeluard** [comment]
@flexsurfer Can you detail the plan to not have cookies shared/localStorage shared too?

**Comment by jeluard** [comment]
Relates to https://github.com/ipfs/community/issues/319

**Comment by rachelhamlin** [comment]
To-do - @jeluard you can list options for this issue here.

Two most popular options from the call were me 6 (??) option and using a hash.

**Comment by jeluard** [comment]
Will do! BTW it is meeseeks :) https://meeseeks.app/

<blockquote><div><strong><a href="https://meeseeks.app/">loading...</a></strong></div></blockquote>

**Comment by jeluard** [comment]
See some notes [here](https://notes.status.im/browser-ens-dapp-research?view)
