### ISSUE TITLE
Improve quality of logs in Status Desktop

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#6593]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to be able to quickly scan high-quality logs from Status Desktop so that I can quickly diagnose an issue.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently logs are sub-optimal in many ways. Some examples that should be fixed:

#### Multiple lines from ubuntu-server are bundled together in one line

```
14:21:53.998 - D - ubuntu-server std:  "INFO [status-im.data-store.realm.core:107] - migrate schemas\nDEBUG [status-im.data-store.realm.core:35] - Opening realm at  /home/pedro/.local/share/Status/default.realmaccounts/0x93c8729708a4ca2af8a3ee755b02cd35afd39c1dbbe95e52c0056f9abbf2ccf1 ..."
```

#### ubuntu-server prefix doesn't bring real value

- `- D - ubuntu-server std:  "DEBUG *"` should read `- D - "*"` 
- `- D - ubuntu-server err:  "WARN *"` should read `- W - "*"`

### Some ubuntu-server entries contain no log level indication

E.g. `- D - ubuntu-server err:  "-- Server starting"`

Related to https://github.com/status-im/status-react/issues/5848

**Comment by churik** [comment]
@PombeirP WDYT about this issue? should it be reopened?

**Comment by pedropombeiro** [comment]
I've since made some improvements to the Desktop logs, so maybe the current state is satisfactory. Let's leave it closed and if someone feels we still need to improve it more, then we can reopen or create new one.
