### ISSUE TITLE
Can’t click on buttons in user profile when the profile is accessed from group info screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6598]
### Description

*Type*: Bug

*Summary*: If a user profile screen is opened by clicking on user in a group info screen, the buttons "Send message", "Send transaction", "Add to contact", etc. do not trigger any action.  

#### Expected behavior
The buttons navigate to correct screens and screen hierarchy is correct. E.g. clicking "Send transaction" opens chat with "/send" and the back button in chat navigates to Home tab. 

#### Actual behavior
The buttons do not trigger any navigation.

### Reproduction

- Turn ON dev mode in Profile
- Go to Home and create a group chat
- Open the group info and click on a user

### Additional Information
* Status version: 5 Nov, build with enabled group chats 
* Operating System: Android, iOS

**Comment by cammellos** [comment]
@lukaszfryc are you sure you are not on your own profile? 
If that is the case, should we allow a user to see to his profile page?

**Comment by lukaszfryc** [comment]
@cammellos oh, you are right. I was on my own profile. So, I think we should not allow to click on user's own profile. 

Btw, I found that non-admin can't access other people's profiles in group chat info screen. There is no options ("...") button like group admin has:

<img src="https://user-images.githubusercontent.com/7532782/48004207-d5f30500-e110-11e8-9ac1-3bce9f0519d4.png" width="500">

I think I will close this issue and create 2 separate to address above things.

**Comment by lukaszfryc** [comment]
I created https://github.com/status-im/status-react/issues/6614.
