### ISSUE TITLE
Localized requests may not complete

### ISSUE THREAD

**Issue by joshuam10o** [status-im/status-react#660]
#645  causes problems if the local representation of decimal points of the sender is different from the recipient ( , vs . ). 
![image](https://cloud.githubusercontent.com/assets/22443690/21713011/6745b54a-d400-11e6-9cd2-40682c87b7af.png)

Edit: fixing #645 may fix issues with decimals in requests. Actual issue (failure to perform request with a different representation of the decimal point) is not shown in screenshot, but I've sent in a report with the behavior.

**Comment by jarradh** [comment]
Thanks @joshuam10o ! I think this is a duplicate of #645 ?

**Comment by joshuam10o** [comment]
Sorry, didn't notice that, made the issue more specific. Is this still a duplicate?

**Comment by joshuam10o** [comment]
#665 describes the issue better, I'll close this.
