### ISSUE TITLE
User is redirected to home screen after opening and closing link in a chat

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6606]
### Description

*Type*: Bug

*Summary*: After i received a link in chat and opened it in Status browser i tap close and then i am redirected to Home screen which is not expected. I want to be redirected to the same chat i opened the link from.

#### Expected behavior
User is redirected back to the chat where the link was opened from

#### Actual behavior
User is redirected to Home screen

### Reproduction

- Open Status
- Go to public chat
- Open a link from any message in this public chat
- Close the browser window

**Comment by yenda** [comment]
@jeluard is this one for dapp team? (passing potato)

**Comment by jeluard** [comment]
@yenda Sounds like yes
