### ISSUE TITLE
"Create group chat" fixes for Desktop

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6607]
### Description
UI fixes for the process of creating a group chat on desktop.

### Solution
![group chat - select contacts - contact list1](https://user-images.githubusercontent.com/37297779/49299258-0e7ec800-f49e-11e8-8303-01c31079e8bf.png)

[Figma designs - Desktop](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=219%3A41389) > Group chat

[Figma designs - Mobile](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=227%3A320) > Group chat

### Notes
Other functionality regarding group chat like e.g. see group details, add more people, make somebody admin are still WIP. This issue is focused on group chat creation.

**Comment by churik** [comment]
Irrelevant in terms of #7551
