### ISSUE TITLE
Implement New Command UI / Fullscreen designs

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#661]
Many users face the issue of trying to navigate out of a browser tab, here is our first iteration on the new tab

![actions](https://cloud.githubusercontent.com/assets/2714786/21713538/0d48da04-d42d-11e6-8fdc-a2ce0f00588c.png)

**Comment by Jas0n-F** [comment]
Users on iOS reporting that wallet pulldown is interfered with by iOS pull-down menu functionality.

https://instabug.com/applications/status/beta/bugs/7?status=New
https://instabug.com/applications/status/beta/bugs/6?status=New

**Comment by annadanchenko** [comment]
extra instabug issues related to "implement back button" in Dapp screen and in Wallet screen:
https://dashboard.instabug.com/applications/status/beta/bugs/130
https://dashboard.instabug.com/applications/status/beta/bugs/121
