### ISSUE TITLE
Navigate to profile screen after clicking on a member in group info screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6614]
### Description

*Type*: Feature

*Summary*: When a group chat member (**non-admin**) opens the group info screen, he should be able to click on a member to see his/her profile. 

#### Expected behavior
1) When member is clicked, navigate to his/her profile screen.
2) When I click on myself, nothing should happen.

#### Actual behavior
Currently, nothing happens when clicking on member's avatar or name if you are not an admin of the chat. For admins, there is "..." that shows "View profile" and "Remove from chat" options.  

<img src="https://user-images.githubusercontent.com/7532782/48004207-d5f30500-e110-11e8-9ac1-3bce9f0519d4.png" width="500">

### Reproduction

- User A: Create a group chat with User B
- User B: Open group chat info and click on User A

### Additional Information
* Status version: Nov 6 develop, group chats enabled
* Operating System: all

**Comment by yenda** [comment]
@cammellos do you have this one in your scope?

**Comment by cammellos** [comment]
@yenda no, I can assign it to myself
