### ISSUE TITLE
Mobile notifications don't clear when selected 

### ISSUE THREAD

**Issue by J12B** [status-im/status-react#6618]
### Description

*Type*: Bug

[comment]: # I have received a mobile notification at the top of my screen from Status: "You have a new message". When I click the notification, it takes me into Status. However, the notification doesn't clear when doing that, so it still appears like I have a new message even though I do not. 

I can clear the notification by swiping, but would expect the notifications to clear upon accessing them. 

#### Expected behavior
[comment]: # Notifications clear once reviewed/access. 

#### Actual behavior
[comment]: # Notifications remain. 

### Additional Information
[comment]: # 
* Status version: 0.9.30 (11274)
* Operating System: Android 9

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by yenda** [comment]
@PombeirP have you seen that one? Seems related to what you are working on regarding PNv2?

**Comment by pedropombeiro** [comment]
Haven't come across this issue yet.
