### ISSUE TITLE
Sync user profile image on desktop and mobile

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6619]
### User Story
As a user, I want to see my profile image synced both on mobile and desktop. 

### Description
*Type*: Bug

*Summary*: After updating my user image on mobile, I don't see it reflected on desktop.

I changed my image on mobile:
![img_7454](https://user-images.githubusercontent.com/37297779/48070918-b4992400-e1b7-11e8-8f09-414175867a22.PNG)

This is what I see on desktop:
<img width="336" alt="captura de pantalla 2018-11-06 a la s 11 24 43 a m" src="https://user-images.githubusercontent.com/37297779/48070731-51a78d00-e1b7-11e8-8d96-10d3325dcc69.png">

#### Expected behavior
Same image on mobile and desktop for a specific account.

#### Current behavior
After changing the img on mobile, desktop keeps showing an old profile image.

### Reproduction
- Open Status Mobile
- Change your profile image
- Open Status Desktop
- Go to Profile and check image

### Solution
Sync user profile images desktop <-> mobile

Build V0.0.1 (7aa597517)

**Comment by churik** [comment]
@lukaszfryc is it fixed in https://github.com/status-im/status-react/pull/6714?

**Comment by lukaszfryc** [comment]
@churik yes. But, you need to pair to enable the sync. It's not automatic.

**Comment by churik** [comment]
Updated https://ethstatus.testrail.net/index.php?/cases/view/5680, consider issue as closed

<blockquote><img src="https://static.testrail.io/5.6.0.3841/images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/5680">Login - TestRail</a></strong></div></blockquote>
