### ISSUE TITLE
Ability to remove chat sessions from chat list

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#662]
At the moment there is no way to delete chats from the chat list. We need to think about how to do this.

![chat-list](https://cloud.githubusercontent.com/assets/2714786/21714284/c1f4d356-d430-11e6-84b6-02e348b87e19.png)

**Comment by Shrinks99** [comment]
Apple does this really well in the Messages app.  Users swipe the message to the left and it reveals a delete button.

This can be done in iOS with a [table-view row](https://developer.apple.com/reference/appkit/nstableviewrowaction)

**Comment by jarradh** [comment]
Agreed @Shrinks99 I love that approach

**Comment by andmironov** [comment]
guys, this won't work for us since we're using the swipe left/right to navigate through tabs

**Comment by andmironov** [comment]
we have "Edit mode" in contacts, let's do the same in chats (tap three dots icon on top -> edit -> icon appears next to each chat item)

**Comment by jarradh** [comment]
@andmironov this ticket is already closed
