### ISSUE TITLE
Push notifications don't show who is sending the message

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6621]
### User Story

As a user, I want to see where a message is coming from when I receive a push notification.

### Description
*Type*: Bug

*Summary*: Push notifications don't indicate where the message is coming from and the only way to know is by opening the app and searching for that message.

#### Expected behavior
Show origin of the message on a push notification.

#### Actual behavior
Nothing indicates where the messages are coming from:

<img width="353" alt="captura de pantalla 2018-11-06 a la s 12 12 05 p m" src="https://user-images.githubusercontent.com/37297779/48073394-6c7d0000-e1bd-11e8-8184-8e51f6ddc0b9.png">

<img width="354" alt="captura de pantalla 2018-11-06 a la s 11 49 00 a m" src="https://user-images.githubusercontent.com/37297779/48072721-f1671a00-e1bb-11e8-8eb4-c3250b28841a.png">

<img width="354" alt="captura de pantalla 2018-11-06 a la s 12 02 28 p m" src="https://user-images.githubusercontent.com/37297779/48072708-ed3afc80-e1bb-11e8-990a-c683631c0d11.png">

### Solution
For 1:1 chat, push notifications text should be:
- Title: **{User-Name}**
- Body: Message

<img width="451" alt="captura de pantalla 2018-11-06 a la s 12 09 08 p m" src="https://user-images.githubusercontent.com/37297779/48073126-cdf09f00-e1bc-11e8-8ee3-69d852fd566a.png">

For @mentions (feature TODO):
- Title: "**{User-Name} mentioned you**"
- Body: Mention message

<img width="472" alt="captura de pantalla 2018-11-06 a la s 12 10 51 p m" src="https://user-images.githubusercontent.com/37297779/48073212-0f814a00-e1bd-11e8-9fb3-c189c3aa4ecf.png">

For replies:
- Title: "**{User-Name} replied**"
- Body: Reply message

<img width="468" alt="captura de pantalla 2018-11-06 a la s 12 12 46 p m" src="https://user-images.githubusercontent.com/37297779/48073351-540ce580-e1bd-11e8-9aab-68a285ffd6ec.png">

### Additional Information
Please note that we still don't have the mentions feature :)

**Comment by oskarth** [comment]
I notice the desktop notification shows message payload. Is this encrypted end to end?

**Comment by pedropombeiro** [comment]
The desktop notifications are currently done purely on client-side (as each message is retrieved and added to the db, there's logic to determine if a notification should be shown to the user). This means that the user won't see notifications if the app isn't running.

**Comment by churik** [comment]
@EugeOrtiz I believe we can close it or update the title because the current version of PNs do show source, contact and time.
WDYT?
