### ISSUE TITLE
After first login with existing account "Send" button is disabled until logout

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6628]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when login for the first time after upgrading to the new build, "Send" button will be disabled until relogin to the app.
Could reproduce 2 times from 5 attempts.

#### Expected behavior
Can send message

#### Actual behavior
Send button is disabled
<img width="346" alt="12345" src="https://user-images.githubusercontent.com/4557972/48122820-c55d9e80-e278-11e8-919e-078fb39aa18c.png">

### Reproduction
**Prerequisites**: user already have account on one of the previous nightly

**Scenario 1:**
- Install (replace) last nightly
- Open Status
- Log in
- Try to send a message

**Scenario 2:**
- Install last nightly
- Create new account
- Join to public chat
- Try to send a message

Sometimes relogin can help, but not always.
My assumption that application for some reason lost connection with mailserver and no warning is shown, because in all cases messages are not fetching.

### Additional Information

* Status version: nightly 07/11/2018
* Operating System: Mac OSx
* Video: https://monosnap.com/file/CNkcaLYFPYQUSBeu14xQ1MXhsGMIb4

#### Logs

* StatusIm.log: https://drive.google.com/open?id=1i3MQHreDdJ5Ah2yZm2gxsJRY0JFBbcoq

**Comment by hetvart** [comment]
NOTE: several tests failed due to the same reason in Status Mobile (latest nightly, StatusIm-181108-025919-ae3029-e2e.apk). The repro scenario works on mobile app as well.

**Comment by churik** [comment]
@dmitryn I believe it can be related to https://github.com/status-im/status-react/pull/6467.
Several  users also complaining about it.
Can you please take a look when you have a time?

**Comment by dmitryn** [comment]
@churik we have PR that should likely to fix it https://github.com/status-im/status-react/pull/6647

**Comment by dmitryn** [comment]
Fixed by https://github.com/status-im/status-react/pull/6647
