### ISSUE TITLE
Touchid/Fingerprint Authentication

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#663]
We should allow touchid/fingerprint authentication to login and sign requests.

**Comment by rolandkofler** [comment]
Take a moment to reflect what security researchers say:
> Your fingerprint is your username not your password

Nobody would write their password on the back of their smartphone, yet the fingerprints are all over it.

**Comment by carlbennetts** [comment]
https://instabug.com/applications/status/beta/bugs/67

**Comment by tiabc** [comment]
Absolutely necessary. It's totally inconvenient to login by password every time.

**Comment by chadyj** [comment]
Closing since this is more active/recent https://github.com/status-im/status-react/issues/5557
