### ISSUE TITLE
Pinned messages in 1-1 and group chats

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6640]
### User Story

As a user, I want to pin or star messages to have quick access to them.

### Description

*Type*: Feature request

*Summary*: to have quick access to selected messages which I want to save would be nice to create feature like pinned messages at least for group (for admin) and 1-1 chats. Not sure if we can that for public chats due to security reasons.
How it works in other messengers:
**On WhatsUp:** no pinned messages, but they have starred messages. If you star a message you can quickly access it in user profile.
**On Telegram:** one pinned message in group chats, can be added only by group admin
**On Slack:** can create several pinned messages in 1-1 and public chats and quickly access them using the special icon.
IMO variant with Slack is most convenient as we used Status as the primary communication tool

#### Expected behavior
can pin the message for group and 1-1 chats

#### Actual behavior
no action to pin the message

* Operating System: all

Issue is just to start a discussion around possible feature. Any comments appreciated.

**Comment by StatusSceptre** [comment]
Is there a bounty size we'd like to make this?

**Comment by StatusSceptre** [comment]
@yenda @churik following up on bounty size and if it is still bounty worthy.

**Comment by yenda** [comment]
I think this feature is too big for a bounty, it would also require design input before it can be implemented

**Comment by guylouis** [comment]
replaced by #11699
