### ISSUE TITLE
Chat command recipients should be able to install an extension

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6644]
### User Story

As a user, I want the ability to easily install the extension needed to show the chat command message. The extensions URL could be sent as part of the message payload.

### Description

*Type*: Feature

When receiving a message from an unknown command, a placeholder message is displayed.

It should be easy to install the required command from the chat screen.

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/49152269-920bae00-f312-11e8-8704-704f1284a008.png)

**Comment by denis-sharypin** [comment]
Link from the message triggers extension popup

<img width="879" alt="screenshot 2018-11-28 13 32 32" src="https://user-images.githubusercontent.com/6559881/49152108-16a9fc80-f312-11e8-840c-ca7354732d92.png">

**Comment by flexsurfer** [comment]
@rachelhamlin could you help with the copy?

**Comment by rachelhamlin** [comment]
Looks OK. Slight modification: 

“To see this message,
install the extension”

**Comment by flexsurfer** [comment]
![install-extension](https://user-images.githubusercontent.com/11790366/49161452-25e87480-f329-11e8-8d77-00cc7809e0bb.gif)

**Comment by rachelhamlin** [comment]
Good by me!
