### ISSUE TITLE
Status could not connect to peers on public wifi network

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6645]
### Description

*Type*: Bug

*Summary*: 

I was connected to a public wifi that had internet. All pages like google.com loaded fine. But, Status kept showing "Connecting to peers..." and did not fetch any messages. I tried on iOS, Android and Desktop. It would be great to investigate it as it may be the case for many of our users. I was looking at the logcat, but there was nothing that might be related. I'm attaching geth.log to investigate it.

[geth.log](https://github.com/status-im/status-react/files/2560978/geth.log)

<img src="https://user-images.githubusercontent.com/7532782/48186894-a6731100-e339-11e8-8bac-255ed91816a4.png" width="200">

### Reproduction

No exact steps to reproduce. I was on open public wifi network.

### Additional Information
* Status version: nightly, Nov 8
* Operating System: Android, iOS, Desktop

**Comment by Swader** [comment]
I'd say this is a pretty big deal.
