### ISSUE TITLE
Improve chat list

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6657]
### Description
Updated design for the chat list (left panel). Design improvements include:

- A more condensed list of chats
- Clearer highlight of current chat
- Background color to highlight the chat area and bring focus to the conversation

### Current implementation vs new design
![group2](https://user-images.githubusercontent.com/37297779/48223116-0a66fb00-e375-11e8-83d6-a3f28dbabd47.png)

### Solution

- [ ] Implement chat rows
- [ ] Review margins and paddings of rows
- [ ] Implement row highlight
- [ ] Review margins and paddings of row highlight
- [ ] Implement public channel row design
- [ ] Apply background color
- [ ] Review font sizes, colors and weights according to the designs
- [ ] Review it with your UX friend before merging :)

[Designs @ Figma ](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=309%3A11691)

**Comment by churik** [comment]
Irrelevant in terms of #7551
