### ISSUE TITLE
Android: (optionally) use different package name for debug builds

### ISSUE THREAD

**Issue by d10r** [status-im/status-react#666]
Currently, it's not possible to have a release build and a debug build installed on the same device at the same time.
Since debug builds can be used only when connected to a Computer, that's inconvenient.

With gradle, it's easy to configure a different package name for debug builds, see [build types doc](https://developer.android.com/studio/build/build-variants.html#build-types).

I tried this (see [commit](https://github.com/d10r/status-react/commit/32d8452fc3332521039afcfdaf9229f522c5ae9a)) with the following result:

The next run of ```react-native run-android``` successfully builds and installs with the new package and App name...
<pre>
$ adb shell "pm list packages | grep status"
package:im.status.ethereum.debug
</pre>
... but fails to start the App:
<pre>
...
:app:installDebug
Installing APK 'app-debug.apk' on 'D6603 - 6.0.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 48.842 secs
Starting the app on BH913W671L (/home/didi/dev-tools/android-sdk-linux/platform-tools/adb -s BH913W671L shell am start -n im.status.ethereum/.MainActivity)...
Starting: Intent { cmp=im.status.ethereum/.MainActivity }
Error type 3
Error: Activity class {im.status.ethereum/im.status.ethereum.MainActivity} does not exist.
</pre>

Since it was installed successfully, I can manually start the App on the phone. If I do so, everything seems to work as expected (it may be necessary to first restart the react packager and lein repl though).

I'm not yet familiar with the react-native stuff, thus currently stuck here. Help appreciated!

Also, it may not be desirable to have this change applied by default. It could be configurable, e.g. by having a dedicated build variant.

**Comment by mandrigin** [comment]
that is already implemented. the package name is `im.status.ethereum.debug` for debug builds for both iOS and Android.
