### ISSUE TITLE
Terms and conditions for Desktop redirect to Mobile T&C

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6663]
Description

Type: **Bug**

Summary: When you click on 'Terms and Conditions' link for desktop, you are redirected to a link https://www.iubenda.com/privacy-policy/45710059 that has 'Privacy Policy of Status Mobile' as a title
Probably we should change the title, or make a separate page for ''Privacy Policy of Status Desktop''

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/43638377/48211015-42743b00-e381-11e8-9bbf-2eb10f496098.png">

**Expected behaviour**

User is redirected to ''Privacy Policy of Status Desktop'', or at least something that does not specify directly to Mobile

**Actual behaviour**

User is redirected to a page that has 'Privacy Policy of Status Mobile' as a title

Steps to reproduce:

1. Go to Welcome page of Status Desktop
2. Click on 'Privacy Policy' link at the bottom

<blockquote><img src="https://www.iubenda.com/images/site/fb-image.png" width="48" align="right"><div>iubenda</div><div><strong><a href="https://www.iubenda.com/privacy-policy/45710059">Privacy Policy of Status Mobile</a></strong></div><div>This Application collects some Personal Data from its Users.</div></blockquote>

**Comment by churik** [comment]
cc @chadyj 
As release are coming soon, should we create new T&C specific for Desktop?

**Comment by churik** [comment]
Irrelevant in terms of #7551
