### ISSUE TITLE
Amount of unread messages in app doesn't match OSX dock bar and Home tab doesn't have dot when we have unread messages

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6672]
### Description
*Type*: Bug

The number of unread messages in the app doesn't match the info in OSX dock bar.

<img width="1434" alt="captura de pantalla 2018-11-09 a la s 10 53 02 a m" src="https://user-images.githubusercontent.com/37297779/48266377-f3281c00-e40d-11e8-8428-702e52b19667.png">

#### Expected behavior
To show the same amount of unread messages both in the app and in the OSX dock bar.

### Reproduction
- Open Status Desktop
- Wait until receiving a new message
- Check dock bar

Following https://github.com/status-im/status-react/pull/6888:
The home tab should indicate that there is activity going on (see proposed design). I think we will be repeating information by adding again the total amount of unread messages (already on dock). A simple "dot" could be used to indicate that there is activity going on. We could also use this for Profile when we need to get the user's attention. [Design proposal](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=377%3A0):
![group 19](https://user-images.githubusercontent.com/37297779/49243569-6eb53180-f3ec-11e8-8789-ee57e9da651f.png)

![group 22](https://user-images.githubusercontent.com/37297779/49243622-87254c00-f3ec-11e8-8b51-95834b9982e4.png)

Summary:
[ ] - OSx dockebar should have amount of all unread messages
[ ] - Home tab should have dot to indicate about any activity

**Comment by EugeOrtiz** [comment]
The dock seems to show only # of direct messages from 1:1 chats.

**Comment by churik** [comment]
It is feature, @EugeOrtiz 
When there are unread messages in public channels, only red dot is shown

**Comment by EugeOrtiz** [comment]
I reopen the issue for discussion. 
I think we should show the entire amount of unread messages in the dock, no matter where they come from. A dot seems to indicate that there are no unread messages. 

For example, Telegram shows the entire amount of unread message in the dock, no matter if they are from a channel or a 1:1 conversation.

**Comment by SlizkovaGanna** [comment]
@EugeOrtiz 
I agree, we should either:
**1)** show the dot if there's any activity for all the cases (no matter if that is 1-1 chat, group chat or a public chat)
**2)** show the exact number of new messages, for all the cases (no matter if that is 1-1 chat, group chat or a public chat)

Right now, we are showing only messages received in 1-1 chats and group chats, and it is confusing from user perspective.
The fact that logic for public chats is different from group chats - doesn't make sense, and is a bug even if we want to stay with the old logic. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/43638377/49284894-99f85900-f49e-11e8-9d2b-cabbdcfe6849.png">

@chadyj @churik @siphiuel @lukaszfryc what do you guys think?

**Comment by SlizkovaGanna** [comment]
A good point from @errorists on this, from a different comment - https://github.com/status-im/status-react/pull/6888#issuecomment-442950127

> I'd like to clarify one bit though, with the total unread badge on the dock icon, you mean the sum total number of unread messages across all chats or the number of chats with unread messages, afaik Telegram, Messenger or Whatsapp follow the second option and I'd assume we want to also. Having the number on the dock badge update for each new single message across all chats can be irritating and I feel unnecessary.
