### ISSUE TITLE
Different tabs for Chats and dapps

### ISSUE THREAD

**Issue by MoribETM** [status-im/status-react#6675]
Hey, if you have a lot chats and dapps, its getting really annoying to find the right chat!
An easy solution for this would be to make different tabs for dapps and chats!
Thx, have a nice day

**Comment by Swader** [comment]
It silly that this is still not a thing

**Comment by rachelhamlin** [comment]
Thanks for opening an issue @MoribETM. We completely understand the frustration.

There's conflict with other discussions about Status global nav, captured [here](https://notes.status.im/IUih9JLaR--1iMU97PrD2A). 

That said, improved designs do exist and we're pushing to advance them in this [new issue](https://github.com/status-im/status-react/issues/7534).
