### ISSUE TITLE
New group chat feature doesn't work on macOS

### ISSUE THREAD

**Issue by pcowgill** [status-im/status-react#6676]
### User Story

As a user, I want to create a new public group chat so that others can join it and chat with me.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Clicking Start chat under New Group chat doesn't work.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I thought I would be prompted to pick a name for a new public chat.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The app showed nothing but a white screen indefinitely (like how it looks when you first open the desktop app, but it never went away).

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
After logging in, click `+` button next to `Type here to search chats...`. Then click `Start chat`.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: Something should happen when you try to create a new group chat.

- [ ] Make something happen when you click `Start chat` under `New Group chat`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: macOS v0.0.1 (0bc9fb6d9)

[comment]: # (Android or iOS.)
* Operating System: macOS Mojave version 10.14.1

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
n/a

**Comment by EugeOrtiz** [comment]
[Here are the designs](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=230%3A11231) for the flow of creating a group chat. 

@cammellos Can you let me know if you can implement this?

**Comment by cammellos** [comment]
this should be fixed in #6697 please re-open if it's not the case, thanks for reporting the issue!

**Comment by pcowgill** [comment]
@cammellos It doesn't appear to be fixed in the latest nightly desktop build, c088e7b65

**Comment by pcowgill** [comment]
@cammellos Should we reopen this issue, based on that? (cc @EugeOrtiz)

**Comment by cammellos** [comment]
@pcowgill could you please replicate with a newer nightly and re-open if still the case?
Thanks!
