### ISSUE TITLE
"Send" button is always enabled on Desktop

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6684]
### Description
"Send" button is enabled all the time, even when there is nothing to send. It should only be enabled only if the user typed something in the input field.

*Type*: Bug

### Expected behavior
Button disabled if no text or only spaces:
<img width="671" alt="captura de pantalla 2018-11-12 a la s 9 49 19 a m" src="https://user-images.githubusercontent.com/37297779/48348480-42658b00-e660-11e8-9e6d-829cba6adb31.png">

Button enabled when there is text:
<img width="691" alt="captura de pantalla 2018-11-12 a la s 9 52 46 a m" src="https://user-images.githubusercontent.com/37297779/48348663-bbfd7900-e660-11e8-9130-5382f2299b7f.png">

### Actual behavior
Send button is always enabled.
<img width="684" alt="captura de pantalla 2018-11-12 a la s 11 08 43 a m" src="https://user-images.githubusercontent.com/37297779/48352404-5cf13180-e66b-11e8-8078-f4bba5d30e35.png">

### Reproduction
- Open Status Desktop
- Join a chat

### Solution
- [ ] If no text (or only spaces), button disabled
- [ ] If text, button enabled :)

Issue related to #6111

**Comment by churik** [comment]
Irrelevant in terms of #7551
