### ISSUE TITLE
Group chat not working properly

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6685]
### Description

During the last step of the group chat creation flow, the user get's stuck on an empty screen.

*Type*: Bug

#### Expected behavior
Group chat created and redirected to the chat list after typing the name of the group chat.

#### Actual behavior
User gets stuck after typing the name of the group chat on this screen:
<img width="1021" alt="captura de pantalla 2018-11-12 a la s 11 15 54 a m" src="https://user-images.githubusercontent.com/37297779/48352883-be65d000-e66c-11e8-8834-65e0fd058f26.png">

### Reproduction
- Open Status Desktop
- Start a new group chat
- Add members
- Add group name
- Get stuck 👎 

### Solution
After user creates a group chat, it should be redirected to the group chat she just created.

Wanna make group chat better? Check also issue #6607

**Comment by churik** [comment]
known, will be fixed https://github.com/status-im/status-react/pull/6658

**Comment by cammellos** [comment]
fixed in #6697
