### ISSUE TITLE
User is being redirected to 1-1 chat when requesting assets from wallet

### ISSUE THREAD

**Issue by hetvart** [status-im/status-react#6687]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When user is sending a transation request to a contact the app redirects him/her to 1-1 chat with the contact. 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Setup/recover 2 accounts: primary and secondary with some ETH on these accounts
2. Login as primary account and add secondary account to contacts (start 1-1 chat)
3. Setup wallet 
4. Click 'Receive transaction' -> 'Send a transaction request'
5. Provide an amount, and secondary acccount as a recipient
6. Click 'Send request'

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
the user should stay on Wallet screen when the request is sent

#### Actual behavior
[comment]: # (Describe what actually happened.)
the system opens 1-1 chat with the contact person

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
0.9.30 (12054)
* Operating System: Android 7.1

**Comment by goranjovic** [comment]
This actually works as intended. But I do see your point in the inconsistent behavior between Send and Request in Wallet. We'll discuss this with the UX
