### ISSUE TITLE
Update ENS resolving implementation to match what is defined in EIP-1577

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#6688]
**What problem are you trying to solve?**

To try and find a better system @arachnid and I created [EIP-1577](https://github.com/ethereum/EIPs/pull/1577) that allows for a better representation of network and content addresses.

**Describe the solution you'd like**

Implement resolution using the new `multiaddr` field when available.

*Issue was copied over from the [Metamask](https://github.com/MetaMask/metamask-extension/issues/5742) repository because of laziness*

**Comment by decanus** [comment]
There will be changes made to the EIP so implementation should be paused.

**Comment by decanus** [comment]
The EIP has been updated and should be good to go: https://eips.ethereum.org/EIPS/eip-1577

<blockquote><div>Ethereum Improvement Proposals</div><div><strong><a href="http://eips.ethereum.org/EIPS/eip-1577">contenthash field for ENS</a></strong></div><div>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards.</div></blockquote>

**Comment by decanus** [comment]
The EIP has been updated @rachelhamlin, the implementation will need updating too. https://eips.ethereum.org/EIPS/eip-1577

<blockquote><div>Ethereum Improvement Proposals</div><div><strong><a href="http://eips.ethereum.org/EIPS/eip-1577">contenthash field for ENS</a></strong></div><div>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards.</div></blockquote>

**Comment by jeluard** [comment]
@decanus Do you mind pointing at what changed specifically?

**Comment by decanus** [comment]
@jeluard The multicodec table used and the way the hashes are encoded.

**Comment by rachelhamlin** [comment]
thanks @decanus 🙏
