### ISSUE TITLE
Desktop client doesn't have a connection with mailserver and doesn't fetch messages

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-react#6689]
### User Story

I want to fetch messages when application was offline for some time and when i join new channel.

### Description
*Type*: Bug

Desktop client doesn't fetch messages when app is restarted or when i join the channel. Additionally there are no connection to mail server. On linux you can check your connections using lsof or netstat, for example:

```
> lsof -i -P | grep 23121

AppRun    23121   dd   28u  IPv4 11408906      0t0  TCP localhost:48414->localhost:5000 (ESTABLISHED)
AppRun    23121   dd   41u  IPv6 11412426      0t0  TCP *:35375 (LISTEN)
AppRun    23121   dd   45u  IPv4 11404011      0t0  TCP dd-desktop:58376->waw02s07-in-f164.1e100.net:80 (ESTABLISHED)
AppRun    23121   dd   47u  IPv4 11415569      0t0  TCP dd-desktop:50000->47.89.16.125:30305 (ESTABLISHED)
AppRun    23121   dd   51u  IPv4 11415570      0t0  TCP dd-desktop:50308->236.60.238.35.bc.googleusercontent.com:30305 (ESTABLISHED)
AppRun    23121   dd   59u  IPv4 11413000      0t0  TCP dd-desktop:56448->47.52.173.66:30304 (ESTABLISHED)
```
Look for ESTABLISHED connection to hosts with ports 30304/5. All of them can be found in our fleet of whisper nodes - https://fleets.status.im/. I expect to see at least one connection to a mail server, maybe temporarily.

### Reproduction

- restart an app or join existing channel
- wait for messages
- check connections

### Additional Information
* Status version: d2160e3
* Operating System: Ubuntu

#### Logs

They are huge. I will try to capture new logs

<blockquote></blockquote>

**Comment by dshulyak** [comment]
I selected different mail server and now my client fetches messages and has a connection with mail server. So in my case this is probably just a lack of feedback that i wasn't able to connect with initial mail server.

**Comment by cammellos** [comment]
I have the same issue with:
mail-03.do-ams3.eth.beta
@jakubgs how's that mailserver? I can't get any messages from it

**Comment by pedropombeiro** [comment]
Unfortunately, the status-go code is too far ahead compared with the deployed eth.beta mailservers, so the canary is incompatible and can't give us any meaningful information. It does work with eth.staging, which suggests we should upgrade eth.beta.

**Comment by cammellos** [comment]
@PombeirP got it, thanks

**Comment by cammellos** [comment]
@adambabik how is it looking for upgrading the fleet?

**Comment by adambabik** [comment]
We want to deploy `eth.beta` today. It was tested yesterday with the current release.

**Comment by jakubgs** [comment]
The upgrade was finished today, the `eth.beta` fleet now runs a up-to-date `statusd`.

**Comment by jakubgs** [comment]
Is this still an issue?

**Comment by dshulyak** [comment]
I think so. We didn't do anything to address a problem that any given mail server can run out of slots for connections. We need at least to have a feedback for the user that we cannot connect with mail server

**Comment by jakubgs** [comment]
@dshulyak 
>We need at least to have a feedback for the user that we cannot connect with mail server

As far as I can tell `MaxPeers` setting isn't a Whisper setting but a Devp2p one, I don't see anything related there:
https://github.com/status-im/whisper/blob/master/whisperv6/whisper.go
@adambabik would it be possible to send back an envelope about reaching max peers?

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/whisper">status-im/whisper</a></strong></div><div>Contribute to status-im/whisper development by creating an account on GitHub.</div></blockquote>

**Comment by mandrigin** [comment]
I think we have an error notification for that right now even in Desktop and we should be much better at connecting to mailserver. Feel free to reopen if you are disagree.
