### ISSUE TITLE
Allow commands to add events before parameters filling

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6691]
### User Story

As a developer, I want to trigger extra events before and after a command parameter is filled.
This allows the retrieval of external data that would then be used to display better parameter suggestion.

```clojure
:parameters [{:id                     :some-id
             :placeholder             "Some placeholder"
             :on-before-user-input    [some-event]}]
```

Those events will receive as properties the value of all previously filled parameters as a vector.

### Description

*Type*: Feature

**Comment by janherich** [comment]
I don't think the approach here is the right one, there are several problems with that:

* Command can be entered in multiple ways, typing it, selecting from list of available commands, or pasting the whole text of command string with or without arguments - would be the method for example called even if command string with arguments is pasted into the input field, there is no "middle state" of selected command without arguments ?
* Retrieval of external data is usually asynchronous process which can take some time to complete - if I for example write `/send-collectible` in the input field and expect that I will have immediately suggestions for collectible types or particular NFT (second argument) available, it won't be the case and as a user, I will be confused, assuming that the command just doesn't work properly.
* It's potentially inefficient to start the data retrieval each time each time the command is selected, and anything else (caching, etc) would require per-case approach which could not be applied to all commands in generic way

Better solution in my opinion is to introduce a concept of dependencies (backed by the protocol probably), where each "component" can declare dependency like `/send-collectible` -> `#{:cryptokitties :strikers}` (pseudocode) and upon start-up, the app will iterate over available components and automatically fetch declared dependencies for them.
it will be much more declarative and nicer then imperative "do this, do that" approach for loading dependencies which we currently have, for example as loading of specific tokens upon visiting some screen in wallet (cc @goranjovic ).

**Comment by jeluard** [comment]
I agree it would be better to have something like that, especially for the NFT command.
Now we still need that chat command hook in the general case IMO.

**Comment by jeluard** [comment]
Replace by view lifecycle hooks.
