### ISSUE TITLE
Add SNT Voting Dapp to Dapp List

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/status-react#6693]
**Dapp Name:** SNT Voting DApp

**Category:** Utilities

**URL:** https://vote.status.im

**Order:** after `Smartz`, before `Status Test DApp`

**Description:** Let your SNT be heard! Vote on decisions exclusive to SNT holders, or create a poll of your own.

**SVG code:** https://docs.google.com/document/d/1qTelQkduddwF1s5uv3pVoATqFTsO21MTd5QzI2M781I/edit?usp=sharing

**Comment by jeluard** [comment]
@denis-sharypin Do you mind creating a PNG from the SVG? :)

**Comment by jeluard** [comment]
@errorists Can you help with that? :D

**Comment by flexsurfer** [comment]
@Graeme-Code can we register ens and add dapp with this ens ?

**Comment by errorists** [comment]
![votingdapp](https://user-images.githubusercontent.com/4932774/48412670-a1e99680-e745-11e8-96a7-20135b695f73.png)

**Comment by rachelhamlin** [comment]
Can we merge this to include in the release in the meantime?

**Comment by jeluard** [comment]
@rachelhamlin Sure! Just merged.

**Comment by rachelhamlin** [comment]
Thanks!

**Comment by rachelhamlin** [comment]
Left a request in voting DApp repo to register ENS - https://github.com/status-im/snt-voting/issues/40
