### ISSUE TITLE
ENS dapp does not reflect web3  opt-in

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6694]
### Description

*Type*: Bug

*Summary*: ENS dapp does not ask for web3 permissions when this is enabled in Profile

#### Expected behavior
ENS dapp should ask for wallet / profile permissions when web3 is enabled

#### Actual behavior
`names.statusnet.eth` dapp does not ask for permissions with web3 enabled

### Reproduction

- Open Status
- Enable web3 provider in profile
- Open `names.statusnet.eth`

**Comment by rachelhamlin** [comment]
Closing. Will handle with [#78](https://github.com/status-im/ens-usernames/issues/78) in the ens-usernames repo.
