### ISSUE TITLE
Stuck at 'Connecting to peers'

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#6701]
Same on Desktop old nightly and latest nightly, and mobile. Public WiFi and 4G. ~5 mailserver, with restarts in between.

Seems like it happens to a few people. Suspect cluster/fleet issue.

Last message for me received ~1h ago.

Thread to diagnose.

**Comment by oskarth** [comment]
Duplicate, see https://github.com/status-im/status-react/issues/6700

**Comment by jakubgs** [comment]
The `docker` service failed to reboot correctly on the fleet. Working on it.

**Comment by jakubgs** [comment]
Ok, the containers should be back up and running.

**Comment by jakubgs** [comment]
Wait, not yet.

**Comment by jakubgs** [comment]
Ok, now it should be back up.
