### ISSUE TITLE
Standardized debug artifact generation

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#6710]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to work with standardized debug/logging artifacts so that I don't miss any vital information when debugging an issue, and can trust that all required information is present in this standardized artifact.

As a user, I want to have a 1-click solution to provide debugging information to the app developer so that I'm not required to go hunt for logs on the file system and know that the developer won't be missing any important information.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently gathering logs to report a bug is a non-trivial task even for Core contributors. The issues with it are:
- The two relevant logs, status-react log (`Status.log`) and the status-go log (`geth.log`) are located in separate folders, which differ per platform (we currently support 5 platforms). `Status.log` is only generated on desktop platforms, for mobile we currently rely on developer tools which won't be available to end users;
- The user needs to remember to fetch the two of them and not just one;
- The user needs to remember to set the appropriate log level before collecting the logs;
- Having a safe export of the app db could be useful to debug certain issues (e.g. it could tell us how many peers a device is connected to, which mailserver it is connected to, etc.);
- The user probably wants to zip the files so he can easily attach them on an email, which is something that can/should be automated.

We can do much better by automating most of these steps for the end-user.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

1. User notices buggy behavior in app and decides he wants to report it;
1. User enables logging in the app (ideally we have a single setting which would take care of that, but that's for a later GHI).
1. When user is finished reproducing bug, he/she clicks on `Send logs` button and the app will:
  1. Fetch logs/system information/P2P status and zip the files;
  1. Share this file using the OS share dialog on mobile (which allows sharing to Gmail, etc), or by opening a file explorer on the folder location (on Desktop).

**Comment by pedropombeiro** [comment]
@andmironov I'd like to get this bountied out. Do you want to give some guidelines on how you'd want this to look, or is a `Send logs` button inside the advanced section good enough?

**Comment by pedropombeiro** [comment]
Decided to take a stab at this (which doesn't invalidate any external contributor from picking it up and finishing it), and this is what it's currently looking like: [video](https://drive.google.com/file/d/1fmLa7PwxGL-tWmvM6hOS4f7fLK_rNhIP/view?usp=sharing). Still missing `Status.log`, but if I'm not mistaken this is currently only being generated for Desktop, right? Thoughts welcome @annadanchenko, @Serhy.

[debug.zip](https://github.com/status-im/status-react/files/2683117/debug.zip)

**Comment by pedropombeiro** [comment]
Current design on the Desktop app, cc @andmironov:

![image](https://user-images.githubusercontent.com/138074/50148759-9bf15300-02b9-11e9-9690-7405a51f45b8.png)

**Comment by annadanchenko** [comment]
1. Will created logs be automatically deleted after sending?
2. for mobile: are we going to create separate Status.log instead of getting logcat/console log? 
3. Will keycard events be included in the log? If so in which one?
4. Should we add some disk space check before starting log?
5. Is there any difference between release/nightly/pr build logging? Will be all logs turn to DEBUG by default on nightly/pr and turned off on release? (that is preferred way personally for me as a tester to catch bugs I can't reproduce on nightly/pr at least in the logs)

**Comment by pedropombeiro** [comment]
By the way, I've had to move `geth.log` to the app data directory so that the app can read it and zip it. That means e.g. we can't access it with `adb shell` and must rely on the app export functionality to see the file.

**Comment by pedropombeiro** [comment]
>     1. Will created logs be automatically deleted after sending?

We can delete them if we wish (although for geth.log that'd probably require stopping the node, deleting the file and then restarting the node)

>     2. for mobile: are we going to create separate Status.log instead of getting logcat/console log?
> 

That's the idea, end users won't have a way to send us Status.log if we don't implement this (except maybe for power users).

>     3. Will keycard events be included in the log? If so in which one?

I imagine these are system-level events, so they would normally not show up in Status.log. It depends on how we end up generating Status.log. If we just redirect `adb logcat` to a file, we could also capture those events.

>     4. Should we add some disk space check before starting log?

Definitely. At some point, we should also implement log rotation to avoid consuming too much disk space with our logs.

>     5. Is there any difference between release/nightly/pr build logging? Will be all logs turn to DEBUG by default on nightly/pr and turned off on release? (that is preferred way personally for me as a tester to catch bugs I can't reproduce on nightly/pr at least in the logs)

I'm not planning any changes to the current default log levels. The only thing is that we'll have this `Enable debug mode` switch which will make sure the log level for every log is set to DEBUG for as long as it is active.

**Comment by pedropombeiro** [comment]
Pinging @hesterbruikman for any UX input you might have.

**Comment by andmironov** [comment]
Hey, sorry can't give any input regarding desktop now. i've been working on something similar for mobile, take a look if it helps https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=1%3A467


<blockquote><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=1%3A467">Figma</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
> Hey, sorry can't give any input regarding desktop now. i've been working on something similar for mobile, take a look if it helps https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=1%3A467

I can't seem to access the link (I've signed up to Figma using my status email, but still no luck)

<blockquote><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=1%3A467">Figma</a></strong></div></blockquote>

**Comment by andmironov** [comment]
invite sent
