### ISSUE TITLE
Display name should be persisted over time

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6711]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a chat user, I want to always see the names of people where that have added me as a contact so that I know who I'm talking to.

### Description

From a users point of view the app seems to sometimes forget names of contacts and relationship. This tends to happen with multi-devices or across installs.

One day I'll see I'm chatting with "Fred", and the next day I see "random three names".

I'll also see the "add to contacts" UI of someone I've added multiple times already

#### Expected behavior
- Remember the name and connection status

#### Actual behavior
- Random names showing along with "add to contact" UI

**Comment by churik** [comment]
@chadyj are you sure it is not because Fred reinstalled the build and restore his account on new device?

**Comment by cammellos** [comment]
I'll take this, one issue is for sure multi-device (once you re-install it propagates the random name again), I'll work on keeping account info (name & photo path synced across devices), and then we can revisit

**Comment by cammellos** [comment]
> I'll also see the "add to contacts" UI of someone I've added multiple times already

this should be addressed by #6697 in most cases (it works in the same way messages work, so if a device is offline and the sync-update is not on the mailserver, you'd have to sync them manually again)

**Comment by lukaszfryc** [comment]
> this should be addressed by #6697 in most cases 

I will test it and close the issue.

**Comment by cammellos** [comment]
@lukaszfryc it's two separate issues at play here, `Add to contacts` should be fixed by pairing/etc, while reverting to default contact name should be fixed in the scope of https://github.com/status-im/status-react/pull/6714

**Comment by lukaszfryc** [comment]
@cammellos thanks for details.

> Add to contacts should be fixed by pairing/etc, 

Yes, it works when devices are paired.

> while reverting to default contact name should be fixed in the scope of #6714

Sounds good!
