### ISSUE TITLE
Unread message counter appears for own messages

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6716]
### Description

*Type*: Bug

*Summary*: When user opens a public chat on multiple devices (like 2 phones) and sends a message on one of them, the message appears as unread on the 2nd device.

#### Expected behavior
Own messages should not be added to unread messages counter on other devices.

#### Actual behavior
Own messages appear as unreaded on another devices.

### Reproduction

- Join a public chat on 2 devices
- Device A: send a message
-> Device B: sees the message as unread.

### Additional Information
* Status version: nightly, Nov 14
* Operating System: all

**Comment by cammellos** [comment]
This should have been fixed in https://github.com/status-im/status-react/pull/6697 and should work as expected in latest nightly, could you check and close if it's the case?

**Comment by lukaszfryc** [comment]
Yes, works fine. Tested on `89e0ea`. Thanks @cammellos
