### ISSUE TITLE
No new message when push notification is opened

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6717]
### Description

*Type*: Bug

*Summary*: Few people have complained that when they click on a push notification, the new message does not appear. It maybe related to the message not being fetched correctly when the app opens. I could not reproduce it on my side. 

### Reproduction

No steps to reproduce yet.

### Additional Information
* Status version:
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@adambabik and @jarradh did you experience this issue on your side? Does it still happen? If yes, please share steps you do and logs (`adb logcat`, `adb pull /sdcard/Download/geth.log`)

**Comment by adambabik** [comment]
I had it yesterday. The question is when I get a Push Notification, does the message is already downloaded in the app? If not, it's totally possible that I get a notification, open the app and the message is simply not there yet.

Another thing is that when I have many private chats, I have no idea which conversation that notification was related to. But I guess fixing this requires rethinking Push Notifications.

**Comment by 0xc1c4da** [comment]
I have this behaviour consistently, noticed it before Prague, I have 2 accounts in Status but no one messages me on the second one (no one knows it and there is no contacts in it).

I often receive a push notifications, however once I've "signed in" (can we change this wording because it's not exactly what's happening) and messages are fully fetched, yet no new private messages are to be found. I have tried different mailservers to no avail.

They appear to be lost forever. On several occasions I have been asked why I haven't responded, the most recent was yesterday where Graeme has even asked me if I received his last message.

re @adambabik regarding PN. it might be possible, the reason we don't is because we don't want to leak metadata. 

I will attempt to pull logs  next time it happens, though I suspect it's a Mailserver thing

**Comment by lukaszfryc** [comment]
> The question is when I get a Push Notification, does the message is already downloaded in the app? If not, it's totally possible that I get a notification, open the app and the message is simply not there yet.

@PombeirP could you answer that?

**Comment by pedropombeiro** [comment]
The PN currently is not tied to fetching Whisper messages, there's a long-standing GHI for that: https://github.com/status-im/status-react/issues/3451

So when you receive a PN and click on it, that will open the app and only then fetching of messages is triggered (as usual). I just did a few tests on my side and here's what I saw:

Test consisted of sending 1:1 message from account A (desktop) to account B (Android).

Case 1: Android app is unlocked and running in the background
1. A sends message to B
1. B sees PN and clicks on it
1. B's app opens the correct 1:1 chat and message is there 

Case 2: Android app is not running
1. A sends message to B
1. B sees PN and clicks on it
1. B's app opens asking for password, user enters it
1. B's app fetches the message but stays in the main screen (logic to navigate to chat got lost, seems like a bug)

**Comment by adambabik** [comment]
> B's app opens the correct 1:1 chat and message is there

So we do tie a push notification to the chat. I am not sure I ever had it working on iOS... How do we do that? Via a topic?

**Comment by pedropombeiro** [comment]
> So we do tie a push notification to the chat

In that sense, yes. What I meant is that the fact that a PN arrives currently doesn't trigger background fetching of Whisper messages.

Just looked at the code and this is what is sent to status-go:

```clojure
    {:send-notification {:message (js/JSON.stringify #js {:from (accounts.db/current-public-key cofx)
                                                          :to   (get-in cofx [:db :current-chat-id])})
                         :payload {:title (i18n/label :notifications-new-message-title)
                                   :body  (i18n/label :notifications-new-message-body)
                                   :sound notifications/sound-name}
                         :tokens  [fcm-token]}}))
```
https://github.com/status-im/status-react/blob/develop/src/status_im/chat/models/message.cljs#L304

So basically the sender pubkey and the chat ID is sent as JSON payload on the push notification.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by yenda** [comment]
@PombeirP are you looking into that one or should I take it?

**Comment by pedropombeiro** [comment]
You can take it, @yenda

**Comment by oskarth** [comment]
@yenda @PombeirP any update on this one?

**Comment by pedropombeiro** [comment]
@oskarth I've recently merged https://github.com/status-im/status-react/pull/7389 which could be a cause in some situations where you have bad connectivity, but not sure if this completely fixes things (i.e. if it is the only scenario where this can happen).

**Comment by oskarth** [comment]
@annadanchenko thoughts?

**Comment by mandrigin** [comment]
I don't think we will fix it 100% while we are using whisper and while we are using a separate channel for push notifications (like Firebase).

PNs are guaranteed to arrive, Whisper messages don't provide guarantees like that.
Maybe data sync layer can help there (if we'll be able to request this message specifically from the network), but I'm not sure how to handle this exact issue.

**Comment by churik** [comment]
Not relevant for Status v1.0.1
