### ISSUE TITLE
Scrolling not working in WKWebview

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#672]
User reported not being able to scroll down in Etherisc DApp.
https://instabug.com/applications/status/beta/bugs/68

<img src="https://s3.amazonaws.com/instabug-pro/states/files/44640736/screenshots/c32fa523cc7be55a50d83586d07c445c_original.jpg?1483718177" width="320">

**Comment by rasom** [comment]
@annadanchenko can we reproduce this?

**Comment by annadanchenko** [comment]
@rasom Yes, I can reproduce only on iOS non-working horizontal scroll on this page with today's develop build. Vertical scroll works fine. In Android both scrolls are fine.

**Comment by annadanchenko** [comment]
can't reproduce anymore (real iphone 7 plus and real iphone 5s) build 0.9.11d372: Horizontal scrolling works ok
![img_3164](https://user-images.githubusercontent.com/6584810/32963427-2daea92c-cbd0-11e7-91ed-a025cc3b4f64.jpg)
