### ISSUE TITLE
self-messaging (i.e. notepad)

### ISSUE THREAD

**Issue by rcullito** [status-im/status-react#6723]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I would like to able to send messages to myself. This would be nice to have for its own sake, but more pressing is the need to send messages across devices without having to leave the status app. 

*Type*: <Feature>

Either this message would be indistinguishable from messaging other clients, or if it's not too oppressive perhaps a gentle reminder that the user is messaging themself. 

#### Expected behavior
when pasting a contact key into the "add new chat", it is possible to open up a chat window with one participant

#### Actual behavior
at the text input level, a message in red states that this behavior is explicitly prohibited 

### Reproduction
Add your own contact key into a new chat window

**Comment by chadyj** [comment]
This can be achieved today with a public chat for #rcullitosecretchat (but messages will be public if the channel name is found)

**Comment by rcullito** [comment]
ah nice. thanks for the additional context @chadyj
