### ISSUE TITLE
Only show desktop PNs for messages that were sent after signing in to the account

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#6724]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I only want to receive PNs for messages that have arrived after I signed in to the account so that I'm not submerged by an endless stream of PNs.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently we're showing PNs for any message that was sent in the last 24 hours. This can create an endless stream of PNs if we're part of busy chat rooms. The user doesn't really need to see those notifications, since once he logs in he'll see the old messages being retrieved. Taking that into account, he'll only need PNs for messages that are newer than that event.

**Comment by yenda** [comment]
This can be achieved by only triggering a notification if the timestamp of the message is older than login time for the account

**Comment by churik** [comment]
Still relevant
