### ISSUE TITLE
Support Windows 7

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#6726]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to run Status on Windows 7 so that I can use my current OS.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The Status app should support Windows 7.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

The app starts normally as in Windows 7.

#### Actual behavior
[comment]: # (Describe what actually happened.)

The Status app currently hangs when being started on Windows 7, it's not obvious what it is doing and whether this is related to ubuntu_server.exe or Status.exe.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on Windows 7

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Compile with `CFLAGS=-D_WIN32_WINNT=0x0601 -DWINVER=0x0601` (did initial attempt adding to `desktop/Toolchain-Ubuntu-mingw64.cmake` but that didn't fix things by itself)
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.0.1
[comment]: # (Android or iOS.)
* Operating System: Windows

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
No logs are generated.

**Comment by sergeevabc** [comment]
Thanks for creating this issue, Pedro.
