### ISSUE TITLE
Add notification support for Windows

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#6728]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see notifications on Windows so that I know when a message arrives.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently there's a build error when enabling the SnoreToast plugin (`-DBUILD_snoretoast=ON`):

```
/home/pedro/src/github.com/status-im/status-react/desktop/modules/react-native-desktop-notification/desktop/SnoreNotify_ep-prefix/src/SnoreNotify_ep-build/src/plugins/backends/snoretoast/libsnore_backend_windowstoast_autogen/EWIEGA46WW/moc_snoretoast.cpp: In function 'QObject* qt_plugin_instance_WindowsToast()':
/home/pedro/src/github.com/status-im/status-react/desktop/modules/react-native-desktop-notification/desktop/SnoreNotify_ep-prefix/src/SnoreNotify_ep-build/src/plugins/backends/snoretoast/libsnore_backend_windowstoast_autogen/EWIEGA46WW/moc_snoretoast.cpp:236:35: error: invalid new-expression of abstract class type 'SnorePlugin::WindowsToast'
 QT_MOC_EXPORT_PLUGIN(SnorePlugin::WindowsToast, WindowsToast)
```

**Comment by pedropombeiro** [comment]
Added missing method in https://github.com/status-im/snorenotify/commit/9d54904e4896ab6c3c3a52f97381e5948b455970.

We need to add NSIS script as mentioned https://techbase.kde.org/Projects/Snorenotify/Windows-Toast-Notification once the installer PR lands.

<blockquote><img src="https://www.kde.org/aether/media/192x192.png" width="48" align="right"><div><strong><a href="https://techbase.kde.org/Projects/Snorenotify/Windows-Toast-Notification">Projects/Snorenotify/Windows-Toast-Notification - KDE TechBase</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
Added both the trayicon and windowstoast plugins but the log still shows an empty list of notification plugins:

```
08:15:29.116 - D - [RCTNotification] - DesktopNotification::DesktopNotification List of all loaded Snore plugins: ()
08:15:29.116 - D - [RCTNotification] - DesktopNotification::DesktopNotification Current notification backend: ""
```

Any ideas @MaxRis?

**Comment by maxhora** [comment]
@PombeirP have you added import of static plugins for Windows platform?
It should happen on early stage of app running.

For MacOS it was working out of the box by [including generated header file ](https://github.com/status-im/status-react/blob/develop/modules/react-native-desktop-notification/desktop/desktopnotification.cpp#L19). You can try similar for Windows as well.

But on Linux generated header file had some issues and hardcoded version of similar generated header file [is there](https://github.com/status-im/status-react/blob/develop/modules/react-native-desktop-notification/desktop/desktopnotification.cpp#L27)

**Comment by pedropombeiro** [comment]
@MaxRis yeah, that header wasn't being included, could very well be that. When including it on Windows though I get this error (seems like `src/libsnore/plugins/settingsplugin.cpp` isn't being built but is being referenced somewhere):

```
../modules/react-native-desktop-notification/desktop/SnoreNotify_ep-prefix/src/SnoreNotify_ep/lib/libsnore_settings_backend_snore.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.text+0x101): undefined reference to `Snore::SettingsPlugin::SettingsPlugin()'
../modules/react-native-desktop-notification/desktop/SnoreNotify_ep-prefix/src/SnoreNotify_ep/lib/libsnore_settings_backend_snore.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.text$_ZN11SnorePlugin19SnoreSettingsPluginD1Ev[_ZN11SnorePlugin19SnoreSettingsPluginD1Ev]+0xb): undefined reference to `Snore::SettingsPlugin::~SettingsPlugin()'
../modules/react-native-desktop-notification/desktop/SnoreNotify_ep-prefix/src/SnoreNotify_ep/lib/libsnore_settings_backend_snore.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.text$_ZN11SnorePlugin19SnoreSettingsPluginD0Ev[_ZN11SnorePlugin19SnoreSettingsPluginD0Ev]+0x13): undefined reference to `Snore::SettingsPlugin::~SettingsPlugin()'
collect2: error: ld returned 1 exit status
```

UPDATE: I'm now trying to do the same as Linux, that's probably better.

**Comment by pedropombeiro** [comment]
Yup, much better now:

```
10:18:51.321 - D - [RCTNotification] - DesktopNotification::DesktopNotification List of all loaded Snore plugins: ("Snore", "Windows Toast")
10:18:51.321 - D - [RCTNotification] - DesktopNotification::DesktopNotification Current notification backend: "Windows Toast"
```
