### ISSUE TITLE
Emojis are cropped

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#673]
Opening the available emojis, they are clipped on the right, and the bottom.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/142
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/58

<img src="https://s3.amazonaws.com/instabug-pro/states/files/44638667/screenshots/b05fe1d4a3e4ac9d132182059a9fc3e0_original.jpg?1483717259" width="320">

**Comment by jarradh** [comment]
Upstream bug in the emoji picker component we're using.

**Comment by jarradh** [comment]
https://github.com/yonahforst/react-native-emoji-picker
