### ISSUE TITLE
Restart macOS signing on segmentation fault 

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6737]
Every now and then signing script for macOS crashes with segmentation fault. Since it is a known issue, I think it is safe to restart this process at least once or twice more when this segmentation fault happens.

The error message is like that

```
Warning: unable to build chain to self-signed root for signer "Developer ID Application: STATUS HOLDINGS PTE. LTD. (DTX7Z4U3YA)"../scripts/sign-macos-pkg.sh: line 105: 66333 Segmentation fault: 11  codesign --sign "$DEV_ID" --force --verbose=4 "$OBJECT"
```

**Comment by churik** [comment]
Irrelevant as I could understand
