### ISSUE TITLE
Requesting a second confirmation code not intuitive

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#674]
Requesting a second confirmation code (if the first expires) should be made more intuitive.

_"I had no cell reception when I requested my confirmation code, it was expired by the time I received it. There is no immediately obvious way to request a new code."_

<img src="https://s3.amazonaws.com/instabug-pro/states/files/44625503/screenshots/7028fd18df3563c6b9caa0f3f9cc215a_original.jpg?1483711087" width="320">

**Comment by Jas0n-F** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/168

**Comment by annadanchenko** [comment]
there is no phone command and confirmation-code command anymore
