### ISSUE TITLE
Mobile FAQ link is broken

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6740]
The mobile app has a link to the FAQ from Profile > Need Help? > Frequently Asked Questions.

The FAQ is no longer shown.

It links to https://wiki.status.im/Frequently_Asked_Questions which now redirects to the docs site tech documentation page.

Solution:

Change the link from `https://wiki.status.im/Frequently_Asked_Questions ` to `https://status.im/docs/FAQs.html` in the app.

Needs to be fixed for the 0.9.31 release.

**Comment by andytudhope** [comment]
@chadyj the FAQs are here: https://status.im/docs/FAQs.html

Though not the most mobile friendly because we kinda got stalled on the design for the sidebar and I have yet to discuss that with @andmironov or @NistorCristian... Anyway, we can at least just update the link.

**Comment by chadyj** [comment]
Thanks Andy.

So let's change the link from `https://wiki.status.im/Frequently_Asked_Questions ` to `https://status.im/docs/FAQs.html` in the app.
