### ISSUE TITLE
Keyword notifications in chat

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6741]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a chat user, I want to be notified when keywords are mentioned so that I can better follow relevant conversations.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

We have previously discussed mentions, but it is complicated by auto-suggest, random name, display name, and active chats.  It is also limited because a user can only be notified by mentions of their display name.

A more flexible approach could be setting up notifications for _any_ keyword, such as _bob_, _clojure_, _desktopteam_, or _security._

The notifications could be marked by a change in message colour, and perhaps a special notifications UI.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Solution

https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=488%3A17

cc @errorists @yenda

**Comment by EugeOrtiz** [comment]
@chadyj @errorists  How do you imagine keywords working in relationship with notifications from 1:1 chats? E.g. If my keyword is "cake", I won't receive any PN from a contact unless she mentions "cake" in the conversation? Will KWs work as a filter for current PNs? What about PNs for replies?

**Comment by chadyj** [comment]
They are complimentary and can co-exist  :-)

Eg notifications will be shown in these scenarios:
- 1-1 message received
- "cake" mentioned in #status 
- 1-1 message received mentioning "cake"

Desktop needs some notification improvements because currently all messages trigger the notification.  We should fix this while doing notifications https://github.com/status-im/status-react/issues/6445

**Comment by chadyj** [comment]
@yenda How would notifications work on **mobile**? The message needs to be downloaded locally before the notification can fire.

So the mobile experience would be no notifications until the user opens Status. Then status downloads the messages and fires any notifications

Perhaps we need a new in-app notification?  Or can we get local notifications showing when the app is in the foreground?

Or @errorists can we alter the chat list so users know there are notifications waiting in the chat?

**Comment by errorists** [comment]
Mobile designs -> [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=374%3A1)
I've added a design there for in-app notifications, in case we need them.

Regarding the chat list, we've been discussing it previously if it made sense to only show the badge and update the number on channels when the message is directed at you, so it's in a way PN worthy. So only things like keywords, mentions, replies to you, in the future also threads, would update the number, with regular messages only showing blank new activity, similar to how the dock badge on desktop works now.
I'm also starting to wonder if it makes sense to plan for a dedicated 'New Activity' view that would track every PN, every thing requiring your attention or happening while you were gone, but this is another topic entirely.

**Comment by errorists** [comment]
I'm wondering if we can't reliably push keyword notifications on mobile, does the entire feature make sense there at all? Imho, It's either working and reliable all the time or not there at all, and not with exceptions *works only when you're inside the app.

**Comment by chadyj** [comment]
> I'm wondering if we can't reliably push keyword notifications on mobile, does the entire feature make sense there at all? Imho, It's either working and reliable all the time or not there at all, and not with exceptions *works only when you're inside the app.

The use case is 100% needed. But perhaps it could be solved better on mobile through the discussed "notifications" UI?  

I'd also appreciated getting alerted asap if I'm using the app and someone ping me somewhere. Let's solve this use case.
