### ISSUE TITLE
No successful release build job runs in Jenkins for release/0.9.31 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6743]
***Summary***: All job runs (4 of them by this moment) from https://ci.status.im/job/status-react/job/release/job/release%252F0.9.31/ job failed to succeed. 

If i'm correct it's because of mobile-android trying to push Slack message. 

#### Expected behavior
Successful build with iOS, Android, Android e2e artefacts in https://ci.status.im/job/status-react/job/release/job/release%252F0.9.31/

#### Actual behavior
Failing builds with iOS, Android, Android e2e artefacts in https://ci.status.im/job/status-react/job/release/job/release%252F0.9.31/

#### Logs
E.g. https://ci.status.im/job/status-react/job/combined/job/mobile-android/7435/console

```
15:28:21 [13:28:20]: To update all plugins, just run
15:28:21 [13:28:20]: $ bundle exec fastlane update_plugins
15:28:21 
15:28:21 [13:28:20]: fastlane finished with errors
15:28:21 
15:28:21 [!] Error pushing Slack message, maybe the integration has no permission to post on this channel? Try removing the channel parameter in your Fastfile, this is usually caused by a misspelled or changed group/channel name or an expired SLACK_URL
15:28:21 
```

<blockquote><img src="/static/60651f1e/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.31/">release/0.9.31 [status-react » release] [Jenkins]</a></strong></div></blockquote>
<blockquote><img src="/static/60651f1e/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-android/7435/console">status-react » combined » mobile-android #7435 Console [Jenkins]</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@jakubgs any update? We need to have it fixed as we are releasing soon.

**Comment by cammellos** [comment]
taking a look at this, removed slack notifications and kicked the build

**Comment by jakubgs** [comment]
Sorry, I was OoO on Friday.

**Comment by annadanchenko** [comment]
for 0.9.32 there are successful builds, so not a blocker for release anymore (removing "release" label)

**Comment by jakubgs** [comment]
Wasn't this already resolved by @cammellos ? I think this can be closed.
