### ISSUE TITLE
After creating a group chat, chat icons are not displayed

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6747]
## Description
*Type*: Bug
After creating a group chat, the chat icon is not shown in chat list (left panel) and chat header (top).

## Expected behavior
An icon with the first letter of the group name is shown both in chat list and chat header:

<img width="890" alt="captura de pantalla 2018-11-15 a la s 4 42 48 p m" src="https://user-images.githubusercontent.com/37297779/48577285-8d4c0080-e8f5-11e8-9ac2-0d45615d2ca6.png">

[Designs on Figma](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=230%3A16017)
[Icon design specs](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=309%3A11923)

## Actual behavior
Chat list:
<img width="1021" alt="captura de pantalla 2018-11-15 a la s 4 37 34 p m" src="https://user-images.githubusercontent.com/37297779/48577464-fe8bb380-e8f5-11e8-9e7f-ed8db8bdf072.png">

Chat header:
<img width="774" alt="captura de pantalla 2018-11-15 a la s 4 46 05 p m" src="https://user-images.githubusercontent.com/37297779/48577542-29760780-e8f6-11e8-955c-08fc1e5bdb52.png">

### Reproduction
- Open Status Desktop
- Create a group chat

### Solution
- [ ] Add group icon to chat list
- [ ] Add group icon to chat header

### Additional Information
Wanna improve the group chat experience? Go to this 👉 [issue](https://github.com/status-im/status-react/issues/6607) 👈

**Comment by churik** [comment]
Irrelevant in terms of #7551
