### ISSUE TITLE
Back button doesn't work on recover screen

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#675]
Back button in top left corner does not return users to login screen.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/112
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/150
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/112

<img src="https://s3.amazonaws.com/instabug-pro/states/files/44572205/screenshots/29a2b484631508d4c9ed91af7b92dbde_original.jpg?1483677500" width="320">

**Comment by jarradh** [comment]
Back button is fine, in this case it's caused by #652

**Comment by flexsurfer** [comment]
fixed recover button by https://github.com/status-im/status-react/pull/726
