### ISSUE TITLE
Add DApps for 0.9.33

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6760]
This issue will be updated with additional DApps.

**slow.trade**
URL: https://slow.trade/
[Logo](https://drive.google.com/file/d/1-ayAOt1av8fI2OKrdJJyHaG7vcIxCJJc/view?usp=sharing)
Category: Exchanges
Order: bottom of list
Description: Trade fairly priced crypto assets on the first platform built with the DutchX protocol.

**3Box**
URL: https://3box.io
[Logo](https://drive.google.com/file/d/1sjwyqAt-Y3ExCgrcnMN1I0G_rIpfc1ez/view)
Category: Utilities
Order: top of list
Description: Create and manage your Ethereum Profile.

**Comment by chadyj** [comment]
Still needed in 0.9.32?

**Comment by rachelhamlin** [comment]
@chadyj no - title is now a misnomer, I'll update it for the next release.
