### ISSUE TITLE
Align timestamp formats in chat list

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#6763]
## User Story
As a user, I want to see a consistent timestamp on chats between my devices.

## Description
Chat timestamps have different formats on mobile and desktop.

## Expected behavior
Same date/time format for any device.

## Actual behavior
![img_7484](https://user-images.githubusercontent.com/37297779/48645314-16ca0400-e9c4-11e8-8071-61a05cc5f1c0.PNG)
<img width="341" alt="captura de pantalla 2018-11-16 a la s 5 18 20 p m" src="https://user-images.githubusercontent.com/37297779/48645319-19c4f480-e9c4-11e8-9159-eab58cbf3a07.png">

### Today’s time
For messages within the current day, use uppercase AM or PM, without periods. Format **HH:MM AM/PM**
Examples:
* 02:00 AM
* 10:30 PM

### This week
Within the current week, use the day of the week until last Sunday. If the last message was yesterday, we show “**Yesterday**”.
Examples:
* Yesterday
* Wednesday
* Monday
* Sunday

### Any other date, this year
When last message was before this week, and it’s within the current calendar year, we show the date without periods. Format **DD ShortMonth**
ShortMonth: Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec.
Examples:
* 16 Jan 
* 01 Feb 

### Any other date, before this year
When last message was before the current calendar year, we show the date with the following format without periods **DD ShortMonth YYYY**
Examples:
* 16 Jan 2017
* 01 Feb 2016

Examples:
![chat list - dates format - prposal 3 - winner _](https://user-images.githubusercontent.com/37297779/48645455-83dd9980-e9c4-11e8-9357-9efeb84133de.png)
![home tab](https://user-images.githubusercontent.com/37297779/48645459-863ff380-e9c4-11e8-9232-c22edfa75df7.png)

[Designs in Figma](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop-Chat?node-id=297%3A469)

**Comment by churik** [comment]
Irrelevant in terms of #7551
