### ISSUE TITLE
"Image not recognised" warning error when opening latest nightly .dmg file

### ISSUE THREAD

**Issue by ceripower** [status-im/status-react#6767]
# Problem

I downloaded the latest nightly, and when clicking the .dmg to open it, I get a warning message saying `The following disk images couldn't be opened: StatusIm 181119-0259 Image not recognised`.

The error message stops the .dmg file from being opened.

<img width="372" alt="screen shot 2018-11-19 at 10 45 32" src="https://user-images.githubusercontent.com/25318254/48695622-448f9280-ebe8-11e8-9272-65fa2f2a3978.png">

**Comment by churik** [comment]
@ceripower would you mind to share details of your OS?

**Comment by ceripower** [comment]
Hi @churik! MacOS High Sierra version 10.13.3, let me know if you need anything else!

**Comment by churik** [comment]
cannot reproduce on Mac OSx Mojave 10.14.1

**Comment by hetvart** [comment]
could not reproduce on macOS High Sierra 10.13.6

**Comment by chadyj** [comment]
@rachelhamlin had this too last week.

I couldn't repro on 10.14.1

@gnl Have you seen anything like this?

**Comment by churik** [comment]
Not reproducible
