### ISSUE TITLE
No tokens shown on main Wallet screen after upgrade 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#6768]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: No tokens and collectibles are shown on main Wallet screen in Assets section after upgrade (user had them shown before upgrade)

Note that if pull down to refresh then tokens are loaded but it's not obvious to the user as ETH was loaded by default

before:
![img_2491](https://user-images.githubusercontent.com/6584810/48702153-799fe300-ebf0-11e8-9098-0de0b999fb41.jpg)

after:
![img_2493](https://user-images.githubusercontent.com/6584810/48702165-86243b80-ebf0-11e8-8e64-cc1e468e4a8a.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After upgrade tokens and collectibles are shown in main wallet screen (if user had them)
#### Actual behavior
[comment]: # (Describe what actually happened.)
only ETH is shown on main wallet screen, no tokens and collectibles
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install 0.9.30 (11274) from TestFlight
- Recover account that has tokens (and collectibles)
- Open wallet to see tokens are shown on main screen
- Close app
- upgrade to 0.9.31
- open wallet to check what's shown on main screen

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: upgrade from 0.9.30 to 0.9.31
* Operating System: found on iOS

**Comment by lukaszfryc** [comment]
@mandrigin @cammellos or maybe @rasom, could you fix it?

**Comment by annadanchenko** [comment]
or @goranjovic ?

**Comment by PhilipandWu** [comment]
was just going to make a GH issue as i'm facing this problem, but i see it's here, awesome!

Just to add more info, the SNT assets sometimes do show up back again in the asset list according to another status user after reloading the app. Hasn't happened to me yet.

**Comment by annadanchenko** [comment]
@PhilipandWu thanks for the feedback! To workaround the issue: on the main wallet screen (where SNT or other assets are no longer shown), tap and pull down in wallet
