### ISSUE TITLE
Add ability to copy passphrase

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#677]
Many users have asked for a way to copy their passphrase.
I think we can come up wit a more intuitive way than just copy pasting the message.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/63

Similar to: https://github.com/status-im/status-react/issues/639.

**Comment by jarradh** [comment]
Ideally we had a blocking mechanism requiring the user to enter a sampling of the pass phrase ie "4th word", "6th word", "9th word".

**Comment by jarradh** [comment]
Maybe Pull Request #707 is enough

**Comment by alwx** [comment]
Already in `develop`.
