### ISSUE TITLE
Clicking on the deep link when app is closed simply opens the app

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6795]
Type: **Bug**

Summary: When app is closed, and user clicks on a deep link, after he logs in the expected profile/chat is not opened.

**Expected behavior**

After user logs in, the expected profile/chat should open

**Actual behavior**

After user logs in, the expected profile/chat is not opened

**Steps to reproduce:**

1. Make sure app is closed
2. Open a deep link, ex.
https://get.status.im/user/0x044b76588cbe06b625e3c8885bd3e2207f62f8b61bf09aa4dfc4237d3246f97c3bcd2049df6d897e74a6ffd94c0f1f4c4cc0ca00762d6f0dea29f6b82105cf72e1
https://get.status.im/chat/public/status-protocol
3. Login using an existing account

**Additional information:**

Status version: desktop nightly build 11/20/18
Operating System: MacOS 10.13.4

<blockquote><div><strong><a href="https://get.status.im/user/0x044b76588cbe06b625e3c8885bd3e2207f62f8b61bf09aa4dfc4237d3246f97c3bcd2049df6d897e74a6ffd94c0f1f4c4cc0ca00762d6f0dea29f6b82105cf72e1">View user 0x044b76588cbe06b625e3c8885bd3e2207f62f8b61bf09aa4dfc4237d3246f97c3bcd2049df6d897e74a6ffd94c0f1f4c4cc0ca00762d6f0dea29f6b82105cf72e1 profile in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/chat/public/status-protocol">Join the public chat: #status-protocol in Status</a></strong></div></blockquote>

**Comment by churik** [comment]
I'm not sure it is an issue.
@dmitryn can you confirm what is expected result in this case?

**Comment by churik** [comment]
Still relevant
