### ISSUE TITLE
Deep links don't work on Linux and Windows

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6796]
Type: **Bug**

Summary: 
- On Linux, when application was marked as 'executable', clicking on a deep link does not lead to triggering the app;
- On Windows after installation at attempt to open any valid link (i.e. `https://get.status.im/user/0x0472b0f0f58ef9f3275874bb72ab1db784486ec7bd68cda8f658410fbbf1427a9b384bc921299df1974f1786a83b6d515c2fe413273f593e5ecbd794dabd025292`) in Microsoft Edge I got suggestion look for app in the store:
![app_w](https://user-images.githubusercontent.com/4557972/48848764-15725000-eda5-11e8-9ee5-9a3339b193df.png) and when open app in Chrome nothing happens; neither suggestions nor errors in console at attempto to open it in latest Chrome.

**Expected behaviour:**

After clicking on a deep link when app is closed: the app is opened, after user logs in he is redirected to the expected page - profile/chat
After clicking on a deep link when app is opened and user is logged in: the app is triggered, the expected page is opened - profile/chat

**Actual behaviour:**

*Linux:*
When app is opened/closed: The app is not triggered, all I see is 'The address was not understood' error in the browser

*Windows:*
nothing happens in Chrome; suggestion to look for the appropriate app in Edge browser.

**Steps to reproduce:**

*Linux:*
1. Download the app for Linux
2. In properties, mark it as 'Allow executing file as program'
3. In the browser, open a deep link URL and click 'Open in Status'

*Windows:*

1. Download and install the app for Windows
2. Launch it and create new account
3. Launch any browser and open valid deep link

**Additional information:**

Status version: desktop nightly build 11/20/18
Operating System: Linux 2.6 (64-bit) emulated

**Comment by churik** [comment]
Relevant
