### ISSUE TITLE
[Pairing] User pictures for contacts are not synced across devices

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6798]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: as the continuation of #6697. Currently, when you add somebody with custom picture to your contact list on one device, you still will see default picture in another device after sync.

#### Expected behavior
contact A is added with custom picture

#### Actual behavior
contact A is added with default picture

### Reproduction
*Prerequisites:* same account is using on Device1 and Device2, sync is enabled between 2 devices (instructions are here https://ethstatus.testrail.net/index.php?/cases/view/5680)

- Open Status on Device1
- Add to contacts someone with custom picture (contact A)
- Log in to Device2
- Tap on + 
- Tap on Start new chat

### Additional Information
* Status version: nightly 20/11/2018
* Operating System: all

<blockquote><img src="https://static.testrail.io/5.6.0.3841/images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/5680">Login - TestRail</a></strong></div></blockquote>

**Comment by chadyj** [comment]
PR here https://github.com/status-im/status-react/pull/6714

**Comment by churik** [comment]
@chadyj it is another one. I'm talking about contact list and pictures of other users in contact list.

**Comment by churik** [comment]
Still reproducible

**Comment by churik** [comment]
Not relevant for Status v1.0.1
