### ISSUE TITLE
[Pairing] Messages are shown as new on other devices even when they were read on one device

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6799]
### Description

*Type*: Feature

### User Story

As a user, I don't want to see unread messages once they were read on another device.

### Description

*Summary*: as the continuation of #6697. 
Currently, when you read messages in 1-1, group or public chat on one device, you still will see these messages as new in another device after sync.

#### Expected behavior
messages are read

#### Actual behavior
messages are new

### Reproduction
*Prerequisites:* same account is using on Device1 and Device2, sync is enabled between 2 devices (instructions are here https://ethstatus.testrail.net/index.php?/cases/view/5680).
There are new messages in 1-1, group and public chats from other users.

- Open Status on Device1
- Read all new messages on Device1.
- Log in to Device2
- Check chat list for new messages

### Additional Information
* Status version: nightly 20/11/2018
* Operating System: all

**Comment by yenda** [comment]
@cammellos could this be added to the stuff that is synced between devices?

**Comment by churik** [comment]
still relevant

**Comment by churik** [comment]
not relevant anymore
