### ISSUE TITLE
[Pairing] Sync public channels across devices

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6801]
### Description

*Type*: Feature

### User Story

As a user, I want to see my public channels across devices, so that I don't need to join them several times.

### Description

*Summary*: as the continuation of #6697. 
Currently, when you join any public chat on one device, you still will need to join it on another device regardless sync is enabled or not.

#### Expected behavior
can see new public chat

#### Actual behavior
no new public chat was added

### Reproduction
*Prerequisites:* the same account is using on Device1 and Device2, sync is enabled between 2 devices (instructions are here https://ethstatus.testrail.net/index.php?/cases/view/5680).

- Open Status on Device1
- Join any public chat on Device1.
- Log in to Device2
- Check chat list

### Additional Information
* Status version: nightly 20/11/2018
* Operating System: all

<blockquote><img src="https://static.testrail.io/5.6.0.3841/images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/5680">Login - TestRail</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@churik this one has been implemented, should we close it?

**Comment by churik** [comment]
I think so
