### ISSUE TITLE
[Pairing] Sync deleting chats \ clearing history across devices

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6803]
### Description

*Type*: Feature

### User Story

As a user, I want to delete my chat only once on one device instead of deleting it on several devices.

### Description

*Summary*: as the continuation of #6697. 
Currently, when you delete any chat or clearing chat history on one device, you still will need to repeat it on another device regardless sync is enabled or not.

#### Expected behavior
Chat A is deleted;
History for chat B is empty;

#### Actual behavior
chats are not changed

### Reproduction
*Prerequisites:* the same account is using on Device1 and Device2, sync is enabled between 2 devices (instructions are here https://ethstatus.testrail.net/index.php?/cases/view/5680).
Chats A and B (1-1 or group) are active on both devices and contain some history.

- Open Status on Device1
- Delete Chat A
- Clear history for Chat B
- Log in to Device2
- Check chat A and B

### Additional Information
* Status version: nightly 20/11/2018
* Operating System: all

<blockquote><img src="https://static.testrail.io/5.6.0.3841/images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/5680">Login - TestRail</a></strong></div></blockquote>

**Comment by churik** [comment]
Not stale

**Comment by cammellos** [comment]
@churik is this still valid or it's been fixed?
Thanks!

**Comment by churik** [comment]
done already, thanks for spotting!
