### ISSUE TITLE
Are the design files also open source?

### ISSUE THREAD

**Issue by JustinDrake** [status-im/status-react#681]
I love the Status design. Are the design files (e.g. PSD files) public?

**Comment by jarradh** [comment]
They will be but aren't at the moment,  Sketch files will be provided, when our designer is back from holiday.

We also use Zeplin to communicate designs to developers but they are not very useful for open source so we need to find alternative

**Comment by Shrinks99** [comment]
The "Check out our designs" link in the GitHub readme currently doesn't go anywhere!  Might want to fix that!  :) @jarradh @andmironov
