### ISSUE TITLE
Public chats are missing messages on different devices

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-react#6814]
# Problem

Public chats are missing messages, that are not recovered even after multiple history requests.

I suspect that the problem is in the way we query history from mail servers. As I understood from the discussion in Status.im we do it in a following way: If at first I query envelopes from 13:10:11 till 13:15:17 and query was successful, next time i will start my query from 13:15:17 till some timestamp. The problem is that mail server can receive a message with timestamp lower than 13:15:17 after we sent back a history for 1st query.

# Implementation

Mail server uses (Expiry timestamp - TTL) as a timestamp for the message. Additionally there is small time window that is tolerated by any whisper node, afair it is 10s. I would suggest to adjust query with a common TTL and mentioned whisper window. 

It will increase rate of duplicates, but we will stop missing messages from mail server.

# Acceptance Criteria

Messages that are received by mail server after history was queried should be sent to the user on a subsequent queries.

link: https://github.com/status-im/status-react/issues/6757

**Comment by mandrigin** [comment]
That is a great find!
