### ISSUE TITLE
Make username bold on profile screen for desktop

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6817]
User story:

As a user, I want usernames on desktop to be highlighted in bold, just like on mobile. For user's profile, have the default name be in grey font like for mobile

Type: **Feature request**

Summary: Currently, on mobile, usernames are displayed in bold on profile screen. 
On desktop they are not.

**Expected behaviour**

Usernames to be displayed the same style/font as on mobile. Please check the screenshots attached.

**Actual behaviour**

Username is of a regular font

**Screenshots:**
**Desktop:**
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/43638377/48788778-34fd7000-ecf4-11e8-8ac0-9386b8fc0f28.png">
**Mobile:**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/43638377/48790627-7859dd80-ecf8-11e8-8024-099188b1295f.png">
**Desktop:**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/43638377/48788800-3fb80500-ecf4-11e8-955b-3f85b093ff14.png">
**Mobile:**
<img width="442" alt="image" src="https://user-images.githubusercontent.com/43638377/48790612-6f690c00-ecf8-11e8-9298-d234029ab8d4.png">

**Comment by churik** [comment]
Irrelevant in terms of #7551
