### ISSUE TITLE
Username and chat name are not formatted correct for group chat commentary messages

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6818]
Type: **Bug**

Summary: It looks like for group chats, username and chat name should be displayed in bold,( * * used), but it's not working. 

**Expected behavior:**

Username and chat name are displayed in bold for commentary messages

**Actual behavior:**

Username and chat name are displayed in regular font for commentary messages, but framed with asterisks

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/43638377/48788848-5cecd380-ecf4-11e8-938a-c7e7f352b388.png">

**Reproduction**:

1. Open Status
2. Create a group chat with 2 people
3. Check how commentary messages are displayed for the new group chat

**Additional Information:**

Status version: nightly 11/20/2018
Operating System: Linux 2.6 emulated, MacOS 10.13.4

**Comment by churik** [comment]
Relevant
