### ISSUE TITLE
Support web3 sync methods

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#682]
In webview we do not support sync methods, this was a tradeoff in support https:// vs sync methods in our current web3 Provider.

A hack work around for DApp developers is to use http:// and use a HttpProvider with web3 that connects directly to 127.0.0.1:8545

**Comment by jarradh** [comment]
We could partially solve this, if the user is not on `https://` we can support sync by modifying `StatusHttpProvider` in `resources/web3_init.js` `send` method to fall back to the default `HttpProvider` send method.

**Comment by mathvdh** [comment]
I was having a look into this.
@jarradh do you mean something like this :
```
var StatusHttpProvider = function (host, timeout) {
    this.host = host || 'http://localhost:8545';
    this.timeout = timeout || 0;
    this.defaultHttpProvider = new web3.providers.HttpProvider(host, timeout);
};

StatusHttpProvider.prototype.send = function (payload) {
    if (this.host.indexOf('https') != -1) {
        return this.defaultHttpProvider.send(payload)
    } else {
        throw new Error('You tried to send "'+ payload.method +'" synchronously over HTTPS. Synchronous requests are only supported over HTTP, sorry.');
    }
};
```
Or you mean copying the code from the send method in the default httpprovider ?
Not sure I understand correctly ...
(Also I'm not saying this is a clean solution, it could be improved obviously, but it's more to see if it's what you mean ?)

**Comment by jarradh** [comment]
@mathvdh yes, something like that for now, even though it's ugly it would increase our compatibility "surface area"

**Comment by mathvdh** [comment]
Well, after reading it again and the sources of web3_init , I have the impression it doesn't make sense... 

Because in there we always connect using http
See : `web3 = new Web3(new StatusHttpProvider("http://localhost:8545"));`
So I guess this is not where I should look if we are on https or not ... or there is something I don't understand ...

**Comment by jarradh** [comment]
sorry I thought your example wasn't complete but you understood the gist of it. 

Look at `StatusHttpProvider` please. You will see it communicates to status though an object.

**Comment by mathvdh** [comment]
@jarradh : Yes I'm digging a bit more into it .. thanks
