### ISSUE TITLE
Add Alchemy RPC Providers for Ropsten, Rinkeby and Mainnet

### ISSUE THREAD

**Issue by andytudhope** [status-im/status-react#6822]
# Problem

Relying only on Infura for RPC connections while we finish off our work on [ULC](https://status.im/research/ulc_in_details.html) is obviously not great. Recently, we implemented alternative RPC endpoints for POA Network sidechains, which was awesome - but they too were going over Infura. @corpetty and myself had a chat with the people from Alchemy, and they're keen to let us plug into their infrastructure (which they've been using to manage a successful hedge fund, among other things).

In my view, we should not be hasty to move away from Infura, but being able to offer alternative RPC endpoints obviously makes our product more robust and less prone to failure if - for instance - something happens to Infura. 

# Implementation

It's really as simple as just adding some more RPC providers to our Network Connections page. However, there are some details worth mentioning: 

Alchemy is not currently open source, and we require some keys to access their API. I'm not sure how people feel about this. Infura isn't open source either but, like I say, the more providers we can offer/connect to, the better it is for us. 

Moreover, "those keys are in profiling mode right now so things are going to be slightly slower - we profile your traffic first to understand and make sure we serve it super reliably, then we turn our infra on 100%. For profiling mode, we'll basically replay your requests 10-100x on our infra to load test and make sure we can handle any spikes you have etc". Also not sure how people feel about that one?

# Acceptance Criteria

3 new RPC connections (for Ropsten, Rinkeby and Mainnet) accessible and working.

# Future Steps

* They have a talented team, and it would be interesting to see if we can advance work with them on stateless whisper clients (cc @mandrigin) so that we could access `shh` over RPC.
* Might be worth exploring whisper visualizations with them of they are already looking at a bunch of other things.

**Comment by andytudhope** [comment]
Some notes from responses:

1. Alchemy is working with a lot of other projects already and people are switching over because they're faster and more reliable. Other projects report they've benchmarked Alchemy as 10-20x faster.
2. The profiling is only for a couple hours, and only looks at stuff like CPU and performance (not queries or data).

Would really love some input @jakubgs @goranjovic @chadyj

**Comment by jakubgs** [comment]
I don't see any issues with adding it just to give our apps more RPC endpoints to chose from. Should increase redundancy.
The profiling might not be an issue, depends on what "slightly slower" means?  10%? 30%? 50%? sure, fine, more than 100%? might become an issue.

**Comment by nikilster** [comment]
Sounds good! Profiling is optional - really to show you guys analytics on how much faster and more reliable the service is. We can skip it.

**Comment by mikealchemy** [comment]
@jakubgs @andytudhope - wanted to give a quick update from our end. We removed the profiling step entirely from our onboarding process. That means we can get you that performance improvement Andy mentioned above right away

Other good news is that in addition to projects like CryptoKitties and Radar Relay using us, Augur has been using us to power their production mainnet and just [made an announcement](https://twitter.com/AugurProject/status/1073376721884172289) about our speed and reliability! Would love to start doing them same for you guys!
