### ISSUE TITLE
"LES not syncing" debug info visible when list of chats is loaded

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6823]
### Description

*Type*: Bug

*Summary*: The issue is on develop branch. But, it can be reproduced more easily on #6722 when there is a lot of chats with messages. Then, the "LES" text appears while the chats are being loaded:

<img src="https://user-images.githubusercontent.com/7532782/48831280-ca414880-ed76-11e8-92c9-68443768c735.png" width="200">

### Reproduction

- Use builds from #6722
- Join lot of public chats with messages
- Log out and log in again

### Additional Information
* Status version: nightly, Nov 21
* Operating System: iOS

**Comment by lukaszfryc** [comment]
@mandrigin could you assign it to yourself?

**Comment by lukaszfryc** [comment]
@mandrigin do you know who can help with this issue? I think it maybe a release blocker.

**Comment by mandrigin** [comment]
@lukaszfryc when are we releasing, btw? :) I was thinking of putting a bounty on this one.

**Comment by lukaszfryc** [comment]
@mandrigin I suggest to cut the release tomorrow and release next week. Please see https://github.com/status-im/status-react/issues/6891

I'd not put bounties on release blockers :) Anyway, we may discuss if this issue is a release blocker or not.

**Comment by mandrigin** [comment]
@lukaszfryc np, I'll take a look at it now

**Comment by mandrigin** [comment]
@lukaszfryc I have fixed it

**Comment by lukaszfryc** [comment]
@mandrigin great :)
