### ISSUE TITLE
Consider the option to remove text input when only using a dapp

### ISSUE THREAD

**Issue by Shrinks99** [status-im/status-react#683]
Yes, Status is a text based messaging app and text interface with popular dapps is definitely a great feature.  That aside, interacting with commands is not the most intuitive way for many programs to be used.

Using the wallet as an example, we see that users are presented with a GUI after opening it, this is great.  The GUI is by far the easiest way for people to send ETH to other people when presented with the other party's QR code and it does what it's intended to do.

Users still have a text input bar at the bottom however which could [definitely pose some confusion!](https://imgur.com/a/MYLA3)

I propose removing the text based interface and relying solely on a graphical interface for user interaction with dapps in Status.  Removing this for the wallet should not have any impact on the dapp's use in a conversation (For example, one should still be able to use the !send command in a chat with another user considering that the P2P messaging is the point of the app).  This would also eliminate the need for users to close the browser and then have to close the command input window.  [Here's a mockup of what it might look like instead](https://i.imgur.com/La49gcm.jpg), way simpler!

~~I also believe the !browse command way of interfacing with web based dapps (and the wallet) leads to a less than awesome user experience and removing it in favour of only using a graphical interface would be better.~~  _I retract this statement after seeing where you're going with this._

If you want to take this a step further, consider putting dapps on their own page in the bottom bar and separating them from other users entirely.  This would allow you to use a grid pattern instead of a list so that users can see more applications at once, after all, if this is the way the entire internet is going people will probably want to use lots of these things and grouping them in with the chat interface probably wont help those who are completely new to the Ethereum ecosystem.  I've made a rough mock up of what this could look like [here.](https://imgur.com/a/oGFDc)  Discover people and dapps in the Discover section, use your dapps in the My Dapps section, browse your added users in the Contacts section and message users in the Chats section.

Thanks for your time, I hope you find my suggestions helpful!

**Comment by jarradh** [comment]
Thanks for your question! This is something I have thought about alot over the past year and yes we have considered something similar to what you propose, our older design looked something like. We recognise that chat interface is not the best interface always. 

<img width="463" alt="screen shot 2017-01-07 at 1 46 33 pm" src="https://cloud.githubusercontent.com/assets/2714786/21740061/d48693e2-d4df-11e6-99e3-2528f9a10942.png">

Where those messages go is a great question! There's two working answers and this will become more solidified as we put forward our chat api proposal. The first is two the DApp developer themselves for support requests, the second is to a message stream that can be consumed by the chatbot.  Also we plan to have many different message types that looks like a subset of react native.

I do disagree on the `!browse` command, I think the text input interface certainly should become the address bar and we just need to work on it more to become more integrated and provide a better browsing experience. Almost everything we'd implement for a graphical/browsing experience is redundant in an address bar. Also consider most browsing experiences on mobile suck. I personally find Chrome unwieldy (Status is no better, yet) but I can certainly say we will only mimic great ideas found in browsers. 

A grid pattern for DApps is definitely doable and requires no seperation to perform.

**Comment by jarradh** [comment]
It will also be possible to hide the text input area, here is how we internally communicate about the Status interface. So as you can see the suggestions are can be fullscreen, without the keyboard interface.

<img width="1159" alt="chat_anatomy" src="https://cloud.githubusercontent.com/assets/2714786/21740118/a7221f3c-d4e1-11e6-9e90-e2a5dec8f832.png">

The tab will look something like this,

![actions](https://cloud.githubusercontent.com/assets/2714786/21740121/bef204a6-d4e1-11e6-96a3-048872792997.png)

**Comment by Shrinks99** [comment]
Very interesting stuff.  I've never seen an application integrate an address bar with a chat interface so you're certainly breaking new ground!  If you would like to minimize user confusion while still maintaining minimal text input perhaps implementing a [picker](https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/) would work.

As I showed in my mockup highlighting and slightly separating the Ethereum wallet functionality of the Status app from other dapps might also be nice.  Nobody wants their wallet functionality buried in their chat conversations!  I think the grid pattern for dapps would definitely be a step to solving that.  :)

As with most alphas I'd imagine UI isn't your biggest concern right now and there is always plenty of room to make changes.  I'm really happy you guys are listening to feedback about this stuff and as with any good pice of design constructive criticism is a part of the process!  I'm Excited to see where the future leads!

**Comment by hitwill** [comment]
I think that (programmers aside) most users would not be comfortable with a CLI for the most part, that means typing and remembering commands, whereas they have become used to 'thumbing' on GUI's for the majority of apps out there.

**Comment by jarradh** [comment]
sure @hitwill that's entirely possible in our current setup
