### ISSUE TITLE
Faucet request error

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6836]
### Description

*Type*: Bug

*Summary*: 

```
Access to XMLHttpRequest at 'https://faucet.status.im/donate/0x58d8c3d70ce4fa4b9fb10a665c8712238746f2ff' from origin 'https://gateway.ipfs.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

#### Expected behavior
able to faucet some funds from simpledapp.eth on ropsten

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/48889127-d8aa6580-ee45-11e8-98a3-51a3c840710a.png)

### Reproduction

- Open Status
- Go to ropsten
- Open simpledapp.eth and faucet funds

**Comment by flexsurfer** [comment]
@asemiankevich  fixed

**Comment by asemiankevich** [comment]
@flexsurfer thanks
