### ISSUE TITLE
App crashes when using a strong password.

### ISSUE THREAD

**Issue by Smokyish** [status-im/status-react#684]
If i use a password that is 36 characters long, consisting of alphabets, numbers, minus, underline and special characters, the app crashes after sending password confirmation.

**Comment by jarradh** [comment]
thanks for the issue!

**Comment by Smokyish** [comment]
This appears to be related to special characters, even a much shorter password with them crashes the app. Could be just a certain character or a set or characters.

**Comment by Jas0n-F** [comment]
This user has reported the crash when using Password1 to generate a secure password

https://instabug.com/applications/status/beta/bugs/101?status=New

**Comment by Jas0n-F** [comment]
Another user reporting crash following password input, they've also pointed out that their phone is very low on storage space. Not entirely sure it's related, but thought it was worth mentioning here.

https://instabug.com/applications/status/beta/bugs/64?status=New
