### ISSUE TITLE
"Wrong decimals for token..." warning pop-up after account login connected to Ropsten (LES) network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6840]
***Type***: Bug

***Summary***: Each time user logs in to account with Ropsten (LES) network set, there are warning pop-ups appear per token enabled in wallet: `Wrong decimals for token STT at address ... - set to 18 but detected as 0`

#### Expected behavior
No warning pop-us about token decimals when user logs in to account with Ropsten (LES) network set. We can keep it in logs though.
 
#### Actual behavior
<img width="295" alt="screenshot 2018-11-22 at 14 51 23" src="https://user-images.githubusercontent.com/8749671/48904130-1919db80-ee66-11e8-97ec-67f5505290d9.png">
<img width="297" alt="screenshot 2018-11-22 at 14 51 15" src="https://user-images.githubusercontent.com/8749671/48904136-1ae39f00-ee66-11e8-9b3b-69c6911327e3.png">

### Reproduction
- Open Status and create new account
- In Profile settings navigate to `Fleet` and set `les.dev.ropsten`
- Login to account again. Navigate to `Profile` -> `Network` -> `Ropsten (LES)` and confirm your choice
- Log in to account again

### Additional Information
* Status version: Develop https://ci.status.im/job/status-react/job/manual/lastSuccessfulBuild/artifact/pkg/StatusIm-181116-141815-70757e-pr.apk / https://ci.status.im/job/status-react/job/manual/lastSuccessfulBuild/artifact/pkg/StatusIm-181116-141815-70757e-pr.ipa 
* Operating System: Android and iOS

#### Logs

 
[Logcat_logs](https://github.com/status-im/status-react/files/2608139/logcatDecimalsErro.txt) per status.ethereum process

[Geth.log](https://github.com/status-im/status-react/files/2608141/gethlogdecimals.log) with DEBUG level set  

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/manual/lastSuccessfulBuild/artifact/pkg/StatusIm-181116-141815-70757e-pr.apk">Error 404 Not Found</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/manual/lastSuccessfulBuild/artifact/pkg/StatusIm-181116-141815-70757e-pr.ipa">Error 404 Not Found</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@goranjovic this validation message is shown i believe because sync is not done under this network right? So no data about the contract is retrieved to compare with

cc @mandrigin

**Comment by goranjovic** [comment]
@asemiankevich Sounds like that

**Comment by Serhy** [comment]
There is no Ropsten (LES) available now in develop so I can't confirm, but very likely it still takes place.
