### ISSUE TITLE
[Auto test] Cover 'Not enough ETH for gas' tooltip triggering by autoetest

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6847]
**User Story**
As a test engineer I want

- [x] [Error "Not enough ETH for gas" trying to send amount > all ETH funds + total fee in Dapp](https://ethstatus.testrail.net/index.php?/cases/view/5685)
- [x] [Error "Not enough ETH for gas" trying to send amount > all ETH funds + total fee from Wallet](https://ethstatus.testrail.net/index.php?/cases/view/5686)
- [x] [Error "Not enough ETH for gas" trying to send amount > all ETH funds + total fee from Chat](https://ethstatus.testrail.net/index.php?/cases/view/5687)

to be covered by automated tests

**Comment by hetvart** [comment]
status: ready https://github.com/status-im/status-react/pull/6896
