### ISSUE TITLE
Fix loading indicator in browser

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6851]
### User Story

As a user, I want visual feedback that a page is loading in the browser so I know to wait for it.

### Description

*Type*: Feature

*Summary*: DApps especially can be slow to load. When doing so in the Status browser, the user is faced with a static-looking, blank screen. There's no indicator that the page is still loading.

#### Expected behavior
Display a loading indicator in the browser for slow loading pages. It would be nice to follow convention with a horizontal progress bar:

<img src="https://user-images.githubusercontent.com/15470435/48916325-0ad9b880-ee82-11e8-99f3-20e081a2ace0.png" width=250 />

#### Actual behavior
Slow loading pages appear stuck:
<img src="https://user-images.githubusercontent.com/15470435/48916336-1d53f200-ee82-11e8-9c04-5ea7dd20cea4.png" width=250/>

**Comment by errorists** [comment]
I'm actually working on progress bars for chat atm, we could create a **component** for any progress bars that work like this one here (click on the fetching messages button), wdyt? https://framer.cloud/MsLgV/1

<blockquote><img src="https://framer.cloud/MsLgV/1/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/MsLgV/1">Status Notifications</a></strong></div><div>This project was made with Framer, a design tool for turning original concepts into working prototypes.</div></blockquote>
