### ISSUE TITLE
Group admin does not effectively leaves group chat

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#6860]
# Problem

If I created a group chat, the only way of effectively leaving it is by first removing all members, otherwise I would still keep receiving new messages from this group.

# Implementation

I suggest that two options should be available:
1. Option to 
   - pass admin to other user; 
   - have multiple admins. 
2. When (the last) group admin leaves, the oldest member of group chat should become the new admin.

# Acceptance Criteria

Group admin should easily able to leave group chat.

**Comment by lukaszfryc** [comment]
Thanks for your thoughts @3esmit. 

I think there is also a 3rd option: When last group admin leaves, he sees popup saying that unless he pass admin to other user, the group chat will be closed.

Would be good to research other clients and then decide on behaviour. I can do it later this week.

cc @chadyj

**Comment by lukaszfryc** [comment]
> If I created a group chat, the only way of effectively leaving it is by first removing all members, otherwise I would still **keep receiving new messages** from this group.

Btw, @chadyj @cammellos do you think it maybe a blocker for group chat release (https://github.com/status-im/status-react/issues/6882)?

**Comment by cammellos** [comment]
To me it does not feel like a blocker, but I can easily change the behavior temporarily so that admin can leave, it might leave some group chats orphaned (no admins), up to you, and then we can have more sophisticated solutions.

**Comment by chadyj** [comment]
cc @errorists ^^

> To me it does not feel like a blocker, but I can easily change the behavior temporarily so that admin can leave, it might leave some group chats orphaned (no admins), up to you, and then we can have more sophisticated solutions.

+1

**Comment by errorists** [comment]
The way it was designed, you can pass admin privileges to other members and if you decide to leave the group chat being its only admin, you're required to pass it to someone else, but @lukaszfryc solution with closing the group would also work. [designs](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=227%3A320)
