### ISSUE TITLE
Impossible to download backup from registrar.ens.domains

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6862]
`registrar.ens.domains` is unusable in status browser

## Steps to reproduce

1. Go to ropsten (to dont waste money), (assert to have funds on ropsten)
2. open dapp registrar.ens.domains
3. make a bid to any name 
4. try to backup your bids (button does nothing)
5. close status and open again
6. open dapp registrar.ens.domains (your bids are erased)

**Comment by asemiankevich** [comment]
thanks @jeluard i will look into it

**Comment by jeluard** [comment]
@asemiankevich Have you looked into it? :)

**Comment by asemiankevich** [comment]
> @asemiankevich Have you looked into it? :)

1. When i tap `download bids`
![image](https://user-images.githubusercontent.com/28752642/50080461-2f188300-01fd-11e9-8f7e-a6b0db1c841f.png)

2. After i reload app - bids are gone

**Comment by asemiankevich** [comment]
hold on, actually point 2 is fine - seems reloading works ( both Metamask and Status).

**Comment by Swader** [comment]
Still a thing

**Comment by churik** [comment]
The workflow in  dapp registrar.ens.domains is changed, could buy name on Ropsten network.
Considering the issue is not relevant anymore (Status v1.0.1)
