### ISSUE TITLE
Allow fleet selection on desktop

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6876]
**User Story**

To allow to select different fleets for use with the app, as it is on mobile:

As a sysadmin I want the app to be able to switch between different eth fleets without having to re-build the whole application. This is necessary to test infrastructure changes and statusd version changes on a staging fleet before it's deployed to the fleet used in the public release.

Check https://github.com/status-im/status-react/issues/5213 for reference

**Comment by jakubgs** [comment]
I think this is sensible. We run different versions of `status-go` on different fleets to the ability to select fleets would make testing the interaction between the desktop app and the fleet easier.

**Comment by churik** [comment]
Irrelevant in terms of #7551
