### ISSUE TITLE
Ensure browser sessions can not correlate identities between Status account sessions

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#688]
Cookies, localStorage, or other such features should not persist when the user signs in otherwise it will be possible to link identities together from a dapp perspective. Also use this issue to investigate the most future-proof method of resetting such state as it seems this sort of behavior could show up in unforeseen ways and be a repeat problem.

note: updated from "when the user signs out" to "when the user signs in" since an unclean exit from the app could also sidestep the protection.

**Comment by jarradh** [comment]
awe-inspiring thoughtful find @rabbit - thank-you so much for thinking of this

**Comment by alwx** [comment]
Thank you for your report, @rabbit. I've fixed this issue in #735.
