### ISSUE TITLE
App version between iOS and Android is not aligned for the same nightly build

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6881]
***Type***: Bug

***Summary***: There are a different app version in iOS and Android app from the same nightly. E.g. for the nightly build updated 2018/11/26 11:52:00 UTC:
iOS: Version `0.9.31 (1811231740); node 27700aa2`
Android: Version `0.9.31 (9999); node 27700aa2`

[Recently](https://github.com/status-im/status-react/pull/6578) we updated the apsolute value for build number. And it's all fine for iOS. But Android apparently limited in display 9999 values for build numbers. So any Android build has the 0.9.31 (9999) version at the moment.

#### Expected behavior
App version is the same on iOS and Android for the same build. 

#### Actual behavior
App version between iOS and Android is not aligned for the same build:

<img width="297" alt="screenshot 2018-11-26 at 15 16 01" src="https://user-images.githubusercontent.com/8749671/49016266-3a443a00-f18e-11e8-879a-092d202c4092.png">
<img width="360" alt="screenshot 2018-11-26 at 15 16 10" src="https://user-images.githubusercontent.com/8749671/49016269-3ca69400-f18e-11e8-8f0a-b4904255c534.png">

### Reproduction

- Install latest Status develop build on iOS
- Install latest Status develop build on Android
- Verify app version on both platforms in `Profile` -> `About`

### Additional Information
* Status version: iOS (`0.9.31 (1811231740); node 52a1bdfe`) / Android (`0.9.31 (9999); node 52a1bdfe`
* Operating System: Android and iOS

**Comment by mandrigin** [comment]
@jakubgs looks like the build script is borked

**Comment by jakubgs** [comment]
Yeah, this looks weird. Let me investigate.

**Comment by jakubgs** [comment]
Okay, this should fix it: https://github.com/status-im/status-react/pull/6894

This android build should have the right build number:
https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181127-170423-0e19f5-pr.apk

**Comment by Serhy** [comment]
https://github.com/status-im/status-react/pull/6894 which fixing the version numbers is not in develop (and 0.9.32 release)
Closing the issue.
