### ISSUE TITLE
'Intrinsic gas too low' error when sending a transaction with valid data to a non-contact after scanning QR code

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6895]
Type: **Bug**

Summary: It's impossible to send a transaction after scanning a QR code.
Currently, after you sign a transaction, an error 'Intrinsic gas too low'  is displayed.

**Expected behavior**

'Transaction sent' success screen is shown
Transaction is sent with no errors

**Actual behavior**

1-1 chat screen with an error 'Intrinsic gas too low' is displayed
Transaction is not created

<img width="440" alt="image" src="https://user-images.githubusercontent.com/43638377/49076154-0a09a380-f241-11e8-814c-2a79c5c3f59b.png">

**Reproduction**

1. Create a new account and log in
2. Switch your network to Ropsten
3. Request Eth in the Status test App
4. Click '+' select 'Scan QR code' and scan contact code of a secondary device
5. On profile screen, select 'Send transaction'
6. Set your transaction data to available amount in Eth and click 'Send' button
7. On the 'Send transaction' screen open Advanced settings to make sure your Gas limit is 21000 and Gas price is 1 (default data)

<img width="442" alt="image" src="https://user-images.githubusercontent.com/43638377/49076190-1b52b000-f241-11e8-901f-db9562c2643a.png">

8. Sign your transaction
 
**Additional data:**

Status version: 0.9.31 (1811231740); node 27700aa2 (Nov 27 nightly build)
Operating System: iOS

**Comment by SlizkovaGanna** [comment]
Theoretically should be fixed after https://github.com/status-im/status-react/issues/4923 is fixed.
@goranjovic please let me know if you want me to close this one

**Comment by churik** [comment]
Still reproducible

**Comment by goranjovic** [comment]
@churik Possibly fixed in PR #7263

**Comment by churik** [comment]
Not relevant after redesign in Status v1.0.1
