### ISSUE TITLE
Do not share user's info when sending a message to a non-contact

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6897]
**User Story**

As a user, I would like to send a message to someone without sharing my personal info. 
To share my info, I would select 'Add to contact' option.

**Description**

When a user scans QR code of a contact, he is left with several options, such is: 
'Add to contacts', 'Send message', 'Send transaction', 'Share profile link' 
When you select an option of sending message without adding them to your contacts, you share your info regardless, as a contact request upon sending that message.
So, the person is in your contacts automatically. 

In my opinion, it's not obvious that a user will share his/her details when sending a 1-1 message to a contact.

The question is, shouldn't we keep user anonymous when he is simply sending a message, without selecting 'add to contacts'? 

**Expected behavior**

User should have the ability to send a message without revealing their contact info

**Actual behavior**

As soon as user clicks 'Send message', their contact data is revealed to that person without user's knowledge (a contact request is sent)

**Reproduction**

1. Scan QR code
2. Select 'send message'
**Actual result:** At this point a contact request is sent without the user's knowledge (for me it would not be obvious that I'm automatically adding that person to my contact list just by sending them a message)
3. Send a message
**Actual result:** At this point the reciever can see my name and contact data, since a contact request was sent.

**Comment by asemiankevich** [comment]
@errorists @hesterbruikman wdyt?

**Comment by lukaszfryc** [comment]
I think this is more a product question. @chadyj @cammellos please share your thoughts.

**Comment by hesterbruikman** [comment]
From a usability perspective I would say that whatever we decide it needs to be transparent. The problem of the current flow as I see it is that it is not communicated what information (i.e. wallet address is shared). 

fyi: @andmironov is working on some awesome designs that address this.

**Comment by lukaszfryc** [comment]
> fyi: @andmironov is working on some awesome designs that address this.

So we already decided how it will work? Do we have any mockups?

**Comment by hesterbruikman** [comment]
In my mind it's in a conceptual design phase. There are mocks, but these are not a decision on how it will work. It's an exploration for now. Sorry, can't find the screens at the moment:/
