### ISSUE TITLE
Automatically pair and sync data across devices 

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6898]
### Description

*Type*: Bug

*Summary*: We introduced pairing/multi-device support in https://github.com/status-im/status-react/pull/6242 and https://github.com/status-im/status-react/pull/6697. But, to enable it users need to go to the settings and manually pair with another device. This needs to be repeated on each device. The process takes time and maybe confusing for some non-technical users. I suggest to support automatic pairing of each devices by default. So, each message, contact, profile change, etc. is automatically synced across all devices that use the same account.  

#### Expected behavior
Say I use only desktop app. When I install mobile app and restore my account, I should be automatically paired with desktop device. All content from the desktop app should be automatically synced with the mobile app. 

#### Actual behavior
I need to manually pair each device in settings. I need to repeat it on every device:

<img src="https://user-images.githubusercontent.com/7532782/49079644-797f9300-f241-11e8-8c61-14ffd81c2598.png" width="200">

### Reproduction

- Restore account on multiple devices 
- On each device: go to Settings->Devices and pair other devices

### Additional Information
* Operating System: all

**Comment by lukaszfryc** [comment]
@cammellos is this feature possible and secure?

**Comment by cammellos** [comment]
@lukaszfryc technically it is possible, but is not secure, anyone having access to your seed phrase will basically have access to all historical data, control over which devices are kept syncing (we can only keep syncing x amount of devices), and would invalidate pfs.

 I think this step is fairly rare (normal users rarely change devices), so having to work a bit is ok, rather I would work on making it more discoverable and easier to use.

**Comment by lukaszfryc** [comment]
I see. I'd say it's rare between mobile devices but quite common if you think of desktop and mobile sync. As you said, let's make it more discoverable in this case. I'd expect to see an automatic suggestion inside mobile app asking if I want to sync data between my desktop device. Same on desktop if I already use mobile app.

@chadyj @errorists wdyt?

**Comment by cammellos** [comment]
> I'd say it's rare between mobile devices but quite common if you think of desktop and mobile sync.

I meant something a bit different, it's rare, meaning that you don't have to do it every week say, you do it once, and then it's set up for a while, and you have only to do it if you re-install etc (which should happen rarely to a normal user), but otherwise I agree

automatic suggestion sounds like a good idea

**Comment by churik** [comment]
> automatic suggestion sounds like a good idea

agree here. In any case, we should be sure that devices are keeping to be synced when upgrading builds on all of them or in several and add instructions and suggestions how to enable pairing for the very first time.

**Comment by lukaszfryc** [comment]
> automatic suggestion sounds like a good idea

@cammellos but, is it possible technically?

**Comment by cammellos** [comment]
@lukaszfryc I am thinking on something on these lines:
1) You click on pair devices on device A
2) Device B/C/D will see a pop up, "Device A has been detected, would you like to pair and enabled it?"
3) Device A will see a pop up "Device B has been detected, would you like to pair and enable it?"
something on these lines

**Comment by lukaszfryc** [comment]
@cammellos sounds good. But my ideal experience would be to see a status bar in Home tab saying "2 devices available to pair". When I click on it I'd be redirected to Devices screen and follow your instructions. Can the device knows it before allowing to pair it (clicking "Pair this device")? 

---

Btw, I'd say that currently, when a user goes to Settings->Devices, he is lost because:
1) There is no action/feedback when "Pair this device" button is pressed. I suppose we should say that the device is now available to pair on other devices.
2) There is no guide how to pair devices. Instead of "Pair your devices to sync contacts and chats between them" the app should say something like "Enable pairing on your other devices to see them here. Then click on them to pair". 

<img src="https://user-images.githubusercontent.com/7532782/49084636-57414180-f250-11e8-95c9-3327910da1fa.png" width="200">

**Comment by cammellos** [comment]
@lukaszfryc other devices won't be able to discover device A until device you click "pair this device" on device A, we could advertise the device periodically but I'd avoid it for now (it trade offs on darkness). 

for the ux feedback cc @errorists

**Comment by lukaszfryc** [comment]
@cammellos but device A that did not allow for pairing yet can detect device B and automatically show a hint saying "Device B available to pair" (provided device B allowed for pairing)?

**Comment by cammellos** [comment]
as long as someone pressed `Pair this device` on device B, yes

**Comment by lukaszfryc** [comment]
ok, I think I will create a separate issue for "Suggest available devices to pair" to implement it.

**Comment by lukaszfryc** [comment]
> There is no guide how to pair devices. Instead of "Pair your devices to sync contacts and chats between them" the app should say something like "Enable pairing on your other devices to see them here. Then click on them to pair".

@cammellos in terms of upcoming release, do you think it's worth changing the copy there to make it more explicit how to pair the devices? I'm worried that many people may not understand that they first need to click on "Pair this device" on other devices to see them on the list. cc @errorists

**Comment by cammellos** [comment]
we could also literally just link to the discuss post for the time being :)

**Comment by lukaszfryc** [comment]
I do not think anyone will leave the app and read the discuss post :( 

I really think we should update the copy and ideally make the "pair button" a toggle. Currently, the app does not give any feedback when I click "Pair this device". I'd change it to a toggle so you could understand that it's enabled / disabled.

**Comment by cammellos** [comment]
that's not quite how it works :) 
basically when you click on Pair this device, your device is made discoverable by simply sending a message, so it's not a toggle (i.e if you add another device a couple of days after, you still will have to click on Pair this device to have the old device showing in the new device).

**Comment by lukaszfryc** [comment]
Thanks for explaining it :) 

Anyway, I still think it's hard to understand how to set it up. I'd expect something to happen when I press a button. Currently, nothing happens visually when "Pair this device" is clicked. 

@errorists ideally, we should guide users step by step by the pairing process. First, ask them to make their device discoverable, then ask to make other devices discoverable and as a last step click on devices to sync. 

I'm really worried that hardly anyone will use this great feature in current version.

**Comment by lukaszfryc** [comment]
I'm closing the issue as we do not want to have the **auto** sync by default https://github.com/status-im/status-react/issues/6898#issuecomment-442032043. 

As for the **suggestion** to sync, please create a separate feature request if you think we can automatically suggest user that she can pair with other devices https://github.com/status-im/status-react/issues/6898#issuecomment-442033480.
