### ISSUE TITLE
Latest block In Ropsten(LES) fall behind latest block in Ropsten RPC

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6901]
***Type***: Bug

*Summary*: When `Ropsten (LES)` network (with les.dev.ropsten fleet setting) is enabled we pull the latest block number and start sync. The latest block number in a case of Ropsten RPC is far beyond the latest block that Ropsten (LES) is put to use as latest:
For example at this moment (27th Nov 2018 ~13.00 CET):
**Rospten (LES)** defines: `syncing 4198783 of 4329035 blocks...` i.e. **4329035** is the latest block LES is about to sync up to.
**Ropsten RPC** (taken from etherscan): latest block **4515401**

It's 28 days difference! (timestamp for 4329035 block LES is looking for Oct-30-2018)

#### Expected behavior
Ropsten (LES) latest block aligned with latest block in Ropsten network

#### Actual behavior
Ropsten (LES) latest block is not aligned with latest block in Ropsten network

<img width="360" alt="screenshot 2018-11-27 at 14 07 53" src="https://user-images.githubusercontent.com/8749671/49081017-1cd6a500-f24e-11e8-8c8c-d944f19c8696.png">
VERSUS 
<img width="1146" alt="screenshot 2018-11-27 at 14 04 32" src="https://user-images.githubusercontent.com/8749671/49081041-30820b80-f24e-11e8-9c54-b4efa7c561dd.png">

### Reproduction

- Open Status develop build (e.g. nightly) and create new account
- Switch fleet setting to `les.dev.ropsten` and set network to `Ropsten (LES)`
- Stay on Home screen
- Once sync process is started note the latest block LES is exposed at screen top (the `LES: 'latest' #[current_block_num] syncing [current_block_num] of [latest_block_num] blocks`
- Check the latest block at, for example, Etherscan for Ropsten network (ropsten.etherscan.io)
- Compare latest_block_num between LES and Ropsten 

### Additional Information
* Status version: Develop `0.9.31 (1811211215); node 52a1bdfe`
* Operating System: Android and iOS

#### Logs

[geth.log](https://github.com/status-im/status-react/files/2619905/geth.9.log) with 'Trace' log level see there

``` 

t=2018-11-27T12:13:36+0000 lvl=dbug msg="Remote head header identified" peer=0419bab5f2fb5f64  number=4330851 hash=0x73b37d70f3e1f70f1e88b00f8d71c7d53427959c48bb616a9c4893182555a8a5
t=2018-11-27T12:13:36+0000 lvl=dbug msg="Looking for common ancestor" peer=0419bab5f2fb5f64  local=4198783 remote=4330851

```

**Comment by mandrigin** [comment]
Just to add to this task. LES servers that are used here (added as static peers) are:
```
        "les-rops.misc": {
            "node-01.do-ams3.les-rops.misc": "enode://bc827e035cf3a42c249374be7ddc9c2fb819765c440116cf01aa6a8d70d03043d29ccd42b32a283f5ab08294467eb3b92fc40111e9af1770c84bc116edae89c0@104.248.199.52:30303", 
            "node-02.do-ams3.les-rops.misc": "enode://52018eb510f8d3321e68e003de14b151ed31c76b98d760f48d4de6b5d3a1ce39d18e4685b87001cebf582eb0cf9debc3c35b84509e476f00324f4c10347a33ab@104.248.199.213:30303", 
            "node-03.do-ams3.les-rops.misc": "enode://690c93ac2f6e6f711a175cc6a73a3cf3b649eea83c458ce34364c69d1b557bb408693f06bdf6fc31538a744d5c231fdd904cce5665d04ce165032c0fc009a208@104.248.199.160:30303"
        }
```

**Comment by mandrigin** [comment]
Constantinople issue, let's keep it open. Needs to be revisited after the hard fork and status-go upgrades.
