### ISSUE TITLE
The logo unread message counter is not cleared when logging in under a new created account

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6902]
Type: **Bug**

Summary: When user has unread messages, after logging out and creating the new account, that new account inherits the icon message counter.

**Expected behavior**

Logo unread message counter should clear up when logging in as a different user

**Actual behavior**

Logo unread message counter is inherited from the previous account, when logging in under a new created account

**Reproduction**

1. Log in using your existing account with unread messages from 1-1 chat/send a message to your user so that icon unread message counter would appear
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/43638377/49082344-35e15500-f252-11e8-9d5e-9546ba4abd4d.png">

2. Log out

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/43638377/49082379-47c2f800-f252-11e8-8e1a-936d7acab8a0.png">

3. Create a new account and log in right away

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/43638377/49082418-61643f80-f252-11e8-805d-0bfa2e934262.png">

**Additional Information**

Status version: Status desktop 26/11/18
Operating System: Mac OSx

**Comment by churik** [comment]
Relevant
