### ISSUE TITLE
Replies are shown as ordinary messages if they are sent from current nightly and quoted on release build or when reply to old message sent before upgrade and both contacts are on release build

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6903]
# Case 1: Replies are shown as ordinary messages if they are sent from current nightly and quoted on release build
### Description

*Type*: Bug
*Summary*: when user has current nightly installed and replies to message, sent from release build, user with release build will see an ordinary message and vice versa.

#### Expected behavior
can see reply message on both A and B

#### Actual behavior
ordinary message on device A and reply message from device B
![deblkdjsf](https://user-images.githubusercontent.com/4557972/49085954-958c3000-f253-11e8-92cb-e4828707683b.png)

### Reproduction

**Prerequisites:** 
1. device A has installed  0.9.31 version (released) 
2. device B has installed  latest nightly 26/11/2018

- Open Status on device A
- Log in
- Join any channel (i.e. #test)
- Open Status on device A
- Log in
- Join same channel (i.e. #test)
- Send a message from device A
- Reply to message from device B
- Check public chat on device A and B

### Additional Information
* Status version: nightly 26/11/2018
* Operating System: all

# Case 2:  No quotation is shown in the reply message on recipient side if reply to message sent before upgrade

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Recipient gets no quotation in the reply message if reply to message sent before upgrade from 0.9.31 to 0.9.32. On sender side quotation is shown as expected. Both recipient and sender are on 0.9.32. Note that if reply to message sent after upgrade is done on both sides then quotation is shown as expected for both sender and recipient. So, issue is only on recipient side for replies to "old" messages sent while being on 0.9.31.

Recipient (no quotation is shown):
![36012](https://user-images.githubusercontent.com/6584810/49231010-4aa81f00-f3f1-11e8-9722-f679bdd07ca7.jpg)

Sender (shows quotation as expected)
![screenshot_20181129-160441](https://user-images.githubusercontent.com/6584810/49231076-6f9c9200-f3f1-11e8-90bf-65359a7d4b07.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Quotation is shown to recipient, sender and other chat participants for replies to messages sent on 0.9.31 and on 0.9.32 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Quotation is not shown to recipient if reply to message sent before upgrade
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. sender and recipient are on 0.9.31 and they are in contacts of each other
2. both send text message in 1:1 chat
3. both upgrade to 0.9.32
4. sender replies to message from recipient in 1:1 chat
5. check how reply is shown on recipient side

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: from 0.9.31 release to build 7 of 0.9.32 release
* Operating System: Android and iOS

**Comment by churik** [comment]
@rasom as we discussed on chat-sync meeting, it could be related to your recent changes in message-IDs.
Can you confirm or disprove it?

**Comment by rasom** [comment]
@churik ~~yes it is related to the `message-id` thing and i doubt that we can do anything here~~
working on it

**Comment by asemiankevich** [comment]
@yenda thoughts?

**Comment by yenda** [comment]
@asemiankevich as I said in the release thread I think we should break compatibility (it's just for responses) and pass message-id in the messages from now on to avoid this kind of problems in the future

**Comment by rasom** [comment]
fix is ready https://github.com/status-im/status-react/pull/6976
