### ISSUE TITLE
Fail build if `package-lock.json` changes

### ISSUE THREAD

**Issue by corpetty** [status-im/status-react#6906]
In an attempt to start monitoring our dependencies, we should fail the build if the `package-lock.json` file changes as it checksums all dependencies.  This gives us an initial guarantee that whatever changes that are happening are not within the scope of dependencies, and informs us that we need to check whatever changes happen within a dependency when they change.

This will suffice as an initial attempt to start monitoring these things, until we can implement a more robust methodology in the build process such as https://snyk.io

<blockquote><div>Snyk</div><div><strong><a href="https://snyk.io/">Open Source Security Platform | Snyk</a></strong></div><div>Snyk helps you use open source and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and much more.</div></blockquote>

**Comment by mandrigin** [comment]
I'll take a look at it.
