### ISSUE TITLE
Link failed tests with known issues under PR's e2e test results

### ISSUE THREAD

**Issue by hetvart** [status-im/status-react#6907]
### Summary:
As a QA I want to see which tests failing under a PR relate to known issues and which are new failures.

### Idea:
This should help a developer/qa to understand which fails are new and which are known issues (i.e. those that have associated unresolved bug)

**How test will look in code:**
We introduce a new mark to assign existing open issues to a test
```python
@marks.testrail_id(5356)
@marks.critical
@marks.github_issue(2, 3)
def test_known_issue(self):
    sign = SignInView(self.driver)
    foo = False
    if not foo:
        sign.driver.fail('Oops!')
```
So the above test will fail but it has a list of associated issues assigned. We will check the state of the issues. If at least one of the listed issues is in open state the test will be marked as "known issue" and appropriate GitHub issue will be assigned to the result in TestRail and under a developer PR (statustestbot comment).

**How it will look in GitHub:**

**_Collapsed:_**

![statustestbot](https://user-images.githubusercontent.com/15172961/49441691-f970a480-f7cf-11e8-87f1-697f7d8160f9.jpg)

**_Expanded:_**

![expanded](https://user-images.githubusercontent.com/15172961/49441719-068d9380-f7d0-11e8-93e2-27e877e29f7c.jpg)

**How it will look in TestRail:**
<img width="493" alt="testrail" src="https://user-images.githubusercontent.com/15172961/49441860-6ab05780-f7d0-11e8-8dfb-8c4b7d5f619d.png">

**Comment by hetvart** [comment]
@yevh-berdnyk @antdanchenko 
please find a time to express your thoughts on this matter.

**Comment by antdanchenko** [comment]
@hetvart what do you think about adding failure message to the github issue and match them not only by closed/open status, but also by test failure message?

e.g.
https://ethstatus.testrail.net/index.php?/tests/view/371168&group_by=tests:status_id&group_order=desc&group_id=5

Check that https://github.com/status-im/status-react/issues/6138 status is open and that failure message is `'Seen' status is not shown under the text message which was read by a receiver`
