### ISSUE TITLE
IOS pings apple.com

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#6912]
# Problem
IOS pings `apple.com` via `NetInfo` for connectivity checks.

## Description
It looks like IOS is pinging `apple.com` for checking if the device is connected 

https://github.com/facebook/react-native/blob/eebc8e230a9f72c3dde34a5cfd59bbffba55e53d/Libraries/Network/RCTNetInfo.m#L127

I have only verified this by code inspection and not actually checking the connections made to the app, so it might not be the case.

Ideally for privacy concern we should either not use `NetInfo` and rely on `peers` count or at least use something safer for this.

Related to: https://github.com/status-im/react-native-desktop/issues/378

<blockquote><img src="https://avatars0.githubusercontent.com/u/69631?s=400&v=4" width="48" align="right"><div>![](https://assets-cdn.github.com/favicon.ico)GitHub</div><div><strong>[facebook/react-native](https://github.com/facebook/react-native)</strong></div><div>A framework for building native apps with React. Contribute to facebook/react-native development by creating an account on GitHub.</div></blockquote>

**Comment by Swader** [comment]
I don't think this is resolved

**Comment by flexsurfer** [comment]
@cammellos still relevant?

**Comment by cammellos** [comment]
Closing this,  it is still relevant, but given we have push notifications those are likely leaking much more metadata
