### ISSUE TITLE
Swipe gestures and field inputs conflict with each other

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#692]
## Description

Swiping left and right to change views can interfere if the user does the swipe action over an active input field.

### Reproduction

Using iOS:

1. Go to the flyout menu sidebar showing user profile photo and current status at top with menu items below.
2. Swipe left over the users name.

### Observation 

Instead of the flyout menu closing with the swipe gesture, the keyboard is presented to change the users name. (sidenote: I don't think a menu should be a form in the first place but demonstrates the issue well)

### Expectation

The flyout menu should close.

---

### Reproduction 

Using iOS:

1. Go to Chats listing view.
2. Press and hold an existing chat session.
3. Swipe right.

### Observation 

There are no view panels to the left of the Chats listing view so the swipe gesture is ignored and the pressed chat session will open.

### Expectation 

The swipe action should be ignored and not registered as a tap.

**Comment by chadyj** [comment]
Shouldn't be a problem anymore
