### ISSUE TITLE
Implement spec-based generative testing and tracing with Ghostwheel

### ISSUE THREAD

**Issue by gnl** [status-im/status-react#6924]
- [x] Release Ghostwheel with Status-relevant updates.
  - https://github.com/gnl/ghostwheel/blob/master/CHANGELOG.md
- [ ] Submit PR to enable Ghostwheel usage for spec-instrumentation, generative testing and evaluation tracing during Status development
- [ ] Submit PR for any issue with specced and gen-tested code.

# Problem

An overview of the background required to understand the problem.
A problem description.

# Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

# Acceptance Criteria

Rules for the future PR to be accepted.

# Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by mandrigin** [comment]
I guess it isn't happening now? @yenda feel free to reopen if we want to keep it.

**Comment by yenda** [comment]
I saw @gnl last weekend I should have asked him
