### ISSUE TITLE
Collection of low priority visual issues

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#693]
I'll be collecting several issues here that are subjective and up to you to determine their validity. If and when it comes time to address these, **copy it out into its own issue**.

## Non-View Specific

* Transitions between views feel a little too snappy in contrast to the gentle theme of the app. Consider playing with ~100ms fades or content zoom ups on initial view load.
* When using airplane mode, the "Offline" hint ...
  * obscures content below it. add a top padding when offline.
  * interacts oddly with the browser view because it replaces the top header bar.
* Conversational UI's should provide access to timestamps for each message. ex: Messages app on iOS enables a left swipe to reveal individual message  #timestamps.

## Account Listing

* "Switch users" is an odd phrasing for a situation where the user has yet to login. Consider hiding the text for initial login or renaming to something like "Accounts" that works in all contexts.
* Hash strings can be intimidating to some users, limit their exposure for passive displays such as the account list, it still shows up in full on the login form. Consider adopting a GitHub-style shortening of the hash. ex: `1110fd263` it might be interesting to define an on-brand, 16 point color palette for each hex value, at a glance the color sequence may be a better indicator than the values themselves.

## Login Form

* Connect should be disabled if the password input is empty.
* On incorrect password, consider a more visually prominent error hint such as coloring, bolding, or left-right shaking animation when the hint first appears.

## Chats Listing

* When press and holding an item, it becomes semi-transparent. If the item above the selected item has multiple lines of text, it becomes revealed and the overlap is visible.

`more to come...` 😈

**Comment by jarradh** [comment]
@carlbennetts was animate about the transition times, maybe we are too fast now, before we were too sluggish.

**Comment by sla-shi** [comment]
Need to validate these issues and create separate tasks.

**Comment by yenda** [comment]
@andmironov @denis-sharypin can we close this ?

**Comment by denis-sharypin** [comment]
yes
