### ISSUE TITLE
Port chat.command extension hook to desktop

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6934]
# Problem

`chat.command` extension hook is not available to desktop users.

# Implementation

Port existing mobile implementation to desktop.

# Acceptance Criteria

`chat.command` extensions can be executed.

# Notes

This requires chat command feature to be implemented in desktop.

**Comment by rachelhamlin** [comment]
Is this issue about implementing chat command on desktop, or doing additional work on extensions for it to work?

**Comment by jeluard** [comment]
@rachelhamlin Yes it is the extension specific glue needed. It still requires the chat command to be ported first.

**Comment by rachelhamlin** [comment]
@jeluard okay cool. I'll see about creating an issue for desktop chat commands.

**Comment by churik** [comment]
Irrelevant in terms of #7551
