### ISSUE TITLE
Discover view lost its over scroll bungie effect

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#694]
## Description

[iOS] The Chats and Contacts views will allow you to slide a view beyond its max height and it will snap back. The Discover view has lost this effect.

## Reproduction

1. Go to Discover view.
2. Slide down to go beyond top of page. **[nothing happens]**
3. Go to Chats view.
4. Slide down to go beyond top of page. **[bungie effect is visible]**

**Comment by flexsurfer** [comment]
I think it's as design for Empty screen, there is background picture and no list component at all, but for screen with items it has been turned off deliberately [here](https://github.com/status-im/status-react/blob/3258df51c826e75250d85565d1f990a5c626b20d/src/status_im/discover/styles.cljs#L30)
