### ISSUE TITLE
No quotation is shown in the reply message on recipient side if reply to message sent before upgrade 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#6944]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Recipient gets no quotation in the reply message if reply to message sent before upgrade from 0.9.31 to 0.9.32. On sender side quotation is shown as expected. Both recipient and sender are on 0.9.32. Note that if reply to message sent after upgrade is done on both sides then quotation is shown as expected for both sender and recipient. So, issue is only on recipient side for replies to "old" messages sent while being on 0.9.31.

Recipient (no quotation is shown):
![36012](https://user-images.githubusercontent.com/6584810/49231010-4aa81f00-f3f1-11e8-9722-f679bdd07ca7.jpg)

Sender (shows quotation as expected)
![screenshot_20181129-160441](https://user-images.githubusercontent.com/6584810/49231076-6f9c9200-f3f1-11e8-90bf-65359a7d4b07.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Quotation is shown to recipient, sender and other chat participants for replies to messages sent on 0.9.31 and on 0.9.32 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Quotation is not shown to recipient if reply to message sent before upgrade
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. sender and recipient are on 0.9.31 and they are in contacts of each other
2. both send text message in 1:1 chat
3. both upgrade to 0.9.32
4. sender replies to message from recipient in 1:1 chat
5. check how reply is shown on recipient side

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: from 0.9.31 release to build 7 of 0.9.32 release
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
might be connected to https://github.com/status-im/status-react/issues/6903

**Comment by mandrigin** [comment]
@yenda is you happen to have some time, can you take a look? I'm pretty sure you should know these parts of code the best :)

**Comment by yenda** [comment]
@annadanchenko yes it is a duplicate of https://github.com/status-im/status-react/issues/6903

**Comment by annadanchenko** [comment]
@yenda  I will add this info to #6903, thanks

**Comment by annadanchenko** [comment]
updated #6903
