### ISSUE TITLE
Implement chat commands on desktop

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6945]
### User Story

As a user, I want to use chat commands to do things like `/send` tokens on Status desktop, so that I have the conveniences I'm accustomed to on mobile. 

### Description

*Type*: Feature

*Summary*: Bring mobile chat commands to desktop.

#### Expected behavior
Users can `/send` and `/request` payments. 

With commands implemented, we can also [port chat command extensions](https://github.com/status-im/status-react/issues/6934) to desktop.

#### Actual behavior
Attempting to type a command like `/request` results in no message being sent.

**Comment by chadyj** [comment]
Coming soon-ish!
Depends on https://github.com/status-im/status-react/issues/6297

**Comment by Swader** [comment]
Reopening because it's important to me

**Comment by churik** [comment]
Closed as commands are removed now in #8674
