### ISSUE TITLE
"no value" instead of ETH is shown in chat list for send/request after upgrade

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#6953]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "no value" instead of "ETH" is shown in last message preview on Home tab after upgrade from 0.9.31 to 0.9.32 for send or request messages. Note that inside 1:1 chat message message is shown as expected and request can be used to send ETH. Same for send message: in 1:1 chat it's shown fine.

Before upgrade:
![before upgr](https://user-images.githubusercontent.com/6584810/49254544-c45bff00-f429-11e8-988c-94dcb60cb840.png)

After upgrade
![after upgr](https://user-images.githubusercontent.com/6584810/49254560-caea7680-f429-11e8-91a1-1719081876d5.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
same preview as before upgrade is shown after. For example, "Requesting 0.05 ETH" is shown as last message in 1:1 chat on Home tab
#### Actual behavior
[comment]: # (Describe what actually happened.)
"Requesting 0.05 <no value>" is shown for 1:1 chat on Home tab after upgrade
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- A and B are in contacts of each other and have 0.9.31 release installed
- A sends request in 1:1 chat of 0.05 ETH
- B can see in Home tab for the 1:1 chat new request message "Requesting 0.05 ETH"
- B upgrades to 0.9.32 and check how request looks like

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: upgrade from 0.9.31 to build 7 of release 0.9.32
* Operating System: Android and iOS

**Comment by asemiankevich** [comment]
@goranjovic  @bhauman Wondering how difficult is to fix this? It is not a release blocker but if it looks like something easy to fix - would be nice to include in upcoming release

**Comment by goranjovic** [comment]
@asemiankevich Unfortunately, not an easy fix. Depends on #6492

**Comment by yenda** [comment]
@goranjovic since it already works in the chat it doesn't seem like it depends on #6492, more like inconsistency in the way last message is shown compared to the chat itself don't you think?
