### ISSUE TITLE
Install nvm or iOS slaves

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#6955]
# Problem

Now that we moved to `yarn`, we can also upgrade to node 10. However we need to upgrade realm as well since node 10 only supported from realm `2.19.0`.
The problem is that there is a commit before `2.19.0` of realm that assumes use of a node package manager for iOS release process with realm. It seems like it is going to take a while for upstream to fix this as they need to make changes to their CI before a fix is merged.

# Implementation

In order to be able to upgrade realm and node the quickest path for us is to install nvm on iOS slaves.

# Acceptance Criteria

nvm is installed on iOS slaves and https://github.com/status-im/status-react/pull/6949 can be built

# Future Steps

nvm is installed on all slaves

**Comment by jakubgs** [comment]
So here are the issues with NVM:

* `nvm` is not a script or a binary, it's a huge shell function, which means we can't easily link to it.
* Jenkins does not run `interactive` shells so it does not load things like `nvm` from `.bashrc` for example.
  - Calls to `nvm use ${VER}` have no effect between invocations of `sh`.
  - This means we'd need to run `nvm.sh` for every invocation of `sh`, like so:
  `sh 'source ~/.nvm/nvm.sh && ${COMAND}'`
  which is stupid.
* Node version can be changed with `nvm alias default ${VER}` but for it to take effect Jenkins node needs to be reconnected.

As an alternative we could use the [NVM Wrapper Plugin](https://wiki.jenkins.io/display/JENKINS/Nvm+Wrapper+Plugin) which can be used in a declarative pipeline like so:
```groovy
pipeline {
    agent { label "linux" }
    
    stages {
        stage('Test') {
            steps {
                nvm('v10.14.1') {
                    sh 'node --version'
                }
            }
        }
    }
}
```
Example run: https://ci.status.im/job/tests/job/nvm-test/5/console

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/tests/job/nvm-test/5/console">tests » nvm-test #5 Console [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
Now, this syntax means we have to use `nvm('v10.14.1')` in every Stage where we need the specific version of Node. This is an improvement over calling `nvm.sh` in every `sh` invocation, but still a bit messy.

**Comment by jakubgs** [comment]
I might add that the disadvantage of this approach is that we node version would have to be hardcoded in the `Jenkinsfile`s, or possibly loaded from a file from `status-react`(`NODEJS_VERSION`) and then used via a variable in `nvm()` call, like so:
```groovy
stage('Test') {
    steps {
        def nodeVersion = readFile("${env.WORKSPACE}/NODEJS_VERSION").trim()
        nvm(nodeVersion) {
            sh 'DO STUFF'
        }
    }
}
```

**Comment by jakubgs** [comment]
It appears that the approach with NVM Wrapper Plugin works as shown in: https://github.com/status-im/status-react/pull/6949
Not sure though if this is the approach we want to use for all builds.

**Comment by jakubgs** [comment]
So this is pretty much done, we have NVM on slaves:
https://github.com/status-im/infra-misc/commit/4a6cd137ba828c121ba0a75b0772d182364a4b5a
And we use it in builds using the `nvm()` wrapper:
https://github.com/status-im/status-react/blob/develop/ci/Jenkinsfile.ios#L30
I consider this done.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>
