### ISSUE TITLE
Upgradable message-ids

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#6956]
# Problem

Whenever we make changes to the way message-ids are generated it creates upgradability issues. It happens again in latest release with message responses https://github.com/status-im/status-react/issues/6903#issuecomment-443127013

# Implementation

We need to pass the message-ids with the message to avoid that in the future. These are the problems I think should be taken into consideration:
- pk of the sender and chat-id might be prefixed to the message-id locally to avoid forged message-id overwriting previous messages
- chat-id needs to be consistent so the previous point might just move the problem there

# Acceptance Criteria

- message-id is speced and easily reproducible in other implementations of the communication protocol
- message-id is passed in messages with reasonable guarantees that it cannot be used to overwrite previous messages (ignoring existing ids can be considered but this will open up to MIT attacks if we don't prefix pk, an attacker could silent someone in a public chat by overwritting all their messages for a broad part of the network if they have better connectivity)

**Comment by mandrigin** [comment]
@yenda 

> pk of the sender and chat-id might be prefixed to the message-id locally to avoid forged message-id overwriting previous messages

I don't see how it helps if I myself want to overwrite my own messages, which can be of use for a malicious actor.

**Comment by mandrigin** [comment]
I don't know how bad this idea is, but we can just denormalize and include the whole source message in a reply. Then, we can assign IDs to messages client-side on receiving, so no one will be able to tamper with them.

**Comment by cammellos** [comment]
@yenda @mandrigin we should not overwrite messages (messages should be immutable), it prevents a different scenario, namely a malicious user sending a message with identical `id` as soon as they see it, in which case a race condition is trigger where first-one (not last one) wins.

**Comment by cammellos** [comment]
> we can just denormalize and include the whole source message in a reply


Would need to be signed though, otherwise how can we make sure is not being tampered? 
If we use ids we are back to square one (a user who does not have the original message can't verify that is not tampered), or I am missing something?

**Comment by mandrigin** [comment]
@cammellos in a distributed system you can't really guarantee which message comes first though.
that is why I think that the root of the all issues is allowing ID generation on the sender side, because then it opens the whole can of worms of tampering/races/etc.

actually, the only place where we use these IDs externally is in replies. there, we need to guarantee that the user replied on what he has seen and that everyone will see it. hence, the idea to include the whole message content in the reply.

**Comment by mandrigin** [comment]
one thing that we absolutely have to guarantee about replies is that:
- if I see your message "do you like the first season of Stranger Things" and reply "Yes" to it, then
- everyone in the chatroom should see that I replied to that particular message

but that original message should be signed by the original author and the signature should be checked, of course

**Comment by cammellos** [comment]
> @cammellos in a distributed system you can't really guarantee which message comes first though.

Thanks, that I know :), it is exactly what appending the `pk` locally is preventing. it allow us to keep `id` generation flexible (we can change schema across version, new fields added are irrelevant, which is the main pain point), but still make sure order does not matter

**Comment by cammellos** [comment]
> but that original message should be signed by the original author and the signature should be checked, of course

If we sign the message content, then denormalizing the message in the reply just works yes

**Comment by yenda** [comment]
> actually, the only place where we use these IDs externally is in replies

we also use it in seen messages, and it will also be used for threads, reactions, and other kind of incoming features

**Comment by mandrigin** [comment]
> we also use it in seen messages, and it will also be used for threads, reactions, and other kind of incoming features

then we need to be bloody sure that we have a way to mention another message that is secure and compatible :-)

**Comment by rasom** [comment]
> If we sign the message content, then denormalizing the message in the reply just works yes

in this case, we will be able to reference messages from other chats btw. I mean even if a recipient  is not a member of that chat.

**Comment by cammellos** [comment]
@rasom that's just a matter of deciding what to include in the signature, you can include `chat-id` as well

**Comment by mandrigin** [comment]
Juat to document it there:
Keeping sha3 IDs might work just well if:
- on a sender we get sha3 of a messageafter it was serialized (raw payload bytes)
- on a receiver we get sha3 of a message before attempting to deserialize it (on raw payload bytes)

Whisper guarantees that the bytes we send are the bytes we receive. Hence, these hashes won’t depend on our interpretation/formats/etc.

**Comment by rasom** [comment]
We receive `hash` from `status-go` side, why can't we use it? I suppose that was discussed, but i don't remember the exact reason.

**Comment by rasom** [comment]
Probably because we can't calculate it before the message is sent or something. Well, we can calculate payload's hash.

**Comment by rasom** [comment]
In group chats we do not receive payload for the message specifically as it is wrapped via `GroupMembershipUpdate`. So the question is whether it's fine to use `GroupMembershipUpdate`'s payload for calculating id.

**Comment by cammellos** [comment]
@rasom for group chats  the payload of  actual chat message seems to be the safest choice, it means the message needs to be serialize just to calculate the id, but I feel is more consistent and allows us to recalculate ids for each message separately (comes in handy once/if we start syncing messages across devices etc)

**Comment by rasom** [comment]
ok, this means that we 
1) we need to lock down `Message` record and agree that its interface (specifically number and order of fields) can't be changed 
2) make sure that if we want to change these fields `v2.Message` record (or something like this) is created instead of changing existing one
3) make sure that `Message` can be handled by all next versions of the app since now

Otherwise, we will have compatibility issues again. Like we had when `Message`'s namespace was changed.

**Comment by cammellos** [comment]
Not sure, wait a second,
we want to take the hash of the serialized transit, not of the `Message` record (i.e. the bytes transmitted on the wire). If we add a field, the ID of that will change on the sender side, but the receiver will not parse it before creating the id, so the id will be the same. Because we use the non-parsed (the bytes received) object, so it should be fine to add/remove fields, or there's something I am not considering?

**Comment by rasom** [comment]
> @rasom for group chats the payload of actual chat message seems to be the safest choice

@cammellos do you mean the payload of `GroupMembershipUpdate` or it's `message` filed?

**Comment by cammellos** [comment]
the `message` inside, not `GroupMembershipUpdate`

**Comment by mandrigin** [comment]
I added this topic as a discussion point for the dev meeting today. Maybe we can just talk through all the edge cases that are left.

**Comment by rasom** [comment]
> we want to take the hash of the serialized transit, not of the Message record

correct, and right now we don't have serialized transit of the Message which is wrapped via `GroupMembershipUpdate `, or i'm wrong? The recipient will need to calculate it. Then we either need to send serialized transit of the message in `GroupMembershipUpdate`'s `message` field or guaranty that it can be calculated properly on the recepeint's side.

**Comment by cammellos** [comment]
> and right now we don't have serialized transit of the Message which is wrapped via GroupMembershipUpdate 

@rasom that's correct so just that we are on the same page, for a group membership update:

On sender size:

1) Create message payload
2) Serialize, calculate message-id, add to the database
3) Wrap in `GroupMembershipUpdate` and send

On receiver:

1) Extract inner message
2) Serialize
3) calculate message-id, Deserialize, add to the database

As opposed to for normal messages:

Sender flow:

1) Create message payload
2) Serialize, calculate message-id, add to the database
3) Send

Receiver flow:

1) calculate message-id, Deserialize, add to the database

**Comment by cammellos** [comment]
But yes, I see your point now :)

**Comment by cammellos** [comment]
Ok, probably best to stick to `message-id` calculate over `GroupMembershipUpdate`, as as you said new fields might pose the same problem.

**Comment by yenda** [comment]
Locking down the message format and having versioning is exactly what we had before and it was abandonned because it breaks forward compatibility for old clients

**Comment by cammellos** [comment]
> Locking down the message format and having versioning is exactly what we had before and it was abandonned because it breaks forward compatibility for old clients


Yes, if we use `GroupMembershipUpdate` we won't be locking down message format, while we would if we calculated the id using the inner message (as it needs to be deserialized, so new fields might not be available), it comes at some costs and wanted to avoid this, but for now seems to be the safest choice
