### ISSUE TITLE
To make styling of generated names bold for quote bubbles

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6959]
**User Story**

As a user, I want my generated names displayed in bold, comparing to the default 3-word name
As it's in the mockup:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/43638377/49282028-c4461880-f496-11e8-9f12-ef89095d166a.png">

Type: **Feature**

**Summary:** 
Currently, bold is user for generated names for regular messages, and not replies.

**Additional information:**
Status version: nightly 30/11/2018
Operating System: Mac OS
Original implementation - https://github.com/status-im/status-react/pull/6655
Designs - https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=134%3A1887

<blockquote><img src="/file/MRYBI5axcTwL4Ft8xAYhFOfy/thumbnail?ver=thumbnails/4aa1a96a-fbfc-444e-bc2b-23b78ad1873f" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by churik** [comment]
Irrelevant in terms of #7551
