### ISSUE TITLE
Use peer count as a definition for Online/Offline within status desktop

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#6961]
## Description

Currently, we rely on React Native's NetInfo API to check whether there is internet connectivity. On desktop, for instance, this presents a problem as by default react-native-desktop's NetInfo module uses `google.com` in order to check network connectivity.

## Solution
Although it is now possible to invoke `setConnectionCheckUrl()` on Desktop in order to set a custom URL, it would be better to instead rely on active peers count as a definition of being online.

**Comment by vkjr** [comment]
@siphiuel, I narrowed a bit scope for this issue, to fit desktop release.
@cammellos made a #7012 pr that fix all we need for desktop but it doesn't touch mobile wallet that still uses `NetInfo`. 

If we want to get rid from `NetInfo` in wallet, new issue can be added. (cc) @goranjovic

**Comment by vkjr** [comment]
#7012 merged, so closing this one
