### ISSUE TITLE
'Null is not an object located in group-chat-profile' app crash when deleting Group Chat from group info screen

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6963]
*Type*: Bug

*Summary*: App crashes when group chat member (admin or participant) deletes Group Chat via 'Delete Chat' option located at `Group info` screen.
Note: It's OK if delete group chat via 'Delete Chat` option from chat-menu options.

#### Expected behavior
After 'Delete chat' option submitted from 'Group info' screen: Group chat deleted and user navigated to Home screen. 

#### Actual behavior
'Null is not an object located in group-chat-profile' app crash when deleting Group Chat from group info screen

<img width="326" alt="screenshot 2018-11-30 at 13 09 28" src="https://user-images.githubusercontent.com/8749671/49285821-33286f00-f4a1-11e8-9603-f073b062c7c3.png">

### Reproduction

- Open Status and create new account (`Contact1(admin)`)
- Add any contact (`Contact2(member)`)
- Create 'Group Chat' with added contact
- Navigate by `Contact1(admin)` OR `Contact2(member)` from Group Chat screen to: top-right menu -> `Group info`
- Tap `Delete chat` option

### Additional Information
* Status version: Develop, release 0.9.32
* Operating System: Android and iOS

#### Logs

TBD....

**Comment by lukaszfryc** [comment]
Removing release label as it's already cherry picked into release/0.9.32.
