### ISSUE TITLE
Discover view Popular Tags as cards are difficult to swipe correctly

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#697]
When multiple Popular Tags are available on the Discover view, they appear as left-right scrollable cards you can flip through. As a design choice this isn't necessarily bad but in its present state could use some adjustment as it's easy to accidentally move to the Chats or Contacts view.

## Recommendations

* Make it more clear these cards are even there. I was unaware at first as left-right scrolling items within views only appears in this one part of the app.
* Give more space from the edge of the view by making the cards smaller.
* Reveal more of the out-of-view cards, ideally to the point where some text is cut off giving the user a visual clue that there is something there.
* Consider redesigning this element into its own view. Popular tags can be presented the same as every other grouped list if you drop the inner card content. Clicking a popular tag would then show what is currently on the card into its own view, bringing it closer in line to the rest of the app flows.

### Spatial Awareness Inconsistency

Additional to the above, there is a scenario with this element that may break the spatial awareness of the user. Steps to reproduce this scenario:

1. Go to Discover view.
2. Slide to the second or other cards (anything but first).
3. Tap any tag name, item, or user photo.
4. From this view, tap the back arrow to return to the Discover view.

The cards reset their position breaking the spatial awareness of the user. They will be thinking they are going back but the card they interacted with is not visible. Unless the user remembers where they were, they will have lost their place.

**Comment by annadanchenko** [comment]
Discover feature is removed
