### ISSUE TITLE
Update the colours and username display inside the mobile chat UI 

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#6979]
# Problem

As part of the ongoing work on UI components we've made some changes to the mobile UI that aim to unify it across all screens and products, this issue is related to introducing those changes into chat message UI.

# Implementation

![comparison](https://user-images.githubusercontent.com/4932774/49366766-70337200-f6ea-11e8-8832-ee920a1fdbf1.jpg)

### The scope of this task is related to two areas:
_Change of chat background from grey to white, and incoming messages from white to light blue, with some minor colour tweaks that go along with it. The purpose of that is unifying the visual design across all screens and mobile-desktop chat UIs_

- [ ] Change the chat background colour to white (#FFF)
- [ ] Change the Incoming message bubble background colour to Light Blue (#ECEFFC)
- [ ] Outgoing reply message, change the colour to 70% white (rgba 255,255,255, 0.7) of following:
- the quoted username colour 
- quoted text colour 
- the timestamp colour
 / _this is a fix, currently, the contrast ratio is too low there to be readable_
Incoming reply message, the 2px high underline below the quoted snippet should be 10% black (rgba 0,0,0 0.1)

_Change the way we render usernames inside chat to better distinguish between chosen username and 3w anonymous username_

- [ ] Chosen username, font-size 13px font-weight: 500, color: Dark Grey (#939BA1), line-height: 16px
- [ ] 3w anonymous name, font-size: 12px, font-weight 400, color: Dark Grey (#939BA1), line-height: 16px
- [x] change the :: characters to a bullet • (opt+8 on mac)
- [ ] 12px padding on the left, 16px on the right (the username begins at the same place as text inside message bubbles)
- [ ] the entire username should span the entire screen width and not only the message bubble (it can be wider than the message bubble)
- inside message replies, the entire quoted username should be truncated with ellipsis (…) if it overflows and doesn't fit in a line

# Acceptance Criteria

![screenshot 2018-12-03 at 11 21 16](https://user-images.githubusercontent.com/4932774/49368074-23ea3100-f6ee-11e8-8ea2-e7ae95900455.png)

All improvements were introduced as outlined [in this design](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1254%3A1791) 

thanks a bunch!

**Comment by rachelhamlin** [comment]
@siphiuel @yenda let's treat this one as a precursor to #7237 so that we can have correct styling.
