### ISSUE TITLE
The sidebar menu is probably unnecessary

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#698]
## Description

The flyout sidebar menu -- showing your user photo, current status, menu items -- is incomplete and duplicates functionality that's always visible. Adding an additional bottom menu item for settings and shifting the user profile off to the Contacts view could remove this menu altogether. Since it competes with the left-right swipes to move between main views, it might be worth killing it off.

## Observations & Recommendations

* Move the user identity to the top of the Contacts view as a prominent element that differs from the rest of the view (or place it in the absent Settings view or similar upon redesign). Does not need to take up much screen real estate, can be an alteration of what you see on the **Account Listing** ("Switch Users") view. Clicking this item would take you to a full view to inspect the users current identity, this view could double as a form and be more intuitive than having a form in a menu.
* Using the flyout menu to go to Discover and Contacts views is disorienting. Several elements slide around all at once and move in inconsistent directions depending on where you are in the app.
  * using the flyout menu from the Chats view to click "Discover" will slide flyout menu left and main app view **left** at the same time with different speeds.
  * using the flyout menu from the Contacts view to click "Discover" will slide flyout menu left and main app view **right** at the same time with different speeds.
  * there's no reason to go into the flyout menu to reach these main views, they're present in the bottom menu bar.
* The absent Settings view has no other position in the app at the moment. As I see it, this is the _only_ remaining reason to have the flyout menu.

**Comment by jarradh** [comment]
In it's current form you're probably right, the menu items there are largely placeholders, I don't think we should get rid of it though because I believe it will be immeasurably useful in the future, for example we can show pending transactions and overall balance in here instead, and I love the ability to quickly update my Status. Imagine this flying out instead of the transaction screen, this could be part of the redesign in #700

**Comment by andmironov** [comment]
Nice points, thanks a lot!
So we clearly need a special space where we can:
- Update status;
- List the latest transactions;
- Switch accounts;
- Edit profile;
All of these relate to each other and form a special "personal space" which is not necessary a Drawer
