### ISSUE TITLE
85,2 GB size is shown in Control Panel for Status app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6981]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see real size of installed programs.
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  wrong size of Status Desktop is shown in Control Panel > Programs and Features - instead of real size is shown 85,2 GB

#### Expected behavior
real size of app

#### Actual behavior
85,2 GB is shown
![size](https://user-images.githubusercontent.com/4557972/49370142-a0cbd980-f6f3-11e8-8a84-4ac30a04d311.png)

### Reproduction

- Download and install Status 
- Open Control Panel > Programs > Programs and features
- Check out Status Desktop size

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 30/11/2018
[comment]: # (Android or iOS.)
* Operating System: Windows 10 home

**Comment by oskarth** [comment]
Is this definitely only Windows?

cc @PombeirP

**Comment by churik** [comment]
@oskarth on Mac OSx app size is 353,2 MB - I believe it is right.

**Comment by pedropombeiro** [comment]
@oskarth I've seen this issue on other Windows apps in the past. It could be related to NSIS, or the actual install script itself. I based myself on the script used by some well-known app (not sure if Winamp) and trimmed/adapted it for our needs. It seems to be purely aesthetical, so for the initial version I didn't bother to spend much time looking into solving that.

**Comment by churik** [comment]
Still relevant
