### ISSUE TITLE
Enable group chats in nightlies by default

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6982]
### Description

*Type*: Bug

*Summary*: Let's move group chats to a next testing stage and enable them in nigtlies. Currently, they are available only after dev mode is on. Enabling them by default would allow for easier access and simplify e2e test automation (https://github.com/status-im/status-react/issues/6884).  

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@cammellos could you help here?

**Comment by cammellos** [comment]
@lukaszfryc should be already in https://github.com/status-im/status-react/commit/5795ca8d1a58ff3e7efbefa1e4c2f9b509e7e9ec ?

**Comment by lukaszfryc** [comment]
Ah, true. I used old nightly. Thanks!
