### ISSUE TITLE
Improve replies and copying messages on desktop with context menus

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6985]
# Problem

A recent desktop hack introduced replies via left click and copying via right click because there wasn't an ability to use context menus.  But now there are so we can fix this!

# Implementation

The current left/right click functionality should be removed.  New functionality:

Right click on a message. A menu shows:
- "Reply"
- "Copy message"

# Acceptance Criteria

- Left/right click implementation is gone
- Implementation above is implemented and tested

# Notes

n/a

# Future Steps

None

cc @siphiuel

**Comment by vitvly** [comment]
Closed in #6994
