### ISSUE TITLE
Profile fields are not easily understandable to average users

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#699]
## Description

Hash and hex values are understood by some users 🤓 but not most users 😕. Even among the 🤓 users, there is common misinterpretation and mishandling of these kinds of values. The presentation of these values in the app is intimidating to 😕 users, may even appear like the app is breaking by showing them.

The Console app is an ideal candidate for explaining these concepts to the user when they first join, but otherwise the app should introduce these concepts to the user so they feel equipped to manage them.

Additionally, the Phone Number being a privacy field conflates the meaning of these values. It's not clear if the phone number is exposed to other users or if the address and public key can be discovered by other means.

## Questions the user may have ...

* Is it safe to share these values with strangers or is this for my eyes only?
* Does sharing these values expose me to any risks?
* What are some situations where I would want someone to scan these values?
  * Is this the only way you can friend someone?
  * Can I get a URL of these values to send to someone or do I need to travel to them?
  * QR scans of mobile devices is an intimate interaction, these are personal devices. If there are times a QR scan will be used in a privacy-oriented manner, it's important to reinforce safe behavior so the user has confidence in their actions.

**Comment by jarradh** [comment]
I agree with all of these points, for example we encounter the address vs public key thing quite often. Which stems from us wanting to use the same keypair in both Whisper & the Blockchain, something I'm not willing to compromise on, but we definitely need.

One thing we could do here is only rely on public key for Status and let the wallet display address, which would be cleaner, but there is the issue of people sharing a public key with other mobile wallets, if we don't implement the shortened public key then maybe other wallets will through error with such a long string.

In any case we hope to hide alot of this once we have a better path forward with usernames and identity #669

**Comment by rabbit** [comment]
Another option might be to find a clever way to mask it as a visual element. Copy a value to clipboard by tapping a key icon or name tag icon. The QR view already displays the value if a user wants to check it and a QR is as opaque as a hash. You could also combine the two into a single QR by combining key and address but that contradicts your need to access the individual values.
