### ISSUE TITLE
User's image is a square when replying to their message, not a circle

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6999]
Type: **Bug**

Summary: On desktop, when replying to a message of the user, in reply bubble in message input area, that icon is displayed as a square, not a circle.
It's especially visible when there's a profile icon set.

Reported separately from https://github.com/status-im/status-react/issues/6216 , since it's not an inconsistency with design.
I could not find any design references for this on , https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=0%3A1 but it should be consistent with mobile.

**Expected behaviour**

The icon displays as the circle (the same as in the chat) for mobile (iOS and Android)

<img width="433" alt="image" src="https://user-images.githubusercontent.com/43638377/49443496-499e3580-f7d5-11e8-9492-50241fb3a691.png">

**Actual behaviour**

The icon displays as a square (original image used), and looks inconsistent

<img width="680" alt="image" src="https://user-images.githubusercontent.com/43638377/49443473-3be8b000-f7d5-11e8-9954-67b314074c6e.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/43638377/49443644-a7cb1880-f7d5-11e8-8256-d67e6fa2820e.png">

**Reproduction:**

1. Open desktop app on device A
2. Start 1-1 chat/join a public chat with a user who has a profile icon set 
3. Click on the message to quote it

<blockquote><img src="/file/MRYBI5axcTwL4Ft8xAYhFOfy/thumbnail?ver=thumbnails/fac994be-9ef2-40fb-927a-73fd39d0041d" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by churik** [comment]
@SlizkovaGanna would you mind to add info to https://github.com/status-im/status-react/issues/6216 and close this one?
We already have task about missing design on replies on desktop, I don't see any reason to have several issues about it

**Comment by SlizkovaGanna** [comment]
@churik like I've mentioned in the description, my logic was that it's not inconsistency with the design -  icons are not described in the mockups.
But I don't mind adding it as a separate comment in https://github.com/status-im/status-react/issues/6216
Closing this one.
