### ISSUE TITLE
Multiple transactions in transaction screen is not obvious

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#700]
## Description

The transaction confirmation dialog uses a sliding cards style interface to stack multiple transactions together. Even advanced users are likely to ignore the content of these transaction boxes, seeing them as paranoia spot checks rather than standard confirmation dialogs.

This problematic situation is compounded with a bug that registers multiple transactions when only one transaction was intended by accidentally tapping a command submit button more than once before the transaction confirmation dialog presents itself. The card style interface obscures the fact that multiple transactions were accidentally added. In the case of `send` commands, this will repeatedly send the given amount of ether for every accidental tap beyond the first tap.

## Reproduction

[iOS]

1. Begin a chat session with a user.
2. Activate the `send` command to bring up the numpad interface.
3. Input a value of `1`
4. Quickly and deliberately tap the submit button 3 times then wait.
5. Confirm the action to complete the command.

## Observation

1. The transaction confirmation dialog obscures the presence of 3 pending transactions because of the card style interface.
2. When the command fires, 3 distinct `send` actions will appear in chat.
3. An attempt to send `1` ether results in sending `3` ether.

## Expectation

You know. 😜

**Comment by rabbit** [comment]
@jarradh critical issue.

**Comment by jarradh** [comment]
This screen is designed to take multiple transactions, there is a problem that we can't have sendTransaction as blocking, when you are potentially running multiple dapps at a given time. 

I would recommend mandating a scroll through the pool of pending transactions before we allow the user to sign them, and give the user very clear indications on how to

**Comment by rabbit** [comment]
The title of this issue is maybe misleading. I don't mean to suggest the issue is stacking commands or having multiple transactions. That's necessary. Only that the presence of multiple transactions was not obvious.

**Comment by jarradh** [comment]
I actually thought you were referring to our previous 'staging' area which stacked commands before being sent to the chat (which we have since removed) and maybe had reared it's ugly head again

**Comment by jarradh** [comment]
Also I want to do the same thing as Parity does with the transaction screen, that is Console sends the user a very specific pattern as an image, this visual pattern won't be known to DApps so will be hard to fake, if put in the transaction screen - the user can look for this pattern to determine screen authenticity

**Comment by rabbit** [comment]
I assume the multi tap bug is present elsewhere in the app but chose to demonstrate it by unintentional loss of ether. Clarifying this just in case it got lost from renaming the issue.

Tapping a command submit action, to invoke the transaction confirmation, should only register the first tap instead of queuing a transaction per tap. I shouldn't have combined that issue with my thoughts on how the transaction confirmation exacerbates the problem.

**Comment by jarradh** [comment]
#698
