### ISSUE TITLE
Add Jenkins release build for desktop

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#7001]
# Problem

Jenkins can have separate build for desktop releases that has tweaked settings. For example - disabled logging, disabled wip features. 
Also that build can upload results here - https://github.com/status-im/status-react/releases

# Implementation

- Add new jenkinsfile for desktop release
- Add Jenkins job for releasing to GitHub https://docs.fastlane.tools/actions/set_github_release/

# Acceptance Criteria

Jenkins has option to build desktop release build.

# Notes
Existing jobs:
- [Release job](https://ci.status.im/job/status-react/job/release/)
- [iOS release and upload](https://ci.status.im/job/status-react/job/upload_release_ios/)
- [Android release and upload](https://ci.status.im/job/status-react/job/upload_release_android/)

**Comment by chadyj** [comment]
Let's use the Fastlane action to upload to Github :)
https://docs.fastlane.tools/actions/set_github_release/

<blockquote><img src="../../img/favicon.ico" width="48" align="right"><div><strong><a href="https://docs.fastlane.tools/actions/set_github_release/">set_github_release - fastlane docs</a></strong></div></blockquote>

**Comment by chadyj** [comment]
@jakubgs is this something you could help us with please?
