### ISSUE TITLE
Rename hardwallet to keycard

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#7004]
# Problem

As new name for the Keycard project was chosen, it's time to rename "hardwallet" to "keycard" in the code and in UI as well. This would also help to avoid confusion, as related projects (Android SDK, react-native SDK wrapper) are already using "keycard" naming.

# Implementation

No logic should be changed, just renaming.

# Acceptance Criteria

No "hardwallet" mentions in status-react codebase.

# Notes

This PR should be merged first https://github.com/status-im/status-react/pull/7003

# Future Steps

None

**Comment by guylouis** [comment]
can this be closed, or should we keep it for tracking ?

**Comment by dmitryn** [comment]
Let's close it
