### ISSUE TITLE
Show progress during applet installation

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#7005]
# Problem

Keycard applet installation takes ~20 seconds. During the process we only show spinning circle indicator so it's not clear how much time left.

# Implementation

We could show progress bar or percentage number. 

Installer could emit events to status-react signaling the step it's currently on.

# Acceptance Criteria

Show progress bar or percentage number during applet installation.

# Notes
Installer code
https://github.com/status-im/react-native-status-keycard/blob/master/android/src/main/java/im/status/ethereum/keycard/Installer.java#L38 

Emit events example https://github.com/status-im/react-native-status-keycard/blob/master/android/src/main/java/im/status/ethereum/keycard/SmartCard.java#L112

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-status-keycard">status-im/react-native-status-keycard</a></strong></div><div>Contribute to status-im/react-native-status-keycard development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-status-keycard">status-im/react-native-status-keycard</a></strong></div><div>Contribute to status-im/react-native-status-keycard development by creating an account on GitHub.</div></blockquote>

**Comment by denis-sharypin** [comment]
Hey @dmitryn could you please check out is it possible in RN to use this indicator: https://material.io/design/components/progress-indicators.html#linear-progress-indicators
Particularly, this one `Determinate linear progress indicator`

<blockquote><img src="https://material.io/design/https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1yvwYX4JFBeviyHyb7ctX9ZDEhnQ1J7RZ%2Fprogress-thumbnail-2x1.png" width="48" align="right"><div>Material Design</div><div><strong><a href="https://material.io/design/components/progress-indicators.html">Progress indicators</a></strong></div><div>Progress indicators display the length of an operation or visualize an unspecified wait time.</div></blockquote>

**Comment by dmitryn** [comment]
@denis-sharypin we can use built-in https://facebook.github.io/react-native/docs/progressbarandroid which looks similar.

![screenshot_20181217-135856](https://user-images.githubusercontent.com/23836/50083302-5b83cd80-0204-11e9-9446-1dca51e0b47f.png)




<blockquote><img src="/react-native/img/favicon.png" width="48" align="right"><div><strong><a href="https://facebook.github.io/react-native/index.html">ProgressBarAndroid · React Native</a></strong></div><div>Android-only React component used to indicate that the app is loading or there is some activity in the app.</div></blockquote>

**Comment by denis-sharypin** [comment]
Looks good to me!

**Comment by asemiankevich** [comment]
looks good to me
![image](https://user-images.githubusercontent.com/28752642/50400307-cbf79500-0796-11e9-9c55-22d5fbd55e37.png)
