### ISSUE TITLE
Unable to modify phone number in profile

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#701]
## Description

Two odd issues here. First is going into the users profile and tapping on the phone number makes the text smaller for no apparent reason. Second is editing the profile, it appears the number can be modified but accepts no input.

This also caused the app to freeze first I encountered it then unfroze itself sending me to the Chats view (I was tapping around, it maybe locked up and later registered a tap on the back arrow to exit). I was unable to reproduce this freezing issue. Maybe related to editing the phone field initially.

**Comment by jarradh** [comment]
I think we need to re-work the whole phone thing, the reason changing mobile isn't editable in the profile is that it shouldn't be changed without going through the verification process, I agree that it is weird - in the very least it should lead back to Console doing a `!phone` request

**Comment by jumarko** [comment]
I wanna look into this...

**Comment by jumarko** [comment]
I've submitted a pull request: https://github.com/status-im/status-react/pull/770#pullrequestreview-18884853
@jarradh please take a look at it - check my comments/questions.
Thank you.
