### ISSUE TITLE
Wallet balance is shown as 0 when having more than 76 assets enabled in portfolio

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7016]
### Description

*Type*: Bug

*Summary*: Wallet balance is shown as 0 when having more than 76 assets enabled in portfolio

#### Expected behavior

As a user i want to see my balance with respect of enabled assets in portfolio

#### Actual behavior
Wallet balance is shown 0 if more than 76 assets are enabled (thanks @churik for investigation)

### Reproduction

- Open Status
- Recover account with some funds and make sure balance is more than 0
- Enable 77 assets in portfolio (+75 if you have ETH and SNT already for ex)
- Pay attention to the balance

**Comment by goranjovic** [comment]
wow, good catch

**Comment by asemiankevich** [comment]
can't reproduce anymoe
