### ISSUE TITLE
Improve readability of user's ID in chat message area

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#7020]
## Description
*Type*: Bug

User identifier (display, random or ENS name) are not highlighted enough, that makes it hard to scan the list of messages and identify who is saying what.

<img width="680" alt="captura de pantalla 2018-12-05 a la s 7 35 41 p m" src="https://user-images.githubusercontent.com/37297779/49548612-0f13c600-f8c5-11e8-8081-005a5a640ce4.png">

## Expected behavior
Primary identifier (display name, random name or ENS name) should be highlighted using the correct styles.

<img width="527" alt="captura de pantalla 2018-12-05 a la s 7 46 26 p m" src="https://user-images.githubusercontent.com/37297779/49549095-80a04400-f8c6-11e8-8e04-0a563d07c364.png">

## Solution
- [ ] Include InterUI semibold](https://rsms.me/inter/) (font-weight: 600) to our library
- [ ] Highlight main user identifier in chat area[ following the correct styles ](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=728%3A41)

[See designs on Figma](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=728%3A41)

<blockquote><img src="https://rsms.me/inter/res/poster.png" width="48" align="right"><div><img src="/inter/res/favicon.png" height="14"> rsms.me/inter</div><div><strong><a href="https://rsms.me/inter//">Inter UI font family</a></strong></div><div>Inter UI is a new typeface optimized for computer user interfaces</div></blockquote>

**Comment by churik** [comment]
Can be closed because of #7551
