### ISSUE TITLE
PFS and missing contact information for 1:to:1

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7025]
# Problem

Once  we enable PFS there might be some instances where it won't be possible to establish a PFS connection between two peers, due to the fact that a bundle is not available.

In such cases https://discuss.status.im/t/pfs-and-missing-contact-information/362 flow will take place.

This task will consist in:
1) Minimize the times a bundle is not available
2) Implement the UX flow when a bundle is not available.

<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/pfs-and-missing-contact-information/362">PFS and missing contact information</a></strong></div><div>Hello,  PFS relies on a piece of data to be exchanged between the users to allow a “secure channel” to be established (any messages exchanged through a secure channel have pfs properties).  A secure channel can be established currently in a few ways:   Through public chats Through contact codes  Which means that if you send a direct message to a user who you added through a contact code (we changed the format), or you have received a message from the user in any public chat, the app works exactl...</div></blockquote>

**Comment by oskarth** [comment]
^ @hesterbruikman @corpetty FYI

**Comment by oskarth** [comment]
@cammellos what's the state of this?

**Comment by cammellos** [comment]
@oskarth working on it now, https://github.com/status-im/status-react/pull/7702 , so should be re-opened
