### ISSUE TITLE
PFS and group chats

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7026]
Currently PFS is only guaranteed for the initial group, but messages sent by members who joined at later stages might not have this property.
PFS should hold for all messages in a group chat.

**Comment by oskarth** [comment]
^ @hesterbruikman @corpetty FYI

**Comment by oskarth** [comment]
@cammellos what's the state of this?

**Comment by cammellos** [comment]
Currently pfs is guaranteed for the initial group, but not for members who have been added after, that still needs working, I will update the description

**Comment by rachelhamlin** [comment]
This is still relevant and true, right, @cammellos?

**Comment by cammellos** [comment]
This is still relevant, but won't be addressed any time soon, it's the same for 1-to-1 chats and it's all described in the specs, it will require some input from ux if we want to address this (implement some contact request flow before user can exchange messages etc)

**Comment by cammellos** [comment]
Closing this a
