### ISSUE TITLE
9999 instead of 2018120610 is shown in About for iOS version on TestFlight

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7027]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For iOS app installed from TestFlight about contains 0.9.32(9999) as version instead of 0.9.32(2018120610)

![img_2546](https://user-images.githubusercontent.com/6584810/49587889-85680500-f965-11e8-98f2-6bd9fdbb02b7.jpg)

**Comment by jakubgs** [comment]
How was this built? Maybe a link to the artifact and the Jenkins build?

**Comment by annadanchenko** [comment]
https://ci.status.im/job/status-react/job/upload_release_ios/63/consoleFull

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/upload_release_ios/63/consoleFull">status-react » upload_release_ios #63 Console [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
RIght, because for some reason we still keep using these separate jenkinsfiles that are not supported or maintained.
https://github.com/status-im/status-react/pull/7028 - temporary fix

We need to stop using that and use the main `Jenkinsfile` with the `release` flag.
