### ISSUE TITLE
Warn the user when they are accessing an insecure app url

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#703]
## Description

It's currently possible to open a non-ssl url. This creates a situation where a user may rightly trust the app but wrongly trust that their connection to that app is secure, exposing them to attacks such as a mitm replacing contract addresses. At the **very** least, a user should be encouraged very strongly to never use non-ssl app connections. If it's possible to deny them outright, I would recommend it at least until there has been sufficient time to find ways to protect the user in these situations.

**Comment by jarradh** [comment]
We need to think of how best we should highlight the use of `http://`, ideally I would prefer without much intrusion into what the user is doing, I do like the idea of treating `https://` as 'normal' and having a negative associative colour to `http`
