### ISSUE TITLE
[EPIC] Improve mobile app navigation and DApp discoverability

### ISSUE THREAD

**Issue by jpbowen** [status-im/status-react#7030]
# Problem

Discoverability of DApps and other key features in the mobile app have been documented in usability testing, [#5802](https://github.com/status-im/status-react/issues/5802) and proposed solutions are currently underway in WP3 and will be within the scope of work for WP5 in December 2018. 

The proposed solution addresses ongoing user feedback and findings from UXR such as: 
- Path to switching modes (e.g. Wallet -> DApps) is unclear 
- Lack of consistent UI element to refer to for app navigation
- Unclear how to start a new chat with a new or existing contact
- Separating DApps entry point from a submenu and bringing back to the main nav bar 

More context on current efforts are in:
- [Design Work Package 3](https://docs.google.com/presentation/d/1AKhBTvnMS9VtV1_YUTZCTsM7VoXbn7I5xNDSU3hlMBs/edit#slide=id.g4200462503_0_252)  

# Implementation
- WIP (TESTING NEEDED!) [Figma design explorations](https://www.figma.com/file/deXIBZm6fU1CCL0voYbfTujz/Navigation?node-id=1%3A2) by @errorists 

[Epic project board](TBA)
- [] User test (A/B) at least two different versions of app navigation
- [] Main screen restyle to have a persistent nav bar ... 
- []

# Future Steps
- UXR testing to A/B/C test explorations of app nav determined by WP5
- Improvements based on testing

**Comment by rachelhamlin** [comment]
New issue here: https://github.com/status-im/status-react/issues/7534
