### ISSUE TITLE
[Question] How to import/export to MetaMask?

### ISSUE THREAD

**Issue by asddsaz** [status-im/status-react#7034]
**Question**: How would I import my Status account to MetaMask? Is it possible to import my MetaMask account to Status?

**Comment by annadanchenko** [comment]
@asddsaz in Status mobile app open Profile -> Backup your recovery phrase -> tap "Ok, continue" to get recovery phrase with 12 words shown. These 12 words is your seed phrase that can be used to recover account in MetaMask or other wallet. 

![img_2575](https://user-images.githubusercontent.com/6584810/49956589-d8156400-ff05-11e8-82e5-5c138c85efcc.jpg)

Example of my test account recovery phrase, yours will be other 12 words:
![img_2577](https://user-images.githubusercontent.com/6584810/49956639-f4190580-ff05-11e8-98fb-ba094456e711.jpg)



### Before exporting account to MetaMask
Make sure you wrote down recovery phrase or any other way to restore your existing accounts in MetaMask. See https://metamask.zendesk.com/hc/en-us/articles/360015489431-Exporting-Your-Seed-Phrase for instructions. It's important to have seed phrase saved to be able to restore your account(s) in the future. If you didn't save it I would not recommend to proceed with instructions below.

### To export from Metamask
1. In Metamask log in to the account you want to export
2. Open Settings (can be found by clicking on Account icon in top right corner)
<img width="1154" alt="screen shot 2018-12-13 at 18 41 00" src="https://user-images.githubusercontent.com/6584810/49957534-71de1080-ff08-11e8-9bfe-7cde2ec69ec6.png">
3. On Settings tab scroll down to button "REVEAL SEED WORDS" and click it

<img width="1164" alt="screen shot 2018-12-13 at 18 41 12" src="https://user-images.githubusercontent.com/6584810/49957596-9d60fb00-ff08-11e8-94f8-0245b651325e.png">

4. Enter password and click button Next. As a result, you should see screen with "Your private seed phrase" that consists of 12 words, here is example for my test account:

<img width="1104" alt="screen shot 2018-12-13 at 18 41 33" src="https://user-images.githubusercontent.com/6584810/49957698-e9ac3b00-ff08-11e8-934a-b7eedef88db7.png">

5. Write down these words (it's not recommended to store it in digit form anywhere else as anyone who knows these words will get access to your account)

6. In Status app log out from the account if you are logged in (Profile -> Log out)

7. On  screen "Sign in to Status" tap on link "Other accounts"
![img_2578](https://user-images.githubusercontent.com/6584810/49957958-bae29480-ff09-11e8-9240-f074f16b572a.jpg)

8. On screen "Sign in to Status" tap on link "Add existing account"
![img_2579](https://user-images.githubusercontent.com/6584810/49957993-d2ba1880-ff09-11e8-9db3-a505da8fae47.jpg)

9. On screen "Sign in to another account" type 12 words of you MetaMask seedphrase into field "Recovery phrase" and any password longer than 6 chars to log into the account later
![img_2580](https://user-images.githubusercontent.com/6584810/49958022-e6657f00-ff09-11e8-9835-a36ebc4ff52d.jpg)

10. Wait for Home tab to be shown it will mean that account is recovered. You can check it's the same account by comparing account address. In Status app it's shown in Wallet -> Deposit

### To import to MetaMask:
1. In MetaMask logout from any account if you are logged in
2. On "Welcome Back!" screen use link "Import using account seed phrase"
<img width="1139" alt="screen shot 2018-12-13 at 18 15 22" src="https://user-images.githubusercontent.com/6584810/49955840-1e69c380-ff04-11e8-9339-80b8d934b547.png">
3. On the screen "Restore your Account with Seed Phrase": type 12 words into field "Wallet Seed" and any password you want to access your account in MetaMask into fields "New Password" and "Confirm Password" (it's not mandatory to have same password as in Status app).  Below is an example for my test account seed phrase. Your's phrase can be found in Status app -> Profile -> Backup your recovery phrase -> tap "Ok, continue" 
<img width="1180" alt="screen shot 2018-12-13 at 18 25 38" src="https://user-images.githubusercontent.com/6584810/49956153-cc756d80-ff04-11e8-80c9-a66d08fc7153.png">
4. Click on button "Restore"
5. As a result, you'll get access to the account that was restored with provided seed phrase. You can validate that it's the same account as in Status app by checking its address. In Metamask it's written under Account 1, Details: "0x3f16...3C94". It should be the same one shown in Status app -> Wallet -> Deposit. E.g in my case it's "0x3f165393215decf76e056B58f0bdB2aF702E3C94"
<img width="1153" alt="screen shot 2018-12-13 at 18 28 39" src="https://user-images.githubusercontent.com/6584810/49956282-1e1df800-ff05-11e8-881f-09bcb535061f.png">




<blockquote><img src="https://theme.zdassets.com/theme_assets/2313093/b11710669121937fbc14ceec3cbe07855e36c8f8.png" width="48" align="right"><div>MetaMask</div><div><strong><a href="http://metamask.zendesk.com/hc/en-us/articles/360015489431-Exporting-Your-Seed-Phrase">Exporting Your Seed Phrase</a></strong></div><div>When initially setting up your MetaMask account, you are prompted several times to confirm that you've copied down your seed phrase as it is the ultimate and only reliable way to recover your accou...</div></blockquote>
