### ISSUE TITLE
[Fetching messages] dialog is shown for all the time running app

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7035]
### Description

*Type*: Bug

*Summary*: Persistent [Fetching messages] dialog appears

#### Expected behavior

[Fetching messages] dialog disappear when messages are fetched

#### Actual behavior
[Fetching messages] dialog is shown all the time running the app

![image](https://user-images.githubusercontent.com/28752642/49633159-615dff80-fa09-11e8-947a-2ea15a8ea388.png)

**Comment by asemiankevich** [comment]
@cammellos maybe you have an insight here?

**Comment by cammellos** [comment]
@asemiankevich only theories but the best I have got so far is that there are a lot of messages in the `discovery-topic` and that requests takes long to process and it's called multiple times, basically going back to asking for the full day
