### ISSUE TITLE
No protocol method Hook.hook-in defined for type null: at login with enabled not-supported extension (/collectible)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7037]
### Description

*Type*: Bug
*Summary*:  added extension with  /collectible chat command (did ~ 2 weeks ago on 0.9.31) and after upgrade to 0.9.32 got an error `No protocol method Hook.hook-in defined for type null: `. Error appears every time after login.
If /collectible extension is not supported anymore (I think so because don't see it in https://notes.status.im/roft7IJFRyW66E5mF23PVQ?view), I believe we should at least warn users somehow about it and suggest to delete it or mark as inactive.
NOTE: when I switched off this extesion, I still can see this error;  only deletion helped.

#### Expected behavior
no error; can see command /collectible in 1-1 chat OR I warned that extension shouldn't work.

#### Actual behavior
`No protocol method Hook.hook-in defined for type null: ` after log in
![2018-12-07 10 40 31](https://user-images.githubusercontent.com/4557972/49639938-843de300-fa0c-11e8-9c6e-f28fa713654c.jpg)

### Reproduction

- Open Status with enabled /collectible extension 
- Log in

### Additional Information
* Status version: 0.9.32 
* Operating System: Android, iOS

<blockquote><div><strong><a href="https://notes.status.im/roft7IJFRyW66E5mF23PVQ?view">Chat commands - CodiMD</a></strong></div></blockquote>

**Comment by churik** [comment]
@jeluard WDYT?

**Comment by jeluard** [comment]
Yes might make sense to handle this gracefully, even so it shouldn't happen in the future.

**Comment by jeluard** [comment]
@churik Should be fixed now. Please reopen if you can still reproduce :)
