### ISSUE TITLE
AppImage binary is ~242 MB 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7041]
AppImage file for Linux is ~242 MB, which  is 2 times more than .dmg and .exe.
Expected size ~120 MB

<img width="330" alt="nightly status-react jenkins 2018-12-07 14-11-36 1" src="https://user-images.githubusercontent.com/4557972/49650095-72b80380-fa2b-11e8-958e-bb8f039324a4.png">

**Comment by chadyj** [comment]
@MaxRis @vkjr Can you please take a look at this? 

@3esmit commented about a nested app image:

> Noticed something strange in AppImage… there is StatusIm.AppImage inside Status.AppImage, this inner AppImage also contains a ubuntu-server.

**Comment by maxhora** [comment]
Will look into this

**Comment by maxhora** [comment]
@jakubgs could you please help upload [updated zip package](https://drive.google.com/file/d/1HSIR_C-eHEmw3ees3QNnaCaq5dahHBGj/view?usp=sharing) to ams3.digitaloceanspaces.com. The idea is to replace old one from [here](https://github.com/status-im/status-react/blob/develop/scripts/build-desktop.sh#L279) to new one uploaded.
The difference is the only file `Status.AppImage` removed from the old archive. That file seems got there by mistake, but doubles the size of final produced package with no sense.

**Comment by jakubgs** [comment]
~~How can I download it? It just opens the zip on the site.~~
Ah, found the button.

**Comment by jakubgs** [comment]
Here: https://desktop-app-files.ams3.digitaloceanspaces.com/StatusImAppImage_20181208.zip

BTW, can we automate the building and uploading of this image?

<blockquote></blockquote>

**Comment by maxhora** [comment]
@jakubgs thanks a lot! going to give it a try

[there is](https://github.com/status-im/status-react/issues/6175) on-going work to remove dependency on `ubuntu_server` and `node_modules/realm`'s Node.JS native module. Ideally, these packages will disappear completely. Hopefully, soon :)

**Comment by jakubgs** [comment]
Glad to hear that!

**Comment by maxhora** [comment]
Thank you @3esmit , @churik , @chadyj  for spotting this issue! @jakubgs thanks a lot for efforts to resolve it!
