### ISSUE TITLE
Show sender in mobile push notifications when db is unlocked

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#7043]
# Problem

Currently, PNs are created very generically with `:notifications-new-message-title` as the title and `:notifications-new-message-body` as the body.

# Implementation

We should try to match the sender of the PN with a contact, and if found we should use that as the body instead of `:notifications-new-message-body`. This is to be done in `handle-on-message` in `src/status_im/notifications/core.cljs`.

# Acceptance Criteria

If the user has the receiving account unlocked in his device and receives a PN from a contact, he should see the name of the contact in the PN body. Otherwise, the behavior stays the same as currently.

# Future Steps

In the future, we'll want to start calling `setNotificationId` on notifications so we can update them with the contact names once the account is unlocked.

**Comment by StatusSceptre** [comment]
Is this issue still relevant? @PombeirP

**Comment by pedropombeiro** [comment]
Yes, coincidently I just filed a PR for it today: https://github.com/status-im/status-react/pull/7383
