### ISSUE TITLE
Navigate to message matching partial IDs in mobile push notifications when PN is tapped

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#7044]
# Problem

Currently, we're sending partial hashes of pubkeys in `from` and `to` in the PN payloads. The goal is to add an `id` field containing the last 4 bytes of the message ID (which itself is currently `sha3(from + raw-payload)` so that we can later do a linear lookup at the receiving client to find the message again, without giving away too much in terms of privacy/darkness.

# Implementation

If `msg.id` field is present in PN payload when `handle-on-message` is called, pass it to `chat-model/navigate-to-chat` and try to find and navigate (scroll) to message.

# Acceptance Criteria

Currently PNs will likely arrive much sooner than the Whisper message (especially if the account is locked). In order to test this functionality, we should:
1. Receive PN with `msg.id` field;
1. Unlock target account so that it can receive the Whisper messages;
1. Once messages are received, tap on PN and verify that it navigates you not only to the correct chat (existing behavior) but scrolls to the correct message inside the chat.

# Future Steps

We'll want to implement #3451 so that everything happens automatically even if the app was locked at the time we tapped the PN (i.e. app will ask us to unlock account, fetch messages and once message with correct ID is received, navigate to it)

**Comment by StatusSceptre** [comment]
Is this issue still relevant @PombeirP

**Comment by pedropombeiro** [comment]
To me it makes perfect sense, not to have to guess which message the PN actually refers to once you tap it (will become even more important once we start showing the message contents on the PN).

**Comment by StatusSceptre** [comment]
thoughts on pricing?  I'll fund it then.

**Comment by pedropombeiro** [comment]
@StatusSceptre not sure I follow, isn't pricing standard? The issue is already marked as M size. at first thought, this should be relatively straightforward for someone familiar with RN and Clojure, but I'm almost sure issues will appear with programmatic requests to scroll the view, hence the M size.

**Comment by StatusSceptre** [comment]
@PombeirP pricing isn't necessarily standard.  Typically a M bounty can be funded automatically and ranges from 150-400 with most of the time it just being set to 300.  That is quite a range, and should be up to the CC to choose.  These ranges are in flux as we tune the gitcoin bounty process as all work isn't the same.

**Comment by StatusSceptre** [comment]
@PombeirP - Hi Pedro, this seems like it may have been missed - does this still need to be funded?

**Comment by pedropombeiro** [comment]
@StatusSceptre oops, I forgot to get back to you on this. I'd say this is probably a low L, because of the amount of testing required to ensure that the functionality works, as well as the scrolling functionality (which is always a potential source of surprises in any project).

**Comment by churik** [comment]
don't think it is still relevant. 
@rachelhamlin reopen if it is
