### ISSUE TITLE
Group mobile push notifications by sender

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#7046]
# Problem

Currently, push notifications are not grouped (even though we call `setGroupSummary`), so the user potentially ends up with a ton of push notifications in the notification center.
 
# Implementation

We should:
- maintain a summary PN with a fixed ID
  - we call `setNotificationId` on it so we can update it later without creating a new one. Maybe the sender ID hash (`from`) can be used as the parameter so that we group by sender.
  - we call `setGroupSummary true` to mark it as the summary
- for both the summary and the individual message PNs, we call `setGroup` with a concatenation of `group-id` and the sender hash (e.g. `(str group-id "-" from)`)

Relevant documentation:
- https://developer.android.com/training/notify-user/group
- e.g. `AndroidNotification.md` in https://github.com/invertase/react-native-firebase-docs/tree/master/docs/notifications/reference

# Acceptance Criteria

PNs are grouped by sender in both Android and iOS.

<blockquote><img src="https://developer.android.com/_static/954bdbf227/images/android/favicon.png" width="48" align="right"><div>Android Developers</div><div><strong><a href="https://developer.android.com/training/notify-user/group">Create a Group of Notifications  |  Android Developers</a></strong></div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/13588260?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/invertase/react-native-firebase-docs">invertase/react-native-firebase-docs</a></strong></div><div>📖 React Native Firebase documentation source files - please use the website to browse the docs. - invertase/react-native-firebase-docs</div></blockquote>

**Comment by StatusSceptre** [comment]
Is  this still a relevant bounty @PombeirP ?

**Comment by pedropombeiro** [comment]
It is, but probably only makes sense to start once we add support for displaying PNs with sender and full message text.

**Comment by StatusSceptre** [comment]
ok, removing the tag, please re-add when you'd like to fund it again.
