### ISSUE TITLE
ETH icon contains an unexpected dot (main screen, Assets in send screen, maybe other places)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7047]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Some unexpected line/dot is left on ETH icon, can be seen on main Wallet screen and in Send-> Assets
![screenshot_20181207-172225](https://user-images.githubusercontent.com/6584810/49660055-f67ee980-fa45-11e8-9d29-c33f8b5c5d93.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Icon looks clea, no leftover graphic
#### Actual behavior
[comment]: # (Describe what actually happened.)
a small dot is shown in top left part of the ETH icon
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- open Wallet 
- check ETH icon look

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.32 release
* Operating System:  Android and iOS

**Comment by denis-sharypin** [comment]
@goranjovic  please reupload the icon

@1x: ![eth](https://user-images.githubusercontent.com/6559881/49660716-98530600-fa47-11e8-83c5-54fb25c6fdd6.png)
——
@2x:
<img width="40" alt="eth 2x" src="https://user-images.githubusercontent.com/6559881/49660761-adc83000-fa47-11e8-8e10-7d928a99e5e1.png">

——
@3x:
![eth 3x](https://user-images.githubusercontent.com/6559881/49660767-b0c32080-fa47-11e8-9d1f-5183c6ee1f41.png)
