### ISSUE TITLE
Create a Docker image for building for Android

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#7054]
Changes on Linux Jenkins slaves too often cause issues with builds. To avoid that a Docker image like the ones used for Windows and Linux([`linux-desktop-ubuntu`](https://hub.docker.com/r/statusteam/linux-desktop-ubuntu/) and [`windows-desktop-ubuntu`](https://hub.docker.com/r/statusteam/windows-desktop-ubuntu/)) needs to be created.

**Comment by divan** [comment]
Related: https://github.com/status-im/status-react/issues/3631
