### ISSUE TITLE
Bringing status-react Desktop to OS X AppStore

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#7057]
# Problem

Our goal is to publish status-react Desktop in Apple Store.

# Known issues

1. QtWebEngine module (at the moment responsible for rendering of embedded WebViews) is not compatible with AppStore;

Useful links:
https://mediaarea.net/blog/2018/02/14/QtWebEngine-MacAppStore
https://bugreports.qt.io/browse/QTBUG-60443
https://doc.qt.io/qt-5.11/qtwebengine-deploying.html

Possible solution relies in custom build of QtWebEngine (based on Chromium's sources).
Deprecated alternative to QtWebEngine is QtWebKit (JavaScriptCore is part of it).

cc: @chadyj 

<blockquote><div><strong><a href="https://mediaarea.net/blog/2018/02/14/QtWebEngine-MacAppStore">Using QtWebEngine on the Mac App Store</a></strong></div><div>MediaArea blog</div></blockquote>
<blockquote><img src="/s/57pps/711002/7b049b77f66e256a8f5944987495e729/_/jira-favicon-hires.png" width="48" align="right"><div><strong><a href="https://bugreports.qt.io/browse/QTBUG-60443">[QTBUG-60443] QtWebEngineProcess.app will not run in sandbox mode - Qt Bug Tracker</a></strong></div></blockquote>
<blockquote><img src="//d33sqmjvzgs8hq.cloudfront.net/wp-content/themes/oneqt/assets/images/favicon.ico.gzip" width="48" align="right"><div><strong><a href="https://doc.qt.io/qt-5.11/qtwebengine-deploying.html">Deploying Qt WebEngine Applications | Qt WebEngine 5.11</a></strong></div></blockquote>

**Comment by chadyj** [comment]
Thanks for looking into this Max.  Whilst it would be great to get into the Mac App Store I don't think it is a short or mid term priority.
- It isn't required. Desktop has other distribution channels available such as status.im
- Our mobile app isn't yet in the App Store with no release date set
- There is censorship and other risks in the App Store that make it a brittle and tenuous solution  

If we could eventually get into the App Store with little cost, then that is a bonus, but if there is a lot of effort I'd question the impact given the above.

**Comment by churik** [comment]
@rachelhamlin are we still aiming to do this?
