### ISSUE TITLE
Group chats not working with large amount of users

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7059]
It has been reported that group chats performance starts degrading when the number of users > 50 ( it might happen earlier).

This results in dropped messages and delayed communication.

That's likely a limit with pairwise encryption, we were aware that performance wise it does not scale, and eventually it would need to be improved to support large groups.

**Comment by chadyj** [comment]
What are your follow up thoughts here?

Seems like short term we can cap group chat membership to prevent degradation.

Longer term we need to explore scaling options. But we might not need to do that for a while until we start to hear user feedback wanting larger groups?

**Comment by cammellos** [comment]
@chadyj yes, limiting to a safe number would be the first option. 
Longer terms we can think of a more scalable way.

We have a few options: 
relaxing encryption for large groups
 keep current way and improve performance
 let the admin decide what kind of group chats they want to create (small, increased security), large (relaxed encryption)
