### ISSUE TITLE
Add more Ropsten Testnet warnings

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#706]
1. We should make Status application title under icon in launcher say  `Status (testnet)`
2 Console say in bold this is on testnet only, do not send real ETH

Open to other ideas

**Comment by rabbit** [comment]
You could communicate to the user any time they are on any non-main net connection. Something that can be either configured out (for ETC clones of status?) or permanently dismissed by the user. Maybe similar to the "Offline" message that appears in airplane mode.

**Comment by jarradh** [comment]
We can put this communication on the transaction screen as well.

**Comment by sla-shi** [comment]
Revisit this after #1628 is closed.
