### ISSUE TITLE
Cannot see contacts profile pic

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#7064]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a chat user, I want to see the user pic of other contacts I'm chatting with.

### Description

*Type*:Bug

I'm chatting with contacts that have a user pic, but I don't see it.

#### Expected behavior
See the user pic of contacts

#### Actual behavior
Don't see the user pic

### Solution

cc @cammellos @yenda Do you know what is going on here?

**Comment by cammellos** [comment]
There are a few possible causes for this issue:
1) Dropped whisper messages
2) The sender's picture are not synced across devices (if you add a contact on desktop and you have your default picture on then that's the one that will be seeing by that contact until a picture is updated).

Syncing of account picture should alleviate the problem to some extent.

To some extent we can't have completely consistent data, but a few simple options to overcome this:
1) Don't advertise a default picture (I  think currently we actually advertise the default picture, say you change your name on desktop), which might override a previous version sent from a different device

2) Periodically advertise your contact-info. We could advertise once a day (for example) your picture and name to lower the possibility of this data to be out-of-sync, which also should help with wallet recovery.
