### ISSUE TITLE
Upgrade to react-native 0.57

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7074]
# Problem

The latest version of react-native will bring improvements for development of desktop
Changes in react-native preset requires update on mobile as well if desktop is updated

# Implementation

- update libraries
- update react-native

# Alternative

Separate babel presets for mobile and desktop

# Acceptance Criteria

Projects builds and works without regressions

**Comment by churik** [comment]
Still relevant as far as I can understand

**Comment by yenda** [comment]
@churik no we are moving directly to 0.58
