### ISSUE TITLE
"Your phone appears to be ROOTED" message nuisance.

### ISSUE THREAD

**Issue by Smokyish** [status-im/status-react#709]
I think it's important to have the pop-up message appear, but because it appears every time Status is opened, it will start to get pretty annoying pretty fast.
I suggest changing the message to appear for the initial start of the app and then every Nth time Status is opened, ie. every twentieth/fiftieth time just to remind people that this can be a security issue. 
The message will get especially annoying when people use Status daily and open the app possibly many times a day.

**Comment by jarradh** [comment]
hmm, I can see how it's annoying, in the meantime rootcloak xposed module

**Comment by jiriknesl** [comment]
Thinking of solving this issue.

Where is the root check? I cannot find it in status-repo (looking for messagee about rooted phone).

I'd solve it that after first run it is shown only in 2 % of runs. Is it ok?

**Comment by jiriknesl** [comment]
WIP https://github.com/jiriknesl/status-react/commit/753b0449e54fa2b993cc48fc1a4a317edcf27c15

**Comment by ghost** [comment]
Looks abandoned. Taking over.
