### ISSUE TITLE
After logging > 24h messages from yesterday are shown as messages that are sent today

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7090]
### Description

*Type*: Bug

*Summary*: when you are logging more than 24h, messages that sent yesterday are shown below "Today" in chat. According to discussing it with @cammellos  those messages are cached and the view is not refreshed when day passes. The issue disappears after relogin.

#### Expected behavior
message is shown below "Yesterday"

#### Actual behavior
message is shown below "Today"
<img width="679" alt="sfd" src="https://user-images.githubusercontent.com/4557972/49941234-37617d00-fee2-11e8-8f3a-3b31e9af6c35.png">

### Reproduction

- Open Status
- Create any custom public chat (i.e.` #test123`)
- Send a message
- Don't log out  >24h
- Check ` #test123`

### Additional Information
* Status version: 0.9.32
* Operating System: all

**Comment by rachelhamlin** [comment]
@churik is it still possible to repro this one?

**Comment by churik** [comment]
yes, I need 24 hours for this) will try to repro and share here

**Comment by rachelhamlin** [comment]
Okay thanks @churik. @StatusSceptre can we add a bounty to this one please? :)

**Comment by churik** [comment]
still relevant (release 0.13.0)

**Comment by churik** [comment]
should be retested along with https://github.com/status-im/status-react/issues/10003

**Comment by churik** [comment]
Still relevant in Status v1.0.1

**Comment by churik** [comment]
Agree, very edge case.
Mentioned in #11271
