### ISSUE TITLE
Could not change account exception shown when account is recovered

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7093]
### Description

*Type*: Bug

*Summary*: 

`Could  not change account {:message "Account's database does not exist.", :error :database-does-not-exist}`

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/49950715-63dcbf80-ff09-11e8-9191-d4419be3e89a.png)

### Reproduction
- build develop (emulator)
- recover account

NOTE: same on account creation

**Comment by rasom** [comment]
This is not an exception, that's a warning. It can be seen only in dev mode and doesn't affect anything in prod build.

**Comment by asemiankevich** [comment]
> This is not an exception, that's a warning. It can be seen only in dev mode and doesn't affect anything in prod build.

 okay , i used wrong wording here. 

Thanks for taking a look. I assume i can close it then.
