### ISSUE TITLE
Messages not loaded from the database if out-of-order messages are received

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7097]
Some messages are not loaded from the database if messages with an older timestamp are received (from the mailserver for example).

### Step to replicate
The steps to  replicate are a bit artificial, this is the simplest way, but fetching old messages from the mailserver might also result in this behavior, or receiving a message from a peer with the clock set to the wrong time.

1) Post 100 messages (1,2,3,4,5...) in a public chat
2) Make sure all those messages are on device A
3) Change your time to -1 day
4) Login/Logout
5) Go to that chat, do not scroll up
6) Post a few messages (5)
7) Scroll up, there should be some gaps in messages

Login/logout should fix the issue and those messages should appear again.

### Details

This is due to the fact that we use the count of messages loaded to paginate, but the collection underneath (and our count as well) change with the receiving of messages, which leads to unstable pagination.

A possible solution is to use a cursor `clock-value-message-id` and use that to paginate (no skipping, you always fetch the last x messages that have a cursor value > last-clock-value fetched). This might lead to empty pages (pages full of duplicates) if old messages are received and the request will have to be retried, but at least it won't be resulting in skipped messages (which has an impact on the user, unlike empty pages that can be retried).

**Comment by churik** [comment]
@cammellos yeah, this is way to reproduce the issue what @rasom told recently.
Basically on this case I got:
-  messages are shown as sent several times  after scrolling down;
- these messages are shown at the end of other chats when I'm switching between them;
- after  setting automatic date and login\logout issue messages are shown as sent yesterday you can switch between chats normally.
Logs:
[Status_r.log](https://github.com/status-im/status-react/files/2680759/Status_r.log)
[geth.log](https://github.com/status-im/status-react/files/2680761/geth.log)

<img width="568" alt="messages_old" src="https://user-images.githubusercontent.com/4557972/50013206-d65ca680-ffc0-11e8-9a4d-55ca2f81d9af.png">
<img width="568" alt="older" src="https://user-images.githubusercontent.com/4557972/50013453-76b2cb00-ffc1-11e8-877d-d3c8b06b3e87.png">
