### ISSUE TITLE
Messages aren't fetched from offline mode if mailserver is mail-02.ac-cn-hongkong-c.eth.beta 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7098]
### Description

*Type*: Bug

*Summary*: for one mailserver `mail-02.ac-cn-hongkong-c.eth.beta ` history is not fetched from offline mode.
If you change it to other manually - history is fetching successfully.

*Prerequisites:* user has build installed on desktop platform (in my case it is Mac OSx) and mail server is `mail-02.ac-cn-hongkong-c.eth.beta`

After this history is finally fetched.
**Reproducible only on for my setup.** (feel free to request `Status` folder to debug it)
#### Expected behavior
all sent messages are fetched 

#### Actual behavior
no new history fetched or only last sent message is fetched. If you go to settings and change mailserver (in my case I changed to `mail-01.do-ams3.eth.beta`) - all history will be fetched.

### Reproduction
- join any public chat (i.e. #12345test)
- log out 
- sent some messages to the same chat from another device (several messages)
- log in on desktop
- check this chat 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 14/12/2018
* Operating System: Mac OS
* NOTE: reproducible only for my current setup on desktop, for all types of chat (1-1, group, public) and only for this mailsever.

#### Logs
Video: http://take.ms/ERSKV
[geth.log](https://github.com/status-im/status-react/files/2679490/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2679459/Status.log)

**Comment by vkjr** [comment]
@churik, when you reproduce this on mobile, are you connected to the same network provider?
It is strange for me that it is desktop-only. I can suspect that you can't connect from mobile and can't connect from desktop because of different networks? If you connect mobile to the same network and issue reproducible, then probably something is with the provider.

**Comment by churik** [comment]
@vkjr I agree that's strange. I have the same wifi network on both devices.
Also I retested it on different accounts with different number of chats - the same.

**Comment by churik** [comment]
OK, found out. Specific for my setup, which is only on desktop - so if I clean up the data fully, I couldn't reproduce it.
On current setup I can reproduce it for all accounts - new and recovered.
I'll save my setup for anyone who can debug an issue.
