### ISSUE TITLE
No way to delete chats

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#710]
There should be some way to delete chats from chat list.

**Comment by Smokyish** [comment]
A suggestion for the contact and chat ordering:
If you hold down a finger on any contact/chat, it enables "editing mode" where you can drag any contact/chat up/down and re-order them that way to whatever order you want.

The same editing mode could have either a spot/icon where you could drag a contact/chat to remove it, or just a button on each contact that is only visible in the editing mode that allows the user to delete the contact/chat.

**Comment by jarradh** [comment]
Perhaps we can utilise https://github.com/jemise111/react-native-swipe-list-view or at least use it for inspiration (found by @johnmn3)
