### ISSUE TITLE
Add some texts according to security review

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7100]
# Problem
After security review (notes are here:  https://notes.status.im/zn74OjGLQx2V5ctqSTatgA) several changes should be done:

- [ ]  display disclaimer on download “Expect changes, vulnerabilities" 
Should be done on page with links to download release.

- [x] recovery page should include “Exposes funds associated with keys” 
Should be done on "Sign in to another account" page 
<img width="568" alt="4" src="https://user-images.githubusercontent.com/4557972/50005587-29c3fa00-ffab-11e8-95bf-a1522ea5f740.png">

- [x] and login page “This is alpha software” -  it must appear at the start, before user created account.
<img width="568" alt="jlfsljjlfkd" src="https://user-images.githubusercontent.com/4557972/50005555-13b63980-ffab-11e8-81a3-27e43ff90a6c.png">

<blockquote><div><strong><a href="https://notes.status.im/zn74OjGLQx2V5ctqSTatgA">Desktop Release Security Questions - CodiMD</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@churik, "this is alpha software" should be fixed also. As far as I remember, it must appear at the start, before user created account.
Starting work on this.

**Comment by churik** [comment]
Updated issue. thanks @vkjr !

**Comment by vkjr** [comment]
@churik, it is not clear for me where exactly on the recovery page “Exposes funds associated with keys” should be placed. Do you know this?

**Comment by churik** [comment]
Unfortunately not.
@errorists maybe you can provide quick design input?

**Comment by errorists** [comment]
a quick solution to the text on recovery page: it should be placed below the password, 24px top margin between text and password input, 12px text in Dark Grey color (#939BA1), so something like this 
<img width="515" alt="screenshot 2018-12-18 at 10 04 47" src="https://user-images.githubusercontent.com/4932774/50143231-672acf00-02ac-11e9-8fec-1fe200ccd348.png">

**Comment by rachelhamlin** [comment]
@churik @vkjr for that copy, "Exposes funds associated with keys," I suggest:

`Your wallet information will be exposed by importing this account.`

But exposed to whom/what @corpetty? What's the additional danger in importing this account to desktop?

**Comment by rachelhamlin** [comment]
@churik do we have a download screen for the alpha release prepared for me to add disclaimer copy (item #1)?

**Comment by churik** [comment]
@rachelhamlin no, we don't have.
I suppose it should be somewhere here https://status.im/get_desktop/ and I'm not sure who is responsible for this

<blockquote><img src="/img/share.png" width="48" align="right"><div><strong><a href="https://status.im/get_desktop/">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>
