### ISSUE TITLE
Don't display stats on desktop if it doesn't include required changes on status-go side

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7101]
# Problem

Currently, if `status-go` version for desktop doesn't contain changes required for https://github.com/status-im/status-react/pull/6990 to work correctly, 0 in stats are shown. 
<img width="568" alt="sdfsdf" src="https://user-images.githubusercontent.com/4557972/50005864-1b2a1280-ffac-11e8-8051-6f0b5ddcbfe2.png">

# Implementation
Expected that stats shouldn't be displayed if it cannot because of go-version.

**Comment by vitvly** [comment]
@adambabik do you think enable-metrics-by-default branch could go together with https://github.com/status-im/status-go/pull/1329, or should we disable stats for now?

**Comment by adambabik** [comment]
Working on it.

**Comment by churik** [comment]
@adambabik 
It is already fixed in https://github.com/status-im/status-react/pull/7144 :) so seems that required changes were added there

**Comment by adambabik** [comment]
@churik that went with a geth 1.8.20 upgrade :/ If that's ok then great but I can also prepare a build without it.

There were just few changes in the upgrade so I believe it should be smooth.

**Comment by churik** [comment]
IMO that's OK if stats is right (couldn't check)
@siphiuel WDYT?

**Comment by vitvly** [comment]
@churik should be fine

**Comment by adambabik** [comment]
Let's use https://github.com/status-im/status-go/releases/tag/0.17.10-beta.1.

**Comment by churik** [comment]
Already  fixed
