### ISSUE TITLE
[DApp] Add support for dBay

### ISSUE THREAD

**Issue by LuisEGV** [status-im/status-react#7107]
# Problem

Please add compatibility of the Marketplace dBay. (https://www.dbay.ai/) I could do it myself, but I don't have authority to make a pull request.

# Description
Single Marketplace to buy all your dApps without no middlemen and no commision. 

# Implementation

I linked an image for dBay. (180x180) 

![dbay logo](https://user-images.githubusercontent.com/19657680/50040237-0f5d4f80-0083-11e9-912a-c25dadbb0b94.png)

<blockquote></blockquote>

**Comment by jeluard** [comment]
@LuisEGV You can create PR, there shold be no permission required.
