### ISSUE TITLE
After reopening application non-existed mailserver without name is shown on the top of the list

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7115]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: after installing application, creating account and then relaunching app I can see additional mailserver with empty name and no-value.

#### Expected behavior
no new mailservers are shown

#### Actual behavior
![no-mailserver](https://user-images.githubusercontent.com/4557972/50094333-45313e00-0213-11e9-9f43-90c64fa54d50.png)
If I try to connect to it, I cannot fetch history for 24 h, but can send and receive messages

### Reproduction

- Open Status
- Create an account
- Close app
- Start app again
- Check profile>Advanced settings

### Additional Information
* Status version: nightly 17/12/2018
* Operating System: Mac OS
#### Logs
[Status.log](https://github.com/status-im/status-react/files/2686535/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2686538/geth.log)

**Comment by churik** [comment]
release blocker? @rachelhamlin @siphiuel

**Comment by vitvly** [comment]
Will check.

**Comment by churik** [comment]
Can't reproduce
