### ISSUE TITLE
MVP 7 Mentions

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7117]
# Problem

- As a user, I want to be able to mention other users in the chat
- As a user, I want to have a way to easily notice when I have been mentioned in a chat

# Design

[Figma for mentions](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=144%3A233)
[Figma for notifications](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1403%3A10378)

# Implementation

There is two ways to implement this feature.

## Keywords

A user could specify a list of keywords that would be used in a regexp search to check if they are contained in the messages that are received. Keywords will be highlighted in chats

The search needs to be done upon reception of each message

## Real mentions

When mentioning someone using his public key, username or random username, the mention is replaced by the public key of the user. In the chat people will see the random name by default or the username corresponding to the public key if they know it. If it is the user public key that his mention it will be highlighted.

Mentions are sent as a separate field in the message.

# Acceptance Criteria

- use cases and designs are implemented

**Comment by 0xc1c4da** [comment]
➤ Hester Bruikman commented:

Rachel Hamlin considering this discuss post. Perhaps mentions need to be higher on the priority list. Seems like a first step to #viral #dapp #mentions

https://discuss.status.im/t/friend-to-friend-content-discovery-community-feeds/1212/2
