### ISSUE TITLE
SNT and emoji reactions

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7118]
# Problem

As a user, I want to be able to react to a message by sending SNT to it
As a user, I want to react to a message with an emoji

# Implementation

use https://github.com/instea/react-native-popup-menu or custom popup-menu

# Design 

[Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1239%3A0) // [Framer prototype](https://framer.cloud/ObAKy/)

# Implementation

- SNT reactions should use a flow similar to the one of the `/send` command
- SNT reactions require some mechanism to verify the transaction
- investigate `reaction` schema vs having `reaction` string field storing reactions as edn in the `message` schema

# Acceptance Criteria

- user stories are implemented

**Comment by Samyoul** [comment]
Process flow

- User selects a message and selects an emoji reaction
- UI sends a JSON RPC method call to `status-go`
  - How does this RPC message get created?
  - Does UI set the content type of the message etc?
- `status-go` receives RPC method call
- `status-go` parses the RPC data and interprets the message to be sent via Waku
- `status-go` saves outgoing message
  - Although the logic seems to save the chat, does this include the messages?
  - see `protocol/persistence.go`
- `status-go` sends message to peers
- peer receives message, 
- peer parses the message
- peer saves the message
  - How are migrations generated?
  - Does the peer update the UI or does the UI request an update for new messages?
