### ISSUE TITLE
MVP 5 Mark all as read

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7119]
# Problem
#5394
More recent: #6375

Fix 9+ new messages badge

* as a user I want to open chats in the position of the last read messages
* as a user I want to be able to jump to the latest messages and mark all the messages as read.

# Design
https://github.com/orgs/status-im/projects/49#card-15833897

# Implementation

* implement design
* be careful with opened chat when receiving messages from mail server as the messages for the current chat are currently marked as seen when received.

# Acceptance Criteria

* use cases and design are implemented

**Comment by oskarth** [comment]
If it requires design and we don't have resources then we have two options IMO:
1) Make design a bounty
2) Failing that, make bounty to integrate it under dev mode w. flag

**Comment by rachelhamlin** [comment]
@oskarth I believe the designs for mobile are still okay, but understand your interest is more in having the feature for desktop (#7200). Given that we now have mobile UI on desktop, should we put a bounty on the mobile version first and then desktop separately?

**Comment by oskarth** [comment]
@rachelhamlin sure, no specific preference on order/platform, I think the desktop should follow naturally after mobile UI.

**Comment by rachelhamlin** [comment]
@oskarth okay, I'm putting one on #6375 as it has the best description and designs linked.
