### ISSUE TITLE
Implement Transaction Signing Pattern

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#712]
As mentioned in #700 we will incorporate a signing pattern thats generated within Console, to signal to a user that the transaction signing screen is legitimate and not a phishing attempt, this technique is employed in in Ethcores Parity.

Here's my initial idea of how that would look like.

<img width="364" alt="screen shot 2017-01-11 at 10 14 09 am" src="https://cloud.githubusercontent.com/assets/2714786/21834551/733d2522-d7e8-11e6-88b5-81492ea434e1.png">

**Comment by jarradh** [comment]
I think a pattern is going to be too abstract, but what we could potentially do is grab 1200 images from https://www.pexels.com/popular-photos/all-time/ remove any NSFW images and then 
scale&crop them down to a dimension (ie `300x50`) at 60% jpg quality each image would be 2-3kb and adding only 3MB to filesize. Could potentially reduce phishing ability down to 1 in 1000 and still look aesthetically pleasing and recognisable.

**Comment by sla-shi** [comment]
Won't fix because of #1585
