### ISSUE TITLE
MVP 8 send images (as extension)

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7120]
# Problem

As a user, I want to be able to send and visualize images in the chat.

This is a community feature request that is quite recurrent.
The whisper protocol isn't suited for sending images and the swarm protocol isn't ready.

# Implementation

An extension that would use one of the public image hosting provider could be developed to provide this feature.
Since it is an extension it wouldn't be officially part of Status. The user should be aware that this kind of extension, like gfycat, doesn't provide the same level of privacy and security than the text messaging in Status. 
The shortcomings of public image hosting providers are:
- images are posted publicly, 
- the host knows the ip of the sender, 
- the host knows the ip of the viewers.
- the host can censor or modify the content

# Acceptance Criteria

- `/imgur` or similar command using a public image hosting provider can be added as an extension by users to publicly post images with the security limitations of such hosting website.
- optional: images are cache so that it isn't necessary to re-fetch them everytime the message is loaded

**Comment by yenda** [comment]
@jeluard I believe such feature would require extensions to have access to file browser?

**Comment by jeluard** [comment]
@yenda To select a picture from the gallery or take a new one that would be sent to say `imgur`? Yes, see #6596 (@tbenr is on it :))

**Comment by yenda** [comment]
@jeluard yes seems like this issue would do

**Comment by hesterbruikman** [comment]
Superseded by current images in chat over Waku
