### ISSUE TITLE
Wallet won't open after update to Android 6.0

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#713]
Upon updating to Android 6.0, wallet will not open. 

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/182?status=New

![image](https://cloud.githubusercontent.com/assets/25023739/21835110/497c08f2-d81f-11e6-9f6e-d90809cbefb9.png)

**Comment by jarradh** [comment]
i see in log `[Error: Invalid JSON RPC response: ""]` seems related to #652

**Comment by rasom** [comment]
duplicate #652
