### ISSUE TITLE
Sign transaction with Keycard

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#7133]
# Problem

It's not possible to sign transaction with Keycard

# Implementation

TBD

Screens https://www.figma.com/file/UfQjpWl1hmRchHIyY3Wvu2nW/Hardwallet-light-flows?node-id=0%3A1

# Acceptance Criteria

It should be possible to sign wallet transaction with Keycard 

<img width="995" alt="screenshot 2018-12-18 17 05 11" src="https://user-images.githubusercontent.com/23836/50159170-17b5c480-02e7-11e9-918c-abd0fa56b6ba.png">

<blockquote><img src="/file/UfQjpWl1hmRchHIyY3Wvu2nW/thumbnail?ver=thumbnails/e59ee715-babe-4094-b5cd-6967dc112d3a" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/UfQjpWl1hmRchHIyY3Wvu2nW/Hardwallet-light-flows">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by dmitryn** [comment]
@goranjovic 

Current version of react-native-status-keycard is 2.3.2.
You could see how other keycard SDK methods are implemented here: 
https://github.com/status-im/react-native-status-keycard/blob/v2.3.2/android/src/main/java/im/status/ethereum/keycard/RNStatusKeycardModule.java

SDK docs: https://status-im.github.io/keycard.status.im/api/sdk_derivation_sign.html#Signing

PIN screen is already implemented: https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/hardwallet/pin/views.cljs#L70

Hold card animation is here: https://github.com/status-im/status-react/blob/develop/src/status_im/react_native/resources.cljs#L72

You also need to HARDWALLET_ENABLED to 1 in `.env` to start working with keycard.

Until keycard login is ready, you need to create 2 accounts: keycard account and regular account with password. Then you need to login with regular account.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-status-keycard">status-im/react-native-status-keycard</a></strong></div><div>React Native library to interact with Status Keycard using NFC connection (Android only) - status-im/react-native-status-keycard</div></blockquote>
<blockquote><div><strong><a href="https://status-im.github.io/keycard.status.im/api/sdk_derivation_sign.html#Signing">Status Incubate: helping #buidl web3</a></strong></div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by dmitryn** [comment]
@goranjovic One more thing to add. I'm currently working on login with keycard in this branch `feature/login-with-keycard-merged` https://github.com/status-im/status-react/pull/7341

I added some improvements on how PIN screen work so it would be great if you start your work based on `feature/login-with-keycard-merged` branch. As a bonus, you would have keycard login working so you won't need to create 2 accounts (keycard and regular) to login.

**Comment by dmitryn** [comment]
@goranjovic Also, it might be useful to read these guides
https://github.com/status-im/status-keycard/blob/master/UX_NOTES.md
https://github.com/status-im/status-keycard/blob/master/CLIENT_NOTES.md

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-keycard">status-im/status-keycard</a></strong></div><div>Our Javacard Implementation for making secure transactions within Status and Ethereum - status-im/status-keycard</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-keycard">status-im/status-keycard</a></strong></div><div>Our Javacard Implementation for making secure transactions within Status and Ethereum - status-im/status-keycard</div></blockquote>

**Comment by gravityblast** [comment]
@dmitryn @goranjovic 

I'm adding here some documentation on how to interact with `status-go`.

`status-react` should:

1 - build the transaction "object" that usually sends to `sendTransaction`

2 - call `HashTransaction` in `status-go` [(code)](https://github.com/status-im/status-go/blob/develop/lib/library.go#L431). This function will return:
```
{
  "transaction": {
    ...
  }, 
  "hash": "0x..."
}
```

The `transaction` in the response contains the transaction sent at step 1 with the right nonce, gasPrice, and gas.
`hash` is the tx hash that we need to send to the keycard.

3 - send the transaction hash to the keycard. The keycard will return the signature.

4 - call `SendTransactionWithSignature ` [(code)](https://github.com/status-im/status-go/blob/develop/lib/library.go#L409) passing the tx received at step 2 and the hash received at step 3.
