### ISSUE TITLE
Status.log is created on Windows release build

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7140]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Status.log is created on Windows if install release Desktop build and create account

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No Status.log is created until user will enable logging
#### Actual behavior
[comment]: # (Describe what actually happened.)
Status.log is created
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://www.screencast.com/t/Nf0gzjJ53
- Download Windows release build 1 from https://ci.status.im/job/status-react/job/release/job/release%252Fdesktop%252F0.9.0/1/
- Make sure no Status is installed and there is no Status folder in %LOCALAPPDATA%
- run Windows installer and install Status. In my case i've change default path to install to D:/Program Files
- run Status 
- open  %LOCALAPPDATA%/Status folder and monitor its content
- Create new account in Status
- provide password, click Next
- confirm password and click Next. Creating account will be shown for a while
- on the step with Name just start typing and wait ~10-30 seconds and watch %LOCALAPPDATA%/Status In my case Status.log was created 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release build #1
* Operating System: Windows 10 Pro 

#### Logs
[Status (2).log](https://github.com/status-im/status-react/files/2691703/Status.2.log)

<blockquote><img src="https://content.screencast.com/users/anna123123/folders/Status/media/6e716ca4-f7b9-47c6-8e53-5c05fe34966b/FirstFrame.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Screencast.com</div><div><strong><a href="https://www.screencast.com/t/Nf0gzjJ53">windows status.log</a></strong></div><div>Shared from Screencast.com</div></blockquote>
<blockquote><img src="/static/9b8798e5/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Fdesktop%252F0.9.0/1/">status-react » release » release/desktop/0.9.0 #1 [Jenkins]</a></strong></div></blockquote>

**Comment by churik** [comment]
good news with this issue are:
1) that it is not reproducible all times and specific to Windows
2) geth.log is not created
2) Status.log stops growing right after you login to account, so application detects that logging is disabled. 
My suggestions for now is to review created log for sensitive data and if it doesn't have it - postpone this issue.
[Status.log](https://github.com/status-im/status-react/files/2694671/Status.log)
@annadanchenko WDYT?

**Comment by annadanchenko** [comment]
@churik I'm ok if log will be reviewed cc @corpetty
