### ISSUE TITLE
haptic sticking on swiping to right on Status Mobile 

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#7171]
Couldn't really  describe what's going on so here's a  screen  recording.  

https://sendvid.com/xakbtsd6

<blockquote><img src="https://thumbs2.sendvid.com/ad/20/xakbtsd6.jpg" width="48" align="right"><div>Sendvid</div><div><strong><a href="https://sendvid.com/xakbtsd6">ScreenRecording 12 23 2018 23 32 32</a></strong></div></blockquote>

iOS 12.1.2 iPhone X

**Comment by errorists** [comment]
Yeah, this entire swipe gesture is super janky and just bad. I’d suggest we either redo it altogether instead of patching up or replace it with a long press gesture.

**Comment by rachelhamlin** [comment]
WTF. 

Can we switch this for long press to delete instead @rasom or @yenda?

**Comment by hesterbruikman** [comment]
Can we close this issue as it will be addressed here: https://github.com/status-im/status-react/issues/7715#?

**Comment by annadanchenko** [comment]
no swipe gesture anymore in chats
