### ISSUE TITLE
Loading status takes ~20 secs or longer

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#7178]
# Problem

When I open status it takes a very long time to load initial state with multiple public chats opened. 

Video example on iPhone X with 250MB down connection 

https://sendvid.com/2umj6ak4

<blockquote><img src="https://thumbs2.sendvid.com/91/aa/2umj6ak4.jpg" width="48" align="right"><div>Sendvid</div><div><strong><a href="https://sendvid.com/2umj6ak4">8D9</a></strong></div><div>Upload and share videos instantly. It's free and simple. No signup required.</div></blockquote>

**Comment by pablanopete** [comment]
Looks like #7099 is possibly related, can close if already ref.@rasom is this the same problem?

**Comment by rasom** [comment]
Hey @pablanopete, how many chats do you have in the app? Which version are you running?

**Comment by pablanopete** [comment]
0.9.32 (stable release, latest public hotfix from TestFlight) @rasom

I’ve got a whole lot of chats ¯\_(ツ)_/¯ at least 50+ individual + public chats and group chats.

**Comment by rasom** [comment]
ok, I see. This particular problem is already fixed in `develop`, but it hasn't been released.
