### ISSUE TITLE
Backup Status DB to Swarm

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#718]
We need to encrypt our app database with the currently logged in account and back it up to Swarm,
later on account recovery we should attempt to retrieve this data.

**Comment by commiteth** [comment]
Current balance: 0.00000000
Contract address: 0xf141384037f26003d8d42292276c5b2ecf392bff
![QR Code](https://commiteth.com/qr/status-im/status-react/bounty/718/10fa59afc7b6ba2d08acd63c6e43d80c4886a645f22381bdc934fa3ee1d376bc/qr.png)
[https://commiteth.com](https://commiteth.com)

**Comment by annadanchenko** [comment]
Instabug:
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/330
