### ISSUE TITLE
Can't create new account or restore existing after error "This account already exists but passwords don't match" until relaunch app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7189]
### Description

*Type*: Bug

*Summary*: after "This account already exists but passwords don't match" error is shown (at attempt to restore the same account with different passwords) - you can't create a new account (the app is hanging on step "Creating account") neither add existing account using seed phrase until full account restart.

#### Expected behavior
can create new account

#### Actual behavior
can't create new account

### Reproduction

- Open Status
- Restore  account from seed phrase
- Sign in
- Restore the same account with a different password to get an error "This account already exists but passwords don't match"
-  Try to create a new account or restore another account from seed phrase

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 26/12/2018
* Operating System: all

#### Logs
[Status.log](https://github.com/status-im/status-react/files/2710176/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2710178/geth.log)

**Comment by asemiankevich** [comment]
@churik this is in release 0.9.33 (2018122603) at least android
