### ISSUE TITLE
Integrate with Development Tools

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#719]
For our developer tooling we need to look into Truffle & Embark to see how web&chat dapps can be hot-loaded / easily developed for Status.

Somewhat related to #716

**Comment by alwx** [comment]
The hot-loading can be done in a simple way: we can use a `geth` console to send a request to add some app to the list (as well as remove it)

**Comment by jarradh** [comment]
having a cli tool on desktop that watches a file and hotloads code that way, with a 'REPL' that pipes to geth console would be a very handy approach.
