### ISSUE TITLE
Wallet set up is shown after transaction is completed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7190]
### Description

*Type*: Bug

*Summary*: I receoverd account. I opened 1x1 chat. I send a request of HND token. Then i sent STT 0 amount in this 1x1 chat - wallet set up screen was shown as i did not complete onboarding yet. I finished signing txn and tapped OK. wallet set up screen is shown again .

#### Expected behavior
wallet onboarding is not shown once done

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/50448978-54ac3780-0935-11e9-8252-aa079ac9b4fb.png)

### Reproduction

- Open Status
- Recover account
- Start new 1x1 chat with ens username (Nastya for ex)
- Switch to Ropsten
- Send /request HND 1 in 1x1 chat with Nastya
- Send /send STT 0 in 1x1 chat with Nastya
- Complete onboarding
- Sign txn
- Tap okay

**Comment by asemiankevich** [comment]
this screen  is also shown in the following case:
- create account (0 eth )
- complete onboarding
- add contact and open chat
- tap send ETH 0
- see insufficient funds
- tap cross button

**Comment by Serhy** [comment]
For the https://github.com/status-im/status-react/issues/7190#issuecomment-472346566 separate issue created https://github.com/status-im/status-react/issues/7821

#7821 chosen to be fixed before release. This issue is very similar to #7821 - marked with `release` too
