### ISSUE TITLE
Universal links not working on some devices

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7196]
It has been reported that universal links from https://people-ops.status.im/status-channels/ are not working.

The link is opened in the browser instead of status-app.

The app is installed, the version is `0.9.32`, the OS is android pie.

![error](https://user-images.githubusercontent.com/1017008/50510075-96012c00-0a88-11e9-9573-752ee0012a6d.jpg)

<blockquote><img src="https://people-ops.status.im/content/images/2018/10/iStock-605996608.jpg" width="48" align="right"><div>People Ops at Status</div><div><strong><a href="https://people-ops.status.im/status-channels/">Status Channels</a></strong></div><div>What are the best channels in Status? Here is a directory of Status public channels used by Status Core Contributors. A live list is maintained here.#book-club #clojure #cryptolife #dac-zero #ethereum #legal-continuance-and-liberty #Lorikeet - Collaborative Component Design with Aragon / Bounties Network #moot / Be yourself, be us #sitg-one #status #status-analytics #status-brand</div></blockquote>

**Comment by jeluard** [comment]
Superseded by #7213
