### ISSUE TITLE
Add Firstblood DApp

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#720]
http://app.firstblood.io/

I think the logo may need some work to look nice within our contact circle

![192px](https://cloud.githubusercontent.com/assets/2714786/21923486/00af6d56-d9a7-11e6-82a3-dbd34505e478.png)

**Comment by jarradh** [comment]
http://wiki.status.im/contributing/development/adding-dapps/

**Comment by auryn-macmillan** [comment]
This one fits nicely in the contact circle, on android at least.

![fb2](https://cloud.githubusercontent.com/assets/8453294/21940519/c01c88dc-d992-11e6-8711-19986faec777.png)

**Comment by auryn-macmillan** [comment]
I went ahead and made a pull request to add FirstBlood.

**Comment by jarradh** [comment]
thanks @auryn-macmillan !

**Comment by alwx** [comment]
#728 was merged 5 mins ago. Thanks @auryn-macmillan !
