### ISSUE TITLE
Add "mark read" in desktop chats

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#7200]
# Problem

Sometimes to many messages are shown as unread in a chat. If user not going to scroll to the top and read them all, he should have option to mark all messages as read.

# Implementation

# Acceptance Criteria
User can mark messages in a chat as read

# Notes

# Future Steps

**Comment by Swader** [comment]
@vkjr I think you mean "mark read" but "mark unread" would be cool too.

**Comment by vkjr** [comment]
@Swader, thanks for noticing, you are right, I meant "mark read" :)

**Comment by oskarth** [comment]
@flexsurfer @rachelhamlin I understand this might not be on the critical path. However, it's a much needed feature, so can we bounty it up please?

**Comment by annadanchenko** [comment]
@oskarth also see https://github.com/status-im/status-react/issues/7119

**Comment by 0xc1c4da** [comment]
➤ Hester Bruikman commented:

cc Rachel Hamlin

**Comment by rachelhamlin** [comment]
FYI - we are putting a bounty on the mobile version of this feature, #6375.

**Comment by vkjr** [comment]
Cool, when desktop get mobile UI, this feature will be there automatically.
