### ISSUE TITLE
Add quick search function for mobile

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7208]
# Problem
Using Status chat day-to-day, to exchange essential information not documented elsewhere, searching chats becomes more desireable. To objective of search being to read, quote, reply to or copy historic messages.

- As a user I want to find specific messages from the past
- As a user I want to search for specific messages by topic
- As a user I want to search for specific messages by user
- As a user I want to search for specific messages by accross public, private and group chats

Original> Can't find my channels or messages.

# Implementation

Implement quick search similar to on Desktop.

# Acceptance Criteria

I can search for channels easily on Mobile.

# Notes

This already exists on Desktop, so should be able to re-use at least logic. @yenda can probably advice.

This would make a great bounty as well for the chat-team to issue (cc @yenda @rachelhamlin).

# Future Steps

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/6252

I added the bounty labels but it's unlikely I'll review the code, so I defer to @yenda et al for how to deal with it a la https://discuss.status.im/t/bounties-bounties-for-everyone/784

**Comment by errorists** [comment]
Designs for mobile are available here, though they go a step further than search on desktop allowing to search message history in addition to filtering chats/contacts. [Figma link](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=618%3A7739)

**Comment by StatusSceptre** [comment]
What's the current state of this @oskarth, is this bounty considered a `Medium` bounty still with the updates from @errorists ?

**Comment by rachelhamlin** [comment]
@StatusSceptre actually, @yenda is going to work on this this week. I'm removing the bounty labels for now.

**Comment by hesterbruikman** [comment]
https://github.com/status-im/status-react/pull/7511
@yenda can we close this issue as you're working on it in #7511?

**Comment by cammellos** [comment]
This should be implemented, at least the channels part.
