### ISSUE TITLE
Support universal links resolution in Status browser

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#7213]
### User Story

As a user, I want to have universal links resolved from within Status browser.

### Description

*Type*: Trying to open universal link from withing Status browser ends up with 'Unable to load page' in the Status webview. Universal links to user profiles, chats, webpages should redirect to appropriate place in Status app (see steps to reproduce for expected behavior)

### Steps to reproduce:
1) Open Status
2) Navigate to `+` -> `Open DApp` -> paste universal link to your own profile: `https://get.status.im/user/[your_own_public_key_here]`
3) Scroll down an tap `Open in Status` button
**Actual result:** User keep stay in webview with the 'Unable to load page' error
**Expected result:** User navigated to own Profile screen (`Profile` tab)
4) Navigate to `+` -> `Open DApp` -> paste universal link to your user profile, for example `https://get.status.im/user/0x042b61de5ca761d3ca21be6b86622c3e5cc3fa0b049b8aae4abf9fbb97d685c88dacb1f7a57c7b1b868cfb0e410f9f899883b3a97fa87cb4138eaf458b07747a40`
5) Scroll down an tap `Open in Status` button
**Actual result:** User keep stay in webview with the 'Unable to load page' error
**Expected result:** User navigated to contact Profile screen
6) Navigate to `+` -> `Open DApp` -> paste universal link to public chat: `http://get.status.im/chat/public/status`
7) Scroll down an tap `Open in Status` button
**Actual result:** User keep stay in webview with the 'Unable to load page' error
**Expected result:** User navigated to `#status` public channel
8) Navigate to `+` -> `Open DApp` -> paste universal link to Dapp: `https://get.status.im/browse/www.cryptokitties.co/search`
9) Scroll down an tap `Open in Status` button
**Actual result:** User keep stay in webview with the 'Unable to load page' error
**Expected result:** https://www.cryptokitties.co/search opened in Status browser

**Comment by jeluard** [comment]
Cannot reproduce this.

**Comment by jeluard** [comment]
@asemiankevich Can you take a look and see if you can reproduce?

**Comment by Serhy** [comment]
Updated title and description: issue is when opening universal link from withing Status browser.
