### ISSUE TITLE
Add custom scheme support for ethereum-*

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#7214]
### User Story

As a user, I want to have ethereum links (EIP [681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md)) redirect to status wallet.
Also clicking on such link in external apps should open status wallet.

*Type*: Feature

**Comment by flexsurfer** [comment]
@churik @Serhy this should be implemented already? can we close?

**Comment by Serhy** [comment]
It is implemented already. Closing.  There are bugs already in GH but feature itself implemented.
