### ISSUE TITLE
Wallet balance switches to Finney after sending ETH transaction

### ISSUE THREAD

**Issue by nvtaveras** [status-im/status-react#722]
I found this a bit confusing from an user perspective. When I first opened the wallet app, it showed "0.000000" WEI as my balance. 

After getting some ether from a faucet, it switched to "1.000000" ETH.

And after making two transactions (0.25 and 0.12 ETH) it switched to "629.160000" FINNEY. 

My original receiving transaction shows as +1 ETH, however the other ones show under the FINNEY in the transactions list.

It looks like the currency shown will be ETH if the value is the transaction is >= 1 ETH, or FINNEY otherwise, which I find confusing from a UX point of view.

Is there any particular reason for this logic or should we use ETH in all cases?

**Comment by jarradh** [comment]
I agree it's abit weird, we'll probably end up doing a wallet design as I don't like alot about it

hmm this issue might live better on https://github.com/status-im/wallet , mind moving it?

**Comment by sla-shi** [comment]
Won't fix because the Wallet UI will be updated.
