### ISSUE TITLE
0.9.33 public mobile release

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#7224]
Creating this issue to manage 0.9.33 public release.

open issues and PRs for release: https://github.com/status-im/status-react/labels/release

(template from prior release issues)

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by mandrigin** [comment]
@pablanopete thanks for creating the issue!

Just for the record, this release will be internal and won't be publicly available. We will target 0.9.34 to be a public release.

**Comment by mandrigin** [comment]
the release branch is [`release/0.9.33`](https://github.com/status-im/status-react/tree/release/0.9.33)

**Comment by rachelhamlin** [comment]
Just for posterity, we discussed an early Feb target for `0.9.34`. 

The work on device syncing & reliability will be great to have public, since ETHDenver is promoting an #ETHDenver channel in Status.

**Comment by StatusSceptre** [comment]
In that case should I change the title to 0.9.34? just so the issue can be updated with all relevant information and we’re all on the same page about release. @rachelhamlin @mandrigin

**Comment by pablanopete** [comment]
Great thanks for all the information! Updating the title to reflect the public release for coordination, since 0.9.33 will be internally tested. 

@mandrigin @rachelhamlin

**Comment by rachelhamlin** [comment]
Yeah, let's use to manage `0.9.34` instead.

I've begun a list of updates to be included in the [release notes](https://notes.status.im/mobile-release-notes), although it's very incomplete.

Easiest thing is probably to ask team leads what updates need to be publicly released since December 6th. 
cc @mandrigin @yenda @jeluard @guylouis @goranjovic 👋

**Comment by jeluard** [comment]
@mandrigin Is the branch you shared for `0.9.34` ? Might be worth renaming it?

**Comment by mandrigin** [comment]
@jeluard then we can just ignore the internal release. Initially I thought that it makes sense to track internal releases too, but, whatever.

**Comment by jeluard** [comment]
My bad I didn't know we have internal releases.

**Comment by rachelhamlin** [comment]
Hey @mandrigin - the token requested for this release should be available by Jan 30th, and it's then a matter of our adding it (hoping @goranjovic can help with that). 

In the meantime, I can help to complete the list of everything else we'd like to have included.

(FYI @annadanchenko)

**Comment by mandrigin** [comment]
@rachelhamlin wasn't the initial deadline for this token end of this week?

**Comment by mandrigin** [comment]
We will release 0.9.33 in public as well, since Infura hotfix broke our release schedule :)

**Comment by rachelhamlin** [comment]
That's what we asked for @mandrigin, but the team says the 30th is the latest they'll have it ready. Up to you whether we can wait for that or not. What do you think?

**Comment by mandrigin** [comment]
Let's see, I don't want to promise anything at that point.

I think that we shouldn't think at this token right now. If it is ready before we release 0.9.33, we can include it (it doesn't look like a lot of work to me). If not — maybe we can make a hotfix with just this token afterwards.

What do you think @annadanchenko @rachelhamlin?

**Comment by rachelhamlin** [comment]
Yup, I think that works great. If it makes sense otherwise to start on this release, I don't want to delay for a non-urgent issue.

cc @pablanopete

**Comment by annadanchenko** [comment]
closing as release 0.9.33 is out
