### ISSUE TITLE
Erasing old data doesn't work on Status desktop on MacOS

### ISSUE THREAD

**Issue by pcowgill** [status-im/status-react#7225]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to open Status on desktop so that I can use the app.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I open status, and I want to make it past the screen where it says: 'We were not able to decrypt your data' and 'We were not able to decrypt your data, you might need to create new account and erase your old data by tapping "Apply". Clicking on "Cancel", will try again' .

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I expect that clicking on apply will erase my old data and let me create a new account.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Clicking on apply is no different from clicking on cancel. I remain stuck on this screen. This remains true after uninstalling the app and reinstalling it on MacOS.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Download Status desktop on MacOS. Open it.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] The flow for erasing old data when a user clicks "Apply" should be fixed.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: https://ci.status.im/job/status-react/job/combined/job/desktop-macos/4971/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.dmg
[comment]: # (Android or iOS.)
* Operating System: MacOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
If I should find logs, please instruct me how to do that on MacOS. Thanks!

<blockquote></blockquote>

**Comment by vkjr** [comment]
@pcowgill, thanks!

**Comment by pcowgill** [comment]
If you have any more context on why you closed this @churik, that would be helpful. Thanks!

**Comment by vkjr** [comment]
@pcowgill, this issue related to old UI of Status Desktop. We switched to using mobile UI for desktop, so it is now irrelevant.

**Comment by churik** [comment]
Ofc @pcowgill 
https://status.im/get/ - this only versions of Status, that are supporting after release v1.
Old desktop versions, based on QT, are not supporting anymore - but there is a plan to continue (based on two-pane UI), you can track progress on these issues: 
https://github.com/status-im/status-react/issues?q=is%3Aopen+is%3Aissue+label%3Adesktop-new
