### ISSUE TITLE
Implement Tribute to Talk setting flow

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7235]
### User Stories

As a user who values privacy and/or is in demand, I would like to set a minimum required SNT amount to contact me, so that I can prevent spam. 

As a user with a tribute set, I would like the option to edit the amount, to adapt based on the number of requests I'm receiving.

As a user with a tribute set, I would like the option to disable and open myself up to new contacts again.

### Description

*Type*: Feature

*Summary*: 
Requires an addition to the profile screen, and a 4 step flow to set a tribute. 
The edit flow is a repeat of the setting flow.
There are two additional screens for disabling a tribute.

See top two rows here: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1319%3A13403 

cc @errorists for further design specs 

*note* we are missing the `learn more` screen (I like the idea of having one). Copy adjustments TK.

#### Expected behavior
TtT section on the profile highlighted with a `New` badge that disappears after user has clicked into the feature.

No ceiling on TtT amount, but must be above 0 SNT.

<blockquote><img src="/file/aS1ct66VQ6V0cio7vSqS8UoG/thumbnail?ver=thumbnails/cd169769-3564-437b-ae92-28d0bac40c14" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by errorists** [comment]
Regarding content for 'Learn more' and more general any text I'm using in designs, who can we work with to get it proofed and written if needed?

**Comment by rachelhamlin** [comment]
I'm happy to do that. I'll weigh in on copy for the existing screens as well - tomorrow morning.

**Comment by rachelhamlin** [comment]
Exciting to see this one closed 🤩 @siphiuel @yenda
