### ISSUE TITLE
Implement Tribute to Talk chat flow

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7237]
### User Story

As a user looking for new contacts, I want the option to pay tribute to people I am interested in speaking with.

### Description

*Type*: Feature

*Summary*: New system message required.

See [row 3 Figma designs](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1319%3A13403)

cc @errorists for further chat specs.

#### Expected behavior
When I try to chat with a user who has TtT set, I receive the below message with option to pay user. When I choose `Pay N SNT`, a wallet transaction with the correct amount is triggered. 

<img src="https://user-images.githubusercontent.com/15470435/50904317-49bad200-1420-11e9-8b4d-82fd77033948.png" width=250/>

*note* the personalised message is optional and depends on whether user has set one.

This issue & #7235 should use the same `learn more` screen.

**Comment by errorists** [comment]
It would be soo awesome if we gave [this little task](https://github.com/status-im/status-react/issues/6979) a bump while working on this since if we're to add new styles of messages it would be appropriate to use the new, correct colour values in place. 🙏

**Comment by rachelhamlin** [comment]
Good to know - thanks @errorists! I assigned @siphiuel to that one as well, adding to Pivotal board.
