### ISSUE TITLE
'Join chat' presented to user in any group chat after upgrade on to 0.9.33 release build

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7244]
*Type*: Bug

*Summary*: Users who have group chats in 0.9.32 release version (even they were admins who created Group Chat) will be presented with a 'JOIN CHAT' button. After 'Join chat' button tap OR message was sent to this chat, - a system message `[username] joined group` shown (only for user who "joined" the chat again). 

Message history is kept, but those messages sent in group after user upgrade won't be received until contact "joins" group chat again. 

#### Expected behavior
No 'JOIN CHAT' screen after upgrade for the group chat user invited prior upgrade  

#### Actual behavior
'JOIN CHAT' screen after upgrade for the group chat user invited prior upgrade  

### Reproduction

- Install release 0.9.32 build and create new account on Device 1 (UserA)
- Install release 0.9.32 build and create new account on Device 2 (UserB)
- UserA adds UserB in contacts
- UserA (admin) creates with UserB a group chat
- Both exchange messages in the group chat
- Now, UserA(admin) upgrades on to Release 0.9.33 build and logs in to account
- UserA navigates to Group Chat

**Actual result:** 'JOIN CHAT' invitation screen is shown. 
**Expected result:**UserA navigated group chat screen.

- _[Optional step]_ UserB sends text/emoji messages

**Actual result:** 'Join chat' disappears, UserA wind up to group chat and sees all messages + `UserA has joined the group` system message shown only to UserA.  
<img width="270" alt="screenshot 2019-01-09 at 19 17 57" src="https://user-images.githubusercontent.com/8749671/50916624-391c5300-1444-11e9-9cd6-93c4250b1aed.png">

### Additional Information
* Status version: Upgrade from 0.9.32 to 0.9.33 release
* Operating System: Android and iOS

**Comment by asemiankevich** [comment]
@Serhy its not a bug, it was introduced in #7112 PR as a feature (with ugly design for now). It will be improved later. cc @annadanchenko

**Comment by Serhy** [comment]
Yes, I see in https://github.com/status-im/status-react/pull/7112 the note that we agreed for this scenario when upgrading from 0.9.32 to 0.9.33.
I confirmed it should not be the case when upgrading from 0.9.33 to next (0.9.34) release. (Upgrade made from 0.9.33 RC to latest nighly)

Taking this into account and that Group Chats are in Beta state closing this issue.
