### ISSUE TITLE
Automatically join new users into #introductions public channel

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#7245]
As a new user to status I would l like to be entered into a public chat through on-boarding so I can see that there is conversation and I can connect with the community and understand how public chats work.  

This was feedback from a new user joining status and I also believe it would help new users get the hang of Status chats, as well as build the community.   

Not sure of the technical feasibility or how trivial this issue is, so opening it for discussion, UX consequences and feedback because of community member request!

**Comment by pablanopete** [comment]
Screenshots shared from feedback of community member.  
https://monosnap.com/file/DkWNbvHBMCyqHqgtBHE0wdYY74clXc

<img width="616" alt="screen shot 2019-01-09 at 11 37 23 am" src="https://user-images.githubusercontent.com/18363825/50917412-0f8f0780-1403-11e9-8ca7-199b03d8b067.png">

<img width="605" alt="screen shot 2019-01-09 at 11 37 38 am" src="https://user-images.githubusercontent.com/18363825/50917423-13bb2500-1403-11e9-8bdd-fc711ab746c5.png">



<blockquote><img src="https://monosnap.com/facebook/generate_image_preview?id=DkWNbvHBMCyqHqgtBHE0wdYY74clXc" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/DkWNbvHBMCyqHqgtBHE0wdYY74clXc">Screenshot "Monosnap 2019-01-08 18-13-14.png"</a></strong></div></blockquote>

**Comment by rachelhamlin** [comment]
This would be a nice improvement to help new users stick. It's definitely a cold onboarding right now. Will consider this for a future chat iteration, once TtT MVP is shipped.

**Comment by StatusSceptre** [comment]
Possibly even consider adding a “join chat” display if automation doesn’t make as much sense, where a user can see there is not just a blank screen with 0 chats.

**Comment by yenda** [comment]
What is the idea here exactly? To suggest to the user to drop by #status chat? I suppose this requires some UX design flow @hesterbruikman @andmironov

**Comment by pablanopete** [comment]
Yes @yenda as stated above, just logging the issue as it was a newcomers input they wouldn't had noticed public chats without this.

**Comment by hesterbruikman** [comment]
Thanks for bringing the feedback @hutch and looping in @yenda. Expanding on boarding with some sort of intro and improved empty state screens is on the backlog for core, indeed needs a design proposal first.

Will take this along as a requirement.

**Comment by StatusWrike** [comment]
➤ Hester Bruikman commented:

Maciej Zadykowicz  This is a requirement for empty states, synced to a Github issue

**Comment by StatusWrike** [comment]
➤ Maciej Zadykowicz commented:

Hester Bruikman so we automatically populate their chat list with the #introductions channel? I don't like it at all. Imo it should be made easier, that's what the new empty state does, but dumping users there without consent that's not Status-y at all. It's a chat with strangers saying 'Hi', imo to make people feel more welcomed we should present new users with a selection of interest based chat topics and make sure they're active.

**Comment by hesterbruikman** [comment]
Makes sense and this is open to whatever solution you think is best. Underlying reason is that quite a few channels don't have 24/7 communication so they might appear empty. A system requirement could be that we need a dynamic list based on trending channels to fix that.
