### ISSUE TITLE
Contact Requests

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7250]
### User Story

_Send requests_
As a user, I want to send contact requests to friends in Status so that I can see their display names and photos, and circumvent Tribute to Talk for people I know.

_Receive requests_
As a user, I want to review my list of contact requests and either approve or ignore them. 

As a user, I want to be notified when I have a new contact request in case someone I know is trying to reach me over Tribute to Talk. 

### Description

*Type*: Feature

*Summary*: 

Contact management is important in a world where being in a user's contacts significantly enhances your experience of chatting with them.

Three key needs from contact management:
+ Contact request 
+ Remove contact 
+ Unblock (non) contact 

The scope of this issue is confined to **contact requesting**.

Contact requests offer a workaround to Tribute to Talk, for two users who know each other, and is also helpful for enhancing the experience of two users.

#### Expected behavior
This issue is a placeholder for now. 

[WIP progress designs ](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=259%3A0)

**Comment by flexsurfer** [comment]
@rachelhamlin is this still relevant?

**Comment by errorists** [comment]
I might return to it later, much later. for now I see it as unnecessary seeing as contacts don't have much use, it's just a name on a list.

**Comment by rachelhamlin** [comment]
We have a quite a few new considerations w/r/t contacts and identity/account contracts in Status:

- Conversations with 3box for social profiles, which Ricardo would like to support
- ENS usernames
- Universal login
- EIP 2429 friend recovery

Perhaps we need to launch a new swarm to figure out how all these parts work together, and what our priorities are.

**Comment by errorists** [comment]
oh for sure, like the idea! currently I'm investigating [sharing account details with contacts](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4248%3A147), this could be included too

**Comment by cammellos** [comment]
Closing for now as it seems outdated, @errorists feel free to re-open if you think it should stay open.
