### ISSUE TITLE
'Ethereum node started incorrectly error' when app starts from universal link for extension

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7253]
***Type***: Bug
***Summary***: Status app is not running. When user navigates to universal link for extention app starts but right away the `Ethereum node started incorrectly error` appears.

#### Expected behavior
Navigation to 'Extension' screen with extension data users is about to install happens after login to account if user started Status from extension universal link. After user tap 'OK' status crashes and closes

#### Actual behavior
'Ethereum node started incorrectly error' when app starts from universal link for extension
<img width="327" alt="screenshot 2019-01-10 at 17 41 41" src="https://user-images.githubusercontent.com/8749671/50979389-06836080-14ff-11e9-82fe-236924f1b004.png">

### Reproduction

- Status app is closed
- In external browser open `https://get.status.im/extension/ipfs@QmYnUj7v3UiP6X1YfRuhea5mXpjTGG1KKnCwFS4TKzKTpD` link -> tap `Open in Status` 
**OR**
- scan QR code with camera (iOS or Android device which support QR code scan with native camera app) -> tap on `Open in Status` pop-up
- Log in to account

### Additional Information
* Status version: Release/develop 0.9.33
* Operating System: Android and iOS

#### Logs

LogCat logs for when app crashes 
 : 
```
...
01-10 17:45:26.728 10737 10791 E ReactNativeJS: ERROR [status-im.utils.fx:30] - Merging fx with common-keys:  #{:db :extensions/load}
01-10 17:45:26.750 10737 10792 E unknown:ReactNative: console.error: "ERROR [status-im.utils.fx:30] - Merging fx with common-keys:  #{:db :extensions/load}", stack:
01-10 17:45:26.750 10737 10792 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$3@12:346554
...
...

```
(full logcat when app starts from Extention universal links is here [logcatExt.log](https://github.com/status-im/status-react/files/2746055/logcatExt.log))
[Geth.log](https://github.com/status-im/status-react/files/2746057/geth.22.log) with debug level

**Comment by Serhy** [comment]
https://github.com/status-im/status-react/issues/6166 is related

**Comment by jeluard** [comment]
@Serhy Looks like it's fixed now?

**Comment by Serhy** [comment]
Indeed, @jeluard. Can't reproduce anymore with 0.10 release (and same with related issue #6166 which looks good now). Closing this issue.
