### ISSUE TITLE
Add new asset for Ethdenver event 

### ISSUE THREAD

**Issue by StatusSceptre** [status-im/status-react#7266]
This is for a custom token on XDAI network

we'll need address, name, symbol and icon image should be added 

For public release 0.9.34

**Comment by pablanopete** [comment]
part of #7224 release needs.

**Comment by rachelhamlin** [comment]
cc @goranjovic - a request for ETHDenver

**Comment by StatusSceptre** [comment]
@austintgriffith to help update when there's more information available.

**Comment by rachelhamlin** [comment]
Hey guys! Do you think this token will be ready by end of week? That's the safest deadline to guarantee that it makes it into the public release.

@pablanopete @austintgriffith

**Comment by dbe** [comment]
Hey @rachelhamlin,

I'm working on the burner-wallet with Austin for ETH Denver. We are going to come up with a firm code freeze data asap and can update this at that point.

One quick question: Does the contract address for our token need to be hard-coded and sent out as part of a release, or is that something we could update dynamically in case there were any changes we were forced to make to the token contract. I'm trying to get a picture of how frozen the contract needs to be.

**Comment by rachelhamlin** [comment]
Hey @dbe - unfortunately at this point, we hard code token addresses :( So there is pressure to include it in time for testing and release.

**Comment by austintgriffith** [comment]
Hey guys, we will *for sure* have a token contract address for you by the 30th. 
We'd like to get everything we can possibly think of tested by then. 
We will try to have it sooner, but there are just things we want to make sure get included. 
One thing we should mention is there is a chance something new comes up that causes us to run on a new token. So the status app would be on the old token. 
Is there at least a way you guys can deploy with some sort of a deadman switch in case we have to patch the contract days before the event?

**Comment by rachelhamlin** [comment]
That's great news, @austintgriffith. Pinged @goranjovic on Status, as he's the one to answer your question. Will check back in for updates.

**Comment by goranjovic** [comment]
> Is there at least a way you guys can deploy with some sort of a deadman switch in case we have to patch the contract days before the event?

Unfortunately, no. If you change the contract, we can only re-release, which isn't a quick process.

**Comment by Swader** [comment]
@goranjovic why not use a proxy contract and then replace the implementation being referenced behind the scenes if needed?

**Comment by mandrigin** [comment]
I agree with @Swader but I guess this question is more suitable for @austintgriffith to answer...

**Comment by austintgriffith** [comment]
Yeah we could probably set something up like that if we have time. Let me ping @dbe on this too.

**Comment by rachelhamlin** [comment]
Apologies to be pushy about it @austintgriffith but roughly how much longer are we looking at for a contract we can use here? Does by the 30th likely = the 30th at this point?

**Comment by austintgriffith** [comment]
Okay, we finally got it audited, deployed, and verified:
https://blockscout.com/poa/dai/address/0x3e50bf6703fc132a94e4baff068db2055655f11b/contracts

Name: buffiDai
Symbol: BUFF
Address: 0x3e50bf6703fc132a94e4baff068db2055655f11b
Image:
![bufficorn](https://user-images.githubusercontent.com/2653167/52166924-ba2bda80-26d0-11e9-9635-4355afdb835c.png)


<blockquote><img src="/poa/dai/images/favicon-4b07bf6e08598841211159d4f56ce08d.ico?vsn=d" width="48" align="right"><div><strong><a href="https://blockscout.com/poa/dai/address/0x3e50bf6703fc132a94e4baff068db2055655f11b/contracts">ERC20Vendable (0x3E50BF6703Fc132A94E4BAfF068db2055655f11B) - xDai Chain Explorer</a></strong></div><div>View the account balance, transactions, and other data for 0x3E50BF6703Fc132A94E4BAfF068db2055655f11B on the (xDAI)</div></blockquote>

**Comment by austintgriffith** [comment]
Here is a new image, they wanted to float the dai logo on top:
![buffidailogo](https://user-images.githubusercontent.com/2653167/52167607-011ecd80-26db-11e9-8650-af771fac2a90.png)

**Comment by rachelhamlin** [comment]
Great work guys! 

@austintgriffith can we get some tokens for testing? You can send to 0x06E7D699c4842E712E32d66C15F7e451c0E2a496

**Comment by guylouis** [comment]
@goranjovic @mandrigin can we add support for this BUFF token in 0.9.33 ?

**Comment by austintgriffith** [comment]
So, anyone can buy into buffiDai. You just go to buffidai.io, click exchange, and move xDai into buffiDai: 
![image](https://user-images.githubusercontent.com/2653167/52221545-9d251200-285e-11e9-9054-eec556ebafc2.png)

Also, I sent you $0.25 in BUFF:
![image](https://user-images.githubusercontent.com/2653167/52221604-c0e85800-285e-11e9-9ef8-e61d71cac2c7.png)

**Comment by rachelhamlin** [comment]
**Nvm** - I'm told tokens have changed hands :) cheers! 

Hey @austintgriffith @dbe! Just a reminder - we need some test tokens to make sure things are working properly, although the token's been merged and should be included in our release. 

Can you send some tokens for testing to 0x06E7D699c4842E712E32d66C15F7e451c0E2a496?

**Comment by StatusSceptre** [comment]
Hey this has been taken care of w/ anna Out of band! Thx.

**Comment by austintgriffith** [comment]
@rachelhamlin it looks like that address has 0.25 BUFF. https://blockscout.com/poa/dai/address/0x06e7d699c4842e712e32d66c15f7e451c0e2a496/transactions
You can also bridge into buffidai.io in the Exchange section. 
Do you guys need more tokens or did you get it solved?

<blockquote><img src="/poa/dai/images/favicon-4b07bf6e08598841211159d4f56ce08d.ico?vsn=d" width="48" align="right"><div><strong><a href="https://blockscout.com/poa/dai/address/0x06e7d699c4842e712e32d66c15f7e451c0e2a496/transactions">0x06E7D699c4842E712E32d66C15F7e451c0E2a496 - xDai Chain Explorer</a></strong></div><div>View the account balance, transactions, and other data for 0x06E7D699c4842E712E32d66C15F7e451c0E2a496 on the (xDAI)</div></blockquote>

**Comment by rachelhamlin** [comment]
All set @austintgriffith. Just overlooked that pre-coffee this morning. Thanks though!
