### ISSUE TITLE
Timestamps in chat list don't match timestamps of last sent messages

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7270]
### Description

*Type*: Bug

*Summary*: timestamps in chat list differ from timestamps of last sent message, and basically time of fetching message is displayed instead.

#### Expected behavior
can see timestamp of last sent message in both chat list and chat

#### Actual behavior
 time when message was fetched is shown in chat list
<img width="417" alt="img_0d55f218135a-1 jpeg 2019-01-14 16-53-41" src="https://user-images.githubusercontent.com/4557972/51175184-dd295280-18b9-11e9-9532-53b70bfafb44.png">

### Reproduction

- Open Status
- Join any public chat
- Close app
- Sent to public chat any message from other device
- Wait >1 min
- Open Status, login and check  last message timestampt in chat and chat list

### Additional Information

* Status version: nightly 15/01/2019
* Operating System: all

**Comment by Swader** [comment]
Also easy to replicate by issuing a sync and then observing that the device TO which messages were synced has fetched chats displayed as more recent than those actually recently used.

**Comment by rachelhamlin** [comment]
@annadanchenko @rasom @mandrigin we decided to prioritise this bug on our backlog grooming call yesterday. I now realise it's related to work @rasom is doing for message performance optimisation. Would you be willing to take it on under core?

**Comment by churik** [comment]
cc @rachelhamlin - it is supervisible for all users, and it was reported several times in `#status` channel
