### ISSUE TITLE
Address and web3 authorising permission window disappears right away ENS/Voting dapp home view loads

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7274]
***Type***: Bug

***Summary***: With enabled browser privacy mode we ask users for permissions to Wallet address and enabling web3 in a pop-up. In latest ENS Dapp respective pop-up disappears right away after Dapp screen loads. This makes ENS Dapp screen unresponsive.
We need to persist and keep web3 + address permission access pop-up in that case on Status browser level

Note: it's OK with iOS Status browser
Note2: all fine with 'browser privacy mode' = OFF

#### Expected behavior
Address and web3 permissions pop-up keep stay after navigation to ENS Dapp with 'Browser privacy mode' enabled account setting

#### Actual behavior
Address and web3 permissions pop-up disappear after navigation to ENS Dapp with 'Browser privacy mode' enabled account setting. ENS Dapp unresponsive for taps after that. 
Links to video of the behavior https://drive.google.com/file/d/1-7HbevTwJH8m4oMo-ffcfnR6fydwJ6RA/view?usp=sharing

### Reproduction

- Open status and create new account
- Navigate to `Profile` -> `ENS names` (or open ENS dapp link https://ipfs.infura.io/ipfs/QmWCEQ4RRoQxSEcuQvaoTG5kyPcCMbsmqpykp1Y95MyLjm directly in status browser) 
- Check that `"names.statusnet.eth" would like to connect to your wallet`  is shown until you tap on allow/deny

### Additional Information
* Status version: Develop 0.9.33 (It's **all OK** with **Release 0.9.32** version)
* Operating System: Android

#### Logs

[logcat.log](https://github.com/status-im/status-react/files/2759621/logcatbla11.log) logs before tap upon ENS Daap from Profile screen

<blockquote><div><strong><a href="https://ipfs.infura.io/ipfs/QmWCEQ4RRoQxSEcuQvaoTG5kyPcCMbsmqpykp1Y95MyLjm">Status.im Domain Registration</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
on Android 9, today's nightly build:
- Open status and create new account
- Navigate to Profile -> ENS names 
Result: popup with permission request is shown for very short moment and than is hidden, so I can tap on Allow/Deny. If tap on "Let's go" button then nothing happens

**Comment by rachelhamlin** [comment]
Works fine for me on iOS. 

New account -> ENS names -> pop-up appears and remains until I take action.

**Comment by Serhy** [comment]
Same issue with Voting Dapp (https://vote.status.im) as well

<blockquote><div><strong><a href="https://vote.status.im/">Status.im - Survey</a></strong></div></blockquote>
