### ISSUE TITLE
Random 'java.lang.NullPointerException' at attempt to start 0.9.32-1

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7281]
### Description

*Type*: Bug
*Summary*: sometimes at attempt to start build 0.9.32-1 'java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Messenger.send(android.os.Message)' on a null object reference'. Can't reproduce manually, can be random.

#### Expected behavior
can start app

#### Actual behavior
<img width="192" alt="sdfsadf" src="https://user-images.githubusercontent.com/4557972/51191456-b3d1ec00-18e4-11e9-9fcf-f17da052e1d7.png">

### Reproduction

- Open Status

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release 0.9.32-1 (staging fleet is set by default, used this [custom build](https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32-1/lastSuccessfulBuild/artifact/pkg/StatusIm-181217-093744-07a7a5-e2e.apk) 
 Status version: release 0.9.32-1 (beta fleet is set by default)
* Test in SauceLab (staging): https://app.saucelabs.com/tests/0b8d26472cf5459d8d3becac3a036aa3/commands?auth=05a66084424f252494761160912f052d#22
* Operating System: Android

#### Logs

[logcat-1.txt](https://github.com/status-im/status-react/files/2760329/logcat-1.txt) (staging)
[logcat.txt](https://github.com/status-im/status-react/files/2782430/logcat.txt) (beta)

**Comment by mandrigin** [comment]
@antdanchenko is it possible to reproduce it (even in autotests) on the current nightlies? If so, I can take a look at it.
