### ISSUE TITLE
Crash when pasting public address into a field with existing text.

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#729]
Android user reporting a crash following pasting public address into a field with existing text.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/169?status=New

Console log does not contain anything obvious as to what is causing the issue.

**Comment by rasom** [comment]
The original report message is a bit vague, I cannot reproduce this bug.

**Comment by alwx** [comment]
If I paste long text to this field, I see the same problem. So probably it's somehow related to the text length.

**Comment by alwx** [comment]
Hm, tried to reproduce it now, but without any success. There is a change that this bug has already been fixed.

**Comment by rasom** [comment]
You are right, it was fixed here https://github.com/status-im/status-react/issues/649
