### ISSUE TITLE
Loading iframe in Status Browser

### ISSUE THREAD

**Issue by zachferland** [status-im/status-react#7292]
## Intro
Our lib [3box](https://github.com/3box/3box-js) uses an iframe to share ipfs/orbitdb data locally across domains (vs syncing everything from server each new domain).

## Issue
 Iframe works in all major browsers but has failed in all mobile dapp browsers (IOS at least, haven't got an android device to test on yet) including Status wallet. Seems like this could have to with the 'WebViews' (WKWebView on IOS) in the mobile app and maybe permissions in 'WKNavigationDelegate'. Wondering if there are stricter CORS policies in these webviews. Any mobile devs here have any insight? We are bit lost at what it could be and without any error feedback cant pinpoint it further.

Found this doc - https://notes.status.im/s/rJ0SO5tpQ But didn't find anything related there.

<blockquote><div><strong><a href="https://notes.status.im/s/rJ0SO5tpQ">Status Dapps browser - CodiMD</a></strong></div><div># Status Dapps browser  Currently to display web dapps content we use `react-native-webview-bridge` </div></blockquote>

**Comment by pablanopete** [comment]
Thanks for opening this issue @zachferland - pinging  @flexsurfer who might be able to help point out where the issue lies in the browser.

**Comment by zachferland** [comment]
Revisited again later in the day, after a bit of time, was able to build and run the app (Status) in the simulator (IOS) and capture some error output with the inspector. Looks like it may not actually be the iframe alone, but iframes (with differing origins) that use IndexedDB. Not exactly sure if this yet, and not clear why this is only the case in webview (not safari generally), this may also only be IOS (safari). Going to try a minimized example to check if really IndexedDB. 

Here was the error output: 
```

[Error] SecurityError: IDBFactory.open() called in an invalid security context
   open (index.min.js:1:1063975)
   _open (index.min.js:1:1063975)
   open (index.min.js:1:1074402)
   _open (index.min.js:1:502555)
   open (index.min.js:1:4625)
   _open (index.min.js:1:366984)
  open (index.min.js:1:370993)
  open (index.min.js:1:1081241)
   g (index.min.js:1:1080752)
   g (index.min.js:1:1080372)
   l (index.min.js:1:353149)
   e (index.min.js:1:742802)
   x (index.min.js:1:748153)
   exports (index.min.js:1:2561637)
   k (index.min.js:1:2539224)
   Eval Code (iframe.js:24)
   eval
   /iframe.js (iframe.js:107)
   **webpack_require** (iframe.js:30)
   (anonymous function) (iframe.js:94)
   (anonymous function) (iframe.js:95)
   webpackUniversalModuleDefinition (iframe.js:7)
   Global Code (iframe.js:10)
```

**Comment by jeluard** [comment]
@zachferland Can you detail what you mean by iframe don't run? Do you need `web3` features available from the iframe?

**Comment by zachferland** [comment]
@jeluard specifically thought loading the iframe was blocked due to some policy in the webview that differed from other browsers. But after looking into it before, I specifically mean it throws the error in the comment above (found from running status app in simulator (IOS)), which I think is indexeddb, which then blocks orbitdb/ipf from running in the iframe. Don't need any web3 features in the iframe. Trying to pinpoint further now if this is really indexeddb and why is this the case. Let me know if that makes sense.

**Comment by jeluard** [comment]
I guess it does? Could you try to reproduce with a simple iframe doing some indexedb things?

**Comment by zachferland** [comment]
yup! that's the plan, will try to create a minimal example that creates the same error, will post here how it goes

**Comment by zachferland** [comment]
Turns out it is a general safari constraint, that differs from other browsers (including chrome/firefox). Not an IOS/Webview specific issue, but had not realized since always testing on desktop with metamask and chrome/firefox. Iframe can't use IndexedDB storage when not same origin. But can use local storage, seems this is true because historically this was the behavior, but was not enabled when indexedDB was added, don't know why this differs from other browsers. 

Replicated same error with minimal example here - https://github.com/3box/3box-iframe-browser-test

Thanks @pablanopete and @jeluard for the quick follow up! This is issue is resolved then, nothing specific to Status.

@jeluard one more question, is there any more details on this issue https://github.com/status-im/status-react/issues/7063. Not being able to persist localstorage would make our lib extremely slow, is this a constraint or just something not yet implemented in status? and do you know if the same also true for IndexedDB?

<blockquote><img src="https://avatars3.githubusercontent.com/u/45031480?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/3box/3box-iframe-browser-test">3box/3box-iframe-browser-test</a></strong></div><div>Use for testing simple assumptions about browser features - 3box/3box-iframe-browser-test</div></blockquote>

**Comment by jeluard** [comment]
@zachferland Right this is something we plan to implement. Not entirely sure about IndexedDB but probably not persisted either.

**Comment by zachferland** [comment]
Got around to trying localstorage and indexeddb in a simple example and it was persisted, at least for apps at domains. But of course not for dapps fetched from ipfs as referenced elsewhere.

**Comment by pleerock** [comment]
Hey guys, having the same issue with ipfs, were you able to resolve the issue?
