### ISSUE TITLE
Error on running app "status_im.react_native.js_dependencies.keychain.SetUsername is not a function"

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7299]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Error "status_im.react_native.js_dependencies.keychain.SetUsername is not a function" is shown if start the app after installing last nightly (fresh install not update). See it on Windows and @jakubgs says it's on Linux too.

**Comment by mandrigin** [comment]
this was an issue in our fork that I fixed recently, see this commit: https://github.com/status-im/react-native-keychain/commit/33eb25baf359414f7a30a34a0298a6347f698138

maybe we need to have an dependency upgrade

**Comment by churik** [comment]
@mandrigin can you please help with it?

**Comment by mandrigin** [comment]
I think @vkjr should know what to do, probably just update the react-keychain dependency there.

**Comment by mandrigin** [comment]
@PombeirP can it be related with the stuff you did with dependencies?

**Comment by vkjr** [comment]
@PombeirP, in your changes `react-native-keychain' tag points not to the last commit - https://github.com/status-im/react-native-keychain/releases

This one is the last one and contains fixes from @mandrigin related to `setUsername` function - https://github.com/status-im/react-native-keychain/commit/33eb25baf359414f7a30a34a0298a6347f698138

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-keychain">status-im/react-native-keychain</a></strong></div><div>:key: Keychain Access for React Native. Contribute to status-im/react-native-keychain development by creating an account on GitHub.</div></blockquote>

**Comment by pedropombeiro** [comment]
I tried to make the tags point to the same commit SHA, but there was one exception which looked harmless to use the same commit on mobile and desktop, let me check if that was the one.

**Comment by pedropombeiro** [comment]
@vkjr develop was pointing to https://github.com/status-im/react-native-keychain/commit/ea1bfe6b803ab712d6009a40267db820ce2ec2cd, and my upgrade moved it to the following commit: https://github.com/status-im/react-native-keychain/commit/43e5512cabb8ee064fd9e503be943dcf2c7d7669. I guess that was a bad commit and we need https://github.com/status-im/react-native-keychain/commit/33eb25baf359414f7a30a34a0298a6347f698138 ? I remember thinking I needed to use the latest one but clearly that fell through the cracks.

**Comment by vkjr** [comment]
@PombeirP, I'm updating and checking PR with fix right now.
