### ISSUE TITLE
Error message when launching Maker Market.

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#731]
Android user reports error message upon launching Maker Market, after having visited Oaken Console and Auction House DApps.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/158?status=New

![image](https://cloud.githubusercontent.com/assets/25023739/21971006/75385554-dc11-11e6-9830-fd554053f348.png)

``` Error on param suggestions [{:command {:color "#7099e6", :description "Confirmation code", :has-handler false, :name "confirmation-code", :params [{:name "code", :type "number", :value nil}], :suggestions-trigger "on-change", :type :response}, :content nil, :chat-id "console"} {:error "ReferenceError: 'call' is not defined"}]```

**Comment by rasom** [comment]
duplicate #652
