### ISSUE TITLE
Empty error pop-up when sending tx from Wallet to contact if public/group chat at the top on Home screen

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7332]
***Type***: Bug

***Summary***: When transaction is sent from Wallet to the contact from contacts list but there is a public or group chat stands at the top of Home screen - there is an empty `Error` pop-up appears ( `Invalid push notification payload...` in logs). `/send ` message is sent in respective 1-1 chat though after transacting from Wallet.
It's all fine if the contact I send TX to is the latest chat I had with (so this contact stands at the top of Home screen). It's also fine when Dapp is the latest item on Home screen

#### Expected behavior
No errors when sending tx from Wallet to contact if public/group chat at the top on Home screen
#### Actual behavior
Empty error pop-up when sending tx from Wallet to contact if public/group chat at the top on Home screen
<img width="324" alt="screenshot 2019-01-24 at 13 18 04" src="https://user-images.githubusercontent.com/8749671/51674849-8f5bcb00-1fda-11e9-865b-794fa3cffd24.png">

### Reproduction

- Open Status and recover an account with assets (Contact1)
- Create another contact (Contact2)
- Contact2 sends contact request to the Contact1 and sends text message
- Contact1 navigates to 1-1 chat and taps 'Add to contacts'
- Contact1 joins public chat (e.g. `#testpushwallet`) and sends a text message there
- Contact1 navigates to `Wallet` -> `Send`
- Contact1 selects Contact2 from `Choose recipient` -> Contact2
- Contact1 specify amount to send (e.g. 0.00001, ETH Asset stays by default)
- Contact1 signs the transaction

### Additional Information
* Status version: Develop `0.9.33 (2019012408) status-go v0.19.0-beta.1`

* Operating System: Android and iOS

#### Logs

```
01-24 11:01:24.686 27506 27616 I ReactNativeJS: ***
01-24 11:01:24.686 27506 27616 I ReactNativeJS: NAME: nil
01-24 11:01:24.686 27506 27616 I ReactNativeJS: MESSAGE: "Invalid push notification payload{:from \"0x043a5583b23ed88ef030fe4636c8cf7d5bace61f928a626726dacc9f1ece90012f5cfc7a141d883a6b86254f743fc52c8343496c28152cbe2aad920b7fbaa6e2bd\", :to nil, :id \"0x6b4e146b37eab0662ce9db71ef9864b0bf657fe3497c3197cc7158349b357394\"}"
01-24 11:01:24.686 27506 27616 I ReactNativeJS: 
01-24 11:01:24.686 27506 27616 I ReactNativeJS: 
01-24 11:01:24.686 27506 27616 I ReactNativeJS: 
01-24 11:01:24.686 27506 27616 I ReactNativeJS: ***
```

**Comment by annadanchenko** [comment]
same issue also exists in #7294 with new status-go (beta 9)

**Comment by Serhy** [comment]
Updated description, as it appeared that it's all fine in certain cases.
Issue appears when TO the contact who will sent transaction later - the contact-request been sent by a future recipient.

**Comment by vitvly** [comment]
Strange, but I still cannot reproduce it. What I did:

1. Create a new account (Android emulator).
2. Send it some funds from Metamask (Mainnet)
3. In emulator, copy Status address and click `Join private chat` in Status Desktop. Then send a message there.
4. In emulator, I see a new chat, go there, click `Add to contacts`.
5. In emulator, click `Join public chat` and join `testissue1`.
6. In emulator, send a message to `testissue1`.
7. In emulator, go to Wallet and send some ETH to Status Desktop contact.
