### ISSUE TITLE
null is not an object (evaluating 'e.cljs$core$IFn$_invoke$arity$1') Error

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7337]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After opening app there is null is not an object (evaluating 'e.cljs$core$IFn$_invoke$arity$1') Error

Can't repro myself. @jarradh can

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33 (2019012103)
* Operating System: Android

#### Logs
[geth.log](https://github.com/status-im/status-react/files/2795372/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2795373/Status.log)

**Comment by arnetheduck** [comment]
Just hit this this on android.. got a notification (actually, two), clicked on it and the message appeared.

status version 0.10.0 2019022807

![screenshot_20190305_194203_im status ethereum](https://user-images.githubusercontent.com/1382986/53850031-941f8180-3f7f-11e9-9121-2fa740178863.jpg)

**Comment by churik** [comment]
Didn't see it during testing after release Status-v1.0.1
Please reopen if it is still relevant for someone.
