### ISSUE TITLE
Add Aragon to DApp list

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7346]
#### Expected behavior
Aragon listed in DApp list.

Add to `Utilities` list.

Order below `3Box`. 

Name: `Aragon`
URL: https://mainnet.aragon.org
Logo: [use white vertical](https://wiki.aragon.org/design/logo/)
Description: `Build unstoppable organizations on Ethereum`

**Comment by rasom** [comment]
a short description is also required

**Comment by rasom** [comment]
probably "Build unstoppable organizations on Ethereum"

**Comment by rachelhamlin** [comment]
Thanks @rasom!
