### ISSUE TITLE
Blank screen when launch MacOS build after fresh installation

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7348]
***Type***: Bug

***Summary***: After fresh install of MacOS build there is a blank screen when user launches Status. No Status.log (Status folder created but it's just empty). system.log shows only ```Status[1493]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug```
Note, it's all fine when I:
- install Release 0.9.0 version. Then delete ~/Library/Application\ Support/Status (with folder) completely -> delete Status from Applications. So looking like next instalation is "fresh". But after that install latest nightly with replacing release application version - it's all fine and I created an account successfully
- It's OK if upgrade from Release to Nigtly (without flushing Stasus folder)

#### Expected behavior
After fresh MacOS install I see create/recover an account screen and can create an account

#### Actual behavior
Blank screen when launch MacOS build after fresh installation

### Preconditions
There no ~/Library/Application\ Support/Status folder at all
There is no Status in Applications exist
Reboot the system

### Reproduction
- Download latest develop build and install it
- Launch Status

### Additional Information
* Status version: Develop 0.9.0 (16b657)
* Operating System: confirmed with MacOS Mojave 10.14.2 (and 10.14.3)

#### Logs

There is no logs at all created. Only system.log 
```Status[1493]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug ```

**Comment by cammellos** [comment]
I had a similar issue on Linux, so probably not macos only.
I was testing some stuff and removed my Status directory, and I could not create an account. Only after I restored the directory the app worked again, although with the existing accounts.

**Comment by vkjr** [comment]
Wasn't able to reproduce this with Mojave 10.14. Will try updating to 10.14.3
