### ISSUE TITLE
 Fetching animation and  "Connected..." / "Offline"status bars are placed on the bottom of the chat area

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7351]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: introduced by https://github.com/status-im/status-react/pull/7141 - on desktop fetching animation and status messages are placed on the bottom of chat area.

#### Expected behavior
fetching animation and status bar are shown below the header on chat area

#### Actual behavior
![pffl](https://user-images.githubusercontent.com/4557972/51828639-4e222e80-22ec-11e9-900a-19106c44b6cd.png)

### Reproduction

- Open Status
- Open any chat
- Go to offline

### Additional Information

* Status version: nightly 28/01/2019
* Operating System: Mac OSx, Linux, Windows

**Comment by vkjr** [comment]
@yenda, will you take fixing this one?
