### ISSUE TITLE
Change confirmation screen link styling [Kyber extension polish]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7356]
### Description

`Back to exchange` link is too subtle. Can we use button styling instead?

#### Expected behavior
`Back to exchange` link uses a button or other component to look more like a CTA.

#### Actual behavior
[comment]: # (Describe what actually happened.)
<img src="https://user-images.githubusercontent.com/15470435/51833617-3c468880-22f8-11e9-9af4-e1019914bcb7.png" width=200/>

**Comment by denis-sharypin** [comment]
@jeluard how can I try this extension out?

**Comment by jeluard** [comment]
@denis-sharypin Just scan the QR code that you find after clicking publish from within status.
Do you have access to figma files?

**Comment by rachelhamlin** [comment]
There's no link to the extension on this issue :) but it's here - https://status-im.github.io/pluto/try.html?hash=QmeqDrXwwwesgb6Dj9UurtgX1VoS4h6tApxLTLU1BSD7Vo

@denis-sharypin 

<blockquote><img src="/pluto/img/favicon.png" width="48" align="right"><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by jeluard** [comment]
🤦‍♂️

**Comment by denis-sharypin** [comment]
@rachelhamlin, @jeluard , what do you think about following already [existing and implemented wallet designs ](https://www.figma.com/file/SIeZPHvrX7KUwEBW8VQct8C5/New-send-transaction?node-id=649%3A0) and use such design:

<img width="483" alt="screenshot 2019-01-29 10 45 43" src="https://user-images.githubusercontent.com/6559881/51899322-13cf9480-23b3-11e9-8dd5-3f30b919f956.png">

Also, I think it's important to mention the amounts (missing in the current implementation)

**Comment by rachelhamlin** [comment]
Okay for me @denis-sharypin! Would you be able to make this change this week @jeluard? 

Amounts are something that are dependent on a change to pluto, but also in the works.

**Comment by jeluard** [comment]
Nice! Sure I will look at it soon.
@denis-sharypin How about the 2 other final screens (pending and failed)? Should they be updated too?
Figma: https://www.figma.com/file/D942buO2kd96KZQNIikjsPm9/Kyber-extension?node-id=0%3A1

<blockquote><img src="/file/D942buO2kd96KZQNIikjsPm9/thumbnail?ver=thumbnails/6029ad37-85c9-4fbb-a9e9-e2b484e82ef7" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/D942buO2kd96KZQNIikjsPm9/Kyber-extension">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by denis-sharypin** [comment]
@jeluard yeah sure, I updated those screens. Thanks!
