### ISSUE TITLE
Private group chats and missing messages from certain peers

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7362]
Sometimes in a private group chat messages are missing from a particular peer.

We don't have exact steps to replicate, but one description is:

Create group chat on A, with B and C.

A sends a message to B, B is able to receive it, but when replying A won't see their response.

We haven't been able to replicate and have access to logs, so please add `geth.log` in your comment.

The most likely explanation is that it is due to multiple devices present (re-installing etc), as the encryption is device-to-device, and the system has not picked up the devices correctly.

There's currently a mechanism to handle such cases, but is not toggled on yet, also https://github.com/status-im/status-react/pull/7342 will help keeping this information up to date. 

Update:

1) One issue was due to the fact that certain nightly were publishing on a separate topic, that has been disabled for now, so it should not impact it anymore.
2) Another issue reported is that if you join on device A, and device B is offline, some of the messages that are sent before B receives the join notification are lost (can be retrieved from the mailserver, but they might already be in the dedup cache)

**Comment by churik** [comment]
OK, on my account I can't receive invitations to group chats anymore if they are sent from a particular user.

So as `userA` I received ~4-5 invites to group chats from `userB` and was able to chat normally but after some regular message I can't receive messages in group chats and invitations to group chat from `userB` anymore
in my case `userA` - reproducible for both devices with `userA` account, on 1 device (Mac OS) - nightly 30.01.2019, on device 2 - 0.9.32 release 

`User B` - 0.9.33 (2019013112) status-go v0.19.0-beta.9 / Develop 0.9.33

Geth.log for `UserA` (in this case as `User B` I send invite to group chat and send several messages to this chat; `UserA` can't receive an invitation):
[geth.log](https://github.com/status-im/status-react/files/2821175/geth.log)

**Comment by churik** [comment]
@cammellos does it make sense to keep it open?

**Comment by cammellos** [comment]
This can be closed
