### ISSUE TITLE
Hook pluto extension lifecycle

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#7363]
### User Story

As a developer, I want my extension lifecycle to be respected.

Note that ephemeral extensions (`ephemeral?` boolean in `meta` section) should not be installed nor persisted.

Blocked by https://github.com/status-im/pluto/issues/13

### Description

*Type*: Feature

**Comment by jeluard** [comment]
@tbenr You might enjoy this one too :D

**Comment by tbenr** [comment]
OK! that's interesting!
