### ISSUE TITLE
Add "Learn more" TtT screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7367]
### User Story

As a user, I want more information about Tribute to Talk so that I can fully understand the feature. 

### Description

*Type*: Feature

*Summary*: Add `Learn more` screen into TtT flows. There are two versions for two different places:

1. For the person setting tribute (TtT settings)
2. For the person seeing chat pay wall

#### Expected behavior
1. (this issue) Settings flow contains learn more link, and appropriate screen.  Screen is called [Learn more from TtT setup flow](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1319%3A13403).

2. Chat paywall screen contains learn more link, and appropriate screen (Learn more from TtT paywall).

#### Actual behavior
`Learn more` screen hadn't been designed during settings implementation.

**Comment by rachelhamlin** [comment]
@errorists will you just confirm when `Learn more` screen is ready for implementation? :)

**Comment by vitvly** [comment]
I've added a "Learn more" screen for the tribute owner in scope of #7304 : https://github.com/status-im/status-react/blob/bac946edb905c93324bdd5f73c02c55d14a8c629/src/status_im/ui/screens/profile/ttt/views.cljs#L216, so maybe it can stay in scope of that PR.

**Comment by rachelhamlin** [comment]
Great - assuming it uses the right copy? I'll close this.
