### ISSUE TITLE
Push notification is shown only on one device even if there are several paired devices with same account

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7368]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Push notification is shown only on one device while same account can be recovered on several devices and these devices can be paired, so user would expect to have same behaviour (getting PN, messages, contacts, chats) on all devices with same account.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
PN is shown on all paired devices where same account exists
#### Actual behavior
[comment]: # (Describe what actually happened.)
PN is shown only on one of such devices
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Recover same account on 2 devices and pair them
- Add a contact 
- get new message in 1:1 chat from added contact while app is on background or closed on both devices
- check if push notification is shown on both devices that just received a message

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33
* Operating System: Android and iOS

**Comment by cammellos** [comment]
@churik this should now work as expected (limited to 3 devices, if you have more hanging around, then you might get inconsistent behavior), should we close it?

**Comment by churik** [comment]
Yes, for sure! Don't know why `fixes` keyword didn't make it in #7426
