### ISSUE TITLE
'Shake to report bug' message not appearing in selected language.

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#737]
Android user who selected Italian as their language has shown that the 'Find a bug or have a suggestion?' is not in their chosen language, rather it has defaulted to English.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/65?status=New

![image](https://cloud.githubusercontent.com/assets/25023739/22051678/c4213f98-dda9-11e6-87db-13d49727b391.png)

**Comment by alwx** [comment]
It looks like `react-native-instabug` package doesn't support most of the possible locales:
https://github.com/Kennytian/react-native-instabug/blob/master/android/src/main/java/com/kenny/instabug/InstabugModule.java#L106

The solution is time-consuming but pretty straightforward.

**Comment by gdeer81** [comment]
@alwx so is this just a matter of sending a PR to instabug with all of the locales covered?

**Comment by fixxer** [comment]
Posted the [PR](https://github.com/Kennytian/react-native-instabug/pull/18) to [react-native-instabug](https://github.com/Kennytian/react-native-instabug).

**Comment by Serhy** [comment]
Fix on Instabug side (https://github.com/status-im/status-react/issues/737#issuecomment-369039518 ) has been merged and now language localised in Status app fine (Italian/Russian). 
Closing this issue.
