### ISSUE TITLE
Stickers Market design polish

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#7374]
i did a design review and here are the issues I found

**Polish**
- [x] the icon for Commands is black, should be Grey (common, not related to stickers)
- [x] like [I've mentioned before](https://github.com/status-im/status-react/pull/7210#issuecomment-451949739), the Sticker Menu should grab its height from the system keyboard
- [x] The 'Get stickers' button doesn't have touch feedback, it should be a Touchable with Opacity
- [ ] The Sticker Market toolbar/top nav is too high, it looks like it's 108px, should be a 100 (common, not related to stickers)
- [x] Sticker Market, tapping on the smaller sticker thumbnail, title or artist name should also lead you to sticker details, the only area that's outside of that is the install button.
- [x] Sticker Pack Details, the thumbnail should be a 64 by 64
- [ ] Sticker Pack Details, the thumbnail, title and subtitle are too low, I guess the toolbar here is again 8px too high pushing them down.  (common, not related to stickers)
- [x] Sticker Pack Details, the entire top toolbar is too high, should be a 188 instead of 202px
- [x] the underline under selected sticker pack should have a 1px border radius. We're designers, we round everything ;) 
- [x] a non-issue yet since we won't have many packs at launch but the sticker pack selection menu should be horizontally scrollable

**Separate issues**
- a beautiful thing that would make me cry is if the menu wouldn't 'jump' on opening but animate instead. But this is a larger problem as the text input also has this wonky issue where only the keyboard animates smoothly and the input just teleports into position. [Issue required]
- the sticker pack menu, the one where you can select the sticker to send, should be [horizontally page'able](https://facebook.github.io/react-native/docs/scrollview#pagingenabled) so you can swipe between sticker packs. [Issue required]
- tapping on a sent sticker should display the sticker details view. [Issue required]

_Originally posted by @errorists in https://github.com/status-im/status-react/pull/7210#issuecomment-458841834_

**Comment by jeluard** [comment]
Also consider:

* adding desktop sticker rendering
* allowing to reply with a sticker
