### ISSUE TITLE
Message bubble is too wide on iPhone 5s (can't read part of text) and on Galaxy S6 (very close to screen edge) 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7380]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: there are 2 issues with bubble width:
1. end of the string is not visible in the bubble on iPhone 5s 
![img_4257](https://user-images.githubusercontent.com/6584810/51982565-aa28b680-2496-11e9-92b4-0b98cdefa5eb.jpg)

2. right side of the bubble is too close to the edge of the screen on Samsung Galaxy S6 that contradicts with design from https://github.com/status-im/status-react/issues/6440 (assuming similar expectations on Android)
![screenshot_20190130-134736](https://user-images.githubusercontent.com/6584810/51982925-a34e7380-2497-11e9-89d0-5ab39418847b.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join #status channel or receive some 3-4 line messages in any other test channel

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly January 30
* Operating System: Android 6.0.1 real Galaxy S6 and iOS 12.1.2 iPhone 5s

**Comment by errorists** [comment]
🙏 thank you @annadanchenko for finding that, indeed the design wasn't implemented correctly. @yenda There should be a minimum margin of 64px on the larger side, meaning it cannot be smaller than 64 and if required we decrease the width of the message till it fits.

**Comment by yenda** [comment]
I'm looking into it, will have a fix tomorrow morning

**Comment by yenda** [comment]
Ok it should be good now, the old css really didn't care about the minimum left and right margin which is why only increasing the width caused issues on smaller device. I rewrote part of the css in the PR to make sure there is always 64px left and right
