### ISSUE TITLE
Update reference for view components

### ISSUE THREAD

**Issue by krisc** [status-im/status-react#7384]
@jeluard suggested I update the documentation for view components on this page (https://status.im/extensions/reference_views.html) to reflect the latest improvements.

@StatusSceptre  I just have a simple question and then I can finish this in less than a day.

My question is do components still have a `style` property? In the code here (https://github.com/status-im/status-react/blob/develop/src/status_im/extensions/core.cljs#L403), I don't see a `style` property even though the tutorial says they have it.

**Comment by krisc** [comment]
Sorry, I think I may have posted this in the wrong repo.

**Comment by jeluard** [comment]
@krisc `style` is special, it is available for all components.
