### ISSUE TITLE
Unable to access faucet

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#739]
Android user unable to access faucet

Seeing this error repeated 13 times in the console log.

```01-17 16:58:31.982 D/ReactNativeJS(16918): DEBUG [status-im.commands.handlers.loading:70] - Error parsing commands:  nil nil```

This one is repeated multiple times, too.

```01-17 16:58:56.073 D/ReactNativeJS(16918): DEBUG [status-im.components.status:143] - {:error "ReferenceError: 'call' is not defined"}```

![image](https://cloud.githubusercontent.com/assets/25023739/22052042/74e4b90c-ddac-11e6-88c9-1ec8e2c72ae2.png)

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/196?status=New

**Comment by rasom** [comment]
duplicate #652, it is not related to the faucet, jail is not working here
