### ISSUE TITLE
App crash: ...mailserver/check-connection-timeout], :db nil when account logs out

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7391]
**_Type_**: Bug

**_Summary_**: When user logs out of account, app may crash with the `fx/defn expects a map of cofx as first argument got {:event [:mailserver/check-connection-timeout], :db nil, :now 1548952778992}.... ` like error (please see full error in logs). I have no strict steps to reproduce so far. But while trying to reproduce it I can say that this crash happened when:

* create new account -> send contact request and several text messages to another account -> tap 'Log out' from Profile
* Recover an account (with offline message history in 1-1 chats) -> use Status for ~10 minutes (join public chats, navigate and Sign message in Dapps). Then I didn't touch Status keeping it in the foreground and in about 5 minutes -> Change Log Level from default setting (it will log you out)
* Doesn't matter whether indication about connecting to peers / fetching messages at top of Chat/Home screen is finished or still in process

#### Expected behavior
No crash when user logs out (via 'Log Out' button or via an activity with the forced account log out - change LogLevel, change Network)

#### Actual behavior
Sometimes when contact logs out - Status crashes with error:
![](https://user-images.githubusercontent.com/8749671/52074108-ceb58900-2591-11e9-8f46-ba7de902c613.png)

### Reproduction

* Install fresh develop / release 0.9.33 build
* Recover an account with offline message history
* Join public chats from the recommended list 
* Sign in to Cryptokitties
* Change Log level from Profile -> Log Level to 'Info' level

### Reproduction 2 (when it appeared in my case as well)

* Install fresh develop / release 0.9.33 build
* Create first account -> scan QR code of a contact and send 10 message to this contact -> Log out.
* Create second account -> scan QR code of a contact and send 10 message to this contact -> Log out.
* Create third account -> scan QR code of a contact and send 10 message to this contact -> Log out.

### Additional Information

* Status version: Release candidate `0.9.33 (2019013112) status-go v0.19.0-beta.9` / Develop 0.9.33
* Operating System: Android and iOS

#### Logs

```
01-31 18:39:38.996 11140 11195 I ReactNativeJS: NAME: "Error"
01-31 18:39:38.996 11140 11195 I ReactNativeJS: MESSAGE: fx/defn expects a map of cofx as first argument got {:event [:mailserver/check-connection-timeout], :db nil, :now 1548952778992} in function function (e) {switch(arguments.length){case 0:return status_im.mailserver.core.check_connection.cljs$core$IFn$_invoke$arity$0();case 1:return status_im.mailserver.core.check_connection.cljs$core$IFn$_invoke$arity$1(arguments[0]);default:throw Error(["Invalid arity: ",cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""))}}
01-31 18:39:38.996 11140 11195 I ReactNativeJS:
01-31 18:39:38.996 11140 11195 I ReactNativeJS: cljs$core$IFn$_invoke$arity$1@index.android.bundle:12:5552418
01-31 18:39:38.996 11140 11195 I ReactNativeJS: index.android.bundle:12:7929588
01-31 18:39:38.996 11140 11195 I ReactNativeJS: index.android.bundle:12:1745644
01-31 18:39:38.996 11140 11195 I ReactNativeJS: invoke_interceptor_fn@index.android.bundle:12:1675950
01-31 18:39:38.996 11140 11195 I ReactNativeJS: invoke_interceptors@index.android.bundle:12:1676251
01-31 18:39:38.996 11140 11195 I ReactNativeJS: execute@index.android.bundle:12:1678700
01-31 18:39:38.996 11140 11195 I ReactNativeJS: handle@index.android.bundle:12:1687113
01-31 18:39:38.996 11140 11195 I ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@index.android.bundle:12:1714198
01-31 18:39:38.996 11140 11195 I ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1@index.android.bundle:12:1699183
01-31 18:39:38.996 11140 11195 I ReactNativeJS: index.android.bundle:12:1702363
01-31 18:39:38.996 11140 11195 I ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3@index.android.bundle:12:1706574
01-31 18:39:38.996 11140 11195 I ReactNativeJS: index.android.bundle:12:1700485
01-31 18:39:38.996 11140 11195 I ReactNativeJS: index.android.bundle:24:1801
01-31 18:39:38.996 11140 11195 I ReactNativeJS: k@index.android.bundle:24:643
01-31 18:39:38.996 11140 11195 I ReactNativeJS: q@index.android.bundle:24:1007
01-31 18:39:38.996 11140 11195 I ReactNativeJS: callImmediates@index.android.bundle:24:3202
01-31 18:39:38.996 11140 11195 I ReactNativeJS: value@index.android.bundle:19:2904
01-31 18:39:38.996 11140 11195 I ReactNativeJS: index.android.bundle:19:1377
01-31 18:39:38.996 11140 11195 I ReactNativeJS: value@index.android.bundle:19:2621
01-31 18:39:38.996 11140 11195 I ReactNativeJS: value@index.android.bundle:19:1347
01-31 18:39:38.996 11140 11195 I ReactNativeJS: [native code]
01-31 18:39:38.996 11140 11195 I ReactNativeJS: value@index.android.bundle:19:962
01-31 18:39:38.996 11140 11195 I ReactNativeJS: [native code]
01-31 18:39:38.996 11140 11195 I ReactNativeJS:
```

[Logcat.log](https://github.com/status-im/status-react/files/2818475/crashwhenlogout.log)
 for status PID when app crashed: 
[geth.log](https://github.com/status-im/status-react/files/2818486/gethwhenappcrash.log)
 (with DEBUG level) when app crashed

**Comment by Serhy** [comment]
Reproduced again via switching between three accounts I have. And on a third login and I was able to see Home screen - then was able to swich to 'Profile' screen and same error(s) (there are three of them in logs) brought the app crash.

Logcat when I switched between three accounts:
[logcat_with_three_exceptions.log](https://github.com/status-im/status-react/files/2820903/logasdfsdf22.log) (Search for `PRETTY PRINTED EXCEPTION` to see all errors)

**Comment by churik** [comment]
Reproduced again on switched 2 accounts after upgrade from 0.11.0 to https://github.com/status-im/status-react/pull/7862 PR build on Android 8.
So login -> logout -> login to another account causes an error.
Logcat: [logcat2.log](https://github.com/status-im/status-react/files/3068386/logcat2.log)

**Comment by mandrigin** [comment]
@churik @Serhy what do you think about making it a smaller bounty? `M` or even `S`?

**Comment by Serhy** [comment]
@mandrigin yes, OK for bounty. Just not sure about the complexity of the fix. Similar issue with a crash after logout we fixed in the past by disabling the ability to log out (Disabled 'Log out' and 'Advanced' buttons on profile) until all after-login activities finished (https://github.com/status-im/status-react/pull/7032 and https://github.com/status-im/status-react/pull/7144)

**Comment by churik** [comment]
Can't reproduce issue (tried both scenarios) in nightly 25/02/2020
@Serhy have you seen this message lately?

**Comment by Serhy** [comment]
Haven't seen it for a long time. 
Lets' close it.
