### ISSUE TITLE
Status Desktop doesn't work on Linux

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7394]
# Problem

On Linux Mint Status Desktop doesn't start anymore in nightlies, all I get is a white screen. It doesn't go far enough to produce any log.

# uname -a
Linux desktop 4.15.0-20-generic #21-Ubuntu  x86_64 GNU/Linux

**Comment by churik** [comment]
@vkjr can be related to https://github.com/status-im/status-react/issues/7348

**Comment by vkjr** [comment]
@yenda, could you please check against this build - https://github.com/status-im/status-react/pull/7406 ?

**Comment by yenda** [comment]
@vkjr yes I tried and it works! Awesome thank you
