### ISSUE TITLE
Use same UI and navigation on desktop and mobile

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7399]
# Problem

Desktop is currently using a different set of screens and navigation system, which adds up to the burden of maintaining the platform. 

# Implementation

Check what is required to have desktop work with the current mobile screens. We can use conditionals like we already have for ios/android for platform specific things but overall that would remove the only limitation we have for having features released on both platforms simultaneously.

# Acceptance Criteria

Desktop doesn't use it's own screens anymore

# Related issues
- [Improve FlatList performance ](https://github.com/status-im/react-native-desktop/issues/470)
- [Two-pane status UI](https://github.com/status-im/status-react/issues/8168)

# Notes

- react-navigation might need to be implemented for the desktop platform?

**Comment by 0xc1c4da** [comment]
➤ Oskar T commented:

Is this really Eric D? Not Volodymyr Kozieiev?

**Comment by vkjr** [comment]
Eric created this long ago as a proposal, so I decided not to create a new github issue for ongoing work since this one already describes the problem.

**Comment by vkjr** [comment]
This issue was closed because referenced in #7551 PR. But for now mobile UI merged under flag, so we can't call this issue closed.
