### ISSUE TITLE
privacy leak - sharing contact info without user action

### ISSUE THREAD

**Issue by gravityblast** [status-im/status-react#7401]
# Problem

Initially it was possible to have a 1:1 chat with a user without sharing personal contact information like name and profile picture.
It looks like it's not possible anymore, because contact informations are sent automatically to the other user when opening a 1:1 chat.

# Example

1 - Alice writes a messages in a public chat
2 - Bob sends a message to the same public chat
3 - Alice cannot see Bob's real name; she can see the 3 random words.
4 - Bob clicks on Alice's profile and then on "Send message". 1:1 chat opens (without actually sending messages).
5 - At this point Alice can see Bob's real name, because profile informations have been sent at point 4, without any action from Bob. Bob didn't have to click on "Add to contacts"

As we discussed in Status, we changed this behaviour some months ago, but I'm not sure if it has been decided from a UX point of view, and if we want to keep it.

Is there any other reason for this? Maybe related to push notification?

**Comment by hesterbruikman** [comment]
From a UX perspective this is undesireable behavior as regardless of whether we want to expose identities in advance of sending a message (don't think we do), we currently don't communicate this system state well.

**Comment by cammellos** [comment]
I believe it was done during the move to the new protocol, as a mean to exchange a key (without the contact request the two users would not be able to communicate). That mechanism has been now removed, and this simply looks like an artifact of that choice, so there's no harm in removing. Push notifications will be affected in the sense that if you don't add someone in your contacts, when they send you a message, you wont receive push notifications, but that's expected.

**Comment by hesterbruikman** [comment]
@corpetty what's your view on this?

**Comment by corpetty** [comment]
Yes, please remove.  you should be able to contact a public key (which will be better w.r.t. spam after TtT) but the profile shouldn't be exposed until after the contact has been added.

**Comment by cammellos** [comment]
@hesterbruikman I take the same goes for when I copy and paste the public key in `Start new chat` or use an ENS name? (currently I believe they are also added as contacts)

**Comment by hesterbruikman** [comment]
IYes, thanks for bringing that up. IMO only an explicit 'Add to contacts' should lead to adding people to a contact list. There might be an exception in Tribute to Talk where I believe people are added to eachothers contact list upon release funds from escrow. cc @rachelhamlin
