### ISSUE TITLE
Oauth-login dapps stuck in infinite loop

### ISSUE THREAD

**Issue by Swader** [status-im/status-react#7402]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to log into Oauth websites in the dapp browser so I can use them.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When visiting a site that needs Oauth login, like Gitcoin into which you can log in via Github, the dapp browser will get stuck in an infinite loop. See video.

To reproduce, visit Gitcoin.com/grants, log in via Github, and observe.

OS: Android 9+, possibly others.

[Video here](https://matrix.org/_matrix/media/v1/download/matrix.org/hqxQoiGYkqvHHCUCPDDVCXuz)

**Comment by cammellos** [comment]
This should be fixed, closing
