### ISSUE TITLE
No option to recover immediately after a fresh install.

### ISSUE THREAD

**Issue by auryn-macmillan** [status-im/status-react#741]
On a fresh install, the user is prompted to create a new account.
There is no immediate option to recover an old account.
So a user is forced to create a new account that will never get used in order to progress to the screen where they are presented with an opportunity to recover their existing account.

**Comment by jarradh** [comment]
@andmironov at the moment we hide the back button on on-boarding, maybe we can have a "recover account" icon here which takes user to the account recovery page.

**Comment by flexsurfer** [comment]
temporary implementation
![image](https://user-images.githubusercontent.com/11790366/31771742-e0fa2f76-b4e5-11e7-8552-6bffb9f22101.png)

**Comment by annadanchenko** [comment]
Side effect with empty suggestions :

![39712](https://user-images.githubusercontent.com/6584810/31778393-d001974e-b4f0-11e7-9112-178282db8cec.jpg)
Steps:
- launch app 
- tap on Password message (/password and keyboard are shown). 
- Tap on Recover. 
- Tap on Back. 
- Tap again on message with password in console

https://app.testfairy.com/projects/4803590-status/builds/6901542/sessions/8/?accessToken=VJzLzTEwr5FPA2C6pmLJWzOJ2Uk


both iOs and Android

**Comment by flexsurfer** [comment]
fixed

**Comment by annadanchenko** [comment]
verified ok. can be merged

**Comment by flexsurfer** [comment]
Fixed in develop. Will be released in 0.9.12
