### ISSUE TITLE
Message in 1-1 chat leads to error when devices are paired

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7410]
### Description

*Type*: Bug

*Summary*: having paired devices with 0.9.32 (or with RC 0.9.33 https://ci.status.im/job/status-react/job/release/job/release%252F0.9.33/11/)  and latest desktop nightly (2019/02/04) leads to error at attempt to send the message from mobile and appearing additional chat with own user messages after app restarting

#### Expected behavior
can see 1-1 messages in desktop

#### Actual behavior
On desktop:
![2019-02-04 10 46 24](https://user-images.githubusercontent.com/4557972/52200927-49202a80-286a-11e9-9f9b-a7e13d5ecf89.jpg)
On IOS:
![img_0a17df917e23-1](https://user-images.githubusercontent.com/4557972/52204915-ca30ef00-2875-11e9-99cc-9214ca09feda.jpeg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on desktop (nightly 04/02/2018)
- Create new account,create 1-1 chat
- Restore same account mobile (0.9.32 or RC 0.9.33 https://ci.status.im/job/status-react/job/release/job/release%252F0.9.33/11/) 
- Pair both devices
- send any message to 1-1 chat from mobile. After reopening app you'll see additional chat (in my case with `Studious Robus Chimneyswift`) which contains all your own messages sent from another device.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 04.02.2019
* Operating System: all

#### Logs
From desktop:
[Status.log](https://github.com/status-im/status-react/files/2827409/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2827410/geth.log)

From IOS:
[geth.log](https://github.com/status-im/status-react/files/2827643/geth.log)

**Comment by cammellos** [comment]
looking into this, not a release blocker as not in 0.9.33 or caused by it
