### ISSUE TITLE
'TypeError: network request failed' when tap on attempt to connect to POA Network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7411]
***Type***: Bug

***Summary***: Can't connect to `POA network` network from the account network settings. When user with stable WiFi connection taps on 'Connect' button upon 'POA network' the `TypeError: network request failed` error pop-up appears.

#### Expected  behavior
User can connect to `POA Network` from Network settings with no errors.

#### Actual behavior
'TypeError: network request failed' pop-up appears when tap on attempt to connect to POA Network
<img width="331" alt="screenshot 2019-02-04 at 12 59 15" src="https://user-images.githubusercontent.com/8749671/52204393-b3da6180-287c-11e9-88c4-75899d02f88f.png">

### Reproduction

- Open Status and create new account
- Navigate to `Profile` -> `Network` -> `POA network`
- Tap 'Connect' button

### Additional Information
* Status version: Release 0.9.32 / Release 0.9.33 / Delelop 0.9.33 (4th of February nightly build)
* Operating System: Android and iOS

#### Logs

[gethPOAnetwork.log](https://github.com/status-im/status-react/files/2827590/geth.49.dd.log)
[logcatPOAConnectAttempt.log](https://github.com/status-im/status-react/files/2827591/logcassefef.log)

**Comment by pablanopete** [comment]
It could possibly be that since the Infura changes that POA network also changed its RPC connection.

**Comment by SiddigZeidan** [comment]
Infura has disconnected the POA nodes, so Status needs to switch the RPC URL from the Infura one to https://core.poa.network . Sorry about the inconvenience guys 
https://forum.poa.network/t/infuras-poa-core-nodes-to-be-disabled-on-2-1-19/1881

<blockquote></blockquote>
<blockquote><img src="https://discourse-cdn-sjc1.com/business5/uploads/poa1/optimized/2X/e/e1036f7b9bf2894593cb84c2c6a12c26e2e1a9d9_2_690x258.jpeg" width="48" align="right"><div><img src="https://discourse-cdn-sjc1.com/business5/uploads/poa1/original/1X/4bb35433cd377f367a00c759ff33295d39a1cbf2.png" height="14"> POA Forum</div><div><strong><a href="https://forum.poa.network/t/infuras-poa-core-nodes-to-be-disabled-on-2-1-19/1881">Infura's POA Core nodes to be disabled on 2/1/19</a></strong></div><div>POA Community,  As of this coming Friday, February 1st (2/1/19 ), POA Core’s Infura nodes will be disabled.  What This Means For the last 6 months, Infura has partnered up with POA Core to provide reliable uptime for POA nodes. This meant that DApps and users can connect through POA Core through two means:    https://core.poa.network    https://poa.Infura.io    As soon as the node gets disabled https://poa.Infura.io RPC will cease to work.  DApp Developers and Users If you usually connect to P...</div></blockquote>
