### ISSUE TITLE
PNs are not coming for contacts which were added through device sync

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7417]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: when the user appears in contacts after device sync - PNs are not received for new messages in 1-1 chat.

#### Expected behavior
can see PNs

#### Actual behavior
no PNs

### Reproduction

- Create account (User A, device 1)
- Start 1-1 chat with User B (User A, device 1)
- Send several messages as User B (User B, device 3)
- Restore account of User A on device 2
- Pair device 1 and 2 (User A)
- Check that User B is added as contacts (User A, device 2)
-  Send several messages as User B (User B, device 3)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33 RC and 
[comment]: # (Android or iOS.)
* Operating System: Android, iOS

#### Logs

[pnslog.txt](https://github.com/status-im/status-react/files/2828787/pnslog.txt)
[geth (1).log](https://github.com/status-im/status-react/files/2828788/geth.1.log)

**Comment by yenda** [comment]
If I'm not mistaken the fcm token is per device. After receiving new contacts through sync the app should communicate the fcm token of the new device and the contacts would need to send a notification to each device. I don't think the notification code currently handles sending multiple notifications

**Comment by annadanchenko** [comment]
PNs in general are not received on multiple devices https://github.com/status-im/status-react/issues/7368

**Comment by cammellos** [comment]
Correct, currently the push notifications system only handles 1 device, I can probably work on adding support for multiple devices, but it's not a quick fix (likely requires a protocol change).

**Comment by mandrigin** [comment]
We have it on our roadmap, btw

**Comment by cammellos** [comment]
ah cool, I don't mind owning this, as I have already an idea on how to implement it.

**Comment by annadanchenko** [comment]
@churik closing as it's described in #7368
