### ISSUE TITLE
Recover account screen only has 1 password field

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#7418]
# Problem

When trying to recover an account in status when I already have a current account there's only 1 field for password which could lead to me making a typo / locking me out.

# Expected

When recovering an account show two prompts with a 'confirm' for password so that a typo doesn't lock me out  and I'm sure of my  password

Area in question:

![img_4089](https://user-images.githubusercontent.com/18363825/52223939-66ee8f00-286c-11e9-9fb2-aa1f0a256574.JPG)

**Comment by jakubgs** [comment]
I've gotten bitten by this more than once. I type the password in, use the account for a while, then reboot my phone, try logging in and... no dice... apparently typed in the password wrong the first time when recovering.

Whelp, I guess I'm recovering AGAIN...
