### ISSUE TITLE
No user feedback on mailserver error

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#7422]
# Problem

When a user selects a mailserver and the connection to this mailserver is unsuccessful (state goes from `:connecting` to `:error`), we don't handle that at all.

So, essentially, after that, no error message is shown, there are no re-tries and we don't even try to request historic messages. App is essentially unusable.

# Acceptance Criteria

When the mailserver connection goes to `:error`, show an error message to a user ("error connecting to the mailserver `{mailserver_name}`") and 2 buttons ("retry" and "pick another"). When user presses "pick another", navigate him to the mailserver choosing screen.

**Comment by annadanchenko** [comment]
@errorists and @yenda fyi

**Comment by errorists** [comment]
thanks @mandrigin 

<img width="270" alt="title text" src="https://user-images.githubusercontent.com/4932774/52265679-eba4e000-2934-11e9-8437-4697fa0ca3ed.png">


My immediate reaction would be to include an Alert like above

**Comment by rasom** [comment]
btw we already show the next status in the badge
![screen shot 2019-02-05 at 13 04 52](https://user-images.githubusercontent.com/2364994/52269455-cd47e000-2946-11e9-93f0-65dcc16e9ce1.png)

but this code was broken. Anyway I will add dialog as well

**Comment by mandrigin** [comment]
@errorists oh, thank you!
