### ISSUE TITLE
 "Block user" and back button in "Contacts" and "Blocked users" always leads to "Home" instead of appropriate screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7437]
### Description

*Type*: Bug

*Summary*: introduced in https://github.com/status-im/status-react/pull/7170
generally navigation from tabs "Blocked users" and "Contacts" from profile screen and back should be improved from my POV

For example:
1) Profile > Blocked Users > Open any user profile > go back. Expected that I'll be redirected to Blocked Users, but in fact I am redirected to "Home" 
2)  Profile > Contacts > Open any user profile > go back. Expected that I'll be redirected to Contacts, but in fact I am redirected to "Home" 
3)  Profile > Contacts > Open any user profile > Block user. Expected that I'll stay on User Profile, but  in fact I am redirected to "Home"

**Comment by churik** [comment]
Still relevant in v1.0.1

**Comment by rachelhamlin** [comment]
@Ferossgp would you mind fixing this one? Feels like an easy fix and I'd like to include in 1.3 if possible :)

**Comment by Ferossgp** [comment]
@rachelhamlin I will do it, but this is not an obvious one, cause the contact screen is a part of the Chat tab. So when we open a contact we open the chat tab and inside this tab we open the contact information. I think I can duplicate the screen into the chat tab and profile tab, and open the one specific to the tab in which was asked to be opened.
