### ISSUE TITLE
No Push Notifications are received when app is closed (on IOS)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7438]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: introduced by https://github.com/status-im/status-react/pull/7268. Basically it means if app is closed, user can't receive PN on IOS.
Issue is created because it worked in another way on 0.9.32, so it is a placeholder for possible discussion around expected behavior.
From PR (https://github.com/status-im/status-react/pull/6893#issuecomment-453983432):

> This is only expected on iOS. Android has provisions to deal with starting up the app through a background task if needed (see link to docs in OP). On iOS, we should show the notifications to the user once he starts the app/logs back in.

#### Expected behavior
user can see PN for incoming message

#### Actual behavior
no PN

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- User1: Open Status
- User1: add User2 to contact list
- User2: add User1 to contact list
- User1: close app
- User2: send message to 1-1 chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: RC 0.9.33
* Operating System: IOS

**Comment by annadanchenko** [comment]
still valid
