### ISSUE TITLE
A pop-up message saying "No protocol method IMap."

### ISSUE THREAD

**Issue by jinhojang6** [status-im/status-react#7458]
# Problem

When I was checking the 'status-core' chatroom, this pop-up message below appeared out of nowhere and I could not scroll up on the screen anymore after clicking on the 'OK' button.

![jinhojang](https://user-images.githubusercontent.com/41753422/52520188-277bd480-2caa-11e9-8389-b06d50605d94.jpeg)

Afterward, all the chatrooms on my home screen said 'there is no message'. 

# Notes

I logged out and all the chatrooms were restored when I logged in again.

Notes from Nastya:  i 've seen this issue today, once i added Andrey as a contact on mobile for the account which is synced on desktop and mobile

![2019-04-17 15 45 48](https://user-images.githubusercontent.com/28752642/56289679-2a6fc700-612a-11e9-819a-919d5c90161a.jpg)

**Comment by Serhy** [comment]
The second error `No protocol method IMap.-dissoc defined for type cljs.core/EmptyList: ()` moved in separate issue https://github.com/status-im/status-react/issues/8273
