### ISSUE TITLE
:navigation-stack is grows on switching tabs

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#747]
![image](https://cloud.githubusercontent.com/assets/11790366/22123847/6815f112-de9e-11e6-9896-144e4b3b51b9.png)

these screens don't have back buttons so i think we don't need to store tabs in the stack,
and on Android it's not good behavior to go back through all stack

**Comment by rasom** [comment]
Looks like it would be better to use `:navigate-replace` for switching between tabs to avoid this.

**Comment by mathvdh** [comment]
Hi, I'm trying to handle this as a appetizer ... It seems quite simple :)
After looking a bit I only have one issue with the proposed solution, If we use `:navigation-replace` to switching between tabs, we don't update `:prev-tab-view-id` and  `:prev-view-id` when switching tabs. An alternative I would like to propose is to replace the call to `push-view` with `replace-view` in the handler for `:navigate-to-tab`. So we still update those but don't add to the navigation-stack ?
If OK for you guys I'll submit a PR with this fix (a one-line fix really :)

**Comment by rasom** [comment]
Hi, @mathvdh , it sounds fine, lets try :)

**Comment by etartakovsky** [comment]
Should be closed?

**Comment by jarradh** [comment]
yes, PR didn't include a `fixes #747` which allows us to rely on Github auto-closing, good catch @etartakovsky
