### ISSUE TITLE
Messages disappear on restarting the app 

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7474]
A user reported that messages disappear after restarting the app, both messages that they received and they sent.

They had conversations in #status channel.

After restart, the messages from the previous conversation disappeared (until October 2018, likely the last time it was in the chat before upgrading to 0.9.33).

We asked to replicate, and it was partially replicated (some of the newer messages were persisted, but older were not).

Fetch 24 hours did not help.

We posted a reply to a message that disappeared, and the original message was not visible on the user device (which seems to indicate that the original message was not saved in the db).

Device is running 0.9.33, IOS 12.1.2, Iphone 5s.

Two extensions installed, giphy and an example extension made by status.

We asked to uninstall the extensions and it could still be replicated (all history gone).

**Comment by Serhy** [comment]
To reproduce behavior of disappearing messages after relogin could be done with the device date change to the past:

**Reproduction:**
1) Install Status
2) Manually change the date to yesterday (at this moment it's 19th of February)
3) Open Status and create new account
4) Join `#status` public chat
5) Wait till message history is fetched (Note: it fetches last 24h, so, depends of time when you execute this scenario, yesterdays messages - 18th of Feb at the current moment - should be present too)
6) Close Status app
7) Update the date to current date (20th of February at this moment)
8) Open Status, log in to account
9) Verify that: a) message history fetched in 5th step above is kept. b) message history is fetched and displays for the last 24h
10) Relogin to account
11) Verify that: a) message history fetched in 5th step above is kept. b) message history is fetched and displays for the last 24h
**Actual result:** Latest message displayed in `#status` public chat is the last message posted at 18th of Feb (next messages, starting from 19th of Feb, are not visible. However, on Home screen the 'real' message is shown. 

<img width="970" alt="screenshot 2019-02-20 at 15 06 20" src="https://user-images.githubusercontent.com/8749671/53093971-8dc1ec00-3521-11e9-97b4-292e7c4dd711.png">

Confirmed with iOS, MacOS, Android - develop build (20th of February nightly build)
