### ISSUE TITLE
Status app fail to start in emulator after installation [Android 7.x simulator]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7476]
***Type***: Bug

***Summary***: In emulators Status fails to run after installation (both fresh install or upgrade).
Likely reason when it may be introduced in https://github.com/status-im/status-react/pull/6914
It's OK on the real device though.
Logs with an error provided below.

It affects saucelabs services we use for e2e-tests, so they will fail!

#### Expected behavior
Status starts and I appear on login page after app launch

#### Actual behavior
Status app fail to start in emulator after installation
<img width="403" alt="screenshot 2019-02-12 at 13 05 48" src="https://user-images.githubusercontent.com/8749671/52631721-36d86900-2ec8-11e9-888b-d875aabaf37f.png">

### Reproduction

- Start Android emulator (e.g. Genymotion)
- Instal latest nightly build
- Start Status

### Additional Information
* Status version: Develop 0.9.34 (2019021120) status-go vN/A
* Operating System: Emulator Android 7.0 / 7.1.0

#### Logs

```
--------- beginning of crash
02-12 05:23:53.868  5283  5332 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5332 (mqt_native_modu)
02-12 05:23:53.868  5283  5317 D StatusNativeLogs: runtime/cgo: pthread_key_create failed
02-12 05:23:53.868   118   118 W         : debuggerd: handling request: pid=5283 uid=10103 gid=10103 tid=5332
02-12 05:23:53.887  5333  5333 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-12 05:23:53.887  5333  5333 F DEBUG   : Build fingerprint: 'Android/vbox86p/vbox86p:7.1.1/NMF26Q/91:userdebug/test-keys'
02-12 05:23:53.889  5333  5333 F DEBUG   : Revision: '0'
02-12 05:23:53.889  5333  5333 F DEBUG   : ABI: 'x86'
02-12 05:23:53.889  5333  5333 F DEBUG   : pid: 5283, tid: 5332, name: mqt_native_modu  >>> im.status.ethereum <<<
02-12 05:23:53.889  5333  5333 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-12 05:23:53.889  5333  5333 F DEBUG   :     eax 00000000  ebx 000014a3  ecx 000014d4  edx 00000006
02-12 05:23:53.889  5333  5333 F DEBUG   :     esi c3b0e978  edi c3b0e920
02-12 05:23:53.889  5333  5333 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
02-12 05:23:53.889  5333  5333 F DEBUG   :     eip ea8debb9  ebp c3b0e538  esp c3b0e4dc  flags 00200296
02-12 05:23:53.890  5333  5333 F DEBUG   : 
02-12 05:23:53.890  5333  5333 F DEBUG   : backtrace:
02-12 05:23:53.891  5333  5333 F DEBUG   :     #00 pc 00000bb9  [vdso:ea8de000] (__kernel_vsyscall+9)
02-12 05:23:53.891  5333  5333 F DEBUG   :     #01 pc 0007a30c  /system/lib/libc.so (tgkill+28)
02-12 05:23:53.891  5333  5333 F DEBUG   :     #02 pc 00075b55  /system/lib/libc.so (pthread_kill+85)
02-12 05:23:53.891  5333  5333 F DEBUG   :     #03 pc 0002786a  /system/lib/libc.so (raise+42)
02-12 05:23:53.891  5333  5333 F DEBUG   :     #04 pc 0001ee46  /system/lib/libc.so (abort+86)
02-12 05:23:53.891  5333  5333 F DEBUG   :     #05 pc 00b5f9b5  /data/app/im.status.ethereum-1/lib/x86/libgojni.so

```
[logcatAppCrashEmulator.log](https://github.com/status-im/status-react/files/2855472/logcatAppCrashEmulator.log)

**Comment by mandrigin** [comment]
It is impossible to use the current status app in **genymotion** emulator with Android 7.0 and Android 7.1, due to the bug in compilation flags for genymotion's version of Android itself.

Stock emulator works just fine.
Real devices work just fine.

SauceLabs tests were moved to 8.x where this issue is not present anymore.

There is nothing we can do about 7.0 and 7.1 with genymotion, so I'm closing the issue.
