### ISSUE TITLE
Implement emoji for signing phrase

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7486]
# Problem

I can't remember my signing phrase since it is just three words I confuse with other stuff.

# Implementation

Use Emoji guard to distinguish signing phrase from other passphrases.

# Acceptance Criteria

- Emoji guard implemented
- Graceful upgrade/behavior for existing accounts
- Security sanity check

# Notes

See https://github.com/status-im/status-react/pull/5824

This was discussed in Janitors. While I agree with the blocking in this PR at that time, I do think it'd be a step up to get it into the app. Especially as there doesn't seem to be any concrete suggestions for better solutions.

cc @yenda (kudos for initial PR!) @jarradh @hesterbruikman 

# Future Steps

Do more UX research on better solutions when resources are available.

**Comment by yenda** [comment]
Might be worth thinking about the best cost effective solution here considering the work has already been done once. Is it better to reopen the PR and refresh it (I could do that), or @rasom is it the same drawer component you are working on in your recent PR and it might be better to switch to use this one?

**Comment by cammellos** [comment]
Closing this for now as it's seems that's not something that will be implemented any time soon/lack of appetite for it, feel free to reopen
