### ISSUE TITLE
Wallet should be named 'Receive' not 'Deposit'

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7487]
# Problem

Wallet used to be called Receive not Deposit. Now it is more confusing to several people.

# Implementation

Fix string.

# Acceptance Criteria

String fixed. Look at other languages for sanity check, if applicable.

# Notes

Why was this changed?

# Future Steps
-

**Comment by oskarth** [comment]
@goranjovic @hesterbruikman

**Comment by asemiankevich** [comment]
@oskarth it was changed in redesign flow last year

**Comment by asemiankevich** [comment]
https://www.figma.com/file/SIeZPHvrX7KUwEBW8VQct8C5/New-send-transaction?node-id=0%3A1

<blockquote><img src="/file/SIeZPHvrX7KUwEBW8VQct8C5/thumbnail?ver=thumbnails/fe343a06-caf5-4f96-8226-e5f2110dc263" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/SIeZPHvrX7KUwEBW8VQct8C5/New-send-transaction">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by oskarth** [comment]
But with what rationale? I haven't heard anyone who likes it, and at least 3 people (myself included) who finds it confusing and weird.

**Comment by asemiankevich** [comment]
> But with what rationale? I haven't heard anyone who likes it, and at least 3 people (myself included) who finds it confusing and weird.

this is by design now, i have provided the link above. ping @denis-sharypin

**Comment by hesterbruikman** [comment]
Add me to the 3 people if you didn't yet @oskarth . I'll see if I can fid any documentation on the rationale.

[UPDATE] I can only find reference to 'Receive' and 'Send request' in documention by Obi: https://docs.google.com/document/d/1unyX6WsuB7godU5t4_5ajD5G3TmLsNHZbbUK7FjBsrE/edit

**Comment by naghdy** [comment]
+1 this is very confusing (I'm here at ETHDenver, and people can't automatically figure out which button to click".

Please change in the next release. 

![img_5516](https://user-images.githubusercontent.com/32269875/52891621-5c27da00-3149-11e9-929a-a72a08b2f49c.PNG)

**Comment by hesterbruikman** [comment]
@goranjovic fixed this: https://github.com/status-im/status-react/pull/7502
