### ISSUE TITLE
Can't create account on android PR builds 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7489]
# Problem

Found in https://github.com/status-im/status-react/pull/7457#issuecomment-462873139
App is named "Status PR" instead of "Status". 
When trying to create the account I'm redirected to last visited app (in my case it was file manager) after setting password.

Video: https://take.ms/JdJSG
Logcat: 
[logcat-andr2.txt](https://github.com/status-im/status-react/files/2857028/logcat-andr2.txt)
Version of app: 0.9.34.Pr

**Comment by churik** [comment]
it is probably related to #7287, @jakubgs can you take a look?

**Comment by jakubgs** [comment]
Oh

**Comment by jakubgs** [comment]
Since I'm working on this in the open PR this is not an issue in `develop`. Closing.
