### ISSUE TITLE
Desktop profile left pane has tabs overlapping ungracefully with profile settings list

### ISSUE THREAD

**Issue by bitsikka** [status-im/status-react#7495]
# Problem
In Desktop when you go to *Profile* tab, if the app window height is made small, in the left-pane, tab-bar overlaps with the list of settings in the profile.

see pic: https://imgur.com/a/iNPCOiy

# Acceptance Criteria

tab-bar background should be opaque and overlap over the settings/profile-options list

**Comment by churik** [comment]
Thanks for the issue @bitsikka !
I'll add this info to https://github.com/status-im/status-react/issues/5151

**Comment by churik** [comment]
Logged as a part of #5151
