### ISSUE TITLE
Warn users that messages sent before accepting invitation to group chat won't be received

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7498]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, creator of group chat, I want to be notified that my messages, sent  before accepting invitation to group chat won't be received by user after joining chat.

### Description

*Type*: Bug

*Summary*: when create a group chat you can send  messages that not will be received after joining other users to group chat. So messages between `*User B* has been invited ` and between `*User B* has been joined` will be never received by User B, which is not clear for chat creator.

#### Expected behavior
`User A` is notified that notifications sent before accepting invitation will be missed by `User B` 

#### Actual behavior
messages can't be received by `User B` 

### Reproduction

- `User A`: Open Status
- `User A`: add `User B` to contacts
- `User A`: start a group chat chat with `User B` 
- `User A`: send several messages to group chat
- `User B`: accept invitation

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 13/02/2014
* Operating System: all

@hesterbruikman  please, take a look when you have a time. What is the best solution for user-chat creator in this case?

**Comment by hesterbruikman** [comment]
That actually explains a lot:P Will take a look, but adding @errorists in case he gets to it before I do

**Comment by churik** [comment]
Still relevant in Status v1.0.1

**Comment by errorists** [comment]
ok we're working on group chat today, and I'm looking into it. tho tbh I don't see that as an issue, message history not going back before you joined, seems like an obvious limitation.

<img width="468" alt="Screenshot 2020-02-26 at 11 55 27" src="https://user-images.githubusercontent.com/4932774/75338372-e3487b80-588e-11ea-97d5-09dda0017ce2.png">

we could customise this text here if you guys feel like it's really important to communicate.

**Comment by errorists** [comment]
> So messages between *User B* has been invited and between *User B* has been joined will be never received by User B, which is not clear for chat creator.

why would you expect they would be received by User B?

**Comment by churik** [comment]
thx @errorists! 

For me (if I'm not familiar with group chat flow in Status) as for chat creator it is not clear that the user will receive an invite -> then it should join and only after that you can send message.

@hesterbruikman if you feel that it is obvious from current implementation - I'll close it.

**Comment by errorists** [comment]
Let's not close it yet for now, do the first round of UI updates Gheorghe is working on now, test that PR and get a feel if it's an issue. The way I see it now, we might need to communicate more clearly that those people were only invited and didn't join yet. However I think that once you understand that, it's implied that they won't receive any messages until they join the chat.

**Comment by cammellos** [comment]
@errorists do you think this can be closed or you would like to improve the user experience?
