### ISSUE TITLE
"Sync all devices" button is shown before setting up device name in "Devices"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7499]
### Description
_Type_: Bug

_Summary_: there is no way to `Sync all devices` before setting a name to your device, so I suggest to show this button only after device name is set (on next step).

#### Expected behavior
no `Sync all devices` button

#### Actual behavior
![](https://user-images.githubusercontent.com/4557972/52720114-55616180-2fa7-11e9-8ef3-416187fe7f41.png)

### Reproduction

* Open Status
* Go to Profile > Devices

### Additional Information

* Status version: nightly 13/02/2019
* Operating System: Android, iOS

**Comment by churik** [comment]
Still relevant in Status v1.0.1

**Comment by cammellos** [comment]
Closing for now, as logic will likely be revamped as we change the pairing process for desktop.
