### ISSUE TITLE
Too many notifications from Status

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#7501]
This is ridiculous:
![screenshot_20190214-122203](https://user-images.githubusercontent.com/2212681/52783801-5059ec00-3053-11e9-8373-245edb350d79.jpg)

**Comment by Swader** [comment]
+1, why is notification bulking yet another thing that Status has to reinvent?

**Comment by asemiankevich** [comment]
@jakubgs @Swader this is now  works as expected. the feature will be improved very soon

**Comment by pedropombeiro** [comment]
@rachelhamlin I believe we discussed this in the context of https://github.com/status-im/status-react/issues/7046 a while back, maybe on iOS it is not as bad, but on Android it is clearly an issue.

**Comment by rachelhamlin** [comment]
@PombeirP I see the point. And you've fixed it?

**Comment by pedropombeiro** [comment]
I have a local fix I could apply that would group messages by sender.

**Comment by pedropombeiro** [comment]
Actually, the easiest would be to only show a single notification per sender (I believe that's what we initially discussed). Would that be acceptable?

**Comment by jakubgs** [comment]
Pretty much anything would be an improvement over what we have right now.

**Comment by rachelhamlin** [comment]
@PombeirP why not group messages by sender if you have a local fix?

**Comment by pedropombeiro** [comment]
@rachelhamlin I realized later that the local fix I have is for having a single PN per sender, sorry for the confusion. I actually started by grouping them, but it didn't seem to make much sense until we start actually showing the messages on the PNs themselves. I'm happy to do any of the two approaches, we just need to make a decision.

**Comment by rachelhamlin** [comment]
@PombeirP gotcha. I think it's better for the user to just disable notifications in that case. If we could bundle them, and you have the bandwidth to do so in context of other improvements, that'd be fantastic. 

There's also some mitigation to this issue in the profile & settings updates that allow users to disable notifications from contacts: https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A3116 

<blockquote><img src="/file/TNCyHKtR3sx5EL6YznFWUa4O/thumbnail?ver=thumbnails/cf49a938-6892-4718-b1ce-21a678069423" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by jakubgs** [comment]
This is still an issue. And it's absurd.
