### ISSUE TITLE
can't scan QR code for ETHDenver

### ISSUE THREAD

**Issue by owocki** [status-im/status-react#7512]
hey all im trying to get the status to read this QR code in the mobile app under "Scan QR COde"
but when i scan it Status says "This is not a valid Universal Link".

<img width="152" alt="screen shot 2019-02-14 at 1 52 36 pm" src="https://user-images.githubusercontent.com/513929/52817334-c7e24800-3060-11e9-82cd-409edcaf64cd.png">

![photo 40](https://user-images.githubusercontent.com/513929/52817350-ce70bf80-3060-11e9-9cf4-6f35b01981b3.jpg)

**Comment by owocki** [comment]
I think if it's a valid HTTPS link it should be a 'valid universal link' right?

**Comment by StatusSceptre** [comment]
Hey you’ll need to use the native camera qr code scheme for deep links here:

Here is the content from the old wiki:

Universal Links (iOS) & Deep Links (Android)

What are Universal & Deep Links

With universal links (iOS) and deep links (android) mobile users can tap a link to Status and get seamlessly redirected to the Status app and linked to specified screens without going through the browser. If Status isn’t installed, tapping a link to the Status website opens a Status website with info on the link and instructions to download the mobile app.

What Links Are Supported

Public Chats

https://get.status.im/chat/public/CHANNEL-NAME eg https://get.status.im/chat/public/status

DApp Browser

https://get.status.im/browse/DAPP-ADDRESS eg https://get.status.im/browse/www.cryptokitties.co

Users

https://get.status.im/user/CONTACT-ADDRESS eg https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx https://get.status.im/user/name.stateofus.eth

Custom URL Scheme

In addition to the deep links the above links can be called with the status-im:// custom URL scheme, such as status-im://chat/public/status



<blockquote><div><strong><a href="https://get.status.im/chat/public/CHANNEL-NAME">Join the public chat: #CHANNEL-NAME in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/chat/public/status">Join the public chat: #status in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/browse/DAPP-ADDRESS">Browse to DAPP-ADDRESS in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/browse/www.cryptokitties.co">Browse to www.cryptokitties.co in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/user/CONTACT-ADDRESS">View user CONTACT-ADDRESS profile in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx">View user 0x044166fa04e967e333211ae0cc1087c9c74exxx profile in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/user/name.stateofus.eth">View user name.stateofus.eth profile in Status</a></strong></div></blockquote>
