### ISSUE TITLE
Blue progress bar on chat screen spins infinitelly

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7520]
***Type***: Bug

***Summary***: In some cases progress bar runs infinitely on chat screens. 
Can reproduce, but it just happens from time to time. 
It was noticed with Desktop MacOS app (in my case, but mobile affected as well) after Status was on background for ~10 mins then opened and navigated to any type of chat. The blue bar spinning for infinitely long until app restart or mailserver change. 
In my case it happened when I was:
Connected to mail-01.do-ams3.eth.beta (manually set this mailsever) -> put Status on background -> disable WiFi connection for ~7-10 mins -> enable WiFi -> wait 1 minute more -> open Status 

#### Expected behavior
Blue progress bar disappears after contact connected to mailservers successfully and messages are fetched 
#### Actual behavior
Blue progress bar spinning infinitely even contact connected to mailservers successfully and messages are fetched (these two items I confirm by joining to public chat and receiving messages history)

![inf_blue-bar](https://user-images.githubusercontent.com/8749671/52948691-ba8bcd00-3382-11e9-8569-5d038cd66c9a.gif)

### Reproduction

- Open Status and confirm no progress bar is running  
- Manually set connection to particular mailserver (in my case it was mail-01.do-ams3.eth.beta)
- Put Status on background
- Enable airplane mode
- Wait 10 minutes
- Disable airplane mode
- Open Status and pay attention to blue progress bar

### Additional Information
* Status version: Develop (`Desktop v0.9.0 (1da67672a)`)
* Operating System: iOS, Android, MacOS

#### Logs

[Status.log](https://github.com/status-im/status-react/files/2879206/Status123.log)

**Comment by Serhy** [comment]
Updated description with log for MacOS. 
After I unlocked PC and opened Status I noticed spinning blue bar. I flushed Status.log, waited 5 minutes - spinning bar was 'In progress' state... Then I changed mailserver (could be seen by looking in logs at `update-mailservers` event in logs)- and everything become fine (i.e. spinning bar disappeared)

**Comment by cammellos** [comment]
@Serhy thanks for the logs, I think what I need is the logs just before this, essentially the loading bar is there but it's not doing anything, we need to get the logs that initiated the loading bar in the first place.
Do you still have those logs?

There is also https://github.com/status-im/status-react/pull/7524 that might fix the issue, if you'd like to spin it for a ride.
Thanks!

**Comment by Serhy** [comment]
Actually yea, just got the issue again (simply opened MacOS build from background while WiFi connection always on place). The only remark is that I had installed and recovered my account on mobile device (which reflected on MacOS with 'Pair device' pop-up. It's just a note, because in the past 'Pair device' event had no issues in this relation).
Below is the full Status.log that I have: please note that before ~12:29 it was all fine. And Status opened from background (when endless blue bar appeared) at ~12:30 log timestamps.

 
[Status.log](https://github.com/status-im/status-react/files/2879597/StatusBeforeSpinnerAppeared.log)

Installing MacOS build from #7524 meanwhile to stay on this build.

**Comment by cammellos** [comment]
@Serhy do you have the Geth.log as well by any chance?

**Comment by Serhy** [comment]
No geth.log for desktop build :( 
Maiby because the build I had was after https://github.com/status-im/status-react/issues/7507 issue with geth.log appeared

**Update**: it's not https://github.com/status-im/status-react/issues/7507 but something different. I had enabled 'Logging enabled' and no geth.log. But switched off and on togle button, and I see geth.log. It's MacOS build from #7524 i'm on now.
