### ISSUE TITLE
Null is not an object (evaluating 'u.length') when message from blocked user is coming

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7521]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: it was fixed in #7170, but it is again reproducible in current nightly. When message from blocked user is coming, user is seeing `Null is not an object (evaluating 'u.length')`

#### Expected behavior
no error

#### Actual behavior
![img_8f7deebbb6e1-1](https://user-images.githubusercontent.com/4557972/52949761-82ce5680-337d-11e9-8f05-c4d2f933bfd3.jpeg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account and add User2 to contacts
- Start chat with User2, exchange several messages
- block User2
- as User2: send several messge to 1-1 chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  nightly 18/02/2019
* Operating System: Android, iOS

**Comment by churik** [comment]
@yenda please take a look. Thanks!

**Comment by yenda** [comment]
@churik @cammellos there is an error even before that now when blocking a contact, it was introduced with https://github.com/status-im/status-react/commit/bddae03ab234f6574b0c5d4615f586e81512a638 I propose we revert it

`Error: contact.device-info must be of type 'contact-device-info'`
