### ISSUE TITLE
N/A instead of status-go version in About

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7522]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: N/A is shown instead of status-go version in Profile -> About

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Profile -> About

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly Feb 18
* Operating System: Android and iOS

#### Logs

empty geth.log

**Comment by annadanchenko** [comment]
It looks like it's connected with #7507 
now in logcat for GoLog entries I can find `Starting peer-to-peer node` but it does not contain status-go version
Now:
```
02-18 13:52:54.555 15571 15638 E GoLog   : INFO [02-18|12:52:54.555] Starting peer-to-peer node               instance=StatusIM/android-arm/go1.10.4
```
Previously (in geth.log)
```
t=2019-02-05T18:23:25+0000 lvl=info msg="Starting peer-to-peer node"     instance=StatusIM/v0.19.0-beta.9/android-arm/go1.10.4
```

**Comment by mandrigin** [comment]
I will take a look
