### ISSUE TITLE
Extension is not shown in chat if Development mode is switched off

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7527]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: Extension command and its chat message is not shown after user installed the extension and relaunched the app if development mode is OFF. If user tries to install extension again by tapping on its placeholder message then popup is shown that extension is already installed.

So, in order to have extension working user needs to turn ON development mode. Because user can install extension by scanning QR code or by tapping on extension's message in the chat (e.g. for Gfycat) and have no idea about development mode we need to warn user about setting development mode on or find other solution.

We also might add some info on the message placeholder "To see this message install the extension" to inform about turning on development mode.

So, there should be solution that explains to the user why extension is not shown even if it's installed for 2 cases:

1. user never turned on development mode
1. user turned off development mode after installing an extension

after user relaunch the app:
![img!UNITO-UNDERSCORE!2814](https://user-images.githubusercontent.com/6584810/53026464-4543f900-3463-11e9-98cd-6dcc6159a699.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Install Status and create an account
* Install Gfycat extension from https://status-im.github.io/pluto/try.html?hash=Qmb1B3jXNdc9WZCcWFzpkTXtrurnKxYQFvUDhp2J4SVCCX
* send some Gfycat image to the public chat
* Close the app
* open app again and check if you can see the image and Gfycat command in the chat
Note: if you will turn on development mode then extension image will be shown again as expected. If you will turn it off and relaunch the app then instead of the image there is placeholder with text "to see this message Install the extension"

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.9.33 and 0.9.34
* Operating System: Android and iOS

**Comment by flexsurfer** [comment]
@rachelhamlin I suggest showing the message if dev mode is off, something like "To be able to install the extension you need to enable dev mode first in your Profile under Advanced", wdyt? could you help with the text of this message?

**Comment by rachelhamlin** [comment]
Hmm. Tough one. If the user enables dev mode and revisits this chat, do we then display the install extension message @flexsurfer? 

In that case, I'd write: "Please enable development mode in advanced settings (link to profile)."  [Option A]

Better yet, if we can deep link to the advanced settings section directly, "To see this message, enable development mode (link to advanced profile settings)." [Option B]

**Comment by flexsurfer** [comment]
@rachelhamlin or we can show popup "Enable dev mode and install" "Yes" "No" , in this case, we just enable dev mode when user press "yes" and install the extension

**Comment by rachelhamlin** [comment]
Oooh that would really be best @flexsurfer. We don't need design for this, do we?

**Comment by flexsurfer** [comment]
@rachelhamlin we don't need, we can use a standard popup, I just need a text of this message

**Comment by rachelhamlin** [comment]
Maybe something like this @flexsurfer?

<img src="https://user-images.githubusercontent.com/15470435/53883960-cb8f3c00-401a-11e9-9a84-27c4b4b20e8c.png" width=200/>

**Confirm Install**

`Development mode is required to install an extension. Do you want to enable and continue installing?`

`OK` `Cancel`

**Comment by annadanchenko** [comment]
can reproduce on release 0.12.0 build 13 both ios and android

**Comment by annadanchenko** [comment]
seems like there is some specific case when it can be reproduced, so assigned to myself to investigate more

**Comment by annadanchenko** [comment]
can't repro
