### ISSUE TITLE
Separate DApp & chat tabs in mobile navigation

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7534]
### User Story

As a user, I want to discover the DApps/browser in Status more easily and have separation between DApps and chat. 

### Description

*Type*: Feature

*Summary*: From a [previous issue](https://github.com/status-im/status-react/issues/7030), this is a long requested change by users. User problems to address are (1) difficulty locating DApps/browser in current nav, and (2) [distaste for clutter on home screen](https://github.com/status-im/status-react/issues/6675) between browser items & chat. 

```
The proposed solution addresses ongoing user feedback and findings from UXR such as:

* Path to switching modes (e.g. Wallet -> DApps) is unclear
* Lack of consistent UI element to refer to for app navigation
* Unclear how to start a new chat with a new or existing contact
* Separating DApps entry point from a submenu and bringing back to the main nav bar
```

#### Expected behavior
DApps & chat are their own tabs in the [new bottom nav bar](https://github.com/status-im/status-react/pull/7483), per these [Figma designs](https://www.figma.com/file/deXIBZm6fU1CCL0voYbfTujz/Navigation?node-id=1%3A2).

DApps tab takes users to existing `Open DApp` screen.

#### Actual behavior
Home screen mixes DApps & chat items.

**Comment by churik** [comment]
Don't forget to check scenario 2 from https://github.com/status-im/status-react/pull/7550#issuecomment-468333333 - shouldn't be reproducible after redesign

**Comment by rachelhamlin** [comment]
@flexsurfer should I break this into two issues? 

1) Separate DApps tab
2) Chat tab has plus icon in new position, with chat options only

**Comment by flexsurfer** [comment]
@rachelhamlin yeap, plus icon is a separate issue for sure, thanks
