### ISSUE TITLE
Contact stuck on login screen after Status opened with autologin enabled [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7537]
***Type***: Bug

***Summary***: Contact stuck on login screen after Status opened with autologin enabled. 
If to tap `<` ->  `Other accounts` to return to Sign In screen and try to create new account - user stuck on endless 'Creating your account...' screen
If to tap `<` ->  `Other accounts` -> tap on account, where no autologin enabled, - user appears on Home screen right away.

All fine with Android 6.0.1 (Galaxy Note 4)

#### Expected behavior
Contact logged in to account after Status opened with autologin enabled. 

#### Actual behavior
Contact stuck on login screen after Status opened with autologin enabled. 
<img width="261" alt="screenshot 2019-02-20 at 18 30 34" src="https://user-images.githubusercontent.com/8749671/53107412-a3450f00-353d-11e9-9d24-26221161b6a2.png">

### Reproduction
- Install Status
- Create new account
- Log out of account.
- Log in to account with enabled 'Set password until logout' option
- Close Status
- Open Status

### Additional Information
* Status version: Develop 
* Operating System: iOS 12.1.2

#### Logs

[StatusiOSConsoleLog.log](https://github.com/status-im/status-react/files/2885535/StatusiOSConsoleLog.log)

**Comment by churik** [comment]
Can confirm that can't reproduce on LG V20 (Android 8.0) - all fine and can reproduce on Iphone 7 (IOS 11.4)

**Comment by mandrigin** [comment]
@Serhy it should be a regression... does it behave like that in the release? I use auto-save all the time...

**Comment by churik** [comment]
@Serhy @mandrigin can't reproduce it on release 0.9.33 on  IPhone XS
So definitely a regression

**Comment by mandrigin** [comment]
can we try to identify (if we keep nightlies) where did that happen?

**Comment by Serhy** [comment]
> can we try to identify (if we keep nightlies) where did that happen?

14th of Feb nightly build - all ok.
15th of Feb nightly build - the issue is present
It started after one of the commits (navigation related?) merged that are listed here https://ci.status.im/job/status-react/job/nightly/945/

**Comment by mandrigin** [comment]
@rasom can you take a look if your routing refactoring can cause that?
