### ISSUE TITLE
Bottom navigation jumping to the top of field when you set focus on it

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7545]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: introduced in https://github.com/status-im/status-react/pull/7483 and for fix after merge. Bottom navigation jumps for a moment when keyboard is opened.

#### Expected behavior
bottom navigation is hidden behind the keyboard 

#### Actual behavior
![bts](https://user-images.githubusercontent.com/2364994/52896443-9e482e80-31d0-11e9-81e2-3293fdc16747.gif)
### Reproduction

- Open Status
- Create account
- Join any chat
- open it and set focus to input field

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 21/02/2019
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by rasom** [comment]
not like we have too many options here @churik 

It's rather till we find better way to solve bottom nav on android. That's not a bug, that's how animation works on slower android device.

**Comment by churik** [comment]
so there is no way to get rid of this behavior?
I have LG V20 (it is not really slow device) and this flickering is very noticeable anyway

**Comment by rasom** [comment]
we can adjust animation duration, probably making it slower will help to see actually animation there :D

**Comment by churik** [comment]
Closed as by design for now
Discussion below https://github.com/status-im/status-react/pull/7483#issuecomment-463920754
