### ISSUE TITLE
"Message syncing" section in profile is available for users on wi-fi

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7557]
# Problem

For users on Wi-Fi there is one feature that actually does nothing at attempt to tap on it. It was introduced as a part of https://github.com/status-im/status-react/pull//7433 .
I profile it looks like:
![fsdf](https://user-images.githubusercontent.com/4557972/53249652-ed063480-36b8-11e9-869b-7dd153d0c440.png)
So when the user is using  WI-Fi connection tries to tap on it - nothing happens.

Should we exclude it for this case?

@hesterbruikman @errorists please, take a look when you have time.

**Comment by hesterbruikman** [comment]
Thanks for tagging Chu! On what platform and version is this? On iOS Nightly I do get the Message syncing settings screen, while being on Wi-Fi.

**Comment by churik** [comment]
Well for me nothing happens on both IOS 11.4. and Android 8.0 devices.

**Comment by hesterbruikman** [comment]
That's weird. Here's a screen recording of what it looks like for me: https://file.globalupload.io/1jCfKSdCQp.MP4

Recorded on iPhone 8. iOS 12.1.4 on WiFi.

<blockquote></blockquote>

**Comment by churik** [comment]
Can't reproduce on nightly 25/02/2019
