### ISSUE TITLE
"Not connected. Tap for options" status for messages sent while fetching from mailserver in progress

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7559]
**_Type_**: Bug
**_Summary_**: When message is sent while blue progress bar in progress it very often ends up with the `Not connected. Tap for options` status. But in fact, the message reached mailserver fine since it can be received later from offline inbox

It's follow up issue to whisper-level mailserver message reliability improvement made in https://github.com/status-im/status-react/pull/7243 
Please see video between Desktop (sender) and iOS (receiver) here: https://drive.google.com/file/d/1TG23DfjxwdBDnY06B-AjRIKACVRS0o5Z/view showing the issue.

In a case of Fetching messages which are in progress the message statuses about successfully reaching mailsever fails to be received back by the message sender and so that's why `Not connected. Tap for options`. From the offered options `Resend` / `Delete` message can be deleted but it will be deleted only for message sender. 

#### Expected behavior
Message is marked as 'Sent' if it was sent when user connected to mailsever

#### Actual behavior
"Not connected. Tap for options" status for messages sent while fetching from mailserver in progress
![](https://user-images.githubusercontent.com/8749671/53232741-75261300-3694-11e9-96d9-80fd25d4b770.png)

### Reproduction

* Open Status
* Create new account (do not wait until blue progress bar disappears) and
* Join public chat (e.g. `#whisperconfirmtest`)
* Send text message

### Additional Information

* Status version: Develop
* Operating System: Android, iOS, Desktop OSs

#### Logs
[Status.log](https://github.com/status-im/status-react/files/2893185/Status.log)
 from Desktop build for video session above:

**Comment by churik** [comment]
@Serhy I believe in Status v1.0.1 a bit different, like https://github.com/status-im/status-react/issues/9928 
WDYT?

**Comment by Serhy** [comment]
> @Serhy I believe in Status v1.0.1 a bit different, like #9928
> WDYT?

Exactly. No need to keep this one open, - #9928 is the same with fresher behavior.
