### ISSUE TITLE
0.10.0 public mobile release (0.9.34 in old versioning scheme) 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7566]
issue to manage 0.10.0 release (this is the next release after 0.9.33 and would have 0.9.34 version but we are changing versioning scheme)

open issues and PRs for release: https://github.com/status-im/status-react/labels/release

**Comment by jakubgs** [comment]
![eh_impressive](https://user-images.githubusercontent.com/2212681/53355889-63f63400-392a-11e9-882c-ce768b0c6ad5.gif)

**Comment by mandrigin** [comment]
release ci job: https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/

release branch: `release/0.10.x`. we will use tags to mark the exact commits that are used for releases/hotfixes (like `0.10.0`, `0.10.1`, etc).
That is a usual practice in many open-source projects and will make it easier to navigate our history later.

<blockquote><img src="/static/988e78de/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/">release/0.10.x [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
just pushed Andrea's change (https://github.com/status-im/status-react/pull/7526) to develop and the release branch.

@annadanchenko do we have anything else that is waiting?

**Comment by annadanchenko** [comment]
released
