### ISSUE TITLE
add WIBB token on Rinkeby

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#7568]
Add support of WIBB token on Rinkeby network, to support Womens in Block Chain Barcelona DAO 

Contract adress
0x7d4ccf6af2f0fdad48ee7958bcc28bdef7b732c7

Reference:
https://github.com/womeninblockchainbarcelona/wibb-project/blob/master/0.General/Importing-WIBB-tokens-to-Metamask.md

**Comment by goranjovic** [comment]
@guylouis do we have any icon or logo for this one?

**Comment by guylouis** [comment]
Can't find any. Do we have a generic icon defined for tokens in this case ?

**Comment by goranjovic** [comment]
@guylouis yes, but it's a bit bland. Doesn't matter, I'll add it without the icon, if we do find it in the mean time we'll add it too, if not no harm.
