### ISSUE TITLE
Desktop unable to connect

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7573]
### Description

*Type*: Bug

*Summary*: 

_Edit:_ It seems that my path that produced this problem was actually a downgrade previous nightly back to the [alpha build](https://status.im/get_desktop/). 

~I downloaded the nightly today and can no longer connect. `Chat offline` after switching mail servers and restarting repeatedly. Old version was working.~

Is it just me who is still unable to connect? 

![image](https://user-images.githubusercontent.com/15470435/53332658-c5e37900-38eb-11e9-8c9a-db5ddff24e86.png)

I also got here via migration failure error:

![image](https://user-images.githubusercontent.com/15470435/53332705-e7446500-38eb-11e9-9004-962142a0621a.png)

**Comment by cammellos** [comment]
@rachelhamlin the pictures above are not from a nightly likely, so it looks like the app was dowgraded, do you remember where you downloaded this build from?

**Comment by rachelhamlin** [comment]
Is it possible I just downloaded the alpha build again? So here: https://status.im/get_desktop/


<blockquote><img src="/img/share.png" width="48" align="right"><div><strong><a href="https://status.im/get_desktop/">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>
