### ISSUE TITLE
App in "Offline" state is launched if open app via Push notification (with saved password)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7579]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Offline state is shown for long time (10 minutes at least) if open app by tapping on push notification. password should be saved, so 1:1 chat is opened. Found on Android, can't test on iOS because no PNs are received on iOS when app is closed atm https://github.com/status-im/status-react/issues/7438

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
1:1 chat is opened, app connects to mailserver and massage that triggered PN is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
1:1 chat is opened with Offline status, no new messages shown. Log contains
```
02-25 17:01:56.108 24541 24577 D StatusModule: ConnectionChange: wifi, is expensive false
02-25 17:01:56.113 24541 24576 E ReactNativeJS: ERROR [status-im.mailserver.core:118] - mailserver: update-mailservers error there is no running node
02-25 17:01:56.120 24541 24576 D ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :init-rest-of-chats
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: console.error: "ERROR [status-im.mailserver.core:118] - mailserver: update-mailservers error there is no running node", stack:
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$3@12:346554
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:346351
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:351623
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: c@12:7236495
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: r@12:7236677
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: <unknown>@12:2635905
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: <unknown>@12:2655168
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: cljs$core$IKVReduce$_kv_reduce$arity$3@12:556327
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: _kv_reduce@12:155014
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: reduce_kv@12:265905
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$10@12:2652474
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: <unknown>@12:5590266
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: t@12:5324044
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: s@12:5323921
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: r@12:5324198
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: value@19:3651
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: <unknown>@19:1257
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: value@19:2621
02-25 17:01:56.121 24541 24577 E unknown:ReactNative: value@19:1227

```
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status, add someone as a contact
- log out, turn on "Save password until logout", log in
- close Status app
- get push notification from your contact who send text message in 1:1 chat with you
- tap on push notification, as a result Status app is launched, logs in automatically and 1:1 chat is shown
- check if it's connected to mailserver and if new message is shown in the chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.34 nightly feb 25 and release 0.9.33
* Operating System: Android 9 and 6.0.1
#### Logs

logcat: 
[offline.log](https://github.com/status-im/status-react/files/2901359/offline.log)

**Comment by mandrigin** [comment]
it looks like we never sign in when we start the app from notifications
