### ISSUE TITLE
Feature Request: Better scrolling on Desktop for Linux

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7595]
I find it difficult to catch up on and refer to earlier conversations on Desktop due to a poor scrolling experience. Here are the main pain points:

1) Scrolling with mouse wheel is way too sensitive. It just flies off the handle.
2) I can't scroll with page up and down (nor ctrl-f to search like in most web-based chats, but that's a separate issue)
3) If I try to use my mouse to scroll, the bar disappears or it is too tiny.

Simplest fix would probably be to bind PgUp/Down to scrolling a page (good bounty!). Alternatively decrease sensitivity, if this is a setting somewhere.

cc @hesterbruikman @vkjr

**Comment by Swader** [comment]
This applies to Windows as well. Scrolling is fine with mouse for me, but on trackpad, a single move will scroll the screen thousands of miles up/down, as if the easing is not detected.
