### ISSUE TITLE
Add Uniswap DApp

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7596]
### Description

Add Uniswap DApp. 

**Name:** Uniswap
**URL:** https://uniswap.exchange
**Description:** Uniswap offers automated ERC20 exchange on Ethereum. There is no token, platform fee or listing free.
**Category:** Exchanges

Needs logo.

**Comment by annadanchenko** [comment]
>Needs logo.

is it suitable https://pbs.twimg.com/profile_images/1057983528128954369/Ux8N5qTk_400x400.jpg ?

**Comment by annadanchenko** [comment]
added in https://github.com/status-im/discover-dapps/commit/8db200bef2c8110a6d4a5d57cfc1b7da06651b14
