### ISSUE TITLE
Vertical scrollbar is shown for 1-2 sec on Sign in to Status screen

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7605]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: Unnecessary vertical scrollbar is shown for several seconds and then is hidden on Sign in to Status screen 
![screenshot!UNITO-UNDERSCORE!20190225-132945](https://user-images.githubusercontent.com/6584810/53496729-eb66b300-3aa2-11e9-9aae-5ff434461737.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No scrollbar is shown if height/width of the screen is enough to show its elements

#### Actual behavior
[comment]: # (Describe what actually happened.)
Vertical scrollbar is shown for several seconds and then disappears 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status and create account
* close app
* launch app
* check if there is any scrollbar shown on Sign in screen

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.9.34 nightly and 0.10.0 release
* Operating System: Android 6.0.1 real galaxy S6 and Android 9 rela Pixel XL

**Comment by rachelhamlin** [comment]
@yenda is it possible this came out of fixing the overlap on small screens?

**Comment by yenda** [comment]
I am not able to reproduce on One Plus 5T but from the screenshot it looks like the screen is small enough to require a ScrollView, there is probably a few pixels to scroll down

edit: accidentally closed though I'm not sure it's an issue

**Comment by annadanchenko** [comment]
@yenda  I have another device: Pixel XL and on 0.9.33 release the screen had no scroll while on 0.10.0 it does. so it looks like regression and happens on some bigger screens too.
Also note that this scroll bar disappears after 1-2 seconds even if user does not touch the screen. I would assume that if it's a small screen size then scroll bar should be visible and does not disappear

0.9.33 release
![screenshot_20190227-161846](https://user-images.githubusercontent.com/6584810/53501023-c62a7280-3aab-11e9-9777-a861dfa04794.png)

0.10.0 release build 12:
![screenshot_20190227-162029](https://user-images.githubusercontent.com/6584810/53501052-d2aecb00-3aab-11e9-9cdd-a77d194a6c44.png)

**Comment by yenda** [comment]
![screenshot_20190227-162707](https://user-images.githubusercontent.com/1181225/53501561-af385000-3aac-11e9-90e6-a9796c79398f.jpg)
I don't have any scrollbar at all on OnePlus 5T `1080*2160`.
How can you get such a small screen on Pixel? Isn't it suppose to be `1440*2560`?

**Comment by churik** [comment]
Still relevant in Status V1.0.1 on LG V20 (1440 x 2560)
