### ISSUE TITLE
Determine why bchat does not work in Status

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#761]
http://swarm-gateways.net/bzz:/go-bchat.eth/ 

Runs on Ropsten, requests are async and works on desktop with `geth --light` 

Doesn't appear to work in Status

**Comment by alwx** [comment]
@jarradh hm seems like it works
<img width="487" alt="screen shot 2017-01-30 at 17 38 28" src="https://cloud.githubusercontent.com/assets/911127/22427137/fec7af98-e712-11e6-98ea-b3b13980f788.png">

**Comment by jarradh** [comment]
Apparently the problem occurs on Android and on real device

**Comment by rasom** [comment]
```
Uncaught Error: You tried to send "eth_accounts" synchronously. Synchronous requests are not supported, sorry.
```
This happens on android

**Comment by rasom** [comment]
related to https://github.com/status-im/status-react/issues/682

**Comment by jarradh** [comment]
Ahh I see

**Comment by jarradh** [comment]
From @rasom:
> so… on android sync calls are working now (in my local version). When i’m creating a new board transaction screen is opening and bchat is requesting 2 ETH, but when I confirm transaction nothing is happening, status-go doesn’t respond and five minutes later i see

```01-31 21:38:46.576 23568 23633 D ReactNativeJS: DEBUG [status-im.handlers:123] - :event-str {"type":"transaction.failed","event":{"id":"c2bcf1e4-859a-4991-8464-686767c73f50","args":{"from":"0x0fc7f53d123919f21b46ed29756fa9d893483064","to":"0xd5df04090992ef7f3ec83f53601db3dc8232ee01","gas":null,"gasPrice":null,"value":"0x1bc16d674ec80000","data":"0xf782fa4f000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000024a66000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000015400000000000000000000000000000000000000000000000000000000000000","nonce":null},"message_id":"","error_message":"transaction sending timed out","error_code":"3"}}```

An issue has been created for this status-im/status-go/issues/99

**Comment by jarradh** [comment]
```
Yeah there is no gas estimation in this function, the other clients (ie mist + metamask) have some sort of pre-transaction estimation so people aren't currently running into issues with the current setup. In the past I have run into problems with relying on the client based gas estimation due to the way the contract works, that's why you see hardcoded gas for other transactions (ie posts or new threads).
I'll set the gas amount and let you know when it's complete.
```

Maybe we should also call eth_estimateGas if no gas param provided

**Comment by rasom** [comment]
https://github.com/ethereum/mist/blob/47570c906074cdba89ba520ce5a2f78363e8e2a0/interface/client/templates/popupWindows/sendTransactionConfirmation.js#L160
