### ISSUE TITLE
Search bar and Cancel button do not respond after opening user Profile from found public chat and sending a message to the user

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7617]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Search bar and Cancel button do not respond if 
- find public chat via search
- open a user profile from this public chat
- send message to the user
- return back to Home

![screenshot_20190228-112453](https://user-images.githubusercontent.com/6584810/53560114-f75a7f80-3b4b-11e9-9472-5ddecd3cf9b9.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can cancel search or initiate new search
#### Actual behavior
[comment]: # (Describe what actually happened.)
nothing happens if tap on Cancel or tap on Search bar to start typing
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and join a public chat X with some messages in it
- search for this chat X on Home tab
- tap on found public chat X
- in the public chat tap on some user profile image to open its Profile
- in Profile of the user tap on Send message
- tap on "<" in top left corner to return to Home screen and check if you can start new search or Cancel search to see all chats

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.10.0
* Operating System: Android and iOS

**Comment by churik** [comment]
@yenda please, take a look when have time. Thanks!

**Comment by yenda** [comment]
@churik I will deal with it on Monday, gave it a shot today but wasn't successful
