### ISSUE TITLE
Group invite is shown if group is created by blocked user and some other user joins the group

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7622]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Alice blocked Bob. When Bob creates a group chat then invite to the group is not shown to Alice. However, if some other user joins the group then invite is shown to Alice.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No group invite is shown to Alice 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Group invite is shown to Alice if some other user joins Bob's group chat
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- As Alice: block Bob
- As Bob: create new chat with 2 users: Alice and user3 (user3 is not in Alice's contacts)
- As user3: join group chat created by Bob
- As Alice: check if Bob's group chat is shown in the chats list

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.10.0
* Operating System: found on Android (alice and user3), iPhone (Bob)

**Comment by churik** [comment]
Comment here:  https://github.com/status-im/status-react/pull/7170#issuecomment-458913087

@yenda @rachelhamlin @hesterbruikman  can you confirm that it is expected behavior or we consider it as an issue?

**Comment by rachelhamlin** [comment]
Still expected behavior, but I've added this to our pivotal icebox along with the other few block user bugs we'd picked out.

I think we should only prioritize it if we hear of it becoming an issue for people.

**Comment by hesterbruikman** [comment]
Agreed, seems like an edge case we need to monitor so good to have it on the board. As I recall there was more confusion around when 'invites' are send and groups joined from different devices. This requires more investigation and design of a Group creation flow. Would not prioritize this at the moment.

**Comment by churik** [comment]
Still relevant in Status V1.0.1

**Comment by cammellos** [comment]
marking as wontfix as seems like the consensus is that it's not something we'll prioritize anytime soon.
