### ISSUE TITLE
0.10.1 public mobile hotfix release

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7636]
issue to manage mobile 0.10.1 hotfix release

open issues and PRs for release: https://github.com/status-im/status-react/labels/release

**Comment by annadanchenko** [comment]
PRs already included in release:
https://github.com/status-im/status-react/pull/7635
https://github.com/status-im/status-react/pull/7637
https://github.com/status-im/status-react/pull/7653 (issue https://github.com/status-im/status-react/issues/7639)
https://github.com/status-im/status-react/pull/7660

**Comment by jakubgs** [comment]
Okay, @mandrigin already added 75ff21be0 to [release/0.10.x](https://github.com/status-im/status-react/commits/release/0.10.x). Please ping me when the other 2 changes are ready to be added as well.

**Comment by annadanchenko** [comment]
https://github.com/status-im/status-react/pull/7637 - ready to be merged into develop and cherry picked for 0.10.1 release

**Comment by jakubgs** [comment]
I see @cammellos already cherry-picked these two:
* 458bc07a2a228ce5fcde99cd592af917c880610d - `Fix concurrent retry-request`
* 37c165a8e16a5d12207ee4859a4ecb2b4b6d5fd3 - `Add unpinning of mailservers`

I guess the only thing remaining is https://github.com/status-im/status-react/issues/7639 right?

**Comment by annadanchenko** [comment]
> I guess the only thing remaining is #7639 right?

now we are waiting for the fix for https://github.com/status-im/status-react/pull/7653 So one more extra PR in addition to #7639

**Comment by annadanchenko** [comment]
https://github.com/status-im/status-react/pull/7653 - ready to be merged into develop and cherry picked for 0.10.1 release

**Comment by jakubgs** [comment]
Merged and cherry picked:
* 0193e4bbf - `Update translations`

Build: https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/25/

**Comment by annadanchenko** [comment]
https://github.com/status-im/status-react/pull/7660 - ready to be merged into develop and cherry picked for 0.10.1 release

**Comment by jakubgs** [comment]
Merged an cherry picked:
* bac21a654 - `[fix 7652] fetching indicator on Home tab`

Build: https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/26/

**Comment by rachelhamlin** [comment]
Thanks for tracking all the issues here @annadanchenko. When do you want to push this?

**Comment by jakubgs** [comment]
It looks like @cammellos bumped the version to `0.10.2` unnecessarily in 88847c292a6a90fdac92fdc9c6ea41ad75ae9ca9.
Igor already changed it to `0.10.1` in c04831ad0820077c9f3771f91217a4d77be45fa9.

**Comment by jakubgs** [comment]
Okay, that was fixed. We have a ready `0.10.1` build:
https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/30/
Unless there's anything else we want to include then that build is good to go.

**Comment by annadanchenko** [comment]
@rachelhamlin @pablanopete it looks like we can release today's afternoon if all is ready on comms side. please, check in #test-team channel for the latest status ~15:00 CET and let's target to release at 15:30 CET if all is OK

**Comment by annadanchenko** [comment]
@rachelhamlin @pablanopete TestFlight build is Waiting for Review, so it might not be ready by 15:00 CET today.

**Comment by annadanchenko** [comment]
TestFlight build not Approved yet, can take 1-2 days. Let's move release date to tomorrow (Mar 7) 15:00 CET

**Comment by annadanchenko** [comment]
Ready to release hotfix 0.10.1 today at 15:00 CET

**Comment by annadanchenko** [comment]
released
