### ISSUE TITLE
Small copy fixes for 0.10.1 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7639]
### Description

Can we please make the following copy adjustments on these strings for [#7636](https://github.com/status-im/status-react/issues/7636)? 

1. `DApps permissions` to `DApp permissions` (Profile)

<img src="https://user-images.githubusercontent.com/15470435/53633530-03ac0e80-3c18-11e9-952d-2570dbf3f165.png" width=200/>

2. `Browsers` to `Browser` (Home search)

<img src="https://user-images.githubusercontent.com/15470435/53633580-30f8bc80-3c18-11e9-9c97-67b2ed33b113.png" width=200/>

3. Block contact pop-up confirmation (Block user flow)

<img src="https://user-images.githubusercontent.com/15470435/53633601-4241c900-3c18-11e9-8693-d3361583f50f.png" width=200/>

`Blocking will delete all of this user previous messages and stop new ones from reaching you`

to 

`Blocking will delete this user's previous messages and stop new ones from reaching you`

4. Rename `Message syncing` to `Mobile data` (Profile)

<img src="https://user-images.githubusercontent.com/15470435/53633649-60a7c480-3c18-11e9-9958-085e20a3eb59.png" width=200/>
<img src="https://user-images.githubusercontent.com/15470435/53633678-71f0d100-3c18-11e9-805e-c931070ad125.png" width=200/>

**Comment by rachelhamlin** [comment]
cc @hesterbruikman for a review, if you will :)

**Comment by hesterbruikman** [comment]
'Message syncing' also needs copy update on the bottom sheet.
I'll report the issue of the background seperately.

![screenshot_20190301-080037](https://user-images.githubusercontent.com/35233054/53634986-10cafc80-3c1c-11e9-8700-eaddddfc93bd.png)

**Comment by annadanchenko** [comment]
@rachelhamlin chelhamlin 
> 1. `browsers` to `browser` (Home search)

I guess you want it to be started from capital letter, so `Browser`, right?

**Comment by rachelhamlin** [comment]
Yes, fixed - thanks @annadanchenko

**Comment by annadanchenko** [comment]
> 'Message syncing' also needs copy update on the bottom sheet.

@hesterbruikman what's wrong with 'Message syncing' copy on the bottom sheet? atm, all requested changes are implemented except this one. Can you provide the text, please?

**Comment by hesterbruikman** [comment]
It's a minor change for consistency:
Sync using Mobile Network > Sync using Mobile data

**Comment by annadanchenko** [comment]
@cammellos can you address https://github.com/status-im/status-react/issues/7639#issuecomment-469283375 please?
