### ISSUE TITLE
Backspace removes the function button.

### ISSUE THREAD

**Issue by Smokyish** [status-im/status-react#764]
Let's say you have /browse function selected and the button is active in the message field, if you input a url/text and have a typo there, if you hold down backspace long enough, or just repeatedly push it, the button also get deleted and the input field closed and you need to re-select it .

I think it would be better if the button would stay static and could be changed by tapping it and choosing the function (browse, send, location etc.) from the menu, and the message input field would only delete the text but not the function button.

**Comment by jarradh** [comment]
This is by design, it's not a button its just text in the input field. I get your point I'm not sure it's an issue, anyway you on the design channel and you can see how we've already done exactly what you've described.
