### ISSUE TITLE
Message sync/Mobile data bottom sheet background

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#7640]
# Problem
On small screen, Android 7, the bottom sheet modal to set sync options over mobile data lacks background. This issue good not be reproduced earlier, but still persists.

Current behavior
Bottom sheetis shown without background, making sheet and background text unreadable.

Expected behavior
Bottom sheet is shown with background on all devices.

![screenshot!UNITO-UNDERSCORE!20190301-080037 3](https://user-images.githubusercontent.com/35233054/53635429-6653d900-3c1d-11e9-97be-20757a859921.png)

# Future Steps
Check on small screen Android 7

**Comment by churik** [comment]
@hesterbruikman can you please recheck this on current [nightly](https://status-im.ams3.digitaloceanspaces.com/StatusIm-200226-025900-17e5fc-nightly-universal.apk) ?
Bottom sheet modals were redesigned, I have never experienced this issue.

**Comment by hesterbruikman** [comment]
Resolved in the latest nightly!

![Frame 1](https://user-images.githubusercontent.com/35233054/75440906-f295fa80-595c-11ea-95f0-a771a7726eae.png)
