### ISSUE TITLE
Snackbar in wallet obtrudes amount

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#7641]
# Problem
When currency conversion error is shown, snackbar obtrudes content, specifically total asset value.

## Current behavior
Snackbar overlays wallet content

## Exected behavior
Snackbar pushes wallet content down

![signal-2019-03-01-080741](https://user-images.githubusercontent.com/35233054/53635884-cb5bfe80-3c1e-11e9-93bf-85b15b96c07f.png)

# Implementation
In Chat a new Snackbar component was implemented that pushes content down, rather than be displayed as an overlay.

# Acceptance Criteria
On all occasions snackbar is shown in wallet, wallet content is pushed down.
Rules for the future PR to be accepted.

# Future Steps
Check for other places where older version of snackbar is used.

**Comment by hesterbruikman** [comment]
@goranjovic this one is not on any backlog at the moment. Can you advise on whether it should be or if this might be a bounty candidate? 

cc @rachelhamlin

**Comment by rachelhamlin** [comment]
Oh yes, let's put a bounty on. Would you mind helping a contributor with this @goranjovic?

**Comment by goranjovic** [comment]
@hesterbruikman This was actually intentional. The thing that gets hidden away is the total asset value *in fiat*. Now, this error happens when conversion rates are unknown because the api that gives us the rates is unreachable, e.g. blocked by proxy, down or phone is simply offline. 

In that case, we were previously displaying 0, which is misleading and outright scary. At some point we made it hide the figure in this scenario, as its fiat value is meaningless without a correct rate.

**Comment by goranjovic** [comment]
I agree that we should have a design task to figure the proper way to communicate what I said above to the end user, as the current state was based on an ad hoc decision during release testing/fixing. 

But we can't just implement it like described in this issue - would result in a regression.

**Comment by hesterbruikman** [comment]
Thanks @goranjovic ! I'll create a design story for it in wallet and see who has time to look into this. It sounds like we need a distinction between empty states 
(pending and not available) and error states/information. 

This is not unique to wallet:) Will remove the bounty label until we have this figured out.

https://www.pivotaltracker.com/story/show/164399297

**Comment by cammellos** [comment]
This looks outdated as wallet has gone through many changes, feel free to reopen if not the case
