### ISSUE TITLE
Next level search bar behavior

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#7643]
# Problem
When pulling down and showing the searchbar by accident, e.g. pull to refresh attempt, t stays persistant and takes unexpected effort to get it out of view.

## Current behavior
After pulling to show the searchbar I need to tap on it to find a 'Cancel'

## Expected behavior
The searchbar disappars like magic when not used;)

# Implementation
Persistant cancel icon
Searchbar can be 'pushed' back up

**Comment by hesterbruikman** [comment]
@errorists any thoughts on how to manage Search bar disappearance?

**Comment by errorists** [comment]
Yeah, for reasons due with RN architecture we couldn't have it the way I intended to and now I'm beginning to consider the alternatives. What I'd propose is to get us moving on with searching message history and remove the animation, searchbar remains fixed at the beginning of chats list, dapps get their own tab and we remove browser results in search. To me the search right now is very beta and I'd like to move forward here.

In the current implementation, scrolling up should remove the searchbar, inverse to how scrolling down shows it. In addition it should only work when you're at the beginning of the list so the search is shown during the overdrag behaviour.

**Comment by hesterbruikman** [comment]
To be continued here: https://github.com/status-im/status-react/issues/7697
