### ISSUE TITLE
History message display incorrectly

### ISSUE THREAD

**Issue by qfrank** [status-im/status-react#7650]
# Problem

After click on public channel '#status', can't see the message 'Anyone home?',pls check details with attach files.

![11](https://user-images.githubusercontent.com/12406719/53705075-d4d2aa00-3e5c-11e9-94bb-6422f4472143.png)
![12](https://user-images.githubusercontent.com/12406719/53705076-d56b4080-3e5c-11e9-9eba-4ac6fc3c9a95.png)
![13](https://user-images.githubusercontent.com/12406719/53705077-d56b4080-3e5c-11e9-8530-1c14e34b349a.png)

my ios system version: 12.1.3

**Comment by qfrank** [comment]
hi @flexsurfer 
why this issue just simply get being  closed without explanation?

**Comment by flexsurfer** [comment]
hi @qfrank , sorry, i thought it was fixed, feel free to reopen if it's still relevant, thanks
