### ISSUE TITLE
Deeplinking issue (universal link to ENS username)

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#7651]
### User Story
As a user, I expect that when I am sent a status link like https://get.status.im/user/foo.stateofus.eth, a chat is directly opened with the user `foo.stateofus.eth`. This is currently not the case..

#### Expected behavior

* Opens a chat directly with the user.

#### Actual behavior

* Status is opened

### Reproduction

* Simply share a link and click on it

### Additional Information

* Status version: v0.10.0
* Operating System: iOS

**Comment by StatusSceptre** [comment]
Great catch @decanus thanks for opening the issue!

@yenda @rasom @rachelhamlin FYI - what would need to be done to resolve this; is this part of the profile restructure? Currently ENS names are only served through the interface and deeplinks do not recognize them and contact code is default share.

**Comment by rachelhamlin** [comment]
Nice catch. I'd love to see this happen at some point.

**Comment by hesterbruikman** [comment]
Issue in progress: https://github.com/status-im/universal-links-handler/issues/17
https://github.com/status-im/status-react/pull/9811
