### ISSUE TITLE
No fetching indicator is shown on Home tab

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7652]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is no fetching indicator shown on Home tab only if user opens some chat screen then indicator is shown. It gives user wrong impression on the app state (fetching vs done fetching) and can lead to complains on no messages received if user remembers last message in the chat and looks only on Home tab

Issue:
![screenshot_20190304-113025](https://user-images.githubusercontent.com/6584810/53727715-271dc600-3e71-11e9-8287-f6c979c22b53.png)

Works fine inside chat screen:
![screenshot_20190304-113010](https://user-images.githubusercontent.com/6584810/53727729-31d85b00-3e71-11e9-9782-a8cd49b8c0bd.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Fetching indicator (blue line) is shown on Home tab when fetching messages is in progress
#### Actual behavior
[comment]: # (Describe what actually happened.)
Fetching indicator is not shown on Home tab, only if open chat scree then it's shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Jon status public chat 
- Go to Home tab (by tapping on < button) while fetching is still in progree
- check if fetching indicator is moving on Home tab above chat list

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.10.0 release and nightly
* Operating System: Android (Pixel XL, Android 9, Galaxy S6 Android 6.0.1) and if use release 0.10.0 then can reproduce on iOS too (iphone 7 plus, ios 11.0.3)

**Comment by rachelhamlin** [comment]
@yenda possible for you to take a look at this one?

**Comment by annadanchenko** [comment]
@yenda I've rechecked iOS release 0.10.0 this issue exists there too, so it's not Android specific for release

**Comment by annadanchenko** [comment]
@yenda it's the last issue that needs a fix and will be included into hotfix release. Any estimate when it can be ready for testing?

**Comment by annadanchenko** [comment]
fixed by https://github.com/status-im/status-react/pull/7660
