### ISSUE TITLE
[TESTS] Add new critcal tests

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7661]
Add e2e for new critical tests:

- [x] [pair devices ](https://ethstatus.testrail.net/index.php?/cases/view/5762)
- [x] [block user feature](https://ethstatus.testrail.net/index.php?/cases/view/5763)
- [x] [chat search](https://ethstatus.testrail.net/index.php?/cases/view/5757)

**Comment by Serhy** [comment]
It was implemented in https://github.com/status-im/status-react/pull/8303
Closing the issue
