### ISSUE TITLE
Different chat history for #status is shown on different app versions

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7672]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Using 3 different app versions I can see different content in #status history. Versions I use:
- 0.10.0 release,
- desktop nightly 0.9.0 (a34ec7ffb) status-go v0.23.0-beta.5
- yesterday's PR build 0.11.0 status-go v0.23.0-beta.7 from https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-7660/1/ 

### Content 0.10.0 release (from Mar 3 to start of Mar 4 = Yesterday):
Note that Mar 4 contains 1 message "Anyone home?" and Yesterday starts with Korean messages. The issue is that Yesterday is Mar 4 so both should be grouped together

![img_5902](https://user-images.githubusercontent.com/6584810/53795515-71b34700-3f32-11e9-9da0-fa4fa4a7cb90.jpg)
![img_5903](https://user-images.githubusercontent.com/6584810/53795527-77a92800-3f32-11e9-9655-c3ac0e0a6795.jpg)
![img_5904](https://user-images.githubusercontent.com/6584810/53795532-7c6ddc00-3f32-11e9-8536-0a2918b52a41.jpg)
![img_5905](https://user-images.githubusercontent.com/6584810/53795542-7f68cc80-3f32-11e9-886f-44f6520e750b.jpg)

### desktop nightly 0.9.0 (a34ec7ffb) status-go v0.23.0-beta.5
<img width="1333" alt="screen shot 2019-03-05 at 10 38 15" src="https://user-images.githubusercontent.com/6584810/53795717-d8386500-3f32-11e9-8bf1-da9202da2764.png">

### yesterday's PR build 0.11.0 status-go v0.23.0-beta.7 (as of Mar 4)
![img_2843](https://user-images.githubusercontent.com/6584810/53795942-56950700-3f33-11e9-9cbc-c0f9f1f9adff.jpg)
![img_2844](https://user-images.githubusercontent.com/6584810/53795955-5c8ae800-3f33-11e9-95d2-084fbf5012cb.jpg)
![img_2845](https://user-images.githubusercontent.com/6584810/53795966-614f9c00-3f33-11e9-990e-05b715e50b19.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
History is the same for same chat on different app versions

**Comment by asemiankevich** [comment]
so i have desktop V 0.9.0 (40b3100cf) (some old one). 

here is the message pull for March 3
 
![image](https://user-images.githubusercontent.com/28752642/53796998-56eacd80-3f46-11e9-983e-f84e743f1b48.png)

and March 4

![image](https://user-images.githubusercontent.com/28752642/53797107-8ef21080-3f46-11e9-8639-b02145969f75.png)

`anyone home` message is missing, yes, some korean messages are in place

![image](https://user-images.githubusercontent.com/28752642/53797260-e1333180-3f46-11e9-87e8-269046f842b4.png)

**Comment by mandrigin** [comment]
@annadanchenko okay, so is there any version that actually behaves properly? :)

**Comment by churik** [comment]
Not relevant after launching Status v1.0.1
