### ISSUE TITLE
Public chat history disappears 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7674]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: History of the #status public chat was present yesterday and now it disappears. 
![screenshot_20190305-083457](https://user-images.githubusercontent.com/6584810/53798447-8d215080-3f38-11e9-9d17-5d777575cbea.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
History is present
#### Actual behavior
[comment]: # (Describe what actually happened.)
History disappears
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open #status chat
- Scroll to see history before Yesterday

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33
* Operating System: Android

**Comment by mandrigin** [comment]
@annadanchenko @jarradh can anyone reproduce it on 0.10.1?

**Comment by churik** [comment]
Couldn't reproduce in Statusv1.0.1
