### ISSUE TITLE
Error error error.. doesn't support name when entering profile - about

### ISSUE THREAD

**Issue by arnetheduck** [status-im/status-react#7683]
After hitting #7337, clicked ok to get rid of error and then wanted to click profile -> about to find app version. Got the attached error, had to restart app, now it works again.

![screenshot_20190305_194422_im status ethereum](https://user-images.githubusercontent.com/1382986/53850248-29227a80-3f80-11e9-837c-550e456b36a4.jpg)

**Comment by churik** [comment]
Didn't see it during testing after release Status-v1.0.1
Please reopen if it is still relevant for someone.
