### ISSUE TITLE
When resend long messages (> 20 rows) in public chats, 2 messages are shown for sender

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7686]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when resend long message (>20 rows, with "Show more" option) only one message is sent (it is expected) in public chat but fo sender two messages are shown.
![receiver](https://user-images.githubusercontent.com/4557972/53870828-3af53380-3ffb-11e9-9e5b-8310fdf740d0.png)

#### Expected behavior
one message will be sent and shown

#### Actual behavior
one message is sent, but two messages are shown for sender

### Reproduction

- Open Status
- Join any public chat
- Paste to message area a long message (> 20 rows)
- Go to offline 
-  Quickly send the message (~in 2 sec after going to offline). Wait until "Not Confirmed. Tap for options" is appeared.
- Go to online.
- Resend message.

### Additional Information

* Status version: release 0.10.0
* Operating System: all

**Comment by rasom** [comment]
> Go to offline
> Send a long message (> 20 rows). Wait until "Not Confirmed. Tap for options" is appeared.

on mobile send button is disabled if device is offline

**Comment by churik** [comment]
@rasom not in first two seconds. I updated issue to be more precise.

**Comment by churik** [comment]
not relevant anymore
