### ISSUE TITLE
Support Goerli testnet

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7689]
# Problem

I can't use Goerli cross-client testnet on 0.10, which is the new hot testnet.

# Acceptance Criteria
Under network settings, I expect to be able to select Goerli test net. I also expect it to work.

Rules for the future PR to be accepted.

# Notes

https://goerli.net/

I suggest we make this a bounty. I don't know the scope of this integration, so I defer to @mandrigin and @adambabik 

# Future Steps
-

**Comment by adambabik** [comment]
The first thing is to upgrade status-go to the newest go-ethereum. After it's done, this should be trivial and a bounty makes sense.

**Comment by Swader** [comment]
Please also consider adding https://lisinski.online - it's a national testnet we're running that's a clone of Goerli. We're also running shh and swarm, along with IPFS, so it's a full, public testnet meant to be pushed to its limits. I can help with this.

**Comment by oskarth** [comment]
@adambabik do we have an issue for that? if it isn't prio I'd suggest making it a bounty as well.

**Comment by mandrigin** [comment]
https://github.com/status-im/status-go/issues/1413
