### ISSUE TITLE
Add e2e test based on 7680 (sign typed message to dapp)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7696]
# Problem

https://github.com/status-im/status-react/pull/7680 should be coverd in e2e tests with middle or low priority (run in nightlies, dont run in PRs).

- open status
- switch to ropsten
- open test dapp
- open transactions
- make sure text box for [Sign typed message] is pre-populate with JSON
- tap Sign Typed Message
- make sure Signed typed message has response hash

**Comment by antdanchenko** [comment]
test case added with significant changes in steps https://ethstatus.testrail.net/index.php?/cases/view/5784
automated test has been added in #7836
