### ISSUE TITLE
Add test to buy stickers in status app

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7699]
# Problem

We finally have 1 transaction required to buy stickers in status (https://github.com/status-im/status-react/pull/7687), please include this in tests.

Could run it in PRs and nightlies if we have enough space. If not - then nightlies only.

Steps how to buy stickers:
1. open status
2. switch to ropsten
3. faucet eth and stt
4. go to 1x1 chat and tap stickers icon
5. tap Get stickers
6. tap icon with SNT under any sticker pack
7. sign transaction
8. wait for the transaction to be mined (spinner on the stickers screen should disappear)
9. tap Install
10. go back to chat
11. tap Stickers icon and make sure you have stickers pack present now
12. tap any sticker to send
13. check the sticker was received by recipient

**Comment by Serhy** [comment]
Has been implemented in https://github.com/status-im/status-react/pull/7720
Closing this issue.
