### ISSUE TITLE
status.im/stable does not contain 0.10.1 release files but has other artefact with 0.11.0 version

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7703]
# Problem
https://status.im/stable/ page for latest release builds contains artefact with 0.11.0 version that was not tested as release. This version contains some changes (Removed Wallet modals) that were introduced after latest public mobile release 0.10.1 I've checked it on apk file https://status-im.ams3.digitaloceanspaces.com/StatusIm-190307-172340-b63955-release.apk 

<img width="1204" alt="Screen Shot 2019-03-08 at 21 54 59" src="https://user-images.githubusercontent.com/6584810/54055288-e0232e00-41ec-11e9-8ebd-ac06c093167b.png">

# solution
1. Remove content of https://status.im/stable/ and put there 0.10.1 artefacts from build https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/30/

**Comment by annadanchenko** [comment]
@jakubgs @andytudhope after  https://github.com/status-im/status.im/pull/249 apk file is fixed and points to 0.10.1 artefact. However, some issues still present:
1. iOS build contains only QR code that points to 0.11.0 version. Would expect link to ipa file from https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/30/ and QR Code for it
2. all desktop builds should be removed as they were not tested during mobile release 0.10.1 testing and can't be called stable
3. `Updated On` shows today's date. It looks like date is autoupdated while content of the page is fixed

Current situation:
<img width="1193" alt="Screen Shot 2019-03-11 at 12 19 29" src="https://user-images.githubusercontent.com/6584810/54120558-4c25b200-43f8-11e9-90ad-e39ab0d92e30.png">

**Comment by annadanchenko** [comment]
@andytudhope @jakubgs there are 3 issues left:
1. Apk link is wrong and does not work https://status-im.ams3.digitaloceanspaces.com/statusIm-190305-152317-ff3c9d-release.apk It should be capital S in StatusIm: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.apk
2. QR code for iOS still points to wrong 0.11.0 artefact. Would expect link to ipa file from https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/30/ and QR Code for it
3. QR code for apk file is wrong and points to some nightly https://status-im.ams3.digitaloceanspaces.com/StatusIm-190315-025900-670deb-nightly.apk it should be QR code for https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.apk

Desktop links are fine. It's quite urgent as link is shared with users already.

<img width="1273" alt="Screen Shot 2019-03-15 at 09 55 06" src="https://user-images.githubusercontent.com/6584810/54420428-438bef00-470a-11e9-88dc-7959048f875f.png">

**Comment by mandrigin** [comment]
@annadanchenko I fixed the URL and removed QR codes because as it turns out we don't have any QR code generation for stable builds, so the nightlies were copy-pasted. Right now at least there are no wrong builds there, but obviously, this page needs waaaay more work.

@annadanchenko there is actually a file where you can fix the URLs itself: https://github.com/status-im/status.im/blob/develop/source/_data/releases.yml

**Comment by mandrigin** [comment]
I remove the "high-severity" label, but the QR code generation should be fixed!

**Comment by jakubgs** [comment]
This is a fix to missing Diawi link and QR code images: https://github.com/status-im/status.im/pull/255
For future reference, please create issues for https://status.im in the https://github.com/status-im/status.im repo.
