### ISSUE TITLE
RealmJS.build/Release-iphoneos/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh: line 29: node: command not found

### ISSUE THREAD

**Issue by AlleniCode** [status-im/status-react#7707]
There is an error when I use Xcode to Archive:

/Users/zhangyutao/Library/Developer/Xcode/DerivedData/StatusIm-gzunxvmwsbjtksetngwgbybkyoje/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/IntermediateBuildFilesPath/RealmJS.build/Release-iphoneos/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh: line 29: node: command not found
Command /bin/sh failed with exit code 127

**Comment by rasom** [comment]
looks similar to https://github.com/realm/realm-js/issues/1448

**Comment by rasom** [comment]
doesn't look like Status specific issue btw

**Comment by mandrigin** [comment]
@AlleniCode, the solution is listed in this comment: https://github.com/realm/realm-js/issues/1448#issuecomment-340757479

feel free to reopen this issue if it doesn't work for you
