### ISSUE TITLE
Jenkins build to update cn.status.im fails so page contains old link to release apk

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7713]
# Problem

https://cn.status.im/ contains link to apk from old release https://status-im.ams3.digitaloceanspaces.com/StatusIm-181217-093751-07a7a5-release.apk 

If run https://ci.status.im/job/misc/job/cn.status.im/70/ it fails, so can't update to new apk. error in the build: 
```
$ ssh-agent
Identity added: /home/jenkins/workspace/misc/cn.status.im@tmp/private_key_6987807046350796826.key (/home/jenkins/workspace/misc/cn.status.im@tmp/private_key_6987807046350796826.key)
Warning: Permanently added 'node-01.ac-cn-hongkong-c.web.misc.statusim.net,47.244.127.233' (ECDSA) to the list of known hosts.
scp: error: unexpected filename: .
```

# Acceptance Criteria

https://cn.status.im/ page contains link to latest apk. 
atm it's 0.10.1 https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.apk

**Comment by jakubgs** [comment]
Okay, I've fixed the builds for https://cn.status.im/ with https://github.com/status-im/cn.status.im/commit/29407f3bc43416971584b78cfdd0de9b941de84b.

I've also run this build: https://ci.status.im/job/misc/job/cn.status.im/78/
With the provided APK url as a parameter, the URL us now correct on https://cn.status.im/.
