### ISSUE TITLE
App freezes when using it while poor 2G connection enabled [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7714]
***Type***: Bug

***Summary***: It was noticed with 2G connection (on iOS), where network to receive/send data is really poor. Also, perfectly reproducible if you don't have any funds on SIM so no cellular data available and any of LTE/3G/2G networks are enabled.
When using Status app with above conditions - app freezes when navigating between the screens.
In the video below pay attention at:  23rd, 37th, 59th seconds - at that point app was freezing  https://drive.google.com/file/d/1zQ1MZPiH25ioNjSL6iB9yTnUsyGlwT7-/view?usp=sharing

NOTE: issue with app freezing is not present when Airplane mode enabled 
NOTE2: it's all fine with 3G/LTE cellular data enabled.

#### Expected behavior
No freezes when poor (2G) / limited (3G/LTE enabled but no access to cellular data) connection is enabled.
 
#### Actual behavior
Status app freezes when using it while poor 2G connection enabled [iOS]

### Preconditions
WiFi disabled. 
2G cellular enabled (OR your SIM card does not have funds)

### Reproduction

- Open Status 
- Create new account
- Join public chat 

### Additional Information
* Status version: 0.10.1, Develop 0.11.0
* Operating System: iOS 12.1.4 (iPhoneX)

**Comment by 0xc1c4da** [comment]
➤ Hester Bruikman commented:

> Debug issue
> Try on different devices
> Investigate any requests going on upon adding name to account creation
> Create bounty

**Comment by cammellos** [comment]
Closing for now as probably outdated, feel free to reopen if still an issue.
