### ISSUE TITLE
Magic Suggestions Area

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#772]
type `/send 0.02` then hold down delete button.

A suggestions area will appear outside of any command state.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/228?status=New

**Comment by jumarko** [comment]
Would you mind attaching any details (screenshots) to the github issue as well?
Is it possible to simulate on emulator?

**Comment by rasom** [comment]
![mb](https://cloud.githubusercontent.com/assets/2364994/22973808/e9ab3df6-f387-11e6-988f-9003abfb9509.gif)

Still can be reproduced in `develop`
