### ISSUE TITLE
Stickers are not tappable right after install

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7723]
# Problem

Stickers pack is not tappable upon install.

note1: i can swipe to the right to switch to sticker pack
note2: after relaunch it works

# Steps

1. open status (e2e build)
2. switch to ropsten 
3. buy some stickers and install
4. go back to 1x1 chat and tap the installed sticker pack icon

Expected: can tap sticker pack and select it
Actual: can switch only with swipe

**Comment by jeluard** [comment]
Related to #8349 

If you click on current then latest pack right after installation it will work.

**Comment by rachelhamlin** [comment]
Note - this is also an issue when opening the stickers drawer again later on.

It appears as if I am on the pack I own, but instead am seeing my most recently used + cannot tap 'recently used': https://prnt.sc/ofr2u2

**Comment by rachelhamlin** [comment]
@flexsurfer is it possible to have you review this one before next week?

**Comment by flexsurfer** [comment]
@rachelhamlin yes, sure
