### ISSUE TITLE
ONHOLD Remove blue circle icon on avatar when new person starts chat

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#7743]
# Problem
We have a circle icon that is displayed on the avatar of a new person that sends you a chat. The behavior of the icon is illdefined and because of its infrequent use and similarities to a 'online' icon causes confusion for users. However, the icon serves the important function of mitigating risk of impersonation. 

Impersonation can occur when. 
User A (Jarrad) has added User B as contact
User B has or has not added User A as a contact
User C (impersonator) changes their chosen name to Jarrad, adds User B as a contact and requests a transaction.
By showing the blue circle, User B can be triggered to verify User C's identity outside of Status.

We would like to adjust this icon, or look for alternative ways to show that someone is a new contact. As discussed with Chat team, Design team, and with QA.

The icon can be removed when choosen names are removed as part of the Profile update. https://discuss.status.im/t/profile-information-structure-please-review/1080/22

A more important indicator would be to show that someone is 'added to your contacts' in other words, that you are sharing your wallet address (as well as, currently, your chosen user name) with them. However, for the time being we will not repurpose this existing icon because of it's similarity to an 'online' status icon.

![Screenshot_20190314-185229](https://user-images.githubusercontent.com/35233054/54423866-ef850880-4711-11e9-8ab1-f8435ec6ed6e.png)

# Implementation

# Acceptance Criteria
Phone A
- Create new account
- Find someone (yourself) in public channel
- Add to contacts
- Send message

Phone B
- Icon should not appear on avatar

# Notes

# Future Steps

**Comment by cammellos** [comment]
I believe this has been done.
