### ISSUE TITLE
Custom Mailserver won't let me add one

### ISSUE THREAD

**Issue by Swader** [status-im/status-react#7746]
When I go into the add custom mailserver screen in advanced on mobile (iOS), no type of input will make the Save button clickable. I am unable to save any custom mailserver I'm running, tried IP, human readable domain name, enode address, nothing works. Like I'm not typing anything at all in - no error message either.

Androidd 9+.

**Comment by mandrigin** [comment]
Definitely a release blocker taking the chaos unicorn day into account. 
We need to both fix the bug and also show an example of what is expected to be entered there. It is confusing otherwise.

**Comment by Swader** [comment]
@oskarth maybe we should keep a list of chaos day blockers so we can prioritize in the next 10 days for chaos release?

**Comment by annadanchenko** [comment]
@Swader can you share link you are trying to use for mailserver, please? there is a poor error handling that does not enable mailserver Save button if it considers link as invalid... I was adding custom mailserver successfully in one of the recent nightlies... Example of the link that worked for me:
enode://531e252ec966b7e83f5538c19bf1cde7381cc7949026a6e499b6e998e695751aadf26d4c98d5a4eabfb7cefd31c3c88d600a775f14ed5781520a88ecd25da3c6:status-offline-inbox@35.225.227.79:30504

**Comment by Swader** [comment]
So it expects an enode format? Ok hold on, let me regenerate and retry, then I'll post back.

**Comment by Swader** [comment]
`enode://b7a2fe6c8b53650076cb71b5acfad89a74adb2f123ad21d21e9a6dec733299f03ecc56c82fb814c8d0cac4c685e0ab0f6 9ab7c105f6127392821088f0dad6612:status-offline-inbox@192.168.0.54:30304`

This is local network only. Not exposing it outwards just yet.

**Comment by Swader** [comment]
No dice. Save button isn't triggering. I tried with a QR code, too.

**Comment by jakubgs** [comment]
>`enode://b7a2fe6c8b53650076cb71b5acfad89a74adb2f123ad21d21e9a6dec733299f03ecc56c82fb814c8d0cac4c685e0ab0f6 9ab7c105f6127392821088f0dad6612:status-offline-inbox@192.168.0.54:30304`

Why is there a space in this enode address?

**Comment by Swader** [comment]
Oh jesus, you're right. I didn't even see it at 3am. It lets me press Save now, but fails to connect with "could not be reached" error. Progress!

As a matter of UX (@hesterbruikman), I recommend updating the link checking regex here to specifically check for possible errors, to trim left and right, and to have more verbose error messages on fail (each regex check should ideally have its own message). It was almost impossible to notice the space on mobile in the middle of a single-line input.

**Comment by rachelhamlin** [comment]
@Swader the "could not be reached" error was expected?

**Comment by Swader** [comment]
@rachelhamlin yep, I was on the wrong wifi
