### ISSUE TITLE
No error message if provide wrong mailserver or bootnode url

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7752]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is no error message if provided url is considered as invalid. Save button is not enabled and user has no clues on what's wrong and what is expected format (e.g. as in https://github.com/status-im/status-react/issues/7746)

We can show error above the filed with a message on what's wrong and share some expected format for url... Or can add a link to tech doc where adding custom mailserver and sample of the  url format/example are provided...

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Explanation on why the provided url is invalid and what's the valid format
#### Actual behavior
[comment]: # (Describe what actually happened.)
No error message
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
For mailserver:
- Open Status -> Profile -> Advanced -> Mailserver 
- Turn off automatic selection 
- Tap + to add custom mailserver
- provide Name and type "invalid" into mailserver address field
- Check Save button and if there is any error message

![IMG_5969](https://user-images.githubusercontent.com/6584810/54524862-3d4c7b80-4973-11e9-86cd-8f04dd6e2f23.jpg)

For bootnode:
- enable bootnode in Profile -> Advanced -> Bootnodes
- sign in and go again to Profile -> Advanced -> Bootnodes
- Tap + to add bootnode
- provide Name and type "invalid" into bootnode address field

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: all previous releases and current nightly
* Operating System: Android and iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by churik** [comment]
close to https://github.com/status-im/status-react/issues/7333 - but seems there is no error anymore, before it was `Re-matches must match again a string`

**Comment by rasom** [comment]
is this enough?
<img width=250 src=https://user-images.githubusercontent.com/2364994/54694739-6286e880-4b31-11e9-893d-0de9409a8896.jpg />

**Comment by mandrigin** [comment]
@rasom also, as a placeholder, can we provide an  example enode id, so user knows what to enter there?

**Comment by rasom** [comment]
I'm not sure it will fit well in that tooltip, but I'll try

**Comment by rasom** [comment]
@mandrigin @annadanchenko what about this one?

<img width=300 src=https://user-images.githubusercontent.com/2364994/54738122-8bec5680-4bbb-11e9-9a99-03156265cd9f.jpg />

**Comment by mandrigin** [comment]
@rasom I thought about it being in a placeholder of the text field, just like “specify a name”. 
It would still be cool to add that, so when a person opens it for the first time, they know what to do. 

And let’s keep this updated error message too.
