### ISSUE TITLE
Status keeps crashing after Login

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#7757]
# Problem
On certain days, Status keeps crashing after login for practically the whole day. On other days it works fine; haven't been able to find a plausible cause.

Phone: Faiprhone
OS: Android 7 (Low memory and slow processor!)
Status version: 0.10.1 (installed on March 5)
Issue persists on Mobile Network and Wifi

* Launch screen
* Enter password
* Snackbar Offline
* Snackbar Connected
* When the app starts crashing, in the beginning I receive an error message in Status, after restarting (and crashing) a few times, I only see the System OS dialog stating Status stopped.
* After the native dialog is shown that says the app was closed. It is still 'open' as a window. As in I can select the Window which opens Status launchscreen.

_I do receive notifications_

Screen shot was made on March 6
https://file.globalupload.io/S7YqTXt5x0.png

# Implementation
# Acceptance Criteria
# Notes
# Future Steps

**Comment by hesterbruikman** [comment]
cc @annadanchenko @mandrigin

**Comment by annadanchenko** [comment]
@hesterbruikman as soon as it happens again can you launch app, sign in and send logs right after the crash, please? It's in Profile-> Advanced -> Send logs

**Comment by annadanchenko** [comment]
btw, are there any extensions installed? if so which ones? also have you upgraded from previous release or from nightly/PR build before installing 0.10.1?

**Comment by hesterbruikman** [comment]
> 
> 
> @hesterbruikman as soon as it happens again can you launch app, sign in and send logs right after the crash, please? It's in Profile-> Advanced -> Send logs

I've tried, I can't get to them before the app crashes. Is there a file I can access on my phone?

**Comment by asemiankevich** [comment]
I've installed 0.10.1 (2019031114) on my Android 7 - basic functionality works, no crashes at least at first glance. @hesterbruikman  which device you are using?

**Comment by cammellos** [comment]
Just to add, I have had the same issue before, only happens once I had more data (chat & contacts). In the logs I saw an Out of memory error, so this is likely due to memory consumption.

**Comment by hesterbruikman** [comment]
Managed to get Status working on my Fairphone at last. Only step 7 and 8 seemed to have an effect. Any theories on whether this can be the case?

@cammellos what do you think of these opportunities to prevent getting stuck because of 'Out of memory' error:
- No fetching attempt when last received on client was +30 days ago.
- Manual fetching for channels that seem to have gone stale. 

1. Delete chats on Desktop
2. Delete more apps from my phone
3. Uninstall/Reinstall release
4. Uninstall/Reinstall nightly
5. On Reinstall recover old account
6. On Reinstall recover and create a new account
7. On Reinstall create a new account, followed by recover account
8. Toggle of Device sync on all connected devices

**Comment by cammellos** [comment]
@hesterbruikman it's due to the amount of data the app is loading in memory (number of chats/contacts), not necessarily on how much data we fetch from the mailserver etc (I was able to replicate the same issue in airplane mode). The best way to go about this is probably to try to understand where memory consumption is high, and what causes it, but we need to be able to replicate consistently ( I can try again on my device).

**Comment by churik** [comment]
@hesterbruikman do you face it after launch Status v1.0.1?

**Comment by hesterbruikman** [comment]
I'd have to check on my old phone. Back home tomorrow, I'll give it a spin and get back here!

**Comment by hesterbruikman** [comment]
@churik Channels aren't active enough to properly test:/ I'll need to try again when there's more activity or more bridged channels.

**Comment by flexsurfer** [comment]
@hesterbruikman is this still an issue?

**Comment by hesterbruikman** [comment]
Sorry I missed this @flexsurfer hasn't been an issue recently, but I'll dust off that phone to give it a try. Would appreciate some spam in this case as the issue occurs with having a decent number of chats open 0x04f1ab965a3db6433923ceba0488ff605f230aca4c4c93bb6563c10b700cfdbbed2a364c980b9cf9679f352584d4da44cc01fc1e7257f1d2b80ffff5af64aa129f
