### ISSUE TITLE
Paste and other options are not shown after long press on URL input, on DApps screen

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#7760]
Type: Bug

Summary: There are no `PASTE` and other options, after pressing on URL input for 10+ seconds

**Steps to reproduce:**
1. Create new account
2. Go to DApps screen
3. Hold URL input for several seconds

**Expected behavior**
PASTE and other options are shown, after pressing for ~2 seconds on URL input

**Additional Information**
Status version: 0.11.0
Operating System: Android

**Comment by churik** [comment]
Working fine on IOS 11.4.1 (IPhone 7)

**Comment by Serhy** [comment]
Works on iOS 12.1.4 (iPhoneX).
Confirmed on Android8 - no 'Paste' option to insert URL
