### ISSUE TITLE
Image on Welcome to Status screen is not center aligned on small device screens

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7764]
*Type*: Bug

*Summary*: 
On small device screen resolution, like on iPhone5S (640×1136) the Welcome to Status image is aligned to left: 

<img width="594" alt="Screenshot 2019-03-18 at 19 54 57" src="https://user-images.githubusercontent.com/6584810/54611371-19fafc80-4a57-11e9-9032-a8a182b00038.jpg">

Screen introduced with new screen from https://github.com/status-im/status-react/pull/7755 
#### Expected behavior
Welcome to Status image is centred on any screen size

#### Actual behavior
Image on Welcome is not center aligned on small device screens

### Reproduction

- Open Status on iPhone5S
- Enter new password, confirm password
- Enter username
- Presee 'Next' button to navigate to 'Welcome to Status' screen

### Additional Information
* Status version: Develop 0.11.0 (3c5502)
* Operating System: Android and iOS

**Comment by asemiankevich** [comment]
android 5.2" also in charge

![image](https://user-images.githubusercontent.com/28752642/54670152-09ed2680-4b04-11e9-9c5c-f273c17d2d43.png)
