### ISSUE TITLE
Non-mainnet as TX fee and TX history if account recovered after logout from contact that was in POA/xDAI/testnet 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7765]
***Type***: 

***Summary***: UserA was on non-Mainnet network(POA/xDAI/Ropset/Rinkeby). If to log out of UserA -> recover/create another account UserB -> UserB is stick to network UserA was set at some places:
- transaction fee display non-Mainnet fees
- TX history is not-Mainnet
- Fiat values refer to non-Mainnet (on the main Wallet screen, send/request)
- try to add contact by ENS name (it won't find this account because for this it looks in different network)

However, sending ETH/assets by UserB - uses Mainnet network: I bought cryptokitty fine and Send token in 1-1 chat, - even TX fee was xDAI
After user re-logins to account - Mainnet is used as expected on all places.

NOTE: can't reproduce if to switch between accounts with different networks. It happens when second account is created/recovered.

#### Expected behavior
Mainnet applied everywhere: TX fee, TX history, fiat conversion to the account which created/recovered after logout from account used NON-Mainnet network

#### Actual behavior
POA/xDAI/Rinkeby/Ropsten are applied in TX fee values, TX history, fiat conversion by the account which created/recovered (and connected to Mainnet by default) after logout from account used POA/xDAI/Rinkeby/Ropsten  network
<img width="343" alt="Screenshot 2019-05-22 at 20 53 32" src="https://user-images.githubusercontent.com/8749671/58196876-dda48080-7cd3-11e9-94bd-c36846c591ae.png">

### Reproduction

- Open Status and create new account (UserA) 
- UserA switches to POA/xDAI/Ropsten/Rinkeby network
- UserA logs in to account
- UserA logs out of account
- Recover an account (or create a new one). It's UserB.
- UserB checks whether USD conversion is applied according to Mainnet on main `Wallet` screen
- UserB checks whether it's possible to add ENS name
- UserB checks whether Wallet -> Send -> Transaction Fee display Mainnet values
- UserB adds any contact and sends `/send SNT 0`  checks whether USD value

**Actual result**: For the last four items:
- UserA's network applied to USD conversion on Wallet main screen
- ENS name not found
- UserA's network applied to Transaction Fee
- UserA's network applied to fiat conversion in `/send`/`/request`

**Expected result:** 
- Mainnet applied to USD conversion on Wallet main screen
- ENS name is added fine
- Mainnet in Transaction Fee
- Mainnet applied to fiat conversion in `/send`/`/request`

### Additional Information
* Status version: Develop 0.11.0 (UPDATE: confirmed with Release 0.12.2 build - issue is present)
* Operating System: Android and iOS

#### Logs
Logs for scenario when user UserA logged out and UserB created (because that's the place where we should apply Mainnet everywhere
[logcatRopstenOnMainnetInRequest.log](https://github.com/status-im/status-react/files/2985043/RopstenVSMainnet3.log)
Geth.log i've set to DEBUG when UserA created, but issue appears on UserB side until I relogin, so UserB part there is set to use INFO level by default: 
[geth.log](https://github.com/status-im/status-react/files/2985044/geth.log)

**Comment by annadanchenko** [comment]
can reproduce same issue if have 2 accounts:
1. 1st account is on Ropsten
2. 2nd account is recovered (thus on Mainnet) 


Steps:
1. create account1 and switch to ropsten
2. log out
3. recover account to have second one 
4. add someone to contacts of the second account 
5. from wallet send a request to the contact (as second account): despite the fact that ETH and SNT are shown as assets and Mainnet is network the received/sent request is shown in chat as ETHro

**Comment by annadanchenko** [comment]
@Serhy can you recheck for other POA/DAI network if it can be reproduced, please? (it might set severity higher, as now test net is not most frequently used option)

**Comment by Serhy** [comment]
> @Serhy can you recheck for other POA/DAI network if it can be reproduced, please? (it might set severity higher, as now test net is not most frequently used option)

Reproduced with POA, xDAI, Rinkeby and Ropsten.
Additionally, I retested and updated description with more details what happens. 

We Inherit the network in certain places here from the first account by the second recovered/new account

**Comment by rachelhamlin** [comment]
I'm going to leave this one in Core UI backlog without bounty for now, because with multi-account people will have very little incentive to create multiple Status accounts. Thanks for thorough notes @Serhy.

**Comment by churik** [comment]
Couldn't reproduce it in nightly 26/02/2020
