### ISSUE TITLE
2 overlapping screens are shown for a second when creating account 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7770]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When creating an account there is another screen shown on top of the expected one that looks messy. Can reproduce on Android only

<img width="540" alt="Screen Shot 2019-03-20 at 09 59 23" src="https://user-images.githubusercontent.com/6584810/54671832-0010f680-4af7-11e9-8135-e7b42a734aba.png">

![screen](https://user-images.githubusercontent.com/6584810/54672225-eb812e00-4af7-11e9-8bdf-53426cae40c7.gif)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status 1st time
- tap on create account

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.11.0 nightly
* Operating System: Android

**Comment by churik** [comment]
Not relevant in Status v1.0.1
