### ISSUE TITLE
Beta warning popup is not shown after user created an account

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7771]
# Problem

In 0.10.1 we are showing Beta warning popup when user created an account and gets Home/Chat screen for the first time. Now it's not shown. Only after user closes the app and logs in again then popup is shown.

Happens on Android and iOS, nightly 0.11.0 March 20

Steps:
1. Create account and check is beta popup is shown

Expected popup:
![31302](https://user-images.githubusercontent.com/6584810/54673695-1325c580-4afb-11e9-8a5a-b3a6d8bb4fa4.jpg)

**Comment by hesterbruikman** [comment]
When resolving this, please also take a look at Beta alert on upgrading which is slightly different, but might be low hanging when working on this issue. https://github.com/status-im/status-react/issues/7598
