### ISSUE TITLE
There is no text "Searching message history coming..." inside Messages section for search results

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7774]
# Problem

For search results: It might look like search inside Messages does not work while we didn't implement it and should show  "Searching message history coming..." inside Messages section. This text was shown in 0.10.1 but is not shown in 0.11.0:

![Screenshot_20190320-114419](https://user-images.githubusercontent.com/6584810/54678716-022e8180-4b06-11e9-9944-5cc23b33010b.png)

Expected:

![46468](https://user-images.githubusercontent.com/6584810/54678762-1f635000-4b06-11e9-8ae1-d6a793dfec36.jpg)

# Steps:
1. Open status and search on Chat screen

# Platfroms
Android and ios

**Comment by rachelhamlin** [comment]
Womp womp, we have a regression on search @yenda.
