### ISSUE TITLE
Problems with discover updates

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#778]
Steps to reproduce (using newly created account):
1. Open *Discover* screen;
2. Open drawer and edit your status (just adding a tag will work well);
3. Close the drawer. Everything should be fine — your status should be in both "Popular tags" and "Recent tags" lists;
4. Open the drawer again;
5. Edit the status, but don't change the tag.
There is no new status in "Popular tags" list, but it exists in "Recent tags" list.

<img width="487" alt="screen shot 2017-01-30 at 22 02 18" src="https://cloud.githubusercontent.com/assets/911127/22437115/c913a602-e737-11e6-8d60-a8fbd617b903.png">

**Comment by jumarko** [comment]
At first sight, the described behavior looks ok to me.
I'd say that it's a logical behavior to display new status among "Popular tags" only in case some tag has been changed or added.
The "recent discoveries" list should probably show all new statuses ignoring the fact whether tag has been changed or not (and just some text was added).

However, I'm still pretty new to status-im so I'm not sure what was the original intention behind this screen :).

Maybe @jarradh can give some feedback on this.

**Comment by jumarko** [comment]
@jarradh @alwx Would you mind giving some feedback on this issue (see my comment above)?
It's been opened for quite a while...
