### ISSUE TITLE
Gas estimation in ETH/token send from Wallet

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#7786]
# Problem

Default gas limit value is hardcoded for both token and ether transfers from wallet.

This presents a problem in the following two use cases:

1. When user wants to trigger a smart contract default function by directly sending a transaction to the contract address. One example is sending 0 ETH to any ropsten token contract in order to get test tokens.
2. When token transfer function requires a higher amount of gas than what is specified in the default value (hasn't ever happened yet, but is theoretically possible).

Right now, the only recourse users have is to manually increase the gas limit, which is tedious and likely to happen only after their first transaction failed due to 'out of gas'.

# Acceptance Criteria

- Direct transactions to smart contracts are successful with default gas settings
- Token transfers are still successful with default gas setting

**Comment by guylouis** [comment]
@goranjovic can you precise in the issue what's the foreseen strategy we plan to follow to fix this ? thanks !
