### ISSUE TITLE
Share /nix/store with host so that each job doesn't need to fetch the whole Nix store contents

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#7792]
# Problem

The /nix/store folder should be mapped as a volume onto the Jenkins Docker image so they can be shared across builds.

Carry-over from https://github.com/status-im/status-react/pull/7506

**Comment by flexsurfer** [comment]
@jakubgs is this still relevant?

**Comment by jakubgs** [comment]
I'm not sure if this is a good idea. Lets close it.
