### ISSUE TITLE
Patch Android NDK binaries to use Nix's ld interpreter and Nix dependencies

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#7795]
# Problem

We need to do this so that it can run on NixOS (ideally just build from source)

# Implementation

Ideally we should use Android SDK and NDK from nixpkgs, but if not feasible short-term, we should try to just build NDK from source.

Carry-over from https://github.com/status-im/status-react/pull/7506

**Comment by cammellos** [comment]
@jakubgs closing this for now, assuming is stale, feel free to reopen if it's something worth working on.
