### ISSUE TITLE
chat does not scroll if touch starts on top of datemark

### ISSUE THREAD

**Issue by bitsikka** [status-im/status-react#7799]
# Problem

In mobile, in any particular chat with messages, if you touch on the datemark separator(e.g. "Today", "Yesterday") while beginning to scroll - it doesn't scroll.

# Solution

Make the root view of status-im.ui.screens.chat.message.datemark/chat-datemark component a react/touchable-without-feedback view rather than plain react/view

PR incoming

**Comment by annadanchenko** [comment]
@bitsikka thank you! 
can reproduce both on iOS and Android on today's nightly build
