### ISSUE TITLE
Chat messages not correctly ordered

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#7806]
### User Story

As a user, I want to see messages ordered by their timestamp

### Description

*Type*: Bug

![Image-1](https://user-images.githubusercontent.com/359723/54808619-0df28300-4c81-11e9-9cfe-b8a0b61fa30c.jpg)

**Comment by jeluard** [comment]
Just after the message disappeared

![Image-1 (1)](https://user-images.githubusercontent.com/359723/54808867-c8828580-4c81-11e9-9cd7-d1f3f0185c32.jpg)

**Comment by cammellos** [comment]
@jeluard timestamps cannot be used for ordering messages, as they don't give us enough guarantees (for a rationale https://github.com/status-im/status-react/blob/cfcfa01a64ed88b8e01e10b859e316c8de7d11c8/src/status_im/utils/clocks.cljs#L4 ), so it's generally ok to see out-of-order timestamps and does not necessarily 'indicate a bug.

For the specific issue, this is a known behavior, if a user posts in a chat before fetching any message (`Yeah wtf`), that message might be ordered in the past (happens mainly in #status chat as clock-value has raced ahead).
This is something we can mitigate but not prevent completely, without giving up more effective guarantees (namely, causal ordering) for ordering.

 It should not change ordering though (i.e disappear, you should have never seen this message as it would have been ordered back in the past), and that's a regression introduced during performance optimization https://github.com/status-im/status-react/pull/4221#pullrequestreview-119623831 , we can leave this open, but I would change the description.

**Comment by jeluard** [comment]
Ok I understand the technical limitations you are mentioning (under our current messaging architecture) now as a user I find that pretty concerning.

> so it's generally ok to see out-of-order timestamps

Really depends on the perspective :) 

Maybe it would be worth having some page describing those behaviors and stating they are known limitations.

**Comment by cammellos** [comment]
@jeluard good idea, feel free to create one, it's a good way to get acquainted with this part of the codebase and understand the nuances of the implementation!

**Comment by jeluard** [comment]
@cammellos More talking of user expectations, not implementation.

Sounds like you are the one with that knowledge? I'd love to have a FAQ listing those limitations that random users (me?) are probably not aware of.

**Comment by cammellos** [comment]
I would expect you (and everyone else in the team of course) to have that knowledge of a fundamental part of the system and distributed p2p systems in general, as you are not really a random user, but a core developer :) , so that if there's anything to fix , anyone is able to at least understand the basics.

I am happy to assist if you have any question, but I think strong ownership is to be avoided, so this will definitely help sharing knowledge and reduce ownership.
