### ISSUE TITLE
[Wallet] No loading indicator if pull to refresh on main Wallet screen [ios only]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7812]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is no loading indicator if pull to refresh on main Wallet screen - just white space is shown

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
loading indicator is shown
![91090](https://user-images.githubusercontent.com/6584810/54820805-a0eee580-4ca0-11e9-9cc6-8cbfd808eb0e.jpg)
#### Actual behavior
[comment]: # (Describe what actually happened.)
![28393](https://user-images.githubusercontent.com/6584810/54820829-bc59f080-4ca0-11e9-9a0d-bf75b6e54c6e.jpg)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status -> wallet -> pull screen down 

* Status version: release build 14 on iOS only (real iphone 7 plus and 5s)

**Comment by flexsurfer** [comment]
@annadanchenko could you check, should be fixed in develop

**Comment by annadanchenko** [comment]
no more such screen
