### ISSUE TITLE
Sync installed extensions between paired devices

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#7833]
### User Story

As a user, I want all my installed extensions to be synced between devices.

### Description

*Type*: Feature

Syncing works in two steps:

Once devices are paired, there's a `Sync all` button, used to sync data unidirectionally (from the device where sync-all is pressed, to any paired device). Any further extension will be synced automatically, by sending a specially crafted message.

So in essence:
1) After pressing sync all on device A any extension should appear on device B (not viceversa)
2) After installing an extension on device A, the same extension should appear on device B

Given that extension can potentially execute some code, we want to make a decision whether synced extensions are enabled automatically or require user approval.

For an example of what it means to add something to syncing https://github.com/status-im/status-react/commit/5f910a0beced28ae5bfb4086e93fa56659c219db

**Comment by cammellos** [comment]
closing this for now as not relevant anymore
