### ISSUE TITLE
Types are overlapping with names on DApps tab while scrolling

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7834]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: when scrolling in DApps tab - types (i.e. "Exchages", "Games" etc) are overlapping with Dapp list. Relevant only for IOS.

#### Expected behavior
no overlapping
#### Actual behavior
![2019-03-26 12 50 50](https://user-images.githubusercontent.com/4557972/54994937-cee86880-4fc5-11e9-8ab7-1f69478720b9.jpg)

### Reproduction

- Open Status
- Log in
- Open Dapp tab
- Scroll

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release 0.11.0 [builds](https://ci.status.im/job/status-react/job/release/job/release%252F0.11.x/23/)
[comment]: # (Android or iOS.)
* Operating System: IOS (tested on IOS 11.4.1)

**Comment by rasom** [comment]
not relevant anymore
