### ISSUE TITLE
No suggestion list of options in /principles extension appears in chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7843]
***Type***: Bug

*Summary*:  When select `/principles` chat command (after installing respective extension) there is no list of suggested options appears.

It's all OK with, e.g. `/gfycat` extension - suggestion input there appears.

No issues with 0.10.1 release builds.
No issues with the build made of https://github.com/status-im/status-react/pull/7740

#### Expected behavior
List of suggestions appears when tap `/principles` extension chat command
#### Actual behavior
No list of suggestions appears when tap `/principles` extension chat command

<img width="522" alt="Screenshot 2019-03-27 at 10 17 12" src="https://user-images.githubusercontent.com/8749671/55060163-825e6500-5079-11e9-95c2-dc70adfe5b8c.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and create new account
- Navigate to `Profile` -> `Advanced` -> `Extensions` -> `+`
- Paste `https://get.status.im/extension/ipfs@QmSbBVf31sjoqTe5DRUSBd2ADVQejWRqduU3FgfbC32kjP` link ('/principles` extension) -> Install  
- Join any public chat
- Tap -> `/` -> `/principles`

### Additional Information
* Status version: Release 0.11.0, develop 0.12.0
* Operating System: Android and iOS

**Comment by jeluard** [comment]
Please check with https://status.im/extensions/play.html?hash=QmSvd5iehhrkSCQR12hEyJtJzCjEQo1ax8936BnkBhQi5a

**Comment by Serhy** [comment]
> Please check with https://status.im/extensions/play.html?hash=QmSvd5iehhrkSCQR12hEyJtJzCjEQo1ax8936BnkBhQi5a

Works perfectly with 0.11.0 release!

**Comment by jeluard** [comment]
Do you want to keep this issue open?

**Comment by Serhy** [comment]
Closed.
