### ISSUE TITLE
Make new Desktop release build with 0.11.0

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7858]
For Chaos Unicorn Day we needed one new release for desktop.

So for this required:
- make new release branch release/desktop/0.11.0
- update version in this branch
- confirm, that logging is switched off by default in release builds

**Comment by vitvly** [comment]
Branch `release/desktop/0.11.0` created, version updated to 0.11.0.

**Comment by vitvly** [comment]
Logging should be switched off by default in release builds.

**Comment by churik** [comment]
Closed, pages  https://status.im/stable/ i https://status.im/get_desktop/  are updated.
Thanks @siphiuel !
