### ISSUE TITLE
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by kobuta23** [status-im/status-react#7860]
### User Story
As a user, I want to sign a message on ethfinex from my android status app so that an order is posted to 0x markets.

### Description
_Type_: bug

_Summary_:

When signing an order on ethfinex, upon inputting my password, the screen freezes and this message shows: 
Java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
And I am invited to exit, , after which the app crashes

#### Expected behavior
Should sign and proceed

#### Actual behavior
Crashes

### Reproduction

* Open Status
* open trustless.ethfinex.com
* Login selecting status as provider
* lock tokens
* make order and attempt to sign it

### Solution
I wish I knew

### Additional Information

* Status version: Android, version 0.11.0 0.23.0-beta.8-chaos

#### Logs
Not sure how to generate logs

**Comment by jeluard** [comment]
@kobuta23 Can you post steps to reproduce this?
