### ISSUE TITLE
Chat vulnerable to IDN attack

### ISSUE THREAD

**Issue by corpetty** [status-im/status-react#7863]
# Problem
Our chat is vulnerable to an IDN homograph attack as described in [this](https://wildfire.blazeinfosec.com/security-advisory-signal-idn-homograph-attack-2/) article.  

It appears as though browser correctly handles these URLs, but rendered links in chat (both mobile and desktop) do not.

It is important that we properly validate and sanitize text to protect our users from phishing attacks, as we all know the proliferation of them in the cryptocurrency community.  Status _must_ take as many measures as we can to mitigate them.

This was tested by me and @mandrigin in the #test-idn-attack channel (messages are probably past TTL now).

# Implementation

You can recreate this by creating a IDN Homograph at [this site](https://www.irongeek.com/homoglyph-attack-generator.php) and pasting it in the chat.  Then copy and pasting that link to a browser to see what the difference is. 

# Acceptance Criteria

We should follow the recommendations of the above linked article, more specifically:
```
URLs with mixed scripts (e.g., Latin and Cyrillic in the same domain name) or URLs using scripts not installed or enabled in the device should be displayed in the message as un-clickable.

Alternatively, we could implement the same strategy used by WhatsApp to mark the link as insecure, with a clear warning message to the user when an IDN homograph domain name is encountered in the message.
```

pinging @siphiuel, @goranjovic , and @yenda

**Comment by goranjovic** [comment]
@corpetty Should I create a separate issue for the ENS name in wallet and refer to this one?

**Comment by corpetty** [comment]
@goranjovic yes.

**Comment by churik** [comment]
Hello, @corpetty!
Is this one still relevant?

**Comment by churik** [comment]
Closing as not planned and due to the lack of activity
