### ISSUE TITLE
Mailserver request error after restoring drive

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#7872]
# Problem

I had an issue with my Linux install and had to restore an image from a month ago. When opening a chat in Status Desktop I see the following when I click on the gray error at the bottom:

![image](https://user-images.githubusercontent.com/138074/55358072-d2e91e80-54ce-11e9-8493-56c95d95f09e.png)

# Acceptance Criteria

New messages arrive for chats even though the database is old.

**Comment by churik** [comment]
Not relevant anymore
