### ISSUE TITLE
Keyboard overlapped message input when replying to long message (can't see what I'm typing)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7875]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I always want to see what I'm typing.

### Description

*Type*: Bug

*Summary*: when replying snippet is ~5 rows (max) and you typing a reply in message box - you can't see what you are typing starting from 3d lin on Android (LG V20) and from 8d line on IOS (IPhone 7).
This issue is reproducible on nightly 01/04/2018 (so it is not caused by https://github.com/status-im/status-react/pull/7666) but it is not on release 0.11.0 (tested on IOS 12, iPhone XS)

#### Expected behavior
message area is scrollable, can see last row

#### Actual behavior
![photo_2019-04-02 15 08 21 jpeg 2019-04-02 15-08-43](https://user-images.githubusercontent.com/4557972/55404972-66673180-5559-11e9-8f3e-96b571c590fa.png)

### Reproduction

- Open Status
- Open any chat
- Send long message (>5 rows)
- Long tap on message
- On message input type > 3 rows for Android (>8 rows for IOS)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 01/04/2018 
* Operating System: Android, IOS

**Comment by trowacat** [comment]
I will look into this and see if I am able to help

**Comment by churik** [comment]
Not reproducible anymore on nightly 07/01/2020
