### ISSUE TITLE
Update text input field in ENS DApp (component)

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#7886]
# Problem
[Search for available name] input field in ENS DApp can be improved.

The input field needs to communicate that a name needs to consist of:
- at least 5 characters
- letters and numbers only

# Implementation
The following or a variation of. 

- Add label 'Search for available name'
- Add placeholder 'e.g. johndoe66
- A description with above information

Issue requires design input. @andmironov and/or @errorists

Ideally this inputfield is developed as React Native component in this [repo ](https://github.com/status-im/status-components/) first and then reused for React Web in the DApp.

# Acceptance Criteria
Component in https://github.com/status-im/status-components/ following design spec.
Component applied in ENS DApp.

# Notes

# Future Steps

**Comment by hesterbruikman** [comment]
cc @rachelhamlin @jeluard please review if it makes sense to bounty this issue.

**Comment by errorists** [comment]
<img width="375" alt="03@2x" src="https://user-images.githubusercontent.com/4932774/55488130-ba444a00-562f-11e9-90cb-d03c8302a76c.png">

**Comment by jeluard** [comment]
I believe it does, yes!

ENS DApp source is hosted in a different repo: https://github.com/status-im/ens-usernames
It might be simpler to move the issue there?

**Comment by hesterbruikman** [comment]
> 
> 
> I believe it does, yes!
> 
> ENS DApp source is hosted in a different repo: https://github.com/status-im/ens-usernames
> It might be simpler to move the issue there?

Good idea, I'll move it there.

And thank you @errorists , that is some lightingspeed design work! 
Small note: I don't think spaces are allowed, so maybe just `apocalypse22` or something as placeholder.

**Comment by rachelhamlin** [comment]
Thanks for creating this @hesterbruikman. Closing status-react issue.
