### ISSUE TITLE
Discover

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#789]
An Epic for Discover including Screen Redesign Tasks 

See also https://github.com/status-im/wiki.status.im/blob/master/docs/proposals/discover.md

**Comment by sla-shi** [comment]
@denis-sharypin can you pls review, validate, take into account the issues under this epic while working on the Discover UI?
After the new Discover UI is approved - revisit the issues and close the old ones - Vic.

**Comment by annadanchenko** [comment]
Discover feature is removed
