### ISSUE TITLE
Card is not usable after crash on stage "Generating  mnemonic phrase" in offline state

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7892]
### Description
_Type_: Bug

_Summary_: after crash in offline mode when generating mnemoinc phrase during sign up, I can't find a way to continue - tried with `keycard-cli` and with application - in both cases can't connect to card.

#### Expected behavior
Can continue after go back online

#### Actual behavior
Application is crashed. 

After this crash I'm unable to use this card anymore.
If I try to use `keycard-cli delete -l debug` or `./keycard-cli install -l debug cap.cap` tool is hanging on step:

```
./keycard-cli delete -l debug
INFO [04-03|17:37:46.083] waiting for a card package=status-go/cmd/keycard
INFO [04-03|17:37:46.085] card found package=status-go/cmd/keycard index=0
DEBUG[04-03|17:37:46.085] using reader package=status-go/cmd/keycard name="ACS ACR 38U-CCID"
DEBUG[04-03|17:37:46.085] connecting to card package=status-go/cmd/keycard reader="ACS ACR 38U-CCID"
```

If I try to create account using .apk, application is hanging on "Preparing card" stage.

### Reproduction

* Open Status
* Tap on create account -> Keycard
* Create PIN
* On stage "Preparing card" go to Airplane mode
* on "PUK and Pair Codes" tap next
* On stage of "Generating mnemonic phrase" tap try again 

### Additional Information

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 8, LG V20
* Keycard-cli: https://github.com/status-im/keycard-cli/releases/tag/0.0.1, cap: https://github.com/status-im/status-keycard/releases/tag/2.1.1 (installed with https://gist.github.com/gravityblast/8c7472dcf86f7b23c797b79c2dbc1d0a)

#### Logs
Unfortunately, I can't fetch logs for this device - adb is not working.

**Comment by dmitryn** [comment]
App needs internet to fetch bip39 words list during keycard setup. I will check if we can pre-download that list and put it to app resources.
