### ISSUE TITLE
Card is not detected if it's next to the phone and was used to launch Status app

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7893]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: If Status app is not launched and you put your phone on keycard and does not move them: Status app is launched automatically and let's you to select into which account to sign in (I have 2 accounts). If keycard account is selected and user types correct PIN then screen "Hold card to the back of your phone" is shown despite the fact that card is already touches phone. I waited for ~3 minutes and it was still expecting the card. After user removes card and holds it again then he can sign in to the app successfully.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Card is detected

#### Actual behavior
[comment]: # (Describe what actually happened.)
Card is not detected, so user needs to remove it and hold again

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Kill Status app, so it's not running on background
* put your phone on the card -> Status will launch automatically (do not move card or phone)
* enter correct PIN
* check what screen is shown 

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

#### Logs
full logcat:
[allcard2.log](https://github.com/status-im/status-react/files/3039563/allcard2.log)

**Comment by dmitryn** [comment]
I get
```
 java.lang.NullPointerException: Attempt to invoke interface method 'im.status.keycard.io.APDUResponse im.status.keycard.io.CardChannel.send(im.status.keycard.io.APDUCommand)' on a null object reference
```
when i try to interact with the keycard that was connected before app was launched.

Let me check keycard java SDK on this error and if such interaction is possible.
