### ISSUE TITLE
"Wrong word" validation message overlaps required word number on "Recovery phrase" step

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7896]
### Description

*Type*: Bug
*Summary*: if you enter wrong word while checking your recovery phrase, in order to continue you need to go back to "Your recovery phrase" screen, because word number is overlapped with "Wrong word" validation message 

#### Expected behavior
Can see which word is needed 

#### Actual behavior
![Monosnap 2019-04-03 18-02-35](https://user-images.githubusercontent.com/4557972/55494244-b1a54100-563a-11e9-9e7d-ea19b6bd7401.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Tap on create account -> Keycard -> follow instructions
- After "Your recovery phrase" tap Next
- Enter wrong word

### Additional Information

* Status version: 0.12.0 apk  http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 8, LG V20

**Comment by dmitryn** [comment]
I suggest to close the issue as this screen will look differently in new onboarding design and should not have this problem as there is enough space to show error tooltip https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=469%3A299

<img width="363" alt="Screenshot 2019-04-29 21 35 38" src="https://user-images.githubusercontent.com/23836/56918472-d3bda200-6ac6-11e9-80af-d49b65cef591.png">

**Comment by andmironov** [comment]
Addressed in https://github.com/status-im/status-react/issues/9277
