### ISSUE TITLE
PIN screen is shown if cancel sign message in DApp and switch to Chats tab

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7897]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: PIN screen is shown on Chats tab after user returns from PIN screen to sign a message in the DApp and taps on Chats tab

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
list of Chats is shown (or some opened chat)

#### Actual behavior
[comment]: # (Describe what actually happened.)
PIN screen is shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=1thgsPdxlsqCN4zQyppuVXQxt44n9G_k5
While on Ropsten network:

* Open Status and sign in with keycard
* Switch to DApps tab, scroll to the very end and tap on Status Test Dapp
* in Test DApp: tap on Transactions -> Sign message. As a result, Sign message screen will be shown
* tap on Sign
* DO NOT enter PIN. Tap on "<" button in top left corner to return to the Dapp
* tap on Chats icon

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

#### Logs
[comment]: # (if on Android please replicate bug whilst running adb logcat)
[Status.log](https://github.com/status-im/status-react/files/3039711/Status.log)

**Comment by dmitryn** [comment]
`enter-pin` screen is part of the `chat-stack`. When you dispatch `:navigate-to :chat-stack`, view-id changes to `:chat-stack`, but then `:screens/on-will-focus :enter-pin` gets dispatched for some reason (which changes view to :enter-pin). 

@rasom do you have an idea what's happening? I might be using stack in a wrong way.

**Comment by dmitryn** [comment]
Not sure why enter-pin is a part of chat-stack. But the same thing happens when you navigate to wallet-stack (and enter-pin screen needs to be part of the stack) .
