### ISSUE TITLE
Text overlaps border on keycard setup screens (on steps 1. PIN code, 2. Initialization ... )

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7900]
# Problem

On several steps (at least step 1 and 2) for setting up a keycard text on the top overlaps its container. Would expect ... at the end of the text or that it's not visible if goes beyond box border 

* Device: real Galaxy S6, Android 6.0.1
* Status version: 0.12.0 apk  http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk

![1s](https://user-images.githubusercontent.com/6584810/55499842-401fbf80-5647-11e9-96e7-c9d402f51c96.png)
![2s](https://user-images.githubusercontent.com/6584810/55499848-431ab000-5647-11e9-9931-e483ec18ba00.png)

**Comment by andmironov** [comment]
Addressed in https://github.com/status-im/status-react/issues/9274
