### ISSUE TITLE
No dots are shown when entering wrong PIN or PUK code

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7904]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: when entering wrong PIN or PUK codes, initially in design validation error is shown under dots (required number of symbols). For there are no dots shown until the user starts typing. It is relevant for all screens where PIN or PUK code is needed (sign in, log in, change pin, reset)

#### Expected behavior
![eexe](https://user-images.githubusercontent.com/4557972/55538583-0be7e580-56bf-11e9-8bfc-87c59677a7a1.png)

#### Actual behavior
![save](https://user-images.githubusercontent.com/4557972/55538607-1a360180-56bf-11e9-812d-b41d766b7940.png)

### Reproduction

- Open Status
- Tap on "Create account with keycard"
- On Step "Enter pin to procced" on 2 screen  enter wrong PIN

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.12.0 apk  http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 8, LG V20

**Comment by guylouis** [comment]
I guess this can be closed right @churik  ?

**Comment by churik** [comment]
a long time ago, I suppose yes
