### ISSUE TITLE
Two names for recovery phrase ("recovery phrase", "mnemonic phrase") are using during setup process

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7905]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: it may be confusing for users to see 2 names of the same thing during setup process - after 4 step app says "Next step is generating mnemonic phrase" while next step is "Recovery phrase" in header.
So needs to be chaged in "Card is paired" screen and in "Generating mnemonic phrase" screen to "Recovery phrase" for consistency.

#### Expected behavior
"Recovery phrase" is unsing everywhere 

#### Actual behavior
<img width="231" alt="12321" src="https://user-images.githubusercontent.com/4557972/55541757-e7dbd280-56c5-11e9-91bd-e1e511e2fb7f.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard
- Pay attention to "Card is paired" screen

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.12.0 apk  http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 8, LG V20

**Comment by andmironov** [comment]
Addressed in https://github.com/status-im/status-react/issues/9277
