### ISSUE TITLE
Label in Russian is cut 

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#791]
![image](https://cloud.githubusercontent.com/assets/25023739/22633324/46eb9e16-ec85-11e6-8de3-751aca26d887.png)

https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/226?status=New

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/issues/657

**Comment by rasom** [comment]
The issue was fixed in 1165th commit, the version of app in bug report is  `0.9.2-71-g016e9b3+ (1156)`
