### ISSUE TITLE
"Status-unknown go error" at attempt to log in to account when card is reset

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7911]
### Description
_Type_: Bug

_Summary_: when I reset a card, I actually accept the fact that the account will not be useful anymore (or it should be usable?), but it is not handling in app.
I would expect that after I reset card I automatically logged out and redirected to initial screen without any accounts, where I can create new account.
For this:
1) we need explicitly warn users, that account will be deleted
2) implement actual logout and deleting account
For now if I reset card and the logout, at attempt to log in "Unknown status-go error" is shown.

#### Expected behavior
 after I reset card I automatically logged out and redirected to initial screen without any accounts, where I can create new account

#### Actual behavior
Unknown status-go error.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Create account with card
* Go to Profile > Status keycard
* Reset card
* Log out
* try to log in

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android 8, LG V20

#### Logs
[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
04-04 13:15:49.099 23108 23805 I GoLog : ssdp: got unexpected search target result "upnp:rootdevice"
04-04 13:15:49.100 23108 23805 I GoLog : ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178840f5e3"
04-04 13:15:49.100 23108 23805 I GoLog : ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
04-04 13:15:49.101 23108 23803 I GoLog : ssdp: got unexpected search target result "upnp:rootdevice"
04-04 13:15:49.101 23108 23805 I GoLog : ssdp: got unexpected search target result "upnp:rootdevice"
04-04 13:15:49.101 23108 23805 I GoLog : ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178840f5e3"
04-04 13:15:49.101 23108 23803 I GoLog : ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178840f5e3"
04-04 13:15:49.105 23108 23803 I GoLog : ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
04-04 13:15:49.110 23108 23805 I GoLog : ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
04-04 13:15:49.500 2541 2541 I NetworkController.WifiSignalController: Change in state to: connected=true,enabled=true,level=3,inetCondition=1,iconGroup=IconGroup(Default Wi-Fi Icons),activityIn=true,activityOut=true,rssi=-54,,ssid="MiFibra-EBF7",badgeEnum=0,isTransient=false,isGigaWiFi=false,isAttWifiCall=false,detailedState=CONNECTED

```

**Comment by dmitryn** [comment]
I agree that after reseting the card and logout, we also need to delete or hide account from the accounts list as it becomes unusable. We don't have account removal at the moment, so maybe we could just hide it from the list not to confuse user.

@guylouis what do you think?

**Comment by guylouis** [comment]
I agree !

I also opened this issue yesterday about the same problem https://github.com/status-im/status-react/issues/7894

I also think that after card reset we should log out the user from his account, because he can't truly use it for any transactions.
