### ISSUE TITLE
Unable to load page if open names.statusnet.eth during chaos unicorn day

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7912]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If open names.statusnet.eth with chaos mode on then "unable to load page" error is shown. Part of feedback from @oskarth was "Should get a more informative error, or better yet some kind of caching to get (verified) ENS info."

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Profile -> advanced -> turn on chaos mode 
- Profile -> ens names

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.11.0 release
* Operating System: Android and iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by churik** [comment]
Not relevant in Status v1.0.1
