### ISSUE TITLE
If card has keys on it, there is no way to use it with new device (cannot restore an account with pairing code)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7913]
### Description
_Type_: Bug
_Summary_: when I create account with keycard, there is no way to restore it with pairing code.

#### Expected behavior
can restore account

#### Actual behavior
"This card has already an account on it. If you wish to change it, login first and then reset your card".
So if you don't have card-reader or device with initial install - it is dead end for card.

### Reproduction

* Open Status
* Create account with keycard
* Reinstall build or install on another device
* Tap on "I already have an account" > Keycard
* Tap card and enter valid pairing code

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android 8, LG V20

**Comment by asemiankevich** [comment]
@dmitryn can we rebase ? i think we have the fix for navigation when user is not able to recover account -> redirect to home screen when tapping a card. Should be fixed in another PR i belive
