### ISSUE TITLE
Messages are marked as not confirmed

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#7914]
quite a few users have reported

a) Messages marked as not confirmed
b) Messages not being sent
c) Spinner is never removed from messages 

This happens in conjunction of 1) Disabling automatic selection 2) Starting stopping the app while requests to the mailserver are happening (i.e Fetch 24 hours).

There are probably a few issues at play here.

**Comment by churik** [comment]
It is fixed in https://github.com/status-im/status-react/pull/10405
