### ISSUE TITLE
Text for empty chat state is shown upside down and text direction is strange

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7915]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After joining public chat or 1:1 chat its text and icon are shown upside down. Only after sending there at least 1 message the text and icon are shown normally
![Screenshot_20190404-154848](https://user-images.githubusercontent.com/6584810/55561476-81b97480-56f2-11e9-9f2d-2c204c2cb443.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
text and icon have usual position

#### Actual behavior
[comment]: # (Describe what actually happened.)
text and icon are upside down
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Tap +
- Tap Join public chat
- for topic: type "public" (or any other name of empty chat) and tap enter
- check text and icon in the open empty chat

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.12.0
* Operating System: Android and iOS

**Comment by churik** [comment]
Appeared after merge https://github.com/status-im/status-react/pull/7663, but in last builds https://github.com/status-im/status-react/pull/7663#issuecomment-478569201 they were OK.

**Comment by bitsikka** [comment]
on it

**Comment by bitsikka** [comment]
found possible reason:

It is probably due to the recent migration to RN 0.59.2 which probably does not include this fix
https://github.com/facebook/react-native/commit/198eb0269781803cc16254916b0477916afbcb0e

opting for temporary solution until RN is upgraded again separately.

temp fix coming up

**Comment by mandrigin** [comment]
@bitsikka what do you think about upgrading RN instead (0.59.2 → 0.59.3), it is just a bugfix release, it shouldn't affect our app much.

**Comment by bitsikka** [comment]
agreed - that's a better idea.

**Comment by bitsikka** [comment]
- upgrade fixes the problem - tested locally

- cannot send PR to nonexistent branch in `status-im/react-native`

- PR to `status-im/status-react` (with only changes to `package.json.orig`, `yarn.lock`, `Podfile.lock`) depends on PR to `status-im/react-native`

- *These PRs for upgrading RN looks to be better performed internally by a Core dev*

- upgrade also fixes at least one another problem I'd noticed(password field dots leading/line-height change as you type) - probably fixes more problems

**Comment by bitsikka** [comment]
> * These PRs for upgrading RN looks to be better performed internally by a Core dev

cc @rasom 
ping @mandrigin

**Comment by mandrigin** [comment]
@bitsikka I think there is no reason for us to use our own fork or RN at that moment. all the patches we had are already in upstream.
@rasom wdyt?

**Comment by bitsikka** [comment]
Makes sense 👍 

Meanwhile, testing with mainstream RN
Plus, going to keep some mind on cases/issues discussed in PR for RN upgrade to 0.59.2

**Comment by bitsikka** [comment]
no dice
ran into issues with regular RN :(

issues like 
```
console.error: "re-frame: no handler registered for effect:", {"ns":null,"name":"keyboard-max-height","fqn":"keyboard-max-height","_hash":-869899104,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096}, ". Ignoring."

error
    index.bundle?platform=ios&dev=true&minify=false:66704:29
_callTimer
    index.bundle?platform=ios&dev=true&minify=false:28035:17
callTimers
    index.bundle?platform=ios&dev=true&minify=false:28242:19
__callFunction
    index.bundle?platform=ios&dev=true&minify=false:3277:49
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:3034:31
__guard
    index.bundle?platform=ios&dev=true&minify=false:3231:15
callFunctionReturnFlushedQueue
    index.bundle?platform=ios&dev=true&minify=false:3033:21
```

**Comment by mandrigin** [comment]
@bitsikka so you don't have this exact issue on the latest develop? because it is for sure doesn't sound  like RN-related to me.

**Comment by cammellos** [comment]
@bitsikka that's also in develop, https://github.com/status-im/status-react/issues/7917 has the same logs

It means some code is returning `db` instead of `cofx` somewhere, I can take a look at it on Monday.

**Comment by bitsikka** [comment]
@cammellos my bad.. I know at least one place in the code I wrote where I'm returning db instead of cofx. I'm testing it out and so far it gets rid of that particular error above, but, emits another similar error having to do with wallet. Going to continue hunt down and testing.

Thanks for that insight too - I was baffled by the error but now it makes sense.

**Comment by bitsikka** [comment]
@cammellos, @mandrigin fixed (in PR #7922 as a fix for #7917) the error I mentioned above 

So, that error is indeed not concerned with this issue

Hence, no reason so far to not make a PR to upgrade RN to 0.59.3, which will fix this issue

**Comment by mandrigin** [comment]
great! ping me when it's ready!

**Comment by bitsikka** [comment]
> great! ping me when it's ready!

ping @mandrigin

**Comment by churik** [comment]
@bitsikka thanks for your fix!

There are several issues.

#### 1) No label is shown if you open chat via valid deep link

**Steps:**
- tap on valid deep link (i.e. https://get.status.im/chat/public/coo)
- pay attention to opened chat

**Expected result:** can see icon \ label for empty screen state
**Actual result:** 
![photo_2019-04-08 12 07 10](https://user-images.githubusercontent.com/4557972/55716274-dc0a4c00-59f6-11e9-845a-88904deb29f4.jpeg)
If you tap back and again open chat, you can see the label. On nightly you can see label right after you open chat via deep link.

#### 2) Username is not centered when it contains > 1 row
I expect that username should be aligned on center.
For now:
<img width="228" alt="dsfdsf" src="https://user-images.githubusercontent.com/4557972/55716628-bc275800-59f7-11e9-8287-60d48365b58d.png">
