### ISSUE TITLE
Contacts are not synced between 0.11.0 and current nightly

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7917]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: contact list is not synced if one device is using release 0.11.0 and second - current nightly.

#### Expected behavior
 public chats and contact are shown on Device B.
Also group chats and 1-1 chats are synced correctly.

#### Actual behavior
contacts are not synced.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Device A: create account on 0.11.0 (tried on IOS), add contact
- Device B: restore the same account on PR build (tried Mac OS and IOS builds)
- Pair devices A and B
- Device A: tap on sync all

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 04/03/2019
* Operating System: all

#### Logs

Logs for device B:
[geth.log](https://github.com/status-im/status-react/files/3044118/geth.log)
[Status.log](https://github.com/status-im/status-react/files/3044121/Status.log)

**Comment by churik** [comment]
> @bitsikka I don't think the issue was introduced with your PR , I think it was possibly introduced in #7805 @yenda might have more context, but if you check the logs Status.log (line 1703) , looks like it's not validating and therefore is rejected as it is missing one of those system tags

@yenda would you mind take a look?

**Comment by bitsikka** [comment]
@yenda @cammellos I gave it a shot at https://github.com/bitsikka/status-react/commit/76110b9d60189236dbdbb12398d7a55deb2a83b7 . With regards to syncing contacts only, would that work? 🤔 

not making a PR because not sure of the logic and because did not test with 0.11.0 device. Did test it between MacOS latest nightly(A) and iOS-simulator dev build(B) though.

@churik seems like syncing of 1-1 and group chats have been on hold ever since beginning of December last year; which would mean(not verified) that they do not sync even between two 0.11.0 devices.

**Comment by cammellos** [comment]
not in front of the laptop, but does not seem to be what we need. What
looks like is  that in he commit I have sent you before @yenda introduced a
new field for contacts ( system tags) and validate against it (check if
present). Older version don't send this field, so newer versions discard
the message, so the change broke compatibility. Newer version should accept
older version messages and act accordingly.

not sure if it s clear.

**Comment by cammellos** [comment]
https://github.com/status-im/status-react/blob/b16c224fd5602330e76db0952cdeb7a08e8f0ba4/src/status_im/contact/db.cljs#L31 this field should not be required, if it is, it will break compatibility as older version are not sending it (it was not present before), or alternatively the message should be validated without and a sensible default should be set if not there.

**Comment by bitsikka** [comment]
Ah I see, make sense(kind of) now

as a noob, got confused between `system-tags` and `partitioned-topc`

This is a bit beyond contextual knowledge I have gained so far

**Comment by churik** [comment]
@cammellos are you on it or I should ping @yenda?

**Comment by cammellos** [comment]
@churik i can take a look at it, but i won't have time this week for sure

**Comment by bitsikka** [comment]
@cammellos @churik I am taking another crack at it

**Comment by bitsikka** [comment]
@cammellos @churik when you have time please take a look

This PR takes care of contacts not syncing as in issue title only
