### ISSUE TITLE
Keyboard doesn't minimize properly on iOS

### ISSUE THREAD

**Issue by Shrinks99** [status-im/status-react#7926]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to minimize the keyboard by swiping down on the chat portion of the screen so that Status has the same keyboard UX as every other implementation on iOS.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarize the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When I am reading chat instead of just tapping on the chat portion of the screen (which is good, that works correctly) I would like to also be able to swipe down on the keyboard to hide it.

#### Expected behavior
The keyboard hides when I swipe down (see Messages or Facebook Messenger on iOS for reference implementation of expected behavior)

#### Actual behavior
The keyboard does not hide and instead continues to be visible with the chat still scrolling when a user's finger is over the keyboard.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Navigate to any chat
- Open the keyboard and then attempt to swipe downwards at the top of the keyboard in order to hide it

### Additional Information
* Status version: 1.2
* Operating System: iOS 13.4.1
* Hardware: iPhone XR

**Comment by cammellos** [comment]
This might be fixed, closing, reopen if necessary and thanks for reporting the issue.
