### ISSUE TITLE
Refactor: change text-field component name

### ISSUE THREAD

**Issue by GustavoNunes** [status-im/status-react#793]
We should change the `text-field` component to have a more semantic name, now its name is too similar to the `text-input` component (which it wraps). @alwx suggested `text-input-with-label`.

**Comment by tomby42** [comment]
@GustavoNunes I will look at it. Is there an agreement about the name `text-input-with-label` ?

**Comment by GustavoNunes** [comment]
thanks @tomby42! I think we can go with that

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/pull/979
