### ISSUE TITLE
Text for chat name for empty public chat is not centered if contains > 1 row

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7931]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when username contains > 2 rows, username is not centered.

#### Expected behavior
Username is centered

#### Actual behavior
*Android*
<img width="228" alt="dsfdsf" src="https://user-images.githubusercontent.com/4557972/55721139-dd417600-5a02-11e9-9c7e-3b388a91ef5b.png">
*IOS*
<img width="230" alt="fffff" src="https://user-images.githubusercontent.com/4557972/55721351-6f497e80-5a03-11e9-9b97-db139d052e02.png">

### Reproduction

- Open Status
- Start chat with any user with long 3 random username

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 08/04/2019
* Operating System: Android 8, iOS 11.4.1

**Comment by churik** [comment]
@errorists would appreciate if you can provide design feedback. Thanks!

**Comment by errorists** [comment]
thanks Chu for tagging me and easy, like you said it should be centred :)
