### ISSUE TITLE
joining public chat with messages throws error

### ISSUE THREAD

**Issue by bitsikka** [status-im/status-react#7933]
# Problem

When joining new busy public chat that is sure to have offline messages being fetched from mail-server(not empty after joining), following error is thrown:

```
console.error: "re-frame: no handler registered for effect:", {"ns":null,"name":"wallet-selected-asset","fqn":"wallet-selected-asset","_hash":-157625120,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096}, ". Ignoring."
error
    
_callTimer
    RefreshControl.js:178:8
callTimers
    StatusBar.js:320:6
__callFunction
    
<unknown>
    FS.common.js:276:13
__guard
    FS.common.js:481:6
callFunctionReturnFlushedQueue
    FS.common.js:275:11
```

# Implementation

A bug was introduced in #7454 whereby part of event handler behind event `:message/add` is returning db instead of cofx

fix by returning cofx

PR with fix coming up

**Comment by churik** [comment]
@bitsikka I didn't face this error when joining #status (which is most of the busy chats as I know).
Any clues how it can be reproducible and what it depends on (i.e. the number of messages, a message with some content, etc)?

**Comment by bitsikka** [comment]
@churik it should be any public chat with any number or kind of messages - or basically, it has to be not empty upon joining

Not sure why you are not getting the error but it may be due to few reasons
- I'm encountering the errors in development build where errors of this type manifests in UI
- It is possible I have perhaps slower connection than yours
- perhaps in your case the errors are in the log, but not shown on the UI

The reason I'm suspecting those may be the cause is because one of the logic behind #7454 fix is (in general) that, it checks if the sync with mailserver(or otherwise) completed *twice*:
- once when mailserver tells the client that request is completed(but messages may not have arrived yet)
- once again (for redundancy of when the messages actually arrive and added; and also to account for messages received via peers at join time(i.e. messages not from mailserver)

with those checks it transitions the app state to essentially *synced* which is then used to determine what state of intro screens to show.

error happens in the second(redundency) case, which if the connection is fast, could be skipped.

also incidentally the error for this resemble errors in log for #7917 - therefore the earlier confusion

**Comment by churik** [comment]
@bitsikka you are right, it is not shown in UI. Found this error in logs after joining chat.

**Comment by churik** [comment]
Checked on Android 8 (joining all type of chats, fetching messages from offline mode) and IOS 11.
No more `console.error` in logs.
One more thank you @bitsikka for noticing and fixing it.
Failed teats are not related to PR, so ready to merge.
