### ISSUE TITLE
Add extra space for the (+) button on the home screen

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#7941]
# Problem
Currently the (+) button covers the last item of the recent chats list

# Implementation
Let's add extra 64px to the bottom of the list (the same height as a list item)

![](https://user-images.githubusercontent.com/3115606/55799524-447e2980-5ada-11e9-85d2-5dd0cfc04b9c.png)

**Comment by annadanchenko** [comment]
@andmironov should it be mentioned as solution for https://github.com/status-im/status-react/issues/7859 and this one closed?

**Comment by andmironov** [comment]
@annadanchenko yes, thank you!

**Comment by annadanchenko** [comment]
can tap on + now, see #8166 for design of + button
