### ISSUE TITLE
Tap on "Fetch messages" leads to endless spinner if connection is lost during fetching

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7969]
### Description
_Type_: Bug
_Summary_: introduced in https://github.com/status-im/status-react/pull/7919 - decision was to fix it separately. "Fetch messages" still can lead to the endless spinner when the app goes offline-online during fetching. 

#### Expected behavior
messages fetched normally

#### Actual behavior
https://user-images.githubusercontent.com/4557972/55971883-9f528500-5c82-11e9-9bd6-b3e399175304.png

### Reproduction
**Prerequisites:** "Fetch messages" should be shown (app offline for > 24h)

* Open chat with "Fetch messages"
* tap on it
* go to offline 
* go back online

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 13/04/2019
* Operating System: Android, iOS

**Comment by bitsikka** [comment]
I may have some context on this one. Will take a look after I see about #7917
