### ISSUE TITLE
Beta alert is not shown after upgrading on IOS with enabled "Save password"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7970]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: issue in https://github.com/status-im/status-react/pull/7862 - decided to be fixed separately. So if on 0.11.0 you have "Save password until logout" enabled, after upgrade to current nightly you will not see beta alert (IOS only)

#### Expected behavior
beta alert is shown

#### Actual behavior
no beta alert

### Reproduction

- Install 0.11.0 release
- Create account
- Logout
- Enable  "Save password until logout"
- Upgrade to current nightly

### Additional Information

- Status version: nightly 12/04/2019
- Operating System: IOS

**Comment by annadanchenko** [comment]
@churik seems like it's fixed already (tried on ios upgrading from 0.12.1 -> 0.12.2), can you close if can't reproduce, please?

**Comment by churik** [comment]
Can't reproduce 0.12.2 -> nightly 22/04/2019
Thanks @annadanchenko !
