### ISSUE TITLE
window.web3 Undefined

### ISSUE THREAD

**Issue by RyRy79261** [status-im/status-react#7984]
### User Story

As a developer, I want to follow the [Status Documentation](https://dev.status.im/developer_tools/status_web_api.html) to connect to a dapp-

### Description
*Type*: Bug
*Summary*: window.web3 is undefined, the deprecated `ethereum.enable()`functions

#### Expected behavior

`web3` to be injected into the dapp browsers window variable to provide the dapp with `web3.currentProvider`

#### Actual behavior

`window.web3` is undefined

### Reproduction

1. Open Status
2. Switch to Rinkeby
3. Open local network React dapp
4. Attempt to retrieve `window.web3`

### Solution

Inject the `web3` object into the browsers window

**Comment by jeluard** [comment]
Can you clarify `window.web3 is undefined, the deprecated ethereum.enable()functions` ?
Not super clear what you are doing exactly.

The documentation you should follow is [here](https://status.im/developer_tools/access_eth_provider.html)
Note that you can [debug](https://dev.status.im/developer_tools/debug.html) remotely to get a better picture.

**Comment by jeluard** [comment]
Is this still relevant now that #7985 has been answered?

**Comment by flexsurfer** [comment]
@RyRy79261 I've changed our docs, because if privacy mode is enabled we don't provide web3 provider, but you always can get access to status api with `window.ethereum.status` object
changes in docs https://github.com/status-im/status.im/pull/273/files

**Comment by RyRy79261** [comment]
@flexsurfer Thanks! 

I've updated the init functions to detect status as initially we were using 'eth_requestAccounts' to unlock. Will add a flow in for Status :)

Detection code:

``` js
const { currentProvider: cp } = window.web3
const { ethereum } = window;
const isToshi = !!cp.isToshi
const isCipher = !!cp.isCipher
const isMetaMask = !!cp.isMetaMask
const isStatus = ethereum ? !!ethereum.isStatus: false;
```

**Comment by jeluard** [comment]
Closing as doc has been updated.
