### ISSUE TITLE
EIP 1102 compliance

### ISSUE THREAD

**Issue by RyRy79261** [status-im/status-react#7985]
### User Story

As a developer, I want to follow the standard specified in the [Status Documentation](https://dev.status.im/developer_tools/status_web_api.html) for requesting account access and connecting to the wallet.

### Description

*Type*: Bug

When running the EIP 1102 function for requesting account access `ethereum.send('eth_requestAccounts')` there is no permission request on Status

*Summary*:  Status does not appear to have the functions in place to execute this request

#### Expected behavior
The approval pop up to allow connection to the dapp would show up after the `ethereum.send('eth_requestAccounts')` is triggered

#### Actual behavior

Nothing happens on the browser post execution of `ethereum.send('eth_requestAccounts')`

### Reproduction

* Open up Status
* From JS or console, run `ethereum.send('eth_requestAccounts')`

### Solution

Update Status to comply with EIP 1102

**Comment by flexsurfer** [comment]
hey @RyRy79261 thanks for the issue, currently EIP still in progress, and you can find here current status implementation https://status.im/developer_tools/access_eth_provider.html , if you want to use latest EIP specification it's available under `ethereumBeta` provider

**Comment by RyRy79261** [comment]
Awesome, thanks @flexsurfer !
