### ISSUE TITLE
Can we add cross app communication api for other mobile app?

### ISSUE THREAD

**Issue by harryfei** [status-im/status-react#7987]
### User Story

As a mobile app creater, I want to use Status to sign ETH transactions so that I can write a native mobile dapp.

### Description

*Type*: Feature

*Summary*: 

Both iOS and Android have cross app communication mechanism. Can we implement some APIs for other mobile apps to leverage the ETH wallet.
The other app may want to:

* Use the ETH account address as account
* Sign blockchain transaction.

**Comment by cammellos** [comment]
Please add a feature request on https://discuss.status.im/ , thanks for your input!
