### ISSUE TITLE
Google Play release inaccurate marketing claim

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7988]
Did anyone notice the app release in Google Play says "Beta Features: Light Client - Status runs a full implementation of Go Ethereum, with the light client and Whisper protocols enabled"? This is just false right now, we don't have light client enabled. It's exactly the type of technical inaccuracy as marketing claim we had on our wall of shame before.

Noticed by going to get.status.im on Android => redirect to Google Play Store => see release notes from April 11

cc @mandrigin @annadanchenko @rachelhamlin

**Comment by annadanchenko** [comment]
updated description in PlayStore (for each of 10 translations) by deleting this claim. It says "Updates to your app usually become available on Google Play within a few hours, but may sometimes take longer."
<img width="1074" alt="Screen Shot 2019-04-17 at 12 01 15" src="https://user-images.githubusercontent.com/6584810/56279659-d0aad500-6108-11e9-88cd-9bf7abfc26fd.png">


Will re-check content shown in PlayStore description in 1 day (on April 18) to see if it fixes the issue.

**Comment by annadanchenko** [comment]
fixed. if open description in playstore there is no "Light Client - Status runs a full implementation of Go Ethereum, with the light client and Whisper protocols enabled"

![Screenshot_20190418-090137](https://user-images.githubusercontent.com/6584810/56342655-e2e44c00-61b8-11e9-8b04-851cda763cb1.png)

**Comment by annadanchenko** [comment]
For some reason, old text is shown again in PlayStore listing for 0.12.1 release

<img width="1558" alt="Screen Shot 2019-05-10 at 12 05 49" src="https://user-images.githubusercontent.com/6584810/57519643-13cd2200-731c-11e9-98b3-2e3eb6ffc06c.png">

**Comment by annadanchenko** [comment]
updating the description again by removing "Light Client - Status runs a full implementation of Go Ethereum, with the light client and Whisper protocols enabled"

Will monitor it for couple of days and contact customer support if it returns.

**Comment by annadanchenko** [comment]
Description is no updated. Contacted CS and it can take up to 2 business days to get an answer

**Comment by annadanchenko** [comment]
Full description should be changed in all full_description.txt files for each language in fastlane/metadata/android :

1. Remove first option with Light client claim in section Beta features
2. Update https://chat.status.im/ to https://get.status.im/chat/public/status

**Comment by Serhy** [comment]
@annadanchenko , @oskarth, I have a question:
We have full description for Android in several languages: de, en, fa, fr, ja, ko, pt, ru and zh. 
And we have several default public chats in 'Selected' list in app. Would it makes sense to use instead https://chat.status.im/ reference to the respective public channel (if no public channel in app - default to `status`)?
So it would be:

|  Full_description  |  Link to public  |
|  -------------  |  -------------  |
|  de-DE  |  https://get.status.im/chat/public/status  |
| en-US | https://get.status.im/chat/public/status |  
| fa | https://get.status.im/chat/public/status-farsi |
| fr-FR | https://get.status.im/chat/public/status |  
| ja-JP | https://get.status.im/chat/public/status-japanese |
| ko-KR | https://get.status.im/chat/public/status-korean |  
| pt-BR | https://get.status.im/chat/public/status |
| pt-PT | https://get.status.im/chat/public/status |  
| ru-RU | https://get.status.im/chat/public/status-russian |  
| zh-CN | https://get.status.im/chat/public/status-chinese |  

Or better to point everyone to  https://get.status.im/chat/public/status ?

**Comment by annadanchenko** [comment]
@j-zerah wdyt? point to status chat or specific "language" chat (like https://get.status.im/chat/public/status-russian)

**Comment by j-zerah** [comment]
Good question. I think including every language in the app description is not scalable as we grow and start to have communities all over the world. Also - it is better to join and see an active community and then find the specific channel you are looking for from there (as opposed to being dropped into a channel with nobody there). 

I think best to drive to 2 channels for now:

Introduce yourself to the growing community and connect with people all over the world:
#introductions [https://get.status.im/chat/public/introductions]

Join the general public channel #status for updates, news, and discussion about all things Status
[https://get.status.im/chat/public/status]

**Comment by Serhy** [comment]
Thanks @j-zerah. The single reference to #status public will be used for all languages as an update in the scope of this issue

There is a separate issue will be created to get all translations for the 

```
Introduce yourself to the growing community and connect with people all over the world:
#introductions [https://get.status.im/chat/public/introductions]

Join the general public channel #status for updates, news, and discussion about all things Status
[https://get.status.im/chat/public/status]
```
