### ISSUE TITLE
"Can't find web3 library" at attempt to open simpledapp.eth from DApps list

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7989]
### Description
_Type_: Bug

_Summary_: issue is reproducible if try to open DApp `simpledapp.eth` from DApps list - not always from first attempt, but if you try to repeat it twice - three times, it is reproducible.

#### Expected behavior
simpledapp.eth is opened normally

#### Actual behavior
![2019-04-17 11 01 26](https://user-images.githubusercontent.com/4557972/56274999-2af36800-6100-11e9-93cf-d82bbe048d2b.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Switch to Ropsten
* Open DApps
* Try to access Status Test DApp (retry if no error)

### Additional Information

* Status version: nightly 17/04/19
* Operating System: Android
On IOS sometimes it leads to "Unable to load page", but I didn't see "Can't find web3 library".

#### Logs
[logcatTestDapp.log](https://github.com/status-im/status-react/files/3088734/logcatTestDapp.log)
From debug tools:
`web3 nil`

```
cljs.core.enable_console_print_BANG_=function cljs$core$enable_console_print_BANG_(){cljs.core._STAR_print_newline_STAR_=false;cljs.core.set_print_fn_BANG_(function(){var G__1986__delegate=function(args){return console.log.apply(console,cljs.core.into_array.cljs$core$IFn$_invoke$arity$1(args))};var G__1986=function(var_args){var args=null;if(arguments.length>0){var G__1987__i=0,G__1987__a=new Array(arguments.length-0);while(G__1987__i<G__1987__a.length){G__1987__a[G__1987__i]=arguments[G__1987__i+
```

![2019-04-17 11 08 02](https://user-images.githubusercontent.com/4557972/56275477-1a8fbd00-6101-11e9-8c96-5c5938cb5bce.jpg)

**Comment by jeluard** [comment]
@flexsurfer Have you seen that?

**Comment by flexsurfer** [comment]
can't reproduce

**Comment by asemiankevich** [comment]
> can't reproduce

issue is reproducible on android for me this way:

1. open status
2. switch to ropsten
3. open simple dapp (probably will load normally)
4. go back to dapps list and open simple dapp from the list (not from the shortcut) again
5. repeat step 4

basically i am able to repro it without step 5, so second attempt is not successful

**Comment by asemiankevich** [comment]
can't reproduce anymore, issue is fixed
