### ISSUE TITLE
Endless loading indicator on Dapp view after opening universal link from within Dapp

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7996]
***Type*:** Bug

**_Summary_**: When universal link (to public chat/contact profile) is opened from Dapp (or webpage) user is redirected to respective view (public chat view / user profile view) as expected. However, navigating back to Dapp screen - at the same time we load the universal link page (with 'Open in Status' button) which has several consequences: 
1) There is endless blue loading indicator on Dapp view
2) URL of the Universal link is not disaplayes in URL bar 
3) `<` back browser button is not active, - so no way to navigate back to previous screen
4) In the case universal link is for public chat -> tapping `Open in Status` button redirect user to public chat (again) and there is endless loading spinner on public chat (_update:_ this part is #7952). Dapp screen will display now 'Unable to load page'

To eliminate all above, no need to open universal link webpage in a case when univeral link requested from withing Dapp. Please see steps to reproduce 

#### Expected behavior
When user opens universal link to public chat or user profile in webpage/Dapp redirect to respective view happens and **no** https://get.status.im webpage is opened on Dapp screen
(should be the same behavior as if to paste-and-go universal link in Dapp view)

### Actual behavior
Opening universal link from DappStore opens `https://get.status.im/...` webpage and there are consequences with it described above
Video: https://drive.google.com/file/d/1z4F-Eb4YXKIGCmCtxUlMPxOLV9e4LJas/view

### Reproduction 1

* Open Status and create new account
* Navigate to Dapp tab -> open https://dap.ps webpage
* Scroll to the bottom and tap any of `Join the DApp community chat` / `Support` elements
* Navigate back to Dapp view

### Reproduction 2

* Open Status and create new account
* Navigate to Dapp tab -> open `https://people-ops.status.im/status-channels/` webpage
* Tap any item from the list of public chats
* Navigate back to Dapp view

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: Develop `20190418`
* Operating System: Android and iOS

**Comment by bitsikka** [comment]
> 4\. In the case universal link is for public chat -> tapping `Open in Status` button redirect user to public chat (again) and there is endless loading spinner on public chat.

this part sounds like related to #7952 and if it is, as proposed in 7952, merging #7820 would fix it

**Comment by Serhy** [comment]
> > 4. In the case universal link is for public chat -> tapping `Open in Status` button redirect user to public chat (again) and there is endless loading spinner on public chat.
> 
> this part sounds like related to #7952 and as proposed in it merging #7820 would fix it

Yes, thanks @bitsikka that's correct. There is a second public chat join activity happens, so it's #7952

**Comment by churik** [comment]
should be retested after fix for  https://github.com/status-im/status-react/issues/10083

**Comment by churik** [comment]
still relevant on release 1.4

**Comment by hesterbruikman** [comment]
Closing as I can no longer reproduce the issue (cc @Serhy @churik)
