### ISSUE TITLE
Global distribution method for apk & internal auto update

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#800]
Google Play / App Stores are centralised point of failure, we should encourage an install and upgrading path outside of google play, based on the blockchain.

Can be on Swarm for existing clients or globally accessible via CDN

Needs hash checkpointing

**Comment by TheHealthyCat** [comment]
Maybe something like what Parity is using since v1.5 (Nativity)?
[https://github.com/ethcore/parity/releases](url)
