### ISSUE TITLE
Different timestamps

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#8002]
# Problem

The status client currently has 2 different timestamps for specific messages, in the message overview it displays when a message was received (when I last opened status) whereas in the chat it displays when the message was actually sent.

It probably makes more sense to display both as when the message was actually sent.

**Overview**
![IMG_6779](https://user-images.githubusercontent.com/7621705/56373927-51013100-6202-11e9-89a9-f38a63d96266.jpg)

**Chat**
![IMG_6780](https://user-images.githubusercontent.com/7621705/56373933-5494b800-6202-11e9-90f8-150f2da23144.jpg)

**Comment by churik** [comment]
@decanus 
thanks for reporting!
This issue is already reported in https://github.com/status-im/status-react/issues/7270
