### ISSUE TITLE
TouchID Feature Request

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#8007]
### Description

Instead of having to enter my password manually on my iPhone or Mac, I would like to be able to use TouchID when this technology is available. There is already a TouchID library which may make this implementation easier:
 - https://github.com/naoufal/react-native-touch-id

This could also be useful for signing transactions etc.

**Comment by oskarth** [comment]
@mandrigin @StatusSceptre wdyt about a bounty for this one?

**Comment by tbenr** [comment]
Is this related to #6573 ?

**Comment by oskarth** [comment]
Indeed, seems like a dup. Searching for touch ID didn't show that issue, so I added Touch ID to that issue's title. GH still hasn't indexed it though https://github.com/status-im/status-react/search?q=touchid&type=Issues

Can probably close this one?
