### ISSUE TITLE
App crashes when depositing ETH to a DApp.

### ISSUE THREAD

**Issue by Smokyish** [status-im/status-react#801]
Whenever i try to make a deposit in a DApp = Gnosis, Maker Market, after entering the amount when pressing Confirm/Deposit, the app crashes.

This is on version 0.9.2-95-g4c34404+.

**Comment by jarradh** [comment]
can you provide clearer step by step instructions please? what do you mean by deposit?

**Comment by Smokyish** [comment]
- Login
- Open Gnosis in Chats
- Click "I confirm the terms and conditions"
(- this would likely be another issue -> wait, the Market list doesn't load, nothing happens [have waited 15+ mins on an occasion], press back on phone, back to Chats, re-open Gnosis, Market list loads)
- Open menu/drawer, click Account, close drawer by pressing menu button again
- Click Deposit ether
- Enter 1
- Click Confirm -> crash

- Login
(- Open Wallet in Chats)
- Open Maker Market in Chats
(- same issue with loading, need to go back and sometimes even manually enter https://mkr.market/ )
- Click Deposit/Withdraw
- Click on input field under Deposit
- Enter 1
- Click Deposit -> crash

**Comment by annadanchenko** [comment]
@Smokyish on 0.9.6 version the first scenario (Gnosis) is working fine with no crashes, can deposit ether. Second one (Maker) I can't check as Wrap/Unwrap options are not active atm. Can you confirm that it works for you and if yes then close this issue?

**Comment by Smokyish** [comment]
@annadanchenko Verified that both Gnosis and Maker deposits work, closing the issue.
