### ISSUE TITLE
$100 equivalent Cold Storage Notification

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#802]
We should encourage behaviours to treat Status just like you would carry around your wallet. It's rare people carry 1000's of dollars in their wallet on a daily basis. 

So once we reach some arbitrary limit we should encourage the user to setup "auto transactions" to a cold storage wallet setup else.

**Comment by knocte** [comment]
> to a cold storage wallet setup else

I'm curious, does Status.IM support cold storage mode (work offline without internet) or you mean pair with another wallet?
