### ISSUE TITLE
Contacts that added after initial sync on 0.12.0 are shown in contact list on release 0.11.0, but in fact are not added as contacts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8030]
### Description
*Type*: Bug
*Summary*: guess leftover from https://github.com/status-im/status-react/issues/7917.
If device from current nightly and 0.11.0 are synced and user add contact on current nightly - it will appear in Contact List on 0.11.0, but if you open user profile - it is not added as a contact.

#### Expected behavior
contact A is added as a contact on `device B`

#### Actual behavior
contact A appeared in the contact list, but he is not added as a contact
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4557972/56668902-99ac6480-66b0-11e9-9490-00f17b43ece0.gif)

### Reproduction

- Pair `device A` with current nightly and `device B` with 0.11.0
- sync all devices
- add contact A on `device A`
- check contact list on `device B`
- tap on contact A to check his profile

### Additional Information

- Status version: 0.11.0 <- latest nightly
- Operating System: Android, iOS

**Comment by annadanchenko** [comment]
@cammellos @churik added it to release blockers because users do not update desktop so often (so will keep 0.11.0 version or lower) but will update mobile, so for most of them such issue will occur.
