### ISSUE TITLE
Redirect to Chats main view happens after QR code scan on 'Add bootnode' or 'Add mailserver' screen  

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8044]
***Type***: Bug

***Summary***: There is the same bug when contact scans QR code on the `Add bootnode` and `Add mailserver` screens: contact redirected from `Add bootnode` / `Add mailserver` screens. 

On iOS its redirect to blank screen. 
On Android there is a redirect to Chats/Dapps/Wallet/Profile screens (it depends, apparently, which tab was active prior navigation)

It's noticeable (on Android) that QR code value has read and inserted in editbox, - but then it always follows by redirect

#### Expected behavior
Contact keep staying on the same screen after QR code got scanned at 'Add bootnode' / 'Add mailserver' screens

#### Actual behavior
Contact redirected from respective screen after QR code got scanned at 'Add bootnode' / 'Add mailserver' screens

![1111](https://user-images.githubusercontent.com/8749671/56754955-f6824a80-6796-11e9-86f5-6c2c1407a631.gif)

### Reproduction 1

- Open Status and create new account
- `Profile` -> `Bootnodes` ->`+` -> tap `Scan QR code` -> scan valid QR code

### Reproduction 2

- Open Status and create new account
- `Profile` -> `Mailserver` ->`+` -> tap `Scan QR code` -> scan valid QR code

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: Develop, Release 0.12.0
- Operating System: Android and iOS

**Comment by rachelhamlin** [comment]
@jeluard do you mind taking a look at it while we firm up designs for onboarding?

**Comment by jeluard** [comment]
@rachelhamlin Sure!

**Comment by jeluard** [comment]
@Serhy Please give #8044 a try. It will help us pinpoint the issue.

**Comment by Serhy** [comment]
> @Serhy Please give #8044 a try. It will help us pinpoint the issue.

https://github.com/status-im/status-react/pull/8048 -> fixes current #8044 and #7995 issue
