### ISSUE TITLE
TypeError (evaluating 'a.replace') when logging out with wallet is on  'Send transaction' screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8051]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: when user logs out with "Send transaction" screen on Wallet tab - app is crashed.

#### Expected behavior
logged out normally

#### Actual behavior
![photo!UNITO-UNDERSCORE!2019-04-26 12 48 05](https://user-images.githubusercontent.com/4557972/56802945-af8d6700-6821-11e9-97cc-276882279cda.jpeg)

### Reproduction

* Open Status
* Open "Send transaction" screen
* go to profile
* log out

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: release 0.12.0
* Operating System: Android
#### Logs

[logx2.log](https://github.com/status-im/status-react/files/3120942/logx2.log)

**Comment by asemiankevich** [comment]
@dmitryn could be a regression of recent keycard merges?
