### ISSUE TITLE
[TTT] copy for disabled contract

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8056]
# Problem

There is no screen in Figma for what it should look like to the user once TTT is disabled because the contract has been stoped:

We need:
- a warning that is shown to the user explaining that he needs to update status to keep using the feature (can be just a popup with some text)
- either remove the tribute to talk action from profile menu (my prefered option) or show it in red or something
- if the user opens a chat with a contact that has ttt set it should warn him that he may not receive his messages

**Comment by errorists** [comment]
@yenda I'm a bit out of the context, this all is for a person who had TtT running but the contract was somehow stopped right? so to make sure I get it: 
• updating Status will once again make the feature active?
• unless updated, In his own profile he won't be able to access any of the Tribute to Talk settings
• if he opens a chat with a paywalled contact for whom he previously paid, he should be informed that messages might (also, are we sure or it's a guess) not arrive.

**Comment by yenda** [comment]
> • updating Status will once again make the feature active?

This one should be feasible yes
@3esmit could you confirm?

> • unless updated, In his own profile he won't be able to access any of the Tribute to Talk settings

yes the feature should basically disappear from the settings or be shown as permanently disabled (until update)

> • if he opens a chat with a paywalled contact for whom he previously paid, he should be informed that messages might (also, are we sure or it's a guess) not arrive.

no only for a new contact that is paywalled

**Comment by 3esmit** [comment]
If the contract was stopped it means it cannot change the settings in the contract until the contract is enabled again or a new contract address is defined at client. 
In case of disabled contract, the behavior could be: 
1. Disable TTT
2. Use last defined setting
3. Use a default value

**Comment by errorists** [comment]
thanks! my take on it, 
For points 1 and 2, we show the TtT menu in profile with a red warning and label to update Status and a '!' character in the profile tab badge -> [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4675%3A147)

For paywalled contacts, point 3, if we're not sure if the sent messages arrive I'd rather disable and hide the input altogether there and block sending messages -> [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4671%3A6)

obvs, if any of that is too much work and we want to wrap up TtT I can write up text for a popup re:point 1, and hide the TtT menu completely in point 2, lmk.

**Comment by yenda** [comment]
So current proposal is that when contract is stopped on old client we should:
- block input when not whitelisted? by contact
- show red warning and label on tribute to talk settings (cf figma https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4671%3A6)

@errorists the problem with your figma design for the chat is that you assume we can know that tribute to talk is enabled, the thing is that when the contract is stopped, meaning tribute to talk works in a way that doesn't work with the contract anymore, we can't know so basically we have to show this screen for any of your contacts that has not whitelisted you (meaning you paid or he paid tribute in the past, or that he sent you a contact request).
