### ISSUE TITLE
[ENS Names] Use ens username in chat

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8067]
Implement ens username settings and show ens names in chats

![image](https://user-images.githubusercontent.com/11790366/56898694-fda8a180-6a91-11e9-96f4-82334ba9bfb3.png)

![image](https://user-images.githubusercontent.com/11790366/56898966-9b03d580-6a92-11e9-8fe9-5b43fb7b49ff.png)

crossed element not in the scope of this PR

Acceptance criteria:

1) pixel perfect
2) it should be possible to select a primary username
3) it should be possible to enable "use my ENS name in chats"
4) ens name must be verified and shown in chats for messages which contains ens name

Figma: https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A3116

**Comment by jeluard** [comment]
Heuristic to display name:

- defaults to funky animal names
- ENS name overrides funky name
- Nickname, if set, is displayed in addition

**Comment by jeluard** [comment]
Having ENS name resolution go side makes sense as most of the chat protocol handling and persistency will be migrated there soon. There might be a performance boost too but probably marginal.
After discussing with @adambabik and @cammellos it appears that this work will happen no sooner than end of month. To validate assumptions and have an early prototype I will go ahead with the Clojure implementation (unless it becomes apparent the work is significant).
