### ISSUE TITLE
Auto assign reviews to Core

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#8074]
## Problem
Often PRs don't get picked up by core contributors, and they take a long time to get reviewed. This is especially a problem for non core contributors.

## Context

Aside from https://github.com/status-im/status-react/blob/develop/doc/decisions/0011-tweak-pr-process.md, which mostly helps core contributors who know who to ask, I also set up two teams: #status-core and #status-core-ui. This means you can ask these teams for review if you don't know who in particular should review a PR. It also means you can see outstanding PRs and who is responsible for them, e.g. here:

`state:open type:pr team-review-requested:status-im/status-core`

https://github.com/status-im/status-react/search?q=state%3Aopen+type%3Apr+team-review-requested%3Astatus-im%2Fstatus-core&type=Issues

We see 11 reviews that are requested from Core. For Core UI we see 13

https://github.com/status-im/status-react/search?q=state%3Aopen+type%3Apr+team-review-requested%3Astatus-im%2Fstatus-core-ui&unscoped_q=state%3Aopen+type%3Apr+team-review-requested%3Astatus-im%2Fstatus-core-ui&type=Issues

(You can also do similar search queries for individuals)

## Solution

The above helps somewhat, since it ensures there's a fallback swarm/team for each PR. Core by default, Core UI if it concerns UI.

However, for non core contributors they don't know who to request review from (and might not have permissions). Therefor, it'd be useful to auto request review from Status Core team. IF it needs to be delegated further to Core UI or individuals that's something Core can do.

@PombeirP is this doable with Probot?

FYI @mandrigin @rachelhamlin @flexsurfer re new GH teams

**Comment by oskarth** [comment]
Also fyi @annadanchenko

**Comment by pedropombeiro** [comment]
@oskarth can you please clarify the part which you'd like to automate with Probot? Is it the automatic assignment to `#status-core` for PRs from external contributors?

**Comment by oskarth** [comment]
@PombeirP To keep it simple, I'd say auto assign all PRs to status-core. Unless it's very straight forward to filter on non CCs

**Comment by pedropombeiro** [comment]
Auto-assigning to status-core would be straightforward, not sure how much work would be to filter on non-CCs.

**Comment by pedropombeiro** [comment]
This existing Probot app could be interesting: https://github.com/kentaro-m/auto-assign

**Comment by oskarth** [comment]
@PombeirP any update on this? Or how it fits into prios

**Comment by pedropombeiro** [comment]
I'll need to put aside some time to work on this. I've been deep into reproducible builds and haven't looked into this yet.
