### ISSUE TITLE
Some dapps don't work in status when privacy mode is enabled

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8082]
# Problem

Some dapps don't support EIP 1193, and they just don't work in status when privacy mode is enabled

## Future Steps

Find out how we could inform users about this

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/57016968-404ab500-6c1d-11e9-9092-2ce47dc0e193.png)

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/57019895-0a5efe00-6c28-11e9-976a-5ab102eb3e91.png)

**Comment by hesterbruikman** [comment]
Can't pinpoint why, but it took me a while to process.

@errorists have you considered radiobuttons?

- Allow all DApps Wallet access
- Ask for permission _(some DApps might not work)_

**Comment by errorists** [comment]
@hesterbruikman that's good, why isn't it designed like this at the settings level ? :)

**Comment by hesterbruikman** [comment]
> 
> 
> @hesterbruikman that's good, why isn't it designed like this at the settings level ? :)

Good call... I'll at a link to this issue to align when we move focus back to Settings.
