### ISSUE TITLE
Add 'Drafts' to the Chat Tab

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#8087]
# Problem

Currently whenever we compose a message and instead of sending it we go back to chats tab, we correctly save whatever we wrote in this chat as a draft. However it's not indicated in the Chats tab, making this actually cool feature go unnoticed and impossible to keep track of.

## Implementation

For each chat with a drafted message, we show a text label in list item preview, simply saying it's a pending Draft, followed by whatever was typed inside the chat text input, like so

<img width="375" alt="Cell" src="https://user-images.githubusercontent.com/4932774/57008342-b0dadd00-6bef-11e9-8e71-829f3641c48e.png">

The text label uses the same text attributes with a different, Accent Blue, colour. It persists as long as the draft is composed until the input is either cleared or message sent.

Figma -> [Drafts](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=2340%3A2)

## Acceptance Criteria

Implemented according to design and tested.

## Notes

Thank you 🙏  if you need help to visualise it, Telegram does something similar

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
