### ISSUE TITLE
[TTT] Design copy for TTT not available on current network

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8090]
# Problem

Currently TTT is only available on mainnet, the TTT setting should reflect that on other networks by either not showing up or showing a warning

**Comment by errorists** [comment]
Let's show it disabled with a message like so 

<img width="375" alt="Double" src="https://user-images.githubusercontent.com/4932774/57013808-8730ae80-6c0d-11e9-950d-28c35d56297d.png">

https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4706%3A0

also @yenda if I'm on testnet and hit a paywall myself, I assume we need to communicate it too right?

**Comment by yenda** [comment]
What do you mean I don't understand the question

**Comment by errorists** [comment]
in the instance of a user not being on mainnet, if he would encounter a new contact with TtT enabled, would he be able to interact and pay the tribute?

**Comment by yenda** [comment]
Ttt is per network, so if let's say I'm on mainnet and you are on ropsten,
I have no way to know if you have ttt enabled. That's why swarm feeds will
be much better and reliable.

**Comment by yenda** [comment]
https://github.com/status-im/status-react/issues/8090#issuecomment-488253204 has been implemented in current ttt-flow draft
