### ISSUE TITLE
[TTT] No limit for number of chars in manifest

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8102]
# Problem

A user could set a very large number of characters in his message or a very high snt-amount. Both could cause all sorts of performances issues and even crashes with extreme numbers.

I propose a silent 2k char limit for the message and 100 digits for the snt-amount

@rachelhamlin @errorists 

# Implementation

- fetching: before doing anything with the manifest file, count the number of chars and return nil if it is too long, then in valid? function check 2k char for message and 100 for snt-amount
- setting: if silent then just check if manifest is valid and show generic error after edit screens, otherwise if there is a copy for that maybe a popup when reaching limit?

**Comment by rachelhamlin** [comment]
I'm on board. But not a release blocker.

**Comment by errorists** [comment]
I'm ok with the welcome message being capped at a reasonable 280 chars and something much smaller for SNT, like 6 digits. We can have twitter style char counters if it helps, but agree, I'm more inclined to ship it and apply lessons learned than getting it perfect on release.
