### ISSUE TITLE
No labels for icons are shown on Group Info screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8105]
### Description
_Type_: Bug
_Summary_: no icons are displayed on "Group Info" screen for group chats

#### Expected behavior
Can see labels for options

#### Actual behavior
![Screenshot!UNITO-UNDERSCORE!2019-05-02-10-14-45](https://user-images.githubusercontent.com/4557972/57063393-60cd4a80-6cc3-11e9-9646-4b03b3e60e68.png)

### Reproduction

* Open Status
* Create account
* Add contact
* Create group chat
* Open three dots > Group info

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 02/05/2019
* Operating System: Android, IOS

**Comment by churik** [comment]
@yenda I believe it is regression from TtT Pr, can you please take a look?

**Comment by yenda** [comment]
I'm off until Tuesday I assigned @siphiuel
