### ISSUE TITLE
Wallet balance is not updated when transaction is received

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8107]
### Description
_Type_: Bug
_Summary_: in current nightly when the transaction is received - wallet balance is not updated after switching to another tab and going back until login / logout. Cause failure of e2e test [test_backup_recovery_phrase_warning_from_wallet](https://ethstatus.testrail.net/index.php?/tests/view/611459)
Introduced by https://github.com/status-im/status-react/pull/8050.

#### Expected behavior
wallet balance is updated 

#### Actual behavior
wallet balance is not updated 

### Reproduction

* Open Status
* Create account, change network to Ropsten
* Send from another device some ETHro (i.e. 0.01 ETHro)
* wait until transaction is confirmed
* switch on "Home"
* switch back to balance to update it

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 02/05/2019
* Operating System: Android, IOS

#### Logs
[Status-debug-logs (2).zip](https://github.com/status-im/status-react/files/3137783/Status-debug-logs.2.zip)

**Comment by churik** [comment]
@flexsurfer please, take a look when you have a time

**Comment by flexsurfer** [comment]
@churik are you sure steps are correct? we never had an auto-update for balance

**Comment by churik** [comment]
@flexsurfer Yeah, steps are not exact, you are right.
I updated steps.
But anyway I think that we should add an issue that assets are not updated automatically or even on pull-to-refresh, it will be separate issue.
