### ISSUE TITLE
Wrong value in QR code of nightly .apk and diawi links on https://status.im/nightly

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8117]
**_Type_**: Bug

**_Summary_**: There is a correct and relevant links to nightly build on status.im/nightly page for buttons `iOS App` and `Android App`, but QR codes below store links to the old nightly builds (~1 month old nightly)

Apparently, issue in https://ci.status.im/job/misc/job/status.im job where we generate QR code.

#### Expected behavior
QR code for nightly Mobile links stores the same value as URL to nightly build.

#### Actual behavior
QR code for nightly Mobile links stores the different value than URL to nightly build. 

![](https://user-images.githubusercontent.com/8749671/57126394-83c82f00-6d95-11e9-8eca-bf276be9dae3.png)

### Reproduction

* Open https://status.im/nightly/ and scan nightly build QR code

**Comment by jakubgs** [comment]
Issues about our website should be reported to the site repo: https://github.com/status-im/status.im

I'll take a look at this today.

**Comment by jakubgs** [comment]
Fix: https://github.com/status-im/status.im/pull/317

**Comment by jakubgs** [comment]
https://dev.status.im/stable/ - looks fixed to me.

**Comment by jakubgs** [comment]
Pushed to master.
