### ISSUE TITLE
Generate address for default contacts (if possible)

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#812]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently we are generating an address from a public key for all new contacts, but this functionality is missed for default contacts.

#### Expected behavior
A user should be able to send eth to a non-dapp default contact (like Jarrad).

#### Actual behavior
A user sees validation error when is trying to send eth to Jarrad.
![pasted image at 2017_02_16 16_38](https://cloud.githubusercontent.com/assets/2364994/23023662/485ac20e-f45f-11e6-936e-62f7a93610c2.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open chat with Jarrad
- Send `/send` command

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: `develop`

**Comment by jarradh** [comment]
Isn't this related to #752

**Comment by rasom** [comment]
It is related and it works when you are adding a new contact. But this functionality was missed for default contacts.
