### ISSUE TITLE
[Onboarding] Get started screens

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8131]
![image](https://user-images.githubusercontent.com/11790366/57216771-1c0e2000-6ff1-11e9-87ad-c5b0f48fb6f8.png)

**Recovery is not in the scope of this PR**

Acceptance criteria:

1. pixel perfect
1. it's possible to swipe pictures
1. pictures is autoswiped?

Figma: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

**Comment by flexsurfer** [comment]
@andmironov could you provide more details on pictures behaviour?

**Comment by StatusWrike** [comment]
➤ Rachel Hamlin commented:

Should also be able to close this one this week.
