### ISSUE TITLE
[Onboarding] Select storage and save with password

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8134]
![image](https://user-images.githubusercontent.com/11790366/57217928-41e8f400-6ff4-11e9-8cbf-da0b98c566d2.png)

**Keycard is not in the scope of this PR**

Acceptance criteria:

1. pixel perfect
1. it's possible to select device storage
1. store with password

Figma: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

**Comment by rachelhamlin** [comment]
Hey @siphiuel! Is this issue being addressed in [#8234](https://github.com/status-im/status-react/pull/8234) or is it a separate PR?

**Comment by flexsurfer** [comment]
@rachelhamlin storage selection and save with password were done in #8234 , i'll create separate issue for the pincode
