### ISSUE TITLE
Wallet address validation error when scanning contact code with 2 cameras opened on 2 tabs

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8138]
# Problem

Wallet address validation error is shown in case user has opened cameras on 2 tabs and trying to scan valid contact code

![image](https://user-images.githubusercontent.com/28752642/57229035-d87ddb00-701d-11e9-9779-f84241fb03ce.png)

# Steps

1. open status
2. open wallet - bypass onboarding - send - scan qr
3. tap chat tab -> plus button -> add contact -> scan code
4. scan valid contact code

# Note

if user switches to wallet tab - it is shown that contact code was scanned there. Seems the scanning content is being mixed up when having 2 cameras opened

**Comment by annadanchenko** [comment]
should be solved after #8139 is solved by making QR scan window modal)
