### ISSUE TITLE
Rework Pair code to avoid characters that could be mistyped

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8145]
# Problem
Pairing code could contain capital [L] and lower case [i] which look identical to the user therefore pairing code could be hard to guess.

![image](https://user-images.githubusercontent.com/28752642/57301523-ee54d400-70e1-11e9-8b69-a279b56fc8e0.png)

## Steps

1. open status
1. tap create new account
1. select keycard
1. hold the card until app generates your keys

## Details
Some doc here : https://status.im/keycard_api/apdu_init.html

https://stackoverflow.com/questions/55556/characters-to-avoid-in-automatically-generated-passwords could be helpful

## Notes
@guylouis @hesterbruikman i feel like this could be a bad user experience since user will think that our app is not working

@andmironov maybe you know other symbols which could be confusing and should be excluded due this reason ? Thanks!

**Comment by guylouis** [comment]
@dmitryn since he's the one generating the pairing code

**Comment by bitgamma** [comment]
just a note: we can chose to restrict the character set for the password when **generating** it without problems. We can even restrict it to number. However for compatibility with other wallets, which might use arbitrary alphanumeric passwords, we should still allow the user to enter any password when **pairing**

**Comment by dmitryn** [comment]
I'm going to use this set of characters to generate pairing code
`!#%+23456789:=?@ABCDEFGHJKLMNPRSTUVWXYZabcdefghijkmnopqrstuvwxyz`
taken from here https://www.grc.com/ppp.htm
(there is no small 'L' and capital 'i')

**Comment by dmitryn** [comment]
@bitgamma @gravityblast does this char set look secure? This is how it's implemented https://github.com/status-im/react-native-status-keycard/blob/generate-pairing-code-from-chars/android/src/main/java/im/status/ethereum/keycard/SmartCardSecrets.java#L70

I'm also thinking about excluding some of special symbols (like `=` and `:`) as it might look unusual from UX perspective having them in password /cc @andmironov @hesterbruikman

**Comment by bitgamma** [comment]
@dmitryn looks fine to me, the security requirements for pairing code are not too high so it would be fine even to exclude punctuation.
