### ISSUE TITLE
Improve pairing code UX for incorrect attempts

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8147]
# Problem

If wrong pairing code is entered , user is not able to proceed after [Next] button is hit, however the input field is not cleared and red tooltip remains for next attempts which might make user think that next attempts are not being processed by system.

NOTE: if i remove the card and tap it again - field is cleared.

![image](https://user-images.githubusercontent.com/28752642/57310382-65926400-70f2-11e9-9954-87352814a62f.png)

## Steps

1. open status
2. i have an account -> keycard
3. pair the device
4. enter wrong pairing code and do not remove the card
5. tap next one more time with the same wrong code

Actual result: UI says nothing that second attempt is done , looks like user is stuck

![image](https://user-images.githubusercontent.com/28752642/57310788-1698fe80-70f3-11e9-8e05-146e3c1d4255.png)

@hesterbruikman could you suggest something here?

**Comment by andmironov** [comment]
Closing for now, will address later in UX issues for Keycard settings
