### ISSUE TITLE
EIP681 `value`, `chain_id`, `gasLimit` and `gasPrice` are not supported

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8150]
### Description

*Type*: Bug
*Summary*: Some of the parameters mentioned in [EIP681 spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) are not supported in Status app.

1)  Links without `function_name` are not resolved, i.e. `ethereum:0xfb6916095ca1df60bb79Ce92ce3ea74c37c5d359?value=2.014e18` so when scanning URL with this link, got an error 
<img width="225" alt="Monosnap 2019-05-01 11-19-13" src="https://user-images.githubusercontent.com/4557972/57011643-f94fc600-6c02-11e9-8033-5888608b0d09.png">
So I didn't find a way to check `value` for ETH

2) If using ERC20 tokens as parameters, value is not resolved, i.e. after scanning `ethereum:0x744d70fdbe2ba4cf95131626614a1763df805b9e/transfer?address=0x8e23ee67d1332ad560396262c48ffbb01f93d052&uint256=1` should sent 1 SNT as far as I understand.
In fact after scanning QR with link I've got:
![photo_2019-05-01 11 27 14](https://user-images.githubusercontent.com/4557972/57011896-18028c80-6c04-11e9-9296-8e36742f7758.jpeg)

So the asset was changed to tokens, but the value is not displayed.

3) Parameters `gasLimit` and `gasPrice` are not resolved (i.e. in `ethereum:0x744d70fdbe2ba4cf95131626614a1763df805b9e/transfer?address=0x8e23ee67d1332ad560396262c48ffbb01f93d052&value=1&gasLimit=100&gasPrice=1`
However `gas` is resolved, as it mentioned in [spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md)

4) `chain_id` is not resolved
atattempt to scan `ethereum:0x9810fc231ca9dabe30da595763a7b81a215aaceb/transfer?chain_id=3&address=0x8e23ee67d1332ad560396262c48ffbb01f93d052&value=1` on Ropsten got an error:

#### Expected behavior
all paramters are pasted on "Send transaction" screen

#### Actual behavior
mentioned in description

### Reproduction

- Make valid links according to  [EIP681 spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md)
- Make a QR with any QR code genarator
- Open Status
- Tap on + > Scan QR

- Status version: nightly 08/05/2019
[comment]: # (Android or iOS.)
- Operating System: Android, iOS

**Comment by rachelhamlin** [comment]
Relabeling this `feature` because it's about completing the implementation of EIP681, not a problem with the portion we have complete.

**Comment by churik** [comment]
`value` is still not supported
