### ISSUE TITLE
Persist wallet transactions

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8152]
# Problem

Every time users logs in, transactions are fetched again. 

## Implementation

- the transactions should be persisted in realm
- remember oldest checked block and query whole history iteratively over time
- remember latest checked block to only query from there

## Acceptance Criteria

- token transactions older than 2 weeks are visible in transaction history
- history is only fetched for the blocks that were created since last login

**Comment by yenda** [comment]
Currently being worked on go side by @dmitryn 
status-react side implementation once this is done shouldn't take more than a couple day

**Comment by flexsurfer** [comment]
@yenda could you give an update for this issue please?

**Comment by yenda** [comment]
@flexsurfer yes it is solved in status-go so it will be solved in with my pending PR on wallet api integration

**Comment by flexsurfer** [comment]
great thanks!
