### ISSUE TITLE
[Wallet] Ensure failed token transactions are shown as such

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8153]
# Problem

Token transactions can fail when the user doesn't have enough tokens at the moment the transaction is included in the chain. This isn't shown properly especially in the transaction received messages in chat

## Implementation

- if a transaction has 0 eth and some data, we show it as a contract call and try to decode the data in a human readable form
- if a transaction has 0 eth, some data but no log we can assume that the underlying contract execution failed. for erc20 tokens that would usually mean you didn’t have enough tokens or you didn’t pay enough gas

## Acceptance Criteria

- an ERC20 token transaction for which the user didn't had enough funds is shown as failed token transaction in the transaction list and chat messages

**Comment by flexsurfer** [comment]
@yenda any updates for this issue?

**Comment by flexsurfer** [comment]
@yenda is this still  relevant?
