### ISSUE TITLE
App crashes upon launch on Pixel 3

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8154]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User reports that "I have the latest stable status.im release on google pixel 3 and it crashes immediately on launch"

#### Expected behavior

app is launched

#### Actual behavior

app crashes

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 0.12.0 or 0.12.1 (not clear yet)
[comment]: # (Android or iOS.)
- Operating System: Android, real device Pixel 3 

### Notes from test team
I can't reproduce it for fresh install (not upgrade) on Pixel 3 and Pixel 3 XL with both latest releases if use real devices from Browserstack:
0.12.0 https://status-im.ams3.digitaloceanspaces.com/StatusIm-190429-110727-0ceb4c-release.apk
0.12.1 https://status-im.ams3.digitaloceanspaces.com/StatusIm-190506-084842-09a03e-release.apk

**Comment by churik** [comment]
Can't reproduce on Pixel 3 (Android 9, Android 10) - real devices (BrowserStack)
