### ISSUE TITLE
ERROR [status-im.models.transactions:99] - Request for block info failed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8157]
# Problem

Found in https://github.com/status-im/status-react/pull/8112 but was not introduced there

![image](https://user-images.githubusercontent.com/28752642/57406504-97d2bd00-71e9-11e9-87bd-58c2efd39c71.png)

## Steps

Test that has failed https://ethstatus.testrail.net/index.php?/tests/view/635270

## Logs

```
05-08 08:46:27.713  4559  4613 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :chat
05-08 08:46:27.716  4559  4613 D ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
05-08 08:46:27.726  4559  4613 E ReactNativeJS: ERROR [status-im.models.transactions:99] - Request for block info failed
05-08 08:46:27.731  4559  4586 D EGL_emulation: eglMakeCurrent: 0xd1bd9ba0: ver 2 0 (tinfo 0xd1c7e160)
05-08 08:46:27.739  4559  4613 W ReactNativeJS: Unable to symbolicate stack trace: Bundle was not loaded from the packager
05-08 08:46:27.744  1410  1947 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
05-08 08:46:27.745  4559  4613 D ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :chat
```

**Comment by yenda** [comment]
This will be fixed within #8151

**Comment by asemiankevich** [comment]
thanks @yenda :)

**Comment by Serhy** [comment]
Get this error on the real device with Android 8.1 with nightly build after sending a transaction in DApp -> Sign Tx -> tap 'Done' button.

**Comment by annadanchenko** [comment]
@asemiankevich how often does it happen? is it on both ios and android?

**Comment by flexsurfer** [comment]
@yenda do you know the reason of this? can we have a quick temporary fix for this just to unblock autotests?

**Comment by yenda** [comment]
@flexsurfer I don't think there is a quick fix because I can't reproduce it. My guess is that sometimes get-block-info returns nothing if the block is not found (requested too soon, the node didn't receive it yet). It will be fixed anyway by the end of the day with my token transaction PR which removes it completely

**Comment by asemiankevich** [comment]
> @asemiankevich how often does it happen? is it on both ios and android?

i got it once within autotests and i see sergey could repro with dapp. Both cases were seen on androids. I did not hunt for this bug more yet

**Comment by asemiankevich** [comment]
can't reproduce anymore
