### ISSUE TITLE
"this.props.onPress is not a function" on tapping back from transaction details screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8160]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug
_Summary_: when tapping button "Back" on screen "Transaction details" - got an error "this.props.onPress is not a function". User still can navigate back using native keyboard.

#### Expected behavior
no error

#### Actual behavior
![photo!UNITO-UNDERSCORE!2019-05-09 10 17 00](https://user-images.githubusercontent.com/4557972/57438164-98983d00-7243-11e9-8150-b33c33120765.jpeg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Go to Transaction History
* Open Transaction Details
* Tap on "Back"

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 09/05/2019
* Operating System: Android, iOS

**Comment by flexsurfer** [comment]
we missed this issue here https://github.com/status-im/status-react/pull/8140
