### ISSUE TITLE
Can't open newly installed nightly on Mac 

### ISSUE THREAD

**Issue by J12B** [status-im/status-react#8178]
# Problem

Installed the latest nightly (from https://status.im/get/) on my Mac (running Mojava 10.14.4). 

Upon installation I tried to open the app but received an error message:

"We were not able to decrypt your data, you might need to create new account and erase your old data by tapping "Apply". Clicking on "Cancel" will try again. 

Problem: Clicking "apply" or "apply" has no action - the screen refreshes back to the same error message. 

I shut down the application, and re-opened, but received the same issue.  

Current state: am unable to use the app on Mac.

**Comment by churik** [comment]
Question: from which version you are upgraded?

With this error you can't use your dataset - you need to clean all data, reinstall app and restore your account from seed phrase. If you use several devices, you can pair them after installation and restore your contacts / public chats / username / photo.

Steps:
- delete your status app completely form `Applications`
- delete your Status data inside ` ~/Library/Application\ Support/`
- in terminal:
 `rm ~/Library/Preferences/im.status.StatusDesktop.plist`
 `killall -u $USER cfprefsd` 
- reboot your mac
- try to install nightly again

**Comment by J12B** [comment]
Thanks! As far as I can tell, the last nightly I installed was StatusIm-190412-103700-89f34a-nightly. around 12th April. Will take suggested action!

**Comment by pedropombeiro** [comment]
For what it's worth, I tried the upgrade on Mojave but it was successful, so at least it doesn't look like a widespread problem.

**Comment by churik** [comment]
Yes, I did the same approximately every week, didn't notice the problem as well.

**Comment by J12B** [comment]
Followed your instructions @churik and I'm back up and now running with the latest nightly. Thanks!
