### ISSUE TITLE
[Keycard] Keyboard is active after logout or change PIN

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8187]
# Problem
When logging out from an account which was created with keycard -> keyboard is active, and UI looks messy.

Same issue (active keyboard) appears when changing PIN

![image](https://user-images.githubusercontent.com/28752642/57570843-4146c800-740f-11e9-9dac-0eb8ac1874c7.png)

![image](https://user-images.githubusercontent.com/28752642/57571324-342cd780-7415-11e9-98c9-207c08cdbbd4.png)

## Steps

1. create account with keycard
1. logout

OR 

1. create account with keycard
1. profile > keycard -> change PIN -> enter correct PIN -> enter new PIN -> confirm new PIN

**Comment by asemiankevich** [comment]
@dmitryn probably some leftover of this PIN screen removal, please take a look

**Comment by dmitryn** [comment]
Weird bug – It only happens after new account setup, but it's not reproducible if you re-open the app.

I see a lot of repeated events in log:
```
:signals/signal-received "{\"type\":\"node.stopped\",\"event\":null}"
:set :keyboard-height ...
:set :keyboard-max-height ...
:hide-tab-bar
:set :keyboard-height ...
:set :keyboard-max-height ...
:hide-tab-bar
:set :keyboard-height ...
:set :keyboard-max-height ...
:hide-tab-bar
...
and so on 
```
which got dispatched immediately after logout
