### ISSUE TITLE
0.12.2 mobile hotfix release

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8196]
issue to manage mobile 0.12.2 hotfix release

- open issues and PRs for release: https://github.com/status-im/status-react/labels/release
- release notes to be added: https://notes.status.im/mobile-release-notes

Hotfix release scope:
- Update client with new status-go v0.25.0-beta.0
- on iOS client change staging to beta fleet
- update beta fleet with status-g0 v0.25.0-beta.0 (cluster is updated on May 15, ~10:56 CEST)

Expected feature freeze date:  May 13, 2019
Expected release date: May 15, 2019

### Testing info
- build 17 testing plan: https://ethstatus.testrail.net/index.php?/runs/view/3337
- build 17 https://ci.status.im/job/status-react/job/release/job/release%252F0.12.x/17/

### Builds in TestFlight and PlayStore to push as a release
TestFlight: 2019051311
PlayStore:  not the last one in the list! Use 2019051310. Version: 0.12.2. Uploaded: May 13, 1:25 PM

### Links for stable page update:
DIAWI: 'https://i.diawi.com/saTJ11'
APK: 'https://status-im.ams3.digitaloceanspaces.com/StatusIm-190513-105723-4ecac0-release.apk'
IOS: 'https://status-im.ams3.digitaloceanspaces.com/StatusIm-190513-105723-4ecac0-release.ipa'

Steps:
- [ ] Update the release schedule https://status.im/mobile-release-schedule/ (status.im/source/mobile-release-schedule/index.md)
- [x] Create 0.12.x release build with updated status-go v0.25.0-beta.0
- [x] Submit iOS build to Apple review
- [x] ~Create release notes~ only announcement in twitter and other comm channels will be done
- [x] Regression testing for release candidate build
- [x] ~(optional) Fix known blocker(s) found during regression testing~
- [x] ~(optional) Cherry pick fix(es) to the release branch~
- [x] ~(optional) Verify fix(es) on new release candidate build~
- [x] ~(optional) Retest~
- [x] ~Battery consumption testing~
- [x] Update description for final release build on PlayStore and TestFlight
- [x] Get links to release artefacts to update stable page
- [x] Update status.im/stable page with artefacts for mobile release (ipa, apk and diawi links)
- [x] Update cn.status.im with release apk link
- [x] Get exact versions of the tested final release build from test team and push them as release

Post release steps:

- [x] ~Update PlayStore Screenshots if significant feature is added or existing Screenshots are no longer same as in previous version~

**Comment by annadanchenko** [comment]
info valid on May 13:
- apk for release: **not the last one in the list!** Use 2019051310. Version: 0.12.2. Uploaded: Today, 1:25 PM
- ios version for release: 2019051311 (sent to Apple review)

**Comment by annadanchenko** [comment]
@mandrigin @rachelhamlin @j-zerah proposed text for comms on hotfix 0.12.2 `Hotfix to improve mailservers' performance`

**Comment by j-zerah** [comment]
We've pushed hot fix 0.12.2: it includes a fix to improve mailserver performance.

Update to the latest version here https://status.im/get/


work?

**Comment by annadanchenko** [comment]
Small update (mailservers' instead of mailserver):

We've pushed hot fix 0.12.2: it includes a fix to improve mailservers' performance.

Update to the latest version here https://status.im/get/

**Comment by annadanchenko** [comment]
got Apple approval for ios build in TestFlight, release will be pushed today May 15, 2019 15:00 CEST

**Comment by annadanchenko** [comment]
sorry guys, but we need to investigate new issue found in the last moment, will update in ~1 hr on the next steps

**Comment by annadanchenko** [comment]
issue is not a blocker, pushing release now

**Comment by annadanchenko** [comment]
ios and android releases are pushed.
updated stable page with links to new artefacts https://github.com/status-im/status.im/pull/326
updating release schedule https://github.com/status-im/status.im/pull/328
