### ISSUE TITLE
Error: chat.chat-id must be of type 'string', got 'null' (null)"

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8200]
# Problem

```console.error: "ERROR [status-im.utils.async:19] - failed to run task Error: chat.chat-id must be of type 'string', got 'null' (null)"```

error
    YellowBox.js:59:8
_callTimer
    JSTimers.js:152:14
_callImmediatesPass
    JSTimers.js:200:17
callImmediates
    JSTimers.js:473:30
__callImmediates
    MessageQueue.js:337:6
<unknown>
    MessageQueue.js:135:6
__guard
    MessageQueue.js:314:10
flushedQueue
    MessageQueue.js:134:17

## Steps

1. open status develop
2. + button -> new chat
3. enter any valid ens name and hit enter

![image](https://user-images.githubusercontent.com/28752642/58094714-0ba59a00-7bda-11e9-8a5c-1b3adbbf8668.png)

## Note

was able to reproduce it in #8228 when deleting public chat

**Comment by asemiankevich** [comment]
was able to reproduce it in https://github.com/status-im/status-react/pull/8228 when deleting public chat

**Comment by yenda** [comment]
@asemiankevich have you tried on other PRs (needs to be a build with log/error enabled because it's how they show in PR builds, on nightlies you would only see that in the logs), because #8228 doesn't touch chats at all

**Comment by yenda** [comment]
@asemiankevich the cause is already known

There is a comment from @cammellos in the code:
```
;; TODO: There's a race condition here, as the removal of the filter (async)
;; is done at the same time as the removal of the chat, so a message
;; might come between and restore the chat. Multiple way to handle this
;; (remove chat only after the filter has been removed, probably the safest,
;; flag the chat to ignore new messages, change receive method for public/group chats)
;; For now to keep the code simplier and avoid significant changes, best to leave as it is.
```

Basically this is reproducible by adding #status public chat and deleting it not too long afterward because you will still be receiving messages from the mailserver but the chat will be deleted from the database at that time so the transaction will fail

**Comment by asemiankevich** [comment]
thanks for checking that @yenda !
