### ISSUE TITLE
web3.personal.sign() not displaying message to sign and refusing password

### ISSUE THREAD

**Issue by FabioBonfiglio** [status-im/status-react#8209]
# Problem

Same as described [here](https://github.com/status-im/status-react/issues/4529) (best matching issue I found, but closed a long time ago), plus the fact that entered password isn't accepted, in response to a `web3.personal.sign("My message..", address, callback)` call.
Works well in Metamask.

**Comment by flexsurfer** [comment]
hey, thanks for the issue, could you please provide some code?

**Comment by FabioBonfiglio** [comment]
> hey, thanks for the issue, could you please provide some code?

Sure. Here is a snipet :
```javascript
ethereum.enable()
.then(function (accounts) {
  if (ethereum.isStatus) {
    web3 = new Web3(ethereum); // Here I inject web3.js API v0.20.6
  }
  web3.personal.sign(
    "This is a test msg to be signed.",
    accounts[0],
    function(err, sig) {
      if (sig != null) {
        console.log(sig);
      }
  });
});
```
Works well in a browser with Metamask.
In Status, it displays the signing screen, but message isn't displayed, and password isn't accepted ("wrong password" toast message) even with correct password.
Issue present in both normal and dev modes.
I use Status version 0.12.1 (status-go vv0.24.0-beta.1) and I run it on Android 9.

**Comment by FabioBonfiglio** [comment]
Here is a screenshot :
![Screenshot_20190515-103129](https://user-images.githubusercontent.com/48284219/57761197-4e103800-76fd-11e9-85e8-07ff07311f53.png)

**Comment by flexsurfer** [comment]
thanks @FabioBonfiglio i'll take a look!

**Comment by flexsurfer** [comment]
```js
web3.currentProvider.sendAsync(
{method: "personal_sign",
 params: [web3.toHex(message) account[0]],
 from :  account[0]},
cb);
```
if you need a workaround for now

**Comment by FabioBonfiglio** [comment]
This workaround works and now the password is accepted and I'm able to sign the message.
However, in the case of a long content, message is truncated and only the last lines are displayed : 

![Screenshot_20190515-131405](https://user-images.githubusercontent.com/48284219/57771670-aa7e5200-7713-11e9-9251-a9e1df647dae.png)

**Comment by flexsurfer** [comment]
@FabioBonfiglio you can scroll a message, but yes it's a bad UX, will be addressed in the new wallet UI soon

**Comment by FabioBonfiglio** [comment]
> @FabioBonfiglio you can scroll a message, but yes it's a bad UX, will be addressed in the new wallet UI soon

Unable to scroll here.
Looking forward to the new UI then :)
