### ISSUE TITLE
Empty mailserver added after app opened from PN with account autologin enabled [Android]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8217]
*Type*: Bug

*Summary*: When contact opens an app from PN with autologin enabled - in the list of mailservers there is an empty-value mailserver is added.
If to switch to this <no-value> mailserver then simultaneously 'Autoselection mailserver' setting is enabled -> connection to the <no-value> mailserver fails and contact switches to valid mailserver as expected.

With no autologin it's all fine (no empty mailserver in the list)
If open the app not from PN everything is OK as well  

No issues on iOS, but confirmed with Android

#### Expected behavior

No unexpected mailserver values are added in the list after app opened from PN with account autologin enabled 

#### Actual behavior

Empty mailserver added after app opened from PN with account autologin enabled [Android]
<img width="330" alt="Screenshot 2019-05-15 at 17 36 24" src="https://user-images.githubusercontent.com/8749671/57784085-fc38d380-7737-11e9-8c07-b47857597303.png">

### Reproduction

- Open Status and create new account (`User1`)
- `User1` re-logins with 'Autologin' setting enabled
- `User1` receives contact request from `User2` and adds `User2` in contacts
- `User1` closes Status app
- `User2` sends a message to `User1` (`User1` should receive Push Notification after that)
- `User1` taps Push Notification
- `User1` navigated to `Profile` -> `Mailserver settings`

### Additional Information

- Status version: Develop 0.13.0, Release 0.12.1, Release 0.12.2
- Operating System: Android

#### Logs
Logcat from `User1` above when user opened app from PN
(note: errors after `05-15 17:32:43.304  1495  1529 E ReactNativeJS: ERROR [status-im.mailserver.core:113] - mailserver: add-peer error invalid URL scheme, want "enode"
` are loged after I selected empty mailserver)
[NoValueMailserverFromPN.log](https://github.com/status-im/status-react/files/3183017/NoValueMailserverFromPN.log)

**Comment by rachelhamlin** [comment]
Could someone investigate what's happening here? Is this just creating a UI list item? Wondering what the risk level is, if automatic selection might eventually switch user to a non-functioning/empty mail server and crash the app, for example.
