### ISSUE TITLE
AppImage can't start on some Linux systems

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8226]
# Problem
from #status channel:
![Linux](https://user-images.githubusercontent.com/4557972/57935023-279afa00-78c1-11e9-8df1-812f2d1ab7a0.png)

## Notes
In https://status.im/docs/FAQ-desktop.html there is no info about supported versions of Linux / Mac OS.
From testing perspective: now for sure app is working on Linux Ubuntu 18.04 and it is not working on Linux Ubuntu 16.x

## Future Steps

Update https://status.im/docs/FAQ-desktop.html with supported OS versions.

**Comment by churik** [comment]
@vkjr @siphiuel probably you can help to find out which versions are supported.

**Comment by vitvly** [comment]
I think we support Ubuntu only starting from 18.04.

**Comment by vkjr** [comment]
@siphuel, do you know how we got this limitation?
