### ISSUE TITLE
App crash when submit cryptokitties with different than it's valid domain

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8239]
**_Type_**: Bug

**_Summary_**: Status crashes when requesting in Status app browser cryptokitties with different than `.co` domain name (e.g. of domain name values are `.com`/`.io`/`.blarandom` etc)
Could not get example with several other Dapps.

#### Expected behavior
`Unable to load page` page in Status browser app when open `https://www.cryptokitties` with different than `.co` domain name

#### Actual behavior
App crash when open `https://www.cryptokitties` with different than `.co` domain name
![](https://user-images.githubusercontent.com/8749671/58020124-eba9a400-7b0f-11e9-8bbb-60fabbf78ae3.png)

### Reproduction 1

* Open Status and create new account
* Navigate to `Dapps` -> enter `https://www.cryptokitties.domainname` in URL box
* Submit URL

### Reproduction 2

* Open Status and create new account
* Navigate to `Dapps` -> enter `https://www.cryptokitties.co` in URL box
* After Dapp loaded edit `.co` domain in URL box to `.com` and submit

### Additional Information

* Status version: Nightly develop 0.13/release 0.12
* Operating System: Android and iOS

#### Logs
Logcat of the issue:
[logcat_with_crash.log](https://github.com/status-im/status-react/files/3197771/CrashCryptoCatURLEdit.log)

**Comment by flexsurfer** [comment]
something wrong with this view https://github.com/status-im/status-react/blob/e739b4a3590d9f8cf364fb209b1fede53a5c9942/src/status_im/ui/screens/browser/site_blocked/views.cljs#L16

**Comment by churik** [comment]
Issue is not reproducible.
Also rechecked tapping on invalid URL - behavior is the same as in current nightly.
Tested on IOS 11.4.1 (IPhone 7), Android 8 (LG V20).
