### ISSUE TITLE
eth_signTypedData_v3 password is refused.

### ISSUE THREAD

**Issue by leroldary** [status-im/status-react#8241]
# Problem
eth_signTypedData_v3 isn't working for all valid messages. Trying to sign the eip712 structured data "wrong password" is displayed.
Example: https://dicether.github.io/js-eth-personal-sign-examples/ ("Sign Typed Data V3").

**Comment by flexsurfer** [comment]
hey @leroldary thanks!
there is a mistake in this example 
```
{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Person\":[{\"name\":\"age\",\"type\":\"uint64\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"wallet\",\"type\":\"address\"}],\"Mail\":[{\"name\":\"from\",\"type\":\"Person\"},{\"name\":\"to\",\"type\":\"Person\"},{\"name\":\"contents\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"uint256\"}]},\"primaryType\":\"Mail\",\"domain\":{\"name\":\"Ether Mail\",\"version\":\"1\",\"chainId\":1,\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\"},\"message\":{\"from\":{\"age\":46,\"name\":\"Cow\",\"wallet\":\"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826\"},\"to\":{\"age\":445711732,\"name\":\"Bob\",\"wallet\":\"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\"},\"contents\":\"Hello, Bob!\",\"id\":\"18446744073709551617\"}}"
```

is says "id\",\"type\":\"uint256\" but \"id\":\"18446744073709551617\"}}" is string

but we must show an error in the message field but not "wrong password"

**Comment by sterlu** [comment]
Is there a workaround for this? Signing typed data has been broken for at least a month.

**Comment by flexsurfer** [comment]
@sterlu  could you elaborate, please? signing typed data works properly in status, the problem in the example

**Comment by sterlu** [comment]
Hey @flexsurfer, thanks for the quick reply. 

I tried changing the example so that `18446744073709551617` is a number but the behavior did not seem to change. I've also tried signing orders via `@0x/order-utils` and gotten the same result. 

Running Status 0.12.2 on iOS.

**Comment by flexsurfer** [comment]
@sterlu are you trying on mainnet? because \"chainId\":1 is mainnet, and it works fine for me in status on mainnet with the 18446744073709551617 fixed as number

**Comment by leroldary** [comment]
@flexsurfer The string is intentionally. Or, how should one provide numbers greater than 2^53-1 bits? Or did I miss something?

**Comment by flexsurfer** [comment]
@leroldary makes sense, i'll take a look again, thanks

**Comment by sterlu** [comment]
@flexsurfer You are correct, when the chainId is present in the domain, and the same network is selected, the signing process seems to be correct. 

However, 0x orders do not contain a chain ID in their domain: https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/eip712_utils.ts#L61

The spec does say the user-agent should refuse signing if domain->chainId does not match the currently active chain. (https://github.com/0xProject/EIPs/blob/master/EIPS/eip-712.md#definition-of-domainseparator) So according to the spec recommendation, behavior of Status seems to be correct (other than the wrong error message). However neither Metamask nor Portis (don't know any other wallets that implement 712) seem to be working fine without chainId in the domain. 0x also seems to ignore this recommendation. 

Not sure what to make of this.

**Comment by flexsurfer** [comment]
big number will be fixed in status-go https://github.com/status-im/status-go/pull/1470

**Comment by flexsurfer** [comment]
proper error message: https://github.com/status-im/status-react/issues/8275

**Comment by flexsurfer** [comment]
thanks @sterlu could you please provide steps to repro with 0x ? thanks

**Comment by sterlu** [comment]
@flexsurfer this should cover it

```js
const { Web3ProviderEngine, RPCSubprovider, MetamaskSubprovider } = require('@0x/subproviders')
const { signatureUtils, orderHashUtils } = require('@0x/order-utils')

const statusTest = async function() {
  const order = {
    'makerAddress': '0x0000000000000000000000000000000000000000',
    'takerAddress': '0x0000000000000000000000000000000000000000',
    'feeRecipientAddress': '0x0000000000000000000000000000000000000000',
    'senderAddress': '0x0000000000000000000000000000000000000000',
    'makerAssetAmount': '40000000000000000000',
    'takerAssetAmount': '199500000000000000',
    'makerFee': '0',
    'takerFee': '0',
    'expirationTimeSeconds': '1558952368',
    'salt': '54266069353572226856629360689057169471602218976231584008749941008165089300388',
    'makerAssetData': '0xf47261b0000000000000000000000000d9ebebfdab08c643c5f2837632de920c70a56247',
    'takerAssetData': '0xf47261b0000000000000000000000000aa7427d8f17d87a28f5e1ba3adbb270badbe1011',
    'exchangeAddress': '0x0000000000000000000000000000000000000000'
  };

  const from = window.web3.eth.accounts[0];

  const providerEngine = new Web3ProviderEngine();
  const currentProvider = window.ethereum || window.web3.currentProvider;
  providerEngine.addProvider(new MetamaskSubprovider(currentProvider));
  providerEngine.addProvider(new RPCSubprovider('https://mainnet.infura.io'));
  providerEngine.start();

  let signedOrder = await signatureUtils.ecSignOrderAsync(providerEngine, order, from);

  const orderHashHex = orderHashUtils.getOrderHashHex(order);
  if (await signatureUtils.isValidSignatureAsync(providerEngine, orderHashHex, signedOrder.signature, from)) {
    alert('Successfully recovered signer');
  } else {
    alert('Failed to verify signer');
  }
}
```

**Comment by churik** [comment]
@sterlu does it still relevant?

**Comment by flexsurfer** [comment]
@churik should be fixed
