### ISSUE TITLE
[Wallet] erc20 custom tokens leftovers

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8243]
@hesterbruikman :
'Add custom token' can use some more love:
a) Retains position on list scroll, but has no visual indication of this. Is this as specified? @errorists can you please take a look?
b) If the behavior of Add custom token is that it adds all selected items, I think it needs a stronger conection to the Select boxes. Maybe same row as 'default' title as in one of the design proposals

@errorists :
The 'Add custom token' button should not have a sticky position, it's just a regular list item that scrolls with the rest of the list

**Comment by errorists** [comment]
Some additional things: upon loading the list of tokens ( ••• -> Manage Assets ) my phone becomes unresponsive - can't scroll or toggle - for 2-3 seconds, iPhone X, iOS 12.3 :(

Both the 'Add custom token view' and 'Assets' use the incorrect white Status Bar appearance (btw it's a pain in the ass we have to do this manually each time)

Does the token icon get a randomly assigned background color similar to our chats? I only had green ones so far… If not, it should :)

Is there a way to delete a custom token? swipes and long presses don't work

other than those small nitpicks, great job! 👏

**Comment by flexsurfer** [comment]
> Some additional things: upon loading the list of tokens ( ••• -> Manage Assets ) my phone becomes unresponsive - can't scroll or toggle - for 2-3 seconds, iPhone X, iOS 12.3 :(
> 
wow that's weird, haven't noticed that, and you don't have same in nightly right?

> Both the 'Add custom token view' and 'Assets' use the incorrect white Status Bar appearance (btw it's a pain in the ass we have to do this manually each time)

could you elaborate, please?
 
> Does the token icon get a randomly assigned background color similar to our chats? I only had green ones so far… If not, it should :)

yes it's , i use these colors https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/colors.cljs#L48, for me it was mostly green as well, but i saw purple once, should work the same as for chats, have you noticed if chats mostly green?

> Is there a way to delete a custom token? swipes and long presses don't work
long press was merged yesterday, so i'll work on https://github.com/status-im/status-react/issues/8236 asap
> other than those small nitpicks, great job! 👏

thanks!

**Comment by errorists** [comment]
> wow that's weird, haven't noticed that, and you don't have same in nightly right? 

It happened on first open, on second open I could scroll but it was super laggy with maybe a couple FPS, on third was ok. It looks like it's not optimised for the amount of things to render in the list. 

edit, nightly: the same, there's a noticeable delay between pressing Managing assets and the Assets view transitioning and while I start scrolling after open, I see it starts to load other list items which slows it down to a crawl 

> could you elaborate, please?

Sure, the iOS status bar, the one with clock, is using the white appearance, so it's invisible, should be black :)

For the background in chats I'm mostly getting purples and blues, no greens at all :D
