### ISSUE TITLE
IPFS Gateway reportedly unreliable (PLACEHOLDER ISSUE)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#8251]
NOTE: This is a placeholder issue as I haven't personally experienced this issue, please edit it/close it as appropriate.

# Problem

It appears IPFS gateway is "unreliable" (NOTE: Unqualified statement, I don't know what people mean by this.)

## Acceptance Criteria

- Understand root cause of why unreliable
- Fill upstream bug if necessary
- Either fix or leave open as upstream or wontfix

## Notes

https://github.com/status-im/status-react/pull/8129#issuecomment-494431093%20question%20on%20TTT%20an

https://github.com/status-im/status-react/pull/8129#issuecomment-494431093

> for now to resume testing we need separate IPFS gateway, because given by Infura don't work all the times.

So I succeeded to install TTT <10 % cases (actually only two times during the whole day of testing) It is mentioned in 8 #8129 (comment).

is this new behavior or have we obsreverd this a lot during testing last fwe months?
is it specific to infura gateway? was a local node used during testing? is it a problem for a specific time? rate limited? what's the error response from gateway?

> when I tested https://github.com/status-im/status-react/pull/7304 - I didn't notice this issue.
There I set up TTT a lot of times as well.
so unless we changed a bunch of stuff, that seems to possibly point to a temporary infura overloaded issue

so if we could isolate that behavior with specific response codes from gateway in a minimal example and show how it is non determinstic, we can point this to e.g. upstream and figure out root cause
Upstream?
https://github.com/INFURA/infura/issues/145
https://discuss.ipfs.io/t/504-gateway-timeout/4995
https://ethereum.stackexchange.com/questions/46638/how-long-does-infura-store-a-file-on-ipfs (old? re pinning)

**Comment by oskarth** [comment]
@yenda @siphiuel @churik @bgits @flexsurfer you guys have actually experienced this issue, so please edit this as appropriate with better details.

**Comment by vitvly** [comment]
I've experienced 2 kinds of issues:
1. Timeouts when invoking ipfs add through HTTP API.
2. Even after file is added successfully, often not possible to get it afterwards using the same gateway URI. But might be possible from a different gateway.

**Comment by oskarth** [comment]
@siphiuel Thanks. These sound like two separate issues, can you please create these as two issues with more details, including basic version number, if people upstream have this issue, etc? Then we can link it back here as an umbrella issue.

**Comment by bgits** [comment]
> I've experienced 2 kinds of issues:
> 
> 1. Timeouts when invoking ipfs add through HTTP API.
> 2. Even after file is added successfully, often not possible to get it afterwards using the same gateway URI. But might be possible from a different gateway.

You need to pin to either a node or the gateway to ensure the content does not get garbage collected. You should also ensure your adding and pinning to a node that will stay up. Pinning to your local node can give the impression that it's on the network but it's just cached locally.
