### ISSUE TITLE
[Wallet] Don't renew tokens I've removed on wallet update

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8254]
# Problem

The wallet updates when I receive a new transaction or a block is missed.
In both of these cases, a bug is causing tokens I removed from my display via `Manage Assets` to reappear. 

## Implementation

@yenda is familiar with the problem in develop.

## Acceptance Criteria

- Removing a token using `Manage Assets` means it does not reappear until I add it back, or I update Status.

**Comment by churik** [comment]
Not reproducible on nightly 26/02/2020
