### ISSUE TITLE
Error java.lang.IllegalArgumentException: 16 > 0

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#8256]
### Description
During keycard setup the error happens some times:

`Error java.lang.IllegalArgumentException: 16 > 0`

### Reproduction
No exact steps to reproduce but it may happen during pairing or generating keys step.

### Device
This user is using Galaxy S10+

### Solution
I expect it might happen because of unnecessary call to `getApplicationInfo()` method on "card connected" event.

![](https://user-images.githubusercontent.com/23836/58166498-9ea20b00-7c92-11e9-8993-f2e52e653dc8.png)

**Comment by dmitryn** [comment]
@asemiankevich does it reproduce on your device? I have fix in mind that needs to be verified, but i cannot reproduce it on my phone.

**Comment by asemiankevich** [comment]
@dmitryn i've seen this error several times , but no clear steps, i need to try again
