### ISSUE TITLE
Gas estimation on contract transfers for Eth transfers incorrect

### ISSUE THREAD

**Issue by RyRy79261** [status-im/status-react#8269]
### User Story

As a user, I would like to send some funds to other accounts such as Gnosis Safe.

### Description

*Type*: Bug
Sending eth to contract account estimates required gas at 21000 rather than the contract estimate.

*Summary*: Sending eth to the gnosis wallet sets the gas limit to 21000 rather than the actual amount thus will always fail

#### Expected behavior
Sending eth to this address happens successfully

#### Actual behavior
Transaction fails

### Reproduction
Send eth to a gnosis safe address

### Solution
This potentially has something to do with Create2 as the first TX on a gnosis safe account is an Eth transfer followed by contract creation. The way Status is establishing if its a contract or not needs to be amended 

### Additional Information
Working Tx (Gas:  33,087 ): https://etherscan.io/tx/0xa5f01294a6fe5b65538b41fc9a876d6ba13129e36395472953073e2093ec6c02

Failing Status Tx (Gas: 21,000): https://etherscan.io/tx/0xc6605a3739e3d198463124e3f97bcbba3442c2c9651256f30293b702c00ed39f

- Status version: 0.12.2
- Operating System: Android

**Comment by flexsurfer** [comment]
thanks @RyRy79261 we'll take a look

**Comment by rachelhamlin** [comment]
Just noting that this will be resolved in #8026 :)

**Comment by flexsurfer** [comment]
fixed in #8026
