### ISSUE TITLE
:load-default-contacts! handler is overwritten 

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#827]
### Description

`:load-default-contacts!` handler is duplicated `0.9.4` branch

See warning here:
<img src=https://cloud.githubusercontent.com/assets/2364994/23305173/2e6a5574-faa6-11e6-9ab9-065d140d9d62.png width=320/>

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status

**Comment by flexsurfer** [comment]
@rasom fixed in the epic/ui-refresh
