### ISSUE TITLE
"No protocol method IMap cljs.core/EmptyList: ()" when navigate to chat with unblocked user

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8273]
**_Type_**: Bug
_Summary_: `No protocol method IMap.-dissoc defined for type cljs.core/EmptyList: ()` error appears upon `load-more-messages` action in the chat with 20+ of your own messages and a received message(s) which is/are not shown. To clarify:

* `load-more-messages` in 0.12.2 release triggered when we scroll chat history with 20+ messages. In 0.13.0 version it becomes 5+ threshhold.
* `Received message(s) which is/are not shown` happens when you UNblock chat with user who sent you messages while this user were blocked (I received those messages then after re-logging)

Another thing to note is when this error appears - no more than 20+ are shown, but if they are there - `No protocol method IMap cljs.core/EmptyList: ()` fires up each time I pull more messages (please see video below at the end!)

After re-login to account all messages are shown, I can scroll and load-more-messages fine. No cljs.core/EmptyList: () error.

#### Expected behavior
No errors upon `load-more-messages` action in the chat with 20+ of your own messages and a received message(s) which is/are not shown.

#### Actual behavior
`No protocol method IMap.-dissoc defined for type cljs.core/EmptyList: ()` error appears upon `load-more-messages` action in the chat with 20+ of your own messages and a received message(s) which is/are not shown.
![](https://user-images.githubusercontent.com/8749671/58271649-2bcd8880-7d95-11e9-8b21-b6273b7b34ee.png)

Video: https://drive.google.com/file/d/1RJun-mbo5ateCArjPdY_7z2OcYssKuiR/view?usp=sharing

### Reproduction

* Open Status and create new account (UserA)
* UserB adds UserA in contacts. UserA then adds UserB
* UserA sends 50 messages to UserB
* UserA blocks UserB (from UserB's Profile -> `Block User`)
* UserB sends 10 messages to UserA
* UserA from `Profile` -> `Contacts` -> `Blocked Users` -> UserB profile -> Unblocks UserB
* UserA navigates to UserB 1-1 chat (scroll up to load more messages)

### Additional Information

* Status version: Release/Develop 0.12.2/0.13.0
* Operating System: Android and iOS 

#### Logs
UserA above:
[Status.log](https://github.com/status-im/status-react/files/3213307/Status.log)

**Comment by Serhy** [comment]
In this issue, we used Block User feature as the way to reproduce the error.
However, `Block User path` it's not the root cause. It's because some of the messages that were received by user are not shown in chat screen + user scrolls to the top to load history (please see https://github.com/status-im/status-react/issues/7458) 
That's why `medium-priority` I put here.

**Comment by churik** [comment]
Can't reproduce in on nightly 26/02/2020.
Have you seen this recently @Serhy ?

**Comment by Serhy** [comment]
Can't reproduce with recent develop builds.
