### ISSUE TITLE
Investigate memory clearance

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8279]
# Problem

> I couldn’t find any provisions for clearing sensitive data from memory in the ClojureScript code. This is something I would like to examine in the build artifacts in a longer security assessment.

## Notes

This issue was reported by Trail of Bits in a brief app review. 

We need to confirm whether this is missing and create a new issue to fix it if so.

**Comment by cammellos** [comment]
Seems like there's no easy way to do this in clojurescript/javascript.
There are some data structures that get override https://security.stackexchange.com/questions/192387/how-to-securely-erase-javascript-parameters-after-use but you'd still have to get it there and in that case memory would be exposed, as it would be pulled from the JSON api into a string. Closing for now, feel free to reopen if new information comes up.
