### ISSUE TITLE
Investigate transport security configuration

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8280]
# Problem
Trail of Bits found issue with line 44 of https://github.com/status-im/status-react/blob/develop/ios/StatusIm/Info.plist

`<key>NSAppTransportSecurity</key>

```
<dict>
```

```
        <key>NSAllowsArbitraryLoads</key>
```

```
        <true/>
```

```
        <key>NSExceptionDomains</key>
```

```
        <dict>
```

```
<key>api.status.im</key>
```

```
<dict>
```

```
<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
```

```
<true/>
```

```
</dict>
```

```
<key>localhost</key>
```

```
<dict>
```

```
<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
```

```
<true/>
```

```
</dict>
```

```
        </dict>
```

    </dict>`## Notes
We might need to have this config for the browser. But worth investigating if WKWebView can ignore that, per @mandrigin

**Comment by mandrigin** [comment]
@flexsurfer can you take a look if we can get rid of this conf and our DApps browser will still work?
