### ISSUE TITLE
Remove unnecessary permissions [iOS]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8282]
# Problem

ToB recommended that we remove any unnecessary permissions from https://github.com/status-im/status-react/blob/develop/ios/StatusIm/Info.plist. 

Per @mandrigin, we can probably remove this one:

`<key>NSContactsUsageDescription</key>

	<string>We need to access your contacts</string>`

## Notes

Would like to have @flexsurfer or @jeluard confirm that this is true before we remove.

**Comment by jeluard** [comment]
There is certainly a need to cleanup those as our dependencies (and related permissions) have significantly changed over time.

**Comment by mandrigin** [comment]
@StatusSceptre let's make this one a bounty too

**Comment by flexsurfer** [comment]
fixed
