### ISSUE TITLE
Remove unnecessary permissions [Android]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8284]
# Problem

From Trail of Bits:

> There is a configuration for a debug keystore, but not for a production keystore. Ensure that you aren't running the application in a debug configuration at all times. 

> Similar to the iOS version of the application, excessive permissions are being set for the application. Does it actually require NFC access? There is even a line in the android manifest saying: 

 

    

    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove"/>

## Notes

As with[ iOS](https://github.com/status-im/status-react/issues/8282), we need to go through the Android permissions and remove anything unnecessary.

**Comment by KubebatHaMachatz** [comment]
Hi,

Looking at the list of permissions in the Android manifest (https://github.com/status-im/status-react/blob/develop/android/app/src/main/AndroidManifest.xml) and after installing the Android app and playing with it a bit - It looks like the following permissions can be removed without affecting the app's functionality:
1. android.permission.NFC - can be removed assuming there is not NFC functionality (transferring funds from one device in proximity to another)
2. android.permission.ACCESS_FINE_LOCATION - can be removed assuming the app doesn't use the device's location services.
3. android.permission.READ_PHONE_STATE - This permission enables the app to access the device's mobile info (cellular network info, phone number, call log, text messages etc). I cannot think of a reason for Status to need this permission.

There are additional permissions i the manifest that might be redundant as well but I haven't had the time to dig into it. the ones I listed are the major ones.

**Comment by KubebatHaMachatz** [comment]
Please let me know if you are looking for someone to get involved and handle this issue. I'm a veteran Android dev (7+ years).

**Comment by katzdan** [comment]
Please let me know if you are looking for someone to get involved and handle this issue. I'm a veteran Android dev (7+ years).

**Comment by dmitryn** [comment]
We need `android.permission.NFC` for interaction with Keycard https://keycard.status.im
Not sure about other permissions listed though.

**Comment by mandrigin** [comment]
@katzdan thanks, we will appreciate your help! I'll make a bounty out of this issue then

**Comment by mandrigin** [comment]
@StatusSceptre let's make this one a bounty

**Comment by KubebatHaMachatz** [comment]
Can you attach a link to the GitCoin item so I can apply?

**Comment by rachelhamlin** [comment]
It's not yet active but will be included on the issue once the person who manages it sets it up @katzdan :)
