### ISSUE TITLE
Fix find-ns-obj not supported for target react-native error with advanced compilation

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8286]
# Problem

As described in the following issue:
https://github.com/thheller/shadow-cljs/issues/500

We currently need to use a fork a cljs to use advaned compilation with shadow-cljs because of a `find-ns-obj not supported for target react-native error`

## Implementation

Find what is the cause of the error in the code base and fix it

## Acceptance Criteria

The solution should be based on this PR and not use a fork of cljs

https://github.com/status-im/status-react/pull/8285

**Comment by yenda** [comment]
@StatusSceptre can we quickly bounty that to get it solved?

**Comment by rasom** [comment]
https://github.com/status-im/status-react/blob/448e84a0e99a5a14583c82c278a7c5e0ae84b673/src/status_im/utils/views.clj#L55 this line

**Comment by yenda** [comment]
@rasom I remember that it was added because otherwise the macro would complain about missing require in the namespace that don't require it already, is it going to become a problem again if we simply remove it?

**Comment by StatusSceptre** [comment]
@yenda I am a little confused here. Do you want me to create a bounty on this, even though it has already been solved and merged (with multiple authors)?

**Comment by yenda** [comment]
@StatusSceptre it doesn't need to go on gitcoin since it is already done but we should still reward @hlolli

**Comment by StatusSceptre** [comment]
I'll need a receiving address for that then, could not find a gitcoin profile for @hlolli...
