### ISSUE TITLE
 Google Play 64-bit requirement to solve before August 1, 2019

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8292]
Warning from PlayStore:

This release is not compliant with the Google Play 64-bit requirement

The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 2019052417.

From August 1, 2019 all releases must be compliant with the Google Play 64-bit requirement.

Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app. [Learn More](https://developer.android.com/distribute/best-practices/develop/64-bit)

Extra info in blog post: https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html
<img width="1580" alt="Screen Shot 2019-05-28 at 14 37 31" src="https://user-images.githubusercontent.com/6584810/58478366-305bbd80-8156-11e9-8501-a3738c8bebf6.png">

**Comment by jakubgs** [comment]
I'm researching the 64 bit support for Android builds and here is what I found:
#### What we include
```
 $ zipinfo -1 StatusIm-190524-171002-7f38c5-release.apk | grep \.so$
lib/armeabi-v7a/libc++_shared.so
lib/armeabi-v7a/libconceal.so
...(omitted)...
lib/x86/libc++_shared.so
lib/x86/libconceal.so
...(omitted)...
```
So we clearly do support `armeabi-v7a`, but we lack `arm64-v8a` libraries.
According to our `build.gradle` we include it:
https://github.com/status-im/status-react/blob/131b423a0acb92618192be17a92a9e51feda592e/android/app/build.gradle#L158
but then we exclude the `arm64-v8a`(as well as some others):
https://github.com/status-im/status-react/blob/131b423a0acb92618192be17a92a9e51feda592e/android/app/build.gradle#L177
Not sure why we build for it and then exclude it(as we do with `x86_64`), but it seems like just removing that `exclude` should fix things.

**Comment by jakubgs** [comment]
According to this:
https://developer.android.com/distribute/best-practices/develop/64-bit#build_your_app_with_64-bit_libraries
>Most Android Studio projects use Gradle as the underlying build system, so this section applies to both cases. Enabling builds for your native code is as simple as adding the arm64-v8a and/or x86_64, depending on the architecture(s) you wish to support, to the ndk.abiFilters setting in your app's 'build.gradle' file.

I've ran a manual build with a branch(`enable-arm64-v8a`) that does that:
https://ci.status.im/job/status-react/job/combined/job/mobile-android/10996/
Which resulted in this:
```bash
$  zipinfo -1 StatusIm-190530-150447-756b72-pr.apk | grep \.so$ | awk -F'/' '{print $2}' | uniq
arm64-v8a
armeabi-v7a
x86
```
So removing that `exclude` clearly works.

**Comment by jakubgs** [comment]
This does increase the size of the APK from `51M` to `68M`.
I'm not entirely sure why we need the `x86` libraries, or `x86-64` for that matter, since we remove them anyway.

**Comment by jakubgs** [comment]
I think this can be solved as the Android builds now include the `arm64-v8a` architecture:
https://github.com/status-im/status-react/blob/d2a51f9711f1c74c0327fcd076dc1bff5fa32d4f/android/gradle.properties#L44
