### ISSUE TITLE
Update screenshoots in PlayStore

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8293]
# Problem
pictures with old UI and old DApp tab is shown in play store, we need to update them in https://github.com/status-im/status-react/tree/develop/fastlane/metadata/android/en-US/images/phoneScreenshots with these pictures (use same order as list below)

![1 wallet](https://user-images.githubusercontent.com/6584810/58484190-e4af1100-8161-11e9-80cd-eb5a5f774a8a.png)
![2 send tx](https://user-images.githubusercontent.com/6584810/58484214-ec6eb580-8161-11e9-917f-f2a7e1551a61.png)
![3 tx history](https://user-images.githubusercontent.com/6584810/58484262-04463980-8162-11e9-812d-485eccabc11b.png)
![4 chats list](https://user-images.githubusercontent.com/6584810/58484272-090aed80-8162-11e9-86c6-53900a7c35bb.png)
![5 one to one chat](https://user-images.githubusercontent.com/6584810/58484285-0dcfa180-8162-11e9-9b25-ddc84893fb09.png)
![6 public chat](https://user-images.githubusercontent.com/6584810/58484296-132cec00-8162-11e9-94e3-174bcb2614ff.png)
![7 daps](https://user-images.githubusercontent.com/6584810/58484300-16c07300-8162-11e9-89d1-83f0f88764c8.png)

**Comment by j-zerah** [comment]
Please update Playstore copy cc @annadanchenko 

**Title:** 
Status — Private, Secure Communication (Unreleased)

**Description**
Status is an open source, multi-purpose communication tool that combines a peer-to-peer messenger, decentralized crypto-wallet, and Web3 browser.

Important: Status is currently in beta testing. There are risks associated with testing a beta product, so when opting in you will be prompted to read and acknowledge you understand and accept these risks.

Though still a work in progress, we hope this beta shows the beginnings of a friendly, intuitive experience for Ethereum, and what will hopefully be the start of a fantastic client for the Ethereum network.

**What is Status?**
Status is a messenger, crypto wallet, and Web3 browser built with state of the art technology.

Status strives to be a secure communication tool that upholds human rights. Enabling community money, community law and through privacy, preserving culture.

**Beta Features:**

■ Encrypted Messaging — built using the Whisper protocol, enabling peer-to-peer private, public, and group chats, & social payments.

■ Secure Crypto Wallet — safely send, store and receive crypto assets including ERC20 and some ERC721 tokens.

■ Browse DApps — privately browse the growing ecosystem of DApps with the Web3 browser. Browse the latest marketplaces, exchanges, games, and more.


**Get Involved**
As an open source project, the single best way to get involved with development is to download and test Status. Our mission is to facilitate the transition to a more open internet and financial system through the new paradigm Ethereum represent. Status is building a community where anyone is welcome to join and contribute to the cause. Explore all the ways you can get involved https://status.im/get-involved/
