### ISSUE TITLE
preview privacy mode not working properly in some android devices until app restart

### ISSUE THREAD

**Issue by bitsikka** [status-im/status-react#8295]
# Problem

I just discovered that on my One+ 2 device with `OxygenOS version 3.6.1` `Android version 6.0.1` turning on `Preview Privacy Mode` does not blank out preview as it is supposed to when the app is in background

It shows the last captured screen when app was put in background without the setting being on.

restarting the app with the setting on makes it behave as expected - preview is blank

## Implementation
I see two possible scenario

1) Figure out if there is a way to clear captured screen just before setting is turned on or something like that to align the behavior to what is expected

2) Alert the user when the user turns on the feature that it requires the app to be restarted to work fully

## Acceptance Criteria

No surprises - set correct expectation - app/feature behaves as expected

## Notes

In the code FLAG_SECURE is enabled only for Android version ICE_CREAM_SANDWICH or above - make sure the setting is visible for those devices only to set additional expectation. Document it in appropriate user documentation

**Comment by flexsurfer** [comment]
should be fixed
