### ISSUE TITLE
Display DApp in fullscreen when user scrolls up

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-react#8299]
# Problem

The status browser takes a lot of screen real estate which distracts from the dapp itself.

## Implementation

The approach taken in other mobile browsers is to hide the toolbars when the user scrolls down, and to show the toolbar again when scrolling up. Below is how it looks like in firefox mobile.

![image0 (1)](https://user-images.githubusercontent.com/176720/58502783-4452ef80-8155-11e9-9b57-b162621180a5.png)

![image0 (2)](https://user-images.githubusercontent.com/176720/58502793-474de000-8155-11e9-9842-010762fb5468.png)

**Comment by andremedeiros** [comment]
@hesterbruikman @errorists do we understand how iOS/Android decide to hide the top bar? Sounds like this could be a huge improvement in terms of screen usage (particularly for lower end phones.)

**Comment by errorists** [comment]
@andremedeiros we just need for it to happen, hiding the toolbar was always there as part of the design for quite a long time now [Figma](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=3000%3A772)

If we want to hide the address bar along with it, sure we could discuss that. that's like 56 pixels of additional space, 52 for the toolbar.

**Comment by hesterbruikman** [comment]
> @hesterbruikman @errorists do we understand how iOS/Android decide to hide the top bar?

To add, here are 2 related issues. If we solve them, it'll probably make it easier to fix this. I don't think we control the topbar well atm.

- Include a safeArea in the topbar: https://github.com/status-im/status-react/issues/8981
- Search bar hide on scroll (address bar would than act as the Search bar component: https://github.com/status-im/status-react/issues/7697

The browser address bar is currently out of scope for #8981 I'm not sure why that is though. Probably @rachelhamlin or @flexsurfer can answer that.

**Comment by errorists** [comment]
> Search bar hide on scroll (address bar would than act as the Search bar component)

to only add to that so it's not confused, it's a different behaviour we want for those. Browser's address bar is a predefined Y axis animation that happens when a certain scroll velocity value has been achieved on scroll.
For the Search Bar, it's placed at a -1 position in the list, kinda like a basement. We don't animate it.

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/issues/12394
