### ISSUE TITLE
Console dapp can be removed form application (epic/ui-refresh)

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#830]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Console and Wallet dapps can be removed form application

#### Expected behavior
A user can not remove Console dapp.

#### Actual behavior
A user can remove Console dapp.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status 
- Open contacts screen
- Open context menu
- Edit
- Open Console contact's context menu
- Delete contact

**Comment by flexsurfer** [comment]
do we need a new property for contact item, something like `can-be-deleted?`? or should we just prevent deletion of console and wallet in the code?

**Comment by rasom** [comment]
No, I suppose that we can just hardcode this for Console and maybe Wallet, not sure about Wallet

**Comment by jeluard** [comment]
Duplicated by #1171
