### ISSUE TITLE
Check into validity checker (Android)

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8300]
# Problem

Also reported by Trail of Bits:

> I couldn’t find a file validity checker. This is important when you are using external storage. The permissions in the Android manifest indicate that you are using external storage. 

## Implementation

The point of this issue is to investigate whether this exists or not. 

## Acceptance Criteria

Comment on whether we have a file validity checker on Android. If no, please create separate issue for follow-up.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
