### ISSUE TITLE
Stop exporting services (Android)

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8302]
# Problem
A static analysis from Trail of Bits indicated that we are sharing the following services with other apps on the user's device:

> "Service (io.invertase.firebase.messaging.RNFirebaseMessagingService) is not Protected. An intent-filter exists." - A Service is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. The presence of intent-filter indicates that the Service is explicitly exported.

> "Service (io.invertase.firebase.messaging.RNFirebaseInstanceIdService) is not Protected. An intent-filter exists."        A Service is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. The presence of intent-filter indicates that the Service is explicitly exported.

> "Service (com.google.firebase.messaging.FirebaseMessagingService) is not Protected. [android:exported=true]" - A Service is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device.

> "Broadcast Receiver (com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver) is Protected by a permission, but the protection level of the permission should be checked. Permission: android.permission.INSTALL_PACKAGES [android:exported=true]" -        A Broadcast Receiver is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. It is protected by a permission which is not defined in the analysed application. As a result, the protection level of the permission should be checked where it is defined. If it is set to normal or dangerous, a malicious application can request and obtain the permission and interact with the component. If it is set to signature, only applications signed with the same certificate can obtain the permission.

> "Broadcast Receiver (com.google.firebase.iid.FirebaseInstanceIdReceiver) is Protected by a permission, but the protection level of the permission should be checked. Permission: com.google.android.c2dm.permission.SEND [android:exported=true]" -        A Broadcast Receiver is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. It is protected by a permission which is not defined in the analysed application. As a result, the protection level of the permission should be checked where it is defined. If it is set to normal or dangerous, a malicious application can request and obtain the permission and interact with the component. If it is set to signature, only applications signed with the same certificate can obtain the permission.

> "Service (com.google.firebase.iid.FirebaseInstanceIdService) is not Protected. [android:exported=true]" - A Service is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device.

## Notes
Please ensure that these services are no longer shared.

**Comment by mandrigin** [comment]
@StatusSceptre let's make a bounty out of this issue?

**Comment by cammellos** [comment]
Firebase has been removed, so this does not seem to be any longer an issue.
