### ISSUE TITLE
[keycard onboarding] intro and start screens

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#8306]
# Problem
Implement intro and start screens of keycard onboarding flow.

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=928%3A623

![](https://user-images.githubusercontent.com/23836/58548657-665e7780-8212-11e9-9c34-d9016622a008.png)

**Comment by asemiankevich** [comment]
@dmitryn after you added scrolling - the text is hidden under dots. It may be related to my small screen (5.2") @hesterbruikman 

![image](https://user-images.githubusercontent.com/28752642/60185110-07504a80-9832-11e9-93dd-bad32d291637.png)

also i cant scroll this screen and can't proceed

![image](https://user-images.githubusercontent.com/28752642/60185328-601fe300-9832-11e9-8d9d-0e70bc32ac3b.png)

**Comment by dmitryn** [comment]
@asemiankevich i'm removing these dots. Just pushed new commit to PR.
