### ISSUE TITLE
[keycard onboarding] keycard tapped modal screens

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#8309]
# Problem
Implement keycard tapped modal screens

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=928%3A427

During the onboarding, if keycard tapped before key storage is selected, modal screen should be shown.

![](https://user-images.githubusercontent.com/23836/58549715-d0781c00-8214-11e9-84ee-e4f51b744f2e.png)

**Comment by corpetty** [comment]
this is fine to happen post audit code freeze.
