### ISSUE TITLE
[keycard onboarding] pin screens

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#8310]
# Problem
Implement pin screens.

## Implementation
Use PIN screens implementation from regular onboarding.

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=1018%3A17997

![](https://user-images.githubusercontent.com/23836/58549881-306ec280-8215-11e9-9263-a3fe440132b6.png)

**Comment by dmitryn** [comment]
Depends on https://github.com/status-im/status-react/pull/8234
PIN screen could be taken from there.

**Comment by StatusWrike** [comment]
➤ Guy-Louis Grau commented:

Dmitry, can this one be closed ?
