### ISSUE TITLE
[keycard onboarding] 'screenshot taken' modal screen

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#8313]
# Problem
Implement 'screenshot taken' modal screen

## Implementation
If screenshot is taken during puk and pair code backup, modal screen should be shown.
![](https://user-images.githubusercontent.com/23836/58550267-0b2e8400-8216-11e9-98e5-4003b846152f.png)

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=1328%3A147

**Comment by dmitryn** [comment]
There is a library which does screenshot detection. It register observers that listens to new media files on your device and checks if new file could be the screenshot (by file name and image dimensions)

https://github.com/fenglu09/react-native-screenshot-detect/blob/master/android/src/main/java/com/jason/rnscreenshotdetect/ScreenShotDetectModule.java

If we are up to use it, we would need Android storage read permissions `READ_EXTERNAL_STORAGE`  (i suppose we already have it).

**Comment by StatusWrike** [comment]
➤ Dmitry Novotochinov commented:

Should be checked if this is a part of V1

**Comment by guylouis** [comment]
@rachelhamlin @hesterbruikman 
we had planned to prevent the user to take screenshots of the screen when on a screen with secrets (here for keycard puk and pairing code)
this requests some native code for android
if we do that for keycard secrets we should do it for mnemonic too for non keycard users, and thus should be done on android and ios 
can we consider this out of v1 (this is what we consider now, just want to check and align)

**Comment by hesterbruikman** [comment]
my 2c, regretfully: out of V1

**Comment by rachelhamlin** [comment]
Agreed. Do we have this in Wrike?

**Comment by guylouis** [comment]
Here https://www.wrike.com/open.htm?id=357492241

**Comment by guylouis** [comment]
not needed anymore since this is managed by a setting for the whole status app
