### ISSUE TITLE
[Tests] Configure automation framework to cover Goerli network testing

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8318]
# Problem
We have now Goerli network (testnet) added to network list, it was done in https://github.com/status-im/status-react/pull/7734. Suggest to adjust out e2e framework to cover transaction tests on this network too

## Implementation

* [ ] have possibility to create separate build with Goerli network enabled by default for automation
* [ ] deal with Goerli faucet https://faucet-goerli.status.im/faucet-info and fill test accounts with ETH on Goerli
* [ ] select a bunch of tests to be run on this network
* [ ] probably adapt simpledapp.eth (status-im.github.io/dapp) to have ETH and tokens assets there for testing purposes, maybe @flexsurfer could help

## Acceptance Criteria

* [ ] e2e tests (selected range of tests) could be run on Goerli network, testing could rely on this results (selected tests should pass).

**Comment by cammellos** [comment]
Closing for now as that requires a considerable amount of effort
