### ISSUE TITLE
Change or remove back button from DApp browser screen

### ISSUE THREAD

**Issue by naghdy** [status-im/status-react#8321]
# Problem
I was using the Teller Network DApp within the Status browser. As I was tapping specific sellers, and trying to go "back" to the main screen - I kept accidentally pressing the browser back button on the top left. This was very frustrating, because I kept having to re-open the DApp even though I just wanted to go back to the previous screen.

I believe this is a flaw in the placement of the back button, and would recommend we replace (or even remove) the back button.

## Notes
Here is a screenshot of the button. Any thoughts for improvements to this? From a timeframe perspective, considering this is primarily client work, we can do it after the code freeze.
![IMG!UNITO-UNDERSCORE!6360](https://user-images.githubusercontent.com/32269875/58625310-805f8f00-82d2-11e9-9ae5-ca27b383c9a2.jpg)

**Comment by iurimatias** [comment]
Instead of the back arrow we could replace it with a icon that clearly indicates this would change tabs/pages, something like the icons below.

![Screen Shot 2019-05-30 at 7 40 39 AM](https://user-images.githubusercontent.com/176720/58630795-77f55d00-82ae-11e9-97b6-8e1399f2db8c.png)

![Screen Shot 2019-05-30 at 7 42 00 AM](https://user-images.githubusercontent.com/176720/58630798-7af04d80-82ae-11e9-9185-15b85334e559.png)

**Comment by flexsurfer** [comment]
this is a regression, we had "X" button before, maybe @errorists could suggest something even better

**Comment by errorists** [comment]
thanks for bringing it to attention, the back design was always a lesser evil until we can do proper window/tabbed browsing. The problem with 'X' was that it suggested finality, that whatever you're doing now won't be coming back which wasn't true, the current URL and browsing history is kept intact waiting for you in the DApps list. I'll take a look at alternatives like a 'home' icon or the aforementioned tabs and see what performs better in quick user tests throughout the weekend.

**Comment by rachelhamlin** [comment]
👍 Low priority though @errorists. Don't want us to derail from multi-account by thinking about minor changes that can happen post code freeze.

**Comment by naghdy** [comment]
Agree with @rachelhamlin this is something we can do post code freeze as it's simply UI changes. 

Thanks @errorists and @flexsurfer for your prompt response

**Comment by hesterbruikman** [comment]
Discussed with @errorists . Reverting to the previous 'X' is the best short term solution.

This will at least help alleviate any confusion between going back to Home and navigating back in the DApp/tab.
