### ISSUE TITLE
`Re-matches must match again a string` at attempt to report a bug when logged out

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8325]
### Description
*Type*: Bug
*Summary*: at attempt to shake the phone and report a bug before login error `Re-matches must match again a string`.
After closing popup unable to call dialog on shaking until app restart.

#### Expected behavior
Can report a bug 

#### Actual behavior
![IMG_0045474D998A-1](https://user-images.githubusercontent.com/4557972/58643262-36d96900-82ff-11e9-96ac-691ff8b0c728.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Log out
- Shake the phone
- Tap on "Report a bug"

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 0.13.0
- Operating System: Android, iOS

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
@churik I can't repro on iOS but I frankly don't know what build I'm on. Let's plan to investigate.

**Comment by churik** [comment]
I will recheck it and let you know

**Comment by churik** [comment]
@rachelhamlin can reproduce it on current `develop` (on Android)

**Comment by rachelhamlin** [comment]
@churik to clarify - can you not continue with the `report a bug` option here?

**Comment by churik** [comment]
@rachelhamlin no, I can't. If I tap 'report a bug', error appears again.
So it makes impossible to send logs / report error when you are logged out.

**Comment by rachelhamlin** [comment]
I'm removing this from the v1 release backlog bc users have other avenues to report bugs, namely #status, or perhaps some other #support channel. 

cc @andremedeiros
