### ISSUE TITLE
Transaction: [missing {{amount}} value] ETH

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#833]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to send a transaction and not see a weird error message that doesn't exist when I open the chat.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The message appears as Transaction: [missing {{amount}} value] ETH

Found on iOS

![bug](https://cloud.githubusercontent.com/assets/2714786/23456693/cbb4ff06-fe74-11e6-9fd9-d1c7d10dc3f6.jpg)

**Comment by rasom** [comment]
Fixed in #832
