### ISSUE TITLE
Styles bugs in contacts (epic/ui-refresh)

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#834]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
Some bugs (maybe not) left after https://github.com/status-im/status-react/pull/826

1. "Delete contact" label has different color [iOS] 
<img width="755" alt="screen shot 2017-03-02 at 12 44 20" src="https://cloud.githubusercontent.com/assets/2364994/23508031/75742164-ff58-11e6-8ded-4e7a1d8f65a6.png">

2. "Search contacts" label is not on the same line with `back`/`search` icons [iOS]
 I'm not sure that this is a big problem but I was able to find this difference, so it can be noticeable
<img width="1237" alt="screen shot 2017-03-02 at 13 44 46" src="https://cloud.githubusercontent.com/assets/2364994/23508175/1e604370-ff59-11e6-9330-ab83c8e1dab0.png">

3. Different background color [iOS] 
<img width="762" alt="screen shot 2017-03-02 at 12 47 43" src="https://cloud.githubusercontent.com/assets/2364994/23508183/2c439fb4-ff59-11e6-9101-62794397554e.png">
 
4. Wrong font styles for "Search contacts" placeholder [Android]
<img width="834" alt="screen shot 2017-03-02 at 14 37 26" src="https://cloud.githubusercontent.com/assets/2364994/23508211/4de3a8f8-ff59-11e6-9377-25d9e05a0397.png">

**Comment by flexsurfer** [comment]
1. Can't find easy way to do this (there is no option for text color in the ActionSheetIOS)
3-4 are bugs, should be fixed

**Comment by flexsurfer** [comment]
2. 
![image](https://cloud.githubusercontent.com/assets/11790366/24096384/84f9dac0-0d72-11e7-841e-24c3b1c6ae39.png) @andmironov I think we should fix this in mockups, placeholder and text should be on the same line

**Comment by flexsurfer** [comment]
3. 
![image](https://cloud.githubusercontent.com/assets/11790366/24096501/f2009366-0d72-11e7-8506-4eeca5a08c46.png) @andmironov but for group contacts list we have white background

**Comment by flexsurfer** [comment]
mockups has been changed  for items 2 and 3

**Comment by flexsurfer** [comment]
1 and 4 fixed in code
