### ISSUE TITLE
Deploy postgres mailserver to the rest of the fleet

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#8353]
Currently postgres mailserver is only deployed on one test fleet and it is currently under testing.
If testing is successful we will want to deploy that to the remaining fleets, but first we need to hydrate them (through syncing potentially).

This will involve installing postgres so that they have access to it and change config.

**Comment by annadanchenko** [comment]
@cammellos no issues found, so green light from testing, however I'm not sure if syncing data from other mailservers with last 30 days history will go smoothly, @adambabik to confirm

**Comment by StatusWrike** [comment]
➤ Igor Mandrigin commented:

Andrea Piana what do you think we can make a "real" migration from the old DB to the new one? Just read the old levelDB and write everything to Postgres?

**Comment by StatusWrike** [comment]
➤ Andrea Piana commented:

that's probably fine, as I understand though Adam Babik is working on restoring the sync functionality, either way is fine with me

**Comment by StatusWrike** [comment]
➤ Nabil Naghdy commented:

Andrea Piana Is there an update on this timeline?

**Comment by StatusWrike** [comment]
➤ Andrea Piana commented:

I'll ask adam what the state of the sync

**Comment by StatusWrike** [comment]
➤ Nabil Naghdy commented:

Whats the latest on this?

**Comment by StatusWrike** [comment]
➤ Andrea Piana commented:

Staging has been migrated, and it will be tested probably today or so, once successfully tested we can proceed with Beta, but other then testing no development effort is spent on this, as it's just a matter of running a script

**Comment by jakubgs** [comment]
I've deployed to all `eth.beta` hosts except for `mail-03.do-ams3.eth.beta`, which was left for @annadanchenko for tests. Once she's done with it I will complete the migration.

**Comment by rachelhamlin** [comment]
Checking in because this is slated for completion today in Wrike. Ballpark, much effort is left for you both? @annadanchenko for testing, and @jakubgs for whatever remains to complete migration - is it dependent on testing outcome?

**Comment by jakubgs** [comment]
This has been completed, I just forgot to close the issue.
