### ISSUE TITLE
Error dialog is shown when switching languages on some android devices

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8365]
# Problem

Error dialog is shown when switching system language while status is running on background

## Steps

1. open status
2. send to background
3. change system language in phone settings
4. resume app from background

Expected: user is logged out when system language is changed.
Actual: error dialog is shown

![image](https://user-images.githubusercontent.com/28752642/58959838-98da1880-87ae-11e9-89ee-940405e911a6.png)

## Logcat

https://drive.google.com/open?id=1uHo2TY5z_jIl5yHmxRv8Qj69qu6oUXPw

## Notes

Reproduced on Huawei P10 Lite Android 8

**Comment by yenda** [comment]
As a first step we should switch to https://github.com/react-native-community/react-native-localize because react-native-languages is deprecated

**Comment by rasom** [comment]
@yenda this is unrelated to the issue
