### ISSUE TITLE
Fullscreen WebView and "Offline" message look bad together

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#837]
<img width="487" alt="screen shot 2017-02-26 at 18 16 39" src="https://cloud.githubusercontent.com/assets/911127/23546245/bd01913a-000f-11e7-8001-e68b845afbc8.png">

**Comment by andmironov** [comment]
Would it be okay if we just cover the offline badge with the suggestions area? I mean, it wouldn't be visible, but i think it makes sense, since the suggestions area is sort of a pop-up

**Comment by annadanchenko** [comment]
On Android only: Offline is hidden behind the screen
builds: 0.9.6 and 0.9.6-7-ga9d1426+ 
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7dTRYSXBmVW96NEk

**Comment by andmironov** [comment]
yeah, the way it works on Android is exactly what i am talking about

**Comment by annadanchenko** [comment]
@andmironov I think that hiding Offline message is not a good idea. If device goes offline while user is on Wallet screen then there is no way to see this. We need to make sure that user sees this message
