### ISSUE TITLE
"a.toNumber is not a function" when open collectibles (Ethermon, Cryptostrikers)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8370]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: when open collectibles like Cryptostrikers or Ethermon - error is shown. Not reproducible with CryptoKitties.
It is not reproducible on release 0.13.0.

#### Expected behavior
can see collectibles

#### Actual behavior

![2019-06-06 15 29 50](https://user-images.githubusercontent.com/4557972/59036619-f5513c80-886f-11e9-896d-0c2e38aea76f.jpg)

### Reproduction

- Open Status
- Restore account with collectibles (Ethermon, Cryptostrikers in my case) 
- Set up wallet
- tap on Ethermon or Cryptostrikers in Collectibles list

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 06/06/2019
- Operating System: Android, iOS

#### Logs
[Status-debug-logs.zip](https://github.com/status-im/status-react/files/3261749/Status-debug-logs.zip)

**Comment by flexsurfer** [comment]
@churik should be fixed in nightly
