### ISSUE TITLE
Adding dependency causes Status to get stuck in logo

### ISSUE THREAD

**Issue by e18r** [status-im/status-react#8373]
### User Story

As a developer, I want to include the [unfurl](https://github.com/e18r/unfurl) library in the Status codebase, in order to address issue #4606.

### Description

*Type*: Bug

*Summary*: When I `:require` the [unfurl](https://github.com/e18r/unfurl) library in my code, the development app is launched, but it gets stuck on the logo forever. I imported that library in an [example project](https://github.com/e18r/test-project) successfully.

#### Expected behavior
![status2](https://user-images.githubusercontent.com/16065447/59049662-1c971200-884e-11e9-93f9-26a037d6252e.jpg)
Last line of `make react-native-android`:

    ::ffff:127.0.0.1 - - [06/Jun/2019:17:25:13 +0000] "GET /target/android/env/android/main.js HTTP/1.1" 304 - "-" "okhttp/3.12.1"

#### Actual behavior
![status1](https://user-images.githubusercontent.com/16065447/59049715-405a5800-884e-11e9-8bd1-82a74826f7a3.jpg)
Last line of `make react-native-android`:

    ::ffff:127.0.0.1 - - [06/Jun/2019:17:02:54 +0000] "GET /target/android/hickory/core.js HTTP/1.1" 304 - "-" "okhttp/3.12.1"

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- `git clone https://github.com/e18r/status-react -b fix-#4606`
- `git checkout 1a354b705`. In this commit, I added the dependency, but didn't require it in my code yet.
- Connect phone, run `adb start-server` and make sure it appears in `adb devices`. Run `adb reverse tcp:3449 tcp:3449`.
- Run `make start-dev-android-real`, `make react-native-android`, and `make run-android`
- Wait until everything is executed
- The app is launched correctly on the phone: ![status2](https://user-images.githubusercontent.com/16065447/59049662-1c971200-884e-11e9-93f9-26a037d6252e.jpg)
- Stop everything and `git checkout fix-#4606`. In this commit, I `:require` the dependency in my code.
- `make clean`
- Run the commands again
- The app is launched on the phone, but it gets stuck on the logo: 
![status1](https://user-images.githubusercontent.com/16065447/59049715-405a5800-884e-11e9-8bd1-82a74826f7a3.jpg)

### Additional Information
* Status version: commit 04de022ea, Sun Jun 2 14:10:46 2019 +0200
* Operating System: Android

#### Logs
Note: `adb logcat` seems to give too much unrelated information that could be confidential. Please let me know if you need that log.

##### WORKING #####
[startdev-android-real](https://pastebin.com/wfzfFidN)
[react-native-android](https://pastebin.com/scRadBRd)
[run-android](https://pastebin.com/mgk02cCN)

##### NOT WORKING #####
[startdev-android-real](https://pastebin.com/e03zfDCt)
[react-native-android](https://pastebin.com/PCzUknbR)
[run-android](https://pastebin.com/071sTA2r)

**Comment by pedropombeiro** [comment]
I do see this in adb logcat:
```
06-07 11:29:24.949  1932  1973 I ReactNativeJS: Requiring: react-native-keychain
06-07 11:29:27.209  1932  1973 I ReactNativeJS: Requiring: react-native-camera
06-07 11:29:30.735  1932  1973 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
06-07 11:29:30.735  1932  1973 W ReactNativeJS: ReferenceError: Can't find variable: Node
06-07 11:29:30.735  1932  1973 W ReactNativeJS: hickory$core$node_type
06-07 11:29:30.735  1932  1973 W ReactNativeJS: eval code
06-07 11:29:30.735  1932  1973 W ReactNativeJS: eval@[native code]
06-07 11:29:30.735  1932  1973 W ReactNativeJS: asyncImportScripts$@http://10.0.3.2:8081/index.android.delta?platform=android&dev=true&minify=false:206670:21
```

I'm assuming it's referring to
``` javascript
return (Node[[cljs.core.str.cljs$core$IFn$_invoke$arity$1(type),"_NODE"].join('')]);
```
in line 81 of `target/android/hickory/core.js`

maybe this is relevant? https://github.com/davidsantiago/hickory/issues/17#issuecomment-168378641

**Comment by e18r** [comment]
Thank you for your help, @PombeirP. It's probably very relevant, will look into that.
