### ISSUE TITLE
"Save password" is unavailable for devices without biometric authentication

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8375]
### Description
*Type*: Bug
*Summary*: on devices without biometric authentication not possible to use "Save password" anymore.
Instead of toggle "Save password is unavailable: your device may be rooted or lacks the necessary security feature"
Most likely was introduced in https://github.com/status-im/status-react/pull/8127

#### Expected behavior
Can use "Save password"

#### Actual behavior
![download (3)](https://user-images.githubusercontent.com/4557972/59093082-61d14780-8913-11e9-87c8-7270b0b9bf42.png)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account
- Log out

### Additional Information

- Status version: nightly 07/06/2018
- Operating System: Android (AFAIK there is no more iPhones without touch ID that Status can support)
- Devices: without biometric authentication (tested on Samsung Galaxy S7, Google Nexus 6)

**Comment by annadanchenko** [comment]
@tbenr would it be possible to fix it? So, devices without biometric authentication  can use Save password as before #8127?

**Comment by tbenr** [comment]
@churik @annadanchenko checking..

**Comment by tbenr** [comment]
Initially I implemented that check but then i forgot it was there...
