### ISSUE TITLE
Use cloudlare ipfs for stickers instead infura

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8376]
# Problem

Infura ipfs gateway is not reliable

## Implementation

Use cloudflare instead

**Comment by jeluard** [comment]
This issue requires more background checks.

Specifically:

- IPFS support pinning, moving away from it we would need to replace that
- are we confident that we have perf issues?
- if so, will moving to cloudflare solve it?

**Comment by StatusWrike** [comment]
➤ Rachel Hamlin commented:

Will discuss on 25/6 core UI sync.
