### ISSUE TITLE
[PERF] Replace use of slurp macro

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8381]
# Problem

Using the slurp macro is bad, whatever you slurp ends up being copied as is as a string in the minified js produced by the compiler, even with advanced optimization.

## Implementation

Each use case of the slurp macro is unique. The easiest case to get rid on is json config files, because they can be used like modules. @rasom can probably describe how to proceed

## Acceptance Criteria

The slurp macro is deleted

**Comment by rasom** [comment]
Implemented in #8394, though impact on performance is kind of limited. On the other hand it makes it a bit simpler to reason about the rest of index.*.js, because besides `status-im.utils.gfycat.*` the rest of it is actually js code, not string resources.
