### ISSUE TITLE
[PERF] Minify html, js and css

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8383]
# Problem

When opening a webview, we inject a modified version of web3 and 25k of non minified code of ours.
The web3 code is slurped and hence there is a 140ko string in the advanced compiled code (see #8381)

Extensions are also slurping a non minified 4k html file

## Implementation

Minify our html/css/js in the build pipeline
Find a way to inject web3 without slurping it into the bundle

## Acceptance Criteria

Can't find web3 in index.android.js
Can't find our html/css/js in index.android.js
Both are injected minified in the webview

**Comment by rasom** [comment]
this is handled by #8394 except magnification, but assuming it has very love impact on performance there is no real need to do magnification here

**Comment by pedropombeiro** [comment]
Is this issue still relevant?
