### ISSUE TITLE
Where can i get a apk？

### ISSUE THREAD

**Issue by mivanzhang** [status-im/status-react#8391]
# Problem

An overview of the background required to understand the problem.
A problem description.

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by mivanzhang** [comment]
Where can i get a apk？I want to have a try

**Comment by annadanchenko** [comment]
from PlayStore https://play.google.com/store/apps/details?id=im.status.ethereum or from https://status.im/stable/
