### ISSUE TITLE
Black bar overlaps the bottom tab panel [on iPad Pro]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8395]
***Type***: Bug 
***Summary***: On iPad Pro the bottom tab bar is covered by the safe area, meaning the black bar overlaps the text labels. And when the panel is minimized - the device bar overlaps icons.
We need to have extra padding, just like we do for the iPhone X.

#### Expected behavior
Status app bottom tab panel (Chats-Dapps-Wallet-Profile) is not overlapped by iPad Pro's bottom bar

#### Actual behavior
On iPad Pro the bottom tab bar is covered by the safe area, meaning the black bar overlaps the text labels.

![image1](https://user-images.githubusercontent.com/8749671/59178887-fe405780-8b68-11e9-8701-734c9a7abebf.jpeg)

### Reproduction

- Open Status on iPad Pro
- Navigate between screens

### Additional Information

- Status version: Release 0.13.0/ Develop
- Operating System: iOS

**Comment by churik** [comment]
Status v1.0.1 can't be installed on IPads, so closing
