### ISSUE TITLE
Noticible delay of 6th+ message appearance on chat view if they fit the screen after navigation

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8397]
***Type***: Bug

***Summary***: If there are > 5 messages fit the chat view on a device, in many cases, it's noticeable that we load first 5 messages and then the rest bunch of messages. It makes "the app laggy" impression. 

#### Expected behavior
All messages that fit chat view upon navigating to one appear at the same time.

#### Actual behavior
Noticible delay between first 5 and reset of messages appearance on chat view, if 6th (or more) messages fits the same screen after navigation to chat 

<img width="735" alt="Screenshot 2019-06-10 at 12 47 05" src="https://user-images.githubusercontent.com/8749671/59187452-271f1780-8b7e-11e9-92e3-fa0cc0ddb176.png">

VIdeo: https://drive.google.com/file/d/1q0DPexw-yUEEKxMGVvDgE96avDwW4BbZ/view?usp=sharing
### Reproduction

- Open Status and create new account
- Open chat with 5+ one-line messages (e.g. `#5thplusmessages` or `#status`)
- Pay attention to when 6th and latest messages appear

### Additional Information

- Status version: Release 0.13.0, Delevep 0.14
- Operating System: Android and iOS

**Comment by churik** [comment]
Don't think that it is like this now.
@Serhy wdyt?

**Comment by Serhy** [comment]
It's definitely improved right now in V1 release.
