### ISSUE TITLE
Implement Emoji Replace

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#840]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to type and have emoji's automatically replaced for me.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: https://github.com/mugendi/emoji-replace

**Comment by TimoKramer** [comment]
I'd like to try this.

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by TimoKramer** [comment]
still working on this one. but it's quite tough to wrap my head around all this stuff. @jarradh did you choose this specific library or is it random? it consists of two other libs and itself has quite rudimentary functionality...besides there are libs on cljsjs.

**Comment by jarradh** [comment]
random, feel free to choose whatever

**Comment by TimoKramer** [comment]
I don't get this js interop stuff and which library is used how. I am leaving this issue to someone else or a later me.

**Comment by Hackdom** [comment]
Jumping on board, hope all is well. I'm looking at this and seems easy enough without external libs already being implemented. I see that Status uses the react-native-emoji-picker which depends on the emoji-datasource's json. Is there a way to grab that json already being used directly in cljs?

**Comment by TimoKramer** [comment]
U+1F602

**Comment by matthieu-beteille** [comment]
Has this one not been done yet?

I'll give it a try. 👍
