### ISSUE TITLE
No quote is shown on nightly build if reply is sent from 0.13.0 release build 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8401]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  
UserA on release build replies to the userB on nightly build. UserB on nightly build sees only message from userA and no quote as it's a usual message sent and is not a reply. Same happens to userA on release build: no quotes shown if userB replies:

<img width="634" alt="Screen Shot 2019-06-11 at 11 26 52" src="https://user-images.githubusercontent.com/6584810/59260601-36fd3100-8c3c-11e9-9ff0-23ff29f4322e.png">

#### Expected behavior

users on release and on nightly can see quotes in replies

#### Actual behavior

- users on same version can see quotes in replies. 
- users on release version can't see quotes if reply is sent from nightly build
- users on nightly can't see quotes if reply is sent from release

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status installed from release 0.13.0 build
- join public chat and send a reply to some text message
- install Status from nightly, join same chat and check if quote (initial message to which user replied) is shown in the reply sent from release
- send reply in public chat from nightly build
- check that on release build you can see quote in reply sent from nightly

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 0.13.0 and nightly from June 11
[comment]: # 
- Operating System: Android and iOS

**Comment by rachelhamlin** [comment]
Removed from v0.14 release after conversation with Anna in Status. Breaking compatibility with previous versions when v1 is launched so this fix would be irrelevant then.

**Comment by flexsurfer** [comment]
v1 will be incompatible with v13
