### ISSUE TITLE
Error shown when enabling biometric auth for second account

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8404]
# Problem

Error shown when enabling biometric auth for second account

## Steps

1. create account -> profile -> dev mode -> enable biometric auth
2. logout
3. create brand new account -> profile -> dev mode -> enable biometric auth

![image](https://user-images.githubusercontent.com/28752642/59349074-6d60ac00-8d21-11e9-8fbb-349d89d58f9a.png)

**Comment by churik** [comment]
Should be rechecked after https://github.com/status-im/status-react/issues/10061 fix

**Comment by churik** [comment]
not relevant anymore on release 1.4
