### ISSUE TITLE
Wrong password error shown when signing typed message in Simpledapp on Mainnet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8405]
# Problem

Wrong password error shown when signing Typed message in Simple dapp while on Mainnet. Works fine on Ropsten

## Steps

1. open status -> create account
2. open simpledapp.eth -> transactions -> sign typed message

![image](https://user-images.githubusercontent.com/28752642/59349869-5e7af900-8d23-11e9-8b8c-d79bd8ec048d.png)

**Comment by rachelhamlin** [comment]
@asemiankevich is it only simple dapp? Or is it other DApps as well?

**Comment by asemiankevich** [comment]
i am not aware of any other dapp where i can test this on Ropsten / Mainnet unfortunately (

**Comment by rachelhamlin** [comment]
Have you ever seen the `Wrong password` error when typing in a mainnet DApp?

**Comment by asemiankevich** [comment]
nope, dont think so

**Comment by churik** [comment]
@rachelhamlin 
it is still valid, but I don't know real usecase (how to check this in DApps)
Does it make sense to keep it opened?

**Comment by StatusSceptre** [comment]
No harm keeping it open, we just don't need to worry about it unless it comes up with users.

**Comment by churik** [comment]
Not relevant anymore on release 1.4; error now chainId3 doesn't match selected chain.
