### ISSUE TITLE
No incoming messages in group chat for recovered account (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8416]
# Problem

Recovered account on my Android device does not see incoming messages in a group chat.

## Steps

1. on Device A (android) recover account with known seed 
2. on Device B (iphone) create brand new account
3. switch both to ropsten and add to contacts
4. create a group chat with 2 accounts
5. from device A send a message to group chat, make sure it is visible for Device B
6. from device B send a message to group chat, make sure it is visible for Device A

## Logs

1. logcat  https://drive.google.com/open?id=1HvOzWldQQK-yEqlV_rlM1q8GbF_3sxPz
2. geth.log https://drive.google.com/open?id=1iz1egd6zSArKr7SV1Hi_PhoZbq9HYjHD

## Notes

Blue bar does not fetch the messages, the message is not received neither after restart, nor after i force Fetch last 24h

android 7, xiaomi redmi 4
huawei p10 lite, android 8

![image](https://user-images.githubusercontent.com/28752642/59491095-f21d0880-8e8e-11e9-94c5-ed6bbaad8019.png)

![image](https://user-images.githubusercontent.com/28752642/59491097-f2b59f00-8e8e-11e9-9011-3c156c0ac7c7.png)

**Comment by asemiankevich** [comment]
@cammellos maybe you could take a look into this? I see some crashes in logs, not sure if this a reason

**Comment by cammellos** [comment]
thanks,

just to make sure, messages from B are not seen on A, is that correct?

for the account A, how many devices ( or installations) are around ?( i. e do you often recover)

**Comment by asemiankevich** [comment]
@cammellos 

> just to make sure, messages from B are not seen on A, is that correct?

yes, right

> for the account A, how many devices ( or installations) are around ?( i. e do you often recover)

difficult to count, a lot of times, i use this account for testing and it is my account i am using for chats in status. Ping me i can share the seed if needed

**Comment by cammellos** [comment]
that s likely the issue, we only sync max 3 devices, if you have many
running it will only pick 3, eventually it will settle if you stop using
them, but as soon as you recover it might target old devices ( it targets
the last 3 by activity, or that are paired with an active device)

**Comment by churik** [comment]
Closing as part of https://github.com/status-im/status-react/issues/9857
