### ISSUE TITLE
Translation is missing on Chats screen

### ISSUE THREAD

**Issue by trybeee** [status-im/status-react#842]
### Description

*Type*: Bug

*Summary*:  Translation of message content is missing on Chats screen during the sign up process.

![screenshot 2017-03-02 19 46 31](https://cloud.githubusercontent.com/assets/23836/23563573/19d091d6-fffc-11e6-8be6-fd25c38f006c.png)

#### Expected behavior
It should show the message content.

#### Actual behavior
It shows `[missing "en-US/command-text-confirmation-code" translation]`

### Reproduction

- Sign up with a new user 
- Proceed to step "enter your phone"
- Enter phone number
- Go back to Chats list

### Solution

*Summary*: Straightforward solution is to add translation under the key "command-text-confirmation-code" to every localization, but i think this is redundant since the contents of it is the same as text under the "confirmation-code" key.

Another solution is to change dispatcher of the messages with content-type "command-request" as it seems those messages doesn't need adding "command-text" prefix to the key name: https://github.com/trybeee/status-react/blob/develop/src/status_im/chats_list/views/inner_item.cljs#L33

### Additional Information

* Status version: 0.9.3

* Operating System: Android and iOS

#### Logs
Message itself:

```
{:same-author false,
 :message-id "1488510260032-ac032365-65e6-5720-8e54-1a4e2b9c459a",
 :content {:command "confirmation-code",
           :content "Thanks! We've sent you a text message with a confirmation code. Please provide that code to confirm your phone number"},
 :same-direction false,
 :clock-value 10,
 :from "console",
 :chat-id "console",
 :content-type "command-request",
 :timestamp 1488510260104,
 :new? false,
 :outgoing false,
 :to "me"}
```

**Comment by trybeee** [comment]
I don't see that bug in test version i've installed from Google Play Store though. 
That bug has been seen on app build from "develop" branch (head commit 041b5abfad48802f8108d5e47bece6391a3d6d1e)

**Comment by alwx** [comment]
@trybeee thanks for reporting!

However, the code you refer to no longer exists. `message-content` multimethod has been removed in this commit: https://github.com/status-im/status-react/commit/d6f43d32485fadaa743f3ac363a5c45a379cf719

It seems like you should sync your `develop` branch with our to make this issue gone.
