### ISSUE TITLE
bitcoincash:qqtuqpd7twp7cznjcr694yaegr2ejc009swz95f3v0

### ISSUE THREAD

**Issue by Amolrada2442** [status-im/status-react#8427]
# Problem

An overview of the background required to understand the problem.
A problem description.

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by annadanchenko** [comment]
@Amolrada2442 closing, as there is no explanation
