### ISSUE TITLE
Can't run ios develop build on iPad 5th generation

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#8428]
# Problem

When running latest develop on device "iPad (5th generation)", getting error:
<img width="578" alt="Screen Shot 2019-06-18 at 11 58 33 AM" src="https://user-images.githubusercontent.com/5786310/59668799-c917b300-91c1-11e9-8ea5-f24b99e55c74.png">

## Steps
- checkout latest develop (`c26572653f75e76292678a4aa0d625c401d936d2` at the time of writing)
- in separate terminals run:
`make run-ios-simulator`
`make react-native-ios`
`make run-ios SIMULATOR="iPad (5th generation)"`

**Comment by vkjr** [comment]
`iPad Air 2` works fine

**Comment by churik** [comment]
No support for IPad now (Status v1.0.1)
