### ISSUE TITLE
[Multi-Account] Build account settings for individual wallet 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8446]
### Description

*Type*: Feature

*Summary*: Build on #8348. Add the [`Account settings` screens](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Mobile-wallet?node-id=2559%3A33433). 

#### Expected behavior

When viewing a wallet, I can tap on `Account settings` to change the name and color of the wallet. 

![image](https://user-images.githubusercontent.com/15470435/59857610-2f8f0380-9371-11e9-81e5-434084379918.png)

#### Actual behavior

`Account settings` don't yet exist. Menu item is not tappable.

<img src="https://user-images.githubusercontent.com/15470435/59857723-6b29cd80-9371-11e9-8bcc-761f4b63add1.png" width=200/>

**Comment by flexsurfer** [comment]
blocked by https://github.com/status-im/status-go/issues/1635
