### ISSUE TITLE
Add support to switch networks

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-react#845]
### User Story

As a developer
I want to be able to switch networks 
So I can more easily develop DApps

### Description

*Type*: Feature

Typically when developing DApps, a developer uses his own private chain or a simulator.
Status inserts its own web3 object (as expected) into the dapp, however, this web3 object is connected to a different network than the development one.

### Solution

Add support to choose which network/node to use for development purposes.

- [ ] Support to specify a custom RPC (e.g from metamask http://i.imgur.com/pBLZav8.png)
- [ ] Support in the status dev api to specify this (e.g ```switch-node {"url": "http://my-machine-ip:8545"}```)

**Comment by commiteth** [comment]
Current balance: 0.00000000
Contract address: 0x9f529ce5dacaaa54cbf68cba546493478ca6e461
![QR Code](https://commiteth.com/qr/status-im/status-react/bounty/845/4a8c0cc846ef5ad65da0e885742ab41fe4cc2f766b9dfdf9f8f7eea0b2f0567b/qr.png)
[https://commiteth.com](https://commiteth.com)

**Comment by alwx** [comment]
@iurimatias 
https://github.com/status-im/status-react/pull/852
