### ISSUE TITLE
Screenshots disallowed on Android

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8454]
### Description

*Type*: Bug

*Summary*: While testing [PR #8425](https://github.com/status-im/status-react/pull/8425), @asemiankevich was unable to take a screenshot. Received message that it is not allowed by the organization. 

Would be good to investigate.

@asemiankevich is this still reproducible? Is it only on the wallet overview? 

#### Expected behavior

Screenshots possible on all devices

#### Actual behavior

Can't screenshot on Android.

**Comment by asemiankevich** [comment]
i need to try more, also i though we wanted to limit screenshots on recovery phrase screens

**Comment by bitsikka** [comment]
is Profile -> Preview Privacy Mode on?

This PR required an implementation in android which prevents screen capture globally if the setting is on
https://github.com/status-im/status-react/pull/8009

**Comment by asemiankevich** [comment]
@rachelhamlin i cant reproduce it anymore. also i was able to see that only in a PR, maybe some race condition was reached.
