### ISSUE TITLE
Investigate time to load token value

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8455]
# Problem

While testing PR #8425, @hesterbruikman found:

`It took suspiciously long to include the token value in the total asset amount. I didn't time it, so it could just be deceiving, but would appreciate if you can check if there's anything that can cause a significant delay.`

## Notes

Would be great to have QA verify this issue.
Following further reports, someone from engineering take a peak into why this might be happening. It's possibly a third-party issue that we can't fix.

**Comment by hesterbruikman** [comment]
After further investigation: The total amount shown initially is ETH only, after change to the currency setting, token value is added to the total amount.

**Reproduce**
- Check current total value on release > Wallet
- Recover existing account on nightly
- Go to Wallet
- Check total value
- Tap [...] > Set currency
- Select a currency 
- Set currency again to go to your original currency to compare ETH only and ETH + Token value


![Frame 3](https://user-images.githubusercontent.com/35233054/59915290-91587780-941c-11e9-9cd7-eebb4b197708.png)

**Comment by rachelhamlin** [comment]
Oh, I see! Thank you for clarifying. That means I've actually created two issues for this. I'm closing this one in favor of #8457.

**Comment by hesterbruikman** [comment]
After further investigation: The total amount shown initially is ETH only, after change to the currency setting, token value is added to the total amount.

**Reproduce**
- Check current total value on release > Wallet
- Recover existing account on nightly
- Go to Wallet
- Check total value
- Tap [...] > Set currency
- Select a currency 
- Set currency again to go to your original currency to compare ETH only and ETH + Token value


![Frame 3](https://user-images.githubusercontent.com/35233054/59915290-91587780-941c-11e9-9cd7-eebb4b197708.png)
