### ISSUE TITLE
[Multi-Account] Display collectibles in empty state

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8456]
### Description

*Type*: Feature

*Summary*: There are two assets represented in the wallet: tokens & collectibles. 

Currently, a user does not see the collectibles tab unless they own collectibles supported by the Status wallet.

The collectibles tab should be visible no matter what, with an empty state for users who don't own Status-supported collectibles.

#### Expected behavior

Collectibles tab persists for all users. If they don't own any Status-support collectibles, they see an empty state.

[Figma link](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Mobile-wallet?node-id=2840%3A55)

![image](https://user-images.githubusercontent.com/15470435/59913514-2acd5c80-9410-11e9-96b5-09bfc9ca33d3.png)

#### Actual behavior

The collectibles tab does not appear unless user has collectibles.

**Comment by flexsurfer** [comment]
already implemented

**Comment by hesterbruikman** [comment]
Just walking through older issues, I notice that on nightly, collectibles are only visible by default on the account overview screen, not on the individual account cards. What do you think, shall I reopen this issue or open a new one?

**Comment by flexsurfer** [comment]
new one would be better, thanks
