### ISSUE TITLE
[Multi-Account] Display token values for recovered account 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8457]
### User Story

As a user recovering an existing account, I want to see my total token value when I recover an account. 

### Description

*Type*: Bug

*Summary*: When a user recovers their account using seedphrase, the fiat total value of their wallet does not include their ERC20 tokens (only ETH).

The user can fix this by changing their currency and refreshing wallet, but it should display correctly by default.  

#### Expected behavior

- Recover account using seed phrase
- Open wallet
- See full fiat value of all of my holdings, incl. ERC20s, like so:

<img src="https://user-images.githubusercontent.com/15470435/59915275-27d46b00-9414-11e9-9677-c98d53215e0d.png" width=200/>

#### Actual behavior

- Recover account using seed phrase
- Open wallet
- See only fiat value of my ETH

**Comment by churik** [comment]
Can't reproduce anymore. 
@rachelhamlin please reopen if still relevant for you
