### ISSUE TITLE
Swipe back from "Sign in to status" (accounts list) leads to empty login form and at attempt to login - "Unknown status-go error"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8462]
### Description

*Type*: Bug
*Summary*:  all behavior is related to navigation between sign in screens, so I decided to keep it as one issue with two subsections
Navigation before sign-in is changed in last nightly in comparison with release 0.13.0 on IOS. 
1. Now it is possible to swipe back from the accounts list and this leads to "Sign in" screen with the empty login form. 

2. Also when you tap on your account in the account list, there are several differences:
2.1) focus is not set automatically to the password field
2.2) you can't swipe back from this page (IOS only)
2.3) if you tap on "Back" button, "Other accounts" link will be shown on left bottom corner (IOS only) (IOS only)

### Expected behavior
1) swipe back is not allowed (lime in 0.13.0) or log in to last used account is shown
2. All results below are related to screen, described in 2.
2.1) focus is set in Password field, the keyboard is opened **(probably it is a feature after merging keycard)**
![before_focus](https://user-images.githubusercontent.com/4557972/59933142-21acb180-9449-11e9-9a7d-4b39bf226d50.jpeg)

2.2) you can swipe back to accounts page (IOS only)

2.3) redirected back to accounts page

### Actual behavior
1)  empty login form, status-ge error at attempt to login on this screen
 ![ezgif com-optimize](https://user-images.githubusercontent.com/4557972/59932313-325c2800-9447-11e9-8621-92744fb31e04.gif)
2.1) focus is not set in Password field
![after_focus](https://user-images.githubusercontent.com/4557972/59933156-28d3bf80-9449-11e9-8b84-af1ca956207e.jpg)
2.2) you can't swipe back from this page (IOS only)
2.3) user is not redirected; "Other accounts" appears in left bottom corner.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/4557972/59933725-3e95b480-944a-11e9-94f8-ba351542d7ef.gif)

### Steps

(1) Status-go error
- create account
- log out
- tap on "other accounts"
- swipe back
- try to login

(2) Navigation between sign-in screens
- create account
- log out
- tap on "other accounts"
- tap on your account
- try to swipe back (2.2)
- tap on "Back" arrow (2.3)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 21.07.2019
- Operating System: Android, iOS

**Comment by churik** [comment]
@hesterbruikman would like to have your opinion of what should be fixed here.
Sorry for long descriptions, don't think there is some point to split it - but tell me if you think it should be.
Thanks!

**Comment by hesterbruikman** [comment]
Thanks for tagging @churik. Indeed looks like something introduced through Keycard.
https://github.com/status-im/status-react/issues/8032 is about to start to implement new 'unlock' screens in line with onboarding and including 6-digit passcode. 

Short answer for me would be to wait for a PR on that issue to see if the problem persist. But I'll look in more detail in Monday. On mobile only atm.

**Comment by churik** [comment]
not reproducible anymore
