### ISSUE TITLE
Docker Linux Desktop Image Build Recommendation/Guidance

### ISSUE THREAD

**Issue by NH603** [status-im/status-react#8467]
Hi All,

First off let me say, I want to commend you on building such a remarkable and well thought out project. I'm just scraping the surface, but your work on this is very impressive, so thank you for that.  

Secondly, as I'm still familiarizing myself with this repo and others, I wanted to get your guidance on the best approach for building my own docker image for this repo and the included Linux desktop app? With the help of some of your wiki pages and your shared guidance on past issues, I've successfully built and compiled the status-go repo and have that running in a VM as we speak. I've looked through some of your commit history and noticed that you had some "docker-build" scaffolding along with some builds for Linux, Base, Mac and Android. I've tried to mix and match that design with today's release configuration, but I've been unsuccessful so far. Again, I just started learning this project so I'm sure with time I can figure it out successfully, but I did want to reach out to the community to see if you had some good guidance to share with me to help get started with my own docker build for Linux desktop? Ideally, I'll probably incorporate a docker-compose type build here as well (I noticed you offered a good scaffolding example in "test/docker" to assist with setting up your status-go node and bootnode, but again, didn't notice any docker build for the status-react Linux desktop, other than past commit history.) 

Kindly let me know if you have any recommendations for how to best get started with compiling and running my own docker image for the Linux Desktop app? 

Thank you in advance for any guidance that you may be able to share.

**Comment by cammellos** [comment]
Thanks for your interest, the desktop app was discontinued, and it's now a separate project https://github.com/status-im/nim-status-client , they might able to assist you there.
