### ISSUE TITLE
Build status-react takes too much resources

### ISSUE THREAD

**Issue by speedyFixer** [status-im/status-react#8469]
# Problem

I'm working on some bounties and when I build the status-react repository my desktop computer gets stuck after I run make run-android.

It tooks almost 98% of CPU

My specs:
16 GB DDR4 RAM
Core i5-8400 2.80GHz x 6
SSD M2 NVME
Ubuntu 18.04.2 LTS

Do I need more hardware or is there a problem with the build tool? 

Anyone with the same problem?

**Comment by speedyFixer** [comment]
@PombeirP Could you help me? Any idea about what is going on? Thanks in advance!

**Comment by pedropombeiro** [comment]
@speedyFixer the machine specs sound OK. You might run out of RAM if you have other apps that use a lot of memory if you don't have a swap file, but otherwise, I don't see anything problematic.

**Comment by mandrigin** [comment]
@speedyFixer it uses a lot of resources to compile react-native itself, all the cores of my iMac Pro are 100% when I run `make run-android` or `make startdev-android-genymotion`.

**Comment by speedyFixer** [comment]
Hi, thanks guys, I "solved" this, closing any app when I execute those commands. Thanks.

**Comment by iurimatias** [comment]
closing as per the comment saying it's been solved
