### ISSUE TITLE
Very long Topic of the group chat blocks & prevents to scroll down and see chat settings

### ISSUE THREAD

**Issue by asotnicov** [status-im/status-react#8473]
# Description
As a user i would like to be able to scroll down the chat's settings popup even if the Topic is too long.

# Steps
_Type_: bug
- Open Status installed from nightly 2019-June-20, ver. 0.14.0 (2019062002).
- Navigate to Chats - +Start group chat 
- Choose few users and insert long topic text (over 350 symb)
- Create chat and try to open chat settings

**Actual**
- Very long Topic of the group chat blocks & prevents to scroll down and see chat settings
![image](https://user-images.githubusercontent.com/22766829/59979249-dc75b480-95ed-11e9-9db0-5f1a7146d429.png)

**Expected**
- Allow user to scroll down the popup or limit topic length with 100 symbols

CC: @annadanchenko

**Comment by churik** [comment]
Let's keep it open now due to "Add members" screen:
![photo_2020-02-26 17 17 43](https://user-images.githubusercontent.com/4557972/75364376-f160c100-58bb-11ea-80e7-fa90dd324a66.jpeg)

But in other places, it was fixed in nightly 26/02/2020

**Comment by churik** [comment]
fixed in #10099
