### ISSUE TITLE
An object of simpledapp.eth - Transactions is not fit on the screen

### ISSUE THREAD

**Issue by asotnicov** [status-im/status-react#8474]
# Description
As a user i would like to be able to see the full name of the transaction i going to make. Maybe some additional & important conditions are hidden.

# Steps
_Type_: bug
- Open Status installed from nightly 2019-June-20, ver. 0.14.0 (2019062002).
- Navigate to DApps - simpledapp.eth - Transactions 
- Scroll down and pay attention, that one transaction is not fit on the screen

**Actual**
- Transaction name doesn't fit on the screen
![image](https://user-images.githubusercontent.com/22766829/59979748-527d1a00-95f4-11e9-9d83-a48507aac304.png)

**Expected**
- Allow user to see full transaction name. Maybe we should cut and move to the new line part of the name.

CC: @annadanchenko

**Comment by churik** [comment]
Not relevant, as it used only for testing purposes
