### ISSUE TITLE
@mailman bot [epic/chat-api]

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#848]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
1. inject mailman's commands as local commands in all chats (currently only `location` command). Optionally just map `/location` to `@mailman location`
> jarradhope [18:32] 
maybe we can cheat with a  'thin mapping' for `/location` to `@mailman location`
https://status-im.slack.com/archives/internal-status/p1487608332006869
2. hide `@mailman` from contacts list

**Comment by annadanchenko** [comment]
testing

**Comment by annadanchenko** [comment]
Currently: /location command is shown in Console
Expected: /location shown only in chats (1-1. public, group chats)
