### ISSUE TITLE
[Multi-Account] Generate new account

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8480]
# Problem

Generate new account with multi-account key structure. 

This work is dependent on @gravityblast's work on the go API https://github.com/status-im/status-go/pull/1500

User creates brand new account on multi-account build, from scratch.

Design explorations are [here](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=1927%3A0).

Multiaccounts creation notes: https://notes.status.im/qEBnRFTaQ2SMAGZitN8_Fw

## Implementation

1) new onboarding, which generates whisper and wallet accounts
2) use new whisper account for messages
3) use wallet for all assets (dapps , chat, wallet)
4) show new wallet in accounts explorer

## Acceptance criteria
it's possible to create a new status account selecting it from 5 generated accounts, whisper key is different from wallet public key

**Comment by yenda** [comment]
I will ignore scenario 2 for this issue.

Before new onboarding is merged, I'll focus on `Moving underlying status-react data from single wallet to multiple` and add `Watch only address`, all other screens have blockers.

**Comment by flexsurfer** [comment]
hey @yenda could please elaborate what do you mean by `Moving underlying status-react data from single wallet to multiple`, thanks

**Comment by yenda** [comment]
Hey @flexsurfer my bad I meant account not wallet

**Comment by flexsurfer** [comment]
@yenda still, could you please describe what does it mean :)

**Comment by rachelhamlin** [comment]
Note: We want to move account storage to go side but @gravityblast is working on login API atm, so @flexsurfer is storing this in realm.

We can finish & test this issue, and then next week work with @gravity to move account storage to go. In tandem @flexsurfer can work on adding a watch-only account.
