### ISSUE TITLE
Cannot read property `substring` of null when start 1-1 chat via pasting public key or ENS name

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8489]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: when start 1-1 chat via + > Start new chat > Paste valid ENS username or public key - error `Cannot read property 'substring' of null` appears, but chat added

#### Expected behavior
no error

#### Actual behavior
![123234234](https://user-images.githubusercontent.com/4557972/60085623-eefd0480-9739-11e9-9d1d-a0715b9a7e5d.png)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click on + > Start new chat
- Insert valid ENS name or public key

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 24/06/2019
[comment]: # (Android or iOS.)
- Operating System: Mac OS, Linux, Windows

#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/3324487/Status-debug-logs.zip)

**Comment by asemiankevich** [comment]
@siphiuel @flexsurfer anything on this one?

**Comment by flexsurfer** [comment]
@asemiankevich no i think, we're focused on release
