### ISSUE TITLE
Null is not an object (evaluating `r.substring`) when trying to start new chat with empty contact code

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8492]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: error is shown at attempt to start 1-1 chat with empty or erased value. In both cases, error appears (in 1 case - `Null is not an object (evaluating "r.substring") `, in 2 -   `Null is not an object (evaluating "a.substring") `)

#### Expected behavior
1) validation error 
2) no error

#### Actual behavior
1) `Null is not an object (evaluating `r.substring`)`
2) `Null is not an object (evaluating `a.substring`)`
![IMG_6338](https://user-images.githubusercontent.com/4557972/60100431-03e99000-975a-11e9-8229-ffbe197d2722.PNG)
![image](https://user-images.githubusercontent.com/28752642/63587851-afbe2900-c5ad-11e9-99bd-5eedddb37b0e.png)

### Reproduction

**Scenario 1:**
- Open Status
- Tap on + > Start new chat
- Set focus on field with contact code  and submit empty value 

**Scenario 2:**
- Open Status
- Tap on + > Start new chat
- Set focus on field with contact code, input some value
- Erase value

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 25/06/2019
[comment]: # (Android or iOS.)
- Operating System: Android, iOS

#### Logs
[status_logs1.zip](https://github.com/status-im/status-react/files/3325355/status_logs1.zip)

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
I'm not sure what the appropriate error message is here.

I would suggest:

`Please enter a valid username or chat key.` (the term we're adopting for Whisper ID in v1)
