### ISSUE TITLE
New confirm recovery phrase screen

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#8499]
# Problem

Implement new confirm recovery phrase screen using drag-n-drop.

## Acceptance Criteria

Should look like in Figma https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A16259&viewport=-1860%2C217%2C0.3411950469017029

and work both on Android and iOS.

## Screenshots

<img width="289" alt="Screenshot 2019-06-26 13 24 07" src="https://user-images.githubusercontent.com/23836/60172854-3ce73a80-9816-11e9-93d2-93b8ff1a0222.png">
<img width="290" alt="Screenshot 2019-06-26 13 24 16" src="https://user-images.githubusercontent.com/23836/60172857-3ce73a80-9816-11e9-9187-fc5c0df16f3d.png">
<img width="291" alt="Screenshot 2019-06-26 13 24 25" src="https://user-images.githubusercontent.com/23836/60172859-3d7fd100-9816-11e9-859b-2ead8e007889.png">
<img width="287" alt="Screenshot 2019-06-26 13 24 41" src="https://user-images.githubusercontent.com/23836/60172861-3d7fd100-9816-11e9-8d6d-e285998dc97b.png">
<img width="288" alt="Screenshot 2019-06-26 13 24 55" src="https://user-images.githubusercontent.com/23836/60172864-3d7fd100-9816-11e9-8315-6052bcd67c39.png">

**Comment by dmitryn** [comment]
Depends on https://github.com/status-im/status-react/pull/8234
PIN screen could be taken from there.

**Comment by hesterbruikman** [comment]
Latest designs here: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A16367 Please flag if you don't have access.

A prototype is work in progress.

@dmitryn: @andmironov and design team just discussed removing the drag and drop to make implementation easier, as well as making the process less error sensitive for users. It is now "Select a word and tap on it’s correct position". Can you check it out and see if you want to keep the bounty label in that case?

**Comment by dmitryn** [comment]
@hesterbruikman now it's easier to implement, but i'd keep bounty on it anyway – it would be nice if someone will implement it while i'm busy with other parts.

**Comment by andmironov** [comment]
Hey, after a discussion, we decided to make this a bit more simple and remove the drag-and-drop and replace it with just taps.

Here's a video with how it should look:  https://www.dropbox.com/s/tpqc1sihu8xjdny/backup.mov?dl=0

Here are some notable things:
- you can select only one word at a time by tapping on it;
- if you have already selected a word and then tapped on another one, the other one gets selected;
- if you tap on an already selected word, it gets deselected;
- the error is shown for 1200 ms;
- the successful frame stays and the word disappears  if placed correctly;
- after an error is shown, the currently selected word gets deselected

**Comment by annadanchenko** [comment]
@hesterbruikman @rachelhamlin please, clarify term we need to use for seed/recovery phrase as both are used now in the new flow while we need to use only one. In older releases we are using "recovery phrase" term

**Comment by rachelhamlin** [comment]
~Let's continue with `recovery phrase` for v0.14.~

Wait - I realize this is not for release. Are we meant to be calling it seed phrase or recovery phrase in future @hesterbruikman?

**Comment by cammellos** [comment]
this looks stale, closing, feel free to re-open
