### ISSUE TITLE
Implement new screens for seed phrase back up 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8504]
# Problem

we have implemented new screens for seed phrase back up for keycard accounts https://github.com/status-im/status-react/pull/8490

we need this for basic non-keycard accounts too once nailed, probably after V1.

## Implementation

new screens for seed phrase back up for account with password

@hesterbruikman @dmitryn @guylouis

**Comment by StatusWrike** [comment]
➤ Hester Bruikman commented:

Update: we had a design review with design team. Swtiched from drag and drop to top to correct position as it's easier to implement and less error sensitive for users. Also translates better to Desktop.

**Comment by guylouis** [comment]
This is not related to keycard at all, so I remove the keycard label

It's a general feature of status, wether the account is a keycard one or not

The label was put in the past because Dmitry N. was supposed to do the implementation at some point

cc @rachelhamlin
