### ISSUE TITLE
Keyboard overlaps when signing transaction (android)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8506]
# Problem

Screen is overlapped with keyboard

## Steps

1. install status
2. faucet funds
3. in simpledapp request stt

![image](https://user-images.githubusercontent.com/28752642/60332431-7a2b0400-999f-11e9-9de4-528ef828a87d.png)

**Comment by flexsurfer** [comment]
can't reproduce, i'm not sure why keyboard is shown, because there is no active input

**Comment by asemiankevich** [comment]
it is shown when i want to enter password when sign transaction @flexsurfer , so on android it looks like that:
![image](https://user-images.githubusercontent.com/28752642/60647530-9c60ce00-9e46-11e9-9375-414b9f3b0eda.png)


and iOS looks like this:
![image](https://user-images.githubusercontent.com/28752642/60647565-af739e00-9e46-11e9-8334-9b13954af376.png)

**Comment by hesterbruikman** [comment]
Verifying, I have this issue as well on Android, Galaxy S10e, yesterday's nightly.
