### ISSUE TITLE
Can't send transaction from wallet, recipient is shown as unknown

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8507]
# Problem

Unknown recipient shown when pasting / scanning wallet address or selecting from contacts

## Steps

1. open status
2. go to wallet
3. choose recipient -> scan valid address and send txn

Repeat with copypasting address or select from contacts

Transaction is failed since recipient is shown as Unknown

![image](https://user-images.githubusercontent.com/28752642/60435852-46f0ab00-9c13-11e9-960f-710d63a55a3d.png)

**Comment by flexsurfer** [comment]
can't reproduce in the latest develop

**Comment by asemiankevich** [comment]
can't reproduce in nightly now
