### ISSUE TITLE
Commands list is partially hidden on iOS, /send command is not shown

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8508]
# Problem

/send command is not shown in suggestions on iOS

## Steps

1. open status on iOS
2. open 1x1 chat
3. tap command button

![image](https://user-images.githubusercontent.com/28752642/60437117-51607400-9c16-11e9-87ec-8e44b31bdea6.png)

**Comment by Serhy** [comment]
Regression from https://github.com/status-im/status-react/pull/8477 
However, it's OK with iPhoneX (iOS 12) view
