### ISSUE TITLE
Assets list is not fully scrollable on iOS

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8509]
# Problem

Can't fully scroll assets list when sending from chat, last item is cut

## Steps

- open status
- enable a lot of assets in wallet
- open 1x1 chat
- tap /send or /request
- scroll the list
- try to access the very last item in the list

![image](https://user-images.githubusercontent.com/28752642/60437437-0561ff00-9c17-11e9-9caf-961c8fc2cff6.png)

**Comment by Serhy** [comment]
Regression from https://github.com/status-im/status-react/pull/8477 
However, it's OK with iPhoneX (iOS 12) view
