### ISSUE TITLE
Asset selector is tappable when being on Recipient screen (iOS)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8530]
# Problem

Can tap asset selector and be redirected to it when being on another screen. 

## Steps:

1. open status
2. open wallet
3. tap Send
4. tap Specify recipient -> from contacts
5. tap the area where Asset selector should be 

Please check the video attached 

https://drive.google.com/open?id=1q5DImRpSBqI-q6vYUbh41QW9Jj0jNAwR

devices: iPhone 7 iOS 13, iPhone XR iOS 12.3.1

**Comment by churik** [comment]
Not relevant in Status v1.0.1
