### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME when accessing Deep links in Simple Dapp

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8532]
# Problem

Can't open [Deep Links] section in Simple Dapp

## Steps

1. open status
2. open simpledapp.eth
3. tap deep links -> tap a link

## Logs

[status_logs.zip](https://github.com/status-im/status-react/files/3367237/status_logs.zip)

**Comment by churik** [comment]
works now
