### ISSUE TITLE
[Onboarding] Enable fingerprint login during first-time setup

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#8533]
# Problem

As it stands now, the below piece of functionality:
  - fingerprint work done in https://github.com/status-im/status-react/pull/8127

is not integrated into the onboarding setup flow

## Implementation

Integrate https://github.com/status-im/status-react/pull/8127 with onboarding setup.

Figma screens for reference: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

**Comment by rachelhamlin** [comment]
Hey @siphiuel how much time are we looking at for this task?

**Comment by vitvly** [comment]
@rachelhamlin Less than a day i think, should be just integrating the existing fingeprint logic into new onboarding flow

**Comment by rachelhamlin** [comment]
@siphiuel cool, thanks. I'm putting it in Wrike for end of this week.

**Comment by rachelhamlin** [comment]
Are we all clear on requirements for this issue @siphiuel @flexsurfer? AFAIK, what was missing during onboarding was the native configuration of the biometrics. When you opt in, the device should run a confirmation. But—I'm not clear as to which biometrics we're collecting. 

In [this issue](https://github.com/status-im/status-react/pull/8127), it states that we're enabling both finger print & face ID, but only face ID appears to trigger when I opt in from settings on iOS. 

I'm also wondering if we need some reference to biometric login on the log-in screen? How does one choose between face or finger print?

**Comment by vitvly** [comment]
@rachelhamlin In https://github.com/status-im/status-react/pull/8903 there is a rule: if FaceID is present, use that, otherwise fingerprint. Not sure if this is correct.

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/issues/8966

**Comment by rachelhamlin** [comment]
I'm going to close this one in favor of #8966
