### ISSUE TITLE
Verify ens-name client side

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#8541]
### User Story

As a user, I want to make sure ENS name displayed in chat and profile has been verified.

### Description

*Type*: Feature

ENS name is sent as part of chat messages and account details. It is displayed as is and could be spoofed.
Proper solution involves checking the ENS validity client side. For performance reason it's been agreed that it should be done `status-go` side.

**Comment by rachelhamlin** [comment]
Do we need an equivalent version of this issue in the go repo?

**Comment by jeluard** [comment]
Good point! Actually this is a go only task. 
Maybe I should move this issue there? WDYT @adambabik @cammellos ?

**Comment by jeluard** [comment]
FYI @PombeirP

**Comment by rachelhamlin** [comment]
Duplicated this in status-go.
