### ISSUE TITLE
White Screen Suggestions Area / WebView

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#855]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to open `/browse` so that I can use dapps.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is a bug where the suggestions area is just white. It sometimes work but it happens too often to be just some network related bug. Especially when other webviews and brwosers can load the *same* url's without problem.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Tap on a DApp Chat item,see the dapp.
#### Actual behavior
[comment]: # (Describe what actually happened.)
Tap on a Dapp Chat item, see nothing.

![screen](https://cloud.githubusercontent.com/assets/2714786/23615495/e3f2fe18-0286-11e7-9265-3d13df77f203.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Browse to a DApp on contacts
- Tap on it.
- See white screen, cry.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3 (Gplay)
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by jarradh** [comment]
```
my guesses are maybe an injection problem
or maybe a memory/resources problem
or some weird blocking issue (???)
fyi i think it might happen on ios as well @roma at least its possible to load the webpage and not show main account, which is the other alternative i see on 
```

**Comment by jarradh** [comment]
thanks @rasom  for the special build, with this I can debug chrome windows.
I typically see a white screen when ther eis more than 4 instances of `about:` and there is typically 4 items of console logs while the page hands for 15+ seconds before the page will actually load.

<img width="635" alt="screen shot 2017-03-08 at 12 14 37 pm" src="https://cloud.githubusercontent.com/assets/2714786/23702304/ef08329e-03fa-11e7-9acf-d7a9e0a36856.png">
<img width="638" alt="screen shot 2017-03-08 at 12 12 31 pm" src="https://cloud.githubusercontent.com/assets/2714786/23702305/ef089c84-03fa-11e7-9d52-c1e00d196d99.png">

**Comment by annadanchenko** [comment]
experience same issue in 0.9.4 with Dapp (action house) and Wallet.
Screencast: https://www.screencast.com/t/29UcYLH4Kc
Log:
[20171003183758-logcat.txt](https://github.com/status-im/status-react/files/834671/20171003183758-logcat.txt)

**Comment by annadanchenko** [comment]
### Instabug
iOS
* 0.9.3 https://dashboard.instabug.com/applications/status/beta/bugs/136

Android:
* 0.9.3 https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/257
* 0.9.3 https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/254
* 0.9.0 https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/238

**Comment by annadanchenko** [comment]
White screen is shown when open Augur Dapp. 
On build for epic/ui-refresh (Android) http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-b7ef78.apk

[20173103145738-logcat.txt](https://github.com/status-im/status-react/files/885696/20173103145738-logcat.txt)
