### ISSUE TITLE
[Onboarding] Design touch-ups

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8551]
# Problem

- Notification icon is cut off at the bottom
- Navigation is too high, should be in header 44px from the top
- Keycard icon scales on Samsung Galaxy x and becomes unreadible
- There's noticeable padding on both sides of the image carousel when scrolling. The carousel should stretch the entire width of the screen.
- The dots below the carousel should be switched on/off in the same event - when page has changed. Currently it looks like when on scroll start they switch off and if the page changed, they switch back on.

**Comment by hesterbruikman** [comment]
Copied from https://github.com/status-im/status-react/pull/8234#issuecomment-510029198

**Welcome screens**
- The welcome screen cuts off the images and text, should not be this way (see screenshot below);
- on "Get yourself a key" screen, when tapping on "Generate a key" button, the image moves a few pixels down;
- If I tap "Generate a key" -> See the list of available account names -> tap "back" -> tap "Generate a key" again -> there's a bug: infinite spinner "Generating a key";

**Choose a key and name screen**
- Wrong layout (margins around screen title and the list) (see Figma);
- Bottom sheet (the one you see after tapping on "Learn more") has wrong margins (see Figma);
- Wrong margins In list items (see Figma);
- The line that separates the "Next" button is not 100% wide (see Figma);

**Select key storage screen**
- Slightly wrong layout (see Figma);
- List items have slightly wrong margins (see Figma);
- Bottom sheet (the one you see after tapping on "Learn more") has wrong margins (see Figma);

**Create password screen**
- The cursor follows the opening keyboard, overlays the text;
- The line that separates the "Next" button is not 100% wide (see Figma);
- The typeface of the password is too big;
- The margin around the "Next" button is too big (see Figma);

**Enable fingerprint**
-   I have an iPhone X, why am I seeing this?;
- The "Sync using mobile data" bottom sheet appears here. Does not make sense, I think we should show it after the setup is complete, maybe after the second launch of the app;

**Comment by flexsurfer** [comment]
1) image is cut
![image](https://user-images.githubusercontent.com/11790366/63937021-20f85300-ca6a-11e9-8689-ea8634b5422b.png)

2)labels overlap
![image](https://user-images.githubusercontent.com/11790366/63937031-25bd0700-ca6a-11e9-9e79-c5e3930b7089.png)

**Comment by andmironov** [comment]
Also, here are some issues in the recovery flow:

- Header too high;
- Toolbar (with "Next" button) is far away from keyboard;
- Word count is cut;
- Error message covers header;
- In general a lot of margins are wrong, please check the mockup

![IMG_9744](https://user-images.githubusercontent.com/3115606/64256304-dbd19680-cf2b-11e9-9305-99013daf5d4a.PNG)

**Comment by vitvly** [comment]
@andmironov apologies for confusion, I've created a separate issue for recovery-related bugs: https://github.com/status-im/status-react/issues/8911
