### ISSUE TITLE
[Maybe Later] for notifications setting in onboarding does not disable notifications  

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8554]
# Problem

Tapping `Maybe later` does not make effect, so notification setting will be enabled no matter which option i select. This applies only for Android devices.

![image](https://user-images.githubusercontent.com/28752642/60972345-c0cd1680-a32e-11e9-9e14-0c36231b2ef5.png)

## Implementation

Tapping `Maybe later` does not enable notifications. Notifications settings are off for Status app in device settings.

**Comment by rachelhamlin** [comment]
On iOS, when I choose `Maybe later`, I still see this pop-up shortly after onboarding: 

![IMG_5084](https://user-images.githubusercontent.com/15470435/66204035-c9b95400-e6a1-11e9-8b54-86720f5b4dab.PNG)
