### ISSUE TITLE
no push notification shown if send message in 1:1 between 0.13.0 release and nightly

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8555]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: no pn is shown if send message from 0.13.0 in 1:1 chat to user with nightly build. same if user from nightly sends to 0.13.0 release. For both cases when app is on background ios/Android and when app is not running on Android. 

#### Expected behavior

[comment]: # (Describe what you expected to happen.)
push notification is shown if message was sent in 1:1 chat
#### Actual behavior
no push notification is shown
[comment]: # (Describe what actually happened.)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- user1 installed nightly and user2 installed 0.13.0 release
- 2 users add each other to contacts, both have password saved
- user1 moves app to background
- user2 sends text msg in 1:1 chat with user1
- check if user1 gets push notification

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version:  0.14.0 nightly from july 10 and 0.13.0 release
- Operating System: Android 6,9 and iOS 12.3

**Comment by rachelhamlin** [comment]
Perhaps we should leave this one and #8401 out of release since we are breaking compatibility for v1? We can fix it in v1 - wdyt @annadanchenko @flexsurfer @yenda?

**Comment by flexsurfer** [comment]
if we break compatibility for v1 we don't need to fix it at all, that's why i suggest to don't waste resources on it, but we'll have this bug in 14 release then

**Comment by rachelhamlin** [comment]
Removing after conversation with Anna in Status.
