### ISSUE TITLE
Last message jumps up after chat is opened

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8556]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: after chat screen is opened input filed overlaps with last message, so message is half-visible. After  this last message "jumps up", so it's fully visible. It happens in each chat type.

when chat opened:
![Screenshot_20190710-173857](https://user-images.githubusercontent.com/6584810/60985641-18bf4980-a33e-11e9-9370-3628a1cbea6d.png)

a second later after chat is opened
![Screenshot_20190710-173907](https://user-images.githubusercontent.com/6584810/60985655-1eb52a80-a33e-11e9-9bca-0d09a1cc6147.png)

![jump](https://user-images.githubusercontent.com/6584810/60985815-7a7fb380-a33e-11e9-96db-235899038e9d.gif)

#### Expected behavior

Chat screen shows all messages and nothing is moving on the screen if no new messages received
#### Actual behavior
last message jumps up after chat screen is opened

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- join public chat with message and open it
- look at last message in the chat and if it moves on the  screen 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly july 10
- Operating System: Android and iOS

**Comment by asemiankevich** [comment]
also visible with [Add to contacts] bar.

**Comment by flexsurfer** [comment]
introduced here https://github.com/status-im/status-react/pull/8498
