### ISSUE TITLE
QR Code Scanning Addresses doesn't scan Commiteth

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#856]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to scan a qr code so that I can send eth to an address.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Commiteth displays a comment with the address in QR code  as you can see here: status-im/status-react/issues/854 . However when using the wallet send command the QR code does not register.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I open the wallet, type number and press send, i scan the qr code and i'm done.

#### Actual behavior
[comment]: # (Describe what actually happened.)
I open the wallet, type number and press send, i face camera at QR code, nothing happens.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Request ETH via /faucet
- Open Wallet
- Type in 0.5 and tap Send
- Stare at your phone trying to read a qr code

I have also generated a QR Code myself with the correct data and tested it against Status.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3 (Gplay)
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by jarradh** [comment]
Actually QR scanning is broken within Status.
I tried generating own qr codes of 
ethereum:0x0cf800ae3235bc13698e7c616662d282e8603db0
![0x](https://cloud.githubusercontent.com/assets/2714786/23655319/d6493a6c-0334-11e7-8625-8460aadb0b1e.png)

and
ethereum:0cf800ae3235bc13698e7c616662d282e8603db0
![1](https://cloud.githubusercontent.com/assets/2714786/23655322/da432f38-0334-11e7-8070-f20344b52f2d.png)

**Comment by rasom** [comment]
So... the first QR from the comment above is not handled properly on Android (while it works on iOS), as far as i understand it represent "ethereum:0x0cf800ae3235bc13698e7c616662d282e8603db0" string but not in UTF8... literally when i compare "ethereum:0x0cf800ae3235bc13698e7c616662d282e8603db0" string with results of QR scanning it returns false but my eyes see the same strings.

When I tried to generate the same QR I got
![qr-code](https://cloud.githubusercontent.com/assets/2364994/23671779/1de0875a-0375-11e7-82f0-5504be9fac17.gif)
and this QR can be handled on android

**Comment by rasom** [comment]
There was a bug, the application didn;'t return to webview after scanning, will commit fix soon. But QR generated by Commiteth can be scanned.

**Comment by jarradh** [comment]
amazing, thanks @rasom !
