### ISSUE TITLE
[Keycard] option icon is cut on Android (5.2" screen)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8561]
# Problem

Icon is cut on some screens, for ex 5.2" screen Android device. Could be more cases.

![image](https://user-images.githubusercontent.com/28752642/61107821-757b4b00-a489-11e9-9491-b9b3b9e4c197.png)

## Steps

1. install status
2. follow onboarding flow until [Select key storage] screen

Keycards are planned to be used with android devices , so good to have pixel perfect screens here.

**Comment by bitsikka** [comment]
I might have broken it in one PR(in which I was careless about changing global used code related to icon) and fixed it in another(fixed it when I realized the mistake). I can't see this problem anymore.

**Comment by vitvly** [comment]
@asemiankevich can you still reproduce it on nightly?

**Comment by asemiankevich** [comment]
@siphiuel good call, its fine now
