### ISSUE TITLE
Build v1.0 banner & modal to highlight breaking change

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8566]
### User Story

As a user, I want to receive a heads up about what I can do to prepare for breaking changes coming in the public release (v1.0) later this year, so that I don't lose any of my funds.

### Description

*Type*: Feature

*Summary*:
In v1.0, we're forcing users to create new Status 'accounts' on our new key structure - separating the Whisper ID and wallet ID. No Whisper data (contacts, messages) from a beta version of Status can be recovered.

A user _can_ recover their Ethereum address & any funds associated by recovering their seed phrase. Any user that owns an ENS name must have the seed phrase of the associated address in order to recover that as well.

In our final beta release, v0.14.0, we'll notify users of these impending changes. Users who have lost their seed phrase should transfer funds to another wallet ahead of v1.0.

#### Expected behavior

Banner and modal alert users that they need to have their seed phrase in order to recover their wallet + ENS name when v1.0 is launched.

[Figma designs](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=2591%3A22425)

- Banner should persist across all tabs (chat, wallet, etc.).
- If the user taps, the modal is opened.
- Once the user closes the banner or modal, it is gone unless they delete and re-install.

Note: Minor copy changes might be required. Mention of sticker market in list of `What's new` depends on whether that work will be included in this pending release. @rachelhamlin to follow up.

#### Actual behavior

No warning to users exists yet.

**Comment by jakubgs** [comment]
Should this warning banner contain a link to a more detailed description of the reasoning behind the changes?

**Comment by rachelhamlin** [comment]
It's a good idea @jakubgs. I can work with @j-zerah on a blog post about why we're going through all this and we can add a link.

**Comment by bitsikka** [comment]
I'm working on this.

@rachelhamlin Given that the banner/modal will be short lived, do the text copies have to be translation copies(as opposed to hardcoded inline [not even sure if we ever do inline hardcoded text @yenda? maybe that's a bad practice])?

cc @jinhojang6

**Comment by flexsurfer** [comment]
@bitsikka  this change will be only in release branch (will be created soon), so it can be done as translation copies
