### ISSUE TITLE
Can't locate tooltips by e2e tests

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8567]
***Type***: Bug

***Summary***:  Tooltips are not present in XML of page (e2e tests also don't see the text from those tooltips)
`Wrong password` (on login and transaction sigh in views) and `Recovery phrase is invalid` tooltips - are those which affected by issue
But, for instance, `Not enough ETH for gas` and `Invalid format. Must be enode....` tooltips have no issues (red background as expected) 

#### Expected behavior
'Wrong password' tooltip with red background

#### Actual behavior
'Wrong password' tooltip with white background

<img width="344" alt="Screenshot 2019-07-15 at 15 54 16" src="https://user-images.githubusercontent.com/8749671/61217681-e2584480-a718-11e9-9d97-24fe702cc2c5.png">
<img width="337" alt="Screenshot 2019-07-15 at 15 54 29" src="https://user-images.githubusercontent.com/8749671/61217682-e2584480-a718-11e9-835b-083381537979.png">

### Reproduction

- Open Status
- Tap `Access key` to navigate to recovery phrase view
 - Put cursor into password field
**Actual result:** `Required field` tooltip with white background
**Expected result:** `Required field` tooltip with red background
- Recover any account with funds
- Navigate to `Wallet` -> `Status account` -> `Send transaction`
- Try to send transaction but sign it with the wrong password
**Actual result:** `Wrong password` tooltip with white background
**Expected result:** `Wrong password` tooltip with red background

### Additional Information
- Status version: Develop 0.14.0  (2019071505)
- Operating System: Android and iOS

**Comment by Serhy** [comment]
Marked with `medium-priority`, because e2e tests are failing due to those tooltips are not present in page xml too

**Comment by churik** [comment]
Still relevant.
Blocker for e2e 5686, partially 5363, 5463

**Comment by churik** [comment]
Very important for e2e tests, blocks a lot of checks
