### ISSUE TITLE
Hide 'add account' option in wallet

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8568]
### Description

*Type*: Feature

*Summary*: Multi-account UI has been introduced in the nightly. It includes a panel to `Add account`, which in the future will allow users to import additional wallets into Status. These flows are not built yet. We want to hide this UI element but release the other changes in beta v0.14.

#### Expected behavior

`Add account` panel is hidden/removed.

#### Actual behavior

`Add account` panel is visible.

<img src="https://user-images.githubusercontent.com/15470435/61222544-cf427600-a712-11e9-8fe4-33f125f5c688.png" width=220/>

**Comment by StatusWrike** [comment]
➤ Rachel Hamlin commented:

The work is done. Waiting for release branch to merge.
