### ISSUE TITLE
Distributed or decentralised

### ISSUE THREAD

**Issue by ShalokShalom** [status-im/status-react#857]
Is status distributed or decentralised?

![centralized-decentralized-distributed](https://cloud.githubusercontent.com/assets/6344099/23627170/f3138cc2-02af-11e7-85d6-0cb318c2576d.jpg)

**Comment by jarradh** [comment]
Status uses Ethereum so maybe you'd find this link suitable to your question:

https://www.reddit.com/r/ethereum/comments/2spqdj/is_ethereum_decentralized_or_distributed/

**Comment by ShalokShalom** [comment]
So it still use some kind of a server-client system?

This Link does not make it clear to me. Anyway, all over your website is the term decentralised used, i simply wanted to asked, because these 2 terms often get mixed.

**Comment by jarradh** [comment]
No... there is no client-server. Are you kidding me?
It's distributed. If you know this argument you also know that decentralised and distributed is debated. 

I don't understand why the link isn't clear to you? 
This is not suitable as an issue, come join our slack and chat about it in #status
