### ISSUE TITLE
Hide 'Chat settings' from ENS usernames section

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8570]
### Description

*Type*: Feature

*Summary*: We recently moved ENS registration to a native flow inside Status, and built support to display ENS names in chat by default.

There is a security blocker on status-go that prevents ENS display from being releasable.

Thus we need to hide the ENS chat setting for beta release v0.14.

#### Expected behavior

`ENS usernames` section in the profile offers registration flow, but not `Chat settings`.

#### Actual behavior

`Chat settings` feature is visible from `ENS usernames`.

![image](https://user-images.githubusercontent.com/15470435/61224678-eaaf8000-a716-11e9-9766-ee917e3615e1.png)

**Comment by StatusWrike** [comment]
➤ Rachel Hamlin commented:

The work is done. Waiting for release branch to merge.

**Comment by annadanchenko** [comment]
@rachelhamlin it seems that hiding Chat settings feature in ENS usernames does not solve the issue  completely. User will see ENS name of another user in 1:1 chat title (if they are in contacts of each other):
![Screenshot_20190718-144231_Status PR](https://user-images.githubusercontent.com/6584810/61458825-b5e83680-a96b-11e9-9999-a52d008bfa0d.jpg)

![Screenshot_20190718-144254_Status PR](https://user-images.githubusercontent.com/6584810/61458820-b1238280-a96b-11e9-8c01-a104b041e348.jpg)

**Comment by rachelhamlin** [comment]
@annadanchenko taking a look. Did you set your name to show previously? 

Any idea why this is happening @jeluard?

**Comment by flexsurfer** [comment]
i believe this should be reverted in @jeluard PR https://github.com/status-im/status-react/pull/8586

**Comment by jeluard** [comment]
@flexsurfer Why? 8586 is about custom names, not ENS

@rachelhamlin This one is just removing the UI, if you already had a ENS name set it will still show up. #8569 is fixing it

**Comment by flexsurfer** [comment]
@jeluard summary says "Do not display ENS name anymore (neither in profile nor chat)." is it something different?

**Comment by annadanchenko** [comment]
got it, so this issue is just to hide ui setting and not about using/showing ens name(s) in other part of the app

**Comment by flexsurfer** [comment]
correct
