### ISSUE TITLE
Impossible to get current geolocation in Status Dapp browser

### ISSUE THREAD

**Issue by jrainville** [status-im/status-react#8573]
### User Story

As a developer, I want `navigator.geolocation.getCurrentPosition` to work in the Status Dapp Browser so that we can use maps with the user's current location.

### Description

*Type*: Bug

*Summary*: Experienced the issue in Status Teller Network, using `navigator.geolocation.getCurrentPosition` (browser API to get the user's current location) doesn't work in Status' Dapp browser, whereas it works in Chrome, Opera, Firefox, etc.

#### Expected behavior

When calling `navigator.geolocation.getCurrentPosition` in the Dapp code, absolutely nothing happens.

#### Actual behavior

On calling the function, it should display a small popup or window asking "do you want to share your current location". Pressing yes gives the position of the user to the code, pressing no returns an error. Currently, the callback just never returns because the popup never appears.

#### Testing in the Teller Network

- Open Status
- Make sure you are in Rinkeby (Profile > Advanced > Network)
- Go to Dapp browser
- Go to https://status-im.github.io/status-teller-network/rinkeby/#/offers/map
- Nothing appears, it just stays at the default location

-> If you instead test in a browser with metamask, it will actually work

#### Testing with a really basic app

- Create a small app (can be just an html file)
- Follow this guide https://developers.google.com/maps/documentation/javascript/geolocation
- Test in Status

### Solution

*Summary*: I don't know, probably just need to enable the popup to show

### Additional Information

- Status version: 0.13.0
- Operating System: Android and iOS (Also experienced by @iurimatias and @richard-ramos

**Comment by jeluard** [comment]
@jrainville Could you see anything special in debug logs?
See https://status.im/developer_tools/debug.html

**Comment by jrainville** [comment]
Just tried debugging and there is sadly nothing in the logs.

**Comment by jeluard** [comment]
@jrainville Just tried on iOS emulator and it works as expected. A popup confirmation appears, then location is shown.

**Comment by jeluard** [comment]
Also while both should be fine, it might makes sense to test with `preview privacy mode` on.

**Comment by jrainville** [comment]
> Just tried on iOS emulator and it works as expected. A popup confirmation appears, then location is shown.

Interesting. I'm going to check with my colleagues. I think @richard-ramos had the same issue as me, but he had an Android too. Maybe @iurimatias , who has an iOS, can make it work.

**Comment by richard-ramos** [comment]
I have the same issue (using Android). I also tried by changing the privacy setting but the pop-up did not display

**Comment by jrainville** [comment]
Iuri just tested and he doesn't have the issue on iOS.

So it seems it's an issue that might only affect Androids

**Comment by corpetty** [comment]
In regards to this issue and V1 audits, this can be done outside of the audit. Current implementation asks for permission from user, the display just doesn't show (on actual devices) and shows on emulators so there is a bug here, not a security issue.

**Comment by cammellos** [comment]
Not sure if it's still an issue, can't test using the link as it returns a 404, feel free to re-open if that's still an issue.
