### ISSUE TITLE
Account recovery & registration issue on Mac Desktop

### ISSUE THREAD

**Issue by rbnpercy** [status-im/status-react#8596]
After registering my initial account on the stable release Mac desktop client, I was given my 12 word recovery key, which I screengrabbed and kept in a safe place.

After trying to recover my account with my 12 word key, the desktop client actually created a new account altogether with a new contact code.

I tried again, and the same thing happened - 2 new accounts with new contact codes, for both times I tried to recover my initial account.

After chatting with Corey, I downloaded the nightly build of the desktop client, and again went through the account recovery, **with my initial recovery phrase**, and it recovered one of the new accounts the desktop client created.  I tried my recovery phrase on the mobile app (iOS), and it again recovered the same (newer) account that the nightly desktop build recovered.

@corpetty

**Comment by corpetty** [comment]
I think this is a status-react-desktop issue... there might be a discrepancy between key generation when creating an account on that and recovering the same seed phrase. Looking into it.

**Comment by corpetty** [comment]
@vkjr can you point me in the direction of where we do the key derivation based on given seed phrase for both account generation and account recovery?  I have a hard time dissecting the desktop code.

**Comment by corpetty** [comment]
Was not able to reproduce on a linux VM.  Steps attempted:
- Downloaded beta client from website
- created new account
- backed up seed phrase
- logged out
- imported same account as new account

This resulted in the same account. I then tried this with the latest nightly and recovered the same account again.

**Comment by rbnpercy** [comment]
I now can't replicate the issue myself, using the nightly build it recovers my newest account (the one that was newly generated, but I'll be sticking with).

I haven't tried to replicate the issue for Ubuntu / Win, so I think it was just an OSX problem.

**Comment by vkjr** [comment]
@corpetty, desktop uses the same login/recover screens as mobile do, so part of code you are looking should be the same as for mobile. I believe this is the part of code you are looking for - https://github.com/status-im/status-react/blob/develop/src/status_im/accounts/recover/core.cljs#L28
