### ISSUE TITLE
Going back on webview / on a web page.

### ISSUE THREAD

**Issue by Smokyish** [status-im/status-react#860]
### User Story

As a user, I want to be able to go back on a web page/DApp so that i don't get thrown out of browse everytime i hit Back.

### Description
The Back function is quite commonly used when browsing the internet, people are used to it, and not having it can sometimes disrupt the user experience.

*Type*: Feature

#### Expected behavior
When browsing a web page/DApp, and i want to go back to a previous page, i hit the back button on my Android phone and go back to the previous page that i was browsing.

#### Actual behavior
When browsing a web page/DApp, and i want to go back to a previous page, i hit the back button on my Android phone to get back to the previous page that i was browsing, upon hitting back, i get thrown out of browsing, back to the Chats/Contacts page.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open ie. Gnosis
- Open ☰ / Menu
- Select API
- You're now on the API Docs, the DApp menu and UI is no longer visible, hit Back to go back to the DApp.
- Thrown back to Chats/Contacts.

### Solution
There should be some way to go back on sites, i've only tested with one Android device, so this can be caused by a different keyboard or device or something.

### Additional Information
* Status version: 0.9.3
* Operating System: Android

**Comment by annadanchenko** [comment]
Related Instabug reports: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/307
