### ISSUE TITLE
Empty screen when tapping on sticker

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8605]
# Problem

I tapped on a sticker I received and saw this:

![image](https://user-images.githubusercontent.com/15470435/61617472-a6fece00-ac62-11e9-9323-f09b318848e3.png)

## Implementation

Ultimately tapping on a sticker was meant to open the pack in the sticker market.

In the interest of time (v0.14 + Julien leaving) I think it's best that we disable tapping on a sticker for now.

## Acceptance Criteria

Nothing happens when I tap on a sticker in chat.

**Comment by flexsurfer** [comment]
@rachelhamlin @annadanchenko let's try to reproduce this in mainnet, maybe it was sticker from old contract or some test sticker with wrong data, so it can't be reproduced with mainnet stickers

**Comment by rachelhamlin** [comment]
I am not able to reproduce on mainnet at the moment @flexsurfer
