### ISSUE TITLE
Update account storage from Realm to go

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8609]
### Description

*Summary*: Placeholder issue corresponding with (and blocked by) [#11 in /status-protocol-go](https://github.com/status-im/status-protocol-go/issues/11).

#### Expected behavior

[comment]: # (Describe what you expected to happen.)

#### Actual behavior

**Comment by cammellos** [comment]
@rachelhamlin this is currently not blocked by https://github.com/status-im/status-protocol-go/issues/11, we decided (unless someone has a strong opinion against), to move it to `status-go` instead, so can be picked up now. I believe @dshulyak might be already working on it.

**Comment by yenda** [comment]
@cammellos @rachelhamlin confirmed that @dshulyak is working on it and I am integrating it in status-react, currently paused waiting for multiaccount work to be merged in status-react as it introduce lots of changes in login flow

**Comment by StatusWrike** [comment]
➤ Rachel Hamlin commented:

Should be closed by PR #8725

**Comment by rachelhamlin** [comment]
@yenda are the bugs you're working on wrt realm still relevant to this issue? Can we capture what you're working on in new ones and close this? 🙏

**Comment by yenda** [comment]
We can keep this issue open for now, right now I am not working on this, first I need these status-go issues to be solved:

https://github.com/status-im/status-go/issues/1578
https://github.com/status-im/status-go/issues/1579
https://github.com/status-im/status-go/issues/1581
https://github.com/status-im/status-go/issues/1582

Then I will create an issue to implement them based on how many status-go PRs it takes and remove realm entirely

**Comment by rachelhamlin** [comment]
@dshulyak I know you're assigned to all these go issues, but just want to confirm - are they WIP? adding to wrike.

**Comment by flexsurfer** [comment]
YES!

**Comment by rachelhamlin** [comment]
Wooooo!
