### ISSUE TITLE
Disable beta warning for v1

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8616]
# Problem

When a user launches a beta version of Status, they receive a warning about the app being in beta. We should disable this warning for version 1. 

## Implementation

Remove beta warning pop-up from launch.

## Acceptance Criteria

Beta warning no longer appears.

## Notes

I would prefer we don't merge this change into develop until we are close to a v1 cut.

**Comment by flexsurfer** [comment]
@asemiankevich could you confirm this is done?

**Comment by asemiankevich** [comment]
@flexsurfer i havent seen this beta warning since it was removed several weeks ago.
