### ISSUE TITLE
Disable stickers in testnet

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8624]
# Problem

It's possible to send test stickers from ropsten network

## Implementation

It should be not possible to select and send stickers from testnets

**Comment by rachelhamlin** [comment]
Adding my notes:

A sticker pack I 'purchased' on testnet can be used as normal on Mainnet, which undermines the economic utility of the feature.

We will still need the option to test stickers on testnet in the future. For beta release v0.14, the easiest thing to do is disable them on testnet.

For future, we can use special builds for testnet use.
