### ISSUE TITLE
Term 'Recovery phrase' should be used instead of 'seed phrase' for release 0.14.0

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8626]
# Problem

In previous releases up to 0.13.0 we were using term 'recovery phrase' for 12 words used to recover an account. In the release 0.14.0 because of re-design some parts of the app use term 'seed phrase' for the same entity. It should be fixed so old users have consistent experience.

## Implementation

Places to change seed phrase to recovery phrase:
1. Account explorer:
![Screenshot_20190724-120215](https://user-images.githubusercontent.com/6584810/61785029-25966f80-ae0b-11e9-9ffd-a7e71752b113.png)

2. v1 warning
![Screenshot_20190724-120250](https://user-images.githubusercontent.com/6584810/61785094-419a1100-ae0b-11e9-92cd-b6c6d57e63bd.png)

## Acceptance Criteria

"Seed phrase" term is not shown on any screen in the app. Term "recovery phrase" is used instead of "seed phrase"

**Comment by rachelhamlin** [comment]
Any instance of `seed phrase` in this build should be updated to `recovery phrase`.
