### ISSUE TITLE
Fixes to v1 warning

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8629]
# Problem

We have a few issues that need fixing in the v1 notification screen:

1) Any instance of `seed phrase` must be changed to `recovery phase`.
2) The red background warning about phrase backup is easy to miss on small screens.
3) We need to point the links on the page to the right URLs.

[Figma link](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=2591%3A22548)

## Implementation

- Update spacing between image & header 
- Update copy in top paragraph (awaiting changes in Figma):
`Status is taking important steps toward a more secure, censorship resistant network. Thanks for being part of beta; we're sure you'll love v1.0!`
- Route `Learn more` to a link redirect that can be pointed at the blog post when ready. With help from @jakubgs 
- Link `#status` to https://get.status.im/chat/public/status
- Link `Twtitter` to https://twitter.com/ethstatus
- Warning text in the red box says `recovery phrase` rather than `seed phrase`.
- Move `Got it` button to bottom of page, rather than leaving it fixed on screen, to increase odds of people seeing the full text. 

## Acceptance Criteria

- Less spacing at top of screen
- Copy reads the following at top:
`Status is taking important steps toward a more secure, censorship resistant network. Thanks for being part of beta; we're sure you'll love v1.0!`
- Links work.
- Warning text in the red box says `recovery phrase` rather than `seed phrase`.
- `Got it` button is below the scroll, not fixed.

## Notes

The blog post won't be published until next week. Can start draft to use as a placeholder today.

**Comment by jakubgs** [comment]
Here's a redirect: https://v1-changes-explained.status.im/.
Created in https://github.com/status-im/infra-misc/commit/969b7705.
For now it just points at https://status.im/, we can update it later.

**Comment by rachelhamlin** [comment]
Thanks @jakubgs!
