### ISSUE TITLE
Several transactions are shown for outgoing token transaction

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8638]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: mentioned in https://github.com/status-im/status-react/pull/8552#issuecomment-511362722.
Several issues are introduced by  https://github.com/status-im/status-react/pull/8552:

### 1. If you send tokens from your account there are two transactions instead of one.
The first transaction is without amount (`... HND`) in "Pending" state, the second transaction is actually what is expected:
<img width="226" alt="hnd" src="https://user-images.githubusercontent.com/4557972/61874856-b2aff600-aee9-11e9-8eb3-53ea6a26d1ca.png">
These transactions are not updated for me inside transaction details until manual reopening app. So, in ~20 min I still see the same, and no confirmations if I tap on `1 HND`  transaction.
On receiver side 125 confirmations for this transaction.
**All fine after relogin.**

### 2. Instead of 1 transaction after buying sticker pack 2 are shown, second is "0 ERC20"
**Steps:**
- switch to Ropsten
- make sure that have ETH and STT on Ropsten
- buy sticker pack

<img width="244" alt="Monosnap 2019-07-25 15-19-06" src="https://user-images.githubusercontent.com/4557972/61877644-b5ade500-aeef-11e9-8bfc-55b68b839fec.png">

### 3. Transactions in tokens are doubled if you send two transactions (one in tokens, one in ETH) in a row
**Steps:**
- send a transaction in tokens
- send a transaction in ETH
- check transaction history.
Transaction in tokens appears twice in history (in green initial transaction, in red - what appears after sending ETH)
<img width="228" alt="dsda" src="https://user-images.githubusercontent.com/4557972/61878116-b135fc00-aef0-11e9-82be-667da59b1135.png">
**All fine after relogin.**

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 25/07/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
@rachelhamlin @annadanchenko release-blocker?

**Comment by rachelhamlin** [comment]
How much effort is this to fix @yenda?

**Comment by yenda** [comment]
1. unknown I don't know the cause, will investigate
2. not really a bug it's the best effort we talked about, this is the transfers that happened in the transaction, you spend STT and you receive a token
3. I think I know what it is should be less than an hour if I find a quick fix

**Comment by rachelhamlin** [comment]
Ah, I see. Okay, if there's a quick fix, great. If not, leave it.

**Comment by churik** [comment]
@rachelhamlin @yenda sorry for the confusion, it is not in release branch yet as @yenda said. 
So can be postponed.

**Comment by rachelhamlin** [comment]
Oh—better. Drop for now!
