### ISSUE TITLE
Make Back up seed phrase notification in wallet tappable and add display logic

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#8650]
_Type_: Feature

_Summary_: The Wallet > Account explorer shows a notification [Back up your seed phrase] 

1. Notification needs to be tappable. When tapped it needs to open the back up seed phrase flow
2. Notification needs to appear as soon as the user has assets in their wallet

_Already implemented: Notification disappears once the user has completed the back up seed phrase flow._

3. BONUS: the [!] icon need to be updated to tiny-warning icon @andmironov can you point to or provide the asset?

**Comment by rasom** [comment]
> Notification needs to appear as soon as the user has assets in their wallet 

just to double check, we don't want to show it unless user has some assets in their wallet, right?

**Comment by hesterbruikman** [comment]
> just to double check, we don't want to show it unless user has some assets in their wallet, right?

Correct. Intention is to show the notification in:
**Profile** - at all times until backup process has been completed. 
**Wallet** - only when the user has assets in _any one of the accounts that is derived from the root key_.

For example:

1. I create a multiaccount (root key incl chat and wallet)
2. I do not back up seed phrase > _no_ notification in wallet
3. I receive funds on initial account in wallet > notification in wallet
4. I generate a new account derived from root key > notification in wallet
5. I move all funds from the initial account to new account > notification in wallet



cc @andmironov @errorists

**Comment by rasom** [comment]
@hesterbruikman it should work as you described in #9253
