### ISSUE TITLE
Mailserver Request range error

### ISSUE THREAD

**Issue by jfarid27** [status-im/status-react#8653]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to fix the mailserver request errors so that we don't see the error messages.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When connecting to a status go node that I host via docker, I keep seeing a mailserver request error. I'm not sure what's causing this.

#### Expected behavior

[comment]: # (Describe what you expected to happen)

No error.

#### Actual behavior

[comment]: # (Describe what actually happened)

An error message logs on screen. It seems to be fine and I seem to be getting new messages. I'm just not sure why this is an issue.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step)

Start a docker status go node, and connect to it via the mobile app. After a while you'll see this message pop up when using the app.

### Solution

Don't have one.

### Additional Information

![Screenshot_20190727-115321](https://user-images.githubusercontent.com/1673206/61996754-f0398e00-b065-11e9-8358-1e76eacf8f1d.jpg)

![Screenshot_20190727-115924](https://user-images.githubusercontent.com/1673206/61996758-07787b80-b066-11e9-9f61-368b7e4a0565.jpg)

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
...
```

**Comment by cammellos** [comment]
@jfarid27 are you running the latest status-go docker image? If not, could you try upgrading? Let me know and thanks for reporting the issue

**Comment by jfarid27** [comment]
@cammellos Just bumped to v0.31.0-beta.0 and things seem ok for now. I'll close and reopen if the problem persists.

**Comment by jfarid27** [comment]
Still seeing this issue. It looks like on first load after the mailserver is running it's totally fine, but after closing the app for a while and coming back, the error pops up. I don't really have good numbers on what messages were lost, but it looks like I can't fetch messages once the range error happens. I took a look at the docker logs and I'm seeing this message as well.

![Screenshot from 2019-08-29 10-05-55](https://user-images.githubusercontent.com/1673206/63947309-ab2dc080-ca44-11e9-86ab-51715af75491.png)
