### ISSUE TITLE
Duplicated own messages when 'Fetch 24h history' in public chat after release upgrade 0.13 -> 0.14 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8658]
***Type***: Bug

*Summary*: After upgrade from release 0.13 to release 0.14 version -> if to tap 'Fetch 24h history' in public chat (with messages sent in v0.13) then your own messages are duplicated 

No messages duplication in 1-1/Group chats
And all fine for upgrade from 0.12.2 -> 0.13

#### Expected behavior
No messages duplication upon 'Fetch 24h history' 
 
#### Actual behavior
Duplicated own messages when 'Fetch 24h history' in public chat after release upgrade 0.13 -> 0.14 

![123123123](https://user-images.githubusercontent.com/8749671/62039527-8c979800-b200-11e9-97ff-e63382885af0.gif)

### Reproduction

- Install release 0.13 app version
- Open Status and create new account
- Join public chat (e.g. `#avoid-duplication`)
- Send one or more text/emoji messages 
- Upgrade to 0.14 release version
- Open Status and login to the account
- Navigate to public chat with messages you've sent
- Tap `...` chat options menu -> `Fetch last 24h history`

### Additional Information

- Status version: Develop/Release 0.14 upgraded from 0.13 version
- Operating System: Android and iOS

#### Logs
TBD..

**Comment by churik** [comment]
Not relevant in Status v1.0.1
