### ISSUE TITLE
No chats on 'Chats' view if to clear entered search term in 'Search' chat input

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8662]
***Type***: Bug

***Summary***: If to clear "Search" input on Chats view we hide search input (along with 'Cancel' button). Along with that, we give no ability to cancel chat searching and only white screen keep staying on 'Chats' view. So there are no chats that were present on the 'Chats' view are shown and available for open. 
After app re-launch everything is fine and chats are displayed as expected

#### Expected behavior
`Search input` and `Cancel` are shown on 'Chats' view after clear Search input with the entered keyword in Search input

#### Actual behavior
No `Search input`, no `Cancel`, no list of chats are shown on 'Chats' view after clear Search input with the entered keyword in Search input

![32132131231211111111](https://user-images.githubusercontent.com/8749671/62044115-cd94aa00-b20a-11e9-9b8b-39ecf765499f.gif)

### Reproduction

- Open Status and create new account
- Join any public chat
- Navigate back to main 'Chats' view
- Pull-down the screen so 'Search' input appears
- Enter any keyword in Search input
- Clear the 'Search' input

### Additional Information

- Status version: Delelop/Release 0.14.0
- Operating System: Android and iOS

**Comment by annadanchenko** [comment]
@rachelhamlin v1 scope

**Comment by flexsurfer** [comment]
@Serhy cant reproduce

**Comment by rachelhamlin** [comment]
Me neither. I entered a search term, hit cancel, and saw my chats list again. iOS

**Comment by Serhy** [comment]
Can reproduce with develop builds.
Maybe last step was unclear (sorry for that). So
> Clear the 'Search' input

Means tap `<-` backspace button on keyboard to clear chracters in the search input field.

Video of the issue: https://drive.google.com/file/d/1JZd-siJiSciU_74w7OtJV4-Qw_JvSk52/view
