### ISSUE TITLE
No browsing Dapp history after switch to different network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8663]
***Type***: Bug

*Summary*: There is no browsing history on DApp screen present after user switched on a different network from the network where browsing history were saved.
So if user browsed Dapps in Mainnet and then switches on to POA network - there won't be any record.
This agreed to be fixed out of https://github.com/status-im/status-react/pull/8594 from where this issue introduced.

#### Expected behavior

Browsing Dapp history kept disregard the network user is switching to

#### Actual behavior
History of Dapps browsed is not present after user switches on a different network 

![33333333](https://user-images.githubusercontent.com/8749671/62046201-084d1100-b210-11e9-994e-02ec418b54a2.gif)

### Reproduction

- Open Status and create new account
- Navigate to Dapps view -> open `dap.ps` 
- Navigate back to DApp view and confirm 'Discover Dapps https://dap.ps is present in 'Recent' history
- Switch to POA network ( or any other network)
- Login to account
- Navigate to DApps view and check the Recents is not empty

### Additional Information

- Status version: Develop 0.14 (nightly 2019072614)
- Operating System: Android and iOS

**Comment by churik** [comment]
Can't reproduce on nightly 26/02/2020
