### ISSUE TITLE
Cannot Capture Profile Image

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#867]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to take a photo of myself so that I have a picture in my profile.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In the profile page I can edit my picture and take a photo. however after capturing the image I cannot save my profile as the arrow is greyed out.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Capture photo, and press blue arrow

#### Actual behavior
[comment]: # (Describe what actually happened.)
Cpature photo, tap disabled arrow... nothing

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Login
- Open Drawer
- Open Profile
- Tap on edit profile button 
- tap on edit image button
- tap on capture
- take photo
- stare at grey arrow and be confused.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] allow profile to be saved.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3 (Gplay)
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
