### ISSUE TITLE
Increase number on 'unread' messages indicator to +99

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#8676]
As a user I want to be able to see if the number of unread or new messages in a chat make it worthwhile to open the chat to read up on messages or ignore them in case there are too many.

The current logic and representation of unread/new messages is not achieving the goal. Often all chats are shown to have +9 messages and it is not clear how to get rid of this indicator; As a result it continues to draw attention and causes a lot of frustration.

While we look for smarter solutions to display and interact with unread/new messages, we want to introduce this quick fix to help people decide whether a chat is worthwhile opening.

### Current
TheChat list shows the number of unread/new messages in a blue circle, if the number of messages is >9, it is displayed as +9.

### Expected
- The chat list shows the number of unread/new messages in a blue circle. If the number of messages is >99, it is displayed as +99,
- The bubble should grow horizontally to accommodate the number with sufficient padding of 6 on both sides

[Link to Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=5332%3A27331)

<img width="375" alt="Home Tab" src="https://user-images.githubusercontent.com/4932774/66902879-bb542c00-f001-11e9-8af1-5a0f5e74e0d8.png">

**Comment by hesterbruikman** [comment]
@rachelhamlin @annadanchenko @errorists would love your thoughts or a thumbs up on this issue as a quickfix to 'unread messages'.

Related issues: 
https://github.com/status-im/status-react/issues/6375
https://www.wrike.com/open.htm?id=359077270
https://github.com/status-im/status-react/issues/7497

**Comment by rachelhamlin** [comment]
I give it a thumbs up for a quick fix. 🙂
We can revisit all this slack in messaging after V1 release is cut.
