### ISSUE TITLE
Cover the list of test cases with e2e automates tests

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8677]
Create automated tests for the next test scenarios from TestRail:
- [x] https://ethstatus.testrail.net/index.php?/cases/view/6208
- [x] https://ethstatus.testrail.net/index.php?/cases/view/5738
- [x] https://ethstatus.testrail.net/index.php?/cases/edit/6202

**Comment by yevh-berdnyk** [comment]
> * [ ]  https://ethstatus.testrail.net/index.php?/cases/view/6208

The last step was moved to https://ethstatus.testrail.net/index.php?/cases/view/6220
