### ISSUE TITLE
Test if strings from en.json are used in the code and create a list of unused strings

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8693]
# Problem

Some stings from https://github.com/status-im/status-react/blob/develop/translations/en.json are not used in the app anymore but they are present in all translations files and eat space. For example, 
```
   "phone-e164": "International 1",
```

 We need some test that would detect unused strings and lists them in a bug report. This test also can become part of nightly suite to detect similar issues in the future

**Comment by annadanchenko** [comment]
comment from @yenda "one could search for ":t/%s" in the codebase, sort, uniq but I think there is some programmaticaly generated labels so there will be exceptions"

**Comment by annadanchenko** [comment]
Other non-used stings:

-  "address-explication": "Your public key is used to generate your address on Ethereum and is a series of numbers and letters. You can find it easily in your profile",

**Comment by annadanchenko** [comment]
@yevh-berdnyk any estimations on when it can be done?

**Comment by yevh-berdnyk** [comment]
@annadanchenko I'm planning to accomplish it tomorrow
