### ISSUE TITLE
String "Nobody sees your name unless you provide it" should be changed/removed?

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8694]
# Problem

In the phrase from  "about-names-content" we say
`Your identity is secure and private by design. You get a locally generated cryptographic keypair. The name and image are a readable version of this. They are unique. Nobody can pretend to be you. Nobody sees your name unless you provide it.`
Statement `Nobody sees your name unless you provide it` is wrong because everyone can see 3 words generated username and in this context we speak about this name.

Possible solutions would be 
1. to introduce ENS names concept here and explain a bit how user can get such name 
or
2. Remove this string

Would like to get feedback on actual solution, especially from @rachelhamlin and @hesterbruikman

**Comment by hesterbruikman** [comment]
Good catch! Maybe we can add "Nobody sees your `real world` name unless you provide it"?

Else I'd prefer option 2. I believe introducing ENS in Onboarding would be too much for newcomers unfamiliar to ENS and not essential at time of onboarding

**Comment by rachelhamlin** [comment]
Ditto - I like `real name`.
