### ISSUE TITLE
Duplicate strings in translations

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8698]
# Problem

There are duplicate entries with same content but different keys in https://github.com/status-im/status-react/blob/develop/translations/en.json and the rest of non-English translations files in https://github.com/status-im/status-react/blob/develop/translations . 

For example: for word `Cancel` there are 3 keys:
- "browsing-cancel"
- "cancel"
- "message-options-cancel"

Full list of 41 duplicate entries: https://docs.google.com/spreadsheets/d/14tQQM8GKQn3KC3_jYNdqJs7Mh7Rj8VjNjcQbr49OfP0/edit?usp=sharing

## Implementation

1. https://github.com/status-im/status-react/blob/develop/translations/en.json should be cleaned up to have only one key for same content. If multiple keys for same content are used in the app then it should be adjusted to use same key in the app. Please, use https://docs.google.com/spreadsheets/d/14tQQM8GKQn3KC3_jYNdqJs7Mh7Rj8VjNjcQbr49OfP0/edit?usp=sharing to locate duplicates and write down the key that remains, so it simplifies testing
2. the rest of files in https://github.com/status-im/status-react/blob/develop/translations should be also cleaned up and strings removed from en.json should be removed for these files too

## Acceptance Criteria

1. No duplicates (same content for different keys) in https://github.com/status-im/status-react/blob/develop/translations/en.json
2. The rest of files in https://github.com/status-im/status-react/blob/develop/translations contain same keys as en.json and do not contain extra keys
3. No lost strings in the app UI

**Comment by churik** [comment]
should be fixed after merge https://github.com/status-im/status-react/pull/9932

**Comment by Serhy** [comment]
#9932 merged. Closing the issue.
