### ISSUE TITLE
Keycard sign up/sign in UI/UX fixes

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#8701]
Creating a separate issue for design fixes mentioned here https://github.com/status-im/status-react/pull/8618/ for them not to get lost:

- If I tap the card before I've chosen "Keycard" as storage, I get a popup "Connection with the card has been lost"';
- If I try to set up a card, which has been already been used, I see an alert "This card has already a miltiaccount on it, please login...". I think the copy has to be changed and we should offer a "Login" button, as the only way to log in from here is to tap "back" several times;
- There is no way (i did not find it) to log in without a password (with keycard + passcode);
- PUK code and Pair code typeface
should be monospaced (Roboto Mono) to make it easy to tell whether it's a zero or an "O";
- Maybe let's add spaces to the PUK code? 068091011194 -> 0680 9101 1194;
- The keyboard is not shown on seed phrase word confirmation screen right away;
- The text not centered on seed phrase word confirmation screen;

Something else regarding the Keycard setup. I've noticed that on smaller screens there's no room for both the list of upcoming steps and the keycard + phone image. I think both are important.

What I suggest is that instead of this:
<img width="1334" alt="Screen Shot 2019-08-01 at 12 58 47" src="https://user-images.githubusercontent.com/3115606/62284403-39ba1c80-b45c-11e9-81c0-4cd1721cbe7e.png">

We do this:
<img width="886" alt="Screen Shot 2019-08-01 at 12 59 01" src="https://user-images.githubusercontent.com/3115606/62284430-45a5de80-b45c-11e9-8d00-1f75490df43f.png">

**Comment by dmitryn** [comment]
Some of the issues were already resolved in https://github.com/status-im/status-react/pull/8618
i'm marking them with checkboxes:

- [ ] If I tap the card before I've chosen "Keycard" as storage, I get a popup "Connection with the card has been lost"';
- [ ] If I try to set up a card, which has been already been used, I see an alert "This card has already a miltiaccount on it, please login...". I think the copy has to be changed and we should offer a "Login" button, as the only way to log in from here is to tap "back" several times;
- [ ] There is no way (i did not find it) to log in without a password (with keycard + passcode);
- [x] PUK code and Pair code typeface
should be monospaced (Roboto Mono) to make it easy to tell whether it's a zero or an "O";
- [x] Maybe let's add spaces to the PUK code? 068091011194 -> 0680 9101 1194;
- [ ] The keyboard is not shown on seed phrase word confirmation screen right away;
- [x] The text not centered on seed phrase word confirmation screen;
- [x] Something else regarding the Keycard setup. I've noticed that on smaller screens there's no room for both the list of upcoming steps and the keycard + phone image. I think both are important.
