### ISSUE TITLE
Unable to sign in  or restore account if password cointains ' symbol (quotemark)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8702]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: using password with quotemark `'` leads to error:
```
08-05 06:24:58.791  4332  4732 E GoLog   : failed to set key pragma
08-05 06:24:58.796  4332  4391 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.login.callback/login-success
08-05 06:24:58.810  4332  4391 E ReactNativeJS: ERROR [status-im.multiaccounts.login.core:125] - failed to login failed to set key pragma
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: console.error: "ERROR [status-im.multiaccounts.login.core:125] - failed to login failed to set key pragma", stack:
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: error@345.js:96:29
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: hca@7201:45
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: a@7303:53
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: c@91168:136
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: b@91163:24
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: <unknown>@33320:26
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: <unknown>@33605:52
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: Jb@11905:35
08-05 06:24:58.820  4332  4392 E unknown:ReactNative: gc@3075:47
```
 and user automatically logged out

#### Expected behavior
can use password with  ' symbol

#### Actual behavior
error

### Reproduction

- Open Status
- Try to create account with password that contains `'`

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nigthly 04/08/2019. 
- Operating System: Android, iOS

#### Logs

Full test and logcat can be found [here](https://app.saucelabs.com/tests/b6eec76897c7489a871cef95ca8b53cf#30)

**Comment by churik** [comment]
@cammellos @rachelhamlin imo should be fixed in scope of V1

**Comment by cammellos** [comment]
@dshulyak I can check on our side (`status-protocol-go`), but are you hashing the password on yours (browsers etc), as if not that's likely the reason? 

Because breaking changes are ok,we could also hash it before sending it to status-go (so that Login will get the hashed password), sounds safer and we don't really have to worry about this anymore, but not sure if there are other unintended consequences (I can't see any)

**Comment by rachelhamlin** [comment]
Thanks @churik. Can we begin flagging v1 release issues with the label? cc @annadanchenko

**Comment by dshulyak** [comment]
@cammellos you are right it is passed as it is

**Comment by corpetty** [comment]
> we could also hash it before sending it to status-go (so that Login will get the hashed password), sounds safer and we don't really have to worry about this anymore

very much this.

**Comment by yenda** [comment]
@cammellos I can assign the issue to myself and do the hashing on status-react side or do you still plan to do it

@corpetty can we use sha3 for web3.utils?

**Comment by cammellos** [comment]
up to you, is to be implemented in status-react, i am on some other tasks
now, but can pick up later if you have your plate full

**Comment by yenda** [comment]
I can take it np
