### ISSUE TITLE
NFC setting on/off is not detected dynamically

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#8703]
Verified on Oneplus 6, and Samsung J5

When trying to onboard on a android phone with Keycard, the user goes through three screens 
i. Select Key storage
ii. Store your key on Keycard information screen 
iii. "Hold card to the back of your phone" (if NFC is on), or "Turn NFC on to continue" (if NFC is off)

Problem: if the user NFC is off, and is prompted to turn it on on step ii, then he turns it on, the change is not detected by Status. This is quite disturbing and could make the user abandon onboarding.

Remark on reproduction: it seems the detection is done at step i. (user must go back to step i for Status to detect a setting change), although it should be done when in step iii. dynamically

@dmitryn 
@asemiankevich

**Comment by asemiankevich** [comment]
@guylouis yes, as i said - the flow is now more a happy path , there will be more issues . I suggest to retest and fix everything when the implementation is done.
