### ISSUE TITLE
if NFC is off,  user is not prompted to turn NFC on at login

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#8704]
Tested on oneplus 6 

- user has a keycard multiaccount 
- NFC is turned off 
- user tries to login 
- user is asked to tap his Keycard and is not prompted to turn his NFC on 

cc @asemiankevich

**Comment by asemiankevich** [comment]
@guylouis yes, as i said - the flow is now more a happy path , there will be more issues . I suggest to retest and fix everything when the implementation is done.
