### ISSUE TITLE
A problem occurred! Multiaccount's and realm db passwords does not match when multitapping Next button

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8710]
# Problem

`A problem occurred! Multiaccount's and realm db passwords does not match` error shown when multitapping Next button while creating new account

![image](https://user-images.githubusercontent.com/28752642/62536972-03174400-b858-11e9-82ac-e08adeeae1d8.png)

## Steps

- open status
- start creating new account
- tap Next button on Password confirmation screen several times

Check out the video https://drive.google.com/open?id=1YwK6avjV1Jli6cM5wi7GANs5g9QvkAAU

**Comment by churik** [comment]
Fixed in https://github.com/status-im/status-react/pull/8815 so is not reproducible on nightly 27/08/2019
