### ISSUE TITLE
Copy update Transaction overview Contract interaction

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#8711]
# Problem
When I sign a contract the label on the Transaction overview screen describes 'Contract Interaction'. As a user this does not inform me about what to do. In combination with the limited information available when signing contracts, current copy can add to a feeling of distrust.

This state of the transaction overview screen comes up, for example, in the case of 'Buying a license' for Teller Network.

## Current
Copy 'Contract interaction'

## Expected
Copy 'Sign contract'

#### Current title
![Screenshot_20190806-133659_Status](https://user-images.githubusercontent.com/35233054/62537837-b466ab80-b851-11e9-9039-b45590fdaa5b.jpg)

**Comment by errorists** [comment]
just my 0.02, **Sign contract** gives me the creeps, maybe some personal bias but most of the time it's someone f*ing you over

**Comment by rachelhamlin** [comment]
How about `authorize`?

**Comment by errorists** [comment]
+1 to `authorise`

**Comment by hesterbruikman** [comment]
Best alternative. I don't see it as 100% accurate yet :/ `Authorize` to me indicates a future action. While it is actually an immediate transaction, just not one that includes funds. 

Other options:
Confirm contract
Approve contract
... More suggestions?

**Comment by rachelhamlin** [comment]
I'm not opposed to `sign` myself. It's a cryptographic standard, not limited to blockchain. Put together with `contract`, it's a rather unfortunate combo, but it's also _accurate_.
