### ISSUE TITLE
"Enable notifications" and "Enable fingerprint" screens are shown each time  on account creating

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8712]
### Description

*Type*: Bug
*Summary*: "Enable PN" and "Enable fingerprint" screens are shown on each account creating, should only once after installing app (so after first 
cannot be reproduced on nightly 05/08/2019, so appears on latest 06/08/2019

#### Expected behavior
"Enable notifications" and "Enable fingerprint" screens are not shown

#### Actual behavior
"Enable notifications" and "Enable fingerprint" screens are shown after login

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new account
- Log out
- Create another account

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 06/08/2019
- Operating System: Android, iOS

**Comment by asemiankevich** [comment]
@churik @yevh-berdnyk is it sill a case? I can't reproduce it in today's nighlty

**Comment by churik** [comment]
it is gone in nightly 22/08/19
