### ISSUE TITLE
Fix false failed tests and implement new tests

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8716]
`test_privacy_policy_is_accessible` - remove lastest check for Privacy policy

`test_copy_transaction_hash` - apparently sometimes it fails to copy value (also the Paste in chat to check whether value copies might be redundant here. Lets just check clipboard like self.driver.get_clipboard())

`test_open_user_profile_using_deep_link` - remove "Send transaction" check (we disabled this feature for now)

**Implement:** 
https://ethstatus.testrail.net/index.php?/cases/view/5330
https://ethstatus.testrail.net/index.php?/cases/view/6222
https://ethstatus.testrail.net/index.php?/cases/view/5392
https://ethstatus.testrail.net/index.php?/cases/view/6221

**Comment by yevh-berdnyk** [comment]
@Serhy 

> `test_privacy_policy_is_accessible` - remove lastest check for Privacy policy

updated
> `test_copy_transaction_hash` - apparently sometimes it fails to copy value (also the Paste in chat to check whether value copies might be redundant here. Lets just check clipboard like self.driver.get_clipboard())

get_clipboard() method is not supported by the Appium version which is currently used in the project
> `test_open_user_profile_using_deep_link` - remove "Send transaction" check (we disabled this feature for now)

updated
> **Implement:**
> https://ethstatus.testrail.net/index.php?/cases/view/5330
> https://ethstatus.testrail.net/index.php?/cases/view/6222

I was not succeeded in receiving push notifications on SauceLabs emulators so skipping those tests for now
> https://ethstatus.testrail.net/index.php?/cases/view/5392

was implemented earlier
> https://ethstatus.testrail.net/index.php?/cases/view/6221

added test_app_on_background_by_back_button
