### ISSUE TITLE
Search icon does nothing on Chats screen 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#872]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to search in chats so that I can find my previous conversations that contain a "search term". If feature is not yet implemented for Chats screen then the icon should be disabled or not visible

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If tap on Search icon on Discover or on Contacts screen then search field is shown, so user can type the search term. On Chats screen if tap on Search icon then nothing happens

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Search field is shown and user can type in it. 
Or
If feature is not yet implemented for Chats screen then the icon should be disabled or not visible

#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing happens
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Chats screen
- Tap on Search icon in the top right corner

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Fix it

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3
* Operating System: Android and iOS
* Instabug: https://dashboard.instabug.com/applications/status/beta/bugs/105

#### Logs
Log from Instabug issue: 
(user_steps) 27-01 07:53:28.820  Shake in: UIViewController
(user_steps) 27-01 07:53:27.668  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:53:27.084  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:53:24.416  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:53:22.253  Top View: UIViewController
(user_steps) 27-01 07:53:22.252  Selector: cancelButtonPressed: by (IBGButton) in IBGScreenshotVC
(user_steps) 27-01 07:53:22.250  Touch: (IBGButton) in IBGScreenshotVC
(user_steps) 27-01 07:53:16.330  Top View: IBGScreenshotVC
(user_steps) 27-01 07:53:16.320  Selector: resignFirstResponder by ((null)) in IBGPromptVC
(user_steps) 27-01 07:53:16.318  Selector: resignFirstResponder by ((null)) in IBGPromptVC
(user_steps) 27-01 07:53:16.314  Touch: (UITableViewCellContentView) in IBGPromptVC
(user_steps) 27-01 07:53:09.377  Shake in: IBGPromptVC
(user_steps) 27-01 07:53:08.775  Shake in: IBGPromptVC
(user_steps) 27-01 07:53:08.670  Top View: IBGPromptVC
(user_steps) 27-01 07:53:08.508  Top View: IBGMainWindow
(user_steps) 27-01 07:53:08.483  Selector: resignFirstResponder by ((null)) in UIViewController
(user_steps) 27-01 07:53:05.840  Swipe: ((null)) in UIViewController
(user_steps) 27-01 07:52:55.918  Swipe: ((null)) in UIViewController
(user_steps) 27-01 07:52:54.035  Swipe: ((null)) in UIViewController
(user_steps) 27-01 07:52:47.531  Touch: Find a bug or have a suggestion? Just ~shake~ your phone!(RCTText) in UIViewController
(user_steps) 27-01 07:52:38.461  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:37.609  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:36.709  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:35.741  Touch:  (RCTView) in UIViewController
(user_steps) 27-01 07:52:35.091  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:34.342  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:33.158  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:32.423  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:31.773  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:29.989  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:23.235  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:22.485  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:21.551  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:20.184  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:19.025  Selector: textFieldEndEditing by (RCTTextField) in UIViewController
(user_steps) 27-01 07:52:19.016  Touch: (RCTImageView) in UIViewController
(console_log) 27-01 07:52:17.199  Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
(user_steps) 27-01 07:52:17.084  Selector: textFieldBeginEditing by (RCTTextField) in UIViewController
(user_steps) 27-01 07:52:17.032  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:15.748  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:14.714  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:14.030  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:52:12.680  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:11.546  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:10.162  Touch: (RCTView) in UIViewController
(user_steps) 27-01 07:52:03.343  Swipe: ((null)) in UIViewController
(user_steps) 27-01 07:51:57.589  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:51:56.171  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:51:50.036  Swipe: ((null)) in UIViewController
(user_steps) 27-01 07:51:47.400  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:51:44.999  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:51:42.781  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:51:41.164  Touch: (RCTImageView) in UIViewController
(user_steps) 27-01 07:51:31.626  Touch:  (RCTText) in UIViewController
(user_steps) 27-01 07:51:27.358  Touch:  (RCTText) in UIViewController
(user_steps) 27-01 07:51:21.904  Touch: Connect(RCTText) in UIViewController
(user_steps) 27-01 07:51:19.700  Selector: textFieldEndEditing by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:19.690  Selector: textFieldSubmitEditing by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:18.807  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:18.556  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:18.356  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:17.707  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:17.423  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:16.807  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:16.541  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:16.307  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:15.508  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:15.363  Selector: textFieldDidChange by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:14.951  Touch: (UIKeyboardLayoutStar) in UIViewController
(user_steps) 27-01 07:51:13.890  Selector: textFieldBeginEditing by (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:13.884  Touch: (RCTTextField) in UIViewController
(user_steps) 27-01 07:51:12.500  Touch: Stingy Slushy Northernpike(RCTText) in UIViewController
(user_steps) 27-01 07:51:07.028  Top View: UIViewController
(user_steps) 27-01 07:51:07.028  Application: DidBecomeActive
(console_log) 27-01 07:51:06.835  folderName: file:///var/mobile/Containers/Data/Application/9BF14F16-927A-41FD-8878-FF4BDDBF01DE/Documents/ethereum/
(user_steps) 27-01 07:51:04.797  Top View: UIViewController

![chats screen](https://cloud.githubusercontent.com/assets/6584810/23753329/56f0f2fe-04d9-11e7-9aa8-a2f8fd8345db.png)

[comment]: # (if on Android please replicate bug whilst running adb logcat)

**Comment by GustavoNunes** [comment]
Hi @annadanchenko! PR #843, which will possibly be merged for 0.9.5, implements the search, however it only searches by name, not by the chat content.
Should it be changed to also search by previous conversations content?

**Comment by rasom** [comment]
@GustavoNunes, let's implement search by conversations content later.

**Comment by annadanchenko** [comment]
@GustavoNunes I might want to much for the beginning, search by name is also fine
