### ISSUE TITLE
Autofocus is broken in Status app

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8730]
# Problem

Turned out that autofocus is broken across the app. Originally found here https://github.com/status-im/status-react/pull/8687#issuecomment-519178199

## Steps

- open status -> tap access key -> keyboard is not active for entering recovery phrase
- open status -> create new account -> back up recovery phrase -> confirm -> keyboard is not active for entering recovery phrase
- open status -> profile -> advanced -> edit network

## Acceptance Criteria

if `auto-focus` property is enabled, then keyboard should be shown

![image](https://user-images.githubusercontent.com/28752642/62850818-d1392e00-bcec-11e9-9640-6060761159d8.png)

**Comment by rachelhamlin** [comment]
Is this happening on specific builds or platforms @asemiankevich? The keyboard appears in these scenarios for me on iOS nightly (v 0.14.0 2019072409). Does it completely block you from accessing your key, backing up, etc.?

**Comment by asemiankevich** [comment]
> Is this happening on specific builds or platforms @asemiankevich? The keyboard appears in these scenarios for me on iOS nightly (v 0.14.0 2019072409). Does it completely block you from accessing your key, backing up, etc.?

it does not depend on platform i think, also it is not blocking user from anything - just annoying

**Comment by churik** [comment]
Not reproducible for me (Android 8, LG V20)
