### ISSUE TITLE
Endless spinner instead of "Not confirmed. Tap for options" status for messages

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8734]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when messages cannot be sent (i.e. unstable connection), we had options to resent it or delete.  Now instead of options, the endless spinner is displayed.
Issue is not reproducible on 0.13.0

#### Expected behavior
"Not confirmed. Tap for options"

#### Actual behavior
endless spinner 
![IMG_7ACA4BA0C66F-1](https://user-images.githubusercontent.com/4557972/62866310-c4c6cc80-bd10-11e9-966a-ac548f83f4b6.jpeg)

### Reproduction

*Note: easy-to-reproduce on IOS only, but I think that issue is not platform-specific*

- Open Status
- Join any public chat
- Turn on airplane mode and quickly send a message (3 sec until button will be hidden)
- Wait for minute
- Turn off airplane mode 
- Wait for minute

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 12/08/2019
- Operating System: Android, iOS

#### Logs
[geth.log](https://github.com/status-im/status-react/files/3492416/geth.log)

**Comment by cammellos** [comment]
@churik @Serhy this might actually be fixed on develop, could you try it out when you have some time? Thanks!

**Comment by Serhy** [comment]
Indeed with the latest nightly (2019081303) confirmed not reproduced:
In 1-1 / Public chats: turned on Airplane mode and quickly send a message while there is a Send button present. In 1-2 minutes there is a 'Not sent. Tap for options' status appears below the message. 
And in a case of WiFi enabled during 1-2 minutes - the 'Sent' status as expected appears. 
Thanks @cammellos, closing this issue.

**Comment by churik** [comment]
It is reproducible again on nightly 22/08/2019 - so:
when I try to use "Resend" - error (tried from offline state)
![photo_2019-08-22 11 13 42](https://user-images.githubusercontent.com/4557972/63502465-e91f6780-c4cd-11e9-85cb-3a0f1125078d.jpeg)

Logs: 
[Status-debug-logs.zip](https://github.com/status-im/status-react/files/3529286/Status-debug-logs.zip)
After this error "Not confirmed. Tap for options"  doesn't appear again and the message is shown in chat with endless spinner.

**Comment by churik** [comment]
cc @rachelhamlin
