### ISSUE TITLE
In German sum with decimal separator can't be requested because it contains comma and treated as invalid

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#874]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use a proper decimal separator so that I can request 0.5 ETH in German where it's 0,5 ETH.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In German Language there is a "," separator for sum. Currently, I cannot request 0.5 ETH, because the validator does not accept 0,5. Keyboard contains only "," and no "." Note that it's possible to send 0,5 ETH, so the issue seems to be only with requesting.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
In German language: I can type 0,5 ETH and they can be requested.

#### Actual behavior
[comment]: # (Describe what actually happened.)
In German language: Keyboard contains only "," separator. When I type 0,5 ETH they can't be requested as validator considers it as invalid sum
![german sum separator](https://cloud.githubusercontent.com/assets/6584810/23759031/d204ee48-04eb-11e7-8eeb-70b4538e5db2.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Change iPhone language to German
- Open Status
- Log in
- Open Contacts, open a contact from People section and try to Request ETH of 0.5

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3
[comment]: # (Android or iOS.)
* Operating System: iOS
* Instabug: https://dashboard.instabug.com/applications/status/beta/bugs/127

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
