### ISSUE TITLE
Public chats reappear after deleting

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8740]
### Description

*Type*: Bug

*Summary*: 
Public chats are reappeared if they are deleted after creating new account and before first logout.
The issue is reproducible in nightly 12/08/2018 (no issue in nigtly for 12/08/2019) - most likely was introduced by commit https://github.com/status-im/status-react/commit/370bc207bcfa8ee76eb8011d048e1e4cc0b78f2a.

#### Expected behavior
chats are not reappeared 

#### Actual behavior
chat is still displayed
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/4557972/62929991-d1ecc580-bdbb-11e9-94b5-233d3dcc9c71.gif)

### Reproduction

- Open Status
- Create a new account
- Join public chat
- Delete public chat

### Additional Information

- Status version: nightly 13/08/2019
- Operating System:  Android, iOS

### Additional Information 
Logs + steps: https://app.saucelabs.com/tests/c0d1a068138149b1a4d53f2c341dee94?auth=a9df754a82209162a75fcb5e8c0d91d5

**Comment by churik** [comment]
cc @cammellos

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
I don't like it and won't remove the `v1 release` label, but I could live with it. Another bounty candidate.

**Comment by cammellos** [comment]
I could not replicate, @churik can you consistently replicate or it happens only on tests/every now and then? ( I think I might know what it does not happen always, possibly due to https://github.com/status-im/status-protocol-go/issues/44 )

**Comment by churik** [comment]
Seems this one is gone.
Checked on nightly 19/08/2019
