### ISSUE TITLE
Fix [Next] button on password confirmation screen (onboarding)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8743]
# Problem

There are several issues with Next button when confirming password in new onboarding flow:

1. No visual effect that button is tapped
2. I can tap this button several times (should be disabled once tapped first time)
3. If i tap the button several times, i either close next screen (with Fingerprint settings) or i can run into https://github.com/status-im/status-react/issues/8710
4. Screens are not smooth by tapping this Next button, looks like they are stuck for a second

## Steps

1. open status
2. go though onboarding until password set up and confirmation
3. enter password and tap Next button quickly several times

**Comment by rachelhamlin** [comment]
Can you please include expected result and screenshots?
