### ISSUE TITLE
No messages are received by Group chat members if sender re-login once 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8744]
***Type***: Bug

***Summary***: Messaging stops working in Group chats if you re-login after group chat creation. They are marked as Sent but no one from Group chat members will see them. 

#### Expected behavior

Messages are received by the recipient in GroupChat after message sender re-logins to account

#### Actual behavior

No messages are received by the recipient in GroupChat after message sender re-logins to account

<img width="661" alt="Screenshot 2019-08-14 at 13 38 44" src="https://user-images.githubusercontent.com/8749671/63015158-e8b51a00-be98-11e9-83e4-307f314e728e.png">

### Reproduction

- Open Status on two devices and create new accounts (UserA and UserB)
- UserA adds UserB in contacts
- UserA (or UserB - doesn't matter) creates a Group chat
- UserA and UserB exchange with messages (at this point everything is OK and messages received by both users)
- UserA re-logins to account
- UserA sends a text message to UserB in Group chat
**Actual result** Nothing is received by UserB.
- Now UserB sends text message to UserA
**Actual result = Expected result:** UserA received message
- UserB re-logins to account
- Both users exchange with the messages in Group Chat
**Actual result:** No one from UserA and UserB received message

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: Develop (2019081212)
- Operating System: Android and iOS

**Comment by Serhy** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
This one is fairly clear cut, but can you please include screenshots? Thanks!

**Comment by Serhy** [comment]
Updated with screenshot
