### ISSUE TITLE
Status any plans to support URL Scheme?

### ISSUE THREAD

**Issue by makoshan** [status-im/status-react#875]
- EIP 67: https://github.com/ethereum/EIPs/issues/67 
- MyEtherWallet :  https://github.com/kvhnuke/etherwallet/issues/283
- bitcoin: https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki

**Comment by chadyj** [comment]
Hi. We now support a custom URL scheme's https://wiki.status.im/Universal_Links

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>
