### ISSUE TITLE
Password input layout is messy when validation error is present (new wallet account)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8758]
# Problem

Screen looks broken when validation error is present on the screen

## Steps

- create new account
- tap wallet -> add account
- tap Add an account
- tap Generate a new account
- enter 000000 value into password field and tap Generate account button

## Actual result:

- password input is moved to the top  (because of additional text is added to the screen)

![image](https://user-images.githubusercontent.com/28752642/63082062-e82a8b00-bf4d-11e9-9259-be7f2afa46d9.png)

- if i remove wrong password and tap [enter] on android keyboard in order to close it -> it is very difficult to find the input field to re-enter the password

![image](https://user-images.githubusercontent.com/28752642/63082366-bc5bd500-bf4e-11e9-8f22-1fb3e6f61b26.png)

@hesterbruikman @flexsurfer

**Comment by asemiankevich** [comment]
@rachelhamlin

**Comment by churik** [comment]
not reproducible on nightly 26/02/2020
