### ISSUE TITLE
Only 1 icon (Chats) in the footer instead of 3 (no Discover and Contacts)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#876]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to open Contacts and Discover screens so that I can use them.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: there is 1 icon in the footer: Chats

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
there are 3 icons in the footer: Chats, Discover and Contact
#### Actual behavior
[comment]: # (Describe what actually happened.)
there is 1 icon in the footer: Chats
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- See the footer
![footer](https://cloud.githubusercontent.com/assets/6584810/23790026/a3b3da4e-057d-11e7-9190-fe565bdc96c2.jpg)

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4d11 build 1212.11
* Operating System: Android and iOS

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by annadanchenko** [comment]
Instabug: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/249
