### ISSUE TITLE
Added account is duplicated when multutapping Finish button

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8760]
# Problem

If i multitap [Finish] button when adding an account to my multiaccount instance -> then added account will be duplicated in wallet

![image](https://user-images.githubusercontent.com/28752642/63084798-b10ba800-bf54-11e9-9461-a70201130dab.png)

## Steps

- create new account
- tap wallet -> add account
- tap Add an account
- tap Generate a new account
- enter password -> generate new account
- select account color
- tap [Finish] button several times in a row
- check wallet

## Video

https://drive.google.com/open?id=1Xa0j7wG0StB22sSOvRHFgzO9yaHTxA0I

## Notes

Similar to https://github.com/status-im/status-react/issues/8710 

@flexsurfer @siphiuel

**Comment by yenda** [comment]
Is this still relevant?

**Comment by asemiankevich** [comment]
> Is this still relevant?

@yenda i was able to reproduce it in today's nightly, so yes.

**Comment by yenda** [comment]
Yes I saw that sorry I fixed it in the PR
