### ISSUE TITLE
Inconsistencies in "Show my ENS name in chat" setting in user profile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8765]
# Problem
After https://github.com/status-im/status-react/pull/8722 will be merged, setting "Show my ENS name in chat" will be used and chat name will be resolved according to [figma design](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?)
But there are some issues \ unexpected behavior IMO, which should be addressed before this feature will be released.
So I'll put which inconsistencies (from my POV) I've already seen one by one in this issue to keep track on decisions about all of them.

### 1. "Show my ENS name in chat" doesn't affect 1-1 chat and partially group chat

I think that if it affects public chat only, setting should be renamed to "Show my ENS name in public chat". Besides, there is some unexpected behavior for system messages in group chats: when setting is off "name.stateofus.eth" is shown.

**Steps:**
- user A: restore account with ENS name, bind it
- user B: add user A to contacts
- user A: turn off "Show my ENS name in chat"
- user B: start chat with user A
- user B: start froup chat with user A

**Expected result:** 
1. setting is renamed to "Show my ENS name in public chat" and  ENS username for all messages in group chat 
or
2. default username in 1-1 chat, group chat

**Actual result:** 
- for 1-1 chat still see ENS username as a chat name;
- for group chat for system messages full ens name is shown
<img width="475" alt="photo_2019-08-15 20 08 18 jpeg 2019-08-15 20-09-00" src="https://user-images.githubusercontent.com/4557972/63115974-cc000b80-bf98-11e9-864e-e69b069f62ed.png">

### 2. Turning off "Show my ENS name in chat" or set new name as primary affects only new messages in chats

That leads to a situation when the same user has several names in the same chat.

**Steps:**
- user A: restore account with ENS name, bind it
- user B: add user A to contacts
- user A: turn on "Show my ENS name in chat"
- user A: send message to public chat
- user A: turn off "Show my ENS name in chat"
- user A: send message to public chat

**Expected result:**  username is updated for all previous messages in the chat

**Actual result:** 
<img width="199" alt="12345" src="https://user-images.githubusercontent.com/4557972/63116526-264d9c00-bf9a-11e9-90b3-fbb4c751b503.png">

#### 3.1 User A: "Show my ENS name in chat" is on, `User A` is not added as the contact of `User B`
![screencast 2019-08-15 20-34-03](https://user-images.githubusercontent.com/4557972/63117723-a6750100-bf9c-11e9-9213-7c143f75d90a.gif)
In this case, you see ENS name in chat, tap on it -> and no  ENS name is shown in the user profile.
Expected from my POV: both ENS name and default username are visible.

#### 3.2 User A: "Show my ENS name in chat" is on, `User A` is added as contact of `User B`
![screencast 2019-08-15 20-44-17](https://user-images.githubusercontent.com/4557972/63118607-80e8f700-bf9e-11e9-9871-81245d90ae62.gif)

In this case, you see ENS name in chat, tap on it -> and only ENS name is shown in the user profile
Expected from my POV: both ENS name and default username are visible.

#### 3.3 User A: "Show my ENS name in chat" is off, `User A` is added as a contact of `User B`

In this case, you see default username in chat, tap on it -> and only ENS name is shown in the user profile
Expected from my POV: both ENS name and default username are visible.

### 4. No ENS name is shown on Sign-in screen 

**Steps:**
- user A: restore account with ENS name, bind it
- user A: log out

**Expected result:**  can see ENS username on the sign-in screen 

**Actual result:** 
only default name is shown
<img width="198" alt="photo_2019-08-15 20 59 25 jpeg 2019-08-15 20-59-37" src="https://user-images.githubusercontent.com/4557972/63119119-a6c2cb80-bf9f-11e9-84f3-21ab19f25b29.png">

# Summary:

- [ ] 1. "Show my ENS name in chat" doesn't affect 1-1 chat and partially group chat
- [ ] 2. Turning off "Show my ENS name in chat" or set new name as primary affects only new messages in chats
- [ ] 3. No consistency for user profile views 
- [ ] 4. No ENS name is shown on Sign-in screen
 
IMO 2 for sure should be added as `v1-release`, other depending on decisions, so after discussion will create separate issues.
 
Need help of @hesterbruikman @annadanchenko @rachelhamlin to define priority and expected results in each case.

**Comment by hesterbruikman** [comment]
@errorists can you also take a look please?

1. I need some help retracing our decision here. I believe we opted for an 'all or nothing' ENS name toggle, incl 1:1 and group chat, irrespective of contact status, but may have missed conversations along the way.
2. Afaik is expected behavior. Agree it's not great. Believe there was no technical solution for this. Could be a blessing in disguise, I'd love to hear more thoughts on. On the one hand you can see who might know you by your anonymous name, on the other hand, newcomers to a chat might be able to tie your pseudo-anonymous name and ENS name together.
3. Could inconsistency in other user profile be taken along in #8776 @rachel @flexsurfer?
4. Indeed is inconsistent, but the safest bet as long as we don't have a chat agnostic unlock screen. Showing ENS name before password entry on Unlock screen introduces a privacy weakness (cc @yenda)

**Comment by errorists** [comment]
1. it's all or nothing, you switch ENS to broadcast it publicly including 1:1 and group chats
2. that's a technical limitation, we have to accept it for what it is and file under quirks of our current messaging protocol. at least it's consistent and predictable. 
3. that's a bug, it should be persistent

**Comment by churik** [comment]
closing this one and open https://github.com/status-im/status-react/issues/8854
