### ISSUE TITLE
Fixes in e2e for critical and high-prio tests

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8769]
- [x] 1. https://ethstatus.testrail.net/index.php?/tests/view/812731 - passed locally with the same build:( take a look (probably waiting for home_button can fix it); if not - IMO is better to skip the last check:
```
 sign_in.sign_in()
 if not sign_in.home_button.is_element_displayed():
            self.errors.append('User is not logged in')
```
because anyway we are logging with new account in a lot of e2e.

- [x] 2. https://ethstatus.testrail.net/index.php?/tests/view/812874 - change to device time
- [x] 3. https://ethstatus.testrail.net/index.php?/tests/view/812872 
3.1 delete custom usernames - they are not used anymore;
3.2 basic_user['public_key'] - for all users that are used in tests, update public key - they are changed.
- [x] 4. https://ethstatus.testrail.net/index.php?/tests/view/812841 - update according to new flow in recovery
- [x] 5. https://ethstatus.testrail.net/index.php?/tests/view/812844 - debug why element couldn't be found 
```
{ "using": "xpath", "value": "//*[@text=\"Wrong password\"]" }
```
- [x] 6. https://ethstatus.testrail.net/index.php?/tests/view/812806 - change test, it is not mistake when messages are shown after user joined to chat (previously there was a check that messages are visible when user invited to chat)

- [x] 7. https://ethstatus.testrail.net/index.php?/tests/view/812859 - remove username edit (btw should be removed at all in all tests) and checking it in test

- [x] 8. https://ethstatus.testrail.net/index.php?/tests/view/812819 - investigate why `recover_access_view.send_as_keyevent(phrase)` is sending ` ` - probably due to issue https://github.com/status-im/status-react/issues/8548

**Comment by yevh-berdnyk** [comment]
> 1. https://ethstatus.testrail.net/index.php?/tests/view/812731 - passed locally with the same build:( take a look (probably waiting for home_button can fix it); if not - IMO is better to skip the last check:
> 
> ```
>  sign_in.sign_in()
>  if not sign_in.home_button.is_element_displayed():
>             self.errors.append('User is not logged in')
> ```
> 
> because anyway we are logging with new account in a lot of e2e.

Gathering errors is remomed in this test

> 2. https://ethstatus.testrail.net/index.php?/tests/view/812874 - change to device time

Fixed in https://github.com/status-im/status-react/pull/8768
> 3. https://ethstatus.testrail.net/index.php?/tests/view/812872
>   3.1 delete custom usernames - they are not used anymore;
>   3.2 basic_user['public_key'] - for all users that are used in tests, update public key - they are changed.

The test is updated. All other public keys will be updated in a separate PR
> 4. https://ethstatus.testrail.net/index.php?/tests/view/812841 - update according to new flow in recovery

Changed, however the test will fail because passphrase remains capitalized
> 5. https://ethstatus.testrail.net/index.php?/tests/view/812844 - debug why element couldn't be found
> 
> ```
> { "using": "xpath", "value": "//*[@text=\"Wrong password\"]" }
> ```
 The test could not find public key text, it's fixed by update of public keys 
> 6. https://ethstatus.testrail.net/index.php?/tests/view/812806 - change test, it is not mistake when messages are shown after user joined to chat (previously there was a check that messages are visible when user invited to chat)

Updated, a message will be sent after a user has joined a chat
> 7. https://ethstatus.testrail.net/index.php?/tests/view/812859 - remove username edit (btw should be removed at all in all tests) and checking it in test

Updated
> 8. https://ethstatus.testrail.net/index.php?/tests/view/812819 - investigate why `recover_access_view.send_as_keyevent(phrase)` is sending ` ` - probably due to issue #8548

In that step the test performs empty password validation so it's expected to send ' '. 
The test is fixed
