### ISSUE TITLE
Add intro text for empty Discover screen, so new users know what to expect and how to use it

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#877]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a new user, I want to understand why Discover screen is empty so that I can start using it and add tags.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: New user opens Discover screen that contains no info atm. It would be nice educational feature to add some explanation of why it's empty and when it will get content

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
User opens Discover screen. If screen is emtpy (nothing to discover) then there is some explanation, so user learns about tags/contact etc 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Discover screen contains text "No statuses discovered"
![discover empty](https://cloud.githubusercontent.com/assets/6584810/23791439/3f6c0088-0583-11e7-9d6b-3cdb79308514.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- As a new user without any contacts, open Status
- Open Discover screen

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3
* Operating System: Android and iOS
* Instabug: https://dashboard.instabug.com/applications/status/beta/bugs/274

**Comment by jarradh** [comment]
https://github.com/status-im/status-react/blob/43667ea6ac077753390dbaa73db1e27cd7b0436a/src/status_im/translations/en.cljs#L135

Needs Translations

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by juanmadrigal1219** [comment]
from the status wiki that explains the discover feature more to help whoever is working on this issue.
https://wiki.status.im/proposals/discover/

**Comment by p14n** [comment]
How about "Discovery collects the status of your contacts (and their contacts) and shows them, organised by hashtag, to help you make connections" ?

How does the project handle adding the correct translations?  

![discovery](https://user-images.githubusercontent.com/676545/28844377-53ad6114-76fc-11e7-9279-cd124e5f915f.png)

**Comment by goranjovic** [comment]
Solved in #1874
