### ISSUE TITLE
Network details screen is shown when changing networks

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8771]
# Problem

User is stuck on Network details when changing networks.
Should be landed on login screen after a network change.

## Steps:

1. create account
2 profile -> dev mode ->network -> select Ropsten and confirm

![image](https://user-images.githubusercontent.com/28752642/63244573-76608300-c266-11e9-82a4-f39202722a05.png)

**Comment by yenda** [comment]
Is this still happening? I can't reproduce

**Comment by asemiankevich** [comment]
> Is this still happening? I can't reproduce

i can't reproduce manually but sometimes autotests could repro it.

**Comment by churik** [comment]
Yes, it is still reproducible sometimes (but once in ages).

**Comment by churik** [comment]
Didn't see it for a long time, suppose it is gone
