### ISSUE TITLE
Keyboard with upper case letters is shown when tap in Password field on Login screen

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#878]
### User Story

As a user, I want to type my password as quickly as possible so that I can login.

### Description

*Type*: Bug

*Summary*: keyboard with capital letters is shown if tap on Password on Login screen. Usually, for password fields there is no capitalization of first letter. For example, when user creates new password in the Status then for password input keyboard is shown with lowercase letters.

#### Expected behavior
Keyboard with lowercase letters is shown when user taps on Password field (a instead of A)
#### Actual behavior
Keyboard with upper case is shown when user taps on Password field

![password](https://cloud.githubusercontent.com/assets/6584810/23792238/646fa5c6-0586-11e7-9be1-e9c1b9cf5b8d.png)

### Reproduction

- Open Status
- Tap on username to login
- On Login screen tap on Password -> keyboard is shown. check the letters on keyboard (upper case or lowercase)

### Solution
*Summary*: 

- [ ] ...

### Additional Information
* Status version: 0.9.3
* Operating System: Android 7.0, 6.0.1
* Instabug: https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/276

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
