### ISSUE TITLE
Error scrollToIndex when tapping [Fetch messages] twice in a row

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8797]
# Problem

`Error
scrollToIndex should be used in conjunction with getItemLayout or on-ScrollToIndexFailed, otherwise there is no way to know the location of offscreen indicies or handle failures`

![image](https://user-images.githubusercontent.com/28752642/63419350-50c1ae00-c40d-11e9-9d3b-bb7a85d18897.png)

## Steps
1. create new account
2. join test-team public chat
3. tap `Fetch previous messages` twice in a row before messages appear

**Comment by flexsurfer** [comment]
cc @rachelhamlin users report this issue in v1
