### ISSUE TITLE
Can't login to application

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8799]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: sometimes after creating an account I can see endless spinner instead of + button and after logout, I can't log in. If I try to create new account - after logout  I also can't login to the app, it shows "Processing" state.
I couldn't find a way to recover from this state - only reinstalling app helped

#### Expected behavior
can login to app

#### Actual behavior
![pr](https://user-images.githubusercontent.com/4557972/63423899-8cf50e80-c40d-11e9-8913-5c42500cc73f.gif)

### Reproduction

- Open Status
- Create an account
- Logout
- Login

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 21/08/2019
- Operating System: Android

#### Logs
Geth.log: 
[geth (1).log](https://github.com/status-im/status-react/files/3524821/geth.1.log)
Logcat: 
[logcat_processing.log](https://github.com/status-im/status-react/files/3524823/logcat_processing.log)

**Comment by yenda** [comment]
There is two errors related in the geth logs:
- first there is already a node running when you login, which is very odd, I wonder how that could have happen
- second the account is not found in the database when you login
`t=2019-08-21T10:07:10+0000 lvl=eror msg="failed to start a node" address=0x652178f65F1a4d85c0f0CdC45CBB0bC7CA8C2Df7 error="sql: no rows in result set"`

It would be great to have a more precise description of the reproduction steps.

First question, did you install fresh or was it an update? Did you manage to reproduce after re-installing. If it is only when you update I would say that is probably the cause, we are not making upgradable nightlies at the moment, and the changes merged yesterday were pretty heavy

**Comment by churik** [comment]
@yenda 
1) it was fresh install
2) no, I didn't manage to reproduce this. but @asemiankevich told that she faced with it as well.

**Comment by asemiankevich** [comment]
it happens from time to time, i've seen this after logout , but was blaming some bad connection at home. Looks like sometimes node can't start

**Comment by churik** [comment]
Caught by e2e: https://app.saucelabs.com/tests/6a640091d97947509e3d454ac7b07f90?auth=48fb9d4eafc80590ab1fb9b48178798c#48

**Comment by churik** [comment]
Couldn't reproduce anymore
