### ISSUE TITLE
Capital letters are not replaced in recovery phrase

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8800]
### Description

*Type*: Bug

*Summary*: on release 0.13.0 all uppercase was replaced by lowercase in recovery phrase input field automatically. Now on Android recovery phrase with capital letters remains the same, but anyway it recovers right account (whisper id + wallet address)

#### Expected behavior
recovery phrase in lowercase

#### Actual behavior
recovery phrase is persisted

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Tap on "Access key"
- Enter phrase with uppercase letters

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 21/08/2019
- Operating System: Android

#### Logs

Video and logs: https://app.saucelabs.com/tests/1d8650491fd7488b8dacdf85c7707c4d?auth=6b244604bc292931a211ca12523a9b24v

**Comment by asemiankevich** [comment]
@dmitryn @hesterbruikman is that an issue what do you think? I mean if we recover correct account in both cases (upper case and lower case letters)?

**Comment by dmitryn** [comment]
During actual recovery we convert characters to lowercase so it doesn't matter what user types in. From UX point of view, i personally prefer to see what i'm typing without modifications. 
But we can revert to old behavior if that was better.

**Comment by asemiankevich** [comment]
i am okay with current behavior, thank you @dmitryn !

i think we can align autotest then @churik @yevh-berdnyk ?

**Comment by churik** [comment]
we can just remove it from testrail and e2e then
https://ethstatus.testrail.net/index.php?/cases/view/5394

**Comment by churik** [comment]
Ok, I guess it is better to replace this with the test that will check that from recovery phrase with capital letters will be recovered user with expected whisper id.
Will edit https://ethstatus.testrail.net/index.php?/cases/view/5394

**Comment by hesterbruikman** [comment]
> 
> 
> During actual recovery we convert characters to lowercase so it doesn't matter what user types in. From UX point of view, i personally prefer to see what i'm typing without modifications.
> But we can revert to old behavior if that was better.

Apologies for the late reply. But leaving it as I imagine we'll have similar conversations on other text entry fields. Current behavior is ok IMO. Agree with @dmitryn that as a user you'd want to see what your typing. The preferred solution  here is magic=ok, hiddenmagic≠ok. 

If we require lower case, preferred behavior is to set the native keyboard to lowercase entry; This gives the user most control and transparency.

**Great**
Set native keyboard to lowercase

**OK**
Overwrite Upper case 'behind the scenes' on submitting the entry

**Meh**
Adjusting what you type on the fly
