### ISSUE TITLE
No redirect from universal links after login

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8802]
#  Description

*Type*: Bug

*Summary*: no redirection to user profile / public chat / Dapp if you open the link and should login.
On 0.13.0 if you open link `https://get.status.im/user/0x0449add8977ca4aea3c5b7dde3cfca4a1e59171bacb306d7c7830a9cecb565b10bc618ad77e3c4c1c1893e8e82d6d0af7730ea73c7f000c27cb990c6c741b1377a` when app is closed and login - you will be redirected to user profile, on current nightly - to dashboard

#### Expected behavior
redirect to new chat `#tery`

#### Actual behavior
dashboard is shown

### Reproduction

- Tap on link https://get.status.im/chat/public/tery
- Login

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 21/08/2019

- Operating System: Android, iOS

#### Logs

Logs and video is [here](https://app.saucelabs.com/tests/03e0da2c9e114379ab03a007aa362e00?auth=998715fbab2df3d2fb1c08dbbde652dd#90)

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
`e2e test blocker` is a pain but from a user perspective I wouldn't call it a release blocker. Adding to new v1 'non blocking' backlog in Wrike. Thanks!

**Comment by churik** [comment]
Well, I wouldn't agree here.
AFAIK we placed a lot of links outside the app (i.e. for `#status` channel) in Twitter, social networks etc. and if user tap on it and nothing happens - it will affect the first impression of the app.
From my perspective, it is even `high-priority` issue.
Let's talk about it on core-sync and check with others, is it OK?
cc @annadanchenko

**Comment by rachelhamlin** [comment]
We can take those down if we had to—thinking about the # of engineering resources we have vs. the backlog of severe issues, I think it's reasonable to consider alternatives. That said, this one might be a small effort and therefore feasible. I'd like to have that conversation, but it might be more useful to do so when we are past the code freeze.
