### ISSUE TITLE
Fix e2e failures

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8808]
- [ ] https://ethstatus.testrail.net/index.php?/tests/view/822122 - not sure why failed

- [x]  https://ethstatus.testrail.net/index.php?/tests/view/822207 - edit; no "UserNameSetByUserText" element anymore

- [x] https://ethstatus.testrail.net/index.php?/tests/view/822229 - false failure; wait for "Sign in" button to be active 

- [x] https://ethstatus.testrail.net/index.php?/tests/view/822189, https://ethstatus.testrail.net/index.php?/tests/view/822243 - change to default usernames (change device_2_custom_username to default username until https://github.com/status-im/status-react/issues/8765)

- [x] https://ethstatus.testrail.net/index.php?/tests/view/822194, https://ethstatus.testrail.net/index.php?/tests/view/822192 - two more profile picture fix

- [x] https://ethstatus.testrail.net/index.php?/cases/view/5394 - recreate;

**Comment by yevh-berdnyk** [comment]
> * [ ]  https://ethstatus.testrail.net/index.php?/tests/view/822122 - not sure why failed

Will be fixed with #8784 

Other tests are updated
