### ISSUE TITLE
Messages are not visible in a group chat once i remove a chat member

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8809]
# Problem

There is a group chat of 2 people. I send some messages there as admin -> non-admin also see them in this group conversation. As admin i delete second chat participant and continue sending messages to this chat. As a result messages are not shown in chat for admin (i can see newly sent message in chat preview on Chat tab though).

## Steps

1. as user A (admin) create group chat with user B
2. as user B accept the invitation
3. as user A send some messages
4. as user B  make sure you see the messages in this group
5. as user A tap 3 dots -> group info -> delete user B from group
6. as user A continue sending messages to this chat
7. as user A check that the messages are visible

As a result they are not visible. If you move to Chats tab -> you can see the message in chat preview.

![image](https://user-images.githubusercontent.com/28752642/63499039-bb3b2280-c4cf-11e9-954f-4904f7006f77.png)

Check the video: https://drive.google.com/open?id=1v6C7TsgPHBWrAKuQOPa9ScnLRoTI8xiH

## Device and build
- Huawei P10 Lite Android 8, Xiaomi Redmi Note 4 Android 7
- nightly build 22-Aug-2019, https://status-im.ams3.digitaloceanspaces.com/StatusIm-190822-025900-06dd2e-nightly.apk

**Comment by churik** [comment]
@cammellos please, take a look when you have time.
Thanks!

**Comment by cammellos** [comment]
I see, we should probably not allow sending to an empty chat and disable the text input in such cases (that's the root of the problem I believe, if there was another member everything would work ok), what do you think?

**Comment by asemiankevich** [comment]
@hesterbruikman ? :)

**Comment by churik** [comment]
It is like chat with myself only) I suppose that messages should be visible in that case, but if it is not possible - it is enough to prevent user from sending messages until he adds new members IMO

**Comment by cammellos** [comment]
both are possible, although no-one but yourself will see the messages, even if they join at later time, it's technically a bit more complex, but best to go for the preferred ux solution.

**Comment by churik** [comment]
@asemiankevich is it only when in group chat 2 members, and admin delete one, or it is reproducible for 3-4 people as well when admin deletes one member?

**Comment by asemiankevich** [comment]
> @asemiankevich is it only when in group chat 2 members, and admin delete one, or it is reproducible for 3-4 people as well when admin deletes one member?

it happens as described in an issue, but worth mentioning it happens only when i am the only 1 left in the group chat, so if i have 3 members and remove someone - if i continue messaging -> all messages are shown.

**Comment by churik** [comment]
should be rechecked after fix https://github.com/status-im/status-react/issues/10054

**Comment by churik** [comment]
Still the issue, happening only if 1 admin left in the chat - in this case, all sent messages are stuck with endless spinner.
But if admin add new member, all new messages are sending as expected.
so it doesn't look to me as high-prio issue and IMO can be fixed later - not usual situation when admin will remove all users and keep sending messages.

![photo_2020-04-14 12 25 09](https://user-images.githubusercontent.com/4557972/79214372-fe754780-7e4a-11ea-8459-2bd90336657a.jpeg)

**Comment by churik** [comment]
Not relevant anymore on 1.4
