### ISSUE TITLE
status-go version is shown as N/A

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8813]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In nightly build, Profile -> About -> status-go version is shown as vN/A

#### Expected behavior

Expect to see status-go version number

#### Actual behavior

![Screenshot_20190822-122945](https://user-images.githubusercontent.com/6584810/63507989-508ee480-c4d9-11e9-953f-8acf15b6246e.png)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status -> Profile
- Check version shown for status-go 
### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly Aug 22
- Operating System: found on android

**Comment by rachelhamlin** [comment]
Requesting @cammellos or @adambabik to take a look into this to see if it's a go fix.

**Comment by adambabik** [comment]
I need to first fix https://github.com/status-im/status-go/issues/1591. It looks like we either do not expose `web3` API module from status-go or it does not respond properly.

**Comment by adambabik** [comment]
```
$ echo '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' | nc -U /Users/adamb/repos/status-go/test-dir/geth.ipc | jq .
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "Statusd/v0.33.0-beta.0/darwin-amd64/go1.12.9"
}
```
`web3` needs to be enabled in the `APIModules` in the config. However, if we turned it off due to security reasons, we may need to provide our own implementation in order not to turn the whole module on.

Let me know how the version is currently retrieved from the node.

**Comment by rachelhamlin** [comment]
cc @flexsurfer

**Comment by rachelhamlin** [comment]
@corpetty can you take a look at this? I don't think it's required for the code freeze but it was tagged as such so I want to make certain with you.
