### ISSUE TITLE
No geth.log in Downloads folder on nightly build

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8814]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:
-  No geth.log created if app has Storage permissions and new user is created. 
- If use Report a bug to send logs then geth.log is also not included into zip file

Found on nightly build from Aug 22 https://status-im.ams3.digitaloceanspaces.com/StatusIm-190822-025900-06dd2e-nightly.apk

Video to see settings and log level: https://drive.google.com/open?id=1O3ZALAL3Wv8cYYkvgXjSFGLQg2TtcvKt
#### Expected behavior

geth.log is on Internal storage -> Downloads

#### Actual behavior

no geth.log can be found on all Internal storage

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Remove geth.log from previous installations
- Install Status
- Create new account and add a picture to profile (to give app Storage permissions)
- Close app
- Launch app again
- Check Downloads folder on internal storage if it contains new geth.log

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly aug 22
- Operating System: found on real Android 9, Pixel XL and Android 6, Galaxy S6

**Comment by asemiankevich** [comment]
I can see geth.log on my device, Huawei P10 Lite Android 8 with nightly build https://ci.status.im/job/status-react/job/nightly/1222/

**Comment by asemiankevich** [comment]
and I can't see it on my Xiaomi Redmi Note 4 Android 7 same build https://ci.status.im/job/status-react/job/nightly/1222/

**Comment by churik** [comment]
geth.log is created on LG V20, Android 8 ,nightly 22/08/2019

**Comment by annadanchenko** [comment]
on nightly from Aug 29 there is geth.log created, so closing this issue (Pixel XL, Android 9)
