### ISSUE TITLE
"Processing" instead of validation message in case if you entered invalid password when sign in

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8829]
###  Description

*Type*: Bug

*Summary*: no validation error is shown when entering wrong password on login screen. Instead "Wrong password" endless "Processing" screen is shown.
Hopefully, that #8799 has the same cause - but in this case I can normally create account, logout and login after this error

#### Expected behavior
"Wrong password"

#### Actual behavior
Processing 
![pr](https://user-images.githubusercontent.com/4557972/63423899-8cf50e80-c40d-11e9-8913-5c42500cc73f.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Log out
- Try to login with the wrong password

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 23/08/2019
[comment]: # (Android or iOS.)
- Operating System: Android, iOS

#### Logs

Full video and log: https://app.saucelabs.com/tests/6a640091d97947509e3d454ac7b07f90?auth=48fb9d4eafc80590ab1fb9b48178798c#58

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by yenda** [comment]
It seems like we need a signal from status-go that the login failed. I created an issue there https://github.com/status-im/status-go/issues/1583
