### ISSUE TITLE
"No protocol method ISet" error when unblock non-contact [IOS only]

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8831]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*:  at attempt to unblock user who is not added to your contacts, got an error: "No protocol method ISet"  on IOS. It is working as expected on Android - no error.
The issue is not reproducible after relogin.

#### Expected behavior
no error

#### Actual behavior
![photo_2019-08-23 18 44 36](https://user-images.githubusercontent.com/4557972/63608767-12c3b600-c5d6-11e9-8065-4211fcfb037f.jpeg)

### Reproduction

- Open Status
- Block smbd from public chat (not from your contact list)
- Unblock user (from Profile > Contacts > Blocked Users)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 23/08/19
[comment]: # (Android or iOS.)
- Operating System: iOS

**Comment by yenda** [comment]
I can reproduce on Android:
- create account
- join #status   
- block first user
- go to profile contacts blocked
- unblock
