### ISSUE TITLE
Save password is unavailable when log in via deep link

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8840]
# Problem

`Save password is unavailable. Your device may be rooted or lacks necessary security features` when opening deep link

![image](https://user-images.githubusercontent.com/28752642/63753074-0b90f680-c8bb-11e9-9eaf-6d52579f6c47.png)

## Steps

- install status and close
- in browser access https://get.status.im/browse/status-im.github.io/dapp -> select status app to open the link

https://app.saucelabs.com/tests/514484ccc2ad4de2b3ee97b90f9e10db?auth=e834f187944a826cb2d88080a74d4a11#94

**Comment by churik** [comment]
should be rechecked after https://github.com/status-im/status-react/issues/10061 and https://github.com/status-im/status-react/issues/10083

**Comment by churik** [comment]
not relevant anymore on release 1.4
