### ISSUE TITLE
Back button is not active on Recover a key stored on keycard screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8851]
# Problem

Build-in in-app button at the top left is not active, so tapping it does not redirect me to the previous screen.

![image](https://user-images.githubusercontent.com/28752642/63851346-cf36c680-c99e-11e9-9525-63d125cdaae5.png)

## Steps

1. open Status
2. tap Access key
3. select Recover with Keycard
4. tap in-app Back button at the top left

**Comment by acolytec3** [comment]
Quick note, I could not reproduce this on a Oneplus 6T with a current build from the develop branch.  The in-app back button appears to work just fine and navigates back to the previous page as expected so wondering if it got fixed.

**Comment by rachelhamlin** [comment]
Thanks for that @acolytec3! I believe it's been reported somewhere else and should get fixed in the scope of another issue, if it still exists. Closing.
