### ISSUE TITLE
Finish "Show my ENS name in chat" setting in user profile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8854]
### Description
_Type_: Feature
_Summary_: according to ENS call today (notes are [here](https://notes.status.im/DRZxyjWyQc6o_F32uSCaLg)) "Show my ENS name in chat" setting is not related to user nickname and should be applicable for all types of chats and user profile view regardless of the fact user was added to contacts or not.
So, based on https://github.com/status-im/status-react/issues/8765 there are several inconsistencies that should be fixed.

#### 1. Adding user to contacts affects to displaying his name in profile.
It is inherited from a nickname - currently, if the user added to your contacts you are able to see his name.
Now if you are added as contact user will see:
![](https://user-images.githubusercontent.com/4557972/63860620-ba136500-c9a9-11e9-94a8-84fed24d69dc.png)
![](https://user-images.githubusercontent.com/4557972/63860621-baabfb80-c9a9-11e9-80e4-16eae6985d33.png)
![](https://user-images.githubusercontent.com/4557972/63860622-baabfb80-c9a9-11e9-8c31-97f37aaa2ff1.png)
![](https://user-images.githubusercontent.com/4557972/63860623-baabfb80-c9a9-11e9-8518-0321f9a09a4e.png)
Expected that in all these places will be default username, because "Show my ENS name in chat" setting is off.

#### 2. If "Show my ENS name in chat" setting is on, it should affect all places - public chats, group chats, 1-1 and user profile view
So when the setting is enabled ENS name should be shown in the following places (regardless you are added to contacts or not):

* 2.1. Рreview of 1-1 chat in Home Screen
![](https://user-images.githubusercontent.com/4557972/63862005-35761600-c9ac-11e9-82e2-4769ac53a432.png)
* 2.2. 1-1 chat
![](https://user-images.githubusercontent.com/4557972/63862024-3ad36080-c9ac-11e9-8ebe-f37a5d59cfac.png)
* 2.3. options in 1-1 chat
![](https://user-images.githubusercontent.com/4557972/63862041-40c94180-c9ac-11e9-8a7d-ab4398557376.png)
* 2.4. user profile
![](https://user-images.githubusercontent.com/4557972/63862073-47f04f80-c9ac-11e9-8614-e64a8e652a06.png)
* 2.3. group chat
![](https://user-images.githubusercontent.com/4557972/63862562-0dd37d80-c9ad-11e9-8db3-ed53dfafbc0c.png)
* 2.4. group info in group chat
![](https://user-images.githubusercontent.com/4557972/63862577-12983180-c9ad-11e9-8a82-c46963bfc294.png)
* 2.5. contacts list
![](https://user-images.githubusercontent.com/4557972/63862693-4a9f7480-c9ad-11e9-911a-3d88ef00898c.png)
* 2.6 preview of chat settings
![](https://user-images.githubusercontent.com/4557972/64241800-af565400-cf04-11e9-934f-6fc20fc3ce16.png)

### Summary

* [ ] remove link between adding user to contact and displaying of ENS name completely

**When setting "Show my ENS name in chat" is on, add ENS name to:**

* [ ] preview of 1-1 chat in Home Screen
* [ ]  1-1 chat
* [ ]  options in 1-1 chat
* [ ] user profile (full ENS + dafault 3-word random name)
* [ ] group chat
* [ ] group info in group chat
* [ ]  contacts list
* [ ] preview of chat settings in ENS name

**Comment by churik** [comment]
@errorists - please, review it - everything is correct here?

cc @rachelhamlin

**Comment by errorists** [comment]
Correct! I think we can agree that his is common sense that we should not have inconsistencies in displaying usernames and whichever you selected (displaying ENS name or not) in the setting should populate everywhere a username is used. It's not merely a replacement for the current display name scheme, it's a new global identifier that you can choose to broadcast publicly or not.

**Comment by errorists** [comment]
@churik by the way a question if you will, in the latest Jenkins build, when I toggle 'Show my ENS username in chats' the preview below it doesn't update to match the setting, it always shows my random funny name, is that a known bug? it should show the ens username when toggled on.

**Comment by churik** [comment]
I'll add it to description. Thanks for noticing.

**Comment by errorists** [comment]
![ens](https://user-images.githubusercontent.com/4932774/68392562-4ee4cc80-016a-11ea-9a55-7e5736d33d5a.png)

can i drop this here and ask kindly whomever is working on this to address those. you're awesome.

**Comment by flexsurfer** [comment]
thanks @errorists

**Comment by flexsurfer** [comment]
### Summary

- [x] remove link between adding user to contact and displaying of ENS name completely

**When setting "Show my ENS name in chat" is on, add ENS name to:**

- [x] preview of 1-1 chat in Home Screen
- [x]  1-1 chat
- [x]  options in 1-1 chat
- [x] user profile (full ENS + dafault 3-word random name)
- [x] group chat
- [x] group info in group chat
- [x]  contacts list
- [x] preview of chat settings in ENS name

**Comment by flexsurfer** [comment]
| 1-1 chat in Home Screen | 1-1 chat | options in 1-1 chat |
| ------------- | ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/11790366/68591479-21ad5c80-0491-11ea-9f57-7922003a67aa.png) | ![image](https://user-images.githubusercontent.com/11790366/68591509-32f66900-0491-11ea-88cc-cf5d367f2a8e.png) | ![image](https://user-images.githubusercontent.com/11790366/68591551-41dd1b80-0491-11ea-84d0-eeccb1300f7f.png) |

**Comment by flexsurfer** [comment]
| user profile  | contacts list | preview  in ENS name |
| ------------- | ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/11790366/68591596-5e795380-0491-11ea-94ef-7dfd90e2d85a.png) | ![image](https://user-images.githubusercontent.com/11790366/68591723-ab5d2a00-0491-11ea-9e0e-ef3da93a5ff4.png) | ![image](https://user-images.githubusercontent.com/11790366/68591800-d34c8d80-0491-11ea-8e58-89aff542bc72.png) |

**Comment by churik** [comment]
@churik 
TC 6226 should be completed in scope of this PR.

related to https://github.com/status-im/status-react/pull/9428

**Comment by flexsurfer** [comment]
| group chat  | group info in group chat |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/11790366/68594055-0d6c5e00-0497-11ea-8443-812d79424c4a.png) | ![image](https://user-images.githubusercontent.com/11790366/68664224-4ad8f600-0540-11ea-848e-fc1249f70831.png) |
