### ISSUE TITLE
Fiddle - icon images, fonts are not loading, and console errors

### ISSUE THREAD

**Issue by bitsikka** [status-im/status-react#8866]
# Problem

In an attempt to add more cases for `list-item` ran into some problems
- icon images are not loading
- fonts rendered is default `Serif` font
- browser console errors

cc @flexsurfer 

------
![screencapture-localhost-9500-2019-08-29-17_24_33](https://user-images.githubusercontent.com/42058840/63938114-c4a22d00-ca83-11e9-8ef8-2ebbdfe814fd.png)
------
![Screen Shot 34](https://user-images.githubusercontent.com/42058840/63938085-b522e400-ca83-11e9-9f7b-bb7c3f93fe76.png)

**Comment by flexsurfer** [comment]
thanks! errors is fine :) to have icons you need to run `clj prepare.clj`

**Comment by flexsurfer** [comment]
i'm not sure about fonts , they should be loaded from here https://rsms.me/inter/inter.css, can you access this url?

**Comment by bitsikka** [comment]
> thanks! errors is fine :) to have icons you need to run `clj prepare.clj`

got it 👍 

Re: errors I think we can get rid of some like i18n by adding in deps.edn or something- going to try it - I required it in `list-item` namespace for convenience

btw - I can kind of see where this is going `status-react-web` 😄 would be so awesome!

**Comment by bitsikka** [comment]
> i'm not sure about fonts , they should be loaded from here https://rsms.me/inter/inter.css, can you access this url?

it loads up fine on the browser when I click on it. Maybe if I get rid of as many errors as possible it will help.

Maybe also CLJS Webtools chrome extension is messing it. Will disable it and try again in leisure.

**Comment by flexsurfer** [comment]
@bitsikka what browser do you use? doesn't work for me in safari as well

**Comment by bitsikka** [comment]
I use google chrome :(
