### ISSUE TITLE
[Type a message] placeholder for Account added screen is misleading

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8875]
# Problem

`Type a message` placeholder looks odd for account name. Please change to more appropriate copy and get back [Account 1] autofill

## Steps

1. open status
2. open wallet
3. add account

![image](https://user-images.githubusercontent.com/28752642/64025518-853c1500-cb45-11e9-8f95-e95d6425d023.png)

**Comment by churik** [comment]
Fixed in Status v1.0.1
