### ISSUE TITLE
Fix deprecated webview API issue

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8897]
# Problem

Not sure if this is a release blocker; docs do not detail when Apple will stop accepting use of this API. 

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "Status - Ethereum. Anywhere." 0.13.2 (2019090313). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by rachelhamlin** [comment]
@siphiuel curious - do you think we need to prioritize this one for v1?

**Comment by vitvly** [comment]
@rachelhamlin this is in scope for webview migration, as UIWebView was removed from community webview back in version 7.0.1: https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1

**Comment by rachelhamlin** [comment]
@siphiuel will we run into trouble when we submit v1 with UIWebView included?

**Comment by vitvly** [comment]
@rachelhamlin I don't think so, this is only a deprecation warning. As Apple hasn't yet provided an exact deadline when they will actually start rejecting apps with UIWebView, we should be safe for now. Once Apple provides the deadline, I think there will still be a fair amount of time (> 1 month) before it comes into effect.

**Comment by rachelhamlin** [comment]
Great :) that's good to hear. Thanks @siphiuel.

**Comment by churik** [comment]
as I can understand, issue is still relevant in Status v1.0.1

**Comment by vitvly** [comment]
Closed in https://github.com/status-im/status-react/pull/10090
