### ISSUE TITLE
Message is sent on Enter but input field is not cleared 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#890]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to send multiple messages by tapping Enter so that I can chat.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User types text in chat and taps on Enter to send it. As a result:

1. Text is sent
2. Input field contains text 
3. Cursor is moved to the next line in the input field

Note: this issue does not exists in iOS. It works fine in iOS: user taps on Return -> text is sent and input field is cleared

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When user taps on enter -> text is sent and input field is cleared
#### Actual behavior
[comment]: # (Describe what actually happened.)
When user taps on enter -> text is sent; input field is not cleared and contains sent text; cursor is on the next line
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
screencast: https://www.screencast.com/t/FY5nmFdV9yQ
- Open Status, login
- Open Contacts and open any contact
- type "1" and tap on enter 
- type "2" and tap on enter

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3
* Operating System: Android

**Comment by coyotespike** [comment]
@annadanchenko I can reproduce this issue with my physical keyboard. When I use the software keyboard on Android emulator, the text input is cleared correctly. Are you using software/real device, or computer keyboard?

**Comment by annadanchenko** [comment]
@coyotespike I'm using a real Android device: Galaxy S6 and S7

**Comment by annadanchenko** [comment]
Not a bug anymore. Now, hitting on enter adds new line to the input instead of sending a message
