### ISSUE TITLE
"Null is not an object" crash when tapping on "Learn more" screen during onboarding

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8901]
### Description

*Type*: Bug
*Summary*: tapping on "Learn more" link during onboarding leads to crash (on "Choose key and name", "Select key storage")
For e2e it is required to add accessibility-id to this link to prevent this to happen in the future.

#### Expected behavior
no crash

#### Actual behavior
<img width="467" alt="cvxvc" src="https://user-images.githubusercontent.com/4557972/64188262-5b9b2a80-ce72-11e9-9c6f-636682a03a4f.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Tap on "Generate new key"
- Tap on "learn more"

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 03/09/2019
- Operating System: Android, iOS

### Logs
[status_logs-1.zip](https://github.com/status-im/status-react/files/3570341/status_logs-1.zip)

**Comment by churik** [comment]
сс @rachelhamlin

**Comment by Serhy** [comment]
Should be fixed after https://github.com/status-im/status-react/pull/8903 is merged

**Comment by vitvly** [comment]
Added accessibility-label to `Learn more` links in https://github.com/status-im/status-react/pull/8903.
