### ISSUE TITLE
Can't add custom bootnode, toggle is broken

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8902]
# Problem

Can't add custom bootnode, toggle is broken

## Steps

1. open status
2. tap profile
3. tap advanced
4. tap bootnodes
5. tap toggle on/off -> toggle is NOT enabled
6. add a custom bootnode and save ( for example enode://a8a97f126f5e3a340cb4db28a1187c325290ec08b2c9a6b1f19845ac86c46f9fac2ba13328822590fd3de3acb09cc38b5a05272e583a2365ad1fa67f66c55b34@167.99.210.203:30404)

Actual result: bootnode is not saved, toggle could not be enabled

![image](https://user-images.githubusercontent.com/28752642/64190440-116c7600-ce7f-11e9-998b-faa96de523e5.png)

## Notes:

build: nightly 03-09-2019 https://status-im.ams3.digitaloceanspaces.com/StatusIm-190903-025900-df3473-nightly.apk
device: ios 12.4, android 8

**Comment by rachelhamlin** [comment]
Hmm, I hope this is just the toggle and not the boot node setting itself.
