### ISSUE TITLE
UI Components

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8920]
1) Colors

* [ ] [GHI xs] rename colors names according to figma 
Example: `Light Grey` -> `:light-grey`
Figma: https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=787%3A807

2) Icons

* [ ] [GHI xs] rename namespace `status-im.ui.components.icons.vector-icons` to `status-im.ui.components.icons` and `vector-icons` aliases to `icons`

3) List items

* [ ] [GHI m] replace all implementation and usages in the app by `list-item` component, remove item components in `status-im.ui.components.list.views`, move `status-im.ui.components.list.views to status-im.ui.components.react`

4) Top bar

* [ ] https://github.com/status-im/status-react/issues/8981 implement topbar component similar to list-item component, move statusbar into topbar, replace all usages of statusbar and toolbar on new topbar, implement `{:type :big}` for topbar and use large-toolbar implementation
First iteration https://github.com/status-im/status-react/pull/9711

5) UI elements (buttons , switches, checkboxes) 

* [ ] [GHI s] replace all implementation and usages in the app by new UI elements 

6) Toolbar 

* [ ] [GHI s] replace all implementation and usages in the app by new toolbar

7) Snackbar 

* [ ] [GHI s] implement snackbar similar to list-item

**Comment by cammellos** [comment]
@flexsurfer I'll close this for now as looks stale, feel free to re-open if still relevant (just doing some spring cleaning :) )
