### ISSUE TITLE
Disable camera sound when device is in silent mode

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8924]
# Problem

When taking photo on a device with a silent mode enabled -> camera still makes sound

## Steps:

Turn on silent mode on your device

1. open status
2. profile -> edit user picture
3. tap capture and capture a photo

**Comment by asemiankevich** [comment]
@rachelhamlin bounty? :)

**Comment by churik** [comment]
not relevant for Status v1.0.1
