### ISSUE TITLE
Loading screen on sign out

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8927]
# Problem

When pressing sign out, the user can sometime briefly see a profile screen with "Unknown" as name.

## Implementation

This is due to the fact that all user data is flushed on sign out but for a moment the profile screen is still visible.
A spinning wheel similar to what is shown on account creation and login should be shown instead.

## Acceptance Criteria

User never sees "Unknown" profile

**Comment by yenda** [comment]
@rachelhamlin good candidate for bounty

**Comment by rachelhamlin** [comment]
@yenda FYI to request a bounty, please label 'bounty-awaiting-approval' and add to project Status Bounty Tracker, I'll be much more likely to see it!
