### ISSUE TITLE
Update to reagent 0.8

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#8928]
# Problem

In many components we need to return multiple Dom nodes at once, to achieve that we use a warpping view but that is inneficient because it requires creation of a superfluous Dom nodes.

## Implementation

React has a solution for that named fragments
Reagent 0.8 introduces a syntax to use react fragments
Updating reagent will allow use to use that syntax https://github.com/reagent-project/reagent/blob/master/doc/ReactFeatures.md#fragments

## Acceptance Criteria

Reagent is updated

**Comment by Ferossgp** [comment]
Now 0.9.1 is also available with more improvements

**Comment by yenda** [comment]
Awesome, we'll look into this after v1!

**Comment by rachelhamlin** [comment]
Hey gang - just checking in, is this a must-have for the next release? As a lay person, I don't understand the risk/benefit :) @yenda @Ferossgp
