### ISSUE TITLE
"Done" ("Intro" for IOS) on native keyboard during ENS name setup open sign transaction screen instead of proceeding to next screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8933]
###  Description

*Type*: Bug
*Summary*: if you tap on "Done" ("Intro" for IOS) on the native keyboard during ENS name registration you will see transaction screen even you are the owner of username and don't need to sign the transaction.

#### Expected behavior
"Username is added" screen

#### Actual behavior
transaction screen
![xzzvxxvcx](https://user-images.githubusercontent.com/4557972/64426749-b7062c00-d0af-11e9-838a-5fc4348a62df.gif)

### Reproduction

- Open Status
- Restore key, that owns ENS name, ENS name should be associated with chat key
- Go to Profile
- Tap on ENS -> enter name that is owned by you
- Tap "Done" on native keyboard  ("Intro" for IOS)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 06/09/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by yenda** [comment]
@churik @rachelhamlin I tested that one on Android OP7P with my account and it seems like it is already fixed?

**Comment by churik** [comment]
will check today and close if not relevant.

**Comment by churik** [comment]
Issue is gone, confirmed on Android8 - LG V20 and IOS 13 - IPhone7.
