### ISSUE TITLE
Only one sticker is shown in "Recently used"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8934]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: if you are using stickers, only one is shown on the "Recently used" screen. I would prefer to see the list of the "Recently used" stickers instead of blank space.

#### Expected behavior
several stickers in "Recently used"

#### Actual behavior
![photo_2019-09-06 14 36 51](https://user-images.githubusercontent.com/4557972/64428425-f9316c80-d0b3-11e9-952f-03e9f7003a0a.jpeg)

### Reproduction

- Open Status
- Join public chat
- Install sticker pack
- Send several different stickers
- Tap on sticker in input field -> open "Recently used" 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 06/09/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
@rachelhamlin don't think it is `v1`
Mark it if you think it should be included.

**Comment by errorists** [comment]
+1 it should most definitely contain a list of stickers used recently, ordered chronologically by the most recent ones going from top left to bottom right. We might discuss the number of stickers to keep here, from a user perspective it's around 24, if performance sucks then less.

**Comment by rachelhamlin** [comment]
Agreed that we can live without it for v1, but annoying!
