### ISSUE TITLE
SMS with confirmation code is not received by Instabug reporters from USA and Canada

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#894]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to receive text message with confirmation code so that I can confirm my phone number.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Several USA users are reporting in Instabug that sms is not received
  * number format +1206####### and +1-206-###-#### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/295
  * +1864####### and (864) ###-#### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/269
  *  +1514####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/224
  * +1773####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/297
  * 623####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/256
  * 630####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/253
  * 303####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/251
  *  240####### https://dashboard.instabug.com/applications/status/beta/bugs/123
  *  734####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/314
  * https://dashboard.instabug.com/applications/status/beta/bugs/138
  * https://dashboard.instabug.com/applications/status/beta/bugs/140
  * https://dashboard.instabug.com/applications/status/beta/bugs/142
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/329
* https://dashboard.instabug.com/applications/status/beta/bugs/170
* 208####### https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/341
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/340
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/337
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/346
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/347
* https://dashboard.instabug.com/applications/status/beta/bugs/205
* https://dashboard.instabug.com/applications/status/beta/bugs/193
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/398

Canada numbers:
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/313
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/324
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/331
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/333
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/384

Spain:
* +1818####### and 818####### https://dashboard.instabug.com/applications/status/beta/bugs/163

India:
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/405

New Zealand
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/482

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
sms is received
#### Actual behavior
[comment]: # (Describe what actually happened.)
sms is not received
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status 
- In Console tap on message "Tap here to enter your phone number"
- Type phone number and send it
- Wait for a text message to be received by the phone

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3
* Operating System: Android and iOS

**Comment by sla-shi** [comment]
I checked the Twillio logs and found that 8.1% of SMS not delivered in August 2017.  Not sure it's acceptable ratio and we can see if we implemented the StatusCallback parameter when sending SMS https://www.twilio.com/docs/api/rest/sending-messages#example-1 
Is it possible to set the callback URL to the running Status app and handle the HTTP request @rasom ?

**Comment by asemiankevich** [comment]
I am not receiving this code in '0.9.10-351-gc9c5c579+` build

**Comment by annadanchenko** [comment]
Phone feature is removed
