### ISSUE TITLE
At attempt to add ENS name purchased on another domain requires 10 SNT (equal to purchasing new ENS name on stateofus.eth)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8941]
###  Description

*Type*: Bug

*Summary*: when I own a name on another domain (i.e. `.eth`) from my POV there should be only one transaction performed to bind my ENS name and chat key. Currently, the app requires 10 SNT like you are purchasing the name one more time.

#### Expected behavior
the transaction with 0 ETH to bind my ENS name and chat key 

#### Actual behavior
![ENSname](https://user-images.githubusercontent.com/4557972/64436078-ec1c7980-d0c3-11e9-99e1-0901d53d50fe.gif)

### Reproduction

*Prerequisites:*  owned an ENS purchased on another domain

- Open Status
- Recover key
- Go to Profile > ENS
- Get Started > I own a name on another domain
- Enter name that is owned by you
- Tap on "Proceed" button

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 06/09/2019
- Operating System: Android, iOS

**Comment by asemiankevich** [comment]
@rachelhamlin  
@flexsurfer

**Comment by churik** [comment]
can be related to https://github.com/status-im/status-react/issues/8853 - so need to be rechecked in PR with fix

**Comment by rachelhamlin** [comment]
Okay, will not bounty it yet—can probably be fixed within scope of #8853 regardless.

**Comment by 3esmit** [comment]
I experienced this. Seems like that the application is missing the case of "update key". It is trying to register the username again, which will fail the transaction because the username is already registered. I will comment more on this on the issue about change whisper id feature that Rachel referenced above.

**Comment by 3esmit** [comment]
When the chat key (x,y of pub key) are updated the UI will allow me to add that as my username, that is the case. So this happens only when the Whisper ID is not of the current user.

**Comment by rachelhamlin** [comment]
@yenda can I close this issue and fold it into the acceptance criteria for #8853?

**Comment by yenda** [comment]
@rachelhamlin yes

**Comment by rachelhamlin** [comment]
Feels good
