### ISSUE TITLE
Different sticker selection panel height than native keyboard [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8942]
***Type***: Bug

***Summary***: When sticker icon from message insput is tapped the sticker selection panel is higher than native keyboard [iOS]
We need to alight sticker selection to fit native keyboard height

#### Expected behavior
Sticker selection panel height = native device keyboard height

#### Actual behavior

<img width="454" alt="Screenshot 2019-09-06 at 18 04 45" src="https://user-images.githubusercontent.com/8749671/64438469-d6618100-d0d0-11e9-8008-f4c09254e61c.png">

### Reproduction

- Open Status and create new account
- Join public chat
- Tap in message input
- Tap upon stickers icon in message input 

### Additional Information
- Status version: Develop 0.14.0 (2019090603)
- Operating System: iOS

**Comment by Serhy** [comment]
@rachelhamlin it's not V1 priority as for me. Maybe worth for bounty.

**Comment by errorists** [comment]
just fyi I was under the impression this is not possible, that we could not sample the height of the system keyboard cc @flexsurfer cause he's the grand wizard behind this :)

**Comment by rachelhamlin** [comment]
Yes, that's what we heard on the call today...definitely nice-to-have, open to alternative solutions as well.

**Comment by churik** [comment]
still relevant (nightly 26/02/2020)

**Comment by errorists** [comment]
I don’t think it’s relevant anymore, I recall we specifically addressed this and on my iPhone they both share the same height.
