### ISSUE TITLE
High power consumption on syncing

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#895]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Phone power consumption is high and phone gets hot for several Instabug reporters:
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/289
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/288
  * https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/201
  * https://dashboard.instabug.com/applications/status/beta/bugs/104
  * https://dashboard.instabug.com/applications/status/beta/bugs/78
  * https://dashboard.instabug.com/applications/status/beta/bugs/73
  * https://dashboard.instabug.com/applications/status/beta/bugs/148
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Phone is not getting hot or user is warned about high power-consumption during specifc actions, so user knows what to expect
#### Actual behavior
[comment]: # (Describe what actually happened.)
Phone gets hot
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install and Open Status
- Let it sync

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.1, 0.9.2, 0.9.3
* Operating System: Android and iOS

**Comment by jarradh** [comment]
This may be alleviated by the pure go ethash generation and caching which will make it to status-go eventually, ultimately it will become less of an issue as LES protocol develops and the switch to Proof of Stake

**Comment by annadanchenko** [comment]
Instubug reports 0.9.6 version:
* https://dashboard.instabug.com/applications/status/beta/bugs/200

**Comment by jarradh** [comment]
This isn't going to change during proof of work, the good thing its really only the initial sync and then every ~30k blocks
