### ISSUE TITLE
"Automatic selection" in "Mailserver settings" is not aligned with checkbox

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8956]
### Description

*Type*: Bug

*Summary*: "Automatic selection" in "Mailserver settings" is not aligned with checkbox - it is located under checkbox

#### Expected behavior
"Automatic selection" label is aligned with checkbox

#### Actual behavior
<img width="188" alt="dsvsdf" src="https://user-images.githubusercontent.com/4557972/64531157-12822500-d30f-11e9-9ae9-f2ef0242f901.png">

### Reproduction

- Open Status
- Create account
- Open Profile > Sync Settings

### Additional Information

- Status version: nightly 09/09/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
Let's fix it, looks ugly

**Comment by churik** [comment]
@rachelhamlin remove label, if you think it is out of scope

**Comment by churik** [comment]
still relevant on nightly 07/01/2020

**Comment by rachelhamlin** [comment]
Sharing with Gheorghe.

**Comment by rachelhamlin** [comment]
Easy! 😍👏🏼 @Ferossgp
