### ISSUE TITLE
Wallet address can't be copied by tapping on it

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8957]
### Description

*Type*: Bug
*Summary*: during wallet redesign possibility to copy code by tap (as it made for profile > chat key) is lost.

#### Expected behavior
can copy address

#### Actual behavior
nothing happens
<img width="189" alt="xzcx" src="https://user-images.githubusercontent.com/4557972/64532916-b9b48b80-d312-11e9-9e0b-541dbfc9cf3e.png">

### Reproduction

- Open Status
- Create account
- Go to wallet > select Account
- Tap on receive
- Tap on wallet address 
### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 09/09/2019
- Operating System: Android, iOS

**Comment by errorists** [comment]
just to clarify, it should be a regular tap just like in profile, no long-press needed. On the same screen, the bottom margin below the Share button isn't the same as in the profile, it's larger, which is a small UI bug but maybe can be addressed in the same PR. 🙏
