### ISSUE TITLE
Mobile data syncing pop-up missing text

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8973]
# Problem

On the nightly, the 'sync mobile data' modal shows only the icons for each option, with no text:

<img src="https://user-images.githubusercontent.com/15470435/64769420-2f9f3980-d543-11e9-8c31-96c2417c0333.png" width=200/>

## Expected behavior

Text describes each option:

`Continue syncing`
`Stop syncing`

**Comment by yenda** [comment]
@flexsurfer I think it happened here https://github.com/status-im/status-react/commit/b18a04414675b7598a8746bb5a99488f19c39d88

**Comment by yenda** [comment]
@Serhy @churik do we have automated tests for this popup? can automated test catch it if the text is there but not visible? (not saying this is the case here, maybe it is just missing)

**Comment by churik** [comment]
no, we don't have. I can write test to check that options are presented and that Remember my choice is working, but unfortunately I can't emulate 3G network on emulator to check that whole feature is working as expected

**Comment by churik** [comment]
UPD: it wasn't right, seems Sauce Lab provides some possibility for checking app under different network speed, i'll investigate this
