### ISSUE TITLE
[Multi-account] Allow user to choose wallet for DApp transactions

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8977]
# Problem

**As a multiaccount user, I want to control which account I use to transact with DApps, so that (1) I never need to move assets between accounts to take advantage of DApps; and (2) my privacy can be better protected by not funneling all transactions through a single account.**

In v1, users can initiate transactions from the wallet screen (send/receive buttons) or from within a DApp. Chat commands are temporarily disabled.

Users deserve an option to select which of their accounts they transact with when using DApps. Currently, the 'default' account can not be changed. This severely limits the utility of multi-account. 

Update 2/10/19, after discussion btwn @flexsurfer, @simonricoo, @errorists, @hesterbruikman and @rachelhamlin:  

- Account selection will be global and apply to all previous tabs and DApps. 
- Cookies & data in previous tabs will be cleared.
- User will have to grant permission to DApp to access new account when opening again. 
- Out of scope: selection _within_ a DApp/tab.

A future, more privacy-centric model more in line with the [windows manager mentality](https://discuss.status.im/t/window-based-navigation/1374/7) would allow users to switch accounts or even have a dedicated account per DApp.

An additional future requirement might be to manage DApp permissions at an account level. They are currently global, tied to the current Status wallet. 

## Implementation

We've designed this control in context of the DApp browser.

[Figma screens](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=2998%3A0)

![image](https://user-images.githubusercontent.com/15470435/66035408-fc791600-e502-11e9-8146-4d45f6f54ce9.png)

## Acceptance Criteria

- From the browser home screen, a user sees the ['Account name' option](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=2998%3A153) at the bottom, it hides on scroll. 
- Clicking on 'Status account' opens a bottom sheet with a scrolling list of all the user's accounts.
- The [DApp permissions modal](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=3000%3A5095) reflects the specific account a user is connecting with, rather than just "wallet" generically. 

**Out of scope for this issue**
- Selection from within a DApp/tab

**Comment by 3esmit** [comment]
Very important to have a clear UX on this, especially when we use "account contracts" where users will always have 2 accounts, one it's "private key" and other its "account contract" (that is controlled by the user private key). 

### Account Select
Would be nice to give user a feedback on what is the "default account", and a way of user changing the default account. 
Other things that could be added to help guide user choice: "balance converted to user currency", "eth balance", "most valuable token balances first", "account type", "ens name", "identicon", "account nonce/txCount",

### Account Change
When the account is changed it could refresh the DApp screen, but thats not the best way. MetaMask currently developing a solution with events on the web3 object, see
https://metamask.github.io/metamask-docs/Advanced_Concepts/Provider_API#ethereum.on(eventname%2C-callback)

In past we used to check every 100 milliseconds if accounts changed (when that was needed), see this
https://medium.com/coinmonks/detecting-metamask-account-or-network-change-in-javascript-using-web3-1-0-0-18433e99df5a

### Network Change
Also (offtopic but related), the same applies to Network Change, while I would appreciate that we could easily change network, I understand that is a developer tool and can be left in a far/hidden screen, anyway it might also want to fire an event or reload the dapps.

**Comment by 3esmit** [comment]
Perhaps the account could be selected on the "Account Privacy Pop-up", which allows the Dapp to read the account in first place. 

The screen could also allow to derive a new account only for that dapp, this could be done by naming the account the same name of the dapp. The dapps should remember this decision, and always use the same account for the same dapp. 

Users should be able to switch between accounts, this could be:
1. a menu option, like browser options.
2. right before making a transaction, like in #8909 @andmironov designed

Changing the account right before a dapp transaction can be dangerous (transaction might be crafted for a specific account and invalid in other) so perhaps the number 2. should not be considered, and the field be only an indicator.  

Number 1. user could not only change accounts but also remove the dapp authorization, perhaps the button could bring again the screen of authorization, allowing user to reject or select another account.

**Comment by flexsurfer** [comment]
@3esmit i believe we must "reset" browser on account change, to clear all data, cookies etc from security and privacy pov?

**Comment by rachelhamlin** [comment]
Would a lower fi, less risky way of solving this problem be to allow the user to set a custom default account from the wallet screen? @simonricoo @flexsurfer

**Comment by 3esmit** [comment]
@flexsurfer No,  the **change of ethereum address should not refresh the page** and nither change local data, because can cause mistakes and certainly will cause annoyance. 

Ideally **DApps should detect those changes**. In past dapps used a "thread" (setInterval) in loop checking for a change in account, which was horrible, and so I understand your suggestion of refresh the page and local storage.
```
//Not a fun pattern to have to use

var account = web3.eth.accounts[0];
var accountInterval = setInterval(function() {
  if (web3.eth.accounts[0] !== account) {
    account = web3.eth.accounts[0];
    updateInterface();
  }
}, 100);
```

Now Metamask fires an event to Dapps handle the change, which some dapps might subscribe to.
See https://metamask.github.io/metamask-docs/Advanced_Concepts/Provider_API#ethereum.on(eventname%2C-callback)


The browser data, cookies and local storage must only change when the user logins in other Status account (other database, other mnemonic, etc), i.e. user logoff Status and chooses another "multiaccount" to login. 

_**Network change**_
_The network change also should not  change database, but only fire an event. In past Metamask used to refresh the page, but now it fires an event. The Network change case we can discuss in other issue, as is more complex than ethereum account change_ 

References:
[Detecting Metamask account or network change in Javascript using Web3 1.0.0](https://medium.com/coinmonks/detecting-metamask-account-or-network-change-in-javascript-using-web3-1-0-0-18433e99df5a)

**Comment by flexsurfer** [comment]
@3esmit but what the difference between multiaccount and account?  if i change account i still don't want dapp to know that another one is mine as well, maybe we could add a checkbox "clear data" enabled by default? @errorists

**Comment by 3esmit** [comment]
Ah, I see the issue. I think we need to rethink the flow of authentication of dapp.

1. when opens an tab user is opening a session, when he loads an app it would be not authenticated (no accounts) but it would have a db, cookies or whatever...
2. when user is requested account or when user manually go to accounts it can change what accounts are exposed, when there is a change that event is fired
3. if user don't want to mix identities, user opens a new tab and select an unique account from there.

We can add some warnings (with dont show again button) to alert user that he is mixing accounts and some dapp might track it.


It's hard to give you a fast path to fix this, If you want we can arrange an time for a call or a text discussion on Status.im channels.

**Comment by Ravi-webinfo** [comment]
![image](https://user-images.githubusercontent.com/3839401/162165937-ad0311f2-9f75-444a-bd5f-1d54a999e3dc.png)
