### ISSUE TITLE
Error 'Hzb.checkViodeoAuthorizationStatus in not a function' at attempt to scan QR on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8997]
###  Description

*Type*: Bug

*Summary*: when scanning QR code getting error 'Hzb.checkViodeoAuthorizationStatus is not a function' instead of dialog about granting permission to camera. 
Have a device with IOS 11.4.1. only, so would appreciate if someone can check on iPhones with newer versions.

#### Expected behavior
can scan QR

#### Actual behavior
![error5](https://user-images.githubusercontent.com/4557972/64871768-3b275900-d646-11e9-8633-addef0f977e8.png)

### Reproduction

- Open Status
- Create account
- Tap on + > Scan QR code

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 13/09/2019
- Operating System: iOS 11.4.1.

**Comment by Serhy** [comment]
The same with iOS 12.4.1 when opening camera in any place of app: 
`+ -> Scan QR code` 
`+ -> Start new chat -> button next to 'Enter chat key' input`
`Wallet -> Status account -> Send -> Specify recipient -> Scan QR code`
`Profile -> Edit upon profile userpic -> Capture`
