### ISSUE TITLE
'Enter your password' screen has no PW entry field when creating new account

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#8998]
# Problem

I was adding an account from the account explorer. To do so, you need to enter your Status password. However, the screen has no password input on it:

![image](https://user-images.githubusercontent.com/15470435/64873008-247e0380-d640-11e9-81cc-8b372b9dc728.png)

I am unable to move past this screen to generate a new account.

## Notes

Oddly enough, on the same build, when I did the same thing from a different root key, I was able to enter my password and add a second account to the explorer. 

## Acceptance Criteria

- Password input field appears
- Password input field does not cut off pw when entered (this happened the time I was able to successfully enter a pw - it's like the box was too short)

**Comment by churik** [comment]
@rachelhamlin are you sure that it is not possible to set focus on this field?
Any way to narrow the problem, can you please specify device / OS/ screen resolutions so I can recheck it on BrowserStack?

**Comment by vitvly** [comment]
Just checked that password input has autofocus set, so need to more how this can be reproduced. Is it on iOS?

**Comment by andmironov** [comment]
I don't know what is the best way to address that, but here's a general rule i can think of:

**when the input is invisible and entering something in it is the only "happy" flow, the keyboard should be persistent and it should be impossible to hide it**

because it's hard to get it back when you can't see the input

**Comment by rachelhamlin** [comment]
I don't remember what build this was on but haven't been able to reproduce it since, so I'm closing it.
