### ISSUE TITLE
Set of issues in chats ui in the epic/ui-refresh

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#900]
1) The menu does not close in ios simulator by pressing outside the menu
![image](https://cloud.githubusercontent.com/assets/11790366/23945222/c5a19260-0986-11e7-873e-f1bb4e679c35.png)
2) search in chats list works strange 
![image](https://cloud.githubusercontent.com/assets/11790366/23945241/e07e32be-0986-11e7-9d2f-11d1aba03357.png)
![image](https://cloud.githubusercontent.com/assets/11790366/23945256/eb69b540-0986-11e7-961b-b1a5e412f23e.png)
3)in active search there should be a clear button
![image](https://cloud.githubusercontent.com/assets/11790366/23945289/03c6448c-0987-11e7-961c-45c7a6d357fe.png)
4)search in "create new chat" screen works strange
![image](https://cloud.githubusercontent.com/assets/11790366/23945338/3c151070-0987-11e7-8698-b04c50877bfa.png)

**Comment by flexsurfer** [comment]
@GustavoNunes can you take a look on these issues

**Comment by GustavoNunes** [comment]
Thanks @flexsurfer! However, I can't reproduce the search issues (2 and 4), could you give more details on how these happen?
I will take care of 1 and 3.

**Comment by flexsurfer** [comment]
5)
![image](https://cloud.githubusercontent.com/assets/11790366/24034085/df7f7a78-0b00-11e7-8c9f-12cc57dcbe0c.png)

**Comment by flexsurfer** [comment]
@GustavoNunes about 3, you need to provide search text into toolbar-with-search, maybe it should be reworked later, this logic should be inside toolbar

**Comment by flexsurfer** [comment]
@GustavoNunes i think we should create separate issue for 2 and 4, because it's not related with ui-refresh
