### ISSUE TITLE
Impossible to add new account in wallet if profile is created with keycard

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9019]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: instead of PIN password is required when add new account

#### Expected behavior
PIN is required

#### Actual behavior
password is required

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new account with keycard
- Go to wallet
- Try to add new account

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 20/09/2019
[comment]: # (Android or iOS.)
- Operating System: Android

**Comment by guylouis** [comment]
-deleted- sorry I mixed up  two issues
