### ISSUE TITLE
Obtain access to the contacts profile picture via the Status DApp API

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-react#9024]
### Problem
In Teller Network, if a user has already added another user to their contacts, and then see their offers in the list of offers, they should be able to see that user's profile picture instead of the identicon. 

Currently we do not have a way to obtain that profile picture, the API does not provide such functionality, which would be useful not only for Teller Network, but for any DApp that wishes to have a greater level of integration with the Status App

### Suggested Implementation

```
window.ethereum.status
.getProfilePicture("0xCONTACT_PUBLIC_KEY_GOES_HERE")
.then(image => {
console.log('Base64 Image data:', image);
})
```

**Comment by flexsurfer** [comment]
@richard-ramos do you need user profile picture as well? I'm just thinking, maybe we could add one new permission - contacts and update profile permission
so it will be 
getUserProfile -  {contactCode , profilePicture, name}
getContacts - [{address, profilePicture, name} ] 
@hesterbruikman wdyt ?

**Comment by richard-ramos** [comment]
That would be great, because the user also has a profile in teller, so it would be nice to see their own picture too!

**Comment by hesterbruikman** [comment]
Aaaah:( I hate to make things complicated here, but I believe we can't introduce this feature without a change to dapp permission dialogs, at minimum. 

'Who you have added as a contact' could be privacy sensitive information. As a user and as Status I would want to know how the DApp handles this information. @simonricoo @errorists can you sync on what changes the permission dialog would need without investing too much effort for the time being?

In the meantime I think we should hash out the privacy impact in this thread so we can decide:

- do we allow for a getContacts function at all
- what might be done with this function (minimal threat modeling)
- If we allow getContacts function what should be communicated to the user allowing the sharing of contacts
- If we allow getContacts function what should be communicated to the user sharing their Whisper ID/Contact key to anyone else (as it might be exposed by the individuals with initial access)
- how might this feature be impacted when multiple chat keys are used

**Comment by cammellos** [comment]
Closing this as probably stale, feel free to re-open if necessary
