### ISSUE TITLE
Crash at attempt to use second multiaccount with keycard

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9028]
###  Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: if you have several keycards, at attempt to create a second account with keycard Status will crash.

#### Expected behavior
can use 2 accounts with keycard

#### Actual behavior
crash on "finishing up" stage and at attempt to login

### Reproduction

**Prerequisites:** have several keycards with pre-installed keycard applet

- Open Status
- Create account with keycard
- Log out
- Create second account with another keycard

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 24/09/2019
- Operating System: Android

#### Logs

Full logcat: [second_account.log](https://github.com/status-im/status-react/files/3647426/second_account.log)

**Comment by churik** [comment]
@guylouis should it be the part of v1 release?

**Comment by guylouis** [comment]
cc @yenda for his advice on the root problem
@rachelhamlin wdyt regarding priorities ?

I personally think we should have it part of v1, it comes down to being able to support :
- status manages several wallets(=multiaccounts)
- any multiaccount at creation can either be protected by a password on the phone, or by a keycard 

If for some reasons (priorities) we prevent not supporting more than one keycard wallet then we should have a warning pop-up when the user tries to set-up a second one

**Comment by guylouis** [comment]
cc @dmitryn too FYI

**Comment by rachelhamlin** [comment]
@yenda pinging you again - do you have insight into the problem? 

It seems logical to include. I am worried about the size of the v1 backlog. But if we don't support multiple keycards in v1, we need screens to explain that.

**Comment by dmitryn** [comment]
@rachelhamlin it's fixed in https://github.com/status-im/status-react/pull/9053

**Comment by rachelhamlin** [comment]
Awesome @dmitryn!

**Comment by guylouis** [comment]
@chu @rachelhamlin sorry if the question was already addressed and the answer is obvious: in the new QA process who closes issues like this one ?

**Comment by yenda** [comment]
@guylouis if the PR that claims to fix is merged it is closed automatically
