### ISSUE TITLE
Hide 'export account' option for v1

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9040]
# Problem

The `Export account` menu option needs to be hidden from the individual account settings menu for v1, as the feature will not be introduced until later:

<img src="https://user-images.githubusercontent.com/15470435/65600492-1d3beb80-df98-11e9-81cf-c1d361595ae5.png" width=250/>

## Acceptance Criteria

When you click into an account within the account explorer and tap the '...' toolbar, you should see only the `Account settings` option (currently inactive, but should be implemented in #8446).

**Comment by yenda** [comment]
@rachelhamlin what was that option suppose to do exactly?

**Comment by rachelhamlin** [comment]
@yenda pretty sure it's for this keystore flow: https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Mobile-wallet?node-id=3294%3A31930 (I wasn't part of that design review)
