### ISSUE TITLE
Use images the right way

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#9045]
# Problem

We have multiple way of using images

## Implementation

https://facebook.github.io/react-native/docs/images

Remove
```
src/status_im/ethereum/macros.clj:26:(defmacro resolve-icons
src/status_im/ethereum/macros.clj:47:(defmacro resolve-native-currency-icons
```

## Acceptance Criteria

No more images in android/ and ios/

**Comment by hesterbruikman** [comment]
Superseded by images over Waku
