### ISSUE TITLE
Can't type ENS name in "New chat" screen (when start typing "0X04" appears)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9046]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when start to type ENS name, can't finish because "0X04" appears on the start of the string, and it is not possible to delete it.
Also when you paste valid ENS - it is replaced by public key 

#### Expected behavior
can type ENS

#### Actual behavior
0X04 appears
![lop](https://user-images.githubusercontent.com/4557972/65612186-28047980-dfb4-11e9-80b1-6062d4edd687.gif)

### Reproduction

- Open Status
- Tap on + > Start new chat
- Start typing ENS name

### Additional Information

- Status version: nightly 25/09/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
Was introduced on nightly 11/09/2019

**Comment by yenda** [comment]
@siphiuel could it be b215292b2307a1f59080d480d96e2e8016dee64a ?

**Comment by vitvly** [comment]
@yenda hm, could be, have to investigate where this 0x04 comes from

**Comment by yenda** [comment]
It comes from `status-im.ethereum.ens` uncompressed public key

**Comment by yenda** [comment]
```
;; Set default-value as otherwise it will
                          ;; be erased in global `onWillBlur` handler
                          :default-value       new-identity
```
in `new_chat.views`, the problem is that new-identity should not be the default value if there is an error

**Comment by vitvly** [comment]
Will fix this, introduced in my PR, thanks @yenda for the hint.
