### ISSUE TITLE
Nothing happens when holding keykard right back agains after error

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9057]
### Description

*Type*: Bug
*Summary*: it is not possible to continue working with keycard from the same screen after any error (i.e. "Not keycard applet installed") at attempt to hold the same card to the back of the phone "Connection to the card is lost" appeared, and if you hold right card - nothing happens. To proceed you need to go back and open this screen again.

Screens where I can reproduce this issue:
- generate new key > keycard > Hold card to the back of your phone to start

- settings > change PIN > enter right PIN > hold wrong card > hold right card: endless spinner
- settings > change PIN >  enter right PIN > hold wrong card > hold right card: endless spinner

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 27/09/2019
- Operating System: Android

**Comment by churik** [comment]
@andmironov please take a look

**Comment by andmironov** [comment]
Addressed in https://github.com/status-im/status-react/issues/9367 and in other issues where this bug occurs
