### ISSUE TITLE
Separate status-react issue templates into bug & feature

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9058]
@jakubgs would you do the honor? Assuming we can override the existing templates in status-react (`Full Bug Report` and `Simple Issue Report`), I think this makes more sense:

### Full Bug Report --> Feature Issue

[Old template in hackmd](https://hackmd.io/wR7LASy4R2uT2uy0XK2DXg)
[Proposed template in hackmd](https://hackmd.io/8Qnps_oQRWWcti-7kMcYxw)

### Simple Issue Report --> Bug Report

[Old template in hackmd](https://hackmd.io/OMVZwJ8yS9KUdeYHlS7g3A)
[Proposed template in hackmd](https://hackmd.io/z_83ZYUtTZC2fjhoolTFsw)

**Comment by jakubgs** [comment]
What about the `Issue default title`, do you have any suggestions for this?

(Also, we have https://notes.status.im/, use that instead of https://hackmd.io/)

**Comment by jakubgs** [comment]
PR for updating the templates: #9060
