### ISSUE TITLE
Account balance is not fetched when multiaccount is created with keycard

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9061]
###  Description

*Type*: Bug

*Summary*: if multi-account is created with the keycard, the balance of account is not fetched.
It remains with "..." instead of converted value regardless of network.
Is reproducible for me every time and only with accounts, created with keycard.

However, the overall balance of the whole multiaccount is updated after relogin - but balance of separate account remains unchanged.

#### Expected behavior
"0 USD"

#### Actual behavior
... USD
![Screenshot_20190927-164648_Status](https://user-images.githubusercontent.com/4557972/65775110-d5f05f00-e13f-11e9-93b8-a6e94deecb56.jpg)

### Reproduction

- Open Status
- Create account with keycard
- Wait several minutes and check account balance
- Relogin

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 27/09/2019
- Operating System: Android

**Comment by guylouis** [comment]
as noted by @churik , this bugs prevents performing any transaction from the wallet it self or from dApp
