### ISSUE TITLE
Store eip1581 extended key

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#9088]
# Problem

After a discussion triggered by https://github.com/status-im/status-react/pull/9033 it was decided to store the extended key at path `m/43'/60'/1581'` so that in the future if and when we would like to derive an encryption key from this path it will be available to the user without having to input their seed phrase again.
This has no impact on the user experience, so it's just a technical task.

## Acceptance Criteria

- The key at path `m/43'/60'/1581'` should be stored encrypted on disk, similarly as we do with the chat key (`m/43'/60'/1581/0'/0'`) and wallet key (`m/44'/60'/0'/0/0`)
- Stop storing the master key
- Store instead of the master key the key at `m/44'/60'/0'/0/` and use that to derive wallets
- Ensure that this key can be accessed by the application
- Update https://notes.status.im/QxNC1H2cQMG7t8GvEb_Ctw with the relevant key informations

**Comment by cammellos** [comment]
cc @gravityblast @corpetty @andremedeiros 

Could you have a look everything makes sense? 

@gravityblast I will want to ask a few questions, what the best way to reach you these days? (emails/status?). Thanks!

**Comment by flexsurfer** [comment]
but we store root key, and we can derive encryption key in any time no? why do we need to enter seed phrase?

**Comment by flexsurfer** [comment]
so currently we encrypt and store root key using user password, what we want to do later, ask user a password derive encryption key from root key, encrypt and store root key using derived encryption key and remove user password?

**Comment by cammellos** [comment]
> but we store root key, and we can derive encryption key in any time no? why do we need to enter seed phrase?

From the conversation had yesterday, my understanding is that we do not store the master key, but only those that we use to derive extra chat keys (`m/43'/60'/1581'/0'...`) and extra wallet `m/44'/60'/0'...`), the encryption key would be a leaf of `m/43'/60'/1581'`, which we currently do not store, so the task would be to store that, from which whisper keys, but not wallet keys can be derived.

> so currently we encrypt and store root key using user password, what we want to do later, ask user a password derive encryption key from root key, encrypt and store root key using derived encryption key and remove user password?

apart from the conversation about root key, how we would do is:
1) Store `m/43'/60'/1581'`, encrypt with the user password (this task)
2) Once we decide to switch to an encryption key derived by that key, on first login we would do something like:
  - Decrypt key with user password
  - Derive encryption key
  - Migrate the database from one key to the other
  - Store encryption key in secure enclave/keychain protected by the user password (or biometric if enabled)
  At this point the `1581` extended key could be deleted if we wish to do so.

Does that make sense to you? (and others)

**Comment by yenda** [comment]
We do store the root key for non keycard accounts

**Comment by gravityblast** [comment]
the master key is never stored. I think with "root key", @flexsurfer means the parent of the BIP44 key, which is used to derived the next child keys. At least I see in the clojure code we call it `path-root`:

`(def ^:const path-root "m/44'/60'/0'/0")`

**Comment by gravityblast** [comment]
in theory we never want to store the master key, otherwise there's no reason to store the others, we can just derive them.

@yenda @flexsurfer are we using `MultiAccountStoreAccount`?
We should only use `MultiAccountStoreDerivedAccounts` passing the master key, so that only the derived accounts are saved.

 `MultiAccountStoreAccount` can be use in case an imported key is not an extended key, so we just want to store it instead of deriving other keys.

**Comment by gravityblast** [comment]
here is the documentation about the account generator:

https://github.com/status-im/status-go/blob/develop/account/generator/README.md

**Comment by gravityblast** [comment]
> StoreAccount stores the key identified by its ID, so in case the key comes from Generate or ImportPrivateKey, it will store the master key. In general we want to avoid saving master keys, so we should only use StoreDerivedAccounts for extended keys, and StoreAccount for normal keys.

**Comment by cammellos** [comment]
@yenda looking at the code does seem we save the master key, `storeAccount` with the id of the multiaccount the user selected, I'll look into it, I will remove it and instead save the parents of the keys if we need to derive again ( `"m/44'/60'/0'/0"` `m/43'/60'/1581'` ), any objections?

**Comment by corpetty** [comment]
no problem from me here.

**Comment by corpetty** [comment]
could we get comments on which key we store in the code to be inline with naming described in this doc: https://notes.status.im/QxNC1H2cQMG7t8GvEb_Ctw

**Comment by cammellos** [comment]
Update on progress:
seems like we are storing the master key, it is currently used to generate new wallet addresses.
So the scope of the task has changed to:
1) Stop storing master key
2) Store instead `"m/44'/60'/0'/0"` from which any wallet key can be derived

In addition to storing eip1581, from which any chat key can be derived.
I will update the task.

**Comment by rachelhamlin** [comment]
Thanks @cammellos :)
