### ISSUE TITLE
Blank profile screen in Status Desktop

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#9091]
# Problem

When user switches to own profile page it shows blank. But if he scrolls it with mouse content appears.
Same issues exists when open profile pages of other users.

## Implementation

TBD

## Acceptance Criteria

Profile page shows all information

## Notes

**Comment by churik** [comment]
still relevant

**Comment by churik** [comment]
Is not relevant anymore according to current desktop work (confirmed with @vkjr)
