### ISSUE TITLE
Desktop crashes after account recover in dev mode

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#9098]
# Problem

When launched in dev mode status desktop fails with red screen:

![Screen Shot 2019-10-02 at 7 16 19 PM](https://user-images.githubusercontent.com/5786310/66062174-9499ee00-e549-11e9-89cc-cf00532e8f61.png)

## Implementation

TBD
## Acceptance Criteria

Status desktop should successfully start in dev mode

**Comment by churik** [comment]
still relevant

**Comment by churik** [comment]
Is not relevant anymore according to current desktop work (confirmed with @vkjr)
