### ISSUE TITLE
Feature/profile ui refresh leftovers [ui-refresh]

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#911]
See comment, https://github.com/status-im/status-react/pull/899#issuecomment-287289687, item 1 and 2 in Android section

**Comment by flexsurfer** [comment]
1. - [x] list background ( mockup fixed)
2. - [x] empty field  (mockup updated and code implemented)

**Comment by jarradh** [comment]
Name field is empty with no placeholder? Should we just use grey randomly generated name

It's not clear to me what List Background is

**Comment by flexsurfer** [comment]
list background Android
![image](https://cloud.githubusercontent.com/assets/11790366/24184911/6433107a-0ee1-11e7-96e9-c83e7bb17bb9.png)

**Comment by flexsurfer** [comment]
empty Name field will be reworked in another PR
