### ISSUE TITLE
Status specific User-Agent HTTP header

### ISSUE THREAD

**Issue by tpatja** [status-im/status-react#913]
### User Story

As a user, I would like Status to use uniform User-Agent HTTP headers on both platforms.

### Description

*Type*: Improvement

*Summary*: Use Status-specific user-agent header, so identifying Status users is simpler

Currently, the following user-agent strings are used:

iOS: `StatusIm/1234 CFNetwork/808.3 Darwin/16.3.0`
Android: `"okhttp/3.4.1"`

The immediate benefit of this will be getting metrics of Status users on commiteth.com.

### Solution
I propose `StatusIm <version>/<platform>` for the header value.

This blog post has instructions on how to set the header: http://blog.bigbinary.com/2016/07/10/passing-user-agent-or-custom-header-in-react-native-webview.html

**Comment by jarradh** [comment]
I'm not sure about this, tbh it seems like leaking information about the user to me?  How is this not a violation of privacy?

**Comment by jarradh** [comment]
If we do it, it should be generic imo

**Comment by tpatja** [comment]
I don't think indicating Status being used in the User-agent header violates the user's privacy.

If the value contained something specific about **a** user, that would be a violation, but indicating the software used is just [common](https://tools.ietf.org/html/rfc7231#section-5.5.3) practice.

**Comment by chadyj** [comment]
We now provide a way to identify Status
https://wiki.status.im/Adding_your_DApp_to_Status#Identify_Status_Client

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://wiki.status.im/Adding_your_DApp_to_Status#Identify_Status_Client">Adding your DApp to Status - Status Wiki</a></strong></div></blockquote>
