### ISSUE TITLE
Group chat UI cleanup [DRAFT]

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9131]
# Problem

Skeleton issue to log & follow up. 

- Spacing on group chat screens is off
- Admin view of `group info` is inconsistent from group member view (in an unintentional way—one has '...' to show member info, the other is simply tappable)
- ???

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by errorists** [comment]
Thanks for logging it in the system @rachelhamlin 

in the meantime, all of the Group Chat designs [are kept here in Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=227%3A320)

A recap of things that need work: 

---

Profiles, they're both out of date and having a bunch of layout / ux issues of their own.

<img width="435" alt="Group 55" src="https://user-images.githubusercontent.com/4932774/66299768-7a1e9680-e8f4-11e9-8499-1037bc251396.png">

---

System messages

<img width="435" alt="Group 53" src="https://user-images.githubusercontent.com/4932774/66299793-8145a480-e8f4-11e9-9e59-985efc1f9fed.png">

---

Layout issues in the 'New Group chat' flow, needs our components, proper alignment etc.

---

Group chat's overflow menu

<img width="435" alt="Group 56" src="https://user-images.githubusercontent.com/4932774/66300111-092bae80-e8f5-11e9-9f40-1da9a7309fbe.png">

---

Take a look at user right management / admins. 

--- 

👀 will edit as I test it out and find more issues

**Comment by churik** [comment]
@rachelhamlin I believe this one can be closed, as it is resolved in #10099
