### ISSUE TITLE
Desktop app doesn't start on LInux

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#9133]
### Problem

New Desktop app doesn't start on Linux. It exists after 1 second without any errors.

### Example

```
 $ wget https://status-im.ams3.digitaloceanspaces.com/StatusIm-191007-025900-df8749-
 $ chmod +x StatusIm-191007-025900-df8749-nightly-universal.AppImage 
 $ ./StatusIm-191007-025900-df8749-nightly-universal.AppImage 
 $ echo $?
1
```
Nothing happens, it just exits

**Comment by corpetty** [comment]
Confirmed on Arch Linux.

**Comment by churik** [comment]
still relevant

**Comment by churik** [comment]
Is not relevant anymore according to current desktop work (confirmed with @vkjr)
@jakubgs reopen if it is still needed
