### ISSUE TITLE
User is not asked to re-login after changing Fleet settings (and no mailserver selected)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9135]
# Bug Report

## Problem

When changing fleet from Profile there is no mailserver from the mailservers pool of particular fleet is set, thus - no messages are received from offline. 

And in general with all the rest of consequences of when mailserver set to null: e.g. Fetch more message in public chat results in 'An error occured while fetching history' or if I send message to 1-1/group chat - no one from those who offline at this moment will ever receive it.

After re-login everything is fine. In the past we used to force user to re-login to account after fleet has changed. Not sure when that changed (that we do not log user out with respective pop-up saying "You need to re-login for changes to take effect" message) but we need either to return back previous behavior (force re-login) or select mailserver right after fleet option has changed.

#### Expected behavior
User force logout happens after fleet option is changed from Profile

#### Actual behavior
User is not asked to re-login after fleet option is changed from Profile. No mailserver is set after fleet option is changes. Making 'Fetch more message' call results in 'An error occured while fetching history...' with the following error when user tap this status: `Mailserver request error: The following error was returned by the mailserver: failed to decrypt p2p request`

<img width="306" alt="Screenshot 2019-10-07 at 16 51 01" src="https://user-images.githubusercontent.com/8749671/66317692-ad781a00-e922-11e9-83f6-825b8828f680.png">

#### Acceptance Criteria

- When confirming Fleet changing via tap of `Confirm` button - user forced to log out of account and appears on login screen
- Logging to account connects user to selected fleet. `Mailserver settings` is set to 'Automatic selection' and so automatic selection of mailserver is made after login.

### Reproduction

- Open Status and create new account
- Navigate to `Profile` -> `Advanced` -> `Fleet`
- Tap upon `eth.staging` option

### Additional Information
- Status version: Develop `0.14.0 (2019100703)`
- Operating System: Android and iOS

#### Logs

Logcat for what happens when tap fleet -> `Confirm`
```
10-07 17:13:45.911 10708 10708 D ViewRootImpl@65c2fd7[MainActivity]: ViewPostIme pointer 0
10-07 17:13:45.972 10708 10708 D ViewRootImpl@65c2fd7[MainActivity]: ViewPostIme pointer 1
10-07 17:13:45.985 10708 10760 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :fleet.ui/fleet-selected
10-07 17:13:45.994 10708 10708 D Dialog  : mIsSamsungBasicInteraction = false
10-07 17:13:45.994 10708 10708 D Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
10-07 17:13:45.997 10708 10708 I DecorView: createDecorCaptionView >> DecorView@e9eed61[], isFloating: true, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
10-07 17:13:46.006 10708 10708 D ScrollView: initGoToTop
10-07 17:13:46.009 10708 10708 D ScrollView: initGoToTop
10-07 17:13:46.024 10708 10708 D InputTransport: Input channel constructed: fd=91
10-07 17:13:46.024 10708 10708 D ViewRootImpl@ee86736[MainActivity]: setView = DecorView@e9eed61[MainActivity] TM=true MM=false
10-07 17:13:46.026 10708 10708 D ViewRootImpl@ee86736[MainActivity]: dispatchAttachedToWindow
10-07 17:13:46.048 10708 10708 D ViewRootImpl@ee86736[MainActivity]: Relayout returned: old=[0,72][1080,2076] new=[27,790][1053,1357] result=0x7 surface={valid=true 491750215680} changed=true
10-07 17:13:46.053 10708 10732 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
10-07 17:13:46.053 10708 10732 D OpenGLRenderer: eglCreateWindowSurface = 0x727e89e300, 0x727e98d010
10-07 17:13:46.054 10708 10708 D ScrollView:  onsize change changed 
10-07 17:13:46.054 10708 10708 D ScrollView:  onsize change changed 
10-07 17:13:46.061 10708 10708 D ViewRootImpl@ee86736[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
10-07 17:13:46.080 10708 10708 D ViewRootImpl@ee86736[MainActivity]: MSG_RESIZED: frame=Rect(27, 790 - 1053, 1357) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
10-07 17:13:46.101 10708 10708 D ViewRootImpl@65c2fd7[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
10-07 17:13:46.102 10708 10708 D InputMethodManager: prepareNavigationBarInfo() DecorView@7bec532[MainActivity]
10-07 17:13:46.102 10708 10708 D InputMethodManager: getNavigationBarColor() -855310
10-07 17:13:46.940 10708 10708 D ViewRootImpl@ee86736[MainActivity]: ViewPostIme pointer 0
10-07 17:13:47.039 10708 10708 D ViewRootImpl@ee86736[MainActivity]: ViewPostIme pointer 1
10-07 17:13:47.050 10708 10760 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :fleet.ui/save-fleet-confirmed
10-07 17:13:47.063 10708 10732 W libEGL  : EGLNativeWindowType 0x727e98d010 disconnect failed
10-07 17:13:47.063 10708 10732 D OpenGLRenderer: eglDestroySurface = 0x727e89e300, 0x727e98d000
10-07 17:13:47.063 10708 10732 D OpenGLRenderer: endAllActiveAnimators on 0x7237368600 (RippleDrawable) with handle 0x72358232a0
10-07 17:13:47.063 10708 10708 D ViewRootImpl@ee86736[MainActivity]: dispatchDetachedFromWindow
10-07 17:13:47.063 10708 10708 D ViewRootImpl@ee86736[MainActivity]: Surface release. android.view.ViewRootImpl.doDie:7979 android.view.ViewRootImpl.die:7947 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.Dialog.dismissDialog:518 android.app.Dialog.dismiss:501 com.android.internal.app.AlertController$ButtonHandler.handleMessage:188 
10-07 17:13:47.087 10708 10708 D InputTransport: Input channel destroyed: fd=91
10-07 17:13:47.095 10708 10708 D ViewRootImpl@65c2fd7[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
10-07 17:13:47.097 10708 10708 D InputMethodManager: prepareNavigationBarInfo() DecorView@7bec532[MainActivity]
10-07 17:13:47.098 10708 10708 D InputMethodManager: getNavigationBarColor() -855310
10-07 17:13:47.104 10708 10708 E ViewRootImpl: sendUserActionEvent() returned.
10-07 17:13:47.499 10708 10926 D StatusModule: Signal event: {"type":"wallet","event":{"type":"newblock","blockNumber":8695371,"accounts":[]}}
10-07 17:13:47.506 10708 10760 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
10-07 17:13:47.510 10708 10760 D ReactNativeJS: DEBUG [status-im.events:667] - :event-str {"type":"wallet","event":{"type":"newblock","blockNumber":8695371,"accounts":[]}}


```

**Comment by Serhy** [comment]
@rachelhamlin I see it as low-prio issue, taking that 'Fleet settings' is "Advanced mode" of using Status and that there is no issue after re-login.
Good candidate for bounty

**Comment by churik** [comment]
The same issue with bootnodes enabling/saving - on release 0.13.3 there is force logout on these actions.
On current nightly user is not asked to relogin so I suppose that new settings are not applied (but I don't have a way to check it though)

**Comment by cammellos** [comment]
I believe this has been fixed, feel free to reopen.
