### ISSUE TITLE
No Push Notifications when app is closed [Android]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9136]
# Bug Report

## Problem
There are no push notifications appear when message is sent to user in 1-1 chat when Status is closed on Android.
No issues when app on background. 

#### Expected behavior

PN with hashed username appears when messages is sent to user in 1-1 chat when Status is closed 

#### Actual behavior
No PN with hashed username appears when messages is sent to user in 1-1 chat when Status is closed 

#### Acceptance Criteria
On Android, when Status is closed and message is sent in 1-1 chat to this user by the contact who is in the user contact list, - PN appears with the hashed username (because db is closed at this moment)

### Reproduction

- Open Status on two devices and create UserA and UserB
- UserA adds UserB in contacts 
- UserA closes Status app
- UserB sends test message to UserA
- UserA checks whether PN appears

### Additional Information
- Status version: develop  `0.14.0 (2019100703)`

- Operating System: this issue is about Android only (for iOS it's separate issue)

#### Logs

logcat when message is received while Status is closed
```
10-07 17:58:32.997 16528 16626 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :notifications.callback/on-message
10-07 17:58:33.001 16528 16626 W ReactNativeJS: WARN [status-im.notifications.core:109] - failed to lookup contact from hash, not logged in
10-07 17:58:33.005 16528 16626 W ReactNativeJS: WARN [status-im.notifications.core:109] - failed to lookup contact from hash, not logged in
10-07 17:58:33.009 16528 16626 D ReactNativeJS: DEBUG [status-im.notifications.core:226] - handle-on-message app-state: active view-id: nil current-chat-id: nil from: 0x4d6ec88b force: true
10-07 17:58:33.017 16528 16626 D ReactNativeJS: DEBUG [status-im.notifications.background:21] - message-handler-fn called {"ttl":2419200,"sentTime":1570460310119,"messageId":"0:1570460310123549%2bc945a9f9fd7ecd","from":"854811651919","data":{"msg-v2":"{\"from\":\"0x4d6ec88b\",\"to\":\"0x62102113\",\"id\":\"0xcc05a289\"}"}}
10-07 17:58:33.021 16528 16626 D ReactNativeJS: DEBUG [status-im.notifications.background:24] - dispatching :notifications.callback/on-message to display background message {:from "0x4d6ec88b", :to "0x62102113", :id "0xcc05a289"}
```

**Comment by rachelhamlin** [comment]
Just to keep my head on straight: this is the expected behavior on iOS (but not Android), right?

**Comment by Serhy** [comment]
Not expected on iOS as well :) 
On iOS we just had never it's working afair. Respective issue for iOS https://github.com/status-im/status-react/issues/7438

**Comment by rachelhamlin** [comment]
👌🏼 Is this one a regression @Serhy?

**Comment by Serhy** [comment]
@rachelhamlin yes it's a regression, but I could not find nightly build issue appeared (we don't have autotests for PNs as well).
Earliest build I confirmed it's not working is 26th of September nightly develop build.
