### ISSUE TITLE
Impossible to disable "Automatic Selection" in "Mailserver settings"

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9152]
# Bug Report

## Problem

I want to use a custom mailserver, I am able to add a custom mailserver, but not to change the automatic selection to off, so I can't select my custom mailserver.

#### Expected behavior

No bug.

#### Actual behavior

Contains bug.

#### Notes
Perhaps can be fixed together with #8956 

#### Acceptance Criteria

Users should be able to create a custom mail server, unselect the box, and use the selected mailserver.

### Additional Information

Android version downloaded from https://ci.status.im/job/status-react/job/nightly/1280

**Comment by 3esmit** [comment]
If this is just happening to me, might be a bug in my config. I added a mailserver in my lan and then noticed that.

**Comment by 3esmit** [comment]
I reinstalled and the issue is not there. Seems like this is caused when added an mailserver. I will investigate further.

**Comment by churik** [comment]
It is not reproducible on nightly 26/02/2020
