### ISSUE TITLE
Account name remains if you change address to another on "Send transaction"  screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9180]
# Bug Report

## Problem
Account name remains in "Recipient" field when you change field value to scanned or pasted address of another user

#### Expected behavior
no account name is shown

#### Actual behavior
<img width="222" alt="sasdsad" src="https://user-images.githubusercontent.com/4557972/66650624-57acb600-ec31-11e9-8f9c-57a1a127304a.png">

### Reproduction

- Open Status
- Go to Wallet > Send
- Select account in "Recipient" field
- tap on  "Recipient" field and > Enter recipient address > paste valid address > Done

### Additional Information

- Status version: nightly 11/10/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
@rachelhamlin believe we can live with it in `v1 release`
Add a label if you think it should be added in scope.

**Comment by acolytec3** [comment]
@churik @rachelhamlin FYI, was looking for something to work on and this one looked pretty straight-forward (and it was! ).  PR submitted.

**Comment by StatusSceptre** [comment]
@acolytec3 so good. are you still looking for issues? :) let me point you to some I'd like to sneak into v1. I'll tip you on the next...!

**Comment by acolytec3** [comment]
I'm open.  Which one(s) do you have in mind?
