### ISSUE TITLE
Can't add several custom mailservers until relogin

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9181]
# Bug Report

#### Problem
There are two issues in adding and using custom mailserver:
1) when you connect to mailserver, some hash is shown instead of name :
<img width="229" alt="testetss" src="https://user-images.githubusercontent.com/4557972/66656961-49659680-ec3f-11e9-8944-6623c6f73190.png">
2) when you added custom mailserver, look it's detailes, you can't add new one: if you tap on "+", details of previous added mailserver is shown.
Field values are erased after relogin

#### Expected behavior
1) mailserver name is shown 
2) field value are erased

#### Actual behavior
![mailc](https://user-images.githubusercontent.com/4557972/66658550-00631180-ec42-11e9-9723-17434d425989.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Profile > Sync setting > Mailserver
- Tap on +, add new mailserver
- Connect to mailserver and go back (issue 1)
- Tap on added mailserver
- Go back
- Tap on + again (issue 2)

### Additional Information

- Status version: nightly 11/10/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
Still relevant on nightly 26/02/2020

**Comment by cammellos** [comment]
@churik is this still an issue?

**Comment by churik** [comment]
Yes, still the issue in 
> 2) when you added custom mailserver, look it's detailes, you can't add new one: if you tap on "+", details of previous added mailserver is shown. Field values are erased after relogin
