### ISSUE TITLE
Set password keyboard starts uppercase on old android (6.0.1)

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9184]
# Bug Report

## Problem

Using Status v1 on older android 6.0.1 (Marshmallow) starts with uppercase on set password (Multiaccount creation).
Should verify if password keyboard is being used correctly, and ensure that all versions of software use a safe keyboard.

#### Expected behavior

Keyboard starts as a password keyboard.

#### Actual behavior

Keyboard starts as text mode.

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

Install Status in a older device. create a new multiaccount, go set password, password is set wrong because capital letter.

### Additional Information

- Status version: build 1283
 Android 6.0.1

**Comment by flexsurfer** [comment]
same on galaxy s10
