### ISSUE TITLE
Several Keycard issues while trying to recover an account

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9200]
**Hold card to the back of your phone to start screen**

* We never mention that if you are already holding your Keycard to your phone you need to put it away and hold again for the connection to be established `Design work needed`; 
* We ask to maintain "card to phone" connection even though it's not necessary all the time. It's necessary only when we specifically ask for it and show the image `Design work needed` ;
* No indication that the phone is "looking for a card". I suggest some animation + a hint "try moving the card around the phone to find the best spot with the connection " and a timeout "No cards found, try again?" `Design work needed` ;

**Enter your pairing code screen**

* There's no need to hold the card to your phone here, but it's never mentioned. I instinctively continue holding it and it becomes really frustrating to look for the pairing code and enter the code, while my phone is laying on the card on my desk `Design work needed` ;
* I think we should mention how the pairing code looks (9 characters, letters, and digits) `Design work needed`;
* The error says: "Invalid pairing password" event though everywhere else it's called "Pairing code" `Design work needed`;

**Onboarding -> store on Keycard screen**

* When trying to create an account and store it on a keycard, which has already been initiated and has an account on it, I see an error:
  * "**This card has already a multiaccount on it**" – what's a multiaccount? we never mention it in the copy before. If the card only had a "regular account", would it be possible to proceed? `Design work needed`;
  * "**If you wish to change it**" – I guess I wish to change it from a "multiaccount" to a "regular account" if that helps :-) `Design work needed`
  * "**If you want to import keycard multiaccount please use "Add existing multiaccount**" – there's no "Add existing multiaccount" button :-) where should I be looking for it? `Design work needed`
* After "Cancel" is tapped the alert says "Dangerous operation. We highly recommend to finish the setup in order to use the keycard" which is misleading when i tap my old keycard and just wish to cancel the process and sign in. It leaves me with an impression i did something wrong (and maybe lost everything, since it said "Dangerous") `Design work needed`

**Comment by guylouis** [comment]
Hey Andrei, what would you think of splitting this one in two : 
- one about improvbements to NFC tapping user experience 
- one about user story and wording experience 

?

**Comment by andmironov** [comment]
addressed in https://github.com/status-im/status-react/issues/9277
