### ISSUE TITLE
Endless processing spinner after entering wrong PIN when signing message from DApp

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9206]
# Bug Report

## Problem

If you enter wrong PIN instead of validation error endless "Processing" spinner is shown.
Also translation is missing on signing screen.
<img width="242" alt="miss" src="https://user-images.githubusercontent.com/4557972/66762623-a911ab00-eea6-11e9-9585-c255cba28629.png">

#### Expected behavior
validation error, can enter valid PIN

#### Actual behavior
![proc_s](https://user-images.githubusercontent.com/4557972/66762588-94cdae00-eea6-11e9-9e12-d39734effc36.gif)

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

- Open Status
- Login with KeyCard
- Open status-im.github.io/dapp > Transaction > Sign message
- Enter wrong PIN-code > sign in

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 14/11/2019
- Operating System: Android

#### Logs

Full logcat: [logcat.log](https://github.com/status-im/status-react/files/3725121/resend_button.log)

**Comment by guylouis** [comment]
@churik 
hey Chu ! I am curious about what you think of the criticity of this one? if right PIN is entered, then everything is ok and if it's a wrong PIN the app needs to be killed right ?

**Comment by churik** [comment]
Yes, I believe it should be fixed - just to display validation error.
I think that it should be done in v1 scope.

**Comment by rasom** [comment]
My both keycards are dead, that's why can't work on it now.
