### ISSUE TITLE
Input gets previous message if start typing new one [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#921]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In chat user typed first message: "Hi" and sent by tapping on send icon. When user starts typing second message "how are you" then the fist one appears in the input: "Hihow...."
There was a similar behavior in https://github.com/status-im/status-react/issues/890 on 0.9.3 build but it happened only if user send message by hitting Enter. Now tapping on icon is producing similar issue.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When user starts typing second message then no additional text is appended
#### Actual behavior
[comment]: # (Describe what actually happened.)
first message (Hi) is appended to the start of the second message (how are you), so it becomes "Hihow are you"
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Screencast: https://www.screencast.com/t/ju9fCI83P
- Open Status and login
- Open 1-1 chat
- Type "Hi" and send it by tapping on send icon. As a result, "Hi" is shown in message container
- Type "how are you" 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3-25-gf56c421+ (build with `epic/ui-refresh` branch)
* Operating System: Android 7.0
* Device: real Samsung Galaxy 7

### Logs
[20172103232056-logcat.txt](https://github.com/status-im/status-react/files/859809/20172103232056-logcat.txt)

**Comment by rasom** [comment]
sounds similar to https://github.com/status-im/status-react/issues/379

**Comment by annadanchenko** [comment]
duplicate of #379. Issue still happens
