### ISSUE TITLE
MacOS app build lacking "notarization"

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#9212]
# Description

In the process of upgrading to XCode 11.1 in #9172 an issue was discovered with verification of MacOS builds:
```
### Assessing Gatekeeper validation...
StatusIm-191014-095652-6d1653-pr-universal.dmg: rejected
source=Unnotarized Developer ID
```
The specific command that failed was:
https://github.com/status-im/status-react/blob/9ff21348f3827debc252e963f4609ec8347a6641/scripts/sign-macos-pkg.sh#L116

# Symptoms
A `dmg` not properly signed and rejected by `spctl` utility appears on MacOS like this:
![unknown](https://user-images.githubusercontent.com/2212681/66819144-bbd7be80-ef3e-11e9-9845-6d91a7e823e7.png)

# Details
According to Apple this failure is due to lack of something called "notarization":

>Notarization gives users more confidence that the Developer ID-signed software you distribute has been checked by Apple for malicious components. Notarization is not App Review. The Apple notary service is an automated system that scans your software for malicious content, checks for code-signing issues, and returns the results to you quickly. If there are no issues, the notary service generates a ticket for you to staple to your software; the notary service also publishes that ticket online where Gatekeeper can find it.
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by Serhy** [comment]
This seem to be the same (or similar) behavior with previous builds too, when launching MacOS build. 
To "bypass" this I did: 
`Control + click` on installed Status app -> `Open` -> click `Open` button

That worked for too for https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-191015-092131-848866-pr-universal.dmg build (taken from #9172)

**Comment by churik** [comment]
still relevant

**Comment by churik** [comment]
Is not relevant anymore according to current desktop work (confirmed with @vkjr)
@jakubgs reopen if it is still needed
