### ISSUE TITLE
Unpairing card doesn't warn user about consequences and there is no automatic logout after unpairing

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9214]
# Problem

Basically account, created with keycard after unpairing card is useless - so after logout you can't login again on the same device (you can't pair it again before app reinstall)
Also If you tap back right after unpairing, you can see error:
![photo_2019-10-15 14 12 11](https://user-images.githubusercontent.com/4557972/66830506-ec772280-ef55-11e9-856a-6c12b135b94d.jpeg)

[Status.log](https://github.com/status-im/status-react/files/3729130/Status.log)

Now currently this popup is shown before unpairing:
![photo_2019-10-15 14 14 20](https://user-images.githubusercontent.com/4557972/66830591-192b3a00-ef56-11e9-8b6e-a948efbc052c.jpeg)

So to prevent issue with invalid account (I think we don't have option now to remove account from status) I suggest:
- add more details to popup where will be clearly stated what is unpair and that you can't use this account on this device anymore unless you reinstall the app
- automatic logout (with additional confirmation dialog)

@andmironov @hesterbruikman would like to have your opinion on this

**Comment by andmironov** [comment]
Hey! Thanks for the heads up! This means that the process of unpairing should be redesigned. I will be working on it. cc @guylouis @dmitryn

**Comment by andmironov** [comment]
<img width="1649" alt="Screen Shot 2019-10-15 at 16 21 16" src="https://user-images.githubusercontent.com/3115606/66835236-d7a38a80-ef67-11e9-8e69-6ce76be4a90e.png">


Here's a first draft of the flow. You can leave comments in Figma https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=576%3A0

**Comment by guylouis** [comment]
replaced by #9228 
closing this one for clean up
