### ISSUE TITLE
Use eth.staging as a default fleet for development and nightlies

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#9216]
# Feature Issue

After upgrade of geth and Whisper, the algorithm to calculate envelope's PoW in Whisper changed. It means that sending a message from a client before and after the change might calculate PoW totally different and messages won't be exchanged.

In order to fix it, all clients and forwarding Whisper nodes have to use the same Whisper PoW algorithm.

That's why in https://github.com/status-im/status-go/issues/1641 we upgraded `eth.staging` fleet to the newest status-go version. It means that `eth.staging` and the current status-react develop builds use the same Whisper PoW algorithm and messages can be properly exchanged.

### User Story

As a developer, I would like to use a fleet which runs Whisper nodes compatible with the status-react develop builds.

### Acceptance Criteria

- All messages sent between the status-react develop clients have to be received
- status-react develop builds use `eth.staging` as a default fleet

**Comment by adambabik** [comment]
cc @oskarth

**Comment by oskarth** [comment]
Is anyone handling this in @status-im/status-core (also cc @andremedeiros in case you aren't in that team yet)?

**Comment by jakubgs** [comment]
This can be easily changed by using the `FLEET` parameter in Jenkins:
https://ci.status.im/job/status-react/job/manual/build
Or just modifying the default value here:
https://github.com/status-im/status-react/blob/647bde7c6b46faf0eb4bf240457b385255275380/.env.nightly#L6
And other `.env.*` files.

**Comment by jakubgs** [comment]
Although do take into account that the `eth.staging` fleet is much smaller than the `eth.beta` one. Though considering our small usage it should be fine.

**Comment by oskarth** [comment]
It seems like the app might be ignoring this setting and using beta fleet anyway

> I will ask eric, it might be that the client is not switching fleet correctly
that might be an issue on our side, settings might be saved but not applied, since we moved them to status-go
so the client might still be hitting the beta fleet, I am on something else but could take a look at this later, but I'd rather focus on what I am currently finishing off, so if anyone would like to investigate by all means :)

**Comment by cammellos** [comment]
cc @rachelhamlin

**Comment by cammellos** [comment]
closed via #9379
