### ISSUE TITLE
Network fee values fetching takes >1 min

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9217]
# Bug Report

## Problem
Often when signing transactions especially from Dapp in emulators, network fee can take forever to be fetched and calculated which results in 0 as network fee TX value. 
It's not always reproducible (that network fee takes more than 1 min to update) but happens often when e2e tests are running: e.g. https://app.saucelabs.com/tests/02ffaf2d675747efb0733450b8251b04?auth=7d0aecd1dbc9e8dfb11316c079d89064#103 (from 3:29 - 4:29 - network fee 0 and so 'Sing with password' disabled)

#### Expected behavior
Network fee updated in less than 3 seconds after 'Sending TX' bottom-sheet appears

#### Actual behavior
Network fee update value 1 minute after 'Sending TX' bottom-sheet appears

<img width="409" alt="Screenshot 2019-10-15 at 19 25 39" src="https://user-images.githubusercontent.com/8749671/66850514-a46df500-ef81-11e9-91bd-b1545d2c67d7.png">

#### Notes

Not related to any recent PRs, it was happening in the past. 
#### Acceptance Criteria
When `Sending [token]` transaction bottom-sheet appears, Network Fee update it's values in less than 3 seconds

### Reproduction

- Open Status and create new account 
- Navigate to DApps -> enter simpledapp.eth in URL and submit
- Navigate to Assets tab 
- Tap 'Request STT' button and verify transaction fee is not 0 

### Additional Information
- Status version: develop nightly `0.14.0 2019151002`
- Operating System: Android and iOS

**Comment by churik** [comment]
Didn't see this on Status v1.0.2
@Serhy please reopen if still relevant
