### ISSUE TITLE
Re-implement filter for transaction history

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9225]
# Bug Report

## Problem
During redesign filter for transaction history was lost.
I couldn't find it in [wallet design](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=1743%3A303)

#### Expected behavior
Can filter transaction history ("Incoming", "Outgoing", "Pending", "Failed")

#### Actual behavior
No option in new wallet

@errorists or @andmironov can you check it please?

cc @rachelhamlin

**Comment by andmironov** [comment]
Hey! Now history is the third tab on the individual account screen:

<img width="513" alt="Screen Shot 2019-10-16 at 16 52 42" src="https://user-images.githubusercontent.com/3115606/66925662-6cc08500-f035-11e9-91ee-04cce97a3b99.png">

**Comment by errorists** [comment]
@andmironov can I filter the list?

**Comment by andmironov** [comment]
Oh nope, you can't, it has been lost indeed.
