### ISSUE TITLE
Styling + add date seed phrase backed up

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9226]
# Problem
Recently functionality was introduced to remove the notification to back up seed phrase, once the  process to back up seed phrase has been completed. #9105 

The visual style of this implementation leaves the list item as greyed out. This can result in confusing it for a header and being unsure about whether the seed phrase has been backed up. We want to make it more apparent that the seed phrase has been backed up, adding also the date on which the seed phrase was backed up.

## Implementation
![Frame 1](https://user-images.githubusercontent.com/35233054/66930451-e6a43e80-f034-11e9-85d0-967f44a217ed.png)

## Acceptance Criteria
- Follow Figma design: https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=910%3A1
- Use list component if possible
- check mark used is character in Inter font ✓ 

## Notes
Please check if the notification, to back up seed phrase, inside the wallet also disappears. If this is not the case, please create a new issue.

**Comment by cammellos** [comment]
Could we add a well formed user story to the issue (as a user ... )?

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
