### ISSUE TITLE
Add an unpairing keycard  feature

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#9228]
Unpairing a card is an advanced feature for users that might be in the following situation:
- they have used their keycard with 5 phones and want to pair to a new one
- have more than Np cards paired to a phone 

The most simple unpairing feature consist of removing the card and phone pairing slot. 

We can possibly add a feature to remove all pairing slots from a card. This is usefull if the user has lost a phone. 

need design input

**Comment by guylouis** [comment]
see #9214 for design

**Comment by guylouis** [comment]
@bitgamma can you remind me and put down here the maximum number of cards that can be paired to one status app on a given phone ?

**Comment by guylouis** [comment]
design can be impacted by https://github.com/status-im/status-react/issues/9064 decision

**Comment by flexsurfer** [comment]
@guylouis @bitgamma still relevant?

**Comment by bitgamma** [comment]
@flexsurfer somewhat. We talked about it with @guylouis a couple of months ago and decided to leave the issue open for now although the use cases for such functionality are pretty much edge cases

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. Added `recheck` label for easy finding that one in case of need.
