### ISSUE TITLE
Clean keycard and remove multi-account

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#9229]
**Situation** 

Currently, after a keycard has been set-up after onboarding the keycard has 
- setup a PIN, Pairing code, PUK
- secrets loaded (which correspond to status multiaccount seed)

**Problem** 

There is no possibility for the user to remove the secrets loaded physically from the card

A user might want to delete the secrets from his card because
- despite the high level of hardware security of his card, he wants to remove them physically from there to prevent any attack to succeed now or later 
- he wants to change the multiaccount on his card

**Solution** 

A simple approach would be 
- user is logged in his keycard multiaccount
- user goes to 'settings/keycard'
- user choses 'reset keycard' (to be added, does not exist today)
- user is prompted 
"You're about to delete the keys on this card, your pairing code/PUK & PIN remain will unchanged.
You must have your seed if you want to recover any funds from this key in the future. You can now restore another key on this card. Your Pairing code remains unchanged and will be needed if you use a new phone. 
Are you sure you want to proceed ? yes/no"
- if the user clicks 'yes' then 
            - we leaves PIN, PUK, Pairing uncode untouched on the card 
            - the secret on the card is deleted
            - the multiaccount is removed from the phone

**Comment by 3esmit** [comment]
If user forgets Pairing code, PUK and/or PIN, it should be able to reset?

**Comment by guylouis** [comment]
given the low value ($) of the card it self we've not designed it this way ...
the user must remember his PIN (or PUK) to access his card, and he must remember his pairing if he has no phone paired

If we implement https://github.com/status-im/status-react/issues/9064 after v1, the user will be able to recover any keycard if he has his seed (and if PUK/Pairing hasn't been changed form the derived version of the seed by another app...)

**Comment by rasom** [comment]
[Keycard's side of this task is already implemented](https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/hardwallet/settings/views.cljs#L127), so we need to make sure that there is an API for multiacc removal.

**Comment by guylouis** [comment]
Ok
Decided with @Rachel Hamlin <rachel@status.im> that resetting a keycard and
removing its account is post v1.0

**Comment by cammellos** [comment]
@errorists @hesterbruikman could you please have a look at the UI for this?
Thanks

**Comment by guylouis** [comment]
would be great to progress on this 
 @johnlea-quiup 
wdyt about the UX ?

**Comment by hesterbruikman** [comment]
Wondering if this could be captured under 'Delete my profile' for consistency with regular multiaccounts. Result would be more or less this:

![Frame 222](https://user-images.githubusercontent.com/35233054/97640392-e8268600-1a40-11eb-8fa2-5a20bf5b6345.png)
[Figma](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8197%3A858)

**Comment by guylouis** [comment]
fully agree with you @hesterbruikman

**Comment by guylouis** [comment]
So this issue #9229 is flow 6 of this figma design https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=8197%3A858
