### ISSUE TITLE
Overlapping on some screens (onboarding, wallet -  English, Galaxy S7)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9233]
# Bug Report

It is very visible and in happy-path flow, so should be fixed in v1 IMO.
## Problem
On "Send Transaction" screen:
<img width="153" alt="App Live Dashboard 2019-10-17 13-54-43" src="https://user-images.githubusercontent.com/4557972/67008401-ae126c80-f0e9-11e9-9d14-13567c81b7bd.png">

On "Select key storage" (during onboarding):
<img width="144" alt="s7_overlap" src="https://user-images.githubusercontent.com/4557972/67008570-119c9a00-f0ea-11e9-8006-38f8270c2ac9.png">

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 17/10/2019
- Operating System: Android (small screens)
For me reproducible on Samsung Galaxy S7 (5,5'')

**Comment by StatusSceptre** [comment]
@churik can I combine with this issue? https://github.com/status-im/status-react/issues/7990

I'll add more DAI to the bounty if so.

**Comment by StatusSceptre** [comment]
[This is a handy benchmark](https://www.screensizemap.com/?utm_source=departmentofproduct_newsletter&utm_medium=departmentofproduct_newsletter&utm_campaign=departmentofproduct_newsletter) when thinking about the importance of these two issues - the Samsung Galaxy J7 has popularity under 2% compared to other screen sizes. (Data from Statcounter)

**Comment by rasom** [comment]
I can't find any Figma screens for the first case, would it be fine with a multiline text 
<img width=300 src=https://user-images.githubusercontent.com/2364994/67364507-5b690280-f578-11e9-99bd-2e740688b43e.png />

**Comment by churik** [comment]
@rasom that's because the whole flow should be fully redesigned according to https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet - but I believe it is out of scope for `v1 release`.
So seems fine to me for now.

**Comment by rasom** [comment]
@churik ok thanks
