### ISSUE TITLE
[WebView-migration] JS injection prior to document load

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#9260]
# Feature Issue

We are migrating from RN's built-in WebView to [react-native-community/webview](https://github.com/react-native-community/react-native-webview). In scope of this migration, we will maintain our own [fork](https://github.com/status-im/react-native-webview).

This issue deals with the high-priority task that has to be completed first: supporting JS injection into WebView prior to document load.

### User Story

We want to implement JS injection into WebView prior to document load as this is required for web3.js to work properly. This would make it possible to run Dapps within Status's browser.

### Description
For RN's WebView, a corresponding  issue https://github.com/status-im/status-react/issues/553  has been closed by @rasom in https://github.com/status-im/react-native-webview-bridge/commit/85c4266b9109dfb150525535b2bd36a1f2969a34 and https://github.com/status-im/react-native-webview-bridge/commit/381467999a6737617eef6d0b6a26b1eed13edc41.

We need to implement an alternative for community WebView. As of now, a corresponding issue https://github.com/react-native-community/react-native-webview/issues/229 is closed without a proper solution.

### Acceptance Criteria

Verify that web3.js is injected properly.

### Notes

This is part of a larger WebView migration project (RFC for it: https://github.com/status-im/team-core/issues/4)

A PR for this issue should also fix https://github.com/status-im/status-react/issues/8897 (community WebView has migrated away from UIWebView in version 7) and https://github.com/status-im/status-react/issues/9044.

**Comment by cammellos** [comment]
Could we get a well formatted user story for this one (As a user? )? Not sure what the actual feature is, looks a bit more like a chore? (Does have any impact on the user? ). If it's a chore we should probably not estimate it, or if estimated, don't count it as velocity

**Comment by vitvly** [comment]
@cammellos it would enable running Dapps in Status's browser

**Comment by cammellos** [comment]
So, should we add something like:
As a user
I want to be able to run Dapps in Status browser
So I can use my favourite dapps 
?

I thought this was already possible, what would be the difference with the current state of things?

**Comment by vitvly** [comment]
I've included a link to RFC for a project this task is part of: https://github.com/status-im/team-core/issues/4. Sorry, forgot to link it earlier.

**Comment by vitvly** [comment]
We plan to migrate to another WebView library, so this particular feature will have to be re-implemented.

**Comment by cammellos** [comment]
Ok, this looks to me like is a chore (we are swapping out a dependency), as if completed we will have feature parity with current app and no impact to the user (not saying it's no worth it, just figuring this out so we can properly estimate it)

**Comment by vitvly** [comment]
Correct, this is not going to introduce any new end-user functionality.

**Comment by cammellos** [comment]
cool, I will mark this as chore and update the spreadsheet, thanks!

**Comment by vitvly** [comment]
@cammellos thank you!

**Comment by yenda** [comment]
@cammellos it should be measured to verify but one of the original motivation was that it would improve initial load time of webviews

**Comment by vitvly** [comment]
Closed in https://github.com/status-im/status-react/pull/10090
