### ISSUE TITLE
[EPIC] Keycard Sign in 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#9264]
I segmented these into P0, P1, P2. [RH]

P0

* [x] ISSUE #9342
**Error message copy needs to be changed**
* [x] ISSUE #9345
**"More" button behavior is wrong**

* [x] ISSUE #9350
**Change `Cancel` to `<` and remove extra screen if only one key**
* [x] ISSUE #9354 
**Don't ask for the Keycard all the time to sign in**

P1

* [ ] ISSUE #9349
**"Wrong passcode" indicator**
* [ ] ISSUE #9346
**Replace ... characters in address with the horizontal ellipsis special character**
* [ ] ISSUE #9347
**Show the number of passcode wrong attempts**
* [ ] ISSUE #9341
**Active state of pinpad buttons**
* [ ] ISSUE #9353
**Layout fixes and support of small screens**
* [ ] ISSUE #9344
**"Access key" copy, layout and behavior** - fix copy p0, responsiveness & drop down are p1 [RH]

P2

* [ ] ISSUE #9316 (Low priority, WIP)
**Review of card errors depending on their state**
* [ ] ISSUE #9348 
**Frozen keys** - Is this a new feature idea or was it planned? [RH]

**Comment by rachelhamlin** [comment]
@guylouis @churik @andmironov hey FYI,  I segmented these into P0, P1 and P2. Updated one of the issues to include the removal of the "Step 1 of 2" breadcrumbs. 

I'm not sure if we've captured the lack of key on the sign in screen either? 
![image](https://user-images.githubusercontent.com/15470435/68217478-91779f00-ffda-11e9-91e2-9ff987a1baf2.png)

**Comment by guylouis** [comment]
IRL not having  #9354 is a real pain, because it means taping your card and entering your pin fro every interaction you have with status app
It should probably be higher prio

**Comment by guylouis** [comment]
@rachelhamlin

**Comment by churik** [comment]
@rachelhamlin can we mark P0 as `v1 release` here?

**Comment by rachelhamlin** [comment]
Thanks for calling it out guys. I re-added #9354 to v1 must-have scope, but will leave the other UI issues out and categorize them as p1s.

**Comment by churik** [comment]
@rachelhamlin  without fix for https://github.com/status-im/status-react/issues/9344 and https://github.com/status-im/status-react/issues/9345 it is not possible to create another multiaccount if you have only keycard account on phone due to wrong navigation and problems with keycard login screen
From my POV they required for v1.

**Comment by guylouis** [comment]
@rachelhamlin I moved #9354  part of the P0 of the epic too, for consistency. 
As for #9344 and #9345, great point @churik , they are already P0, if we can't have them in v1.0.0, let's have them in v1.0.1 :)

**Comment by churik** [comment]
@guylouis @andmironov FYI: moved to P1 issue #9344 according to https://github.com/status-im/status-react/issues/9344#issuecomment-555581132

**Comment by andmironov** [comment]
Addressed in https://github.com/status-im/status-react/issues/9367 and in other issues where this bug occures
