### ISSUE TITLE
"Multiaccount is currently empty" at attempt to login after navigating to Enter seed phrase and go back

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9268]
# Bug Report

## Problem

Continuation of https://github.com/status-im/status-react/issues/8930#issuecomment-534646028 

#### Expected behavior
Can log in

#### Actual behavior
![photo_2019-10-23 13 11 40](https://user-images.githubusercontent.com/4557972/67387185-abef5880-f596-11e9-8d6c-1e23f335919e.jpeg)

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- install develop (nightly) build 
- create new account (or recover an account - confirmed in both cases)
- once on Chats screen navigate to Profile and Log out off account
- from login page tap Access key button -> tap Enter Seed phrase
- tap "Back"
- try to login

### Additional Information
- Status version: nightly 23/10/2019
- Operating System: Android, iOS

#### Logs

[logcat.log](https://github.com/status-im/status-react/files/3761974/logcat.log)

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
@churik to understand the situation - this was on a simple log-in attempt? 😱

**Comment by churik** [comment]
@rachelhamlin 
yes. login > Access key > Enter Seed phrase > Back > try to login: error
