### ISSUE TITLE
Often 'Could not connect to mailserver' when unstable connection and pinned mailserver

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9269]
# Bug Report

## Problem
When connection is not stable it's not rare case to see 'Could not connect to mailserver'. There are different scenarios but all of them has the same root cause: when trying to connect to the same mailsever in a short period of time (not sure exact value but < 10s for sure) the 'Could not connect to mailserver' appears. See below user scenarios:

**Usecase#1:** 
User has unstable WiFi connection and mobile data enabled. And account has pinned mailsever. 
In that case we have often switch of the network WiFi <-> 3G/4G which ends in attempt to connect to the same mailserver

**Usecase#2:** 
User has pinned mailserver. And at some point connection lost. The 'Could not connect to mailserver' appeared with 'Retry' option. User taps 'Retry' and gets  'Could not connect to mailserver' again. Taps 'Retry' and again ->  'Could not connect to mailserver'. It is happened because same mailserver has attempted to connect.

 

#### Expected behavior
Connecting to the same mailsever in less than 10 seconds establishes connection without  'Could not connect to mailserver'

#### Actual behavior
Connecting to the same mailserver in less than 10 seconds fails with the following 'Could not connect to mailserver' pop-up 

![2019_10_23_16_09_03](https://user-images.githubusercontent.com/8749671/67396321-08ab3d00-f5b0-11e9-96ab-146e6f7b71c1.gif)

### Reproduction is simple

- Open Status and create new account
- Navigate to `Profile` -> `Sync Settings` -> `Mailserver`
- Uncheck `Automatic selection`
- Tap upon mailserver you are connected to now 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: develop `0.14.0 (2019102115)`
- Operating System: Android and iOS

#### Logs

Logcat with error when same mailserver connected: 
[logcat_tap_to_connect_twice.log](https://github.com/status-im/status-react/files/3762612/Log_Tap_to_connect_twice.log)

**Comment by Serhy** [comment]
@rachelhamlin I would like to include it in V1-scope. Fix of this issue should increase UX by not alarming with 'Could not connect to mailserver' for those who use pinned mailservers.

**Comment by andremedeiros** [comment]
@cammellos @Serhy sounds like this one can be closed. Is that right?

**Comment by Serhy** [comment]
Mm, i'd actually be glad if we look at it. 

So the `Reproduction` there in description is just to show how to reproduce the issue. And it still reproducible. 
And so consequences of connecting to same mailserver in less than 10 sec may still be on place.

**Comment by cammellos** [comment]
Yes, I think we should keep this open for now, as we haven't done any work with that regard
