### ISSUE TITLE
Crash if save status with #tag in Edit Profile screen [ui-refresh] 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#928]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Edit profile, in Status field type any tag, tap on empty place to hide keyboard, tap on Save -> App crashed
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App crashed
#### Actual behavior
[comment]: # (Describe what actually happened.)
Status is saved
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Screencast iOS: https://www.screencast.com/t/PoEDoWTEn
Screencast Android: https://www.screencast.com/t/U0B2LrDTsst
- Open Status and login
- Open Profile
- Tap "..." to edit profile
- Tap on Edit
- In Status field type #there 
- on iOS tap on empty space below the field to hide keyboard (on Android: tap on Enter to hide keyaboard)
- Tap on Save button -> crash

### Additional Information

[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4d25
* Operating System: iOS and android

#### Logs
* iOS crash log: [StatusIm-2017-03-22-091730.crash.txt](https://github.com/status-im/status-react/files/860753/StatusIm-2017-03-22-091730.crash.txt)
* Android: 
[20172203-logcat.txt](https://github.com/status-im/status-react/files/860805/20172203-logcat.txt)

**Comment by flexsurfer** [comment]
looks like it crash only if you tap return on ios keyboard before save

**Comment by annadanchenko** [comment]
it's both if tap return and if just tap on empty place without hitting Return

**Comment by flexsurfer** [comment]
@annadanchenko is it work fine on Android?

**Comment by annadanchenko** [comment]
@flexsurfer wow it crashes on Android too. if Hit Return and then tap Save button.

**Comment by annadanchenko** [comment]
@flexsurfer Added the logcat and screencast for Android

**Comment by flexsurfer** [comment]
it's really weird, it reproduced only for "#text\n", not reproduced for "text\n" and "#text \n"
