### ISSUE TITLE
Include Select storage step in onboarding on iOS

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9289]
# Problem
The onboarding flow has recently been updated. Part of the onboarding flow includes a screen `Select key storage` asking the user to select where they want to store their newly generated key.

This screen includes the options to select:

Default

- This device

Advanced

- Keycard

Purpose of this screen is a) functional (select storage location) and b) non-functional (communicate that the keys are stored locally, no servers, no backup).

This screen is currently not shown on iOS, presumably as `This device` is the only option as Keycard hasn't been implemented for iOS yet. Given it's non-functional/communication purpose use we'd like to see it included in Onboarding for iOS with only the default option visible.

![Key storage1](https://user-images.githubusercontent.com/35233054/67584358-b869e180-f74d-11e9-8bb2-066fe05cd4fe.png)

## Notes
Please ping @errorists and/or @hesterbruikman for review

**Comment by hesterbruikman** [comment]
cc @rachelhamlin @rasom

**Comment by rachelhamlin** [comment]
Do you think it's a little strange to offer an option that has only one option? 😅

Perhaps we should include keycard reference, grayed out? This also acts as keycard promotion.

**Comment by errorists** [comment]
I was about to say the same, Rachel beat me to it :) This should be its own iOS specific design that can introduce the concept but doesn't fool users into thinking they're asked to make a choice.

please, hold off with this one until a proper design is specified
