### ISSUE TITLE
Profile for Unknown contact (not added to the contacts) looks empty

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#930]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: It's possible to view stranger's profile by browsing people in Discover. In this case profile of someone who is a friend of our friend but is not known to us looks like this:
* New ver 0.9.4d25
![screenshot_20170322-154622](https://cloud.githubusercontent.com/assets/6584810/24206154/baf30104-0f1d-11e7-83a4-712811479267.png)

* Older ver 0.9.4 
![screenshot_20170322-154611](https://cloud.githubusercontent.com/assets/6584810/24206554/d9643d96-0f1e-11e7-873a-d143684ebac2.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- the public key should be known (in the discover message)
- the name can be generated randomly
- icon should be derived from the public key
#### Actual behavior
[comment]: # (Describe what actually happened.)
see screenshots in summary: all fields are empty. If tap on show QR then QR of the viewer is shown (not QR of the unknown contact)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
You need 3 Contacts:
1. Contact1 who has Contact2 in Contacts
2. Contact3 who has Contact2 in Contacts but does not know about Contact1
3. Contact1 should get some tags, so they are listed in Discover for all Contacts 1,2,3

As Contact3
- Open Status and login
- Open Discover
- Tap on profile picture of Contact1 in Popular tags. Chat with Contact1 will be opened
- Tap on profile picture of Contact1 to open his profile

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4 and 0.9.4d25
* Operating System: Android and iOS

**Comment by annadanchenko** [comment]
@jarradh I've added your comments from Slack to expected behavior. I would also expect that profile of the unknown person shows
* status with tags
* Address
Does not show:
* phone number

Please, correct if it's wrong

**Comment by flexsurfer** [comment]
in a discover item we have `:whisper-id` (public key), we can generate name and photo, but we can't get other user info, like current status or address or phone

**Comment by flexsurfer** [comment]
![image](https://cloud.githubusercontent.com/assets/11790366/24238171/642a24a4-0fba-11e7-9a68-507fddc1e9e4.png)
atm you can chat, but can't /send to such users

**Comment by annadanchenko** [comment]
not relevant anymore
