### ISSUE TITLE
Transaction sent two times instead of one.

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#931]
### User Story

As a user, I want to send funds to other account.

### Description

*Type*: Bug

*Summary*: Created account yesterday, today I found out that we have faucets in console, as I didn't knew what network I was using, I asked to both of faucets.
Then I went to wallet and my balance was 1 ETH, and than sent to Jarrad 0.1 ETH. Confirmed the transaction and than I went back to wallet, and I had 1.79 ETH. I realized that I recieved 1 ETH from both faucets and my transaction was sent duplicated. 
In wallet log it appers only one transaction, but the balance seems to be reduced twice. 

#### Expected behavior
Only one transaction per confirmation

#### Actual behavior
Transaction replayed 

### Reproduction
- Go to console, 
- ask for both faucets, 
- go to your wallet 
- make a transaction to someone
- repeat (until it happens)

### Solution
*Summary*: 
To be defined. 

### Additional Information
* Status version: 0.9.4+ (15/03/2017)
* Operating System: Android

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/224810/24209278/93f11a96-0f04-11e7-8fb6-5f033be06d83.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209296/9ed7eec6-0f04-11e7-9436-8f171895c933.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209317/a95b73a4-0f04-11e7-8019-a7553f4d425f.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209329/b3dad4f0-0f04-11e7-849d-45b378303b28.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209348/c0dbf67a-0f04-11e7-8c36-9e6d6afbe283.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209365/c8b54536-0f04-11e7-9cc4-6463e1a146b7.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209378/d13b3878-0f04-11e7-97c8-1dda0b673fe2.png)
![image](https://cloud.githubusercontent.com/assets/224810/24209404/e58947f2-0f04-11e7-8967-326bbfcd67a8.png)

**Comment by yenda** [comment]
Is this still relevant or outdated ?

**Comment by asemiankevich** [comment]
Outdated
