### ISSUE TITLE
Contacts are not syncing between devices

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#9317]
# Bug Report

## Problem

When testing develop as of 29/10/2019 contacts are not syncing in the following scenario:
- create account on iOS device
- recover account on Android device
- pair both device, sync all
- send 1-1 message to the account from another device
- add contact on Android device
- contact is not synced
- sync all on both devices
- contact is still not synced

**Comment by churik** [comment]
@yenda do you still experience it?
https://github.com/status-im/status-react/issues/9805 also can be related, however in your case you added contact after sync.

If you still see it, please attach logs.

**Comment by churik** [comment]
Issue with syncing is logged in #9805
