### ISSUE TITLE
If Wallet was opened from DApps then it's possible to select only DApps as recipient for SEND ETH  [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#934]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If open Wallet from DApps group then it's possible to send ETH only to DApps (because only they are available for selecting as address). I would expect to be able to select any contact to receive ETH.
![dapps](https://cloud.githubusercontent.com/assets/6584810/24236486/37079596-0fa2-11e7-8274-ba5d5164c31b.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
It should be possible to send ETH only to People, so 
* people contacts should be available for selection
* DApps contacts should be not availbale for selection
#### Actual behavior
[comment]: # (Describe what actually happened.)
Only DApps are available for selection if Wallet was opened from Contacts -> DApps group

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
screencast: https://www.screencast.com/t/4u3GIFlewx
- Open Status and login
- Open Contacts
- Scroll to group DApps and open More 
- Open Wallet from DApps group
- In Wallet type 0.1 and tap SEND
- Scroll the list of contacts that can be selected to send ETH to

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4d25
* Operating System: Android and iOS

**Comment by flexsurfer** [comment]
it seems we have missed this screen, when reworked contacts management, we need to fix it in the ui-refresh
