### ISSUE TITLE
Keycard sign in – "More" button behavior is wrong + breadcrumbs must be dropped

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9345]
_Part of #9264 keycard sign in epic (mark as checked there, when closing this issue)_

1. On the sign in screen, the **"..."** in the top right corner should open a drop-down with one item only "Get a new key"

Image:
<img width="800" alt="get-a-new-key" src="https://user-images.githubusercontent.com/3115606/67676898-8e1e5b00-f9bd-11e9-89e1-6a6d44e1c1a0.png">

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

2. The breadcrumbs that read "Step 1 of 2" should be removed to match the non-Keycard flow.

**Comment by rachelhamlin** [comment]
What does it do currently? Is it there?

**Comment by guylouis** [comment]
the more button is here, but it shows two entries "create a new key" and "add another key" which is confusing. There should be only one entry as defined by Andrei above

**Comment by rasom** [comment]
@andmironov 
> The breadcrumbs that read "Step 1 of 2" should be removed to match the non-Keycard flow.

I don't get what that means 

**upd** forget it, I'm retarded
