### ISSUE TITLE
Keycard sign in – Frozen keys

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9348]
_Part of #9264 keycard sign in epic (mark as checked there, when closing this issue)_

After 3 wrong passcode entry attempts, the key the user is trying to access should become "Frozen" which means that the user can no longer access it just with their passcode. To access a frozen key the user has to use either the pairing and PUK codes or the seed phrase.

When the key is "Frozen" it is still listed in "Your keys" list but is grayed out.
The num pad is disabled. There's a "Key frozen. Help" Error on top of the num pad. "Help" opens a popup with a text which explains the situation. Here's the current version of it, it might change later:

`If you forgot your passcode, you can access your key using your pairing and PUK codes or your seed phrase. If you’ve lost all of those, unfortunately, there’s no other way to access your key again`

Image:

<img width="1271" alt="fr3" src="https://user-images.githubusercontent.com/3115606/67836973-f0479f00-fb28-11e9-907d-ccaf6f2aad84.png">

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

---

**Bonus** (Also mentioned in https://github.com/status-im/status-react/issues/9285)
It would be even cooler and a much better experience for the user if we add a more verbose warning when there's only one attempt left, with "Help" link in it to open a popup explaining what a "Frozen key" is. This could be the next iteration of this issue.

Image:
<img width="425" alt="last-attempt" src="https://user-images.githubusercontent.com/3115606/67837499-26395300-fb2a-11e9-8243-948f942b9930.png">

**Comment by rachelhamlin** [comment]
Was this speced for v1 @guylouis?

**Comment by guylouis** [comment]
" To access a frozen key the user has to use either the pairing and PUK codes or the seed phrase." 

Well actually it's possible that user has two duplicates of the same card, so the frozen state is a qualification of the card and not of the account ....
So: I'd avoid greying out a keycard multiaccount

When a user tries to tap a card with a PIN, he should always be shown the following: 
- if he's entered a wrong PIN, and has at least one more PIN attempt remaining: number of PIN attempts remaining
-if he's entered a PIN but his card is PN blocked: he must be able to enter a PUK, and shown the number of PUK entry remaining if he made a wrong PUK entry attempt 
- if he's out of PIN & PUK entry : that his card is fully blocked. A geek could remove the applet and start everything from scratch but no through status. A regular status user should be let known that his card is bricked and he can't use it anymore at all. 

@andmironov

**Comment by rasom** [comment]
@guylouis @andmironov 
another reason why I wouldn't grey out the account is that a user can enter PUK on another device and "unfroze" the card there. We can't know it before user will try to interact with a card. So forcing them to enter PUK code might be unnecessary.

**Comment by andmironov** [comment]
Wait, but, if I accessed a frozen key on another device it does not mean it should unfreeze on the old one.

What if my device was stolen and the card got frozen because the thief does not know my passcode?

**Comment by guylouis** [comment]
It all comes down to that 'being frozen or unfrozen' is a status for the card and not the account on the phone 

What would make more sense is to never show the account as freezed on any phone, because the phone has no way to know if the card is forzen or not actually

**Comment by andmironov** [comment]
ok, but how do we prevent users from entering the passcode more than 3 times and inform them about it?

**Comment by guylouis** [comment]
With regards to the 3 PIN attempts, it's exactly the same experience as with your banking card and with ATMs, it's the user responsability to remember that he has already made 2 wrong attempts with his card, when he tries for the third time (with the same phone, or another one) and thus take the risk to block it

**Comment by andmironov** [comment]
>  it's exactly the same experience as with your banking card and with ATMs

Sorry, i still don't understand. What is that? In my banking app the card gets blocked :-)

**Comment by guylouis** [comment]
Let's say you go to an ATM and type 2 times a wrong PIN. You will get on this ATM a message saying that you have only one attempt left on your card. Then you leave and try with another ATM, when you type your PIN on this new ATM you don't get a warning message before entering your PIN that you only one have attempt left on your card. It's your responsability to know that you have only one attempt left.

**Comment by rasom** [comment]
@andmironov considering that we won't grey out accounts, are there any changes that should happen in design before proceeding with implementation?

**Comment by andmironov** [comment]
@guylouis ok, but my question is, how do we indicate that the user has no attempts left?

**Comment by andmironov** [comment]
> considering that we won't grey out accounts, are there any changes that should happen in design before proceeding with implementation?

@rasom most likely yes, as soon as I understand :-) currently I don't. We need to prevent users from entering the prong passcode mare than three times, right?

**Comment by guylouis** [comment]
moving this as a P2 in the EPIC, until it's clarified

**Comment by rachelhamlin** [comment]
Hmm, PCI compliance for fintech companies dictates a [minimum of 6 password attempts](https://www.securitymetrics.com/blog/pci-requirement-8-combatting-weak-passwords-and-usernames) before lock-out. 

Even if keycard is more analogous to a debit card, 3 attempts sounds a little restrictive, given that the user has to enter seed phrase or PUK code again to recover.

Perhaps they could be warned about this before they get to their last attempt? In case they are traveling, for example, and can't access their means of recovery.

Additionally, we might consider simply freezing the account for 30 mins - 1 hour before user can try again, as a first measure. @andmironov @guylouis

**Comment by guylouis** [comment]
> Additionally, we might consider simply freezing the account for 30 mins - 1 hour before user > can try again, as a first measure. @andmironov @guylouis

the lock down is done at the card level, and the card has no notion of time, so this not technically possible 

>Perhaps they could be warned about this before they get to their last attempt? In case they are traveling, for example, and can't access their means of recovery.

the number of attempts remaining can not be stored on the phone (simply because a card can be used by several phones), and this number of attempts is an info held by the card. For all interactions with one tap only (most of them are) we thus can't tell to the user in advance how many attempts he has left. It's actually super similar to how you use a debit card with ATM. You are (I have never been :) !) warned by the ATM about how many attempts I have left. However when the user makes a wrong PIN, we wan to warn him and tell him how many he has left. Detailed here https://github.com/status-im/status-react/issues/9347

> Even if keycard is more analogous to a debit card, 3 attempts sounds a little restrictive, given that the user has to enter seed phrase or PUK code again to recover.

The setting to 3 max attempts is hardcoded for now in the applet, and the applet is installed at the factory. We could switch it to 6 in a new applet suite easily. Or make it a parameter of the initialization command. This second approach would be more elegant. I created a github issue https://github.com/status-im/status-keycard/issues/62

**Comment by rachelhamlin** [comment]
Ah, makes sense. Totally appreciate the ATM card analogy. Perhaps it won't be a problem. Curious also to know what @corpetty thinks of 6 attempts over 3, before we change anything on the applet :)
