### ISSUE TITLE
Keycard sign in – "Wrong passcode" indicator

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9349]
_Part of #9264 keycard sign in epic (mark as checked there, when closing this issue)_

The "Wrong passcode" indicator should be displayed for 2.2 seconds and disappear (to be replaced with the number of attempts indicator https://github.com/status-im/status-react/issues/9285), as well as the red background of the dots below it.

When the error appears **the device should vibrate** if possible.

The animation of the message should work as follows:

```
error-pre-shown: { scale: 1, y: -8, opacity: 0 },
error-shown: { scale: 1, y: 0, opacity: 1 },
error-post-shown: { scale: 1, y: 8, opacity: 0 },
```

The transition between those states:

```
duration: 0.4,
ease: [0.77, 0, 0.175, 1],
```
Video:

<img width="375" alt="ыскуут" src="https://user-images.githubusercontent.com/3115606/68083697-c236c780-fe66-11e9-818b-05f9e5815226.gif">

Static image:

<img width="1153" alt="Untitled5" src="https://user-images.githubusercontent.com/3115606/67676507-9d50d900-f9bc-11e9-97e9-b81577a331c1.png">

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

**Comment by rachelhamlin** [comment]
How is it working currently?

**Comment by guylouis** [comment]
It just shows the error message (the copy needs to be changed see #9342 ) and is not removed after a delay, which is confusing to the user

**Comment by churik** [comment]
@guylouis 
I see several issues in current version of the app apart from #9661 in this flow

## When user is logged out
### 1) Reopening screen from state "PUK code is required"  leads to PIN-code screen
 If user after exceeding attempts of passcodes tap back and open account from list -> he will see again 6-digit passcode, not sure it is expected. 
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/4557972/80369827-33dc5500-888f-11ea-8bcb-b90563b6aac0.gif)

### 2) 3 invalid passcode attempts -> valid PUK -> change PIN
In this case, in the workflow you need to set up a new passcode. 
It is implemented, but not clear from user perspective.
How it looks now:
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/4557972/80375195-2d9ea680-8898-11ea-802e-06045ba40bd3.gif)
So after entering valid PUK code field for some 6-digit code is shown without explanation.

### 3) 3 invalid passcode attempts -> invalid PUK code -> keycard is frozen
I believe this case is not handled.
So when user has 0 retries left for entering PUK code, login is freezing with endless spinner.
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/4557972/80375560-cfbe8e80-8898-11ea-89dc-3e215431aa97.gif)

## When user is logged in
### 1) Reopening screen from state "PUK code is required"  leads to PIN-code screen
It is same, so state is not preserved
### 2) 3 invalid passcode attempts -> valid PUK -> change PIN
Known issue #10452 
In this case change PIN-code is shown behind the "Signing in flow"
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/4557972/80477630-921b3d80-894c-11ea-87f6-f25f3901e472.gif)
### 3) 3 invalid passcode attempts -> invalid PUK code -> keycard is frozen
Endless 
After 0 retries left for PUK code -> nothing changed, no info that kecard can't be used anymore
![photo_2020-04-28 12 49 36](https://user-images.githubusercontent.com/4557972/80479312-1ec6fb00-894f-11ea-8e00-e16ef58423cf.jpeg)

**Comment by churik** [comment]
so @hesterbruikman I think we need to define 3 workflows when user is logged in and user is logged out.
#### User is logged in

- [ ] Reopening screen from state "PUK code is required" leads to PIN-code screen
- [ ] 3 invalid passcode attempts -> valid PUK -> change PIN
- [ ] 3 invalid passcode attempts -> invalid PUK code -> keycard is frozen

#### User is logged out

- [ ] Reopening screen from state "PUK code is required" leads to PIN-code screen
- [ ] 3 invalid passcode attempts -> valid PUK -> change PIN
- [ ] 3 invalid passcode attempts -> invalid PUK code -> keycard is frozen

**Comment by churik** [comment]
consider one more possible flow for this case - 3 invalid passcode attempts when User is recovering key from keycard. In this case currently after exceeding attempts app still requesting Passcode

**Comment by guylouis** [comment]
@rasom  I imagine you can close this one
