### ISSUE TITLE
Keycard sign in – Don't ask for the Keycard all the time to sign in

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9354]
_Part of #9264 keycard sign in epic (mark as checked there, when closing this issue)_
_Replacing https://github.com/status-im/status-react/issues/8180 with this new issue_

The user should be able to choose not to be asked for the Keycard to sign in all the time. This should be done using the same way currently "Save password" feature works, for non-keycard keys in Status.

- The should be a checkbox during sign in. I suggest it to be called. `Don’t ask for the card all the time` with a description below `If you don't want to be asked to tap the card each time you open Status`;
- If the user checks that checkbox, we should ask to enable biometric sign in for additional security;
- On iOS "biometric check" might be Face ID or Touch ID depending on the device. On Android afaik it's only possible to use fingerprint;
- This `Don’t ask for the card all the time`  checkbox should be disabled during device-to-card interaction process;
- There should be a way to disable and re-enable biometric sign in in the settings;
- If the `Don’t ask for the card all the time` feature is enabled as well as the biometric sign in, the sign in should happen with a biometric check. If it fails, the user should be offered to sign in using the passcode + Keycard tap;
- If the user unchecks the checkbox, when the biometric has been enabled before, we should show a popup and warn that it will be disabled now;
- The num pad should have an additional key (Face ID or fingerprint icon)
- This should work on small screens as well, see https://github.com/status-im/status-react/issues/9353 for additional specifications;

**Checkbox + Enable biometric**

<img width="1238" alt="rm1" src="https://user-images.githubusercontent.com/3115606/67843114-52f36780-fb36-11e9-8374-83f6db0edcd0.png">

**SIgn in when biometric is enabled**

<img width="1349" alt="rm2" src="https://user-images.githubusercontent.com/3115606/67843123-571f8500-fb36-11e9-8970-d11657435b87.png">

**Disbaling `Don’t ask for the card all the time`**

<img width="809" alt="rm3" src="https://user-images.githubusercontent.com/3115606/67843126-5b4ba280-fb36-11e9-9f76-de2231239712.png">

Figma:
All the flows are described here, see flows number 6 and 7
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

**Comment by guylouis** [comment]
this one is high priority from a user experience stand point, since login with keycard all the time is a irl pain !

**Comment by rasom** [comment]
> On iOS "biometric check" might be Face ID or Touch ID depending on the device.

Don't forget that iOS part is kind of irrelevant for those tasks.

**Comment by andmironov** [comment]
> Don't forget that iOS part is kind of irrelevant for those tasks.

It is for now but should be kept in mind that the copy + icon ("Fingerprint"+ fingerprint icon) might change depending on the device in the future

**Comment by rasom** [comment]
@andmironov @guylouis 
I'm not sure the whole thing as it is formulated at the moment makes sense. Currently we can neither decrypt user's database nor start listening for incoming messages without keycard, so I don't think that it actually makes sense to be able to log into the app without using the keycard. We can store PIN if user doesn't want to enter it, but card will still be needed.

**Comment by guylouis** [comment]
As discussed and agreed in #keycard channel, the encryption key m / 43' / 60' / 1581' / 1' / 0 can be stored on the phone when the user selects the 'don't ask for card all the time ' option

**Comment by rasom** [comment]
@andmironov @guylouis 
We still don't have touch/Face ID login implemented in our app, so for the first version i would prefer to have just a checkbox with label like "Don't ask password on next login", similar to what we have for on-device account, and then on the next iteration add touch/Face ID.

Does it sound good enough?

**Comment by guylouis** [comment]
@rasom seems good to me

**Comment by rasom** [comment]
@andmironov 
Currently it possible to connect card to device at `step 1` screen and then on entering pin you will be logged into account without `step 2` screen shown at all. Can we somehow move that checkbox to `step 1`? Because there's a chance user will never see that option.

**Comment by andmironov** [comment]
@rasom you mean the user will never see it if it’s on? If yes, I believe it’s safe to say this should be handled in settings (turning the biometric sign in off) 

I understand the reason to put the checkbox to ‘step 1’ thought but it’s hard to fit it in there now. 

On the other hand, we will have to do it eventually if we’re going to implement the new card interaction design (https://github.com/status-im/status-react/issues/9365), where there’s no ‘step 2’ at all :-) So please let me try to do it, I need some time.

**Comment by andmironov** [comment]
We might go with this, showing the popup when the checkbox is checked

<img width="773" alt="Screen Shot 2019-11-27 at 14 17 40" src="https://user-images.githubusercontent.com/3115606/69719020-b0240e00-1120-11ea-845d-237b702e3290.png">

cc @rasom

**Comment by rasom** [comment]
@andmironov biometric auth is not mandatory when we save password for a regular acc (and it is kind of hidden in settings, that's why i had no idea about it till yesterday), should we have a parity here with a keycard account?

**Comment by andmironov** [comment]
It's not, but for the regular sign in it should work the same (show a popup asking if the user wants to enable biometric), it just has not been implemented yet (i don't know why and i don't know what's the plan)

<img width="847" alt="Screen Shot 2019-11-27 at 15 47 17" src="https://user-images.githubusercontent.com/3115606/69724649-64c42c80-112d-11ea-9e6d-96065295a32f.png">

Please see all the sign in screens here https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

**Comment by guylouis** [comment]
cc @rachel for last remark about last remark about  signin
