### ISSUE TITLE
Dapp's permission form doesn't fit in the bottom sheet

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9360]
# Bug Report

## Problem

Dapp's permission form doesn't fit in the bottom sheet
![image](https://user-images.githubusercontent.com/11790366/67855868-9be5f480-fb13-11e9-97b9-f43c07b0a3fb.png)

**Comment by rachelhamlin** [comment]
This doesn't block user does it @flexsurfer?

**Comment by flexsurfer** [comment]
yeah it's just a reminder for me to fix, it's just a 10min fix
