### ISSUE TITLE
Onboarding with Keycard – Hold card to the back of your phone screen

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9364]
_Part of #9274 onboarding with Keycard epic (mark as checked there, when closing this issue)_

This screen, as well as any other card-to-phone interaction screen, needs to be revisited, after testing it on several devices.

Here's https://github.com/status-im/status-react/issues/9365 a proposal of how this screen should behave and handle all the possible states.

**Comment by churik** [comment]
Can be closed I believe as a part of https://github.com/status-im/status-react/issues/9365
Reopen if it is important
