### ISSUE TITLE
Keycard -> Device interaction flow

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9365]
**What's the problem?**
The way the flow has been designed does not take into account several edge-cases, which were discovered after testing it. 
- The connection with the Keycard often is pretty had to establish (due to the fact that NFC readers are weak on many devices) and easy to interrupt; 
- Sometimes after a successful connection, it might take up to 15 sec to process the data transfer, which is not supported by the UI and for the user it might feel like it's stuck;
- We never explicitly mention that during onboarding the user does not have to keep the card connected all the time, which makes the experience much worse, the user will instinctively maintain the connection during the whole process;
- The flow is on iOS-ready. On iOS the NFC interactions are handled by a native popup;

**States**

- **Initial state.** Screen indicates that it's ready to accept connections;
- **No NFC.** Screen indicates that NFC if switched off on the device and has to be switched on to continue;
- **No connection for 10 seconds.** The screen indicates that the device is still looking for the card and the user most likely should move the card to find the NFC reader on the device;
- **Connection established.** The screen indicates that the connection has been successfully established and the user should hold the card still not to interrupt it. Replaced by "Processing" after 2 sec;
- **Processing...** Screen indicates that a data transfer is in progress. Sometimes it takes up to ~15sec so it's important to indicate that everything is ok, the user just has to hold the card still and wait;
- **Connection interrupted** An error appears to indicate that the connection has been lost and the user should put the card back where it was and hold it still;

**Video**  
https://dribbble.com/shots/8379578-NFC-card-interaction

Figma: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=5358%3A146
<img width="1627" alt="Screen Shot 2020-02-04 at 14 10 04" src="https://user-images.githubusercontent.com/3115606/73739848-113b1400-4758-11ea-80aa-b0a374773c7b.png">

**Comment by andmironov** [comment]
UPD video of how it works https://dribbble.com/shots/8379578-NFC-card-interaction

**Comment by guylouis** [comment]
@andmironov could you add the dabber (?) video link you mentioned ? thanks
