### ISSUE TITLE
Transaction's amount is shown in exponential notation

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#9389]
# Bug Report

#### Expected behavior

Transaction's amount and fee are shown as regular numbers

[comment]: # (Describe what you expected to happen. Please include designs if possible.)

#### Actual behavior
Transaction's amount is shown in exponential notation.

[comment]: # (Describe what actually happened. Please include screenshots if possible.)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

Try to send 0.00000000000001 ETH and see values amount value in transaction sheet.

<img width=320 src=https://user-images.githubusercontent.com/2364994/68104147-92c5a080-fee2-11e9-975a-9eba21647d7c.jpg />

**Comment by churik** [comment]
still relevant on nightly 26/02/2020 - for transaction sheet and 1-1 chat
