### ISSUE TITLE
Different userpic (or no userpic at all) in public chat 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9400]
# Bug Report

## Problem

In public/group chats received messages are recognised like they were sent from single account:  userpics of previous contacts are 'replaced' by current latest message.  

#### Expected behavior

Userpic corresponds to usermane and displayed next to each message apart the scenario of when two or more messages send by same user in public/group chats

#### Actual behavior

Userpic of latest contact is shown only in public/group chats from last user 
<img width="570" alt="Screenshot 2019-11-05 at 17 26 26" src="https://user-images.githubusercontent.com/8749671/68221126-a0b61700-fff1-11e9-8c0f-69dc3c489310.png">
Video: https://drive.google.com/file/d/1iK8J6FUYKjkew4YuhrMlC1Ih1bjzgIF6/view?usp=sharing

#### Notes
Reproduced in https://github.com/status-im/status-react/pull/9392 build too

### Reproduction

- Open Status on two devices and create UserA and UserB
- Join same public chat (e.g. `#userpics`)
- UserA sends text message
- UserB sends text message
- UserA sends text message
- UserB sends text message
- Pay attention on userpic
- If UserC will send message in same public chat for UserB and UserA all latest messaged will be shown they like sent by UserC

### Additional Information

- Status version: develop `0.14.0 (2019110511)`
- Operating System: Android and iOS

**Comment by cammellos** [comment]
I'll take this one, my doing likely
