### ISSUE TITLE
Long sum is overlapping other ui elements in 1-1 chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#941]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Long sum 0.12345678912345678 ETH is sent.
In 1-1 chat there is only 0.123456789 shown and ETH is hidden behind right edge
![chat and long sum](https://cloud.githubusercontent.com/assets/6584810/24300056/71cbc058-10ab-11e7-9c39-2d0b11a65039.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The complete sum and currency are visible and do not overlap other ui elements 
#### Actual behavior
[comment]: # (Describe what actually happened.)
1. In Transactions sum overlaps Address and Date
2. In 1-1 chat there is only 0.123456789 shown instead of 0.12345678912345678 and ETH is hidden behind right edge

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- In 1-1 chat send someone 0.12345678912345678 ETH
- Open Wallet to see Transactions
- Open 1-1 chat to see the sent sum and currency

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4
* Operating System: Android (Samsung Galaxy S6) and iOS

**Comment by yenda** [comment]
The wallet part is outdated with the new wallet but this issue is still relevant for the chat

**Comment by annadanchenko** [comment]
will keep #3512 as open
