### ISSUE TITLE
UI hangs right after sign in for 1-2s on slow Android devices

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9425]
# Bug Report

## Problem

UI hangs right after sign in for 1-2s on slow Android devices
And it's not responsive, user actions ignoring 

#### Expected behavior

UI works smoothly right after sign in its possible to click buttons

#### Notes

These two events might be the reason

![image](https://user-images.githubusercontent.com/11790366/68576755-f3b72080-046e-11ea-93cc-aa11391159cd.png)

signal is `"{\"type\":\"node.login\",\"event\":{}}"`

**Comment by flexsurfer** [comment]
cc @rachelhamlin

**Comment by flexsurfer** [comment]
as a solution we could use js object like here https://github.com/status-im/status-react/pull/9305

**Comment by cammellos** [comment]
also we could try first to use `clj-bean` to see if it improves things, while keep the ease of use

**Comment by flexsurfer** [comment]
for config we use transit, so we need to change it first

**Comment by flexsurfer** [comment]
there are two different things why UI hangs
1) we have huge fx for tokens validation in nightlies
2) because of react-navigation we initialize all views and subscriptions after sign in 

in this task, we'll address the only first one

**Comment by flexsurfer** [comment]
for 2 we could show loading indicator until UI will be ready

**Comment by cammellos** [comment]
@flexsurfer are you actively looking into this or should I take a look? (I have noticed you moved it in "To do")

**Comment by flexsurfer** [comment]
@cammellos I've made a research and found two reasons, 1 was only in nightly and 2 not so critical and could be done later, but if you want you can look at it, i don't work on in it anymore

**Comment by flexsurfer** [comment]
2. because of react-navigation we initialize all views and subscriptions after sign in

i think the solution could just keep loading indicator until UI is initializing, so it's not a performance optimization but just make UX better

**Comment by churik** [comment]
@flexsurfer do you still see this issue?
