### ISSUE TITLE
Message counter reappears after relogin in chats 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9429]
# Bug Report

## Problem
After message received and read - message counter disappears as expected. However, after re-login to account, each message counts as "unread" and so unread message counter reappears each relogin in any type of chats.

#### Expected behavior
All read messages keep the 'read' status and no 'Unread' message counter in chat after contact relogin.

#### Actual behavior
<img width="754" alt="Screenshot 2019-11-11 at 15 43 44" src="https://user-images.githubusercontent.com/8749671/68591735-114daf80-049a-11ea-864d-b5b0e536aa65.png">

### Reproduction

- Create two new users: UserA and UserB
- UserA adds UserB and vice versa
- Both users join the same public chat
- UserA sends text message in 1-1 chat with UserB
- UserA sends text message in public chat
- UserB navigates to both chats to read messages
- UserB reopens Status and logins to account

### Additional Information
- Status version: develop `0.14.0 (2019111102)`
- Operating System: Android and iOS

**Comment by cammellos** [comment]
Close via https://github.com/status-im/status-react/commit/13b01ce8795c8890cc5b733bef21dba65435ca41
