### ISSUE TITLE
Received messages disappeared in chats after re-login

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9430]
# Bug Report

## Problem
Received messages in public/1-1/group chats disappear from respective chat view after re-login to account.
If I received message while I was online - those messages are kept upon next login BUT issue # https://github.com/status-im/status-react/issues/9429 takes place. And it needs 2-3 relogin attempts so those received messages are gone
But in a case of public chat like `#status` or `#status-core` it's enough to join chat, read messages (or not even read them so unread message counters are in place), - and upon next login there are no messages in chats.
Those messages user SENT - always present, but not those user received.
 
**NOTE**: the last message always kept displayed on main `Chats` view per chat if it was received by user NOT from offline inbox but while user was online 

#### Expected behavior
All messages received in chat kept in chats view after relogin

#### Actual behavior
Receive messages in 1-1/public/group chat -> reopen Status and login -> no messages are present in chat view

![4334554545](https://user-images.githubusercontent.com/8749671/68596987-da30cb80-04a4-11ea-9954-064b407bb268.gif)

### Reproduction

- Open Status and create new account
- Join `#status` and/or `#status` public chat 
- Read messages received from offline inbox
- Re-login to account
- Open chats again and verify messages are present

### Additional Information
- Status version: develop 0.14.0 (2019111102)
- Operating System: Android and iOS

**Comment by churik** [comment]
cc @rachelhamlin
