### ISSUE TITLE
it must not be possible to create two accounts (one with keycard, one without keycard) with the same seed

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#9435]
**Description** 
It is currently possible to create two accounts that have the same mnemonic (hence the same seed) one with keycard, one without keycard. 

**Problem**
This is a security problem and totally defeats the purpose of keycard. The problem is that it gives a false sense of security to the user
- that uses keycard to keep his private keys offline, in a cold storage
- while they are still stored on the phone 

**Reproduction** 
-  create a keycard account: generate a key > select storage: keycard. At this stage write down the mnemonic.
- create a non-keycard account with the same seed: access key > enter seed phrase 

reproduced in #9062 

**Solution**
whenever a new status account (keycard or non-keycard) is created we must make sure that there is no existing account with the same seed on the phone (keycard or non-keycard)

cc @rachelhamlin @corpetty @rasom

**Comment by rasom** [comment]
@guylouis 
We have two ways to restore account at the moment:
1. by entering mnemonic
2. by pairing a keycard with existing acc on it
 
The problem with the second case is that we have to pair a card with a device before we can get master key address and check that this multiaccount already exists. We disabled the option to unpair card https://github.com/status-im/status-react/issues/9227 , and so the question is: do we want to propose user to unpair card in this case, or we just show them that account can't be restored and keep one extra slot occupied?

**Comment by guylouis** [comment]
for reference, this was discussed in the channel, and there is indeed a possibility to check some hash of the master key on the keycard by tapping the keycard, prior to any card-phone pairing. So by comparing this hash with the hash of the multiaccount on the phone, we can check if they are similar or not.
