### ISSUE TITLE
Not possible to pair new account with keycard having pre-generated PUK/Passcode

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9451]
# Bug Report

## Problem
Applet in the new keycards is not initialised. Means there is no PIN/PUK/Passcode generated yet.
However in a case keycard has PUK code and Passcode generated but not paired to any account there is a weird flow happens while creating new account with keycard as key storage: after confirming 'Seed' phrase user redirected right to 'Confirm passcode'. And entering any passcode but PIN ends up on infinite spinner. Status app re-install and starting from scratch doesn't help. 
Besides misleading screen user unlikely guess to enter PIN code as only valid value on the sudden 'Confirm passcode' screen

Keycard  can be initialised and not paired to account:
- when user stops keycard pairing during new account creation at 'Write codes down and store them securely' screen tapping 'Cancel' on this screen or closing the Status app
- in the future with 'reset keycard' feature (https://github.com/status-im/status-react/issues/9229)
- through `keycard-cli` client (`./keycard-cli init`)

#### Expected behavior
TBD

#### Actual behavior
Confirm passcode screen appears right after confirming seed phrase while creating new account with keycard key storage. Any value entered on this screen ends with infinite spinner. 

<img width="517" alt="Screenshot 2019-11-15 at 16 23 03" src="https://user-images.githubusercontent.com/8749671/68950327-97ccfe80-07c4-11ea-8ee8-6324abfaa496.png">

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Precondition
Easiest way to made keycard with secret codes generated but not paired to any account is through keycard-cli
- ./keycard-cli delete -l debug
- ./keycard-cli install -l debug -a [path_to_keycard_v3.0.cap]
- ./keycard-cli init -l debug`

### Reproduction

- Open Status
- Tap `Get started` ->  `Generate a key` -> `Next` -> select `Keycard` as a key storage and tap `Next`
- Tap `Begin setup`
- Hold the card to the back of device
**Actual result:** You will be redirected to `Enter your pairing code` screen. 
- Enter valid pairing code and tap `Pair to this device`
**Actual result:** You appear on Backup "Seed" phrase screen. Remember this phrase. Tap `Confirm` -> `Yes`
- Enter the first confirmation seed pharse word  and tap `Next`
- Enter the second confirmation seed pharse word  and tap `Next`
**Actual result:** You appear on 'Confirm the passcode' screen. 
- (optional) Enter any value but PIN code.
**Actual result:** Endless spinner and user keep staying on the same screen.

 
### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: develop `0.14.0 (2019111502)`
- Operating System: Android

#### Logs

Logcat after entering passcode when app hung up:
```
11-15 16:45:11.306  3146  3146 D ViewRootImpl@e653eab[MainActivity]: ViewPostIme pointer 0
11-15 16:45:11.374  3146  3146 D ViewRootImpl@e653eab[MainActivity]: ViewPostIme pointer 1
11-15 16:45:11.394  3146  3201 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
11-15 16:45:11.406  3146  3201 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet/process-pin-input
11-15 16:45:11.411  3146  3202 D CardChannel: COMMAND CLA: 00 INS: A4 P1: 04 P2: 00 LC: 09
11-15 16:45:11.451  3146  3202 D CardChannel: RESPONSE LEN: 63, SW: 9000 
11-15 16:45:11.451  3146  3202 D CardChannel: -----------------------
11-15 16:45:11.492  3146  3202 D CardChannel: COMMAND CLA: 80 INS: 10 P1: 00 P2: 00 LC: 41
11-15 16:45:11.705  3146  3202 D CardChannel: RESPONSE LEN: 30, SW: 9000 
11-15 16:45:11.705  3146  3202 D CardChannel: -----------------------
11-15 16:45:11.734  3146  3202 D CardChannel: COMMAND CLA: 80 INS: 11 P1: 00 P2: 00 LC: 40
11-15 16:45:11.956  3146  3202 D CardChannel: RESPONSE LEN: 40, SW: 9000 
11-15 16:45:11.956  3146  3202 D CardChannel: -----------------------
11-15 16:45:11.964  3146  3202 I SmartCard: secure channel opened
11-15 16:45:11.969  3146  3202 D CardChannel: COMMAND CLA: 80 INS: 20 P1: 00 P2: 00 LC: 20
11-15 16:45:12.182  3146  3202 D CardChannel: RESPONSE LEN: 20, SW: 9000 
11-15 16:45:12.182  3146  3202 D CardChannel: -----------------------
11-15 16:45:12.190  3146  3202 D StatusKeycard: Unexpected error SW, 0x63C2
11-15 16:45:12.205  3146  3202 I zygote  : Deoptimizing void com.facebook.react.uimanager.ReactShadowNodeImpl.<init>() due to JIT inline cache
11-15 16:45:12.223  3146  3201 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/on-verify-pin-error
11-15 16:45:12.233  3146  3201 D ReactNativeJS: DEBUG [status-im.hardwallet.core:1118] - [hardwallet] verify pin error {:code "EUNSPECIFIED", :error "Unexpected error SW, 0x63C2"}
```

**Comment by Serhy** [comment]
@guylouis please, need your input here for expected behavior

I suggest in that case we follow the same flow when keycard has not been initialised. So
`Begin setup` -> Hold the card to the phone

The next is: 
`Enter passcode` -> `Confirm passcode` (not  `Enter your pairing code` screen) appears. 

After confirming passcode we redirected to `Enter your pairing code` screen followed by `Backup "Seed" phrase` which ends up in `Finishing up...` -> `Welcome to Status!`

**Comment by guylouis** [comment]
@Serhy thanks for finding this bug!

I fully agree with your suggestion of desired behaviour

In terms of priority regarding v1 release, since in v1 we will not have 'reset keycard' feature #9229, this case will happen only very rarely, as you said only "when user stops keycard pairing during new account creation at 'Write codes down and store them securely' screen tapping 'Cancel' on this screen or closing the Status app", I'd suggest we keep it in the post v1 priorities. Let me know if you disagree. 

cc @rachelhamlin

**Comment by Serhy** [comment]
Yes, agree it's not a V1 priority issue.

**Comment by Ferossgp** [comment]
@Serhy @guylouis I can make this flow working like that:
`Begin` > `Pairing Code` (Which user should have cause he was warned to store code) > `Pin Code` > `seed phrase` > Success. This is the only flow we can have now cause the card can't be reset.

**Comment by Ferossgp** [comment]
Partially fixed in #10015 it works the right way by replacing the PIN screen without header 1 of 3 and handling pin correctly. Needs to be checked for all edge cases.

**Comment by rasom** [comment]
can't reproduce this issue

**Comment by bitgamma** [comment]
@Serhy this should be fixed now

**Comment by Serhy** [comment]
Can not reproduce anymore with reproduction, closing the issue
