### ISSUE TITLE
Improve bandwidth usage

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#9465]
As a user 
I want the status-app to consume less bandwidth
So I can use the app without burning through my data plan

### Problem
Currently the status-app uses a large amount of bandwidth https://github.com/status-im/status-react/issues/9081 . This is likely due to how whisper works https://discuss.status.im/t/fixing-whisper-for-great-profit/1419 .

A potential solution has already been identified  in the discuss post above, where a new type of nodes (waku-nodes), should be implemented which will drop the usage of bloom filters and instead use topics directly.

In the scope of this task there should be an option for the app to optionally use this waku nodes, while preserving the current functionalities of the app (real time messaging + offline messaging).

Bandwidth measurements should also be performed to quantify the improvements over whisper, ideally through automated testing.

### Acceptance criteria

* Waku nodes can be optionally used in the app
* Current app functionalities are maintained while waku-nodes are used
* The usage of waku nodes should result in a tangible improvement in bandwidth.

### Result

Waku shows significant improvement in bandwidth:

https://notes.status.im/waku-benchmark?edit

**Comment by oskarth** [comment]
@PombeirP do you have a link to the status-nim integration issue that is blocking this on the Nim side? `waku/0` (including bridging) is already merged in nim-eth.

**Comment by pedropombeiro** [comment]
https://github.com/status-im/nimbus/issues/406

**Comment by oskarth** [comment]
I don't believe all (perhaps even most?) of those issues are a blocker for  getting experimental Waku support in the app and testing that it works end to end, with bridging etc.

**Comment by pedropombeiro** [comment]
Yeah, the most important right now are in the `Regarding wrapper/API implementation` section, as well as successfully integrating `libnimbus.a` into `libgojni.so` (which I'm currently working on).

**Comment by cammellos** [comment]
This has been verified and it's merged in develop.
