### ISSUE TITLE
Connect to the closest waku-node

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#9467]
As a user
I want to connected to the closet waku node
So that I can retrieve messages faster

### Problem

Waku nodes will be located in different geographical reason, likely there will be a tangible performance difference by connecting to the closest node available.

A client should connect to the closest node available by ping time, and should prefer connecting to that node if available.

### Acceptance criteria

* Upon connecting/reconnecting to a node, a client should always prefer the fastest node (measured in ping time) if available.
* Any re-connection mechanism should be using this option if implemented  ( https://github.com/status-im/status-react/issues/9466 )

Depends on https://github.com/status-im/status-react/issues/9465

**Comment by oskarth** [comment]
@cammellos do you think response time is related enough to bandwidth usage that it should be part of the same piece of work? or do you think this will directly impact bandwidth due to things like connection drops etc?

Another option might be to tackle this independently.

**Comment by cammellos** [comment]
@oskarth historically we have had issues with connection drops, as if you get disconnected from a mailserver/waku node while you are syncing messages, you have to start from scratch, leading to fetching the same messages multiple times.

This is technically correct, as mailserver don't have a synchronization protocol and therefore they are not consistent which each others, so attempting to use the same cursor across them is not something we want to use, it does work now, but there's no guarantee that it will in the future (think of a stateful cursor a la elasticsearch).

This is not necessarily  something we should lump in the same category as "bandwidth improvements" (no opinion on the matter), but I think it's something we should be doing in any case.

**Comment by cammellos** [comment]
This has been implemented as the method used for normal whisper nodes works just the same for waku.
