### ISSUE TITLE
Update chat message appearance

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9469]
The purpose of this task is to align any chat message styling with the intended design, some of the values outlines in the story may already be correct and present in code, nevertheless I ask to double check that's the case. The purpose here is to make sure the chat message UI is bug free and a joy to look at while providing a solid foundation to build chat based features like message extensions, images etc.

### User Story

As a user, I want to the chat message appearance to be consistent, easily scannable and aesthetically appealing so that I can enjoy using chat more. 

### Description

**1. Update the rounded corners on all messages,** 

incoming messages, top left: `16`, top right: `16`, bottom right: `16`, bottom left: `4`

<img width="141" alt="Group 19" src="https://user-images.githubusercontent.com/4932774/69034954-b8729f80-09e2-11ea-9fd3-a807490a6966.png">

outgoing messages, top left: `16`, top right: `16`, bottom right: `4`, bottom left: `4`

<img width="141" alt="Group 20" src="https://user-images.githubusercontent.com/4932774/69034987-cfb18d00-09e2-11ea-98b9-767098883e01.png">

**2. Make sure inner paddings match design**

Horizontal: `12` , Vertical: `6`

<img width="118" alt="Group 21" src="https://user-images.githubusercontent.com/4932774/69035198-5f573b80-09e3-11ea-8881-0f375ef59fb3.png">

**3. Make sure the minimum space in a line between a timestamp is 12**

<img width="121" alt="Group 22" src="https://user-images.githubusercontent.com/4932774/69035316-aba27b80-09e3-11ea-921b-a7815b251352.png">

**4. Make sure the text is styled correctly**

<img width="351" alt="Group 23" src="https://user-images.githubusercontent.com/4932774/69035372-ca087700-09e3-11ea-94fa-d4e0f1372aca.png">

**5. Make sure that avatars and usernames are wrapped inside touchable and styled correctly**

<img width="362" alt="Group 39" src="https://user-images.githubusercontent.com/4932774/69747889-79adb980-1147-11ea-83e1-63f23d5fd44c.png">

**6. Make sure that the date headers and status indicators match the spec**

<img width="549" alt="Group 27" src="https://user-images.githubusercontent.com/4932774/69035758-a85bbf80-09e4-11ea-9fb4-2a55df2aa182.png">

<img width="257" alt="Group 28" src="https://user-images.githubusercontent.com/4932774/69035787-bc9fbc80-09e4-11ea-8211-68bbeb482de2.png">

**7. Update the appearance of Emoji only messages**

<img width="284" alt="Group 30" src="https://user-images.githubusercontent.com/4932774/72150541-00d88900-33a6-11ea-8a85-9d52a54d178c.png">

**8. Update the appearance of Sticker messages**

<img width="274" alt="Group 31" src="https://user-images.githubusercontent.com/4932774/69036230-b8c06a00-09e5-11ea-8a5f-9f1944a3f588.png">

**9. Make sure messages grow horizontally to fill the available space correctly**

without avatar, the larger margin should be `96`
with avatar, it's `52`

<img width="383" alt="Group 29" src="https://user-images.githubusercontent.com/4932774/69036465-3b492980-09e6-11ea-8b99-572e9dbcf56a.png">

**10. Update the appearance of long messages**

<img width="550" alt="Group 35" src="https://user-images.githubusercontent.com/4932774/69037667-8f550d80-09e8-11ea-865b-fc50ffd3e9ed.png">

**11. Make sure the layout of direct replies matches the spec**

<img width="513" alt="Group 36" src="https://user-images.githubusercontent.com/4932774/69705721-63c3d880-10f6-11ea-94f0-83a9979b55ee.png">

### Acceptance Criteria

All of the above were either updated or already compliant with the design spec.

### Notes

[Figma designs](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=5380%3A26979)

message me on discord with any questions, thank you! 🤗

**Comment by churik** [comment]
@errorists most of the issues are addressed I guess, should we close this one?

**Comment by errorists** [comment]
@churik right most but not all, it's still awaiting @Ferossgp to follow up on points 10 and 8 🙏 we agreed to leave it open until then
