### ISSUE TITLE
Ignore Dark Mode setting on iOS13

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9470]
# Problem

At present, whenever dark mode is enabled on iOS, it only introduces a bunch of bugs without any advantages. 

- Status bars are presented white making them invisible against our white backgrounds, 

- photo picker dialogues are presented with incorrect styling all over, making them difficult to use
- dark keyboards are an unwelcome sight without a Dark Mode of our own.

## Implementation

To quote the maestro @flexsurfer 

> it seems like simple one to ignore dark mode
add this to your Info.plist file:
    <key>UIUserInterfaceStyle</key>
    <string>Light</string>

## Acceptance Criteria

There are no visible changes to our UI when dark mode is enabled.

thank you kindly! 🙏

**Comment by rasom** [comment]
All mentioned issues except Status Bar are fixed in #9564. 
Status Bar should be fixed with RN upgrade https://github.com/facebook/react-native/issues/26619#issuecomment-541143915
