### ISSUE TITLE
Fix ENS setting glitches + disallow setting before Tx confirmed

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9473]
# Bug Report

## Problem

As I was reclaiming my ENS name `rachel.stateofus.eth` on the 18/11/19 nightly, I ran into a couple of small snags:

1. The '->' button to trigger the transaction is very, very slow to respond. I tapped on it many times before the bottom sheet finally appeared.

2. When the bottom sheet did appear, it loaded with this `Invalid number` error.

![IMG_5953](https://user-images.githubusercontent.com/15470435/69047955-41de9d80-09f4-11ea-9d6d-8bc9e93aaeef.PNG)

3. After I signed and saw the confirmation screen, the contract interaction bottom sheet remained open and the `Invalid number` appeared again. I also had to tap the `Cancel` button multiple times to make it go away.

![IMG_5956](https://user-images.githubusercontent.com/15470435/69047962-460abb00-09f4-11ea-8e5d-00db8dd4ff19.PNG)

4. ([separate issue](https://github.com/status-im/status-react/issues/8837)) The system `Save password` option came up while I was trying to close the bottom sheet again. 

#### Expected behavior

- Do not allow user to "Show my ENS username in chats" unless the setting Tx is mined. It should be grayed out if the Tx is not yet confirmed.
- Buttons respond on first tap.
- No 'invalid number' error.
- Bottom sheet disappears once Tx has been signed. This should be fixed by preventing user from tapping button and triggering multiple Txs.

#### Acceptance Criteria

See above.

### Reproduction

- In ENS flow, enter a name you already own and follow instructions.

### Additional Information

- Status version: Nightly
- Operating System: iOS 13.1.3

**Comment by churik** [comment]
@rachelhamlin 

2) "Invalid number" in Gas Price is known issue in all wallet flows, should we log it separately @flexsurfer ?


3) You saw several transaction sign screens because you tapped a lot of times.
Is there any way to prevent multi tapping @flexsurfer ?

**Comment by flexsurfer** [comment]
@churik  what do you mean by issue for 2 ?  we have an issue to show this error with more user friendly message

for 3 yes, we must prevent this

**Comment by churik** [comment]
> @churik what do you mean by issue for 2 ? we have an issue to show this error with more user friendly message

Ah. OK, just didn't find it from the 1 attempt. Thanks!

**Comment by flexsurfer** [comment]
fixed all points except Do not allow user to "Show my ENS username in chats" unless the setting Tx is mined. It should be grayed out if the Tx is not yet confirmed., @churik  lets create separate issue, thanks
