### ISSUE TITLE
Stickers in "Recent" are not aligned to the right if they are from different stickerpacks

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9482]
# Bug Report

## Problem

![photo_2019-11-19 10 45 51](https://user-images.githubusercontent.com/4557972/69135660-c47d6080-0ab9-11ea-9e80-eaa87b851934.jpeg)

#### Expected behavior
stickers are aligned to the right

#### Actual behavior
stickers are not aligned

### Reproduction

- Open Status
- Join any public chat
- Install free stickerpack and buy another one
- Send one sticker from each stickerpack
- Open Stickers > "Recent" 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 19/11/2019
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
Oops

**Comment by churik** [comment]
still relevant on nightly 26/02/2020

**Comment by churik** [comment]
still relevant on nightly 26/07/2022

**Comment by flexsurfer** [comment]
will be fixed in new design
