### ISSUE TITLE
Reintroduce back collapsing of long messages in chats

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9484]
# Bug Report

## Problem

After moving message parsing to status-go (in https://github.com/status-im/status-react/pull/9409) we lost (as known issue) collapsing messages when message content has more than 20 lines. 

#### Expected behavior
Messages with more than X (variable) lines are collapsed in message bubble 

#### Actual behavior
Messages with more than X (variable) lines are collapsed in message bubble 

![123123](https://user-images.githubusercontent.com/8749671/69140816-fb5c7200-0acb-11ea-82db-79864ba00345.gif)

### Reproduction

- Open Status and create new account
- Join any chat (e.g. public chat `#test777`)
- Send message containing 200 lines

### Additional Information
- Status version: develop `0.14.0 (2019181102)`
- Operating System: Android and iOS

**Comment by Serhy** [comment]
There is a https://github.com/status-im/status-react/issues/9469 task dedicated to styling of long messages but this issue is for reintroducing line-limit back.

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by StatusSceptre** [comment]
Potentially fix together with #9485?

**Comment by churik** [comment]
@rachelhamlin 
IMO they are not the same. 
The decision was (fix me if I'm wrong):
1) limit sending messages to 2000 chars (can prevent https://github.com/status-im/status-react/issues/9485 )
2) reintroduce back collapsing of long messages (it was before 20 rows)

**Comment by rachelhamlin** [comment]
Is 2000 characters less than 20 rows? I guess it depends on how many characters it takes before we need to collapse messages. :)

**Comment by churik** [comment]
Collapsing is more about showing the content I believe, sending is about the limitation of symbols for the sender to prevent long messages to appear, and there are several possible ways to do it - i.e. showing validation message at attempt to typing \ pasting > 2000 chars or to split content when it was sent.

So it would be nice to decide what we should do here.

**Comment by rachelhamlin** [comment]
Well, let's definitely fix this issue of messages needing to be collapsed again, and keep the other one separate.
