### ISSUE TITLE
Not all items are displayed with markdown in nested message

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9487]
# Bug Report

## Problem
If a lot of items should be shown with markdown, it applies only for some of them in the start and in the end of the message.
REproducible with Android only(tried with Android 8 and Android 9)

#### Expected behavior
Markdown is applied to all items

#### Actual behavior
![no_markdown](https://user-images.githubusercontent.com/4557972/69146479-3eb8df80-0ad0-11ea-874b-acb89c8ce1ff.gif)

[Payload](https://docs.google.com/document/d/1xWtryiYHfifCuJF5MtIxC7WXCxp9_pkXOkVpCH1Ju3k/edit?usp=drivesdk)

[comment]: # (Describe how we can replicate the bug step by step.)
###Steps to reproduce
- Open Status
- Join public chat
- Send message with several items with markdown (i.e. with 100 `__bold__`)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 18/11/2019
- Operating System: Android

**Comment by cammellos** [comment]
Verified it's not a problem with markdown specifically, seems like it's more of an issue with rendering an android

**Comment by churik** [comment]
still relevant on nightly 26/02/2020 (bold is not applied)

**Comment by churik** [comment]
Still relevant on 1.4

**Comment by cammellos** [comment]
I'll close this one for now, given we limit the number of messages and cut it off it's probably less of an issue, feel free to re-open
