### ISSUE TITLE
Reply in input box is not scrollable

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9488]
# Bug Report

## Problem

On released 0.13.2 when you tap on long message > Reply you can scroll inside input box to see all content.
Currently you see only three first rows and ..., content is not scrollable

#### Expected behavior
Content is scrollable and can see the whole message

#### Actual behavior
<img width="218" alt="photo_2019-11-19 13 47 33 jpeg 2019-11-19 13-47-48" src="https://user-images.githubusercontent.com/4557972/69147842-47f77b80-0ad3-11ea-942a-0a93348ba8d6.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join public chat
- Long tap > Reply on long message (> 3 rows)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 19/11/2019
- Operating System: Android, iOS

**Comment by errorists** [comment]
actually this was done by me on purpose :D 3 lines hard limit

**Comment by churik** [comment]
Ah, so it is not an issue?
Ok, closing then
