### ISSUE TITLE
No sorting of chat elements per latest activity on Chats view

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9489]
# Bug Report

## Problem

When message is received to chat we do not move the chat item to the top of list of chats on `Chats`. It's randomly (could not identify pattern yet) sorted  and stands among list of the rest chat elements making it non user friendly as you need o scroll across whole list of chats to find out where new message received.

#### Expected behavior
Chat items on `Chats` view sorted by the latest message received in chat. Thus, chat with latest message moves chat item to the top of the list

#### Actual behavior
Chat items on `Chats` view sorted randomly when mesage is received in chat.
![ezgif-1-8f7b5d34534f](https://user-images.githubusercontent.com/8749671/69148257-8e9da380-0adc-11ea-9d3d-64abe4e94127.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and create new account
- Join several public chats (or 1-1 chats) and read messages
- Join different public chat for testing purposes (e.g. `#test1ordering`)
- Navigate back to `Chats` view
- By another contact send message to public chat  `#test1ordering`
- Verify  `#test1ordering` moved to the top of the list of chats on `Chats` main view

### Additional Information
- Status version: develop` 0.14.0 (2019181102)`
- Operating System: Android and iOS

**Comment by churik** [comment]
@rachelhamlin seems like a very annoying issue, especially when you have a lot of chats.
Probably worth to be included into v1?

**Comment by rachelhamlin** [comment]
Added to P1, and agreed this would be nice to fix.
