### ISSUE TITLE
No SNT by default after multiaccount creation / restoring

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9493]
# Problem

On release 0.13.2 after creating the account you saw ETH + SNT by default, and now only ETH enabled.
So to see SNT you need to go to the options > Mange assets > enable SNT.

I believe that it is better to return SNT by default, as it was before.

**Comment by flexsurfer** [comment]
there is no simple solution for this issue, let's postpone it for now

**Comment by j-zerah** [comment]
hey all - i want to add my 2c here. As part of launch, we will be running a number of campaigns pushing SNT utility both in the application and in the governance of The Status Network:
- Partner campaign with ENS to drive stateofus.eth ens registration (which costs 10 SNT)
- Purchasing Sticker Packs (one of which will cost 20SNT)
- Community governance in q1 of 2020 via a potential update to SNT voting Dapp

All of these features require SNT and we want people to have as little barrier to entry into these features as possible. We also want to remind people that SNT is required for some features and participation in the network.

It makes sense to me to list SNT by default as a friendly reminder that it is required

**Comment by hesterbruikman** [comment]
@flexsurfer can you elaborate on what the solution would be and what's blocking?

@j-zerah Should we create a bunch of offers on Teller so we can instruct people to go to teller.exchange?
cc @iurimatias this also brings the requirement to create combined ETH/ERC-20 offers

**Comment by flexsurfer** [comment]
@hesterbruikman i thought this one is not really important but if we want to promote SNT by showing zero balance, i could look at  this one and find some implementation, so currently we search for new tokens only if we don't have any tokens selected, selecting SNT with zero balance by default we don't search tokens anymore, and if you recover account with tokens only SNT one will be shown

**Comment by rachelhamlin** [comment]
Selected for v1 but it can be fixed after the release candidate is cut this week. Main item driving RC cut off now is commands.

**Comment by j-zerah** [comment]
@hesterbruikman  - when teller is ready and in production, ya seems like a good idea

**Comment by acolytec3** [comment]
@flexsurfer Just a reminder, my [PR](https://github.com/status-im/status-react/pull/9635) that you closed previously should accomplish this.
