### ISSUE TITLE
Empty chat instead of spinner while messages are rendering

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9495]
# Bug Report

## Problem
When chat contains heavy messages and you open it after relogin or on the next day instead of spinner like in [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=3%3A1031) you see "It's been quiet here"

#### Expected behavior
Spinner like in [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=3%3A1031) 

#### Actual behavior
![rendering](https://user-images.githubusercontent.com/4557972/69161550-a2043b00-0aeb-11ea-95bb-d7c8ff076772.gif)

### Reproduction

- Open Status
- Join to a chat with heavy messages (long text, markdown, ect)
- Relogin
- Open this chat again

### Additional Information

- Status version: nightly 19/11/2019
- Operating System: Android, iOS (however messages are rendered faster on IOS, and this issue is not so visible)

**Comment by churik** [comment]
still relevant on nightly 26/02/2020

**Comment by churik** [comment]
Don't agree - it is extremely visible, so it is always like "blinking" when navigating to chat.
summon @errorists to have your opinion about that.
IMO at least some spinner is needed to make it smoother - it shouldn't be too much effort from dev side

**Comment by errorists** [comment]
I agree, I never liked that even before the spam, it's noticeable and jarring. Can't we cache the messages so we can show the last state? Or if that's not on the table, do some skeleton loading like Discord does?

**Comment by churik** [comment]
can't see this behavior on release 1.13, reopen if still relevant
