### ISSUE TITLE
Upgrade nixpkgs to include Go 1.13

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#9500]
I was requested by @cammellos to upgrade the current Go version we are using:
https://github.com/status-im/status-react/blob/5ecc7590d98fafd834a065dad82c01649b47c973/nix/derivation.nix#L20
But in order to do that I might have to do a full upgrade of our [`nixpkgs`](https://github.com/status-im/nixpkgs) fork.

Previous Go upgrade for reference: https://github.com/status-im/nixpkgs/commit/35e0ad9f6d83f431fe5a156793e44f095b8039ab

**Comment by jakubgs** [comment]
It appears that the main issue with upgrading `nixpkgs` is that our `status-mods` branch in [our fork](https://github.com/status-im/nixpkgs/tree/status-mods) contains quite a few custom fixes to make old QT version work for MacOS desktop builds:

* https://github.com/status-im/nixpkgs/commit/f9763e572651199117f4444de0df6783068fecde
* https://github.com/status-im/nixpkgs/commit/e2ab4ad56aed99eca93cb5a45c4c8cedbba5e536
* https://github.com/status-im/nixpkgs/commit/f23f949d533b513b5a991873cb841aefe93c8bd2
* https://github.com/status-im/nixpkgs/commit/06e0997892cae4ffafed8e79cfdf422c10773391

Those fixes might be quite a pain to port to an updated `nixpkgs` branch. Considering currently the work on the desktop app has been suspended it might make more sens to just disable desktop builds in CI and go back to fixing this when we resume work on desktop.

@vkjr what do you think about this?

**Comment by vkjr** [comment]
@vkjr, totally fine with that!

**Comment by jakubgs** [comment]
I'm working on this in the `nixpkgs-upgrade` branch using the [`status-mods-upgrade`](https://github.com/status-im/nixpkgs/tree/status-mods-upgrade) branch of `nixpkgs` and currently I'm struggling with building `gomobile` correctly.

When building `status-go` I was getting:
```
Building mobile library for android

type-checking package "github.com/status-im/status-go/mobile" failed (/build/go/src/github.com/status-im/status-go/mobile/multiaccount.go:4:2: could not import encoding/json (go/build: importGo encoding/json: exit status 2
go: cannot find GOROOT directory: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.13.4/share/go
```

So I checked the strings and indeed the pats in `gomobile` have been changed:
```
 $ strings /nix/store/c0y10k1v1ydnqgmnzyd14nffcv5n38sr-gomobile-20190719-d2bd2a2-bin/bin/.gomobile-wrapped | grep eeeee | head -n 5 
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.13.4/share/go
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.13.4/share/go/src/html/template/urlpart_string.go
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.13.4/share/go/src/html/template/url.go
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.13.4/share/go/src/html/template/transition.go
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.13.4/share/go/src/html/template/template.go
```
Which means it gets treated with the `remove-references-to` function like `status-go` is:
https://github.com/status-im/status-react/blob/8bd2326369ac5424e55d397cdbee5455ac376f1b/nix/status-go/build-status-go.nix#L16-L17
https://github.com/status-im/status-react/blob/8bd2326369ac5424e55d397cdbee5455ac376f1b/nix/status-go/build-status-go.nix#L55-L61

**Comment by jakubgs** [comment]
This same process is done in the `buildGoPackage` function from `nixpkgs`:
https://github.com/status-im/nixpkgs/blob/dd5a7c9b/pkgs/development/go-packages/generic/default.nix#L46
https://github.com/status-im/nixpkgs/blob/dd5a7c9b/pkgs/development/go-packages/generic/default.nix#L211-L213
So in theory this is standard practice for Go packages compiled via Nix. Why then does it cause problems with `gomobile`?

**Comment by jakubgs** [comment]
My guess is that for some reason the Go upgrade to 1.13 causes it to ignore modules available in the `vendor` folder of `status-go` repo.

According to this page:

>The -mod=vendor flag (e.g., go build -mod=vendor) instructs the go commands to use the main module's top-level vendor directory to satisfy dependencies.
>https://github.com/golang/go/wiki/Modules

But I don't see us using this flag in `status-go` repo.

**Comment by jakubgs** [comment]
Looks like setting `GO111MODULE=off` fixes the `status-go` build errors.

**Comment by jakubgs** [comment]
Now my issue is the `STATUS_REACT_HOME` env variable which normally was set here:
https://github.com/status-im/status-react/blob/b5038523879318dbb0fc081d0e898f71f71f4d69/nix/mobile/android/targets/release-android.nix#L112
And this somehow magically propagated to all the other Nix modules like the `fastlane/default.nix` which uses it to find `fastlane/Fastfile` location:
https://github.com/status-im/status-react/blob/b5038523879318dbb0fc081d0e898f71f71f4d69/fastlane/default.nix#L26-L28
My guess is something about upgrading to Nix `2.3.1` caused this to happen.

**Comment by jakubgs** [comment]
I found the Release notes for Nix 2.3, and this one sounds related:

>The installer now enables sandboxing by default on Linux. The max-jobs setting now defaults to 1.
>https://nixos.org/nix/manual/#ssec-relnotes-2.3

Which is:
>`sandbox`
>If set to true, builds will be performed in a sandboxed environment, i.e., they’re isolated from the normal file system hierarchy and will only see their dependencies in the Nix store, the temporary build directory, private versions of /proc, /dev, /dev/shm and /dev/pts (on Linux), and the paths configured with the sandbox-paths option. This is useful to prevent undeclared dependencies on files in directories such as /usr/bin. In addition, on Linux, builds run in private PID, mount, network, IPC and UTS namespaces to isolate them from other processes in the system (except that fixed-output derivations do not run in private network namespace to ensure they can access the network).

So I downgraded Nix to `2.2.1` and tried building again, and it failed the same way.
I'm confused as to which change caused this.

**Comment by jakubgs** [comment]
Nope, still failing:
```
STATUS_REACT_HOME is empty!
```
I can't tell how any of my changes other than a Nix upgrade could have cause this.

**Comment by jakubgs** [comment]
I tried using:
```
export GO111MODULE=on
export GOFLAGS=-mod=vendor
```
As Adam suggested, but `gomobile` fails while trying to download dependencies, so it doesn't work.

**Comment by jakubgs** [comment]
Android builds seem to work, but iOS is failing when building `git`:
```
Building '/nix/store/s8mrfv3h6bsnkgl35bi394yhwsl13k24-git-2.24.0.drv'...
...
/private/var/folders/sn/6fj1hwmd11zdtjk4f5skyj2w0000gp/T/nix-build-git-2.24.0.drv-0/git-2.24.0/t/ \
  ../contrib/completion/git-completion.bash: \
  line 378: compgen: command not foun
```
But hacks around that can be found in `nixpkgs`, which is setting `doCheck = false`:
https://github.com/NixOS/nixpkgs/blob/9b67ea91/pkgs/os-specific/linux/openvswitch/default.nix#L45
But that is already done in our branch:
https://github.com/status-im/nixpkgs/blob/dd5a7c9b/pkgs/applications/version-management/git-and-tools/git/default.nix#L250

**Comment by jakubgs** [comment]
Looks like this is a known issue: https://github.com/NixOS/nixpkgs/issues/73806
And it seem to have been fixed 3 days ago in: https://github.com/NixOS/nixpkgs/pull/73826

**Comment by jakubgs** [comment]
PR: https://github.com/status-im/status-react/pull/9531
