### ISSUE TITLE
Token Warnings

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9505]
# Feature Issue

Add a feature for warning users about tokens they hold and needs some action to be taken, such as upgrading to a new contract, or about potential security issues on the token. 
The current listing of tokens the wallet have, could have a new optional fields for enabling this warnings.

### User Story

As a user, I want to be warned when I hold tokens which are not good to use, as for example:
- TheDAO tokens which should be withdrawn into ether after DAOFork.
- Arcade City tokens that needed to be converted into Swarm City tokens
- SAI token, which have their name renamed from DAI.
- New DAI token, which taken the name from old DAI (now named SAI).
- SAI token, which should be upgraded. 

### Example 

https://etherscan.io/address/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 
![image](https://user-images.githubusercontent.com/224810/69275745-c0396c00-0bbb-11ea-989a-20c1aee1ab0b.png)

### Notes

See #9491

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. Added `recheck` label for easy finding that one in case of need
