### ISSUE TITLE
Chat onboarding tooltip needs fixes to scroll behaviour

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9509]
# Problem

The current implementation of the chat onboarding tooltip has issues that relate to scrolling. 

- First, if the list of chats is empty, the screen can't be scrolled. This should be fixed to accommodate scrolling, when the list is empty.

- Secondly, after the tooltip is dismissed, the list still counts its height for the purpose of scrolling. This can be best observed on the video below

- Third, the tooltip doesn't have the bottom margin of 64, it should be possible to scroll so it's not covered by the + button.

[Link to video demonstrating issues](https://www.dropbox.com/s/7kn9gcnj26g0sx8/onboardingscroll.mp4?dl=0)

## Implementation

Implement the tooltip properly so it behaves just like a regular item on a scrollable list

## Acceptance Criteria

All of the above were fixed

## Notes

Thank you kindly!

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/69530171-e1121080-0f71-11ea-8bad-efefe03d4925.png)
