### ISSUE TITLE
It takes too long time to load dapps list on Android and there is no list at all on ios

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9525]
# Bug Report

## Problem

Because of dap.ps the only way to navigate to different dapps,  it's a major part of our application, and currently list of dapps works really bad, It takes too long time to load dapps list on Android and there is no list at all on ios

#### Expected behavior

list loads fast on ios and android

Related issue : https://github.com/dap-ps/discover/issues/16

**Comment by flexsurfer** [comment]
cc @rachelhamlin @andremedeiros

**Comment by rachelhamlin** [comment]
Hmm. Wonder if this has the same root as the [iOS bug](https://github.com/dap-ps/discover/issues/16) - dapps not loading at all. We had a contributor on it but I think we should take a look at this ourselves before v1.  Dapps are loading okay on my desktop browser. 

Any chance this is also [Infura related](https://github.com/dap-ps/discover/issues/54)?

**Comment by flexsurfer** [comment]
> Hmm. Wonder if this has the same root as the iOS bug 

yes it's in the description

> Any chance this is also Infura related?

here are two different issues:
1) list is empty on ios, because of CORS
2) loading long time on Android - because of infura yes, but different infura - ipfs, stickers also slow because of infura ipfs

**Comment by jakubgs** [comment]
But we are loading those Infura IPFS resources via an AWS CDN, so those should be cached.

**Comment by flexsurfer** [comment]
@jakubgs could you elaborate? i believe we load them directly from ipfs.infura

**Comment by jakubgs** [comment]
Not directly, what we do is our backend calls Infura and makes images available via it's own API available at `/metadata/image` which is affected by the AWS CloudFront CDN as you can see from the headers:

![dap_ps_image_req](https://user-images.githubusercontent.com/2212681/69541467-7e2c7380-0f89-11ea-9e41-e3979499aa99.png)

![dap_ps_image_req_headers_000](https://user-images.githubusercontent.com/2212681/69541471-808ecd80-0f89-11ea-9745-51c06a368873.png)

**Comment by flexsurfer** [comment]
yeah was talking about stickers in the status app, sorry for confusion

**Comment by flexsurfer** [comment]
blocked by dap-ps/discover#16

**Comment by jakubgs** [comment]
I fixed up the load times a bit by closing: https://github.com/dap-ps/discover/issues/54

I'll take a look at iOS load issues tomorrow before I go on holidays.

**Comment by flexsurfer** [comment]
thanks @jakubgs , the reason for ios is 
![image](https://user-images.githubusercontent.com/11790366/70779667-c8cd2e80-1d84-11ea-9fd2-1d032423ae09.png)

**Comment by flexsurfer** [comment]
so how it works, if there is no access to status web3, dap.ps calls infura directly from browser

**Comment by flexsurfer** [comment]
https://github.com/dap-ps/discover/issues/16#issuecomment-565344123

**Comment by rachelhamlin** [comment]
Pretty sure we can close this one. https://dap.ps takes a beat to load on my Samsung, but the DApps load very quickly.

Still need to push changes from prod.dap.ps to whatever https://dap.ps points at, but the fix is in https://github.com/dap-ps/discover/issues/16#issuecomment-565344123.
