### ISSUE TITLE
Can't submit DApps on dap.ps

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9528]
# Bug Report

## Problem

Issue is captured in the dap-ps org repo: 

[Can't submit new DApp on iOS](https://github.com/dap-ps/discover/issues/12)

#### Expected behavior

User can complete a form and stake SNT in order to submit their DApp to be listed.

#### Actual behavior

Connectivity errors. 

#### Acceptance Criteria

Submission is successful. 

### Reproduction

- On iOS, navigate to https://dap.ps while on mainnet
- Scroll to bottom and `Submit a DApp`
- Enter information and hit `Continue`
- `Publish` DApp with or without staking SNT 

### Additional Information

Tested most recently on iOS 13.1.3

**Comment by flexsurfer** [comment]
@rachelhamlin is this fixed ?

**Comment by rachelhamlin** [comment]
Yes, I believe so.
