### ISSUE TITLE
Wallet UI: Ability to see and copy a transaction hash and full address of receiver/sender

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#954]
### User Story

As a user, I want to see and copy full transaction hash (both for the current transaction and for past transactions) so that I can use it in other apps.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently, in Main Wallet it's possible to see Transactions list with 
- not full address of recipient/sender with ... at the end (depends if it's in or out transaction )
- Date and time of transaction
- Sum that was transferred
- "+" or "-" to show in and out transaction

What users would like to have:
1. For sure: possibility to see and copy transaction hash (not shown in current version)
2. Most likely: possibility to see and copy an address of recipient/sender (not fully shown in current version)

Examples of available fields/data on ROPSTEN TESTNET:
* Transactions overview for address: https://testnet.etherscan.io/address/0xd0844aff4f66176702dd2ffd07dcc3731c5caab4
* Details of a transaction: https://testnet.etherscan.io/tx/0x8e6848da62006a68259f97a78600c06ea613eae81429320c307cbf28447e805f

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
For current transaction and for previous transactions: 
1. Transaction hash is visible to user and can be copied
2. Sender/Receiver address is fully visible and can be copied 
#### Actual behavior
[comment]: # (Describe what actually happened.)
1. Transaction hash can be found
2. Address of receiver/sender is not fully visible and can't be copied
![wallet ransactions](https://cloud.githubusercontent.com/assets/6584810/24450295/af4dde3e-147a-11e7-99b9-0d7401023216.jpg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- Send some contacts (both in contact list and with scan QR) some ETH
- Receive some ETH from your contacts or via Scan QR
- Open Wallet and check Transactions 

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Need new designs and interaction flows to include data on Transaction hash and full address of receiver/sender for past transactions and for current transaction
- [ ] Implement designs

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4
* Operating System: Android and iOS

Instabug:
* https://dashboard.instabug.com/applications/status/beta/bugs/171
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/321

**Comment by yenda** [comment]
oudated with new wallt
