### ISSUE TITLE
Search can't be opened by pull-to-refresh gesture

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9540]
# Bug Report

## Problem

Search edit box appears and immediately hides when pull-to-refresh - so the search of chats is not usable.

#### Expected behavior
Can search

#### Actual behavior
![search](https://user-images.githubusercontent.com/4557972/69733814-41e64800-112e-11ea-9fca-8a025d4acbf8.gif)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join several chats
- Pull-to refresh to open "Search"

### Additional Information

- Status version: nightly 27/11/2019
- Operating System: Android, iOS

@rachelhamlin regression issue IMO should be fixed as part of V1

**Comment by errorists** [comment]
@rachelhamlin search is embarrassing at the moment, can I put forward a suggestion to disable it for v1? :)

**Comment by churik** [comment]
It is at least a way to access chats quickly, so don't agree with removal.
It's OK when you have 20 chats, but if you have 100 it's quite difficult to find particular one.

**Comment by StatusSceptre** [comment]
Merging with #9576
