### ISSUE TITLE
Crash with "Can't popup empty list" error at attempt to sign transaction after tapping on "Done" several times  in "Recipient"

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9562]
# Bug Report

## Problem

Reproducible only on account with large amount of transactions, so can't reproduce on new accounts.
Crash is happening when trying to resolve ENS name or just tap on "Done" several times on "Recipient" screen since the wallet is extremely slow, it is a very common scenario.

#### Expected behavior
can sign transaction

#### Actual behavior
"Can't pop empty list" and crash

#### Notes
Related to https://github.com/status-im/status-react/issues/9203 as wallet is extremely slow after restoring multiaccount.

### Reproduction

- Open Status
- Restore multiaccount with transactions
Below are steps that worked for me:
- Switch to Ropsten
- Go to wallet > Send
- in "Recipient" type "nastya.stateofus.eth"
- tap on "Done" several times (as name is not resolved from the 1 attempt)
- try to sign transaction

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 02/12/2019
- Operating System: Android, iOS

#### Logs

[status_logs.zip](https://github.com/status-im/status-react/files/3910819/status_logs.zip)

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by rasom** [comment]
@churik tried to reproduce, no success

**Comment by churik** [comment]
Can't reproduce as well.
8 days ago I tried 5 times and it was reproducible, Sergey also could reproduce it.
I'll remove it from v1 scope for now and will wait until @Serhy will try on his accounts as well.

**Comment by Serhy** [comment]
Now with develop `0.14.0 (2019121602)` build I'm able to reproduce even with new account (no transactions) when submitting valid ENS name as recipient in Wallet by tapping 'Done' quickly several times (reproducing with Galaxy J7 Android 8.1). And now it's not only "Can't popup empty list" pop-up appears but I wind up on different screen (depends of how many times tap 'Done').

Video of current behavior: 
https://drive.google.com/file/d/1-6Z5PR6CTpK3jUqPq1b8mkuKr8zqEz6i/view


Reproduction:
1) Create new account
2) `Wallet` -> `Status account` -> `Send` -> `Choose recipient` -> `Enter recipient address`
3) Enter `nastya.stateofus.eth`
4) Tap `Done` 5+ times like you are in panic want to send transaction asap

<img width="427" alt="Screenshot 2019-12-17 at 12 01 52" src="https://user-images.githubusercontent.com/8749671/70985588-0b647300-20c5-11ea-97d8-bdc2ea3d70ed.png">

If to disable (and grey out) `Done` button after tap that would solve the problem. 
Not a V1 prioriority.

**Comment by rachelhamlin** [comment]
Hmm, I couldn't reproduce on nightly on iOS or Android. Clicked `Done` in a total panic and everything.
