### ISSUE TITLE
Do not allow user to "Show my ENS username in chats" unless the setting Tx is mined

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9565]
# Bug Report

## Problem
"Show my ENS username in chats"  is available when transaction for setting chat key don't get enough confirmations, because it will not be visible in chat.

#### Expected behavior
should be greyed out when the transaction is pending

#### Actual behavior
available immidiately

#### Notes
Leftover from #9473 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Restore multiaccount that owns ENS that is not connected with your chat key
- Open Profile > ENS
- Type your ENS
- Procced to signing. Pay attention to "Show my ENS username in chats" after signing transaction (small network fee makes issue more visible)

### Additional Information

- Status version: nightly 02/12/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
Feature is removed for now

**Comment by Serhy** [comment]
Feature returned back and this issue too. Reopening.

**Comment by Serhy** [comment]
Sorry misread the issue description, this feature removed.
