### ISSUE TITLE
Release iOS 0.13.3 crashes on launch

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9570]
# Bug Report

## Problem

iOS beta release 0.13.3 crashes on launch (iOS13.2)

#### Expected behavior

Stautus launches
#### Actual behavior

Status crashes

<img width="277" alt="Screenshot 2019-12-03 at 11 52 29" src="https://user-images.githubusercontent.com/8749671/70039983-6aa18e00-15c3-11ea-9665-3bcbbc8051eb.png">

#### Notes
Jenkins job made release build https://ci.status.im/job/status-react/job/release/job/release%252F0.13.x/16/
Commit bumped app version https://github.com/status-im/status-react/commit/3cae015d6425b26070df3b38a37a06895bf44512 

### Reproduction

- Install Status from TestFlight
- Open Status

### Additional Information
- Status version: 0.13.3 release
- Operating System: iOS

#### Logs

Logs with crash details (logs which filtered by StatusIm in dev console)

[iOS13-2_crash_logs_forStatusIm_process.log](https://github.com/status-im/status-react/files/3915920/iOS13-2_crash_logs_forStatusIm_process.log)

**Comment by Serhy** [comment]
cc @rachelhamlin @jakubgs @andremedeiros

**Comment by jakubgs** [comment]
I fixed the build, but I have no idea about why the crash happens, I'm not a mobile developer.

**Comment by Serhy** [comment]
Build `0.13.3 (2019120317)` tested with iOS 13.2, looks good:
- Can install build from TestFlight and launch fine
- Can create and recover an accounts
- Can see messages from public chats and can exchange messages in 1-1/Group
- Can send transaction in 1-1 chat and from Wallet
- Can send transaction in DApp

Thank you @flexsurfer, @jakubgs !

**Comment by jakubgs** [comment]
So ultimately the commit that will be released is 3480aef404ad98ff00904da90daad756676d92fb on the [release/0.13.x](https://github.com/status-im/status-react/tree/release/0.13.x) branch.

Can we press the release button already, or are there any remaining qualms?

**Comment by Serhy** [comment]
Pressed the button, but it's Waiting for Review now. As soon as reviewed, will release

**Comment by jakubgs** [comment]
Awesome, thanks Sergey!
