### ISSUE TITLE
Enabling biometric on signin issues

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9573]
# Bug Report

## Problem

1) It says keycard for regular accounts without keycard
![image](https://user-images.githubusercontent.com/11790366/70121344-b0fff700-166e-11ea-8c57-18e0283ae3d2.png)

2) Clitical security issue
  - check "save password"
  - enable biometric
 - press "save password"
 - press "cancel"

save password still selected, and biometric should be enabled, sig in, check biometric, biometric is off

3)select "save passord", cancel biometric, deselect "save password" , select "save password" - no popup with biometric

**Comment by flexsurfer** [comment]
@churik @rasom

**Comment by churik** [comment]
missed it, thx @flexsurfer

**Comment by rasom** [comment]
3) is not an issue, nothing to confirm there as biometric hasn't been enabled

**Comment by flexsurfer** [comment]
3. i mean no popup suggesting to  enable biometric, i expect it every time i select "save password" why it works only first time?

**Comment by rasom** [comment]
@flexsurfer oh I see then, will re-check tomorrow
