### ISSUE TITLE
Make sure status supports EIP 1102 and EIP 1193

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9575]
https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a

1) In Metamask, the provider by default has an empty array of accounts, which will be populated if the user gives access to the dapp, while Status' provider returns null. This causes Status to raise this error: "The requested account has not been authorized by the user." in this code block 

It is causing problems in Embark because it uses getAccounts a lot to determine if a dapp is connected or not.

2) web3.eth.getCoinbase() returns default account , should return selected account for dapps

**Comment by rachelhamlin** [comment]
Are we removing the EIP1102 browser tool tip as part of this issue now?

![image](https://user-images.githubusercontent.com/15470435/70454628-be572000-1a78-11ea-8433-27143ad5a6e3.png)


To recap the discussion from Discord:
- By now, modern DApps are compliant with EIP1102. 
- And in fact, no longer work if privacy mode is disabled. Thus, the `Always allow` option will break up-to-date DApps.
- As such, we will hide this tooltip to encourage the use of privacy mode in the browser. Users can disable privacy mode from their profile settings. Copy update TK.

More problematically, there is a lack of consistency between MM's implementation, Trust's, etc. DApps are almost guaranteed to be broken in some browsers now. We will touch base with MM to see how we can work together on improving this.

**Comment by flexsurfer** [comment]
@rachelhamlin MM doesn't have this options anymore and privacy mode enabled by default, most modern dapps don't support  privacy mode disabled mode, so probably we can just remove this setting in this PR same as MM did

**Comment by rachelhamlin** [comment]
Oh, got it. Okay, that sounds good.
