### ISSUE TITLE
Sometimes confirmation window does not appear on logout

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9584]
# Bug Report

## Problem
Causes false e2e failures.
Can be reproduced ~ 1 from 4 times.
Generally on Logout confirmation popup appears and you need to tap OK for logout, but sometimes it just logged out automatically.

#### Expected behavior
confirmation popup

#### Actual behavior
user is logged out

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Login
- Log out
- Repeat until the issue is reproduced

### Additional Information

- Status version: nightly 04/12/2019
- Operating System: Android, iOS

**Comment by michaelsbradleyjr** [comment]
I am unable to reproduce this bug in current `develop`, using either iOS simulator or a physical android device.

The code related to logout was refactored in d823a2082a9edac8949d18d80065c2637f111812 and some other commits a couple of months ago.

@churik have you encountered this bug in e2e testing recently?

**Comment by churik** [comment]
no, for a long time.
I'll close it for now, thanks!
