### ISSUE TITLE
Random crash when click on + > Start new chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9586]
# Bug Report

## Problem

Sometimes app crashes after tapping + > start new chat (e2e tests caught this behavior 2 times in one set of 150 e2e).
Couldn't reproduce manually.
Most likely was introduced by https://github.com/status-im/status-react/pull/9571, was found during testing rebased https://github.com/status-im/status-react/pull/9547

#### Expected behavior
no crash

#### Actual behavior
app crashed

### Reproduction

- Open Status
- Restore multiaccount from seed phrase
- Tap on + > New chat

### Additional Information

- Status version: develop after https://github.com/status-im/status-react/pull/9571
- Operating System: so far Android

#### Logs

Full video / logcat is [here](https://app.saucelabs.com/tests/43527423de714648881de6508cbf82b4?auth=e3f92a1ede922c99b2b49273fe05fa0d)

Crash logs:
```
12-04 07:05:33.317  4351  4377 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:34] - :on-will-focus :new-chat
12-04 07:05:33.323  4351  4351 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 448)
12-04 07:05:33.323  4351  4351 D AndroidRuntime: Shutting down VM
12-04 07:05:33.324  1636  1704 W InputDispatcher: channel '264c501 im.status.ethereum.pr/im.status.ethereum.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-04 07:05:33.324  1636  1704 E InputDispatcher: channel '264c501 im.status.ethereum.pr/im.status.ethereum.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
--------- beginning of crash
12-04 07:05:33.324  4351  4351 E AndroidRuntime: FATAL EXCEPTION: main
12-04 07:05:33.324  4351  4351 E AndroidRuntime: Process: im.status.ethereum.pr, PID: 4351
12-04 07:05:33.324  4351  4351 E AndroidRuntime: java.lang.RuntimeException: Adding window failed
12-04 07:05:33.324  4351  4351 E AndroidRuntime:  at android.view.ViewRootImpl.setView(ViewRootImpl.java:738)
12-04 07:05:33.324  4351  4351 E AndroidRuntime:  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
12-04 07:05:33.324  4351  4351 E AndroidRuntime:  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
12-04 07:05:33.324  4351  4351 E AndroidRuntime:  at android.app.Dialog.show(Dialog.java:330)
```

**Comment by rasom** [comment]
I can't reproduce this issue

**Comment by rasom** [comment]
@churik unless we have clear steps to reproduce I'm not sure what to fix here.

**Comment by churik** [comment]
It is random and I saw it in e2e again - so users can see it from time to time as well.
For now I can remove v1 release and we will see how dogfooding of Status will go.

**Comment by rasom** [comment]
But you haven't reproduced it manually, right?

**Comment by churik** [comment]
no, I couldn't either.
I only see it in e2e and fetch all logs.

**Comment by vkjr** [comment]
Also wasn't able to reproduce.

**Comment by churik** [comment]
didn't see this for a while
