### ISSUE TITLE
Minor fixes in popup

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9596]
- The title should have "Fingerprint" (Touch ID/Face ID for iOS) in it;
- Paddings and type size must be re-checked. Also, line-height of the main text. If it's not possible to make the text grey with some words black, all text should be grey, not black

<img width="873" alt="Screen Shot 2019-12-06 at 14 54 16" src="https://user-images.githubusercontent.com/3115606/70321413-50bcb100-1838-11ea-8869-cd2da2e406b4.png">

Figma https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

**Comment by rasom** [comment]
https://github.com/status-im/status-react/issues/9354
