### ISSUE TITLE
Lines around blinking icons

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#960]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For "blinking" icons there are 4 lines shown around icon (e.g. password request, phone request, money request)

![lines next to password icon](https://cloud.githubusercontent.com/assets/6584810/24552592/5548382c-1627-11e7-8044-477da010dd75.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No lines are shown around icon
#### Actual behavior
[comment]: # (Describe what actually happened.)
4 lines are shown around icon when it's blinking
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
screencast: https://www.screencast.com/t/e1WlierG
- Open Status and login
- Open Console and check icon for phone number request
- From other contact request money from your contact. 
- Open 1-1 chat with money request and check the icon next to it

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4-25-gb7ef782+  epic/ui-refresh (Android) http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-b7ef78.apk
[comment]: # (Android or iOS.)
* Operating System: Android 7.0. (real Samsung Galaxy S7). On iOS looks fine (no lines are shown)

**Comment by occamin** [comment]
Hey @annadanchenko 

Is this still a bug? I tried to reproduce locally on my phone (Huawei Ascend Mate 7, Android 6.0) and an AVD more similar to a S7 (Android 7.0 5.1-inch 2560x1440). Both times there were no blinking lines around the icon

**Comment by annadanchenko** [comment]
@occamin yes, I can reproduce it on 0.9.7-21-g1b2f657+ (develop build).
Using Galaxy S7, Android 7.0
I also noticed that lines are getting more visible if you scroll to the blinking icon and leave it to blink for 4-5 times

**Comment by rasom** [comment]
@annadanchenko can this be reproduced now?

**Comment by annadanchenko** [comment]
can't reproduce on Galaxy S6
