### ISSUE TITLE
Keycard Settings – Change passcode

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9600]
<img width="1613" alt="Screen Shot 2019-12-06 at 16 44 10" src="https://user-images.githubusercontent.com/3115606/70327365-b49aa600-1847-11ea-8924-10aeb8223616.png">

Everything here is quite straightforward, let me know if I am missing something? Is the "Confirm with card" step necessary? cc @guylouis 

Figma https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=917%3A19200

**Comment by guylouis** [comment]
There are two options I guess 
- as you described, only one tap of card fater user has input old and new pin (2x). 
Pro: only one tap
Con: if user enters a wrong old passcode, he has to enter the full process again (type new passcode two times)
- first ask the user to type his old password, tap the card, if NOK error message, if OK we need to store the passcode in RAM the time for the user to enter his new passcode and tap again the card 
Pros: if old passcode is wrong, error message is shown directly 
Cons: two taps, and passcocde is stored in RAM 

Seems a good subject for a quick talk during our weekly sync :)

@andmironov
@michele

**Comment by guylouis** [comment]
After discussion we're going for the first option, as described by andrei above.

**Comment by andmironov** [comment]
also, i'm adding "forgot passcode" button and flow. We were discussing a separate issue for this, but i think it might make sense to do it here

<img width="598" alt="Screen Shot 2019-12-10 at 17 02 52" src="https://user-images.githubusercontent.com/3115606/70535970-ff316080-1b6e-11ea-94c3-2089ad1061be.png">
