### ISSUE TITLE
Keycard Settings – Unpair card

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9601]
<img width="1569" alt="Screen Shot 2019-12-06 at 16 47 09" src="https://user-images.githubusercontent.com/3115606/70327537-0e9b6b80-1848-11ea-8218-001570fa9f56.png">

All the steps and copy are on the image. Am I missing something @guylouis ?

Figma https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=576%3A0

**Comment by guylouis** [comment]
The warning should be about that the userneeds to have his pairing password written down somewhere to regain access to his cards, if he lost it he's f***ed, if he has it then he can repair his card to the phone and is not limited in any ways
