### ISSUE TITLE
QRCode scanned ERC681 (Transaction Request) does not fill value

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9606]
# Bug Report

## Problem

When using QRCode scanner an ERC681 link, it fills only the author and token. Value is not filled. 

#### Acceptance Criteria

Value must be filled for erc20 token transfers and for ETH value transfers when processing ERC681 links.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open a Wallet
- new Transaction
- Scan QRCode

**Comment by churik** [comment]
AFAIK now (on nightly 15/04/2020) links with params (value, contract address, etc) are resolved only if scanning them from wallet -> QR icon at the top from wallet view.
In case of usage for scanning ERC681 link Send transaction screen > To > Scan recipient address only address is resolved.

it is confirmed by @hesterbruikman (pinging just in case)
@3esmit that's the issue, did I understand correctly?

**Comment by churik** [comment]
can be closed after implementing  processing ERC681 links from wallet -> scan QR
