### ISSUE TITLE
Universal QRCode scanner

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9609]
# Feature Issue

### User Story

As a user I want to have easy access to a QRCode scanner, so I don't have to find the right place to scan something.  

### Description

Currently we have two QRCode scanners, one in chat, and other in the transaction form. It's correct for each of them only accept the types they expect, however it becomes complicated to users if they have to find the right place to scan a QRCode.

Other applications that use multiple QRCode types use only a universal scanner, which recognize the type being scanned and follow the correct path.

For Status, that would be processing [ERC-681] and other future [ERC-831], this universal scanner would be important.

Other modifications would have to be made, such as the public chats, private chats, and more follow a standard format, so it can be decoded by the scanner more easily.

Without falling into [ERC-831], scanning;
- `#channel`: a public channel; 
- `@0x"68 byte long number"`: a pubkey (private chat); 
- `@anything.eth`: resolve a pubkey (private chat); 
- `anything.eth`: resolve a [ERC-1577] in browser (dapp). 

Falling into [ERC-831] we could have also:
`ethereum:pay-`: [ERC-681], opens payment wall with default account;
`ethereum:tx-`: [ERC-2400], checks and display transaction (offer link to view in etherscan).

After scanning, the data should be rendered (when possible) and user must be asked if want to follow the scanned action (never autorun on scan), which the rendering would help in user decision.  

### Notes

The list of [ERC-831] should grow. A discussion was open to standardize all deep links in Status under this standard, see https://discuss.status.im/t/eip831-uri-format-for-ethereum-in-status/1402

[ERC-831]: https://eips.ethereum.org/EIPS/eip-831
[ERC-681]: https://eips.ethereum.org/EIPS/eip-681
[ERC-1577]: https://eips.ethereum.org/EIPS/eip-1577
[ERC-2400]: https://github.com/status-im/EIPs/blob/tx-hash-uri/EIPS/eip-2400.md

**Comment by andmironov** [comment]
Here's an issue about the QR code scanner in wallet https://github.com/status-im/status-react/issues/9649

**Comment by flexsurfer** [comment]
@3esmit is this still relevant?

**Comment by hesterbruikman** [comment]
Closing this issue as it's tracked here #10764
