### ISSUE TITLE
Wallet: Add "Send max"

### ISSUE THREAD

**Issue by leafcutterant** [status-im/status-react#9611]
### User Story

As a user, I want to have a button "Send max" so that I can send the maximum amount of a currency and leave no dust behind.

### Description

*Type*: Feature

*Summary*: see above

### Additional Information
* Operating System: Android

**Comment by andmironov** [comment]
a quick sketch (not final). wdyt? @flexsurfer 

Also, can we include a USD value?

<img width="401" alt="Screen Shot 2019-12-17 at 17 05 07" src="https://user-images.githubusercontent.com/3115606/71001967-6743f180-20ef-11ea-9cca-59b3746de68b.png">

**Comment by leafcutterant** [comment]
Looks good ! Just please make sure that the feature also makes it to the send screen when initiated from the wallet and from the dapp browser.

**Comment by andmironov** [comment]
sure! there should be no difference regarding the entry point. this popup is the same everywhere

**Comment by flexsurfer** [comment]
done
