### ISSUE TITLE
App Crash in iOS 

### ISSUE THREAD

**Issue by bamos01** [status-im/status-react#962]
### User Story

Installed status with testflight on iOS (updated to newest release.  I am able to create new account and log in but wallet does not sync and eventually app crashes.  I delete reinstall app but same behavior.  I think problem is I have old wallet data and it cannot sync- needs to be cleaned out and sync from scratch but no way to do this that I know of .

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: <Bug|Feature>

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- ...
- Step 3, etc.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by annadanchenko** [comment]
@bamos01 Can you reproduce the issue with version 0.9.5?

**Comment by yenda** [comment]
Outdated
