### ISSUE TITLE
Messages with stickers can't be quoted and used in replies

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9624]
# Feature Issue

Not possible to quote message with stickers or reply with stickers to ordinary messages.

### User Story

As a user, I want to be able to quote stickers and reply with stickers.

### Description

**Scenario 1:**
- send sticker to public chat
- try to long-tap on it to have options (I believe only `reply` should be available here) 

It can be combined with install pack (now install menu is opened automatically on tap) - wdyt @errorists @hesterbruikman? 

**Scenario 2:**
- send message without stickers to chat
- long tap on it > Reply
- use stickers

**Expected result:**
quoted message with sticker
**Actual result:**
quoted message remains in input field
![photo_2019-12-09 16 53 06](https://user-images.githubusercontent.com/4557972/70450682-6c2bf400-1aa4-11ea-89fb-10d2f4f67b5b.jpeg)

**Comment by errorists** [comment]
Here are the designs for replying to stickers in chat [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1643%3A749)

However replying with stickers to messages would need some significant changes to how the chat input works and I don't plan on adding that yet. For the time being I think posting a sticker separately after replying is not a deal breaker.
