### ISSUE TITLE
Placeholders "Enter ENS username" and "Create a topic" are cut on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9625]
# Bug Report

## Problem
Placeholders are cut for:
1) + > Start new chat > chat key input field
2) + > Start group chat > "Create a topic"
![photo_2019-12-09 17 11 29 jpeg 2019-12-09 17-12-04](https://user-images.githubusercontent.com/4557972/70452403-5cfa7580-1aa7-11ea-86c9-9544e6388577.png)

#### Expected behavior
placeholders are not cut

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 09/12/2019
- Operating System: Android

**Comment by churik** [comment]
@rachelhamlin small one but extremely visible, might be worth to fix  in v1 scope

**Comment by StatusSceptre** [comment]
We can fix after feature freeze :)
