### ISSUE TITLE
Remove chat menu item and toggle app switching privacy on by default

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9636]
# Problem

Combination issue spanning two product areas:

1. Chat `+` menu—remove an option
2. `Profile` > `Privacy and security`—turn a setting ON by default, alter copy

## Implementation

- Remove the `Scan a QR code` option from the chat menu

![image](https://user-images.githubusercontent.com/42685581/70577402-386ece00-1b79-11ea-92b7-029b835c6b2c.png)

- Change the copy of `Hide content when switching apps` to `White out Status when switching apps`
- Set this toggle to be ON by defautl
![image](https://user-images.githubusercontent.com/42685581/70577490-50465200-1b79-11ea-844f-2b2ab919bb2a.png)

## Acceptance Criteria

- No more scan QR code option in chat menu
- New copy for Privacy and security option
- White out setting is on by default

**Comment by churik** [comment]
Reason why scannig QR code option in chat menu should be removed:
from @hesterbruikman:  it's out of context in chat. I genuinely love the scan anything feature, but in our current tab based UI we don't really have a fitting spot for such a global feature and it leads to an overwhelming nr of options inside chat. Would love to see it make a come back when we move to something like window-based navigation
