### ISSUE TITLE
java.lang.IllegalArgumentException 16>0 after entering wrong PIN on login screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9650]
# Bug Report

## Problem
![photo_2019-12-12 11 51 53](https://user-images.githubusercontent.com/4557972/70706405-1e96cd80-1cd6-11ea-996a-8a46e00160ed.jpeg)

#### Expected behavior
2 retries are left

#### Actual behavior
java.lang.IllegalArgumentException 16>0  

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new multiaccount
- Log out
- Enter wrong PIN
- Tap card to NFC

### Additional Information
- Status version: nightly 12/19/2019
- Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
12-12 19:00:00.083 15837 16039 D CardChannel: RESPONSE LEN: 00, SW: 6F00 
12-12 19:00:00.083 15837 16039 D CardChannel: -----------------------
--------- beginning of crash
12-12 19:00:00.084 15837 16039 E AndroidRuntime: FATAL EXCEPTION: Thread-6
12-12 19:00:00.084 15837 16039 E AndroidRuntime: Process: im.status.ethereum, PID: 15837
12-12 19:00:00.084 15837 16039 E AndroidRuntime: java.lang.IllegalArgumentException: 16 > 0
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at java.util.Arrays.copyOfRange(Arrays.java:3444)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.keycard.applet.SecureChannelSession.transmit(SecureChannelSession.java:407)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.keycard.applet.SecureChannelSession.mutuallyAuthenticate(SecureChannelSession.java:277)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.keycard.applet.SecureChannelSession.mutuallyAuthenticate(SecureChannelSession.java:264)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.keycard.applet.SecureChannelSession.autoOpenSecureChannel(SecureChannelSession.java:130)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.keycard.applet.KeycardCommandSet.autoOpenSecureChannel(KeycardCommandSet.java:164)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.ethereum.keycard.SmartCard.getKeys(SmartCard.java:308)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at im.status.ethereum.keycard.RNStatusKeycardModule$9.run(RNStatusKeycardModule.java:212)
12-12 19:00:00.084 15837 16039 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
12-12 19:00:00.106  1829  3463 D WindowManager: Input focus has changed to Window{e3fe73e u0 im.status.ethereum/im.status.ethereum.MainActivity}
12-12 19:00:00.131  3456  3456 D StatusBar: disable<e i a s b h r c s > disable2<q i n g r >
12-12 19:00:00.131  3456  3456 D PhoneStatusBar/NavigationBarView: setDisabledFlags back:false home:false recent:false
12-12 19:00:00.132  3456  3456 D StatusBarClock:  isNormalMode= true clock visible=true
12-12 19:00:00.206   782  1556 I SDM     : HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
12-12 19:00:00.206   782  1556 I SDM     : HWCDisplayBuiltIn::NotifyCitSensorService: out partial brightness:53.718937 R:236.000000, G:238.000000, B:236.000000
```

**Comment by churik** [comment]
cc @guylouis @rachelhamlin @rasom

**Comment by rasom** [comment]
@churik can't reproduce in nightly

**Comment by churik** [comment]
@rasom indeed, in current nightly I see other behavior.

It is different for 2 phones (Android8 and Android10).
Steps are the same:
- create account with keycard 
- tap card to the back of the phone
- log out (continue hold card to the back of your phone)
- enter wrong PIN

Results for LG V20 (Android 8):
connection with card is lost screen, you need tap card back and forth, then wrong PIN code error
![LG-phone](https://user-images.githubusercontent.com/4557972/70903719-c1fe2000-1fff-11ea-9e86-57123907c988.gif)
Log: 
[Log-phone.log](https://github.com/status-im/status-react/files/3967785/Log-phone.log)


Results for Xiaomi Mi Note 9 (Android 10):
"You tapped wrong card" error
![telegram-cloud-document-4-6032622046469424660](https://user-images.githubusercontent.com/4557972/70904380-7ba9c080-2001-11ea-95b7-2377ae2288a1.gif)

[xiaomi-log.log](https://github.com/status-im/status-react/files/3967791/xiaomi-log.log)


Issue is reproducible until relogin.

**Comment by guylouis** [comment]
could not reproduce it with nightly from 06/02/2020 and a one plus 6 phone

**Comment by rasom** [comment]
@churik 
I can reproduce 
```
Results for Xiaomi Mi Note 9 (Android 10):
"You tapped wrong card" error
```
but I think that's a different issue from original `java.lang.IllegalArgumentException 16>0` problem. And I can't reproduce `java.lang.IllegalArgumentException 16>0`. So we rather need to edit this issue or close it and create a new one.

**Comment by churik** [comment]
better to create new one.
Closing this issue.
Thx @rasom
