### ISSUE TITLE
Message state in group chat is not updated (endless spinner after sending)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9653]
# Bug Report

## Problem
Messages are delivered, but status is not updated
![photo_2019-12-12 13 55 35](https://user-images.githubusercontent.com/4557972/70713820-18f5b380-1ce7-11ea-9c5b-bbf6b6346ca2.jpeg)

#### Expected behavior
"Sent"

#### Actual behavior
endless spinner

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create group chat with User B
- as User B: join Group chat
- Send message to group chat

### Additional Information
- Status version: nightly 12/12/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
cc @rachelhamlin @cammellos

**Comment by churik** [comment]
If we will release with this error, better to disable Group chats at all IMO

**Comment by cammellos** [comment]
It should be easy to fix, I can have a look

**Comment by churik** [comment]
@cammellos checked on today nightlies:
https://i.diawi.com/Yk4cAd
https://status-im.ams3.digitaloceanspaces.com/StatusIm-191220-025900-a72d4c-nightly-universal.apk

It is still an issue.
And I suppose that it is a reason why replied messages are not visible in group chats as well:

![photo_2019-12-20 12 13 12 jpeg 2019-12-20 12-13-48](https://user-images.githubusercontent.com/4557972/71251304-49aa9e00-2322-11ea-97d7-81c5a77657b8.png)

**Comment by rachelhamlin** [comment]
Can we please keep the priority on commands if not complete yet? It would be great if we could fix everything, but we have to release at some point. I'll give group chat another run through today.

**Comment by cammellos** [comment]
yes, I am not actively working on this, I am on commands with eric

**Comment by cammellos** [comment]
This is reported to be fixed in develop, @churik @Serhy could you confirm if that's the case and close if necessary? Thanks!

**Comment by Serhy** [comment]
Confirmed with iOS and Android it's not reproduces anymore with the latest nightly build. Closing the issue.
