### ISSUE TITLE
'Cannot read property' error at attempt to add members to group chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9655]
# Bug Report

## Problem
Crash with error `Cannot read property 'ToLowerCase' of null` at attempt to add members without contacts or null is not an object when user has some contacts

#### Expected behavior
can add member

#### Actual behavior
![IMG_6538](https://user-images.githubusercontent.com/4557972/70722674-fc15ac00-1cf7-11ea-805f-70e6eda6cd2a.PNG)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create Group Chat with some user
- Go to options > group info > add members

### Additional Information

- Status version: nightly 12/12/2019
- Operating System: <Android|iOS>

#### Logs

[status_logs-2.zip](https://github.com/status-im/status-react/files/3956357/status_logs-2.zip)

**Comment by churik** [comment]
cc @rachelhamlin @cammellos

**Comment by acolytec3** [comment]
Could I pick this one up? Would be interested in doing a chat related issue.

**Comment by cammellos** [comment]
@acolytec3 sure, by all means, that would be very helpful, not sure who to ask if we want to bountify it though, maybe @rachelhamlin

**Comment by acolytec3** [comment]
Oh, not worried about the bounty (though won't say no 😁). I just want to
make sure it's an issue the teams need worked on before I take a look at
it.

**Comment by churik** [comment]
Definitely it is an important one.
Thanks @acolytec3!

**Comment by acolytec3** [comment]
@churik Is this still a bug?  I'm not 100% sure I'm following how to recreate it but I've tried creating a group chat and was able to add a member who didn't have any contacts.  Not sure if I'm just not following the steps correctly or not.  Can you give me a chatkey for a generic member with no contacts so I can try recreating?

**Comment by rachelhamlin** [comment]
Hmm, I can't reproduce it on either iOS or Android

**Comment by churik** [comment]
I'll check in 1h and close if couldn't reproduce, thx

**Comment by churik** [comment]
It is gone. Thanks guys.
