### ISSUE TITLE
Correct the appearance of group chat system messages

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9657]
# Problem

Currently system messages in group chats appear like regular messages with mentions inside. It's an improvement over the previous UI, but that's not at all how we want them to look like.

![](https://media.discordapp.net/attachments/626738033701683200/654671507318112276/photo_2019-12-12_14.10.29.jpeg)

## Implementation

<img width="1261" alt="Screenshot 2019-12-12 at 16 12 51" src="https://user-images.githubusercontent.com/4932774/70725612-01292a00-1cfd-11ea-9e02-a89fc3a265fe.png">

---

each system message is just text centred in the chat thread. 8px margin on all sides. Black for username, Grey for the rest.

<img width="375" alt="Group 44" src="https://user-images.githubusercontent.com/4932774/70726377-469a2700-1cfe-11ea-9ef1-1bf8be59396f.png">

---

and that's how they appear in a chat

<img width="375" alt="Group Chat -_ Someone left chat" src="https://user-images.githubusercontent.com/4932774/70726364-439f3680-1cfe-11ea-96d3-1d44abc74b36.png">

Usernames are not links, anonymous random names appear without the `@` character preceding them.

## Acceptance Criteria

Implemented according to design. [Link to Figma here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=480%3A361)

## Notes

Thank you!

**Comment by cammellos** [comment]
This has been merged now @errorists could you check if it can be closed please?
Thanks

**Comment by errorists** [comment]
@cammellos yes, the contributor did an excellent job there, it can be closed. thanks
