### ISSUE TITLE
Recovery word input field is cut off in Keycard flow

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9658]
# Bug Report

## Problem
Recovery word input field is cut off

![image](https://user-images.githubusercontent.com/11790366/70798694-e95ab000-1da7-11ea-8d27-9dbd1aa9f79d.png)

#### Expected behaviour

word is fully visible

**Comment by flexsurfer** [comment]
cc @rachelhamlin @churik

**Comment by rachelhamlin** [comment]
This is fixed in the main recovery flow for sure. I'm pretty sure all instances of this issue are gone, correct me if wrong @Serhy :)

**Comment by flexsurfer** [comment]
its keycard flow

**Comment by rachelhamlin** [comment]
Oops, okay. Let's add to UI back log.
