### ISSUE TITLE
Its not possible to cancel signing transaction with keycard after entering PIN

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9660]
# Bug Report

## Problem

1) Its not possible to cancel signing transaction with keycard

2) There is warning popup after signing transaction

#### Expected behavior

1) Its possible to cancel signing transaction
2) There is no warning popup after sign or cancel transaction

#### Actual behavior

Sign transaction with keycard
Touch device with keycard for 1 second
Remove keycard 
Warning popup appears under signing sheet
Loading indicator is showed on signing sheet
Press cancel on signing sheet
Warning popup is still there
Close popup and try to sign another transaction
There is pincode screen with loading indicator
Not possible to continue

**Comment by flexsurfer** [comment]
cc @rachelhamlin @churik

**Comment by churik** [comment]
Tested the following scenarios:

1. Open wallet > Add values for amount, To > Tap on Send
2. Open wallet > Add values for amount, To > Tap on Cancel
3. Open wallet > Add values for amount, To > Tap on Send > Sign with Keycard
4. Open wallet > Add values for amount, To > Tap on Send > Cancel
5. Open wallet > Add values for amount, To > Tap on Send > Sign with Keycard > Put card to the back of your phone for 1 sec > Processing screen
![photo_2019-12-13 16 15 50](https://user-images.githubusercontent.com/4557972/70810316-d81f9c80-1dc3-11ea-8624-1d3d1969a679.jpeg)
- 5.1. If from this state you will tap on "Cancel", at attempt to sign transaction you will get endless spinner
![photo_2019-12-13 16 32 06](https://user-images.githubusercontent.com/4557972/70811569-22a21880-1dc6-11ea-8af2-40b267208b3a.jpeg)

Logcat: 
[endless-processing.log](https://github.com/status-im/status-react/files/3961416/endless-processing.log)
So you are blocking in transaction signing until manual app restart.

- 5.2. If wait for several mins and then put the card to NFC reader again, connection is not restored, so transaction signing stuck on endless processing.
Logcat:
[endl-processing-signing.log](https://github.com/status-im/status-react/files/3961457/endl-processing-signing.log)

Issues 5.1. and 5.2. are reproducible from Dapp and from Wallet.
@rasom let me know if I need to track 5.1 and 5.2  separately

**Comment by churik** [comment]
cc @guylouis

**Comment by guylouis** [comment]
Reproduced on nightly from 6/02/2020 with JCOP4

JCOP4 being much faster than JCOP3 the signature takes about 1 second. If the card is removed from the phone before this 1 second the issue is still here. 

This issue is still open but slightly less prevalent with JCOP4 than with JCOP3

**Comment by rachelhamlin** [comment]
This strikes me more like user error then. Don't sign and apply keycard if you don't want to confirm, no? @guylouis

**Comment by guylouis** [comment]
An other way to phrase the issue: "if a user removes his card while signing transaction, then the app get into stuck state, and the user doesn't know if he's transaction was signed or can't either sign another transaction"

I did not put it as a 'blocker' since jcop4 is fast, but still when it happens (removing the card while signing) it's a pretty bad behaviour

**Comment by rachelhamlin** [comment]
Ah, okay, clear. It does need a fix, but hopefully not urgently :) Noted.
