### ISSUE TITLE
PUK code screen is overlapping on login screen when PUK code is required (3 unsuccessful PIN attempts)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9661]
# Bug Report

## Problem

<img width="190" alt="Overlap" src="https://user-images.githubusercontent.com/4557972/70900411-09cd7900-1ff9-11ea-9168-99d781677e49.png">

#### Expected behavior
No overlapping

#### Actual behavior
screenshot is attached

### Reproduction

- Open Status
- Сreate Account
- Log out
- Log three times wrong PIN code

### Additional Information

- Status version: nightly 16/12/2019
- Operating System: Android

**Comment by churik** [comment]
oops, duplicated in #10440 
closing it.

**Comment by hesterbruikman** [comment]
Overlap is fixed, but ideally we have the new PUK screen implemented for this issue:

- 'Don't ask for card to sign in' not shown
- PUK entry field has 3 dot areas, in ling with 12 digit PUK
- No overflow menu as this is a separate screen from the Passcode entry and doesn't require 'Get new keys' at this level

Does that make sense? Let me know if you see any issues implementing the flow as on [Figma](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=6825%3A297)


![Frame 180](https://user-images.githubusercontent.com/35233054/81968510-c2d1c700-961c-11ea-98ee-1a52cecb184f.png)

**Comment by rasom** [comment]
@hesterbruikman you are right, it will be fixed with updated PUK flow
