### ISSUE TITLE
 NFC is turned off by default in Status app settings

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9662]
# Bug Report

## Problem
On some phones (device: Xiaomi Note 9, OS: Android 10QKQ1) NFC settings can be set in app settings.
So even globally NFC is turned on, in app settings it can be turned off.
This case is not handled in app, by default it is turned off for Status app.

#### Expected behavior
Turn NFC in your app settings

#### Actual behavior
at attempt to create account nothing happens 
![photo_2019-12-16 12 13 08](https://user-images.githubusercontent.com/4557972/70902579-7185c300-1ffd-11ea-9818-c225c99b2c8d.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Install and open Status
- Try to setup account with Keycard

### Additional Information

- Status version: nightly 16/12/2019
- Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
2-16 17:30:36.653   787  4294 D NxpTml  : PN54X - Invoking I2C Read.....
12-16 17:30:36.660  8947  9833 W LocalConnector: Cannot connect the wmserver-data-reciever-74746
12-16 17:30:36.660  8947  9833 W LocalConnector: java.io.IOException: Connection refused
12-16 17:30:36.660  8947  9833 W LocalConnector: 	at android.net.LocalSocketImpl.connectLocal(Native Method)
12-16 17:30:36.660  8947  9833 W LocalConnector: 	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
12-16 17:30:36.660  8947  9833 W LocalConnector: 	at android.net.LocalSocket.connect(LocalSocket.java:147)
12-16 17:30:36.660  8947  9833 W LocalConnector: 	at com.miui.wmsvc.b.b.a$a.run(Unknown Source:40)
12-16 17:30:36.660  8947  9833 W LocalConnector: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by churik** [comment]
@guylouis WDYT, should be included in release?

**Comment by guylouis** [comment]
this is such a good point, thanks for spotting this. If I understand well, if I have a xiaomi note 9 with NFC turned on, I download status app, then my NFC does not work with status unless I manually to Status dedicated NFC settings. 
That's an issue, and yes we should be included in release

**Comment by churik** [comment]
@guylouis yes, exactly - so if phone have separate NFC preference for each app, it is disabled by default.
Ok, added label.
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
Sorry, but it can't be a release blocker given where things currently stand. We're aiming to submit the app Jan 2nd or 3rd and next week is Christmas. So, need to remove anything non-critical from the v1 release backlog, and this we can live without.

**Comment by Ferossgp** [comment]
Also now NFC check is done only before navigation to screens which need NFC. If the user enables it using quick access sheet, while screen with "Turn on NFC" the app does not react to that. User should close/move to bg and open app again to see NFC changes. It should be a listener as other checks like internet conenction 🙏

**Comment by guylouis** [comment]
I'll create a separate short issue for the architectural change from a one time check to a listener
https://github.com/status-im/status-react/issues/10011
Thanks @Ferossgp

**Comment by rachelhamlin** [comment]
Three months later...I'm now tagging this as `blocker` as in - blocker for keycard release. :) Unless @guylouis, you disagree.

**Comment by rasom** [comment]
@churik are there other devices with such problem?

**Comment by rasom** [comment]
@churik did you try to install other apps which use nfc on this device to check if they somehow solve this issue? like NFC Tools or something

**Comment by churik** [comment]
@rasom 
> @churik are there other devices with such problem?

I have only one where I can configure settings for NFC separately for the app

> @churik did you try to install other apps which use nfc on this device to check if they somehow solve this issue? like NFC Tools or something

Yeah, will do and post update here

**Comment by churik** [comment]
Can't reproduce  - now it always asks to turn on NFC for phone, which is OK.
Will reopen if it will be reproducible again
