### ISSUE TITLE
Missing translations on "Lock app with fingerprint", "Save with password" popups

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9666]
# Bug Report

## Problem
![photo_2019-12-16 15 11 47](https://user-images.githubusercontent.com/4557972/70913487-68552000-2016-11ea-8b4a-a6db5fddbc5f.jpeg)
![photo_2019-12-16 15 12 02](https://user-images.githubusercontent.com/4557972/70913545-7efb7700-2016-11ea-98f2-f50c463d1862.jpeg)

#### Expected behavior
translation is added 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard
- Go to Settings > Privacy and Security > Enable app with fingerprint
- Logout
- Tap on "Don't ask for keycard to sign in"

### Additional Information

- Status version: nightly 16/12/2019
- Operating System: Android

**Comment by churik** [comment]
cc @rachelhamlin @guylouis

**Comment by rachelhamlin** [comment]
Not cute, but not a blocker.

**Comment by churik** [comment]
@rachelhamlin can't agree.
If you tap on "Save password" on Login screen you will see missing translations as well.
It is extremely visible for all users.
![photo_2019-12-20 11 22 52](https://user-images.githubusercontent.com/4557972/71248422-16b0dc00-231b-11ea-8cda-1f86e43c1b99.jpeg)
