### ISSUE TITLE
Keycard can't sign a message or contract interaction provided by a dApp (cryptokitties, status kudos dApp)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9668]
# Bug Report

## Problem
Can't proceed in Cryptokitties DApp after signing message with keycard.

#### Expected behavior
Signed up

#### Actual behavior
can't sign in

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard
- Open cryptokitties
- Create new account, sign message

### Additional Information
- Status version: nightly 16/12/2019
- Operating System: Android

#### Logs

Full adb: 
[logcat-ck.log](https://github.com/status-im/status-react/files/3968761/logcat-ck.log)

**Comment by churik** [comment]
@rachelhamlin @guylouis marked it as v1, as I think it may affect all DApps that requires messge sign.

**Comment by yenda** [comment]
@rachelhamlin I remove the v1 tag since keycard will be disabled

**Comment by guylouis** [comment]
(Tested again with nightly from 06/02/2020 #1423)

The following error message is shown: "Transaction failed - insufficient funds for gas*price + value". The account has enough ETH (0,23ETH)

I got the same problem with the Status Kudos dApp on a contract interaction

It seems Keycard is unable to sign correctly any signature request or contract iteraction sent by a dAop

**Comment by gravityblast** [comment]
@guylouis in general the keycard signs just a hash, so it looks like the hash sent to the keycard is wrong

**Comment by rachelhamlin** [comment]
Browser issue? @siphiuel since you're experienced in both Keycard & browser, can you investigate root cause?

**Comment by vitvly** [comment]
@rachelhamlin yes will look at it. Must be something with hash as @gravityblast mentioned

**Comment by rachelhamlin** [comment]
Thanks @siphiuel!

**Comment by vitvly** [comment]
Tried with Cryptokitties, see the same problem as reported by @guylouis - after signing with Keycard, dapp is not properly redirected, but hangs on 'Sign in' screen. Works for non-keycard account. Added more logging and compared adb logs between keycard and non-keycard accounts, but see no meaningful difference yet.

**Comment by churik** [comment]
@siphiuel have the same behavior in nightly 23/03/2019
Logs: [Status-debug-logs-dapp.zip](https://github.com/status-im/status-react/files/4369744/Status-debug-logs-dapp.zip)

**Comment by vitvly** [comment]
@churik this is strange, i could reproduce it at least in https://github.com/status-im/status-react/pull/9390, but now it's not reproducible either there or in develop. Also tried most recent nightly. Cryptokitties work just fine. Can you please re-check on your end?

**Comment by churik** [comment]
Well, me neither.
