### ISSUE TITLE
Whitespace at the end of seed leads to recovering another account

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#9670]
# Problem

If there are whitespaces at the end of a seed phrase, wrong account will be recovered.
That can be a case when user copies recovery phrase from text editor.

## Acceptance Criteria

Whitespaces between and after seed phrase doesn't affect the recovered account

**Comment by vkjr** [comment]
cc @churik

**Comment by acolytec3** [comment]
We ought to be able to fix this bug with [this PR](https://github.com/status-im/status-react/pull/9648/files) once it gets implemented since that will change the validation logic on validating seed phrases.

**Comment by vkjr** [comment]
@acolytec3, great! Probably this issue worth mentioning in PR `Fixes` section then.
