### ISSUE TITLE
Filling recipient after entering Tx amount clears amount

### ISSUE THREAD

**Issue by StatusSceptre** [status-im/status-react#9671]
# Bug Report

## Problem

The amount is the first field in a transaction. When you fill this out, and then add recipient by scanning their QR code, the amount is reset.

#### Expected behavior

Amount is maintained unless user cancels the Tx.

#### Actual behavior

Set Tx amount.
Scan recipient QR code.
Amount is cleared and must be re-entered.

**Comment by ghmulti** [comment]
Is there any additional information that might help - on which app version the problem has been observed?

**Comment by churik** [comment]
It is a duplicate of #9580
