### ISSUE TITLE
v1 Copy Changes - Bits & Pieces

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9672]
# Problem
App copy has never been reviewed holistically, end-to-end. 

I did so over the past week to ensure clarity, brevity and good grammar. Kept language neutral due to a) time constraint, b) lack of formal brand/creative process and c) desired ease of translation. 

Reviewed with Jonny, Graham, Hester and Maciej in phases.

Additional edits to come in separate issues. This first round is low-hanging fruit, with easy consensus to change.

## Implementation
[This PDF](https://drive.google.com/file/d/1NdrEBrcMvqyNGUednHrMe02UfFqGDuhP/view?usp=sharing) shows various screens in their current state, with desired copy alongside them. 

[This additional PDF](https://drive.google.com/file/d/10rcCsMP9Z7Jh-JYjGjKmjQm9N_pL1Pg4/view?usp=sharing) contains edits to the seed phrase backup flow.

## Acceptance Criteria
Please match desired changes exactly, including capitalization and punctuation.
**There are two changes to ignore in the PDF: please leave `Manage assets` on wallet menu, and ignore the change from `mail servers` to `history nodes`.**

**Keycard onboarding step 3**

* `Backup "Seed" phrase` > Back up seed phrase
* `With this seed phrase you can always get your key back. Write the seed phrase down. Keep it safe, offline, and separate from this device.` > You need this seed phrase to get your key back. Write it down. Keep it safe, offline, and separate from this device.
* `You cannot do this later. Without the seed phrase you will not be able to access your key or any assets associated with it if you loose your device.` > You won’t have a second chance! If you lose or change your device, you will not be able to access your key or any assets associated with it unless you have your seed phrase.

**Chat**

Opening screen

* `Chat and transact privately with your friends.` > `Chat and transact privately with friends`
* `Follow your interests in one of the many public chats.` > Jump into a public chat and meet new people

Join public chat

* `A public chat is where you get to hang out with others, make friends and talk about subjects of your interest.` > Join public chats for your interests! Anyone can start a new one.

Mobile syncing pop-up

* `Sync using Mobile data` > Sync using mobile data?
* `Status tends to use a lot of data when syncing chats. You can choose not to sync when on mobile network.` > Status uses a lot of data when syncing chats.
* `You can change this later in settings` > You can change this later in settings
* `Until connected to Wi-Fi?` > Until connected to Wi-Fi
* ~`You can configure syncing in more detail in settings`~

**Profile**

Privacy and security

* `White out Status when app switching` > Hide Status previews when app switching

About

* `Privacy Policy` > Privacy policy

Sync settings

_Not enough consensus on this yet, please ignore._

* ~`mailserver` > History node~
* ~`Mailserver settings` > History node selection~

**Wallet**

Signing phrase pop-up

* `You should see these 3 words before signing each transaction` > These three words prove that a transaction is safe.
* `If you see a different combo, cancel the transaction and logout.` > You should see these words before signing each transaction. If you don't, cancel and sign out.
* `Remind me later` > Show me this again
* `OK, got it` > Okay, got it

Menu options

IGNORE ONE CHANGE

* ~`Manage assets` > Manage tokens~
* `Set currency` > `Set default currency`
* `Backup your seed phrase` > Back up your seed phrase

Browser

* `Browsed websites will appear here.` > Browser history will appear here

Seed Phrase Backup

* `If you lose your seed phrase you lose your data and funds` > If you lose your seed phrase you lose everything
* `Status can't help you recover your multiaccount if you lose your seed phrase. You are in charge of the security of your data, and backing up your seed phrase is the best safeguard.` > Money, messages, all of it. Status can't access your data nor help you retrieve it. You are in charge of your keys, and your seed phrase is how you recover them. Back it up somewhere safe!
* `OK, continue` > Okay, continue
* `Backup seed phrase` > Back up seed phrase
* `This is your seed phrase. You use it to prove that this is your wallet. You only get to see it once! Write it on paper and keep it safe in a secure place. You will need it if you lose or reinstall your wallet.` > These 12 words are your seed phrase. You need it to recover your account when you change phones or reinstall. Write it on paper and keep it safe. **You only get to see it once!**

**Comment by sirlupinwatson** [comment]
Nice and great modifications that i can refer on, for future interest in translation or editing.
Thanks for this great post @rachelhamlin

**Comment by rachelhamlin** [comment]
More to come @Sirlupinwatson1!

cc @j-zerah @hesterbruikman @errorists @jinhojang6 and @andremedeiros. Mostly as an FYI, but if you have improvements or feedback, please share.

**Comment by acolytec3** [comment]
@rachelhamlin Not sure if this is the right place or not but don't forget to clean up the language/translations related to the `custom-seed-phrase-1` and `custom-seed-phrase-2` labels that are no longer representative of what's happening when restoring a multiaccount from a seed phrase.

**Comment by rachelhamlin** [comment]
@acolytec3 would you want to go ahead and fix that? I think you understand it best. I'm looking at it in en.json and don't understand why the message is split into `custom-seedphrase-1` and `custom-seedphrase-2` - again can pay you directly :) 

[My comment with updated copy](https://github.com/status-im/status-react/pull/9648#issuecomment-567501165)

**Comment by acolytec3** [comment]
@rachelhamlin Sure.  Just to verify my understanding.  You want the english copy updated to below?
`This seed phrase doesn't match our supported dictionary and can't be used. Some words may be misspelled.`

I can't comment on why there's the breakout between the `custom-seed-phrase-1` and `2` but presumably due to field lengths or something given that the original copy here actually had `custom-seed-phrase-3` and `4` too (though I removed those in my earlier PR).  I'll put all of your copy in `custom-seed-phrase-1` and update `custom-seed-phrase` to "Invalid Seed Phrase".

I'm assuming I should leave in `custom-seed-phrase-2` as blank in the English translation and untouched in all the other translations since it looks like the copy isn't broken down into discreet sentences in the two fields.  Right?
