### ISSUE TITLE
Default wallet account not saved after logout on Keycard multiaccounts

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#9677]
# Bug Report

## Problem

Default wallet account `Status Account` is not preserved after restart/logout on Keycard multiaccounts.

#### Expected behavior

`Status account` should be visible under Wallet after logout/restart.

#### Actual behavior

`Status account` is not displayed. All additional accounts are properly preserved between restarts though.

### Reproduction

1. Create or recover a keycard multiacc
2. Go to wallet and there will be one Status account (the default one)
3. Logout/restart app
4. Login again and go to wallet
5. No wallet accounts

### Notes
Probably it's `save-account-and-login-with-keycard` being the culprit here.

### Additional Information
- Status version: latest nightly (tried in current develop)
- Operating System: Android

**Comment by churik** [comment]
cc @guylouis @rachelhamlin

**Comment by guylouis** [comment]
waouh, super critical of course

**Comment by yenda** [comment]
@churik I think this was fixed in https://github.com/status-im/status-react/pull/9691 ?

**Comment by churik** [comment]
Yes, it was, thank you!
