### ISSUE TITLE
Display keycard logo in wallet

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9681]
# Problem
Accounts with keys stored on Keycard need to be easily recognized and distinguished from other accounts as they are stored with a different security level. Design solution is to include a Keycard logo on the account cards.

## Implementation
In account overview and individual account view add logo to account card if account is stored on Keycard.
Designs here: https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=4550%3A0

![Keycard logo](https://user-images.githubusercontent.com/35233054/71030925-af284000-2112-11ea-88b7-24aadca36ce5.png)

## Acceptance Criteria
Pixel perfect following design

**Comment by hesterbruikman** [comment]
cc @guylouis @andmironov couldn't find an issue for this, please share if there is one.

**Comment by andmironov** [comment]
no such issue, thanks!

**Comment by guylouis** [comment]
The keycard logo is in the account overview and we can consider it's enough
