### ISSUE TITLE
Don't drop unconfirmed transactions

### ISSUE THREAD

**Issue by leafcutterant** [status-im/status-react#9684]
# Bug Report

## Problem

I sent transactions that were expected to be included in hours. They are still visible on Etherscan, but Status dropped them from the Transaction history screen after a while and I don't know what status will do if they become confirmed.

#### Expected behavior

Don't drop transactions. Keep a record of each one initiated by the user, even if it is never included in the chain.

#### Actual behavior

Drops transactions (they disappear from Transaction history, even though they were there initially).

### Reproduction

See above

### Additional Information

- Status version: 0.13
- Operating System: Android

**Comment by michaelsbradleyjr** [comment]
Related to #9976 (blocker).

**Comment by churik** [comment]
IMO it is duplicate of https://github.com/status-im/status-react/issues/9976
Closing for now, free to reopen
