### ISSUE TITLE
"Invalid status code: 530" when switching to Goerli network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9688]
# Bug Report

## Problem

Can't switch to Goerli network. There is an error appears when trying to connect: `Invalid status code: 530`

#### Expected behavior

Can switch to Goerli network

#### Actual behavior

<img width="352" alt="Screenshot 2019-12-18 at 12 10 43" src="https://user-images.githubusercontent.com/8749671/71077082-6fec0480-218f-11ea-9314-f236bd7b7f74.png">

### Reproduction
- Open Status and create new account
- Navigate to `Profile` -> `Advanced` -> `Network` -> `Goerli with upstream RPC`
- Tap `Connect`

### Additional Information

- Status version: develop 2019121702
- Operating System: Android and iOS

**Comment by Serhy** [comment]
I think we need it fixed in V1, @rachelhamlin @andremedeiros

**Comment by Serhy** [comment]
https://goerli.blockscout.com/ that we use as upstream has 530 response.

**Comment by rachelhamlin** [comment]
I don't think it's a blocker. Isn't this used primarily around ETHBerlin? Even if not - as long we have a working testnet, not a blocker.

**Comment by churik** [comment]
closed in favor of #11964
