### ISSUE TITLE
UI corrections in the stickers panel, scroll / animation

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9699]
# Problem

Current implementation of the sticker panel has a couple of issues that combined make it appear buggy.

• Whenever it's presented, it visibly scrolls to the sticker pack you had previously selected. Instead it should start at the correct index right away without scrolling to it.
• When switching between the text input and stickers or commands, the entire view blinks and jumps, visible on the attached video. Instead the input and icons toolbar should simply animate to the new position, like it does when switching from stickers to text input.
• another issue spotted by @Ferossgp `if you open stickers in chat then go back and enter again the same chat the stickers panel opens. IMO it should not. It is minor, but I think it can be added in backlog`, needs a fix

[Attached video here](https://www.dropbox.com/s/rpsqyj9truf9cse/stickers%20bugs.mp4?dl=0)

## Implementation

• Stickers start at the correct index without scrolling to it each time
• switching between text input and stickers doesn't blink the view, instead smoothly animating the toolbar to its new position.

## Acceptance Criteria

Both issues were corrected

## Notes

thanks a bunch! 🙏

**Comment by hesterbruikman** [comment]
@errorists @Ferossgp are the issues described in this issue still relevant?

**Comment by churik** [comment]
closing as stale issue, @errorists please reopen if still relevant, thank you!
