### ISSUE TITLE
Keycard pairing code: evaluate if we simplify pairing code format

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#9703]
**Context** 
When onboarding with a brand new keycard
- status app is generating a pairing code for this card and sets it up in the card 
- the user is asked to write it down (he's not asked to type it in, because that's not necessary technically speaking)

when a user wants to use this card with another phone with status, he'll be asked to enter the pairing code 

**Problem**
The pairing code format generated by status is 20 letters or numbers, and is case sensitive. This is quite complex and can create human error writing down or typing it 

**Solution**
Should we simplify the format of the pairing code while maitaining a sufficient level of entropy (ux-security tradeoff) ? 

remark: other apps like Gnosis can initiate keycards, and are free (given keycard api) to setit up in any format. So we should keep Status entry form free format too, for the case where a status user wants to pair with a card generated on Gnosis.

**Comment by guylouis** [comment]
a more radical approach is questioned in #9064 (abstraction of pairing code and PUK)

**Comment by bitgamma** [comment]
the format implemented is 5 characters, where a lower-case letter is followed by a number. 0/1 l/o are excluded from the list of allowed symbols  to allow confusion. The reason for this exact format is a compromise between length, number of possible combinations and making sure that no embarassing words are generated.
