### ISSUE TITLE
Redirect to 1 step from 3 if put card to NFC on Backup seed phrase during pairing (no key on card)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9704]
# Bug Report

## Problem
Workflow is broken (app redirects to enter PIN code after "Back up seed phrase" step) if put card to and from NFC reader on  "Backup seed phrase" screen when paiting card after cancelling initial create multiaccount flow.

#### Expected behavior
Step 3 -> Backup seed phrase -> finishing up

#### Actual behavior
Step 3, then step 1.

![telegram-cloud-document-4-6041711533002589704](https://user-images.githubusercontent.com/4557972/71168999-3c28e180-2258-11ea-962e-dcdd64c308e4.gif)

### Reproduction

- Open Status
- Get Started -> Generate Key -> Next -> Keycard -> enter and confirm PIN code
- on "Pairing code and PUK" screen cancel setup
- Get Started -> Generate Key -> Next -> Keycard -> enter valid Pairing code
- Hold card to the NFC reader
- on "Backup seed phrase" screen put card back and forth to NFC reader

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 19/12/2019
- Operating System: Android 

#### Logs

[broken-flow.log](https://github.com/status-im/status-react/files/3983216/broken-flow.log)

Card info:
```
Installed: true
Initialized: true
Key Initialized: false
InstanceUID: 0xd8aa1d7203207211cd903f526c255d01
SecureChannelPublicKey: 0x04816ba10bc533551239a3216fc3cbf46402d51c52b9ff6159b707967e9a0bfe20dbd3831661f3a4d0e540e7041ea6bf31cf55e79ef06896a1d8ab4e2396bfc191
Version: 0x0300
AvailableSlots: 0x05
KeyUID: 0x
Capabilities:
  Secure channel:true
  Key management:true
  Credentials Management:true
  NDEF:true
```

**Comment by hesterbruikman** [comment]
For future reference. This issue should be resolved if https://github.com/status-im/status-react/issues/9365 is implemented as the bottom sheet state should not affect navigation.
