### ISSUE TITLE
Tozemoon stickers are not shown in chat on recipient side

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9706]
# Bug Report

## Problem

When sending any sticker from Tozemoon package it is not displayed for recipient(s) in public/1-1/group chats 

#### Expected behavior

Tozemoon sticker is shown for recipient 

#### Actual behavior

<img width="527" alt="Screenshot 2019-12-19 at 17 39 21" src="https://user-images.githubusercontent.com/8749671/71186816-89bc4300-2286-11ea-979f-dc35392c18f3.png">

#### Notes

From core chat:
`sticker.Pack == 0` might be a reason

### Reproduction

- Open Status on UserA and UserB side
- UserA added UserB in contacts
- UserA installs `Tozemoon` sticker pack
- UserA sends tozemoon sticker to UserA in 1-1/public/group chat

### Additional Information
- Status version: `develop 2019121802`
- Operating System: Android and iOS

**Comment by Serhy** [comment]
@rachelhamlin @andremedeiros @cammellos @flexsurfer  added in V1 scope

**Comment by flexsurfer** [comment]
fixed here https://github.com/status-im/status-go/pull/1749

**Comment by rachelhamlin** [comment]
Bravo Andrey.
