### ISSUE TITLE
text-change optimisations

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#971]
@flexsurfer had noticed that typing generates numerous events [here](https://github.com/status-im/status-react/pull/909#issuecomment-291776898) 

> when i was working with the input field i noticed that it require a lot of CPU when writing text, and sometimes it works with glitches on Android. I found that each inputted symbol generates at least 15 events, and if you're writing fast it's a large flow of events and calculations, maybe we need some optimization here because chatting fast using simple text is the main purpose of chats

**Comment by jarradh** [comment]
what are the events generated?

**Comment by flexsurfer** [comment]
next re-frame events 
![image](https://cloud.githubusercontent.com/assets/11790366/24698564/d1dc974a-19f9-11e7-9adf-0523334858a6.png)

each event will be processed on `goog.async.nextTick` and there may be inconsistency and visual glitches

**Comment by flexsurfer** [comment]
also on opening dapp a lot of duplicated events 
![image](https://cloud.githubusercontent.com/assets/11790366/25268083/0c8fbfba-2680-11e7-8aff-04461a1bb760.png)

**Comment by alwx** [comment]
I've combined and/or removed several redundant calls.

This is how it looks now (when you enter a letter):
<img width="217" alt="screen shot 2017-04-21 at 10 36 20" src="https://cloud.githubusercontent.com/assets/911127/25273926/9c75773a-2696-11e7-8e5d-220af54f5530.png">
