### ISSUE TITLE
New empty state in case tx history cannot be shown

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9710]
# Problem
There are several issues with tx history. See https://github.com/status-im-status-go/issues/1665 and #9203 

Currently we show "No transactions in your history" which is misleading as the issue is that they are not updated. 

New empty state can be shown in this case.
Other empty states require updating for consistency

## Implementation
<img width="1470" alt="Screen Shot 2019-12-20 at 13 50 11" src="https://user-images.githubusercontent.com/3115606/71250014-a9f40c80-232f-11ea-87c9-d12c7b3a6ef9.png">

Figma: https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=1743%3A303

#### Persistent link
Let's always show the etherscan link since we are not sure if the history is consistent

#### There might be more. Refresh
Let's give the user control over refreshing the history.

#### Loading
Since the loading might take a while, let's show Loading transaction history. This might take a while. below the loading spinner;

#### Error
Design should be shown on two requests:
* Verify that there were transactions
* Exclude received tokens
@rasom can you clarify why we need to exclude these?

#### No transactions
Fix the line-height of No transactions here yet (Should be Main Text 15px style)

Etherscan link should include address of selected account (i.e. the account in view): https://etherscan.io/address/address

## Acceptance Criteria
Pixel perfect according design

## Future Steps
* Add account
* Send funds from one account to another
* Check History

Note for post-v.1 : Let's keep in mind that there's more to improve this screen. For instance, loading of long transaction history lists should be paginated and additional Send/Receive buttons should appear.

**Comment by hesterbruikman** [comment]
@andmironov merged https://github.com/status-im/status-go/issues/1751 into this issue, please check

**Comment by rachelhamlin** [comment]
@hesterbruikman I'm just glancing at this, but given that #9203 is fixed and we always show a link to Etherscan - is this issue satisfied for v1? It seems to be, but let me know if I removed the label too quickly.

**Comment by hesterbruikman** [comment]
Yes, I think it's fine to remove the V1 label as fetching issues shouldn't occur as often. We can leave it open regardless until the loading states are implemented.

**Comment by rachelhamlin** [comment]
Okay, great, we're in alignment!

**Comment by churik** [comment]
I believe it works in very similar way now, as we show "Something went wrong" in case we can't load history and can pull-to refresh to upgrade history.
@hesterbruikman please, reopen if still relevant.
Thanks!
