### ISSUE TITLE
Overall balance is not changing after deleting watch-only account 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9717]
# Bug Report

## Problem
After deleting watch-only account  wallet balance should be changed accordingly. Now it is possible to get such state:
![Monosnap 2019-12-20 17-21-13](https://user-images.githubusercontent.com/4557972/71268409-2ba66300-234d-11ea-8205-d7c79820f769.png)

After relogin balance is updated.

#### Expected behavior
Balance is updated

#### Actual result
Balance is not updated

### Reproduction

- Open Status
- Add watch-only account with funds
- Delete watch-only account with funds
- Check overall balance

### Additional Information
- Status version: nightly 20/12/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
@rachelhamlin can be a bounty I believe.
It is easy one for @acolytec3 :)

**Comment by acolytec3** [comment]
I'll take a look later today. I'm guessing it's a quick fix since it sounds like the same issue as that other balance related bug.

**Comment by StatusWrike** [comment]
➤ acolytec3 commented:

I'll take a look later today. I'm guessing it's a quick fix since it sounds like the same issue as that other balance related bug.

**Comment by acolytec3** [comment]
PR submitted.  :grin:
