### ISSUE TITLE
No 'Apply' button appears when updating "Wallet"-> "Account"-> "Account settings"

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9723]
# Bug Report

## Problem

When updating account from it's settings in Wallet (Name/Colour) there is no way to apply the changes because `Apply` button is not showing up at the top-right of top-bar when changing any setting of the account. 

#### Expected behavior

Apply button appears at the top-right of the screen upon changin any of colour/name of "Wallet"-> "Account"-> "Account settings"
#### Actual behavior
<img width="280" alt="Screenshot 2019-12-23 at 13 14 15" src="https://user-images.githubusercontent.com/8749671/71355000-50394f80-2586-11ea-9836-79b06e18e554.png">

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Might be regression from https://github.com/status-im/status-react/commit/f90fe2f04ddd8fa8abc15eb2cb2c0af99837587a

### Reproduction

- Open Status and create new account
- Navigate to `Wallet` -> `Status account` -> top-right `...` menu -> `Account settings`
- Change name or colour

### Additional Information

- Status version: 0.14.0 (2019122015)
- Operating System: Android and iOS

**Comment by churik** [comment]
it means that it is not possible to update account settings.
v1 IMO
