### ISSUE TITLE
Status is not usable after relogin if add watch-only account that matches address of one of the created accounts

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9724]
# Bug Report

## Problem
If add watch-only account that matches address of Status account (or any account that is already created in your multiaccounts) it is not possible to login again or to create new multiaccount or login to existing one

#### Expected behavior
Can't add watch-only account with same address

#### Actual behavior
![photo_2019-12-23 16 37 21](https://user-images.githubusercontent.com/4557972/71366531-82f14100-25a2-11ea-9c10-d01a15c6a2f8.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create multiaccount
- Open wallet -> copy address of status account
- Add watch-only account that matches the address of status account

### Additional Information

- Status version: nightly 23/12/2019
- Operating System: Android, iOS

#### Logs

[no-rows-in-result-set.log](https://github.com/status-im/status-react/files/3995455/no-rows-in-result-set.log)

**Comment by acolytec3** [comment]
Can I pick this one up?  I've got an idea on how to fix that should be pretty straight forward.
