### ISSUE TITLE
password confirmation [chat-ui]

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#973]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description
![image](https://cloud.githubusercontent.com/assets/11790366/24743895/aec01722-1ab8-11e7-85e9-f189b1a57514.png)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

**Comment by alwx** [comment]
This issue is fixed in #982
