### ISSUE TITLE
Arguments with spaces [chat-ui]

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#974]
Arguments cannot contain spaces.
It means that if you enter something like `/phone +44 1234 567891`, the handler will treat the string like the `phone` command with 3 arguments `["+44" "1234" "567891"]`.

It can be solved the same way as Bash solves it: `/phone "+44 1234 567891"` should be treated like a command with one argument.

**Comment by rasom** [comment]
<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/24752055/ec667384-1ad4-11e7-9c8d-53dd9c9cceb7.PNG />

^ suggestions 

<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/24751927/2b7a288c-1ad4-11e7-93af-cd2d93a8031f.PNG />

I have doubts that users will start writing their phone number with `"` character... I mean, imagine that user is writing `/phone +380 67` without tapping on suggestion but using it as an example. So he see that `+380 39 123 4567` example,  but when he tries to use such format it doesn't work. That's confusing

**Comment by alwx** [comment]
So what we're going to do with this issue now?

**Comment by jarradh** [comment]
first off the phone command should be using the phone keyboard
second couldn't the javascript handler can use `arguments` array and concatenate all params into one phone number before parsing?

**Comment by jarradh** [comment]
quotation marks won't fly here

**Comment by alwx** [comment]
That's right. But what about *now*? Am I right that we're going to comment out this command because it doesn't work anyway?

**Comment by jarradh** [comment]
Either fix it now and we can look at status-server and twilio closely, since nobody has. 
or comment it out and fix it in the future.

**Comment by alwx** [comment]
I think it's better to comment it out now, because writing custom handlers for commands will take time. Nobody prevents us from commenting it out and starting looking at status-server and twilio closely right after that.
