### ISSUE TITLE
Hide keycard options for Android as well (v1)

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9740]
# Problem

Keycards are being wiped on recovery—we are therefore not going to sell any until we have resolved the issue. 

This issue is to hide any Keycard related options in the onboarding & recovery flows on Android. Keycard options are already hidden on iOS.

## Implementation

Remove these options from Android v1 build:
 - Unlock screen -> Add existing keys -> `Recover with Keycard`
- During onboarding (Access existing keys -> Enter seedphrase  --> ..... -> Select Keycard as storage)

![image](https://user-images.githubusercontent.com/15470435/71670637-81600f80-2d3e-11ea-949a-a59fa51c305c.png)

## Acceptance Criteria

Option to recovery with Keycard no longer appears on Android.
Key storage selection no longer appears on Android during onboarding.

## Notes

cc @guylouis @gravityblast @andremedeiros 

## Future Steps

Resolve erased keycard issue w/ help of NXP.

**Comment by guylouis** [comment]
cc @bitgamma too

**Comment by rachelhamlin** [comment]
Evidently the current release build does not include any references to Keycard, so if we're basing v1 off a release (?), then we don't need to change anything here. Just need to be aware of this.

cc @churik @Serhy
