### ISSUE TITLE
Chat command UI requires account selection first

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9742]
# Problem

When sending funds via chat command, the UI requires you to select a wallet to send from before entering an amount.

If you do this in the wrong order, as prompted if following the flow from top to bottom of the screen, you will receive an `Insufficient funds` error. 

![image](https://user-images.githubusercontent.com/15470435/71679354-5f25bc00-2d55-11ea-82e6-0237129e2e51.png)

## Implementation

How can we improve this? 

- Restrict user from entering amount until account is selected
- Highlight account selector on the screen
- Reverse the order of amount and account selector
- [Update the error copy to be more instructive](https://github.com/status-im/status-react/issues/9742#issuecomment-570605945)

I think this requires your input @andmironov & @yenda - not a v1 blocker but it's fairly confusing.

## Acceptance Criteria

We need to agree upon a solution before determining acceptance criteria.

**Comment by rachelhamlin** [comment]
I think the best solution is one proposed by Andrea. Can we just change this error message to read, "Select account first"? 

Then we can improve later. cc @andmironov @yenda

**Comment by yenda** [comment]
@rachelhamlin @andmironov what about selecting the first account by default? (I made and pushed the fix in a separate commit anyway)

**Comment by rachelhamlin** [comment]
💯 that works for me @yenda

**Comment by andmironov** [comment]
@yenda yep, that's great!

**Comment by flexsurfer** [comment]
@yenda is this fixed ?

**Comment by yenda** [comment]
yes
