### ISSUE TITLE
Support importing private key

### ISSUE THREAD

**Issue by danimesq** [status-im/status-react#9749]
By seed (MetaMask) and privatekey.

**Comment by acolytec3** [comment]
@DaniellMesquita When you say "seed", are you referring to the 12 word seed phrase?  If so, that's already supported in account onboarding.  If you take the seedphrase for your metamask account and use that as the "keys" during account onboarding, the first account that is created in your wallet will be your Metamask account.  

Alternatively, are you just wanting to be able add an ethereum address on the wallet views that's not tied to the multiaccount logged in?

**Comment by rachelhamlin** [comment]
Bingo. In v1, you can do this during account recovery, as @acolytec3 says.

However, the option to add an address by seed phrase within another wallet is on the backlog.

**Comment by danimesq** [comment]
There is a imported ETH address in my MetaMask account, which means seed will not import. My request is to support importing private keys.

**Comment by acolytec3** [comment]
@rachelhamlin I think `status-go` supports this already, if I'm reading the [`extkeys`](https://github.com/status-im/status-go/blob/c0c963bdaade096dd0ce6eb7b9eed9ef7620f652/extkeys/hdkey.go#L343) code correctly though we'd need to add it to the API in order for status-react to consume it, kind of like we did with BIP39 mnemonic validation.  Is this something the core team would want to add as an additional way to recover an account?  Seems like an edge case for the general public but I suppose there are those who would like to import accounts to the Status app who didn't generate them from a mnemonic.

**Comment by rachelhamlin** [comment]
To be honest, we hadn't thought about it in context of recovery. We do have plans to import keystore files into existing accounts, but it is a rarer case. My first priority would be to support the [`Add account` > `Enter a seed phrase` path](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=4207%3A3446) within wallet.

**Comment by danimesq** [comment]
My main account is based in privatekey.
Im using MetaMask mobile as it quickly supported privatekey importing. Im yet willing to also use Status.

**Comment by edsonayllon** [comment]
I'd like this as well. My main account is saved via private key. That account has things like reputation in DAOs that are non-transferable, and is currently the owner to my ENS name.

**Comment by rachelhamlin** [comment]
I've been hearing this from quite a few folks and inside Status once or twice. Sounds like a reasonable next addition to wallet (over importing from seed phrase, actually). Thanks guys, for speaking up. @edsonayllon @DaniellMesquita @acolytec3

**Comment by acolytec3** [comment]
Can we implement in status-go? I might be interested in working on it 😁

**Comment by churik** [comment]
@rachelhamlin 
 https://github.com/status-im/status-react/pull/10100 implemented importing private key + seed phrase inside the wallet.
So actually it resolves importing of private key itself, but you can't use your ENS on that wallet anyway (currently multiple accounts are not supported in ENS)

**Comment by danimesq** [comment]
@churik 

But if only the keypair imported account have a domain, it works?

**Comment by churik** [comment]
@DaniellMesquita what do you mean `have a domain`?
Do you have ENS name registered in your wallet, which you want to connect to chat key?

**Comment by danimesq** [comment]
@churik

Yes, my privatekey I need to import uses that.

How to download this build (isn't in Play Store and the /releases page is very outdated compated to it) ?

**Comment by churik** [comment]
@DaniellMesquita 
You can import your account inside status multiaccount using your private key in next release (1.1.0) - release is in `Testing` stage now.

But you still can't use your ENS on this account, because ENS is using default (`Status` wallet).
So currently to use ENS you still need your seed phrase (to get it in MetaMask you need to import it first to browser extension, and then open Settings > Security > Reveal seed phrase) 

 I'll create separate issue about importing  default account (`Status` wallet) using the private key (in that case you can use ENS name)

**Comment by flexsurfer** [comment]
> to get it in MetaMask you need to import it first to browser extension, and then open Settings > Security > Reveal seed phrase

it's not possible if you have the only private key,

> I'll create a separate issue about importing default account (Status wallet) using the private key 
this won't be implemented because of security

better to create an issue for selection wallet for ens name
