### ISSUE TITLE
App freezes if tap on digital keyboard after "Cancel" on Send Transaction screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9759]
# Bug Report

## Problem

There is a lag between tap on "Cancel" on "Send Transaction" and the moment of closing digital keyboard for entering amount. If tap during this time on any key on digital keyboard  - app is freezing until force reopening.

#### Expected behavior
app is not freezing or it is not possible to tap on keyboard

#### Actual behavior

![2020-01-07 13 18 23](https://user-images.githubusercontent.com/4557972/71895105-659aa600-3150-11ea-95b4-f7b724c81cca.gif)

### Reproduction

- Open Status
- Open Wallet
- Tap on "Send"
- Tap on Cancel
- When keyboard is still shown, tap on any key

### Additional Information

- Status version: nightly 07/01/202
- Operating System: Android, iOS

#### Logs

[app-freezw.log](https://github.com/status-im/status-react/files/4030607/app-freezw.log)

**Comment by churik** [comment]
Same issue is reproducible with send / request commands from 1-1 chat
cc @flexsurfer @yenda

**Comment by flexsurfer** [comment]
ill take a look
