### ISSUE TITLE
Disable group chats for v1

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9766]
# Problem

Group chats are quite buggy. Let's minimize problematic experiences in v1 by hiding this option in chat.

## Implementation

Hiding the group chat option from the chat menu should be sufficient.

![image](https://user-images.githubusercontent.com/15470435/71927362-37878700-318d-11ea-8ed2-5f0865963810.png)

## Acceptance Criteria

Users can no longer start or be invited to group chats.

**Comment by cammellos** [comment]
please only do that in release version of the app, so that we can still run tests etc against them

**Comment by jakubgs** [comment]
Wait, isn't the screenshot highlighting the wrong button here?

**Comment by cammellos** [comment]
yes, though the PR disabled the right one
