### ISSUE TITLE
Fix shadow in Wallet on Androind

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9769]
All accounts as well a the "Add account" button should have the same shadow

<img width="906" alt="Screen Shot 2020-01-08 at 13 49 50" src="https://user-images.githubusercontent.com/3115606/71972476-c217c700-321d-11ea-8f62-db2dac9ed249.png">

Shadow properties:
`box-shadow: 0px 2px 16px rgba(0, 9, 26, 0.12);`

Figma
https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=1743%3A303

**Comment by errorists** [comment]
@andmironov with Android it requires an [Elevation](https://material.io/design/environment/elevation.html#elevation-in-material-design) value, regular box shadow doesn't work. so when shadow is used I think we need to provide elevation values next to mockups. I'm guessing the elevation value for cards should be higher than what it is to approximate the box shadow.

**Comment by Ferossgp** [comment]
@andmironov In iOs seems like everything is correct - do you have an idea which elevation size will fit better for android?

**Comment by andmironov** [comment]
I just tried both `3dp` and `2dp`. Both seem off to me but  `2dp` seems just a bit less aggressive

<img width="884" alt="Screen Shot 2020-01-10 at 12 41 55" src="https://user-images.githubusercontent.com/3115606/72142824-9d9b2680-33a6-11ea-9cc5-7bd3e61c4eeb.png">

i'd stick to `2dp` (does it look like on the screenshot above in real life btw?)

**Comment by flexsurfer** [comment]
https://ethercreative.github.io/react-native-shadow-generator/
