### ISSUE TITLE
Add back button to step 2 of Keycard unlock

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9770]
# Bug Report

## Problem
When unlocking a Keycard multiaccount the user can get stuck on step 2 `hold card against the phone` when they've entered the passcode, but do not have immediate access to the Keycard. There is no way to go back to select another multiaccount.

#### Expected behavior
Step 2 has a back button
<img width="794" alt="Screen_Shot_2020-01-08_at_15 42 15" src="https://user-images.githubusercontent.com/35233054/71979251-80871c00-321d-11ea-9431-0e28819018b0.png">

#### Actual behavior
Step 2 does not have a backbutton
![Screenshot_20200108-133921_Status](https://user-images.githubusercontent.com/35233054/71979287-a0b6db00-321d-11ea-9ff8-24547ae4b44b.jpg)

#### Notes
Add back button

#### Acceptance Criteria
Back button let's user go back to step 1

### Reproduction
- Status build with 2 or more multiaccounts
- Select Keycard multiaccount
- Enter passcode
- Don't tap card (imagine you don't have it with you)

### Additional Information
- Status version: 0.14.0 (2020010802)
- Android

**Comment by churik** [comment]
Not relevant with bottom sheet on v1.4
