### ISSUE TITLE
Translation error in Keycard dialog

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9771]
# Bug Report
## Problem
Copy includes a translation error

#### Expected behavior
Dialog only shows: "If you don't want to use Keycard each time to access the app, enable <fingerprint/face ID> sign in." 
{{bio-type-label}} should be replaced with biometric id offered by OS (fingerprint only for Android at the moment.
Correct padding is used: 24px horizontal padding and on children inside the content container.

#### Actual behavior
Dialog shows translation error
![Screenshot!UNITO-UNDERSCORE!20200108-132900!UNITO-UNDERSCORE!Status](https://user-images.githubusercontent.com/35233054/71979598-6437af00-321e-11ea-93e4-94e622e4d22d.jpg)

#### Notes
Issue doesn't seem to be in translation file. Copy there is:
line 72: "biometric-enable-keycard": "If you don't want to use your Keycard each time to access the app, enable {{bio-type-label}} sign in",

#### Acceptance Criteria
Dialog only shows intended copy

### Reproduction

* Select Keycard multiaccount
* Select checkbox 'Don't ask for card to sign in`

### Additional Information
Please check if this modal exists as a component. If so please 

* add a note to apply correct padding when using the component. Correct padding is: 24px horizontal padding and on children inside the content container.
* include a boolean property YES/NO for the padding or a default value like 24 that can be overriden.
* Status version: 0.14.0 (2020010802)
Android

**Comment by andmironov** [comment]
Also, paddings on the left and right are missing

**Comment by churik** [comment]
Not reproducible in 1.4
