### ISSUE TITLE
Update onboarding illustrations to animated versions

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9774]
# Problem
The static illustrations in onboarding can be replaced with animated illustrations we didn't have before.

## Implementation
@errorists can you add the animations here

## Acceptance Criteria
Exact same dimensions as current illustrations, but replaced with animated sourcefiles.

**Comment by errorists** [comment]
[link here](https://www.dropbox.com/sh/uzdrq6sqkclhjsb/AAC_1XPVPCX3y7s4lQXnuQSea?dl=0) 👀 

technical: please don't modify assets in any way. these mp4s should be looped in code as they won't on their own unlike gifs

**Comment by Ferossgp** [comment]
Reverted here https://github.com/status-im/status-react/pull/9869

**Comment by errorists** [comment]
Making a note for posterity: we didn't manage to eliminate issues neither on Android (black box present when loading the video) nor iOS (some iPhone models exhibit black borders around video container). That's why we decided to revert to previous implementation with static images.

**Comment by churik** [comment]
@errorists is it relevant?

**Comment by errorists** [comment]
> @errorists is it relevant?

@churik yes, we had to downgrade to non-animated because bugs but it was always the goal to have them animate. I'd leave it
