### ISSUE TITLE
Add glossary of terms to profile page

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9778]
# Problem

Status introduces a lot of new and unfamiliar terminology. 

## Implementation

Create a basic `Glossary` page under the Profile `Need help?` section.

- `Frequently asked questions`
- `Glossary`
- `Submit a bug`
- `Request a feature`

## Acceptance Criteria

Implement a static text page with the following copy: 

**Account** - Your Status account, accessed by the seed phrase that you create or import during onboarding. A Status account can hold more than one Ethereum address, in addition to the one created during onboarding. We refer to these as additional accounts within the wallet.
**Seed Phrase** - A set of friendly-to-read words, randomly selected from the BIP39 standard list and used to recover or access your Ethereum account on other wallets and devices. Also referred to as a “mnemonic phrase,” “recovery phrase” or “wallet backup” across the crypto ecosystem. Most crypto apps use this same standard to generate accounts.
**Chat Key** - Messages on the Status chat protocol are sent and received using encryption keys. The public chat key is a string of characters you share with others so they can send you messages in Status.
**Chat Name** - Three random words, derived algorithmically from your chat key and used as your default alias in chat. Chat names are completely unique; no other user can have the same three words.
**ENS Name** - Custom alias for your chat key that you can register using the Ethereum Name Service. ENS names are decentralized usernames. 
**Wallet Key** - A 64 character hex address based on the Ethereum standard and beginning with 0x. Public-facing, your wallet key is shared with others when you want to receive funds. Also referred to as an “Ethereum address” or “wallet address.”
**Peer** - A device connected to the Status chat network. Each user can represent one or more peers, depending on their number of devices.
**Mailserver** - A node in the Status network that routes and stores messages, for up to 30 days.

## Notes

Formatting is up to you. We don't have any precedence for a page like this. I'd probably suggest words are bolded, and that we use slightly higher paragraph spacing than normal to separate the entries. cc @errorists

**Comment by errorists** [comment]
designs [here](https://www.figma.com/file/bPS9GrvMr7LnH7vnkmuveQfd/Settings?node-id=1056%3A20184)

I think the only difference I made it alphabetical order, like a dictionary cause those are cool ;)

**Comment by rachelhamlin** [comment]
Amazing, thank you @errorists.
