### ISSUE TITLE
Restoring same account in multiple ways ends in account being inaccessible by any means. 

### ISSUE THREAD

**Issue by corpetty** [status-im/status-react#9779]
# Bug Report

## Problem

Restoring same account in multiple ways ends in account being inaccessible by any means. This is potentially an issue if a user wants to access an account in a lost keycard and tries to restore from the original seed phrase. 

#### Expected behavior

accessing existing keys from seed phrase of an already existing "account" either overwrite current access methods, create identical "account" with different access methods, or add access methods together to the same "account". 

#### Actual behavior

"accounts" are merged into a single one, and no unlock method works.
- password says it is incorrect
- keycard says the account exists and needs to be unlocked, and leads to the password screen which doesn't work. 

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

going through the "access existing keys" of an account that already exists either:
1. says the account exists and asks if you want to change access method
2. creates another "account" that has separate access methods but obviously the same keys

### Reproduction
I used the following procedure to produce this bug
1. going through "access existing keys" flow via the keycard recovery method
2. signing out of "account"
3. going through "access existing keys" flow via seed phrase with the same seed phrase used on keycard (which produces the same keys and derivatives)
4. signing out of "account"
5. attempting to sign in via any method of the single available "account"

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: Jan 8 nightly build `#1387`
- Operating System: Andoid 10
- Phone: Pixel 4

**Comment by yenda** [comment]
@rasom @rachelhamlin should we prevent recovery of an existing account?

**Comment by rachelhamlin** [comment]
@yenda @corpetty I think we should prevent second recovery of an existing account. Edge case, but certainly a problematic one. Can we block the user with an error message that says something like, `You already have an account with this seed phrase. Please log in.`?

Also curious what happens if you uninstall and reinstall in this scenario.

**Comment by churik** [comment]
It is closed - now at attempt to restore the same account suggestion popup with "Unlock" button
