### ISSUE TITLE
Update the "Your keys" screen

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9782]
Currently, this screen is called "Unlock", let's update it. 

- The screen header should be consistent with the rest of the app;
- The list items in the keys list should be consistent with the rest of the app;
- "Access key" button as well as `...` should be consistent with the rest of the sign in flow;
- Let's update the keycard indicator for it to be consistent with the rest of the app;

<img width="1201" alt="Screen Shot 2020-01-09 at 12 46 15" src="https://user-images.githubusercontent.com/3115606/72056695-213d1080-32de-11ea-95de-c41f8c597fe6.png">

Small screens:
<img width="652" alt="Screen Shot 2020-01-09 at 12 49 51" src="https://user-images.githubusercontent.com/3115606/72056977-af18fb80-32de-11ea-9854-f2ec815eef8b.png">

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

**Comment by Ferossgp** [comment]
@andmironov I'm doing just the UI related things in my PR, I think strings should be replaced separately. If I will change only English, other languages will remain outdated as they for sure will be forgotten. 
@rachelhamlin can you plese look into translation strings?

**Comment by rachelhamlin** [comment]
That's true @Ferossgp but it's okay for you to change them. We update the English strings in Lokalise and then people translate them when they can—unfortunately the open source translation process is imperfect at best.

**Comment by Ferossgp** [comment]
![Screenshot 2020-01-29 at 10 59 35](https://user-images.githubusercontent.com/5794620/73337916-7093b280-4286-11ea-8b4e-184740300fca.png)
Updated, for other languages it will show the missing translation, added only English now.
