### ISSUE TITLE
Add a loading indicator and button to username input of start new chat

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9789]
### User Story

As a user I want feedback when I'm entering a ENS username, when it's looking up my public key and when it's resolved correctly, even on a slower connection. 

### Description

The scope of this issue is 
• Add a dedicated 'Start' button next to the input with three states: disabled (greyed out), pending (greyed out with spinner), ready (blue). this is the same button that's used in ENS name registry.
• We show the disabled state whenever you can't proceed forward, correct state when a correct contact code or ENS username is entered, pending when it's resolving the chat key.
• Change the position of the QR Code button to be placed in the right side of Top Bar. Change the icon to the QR Code to be consistent with wallet.
• Change the subtitle informing of invalid entry to `User not found`
• The container in which this subtitle is shown should always be visible, 16px high, so that the subtitle when shown, doesn't push the contact list downward.
• Match the subtitle style with Figma, it's `font size: 13, font weight: 500, line height: 16, black'

### Acceptance Criteria

All of the above points were implemented and are correct with this [Figma design here ](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=7957%3A169)

### Notes

When in doubt with chat key resolution, please get in touch with @flexsurfer for help
thanks! 🙏

**Comment by rachelhamlin** [comment]
This error message that appears the moment I start typing in this field drives me nuts. 

<img src="https://user-images.githubusercontent.com/15470435/73350336-65a94400-42bf-11ea-86b6-678f4688ac52.png" width=250/>

Would be an excellent enhancement if we could eventually populate a list of matching names as the user types. If I recall correctly, reverse lookup may have been a requirement for this.
