### ISSUE TITLE
Custom token disappears after re-login

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9792]
# Bug Report

## Problem

When custom token is added in wallet I can see appropriate amount for my address and can send transaction. But token disappears after re-login.  

#### Expected behavior
Custom token is present after re-login 

#### Actual behavior
Custom token disappears after re-login 
<img width="560" alt="Screenshot 2020-01-10 at 14 41 47" src="https://user-images.githubusercontent.com/8749671/72153714-5a957f00-33b7-11ea-8bb9-f8c3bdf9fea1.png">

### Reproduction

- Open Status and create new account
- Navigate to `Wallet` -> top-right `...` menu button -> `Manage assets` -> `Add custom token`
- Paste `0x6758b7d441a9739b98552b373703d8d3d14f9e62` address (POA ERC20 contract)
- Re-login to account and check the token is still present

### Additional Information
- Status version: Develop 0.14.0 (2020011002)
- Operating System: Android and iOS

**Comment by yenda** [comment]
should be fixed in develop now

**Comment by andremedeiros** [comment]
Confirmed custom tokens remain after signing out / signing back in.
