### ISSUE TITLE
How to resolve same name !command conflict?

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#98]
When 2 DApps are added to a chat session and use the same !command text, ie “!command” == “!command” 

how best should we resolve this?

**Comment by jarradh** [comment]
by referring to the bots name beforehand ie @botname!command

**Comment by rabbit** [comment]
can a name have an exclamation point character in the name?

**Comment by jarradh** [comment]
yes at the moment, but we should disallow it, we're actually talking about switching to `/`, there was a reason for `!` but we all forgot why now.

**Comment by rabbit** [comment]
`/` would make me very happy.

**Comment by jarradh** [comment]
Okay if it will make you happy, we'll change :D

**Comment by Smokyish** [comment]
`/` would be more in line with current general practices on many other platforms.
With that also the pretty common `/me` could be added for commands to reference one's own actions ie. `/me balance` to check account balance etc.
