### ISSUE TITLE
App crash if provide phone number before creating password

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#980]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If send phone number before creating a password then app crashes

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Before password is set: /phone command should work as usual or it should be hidden from a user
#### Actual behavior
[comment]: # (Describe what actually happened.)
If send a valid phone number via /phone command before password is set then app crashes
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
screencast: https://www.screencast.com/t/vqeGQl9DasCL
- Open Status as a new user (use Switch users -> add account)
- In console do not set password, 
- Open commands and tap on "Send Phone Number"
- Provide valid phone number and tap on send icon

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4 and 0.9.5 builds
* Operating System: Android and iOS
#### Logs
0.9.4+ Android: 
[20170704102303-logcat.txt](https://github.com/status-im/status-react/files/904966/20170704102303-logcat.txt)
#### Instabug
https://dashboard.instabug.com/applications/status/beta/bugs/173

**Comment by jarradh** [comment]
It should be hidden from user.
