### ISSUE TITLE
Disable custom picture for non-ens usernames

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#9801]
# Bug Report

## Problem

We want to disable custom pictures for users that don't have an ens username so that it is not possible to impersonate someone by using their identicon as profile picture, which would deceive anyone not paying attention to the random name.

**Comment by rachelhamlin** [comment]
Removed v1 label as it's too impactful a decision to make on the fly. We need to discuss the way we'd store images, disabling photo-path down to protocol, etc.

**Comment by rachelhamlin** [comment]
We can close this, no? It was decided 🤷‍♀️ This makes more sense.

**Comment by yenda** [comment]
@rachelhamlin I'm a bit confused it was decided to soft delete the feature right? There is a PR for that that is going to be merged anytime. By soft delete I mean there is no consequences to the deletion besides not being able to set a profile picture for v1, but the feature can be re-enabled later and though v1 user won't be able to change it without updating, they will see others profile pictures (when contacts)

**Comment by rachelhamlin** [comment]
@yenda what do you mean they will see other user's profile pictures when contacts? 

As of our convo today, my understanding is: 

v1.0 - No custom profile photos whatsoever. 
v1.1 - Custom pic option available as part of ENS, everyone can see your photo along with your ENS name if you choose to upload one.

Is that off?

**Comment by yenda** [comment]
@rachelhamlin I mean that if we restore the feature as-is, it will work just like now even for non updated client because the PR just disabled to possibility to set a profile picture. This just buys us the time to decide how we reintroduce the feature, either by going back to previous behavior, or by removing it completely and replacing it by ens-only public picture, or something else.
