### ISSUE TITLE
Contacts added before sync are not syncing after pairing devices

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9805]
# Bug Report

## Problem

Sometimes contacts added before device pairing don't appear on the second device. 
Reproducibility ~10%, sometimes can be reproducible manually. 
Appeared ~3 weeks ago, can investigate more precisely if it makes sense. 
Reason for failing e2e with reason `Contact is not found in Contacts after initial sync` in PRs and in nightly

#### Expected behavior
contact 1 appeared on Device B

#### Actual behavior
contact list on Device B is empty

### Reproduction

- Device A: Open Status, create account (account A)
- Device A: Add contact 1 to contact list
- Device B: Restore Account A from seed phrase
- Device B: discover Device B to Device A
- Device A: enable Device B 
- Device A: Sync All
- Device B: check the contact list

### Additional Information

- Status Version: nightly 13/01/2020
- Operating System: Android, iOS

#### Logs

Device A (07:03-07:17): https://app.saucelabs.com/tests/415b42b905024c66a5068c83d65bfcb3?auth=9c122258311f559a293e329bda8d9bd8#138

Device B (07:17 -07:41): https://app.saucelabs.com/tests/4dd6f815434e4514bcc06ce6b61049cd?auth=86bb2c8e1c9a0ce3de169230a22e9887#74

**Comment by churik** [comment]
Currently contacts, added right after device pairing are not syncing.
Reproducibility in e2e increased during last 5 days (20-25.03)
Device A (main): 
[logcat (2).log](https://github.com/status-im/status-react/files/4380684/logcat.2.log)
Device B(paired): [logcat (3).log](https://github.com/status-im/status-react/files/4380685/logcat.3.log)

**Comment by churik** [comment]
currentky blocks 1 check in `test_pair_devices_sync_one_to_one_contacts_public_chat`.

**Comment by cammellos** [comment]
This should be fixed (I don't see errors in e2e), feel free to open again if not fixed.

**Comment by churik** [comment]
@cammellos you don't see errors because this check is disabled.
Didn't know it was fixed, then I'll enable check again and will see

**Comment by cammellos** [comment]
:) it might not be fixed, I assumed it was fixed because the tests were not complaining, but worth re-enabling and checking, as we touched that code. If it's still failing, worth fixing.

**Comment by churik** [comment]
will keep an eye on it
