### ISSUE TITLE
Transactions ui-refresh bugs [iOS] [ui-refresh]

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#981]
Simulator - left side, Zeplin - right side:

1. ![screen shot 2017-04-07 at 11 48 44](https://cloud.githubusercontent.com/assets/2364994/24793833/2a34cfbe-1b8c-11e7-93bd-222b9df6d53b.png)

2. ![screen shot 2017-04-07 at 11 49 13](https://cloud.githubusercontent.com/assets/2364994/24793872/4bc0956e-1b8c-11e7-8ef5-26621564b7c0.png)

3. ![screen shot 2017-04-07 at 11 49 50](https://cloud.githubusercontent.com/assets/2364994/24793874/4f9ec3e0-1b8c-11e7-983c-ff174aa432dc.png)

- 1. Wrong style for username in transaction item header
- 1. Wrong positions of elements inside transaction item header 
- 2. "Enter your password to ..." label doesn't exist in design
- 2. "Confirm transaction by ..." tip is absent 
- 2. Underline has wrong style
- 3. "Password" label is absent
- 3. "Wrong password" tip wrong style
- 3. Underline wrong style

**Comment by flexsurfer** [comment]
@rasom @GustavoNunes   i can fix this using text-input-with-label component after we merge https://github.com/status-im/status-react/pull/979

**Comment by rasom** [comment]
@flexsurfer, let's do this

**Comment by GustavoNunes** [comment]
thanks @flexsurfer and @rasom! one update: the first item (the gray recipient name) was wrong in the design, it is been updated to blue (as implemented).
