### ISSUE TITLE
User without ENS name in profile don't see others ENS names

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9819]
# Bug Report

## Problem
Until user doesn't add ENS name in profile, he can't see others ENS names in public chats.
Can be related to https://github.com/status-im/status-react/issues/9815

#### Expected behavior
ENS names are resolved for all users

#### Actual behavior
ENS names are not resolved until you add ENS in profile

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join chat with messages, sent from users with ENS name (i.e. #status)
- Check usernames on messages

### Additional Information

- Status version: nightly 14/01/2019
- Operating System: Android, iOS

cc @rachelhamlin

**Comment by flexsurfer** [comment]
@churik can't reproduce this, i only know that you have to receive 3 or more messages to resolve an ens name, receive by your node, not from mailserver 
This should be fixed here https://github.com/status-im/status-go/issues/1730

**Comment by churik** [comment]
On current nightly (from 15.01.2019) - created new multiaccount, joined #status chat, fetched all history and see only random names.
Is it a consequence of the necessity to receive 3 or more messages I suppose (fetched history is not counted)? 
If yes, let's wait for merging fix on go side and I'll recheck it once more.

**Comment by flexsurfer** [comment]
hm looks like we resolve names from mailserver, but i've never seen resolved names from mailserver, probably  status-im/status-go#1730 might fix this as well

**Comment by churik** [comment]
Can't reproduce after merging https://github.com/status-im/status-react/pull/9836
