### ISSUE TITLE
No navigation to Tozemoon sticker pack when tap on the sticker in the chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9821]
# Bug Report

## Problem

Tapping on Tozemoon sticker from inside chat view there is no navigation to it's pack happens for purchase (or adding if already purchased). 
<img width="356" alt="Screenshot 2020-01-14 at 12 19 50" src="https://user-images.githubusercontent.com/8749671/72335976-8a4eca80-36c8-11ea-9f39-c78303b40c62.png">

All fine with `Status Cat` sticker though.

#### Expected behavior

Navigation to `Tozemoon` sticker pack happens when tap on tozemoon sticker in the chat
#### Actual behavior

No navigation to `Tozemoon` sticker pack happens when tap on tozemoon sticker in the chat

### Reproduction

- Open Status and create  new account
- Join `#status` public chat (or any public chat where `Tozemoon` stickers exist
- Tap on the tozemoon sticker

### Additional Information
- Status version: develop 0.14.0 (2020011402)
- Operating System: Android and iOS

**Comment by Serhy** [comment]
cc @flexsurfer @rachelhamlin @andremedeiros 
included in V1

**Comment by flexsurfer** [comment]
should be fixed in status-go, packid = 0 should be in the message content

**Comment by cammellos** [comment]
This should be now fixed in develop, feel free to close if that's the case.

**Comment by Serhy** [comment]
Confirmed with iOS and Android that it fixed in latest nightly build
