### ISSUE TITLE
Latest 24h messages are not visible in public chat I join it after contact request received

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9824]
# Bug Report

## Problem

If I receive contact request (not even a message - only contact request) then when I join to public chat having messages for the last 24h - those messages in publics are not shown in chat view. However messages are received (just not shown) because: 
a) I see the latest message (preview) in chat item on Chats main view and 
b) if I re-login I immediately see counter of unread messages in those public chats (not sequentially increasing) and messages itself when I open the public chat

#### Expected behavior

Messages are visible in public chat 

#### Actual behavior

<img width="717" alt="Screenshot 2020-01-14 at 14 24 13" src="https://user-images.githubusercontent.com/8749671/72344294-91320900-36d9-11ea-8cff-00de6a73246a.png">

### Reproduction

- Open Status and create new account (UserA)
- With different user (UserB) send a contact request to UserA (I did by `Scan QR code`)
- UserB taps `Add to contacts` from 1-1 chat created with UserA 
- UserA joins public chat having history in the last 24h (e.g. `#status` )

### Additional Information

- Status version: develop `0.14.0 (2020011402)`
- Operating System: Android and iOS

**Comment by Serhy** [comment]
Not reproducible with 1-1 chats (I receive offline history fine in different 1-1 chats after contact request)

**Comment by cammellos** [comment]
@Serhy I have tried to replicate but with no luck, following exactly the same steps. Can you consistently replicate or it only happens sometimes?

Also if you can, could you check if you can replicate here ? https://github.com/status-im/status-react/pull/9787 ( I could not )

**Comment by Serhy** [comment]
Yes, @cammellos reproducible for me all the time on iOS and Android (v8.1 and v9 confirmed) 
And reproducible with latest builds in https://github.com/status-im/status-react/pull/9787 (https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200114-125748-683cb6-pr-universal.apk and https://webapp.diawi.com/install/KLfEJS

(Sorry I've skipped there in description a step to switch to `eth.staging`) 

So create an account -> this account receives contacts request (`Add to contacts`: you may send messages but it doesn't matter for issue) -> then join public chats `#status` / `#status2`(i've posted messages there) and verify messages are in chat view.

**Comment by Serhy** [comment]
Looking at logcat now..

**Comment by Serhy** [comment]
Of course while I was getting logcat I got the case when in `failed to reproduce all the time` :) (well not completely and before I seen it reproducible 10 of 10 times)
So firstly I created and account and switched to `eth.staging` fleet. Then starting from this point 
[logcat_empty_public.txt](https://github.com/status-im/status-react/files/4059658/logcat_empty_public.txt)
 
I opened QR code of this user and with different device scanned it and from 1-1 chat tapped `Add to contacts`
Then I opened `#status` then `#chitchat` then `#status2`. But appeared with `#status` but rest of chats (#chitchat and status2) were fine and it's visible the messages are there decoded (search for `Monkey`)

Log snippet on `#status` with no messages in chat view: 
``` 
01-14 16:32:28.726 16928 16984 E GoLog   : ERROR[01-14|14:32:28.725] received unexpected data in the the confirmation event namespace=EnvelopesMonitor batch=0x624802d0ef79014be6f945915fb0cd3fdf74ad3d477ffec09c2c0e7caa4370ed
01-14 16:32:28.726 16928 17234 D StatusModule: Signal event: {"type":"envelope.sent","event":{"ids":null,"hash":"0x0000000000000000000000000000000000000000000000000000000000000000","message":""}}
01-14 16:32:28.743 16928 16971 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
01-14 16:32:28.762 16928 16971 D ReactNativeJS: DEBUG [status-im.events:599] - :event-str {"type":"envelope.sent","event":{"ids":null,"hash":"0x0000000000000000000000000000000000000000000000000000000000000000","message":""}}
01-14 16:32:29.170 16928 16982 E GoLog   : INFO [01-14|14:32:29.169] recovered installation                   namespace=Protocol site=recoverInstallationsFromBundle installation-id=2078265a-2583-5f01-9cb2-3666dda93d81

```

**Comment by cammellos** [comment]
@Serhy this should be fixed, could you verify please? Thanks!

**Comment by Serhy** [comment]
Thanks @cammellos ! 
This is fixed. Can't reproduce on Android and iOS with Release1.2.1 / nightly build.
Closing this one.
