### ISSUE TITLE
App crash if enter non-existing command (e.g. /aaaa) [chat-ui]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#983]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sending non-existing command causes app to crash

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
non-existing commands sent in chat are treated as a text. App does not crash
#### Actual behavior
[comment]: # (Describe what actually happened.)
App crashes if send non-existing command, e.g. /aaaa
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- Open Console or 1-1 chat
- type /aaaa and send it.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 
* Android 0.9.4-39-g4fd2e94+  bug/password-input (Android) http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-4fd2e9.apk
[comment]: # (Android or iOS.)
* iOS: 0.9.5d39
* Operating System: Android and iOS

#### Logs

[20170704151431-logcat.txt](https://github.com/status-im/status-react/files/905645/20170704151431-logcat.txt)

**Comment by alwx** [comment]
This issue has been fixed here: https://github.com/status-im/status-react/pull/982
