### ISSUE TITLE
Make sure that everywhere the asset image is done properly

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9832]
When discussing this pull request https://github.com/status-im/status-react/pull/9772 we noticed that the asset image is not done properly and consistently across the app. 

For instance, on the `Send transaction` bottom sheet the asset image has no border, although on the `Wallet` main screen it has.

Any asset image across the app should follow these rules:
- It should be a circle with a square .png image inside;
- It should have a #000000 1px **inner border** (important, not an outer border, most likely means that there should be nested objects) with 10% opacity;

Here's a more visual explanation of why that matters:

<img width="843" alt="Screen Shot 2020-01-15 at 15 43 01" src="https://user-images.githubusercontent.com/3115606/72434865-babc6480-37ad-11ea-9b3e-ba22cdd43e6a.png">

**Comment by emizzle** [comment]
@andmironov -- I can't seem to replicate this *working* as expected anywhere. Could you send a screenshot of a token where this *works*?

**Comment by emizzle** [comment]
Closed due to new icon set -- see https://github.com/status-im/status-react/pull/10436#issuecomment-620495157.
