### ISSUE TITLE
Update the ETH logo across the app

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9833]
While discussing this https://github.com/status-im/status-react/pull/9772 pull request we decided that it would be better to update the ETH logo to have a black background, to stand out a bit more in the app.

<img width="936" alt="Screen Shot 2020-01-15 at 15 48 14" src="https://user-images.githubusercontent.com/3115606/72435142-74b3d080-37ae-11ea-8e68-3b1da0aa7f0a.png">

I've prepared a png file (make sure to finish this issue first https://github.com/status-im/status-react/issues/9832) 

Here's the `eth.logo.png` (consider compressing before using)  https://www.dropbox.com/s/at16848wok0iqev/eth-logo.zip?dl=0

**Comment by errorists** [comment]
@andmironov looks dope! 🖤  could I ask you to update the [ETH user pick](https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=16%3A12) in our component lib? 🙏
