### ISSUE TITLE
Multiaccount is not loaded after relogin if change account in browser

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9835]
# Bug Report

## Problem
Multiaccount is not loaded after relogin after changing account in DApps

#### Expected behavior
multiaccount is loaded

#### Actual behavior
multiaccount is not loaded

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create multiaccount
- Go to wallet and add account 2
- Go to browser > switch to account 2
- Relogin

### Additional Information

- Status version: nightly 16/01/2020
- Operating System: Android, iOS

**Comment by flexsurfer** [comment]
fixed in latest nightly
