### ISSUE TITLE
No ENS name and custom userpicture on login screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9840]
# Bug Report

## Problem
ENS name and custom userpicture settings are not shown on login screen.

#### Expected behavior
ENS name + custom avatar

#### Actual behavior
![photo_2020-01-16 15 38 45 jpeg 2020-01-16 15-39-12](https://user-images.githubusercontent.com/4557972/72534043-75179e80-3876-11ea-8814-8f852768beaf.png)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status, create new multiaccount
- Set ENS name
- Change user picture
- Log out

### Additional Information
- Status version: nightly 16/01/2020
- Operating System: Android, iOS

**Comment by rachelhamlin** [comment]
I agree this would be more user friendly—though iirc we may have left it this way intentionally to be more privacy preserving in extreme scenarios. e.g. your phone gets inspected at the border, there is no proof that this Status account belongs to you. Right @hesterbruikman?

**Comment by churik** [comment]
can be closed due to redesign
