### ISSUE TITLE
Wrap bottom sheet component around the total height of its nested elements

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#9848]
# Problem

Our bottom sheet component requires us to specify its height. Which is not optimal and forces us to create scrollable layouts where we can't exactly tell how large the nested layout is, see Account Selection in Browser.

## Implementation

Let's figure out a way to calculate the height of the bottom sheet based on the size of its nested content. So regardless of what we place, it will always wrap its size based on that. 

<img width="375" alt="fig1" src="https://user-images.githubusercontent.com/4932774/72619017-a8bcfc00-393c-11ea-9a81-d3b5baba782f.png">

And if the content grows too large - and by that i mean more than the available screen height - only then we overflow the content inside so it scrolls. 

<img width="375" alt="fig 2" src="https://user-images.githubusercontent.com/4932774/72619242-27199e00-393d-11ea-9046-684d1f02a045.png">

## Acceptance Criteria

Bottom sheet calculates its height correctly based on the height of nested elements inside it. All currently used bottom sheets start to use this behaviour, hardcoded scroll is removed where used.

## Notes

This can work in tandem with this issue https://github.com/status-im/status-react/issues/9846
Thanks!

**Comment by Ferossgp** [comment]
To avoid scroll view and pan responder issues I would suggest to look how it is handled here: https://github.com/react-native-community/react-native-modal/blob/master/src/modal.tsx#L301 or we can also use this library in future to wrap bottom sheet in it.
