### ISSUE TITLE
'Confirmed' status in 1-1 chat pending transaction as soon as account re-logins

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9851]
# Bug Report

## Problem

Disregard the sent transaction in 1-1 chat with 'Send' command which still in 'Pending...' state (in network and so in wallet), - after user re-opens the app the `Outgoing transaction` gets `Confirmed!` status. 
If to tap on such TX nothing happens, but it because there is no TX in history yet at all so that's expected and a part of another issue.
This issue is dedicated to align transaction `Outgoing transaction` status send in 1-1 chat to it's actual status: if TX is not in TX history - we keep showing 'Pending...' status

#### Expected behavior

Outgoing transaction keep staying with 'Pending...' status in 1-1 chat after account relogin if it's 'Pending...' in network
#### Actual behavior

Outgoing transaction gets 'Confirmed... ' status in 1-1 chat after account relogin always

Video: https://drive.google.com/file/d/1oFzAqlt-47rRII4yNrqJGqOqqamzno6E/view?usp=sharing

### Reproduction
- Open Status and recover an account with funds (UserA)
- Add UserB in contacts and open 1-1 chat with this contact
- UserA sends 'Send transaction' with valid amount of ETH/tokens
- UserB taps `Accept and share address`
- UserA signs transaction in 1-1 chat
- UserA re-logins to account and checks transaction status in 1-1 chat

### Additional Information
- Status version: develop 0.14.0 (2020011702)
- Operating System: Android and iOS

**Comment by Serhy** [comment]
Not a blocker for V1 IMO but rather nice to have.

**Comment by flexsurfer** [comment]
looks like a blocker for me @rachelhamlin , because it might confuse user that tx is confirmed but it isn't

**Comment by flexsurfer** [comment]
@Serhy is it only outgoing or incoming as well ?

**Comment by Serhy** [comment]
No, only outgoing, @flexsurfer 
Incoming kept in "Shared '[account_name]'" until transaction gets confirmations and appears in 'Wallet'

**Comment by Serhy** [comment]
Only outgoing, @flexsurfer 
For incoming messages in 1-1 chat - they stay in "Shared [account_name]" until transaction is confirmed.

**Comment by cammellos** [comment]
This is due to the fact that pending transaction originating in the app are not stored https://github.com/status-im/status-react/issues/9976 , one way to fix this is to at least store in the database the pending transactions that are created within the app.

**Comment by cammellos** [comment]
We can probably fix in an easier way, by assuming that if the transaction is not in the history is pending, as my understanding is that failed transactions will show in the history.
