### ISSUE TITLE
Searchbar appears after adding first chat

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#9855]
# Problem

Searchbar appears when first chat added. But user shound't see it until he intentionally open it.

Steps to reproduce
- create account, don't close "Chat and transact privately with friends"
- tap on + > Join public chat > 
- get back to chat list 
- Search field is opened (not focused).
So it appears without pull-to-refresh gesture.

Introduced in #9743

## Acceptance Criteria
search field not visible on screen after beforementioned steps

**Comment by iurimatias** [comment]
@vkjr can this issue be closed after #9743 ?

**Comment by vkjr** [comment]
@iurimatias, #9743 didn't close this issue, it started it :)
