### ISSUE TITLE
No messages are received by user if they were sent to his ENS name before setting in Profile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9857]
# Bug Report

## Problem
If start chat with existing ENS name, which is already associated with chat key, but user didn't set ENS name in profile yet - this user will not receive messages. 

#### Expected behavior
can see messages

#### Actual behavior
no messages;
messages are received only if user with ENS manually start chat with sender

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- User A: restore account with ENS name, but don't set it in Profile
- User B: start chat with ENS name of User A, send some messages

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nigthly 20/01/2020
- Operating System: Android, iOS

**Comment by churik** [comment]
can be release blocker for v1

cc @rachelhamlin @cammellos

**Comment by Serhy** [comment]
I received messages sent to such user, but since 3-4 minutes later on one account, within ~15 minutes later on another attempt, and since ~7 minutes with third account. 
So messages are received but just not instantly.

If I add user via public key message received instantly

**Comment by cammellos** [comment]
This is possibly due to multiple devices and recovering, it takes some time before other users see the device, until then messages won't be received (same if there are many devices/installations around, more than 3,). they might, but we can make no guarantees.

I can take a look at whether is an ENS specific issue, but unlikely.

Could you add information about the account you used for the tests? (Do you recover it often? ,how many times a day? do you have other devices? when messages where not sent both devices where online?)

**Comment by Serhy** [comment]
Yea, in my case I recovered each of account more than 3 times for sure during the day. 
Checking with newly created account who just bought ENS.

**Comment by Serhy** [comment]
Well, there is no way to have no ENS assigned and that it would be first account creation (ENS assigns right after in purchased)
So I did with RC:
1) Created new account
2) Sent 10 SNT and enough ETH to buy ENS name
3) Created ENS name
4) Flushed the data of Status app
5) Recovered this account on the same device
6) WIth different accounts from another devices having RC build: add this user by ENS name from `Start 1-1 chat`
7) Send messages 

Actual result: messages received in 4-5 minutes (with some delay between messages receiving). Ordering is right, but it's visible (by timestamps) that messages received with delay

<img width="518" alt="Screenshot 2020-01-21 at 11 42 08" src="https://user-images.githubusercontent.com/8749671/72793416-16ba3980-3c43-11ea-944b-44dce15d6b53.png">

**Comment by Serhy** [comment]
It's not great, but IMO it should not block release. Would block if messages were lost forever but they received eventually.

**Comment by cammellos** [comment]
could you try the same without adding by ens? add by public key, but go
through the same steps.
Thanks!

**Comment by Serhy** [comment]
Yea, correct. 
There is a same issue if I add user via public key following above steps (including buying ENS)

So related to how many times account recovered. 
After 1-1 chat appeared on receiver side messages coming fine and even if to delete 1-1 chat (user is not added in contacts by message Recever) and message sender sends message again the message received right away.

**Comment by rachelhamlin** [comment]
Wait, so @Serhy, if you recover your account several times and I send a message to your pubkey - you won't receive it? Or they are received on a 4-5 minute delay (and same if I send to your ENS that is not yet set up in your profile)?

**Comment by cammellos** [comment]
this is expected, recovering the account might have a delay on receiving  1-to-1 messages, as peers need to be notified of the new device, pairing helps speeding up the process, but until there some permanent form of storage (swarm etc), this can only be mitigated but not solved

**Comment by rachelhamlin** [comment]
Okay, cool. I'm going to backlog this then.

**Comment by churik** [comment]
also affects group chats (as mentioned in https://github.com/status-im/status-react/issues/8416)
