### ISSUE TITLE
DApp commands are not added to Status

### ISSUE THREAD

**Issue by coyotespike** [status-im/status-react#987]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to add `commands.js` so that I can create custom commands.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Even when `commands.js` is publicly available, the command does not add to Status.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

After adding `truffle-box-status`, with a command defined and available at `http://localhost:3000/commands.js`, the command should be available within the Truffle App.

#### Actual behavior
[comment]: # (Describe what actually happened.)

Only `browse` is available.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add `truffle-box-status`, with a simple command in `public/commands.js`
- Click on the Truffle box. No command is available.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- Probably a new `http-get` that works with `localhost`

### Additional Information
* Status version: running off branch `develop`
[comment]: # (Android or iOS.)
* Operating System: Android

**Comment by coyotespike** [comment]
`utils/utils/http-get` is used in `commands/loading/fetch-commands!` to try to load the DApp's `commands.js`. 

This doesn't work in local development, or when the file is hosted like at "https://www.dropbox.com/s/gazcf825lv4ygf6/commands.js?raw=1"

I tested with `slurp`. It works with the DropBox location but does not work for resources served via `localhost`.
```
    (and dapp? dapp-url)
    (dispatch [::validate-hash whisper-identity (slurp "https://www.dropbox.com/s/gazcf825lv4ygf6/commands.js?raw=1")])
```

**Comment by rasom** [comment]
This `slurp` is macros, we can't use it. Did you run application on simulator or on real device?

**Comment by coyotespike** [comment]
I grabbed the macro from utils/slurp, since it worked for an external file
I'm surprised it does not work for localhost. I ran on Genymotion. Maybe it
works on a real device? But many devs will want to use a simulator so it'd
be good to get it working there too.

**Comment by rasom** [comment]
If you are using Genymotion you have to `reverse` tcp connection from you computer to allow Android application to access some local servet, like if you are running server on localhost:xxxx you have to run:
`adb -s 5a469bf5 reverse tcp:xxxx tcp:xxxx`

As slurp is a macro it expands in compile time, hence if you are using it like `(slurp "string_url")` it works fine, but if you will run it as `(slurp symbol-with-url)` this will not work correctly in the runtime.

**Comment by coyotespike** [comment]
I run
```
adb reverse tcp:8081 tcp:8081
adb reverse tcp:3449 tcp:3449
adb forward tcp:5561 tcp:5561
```
and for some reason `8082` is usually reversed too.

**Comment by rasom** [comment]
@coyotespike, if you want to make `http://localhost:3000/commands.js` available from Genymotion you have to run
`adb reverse tcp:3000 tcp:3000`

**Comment by coyotespike** [comment]
@rasom Yes, that's what I have done. This solves a [truffle-box-status issue](https://github.com/status-im/truffle-box-status/issues/1) where the DApp opened at the wrong URL on Android. So that's helpful. But the command still doesn't load. 

This test in `fetch-commands!` returns false. 
```
                (fn [response]
                  (and
                   (string? (.text response))
                   (when-let [content-type (.. response -headers (get "Content-Type"))]
                     (s/includes? "application/javascript" content-type))))
```
- If I skip that test by forcing it to return true, `parse-jail` redboxes saying expects string not object

**Comment by rasom** [comment]
@coyotespike  this issue is fixed in `epic/chat-api`
