### ISSUE TITLE
Respond to FaceID failure callback

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9871]
# Problem
When FaceID fails, the user is directed to the password unlock screen with no opportunity to try again.

## Implementation
Respond to callback of FaceID failure

- The Face ID check should not happen on a blank background like it is right now, it should happen on top of the pin pad;
- A failed Face ID should allow to enter the passcode instead or re-trigger the Face ID  check
here's where it's a password, not passcode

<img width="1399" alt="Screen Shot 2020-01-22 at 17 43 19" src="https://user-images.githubusercontent.com/3115606/72903697-c2947f80-3d3e-11ea-8e64-ccc682988c80.png">

## Acceptance Criteria
FaceID behavior is implemented according to design in [Figma](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=5038%3A214)

## Notes
Investigate if the behavior can/should be the same for fingerprint

## Future Steps

- Create multiaccount
- Enable FaceID
- Close app (don't sign out, settings will be reset until this issue is resolved: https://github.com/status-im/status-react/issues/9763#issuecomment-573052216
- Open with FaceID, hold phone away from face - make FaceID fail
- Tap Try FaceID again

**Comment by hesterbruikman** [comment]
cc @andmironov @errorists @andremedeiros @Ferossgp 

Here's the issue discussed today to allow retry in case FaceID failed. Please check for accuracy and leave any comments.

**Comment by errorists** [comment]
does that mean we're implementing pin codes next to passwords like in the design?

**Comment by hesterbruikman** [comment]
I should have specified. This is adding an option to trigger FaceID after failure callback only for now. @andremedeiros will check back later on passcode. This depends on how we handle the key encryption at the moment.

**Comment by errorists** [comment]
@hesterbruikman thanks. dunno, don't you feel the issue could be better formatted to actually describe what's expected? :)

• add a biometric icon (faceId/touchID) next to password input to allow retries of failed or cancelled checks.
• biometric check should happen on the same view you're using to unlock your phone

and remove the pincode screenshot, since that's not in scope

**Comment by hesterbruikman** [comment]
Can definitely be more clear. Thanks for adding that summary. On the passcode, removed the screenshot. Was thinking of Keycard, but that's actually not relevant on iOS.
