### ISSUE TITLE
No connection to mailservers on eth.prod

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9877]
# Bug Report

## Problem

Mailservers from `eth.prod`  fail to connect. On iOS when tapping on `An error occured while fetching history` the `Mailserver request error` pop-up appears.
Same with RC.

Switching to eth.staging make things working fine

#### Expected behavior

Can connect to mailservers and fetch history

#### Actual behavior

Can not connect to mailserver and no history fetched

<img width="286" alt="Screenshot 2020-01-22 at 11 44 28" src="https://user-images.githubusercontent.com/8749671/72883203-919b5700-3d0c-11ea-9b79-1c12980e994b.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
- Install Status develop build 
- Open Status and create new account
- Join public chat

### Additional Information

- Status version: develop 2020012208 (nightly 22nd of January)
- Operating System: Android and iOS

#### Logs

```
01-22 11:48:22.932   970   970 D ScrollView:  onsize change changed 
01-22 11:48:22.932   970   970 D ScrollView:  onsize change changed 
01-22 11:48:22.934   970   970 D ViewRootImpl@d8a9faf[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
01-22 11:48:22.951   970   970 D ViewRootImpl@d8a9faf[MainActivity]: MSG_RESIZED: frame=Rect(27, 744 - 1053, 1403) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-22 11:48:22.974   970   970 D ViewRootImpl@f9e1fbf[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
01-22 11:48:22.974   970   970 D InputMethodManager: prepareNavigationBarInfo() DecorView@b6a723a[MainActivity]
01-22 11:48:22.974   970   970 D InputMethodManager: getNavigationBarColor() -855310
01-22 11:48:24.012   970  1021 E GoLog   : ERROR[01-22|09:48:24.011] failed to dowload transfers using concurrent downloader error=nil
01-22 11:48:24.012   970  1576 E GoLog   : ERROR[01-22|09:48:24.012] failed to dowload transfers using concurrent downloader error=nil
01-22 11:48:24.014   970  1576 E GoLog   : ERROR[01-22|09:48:24.011] failed to dowload transfers using concurrent downloader error=nil

```

**Comment by adambabik** [comment]
The problem is because of this change: https://github.com/status-im/status-go/pull/1805/files#diff-f422bb8b8162ca6a8f7fbff615267548R382. Mailserver (or the app) requiers `Topics` field while the other side does not understand it and deserialization breaks producing garbage as you see in the alert.

We need to align status-go used on the mailservers and in the app.

**Comment by Serhy** [comment]
Works now. Closing the issue
