### ISSUE TITLE
App shows 'buy' for stickerpack user owns when pressing on sticker in chat (Infura - related?)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9886]
# Bug Report

## Problem
App requires to buy stickerpack that was bought previously from "Tozemoon" sticker pack opened by tap on Tozemoon's sticker from inside chat view. 
NOTE: It's all fine when I open sticker market place from message input sticker icon. And also if I done that - there is no issue. Until I re-login to account.

So for me now, with RC4 - there are no problems when I open Tozemoon sticker pack from message input sticker icon
But issue is when I logged in to account (with bought but not installed Tozemoon) -> open chat with Tozemoon sticker -> tap tozemoon sticker from chat view 

#### Expected behavior
can install stickerpack

#### Actual behavior
![photo_2020-01-22 15 06 35](https://user-images.githubusercontent.com/4557972/72900790-cfa67400-3d28-11ea-868a-d0ad1a34c867.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Restore account from seedphrase that bought 'TOZEMOON' before
- Join public chat with tozemoon sticker sent (#tozemoon)
- Tap upon Tozemoon sticker
**Actual result:** No Install button available but 20 SNT instead

### Additional Information

- Status version: nightly 22/01/2020
- Operating System: Android, iOS

### Logs
[stick-log.log](https://github.com/status-im/status-react/files/4097699/stick-log.log)

**Comment by churik** [comment]
cc @flexsurfer @rachelhamlin

**Comment by cryptounknown** [comment]
This did not happen to me. It worked as expected on my end. I had purchased the sticker pack on a nightly build a few weeks ago and it restored great on the V1 RC.

**Comment by rachelhamlin** [comment]
Other v1 issues that may be related to Infura:
- ENS name availability very slow to load (reported 2x) 
- Sticker packs slow to load (reported 1x)

**Comment by Serhy** [comment]
I'm not sure if it's infura or not (for me there is nothing like Infura-related)
But reproduced for me now in RC3, I just want to specify scenario:

**Preconditions:**
- Tozemoon sticker exists in public chat (e.g. of chat `#tozemoon

**Reproduction**:
- Open Status
- Restore account from seedphrase that bought 'TOZEMOON' before
- Join public chat with tozemoon sticker sent (`#tozemoon`)
- Tap upon Tozemoon sticker
**Actual result**: No Install button available but `20` SNT instead

However:
**Steps when NOT reproduced**:
- Open Status
- Restore account from seedphrase that bought 'TOZEMOON' before
- Join public chat with tozemoon sticker sent (or  any chat basically)
- Tap upon sticker icon in message input
- Find Tozemoon sticker to install
**Actual result = Expected result**: I can Install sticker pack fine

**Comment by rachelhamlin** [comment]
It's okay for me on iOS.

On RC4 iOS, I have the Install button when I click on a Tozemoon sticker in chat.
On RC4 Android, I am shown the price in SNT.

**Comment by Serhy** [comment]
On RC4 I have this issue in both iOS (13.3) and Androids 

One note: If you open sticker market place from message input at least once then all fine when opening  tozemoon sticker pack from chat, but it's until you re-login.
So issue (in RC4 for sure for me on iOS and Android 9 and Android 8) is that "App requires to buy stickerpack that was bought previously in the tozemoon sticker pack opened by tap on Tozemoon sticker from inside chat view"
Updated description.
