### ISSUE TITLE
Wallet with no text or 0 WEI and "Open wallet" button is not responding

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#989]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: opened Wallet and there is no text just empty box. Prior to this Wallet could be opened when there are no transactions done. After 2-3 transactions Wallet starts to show 0 WEI instead of real balance with some ETH. If continue to close/open Wallet then it starts showing just empty box with no text.

After some transactions are done 0 WEI is shown as balance (syncing is complete)
![wallet 0](https://cloud.githubusercontent.com/assets/6584810/26024672/8e9f6160-37d6-11e7-8de9-a42affc203a9.jpg)

After several attempts (2-3) to open Wallet from Contacts it shows just empty box:
![empty wallet](https://cloud.githubusercontent.com/assets/6584810/24900583/9fe9a84a-1ea4-11e7-936b-055226208eaa.jpg)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Wallet is shown as usual (text, sum, link to open it)
#### Actual behavior
[comment]: # (Describe what actually happened.)
Empty box with no text is shown, so user cant get into the Wallet
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
screencast1: https://www.screencast.com/t/vIC3RAOB
screencast2: https://drive.google.com/file/d/0Bz3t9zSg1wb7eThlRDZQUW9wTDQ/view?usp=sharing
screencast3 (wallet with text but tap does not open Wallet): https://drive.google.com/file/d/0Bz3t9zSg1wb7LTNqNnRRbVgtQTQ/view?usp=sharing
Not sure how it happened. Installed new build on device where 0.9.4 was removed. Was using app for ~20 minutes, Than it was closed and after I opened it again there is grey screen shown first instead of Wallet and later this empty box.

Note: after reopening same issue. It looks like I can't access the Wallet anymore
Sometimes Wallet shows text but if tap on Open Wallet then nothing happens

After re-installing the app I can reproduce issue after these steps:
- Open app and create a password
- send faucet request 
- Wait till wallet is updated and shows 1 ETH
- Add another contact (Android device) 
- In 1-1 chat request from this contact 0.01 ETH and receive it 
- Open Wallet from Chats and from Contacts. At first, Wallet is grey screen. If re-open app and open Wallet from Contacts then it becomes screen with no text. If Wallet shows some text, try to tap on "Open Wallet" - in my case nothing happens after tap

Address: 199ea0a8682bb913d7ef782aebf1af38f17d3f83

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.5d15 develop, 0.9.6 and 0.9.7
* Operating System: iOS 10.3.1
it does not happen on Android
#### Logs

* Log1 for screencast1: [20171104104107-consolelog.txt](https://github.com/status-im/status-react/files/912624/20171104104107-consolelog.txt)
* Log2 for screencast2: 
[20171104105852-consolelog.txt](https://github.com/status-im/status-react/files/912664/20171104105852-consolelog.txt)
* Log3 for screencast3: 
[20171104111641-consolelog.txt](https://github.com/status-im/status-react/files/912710/20171104111641-consolelog.txt)

### Instabug
* 0.9.6 iOS 10.3.1 iPhone SE https://dashboard.instabug.com/applications/status/beta/bugs/224
* 0.9.7 iOS 10.3.2 iPhone 7 https://dashboard.instabug.com/applications/status/beta/bugs/295
* 0.9.8 10.3.2 iPhone 6s https://dashboard.instabug.com/applications/status/beta/bugs/318
* 0.9.9 https://dashboard.instabug.com/applications/status/beta/bugs/346

**Comment by annadanchenko** [comment]
Instabug:
* iphone6s, iOS 10.3.1 https://dashboard.instabug.com/applications/status/beta/bugs/186

**Comment by annadanchenko** [comment]
Issue can be reproduced on iphone simulator for Iphone 7 plus, iOS 10.3 with development build

**Comment by sla-shi** [comment]
Closing this per @roma suggestion - not relevant since we @GustavoNunes is working on another version of wallet atm.

**Comment by sla-shi** [comment]
Reopening to keep it on the radar, and added won't fix label.

**Comment by romaroma** [comment]
When a new version of wallet will be available? Is there any way to fix wallet now? Probably reinstall the app? Or just wait and prey? )

**Comment by annadanchenko** [comment]
@romaroma As a workaround outside of the app: open https://ropsten.etherscan.io/ and search by the address (available on Profile screen) to see balance and transactions. More ugly workaround inside the app: open any 1-1 chat, e.g. tap on Jarrad in Contacts and try to send some insane big amount (e.g. 10000) - an error message will be shown with a balance at the end (like Insufficient funds .... balance X ETH). For this specific issue re-installing the app usually does not help.

**Comment by sla-shi** [comment]
Not applicable with the new wallet implementation.
