### ISSUE TITLE
Empty 1-1 chat if opened from public chat

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9900]
# Bug Report

## Problem

Create 1-1 chat , send messages, close the app, reopen the app, do not open 1-1, open public chat, find this contact, press on it, press send message, empty chat is opened

#### Expected behavior

All messages in 1-1 sould be shown

#### Actual behavior

1-1 chat is empty

**Comment by churik** [comment]
can be related to https://github.com/status-im/status-react/issues/9444

**Comment by rachelhamlin** [comment]
Yuck.

**Comment by churik** [comment]
https://github.com/status-im/status-react/issues/9444 is the same, it is one more scenario.
Thanks @flexsurfer 
If you tap back -> open 1-1 chat from list, you will see normal history.
