### ISSUE TITLE
ENS name reverted to previous value after fetching messages that were sent with previous name

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9905]
# Bug Report

## Problem

After someone fetches older messages prior to change to ENS name, ENS name value will be reverted to previous value.

#### Expected behavior
User B: ENS name value for User A mathes actual (Y)

#### Actual behavior
ENS name is shown as previous value

### Reproduction

- User A: set ENS username X, write message to `chat 1` and `chat 2`
- User B: join `chat 1`
- User A: change username to Y, send message to `chat 1`
- User B: check that name in  `chat 1` changed to Y
- User B: join `chat 2`

### Additional Information

- Status version: nightly 24/01/2020
- Operating System: Android, iOS

**Comment by churik** [comment]
@rachelhamlin not sure that it is actually V1, but I suppose that due to this issue I saw "blinking" ENS name in status chat yesterday.

**Comment by rachelhamlin** [comment]
Why is ENS the bane of my existence. It only shows as the old name for the user who fetched older messages, I assume? Not a v1 blocker, but if you can fix it easily @cammellos, then please 🙏

**Comment by cammellos** [comment]
@churik this should be fixed, could you verify? thanks!

**Comment by churik** [comment]
Not relevant in 1.4
