### ISSUE TITLE
ENS names are not resolved in public chat until you start chat directly with ENS name

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9906]
# Bug Report

## Problem

Continuation of https://github.com/status-im/status-react/issues/9819 - currently ENS names in public chats are not resolved until you manually start chat with participant of this chat by ENS name. After relogin ENS name of this participant will be resolved and when new messages will come from users with ENS names, they will be resolved as well.

#### Expected behavior
ENS names will be resolved

#### Actual behavior
ENS names are not visible.
And if from this state User A start 1-1 chat with one of the participants of chat (for #status i.e. jakub) using his ENS name and then relogin -> as new messages will come, ENS names will be resolved for fetched messages as well. 

### Reproduction

- User A: create new account
- User A: join public chats where ENS name is set for some of participants (i.e. #status) 
- User B with ENS: send new message to public channel. User A still doesn't see ENS names, so the problem is not related to fetching messages.

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: [RC 12](https://ci.status.im/job/status-react/job/release/job/release%252F1.0.x/12/)
- Operating System: Android, iOS

**Comment by churik** [comment]
cc @rachelhamlin 
v1?

**Comment by churik** [comment]
сс @flexsurfer

**Comment by cammellos** [comment]
Is this still an issue? Could not replicate on develop

**Comment by flexsurfer** [comment]
i think it is not consistently replicated , might be related to infura , probably sometimes verification request failed , we could add a retry on error

**Comment by cammellos** [comment]
I can do that, we can retry a few times and then give up

**Comment by yenda** [comment]
I only noticed once that names were not resolved on a new account, but it was actually just delayed and appeared later which is fine, we chose to show messages first and resolved afterward. But indeed adding retries in case of infura error would be nice

**Comment by rachelhamlin** [comment]
Not happening for me on RC3. On one occasion when I loaded #status-dogfooding, Andrey's name was missing and had previously been set. The others were okay. I'm not sure it was this same problem.

**Comment by rachelhamlin** [comment]
v1.1 release label removed because I'm not able to reproduce this, nor hearing reports.

**Comment by flexsurfer** [comment]
it was fixed
