### ISSUE TITLE
Do not show ENS name in profile unless Tx is confirmed

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9912]
# Problem

If my ENS Tx fails, it seems to get stuck in a pending state on my profile, at least for a given session. It would be better that we don't display it on the profile until the Tx is mined.

Another user can register the name while I'm waiting because my Tx has, in fact, failed. 

### Current state
**Success??**
<img src="https://user-images.githubusercontent.com/15470435/73075788-4ab98700-3eef-11ea-86be-b1bc590a94e3.png" width=250/>

**Wait a minute... (What I think is happening based on ENS screen)**
<img src="https://user-images.githubusercontent.com/15470435/73075832-645ace80-3eef-11ea-869c-30a642e94e24.PNG" width=250/>

**What actually happened**
<img src="https://user-images.githubusercontent.com/15470435/73076137-14303c00-3ef0-11ea-87b8-54b8693043c3.PNG" width=250/>

### Preferred implementation

- No ENS name on my profile and I still see `ENS usernames` as my entry point
- Ideally, we 1) add a pending state for the list usernames. It should indicate that a name is pending somewhere on this page. 
- 2) We add a state for a failed transaction. 

**This screen can stay like this until names are confirmed** 
<img src="https://user-images.githubusercontent.com/15470435/73076553-ec8da380-3ef0-11ea-9440-5cd68a30de5b.PNG" width=250/>

**This screen should have a pending and failed Tx state, ideally**
<img src="https://user-images.githubusercontent.com/15470435/73076554-ec8da380-3ef0-11ea-95e7-18c78ff3216a.PNG" width=250/>

**Comment by kmoll** [comment]
I am experiencing this too, although it seems to be more than just a given session.  Is there a way to release the name if the transaction fails?

**Comment by henrystats** [comment]
Issue also affects sharing of personal link. If your ens name is pending, it still generates a link with your pending ens name.

i.e https://join.status.im/u/henrystats.stateofus.eth
