### ISSUE TITLE
Add REP logo for wallet asset

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9920]
# Problem

We're missing the logo for REP in the wallet. 

![image](https://user-images.githubusercontent.com/15470435/73158946-ec232180-4117-11ea-9e35-f7d051e34f4c.png)

Can we use [this image](https://drive.google.com/file/d/1Fize4n35YdJ5hxn8X0cE0I442_vUrIpq/view?usp=sharing) for REP?

**Comment by yenda** [comment]
@errorists do you use some tool to get the different sizes for mobile?

**Comment by errorists** [comment]
generally i do, you can find the assets [here](https://www.dropbox.com/sh/kcayqgdf5z96zl0/AAC7AJlauOSgFUwxU9YjkA3Ea?dl=0)
