### ISSUE TITLE
Messages don't appear in 1-1 chat at first

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9929]
# Bug Report

VIDEO: https://drive.google.com/file/d/1OCCBrg9nExZ_A01RoTtKFOfg4qAUHTtl/view?usp=sharing

## Problem

Messages don't appear in 1-1 chat

#### Expected behavior

Messages appear in 1-1 chat right after pressing send button

#### Actual behavior

Messages don't appear in 1-1 chat

### Reproduction

- Open Status
- Send messages while "connecting"
- Close app
- Open again
- immediately open chat and send messages
- messages don't appear  in chat
- messages appear after some time

**Comment by cammellos** [comment]
This might be fixed, once RC4 is out could you please try upgrading and seeing if it is still there? (I would suggest you wait say 20 minutes with the app open, to flush all outstanding messages to be sent)

**Comment by flexsurfer** [comment]
still can reproduce in RC4 but only for a few messages right after login

**Comment by flexsurfer** [comment]
can be reproduced on new account on ios as well
create account
join public chat (with messages probably)
send message

**Comment by rachelhamlin** [comment]
I don't think this issue is happening on v1, but let's reopen if so.
