### ISSUE TITLE
UI refresh bugs [iOS]

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#994]
- [x] 1.

 
<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/25021873/5fdcd6a6-209c-11e7-9753-75e1119a2edc.jpg />

- [x] 2. 
<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/25021881/6525c1ea-209c-11e7-8a49-97ffbec11a66.jpg />

- [x] 3.
<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/25021883/6aa3845e-209c-11e7-8e46-76db696ed8a8.jpg />

- [x] 4. **FIXED**
<img width=320 src=https://cloud.githubusercontent.com/assets/2364994/25021890/70284108-209c-11e7-9bf9-d89d9a25765e.jpg />

- [ ] 5.
![br](https://cloud.githubusercontent.com/assets/2364994/25021897/7bef84e2-209c-11e7-9a28-c4265f08f5ca.gif)

- [x] 6. back button arrow looks differently in contact's profile and i chat 
![bb](https://cloud.githubusercontent.com/assets/2364994/25021904/859eaf36-209c-11e7-982a-ace40f3b45fe.gif)

**Comment by flexsurfer** [comment]
- [ ] 7. close icon is small in a modal window
![image](https://cloud.githubusercontent.com/assets/11790366/25131559/d74bf540-244e-11e7-8347-f7b0ca3cdeb6.png)
