### ISSUE TITLE
App is trying to reconnect spontaneously to 3 mailservers in the cycle it might take up to 30 sec

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9943]
# Bug Report

## Problem

Sometimes during chatting App trying to reconnect spontaneously to 3 mailservers in the cycle it might take up to 30 sec

#### Expected behavior

Reconnect is fast and hidden from the user

#### Actual behavior

User sees spinners and "connecting" banner up to  30 sec

Logs https://gist.github.com/flexsurfer/80213875d35fb1686fd8b78af8a58ed8

**Comment by yenda** [comment]
Do you still have this issue or was it caused by the spam/24h request?

**Comment by flexsurfer** [comment]
it was caused by high load on mailservers, currently, we  don't have a high load, so I don't have this issue

**Comment by flexsurfer** [comment]
haven't seen this for a while

**Comment by flexsurfer** [comment]
still an issue
