### ISSUE TITLE
Failed to create database after upgrading ios app

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9947]
# Bug Report

![image](https://user-images.githubusercontent.com/11790366/73441588-84591a80-4353-11ea-865f-b74d75eb6b2a.png)

## Problem

Failed to create database after upgrading Ios app

#### Expected behaviour

no errors, it's possible to continue work with the app after upgrade

#### Actual behavior

not possible to sign in after the upgrade

**Comment by errorists** [comment]
just to add to that, on my end after launching the app after upgrade I'm stuck on a blank white screen with a spinner in the middle. nothing happens, it just remains this way. maybe it's because I have FaceID turned on, dunno.

**Comment by flexsurfer** [comment]
yes its because "save password" selected

**Comment by rasom** [comment]
@flexsurfer 
that's when upgrading from which version to which?

**Comment by errorists** [comment]
I had this when going from `rc2->rc3` `rc3->rc4` `rc4->rc5`

**Comment by flexsurfer** [comment]
any version, just upgrade,

**Comment by rachelhamlin** [comment]
Am I right in my understanding that this would be a problem for users going from v1 to v1.1?

**Comment by flexsurfer** [comment]
yes any ios upgrade
