### ISSUE TITLE
Sometimes spinner is shown for every sent message

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9956]
# Bug Report

## Problem

Sometimes spinner is shown for every sent message, even is there is no "connecting" banner, and mailservers is connected

#### Expected behavior

Spinner changed on sent or error after some time

#### Actual behavior

Spinner doesn't dissapear

**Comment by rachelhamlin** [comment]
Do you think it's unrelated to #9928?

**Comment by flexsurfer** [comment]
this one is different, but they some kind of related

**Comment by rachelhamlin** [comment]
Same question as on #9928 - messages are ultimately delivered in this scenario?

**Comment by flexsurfer** [comment]
we don't know for sure, probably yes

**Comment by churik** [comment]
It is resolved in https://github.com/status-im/status-react/pull/10405
