### ISSUE TITLE
Update glossary view

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#9961]
# Problem
Some content doesn't accurately present the concepts, this might lead to confusion. Especially when Smart Contract accounts are introduced in the future.

## Proposed updates
FROM
"account-content": "Your Status account, accessed by the seed phrase that you create or import during onboarding. A Status account can hold more than one Ethereum address, in addition to the one created during onboarding. We refer to these as additional accounts within the wallet.",

TO
"account-content": "You can compare accounts in Status to bank accounts. Like a bank account, an account typically has an address and a balance; You use this account to transact on Ethereum. You can have multiple accounts in your wallet. All accessed by unlocking Status.",

_WHY > Bring content in line with FAQ and remove reference to multiacccount as being Status account._

FROM
"wallet-key-title": "Wallet Key",
"wallet-key-content": "A 64 character hex address based on the Ethereum standard and beginning with 0x. Public-facing, your wallet key is shared with others when you want to receive funds. Also referred to as an “Ethereum address” or “wallet address.”",

TO
"wallet-key-title": "Account address",
"wallet-key-content": "A 64 character hex address based on the Ethereum standard and beginning with 0x. Public-facing, your account address is shared with others when you want to receive funds. Also referred to as an “Ethereum address” or “wallet address.”",

_WHY > Ensure that people don't assume they have only one address, tied to wallet tab._

## Acceptance Criteria
Copy updated to above in https://github.com/status-im/status-react/blob/develop/translations/en.json

## Notes
@3esmit please check if this captures your comments.

**Comment by hesterbruikman** [comment]
cc @errorists @rachelhamlin @Ferossgp

**Comment by 3esmit** [comment]
Chat Key dont gets renamed to Chat ID?  I guess this will require wider change then in glosary, that would include glossary.

**Comment by bluebibi** [comment]
unsubscribe


2020년 2월 8일 (토) 오전 6:49, Ricardo Guilherme Schmidt <notifications@github.com>님이
작성:
