### ISSUE TITLE
Update prices in fiat more frequently

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9962]
# Bug Report

## Problem
Currently, price in fiat updated only on sign in, but app might be opened for a  long time and prices may change

#### Expected behavior

prices are updated more frequently

**Comment by rachelhamlin** [comment]
I don't think this is a blocker. v1.1 perhaps?

**Comment by flexsurfer** [comment]
i still think its a blocked, imagine you want to send 10SNT and status shows price as 1 USD, but the real price is 10USD, i made a super simple fix for v1 , one line , update prices each time wallet tab is opened

**Comment by qfrank** [comment]
would it be better if we can force update via pulling down action?
