### ISSUE TITLE
Upload profile picture with ENS

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9966]
# Feature Issue

We're converting profile photos into a feature of ENS. The primary reason is that profile photos were confusing before—only contacts could see them. In v1, contacts have no other privileges or special relationship.

Photos simply make more sense as part of a user's ENS identity.

However, the more value we build around ENS, the more important it becomes that we allow users the option to pay for their name privately, or at least with a wallet of their choosing. We are prioritizing the option to [remove your name](https://github.com/status-im/status-react/issues/8497) from your chat key for the same release, to offer a measure of control over a user's wallet exposure.

### User Story

As a user, I want to upload a custom photo to my ENS profile so that I can be identified by it in chat.

### Description

These are the options designed by @errorists:
1) User can upload a photo during registration—this is optimal, as the user then pays one network fee in the course of registration.
2) User can upload or change photo at any later point. This requires another Tx and gas. 
3) User can remove a photo they've uploaded.

[Registration flow](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4211%3A2)
[Change or remove photo](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4066%3A7399) (entry point = user profile photo within ENS section)

### Acceptance Criteria

- User can add/change/cancel adding photo during registration
- User can change or remove photo once added, or add one if there is not one
- User can position, crop and preferably pinch to scale image 
- Image requirements? File type?
- IPFS storage

**Comment by 3esmit** [comment]
We could use contenthash to set a JSON typed data into the user, where one of the fields could be profilepic https://github.com/ensdomains/resolvers/blob/master/contracts/profiles/ContentHashResolver.sol
