### ISSUE TITLE
Update the keycard indicator for multiaccounts screen

### ISSUE THREAD

**Issue by Ferossgp** [status-im/status-react#9969]
# Problem

- Let's update the keycard indicator for it to be consistent with the rest of the app;

## Implementation
The keycard indicator is moved to the user photo.

## Acceptance Criteria
Should follow Figma UI https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

**Comment by guylouis** [comment]
this is done
