### ISSUE TITLE
Sliding keyboard on suggested "iCloud Password" (autofill)

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-react#9981]
# Bug Report

## Problem
When I tab on suggested "icloud password" in onboarding/signing a transaction/or anywhere else password is required, the keyboard slides down -> faceID –> slides back.

#### Expected behavior

See figma file for onboarding:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=5991%3A36478
<img width="1806" alt="Screenshot 2020-02-05 at 15 10 32" src="https://user-images.githubusercontent.com/52249767/73849136-ae19b200-4829-11ea-8feb-0711ec0ee4c8.png">

See figma file for wallet:
https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=6003%3A43682
<img width="1623" alt="Screenshot 2020-02-05 at 15 12 03" src="https://user-images.githubusercontent.com/52249767/73849237-e02b1400-4829-11ea-9dae-753327cd98c8.png">

 

#### Actual behaviour

When click on "iCloud password" the keyboard slides down then it comes back.
![RPReplay_Final1580893771](https://user-images.githubusercontent.com/52249767/73844095-28453900-4820-11ea-9ad5-9e4a7e1adbbc.gif)
 

### Reproduction

1. Go to Native iPhone->Settings->Password&Accounts–>Website & App Passwords–>Hit"+"icon to add a password–>
2. Write: Website: discuss.status.im, Username: Your user name, Password: Your Password, Hit "Done"
3. Open fresh new installed Status–>Use seed phrase–>When Status asks for account icloud should recommend you the password from discuss
4. Now your keyboard is jumping too :)

**Comment by churik** [comment]
As two fields of password and confirming password are on the same screen now and taking into account redesign, don't think this issue is relevant for now.
Feel free to reopen.
