### ISSUE TITLE
Improve watching to new blocks (recent transfers state)

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#9987]
# Feature Issue
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story
As a user, I want to see the most recent tx history of my accounts with no delays using as little internet traffic as possible to be able to know the recent state of my accounts. 

### Description

* [ ] the way how we listen to recent blocks should be rewritten so that we do not 
fetch an entire block each time. We can use 
eth_getBalance/eth_transactionsCount/eth_getLogs instead. The number of requests
will increase, but even if we will make hundreds of such requests it will cost
less traffic than eth_getBlockByNumber with all transactions. And we can make
these requests for free as archival node will not be required (reroute them to
cloudflare for instance).
* [ ] also the way how we check recent block can be rewritten so that we alway stay
1-2 blocks behind the "latest" instead of allowing some kind of queuing, as we 
have now. In this case we can avoid unnecessary delays and show actual transfers
state faster (and what's probably more important that delay can be relatively 
stable)
* [ ] (**partially implemented, we do not check blocks while app is in the background**) 
on android we could stop listening to each new block when app is in the
background and check history once per 1-2 minutes. That will also save traffic 
and we still will be able to show PNs with transfers (if we plan to do this).

### Acceptance Criteria
[comment]: # (Rules for the future PR to be accepted.)

### Notes
[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by oskarth** [comment]
This has a big impact on BW right now from what I understand.

From @cammellos 

> Current usage is driven by wallet, around 1MB per minute. That's a constant and does not increase as network increases. It > ignores mobile data settings for now, something we are aware of.
> 
> Another source of bandwidth is disconnection from mailserver, each costs around 250KB, so a few disconnection in a minute > can significantly impact bandwidth.

@andremedeiros @hesterbruikman are you aware of this issue and is there a plan to address it? W.r.t retention from eating up BW, especially in target markets.

**Comment by rasom** [comment]
@cammellos 
So basically what I would do now:
1. Stop watching each block via `eth_getBlockByNumber`, because it is expensive in terms of traffic (we retrieve transactions along with block) and also 99.9% of those calls are in vain.
2. Instead I would just check a range of blocks each N minutes (let's say 20) using eth_getBalance/eth_transactionsCount/eth_getLogs 
3. In case if user sends new transaction I would also start watching each block until tx is confirmed

I just tested this approach and in case if there is no new transactions we send 48 `eth_*` requests in 21m instead of 580 we currently have in develop (no changes on status-go side). And this 48 number can be reduced about two times because some requests are executed more than once on status-go side (same method and parameters).

**Comment by rasom** [comment]
this one is partially implemented already, the rest of it is likely irrelevant. Closing it
