### ISSUE TITLE
Support 3box.io profiles to status users

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9988]
# Feature Issue

Currently Status.im have a very simple profile system, only allowing to set a name and a ens domain (usually username.stateofus.eth). 

3box.io is using OrbitDB (that uses IPFS) and ethereum to authenticate changes in this DB, that can store users profile in a very flexible way. 

### User Story

As a user, I want to have a public profile that I can selectively share with my contacts or with the world. 

### Description

Possible features:
- Public Profile
- User Public Feeds
- privately contact list backup/sync
- (...) 

### Acceptance Criteria

1. Status User profile stored on 3box.io is managed by EIP1581 (non wallet key) 
2. Contacts IDs (other EIP1581 pub keys) are allowed to read user profile

### Notes

Should only be used for information that is not intended to be absolutely private, but for allowing users that want to share public information with other users. 

### References 

3Box SDK: https://github.com/3box/3box-js/ 
IdentityWallet SDK: https://github.com/3box/identity-wallet-js/
Add new keytypes (EIP1581) to the same system: https://github.com/3box/js-3id-blockchain-utils
Docs: https://docs.3box.io/build/wallets/4.-link-an-address-to-the-identity

Orbit DB: https://github.com/orbitdb/orbit-db

**Comment by flexsurfer** [comment]
@3esmit is this related to https://github.com/status-im/status-react/issues/9909 ? cc @rachelhamlin

**Comment by cammellos** [comment]
Please add feature requests to https://discuss.status.im/ , thanks for you input!
