### ISSUE TITLE
Add optional mnemonic salt (password) support as TREZOR plausible deniability

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#9989]
# Feature Issue

Some uses might be using seed phrases salted with a password. Additionally, the Status should support its own variant of plausible deniability feature.

### User Story

As a user I want to use my TREZOR seed phrase that is salted with my password.

As a user I want to show a dummy wallet for a threat forcing me to unlock my wallet.

### Description

The main focus would be only to allow a trezor user to load their seed phrase on Status so they can access their salt protected seed phrase in Status Wallet.

The second effort would be to implement a method of plausible deniability for the wallet, e.g. by default the wallet is never unlocked, and a password is required to unlock it, if the wrong password is given, the wrong wallets are shown. 

### Acceptance Criteria

TREZOR wallets with password should be supported in Status.im

### Notes

MyCrypto.com supports this. https://twitter.com/3esmit/status/1225031530080284673

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
 Added `recheck` label for easy finding that one in case of need.
