### ISSUE TITLE
Tap in input filed has no effect if message was sent with Enter [ui-refresh]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#999]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User sent a message in 1-1 chat by tapping on Enter. Message was sent. However, if user taps in input field again to start typing next message then nothing happens and keyboard is not shown 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If user taps on input field then keyboard is shown, so user can start typing text
#### Actual behavior
[comment]: # (Describe what actually happened.)
If user taps in input field then keyaboard is snot show, so it's not possible to type a message
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Smk1YWEzUWVnR2c
- Open Status and login
- Open 1-1 chat
- type "one" and tap on Enter in device keyboard
- As soon as message is sent tap in input field again

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.5-38-gdd2c3aa+
* Operating System: Android 7.0, real device Samsung Galaxy S7

**Comment by alwx** [comment]
Fixed in #1011
