### ISSUE TITLE
QR code won't close from wallet screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9992]
# Bug Report

## Problem

Reported by Jarrad:

When QR code is opened from wallet > individual account > share button, and back button is then pressed, QR code does not close and remains on wallet overview.

#### Expected behavior

QR code panel is closed when user goes back. 

#### Actual behavior

QR code remains on wallet overview screen.

#### Notes

Can not reproduce on iOS. 

### Reproduction

- Go to wallet
- Open an individual wallet
- Press the share button to bring up QR code
- Press back button

### Additional Information

Samsung Galaxy Fold on RC 9

**Comment by flexsurfer** [comment]
hardware back button ? yeah to fix that, popover should be a screen , and bottom sheet  as well @errorists @Ferossgp

**Comment by flexsurfer** [comment]
its even worst with sending tx from chat, you can open tx bottom sheet, and go back to chats screen, and dunno what will happen when you send this tx from chats screen

**Comment by flexsurfer** [comment]
could be fixed here : https://github.com/status-im/status-react/pull/9945
